Do not allow RTLO char in filenames
nextcloud/server pull request #10030
Opened 2018-06-27 20:57 UTC by rullzer

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-06-28 07:21 UTC, ChristophWurst commented on tests/lib/Files/PathVerificationTest.php
> +		$this->expectException(InvalidPathException::class);
Aren't you throwing an `InvalidCharacterInPathException` instance?

2018-06-28 07:22 UTC, ChristophWurst commented on tests/lib/Files/PathVerificationTest.php
> +		$this->expectException(InvalidPathException::class);
I see that it's a [specialization](https://github.com/nextcloud/server/blob/a077c129c8006e9cd9b864c343f49181fe562592/lib/public/Files/InvalidCharacterInPathException.php) but I just wanted to bring it up in case this wasn't intentional :wink:

2018-06-28 07:47 UTC, nickvergessen commented
Hmm I guess it's fine, but of course it could cause problems in RTL countries if people name their files in their language, which is why I didn't plan to do this yet. Just imagine you would have to name your files `tohsneercs` all the time  instead of `screenshot`

2018-06-28 07:52 UTC, nickvergessen requested changes

2018-06-28 07:52 UTC, nickvergessen commented on lib/private/Files/Storage/Common.php
> +		if (mb_strpos($fileName,  mb_chr(8238, 'utf8')) !== false) {
`mb_chr` is php 7.2+ so we can't use it

2018-06-28 07:55 UTC, rullzer commented on lib/private/Files/Storage/Common.php
> +		if (mb_strpos($fileName,  mb_chr(8238, 'utf8')) !== false) {
https://github.com/nextcloud/3rdparty/blob/master/symfony/polyfill-mbstring/bootstrap.php#L56

2018-06-28 07:56 UTC, rullzer commented
> Hmm I guess it's fine, but of course it could cause problems in RTL countries if people name their files in their language, which is why I didn't plan to do this yet. Just imagine you would have to name your files tohsneercs all the time instead of screenshot

mmm fair enough. Maybe then we should just forbid the char anywhere but the first char?

2018-06-29 16:12 UTC, jaller94 commented
I don't see an issue connected to this PR.
Why does this char need to be disallowed? What is broken?
How do the operating systems handle the RTLO char in filenames?

2018-07-26 15:08 UTC, MorrisJobke commented
As @nickvergessen already wrote in https://github.com/nextcloud/server/issues/10410#issuecomment-408112264: maybe it's better to not go for that approach.

2018-07-29 09:02 UTC, alexara commented
If you allow RTLO, please consider, that it can be used to spoof file names by malicious users.

> For example, the file name with ThisIsRTLOfileexe.doc is actually ThisIsRTLOfiledoc.exe, which is an executable file with a U+202e placed just before “doc.”

Source: https://resources.infosecinstitute.com/spoof-using-right-to-left-override-rtlo-technique-2/

2018-07-30 07:00 UTC, nickvergessen commented
yes @alexara that was exactly why this PR was started. But we asked users of RTL languages for feedback and they are using mixed and RTL only names, so we would cause a lot of problems for them, to prevent fraud by your colleagues and friends, people that share the instance with you.

Which is why I vote for *no*

2018-09-12 10:00 UTC, closed without merging