Comments on Token entities and controller
nextcloud/server pull request #10075
Opened 2018-07-02 09:18 UTC by liamdennehy

Add support for comments on Token entities and controller.

* No database migration file included as I have no idea how to start.
* No front-end implementation as I expect some design needs to happen first.

2018-07-02 09:45 UTC, MorrisJobke commented
> No database migration file included as I have no idea how to start.

@nickvergessen Could you document the process of creating a migration in https://docs.nextcloud.com/server/13/developer_manual/app/index.html#storage ?

2018-07-02 10:48 UTC, liamdennehy commented
Added a migration to source branch by copying a "core" sample in a [blog post](https://www.schilljs.com/2017/09/08/migrations-for-nextcloud-apps.html) by @nickvergessen. Still can't figure out how to generate a migration for "core" schema:
```
apache@laptop /src/nextcloud $ ./occ migrations:generate core 14001
                                          
  Failed to generate new migration step.  
                                          
migrations:generate <app> <version>
```

2018-07-02 11:19 UTC, nickvergessen commented
Did you miss to make the directory writable? That would be the only reason why it could fail...

2018-07-04 08:11 UTC, liamdennehy commented
Juggling permissions between apache and my own account is tripping me up constantly. Migration added to the PR.

2018-07-11 13:13 UTC, MorrisJobke commented
@nickvergessen @ChristophWurst @rullzer It would be nice to have for 14, right?

2018-07-11 22:06 UTC, liamdennehy commented
Are we happy with the random string generator to test both complex strings and truncation? If so, should this move to a single function (right now it's duplicated), and if not replace it with a static string (constant) to still test truncation? 05489043fa379f5837f96cadeace801c64c35ba7

2018-07-20 10:16 UTC, nickvergessen requested changes

2018-07-20 10:16 UTC, nickvergessen commented on core/Migrations/Version14000Date20180702122915.php
> +			'notnull' => true,
false please, otherwise empty string creates an error on oracle/postgres

2018-07-20 10:16 UTC, nickvergessen commented on core/Migrations/Version14000Date20180702122915.php
> +	public function postSchemaChange(IOutput $output, \Closure $schemaClosure, array $options) {
remove

2018-07-20 10:16 UTC, nickvergessen commented on core/Migrations/Version14000Date20180702122915.php
> +	public function preSchemaChange(IOutput $output, \Closure $schemaClosure, array $options) {
remove

2018-07-20 10:16 UTC, nickvergessen commented on lib/private/Authentication/Token/DefaultToken.php
> +		is_null($comment) && $comment = "";
what is this? its evaluating a bool which is not used at all

2018-07-20 10:16 UTC, nickvergessen commented on lib/private/Authentication/Token/DefaultToken.php
> +	public function setComment(string $comment = "") {
single quotes

2018-07-20 10:16 UTC, nickvergessen commented on lib/private/Authentication/Token/PublicKeyToken.php
> + 		is_null($comment) && $comment = "";
same here, looks wrong

2018-07-20 10:16 UTC, nickvergessen commented on lib/private/Authentication/Token/PublicKeyToken.php
> +	public function setComment(string $comment = "") {
single quotes

2018-07-20 10:16 UTC, nickvergessen commented on tests/lib/Authentication/Token/DefaultTokenTest.php
> +		$tComment = $this->generateRandomString(300);
use `$this->getUniqueID()` instead

2018-07-20 10:16 UTC, nickvergessen commented on tests/lib/Authentication/Token/PublicKeyTokenTest.php
> +		$tComment = $this->generateRandomString(300);
use `$this->getUniqueID()` instead

2018-07-23 07:14 UTC, liamdennehy commented on core/Migrations/Version14000Date20180702122915.php
> +			'notnull' => true,
The setter turns an emtpy value into a zero-length string, so no persists should enter a null, while the getter turns nulls into a zero-length string. This is here for a db upgrade adding the column and tolerating nulls. Will remove anyway, but curious why this is not approach isn't sufficient.

2018-07-23 07:18 UTC, liamdennehy commented on lib/private/Authentication/Token/DefaultToken.php
> +	public function setComment(string $comment = "") {
Here's the setter that has a default of `''`, allowing nulls in the table.

Replaced with single-ticks. Any guidance on why this is preferred?

2018-07-23 07:20 UTC, nickvergessen commented on core/Migrations/Version14000Date20180702122915.php
> +			'notnull' => true,
You are disallowing null-values, for oracle or postgres (I dont know right now) empty/zero-lnegth string is saved as null, so that will fail

2018-07-23 07:35 UTC, liamdennehy commented on lib/private/Authentication/Token/PublicKeyToken.php
> + 		is_null($comment) && $comment = "";
done

2018-07-23 07:35 UTC, liamdennehy commented on lib/private/Authentication/Token/PublicKeyToken.php
> +	public function setComment(string $comment = "") {
done

2018-07-23 07:40 UTC, liamdennehy commented on tests/lib/Authentication/Token/PublicKeyTokenTest.php
> +		$tComment = $this->generateRandomString(300);
done, and removed function

2018-07-23 07:40 UTC, liamdennehy commented on tests/lib/Authentication/Token/DefaultTokenTest.php
> +		$tComment = $this->generateRandomString(300);
done, and removed function

2018-07-23 07:41 UTC, liamdennehy commented on lib/private/Authentication/Token/DefaultToken.php
> +		is_null($comment) && $comment = "";
Only if underlying db allows nulls, which you've advised against. Removed.

2018-07-23 09:43 UTC, liamdennehy commented on core/Migrations/Version14000Date20180702122915.php
> +	public function postSchemaChange(IOutput $output, \Closure $schemaClosure, array $options) {
Done

2018-07-23 09:43 UTC, liamdennehy commented on core/Migrations/Version14000Date20180702122915.php
> +	public function preSchemaChange(IOutput $output, \Closure $schemaClosure, array $options) {
Done

2018-07-23 09:44 UTC, liamdennehy commented
Apologies if units fail, for some reason phpunit is complaining about versions on my workstation

2018-07-23 10:07 UTC, ChristophWurst commented
@liamdennehy what is this comment used for? Do we have a ticket/feature this is needed for?

2018-07-23 10:54 UTC, MorrisJobke commented
> Apologies if units fail, for some reason phpunit is complaining about versions on my workstation

We only support 6.5.x as of now and not yet 7.x+

2018-07-24 08:34 UTC, ChristophWurst commented
Thank you, @liamdennehy. I'm with @juliushaertl [on this](https://github.com/nextcloud/server/issues/8443#issuecomment-401716771). I'd also prefer to just have the label editable than having two labels.

2018-07-24 13:41 UTC, MorrisJobke commented
@ChristophWurst @nickvergessen Let's move this to 15, okay?

2018-09-05 14:50 UTC, ChristophWurst commented
Can we close this? I'm still convinced we should use the existing columns rather than adding a second one for the description. See https://github.com/nextcloud/server/pull/10075#issuecomment-407326905.

2018-09-13 07:28 UTC, nickvergessen commented
I agree.

2018-09-13 07:28 UTC, closed without merging