Public interfaces for dashboard app
nextcloud/server pull request #10222
Opened 2018-07-12 16:46 UTC by daita

2018-07-12 18:59 UTC, rullzer submitted a review, later dismissed

2018-07-12 18:59 UTC, rullzer commented on lib/public/Dashboard/IDashboardWidget.php
> +
Licence header

2018-07-12 18:59 UTC, rullzer commented on lib/public/Dashboard/IDashboardWidget.php
> +	public function getId();
NC14 is >php 7.0. So you can use return types

2018-07-12 18:59 UTC, rullzer commented on lib/public/Dashboard/IDashboardWidget.php
> +<?php
strict typing since we are >7.0 anyway

2018-07-13 00:05 UTC, daita commented on lib/public/Dashboard/IDashboardWidget.php
> +	public function getId();
can I use : void ? (php 7.1)

2018-07-13 11:28 UTC, daita commented
@rullzer: please have a look to the asked edit

2018-07-16 08:17 UTC, nickvergessen commented on lib/public/Dashboard/Model/IWidgetEvent.php
> +	public function __construct(string $widgetId);
I wouldn't add the constructor to the interfaces.
Just call `setWidgetId` instead

2018-07-17 11:51 UTC, juliushaertl commented
@daita You will also need to adjust the following xsd files to make the dashboard section valid in the appinfo.xml:

https://github.com/nextcloud/server/blob/master/resources/app-info-shipped.xsd
https://github.com/nextcloud/server/blob/master/resources/app-info.xsd

And the app store needs those updates as well.

2018-07-17 11:55 UTC, juliushaertl commented
Just a general thing, when we add new sections to the appinfo.xml like <dashboard> for this case, does this break apps that also support versions previous to 14? 

The app store only has one version-independent file to validate the appinfo, so that should work fine, but does the server also checks for a valid appinfo at some point?

2018-07-17 14:44 UTC, nickvergessen commented
Yes the app check-code checks it, but additional stuff is not a problem as far as I know.
Only if you have stuff, which is not parsing valid, it will cry

2018-07-17 21:57 UTC, MorrisJobke commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * @return string
Missing `@since 14.0.0` on the methods and the interface.

2018-07-17 21:57 UTC, MorrisJobke commented on lib/public/Dashboard/IDashboardWidget.php
> +<?php declare(strict_types=1);
Put the `declare()` on a new line.

2018-07-17 22:00 UTC, MorrisJobke commented
It's a bit late for that ... freeze was on Friday ... at least for the server PR.

And also it was never brought up to be needed for 14. :/

2018-07-17 22:06 UTC, jancborchardt commented
No need to rush in the dashboard, no? We can merge it very early for 15, and then properly work on adding endpoints to the different apps and have the Dashboard app use those, like any other app.

2018-07-17 22:12 UTC, daita commented
Well, you know. After working on something else for months and finally having few days to do something fun. But I get it; @nickvergessen already told me last week that I should not waste my time on it.

So, no rush.

2018-09-01 17:05 UTC, daita commented
So, ready for NC15.

@nickvergessen : Added also a IDashboardManager that can be called with Automatic DI so there is no more API, just call the right method from the dashboardManager, that will check if app is installed or not.

2018-09-03 12:46 UTC, nickvergessen commented on lib/private/Dashboard/DashboardManager.php
> +	) {
opsy

2018-09-03 12:47 UTC, nickvergessen commented on resources/app-info-shipped.xsd
> +    </xs:complexType>
this needs to go to the appstore too

2018-09-05 15:57 UTC, ChristophWurst submitted a review, later dismissed
Some nitpicks. Please also make sure you have a line break at the end of each file (as github shows here) to be consistent with our other source files.

Thanks!

2018-09-05 15:57 UTC, ChristophWurst commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * @return array
Please add more documentation to these methods. What are they supposed to return? `array` is very generic :wink:

2018-09-05 15:57 UTC, ChristophWurst commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * @return array
same as above

2018-09-05 15:57 UTC, ChristophWurst commented on lib/public/Dashboard/Model/IWidgetRequest.php
> +	public function __construct(string $widgetId);
the interface determines the constructor interface? This doesn't seem right :see_no_evil:

2018-09-05 15:57 UTC, ChristophWurst commented on lib/public/Dashboard/Model/IWidgetRequest.php
> +	 * @param string $request
what kind of request is this string?

2018-09-05 15:57 UTC, ChristophWurst commented on lib/public/Dashboard/Model/IWidgetSettings.php
> +	public function __construct(string $widgetId, string $userId);
Please remove this. Same issue as above.

2018-09-06 19:55 UTC, rullzer commented on resources/app-info.xsd
> +                        maxOccurs="unbounded"/>
that doesn't look right.

2018-09-06 19:55 UTC, rullzer commented on resources/app-info-shipped.xsd
> +            maxOccurs="unbounded"/>
same here

2018-09-13 07:35 UTC, nickvergessen commented on lib/private/Dashboard/DashboardManager.php
> +			return \OC::$server->query($service);
you can inject `IServerContainer` in your constructor. Then you can also better unit test this.

2018-10-04 07:55 UTC, daita commented
:ping_pong: 

Would be great to go on with this one, as it is a blocker to work on the dev of widgets for 15.
(I know it's missing tests, this would come later)

2018-10-08 07:18 UTC, MorrisJobke commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * ];
A template object would be nice, because it is automatically properly typed and has then proper autocompletion as well. 😉

2018-10-08 07:18 UTC, MorrisJobke commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * 	  'push' => (string) JavaScript function to be called on push event
A settings object would be nice instead of a multidimensional array. 🤔

2018-10-08 07:19 UTC, MorrisJobke commented on lib/public/Dashboard/Model/IWidgetRequest.php
> +	 * @param string $request
@daita 🏓

2018-10-08 07:19 UTC, MorrisJobke commented on lib/public/Dashboard/Model/IWidgetSettings.php
> +	public function __construct(string $widgetId, string $userId);
@daita 🏓

2018-10-08 07:21 UTC, MorrisJobke reviewed
Beside the comments it looks good 👍

2018-10-08 07:37 UTC, ChristophWurst commented
Could you briefly describe how the new interfaces fit together please? I still haven't quite understood how this is supposed to work. Would it make sense to allow more than one entry in `info.xml` per app?

2018-10-08 07:40 UTC, ChristophWurst commented
- [ ] Since the info schema here is a copy of the appstore one, we should get https://github.com/nextcloud/appstore/pull/567 in first.

2018-10-08 07:41 UTC, ChristophWurst commented
> Could you briefly describe how the new interfaces fit together please?

Sorry for being so nitpicky here, but since this will be a quite large public API of our server which we hope lots of apps use, I really want this to be as easy to use as possible (also in regards to documentation).

2018-10-09 07:03 UTC, daita commented on lib/public/Dashboard/Model/IWidgetSettings.php
> +	public function __construct(string $widgetId, string $userId);
saw that ... removed.

2018-10-09 07:03 UTC, daita commented on lib/public/Dashboard/IDashboardWidget.php
> +	 * ];
moved to objects in various spot, pushed. Will comment during the day.

2018-10-10 08:29 UTC, daita commented
All commented and looking good. 

Please review !

2018-10-10 08:37 UTC, ChristophWurst requested changes

2018-10-10 08:37 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
please use the `::class` syntax, this makes finding class usages and refactoring later a lot easier :+1:

2018-10-10 08:37 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$eventsService = $this->getService('\OCA\Dashboard\Service\EventsService');
same

2018-10-10 08:37 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$eventsService = $this->getService('\OCA\Dashboard\Service\EventsService');
same

2018-10-10 08:37 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$eventsService = $this->getService('\OCA\Dashboard\Service\EventsService');
same

2018-10-10 08:37 UTC, ChristophWurst commented on lib/public/Dashboard/Model/IWidgetRequest.php
> +	 * @param string $request
:man_shrugging: :ping_pong:

2018-10-10 08:37 UTC, ChristophWurst commented on lib/public/Dashboard/Model/IWidgetTemplate.php
> +	 * JavaScript function to be called when loading the widget on the
how will that function be invoked? Does it have to exist globally?

2018-10-10 08:37 UTC, ChristophWurst commented on lib/private/Dashboard/Model/WidgetTemplate.php
> +	public function getCss(): array {
how will this CSS be loaded? Is this property the actual CSS contents or just the URL?

2018-10-10 08:49 UTC, daita commented on lib/public/Dashboard/Model/IWidgetTemplate.php
> +	 * JavaScript function to be called when loading the widget on the
it does not have to exist globally, it is called by the app

2018-10-10 08:52 UTC, nickvergessen commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
Would require another try-catch in here of course, in case the dashboard app is not here.

2018-10-10 08:55 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
Why would it? `::class` is simply replaced by the FQCN (string) by the interpreter.

2018-10-10 08:59 UTC, nickvergessen commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
I thought this would invoke autoloading and therefor throw? 🤷

2018-10-10 09:04 UTC, daita commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
The thing is that I am not sure the app is available at this point, and calling the ::class does not clean enough

2018-10-10 09:18 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +		$widgetsService = $this->getService('\OCA\Dashboard\Service\WidgetsService');
```
$ php -a
Interactive shell

php > echo Joas::class;
Joas
```

2018-10-10 10:42 UTC, rullzer reviewed
I don't see a reason for much of this implementation to be in the server. Like the actual implementation of a lot of those classes can just be in the dashboard app itself right?

2018-10-10 10:42 UTC, rullzer commented on lib/private/Dashboard/Model/WidgetSetting.php
> +	public function __construct($type = '') {
typehint

2018-10-10 10:42 UTC, rullzer commented on resources/app-info-shipped.xsd
> +    </xs:complexType>
More general why is this needed here? I don't see it being used yet.

2018-10-10 10:49 UTC, ChristophWurst commented
General note: you could and probably should remove most of the setters. How values are set in the implementation is not a concern of the server or other components, these are internals. All that matters to the server is how to get values (css, script, HTML, function references), right? That would shrink the interface sizes *a lot*.

2018-10-10 11:00 UTC, ChristophWurst commented
- [ ] Unclear: How do `IWidgetSetting` and `WidgetSettings` fit together? Why is there an implementation for it, if there's no API to get an instance of the interface? This only makes sense if there is some kind of factory method to obtain an instance. Same goes for `WidgetSetup`
- [ ] Unclear: Are `IWidgetSetup`, `IWidgetSetting` and `IWidgetTemplate` meant to be implemented by other apps? Do we rely on them being serializable? Then the `JsonSerializable` should be an interface those interfaces extend.

2018-10-10 12:21 UTC, ChristophWurst commented on lib/public/Dashboard/Service/IEventsService.php
> +	 * @return mixed
`IWidgetEvent`?

2018-10-12 06:54 UTC, ChristophWurst requested changes
Looks a lot better :+1: 

Let's move the implementations to the dashboard app. I don't think they should be in the server as they aren't even used directly.

Nitpick: `@see WidgetSetting` is a bit misleading. Not sure what it should tell me. It's also a bit misplaced in the interfaces because that would point to the private implementation. All usage should be documented in the public interfaces though :wink:

2018-10-12 06:54 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +	private $container;
unused

2018-10-12 06:54 UTC, ChristophWurst commented on lib/private/Dashboard/DashboardManager.php
> +	private $appManager;
unused

2018-10-12 06:54 UTC, ChristophWurst commented on lib/private/Dashboard/Model/WidgetSetting.php
> +class WidgetSetting implements JsonSerializable {
I think this implementation can be safely move to the dashboard app

2018-10-12 06:54 UTC, ChristophWurst commented on lib/private/Dashboard/Model/WidgetSetup.php
> +class WidgetSetup implements JsonSerializable {
I think this implementation can be safely move to the dashboard app

2018-10-12 06:54 UTC, ChristophWurst commented on lib/private/Dashboard/Model/WidgetTemplate.php
> +class WidgetTemplate implements JsonSerializable {
I think this implementation can be safely move to the dashboard app

2018-10-12 08:06 UTC, daita commented
@ChristophWurst 

- I removed the unused variable from DashboardManager

- WidgetSetting, WidgetSetup and WidgetTemplate are created by the app that generate the widget, so it should stays here. This should be documented in the IDashboardWidget

2018-10-12 08:16 UTC, ChristophWurst commented
> WidgetSetting, WidgetSetup and WidgetTemplate are created by the app that generate the widget, so it should stays here. This should be documented in the IDashboardWidget

WidgetSettings is not used outside the private namespace. Hence it must not be used by apps.

`IDashboardWidget::getWidgetSetup` returns a `WidgetSetup`, which violates the public/private API separation. It should instead return an `IWidgetSetup`. Fixing this will effectively make the `WidgetSetup` implementation independent of server and apps, hence moving it to the dashboard app is fine/recommended.

2018-10-12 08:20 UTC, ChristophWurst commented
>     * WidgetSetting, WidgetSetup and WidgetTemplate are created by the app that generate the widget, so it should stays here. This should be documented in the IDashboardWidget

If a construct (class/interface) is used by an app, it has to be a public API. There are two possible use cases:

* The server only cares about an objects methods: create an interface that is implemented in an app's class.
* The app should extend an existing (potentially abstract) class: export the class in the public API
* The app use objects generated by the server or dashboard app: extract an interface from those interfaces, export them in the public API and provide factory classes/methods to create the objects as public API.

2018-10-12 11:14 UTC, ChristophWurst commented
After a bit of discussion I think I've finally understood how the different components will be used. I created a little diagram that outlines where certain classes/interfaces live:
![bildschirmfoto von 2018-10-12 13-08-30](https://user-images.githubusercontent.com/1374172/46866121-5f6c2b80-ce20-11e8-919f-d283b52fae03.png)

This works for @daita and clearly separates what should be in server/dashboard and other apps. This removes and dependency from server on the dashboard app. The implementation part in server (esp the private part) is minimal. The three classes for setup, settings and template were deliberately moved to OCP as classes as they are simple models (or better *data transfer objects*).

2018-10-12 14:37 UTC, rullzer commented
> After a bit of discussion I think I've finally understood how the different components will be used. I created a little diagram that outlines where certain classes/interfaces live:
> ![bildschirmfoto von 2018-10-12 13-08-30](https://user-images.githubusercontent.com/1374172/46866121-5f6c2b80-ce20-11e8-919f-d283b52fae03.png)
> 
> This works for @daita and clearly separates what should be in server/dashboard and other apps. This removes and dependency from server on the dashboard app. The implementation part in server (esp the private part) is minimal. The three classes for setup, settings and template were deliberately moved to OCP as classes as they are simple models (or better _data transfer objects_).

Yes makes sense.
As some of the classes are only tiny and there to transport data. I would like to make the getters and setters at least final. We can always losen this later. But lets start from a strict implementation.

2018-10-15 13:48 UTC, rullzer approved these changes
Ok I think it is time to get this in.
It looks sane to me.

Lets see how far we get.
@daita could you squash your commits?

2018-10-15 15:31 UTC, ChristophWurst requested changes
Wasn't the plan to have `WidgetSettings`, `WidgetSetup` and `WidgetTemplate` in OCP? They're in the private namespace right now.

2018-10-15 15:42 UTC, ChristophWurst approved these changes
Looks good now!

You probably have to run `./build/autoloaderchecker.sh` to make CI happy.

Also, please make squash this and make this a single commit change :wink:

2018-10-15 16:40 UTC, MorrisJobke commented
CI says no: https://drone.nextcloud.com/nextcloud/server/11524/93

2018-10-15 17:01 UTC, ChristophWurst requested changes
Please remove additional files and rerun autoloader command

2018-10-15 17:01 UTC, ChristophWurst commented on lib/composer/composer/autoload_classmap.php
> +    'OCP\\Dashboard\\Model\\IWidgetRequest' => $baseDir . '/lib/public/Dashboard/Model/IWidgetRequest.php',
interfaces were removed

2018-10-15 17:16 UTC, ChristophWurst approved these changes
Nvm the last review, I was confused by the interface names it seems

2018-10-15 18:56 UTC, merged