Adjusts the files multi select header width
nextcloud/server pull request #10331
Opened 2018-07-22 09:45 UTC by weeman1337

Just a tiny style adjustment to align the files multi select header.

2018-07-23 16:56 UTC, skjnldsv commented on apps/files/css/files.scss
> +	left: 300px; /* sidebar */
Please use the proper variable :)
`$navigation-width`

2018-07-23 16:56 UTC, skjnldsv requested changes
Please use the proper variable :)
`$navigation-width`

2018-07-23 17:00 UTC, weeman1337 commented
@skjnldsv done. I wasn't sure if I can use it, because it's located under `core` and the other style file is under `app/files`. So the core variables can be used from any app shipped by default?

2018-07-23 17:01 UTC, skjnldsv commented
You rocks! :)
Also, now that you're a contributor, you should be able to directly create branches from the nextcloud/server repo ;)

2018-07-23 17:01 UTC, skjnldsv approved these changes

2018-07-23 17:03 UTC, skjnldsv commented
> So the core variables can be used from any app shipped by default?

Any variable used in variables.scss is appended to the compilation of the file, so you're free to use the variables directly yes :)
Note though that we deprecated the use of the scss variables for 15 in favor of css4 variables. So the variables.scss file won't be appended to the scss files anymore in the next version (15)

2018-07-24 08:48 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-07-24 08:48 UTC, merged