make file cache updates more robust
nextcloud/server pull request #10397
Opened 2018-07-25 15:13 UTC by schiessle

Only update the encrypted version after the write operation is finished and the stream is closed

With Amazon S3 as primary storage it happened that we tried to update the "encryption version" before the file was added to the file cache which lead to a wrong version number. By updating the version only after the stream was closed I could solve the issue.

@icewind1991 please have a look if this makes sense. Thanks!

2018-07-31 10:19 UTC, rullzer approved these changes
Makes sense. but I'd love for @icewind1991 to have a look

2018-07-31 10:25 UTC, schiessle commented
@rullzer done

2018-08-06 13:30 UTC, icewind1991 commented
I would prefer if it used a `CallbackWrapper` instead and update the cache from the close callback, that way seems a bit cleaner to me and less mixing on concerns.

(you can use the write callback to set the `$fileUpdated` flag)

2018-08-07 20:13 UTC, schiessle commented
@icewind1991 I agree with you in general. But as I want to backport it to 13 as well I would like to keep the fix as small as possible:

Suggestion: Let's merge this for 14 and backport it for 13  and I will do a follow up PR for master (15) to add a CallbackWrapper.

2018-08-08 13:54 UTC, icewind1991 requested changes

2018-08-08 13:54 UTC, icewind1991 commented on tests/lib/Files/Stream/EncryptionTest.php
> +		$cache->expects($this->any())->method('update')->with(5, ['encrypted' => 3, 'encryptedVersion' => 3]);
change this to `$this->once()` please

2018-08-08 13:54 UTC, icewind1991 commented
> Suggestion: Let's merge this for 14 and backport it for 13 and I will do a follow up PR for master (15) to add a CallbackWrapper.

Sounds good to me

2018-08-08 16:25 UTC, schiessle commented on tests/lib/Files/Stream/EncryptionTest.php
> +		$cache->expects($this->any())->method('update')->with(5, ['encrypted' => 3, 'encryptedVersion' => 3]);
It is not possible the stream, created in the method is used in various places. Sometimes the method is never called and some tests uses the instance multiple times so it is used more then once. All I want to make sure is that every time it is called, it should be called with the right parameters.

2018-08-08 16:27 UTC, schiessle commented
Let's get this in for the beta3 so that it gets some test coverage...

2018-08-08 16:27 UTC, merged

2018-08-20 12:11 UTC, MorrisJobke commented
@schiessle Could you prepare the backport?