Refactor secure randomness check
nextcloud/server pull request #10422
Opened 2018-07-27 10:05 UTC by Hecke29

closes #5530

2018-07-27 10:40 UTC, go2sh commented
You don't need to update every translation file. It's done automatically.

2018-07-27 10:42 UTC, Hecke29 commented
@go2sh Do I have to execute some script to update them or just remove the commit entirely?

2018-07-27 11:58 UTC, go2sh commented
There is a bot for the translations. You have to do nothing.

2018-07-27 11:59 UTC, Hecke29 commented
Removed the commit with those translations 👍

2018-07-30 08:58 UTC, nickvergessen requested changes

2018-07-30 08:58 UTC, nickvergessen commented on settings/Controller/CheckSetupController.php
> +								SecureRandom $secureRandom) {
Should use the interface `OCP\Security\ISecureRandom`

2018-08-02 12:47 UTC, Hecke29 commented
@nickvergessen done

2018-08-24 14:58 UTC, closed without merging