do not trigger counting on LDAP
nextcloud/server pull request #10610
Opened 2018-08-09 11:27 UTC by blizzz

1. have LDAP enabled
2. go to user management

Expected:
* no user count for "Everyone"

Actual:
* waiting, then a high number :scream: 

this fixes it.

(Yes, it also mixed OCA space into OC, it was already the case though :speak_no_evil: :see_no_evil: )

2018-08-09 11:31 UTC, ChristophWurst commented
> (Yes, it also mixed OCA space into OC, it was already the case though speak_no_evil see_no_evil )

Noted ✍️.

2018-08-10 09:01 UTC, blizzz commented
@juliushaertl which number to do you refer to? in the sidebar, none will be shown.

2018-08-10 09:53 UTC, juliushaertl commented
> @juliushaertl which number to do you refer to? in the sidebar, none will be shown.

Yes, at least on my test instance it shows the number of local users is shown (for the everyone group). But that is a small design issue we can fix afterwards.

> Do we also have that slow counting issue with other user backends? Then we should aim for a more general approach like disable counting for all external user backends for example.

At least user_saml app doesn't implement the countUsers action on the UserBackend so it will not be triggered there. I'm fine with this for now. We can still find a more generic way if we encounter further issues with other backends.

2018-08-10 09:53 UTC, juliusknorr approved these changes

2018-08-10 09:54 UTC, juliusknorr requested changes

2018-08-10 09:54 UTC, juliushaertl commented on settings/Controller/UsersController.php
> +use OCA\User_LDAP\User_Proxy;
Not sure about this, it also seems to work with the user_ldap app enabled. Is it always available though autoloading or are there cases when this might fail?

2018-08-10 10:13 UTC, blizzz commented
> > @juliushaertl which number to do you refer to? in the sidebar, none will be shown.

> Yes, at least on my test instance it shows the number of local users is shown (for the everyone group). But that is a small design issue we can fix afterwards.

This should not be the case. The counting goes per general user manager, and it should not happen at all.


>>    Do we also have that slow counting issue with other user backends? Then we should aim for a more general approach like disable counting for all external user backends for example.

> At least user_saml app doesn't implement the countUsers action on the UserBackend so it will not be triggered there. I'm fine with this for now. We can still find a more generic way if we encounter further issues with other backends.

We should aim for a proper way, yes, it's just it is a bit late for 14 to introduce new Interfaces, e.g.

2018-08-10 10:15 UTC, blizzz commented on settings/Controller/UsersController.php
> +use OCA\User_LDAP\User_Proxy;
When I tested it, it worked for me with both user_ldap enabled and disabled. In the logic, the class is only referred to when user_ldap was found enabled.

2018-08-10 12:01 UTC, juliushaertl commented on settings/Controller/UsersController.php
> +use OCA\User_LDAP\User_Proxy;
Ok fine by me then, worked here as well.

2018-08-10 12:59 UTC, rullzer commented
There is an interface for groups. https://github.com/nextcloud/server/tree/master/lib/public/Group/Backend

2018-08-10 13:13 UTC, blizzz commented on settings/Controller/UsersController.php
> +use OCA\User_LDAP\User_Proxy;
@juliushaertl mind updating your review?

2018-08-10 13:23 UTC, juliusknorr approved these changes

2018-08-10 13:35 UTC, rullzer commented on settings/Controller/UsersController.php
> +			$this->userManager->getBackends();
what is this doing here?

2018-08-10 13:38 UTC, blizzz commented on settings/Controller/UsersController.php
> +			$this->userManager->getBackends();
chilling around. thanks for the catch.

2018-08-10 18:54 UTC, rullzer approved these changes
Code makes sense. :elephant:

2018-08-10 18:54 UTC, merged