Fixes more apps menu and settings/user menu positions
nextcloud/server pull request #10723
Opened 2018-08-16 17:10 UTC by weeman1337

* Sets the more apps menu container a width of 0. There is now no risk to catch clicks.
![image](https://user-images.githubusercontent.com/6216686/44223338-a4107900-a187-11e8-89c3-fbab6b2bccfd.png)

closes #10716

* Also tweaks the settings/user menu triangle position

closes #10722

Tested in latest Chrome, Edge, Firefox and Safari.

2018-08-17 13:50 UTC, blizzz submitted a review, later dismissed
⚫🧙 ;) works and looks good. No idea whether it could have other implications, but on first sight all looks fine.

2018-08-17 14:00 UTC, skjnldsv requested changes
To fix the settings menu, this property needs to be `!important` or have a higher selector weight :)

https://github.com/nextcloud/server/blob/ccb8f7dff6efa2c3f55eacfe2bb87f061c9c4aa0/core/css/header.scss#L408

See other comments otherwise! ;)
Thanks again for taking care of this!

2018-08-17 16:04 UTC, weeman1337 commented on core/css/header.scss
> +			right: 22px;
Good finding!

2018-08-17 16:32 UTC, skjnldsv commented on core/css/header.scss
> +		right: 22px;
This or https://github.com/nextcloud/server/blob/ccb8f7dff6efa2c3f55eacfe2bb87f061c9c4aa0/core/css/header.scss#L408

Pick one ;)

2018-08-17 16:45 UTC, weeman1337 commented on core/css/header.scss
> +		right: 22px;
✓ done

2018-08-17 16:49 UTC, skjnldsv approved these changes

2018-08-20 13:20 UTC, MorrisJobke approved these changes

2018-08-20 13:22 UTC, merged