in 14 the click action gets lost in the Backbone view.
nextcloud/server pull request #10782
Opened 2018-08-21 14:34 UTC by blizzz

fixes #10774 – tagging a file does not work with the second time you open the sidebar

I am not sure this is the best way to fix it, but it works. For this at least. There should be some reason why the click action gets unbound in 14, I don't know why though and don't know where to look. Thus, not sure whether this can be a problem for other FilePlugins.

2018-08-21 16:47 UTC, skjnldsv approved these changes

2018-08-22 08:20 UTC, MorrisJobke commented
Does not really work for me:


https://cloud.morrisjobke.de/s/B5CJKcNHbWKAyQa

As you can see the click on the "Tag" label triggers the dropdown of the tag element but does not change the visibility (not shown input just shows the dropdown and for a shown input the dropdown just switches on and off)

2018-08-22 15:44 UTC, blizzz commented
@MorrisJobke different issue, and I could not observe it here

2018-08-22 18:56 UTC, MorrisJobke requested changes
Then this breaks master for me - this is the same stuff on master, where I can at least open it once per page refresh: https://cloud.morrisjobke.de/s/ygYmJcTcMEpkajJ

2018-08-22 18:56 UTC, MorrisJobke commented
Browser I tested in: Safari

2018-08-24 19:52 UTC, MorrisJobke commented
Let's fix it later and backport.

2018-09-12 15:58 UTC, blizzz commented
> Then this breaks master for me - this is the same stuff on master, where I can at least open it once per page refresh: https://cloud.morrisjobke.de/s/ygYmJcTcMEpkajJ

→  File not found

:crying_cat_face:

2018-09-14 15:02 UTC, blizzz commented
What I see on a QtWebEngine based browser is that after selecting a tag, it is shown on the upper left corner in the browser window. That's the only glitch, otherwise in works.  In FF everything is shiny, however.

2018-09-14 15:32 UTC, blizzz commented
> What I see on a QtWebEngine based browser is that after selecting a tag, it is shown on the upper left corner in the browser window. 

And the moment I tried to investigate it, it stopped to happen. Whyever. 

Anybody else with Safari or who can do reproduce issues? Otherwise i'd vote for merging, as the state is at leat better than before.

2018-09-23 19:05 UTC, sketchygamesdev commented
@MorrisJobke Just curious, when this is fixed and merged will it also affect the NextCloud 14/Beta snap? Tags are only working once per page refresh for me as well. Ya'll probably already knew that though.

2018-09-24 10:31 UTC, MorrisJobke commented
> @MorrisJobke Just curious, when this is fixed and merged will it also affect the NextCloud 14/Beta snap? Tags are only working once per page refresh for me as well. Ya'll probably already knew that though.

Yes. Once fixed it will be in the next release. It seems to be 14.0.2 earliest though

2018-10-02 17:02 UTC, MorrisJobke commented
@blizzz Any news on this one?

2018-10-08 09:12 UTC, blizzz commented
@MorrisJobke still what I said in https://github.com/nextcloud/server/pull/10782#issuecomment-421396365  I have not found anyone else with Safari. But since, you're back ;)  If you can reproduce it we can tackle that, otherwise merge.

2018-10-08 15:13 UTC, MorrisJobke approved these changes
Retested and works better than on master 👍

2018-10-08 15:14 UTC, merged

2018-10-09 13:32 UTC, MorrisJobke commented
Let's revert as it breaks the sharing entries. See https://github.com/nextcloud/server/pull/11715#pullrequestreview-162888218