Switches the default logo color depending on the primary color
nextcloud/server pull request #10898
Opened 2018-08-28 10:32 UTC by weeman1337

These changes add switching the _default_ logo from white to blue depending on the primary color.
The switch happens between #cccccc and #dddddd

![image](https://user-images.githubusercontent.com/6216686/44717798-54527b80-aabe-11e8-9191-945ca10ee5be.png)

![image](https://user-images.githubusercontent.com/6216686/44717787-50265e00-aabe-11e8-99d2-b7b9a3e51d3c.png)

A custom logo doesn't use this mechanism.

Closes #10684

2018-08-28 10:33 UTC, weeman1337 commented on apps/theming/css/theming.scss
> +#theming-preview-logo,
I moved this out of the condition.
The variable always contains the logo.

2018-08-28 10:34 UTC, weeman1337 commented on core/img/logo-blue.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
I added the blue versions and didn't use the svg api, because it may not be available e.g. on the guest page.
There was another issue also taking out some icons for that reason.

2018-08-28 13:30 UTC, jancborchardt commented
@weeman1337 cool! I will come over to you in a bit :) Meanwhile – what would happen, say, when you have a light yellow or green theming color? Cause then the logo color would clash, right? That's why I would make it dark instead of blue, just like the top bar icons.

2018-08-28 13:39 UTC, weeman1337 commented
@jancborchardt I made it blue because of https://github.com/nextcloud/server/issues/10684#issuecomment-412843478

> We had some discussion about that in the past, and the conclusion was that we don't want to invert the logo, because the Nextcloud logo should either be blue or white.

2018-08-28 15:04 UTC, jancborchardt commented
So @weeman1337 and me just looked at it and we just have to pick a tradeoff:

1. Logo always :white_circle: white: Looks bad as soon as the color is light and all icons are dark
2. Logo :white_circle: white on dark background, and :large_blue_circle: blue on light background: Looks _really_ bad on any light color which is not grey.
3. Logo :white_circle: white on dark background, and :black_circle: black on light background: Looks decent.

So we are going for option 3. cc for info @nextcloud/designers 

Only thing to adjust is that the threshold for change is the same as for the app icons in the top bar. :) Then :+1: from me.

2018-08-28 15:52 UTC, MorrisJobke commented
Please wait for the stable14 branch until merging. I would like to not merge this into 14 that short before a release.

2018-08-29 09:28 UTC, skjnldsv requested changes
Good stuff :)
Some small nitpicks ;)

2018-08-29 09:28 UTC, skjnldsv commented on apps/theming/css/theming.scss
> +		$image-logo: url('../../../../svg/core/logo/logo/000000?v=1');
Please use the scss function for that :)

2018-08-29 09:28 UTC, skjnldsv commented on apps/theming/css/theming.scss
> +		$image-logo: url('../../../../svg/core/logo/logo/000000?v=1');
https://github.com/nextcloud/server/blob/7210b1144bd96a9f9d2cc8ff88304c3bba1038f1/core/css/functions.scss#L34-L48

2018-08-29 09:28 UTC, skjnldsv commented on core/img/logo/logo.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
why this change of the logo file? :)

2018-08-29 09:28 UTC, skjnldsv commented on core/Controller/SvgController.php
> +		$fillRe = '/<((circle|rect|path)((!fill)[a-z0-9 =".\-#():;])+)\/>/mi';
If you change the regex, please update the tests to make sure we also cover the reason why you changed this ;)

2018-08-29 11:59 UTC, weeman1337 commented on core/Controller/SvgController.php
> +		$fillRe = '/<((circle|rect|path)((!fill)[a-z0-9 =".\-#():;])+)\/>/mi';
I'll add a test!
It changes the regex to do what the comment says ;) The actual version replaces existing fills. Removing the ? only matches if there isn't a fill already.

2018-08-29 12:03 UTC, weeman1337 commented on core/img/logo/logo.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
I just removed the grouping of the three circles. The svg coloring freaked out..

2018-08-29 12:47 UTC, skjnldsv commented on core/img/logo/logo.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Can you clean things up then? :)
We use scour ;)

`scour --create-groups --enable-id-stripping --enable-comment-stripping --shorten-ids --remove-metadata --strip-xml-prolog --no-line-breaks -i old.svg new.svg`

2018-08-30 19:09 UTC, weeman1337 commented on core/img/logo/logo.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
done

2018-08-30 19:12 UTC, weeman1337 commented
@skjnldsv I added a SvgControllerTest. The SVG coloring has some pitfalls. E.g. applying it on a black circle (without stroke/fill) or a group (applying it to child elements) may result in unwanted filled elements. I tweaked the Nextcloud logo to work.

With the new test we may extend the behavior in the future.

2018-08-30 19:14 UTC, weeman1337 commented on core/css/functions.scss
>  @mixin icon-color($icon, $dir, $color, $version: 1, $core: false) {
I took this apart, because it didn't do what the comment said...

2018-08-30 19:53 UTC, skjnldsv commented on core/css/functions.scss
>  @mixin icon-color($icon, $dir, $color, $version: 1, $core: false) {
Thx!

2018-08-30 19:54 UTC, skjnldsv commented
> With the new test we may extend the behavior in the future.

Maybe we should enforce a fill attribute and only replace in the future :)

2018-08-31 07:31 UTC, suntorytimed commented
Could this be implemented for the favicon as well? Would be nice to have a favicon that corresponds to the primary color and the different color of the Nextcloud logo. Currently it is necessary to use imagmagick to do any changes to the favicon.

2018-10-02 06:38 UTC, rullzer commented
Rebased

2018-10-02 06:57 UTC, skjnldsv approved these changes

2018-10-02 06:57 UTC, skjnldsv approved these changes
Code looks good! Let's wait the input of our lord and master @juliushaertl  :wink:

2018-10-02 07:40 UTC, juliushaertl commented
@weeman1337 There is one test failing:

```
There was 1 failure:

1) OCA\Theming\Tests\UtilTest::testGetAppImage with data set #0 ('core', 'logo.svg', '/drone/src/github.com/nextclo...go.svg')
Failed asserting that false matches expected '/drone/src/github.com/nextcloud/server/core/img/logo.svg'.

/drone/src/github.com/nextcloud/server/apps/theming/tests/UtilTest.php:172
```

Besides that it looks good to me, the favicon could also use the inverted logo, as we generate a png from with imagemagick for that anyway, but we can do that in a follow up pr.

2018-10-03 13:56 UTC, jancborchardt approved these changes
Nice, looking good! :+1: 

And yes, @juliushaertl follow-up PR to adjust the favicon would be great! :)

2018-10-03 19:39 UTC, MorrisJobke commented
@weeman1337 Tests still fail 😢

2018-10-08 08:33 UTC, merged