Add fix response
nextcloud/server pull request #10967
Opened 2018-09-02 13:53 UTC by jakobsack

This pull request allows apps to return a zip file created on the fly.

implements #7589

2018-09-04 07:55 UTC, ChristophWurst commented on lib/public/AppFramework/Http/ZipResponse.php
> +			return;
I wonder if ignoring this invalid argument silently is the best way to handle this. Maybe we should just fail with an InvalidArgumentExeption or similar. What do you think, @rullzer?

2018-09-04 08:08 UTC, ChristophWurst requested changes
Generally, this looks good. Thanks!

I'd love to see tests, though, if possible.

2018-09-04 08:08 UTC, ChristophWurst commented on lib/public/AppFramework/Http/ZipResponse.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
:see_no_evil:

2018-09-04 08:08 UTC, ChristophWurst commented on lib/public/AppFramework/Http/ZipResponse.php
> + * @author Roeland Jago Douma <roeland@famdouma.nl>
really?

2018-09-28 14:36 UTC, rullzer commented on lib/public/AppFramework/Http/ZipResponse.php
> + * @author Roeland Jago Douma <roeland@famdouma.nl>
Yes he took it from an old PR of mine ;)

2018-10-02 06:27 UTC, rullzer commented on lib/public/AppFramework/Http/ZipResponse.php
> +			return;
Agreed done

2018-10-02 06:28 UTC, rullzer commented on lib/public/AppFramework/Http/ZipResponse.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
fixed

2018-10-02 06:30 UTC, rullzer commented
I'm not sure yet how to test this as the zipstreamer is quite aggressive and just outputs.

We could of course wrap it in another stream. Thinking about it that probably is best for the abstraction.

2018-10-02 17:42 UTC, MorrisJobke commented
@rullzer said: "we should abstract it with a stream wrapper"

2018-10-02 20:22 UTC, rullzer approved these changes

2018-10-02 21:34 UTC, MorrisJobke approved these changes

2018-10-02 21:34 UTC, merged

2018-10-07 19:33 UTC, jakobsack commented
Hi all, thanks for merging this while I was on vacation :-)