occ app update command
nextcloud/server pull request #11053
Opened 2018-09-04 20:37 UTC by michag86

partial fix for #7002

This new command has two parameters/options:
appid as parameter updates a single app
--all updates all updatable apps

output looks like this:
```
calendar new version available: 1.6.1
calendar updated
contacts new version available: 2.1.6
contacts updated
```

If no update is available, no output is written.

@MorrisJobke @exploide @enoch85

2018-09-24 18:55 UTC, MorrisJobke commented
@rullzer @nickvergessen @ChristophWurst Mind to have a look at this?

2018-09-24 19:21 UTC, nickvergessen requested changes

2018-09-24 19:21 UTC, nickvergessen commented on core/Command/App/Update.php
> +                }
Intendation is off

2018-09-24 19:21 UTC, nickvergessen commented on core/Command/App/Update.php
> +			$output->writeln("<error>Please specify an app to update or \"--all\" to update all updatable apps\"</error>");
I would print the list of available updates instead

2018-09-24 19:21 UTC, nickvergessen commented on core/Command/App/Update.php
> +			if (!\OC_App::getAppPath($singleAppId)) {
Inject IAppManager instead?

2018-09-24 19:21 UTC, nickvergessen commented on core/Command/App/Update.php
> +			$apps = \OC_App::getAllApps();
IAppManager should have a similar method too?

2018-09-24 19:21 UTC, nickvergessen commented on core/Command/App/Update.php
> +		$installer = \OC::$server->query(Installer::class);
Inject this instead

2018-09-24 21:28 UTC, michag86 commented on core/Command/App/Update.php
> +			$apps = \OC_App::getAllApps();
IAppManager->getInstalledApps returns only enabled apps.

2018-09-24 21:28 UTC, michag86 commented on core/Command/App/Update.php
> +			if (!\OC_App::getAppPath($singleAppId)) {
IAppManager->isInstalled returns only true if app is enabled:
https://github.com/nextcloud/server/blob/stable14/lib/private/App/AppManager.php#L209
IAppManager->getAppPath throws an error if the app is not installed. 
https://github.com/nextcloud/server/blob/stable14/lib/private/App/AppManager.php#L315
I've tried it with try and catch but cannot get it working at the moment.

2018-09-25 13:27 UTC, nickvergessen commented on core/Command/App/Update.php
> +			if (!\OC_App::getAppPath($singleAppId)) {
Well, `IAppManager->getAppPath()` just calles `\OC_App::getAppPath()` and throws if the return is false. So the following should work:
```php
try {
    $this->appManager->getAppPath($singleAppId);
} catch (AppPathNotFoundException $e) {
    $output->writeln($singleAppId . ' not installed');
}
```

2018-09-25 13:30 UTC, nickvergessen commented on core/Command/App/Update.php
> +			$apps = \OC_App::getAllApps();
right

2018-09-25 13:30 UTC, nickvergessen commented on core/Command/App/Update.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
`* @copyright Copyright (c) 2018, Klaus Herberth <klaus@jsxc.org>` ?

Or why is the author != copyright?

2018-09-28 13:05 UTC, MorrisJobke commented on core/Command/App/Update.php
> +		$installer = \OC::$server->query(Installer::class);
Because @michag86 asked in IRC: that means you create a constructor and member variable with this:

```
/** @var Installer */
private $installer;

public function __construct(Installer $installer) {
    $this->installer = $installer;
}
```

And then you can use `$this->installer` instead of do the `query`. 😉

2018-09-29 20:09 UTC, patschi commented on core/register_command.php
> +        $application->add(new OC\Core\Command\App\Update());
Just want to point out that indentation is wrong here too :)

2018-09-30 15:06 UTC, michag86 commented on core/Command/App/Update.php
> +			$output->writeln("<error>Please specify an app to update or \"--all\" to update all updatable apps\"</error>");
option --showonly added

2018-10-01 09:34 UTC, nickvergessen commented on core/Command/App/Update.php
> +		} else if ($input->getOption('all')) {
`} else if ($input->getOption('all') || $input->getOption('showonly')) {` ?

Otherwise you always need to specify both.

2018-10-01 09:42 UTC, michag86 commented on core/Command/App/Update.php
> +		} else if ($input->getOption('all')) {
Good point. I have changed it.

2018-10-01 09:50 UTC, nickvergessen approved these changes

2018-10-01 16:54 UTC, MorrisJobke commented on lib/composer/composer/autoload_static.php
> +        'OC\\AppFramework\\Logger' => __DIR__ . '/../../..' . '/lib/private/AppFramework/Logger.php',
This file does not exist in our code base. I guess you have it only locally on your machine. Could you remove those lines? (same for the file above)

2018-10-01 18:02 UTC, danielkesselberg commented on lib/composer/composer/autoload_static.php
> +        'OC\\AppFramework\\Logger' => __DIR__ . '/../../..' . '/lib/private/AppFramework/Logger.php',
Looks like the branch is out of date. These file should be present since https://github.com/nextcloud/server/pull/11046/files

2018-10-29 23:37 UTC, MorrisJobke commented
@michag86 May I ask you to update your branch? Because #11627 for example touched similar code parts. If you need help then I or @patschi can help you with updating this branch and get it in.

2018-11-01 15:54 UTC, MorrisJobke commented
As @michag86 asked me to rebase and resolve the conflicts I did this and also updated a bit the code style. Looks good now to me 👍

2018-11-01 16:04 UTC, MorrisJobke commented on core/Command/App/Update.php
> +					} catch(\Exception $e) {
It would be good to log also the exception here. Let me do that.

2018-11-01 16:08 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-11-01 16:33 UTC, patschi commented on core/Command/App/Update.php
> +					} catch(\Exception $e) {
Wouldn't it make sense to also use `Throwable`s here, as Christoph suggested for `app:remove` here: https://github.com/nextcloud/server/pull/11627#discussion_r224119436?

2018-11-01 21:08 UTC, MorrisJobke commented
Restarted CI because of network issues: https://drone.nextcloud.com/nextcloud/server/12256

2018-11-01 23:41 UTC, MorrisJobke commented
CI failures are unrelated.

2018-11-01 23:41 UTC, merged