Bugfix 2FA theme: buttons white
nextcloud/server pull request #11123
Opened 2018-09-09 09:17 UTC by CrazyEasy

Before:
![screenshot_20180909_111457](https://user-images.githubusercontent.com/42419545/45263006-d8dbbd00-b421-11e8-8383-014d9f32e0c2.png)

After:
![screenshot_20180909_111418](https://user-images.githubusercontent.com/42419545/45263011-e3965200-b421-11e8-88c0-ade4cdb4a4f1.png)

2018-09-10 14:04 UTC, ChristophWurst commented
@CrazyEasy I've *never* seen that bug. Do you use any custom CSS or theming?

2018-09-10 14:04 UTC, skjnldsv requested changes

2018-09-10 14:04 UTC, skjnldsv commented on apps/theming/css/theming.scss
> +			color: $color-primary-text;
Please use the css variables :) 
https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss
`var (--color-primary-text);`

2018-09-10 14:04 UTC, skjnldsv commented on apps/theming/css/theming.scss
> +			color: $color-primary-text;
`var (--color-primary-text);`

2018-09-10 14:05 UTC, skjnldsv commented
@CrazyEasy Thanks a lot for your fix :)
A small fixes are needed to ensure compatibility with the accessibility app and the new design functions ;)

:+1:

2018-09-10 14:10 UTC, CrazyEasy commented
@ChristophWurst 
>  I've never seen that bug. Do you use any custom CSS or theming?

No I don't. It's just the normal installation of Nextcloud 14.

2018-09-10 14:20 UTC, skjnldsv approved these changes

2018-09-25 14:18 UTC, rullzer approved these changes

2018-09-25 14:19 UTC, rullzer commented
@CrazyEasy Thanks a lot for your fix :rocket: 

Normally we require commits to be signed off. But for this it is fine.
Looking forward to your next PR!

2018-09-25 14:20 UTC, merged