sharebymail: Add linebreak before password
nextcloud/server pull request #11338
Opened 2018-09-23 18:46 UTC by rubo77

This commit will add a linebreak right before the password, so long passwords, containing hyphen or other breakable characters, do not break the password into two lines any more.

In HTML-View the email has already the correct width, so the password is in the next line. But in text-only view, the width of the email depends on the email client.

---
Signed-off-by: Ruben Barkow <github@r.z11.de>

2018-09-28 15:34 UTC, danxuliu requested changes
@rubo77 I think that you mixed some branches or something like that, because you removed some features introduced in Nextcloud 14 (the share note and send password by Talk). Could you take a look? Thanks :-)

2018-09-29 08:02 UTC, rubo77 commented
@danxuliu you were right, I had an old base for my PR. I fixed that, so there is only this onle line, I really want to change.

2018-10-01 09:29 UTC, nickvergessen commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
I would propose to remove the password from the string instead and put it into a new `$emailTemplate->addBodyText()` call.

2018-10-01 13:15 UTC, rubo77 commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
could you write the code here please, what you mean exactly?

2018-10-01 13:17 UTC, rubo77 commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
I understand, but then the translation string would change, and this affects all translations then.

2018-10-01 17:16 UTC, nickvergessen commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
Better than starting to add a line break in a one-linr string

2018-10-02 19:31 UTC, rullzer requested changes

2018-10-02 19:31 UTC, rullzer commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
I agree with @nickvergessen here :)

translations are updated automatically.
Please update then we can get this in :)

2018-10-02 22:56 UTC, rubo77 commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$emailTemplate->addBodyText($this->l->t('It is protected with the following password: %s', ["\n" . $password]));
done.

I hope I changed it correctly. I am not sure, if `addBodyText` automatically ends with a lineBreak?

2018-10-03 08:02 UTC, rullzer commented
@rubo77 could you post a quick screenshot how it looks now?

2018-10-03 09:43 UTC, rubo77 commented
Sreenshots made with this solution:

![auswahl_023](https://user-images.githubusercontent.com/1591563/46402949-6ea4f800-c701-11e8-8ce3-01269cb323f7.png) 
![auswahl_021](https://user-images.githubusercontent.com/1591563/46402965-782e6000-c701-11e8-8dd2-9e5de367f824.png)

2018-10-03 09:59 UTC, jancborchardt approved these changes
Looks good! Better focus on the password than before too:+1:

2018-10-03 10:00 UTC, rullzer approved these changes
Looking good :rocket:

2018-10-03 10:57 UTC, merged