Add notification to generate 2FA backup codes
nextcloud/server pull request #11462
Opened 2018-09-29 19:06 UTC by rullzer

Adds a notiication to generate 2FA backup codes if you enable a 2FA provider without having generated backup codes.

TODO:
- [ ] Background/Repair job to check this for already existing users
- [ ] Tests

2018-09-29 19:13 UTC, ChristophWurst commented
Ref https://github.com/nextcloud/server/issues/11380

2018-09-29 19:23 UTC, ChristophWurst requested changes

2018-09-29 19:32 UTC, rullzer commented on lib/public/Authentication/TwoFactorAuth/RegistryEvent.php
> +	public function getProvider(): IProvider {
true but it makes sense in context of the event.

2018-10-01 08:00 UTC, ChristophWurst commented on apps/twofactor_backupcodes/tests/Unit/BackgroundJob/RememberBackupCodesJobTest.php
> +	/** @var IRegistry|\PHPUnit_Framework_MockObject_MockObject */
FYI this is `\PHPUnit\Framework\MockObject\MockObject` now since we're using phpunit 6+

2018-10-01 08:07 UTC, rullzer commented on apps/twofactor_backupcodes/tests/Unit/BackgroundJob/RememberBackupCodesJobTest.php
> +	/** @var IRegistry|\PHPUnit_Framework_MockObject_MockObject */
We do? Perfect.

2018-10-01 08:24 UTC, ChristophWurst approved these changes
Code looks good and works as expected :+1: 

Found a nitpick about making the text more consistent across the UI.

2018-10-01 08:27 UTC, ChristophWurst commented on apps/twofactor_backupcodes/tests/Unit/BackgroundJob/RememberBackupCodesJobTest.php
> +	/** @var IRegistry|\PHPUnit_Framework_MockObject_MockObject */
Yup: https://github.com/nextcloud/server/blob/a13730cedecd3d9834efa6b43c1130f231cd44ec/autotest.sh#L56

2018-10-01 09:16 UTC, nickvergessen submitted a review, later dismissed

2018-10-01 09:16 UTC, nickvergessen commented on apps/twofactor_backupcodes/lib/Notifications/Notifier.php
> +					$l->t('You have enabled two-factor authentication but have not yet generated backup codes. Be sure to do this in case you lose access to your seond factor.')
this is a very long subject. maybe you put this into the message and use a shorter subject (max 10 words)

2018-10-01 09:16 UTC, nickvergessen commented on lib/public/Authentication/TwoFactorAuth/IRegistry.php
> +	const EVENT_PROVIDER_DISABLED = self::class . ':disable';
all other event use `::` as seperator, but nvm

2018-10-01 09:20 UTC, rullzer commented on apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php
> +		if ($this->getLastRun() > ($this->time->getTime() - 60*60*24*14)) {
Right I could just do that... Initially i had different plans with it :) let me fix.

2018-10-01 09:37 UTC, nickvergessen commented on apps/twofactor_backupcodes/lib/Notifications/Notifier.php
> +					$l->t('You have enabled two-factor authentication but have not yet generated backup codes. Be sure to do this in case you lose access to your seond factor.')
` to your seond factor.`
seCCCCCCCCond

2018-10-01 09:42 UTC, rullzer commented on apps/twofactor_backupcodes/lib/Notifications/Notifier.php
> +					$l->t('You have enabled two-factor authentication but have not yet generated backup codes. Be sure to do this in case you lose access to your seond factor.')
done :)

2018-10-01 10:24 UTC, MorrisJobke approved these changes
Tested and works :+1:

2018-10-01 16:13 UTC, merged