Fix "Uninitialized string offset: 0 at Node.php"
nextcloud/server pull request #11465
Opened 2018-09-29 20:26 UTC by enoch85

Signed-off-by: Daniel Hansson <daniel@hanssonit.se>

Add the suggested fix in #10262 which without this fix spams the log with `Uninitialized string offset: 0 at Node.php#290`

cc @MorrisJobke

2018-09-29 20:34 UTC, enoch85 commented
Backport stable 14: https://github.com/nextcloud/server/pull/11466

2018-09-29 20:36 UTC, enoch85 commented
Backport stable 13 https://github.com/nextcloud/server/pull/11467

2018-09-30 09:51 UTC, MorrisJobke commented
> Backport stable 14: #11466

Only do back ports once they are requested. And please use descriptive issue titles, because "fix #10262" doesn't help anybody. That should be within the description of the PR.

2018-09-30 09:54 UTC, MorrisJobke requested changes

2018-09-30 09:54 UTC, MorrisJobke commented on lib/private/Files/Node/Node.php
> +		if (!$path || $path === '' or $path === '/') {
This is hiding the symptoms and not fixing the cause. The function is called with `null` even if only `string` should be handed in into this method. Thus the root cause it to search somewhere else. Could you first try the patch from https://github.com/nextcloud/server/issues/10262#issuecomment-407409865 to find it.

2018-09-30 10:11 UTC, enoch85 commented
@MorrisJobke  Gotcha! Will edit the original post.

2018-09-30 10:11 UTC, enoch85 commented on lib/private/Files/Node/Node.php
> +		if (!$path || $path === '' or $path === '/') {
This solved my problem and my log isn't spammed anymore on 14.0.1. I'm no PHP developer so I don't have a clue what this does, just trying to help out here since a PR was requested with the fix in the original issue. :angel:

2018-09-30 10:13 UTC, MorrisJobke commented on lib/private/Files/Node/Node.php
> +		if (!$path || $path === '' or $path === '/') {
Sure it solved the symptoms, but still we should not hide them but actually look why it is happening. THat's the reason I asked you to apply the patch, because it logs actually useful information that I or any other developer could use then to properly analyze the problem. 😉

2018-09-30 10:14 UTC, enoch85 commented
Feel free to close this and fix the cause of the issue. I want clean logs, but at the same time I totally get that we should fix the the cause.

2018-10-01 07:57 UTC, closed without merging

2018-10-01 08:05 UTC, enoch85 commented
OK, so I should add this instead:

```
		if ($path === null) {
			\OC::$server->getLogger()->logException(new \Exception(), ['app' => 'debug-empty-path']);
			return '/';
		}
```

2018-10-01 08:08 UTC, MorrisJobke commented
It will for now do the same, but also log some stack trace. You could remove the line with the logger once you have some stack traces.

2018-10-01 17:29 UTC, enoch85 commented
> You could remove the line with the logger once you have some stack traces. 

Oh! I thought that was the fix. :D