Hides the header actions for file drops
nextcloud/server pull request #11569
Opened 2018-10-02 22:09 UTC by weeman1337

As discussed in the ticket the header actions (like download) don't make sense for file drops.

Closes #11514

2018-10-02 22:21 UTC, jancborchardt commented
It seems the share note is floating around as a result of this (see selected top left):
![screenshot from 2018-10-03 00-20-02](https://user-images.githubusercontent.com/925062/46380327-230f3180-c6a2-11e8-96c7-714f509af488.png)
Maybe it should already be repositioned below the folder named like mentioned in https://github.com/nextcloud/server/issues/11513?

2018-10-03 07:42 UTC, weeman1337 commented
I inlined the share note for file drops:
![image](https://user-images.githubusercontent.com/6216686/46396689-61cbd880-c6f0-11e8-9d46-d83ee278e148.png)

@jancborchardt @nextcloud/designers what do you think? For now the note works like the disclaimer.

In general, as an user, I don't know the kind of text.. Do you think it makes sense to add headings for the disclaimer and note?

2018-10-03 09:41 UTC, MorrisJobke commented
> In general, as an user, I don't know the kind of text.. Do you think it makes sense to add headings for the disclaimer and note?

I'm totally fine no matter how it is called. The idea is to show the text to the user. So just showing it make a lot of sense. For the note maybe also a "mweimann left a note:" should be fine to give it a little bit context.

2018-10-03 13:46 UTC, jancborchardt approved these changes
I’d say it’s fine for now. Having _both_ disclaimer _and_ note together is the rarest case. We can still add headings in a follow-up if we feel it’s necessary in practice. :+1:

2018-10-03 14:53 UTC, MariusBluem commented
It is necessary to have headings or separation of those two things. If a disclaimer is set by an admin - all share notes added by users will get lost in the shuffle of legal stuff then.

I would recommend to put the disclaimer under the download button instead - or create a checkbox with „Agree to the terms of service“ hiding the TOS in a popup-box.

2018-10-03 15:14 UTC, jancborchardt commented
> I would recommend to put the disclaimer under the download button instead - or create a checkbox with „Agree to the terms of service“ hiding the TOS in a popup-box.

@MariusBluem This sounds good. Just a sentence below the upload button saying:

> By uploading files, you agree to the **terms of service**

(With the bold part being a link to open the terms of service in a modal.)

@weeman1337 what do you think? It’s also fine if we merge this as it is and do the terms of service stuff in a separate pull request.

2018-10-03 17:14 UTC, weeman1337 commented
> what do you think? It’s also fine if we merge this as it is and do the terms of service stuff in a separate pull request.

I think it's a good idea. I'll push the changes to this PR.

2018-10-29 09:08 UTC, weeman1337 commented
The terms are now shown in a dialog (you may test it; I will attach a screenshot later).

Test fails look unrelated...

2018-10-30 15:00 UTC, jancborchardt commented
What do you think @MariusBluem?

2018-10-31 08:58 UTC, MariusBluem commented
Will test it.

2018-11-01 12:57 UTC, MorrisJobke commented
@weeman1337 Mind to rebase this one, because there are two conflicts 🙈

2018-11-05 21:12 UTC, MariusBluem commented
👍

2018-11-05 22:45 UTC, MorrisJobke commented on apps/files_sharing/templates/public.php
> +						echo $l->t('By uploading files, you agree to the %s.', [
it would be better to have the whole sentence in here, because otherwise the article is not used together with the noun. Just add two `%$1s` and `%$2s` and add in there  begin and end tag.

2018-11-05 22:46 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
>  		if ($share->getNode() instanceof \OCP\Files\Folder) {
`$shareNode` as well? ;)

2018-11-05 22:46 UTC, MorrisJobke commented on apps/files_sharing/css/public.scss
> +	cursor: pointer;
Add the bold here.

2018-11-05 22:46 UTC, MorrisJobke commented on apps/files_sharing/css/mobile.scss
> +	}
Fix tabs vs. spaces here ;)

2018-11-05 22:47 UTC, MorrisJobke commented on apps/files_sharing/templates/public.php
> +								'<b id="show-terms-dialog">' . $l->t('terms of service') . '</b>'
We should not use `<b>` here, because style and semantics should be separated. Just use `<span>` and style in the CSS. @nextcloud/designers is bold even fine here?

2018-11-05 22:47 UTC, MorrisJobke requested changes
Only nitpicks, but too many to ignore them 😉

2018-11-06 07:08 UTC, weeman1337 commented on apps/files_sharing/templates/public.php
> +						echo $l->t('By uploading files, you agree to the %s.', [
I don't get it.. If I put everything in there the HTML doesn't work, because the text system strips it out. If there is a way doing that I'm fine to add it, but I really don't know how..

2018-11-06 09:56 UTC, MorrisJobke approved these changes
I fixed the nitpicks and it works now really nice 👍

2018-11-06 09:57 UTC, MorrisJobke commented on apps/files_sharing/templates/public.php
> +						echo $l->t('By uploading files, you agree to the %s.', [
That's what I meant: https://github.com/nextcloud/server/pull/11569/commits/118ed57aa736bf0f3390d068caf31bf0c8935475

There was a type from my side: `%1$s` it needs to be instead of `%$1s`. Then it shows the text.

2018-11-06 16:41 UTC, juliushaertl commented
One failing unit test :wink: 

```

There was 1 error:

1) OCA\Files_Sharing\Tests\Controllers\ShareControllerTest::testShareFileDrop
Undefined index: isIE

/drone/src/github.com/nextcloud/server/apps/files/templates/list.php:28
/drone/src/github.com/nextcloud/server/lib/private/Template/Base.php:179
/drone/src/github.com/nextcloud/server/lib/private/Template/Base.php:151
/drone/src/github.com/nextcloud/server/lib/private/legacy/template.php:208
/drone/src/github.com/nextcloud/server/apps/files_sharing/lib/Controller/ShareController.php:369
/drone/src/github.com/nextcloud/server/apps/files_sharing/tests/Controller/ShareControllerTest.php:477
```

2018-11-07 14:01 UTC, MorrisJobke commented
Remaining failures are unrelated -> merge

2018-11-07 14:01 UTC, merged