Add FileName to Workflow engine
nextcloud/server pull request #11599
Opened 2018-10-03 16:27 UTC by danielkesselberg

Add support for FileName to workflow engine. I've been thinking about writing a unit test for it but logic is already tested by `AbstractStringCheckTest`.

Close #7136

2018-10-03 17:10 UTC, rullzer requested changes

2018-10-03 17:10 UTC, rullzer commented on apps/workflowengine/lib/Check/FileName.php
> +/**
Please make new php code strict

2018-10-03 17:10 UTC, rullzer commented on apps/workflowengine/lib/Check/FileName.php
> +	public function setFileInfo(IStorage $storage, $path) {
string can be type hinted

2018-10-03 17:10 UTC, rullzer commented on apps/workflowengine/lib/Check/FileName.php
> +	protected function getActualValue() {
Add return type

2018-10-03 18:30 UTC, danielkesselberg commented on apps/workflowengine/lib/Check/FileName.php
> +	public function setFileInfo(IStorage $storage, $path) {
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/public/WorkflowEngine/ICheck.php#L41

Hmm. Interface needs to be adjusted.

2018-10-04 07:57 UTC, rullzer commented on apps/workflowengine/lib/Check/FileName.php
> +	public function setFileInfo(IStorage $storage, $path) {
AH leave it for now then

2018-10-04 16:27 UTC, nickvergessen approved these changes

2018-10-04 17:52 UTC, rullzer approved these changes

2018-10-05 12:56 UTC, nickvergessen commented on apps/workflowengine/lib/Check/FileName.php
> +		return mb_strtolower(basename($this->path));
I'm not sure if we should do the strtolower,
The problem is that the regex and pattern might require a special casing.

if you want strtolower, you can still put it in a regex?

2018-10-05 13:12 UTC, danielkesselberg commented on apps/workflowengine/lib/Check/FileName.php
> +		return mb_strtolower(basename($this->path));
For regex strtolower might be a problem yes but handy for is/not because you don't have to check dummy.png would trigger for Dummy.png as well. 

Is this feature for end users? If so I would suggest to do the strtolower at least for is/not.

2018-10-08 10:24 UTC, nickvergessen approved these changes

2018-10-08 11:57 UTC, merged