Fix call to logger
nextcloud/server pull request #11603
Opened 2018-10-03 19:20 UTC by danielkesselberg

`Argument 2 passed to OC\\Log::info() must be of the type array, string given, called in \/var\/www\/html\/nextcloud\/apps\/theming\/lib\/ImageManager.php on line 120`

https://github.com/nextcloud/server/blob/38a90130ce425d531a804dff591df4a883de3154/lib/public/ILogger.php#L129

2018-10-03 19:34 UTC, MorrisJobke requested changes

2018-10-03 19:34 UTC, MorrisJobke commented on apps/theming/lib/ImageManager.php
> +					$this->logger->info('The image was requested to be no SVG file, but converting it to PNG failed.', [$e->getMessage()]);
I guess we should add it to the message otherwise it's just lost. Could you add it to the message itself by string concatenation?

2018-10-03 20:26 UTC, MorrisJobke approved these changes

2018-10-03 20:27 UTC, ChristophWurst approved these changes

2018-10-04 05:40 UTC, merged

2018-10-04 05:43 UTC, MorrisJobke commented
@danielkesselberg Mind to do a backport to the stable branches 13 and 14?