Put back headings to semibold
nextcloud/server pull request #11616
Opened 2018-10-04 15:05 UTC by skjnldsv

Sorry @jancborchardt but this is looking far too agressive with 600 :/
Semibold is better imho, what do you think? @nextcloud/designers 

| Before | After |
|:---------:|:------:|
|![dev skjnldsv com_apps_files__dir _ 5](https://user-images.githubusercontent.com/14975046/46483305-9b3b3b80-c7f7-11e8-8a3c-485e0df115aa.png)|![dev skjnldsv com_apps_files__dir _ 4](https://user-images.githubusercontent.com/14975046/46483306-9d04ff00-c7f7-11e8-883b-eb172c80ab23.png)|
|![dev skjnldsv com_s_tb3tzzbhnhws8wg 1](https://user-images.githubusercontent.com/14975046/46483246-79da4f80-c7f7-11e8-946d-a1a34486625c.png)|![dev skjnldsv com_s_tb3tzzbhnhws8wg](https://user-images.githubusercontent.com/14975046/46483245-79da4f80-c7f7-11e8-81b9-d7d31b72a341.png)|

2018-10-04 15:18 UTC, MorrisJobke commented
> If you consider that our default is set on light, regular = semibold and semibold = bold for us ;)

I actually prefer that the file name stood out a bit more clearly. 🙈

2018-10-04 15:20 UTC, skjnldsv commented
> > If you consider that our default is set on light, regular = semibold and semibold = bold for us ;)
> 
> I actually prefer that the file name stood out a bit more clearly.

I feel like it's already pretty obvious here: https://user-images.githubusercontent.com/14975046/46483306-9d04ff00-c7f7-11e8-883b-eb172c80ab23.png ?
:)

2018-10-04 16:09 UTC, jancborchardt commented
Light and Regular is not a proper font weight pairing – too little difference. :-1: And mixing 3 different font weights doesn't look good either.

Our pairing is Light (for body text) & Semibold (for highlight/heading), nothing else. Regular is only there in the first place because light doesn't work on some displays. For readability, I was actually considering moving to Regular (for body) + Bold (for highlight) but that might be too much. (There's a branch if you want to check that out. ;)

Sorry but typography is pretty core to the experience so we should not choose it on a whim. Headings are Semibold and ever since the change, everything is so much more organized and clear.

2018-10-04 16:20 UTC, skjnldsv commented
> Our pairing is Light (for body text) & Semibold (for highlight/heading)

The difference between the two is too _rough_, It really looks like a bad design people did on old websites.
I agree on differences, and that it's an improvement, but I would be ok with your argument if you were saying light-regular the same way regular-semibold is ok 

> Sorry but typography is pretty core to the experience so we should not choose it on a whim

Which is exactly why I'm arguing here, if I did not find this important I would have leave it like that. Don't call my suggestion a whim because I disagree with you please.

2018-10-04 19:56 UTC, pixelipo commented
I can't make an educated decision on this issue. I suspect that it makes a bigger difference how these fonts are displayed on each one's screen (conditioned by browser, OS, antialiasing level, screen type (LED, OLED...), screen quality, screen size...) that we won't be able to select the one that looks better in general.

It's quite possible that 400 looks better on @skjnldsv 's screen while 600 looks better on @jancborchardt 's :smiley: Maybe you could try this out on several different configurations? And please don't share screenshots taken on Google The Font Ripper :dagger: ...ehh, I mean Google Chrome :laughing:

2018-10-05 06:19 UTC, pixelipo commented
> > And please don't share screenshots taken on Google The Font Ripper  ...ehh, I mean Google Chrome
> 
> Why is that? :)

Just search "google chrome font rendering" :wink:

2018-10-05 10:14 UTC, jancborchardt commented
@skjnldsv bad example with the Contacts app – it suffers from the same issue as the personal settings of course – too many headers on one page. In that case it should be h3 with font-weight: 300 (not 400), just like we fixed it on the personal settings.

> The difference between the two is too rough , It really looks like a bad design people did on old websites.

This comparison isn't really working or not true. It's not on old websites, check e.g. apple.com, slack.com and others. 

Hey, even the Steve Schoger dude people love so much wrote it in the very tip you pasted in the original pull request.

Good information architecture needs contrast and clear focus. The difference between 300 and 400 is not enough to convey that. And especially as we already use 600 for buttons and _headings_ in the left navigation (yes, we already use bold for headings) it is fitting for h2, h3, h4 etc.

2018-10-05 12:07 UTC, skjnldsv commented
> too many headers on one page. In that case it should be h3 with font-weight: 300 (not 400), just like we fixed it on the personal settings.

But on the personal settings this is h3 with 600, and on contacts this is h3 as well :)

> The difference between 300 and 400 is not enough to convey that.

But we're using light, so the diff is between 100 and 400, which is the same as regular to semibold (300 to 600)

2018-10-05 12:15 UTC, skjnldsv commented
> In that case it should be h3 with font-weight: 300 (not 400), just like we fixed it on the personal settings.

If you need to manually override a global css rule, this is either:
1. not the proper html element
2. not the correct css global rule

2018-10-05 13:32 UTC, pixelipo commented
good argument @skjnldsv - headings (with predefiend styling) should make sense in all cases globally.

2018-10-17 12:55 UTC, jancborchardt commented
So your proposal is to use h3 for Personal settings and use font-weight: 300 for h3?

The problem is that this would create readability issues wherever else h3 is used, especially in vertical writing. Like in the 2FA settings (cc @ChristophWurst who initially brought this exact problem up) and in the News app too.

I really think that the Personal settings page with the large amount of heading + box is a very special case, and it’s fine to simply reduce the font-weight there.

----------------------------------

> But we're using light, so the diff is between 100 and 400

This is not correct. Light is 300, not 100. This is the [naming table](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping), to clear it up:

Value | Common weight name
-- | --
100 | Thin (Hairline)
200 | Extra Light (Ultra Light)
300 | Light
400 | Normal
500 | Medium
600 | Semi Bold (Demi Bold)
700 | Bold
800 | Extra Bold (Ultra Bold)
900 | Black (Heavy)

2018-10-17 12:55 UTC, jancborchardt requested changes
Would still close this, see my comment at https://github.com/nextcloud/server/pull/11616#issuecomment-430616570

2018-10-19 12:16 UTC, skjnldsv commented
@jancborchardt Ah yes, thanks for the details! :+1: 
Nonetheless, css is about standards, you should always think about NOT to create exceptions.
It doesn't matter what we decide to choose. Setting a property to h3 and having to override it somewhere else is absolutely not the way to go and needs to be fixed. I will consider this as a ui regression. The questions is then we do we decide to do?

1. list every heading and decide the proper standard behind it?
2. change the h3 of the personnal settings and the contacts details to the most fitting one?
3. something else? :grin:

2018-10-19 13:15 UTC, jancborchardt commented
> Nonetheless, css is about standards

But we are not discussing about CSS, but about design. There are exceptions sometimes.

Remember when people were confused/critical when they found out that the G of the Google logo is not a perfect circle: https://www.creativebloq.com/news/google-logo-sparks-correct-design-debate

Design is not only dogmatic following of standards.

As said:

> I really think that the Personal settings page with the large amount of heading + box is a very special case, and it’s fine to simply reduce the font-weight there.

Same for Contacts. Those two are the exceptions for headings being set in regular since there are a lot of headings and fields. But the default for headings is the current one (Semibold, maybe soon Bold).

2018-10-19 17:16 UTC, skjnldsv commented
I'll provide a standard next week :)

2018-10-19 17:16 UTC, closed without merging