[14] Fixes the apps menu scrollbar
nextcloud/server pull request #11662
Opened 2018-10-07 12:04 UTC by weeman1337

Backport of #11624, see #11468

2018-10-07 13:08 UTC, skjnldsv approved these changes

2018-10-08 06:36 UTC, rullzer approved these changes

2018-10-08 06:36 UTC, rullzer requested changes
RC is out lets wait for the final to be released

2018-10-11 09:38 UTC, rullzer approved these changes

2018-10-11 09:38 UTC, merged