Show a more specific error message if config file is not writable
nextcloud/server pull request #11663
Opened 2018-10-07 13:27 UTC by burned42

When I tried reproducing the problem described in #8580 I noticed that there is only a very generic error message displayed (like in the attached screenshot in this issue) when the config file does not exist and the config directory is not writable, so e.g. if you set up a new installation and didn't adjust the permissions correctly.

So this PR should introduce a more helpful error message for that case.

2018-10-07 14:27 UTC, burned42 commented
In the `README.md` it says I should mention the people from the according issue, so I guess that's for having the right people notified for reviewing the code, right? So I'll just mention the ones marked as 'Member' I guess: @MorrisJobke @rullzer

Apparently the CI is currently failing but maybe someone of you could also give me a hint on how to debug those failing CI checks. Until now I didn't find out how to run the tests manually to get those errors. When running the tests locally they are all passing, so I don't really know what the issue is with the failing checks.

2018-10-07 18:12 UTC, kesselb reviewed
Thank you for your contribution :+1:

2018-10-07 18:12 UTC, danielkesselberg commented on lib/base.php
> +			OC_Template::printGuestPage('', 'error', ['errors' => [$error]]);
https://github.com/nextcloud/server/blob/c9e93b8084e45d6773e57932165739738c075889/lib/private/legacy/template.php#L339-L346

There is a helper for error page. Maybe this would work here as well?

2018-10-07 18:12 UTC, danielkesselberg commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
Would `!is_file($this->configFilePath) && !touch($this->configFilePath)` work? I guess when either directory or file is not writable `touch` will fail anyway?

2018-10-07 18:15 UTC, danielkesselberg commented
![image](https://user-images.githubusercontent.com/3902676/46585173-a0a1bb80-ca6d-11e8-90f8-d0de01a0ab15.png)
You can check ci here https://drone.nextcloud.com/nextcloud/server/11179

2018-10-08 11:55 UTC, MorrisJobke commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
I think so 👍

2018-10-08 11:56 UTC, MorrisJobke commented on lib/base.php
> +			OC_Template::printGuestPage('', 'error', ['errors' => [$error]]);
Needs to be checked, because it often also initializes stuff and it could be that it is too early in the life cycle. Also just throwing the exception and let index.php handle it, would make the code a bit less cluttered and help to reduce complexity inside `lib/base.php`. @burned42 Is this possible or is it catched on the way out? 

This would be the place where it should be catched: https://github.com/nextcloud/server/blob/master/index.php#L50-L62

2018-10-08 16:32 UTC, burned42 commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
Technically you are correct, `touch` will fail, but when it fails it fails with a PHP Notice generated. I tried to prevent this by first making sure the touch wouldn't fail due to missing write permissions. Another problem is that `touch` can succeed if the file exists and the current user is the owner of the file but has no write permissions, check https://stackoverflow.com/a/990893 for more information about this.

On further testing I also noticed that we should first `touch` and then check for `is_writable` because for a non existing file `is_writable` also returns `false`, see 141b8c526e6f9c1945ddee5c22718b0610ecca29

2018-10-08 16:51 UTC, burned42 commented on lib/base.php
> +			OC_Template::printGuestPage('', 'error', ['errors' => [$error]]);
@danielkesselberg @MorrisJobke Thanks for the suggestions, on first sight this looks nice but it's apparently not really applicable here I think.

The Exception is not catched on the way out, it is caught in `index.php` if I remove the changes on `base.php` but the `OC_Template::printErrorPage()` there throws an Exception with the following message: `Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file" `.

So in fact it gets passed on to the `OC_Template::printExceptionErrorPage()` there which would display the error message with the helpful hint on what to do but only in debug mode. In normal mode it only says that there is a problem and shows the remote IP and request ID. As far as I can see debug mode would be switched on in `config.php` which might not exist yet which is the base problem we are trying to solve :D

2018-10-08 17:00 UTC, burned42 commented
> ![image](https://user-images.githubusercontent.com/3902676/46585173-a0a1bb80-ca6d-11e8-90f8-d0de01a0ab15.png)
> You can check ci here https://drone.nextcloud.com/nextcloud/server/11179. I'm not sure if chmod works on drone.

@danielkesselberg Thanks for the hint. What I don't understand is that for only 4 out of that big list of checks this one unit test fails, but I don't really know drone or the setup so maybe that is totally reasonable.

So if chmod is not working on drone (or some special configuration that is used in those 4 failing test?) that would explain why this test isn't working. I am not really familiar with drone, I found some documentation but nothing about chmod not working or similar. Is there some way to debug this? Or should I just use some commits with a bit of debugging output to check this theory?

2018-10-08 17:08 UTC, danielkesselberg commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
I just found this. Just wondering is these function broken? I guess when config not writable there should be an error.  https://github.com/nextcloud/server/blob/40d185e92812c54b9ef84ffda997079e80335a2d/lib/base.php#L233-L268

PhpStorm tells me that `!$configFileWritable && !OC_Helper::isReadOnlyConfigEnabled()
			|| !$configFileWritable && \OCP\Util::needUpgrade()` may not work as expected.

2018-10-08 17:45 UTC, burned42 commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
There seems to be a config parameter `config_is_read_only` which can be set true if the config file is intentionally not writable, so I guess there shouldn't always be an error if the config file is not writable.

I guess PhpStorm is reporting this because there are no parentheses, but it seems to do the right thing. At least it makes sense, it goes into the if (displaying an error) if either the config file is not writable and not configured to be readonly or if the config file is not writable but an upgrade should be done (which would need to alter the config file).

2018-10-08 17:50 UTC, danielkesselberg commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
Does it makes sense to add a check "is directory writable" to the function above? What do you think is the current check to late? I guess your check is executed much earlier.

2018-10-08 18:16 UTC, burned42 commented on lib/private/Config.php
> +			(!is_file($this->configFilePath) && !is_writable(dirname($this->configFilePath)))
I'm not sure if I understand, where exactly would you suggest adding a check 'is directory writable' and how would that help?

I'm not sure if `checkConfig` is called too late, 'my check' is called a bit earlier in `base.php` via `self::initSession()` which might try to create a `config.php` to set an instance ID. But I don't know if changing the order would be better or not. I guess it wouldn't really matter, we just would have to change `checkConfig` a bit.
`checkConfig` is using `OC_Template::printErrorPage` which as I already found out in https://github.com/nextcloud/server/pull/11663#discussion_r223432063 tries to do some DB queries which of course can fail if there is no config.php with some DB settings.
But as 'my check' is running before that it shouldn't happen because otherwise it wouldn't even get that far to call `checkConfig`.

2018-10-08 20:11 UTC, burned42 commented
> > ![image](https://user-images.githubusercontent.com/3902676/46585173-a0a1bb80-ca6d-11e8-90f8-d0de01a0ab15.png)
> > You can check ci here https://drone.nextcloud.com/nextcloud/server/11179. I'm not sure if chmod works on drone.
> 
> @danielkesselberg Thanks for the hint. What I don't understand is that for only 4 out of that big list of checks this one unit test fails, but I don't really know drone or the setup so maybe that is totally reasonable.
> 
> So if chmod is not working on drone (or some special configuration that is used in those 4 failing test?) that would explain why this test isn't working. I am not really familiar with drone, I found some documentation but nothing about chmod not working or similar. Is there some way to debug this? Or should I just use some commits with a bit of debugging output to check this theory?

@danielkesselberg Alright, I added some checks in b5616fdc4635e090a4936fe06649de031d748821 to make sure the file/directory permissions got applied correctly. And as it seems your assumption that `chmod` isn't working as expected on drone seems to be correct. So, should I just leave this commit in, or is there another solution to this problem?

2018-10-09 07:12 UTC, MorrisJobke commented on lib/base.php
> +			OC_Template::printGuestPage('', 'error', ['errors' => [$error]]);
Okay - then this is the only way. That's how it is early in the init process. :/

2018-10-15 15:43 UTC, burned42 commented
Is there anything that I should/could do currently? Or should I just wait for your review? :)

2018-11-05 23:28 UTC, MorrisJobke commented
@rullzer @blizzz @nickvergessen Mind to look into this one?

2019-10-24 12:58 UTC, ChristophWurst commented
@burned42 could you update this branch to the latest master please? Let's see if the CI issues magically disappeared. Otherwise we have to have another look

Code looks fine otherwise :+1:

2019-10-24 16:38 UTC, burned42 commented
@ChristophWurst honestly, I already kind of forgot about this PR :D but I just pulled latest master and merged it into this branch (no merge conflicts fortunately). So let's see what the CI says.

2019-10-24 17:14 UTC, ChristophWurst commented
> @ChristophWurst honestly, I already kind of forgot about this PR :D but I just pulled latest master and merged it into this branch (no merge conflicts fortunately). So let's see what the CI says.

No worries :) Thanks for the quick action.

Looks like CI is happy (two unrelated failures can be ignored) :tada: :fireworks:

2019-10-24 20:40 UTC, kesselb commented
I'm not a fan. Additional complexity without fixing anything. 

1) We run into some issues while initializing the sessions. Actually there is no instance id yet. I think we should fix this issue by generating the instance id during the setup. 

2) There is [checkConfig](https://github.com/nextcloud/server/blob/de6940352a2f708376219a89ec84a8e6d25ca59e/lib/base.php#L233-L268) method with the same check. It also creates the config.php on demand. Wouldn't it be easier to call `checkConfig` before `initSession`?

https://github.com/nextcloud/server/blob/de6940352a2f708376219a89ec84a8e6d25ca59e/lib/base.php#L639-L645

2019-10-25 19:00 UTC, kesselb commented
> I'm not a fan. Additional complexity without fixing anything.

That probably sounded a bit rude. I still think it's more a theoretical issue because the setup needs a writable config directory anyway and it's not clear to me how you can end up in the above situation but fine by me ;)

2019-12-03 18:24 UTC, nickvergessen requested changes

2019-12-03 18:24 UTC, nickvergessen commented on lib/base.php
> +			OC_Template::printGuestPage('', 'error', ['errors' => [$error]]);
While I understand the intention of this PR, trying to print a page when config has an error is a bad idea. This will try to load SCSS stuff which might also fail to be written, etc, and then you end up with a blank page instead of message which at least gives you a hint what is wrong.

2019-12-03 21:00 UTC, burned42 commented
Alright, I understand, no problem. I just found the issue during last years hacktoberfest and tried to solve it. So as it seems like my solution isn't really sufficient to solve the problem I guess I'll just close the PR and maybe someone else (who maybe is also a bit more familiar with the codebase) will come up with a different solution to the problem ;)

2019-12-03 21:00 UTC, closed without merging

2019-12-18 14:48 UTC, ChristophWurst commented
Thanks for your effort nevertheless!