Allow to inject/mock `new \DateTime()` similar to time()
nextcloud/server pull request #11719
Opened 2018-10-09 13:25 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2018-10-09 13:28 UTC, rullzer approved these changes

2018-10-09 13:33 UTC, ChristophWurst requested changes

2018-10-09 13:33 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/TimeFactory.php
> +	 * @return \DateTime the result of a call to `new \DateTime()`
sounds mysterious, but I guess it will always be an object of type `DateTime` :wink:

2018-10-09 13:33 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/TimeFactory.php
> +	public function getDateTime(): \DateTime {
Can we add the optional params from https://secure.php.net/manual/de/datetime.construct.php? Sometimes you'll want to pass arguments to the constructor and then this API couldn't be used.

2018-10-09 13:37 UTC, nickvergessen commented on lib/private/AppFramework/Utility/TimeFactory.php
> +	 * @return \DateTime the result of a call to `new \DateTime()`
I just copy+pasted+adjusted the one from time()

2018-10-09 13:37 UTC, nickvergessen commented on lib/private/AppFramework/Utility/TimeFactory.php
> +	public function getDateTime(): \DateTime {
sure, will do

2018-10-09 13:39 UTC, ChristophWurst approved these changes
Awesome!

2018-10-09 20:43 UTC, rullzer commented
CI is not pleased

2018-10-10 06:00 UTC, ChristophWurst commented
```
PHP Fatal error:  Class Mock_ITimeFactory_8348b2a8 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\AppFramework\Utility\ITimeFactory::getDateTime) in phar:///usr/local/bin/phpunit/phpunit-mock-objects/Generator.php(264) : eval()'d code on line 1
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /usr/local/bin/phpunit:568
PHP   3. PHPUnit\TextUI\Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:148
PHP   4. PHPUnit\TextUI\TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:195
PHP   5. PHPUnit\Framework\TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:546
PHP   6. PHPUnit\Framework\TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:755
PHP   7. PHPUnit\Framework\DataProviderTestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:755
PHP   8. ExpirationTest->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:755
PHP   9. PHPUnit\Framework\TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:894
PHP  10. ExpirationTest->runBare() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:698
PHP  11. ExpirationTest->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:939
PHP  12. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:1071
PHP  13. ExpirationTest->testExpiration() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:1071
PHP  14. ExpirationTest->getMockedTimeFactory() /drone/src/github.com/nextcloud/server/apps/files_trashbin/tests/ExpirationTest.php:109
PHP  15. PHPUnit\Framework\MockObject\MockBuilder->getMock() /drone/src/github.com/nextcloud/server/apps/files_trashbin/tests/ExpirationTest.php:193
PHP  16. PHPUnit\Framework\MockObject\Generator->getMock() phar:///usr/local/bin/phpunit/phpunit-mock-objects/MockBuilder.php:118
PHP  17. PHPUnit\Framework\MockObject\Generator->getObject() phar:///usr/local/bin/phpunit/phpunit-mock-objects/Generator.php:200
PHP  18. PHPUnit\Framework\MockObject\Generator->evalClass() phar:///usr/local/bin/phpunit/phpunit-mock-objects/Generator.php:221
PHP 19. eval() phar:///usr/local/bin/phpunit/phpunit-mock-objects/Generator.php:264
```

2018-10-10 10:17 UTC, MorrisJobke commented
Still fails 🙈 

```
PHP Fatal error:  Class Mock_ITimeFactory_8ec7d831 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\AppFramework\Utility\ITimeFactory::getDateTime) in phar:///usr/local/bin/phpunit/phpunit-mock-objects/Generator.php(264) : eval()'d code on line 1
...
```

2018-10-10 10:42 UTC, nickvergessen commented
Ah of course versions uses the same weird test as trashbin.
Fixed versions too

2018-10-10 12:54 UTC, MorrisJobke approved these changes

2018-10-10 12:54 UTC, merged