always query the lookup server in a global scale setup
nextcloud/server pull request #11714
Opened 2018-10-09 12:32 UTC by schiessle

Check if global scale is enabled, in this case we should always query the lookup server. Further I improved the label of the result to look like `User Name (uid@nextcloudserver)`

2018-10-09 12:41 UTC, MorrisJobke commented
> Further I improved the label of the result to look like `User Name (uid@nextcloudserver)`

I'm a bit unsure about this, but for now it's fine. We should rethink how to show email, remote, global scale, user and group share presentation anyways as we discussed it at the conf.

2018-10-09 12:58 UTC, rullzer approved these changes

2018-10-09 14:21 UTC, MorrisJobke commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && $isGlobalScaleEnabled) {
Shouldn't this be like that?

```
$isLookupServerEnabled !== 'yes' && !$isGlobalScaleEnabled
```

Because it is:

```
neither lookup server is enabled nor global scale is enabled
```

Or did I miss something here?

2018-10-09 15:42 UTC, schiessle commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && $isGlobalScaleEnabled) {
hm, it worked during my tests as expected, but now I'm confused as well.. let me test it again

2018-10-09 15:48 UTC, schiessle commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && $isGlobalScaleEnabled) {
fixed

2018-10-10 07:03 UTC, MorrisJobke commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && !$isGlobalScaleEnabled) {
Would be a lot more readable if the `=== 'yes'` is added to line 60 and then the if statement only holds `!$isLookupServerEnabled && !$isGlobalScaleEnabled`.

Sorry for nitpicking, but readable code is worth it IMO.

2018-10-10 13:16 UTC, nickvergessen requested changes

2018-10-10 13:16 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				$remote = $this->cloudIdManager->resolveCloudId($lookup['federationId'])->getRemote();
try-catch

2018-10-10 13:16 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				if ($this->currentUserRemote === $remote) continue;
newline + brackets

2018-10-10 13:16 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				$name = isset($lookup['name']['value']) ? $lookup['name']['value'] : '';
use `??` operator, see backport

2018-10-10 13:57 UTC, schiessle commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && !$isGlobalScaleEnabled) {
good idea... will add it.

2018-10-10 14:07 UTC, schiessle commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				$name = isset($lookup['name']['value']) ? $lookup['name']['value'] : '';
yes, but honestly I consider the other one more readable so I will stick to it for now. All other points are addressed... Thanks for all the feedback!

2018-10-10 14:07 UTC, schiessle commented
@MorrisJobke @nickvergessen all comments are addressed

2018-10-12 08:55 UTC, blizzz requested changes

2018-10-12 08:55 UTC, blizzz commented on tests/lib/Collaboration/Collaborators/LookupPluginTest.php
> +			->with('gs.enabled', false)
can we have tests with gs.enabled = true, too, please?

2018-10-12 14:13 UTC, schiessle commented on tests/lib/Collaboration/Collaborators/LookupPluginTest.php
> +			->with('gs.enabled', false)
This will produce the exact same results, because the lookup server is enabled in all test cases :wink: But I added another test (see last commit) which might do what you meant...

2018-10-12 14:28 UTC, blizzz commented on tests/lib/Collaboration/Collaborators/LookupPluginTest.php
> +			->with('gs.enabled', false)
thanks :)

2018-10-15 08:28 UTC, schiessle commented on tests/lib/Collaboration/Collaborators/LookupPluginTest.php
> +			->with('gs.enabled', false)
@blizzz does this count as :+1: :wink:

2018-10-15 09:57 UTC, blizzz approved these changes
:elephant:

2018-10-15 10:14 UTC, merged