[stable14]  always query the lookup server in a global scale setup
nextcloud/server pull request #11723
Opened 2018-10-09 16:54 UTC by schiessle

backport of https://github.com/nextcloud/server/pull/11714

2018-10-10 06:54 UTC, MorrisJobke commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +		if ($isLookupServerEnabled !== 'yes' && !$isGlobalScaleEnabled) {
Would be a lot more readable if the `=== 'yes'` is added to line 60 and then the if statement only holds `!$isLookupServerEnabled && !$isGlobalScaleEnabled`.

Sorry for nitpicking, but readable code is worth it IMO.

2018-10-10 13:15 UTC, nickvergessen requested changes

2018-10-10 13:15 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				$remote = $this->cloudIdManager->resolveCloudId($lookup['federationId'])->getRemote();
`resolveCloudId` can throw, better wrap this in a try-catch too, so we get as many suggestions as possible?

2018-10-10 13:15 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				if ($this->currentUserRemote === $remote) continue;
newline+ brackets please

2018-10-10 13:15 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/LookupPlugin.php
> +				$name = isset($lookup['name']['value']) ? $lookup['name']['value'] : '';
Since we are now in php 7+ you can use:
```php
$name = $lookup['name']['value'] ?? '';
```

2018-10-12 08:57 UTC, blizzz commented
let's finish master first?

2018-10-12 09:23 UTC, closed without merging