Public API to get user acocunt data
nextcloud/server pull request #11740
Opened 2018-10-10 14:33 UTC by juliushaertl

This adds a readonly API to public namespace to allow apps to access the user account data.

2018-10-10 15:20 UTC, ChristophWurst reviewed
I know, I know, this is not labeled to be reviewed yet, but I couldn't resist to give feedback :wink:

2018-10-10 15:20 UTC, ChristophWurst commented on lib/private/Accounts/Account.php
> +		return $this->properties;
FYI this method is expected to return a plain php array, so it should probably use `array_map` to convert props to arrays as well ;)

2018-10-10 15:20 UTC, ChristophWurst commented on lib/private/Accounts/Account.php
> +class Account implements IAccount, \JsonSerializable {
FYI: if the JSON serialization should also be available for apps, the public interface should extend `JsonSerializable`

2018-10-10 17:13 UTC, juliushaertl commented on lib/private/Accounts/Account.php
> +class Account implements IAccount, \JsonSerializable {
Yes, makes sense to have it in the interface of course.

2018-10-10 17:15 UTC, juliushaertl commented on lib/private/Accounts/Account.php
> +		return $this->properties;
Since properties are just objects which also implement JsonSerializable, they will be automatically converted as well.

2018-10-10 17:19 UTC, ChristophWurst commented on lib/private/Accounts/Account.php
> +		return $this->properties;
You're right, if you pass them to https://secure.php.net/manual/de/jsonserializable.jsonserialize.php it should be fine :+1:

2018-10-10 17:28 UTC, juliushaertl commented
> I know, I know, this is not labeled to be reviewed yet, but I couldn't resist to give feedback 

Totally fine for me :wink:

2018-10-10 20:22 UTC, rullzer submitted a review, later dismissed

2018-10-11 08:56 UTC, juliushaertl commented on lib/private/Accounts/AccountProperty.php
> +	private $name;
:+1:

2018-10-11 08:56 UTC, juliushaertl commented on lib/public/Accounts/IAccountProperty.php
> +	 * @return void
Yes, good idea. Done.

2018-10-11 08:57 UTC, juliushaertl commented on lib/private/Accounts/Account.php
> +/**
I moved it from below the copyright to the beginning of the file.

2018-10-11 12:16 UTC, juliushaertl commented
Ready for review.

2018-10-11 12:23 UTC, ChristophWurst requested changes
Looks good otherwise :)

2018-10-11 12:31 UTC, juliushaertl commented on lib/public/Accounts/IAccountManager.php
> +	const NOT_VERIFIED = '0';
They all come from the \OC\Accounts\AccountManager, and are used in the internal implementation like this. I didn't want to change to much on that.

2018-10-11 12:32 UTC, rullzer commented on lib/public/Accounts/IAccountManager.php
> +	const NOT_VERIFIED = '0';
Fair enough

2018-10-11 12:32 UTC, rullzer commented on lib/private/Accounts/Account.php
> +		return $this->properties[$property];
Exception time I guess ;)

2018-10-11 12:33 UTC, juliushaertl commented on lib/private/Accounts/AccountProperty.php
> +			'value' => $this->value,
The name is always available from the data given by the Account class, but yes, it makes sense to have it in the serialized array as well.

2018-10-11 18:38 UTC, rullzer approved these changes
Cool stuff!

2018-10-12 06:31 UTC, ChristophWurst approved these changes
Looks great :+1: 

I'd appreciate if you could squash your commits :)

2018-10-12 06:31 UTC, ChristophWurst commented on lib/private/Accounts/Account.php
> +		if (!array_key_exists($property, $this->properties)) {
perfect :+1:

2018-10-12 07:31 UTC, juliushaertl commented
@ChristophWurst Squashed them :wink:

2018-10-12 08:32 UTC, MorrisJobke commented
```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2018-10-12 10:17 UTC, nickvergessen commented on tests/lib/Accounts/AccountPropertyTest.php
> +			AccountManager::PROPERTY_WEBSITE,
should use them from IAccountManager to make sure they are not removed there?

2018-10-15 07:17 UTC, MorrisJobke commented on tests/lib/Accounts/AccountPropertyTest.php
> +			AccountManager::PROPERTY_WEBSITE,
@juliushaertl Mind to look into this final comment and then we can merge this. 😉

2018-10-15 11:32 UTC, juliushaertl commented on tests/lib/Accounts/AccountPropertyTest.php
> +			AccountManager::PROPERTY_WEBSITE,
@nickvergessen Done.

2018-10-15 18:51 UTC, juliushaertl commented
Failing tests unrelated:

> sh: 1: kill: No such process

2018-10-15 19:46 UTC, merged