Fix illegible text color in columns Size and Modified on dark theme
nextcloud/server pull request #11823
Opened 2018-10-14 11:51 UTC by lex111

Resolves #11441

![image](https://user-images.githubusercontent.com/4408379/46916249-924d2580-cfc0-11e8-9d0c-b9dfa290d815.png)

2018-10-16 07:40 UTC, skjnldsv approved these changes
Very simple, I really like it :)

2018-10-16 09:02 UTC, juliusknorr requested changes

2018-10-16 09:02 UTC, juliushaertl commented on lib/private/Template/JSConfigHelper.php
> +				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
I'm not sure if we should add more app dependencies into the server. Also themeName is kind of confusing, since a theme is actually something different.

@skjnldsv Maybe we can make the accessibility app expose a global namespace for that usecase, similar to the theming app: https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php#L434-L451

Something like:
```
OCA.Accessibility.Config = {
    theme: 'dark'
}
```

2018-10-16 09:14 UTC, lex111 commented on lib/private/Template/JSConfigHelper.php
> +				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
@juliushaertl I can do this, i.e. add `theme` property in `OCA.Theming`?

2018-10-16 12:28 UTC, juliushaertl commented on lib/private/Template/JSConfigHelper.php
> +				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
It should be in the accessibility app, since the theming app could be disabled and we still want accessibility to work.

2018-10-16 12:57 UTC, lex111 commented on lib/private/Template/JSConfigHelper.php
> +				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
You mean the `AccessibilityController` controller?

2018-10-16 18:43 UTC, lex111 commented on lib/private/Template/JSConfigHelper.php
> +				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
Hi @juliushaertl 

I reworked my PR the way you wanted, can you look please?

2018-10-17 13:33 UTC, lex111 commented
Hi guys, please watch this PR :smiley:

2018-10-18 07:25 UTC, jancborchardt approved these changes
Looks good to me, great work @lex111!

2018-10-18 14:23 UTC, juliusknorr approved these changes

2018-10-18 17:55 UTC, lex111 commented
@juliushaertl done :heavy_check_mark:

2018-10-19 07:11 UTC, lex111 commented
friendly ping @denismosolov I'm not late? :smile:

2018-10-19 11:51 UTC, skjnldsv commented
> Yes, fine by me now. Does this also work for you @skjnldsv ?

Good for me ;)

2018-10-19 13:31 UTC, merged

2018-10-19 13:32 UTC, MorrisJobke commented
> Good for me ;)

Then press also the green button ;)

2018-10-19 14:19 UTC, denismosolov commented
> friendly ping @denismosolov I'm not late?

You're rock!