allow to create multiple link shares via share api
nextcloud/server pull request #11844
Opened 2018-10-15 10:45 UTC by schiessle

- [ ] Allow to create multiple share links with the ocs api
- [ ] Get multiple share links with the OCS API
- [ ] Allow to create multiple share links in the web ui
- [ ] Show multiple share links in the web up
- [ ] allow to give share links unique names

2018-10-17 08:56 UTC, schiessle commented
cc @AndyScherzinger  @tobiasKaminsky @marinofaggiana @camilasan @rullzer  With Nextcloud 15 we will support multiple share links. This PR has already implement everything you need to start implementing it on the client. Just in case you looking for something to do :wink: 

Creating links works the same as before. There is just one additional parameter you can use "label" to create/update link shares so that the user can give the share link names to remember which link was used for what.

2018-10-18 10:41 UTC, marinofaggiana commented
ToDo added :-)

2018-10-29 07:42 UTC, skjnldsv commented on core/Migrations/Version13000Date20170718121200.php
> +			$table->addColumn('label', 'string', [
Hum, shouldn't we create a newer file for that?

2018-10-31 09:57 UTC, skjnldsv commented
Should be finished today!
@jancborchardt @nextcloud/designers Can we try to find another saying for "Share link" I'm always finding this confusing as it looks like an action and not a statement :)


Can you start a review now?
That would increase my response time to fixes to day for the feature freeze :)

Basically the only thing left is the label handling! How should we do that?
1. Add an edit button?
2. In the popovermenu?

2018-10-31 11:17 UTC, jancborchardt commented
Just beginning to test this! :) First feedback:
- The ➕ icon is not keyboard-accessible, no highlight on focus
- Ideally the whole row should be clickable, not just the ➕
- Not sure it’s screenreader-accessible right now with the "title" on the icon. But it would be when the whole row is the action.

2018-10-31 11:24 UTC, jancborchardt commented
Made the background of the share link primary color instead of bland grey. This is in line with the change in the Talk app at https://github.com/nextcloud/spreed/pull/1274

2018-10-31 15:21 UTC, skjnldsv commented
> Made the background of the share link primary color instead of bland grey. This is in line with the change in the Talk app at [nextcloud/spreed#1274](https://github.com/nextcloud/spreed/pull/1274)

I was afraid it would be too much, but it is spot on!! :+1:

2018-10-31 17:02 UTC, skjnldsv commented
@nextcloud/designers please review!
What to test:
1. public sharing
2. with expire date enforced
3. with password open by default
4. with password enforced
5. with default expire date 
6. note management

It is still missing the label, but I rather have early feedback to fix things asap!

2018-10-31 17:08 UTC, skjnldsv commented
> * Ideally the whole row should be clickable, not just the heavy_plus_sign

I'm afraid putting the click to the whole row will also trigger other stuff in the children (popover or such) I thing I will rather keep it on the button only to avoid creating issues :(

2018-10-31 18:52 UTC, rullzer commented
The hide download checkbox does not work anymore

(is only there for file shares now)

2018-10-31 19:21 UTC, schiessle commented
> Basically the only thing left is the label handling! How should we do that?
> 1. Add an edit button?
> 2. In the popovermenu?

My suggestion would be to have a "rename" action in the "..." menu. Which behaves similar to renaming a file/folder. If you click the rename action the popover closes and the label "share link" turns into a input field where the user can change the name and press enter or focus out.

2018-10-31 19:22 UTC, rullzer commented on core/js/sharedialoglinkshareview.js
> +			var $element = $(event.target);
event is not defined here.

2018-10-31 19:28 UTC, rullzer approved these changes
Gave it a test round. Works as advertised.

Lets fix the rest later and get this in so it doesn't grow more in size :wink:

2018-11-01 02:17 UTC, jancborchardt commented
Pushed some sorting order and wording fixes! Someone needs to build the handlebars stuff though as I am getting errors and there is no docs! (Currently stuck at `Error: Cannot find module 'optimist'`)

----------------------

> My suggestion would be to have a "rename" action in the "..." menu. Which behaves similar to renaming a file/folder. If you click the rename action the popover closes and the label "share link" turns into a input field where the user can change the name and press enter or focus out.

> Yes, I also like this, but the menu is already very filled :(

I would agree with @schiessle here to put it in the  3-dot menu but to be honest this function is just utterly useless.

 -------------------

Because I’m a bit annoyed at this shoveling of stuff into menus and sidebars yet again, I opened an issue for cleaning up that popovermenu: https://github.com/nextcloud/server/issues/12178

Bottom line: We need to stop just stupidly adding stuff! No one will be able to find their favorite custom setting among all the other custom settings. It’s nuts!

2018-11-01 03:48 UTC, danxuliu commented
>  Someone needs to build the handlebars stuff 

Done.

Besides that I have cleaned up a little the commit history; the code is almost the same as it was before, except for a removed `console.error(e)` (because it was the only content of a commit named _Various fixes_, so I dropped it), an updated documentation to reflect that `ShareItemModel` no longer has the attributes `isLinkShare` and `link`, and a "cast" of the attribute `hideDownload` to a boolean from the int `share.hide_download`.

@skjnldsv If you already made a commit to fix the JavaScript unit tests cherry-picking it on top of the current commits should cause no conflicts.

2018-11-01 03:57 UTC, danxuliu submitted a review, later dismissed
JavaScript unit tests need to be fixed before merging.

Besides that, adding a new link share after the first one does not work when passwords are enforced (the menu to set the password is not shown).

2018-11-01 03:57 UTC, danxuliu commented on core/js/shareitemmodel.js
>  						}
All the code above to set the link is now dead code, because the `link` attribute is no longer set in the share (and the `url` attribute is now used instead of `link` when copying the link to the clipboard); I do not know what that _pre-token_ thing is, though, and if it can be safely replaced by the URL attribute returned by the server.

2018-11-01 05:39 UTC, skjnldsv commented on core/js/shareitemmodel.js
>  						}
No idea. I usually don't want to touch too much here. 😂

2018-11-01 06:00 UTC, skjnldsv commented
> Besides that, adding a new link share after the first one does not work when passwords are enforced (the menu to set the password is not shown).

Nice catch!!

Thanks a lot for the fixes! You two are completely crazy working through the night :(
You need to sleep!

2018-11-01 11:23 UTC, MorrisJobke approved these changes
Tested and works nice 👍 Current state is also perfectly fine to be merged and iterated on later

2018-11-01 11:35 UTC, danxuliu commented
@jancborchardt By the way, same problem as described in https://github.com/nextcloud/spreed/pull/1274#pullrequestreview-170646080:
![share-link-icon-theming-color-white](https://user-images.githubusercontent.com/26858233/47849559-601a3100-ddd2-11e8-90bb-e58d330e3232.png)

2018-11-01 15:52 UTC, danxuliu requested changes
>  Fixed

Not so fast; I have some complaints ;-)

2018-11-01 16:19 UTC, skjnldsv commented
@danxuliu be quick!
I want to get this in today! And don't use this as an excuse to merge your pr before mine :p

2018-11-01 16:28 UTC, danxuliu submitted a review, later dismissed

2018-11-01 16:28 UTC, danxuliu commented on core/js/tests/specs/sharedialoglinkshareview.js
> +					id: 123
Are all the parameters above needed for the tests? Or is it enough to just give the id?

2018-11-01 16:28 UTC, danxuliu commented on core/js/tests/specs/sharedialoglinkshareview.js
>  			$hideDownloadCheckbox = view.$el.find('.hideDownloadCheckbox');
No `data-share-id` used here even if the id `321` was used in `shareModel.set` above; maybe it is unneeded in the other test too?

2018-11-01 16:28 UTC, danxuliu commented on core/js/tests/specs/sharedialogviewSpec.js
> +					url: link,
The link is now got from the share returned by the server, so it can be hardcoded like the other parameters; no need to generate it above.

2018-11-01 17:55 UTC, skjnldsv commented on core/js/sharedialoglinkshareview.js
> +			if(window.oc_capabilities && oc_capabilities.password_policy && oc_capabilities.password_policy.minLength) {
Because it seems there is an issue between the declaration of variables and window.xxx :)

2018-11-01 17:55 UTC, skjnldsv commented on core/js/tests/specs/sharedialoglinkshareview.js
> -			// Setting the item type also triggers the rendering
No, I changed it because it was unnecessary.
This is done on purpose.

2018-11-01 18:04 UTC, skjnldsv commented on core/js/tests/specs/sharedialoglinkshareview.js
> +			expect(shareModel.saveLinkShare.calledOnce).toBeTruthy();
None, forgot to edit ;)

2018-11-01 18:05 UTC, skjnldsv commented on core/js/tests/specs/sharedialoglinkshareview.js
> +					id: 123
No idea if they're needed. The id is at least yes.

2018-11-01 18:09 UTC, skjnldsv commented on core/js/tests/specs/sharedialoglinkshareview.js
>  			$hideDownloadCheckbox = view.$el.find('.hideDownloadCheckbox');
It is! :)
There is only one share, so it doesn't really matter ;)

2018-11-01 18:42 UTC, danxuliu requested changes
>  Fixed :D

Almost :-P I will send a final fix.

2018-11-01 19:10 UTC, skjnldsv commented
Failure unrelated: `sh: 1: kill: No such process` https://drone.nextcloud.com/nextcloud/server/12248/283

2018-11-01 19:10 UTC, skjnldsv commented
> Almost :-P I will send a final fix.

Ahaha! Okay :)
Thanks a lot for your help @danxuliu :hugs:

2018-11-01 20:43 UTC, danxuliu commented on core/js/sharedialoglinkshareview.js
> +			if(window.oc_capabilities && oc_capabilities.password_policy && oc_capabilities.password_policy.minLength) {
OK, but the regular code is not the place to address that ;-) Values set by [JSConfigHelper](https://github.com/nextcloud/server/blob/master/lib/private/Template/JSConfigHelper.php#L161) should be set in the JavaScript unit tests in [specHelper.js](https://github.com/nextcloud/server/blob/4a0b7aaf6c80f59552b1da861432476a8ac4c7cf/core/js/tests/specHelper.js#L86)

2018-11-01 20:48 UTC, danxuliu commented on core/js/tests/specs/sharedialoglinkshareview.js
> -			// Setting the item type also triggers the rendering
Ha, I can see through your lies! :-P [Setting the item type still triggers the rendering](https://github.com/nextcloud/server/pull/11844/files#diff-da7df34db49581af77bd59e4f269dc36R88) ;-)

Setting the link share does no longer trigger the rendering, though; although you did not that on purpose, it was a side effect of renaming the `linkShare` attribute to `linkShares` in the model :-P (I also [removed the event handler](https://github.com/nextcloud/server/pull/11844/files#diff-da7df34db49581af77bd59e4f269dc36L92) because it was no longer used).

2018-11-01 20:48 UTC, danxuliu commented on core/js/tests/specs/sharedialoglinkshareview.js
> +					id: 123
No, they were not, so I removed them everywhere ;-)

2018-11-01 20:50 UTC, danxuliu approved these changes
Rejoice; finally, the nitpicker is _reasonably_ satisfied :+1:

I hope Drone is too... :-P

2018-11-01 21:01 UTC, MorrisJobke commented
🎉 I will merge once drone has done it's job 🎉

2018-11-01 21:09 UTC, skjnldsv commented on core/js/sharedialoglinkshareview.js
> +			if(window.oc_capabilities && oc_capabilities.password_policy && oc_capabilities.password_policy.minLength) {
You learn something everyday!
Well, calling the variable or the window.xxx is the same when declared as global :)

2018-11-01 21:12 UTC, skjnldsv commented on core/js/sharedialoglinkshareview.js
> +			if(window.oc_capabilities && oc_capabilities.password_policy && oc_capabilities.password_policy.minLength) {
Done

2018-11-01 21:36 UTC, merged

2019-05-03 17:34 UTC, lopezio commented
> Future interface stuff that is optional:
> > * [ ]  allow to give share links unique names (web ui)
> > * [ ]  allow to change unique name of a share (web ui)

@schiessle @jancborchardt any progress on these points..? I think they're fundamental to make the multiple linking functionality usable..  with some kind of distinction between the shared links it would be possible to explicitely delete or re-share links based on a target public / individual..

Best Regards!