Set Webpack nonce globally for all apps
nextcloud/server pull request #11846
Opened 2018-10-15 12:00 UTC by ChristophWurst

Ref https://github.com/nextcloud/server/pull/11842#discussion_r225133640.

2018-10-15 12:09 UTC, rullzer approved these changes

2018-10-15 17:59 UTC, juliusknorr approved these changes

2018-10-15 18:23 UTC, juliusknorr requested changes
Seems I have been testing with some cache on the first run. I actually don't have any nonce set on the script tag and the loading still fails.

2018-10-16 09:43 UTC, ChristophWurst commented
@juliushaertl you're right. I wrongly assumed the nonce variable would be a global one. Turns out this has to be set in the entry file and not outside. This PR is therefore invalid, this doesn't work.

2018-10-16 09:43 UTC, closed without merging