Collaboration resources
nextcloud/server pull request #11871
Opened 2018-10-16 15:50 UTC by nickvergessen

2019-01-16 14:17 UTC, nickvergessen commented on apps/files/lib/Collaboration/Resources/ResourceProvider.php
> +			$this->nodes[(int) $resource->getId()] = array_shift($nodes);
First steps first.

The problem I have with this how does removing work?

2019-01-31 10:54 UTC, juliushaertl commented
I've added a screencast of the current UI to the first post: https://github.com/nextcloud/server/pull/11871#issue-223303705 

Please have a look @nextcloud/designers 

@nickvergessen Please have a look as well :wink: 

- We still need to find a way to properly search for collections of a given user: https://github.com/nextcloud/server/pull/11871/files#diff-c0ede1133f7267a466a21eb7ee0e65ceR85
- Permission handling still needs to be sorted out
- Allow apps that don't have a dedicated selection UI (like the file picker) to register a search handler for their resources

Apart from that I think this is a good start for this feature.

2019-01-31 11:16 UTC, nickvergessen commented on apps/files_sharing/src/components/ResourceListItem.vue
> +			<a href="" v-tooltip="'Design projet overview'"><span class="nav-icon-files"></span></a>
opsy?

2019-01-31 11:16 UTC, nickvergessen commented on apps/files_sharing/src/views/CollaborationView.vue
> +		<pre>Vue component file model: {{ this.$root.model.name }} </pre>
?

2019-01-31 15:05 UTC, juliushaertl commented on apps/files_sharing/src/components/ResourceListItem.vue
> +			<a href="" v-tooltip="'Design projet overview'"><span class="nav-icon-files"></span></a>
This is an older version :confused: It is not in the branch anymore

2019-01-31 15:05 UTC, juliushaertl commented on apps/files_sharing/src/views/CollaborationView.vue
> +		<pre>Vue component file model: {{ this.$root.model.name }} </pre>
Same here

2019-01-31 15:06 UTC, nickvergessen commented on apps/files_sharing/src/components/ResourceListItem.vue
> +			<a href="" v-tooltip="'Design projet overview'"><span class="nav-icon-files"></span></a>
Yeah sorry, I guess I looked at the individual commits :see_no_evil:

2019-01-31 15:07 UTC, nickvergessen commented
Conflicts

2019-02-11 12:10 UTC, nickvergessen commented
Access cache should be working now for most things.
If you search the first time and a lot of collections with resources where created already, it is still bad, but we can't really help that.

2019-02-11 16:17 UTC, jancborchardt commented
@juliushaertl looking good generally, nice work! :) The icon-delete would better be `icon-close` X since it does not delete the file but only removes the connection?

2019-02-14 13:52 UTC, juliushaertl commented
@nickvergessen There seem to be some issues with the query when fetching collections / creating collections. The frontend is already working for testing btw, just make sure to run `npm install` and `npm run build` for the core bundle as well as in apps/files_sharing/

```
{"reqId":"QF8IBqEeO2jUbM1L99OQ","level":3,"time":"2019-02-14T13:45:30+00:00","remoteAddr":"192.168.21.1","user":"admin","app":"no app in context","method":"POST","url":"\/ocs\/v2.php\/collaboration\/resources\/collections\/1?format=json","message":{"Exception":"Doctrine\\DBAL\\Query\\QueryException","Message":"The given alias '`r`' is not part of any FROM or JOIN clause table. The currently registered aliases are: `*PREFIX*collres_collections`.","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":1179,"function":"unknownAlias","class":"Doctrine\\DBAL\\Query\\QueryException","type":"::","args":["`r`",["`*PREFIX*collres_collections`"]]},{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":1165,"function":"verifyAllAliasesAreKnown","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[{"`*PREFIX*collres_collections`":true}]},{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":1125,"function":"getFromClauses","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":257,"function":"getSQLForSelect","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":219,"function":"getSQL","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Collaboration\/Resources\/Manager.php","line":95,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/html\/core\/Controller\/CollaborationResourcesController.php","line":62,"function":"getCollectionForUser","class":"OC\\Collaboration\\Resources\\Manager","type":"->","args":[1,{"__class__":"OC\\User\\User"}]},{"file":"\/var\/www\/html\/core\/Controller\/CollaborationResourcesController.php","line":113,"function":"getCollection","class":"OC\\Core\\Controller\\CollaborationResourcesController","type":"->","args":[1]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"addResource","class":"OC\\Core\\Controller\\CollaborationResourcesController","type":"->","args":[1,"files","134"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\CollaborationResourcesController"},"addResource"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\CollaborationResourcesController"},"addResource"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\CollaborationResourcesController","addResource",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"collectionId":"1","_route":"ocs.core.CollaborationResources.addResource"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"collectionId":"1","_route":"ocs.core.CollaborationResources.addResource"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"collectionId":"1","_route":"ocs.core.CollaborationResources.addResource"}]},{"file":"\/var\/www\/html\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/ocsapp\/collaboration\/resources\/collections\/1"]},{"file":"\/var\/www\/html\/ocs\/v2.php","line":24,"args":["\/var\/www\/html\/ocs\/v1.php"],"function":"require_once"}],"File":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryException.php","Line":38,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.96 Safari\/537.36","version":"16.0.0.1"}
{"reqId":"QlzDeFbx0WInqXf2NDxY","level":3,"time":"2019-02-14T13:36:53+00:00","remoteAddr":"192.168.21.1","user":"admin","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/collaboration\/resources\/files\/129?format=json","message":{"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'SELECT `r`.*, `a`.`access` FROM `oc_collres_resources` `r` LEFT JOIN `oc_collres_accesscache` `a` ON (`r`.`id` = `a`.`resource_id`) AND (`a`.`user_id` = ?) WHERE (`r`.`resource_type` = ?) AND (`r`.`resource_id` = ?)' with params [\"admin\", \"files\", \"129\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.id' in 'on clause'","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'SELECT `r`.*, `a`.`access` FROM `oc_collres_resources` `r` LEFT JOIN `oc_collres_accesscache` `a` ON (`r`.`id` = `a`.`resource_id`) AND (`a`.`user_id` = ?) WHERE (`r`.`resource_type` = ?) AND (`r`.`resource_id` = ?)' with params [\"admin\", \"files\", \"129\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.id' in 'on clause'",{"errorInfo":["42S22",1054,"Unknown column 'r.id' in 'on clause'"],"xdebug_message":"<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )<\/span> Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.id' in 'on clause' in \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php on line <i>143<\/i><\/th><\/tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack<\/th><\/tr>\n<tr><th align='center' bgcolor='#eeeeec'>#<\/th><th align='left' bgcolor='#eeeeec'>Time<\/th><th align='left' bgcolor='#eeeeec'>Memory<\/th><th align='left' bgcolor='#eeeeec'>Function<\/th><th align='left' bgcolor='#eeeeec'>Location<\/th><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>1<\/td><td bgcolor='#eeeeec' align='center'>0.0003<\/td><td bgcolor='#eeeeec' align='right'>362328<\/td><td bgcolor='#eeeeec'>{main}(  )<\/td><td title='\/var\/www\/html\/ocs\/v2.php' bgcolor='#eeeeec'>...\/v2.php<b>:<\/b>0<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>2<\/td><td bgcolor='#eeeeec' align='center'>0.0003<\/td><td bgcolor='#eeeeec' align='right'>363192<\/td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'\/var\/www\/html\/ocs\/v1.php'<\/font> )<\/td><td title='\/var\/www\/html\/ocs\/v2.php' bgcolor='#eeeeec'>...\/v2.php<b>:<\/b>24<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>3<\/td><td bgcolor='#eeeeec' align='center'>0.3872<\/td><td bgcolor='#eeeeec' align='right'>5994936<\/td><td bgcolor='#eeeeec'>OC\\Route\\Router->match(  )<\/td><td title='\/var\/www\/html\/ocs\/v1.php' bgcolor='#eeeeec'>...\/v1.php<b>:<\/b>82<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>4<\/td><td bgcolor='#eeeeec' align='center'>0.3882<\/td><td bgcolor='#eeeeec' align='right'>5997008<\/td><td bgcolor='#eeeeec'><a href='http:\/\/www.php.net\/function [...]

2019-02-20 18:21 UTC, juliushaertl commented
@nickvergessen I tried to fix some more issues with the access cache joins. Seems to work now except for two issues, maybe you can have a look at those:

- When adding a resource to a collection the access cache entries for the collections resources get duplicated
- Access cache entries for collections are never added to the access cache

2019-02-21 12:55 UTC, nickvergessen commented
Also todo:
* Add listener to group membership changes and purge for the user in that case.
* File sharing should purge access cache when a share is added/removed

2019-02-22 14:14 UTC, nickvergessen commented
I think the backend should be ready now

2019-02-24 14:47 UTC, juliushaertl commented
@nickvergessen Tests should be fine now. I also fixed another issue with the name missing in the file provider. I'll squash my commits a bit once the tests are happy.

Otherwise ready to review.

2019-02-25 06:06 UTC, juliushaertl commented
Ok still some failures, I'll have another look.

2019-02-25 09:00 UTC, juliushaertl commented on lib/private/Files/View.php
> +			$ownerId = $storage->getOwner($internalPath);
@rullzer Does this make sense? It seems with limited access token permissions getOwner returns null.

2019-02-26 16:37 UTC, juliushaertl commented
Lets see, jsunit tests are fixed, acceptance tests run fine locally.

2019-03-01 08:08 UTC, rullzer requested changes
Besides the 2 extra files. Looks good.

2019-03-01 08:08 UTC, rullzer commented on apps/files_sharing/package.json
> +{
This file need to go

2019-03-01 08:08 UTC, rullzer commented on apps/files_sharing/package-lock.json
> +{
Not needed kill it

2019-03-01 12:10 UTC, juliushaertl commented on apps/files_sharing/package-lock.json
> +{
Thanks, fixed.

2019-03-01 12:12 UTC, juliushaertl commented
Rebased and removed the duplicate package.json

2019-03-01 17:40 UTC, nickvergessen commented
@juliushaertl :+1: ? I cant since its my pr 🙈

2019-03-01 20:12 UTC, juliusknorr approved these changes

2019-03-01 20:22 UTC, rullzer approved these changes
Lets do this!

2019-03-01 20:22 UTC, merged