Formats file sizes using the user's locale
nextcloud/server pull request #11893
Opened 2018-10-17 19:45 UTC by caugner

Fixes #7837

2018-10-17 19:47 UTC, caugner commented
Before:
![image](https://user-images.githubusercontent.com/495429/47112288-36033380-d256-11e8-8885-6aa998a31436.png)

After:
![image](https://user-images.githubusercontent.com/495429/47112267-208e0980-d256-11e8-95bf-8e9b0aed4040.png)

2018-10-17 20:23 UTC, rullzer approved these changes
Awesome.
And with tests :) :heart:

2018-10-17 21:48 UTC, caugner commented
Unfortunately the test fails (I tried to run them locally, but `phantom` failed to spawn, I'm using NixOS, which doesn't support running the downloaded binaries):

![image](https://user-images.githubusercontent.com/495429/47118183-d8c3ae00-d266-11e8-80f2-c9a6cb8da850.png)

I have two possible explanations:

1. Either my `sinon.stub(OC, 'getLocale')` approach doesn't work.
2. Or `phantomjs` doesn't support `toLocaleString` (at least not with the specified locale `de`).

2018-10-18 03:56 UTC, danielkesselberg commented
>     2. Or `phantomjs` doesn't support `toLocaleString` (at least not with the specified locale `de`).

https://github.com/ariya/phantomjs/issues/12581#issuecomment-166645579 :sad

2018-10-18 06:31 UTC, ChristophWurst commented
> First-time contributor

Awesome first-time contribution :v: Thanks a lot :rocket:

2018-10-18 09:47 UTC, MorrisJobke approved these changes

2018-10-18 09:47 UTC, MorrisJobke requested changes
Nice 👍 but it does not work with something like `de_DE`:

```js
parseFloat('8.5').toLocaleString('de_DE');

RangeError: invalid language tag: de_DE
```

I still have no idea how to work around this phantomJS limitation :/ Maybe @danxuliu or @skjnldsv can help here

2018-10-18 10:01 UTC, caugner commented
@MorrisJobke Yes, looks like we need to convert the Nextcloud locale we get from `OC.getLocale()` into a BCP-47 compliant language tag (which uses a dash instead of an underscore to separate language code from region code): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument

2018-10-19 08:45 UTC, rullzer commented
I would be fine to get this in for now. If phantomjs doesn't play nice then so be it.

2018-10-19 10:11 UTC, caugner reviewed
Need to cover case where `getLocale()` is undefined.

2018-10-19 10:11 UTC, caugner commented on core/js/js.js
> +		return this.getLocale().replace(/_/g, '-');
getLocale() can be undefined
```suggestion
		var locale = this.getLocale();
		return typeof locale === 'string' ? locale.replace(/_/g, '-') : locale;
```

2018-10-19 10:15 UTC, caugner reviewed
Took stub fallback value from wrong method.

2018-10-19 10:15 UTC, caugner commented on core/js/tests/specs/coreSpec.js
> +			locale = OC.getLocale();
Use `OC.getCanonicalLocale()` here.

```suggestion
			locale = OC.getCanonicalLocale();
```

2018-10-24 07:10 UTC, rullzer commented
I took the liberty of rebasing

2018-10-24 07:14 UTC, ChristophWurst approved these changes
Nice enhancement. Code looks good and is covered by tests -> :+1:

2018-10-24 07:16 UTC, skjnldsv approved these changes

2018-10-24 09:11 UTC, caugner commented on core/js/tests/specs/coreSpec.js
> +			expect(OC.getCanonicalLocale('de')).toEqual('de');
Rather than calling `getCanonicalLocale` with the locale as a parameter, set the `localeStub` to return this locale.

2018-10-24 09:11 UTC, caugner commented on core/js/tests/specs/coreSpec.js
> +			expect(OC.getCanonicalLocale('az_Cyrl_AZ')).toEqual('az-Cyrl-AZ');
dito

2018-10-24 09:11 UTC, caugner reviewed
Need to fix test for `getCanonicalLocale`

2018-10-24 09:14 UTC, caugner commented on core/js/tests/specs/coreSpec.js
> +			expect(OC.getCanonicalLocale('zu')).toEqual('zu');
```suggestion
			localeStub.returns('zu');
			expect(OC.getCanonicalLocale()).toEqual('zu');
```

2018-10-24 09:14 UTC, caugner commented on core/js/tests/specs/coreSpec.js
> +			expect(OC.getCanonicalLocale('de_DE')).toEqual('de-DE');
```suggestion
			localeStub.returns('de_DE');
			expect(OC.getCanonicalLocale()).toEqual('de-DE');
```

2018-10-24 12:45 UTC, MorrisJobke commented
There is still an error in the JSUnit tests :'(

2018-10-25 08:46 UTC, caugner commented
@MorrisJobke Looks like a test artefact to me: https://drone.nextcloud.com/nextcloud/server/11798/284

Is there an easy way to trigger another CI run?

2018-10-25 09:01 UTC, skjnldsv commented
@caugner https://drone.nextcloud.com/nextcloud/server/11833/283

2018-10-25 11:51 UTC, danxuliu commented
>  Looks like either a test artefact or an unrelated test failing

Unrelated; fix is in #12039 ;-)

2018-10-25 12:04 UTC, MorrisJobke commented
> Unrelated; fix is in #12039 ;-)

@caugner Mind to rebase on current master as the fix was merged 😉

2018-10-25 12:05 UTC, MorrisJobke commented
> > 
> 
> @caugner Mind to rebase on current master as the fix was merged 😉

I just had a look and it is exactly the same stack trace -> merging.

2018-10-25 12:05 UTC, merged

2018-10-25 12:06 UTC, MorrisJobke commented
@caugner Thanks for your contribution. You could have a look at other nice starter issues if you wish so: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

I will also invite you to the Nextcloud organization here ;)