Change typeface to Nunito
nextcloud/server pull request #11932
Opened 2018-10-19 10:29 UTC by jancborchardt

Based on discussions we had, most recently in https://github.com/nextcloud/server/issues/11873

- :abc: Change typeface from Open Sans to Nunito → its rounded design works well with our branding, and it also gives a much friendlier feel. 😊
- :eyes: Move from Light/Semibold to Regular/Bold for better readability 
- :control_knobs: Change main text color from harsh `#000000` to `#222222`

![screenshot from 2018-10-19 12-26-32](https://user-images.githubusercontent.com/925062/47213079-3c9ac380-d39a-11e8-8e2e-b7ec29075d20.png)

2018-10-19 11:41 UTC, skjnldsv commented
I really like it as well!
Could we also rethink our headings at the same time? Since we're changig the font, so we can really have differences between h1,h2,h3 and h4? Pleaaaase @jancborchardt :see_no_evil: ;)

:tada:

2018-10-19 12:00 UTC, MorrisJobke commented
It is far better to read with this on a full HD screen over here.

2018-10-19 12:54 UTC, karlitschek commented
looks good 👍

2018-10-19 13:19 UTC, jancborchardt commented
@skjnldsv that’s a different discussion – let’s work on things step by step. :)

@MorrisJobke @jospoortvliet @karlitschek could I have your approving review then? ;)

Others from @nextcloud/designers please also check it out!

2018-10-19 14:47 UTC, jancborchardt commented
> What is wrong with ttf?

@MorrisJobke according to caniuse:

> WOFF: Compressed TrueType/OpenType font that contains information about the font's source.
> WOFF2: TrueType/OpenType font that provides better compression than WOFF 1.0.

So quicker loading times. Nunito Regular+Bold in ttf is 230 kB, whereas in woff2 (with latin extended even) it’s 77 kB.

But alas – different topic. :)

2018-10-20 16:16 UTC, skjnldsv approved these changes
Awesome!! Nice that the font loading is prioritised now :)

2018-10-23 09:57 UTC, jancborchardt commented
@juliushaertl @karlitschek @MorrisJobke @jospoortvliet so can I have your approving reviews? ;) The +1 does not make the approval process happy. :)

2018-10-23 10:04 UTC, karlitschek approved these changes

2018-10-23 10:39 UTC, MariusBluem approved these changes

2018-10-23 10:41 UTC, skjnldsv commented
@jancborchardt tests failing:

``` bash
There were 6 errors:

1) Test\Preview\BackgroundCleanupJobTest::testCleanupSystemCron
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/lib/private/Preview/GeneratorHelper.php:59
/drone/src/github.com/nextcloud/server/lib/private/Preview/Generator.php:194
/drone/src/github.com/nextcloud/server/lib/private/Preview/Generator.php:118
/drone/src/github.com/nextcloud/server/lib/private/PreviewManager.php:205
/drone/src/github.com/nextcloud/server/tests/lib/Preview/BackgroundCleanupJobTest.php:104
/drone/src/github.com/nextcloud/server/tests/lib/Preview/BackgroundCleanupJobTest.php:112

2) Test\Preview\BackgroundCleanupJobTest::testCleanupAjax
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/lib/private/Preview/GeneratorHelper.php:59
/drone/src/github.com/nextcloud/server/lib/private/Preview/Generator.php:194
/drone/src/github.com/nextcloud/server/lib/private/Preview/Generator.php:118
/drone/src/github.com/nextcloud/server/lib/private/PreviewManager.php:205
/drone/src/github.com/nextcloud/server/tests/lib/Preview/BackgroundCleanupJobTest.php:104
/drone/src/github.com/nextcloud/server/tests/lib/Preview/BackgroundCleanupJobTest.php:134

3) Test\Preview\TXTTest::testGetThumbnail with data set #0 (-72, -43)
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:139
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

4) Test\Preview\TXTTest::testGetThumbnail with data set #1 (73, 5)
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:139
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

5) Test\Preview\TXTTest::testGetThumbnail with data set #2 (-14, 91)
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:139
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

6) Test\Preview\TXTTest::testGetThumbnail with data set #3 (70, -39)
imagettftext(): Could not find/open font

/drone/src/github.com/nextcloud/server/lib/private/Preview/TXT.php:83
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:139
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

--
```

2018-10-23 11:18 UTC, skjnldsv requested changes

2018-10-23 11:18 UTC, skjnldsv commented on lib/private/Avatar.php
> +	 * Nunito cap-height is 0.72 and we want a 200px caps height size (0.4 letter-to-total-height ratio, 500*0.4=200). 200/0.72 = 278px.
Nunito cap-height is 0.73

2018-10-23 11:22 UTC, jancborchardt commented on lib/private/Avatar.php
> +	 * Nunito cap-height is 0.72 and we want a 200px caps height size (0.4 letter-to-total-height ratio, 500*0.4=200). 200/0.72 = 278px.
Really? I just checked with the linked tool and it said 0.7153…

2018-10-23 11:34 UTC, jancborchardt commented on lib/private/Avatar.php
> +	 * Nunito cap-height is 0.72 and we want a 200px caps height size (0.4 letter-to-total-height ratio, 500*0.4=200). 200/0.72 = 278px.
Also with your pen, it says:
- Chrome: 0.7153846416247677
- Firefox: 0.7175

2018-10-23 12:16 UTC, skjnldsv commented on lib/private/Avatar.php
> +	 * Nunito cap-height is 0.72 and we want a 200px caps height size (0.4 letter-to-total-height ratio, 500*0.4=200). 200/0.72 = 278px.
EDIT: Nope, it's 0.713, so it's fine to leave it at 0.72
https://codepen.io/skjnldsv/pen/PydLBK/

2018-10-23 12:23 UTC, skjnldsv approved these changes

2018-10-23 12:26 UTC, jospoortvliet approved these changes
Awesome! :+1:

2018-10-23 13:05 UTC, skjnldsv commented
Failure unrelated: `sh: 1: kill: No such process`

2018-10-23 13:13 UTC, MorrisJobke approved these changes
Looks good 👍

2018-10-23 13:14 UTC, merged