Replace $verbose with VERBOSITY_VERBOSE for scanFiles method
nextcloud/server pull request #11968
Opened 2018-10-21 20:08 UTC by danielkesselberg

Follow-up https://github.com/nextcloud/server/pull/11831

This pr replace `if ($verbose)` with `OutputInterface::VERBOSITY_VERBOSE`

2018-10-22 06:10 UTC, ChristophWurst requested changes
Please don't mix such changes. Let's just adjust the verbosity output logic in this PR.

2018-10-22 06:10 UTC, ChristophWurst commented on apps/files/lib/Command/ScanAppData.php
> +			$output->writeln("\tFile\t<info>$path</info>", OutputInterface::VERBOSITY_VERBOSE);
please don't change these unrelated commands. It's fine to *fix*/*enhance* this in another PR though.

2018-10-22 06:10 UTC, ChristophWurst commented on apps/files/lib/Command/ScanAppData.php
> +			$output->writeln("\tFolder\t<info>$path</info>", OutputInterface::VERBOSITY_VERBOSE);
same

2018-10-22 06:10 UTC, ChristophWurst commented on apps/files/lib/Command/ScanAppData.php
> +		$output->writeln('Scanning AppData for files');
same

2018-10-22 06:10 UTC, ChristophWurst commented on apps/files/lib/Command/ScanAppData.php
> -		$output->writeln("");
same

2018-10-22 06:17 UTC, ChristophWurst requested changes
Please don't change the command logic (post increment, output formatting) in this PR :wink:

2018-11-05 23:35 UTC, MorrisJobke commented
Let's close this one in favor of #11831

2018-11-05 23:36 UTC, MorrisJobke commented
> Let's close this one in favor of #11831

I just realized that it is for a different command.

2018-11-05 23:38 UTC, MorrisJobke approved these changes
Tested and works 👍 Code looks good

2018-11-06 12:38 UTC, danielkesselberg commented
@ChristophWurst :ping_pong:

2018-11-06 12:53 UTC, ChristophWurst approved these changes

2018-11-06 13:41 UTC, merged