Implement the size of an assembly stream
nextcloud/server pull request #12038
Opened 2018-10-25 10:23 UTC by rullzer

This will make it possible to act propely on moves of future files if we
need to know the size (like for max size virus scanning).

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-10-25 20:40 UTC, icewind1991 requested changes

2018-10-25 20:40 UTC, icewind1991 commented on apps/dav/lib/Upload/AssemblyStream.php
> +		];
`$this->size` :)

2018-10-26 08:43 UTC, rullzer commented on apps/dav/lib/Upload/AssemblyStream.php
> +		];
Just making sure you are paying attention :wink:

2018-10-26 13:01 UTC, icewind1991 approved these changes

2018-10-26 13:01 UTC, icewind1991 approved these changes

2018-10-26 15:01 UTC, MorrisJobke approved these changes
Code looks good 👍

2018-10-26 15:02 UTC, merged