Align file menu below '+' button, fix #5595
nextcloud/server pull request #12162
Opened 2018-10-31 10:24 UTC by jancborchardt

Not only makes it look much better and consistent with the rest of our popups, but also fixes https://github.com/nextcloud/server/issues/5595 cc @pixelipo :)

Before & after:
![screenshot from 2018-10-31 11-21-59](https://user-images.githubusercontent.com/925062/47781923-3f34db80-dcff-11e8-84c7-6616d164fffb.png) ![file menu aligned](https://user-images.githubusercontent.com/925062/47781927-3fcd7200-dcff-11e8-8714-ed16e119fb14.png)

When on the right edge, before & after:
![screenshot from 2018-10-31 11-21-39](https://user-images.githubusercontent.com/925062/47781924-3f34db80-dcff-11e8-826b-cd87d7c875a0.png) ![screenshot from 2018-10-31 11-21-02](https://user-images.githubusercontent.com/925062/47781926-3f34db80-dcff-11e8-879a-7eb31e104eab.png)

Please review @nextcloud/designers :tada:

2018-10-31 10:27 UTC, skjnldsv requested changes
Please use our standard `.menu-center` :)
https://docs.nextcloud.com/server/14/developer_manual/design/popovermenu.html#alignment

2018-10-31 13:11 UTC, jancborchardt commented
@skjnldsv the issue is that then it looks like this, cause it’s centered on the container:
![menu-center](https://user-images.githubusercontent.com/925062/47790128-b164ea80-dd16-11e8-8f0f-8c7a3bab24e8.png)

And I don’t really want to mess with the structure at this point **cough** Vue 🤧 ;)

2018-10-31 13:56 UTC, skjnldsv commented
I'll take a look in a moment 🤗

2018-10-31 14:37 UTC, skjnldsv commented
@jancborchardt indeed, the menu should be inside the div that wrap the trigger to fit our standards!
Let's do it your way! :sneezing_face:

2018-10-31 14:37 UTC, skjnldsv approved these changes

2018-10-31 16:06 UTC, jancborchardt commented
@skjnldsv thanks! :) Yes, I didn’t want to include another container or move stuff around, because who knows what kind of CSS nesting looms in the shadows! :spider_web: :spider: :bat:

2018-11-01 11:00 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-11-01 11:01 UTC, merged