Background job to cleanup leftover chunked uploads
nextcloud/server pull request #12227
Opened 2018-11-02 20:24 UTC by rullzer

If a chunked uploads fails for some reason the chunks should be cleaned up at some point in time. Else they can quickly fillup a disk.

When a chunked collection is created a backgroundjob is inserted.
This job is deleted when the chunked upload completes sucsessfully

The job will check if all files have an mtime of more than 24 hours. If so it will kill the folder. So as long as you upload 1 chunk every 24 hours it will not kill them.

TODO:
- [x] Proper DI
- [x] Add an initial repair step that inserts a backgroundjob for all the existing upload folders
   * probably best to have a background job for all the users inserted that does this

CC: @MorrisJobke since we discussed this recently

2019-01-03 10:48 UTC, MorrisJobke requested changes
Code makes sense so far 👍

2019-01-03 10:48 UTC, MorrisJobke commented on apps/dav/lib/BackgroundJob/UploadCleanup.php
> +		//Remove if all files have an mtime of more than a day
```suggestion
		// Remove if all files have an mtime of more than a day
```

2019-01-03 10:48 UTC, MorrisJobke commented on apps/dav/lib/BackgroundJob/UploadCleanup.php
> +		$time = $this->time->getTime() - 60*60*24;
```suggestion
		$time = $this->time->getTime() - 60 * 60 * 24;
```

2019-01-03 10:49 UTC, MorrisJobke commented
I guess this is addressing #8759

2019-01-03 10:56 UTC, rullzer commented
@MorrisJobke yes. But this is only for upload using the new chunked upload. However most are now days.

2019-01-04 14:31 UTC, blizzz approved these changes
makes sense

2019-01-07 10:19 UTC, MorrisJobke approved these changes
Code makes sense 👍

2019-01-07 10:19 UTC, merged