Fix Calendarsubscriptions source column change on Oracle
nextcloud/server pull request #12275
Opened 2018-11-05 11:59 UTC by georgehrke

fixes #11975

2018-11-07 11:52 UTC, ChristophWurst submitted a review, later dismissed

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +		if (!$schema->hasTable('calendarsubscriptions')) {
We had this discussion in another PR recently (with @skjnldsv and @MorrisJobke if I recall). I don't see how that condition could ever evaluate to `true`. Just assume that the previous migrations were run and the table exists.

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +		if ($column->getLength() === null) {
When does that happen?

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104833.php
> +		if (!$schema->hasTable('calendarsubscriptions')) {
same as above

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104833.php
> +		if (!$table->hasColumn('source_copy')) {
just assume it's there

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105110300.php
> +		if ($table->hasColumn('source') || !$table->hasColumn('source_copy')) {
just assume they are there

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105112049.php
> +		if (!$schema->hasTable('calendarsubscriptions')) {
same as above

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105112049.php
> +		if (!$table->hasColumn('source_copy')) {
once again :see_no_evil:

2018-11-07 11:52 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1007Date20181007225117.php
> -	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
Why did you remove this previous migration? IMO migrations should be removed unless they have known bugs that prevent them from running.

2018-11-07 11:55 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1007Date20181007225117.php
> -	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
Okay, so (obviously) this migration triggers https://github.com/nextcloud/server/issues/11975. Is it still safe to remove the class in that case, @nickvergessen?

An alternative would be to just make it a NOP.

2018-11-07 11:59 UTC, nickvergessen commented on apps/dav/appinfo/info.xml
> +	<version>1.8.0</version>
1.7.3 should be fine, I increase it directly after each major release :see_no_evil:

2018-11-07 12:06 UTC, nickvergessen submitted a review, later dismissed

2018-11-07 12:06 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +			return $schema;
return null instead so we know it didnt change and dont need to do anything

2018-11-07 12:06 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +			return $schema;
return null instead so we know it didnt change and dont need to do anything

2018-11-07 12:08 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1007Date20181007225117.php
> -	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
It has to be removed, otherwise Oracle can never install again.

I guess NOP would also work, but well since the migration service doesnt care, I guess removing is the better idea

2018-11-07 12:57 UTC, georgehrke commented
Set version to `1.7.3` and removed the extra checks.

2018-11-07 13:17 UTC, ChristophWurst requested changes
If possible I'd suggest to do a column rename instead of the second copy. Apart from that it looks good!

2018-11-07 13:17 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> + * Auto-generated migration step: Please modify to your needs!
kill with :fire:

2018-11-07 13:17 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105104833.php
> + * Auto-generated migration step: Please modify to your needs!
:fire:

2018-11-07 13:17 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105110300.php
> + * Auto-generated migration step: Please modify to your needs!
:fire:

2018-11-07 13:19 UTC, ChristophWurst requested changes

2018-11-07 13:19 UTC, ChristophWurst commented on apps/dav/lib/Migration/Version1008Date20181105110300.php
> +		$table->addColumn('source', Type::TEXT, [
(somehow one of my review comments got lost) please use `$table->renameColumn` if possible. This was also suggested at https://stackoverflow.com/questions/13402510/oracle-changing-varchar2-column-to-clob and I guess is faster for DBs to execute than copy a full column.

2018-11-07 13:20 UTC, georgehrke commented
> If possible I'd suggest to do a column rename instead of the second copy. Apart from that it looks good!

Doctrine doesn't support that. It would simply delete the column and create a new empty one

2018-11-07 13:20 UTC, georgehrke commented
See https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php#L340

2018-11-07 13:24 UTC, ChristophWurst approved these changes
Looks good!

2018-11-07 13:48 UTC, nickvergessen commented
> I just realized the naming of the files is : Version1008Datexxx which probably means version 10.0.8. 

No, if the version is `X.Y.Z` the migration name is `XXXYYY` without leading zeros

2018-11-07 16:36 UTC, blizzz commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +	 * Version1007Date20181007225117 constructor.
:thinking:

2018-11-09 10:11 UTC, skjnldsv approved these changes

2018-11-12 11:09 UTC, MorrisJobke commented
Rebased to fix conflicts in autoloader.

2018-11-12 11:10 UTC, MorrisJobke commented on apps/dav/lib/Migration/Version1008Date20181105104826.php
> +declare(strict_types=1);
There are license headers missing in all migration files 🙈

2018-11-13 15:34 UTC, merged