Disabling users in WebUI
nextcloud/server pull request #1234
Opened 2016-09-01 14:55 UTC by MorrisJobke

* #413 rebased on master - by @Faldon 
* I reviewed the layout and improved it a bit
* I will continue reviewing it and read through all comments in #413 and try to fix them

2016-09-01 14:57 UTC, MorrisJobke commented
It now looks like this:

<img width="294" alt="bildschirmfoto 2016-09-01 um 16 53 20" src="https://cloud.githubusercontent.com/assets/245432/18172285/1bdb3e1c-7065-11e6-9984-e4ad741db34c.png">

2016-09-01 15:02 UTC, MorrisJobke commented
I tested this and it works quite well :+1: from me

@rullzer @nickvergessen @LukasReschke @mar1u5 @nextcloud/designers Please review

2016-09-01 15:26 UTC, MorrisJobke commented
```
There were 13 failures:

1) Tests\Settings\Controller\UsersControllerTest::testIndexAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
-        0 => Array (...)
-        1 => Array (...)
-        2 => Array (...)
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 200
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:266

2) Tests\Settings\Controller\UsersControllerTest::testIndexSubAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
-        0 => Array (...)
-        1 => Array (...)
-        2 => Array (...)
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 200
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:473

3) Tests\Settings\Controller\UsersControllerTest::testIndexWithSearch
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
-        0 => Array (...)
-        1 => Array (...)
-        2 => Array (...)
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 200
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:635

4) Tests\Settings\Controller\UsersControllerTest::testIndexWithBackend
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
-        0 => Array (...)
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 200
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:711

5) Tests\Settings\Controller\UsersControllerTest::testCreateSuccessfulWithoutGroupAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
         'backend' => 'bar'
-        'lastLogin' => null
+        'lastLogin' => 0
         'displayname' => null
         'quota' => null
         'subadmin' => Array ()
-        'email' => null
+        'email' => ''
         'isRestoreDisabled' => false
         'isAvatarAvailable' => true
+        'isEnabled' => null
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 201
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:783

6) Tests\Settings\Controller\UsersControllerTest::testCreateSuccessfulWithoutGroupSubAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
         'subadmin' => Array ()
-        'email' => null
+        'email' => ''
         'isRestoreDisabled' => false
         'isAvatarAvailable' => true
+        'isEnabled' => null
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 201
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:872

7) Tests\Settings\Controller\UsersControllerTest::testCreateSuccessfulWithGroupAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
         'backend' => 'bar'
-        'lastLogin' => null
+        'lastLogin' => 0
         'displayname' => null
         'quota' => null
         'subadmin' => Array ()
-        'email' => null
+        'email' => ''
         'isRestoreDisabled' => false
         'isAvatarAvailable' => true
+        'isEnabled' => null
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 201
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:955

8) Tests\Settings\Controller\UsersControllerTest::testCreateSuccessfulWithGroupSubAdmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
         'subadmin' => Array ()
-        'email' => null
+        'email' => ''
         'isRestoreDisabled' => false
         'isAvatarAvailable' => true
+        'isEnabled' => null
     )
     'headers' => Array (...)
     'cookies' => Array ()
     'status' => 201
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\ContentSecurityPolicy Object (...)
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1051

9) Tests\Settings\Controller\UsersControllerTest::testRestorePossibleWithoutEncryption
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'backend' => 'OC_User_Database'
-    'email' => null
+    'email' => ''
     'isRestoreDisabled' => false
     'isAvatarAvailable' => true
+    'isEnabled' => null
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1567

10) Tests\Settings\Controller\UsersControllerTest::testRestorePossibleWithAdminAndUserRestore
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'backend' => 'OC_User_Database'
-    'email' => null
+    'email' => ''
     'isRestoreDisabled' => false
     'isAvatarAvailable' => true
+    'isEnabled' => null
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1616

11) Tests\Settings\Controller\UsersControllerTest::testRestoreNotPossibleWithoutAdminRestore
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'backend' => 'OC_User_Database'
-    'email' => null
+    'email' => ''
     'isRestoreDisabled' => true
     'isAvatarAvailable' => true
+    'isEnabled' => null
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1646

12) Tests\Settings\Controller\UsersControllerTest::testRestoreNotPossibleWithoutUserRestore
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'backend' => 'OC_User_Database'
-    'email' => null
+    'email' => ''
     'isRestoreDisabled' => true
     'isAvatarAvailable' => true
+    'isEnabled' => null
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1697

13) Tests\Settings\Controller\UsersControllerTest::testNoAvatar
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'backend' => 'OC_User_Database'
-    'email' => null
+    'email' => ''
     'isRestoreDisabled' => false
     'isAvatarAvailable' => false
+    'isEnabled' => null
 )

/drone/src/github.com/nextcloud/server/tests/Settings/Controller/UsersControllerTest.php:1723
```

2016-09-04 16:53 UTC, Faldon commented
@MorrisJobke Sorry, was out of town for a few days. I'm glad someone more drone experienced does the fixes. ;-)

2016-09-09 05:48 UTC, rullzer commented
- [ ] SVGs need to be minimized
- [ ] SVGs need proper viewBox

2016-09-09 06:02 UTC, rullzer commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== 'disabledUsers') {
This will explode if anybody ever creates a group `disabledUsers`

2016-09-09 06:09 UTC, rullzer commented
* Rebased
* Fixed the current unit tests

- [ ] Add unit tests for disabled users

2016-09-09 06:33 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== 'disabledUsers') {
Then name it NextcloudDisabledUsers

2016-09-09 07:20 UTC, rullzer commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== 'disabledUsers') {
Why not just another parameter $disabledUsers that defaults to false?

2016-09-09 07:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== 'disabledUsers') {
Ah yes ... makes sense then 🙈 It's early in the morning 😝

2016-09-09 07:36 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== 'disabledUsers') {
Well we have the same problem with the group "everyone"

2016-09-09 12:01 UTC, MorrisJobke commented
> SVGs need proper viewBox

Why?

2016-09-10 18:59 UTC, rullzer commented
@MorrisJobke because else firefox et all might desicde to do weird stuff again ;)

2016-09-11 22:18 UTC, MorrisJobke commented
> @MorrisJobke because else firefox et all might desicde to do weird stuff again ;)

But there is a viewbox ;)

2016-09-12 06:39 UTC, rullzer commented
now there is ;)

2016-09-14 13:09 UTC, MorrisJobke commented
@rullzer Unit tests are added.


This is ready for review - cc @LukasReschke @nickvergessen @rullzer

2016-09-14 13:56 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== '_disabledUsers') {
Should we add a public constant for this?

2016-09-14 14:33 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +			if($gid !== '' && $gid !== '_disabledUsers') {
I would say that this is something for a different PR, because then the "_everyone" group should also be handled.

2016-09-14 17:57 UTC, rullzer commented
LGTM then!

2016-09-17 21:23 UTC, MorrisJobke commented
@LukasReschke please review :)

2016-09-19 16:06 UTC, MorrisJobke commented
@nickvergessen Mind to review this? ;)

2016-09-28 21:33 UTC, MorrisJobke commented
@LukasReschke I would really love to see this reviewed :)

2016-10-03 08:56 UTC, ChristophWurst commented
Is it intended that users disappear from the ``Everyone`` list once they get disabled?

2016-10-03 10:06 UTC, MorrisJobke commented
> Is it intended that users disappear from the Everyone list once they get disabled?

I think everyone should contain all users. Because currently disabled is only a kind of group.

2016-10-03 11:02 UTC, MariusBluem commented
...Maybe we should introduce something like **Active Users** and **All users** 😁

2016-10-05 22:46 UTC, MorrisJobke commented
> ...Maybe we should introduce something like Active Users and All users

Could we get this in and then refine afterwards?

2016-10-06 12:17 UTC, nickvergessen submitted a review, later dismissed

2016-10-06 12:17 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +		if(!$this->isAdmin && !$this->groupManager->getSubAdmin()->isUserAccessible($this->userSession->getUser(), $user)) {
`$user` can be null, causing an issue here.

2016-10-06 12:17 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +			);
missing status code here. Should not be OK

2016-10-06 12:17 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +		if(!$this->isAdmin && !$this->groupManager->getSubAdmin()->isUserAccessible($this->userSession->getUser(), $user)) {
same here, non existing user breaks

2016-10-06 12:17 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +				)
missing status code

2016-10-06 12:54 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +			);
That's how the current JS side works. Changing this would need to redo a lot of the JS code, because it only handles the 200 response code results.

2016-10-06 12:54 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +				)
Same as above. This is how the current JS code works. Not nice, but that's it - we can't redo everything always ;)

2016-10-06 12:54 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +		if(!$this->isAdmin && !$this->groupManager->getSubAdmin()->isUserAccessible($this->userSession->getUser(), $user)) {
I will look into this. You commented twice on the same line. Is this correct?

2016-10-06 13:12 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +		if(!$this->isAdmin && !$this->groupManager->getSubAdmin()->isUserAccessible($this->userSession->getUser(), $user)) {
No, two lines, once enable and once disable

2016-10-06 13:13 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +			);
well other errors do have a non 200 status code...

2016-10-06 13:25 UTC, MorrisJobke commented
@nickvergessen I adjusted the if statements to be before the usage of `$user`. Review time :)

2016-10-10 07:54 UTC, MorrisJobke commented
I rebased to fix the merge conflicts (only in the tests)

2016-10-10 14:12 UTC, MorrisJobke commented
@blizzz I fixed the unit tests.

2016-10-10 15:48 UTC, blizzz commented
If the full name col greyed out intentionally? If find it irritating.

2016-10-10 21:51 UTC, MorrisJobke commented
> If the full name col greyed out intentionally? If find it irritating.

What? This isn't correct. Which browser?

2016-10-11 07:15 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +			);
Really? O.o

2016-10-11 07:38 UTC, jancborchardt commented on settings/Controller/UsersController.php
> +						'message' => (string)$this->l10n->t('Unable to disable user.')
This wording is confusing. Better: »Error while disabling user.«

2016-10-11 07:38 UTC, jancborchardt commented on settings/Controller/UsersController.php
> +						'message' => (string)$this->l10n->t('Unable to disable user.')
Same here: »Error while disabling user.«

2016-10-11 07:39 UTC, jancborchardt commented on settings/Controller/UsersController.php
> +						'message' => (string)$this->l10n->t('Unable to enable user.')
»Error while enabling user.«

2016-10-11 07:39 UTC, jancborchardt commented on settings/Controller/UsersController.php
> +						'message' => (string)$this->l10n->t('Unable to enable user.')
»Error while enabling user.«

2016-10-11 07:40 UTC, jancborchardt commented on settings/css/settings.css
> +td.password>span, td.quota>span, td.displayName>span { margin-right: 1.2em; color: #C7C7C7; }
The greying out of the display name comes from this change I guess. ;)

2016-10-11 07:41 UTC, jancborchardt commented on settings/js/users/users.js
> +					OC.dialogs.alert(result.data.message, t('settings', 'Unable to change status of {user}', {user: uid}));
»Error while changing status of …«

2016-10-11 07:43 UTC, jancborchardt submitted a review, later dismissed

2016-10-11 07:43 UTC, jancborchardt commented on tests/Settings/Controller/UsersControllerTest.php
> +					'message' => 'Unable to disable user.',
»Error while disabling user.« – Don’t Repeat Yourself? ;D

2016-10-11 07:43 UTC, jancborchardt commented on tests/Settings/Controller/UsersControllerTest.php
> +					'message' => 'Unable to disable user.',
And again here

2016-10-11 07:43 UTC, jancborchardt commented on tests/Settings/Controller/UsersControllerTest.php
> +					'message' => 'Unable to disable user.',
Just search and replace for »Unable to« ;D

2016-10-11 10:08 UTC, MorrisJobke commented
@ChristophWurst I fixed the layout issue. Thanks @jancborchardt 

@jancborchardt I fixed the wording \o/

@nickvergessen I added the proper return codes and fixed the JS handling of those cases. ;)

2016-10-11 10:53 UTC, blizzz commented
When I as group admin disable a user,

* [ ] a counter appears to the Disabled group entry, despite having LDAP  enabled
* [ ] the disabled user belonging the the group does not appear within Disbled (== it is empty).

2016-10-11 10:54 UTC, blizzz commented
When I as group admin disable a user,

* [ ] a counter appears to the Disabled group entry, despite having LDAP  enabled
* [ ] the disabled user belonging the the group does not appear within Disbled (== it is empty).

(cannot add a review??)

2016-10-19 17:29 UTC, rullzer commented
Conflicts => needs rebase
@MorrisJobke @Faldon can you take a look at @blizz https://github.com/nextcloud/server/pull/1234#issuecomment-252881240

2016-10-19 17:48 UTC, blizzz commented
>  @MorrisJobke @Faldon can you take a look at @blizz #1234 (comment)

I shall writer @rulzer with a single l now. :imp: ;)

2016-11-02 21:43 UTC, MorrisJobke commented
Rebased.

2016-11-02 21:44 UTC, MorrisJobke commented
@blizzz Could you elaborate on your comments. I don't understand them fully.

2016-11-02 22:09 UTC, enoch85 commented
Wow, yet another very nice improvement. Thanks guys!

2016-11-23 17:04 UTC, MorrisJobke commented
Sadly will not make it into 11 -> moved to 12

2016-11-29 22:20 UTC, blizzz commented
rebase needed

2016-11-30 08:54 UTC, nickvergessen commented
This branch has conflicts that must be resolved

2016-11-30 08:54 UTC, nickvergessen commented
You forgot to push @blizzz

2016-11-30 16:06 UTC, MorrisJobke commented
> rebase needed

Done. Mostly because of some major restructuring in the tests class.

Let's see

2016-12-01 13:46 UTC, blizzz commented
and tests failing

2016-12-01 23:23 UTC, MorrisJobke commented
> and tests failing

Fixed

2016-12-02 09:39 UTC, blizzz commented
Almost. Also a signoff check fails.

2016-12-16 12:27 UTC, LukasReschke commented
Rebased on current master. Since the commits with the missing sign-off were before we added the sign-off requirement was added I'd be tempted to ignore that.

Will review if tests do pass.

2016-12-16 22:41 UTC, MorrisJobke commented
> Will review if tests do pass.

They do - only sign-off is the problem here :)

2016-12-19 15:23 UTC, blizzz commented
@MorrisJobke 

> When I as group admin disable a user,
>    a counter appears to the Disabled group entry, despite having LDAP enabled

Seems fixed

>  the disabled user belonging the the group does not appear within Disbled (== it is empty).

1. Before disabling the users:

![spectacle h12133](https://cloud.githubusercontent.com/assets/2184312/21317770/d958b20c-c606-11e6-8161-3a91289e812c.png)

2. After disabling the users, the "Disabled" user count stays at 3 (with LDAP group counts are disabled, because they are expensive, so this magic group is the only one with a count. Not consistent).

(A reload later the group count here is at 5)

3. Going to the Disabled group it does not show any users:

![spectacle z12133](https://cloud.githubusercontent.com/assets/2184312/21317899/61dca8f4-c607-11e6-9ec6-60545ab73380.png)

2016-12-19 15:23 UTC, blizzz requested changes
cf. https://github.com/nextcloud/server/pull/1234#issuecomment-267991153

2016-12-22 04:05 UTC, Luticus commented
It seems like you guys are already working on a fix that's near complete, but I've been simply using the extrasecurity app  with a "disabled" group to add the feature.  I went looking again because nextcloud 11 seems to have broken extrasecurity and that app doesn't get updates all too often.  I found this thread and thought I'd suggest just creating a "disable user" group similar to the global "everyone" and then simply have authentication logic that checks for membership?  Seems like it may be easier and there's no need for an interface change.  

Just thought I'd put the idea out there.

2017-03-20 12:31 UTC, georgehrke commented
needs a rebase

2017-03-24 07:10 UTC, MorrisJobke commented
@ChristophWurst Could you help me out with this one? It's basically fixing some JS stuff? That would be nice :)

2017-04-16 13:38 UTC, oparoz commented on settings/Controller/UsersController.php
> +				array(
Should be replaced by "[" everywhere.

2017-04-18 06:56 UTC, ChristophWurst commented on settings/Controller/UsersController.php
> +				array(
done

2017-04-18 06:58 UTC, ChristophWurst commented
rebased, resolved conflicts and addressed @oparoz´es comment

2017-04-18 07:26 UTC, oparoz commented on settings/Controller/UsersController.php
> +				array(
Thanks :)

2017-04-25 14:18 UTC, blizzz commented
"Disabled" counter is still not being updated, and shown when it probably should not. But users under "disabled" are now shown correctly.

2017-04-25 14:45 UTC, nickvergessen commented
@MorrisJobke whats the status here?

2017-04-25 14:45 UTC, MorrisJobke commented
> @MorrisJobke whats the status here?

No time yet - let me quickly look into this.

2017-04-26 03:42 UTC, MorrisJobke commented
> @MorrisJobke whats the status here?

Sorry ... is not that easy and there are too many other tasks on my list - either we get it in and fix the counter stuff afterwards or we delay this 😕

2017-04-26 03:51 UTC, MorrisJobke commented
I rebased to fix the conflicts.

> "Disabled" counter is still not being updated, and shown when it probably should not. But users under "disabled" are now shown correctly.

@ChristophWurst Could you look into this and try to fix this? That would be super nice. This PR is laying already around since ages. And I currently have no time :/

2017-04-26 08:29 UTC, ChristophWurst commented
> @ChristophWurst Could you look into this and try to fix this? That would be super nice. This PR is laying already around since ages. And I currently have no time :/

Sure, but unlikely that I'll find time for it this week.

2017-04-26 09:08 UTC, blizzz commented
>> @ChristophWurst Could you look into this and try to fix this? That would be super nice. This PR is laying already around since ages. And I currently have no time :/

> Sure, but unlikely that I'll find time for it this week.

Then let's get this in and fix it during beta cycle. It's not a fundamental issue after all.

2017-04-26 09:26 UTC, blizzz requested changes
Found a performance regression

2017-04-26 09:26 UTC, blizzz commented on settings/Controller/UsersController.php
> +		if ($userId === $id) {
The checks could be consolidated instead of being duplicated in `enable()`` and ``disable()`` methods.. Would not see it as a blocker this stage,  but it's better to get this done during beta.

2017-04-26 09:26 UTC, blizzz commented on settings/users.php
> +foreach (OC_User::getUsers() as $uid) {
This is bad. We iterate over hundreds of thousands of users for a value that we can get with a simple SQL query (``SELECT COUNT(userid) from oc_preferences where  appid = 'core' AND configkey='enabled' and configvalue = 'false'``). Currently this leads to a bad performance on opening that Users page.

2017-04-26 09:51 UTC, blizzz commented
I take care of ^

2017-04-26 11:21 UTC, blizzz commented
Done with the things I pointed at with my last review. While testing my changes I also found the counter to work :) But the menu appears only on the top-right of the table (did not touch JS though).

2017-04-28 10:58 UTC, rullzer commented
@blizzz so ready to get reviewed and merged?

2017-04-28 11:02 UTC, blizzz commented
> But the menu appears only on the top-right of the table

@rullzer this is left.

2017-04-28 12:46 UTC, MariusBluem commented
Just 2 small comments, which also can be fixed later - as they are design 😉 

- Icons for Everyone, Disabled and Enabled (Checkbox Icon, X-Icon, for Everyone I would recommend a list icon)

- Introduce a space between Everyone, Disabled, Enabled and the Groups (like apps management between All apps, activated, ... and the categories from app store) 

@jancborchardt

2017-04-28 15:51 UTC, blizzz commented
>   But the menu appears only on the top-right of the table

Merde! Thought all the time it's a JS issue with some wrong placement or whatever… instead, stupid CSS. 

@rullzer ready to get reviewed

@MariusBluem ack to both, but not by me ( ❤️ backend ❤️ ) and perhaps in a new PR 😼

2017-04-28 15:51 UTC, blizzz approved these changes

2017-04-29 03:59 UTC, MorrisJobke commented
Rebased to resolve conflicts in test file

2017-04-29 04:05 UTC, MorrisJobke commented
Tested and works 👍

2017-04-29 04:35 UTC, merged

2017-04-29 04:36 UTC, MorrisJobke commented
Nearly 9 months after the rebase - sorry that it took so long, @Faldon