Move/copy file picker: Remeber last destination and start in current folder
nextcloud/server pull request #12381
Opened 2018-11-09 15:19 UTC by rummatee

This my first time contributing to Nextcloud and using Pull Requests, so please tell me, if I did something wrong.
This Pull Request intends to solve Issue  #11314 .
I changed the signature of the filepicker, but made sure that the behavior doesn't change in case it gets called without the additional argument.

2018-12-20 14:00 UTC, rummatee commented
please review @jancborchardt

2018-12-20 21:45 UTC, jancborchardt commented
@rummatee also, could you rebase onto latest master, as there were some changes? Let me know if you have questions how to do that – I generally also search and find the answer on StackOverflow 😅

2018-12-20 21:52 UTC, jancborchardt commented
Hmm, just tested it and it doesn’t seem to work? Still starts in the root folder every time. Do I need to compile anything? :)

2018-12-20 22:08 UTC, rummatee commented
> @rummatee also, could you rebase onto latest master, as there were some changes? Let me know if you have questions how to do that – I generally also search and find the answer on StackOverflow sweat_smile

indeed I would appreciate some help on this. I see that there is a button to resolve conflicts, but when I do that, it shows me a warning that I am committing to master and I was afraid to confirm that.

> Hmm, just tested it and it doesn’t seem to work? Still starts in the root folder every time. Do I need to compile anything? :)

I don't think it should require to compile anything. I just tested it again and for me it works. I created a folder called "test" and a file in this folder. When I want to move this file the dialog starts in folder "test".

2018-12-21 00:42 UTC, jancborchardt commented
> indeed I would appreciate some help on this. I see that there is a button to resolve conflicts, but when I do that, it shows me a warning that I am committing to master and I was afraid to confirm that.

It’s fine – that is referring to your master branch. It’s not possible for anyone to commit directly to master or any stable branches as we have branch protection enabled. :)

2018-12-22 15:32 UTC, kesselb reviewed
Great improvement :+1:

2018-12-22 15:32 UTC, danielkesselberg commented on core/js/oc-dialogs.js
> +	filepicker:function(title, callback, multiselect, mimetypeFilter, modal, type, path) {
When you change `path` to `path = ''` it should be possible to omit line 216 - 219.

2018-12-23 13:49 UTC, rummatee commented on core/js/oc-dialogs.js
> +	filepicker:function(title, callback, multiselect, mimetypeFilter, modal, type, path) {
I guess so, but I never saw an argument being initialized in the arguments list in Nextcloud. So in order to keep the style consistent, I also didn't.

2018-12-23 13:51 UTC, rummatee commented
> A is working fine for me but B does not work.

okay thank you for clarifying that there are 2 different menus that need this feature. The new commit should add it also to the multiselect menu.

2018-12-23 14:34 UTC, jancborchardt commented
Thanks @rummatee! 

We definitely need a code review on this from someone in  @nextcloud/javascript :)

2018-12-23 15:55 UTC, danielkesselberg commented
Select two or more files, use **top** three dot menu and pick "move or copy". Please note the two buttons "move" and "copy".
![image](https://user-images.githubusercontent.com/3902676/50385256-ff70eb80-06d2-11e9-9691-06c2bca46c06.png)

When you go a directory higher or lower the button label is changed like below even when you are in the same folder again.

![image](https://user-images.githubusercontent.com/3902676/50385270-419a2d00-06d3-11e9-9959-00f3389d8a44.png)

I think the button labels should be the same @jancborchardt

2018-12-23 15:56 UTC, kesselb approved these changes

2018-12-23 18:06 UTC, jancborchardt commented
> I think the button labels should be the same 

Yes, true. Is it possible to make it so that in the folder where the files are right now, they are simply "Copy" and "Move"? Ideally they should also be disabled there, and a tooltip (also visible on click) on the buttons should say "This folder is the current place of the files."

2018-12-23 19:37 UTC, rummatee commented
> > I think the button labels should be the same
> 
> Yes, true. Is it possible to make it so that in the folder where the files are right now, they are simply "Copy" and "Move"? Ideally they should also be disabled there, and a tooltip (also visible on click) on the buttons should say "This folder is the current place of the files."

Well that would be related to issue #11313  #9931 and PR #10825 so I am not completely sure how these would interact. Of course it would be possible to change the label or grey out the buttons, but maybe it is better to leave that out of this PR to avoid conflicts with other PRs?

2018-12-23 23:39 UTC, jancborchardt commented
> maybe it is better to leave that out of this PR to avoid conflicts with other PRs?

Good point, yes let’s do it separately!

Still waiting for a code review from @nextcloud/javascript :) @juliushaertl @danxuliu @kevgathuku @ChristophWurst anyone?

2019-01-07 14:56 UTC, ChristophWurst requested changes
:)

2019-01-07 14:56 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +			if (self.dirInfo.dirLastCopiedTo != undefined) {
this won't work. in javascript you have to use `typeof self.dirInfo.dirLastCopiedTo !== 'undefined'`. Alternatively, use underscore: `!_.isUndefined(self.dirInfo.dirLastCopiedTo)`.

2019-01-07 14:56 UTC, ChristophWurst commented on core/js/oc-dialogs.js
> +	filepicker:function(title, callback, multiselect, mimetypeFilter, modal, type, path) {
I doubt this is possible with the browsers we aim to support. The current style is fine IMO.

2019-01-07 14:56 UTC, ChristophWurst commented on core/js/oc-dialogs.js
> +		if (path == undefined) {
again, checking for undefined like this won't work. use `path = path || ''`.

2019-01-08 07:00 UTC, ChristophWurst requested changes

2019-01-08 07:00 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +			if (typeof self.dirInfo.dirLastCopiedTo !== undefined) {
```suggestion
			if (typeof self.dirInfo.dirLastCopiedTo !== 'undefined') {
```

2019-01-08 10:51 UTC, rummatee commented on apps/files/js/filelist.js
> +			if (self.dirInfo.dirLastCopiedTo != undefined) {
okay sorry that I needed another hint to fix this correctly.
However I looked through both filelist.js and oc-dialogs.js and both use direct comparison with undefined several times. Should I create a new pull request to fix that or is there a reason that in these cases it should directly compare?
Also is there a good way to check for these kinds of issues? Of course I tested my commits manually before pushing them and it behaved as expected.

2019-01-08 13:01 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +			if (self.dirInfo.dirLastCopiedTo != undefined) {
I'm not sure if this comparison is even a problem in modern browsers. So let's keep the other code unchanged unless there are any issues ;)

2019-01-08 15:45 UTC, rummatee commented on apps/files/js/filelist.js
> +			if (self.dirInfo.dirLastCopiedTo != undefined) {
okay sure.
Is my code okay now?

2019-01-08 15:53 UTC, ChristophWurst approved these changes
Code looks good!

2019-01-09 01:53 UTC, jancborchardt commented
Here too @rullzer @MorrisJobke what about the Drone failure? Is it just unrelated?

2019-01-09 08:54 UTC, MorrisJobke commented
The failures are fixed on master already (issue with the PHP 7.0 to 7.3 compatibility). Either rebase or we can just assume that they will work and this is then ready for review and merge.

2019-01-09 17:48 UTC, MorrisJobke commented
@rummatee It seems that your force push closed this PR 🙈 Could you open a new one?

2019-01-09 17:49 UTC, rummatee commented
yeah, I didn't see the rebase conflicts and accidentally pushed to remove all my commits

2019-01-09 17:56 UTC, rummatee commented
hmm does it show my commits again when I click on reopen?

2019-01-09 18:13 UTC, rummatee commented
> @rummatee It seems that your force push closed this PR see_no_evil Could you open a new one?

now that I reopened it, it doesn't seem to run the checks. Do I have to create a new PR?

2019-01-09 18:20 UTC, MorrisJobke commented
> now that I reopened it, it doesn't seem to run the checks. Do I have to create a new PR?

Or rebase again 🙈

2019-01-14 17:09 UTC, juliushaertl commented on core/js/oc-dialogs.js
> +		if (path == undefined) {
We don't need the if-clause anymore since we have the default value assigned with `path = path  || ''`

2019-01-14 17:10 UTC, juliushaertl commented on core/js/oc-dialogs.js
> +	filepicker:function(title, callback, multiselect, mimetypeFilter, modal, type, path) {
Yes, IE doesn't support them https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

2019-01-14 17:17 UTC, juliusknorr requested changes
Small nitpick. Otherwise works as expected and the code looks fine :+1:

2019-01-17 08:03 UTC, rummatee commented on core/js/oc-dialogs.js
> +		if (path == undefined) {
oh, I thought I had long done this.
Now I amended it to my last commit.

2019-01-18 13:31 UTC, juliusknorr approved these changes

2019-01-18 13:32 UTC, juliushaertl commented
Signed-off messages are fine. DCO bot seems to have some issues. :wink:

2019-01-18 16:20 UTC, merged