fix user creation using LDAP Plugin
nextcloud/server pull request #12452
Opened 2018-11-14 14:16 UTC by viniciuscb

When upgrading our installation to nextcloud14 we could not anymore create users in LDAP.

These are changes in user_ldap app that needed to be made to the createUser in the plugin work again. 

We needed to change the createUser function in our plugin also, now it returns the user DN in LDAP, instead of returning a boolean. Other developers who created a plugin for LDAP will need to change this also. 

Their code will break anyway when they try to upgrade to nc14, so we are now throwing an exception when the custom createUser function returns true.

Here is our plugin code:
https://gitlab.com/eita/rios/user_ldap_extended/tree/nc14

2019-02-14 11:58 UTC, blizzz commented
@viniciuscb sorry, I missed this PR. Ideally, next time ping the @nextcloud/ldap group, to ensure it does not get buried.

2019-02-14 12:04 UTC, blizzz requested changes

2019-02-14 12:04 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +		throw new \Exception('Could not create user in LDAP backend.');
why do we need the Exception here? I am afraid this kills creation of local users.

2019-02-19 21:36 UTC, viniciuscb commented
> @viniciuscb sorry, I missed this PR. Ideally, next time ping the @nextcloud/ldap group, to ensure it does not get buried.

Hi @blizzz I will take a look and test it in master.

2019-03-01 08:46 UTC, ChristophWurst commented
Any updates, @viniciuscb? The feature freeze for Nextcloud 16 is today, hence I'm afraid we have to move this to 17.

2019-03-01 09:29 UTC, blizzz commented
@ChristophWurst it's a bug fix, therefore the freeze does not apply here

2019-03-01 16:30 UTC, viniciuscb commented on apps/user_ldap/lib/User_LDAP.php
> +		throw new \Exception('Could not create user in LDAP backend.');
@blizzz I've put out this exception.

2019-03-01 16:31 UTC, viniciuscb commented on apps/user_ldap/lib/User_LDAP.php
> +					$this->access->connection->writeToCache("userExists".$username, true);
@blizzz put out writeToCache, tested and it worked. Maybe it did not work in previous versions.

2019-03-01 16:33 UTC, viniciuscb commented
@blizzz @ChristophWurst took a review according to @blizzz recommendations, tested in local (creating a ldap user / group), have run the automated tests, all worked.

2019-03-05 00:17 UTC, blizzz commented
I plan to review tomorrow

2019-03-05 09:49 UTC, blizzz reviewed
Just one remark, good otherwise!

2019-03-05 09:49 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +					throw new \Exception("LDAP Plugin: Method createUser changed to return the user DN instead of boolean.");
This could be made more precisely to an [\UnexpectedValueException](https://secure.php.net/manual/en/class.unexpectedvalueexception.php). I would like to reduce throwing generic exceptions and instead being more to the point.

Could you also add a @throws tag to the PhpDoc? Since other methods pass on simple `\Exception`, that would suffice for now.

2019-03-05 09:50 UTC, MorrisJobke approved these changes
Code makes sense 👍

2019-03-13 09:50 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +					throw new \Exception("LDAP Plugin: Method createUser changed to return the user DN instead of boolean.");
@viniciuscb would this last request be possible?

2019-03-14 15:14 UTC, viniciuscb commented on apps/user_ldap/lib/User_LDAP.php
> +					throw new \Exception("LDAP Plugin: Method createUser changed to return the user DN instead of boolean.");
solved

2019-03-14 15:21 UTC, blizzz approved these changes

2019-03-14 15:22 UTC, blizzz commented
\backport to stable15

2019-03-14 15:22 UTC, blizzz commented
\backport to stable14

2019-03-14 15:28 UTC, MorrisJobke commented
/backport to stable15

2019-03-14 15:28 UTC, MorrisJobke commented
/backport to stable14

2019-03-14 19:30 UTC, MorrisJobke commented
### Status of [17004](https://drone.nextcloud.com/nextcloud/server/17004): failure

#### ENABLE_OPENLDAP=true, ENABLE_REDIS=true, TESTS=integration-ldap-openldap-features
 * build/integration/ldap_features/ldap-openldap.feature:106
 * build/integration/ldap_features/ldap-openldap.feature:127
 * build/integration/ldap_features/ldap-openldap.feature:148
<details><summary>Show full log</summary>

```
  Scenario: Test LDAP group membership with intermediate groups not matching filter # /drone/src/github.com/nextcloud/server/build/integration/ldap_features/ldap-openldap.feature:106
[Thu Mar 14 18:07:00 2019] 127.0.0.1:57172 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config
[Thu Mar 14 18:07:00 2019] 127.0.0.1:57176 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
[Thu Mar 14 18:07:00 2019] 127.0.0.1:57182 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
    Given modify LDAP configuration                                                 # LDAPContext::modifyLDAPConfiguration()
      | ldapBaseGroups                | ou=OtherGroups,dc=nextcloud,dc=ci            |
      | ldapGroupFilter               | (&(cn=Gardeners)(objectclass=groupOfNames))  |
      | ldapNestedGroups              | 1                                            |
      | useMemberOfToDetectMembership | 1                                            |
      | ldapUserFilter                | (&(objectclass=inetorgperson)(!(uid=alice))) |
      | ldapExpertUsernameAttr        | uid                                          |
      | ldapGroupMemberAssocAttr      | member                                       |
    And As an "admin"                                                               # LDAPContext::asAn()
[Thu Mar 14 18:07:00 2019] 127.0.0.1:57194 [200]: /ocs/v2.php/cloud/groups
    And sending "GET" to "/cloud/groups"                                            # LDAPContext::sendingTo()
[Thu Mar 14 18:07:00 2019] 127.0.0.1:57206 [404]: /ocs/v2.php/cloud/groups/Gardeners/users
    And sending "GET" to "/cloud/groups/Gardeners/users"                            # LDAPContext::sendingTo()
    Then the OCS status code should be "200"                                        # LDAPContext::theOCSStatusCodeShouldBe()
      Failed asserting that SimpleXMLElement Object &000000006275076400000000279c7e09 (
          0 => '404'
      ) matches expected '200'.
    And the "users" result should match                                             # LDAPContext::theGroupResultShouldMatch()
      | alice  | 0 |
      | clara  | 1 |
      | elisa  | 1 |
      | gustaf | 1 |
      | jesper | 1 |
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57224 [200]: /apps/testing/clean_opcode_cache.php
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57226 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01

  Scenario: Test LDAP group membership with intermediate groups not matching filter and without memberof # /drone/src/github.com/nextcloud/server/build/integration/ldap_features/ldap-openldap.feature:127
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57244 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57258 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57266 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
    Given modify LDAP configuration                                                                      # LDAPContext::modifyLDAPConfiguration()
      | ldapBaseGroups                | ou=OtherGroups,dc=nextcloud,dc=ci            |
      | ldapGroupFilter               | (&(cn=Gardeners)(objectclass=groupOfNames))  |
      | ldapNestedGroups              | 1                                            |
      | useMemberOfToDetectMembership | 0                                            |
      | ldapUserFilter                | (&(objectclass=inetorgperson)(!(uid=alice))) |
      | ldapExpertUsernameAttr        | uid                                          |
      | ldapGroupMemberAssocAttr      | member                                       |
    And As an "admin"                                                                                    # LDAPContext::asAn()
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57284 [200]: /ocs/v2.php/cloud/groups
    And sending "GET" to "/cloud/groups"                                                                 # LDAPContext::sendingTo()
[Thu Mar 14 18:07:01 2019] 127.0.0.1:57300 [404]: /ocs/v2.php/cloud/groups/Gardeners/users
    And sending "GET" to "/cloud/groups/Gardeners/users"                                                 # LDAPContext::sendingTo()
    Then the OCS status code should be "200"                                                             # LDAPContext::theOCSStatusCodeShouldBe()
      Failed asserting that SimpleXMLElement Object &000000006275072d00000000279c7e09 (
          0 => '404'
      ) matches expected '200'.
    And the "users" result should match                                                                  # LDAPContext::theGroupResultShouldMatch()
      | alice  | 0 |
      | clara  | 1 |
      | elisa  | 1 |
      | gustaf | 1 |
      | jesper | 1 |
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57324 [200]: /apps/testing/clean_opcode_cache.php
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57326 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01

  Scenario: Test LDAP group membership with intermediate groups not matching filter, numeric group ids # /drone/src/github.com/nextcloud/server/build/integration/ldap_features/ldap-openldap.feature:148
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57338 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57346 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57364 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
    Given modify LDAP configuration                                                                    # LDAPContext::modifyLDAPConfiguration()
      | ldapBaseGroups                | ou=NumericGroups,dc=nextcloud,dc=ci          |
      | ldapGroupFilter               | (&(cn=2000)(objectclass=groupOfNames))       |
      | ldapNestedGroups              | 1                                            |
      | useMemberOfToDetectMembership | 1                                            |
      | ldapUserFilter                | (&(objectclass=inetorgperson)(!(uid=alice))) |
      | ldapExpertUsernameAttr        | uid                                          |
      | ldapGroupMemberAssocAttr      | member                                       |
    And As an "admin"                                                                                  # LDAPContext::asAn()
[Thu Mar 14 18:07:02 2019] ldap_control_paged_result_response(): Result is: No such object (32) at /drone/src/github.com/nextcloud/server/apps/user_ldap/lib/LDAP.php#74
[Thu Mar 14 18:07:02 2019] 127.0.0.1:57380 [200]: /ocs/v2.php/cloud/groups
    And sending "GET" to "/cloud/groups"                                                               # LDAPContext::sendingTo()
[Thu Mar 14 18:07:03 2019] 127.0.0.1:57392 [404]: /ocs/v2.php/cloud/groups/2000/users
    And sending "GET" to "/cloud/groups/2000/users"                                                    # LDAPContext::sendingTo()
    Then the OCS status code should be "200"                                                           # LDAPContext::theOCSStatusCodeShouldBe()
      Failed asserting that SimpleXMLElement Object &00000000627507fa00000000279c7e09 (
          0 => '404'
      ) matches expected '200'.
    And the "users" result should match                                                                # LDAPContext::theGroupResultShouldMatch()
      | alice  | 0 |
      | clara  | 1 |
      | elisa  | 1 |
      | gustaf | 1 |
      | jesper | 1 |
[Thu Mar 14 18:07:03 2019] 127.0.0.1:57426 [200]: /apps/testing/clean_opcode_cache.php
[Thu Mar 14 18:07:04 2019] 127.0.0.1:57428 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01

```
</details>


#### ENABLE_OPEN [...]

2019-03-14 19:31 UTC, MorrisJobke commented
@viniciuscb @blizzz Looks like there is something wrong with the tests :/

2019-03-14 21:39 UTC, blizzz commented
rebase might solve it

2019-03-21 09:22 UTC, MorrisJobke commented
Rebased on master: #14778

2019-03-21 09:22 UTC, closed without merging