Add welcome bot
nextcloud/server pull request #12476
Opened 2018-11-15 22:09 UTC by rullzer

I installed the welcome bot.

This adds the message for new contributors that have their first PR merged.

We can also add:
 * First issue
 * Fist PR opened

See: https://github.com/behaviorbot/welcome?installation_id=457148&setup_action=install

@jospoortvliet @jancborchardt feel free to adjust the wording.

2018-11-15 22:16 UTC, skjnldsv commented
Could be nice to also have links to the irc freenode? 
Maybe also our code of conduct? I dunno :)

2018-11-15 22:19 UTC, rullzer commented
@skjnldsv good point! But maybe we could do that also when the first PR is opend ;)

anyway that is why I wanted input. As I'm sure we also probably need fancy emojis etc ;)

2018-11-16 08:35 UTC, MorrisJobke requested changes

2018-11-16 08:35 UTC, MorrisJobke commented on .github/config.yml
> +    Thanks for your first pull request and welcome to the club!
```suggestion
    Thanks for your first pull request and welcome to the community!
```

2018-11-16 08:35 UTC, MorrisJobke commented on .github/config.yml
> +    Feel free to keep them comming!
```suggestion
    Feel free to keep them coming! If you are looking for issues to tackle then have a look at this selection: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
```

2018-11-16 12:45 UTC, MorrisJobke approved these changes

2018-11-16 12:47 UTC, skjnldsv approved these changes

2018-11-16 12:59 UTC, merged