Implementing trusted_proxies CIDR notation capability for IPv6
nextcloud/server pull request #12535
Opened 2018-11-19 16:43 UTC by olivermg

This PR aims to enhance the capabilities for specifying IP addresses in CIDR notation in the `trusted_proxies` config param (refer to issue #6550 and PR #12036 for more info):

- implement CIDR notation for IPv6
- introduce an abstraction layer for representation of IP addresses/ranges and CIDR notation handling, so other classes than just `Request` might benefit in the future
- update `config.sample.php` to reflect the new capabilities

2018-11-19 17:04 UTC, danielkesselberg commented
@olivermg, thank you for your great contribution :+1:

2018-11-19 17:06 UTC, danielkesselberg commented on lib/private/Net/AbstractIpAddress.php
> + * @copyright Copyright (c) 2018, ownCloud, Inc.
> @copyright Copyright (c) 2018, ownCloud, Inc.

Looks a bit wrong to me. You can read more about license here https://github.com/nextcloud/server/blob/master/contribute/HowToApplyALicense.md

2018-11-19 17:07 UTC, danielkesselberg commented on lib/private/Net/IIpAddress.php
> + * @since 15.0.0
I'm afraid but you are a bit to late for nextcloud 15. I would suggest `@since 15.0.0.` but lets ping @MorrisJobke for a final answer.

2018-11-19 18:35 UTC, rullzer commented on lib/private/Net/AbstractIpAddress.php
> + * @copyright Copyright (c) 2018, ownCloud, Inc.
Yep you own the copyright :)

2018-11-19 18:35 UTC, rullzer commented on lib/private/Net/IIpAddress.php
> + * @since 15.0.0
Yes this will be 16 RC1 is thursday already and we are in freeze

2018-11-19 18:42 UTC, rullzer commented
@olivermg cool stuff!

Just on a general note.
The `\OC` namespace is for private code. And things that should only be used internally in the server.
`\OCP` contains the code and interfaces to be used by apps etc. So it seems to me a lot of this can be moved to `\OCP`.

On a releated note. Would it make sense to see if we could just wrap around https://api.symfony.com/2.3/Symfony/Component/HttpFoundation/IpUtils.html ? The less code we have to maintain ourselfs the better :wink:

2018-11-19 19:39 UTC, olivermg commented on lib/private/Net/AbstractIpAddress.php
> + * @copyright Copyright (c) 2018, ownCloud, Inc.
Okay, I'll adjust this

2018-11-19 19:41 UTC, olivermg commented on lib/private/Net/IIpAddress.php
> + * @since 15.0.0
Okay, so I'll set this to "16.0.0-RC1" or what is the proper version in this case?

2018-11-19 19:51 UTC, olivermg commented
> Just on a general note.
> The `\OC` namespace is for private code. And things that should only be used internally in the server.
> `\OCP` contains the code and interfaces to be used by apps etc. So it seems to me a lot of this can be moved to `\OCP`.

Yeah I see. I noticed the distinction between \OC and \OCP but wasn't realizing that apps might also benefit from this functionality. So I can move this over to \OCP of course.

> On a releated note. Would it make sense to see if we could just wrap around https://api.symfony.com/2.3/Symfony/Component/HttpFoundation/IpUtils.html ? The less code we have to maintain ourselfs the better

I wasn't yet aware of the fact that Nextcloud uses Symfony (wasn't even thinking about it). I agree that in this case it's more appropriate to wrap the Symfony functionality instead of implementing a duplicate.

So I assume your idea of this is to keep the interface stuff (as a generic entry point for Nextcloud core & apps for accessing IP address/subnet functionality) and just replace the underlying logic with wrappers that make use of the corresponding Symfony functionality instead of implementing the logic themselves?

2018-11-19 19:55 UTC, danielkesselberg commented
HttpFoundation is not a dependency right now. Request and Response are part of HttpFoundation as well. It could be confusing if there are OCP\Request and Symfony\Request?

2018-11-19 20:50 UTC, danielkesselberg commented on lib/private/Net/IIpAddress.php
> + * @since 15.0.0
`@since 16.0.0`

2018-11-20 09:13 UTC, MorrisJobke commented on lib/private/Net/IIpAddress.php
> + * @since 15.0.0
> Okay, so I'll set this to "16.0.0-RC1" or what is the proper version in this case?

The sentence by @rullzer was a bit confusing. He meant: the 15.0.0 RC 1 is on Thursday, so this needs to go into 16.

So `@since 16.0.0` is the correct one here 👍

2018-11-21 09:57 UTC, olivermg commented
Fyi: I've moved `IIpAddress` and `IpAddressFactory` to namespace `\OCP\Net`

2018-11-23 08:01 UTC, ChristophWurst requested changes
Code looks great! Thanks a lot!

Let's make this a bit more testable :wink:

2018-11-23 08:01 UTC, ChristophWurst commented on lib/public/Net/IpAddressFactory.php
> +	public static function isIpv6(string $address): bool {
generally speaking, we favor dynamic over static methods because they are mockable and therefore testable. Could you change this to dynamic methods, move this implementation to the `OC` namespace, add an interface for this to `OCP`, register the impl as alias for the interface and inject the interface wherever this factory is used?

Let me know if you need help with this :)

2018-11-25 09:36 UTC, olivermg commented on lib/private/Net/IpAddressV4.php
> +	private $original = '';
Sure, done. Those members were not meant to be in the concrete classes anyway.

2018-11-25 11:16 UTC, olivermg commented on lib/public/Net/IpAddressFactory.php
> +	public static function isIpv6(string $address): bool {
I think I've adjusted the code in the way you imagine. In detail, I've ...
- ...moved `IpAddressFactory` back to the `OC` namespace
- ...created `OCP\Net\IIpAddressFactory`
- ...register `IpAddressFactory` as alias/implementation for `IIpAddressFactory` in `OC\Server`
- ...get the implementation from `\OC::$server->getIpAddressFactory()` in `Request`

If anything is missing or does not conform to what you'd like it to be just let me know :-) .

2018-11-25 13:02 UTC, olivermg commented on lib/public/Net/IpAddressFactory.php
> +	public static function isIpv6(string $address): bool {
...on second thought might getting the factory via `\OC::$server->getIpAddressFactory()` not really be what you meant by _"inject the interface"_ (as it's not injection but relying on the global `\OC::$server`. However, I've looked through some code and found this pattern of `\OC::$server->getSomething()` to be of frequent use (e.g. in `OC\User\User`), so that's how I ended up doing it this way.

If there is a more elegant way of how to do this via proper injection, it'd be awesome if you could point me to an example in the code.

2018-11-25 14:07 UTC, olivermg commented on lib/public/Net/IpAddressFactory.php
> +	public static function isIpv6(string $address): bool {
Okay, I think I'll improve this some more by...
- ...injecting an instance of `IIpAddressFactory` into the constructor of `Request` (instead of accessing `\OC::$server` globally).
- ...adjust the parts of the code that instantiate `Request` to actually inject the instance of `IIpAddressFactory`. If I'm not mistaken there are only two such locations in the code, both in `Server`, so I can inject `$this->getIpAddressFactory()` there.

2018-11-26 13:16 UTC, ChristophWurst commented on lib/public/Net/IpAddressFactory.php
> +	public static function isIpv6(string $address): bool {
> Okay, I think I'll improve this some more by...

Yes, this is exactly how I pictured this. Sorry for not being more clear. Thanks!

2018-11-27 18:01 UTC, ChristophWurst commented on lib/private/AppFramework/Http/Request.php
> +								IIpAddressFactory $ipAddressFactory = null) {
Any particular reason why this is nullable?

2018-11-28 09:34 UTC, ChristophWurst commented on lib/private/AppFramework/Http/Request.php
> +								IIpAddressFactory $ipAddressFactory = null) {
> It'll take some time for me to put that additional effort into this.

Unfortunately this is the correct way to do this. Otherwise this is bound to fail someone in the future that assumes the argument is optional.

2019-01-05 18:53 UTC, johanfleury commented on lib/private/Net/IpAddressV4.php
> +		return '/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\/([0-9]{1,2})$/';
This regex matches invalid IPv4 subnets: <https://regex101.com/r/tjtE95/1> (same for IPv6 in the `IpAddressV6` class).

As IP address are numbers, I think you could use numerical comparison and avoid relying on regexes (that will most certainly be incorrect in a way or another). I'm not really into PHP so I'm not sure what's the best way to do that (to be honest it bugs me that this is not part of the standard library).

Also, I think it would be useful to warn the administrator when they put a wrong value in the configuration (thus using another "parsing" method).

2019-07-15 21:38 UTC, kesselb commented
I am unsure about this pr. The way we implement the logic looks quite complex compared to  https://github.com/symfony/http-foundation/blob/master/IpUtils.php. There is only a little chance that his logic (is ipv4 or is ipv6) changes in the near future (e.g. add ipvX).

@ChristophWurst what should we do? :thinking: 
@MorrisJobke looks like Nextcloud 18 to me :see_no_evil:

2019-10-24 12:55 UTC, ChristophWurst commented
> I am unsure about this pr. The way we implement the logic looks quite complex compared to https://github.com/symfony/http-foundation/blob/master/IpUtils.php. There is only a little chance that his logic (is ipv4 or is ipv6) changes in the near future (e.g. add ipvX).

I can second that.

2020-04-15 08:07 UTC, ChristophWurst commented
Due to lack of activity I will close this PR for now.

2020-04-15 08:07 UTC, closed without merging