handle mail send error gracefully
nextcloud/server pull request #12636
Opened 2018-11-23 15:57 UTC by schiessle

log the error in case a notification mail of a new share couldn't
be send to the recipient and finish the share operation successfully
fix https://github.com/nextcloud/server/issues/12597

2018-11-26 10:10 UTC, rullzer approved these changes

2018-11-26 10:10 UTC, rullzer commented
/backport to stable15

2018-11-26 10:10 UTC, rullzer commented
/backport to stable14

2018-11-28 18:50 UTC, schiessle commented on lib/private/Share20/Manager.php
> +			$this->logger->error('Share notification mail could not be send: ' . $e->getMessage());
@MorrisJobke done :smil

2018-11-29 15:32 UTC, ChristophWurst requested changes
Typo :wink: 

Is the returned bool used?

2018-11-29 15:32 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +			$this->logger->logException($e, ['message' => 'Share notification mail could not be send']);
sen**t**

2018-11-29 16:53 UTC, ChristophWurst requested changes
Result is never checked.

Ref https://github.com/nextcloud/server/blob/0f8de6ed7d08005d036969d1c371dd247f19443e/lib/private/Share20/Manager.php#L687-L694

2018-11-29 16:54 UTC, ChristophWurst commented
>  and finish the share operation successfully

soooo … this is intentional?

2018-11-29 17:35 UTC, ChristophWurst commented
> soooo … this is intentional?

Guess so https://github.com/nextcloud/server/issues/12597#issuecomment-441205645

2018-11-30 09:34 UTC, blizzz commented on lib/private/Share20/Manager.php
> +				$this->logger->error('Share notification mail could not be send to: ' . implode(', ', $failedRecipients));
here as well: sent

2018-12-04 18:35 UTC, schiessle commented
typo fixed

2018-12-05 10:44 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +		return true;
Also considering that the return code isn't even checked. https://github.com/nextcloud/server/pull/12636#pullrequestreview-179903643

2018-12-12 16:30 UTC, schiessle commented on lib/private/Share20/Manager.php
> +		return true;
If you move it to a higher level you need to have multiple try-catch blocks to always handle the same issue. IMHO way to error prone because you can bet that sooner or later you will call the function somewhere and forget the try-catch block. Further you would duplicate the same error handling again and again. The return values are not used until now, right. Still I thought it makes sense that a function which can fail or succeed communicate this to the outside. But if this is really an issue, feel free to add a commit which removes the return statements.

2018-12-12 16:50 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +		return true;
I have to disagree here. Errors should be handled wherever possible. And if you want to ignore this specific one just catch and discard it.

There's nothing worse than a silent error.

2018-12-18 10:45 UTC, schiessle commented on lib/private/Share20/Manager.php
> +		return true;
We inform the admin that he might check their mail setting by writing a log entry. Disturbing the user with an minor error (because the share can still be created) he can't fix anyway doesn't make sense.

2018-12-18 10:53 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +		return true;
> And if you want to ignore this specific one just catch and discard it.

I'm not talking about whether the error should be shown to the user or not but how error handling is done here.

2018-12-19 13:32 UTC, schiessle commented on lib/private/Share20/Manager.php
> +		return true;
sorry, seems that I'm lost here... just push a commit to this branch which the changes you want to have.

2018-12-19 13:50 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +		return true;
-> https://github.com/nextcloud/server/pull/12636/files#r239008468

2019-01-30 14:34 UTC, ChristophWurst approved these changes
I'm fine with @schiessle's changes as this method is solely used in this class :+1:

2019-01-30 15:02 UTC, danielkesselberg commented on lib/private/Share20/Manager.php
> +				return false;
I'm not asking for a change here but the method has no `@return` annotation nor a return type hint. `return;` would be more correct here. `return false;` without another `return true;` looks wrong to me :see_no_evil:

2019-01-30 15:09 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +				return false;
Yeah … my bad. Fixed :)

2019-01-30 15:10 UTC, MorrisJobke approved these changes
Code looks good 👍

2019-01-30 19:05 UTC, merged