Smaller icon and h2 in emptycontent inside the header
nextcloud/server pull request #12711
Opened 2018-11-28 18:10 UTC by nickvergessen

As discussed while looking at https://github.com/nextcloud/notifications/pull/209

2018-11-28 21:05 UTC, skjnldsv requested changes

2018-11-28 21:05 UTC, skjnldsv commented on core/css/styles.scss
> +header #emptycontent,
It should be in header scss :)

2018-12-04 15:47 UTC, nickvergessen commented on core/css/styles.scss
> +header #emptycontent,
done

2018-12-04 15:52 UTC, skjnldsv approved these changes

2018-12-04 16:46 UTC, jancborchardt approved these changes
Looks good! Thanks a lot :heart:

2018-12-04 16:46 UTC, merged