Move OAuth2 db code to QBMapper and make it strict
nextcloud/server pull request #12886
Opened 2018-12-06 14:37 UTC by rullzer

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-12-06 14:40 UTC, ChristophWurst requested changes

2018-12-06 14:40 UTC, ChristophWurst commented on apps/oauth2/lib/Db/AccessTokenMapper.php
> +		} catch (\Exception $e) {
Please catch specific exceptions (does not exist, multiple objects returned) instead of the generic one, otherwise this will also swallow syntax errors, db connection issues and so on :wink:

2018-12-06 14:40 UTC, ChristophWurst commented on apps/oauth2/lib/Db/ClientMapper.php
> +		} catch (\Exception $e) {
same same but different

2018-12-06 14:41 UTC, rullzer commented on apps/oauth2/lib/Db/AccessTokenMapper.php
> +		} catch (\Exception $e) {
Meh but then I ahve 2 catch statements... meh.... but yeah you are right

2018-12-06 14:53 UTC, MorrisJobke commented on apps/oauth2/lib/Db/AccessTokenMapper.php
> +		} catch (\Exception $e) {
#12887

2018-12-06 22:48 UTC, danielkesselberg commented on apps/oauth2/lib/Db/AccessTokenMapper.php
> +		} catch (\Exception $e) {
https://wiki.php.net/rfc/multiple-catch for php7.1+ and maybe another argument to drop php7.0 from nextcloud 16 :thinking:

2018-12-06 23:07 UTC, kesselb approved these changes

2018-12-07 12:37 UTC, ChristophWurst approved these changes
LGTM

2018-12-07 12:37 UTC, merged