Add note to dav endpoint
nextcloud/server pull request #12978
Opened 2018-12-10 14:32 UTC by tobiasKaminsky

Fix https://github.com/nextcloud/server/issues/11702

It is my first PR, @schiessle helped me a bit on how to do this.

2018-12-11 13:31 UTC, tobiasKaminsky commented
Anyone up for a review? @schiessle @rullzer

2019-01-03 12:47 UTC, blizzz commented
do you have a curl example for quickly testing it?

2019-01-03 12:55 UTC, blizzz requested changes

2019-01-03 12:55 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +		if ($user !== null) {
vice versa, return if the user is null at the beginning avoids having the big if-block.

2019-01-03 12:55 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +	 * @return int
a string is returned

2019-01-03 12:55 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +				$notes .= $share->getNote() . " ";
what is the purpose of getting all share notes returned only concatenated by a space?

2019-01-04 08:47 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/Node.php
> +				$notes .= $share->getNote() . " ";
I guess only one share type will have a note, so this is just a quick and ugly way not to deal with checking.
Hints are more than welcome ;-)

2019-01-04 11:09 UTC, tobiasKaminsky commented
@blizzz curl:
```
curl --request GET \
  --url 'http://localhost:9999/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FFOLDER%2F&reshares=true&subfiles=true&shared_with_me=true' \
  --header 'authorization: Basic dG9iaTp0b2Jp' \
  --header 'cookie: nc_sameSiteCookielax=true;nc_sameSiteCookiestrict=true' \
  --header 'ocs-apirequest: true' \
  --cookie 'nc_sameSiteCookielax=true;nc_sameSiteCookiestrict=true'```

Parameter path= needs to be adjusted to your needs.
Then you'll see "<note>123 123</note>" in response.

2019-01-04 15:12 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +				$notes .= $share->getNote() . " ";
I share one file with a "personal note" to a user and the same with a "group note" to a group he is member of. The web interface only displays the personal note.  @nextcloud/sharing is this intentional or undefined behaviour?

The request returns two elements with a note each:

```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <element>
   <id>14</id>
   <share_type>0</share_type>
   <.../>
   <note>personal note</note>
   <path>/php.ini</path>
   <item_type>file</item_type>
   <file_target>/php.ini</file_target>
   <share_with>person_15</share_with>
   <.../>
  </element>
  <element>
   <id>15</id>
   <share_type>1</share_type>
   <.../>
   <note>group note</note>
   <path>/php.ini</path>
   <item_type>file</item_type>
   <file_target>/php.ini</file_target>
   <share_with>barfoo</share_with>
   <.../>
  </element>
 </data>
</ocs>

```

Now I shared to another group the target user is member of and added a different note again. This creates another element in the result set. No concatenation takes place. Internally the file is represented by different node instances, therefore you get multiple element  sets for the entry.

Therefore, just return the first note you encounter. There won't be others (just leave a comment about that). 

I wonder whether there is a short cut to get the share data from the node itself, to avoid asking the share manager about everything. This would improve maintainability, as of new we'd probably forget to query a new sharing type in case it'll be added at some point.

2019-01-15 10:51 UTC, tobiasKaminsky commented
@blizzz I am out here somehow…
what can I do to get this in?

2019-02-14 10:48 UTC, AndyScherzinger commented
Pinging @blizzz and @rullzer to get some attention :) Reading through the comments it seems this PR is. Done but not merged and would help us on the Android client side :) ❤️

2019-02-15 00:07 UTC, blizzz commented
Um, the provided curl call does not help as it does not got via webdav. If i remember correctly, I was using a dav call back then, but that's too late now.

@tobiasKaminsky @nextcloud/sharing what do you think about? (untested)

```diff
diff --git a/apps/dav/lib/Connector/Sabre/Node.php b/apps/dav/lib/Connector/Sabre/Node.php
index fd895c291d..b6433e6e0b 100644
--- a/apps/dav/lib/Connector/Sabre/Node.php
+++ b/apps/dav/lib/Connector/Sabre/Node.php
@@ -298,25 +298,27 @@ abstract class Node implements \Sabre\DAV\INode {
     */
    public function getNoteFromShare($user) {
        if ($user == null) {
-           return "";
+           return '';
        }
 
-       $userShares = $this->shareManager->getSharedWith($user, Share::SHARE_TYPE_USER, $this, -1);
-       $groupShares = $this->shareManager->getSharedWith($user, Share::SHARE_TYPE_GROUP, $this, -1);
-       $circleShares = $this->shareManager->getSharedWith($user, Share::SHARE_TYPE_CIRCLE, $this, -1);
-       $roomShares = $this->shareManager->getSharedWith($user, Share::SHARE_TYPE_ROOM, $this, -1);
-
-       $shares = array_merge($userShares, $groupShares, $circleShares, $roomShares);
-       $shares = array_filter($shares, function (IShare $share) use ($user) {
-           return $share->getShareOwner() !== $user;
-       });
-
-       $notes = "";
-       foreach ($shares as $share) {
-           $notes .= $share->getNote() . " ";
+       $types = [
+           Share::SHARE_TYPE_USER,
+           Share::SHARE_TYPE_GROUP,
+           Share::SHARE_TYPE_CIRCLE,
+           Share::SHARE_TYPE_ROOM
+       ];
+
+       foreach ($types as $shareType) {
+           $shares = $this->shareManager->getSharedWith($user, $shareType, $this, -1);
+           foreach ($shares as $share) {
+               $note = $share->getNote();
+               if($share->getShareOwner() !== $user && !empty($note)) {
+                   return $note;
+               }
+           }
        }
 
-       return $notes;
+       return '';
    }
 
    /**
```

2019-02-15 08:12 UTC, tobiasKaminsky commented
@blizzz thanks for taking care of it.
It seems to work.
The only strange thing is that I get a "null" back for any empty note.
On cadaver it is like this:
```
 <d:prop>
        <d:getlastmodified>Thu, 23 Nov 2017 08:20:33 GMT</d:getlastmodified>
        <d:getetag>&quot;dc947c447f85f5160ce58724002f1c52&quot;</d:getetag>
        <d:getcontenttype>image/png</d:getcontenttype>
        <d:resourcetype/>
        <oc:fileid>249</oc:fileid>
        <oc:id>00000249ocjycgrudn78</oc:id>
        <oc:permissions>SGDNVW</oc:permissions>
        <oc:size>45754</oc:size>
        <d:getcontentlength>45754</d:getcontentlength>
        <nc:has-preview>true</nc:has-preview>
        <oc:favorite>0</oc:favorite>
        <oc:comments-unread>0</oc:comments-unread>
        <oc:owner-display-name>Tobi Kaminsky</oc:owner-display-name>
        <oc:share-types/>
        <nc:note></nc:note>
      </d:prop>
```
and with filled note:
```
<d:prop>
        <d:getlastmodified>Thu, 23 Nov 2017 08:04:19 GMT</d:getlastmodified>
        <d:getetag>&quot;5a168103e2767&quot;</d:getetag>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <oc:fileid>246</oc:fileid>
        <oc:id>00000246ocjycgrudn78</oc:id>
        <oc:permissions>SRGDNVCK</oc:permissions>
        <oc:size>0</oc:size>
        <nc:has-preview>false</nc:has-preview>
        <oc:favorite>0</oc:favorite>
        <oc:comments-unread>0</oc:comments-unread>
        <oc:owner-display-name>Tobi Kaminsky</oc:owner-display-name>
        <oc:share-types/>
        <nc:is-encrypted>0</nc:is-encrypted>
        <nc:note>ShareAble</nc:note>
      </d:prop>
```

On first, I do get null back on android, but it should be "" (empty string), or?
Maybe this is something on my side…

2019-02-15 08:28 UTC, tobiasKaminsky commented
Nevermind this is on my side…

2019-02-25 07:59 UTC, tobiasKaminsky commented
So this is fine from my side.
Can we get this into NC16?

2019-02-25 10:57 UTC, blizzz commented
@tobiasKaminsky mind rebasing? I suppose that should make CI run.

2019-02-25 10:58 UTC, blizzz commented
@tobiasKaminsky and, if the changes work for you, please commit them. I cannot since it is in your fork.

2019-02-26 17:15 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +	public function getNoteFromShare($user) {
sorry, but the indentation is off. We use tabs not spaces.

2019-02-26 17:16 UTC, blizzz approved these changes
after formatting ;)

2019-02-26 17:17 UTC, blizzz commented
another reviewer, please?

2019-02-27 06:14 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/Node.php
> +	public function getNoteFromShare($user) {
Fixed

2019-03-01 08:49 UTC, ChristophWurst approved these changes
Looks good to me otherwise

2019-03-01 08:49 UTC, ChristophWurst commented on apps/dav/lib/Connector/Sabre/Node.php
> +		if ($user == null) {
```suggestion
		if ($user === null) {
```

2019-03-04 11:56 UTC, MorrisJobke commented
### Status of [16667](https://drone.nextcloud.com/nextcloud/server/16667): failure

 * DB=sqlite, ENABLE_REDIS=false, PHP=7.3
<details><summary>Show full log</summary>

```
There was 1 failure:

1) Test\User\DatabaseTest::testSearch
Failed asserting that actual size 3 matches expected size 2.

/drone/src/github.com/nextcloud/server/tests/lib/User/Backend.php:114
/drone/src/github.com/nextcloud/server/tests/lib/User/DatabaseTest.php:119

--

There was 1 risky test:

1) OCA\TwoFactorBackupCodes\Tests\Db\BackupCodeMapperTest::testInsertArgonEncryptedCodes
This test did not perform any assertions

```
</details>


 * DB=mysqlmb4, ENABLE_REDIS=false, PHP=7.3
<details><summary>Show full log</summary>

```
There was 1 failure:

1) TrashbinTest::testExpireOldFiles
Failed asserting that null is identical to 'file2.txt'.

/drone/src/github.com/nextcloud/server/apps/files_trashbin/tests/TrashbinTest.php:186

--

There was 1 risky test:

1) OCA\TwoFactorBackupCodes\Tests\Db\BackupCodeMapperTest::testInsertArgonEncryptedCodes
This test did not perform any assertions

```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=app-files
     * tests/acceptance/features/app-files.feature:60
     * tests/acceptance/features/app-files.feature:72
     * tests/acceptance/features/app-files.feature:79
     * tests/acceptance/features/app-files.feature:90
     * tests/acceptance/features/app-files.feature:97
     * tests/acceptance/features/app-files.feature:126
     * tests/acceptance/features/app-files.feature:133
<details><summary>Show full log</summary>

```
  Scenario: viewing a favorite file in its folder does not prevent opening the details view in "All files" section # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:60
    Given I am logged in                                                                                           # LoginPageContext::iAmLoggedIn()
    And I mark "welcome.txt" as favorite                                                                           # FileListContext::iMarkAsFavorite()
    And I see that "welcome.txt" is marked as favorite                                                             # FileListContext::iSeeThatIsMarkedAsFavorite()
    And I open the "Favorites" section                                                                             # AppNavigationContext::iOpenTheSection()
    And I open the details view for "welcome.txt"                                                                  # FileListContext::iOpenTheDetailsViewFor()
      Row for file welcome.txt in file list could not be found after 100 seconds
      File actions menu button for file welcome.txt in file list could not be found after 100 seconds (NoSuchElementException)
    And I see that the details view is open                                                                        # FilesAppContext::iSeeThatTheDetailsViewIsOpen()
    And I view "welcome.txt" in folder                                                                             # FileListContext::iViewInFolder()
    And I see that the current section is "All files"                                                              # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    When I open the details view for "welcome.txt"                                                                 # FileListContext::iOpenTheDetailsViewFor()
    Then I see that the details view is open                                                                       # FilesAppContext::iSeeThatTheDetailsViewIsOpen()
  Scenario: show recent files                                                 # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:72
    Given I am logged in                                                      # LoginPageContext::iAmLoggedIn()
    And I create a new folder named "Folder just created"                     # FileListContext::iCreateANewFolderNamed()
      │ Create menu button in file list could not be clicked
      │ Exception message: Element is not currently visible and so may not be interacted with
      │ Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      │ System info: host: '19fab3471f9a', ip: '172.17.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-141-generic', java.version: '1.8.0_91'
      │ Driver info: driver.version: unknown
      │ Trying again
      │ 
    When I open the "Recent" section                                          # AppNavigationContext::iOpenTheSection()
    Then I see that the current section is "Recent"                           # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    Then I see that the file list contains a file named "Folder just created" # FileListContext::iSeeThatTheFileListContainsAFileNamed()
      Row for file Folder just created in file list could not be found after 100 seconds (NoSuchElementException)
  Scenario: show recent files for a second time                               # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:79
    Given I am logged in                                                      # LoginPageContext::iAmLoggedIn()
    And I open the "Recent" section                                           # AppNavigationContext::iOpenTheSection()
    And I see that the current section is "Recent"                            # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    And I open the "All files" section                                        # AppNavigationContext::iOpenTheSection()
    And I see that the current section is "All files"                         # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    And I create a new folder named "Folder just created"                     # FileListContext::iCreateANewFolderNamed()
    When I open the "Recent" section                                          # AppNavigationContext::iOpenTheSection()
    Then I see that the current section is "Recent"                           # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    Then I see that the file list contains a file named "Folder just created" # FileListContext::iSeeThatTheFileListContainsAFileNamed()
      Row for file Folder just created in file list could not be found after 100 seconds (NoSuchElementException)
  Scenario: show favorites                                            # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:90
    Given I am logged in                                              # LoginPageContext::iAmLoggedIn()
    And I mark "welcome.txt" as favorite                              # FileListContext::iMarkAsFavorite()
    When I open the "Favorites" section                               # AppNavigationContext::iOpenTheSection()
    Then I see that the current section is "Favorites"                # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    Then I see that the file list contains a file named "welcome.txt" # FileListContext::iSeeThatTheFileListContainsAFileNamed()
      Row for file welcome.txt in file list could not be found after 100 seconds (NoSuchElementException)
  Scenario: show favorites for a second time                          # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:97
    Given I am logged in                                              # LoginPageContext::iAmLoggedIn()
    And I open the "Favorites" section                                # AppNavigationContext::iOpenTheSection()
    And I see that the current section is "Favorites"                 # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    And I open the "All files" section                                # AppNavigationContext::iOpenTheSection()
    And I see that the current section is "All files"                 # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    And I mark "welcome.txt" as favorite                              # FileList [...]

2019-03-04 11:58 UTC, MorrisJobke commented
Failures are unrelated -> merge

2019-03-04 11:58 UTC, merged

2019-03-04 12:09 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Node.php
> +			$shares = $this->shareManager->getSharedWith($user, $shareType, $this, -1);
I doubt this works... The third argument expects a node for sure... but this is a different note that the sharing one

2019-03-04 12:09 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +			$propFind->handle(self::SHARE_NOTE, function() use ($node, $httpRequest) {
Similar comments as to https://github.com/nextcloud/server/pull/14429

I think it would make sense to move this to the share plugin we have.
Because in it current state. If you have N entries in the folder you propfind. This will fire off N*4 queries. This won't scale.

2019-03-04 12:16 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	const SHARE_NOTE = '{http://nextcloud.org/ns}note';
also `share-note` maybe... as just `note` is a bit generic?

2019-03-04 12:29 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Node.php
> +			$shares = $this->shareManager->getSharedWith($user, $shareType, $this, -1);
Ok so it works because the actual function e use int he share amanger is also present. But this will do :boom: at some point.

Either we revert this or we fix it. Because this is not really something we can leave around and have do :boom: when we move to more strict typing. Especially since this isn't covered by any tests.

2019-03-04 12:37 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +			$shares = $this->shareManager->getSharedWith($user, $shareType, $this, -1);
We can fix it by putting an instanceof check against $this beforehand, in line 300. Would be the easiest thing to do, but perhaps not cleanest one. 

Alternative would be to retrieve always correct Node instance, if possible. There's no straight way from View or FileInfo, and I did not look deeper by now.

2019-03-04 12:43 UTC, tobiasKaminsky commented
Just for client side: will this be in NC16 (according to milestone) or NC17 as feature freeze was on friday?

2019-03-04 12:49 UTC, MorrisJobke commented
> Just for client side: will this be in NC16 (according to milestone) or NC17 as feature freeze was on friday?

16. if it doesn't get reverted.