Where is your data?
nextcloud/server pull request #13097
Opened 2018-12-16 17:42 UTC by weeman1337

For previous discussions also see #11319.

**ToDo**
- [ ] personal settings layout improvement
- [ ] settings input view

2018-12-16 17:52 UTC, weeman1337 commented
That's what the front end looks so far:
![image](https://user-images.githubusercontent.com/6216686/50056829-9b927400-0162-11e9-86ab-498afa968e8f.png)

For me it's hard to distinguish links and text as they're displayed the same. So I highlighted them with the primary color. I didn't find anything about that in the dev docs.

The "... is your admin" will have two ways for detection:
- Any admin user if none was selected in the settings
- The selected one from the settings

Any thoughts about that @nextcloud/designers ?

2018-12-17 16:01 UTC, skjnldsv commented
I really like it!
I agree with Jan's suggestions. I would also add that the plug icon doesn't really make any sense. Maybe use a [server icon](https://thenounproject.com/search/?q=server)?

2018-12-17 16:40 UTC, weeman1337 commented
> I would also add that the plug icon doesn't really make any sense

Fully agree. This is only a placeholder - I'm not happy with it, too.  
Should I extend the [NC icon set](https://docs.nextcloud.com/server/15/developer_manual/design/icons.html)? Is there any free icon set I can take the icon from?

> We could think about using "border-bottom: 1px dotted text-color" for marking links.

✓ will do that

> For admins, it's simpler to use "… contact them." instead of "him/her". Works as singular and plural too if there's multiple admins.

@jancborchardt do you suggest listing all admin users then? I thought about picking one of the admins and in addition give the option to define a specific one in the settings.

2018-12-17 16:43 UTC, skjnldsv commented
> @jancborchardt do you suggest listing all admin users then? I thought about picking one of the admins and in addition give the option to define a specific one in the settings.

That is one issue we have with the preferred provider program.
There is no official setting to define a 'contact' for a nextcloud instance. It could be a nice addition :)

2018-12-17 19:18 UTC, shironextcloud commented
>     * For admins, it's simpler to use "… contact them." instead of "him/her". Works as singular and plural too if there's multiple admins.
> 
>     * @shironextcloud what do you think? :)

agree on "them"

really nice :)

2018-12-18 18:50 UTC, weeman1337 commented
@nextcloud/designers regarding links, here are the two dotted options:

![text-decoration](https://user-images.githubusercontent.com/6216686/50175733-e8f71880-02fd-11e9-8087-df59a1e87bdb.png)
---
![border-bottom](https://user-images.githubusercontent.com/6216686/50175725-e399ce00-02fd-11e9-9d79-581b61adad94.png)
---
Where the `text-decoration` way looks cleaner on the whole `border-bottom` is easier to read.

2018-12-18 20:00 UTC, weeman1337 commented
Here is the view for the settings:

![image](https://user-images.githubusercontent.com/6216686/50179626-ccf87480-0307-11e9-8371-3c10f866beb3.png)

I placed it in the "Basic settings" at the bottom.

2018-12-18 20:03 UTC, skjnldsv commented
It looks amazing!!!
Can I be peaky and ask the loader to be on the button to save the form? :see_no_evil: We tend to do that in most of the places and looks better imho. Not that big of a deal though ;)

2018-12-18 20:15 UTC, weeman1337 commented
> Can I be peaky and ask the loader to be on the button to save the form? see_no_evil We tend to do that in most of the places and looks better imho. Not that big of a deal though ;)

@skjnldsv jep - fine for me. Can you give me an example, so I can have a look copy the style.

There is also some feedback (I took it from the settings above). Does anything common exist for that, too?

![image](https://user-images.githubusercontent.com/6216686/50180426-e00c4400-0309-11e9-8da4-3a9da1dbb2c8.png)

2018-12-18 20:17 UTC, skjnldsv commented
Could be nice to have a standard actually!
You know what, I'll let you decide! We could then make sure to have the new standard in as many places as we can on the settings! :rocket: :bowing_man:

2018-12-18 21:04 UTC, weeman1337 commented
@skjnldsv what about this:
![button](https://user-images.githubusercontent.com/6216686/50182901-db975980-0310-11e9-98b8-ddd9814f263f.gif)

2018-12-18 21:10 UTC, skjnldsv commented
I really like it!! :tada: :heart_eyes: 
Some quick thinking:
- I would actually make sure the size does not change that much, because it's confusing to the user.
- I would also not use an input since the loader cannot work (fallback to gif since no pseudo-elements can be applied on an inline element) Use a label to link the action to the input! :wink: 
- No need for the `...` since the loader already give a progress state
- I would use an icon by default for the save button. It draws attention and would also prevent your button from moving too much when switching from "save" to "saving" since the loader width would already be taken by the icon 

I'm sure @jancborchardt  will have some insights as well!

2018-12-19 22:20 UTC, weeman1337 commented
Update today: the server info is now stored and loaded.

I put the info into the config. Why?: My idea is if you deploy an instance you can simply put it into the file. If anyone thinks it should be a db setting, let me know.

The funky save button also got an update: The spinner shows with 1s delay to prevent unnecessary flickering. It says "saved" until you change any form value. Works fine so far. With another icon for the default state ("save") it doesn't jump that much.

2018-12-20 00:16 UTC, jancborchardt commented
Agree with what @skjnldsv said, some additional feedback:

- Buttons should usually go on the right, but being aligned with the fields seems good too, and the size switching will be less strange since the icon and the start of the text will always stay
- The Save button should have `class="primary"` to appear blue
- "Saving" and "Saved" states should have a capital first letter
- The placeholders of the input fields should also have a capital first letter
- For the "Website" and "Link to privacy policy" fields, the placeholder should be "https://…"
- Actually thinking about it: Shouldn’t the company/instance name, website link and privacy policy link be taken from Theming, where we already have that info? cc @juliushaertl 
- Let’s use border-bottom for the links for now. We have to do this generally in the server but this is a good start. (Please make sure to prefix it so it only changes the link styles in this specific container)

If there is no data put in for one of the parts yet, like the server location for example, that part should simply not be shown in the list.

2018-12-20 00:19 UTC, jancborchardt commented
Sorry, forgot to answer your question. For the provider icon, simply use `icon-home`:
![](https://docs.nextcloud.com/server/15/developer_manual/_images/home.png)
https://docs.nextcloud.com/server/15/developer_manual/design/icons.html

2018-12-21 19:19 UTC, weeman1337 commented
> Actually thinking about it: Shouldn’t the company/instance name, website link and privacy policy link be taken from Theming, where we already have that info?

Yes, I see some of the info is already there. Having it redundant doesn't make sense. I think "name" in theming is more the instance name. So missing is "server location", "provider name" and "admin contact". I could also add these fields to the theming section. @nextcloud/designers  ¯\\\_(ツ)\_/¯

2018-12-29 10:06 UTC, weeman1337 commented
Ping @juliushaertl - waiting for a response where to put the fields..

2019-01-08 11:00 UTC, skjnldsv commented
I think there should be a dedicated option to it. Theming is design only, nothing related to administration or mails should go there I think :)

2019-01-09 01:35 UTC, jancborchardt commented
> Theming is design only, nothing related to administration or mails should go there I think :)

That’s not true though. ;) This is the one place where you set things like the instance name, link, privacy policy & terms links etc. These are used across the app, including in emails and such. It’s good that it’s only this one place, and hence the things we need for "Who Owns Your Data" should also either be pulled from there, or if it extends it, be added there.

@weeman1337 the Unsplash app also adds a section in the Theming settings, maybe you can check that out?

2019-01-09 09:04 UTC, MariusBluem commented
„Your Data is protected by“ should be changed to „Your Files are encrypted with“ since

- encryption is only about files and not about all data (maybe we should clarify this even more)
- encrypted is more neutral than protect

2019-01-09 10:13 UTC, skjnldsv commented
> That’s not true though. ;) This is the one place where you set things like the instance name, link, privacy policy & terms links etc. These are used across the app, including in emails and such. It’s good that it’s only this one place, and hence the things we need for "Who Owns Your Data" should also either be pulled from there, or if it extends it, be added there.

Oh you're right! I forgot we added this!
Theming doesn't seems like the appropriate word now! :)
Then yes, This should go into theming I think!

2019-01-09 11:48 UTC, juliushaertl commented
Sorry, missed the notification about this one. Yes, a separate section inside of the theming settings seems suitable to me.

2019-01-09 13:51 UTC, MorrisJobke commented
> Sorry, missed the notification about this one. Yes, a separate section inside of the theming settings seems suitable to me.

Do we really want to bundle this with the theming app, because then it can't be used without the theming app?

2019-01-09 14:17 UTC, juliushaertl commented
> Do we really want to bundle this with the theming app, because then it can't be used without the theming app?

The idea was more to just use the Theming section in the settings, it should still be separate from the theming app itself.

2019-01-13 23:17 UTC, weeman1337 commented
@MariusBluem I've updated the wording:
![image](https://user-images.githubusercontent.com/6216686/51091565-5b87d680-178c-11e9-8f09-0a8cebe8ed54.png)

@juliushaertl the server info is now in the theming section. That means I made the theming section a built in one.

2019-01-20 10:36 UTC, MariusBluem commented
> @MariusBluem I've updated the wording:

Thanks 👍

What do you think about "About this server" instead of "Where is your data?"? @jancborchardt

2019-01-23 17:07 UTC, jancborchardt commented
@MariusBluem I’d say let’s do any further changes in follow-up pull requests. :) The "Where is your data?" is direct and nice.

cc @nextcloud/javascript @nextcloud/designers for review as well :slightly_smiling_face:

2019-01-28 15:50 UTC, MorrisJobke reviewed
Tested and works 👍 

The only minor part that would be nice to be fixed is that if there is nothing specified also the header should not be shown:

![bildschirmfoto 2019-01-28 um 16 45 11](https://user-images.githubusercontent.com/245432/51847828-c4d72000-231c-11e9-870e-f31ce62d764a.png)

2019-01-29 09:41 UTC, skjnldsv requested changes
See Morris's comment :)

2019-01-30 16:07 UTC, MorrisJobke approved these changes
Tested and works 👍

2019-02-05 18:14 UTC, kesselb requested changes
:sunglasses: Some code style and we're done ;-)

2019-02-05 18:14 UTC, danielkesselberg commented on settings/templates/settings/personal/partials/where-is-your-data.php
> +					'<a href="mailto:' . $_['adminMail'] . '" target="_blank" title="" rel="noreferrer noopener">',
In theory there could be an admin account without email. I guess we could ignore that for now.

2019-02-05 18:14 UTC, danielkesselberg commented on lib/private/Settings/Personal/PersonalInfo.php
> +		EncryptionManager $encryptionManager
PHPDoc missing for $encryptionManager

2019-02-06 12:04 UTC, georgehrke commented
@weeman1337 I actually developed something very similar lately, but as an independent app instead of putting it into the server.

I have to two fix some minor issues and will push it to a repository tonight. 
Maybe we can merge our efforts together? :) 

![signal-attachment-2019-01-13-213155](https://user-images.githubusercontent.com/1250540/52340191-6b9f7880-2a0f-11e9-92d2-d5d3f22b002a.jpeg)
![signal-attachment-2019-01-13-222419](https://user-images.githubusercontent.com/1250540/52340192-6b9f7880-2a0f-11e9-9d7f-537c5f2ee798.jpeg)

2019-02-06 12:21 UTC, weeman1337 commented
@georgehrke thanks for the info. So that will be the official "where is my data" app?

That would mean this PR is obsolete?

2019-02-06 12:49 UTC, MorrisJobke commented
> @georgehrke thanks for the info. So that will be the official "where is my data" app?
> 
> That would mean this PR is obsolete?

I would not say so. I would like to have this as it is in this PR. Then we can think on how to integrate both of them into one interface. The problem here was that @karlitschek was not aware of this PR and asked @georgehrke to do it in an app.

2019-02-06 22:10 UTC, karlitschek commented
Yes. It's totally my fault that I wasn't aware of the duplicate work. Sorry. Not sure what the best way is to proceed. Whatever you suggest. @MorrisJobke @weeman1337 @georgehrke

2019-02-07 13:38 UTC, MorrisJobke commented
@georgehrke @weeman1337 I would get this PR here in because it is fully working and was tested already. Also the design team had a look at it and it's approved. We then can check out how to combine or integrate it with your approach because you feature a lot more context due to the user data manifesto.

2019-02-07 13:38 UTC, MorrisJobke commented
@skjnldsv @danielkesselberg @georgehrke @rullzer Please review.

2019-02-10 09:27 UTC, weeman1337 commented on lib/private/Settings/Personal/PersonalInfo.php
> +	private function getWhereIsYourDataParams() {
✓ so for NC16 I can assume PHP >= 7.1 :)

2019-02-10 09:29 UTC, weeman1337 commented on settings/Controller/ServerInfoSettingsController.php
> +	public function storeServerInfo(
✓ so for NC16 I can assume PHP >= 7.1 :)

2019-02-10 09:53 UTC, kesselb approved these changes

2019-02-10 09:57 UTC, danielkesselberg commented on lib/private/Settings/Personal/PersonalInfo.php
> +use OCP\Encryption\IManager as EncryptionManager;
IEncryptionManager would be more clear here.

2019-02-11 10:13 UTC, MorrisJobke commented on lib/private/Settings/Personal/PersonalInfo.php
> +use OCP\Encryption\IManager as EncryptionManager;
Let's do this later as well together with the email check.

2019-02-11 10:13 UTC, merged