Create Folders when moving files
nextcloud/server pull request #13177
Opened 2018-12-20 13:57 UTC by rummatee

This Pull Request intends to solve Issue #7629 .
It adds a button to the file picker next to the breadscrumbs. When clicking on this button it opens a popup that asks for the folders name. After submitting the form, it closes the popup and reloads the file picker's content.
There is one small bug, that I couldn't fix: OC.hideMenus(); prevents the file picker from reacting to keyboard button presses until it is clicked again. So after creating a new folder the enter and escape key will only work again after the user clicked the file picker again.

Please review @MariusBluem @jancborchardt

2018-12-20 22:00 UTC, jancborchardt commented
Nice! This seems to work well, only some feedback:
- [ ] When navigating with the keyboard (via tab to switch elements and enter to "click"), pressing enter on the "New folder" button closes the dialog
- [ ] The distance of the button to the end of the breadcrumbs is a bit much. Should be the same as in the Files app
   ![screenshot from 2018-12-20 22-55-33](https://user-images.githubusercontent.com/925062/50313129-b5a5bc80-04aa-11e9-81e0-416d5a5c2ef9.png)
   ![move copy dialog](https://user-images.githubusercontent.com/925062/50313132-b63e5300-04aa-11e9-9dfc-b1c75110c9ad.png)
- [ ] When choosing a new folder name and pressing enter to confirm, the folder shows up twice or more initially (of course only exists once):
![screenshot from 2018-12-20 22-55-17](https://user-images.githubusercontent.com/925062/50313130-b63e5300-04aa-11e9-8ce1-5357b1890a3a.png)
- [ ] When you create a new folder, and then another one, the input placeholder should be reset to "New folder"

What do you think @rummatee? :)

2018-12-21 22:56 UTC, jancborchardt commented
Also @MariusBluem @fermulator for review since you were active in related issues. :)

2018-12-22 15:46 UTC, danielkesselberg commented
![image](https://user-images.githubusercontent.com/3902676/50376087-6e354280-0608-11e9-96fd-aaedb34732e2.png)

Button looks a bit off to me (Chromium 70+). Maybe related to your last changes because @jancborchardt screenshots looks ok or a local issue on my side.

2018-12-22 15:47 UTC, kesselb approved these changes
Good stuff :+1: Please align the button :sunglasses:

2018-12-23 10:34 UTC, rummatee commented
> Button looks a bit off to me (Chromium 70+). Maybe related to your last changes because @jancborchardt screenshots looks ok or a local issue on my side.

It seems to be related to Chrome. In Firefox it showed the position correctly. However my last commit should fix the position for both chrome and Firefox

2018-12-23 14:33 UTC, jancborchardt commented
@nextcloud/designers can we have another review? :)

2018-12-30 10:42 UTC, violoncelloCH commented
@rummatee Could this be rebased on current master? My dev setup instance complains that downgrading to 15.0.5 is unsupported, so I don't know how I should test this actually.

2018-12-30 15:36 UTC, violoncelloCH commented
thank you @danielkesselberg! that finally worked...

2018-12-30 15:47 UTC, violoncelloCH requested changes
otherwise it looks and works great!

2018-12-30 15:47 UTC, violoncelloCH commented on core/js/jquery.ocdialog.js
> +					if (self.enterCallback != null) {
according to the code style guideline you should use `!==` here (https://docs.nextcloud.com/server/15/developer_manual/general/codingguidelines.html#operators)

2018-12-30 15:47 UTC, violoncelloCH commented on core/js/oc-dialogs.js
> +				if (event.keyCode == 13 || event.which == 13) {
same here (https://docs.nextcloud.com/server/15/developer_manual/general/codingguidelines.html#operators)

2018-12-30 15:52 UTC, violoncelloCH commented
Also, if you create a folder in this "choose target folder" dialog, you normally want to place the file inside of this folder. So wouldn't it make sense to directly enter into the just created folder? What do you think @jancborchardt ?

2019-01-01 14:56 UTC, jancborchardt commented
> So wouldn't it make sense to directly enter into the just created folder?

Yeah, that would be a nice addition! :)

2019-01-01 16:44 UTC, danielkesselberg commented
Some tests are failing. Could you rebase this branch onto master?

2019-01-01 22:30 UTC, violoncelloCH requested changes
perfect from my view otherwise! :+1:

2019-01-02 21:57 UTC, violoncelloCH approved these changes
:+1:

2019-01-05 12:16 UTC, jancborchardt commented
What about the Drone failure here, does that need to be fixed?

2019-01-05 14:40 UTC, danielkesselberg commented
Another rebase should fix the litmus test. Not sure about the other tests. Restarted the build just in case.

2019-01-05 15:18 UTC, danielkesselberg commented
Another test fails now. I don't see how these changes are related to the failing test.

2019-01-09 01:31 UTC, jancborchardt commented
@MorrisJobke @rullzer could you check what it is about the failing tests? :man_singer:

2019-01-09 09:55 UTC, MorrisJobke commented
> @MorrisJobke @rullzer could you check what it is about the failing tests? 👨‍🎤

Those are all hiccups of our test suite 🙈 We should maybe get rid of them, because they are a major annoyance. cc @juliushaertl @danxuliu @rullzer

2019-01-09 15:58 UTC, jancborchardt commented
@rummatee please avoid force-pushing by the way as it makes it difficult to see which changes occured since the last time someone checked. :)

2019-01-09 16:00 UTC, jancborchardt commented
Ah ok, now the test runs through, that’s why you force-pushed. Sorry and nevermind! :)

2019-01-09 16:00 UTC, merged

2019-01-09 17:38 UTC, rummatee commented
> @rummatee please avoid force-pushing by the way as it makes it difficult to see which changes occured since the last time someone checked. :)

I'm supposed to rebase the pull request, right? Is there a different way to do it?

2019-01-09 17:45 UTC, MorrisJobke commented
> I'm supposed to rebase the pull request, right? Is there a different way to do it?

Typically if changes are added, then we do fixup commits and then a final rebase with `--interactive --autosquash` so that they will get squashed into one or multiple commits. That makes it usually easier. In this case if you want to get master stuff in the rebase is still fine IMO.

2019-01-10 04:12 UTC, jancborchardt commented
And @rummatee @danielkesselberg do you know about our next Contributor Week in Stuttgart, March 11–15? Contributors like you can apply for travel/accomodation support, find more info in the blog post at https://nextcloud.com/blog/the-contributor-week-is-over-time-to-plan-for-the-next-one/ :slightly_smiling_face: