[stable13] Fix loginflow with apptoken enter on iOS
nextcloud/server pull request #13374
Opened 2019-01-04 21:56 UTC by MorrisJobke

Backport of #13363

2019-01-04 21:57 UTC, blizzz approved these changes

2019-01-04 22:04 UTC, MorrisJobke commented
There was the method `getServerPath` added in 15.0.0 and back ported to stable14 in #12177 - I added it to this branch as well. After that the login works just fine. 👍

2019-01-05 09:17 UTC, rullzer approved these changes

2019-01-05 09:18 UTC, rullzer requested changes

2019-01-05 09:18 UTC, rullzer commented on core/Controller/ClientFlowLoginController.php
> +	private function getServerPath(): string {
13 also support php5. 6

2019-01-05 15:41 UTC, rullzer approved these changes
Fixed it

2019-01-05 15:41 UTC, merged