Provide initial state for backupcodes in template
nextcloud/server pull request #13481
Opened 2019-01-10 11:43 UTC by rullzer

This saves a direct request to the server when loading the backup codes.
There is no need for this as the data is already known.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2019-01-10 11:47 UTC, rullzer commented
I also bumped the dependencies and added the compiled assets to the gitattributes

2019-01-10 13:29 UTC, ChristophWurst reviewed
Just a nitpick

will test in a minute, just to see how fast it loads :)

2019-01-10 13:38 UTC, rullzer commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
right fair enough...

2019-01-10 19:07 UTC, rullzer commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
fixed

2019-01-13 10:09 UTC, skjnldsv commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
Why use atob?

2019-01-13 18:34 UTC, rullzer commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
Because it is base64 encoded. Else we might run into some random errors with quotes

2019-01-13 18:52 UTC, skjnldsv commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
We use json_encode directly for settings :)
https://github.com/nextcloud/server/blob/master/settings/templates/settings-vue.php#L30

2019-01-13 18:57 UTC, rullzer commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
still feels more error prone. base64 is guaranteed not to contain special chars that might break things

2019-01-13 19:09 UTC, skjnldsv commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = JSON.parse(atob(document.getElementById('twofactor-backupcodes-initial-state').value));
You're right! Let's add this to https://github.com/nextcloud/server/issues/13488

2019-01-14 06:46 UTC, rullzer commented
@skjnldsv can I also get a :+1:  :wink:

2019-01-14 07:44 UTC, ChristophWurst approved these changes
Looks good and works nicely :+1:

2019-01-14 16:57 UTC, juliusknorr requested changes

2019-01-14 16:57 UTC, juliushaertl commented on apps/twofactor_backupcodes/src/views/PersonalSettings.vue
> +	import { mapGetters } from 'vuex'
mapGetters is not used. However you could just use mapState, so you don't need to add all those computed values manually

2019-01-14 17:11 UTC, rullzer commented on apps/twofactor_backupcodes/src/views/PersonalSettings.vue
> +	import { mapGetters } from 'vuex'
Right. That was my plan but it broke hard for me. If you can make it work please do

2019-01-15 19:50 UTC, rullzer commented on apps/twofactor_backupcodes/src/views/PersonalSettings.vue
> +	import { mapGetters } from 'vuex'
fixed

2019-01-16 07:43 UTC, juliusknorr approved these changes

2019-01-16 07:52 UTC, merged