Publish event for app token create/update/delete
nextcloud/server pull request #13548
Opened 2019-01-12 16:53 UTC by danielkesselberg

2019-01-12 18:09 UTC, danielkesselberg commented
https://github.com/nextcloud/server/pull/13548/commits/8aab4601b2bc2b4441500ee9d240dc6ccc4e93b4 no typehint vs `?string` what do you prefer? With `string` these test fails https://github.com/nextcloud/server/blob/720ef48d9283b53356cfadfb56adda13bfa96e64/tests/Settings/ApplicationTest.php#L72

2019-01-14 09:01 UTC, ChristophWurst requested changes
Code looks good! I like this enhancement!

2019-01-14 09:01 UTC, ChristophWurst commented on settings/Controller/AuthSettingsController.php
> +			$this->logger->logException($e, ['app' => 'settings']);
I think the app context might not be necessary. @rullzer do we inject an app logger for settings as well?

2019-01-14 09:02 UTC, ChristophWurst commented
> [8aab460](https://github.com/nextcloud/server/commit/8aab4601b2bc2b4441500ee9d240dc6ccc4e93b4) no typehint vs `?string` what do you prefer? With `string` these test fails

I like `?string` :)

2019-01-14 09:15 UTC, rullzer commented on settings/Controller/AuthSettingsController.php
> +			$this->logger->logException($e, ['app' => 'settings']);
try it ;) I think so

2019-01-14 14:58 UTC, nickvergessen commented on settings/Controller/AuthSettingsController.php
> +			->setType('security')
mind also setting the object data?
`->setObject('app_token', $id)`

In the future we can then jump to activity done on the same object.

2019-01-14 14:58 UTC, nickvergessen commented on settings/Controller/AuthSettingsController.php
> +			->setSubject($subject);
Would it make sense to include the name into the message, so you can see which token was created and maybe delete it more easily?

2019-01-14 14:58 UTC, nickvergessen commented
This was also on my todo list, but thanks for picking it up!

2019-01-21 08:54 UTC, nickvergessen commented on settings/Controller/AuthSettingsController.php
> +			->setSubject($subject);
I prefer the additional query :)
So you know what was deleted

2019-01-21 10:37 UTC, ChristophWurst approved these changes
Tests could be improved, but looks good :+1:

2019-01-21 10:37 UTC, ChristophWurst commented on tests/Settings/Controller/AuthSettingsControllerTest.php
> +		$activityManager->method('generateEvent')
It would be good if the calls on the activity manager are asserted where actually expected -> in the test relevant cases :wink:

2019-01-22 17:18 UTC, danielkesselberg commented on settings/Controller/AuthSettingsController.php
> +		$token = $this->tokenProvider->getTokenById((string)$id);
@rullzer I'm a bit confused about `(string)$id`. Do you remember why you did it that way?

2019-01-22 17:19 UTC, danielkesselberg commented on tests/Settings/Controller/AuthSettingsControllerTest.php
> +		$activityManager->method('generateEvent')
Have a look ;-)

2019-01-30 13:53 UTC, danielkesselberg commented on settings/Controller/AuthSettingsController.php
> +		$token = $this->tokenProvider->getTokenById((string)$id);
Hmm. Looked at that again. There is no typehint for the route right no so basically $id could be anything but [getTokenById](https://github.com/nextcloud/server/blob/674930da7ff0a9bc82425caaf877efe6bae3bbde/lib/private/Authentication/Token/IProvider.php#L74) is typed. I guess this only works because `AuthSettingsController` is not strict yet so `23` is casted to `"23"` before passing to `getTokenById` where `"23"` is casted to `23` again.

2019-01-30 13:56 UTC, danielkesselberg commented on settings/Controller/AuthSettingsController.php
> +		$token = $this->tokenProvider->getTokenById((string)$id);
![image](https://user-images.githubusercontent.com/3902676/51985803-13142c80-249f-11e9-886f-d25fe6243d2f.png)

Does not work if `declare(strict_types=1)`. Let me remove `(string)` and hope that it does not :boom:

2019-01-30 20:44 UTC, danielkesselberg commented
Ready for another review ;-)

2019-01-31 09:27 UTC, ChristophWurst approved these changes

2019-02-01 12:19 UTC, nickvergessen approved these changes
Added rich subject and made the thing strict

2019-02-01 13:56 UTC, merged

2019-02-01 14:56 UTC, danielkesselberg commented on settings/Activity/Provider.php
> +					'token' => [
Cool :+1: I didn't understand how that works :see_no_evil: If there is no definition use [highlight](https://github.com/nextcloud/server/blob/422dd9dfd68bf678801a6ff1a1476d54d668df8f/lib/public/RichObjectStrings/Definitions.php#L259) :tada:

2019-02-01 14:58 UTC, nickvergessen commented on settings/Activity/Provider.php
> +					'token' => [
yeah, but only if it shouldnt have a definition. Tokens are nothing that has a page or something like that, so highlight is good enough.