Use flexbox on app page
nextcloud/server pull request #1355
Opened 2016-09-10 12:38 UTC by rullzer

The amount of white space on the app page was annoying me. So I decided to give flexbox a try.

Before:
![before](https://cloud.githubusercontent.com/assets/45821/18410392/280bfba0-7762-11e6-8551-f3a4f77f32ce.png)

After:
![after](https://cloud.githubusercontent.com/assets/45821/18410395/2d03e4ec-7762-11e6-8773-c9c098894086.png)

Which looks a lot better to me.

However it does need work as you can see on the notenabled page:
![not_enabled](https://cloud.githubusercontent.com/assets/45821/18410461/ead5e9a6-7763-11e6-851b-f97a03c60c4e.png)

Far from done.

- [ ] Experimental apps display
- [ ] Fix per app layout a bit more

CC: @nextcloud/designers @MorrisJobke

2016-09-10 14:05 UTC, raghunayyar commented
Personally, I find it a bit too noisy now since the left ones have the heading on the left and the centre ones have the heading below the image. There is no visual consistency here. May be you want to use two of them instead of the three and make sure the image comes on the left and the content on the right.

2016-09-10 14:06 UTC, raghunayyar commented
Aaah, I missed the second image. Never mind. :P

2016-09-10 14:11 UTC, tcitworld commented
I think margin for only two columns would be fine.

2016-09-10 15:07 UTC, eppfel commented
I like the idea, but it could really be a bit too "noisy". The styling of the per app layout is not so easy, because these are inline-box elements right now.
Experimental apps are separated now:
<img width="1482" alt="bildschirmfoto 2016-09-10 um 17 06 16" src="https://cloud.githubusercontent.com/assets/1899308/18411511/fdb81d22-7778-11e6-9019-e6257091a3d4.png">
<img width="1152" alt="bildschirmfoto 2016-09-10 um 17 06 30" src="https://cloud.githubusercontent.com/assets/1899308/18411512/020b49a8-7779-11e6-8639-36453c183d88.png">

2016-09-10 18:18 UTC, rullzer commented
Thanks for the feedback. I just wanted to get things started. As I have the artistic insight of a table I'll happily hand this over :) I just found that the current design had way to much wasted space.

@eppfel thnx!

2016-09-11 10:08 UTC, eppfel commented
My try in making it less noisy:
<img width="2560" alt="bildschirmfoto 2016-09-11 um 11 49 33" src="https://cloud.githubusercontent.com/assets/1899308/18416556/2350fff0-7818-11e6-8497-4f5e2534dbe7.png">
<img width="1406" alt="bildschirmfoto 2016-09-11 um 11 51 57" src="https://cloud.githubusercontent.com/assets/1899308/18416557/28ae7914-7818-11e6-9992-07bfa32272d3.png">

I think the elements of each app have to be rearranged for a proper overall look. Maybe we have to take the design of the app store into account as well: https://apps.nextcloud.com/

2016-09-11 20:08 UTC, jancborchardt commented
@eppfel looks awesome! (Did I ask you already if you’re going to come to the [Nextcloud conference](https://conf.nextcloud.com)?) ;)

2016-09-12 10:47 UTC, eppfel commented
@jancborchardt You did and I will 😉

2016-10-18 09:48 UTC, jancborchardt commented
@eppfel @rullzer is a first version of this ready for getting in, or where do you need help? We should merge it to master soon so we can see how it works and polish it for Nextcloud 11. :)

2016-10-18 10:58 UTC, MorrisJobke requested changes

2016-10-18 10:58 UTC, MorrisJobke commented on settings/css/settings.css
> +    border-style: solid;
Tabs vs spaces ;)

2016-10-18 11:34 UTC, eppfel commented
@jancborchardt It needs to be fixed, because right now it affects the personal settings page as well. Besides that, the flexing seems robust, but the current version still has borders and I would like to get another opinion on that besides yours ;) Maybe there is time during the meetup, but otherwise the week is packed tight.

2016-10-18 11:39 UTC, eppfel commented on settings/css/settings.css
> +    border-style: solid;
sry, fixed

2016-10-18 15:44 UTC, MorrisJobke commented
@eppfel Ready to review? Then change the label ;)

2016-10-18 15:49 UTC, MorrisJobke submitted a review, later dismissed

2016-10-18 15:49 UTC, eppfel commented
@MorrisJobke Not, yet. I just fixed the spaces with an evil force push. But pssst :speak_no_evil: don't tell anyone

2016-10-18 18:51 UTC, jancborchardt commented
@MorrisJobke do you have any take on grid lines vs no grid lines? As @eppfel asked above ;)

2016-10-18 19:55 UTC, MorrisJobke commented
> @MorrisJobke do you have any take on grid lines vs no grid lines? As @eppfel asked above ;)

I would either go with a higher padding of 40px and no grid lines or leave the grid lines and 30px padding. The higher padding is needed to compensate for the missing visual guidelines. Generally speaking I like the no-gridlines version more, because we only have the line for the sidebar and horizontal lines in the files app for example, but never used vertical grid lines.

2016-10-23 13:37 UTC, jancborchardt commented
@eppfel you wanna try out the higher padding? Then let’s get this in and refine later. I’d hate to have this great improvement laying around for too long. ;)

2016-10-24 07:55 UTC, eppfel commented
Jep. I'll try that out. Was just a crazy last week, no time at all.

2016-10-25 16:08 UTC, eppfel commented
I only used the padding-right, but 50px, because this side has no sharp edge. Works for me, but I will open another issue for organizing the elements of each app.
I squashed my commits, so ready for gogo!

2016-10-26 07:19 UTC, LukasReschke commented
LGTM

2016-10-26 08:27 UTC, MorrisJobke commented
Tested and works 👍 

Tested in Firefox, Chrome, Safari, IE11 and Edge

2016-10-26 08:28 UTC, merged

2016-10-27 22:56 UTC, jancborchardt commented
Awesome work @eppfel! :) :rocket: