Improve the upload progress bar layout
nextcloud/server pull request #13567
Opened 2019-01-14 00:36 UTC by weeman1337

The upload progress bar looked kind of ? unfinished to me:  
![upload-before](https://user-images.githubusercontent.com/6216686/51092838-6480a400-179c-11e9-9433-18581b046d0e.png)

Everything now has the cool round layout. So I updated the progress bar to match that:  
![upload-after](https://user-images.githubusercontent.com/6216686/51092853-94c84280-179c-11e9-90bc-03336795076e.png)

@nextcloud/designers

2019-01-14 17:01 UTC, juliushaertl commented
Looks really nice @weeman1337 :tada: 

Some nitpicking since you are on it already :wink: 

There seems to be a duplicate border between the progress bar and the cancel button. We should merge those.
![image](https://user-images.githubusercontent.com/3404133/51127616-2fb92f00-1826-11e9-8c66-5afb9bb4cd46.png)

The text inside the progress bar should be properly centered vertically
![image](https://user-images.githubusercontent.com/3404133/51127675-5aa38300-1826-11e9-9475-9072e21d4e14.png)

2019-01-14 18:32 UTC, juliusknorr requested changes
See comment :wink:

2019-01-21 09:38 UTC, juliusknorr approved these changes

2019-01-21 12:25 UTC, skjnldsv approved these changes

2019-01-21 12:54 UTC, merged

2019-01-22 08:18 UTC, jancborchardt commented
@weeman1337 since you're now a progress bar pro, do you want to try updating the design to the mockup? :) I can help too if you need anything.

2019-02-13 16:21 UTC, jancborchardt commented
@weeman1337 cool, thank you! :) Created a separate issue at https://github.com/nextcloud/server/issues/14181 so we can track it there.

2019-03-08 01:39 UTC, BloodyIron commented
IMO we need MUCH more info than what we get now, and than the quota bar.

Here's an example alternative tool that not only makes the process "faster" at parts, gives much more feedback about upload progress. Furthermore, it parallelizes the upload process, which is something nextCloud SORELY needs for both the web interface, and sync!