Allow apps to regsiter an initial state
nextcloud/server pull request #13646
Opened 2019-01-17 11:57 UTC by rullzer

Fixes #13488 

This introduces a way for apps to register their initial state so this does not have to be fetched async.

Todo:
- [ ] Clean OCP javascript API to obtain your data
- [ ] Tests for the service

2019-01-18 12:37 UTC, MorrisJobke commented on core/templates/layout.user.php
> +		<?php }?>
Limitation of this is that it only works for logged in pages. I would just add it to every page if there is some initial state.

2019-01-25 12:46 UTC, ChristophWurst requested changes

2019-01-25 12:46 UTC, ChristophWurst commented on apps/twofactor_backupcodes/src/settings.js
> +const initialStateElem = document.getElementById('initial-state-twofactor_backupcodes');
I guess you want to change that to the fancy new API ;)

2019-01-25 12:46 UTC, ChristophWurst commented on core/src/OCP/initialstate.js
> +			return {};
I would prefer to have a `console.warn` here

2019-01-25 12:46 UTC, ChristophWurst commented on core/src/OCP/initialstate.js
> +			console.log('Could not parse initial state of ' + app);
make that a `console.error` and `throw new Error('...')` afterwards, then apps can react to it and do a fallback

2019-01-29 12:21 UTC, rullzer commented
@MorrisJobke @ChristophWurst comments address. Will rebase and squash with the green light ;)

2019-01-29 12:31 UTC, ChristophWurst approved these changes
Looks great!

2019-01-29 13:29 UTC, MorrisJobke approved these changes
Beside my comment this looks good 👍

2019-01-29 14:15 UTC, rullzer commented on lib/private/InitialStateService.php
> +		$this->logger->warning('Invalid data provided to provideInitialState');
Done

2019-01-30 07:36 UTC, merged

2019-01-30 09:57 UTC, skjnldsv reviewed
You'll add tests later? (looking at the OP) :wink: