don't allow enforcing 2FA when no provider is enabled
nextcloud/server pull request #13735
Opened 2019-01-22 13:51 UTC by rummatee

Fixes issue #12267
I decided to pass a complete list of enabled 2FA providers to the template, so that if we decide to do something with this information (for example show a list of the names) this is now easy to change.

2019-01-24 11:21 UTC, blizzz commented
thanks for the PR, I think it makes sense. Please also adjust and extend the failing tests.

2019-01-25 12:53 UTC, ChristophWurst requested changes
:)

2019-01-25 12:53 UTC, ChristophWurst commented on settings/templates/settings/admin/security.php
> +	<?php unset($_['twoFactorProviderData']['backup_codes']); if (!empty($_['twoFactorProviderData'])) { ?>
Please see the original ticket. We must not hide the full UI, but just add a warning ;) There are use cases where enforcing 2FA with user that don't have it *yet* is still desirable, for example when they get enrolled afterwards.

2019-01-25 12:53 UTC, ChristophWurst commented on lib/private/Authentication/TwoFactorAuth/ProviderLoader.php
> +			if (isset($info['two-factor-providers'])) {
this should be cleaned up a bit as it duplicates a lot of the logic from the other method (I can help you with that)

2019-01-26 13:03 UTC, rummatee commented on settings/src/components/AdminTwoFactor.vue
> +				saveChanges();
I don't actually understand why it makes sense to save the changes immediately, but since this was the behavior before, I left it this way.

2019-02-06 10:26 UTC, rummatee commented
So, does this new approach, that works with the .vue files rather than with the php templates solve your objections about the code duplication and about warning the admin instead of disabling? @ChristophWurst 
I don't really have a lot of experience with vue. The readme said to commit the compiled files as well so I did, but I see that (of course) they lead to a lot of conflicts. Should I do something about that?

2019-02-13 14:22 UTC, ChristophWurst commented
> I don't really have a lot of experience with vue. The readme said to commit the compiled files as well so I did, but I see that (of course) they lead to a lot of conflicts. Should I do something about that?

There are conflicts because the webpack bundle has been touched by other PRs as well. You can resolve this by rebasing the branch onto the latest master. When you see conflicts in one of the files above don't try to manually resolve them but just rebuild the js :wink:

2019-03-01 09:25 UTC, ChristophWurst commented
I will try to tackle this for Nextcloud 17. We should do more accurate queries whether providers are enabled in general and in the case of the admin. This needs a bit of work.

2019-03-24 20:44 UTC, rummatee commented
Sorry for the late reply, I had university exams.

I am not completely sure if I understand your comment correctly.
So you want to have 2 different warnings:
One warning if no app is enabled that provides a method for 2FA, because then nobody can log in anymore.
And a different if there are apps enabled that provide 2FA, but the admin didn't set up a mothod for themself, because in this case the admin could not log in anymore.
Is that correct?

I think the second case would be issue  #12269 rather than #12267 and I think that it would be also solved by allowing to set up 2FA on login as described in issue #12268. However I can also work on providing 2 different warnings.

2019-03-25 07:21 UTC, ChristophWurst commented on settings/src/components/AdminTwoFactor.vue
> +				saveChanges();
FYI this has changed in the meantime. Saving is now explicit.

2019-03-25 07:23 UTC, ChristophWurst commented
> Is that correct?

Yes, that is correct.

Yes, for users it will be possible to set up 2FA on login in the future. But when admins enforce it, I would prefer to already warn them on enforcing if they haven't set up a provider. It sounds a bit too scary for me to hope the admin will successfully set it up afterwards. I would rather have that ensured beforehand.

2019-03-31 18:05 UTC, rummatee commented
Sorry, I didn't mean to put all these commits from master in here. How did that happen?

In any case, now it should show different warnings in the case of no provider enabled at all and no provider enabled for the admin.

- [ ] Layout for the warnings

2019-07-18 19:23 UTC, MorrisJobke commented
Rebased and resolved the issues here in #16463

2019-07-18 19:23 UTC, closed without merging