Move calendar settings into basic settings
nextcloud/server pull request #13796
Opened 2019-01-24 14:45 UTC by jancborchardt

Currently the "Groupware" settings section only has Calendar settings. This doesn’t make a lot of sense. And the sentence below the checkbox says it all:

> Please make sure to properly set up the email settings **above.**

Fixed by moving it to basic settings, and improved the spacing (Also fixes background jobs):
![calendar settings basic settings](https://user-images.githubusercontent.com/925062/51685620-f5524d80-1fee-11e9-8ee4-77fcdd60b919.png)

Please review @nextcloud/designers @karlitschek

2019-01-24 14:47 UTC, georgehrke commented
:-1:

https://github.com/nextcloud/server/pull/13765 Is gonna add more settings to group ware

2019-01-24 14:56 UTC, georgehrke commented
On top of that, apps that implement custom Room / Resource backends for calendar scheduling are also supposed to put their UI into the groupware category :)

2019-01-24 14:59 UTC, juliushaertl commented
Circles was also in there iirc.

2019-01-24 15:06 UTC, jancborchardt commented
@georgehrke @juliushaertl alright, good stuff then! :) Will remove the moving of the Calendar server from my pull request. Still modifying some more stuff. :)

2019-01-24 15:17 UTC, jancborchardt commented
Alright, moved it back, but now I need some help – @georgehrke?

- [ ] The docs page at https://docs.nextcloud.com/server/latest/user_manual/pim/calendar.html is empty. This is also where the first run wizard links to. There should really be some content on there and it seems to have been empty for long? cc @jospoortvliet 
- [ ] I doubt I linked the other settings sections correctly. ;) The apps/organization/calendar link, and the email settings link would need to be checked.

2019-01-24 15:18 UTC, karlitschek commented
:+1:

2019-01-24 15:37 UTC, georgehrke commented
> The docs page at https://docs.nextcloud.com/server/latest/user_manual/pim/calendar.html is empty. This is also where the first run wizard links to. There should really be some content on there and it seems to have been empty for long?

It's the correct link, but the documentation is just missing. @MariusBluem What's the status on the calendar doc?

2019-01-24 16:17 UTC, georgehrke commented
@jancborchardt Done

2019-01-24 18:21 UTC, jancborchardt commented
Awesome, thanks a lot @georgehrke!

Please review @nextcloud/calendar @nextcloud/designers :rocket:

2019-01-24 18:22 UTC, jancborchardt commented on apps/dav/templates/settings-admin-caldav.php
> +					'{emailopen}',
@georgehrke guess this is supposed to be called "linkopen"? Not sure :D

2019-01-25 11:44 UTC, skjnldsv requested changes

2019-01-25 11:44 UTC, skjnldsv commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
Please use `p` and use the l10n sprintf method:
```php
p($l->t('%s of %s used', [$_['usage'], $_['total_space']]));
```

2019-01-25 11:46 UTC, georgehrke commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
`p()` will escape `<a href="../admin#mail_general_settings">`

2019-01-25 11:47 UTC, skjnldsv commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
ah yes, then just the translation ;)

2019-01-25 11:48 UTC, georgehrke commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
but p will print the text and once it's printed i can't replace `{emailopen}` or `{linkclose}` 😉

2019-01-25 13:03 UTC, skjnldsv commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
```php
print_unescaped($l->t(
    'Please make sure to properly set up %sthe email server↗%s.',
    '<a href="../admin#mail_general_settings">',
    '</a>'
));
```

And I can see ` %sthe` causing issues.
I don't know, the str_replace seemed weird to me :)

2019-01-25 13:21 UTC, danielkesselberg commented on apps/dav/templates/settings-admin-caldav.php
> +			<?php print_unescaped(str_replace(
I throw `<?php p($l->t('Please make sure to properly set up')) ?> <a href="../admin#mail_general_settings"><?php p($l->t('the email server ↗')) ?></a>` in the ring :rofl:

2019-01-25 16:58 UTC, jancborchardt commented on apps/dav/templates/settings-admin-caldav.php
> +				$l->t('Please make sure to properly set up {emailopen}the email server↗{linkclose}.')
Actually that should not be here at all since it’s only used for external links. :)

If we have a verdict on the syntax of the link / translation combination, then it can be fixed in one go.

2019-01-27 11:36 UTC, tcitworld commented on apps/dav/templates/settings-admin-caldav.php
> +	<a target="_blank" href="<?php p(link_to_docs('user-sync-calendars')) ?>" rel="noreferrer noopener">connect your desktop & mobile for syncing</a>.</p>
Shouldn't these be translated as well ?

2019-01-27 18:39 UTC, MariusBluem commented
@georgehrke Same as I‘ve done with the CalDAV/CarDAV sync docs, I will create a PR with the Basic stuff which can be improved later ... End of this week :)

2019-01-27 18:50 UTC, georgehrke commented
I made the text @jancborchardt added translatable, added a ↗ to the link to the docs and removed the  ↗ from the link to the mail settings.

2019-01-30 16:53 UTC, georgehrke commented
@jancborchardt @skjnldsv @MariusBluem Please check again :)

2019-01-31 21:20 UTC, skjnldsv approved these changes

2019-02-01 09:03 UTC, juliusknorr approved these changes

2019-02-01 12:00 UTC, merged