add file type aac
nextcloud/server pull request #13851
Opened 2019-01-27 13:53 UTC by duybq86

add file type aac

2019-01-27 15:50 UTC, kesselb requested changes
Thank you for your contribution :tada:

2019-01-27 15:50 UTC, danielkesselberg commented on resources/config/mimetypemapping.dist.json
> +	"aac": [""audio/aac""],
There are to many double quotes. 

`"aac": ["audio/aac"],`

2019-03-01 08:59 UTC, ChristophWurst commented
Any update @duybq86? Did you delete your fork, btw?

2019-03-20 10:01 UTC, MorrisJobke commented
Due to deleted fork I will close this PR for now. We are happy to help once this is needed again.

2019-03-20 10:01 UTC, closed without merging