Expose subadmin to OCP
nextcloud/server pull request #13880
Opened 2019-01-29 09:39 UTC by rullzer

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2019-01-29 09:44 UTC, ChristophWurst requested changes
Thanks!

2019-01-29 09:44 UTC, ChristophWurst commented on lib/public/Group/ISubAdmin.php
> +	 * @return bool
what does the returned value mean? Please document

2019-01-29 09:44 UTC, ChristophWurst commented on lib/public/Group/ISubAdmin.php
> +	 * @return bool
same

2019-01-29 09:45 UTC, rullzer commented on lib/public/Group/ISubAdmin.php
> +	 * @return bool
Nothing it seems :P always true...

2019-01-29 10:40 UTC, ChristophWurst approved these changes
Awesome!

2019-01-29 12:12 UTC, nickvergessen commented on lib/public/Group/ISubAdmin.php
> +	public function getAllSubAdmins(): array;
not sure this one should be exposed, the result could be very big anyway

2019-01-29 12:13 UTC, nickvergessen approved these changes

2019-01-29 13:16 UTC, ChristophWurst commented on lib/public/Group/ISubAdmin.php
> +	public function getAllSubAdmins(): array;
Nope. I just need the one where I can ask if user A is subadmin of user B.

2019-01-29 14:34 UTC, MorrisJobke approved these changes

2019-01-29 21:13 UTC, merged

2019-05-21 13:48 UTC, leonklingele-work commented on lib/private/SubAdmin.php
> -		return true;
This breaks API compatibility :(

2019-05-21 15:20 UTC, MorrisJobke commented on lib/private/SubAdmin.php
> -		return true;
As it is private namespace that is totally fine. We state that only the public API is kept stable.