Retrieving contacts/users from database to dropdown menu who shared w…
nextcloud/server pull request #14129
Opened 2019-02-09 16:13 UTC by sananirajabov

The problem is when you click users dropdown menu, first 25 users appear, to fix this problem I implemented code when you share something with user, this user then appear in dropdown menu, and there is no limit how many users will appear.

Signed-off-by: Sanani Rajabov [sananirajabov@gmail.com](mailto:sananirajabov@gmail.com)
Signed-off-by: sananirajabov <sananirajabov@gmail.com>

2019-02-20 07:56 UTC, sualko requested changes
Your pull request is not solving the original issue and prevents user form searching all users.

2019-02-20 07:56 UTC, sualko commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			for ($i = 0; $i < count($allContacts); $i++) {
That's a pretty bad performance hit. If you have thousands of users this is not acceptable.

2019-02-20 07:56 UTC, sualko commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedWith = $conn->executeQuery('SELECT DISTINCT * FROM oc_share');
The whole contact filtering stuff, should probably be moved to the contactsManager.

2019-02-20 07:56 UTC, sualko commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedContacts = [];
Your code is now filtering every contact search, but I think the problem of #5097 was the initial contact menu view, which means without search string.

2019-02-20 07:56 UTC, sualko commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +				if ($row['share_with'] == $allContacts[$i]['UID']) {
This is not what your comment above is promising.

> Matching who shared with current user

2019-03-02 14:42 UTC, sananirajabov commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +				if ($row['share_with'] == $allContacts[$i]['UID']) {
Thanks for analyzing my code and write feedback. I will try to fix these issues you mentioned.

2019-03-29 14:21 UTC, closed without merging