Move files_trashbin to webpack
nextcloud/server pull request #14141
Opened 2019-02-11 10:30 UTC by rullzer

Combine the 2 js files and the scss. This saves compiling the scss on
the go. And going via Nextcloud storage to obtain it.

So 3 requests to 1. And this 1 request can be totally handled by the webserver. No need for NC to do anything :smile:

2019-02-11 10:35 UTC, MorrisJobke commented on apps/files_trashbin/js/files_trashbin.js
> +//# sourceMappingURL=files_trashbin.js.map
Don't forget to add those files to the `.l10nignore`. cc @ChristophWurst as well.

2019-02-11 11:45 UTC, MorrisJobke commented on apps/files_trashbin/.l10nignore
> +js/files_trashbin.js.map
`.map` files aren't scanned anyways ;)

2019-02-11 12:43 UTC, ChristophWurst commented
So … do we want webpack configs for all the apps in this repo or will we just add entry points to the core webpack config? :thinking:

2019-02-11 12:46 UTC, rullzer commented
> So … do we want webpack configs for all the apps in this repo or will we just add entry points to the core webpack config? thinking

Core webpack would be better.

2019-02-12 14:01 UTC, skjnldsv requested changes

2019-02-12 14:01 UTC, skjnldsv commented on apps/files_trashbin/src/webpack.dev.js
> +  devServer: {
unneeded, we don't use the devserver

2019-02-12 15:11 UTC, rullzer commented on apps/files_trashbin/src/webpack.dev.js
> +  devServer: {
I just copied that from somewhere I think :)

2019-02-13 07:55 UTC, skjnldsv commented on apps/files_trashbin/src/webpack.dev.js
> +  devServer: {
Yes, it's all over the place X)
But this is a reliquat from the default webpack config we don't need here :(

2019-02-13 08:46 UTC, rullzer commented
So moved to the single webpack config...

2019-02-13 08:48 UTC, rullzer commented on apps/files_trashbin/src/webpack.dev.js
> +  devServer: {
Resolved by moving to the main webpack config :wink:

2019-02-13 08:48 UTC, ChristophWurst approved these changes

2019-02-13 09:30 UTC, juliusknorr approved these changes

2019-02-13 09:30 UTC, juliushaertl commented
Failure seems unrelated https://drone.nextcloud.com/nextcloud/server/15780/260

2019-02-13 10:34 UTC, merged