Add DB table to extend filecache with metadata etag
nextcloud/server pull request #14228
Opened 2019-02-15 13:04 UTC by MorrisJobke

For #8477

Now the big question is: should we try to add more columns to this new table. The idea was to add some generic columns for strings, integer, bools, etc that are by default are just empty and can be used in the future then? The problem we want to solve with this is that the filecache is a big table that is not easily extendable on all possible DBs without a major downtime due to the size of the table. This is especially the case for MySQL/MariaDB where an added column results in the table being created from scratch and then is copied over and thus causing quite some downtime.

cc @rullzer @icewind1991 @karlitschek @nickvergessen @blizzz @kesselb @ChristophWurst

2019-02-15 14:09 UTC, karlitschek commented
I think it would be clever to add a few 'spare' columns. It will basically be impossible to change this table in the future once it has millions of rows. So I think this is a good idea.

2019-02-15 14:13 UTC, nickvergessen commented
We had a few columns to add already. ctime/utime/mtime need to be covered, we only got 1or2 so far.

The question with empty columns is of course, do we need more int or strings?

2019-02-15 14:50 UTC, MorrisJobke commented
> The question with empty columns is of course, do we need more int or strings?

Another one: what size should they have, because there are multiple sizes on the int side as well as a multitude on the string side as well. Just adding "string columns"  isn't that easy because it has given implications on the performance (how easy it is to add indexes, or if this is possible at all, etc).





> We had a few columns to add already. ctime/utime/mtime need to be covered, we only got 1or2 so far.

Good ones 👍 I would then add a creation time and an upload time column as well, right?

2019-02-15 14:53 UTC, MorrisJobke commented
Any other columns? Something like the visibility due to background scans or background processing? (I just have the antivirus app in mind for example)

2019-02-18 07:18 UTC, MorrisJobke commented
> The problem we want to solve with this is that the filecache is a big table that is not easily extendable on all possible DBs without a major downtime due to the size of the table. This is especially the case for MySQL/MariaDB where an added column results in the table being created from scratch and then is copied over and thus causing quite some downtime.

There is also a tool to migrate it on a live system: https://www.percona.com/doc/percona-toolkit/2.1/pt-online-schema-change.html (problem: it's a tool that needs manual work)

2019-02-20 15:03 UTC, MorrisJobke commented
I added creation and upload time as `datetime` columns.

2019-02-20 15:04 UTC, MorrisJobke commented
Anything else?

2019-02-20 15:10 UTC, rullzer commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addColumn('creation_time', 'datetime', [
Can we please have indexes on this column

2019-02-20 15:10 UTC, rullzer commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addColumn('upload_time', 'datetime', [
This one as wel

2019-02-20 15:59 UTC, MorrisJobke commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addColumn('creation_time', 'datetime', [
Done.

2019-02-26 08:01 UTC, nickvergessen requested changes

2019-02-26 08:01 UTC, nickvergessen commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addUniqueIndex(['fileid']);
Please add a name: https://github.com/nextcloud/server/pull/14025#issuecomment-467335903

2019-02-26 08:01 UTC, nickvergessen commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addIndex(['creation_time']);
Please add a name: https://github.com/nextcloud/server/pull/14025#issuecomment-467335903

2019-02-26 08:01 UTC, nickvergessen commented on core/Migrations/Version16000Date20190215125511.php
> +			$table->addIndex(['upload_time']);
Please add a name: https://github.com/nextcloud/server/pull/14025#issuecomment-467335903

2019-02-26 08:23 UTC, MorrisJobke commented
Added the index names 👍

2019-02-27 13:18 UTC, MorrisJobke commented
Ready for review 👍

2019-02-27 14:07 UTC, blizzz commented
will timestamps (mtime in filecache) and the datetimes here will be comparable? since the timestamp does not carry timezone information. i think @nickvergessen dived into this somewhat deeper some time ago?

2019-02-27 14:42 UTC, MorrisJobke commented
> will timestamps (mtime in filecache) and the datetimes here will be comparable? since the timestamp does not carry timezone information. i think @nickvergessen dived into this somewhat deeper some time ago?

timestamps are by definition UTC, right? Thus it should be no problem.

2019-02-27 15:47 UTC, blizzz commented
@MorrisJobke I am mistaken. DateTime does not carry time zone information, but as long as data is provided in UTC it'll be fine.

2019-02-27 15:48 UTC, blizzz approved these changes

2019-03-01 12:14 UTC, icewind1991 commented
since we use timestamps (int) for storing time in the filecache I would prefer to also use that here

2019-03-01 15:56 UTC, MorrisJobke commented
> since we use timestamps (int) for storing time in the filecache I would prefer to also use that here

This was proposed by @nickvergessen to improve handling of this in the future. I don’t have any specific preference for one or the other.

What do the others prefer?

2019-03-05 10:20 UTC, MorrisJobke commented
> since we use timestamps (int) for storing time in the filecache I would prefer to also use that here

Changed.

2019-03-05 12:48 UTC, rullzer approved these changes

2019-03-06 09:16 UTC, MorrisJobke commented
Big question now: Should we merge this? because the whole logic to properly provide the metadata etag is quite some work and the propagation that is done for the normal etag needs to be replicated to the sharing backend. That's most likely nothing we can accomplish in the remain days.

I would vote for moving this to 17. Sorry for the delay here.

2019-05-14 08:59 UTC, MorrisJobke commented
> Big question now: Should we merge this? because the whole logic to properly provide the metadata etag is quite some work and the propagation that is done for the normal etag needs to be replicated to the sharing backend. That's most likely nothing we can accomplish in the remain days.
> 
> I would vote for moving this to 17. Sorry for the delay here.

I updated this PR and we are now fine with merging this. Once in we can focus on the actual code for the usage of those columns.

2019-07-15 14:59 UTC, MorrisJobke commented
Rebased. Once done I will merge this.

2019-07-15 19:37 UTC, merged

2019-07-16 05:18 UTC, tobiasKaminsky commented
woho :tada: 
Will the other parts also be part of NC17, like metadata etag?

2019-07-16 07:50 UTC, MorrisJobke commented
For now it’s only the table columns. No code was added yet.

2019-07-16 07:50 UTC, MorrisJobke commented
Most likely not, because the propagation code needs to be added for the metadata stuff.