Publish activity if app password created by ocs api or client login flow
nextcloud/server pull request #14263
Opened 2019-02-17 23:04 UTC by kesselb

Close #9750 

AppPasswordController:
```
curl -X GET \
  'https://nextcloud.test/ocs/v1.php/core/getapppassword' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'OCS-APIRequest: true' \
  -H 'cache-control: no-cache'
```
ClientFlowLoginClient: Tested with desktop app for linux

2019-02-17 23:04 UTC, kesselb commented on core/Controller/AppPasswordController.php
> +		$event->setApp('settings')
@nickvergessen can't use 'core' as app here. Is settings ok?

2019-02-18 10:20 UTC, nickvergessen requested changes

2019-02-18 10:20 UTC, nickvergessen commented on core/Controller/AppPasswordController.php
> +		$event->setApp('settings')
I would use dispatch an `GenericEvent` here from `EventDispatcherInterface` and listen to it in the settings app, because that is also where rendering of the activities later happens?

2019-02-18 10:20 UTC, nickvergessen commented on core/Controller/AppPasswordController.php
> +			->setObject('app_token', $generatedToken->getId(), 'App Password');
Use empty string instead of `'App Password'` so it can be translated later on.

2019-02-18 10:20 UTC, nickvergessen commented on core/Controller/AppPasswordController.php
> +			$this->logger->logException($e);
this can be merged with the one above:
```php
$this->logger->logException($e, [
	'message' => 'Could not publish activity',
  'level' => ILogger::WARN,
]);
```

2019-02-18 10:20 UTC, nickvergessen commented on core/Controller/ClientFlowLoginController.php
> +		$event = $this->activityManager->generateEvent();
same here, I would emit an event instead

2019-02-18 12:08 UTC, rullzer commented on core/Controller/AppPasswordController.php
> +		$event->setApp('settings')
Doesn't have to be generic you can make a new class extend it. So you can just make it do you bidding :)

2019-02-18 13:04 UTC, nickvergessen commented on core/Controller/AppPasswordController.php
> +		$event->setApp('settings')
We use GenericEvent almost everywhere. It's good enough for cases like "a new token was created" and limits the numbers of classes to load everywhere everytime etc.

`new GenericEvent($tokenObject)` and every information you need is there.

2019-02-18 18:00 UTC, kesselb commented on core/Controller/AppPasswordController.php
> +		$event->setApp('settings')
https://github.com/nextcloud/twofactor_u2f/blob/master/lib/Event/StateChanged.php looks a bit cleaner but i started with the `GenericEvent` :see_no_evil:

2019-02-19 10:24 UTC, rullzer commented
I do like the event approach btw. As at some point I also want notifications for this. Just so that you get security mails like 'A device with name X has been granted access to your account. If this wasn't you ....'

2019-02-19 11:50 UTC, kesselb commented
Can we get the `GenericEvent` approach in for nextcloud 16?

2019-02-19 13:59 UTC, rullzer approved these changes
Since this is all private API anyway. Lets do it!

2019-02-19 14:02 UTC, nickvergessen approved these changes

2019-02-19 14:08 UTC, merged