fix(EMailTemplate): malformed HTML in some cases
nextcloud/server pull request #14346
Opened 2019-02-22 15:20 UTC by tomaski

when an addBodyListItem() is not directly followed by addBodyButton(), resulting HTML is broken

2019-02-25 13:14 UTC, nickvergessen requested changes

2019-02-25 13:14 UTC, nickvergessen commented on lib/private/Mail/EMailTemplate.php
> +		$this->ensureBodyListClosed();
the order should be the otherway around:
```
		$this->ensureBodyListClosed();
		$this->ensureBodyIsOpened();
```

2019-02-25 23:27 UTC, tomaski commented on lib/private/Mail/EMailTemplate.php
> +		$this->ensureBodyListClosed();
thx @nickvergessen. fixed now

2019-02-26 07:30 UTC, nickvergessen approved these changes

2019-02-26 13:41 UTC, MorrisJobke approved these changes
Code makes sense 👍

2019-02-26 13:41 UTC, merged

2019-02-26 13:41 UTC, MorrisJobke commented
/backport to stable15