optimize Folder::getById to use less queries
nextcloud/server pull request #1441
Opened 2016-09-18 16:38 UTC by icewind1991

Instead of using N+M queries, use 3

(N being the number of storages for a user (including recieving shares, M being the number of storages that contain the matching file)

`UserMountCache::getMountsForFileId` has also been optimized 

Fixes https://github.com/nextcloud/server/issues/1435

2016-09-18 16:41 UTC, LukasReschke commented
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

2016-10-06 14:39 UTC, MorrisJobke commented
@nickvergessen Can you smashbox this?

2016-10-07 07:04 UTC, nickvergessen commented
Smash in progress ⏳

2016-10-07 07:30 UTC, nickvergessen requested changes

2016-10-07 07:30 UTC, nickvergessen commented on lib/private/Files/Node/Folder.php
> +		$cacheEntry = $mount->getStorage()->getCache()->get($id);
I couldn't even set up my instance completly.
`/index.php/apps/files/?dir=/&fileid=2` fails:
```
[Fri Oct 07 09:26:35.900105 2016] [:error] [pid 7565] [client ::1:33150] PHP Fatal error:  Call to a member function getPath() on boolean in /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/Files/Node/Folder.php on line 290
[Fri Oct 07 09:26:35.900149 2016] [:error] [pid 7565] [client ::1:33150] PHP Stack trace:
[Fri Oct 07 09:26:35.900161 2016] [:error] [pid 7565] [client ::1:33150] PHP   1. {main}() /home/nickv/Nextcloud/Smashbox/instance/server/index.php:0
[Fri Oct 07 09:26:35.900168 2016] [:error] [pid 7565] [client ::1:33150] PHP   2. OC::handleRequest() /home/nickv/Nextcloud/Smashbox/instance/server/index.php:40
[Fri Oct 07 09:26:35.900174 2016] [:error] [pid 7565] [client ::1:33150] PHP   3. OC\\Route\\Router->match($url = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/base.php:994
[Fri Oct 07 09:26:35.900180 2016] [:error] [pid 7565] [client ::1:33150] PHP   4. call_user_func:{/home/nickv/Nextcloud/Smashbox/instance/server/lib/private/Route/Router.php:298}(*uninitialized*, *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/Route/Router.php:298
[Fri Oct 07 09:26:35.900187 2016] [:error] [pid 7565] [client ::1:33150] PHP   5. OC\\AppFramework\\Routing\\RouteActionHandler->__invoke($params = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/Route/Router.php:298
[Fri Oct 07 09:26:35.900194 2016] [:error] [pid 7565] [client ::1:33150] PHP   6. OC\\AppFramework\\App::main($controllerName = *uninitialized*, $methodName = *uninitialized*, $container = *uninitialized*, $urlParams = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/Routing/RouteActionHandler.php:47
[Fri Oct 07 09:26:35.900200 2016] [:error] [pid 7565] [client ::1:33150] PHP   7. OC\\AppFramework\\Http\\Dispatcher->dispatch($controller = *uninitialized*, $methodName = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/App.php:127
[Fri Oct 07 09:26:35.900206 2016] [:error] [pid 7565] [client ::1:33150] PHP   8. OC\\AppFramework\\Http\\Dispatcher->executeController($controller = *uninitialized*, $methodName = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/Http/Dispatcher.php:90
[Fri Oct 07 09:26:35.900211 2016] [:error] [pid 7565] [client ::1:33150] PHP   9. call_user_func_array:{/home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/Http/Dispatcher.php:160}(*uninitialized*, *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/Http/Dispatcher.php:160
[Fri Oct 07 09:26:35.900218 2016] [:error] [pid 7565] [client ::1:33150] PHP  10. OCA\\Files\\Controller\\ViewController->index($dir = *uninitialized*, $view = *uninitialized*, $fileid = *uninitialized*, $fileNotFound = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/lib/private/AppFramework/Http/Dispatcher.php:160
[Fri Oct 07 09:26:35.900224 2016] [:error] [pid 7565] [client ::1:33150] PHP  11. OCA\\Files\\Controller\\ViewController->showFile($fileId = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/apps/files/lib/Controller/ViewController.php:151
[Fri Oct 07 09:26:35.900229 2016] [:error] [pid 7565] [client ::1:33150] PHP  12. OC\\Files\\Node\\Folder->getById($id = *uninitialized*) /home/nickv/Nextcloud/Smashbox/instance/server/apps/files/lib/Controller/ViewController.php:273
```

The problem is that the id is a string, therefor the cache here thinks it's a path and doesn't find it....

2016-10-10 12:17 UTC, icewind1991 commented on lib/private/Files/Node/Folder.php
> +		$cacheEntry = $mount->getStorage()->getCache()->get($id);
Added an explicit cast

2016-10-10 14:57 UTC, MorrisJobke commented
Tested and looks good - @rullzer could you have a look at this too?

👍

2016-10-12 07:41 UTC, rullzer commented
Beside my remark this makes sense to me!
Awesome work. :+1:

2016-10-12 07:42 UTC, rullzer requested changes

2016-10-12 07:42 UTC, rullzer commented on apps/files_sharing/lib/API/Share20OCS.php
> +			$share->getNode()->unlock(ILockingProvider::LOCK_SHARED);
Should still go. We handle this in the middleware so we don't have to duplicate this everywhere.

2016-10-12 14:14 UTC, icewind1991 commented on apps/files_sharing/lib/API/Share20OCS.php
> +			$share->getNode()->unlock(ILockingProvider::LOCK_SHARED);
Added this originally to prevent a single failing tests from breaking all other tests with locking errors, will remove it now the tests pass

2016-10-14 11:43 UTC, rullzer approved these changes

2016-10-14 11:43 UTC, rullzer commented
LGTM! :rocket: :new_moon:

2016-10-14 13:04 UTC, nickvergessen approved these changes

2016-10-14 13:04 UTC, nickvergessen commented
Smashbox passed ✅

2016-10-14 13:18 UTC, merged

2016-10-14 13:25 UTC, mmeeks commented
Awesome =) I hope it makes a real difference; any wall-clock timings Lukas ? =)