Show sharees via propfind
nextcloud/server pull request #14429
Opened 2019-02-28 09:30 UTC by tobiasKaminsky

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

2019-02-28 10:49 UTC, blizzz reviewed
too ambiguous maybe

2019-02-28 10:49 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +		if ($this->getPath() === "/") {
or-connect it with the condition in line 303

2019-02-28 10:49 UTC, blizzz commented on apps/dav/lib/Connector/Sabre/Node.php
> +		return implode(', ', $sharees);
ain't it better return the array and format it where the output is being handled (the callee)? This also only works as long as "," is prohibited as identifier. Further, you have all the types mixed in and identifiers are not unique across those types. → What do you want to achieve eventually?

2019-02-28 12:41 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/Node.php
> +		if ($this->getPath() === "/") {
:+1:

2019-02-28 12:42 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/Node.php
> +		return implode(', ', $sharees);
If I simply return $sharees, I do get that as plain string, e.g. "adminuser1user2".
If you have a better way, please feel free to change it or give me a hint.
I do not "care" as long as the client has a list of userIds of all sharees.

2019-02-28 13:53 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/Node.php
> +		return implode(', ', $sharees);
I removed Circle and Rooms, so that now only user, remote user and groups are returned.

2019-02-28 16:38 UTC, blizzz commented
as discussed on irc, we agreed about not returning grouped by type and and each user, group etc. is inside an id-tag within the appropriate element.

2019-03-01 09:41 UTC, rullzer requested changes
So I knew this looked familiar.

Because the way this is implemented it won't scale. If you request this property for a user on a share with 200 entries. It will fire off 300 SQL requests.

We should bundle it with https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/SharesPlugin.php

2019-03-01 09:41 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Node.php
> +				throw new OCSNotFoundException($this->l->t('Wrong path, file/folder doesn\'t exist'));
This should not be here

2019-03-01 09:41 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Node.php
> +				throw new OCSNotFoundException($this->l->t('Could not lock path'));
Same. This is not an OCS endpoint

2019-07-02 06:58 UTC, tobiasKaminsky commented
Bump, can anyone help me here? Or direct me in the right direction? :-)

2019-07-23 08:35 UTC, tobiasKaminsky commented
I really would like to have this in.

2019-07-31 11:12 UTC, rullzer commented
Let me fix the tests this evening

2019-07-31 20:39 UTC, rullzer commented
Ok so the test require some more work as they were/are not the cleanest. I'll have a look tomorrow.

2019-08-02 09:36 UTC, rullzer commented
Test all look good. Time for reviews.

2019-08-02 09:36 UTC, rullzer approved these changes
All good from my part

2019-08-02 09:37 UTC, rullzer commented
Small note. Once we have this we could also enhance the server UI.
We could show who a file is shared to more easily etc.

2019-08-06 08:09 UTC, georgehrke requested changes

2019-08-06 08:09 UTC, georgehrke commented on apps/dav/lib/Connector/Sabre/ShareeList.php
> +			$writer->writeElement("id", $share->getSharedWith());
The inner Elements id, display name, and type should be namespaces as well

2019-08-06 08:09 UTC, georgehrke commented on apps/dav/lib/Connector/Sabre/ShareeList.php
> +			$writer->writeElement("displayName", $share->getSharedWithDisplayName());
You usually don't use camelCase in XML. So either displayname or display-name please :)

2019-08-06 08:09 UTC, georgehrke commented
Besides those two remarks it looks good and works

2019-08-06 08:34 UTC, tobiasKaminsky commented
Can you test this please with an admin account:
```
<nc:sharees>
          <nc:sharee>
            <nc:id>admin</nc:id>
            <nc:display-name/>
            <nc:type>1</nc:type>
          </nc:sharee>
          <nc:sharee>
            <nc:id>user1</nc:id>
            <nc:display-name>User One</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
          <nc:sharee>
            <nc:id>user2</nc:id>
            <nc:display-name>user2</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
``` 

For some reason the display name of an admin is missing, but it should be at least userId.
It is working for other users…
I just want to be sure if this is a problem of my local system…

2019-08-06 08:41 UTC, georgehrke commented on apps/dav/lib/Connector/Sabre/ShareeList.php
> +			$writer->writeElement('{' . self::NS_NEXTCLOUD . '}display-name', $share->getSharedWithDisplayName());
```suggestion
			$writer->writeElement('{' . self::NS_NEXTCLOUD . '}display-name', $share->getSharedWithDisplayName() ?? $share->getSharedWith());
```

2019-08-06 12:02 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/ShareeList.php
> +			$writer->writeElement('{' . self::NS_NEXTCLOUD . '}display-name', $share->getSharedWithDisplayName());
I wrote a test for android library and there the problem also exists.
It seems that always one of the display names is set to userId.

2019-08-06 12:04 UTC, tobiasKaminsky commented
BUG:

- create folder "testFolder"
- share it to user1, user2
- query "/remote.php/webdav/", see 
```
 <d:response>
    <d:href>/remote.php/webdav/testFolder/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees>
          <nc:sharee>
            <nc:id>user1</nc:id>
            <nc:display-name>User One</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
          <nc:sharee>
            <nc:id>user2</nc:id>
            <nc:display-name>user2</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

- query "/remote.php/webdav/testFolder", see:

```
 <d:response>
    <d:href>/remote.php/webdav/testFolder/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees>
          <nc:sharee>
            <nc:id>user1</nc:id>
            <nc:display-name>User One</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

2019-08-08 09:01 UTC, tobiasKaminsky commented
Bug fixed via latest commit.

2019-08-09 06:32 UTC, tobiasKaminsky commented
From my side this is ready to get in

2019-08-11 19:35 UTC, rullzer commented
Fixed the failing tests

2019-08-13 18:20 UTC, georgehrke approved these changes
Seems to do what its supposed do and webdav compliance wise I'm also happy with it 👍

2019-08-13 18:22 UTC, merged