Add app token QR codes for mobile apps
nextcloud/server pull request #14450
Opened 2019-03-01 08:20 UTC by ChristophWurst

This adds the option to generate a QR code in order to easily set up a mobile app with a new app token. App tokens are allowed on mobile as well, but in some cases it's easier to do this flow, e.g. when you're using U2F as your only 2FA method. In that case you would have to type the newly created app token into your phone.

Fixes https://github.com/nextcloud/server/issues/429.

Todo
- [x] Add subtle button to show/generate a QR code
- [ ] Render a URL that actually works with the mobile app

cc @tobiasKaminsky @nextcloud/android @nextcloud/ios 

---

From https://github.com/nextcloud/server/issues/429#issuecomment-442495238

> waiting desperately for integration on server by @ChristophWurst

The time has come :rocket:

2019-03-01 08:27 UTC, ChristophWurst commented
# Screen 1
![bildschirmfoto von 2019-03-01 09-13-14](https://user-images.githubusercontent.com/1374172/53625701-1b799780-3c04-11e9-9270-4d454a3681b0.png)

# Screen 2
![bildschirmfoto von 2019-03-01 09-13-25](https://user-images.githubusercontent.com/1374172/53625700-1ae10100-3c04-11e9-8ad7-118f9fbaf9b5.png)

# Screen 3
![bildschirmfoto von 2019-03-01 09-13-33](https://user-images.githubusercontent.com/1374172/53625698-1ae10100-3c04-11e9-8b45-444b9bd87b2b.png)

2019-03-01 11:28 UTC, ChristophWurst commented
Found out the QR reader feature is already included in the latest Android app releases: https://github.com/nextcloud/server/issues/429.

This is ready to review. I could successfully set up an account on Android with my local dev instance :rocket:

2019-03-01 11:28 UTC, ChristophWurst commented
@marinofaggiana are the `nc://login` URLs supported in our iOS app as well? Is there a QR code reader?

2019-03-01 11:49 UTC, rullzer approved these changes
Works like a charm!

2019-03-01 13:16 UTC, ChristophWurst commented
Failing files app acceptance test is unrelated.

2019-03-01 15:42 UTC, skjnldsv requested changes
One little change but fine otherwise!!

2019-03-01 15:42 UTC, skjnldsv commented on settings/src/components/AuthTokenSetupDialogue.vue
> +			 v-if="!showQR">
v-if, v-else?

2019-03-01 15:47 UTC, ChristophWurst commented on settings/src/components/AuthTokenSetupDialogue.vue
> +			 v-if="!showQR">
Fixed!

2019-03-01 15:49 UTC, skjnldsv approved these changes

2019-03-01 16:38 UTC, ChristophWurst commented
CI failure is unrelated

2019-03-01 16:39 UTC, merged

2019-03-05 19:06 UTC, marinofaggiana commented
Available on iOS.