Password confirmation for some actions
nextcloud/server pull request #1447
Opened 2016-09-19 14:35 UTC by nickvergessen

when performing certain actions, we want to make sure, that the user is actually the user.
Therefor we require a password confirmation, e.g. when changing the email address.

### ToDo
- [ ] Add a message to the confirmation box
- [ ] Use on the personal page:
 - [ ] Add app password
 - [ ] Generate backup codes (2FA)
- [ ] Use on the admin page:
 - [ ] Enable encryption
 - [ ] Change email settings
 - [ ] Or just all?
- [ ] Fix changing an email from the admin page

@LukasReschke @MorrisJobke

2016-09-19 15:58 UTC, nickvergessen commented
Both, because @LukasReschke should already have a look at it, while I develop the rest :stuck_out_tongue:

2016-10-25 13:48 UTC, nickvergessen commented
@MorrisJobke can you have a look?

Currently when you open the user management, then the settings section and toggle "show storage location" that doesn't work.

For easier testing set down the confirmation time to 10 seconds instead of 30 minutes:
```diff
diff --git a/core/js/js.js b/core/js/js.js
index e423b6e..89426cc 100644
--- a/core/js/js.js
+++ b/core/js/js.js
@@ -1536,6 +1536,7 @@ OC.PasswordConfirmation = {
 
        requiresPasswordConfirmation: function() {
                var timeSinceLogin = moment.now() - nc_lastLogin * 1000;
+               return timeSinceLogin > 10 * 1000; // 30 minutes
                return timeSinceLogin > 30 * 60 * 1000; // 30 minutes
        },
 
diff --git a/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php b/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
index 981232f..7e385b9 100644
--- a/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
+++ b/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
@@ -147,7 +147,8 @@ class SecurityMiddleware extends Middleware {
 
                if ($this->reflector->hasAnnotation('PasswordConfirmationRequired')) {
                        $lastConfirm = (int) $this->session->get('last-password-confirm');
-                       if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
+                       if ($lastConfirm < (time() - 10)) { // allow 15 seconds delay
+                       //if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
                                throw new NotConfirmedException();
                        }
                }
diff --git a/settings/ajax/togglegroups.php b/settings/ajax/togglegroups.php
index b9958be..35ac36c 100644
--- a/settings/ajax/togglegroups.php
+++ b/settings/ajax/togglegroups.php
@@ -29,7 +29,8 @@ OC_JSON::checkSubAdminUser();
 OCP\JSON::callCheck();
 
 $lastConfirm = (int) \OC::$server->getSession()->get('last-password-confirm');
-if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
+if ($lastConfirm < (time() - 10)) { // allow 15 seconds delay
+//if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
        $l = \OC::$server->getL10N('core');
        OC_JSON::error(array( 'data' => array( 'message' => $l->t('Password confirmation is required'))));
        exit();
diff --git a/settings/ajax/togglesubadmins.php b/settings/ajax/togglesubadmins.php
index 5658a38..eb79ced 100644
--- a/settings/ajax/togglesubadmins.php
+++ b/settings/ajax/togglesubadmins.php
@@ -25,7 +25,8 @@ OC_JSON::checkAdminUser();
 OCP\JSON::callCheck();
 
 $lastConfirm = (int) \OC::$server->getSession()->get('last-password-confirm');
-if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
+if ($lastConfirm < (time() - 10)) { // allow 15 seconds delay
+//if ($lastConfirm < (time() - 30 * 60 + 15)) { // allow 15 seconds delay
        $l = \OC::$server->getL10N('core');
        OC_JSON::error(array( 'data' => array( 'message' => $l->t('Password confirmation is required'))));
        exit();
```

2016-11-01 19:39 UTC, LukasReschke requested changes

2016-11-01 19:39 UTC, LukasReschke commented on core/js/config.php
> +$sessionTime = \OC::$server->getSession()->get('last-password-confirm');
This is kinda often used and seems error-prone. Maybe let's add that to `OCP\IUser` as new method? `isSudoMode() : bool` or so?

2016-11-01 19:39 UTC, LukasReschke commented on core/js/config.php
> +$sessionTime = \OC::$server->getSession()->get('last-password-confirm');
Would introduce a new dependency on ISession in the User class though. Anyhow, I think we should abstract that away in some other class. Also it's own helper class is fine in the `OC\Security` namespace.

2016-11-02 09:45 UTC, nickvergessen commented on core/js/config.php
> +$sessionTime = \OC::$server->getSession()->get('last-password-confirm');
Well it's used 3 times and in legacy code (ajax endpoints which don't use controller).
Once the legacy is gone, only the annotation is used, so I think the 3 appearances are fine.

2016-11-02 09:55 UTC, LukasReschke commented on core/js/config.php
> +$sessionTime = \OC::$server->getSession()->get('last-password-confirm');
Fair enough

2016-11-03 09:26 UTC, nickvergessen commented
@MorrisJobke I fail to get the quota and the email thing covered, can you try it?

2016-11-03 10:30 UTC, MorrisJobke commented
* [ ] BUG: as an admin I need to enter my password when changing my email address on the personal page (this is not the case for a non-admin)

2016-11-03 10:30 UTC, LukasReschke commented
>  BUG: as an admin I need to enter my password when changing my email address on the personal page (this is not the case for a non-admin)

BUG: As an normal user I should also have to enter my password 😉

2016-11-11 09:00 UTC, nickvergessen commented
Should be ready to review now, only thing left is that you can't submit with enter, but @ChristophWurst will take care of that soon.

2016-11-16 08:58 UTC, rullzer commented
* Submit on enter now works

2016-11-16 16:12 UTC, jancborchardt commented
Please use the modal we use everywhere else. This doesn’t work on mobile at all, and we don’t need a second implementation to maintain & style. ;)

2016-11-17 09:37 UTC, nickvergessen commented on core/css/jquery.ocdialog.css
> -	position: absolute;
@jancborchardt this was required because the password field was not clickable since the button row was overlaying it. Maybe you can have a look at the design a bit.

2016-11-17 15:40 UTC, MorrisJobke commented
@nickvergessen conflicts 🙈

2016-11-18 12:43 UTC, LukasReschke approved these changes

2016-11-18 13:19 UTC, MorrisJobke commented
Tested and works 👍

2016-11-18 14:38 UTC, jancborchardt commented on core/css/jquery.ocdialog.css
> -	position: absolute;
Eeeh this will mess with other dialogs like the move dialog. :-1: 

Will need to check it out

2016-11-18 14:42 UTC, merged