Reconnect to DB after timeout for Notify command. Fixes #14479
nextcloud/server pull request #14480
Opened 2019-03-03 00:44 UTC by cowai

Every 8th hour I got a "2006 Mysql server has gone away". It was due to a 8 hour wait_time.
Since the Notify command should be running 24/7 increasing wait_time won't help much. Change events that triggers this never get registered and filecache will be wrong/out of sync.

This PR makes it reconnect in case of timeout. I borrowed the reconnect logic from: https://github.com/nextcloud/server/blob/1cfa870821c92bdd6854171c8c073ed16529b6df/apps/files/lib/Command/Scan.php#L300

I also needed to move updateQuery to a method due to it being a prepared statement from a dead connection and it needed to be remade after reconnect.

2019-03-04 12:27 UTC, MorrisJobke commented on apps/files_external/lib/Command/Notify.php
> +			$output->writeln("<info>Error while disconnecting from database: {$ex->getMessage()}</info>");
Please log this exception also. You need to inject the logger into the constructor of this class and then you can use it here with something like:

```php
$this->log->logException($ex, ['app' => 'files_external']);
```

2019-03-04 12:27 UTC, MorrisJobke commented on apps/files_external/lib/Command/Notify.php
> +				$output->writeln("<info>Error while re-connecting to database: {$ex->getMessage()}</info>");
Same here.

2019-03-04 12:28 UTC, MorrisJobke commented on apps/files_external/lib/Command/Notify.php
> +			$output->writeln("<info>Error while disconnecting from database: {$ex->getMessage()}</info>");
You can also specify a custom message then:

```php
$this->log->logException($ex, ['app' => 'files_external', 'message' => 'Error while disconnecting from DB', 'level' => 1]);
```

This logs with the message and as log level INFO.

2019-03-04 12:28 UTC, cowai commented on apps/files_external/lib/Command/Notify.php
> +			$output->writeln("<info>Error while disconnecting from database: {$ex->getMessage()}</info>");
Got it!

2019-03-04 12:28 UTC, MorrisJobke commented on apps/files_external/lib/Command/Notify.php
> +			$output->writeln("<info>Error while disconnecting from database: {$ex->getMessage()}</info>");
But maybe a warning is better suited here.

2019-03-04 12:29 UTC, MorrisJobke commented on apps/files_external/lib/Command/Notify.php
> +			$output->writeln("<info>Error while disconnecting from database: {$ex->getMessage()}</info>");
Log levels are also available via constants for better readability: https://github.com/nextcloud/server/blob/38a90130ce425d531a804dff591df4a883de3154/lib/public/ILogger.php#L39-L58

2019-03-04 12:33 UTC, cowai commented on apps/files_external/lib/Command/Notify.php
> +				$output->writeln("<info>Error while re-connecting to database: {$ex->getMessage()}</info>");
Yes. Thank you @MorrisJobke :+1:

2019-03-04 13:15 UTC, MorrisJobke commented
Mind to add the sign-off message to your last commit: https://github.com/nextcloud/server/pull/14480/checks?check_run_id=72120851

2019-03-04 13:24 UTC, cowai commented
@MorrisJobke woops. Done!

2019-03-04 13:57 UTC, kesselb requested changes

2019-03-04 13:57 UTC, kesselb commented on apps/files_external/lib/Command/Notify.php
> +	private $log;
`$log` should be `$logger` because you use it that way (e.g. line 60, line 167)

2019-03-04 14:03 UTC, cowai commented on apps/files_external/lib/Command/Notify.php
> +	private $log;
Thanks. Good catch!

2019-03-04 14:58 UTC, icewind1991 approved these changes

2019-03-04 16:18 UTC, MorrisJobke approved these changes
Code looks good 👍

2019-03-04 20:36 UTC, merged

2019-04-08 15:27 UTC, icewind1991 commented
/backport to stable15

2019-04-08 15:27 UTC, icewind1991 commented
/backport to stable14