Enh/force enable apps
nextcloud/server pull request #14578
Opened 2019-03-06 19:29 UTC by rullzer

Allow force enabling apps. So if an app is not yet compatible with 15 the admin can force enable it

Todo:
- [ ] Fix frontend code of the app management page to allow force enable
- [ ] Add controller to add force enabled apps

Also:
- [ ] Look into appstore for 16 returning all apps

2019-03-06 19:53 UTC, rullzer commented
Frontend behavior:

1. The list that is fetched from `/settings/apps/list` now for each entry contains a `isCompatible` entry.

If isCompatible is false. I suggest we clearly highlight this. Grey out? Red. Whatever. But it needs to be visible. Maybe also a badge oir something?

2. If `isCompatible` is false and `canInstall` is false. There should be a button. This should say something like 'Force`. This will then show a popup I guess where there is some text. Like 'This app is not marked as compatible with your Nextcloud version. If you continue you will still be able to install the app. Note that the app might not work as expected.' Then if the admin continues a post (with the appId) should be made to `/setttings/apps/force`.

3. Then reload the page (This is not the most elegant but will ahve to do for now as you need to reobtain the list of apps).

4. Now you should be able to just enable your app.

2019-03-07 11:42 UTC, ChristophWurst commented
- [ ] Bug on upgrade

```
$ php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OC_App::isAppCompatible(), 2 passed in /home/christoph/workspace/nextcloud/lib/private/Updater.php on line 396 and exactly 3 expected in /home/christoph/workspace/nextcloud/lib/private/legacy/app.php:829
Stack trace:
#0 /home/christoph/workspace/nextcloud/lib/private/Updater.php(396): OC_App::isAppCompatible('16.0.0.2', Array)
#1 /home/christoph/workspace/nextcloud/lib/private/Updater.php(244): OC\Updater->checkAppsRequirements()
#2 /home/christoph/workspace/nextcloud/lib/private/Updater.php(121): OC\Updater->doUpgrade('16.0.0.2', '16.0.0.2')
#3 /home/christoph/workspace/nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#4 /home/christoph/workspace/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/christoph/workspace/nextcloud/3rdparty/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/christoph/workspace/nextcloud/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/christoph/workspace/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/christoph/workspace/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/christoph/workspace/nextcloud/console.php(97): OC\Console\Application->run()
#10 /home/christoph/workspace/nextcloud/occ(11): require_once('/home/christoph...')

```

2019-03-07 11:55 UTC, ChristophWurst commented
- [ ] Bug

```
[Vue warn]: Failed to resolve directive: tooltip

(found in <AppItem> at settings/src/components/appList/appItem.vue)
```

2019-03-07 12:27 UTC, ChristophWurst commented
- [ ] Bug

```

Nextcloud
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 127.0.0.1
    Request ID: 8Tyhi7yR8hwP7m7RK1zy
    Type: ReflectionException
    Code: 0
    Message: Method OC\Settings\Controller\AppSettingsController::ignoreMaxVersion() does not exist
    File: /home/christoph/workspace/nextcloud/lib/private/AppFramework/Utility/ControllerMethodReflector.php
    Line: 47


Trace

#0 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Utility/ControllerMethodReflector.php(47): ReflectionMethod->__construct(Object(OC\Settings\Controller\AppSettingsController), 'ignoreMaxVersio...')
#1 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(95): OC\AppFramework\Utility\ControllerMethodReflector->reflect(Object(OC\Settings\Controller\AppSettingsController), 'ignoreMaxVersio...')
#2 /home/christoph/workspace/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AppSettingsController), 'ignoreMaxVersio...')
#3 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OC\\Settings\\Con...', 'ignoreMaxVersio...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#4 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#5 /home/christoph/workspace/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#6 /home/christoph/workspace/nextcloud/lib/base.php(975): OC\Route\Router->match('/settings/apps/...')
#7 /home/christoph/workspace/nextcloud/index.php(42): OC::handleRequest()
#8 {main}


```

2019-03-07 12:38 UTC, ChristophWurst commented
- [ ] Todo

Style the force enable button in a way that it's obvious the user is performing a critical action.

2019-03-07 14:29 UTC, rullzer commented
Bug on upgrade fixed. It now assumes the max version is not ignored until explicitly stated.

This means apps will still get disable on upgrade. even if they are not force enabled here. Which is a fair limitation for a first step.

2019-03-07 15:07 UTC, rullzer commented
[ ] Bug

Getting an incompatible list of apps from the appstore download & enable does :boom:

2019-03-07 15:24 UTC, rullzer commented
- [ ] Issue

The 'download and force enable' is a bit weird. Because it doesn't download. It only force enables.,

But I'm not a big fan of force enable.. @jancborchardt @karlitschek any suggestions?

2019-03-07 15:32 UTC, rullzer commented
TODO
- [ ] Add some screenshots

2019-03-07 16:01 UTC, karlitschek commented
nice. I'm not sure about the right term. Sorry.

2019-03-12 17:10 UTC, jancborchardt commented
@rullzer can you show a screenshot of where it appears – just in the apps management as button label? I think "Force enable" is fine, no? Or "Enable incompatible app", "Enable untested app", …?

2019-03-18 20:10 UTC, rullzer commented
Ok this is shaping up. Failing tests need to be fixed. But not today.

2019-03-19 06:28 UTC, MorrisJobke commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +	const INVALIDATE_AFTER_SECONDS = 1;
🧐

2019-03-19 06:34 UTC, MorrisJobke commented on settings/src/components/appList/appItem.vue
> +		border-color: red;
We should use something different here. I would vote for:

```css
background: white;
border-color: var(--color-error);
color: var(--color-error);
```

which results in 

![Bildschirmfoto 2019-03-19 um 07 31 44](https://user-images.githubusercontent.com/245432/54585063-5f003e00-4a19-11e9-8d00-63e7d8972bec.png)


Current one looks like this:

![Bildschirmfoto 2019-03-19 um 07 32 06](https://user-images.githubusercontent.com/245432/54585076-67587900-4a19-11e9-87c0-591521f5d9a5.png)


And this would be the current one, but with fixed `color` attribute:

![Bildschirmfoto 2019-03-19 um 07 31 57](https://user-images.githubusercontent.com/245432/54585097-763f2b80-4a19-11e9-9091-ab3463e76cf5.png)

2019-03-19 06:34 UTC, MorrisJobke commented on settings/src/components/appList/appItem.vue
> +		border-color: red;
cc @nextcloud/designers

2019-03-19 06:37 UTC, enoch85 commented on settings/src/components/appList/appItem.vue
> +		border-color: red;
I vote for the first one. White background, red text.

2019-03-19 06:46 UTC, MorrisJobke commented
I fixed the UI to be a bit more elegant (also in dark mode):

![Bildschirmfoto 2019-03-19 um 07 43 08](https://user-images.githubusercontent.com/245432/54585684-0d58b300-4a1b-11e9-9f5a-80f86495aa22.png)

![Bildschirmfoto 2019-03-19 um 07 43 31](https://user-images.githubusercontent.com/245432/54585668-00d45a80-4a1b-11e9-88b6-ff16e141b378.png)

2019-03-19 06:50 UTC, rullzer commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +	const INVALIDATE_AFTER_SECONDS = 1;
Yeah that needs to die

2019-03-19 08:57 UTC, jancborchardt commented
Looks very nice! Only 3 things:
- If there is an update available, we shouldn't show the force enable button? Cause the update might have compatibility with the new version. So actually there should only ever 2 buttons: 1) remove and 2) either enable, update or force enable.
- The position of the text in the sidebar could be closer to the buttons, e.g. moved a bit up so it's below the buttons and above the links.
- In dark theme, the button text of the red button should also be white (lile the primary button).

2019-03-19 09:42 UTC, rullzer commented
> If there is an update available, we shouldn't show the force enable button? Cause the update might have compatibility with the new version. So actually there should only ever 2 buttons: 1) remove and 2) either enable, update or force enable.

True. But out of scope for now. I want this in asap. But will create a ticket.

> The position of the text in the sidebar could be closer to the buttons, e.g. moved a bit up so it's below the buttons and above the links.

Again. Will create a ticket

> In dark theme, the button text of the red button should also be white (lile the primary button).

Fair enough.

2019-03-19 20:31 UTC, rullzer commented
Time to get this in!

2019-03-19 23:37 UTC, nickvergessen submitted a review, later dismissed

2019-03-19 23:37 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/AppFetcher.php
> +		$this->endpointUrl = 'https://apps.nextcloud.com/api/v1/apps.json';
This breaks the "can i update" check in updatenotifications. 🤔
Let me check if we can solve both in one go

2019-03-20 07:30 UTC, skjnldsv commented
> Fair enough.

You're now a designer @rullzer :grin:

2019-03-20 07:33 UTC, skjnldsv requested changes

2019-03-20 07:33 UTC, skjnldsv commented on settings/src/components/appList/appItem.vue
> +<style scoped>
Maybe we should stick to the external css for now.
It will get confusing otherwise.

2019-03-20 09:05 UTC, ChristophWurst commented
I can't reproduce the failing integration test locally. The enterprise bundle can be installed just like before and the "Disable" buttons are shown as well.

2019-03-20 11:22 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/AppFetcher.php
> +		$this->endpointUrl = 'https://apps.nextcloud.com/api/v1/apps.json';
Fixed

2019-03-20 11:27 UTC, nickvergessen commented
To test my change, set your channel to production in version.php and change
https://github.com/nextcloud/server/blob/b04a44babdecad235828505191f5b36f2605ec72/apps/updatenotification/lib/UpdateChecker.php#L49
to
```php
		$data = [
			'version' => '16.0.2.1',
			'versionstring' => '16.0.0',
			'autoupdater' => '1',
			'eol' => '0',
			'web' => 'https://nextcloud.com',
			'url' => 'https://nextcloud.com',
			'changes' => '',
		];//$this->updater->check();
```

if you have talk enabled, it will now still tell you that there is no version for 16 in the update-available check.

2019-03-20 14:37 UTC, rullzer commented on settings/src/components/appList/appItem.vue
> +<style scoped>
Lets also do that separate. I'm fine but I just want this in asap. Then we can fix that during the beta

2019-03-20 14:52 UTC, rullzer commented
CI Green: https://drone.nextcloud.com/nextcloud/server/17171

Lets do this!

2019-03-20 14:59 UTC, nickvergessen approved these changes
:elephant: because I still dont think we should do this

2019-03-20 15:00 UTC, skjnldsv approved these changes

2019-03-20 15:00 UTC, skjnldsv commented on settings/src/components/appList/appItem.vue
> +<style scoped>
ok

2019-03-20 15:31 UTC, MorrisJobke approved these changes
Tested and works 👍 

Would not work in a load balanced scenario due to the change to the config.php, but app management doesn't work as expected there anyways.

2019-03-20 18:22 UTC, merged

2019-03-20 18:34 UTC, rullzer commented
@MorrisJobke fair point. But yes they have issues with that already indeed.

2019-03-20 19:02 UTC, MorrisJobke commented
But the acceptance tests failed 🙈

2019-03-20 19:05 UTC, rullzer commented
@MorrisJobke it did at random... but as you can see https://drone.nextcloud.com/nextcloud/server/17171 passed (which is the same code)

2019-03-20 19:47 UTC, rullzer commented
@MorrisJobke yes race condition. Temp disable in https://github.com/nextcloud/server/pull/14774 we can revert it once all apps have a 16 version.