Show users without groups
nextcloud/server pull request #14614
Opened 2019-03-10 17:54 UTC by chiefbrain

see #14612

2019-03-11 17:54 UTC, blizzz commented on settings/Controller/UsersController.php
> +			$notGroupedUsers = $this->userManager->countNotGroupedUsers();
please (like in the line above) avoid counting on LDAP setups, it might take too long

2019-03-11 20:27 UTC, chiefbrain commented on settings/Controller/UsersController.php
> +			$notGroupedUsers = $this->userManager->countNotGroupedUsers();
Ok, done

2019-03-20 12:52 UTC, blizzz requested changes
See comments.

There is a further issue that complicates this scenario: the user backend actually does not have a clue about the memberships, and there might be more than one group backend enabled and users from one backend might belong to groups from a different one. This makes determining all ungrouped users very expensive.

2019-03-20 12:52 UTC, blizzz commented on lib/private/User/Manager.php
> +	 * @since 1?.0.0
17 (as we're in feature freeze for 16) – but the annotation should go into the Interface `\OCP\IUserManager`

2019-03-20 12:52 UTC, blizzz commented on lib/private/User/Manager.php
> +		$queryBuilder = \OC::$server->getDatabaseConnection()->getQueryBuilder();
this is the wrong place to gather the information for the database, as the UserManager forwards all requests to the registered Backends. This implementation would go to `OC\User\Database`.  The manager instead would cycle through all registered backends implementing this method (→ needs an Interface, e.g. '\OCP\User\ICountUngroupUsers`), and sum up what each backend returned.

2019-03-20 12:52 UTC, blizzz commented on settings/src/store/users.js
> +			return api.get(OC.linkToOCS(`cloud/users/details?offset=${offset}&limit=${limit}&search=${search}`, 2))
This seems to be identical to the following section… why?

2019-03-20 12:52 UTC, blizzz commented on settings/src/views/Users.vue
> +			// Groups, separator, no groups, separator, admin, disabled, everyone
the right-most seperator is unnecessary as it is a special group like the others imho

2019-03-20 12:52 UTC, blizzz commented on settings/src/views/Users.vue
> +				notGroupedGroup.text = t('settings', 'Users w/o groups');							// rename notGrouped group
Let's write out "w/o", for many, especially non-native speaks it might not be clear, and it means different things in different fields (e.g. banking), not making sense, necessarily, but perhaps enough to irritate.

2019-03-20 12:53 UTC, blizzz commented
cc @skjnldsv

2019-09-15 18:30 UTC, ChristophWurst commented
Closing as there are many unresolved review comments that never got any attention.

2019-09-15 18:30 UTC, closed without merging