Show sharing in menu in grid view
nextcloud/server pull request #14695
Opened 2019-03-14 17:02 UTC by skjnldsv

![Capture d’écran_2019-03-14_17-57-11](https://user-images.githubusercontent.com/14975046/54376399-498abd00-4683-11e9-9534-ec7da956100f.png)
![Capture d’écran_2019-03-14_17-57-20](https://user-images.githubusercontent.com/14975046/54376400-498abd00-4683-11e9-99ba-e2c0af3b0c74.png)
![Capture d’écran_2019-03-14_17-57-32](https://user-images.githubusercontent.com/14975046/54376401-498abd00-4683-11e9-8802-3b0cf412ca99.png)

Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

2019-03-14 17:21 UTC, juliushaertl commented on apps/files/js/fileactionsmenu.js
> +			console.info(items);
I'd say this should be removed.

2019-03-14 17:21 UTC, juliushaertl commented on apps/files/js/fileactionsmenu.js
> +console.info(items);
Same here.

2019-03-15 00:53 UTC, jancborchardt commented
Was just comparing with the right-click menu and also with our logical sorting – and I have to correct myself: Let’s put the "Share" action first in the list, _above_ "Favorites" rather than below. Since elsewhere it’s always the first action, even being outside of the menu. :)


Otherwise awesome! :tada:

2019-03-15 09:34 UTC, jancborchardt requested changes
As said let’s put Share as first entry in the menu (sorry for the confusion) then it’s :+1: :)

2019-03-15 09:49 UTC, skjnldsv commented
> As said let’s put Share as first entry in the menu (sorry for the confusion) then it’s  :)

Above favorite?

2019-03-15 09:55 UTC, skjnldsv commented
@jancborchardt done! :wink:

2019-03-15 11:28 UTC, MorrisJobke commented
It now only shows "Shared" for me with the normal share icon instead of the little chain for public links or the avatar for user/group shares. 😢

2019-03-15 11:53 UTC, skjnldsv commented
> It now only shows "Shared" for me with the normal share icon instead of the little chain for public links

I guess I missed some check :)

>  or the avatar for user/group shares.

But this is only on incoming shares, right?

2019-03-15 13:46 UTC, MorrisJobke commented
> But this is only on incoming shares, right?

Ah - right.

2019-03-15 22:30 UTC, jancborchardt approved these changes
sure

2019-03-19 07:12 UTC, MorrisJobke commented
### Status of [17072](https://drone.nextcloud.com/nextcloud/server/17072): failure

#### TESTS=jsunit
<details><summary>Show full log</summary>

```
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'JQMIGRATE: Migrate is installed, version 1.4.1'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'Type files registered'
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileActionsMenu tests rendering does not render inline actions FAILED
	Expected 1 to equal 0.
	apps/files/tests/js/fileactionsmenuSpec.js:117:69
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.Util tests Share action icon shows owner name when owner is available FAILED
	Expected false to equal true.
	apps/files_sharing/tests/js/shareSpec.js:170:65
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.Util tests Share action keep share text after updating reshare FAILED
	Expected false to equal true.
	apps/files_sharing/tests/js/shareSpec.js:392:65
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.Util tests Share action keep share text after unsharing reshare FAILED
	Expected false to equal true.
	apps/files_sharing/tests/js/shareSpec.js:425:65
PhantomJS 2.1.1 (Linux 0.0.0): Executed 1072 of 1076 (4 FAILED) (skipped 4) (13.745 secs / 13.472 secs)

```
</details>

2019-03-20 11:08 UTC, MorrisJobke commented
@skjnldsv Mind to fix the unit tests and conflicts?

2019-03-20 11:21 UTC, skjnldsv commented
@skjnldsv in my todo for today :)

2019-03-21 07:13 UTC, skjnldsv commented
Fixed

2019-03-21 08:20 UTC, MorrisJobke approved these changes
Tested and works 👍

2019-03-21 08:56 UTC, merged