Gpg mailer hooks
nextcloud/server pull request #14722
Opened 2019-03-16 15:33 UTC by tacruc

I'm working on an APP implementing the ability to send encrypted emails to registered users #7310.
Therefor a two small modifications are needed.

- An Hook in scope \OC\Mail    preSendMessage(IMessage $message)
- And the function  OC\Mail\Massage::setSwiftMessage, to replace unencrypted swiftmessage with the encrypted one.

The rest is fixing a bug if swiftMessage->getTo() is returning NULL

2019-03-16 16:46 UTC, tacruc commented
I think the last failures are independent of the commits.
One is a timeout on Publish-S3

The second is 
TESTS-ACCEPTANCE=users
```
  Scenario: create a new user                                       # /drone/src/github.com/nextcloud/server/tests/acceptance/features/users.feature:4
    Given I act as Jane                                             # ActorContext::iActAs()
    And I am logged in as the admin                                 # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                    # SettingsMenuContext::iOpenTheUserSettings()
    And I click the New user button                                 # UsersSettingsContext::iClickTheNewUserButton()
      New user button in Users Settings could not be found (NoSuchElementException)
    And I see that the new user form is shown                       # UsersSettingsContext::iSeeThatTheNewUserFormIsShown()
    When I create user unknownUser with password 123456acb          # UsersSettingsContext::iCreateUserWithPassword()
Then I see that the list of users contains the user unknownUser # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
```

2019-03-16 18:24 UTC, kesselb commented
@rullzer there are no hooks in \OC\Mail. Could we use Events instead of Hooks here?

2019-03-16 18:33 UTC, kesselb commented on lib/private/Mail/Message.php
> +		return is_null($from) ? []: $from;
You can use null coalescing here: `$this->swiftMessage->getFrom() ?? []`;

2019-03-16 18:35 UTC, tacruc commented on lib/private/Mail/Message.php
> +		return is_null($from) ? []: $from;
should work will try it

2019-03-19 10:02 UTC, tacruc commented
@kesselb cloud you add the to review flag?

2019-04-27 21:42 UTC, tacruc commented
@kesselb can you help me, where I can find more information about events. It is important that the email is not send until the call to the app is finished, otherwise an unencrypted email is send.

2019-05-16 22:20 UTC, tacruc commented
I have changed it, to not create a hook, but use the dispatcher to dispatch a event \OC\Mail::preSendMessage

2019-05-21 08:54 UTC, georgehrke commented on lib/private/Mail/Mailer.php
> +                         EventDispatcherInterface $dispatcher) {
Please fix the indentation

2019-05-21 08:54 UTC, georgehrke commented on lib/private/Mail/Mailer.php
> +        $this->dispatcher->dispatch('\OC\Mail::preSendMessage',
indentation

2019-05-21 08:54 UTC, georgehrke commented on lib/private/Server.php
> +                $c->getEventDispatcher()
indentation

2019-05-21 10:26 UTC, tacruc commented on lib/private/Mail/Mailer.php
> +                         EventDispatcherInterface $dispatcher) {
@georgehrke 
I'm confused with the indentation. I should use tabs right?
But in https://docs.nextcloud.com/server/16/developer_manual/general/codingguidelines.html#php it says PEAR and in https://pear.php.net/manual/en/standards.indenting.php it says 4 spaces?

2019-05-21 10:43 UTC, tacruc commented on lib/private/Mail/Mailer.php
> +                         EventDispatcherInterface $dispatcher) {
Never mind found it was too obvious placed.

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Mailer.php
> +                         EventDispatcherInterface $dispatcher) {
`@param EventDispatcherInterface $dispatcher` mind to add the dispatcher to the phpdoc?

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Mailer.php
> + *
Do you need this additional space? :)

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Mailer.php
> +            new GenericEvent(null, [
Hmm. Not sure about this one but i would pass $message as $subject to GenericEvent instead of null.

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Message.php
> +	 * @param Swift_Message
I would prefer `$swiftMessage` here but not sure if there is a strict rule about camel / snake.

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Message.php
> +	public function setSwiftMessage(Swift_Message $swift_Message) {
```suggestion
	public function setSwiftMessage(Swift_Message $swift_Message): void {
```

2019-05-21 10:50 UTC, kesselb commented on lib/private/Mail/Message.php
> +	 * @param Swift_Message
```suggestion
	 * @param Swift_Message $swift_Message
```

2019-05-21 12:40 UTC, tacruc commented on lib/private/Mail/Mailer.php
> + *
No

2019-05-21 13:13 UTC, tacruc commented on lib/private/Mail/Mailer.php
> +            new GenericEvent(null, [
Where would be the place to document the event? Or is there a list of all available events?

2019-05-21 14:01 UTC, kesselb commented on lib/private/Mail/Message.php
> +	 * @param Swift_Message
Hmm ;) I've seen both but please don't mix it :see_no_evil: 

snake_case (words are separated by _)
camelCase (a new word is indicated by a capital letter)

2019-05-21 14:02 UTC, kesselb commented on lib/private/Mail/Message.php
> +	public function setSwiftMessage(Swift_Message $swift_Message): void {
```suggestion
	public function setSwiftMessage(Swift_Message $swiftMessage): void {
```

2019-05-21 14:02 UTC, kesselb commented on lib/private/Mail/Message.php
> +	 * @param Swift_Message $swift_Message
```suggestion
	 * @param Swift_Message $swiftMessage
```

2019-05-21 14:02 UTC, kesselb commented on lib/private/Mail/Message.php
> +		$this->swiftMessage = $swift_Message;
```suggestion
		$this->swiftMessage = $swiftMessage;
```

2019-05-21 14:06 UTC, kesselb commented on lib/private/Mail/Mailer.php
> +			new GenericEvent(null, [
I think we should use `new GenericEvent($message)`. You can fetch the message later with:

```
		/** @var IMessage $message */
		$message = $event->getSubject();
```

cc @nickvergessen @rullzer your opinion :ping_pong:

2019-05-21 15:41 UTC, tacruc commented
@nextcloud/documentation Is there a place where all the available events are documented? For the available Hooks there is but I cloudn't find something for events.

2019-09-02 17:12 UTC, tacruc commented
rebased to master

2020-01-16 10:53 UTC, ChristophWurst commented
As just discussed we should

* Create a typed `\OCP\Mail\Events\BeforeMessageSent` in `lib/public/Mail/Events`
* Add `setSwiftMessage` in the internal Message class
* Use the internal class in https://github.com/tacruc/gpgmailer/blob/4f7fdee2eefcf4d56bfa393c369b7e88ca3a243f/lib/Hooks/MailHooks.php

(exposing an abstraction of Swift is a lot of work and not worth the effort here)

Example event: https://github.com/nextcloud/server/blob/master/lib/public/User/Events/BeforeUserDeletedEvent.php
Example hook to events migration: https://github.com/nextcloud/server/commit/d808f9c053fb80b0ec042f12e39f7387ca7821ca#diff-b9e7943dc8f2ede028acf951e8853ff1
The event dispatcher: https://github.com/nextcloud/server/blob/master/lib/public/EventDispatcher/IEventDispatcher.php

2020-01-20 11:13 UTC, ChristophWurst requested changes
Indentation is off in a few places. Could you check those as well?

2020-01-20 11:13 UTC, ChristophWurst commented on tests/lib/Mail/MailerTest.php
> +		$message = $this->getMockBuilder('\OC\Mail\Message')
use `$this->createMock(Message::class)` to get the mock

2020-01-20 11:13 UTC, ChristophWurst commented on tests/lib/Mail/MailerTest.php
> +			->with($this->callback(function(BeforeMessageSent $e) use ($test, $message, &$count) {
you can use

```
$event = new BeforeMessageSent($message)

...->with($this->equalTo($event))
```

2020-01-20 15:03 UTC, tacruc commented
> Indentation

Found three errors in 2 files, did I miss some place?

2020-01-28 15:42 UTC, ChristophWurst requested changes
Update `@since` tags. Otherwise fine by me :+1:

2020-01-28 15:42 UTC, ChristophWurst commented on lib/public/Mail/Events/BeforeMessageSent.php
> + * @since 18.0.0
```suggestion
 * @since 19.0.0
```

2020-01-29 14:05 UTC, ChristophWurst approved these changes

2020-03-24 20:02 UTC, rullzer approved these changes

2020-03-25 07:10 UTC, merged

2020-10-29 08:10 UTC, MorrisJobke commented
ref #14552