Retrieving shared contacts/users from database to dropdown menu
nextcloud/server pull request #14731
Opened 2019-03-17 19:57 UTC by sananirajabov

The problem is when you click users dropdown menu, first 25 users appear, to fix this problem I implemented code when you share something with user, this user then appear in dropdown menu, and there is no limit how many users will appear.

fix #5097

Signed-off-by: Sanani Rajabov sananirajabov@gmail.com

2019-03-20 11:42 UTC, ChristophWurst requested changes
> lib/private/Contacts/ContactsMenu/ContactsStore.php 100644 → 100755

please revert the permission changes

2019-03-20 11:45 UTC, ChristophWurst requested changes

2019-03-20 11:45 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +				$isLocal = $contact['isLocalSystemBook'] ?: false;
no, please revert this and the whitespace changes above

2019-03-20 11:45 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedUsers = $conn->executeQuery('SELECT DISTINCT * FROM oc_share');
:warning: this is not how we access the database. please use the query builder

2019-03-20 11:45 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$conn = \OC::$server->getDatabaseConnection();
this is not testable. please have the db connection injected via the consturctor

2019-03-20 11:47 UTC, ChristophWurst commented
I think the contacts from shares should be extracted to a new class

2019-03-25 16:49 UTC, sananirajabov commented
> I think the contacts from shares should be extracted to a new class



> I think the contacts from shares should be extracted to a new class

Thanks for your feedback, I will fix as soon as,

2019-03-27 17:25 UTC, sananirajabov commented
It is my first contribution, sorry me if I do something wrong. I am changed permission from 755 to 644, but I do not know it is commited or not.

2019-04-10 05:19 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$this->conn = \OC::$server->getDatabaseConnection();
add `IDBConnection` to the list of parameters. it will be injected.

2019-04-10 05:19 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		if ($filter != null) {
```suggestion
		if ($filter !== null) {
```

2019-04-10 05:20 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$queryBuilder = new QueryBuilder($this->conn,
`$this->conn->getQueryBuilder()`

2019-04-10 12:18 UTC, sananirajabov commented
Now I think it works well, bring shared contacts to dropdown menu and when search happens it search in whole database.

2019-04-10 17:35 UTC, sananirajabov commented
> > lib/private/Contacts/ContactsMenu/ContactsStore.php 100644 → 100755
> 
> please revert the permission changes

Permission reverted to 644

2019-04-11 05:30 UTC, ChristophWurst requested changes

2019-04-11 05:30 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedContactsQuery = $queryBuilder->selectDistinct("share_with")
this, in combination with the expensive iteration below won't scale for larger instances with thousands of shares. there should be a limit

2019-04-11 10:29 UTC, sananirajabov commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedContactsQuery = $queryBuilder->selectDistinct("share_with")
Yes you are right, Actually I had not thought about it. How about limit to 100 shared users? is it ok?

2019-04-11 11:58 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedContactsQuery = $queryBuilder->selectDistinct("share_with")
Sounds good!

2019-04-11 13:45 UTC, sananirajabov commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$sharedContactsQuery = $queryBuilder->selectDistinct("share_with")
I had to limit users to 25 entries because in the same directory Manager class limit users to 25 entries, 

$topEntries = array_slice($sortedEntries, 0, 25);

I did not want to change to 100.

2019-04-17 16:05 UTC, sananirajabov commented
Hi, I had DCO problems, and when entered details to look what is the problem I saw it is sign off problem and also offered two lines git command and I applied then DCO got successful but appeared some problem and I do not know how to solve these problems and conflicts, it shows I signed off someone's commit but I do not know how it happened. If it is possible could you help me?

2019-04-17 16:28 UTC, kesselb commented
Rebase your branch with nextcloud/server:master

2019-04-17 17:36 UTC, sananirajabov commented
> Rebase your branch with nextcloud/server:master
> 
> ![image](https://user-images.githubusercontent.com/3902676/56304607-c73c5f80-613e-11e9-95d2-04ee60c020be.png)
> 
> I usually do it with phpstorm like this. origin is https://github.com/nextcloud/server (because i have write permission to nextcloud/server). You might add a new remote to your repository "upstream" which points to https://github.com/nextcloud/server and rebase onto refs/remotes/upstream/master

Thanks a lot, I solved problem.

2019-04-17 21:04 UTC, sananirajabov commented
I did as much as I could, I could not convert to inner for loop to effective form, I tried to join tables but I could not found where all users come from. With less users in the database it is working fine but when database is getting large, it will become problem. Do I need to close pull request?

2019-09-01 13:13 UTC, gary-kim commented
@sananirajabov Are you still working on this?

2019-09-01 14:01 UTC, sananirajabov commented
> @sananirajabov Are you still working on this?

No, I am not working on this issue. I fixed issue but now it has performance issue when there are lots of records in database.

2019-09-05 10:24 UTC, rullzer commented
Master is no 18 development. If this needs to go into 17 please follow the normal backport procedures after merging.

2019-12-11 14:06 UTC, closed without merging