Add extendService method to IContainer
nextcloud/server pull request #14800
Opened 2019-03-22 08:43 UTC by Toilal

This brings Pimple container "Modifying services after definition" feature (https://pimple.symfony.com/#modifying-services-after-definition) to NextCloud API.

Close #14799

Signed-off-by: Rémi Alvergnat <remi.alvergnat@gfi.fr>

2019-03-22 08:46 UTC, kesselb commented
Sounds like a good plan. What is happening if two apps extends the same service?

2019-03-22 08:51 UTC, Toilal commented
I should try this, but I think it will apply as many decorations as defined.

2019-03-22 09:57 UTC, ChristophWurst requested changes
In general: I really like the idea. @rullzer and I have discussed related architectural issues recently and we want to clean up the app bootstrap and service registration code a bit. Because right now you don't know if other apps have been loaded already, so some services are loaded while others aren't. This is error prone.

Our current idea is to have a new interface for an app's application class that has (at least) two methods. The first one is to simple register services and aliases. The second one would run any other code that should run early in the application lifecycle. The latter is also where using this new API makes most sense as all services are registered.

We can discuss this in greater detail for Nextcloud 17 :)

2019-03-22 09:57 UTC, ChristophWurst commented on lib/public/IContainer.php
> +	 * @since 16.0.0
we're past feature freeze. this has to wait for Nextcloud 17.

2019-03-22 10:09 UTC, Toilal commented on lib/public/IContainer.php
> +	 * @since 16.0.0
Updated

2019-07-16 10:24 UTC, MorrisJobke commented
@rullzer @ChristophWurst Mind to review this one?

2019-09-15 18:38 UTC, ChristophWurst commented
On a second (or third) though I'm not so sure anymore. With this new extend feature we'd open a lot of doors for modification, like almost everywhere, but that isn't necessarily a positive thing. Instead, we should continue adding more explicit hooks/APIs to specific points in there code where we allow/accept modifications.

Hope this makes sense

Cheers :v:

2019-09-15 18:38 UTC, closed without merging