Add Developer Certificate of Origin (DCO)
nextcloud/server pull request #1481
Opened 2016-09-21 14:49 UTC by schiessle

As discussed with @karlitschek this PR adds a "Developer Certificate of Origin" (DCO) and a description how to apply it.

Basically all commits need to be signed with `signed-off-by: your name <your email address>`. `git commit -s` already does this for you.

Additionally I would add a bot which checks all commits of a PR if it contains this "signed-off-by" line.

cc @jospoortvliet to review the textual changes to CONTRIBUTING.md

2016-09-21 15:52 UTC, karlitschek commented
nice 👍

2016-09-21 16:51 UTC, FortressBuilder commented on contribute/HowToApplyALicense.md
> +If you modify a exiting file, please keep the existing license header as
s/a exiting/an existing/

2016-09-21 16:57 UTC, MariusBluem commented
:+1: I've already done this on several PRs :wink:

2016-09-21 19:37 UTC, schiessle commented on contribute/HowToApplyALicense.md
> +If you modify a exiting file, please keep the existing license header as
thanks... fixed

2016-09-21 20:04 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +run the git-commit command with the -s option.
Make that more prominent. Nobody developer really cares about the stuff above and just wants a super simple easy command.

2016-09-21 20:05 UTC, LukasReschke commented on CONTRIBUTING.md
> +Please read this document to learn how to verify the DCO: [contribute/SubmittingPullRequests.md][submittingpullrequests]
"how to verify"? This is not really telling developers "Do execute this one command" and instead telling them "Read this boring legal blah you don't care about" 😉

2016-09-21 20:06 UTC, LukasReschke requested changes

2016-09-21 20:07 UTC, LukasReschke commented
> Additionally I would add a bot which checks all commits of a PR if it contains this "signed-off-by" line.

Let's wait with the merge until this is in. See `.drone.yml` on how to do that.  Basically copy and adjust https://github.com/nextcloud/server/blob/e9780b7995b315883b205288737d00bb90dab24a/.drone.yml#L19-L28 and https://github.com/nextcloud/server/blob/e9780b7995b315883b205288737d00bb90dab24a/.drone.yml#L159

2016-09-21 20:08 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +run the git-commit command with the -s option.
Also highlight this using the code tag so that it is easily caught by somebody.

2016-09-21 20:09 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +To improve tracking of who did what, we use the "sign-off" procedure
This is not a good explanation. This is what the git commit history is for. I'd rather start with the actual reasoning that this is for.

2016-09-21 20:11 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +4. "Tested-by:" is used to indicate that the person applied the patch
Suuuuper complicated stuff above and I doubt it will ever be used as it implies rewriting the history. ;)

2016-09-21 20:16 UTC, schiessle commented on CONTRIBUTING.md
> +Please read this document to learn how to verify the DCO: [contribute/SubmittingPullRequests.md][submittingpullrequests]
It is not about just "do execute this one command" you _should_ read this boring legal blah and only "execute this one command" if you read it and agreed to it :wink:

2016-09-21 20:17 UTC, LukasReschke commented on CONTRIBUTING.md
> +Please read this document to learn how to verify the DCO: [contribute/SubmittingPullRequests.md][submittingpullrequests]
Kinda naive to assume that most of our contributors would do this *cough cough*. It's just confusing as it also contains useless stuff like "Oh you can add also Tested-by and Yolo-Another-Line-By"  ;-)

2016-09-21 20:18 UTC, schiessle commented on contribute/SubmittingPullRequests.md
> +To improve tracking of who did what, we use the "sign-off" procedure
That's not from me. That's the from https://github.com/wking/signed-off-by and more or less the default way to do it.

But let's see what I can do.

2016-09-21 20:18 UTC, LukasReschke commented on CONTRIBUTING.md
> +Please read this document to learn how to verify the DCO: [contribute/SubmittingPullRequests.md][submittingpullrequests]
Sum it up to something like, "For legal reasons you should read [these](whateverlink) properly. But it boils down to: You have the right to make this contribution. Just add a `--sign-off` to your `git commit` to add this line automatically."

2016-09-21 20:21 UTC, schiessle commented on contribute/SubmittingPullRequests.md
> +run the git-commit command with the -s option.
done

2016-09-21 20:22 UTC, schiessle commented on contribute/SubmittingPullRequests.md
> +4. "Tested-by:" is used to indicate that the person applied the patch
we don't want to rewrite history... We want to use it from now on

2016-09-21 20:23 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +4. "Tested-by:" is used to indicate that the person applied the patch
Yes. But NOBODY will use `Tested-by` or`Acked-by` and so on after a PR has been reviewed (as it requires rewriting the branch history). 

This is superfluos information that just confuses user. See https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work on how to make it smaller.

2016-09-21 20:26 UTC, schiessle commented on contribute/SubmittingPullRequests.md
> +4. "Tested-by:" is used to indicate that the person applied the patch
That's just a "you can if you want". if nobody want to... fine. Anyway I just removed it. I don't care about it. It doesn't hurt if someone add extra tags but it also doesn't hurt if we don't mention it.

2016-09-21 20:33 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +contributions).  This line can be automatically added by git if you
Not a fan of that. But well… whatever…

2016-09-21 20:36 UTC, LukasReschke commented on contribute/SubmittingPullRequests.md
> +contributions).  This line can be automatically added by git if you
Note that with the ownCloud CLA you can easily commit anonymous or with pseudonyms by just stating the contribution to be MIT licensed.

2016-09-21 20:51 UTC, schiessle commented on contribute/SubmittingPullRequests.md
> +contributions).  This line can be automatically added by git if you
If you want to have something legally valid you need a real name. A "yes I have the right to give it to you under the AGPL" by Mickey Mouse doesn't make any sense

2016-09-21 21:08 UTC, schiessle commented
Simplified as much as possible. Yes, this adds some additional overhead for contributors. But the overhead is quite small and it improves the legal certainty, that's why we want to have it.

2016-09-21 21:09 UTC, LukasReschke commented
Fair enough. No idea about it to be honest but let me add a CI entry.

That said:

👎, your commit doesn't include the DCO.

2016-09-21 21:14 UTC, schiessle commented
>  but let me add a CI entry.

Thanks!

> your commit doesn't include the DCO. :wink: 

At the moment the contributor guidelines doesn't say that it have to... Anyway, just for Lukasli... :wink: ￼

2016-09-21 23:22 UTC, LukasReschke commented
👍 , added the checker to drone

2016-09-21 23:23 UTC, LukasReschke approved these changes

2016-09-22 08:55 UTC, merged

2016-09-26 23:07 UTC, blizzz commented
> Yes, this adds some additional overhead for contributors. But the overhead is quite small and it improves the legal certainty, that's why we want to have it.

Isn't the overhead that you as contributor need to verify whether you hurt a random patent?

2016-09-28 23:01 UTC, oparoz commented
FYI, there is zero overhead with the new PHPStorm. Just tick the box and your commits are signed.

2016-09-29 11:16 UTC, blizzz commented
Adding the -s to git commit is easily possible in multiple ways, but this is not my concern. It's a legal-related question.

2016-09-29 11:22 UTC, oparoz commented
Sorry, I wasn't replying to you directly. I just wanted to mention that it's now easily possible to do without having to create aliases and use alternative git commands :)