Use name from theme when downloading/printing twofactor backup codes.
nextcloud/server pull request #14829
Opened 2019-03-25 09:53 UTC by fancycode

This helps for people that have twofactor backup codes from different portals (with different names).

2019-03-25 10:54 UTC, ChristophWurst requested changes
Cool!

2019-03-25 10:54 UTC, ChristophWurst commented on apps/twofactor_backupcodes/src/views/PersonalSettings.vue
> +					   download="{{ t('twofactor_backupcodes', '{name}-backup-codes.txt', {name}) }}">{{ t('twofactor_backupcodes', 'Save backup codes') }}</a>
let's just use string concatenation, otherwise translators will come up with fancy file names :wink:

2019-03-26 15:04 UTC, fancycode commented on apps/twofactor_backupcodes/src/views/PersonalSettings.vue
> +					   download="{{ t('twofactor_backupcodes', '{name}-backup-codes.txt', {name}) }}">{{ t('twofactor_backupcodes', 'Save backup codes') }}</a>
Changed in a separate commit, you might want to squash before merging.

2019-03-26 15:47 UTC, ChristophWurst approved these changes
Looks good!

I rebased & squashed

2019-03-27 15:59 UTC, juliusknorr approved these changes

2019-03-27 16:00 UTC, juliushaertl commented
Drone restarted.

2019-03-27 18:59 UTC, merged