Return 404 on v2.php when the app is disabled
nextcloud/server pull request #1489
Opened 2016-09-22 10:20 UTC by nickvergessen

Noticed when testing https://github.com/nextcloud/notifications/pull/23

Not found should obviously return with "404" and not with "500"

2016-09-22 10:29 UTC, schiessle commented
looks ok :+1:

2016-09-22 14:15 UTC, MorrisJobke commented on lib/private/legacy/ocs.php
> +		OC_API::respond(new OC_OCS_Result(null, API::RESPOND_NOT_FOUND, $txt), $format);
Really? Should it not be a Method not allowed response? Because the endpoint is not found and not the actual entity.

2016-09-22 14:15 UTC, MorrisJobke requested changes

2016-09-22 14:51 UTC, nickvergessen commented on lib/private/legacy/ocs.php
> +		OC_API::respond(new OC_OCS_Result(null, API::RESPOND_NOT_FOUND, $txt), $format);
That OCS code does not exist...

2016-09-26 12:00 UTC, nickvergessen commented
@MorrisJobke can we move this forward?

2016-09-27 09:02 UTC, MorrisJobke approved these changes

2016-09-27 09:02 UTC, MorrisJobke commented
:+1:

2016-09-27 09:04 UTC, merged