Allow to search for real pattern in contacts
nextcloud/server pull request #14954
Opened 2019-04-03 22:17 UTC by tacruc

This is a fix of the issues in PR #7929

at the moment the patterns get escaped while creating the SQL Query this removes the possibility to use the wildcards _%. With this PR there would be an $option to disable this behavior.

2019-05-14 12:33 UTC, georgehrke commented on apps/dav/lib/CardDAV/AddressBookImpl.php
> +	 * 	- 'no-escape-_%' - If set to true wildcards _ and % are not escaped
Could we maybe have some name that's better to remember and easier to type please. 

Something like "escape" that defaults to true.

2019-05-14 12:35 UTC, georgehrke requested changes

2019-05-14 12:35 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				$query2->andWhere($query2->expr()->ilike('cp.value', $query->createNamedParameter($pattern)));
This basically removes any kind of sanitisation, making this call vulnerable to SQL injections.
Especially as pattern will most likely be derived from some user input.

2019-05-14 12:42 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				$query2->andWhere($query2->expr()->ilike('cp.value', $query->createNamedParameter($pattern)));
Nevermind, my bad. Whatever is in `$pattern` will still be escaped by `createNamedParameter`.

2019-05-14 12:47 UTC, georgehrke commented
This looks good to me once the option was renamed

2019-05-15 15:24 UTC, ChristophWurst reviewed
Yep, please rename the option. Otherwise the change is fine :+1:

2019-05-15 15:24 UTC, ChristophWurst commented on apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
> +		$vCards[2]->add(new Text($vCards[2], 'CLOUD', 'peter_pan@owncloud.org'));
*cough* Nextcloud *cough*

2019-05-16 06:47 UTC, tacruc commented
@georgehrke, @rullzer thx, for the review I will have time on the weekend to update.

2019-05-23 10:34 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			if(\array_key_exists('escape_like_param', $options) && $options['escape_like_param'] === true) {
```suggestion
			if(\array_key_exists('escape_like_param', $options) && $options['escape_like_param'] === false) {
```

2019-05-27 09:26 UTC, georgehrke commented
It looks like you accidentally updated `3rdparty`. Can you please revert that and [squash your commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing)?

Then we can merge :)

2019-05-29 11:19 UTC, georgehrke approved these changes
Good to go 👍

2019-05-29 12:07 UTC, ChristophWurst approved these changes

2019-05-29 12:18 UTC, tacruc commented
@georgehrke  and @ChristophWurst  thanks for the constructive review.

2019-07-17 20:11 UTC, tacruc commented
What has to be done for the merge?

2019-07-19 16:03 UTC, MorrisJobke approved these changes

2019-07-19 16:03 UTC, merged