[stable9] Add repair step and revert "Open updater" button
nextcloud/server pull request #1501
Opened 2016-09-23 12:11 UTC by MorrisJobke

* backport of #1499 to stable9
* fixes both items in #1485
* repair step moves the update step file `data/updater-INSTANCEID/.step` to a file named `.step-previous-update` to not show all steps as done on the next update
* reverts  202ae42

cc @LukasReschke @nickvergessen @karlitschek

2016-09-23 12:26 UTC, MorrisJobke commented
stable9 doesn't need the fixed from stable10 and master: https://github.com/nextcloud/server/blob/stable9/lib/public/util.php#L83 (there the channel is already set in the config.php

2016-09-23 12:29 UTC, karlitschek commented
:+1:

2016-09-26 09:50 UTC, nickvergessen commented
Worked 👍

2016-09-26 09:56 UTC, LukasReschke commented on apps/updatenotification/templates/admin.php
> +		<?php if($updaterRequirementsFulfilled === true): ?>
Shouldn't we remove that as well now? :)

2016-09-26 09:56 UTC, LukasReschke requested changes

2016-09-26 10:03 UTC, nickvergessen commented on apps/updatenotification/templates/admin.php
> +		<?php if($updaterRequirementsFulfilled === true): ?>
Comment on master only?

2016-09-26 11:50 UTC, MorrisJobke commented on apps/updatenotification/templates/admin.php
> +		<?php if($updaterRequirementsFulfilled === true): ?>
Correct. This is also not on master. (no idea how this came in here)

2016-09-26 12:44 UTC, MorrisJobke commented on apps/updatenotification/templates/admin.php
> +		<?php if($updaterRequirementsFulfilled === true): ?>
Ah gotcha ... it was only added in stable9.

2016-09-26 14:55 UTC, MorrisJobke commented on apps/updatenotification/templates/admin.php
> +		<?php if($updaterRequirementsFulfilled === true): ?>
I fixed this.

2016-09-26 20:29 UTC, LukasReschke commented
LGTM

2016-09-26 20:29 UTC, LukasReschke approved these changes

2016-09-26 20:29 UTC, merged