Replace OC.Notification with toastify js
nextcloud/server pull request #15124
Opened 2019-04-16 10:02 UTC by juliushaertl

This is a PoC pull request for https://github.com/nextcloud/server/issues/13423 to make error messages that are sent though OC.Notification more obvious and visually appealing.

![image](https://user-images.githubusercontent.com/3404133/56199945-2bc3c580-603e-11e9-8de0-072d9fe26397.png)

Feedback is welcome @nextcloud/designers 

Note that the current OC.Notification.show OC.Notification.showTemporary continue to work, but the toastify lib adds additional types (error,warning,success,info) to give a visual hint about the type of message.

2019-04-16 12:08 UTC, rullzer commented
So the design team has to decide of course. But I'm not 100% convinced having it on the bottom is the best. All our notifications etc are on the top so that is where people look. Maybe adding it just blow the header makes more sense?

2019-04-16 12:08 UTC, rullzer commented
Of course visually this looks a lot better than the 1990 style we had before.

2019-04-16 12:16 UTC, stefan-niedermann commented
I think it is hard to distinguish from the other content. Maybe use a contrast color (white on dark background on normal, and dark on white background on dark theme)?

2019-04-16 12:28 UTC, MorrisJobke commented
> So the design team has to decide of course. But I'm not 100% convinced having it on the bottom is the best. All our notifications etc are on the top so that is where people look. Maybe adding it just blow the header makes more sense?

See the last open checkbox ;) It should be moved to the top right.

2019-04-16 13:31 UTC, juliushaertl commented
> I think it is hard to distinguish from the other content. Maybe use a contrast color (white on dark background on normal, and dark on white background on dark theme)?

A full colored background is a bit to much I think, but I've increased the box shadow visibility a bit (see the updated screenshot in the first post)

> So the design team has to decide of course. But I'm not 100% convinced having it on the bottom is the best. All our notifications etc are on the top so that is where people look. Maybe adding it just blow the header makes more sense?

Done :wink:

2019-04-16 13:58 UTC, jancborchardt commented
Top right is indeed much better, that’s where all the "meta / organizational" stuff is. :)

And it looks really really nice! Props @juliushaertl! The only thing I can find is that the x icon is not our `.icon-close` icon – any reason for that?

2019-04-16 13:59 UTC, juliushaertl commented
> And it looks really really nice! Props @juliushaertl! The only thing I can find is that the x icon is not our .icon-close icon – any reason for that?

No reason, I can adjust that as well.

2019-04-16 14:25 UTC, juliushaertl commented
@jancborchardt Thanks for the hint, pushed with the proper close icon 
![image](https://user-images.githubusercontent.com/3404133/56217859-36915100-6064-11e9-804c-36a3c0f4a3fc.png)

2019-04-16 14:40 UTC, skjnldsv commented on core/src/OC/notification.js
> +		options = options || {}
Shall we deprecate in favour of OCP.Toast?

2019-04-16 14:44 UTC, skjnldsv requested changes
Having the mouse over the notification should prevent it from disappearing I think. If you're reading something long and it disappear, you're confused :)

2019-04-16 14:47 UTC, juliushaertl commented on core/src/OC/notification.js
> +		options = options || {}
Ah yes, good point. :+1: Notification was always a bit confusing with the notifications app :wink:

2019-04-16 14:47 UTC, juliushaertl commented
> Having the mouse over the notification should prevent it from disappearing I think. If you're reading something long and it disappear, you're confused :)

I'll see, but we probably need to fix that upstream.

2019-04-17 17:28 UTC, BrookeDot commented
> Having the mouse over the notification should prevent it from disappearing I think. If you're reading something long and it disappear, you're confused :)

I agree, I struggle from a bit of dyslexia and often find myself highlighting text to help me read it and sometimes reading takes a bit longer than "average". Having a notification disappear while reading it can be quite frustrating. Especially if there's not an easy way to get it back. 

> I'll see, but we probably need to fix that upstream.

I have opened up https://github.com/apvarun/toastify-js/issues/21  upstream so we'll see if this feature can get added. If not, perhaps I can recommend not setting the timeout at all.

2019-04-17 17:30 UTC, skjnldsv commented
@BrookeDot Thanks a lot for that! :rocket:

2019-04-18 08:10 UTC, skjnldsv commented
> I have opened up [apvarun/toastify-js#21](https://github.com/apvarun/toastify-js/issues/21) upstream so we'll see if this feature can get added. If not, perhaps I can recommend not setting the timeout at all.

Opened PR: https://github.com/apvarun/toastify-js/pull/22

2019-04-24 07:30 UTC, karlitschek commented
I like it. Looks more modern

2019-04-30 08:17 UTC, juliushaertl commented
I deprecated the old OC.Notification API, should we get this in for now? We can update the dependency later once https://github.com/apvarun/toastify-js/pull/22 is merged.

2019-04-30 08:38 UTC, rullzer commented
@juliushaertl yes lets get it in and then update later :+1: else we keep rebasing etc.

2019-04-30 08:46 UTC, skjnldsv commented
Agreed!
![tumblr_mq00lsWsTd1stru2ro6_250](https://user-images.githubusercontent.com/14975046/56950209-351c5a00-6b35-11e9-9662-e21f93e62382.gif)

2019-04-30 08:46 UTC, skjnldsv approved these changes

2019-04-30 13:02 UTC, MorrisJobke commented
Conflicts 🙈

2019-04-30 13:24 UTC, juliushaertl commented
Did another rebase and removed to fixup from the commit messages.

2019-05-02 09:29 UTC, MorrisJobke approved these changes
Tested and works 👍

2019-05-02 09:30 UTC, MorrisJobke commented
@juliushaertl Mind to fix the conflicts?

2019-05-02 09:37 UTC, MorrisJobke commented
> @juliushaertl Mind to fix the conflicts?

Done.

2019-05-02 09:59 UTC, MorrisJobke commented
JSUnit failures :/

2019-05-09 06:05 UTC, rullzer commented
Need a rebase and the jsunit fixed... then we can get this in

2019-05-09 07:07 UTC, juliushaertl commented
Yep I'll look into the failing tests.

2019-05-22 11:27 UTC, juliushaertl commented
While looking at the tests, we still lack of proper backward compatibility for the `OC.Notification.hide` method. I created https://github.com/apvarun/toastify-js/pull/26 to enhance the library, so that we can have permanent toasts that can be closed as it is currently done in the OC.Notifications implementation.

2019-05-22 20:34 UTC, MorrisJobke commented
> While looking at the tests, we still lack of proper backward compatibility for the `OC.Notification.hide` method. I created [apvarun/toastify-js#26](https://github.com/apvarun/toastify-js/pull/26) to enhance the library, so that we can have permanent toasts that can be closed as it is currently done in the OC.Notifications implementation.

Do we really need that this often?

2019-05-22 20:35 UTC, MorrisJobke commented
> Do we really need that this often?

In most cases it is called to avoid that an old notification is hiding the one that should be added.

2019-05-22 20:52 UTC, juliushaertl commented
>> Do we really need that this often?
> In most cases it is called to avoid that an old notification is hiding the one that should be added.

I would also be happy with just ignoring the hide method and have a default timeout of 30s for notifications that were called without a timeout though the legacy API. 
Anything that speaks against this @nextcloud/designers ?

2019-05-28 14:13 UTC, jancborchardt commented
> I would also be happy with just ignoring the hide method and have a default timeout of 30s for notifications that were called without a timeout though the legacy API.
>  Anything that speaks against this @nextcloud/designers ?

Just to clarify: This issue does not happen when using this new notification API?

Cause a defaut timeout for notifications has a big issue in that people don’t necessarily check the screen or tab all the time, and they might miss a notification. Also, do these notifications have a close button so you can close them _before_ the 30s?

2019-06-05 13:03 UTC, juliushaertl commented
> Just to clarify: This issue does not happen when using this new notification API?

The new API has a default timeout as I would consider those notifications to be more temporary than permanent.

> Cause a defaut timeout for notifications has a big issue in that people don’t necessarily check the screen or tab all the time, and they might miss a notification. Also, do these notifications have a close button so you can close them before the 30s?

I have now also rebuild the old OC.Notifiation.hide() method, so the behavior on the old API should be complete. The only thing that has changed is the fallback if no notification to hide was provided. In that case we do nothing now, as there was a warning logged for quite some time and just removing the first notification doesn't seem to be a good fallback to me.

Let's see if the tests are happy.

2019-06-06 06:59 UTC, juliushaertl commented
:tada: Tests are happy again. @skjnldsv @ChristophWurst Mind to have another look?

2019-06-06 07:04 UTC, skjnldsv commented
Looks all good to me :D
Rebase, sign and squash! :rocket:

2019-06-07 05:36 UTC, juliushaertl commented
> Rebase, sign and squash!

Done :ship:

2019-06-07 06:24 UTC, merged

2019-07-11 15:41 UTC, danxuliu commented
@juliushaertl There is a mismatch in the options received by OC.Notification and OCP.Toast: [OC.Notification uses isHTML](https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/src/OC/notification.js#L142), while [OCP.Toast uses showHtml](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/src/OCP/toast.js#L59). Either [`OCP.Toast.message` is adjusted](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/src/OCP/toast.js#L59-L64) to use `isHTML` too, or [`OC.Notification.showTemporary` is adjusted](https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/src/OC/notification.js#L147-L149) to set `options.showHtml` based on `options.isHTML` (and also the unit tests to reflect that [`OC.Toast.message` expects `showHtml` instead of `isHTML`](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/js/tests/specs/coreSpec.js#L941)).

2019-09-27 13:32 UTC, LinneyS commented
If you scroll down the page, the message is not visible under the header

2019-09-27 13:34 UTC, ChristophWurst commented
> If you scroll down the page, the message is not visible under the header

Please open a new ticket.

2019-09-27 13:35 UTC, skjnldsv commented
Should be fixed already https://github.com/nextcloud/server/pull/17110