Fix fed share test call to return proper result
nextcloud/server pull request #1515
Opened 2016-09-26 09:18 UTC by LukasReschke

Fixes an issue where retrying a previously failed federated share would
not properly reset the availability flag because the return value was
undefined instead of "true".

Downstream of https://github.com/owncloud/core/pull/26041

2016-09-26 09:23 UTC, nickvergessen commented
👍

2016-09-26 12:00 UTC, nickvergessen commented
@MorrisJobke you also reviewed the master version: #1460

2016-09-27 20:05 UTC, MorrisJobke commented
:+1:

2016-09-27 20:05 UTC, MorrisJobke commented
* [ ] wait for 10.0.1 to be released

2016-09-28 08:22 UTC, nickvergessen requested changes
Wait for 10.0.1 release

2016-09-28 20:02 UTC, MorrisJobke approved these changes
10.0.1 is tagged

2016-09-28 20:02 UTC, merged