remove setup args from logging
nextcloud/server pull request #15308
Opened 2019-04-30 10:24 UTC by blizzz

fixes #13550

2019-04-30 10:26 UTC, ChristophWurst approved these changes

2019-04-30 10:27 UTC, rullzer approved these changes

2019-04-30 10:28 UTC, blizzz commented
/backport to stable16

2019-04-30 10:28 UTC, blizzz commented
/backport to stable15

2019-04-30 10:29 UTC, blizzz commented
/backport to stable14

2019-04-30 10:30 UTC, skjnldsv approved these changes

2019-04-30 10:31 UTC, skjnldsv commented
Thanks @blizzz :D

2019-04-30 12:00 UTC, nickvergessen commented on lib/private/Log/ExceptionSerializer.php
> +		'display',
The method names (update too), are really generic.
Would it make sense to rename the methods in the place where they are a problem?

2019-04-30 12:03 UTC, blizzz commented on lib/private/Log/ExceptionSerializer.php
> +		'display',
rather i'd take the class into consideration

2019-05-06 22:21 UTC, blizzz commented on lib/private/Log/ExceptionSerializer.php
> +		'display',
done, and still working here

2019-05-07 06:32 UTC, skjnldsv approved these changes

2019-05-07 11:19 UTC, nickvergessen requested changes
class might be undefined:
https://3v4l.org/niqG4

2019-05-07 11:19 UTC, nickvergessen commented on lib/private/Log/ExceptionSerializer.php
> +			$className = $traceLine['class'];
```suggestion
			$className = $traceLine['class'] ?? '';
```

2019-05-07 11:19 UTC, nickvergessen commented on lib/private/Log/ExceptionSerializer.php
> +			if (isset(self::methodsWithSensitiveParametersByClass[$className])
```suggestion
			if ($className && isset(self::methodsWithSensitiveParametersByClass[$className])
```

2019-05-08 10:17 UTC, nickvergessen approved these changes

2019-05-08 13:50 UTC, merged