Move change pasword settings to Vue
nextcloud/server pull request #15368
Opened 2019-05-04 03:31 UTC by listrate

I was looking at #12906 and saw that the change password section of the settings page was using JQuery. 
This change moves that section to Vue.

This change also introduces new npm packages for zxcvbn & vue-password-strength-meter so there may be some duplication as well.

2019-05-05 18:16 UTC, kesselb commented
Thank you for this contribution :tada: 

Could you compile the assets with `make build-js-production`? Also a rebease against master is required to solve the conflicts.

2019-05-06 06:31 UTC, ChristophWurst requested changes

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/components/AuthSecurityPassword.vue
> +            .catch(tap(() => this.showloader = false))
this will discard the error. `tap` does not work with errors. move the `this.showloader=false` to the other `catch` callback below

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/components/AuthSecurityPassword.vue
> +            var formParameters = {
```suggestion
            const formParameters = {
```

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/components/AuthSecurityPassword.vue
> +            var headers = {
```suggestion
            const headers = {
```

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/components/AuthSecurityPassword.vue
> +<style scoped>
remove if unused

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/main-settings-password.js
> +		tokens: OCP.InitialState.loadState('settings', 'app_tokens'),
this looks like a copy-paste leftover. Please remove the `tokens` prop data

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/main-settings-password.js
> +Vue.use(VueClipboard);
unused, remove it

2019-05-06 06:31 UTC, ChristophWurst commented on settings/src/main-settings-password.js
> +Vue.use(VTooltip);
unused, remove it

2019-05-06 06:31 UTC, ChristophWurst commented on package.json
> +    "zxcvbn": "^4.4.2"
how is this lib loaded? statically bundled or on demand? the diff doesn't tell me :)

2019-05-11 08:47 UTC, rullzer commented
@listrate thanks for this :rocket: 

Could you take care of the comments by @ChristophWurst ?

2019-05-12 04:29 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            .catch(tap(() => this.showloader = false))
Fixed!

2019-05-12 04:29 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            var formParameters = {
Fixed!

2019-05-12 04:29 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            var headers = {
Fixed!

2019-05-12 04:30 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +<style scoped>
Fixed!

2019-05-12 04:30 UTC, listrate commented on settings/src/main-settings-password.js
> +		tokens: OCP.InitialState.loadState('settings', 'app_tokens'),
Fixed!

2019-05-12 04:30 UTC, listrate commented on settings/src/main-settings-password.js
> +Vue.use(VueClipboard);
Fixed!

2019-05-12 04:30 UTC, listrate commented on settings/src/main-settings-password.js
> +Vue.use(VTooltip);
Fixed!

2019-05-12 04:34 UTC, listrate commented on package.json
> +    "zxcvbn": "^4.4.2"
Looking at the source for the vue-password-strength-meter component, zxcvbn is imported using an import statement so I guess it isn't being lazy loaded.

2019-05-13 06:45 UTC, ChristophWurst commented on package.json
> +    "zxcvbn": "^4.4.2"
It's actually not loaded by the strength meter but Nextcloud server (legacy code). 

* Proof that the lib does not load zxcvbn: https://github.com/apertureless/vue-password-strength-meter/issues/20#issuecomment-410437779
* Our version: https://github.com/nextcloud/server/blob/master/core/vendor/zxcvbn/dist/zxcvbn.js
* Where it's loaded: https://github.com/nextcloud/server/blob/8dd54fe64c181d6feb29e09c8c1371aba32ff9df/settings/js/security_password.js#L74

So, could you add an async webpack import for zxcvbn in your new Vue component?

2019-05-13 06:46 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            scoreMessages: ['Very weak password',
Translation?

2019-05-13 06:46 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +        {
inline bracket

2019-05-20 08:28 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +        {
Fixed!

2019-05-20 08:28 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            scoreMessages: ['Very weak password',
Fixed!

2019-05-20 08:39 UTC, listrate commented on package.json
> +    "zxcvbn": "^4.4.2"
I'm not sure if completely understand. I thought that zxcvbn was resolved via webpack and the duplicate zxcvbn package i added in packages.json and not via the security.php file in the templates folder as I removed that and replaced it with the vue js

https://github.com/listrate/server/blob/729b050d70bebe9ad2a1faf94305d9b3a0570459/settings/templates/settings/personal/security.php#L29-L31

I did try to load zxcvbn dynamically via the `OC.linkTo` function and while I did have some success with that when running with npm run dev I saw that the webpack build failed when running npm run build / make build-js-production.

So I have modified the webpack.js to point to the zxcvbn.js file in vendor folder and removed zxcvbn from packages.json.

https://github.com/listrate/server/blob/729b050d70bebe9ad2a1faf94305d9b3a0570459/settings/webpack.js#L49-L52

Let me know if there is a better way to do this.

2019-05-20 08:48 UTC, skjnldsv approved these changes
Very nice work!
Some fixes to do, I left some comments :)

I'll try to soon add eslint to the webpack vue files compilation step.
I'll be easier to have a proper syntax ;)

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +			<form id="passwordform" v-on:submit.prevent>
use shortand `@submit.prevent`.
Also missing a handler, we shout trigger the password change/check on submit as well ? :)

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                    v-bind:placeholder="t('settings','Current password')"
shortand `:placeholder`

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                <v-popover trigger="manual" :open="isOpen" offset="3" :auto-hide="false">
PascaleCase

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                            v-bind:placeholder="t('settings','New password')"
shortand `:placeholder`

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                        <password v-model="newpass" strengthMeterClass = "strengthMeterClass"
`:value` is more appropriate than v-model if you don't use the two-way binding :)

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +				<button id="passwordbutton" v-on:click="changePassword()" :disabled="showloader == true">{{t('settings','Change password')}}</button>
- `@click` shortand :)
- also don't use  `==`, either `===` or just `:disabled="showloader"`

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                <span v-if="showloader" class='password-loading icon icon-loading-small-dark password-state'></span>
`icon-loading-small-dark` is made to be over dark backgrounds.
Did you  meant to use the default loader: `icon-loading-small` ? :)

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +		cb(val);
weird indent

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +    name: "AuthSecurityPassword",
single quotes please

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            baseurl: OC.generateUrl('/settings/personal/changepassword'),
@ChristophWurst any opinion on using this from `nextcloud-server` instead of window.OC?

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                ]
indent

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            return this.newpass != '';
`!==`

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            if (this.oldpass == this.newpass || this.newpass == '')
`===`

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            return Axios.post(this.baseurl,formParameters,{headers: headers}).then(
space after colon ;)

2019-05-20 08:48 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
I don't really understand what `tap` is doing, could you detail a bit? :)

2019-05-20 08:48 UTC, skjnldsv requested changes
I meant to request changes, sorry :)

2019-05-20 09:20 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +			<form id="passwordform" v-on:submit.prevent>
Fixed!

2019-05-20 09:20 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                    v-bind:placeholder="t('settings','Current password')"
Fixed!

2019-05-20 09:21 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                <v-popover trigger="manual" :open="isOpen" offset="3" :auto-hide="false">
Fixed!

2019-05-20 09:21 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                            v-bind:placeholder="t('settings','New password')"
Fixed!

2019-05-20 09:21 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                        <password v-model="newpass" strengthMeterClass = "strengthMeterClass"
Fixed!

2019-05-20 09:21 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +				<button id="passwordbutton" v-on:click="changePassword()" :disabled="showloader == true">{{t('settings','Change password')}}</button>
Fixed!

2019-05-20 09:22 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                <span v-if="showloader" class='password-loading icon icon-loading-small-dark password-state'></span>
I was just following what the previous jQuery was doing

https://github.com/nextcloud/server/blob/8dd54fe64c181d6feb29e09c8c1371aba32ff9df/settings/js/security_password.js#L32-L34


but I have changed it now to icon-loading-small

2019-05-20 09:22 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +		cb(val);
Fixed!

2019-05-20 09:22 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +    name: "AuthSecurityPassword",
Fixed!

2019-05-20 09:23 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +                ]
Fixed??

2019-05-20 09:23 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            return this.newpass != '';
Fixed!

2019-05-20 09:23 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            if (this.oldpass == this.newpass || this.newpass == '')
Fixed!

2019-05-20 09:23 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            return Axios.post(this.baseurl,formParameters,{headers: headers}).then(
Fixed!

2019-05-20 09:25 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
I am not sure to be honest. I'm new to Javascript in general. I was following what was there in another component. Do let me know if I don't need it though. :)

2019-05-20 09:37 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
Where did you found the original tap function then? So I can take a look :)

2019-05-20 09:41 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
I saw it in the AuthTokenSection component 

https://github.com/nextcloud/server/blob/8dd54fe64c181d6feb29e09c8c1371aba32ff9df/settings/src/components/AuthTokenSection.vue#L40-L46

https://github.com/nextcloud/server/blob/8dd54fe64c181d6feb29e09c8c1371aba32ff9df/settings/src/components/AuthTokenSection.vue#L72-L80

2019-05-20 09:49 UTC, skjnldsv requested changes

2019-05-20 09:49 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                        <password :value="newpass" strengthMeterClass = "strengthMeterClass"
no spaces around `=`
And no PascalCase in attributes (vue will automatically convert the data to match the prop) ;)

```suggestion
                        <password :value="newpass" strength-meter-class="strengthMeterClass" 
```

2019-05-20 09:49 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +			<form id="passwordform" @submit.prevent>
Still no handler :)
```suggestion
			<form id="passwordform" @submit.prevent="changePassword">
```

2019-05-20 09:49 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +				<button id="passwordbutton" @click="changePassword()" :disabled="showloader === true">{{t('settings','Change password')}}</button>
You need to pass the function as a reference and not execute it here.
Otherwise it will not work.

```suggestion
				<button id="passwordbutton" @click="changePassword" :disabled="showloader === true">{{ t('settings', 'Change password') }}</button>
```

2019-05-20 09:49 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +                        <p>{{ scoreMessage() }}</p>
`scoreMessages` is a variable, not a function.
```suggestion
                        <p>{{ scoreMessage }}</p>
```

2019-05-20 09:51 UTC, skjnldsv commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
Ah!
@ChristophWurst is this needed here?  :)

2019-05-20 09:55 UTC, ChristophWurst commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
it's not needed here

2019-05-20 10:35 UTC, listrate commented on settings/src/components/AuthSecurityPassword.vue
> +            .then(tap(() => this.showloader = false))
I have removed that code.

2019-05-24 17:54 UTC, rullzer commented
@ChristophWurst @skjnldsv mind to help out here for the final part to get it in?

2019-05-27 07:33 UTC, skjnldsv approved these changes
Rebase and we're good to go :)

2019-05-27 07:44 UTC, ChristophWurst commented on settings/webpack.js
> +			'zxcvbn': path.resolve(path.join(__dirname,'..','core','vendor','zxcvbn','dist','zxcvbn.js'))
on a second thought I think your first attempt was already the better one. because we don't have to load zxcvbn async for a bundle that always uses is. We should revert to the move to package.json, remove the vendored (and probably outdated) version in `core/vendor` and just bundle it with webpack.

I will have a look at how this could be possible.

2019-07-02 07:19 UTC, closed without merging

2019-07-02 07:23 UTC, ChristophWurst commented
Could not successfully update your feature branch, hence opening a new PR

2019-07-02 07:47 UTC, ChristophWurst commented
Please force-push your local state again.