Integration tests qa 222
nextcloud/server pull request #1546
Opened 2016-09-27 16:37 UTC by LukasReschke

From https://github.com/owncloud/core/pull/26219

2016-09-28 18:33 UTC, MorrisJobke requested changes
Tests are failing

2016-09-28 18:33 UTC, MorrisJobke commented on build/integration/features/webdav-related.feature
> +		Then the single response should contain a property "{DAV:}quota-available-bytes" with value "600"
`Property "{DAV:}quota-available-bytes" found with value "592", expected "600" (Exception)`

2016-09-28 18:33 UTC, MorrisJobke commented on build/integration/features/webdav-related.feature
> +		Then the single response should contain a property "{DAV:}quota-available-bytes" with value "693"
`Property "{DAV:}quota-available-bytes" found with value "685", expected "693" (Exception)`

2016-09-29 12:28 UTC, nickvergessen commented on build/integration/features/webdav-related.feature
> +		Then the single response should contain a property "{DAV:}quota-available-bytes" with value "600"
I guess it's because of welcome.txt which has a different size on our end

2016-09-29 12:28 UTC, nickvergessen commented on build/integration/features/webdav-related.feature
> +		Then the single response should contain a property "{DAV:}quota-available-bytes" with value "600"
https://help.nextcloud.com/t/which-tls-config-is-supported-by-the-clients/3708

2016-10-02 19:16 UTC, rullzer commented on build/integration/features/webdav-related.feature
> +		Then the single response should contain a property "{DAV:}quota-available-bytes" with value "600"
Yep it is because Nextcloud has a letter more than ownCloud

2016-10-03 10:07 UTC, MorrisJobke approved these changes

2016-10-03 10:07 UTC, MorrisJobke approved these changes

2016-10-03 10:07 UTC, MorrisJobke commented
:+1:

2016-10-03 10:41 UTC, merged

2016-10-03 10:43 UTC, MorrisJobke commented
signed off check failed ;)