[stable10] Change the minimum log level to fatal (#26213)
nextcloud/server pull request #1548
Opened 2016-09-27 16:41 UTC by LukasReschke

From https://github.com/owncloud/core/pull/26215, backport of https://github.com/nextcloud/server/pull/1523

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

2016-09-27 20:06 UTC, MorrisJobke commented
:+1:

2016-09-28 08:21 UTC, nickvergessen commented
👍

2016-09-28 08:21 UTC, nickvergessen requested changes
Wait for 10.0.1 release

2016-09-28 20:01 UTC, MorrisJobke approved these changes

2016-09-28 20:01 UTC, merged