Remove quota feedback if no link set
nextcloud/server pull request #15651
Opened 2019-05-21 08:51 UTC by skjnldsv

Fix #11635

2019-05-21 09:07 UTC, ChristophWurst requested changes
Even small diffs can have typos

2019-05-21 09:07 UTC, ChristophWurst commented on apps/files/css/files.scss
> +		// if no ink is set, no mouse feedback
```suggestion
		// if no link is set, no mouse feedback
```

2019-05-21 09:51 UTC, ChristophWurst approved these changes

2019-05-21 19:02 UTC, MorrisJobke approved these changes
Tested and works 👍

2019-05-21 19:03 UTC, merged

2019-05-21 19:03 UTC, MorrisJobke commented
/backport to stable16

2019-05-22 13:27 UTC, jancborchardt commented
Good stuff! :) I’m just wondering if removing the interface feedback of the link will not still make it confusing for screenreader users as it’s an empty link? I would have thought it should be removed in the PHP/JS already. But cc @nextcloud/accessibility for input. :)