Make it possible to show admin settings for sub admins
nextcloud/server pull request #15679
Opened 2019-05-22 08:54 UTC by ChristophWurst

Todo
- [x] Add tagging interface for sub admin settings
- [x] Add a new annotation to mark controller routes as accessible for admin and sub admins only
- [x] Filter admin settings if the user is not an admin but sub admin
- [ ] Adjust all the failing tests

Follow-up (or here, if change is small)
- [ ] Do not show empty sections

cc @blizzz for the settings logic
cc @rullzer for the security-related changes

---

On a side note: the `CommonSettingsTrait` should be an abstract base class of the personal and admin settings controllers. That would enforce the private (later protected) properties to be initialized via the constructor. Right now it's fine if you are careful, but IMO the trait is not the best option here.

2019-05-22 12:54 UTC, ChristophWurst commented
>     * Do not show empty sections

This is similar to https://github.com/nextcloud/server/pull/15638. @juliushaertl what is the trick to hide empty sections? Does that only work for personal ones?

2019-05-22 13:02 UTC, juliushaertl commented
> This is similar to #15638. @juliushaertl what is the trick to hide empty sections? Does that only work for personal ones?

If the getSection() method of your `ISettings` implementation returns null it will not be added. This should work for admin settings as well, as if no ISetting object is added to the list, the section will not be shown.

2019-05-23 07:03 UTC, ChristophWurst commented
Thanks @juliushaertl. This trick works for all app setting sections, but apparently not for the four built-in ones. Let me see if I can find an alternative.

2019-05-23 18:20 UTC, rullzer requested changes
Works as advertised!

2019-05-23 18:20 UTC, rullzer commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +			if($this->reflector->hasAnnotation('SubAdminRequired')
Awesome :D

2019-05-24 13:34 UTC, MorrisJobke approved these changes
Tested it and it works really nice 👍

2019-05-24 13:37 UTC, rullzer approved these changes

2019-05-24 13:37 UTC, merged

2019-05-24 13:56 UTC, blizzz commented
> cc @blizzz for the settings logic

:rocket: