Add event dispatcher to OCP
nextcloud/server pull request #15777
Opened 2019-05-28 17:48 UTC by ChristophWurst

2019-05-28 17:58 UTC, rullzer requested changes

2019-05-28 17:58 UTC, rullzer commented on lib/public/EventDispatcher/LazyEventListener.php
> +			$this->service = $this->container->query($this->class);
Catch and log?

2019-05-28 17:58 UTC, rullzer commented on lib/public/EventDispatcher/IEventDispatcher.php
> +	public function addListener(string $eventName, callable $listener, int $priority = 0): void;
missing dispatch function

2019-05-29 08:40 UTC, ChristophWurst commented on apps/files_trashbin/lib/Storage.php
> +		EventDispatcherInterface $eventDispatcher = null,
This was a bug in the code. `EventDispatcherInterface` is injected just like before, but the code here made assumptions about the implementations.

2019-06-19 12:55 UTC, ChristophWurst commented
This should be good to go :)

2019-06-19 13:01 UTC, georgehrke commented on apps/dav/lib/HookManager.php
> +								EventDispatcherInterface $eventDispatcher) {
Tiny nitpick, but shouldn't this be IEventDispatcher coming from OCP? For consistencies sake.

Like:
```
interface IEventDispatcher extends EventDispatcherInterface {}
```

2019-06-19 13:06 UTC, ChristophWurst commented on apps/dav/lib/HookManager.php
> +								EventDispatcherInterface $eventDispatcher) {
Yes, eventually all usages of `EventDispatcherInterface` should be changed to `IEventDispatcher`, but I kind of wanted to show that the Symfony adapter works, without which a lot of code would break.

About `interface IEventDispatcher extends EventDispatcherInterface {}` I'm not sure because it would mean that we inherit the Symfony methods but I'd like to keep the API as minimal as possible for future modifications.

2019-06-24 19:54 UTC, rullzer approved these changes

2019-06-24 19:55 UTC, georgehrke approved these changes

2019-06-25 07:43 UTC, rullzer commented
Failing tests!

2019-06-25 09:48 UTC, merged