Add new Provider interface for preview providers
nextcloud/server pull request #15870
Opened 2019-06-04 13:31 UTC by icewind1991

the main difference is passing the `File` object to the provider
instead of a `View` + path

Old providers will still continue to work as before, all builtin providers have been updated and received some cleanup in their temp/local file handling

The motivation for finally changing this is that the `View` + path doesn't provide enough flexibility to generate the correct previews for storage provided versions

2019-06-13 15:24 UTC, ChristophWurst reviewed
Looks good!

2019-06-13 15:24 UTC, ChristophWurst commented on lib/private/Preview/GeneratorHelper.php
> +			$provider = new ProviderV1Adapter($provider);
nice!

2019-06-13 15:24 UTC, ChristophWurst commented on lib/public/Preview/IProviderV2.php
> +	public function getMimeType();
return type hint would be great :wink:

2019-06-13 15:24 UTC, ChristophWurst commented on lib/public/Preview/IProviderV2.php
> +	public function isAvailable(FileInfo $file);
same

2019-06-13 15:24 UTC, ChristophWurst commented on lib/public/Preview/IProviderV2.php
> +	 * @return bool|\OCP\IImage false if no preview was generated
how about returning `null` instead of `false`? Then a return type could be specified

2019-06-13 15:27 UTC, juliushaertl commented on lib/private/Preview/ProviderV2.php
> +	protected function getLocalFile(File $file, int $maxSize = null): string {
:tada:

2019-06-13 15:29 UTC, juliusknorr requested changes

2019-06-13 15:29 UTC, juliushaertl commented on lib/private/Preview/SVG.php
> +			$content = stream_get_contents($file->fopen('r'));
This should probably also use $this->getLocalFile()

2019-06-13 15:29 UTC, juliushaertl commented on lib/private/Preview/ProviderV2.php
> +				$content = stream_get_contents($content, 5242880);
Should be $maxSize instead of the `5242880`

2019-06-13 20:12 UTC, icewind1991 commented on lib/private/Preview/SVG.php
> +			$content = stream_get_contents($file->fopen('r'));
shouldn't make a difference here, local files are only useful if the generator require a local path to work with

2019-06-13 20:16 UTC, icewind1991 commented on lib/private/Preview/ProviderV2.php
> +				$content = stream_get_contents($content, 5242880);
fixed

2019-06-13 20:16 UTC, icewind1991 commented
added type hints

2019-06-19 13:10 UTC, ChristophWurst approved these changes

2019-06-25 13:04 UTC, rullzer approved these changes
Lets do this!

2019-06-25 13:05 UTC, merged

2019-07-03 09:59 UTC, skjnldsv commented
It broke master!
Let me fix :)