adding toggle password to be able to see it when login
nextcloud/server pull request #15881
Opened 2019-06-05 12:45 UTC by PhieF

Hi

Here is a preview of what it does

![Capture d’écran de 2019-06-05 14-42-51](https://user-images.githubusercontent.com/26841885/58957253-88bb3c80-87a0-11e9-9d69-3d7bdf83be2f.png)

![Capture d’écran de 2019-06-05 14-42-57](https://user-images.githubusercontent.com/26841885/58957258-8c4ec380-87a0-11e9-81ee-ad05be53ccde.png)

What do you think of that ? If approved, I will also push it to registration

2019-06-05 13:17 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				<a href="#" @click="togglePassword" class="toggle-password"><img :src="OC.imagePath('core', 'actions/toggle.svg')"/></a>
@nextcloud/vue we should have input components with built-in slot to have action inline (like the reset in theming, this show password, or whatever we also use) :)

2019-06-05 13:20 UTC, skjnldsv requested changes

2019-06-05 13:20 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
I would prefer the use of a local variable like inputType and toggle it directly from there so that vue can understand the change instead of updating the dom directly :)

2019-06-05 13:20 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				<a href="#" @click="togglePassword" class="toggle-password"><img :src="OC.imagePath('core', 'actions/toggle.svg')"/></a>
```suggestion
				<a href="#" @click.stop.prevent="togglePassword" class="toggle-password">
					<img :src="OC.imagePath('core', 'actions/toggle.svg')" />
				</a>
```

2019-06-05 13:21 UTC, skjnldsv commented
Hello @PhieF !!
Thanks for your request! This is a great work :)

I commented a few nitpicks! :v:

2019-06-05 14:13 UTC, PhieF commented on core/src/components/login/LoginForm.vue
> +				<a href="#" @click="togglePassword" class="toggle-password"><img :src="OC.imagePath('core', 'actions/toggle.svg')"/></a>
To understand: you already have this kind of component ?

2019-06-05 14:14 UTC, PhieF commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
ok, I don't know vue very well, thanks for this advice !

2019-06-05 14:15 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				<a href="#" @click="togglePassword" class="toggle-password"><img :src="OC.imagePath('core', 'actions/toggle.svg')"/></a>
@PhieF no, but I think it would be nice to have it in the future ;)

2019-06-05 14:16 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
Your pull request is pretty good!
Your vue skills seems good to me ;)

2019-06-05 14:30 UTC, PhieF commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
Thanks, I've commit one more, is this what you expected ?

2019-06-05 14:32 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
Yes, perfect!
You can just change the double quotes to single ones. This is considered as good practice :)

2019-06-05 14:35 UTC, PhieF commented on core/src/components/login/LoginForm.vue
> +				if(this.$refs.password.type === "password"){
Done :) !

2019-06-05 14:51 UTC, skjnldsv approved these changes
Awesome!
Please rebase and squash your commits into one and don't forget to add the compiled files as well :)

2019-06-05 15:22 UTC, PhieF commented
I guess it should be ok, I generated .js files just with a  ```make``` command, is it ok ? ```make build-js``` was creating large js files instead of single lines ones

2019-06-05 17:17 UTC, skjnldsv commented
@PhieF `make` is perfect. It create everything from scratch.
`make build-js-production` is the command to only build the js files for production, so it's ok as well :)
`make build-js` is to build the development files :)

2019-06-06 14:20 UTC, skjnldsv commented
@PhieF it seems that you did not signed off your work :)
https://github.com/nextcloud/server/pull/15881/checks?check_run_id=142407417

2019-06-06 14:23 UTC, PhieF commented
Done !

2019-06-06 14:27 UTC, skjnldsv commented
@nextcloud/designers you're up! :eyes:

2019-06-06 14:30 UTC, georgehrke approved these changes
Looks really good 👍

2019-06-11 10:57 UTC, ChristophWurst approved these changes

2019-06-11 12:22 UTC, jancborchardt requested changes
Good stuff @PhieF! Some design & accessibility issues:
- The clickable area of the toggle should be at least 44*44px as per our [design guidelines](https://nextcloud.com/design/). Ideally it reaches the full height (top & bottom) of the input field, and also all the way to the right of the input field so people don’t have to tap exactly.
- The toggle needs to have a hover&focus state (full opacity of the icon) for proper feedback on hover and keyboard focus
- The toggle is missing an aria label to describe it, like `aria-label="Show password"`
- The img needs to have an `alt=""` to define that the image is decorative (if you add the aforementioned aria label

2019-06-25 13:02 UTC, rullzer commented
@skjnldsv @ChristophWurst could you help out here to get the comments by @jancborchardt resolved so we can get this in?

2019-07-09 11:38 UTC, rullzer commented
Lets merge this and focus on the other points while polishing

2019-07-09 11:38 UTC, merged