Markdown support for app descriptions
nextcloud/server pull request #1594
Opened 2016-09-30 12:45 UTC by nickvergessen

@janis91 this should fix the markdown showing up as plaintext...

@icewind1991 your files_markdown app uses the same lib, you might be able to drop it, in case it causes problems otherwise.
@LukasReschke @MorrisJobke

2016-09-30 12:49 UTC, LukasReschke requested changes
I'll take a look later with regards to XSS.

2016-09-30 13:12 UTC, nickvergessen commented
Well the question is, which markup do we want to allow?
I guess most devs would already be happy with:

### Allowed
* **string**
* _italic_
* ``` code, and
* lists: *, 1.

### Unsafe
* Images are not what the page is designed for and are not loaded due to CSP by default, unless shipped (but then you still have a problem with app paths which you don't  know)
* Links are mostlikely the highest risk. Of course they got their use cases, and dev's can already provide links to docs which can have malicious content

2016-09-30 19:13 UTC, BernhardPosselt commented
Last time I've tried marked it was vulnerable to XSS. I've ended up with https://github.com/markdown-it/markdown-it#markdown-it which is "Safe by default"

2016-09-30 19:15 UTC, BernhardPosselt commented
I'd render links because most of the time you want to link to documentation or FAQ to get people started. 

As for images: I'd probably relax the CSP if feasable but require them to be served over HTTPS

2016-11-02 13:12 UTC, nickvergessen commented
Closing, feel free to reopen and pick up, once decisions have been made

2016-12-15 16:10 UTC, nickvergessen commented
Rebased and pushed a commit which:
* Disables rendering of quotes
* Disables images
* Disables links unless they start with `http:` or `https:`

I'd like to do this and also add it to 11, because the app store says markdown is supported and even shows it, but in the app management everything looks broken.

Please review @LukasReschke @BernhardPosselt @MorrisJobke 

@BernhardPosselt please also adjust the app store to not render quotes, images and non-http links, so the feeling is the same everywhere

2016-12-15 16:27 UTC, BernhardPosselt commented
Any reason for not rendering links, quotes and images? These things are probably the most important markdown features. What MD lib are you using?

2016-12-15 16:31 UTC, nickvergessen commented
> Any reason for not rendering links, quotes and images? 

We render links when they are http or https, but javascript, ftp, whatever are just ignored.
Quotes cause layout issues on the small page and images are violating the CSP

> What MD lib are you using?

https://github.com/nextcloud/server/pull/1594/files#diff-0a08a7565aba4405282251491979bb6b

2016-12-15 22:04 UTC, BernhardPosselt commented
I see, yeah, http and https links are currently also what we allow. Quotes should probably be fine if you adjust the styling. I don't think they appear a lot for apps. Or do you mean code blocks?

As for images: @LukasReschke not entirely happy with that behavior maybe we could also rewrite images like this to the image proxy?

2016-12-22 12:51 UTC, MorrisJobke commented
Ping @LukasReschke

2017-01-06 14:38 UTC, MorrisJobke approved these changes

2017-01-06 14:40 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-01-06 14:40 UTC, MorrisJobke commented
I rebased to retrigger the CI

2017-01-11 09:57 UTC, nickvergessen commented
Fixed the tests

2017-01-11 12:57 UTC, MorrisJobke commented
I rebased to fix the failing autoloader test

2017-01-11 15:42 UTC, MorrisJobke commented
Let me fix the failing JS unit tests.

2017-01-11 16:09 UTC, MorrisJobke commented
> Let me fix the failing JS unit tests.

Done 🎉

2017-01-13 16:27 UTC, LukasReschke requested changes
Requires some changes. Will do them myself.

2017-01-13 16:27 UTC, LukasReschke commented on settings/js/apps.js
> +		var renderer = new marked.Renderer();
I'm not really happy with having that code in the "initialize" function.  This means that if somebody somehow manages to bypass the sanitization opening the apps page would be enough to insert it into the DOM. IMO that should happen on clicking the "Show description" action.

2017-01-13 16:27 UTC, LukasReschke commented on settings/js/apps.js
> +		var renderer = new marked.Renderer();
Especially since https://github.com/chjj/marked/pull/592 is not really increasing my confidence in this library at all.

2017-01-13 16:27 UTC, LukasReschke commented on settings/js/apps.js
> +		app.description = marked(app.description.trim(), OC.Settings.Apps.markedOptions);
Not too confident in that myself. I'll also add https://github.com/cure53/DOMPurify as post-processing.

2017-01-13 17:38 UTC, LukasReschke approved these changes

2017-01-13 17:38 UTC, LukasReschke commented
Added DOMPurify at https://github.com/nextcloud/server/pull/1594/commits/b25a3b9226464103033bb06e19e5f3aa98f982d6 – ok for me now.

2017-01-13 17:47 UTC, LukasReschke commented on settings/js/apps.js
> +					'blockquote'
@nickvergessen Whitelist here what you want to have whitelisted 😉

2017-01-16 14:03 UTC, nickvergessen commented
@jancborchardt can you fix lists please? they have too much space and the order items seem to be stripped away. You can tests it by adding the following as an app description:
```
**Bold** and *Italic*

follow the [link](https://localhost)

List:
* one
* two
    + a
    + b
    + c
* thre

List2:
1. one
2. two
    1. a
    2. a
    3. a
3. thrww
```

2017-01-16 18:14 UTC, MorrisJobke commented
> @jancborchardt can you fix lists please? they have too much space and the order items seem to be stripped away. You can tests it by adding the following as an app description:

Let me try to fix this.

2017-01-17 04:22 UTC, MorrisJobke commented
I fixed it and it now looks like this:

<img width="396" alt="bildschirmfoto 2017-01-16 um 22 18 31" src="https://cloud.githubusercontent.com/assets/245432/22007666/35f03a0a-dc3a-11e6-86a4-39b4653d851a.png">

2017-01-17 04:25 UTC, MorrisJobke commented
I just added some top and bottom margin to the paragraphs:

Before:
<img width="387" alt="bildschirmfoto 2017-01-16 um 22 25 07" src="https://cloud.githubusercontent.com/assets/245432/22007717/b1a62ef2-dc3a-11e6-99e6-835a067f201d.png">

After:
<img width="434" alt="bildschirmfoto 2017-01-16 um 22 24 59" src="https://cloud.githubusercontent.com/assets/245432/22007722/b7101754-dc3a-11e6-982e-967aa9aa0e80.png">

2017-01-17 09:38 UTC, nickvergessen commented
Thanks, so ready to merge!

2017-01-17 10:09 UTC, ChristophWurst approved these changes
tested and works

2017-01-17 10:09 UTC, ChristophWurst commented
> Thanks, so ready to merge!

Go go go go! 🏎

2017-01-17 10:11 UTC, merged

2017-01-17 10:12 UTC, nickvergessen commented
I'd still like to backport this to 11, so the new fancy appstore descriptions don't appear broken in Nextcloud.

Opinions @LukasReschke @karlitschek

2017-01-17 10:14 UTC, karlitschek commented
nice. please backport