Use theme colors for text selection
nextcloud/server pull request #16037
Opened 2019-06-21 14:42 UTC by jancborchardt

Currently the text selection is just the default browser color, which is kinda similar to the Nextcloud blue so that’s why it never looked off. ;)
![theming current](https://user-images.githubusercontent.com/925062/59930427-28382a80-9443-11e9-87c3-29a77da520ae.png)

Now it looks much better when themed too. This is especially the case for text-heavy apps like Mail or Notes. :)

![selection themed](https://user-images.githubusercontent.com/925062/59930426-28382a80-9443-11e9-9fe1-737e08abc99e.png)

![selection themed 2](https://user-images.githubusercontent.com/925062/59930425-28382a80-9443-11e9-95ac-3b058f1b4c4a.png)

(Note that the selection color is not 100% the same color but it’s made a bit lighter by the browser for some reason. Just in case you check via color picker. ;)

Please review @juliushaertl @skjnldsv @korelstar

2019-06-21 15:36 UTC, korelstar approved these changes
Very nice! Unfortunately, this has no effect on the selection of the edit mode in notes, since we currently use CodeMirror, which has it's own selection construction. Preview mode works fine 👍

2019-06-22 06:49 UTC, skjnldsv approved these changes

2019-06-22 08:13 UTC, juliusknorr requested changes

2019-06-22 08:13 UTC, juliushaertl commented on core/css/styles.scss
> +	background-color: var(--color-primary);
This should be `--color-primary-element` which has a fallack for bright theming colors like white

2019-07-05 13:52 UTC, rullzer commented on core/css/styles.scss
> +	background-color: var(--color-primary);
Fixed

2019-07-05 14:18 UTC, juliusknorr approved these changes

2019-07-07 18:02 UTC, merged