Fix size of header menus
nextcloud/server pull request #16057
Opened 2019-06-24 12:17 UTC by juliushaertl

Header menus that are bigger than the screen height will now be scrollable:
![image](https://user-images.githubusercontent.com/3404133/60018048-860a8380-968a-11e9-85ed-10fbc680e693.png)

Fixes https://github.com/nextcloud/external/issues/140

The height is limited here https://github.com/nextcloud/server/blob/da7bed1aeeb8a587e6ee760107e872098f7667c4/core/css/header.scss#L91 but I think we should keep this limit since it avoids having lengthy menu bars.

2019-06-24 15:24 UTC, skjnldsv commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
This is an issue on Apple devices as the nav bar is counted in the 100vh. That's why we stopped using it :/

2019-06-24 15:26 UTC, jancborchardt commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
So this needs to be fixed? What’s the proper way to do it?

2019-06-24 15:28 UTC, skjnldsv commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
Use percent. so it depends on the size of the window height. but it's not going to work here as  the % would be relative to the header :thinking:

2019-06-24 15:47 UTC, jancborchardt commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
```suggestion
			max-height: calc(100% - #{$header-height});
```

2019-06-25 10:29 UTC, skjnldsv commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
Does it works Jan?

2019-06-27 15:16 UTC, nickvergessen requested changes
This still needs more changes, the right header menu (with the link to settings and the user list) is still having the problem.
And the normal app menu has 2 scroll bars now...

2019-07-15 20:20 UTC, MorrisJobke commented
@juliushaertl What is the status here? We are close to the beta 1. Should this go into 17 or 18?

2019-09-03 09:46 UTC, nickvergessen commented
Btw this is still a problem with the external sites app: https://github.com/nextcloud/external/issues/140

Would be nice if we can fix this (maybe for 17.0.1) and backport it to 17 and 16?

2019-10-04 18:35 UTC, juliushaertl commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
No as the 100% are calculated from the parent element (which is the popover trigger button at 50px height)

2019-10-04 18:57 UTC, juliushaertl commented
I fixed the duplicate scroll bar by using the existing scroll container. Ready to review from my side.

2019-10-04 19:03 UTC, juliushaertl commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
I have no idea besides the current approach of using at least two times the header height so we have some additional space. Doesn't look to bad to me: 
![image](https://user-images.githubusercontent.com/3404133/66232924-5425a600-e6ea-11e9-9218-17c256d1e0b5.png)

I'm open for suggestions, otherwise we should get this in to at least have some improvement for other browsers.

2019-10-04 19:11 UTC, skjnldsv commented on core/css/header.scss
> +			max-height: calc(100vh - #{$header-height});
You won't see the issue with vh on emulator or android devices.
iOS devices does not take the bottom navigation bar of the browser out of the 100vh. Meaning 100vh always include the navigation bar and therefor always scrolls because it's bigger.

2019-10-07 09:18 UTC, nickvergessen approved these changes
Fixes the issue with the external sites app now

2019-10-07 10:14 UTC, skjnldsv approved these changes
:elephant:

2019-12-07 08:48 UTC, merged