search design details
nextcloud/server pull request #1606
Opened 2016-10-01 16:16 UTC by jancborchardt

Some search design details I did a while ago. Including:
- fixing wording
- use correct styling/elements
- cut off leading slash

Please review @nextcloud/designers @nextcloud/javascript :)

2016-10-01 16:31 UTC, skjnldsv commented
👍

2016-10-01 16:45 UTC, eppfel requested changes
Actually for a user it is not transparent, why there are two different "no results" messages and it looks like a jump frame.

2016-10-01 16:45 UTC, eppfel commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
This is not substituted and will be shown as {filter} on my end.

2016-10-01 16:47 UTC, eppfel commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
<img width="420" alt="bildschirmfoto 2016-10-01 um 18 46 45" src="https://cloud.githubusercontent.com/assets/1899308/19015574/709a0d52-8807-11e6-92aa-5b6c372cd8e3.png">

2016-10-01 18:12 UTC, te-online commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
Okay, I seed, you might just need the last two parameters, maybe?
..., {filter:this._filter},  null, {'escape': false}) as in filelist.js

2016-10-04 12:28 UTC, jancborchardt commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
cc @nextcloud/javascript can you help in this regard?

2016-10-04 15:46 UTC, skjnldsv commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
@jancborchardt is this supposed to display the searched string?

2016-10-05 11:36 UTC, nickvergessen commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:this._filter}) + '</h2>');
this is undefined, will fix

2016-10-05 11:53 UTC, skjnldsv commented
@nickvergessen Thanks for the fix!

![52-12](https://cloud.githubusercontent.com/assets/14975046/19112051/f1d300ba-8b02-11e6-910c-1c3e36478d1c.png)
I don't find it really clear. Should we put some more details? Like "No search results in other folders for «tests»

2016-10-05 11:54 UTC, nickvergessen commented
It still looks like the search icon and the text are jumping down/up at 2 to 3 characters

2016-10-05 11:57 UTC, skjnldsv commented
Small question, why don't I have the same output when searching small queries?
![2016-10-05_13-57-30](https://cloud.githubusercontent.com/assets/14975046/19112161/ad8d0e5e-8b03-11e6-958d-ce1892acf750.png)

2016-10-05 12:03 UTC, eppfel commented
@nickvergessen @skjnldsv That's what I addressed in my review. One is handled in core and the other in files???

2016-10-05 12:06 UTC, skjnldsv commented
There's something strange here indeed! :)

2016-10-05 21:51 UTC, MorrisJobke commented
> There's something strange here indeed! :)

It is by intention: up to 2 charaters it only filters the current view and starting with 3 characters it also triggers a search in all other folders (parents and childs).

2016-10-05 22:03 UTC, MorrisJobke commented
@jancborchardt Could I ask you to respond to all the open questions.

2016-10-06 11:57 UTC, skjnldsv commented
@MorrisJobke Why though?

2016-10-06 15:03 UTC, jancborchardt commented
Yeah ok, that’s weird. To clarify, any search error should only have that one large line of text. Anything else is too complex for a simple search error. Will get on it.

2016-10-06 15:14 UTC, jancborchardt commented
Btw @ChristophWurst here too I would like to bold the search string like we did the folders for the mail error messages: https://github.com/nextcloud/mail/pull/57#pullrequestreview-258796

Can you help me with that?

2016-10-06 15:22 UTC, skjnldsv commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
Same here, you can use html instead of text if you want to add `<strong> `

2016-10-06 15:25 UTC, jancborchardt commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:lastQuery}) + '</h2>');
Won’t that be a problem with translators again because they often mess up the tags? I thought that was a problem cc @LukasReschke

2016-10-06 15:26 UTC, LukasReschke commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:lastQuery}) + '</h2>');
<fett>{filter}</fett>
🙈

2016-10-06 15:45 UTC, skjnldsv commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:lastQuery}) + '</h2>');
@jancborchardt 
`var error = t('core', 'No search results in other folders {tag}{filter}{endtag}', {filter:lastQuery}).replace('{tag}', '<strong>').replace('{endtag}', '</strong>');
$status.append('<h2>' + error + '</h2>');`

2016-10-06 15:46 UTC, skjnldsv commented
@jancborchardt Could we clarify the text error?
https://github.com/nextcloud/server/pull/1606#issuecomment-251653682

2016-10-06 15:50 UTC, skjnldsv commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
`find('p').html(t('files', "No entries in this folder match '{tag}{filter}{endtag}'", {filter:this._filter},  null, {'escape': false})
    .replace('{tag}', '<strong>').replace('{endtag}', '</strong>'));`

2016-10-08 14:06 UTC, jancborchardt commented on core/search/js/search.js
> +					$status.append('<h2>' + t('core', 'No search results in other folders {filter}', {filter:lastQuery}) + '</h2>');
@skjnldsv can you add that as a commit directly on this branch? You are a Nextcloud member so you should be able to do that ;)

2016-10-08 14:06 UTC, jancborchardt commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
Same here ;)

2016-10-08 16:08 UTC, skjnldsv commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
You mean `{tag}` and `{endtag}`?

2016-10-11 11:30 UTC, jancborchardt commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
@skjnldsv I meant if the solution you suggested works, you are welcome to add a commit :)

2016-10-11 12:10 UTC, skjnldsv commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
Okay, I will commit. But we need to be sure the issue you raised with the translators is fine! :)

2016-10-11 12:22 UTC, skjnldsv commented
Commit pushed @jancborchardt ! :)

2016-10-11 12:25 UTC, MorrisJobke commented on apps/files/js/filelist.js
> +						find('h2').text(t('files', "No results in this folder for {filter}", {filter:this._filter},  null, {'escape': false}));
@skjnldsv Looks good 👍

2016-10-11 12:56 UTC, jancborchardt commented
@skjnldsv cool! Did that now also fix the wording which @eppfel suggested?

(btw @skjnldsv did you set up your email locally in git? Because it doesn’t show your avatar on the commit. :)

2016-10-11 12:57 UTC, jancborchardt commented on core/search/js/search.js
> +					var error = t('core', "No search results in other folders '{tag}{filter}{endtag}'", {filter:lastQuery});
@skjnldsv »No search results in other folders **for**« so the wording which @eppfel remarked is fixed also :)

2016-10-11 13:10 UTC, skjnldsv commented on core/search/js/search.js
> +					var error = t('core', "No search results in other folders '{tag}{filter}{endtag}'", {filter:lastQuery});
👍

2016-10-11 13:11 UTC, skjnldsv commented
@eppfel Review update pls? 😄

2016-10-18 08:53 UTC, jancborchardt commented
@nickvergessen @MorrisJobke @eppfel another review please? ;)

2016-10-18 11:47 UTC, MorrisJobke commented
👍

2016-10-18 11:47 UTC, eppfel approved these changes

2016-10-18 11:47 UTC, MorrisJobke commented
Counting @eppfel approval as :+1: ;) Merge it

2016-10-18 11:48 UTC, merged