Add icons to the left sidebar on help.php
nextcloud/server pull request #16150
Opened 2019-06-28 16:03 UTC by GretaD

ref #16076

2019-07-03 06:12 UTC, ChristophWurst requested changes

2019-07-03 06:12 UTC, ChristophWurst commented on settings/templates/help.php
> +			<a class="icon-category-office"
```suggestion
			<a class="icon-category-office <?php p($_['style1']); ?>"
```

to keep the active state

2019-07-03 06:12 UTC, ChristophWurst commented on settings/templates/help.php
> +			<a class="icon-user-admin"
```suggestion
			<a class="icon-user-admin <?php p($_['style2']); ?>"
```

2019-07-03 12:49 UTC, ChristophWurst approved these changes
Please squash the commits. Otherwise this looks good :+1: :wink:

2019-07-05 13:34 UTC, rullzer approved these changes

2019-07-05 13:35 UTC, merged