Add enterprise logo
nextcloud/server pull request #16334
Opened 2019-07-10 16:18 UTC by MorrisJobke

Also set it as theming logo if the subscription is valid.

It does not overwrite existing theming, but if there is no logo set, a valid subscription is there and the theming app is enabled it will be set once.

2019-07-10 16:21 UTC, skjnldsv approved these changes
Sure!

2019-07-10 16:32 UTC, kesselb commented
Namespace does not match folder.

2019-07-10 16:33 UTC, skjnldsv commented on lib/private/Repair/NC17/SetEnterpriseLogo.php
> +namespace OC\Repair\NC16;
```suggestion
namespace OC\Repair\NC17;
```

2019-07-10 16:36 UTC, MorrisJobke commented
> Namespace does not match folder.

Fix pushed

2019-07-10 16:36 UTC, juliushaertl commented on lib/private/Repair/NC17/SetEnterpriseLogo.php
> +		if (!$this->subscriptionRegistry->delegateHasExtendedSupport()) {
Shouldn't this be delegateHasValidSubscription() ?

2019-07-10 21:47 UTC, MorrisJobke commented on lib/private/Repair/NC17/SetEnterpriseLogo.php
> +		if (!$this->subscriptionRegistry->delegateHasExtendedSupport()) {
Yes 🙈

2019-07-11 08:56 UTC, rullzer commented on lib/private/Repair/NC17/SetEnterpriseLogo.php
> +			$this->config->setAppValue('core', 'enterpriseLogoSet', 'yes');
THis is a bit misleading. The logo is not set ;) 'enterpriseLogoChecked' maybe?

2019-07-11 09:42 UTC, MorrisJobke commented on lib/private/Repair/NC17/SetEnterpriseLogo.php
> +			$this->config->setAppValue('core', 'enterpriseLogoSet', 'yes');
Makes sense 👍

2019-07-11 10:47 UTC, MorrisJobke commented
Rebased and squashed.

2019-07-11 10:55 UTC, rullzer approved these changes

2019-07-11 11:37 UTC, juliusknorr requested changes

2019-07-11 11:37 UTC, juliushaertl commented on core/img/logo/logo-enterprise.svg
> +<svg width="3.2143cm" height="2.7502cm" enable-background="new 0 0 196.6 72" version="1.1" viewBox="0 0 113.89 97.45" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w
The image should probably also be converted to a path, as currently it relies on the Open Sans font being present on the users system.

2019-07-11 13:42 UTC, MorrisJobke commented on core/img/logo/logo-enterprise.svg
> +<svg width="3.2143cm" height="2.7502cm" enable-background="new 0 0 196.6 72" version="1.1" viewBox="0 0 113.89 97.45" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w
No idea how to do this, because I don't have Illustrator nor Inkscape and would most likely mess it up. Also the "cm" instead of "px" in the document don't look too good.

cc @jospoortvliet @jancborchardt

2019-07-15 14:47 UTC, juliushaertl commented on core/img/logo/logo-enterprise.svg
> +<svg width="3.2143cm" height="2.7502cm" enable-background="new 0 0 196.6 72" version="1.1" viewBox="0 0 113.89 97.45" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w
I've converted the text to a path and pushed it. Fine by me now. Maybe @jancborchardt knows a bit more if we can properly fix the cm unit later.

2019-07-15 14:47 UTC, juliusknorr approved these changes

2019-07-15 18:31 UTC, merged