Fix filelist overlap with header ref #16076
nextcloud/server pull request #16366
Opened 2019-07-11 15:38 UTC by GretaD

ref #16076

2019-07-12 07:16 UTC, skjnldsv requested changes

2019-07-12 07:16 UTC, skjnldsv commented on core/css/styles.scss
> +	padding-top: 40px;
This seems like a far too wide css selector.
That means every table, td and th will have a padding. Yo uneed to find the css rule that only fit the filelist header :)

2019-07-12 09:35 UTC, GretaD commented on core/css/styles.scss
> +	padding-top: 40px;
oh thats the general css file, thats a stupid suggestion then. Will push the right one asap

2019-07-12 09:38 UTC, skjnldsv commented on core/css/styles.scss
> +	padding-top: 40px;
Nothing stupid here :)

2019-07-18 10:45 UTC, georgehrke commented on apps/files/css/files.scss
> +			top: $header-height + 2px;
How did you come up with the 2px here? :)

2019-07-18 10:56 UTC, GretaD commented on apps/files/css/files.scss
> +			top: $header-height + 2px;
> How did you come up with the 2px here? :)

No matter what i do, it doesnt work if I dont change this. What do you propose? Am i editing the wrong file?

2019-07-18 11:20 UTC, juliushaertl commented on apps/files/css/files.scss
> +			top: $header-height + 2px;
Just removing the 2px worked fine for me locally

2019-07-18 11:36 UTC, GretaD commented on apps/files/css/files.scss
> +			top: $header-height + 2px;
My first file is a pdf file and the next one is an image, the pdf file has borders, the image doesnt. For some reasons it looked better with 2px, but actually it doesnt now that i see carefully :) so im removing the 2px. Thanks @juliushaertl

2019-07-18 12:56 UTC, juliusknorr approved these changes

2019-07-18 12:57 UTC, juliushaertl commented on apps/files/css/files.scss
> +			top: $header-height + 2px;
You're welcome. The border around the icon is already filed as an issue in #14849

2019-07-18 13:08 UTC, georgehrke approved these changes
👍

2019-07-18 18:55 UTC, merged