Don't allow enforcing 2FA when no provider is enabled
nextcloud/server pull request #16463
Opened 2019-07-18 19:23 UTC by MorrisJobke

Resubmit of #13735

Fixes #12267

I haven't committed compiled assets yet.

cc @rummatee

2019-07-22 10:42 UTC, skjnldsv commented on settings/src/store/admin-security.js
>  	save ({commit}, ) {
This looks weird?

2019-07-22 10:42 UTC, skjnldsv commented on settings/src/store/admin-security.js
> +export default {
Much cleaner!! :+1:

2019-07-22 10:44 UTC, skjnldsv commented on settings/src/main-admin-security.js
> +store.commit('setEnforced', initialState.enforced);
This is considered bad practice to commit from a component.
You need to use actions for that.

2019-07-22 10:49 UTC, skjnldsv commented on settings/src/components/AdminTwoFactor.vue
> +			noProviderGlobally: {
You can directly use the function if you don't have a setter here.

```suggestion
			noProviderGlobally() {
				var providers = this.$store.getters.getAllApps.filter( function(app) {
					return ('two-factor-providers' in app && 'provider' in app['two-factor-providers'] && app['active'] === true);
				});
				return (providers.length === 0);
			}
```

2019-07-22 10:50 UTC, skjnldsv commented on settings/src/components/AdminTwoFactor.vue
> +			this.$store.dispatch('getAllApps');
Loading state here?

2019-07-22 10:51 UTC, skjnldsv commented on settings/src/components/AdminTwoFactor.vue
>  				loading: false,
If so maybe set it to true by default?

2019-07-22 10:51 UTC, skjnldsv requested changes
A few comments :)

2019-07-22 12:12 UTC, MorrisJobke commented
> A few comments :)

Feel free to take over - I just untangled the git history.

2021-03-30 19:39 UTC, rullzer commented
I'm going to close this due to lack of activity.
Feel free to reopen if anybody wants to continue.

2021-03-30 19:39 UTC, closed without merging