files_external: proper user user context for sharing
nextcloud/server pull request #16525
Opened 2019-07-24 09:58 UTC by juliushaertl

This will make sure we also have a proper user context for non-logged in users that access the instance though share links. Otherwise the file system setup doesn't work properly for share links, if either a $home or $user variable is configured for substitution.

Steps to reproduce:
- Configure external storage mounted to / with $user contained in the path
- Try to access file shared via link

2019-07-24 09:59 UTC, juliushaertl commented
/backport to stable16

2019-07-24 10:05 UTC, blizzz approved these changes

2019-07-24 16:19 UTC, blizzz commented
That's a good catch already. Another use case are internal shares with placeholders in the config. They also don't resolve because of the wrong replacement it seems.

2019-07-24 18:39 UTC, scanom commented
Just tested the PR, it solves partially the issues referenced. Shared files with path containing $user variable work fine, but opening then with onlyoffice still don't work (download failed). As before, without $user file opens fine.

2019-07-25 06:32 UTC, juliushaertl commented
> That's a good catch already. Another use case are internal shares with placeholders in the config. They also don't resolve because of the wrong replacement it seems.

Hm, then I think it would be better if we pass though the user id that is used to setup the storage (as it seems that it was in stable15 and before). I'll have another look.

2019-07-25 08:10 UTC, juliushaertl commented
@blizzz I've pushed another commit so we reuse the user id that is used to setup the mountpoints https://github.com/nextcloud/server/blob/1b85ef4bf2a18f7ee7bca7bcd3d7702362125d2e/lib/private/Files/Filesystem.php#L395

@scanom I don't have a only office test setup, so maybe you can give that another try. At least for collabora this works just fine now.

2019-07-25 08:32 UTC, blizzz commented
@juliushaertl let me test it today

2019-07-25 08:41 UTC, juliushaertl commented
```
TypeError: Argument 1 passed to OCA\Files_External\Config\UserContext::__construct() must implement interface OCP\IUserSession, instance of Mock_IRequest_d7497604 given, called in /drone/src/apps/files_external/tests/Config/UserPlaceholderHandlerTest.php on line 59
```

Seems the tests also need another look :thinking: Not sure why they don't run yet.

2019-07-25 10:44 UTC, kesselb commented on apps/files_external/lib/Config/UserContext.php
> +	public function setUser($user): void {
Would you mind to check the naming a bit? `$this->user` is returned later as UserId but called User here. I usually try to guess from the name if a method returns a object or an identifier.

2019-07-25 12:05 UTC, scanom commented
@juliushaertl PR working flawlessly now, checked both Onlyoffice and Collabora.

2019-07-25 13:51 UTC, blizzz commented
Issue persists for me, but it seems the issue is deeper. The wrong storage is used when looking for the file id. Still debugging.

2019-07-25 16:00 UTC, blizzz commented
> Issue persists for me, but it seems the issue is deeper. The wrong storage is used when looking for the file id. Still debugging. 

There was an adjustment on the home handler needed, could have seen it way earlier. Stupid me.

2019-07-25 16:00 UTC, blizzz approved these changes

2019-07-29 12:37 UTC, MorrisJobke approved these changes
Tested and works 👍

2019-07-29 12:37 UTC, MorrisJobke commented
CI fails :/

2019-07-29 14:16 UTC, juliushaertl commented
> TypeError: Argument 1 passed to OCA\Files_External\Config\UserContext::__construct() must implement interface OCP\IUserSession, instance of Mock_IRequest_8a9960c5 given, called in /drone/src/apps/files_external/tests/Config/UserPlaceholderHandlerTest.php on line 59

Still not sure why that happens. Could it be that phpunit is not figuring out the proper type hints since it is in the constructor parent class (UserContext)?

2019-07-30 07:31 UTC, juliushaertl commented
Tests should be fine now ... stupid typos.

2019-08-01 21:50 UTC, blizzz requested changes
my commits got lost

and I think also something of yours, @juliushaertl, because I don't get the share owning user anymore. I don't recall what the change was here and I overwrote my local copy with  this state :(

2019-08-02 06:29 UTC, juliushaertl commented
Hm, not sure what happened, because I had your commits locally as I tested them. Github still has them, let try to grab them

2019-08-02 06:40 UTC, juliushaertl commented
@blizzz Restored

2019-08-02 11:14 UTC, blizzz approved these changes

2019-08-02 12:07 UTC, merged