Modify do_action so default ctrl-click opens tab
nextcloud/server pull request #16530
Opened 2019-07-24 15:48 UTC by KnownNexus

Modify do_action to use an ID number
Use item in do_action instead of currentFile
Limit launching direct actions to one time
Use full file item instead of attr-only

2019-07-24 16:12 UTC, juliusknorr requested changes
Nice, seems to work quite well. I've commented inline, but here are some general minor issues with the code style:

- Indentation should use tabs not spaces
- Variable names should be camel case triedActionOnce
- Please remove the console.log statements (they seem to be leftovers from debugging)

2019-07-24 16:12 UTC, juliushaertl commented on apps/files/js/filelist.js
> +	    do_action: function(id) {
Maybe openAction would be a bit more clear

2019-07-24 16:12 UTC, juliushaertl commented on apps/files/js/filelist.js
> +		var attr=item.attr;
no need for an additional variable here

2019-07-24 16:12 UTC, juliushaertl commented on apps/files/js/filelist.js
> +		if(action) {
```suggestion
		if (action) {
```

2019-07-24 16:12 UTC, juliushaertl commented on apps/files/js/filelist.js
> +			$file: item,
indentation seems to be odd here

2019-07-24 16:12 UTC, juliushaertl commented on apps/files/js/filelist.js
> +			} else if (mime === 'application/vnd.oasis.opendocument.text') {
No need to limit this to the mime type of documents. This should work for all actions on files, just not for directories.

2019-07-24 16:24 UTC, KnownNexus commented on apps/files/js/filelist.js
> +			} else if (mime === 'application/vnd.oasis.opendocument.text') {
To confirm, do you want me to just replace 
`linkUrl = this.getDownloadUrl(name, path, type === 'dir');`
with
`linkUrl = this.linkTo(path) + "&editfile="+fileData.id;`
?
￼

2019-08-02 12:13 UTC, KnownNexus commented
I'm not sure what is causing the CI to fail, could someone help me figure it out?
Also i don't believe i have permission to restart the tests, is it possible restarting them could allow them to pass?

2019-08-30 12:30 UTC, davepage-mcr commented
Hi @juliushaertl can you please re-run the CI for this MR or help @KnownNexus understand why it is failing?

2019-08-30 12:39 UTC, kesselb commented
> can you please re-run the CI for this MR

Just rebase this branch to get the latest changes from master and run ci again

2019-08-30 12:41 UTC, kesselb commented on apps/files/js/filelist.js
> +		    this.triediActionOnce = false;
```suggestion
		    this.triedActionOnce = false;
```

2019-08-30 12:41 UTC, kesselb commented on apps/files/js/filelist.js
> +		    this.triediActionOnce = false;
\+ Indentation looks off

2019-08-30 12:41 UTC, kesselb commented on apps/files/js/filelist.js
> +		console.log("nextPage...");
```suggestion

```

2019-08-30 12:41 UTC, kesselb commented on apps/files/js/filelist.js
> +	    _nextPage: function(animate) {
Indentation

2019-08-30 12:41 UTC, kesselb commented on apps/files/js/filelist.js
> +		    console.log("Launching editor, params="+urlParams.editfile);
```suggestion

```

2019-08-30 12:44 UTC, kesselb commented on apps/files/js/filelist.js
> +		    console.log("openAction: no action found");
Drop console.log + else

2019-08-30 12:45 UTC, kesselb commented on apps/files/js/filelist.js
> +	    openAction: function(id) {
Please check indention for this method. 
![image](https://user-images.githubusercontent.com/3902676/64021661-c4159f00-cb34-11e9-8cda-a1ae138d2cec.png)

2019-08-30 12:46 UTC, kesselb commented on apps/files/js/filelist.js
> +		if(!this.triedActionOnce) {
![image](https://user-images.githubusercontent.com/3902676/64021718-e0194080-cb34-11e9-86ec-7e671d26cf64.png)

Please check the indentation here

2019-08-30 12:52 UTC, kesselb commented
https://github.com/nextcloud/server/blob/master/apps/files/tests/js/favoritesfilelistspec.js

This test is failing. CI uses https://github.com/nextcloud/server/blob/master/autotest-js.sh to run the jsunit tests. I guess you need node and some dependencies to run these locally.

2020-01-28 08:32 UTC, kesselb commented
Hi @KnownNexus, sorry for late reply :see_no_evil: Could you rebase the branch with the latest master?

Probably @juliushaertl or @skjnldsv know how to fix the tests.

2020-01-31 16:08 UTC, jonathanmaw commented
Hi @kesselb,

I'm @KnownNexus 's coworker. He's moved on to other things so I'm looking after this for him.

I'll have a look at these changes and see if I can understand these changes and take responsibility for them.

2020-03-26 16:00 UTC, azul commented
Hi @KnownNexus @jonathanmaw ,

Any progress on this? I have rebased your branch and fixed the indentation to only use tabs.
The branch is here:
https://github.com/azul/server/tree/open-new_tab

I'll look into the failing tests next. Please let me know if you are still working on this so we do not duplicate efforts.

2020-03-27 09:50 UTC, jonathanmaw commented
Hi Azul,

thanks for taking care of this. I would be very grateful for you to look into the tests, since I have lost access to the equipment I had previously used to work on this due to the coronavirus restrictions.

2020-04-24 08:51 UTC, juliushaertl commented
Merged with #20185

2020-04-24 08:51 UTC, closed without merging