Add proper PostLoginEvent
nextcloud/server pull request #16579
Opened 2019-07-27 10:59 UTC by rullzer

This can be used by othr mechanisms to listen for this event in a lazy
fashion.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2019-07-27 15:55 UTC, kesselb commented on lib/private/User/Events/PostLoginEvent.php
> +	private $password;
Password cannot be null.

2019-07-29 07:52 UTC, juliusknorr requested changes
I'd prefer to have the tests also check if the dispatch method is called

2019-07-29 08:37 UTC, MorrisJobke approved these changes
Fine with me 👍

2019-07-29 10:29 UTC, rullzer commented
> I'd prefer to have the tests also check if the dispatch method is called

Happy now :wink:

2019-07-29 12:06 UTC, MorrisJobke commented on .htaccess
> +ErrorDocument 404 /
🙈

2019-07-29 14:18 UTC, juliusknorr approved these changes

2019-07-29 14:31 UTC, MorrisJobke commented
Rebased and auto squashed.

2019-07-30 06:54 UTC, merged