Clean all superposed white backgrounds
nextcloud/server pull request #1657
Opened 2016-10-07 14:16 UTC by skjnldsv

In nextcloud there's too much elements with a white background. If the parent element already have a white bg, we should reapply one. This causes a lot of difficulties for themers to create their own.

The though came from my work on a dark theme. Changing the body bgcolor isn't enough.

2016-10-07 16:41 UTC, irgendwie commented on apps/files/css/files.css
> +	border-bottom: 1px solid 1px solid rgba(0,0,0,0.08);
typo? :wink:

2016-10-07 16:41 UTC, irgendwie commented on core/css/apps.css
> +	border-left: 1px solid 1px solid rgba(0,0,0,0.08)
same here

2016-10-07 19:07 UTC, skjnldsv commented on core/css/apps.css
> +	border-left: 1px solid 1px solid rgba(0,0,0,0.08)
sigh... Copy/paste wasn't really effective here...

2016-10-08 08:36 UTC, jancborchardt commented on core/css/apps.css
> +	border-left: 1px solid 1px solid rgba(0,0,0,0.08)
@skjnldsv Nice, very good call on using transparency vs greyspale! Also the code style is `rgba(0, 0, 0, .08)` (space after comma and no 0 before dot ;)

2016-10-08 08:39 UTC, jancborchardt requested changes

2016-10-08 08:39 UTC, jancborchardt commented on apps/files/css/files.css
> +	background-color: rgba(0,0,0,0.08);
Compare this with line 216 where you use the ame .08 color for #eee, instead of #f8f8f8 like here. ;) They should be different, no?

2016-10-08 12:13 UTC, skjnldsv commented on apps/files/css/files.css
> +	background-color: rgba(0,0,0,0.08);
I will calculate the new value. I like it more precise! :)

2016-10-08 12:53 UTC, skjnldsv commented on apps/files/css/files.css
> +	background-color: rgba(0,0,0,0.08);
Done @jancborchardt .
Values are now calculated base on a rgba transparency on white background.

2016-10-08 13:04 UTC, skjnldsv commented on core/css/inputs.css
> -	background-color: #fefefe;
@jancborchardt  I'm not really sure this is humanly visible 😆

2016-10-08 13:07 UTC, skjnldsv commented on core/css/inputs.css
> -	background-color: rgba(255, 255, 255, .95);
@jancborchardt same here. This is not visible to the eye. I changed to something more visible. What do you think?

2016-10-08 13:59 UTC, jancborchardt commented on core/css/inputs.css
> -	background-color: #fefefe;
Probably not really. Do you want to adjust this to the equivalent of #fff instead? Or rather it really needs to be solid #fff because by default the select is grey and it could be on top of dark background.

2016-10-08 14:00 UTC, jancborchardt commented on core/css/inputs.css
> -	background-color: rgba(255, 255, 255, .95);
The point about this was that the background color shines a bit through. For example when we have it in the header of the link share page there are buttons on the top right.

2016-10-08 14:01 UTC, skjnldsv commented on core/css/inputs.css
> -	background-color: rgba(255, 255, 255, .95);
Okay, makes sense!  :)

2016-10-08 14:04 UTC, skjnldsv commented on core/css/inputs.css
> -	background-color: #fefefe;
We shouldn't think of dark backgrounds superposition. Because the rgba I'm changing are planned on a #fff bg. If we want a dark background with the same contrast, we should reverse the values. :)

For this line, I think we could just remove it. Or choose a completely different value to set for all inputs:hover.

2016-10-08 17:07 UTC, skjnldsv commented on apps/files/css/files.css
> -tbody a { color:#000; }
We don't need to redefine the a colors since it's already set on core/styles.css

2016-10-10 07:42 UTC, nickvergessen commented
@skjnldsv you need to "sign off" all your commits:
https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

Can you fix all your commit messages please?

2016-10-10 12:39 UTC, skjnldsv commented
I know, I forgot, I will when I will squash those commits :)
Thanks

2016-10-12 13:47 UTC, georgehrke commented
<img width="436" alt="nextcloud chromium today at 3 45 14 pm" src="https://cloud.githubusercontent.com/assets/1250540/19312530/1381b8ba-9093-11e6-8ac7-717e15c1d677.png">
This also removes the background on the login for me 🙈

2016-10-12 13:57 UTC, skjnldsv commented
@georgehrke Yep, the login form don't have a background. We should apply one to it for this case only. :)

2016-10-18 08:33 UTC, jancborchardt commented
@skjnldsv can you fix what @georgehrke mentioned and the other things? Then squash or so, and we can review it. :)

2016-10-18 08:40 UTC, skjnldsv commented
@jancborchardt Not now. I'm lost for now. This pr extends to more than just white backgrounds I think.
Could you read your irc private message? :)
I sent you something.

2016-10-18 11:54 UTC, jancborchardt commented
@skjnldsv I’m not on IRC atm ;) either Github or email.

2016-10-18 11:55 UTC, skjnldsv commented
Just sent you one 🚀

2016-11-30 14:42 UTC, MorrisJobke commented
@skjnldsv What is the status of this?

2016-11-30 14:45 UTC, skjnldsv commented
@MorrisJobke on hold while I wait for the scss pr. Too much sh*** to clean.
Let's close and see after!

2016-11-30 14:45 UTC, closed without merging