Make rooms / resoureces automatically reply to invites
nextcloud/server pull request #16615
Opened 2019-07-30 10:58 UTC by georgehrke

Signed-off-by: Georg Ehrke <developer@georgehrke.com>

2019-08-21 15:24 UTC, georgehrke commented
@rullzer This is finally read for a code-review :)

2019-08-21 15:26 UTC, georgehrke commented
The calendar app does not show the response status at the moment:
You have to check the calendar-data of the organiser to check:
![8321B77A-3ED5-48CA-B418-5E663B47D335](https://user-images.githubusercontent.com/1250540/63445496-bd9e6d80-c438-11e9-98bb-3fc68cae6e89.png)
![655B86D1-8B9E-4B6C-AD2B-5F37BA4CF4D4](https://user-images.githubusercontent.com/1250540/63445513-c727d580-c438-11e9-8fae-56a641d978c4.png)

2019-08-21 18:22 UTC, rullzer requested changes
Looks good overal

2019-08-21 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Schedule/Plugin.php
> +			$endDateTime = $endDateTime->add(DateTimeParser::parse($vevent->DURATION->getValue()));
You have to add `use Sabre\VObject\DateTimeParser;` according to phpstorm :)

2019-08-21 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Schedule/Plugin.php
> +	private function getAttendeePartstat(Property $attendee = null):string {
Not used?

2019-08-26 11:32 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/Plugin.php
> +	private function getAttendeePartstat(Property $attendee = null):string {
removed

2019-08-26 11:32 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/Plugin.php
> +			$endDateTime = $endDateTime->add(DateTimeParser::parse($vevent->DURATION->getValue()));
Indeed, fixed :)

2019-08-27 11:21 UTC, rullzer approved these changes

2019-08-28 07:12 UTC, ChristophWurst approved these changes

2019-08-28 07:34 UTC, merged