Remove type for size arg on Streamer constructor
nextcloud/server pull request #16636
Opened 2019-08-02 11:15 UTC by artonge

Resolves #12422 and #15117

On 32 bit systems integers can not be bigger than 2 147 483 647. This is problematic as it throws an error when downloading a folder bigger than 2Go because php will cast the size to float.

2019-09-24 07:53 UTC, scriptator commented
Can somebody review and merge this? For me it seems fine and fixes the problem which I experienced

2019-09-24 11:51 UTC, nickvergessen approved these changes
Urgh, while I can see this solving the problem you have, I guess the issue will pop in quite a lot other locations too. I just think that at some point we just can not manage to stay compatible with 16-bit anymore.

2019-09-24 13:20 UTC, kesselb commented
> the issue will pop in quite a lot other locations too.

Yes. Another report for a similar problem is: https://github.com/nextcloud/server/issues/13160. Unfortunately https://wiki.php.net/rfc/bigint is still work in progress.

A) Add a library like https://github.com/brick/math and use BigInteger for size attributes.
B) Don't type hint `$size`

I don't like A nor B :see_no_evil: But there are many raspi instances out there.

2019-09-24 13:45 UTC, nickvergessen commented
Well, you forgot:
C) Don't support mutli GB files on those rapsi instances :see_no_evil:

2019-09-25 16:34 UTC, scriptator commented
> Urgh, while I can see this solving the problem you have, I guess the issue will pop in quite a lot other locations too.

Totally agree! It would be certainly better to fix the problem at the root

> I just think that at some point we just can not manage to stay compatible with 16-bit anymore.

What does this have to do with 16 bit? IMO raspi is running 32 bit which also makes sense when you consider the 2gb limit

2019-09-25 20:08 UTC, kesselb commented
> Totally agree! It would be certainly better to fix the problem at the root

Where is the root? PHP not having BigInt? Raspian not using 64 bit? We don't have much options. Change the type of $size for every occurence to this BigInteger library will take months. Not adding type hints for $size is the only way I can think of.

> What does this have to do with 16 bit? IMO raspi is running 32 bit which also makes sense when you consider the 2gb limit

Typo ...

2019-09-25 20:08 UTC, kesselb approved these changes

2019-09-26 13:53 UTC, scriptator commented
There is of course also another option: officially drop support for 32 bit systems. As I just found out there are 64 bit OS available for the raspberry and even the Raspberrypi foundation is now working on a 64 bit raspbian kernel. If it is clearly stated everywhere that 32 bit does not work properly and raspbian users should install a 64 bit distro I think it should also be okay

2019-09-27 17:16 UTC, artonge commented
I think dropping support for 32-bit systems might be a bit precipitated. 64-bit CPU on a Raspberrypi only came with the version 4, so there will still be a lot of 32-bit rpi for a some years. And the rpi is not the only 32-bit single board computer that is used as a small home server.

So dropping 32-bit support would mean dropping support for a lot of self-hosters.

2019-10-09 14:21 UTC, kesselb commented
cc @rullzer :ping_pong:

2019-12-19 17:35 UTC, nachoparker commented
Raspbian images are still 32 bits userland, even those with a 64 bits kernel.

2019-12-19 17:37 UTC, kesselb commented
Sorry! I forgot the milestone :see_no_evil:

2019-12-19 17:39 UTC, kesselb commented on lib/private/Streamer.php
> +	public function __construct(IRequest $request, $size, int $numberOfFiles){
We should probably add a short note to the docblock why typehinting `$size` is bad.

2019-12-19 19:26 UTC, go2sh commented
I dont think you can change the type to float at all. I had a similar discussions  with Morris and the problem is, that you cannot represent every integer with a float exactly especially for big numbers. You might get a value that is some where around the actual size creating a completely new bunch of problems. Out of bound reads, corrupted files, changing files sizes, plus the behavior might be total random as it depends on the actual file size. Because of that, a size in nextcloud should never be float with the consequences for 32 bit instances.

2019-12-19 19:38 UTC, kesselb commented
> size creating a completely new bunch of problems. Out of bound reads, corrupted files, changing files sizes, plus the behavior might be total random as it depends on the actual file size. 

Probably. But this pr is not about making $size a float. It's about removing the type hint.

2019-12-19 20:18 UTC, go2sh commented
Hitting the type hint is just a symptom. The file size is never stored or transferred as float, so somewhere up the call chain, a conversion to float happens, which shouldn't happen. I can imagine only two sources, either the db or a string conversion. Finding the conversion and throwing an exception is the correct fix.

2019-12-19 20:35 UTC, kesselb commented
PHP will cast the value from filesystem or database to float. Your "correct fix" will break it even more for 32bit users. 

```
php -r "var_dump(PHP_INT_MAX);"
int(9223372036854775807)

php -r "var_dump(9223372036854775807);"                               
int(9223372036854775807)

php -r "var_dump(9223372036854775808);"                               
float(9.2233720368548E+18)
```

2019-12-19 20:42 UTC, go2sh commented
I traced down the problem: The `Streamer` class is called from the `ZipResponse` class. You can add an abitrary amount of resources to the response. The size of each response will be summed up. Then php kicks in: [Integer Overflow](https://www.php.net/manual/de/language.types.integer.php#language.types.integer.overflow) When a php integer overflows, it gets convered to float. :man_facepalming: So you will lose precision no matter what.

2019-12-19 20:59 UTC, go2sh requested changes
As per comment.

2020-01-07 20:03 UTC, rullzer commented
Yep, we need to think of a better way to tackle this.
As removing it will also blow up in several cases as the resulting zip file will be invalid.

2020-02-24 09:52 UTC, artonge commented
Hi,

Maybe the real solution would be to display an error message to the user explaining why the file or zipped folder can't be downloaded.

Could an exception be thrown here, and caught in an error handler to display the correct error message ?

2020-04-10 08:11 UTC, skjnldsv commented
Ping! :)

2020-04-10 10:21 UTC, skjnldsv commented
> Yep, we need to think of a better way to tackle this.
> As removing it will also blow up in several cases as the resulting zip file will be invalid.

What shall we do then?

2020-10-24 10:39 UTC, Wolfgang1966 commented
How about using tar archives für everything above 4GB? It is already there depending on the client os and it will at least allow to download big archives at all. Ok, Windows does not support tar archives directly, but there are enough tools out there which do.  And it is better than being not able to download the file at all.

Tried it with a 9GB archive, was immediately asked to search for a application in the MS app store which offers several of them.

Consider this a workaround, but at least it is (in my opinion) a fair improvement compared to the current situation.

2020-12-07 13:17 UTC, Wolfgang1966 commented
> How about using tar archives für everything above 4GB? It is already there depending on the client os and it will at least allow to download big archives at all. Ok, Windows does not support tar archives directly, but there are enough tools out there which do. And it is better than being not able to download the file at all.
> 
> Tried it with a 9GB archive, was immediately asked to search for a application in the MS app store which offers several of them.
> 
> Consider this a workaround, but at least it is (in my opinion) a fair improvement compared to the current situation.

My version of the constructor in Streamer.php now is:

```
                if ($size > 0 && $size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
                        $this->streamerInstance = new ZipStreamer(['zip64' => false]);
                } else {
                        $this->streamerInstance = new TarStreamer();
                }
```

2020-12-08 10:36 UTC, go2sh commented
@Wolfgang1966 The problem here is, that the size as float doesn't represent the actual size of the files, as floating point numbers (32bit) are only an aproximation of integers (32bit).

2020-12-08 11:57 UTC, Wolfgang1966 commented
> @Wolfgang1966 The problem here is, that the size as float doesn't represent the actual size of the files, as floating point numbers (32bit) are only an aproximation of integers (32bit).

This is true, but in that case not relevant. As you can see, the parameter is only used to distuinguish between the usage of 32bit ZIP or anything else. 32bit zip can be used until 4GiB, which is roughly 4.29 GB. As we compare the value to 4.000.000.000 4GB, there is more than enough safety margin for any kind of missing accurancy that might be introduced by using float here.

2020-12-08 15:46 UTC, kesselb commented
`public function __construct(IRequest $request, int $size, int $numberOfFiles) {`

This code fails if you are on a 32bit operating system and size is bigger than 2147483648 because a bigger value is casted to float and then does not match the type hint anymore and :boom: 

Whatever you are talking about is a different story and unrelated to this pull request.

2021-09-25 12:33 UTC, MichaIng commented
Btw, Raspberry Pi 2 v1.2 is already ARMv8 capable: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications
So relevant 32-bit only SBCs are the RPi Zero models only. But the Raspberry Pi OS 64-bit version is still in beta, so dropping 32-bit support would still affect most RPi users and of course it would also affect a lot of other SBCs, though with a significantly lower user number.

Not representative, but the top 5 SBCs of DietPi users participating our survey program:
RPi 4 Model B (aarch64) | 2588 | 18%
-- | -- | --
RPi 4 Model B (armv7l) | 1856 | 13%
RPi 3 Model B (armv7l) | 1325 | 9%
RPi Zero W (armv6l) | 1042 | 7%
RPi 3 Model B+ (armv7l) | 890 | 6%

`armv7l` means 32-bit OS version, which is still the majority due to limitations of the 64-bit RPi userland and GPU accelerated software builds.

2022-02-23 00:43 UTC, MichaIng commented
/rebase

2022-02-26 15:19 UTC, MichaIng commented
Linking the very same issue present with the trash bin: #13160
Possible solution is the same.

2022-07-13 09:02 UTC, szaimen commented
Closing due to https://github.com/nextcloud/documentation/pull/9071

2022-07-13 09:02 UTC, closed without merging