Add accessibility label to show password checkbox
nextcloud/server pull request #16642
Opened 2019-08-02 18:35 UTC by nesb0t

Fixes #15965.

Added aria-label to show password checkbox. Tested and verified with NVDA.

2019-08-02 19:17 UTC, rullzer approved these changes

2019-08-05 19:35 UTC, skjnldsv requested changes

2019-08-05 19:35 UTC, skjnldsv commented on core/templates/installation.php
> +				   aria-label="Show password">
Please use a translation method :)
```suggestion
				   aria-label="<?php p($l->t( 'Show password' )); ?>">
```

2019-08-06 10:40 UTC, jancborchardt commented on core/templates/installation.php
>  			<label for="show"></label>
@nesb0t @nextcloud/accessibility I would have assumed it’s better to use the label text here? Or is the `aria-label` recommended?

2019-08-06 11:15 UTC, MarcoZehe commented on core/templates/installation.php
>  			<label for="show"></label>
> 
> 
> @nesb0t @nextcloud/accessibility I would have assumed it’s better to use the label text here? Or is the `aria-label` recommended?

No, if a label text is already there, and only the association is missing, use that. It also needs to be localized, so if some information is already available, no need to use aria-label. Checkbox inputs can have the same label association like text inputs, e. g. the for attribute of the label points to the ID of the checkbox input, and the association is done. No need for aria-label.

2019-08-06 13:23 UTC, jancborchardt commented
Thank you @nesb0t for the contribution! :)

Based on the comments from @skjnldsv and @MarcoZehe, could I ask you to change the following:
- Instead of `aria-label` on the checkbox, the text can be put into the `label for="show"` block directly after.
- The `label for="show"` then also needs `class="hidden-visually"` just like the checkbox so it’s only visible for screenreaders.
- It should be translatable in the way @skjnldsv suggested.

Let us know if you need any help. ♥

2019-08-06 13:24 UTC, jancborchardt commented on core/templates/installation.php
>  			<label for="show"></label>
Thanks a lot for clarifying, @MarcoZehe!

2019-09-05 10:24 UTC, rullzer commented
Master is no 18 development. If this needs to go into 17 please follow the normal backport procedures after merging.

2019-12-10 15:20 UTC, skjnldsv approved these changes

2019-12-10 17:22 UTC, kesselb commented
> Thank you @nesb0t for the contribution! :)
> 
> Based on the comments from @skjnldsv and @MarcoZehe, could I ask you to change the following:
> 
>     * Instead of `aria-label` on the checkbox, the text can be put into the `label for="show"` block directly after.
> 
>     * The `label for="show"` then also needs `class="hidden-visually"` just like the checkbox so it’s only visible for screenreaders.
> 
>     * It should be translatable in the way @skjnldsv suggested.
> 
> 
> Let us know if you need any help. ♥

@skjnldsv is this done? ;)

2019-12-10 17:25 UTC, skjnldsv commented
God dammit

2019-12-10 17:26 UTC, kesselb commented
Sorry :see_no_evil:

2019-12-10 17:28 UTC, skjnldsv commented
> Sorry

All good ;)
I missed the other comments! It's indeed the thing to do!

2019-12-10 17:33 UTC, kesselb commented
`The label for="show" then also needs class="hidden-visually" just like the checkbox so it’s only visible for screenreaders.`

Don't forget ;)

2019-12-10 17:37 UTC, skjnldsv commented
god dammit

2019-12-12 09:43 UTC, ChristophWurst approved these changes

2019-12-12 09:47 UTC, merged