Files additionalscripts to real event
nextcloud/server pull request #16641
Opened 2019-08-02 18:20 UTC by rullzer

* New additionalscripts event
* Legacy handler
* Moved comments as a POC

This allows to write nice tiny classes that just do what they need instead of having code and connetion mixed.

2019-08-06 13:01 UTC, ChristophWurst commented on apps/files/lib/Listener/LegacyLoadAdditionalScripts.php
> +class LegacyLoadAdditionalScripts implements IEventListener {
```suggestion
class LegacyLoadAdditionalScriptsAdapter implements IEventListener {
```

2019-08-06 13:01 UTC, ChristophWurst commented on apps/files/lib/Listener/LegacyLoadAdditionalScripts.php
> +	public function __construct(EventDispatcherInterface $legacyDispatcher) {
you can also use the new one. it extends the original one, so there is just one instance

2019-08-06 13:02 UTC, ChristophWurst commented
oh an conflicts :)

2019-08-07 17:44 UTC, rullzer commented
updated :)

2019-08-08 06:17 UTC, ChristophWurst requested changes

2019-08-08 06:17 UTC, ChristophWurst commented on apps/comments/lib/AppInfo/Application.php
> +		$dispatcher->addServiceListener(LoadAdditionalScriptsEvent::class, LoadAdditionalScripts::class);
for one-liners you could also use the `addListener` and pass a closure. but fine by me to have it in a class :)

2019-08-08 06:17 UTC, ChristophWurst commented on apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +	public function __construct(IEventDispatcher $legacyDispatcher) {
```suggestion
	public function __construct(IEventDispatcher $dispatcher) {
```

2019-08-08 06:17 UTC, ChristophWurst commented on apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +		$this->dispatcher = $legacyDispatcher;
```suggestion
		$this->dispatcher = $dispatcher;
```

2019-08-08 08:46 UTC, rullzer commented
Lets do this for 18 (early) as we need other events as well and more functionality.

2019-08-20 10:46 UTC, nickvergessen commented
I would also prefer to merge the 2 event dispatchers if easily possible (one wrapping the other or somthing)

2019-08-26 08:19 UTC, ChristophWurst commented
> I would also prefer to merge the 2 event dispatchers if easily possible (one wrapping the other or somthing)

[That is already the case](https://github.com/nextcloud/server/blob/master/lib/private/EventDispatcher/EventDispatcher.php) using composition and delegation. There is only one instance of a dispatcher, but two interfaces for it.

2019-08-26 12:19 UTC, kesselb commented
![image](https://user-images.githubusercontent.com/3902676/63690261-76cfbf80-c80c-11e9-9475-eb3292fdddad.png)

2019-09-09 14:33 UTC, ChristophWurst approved these changes

2019-09-09 18:17 UTC, rullzer commented
@nickvergessen please have another look. cleaner now

2019-09-14 15:53 UTC, icewind1991 approved these changes

2019-09-15 09:49 UTC, rullzer commented
Recent new eventdispatcher edits broke this. I'll have to take another look.

2019-09-16 17:03 UTC, ChristophWurst approved these changes

2019-09-24 12:35 UTC, nickvergessen commented
So, ready to merge?

2019-09-24 19:56 UTC, merged