Feature/calendar/delegation
nextcloud/server pull request #16666
Opened 2019-08-06 11:48 UTC by rullzer

2019-08-06 11:50 UTC, georgehrke requested changes
First quick dirty review, will check in depth later

2019-08-06 11:50 UTC, georgehrke commented on apps/dav/lib/CalDAV/Proxy/Proxy.php
> +		$this->addType('ownerId', 'string');
default type is string, so adding a type for ownerId and proxyId is not necessary

2019-08-06 11:50 UTC, georgehrke commented on apps/dav/lib/Migration/Version1011Date20190806104428.php
> +		$table->addUniqueIndex(['owner_id', 'proxy_id', 'permissions'], 'dav_cal_proxy_uidx');
I guess we should add indices for proxy_id and owner_id, because we use that for querying.

2019-08-06 11:52 UTC, rullzer commented on apps/dav/lib/CalDAV/Proxy/Proxy.php
> +		$this->addType('ownerId', 'string');
Yes I know. But sill being explicit is nice IMO

2019-08-06 11:52 UTC, rullzer commented on apps/dav/lib/Migration/Version1011Date20190806104428.php
> +		$table->addUniqueIndex(['owner_id', 'proxy_id', 'permissions'], 'dav_cal_proxy_uidx');
Fair enough

2019-08-08 11:44 UTC, tcitworld commented
Could you explain what's the motive behind this?

2019-08-08 12:11 UTC, georgehrke commented
> Could you explain what's the motive behind this?

This will allow you to delegate all your calendars to someone else. Most common use-case is someone sharing their calendars with their assistant/secretary to allow them to send out and respond to invitations on their behalf.

2019-08-08 14:15 UTC, tcitworld commented
Thanks, wasn't sure if it was the issue that you linked on top.

2019-08-14 11:49 UTC, georgehrke commented on apps/dav/lib/CalDAV/Calendar.php
> +		foreach ($proxies as $proxy) {
Note for myself: Remove, just add principal /calendar-user-write

2019-08-14 12:25 UTC, georgehrke commented
![61A4B590-7041-4254-9A12-47DCD40AC5CC-2](https://user-images.githubusercontent.com/1250540/63020768-48162880-be9f-11e9-9c09-7d6139cdafa8.jpg)

🎉🎉🎉

2019-08-14 12:25 UTC, georgehrke commented
tldr of what's left:
- [ ] add ProxyMapper to Resource and Room principal backends
- [ ] tests

2019-08-15 10:24 UTC, georgehrke commented
Let's see if Drone is happy now.

2019-08-15 17:30 UTC, rullzer commented
Lets merge this!

2019-08-15 17:30 UTC, merged

2020-02-12 10:33 UTC, alex-s-team commented
pretty excited about this feature, has this been released already (nextcloud 18 is not showing any delegates in ical)? how can this be activated?

2020-02-12 10:38 UTC, tcitworld commented
@alex-s-team It's available in Nextcloud 17. It will work with CalDAV clients that support the feature, such as Apple Calendar or BusyCal.

2020-02-12 10:42 UTC, alex-s-team commented
thanks very much for your answer, we are using apple calendar and there are no delegates showing up. do i have to activate the feature somehow via config or is the principal url different?

2020-02-12 11:04 UTC, tcitworld commented
As this seems to be a setup issue I would like to ask you to raise your question in the forums (so that we don't spam people in this issue): https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH they offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

2023-02-21 12:54 UTC, rotdrop commented
Just for the record: here we find that this does not work with the OSX calendar app: #17053. At least it is not possible to find anyone to delegate the calendar to ...

2023-12-16 10:25 UTC, z3ky commented
Maybe, the caldav trashbin #26083 #1662 has broken delegation #42051