Workflow frontend overhaul
nextcloud/server pull request #16706
Opened 2019-08-09 14:51 UTC by juliushaertl

This PR still requires quite some cleanup and polishing, once the backend changes are ready to be integrated from https://github.com/nextcloud/server/pull/16682

- [x] Unified UI for managing workflow operations
- [x] Adjust endpoints to fetch all operations
- [x] Add endpoint to test if operations are valid
- [ ] Design polishing as discussed with @jancborchardt 
  - [x] Rule state indicator that turns into save button
  - [x] Turn add rule button into placeholder input
  - [ ] Adjust font color of when/and
- [ ] Integrate operation/event/check data from backend once ready
- [ ] Move operation/event/check registration to backend
  - [ ] Operations: class, title, description, color, icon, supported events
  - [ ] Events: id, name, icon, supported checks
- [ ] Move event/operation registration and option components to apps
- [ ] Migrate check plugins to es6 exports
- [ ] Custom components for existing check plugins
  - [ ] FileType instead of mimetype with predefined sets of types
  - [ ] File size with validation
  - [ ] Request URL with presets
  - [ ] Time with validation
  - [ ] User groups multiselect

2019-08-09 16:49 UTC, jancborchardt commented
Doing make or `make dev-setup` doesn’t work in the apps/workflowengine folder. Is it documented somewhere how to do it? Cause atm I’m seeing a blank page. ;)

2019-08-10 07:43 UTC, rullzer commented
> Doing make or `make dev-setup` doesn’t work in the apps/workflowengine folder. Is it documented somewhere how to do it? Cause atm I’m seeing a blank page. ;)

Run in in the main folder. We have all the apps using the same webpack config else we'd be updating 14 apps all the time instead of just 1 folder

2019-08-10 11:07 UTC, jancborchardt commented on apps/workflowengine/src/components/Operation.vue
> +		background-image: url(/apps-extra/files_accesscontrol/img/app-dark.svg);
`/apps-extra/` shouldn’t be hardcoded here, right? :) At least this results in the icon not showing for me as I have all apps in `/apps`.

2019-08-10 11:08 UTC, jancborchardt requested changes

2019-08-10 11:08 UTC, jancborchardt commented on apps/workflowengine/src/components/Operation.vue
> +		background-image: url(/apps-extra/workflow_pdf_converter/img/app-dark.svg);
Same here with `apps-extra`.

2019-08-10 11:26 UTC, jancborchardt commented
Some additional points:
- [ ] When you click one of the 3 workflows, that chooser vanishes. I’d say it should always stay up top?
- [ ] When I select the "Tag a file" action, I immediately get a tooltip `Operation OCA\FilesAutomatedTagging\Operation does not exist.` I guess I’m missing some separate app, which would be combined in a separate pull request cc @blizzz 
- [ ] On narrow sizes, the arrow and result should be below the conditions, and the select2’s of the conditions also need to get narrower.
- [ ] We need to do a whole lot of detail checking on margins and sizes. E.g. when you click into the "Add a new filter" field, it moves slightly. Similar for when you focus the 3rd field of a condition, the row below moves because of the delete icon showing.
- [ ] As soon as all 3 selects of the condition show, the delete icon only shows when you focus the 3rd field, not when you change the comparator or the first field.
- [ ] I’d say `.icon-close` (❌) is a better icon for removing the current line than the "Delete" trash.
- [ ] The `.actions__item` element could do with a `cursor: pointer`, but because our reset has `cursor: default` on div and h3 we need to set it on those elements too.
- [ ] We could think if a colored bar on the left of the section in the color of the action make sense, or something else visual. Maybe also the icon should be colored then, not black? E.g. block icon should be block red, tag icon should be whatever is used above (currently primary) and Convert to PDF icon should be just the colored PDF icon. Then there’s symmetry in the color.

2019-08-12 08:22 UTC, blizzz commented
>  When I select the "Tag a file" action, I immediately get a tooltip Operation OCA\FilesAutomatedTagging\Operation does not exist. I guess I’m missing some separate app, which would be combined in a separate pull request cc @blizzz

Automated Tagging.

2019-08-19 15:17 UTC, juliushaertl commented on apps/workflowengine/src/components/Operation.vue
> +		background-image: url(/apps-extra/files_accesscontrol/img/app-dark.svg);
Fixed for now by inlining, in the end those will be provided by the backend

2019-08-29 15:15 UTC, juliushaertl commented
@jancborchardt I've fixed a bunch of design issues we have discussed and added some screenshots of the current state to the 1st post. Feedback is welcome

2019-08-30 15:27 UTC, blizzz commented on apps/workflowengine/templates/settings.php
> +<div id="<? p(\OCA\WorkflowEngine\AppInfo\Application::APP_ID); ?>"></div>
```suggestion
<div id="<?php p(\OCA\WorkflowEngine\AppInfo\Application::APP_ID); ?>"></div>
```

it does not render short tags for me, also they are deprecated https://wiki.php.net/rfc/deprecate_php_short_tags

2019-08-31 11:49 UTC, jancborchardt commented
Looking at the screenshots and using the app again, it seems that there’s a loooot of horizontal whitespace we can’t really do much about with a list-type layout. It’s all a bit floating in the air.

It seems that vertical boxes for the actions would fit better, as we thought about for mobile @juliushaertl? It would have the maximum width of the 3 inputs which are in the "When" condition.

> **When: 📁 file is updated**
> and [ … … … ] [ is ] [ … … … …]
> and [ … … … ] [ is ] [ … … … …]
>
> **Then → 📰 Convert to PDF**
> [ Keep original, preserve existing PDFs ]
> **( ✔ Active )**

So then two or even three of these blocks could be next to each other on desktop.
What do you think?

2019-09-02 09:32 UTC, juliushaertl commented
> It seems that vertical boxes for the actions would fit better, as we thought about for mobile @juliushaertl? It would have the maximum width of the 3 inputs which are in the "When" condition.

I don't think that would be a good idea, since the height of the entry is variable to how many and conditions are used and if the operation provide additional options (e.g. automated tagging provides an input field for the list of tags, but this could by anything that needs to be configurable)

How about just reducing the height a bit by using a more condensed styling for the operation like this:

![image](https://user-images.githubusercontent.com/3404133/64104834-560bea80-cd75-11e9-89fe-d666ab0af074.png)

2019-09-02 09:57 UTC, jancborchardt commented
@juliushaertl ok, already looks a bit better! :)

2019-09-09 16:03 UTC, ChristophWurst requested changes
Some nitpicks from the fraction of code I've reviewed :)

2019-09-09 16:03 UTC, ChristophWurst commented on apps/workflowengine/src/components/Checks/RequestUserAgent.vue
> +			const matchingPredefined = this.predefinedTypes.map(groups => groups.children).flat().find((type) => this.newValue === type.pattern)
```suggestion
			return this.predefinedTypes
				.map(groups => groups.children)
				.flat()
				.find((type) => this.newValue === type.pattern)
				.length > 0
```

2019-09-09 16:03 UTC, ChristophWurst commented on apps/workflowengine/src/components/Checks/RequestUserAgent.vue
> +			const matchingPredefined = this.predefinedTypes.map(groups => groups.children).flat().find((type) => this.newValue === type.pattern)
duplication from `isPredefined`?

2019-09-09 16:07 UTC, skjnldsv commented on apps/workflowengine/src/components/Checks/MultiselectTag/MultiselectTag.vue
> +		searchTags().then((result) => {
I will recommend using try..catch and async/await :grin:

2019-09-09 16:08 UTC, skjnldsv commented on apps/workflowengine/src/components/Checks/MultiselectTag/api.js
> +const searchTags = function() {
I actually really dislike this syntax.
`export const searchTags function` looks really weird to me. Unusual chained individual words in javascript.

I always feel like declaring consts and exporting the proper object much cleaner :)

2019-09-10 07:39 UTC, juliushaertl commented on apps/workflowengine/src/components/Checks/FileSystemTag.vue
> +			return true
That was a placeholder for later, I'll remove it for now, since we also did not have a frontend validation in the existing UI and add it to the todo list for later.

2019-09-10 07:46 UTC, juliushaertl commented on apps/workflowengine/src/components/Checks/MultiselectTag/MultiselectTag.vue
> +		asyncFind(query) {
A leftover, since we always fetch the full list of system tags. Not sure if async fetching is possible with the webdav endpoint, but I'll add that to the list for future improvements.

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/src/components/Check.vue
> +		Checks() {
```suggestion
		checks() {
```

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/src/components/Checks/FileSystemTag.vue
> +		label="Select a tag"
l10n

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/src/components/Checks/MultiselectTag/MultiselectTag.vue
> +		value: {
`type: Array`?

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/src/helpers/api.js
> +	const scopeValue = OCP.InitialState.loadState('workflowengine', 'scope') === 0 ? 'global' : 'user'
you could move this up to the module initialization block so it only runs once. OCP should be ready before the app's code

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/src/helpers/validators.js
> +	var regexRegex = /^\/(.*)\/([gui]{0,3})$/
move this and the other regexes out of the functions so they are only created once

and use const :)

2019-09-10 08:27 UTC, ChristophWurst commented on apps/workflowengine/templates/settings.php
> +<div id="<?php p(\OCA\WorkflowEngine\AppInfo\Application::APP_ID); ?>"></div>
nice pattern!

2019-09-10 08:27 UTC, ChristophWurst commented on package.json
> +    "nextcloud-router": "0.0.9",
:heart:

2019-09-10 08:48 UTC, juliushaertl commented on apps/workflowengine/src/components/Checks/MultiselectTag/MultiselectTag.vue
> +		value: {
No, since it can also be a single value (string). It's the same way we do it in nextcloud-vue for the multiselect. Background: I plan to move this to nextcloud-vue, but we need this pr ready for today, so this needs to happen later :see_no_evil:

2019-09-10 13:46 UTC, blizzz approved these changes
good base (mentioned smaller things for follow ups)

2019-09-10 14:05 UTC, merged