Allow admin configured mounts to use user configured global credentials
nextcloud/server pull request #16790
Opened 2019-08-19 12:01 UTC by icewind1991

This is useful when there are multiple admin configured mounts that should all use the same user configured credentials

Fixes #2861

2019-08-19 12:30 UTC, kesselb commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +		if (is_null($user)) {
```suggestion
		if ($user === null) {
```

2019-08-19 12:30 UTC, kesselb commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +			$uid = $user->getUID();
Less complexity without the else

2019-08-19 12:30 UTC, kesselb commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +	const CREDENTIALS_IDENTIFIER = 'password::global';
```suggestion
	private const CREDENTIALS_IDENTIFIER = 'password::global';
```

2019-08-19 13:24 UTC, rullzer approved these changes
looks good to me.

2019-08-22 09:18 UTC, wiswedel commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +			->setText($l->t('User configured Global credentials'));
I'd call it "Global credentials, user entered":
- reads better under _Global credentials_
- consistent wording with _User entered, store in database_

![image](https://user-images.githubusercontent.com/1804221/63502543-123ff800-c4ce-11e9-96b3-d9fd0d624725.png)

![image](https://user-images.githubusercontent.com/1804221/63502643-4c10fe80-c4ce-11e9-9ab9-db4324b88e92.png)

2019-08-22 09:44 UTC, wiswedel requested changes
When credentials haven't been entered or authentication wasn't successful (e.g. after pw change), click on a mount point currently says:

![image](https://user-images.githubusercontent.com/1804221/63504519-07876200-c4d2-11e9-8577-f43e97ab2f3a.png)

Selecting _yes_ leads to

![image](https://user-images.githubusercontent.com/1804221/63504556-1837d800-c4d2-11e9-9be6-83dfa82121d0.png)

Better would be as it is for _User entered, store in database_:

![image](https://user-images.githubusercontent.com/1804221/63504336-a2337100-c4d1-11e9-8c6b-a70f2248f9d8.png)

2019-08-22 09:44 UTC, wiswedel commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +			->setVisibility(BackendService::VISIBILITY_ADMIN)
```->setVisibility(BackendService::VISIBILITY_DEFAULT)```

to show it also on the user's list of configured external storages

2019-09-03 15:50 UTC, wiswedel commented
@icewind1991 any feedback to my change requests? Just wanna make sure this goes into 17.

2019-09-03 17:59 UTC, rullzer commented
@wiswedel he was on on holiday ;)

2019-09-03 19:50 UTC, wiswedel commented
> he was on on holiday ;)

Unbelievable

2019-09-05 10:24 UTC, rullzer commented
Master is no 18 development. If this needs to go into 17 please follow the normal backport procedures after merging.

2019-09-09 04:42 UTC, wiswedel commented
> Master is no 18 development. If this needs to go into 17 please follow the normal backport procedures after merging.

Ah, an auto-reference by a comment in the 17 beta PR made me assume this was actually supposed to be part of that PR.

2019-09-09 04:44 UTC, wiswedel commented
/backport to stable17

2019-09-09 15:14 UTC, icewind1991 commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +			->setText($l->t('User configured Global credentials'));
done

2019-09-09 15:15 UTC, icewind1991 commented on apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php
> +			->setVisibility(BackendService::VISIBILITY_ADMIN)
done

2019-09-09 15:16 UTC, icewind1991 commented
You can now configure the credentials as with "user provided"

2019-09-10 13:44 UTC, ChristophWurst approved these changes
Tested & works. Code looks good!

2019-09-10 14:01 UTC, merged

2019-09-13 12:21 UTC, wiswedel commented
Thanks a lot, @icewind1991 @rullzer @ChristophWurst @kesselb 
Great work