🚧 Accept all incoming shares 🚧
nextcloud/server pull request #16828
Opened 2019-08-21 14:23 UTC by nickvergessen

- [x] Respect the accepted flag from the share table (not used at all at the moment
- [ ] Generate a notification for a user when an individual share is done
- [ ] Generate a notification for all members when a group share is done
- [ ] Generate notifications for all group shares if a user is added to a group
- [ ] Remove the notifications when the share is deleted
- [ ] Remove the notifications when a member is removed from a group
- [ ] Update the accepted flag to 1 (accepted) for all existing shares on update

2019-08-22 12:55 UTC, nickvergessen commented
There is currently an inconsistence with remote shares to normal user shares and group shares.

User shares trigger an individual email, federated shares had a notification to accept and group shares had nothing.

Now since you need to accept all of them, they will all trigger a notification. Should be enough? Or will there be complains again from people how dont have the notifications app installed, or no client set up and therefor dont notice notifications.
But in that case I would say all shares should also trigger an email, not just some.

And then I think this is just working around the mail notification topic again, so in the end notifications should have an option to come via mail

2019-08-22 13:08 UTC, wiswedel commented
> Now since you need to accept all of them, they will all trigger a notification. Should be enough? Or will there be complains again from people how dont have the notifications app installed, or no client set up and therefor dont notice notifications.

We require notifications to be installed and activated. Makes no sense otherwise.

> But in that case I would say all shares should also trigger an email, not just some.
> 
> And then I think this is just working around the mail notification topic again, so in the end notifications should have an option to come via mail

Yeah, fire out emails as much as possible. Not all people have NC or clients open all day (like us 😉 )

2019-09-04 14:52 UTC, nickvergessen commented on lib/public/Share/IShareProvider.php
> +	 * @since 9.0.0
```suggestion
	 * @since 18.0.0
```

2019-09-04 14:53 UTC, nickvergessen commented on lib/public/Share/IShareProvider.php
> +	public function acceptShare(IShare $share, string $recipient): IShare;
@rullzer whats the status here? can we extend the interface, or do we add a new one and make the providers implement both and we simply check for it in the manager?

2019-09-05 10:12 UTC, rullzer commented on lib/public/Share/IShareProvider.php
> +	public function acceptShare(IShare $share, string $recipient): IShare;
I think extending the interface is fine. After all I'm not aware of any apps other than circles/guest doing their own implementation.

2019-09-06 11:30 UTC, nickvergessen commented
User and group shares are now ready for testing and the tech is ready for review. I think we should look at the other share providers in a follow up.

### Remarks
* When the notification is accepted on the files app, you need to reload the page to see it (same for federated shares, but this used to work, so also something for a follow up). At least a note should be displayed to the users.

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			throw new OCSNotFoundException($this->l->t('Wrong share ID, share doesn\'t exist'));
adjust error message

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			throw new OCSNotFoundException($this->l->t('Share type does not support accepting'));
Sounds more like a  BadRequestException then. No big feelings.

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Notification/Listener.php
> +			$notification->setSubject('incoming_user_share')
won't you make it a const, since it's referenced in other places?

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Notification/Listener.php
> +			$notification->setSubject('incoming_group_share');
same

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Notification/Notifier.php
> +						'name' => $share->getShareOwner(),
that 's the user id, right, shoudn't that be turned into the display name?

2019-09-06 13:39 UTC, blizzz commented on apps/files_sharing/lib/Notification/Notifier.php
> +						'name' => $share->getShareOwner(),
also to displayname

2019-09-06 13:39 UTC, blizzz commented on lib/public/Share/IManager.php
> +	 * @since 17.0.0
18

2019-09-06 13:39 UTC, blizzz commented on lib/public/Share/IShareProvider.php
> +//	public function acceptShare(IShare $share, string $recipient): IShare;
:fire:

2019-09-06 13:41 UTC, nickvergessen commented on lib/public/Share/IShareProvider.php
> +//	public function acceptShare(IShare $share, string $recipient): IShare;
temporary until the other implementeations are adjusted then the interface will require it #TechnicalReviewOnly

2019-09-09 12:13 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			throw new OCSNotFoundException($this->l->t('Wrong share ID, share doesn\'t exist'));
I copied this behaviour from `updateShare` and I think it's okay to not leak the existence if the user can not interact with the share

2019-10-02 07:27 UTC, wiswedel commented
Please don't let this get forgotten. Thx.

2019-10-11 11:21 UTC, wiswedel commented
@nickvergessen What's the status on this?

2019-10-30 08:35 UTC, rullzer commented on apps/files_sharing/lib/AppInfo/Application.php
> +		$dispatcher->addListener('OCP\Share::postShare', function(GenericEvent $event) {
Ah those crappy old events...

2019-10-30 08:43 UTC, rullzer requested changes
It doesn't seem to work for me. I share a folder to a user. The get the notifiation. But the folder already shows up directly...

2019-10-30 08:43 UTC, rullzer commented on apps/files_sharing/lib/Migration/SetAcceptedStatus.php
> +			->set('accepted', $query->createParameter(IShare::STATUS_ACCEPTED))
```suggestion
			->set('accepted', $query->createNamedParameter(IShare::STATUS_ACCEPTED))
```

2019-10-31 11:02 UTC, nickvergessen commented on apps/files_sharing/lib/Migration/SetAcceptedStatus.php
> +			->set('accepted', $query->createParameter(IShare::STATUS_ACCEPTED))
Fixed

2019-10-31 11:04 UTC, nickvergessen commented
> It doesn't seem to work for me. I share a folder to a user. The get the notifiation. But the folder already shows up directly...

My last commit was missing here. Pushed it now while I rebased on top of 620 missing commits from master :sweat_smile:

2019-11-01 14:37 UTC, tobiasKaminsky commented
Hm. For me it also does not work, but with
- share works
- receiving user sees a notification
- but clicking on accept results in 404 (url: http://localhost/nc/ocs/v2.phpex.php/ocsapp/apps/files_sharing/api/v1/shares/pending/588)

2019-11-12 16:42 UTC, nickvergessen commented
Rebased due to the heavy conflicts with roelands work of the share expiration notification.

After that I retested it again and it worked fine here. But @tobiasKaminsky your URL looks like the configuration of the URLs is not dont correctly, because I don't juggle with URLs at all: https://github.com/nextcloud/server/blob/0fe4b717dcc5ad50853e0a887bfa60416657988d/apps/files_sharing/lib/Notification/Notifier.php#L245

2019-11-13 07:17 UTC, tobiasKaminsky commented
I tested it and now it works :tada: 

Two things I noticed, which should then be handled in a new PR, if approved:
- be in files root view
- receive a share
- click "accept" on notification
- nothing happens
- where is my file? ;-) I guess this might be irritating users. 
--> can we check if we are in the folder where the shared item should pop up and do a reload?

- share a file with user A
- user A rejects it
- do not get a notification / info about it
- it is just like you never shared to the user
--> maybe add a notification like "user A rejected your share"

2019-11-13 13:01 UTC, rullzer commented
Yay works now indeed.
I say lets get it in and create separate issues to fix.

2019-11-13 13:01 UTC, rullzer approved these changes

2019-11-14 09:05 UTC, ChristophWurst commented on apps/files_sharing/lib/Notification/Listener.php
> +		while (true) {
```suggestion
		while (!empty($shares = $this->shareManager->getSharedWith($user->getUID(), IShare::TYPE_GROUP, null, 50, $offset)) {
```

? Assignments are expressions, they "return" the assigned value.

2019-11-14 09:05 UTC, ChristophWurst commented on lib/private/Share20/DefaultShareProvider.php
> +			$data = $stmt->fetch();
the cursor is not closed?

2019-11-18 15:12 UTC, rullzer commented on apps/files_sharing/lib/Notification/Listener.php
> +		while (true) {
I'm not a fan of such nested magic....

2019-11-18 15:47 UTC, ChristophWurst approved these changes

2019-11-18 19:11 UTC, merged

2019-11-19 18:27 UTC, wiswedel commented
@rullzer do you want me to report QA findings in separate issues just like @tobiasKaminsky earlier?

2019-11-19 19:25 UTC, rullzer commented
Yes track sepratly please