Remove orphaned calendar data from deleted subscriptions
nextcloud/server pull request #16835
Opened 2019-08-22 10:02 UTC by tcitworld

Closes #16833. Ref #13511

2019-08-22 10:07 UTC, tcitworld commented
On my production database, 6M rows of calendarobjects, and 14M rows of calendarchanges are affected.

2019-08-22 10:12 UTC, tcitworld commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects_props', 'calendarsubscriptions',  'objectid');
Deleted those two lines, but Github seems to be having issues.

2019-08-22 13:23 UTC, nickvergessen requested changes

2019-08-22 13:23 UTC, nickvergessen commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects', 'calendarsubscriptions',  'calendarid');
This can not be correct?!
calendarobjects.calendarid already references calendars.id
It can not at the same time reference calendarsubscriptions.id as both a autoincrements

2019-08-22 13:51 UTC, tcitworld commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects', 'calendarsubscriptions',  'calendarid');
I'm pretty sure it does, that's why we have the `calendartype` column in `calendarobjects`.
I added the check that was forgotten.

2019-08-22 14:49 UTC, nickvergessen commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +			$qb->where($qb->expr()->eq('c.calendartype', $calendarType));
```suggestion
			$qb->andWhere($qb->expr()->eq('c.calendartype', $calendarType));
```

2019-08-22 14:50 UTC, nickvergessen commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects', 'calendarsubscriptions',  'calendarid');
So that basically means all subscriptions are being broken when this job is run, because all entries are deleted, which happens on every update.

So I hope the feature is new in 17? @georgehrke

2019-08-23 07:45 UTC, tcitworld commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects', 'calendarsubscriptions',  'calendarid');
Yeah, this means all the cached subscription events but the ones having a subscription ID value that also happens to be a calendar ID are deleted at each update.
But :
* The cached subscription from #10059 isn't used anywhere right now.
* All the cached events for each subscription are purged anyway each time the `RefreshWebcalJob` runs to fetch updated content.

2019-08-23 08:10 UTC, nickvergessen commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		$orphanItems = $this->removeOrphanChildren('calendarobjects', 'calendarsubscriptions',  'calendarid');
Okay, so it fixes itself on the next run, so not the best way but okay.
Nevertheless fix-worthy

2019-08-26 08:20 UTC, georgehrke commented on apps/dav/lib/Migration/RemoveOrphanEventsAndContacts.php
> +		if (in_array($parentTable, ['calendars', 'calendarsubscriptions'], true)) {
```suggestion
		if (\in_array($parentTable, ['calendars', 'calendarsubscriptions'], true)) {
```

2019-08-26 08:21 UTC, georgehrke commented
Otherwise this looks like a reasonable change to me 👍

2019-08-26 10:51 UTC, nickvergessen approved these changes

2019-08-26 10:52 UTC, nickvergessen commented
/backport to stable16

2019-08-26 21:44 UTC, BernieO commented
Thanks for addressing this (#16833) so quickly 👍

Could this also be backported to stable15? Caching webcal calendars was introduced in NC15. So it would definitely make sense to backport it also to NC15

2019-09-04 08:51 UTC, georgehrke approved these changes

2019-09-04 08:54 UTC, merged