Add IAppManager::getAppWebPath()
nextcloud/server pull request #16859
Opened 2019-08-25 13:34 UTC by PhrozenByte

AFAIK there's currently no public API replacement for [`\OC_App::getAppWebPath()`](https://github.com/nextcloud/server/blob/a4e6073e47b1574c4dd9342bde1601ece28bdb3c/lib/private/legacy/app.php#L500-L512), making it impossible for e.g. [`cms_pico`](https://github.com/nextcloud/cms_pico) (resp. nextcloud/cms_pico#77) to pass the `private` app check.

`\OC_App::getAppWebPath()` is used in [`apps/cms_pico/lib/AppInfo/Application.php`](https://github.com/nextcloud/cms_pico/blob/4a0ede227a565a805d73204a61d355694ecd2530/lib/AppInfo/Application.php#L75-L83) and is required to build various asset URLs. `IURLGenerator::linkTo()` is no alternative here since we don't require the URL of a single file, but a base URL (and `IURLGenerator::linkTo()` furthermore does a very, very extensive and rather expensive trial & error).

```
$ php ./occ app:check-code cms_pico -c private
Analysing /var/www/html/nextcloud/apps/cms_pico/lib/AppInfo/Application.php
 1 errors
    line   90: OC_App - Static method of private class must not be called
App is not compliant
```

For `\OC_App::getAppPath()` there's `IAppManager::getAppPath()`, so `IAppManager::getAppWebPath()` feels natural.

**Targeting NC 17.0.0**; might be too much of a last-minute change, but anyway, the patch has virtually no impact, so this feels justifiable...

2019-08-27 06:38 UTC, juliusknorr requested changes
Please add a `@deprecated` annotation to the static method in OC_App as well

2019-08-27 06:40 UTC, juliushaertl commented
> Targeting NC 17.0.0; might be too much of a last-minute change, but anyway, the patch has virtually no impact, so this feels justifiable...

Not sure since we are already in beta phase, but would be fine by me

2019-08-27 09:00 UTC, PhrozenByte commented
> Please add a `@deprecated` annotation to the static method in OC_App as well

You sure? `\OC_App::getAppWebPath()` still holds the actual functionality, just like with `\OC_App::getAppPath()`, that isn't deprecated, too (`AppManager::getAppPath()` is just an public alias for `\OC_App::getAppPath()`). I guess that's because both depend on `\OC_App::findAppInDirectories()`, which holds a large part of the classes functionality. `\OC_App` should be deprecated in whole. However, this would be a rather big change (and no chance to make it into NC 17 I guess).

2019-09-05 15:09 UTC, ChristophWurst commented
> If `\OC_App::getAppWebPath()` should be deprecated nevertheless, shall I deprecate `\OC_App::getAppPath()`, too?

I'm fine with every deprecation if the API is either no used by anyone or there is a public one as well :)

2019-09-05 15:10 UTC, ChristophWurst commented
> public one

something in `\OCP\` to be precise

2019-09-05 15:12 UTC, ChristophWurst requested changes

2019-09-05 15:12 UTC, ChristophWurst commented on lib/public/App/IAppManager.php
> +	public function getAppWebPath($appId);
```suggestion
	public function getAppWebPath(string $appId): string;
```

2019-09-05 15:12 UTC, ChristophWurst commented on lib/public/App/IAppManager.php
> +	 * @since 17.0.0
```suggestion
	 * @since 18.0.0
```

master is 18 now

2019-09-05 15:12 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +	public function getAppWebPath($appId) {
```suggestion
	public function getAppWebPath(string $appId): string {
```

2019-09-05 16:40 UTC, PhrozenByte commented
Here we go :+1: 

Both `\OC_App::getAppWebPath()` and `\OC_App::getAppPath()` (calling deprecated since NC 11, because the public alternative was introduced with NC 11; if I shall rather hint NC 18, just give word) are deprecated now. All new methods are now typehinted (even though the files don't declare strict types).

2019-09-06 08:48 UTC, ChristophWurst approved these changes

2019-09-09 09:50 UTC, juliusknorr approved these changes

2019-09-09 10:20 UTC, rullzer approved these changes

2019-09-09 10:20 UTC, merged