Increase max read
nextcloud/server pull request #16946
Opened 2019-08-30 22:49 UTC by exussum12

8kb is very low, especially given this will be local files

2019-08-30 23:11 UTC, kesselb commented
Thank you :+1: 

Mind to sign off your commits? https://github.com/nextcloud/server/pull/16946/checks?check_run_id=208487803 for more information.

2019-09-02 13:48 UTC, rullzer commented
So I actually tried this and for me it made no difference. As the files are read in 8kb chunks anyways (php internals). did you change other things as well?

2019-09-02 16:35 UTC, exussum12 commented
I guess thats kinda the point. You shouldn't notice a difference. In my set up this stopped bandwidth by a huge amount.

I only looked at this being an issue because of the huge bandwidth usage on my server. This fixed it for me

2019-09-02 17:32 UTC, exussum12 commented
![Screenshot_20190902-182938](https://user-images.githubusercontent.com/1102850/64128729-eebf5c00-cdaf-11e9-8878-39e5be916d7c.png)


See above for bandwidth screenshot. Before and after this change.

2019-09-08 14:56 UTC, rullzer commented
@exussum12 I meant that I still saw 8k reads originating from php :wink: as that is one of the internal constants.

I'll dive a bit deeper.

2019-09-08 16:22 UTC, exussum12 commented
Have you got a link to that source? I did take a look but didn't find it. I imagine its there in the context of IP packets and not disk read packets as many disks actually have larger block sizes than this also now

2019-09-09 15:32 UTC, icewind1991 requested changes
Seems reasonable to me otherwise

2019-09-09 15:32 UTC, icewind1991 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
This should be a multiple of 1024, not 1000

2019-09-09 16:24 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
How come a multiple ? Happy to change it but curious

2019-09-09 18:27 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
It's actually a multiple of both

2019-09-09 18:32 UTC, icewind1991 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
512kb chucks should be 524288

2019-09-09 19:34 UTC, rullzer commented
> Have you got a link to that source? I did take a look but didn't find it. I imagine its there in the context of IP packets and not disk read bytes as many disks actually have larger block sizes than this also now. (Though this effect will be much less noticeable on a disk itself )

Mmm I can only trigger it in docker on old php versions.
Then I'm good to go.

2019-09-09 19:42 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
It's 500kb chunks (as the comment) u less it needs to be divisbile by 1024/1024 ?

2019-09-09 19:46 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
The only thing this should effect is memory. Increasing this will slightly increase the memory per process though 500kb I would think should be fine for most PHP setups ?

2020-02-01 22:04 UTC, kesselb commented
@exussum12 could you change the chunkSize to 512 kB (524288) as requested and rebase the branch with the latest changes from master? Thanks :+1:

2020-02-02 15:02 UTC, kesselb commented
Thanks @exussum12 :+1: 

CI looks good. I restarted the Job because some timeouts. 

@rullzer @icewind1991 :ping_pong:

2020-04-05 19:07 UTC, kesselb commented
Hey @exussum12, mind to do another rebase?

2020-04-12 12:02 UTC, exussum12 commented
rebased

2020-04-15 09:33 UTC, ChristophWurst requested changes

2020-04-15 09:33 UTC, ChristophWurst commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
should be 524288 as per https://github.com/nextcloud/server/pull/16946#discussion_r322391529

2020-04-15 12:11 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
Ah sorry. I think I rebased from a commit without this

2020-04-15 18:10 UTC, exussum12 commented on lib/private/Files/View.php
> +			$chunkSize = 512000; // 500 kB chunks
Done

2020-04-15 22:17 UTC, exussum12 commented
The lint check is failing on lines I've not touched ?

2020-04-16 08:31 UTC, rullzer approved these changes

2020-04-16 08:32 UTC, rullzer commented
> The lint check is failing on lines I've not touched ?

yeah not your fault. new linter

2020-04-16 08:34 UTC, ChristophWurst approved these changes

2020-04-16 08:37 UTC, merged