add MAX and MIN to functionbuilder
nextcloud/server pull request #17006
Opened 2019-09-04 15:10 UTC by icewind1991

Signed-off-by: Robin Appelman <robin@icewind.nl>

2019-09-04 17:34 UTC, rullzer requested changes

2019-09-04 17:34 UTC, rullzer commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * @since 12.0.0
nope

2019-09-04 17:34 UTC, rullzer commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * @since 12.0.0
nope

2019-09-06 11:03 UTC, rullzer approved these changes
fine by me

2019-09-06 12:37 UTC, kesselb approved these changes

2019-09-07 09:09 UTC, merged