Only send samesite cookies
nextcloud/server pull request #17075
Opened 2019-09-09 19:31 UTC by rullzer

This makes the last remaining two cookies lax. The session cookie
itself. And the session password as well (on php 7.3 that is). Samesite
cookies are the best cookies!

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2019-09-10 07:59 UTC, ChristophWurst requested changes
Clicked around, shared some files. All fine :+1:

2019-09-10 07:59 UTC, ChristophWurst commented on lib/private/Session/CryptoWrapper.php
> +							' secure' => $secureCookie,
```suggestion
							'secure' => $secureCookie,
```

?

2019-09-10 08:11 UTC, rullzer commented on lib/private/Session/CryptoWrapper.php
> +							' secure' => $secureCookie,
it was late. lets leave it at that.

2019-10-09 11:19 UTC, rullzer commented
So... for some reason this does :boom: when mixed. So not this only happens on php7.3 and later.
We should probably test in older browsers. But then I guess this is good to go!

2019-10-14 20:09 UTC, kesselb commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
Please consider `PHP_VERSION_ID` ;)

2019-10-21 18:02 UTC, kesselb commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
```suggestion
				if (\PHP_VERSION_ID < 70300) {
```

2019-10-21 18:03 UTC, kesselb commented on lib/private/Session/Internal.php
> +		if (version_compare(PHP_VERSION, '7.3') === -1) {
```suggestion
		if (\PHP_VERSION_ID < 70300) {
```

2019-10-21 18:03 UTC, kesselb commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
```suggestion
				if (\PHP_VERSION_ID < 70300) {
```

2019-10-21 18:04 UTC, kesselb commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
It wasn't me? ;)

2020-02-06 11:37 UTC, skjnldsv commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
Shaggy?

2020-02-06 11:56 UTC, kesselb commented on lib/private/Session/CryptoWrapper.php
> +				if (version_compare(PHP_VERSION, '7.3') === -1) {
I recall that was related to have three of those suggested changes. I'm certain that I pressed the comment button only once ;)

2020-02-06 14:44 UTC, nickvergessen approved these changes

2020-02-06 14:53 UTC, ChristophWurst approved these changes

2020-02-06 19:37 UTC, merged

2020-06-18 21:21 UTC, peacepenguin commented
This change breaks SAML auth in many cases with PHP 7.3 and above.

During a Nextcloud-SAML login, the user attempts to goto the nextcloud frontpage to login, nextcloud sets up the session cookies right away. Then redirects the user to login via SAML.

After the SAML login, there is a POST request with the SAML authorization back to nextcloud: 
 https://<nextcloud fqdn>/index.php/apps/user_saml/saml/acs

With these cookies set to LAX, the POST doesn't contain the needed session cookies, and the auth fails entirely.

If we drop the PHP version to 7.2, the cookie doesn't get set to LAX, and the SAML response POST will contain the needed session cookie, and login via SAML is successful.

This phenomenon is documented here, https://php.watch/articles/PHP-Samesite-cookies :

> When a cookie is marked samesite=Lax, that cookie will not be passed for any cross-domain requests unless it's a regular link that navigates user to the target site. Other requests methods (such as **POST** and PUT) and XHR requests will not contain this cookie.

I can confirm this is the source of the issue two different ways: drop the server php version to 7.2, issue gone; makes sense since this change code only sets the flag if php is 7.3 or above.

Also in chrome hitting nextcloud 19 with php 7.3 or 7.4, after the failed SAML login attempt from this issue, you can manually modify the session cookies in the F12 dev tools to remove the LAX flag from the two session cookies, then retrying login succeeds. 

A workaround is setting up the SAML IdP server on the same subdomain as the nextcloud instance:

sso.**mydomain.net**
nextcloud.**mydomain.net**

In this scenario, the bug doesn't manifest, since they are both part of the same subdomain, LAX allows the cookie to be sent even in a POST.

Unfortunately changing the hosted FQDN of the Identity provider to match your nextcloud instance may not be an option, or feasible.

Perhaps an override for this cookie change can be put in place so SAML auth app users can continue to function as before?