[stable16] Fix opening apps with Ctrl+click
nextcloud/server pull request #17103
Opened 2019-09-11 12:51 UTC by juliushaertl

backport of #17086

2019-09-11 12:51 UTC, juliushaertl commented
/compile amend /

2019-09-11 18:08 UTC, ChristophWurst approved these changes

2019-09-11 18:09 UTC, ChristophWurst commented
> /compile amend /

Nothing to compile on 16 :)

2019-09-11 18:09 UTC, ChristophWurst requested changes

2019-09-11 18:09 UTC, ChristophWurst commented on core/js/js.js
> +                window.location = $app.href
oh. indentation is off

2019-09-12 13:30 UTC, ChristophWurst approved these changes

2019-09-12 13:45 UTC, GretaD approved these changes

2019-09-15 08:20 UTC, merged