Move settings to an app
nextcloud/server pull request #17182
Opened 2019-09-17 14:35 UTC by ChristophWurst

Todo

- [ ] todo

2019-09-18 15:28 UTC, kesselb commented
>  Find out what help.php does

What does help.php? :thinking:

2019-09-18 15:56 UTC, ChristophWurst commented
> What does help.php? thinking

It helps :see_no_evil: 

Used here https://github.com/nextcloud/server/blob/master/settings/routes.php#L96, which still works.

2019-09-18 21:01 UTC, doliG commented
I'm not sure to understand your git history 😅

2019-09-18 21:12 UTC, ChristophWurst commented
> I'm not sure to understand your git history sweat_smile

https://dev.to/koffeinfrei/the-git-fixup-workflow-386d ;)

2019-09-18 21:24 UTC, doliG commented
Wow, that's a nice trick, thanks for sharing.

Actually, what I don't get is why there is so little commits for so many changes (15 commits for 315 file changed).

It's very hard to understand what's going on here for someone who haven't followed the reface from the beginning 🤔

2019-09-18 21:28 UTC, ChristophWurst commented
> Actually, what I don't get is why there is so little commits for so many changes (15 commits for 315 file changed).

I'm refactoring. And mostly moving stuff around. Eventually it will be only one commit.

> It's very hard to understand what's going on here for someone who haven't followed the reface from the beginning thinking

Sorry. We're just making the "settings" code an internal app. Which removes many hacks from the code and will allow us to clean up the server-side DI container registration to allow singletons of critical classes.

2019-09-20 09:54 UTC, ChristophWurst commented
I think this is done. Works here and can't reproduce the random CI failures.

2019-09-20 10:16 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	/** @var \OCA\Settings\Mailer\NewUserMailHelper */
Its imported? So should not be needed?

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/appinfo/info.xml
> +	<author>Bjoern Schiessle</author>
*cough cough*

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/appinfo/info.xml
> +	<name>Nextcloud Settings</name>
```suggestion
	<name>Nextcloud settings</name>
```

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/appinfo/info.xml
> +	<category>files</category>
:confused:

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/appinfo/info.xml
> +</info>
The settings sections and settings panels could be registered here now?

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/tests/Activity/SecurityProviderTest.php
> +		$this->provider = new \OCA\Settings\Activity\SecurityProvider($this->l10n, $this->urlGenerator, $this->activityManager);
Same here, its imported, no need to use the full name

2019-09-20 10:26 UTC, nickvergessen commented on apps/settings/tests/Activity/CertificateControllerTest.php
> +namespace OCA\Settings\Tests\Activity;
Should this be moved to `namespace OCA\Settings\Tests\Controller;`

Activity sounds like the wrong place 😅

2019-09-20 13:25 UTC, ChristophWurst commented on apps/settings/appinfo/info.xml
> +</info>
Yes, that can be done in a follow-up PR!

2019-09-24 11:56 UTC, nickvergessen approved these changes
Still works :elephant:

2019-09-26 09:22 UTC, skjnldsv requested changes
I cannot access the settings from the top right menu, I get redirected to /apps/files :)

2019-09-26 09:42 UTC, ChristophWurst commented
> I cannot access the settings from the top right menu, I get redirected to /apps/files :)

is the app listed as enabled?

2019-09-26 09:45 UTC, skjnldsv commented
> is the app listed as enabled?

Yes 
```
11:43 [admin@workstation] ~/Docker% docker-compose exec --user=docker php php occ app:list
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 2.1.1
  - calendar: 1.6.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.4
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.0
  - files_sharing: 1.10.0
  - files_texteditor: 2.10.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - forms: 1.0.3
  - guests: 1.1.1
  - lookup_server_connector: 1.6.0
  - mail: 0.17.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - pride: 0.0.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: true
  - sharebymail: 1.8.0
  - spreed: 7.0.0-dev.2
  - systemtags: 1.8.0
  - testing: true
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - vueexample: 0.0.1
  - workflowengine: 2.0.0
Disabled:
  - NextcloudExtract
  - browser_warning
  - bruteforcesettings
  - circles
  - dashboard
  - encryption
  - extract
  - files_3d
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - music
  - notes
  - password_policy
  - preferred_providers
  - previewgenerator
  - richdocuments
  - sandblast
  - tasks
  - terms_of_service
  - text
  - theming_customcss
  - twofactor_admin
  - twofactor_nextcloud_notification
  - twofactor_totp
  - user_ldap
```

I tried enabling again, and now the value is not `settings: true`, but `settings: 1.0.0`

2019-09-26 09:50 UTC, skjnldsv commented
I get lots of errors:
```json
{
  "reqId": "0HBW0cdq3lHGqbG7EoX8",
  "level": 0,
  "time": "2019-09-26T09:49:13+00:00",
  "remoteAddr": "172.21.0.1",
  "user": "admin",
  "app": "PHP",
  "method": "GET",
  "url": "/core/preview?fileId=3614&c=bf943200b495ff4ca1bb00ed7b3d7dd2&x=250&y=250&forceIcon=0",
  "message": "Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#58",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36",
  "version": "18.0.0.0"
}
```

2019-09-26 09:55 UTC, ChristophWurst commented
> I get lots of errors:

Unrelated. Happens on master as well.

But I can confirm that the URLs do not work. Also settings vanished from the menu. @rullzer any idea? You fixed this once already :)

2019-09-26 10:44 UTC, rullzer commented
Probably route caching.
Do you have memcache (apcu) configured?

2019-09-26 10:57 UTC, skjnldsv commented
> Do you have memcache (apcu) configured?

yes, let me flush :toilet:

2019-09-26 20:19 UTC, rullzer commented
Ok i have no idea what we did before to make it work
In any case. Pushed a fixup to fix it.

2019-09-26 20:22 UTC, skjnldsv approved these changes
Works! :)

2019-09-27 08:26 UTC, rullzer commented
ci fails (checkers)

2019-09-28 09:37 UTC, skjnldsv commented
/compile amend /

2019-09-28 11:14 UTC, merged