Add update all button to the app list
nextcloud/server pull request #17186
Opened 2019-09-17 20:38 UTC by GretaD

Fix #6989

2019-09-17 20:53 UTC, ChristophWurst requested changes

2019-09-17 20:53 UTC, ChristophWurst commented on settings/src/components/appDetails.vue
> +		<button v-on:click="onUpdate(enable)">Update all</button>
Not translated

2019-09-17 20:53 UTC, ChristophWurst commented on settings/src/components/appDetails.vue
> +		<button v-on:click="onUpdate(enable)">Update all</button>
Is `enable` a var?

2019-09-17 21:30 UTC, GretaD commented on settings/src/components/appDetails.vue
> +		<button v-on:click="onUpdate(enable)">Update all</button>
> Is `enable` a var?

is this a quiz question or do you not know it?

2019-09-17 22:59 UTC, skjnldsv commented on settings/src/components/appDetails.vue
> +		<button v-on:click="onUpdate(enable)">Update all</button>
This button doesn't seems to be relevant, where does it comes from?

2019-09-17 22:59 UTC, skjnldsv commented on settings/src/components/appDetails.vue
> +		<button v-on:click="onUpdate(enable)">Update all</button>
```suggestion
```

2019-09-17 23:02 UTC, skjnldsv commented on settings/src/components/appList.vue
> +			this.apps.forEach(function (app) {
Please make sure to filter the apps that don't have an update so you do not try to update apps that, well, don't have one ;)

2019-09-17 23:02 UTC, skjnldsv requested changes
See comments

2019-09-18 13:00 UTC, gary-kim requested changes
This is going to make managing an install much easier. Thank you.

2019-09-18 13:02 UTC, georgehrke commented on settings/src/components/appList.vue
> +				this.$store.dispatch('updateApp', { appId: app.id })
Please fix indentation

2019-09-19 09:31 UTC, skjnldsv commented on settings/src/components/appList.vue
> +			return this.hasPendingUpdate && ['installed', 'updates'].indexOf(this.category) !== -1
:+1:

2019-09-19 09:31 UTC, skjnldsv requested changes
Great work :)
See others comments ;)

2019-09-19 09:45 UTC, kesselb commented
![image](https://user-images.githubusercontent.com/3902676/65233350-f599de80-dad2-11e9-8eec-9b7386793696.png)

2019-09-19 10:11 UTC, kesselb commented
1. The "Update all" button is only visible on the "your apps" page.

2. https://github.com/nextcloud/server/blob/769cb629aebd368fbddd6ea04067fdcfaa262e3e/settings/Controller/AppSettingsController.php#L263 Add `$appData['update'] = '19.0.1';` above to show the update button for every app and then press the update all button. The result is a password confirmation box for every app with an update. forEach is blocking but the dispatch method not. I don't think we can wait for a event emitted by dispatch so the requiredAdmin call needs to be done before the emit to show only one password confirmation box.

3. Current implementation will update the apps at the same time. I'm not sure if this is a good idea. A new "updateAll" route would be more stable.

2019-09-19 12:32 UTC, skjnldsv commented
> 2\. I don't think we can wait for a event emitted by dispatch so the requiredAdmin call needs to be done before the emit to show only one password confirmation box.

Yes, we can :) 
https://github.com/nextcloud/contacts/blob/380cda3c6a43f7a49ea8cd31869ba276c458c702/src/components/Settings/SettingsAddressbook.vue#L186

@GretaD

2019-09-24 13:38 UTC, GretaD commented
> 1. The "Update all" button is only visible on the "your apps" page.
You propose to be also in other pages? Currently is at "your apps" and "Update" page.

2019-10-01 09:14 UTC, georgehrke commented
> The result is a password confirmation box for every app with an update. forEach is blocking but the dispatch method not. I don't think we can wait for a event emitted by dispatch so the requiredAdmin call needs to be done before the emit to show only one password confirmation box.

> > 2\. I don't think we can wait for a event emitted by dispatch so the requiredAdmin call needs to be done before the emit to show only one password confirmation box.

> Yes, we can :) 
https://github.com/nextcloud/contacts/blob/380cda3c6a43f7a49ea8cd31869ba276c458c702/src/components/Settings/SettingsAddressbook.vue#L186

@skjnldsv But you are inside an forEach loop. So even if the callback inside the foreach loop is returning a promise, it will happily ignore that and just call the next callback.

Leaving us with two options:
1. Solve this problem in javascript:
  - add [p-limit](https://www.npmjs.com/package/p-limit) as dependency 
  - limit concurrent app-updates to one at a time.
  - See for an example: https://github.com/nextcloud/contacts/blob/380cda3c6a43f7a49ea8cd31869ba276c458c702/src/store/addressbooks.js#L399L409

2. Solve this problem in php:
  - Just add a dedicated route that updates all apps with one request.

I would personally prefer 1.

@skjnldsv @kesselb ^

2019-10-02 14:18 UTC, georgehrke commented on settings/src/components/appList.vue
> +const limit = pLimit(1);
You can remove this line, since you are also defining `limit` on line 193.

2019-10-02 14:19 UTC, georgehrke commented on settings/src/components/appList.vue
> +},
Please fix the indentation of this closing bracket :)

2019-10-07 12:57 UTC, kesselb commented
@GretaD could you rebase? ;)

2019-10-07 14:43 UTC, GretaD commented
> @GretaD could you rebase? ;)

darn, i thought i already did

2019-10-08 06:28 UTC, skjnldsv commented
> darn, i thought i already did

Because lots of changes went into server again :)

2019-12-03 07:15 UTC, closed without merging