Move users management to multi line
nextcloud/server pull request #17239
Opened 2019-09-23 11:08 UTC by GretaD

ref #17208 
The user management used to be like this:
 
![user_managn_old](https://user-images.githubusercontent.com/12728974/65420924-ad482c80-de02-11e9-8c11-6be76763c4a3.png)

Now it looks like this:

![user_mangn_new](https://user-images.githubusercontent.com/12728974/65420968-d1a40900-de02-11e9-9950-5d6be459687c.png)

This version is in read mode. The toggle to edit the display name will be added with another patch.
@nextcloud/designers what do you think? Any other suggestions related to design?

2019-09-23 17:57 UTC, ma12-co commented
Looks good to me, I know there's a 'no uppercase' policy @jancborchardt :) but I think that it provides some nice hierarchy here. An alternative to that could be increasing the font size. 
The only thing I would do is vertically align those titles (the first is a bit off because of the sub heading). 
Also, you're pushing the compiled files, is that on purpose?

2019-09-24 05:37 UTC, skjnldsv commented on settings/css/settings.scss
> +				font-size: 10px;
Too small, we should aim for something a bit higher :)
Especially since we'll move to  15 px as default.

On #17208 screenshot, the size is the same, only the colour change ;)

2019-09-24 13:08 UTC, GretaD commented on settings/css/settings.scss
> +				font-size: 10px;
![newnew](https://user-images.githubusercontent.com/12728974/65514205-27e57a80-dedd-11e9-8b99-e3f10238491e.png)

2019-09-24 16:51 UTC, GretaD commented on settings/css/settings.scss
> +				font-size: 10px;
ah, i see, ok

2019-10-04 12:37 UTC, jancborchardt commented
> Looks good to me, I know there's a 'no uppercase' policy @jancborchardt :) but I think that it provides some nice hierarchy here. An alternative to that could be increasing the font size.

Hehe, so the point is that the focus should _not_ be on the table headings, but on the content. That is why they were lighter than the content text. The policy and the design does not come out of thin air. ;)

Uppercase text is quite bad for legibility as well as accessibility, and we shouldn’t start using it here on an otherwise unrelated change, especially not in table headings which are not a point of focus. :)

@GretaD could you change the headings to normal case, and a color like `color: var(--color-text-maxcontrast);`?

2019-11-26 11:31 UTC, skjnldsv requested changes
Rebased and cleaned up :)

- [x] the menu on the end is not aligned anymore :)
   ![image](https://user-images.githubusercontent.com/14975046/69625908-d88c0980-1047-11ea-8d75-23c4d3108929.png)
- [x] Menu not vertically centered
   ![Capture d’écran_2019-11-26_12-26-39](https://user-images.githubusercontent.com/14975046/69626030-17ba5a80-1048-11ea-8381-231e6411a1a8.png)
- [ ] we should not show the password column if it's not in edit mode as nothing is displayed :)
   ![Capture d’écran_2019-11-26_12-27-38](https://user-images.githubusercontent.com/14975046/69626094-37518300-1048-11ea-9ccc-03f0b66208ef.png)
- [x] we can hide the userid when editing so only the displayname (editable) is shown in the middle
   ![Capture d’écran_2019-11-26_12-28-42](https://user-images.githubusercontent.com/14975046/69626154-59e39c00-1048-11ea-8522-1c86f17774d4.png)
- [x] Some slight mislignment of the multiselects
   ![Capture d’écran_2019-11-26_12-29-57](https://user-images.githubusercontent.com/14975046/69626227-813a6900-1048-11ea-8901-dd06cff6a969.png)
- [x] The quota bar doesn't have the tooltip with details like it had before (in readonly mode)

Otherwise great work!! It's looking very clean and much more understandable :)
:+1:

2019-11-26 11:34 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRow.vue
> +						<input
- [ ] the inputs are not shown anymore :(

2019-11-26 11:36 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRow.vue
> +					<ActionButton icon="icon-checkmark" @click="editing = false">
It just toggle the editing, it doesn't save", so the text should be something else :)
To save a property you still need to manually click the submit button next to the input you're changing (the multiselects automatically save on change)

2019-11-26 11:37 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRow.vue
> +		* Create a new group and add user to it
nope, you need the spaces here ;)
This is how comments are formatted :)

2019-11-26 11:38 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +				.map((groupObject) => groupObject.name)
nice! :+1:

2019-11-28 15:40 UTC, GretaD commented on apps/settings/src/components/UserList/UserRow.vue
> +					<ActionButton icon="icon-checkmark" @click="editing = false">
I added "Done" is it better as an option?

2019-11-28 15:41 UTC, GretaD commented on apps/settings/src/components/UserList/UserRow.vue
> +		* Create a new group and add user to it
yep, fixed

2019-11-28 15:41 UTC, GretaD commented on apps/settings/src/components/UserList/UserRow.vue
> +						<input
added back, can you please tell me if its ok now?

2019-11-28 16:00 UTC, GretaD commented
@skjnldsv hey, we were discussing yesterday with Frank and Arthur about the "User Backend" column. Backend is very technical should we rename it something like Local maybe instead of Database? Or something else, less technical.

2019-11-29 10:36 UTC, skjnldsv commented
> Backend is very technical

I think it's hidden by default in the bottom left settings ;)

2019-11-29 10:59 UTC, GretaD commented
> > Backend is very technical
> 
> I think it's hidden by default in the bottom left settings ;)

i meant database not backend :) user backend is fine. the database we were discussing to call it smth like Local user or smth

2019-11-29 11:16 UTC, skjnldsv commented
Yes, it's the "user backend" (database, ldap...) It's hidden by default

2019-12-02 08:54 UTC, jancborchardt commented
> > > Backend is very technical
> > 
> > 
> > I think it's hidden by default in the bottom left settings ;)
> 
> i meant database not backend :) user backend is fine. the database we were discussing to call it smth like Local user or smth

To answer your question: Yes, changing the label from "Database" to "Local" seems good! :)

2019-12-02 10:21 UTC, skjnldsv commented
Ah, sorry I missed your point @GretaD :bowing_woman:

2019-12-03 16:37 UTC, GretaD commented on lib/private/User/Database.php
> +		return 'Local';
im not sure where else should i change BackendName? Maybe also at UserManagment.php `if($user->getBackendClassName() === 'Database')` ?

2019-12-03 16:40 UTC, skjnldsv commented on lib/private/User/Database.php
> +		return 'Local';
I would keep this as is, but just change the displayed backend string. Here it will definitely blow up somewhere else.

2019-12-03 16:40 UTC, skjnldsv commented on lib/private/User/Database.php
> +		return 'Local';
cc @rullzer & @blizzz

2019-12-04 13:06 UTC, rullzer commented on lib/private/User/Database.php
> +		return 'Local';
Yep please keep it there....

2019-12-05 17:14 UTC, skjnldsv commented
Rebased to get latests master changes

2019-12-05 18:13 UTC, skjnldsv commented
Okay, fixed some stuff and cleaned up lots of errors.
Please have a look again @GretaD

2019-12-06 09:52 UTC, skjnldsv commented
/compile fixup /

2019-12-08 11:17 UTC, karlitschek commented
What is the state here? Would be great to have this in 18 :-)

2019-12-08 11:18 UTC, karlitschek commented
@skjnldsv @GretaD

2019-12-08 16:40 UTC, skjnldsv commented
> What is the state here? Would be great to have this in 18 :-)

hopefully we should be able to get this in yes ;)

2019-12-09 10:45 UTC, GretaD commented
> @skjnldsv @GretaD

yes, i will work on tests today and we can have a final review this week.

2019-12-10 15:06 UTC, jancborchardt commented
Some design review, if that is wanted ;)

![users](https://user-images.githubusercontent.com/925062/70540585-19cbff80-1b98-11ea-9a99-51cfdbce76b5.png)

- Nice on the username / display name column! :+1: 
- [ ] The "Password" column is shown but seems useless until you edit a user because it does not contain any info.
- [ ] Table heading only needs a border-bottom of 1px, the 2px is not necessary and we don’t do that elsewhere either.
- [ ] The "Group admin for" table heading wraps too much and looks broken. Should wrap to max 2 lines.
- [ ] Group memberships are not actually shown for me in the overview?
- [ ] Stuff is a bit squished, especially the controls on the right? Having the controls sticky on the right would be much better to have them easily reachable without horizontal scrolling (which is a huge pain)
- [ ] Same for the "Done" button, it could be stickied to the right. If you e.g. just want to edit a person’s email address, you might need to:
   1. Scroll to right
   2. Click edit button
   3. Do the edits
   4. Scroll to right again
   5. Click "Done" button
- [ ] There is some whitespace on the right that seems it should not be there?
    ![groups whitespace](https://user-images.githubusercontent.com/925062/70541152-16854380-1b99-11ea-9b9f-1a1572da10c9.png)

2019-12-10 16:45 UTC, skjnldsv commented on apps/settings/src/components/UserList.vue
> +				 * In case the user directly loaded the user list within a group
Lots of issues with the comments tabs align here :)

2019-12-10 17:04 UTC, GretaD commented on apps/settings/src/components/UserList.vue
> +				 * In case the user directly loaded the user list within a group
my phpstarm is making my life miserable. I will fix it

2019-12-10 17:05 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> + *
add yourself ;)

2019-12-10 17:07 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> +		descendantOf(self::rowForUser($user))->
ah, it won't work as it looks for decendant of the row, but the class IS the row :thinking:

2019-12-10 17:10 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> +		descendantOf(self::rowForUser($user))->
Let me see the options we have

2019-12-10 17:15 UTC, skjnldsv commented on apps/settings/src/components/UserList.vue
> +				 * In case the user directly loaded the user list within a group
^^

2019-12-10 17:15 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> +		descendantOf(self::rowForUser($user))->
Found, remove this line
```suggestion
```

2019-12-10 17:16 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> +		return Locator::forThe()->css(".row--editable")->
```suggestion
		return Locator::forThe()->css("div.user-list-grid div.row.row--editable[data-id=$user]")->
```

2019-12-10 17:16 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/UsersSettingsContext.php
> +		return Locator::forThe()->css(".row--editable")->
And replace by this (we remove the check for decendant and match the row directly with the class :)

2019-12-10 17:29 UTC, skjnldsv commented on tests/acceptance/features/users.feature
> +	Scenario: assign user to a group
Please don't use the automated tabs option of phpstorm :see_no_evil:

2019-12-10 17:51 UTC, GretaD commented on tests/acceptance/features/users.feature
> +	Scenario: assign user to a group
:sob:

2019-12-11 21:12 UTC, GretaD commented
>     * [ ]  The "Password" column is shown but seems useless until you edit a user because it does not contain any info.

Removing it its not that user friendly since you have to wonder where to find the password to change it. We can add a placeholder or text to say smth like " click edit button to change password" or smth
>     * [ ]  Table heading only needs a border-bottom of 1px, the 2px is not necessary and we don’t do that elsewhere either.

Its `border-bottom-width: medium;` not border-bottom:2px. I changed it into `thin`.
> 
>     * [ ]  The "Group admin for" table heading wraps too much and looks broken. Should wrap to max 2 lines.

This is fixed, can you please check it out again, i cannot reproduce it anymore.
> 
>     * [ ]  Group memberships are not actually shown for me in the overview?

Yes, thats right, weird bug after the last changes pushed by @skjnldsv, will see whats wrong.
 
>     * [ ]  Same for the "Done" button, it could be stickied to the right. If you e.g. just want to edit a person’s email address, you might need to:
>       
>       1. Scroll to right
>       2. Click edit button
>       3. Do the edits
>       4. Scroll to right again
>       5. Click "Done" button

only for mobile, otherwise its fine, you dont need to scroll
>     * [ ]  There is some whitespace on the right that seems it should not be there?
>       ![groups whitespace](https://user-images.githubusercontent.com/925062/70541152-16854380-1b99-11ea-9b9f-1a1572da10c9.png)

this is also fixed, please recheck.

2019-12-12 11:23 UTC, skjnldsv approved these changes

2019-12-12 11:26 UTC, skjnldsv commented
All rebased and ready to go.
Acceptance tests now passes locally, should be good!

Please review!

2019-12-12 12:12 UTC, ChristophWurst approved these changes

2019-12-12 15:06 UTC, GretaD commented
CI all greeeeennn yoohooo

2019-12-12 15:10 UTC, merged