Decouple resource provider registration
nextcloud/server pull request #17325
Opened 2019-09-29 19:13 UTC by kesselb

2019-09-30 08:50 UTC, ChristophWurst commented on lib/public/Collaboration/Resources/IProviderManager.php
> +	 * @return array list of resource providers
```suggestion
	 * @return IProvider[] list of resource providers
```

2019-09-30 08:50 UTC, ChristophWurst commented on lib/public/Collaboration/Resources/IProviderManager.php
> +	 * @param string $provider
```suggestion
	 * @param string $provider provider's class name
```

2019-09-30 08:50 UTC, ChristophWurst commented on lib/public/Collaboration/Resources/IManager.php
> +	 * @deprecated 18.0.0 Use IProviderManager::registerResourceProvider instead
- [ ] Add to https://github.com/nextcloud/server/issues/17131 once merged

2019-09-30 08:51 UTC, ChristophWurst commented
I like the idea. Small services are good services.

You'll get bonus points if you add tests :wink:

2019-09-30 14:58 UTC, nickvergessen commented on lib/private/Collaboration/Resources/Manager.php
> +		$this->logger->debug('Manager::registerResourceProvider is deprecated');
Please use the full class name and also log the `$provider` value so people can find out what this is about and which app fucked up

2019-09-30 19:45 UTC, kesselb commented on lib/private/Collaboration/Resources/Manager.php
> +		$this->logger->debug('Manager::registerResourceProvider is deprecated');
Yes

2019-10-01 05:40 UTC, ChristophWurst commented on lib/private/Collaboration/Resources/ProviderManager.php
> +					$this->providerInstances[] = \OC::$server->query($provider);
You can inject `\OCP\IServerContainer` via the constructor to make this mockable and testable

2019-10-01 05:42 UTC, ChristophWurst requested changes

2019-10-01 05:42 UTC, ChristophWurst commented on lib/private/Collaboration/Resources/ProviderManager.php
> +						'message' => 'Error when instantiating resource provider'
```suggestion
						'message' => "Could not query resource provider $provider: " . $e->getMessage()
```

2019-10-01 13:36 UTC, kesselb commented on lib/private/Collaboration/Resources/ProviderManager.php
> +					$this->providerInstances[] = \OC::$server->query($provider);
Yes. Need to mock all query calls then but we can run the tests without a proper di container.

2019-10-02 18:23 UTC, ChristophWurst approved these changes

2019-10-02 18:23 UTC, ChristophWurst commented on tests/lib/Collaboration/Resources/ManagerTest.php
> +	 * @deprecated 18.0.0
a deprecated test function? what? :)

2019-10-02 18:23 UTC, ChristophWurst commented on tests/lib/Collaboration/Resources/ProviderManagerTest.php
> +		$this->assertCount(0, $resourceProviders);
FYI there's also `assertEmpty`

2019-10-02 18:40 UTC, kesselb commented on tests/lib/Collaboration/Resources/ProviderManagerTest.php
> +		$this->assertCount(0, $resourceProviders);
Thanks

2019-10-03 07:54 UTC, ChristophWurst approved these changes
![](https://media.giphy.com/media/8fen5LSZcHQ5O/source.gif)

2019-11-01 14:15 UTC, kesselb commented
Hello @rullzer @juliushaertl :ping_pong:

2019-11-04 09:12 UTC, juliusknorr approved these changes
Nice :+1:

2019-11-11 16:58 UTC, ChristophWurst commented
CI seems happy except for then the DB dies. Let's get this in!

2019-11-11 16:58 UTC, ChristophWurst commented
@kesselb mind squashing the commits?

2019-11-13 21:16 UTC, kesselb commented
CI don't like me today ;) Could someone of you press merge?

2019-12-04 08:13 UTC, nickvergessen requested changes
Some small little fixes needed because we updated phpunit in the meantime

2019-12-04 08:13 UTC, nickvergessen commented on tests/lib/Collaboration/Resources/ManagerTest.php
> +	public function setUp() {
```suggestion
	protected function setUp(): void {
```

2019-12-04 08:13 UTC, nickvergessen commented on tests/lib/Collaboration/Resources/ProviderManagerTest.php
> +	public function setUp() {
```suggestion
	protected function setUp(): void {
```

2019-12-04 09:25 UTC, nickvergessen approved these changes

2019-12-09 08:51 UTC, merged