Initial state for accessibility
nextcloud/server pull request #17382
Opened 2019-10-03 08:21 UTC by skjnldsv

Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

2019-10-04 06:58 UTC, ChristophWurst requested changes

2019-10-04 06:58 UTC, ChristophWurst commented on apps/accessibility/src/Accessibility.vue
> +import { generateUrl } from 'nextcloud-router'
*cough* https://www.npmjs.com/package/@nextcloud/router *cough*

2019-10-04 06:58 UTC, ChristophWurst commented on apps/accessibility/src/Accessibility.vue
>  import axios from 'nextcloud-axios'
*cough* https://www.npmjs.com/package/@nextcloud/axios *cough*

2019-10-04 06:58 UTC, ChristophWurst commented on apps/accessibility/src/main.js
> +import { loadState } from 'nextcloud-initial-state'
really? https://www.npmjs.com/package/@nextcloud/initial-state

2019-10-04 08:13 UTC, skjnldsv commented
/compile amend /

2019-10-12 13:21 UTC, rullzer commented
need a rebase :)

2019-10-12 13:37 UTC, skjnldsv commented
> need a rebase :)

:rocket:

2019-10-14 07:27 UTC, ChristophWurst approved these changes

2019-10-14 15:59 UTC, rullzer approved these changes

2019-10-14 16:00 UTC, merged