Improve previews
nextcloud/server pull request #1741
Opened 2016-10-14 07:44 UTC by rullzer

This PR improves the preview system:

* Previews are stored in the AppData
  - Allows sharing of previews for shared data
  - Allows sharing of previews for external storage
* Now always respects min/max preview size
* Previews are stored in power of 2 sizes (should be more than enough)

Todo:

- [ ] React on update/deletion of files (and fodlers for delete) (CC: @icewind1991)
- [ ] Move all endpoints over
- [ ] Tests!

FYI @oparoz

2016-10-14 10:36 UTC, MorrisJobke requested changes

2016-10-14 10:36 UTC, MorrisJobke commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
*cough* *cough*

2016-10-14 10:36 UTC, MorrisJobke commented on core/routes.php
> +	->actionInclude('core/ajax/preview2.php');
🙈 No controller? 🙊

2016-10-14 10:36 UTC, MorrisJobke commented on tests/lib/PreviewTest.php
> +	 * For this test to work, the preview we generate first has to be the size of ma4x preview
😉

2016-10-14 10:43 UTC, nickvergessen requested changes

2016-10-14 10:43 UTC, nickvergessen commented on core/ajax/preview2.php
> +\OC_Util::checkLoggedIn();
No header given

2016-10-14 10:43 UTC, nickvergessen commented on lib/private/Preview2.php
> +namespace OC;
Please namespace (we have a Preview namespace) then you can also get rid of the `2`

header missing

2016-10-14 10:43 UTC, nickvergessen commented on lib/private/Preview2.php
> +	public function __construct(
docs

2016-10-14 11:01 UTC, rullzer commented on core/routes.php
> +	->actionInclude('core/ajax/preview2.php');
Yeah yeah. On the todo... I wanted to have it work first ;)

2016-10-14 11:01 UTC, rullzer commented on core/ajax/preview2.php
> +\OC_Util::checkLoggedIn();
yeah needs to be moved to a proper controller to get rid of all this crappy stuff.

2016-10-16 18:05 UTC, rullzer commented
File_sharing (public previews) is moved over. Awesome side effect is that we now (thanks to the FileDisplayResponse) get preview client side caching for free!

2016-10-18 11:22 UTC, rullzer commented
Ok all is looking good from my POV.
I'm just not sure how to handle migration. Since there might be more (different) previews of the same image. And picking the right one can be tricky. Also moving everything could take a long time! (even on installations that don't have a dedicated cron job there could be a lot of previews).

Any ideas? @oparoz @MorrisJobke @nickvergessen ?

2016-10-18 12:08 UTC, icewind1991 commented
Maybe don't move old previews over but allow reading the old preview when there is none in the new location, then when a file is changed delete the old ones while generating the new ones

2016-10-18 12:13 UTC, rullzer commented
@icewind1991 mmm could work. But that would still mean that currently wrong previews would still be displayed wrong (so for shared files etc)

2016-10-18 12:24 UTC, adsworth commented
or just delete the previews in the old location when first generating a preview with the new logic. unlinking around 5-10 (I guess that's how many there might be) files shouldn't take to long.

Not migrating old preview would create extra load on big installs though, since all previews need to be regenerated.

2016-10-19 09:25 UTC, rullzer commented
Ok after some more thinking I think just deleting all previews and starting over is the easiest and cleanest way forward.

* For a single file there might now be a few (different) previews lying around
* Even small (sqlite) instances might have a shitload of previews so migrating them when there is no dedicated cron is going to time out.
* Looking into two places is not very performant. Risks selecting the wrong preview. And at some point we have to get rid of the old preview folders anyways.

So I vote for just killing all preview folders. And have the previews be regenerated. In most cases this should be significantly less previews since the previews are now shared.

2016-10-19 10:51 UTC, oparoz commented
This will require some good communication. Last time this happened, everybody complained that Pictures/Gallery was slow, because the initial load would take minutes. Now at least we show something in the first few seconds, but I'm just saying that it won't be great for people will large photo collections.

Maybe it's time to resurrect the occ thumbnail generator. It can take hours for the process to complete, but it's better than having to wait when using the GUI imo.

2016-10-21 10:29 UTC, rullzer commented
@oparoz yes I agree. Good communication is key here. We have a nice list of improvements. But gettings this properly is key.

I would not mind the thumbnail generator resurrection. But I also have been thinking about a listner that injects new/edited files. So we can say generate those in the background. But that is a discussion for another time.

I'll see if the thumbnail generator is easy to resurrect. Because that seems like the fastest solution.

2016-10-28 12:08 UTC, rullzer commented
See https://github.com/rullzer/PreviewGenerator for my ultra simple cli preview generator. It isn't smart. Just looks over all files and if it can generate previews.

It doesn't do anything fancy. because of the caching previews if a preview exists it just returns the file.

2016-10-28 17:51 UTC, rullzer commented
Ok I will update the previewgenerator app with a command to also delete the old previews. That seems the most sensible solution IMO.

So review time.

2016-11-02 21:29 UTC, MorrisJobke commented
Code looks good and also works 👍

2016-11-02 21:29 UTC, MorrisJobke approved these changes

2016-11-03 08:41 UTC, nickvergessen submitted a review, later dismissed

2016-11-03 08:41 UTC, nickvergessen commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
My problem with this is, it will break all apps:
https://github.com/nextcloud/activity/blob/master/lib/Controller/OCSEndPoint.php#L314

2016-11-03 08:42 UTC, MorrisJobke commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
Usually this is not how URLs work - you take the URL and not the name of an URL to get the correct URL. URLs itself are the identifier. 🙈

2016-11-03 08:44 UTC, nickvergessen commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
Well then we should have a public method in the url generator for that.
This is what worked and was suggested in the past to use...

2016-11-03 08:45 UTC, rullzer commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
I don't want to keep all the crappy untested ajax endpoints around just because they might be linked from somewhere.

2016-11-03 08:46 UTC, MorrisJobke commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
Can we create the name for the new URL?

2016-11-03 08:53 UTC, rullzer commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
Name is autogenerated from the app+controller+function

2016-11-03 12:33 UTC, rullzer commented on core/routes.php
> -$this->create('core_ajax_preview', '/core/preview')
I'll just add it to the changelog (with codesnipplet to change) once https://github.com/nextcloud/server/pull/1997 is in. That is best from my POV without introducing yet more routing magic.

2016-11-03 16:38 UTC, oparoz commented
Cool about the changelog. We'll have to test a few apps I guess and communicate heavily if things break so that people can fix their app for launch.

2016-11-03 19:56 UTC, rullzer commented
So 1 more thumbs up plz :)

2016-11-03 20:07 UTC, LukasReschke approved these changes

2016-11-03 20:07 UTC, LukasReschke commented
LGTM

2016-11-03 20:07 UTC, merged