Fix getContent so body content stream can be accessed on POST method
nextcloud/server pull request #17425
Opened 2019-10-06 04:08 UTC by xklonx

I need to get file from body of POST request, but there is no way to get Request->inputStream so i think this fix is correct.

2019-10-21 07:01 UTC, ChristophWurst requested changes
L424 still only mentions `put` in the exception message

2019-10-24 10:57 UTC, ChristophWurst approved these changes

2019-11-01 16:50 UTC, xklonx commented
Method __get get called before controller execution to get parameters for controller method. Therefore, I think that in switch cases params and parameters, only an parsed array is needed.

2020-03-15 13:40 UTC, xklonx commented
@rullzer can you check this please?

2020-07-06 10:25 UTC, MorrisJobke commented
@rullzer Ping

2022-01-17 08:10 UTC, skjnldsv commented
/rebase

2022-01-17 08:32 UTC, skjnldsv commented
@xklonx can you rebase and squash all commits into one please?
I don't have that much permissions on your fork :)

2023-03-07 19:03 UTC, blizzz commented
Closing for inactivity. Code needs to be adjusted to current code base, but it should be pretty easy. If someone is interesting in it, open a new PR with the modifications.

2023-03-07 19:03 UTC, closed without merging