take group creation result into consideration
nextcloud/server pull request #17470
Opened 2019-10-08 16:11 UTC by blizzz

by catch. At the moment, we assume that createGroup simply succeeds :man_shrugging: Not anymore, comes with unit test.

I wouldn't necessarily port it back (not without a reported bug) as it affects behaviour.

2019-10-08 17:13 UTC, skjnldsv commented on lib/private/Group/Manager.php
> +					if($backend->createGroup($gid)) {
```suggestion
					if ($backend->createGroup($gid)) {
```
:see_no_evil:

2019-10-08 17:13 UTC, skjnldsv approved these changes

2019-10-08 17:29 UTC, nickvergessen commented on lib/private/Group/Manager.php
>  			return false;
Should we unify this to null?

2019-10-09 17:10 UTC, blizzz commented on lib/private/Group/Manager.php
>  			return false;
the interface's PHPdoc actually only wants an IGroup returned. 

* the group create occ command relies on IGroup
* and the user add command in some way, too
* setup relies on it, too

2019-10-10 06:55 UTC, nickvergessen commented on lib/private/Setup.php
> +			if($group instanceof IGroup) {
```suggestion
			if ($group instanceof IGroup) {
```

2019-10-30 08:33 UTC, blizzz commented
bump

2019-11-04 10:25 UTC, icewind1991 requested changes

2019-11-04 10:25 UTC, icewind1991 commented on core/Command/Group/Add.php
> +			if($group === false) {
`null` is used as error value here, not `false`

(`!$group instanceof ...` would also be a clearer option here imo)

2019-11-05 15:32 UTC, closed without merging