Allow registering header/footer sections in the file lists
nextcloud/server pull request #17482
Opened 2019-10-09 07:41 UTC by juliushaertl

2019-10-16 10:00 UTC, kesselb commented on apps/files/js/filelist.js
> +			this.headers.forEach((header) => {
Is `filelist.js` tanspiled by babel?

2019-10-16 10:02 UTC, juliushaertl commented on apps/files/js/filelist.js
> +			this.headers.forEach((header) => {
:see_no_evil: Ah of course not, thanks

2019-10-16 10:14 UTC, kesselb commented on apps/files/js/filelist.js
> +			this.headers.forEach((header) => {
Just to be sure. There is a forEach polyfill? Not that I care about IE11 but ...

2019-10-16 10:25 UTC, juliushaertl commented on apps/files/js/filelist.js
> +			this.headers.forEach((header) => {
forEach is supported since IE9 so no polyfill needed for that.

2019-10-16 10:29 UTC, kesselb commented on apps/files/js/filelist.js
> +			this.headers.forEach((header) => {
:tada: I checked the wrong forEach obviously :see_no_evil:

2019-10-17 08:22 UTC, danxuliu requested changes

2019-10-17 08:22 UTC, danxuliu commented on apps/files/js/filelist.js
> +					header.footer(self)
I guess this should be `footer.render(self)` instead.

2019-10-17 08:22 UTC, danxuliu commented on apps/files/js/filelist.js
> +				_.defaults(header, { order: 0 })
`header` => `footer`

2019-10-17 11:40 UTC, juliushaertl commented on apps/files/js/filelist.js
> +					header.footer(self)
:see_no_evil: Thanks, fixed

2019-10-22 11:33 UTC, ChristophWurst approved these changes

2019-10-22 12:11 UTC, danxuliu approved these changes
Tested and works :+1: 

Note that the footer is a bit separated from the table due to [the summary height](https://github.com/nextcloud/server/blob/cbc38628302c618866d041f9b50958a25e16f838/apps/files/css/files.scss#L651-L652). I guess that it would be good to add that space only if there are no footers, although we can worry about that later too ;-)

2019-10-22 12:46 UTC, rullzer commented
Fixup and we get it in @juliushaertl !

2019-10-23 17:39 UTC, merged