add update all button
nextcloud/server pull request #17512
Opened 2019-10-11 13:32 UTC by GretaD

fix #17186

2019-10-18 14:10 UTC, jancborchardt commented
From the screenshot in the other pull request:

- Could we also add some info text left of the button? That is: "4 apps have an update available. **[ Update all ]**"
- Also the text should best be left-aligned with the titles of the apps below, meaning moved a bit to the right. :)

2019-10-22 15:47 UTC, skjnldsv commented on apps/settings/src/components/AppList.vue
> +			return this.getAppsPendingUpdate && ['installed', 'updates'].includes(this.category)
```suggestion
			return this.getAppsPendingUpdate.length > 0 && ['installed', 'updates'].includes(this.category)
```

2019-10-22 15:47 UTC, GretaD commented
@jancborchardt @skjnldsv is this ok? 
![updateall](https://user-images.githubusercontent.com/12728974/67304051-92e19b80-f4f3-11e9-9de5-572cc6fbf5fc.png)
Right now the text is shown in all categories, I'm still working to show it only where the button is, but meanwhile you can check if this looks fine.

2019-10-22 15:48 UTC, skjnldsv commented on apps/settings/src/components/AppList.vue
> +		getAppsPendingUpdate() {
This is not really true :)
You're not getting al the apps with a pending update, but only the first one.
The old variable name was more understandable in my opinion

2019-10-22 15:51 UTC, GretaD commented on apps/settings/src/components/AppList.vue
> +		getAppsPendingUpdate() {
Yes, but the word _has_ give you the impression it will return true or false. But fair, i will change it back in my next commit

2019-10-22 15:52 UTC, skjnldsv commented on apps/settings/src/components/AppList.vue
> +			this.apps
You can use a map function for this directly :)

```js
Promise.all(
	this.apps
		.filter(app => app.update)
		.map(app => limit(() => this.$store.dispatch('updateApp', { appId: app.id }))
)
```

2019-10-22 15:55 UTC, skjnldsv commented on apps/settings/src/components/AppList.vue
> +		getAppsPendingUpdate() {
you can check against more stuff than a boolean ;)
But you're right, you can use something like 
```js
return this.apps.findIndex(app => app.update) !== -1
```

2019-10-22 20:06 UTC, jancborchardt commented
You missed the second thing from my comment above ;)

> Also the text should best be left-aligned with the titles of the apps below, meaning moved a bit to the right. :)

2019-10-22 21:08 UTC, GretaD commented
> (Titles of the apps, not the icons → so a bit more to the right even. :)

ohhh, sorry, clear now

2019-10-22 22:37 UTC, jancborchardt commented
Alright! Last 2 things design-wise:
- [ ] A bit of whitespace between the text and the button would be nice. 14px should be good. (Which equates to the font-size, and yes we should eventually add a variable for this)
- [ ] In your screenshot it only shows 1 app with available update but says "2 apps". If only 1 app has an update then we don’t need to show the "Update all". :)

2019-10-23 09:28 UTC, GretaD commented
> Alright! Last 2 things design-wise:
> 
>     * [ ]  A bit of whitespace between the text and the button would be nice. 14px should be good. (Which equates to the font-size, and yes we should eventually add a variable for this)

Ok, will do
>     * [ ]  In your screenshot it only shows 1 app with available update but says "2 apps". If only 1 app has an update then we don’t need to show the "Update all". :)

No, there are 2 apps that have an update. The screenshot is taken from all the apps page. If there;s only one, than the button it doesnt show.

2019-10-23 11:08 UTC, jancborchardt commented
Ah ok – in this screenshot from above it looks like there is just 1 app with update (Group folders), but I guess you were testing?

> ![updateall](https://user-images.githubusercontent.com/12728974/67304051-92e19b80-f4f3-11e9-9de5-572cc6fbf5fc.png)

2019-10-23 11:46 UTC, GretaD commented
> Ah ok – in this screenshot from above it looks like there is just 1 app with update (Group folders), but I guess you were testing?
> 
> > ![updateall](https://user-images.githubusercontent.com/12728974/67304051-92e19b80-f4f3-11e9-9de5-572cc6fbf5fc.png)

Thats because the other app that needs an update is a disabled one, and its in the end of the list and i cannot get it inside a screenshot(need to scroll), sorry, maybe i should have said that in the first screenshot.
But check, for instance the Updates category

2019-10-25 12:42 UTC, GretaD commented on apps/settings/css/settings.scss
> +		padding-left: 14px;
i cannot find a variable for this one. Do we have one?

2019-10-25 12:43 UTC, GretaD commented on apps/settings/css/settings.scss
> +		padding-left: 14px;
i cannot find a variable for 14px. Do we have one?

2019-10-25 13:00 UTC, skjnldsv commented on apps/settings/css/settings.scss
> +		padding-left: 14px;
Not that I'm aware of :)

2019-10-25 21:28 UTC, jancborchardt commented on apps/settings/css/settings.scss
> +		padding-left: 14px;
We don’t have any unit variables as of now, but some of the mockups @jenniferpiperek has been working on (cc @ma12-co) aim to establish that. :)

2019-11-01 12:37 UTC, GretaD commented
@jancborchardt @skjnldsv @ChristophWurst @juliushaertl can you please check if there is anything else to be done with this ticket?

2019-11-04 01:23 UTC, jancborchardt commented
Good to merge from my side, just check out the file conflict and the Drone failure. :)

2019-11-04 19:09 UTC, jancborchardt approved these changes

2019-11-04 19:10 UTC, jancborchardt commented on apps/settings/css/settings.scss
> +		padding-left: 14px;
Wait, actually this would lead to every primary button in the app list getting a left-padding. You need to be more specific there.

Also, the class is just ".primary". :)

2019-11-12 13:46 UTC, skjnldsv commented
Wrong button :D

/compile /

2019-11-14 15:15 UTC, ChristophWurst commented on apps/settings/src/components/AppList.vue
> +			const appsToUpdate = []
`appsToUpdate` is never assigned any real data?!

2019-11-22 15:06 UTC, ChristophWurst requested changes
Looks good otherwise :)

2019-11-22 15:06 UTC, ChristophWurst commented on apps/settings/src/components/AppList.vue
> +					{{ counter }} {{ t('settings', 'apps have an update available') }}
```suggestion
					{{ t('settings', '{counter} apps have an update available', {counter}) }}
```

Then translators can put the number wherever it makes sense for each language

2019-11-22 17:45 UTC, ChristophWurst approved these changes
Code looks good!

2019-11-23 16:15 UTC, gary-kim approved these changes

2019-11-26 15:26 UTC, jancborchardt commented
Drone is failing, can you check @GretaD?

2019-12-03 05:16 UTC, jancborchardt commented
Drone still erroring?

2019-12-03 07:14 UTC, skjnldsv commented
Unrelated

2019-12-03 07:15 UTC, merged

2019-12-03 13:13 UTC, GretaD commented
i have never been this happy because a pr was merged <3

2019-12-03 13:44 UTC, skjnldsv commented
Congrats @GretaD !