Expose currently active file list though OCA.Files.App
nextcloud/server pull request #17536
Opened 2019-10-14 18:12 UTC by juliushaertl

2019-10-14 19:12 UTC, skjnldsv approved these changes

2019-10-24 12:31 UTC, ChristophWurst requested changes

2019-10-24 12:31 UTC, ChristophWurst commented on apps/files/js/app.js
> +			this.currentFileList = this.fileList
```suggestion
			this.updateCurrentFileList(this.fileList);
```

Does the same, but seems cleaner if we have the explicit setter :)

2019-10-24 12:31 UTC, ChristophWurst commented on apps/files/js/app.js
> +		 * @return {OCA.Files.FileList}
could also be undefined/null?
```suggestion
		 * @return {?OCA.Files.FileList}
```

2020-08-25 20:43 UTC, juliushaertl commented on apps/files/js/app.js
> +		 * @return {OCA.Files.FileList}
Should not happen since it is set in the initialize function, but added just to be sure.

2020-08-26 05:13 UTC, skjnldsv commented
For what do you need this?
I'm cautious to add new specific 'apis' to files as this will make it harder to migrate everything to vue

2020-08-26 05:54 UTC, juliushaertl commented
> For what do you need this?

This would allow to trigger updates of the file list from apps even if it is not the All files view that is used. E.g. when a file is saved in Collabora we trigger a reload of the filelist in the background so that the view is updated once closed. 

> I'm cautious to add new specific 'apis' to files as this will make it harder to migrate everything to vue

Yes, this is only an intermediate step and will require apps that use it to adjust when the files app is being migrated. However those apps already rely heavily on the FileList object so those would need to be migrated anyways then.

2020-08-26 06:23 UTC, skjnldsv approved these changes

2020-08-26 07:44 UTC, ChristophWurst approved these changes

2020-08-26 09:57 UTC, merged