Pass on direct query parameter during login
nextcloud/server pull request #17548
Opened 2019-10-15 14:28 UTC by rullzer

If direct is set we should forward it again.
This to make SAML direct login work again.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2019-10-15 14:34 UTC, rullzer commented
/backport to stable17

2019-10-15 15:09 UTC, blizzz approved these changes
looks good

2019-10-15 16:14 UTC, ChristophWurst approved these changes

2019-10-15 17:46 UTC, skjnldsv requested changes
See comment

2019-10-16 11:27 UTC, schiessle commented on core/src/components/login/LoginForm.vue
> +				:value="direct">
because the "direct" parameter is what we use in various places at the moment, including SAML and GS

2019-10-16 12:58 UTC, schiessle commented
tested it successfully!

2019-10-16 13:47 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				:value="direct">
yeah, but it's coming as a prop, so we don't care about the name of the variable :)

2019-10-16 16:05 UTC, rullzer commented
It will be backported yes

2019-10-16 20:06 UTC, rullzer commented on core/src/components/login/LoginForm.vue
> +				:value="direct">
@skjnldsv you are right

2019-10-16 20:07 UTC, rullzer commented
Ok so i changed the code a bit.
Not direct is only set (and send) if you set direct=1 in the query. Which mimicks more the original behavior.

2019-10-16 20:11 UTC, skjnldsv approved these changes

2019-10-16 22:08 UTC, ChristophWurst approved these changes

2019-10-16 22:24 UTC, merged