🚧 Direct editing API to allow file editing using a one-time token
nextcloud/server pull request #17625
Opened 2019-10-21 15:01 UTC by juliushaertl

Early draft PR so @tobiasKaminsky has something to play with :wink: 

The idea is to unify the token generation and endpoints into a server API, so mobile apps and the desktop client can just query one endpoint instead of requiring individual implementation for every app.

## Still todo
- [ ] background job for token cleanup
- [ ] Issue different token for later requests (e.g. ajax calls done by the editor)
- [ ] Proper exception handling
- [ ] Use proper ITemplate implementation instead of array for template data
- [ ] Add flag to capabilities endpoint if the api is available

To be tested with https://github.com/nextcloud/text/pull/372

<details>
 <summary>API endpoints</summary>

## Obtain editor details

curl 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/direct?format=json' -H 'OCS-APIRequest: true'

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "editors": {
        "text": {
          "name": "Nextcloud Text",
          "mimetypes": [
            "text/markdown"
          ],
          "optionalMimetypes": [
            "text/plain"
          ],
          "secure": false
        }
      },
      "creators": {
        "textdocument": {
          "id": "textdocument",
          "name": "New text document",
          "extension": ".md",
          "templates": false
        },
        "textdocumenttemplate": {
          "id": "textdocumenttemplate",
          "name": "New text document from template",
          "extension": ".md",
          "templates": true
        }
      }
    }
  }
}
```

## Get the list of templates

curl 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/direct/templates/text/textdocumenttemplate?format=json' -H 'OCS-APIRequest: true'

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "1": {
        "id": "1",
        "extension": "md",
        "name": "Weekly ToDo",
        "preview": "https://cloud.bitgrid.net/apps/richdocuments/template/preview/832537"
      },
      "2": {
        "id": "2",
        "extension": "md",
        "name": "Meeting notes",
        "preview": "https://cloud.bitgrid.net/apps/richdocuments/template/preview/832537"
      }
    }
  }
}
```

## Create an empty file 

curl -X POST 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/direct/create?path=/foo1.md&editorId=text&creatorId=textdocument&format=json' -H 'OCS-APIRequest: true'

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "url": "https://nextcloud.local/index.php/apps/files/direct/DbAy3rzfdBosKJjtQyxjq5s9Wz5MAZsjf9cHRZ4LKALrjnawxRAXzncNRpbzYEbT"
    }
  }
}
```

## Create a file from a template

curl -X POST 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/direct/create?path=/foo1.md&editorId=text&creatorId=textdocumenttemplate&templateId=1&format=json' -H 'OCS-APIRequest: true'

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "url": "https://nextcloud.local/index.php/apps/files/direct/DbAy3rzfdBosKJjtQyxjq5s9Wz5MAZsjf9cHRZ4LKALrjnawxRAXzncNRpbzYEbT"
    }
  }
}
```

## Open a file

curl -X POST 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/direct/open?fileId=251&editorId=text&format=json' -H 'OCS-APIRequest: true'

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "url": "https://nextcloud.local/index.php/apps/files/direct/DbAy3rzfdBosKJjtQyxjq5s9Wz5MAZsjf9cHRZ4LKALrjnawxRAXzncNRpbzYEbT"
    }
  }
}
```
</details>

2019-10-21 18:09 UTC, kesselb commented on apps/files/lib/Controller/DirectEditingViewController.php
> +		$eventDispatcher->dispatch(RegisterDirectEditorEvent::class, new RegisterDirectEditorEvent($this->directEditingManager));
```suggestion
		$eventDispatcher->dispatchTyped(new RegisterDirectEditorEvent($this->directEditingManager));
```

2019-11-13 11:22 UTC, juliushaertl commented
Ready for a first round of review, I'll look into adding some tests

2019-11-14 10:32 UTC, ChristophWurst requested changes
Looks nice otherwise :)

2019-11-14 10:32 UTC, ChristophWurst commented on apps/files/lib/Controller/DirectEditingController.php
> +			$this->logger->logException($e);
you might want to add a `['message' => '...']` so it's easier to see where this exception is coming from (without having to go through the stack trace)

2019-11-14 10:32 UTC, ChristophWurst commented on apps/files/lib/Controller/DirectEditingViewController.php
> +		$eventDispatcher->dispatchTyped(new RegisterDirectEditorEvent($this->directEditingManager));
dispatching an event from the constructor makes me a bit suspicious. Could this be done in the `edit` method?

2019-11-14 10:32 UTC, ChristophWurst commented on composer.json
> +	"require": {
indentation seems off :)

2019-11-14 10:32 UTC, ChristophWurst commented on core/Migrations/Version18000Date20191014105105.php
> +		//$schema->dropTable('direct_edit');
remove?

2019-11-14 10:32 UTC, ChristophWurst commented on core/Migrations/Version18000Date20191014105105.php
> +		if (!$schema->hasTable('direct_edit')) {
we've had this discussion before, but I'd argue that this check does not make sense. you should be able to assume the migration hasn't been run, hence that table can't exist at this point. and even if it did, you wouldn't know if has the correct columns afterwards :man_shrugging:

2019-11-14 10:32 UTC, ChristophWurst commented on lib/public/DirectEditing/ITemplate.php
> +abstract class ITemplate implements JsonSerializable {
```suggestion
abstract class ATemplate implements JsonSerializable {
```

2019-11-21 18:12 UTC, juliushaertl commented on core/Migrations/Version18000Date20191014105105.php
> +		if (!$schema->hasTable('direct_edit')) {
Still doesn't hurt to have it, but I'm also fine with removing.

2019-11-22 10:30 UTC, ChristophWurst commented on core/Migrations/Version18000Date20191014105105.php
> +		if (!$schema->hasTable('direct_edit')) {
My argument is that is that we shouldn't catch undefined state here. If we ignore it, it will :boom: later somewhere else. Thus I think failing hard in this very unlikely edge case is fine.

2019-11-22 10:36 UTC, ChristophWurst requested changes
Just a few nitpicks. The rest looks great!

2019-11-22 10:36 UTC, ChristophWurst commented on lib/public/DirectEditing/ACreateFromTemplate.php
> +	 * @return array
`string[]`?

2019-11-22 10:36 UTC, ChristophWurst commented on lib/public/DirectEditing/IEditor.php
> +	 * @return array
`string[]`?

2019-11-22 10:36 UTC, ChristophWurst commented on lib/public/DirectEditing/IEditor.php
> +	 * @return array
`string[]`?

2019-11-22 10:36 UTC, ChristophWurst commented on version.php
> +$OC_Version = array(18, 0, 0, 2);
I think the files bump is enough, no?

2019-11-22 10:36 UTC, ChristophWurst commented on apps/files/lib/Controller/DirectEditingController.php
> +		$this->eventDispatcher->dispatch(RegisterDirectEditorEvent::class, new RegisterDirectEditorEvent($this->directEditingManager));
```suggestion
		$this->eventDispatcher->dispatchTyped(new RegisterDirectEditorEvent($this->directEditingManager));
```

:wink:

2019-11-22 10:36 UTC, ChristophWurst commented on apps/files/lib/BackgroundJob/CleanupDirectEditingTokens.php
> +	const INTERVAL_MINUTES = 15 * 60;
```suggestion
	private const INTERVAL_MINUTES = 15 * 60;
```

2019-11-25 13:15 UTC, juliushaertl commented on version.php
> +$OC_Version = array(18, 0, 0, 2);
Hm, the database is in code, so I guess we still need it here as well

2019-11-25 13:18 UTC, juliushaertl commented
After discussing with @tobiasKaminsky I moved the editor details to the files app capabilities as this will save us one additional request on the apps and will have a rather minimal performance impact on the server side, since most of the data should be static and coming from hardcoded values in php classes.

2019-11-25 14:16 UTC, ChristophWurst commented on version.php
> +$OC_Version = array(18, 0, 0, 2);
Right! My bad.

2019-11-25 14:16 UTC, ChristophWurst approved these changes
Looks great!

2019-11-26 13:48 UTC, rullzer requested changes

2019-11-26 13:48 UTC, rullzer commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
Lets make this a separate endpoint. The capabilities are already to huge and since we add a new entry for each extention this can become even bigger. Lets just have

`'directEditing' => [
  'supported' => true,
  'url' => SOMELINK
]`

Where somelink gives you all the direct editing info you need.
That way we can extend and let it grow without getting a huge capabilities list.

You already see it with the insane list we add in richdocuments....

2019-11-26 13:52 UTC, juliushaertl commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
We had this before, but this requires every client do one additional request when opening the app. (see previous comment)

2019-11-26 14:04 UTC, rullzer commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
Well but then the clients are going to be unhappy since they have to parse a list like https://github.com/nextcloud/richdocuments/blob/master/lib/Capabilities.php#L39-L69 all the time. Plus we also serve this on every page we load in the webui which will slow down every web request.

2019-11-26 16:03 UTC, juliushaertl commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
Ok, let me then add some etag to the capabilities next to the link so that clients only need to request the endpoint when something has changed. Does that sound good @tobiasKaminsky @rullzer ?

2019-11-27 12:20 UTC, tobiasKaminsky commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
Fine. Luckily I can do a git revert :-P

2019-11-27 13:38 UTC, juliushaertl commented on apps/files/lib/Capabilities.php
> +				'directEditing' => $this->getDirectEditingCapabilitites()
Done

2019-11-28 07:44 UTC, rullzer approved these changes
Lets do this then!

2019-11-28 07:49 UTC, merged

2019-12-10 09:18 UTC, tobiasKaminsky commented
Is this documentation somewhere available?

2019-12-10 09:36 UTC, rullzer commented
Nope. @juliushaertl be sure to add it to the docs indeed

2019-12-10 14:47 UTC, marinofaggiana commented
Please update and verify the document: "API endpoints" because is incorrect. thanks

2019-12-13 10:03 UTC, marinofaggiana commented
@juliushaertl the "Get the list of templates" if do not exists a templates do not return nothing, but the Richdocuments API return one record with template of name "Empty", can we use the same logic ?