More filepicker improvements
nextcloud/server pull request #1768
Opened 2016-10-17 12:30 UTC by icewind1991

2016-10-17 12:53 UTC, nickvergessen commented
Would also be nice, if double clicking a valid entry would "choose" it.

2016-10-18 09:43 UTC, jancborchardt commented
@icewind1991 nice work! Added on top of it some nice layout fixes:
![capture du 2016-10-18 11-42-50](https://cloud.githubusercontent.com/assets/925062/19472572/1533ca7e-9528-11e6-9733-f2ace1df2220.png)

Please review @nextcloud/javascript @nextcloud/designers :)

2016-10-18 12:02 UTC, icewind1991 commented
Fixed an issue with the "file exists" dialog that was introduced by @jancborchardt's changes

2016-10-18 15:10 UTC, MorrisJobke requested changes
Calling `OCdialogs.filepicker('test')`doesn't work properly anymore - only folders are shown and choosing doesn't work anymore :(

2016-10-18 15:10 UTC, MorrisJobke commented on core/js/oc-dialogs.js
> +				return file.type === 'dir' || filter.indexOf(file.mimetype) !== -1;
By default the mimetype filter is `undefined, which causes an error here

2016-10-19 12:43 UTC, jancborchardt commented
@icewind1991 I added proper left margin for the title. But the filepicker doesn’t seem to work anymore:
`oc-dialogs.js?v=a057f20…:799 Uncaught TypeError: Cannot read property 'find' of undefined`
![capture du 2016-10-19 14-42-28](https://cloud.githubusercontent.com/assets/925062/19519051/6b60068c-960a-11e6-912f-ea9187c4ab94.png)
cc @nextcloud/javascript

2016-10-19 14:05 UTC, icewind1991 commented
@jancborchardt can't reproduce your issue

2016-10-19 18:31 UTC, jancborchardt commented
Ok, then I guess it’s ready for @nextcloud/javascript for review :)

2016-10-20 11:13 UTC, MorrisJobke approved these changes

2016-10-20 11:14 UTC, MorrisJobke commented
I fixed an overflow issue and applied the proper padding on the right side (it was changed from 10 to 15 px).

I tested this with IE11, Edge, Safari, Firefox and Chrome and it looks good 👍

2016-10-20 11:29 UTC, jancborchardt commented
@MorrisJobke I intentionally made it so the scrollbar is all the way to the right in the dialog. It looks strange otherwise. :)

2016-10-20 12:39 UTC, MorrisJobke commented
> @MorrisJobke I intentionally made it so the scrollbar is all the way to the right in the dialog. It looks strange otherwise. :)

So you think this looks good? 😉 

![bildschirmfoto 2016-10-20 um 14 38 45](https://cloud.githubusercontent.com/assets/245432/19560025/f4c579ac-96d2-11e6-8d0f-a8a8a92629aa.png)

2016-10-20 12:41 UTC, MorrisJobke commented
My version:

![bildschirmfoto 2016-10-20 um 14 39 57](https://cloud.githubusercontent.com/assets/245432/19560064/28b59a9e-96d3-11e6-9d86-0d8dd0cd234d.png)

Your version:

![bildschirmfoto 2016-10-20 um 14 40 20](https://cloud.githubusercontent.com/assets/245432/19560074/37d7d154-96d3-11e6-9eb1-7d13291a8dc8.png)


I still like the one with the consistent paddings 😉 Any other opinions? cc @nextcloud/designers

2016-10-20 12:46 UTC, jancborchardt commented
@MorrisJobke right … also the scrollbar has a white background. And it would need to be flush on the left then too.

:+1: for now, any improvements can come later. Thanks!

2016-10-20 12:46 UTC, merged

2016-10-20 12:49 UTC, skjnldsv commented
Agreed with @MorrisJobke. Seems too far to the right :)

2016-10-22 10:48 UTC, Espina2 commented
I think the position of the button is very weird. And I think the shadow you use in all over the place is to strong and spread. If this are a popup the background should be more black to.