[provisioning_api] Optimization for for large installations
nextcloud/server pull request #17718
Opened 2019-10-28 15:01 UTC by mikaelh

Patch to optimize for large installations where subadmins have access to many groups (>250)

This fix reduces API calls to editUser (ex change locale/display name) from >2 minutes (!) to ~3 seconds per call in average in current installation.

Signed-off-by: Mikael Hammarin <mikael@try2.se>

2019-10-28 15:50 UTC, kesselb commented on lib/private/SubAdmin.php
> +		;
```suggestion
```

2019-10-28 15:52 UTC, kesselb commented
Thanks for your patch :tada:

2019-10-28 17:28 UTC, nickvergessen requested changes

2019-10-28 17:28 UTC, nickvergessen commented on lib/private/SubAdmin.php
> +		$qb = $this->dbConn->getQueryBuilder();
This only works with the default groups backend, so this is not possible. But I have another idea in mind to make this faster

2019-10-28 17:28 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +			if ($this->groupManager->isAdmin($currentLoggedInUser->getUID())
This is a nice turn around 👍

2019-10-29 06:24 UTC, mikaelh commented on lib/private/SubAdmin.php
> +		$qb = $this->dbConn->getQueryBuilder();
> This only works with the default groups backend, so this is not possible. But I have another idea in mind to make this faster

Ah you are right. I did not think about that. If you point me in a direction I can look into it?

2019-10-31 18:41 UTC, blizzz commented on lib/private/SubAdmin.php
> +		$qb = $this->dbConn->getQueryBuilder();
Supposedly, fetch the user's groups and check whether there is an overlap.

2019-12-13 12:18 UTC, blizzz commented
What's the state here?

2020-04-27 06:41 UTC, nickvergessen commented
Did a new PR in https://github.com/nextcloud/server/pull/20677

2020-04-27 06:41 UTC, closed without merging