Add a transfer ownership background job
nextcloud/server pull request #17736
Opened 2019-10-29 11:43 UTC by rullzer

Allow users to initiate transfer ownership

We need to find some way to initiate this.

* Once it is initiated the recipieint should get a notification to accept or decline the transfer
* Initiator is noticed about accept/decline
* If accepted transfer is scheduled
* Transfer happens
* Both parties are notified when transfer completes

TODO:
- [x] The actual background job
- [ ] Find some UI that works to send a file/folder to another user
- [ ] Notification ping pong
- [ ] Activities

2019-10-30 08:12 UTC, nickvergessen requested changes
Blocking merge as per private chat

2019-11-26 09:48 UTC, skjnldsv commented on apps/files/lib/AppInfo/Application.php
> +		parent::__construct(self::APP_ID, $urlParams);
Nice!

2019-11-26 09:48 UTC, skjnldsv commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			->setApp('files')
```suggestion
			->setApp($this->appName)
```
 ?

2019-11-26 09:49 UTC, skjnldsv commented on apps/files/lib/Controller/TransferOwnershipController.php
> +			->setApp('files')
```suggestion
			->setApp($this->appName)
```

2019-11-26 09:50 UTC, skjnldsv commented on apps/files/lib/Notification/Notifier.php
> +		return 'files';
Use APP_ID from `Application`?

2019-11-26 09:52 UTC, skjnldsv commented on apps/files/src/components/TransferOwnershipDialogue.vue
> +			axios.post(url, data)
Use async await please :)

2019-11-26 10:36 UTC, rullzer commented
Ah mmm let me actually finish my todos...

2019-11-26 10:36 UTC, rullzer commented on apps/files/src/components/TransferOwnershipDialogue.vue
> +			axios.post(url, data)
@ChristophWurst :wink:

2019-11-26 11:37 UTC, ChristophWurst commented on apps/files/src/components/TransferOwnershipDialogue.vue
> +			axios.post(url, data)
@skjnldsv fix

2019-11-26 11:40 UTC, skjnldsv commented on apps/files/src/components/TransferOwnershipDialogue.vue
> +			axios.post(url, data)
No time

2019-11-27 07:48 UTC, rullzer commented
Thinking more about it maybe I should not store the path bt just the fileid. Seems saver (plus less error prone)

2019-11-27 07:59 UTC, rullzer commented
Maybe instead of the path store the file id + name of the node? That makes it less error prone.

2019-11-27 07:59 UTC, rullzer commented
We should probably have autocomplete on the user search?

2019-11-27 08:00 UTC, ChristophWurst commented on apps/files/lib/Controller/TransferOwnershipController.php
> +	public function reject(string $id): DataResponse {
```
	 /**
	 * @NoAdminRequired
	 */
```

2019-11-27 08:07 UTC, ChristophWurst requested changes
Otherwise good to go

2019-11-27 08:07 UTC, ChristophWurst commented on apps/files/lib/Migration/Version11301Date20191113195931.php
> + * Auto-generated migration step: Please modify to your needs!
remove

2019-11-27 08:07 UTC, ChristophWurst commented on apps/files/lib/Migration/Version11301Date20191113195931.php
> +		if ($schema->hasTable('user_transfer_ownership')) {
my usual remark: if we really reach the state where the table already exists, something fishy is going on. and then we can't be sure about the table structure later on. I would rather see this fail hard here.

2019-11-27 08:25 UTC, rullzer commented
Good to go now form my PoV

2019-11-27 08:39 UTC, juliusknorr requested changes

2019-11-27 08:39 UTC, juliushaertl commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			$this->failedNotication($transfer);
It should return here

2019-11-27 08:42 UTC, nickvergessen commented on apps/files/lib/Controller/TransferOwnershipController.php
> +		$transferId = (int)$id;
Why do you do this? It hurts the kittens :crying_cat_face: !

You can request an int directly:
https://github.com/nextcloud/spreed/blob/d4fc586f1a796b8cb19cff543b668470556e44b2/lib/Controller/CallController.php#L84

We have magic in place to do the casting as per controller requirements:
https://github.com/nextcloud/server/blob/68748d4f85dd23238aaafb787b1c341f0f2f0419/lib/private/AppFramework/Http/Dispatcher.php#L142-L166

2019-11-27 08:43 UTC, nickvergessen commented on apps/files/lib/Migration/Version11301Date20191113195931.php
> +
missing header

2019-11-27 08:49 UTC, nickvergessen requested changes

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Migration/Version11301Date20191113195931.php
> +		$table->addColumn('file_id', 'integer', [
```suggestion
		$table->addColumn('file_id', 'bigint', [
```

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +				'POST'
```suggestion
				\OCP\Notification\IAction::TYPE_POST
```

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Controller/TransferOwnershipController.php
> +	public function accept(string $id): DataResponse {
```suggestion
	public function accept(int $id): DataResponse {
```

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +			->setParsedSubject(str_replace('{user}', $param['sourceUser'], $l->t('Incomming file transfer from {user}')));
mind to group the subject methods and the message methods? I see someone tripping here already because the order is subject-message-message-subject

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +			->setParsedMessage($l->t('File transfer failed'))
And here you tripped yourself. Mixed up message and subject, same below

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +			->setParsedMessage($l->t('File transfer done'))
same here

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +			->setParsedMessage($l->t('File transfer done'))
and here

2019-11-27 08:49 UTC, nickvergessen commented on apps/files/lib/Settings/PersonalSettings.php
> +	public function getPriority() {
and return types?

2019-11-27 08:49 UTC, juliushaertl commented
ToDo for later polishing:

- [ ] The UI should have some visual feedback

2019-11-27 08:50 UTC, nickvergessen commented on apps/files/lib/Notification/Notifier.php
> +				'POST'
Same applies to all actions

2019-11-27 08:50 UTC, nickvergessen commented on apps/files/lib/Controller/TransferOwnershipController.php
> +	public function accept(string $id): DataResponse {
Same applies to all methods

2019-11-27 08:52 UTC, nickvergessen commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +		if (count($nodes) === 0) {
Whiel you are on it for the missing return below:

```suggestion
		if (empty($nodes)) {
```

2019-11-27 08:54 UTC, nickvergessen commented on apps/files/lib/Controller/TransferOwnershipController.php
> +			->setObject('transfer', (string)$transferOwnership->getId());
This notification is not sent?

2019-11-27 09:24 UTC, rullzer commented on apps/files/lib/Controller/TransferOwnershipController.php
> +		$transferId = (int)$id;
Leftover from an earlier commit

2019-11-27 09:29 UTC, ChristophWurst commented
>  The UI should have some visual feedback

Partly done with https://github.com/nextcloud/server/pull/17736/commits/24178cf3448e384ce026ff1450fb2ff13d4afd0b but not pretty.

2019-11-27 09:30 UTC, rullzer commented
All resolved.

2019-11-27 11:54 UTC, juliushaertl commented on apps/files/src/components/TransferOwnershipDialogue.vue
> -	.addMimeTypeFilter('httpd/unix-directory')
Intended? Now directories cannot be selected anymore.

2019-11-27 11:55 UTC, rullzer commented on apps/files/src/components/TransferOwnershipDialogue.vue
> -	.addMimeTypeFilter('httpd/unix-directory')
Yes it is the great joy of the selector. We want to be able tos elect 

* files
* folders
* root folder

2019-11-27 12:02 UTC, juliushaertl commented on apps/files/src/components/TransferOwnershipDialogue.vue
> -	.addMimeTypeFilter('httpd/unix-directory')
Ah ok, just was thinking that it would only transfer directories accoring to the UI. Anyway transfering files always fails for me. Let me check where that goes wrong.

2019-11-27 12:11 UTC, juliushaertl commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			$this->failedNotication($transfer);
```
{"reqId":"R2pdNafqEbdpeJo4B31d","level":3,"time":"2019-11-27T12:10:41+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":{"Exception":"OCA\\Files\\Exception\\TransferOwnershipException","Message":"Unknown path provided: 3hedh35h.odt","Code":1,"Trace":[{"file":"/var/www/html/apps/files/lib/BackgroundJob/TransferOwnership.php","line":117,"function":"transfer","class":"OCA\\Files\\Service\\OwnershipTransferService","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\User\\User"},"3hedh35h.odt"]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":77,"function":"run","class":"OCA\\Files\\BackgroundJob\\TransferOwnership","type":"->","args":[{"id":18}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":46,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":124,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/apps/files/lib/Service/OwnershipTransferService.php","Line":95,"CustomMessage":"--"},"userAgent":"--","version":"18.0.0.1"}
```

2019-11-27 12:12 UTC, juliushaertl commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			$this->failedNotication($transfer);
```suggestion
			$this->logger->logException($e);
			$this->failedNotication($transfer);
```

2019-11-27 12:18 UTC, juliushaertl commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			$this->failedNotication($transfer);
Occurs when transfering a file in the root directory

2019-11-27 13:53 UTC, rullzer commented on apps/files/lib/BackgroundJob/TransferOwnership.php
> +			$this->failedNotication($transfer);
Fixed by @ChristophWurst

2019-11-27 13:54 UTC, rullzer commented
Ok review time. lets get this in

2019-11-27 20:03 UTC, juliusknorr approved these changes
Tested and works :+1:

2019-12-02 09:25 UTC, ChristophWurst commented on apps/files/src/components/TransferOwnershipDialogue.vue
> -	.addMimeTypeFilter('httpd/unix-directory')
There was something in the transer ownership service that checked if the path is a directory. I changed it to also allow files.

2019-12-02 11:20 UTC, ChristophWurst approved these changes
Tested and works :+1:

2019-12-02 18:06 UTC, merged