switch to Files Node API for zip generation
nextcloud/server pull request #17822
Opened 2019-11-05 15:35 UTC by blizzz

since it is disencouraged to use the static Filesystem methods

2019-11-05 15:36 UTC, blizzz commented
/backport to stable17

2019-11-06 08:34 UTC, rullzer approved these changes

2019-11-06 09:24 UTC, icewind1991 requested changes

2019-11-06 09:24 UTC, icewind1991 commented on lib/private/legacy/files.php
> +						$owner = \OC\Files\Filesystem::getOwner($file);
this shouldn't use the owner but the current user

2019-11-06 13:46 UTC, blizzz commented on lib/private/legacy/files.php
> +						$owner = \OC\Files\Filesystem::getOwner($file);
@icewind1991 what about unauthenticated users, on public shares?

2019-11-06 14:44 UTC, icewind1991 commented on lib/private/legacy/files.php
> +						$owner = \OC\Files\Filesystem::getOwner($file);
They have the "current user" set correctly afaik, since it's also needed for the old `Filesystem` stuff to work (worth double testing though)

2019-11-06 15:06 UTC, blizzz commented on lib/private/legacy/files.php
> +						$owner = \OC\Files\Filesystem::getOwner($file);
nope, using `$userFolder = \OC::$server->getUserFolder();` returns `null` in that case. Of cours we can try that first and fall back to the owner? Or does it open any loophole? Previously it also only just read it. IIRC it's best to avoid using root folder directly for performance.

2019-11-06 15:39 UTC, icewind1991 commented on lib/private/legacy/files.php
> +						$owner = \OC\Files\Filesystem::getOwner($file);
`\OC::$server->getRootFolder()->get(Filesystem::getRoot())` would always have the same behavior as using the old api

2019-11-07 08:46 UTC, blizzz commented
/backport to stable16

2019-11-07 08:55 UTC, icewind1991 approved these changes

2019-11-07 10:03 UTC, merged