Adds possibility to set user documentation l10n.
nextcloud/server pull request #17870
Opened 2019-11-08 19:55 UTC by pierreozoux

I still need to figure out how is the documentation shipped in the Nextcloud package, so I can make sure that pt, fr and de are also shipped.

Relates to https://github.com/nextcloud/documentation/issues/216

Thanks for your help!

2019-11-08 21:58 UTC, kesselb commented
Hmm. `nextcloud-17.0.0.zip` is already ~80mb big. Around 25mb are for the english documentation. Could you imagine to offer the documentation for other languages as apps via the app store? We probably need some way how to register the app (e.g. user_manual_de) to the help controller. Probably shipping also english as app might reduce the archive and makes it easier to ship doc updates.

2019-11-09 08:48 UTC, pierreozoux commented
@kesselb I just checked, removing images and zipping the user_manual folder, it weights only 35105bits. So adding one language documentation, is just 35kb, adding the ~100language would add 3.5mb. I agree that size does matter, and it is important for various reasons, but I propose that we discuss about it in another issue.

2019-11-09 09:32 UTC, kesselb commented on apps/settings/lib/Controller/HelpController.php
> +		define('TRANSLATED_LANGUAGES', array(
Please make this a class member. e.g: `private const TRANSLATED_LANGUAGES`

2019-11-09 09:32 UTC, kesselb commented on apps/settings/lib/Controller/HelpController.php
> +		define('TRANSLATED_LANGUAGES', array(
I would also prefer a better name like `DOCUMENTATION_LANGUAGES`

2019-11-09 09:34 UTC, kesselb commented
Just had a look at `user_manual_de` and it looks outdated to me. We should not ship outdated documentation because this will lead to confusion. Have you thought about the idea of shipping docs for other languages as apps?

2019-11-10 07:51 UTC, pierreozoux commented
Agree, I'll remove the DE, and check the brazilian.
We still have to do the french. Anyway, we have to coordinateur between the documentation repot and here.

About the app, Im maybe biased because I don't want to create a repo, create an app, write tests, write a CICD pipeline and maintain an app for this 5 lines PR, but I think Nextcliud has to be consistent. 
I'm not opposed to the idea of splitting into apps, but IMHO, the split has to happen, either at the i18n or the documentation.

Currently Nextcloud ships i18n for the app itself and the documentation. So to be consistent,  I think it has to ship the documentation translated too.
But I wouldn't be mad if Nextcloud decides that i18n or documentation (or both even) is now an optional package.

But again, I think this is another discussion than this PR.

2019-11-10 07:52 UTC, pierreozoux commented on apps/settings/lib/Controller/HelpController.php
> +		define('TRANSLATED_LANGUAGES', array(
I'll fix when in front of computer, thanks for the advice.

2019-11-11 13:49 UTC, juliusknorr requested changes
I'm strongly against doing this until there is a proper way to have translated documentation somehow kept up to date with the English one. Current de and pt_BR didn't receive an update in the last half year.

Besides that, maybe we should find a way to not ship the duplicate documentations (with images) as individual folders but somehow just have the text translations?

2019-11-11 18:28 UTC, pierreozoux commented
Well :) the english documentation is not that up to date either ;)

https://github.com/nextcloud/documentation/blob/master/user_manual/whats_new.rst (check the date of the last change)

Im also tackling this translation thing here 

https://github.com/nextcloud/documentation/issues/216#issuecomment-551291335

I'm not asking to merge right away, I'm asking for a bit of support to help me roll the ball around this topic:) thanks for your help :)

The next thing I need is to understand, where is the CI that packages the Nextcloud zip and fetch documentations so I can make sure it fetches the right thing at the right time.

2020-07-02 18:38 UTC, ChristophWurst commented
I'd say let's close this for now. This hasn't received any update in quite a while and this is something that needs to be discussed more.

2020-07-06 13:30 UTC, pierreozoux commented
@ChristophWurst I'm still waiting https://github.com/nextcloud/documentation/pull/1824 to be merged first.

Can we keep it open? (and help move the other one?)

2021-03-05 11:12 UTC, pierreozoux commented
So :)

![image](https://user-images.githubusercontent.com/1863453/110107686-863daa80-7dab-11eb-9df6-1e25f0f6a88d.png)

Now we have an automated way to translate documentation \o/

But it is still not shipped inside Nextcloud:

![image](https://user-images.githubusercontent.com/1863453/110107906-cb61dc80-7dab-11eb-94a9-7b6fe20b20b2.png)

(this screenshot is 18.0.14)

I have a simple question, where (I searched) is the line that adds the documentation inside the Nextcloud zip? I just need the answer to that, and then I'll do the necessary PR that is needed to be solved before this PR :)

2024-02-27 13:06 UTC, skjnldsv commented
Hey @pierreozoux seems like this PR is quite old and the direction since changed.
As there is no feedback since a while I will close this ticket.

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2024-02-27 13:06 UTC, closed without merging