move select2 styles to core so it's universal, not only for tags
nextcloud/server pull request #1789
Opened 2016-10-18 17:51 UTC by jancborchardt

Before & after: Much more breathing space, nice Nextcloud style, and proper connection to the input field:
![capture du 2016-10-18 19-46-21](https://cloud.githubusercontent.com/assets/925062/19489481/bab175ee-956b-11e6-9872-fbb433c5fa21.png)![capture du 2016-10-18 19-34-24](https://cloud.githubusercontent.com/assets/925062/19489483/bac9da26-956b-11e6-9ff6-276674f22d31.png)

Please review @nextcloud/designers @ErikPel @nextcloud/javascript you can test it with:
- System tags in the files sidebar
- Enabling apps only for specific users in apps mgmt
- New person selector in Spreed app: https://github.com/nextcloud/spreed/pull/55

The one problem which still occurs (also with old version) is that the dropdown is about 3 pixels too wide on the right. Any idea @nextcloud/javascript? (NOT A BLOCKER)

2016-10-18 18:04 UTC, LukasReschke commented
Works locally. Looks nice! 🚀

2016-10-18 18:12 UTC, skjnldsv commented
@jancborchardt it's because the dropdown uses the width of `.select2-choices`
And it has padding and margin wich sums up to 333px instead of what you wanted.

2016-10-18 18:14 UTC, skjnldsv requested changes

2016-10-18 18:14 UTC, skjnldsv commented on core/css/inputs.css
> +	margin: 3px 3px 3px 0 !important;
here this is you issue @jancborchardt

2016-10-18 18:15 UTC, skjnldsv commented
Ps: there's a lot of !important overriding. Is this really necessary? Shouldn't we load the jquery theme before instead?

2016-10-18 18:19 UTC, jancborchardt commented
> Ps: there's a lot of !important overriding. Is this really necessary? Shouldn't we load the jquery theme before instead?

I agree. @MorrisJobke @LukasReschke how can we change the order here? The inputs.css should be one of the last loaded.

2016-10-18 18:22 UTC, MorrisJobke commented
> I agree. @MorrisJobke @LukasReschke how can we change the order here? The inputs.css should be one of the last loaded.

Crash course for @jancborchardt how to do this:

1. use the search tool of your choice to search for where the CSS is imported
2. change the order there
3. don't always out source this to other people - even if you think this would be nice because they know where - we are no weird dudes who have all the files and lines in our head - we also always use the search tools

2016-10-18 18:25 UTC, MorrisJobke commented
> don't always out source this to other people - even if you think this would be nice because they know where - we are no weird dudes who have all the files and lines in our head - we also always use the search tools

https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/legacy/template.php#L120

2016-10-18 18:27 UTC, skjnldsv commented
The order is reversed when implementing. So in the file @MorrisJobke pointed (thanks :wink: ) you need to pu inputs BEFORE jquery! :grin:

2016-10-18 18:28 UTC, jancborchardt commented
@MorrisJobke I searched for it, but since it was called legacy I assumed it’s not used anymore. There was another file which looked like it’s done there and it seemed like it just loaded all the files from the CSS directory. So thanks for helping.

2016-10-18 18:38 UTC, jancborchardt commented
Experimented with removing all the !importants and with changing the order – doesn’t work. If anyone can make it work I’m happy for enhancements, but I’d say let’s get it in.

2016-10-18 18:52 UTC, skjnldsv commented
This is strange! 😕

2016-10-18 18:52 UTC, skjnldsv approved these changes

2016-10-18 19:10 UTC, skjnldsv commented
@jancborchardt maybe we should add this into the systemtags apps? Since this is only used here?

2016-10-18 19:57 UTC, MorrisJobke commented
> The order is reversed when implementing. So in the file @MorrisJobke pointed (thanks 😉 ) you need to pu inputs BEFORE jquery! 😁

Correct - this is a bit weird, but you figured it out 😉

2016-10-18 20:04 UTC, MorrisJobke commented
:+1:

2016-10-18 20:05 UTC, merged

2016-10-18 22:29 UTC, jancborchardt commented
> maybe we should add this into the systemtags apps? Since this is only used here?

No – as said above it’s also used elsewhere like app mgmt and the spreed app. :) That’s the point of this PR, to make the select2 style adjustments more general.

2016-10-19 06:22 UTC, skjnldsv commented
Okay! :)
So maybe we should add the select2 style injection in core and not systemtags then :p

2016-10-19 09:10 UTC, jancborchardt commented
@skjnldsv that’s what I did here, moved most of the select2 styles from systemtag.css to core/css/inputs.css ;)

2016-10-19 09:14 UTC, skjnldsv commented
Yes, but I mean the `addStyle` function from https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/legacy/template.php#L120

Would be better than loading it from here https://github.com/nextcloud/server/blob/master/apps/systemtags/appinfo/app.php#L35

2016-10-19 10:09 UTC, jancborchardt commented
@skjnldsv good point! Do you want to do the change in a pull request? :)

2016-10-19 10:17 UTC, skjnldsv commented
I'm busy with the scss! :p 
Do it !

![demandingfemaleflyingfish-size_restricted](https://cloud.githubusercontent.com/assets/14975046/19514988/f3c99c28-95f5-11e6-86a9-6de7c0aa90b7.gif)