Bump sabre
nextcloud/server pull request #1792
Opened 2016-10-18 21:06 UTC by rullzer

- [ ] Requires https://github.com/nextcloud/3rdparty/pull/20

Uses: https://github.com/owncloud/core/pull/26115

Lets see what CI thinks of this!

2016-10-19 04:30 UTC, phsc commented
#1427

2016-10-20 10:40 UTC, MorrisJobke commented
> Lets see what CI thinks of this!

It says 🚫 ❗️ 

```
1) OCA\DAV\Tests\unit\CalDAV\CalendarTest::testPrivateClassification with data set #0 (3, false)
Undefined index: {http://owncloud.org/ns}owner-principal
/drone/src/github.com/nextcloud/server/apps/dav/lib/CalDAV/Calendar.php:286
/drone/src/github.com/nextcloud/server/apps/dav/lib/CalDAV/Calendar.php:208
/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/CalDAV/CalendarTest.php:230
2) OCA\DAV\Tests\unit\CalDAV\CalendarTest::testConfidentialClassification with data set #0 (3, false)
Undefined index: {http://owncloud.org/ns}owner-principal
/drone/src/github.com/nextcloud/server/apps/dav/lib/CalDAV/Calendar.php:286
/drone/src/github.com/nextcloud/server/apps/dav/lib/CalDAV/Calendar.php:193
/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/CalDAV/CalendarTest.php:319
```

2016-10-20 11:09 UTC, rullzer commented
Yeah I know. Have been messing with it to get the caldav intergration tests happy. But no real luck so far

2016-11-04 18:47 UTC, rullzer commented
Whee CI is happy. Review time!

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

2016-11-07 13:43 UTC, MorrisJobke commented
Works here fine 👍 I did some smoke testing with WebDAV and some file operations.

2016-11-07 13:43 UTC, MorrisJobke commented
@nickvergessen could we get smashbox for this?

2016-11-09 09:19 UTC, nickvergessen commented
Smashbox passed ✅

2016-11-09 09:54 UTC, LukasReschke requested changes
Looks good. Two new files are not really being tested. Will add myself quickly :)

2016-11-09 09:54 UTC, LukasReschke commented on apps/dav/lib/CalDAV/Schedule/Plugin.php
> +	protected function getAddressesForPrincipal($principal) {
Missing tests. Will quickly add myself.

2016-11-09 09:54 UTC, LukasReschke commented on apps/dav/lib/CalDAV/Plugin.php
> +	function getCalendarHomeForPrincipal($principalUrl) {
Missing tests. Will quickly add myself.

2016-11-09 10:55 UTC, LukasReschke approved these changes

2016-11-09 10:55 UTC, LukasReschke commented
Tests added and third-party rebased.

2016-11-09 12:06 UTC, merged