when a user was delete remove them from applicable list, unless...
nextcloud/server pull request #17920
Opened 2019-11-12 22:56 UTC by blizzz

it is the only user, then remove the mount

fixes #15258

@icewind1991 does it make sense to you? 

Then, we need basically the same for groups.

2019-11-13 08:47 UTC, nickvergessen approved these changes

2019-11-13 08:49 UTC, nickvergessen requested changes

2019-11-13 08:49 UTC, nickvergessen commented on apps/files_external/lib/Service/DBConfigService.php
> +		$query = $builder->select(['a.mount_id', $builder->createFunction('COUNT(a.mount_id) as count')])
Please use `$builder->func()->count('a.mount_id')`

2019-11-13 10:34 UTC, blizzz commented
Ah, edge case. It will remove mounts who are made accessible for groups plus this user.

2019-11-13 12:37 UTC, nickvergessen requested changes

2019-11-13 12:37 UTC, nickvergessen commented on apps/files_external/lib/Service/DBConfigService.php
> +		$this->modifyMountsOnDelete($uid, self::APPLICABLE_TYPE_GROUP);
Möp

2019-11-13 12:37 UTC, nickvergessen commented on apps/files_external/lib/Service/DBConfigService.php
> +	public function modifyMountsOnUserDelete(string $uid) {
Vooid

2019-11-13 12:37 UTC, nickvergessen commented on apps/files_external/lib/Service/DBConfigService.php
> +	public function modifyMountsOnUserDelete(string $uid) {
Same on all other methods

2019-11-13 13:27 UTC, blizzz commented on apps/files_external/lib/Service/DBConfigService.php
> +		$this->modifyMountsOnDelete($uid, self::APPLICABLE_TYPE_GROUP);
only checking whether you are paying attention 😇

2019-11-29 10:33 UTC, blizzz commented
@nickvergessen @icewind1991 can we get this in?

2019-11-29 11:52 UTC, icewind1991 approved these changes

2019-12-04 14:28 UTC, nickvergessen approved these changes

2019-12-04 14:28 UTC, merged

2019-12-04 16:13 UTC, blizzz commented
/backport to stable17

2019-12-04 16:13 UTC, blizzz commented
/backport to stable16

2019-12-04 16:13 UTC, blizzz commented
/backport to stable15

2019-12-05 10:52 UTC, juliushaertl commented on apps/files_external/lib/Service/DBConfigService.php
> +			->rightJoin('a', 'external_applicable', 'b', $builder->expr()->eq('a.mount_id', 'b.mount_id'))
Right join was not supported on sqlite iirc

2019-12-05 10:54 UTC, juliushaertl commented
Breaks quite some integration tests: https://drone.nextcloud.com/nextcloud/server/23756/32/3

2019-12-05 13:42 UTC, blizzz commented on apps/files_external/lib/Service/DBConfigService.php
> +			->rightJoin('a', 'external_applicable', 'b', $builder->expr()->eq('a.mount_id', 'b.mount_id'))
turning it around seems to work, same table after all. PR incoming,