Revert "Remove unneeded more-white icon"
nextcloud/server pull request #17931
Opened 2019-11-13 17:38 UTC by ChristophWurst

Reverts nextcloud/server#17806 because of https://github.com/nextcloud/server/pull/17806#issuecomment-553437325

2019-11-13 17:49 UTC, skjnldsv requested changes
@ChristophWurst I would argue you could also just update your app to use a proper icon class ;)
https://github.com/nextcloud/server/blob/afef15b07bbe97820745c5a863f3be8086c73eab/apps/twofactor_backupcodes/templates/challenge.php#L5

2019-11-13 17:57 UTC, ChristophWurst commented
Feel free to do that. I would argue that we shouldn't break core features :wink:

2019-11-13 19:28 UTC, rullzer approved these changes
* Lets revert
* Officially deprecate
* Kill it in 19

2019-11-14 07:51 UTC, skjnldsv approved these changes

2019-11-14 08:20 UTC, merged