Remove some more direct app instance creations
nextcloud/server pull request #18005
Opened 2019-11-19 13:38 UTC by ChristophWurst

2019-11-20 18:42 UTC, rullzer approved these changes

2019-11-21 10:12 UTC, blizzz approved these changes

2019-11-21 10:13 UTC, blizzz commented
> apps/user_ldap/appinfo/app.php:37 PhanUndeclaredFunction Call to undeclared function \OCA\User_LDAP\AppInfo\Application()

2019-11-21 10:14 UTC, blizzz requested changes

2019-11-21 10:14 UTC, blizzz commented on apps/user_ldap/appinfo/app.php
> +$app = \OC::$server->query(\OCA\User_LDAP\AppInfo\Application());
::class

2019-11-21 11:14 UTC, blizzz approved these changes

2019-11-26 08:20 UTC, merged