Share email to ocs
nextcloud/server pull request #1801
Opened 2016-10-19 12:02 UTC by rullzer

Fixes https://github.com/nextcloud/server/issues/1277

* Adds a new endpoint to send email for a link share
* Removed the possibility to notify recipients of a share
  - They can configure themselfs if they want notifications
  - Long term plan is still to also accept local shares
  - Would require adding a new endpoint that we'd have to support for long time

Currently we use the mailer as is. Which is not really testable. But I want a working version in sooner rather than later.

CC: @MorrisJobke @nickvergessen @LukasReschke @icewind1991

2016-10-19 12:03 UTC, rullzer commented
Also it seems the autocomplete for e-mail addresses is broken. So I disabled it for now. @nickvergessen we can't just search by e-mail on the sharee api right?

2016-10-19 15:47 UTC, MorrisJobke commented
> @nickvergessen we can't just search by e-mail on the sharee api right?

I don't think so, because the "email address style" is actually a remote share, right? cc @schiessle

2016-10-20 08:08 UTC, nickvergessen commented
@MorrisJobke it just sends the link from the link share field.

> We can't just search by e-mail on the sharee api right?

we can make it do so. As far as I can see it just looks into the contacts app for remote users atm.

2016-10-22 11:54 UTC, rullzer commented
@nickvergessen yeah it looks trough all the contacts for e-mail completion it seems. Would be nice if we could add that. I guess we could abuse the SHARE_TYPE_EMAIL for that. Bjorn might also use that in his share by email PR. But searching there is the same I'd say.

2016-10-23 13:25 UTC, jancborchardt commented
> Removed the possibility to notify recipients of a share
> They can configure themselves if they want notifications

Yeah! Thanks a lot @rullzer :)

2016-10-24 11:51 UTC, MorrisJobke requested changes

2016-10-24 11:51 UTC, MorrisJobke commented on core/js/shareitemmodel.js
> +				OC.dialogs.alert(t('core', result.data.message), t('core', 'Warning'));
Where is the `result` coming from?

2016-10-24 11:51 UTC, MorrisJobke commented on core/js/shareitemmodel.js
> +			}).	fail(function(xhr) {
Maybe the `xhr` should be named `result`? 😉

2016-10-25 12:38 UTC, rullzer commented on core/js/shareitemmodel.js
> +			}).	fail(function(xhr) {
yes copy paste error

2016-10-26 19:25 UTC, rullzer commented
Ok lets close this in favor of #1916

2016-10-26 19:25 UTC, closed without merging