Update style of log in page and header
nextcloud/server pull request #18082
Opened 2019-11-23 12:25 UTC by jancborchardt

Refresh for the next version, please review @juliushaertl @skjnldsv @karlitschek @rullzer 

## Before
![header bar before](https://user-images.githubusercontent.com/925062/69478539-350fde80-0e26-11ea-8c10-da2eca15a677.png)
![Log in screen before](https://user-images.githubusercontent.com/925062/69478540-350fde80-0e26-11ea-8b2f-ae43781f9653.png)

## After
- Nice slight fade to have some activity in the header
- More relevant background, app icons instead of dots
- I was also trying to give the primary buttons the fade, but there seem to be some issues with area (some part on the left stays blue?) and theming. So let’s do this for now, further stuff maybe later.

![header bar after](https://user-images.githubusercontent.com/925062/69478538-34774800-0e26-11ea-8b35-fc84233edd78.png)
![Login screen after](https://user-images.githubusercontent.com/925062/69478541-35a87500-0e26-11ea-850c-28b0af853528.png)

2019-11-23 14:32 UTC, skjnldsv commented on core/css/header.scss
> +	background-image: linear-gradient(40deg, var(--color-primary) 0%, rgba(28,175,255,1) 100%);
rgba(28,175,255,1) is off from our default colour.
Are we changing our default from 0082c9 to 1cb0ff?

2019-11-24 02:01 UTC, jancborchardt commented on core/css/header.scss
> +	background-image: linear-gradient(40deg, var(--color-primary) 0%, rgba(28,175,255,1) 100%);
No, it's simply a gradient. To have a gradient there need to be 2 colors, so we go from our primary color to a slightly lighter one. :)

2019-11-24 09:17 UTC, skjnldsv commented on core/css/header.scss
> +	background-image: linear-gradient(40deg, var(--color-primary) 0%, rgba(28,175,255,1) 100%);
Ah, no, I misread the gradient :)
Because I remembered you wanted to 'fade out' the icons, I assumed you were gonna need the primary colour, and a darker/lighter colour to make them stand out.

Also, on the new background, the primary colour is the icon, right? Or the background?
The bg seems lighter than 0082c9 (but that might be a nice optical illusion because of the icons ;) )

2019-11-24 09:48 UTC, karlitschek commented
Nice 👍

2019-11-24 10:20 UTC, jancborchardt commented on core/css/header.scss
> +	background-image: linear-gradient(40deg, var(--color-primary) 0%, rgba(28,175,255,1) 100%);
Not sure I understand the question. :) How it look like is how the design is intended. Both the bottom left is the primary color, as well as the app icons (with some transparency).

2019-11-24 10:45 UTC, JanDragon commented
Looks awesome. 👍

2019-11-25 07:37 UTC, rullzer approved these changes
Noice!
Lets do this

2019-11-25 07:40 UTC, ChristophWurst commented
Doesn't work with theming. Or is this intended?

![Bildschirmfoto von 2019-11-25 08-39-22](https://user-images.githubusercontent.com/1374172/69521381-1d884100-0f5f-11ea-8abc-8c2feb951713.png)

2019-11-25 08:20 UTC, rullzer commented
> Doesn't work with theming. Or is this intended?
> 
> ![Bildschirmfoto von 2019-11-25 08-39-22](https://user-images.githubusercontent.com/1374172/69521381-1d884100-0f5f-11ea-8abc-8c2feb951713.png)

Jikes. good catch/

2019-11-25 10:12 UTC, skjnldsv commented on core/css/header.scss
> +	background-image: linear-gradient(40deg, var(--color-primary) 0%, rgba(28,175,255,1) 100%);
All good! :)

2019-11-25 11:26 UTC, skjnldsv approved these changes

2019-11-25 12:26 UTC, ChristophWurst requested changes
Just making sure nobody clicks that merge button before https://github.com/nextcloud/server/pull/18082#issuecomment-558030683 is resolved

2019-11-25 14:05 UTC, ChristophWurst commented
But I have to admit that the longer I look at this (broken) design, the more I like it.

![Bildschirmfoto von 2019-11-25 15-04-19](https://user-images.githubusercontent.com/1374172/69546914-e9c80e00-0f94-11ea-9e51-eea3cde7a5ba.png)

2019-11-25 14:59 UTC, jancborchardt commented
Heh, right. So for theming we have 2 options:
1. Fall back to a flat color. In that case we should also drop the background on log in since it would not be visible anyway → Simplest solution
2. Generate a slightly lighter primary color. Then we also need to adjust the background image cause it’s using the Nextcloud blue, etc etc.

I’d say let’s do 1? In any case I need some help with this.

2019-11-25 15:03 UTC, skjnldsv commented
1 seems good and straightforward.
But it's kind of sad to drop our nice background just for a colour change.
I guess the issue is that you dropped the automatic colouring of the background?

@juliushaertl how was the theming app doing? Using the svg?

2019-11-25 15:35 UTC, juliushaertl commented
Pushed a commit to adjust the gradient to the primary color. For now I disabled the background image on other colors than nextcloud blue because it looked a bit weired with slightly blue icons on top of other colors.

2019-11-25 15:36 UTC, juliushaertl commented
The previous background image were just white dots that worked on all colors, but we probably could use an svg and use our existing colorize endpoint to get the new background matching the primary color.

2019-11-25 15:47 UTC, skjnldsv commented
> The previous background image were just white dots that worked on all colors, but we probably could use an svg and use our existing colorize endpoint to get the new background matching the primary color.

@jancborchardt could you maybe use your design as svg and use an opacity (dark, light, you choose) over the primary colour?

2019-11-25 16:14 UTC, jancborchardt commented
> @jancborchardt could you maybe use your design as svg and use an opacity (dark, light, you choose) over the primary colour?

The design is SVG, and it’s intended so that the icons sort of "vanish" in the bottom left because they are the primary color, half transparent.

If they are just a white/black/grey transparency, it will look totally different, and off. Feel free to experiment with it though, but I think with @juliushaertl’s fix we could merge this now and experiment further later?

2019-11-25 16:43 UTC, ChristophWurst approved these changes
Tested and looks good!

![Bildschirmfoto von 2019-11-25 17-43-20](https://user-images.githubusercontent.com/1374172/69559909-20a91e80-0fab-11ea-93dc-3c8495dd66ec.png)
![Bildschirmfoto von 2019-11-25 17-43-02](https://user-images.githubusercontent.com/1374172/69559910-20a91e80-0fab-11ea-92dc-7ec2e016cf22.png)

2019-11-25 16:44 UTC, skjnldsv commented
> If they are just a white/black/grey transparency, it will look totally different, and off. Feel free to experiment with it though, but I think with @juliushaertl’s fix we could merge this now and experiment further later?

let's do this then!! :rocket:

2019-11-25 16:53 UTC, georgehrke approved these changes

2019-11-25 16:57 UTC, JanDragon approved these changes

2019-11-26 06:23 UTC, tobiasKaminsky commented
Have you tested theming with some edge cases? Set primary color to black/white?

2019-11-26 11:01 UTC, rullzer commented
Lets do this. And if we run into edge cases we didn't think of we'll fix them then.

2019-11-26 11:01 UTC, merged

2019-11-26 12:45 UTC, tobiasKaminsky commented
Is the background image/pattern somehow missing? 
Or is it not working when theming app is enabled?
I can only see a solid background.

2019-11-26 15:43 UTC, jancborchardt commented
@tobiasKaminsky it does seem to work by default. Can you try going to theming, and in the row of "Log in image" click the "Reset to default" round arrow button?

2019-11-27 10:15 UTC, tobiasKaminsky commented
I did, but it is still plain black (or do you think that the icons are not tinted and therefore cannot shine through?)

2020-02-22 14:01 UTC, SR4ven commented
> @tobiasKaminsky it does seem to work by default. Can you try going to theming, and in the row of "Log in image" click the "Reset to default" round arrow button?

I tried this too and now I'm stuck with a plain background in my set theming color. I had a gradient background before after updating to NC18.

2020-02-23 20:53 UTC, juliushaertl commented
@SR4ven Please open a new issue with a full issue description.