adding timeout param
nextcloud/server pull request #18080
Opened 2019-11-23 10:57 UTC by daita

This would help any app trying to save into a locked file to known the estimated timeout when catching the LockedException.

As an example, it will make the Text App not trying to sync every 5s if the lock is initiated by the FilesLock app.

2019-11-26 17:30 UTC, juliushaertl commented
I would actually prefer to have a separate exception class that extends from LockedException and contains the additional details like lock owner, time

2019-11-26 19:48 UTC, daita commented
@juliushaertl  this would limit the app to 18, which is not a big deal. Please have a look to the new TemporaryLockedException

2019-12-05 09:28 UTC, juliushaertl commented on lib/public/Lock/TemporaryLockedException.php
> +class TemporaryLockedException extends LockedException {
I actually find the Temporary a bit confusing, but not sure about a better wording there. Maybe ManualLockedException?

2019-12-05 15:30 UTC, ChristophWurst requested changes

2019-12-05 15:30 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	private $owner = '';
I'd vote for `string|null` instead of `string|''`

2019-12-05 15:42 UTC, daita commented on lib/public/Lock/ManuallyLockedException.php
> +	private $owner = '';
done

2019-12-05 15:51 UTC, ChristophWurst requested changes
Should still be type-hinted, even if nullable :)

2019-12-05 15:51 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, $owner = null, int $timeout = -1) {
```suggestion
	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, string $owner = null, int $timeout = -1) {
```

2019-12-05 15:51 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	public function getOwner() {
```suggestion
	public function getOwner(): ?string {
```

2019-12-05 16:27 UTC, daita commented
ok, learnt something today. should be ok now

2019-12-13 09:23 UTC, ChristophWurst approved these changes

2019-12-13 09:23 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, string $owner = null, int $timeout = -1) {
```suggestion
	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, ?string $owner = null, int $timeout = -1) {
```

otherwise you can't pass `null` for the owner.

2019-12-13 09:23 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, string $owner = null, int $timeout = -1) {
scratch that. there is a `= null`.

2019-12-13 09:26 UTC, ChristophWurst commented on lib/public/Lock/ManuallyLockedException.php
> +	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, string $owner = null, int $timeout = -1) {
so, in order to construct this with a `null` owner you have to omit the parameter. You can't pass in `null`. If you want to make `null` an allowed value then it should be `?string $owner = null`.

`string $owner` -> not nullable, required param
`?string $owner` -> nullable, requried param
`string $owner = null` -> not nullable, optional param
`?string $owner = null` -> nullable, optional param

hope it makes sense now :)

2019-12-13 09:36 UTC, daita commented on lib/public/Lock/ManuallyLockedException.php
> +	public function __construct(string $path, \Exception $previous = null, string $existingLock = null, string $owner = null, int $timeout = -1) {
sure, i'll fix this

2019-12-19 12:45 UTC, juliusknorr approved these changes

2019-12-20 11:16 UTC, merged