Extend propertypath to 4000
nextcloud/server pull request #18126
Opened 2019-11-26 22:58 UTC by J0WI

Fixes #9907 and maybe also #5477

2019-11-27 13:33 UTC, kesselb commented
Thanks :+1: 

```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2019-11-27 13:41 UTC, kesselb commented on core/Migrations/Version18000Date20191126000000.php
> +
https://github.com/nextcloud/server/blob/0532f8116da1ed92b973c8842c4d18f084255820/core/Migrations/Version18000Date20190920085628.php#L3-L21

Please add the header

2019-11-27 14:53 UTC, J0WI commented on core/Migrations/Version18000Date20191126000000.php
> +
Done.

2019-11-27 16:11 UTC, kesselb commented on core/Migrations/Version18000Date20191126000000.php
> +		if ($schema->hasTable('properties')) {
We can probably remove this check because `properties` is a core table.

2019-11-27 16:52 UTC, J0WI commented on core/Migrations/Version18000Date20191126000000.php
> +		if ($schema->hasTable('properties')) {
Done

2019-12-13 12:20 UTC, ChristophWurst approved these changes

2019-12-13 12:34 UTC, georgehrke commented
Especially if you heavily use calendar and contacts, there will be many entries in oc_properties.
I'm worried this Migration will die in a timeout

2019-12-13 13:28 UTC, ChristophWurst requested changes
see https://github.com/nextcloud/server/pull/18126#issuecomment-565426273

2019-12-16 10:28 UTC, J0WI commented
Is there a way to solve this?

2019-12-19 09:17 UTC, ChristophWurst commented
Discussed this with @rullzer briefly.

* We shouldn't do this migration by default as it will most likely time out on mid-sized to large installations.
* For 19 we can change the original migration so new installations get a more appropriate column width by default
* Add an optional repair step like we have for missing indices, so admins can later migrate the column with with an occ command

I'll also put that into the ticket and close the PR as we won't integrate it in its current form.

2019-12-19 09:17 UTC, closed without merging