fix filename size
nextcloud/server pull request #18163
Opened 2019-11-29 14:09 UTC by GretaD

2019-12-02 11:24 UTC, juliusknorr approved these changes

2019-12-02 14:03 UTC, ChristophWurst commented on lib/private/Files/Storage/Common.php
> +		if (isset($fileName[250])) {
where does this magic number come from and why is 255 wrong? :)

2019-12-02 14:41 UTC, juliushaertl commented on lib/private/Files/Storage/Common.php
> +		if (isset($fileName[250])) {
Just guessing because I didn't dig to deep in the git log:
- 255 characters is the limit on common file systems (ext/xfs)
- initially there was '.part' appended for chunked uploads
- oc_filecache has a 250 char length limit for the filename

2019-12-03 05:14 UTC, jancborchardt commented on lib/private/Files/Storage/Common.php
> +		if (isset($fileName[250])) {
Sounds like that should be above that line as a code comment then? :)

2019-12-03 09:33 UTC, GretaD commented on lib/private/Files/Storage/Common.php
> +		if (isset($fileName[250])) {
yes, commenting my code in general, its not a bad idea :)

2019-12-04 09:24 UTC, nickvergessen requested changes
Add a comment

2019-12-04 13:02 UTC, rullzer approved these changes

2019-12-04 13:15 UTC, merged