add and remove tags from multiple files at once
nextcloud/server pull request #18199
Opened 2019-12-03 08:55 UTC by rolandinus

#10674 
Adds an option to the actions when multiple files are selected.
The tags from all selected files are fetched and the tags which are common to all files will be preselected.
When Tags are deselected they will be removed from all selected files.
When new Tags are selected or created they will be added to all files

2019-12-03 13:42 UTC, kesselb commented
Could you rebase the branch? Should fix the test failures.

2019-12-03 13:47 UTC, skjnldsv commented
@danxuliu could you give a hand on tests here? :)

2019-12-04 16:52 UTC, juliushaertl commented
unit tests should be fixed by rebasing to curent master

2019-12-05 07:37 UTC, skjnldsv commented
The rebase doesn't seems right :see_no_evil:

2019-12-05 13:13 UTC, rolandinus commented
There was some mess with the rebase, should be ok now

2019-12-05 13:38 UTC, skjnldsv commented
ALL GREEN!!!! @nextcloud/javascript can you believe it :D

2019-12-05 13:38 UTC, skjnldsv approved these changes

2019-12-05 13:41 UTC, ChristophWurst requested changes

2019-12-05 13:41 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +            selectedFiles.forEach(function(fileId) {
:boom: did you mean to return early two lines above?

2019-12-05 14:07 UTC, rolandinus commented on apps/files/js/filelist.js
> +            selectedFiles.forEach(function(fileId) {
Yes, that was the plan originally- but I nevery run in to the case while testing that I got not back an array, so I seem to have forgotten it. However if I look at the source getSelectedFiles() it is not guaranteed to return a an array

2019-12-05 15:38 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +            selectedFiles.forEach(function(fileId) {
yes, but this is a bit strange. you check the type, but then you continue anyway, using an API of `Array`. You should either assume it's an array (and remove the check) or handle this case properly and either throw an `Error(...)` or abort the current operation.

2019-12-09 11:35 UTC, rolandinus commented on apps/files/js/filelist.js
> +            selectedFiles.forEach(function(fileId) {
I changed the code and return early now if no files are selected.

2020-01-27 14:22 UTC, skjnldsv commented
Hey @rolandinus 
Now that 18 is released, could you rebase your work to latest master please? :)

2020-01-29 17:08 UTC, rolandinus commented
> Hey @rolandinus
> Now that 18 is released, could you rebase your work to latest master please? :)

I rebased it to newest master, but now I get again errors on  some the tests (for server side parts which I did not touch at all) Last time they vanished after rebasing them to the newest master. But I pushed directly after rebasing. Can anyone give me information about why these errors occur and how i can avoid them?

2020-01-30 09:37 UTC, skjnldsv commented
> Can anyone give me information about why these errors occur and how i can avoid them?

They're coming from anbother issue introduced in master.
They don't seems to be related to your (awesome) work :)

2020-01-30 09:48 UTC, kesselb commented on apps/files/js/filelist.js
> +               // console.log('inputView',self._inputView, self._inputView.$el,'tag container', self.tagsContainer);
```suggestion
```

2020-04-23 22:08 UTC, TueTchen commented
Dear Experts,
would there be a possibility to try this important function in advance in an existing Nextcloud 18 installation as a beta tester?
We're a small group working honorary on preserving children's rights due to child abuse. We're currently working on a big hard case with over 1500 scanned documents that we've already named so that we can get them filtered through Nextcloud Search. And we have prepared about 50 collaborative tags to get these tons of artefacts correctly prepared for our thesis.
What would help us very very much right now, that would be to have your great development of "mass tagging" to tag about 20 to 300 documents at once.
Would there be any chance to get a pre- or alpha release working in a quite fresh 18.0.4 nextcloud installation on a managed hosting server, without having too deep development knowhow, but having enough to understand most of your discussions?
Thanks in advance for your answer!
Peter alias TueTchen, Germany

2020-04-29 22:43 UTC, Spartachetto commented
@kesselb @skjnldsv @juliushaertl I am sorry to bother you, yet this feature would be great... 

Do you think it possible for it to be 
in Nextcloud 19?

Thank you in any case and keep up the good work!!!

2020-04-30 07:11 UTC, ChristophWurst reviewed
Code looks okay-ish, while this legacy jquery style is more than just outdated. But that is the state of the files app right now, so I guess this is ok?

Didn't test and don't have the in depth understanding of this part of our code base. Thus there might be uncovered edge cases.

:elephant:

2020-04-30 18:36 UTC, rullzer commented
I rebased this for CI

2020-05-01 01:08 UTC, jancborchardt commented
> this legacy jquery style is more than just outdated. But that is the state of the files app right now, so I guess this is ok?

Yep – it is indeed outdated but that’s where we are. It’s good for 19 and a big help for people who use tagging.

Short of bigger design feedback I only have 1 point @rolandinus 
- [ ] The "Tags" action should not be the last action in the menu. Better between "Download" and "Select file range". (The last action should always be the destructive action, in this case being "Delete".

2020-05-02 00:04 UTC, jancborchardt commented on apps/files/js/app.js
> +                        }
This block should go a bit further up so it’s below the "Download" action instead. :) Otherwise all good

2020-05-02 00:04 UTC, jancborchardt requested changes
See comment ^

2020-05-04 07:53 UTC, skjnldsv requested changes
> Yep – it is indeed outdated but that’s where we are. It’s good for 19 and a big help for people who use tagging.

No, sorry, I have to block.
This is too sensitive. Sorry @rolandinus , this is some areas of the code where it alwyas blow up later on. I refuse to be the one that have to fix 3 legacy files that are unrelated for this to get in.
Beside, 19 is feature freeze, nothing like that gets in for now :)

2020-05-04 07:58 UTC, ChristophWurst commented
Those who eagerly want this feature can just apply as as patch. You can download that from https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/18199.patch.

2020-05-04 08:15 UTC, MorrisJobke commented
> No, sorry, I have to block.
> This is too sensitive. Sorry @rolandinus , this is some areas of the code where it alwyas blow up later on. I refuse to be the one that have to fix 3 legacy files that are unrelated for this to get in.
> Beside, 19 is feature freeze, nothing like that gets in for now :)

@rolandinus Unfortunately I have to acknowledge this. We are already in beta 7 and it is a too high risk of breakage here. I will move it to the 20 milestone.

2020-05-04 08:16 UTC, rolandinus commented
I know the code is outdated, I just tried to fit it in with the code of the rest of the files app. I am happy to refactor it for a future version of NC. However it would only make sense if the rest of the files app is refactored before I guess

2020-05-04 08:22 UTC, skjnldsv commented
@rolandinus Also, I want to give you some explanation, because I think you deserve to have some.
Our files app code is very old. While we're doing a **crazy** amount of work to have a proper implementation of our features in our apps, this is the core of our project and unfortunately it is incredibly messy. This was written in a different time and to be fair, none of us understand the code architecture. This is patched everywhere, contains lots of jQuery code, etc etc.
This makes it very hard to do anything, because any little enhancement always end up in multiple unknown bugs that takes a few days to debug.

It is never worth it.
We have plans to upgrade the files app too, but those things takes time, as youc an imagine. Keep in mind, we really are all in your awesome feature, but I'm too cold feet and cautious to approve this. For me it's not worth the risk (and we can gamble, but it always blow up somewhere unexpected, alway :( )

Hope you can understand why it takes so long for this to get approved.
Thanks again for your work and interest! :hugs: :bowing_woman:

2020-05-04 17:27 UTC, TueTchen commented
Thank you all for your efforts and your explanations!
In the meantime I'll help myself/ourselves by using the good old school tool 'nc-direct' (= SQL 😅). The tag relation are really very simple, and our acribic file naming help us to get a main mass tagging done on its lowest level.
Regarding our wider usage of tagging (currently >100 tags for >3000 files), there are also growing new requirement and wishes, that underline a well-thought refactoring - e.g. hierarchical tag relations, access rights enhancements and also another kind of showing and handling file taggings (we've already up to 20 tags for the single file, it's not really easy to identify missing or wrong tags).

So thank you again, always good luck & good speed and please stay healthy!
Peter

2021-03-30 10:37 UTC, HTStentiQ commented
any news on this?

2021-04-01 11:55 UTC, closed without merging

2021-04-01 11:56 UTC, skjnldsv commented
Closing, see https://github.com/nextcloud/server/pull/18199#issuecomment-623326652

2021-08-07 07:04 UTC, Sandro1955 commented
Hi, I installed version 12.01, but I can't find the "multiple tags" function in the actions. How do I go about implementing it?

2021-08-11 06:48 UTC, Sandro1955 commented
Hi, I installed version 21.0.4, but I can't find the "multiple tags" function in the actions. How do I go about implementing it?

2021-08-11 06:50 UTC, skjnldsv commented
https://github.com/nextcloud-gmbh/professional_services/issues/321