Add tooltips to username and email
nextcloud/server pull request #18193
Opened 2019-12-02 17:37 UTC by onehappycat

#18158 Add tooltips to username and email fields in user management.

2019-12-02 18:20 UTC, kesselb commented
Thanks :+1: 

Would you mind to share a screenshot? ;)

2019-12-02 18:46 UTC, onehappycat commented
> Thanks 👍
> 
> Would you mind to share a screenshot? ;)

<img width="466" alt="Screenshot 2019-12-02 at 19 45 08" src="https://user-images.githubusercontent.com/56887614/69985864-5fefe600-153c-11ea-8ff5-84784047e157.png">

2019-12-03 07:16 UTC, skjnldsv requested changes
Hum, this will conflict with @GretaD's work on the new layout #17239 
I would rather have this wait until the other to ease the potential rebase :)

2019-12-03 09:32 UTC, GretaD commented
yes please lets wait, not that much left to do on my ticket. I'll ping you again again.

2019-12-03 14:00 UTC, onehappycat commented
Sounds good. The new layout looks amazing. 👍

2019-12-13 12:17 UTC, blizzz commented
@GretaD's PR was merged. What to do with this one?

2019-12-13 12:19 UTC, skjnldsv commented
rework it to add the tooltips at the correct place :)

2019-12-14 13:32 UTC, onehappycat commented
Rebased to current master, added the tooltips to correct places at the new layout.

Before:
<img width="786" alt="Screenshot 2019-12-14 at 14 31 28" src="https://user-images.githubusercontent.com/56887614/70849428-76703880-1e7e-11ea-9bd5-de4df0a7f5a3.png">

After:
<img width="759" alt="Screenshot 2019-12-14 at 14 31 36" src="https://user-images.githubusercontent.com/56887614/70849430-7839fc00-1e7e-11ea-85dc-a3f80611425f.png">

2019-12-15 11:56 UTC, skjnldsv approved these changes

2019-12-15 11:58 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +				<div v-if="user.displayname.length>20" v-tooltip.auto="user.displayname">
Hum, you could also just ellipsis with css and enable the tooltip only when the length is bigger than '20 char' ?

2019-12-15 11:58 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +				<div v-if="user.displayname.length>20" v-tooltip.auto="user.displayname">
Also, we're using the three dot ellipsis character, not three real dots: `…`
And with a space before :)

2019-12-15 11:58 UTC, skjnldsv requested changes
See comments ;)

2019-12-15 17:53 UTC, onehappycat commented
Rebased and added the full output of `make build-js-production`, but webpack is still complaining.

2019-12-16 08:01 UTC, skjnldsv commented
/compile amend /

2019-12-16 11:27 UTC, skjnldsv commented
@onehappycat something else was merged, please rebase again :p
After rebase you can use the `/compile amend /` command to trigger a compile of any js file by our bot ;)

2019-12-16 13:10 UTC, skjnldsv approved these changes

2019-12-16 13:54 UTC, ChristophWurst commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +				<div v-tooltip="user.displayname.length > 20 ? user.displayname : ''" class="cellText">
is there any other way to detect the truncated text? the magic number 20 doesn't care about different fonts, letter width and dynamic size of the conainer.

2019-12-16 15:22 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +				<div v-tooltip="user.displayname.length > 20 ? user.displayname : ''" class="cellText">
Yes, use a vue ellipsis component/directive :)
In the meantime, I'd say let get this in, worst thing that could happen is a tooltip :see_no_evil:

2019-12-19 09:49 UTC, ChristophWurst approved these changes
I like happy cats

2019-12-20 10:23 UTC, merged