Transfer ownership function polishing
nextcloud/server pull request #18270
Opened 2019-12-06 13:30 UTC by wiswedel

Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

2019-12-06 13:43 UTC, ChristophWurst approved these changes

2019-12-06 14:17 UTC, wiswedel commented
The padding after the numbers is quite narrow, but I'm incapable of fixing that. Can someone please have a look at that?

![image](https://user-images.githubusercontent.com/1804221/70329251-3d5f1500-183b-11ea-84d3-d3ec0256c965.png)

I think it's logically safe to push the solution into this polishing PR.

2019-12-06 14:21 UTC, ChristophWurst commented
> The padding after the numbers is quite narrow, but I'm incapable of fixing that. Can someone please have a look at that?

This is something that should be changed/fixed broadly with our design rules and not just here so we can have a consistent appearance.

2019-12-09 10:29 UTC, wiswedel commented
> > The padding after the numbers is quite narrow, but I'm incapable of fixing that. Can someone please have a look at that?
> 
> This is something that should be changed/fixed broadly with our design rules and not just here so we can have a consistent appearance.

@ChristophWurst Fine for me. How do I get this onto that _design rules fix_ backlog?

2019-12-09 11:19 UTC, wiswedel commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
@rullzer Beginner's question: How do I add 2 manual line breaks here?

2019-12-09 11:20 UTC, wiswedel commented on apps/files/lib/Notification/Notifier.php
> +			->setParsedMessage(str_replace('{path}', $param['nodeName'], $l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.')));
@rullzer same question here about line breaks

2019-12-09 12:33 UTC, ChristophWurst commented
> > The padding after the numbers is quite narrow, but I'm incapable of fixing that. Can someone please have a look at that?
> 
> This is something that should be changed/fixed broadly with our design rules and not just here so we can have a consistent appearance.

cc @nextcloud/designers

2019-12-10 05:27 UTC, jancborchardt commented
The list styling is a strange way to do this here, so that’s why it looks strange. Nothing wrong with the list styling, instead the flow should be adjusted. Mostly this is about wording:

> **Folder to transfer**
> ( Select )
>
> **New owner**
> [ Search users ]
>
> **( Transfer `foldername` to `username`)**

Transfer button on the bottom should be greyed out until both folder and recipient are selected.

2019-12-10 09:26 UTC, wiswedel commented
> ( Transfer `foldername` to `username`)

I'm not capable of implementing this. Anyone else?

2019-12-15 09:30 UTC, gary-kim commented
@wiswedel How is this?
![Screenshot from 2019-12-15 17-29-00](https://user-images.githubusercontent.com/47195730/70860744-87917600-1f60-11ea-8de5-c197e09ec1be.png)

2019-12-16 07:33 UTC, rullzer commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
I don't think you can.

2019-12-16 07:35 UTC, rullzer commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
Ah no you can. Just use `\n` for linebreaks

2019-12-16 07:36 UTC, rullzer commented
@gary-kim awesome. Lets go for that

2019-12-16 08:28 UTC, gary-kim commented
Made a few changes with @jancborchardt 
@ChristophWurst Do you want to take another look?
![Screenshot from 2019-12-16 16-28-21](https://user-images.githubusercontent.com/47195730/70890902-19f94e80-2021-11ea-9e22-7c158ce283c2.png)

2019-12-16 08:53 UTC, wiswedel commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
> Just use \n for linebreaks

That didn't seem to work for me

2019-12-16 09:02 UTC, ChristophWurst requested changes
The code changes look good

Touched files like `apps/settings/js/vue-3.js` seem unrelated? Did you install npm dependencies before the build?

2019-12-16 09:02 UTC, ChristophWurst commented
Also, this needs a rebase to resolve the conflicts

2019-12-16 09:16 UTC, juliushaertl commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
`\n` only works inside double quotes.

2019-12-16 09:17 UTC, gary-kim commented
Rebased.


> Touched files like `apps/settings/js/vue-3.js` seem unrelated? Did you install npm dependencies before the build?


The CI [webpack-build succeeded](https://drone.nextcloud.com/nextcloud/server/24379/2/3) so it looks like those files should be touched? Let's see if the new build passes.

2019-12-16 09:21 UTC, ChristophWurst commented
Yes, let's see. ``+95 −10,994`` is very suspicious, though :thinking:

2019-12-16 20:17 UTC, wiswedel commented on apps/files/lib/Notification/Notifier.php
> +				$l->t('Do you want to accept {path}? Note: The transfer process after accepting may take up to 1 hour.'),
> `\n` only works inside double quotes.

omg, that's one of those things one has to learn the hard way 🤨

2019-12-17 02:45 UTC, gary-kim commented
@ChristophWurst Looks like the [webpack-build is still passing](https://drone.nextcloud.com/nextcloud/server/24418/2/3). I'm also not entirely sure what part of the change resulted in all those removals.

2019-12-17 03:05 UTC, jancborchardt approved these changes
Very nice and simple design-wise now. :) Thanks a lot @gary-kim and @wiswedel!

2019-12-17 09:39 UTC, rullzer commented
@ChristophWurst fixed with https://github.com/nextcloud/server/pull/18438

:)

2019-12-17 09:39 UTC, rullzer approved these changes

2019-12-17 10:11 UTC, ChristophWurst approved these changes

2019-12-17 11:00 UTC, merged