Fix login page handling for disabled users
nextcloud/server pull request #1829
Opened 2016-10-20 15:27 UTC by MorrisJobke

* uses a 403 page now with "User disabled"
* before it caused a 500 error message
* downstream of https://github.com/owncloud/core/pull/26256
* @rullzer I extended your changed integration tests with the ones from upstream to 4 tests in total (instead of 2)
![bildschirmfoto 2016-10-20 um 17 20 35](https://cloud.githubusercontent.com/assets/245432/19566366/4693bbce-96ea-11e6-9ffa-6f5f8cc28848.png)

I tested this and this provides proper feedback for the user why the login failed and not only the normal 500 error page.

cc @nickvergessen @LukasReschke

2016-10-21 06:45 UTC, rullzer requested changes

2016-10-21 06:45 UTC, rullzer commented on build/integration/features/provisioning-v1.feature
>  		When sending "GET" to "/cloud/capabilities"
Remove this line then

2016-10-21 08:01 UTC, MorrisJobke commented on build/integration/features/provisioning-v1.feature
>  		When sending "GET" to "/cloud/capabilities"
🙈 Thanks for spotting

2016-10-21 08:06 UTC, MorrisJobke commented on build/integration/features/provisioning-v1.feature
>  		And the HTTP status code should be "401"
The problem here is that OCS returns a 401 and the web UI returns a 403. If we change this then we cause an incompatibility with OC - on the other hand it's weird to have this different for web vs OCS.

HTTP status codes:

401 Unauthorized

> The requestor is not authorized to access the resource. This is similar to 403 but is used in cases where authentication is expected but has failed or has not been provided.

403 Forbidden

>The request was formatted correctly but the server is refusing to supply the requested resource. Unlike 401, authenticating will not make a difference in the server's response.


So the 403 makes sense here.

2016-10-21 08:08 UTC, rullzer commented on build/integration/features/provisioning-v1.feature
>  		And the HTTP status code should be "401"
Yep 403 makes more sense. Trouble is that we don't know in the OCS code what caused the error (since we have no real forbidden status code).

2016-10-21 12:26 UTC, MorrisJobke commented
Then this is ready for review: @rullzer @nickvergessen @LukasReschke

2016-10-21 14:26 UTC, rullzer commented
LGTM

2016-10-24 19:35 UTC, MorrisJobke commented
I only cherry picked the upstream commit: I tested this and it works 👍

2016-10-24 19:35 UTC, merged