Return empty template for default creators
nextcloud/server pull request #18428
Opened 2019-12-16 14:01 UTC by juliushaertl

If a creator has no templates we return a default empty template entry to make it easier for apps so that they only need to implement one behavior that follows the following flow:

- Click create new file
- Select type of document (spreadsheet/document/text)
- Show UI to select template and enter filename

2019-12-16 14:12 UTC, rullzer approved these changes
sure

2019-12-16 14:17 UTC, tobiasKaminsky requested changes

2019-12-16 14:17 UTC, tobiasKaminsky commented on lib/private/DirectEditing/Manager.php
> +							'id' => 'empty',
This must be an integer

2019-12-16 15:37 UTC, tobiasKaminsky commented on lib/private/DirectEditing/Manager.php
> +							'id' => 'empty',
Forget this, I was wrong.

2019-12-16 15:38 UTC, tobiasKaminsky commented on lib/private/DirectEditing/Manager.php
> +							'preview' => null
please add proper extension.

2019-12-16 15:47 UTC, juliushaertl commented on lib/private/DirectEditing/Manager.php
> +							'preview' => null
The extension should be inherited from the creator itself, since they are shared across the different templates

2019-12-16 16:23 UTC, juliushaertl commented on lib/private/DirectEditing/Manager.php
> +							'preview' => null
Done as discussed.

2019-12-17 07:07 UTC, tobiasKaminsky approved these changes

2019-12-17 09:41 UTC, merged