User File Node API for more download cases, skip unreadable files
nextcloud/server pull request #18433
Opened 2019-12-16 17:55 UTC by blizzz

Follow up to #17822

2019-12-17 09:28 UTC, rullzer requested changes

2019-12-17 09:28 UTC, rullzer commented on lib/private/Streamer.php
> +		$userFolder = \OC::$server->getRootFolder()->get(Filesystem::getRoot());
please use...

```suggestion
		$userFolder = \OC::$server->getRootFolder()->getUserFodler(USERID);
```

2019-12-17 09:28 UTC, rullzer commented on lib/private/legacy/files.php
> +			$userFolder = \OC::$server->getRootFolder()->get(\OC\Files\Filesystem::getRoot());
Same here

2019-12-17 10:19 UTC, kesselb commented on lib/private/Streamer.php
> +		$userFolder = \OC::$server->getRootFolder()->get(Filesystem::getRoot());
You're typing to fast for the keyboard ;)

2019-12-17 10:32 UTC, blizzz commented on lib/private/Streamer.php
> +		$userFolder = \OC::$server->getRootFolder()->get(Filesystem::getRoot());
@rullzer might be an unauthanticated user, so no uid. This is a recommendation  by @icewind1991 .

2019-12-17 11:00 UTC, rullzer commented on lib/private/Streamer.php
> +		$userFolder = \OC::$server->getRootFolder()->get(Filesystem::getRoot());
If @icewind1991 says so I'm good.

2019-12-17 11:01 UTC, rullzer approved these changes

2019-12-17 14:14 UTC, blizzz commented
mh, some integration tests for download throw 404s and i can reproduce locally :/

2019-12-17 15:04 UTC, rullzer commented
Lets restart them first

2019-12-17 19:04 UTC, rullzer commented
Nope we'll have to dive into that..

2019-12-17 20:13 UTC, blizzz commented
yeah, no surprise it fails for me, too… I'll dive, either a bit later, or tomorrow morning.

2019-12-17 22:11 UTC, blizzz commented
first arg has to be full path, not just a name. works one folder down, but not deeper structures.

2019-12-18 07:53 UTC, blizzz commented
Passes now (apart from those MySQL timeouts)

2019-12-18 13:27 UTC, icewind1991 requested changes

2019-12-18 13:27 UTC, icewind1991 commented on lib/private/Streamer.php
> +	public function addDirRecursive(string $dir, string $internalDir = ''): void {
passing the `Node`/`FileInfo` instead of the path here would be nice as it would cut the number of filecache queries in half

2019-12-18 20:34 UTC, blizzz commented on lib/private/Streamer.php
> +	public function addDirRecursive(string $dir, string $internalDir = ''): void {
Passing the Node would be more helpful, I agree and had the same thought. I discarded it to have a simpler and smaller changeset to backport.

2019-12-18 20:35 UTC, blizzz commented
/backport to stable17

2019-12-18 20:35 UTC, blizzz commented
/backport to stable16

2019-12-18 20:35 UTC, blizzz commented
/backport to stable15

2019-12-19 11:16 UTC, icewind1991 approved these changes

2019-12-19 16:54 UTC, merged

2019-12-20 11:07 UTC, blizzz commented
15 is EOL now