Restore old behavior allowing to set custom appstore
nextcloud/server pull request #18442
Opened 2019-12-17 11:21 UTC by georgehrke

Signed-off-by: Georg Ehrke <developer@georgehrke.com>

2019-12-17 12:52 UTC, rullzer approved these changes

2019-12-17 14:35 UTC, ChristophWurst requested changes

2019-12-17 14:35 UTC, ChristophWurst commented on tests/lib/App/AppStore/Fetcher/AppFetcherTest.php
> +				} else if ($key === 'appstoreurl' && $default = 'https://apps.nextcloud.com/api/v1') {
```suggestion
				} else if ($key === 'appstoreurl' && $default === 'https://apps.nextcloud.com/api/v1') {
```

:see_no_evil:

2019-12-17 14:36 UTC, georgehrke commented
will squash in a sec

2019-12-17 14:47 UTC, ChristophWurst approved these changes

2019-12-17 14:48 UTC, ChristophWurst commented
do you want to backport this?

2019-12-17 19:03 UTC, rullzer commented
CI is not happy

2019-12-17 19:07 UTC, kesselb commented on lib/private/App/AppStore/Fetcher/CategoryFetcher.php
> +		$this->endpointUrl = $endpoint . '/categories.json';
```suggestion
		$this->endpointUrl = $endpoint . $this->fileName;
```

2019-12-17 19:09 UTC, kesselb commented on lib/private/App/AppStore/Fetcher/AppFetcher.php
> +		$this->endpointUrl = $endpoint . '/apps.json';
```suggestion
		$this->endpointUrl = $endpoint . '/' . $this->fileName;
```

2019-12-19 10:11 UTC, rullzer commented
Did some fixups. Test should pass now

2019-12-22 19:18 UTC, merged

2020-01-06 14:20 UTC, georgehrke commented
/backport to stable17

2020-01-06 14:29 UTC, georgehrke commented
/backport to stable17

2020-01-07 07:51 UTC, juliushaertl commented
Requires https://github.com/nextcloud/server/pull/18546 as well

2020-01-09 15:23 UTC, nickvergessen commented
This breaks the "an you update to the next major" as it assumes now that fileName is also the file name on the api endpoint.
But future-apps.json and apps.json both need to request the `apps.json` endpoint. They just use different request parameters.

2020-01-09 17:17 UTC, georgehrke commented
Fix is in https://github.com/nextcloud/server/pull/18786