Fix Sidebar enabled check
nextcloud/server pull request #18449
Opened 2019-12-17 16:28 UTC by skjnldsv

The Tab constructor was expected to have an enabled function.

2019-12-17 19:03 UTC, rullzer approved these changes
sure... :elephant:

2019-12-17 19:40 UTC, ChristophWurst requested changes

2019-12-17 19:40 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +			const enabled = tabView.canDisplay ? tabView.canDisplay : undefined
nit: you don't like `||`, do you? :)

2019-12-17 19:40 UTC, ChristophWurst commented on apps/files/src/models/Tab.js
> +	get enabled() {
```suggestion
	get isEnabled() {
```

to be consistent with `isLegacyTab`

2019-12-17 19:40 UTC, ChristophWurst commented on apps/files/src/views/Sidebar.vue
> +			} catch {
why would this trow? There is a default value for the callback at https://github.com/nextcloud/server/pull/18449/files#diff-b375c9e422692b79bf11c9f41bbe21beR38 that returns `true`.

2019-12-18 00:27 UTC, skjnldsv commented on apps/files/src/views/Sidebar.vue
> +			} catch {
You're never too careful :grin:

2019-12-18 07:41 UTC, ChristophWurst commented on apps/files/src/views/Sidebar.vue
> +			} catch {
this seems a bit arbitrary. if a boolean getter throws an error then it will be an unexpected one in 99% of the case. now you basically swallow it as it's also not logged. mind removing the try-catch here?

2019-12-19 07:49 UTC, skjnldsv commented
/compile amend /

2019-12-19 09:21 UTC, marcoambrosini reviewed
@skjnldsv I tested this but it still doesn't work for me... Are you able to disable tabs?

2019-12-19 09:23 UTC, skjnldsv commented
> @skjnldsv I tested this but it still doesn't work for me... Are you able to disable tabs?

yes, works for me, let's call

2019-12-19 09:42 UTC, marcoambrosini approved these changes
Works, thanks :)

2019-12-19 10:22 UTC, merged