fix userlist alignment
nextcloud/server pull request #18455
Opened 2019-12-17 22:26 UTC by GretaD

- [ ]  fix userlist alignment
- [ ]  add a close button for new user list

2019-12-17 22:31 UTC, GretaD commented
@skjnldsv @nextcloud/designers how we should move on with the new user list? I did a small change and now it look like this:
![newlist](https://user-images.githubusercontent.com/12728974/71039694-0afbc480-2125-11ea-9b6d-cff0c30d5e8f.png)
I am aware of the overlapping and maybe we should make the borders thicker to make it look like a sticky list over the existing list?

2019-12-19 09:45 UTC, skjnldsv commented
I'm ok with this.
what do you think @jancborchardt

2019-12-24 10:51 UTC, jancborchardt commented
Nice @GretaD!

> I am aware of the overlapping and maybe we should make the borders thicker to make it look like a sticky list over the existing list?

Can you fix that overlapping? The borders should always be only 1px, we never use thicker borders. It’s fine if it’s just sticky as it is. :)

Also, if you notice, the new entry basically duplicates all of the header info. So instead of showing it below the heading, it could be shown instead of it. (Above via z-index.)

And can you add the close button you mentioned? Next to the "Add" button on the right, just like when editing an existing user

2019-12-30 06:40 UTC, jancborchardt requested changes
See comment :)

2020-01-06 11:40 UTC, GretaD commented
@jancborchardt i would say that the **add new user** table should be somehow visually splitted from the existing users. But yes, let me try out your proposal and see how it looks.

2020-01-06 12:44 UTC, GretaD commented
> Can you fix that overlapping? The borders should always be only 1px, we never use thicker borders. It’s fine if it’s just sticky as it is. :)

what do you think? ;)
![newusertable](https://user-images.githubusercontent.com/12728974/71818900-90222b80-308a-11ea-9ec6-462705250912.png)

2020-01-09 07:07 UTC, rullzer commented
master is NC19 now.
Please backport if it needs to go into 18

2020-01-13 22:33 UTC, jancborchardt commented
@GretaD is this now ready for review? :)

2020-01-14 19:20 UTC, GretaD commented
@m4dz i cannot add you as a reviewer but this is the full PR of what we were working :)

2020-01-14 20:16 UTC, georgehrke requested changes
Looks good besides my comments

2020-01-14 20:16 UTC, georgehrke commented on apps/settings/css/settings.scss
> +	  position: sticky;
Please fix the indentation

2020-01-14 20:16 UTC, georgehrke commented on apps/settings/css/settings.scss
> +		    z-index: 0;
Indentation

2020-01-14 20:16 UTC, georgehrke commented on apps/settings/css/settings.scss
> +			  .row {
Indentation

2020-01-14 20:16 UTC, georgehrke commented on apps/settings/src/components/UserList.vue
> +			let validQuota = OC.Util.computerFileSize(quota)
Not sure why you changed it to `let`, it should stay `const` since you are not modifying the value of it

2020-01-14 20:16 UTC, georgehrke commented on apps/settings/src/components/UserList.vue
> +				let currentGroup = this.groups.find(group => group.id === value)
Not sure why you changed it to `let`, it should stay `const` since you are not modifying the value of it

2020-01-15 23:31 UTC, jancborchardt commented
![userlist alignment](https://user-images.githubusercontent.com/925062/72480290-43abbe00-37f7-11ea-8822-401c2ef52eae.png)
- [ ] "Done" button should also be primary so you know what to do next
- [ ] On editing an entry, the action buttons are too much to the right, with the 3-dot-menu being cut off half
- [ ] How do you cancel editing a user? On editing, the 3-dot-menu should change to an X cancel icon.

2020-01-16 14:31 UTC, GretaD commented
>     * [ ]  "Done" button should also be primary so you know what to do next

I'll open a new ticket for this one and will work on it next week.
>     * [x]  On editing an entry, the action buttons are too much to the right, with the 3-dot-menu being cut off half
> 

Done

>     * [ ]  How do you cancel editing a user? On editing, the 3-dot-menu should change to an X cancel icon.

I'll open a new ticket for this one and will work on it next week.

2020-01-16 18:52 UTC, juliusknorr approved these changes

2020-01-16 18:53 UTC, juliushaertl commented on apps/settings/src/components/UserList.vue
> +			let quotaPreset = this.settings.quotaPreset.reduce((acc, cur) => acc.concat({
```suggestion
			const quotaPreset = this.settings.quotaPreset.reduce((acc, cur) => acc.concat({
```

2020-01-16 18:53 UTC, juliushaertl commented on apps/settings/src/components/UserList.vue
> +			let quotaPreset = this.settings.quotaPreset.reduce((acc, cur) => acc.concat({
Eslint fails and bundles need to be recompiled

2020-01-16 19:24 UTC, juliushaertl commented
Fixed eslint, css indent and pushed bundles

2020-01-16 19:30 UTC, georgehrke approved these changes

2020-01-16 22:24 UTC, merged