Adding capability about new chunking - refs #25682 (#26368)
nextcloud/server pull request #1849
Opened 2016-10-21 14:35 UTC by rullzer

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

2016-10-21 15:45 UTC, MorrisJobke commented
owncloud/core#25682

2016-10-21 15:47 UTC, MorrisJobke commented
Tested and works 👍

2016-10-22 12:02 UTC, LukasReschke requested changes

2016-10-22 12:02 UTC, LukasReschke commented on apps/dav/lib/Capabilities.php
> +	public function getCapabilities() {
Will add a small test for that.

2016-10-22 12:06 UTC, LukasReschke approved these changes

2016-10-22 12:06 UTC, LukasReschke commented
LGTM

2016-10-22 13:11 UTC, merged