Allow to edit admin/own user in the user management
nextcloud/server pull request #18555
Opened 2019-12-23 13:05 UTC by juliushaertl

Fix for https://github.com/nextcloud/server/issues/18530

2019-12-23 13:25 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> -			return getCurrentUser().uid !== this.user.id && this.user.id !== 'admin'
I actually think it was something for the subadmins here.
There is indeed an issue, but removing the check might not be the solution.
Subadmins should not be able to edit themselves nor edit the admin user iirc :)

2019-12-23 13:28 UTC, kesselb commented on apps/settings/src/components/UserList/UserRowSimple.vue
> -			return getCurrentUser().uid !== this.user.id && this.user.id !== 'admin'
`this.user.id !== 'admin'` seems to be wrong anyway. I can pick any name for my admin user :thinking:

2019-12-23 13:58 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> -			return getCurrentUser().uid !== this.user.id && this.user.id !== 'admin'
There is definitely something to change here, I agree, but I think this was here (not exactly like that before the multi line pr), that was needed before?

2019-12-23 14:29 UTC, juliushaertl commented on apps/settings/src/components/UserList/UserRowSimple.vue
> -			return getCurrentUser().uid !== this.user.id && this.user.id !== 'admin'
I don't see an issue with that even with those lines removed. 

user1 is group admin of group1
user2 is member of group1
admin is member of group1

As in the following screenshot (from user1) admin cannot be edited and user1 is not shown in general: 

![image](https://user-images.githubusercontent.com/3404133/71363300-fa21d780-2598-11ea-935b-9ce940d86555.png)

2019-12-23 16:01 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> -			return getCurrentUser().uid !== this.user.id && this.user.id !== 'admin'
Then all good! :)

2019-12-23 16:01 UTC, skjnldsv approved these changes

2019-12-23 19:52 UTC, kesselb commented
Yes. I can edit myself again :+1: 

1: Login as admin and check the userlist.

![image](https://user-images.githubusercontent.com/3902676/71377761-ef316c00-25c5-11ea-9113-038ff61b68d8.png)

2: Login as alice (subadmin of testgroup) and check the userlist.

![image](https://user-images.githubusercontent.com/3902676/71377819-16883900-25c6-11ea-9367-41d3b8833322.png)

Where is alice? :thinking:

2019-12-23 20:03 UTC, kesselb commented
1. Login as admin
2. Go to user management
3. Enter editing mode for yourself
4. Try to leave it (seems to work for any other user)

![Peek 2019-12-23 21-01](https://user-images.githubusercontent.com/3902676/71378273-7df2b880-25c7-11ea-8fec-c97663d7b0c2.gif)

2019-12-27 10:24 UTC, gary-kim requested changes
> 1. Login as admin
> 2. Go to user management
> 3. Enter editing mode for yourself
> 4. Try to leave it (seems to work for any other user)

It seems that you currently cannot save when editing your own user.

https://github.com/nextcloud/server/blob/32d279d60754b72e332a148d63272650056b9e98/apps/settings/src/components/UserList/UserRow.vue#L211-L218

2019-12-27 10:35 UTC, gary-kim commented
> Where is alice? thinking
> 
> ![image](https://user-images.githubusercontent.com/3902676/71377929-58b17a80-25c6-11ea-82f8-15993a75e49b.png)
> 
> Alice is returned by the server.

https://github.com/nextcloud/server/blob/32d279d60754b72e332a148d63272650056b9e98/apps/settings/src/components/UserList.vue#L311-L314

Seems to be intentional. I think it'd make more sense if their own user showed up but wasn't editable though.

2020-01-07 19:56 UTC, rullzer commented
Ping :)

2020-01-09 07:07 UTC, rullzer commented
master is NC19 now.
Please backport if it needs to go into 18

2020-01-17 21:06 UTC, kesselb commented
Conflicts :fearful:

2020-02-10 08:06 UTC, wiswedel commented
🏓

2020-02-24 12:21 UTC, wiswedel commented
Anyone still alive fixing this?

2020-02-24 12:42 UTC, juliushaertl commented
Yes, I was waiting for https://github.com/nextcloud/server/pull/19533 to be merged before doing another rebase dance.

2020-02-24 13:02 UTC, wiswedel commented
> Yes, I was waiting for #19533 to be merged before doing another rebase dance.

#19533 has been merged to master, but 18 backport failed

2020-02-25 18:13 UTC, juliushaertl commented
All comments should be addressed, editing the own user is now limited to admin users as it is done in the backend.

Ready for review.

2020-02-25 18:40 UTC, kesselb commented
What is that 3rdparty update about @juliushaertl? :confused:

2020-02-25 18:46 UTC, juliushaertl commented
Oh seems that got in there by accident, I'll fix that.

2020-02-25 18:56 UTC, kesselb commented
If Alice is a subdomain for group Test1234 and access the user list I see other users but not myself. I would expect to at least see Alice even if editing is disable. But not a blocker for this one. It's just confusing.

2020-02-25 19:00 UTC, kesselb commented
![Peek 2020-02-25 19-58](https://user-images.githubusercontent.com/3902676/75277934-4099e980-5809-11ea-9a95-82e64f04859d.gif)

As group admin (probably also as admin) the form for adding a user the page width is weird.

2020-02-25 19:03 UTC, kesselb commented
As group admin add a new user without selecting a group. The warning is shown for the button not the group list. Also not a blocker.

![image](https://user-images.githubusercontent.com/3902676/75278272-dd5c8700-5809-11ea-811d-84f0b1c7640e.png)

2020-02-25 19:04 UTC, juliushaertl commented
> If Alice is a subdomain for group Test1234 and access the user list I see other users but not myself. I would expect to at least see Alice even if editing is disable. But not a blocker for this one. It's just confusing.

That actually works for me: user1 is group admin of group1
![image](https://user-images.githubusercontent.com/3404133/75278322-f5340b00-5809-11ea-9ff8-0936d8524cf5.png)

2020-02-25 19:05 UTC, kesselb commented
Also anything related to showing quota seems to be broken. It seems to be possible to change the quota but not what quota is currently selected. But that's probably fixed by https://github.com/nextcloud/server/pull/18818.

2020-02-25 19:10 UTC, juliushaertl commented
> Also anything related to showing quota seems to be broken. It seems to be possible to change the quota but not what quota is currently selected. But that's probably fixed by #18818.

Oh joy, but yes, let's try to address that in #18818 then.

Same for the others. I can look into those, maybe you could create an issue for them, so I have a list rather than picking up pr comments.

2020-02-25 19:17 UTC, kesselb commented
> That actually works for me: user1 is group admin of group1
> ![image](https://user-images.githubusercontent.com/3404133/75278322-f5340b00-5809-11ea-9ff8-0936d8524cf5.png)

![image](https://user-images.githubusercontent.com/3902676/75279241-88ba0b80-580b-11ea-9379-17bc914f6e15.png)

Ah. I made Alice group admin but not member of the group. But yes a different story because Alice is missing in the user response.

2020-02-25 19:18 UTC, kesselb approved these changes

2020-02-25 23:05 UTC, gary-kim approved these changes
Tested and looked at the code. LGTM.

P.S. Never seen a computed returning a function before. Interesting.

2020-02-26 09:11 UTC, juliushaertl commented
> P.S. Never seen a computed returning a function before. Interesting.

Yeah the benefit of that is that the result is still cached, so it will only update if the dependency changes in contrast to a method.

2020-03-10 15:16 UTC, merged

2020-03-23 12:32 UTC, nursoda commented
I seem to be missing something here: I just installed 18.0.3 and still I can't edit my own user (no pencil icon). I need that e.g. to be able to assign myself to new groups. Currently, my (clumsy) workaround is to impersonate another admin and modify my user there…

![users](https://user-images.githubusercontent.com/8425483/77316860-7055e780-6d0a-11ea-9477-5200ede63b48.png)

2020-03-23 12:47 UTC, wiswedel commented
> I seem to be missing something here: I just installed 18.0.3 and still I can't edit my own user (no pencil icon). I need that e.g. to be able to assign myself to new groups. Currently, my (clumsy) workaround is to impersonate another admin and modify my user there…

I confirm that.
But even the impersonation trick does not work for the first admin that's been configured at installation. 

![image](https://user-images.githubusercontent.com/1804221/77318108-c3c93500-6d0c-11ea-920d-def74a02d8a7.png)

2020-03-23 14:16 UTC, rullzer commented
yeah 18.0.3 is a release with just a security fix.
This will come with 18.0.4

2020-03-23 14:26 UTC, vincentstans commented
> > Can i fix it by downloading and replacing some files ?
> 
> Sorry, @Uwe-MrT. It's only gonna be in 18.0.3, unless you check out the source and compile the Vue stuff by yourself. Then you can have it today.

2020-03-23 14:30 UTC, kesselb commented
@vincentstans what part of "18.0.3 is a release with just a security fix" did you not understand?

2020-04-16 19:25 UTC, Hydrog3n commented
Hello, 
This seems not working in 19.0.0Beta4 with only one user in my case. 

![ksnip_20200416-212430](https://user-images.githubusercontent.com/1223893/79497889-bf9ce880-8028-11ea-8fd7-72f4811705ee.png)

2020-04-30 20:38 UTC, nursoda commented
Works fine in 19 beta 5, thanks!