Sidebar polishing
nextcloud/server pull request #18732
Opened 2020-01-08 08:34 UTC by juliushaertl

Fixes:
- The currently selected file is not highlighted in the file list anymore https://github.com/nextcloud/server/issues/17737
- The tags should not me shown if none are sethttps://github.com/nextcloud/server/issues/17737
- Renaming a file opens the sidebar https://github.com/nextcloud/server/issues/18613

2020-01-08 09:19 UTC, rullzer approved these changes
Tested and fixes the mentioned points!
:guitar:

2020-01-08 09:57 UTC, skjnldsv commented
> * The tags should not me shown if none are set #17737

How do we toggle the view then?

2020-01-08 10:04 UTC, rullzer commented
> > * The tags should not me shown if none are set #17737
> 
> How do we toggle the view then?

You click the tag button ;)

2020-01-08 12:03 UTC, rullzer commented
![tags](https://user-images.githubusercontent.com/45821/71976685-3602a100-3217-11ea-9167-1b6b50e929cb.png)

2020-01-08 14:02 UTC, gary-kim requested changes

2020-01-08 14:02 UTC, gary-kim commented on apps/files/js/filelist.js
> +			}
Even if `show === false`, the sidebar should be opened to the new file if the Sidebar was already open. How about this?
```javascript
(typeof show === 'undefined' || !!show || OCA.Files.Sidebar.file !== '')
```

2020-01-08 15:29 UTC, juliushaertl commented on apps/files/js/filelist.js
> +			}
Wouldn't it then be just called with `_updateDetailsView(fileName)` and therefore call the open method?

2020-01-08 15:52 UTC, skjnldsv commented
Ideally it would have be nice to have a button in the sidebar Actions slot to show the tags. At least that is how Jan and I decided last time we talked about this :see_no_evil:

2020-01-08 16:02 UTC, gary-kim commented on apps/files/js/filelist.js
> +			}
It's used on renaming files, so if the sidebar was already open when a file is being renamed, switch to that file in the sidebar. If it was closed, don't open it.

From #18613

https://github.com/nextcloud/server/blob/27dc4ef268722f525b3ce1f1fe72f0b17531ad6a/apps/files/js/filelist.js#L2662-L2665

2020-01-09 07:07 UTC, rullzer commented
master is NC19 now.
Please backport if it needs to go into 18

2020-01-09 14:01 UTC, gary-kim commented
/backport to stable18

2020-01-13 21:28 UTC, jancborchardt commented
> Ideally it would have be nice to have a button in the sidebar Actions slot to show the tags. At least that is how Jan and I decided last time we talked about this see_no_evil

Yes please :) :label:

2020-01-14 05:29 UTC, gary-kim approved these changes

2020-01-14 05:34 UTC, gary-kim commented
@jancborchardt @skjnldsv Want to take another look at the tags?

2020-01-14 07:36 UTC, rullzer commented
/compile amend /

2020-01-14 10:19 UTC, skjnldsv commented
/compile amend /

2020-01-14 12:49 UTC, skjnldsv commented
/compile amend /

2020-01-14 12:53 UTC, skjnldsv commented
Should be good to go :)

2020-01-14 12:55 UTC, skjnldsv approved these changes

2020-01-14 13:51 UTC, skjnldsv commented
/compile amend /

2020-01-14 23:11 UTC, jancborchardt requested changes
- [x] When clicking "Manage tags", the "Collaborative tags" field should be focused and the popover of the 3-dot-menu should be closed
- [x] When the tags field is already shown and you click "Manage tags", the popover should be closed after hiding the tags field
- [x] I’d say simplify it from "Manage tags" to "Tags" since that is more concise and will work better with internationalization as well

2020-01-15 11:32 UTC, merged

2020-01-15 11:50 UTC, skjnldsv commented
Backport in https://github.com/nextcloud/server/pull/18911