introduce callForSeenUsers and countSeenUsers
nextcloud/server pull request #1888
Opened 2016-10-24 15:30 UTC by MorrisJobke

* downstream of https://github.com/owncloud/core/pull/26361

cc @rullzer @nickvergessen @schiessle 

I will create a ticket to check our codebase for similar usages.

2016-10-24 15:31 UTC, MorrisJobke commented
cc @icewind1991

2016-10-25 06:19 UTC, rullzer commented
I like it.
:+1:

2016-10-25 08:53 UTC, nickvergessen requested changes

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +		return (int)$query->fetchColumn();
Missing `$query->closeCursor()`

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +				'configkey', $queryBuilder->createNamedParameter('lastLogin'))
code style is odd in here

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +	 * @param string $search
Can't see this

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +		$queryBuilder = \OC::$server->getDatabaseConnection()->getQueryBuilder();
DI?

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +		$queryBuilder = \OC::$server->getDatabaseConnection()->getQueryBuilder();
DI?

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +		}
Missing `$query->closeCursor()`

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +	/**
new line before this?

2016-10-25 08:53 UTC, nickvergessen commented on lib/public/IUserManager.php
> +	public function callForSeenUsers (\Closure $callback);
awkward space

2016-10-25 08:53 UTC, nickvergessen commented on lib/private/User/Manager.php
> +	public function callForSeenUsers (\Closure $callback) {
awkward space

2016-10-28 07:43 UTC, nickvergessen requested changes

2016-10-28 07:43 UTC, nickvergessen commented on lib/public/IUserManager.php
> +	 * @param string $search
invalid doc

2016-10-28 08:13 UTC, rullzer commented on lib/private/User/Manager.php
> +		$queryBuilder = \OC::$server->getDatabaseConnection()->getQueryBuilder();
Nah that will cause the DB to be initialized to early. So then installing fails. We should fix that at some point. But probabaly can't right now.

2016-10-28 09:08 UTC, rullzer commented
I fixed most of the comments.
Made the IConfig always injected.

Injecting the DB here fails hard as it gets initialized to early then.

I say lets get this in. :+1:

2016-10-28 09:42 UTC, nickvergessen commented
Fine by me, also tested with the announcement center
Failing tests are sign-off only.

👍

2016-10-28 09:42 UTC, nickvergessen approved these changes

2016-10-28 09:42 UTC, merged