Bring user deletion account
nextcloud/server pull request #1893
Opened 2016-10-24 16:49 UTC by tcitworld

Bring the possibility for an user to delete it's own account. Administrators can enable/disable this functionality.

See https://github.com/owncloud/core/issues/158

- [ ] Security issues
- [ ] Redirect to login with js after deleting account

2016-10-24 19:00 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +		$userOwnDeletion = $this->config->getSystemValue('user_own_account_deletion', false);
Please no config.php switch. This should be stored in the database.

2016-10-24 19:00 UTC, MorrisJobke commented on settings/js/personal.js
> +function deleteAccount () {
Global namespace 🙈 Yes I know, the other methods are also in the global namespace - but at some point we need to clean up this mess 😉

2016-10-24 19:00 UTC, MorrisJobke commented on settings/js/personal.js
> +function deleteAccount () {
Global namespace 🙈 Yes I know, the other methods are also in the global namespace - but at some point we need to clean up this mess 😉

2016-10-24 19:10 UTC, rullzer commented
Can't we just do this as an app?

2016-10-24 19:43 UTC, tcitworld commented
I thought it was a quite small feature to create an app. Also it's configurable by the admin.

2016-10-25 08:57 UTC, tcitworld commented on settings/Controller/UsersController.php
> +		$userOwnDeletion = $this->config->getSystemValue('user_own_account_deletion', false);
Okay. Where should it be activated by the administrator. Additional settings ?

2016-10-25 09:00 UTC, LukasReschke requested changes
I'd also prefer this to be in it's own app. But that may just be personal preference.

In any case, there are some problems with this:
- Missing unit tests for the UsersController
- The "delete your account" should only appear in the settings when it is possible (e.g. the user backend of the currently logged-in user supports it)
- Some remarks that Morris had as well.

2016-10-25 10:58 UTC, tcitworld commented
Most of it is done. I just don't know where the admin setting should show up. Also, how to test if backend supports deletion (I've just put Database for now) ?

2016-10-26 10:11 UTC, nickvergessen commented on settings/templates/personal.php
> +<?php if ($_['accountDeletionEnabled']) { ?>
Should be at the bottom of the site in my opinion

2016-10-26 10:15 UTC, LukasReschke commented
> Most of it is done. I just don't know where the admin setting should show up. Also, how to test if backend supports deletion (I've just put Database for now) ?

`\OCP\UserInterface::implementsActions` + add an action constant

2016-10-26 10:15 UTC, LukasReschke requested changes

2016-10-26 10:15 UTC, LukasReschke commented on settings/personal.php
> +$accountDeletionEnabled = $config->getAppValue('core', 'user_own_account_deletion', false) && $user->getBackendClassName() === 'Database';
> Most of it is done. I just don't know where the admin setting should show up. Also, how to test if backend supports deletion (I've just put Database for now) ?

`\OCP\UserInterface::implementsActions` + add an action constant + adjust the backends.

No hard-coded hackery here 😉

2016-10-28 20:08 UTC, tcitworld commented on lib/private/User/User.php
> +		if (!filter_var($this->config->getAppValue('core', 'user_own_account_deletion', false), FILTER_VALIDATE_BOOLEAN)) {
For some reason. Any help here ?

2016-10-28 20:08 UTC, tcitworld commented on lib/public/IUser.php
> +	 * @since 11.0.0
This or ownCloud notation ?

2016-10-28 20:09 UTC, tcitworld commented on settings/personal.php
> +if ($user->canDeleteAccount()) {
Better way ?

2016-11-05 11:30 UTC, LukasReschke commented on lib/private/User/User.php
> +		if (!filter_var($this->config->getAppValue('core', 'user_own_account_deletion', false), FILTER_VALIDATE_BOOLEAN)) {
`(bool)$this->config->getAppValue('core', 'user_own_account_deletion', 0)` and store an integer would have been my approach.

2016-11-05 11:30 UTC, LukasReschke commented on lib/public/IUser.php
> +	 * @since 11.0.0
I'm fine with this.

2016-11-05 11:30 UTC, LukasReschke commented on settings/personal.php
> +if ($user->canDeleteAccount()) {
👍

2016-11-05 12:43 UTC, tcitworld commented
Rebased. Please review. :-)

2016-11-05 13:27 UTC, rullzer commented
I still really dislike this being in core. In 99.99% of the cases this is not required. For me the only real usecase is if a service provider wants to allow people to delete their accounts. Which is a fair use case. But, again, please do it as an app.

2016-11-05 13:55 UTC, MariusBluem commented
> For me the only real usecase is if a service provider wants to allow people to delete their accounts. Which is a fair use case. But, again, please do it as an app.

Agreed. And Service Providers may want to use their own CRM to have better control over it. So the use-case is as small as this is something for a separate app, I think 😁 ...However: Good work 👍

2016-11-05 13:56 UTC, closed without merging

2016-11-05 13:57 UTC, tcitworld commented
Okay ! (I will delete the branch later)

2016-11-07 11:28 UTC, nickvergessen reviewed
Needs changes

2016-11-07 11:28 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +		$userOwnDeletion = $this->config->getAppValue('core', 'user_own_account_deletion', false);
default value should be `0`

2016-11-07 11:28 UTC, nickvergessen commented on settings/js/personal.js
> +		OC.dialogs.confirm('Do you really want to delete your account ? All your data will be lost !', 'Delete your account ?', function (res) {
Please remove the spaces before `?` and `!`