Make the share accept process optional
nextcloud/server pull request #18940
Opened 2020-01-16 17:52 UTC by juliushaertl

This PR makes accepting shares automatically the default. There are two config.php settings:
- sharing.enable_share_accept - set to true to disable automated share acceptance (reverting the current logic in master)
- sharing.force_share_accept - allow to enforce the new mechanism

The sharing settings will be hidden if accepting is enforced.

2020-01-16 17:53 UTC, juliushaertl commented
/backport to stable18

2020-01-16 18:11 UTC, rullzer requested changes
Also I think you need to update the classmap

2020-01-16 18:11 UTC, rullzer commented on apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
> +		$defaultAcceptSystemConfig = $this->config->getSystemValueBool('sharing.enable_share_accept', false) ? 'no' : 'yes';
Shouldn't we have another if here. That if share accept is false. We just accept it directly?

2020-01-16 18:25 UTC, juliushaertl commented on apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
> +		$defaultAcceptSystemConfig = $this->config->getSystemValueBool('sharing.enable_share_accept', false) ? 'no' : 'yes';
No this is just the default value that might be overwritten later by the user value. If no user value is set it will be used.

2020-01-16 18:26 UTC, juliushaertl commented on apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
> +		$defaultAcceptSystemConfig = $this->config->getSystemValueBool('sharing.enable_share_accept', false) ? 'no' : 'yes';
No this is just the default value that might be overwritten later by the user value. If no user value is set it will be used.

2020-01-16 18:27 UTC, rullzer commented on apps/files_sharing/lib/Listener/UserShareAcceptanceListener.php
> +		$defaultAcceptSystemConfig = $this->config->getSystemValueBool('sharing.enable_share_accept', false) ? 'no' : 'yes';
Aaaah right!

2020-01-16 18:27 UTC, rullzer approved these changes

2020-01-16 18:30 UTC, skjnldsv approved these changes

2020-01-17 00:14 UTC, merged

2022-11-14 22:28 UTC, juliushaertl commented
Autodocumented through the config.php sample