endorse password for share links
nextcloud/server pull request #1894
Opened 2016-10-24 16:53 UTC by MorrisJobke

works like "enforce password protection", but let the
user optionally remove the password protection after the
password is set.

* downstream of https://github.com/owncloud/core/pull/26376

cc @rullzer @schiessle @nickvergessen 

I tested this and it works

2016-10-24 19:08 UTC, rullzer commented
mmmm. Do we really want this? It feels like a very specific option.

2016-10-24 19:12 UTC, MorrisJobke commented
> mmmm. Do we really want this? It feels like a very specific option.

This is up for discussion now.

@jancborchardt for simplify the possible settings vs @karlitschek for feature completeness 

The stage is yours 😉

2016-10-24 21:01 UTC, jancborchardt commented
Sounds like it can make sense, yes. Only being lax and forced about it is strange, this seems like a needed middle ground to do it properly.

2016-10-24 21:05 UTC, LukasReschke commented
Rather strange UX and I don't really like it. A proper behaviour would be to actually show a confirmation dialogue or something like that which asks "Do you really not want to set any password?".

Otherwise this just seems like an confusing solution… 👎 from my side.

2016-10-25 07:16 UTC, karlitschek commented
It is a very specific usecase but not bad. I think it makes some sense 👍

2016-10-25 07:27 UTC, LukasReschke commented
👎 until this is fixed on the client side as well or a _big_ warning is appended that this only works on web.

This gives a wrong level of security plus would qualify for a bounty actually in our bounty program… (Client-Side Enforcement of Server-Side Security)

2016-10-25 07:30 UTC, LukasReschke requested changes

2016-10-25 07:30 UTC, LukasReschke commented on settings/templates/admin/sharing.php
> +		<label for="enableLinkPasswordByDefault"><?php p($l->t('Always ask for a password'));?></label><br/>
Needs to be adjusted. Or the clients fixed.

2016-10-25 07:31 UTC, LukasReschke commented on settings/templates/admin/sharing.php
> +		<label for="enableLinkPasswordByDefault"><?php p($l->t('Always ask for a password'));?></label><br/>
(once that is fixed I'm "ok" with this, not happy but "ok".)

2016-10-25 08:08 UTC, nickvergessen commented
> Test\Settings\Admin\SharingTest::testGetFormWithoutExcludedGroups
Expectation failed for method name is equal to <string:getAppValue> when invoked at sequence index 8
Parameter 1 for invocation OCP\IConfig::getAppValue('core', 'shareapi_enable_link_password...efault', 'no') does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'shareapi_enabled'
+'shareapi_enable_link_password_by_default'

2016-11-02 19:55 UTC, MorrisJobke commented
Lets close this for now. We have no real use case for this already and it is only a partial solution that will cause more issues, than it solves. 

If someone feels the need for this - feel free to reopen this and work again on this.

2016-11-02 19:55 UTC, closed without merging