Provide links to calendar in event creation/update activities
nextcloud/server pull request #19039
Opened 2020-01-21 09:51 UTC by tcitworld

Since Calendar 2.0 we have dedicated routes so we can link to events directly from the Activity app.

See also https://github.com/nextcloud/activity/pull/420 for proper formatting in the Activity app.

![Screenshot_2020-01-21 Activity - Nextcloud- 2](https://user-images.githubusercontent.com/2197836/72794070-aa880780-3c3b-11ea-9344-e0dec2ed5f8c.png)
(The last item has also a link to the event)

2020-01-21 09:53 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +		$appManager = \OC::$server->getAppManager();
Autoinject is probably better here.

2020-03-11 08:56 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +		return $appManager->isEnabledForUser('calendar') && version_compare($appManager->getAppVersion('calendar'), '2.0.0') >= 0;
Can we solve the version requirement by only having compatible releases available for 19?
cc @georgehrke

2020-03-11 09:05 UTC, georgehrke commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +		return $appManager->isEnabledForUser('calendar') && version_compare($appManager->getAppVersion('calendar'), '2.0.0') >= 0;
Hm, I would prefer not artificially forcing users to update the server.

2020-03-11 09:10 UTC, georgehrke submitted a review, later dismissed
~I'm blocking, to put this on hold for now. I'm worried I have to change the url format in order to fix https://github.com/nextcloud/calendar/issues/1894. Will look into that issue today.~

Never mind, it's yet again related to unencoded group names

2020-03-11 09:19 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +		return $appManager->isEnabledForUser('calendar') && version_compare($appManager->getAppVersion('calendar'), '2.0.0') >= 0;
The other way around, but this is already the case. So the version comparison can be removed.

2020-04-16 19:35 UTC, rullzer commented
@georgehrke yay or nay?

2020-04-16 19:37 UTC, georgehrke commented
@tcitworld can you remove the version check as suggested by @nickvergessen.

Then this is good to go

2020-04-17 08:19 UTC, tcitworld commented
Removed the version checked, properly injected dependencies, moved `generateObjectParameter` to `OCA\DAV\CalDAV\Activity\Provider\Event` because not needed in `OCA\DAV\CalDAV\Activity\Provider\Base` and improved tests, so please give a quick look again.

2020-04-17 08:33 UTC, georgehrke approved these changes
Code looks good

2020-04-21 09:07 UTC, nickvergessen commented
Activity PR is merged

2020-04-21 09:13 UTC, nickvergessen requested changes

2020-04-21 09:13 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +	public function __construct(IActivityManager $activityManager, IGroupManager $groupManager, IUserSession $userSession, IAppManager $appManager) {
can we keep the constructor as first function?

And feel free to remove the docs when moving it as they are just duplicating the stronger type hints.

2020-04-21 09:13 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +				$objectId = base64_encode('/remote.php/dav/calendars/' . $owner . '/' . $calendarData['uri'] . '/' . $objectData['uri']);
could this all be done on rendering instead?
Just store owner, firstoccurence and uri in the array,
but to all the calculation on rendering. That would allow us to always link to the next occurance of an repeating event instead of the first one from years ago?

2020-04-21 17:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +				$objectId = base64_encode('/remote.php/dav/calendars/' . $owner . '/' . $calendarData['uri'] . '/' . $objectData['uri']);
> could this all be done on rendering instead?

Yes, will do.

> That would allow us to always link to the next occurance of an repeating event instead of the first one from years ago?

I don't see how can I get the next occurrence of a repeating event without directly parsing the raw ICS data and [expanding it](https://sabre.io/vobject/recurrence/). I only have the first and the last, not the recurring rule.

2020-04-21 18:47 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Backend.php
> +		foreach (array_unique($users) as $user) {
`getUsersForShares` potentially returning the owner itself because of public links for calendar should be fixed somewhere else, this is a temporary fix. We need a proper `nc:` property to indicate that. cc @georgehrke

2020-04-21 18:48 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +					'mode' => 'sidebar',
This could get user's `skipPopover` setting to know if we use the popover or the sidebar, do you want that?

2020-04-21 18:56 UTC, tcitworld commented
Slighty off-topic, it's kinda sad we can't properly detect event being renamed, it makes you think you updated two different events when you just renamed one twice.
![image](https://user-images.githubusercontent.com/2197836/79902869-7676db00-8412-11ea-91d6-04682ccccdcb.png)

2020-04-24 14:59 UTC, nickvergessen requested changes

2020-04-24 14:59 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +	protected function generateObjectParameter(array $eventData) {
This was in the base because it's also used in Todo.php and it makes it more obvious that it is shared.
But I guess it's fine eitherway.

2020-04-24 14:59 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +				$params['link'] = $this->url->linkToRouteAbsolute('calendar.view.indexview.timerange.edit', $link);
this will :boom: when calendar is disabled,
so maybe we return the params without the link (since it's optional anyway) in the exception catching?

2020-04-24 15:00 UTC, georgehrke commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +				$params['link'] = $this->url->linkToRouteAbsolute('calendar.view.indexview.timerange.edit', $link);
So just wrap in `isEnabledForUser`?

2020-04-24 15:01 UTC, georgehrke commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +					'mode' => 'sidebar',
We actually have a special route for this, but it's also hardcoded to sidebar at the moment.

I would just keep it as is and improve later on :)

2020-04-24 15:03 UTC, georgehrke commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +					'mode' => 'sidebar',
If you use that route, we could actually get rid of `firstoccurrence`

2020-04-24 16:31 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +				$params['link'] = $this->url->linkToRouteAbsolute('calendar.view.indexview.timerange.edit', $link);
Yes

2020-04-26 09:06 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +					'mode' => 'sidebar',
I'm using `/dayGridMonth/now/edit/sidebar/$objectId/next` then.

2020-04-26 09:09 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +				$params['link'] = $this->url->linkToRouteAbsolute('calendar.view.indexview.timerange.edit', $link);
Not sure I follow here, we set the link inside the `AppManager::isEnabledForUser` check already, and params without the link will be return at the end properly.

2020-04-26 09:13 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +	protected function generateObjectParameter(array $eventData) {
Yeah, my reasoning was that Calendar doesn't need it.

2020-04-30 07:10 UTC, rullzer approved these changes
Lets do this

2020-04-30 07:10 UTC, merged

2020-04-30 07:11 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Provider/Event.php
> +				$params['link'] = $this->url->linkToRouteAbsolute('calendar.view.indexview.timerange.edit', $link);
Ah, didnt see it as it was all at the end of this long if