Add a public event for contacts interaction
nextcloud/server pull request #19075
Opened 2020-01-22 10:37 UTC by ChristophWurst

Some example of where we could use this

* Sharing a file
* Sending a message in Mail
* Sending invites in Calendar
* Clicking actions in the contacts menu

It's yet to be decided where and how we'll listen to the event and persist the data.

cc @georgehrke @nickvergessen @rullzer @skjnldsv

2020-03-04 08:52 UTC, ChristophWurst commented
Restructured for https://github.com/nextcloud/server/pull/19680

2020-03-04 11:32 UTC, nickvergessen commented
As an app I would simply dispatch an `ContactInteractedWithEvent` event I guess?

2020-03-04 11:35 UTC, ChristophWurst commented
> As an app I would simply dispatch an `ContactInteractedWithEvent` event I guess?

Exactly!

2020-03-05 15:40 UTC, ChristophWurst commented
- [ ] Requires https://github.com/nextcloud/server/pull/19795

2020-03-19 09:39 UTC, nickvergessen commented on apps/files_sharing/lib/Listener/ShareInteractionListener.php
> +			$this->logger->warning('Share type does not allow to emit interaction event');
Talk will spam heavily with this... reduce to info or even debug?

2020-03-19 09:55 UTC, ChristophWurst commented on apps/files_sharing/lib/Listener/ShareInteractionListener.php
> +			$this->logger->warning('Share type does not allow to emit interaction event');
Debug is sufficient. Thanks for the info!

2020-03-19 10:52 UTC, georgehrke commented
Aside from the code-review, is this already testable or do we need to implement the `ContactInteractedWithEvent` in other places first?

2020-03-19 11:03 UTC, ChristophWurst commented
@georgehrke 

> I added some glue to convert share events to interaction events. This way you can test the feature already. Just share a file to a user, email or remote user. Then open the contacts app.

;)

2020-03-20 10:38 UTC, georgehrke requested changes

2020-03-20 10:38 UTC, georgehrke commented on apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
> +			'FN' => $contact->getEmail() ?? $contact->getUid() ?? $contact->getFederatedCloudId(),
If the contact you interacted with is a user, it should use the display name, not UID.

2020-03-20 10:40 UTC, georgehrke commented on apps/contactsinteraction/appinfo/info.xml
> +	<default_enable/>
I'm not sure about this. I can already see people complain that there is a "tracking" app that you can't disable.

2020-03-20 10:47 UTC, nickvergessen commented on apps/contactsinteraction/appinfo/info.xml
> +	<default_enable/>
default enabled !== force enabled

2020-03-20 10:48 UTC, nickvergessen commented on core/shipped.json
> +    "contactsinteraction",
@georgehrke this should be changed instead of `<default_enabled>`

2020-03-20 10:49 UTC, nickvergessen commented on core/shipped.json
> +    "contactsinteraction",
And I have to admit, I don't see a reason to force this?!

2020-03-20 12:40 UTC, ChristophWurst commented on apps/contactsinteraction/appinfo/info.xml
> +	<default_enable/>
oh yes

2020-03-20 12:41 UTC, ChristophWurst commented on core/shipped.json
> +    "contactsinteraction",
yep, should be optional of course!

2020-03-20 12:43 UTC, ChristophWurst commented on apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php
> +			'FN' => $contact->getEmail() ?? $contact->getUid() ?? $contact->getFederatedCloudId(),
note to self: get the user object and use `\OCP\IUser::getDisplayName`

2020-03-20 13:04 UTC, rullzer requested changes
awesome. seems to do the trick and teh code looks sane.
Lets fix the open issues and get this in!

2020-03-20 13:05 UTC, ChristophWurst commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
just to make it non-sharable. that was a recommendation by @georgehrke to get the DAV props right IIRC

2020-03-20 13:06 UTC, georgehrke commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
No, I think it was related to the bug in Contacts that it crashes when shares is null. Contacts always assumes it's an array.

@skjnldsv Was that fixed?

2020-03-20 13:09 UTC, ChristophWurst commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
oh yes, sorry, that was the reason

2020-03-20 13:22 UTC, ChristophWurst commented
Fixed review comments with the exception of the sharing props. The app is now optional and not enabled by default.

2020-03-20 13:34 UTC, skjnldsv commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
> @skjnldsv Was that fixed?

No idea xD
Please do as clean as possible, if contacts have a weird hack somewhere for it, I'll manage around. I rather have you not worry about contacts. But I don't remember what Georg is talkig about :)

2020-03-20 13:37 UTC, georgehrke commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
@skjnldsv You are assuming that `shares` is an Array here:
https://github.com/nextcloud/contacts/blob/master/src/store/addressbooks.js#L65

But it's only an array, if an Addressbook implements `IShareable`, otherwise it's just null.

2020-03-20 13:39 UTC, ChristophWurst commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
k, then let me remove that ;)

2020-03-20 13:43 UTC, rullzer commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
> @skjnldsv You are assuming that `shares` is an Array here:
> https://github.com/nextcloud/contacts/blob/master/src/store/addressbooks.js#L65
> 
> But it's only an array, if an Addressbook implements `IShareable`, otherwise it's just null (or `undefined`, not sure).

Probably because all other addressbooks have it. But I agree we should probably fix contacts then :)

2020-03-20 13:55 UTC, skjnldsv commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
So if undefined = not shareable?

2020-03-20 13:58 UTC, georgehrke commented on apps/contactsinteraction/lib/AddressBook.php
> +class AddressBook extends ExternalAddressBook implements IACL, IShareable {
To check if it's shareable just use `addressbook.isShareable()`:
https://github.com/nextcloud/cdav-library/blob/master/src/models/davCollectionShareable.js#L123

If shares is undefined or null, just treat it like it was an empty array.

2020-03-20 14:33 UTC, nickvergessen commented
> not enabled by default.

I think that would be fine to do?

2020-03-20 14:49 UTC, rullzer commented
> > not enabled by default.
> 
> I think that would be fine to do?

I agree. force enabling it is meh. But if we don't enable it hardly anybody will use it.

2020-03-21 07:49 UTC, rullzer approved these changes
Then lets do this!

2020-03-24 09:25 UTC, georgehrke approved these changes
Tiny nitpick, but otherwise 👍

2020-03-24 09:25 UTC, georgehrke commented on apps/contactsinteraction/lib/AddressBook.php
> +				'principal' => $this->getOwner() . '/calendar-proxy-read',
You don't really need this block. This is only for calendar-delegation.

2020-03-24 14:21 UTC, skjnldsv commented on apps/contactsinteraction/lib/AddressBook.php
> +
Githu is not liking this file, I don't see the linting :thinking:

2020-03-24 14:45 UTC, skjnldsv requested changes
Wait a bit before merging

2020-03-24 15:02 UTC, skjnldsv commented
So, initially the goal was to have this built on top of an API other apps could later use to register new entities to interact with (files, events... you name it!) 

> https://github.com/nextcloud-gmbh/professional_services/issues/227#issuecomment-577084257
> The idea would be to use events, both on the front-end as well as on the back-end. Something like a \OCP\Collaboration\Events\UserInteractionEvent apps can emit when they find a new interaction. Events have the advantage that they will also work when nobody listens.

I feel like it's not clear if this is an api we'll be able to use for other thing than contacts after thi sis merged and I'm afraid to get another super specific api in server.

What do you all think? Can we slightly adjust this so we have a global `InterractedEntity.php` and we allow apps to extend Entities to it or something? Does it make sense ?

2020-03-24 19:24 UTC, rullzer commented
@skjnldsv I get your point. But right now this is what we designed it for. Do you have a real short term plan to use this? Else I'd say lets get it in. And when we come up with a different use case we can always change this or deprecate it and just move on.

Does that sound sane?

2020-03-24 19:28 UTC, skjnldsv commented
> Do you have a real short term plan to use this? Else I'd say lets get it in.

Nah, it's just a matter of keeping things clean. I would have loved to migrate the recent files to this too.
Also because that's how I was pushing things at the core of this implementation, so a little disappointed.  :)

2020-03-25 09:00 UTC, rullzer commented
> > Do you have a real short term plan to use this? Else I'd say lets get it in.
> 
> Nah, it's just a matter of keeping things clean. I would have loved to migrate the recent files to this too.
> Also because that's how I was pushing things at the core and beginning of this implementation. I talked about this a lot on the issue and in talk. So a little disappointed. :)

fair enough.
In any case. Lets get this in. And if we want to do things more generic in the future we see what we do then. THere is no need to over engineer it now. And we can always move things later.

2020-03-25 09:29 UTC, skjnldsv approved these changes
Let's merge :)

2020-03-25 09:31 UTC, skjnldsv commented
```
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT "carddata" FROM "oc_cards" WHERE ("id" IN (SELECT DISTINCT "cardid" FROM "oc_cards_properties" WHERE ("addressbookid" IN (SELECT DISTINCT "id" FROM "oc_addressbooks" WHERE "principalUri" = ?)) AND (("name" = ?) AND ("value" = ?)) GROUP BY "cardid")) AND ("addressbookid" IN (SELECT DISTINCT "id" FROM "oc_addressbooks" WHERE "principalUri" = ?)) LIMIT 1' with params ["principals\/users\/test-versions-user", "UID", "test-versions-user2", "principals\/users\/test-versions-user"]:
7425 |  
7426 | SQLSTATE[42703]: Undefined column: 7 ERROR: column "principalUri" does not exist
7427 | LINE 1: ...SELECT DISTINCT "id" FROM "oc_addressbooks" WHERE "principal...
7428 | ^
7429 | HINT: Perhaps you meant to reference the column "oc_addressbooks.principaluri".
```

Unrelated? Looks like it, but can't be sure. @ChristophWurst?

2020-03-25 14:51 UTC, skjnldsv commented
Pls rebase :see_no_evil:

2020-03-25 17:39 UTC, merged

2023-10-29 01:00 UTC, jdaviescoates commented
Some contact randomly end up in my Recently Contacted here:

![image](https://github.com/nextcloud/server/assets/2113743/841c340e-4da0-4460-9fac-f7442aa190da)

But whilst they are then it's impossible to edit them, which is very frustrating. What possible purpose does this serve?

![image](https://github.com/nextcloud/server/assets/2113743/ee07c46c-c422-4da8-9e03-7f7c087a07d5)

I mean, I can see why Recently Contacted could be useful, but why lock them in read-only mode?!?