Fix data Apache2 .htaccess typo
nextcloud/server pull request #19165
Opened 2020-01-27 16:21 UTC by Simounet

Hi there,
Thank you so much for this amazing piece of software.
Just wanted to fix a quick typo from the data's `.htaccess`. Let me know if I can add anything.
Have a nice day.

2020-01-27 16:23 UTC, kesselb commented
/backport to stable18

2020-01-27 16:25 UTC, kesselb commented
Thanks :+1:

`git commit --amend --signoff`
`git push --force-with-lease origin fix/data-apache-htaccess-typo` 

Would you mind to use the above command to fix the DCO? If you added / removed commits in the meantime the command is proably different.

2020-01-27 16:25 UTC, kesselb approved these changes

2020-01-27 16:27 UTC, skjnldsv approved these changes

2020-01-27 16:35 UTC, Simounet commented
> Thanks +1
> 
> `git commit --amend --signoff`
> `git push --force-with-lease origin fix/data-apache-htaccess-typo`
> 
> Would you mind to use the above command to fix the DCO? If you added / removed commits in the meantime the command is proably different.

Fixed and thanks for the quick reply!

2020-01-27 17:46 UTC, MichaIng requested changes

2020-01-27 17:46 UTC, MichaIng commented on lib/private/Setup.php
> +		$content .= "    <IfModule>\n";
Many thanks, my fault, but it must be: `</IfModule>\n` closing the directive above. 

Passed tests most likely since it is only pared on Apache2.2

2020-01-27 17:50 UTC, Simounet commented on lib/private/Setup.php
> +		$content .= "    <IfModule>\n";
I'm using Apache2.4 and get the parsing error.

2020-01-27 17:58 UTC, MichaIng commented on lib/private/Setup.php
> +		$content .= "    <IfModule>\n";
@Simounet
Ah you're right, in my case it's because data dir is outside the webroot.

2020-01-27 18:00 UTC, MichaIng commented
The `.htaccess` in config btw was correct: https://github.com/nextcloud/server/blob/master/config/.htaccess#L17

2020-02-05 10:11 UTC, MichaIng commented
@Simounet 
 Would you mind to apply the requested change, as we should have this fix ready for next minor release. I hope it's clear that the buggy tag must be a closing tag.

2020-02-05 10:18 UTC, Simounet commented
Hello @MichaIng ,
Sorry for the late reply. I just fixed it.

2020-02-05 10:29 UTC, kesselb commented
/backport to stable18

2020-02-05 10:31 UTC, kesselb commented
cc @rullzer would be nice for 18.0.1.

2020-02-05 10:39 UTC, MichaIng approved these changes

2020-02-05 10:42 UTC, MichaIng commented
:rocket:

2020-02-05 11:32 UTC, merged