Inline oc.js when possible!
nextcloud/server pull request #1917
Opened 2016-10-25 19:41 UTC by rullzer

With https://github.com/nextcloud/server/pull/1871 in we can now do fancy pancy stuff. Like inline javascript safely.

This PR bring you the inlining of oc.js. This file was loaded on each pageload separatly and was a blocking call! Now if your browser support CSPv3 it will inline the file saving you a blocking (non cacheable request!).

* Move oc.js generation to helper class
* Move CSPv3 test
* Inline oc.js when possible

@LukasReschke as discussed!

CC: @MorrisJobke @nickvergessen @icewind1991

2016-10-25 19:52 UTC, LukasReschke requested changes
Awesome! Some nitpicks are still existent though ;)

2016-10-25 19:52 UTC, LukasReschke commented on core/Controller/OCJSController.php
> +	public function __construct($appName,
A kingdom for PHPDocs 🚀

2016-10-25 19:52 UTC, LukasReschke commented on core/templates/layout.base.php
> +				<?php echo($_['inline_ocjs']); ?>
`print_unescaped`? :)

2016-10-25 19:52 UTC, LukasReschke commented on core/templates/layout.guest.php
> +				<?php echo($_['inline_ocjs']); ?>
`print_unescaped`? :)

2016-10-25 19:52 UTC, LukasReschke commented on core/templates/layout.user.php
> +				<?php echo($_['inline_ocjs']); ?>
`print_unescaped`? :)

2016-10-25 19:52 UTC, LukasReschke commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +								ContentSecurityPolicyNonceManager $cspNonceManager) {
Update PHPDoc? ;)

2016-10-25 20:03 UTC, rullzer commented
@LukasReschke fixed

2016-10-25 20:14 UTC, LukasReschke approved these changes

2016-10-25 20:14 UTC, LukasReschke commented
Good stuff! :+1:

2016-10-25 22:19 UTC, MorrisJobke commented
Code looks good and I tested this in Firefox, Safari, Chrome, IE and Edge.

2016-10-25 22:20 UTC, merged

2016-10-26 07:43 UTC, LukasReschke commented
Small addition: https://github.com/nextcloud/server/pull/1920 :)

2016-10-31 09:58 UTC, nickvergessen commented
Please also delete the old file, just cost björn and me some minutes to figure out, why the break point didn't stop...