Allow to overwrite share target mountpoints
nextcloud/server pull request #19321
Opened 2020-02-06 16:11 UTC by nickvergessen

Required for https://github.com/nextcloud/spreed/pull/2876

2020-02-17 08:04 UTC, nickvergessen commented
Would be nice to get this in, so we can finish the Talk side of this feature.

2020-02-21 11:04 UTC, ChristophWurst approved these changes
Not the most appropriate use of events, but fine by me

2020-02-26 10:06 UTC, juliusknorr approved these changes

2020-02-27 13:45 UTC, rullzer requested changes

2020-02-27 13:45 UTC, rullzer commented on lib/public/Share/Events/VerifyMountPointEvent.php
> +								View $view,
any reason not to just use the node API here?

2020-02-27 14:42 UTC, nickvergessen commented on lib/public/Share/Events/VerifyMountPointEvent.php
> +								View $view,
In https://github.com/nextcloud/server/pull/19321/files#diff-815375797d10aaf371d625ead4ed15beR93 we don't have the nodes api available and I wanted to keep the impact minimal (remember, we are inside the process of setting up the FS for the user)

2020-02-28 09:08 UTC, rullzer commented on lib/public/Share/Events/VerifyMountPointEvent.php
> +								View $view,
Right right.
Ok then lets do it.

2020-02-28 09:08 UTC, rullzer approved these changes

2020-02-28 12:41 UTC, merged