Remove deprecated global variables
nextcloud/server pull request #19357
Opened 2020-02-07 16:10 UTC by ChristophWurst

A few apps might break because nobody cared to adapt. So let's remove this sooner than later :)

2020-02-07 16:15 UTC, skjnldsv approved these changes

2020-02-07 16:16 UTC, juliusknorr requested changes
We should at least fix our internal usages in server before removing them. This breaks the files app out of the box :wink: 

```
Uncaught (in promise) ReferenceError: humanFileSize is not defined
    at FileList._createRow (filelist.js:1609)
    at FileList.fileList._createRow (tagsplugin.js:236)
    at FileList.e._createRow (comments.js:1)
    at FileList.e._createRow (additionalScripts.js:1)
    at FileList._renderRow (filelist.js:1793)
    at FileList._nextPage (filelist.js:1281)
    at FileList.setFiles (filelist.js:1359)
    at FileList.reloadCallback (filelist.js:2098)
    at Object.<anonymous> (main.js:25)
    at c (main.js:25)
```

2020-02-07 16:27 UTC, ChristophWurst commented
[The files app? Is that thing still around](https://www.youtube.com/watch?v=Q9A0Vufw3NQ)

Yeah, guess we need that beautifully rewritten Vue files app. Then we can easily import the function there :grin:

2020-02-07 16:27 UTC, ChristophWurst commented
Oh we can just use `OC.Util.humanFileSize`

2020-02-07 16:35 UTC, skjnldsv commented on apps/files/js/filelist.js
> +				this.$el.find('#headerSize a>span:first').text(OC.Util.OC.Util.humanFileSize(summary.totalSize));
```suggestion
				this.$el.find('#headerSize a>span:first').text(OC.Util.humanFileSize(summary.totalSize));
```

2020-02-07 16:35 UTC, skjnldsv commented on apps/files/js/filelist.js
> +							oldFile.find('td.filesize').text(OC.Util.OC.Util.humanFileSize(newSize));
```suggestion
							oldFile.find('td.filesize').text(OC.Util.humanFileSize(newSize));
```

2020-02-07 16:35 UTC, skjnldsv commented on apps/files/js/filelist.js
> +							oldFile.find('td.filesize').text(OC.Util.OC.Util.humanFileSize(newSize));
```suggestion
							oldFile.find('td.filesize').text(OC.Util.humanFileSize(newSize));
```

2020-02-10 07:58 UTC, ChristophWurst commented
This removes ~100KB from each bundle, btw

![](https://i.kym-cdn.com/entries/icons/original/000/028/021/work.jpg)

2020-02-16 16:09 UTC, gary-kim commented
Needs a rebase. :smile:
![image](https://user-images.githubusercontent.com/47195730/74608138-9d1a4c00-5119-11ea-89db-992a25f27927.png)
**Continuous** integration?

2020-02-17 09:34 UTC, gary-kim commented
There seems to be a JSUnit failure, is that unrelated?
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 847 of 851 (42 FAILED) (skipped 4) (27.61 secs / 26.648 secs) 
```

2020-02-17 09:58 UTC, ChristophWurst commented
Whoopsie. A few tests are indeed failing.

2020-03-09 12:32 UTC, ChristophWurst commented
`escapeHTML` is still used in a few places :cry: 

But the rest should be fine.

2020-03-09 14:26 UTC, gary-kim approved these changes
Looks good to me

2020-03-09 14:36 UTC, merged