Log QueryBuilder queries
nextcloud/server pull request #1943
Opened 2016-10-28 09:35 UTC by nickvergessen

@LukasReschke @rullzer 

Fix #1676

2016-10-28 10:49 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		if (\OC::$server->getConfig()->getSystemValue('log_query', false)) {
Can't we inject that in \OC\DB\Connection::getQueryBuilder ?

2016-10-28 11:42 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		if (\OC::$server->getConfig()->getSystemValue('log_query', false)) {
The problem is, that config needs database, so we need to be careful, but let me try.

2016-10-29 07:46 UTC, LukasReschke commented
Tests failing now 🚀

2016-10-31 09:12 UTC, nickvergessen commented
> Tests failing now

Fixed now, seems like data providers are called before `setUp()`

2016-11-02 09:15 UTC, rullzer commented
LGTM

2016-11-02 19:29 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		if ($this->systemConfig->getValue('log_query', false)) {
Missing tests here. Will add…

2016-11-02 19:29 UTC, LukasReschke requested changes

2016-11-02 19:29 UTC, LukasReschke commented on lib/private/Security/CSRF/TokenStorage/SessionStorage.php
> +	public function setSession(ISession $session) {
Missing tests

2016-11-02 20:11 UTC, LukasReschke approved these changes

2016-11-02 20:11 UTC, LukasReschke commented
Added the missing tests.

2016-11-02 20:34 UTC, rullzer commented
YAY tests. :+1: stands

2016-11-02 20:51 UTC, merged