Change the route generation of AuthPublicShareController.php
nextcloud/server pull request #19478
Opened 2020-02-14 11:16 UTC by Tim-Obert

#19475
Signed-off-by: Tim Obert <tobert@w-commerce.de>

2020-02-14 12:41 UTC, nickvergessen commented on lib/public/AppFramework/AuthPublicShareController.php
> +		// $class = $this->camelCaseToLowerCaseUnderscored(substr($class, 0, strpos($class, 'Controller')));
So this is not used?

2020-02-14 12:57 UTC, nickvergessen requested changes

2020-02-14 12:57 UTC, nickvergessen commented on core/routes.php
> -		['name' => 'sharecontroller#showShare', 'url' => '/s/{token}', 'verb' => 'GET', 'app' => 'files_sharing'],
keep this old

2020-02-14 12:57 UTC, nickvergessen commented on lib/public/AppFramework/AuthPublicShareController.php
> +	private function camelCaseToLowerCaseUnderscored($string)
drop this

2020-02-14 12:57 UTC, nickvergessen commented on lib/public/AppFramework/AuthPublicShareController.php
> +		$class = (new \ReflectionClass($this))->getShortName();
replace with:
```php
		$class = (new \ReflectionClass($this))->getShortName();
		if ($this->appName === 'files_sharing') {
			$class = strtolower($class);
		} else if (substr($class, -10) === 'Controller') {
			$class = substr($class, 0, -10);
		}
```

2020-02-14 12:58 UTC, nickvergessen commented
And then use routes:
```
		['name' => 'DummyThing#showShare', 'url' => '/secret/{token}', 'verb' => 'GET'],
		['name' => 'DummyThing#showAuthenticate', 'url' => '/secret/{token}/authenticate/{redirect}', 'verb' => 'GET'],
		['name' => 'DummyThing#authenticate', 'url' => '/secret/{token}/authenticate/{redirect}', 'verb' => 'POST'],
```

2020-02-14 14:44 UTC, nickvergessen approved these changes

2020-02-19 09:55 UTC, blizzz commented
cc @Rello weren't you also doing things with this Controller?

2020-02-23 15:42 UTC, rullzer approved these changes

2020-02-23 15:42 UTC, rullzer commented on lib/public/AppFramework/AuthPublicShareController.php
> +			$class = strtolower($class);
right because we do nasty things in core.
Lets do this for now and at some poitn make sure that we fix those share routes.

2020-02-23 15:43 UTC, merged

2020-02-23 15:44 UTC, rullzer commented
Good stuff thanks for all the work @Tim-Obert

2020-02-23 15:44 UTC, rullzer commented
/backport to stable18

2020-02-23 15:44 UTC, rullzer commented
/backport to stable17