refactoring code to reduce cyclomatic complexity
nextcloud/server pull request #1950
Opened 2016-10-29 10:03 UTC by noodlesegg

2016-10-29 11:50 UTC, rullzer requested changes

2016-10-29 11:50 UTC, rullzer commented on lib/public/AppFramework/OCSController.php
> +		$response = new \OC\AppFramework\OCS\$version($data, $format);
This is not valid

2016-10-29 11:51 UTC, rullzer commented
@noodlesegg thanks for you contribution!
You need to sign off your commits see: https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin

2016-10-29 15:03 UTC, noodlesegg commented on lib/public/AppFramework/OCSController.php
> +		$response = new \OC\AppFramework\OCS\$version($data, $format);
oops will change it..

2016-11-02 07:50 UTC, rullzer approved these changes

2016-11-02 07:51 UTC, rullzer commented
@noodlesegg could you squash your commits and sign off?

2016-11-02 12:43 UTC, noodlesegg commented
hi @rullzer I'm sorry but how can I squash my commits and sign it off? thanks

2016-11-02 12:55 UTC, rullzer commented
1. `git reset --soft HEAD~2`
2. `git commit -s'
3. `git push -f`

At step 2 you'll have to enter the commit message.

2016-11-02 21:01 UTC, MorrisJobke commented
Beside the comment of @rullzer - 👍 from me as well :)

2016-11-07 07:32 UTC, rullzer commented
Replaced by #2032

2016-11-07 07:32 UTC, closed without merging