Fix #19479
nextcloud/server pull request #19541
Opened 2020-02-19 11:01 UTC by acs-ferreira

`flex-wrap` has no effect here.

![image](https://user-images.githubusercontent.com/12234510/74828502-81789680-530f-11ea-9275-8b584ef52529.png)

2020-02-24 10:27 UTC, skjnldsv commented
Hey! :)

Well, grid doesn't make sense here as you're not specifying any grid layout :/

2020-04-23 08:50 UTC, jancborchardt commented
> Well, grid doesn't make sense here as you're not specifying any grid layout :/

What would be a more correct way for @acsfer to fix this in that case? :) (It does seem to fix the issue.)

2020-04-23 08:52 UTC, jancborchardt submitted a review, later dismissed
Design-wise this looks good, except that title and subline are a bit pushed down – they should be centered vertically in the header.

But needs further code feedback from @skjnldsv about what would be the right way to implement this.

2020-04-23 09:00 UTC, acsfer commented
Can't dig into this in the next few days sorry. If @skjnldsv don't do, i'll do it next week.

2020-04-23 09:00 UTC, skjnldsv commented
> `flex-wrap` has no effect here.

it have, the parent have a display inline-flex :)

2020-04-23 09:14 UTC, acsfer commented
Quick display from Firefox dev tools.
![Uploading image.png…]()

2020-04-23 09:15 UTC, acsfer commented
Quick display from Firefox dev tools. ;)
![image](https://user-images.githubusercontent.com/12234510/80081721-9b269c00-8553-11ea-8393-10c24548ff9c.png)

2020-04-23 09:26 UTC, skjnldsv commented
> Quick display from Firefox dev tools. ;)

Ah right, confused myself! Thanks for the help :)
So I think it used to be a flex, because we had the sharee name stacked here as well ?

The whole header should be a flex and the shrinkable area shuld only be the file name then, this is the expected behavior I think :thinking:

2020-04-30 11:39 UTC, skjnldsv commented
Replaced by https://github.com/nextcloud/server/pull/20744

2020-04-30 11:39 UTC, skjnldsv requested changes
Replaced by https://github.com/nextcloud/server/pull/20744

2020-04-30 17:02 UTC, closed without merging