Added Exception catch and ignore for DBuser exists
nextcloud/server pull request #1958
Opened 2016-10-31 07:51 UTC by harry-7

In reference to #1428

2016-10-31 09:40 UTC, nickvergessen requested changes

2016-10-31 09:40 UTC, nickvergessen commented on lib/private/Setup/MySQL.php
> +		catch (\Exception $ignore){}
I guess we should log this, similar to the exceptions in `createDatabase`

2016-10-31 09:41 UTC, nickvergessen commented
Also as per IRC you are missing the sign-off on your commit:
https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

2016-11-02 11:36 UTC, nickvergessen commented
@MorrisJobke @LukasReschke

2016-11-02 11:36 UTC, nickvergessen approved these changes

2016-11-02 19:22 UTC, LukasReschke commented
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "storage" = ?, "path" = ?, "path_hash" = ? WHERE "fileid" = ?' with params [358, "files\/folder2\/folder1\/test.txt", "68142157b2aa9eb749de7b5dd59496cd", "2994"]:
382s
100
SQLSTATE[HY000]: General error: 13 database or disk is full
382s
102
```

/me looks at @MorrisJobke

2016-11-02 19:22 UTC, merged

2016-11-02 19:53 UTC, MorrisJobke commented
> /me looks at @MorrisJobke

Damn ... I will check this.

2016-11-02 20:01 UTC, MorrisJobke commented
> Damn ... I will check this.

Weird - I can't find anything suspicious.