Fix header gradient (by removing it)
nextcloud/server pull request #19669
Opened 2020-02-27 02:47 UTC by earboxer

Close #19040 as suggested by @juliushaertl

2020-02-27 09:39 UTC, mablr approved these changes

2020-03-02 07:56 UTC, juliusknorr requested changes
The plan was to keep the gradient for the default Nextcloud blue, but do not apply it if a custom theming color is set.

Adding a color check like https://github.com/nextcloud/server/blob/bf94acfee79fd0166864d3dae148b67acae3fac7/apps/theming/css/theming.scss#L15 to the main background fade mixin in https://github.com/nextcloud/server/blob/bf94acfee79fd0166864d3dae148b67acae3fac7/apps/theming/css/theming.scss#L11 should do the trick.

2020-03-02 22:12 UTC, kesselb approved these changes
Gradients are so 1990 ...

2020-03-03 14:54 UTC, jancborchardt requested changes
Agree with @juliushaertl, the gradient should only be removed when using a custom theming color.

And gradients being so 1990 makes them in fashion again now ;)
![image](https://user-images.githubusercontent.com/925062/75787330-22983000-5d99-11ea-8b70-b598c613c232.png)

2020-03-13 10:40 UTC, bpcurse commented
> Milestone Nextcloud 19

Will this be backported to 18?

2020-03-20 22:45 UTC, earboxer commented
I added the color check as described by @juliushaertl, but I haven't been able to test it...

What do we have to run on our servers to compile the SCSS? (and it's aware of the user-defined color at compile time?)

2020-04-02 18:38 UTC, rullzer commented
@juliushaertl @jancborchardt good to go now?

2020-04-02 19:04 UTC, juliusknorr requested changes

2020-04-02 19:04 UTC, juliushaertl commented on core/css/header.scss
> +		background-image: linear-gradient(40deg, $color-primary 0%, lighten($color-primary, 20%) 100%);
This breaks the default background image. That change should go to theming.scss. Maybe you can try something like this, to make sure that the gradient is properly set otherwise:

```diff
diff --git a/apps/theming/css/theming.scss b/apps/theming/css/theming.scss
index 0e9b922b27..c2a58dcc3d 100644
--- a/apps/theming/css/theming.scss
+++ b/apps/theming/css/theming.scss
@@ -8,7 +8,11 @@
 }
 
 @mixin faded-background {
-       background-image: linear-gradient(40deg, $color-primary 0%, lighten($color-primary, 20%) 100%);
+       @if ($color-primary == #0082C9) {
+               background-image: linear-gradient(40deg, $color-primary 0%, lighten($color-primary, 20%) 100%);
+       } @else {
+               background-color: $color-primary;
+       }
 }
 
 @mixin faded-background-image {
@@ -23,6 +27,10 @@
                @include faded-background;
                background-size: contain;
        }
+
+       @if ($color-primary != #0082C9) and ($has-custom-background == false) {
+               background-image: none;
+       }
 }
```

2020-04-02 19:05 UTC, juliushaertl commented
> What do we have to run on our servers to compile the SCSS? (and it's aware of the user-defined color at compile time?)

SCSS files should get reloaded automatically when debug mode is enabled. Otherwise you can always run `occ maintenance:repair` to remove all cached CSS.

2020-04-08 16:29 UTC, kesselb commented
Conflicts after https://github.com/nextcloud/server/pull/20343.

2020-06-03 07:20 UTC, juliushaertl commented
Thanks for getting this started. I've moved my suggestion to https://github.com/nextcloud/server/pull/21198 and did a bit of code cleanup in the same run as well so we can get this merged.

2020-06-03 07:20 UTC, closed without merging