Make sure we don't scan files that can not be accessed
nextcloud/server pull request #1972
Opened 2016-11-02 08:28 UTC by nickvergessen

### Steps
1. create a folder on the file system:
```
mkdir "data/admin/files/te
st"
```
2. Run `files:scan admin`
3. Try to delete the folder after realizing your problem

With this fix the file is not added on scanning.

@icewind1991 @MorrisJobke @LukasReschke 

Fix #1965

2016-11-02 14:00 UTC, MorrisJobke commented
```
1) OCA\Files_Sharing\Tests\External\ScannerTest::testScan
Your test case is not allowed to access the database.
2) OCA\Files_Sharing\Tests\External\ScannerTest::testScanFile
Your test case is not allowed to access the database.
```

2016-11-02 14:47 UTC, nickvergessen commented
I will fix that, once @icewind1991 confirmed this is the way to go.

2016-11-02 15:08 UTC, icewind1991 requested changes

2016-11-02 15:15 UTC, nickvergessen commented on lib/private/Files/Cache/Scanner.php
> +		if (!\OC::$server->getDatabaseConnection()->supports4ByteText()) {
That was exactly what I wondered aswell, but I think the cache is inside the view, so this looks shitty from dependency pov. But should we just move it to a separate helper or something?

2016-11-07 14:21 UTC, nickvergessen commented on lib/private/Files/Cache/Scanner.php
> +		if (!\OC::$server->getDatabaseConnection()->supports4ByteText()) {
@icewind1991 should we simply move all the checks from the View into `IStorage::verifyPath` and in the view then simply resolve the path to the storage and call the method?

2016-11-09 10:00 UTC, nickvergessen commented
@icewind1991 moved the validation from view to storage so it's in one place only

2016-11-18 20:38 UTC, MorrisJobke commented
Tested and works 👍 

@rullzer @icewind1991 Please review :)

2016-11-21 08:25 UTC, rullzer commented
Fine by me 👍 But lets have our fs guru have the last vote. Summoning @icewind1991

2016-11-22 11:04 UTC, icewind1991 commented
:+1:

2016-11-22 11:04 UTC, icewind1991 approved these changes

2016-11-22 11:55 UTC, merged

2016-12-02 00:36 UTC, MorrisJobke commented
@nickvergessen Could you open the backport PR? Thanks