pass the existing locks info when making locked exception with absolu…
nextcloud/server pull request #19746
Opened 2020-03-02 16:48 UTC by icewind1991

…te paths

Stops losing debug information

2020-03-03 19:23 UTC, rullzer approved these changes
Makes sense

2020-03-06 10:37 UTC, ChristophWurst requested changes

2020-03-06 10:37 UTC, ChristophWurst commented on apps/dav/lib/Connector/Sabre/File.php
> +					} catch (LockedException $ex) {
`$e` is still used on L270

2020-03-06 10:56 UTC, kesselb commented on apps/dav/lib/Connector/Sabre/File.php
> +					} catch (LockedException $ex) {
I run into that as well. If `$e` is renamed to `$ex` L270 will use the previous exception (from `changeLock` instead of the new one (from `acquireLock`). That's quite confusing ;)

2020-03-09 15:20 UTC, icewind1991 commented on apps/dav/lib/Connector/Sabre/File.php
> +					} catch (LockedException $ex) {
This is on purpose here, the `$ex` exception comes from the attempt to "repair" the original locking error, if the "repair" fails it's still the original locking error that was the cause, and thus the original exception should be forwarded

2020-03-09 16:41 UTC, ChristophWurst commented on apps/dav/lib/Connector/Sabre/File.php
> +					} catch (LockedException $ex) {
Got it. Fine by me then. Maybe add a comment next time :)

2020-03-09 16:42 UTC, ChristophWurst approved these changes

2020-03-09 18:31 UTC, merged