Take full width on public sharing files view
nextcloud/server pull request #19794
Opened 2020-03-05 15:13 UTC by skjnldsv

Spent an afternoon on this, this does the job, we better nuke files and move away to this legacy css code soon

### steps
1. share folder
2. disable download
3. see all fine

| Before | After |
|:---------:|:------:|
|![image](https://user-images.githubusercontent.com/14975046/75995071-2b554700-5efc-11ea-8546-e243315f38e3.png)|![image](https://user-images.githubusercontent.com/14975046/75995039-1ed0ee80-5efc-11ea-8ebc-0640b4782174.png)|

2020-03-05 15:14 UTC, skjnldsv commented
/backport to stable18

2020-03-05 15:27 UTC, georgehrke approved these changes
Code looks good

2020-03-05 15:29 UTC, ChristophWurst approved these changes
:elephant:

2020-03-05 17:02 UTC, juliusknorr requested changes
Still doesn't work for all sizes:

![Peek 2020-03-05 18-00](https://user-images.githubusercontent.com/3404133/76005386-3e234800-5f0b-11ea-873f-1b0d00969787.gif)

Besides that there is also an issue with the 3-dots menu if hide-download is not set, that is even the case in the logged in file list:

![Peek 2020-03-05 18-02](https://user-images.githubusercontent.com/3404133/76005535-73c83100-5f0b-11ea-8a39-211002d83842.gif)

2020-03-05 17:13 UTC, juliushaertl commented
This is actually the same root cause as the fix in https://github.com/nextcloud/server/pull/19440 has. So the other PR fixes the hide download list as well.

2020-03-06 07:02 UTC, closed without merging

2020-03-06 07:02 UTC, skjnldsv commented
Let me give #19440 some attention then