Add address book plugins
nextcloud/server pull request #19795
Opened 2020-03-05 15:39 UTC by ChristophWurst

Somehow Github refused to reopen https://github.com/nextcloud/server/pull/19680, thus a new PR.

Same same as https://github.com/nextcloud/server/pull/19196 but different.

- [x] Pluggable address books
- [x] Load the address book for the user

Tested with https://github.com/nextcloud/server/pull/19075

2020-03-09 11:50 UTC, juliushaertl commented on apps/dav/lib/CardDAV/AddressBookRoot.php
> -		$this->l10n = \OC::$server->getL10N('dav');
Has an unused use and private property now.

2020-03-09 12:13 UTC, ChristophWurst commented on apps/dav/lib/CardDAV/AddressBookRoot.php
> -		$this->l10n = \OC::$server->getL10N('dav');
Fixed :)

2020-03-09 12:17 UTC, juliusknorr approved these changes
Looks good otherwise and seems to do the trick with the parts already available in https://github.com/nextcloud/server/pull/19075

2020-03-09 12:25 UTC, georgehrke requested changes
`UserAddressbooks` should check for reserved names when creating a new collection.
Similar to here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php#L76L84

2020-03-09 12:37 UTC, ChristophWurst commented
Thanks @georgehrke. Added the check :)

2020-03-09 15:04 UTC, rullzer approved these changes
Didn't do extensive testing. But code looks sane

2020-03-09 15:47 UTC, ChristophWurst commented
@georgehrke ok to merge this? :)

2020-03-09 15:52 UTC, georgehrke approved these changes
👍

2020-03-09 16:32 UTC, merged

2020-03-26 22:05 UTC, blizzz commented
@ChristophWurst  the extension of info.xml has to be defined in https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/info.xsd

2020-03-29 15:05 UTC, juliushaertl commented
And https://github.com/nextcloud/server/blob/master/resources/app-info-shipped.xsd / https://github.com/nextcloud/server/blob/master/resources/app-info.xsd :wink:

2020-03-30 09:06 UTC, ChristophWurst commented
:+1: I'll also add it for https://github.com/nextcloud/server/pull/19196 while at it