[POC] Event for failed login attempts
nextcloud/server pull request #19845
Opened 2020-03-07 15:19 UTC by rullzer

First start of a failed login event.
So we can act on it in other parts.

2020-03-09 08:07 UTC, ChristophWurst requested changes
New class needs `@since` annotations, but the rest seems fine :)

2020-03-10 15:33 UTC, blizzz requested changes
terms are being mixed up here :( 

Please use
* loginName, when it is about the value that is entered as name in the login form
* userId, or short uid, when the value exactly and without doubt matches the user id of the user
* username, rather don't

2020-03-30 14:30 UTC, rullzer commented
/compile amend /

2020-03-30 14:36 UTC, blizzz commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			$this->dispatcher->dispatchTyped(new LoginFailedEvent($uid));
possible doing a userExists checks against the uid, and only emitting it against existing users? of course it could be done by the consumer, too.

2020-03-30 14:36 UTC, blizzz commented on lib/private/User/Session.php
> +				$this->dispatcher->dispatchTyped(new LoginFailedEvent($user));
see above

2020-03-30 14:37 UTC, blizzz commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			$this->dispatcher->dispatchTyped(new LoginFailedEvent($uid));
I think it's to good to be clear in what is actually passed in the arguments, to avoid surprises.

2020-03-30 14:38 UTC, rullzer commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			$this->dispatcher->dispatchTyped(new LoginFailedEvent($uid));
Problem is that this still doesn't give the right UID in all cases. Normal backend is case insensitive etc.

I mean in the password policy app we could always do a 'userExist' check.

2020-03-30 14:57 UTC, blizzz commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			$this->dispatcher->dispatchTyped(new LoginFailedEvent($uid));
It should give the correct uid when the user exists, and leave it unchanged otherwise. But let me double check. 

There might be a use case if you try to make fail2ban thing on NC level, when you don't care about an existing user behind a login name (just, it's on the wrong level, you have fail2ban already). But then, we should leave the `preLoginNameUsedAsUserName` to the consumer, too, as it is not necessary for this hypothetic use case. 

So I'd say, when we start with  `preLoginNameUsedAsUserName`, let's do the full thing and only emit when an existing user account is behind that, instead of a half hearted approach.

2020-03-30 15:12 UTC, blizzz commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			$this->dispatcher->dispatchTyped(new LoginFailedEvent($uid));
> Normal backend is case insensitive etc.

It returns the uid in the correct from

2020-03-30 15:22 UTC, blizzz approved these changes

2020-03-30 17:17 UTC, ChristophWurst approved these changes
Looks good!

2020-03-30 17:17 UTC, ChristophWurst commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			if($this->userManager->userExists($uid)) {
at some point we might also want the event for unknown uids, but fine for now

2020-03-30 19:51 UTC, blizzz commented on lib/private/Authentication/Login/LoggedInCheckCommand.php
> +			if($this->userManager->userExists($uid)) {
my rationale was https://github.com/nextcloud/server/pull/19845#discussion_r400259458  if a use case pops up, sure, let's add or adept at that time.

2020-03-31 07:08 UTC, ChristophWurst commented
![Bildschirmfoto von 2020-03-31 09-08-22](https://user-images.githubusercontent.com/1374172/77997152-32bb1500-732f-11ea-84e5-3b81d114e4f5.png)

2020-03-31 11:22 UTC, blizzz approved these changes

2020-03-31 20:17 UTC, merged