Migrate from @babel/polyfill to core-js@3
nextcloud/server pull request #19872
Opened 2020-03-10 09:00 UTC by ChristophWurst

Ref :bookmark: https://babeljs.io/blog/2019/03/19/7.4.0

Supersedes https://github.com/nextcloud/server/pull/19842

2020-03-10 09:02 UTC, georgehrke approved these changes

2020-03-10 09:03 UTC, ChristophWurst commented
FYI the `main.js` bundle shrinks from 1328kB to 1240kB = ~7% :rocket:

2020-03-10 09:10 UTC, juliusknorr requested changes
Does not work in IE11 anymore:

![image](https://user-images.githubusercontent.com/3404133/76296934-47b80180-62b7-11ea-99b7-4ea846340ac7.png)

Mainly it seems that `Object.assign` is no longer properly polyfilled

2020-03-10 09:13 UTC, ChristophWurst commented
> Does not work in IE11 anymore

Huh. Is it because with corejs only the bundled files are polyfilled and anything external isn't? :cry:

2020-03-10 09:14 UTC, juliushaertl commented
Probably, I just checked the login page and it was an Object.assign in backbone.js that caused that.

2020-03-10 09:16 UTC, ChristophWurst commented
Okay. Then we can either
* Close this PR and proceed with what we had before
* Change this PR to still ship the full-fledged polyfill but also just inline the corejs usage for bundled files

2020-03-10 09:19 UTC, juliushaertl commented
Not sure if that fixes it but maybe we could also make sure that the affected node modules are transpiled as well? https://github.com/nextcloud/server/blob/master/webpack.common.js#L86

2020-03-10 09:21 UTC, ChristophWurst commented
It will help with the packages where we know that transpilation is requried. But anything else might break. I think the safe path is to still ship a polyfill.

On that note. We might want to document that apps shouldn't rely on it, so we can phase that out?

2020-03-10 09:37 UTC, skjnldsv commented
You also need other stuff to replace polyfill:

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

2020-03-10 13:10 UTC, ChristophWurst commented
> FYI the `main.js` bundle shrinks from 1328kB to 1240kB = ~7% rocket

Now we're at 1356kB :rocket_crashing:

2020-03-10 13:22 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry

> This option enables a new plugin that replaces the import "core-js/stable"; and import "regenerator-runtime/runtime" statements (or require("corejs") and require("regenerator-runtime/runtime")) with individual requires to different core-js entry points based on environment.

2020-03-10 13:24 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
I think it either means:
- Don't use import core-js
- Or use it and it will be edited to fit your usage

In case of the second, having this into the main.js doesn't make sense as this is a global js file, no? It would make sense to have this into each entry point? :thinking:

2020-03-11 08:49 UTC, ChristophWurst commented on babel.config.js
> +				useBuiltIns: "entry",
The main.js is loaded on *every page*. If that loads the polyfill, everything else should be fine, right?

2020-03-11 08:51 UTC, ChristophWurst commented on babel.config.js
> +				useBuiltIns: "entry",
We want the "individual requires to different core-js entry points based on environment" but also the polyfill for extraneous files

2020-03-11 08:59 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
I don't see how wen can have one entry point that sum up all the other polyfills. Seems counter intuitive to me. :)

2020-03-11 09:33 UTC, ChristophWurst commented on babel.config.js
> +				useBuiltIns: "entry",
Why? That is what we do right now. The Babel polyfill is loaded in main.js, patches all the globals for the missing APIs and all the scripts work afterwards

2020-03-11 09:50 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
Yes, but the goal of `usage` is to only load what is needed.
Therefore it defeat the purpose of a single polyfill including stuff that your current app might not need :)

But if you do it by entry point, each loaded app will only include the polyfill that it needs

2020-03-11 09:51 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
Before it was just adding all the polyfill, so it didn't matter :)

2020-03-24 14:13 UTC, ChristophWurst commented on babel.config.js
> +				useBuiltIns: "entry",
Yeah, but we need *all* the polyfills, not just what the bundles need. Can we even achieve that with core-js?

2020-03-24 14:17 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
Sorry, I confused myself.
Yes, with useBuiltIns: "usage" you can have ondemand import.

2020-03-24 14:49 UTC, ChristophWurst commented on babel.config.js
> +				useBuiltIns: "entry",
But that just means that the bundle will import them, right? It won't import all of core-js as I understand.

2020-03-25 09:17 UTC, skjnldsv commented on babel.config.js
> +				useBuiltIns: "entry",
Yes! Therefore we can have this as is I guess :)
useBuiltIns false/entry will import all the polyfills anyway

2020-03-26 12:30 UTC, skjnldsv approved these changes

2020-03-26 12:31 UTC, ChristophWurst commented
> Mainly it seems that `Object.assign` is no longer properly polyfilled

Tested again with IE11, Object.assign was there :)

2020-03-26 14:52 UTC, gary-kim approved these changes
LGTM. I am a bit worried about [this](https://github.com/zloirock/core-js/issues/767) but it looks like other people have write access so it should still be supported.

EDIT: TLDR, the author and primary maintainer of the project has been sentenced to 1.5 years in prison.

2020-03-26 15:33 UTC, ChristophWurst commented
> LGTM. I am a bit worried about [this](https://github.com/zloirock/core-js/issues/767) but it looks like other people have write access so it should still be supported.

Ouch. Didn't know about that. As the polyfill is deprecated this is our best choice right now. If alternatives evolve, we should be able to migrate to them.

2020-03-26 15:42 UTC, merged