Improved vcard photo handling
nextcloud/server pull request #19901
Opened 2020-03-12 10:30 UTC by nickvergessen

2020-03-12 10:54 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				&& strpos($line, 'PHOTO:data:image/') !== 0) {
should we even limit it to the types in https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/apps/dav/lib/CardDAV/PhotoCache.php#L43-L48

2020-03-12 11:24 UTC, georgehrke requested changes

2020-03-12 11:24 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				&& strpos($line, 'PHOTO:data:image/') !== 0) {
@skjnldsv ^

It's missing svg though

2020-03-12 11:24 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$contact['carddata'] = $this->readBlob($contact['carddata']);
If you remove the Photo here, the etag will change, because it's just an md5 of the data.

2020-03-12 12:11 UTC, skjnldsv commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				&& strpos($line, 'PHOTO:data:image/') !== 0) {
Well, no, svg are cool to have

2020-03-12 15:49 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$contact['carddata'] = $this->readBlob($contact['carddata']);
Which is totally fine as it will make the recipient update the data too :)

2020-04-01 11:32 UTC, rullzer approved these changes
Looks good.
:elephant:

2020-04-01 11:36 UTC, skjnldsv approved these changes

2020-04-01 12:07 UTC, rullzer commented
CI says nope

2020-04-02 09:46 UTC, nickvergessen commented
@georgehrke final +1?

2020-04-02 09:52 UTC, georgehrke requested changes

2020-04-02 09:52 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +		$cardDataArray = explode("\r\n", $cardData);
Using explode instead of VCardReader is a bit hacky, but for the use-case it shouldn't be a problem

2020-04-02 09:52 UTC, georgehrke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$contact['carddata'] = $this->readBlob($contact['carddata']);
Yes, but you set the etag in the previous line, so the etag is not updated although the data changed.

2020-04-14 18:37 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$contact['carddata'] = $this->readBlob($contact['carddata']);
So, what to do? generate a new etag?

2020-04-14 20:00 UTC, rullzer commented
sooooo?

2020-04-15 12:16 UTC, nickvergessen commented
I'm currently unsure about @georgehrke s comments.
Should we generate a new random etag?

2020-04-17 09:40 UTC, rullzer commented
Good to go now?

2020-04-17 09:41 UTC, georgehrke commented
👍 from my side

2020-04-17 09:43 UTC, merged