Hide card for apps store if disabled
nextcloud/server pull request #19968
Opened 2020-03-15 16:38 UTC by kesselb

How to test:

1. Login as admin
2. Go to Settings -> Admin -> Flow
3. See "More flows" card
4. `occ config:system:set appstoreenabled --value false --type boolean`
5. Don't see "More flows" card anymore

2020-03-15 16:42 UTC, kesselb commented on apps/workflowengine/src/components/Workflow.vue
> +			scope: this.$store.state.scope,
I changed that from `loadState` to `this.$store` because scope is already in the store. Let me know if there are reasons to use `loadState` here instead of the store.

2020-03-15 22:09 UTC, blizzz requested changes

2020-03-15 22:09 UTC, blizzz commented on apps/workflowengine/lib/Settings/ASettings.php
> +			$this->config->getSystemValueBool('appstoreenabled')
```suggestion
			$this->config->getSystemValueBool('appstoreenabled', true)
```

to  honour the default. Otherwise the card won't be shown despite the appstore being enabled.

2020-03-15 22:37 UTC, kesselb commented on apps/workflowengine/lib/Settings/ASettings.php
> +			$this->config->getSystemValueBool('appstoreenabled')
Good point 👍

2020-03-16 09:34 UTC, juliushaertl commented on apps/workflowengine/src/components/Workflow.vue
> +			scope: this.$store.state.scope,
Yes, that is fine. Just a general note, setting the value in data like this is not reactive, so if the store changes the value the component will not be updated, which can be fixed by moving them to a computed property: https://github.com/nextcloud/server/blob/enh/noid/hide-apps-store-if-disabled/apps/workflowengine/src/components/Workflow.vue#L76-L78

But fine in this case, since the values are coming from the initial state service anyways and are not changing.

2020-03-16 09:34 UTC, juliusknorr approved these changes

2020-03-16 09:38 UTC, kesselb commented on apps/workflowengine/src/components/Workflow.vue
> +			scope: this.$store.state.scope,
All right. I will change it. JS needs to be recompiled anyway.

2020-03-16 09:44 UTC, blizzz approved these changes

2020-03-16 09:46 UTC, blizzz commented
/compile amend  /apps/workflowengine/

2020-03-16 09:56 UTC, kesselb commented
/compile amend /apps/workflowengine/

2020-03-16 10:07 UTC, kesselb commented
/compile amend /

2020-03-16 11:10 UTC, gary-kim commented
Needs a rebase

2020-03-16 11:30 UTC, kesselb commented
/compile amend /apps/workflowengine/

2020-03-16 12:22 UTC, kesselb commented
Finally ;)

2020-03-16 14:40 UTC, gary-kim approved these changes
LGTM

2020-03-16 21:11 UTC, merged