fix "Use this address..." string?
nextcloud/server pull request #20074
Opened 2020-03-21 01:35 UTC by szaimen

fix https://github.com/nextcloud/server/issues/20054?

I just wanted to bring this change in to start the discussion on this topic.
Any thoughts on this?

2020-03-21 07:19 UTC, rullzer commented on apps/files/templates/appnavigation.php
> +			<em><?php print_unescaped($l->t('<a href="%s" target="_blank" rel="noreferrer noopener">Use this address to access your Files via WebDAV</a>', array(link_to_docs('user-webdav')))); ?></em>
As long as we are fixing things. Could you move out the `a` parts of the translation?

2020-03-21 12:51 UTC, szaimen commented on apps/files/templates/appnavigation.php
> +			<em><?php print_unescaped($l->t('<a href="%s" target="_blank" rel="noreferrer noopener">Use this address to access your Files via WebDAV</a>', array(link_to_docs('user-webdav')))); ?></em>
@rullzer Do you mean something like this?
```suggestion
			<em><?php print_unescaped(<a href="%s" target="_blank" rel="noreferrer noopener">, $l->t('Use this address to access your Files via WebDAV'), </a>, array(link_to_docs('user-webdav'))); ?></em>
```

2020-03-22 13:34 UTC, rullzer commented on apps/files/templates/appnavigation.php
> +			<em><?php print_unescaped($l->t('<a href="%s" target="_blank" rel="noreferrer noopener">Use this address to access your Files via WebDAV</a>', array(link_to_docs('user-webdav')))); ?></em>
Yes. No need to have our translaters translate the link stuff :)

2020-03-22 17:35 UTC, szaimen commented on apps/files/templates/appnavigation.php
> +			<em><?php print_unescaped($l->t('<a href="%s" target="_blank" rel="noreferrer noopener">Use this address to access your Files via WebDAV</a>', array(link_to_docs('user-webdav')))); ?></em>
okay, this is done 👍

2020-03-26 16:12 UTC, kesselb requested changes
Do not work like that.

`print_unescaped` expects a string. Right now a string, string and array are passed to this method. You are probably looking for something like:

 `print_unescaped('<a href="' . link_to_docs('user-webdav') . '" target="_blank" rel="noreferrer noopener">' . $l->t('Use this address to access your Files via WebDAV') . '</a>')`.

Luckily we can simplify that some more. That actual purpose of print_unescaped is to echo strings from a untrusted source (like transifex) unescaped. As we split markup and text now we don't need print_unescaped anymore:

`<em><a href="<?php echo link_to_docs('user-webdav') ?>" target="_blank" rel="noreferrer noopener"><?php p($l->t('Use this address to access your Files via WebDAV')) ?> ↗</a></em>`

2020-03-26 16:26 UTC, szaimen commented
@kesselb thanks for the advice!
Would you mind to create a PR with that? 
I initially only wanted to put a bit focus on that special part of the code with my PR...

2020-03-26 16:28 UTC, kesselb commented
Feel free to take the code and submit a pr.

2020-03-26 16:38 UTC, szaimen commented
Thanks, I'll make a new one.

2020-03-26 16:38 UTC, closed without merging

2020-03-26 16:49 UTC, szaimen commented
superseded by #20186