Allow some apps to have root URLs in their own routing file
nextcloud/server pull request #20114
Opened 2020-03-23 15:47 UTC by nickvergessen

Follow up to prevent #20038  from spreading

2020-03-23 15:49 UTC, nickvergessen commented on core/routes.php
> -		['name' => 'pagecontroller#authenticatePassword', 'url' => '/call/{token}', 'verb' => 'POST', 'app' => 'spreed'],
Those are now in https://github.com/nextcloud/spreed/pull/3134

All other apps are in this PR

2020-03-23 15:49 UTC, nickvergessen commented on lib/private/AppFramework/Routing/RouteConfig.php
> -			$name = $ocsRoute['name'];
Best review this file on https://github.com/nextcloud/server/pull/20114/files?w=1

2020-03-24 20:15 UTC, ChristophWurst approved these changes

2020-04-09 14:34 UTC, rullzer approved these changes

2020-04-11 07:27 UTC, skjnldsv commented
Rebased

2020-04-11 07:33 UTC, skjnldsv commented
Lots of failures

2020-04-16 18:41 UTC, danxuliu requested changes
PHP CS is not happy.

Some integration and acceptance tests failures are legit, and all seem to be caused by `Unable to generate a URL for the named route \"cloud_federation_api.RequestHandler.addShare\" as such route does not exist.`

2020-04-17 07:58 UTC, nickvergessen commented
> PHP CS is not happy.

Should be fixed by a last rebase as it's not caused by this PR.

2020-04-21 12:45 UTC, nickvergessen commented
SHould be good to go now?
Not sure what the acceptance tests complain about. And the failing integration tests are caused by #16035

2020-04-21 14:00 UTC, rullzer commented
> SHould be good to go now?
> Not sure what the acceptance tests complain about. And the failing integration tests are caused by #16035

Lets do this and we fix stuff if it does boom

2020-04-21 14:00 UTC, merged

2020-04-21 18:38 UTC, danxuliu commented
> Not sure what the acceptance tests complain about

The _app-comments_ can be ignored, they are caused by a regression in the sidebar. The others are legit; for some reason with this pull request the Apps app and the Users app show a blank page (and in [8f650fe^](https://github.com/nextcloud/server/commit/613f0f2c0c2f07ad084a64f85debe9f6845b78f2) they work fine).

2020-04-21 20:14 UTC, rullzer commented
> > Not sure what the acceptance tests complain about
> 
> The _app-comments_ can be ignored, they are caused by a regression in the sidebar. The others are legit; for some reason with this pull request the Apps app and the Users app show a blank page (and in [8f650fe^](https://github.com/nextcloud/server/commit/613f0f2c0c2f07ad084a64f85debe9f6845b78f2) they work fine).

which apps?

2020-04-21 20:42 UTC, rullzer commented
aah the apps and user page
mmm indeed.... so I ahve a crude fix ut this seems to break js...