Bugfix - Prevent PHP Warning for count on null on LDAP
nextcloud/server pull request #20123
Opened 2020-03-23 20:50 UTC by lippl

When initializing the `$pwdGraceUseTimeCount` it is not checked if the `$pwdGraceUseTime` may be `null`, when pwdgraceusetime attribute my be not defined in LDAP. Starting PHP 7.2 count throws a warning when called on `null`. 
`[PHP 7.2] count(): Parameter must be an array or an object that implements Countable`
As the ldap search also only returns arrays, `[]` is used instead of `null`.
The redundant check for the variable in the if query is also removed, as only arryas, which implement countable, can be passed.
Additionally this is harmonized for all other LDAP attributes querried within the `handlePasswordExpiry` function.

2020-03-24 10:46 UTC, georgehrke commented
@lippl Is this related to any existing issue?

2020-03-24 10:47 UTC, georgehrke commented
@lippl Can you please add unit tests for it? Thx!

2020-03-24 14:45 UTC, blizzz approved these changes

2020-03-24 14:46 UTC, blizzz commented
@lippl looks good from my point of view, just perhaps you can stash the commits into one?

2020-03-24 19:24 UTC, nickvergessen requested changes
If you only count to see you have more than 0 items, use `!empty()`

2020-03-24 19:24 UTC, nickvergessen commented on apps/user_ldap/lib/User/User.php
> +					&& (count($pwdExpireWarning) > 0)) {
```suggestion
			if(!empty($pwdChangedTime)) {
				if(!empty($pwdMaxAge)
					&& !empty($pwdExpireWarning)) {
```

2020-03-24 19:24 UTC, nickvergessen commented on apps/user_ldap/lib/User/User.php
> +			if((count($pwdReset) > 0) && $pwdReset[0] === 'TRUE') { //user must change his password
```suggestion
			if (!empty($pwdReset) && $pwdReset[0] === 'TRUE') { //user must change his password
```

2020-03-24 19:24 UTC, nickvergessen commented on apps/user_ldap/lib/User/User.php
> +				if((count($pwdGraceAuthNLimit) > 0)
```suggestion
			if ($pwdGraceUseTimeCount > 0) { //was this a grace login?
				if (!empty($pwdGraceAuthNLimit))
```

2020-03-25 17:20 UTC, lippl commented
> @lippl Is this related to any existing issue?

I have not found any open issue for this yet but rather decided to go straight for a fix

> If you only count to see you have more than 0 items, use `!empty()`

@nickvergessen Thanks for the hint! I applied your suggested changes and also extended this to the initial  `count($pwdGraceUseTime)` for a variable by removing the variable, checking for `!empty` first and only later in case it is true use the `count()`, as this should be rare cases.
As you already started some pretty printing I also removed some unnecessary blank spaces as well.

> @lippl looks good from my point of view, just perhaps you can stash the commits into one?

If that is all fine with you, I would squash everything into one commit.

2020-03-25 20:51 UTC, blizzz approved these changes

2020-03-25 20:52 UTC, blizzz commented
> If that is all fine with you, I would squash everything into one commit.

fine with me :)

2020-03-25 21:05 UTC, juliusknorr approved these changes

2020-03-25 21:51 UTC, nickvergessen approved these changes

2020-03-26 10:28 UTC, blizzz commented
Thanks @lippl

2020-03-26 10:28 UTC, merged

2020-03-26 10:28 UTC, blizzz commented
/backport to stable18

2020-03-26 10:28 UTC, blizzz commented
/backport to stable17

2020-03-26 10:29 UTC, blizzz commented
/backport to stable16