Make remote checking more generic
nextcloud/server pull request #20138
Opened 2020-03-24 13:21 UTC by nickvergessen

2020-03-24 13:36 UTC, georgehrke requested changes

2020-03-24 13:36 UTC, georgehrke commented on apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php
> +					'allow_local_address' => $allowLocalAccess !== 'yes',
Shouldn't this be saying `$allowLocalAccess === 'yes'`?

2020-03-24 19:46 UTC, rullzer approved these changes
Didn't test in dept but looks good.

2020-04-01 12:07 UTC, georgehrke approved these changes

2020-04-10 07:04 UTC, rullzer commented
CI is not happy

2020-04-15 10:48 UTC, merged