Add default titles for titleless events in invitations
nextcloud/server pull request #20188
Opened 2020-03-26 17:33 UTC by tcitworld

Closes #19662

2020-03-26 17:36 UTC, georgehrke requested changes

2020-03-26 17:36 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		$summary = ((string) $summary !== '') ? (string) $summary : $l10n->t('Event without name');
In the calendar app, we just call it “Untitled event”

2020-03-26 18:10 UTC, georgehrke approved these changes

2020-04-03 10:13 UTC, ChristophWurst submitted a review, later dismissed
Your indentation seems off, the rest looks good :)

2020-04-03 12:08 UTC, ChristophWurst approved these changes

2020-04-07 09:22 UTC, merged