Provide the proper language to the mailer
nextcloud/server pull request #20246
Opened 2020-03-31 12:06 UTC by rullzer

Else we can't properly translate the footer in the recipients e-mail language.

1. Create 2 users (userA and userB)
2. set language of userB to something other than English
3. share a file from userA to user B

before:
* footer in language of userA

After:
* footer in language of userB

2020-03-31 12:08 UTC, ChristophWurst approved these changes
Of course :see_no_evil:

2020-03-31 12:11 UTC, nickvergessen requested changes
Looks good in general, but the addFooter call should be fixed

2020-03-31 12:11 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> +			$emailTemplate->addFooter('', $l->getLanguageCode());
debugging? addFooter has only 1 parameter

2020-03-31 12:11 UTC, nickvergessen commented on lib/private/legacy/util.php
> +		$logger->debug('Final skeleton folder:' . $skeletonDirectory, ['app' => 'files_skeleton']);
:( so many logs for every user?

2020-03-31 12:17 UTC, rullzer commented on lib/private/legacy/util.php
> +		$logger->debug('Final skeleton folder:' . $skeletonDirectory, ['app' => 'files_skeleton']);
Ah shit no. this was for smething else

2020-03-31 12:17 UTC, rullzer commented on lib/private/Share20/Manager.php
> +			$emailTemplate->addFooter('', $l->getLanguageCode());
No I added this. I need to know the language code.

2020-03-31 12:18 UTC, rullzer commented on lib/private/Share20/Manager.php
> +			$emailTemplate->addFooter('', $l->getLanguageCode());
ah let me fix the interface

2020-03-31 16:27 UTC, juliusknorr approved these changes

2020-04-01 06:48 UTC, georgehrke approved these changes

2020-04-01 15:05 UTC, nickvergessen approved these changes

2020-04-01 15:07 UTC, nickvergessen commented
> There were 26 errors:
> ---
> 1) Test\Mail\EMailTemplateTest::testEMailTemplateCustomFooter
>
> TypeError: Argument 3 passed to OC\Mail\EMailTemplate::__construct() must implement interface OCP\L10N\IFactory, instance of Mock_IL10N_58c1d8ad given, called in /drone/src/tests/lib/Mail/EMailTemplateTest.php on line 54

2020-04-15 12:18 UTC, nickvergessen commented
>  Lint / php-cs check (pull_request) 

failing

2020-04-16 06:53 UTC, nickvergessen commented on apps/theming/lib/ThemingDefaults.php
> +	public function getSlogan(string $lang = null) {
```suggestion
	public function getSlogan(?string $lang = null) {
```

2020-04-16 06:54 UTC, nickvergessen requested changes

2020-04-16 06:54 UTC, nickvergessen commented on lib/public/Defaults.php
> +	public function getSlogan(string $lang = null) {
```suggestion
	public function getSlogan(?string $lang = null) {
```

2020-04-16 06:54 UTC, nickvergessen commented on lib/public/Mail/IEMailTemplate.php
> +	public function addFooter(string $text = '', string $lang = null);
```suggestion
	public function addFooter(string $text = '', ?string $lang = null);
```

2020-04-16 08:06 UTC, rullzer commented
/backport to stable18

2020-04-16 08:06 UTC, rullzer commented
/backport to stable17

2020-04-16 08:06 UTC, merged

2020-04-28 06:42 UTC, kesselb commented
https://help.nextcloud.com/t/error-declaration-of-oca-theming-themingdefaults-getslogan/79514

As ThemingDefaults extend OC_Defaults changing the method signature requires more work.