Improve contributing docs
nextcloud/server pull request #20249
Opened 2020-03-31 13:53 UTC by ma12-co

I remember that setting up my dev env the first time following the current instruction has been a huge pain. There's might people that are able to start contributing but the dev env barrier is just too scary. 
This is aimed at lowering that barrier a bit. Thanks @skjnldsv  for showing me this!

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

2020-03-31 13:59 UTC, skjnldsv commented
I would actually prefer to update the main documentation :)

2020-03-31 14:01 UTC, ma12-co commented
> I would actually prefer to update the main documentation :)

Isn't this more fun for newcomers? With emojis and everything?

2020-03-31 14:03 UTC, skjnldsv commented
> Isn't this more fun for newcomers? With emojis and everything?

You can have this in the docs as well ^^

2020-03-31 14:07 UTC, ma12-co commented
awkay!

2020-03-31 14:29 UTC, CHRINIMUE commented
> I remember that setting up my dev env the first time following the current instructions has been a huge pain. There might people that are able to start contributing but the dev env barrier is just too scary.
> This is aimed at lowering that barrier a bit. Thanks @skjnldsv for showing me this!

True story! I did take me two days (yesterday and today) to get an basic understanding, of what components are used and how to get the env running. 🙈 
Some more basic documents would be really great.

2020-03-31 14:40 UTC, jancborchardt approved these changes
Yes we should improve the documentation as well, but a short intro like this is really important and sorely lacking. Great stuff :+1:

2020-03-31 14:43 UTC, ma12-co commented
So to merge or not to merge?

2020-03-31 14:46 UTC, skjnldsv requested changes
> Yes we should improve the documentation as well, but a short intro like this is really important and sorely lacking. Great stuff

Then maybe not replace the link to our dev documentation?
Let's improve the readme sure, but let's not lose the important more detailed dev docs

2020-03-31 14:47 UTC, ma12-co commented
> Let's improve the readme sure, but let's not lose the important more detailed dev docs

did you see that I linked them at the end of the file??
https://github.com/nextcloud/server/pull/20249/files#diff-936bdf0e69475cb93c1fb082c33b5a51R61

2020-03-31 14:48 UTC, skjnldsv approved these changes
Nope! Thanks!! :wink:

2020-03-31 15:03 UTC, ChristophWurst commented on DEVENV.md
> +sudo nano /etc/php/php.ini
this should be `vim`

Do we need to specify the command here? Both the editor as well as the php.ini location depend on the os and distribution :thinking:

2020-03-31 15:04 UTC, skjnldsv commented on DEVENV.md
> +sudo nano /etc/php/php.ini
We should add a new section; "How to exit vim" :grin:

2020-03-31 15:26 UTC, juliushaertl commented on DEVENV.md
> +sudo nano /etc/php/php.ini
The whole section is depending on the operating system, so I'm not sure this will help more that in will cause confusion if some steps are different.

2020-03-31 15:28 UTC, juliushaertl commented on README.md
> -1. 🚀 [Set up your local development environment](https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html)
I would generally prefer if we keep the original developer manual and either add the hint about the php internal webserver `php -S ...` to the top of that or give the main manual some polishing to make it easier to get started

2020-03-31 15:47 UTC, ma12-co commented
> I would generally prefer if we keep the original developer manual and either add the hint about the php internal webserver php -S ... to the top of that or give the main manual some polishing to make it easier to get started

This is between you @jancborchardt @juliushaertl, I'm ok with both ways!

2020-03-31 16:25 UTC, nickvergessen commented on README.md
> +1. 🚀 [Set up your local development environment](./DEVENV.md)
is this some supported thing or it can be in .github or some other folder?

2020-03-31 16:44 UTC, ma12-co commented on README.md
> +1. 🚀 [Set up your local development environment](./DEVENV.md)
Supported, test here https://github.com/nextcloud/server/tree/improve-contributing-docs

2020-03-31 16:52 UTC, gary-kim commented on DEVENV.md
> + php -S 0.0.0.0:80
You may want to add a note about the PHP dev server being single threaded. That does mean that some apps such as Onlyoffice simply don't work and others such as mail are very slow. Maybe just saying look at the note below if you run into issues with the single threaded dev server?

2020-03-31 17:13 UTC, juliushaertl commented on DEVENV.md
> + php -S 0.0.0.0:80
Also maybe pick a non-privileged port, so it works fine with regular user permissions :wink:

2020-03-31 17:23 UTC, gary-kim reviewed
Also, you're going to have to put the new `DEVENV.md` file here: https://github.com/nextcloud/server/blob/master/build/files-checker.php

That or, it might be more suitable for the file to be in the `contribute` directory?

I just finished up getting the exclude list completely correct for my own build script and now I have even more files to exclude...

2020-03-31 18:05 UTC, jancborchardt commented on README.md
> -1. 🚀 [Set up your local development environment](https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html)
I’m also fine with that :)

2020-03-31 18:06 UTC, jancborchardt commented on DEVENV.md
> +sudo nano /etc/php/php.ini
It’s always very helpful to have both the abstract instructions ("Edit php.ini file …") and the actual steps which work on e.g. Ubuntu. :) Otherwise you end up searching "where is php.ini" etc – this way it’s already solved for a lot of people. And people who use smth like Arch probably also know where the php.ini file is. ;)

2020-03-31 18:55 UTC, ChristophWurst commented on DEVENV.md
> +sudo nano /etc/php/php.ini
I was joking about `vim`, obviously.

But what about the mac users?

2020-04-01 06:06 UTC, ma12-co commented on DEVENV.md
> +sudo nano /etc/php/php.ini
What about winwows users?? xD

2020-04-01 06:07 UTC, ma12-co commented on DEVENV.md
> +sudo nano /etc/php/php.ini
Ok they have WSL now

2020-04-01 06:09 UTC, ma12-co commented on README.md
> -1. 🚀 [Set up your local development environment](https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html)
Ok then I'll take it out of here once we're finished discussing it!

2020-04-01 06:09 UTC, ma12-co commented on DEVENV.md
> +sudo nano /etc/php/php.ini
So what do you suggest?

2020-04-01 06:10 UTC, ma12-co commented
> I just finished up getting the exclude list completely correct for my own build script and now I have even more files to exclude...

It's going in the docs so I will just delete this branch and pr once we're finished discussing it

2020-04-01 06:11 UTC, ma12-co commented on DEVENV.md
> + php -S 0.0.0.0:80
8080?

2020-04-01 06:54 UTC, gary-kim commented on DEVENV.md
> + php -S 0.0.0.0:80
> 8080?

Fine by me. That's what I use: `localhost:8080`

2020-04-01 07:45 UTC, ChristophWurst commented on DEVENV.md
> +sudo nano /etc/php/php.ini
https://github.com/nextcloud/server/pull/20249#pullrequestreview-384808011

2021-03-17 17:15 UTC, PVince81 commented
I think we already have docs for getting started, so not sure if we should duplicate them here.
Maybe we could point at them in a more obvious way: https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html

2021-08-18 12:10 UTC, skjnldsv commented
/rebase

2021-08-18 14:49 UTC, juliushaertl commented
I guess we can close that already due to the discussion above and the comment by @marcoambrosini 

> It's going in the docs so I will just delete this branch and pr once we're finished discussing it

We can still discuss that in detail then in the documentation repo pull request.

2021-08-18 14:49 UTC, closed without merging