Fix/user menu not focused
nextcloud/server pull request #20291
Opened 2020-04-03 14:50 UTC by GretaD

2020-04-03 15:03 UTC, ChristophWurst commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						@click="$emit('toggleMenu')" />
doesn't this navigate? Have you tried `@click.prevent`?

2020-04-03 15:12 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						@click="$emit('toggleMenu')" />
i did try and nothing changed. What is happening now is that the icon-more is disappeared

2020-04-08 20:14 UTC, jancborchardt commented
@caturria is it possible for you to test this as it fixes the issue you reported at https://github.com/nextcloud/server/issues/19464 ? Thank you!

2020-04-08 20:16 UTC, jancborchardt commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						class="icon icon-more"
We only need the "icon-more" class, the single "icon" class is deprecated.

2020-04-09 08:15 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						class="icon icon-more"
Yes, I forgot to remove it. But did you test it, is it ok how it looks now?

2020-04-09 16:10 UTC, caturria commented
Hi,
@@GretaD I will spin up a test instance using your branch this afternoon and let you know by tomorrow.
Thank you very much for taking care of this.

> On Apr 9, 2020, at 4:16 AM, Greta <notifications@github.com> wrote:
> 
> 
> @GretaD commented on this pull request.
> 
> In apps/settings/src/components/UserList/UserRowSimple.vue <https://github.com/nextcloud/server/pull/20291#discussion_r406033454>:
> 
> > @@ -65,7 +65,11 @@
>  					</ActionButton>
>  				</Actions>
>  				<div class="userPopoverMenuWrapper">
> -					<div v-click-outside="hideMenu" class="icon-more" @click="$emit('toggleMenu')" />
> +					<button
> +						v-click-outside="hideMenu"
> +						class="icon icon-more"
> Yes, I forgot to remove it. But did you test it, is it ok how it looks now?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/nextcloud/server/pull/20291#discussion_r406033454>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEAWXZDFUHXLEDLWSXK24NLRLV74DANCNFSM4L4DUVHA>.
>

2020-04-14 17:07 UTC, caturria commented
Hi,
Sorry for the delay.
Apologies for asking, but if I could get a little guidance on upgrading a backup of my instance to this branch, it would be much appreciated.
I have followed all of the steps here:
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html
(Disabled as many apps as possible, backed up files and database, cloned branch and renamed to original Nextcloud directory, copied config/config.php from old to new, execute php occ upgrade).
It fails indicating that the Viewer app’s files have not been correctly replaced.
Viewer cannot be disabled, and apps/viewer does not exist in my old Nextcloud instance directory.
Kind regards,

Jordan.

> On Apr 9, 2020, at 4:16 AM, Greta <notifications@github.com> wrote:
> 
> 
> @GretaD commented on this pull request.
> 
> In apps/settings/src/components/UserList/UserRowSimple.vue <https://github.com/nextcloud/server/pull/20291#discussion_r406033454>:
> 
> > @@ -65,7 +65,11 @@
>  					</ActionButton>
>  				</Actions>
>  				<div class="userPopoverMenuWrapper">
> -					<div v-click-outside="hideMenu" class="icon-more" @click="$emit('toggleMenu')" />
> +					<button
> +						v-click-outside="hideMenu"
> +						class="icon icon-more"
> Yes, I forgot to remove it. But did you test it, is it ok how it looks now?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/nextcloud/server/pull/20291#discussion_r406033454>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEAWXZDFUHXLEDLWSXK24NLRLV74DANCNFSM4L4DUVHA>.
>

2020-04-15 08:58 UTC, GretaD commented
> (Disabled as many apps as possible, backed up files and database, cloned branch and renamed to original Nextcloud directory, copied config/config.php from old to new, execute php occ upgrade). It fails indicating that the Viewer app’s files have not been correctly replaced. Viewer cannot be disabled, and apps/viewer does not exist in my old Nextcloud instance directory. 

Hey Jordan, does the viewer app exist in your apps? If yes, maybe try to delete the app and clone it again: https://github.com/nextcloud/viewer.
It is ok to ask more questions if something else pops up. So dont worry :)

2020-04-15 16:57 UTC, caturria commented
Hi,
Alright; I got the update installed.
What’s working better:

The users list itself reads well now. Scrolling through the options using Control Option Right, here’s what I hear:
User Name

Display Name
Email

Groups

Quota

<Name of first user>

<Display name of first user>

<Email of first user>

0B, 181.2GB used

90% progress indicator

Edit user button.
Where problems remain:
1. The administration manual indicates that a mouse hover over a user would reveal an actions menu which offers choices such as to delete or disable a user. There still does not appear to be a way to access this using the keyboard/ screen reader.

2. The ‘Edit User’ button sometimes does not have its name spoken (sometimes it simply reads as ‘Button’). If it reads as ‘Button’, moving the screen reader cursor away from it and then back will cause it to read as ‘Edit user button’ the second time. Does the caption ‘Edit User’ appear dynamically in response to a mouse over event or something to that effect? If so it would need Aria attributes set in order to consistently speak its purpose.
3. The user editing screen is problematic in the following ways:
*Still has focus issues, on Mac Voiceover still experiences the broken record effect where it gets stuck in a loop between a few options instead of tracking the form elements from beginning to end;
*Does not  focus the correct options when edit user is pressed.
If I press ’Add a new User’, it correctly focuses the user name field and the form is for the most part accessible, however I cannot set custom quotas (the ’Select user quota’ field does not consistently grab input focus, and if I do get it to accept input and type 50GB for instance, the text disappears as soon as it loses focus. So I only have Default quota, Unlimited, 1GB, 5GB and 10GB to choose from, with no way of knowing which of those has actually been chosen.
In summary:
*I can read the users list correctly,
*I cannot delete or disable a user,
*I cannot edit a user without significant difficulty,
*I can create a new user, but cannot assign their quotas.
Thank you very much for your attention to this matter and for your work towards resolving it. Please stay safe and healthy.

Kind regards,

Jordan.

> On Apr 15, 2020, at 4:59 AM, Greta <notifications@github.com> wrote:
> 
> 
> (Disabled as many apps as possible, backed up files and database, cloned branch and renamed to original Nextcloud directory, copied config/config.php from old to new, execute php occ upgrade). It fails indicating that the Viewer app’s files have not been correctly replaced. Viewer cannot be disabled, and apps/viewer does not exist in my old Nextcloud instance directory.
> 
> Hey Jordan, does the viewer app exist in your apps? If yes, maybe try to delete the app and clone it again: https://github.com/nextcloud/viewer <https://github.com/nextcloud/viewer>.
> It is ok to ask more questions if something else pops up. So dont worry :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/nextcloud/server/pull/20291#issuecomment-613912139>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEAWXZACSR4IOE6G2W72XV3RMVZN5ANCNFSM4L4DUVHA>.
>

2020-04-20 10:36 UTC, GretaD commented
Thank you @caturria for the detailed explanation, thats very helpful. So i will move on and fix the action menu part, and we open another ticket for quota, ok?

2020-04-20 14:25 UTC, caturria commented
Hi,
Are you asking me to open another issue for the quota, or saying you’ve done it at your end?

Kind regards,

Jordan.


> On Apr 20, 2020, at 6:36 AM, Greta <notifications@github.com> wrote:
> 
> 
> Thank you @caturria <https://github.com/caturria> for the detailed explanation, thats very helpful. So i will move on and fix the action menu part, and we open another ticket for quota, ok?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/nextcloud/server/pull/20291#issuecomment-616462661>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEAWXZCWUF3GQ7KN6YALDLLRNQQTDANCNFSM4L4DUVHA>.
>

2020-04-20 19:42 UTC, GretaD commented
> Hi, Are you asking me to open another issue for the quota, or saying you’ve done it at your end? Kind regards, Jordan.

Yes please, you open it, i wanted to open it coping what you have wrote on the comment above, but didnt have the time, plus its better if you open it since you have all the details :)

2020-04-22 10:50 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						:aria-label="t('settings', 'Action menu')"
```suggestion
						:aria-label="t('settings', 'Toggle user actions menu')"
```

2020-04-22 10:51 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
```suggestion
					<div class="popovermenu" :class="{ 'open': openedMenu }" aria-expanded="openedMenu">
```

2020-04-22 11:18 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
`aria-expanded` is Boolean, so its true or false, and in our case is true, right? And not `openedMenu`

2020-04-22 11:29 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
Right, should be :aria-expanded="openedMenu"

2020-04-22 11:32 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
I have never seen in this form, also phpstorm complains "wrong attribute value"

2020-04-22 11:54 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
What do you mean You're never seen this form?
This is vue props binding?

2020-04-22 11:58 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
i mean i havent like this:  :aria-expanded="openedMenu", i have only seen it like this:  :aria-expanded="true/false"

2020-04-22 12:02 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  					<div class="popovermenu" :class="{ 'open': openedMenu }">
But openedMenu is a variable that is true or false :p
https://github.com/nextcloud/server/blob/3c76ebe13dacdd17585898e822077da8bc6c7e4c/apps/settings/src/components/UserList/UserRowSimple.vue#L119-L122

2020-04-22 12:03 UTC, GretaD commented
ready for review and testing @skjnldsv @jancborchardt

2020-04-22 12:12 UTC, skjnldsv commented
/compile amend /

2020-04-22 12:12 UTC, skjnldsv commented
Cannot review yet because we need #20591

2020-04-23 12:37 UTC, GretaD commented
> Cannot review yet because we need #20591

its merged, please check it out

2020-04-23 14:22 UTC, ChristophWurst commented
> its merged, please check it out

You have to update this branch :)

2020-04-23 16:43 UTC, GretaD commented
/compile amend /

2020-04-23 16:58 UTC, GretaD commented
i need to fix the border and background color before final review.` Icon more` has inherited the button characteristics 
 
![iconmore-buton](https://user-images.githubusercontent.com/12728974/80126834-cdf08480-8593-11ea-85ef-51858ed51886.png)

2020-04-23 19:42 UTC, GretaD commented
This is a bit tricky, somehow the button is focused but I cannot change the hover opacity of the` icon-more`. It looks like was a z-index problem because when focus via tab, the color is pale, but didnt work.
I added button:focus temporarily to test the tab focus, but have no idea how to add the opacity for icon button.
![ICON-MORE_OPEN](https://user-images.githubusercontent.com/12728974/80141836-7873a200-85aa-11ea-9c4f-36e150fd1a6b.png)

2020-04-24 06:55 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  	}
```suggestion
	.userPopoverMenuWrapper .button.icon-more {
		&:hover,
		&:focus,
		&:active {
			background-color: var(--color-background-dark)
		}
	}
	
```

2020-04-24 07:14 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  	}
Ah no, thi sis because the css is coming from /apps/settings/css/settings.scss:1679.

The apps/users page isn't using scoped styling in components. We weren't sure if it was the good call back then :)

2020-04-24 08:28 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  	}
It doesnt make any difference for what is missing
and what is missing is that when you tab, the 3 dot menu has no opacity, when you hover with mouse, it does(because of settings.scss:1679 as you said) :/

2020-04-24 10:08 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  	}
So change it in the settings.scss:1679 ? :stuck_out_tongue_winking_eye:

2020-04-24 11:50 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
>  	}
right :) ready for review then

2020-04-24 12:09 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +		}
```suggestion
```

2020-04-25 18:06 UTC, skjnldsv approved these changes

2020-04-25 18:07 UTC, skjnldsv requested changes

2020-04-25 18:07 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +		background-image: var(--icon-more-000);
Why do you need to specify the background?
Should be covered by the icon-more class already.

Seeing the changes in apps/settings/css/settings.scss, I don't see the need to have any rules in the vue style section here.
Border make sense though

2020-04-26 21:59 UTC, GretaD commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +		background-image: var(--icon-more-000);
background-color should be there because it inherits the button ` background-color: var(--color-background-dark);` and we dont want that.

the image is taken from settings, you're right.

2020-04-27 07:54 UTC, skjnldsv approved these changes

2020-04-30 07:20 UTC, ChristophWurst approved these changes

2020-04-30 07:20 UTC, ChristophWurst commented
/compile amend /

2020-04-30 07:20 UTC, ChristophWurst commented
ah this needs squashing and a rebase

2020-04-30 18:51 UTC, rullzer commented
/compile amend /

2020-05-01 01:11 UTC, jancborchardt approved these changes
Tested and works!

2020-05-01 06:42 UTC, merged