Add disable storage warning
nextcloud/server pull request #20465
Opened 2020-04-13 20:15 UTC by sbernhard

2020-04-14 00:32 UTC, gary-kim requested changes

2020-04-14 00:32 UTC, gary-kim commented on apps/files/js/files.js
> +      }
You need to use the initial state api to add this as an initial state on the server side with PHP then use JS on the client side to get that initial state here.
Sorry, I'm a bit pressed for time at the moment but I'll expand on this later.
Or @ChristophWurst could if you've got a moment?

2020-04-14 07:14 UTC, sbernhard commented on apps/files/js/files.js
> +      }
Oh, I'm very sorry. I guess, it was just to late so that I don't saw these two works js / php. 
I had a look at some other areas, in which the initialStateService is used. Actually, I think there is no initialStateService for the app 'files' currently. To which initialStateService should I add the setting? 

Is there a document how to rebuild the js assets on a server? (if this is possible) for actually testing a change in JS?

2020-04-14 13:49 UTC, gary-kim commented on apps/files/js/files.js
> +      }
> Is there a document how to rebuild the js assets on a server? (if this is possible) for actually testing a change in JS?

Just run `make` for a production build.
You can also run `make clean dev-setup` to set up your environment then run `make build-js` or `make watch-js` to build development versions.

2020-04-14 16:23 UTC, gary-kim commented on apps/files/js/files.js
> +      }
Take a look here for documentation on the InitialState API: https://docs.nextcloud.com/server/18/developer_manual/app/view/js.html?#loading-initial-state

Provide the initialState in this [file](https://github.com/nextcloud/server/blob/master/apps/files/lib/Controller/ViewController.php) and load it from the client side.

2020-04-19 21:28 UTC, sbernhard commented
I guess, this implementation should also work.

2020-04-20 08:03 UTC, skjnldsv commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
Really not sure about this :(
I really dislike having yet another config flag.

Can't we fix the external storage so that the returned quota is correct directly (meaning server know it is 'unknown' and display accordingly?)

2020-04-20 08:26 UTC, sbernhard commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
its not about fixing something with external storage. 
Sorry, I need to tell you the scenario. Its about this:

On a nextcloud installation we are only using group folders. A individual person shouldn't be able to upload files to nextcloud. Files can only be uploaded and shared in the group folders. 

Therefore the quota of the persons file storage is set to 0 by default. This prevents the user to upload files to the personal space. This works as expected but the storage warning notification is shown all the time, that the storage is full. Therefore, we want to disable this.

2020-04-20 08:34 UTC, skjnldsv commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
Ah right!
For me this is a very specific use case and should not be in nextcloud core.
Use the custom css app and hive the error message :)

2020-04-20 10:49 UTC, szaimen commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
@sbernhard what about mounting an empty local external storage folder as root for all users and making jt read only? Shouldn't that work, too?
I am doing this as well and it works without flaws.

2020-04-20 12:24 UTC, sbernhard commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
Thanks for the ideas @skjnldsv / @szaimen.

@szaimen can you please explain it more precisely:
- if you mount a external folder for all users, with read only, will it show a similar "no space available" message?
- do you set the quote for the users to "0", too?
-  the users will then see a "empty" folder, in which they can not store anything. Doesn't this confuse the users?

2020-04-20 12:37 UTC, szaimen commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
> * if you mount a external folder for all users, with read only, will it show a similar "no space available" message?

It has never shown this warning for me but since I am using this method but I haven't set the quota to 0.

> * do you set the quote for the users to "0", too?

No, you don't have to since your users will not be able to upload anything to their root directory.

> * the users will then see a "empty" folder, in which they can not store anything. Doesn't this confuse the users?

No, they will only see the groupfolders in their root directories.

2020-04-20 13:09 UTC, sbernhard commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
Nice. Looks like this is the solution I need. I will try it and let you know. maybe we should document this.

2020-04-20 13:57 UTC, sbernhard commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
@szaimen, what do you do with the "common" local strorage a nextcloud instance normaly has?

2020-04-20 14:11 UTC, skjnldsv requested changes
Blocking, see comments

2020-04-20 15:04 UTC, szaimen commented on config/config.sample.php
> +'files.disable.storage.warning' => false,
> @szaimen, what do you do with the "common" local storage a nextcloud instance normally has? I guess, it is referenced as the "datadirectory" in config.php.

I don't do anything with it since the user cannot access the files that are initially stored in it.

> Why is the local empty storage hidden and only the group folders are shown?

I think you should try it yourself and find out if it fits your needs :)

Just enable the files_external app, create a local mount, make it read only, name it as "/" and mount it to a testuser. Maybe also give access to the groupfolders. Just try it as if you would already do it this way in production...

2021-04-28 12:12 UTC, J0WI commented on config/config.sample.php
> + * to a storage warning. With this setting, the warning can be disabled.
IMHO a 'display storage warning' flag would be easier to understand than a double negation.

2021-08-18 12:13 UTC, skjnldsv commented on config/config.sample.php
> + * to a storage warning. With this setting, the warning can be disabled.
@sbernhard can you address this? :)

2023-10-17 19:54 UTC, closed without merging

2023-10-17 19:54 UTC, skjnldsv commented
Not relevant anymore with new Files UI