Issue #14447 - WIP - Attempt at adding CookieJar (for review)
nextcloud/server pull request #20508
Opened 2020-04-15 21:24 UTC by liamjack

@nickvergessen @rullzer 

Adds a `newCookieJar` method to `IClientService` and a `getCookieJar` method to `IClient` + add extra option argument `$cookieJar` to `IClientService::newClient` method + implementation of interfaces in HTTP Client

This is WIP for review

2020-04-16 06:16 UTC, nickvergessen requested changes
Some minor changes and I think it's okay.

The only unsure point is whether the API should return a `CookieJarInterface` or we add a wrapped interface like with the GuzzleClient

2020-04-16 06:16 UTC, nickvergessen commented on lib/private/Http/Client/ClientService.php
> +	public function newClient(?CookieJarInterface $cookieJar): IClient {
```suggestion
	public function newClient(?CookieJarInterface $cookieJar = null): IClient {
```

This is needed so we don't break old calls without any arguments

2020-04-16 06:16 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	public function newClient(?CookieJarInterface $cookieJar): IClient;
```suggestion
	public function newClient(?CookieJarInterface $cookieJar = null): IClient;
```

This is needed so we don't break old calls without any arguments

2020-04-16 06:16 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
>  	 * @since 8.1.0
```suggestion
	 * @since 8.1.0 - Since Nextcloud 19.0.0 an optional $cookieJar can be provided
```

2020-04-16 06:16 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	 * @return CookieJarInterface
```suggestion
	 * @return CookieJarInterface
	 * @since 19.0.0
```

2020-04-16 06:16 UTC, nickvergessen commented on lib/public/Http/Client/IClient.php
> +	 * @return CookieJarInterface
```suggestion
	 * @return CookieJarInterface|null
	 * @since 19.0.0
```
```

2020-04-16 06:16 UTC, nickvergessen commented on lib/private/Http/Client/Client.php
> +	 * @return CookieJarInterface
```suggestion
	 * @return CookieJarInterface|null
```

2020-04-16 06:16 UTC, nickvergessen commented on lib/private/Http/Client/Client.php
> +	 * Returns
Could also jsut remove the docs here as the specified returntype is already enough

2020-04-16 06:16 UTC, nickvergessen commented on lib/private/Http/Client/Client.php
> +	 * @param CookieJarInterface $cookieJar
```suggestion
	 * @param CookieJarInterface|null $cookieJar
```

2020-04-16 06:16 UTC, nickvergessen commented on lib/private/Http/Client/Client.php
> +	/** @var CookieJarInterface */
```suggestion
	/** @var CookieJarInterface|null */
```

2020-04-16 21:40 UTC, liamjack commented
Thanks @nickvergessen for your feedback and suggestions, I've implemented these in the latest commit. I'm also unsure about the API returning a `CookieJarInterface`, it's convenient but ideally I want to avoid Guzzle lock-in.

2020-04-21 12:51 UTC, nickvergessen commented
@rullzer no strong feelings. But I think the correct way would be to not expose `CookieJarInterface` and instead add our own CookieJar.

2022-03-03 16:56 UTC, PVince81 commented
I guess cookie jar could be interesting when connecting to remote DAV external storages (perhaps also federated shares) so we don't need to do basic auth for every single call (to be verified)

at least I don't see any cookies used here: https://github.com/nextcloud/server/blob/v23.0.2/lib/private/Files/Storage/DAV.php#L98

2023-03-14 18:39 UTC, max-nextcloud commented
@liamjack I rebased the PR on current master. Hope that's fine with you. Would you still be up to implement the custom interface to wrap the cookie jar in?

2023-03-15 06:34 UTC, max-nextcloud commented
> @rullzer no strong feelings. But I think the correct way would be to not expose `CookieJarInterface` and instead add our own CookieJar.

I tried a different approach in [d7d7e9c](https://github.com/nextcloud/server/pull/20508/commits/d7d7e9c9e16183c78be0020dc576e9bbd298832f): Hide the cookie jar as am implementation detail completely and only expose an option to use it to keep cookies between requests. I think this should do the trick while at the same time keeping the API free from guzzle specifics.

2023-03-15 07:18 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	 * @since 8.1.0 - Since Nextcloud 27.0.0 cookies can be kept with $useCookieJar.
```suggestion
	 * @since 8.1.0
	 * @since 27.0.0 - Parameter $useCookieJar was added
```

2023-03-15 07:20 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	 * @param bool|null $useCookieJar - keep cookies between requests.
```suggestion
	 * @param bool $useCookieJar - keep cookies between requests.
```

2023-03-15 07:20 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	public function newClient(?bool $useCookieJar = false): IClient;
```suggestion
	public function newClient(bool $useCookieJar = false): IClient;
```

No need for null, boolean with on/off is good enough

2023-03-15 07:20 UTC, nickvergessen commented on lib/private/Http/Client/ClientService.php
> +	 * @param bool|null $useCookieJar - keep cookies between requests
```suggestion
	 * @param bool $useCookieJar - keep cookies between requests
```

2023-03-15 07:20 UTC, nickvergessen commented on lib/private/Http/Client/ClientService.php
> +	public function newClient(?bool $useCookieJar = false): IClient {
```suggestion
	public function newClient(bool $useCookieJar = false): IClient {
```

2023-03-15 07:20 UTC, nickvergessen commented on lib/private/Http/Client/Client.php
> +		?bool $useCookieJar = false
```suggestion
		bool $useCookieJar = false
```

2023-03-15 09:32 UTC, max-nextcloud commented on lib/public/Http/Client/IClientService.php
> +	public function newClient(?bool $useCookieJar = false): IClient;
But doesn't that break the current usage of the API?
If the `$useCookieJar` parameter is required we will need to provide it everywhere `newClient` is called, won't we?

2023-03-15 10:06 UTC, nickvergessen commented on lib/public/Http/Client/IClientService.php
> +	public function newClient(?bool $useCookieJar = false): IClient;
It is not required, the `= false` means it falls back to boolean false

2024-02-27 13:12 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open and solve the various conflicts.

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2024-02-27 13:12 UTC, closed without merging