Add promoted-view and square icons
nextcloud/server pull request #20539
Opened 2020-04-17 13:23 UTC by ma12-co

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

2020-04-17 13:35 UTC, skjnldsv commented on core/img/actions/promoted-view.svg
> +<rect x="1" y="1" width="13" height="9" rx="1" fill="black"/>
fill="black" not needed ;)

2020-04-17 13:37 UTC, skjnldsv commented
So, you used a radius of 1, but be aware that the grid one have a radius of .5 :)

2020-04-17 13:41 UTC, ma12-co commented
> be aware that the grid one have a radius of .5 :)

Can I remove all this nearly invisible border radiuses and make squares here? It would help a lot also with how the 3 little squares look..

2020-04-17 13:46 UTC, skjnldsv commented
> Can I remove all this nearly invisible border radiuses and use straight squares here? It would help a lot also with how the 3 little squares look..

see with Jan, I'm fine with whatever :p

2020-04-17 13:48 UTC, jancborchardt commented
> > be aware that the grid one have a radius of .5 :)
> 
> Can I remove all this nearly invisible border radiuses and make squares here? It would help a lot also with how the 3 little squares look..

If it looks good, go ahead. :)

2020-04-17 13:51 UTC, jancborchardt approved these changes
Looks super nice! Seeing how we now have 3 icons without text next to each other, shouldn’t we get the 3-dot menu?
> Start call button | 3-dot menu | Sidebar icon

"Fullscreen" and "Grid view" (shorter wording btw) can be in the 3-dot menu. If we want to, we can even put the sidebar icon in the 3-dot menu as "Participants & settings" or just "Conversation settings".

2020-04-17 14:14 UTC, ma12-co commented
> Looks super nice! Seeing how we now have 3 icons without text next to each other, shouldn’t we get the 3-dot menu?

I wouldn't do this Jan because we are going to bring the whole moderation menu as a 3 dot menu in the app content. Plus those 2 controls are very important for the call imo: provided there's enough width, I think we should show them explicitly

2020-04-17 15:30 UTC, ma12-co commented
@skjnldsv do you know why the build is failing?

2020-04-17 15:31 UTC, skjnldsv commented
Unrelated

2020-04-17 15:52 UTC, nickvergessen commented
I would vote that these are very specific icons and they should just go to the Talk app for now.

Also they should be minified hiding the script in build/

2020-04-18 06:27 UTC, ma12-co commented
> these are very specific icons 

Only the `promoted-view` icon is specific to talk, the grid is used in other apps too.

2020-04-18 09:22 UTC, rullzer commented
> > these are very specific icons
> 
> Only the `promoted-view` icon is specific to talk, the grid is used in other apps too.

fair enough. Then move the promoted view to talk ;)

2020-04-18 10:23 UTC, ma12-co commented
Wouldn't be better, for the sake of standardization, to leave it here? I mean, that icon is in the end just 1 big rectangle on top 3 smaller rectangles, it could also be easily a gallery icon, or something else we haven't thought of! What if a  contributor developing an app needs something like this? Isn't it better to provide it in the server instead of having him create his own version?

2020-04-19 08:25 UTC, rullzer commented
> Wouldn't be better, for the sake of standardization, to leave it here? I mean, that icon is in the end just 1 big rectangle on top of 3 smaller rectangles, it could also be easily a gallery icon, or something else we haven't thought of! What if a contributor developing an app needs something like this? Isn't it better to provide it in the server instead of having him create his own version?
> 
> Edit: we could also add it to talk for now to simplify backports, but I would leave a version of it here as well.

Just dumping all icons in server is not a solution IMO.
Apps should provide their own icons as much as possible. If not only for the backports. And making sure the icon in server isn't suddenly changed.

If it turns out an icon is used consistently across apps for function X. Then we can always move it to server. Or as part of the vue components or whatever.

But lets do that once it is needed. If some app comes along now and thinks they needit. They can just copy the icon from talk.

Let try to keep the server as clean as we can. And the apps as self contained as we can.

2020-04-19 08:26 UTC, rullzer commented
Random brain fart. I don't know how easy/feasible it is. But maybe some npm packages nextcloud/icons would make sense?

That way we still have all the standardized icons. But apps just pick the ones they need?

2020-04-19 08:37 UTC, skjnldsv commented
> Random brain fart. I don't know how easy/feasible it is. But maybe some npm packages nextcloud/icons would make sense?

this is planned™ ^^

2020-04-19 09:50 UTC, ma12-co commented
Allrighty!

2020-04-20 06:34 UTC, ma12-co commented
Done, the only change is now the modification to `icon-toggle-pictures`

2020-04-20 06:41 UTC, skjnldsv requested changes
See comment, please also update the main post screenshots so people know what it is about now ;)

2020-04-20 06:41 UTC, skjnldsv commented on core/img/actions/toggle-pictures-white.svg
> +<rect x="9.16666" y="9.16666" width="5.83333" height="5.83333" fill="white"/>
Not ok with this change, you switched from round values to things like .1666, this is not scalled on the pixel :)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path d="M1 1h6v6H1zM1 9h6v6H1zM9 1h6v6H9zM9 9h6v6H9z"/></svg>
 ```

Also, we shouldn't need a white icon, we have the scss function for it, this is the reason we deleted all the other ones :wink:

2020-04-20 16:31 UTC, jancborchardt commented
> But lets do that once it is needed. If some app comes along now and thinks they needit. They can just copy the icon from talk.

Agreed on that. No premature standardization. :)

2020-04-21 08:55 UTC, skjnldsv commented on core/img/actions/toggle-pictures.svg
> +</svg>
```suggestion
<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
<rect x="1" y="1" width="6" height="6"/>
<rect x="1" y="9" width="6" height="6"/>
<rect x="9" y="1" width="6" height="6"/>
<rect x="9" y="9" width="6" height="6"/>
</svg>
```

2020-04-21 09:59 UTC, skjnldsv commented on core/img/actions/toggle-pictures.svg
> +<svg width="16" height="16" fill="none" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><g fill="#000"><rect x="1" y="1" width="6" height="6"/><rect x="1" y="9" width="6" height="6"/><rect x="
You don't need fill xD
```suggestion
<svg width="16" height="16" fill="none" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="1" width="6" height="6"/><rect x="1" y="9" width="6" height="6"/><rect x="9" y="1" width="6" height="6"/><rect x="9" y="9" width="6" height="6"/></svg>
```

2020-04-21 11:33 UTC, jancborchardt requested changes
Wait a sec – the border-radius removal we actually don’t want. The rounded style is something we go for across the design, and the corners should stay softened as they are now. Feel free to increase the radius to 1px for example.

2020-04-21 12:41 UTC, ma12-co commented
@jancborchardt  please take a look at these icons at 100% . There's no roundness to be seen neither with .5 nor with 1px border radius. We're just making these icons blurry.. It's true that we go for the rounded style but there's no need to do this with icons too imo, and many of the icons we have are have straight edges: 

![Screenshot from 2020-04-21 14-38-03](https://user-images.githubusercontent.com/26852655/79866824-a48df800-83dd-11ea-9509-9cc9780832f4.png)

2020-04-23 08:14 UTC, jancborchardt commented
@ma12-co I agree that currently it’s inconsistent and this is something we need to work on. But look at the latest icons: details/info, confirm, comment, fullscreen, menu-sidebar, video-off, audio-off.

All of these are rounded or have a majority of rounded elements in them, which is what we are going for, and what is absolutely a difference to them being squared, even on icon size. The others merely need to be adjusted, and we shouldn’t take steps back.

2020-04-23 08:19 UTC, closed without merging

2020-04-23 08:20 UTC, ma12-co commented
[:cough:](https://material.io/resources/icons/?style=baseline)

2020-04-23 09:10 UTC, jancborchardt commented
> [:cough:](https://material.io/resources/icons/?style=baseline)

We are all for a unified style – for that reason it seems off to remove the rounding which is intentional (and visible) from only 1 icon, no?

Yes, Material Design has an icon set where they have sharp and rounded corners mixed. Let’s look at others as well:
- [SF Symbols from Apple](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/): Uses a lot of rounding of the corners to make their style more approachable, friendly and easily perceivable. (They also round their hardware and app icons as we know.)
- [Bootstrap icons](https://icons.getbootstrap.com/): Even more rounding there
- [Fontawesome](https://fontawesome.com/icons?d=gallery): I don’t particularly like their specific style, but they also round stuff off.

2020-04-23 09:17 UTC, skjnldsv commented
> * [Fontawesome](https://fontawesome.com/icons?d=gallery): I don’t particularly like their specific style, but they also round stuff off.

should be avoided, they changed license a while ago iirc, [Forkawesome](https://github.com/ForkAwesome/Fork-Awesome) is the new OSS version

2020-04-23 09:21 UTC, ma12-co commented
@jancborchardt  the cough was more of and "Let's use these instead" :) 
They have rounded versions too!
https://material.io/resources/icons/?style=round

2020-04-23 09:44 UTC, ma12-co commented
Discussion continues here: https://github.com/nextcloud/nextcloud-vue/issues/1051