Fix languages empty array
nextcloud/server pull request #20719
Opened 2020-04-29 12:46 UTC by GretaD

When the language is forced and error occurs:
vue.runtime.esm.js:1888 TypeError: Cannot read property 'concat' of undefined
    at a.userLanguage (UserRowMixin.js:125)
    at hn.get (vue.runtime.esm.js:4479)
    at hn.evaluate (vue.runtime.esm.js:4584)
    at a.userLanguage (vue.runtime.esm.js:4836)
    at a.<anonymous> (UserRowSimple.vue?fb94:1)

this happens because the forcedLanguage returns empty array.
Should be backported to 18 too

2020-04-29 13:55 UTC, ChristophWurst commented on lib/private/L10N/Factory.php
> +			return ['commonlanguages' => array_values($commonLanguages), 'languages' => $languages];
should it not be empty arrays?

2020-04-29 14:46 UTC, GretaD commented on lib/private/L10N/Factory.php
> +			return ['commonlanguages' => array_values($commonLanguages), 'languages' => $languages];
so you dont think the error is because of the empty array?

2020-04-29 14:57 UTC, ChristophWurst commented on lib/private/L10N/Factory.php
> +			return ['commonlanguages' => array_values($commonLanguages), 'languages' => $languages];
I mean I'm just guessing. But the other case returns an array of two arrays. Here it previously returned an empty array. So if the js part just assumes that `commonlanguages` or `languages` are there then it will fail. I do not know this code well enough to say if returning all messages here is correct, but it seems a bit suspicious. Check git blame for whom to ask for info :)

2020-04-29 23:14 UTC, blizzz commented on lib/private/L10N/Factory.php
> +			return ['commonlanguages' => array_values($commonLanguages), 'languages' => $languages];
this was introduced by @skjnldsv

2020-04-30 08:08 UTC, skjnldsv commented on lib/private/L10N/Factory.php
> +			$potentialName = (string) $l->t('__language_name__');
Is this some specific variable that exists? Or are you asking for translators to translate `__language_name__` to the language name?

2020-04-30 08:08 UTC, georgehrke commented on lib/private/L10N/Factory.php
> +			$potentialName = (string) $l->t('__language_name__');
See https://github.com/nextcloud/server/pull/20719/files#diff-0adb6edb83bb2d21c924c900685ed501R608

2020-04-30 08:10 UTC, skjnldsv commented on lib/private/L10N/Factory.php
> +			$potentialName = (string) $l->t('__language_name__');
Ah ok! Thanks :)

2020-04-30 08:15 UTC, skjnldsv requested changes
- [x] Doesn't work for me, using `'force_language' => 'fr',` show en
  ![Capture d’écran_2020-04-30_10-14-58](https://user-images.githubusercontent.com/14975046/80688022-78543480-8acb-11ea-9aac-be3019f97a16.png)

2020-04-30 09:11 UTC, GretaD commented
> Doesn't work for me, using `'force_language' => 'fr',` show en

hmm, do we need to change also here? https://github.com/nextcloud/server/blob/b569f3c2c6190197d13077c1d1fa79ce6d508d47/apps/settings/lib/Settings/Personal/PersonalInfo.php#L192-L198

2020-05-04 15:54 UTC, skjnldsv approved these changes

2020-05-04 16:02 UTC, ChristophWurst approved these changes
Didn't test but code looks good

2020-05-04 16:24 UTC, skjnldsv commented
/backport to stable18

2020-05-06 10:00 UTC, MorrisJobke requested changes
CI failures:

```
There were 3 failures:
373	
374	1) OCA\Provisioning_API\Tests\Controller\UsersControllerTest::testGetUserDataAsAdmin
375	Failed asserting that two arrays are equal.
376	--- Expected
377	+++ Actual
378	@@ @@
379	     'website' => 'website'
380	     'twitter' => 'twitter'
381	     'groups' => Array (...)
382	-    'language' => 'de'
383	+    'language' => null
384	     'locale' => null
385	     'backendCapabilities' => Array (...)
386	 )
387	
388	/drone/src/apps/provisioning_api/tests/Controller/UsersControllerTest.php:1019
389	
390	2) OCA\Provisioning_API\Tests\Controller\UsersControllerTest::testGetUserDataAsSubAdminAndUserIsAccessible
391	Failed asserting that two arrays are equal.
392	--- Expected
393	+++ Actual
394	@@ @@
395	     'website' => 'website'
396	     'twitter' => 'twitter'
397	     'groups' => Array ()
398	-    'language' => 'da'
399	+    'language' => null
400	     'locale' => null
401	     'backendCapabilities' => Array (...)
402	 )
403	
404	/drone/src/apps/provisioning_api/tests/Controller/UsersControllerTest.php:1149
405	
406	3) OCA\Provisioning_API\Tests\Controller\UsersControllerTest::testGetUserDataAsSubAdminSelfLookup
407	Failed asserting that two arrays are equal.
408	--- Expected
409	+++ Actual
410	@@ @@
411	     'website' => 'website'
412	     'twitter' => 'twitter'
413	     'groups' => Array ()
414	-    'language' => 'ru'
415	+    'language' => null
416	     'locale' => null
417	     'backendCapabilities' => Array (...)
418	 )
419	
420	/drone/src/apps/provisioning_api/tests/Controller/UsersControllerTest.php:1319
421	
422	--
```

2020-05-06 20:06 UTC, rullzer commented
/backport to stable19

2020-05-08 07:58 UTC, MorrisJobke commented on lib/private/L10N/Factory.php
> +			$potentialName = (string) $l->t('__language_name__');
> Is this some specific variable that exists? Or are you asking for translators to translate `__language_name__` to the language name?

Yes - this is the name of the language you are translating. So this is a different term in each language. That's why we decided to go for this weird name. :)

2020-05-08 07:58 UTC, MorrisJobke approved these changes

2020-05-08 08:03 UTC, MorrisJobke approved these changes
Tested and works 👍

2020-05-08 09:22 UTC, merged