Do not filter id matching userId on non-user-share shares
nextcloud/server pull request #20832
Opened 2020-05-05 16:57 UTC by skjnldsv

Before
![Kazam_screenshot_00018](https://user-images.githubusercontent.com/14975046/81093261-21eb5980-8f02-11ea-9ee2-ad9d4cc96a98.png)
___
After
![Kazam_screenshot_00017](https://user-images.githubusercontent.com/14975046/81093258-2152c300-8f02-11ea-80b0-6e9899f214ba.png)

2020-05-05 16:57 UTC, skjnldsv commented
/backport to stable18

2020-05-05 17:00 UTC, skjnldsv commented
/compile amend /

2020-05-05 18:02 UTC, ChristophWurst commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if (in_array($share->getId(), $known)
mind adding parenthesis so it's either clearly (A||B)&&C or A||(B&&C)?

2020-05-05 18:06 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if (in_array($share->getId(), $known)
Done!

2020-05-05 19:13 UTC, skjnldsv commented
/compile amend /

2020-05-05 19:13 UTC, nickvergessen requested changes
Not build with production

2020-05-05 19:34 UTC, nickvergessen approved these changes

2020-05-05 19:34 UTC, nickvergessen commented
> Lint / php-cs check (pull_request) Failing

2020-05-05 19:37 UTC, skjnldsv commented
> > Lint / php-cs check (pull_request) Failing

fixed

2020-05-06 15:45 UTC, MorrisJobke approved these changes
Code looks good 👍

2020-05-06 15:46 UTC, merged