l10n: Add "The" before "Following"
nextcloud/server pull request #20957
Opened 2020-05-13 13:29 UTC by Valdnet

2020-05-13 20:29 UTC, gary-kim approved these changes

2020-05-15 06:10 UTC, rullzer approved these changes

2020-05-15 06:11 UTC, rullzer requested changes
Tests need update as well it seems

2020-05-15 17:43 UTC, rullzer approved these changes

2020-05-15 17:44 UTC, merged