Improve focus highlight
nextcloud/server pull request #2098
Opened 2016-11-13 13:44 UTC by LiamHD

The currently focused element (e.g. input field) is only hardly visible because the css files disable drawing of the outline. This is really bad for usability especially when using keyboard navigation (with the TAB key).

2016-11-14 09:00 UTC, MorrisJobke commented
cc @nextcloud/designers

2016-11-14 09:18 UTC, Espina2 commented
Can I see a print screen?

2016-11-14 09:53 UTC, LiamHD commented
![image](https://cloud.githubusercontent.com/assets/6286072/20260101/6caa12c8-aa58-11e6-80bb-15d18ade099f.png)

![image](https://cloud.githubusercontent.com/assets/6286072/20260122/8cd65200-aa58-11e6-9fa3-902124d0a14e.png)

2016-11-14 10:10 UTC, jancborchardt commented
@LiamHD thank you for the improvement! :) The default outline was overridden because in lots of cases it’s visually unpleasant and inconsistent between systems and browsers. For many elements we do have hover/focus styles but inputs apparently not.

It would be good to keep it overridden but replace it with a proper style which looks nice and is consistent. Do you want to have a look at that? :)

2016-11-14 10:27 UTC, LiamHD commented
@jancborchardt 
Can you please provide examples where it is "visually unpleasant"? And on which browsers is it inconsistent? At least on chrome and safari on mac the defaults look very similar (light blow glow effect).

2016-11-14 11:08 UTC, eppfel commented
I agree with @jancborchardt that, instead of using the browser default, we should find a consistent style for this.

@LiamHD The glow color is actually the selection color set by the user in the system settings of Mac OS and therefore could yield some weird results. And Firefox on Mac does not have these outlines/glows. And that's just on Mac...

A quick and easy solution would be using the nextcloud accent color for the border. Buttons look odd, though.

![nextcloud-input-focus](https://cloud.githubusercontent.com/assets/1899308/20262565/078affbe-aa63-11e6-934c-304692c7afda.gif)

2016-11-14 11:46 UTC, LiamHD commented
@eppfel: What is odd on the buttons?

2016-11-14 12:21 UTC, eppfel commented
@LiamHD They look like too similar to text inputs. And we don't use this button style...

Maybe changing the font-color helps:
![button-focus](https://cloud.githubusercontent.com/assets/1899308/20264615/c3061342-aa6c-11e6-911a-e639224151ab.gif)

But personally I consider the grey buttons too minimalistic anyway:
![button-redesign](https://cloud.githubusercontent.com/assets/1899308/20264632/d32a1aa2-aa6c-11e6-94b9-f02c2645e26a.gif)
But thats something for another issue...

2016-11-14 15:59 UTC, LiamHD commented
whats the "nextcloud accent color"? Is that defined somewhere in the CSS?

2016-11-14 16:06 UTC, skjnldsv commented
@eppfel I like it!

2016-11-14 17:16 UTC, eppfel commented
@LiamHD It is the nextcloud blue by default, but can by set in the theming app. @juliushaertl to the rescue! 😁 
...and with buttons we might want to distinguish `:hover` and `:focus` states. 🤔

2016-11-15 08:41 UTC, LiamHD commented
I have some trouble changing the outline-color on safari.
See https://jsfiddle.net/LiamHD/15m22c1k/
This is working fine in chrome and in firebox, but safari still shows the blue outline color. Any ideas?

2016-11-15 09:38 UTC, LiamHD commented
b540259 uses the nextcloud blue as outline-color. How does that theming work from a technical point of view? When I change the color in the theming settings the outline-color is not adapted at the moment.

2016-11-15 11:49 UTC, eppfel commented
@LiamHD Nice that you're trying to fix it. I just used the `border-color` in the mockups. I think `outline` is problematic.

The Theming App loads a CSS file generated with the custom color, that overwrites prior CSS properties. The CSS is generated in [server/apps/theming/lib/Controller/ThemingController.php](https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php)

2016-11-15 13:19 UTC, LiamHD commented
Better with 9c02917 ?
So do I also have to adapt server/apps/theming/lib/Controller/ThemingController.php to also override the border-color?

2016-11-15 19:11 UTC, eppfel submitted a review, later dismissed
I think we should stick to the inputs and mabye buttons for now. Other opinions @nextcloud/designers ?

Should we choose 2px borders, we need to address the size glitches.

2016-11-15 19:11 UTC, eppfel commented on core/css/inputs.css
> +	border: 2px solid #0082c9;
1px should be enough and more fitting. Also, changing the border-size, changes the size of the element, which creates layout glitches. (see below)

2016-11-15 19:12 UTC, eppfel commented
@LiamHD We can address the theming in a next step.

2016-11-16 07:42 UTC, LiamHD commented on core/css/styles.css
> +	border: 1px solid #0082c9;
Understood.

2016-11-16 08:22 UTC, LiamHD commented on core/css/styles.css
> +a:focus { 	color: #333; border: 2px solid #0082c9;}
fixed with 6663dc4

2016-11-16 08:22 UTC, LiamHD commented on core/css/styles.css
> +	border: 1px solid #0082c9;
Fixed with 6663dc4

2016-11-16 08:22 UTC, LiamHD commented on core/css/inputs.css
> +	border: 2px solid #0082c9;
Fixed with 6663dc4

2016-11-16 13:22 UTC, juliushaertl commented
@LiamHD Right, changes for the theming CSS go in `apps/theming/lib/Controller/ThemingController.php` but make sure those are also addressed in the unit tests at `apps/theming/tests/Controller/ThemingControllerTest.php`

2016-11-17 21:47 UTC, jancborchardt commented
@LiamHD is this ready by the way? We have Nextcloud 11 feature freeze this week. :)

Please review @nextcloud/accessibility @nextcloud/designers

2016-11-18 10:15 UTC, eppfel commented
There are a lot of unclean effects right now:

---
<img width="308" alt="bildschirmfoto 2016-11-16 um 22 37 46" src="https://cloud.githubusercontent.com/assets/1899308/20426133/f57bbff2-ad7d-11e6-9e80-708610d7eefe.png">

---
<img width="384" alt="bildschirmfoto 2016-11-16 um 22 37 28" src="https://cloud.githubusercontent.com/assets/1899308/20426267/a6f58682-ad7e-11e6-9233-cb564e7d70f3.png">

---
<img width="262" alt="bildschirmfoto 2016-11-16 um 22 36 52" src="https://cloud.githubusercontent.com/assets/1899308/20426566/fa16115a-ad7f-11e6-9256-775421375194.png">


---

I would really advise to limit this PR to text inputs and maybe buttons. It would be an improvement, without breaking other stuff (to my knowledge). These rules could easily added to theming app.

@LiamHD To finally merge this PR you have to [sign your commits](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work) and best would be, if you could squash them to one commit.

So,...

1. finalize changes
1. squash commits
1. sign the commit
1. push force

If you need more help with this, let me know. We might have to open on new branch in the nextcloud/server repository.

2016-11-19 19:00 UTC, LiamHD commented
@eppfel: Will look into this tomorrow.
Ok let's start with the input and buttons (as they already have borders).
How can we fix the "unclean effects in a next PR? Any ideas?
From my point of view every focused element should be highlighted as only by doing this you know "where you are" when you navigate with the keyboard.

2016-11-19 20:22 UTC, eppfel commented
@LiamHD I think we have to address the various links we use on nextcloud individually e.g. in the sidebar a background color might work better than a border.

> From my point of view every focused element should be highlighted as only by doing this you know "where you are" when you navigate with the keyboard.

True that. But in forms using <kbd>⇥</kbd> is most prevalent, so this is definitively a big improvement.

Ideally the tabindex would start at the relevant elements and there would be shortcuts for navigation. We're already discussing keyboard controls in #1444

2016-11-20 10:12 UTC, LiamHD commented
> So,...
> 
> 1. finalize changes
> 2. squash commits
> 3. sign the commit
> 4. push force

Done.

2016-11-20 11:08 UTC, LiamHD commented
Why does the continous-integration build issue;

```
+ php ./build/signed-off-checker.php
0s
3
Some commits were not signed off!
4s
4
Missing signatures on:
4s
5
- 1df8c9058a4e521c7ad1c38b92a9e439215e64da
4s
6
Build has failed
```
?

2016-11-21 12:45 UTC, eppfel commented on core/css/inputs.css
> +button:focus, .button:focus {
Should we add `select:focus` ?
<img width="325" alt="bildschirmfoto 2016-11-21 um 13 42 36" src="https://cloud.githubusercontent.com/assets/1899308/20483109/a4edd334-aff0-11e6-9a7e-85b50703755c.png"><img width="325" alt="bildschirmfoto 2016-11-21 um 13 44 09" src="https://cloud.githubusercontent.com/assets/1899308/20483111/a6c3fe86-aff0-11e6-8966-c9558fc76fce.png">

2016-11-21 12:53 UTC, eppfel commented
@LiamHD Seems to work. Do you want to add these two rules to the theming? 
It is inside the [function getStylesheet()](https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php#L321)
It may needs some tweaking, for the inverted text colors, if someone chooses a very pale color.

The sign-off error: How did you sign it? Maybe a missing whitespace between your name and the e-mail? Just guessing.

2016-11-21 13:38 UTC, LiamHD commented
I added the "select:focus" style and also added a second commit to consider theming.

2016-11-21 13:57 UTC, eppfel commented on apps/theming/lib/Controller/ThemingController.php
> +							'	color: #333; '.
I think this line is obsolete, because it is set to `#333` already.

2016-11-21 13:58 UTC, eppfel commented on core/css/inputs.css
> +	color: #333;
Now, that I look again why is this needed anyway. Isn't this the default?

2016-11-21 14:00 UTC, eppfel commented
Works on my side. Just the minor thing with this `color: #333` , maybe there is a reason for this, that i don't see.

2016-11-21 15:23 UTC, eppfel commented
Ah, and now we have to adjust the tests. 🐝 Totally forgot about that.  But the signing worked 🎉 
[server/apps/theming/tests/Controller/ThemingControllerTest.php](https://github.com/nextcloud/server/blob/master/apps/theming/tests/Controller/ThemingControllerTest.php)

2016-11-21 15:28 UTC, eppfel commented on core/css/inputs.css
> +	color: #333;
There is rule in place already, so yeah, I think it's obsolete:
<img width="995" alt="bildschirmfoto 2016-11-21 um 16 25 35" src="https://cloud.githubusercontent.com/assets/1899308/20488471/6abc7dca-b007-11e6-83d4-0bd45a674f18.png">

2016-11-21 17:15 UTC, LiamHD commented
@eppfel : I did have a look at the tests you mentioned but did not understand them. What needs to be adapted there?
Should I remove the `color: #333` ?

2016-11-22 10:02 UTC, eppfel commented
@LiamHD Yes, removing `color: #333` would save a line of code and a CSS rule to render.

I only changed one nextcloud unit test so far, so no expert either. But to me, it looks like the four functions that fail, check if the generated CSS is as expected. Because we change the CSS, we have to adapt what the test have to expect. 
So, I think we just have to add the additional CSS rules to the tests:
- testGetStylesheetWithOnlyColor
- testGetStylesheetWithOnlyColorInvert
- testGetStylesheetWithAllCombined
- testGetStylesheetWithAllCombinedInverted

See: https://github.com/nextcloud/server/blob/master/apps/theming/tests/Controller/ThemingControllerTest.php#L437

Still happy to help..

2016-11-22 11:42 UTC, LiamHD commented
Okay. Now I have removed the unnecessary color rule. 
Also the test are fixed. 
@eppfel : Thanks for you help.

2016-11-22 13:10 UTC, eppfel commented
Hey, we did it. Glad to help. You could squash and force push again...
LGTM

2016-11-22 16:29 UTC, jancborchardt commented
@LiamHD @eppfel since we just had feature freeze and this has the potential for breakage, I’d be more confident if we wait with merging this until we have stable11 branched off. I’ll schedule this for Nextcloud 12 then, where we can get it in with the beginning of the development cycle so there’s plenty of time to test. :)

2016-12-13 16:00 UTC, LiamHD commented
Any progress here?

2016-12-16 12:40 UTC, LukasReschke approved these changes
Master is free for merges again. I didn't really test this intensively but @jancborchardt statement above indicates that this should be good to go in.

Jan, please give this a final review and either decide to merge or not merge. Thanks.

2016-12-20 15:04 UTC, ChristophWurst requested changes
Works nicely except for HTML selects. The text of the items in the dropdown is colored according to the themed color. This works with dark ones, but bright ones make it impossible to read.
Tested with FF on Linux

2016-12-22 10:03 UTC, MorrisJobke commented
Hey @LiamHD could you check the issue that @ChristophWurst noticed? Thanks :)

2017-01-05 10:22 UTC, ChristophWurst commented on apps/theming/lib/Controller/ThemingController.php
> +			$responseCss .= 'input[type="text"]:focus, input[type="password"]:focus, input[type="search"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="tel"]:focus, input[type="url
@LiamHD we could exclude selects here

2017-01-22 19:29 UTC, eppfel commented
Obsolete due to #3187

2017-01-22 19:29 UTC, closed without merging