Set serverBackground if it is a custom background or default hub
nextcloud/server pull request #21058
Opened 2020-05-20 15:33 UTC by GretaD

fixes #21046

2020-05-20 16:27 UTC, tobiasKaminsky approved these changes

2020-05-22 13:19 UTC, juliushaertl commented on apps/theming/lib/Capabilities.php
> +				'background' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9') ?
We actually need to check for false since that is the background logo default if none is set
https://github.com/nextcloud/server/blob/e06d979f2ebd907d5d95c061458dab66809262c6/apps/theming/lib/Capabilities.php#L71

2020-05-22 13:20 UTC, juliusknorr requested changes

2020-05-22 13:20 UTC, juliushaertl commented on apps/theming/lib/Capabilities.php
>  				'background-plain' => $backgroundLogo === 'backgroundColor',
'background-plain' should return `true` as well if no image is set and the primary color is different than nextcloud blue :)

2020-05-22 16:11 UTC, GretaD commented on apps/theming/lib/Capabilities.php
> +				'background' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9') ?
You mean instead of `$backgroundLogo === null`?

2020-06-05 12:04 UTC, juliusknorr requested changes
Please remove the changes from package-lock.json, otherwise LGTM

2020-06-05 14:08 UTC, GretaD commented
> Please remove the changes from package-lock.json, otherwise LGTM

i had to google what LGTM means :D

2020-06-06 07:42 UTC, rullzer approved these changes

2020-06-06 07:43 UTC, rullzer requested changes

2020-06-06 07:43 UTC, rullzer commented on apps/theming/lib/Capabilities.php
> +				'background-plain' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9'),
Why are the conditions different?

2020-06-08 07:58 UTC, GretaD commented on apps/theming/lib/Capabilities.php
> +				'background-plain' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9'),
`background-plain` its a boolean value, so will already return either true or false

2020-06-08 08:02 UTC, juliushaertl commented on apps/theming/lib/Capabilities.php
> +				'background-plain' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9'),
Ah @rullzer is right, the default fallback for backgroundLogo is false so we should check for that ;)

2020-06-08 08:34 UTC, GretaD commented on apps/theming/lib/Capabilities.php
> +				'background-plain' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9'),
but we do check for false

2020-06-08 08:34 UTC, GretaD commented on apps/theming/lib/Capabilities.php
> +				'background-plain' => $backgroundLogo === 'backgroundColor' || ($backgroundLogo === null && $this->theming->getColorPrimary() !== '#0082c9'),
damn, never mind

2020-06-08 10:27 UTC, juliusknorr approved these changes

2020-06-08 11:44 UTC, rullzer approved these changes

2020-06-08 11:44 UTC, merged