Show changelog in apps management
nextcloud/server pull request #21082
Opened 2020-05-24 14:37 UTC by juliushaertl

This will use the changelog provided by the most recent app store release and show it in the apps management sidebar if available.

Besides that I also did some code cleanup, migrated to use the new sidebar tabs for description/changelog and removed the list transition which had quite a negative performance impact when searching and switching between app categories.

With a changelog:
![image](https://user-images.githubusercontent.com/3404133/82756793-a2ec9100-9ddc-11ea-847a-0f744d6f301e.png)
![image](https://user-images.githubusercontent.com/3404133/82756800-ada72600-9ddc-11ea-8fc6-f25040e91c32.png)

Without a changelog:
![image](https://user-images.githubusercontent.com/3404133/82756822-d29b9900-9ddc-11ea-97f1-9cec15e1752d.png)

2020-05-24 15:24 UTC, jancborchardt commented
Very nice! Only minor thing is that we should call it "What’s new" instead of "Changelog" which is a bit bland and technical. :)

2020-05-25 05:09 UTC, AlexOnFOSS commented
Thats nice! Might it be possible to add a timestamp when the last modification of that update (changelog) has taken place?

2020-05-25 10:25 UTC, GretaD approved these changes
tested and works

2020-05-25 12:50 UTC, jancborchardt requested changes
See comment for wording change (I would add it directly but somehow often the build process for the apps in core messes stuff up for me).

2020-06-06 07:39 UTC, rullzer commented
needs a rebase and the comment from @jancborchardt addressed

2020-07-09 18:49 UTC, juliushaertl commented
I'll wait for https://github.com/nextcloud/server/pull/18969 with the rebase since I forgot that @skjnldsv was already worked on the sidebar migration. Once that is done I'll just pick the relevant changelog changes.

2020-07-09 21:20 UTC, skjnldsv commented
> I'll wait for #18969 with the rebase since I forgot that @skjnldsv was already worked on the sidebar migration. Once that is done I'll just pick the relevant changelog changes.

Thanks! :bow: :heart:

2020-07-28 21:40 UTC, jancborchardt commented
Btw @juliushaertl to make it simpler and also work better on mobile, we could just put the changelog below the description/links instead of using tabs.

This is also how the Android Play store and the iOS app store essentially do it. To alleviate the case of a very long description, we can set some max-height which will expand on click – exactly like we do for the rich workspaces.

2020-08-13 03:33 UTC, rullzer commented
@juliushaertl still something we can tackle for 20?

2020-08-13 06:15 UTC, juliushaertl commented
Not before https://github.com/nextcloud/server/pull/18969

2020-08-13 07:38 UTC, skjnldsv commented
> Not before #18969

will dive into it again soon

2020-08-20 13:01 UTC, rullzer commented
soooo?

2020-09-01 10:10 UTC, juliushaertl commented
Force-pushed the changelog only changes now based on master.

2020-09-01 11:45 UTC, skjnldsv commented on apps/settings/src/components/Markdown.vue
> +		renderMarkdown() {
Would be nice as a library :wink:

2020-09-01 11:45 UTC, skjnldsv commented on apps/settings/src/views/Apps.vue
> +				id="desca"
desca ?
```suggestion
				id="changelog"
```

2020-09-01 11:46 UTC, skjnldsv approved these changes
Minor nitpick! :)
Great job!!! :rocket: :heart_eyes:

2020-09-01 13:28 UTC, juliushaertl commented on apps/settings/src/components/Markdown.vue
> +		renderMarkdown() {
Something for `@nextcloud/vue` or as a separate one?

2020-09-01 14:02 UTC, skjnldsv commented on apps/settings/src/components/Markdown.vue
> +		renderMarkdown() {
Maybe a separate one with the markdown editor?

2020-09-01 14:25 UTC, juliushaertl commented on apps/settings/src/components/Markdown.vue
> +		renderMarkdown() {
Then let's track this in https://github.com/juliushaertl/nextcloud-text/issues/207 for now

2020-09-03 19:03 UTC, rullzer commented
/compile amend /

2020-09-03 20:13 UTC, merged