Search also the email and displayname in user mangement for groups
nextcloud/server pull request #21138
Opened 2020-05-28 15:28 UTC by MorrisJobke

Similar to #17800 but also searches the email address.

This streamlines the search in groups with the one in users: 

https://github.com/nextcloud/server/blob/145eee91fe611a9ae59c5e6d9a8d06104112c1a5/lib/private/User/Database.php#L266-L278

See #13951

* [ ] when testing this it doesn't show the results - but executing the query by hand finds the correct users. Any idea what causes the trouble here?

2020-08-03 13:58 UTC, blizzz commented
> when testing this it doesn't show the results - but executing the query by hand finds the correct users. Any idea what causes the trouble here?

WFM :tm:

2020-08-03 13:59 UTC, blizzz approved these changes

2020-08-04 15:32 UTC, MorrisJobke commented
> [x] when testing this it doesn't show the results - but executing the query by hand finds the correct users. Any idea what causes the trouble here?

Works for me now.

Unfortunately the unified search made the search field unavailable for the user management. Thus I based this on commit 7b91cb5029 which is the one right before the unified search got merged. Then we can still test this and work on a solution for this in 20.

@skjnldsv Is this the wanted behavior of the unified search? Because some apps (like the user management here or the app management) use this for filtering the current view.

@juliushaertl @nickvergessen @kesselb Mind to review this?

@blizzz Does a backport make sense here?

2020-08-04 15:36 UTC, skjnldsv commented
> @skjnldsv Is this the wanted behavior of the unified search? Because some apps (like the user management here or the app management) use this for filtering the current view.

We're discussing this.
The apps are going to appear in the unified search https://github.com/nextcloud/server/pull/22102
For the users it's up to @jancborchardt

2020-08-04 15:56 UTC, MorrisJobke commented
> For the users it's up to @jancborchardt

Same for app management, right? Because it's an admin task vs an normal use case. But up to @jancborchardt

2020-08-05 06:57 UTC, nickvergessen requested changes
Can we have a dedicated test added?

2020-08-05 06:57 UTC, nickvergessen commented on lib/private/Group/Database.php
> +					$query->expr()->eq('configkey', $query->expr()->literal('email')))
```suggestion
					$query->expr()->eq('p.userid', 'u.uid'),
					$query->expr()->eq('p.appid', $query->expr()->literal('settings')),
					$query->expr()->eq('p.configkey', $query->expr()->literal('email')))
```

2020-08-05 06:57 UTC, nickvergessen commented on lib/private/Group/Database.php
> +						$query->expr()->ilike('configvalue', $query->createNamedParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%'))
```suggestion
						$query->expr()->ilike('u.displayname', $query->createNamedParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%')),
						$query->expr()->ilike('p.configvalue', $query->createNamedParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%'))
```

2020-08-05 06:57 UTC, nickvergessen commented on lib/private/Group/Database.php
> +				->orderBy('uid_lower', 'ASC');
```suggestion
				->orderBy('u.uid_lower', 'ASC');
```

2020-08-05 08:55 UTC, juliusknorr approved these changes

2020-08-05 08:57 UTC, MorrisJobke commented
> Can we have a dedicated test added?

I added some integration tests to verify the outside view of this. Otherwise I need to have mocked so much, that it barely is useful in the future.

2020-08-05 08:59 UTC, nickvergessen commented on build/integration/features/provisioning-v2.feature
> +    When sending "GET" to "/cloud/users/detailsoffset=25&limit=25&search="fic-n"
:confused: 

```suggestion
    When sending "GET" to "/cloud/users/detailsoffset=25&limit=25&search=fic-n"
```

2020-08-05 09:02 UTC, MorrisJobke commented on build/integration/features/provisioning-v2.feature
> +    When sending "GET" to "/cloud/users/detailsoffset=25&limit=25&search="fic-n"
🙈

2020-08-05 12:14 UTC, MorrisJobke commented
> I added some integration tests to verify the outside view of this. Otherwise I need to have mocked so much, that it barely is useful in the future.

I refined them a bit and they work locally. Also did some negative testing locally so that they actually indicate when something breaks and it is the case.

Ready for a final review :)

2020-08-05 12:15 UTC, MorrisJobke commented
/backport to stable19

2020-08-05 12:21 UTC, jancborchardt commented
Yep, so there we hit the other part of what we discussed – unified search works great overall, but it does have drawbacks when you are inside an app itself. There e.g. in Talk, Users and Apps, direct filtering of the content is nicer.

This is why in the spec we discussed that the apps which already have in-app search which do proper filtering:
- Can move their in-app search/filter to the top of the navigation, just like Talk – this would work nicely here for User management as well as App management
- Still get the benefit of the unified search in the top right.

Makes sense?

2020-08-05 12:23 UTC, nickvergessen approved these changes

2020-08-05 12:28 UTC, MorrisJobke commented
> This is why in the spec we discussed that the apps which already have in-app search which do proper filtering:
> 
> * Can move their in-app search/filter to the top of the navigation, just like Talk – this would work nicely here for User management as well as App management
> * Still get the benefit of the unified search in the top right.
> 
> Makes sense?

How to differentiate then between the filter and the unified search? Or should we maybe move the filtering from the header into the actual app content?

2020-08-05 14:09 UTC, merged

2020-08-05 14:40 UTC, jancborchardt commented
> How to differentiate then between the filter and the unified search? Or should we maybe move the filtering from the header into the actual app content?

Yep, as said:

> Can move their in-app search/filter to the top of the navigation, just like Talk

;)

2020-08-05 14:44 UTC, MorrisJobke commented
> > Can move their in-app search/filter to the top of the navigation, just like Talk

Ah - I thought adding it to the "top navigation" (aka header) 🙈

2020-08-05 20:26 UTC, blizzz commented
> @blizzz Does a backport make sense here?

yes (:

2020-08-05 20:28 UTC, blizzz commented
> in Talk, Users and Apps, direct filtering of the content is nicer.

at least in Users search has to go via the server. Just too much to pull all of them into the browser.