Type the query builder
nextcloud/server pull request #21142
Opened 2020-05-28 20:06 UTC by ChristophWurst

This is mostly moving types from just phpdoc to actual php type hints.

But I've also changed update, delete and insert slightly so the first parameter is always a string and not nullable. I really can't see a use case where a null table name would be ok.

Changes

* Added return type hints
* Added parameter type hints
* Fixed injected `Connection` because we can't pass our implementation to `\Doctrine\DBAL\Query\QueryBuilder::__construct`, though it indirectly implements that class
* Enabled strict types for both files

2020-06-02 11:43 UTC, rullzer approved these changes

2020-06-04 08:51 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	public function getParameters(): array ;
```suggestion
	public function getParameters(): array;
```

2020-06-04 08:58 UTC, nickvergessen requested changes

2020-06-04 08:58 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	public function getParameterTypes(): array ;
```suggestion
	public function getParameterTypes(): array;
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	public function join(string $fromAlias, string $join, string $alias, $condition): self;
This breaks if no condition was specified.
Now I know it makes little sense, but it is an incompatibility with the doctrine thing, so not sure.

2020-06-04 08:58 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @return mixed[]
```suggestion
	 * @return string[]
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	public function createFunction($call):IQueryFunction;
```suggestion
	public function createFunction($call): IQueryFunction;
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function selectDistinct($select) : IQueryBuilder {
```suggestion
	public function selectDistinct($select): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function addSelect(...$selects) : IQueryBuilder {
```suggestion
	public function addSelect(...$selects): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function delete(string $delete, string $alias = null) : IQueryBuilder {
```suggestion
	public function delete(string $delete, string $alias = null): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function update(string $update, string $alias = null) : IQueryBuilder {
```suggestion
	public function update(string $update, string $alias = null): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function set(string $key, $value) : IQueryBuilder {
```suggestion
	public function set(string $key, $value): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function andWhere(...$where) : IQueryBuilder {
```suggestion
	public function andWhere(...$where): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function setValue(string $column, $value) : IQueryBuilder {
```suggestion
	public function setValue(string $column, $value): IQueryBuilder {
```

2020-06-04 08:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function orHaving(...$having) : IQueryBuilder {
There are some more ` :  ` issues, does php cs fix them?

2020-06-04 09:14 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	public function join(string $fromAlias, string $join, string $alias, $condition): self;
Yeah, I was not fully sure about this one. BUT we can enforce having a condition. We'll still be compatible with doctrine. And I really don't see any use case except the cross product where a join without condition would work. Do you?

2020-06-04 09:14 UTC, ChristophWurst commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +	public function orHaving(...$having) : IQueryBuilder {
I think

2020-07-06 12:04 UTC, MorrisJobke commented
@ChristophWurst 🏓

2020-07-07 09:55 UTC, ChristophWurst commented
I think CI is really not happy about this. I have to split this into smaller patches, it's too complex to do in one go.

2020-07-07 09:55 UTC, closed without merging