[WIP] Status Feature
nextcloud/server pull request #21186
Opened 2020-06-02 10:49 UTC by georgehrke

fixes #20931

2020-06-03 16:01 UTC, kesselb commented on apps/user_status/appinfo/routes.php
> +		['name' => 'UserStatus#learStatus', 'url' => '/api/v1/user_status', 'verb' => 'DELETE'],
```suggestion
		['name' => 'UserStatus#clearStatus', 'url' => '/api/v1/user_status', 'verb' => 'DELETE'],
```

2020-06-03 16:15 UTC, kesselb commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +	 * @since 13.0.0
```suggestion
	 * @since 20.0.0
```

2020-06-03 16:15 UTC, kesselb commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +		if (!$schema->hasTable('user_status')) {
I remember a discussion with @ChristophWurst to not wrap the migration logic into a hasTable check anymore. If the tables are already there the migration runs a second time and that is wrong.

2020-06-03 16:15 UTC, kesselb commented on apps/user_status/lib/Service/StatusService.php
> +		$intlBreakIterator = \IntlBreakIterator::createCharacterInstance();
php-intl is still a optional dependency as per: https://docs.nextcloud.com/server/19/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation

Please update the documentation if php-intl is now a required extension and create a issue to remove the polyfil sometime. I think it's overdue (to make php-intl required) anyway as the test-suite only runs with php-intl and not without.

2020-06-08 08:42 UTC, georgehrke commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +		if (!$schema->hasTable('user_status')) {
Okay, removed it

2020-06-08 10:03 UTC, nickvergessen commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +		$table->addColumn('created_at', Type::INTEGER, [
use datetime?

2020-06-08 13:50 UTC, georgehrke commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +		$table->addColumn('created_at', Type::INTEGER, [
`QBMapper` and `Entity` don't support that and the downside of using integer is little / acceptable imho, no?

2020-07-01 08:11 UTC, nickvergessen requested changes

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/appinfo/app.php
> +$app->registerCapabilities();
Nope, use `IBootstrap` application instead

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/appinfo/info.xml
> +    <name>User Status</name>
```suggestion
    <name>User status</name>
```

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/appinfo/routes.php
> +	'ocs' => [
:sunglasses:

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/img/app.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
`build/image-optimization.sh`

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
We don't do this on any endpoint. Not on notifications, activities, talk chats, etc. so I think we don't need to do it here either.

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/lib/Migration/Version0001Date20200602134824.php
> +
add an index on `clear_at` for the background job?

2020-07-01 08:11 UTC, nickvergessen commented on apps/user_status/tests/Integration/Application/AppTest.php
> +namespace OCA\UserStatus\Tests\Integration\Controller;
wrong namespace,

also I would not call it `Integration` when we have real integration tests in other apps in this directory.

2020-07-01 08:14 UTC, georgehrke commented on apps/user_status/img/app.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
This is just the standard icon from the appstore app skeleton generator.
@jancborchardt Can you please provide a proper icon?

2020-07-01 08:19 UTC, georgehrke commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
This is something I discussed with @tobiasKaminsky. We will have a set of predefined statuses like "On Vacation", etc. 
@rullzer, @tobiasKaminsky and me agreed that we should have them in one central place and that not every app should ship their own copy of the list.

As the language of the client can differ from the user-language in Nextcloud, we need a way for a clients to tell us their preferred language.

2020-07-01 08:21 UTC, georgehrke commented on apps/user_status/tests/Integration/Application/AppTest.php
> +namespace OCA\UserStatus\Tests\Integration\Controller;
This is actually a bug in the AppStore Skeleton Generator. 
https://github.com/nextcloud/appstore/blob/2af4a3fa1bbe4942720a253500efc1fdd542b080/nextcloudappstore/scaffolding/app-templates/12/app/tests/Integration/AppTest.php

Let me just remove this file, since it doesn't really test anything at the moment.

2020-07-01 08:33 UTC, nickvergessen commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
https://github.com/nextcloud/server/blob/master/lib/private/L10N/Factory.php#L383-L412

2020-07-01 08:38 UTC, georgehrke commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
That code is only called if the user did not define any language in Nextcloud.
https://github.com/nextcloud/server/blob/master/lib/private/L10N/Factory.php#L178

2020-07-01 08:38 UTC, nickvergessen commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
I don't really see why activity and notifications etc should behave any different here. So either we use this everywhere and prefer it all the time over the config or not. but having some data served in preference and some in device language is weird I think

2020-07-01 08:41 UTC, georgehrke commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
I'm also fine just using the Nc user-lang. I really don't have any preference here.

@tobiasKaminsky What's your call here?

2020-07-01 10:47 UTC, tobiasKaminsky commented on apps/user_status/lib/Controller/AStatusController.php
> +		$this->lang = $this->request->getHeader('X-REQUESTED-CLIENT-LANG');
If activity/notification currently only obey user setting, then we should do the same here.
As a longer goal language should be done by
1. client sends a language
2. user sets it in its own settings
3. admin defines language
--> but this we can and should discuss somewhere else

2020-07-07 16:09 UTC, jancborchardt commented
Some first quick design review @georgehrke just pasting here since I’m about to leave the office (and internet connection with that ;)

- [ ] App icon: Just use away icon?
- [ ] Default status is "Invisible"? Bit unclear
- [ ] Wording: "Set a status" → "Set status"
- [ ] After state is set for the first time, display the value like "Online", not still "Set status"
- [ ] Status title line is a bit off to the right
- [ ] "Clear status after" instead of "Clear status at" ("after today", "after 30 minutes", "after this week" etc)
- [ ] "Don’t clear" vs "Never", should be the same wording
- [ ] Manually setting the expiration results in "Select option" to be displayed in the select
- [ ] Emoji not reflected in the user menu, should be before the text?

2020-07-17 08:39 UTC, georgehrke commented
> Emoji not reflected in the user menu, should be before the text?

I tried that, but it didn't really convince me:
![07A91CA0-6C87-4D79-AD9A-4B0AEEF77E95](https://user-images.githubusercontent.com/1250540/87766647-c69ae900-c819-11ea-9f02-ef8bc9ad97ac.png)

2020-07-17 11:20 UTC, georgehrke commented on package.json
> +    "@nextcloud/vue": "^2.2.0",
TODO: remove me.
Requires https://github.com/nextcloud/server/pull/21867

2020-07-23 09:22 UTC, georgehrke commented on package.json
> +    "@nextcloud/vue": "^2.2.0",
Done

2020-07-23 13:28 UTC, georgehrke commented
The material icons are still missing attributions. Do we have a central place for that?

2020-07-24 07:47 UTC, rullzer commented on apps/user_status/lib/Service/PredefinedStatusService.php
> +					'time' => 1800,
I love the optimism here ;)

2020-07-24 07:49 UTC, rullzer commented on apps/user_status/lib/Service/PredefinedStatusService.php
> +				'message' => $this->l10n->t('In a meeting'),
ANy reason not the use the function for translations down below? Just so that we don't run into the issue with the same string in multiple places if this ever needs chaging?

2020-07-24 07:51 UTC, rullzer approved these changes
Nice clean code. And works as advertised. Gave it a spin lets get it in!

2020-07-24 08:14 UTC, MorrisJobke approved these changes
Really nice 👍 Only problem is that this is only usable by admin accounts. I highlighted the controller methods that were missing an `@NoAdminRequired` annotation.

Also where can I see those statuses? Or is this not yet in?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/PredefinedStatusController.php
> +	 * @return DataResponse
`@NoAdminRequired`?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/StatusesController.php
> +	public function findAll(?int $limit=null, ?int $offset=null): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/StatusesController.php
> +	public function find(string $userId): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function getStatus(): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function setStatus(string $statusType): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function setPredefinedMessage(string $messageId,
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function setCustomMessage(?string $statusIcon,
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function clearStatus(): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/lib/Controller/UserStatusController.php
> +	public function clearMessage(): DataResponse {
`@NoAdminRequired` ?

2020-07-24 08:14 UTC, MorrisJobke commented on apps/user_status/tests/Unit/Controller/UserStatusControllerTest.php
> +			['busy', '👨🏽‍💻', 'Busy developing the status feature', 500, true, false, null, false, null],
😆

2020-07-24 08:16 UTC, georgehrke commented on apps/user_status/lib/Controller/PredefinedStatusController.php
> +	 * @return DataResponse
Good catch. Let me quickly fix this.

2020-07-24 08:23 UTC, MorrisJobke commented
> Also where can I see those statuses? Or is this not yet in?

Seen it - it's in the followup list

2020-07-24 08:25 UTC, georgehrke commented
> Seen it - it's in the followup list

Added to the follow up list

2020-07-24 10:16 UTC, MorrisJobke commented
Only one more thing:

* [ ] if you are not an admin the menu is shorter and thus it causes a scrollbar to be added when opening the status submenu and the option for a custom status is hidden behind it.

![Bildschirmfoto 2020-07-24 um 12 15 16](https://user-images.githubusercontent.com/245432/88381836-7daddc00-cda7-11ea-85e5-7112cb8c57ff.png)
![Bildschirmfoto 2020-07-24 um 12 15 20](https://user-images.githubusercontent.com/245432/88381839-7f779f80-cda7-11ea-8850-9d325a77f73c.png)
![Bildschirmfoto 2020-07-24 um 12 15 25](https://user-images.githubusercontent.com/245432/88381841-80103600-cda7-11ea-94f7-63562c76b4a1.png)

2020-07-24 10:30 UTC, georgehrke commented
![0440A358-7559-4631-826D-9382734A8F53](https://user-images.githubusercontent.com/1250540/88382292-70452180-cda8-11ea-8ba1-1bef1dc34549.png)

On very small screens, the scrollbar is needed, so a simple `overflow-y:visible` won't do.
The proper solution would be appending the popover to the body.

@ma12-co Any progress on https://github.com/nextcloud/nextcloud-vue/issues/641? :)

2020-07-24 12:46 UTC, juliusknorr requested changes
Just some smaller comments, really nice otherwise :+1:

2020-07-24 12:46 UTC, juliushaertl commented on apps/user_status/src/App.vue
> +			this.mouseMoveListener = debounce(() => {
More a general thing: It would probably be nice to have some global events on the event bus for this, so the logic could be reused by individual apps. Not for this PR of course :wink:

2020-07-24 12:46 UTC, juliushaertl commented on apps/user_status/appinfo/info.xml
> +            <order>-1</order>
:see_no_evil: Maybe rearange the others and give it a order of 0 ?

2020-07-24 12:46 UTC, juliushaertl commented on apps/user_status/src/components/SetStatusModal.vue
> +					:value="message">
Should probably be a v-model since otherwise the custom message is never updated and never reaches the server when updating it.

2020-07-25 13:48 UTC, jancborchardt requested changes
Some design issues – but can also go in a follow-up, your call @georgehrke:
- [ ] The overlap circle should also be shown overlaid on the bottom right of your own avatar in the header so you directly see which status you have. Is this coming in a follow-up with the integration into Talk and the user menu?
- [x] It’s impossible to set one of the custom status suggestions by only using the keyboard, enter has no effect (the emoji picker can also not be entered by the way)
- [x] When changing the status (Online, Away, etc), the colored circle/icon has a loading spinner for a split second. This actually makes the app seem slower than it is. Instead, there should not be a spinner but just immediate change of the icon.
- [x] In the custom status suggestion list, "Working remotely" should be sorted 3rd in list, between "Commuting" and "Out sick" since these days it’s a more common occurence. :) 
- [ ] There’s an alignment issue with short names, should always left-align with the other text entries below:
    ![image](https://user-images.githubusercontent.com/925062/88458780-b70e4680-ce90-11ea-866a-41dde132f41e.png)

2020-07-26 17:25 UTC, ma12-co commented
> @ma12-co Any progress on nextcloud/nextcloud-vue#641? :)

@georgehrke I tried and failed :(

2020-07-31 11:47 UTC, juliusknorr approved these changes
Did some quick tests and the code looks sane :+1:

2020-07-31 12:12 UTC, georgehrke commented
Rebased to fix merge conflicts.
Will merge once CI is done.

2020-07-31 12:46 UTC, nickvergessen commented on apps/user_status/lib/AppInfo/Application.php
> +		$initialState->provideLazyInitialState(self::APP_ID, 'status', static function () use ($appContainer) {
could be done in `BeforeTemplateRenderedListener` as well? There is no need to initialState something when we are not using it.

2020-07-31 12:49 UTC, nickvergessen commented on apps/user_status/lib/BackgroundJob/ClearOldStatusesBackgroundJob.php
> +		$this->setInterval(60 * 15);
lets do it every time the cron runs? So just set it to 1 minute?

2020-07-31 13:03 UTC, nickvergessen requested changes
Autoloader check and commit missing for the app

2020-07-31 13:06 UTC, georgehrke commented on apps/user_status/src/App.vue
> +					{{ $t('user_status', 'Set custom status') }}
Because we are doing it wrong everywhere. 

https://vuejs.org/v2/cookbook/adding-instance-properties.html#The-Importance-of-Scoping-Instance-Properties

If you add properties to the prototype, you are supposed to prefix them with `$` to avoid conflicts.

2020-07-31 13:06 UTC, georgehrke commented on apps/user_status/src/App.vue
> +					{{ $t('user_status', 'Set custom status') }}
There is also an issue about it here: https://github.com/nextcloud/nextcloud-vue/issues/586

2020-07-31 13:09 UTC, georgehrke commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	public function heartbeat(string $status): JSONResponse {
Yes, that's on purpose.
It's only needed for the browser heartbeat.

We decided that mobile files apps should not trigger status changes at the moment.
Mobile talk apps will have to be handled by emitting the `UserLiveStatusEvent` in the Talk app.

2020-07-31 13:13 UTC, nickvergessen commented on apps/user_status/src/App.vue
> +					{{ $t('user_status', 'Set custom status') }}
Bothers me to have it "fixed" in one app. For the sake of maintainability I would prefer to have `t` for now until we update all usages at once.

2020-07-31 13:16 UTC, nickvergessen commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	public function heartbeat(string $status): JSONResponse {
But the Talk server app doesn't know if the user is "away"  or not. We just know the client is asking for messages e.g. but anyway, lets see later.

2020-07-31 13:16 UTC, georgehrke commented on apps/user_status/src/App.vue
> +					{{ $t('user_status', 'Set custom status') }}
Plenty of apps are doing it correctly already. Calendar, Tasks, Privacy, ...

2020-07-31 13:21 UTC, nickvergessen commented
The invisible icon is black on dark background when dark theme is used.

2020-07-31 13:22 UTC, georgehrke commented
> The invisible icon is black on dark background when dark theme is used.

Added to follow up list in PR description.

2020-07-31 13:23 UTC, nickvergessen commented
![Bildschirmfoto von 2020-07-31 15-22-10](https://user-images.githubusercontent.com/213943/89039095-c8989800-d341-11ea-8c8e-d1f9be456b81.png)

"Clear status after" overflows the modal

2020-07-31 13:26 UTC, nickvergessen commented
Pressing enter while filling "What's your status" reloads the page instead of saving the status.

2020-07-31 13:58 UTC, georgehrke commented
/compile amend /

2020-07-31 14:31 UTC, nickvergessen approved these changes
:shark: let's go

2020-07-31 15:25 UTC, merged

2020-07-31 15:49 UTC, jancborchardt commented
Wooohooo congrats @georgehrke! :))) 

@juliushaertl we can continue with the Status integration in Dashboard. ;)