OC.routing is just a @nextcloud/routing proxy
nextcloud/server pull request #21191
Opened 2020-06-02 12:11 UTC by rullzer

So lets kill the duplicate code!

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2020-06-02 12:24 UTC, georgehrke requested changes

2020-06-02 12:24 UTC, georgehrke commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
We should just export linkTo from nc/router instead of redeclaring it

2020-06-02 12:26 UTC, rullzer commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
Does it matter much?
Right now this file is just a proxy (and all the other stuff is there). Hopefully we can kill it at some point anyways. This way we could even add deprecation messages everywhere quickly.

2020-06-02 12:31 UTC, georgehrke commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
It would be much shorter:
```javascript
import {
	linkTo,
	router.generateRemoteUrl as linkToRemote,
	...
} from '@nextcloud/router'

export {
	linkTo,
	linkToRemote,
	...
}
```

2020-06-02 12:31 UTC, ChristophWurst approved these changes
:+1: for the change

:popcorn: for jsunit results

2020-06-02 12:31 UTC, ChristophWurst commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
Both should be fine. The direct assignment is OK if the API is identical. This is the case right now.

2020-06-02 12:39 UTC, rullzer commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
AH like that. Yeah I mean we could. But as I said probably we'd want to deprecate this with some message soonish as well.

2020-06-02 12:40 UTC, georgehrke approved these changes

2020-06-02 12:40 UTC, georgehrke commented on core/src/OC/routing.js
> +export const linkTo = (app, file) => router.linkTo(app, file)
Fine by me :)

2020-06-03 12:10 UTC, ChristophWurst approved these changes

2020-06-04 17:01 UTC, merged