fix #21285
nextcloud/server pull request #21288
Opened 2020-06-07 14:41 UTC by lmamane

2020-06-07 14:44 UTC, lmamane commented
This fixes issue #21285 but I cannot figure out how to add it to linked issue. I followed the github documentation at https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue, but:
1. "Linked issues" is not clickable, the doc says to click there.
1. The "fix #21285" in the description didn't do it either.

2020-06-07 17:37 UTC, kesselb commented
Thanks for debugging :+1: 

Change makes sense to me. We need some changes for the tests. I will have a look later.

2020-06-08 07:00 UTC, ChristophWurst requested changes
Fine from a functionality PoV, but a bit problematic in terms of code quality

Let's make it a bit less error-prone at least

2020-06-08 07:00 UTC, ChristophWurst commented on lib/private/Authentication/LoginCredentials/Store.php
> +			return new Credentials($creds->uid, $this->session->get('loginname'), $creds->password);
This is a bit of a red flag for me as this `loginname` value from the session is set elsewhere. So this relies on a few assumptions, making the code harder to understand and introducing undocumented dependencies between this code and the code that sets the value.

However, I see that we also use this same value in other places. That does not excuse the anti pattern, but it feels a bit less dirty.

In any case, can we maybe add a fallback to the UID when the session value is not there? Like ``$this->session->get('loginname') ?? $this->uid``?

2020-06-08 09:10 UTC, lmamane commented
On Mon, Jun 08, 2020 at 12:01:04AM -0700, Christoph Wurst wrote:
> @ChristophWurst requested changes on this pull request.

> Fine from a functionality PoV, but a bit problematic in terms of code quality

I had started a bigger change, that would have added the loginname to
the associative array (key-value pair set) returned by
$this->session->get('login_credentials')
This entailed changing the event that sets login_credentials, namely
('OC_User', 'post_login'), and also ('\OC\User', 'postLogin') to add
this parameter. However, I wasn't sure if that would touch a
guaranteed stable public API (e.g. for apps) or not.

Changing the ('OC_User', 'post_login') looked rather safe, since it
gives an associative array; changing ('\OC\User', 'postLogin') looked
non-backwards compatible (since it gives multiple parameters, not a
single associative array) _but_ it looked like it could be a private
internal API, and changing all listeners within Nextcloud itself would
be sufficient? But I wasn't sure.

Then I saw this code pattern
$this->session->get('loginname')
elsewhere in the code and thought "ah, that's how they do it".

If you tell me my first idea was better, and that the "public API"
worries are unfounded, I will gladly submit a new pull request based
in that.

Please let me know.

> > @@ -112,7 +112,7 @@ public function getLoginCredentials(): ICredentials {
>
>  		if ($trySession && $this->session->exists('login_credentials')) {
>  			$creds = json_decode($this->session->get('login_credentials'));
> -			return new Credentials($creds->uid, $creds->uid, $creds->password);
> +			return new Credentials($creds->uid, $this->session->get('loginname'), $creds->password);

> This is a bit of a red flag for me as this `loginname` value from
> the session is set elsewhere. So this relies on a few assumptions,
> making the code harder to understand and introducing undocumented
> dependencies between this code and the code that sets the value.

> In any case, can we maybe add a fallback to the UID when the session
> value is not there? Like ``$this->session->get('loginname') ??
> $this->uid``?

I would not put a fallback to a value that is a wrong one, and
systematically so in some scenarios (such as LDAP external
authentication with uid != loginname). That already created a subtle
and hard to track bug (app tokens would work for a few minutes and
then silently stop working...), I don't think keeping such things in
the codebase is a good idea. If we cannot get the loginname, then we
can return an _exception_, or maybe the value null?

2020-06-08 09:31 UTC, kesselb commented
> Then I saw this code pattern
$this->session->get('loginname')

https://github.com/nextcloud/server/blame/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/apps/encryption/lib/Controller/SettingsController.php#L116-L120

Seems the encryption app run into a similar issue before. Adding the loginName to the event sounds good but is quite hard to backport.

2020-06-08 09:42 UTC, lmamane commented
On the "hard to backport" part, we could imagine having this one-liner fix in the stable branches, and the event change in master?

2020-06-09 17:25 UTC, ChristophWurst commented
> On the "hard to backport" part, we could imagine having this one-liner fix in the stable branches, and the event change in master?

Fine by me

2020-06-20 09:38 UTC, lmamane commented on lib/private/Authentication/LoginCredentials/Store.php
> +			return new Credentials($creds->uid, $this->session->get('loginname'), $creds->password);
(addresses in main thread)

2020-06-20 10:50 UTC, lmamane commented
> > On the "hard to backport" part, we could imagine having this one-liner fix in the stable branches, and the event change in master?
> Fine by me

My current patch backports easily to stable19 branch. After you are happy with the current patch, let me know what version you want on stable19 (event change or "dirty" one-liner).

2020-06-20 13:19 UTC, kesselb requested changes
camelCase ;)

2020-06-20 13:19 UTC, kesselb commented on lib/public/User/Events/PostLoginEvent.php
> +		return $this->login_name;
```suggestion
		return $this->loginName;
```
?

2020-06-20 13:19 UTC, kesselb commented on lib/private/Server.php
> +			$userSession->listen('\OC\User', 'postLogin', function ($user, $login_name, $password, $isTokenLogin) {
```suggestion
			$userSession->listen('\OC\User', 'postLogin', function ($user, $loginName, $password, $isTokenLogin) {
```

2020-06-20 13:19 UTC, kesselb commented on lib/private/Server.php
> +				\OC_Hook::emit('OC_User', 'post_login', ['run' => true, 'uid' => $user->getUID(), 'login_name' => $login_name, 'password' => $password, 'isTokenLogin' => $isTokenLogin]);
```suggestion
				\OC_Hook::emit('OC_User', 'post_login', ['run' => true, 'uid' => $user->getUID(), 'loginName' => $loginName, 'password' => $password, 'isTokenLogin' => $isTokenLogin]);
```

2020-06-20 13:19 UTC, kesselb commented on lib/private/Authentication/LoginCredentials/Store.php
> +			return new Credentials($creds->uid, $creds->login_name, $creds->password);
```suggestion
			return new Credentials($creds->uid, $creds->loginName, $creds->password);
```

2020-06-23 21:35 UTC, blizzz commented on lib/public/User/Events/PostLoginEvent.php
> +	public function __construct(IUser $user, string $loginName, string $password, bool $isTokenLogin) {
FYI, we cannot backport this as it breaks public API.

2020-07-06 21:02 UTC, MorrisJobke commented
> My current patch backports easily to stable19 branch. After you are happy with the current patch, let me know what version you want on stable19 (event change or "dirty" one-liner).

The one liner.

2020-07-09 14:39 UTC, MorrisJobke commented
> > My current patch backports easily to stable19 branch. After you are happy with the current patch, let me know what version you want on stable19 (event change or "dirty" one-liner).
> 
> The one liner.

Stable19: #21779

2020-08-20 14:00 UTC, MorrisJobke approved these changes
Code looks good 👍

2020-08-20 14:02 UTC, MorrisJobke commented
Rebased to fix a conflict.

2020-08-24 12:59 UTC, ChristophWurst approved these changes

2020-08-28 14:11 UTC, merged