convert text to single line so tabs in translation issue is fixed
nextcloud/server pull request #2131
Opened 2016-11-15 10:24 UTC by jancborchardt

Please review @MorrisJobke @LukasReschke

2016-11-15 18:00 UTC, rullzer commented on settings/templates/personal.php
> +			<?php print_unescaped($l->t('If you want to support the project <a href="https://nextcloud.com/contribute" target="_blank" rel="noreferrer">join development</a> or <a href="https://nextcloud.com/c
Mmm we should split this up. Translating html stuff is bad. I'll take care

2016-11-15 23:58 UTC, MorrisJobke requested changes

2016-11-15 23:58 UTC, MorrisJobke commented on settings/templates/personal.php
> +				$l->t('spread the word') . '</a>' . '!');?>
This will not work out with other languages. 😢

2016-11-16 08:30 UTC, rullzer commented on settings/templates/personal.php
> +				$l->t('spread the word') . '</a>' . '!');?>
Yeah I was still not sure. But adding HTML to the translation string is asking for trouble.

2016-11-16 09:35 UTC, rullzer commented on settings/templates/personal.php
> +				$l->t('spread the word') . '</a>' . '!');?>
done

2016-11-16 10:31 UTC, jancborchardt commented
@rullzer @MorrisJobke does the HTML stuff need to be fixed in the firstrunwizard then as well? https://github.com/nextcloud/firstrunwizard/commit/8a6df421b1a03b265afce744a8f9f81248db8f19

2016-11-16 10:49 UTC, rullzer commented
@jancborchardt yeah would be better

2016-11-16 18:18 UTC, nickvergessen commented
Looks good 👍

2016-11-16 21:12 UTC, jancborchardt commented
@rullzer can you take care of it since you did it here too? :)

2016-11-16 21:12 UTC, jancborchardt commented
Also review please @MorrisJobke @rullzer

2016-11-16 22:25 UTC, merged