Upload part size as S3 parameter instead of constant value
nextcloud/server pull request #21317
Opened 2020-06-08 15:40 UTC by FlorentCoppint

Some S3 providers need a custom upload part size (500 MB static value in Nextcloud).

Here is a commit to change this value via S3 configuration, instead of using S3_UPLOAD_PART_SIZE constant.

A new parameter is added for an S3 connection : upload_part_size

Signed-off-by: Florent Bautista <florent@coppint.com>

2020-06-08 21:23 UTC, kesselb reviewed
Thanks :+1:

2020-06-08 21:23 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +	protected $upload_part_size;
```suggestion
	protected $uploadPartSize;
```

2020-06-08 21:23 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +	protected $upload_part_size;
Please use camelCase for variables here.

2020-06-08 21:23 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$this->upload_part_size = !isset($params['upload_part_size']) ? 524288000 : $params['upload_part_size'];
Also here for variable and param.

2020-06-08 21:25 UTC, kesselb commented
If possible please squash the commits and add the signoff. 

As per https://github.com/nextcloud/server/pull/21317/checks?check_run_id=750683865 

`git commit --amend --signoff`
`git push --force-with-lease origin s3_upload_part_size` 

should be enough but that might change with additional commits.

2020-06-09 06:46 UTC, FlorentCoppint commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$this->upload_part_size = !isset($params['upload_part_size']) ? 524288000 : $params['upload_part_size'];
> Also here for variable and param.

Hi, are you sure for parameter name ? A lot of parameters are using "underscore style" in Nextcloud

2020-06-09 06:52 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$this->upload_part_size = !isset($params['upload_part_size']) ? 524288000 : $params['upload_part_size'];
https://docs.nextcloud.com/server/19/developer_manual/general/codingguidelines.html#objects-functions-arrays-variables

2020-06-09 09:49 UTC, FlorentCoppint commented
Do I have something to do about failed Continuous Integration test ?

2020-06-09 09:58 UTC, kesselb commented
> Do I have something to do about failed Continuous Integration test ?

I don't think so.

2020-06-09 14:08 UTC, icewind1991 approved these changes
Fine by me :+1:

2020-06-09 14:23 UTC, rullzer requested changes
Can you also update the config.sample.php?

2020-06-09 14:30 UTC, FlorentCoppint commented
> Can you also update the config.sample.php?

I can, but there is no S3 example configuration in config.sample.php :( 
The feature "S3 as primary storage" is explained in documentation, not in config.sample.php

2020-06-09 17:28 UTC, rullzer commented
> > Can you also update the config.sample.php?
> 
> I can, but there is no S3 example configuration in config.sample.php :(
> The feature "S3 as primary storage" is explained in documentation, not in config.sample.php

ah mm goodpoint

2020-06-09 17:28 UTC, rullzer approved these changes

2020-06-09 17:28 UTC, merged

2020-06-15 08:38 UTC, FlorentCoppint commented
/backport to stable19