Dashboard API
nextcloud/server pull request #21346
Opened 2020-06-09 17:02 UTC by juliushaertl

This PR is the first part of the planned dashboard work. For now it contains the following parts:

- Deprecating the old dashboard API
- Add a simplified new API as proposed in #20930 
- Add a new dashboard app that mainly takes care of providing dom elements so that apps can render their own views into it.

A reference panel implementation can be found in https://github.com/nextcloud/recommendations/pull/229

Required steps for implementing a panel as an app developer:

1. Create an Panel class implementing `\OCP\Dashboard\IPanel`
https://github.com/nextcloud/recommendations/pull/229/files#diff-48edb3423d2ffcb238266594991d33d8
2. Register the panel and load apps script 
https://github.com/nextcloud/recommendations/pull/229/files#diff-b8a11151e44bcffc222c5fddc9ab92c9R51-R55
3. Register the panel in the frontend and show your UI in the provided DOM element
https://github.com/nextcloud/recommendations/pull/229/files#diff-b64910aa4f3ca0b34cf6118a2efbda31R35-R45

Open points for discussion
- I for now also registered dashboard as default app if it is enabled as this would make it then the main entry point to Nextcloud, not sure if we want that in the end
- I would actually prefer to have it moved to the server repo especially if it would be the main entry point and as it is enabled by default
  - Updating Nextcloud with the new Dashboard app and the old one installed will need https://github.com/nextcloud/updater/pull/255 to make sure the app is properly replaced
  - With a spearate app directory, using the same app id as the current dashboard app should not be an issue if we have a higher app version available

2020-06-09 17:18 UTC, ChristophWurst commented on apps/dashboard/lib/Controller/DashboardController.php
> +		$this->eventDispatcher->dispatchTyped(new IRegisterPanelEvent($this->dashboardManager));
I'm not a fan of abusing events for this. We should rather have a lazy and lightweight registration mechanism where apps can add their services and we fetch and load that lazily. https://github.com/nextcloud/server/issues/20930#issuecomment-641457131

2020-06-11 02:25 UTC, jancborchardt commented
Great work, added some design & layout fixes. Now just needs the panels (or mocks) for Calendar, Mail and Talk. :)

2020-06-16 08:23 UTC, ChristophWurst commented on apps/dashboard/src/App.vue
> +				return t('dashboard', '🌙 Time to call it a day')
Sorry for nitpicking on this non-technical issue but what about people that use the instance at night? Like people working a night shift? Isn't it strange that the software then tells you to *call it a day*?

I'm fine with a greeting that adjust to the time of day, but I would refrain from assumption about what the time means to the user in terms of active/inactive.

2020-06-16 08:48 UTC, juliushaertl commented on apps/dashboard/src/App.vue
> +				return t('dashboard', '🌙 Time to call it a day')
Agreed, we also should move the emojis into icons so they work fine on systems where no emoji font is installed and are not changed by translations.

@jancborchardt Any other wording suggestions?

2020-06-16 09:19 UTC, jancborchardt commented on apps/dashboard/src/App.vue
> +				return t('dashboard', '🌙 Time to call it a day')
Yeah, was thinking the same, especially as I was working on it in the evening / night. ;) Probably @juliushaertl’s original simple "Good evening" is better.

2020-06-17 08:37 UTC, rullzer commented on apps/dashboard/src/App.vue
> +				return t('dashboard', '🌙 Time to call it a day')
Maybe we add some ML when you are usually working. so it can greet your with good morning whenever you usually start working. So it just shifts your time of day :speak_no_evil:

2020-06-23 14:01 UTC, juliushaertl commented on apps/dashboard/lib/Controller/DashboardController.php
> +		$this->eventDispatcher->dispatchTyped(new IRegisterPanelEvent($this->dashboardManager));
Should be done now with afd6707, it would be cool if you could have a dedicated look at that commit ;)

I kept the event for now and still dispatch it, so that apps can register a panel in a lazy manner even if they don't have 20 as a min-version, but deprecated it right away with afdc5b7 so we can drop it once 19 is EOL.

2020-06-23 14:02 UTC, juliushaertl commented on apps/dashboard/lib/Controller/DashboardController.php
> +		$this->eventDispatcher->dispatchTyped(new IRegisterPanelEvent($this->dashboardManager));
[`088ca9f` (#229)](https://github.com/nextcloud/recommendations/pull/229/commits/088ca9f9bd6d0e4d8c5cea5cc76309b8185dd93c) for the recommendations part

2020-06-23 15:32 UTC, juliushaertl commented
Acceptance tests would still need some more work due to the new default app, but this should be good for a first review round until those are figured out. :wink:

2020-06-23 17:14 UTC, ChristophWurst commented on apps/dashboard/appinfo/info.xml
> +			<order>-1</order>
:eyes:

2020-06-23 17:14 UTC, ChristophWurst commented on apps/dashboard/lib/Controller/DashboardController.php
> +	public function __construct($appName, IRequest $request, IInitialStateService $initialStateService, IEventDispatcher $eventDispatcher, IManager $dashboardManager) {
nit: break the argument list into multiple lines

2020-06-23 17:14 UTC, ChristophWurst commented on apps/dashboard/lib/Controller/DashboardController.php
> +		if (class_exists(LoadViewer::class)) {
not ideal. I guess that needs a public API at some point :)

2020-06-23 17:14 UTC, ChristophWurst commented on apps/dashboard/src/App.vue
> +console.debug('Loading dashboard panels', panels)
:fire: ?

2020-06-23 17:14 UTC, ChristophWurst commented on lib/public/Dashboard/IManager.php
> +	 * @since 20.0.0
do you want to keep this one or should it be deprecated right away?

2020-06-23 17:14 UTC, ChristophWurst commented on lib/public/Dashboard/IPanel.php
> +	public function getIconClass(): string;
could you elaborate on *icon class* vs *icon url*? Both are not nullable, so mandatory?

2020-06-23 17:14 UTC, ChristophWurst commented on lib/public/Dashboard/IRegisterPanelEvent.php
> +	public function registerPanel(IPanel $panel) {
I would say we can do the lazy variant here as well, no?

2020-06-24 07:46 UTC, rullzer commented
> Acceptance tests would still need some more work due to the new default app, but this should be good for a first review round until those are figured out. wink

Maybe as discussed we don't add it as default just yet. only when we think it is ready?

2020-06-24 10:14 UTC, juliushaertl commented on lib/public/Dashboard/IPanel.php
> +	public function getIconClass(): string;
Actually let me drop the iconUrl for now since it is not used anywhere. It was part of the first batch with possible mobile integration in mind, but let's keep only things we need for now.

2020-06-24 10:58 UTC, juliushaertl commented on lib/public/Dashboard/IManager.php
> +	 * @since 20.0.0
Lets actually just remove that and make the actual implementation private as we can then do all registering lazy.

2020-06-24 11:09 UTC, juliushaertl commented on apps/dashboard/lib/Controller/DashboardController.php
> +		if (class_exists(LoadViewer::class)) {
Yes, although nothing for this PR. :wink:

2020-06-24 11:09 UTC, juliushaertl commented
> Maybe as discussed we don't add it as default just yet. only when we think it is ready?

Yes, I've dropped that for now and added it to the todo list for the next steps.

2020-06-24 11:10 UTC, juliushaertl commented on apps/dashboard/src/App.vue
> +				return t('dashboard', '🌙 Time to call it a day')
Changed to Good evening for now.

2020-06-24 11:17 UTC, ChristophWurst commented on apps/dashboard/lib/Controller/DashboardController.php
> +		if (class_exists(LoadViewer::class)) {
Ofc :)

2020-06-24 12:41 UTC, juliushaertl commented
/compile amend /

2020-06-25 13:06 UTC, ChristophWurst requested changes

2020-06-25 13:06 UTC, ChristophWurst commented on lib/private/Dashboard/Manager.php
> +				$panel = $this->serverContainer->query($class);
Let's address https://github.com/nextcloud/documentation/pull/2168#discussion_r445476423.

In the current implementation, apps are likely do run some stuff in their constructors, so you won't just potentially run into a `QueryException` here but any `Throwable`.

I'd say the event where apps should load their stuff can go into a dedicated life cycle method that is called.

2020-06-25 13:32 UTC, juliushaertl commented on lib/private/Dashboard/Manager.php
> +				$panel = $this->serverContainer->query($class);
Yes, I'll have another look :+1:

2020-06-26 14:13 UTC, ChristophWurst approved these changes

2020-06-26 14:13 UTC, ChristophWurst commented on lib/private/Dashboard/Manager.php
> +				$panel->load();
:+1: better :)

2020-06-26 14:14 UTC, ChristophWurst commented on lib/public/Dashboard/IPanel.php
> +	 * Execute panel bootstrap code like loading scripts and providing initial state
``@since 20.0.0`` missing

2020-07-07 09:56 UTC, juliushaertl commented
:ping_pong: for review again

2020-07-10 09:39 UTC, nickvergessen requested changes

2020-07-10 09:39 UTC, nickvergessen commented on apps/dashboard/lib/Controller/DashboardController.php
> +		$appName,
```suggestion
		string $appName,
```

2020-07-10 09:39 UTC, nickvergessen commented on apps/dashboard/src/App.vue
> +		<h2>{{ greeting.icon }} {{ greeting.text }}, {{ name }}</h2>
Please insert the name into the greeting text to make sure it works with translations

2020-07-10 09:39 UTC, nickvergessen commented on lib/private/Dashboard/Manager.php
> +/**
declare strict everywhere?

2020-07-10 09:39 UTC, nickvergessen commented on lib/public/Dashboard/RegisterPanelEvent.php
> + * @deprecated 20.0.0
:see_no_evil:

2020-07-10 09:41 UTC, ChristophWurst commented on lib/public/Dashboard/RegisterPanelEvent.php
> + * @deprecated 20.0.0
https://github.com/nextcloud/documentation/pull/2168/files#diff-26c275b03f37c6dec32beff2f86b69e5R126

2020-07-10 12:00 UTC, juliushaertl commented on lib/public/Dashboard/RegisterPanelEvent.php
> + * @deprecated 20.0.0
Let me add a comment to that so it is clear from the code as well ;)

2020-07-10 12:12 UTC, juliushaertl commented on lib/public/Dashboard/RegisterPanelEvent.php
> + * @deprecated 20.0.0
Ah is there already above

2020-07-10 15:12 UTC, nickvergessen approved these changes
:shark: 
Rebuild needed

2020-07-15 08:43 UTC, juliushaertl commented
/compile amend /

2020-07-15 08:55 UTC, juliushaertl commented
Ah it was the missing map file.

2020-07-15 09:10 UTC, merged

2020-07-15 12:08 UTC, MorrisJobke commented
Breaks master tests - let me fix them.

2020-07-15 12:09 UTC, MorrisJobke commented
> Breaks master tests - let me fix them.

https://github.com/nextcloud/server/pull/21849