Add Personal Share Notes
nextcloud/server pull request #21357
Opened 2020-06-10 09:32 UTC by gary-kim

Closes #21265

Still a work in progress.

2020-06-10 11:16 UTC, gary-kim commented
Umm... confused
![Screenshot_2020-06-10 Build #29713 13 5 - nextcloud server - Drone CI](https://user-images.githubusercontent.com/47195730/84261758-e706c200-ab4e-11ea-979d-f95b8cf63683.png)

2020-06-11 05:19 UTC, gary-kim commented
I was implementing a solution like this because, for example, my resume has 3 different share links that I have sent to different people, all read only and with no expiry. I needed to remove one of them but I had no way to know which one was for whom.

One idea, to maybe combine both options: could we have something where the note to self is more of a "share title"? If you don't put anything there, the message shown is what @jancborchardt came up with, but if you put a title, it shows that instead?

2020-06-11 05:47 UTC, gary-kim commented
Actually, looks like theres a TODO here. Could just implement that.

https://github.com/nextcloud/server/blob/264ce2146c42746dccc3f4f62371483e4ecdfdcd/apps/files_sharing/src/components/SharingEntryLink.vue#L404

2020-06-11 06:13 UTC, gary-kim commented
Oh wait, I didn't notice this, there's a label system for link shares already. Could we maybe just expose editing that to the user?

https://github.com/nextcloud/server/blob/264ce2146c42746dccc3f4f62371483e4ecdfdcd/apps/files_sharing/lib/Controller/ShareAPIController.php#L1087-L1089

cc @skjnldsv

2020-06-11 09:41 UTC, rullzer commented
> Oh wait, didn't notice this, there's a label system for link shares already. Could we maybe just expose editing that to the user?
> 
> https://github.com/nextcloud/server/blob/264ce2146c42746dccc3f4f62371483e4ecdfdcd/apps/files_sharing/src/components/SharingEntryLink.vue#L415-L417
> 
> https://github.com/nextcloud/server/blob/264ce2146c42746dccc3f4f62371483e4ecdfdcd/apps/files_sharing/lib/Controller/ShareAPIController.php#L1087-L1089
> 
> cc @skjnldsv

yes please!
Making this editable would be awesome!

The stuff that jan proposes is a next step I guess (having some context below the link)

2020-06-11 12:00 UTC, jancborchardt commented
> Oh wait, didn't notice this, there's a label system for link shares already. Could we maybe just expose editing that to the user?

Oh cool, sure. :) Then we could just show that note in parentheses behind like:

> Share link (for professor)
>
> Share link (for Alex)

This would then also work for the future if we get that subline with the further info.
Let’s make it a single input field instead of textarea to force people to keep it short. :)

2020-06-11 12:54 UTC, gary-kim commented
> Let’s make it a single input field instead of textarea to force people to keep it short. :)

To do that properly, a change will be required in nextcloud-vue as well. 

Also, I'm definitely not going to keep my messages short :)

2020-06-11 16:58 UTC, jancborchardt commented
> Also, I'm definitely not going to keep my messages short :)

Hehe ;D You’re free to do that of course, I just think that we have to keep in mind where they would need to be displayed – and those will likely be 1-line displays only mostly. Of course people can write more in an input field.

2020-06-12 12:30 UTC, gary-kim commented
Okay, this is what I've got now (turns out no upstream change is required :smile:  ):
![image](https://user-images.githubusercontent.com/47195730/84502629-4e597900-aceb-11ea-8bcf-483b25c86aa4.png)

2020-06-26 06:34 UTC, tobiasKaminsky commented
> Oh cool, sure. :) Then we could just show that note in parentheses behind like:
> 
> > Share link (for professor)
> > Share link (for Alex)

Isn't this some kind of redundant? User sees via icon and as they created it themselves that it is a share link.
So I would instead let the user replace the full text. 
This then also helps a bit with longer names.

Btw: I created a feature parity issue: https://github.com/nextcloud/server/issues/21593

2020-06-30 14:36 UTC, gary-kim commented
Thanks @tobiasKaminsky 

Also, ping for reviews?

2020-07-02 12:42 UTC, jancborchardt commented
> Isn't this some kind of redundant? User sees via icon and as they created it themselves that it is a share link.
> So I would instead let the user replace the full text.

Remember that not everyone spends so much time in Nextcloud as we do. :) So I would still say we should keep the "Share link" text and only put the label inside parentheses behind that.

2020-07-03 05:49 UTC, gary-kim commented
> That is, @gary-kim in your example the "for" is outside of the parentheses but it should not be, basically it’s:
> 
> > Share link (custom text here)

Okie, fixed

2020-07-06 10:06 UTC, tobiasKaminsky commented
On Android it looks like this:
![image](https://user-images.githubusercontent.com/5836855/86581920-17d8ec00-bf81-11ea-99ca-dc9bcc4e2731.png)

(with primary color themed to black)

2020-07-07 10:50 UTC, jancborchardt approved these changes
Looks good design-wise! :)

2020-07-07 12:41 UTC, skjnldsv commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +			<h5 :title="title">{{ title }}</h5>
I'm confused about this part! :thinking:

2020-07-07 12:42 UTC, skjnldsv commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +							defaultContainer: '#app-sidebar'
```suggestion
							defaultContainer: '#app-sidebar'
```

Not valid for `@nextcloud/vue` >= 2.0.0 https://github.com/nextcloud/nextcloud-vue/releases/tag/v2.0.0

2020-07-07 12:44 UTC, skjnldsv commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +						:placeholder="t('files_sharing', 'Enter who this share is for')"
Is this really what we want as a placeholder?
Also, could use a `ariaLabel` :)

2020-07-07 12:45 UTC, skjnldsv commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +			<h5 :title="title">{{ title }}</h5>
Ah, because of the `text-overflow: ellipsis` ?

2020-07-07 12:45 UTC, skjnldsv requested changes
See comments :)

2020-07-07 13:08 UTC, gary-kim commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +						:placeholder="t('files_sharing', 'Enter who this share is for')"
Yeah, probably could do better. I'll change it to `Share label`.

2020-07-07 13:09 UTC, gary-kim commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +			<h5 :title="title">{{ title }}</h5>
Yep.

2020-07-10 06:56 UTC, rullzer approved these changes
Good stuff! Seems to do the trick. I'm all for getting in and fixing small stuff later in followups!

2020-07-10 06:56 UTC, rullzer commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +						:placeholder="t('files_sharing', 'Share label')"
Share label sounds strange to me.... because well it is already a label. But for later concern.
However. I don't ever see this placeholder.....

2020-07-10 23:05 UTC, gary-kim commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +						:placeholder="t('files_sharing', 'Share label')"
Fixed

2020-07-13 13:39 UTC, gary-kim commented
Okay, otherwise good?

2020-07-14 02:04 UTC, gary-kim commented
Rebased

2020-07-14 07:24 UTC, merged

2020-07-14 09:13 UTC, jospoortvliet commented
Great work @gary-kim  - I think this will make a lot of users happy ;-)