Fix create SimpleFile with empty content
nextcloud/server pull request #21386
Opened 2020-06-12 17:46 UTC by d0niek

After that change https://github.com/nextcloud/server/pull/19493 where
you have to provide content to method `newFile` is a bug with empty `''`
content.

Php function `file_put_contents` will returns the numbers of bytes that
written to the file, or `FALSE` on failure
https://www.php.net/manual/en/function.file-put-contents.php

So for empty `''` content it will return `0` which is `true` for this
statement:

```
if (!$result) {
    throw new NotPermittedException('Could not create path');
}
```

From now empty content will not throws an exception.

2020-06-12 20:58 UTC, kesselb commented
Thanks :+1: 

That looks danger. If the underlying storage is an object store for example the result might be true instead of 0. The storage adapter "local" should be changed to follow the interface and return a boolean always.

https://github.com/nextcloud/server/blob/6b2674478770e1b09aedc4e32613a4e01f9075b9/lib/private/Files/Storage/Local.php#L272-L274

2020-06-15 07:03 UTC, rullzer approved these changes
Looks good.
Would you mind also adding a test case?

2020-06-15 07:24 UTC, rullzer requested changes
Ah woops. Yes @kesselb is right. Please modify the local storage to behave properly.

2020-06-15 09:18 UTC, d0niek commented
The same "problem" is here: https://github.com/nextcloud/server/blob/6b2674478770e1b09aedc4e32613a4e01f9075b9/lib/private/Files/Storage/Common.php#L205-L211
Implementation is not Ok with the interface: https://github.com/nextcloud/server/blob/6b2674478770e1b09aedc4e32613a4e01f9075b9/lib/public/Files/Storage.php#L229-L237.
I can fix it but is it Ok? Origin `file_put_contents` return how much bytes were written and maybe someone wants to compare it with data sent to the method?

What about test case, I can write it too but there aren't any test cases with content so should I write them too?

2020-08-20 14:04 UTC, MorrisJobke commented
Another fix went into master already: #22237

2020-08-20 14:04 UTC, closed without merging