Fix modal support for vue apps
nextcloud/server pull request #21417
Opened 2020-06-15 15:01 UTC by nickvergessen

* Fixes missing modal background for vue apps `#content` vs `.content`
* Makes confirmDestructive a modal by default
* Makes the modal darkmode compatible (black overlaying black is not too useful, so I use the font color now)

Before | After
---|---
![Bildschirmfoto von 2020-06-15 17-00-36](https://user-images.githubusercontent.com/213943/84673317-d75df380-af29-11ea-8ff9-056eb9fffdfd.png) | ![Bildschirmfoto von 2020-06-15 17-00-25](https://user-images.githubusercontent.com/213943/84673314-d5943000-af29-11ea-8dc7-e7bf20188d51.png)

2020-06-15 15:06 UTC, nickvergessen commented
/backport to stable19

2020-06-15 15:06 UTC, nickvergessen commented
/backport to stable18

2020-06-15 16:14 UTC, ChristophWurst approved these changes
:elephant:

2020-06-15 16:29 UTC, gary-kim approved these changes
Seems fine to me

2020-06-15 18:45 UTC, jancborchardt approved these changes
Seems good!

2020-06-16 04:14 UTC, skjnldsv commented on core/src/jquery/css/jquery.ocdialog.scss
> +	background-color: var(--color-main-text);
No, because then it will be reverted on dark theme.
We still want a dark opacity on dark mode

2020-06-16 04:14 UTC, skjnldsv approved these changes
Small change, otherwise good! :+1:

2020-06-16 05:05 UTC, nickvergessen commented on core/src/jquery/css/jquery.ocdialog.scss
> +	background-color: var(--color-main-text);
But that is exactly my issue. Depending on the page content you couldn't notice that it was being overlayed and clicking anywhere on the overlay dismisses it.
I'm fine with using another grey value or something overlaying with the background color doesn't work

2020-06-16 06:22 UTC, nickvergessen commented on core/src/jquery/css/jquery.ocdialog.scss
> +	background-color: var(--color-main-text);
No overlay | black | white
---|---|---
![Bildschirmfoto von 2020-06-16 08-18-35](https://user-images.githubusercontent.com/213943/84738558-67438200-afaa-11ea-9e4c-ad88e56ab9c8.png) | ![Bildschirmfoto von 2020-06-16 08-18-26](https://user-images.githubusercontent.com/213943/84738554-6579be80-afaa-11ea-80b1-46355f36da2a.png) | ![Bildschirmfoto von 2020-06-16 08-18-08](https://user-images.githubusercontent.com/213943/84738547-64489180-afaa-11ea-838f-b1f04eeeaaac.png)

2020-06-16 06:27 UTC, nickvergessen commented on core/src/jquery/css/jquery.ocdialog.scss
> +	background-color: var(--color-main-text);
Maybe 0.8 instead of 0.2 overlay on darkmode would be an option?

0.2 | 0.8
---|---
![Bildschirmfoto von 2020-06-16 08-18-26](https://user-images.githubusercontent.com/213943/84739063-3adc3580-afab-11ea-864d-3475fbd92a9a.png) | ![Bildschirmfoto von 2020-06-16 08-25-52](https://user-images.githubusercontent.com/213943/84739006-239d4800-afab-11ea-93ec-669fd7e116b7.png)

2020-06-16 09:17 UTC, jancborchardt requested changes
Good call with the 0.8 instead of 0.2 overlay – looks much better than a bright backdrop.

2020-06-16 09:17 UTC, jancborchardt commented on core/src/jquery/css/jquery.ocdialog.scss
> +	background-color: var(--color-main-text);
The darker overlay with 0.8 looks much better for dark mode than the text-color one @nickvergessen, good one! :+1:

2020-06-17 13:00 UTC, jancborchardt approved these changes
Looks great now! :)

2020-06-17 13:35 UTC, merged

2020-06-23 12:28 UTC, nickvergessen commented
Backports done manually:
https://github.com/nextcloud/server/pull/21541
https://github.com/nextcloud/server/pull/21543