getXbyY can still return false, e.g. when using ldap write support
nextcloud/server pull request #21421
Opened 2020-06-15 19:52 UTC by blizzz

To reproduce: 
1. have ldap_write_support on master (e.g. from https://github.com/nextcloud/ldap_write_support/pull/165)
2. try to create a user
3. You'll get an error message and an exception logged saying "Translation to LDAP DN unsuccessful"

2020-06-15 19:52 UTC, blizzz commented
/backport to stable19

2020-06-16 08:20 UTC, ChristophWurst requested changes

2020-06-16 08:20 UTC, ChristophWurst commented on apps/user_ldap/lib/Mapping/AbstractMapping.php
> +		if ($dn === false && $dn = $this->getXbyY('ldap_dn', 'owncloud_name', $name)) {
IMO this looks like an accidental assignment. How about

```suggestion
		if ($dn === false && ($dn = $this->getXbyY('ldap_dn', 'owncloud_name', $name)) !== false) {
```

2020-06-16 08:55 UTC, blizzz commented on apps/user_ldap/lib/Mapping/AbstractMapping.php
> +		if ($dn === false && $dn = $this->getXbyY('ldap_dn', 'owncloud_name', $name)) {
it's more verbose. The method returns either string or false. But of course it makes sense when otherwise it looks confusing :)

2020-06-16 08:56 UTC, ChristophWurst approved these changes

2020-06-19 14:59 UTC, kklem0 approved these changes

2020-06-19 18:01 UTC, merged