Use the correct mountpoint to calculate
nextcloud/server pull request #21489
Opened 2020-06-19 14:28 UTC by rullzer

If we use the owners mount point this results in null. And then the rest
of the checks get called with null. Which doesn't work.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2020-06-23 07:08 UTC, ChristophWurst approved these changes

2020-06-23 09:52 UTC, danxuliu requested changes
[Unit tests need to be adjusted](https://drone.nextcloud.com/nextcloud/server/29975/11/4).

2020-06-23 09:52 UTC, danxuliu commented on lib/private/Share20/Manager.php
> +				throw new \Exception('Could not get proper user mount for ' . $userMountPointId . '. Failing since else the next calls are called with null');
This should be a `GenericShareException`, or [it should be documented that `generalCreateChecks` can throw](https://github.com/nextcloud/server/blob/69eda9c0f6a3f0128475cde8f9e021c71677c51d/lib/private/Share20/Manager.php#L212-L213) a plain `Exception` too.

2020-06-29 11:40 UTC, nickvergessen commented
Looking into the tests now

2020-06-29 13:27 UTC, nickvergessen commented
Tried my best but this is so … up.
The tests are creating Local storages and initialising the view on them, without going through any layers, so of course when we check the database later on for related storages/mount points the list is empty and therefor the share fails.

2020-07-09 08:50 UTC, nickvergessen approved these changes
:shark: Time to fix up

2020-07-09 10:57 UTC, merged

2020-07-09 10:57 UTC, nickvergessen commented
Backports I guess @rullzer

2020-07-09 11:26 UTC, rullzer commented
Yes

2020-07-09 12:27 UTC, rullzer commented
/backport to stable19

2020-07-09 12:27 UTC, rullzer commented
/backport to stable18

2020-07-09 12:27 UTC, rullzer commented
/backport to stable17