add explanatory text of what to do on app version error
nextcloud/server pull request #2153
Opened 2016-11-16 10:48 UTC by jancborchardt

Please review @nickvergessen @rullzer @LukasReschke @MorrisJobke 

All warnings need an explanation of how to fix it. Otherwise people don’t know what to do and can’t fix the issue.

2016-11-16 10:51 UTC, jancborchardt commented
Btw @nickvergessen this error shows up one by one, for every incompatible app. Instead of fixing all at once I need to fix everyone one by one and refresh. Can we show all the apps which don’t work in one, as we do elsewhere too?

2016-11-16 11:28 UTC, nickvergessen commented
> this error shows up one by one, for every incompatible app. Instead of fixing all at once I need to fix everyone one by one and refresh. Can we show all the apps which don’t work in one, as we do elsewhere too?

Fixed

2016-11-16 11:58 UTC, MorrisJobke requested changes

2016-11-16 11:58 UTC, MorrisJobke commented on lib/base.php
> +		/** @var \OC\App\AppManager $appManager */
Why?

2016-11-16 14:18 UTC, jancborchardt commented
@nickvergessen is it now the same block over again for every app? Can you make it this instead:

> The files of the following apps were not replaced correctly:
> - Activity (activity
> - Notifications (notifications)
> - PDF viewer (files_pdfviewer)
>
> Make sure the version is compatible with the server.

2016-11-16 18:21 UTC, nickvergessen commented
No, it's a comma separated list:
> The files of the app Activity (activity), Deleted files (files_trashbin) were not replaced correctly. Make sure it is a version compatible with the server.


That has to be enough, because we're not going to add HTML support to HintExceptions, because that will have dangerous outcomes on other ends.

2016-11-16 18:21 UTC, nickvergessen commented on lib/base.php
> +		/** @var \OC\App\AppManager $appManager */
Because the used method below is not in the public interface

2016-11-16 21:11 UTC, jancborchardt commented
@nickvergessen sounds good, thanks! :)

2016-11-16 21:11 UTC, jancborchardt commented
:+1:

2016-11-17 14:43 UTC, MorrisJobke commented
Tested and works 👍

2016-11-17 14:43 UTC, MorrisJobke approved these changes

2016-11-17 14:43 UTC, merged