Migrate WFE to the new bootstrap mechanism
nextcloud/server pull request #21547
Opened 2020-06-23 19:10 UTC by ChristophWurst

2020-06-23 20:05 UTC, kesselb commented on apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
> +		script('core', [
`OC_Util::addStyle` might work without the class exists hack ;)

2020-06-23 21:01 UTC, blizzz commented on apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
> +		script('core', [
which?

2020-06-23 21:20 UTC, blizzz requested changes
```json
{
  "reqId": "Fxy8iwmGMpA3GqFnVLBs",
  "level": 3,
  "time": "2020-06-23T21:17:44+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "master",
  "app": "no app in context",
  "method": "GET",
  "url": "/master/index.php/settings/user/workflow",
  "message": {
    "Exception": "OCP\\AppFramework\\QueryException",
    "Message": "Could not resolve OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListener! Class OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListener does not exist",
    "Code": 0,
    "Trace": [
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 116,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListener"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/ServerContainer.php",
        "line": 149,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListener",
          true
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 66,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->",
        "args": [
          "OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListener"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 251,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\WorkflowEngine\\Events\\LoadSettingsScriptsEvent"
          },
          "OCP\\WorkflowEngine::loadAdditionalSettingScripts",
          {
            "__class__": "Symfony\\Component\\EventDispatcher\\EventDispatcher"
          }
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 73,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          [
            {
              "__class__": "Closure"
            }
          ],
          "OCP\\WorkflowEngine::loadAdditionalSettingScripts",
          {
            "__class__": "OCP\\WorkflowEngine\\Events\\LoadSettingsScriptsEvent"
          }
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 86,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\WorkflowEngine\\Events\\LoadSettingsScriptsEvent"
          },
          "OCP\\WorkflowEngine::loadAdditionalSettingScripts"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/apps/workflowengine/lib/Settings/ASettings.php",
        "line": 87,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          "OCP\\WorkflowEngine::loadAdditionalSettingScripts",
          {
            "__class__": "OCP\\WorkflowEngine\\Events\\LoadSettingsScriptsEvent"
          }
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 141,
        "function": "getForm",
        "class": "OCA\\WorkflowEngine\\Settings\\ASettings",
        "type": "->",
        "args": []
      },
      {
        "file": "/srv/http/nextcloud/master/apps/settings/lib/Controller/PersonalSettingsController.php",
        "line": 76,
        "function": "formatSettings",
        "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
        "type": "->",
        "args": [
          [
            [
              {
                "__class__": "OCA\\WorkflowEngine\\Settings\\Personal"
              }
            ]
          ]
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 152,
        "function": "getSettings",
        "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
        "type": "->",
        "args": [
          "workflow"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/apps/settings/lib/Controller/PersonalSettingsController.php",
        "line": 67,
        "function": "getIndexResponse",
        "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
        "type": "->",
        "args": [
          "personal",
          "workflow"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 169,
        "function": "index",
        "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
        "type": "->",
        "args": [
          "workflow"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 100,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Settings\\Controller\\PersonalSettingsController"
          },
          "index"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/App.php",
        "line": 137,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Settings\\Controller\\PersonalSettingsController"
          },
          "index"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Settings\\Controller\\PersonalSettingsController",
          "index",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "section": "workflow",
            "_route": "settings.PersonalSettings.index"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "section": "workflow",
            "_route": "settings.PersonalSettings.index"
          }
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/Route/Router.php",
        "line": 297,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "section": "workflow",
            "_route": "settings.PersonalSettings.index"
          }
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/lib/base.php",
        "line": 1010,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/settings/user/workflow"
        ]
      },
      {
        "file": "/srv/http/nextcloud/master/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/srv/http/nextcloud/master/lib/private/AppFramework/Utility/SimpleContainer.php",
    "Line": 107,
    "CustomMessage": "Could not load event listener service OCA\\Workflowengine\\Listener\\LoadAdditionalSettingsScriptsListene [...]

2020-06-24 07:42 UTC, ChristophWurst commented
I forgot the autoloader update!

2020-06-24 08:44 UTC, blizzz commented
> I forgot the autoloader update!

i thought so. Weirldy enough, when i ran the checker locally last night, it didn't add the files :shrug:

2020-06-24 08:55 UTC, ChristophWurst commented
> i thought so. Weirldy enough, when i ran the checker locally last night, it didn't add the files

The namespace had incorrect casing.

I've rebased & squashed, including your changes :)

2020-06-24 09:13 UTC, ChristophWurst commented on apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
> +		script('core', [
Yeah, though unrelated to this change. Let's do it in a separate PR :)

2020-06-24 09:52 UTC, kesselb commented on apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php
> +		script('core', [
Fine by me ;)

2020-06-24 13:18 UTC, blizzz approved these changes

2020-07-02 19:02 UTC, rullzer approved these changes

2020-07-02 19:03 UTC, merged