Replace TYPE with TYPES
nextcloud/server pull request #21599
Opened 2020-06-26 17:51 UTC by kesselb

As TYPE::* is deprecated.

2020-06-26 18:16 UTC, ChristophWurst approved these changes

2020-06-26 18:16 UTC, ChristophWurst commented
I guess we should document this in the upgrade docs in case apps use it?

2020-06-27 16:51 UTC, gary-kim approved these changes
Yep, ran into this too

2020-06-30 10:16 UTC, rullzer requested changes
Block.

CI does :boom:

2020-06-30 14:06 UTC, nickvergessen commented on lib/private/DB/SQLiteMigrator.php
> +use Doctrine\DBAL\Types\Types as Type;
Error: Call to undefined method Doctrine\DBAL\Types\Types::getType() in /drone/src/lib/private/DB/SQLiteMigrator.php:87

2020-06-30 14:10 UTC, kesselb commented on lib/private/DB/SQLiteMigrator.php
> +use Doctrine\DBAL\Types\Types as Type;
Yep. I'm still undecided how to continue. The cleanest approach would be to not use an alias and migrate all references from `Type::BIGINT` (an others) to `Types::BIGINT`.

2020-06-30 20:21 UTC, kesselb commented
Second try ;)

2020-07-01 01:28 UTC, gary-kim commented
CI looks happy now

2020-07-02 10:21 UTC, merged