Anonymous options are fine
nextcloud/server pull request #21691
Opened 2020-07-05 08:47 UTC by rullzer

There is no reason to block those anonymous options requests. Right now they don't return anything. But they could at some point of course :wink:

2020-07-05 13:47 UTC, MorrisJobke commented
> There is no reason to block those anonymous options requests. Right now they don't return anything. But they could at some point of course 😉

You now made it block more and not less. Before it returned an empty response for anonymous request coming from office only. Now it does this for all anonymous requests. 🤔

2020-07-06 06:18 UTC, rullzer commented
Yeah. But before I threw a 403 now at least you get something back.

2020-07-07 06:04 UTC, juliusknorr requested changes

2020-07-07 06:04 UTC, juliushaertl commented on apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
> -		$isAnonymousOfficeOption = $request->getMethod() === 'OPTIONS' && $isOffice && $emptyAuth;
The reason we only handle anonymous options for Office were because this was [breaking evolution and macOS sync](https://github.com/nextcloud/server/issues/20624) when there was no 404 returned for those. See https://github.com/nextcloud/server/pull/20632

@rullzer Any more details on what this PR supposes to fix?

2020-07-07 07:38 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
> -		$isAnonymousOfficeOption = $request->getMethod() === 'OPTIONS' && $isOffice && $emptyAuth;
Basically it is about becomming RFC compliant. OPTIONS request are usually unauthenticated and that is fine.

2020-07-07 09:58 UTC, juliushaertl commented on apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php
> -		$isAnonymousOfficeOption = $request->getMethod() === 'OPTIONS' && $isOffice && $emptyAuth;
Then we probably should just limit the options plugin to requests to the files app dav path?

2020-11-09 19:09 UTC, closed without merging