Use PSR container interface and deprecate our own abstraction
nextcloud/server pull request #21809
Opened 2020-07-13 10:05 UTC by ChristophWurst

For https://help.nextcloud.com/t/do-we-still-need-ocp-icontainer/86139

* Add the PSR-11 container interface as a replacement for `IContainer`
* Deprecate our `IContainer` and friends
* Make the new interface base of our abstraction to ease the migration

As the pimple psr11 adapter is a final class we can't unfortunately use that little helper, but I've just duplicated the two tiny methods into our `SimpleContainer´.

A quick smoke test tells me this might actually work, but let's see what CI thinks of this :bomb:.

2020-07-13 11:49 UTC, rullzer requested changes
Maybe I'm not 100% right with the PSR... but it seems has and get have clear defined meanings...

2020-07-13 11:49 UTC, rullzer commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return isset($this[$id]);
is this correct? I mean with automatic DI something could not be set while we could initialize it?

2020-07-13 11:49 UTC, rullzer commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this[$id];
Same here. I guess we should really query here or?

2020-07-13 11:58 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this[$id];
See `\Pimple\Psr11\Container` but I agree that this needs some checking

2020-07-14 08:38 UTC, rullzer commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this[$id];
Yeah... I guess it is also maybe vague intentionally.... since with DI you would not know everything yet...

2020-07-14 08:49 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this[$id];
In my understanding there are two difference between our DI and pimple: we will try to do anything possible to load a certain class. Pimple will only build the things it knows.

Also I noticed that we currently have a *query exception* but for pimple or PSR there is even a difference between *does not exist* and *can't construct*.

2020-07-14 19:16 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return isset($this[$id]);
check again :)

2020-07-16 07:41 UTC, ChristophWurst commented
FYI one of my attempts was to get rid of Pimple and replace it with Symfony. But that container is not easy to use as it kind of expects to be first notified about all the known services, then compiled and finally used. But we have a more dynamic approach and allow registration later on. So I switched to the League container and that felt a lot more natural to our DI usage. However, the changes are major and we (@rullzer and I) think it would be a bad idea to cram this in so late in the 20 cycle. Thus this will be done for 21.

The important part is the new PSR API. That is done with this PR. So the migration can start.

2020-07-16 08:08 UTC, rullzer requested changes

2020-07-16 08:08 UTC, rullzer commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this->query($id);
Shouldn't this catch the query exception and throw the PSR11 one?

2020-07-16 08:08 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this->query($id);
Our query exception extends the PSR interface, hence this is fine

2020-07-16 08:09 UTC, ChristophWurst commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +		return $this->query($id);
Once https://github.com/php-fig/container/pull/23#issuecomment-657431032 is resolved we can drop our query exception in favor of the base one. Right now it's not a throwable, so technically it doesn't have a message, code and such

2020-07-16 08:19 UTC, rullzer approved these changes
:rocket:

2020-07-16 09:01 UTC, ChristophWurst commented
I don't see any files anymore :see_no_evil:

2020-07-16 13:15 UTC, MorrisJobke approved these changes
Fine by me 👍 Also changing to a PSR standard is the way to go

2020-07-16 13:43 UTC, merged

2020-07-28 07:25 UTC, nickvergessen commented
This breaks apps ability to use `overwriteService` in unit tests :/

2020-07-28 07:37 UTC, MorrisJobke commented
> This breaks apps ability to use `overwriteService` in unit tests :/
> E.g. https://github.com/nextcloud/spreed/blob/31c20949b4132e0024446a30f0f3a423bf145906/tests/php/Signaling/BackendNotifierTest.php#L126 is currently failing

So we need to adjust `overwriteService` to use the new approach, right?

2020-07-28 07:40 UTC, nickvergessen commented
Yeah, fixed in https://github.com/nextcloud/server/pull/22027

2020-10-06 07:47 UTC, ChristophWurst commented
Documented at https://github.com/nextcloud/documentation/pull/5160