event on webfinger request
nextcloud/server pull request #21817
Opened 2020-07-13 14:35 UTC by daita

Work in Progress.

The idea is to generate an event so that apps can add their own parts to the response on a webfinger request

@roeland

2020-07-15 06:51 UTC, rullzer commented
> @roeland should I keep going this way ?

That is not me ;)

2020-07-22 07:43 UTC, rullzer commented
@daita I'm not fully aware of the webfinger spec. But maybe your API is a bit overkill?

As far as I undersand a webfinger request comes in giving a resource and an optional relation. And we spit back out json right?
So we could gather all the json from the different parts. Mash it together and just return it?

I take it this is to make social handling a bit nicer?

2020-07-23 10:17 UTC, daita commented
Yes, exactly.

It would also make multiple apps answering to the same request. Of course, not about the same protocol

2020-07-28 13:51 UTC, daita commented
ok, I got your point now :)
I will see how to make it simpler

2020-07-28 23:32 UTC, daita commented
So, fresh new commit, a lot simpler. Only one Model `Webfinger` that contains mainly 4 variables: `subject`, `aliases`, `properties` and `links`.

- subject is filed by the WebfingerManager (core), at creation of the Model.
- aliases and properties are filled by apps.
- links is filled by apps and contains the result of the request.

no more method to fill some missing data as it should be useless now. Apps just feed links with an array or a JsonSerializable class.

@rullzer

2020-07-29 13:41 UTC, MorrisJobke commented
@daita Mind to fix the PHP CS warnings?

2020-07-30 07:34 UTC, MorrisJobke commented
There are still some code style warning. See https://github.com/nextcloud/server/pull/21817/checks?check_run_id=923955210 for the diff or just run `composer run cs:fix` (you need to run `composer install` first, but please don't add those php code style files to the commit).

2020-08-28 12:51 UTC, icewind1991 requested changes

2020-08-28 12:51 UTC, icewind1991 commented on lib/private/Webfinger/WebfingerManager.php
> +		header('Content-type: application/json');
instead of doing the output from here, returning the `$webfinger` and outputting it from `public.php` seems cleaner and would allow unit testing this class

2020-09-24 14:22 UTC, ChristophWurst commented
It's a private event. What's the purpose of this?

2020-12-07 23:22 UTC, daita commented
rebased, and moving the event to public.

2020-12-09 09:38 UTC, nickvergessen commented on lib/private/WellKnown/Exceptions/NotManagedWellKnownRequestException.php
> +	public function __construct($errorCode = 404, $message = "", $code = 0, Throwable $previous = null) {
```suggestion
	public function __construct(int $errorCode = 404, string $message = '', int $code = 0, ?Throwable $previous = null) {
```

2020-12-09 09:38 UTC, nickvergessen commented on lib/private/WellKnown/Exceptions/WellKnownRequestException.php
> +	public function __construct($errorCode = 404, $message = "", $code = 0, Throwable $previous = null) {
```suggestion
	public function __construct(int $errorCode = 404, string $message = "", int $code = 0, ?Throwable $previous = null) {
```

2020-12-09 09:39 UTC, nickvergessen commented on lib/private/WellKnown/Model/WellKnown.php
> +	public function addLink(array $arr): IWellKnown {
```suggestion
	public function addLink(array $links): IWellKnown {
```

2020-12-09 09:40 UTC, nickvergessen commented on lib/private/WellKnown/WellKnownManager.php
> +			throw new NotManagedWellKnownRequestException(404);
want to use `OCP\AppFramework\Http::STATUS_NOT_FOUND`?

2020-12-09 09:41 UTC, nickvergessen commented on lib/public/WellKnown/Model/IWellKnown.php
> +	public function addLink(array $arr): IWellKnown;
can you add a sample? it feels weird that `addLink` accepts an array.

2020-12-09 09:42 UTC, nickvergessen commented on public.php
> +	OC_App::loadApps();
Should we keep the current load calls in order?
```suggestion
	OC_App::loadApps(['authentication']);
	OC_App::loadApps(['filesystem', 'logging']);
	OC_App::loadApps();
```

2020-12-09 09:54 UTC, daita commented on lib/public/WellKnown/Model/IWellKnown.php
> +	public function addLink(array $arr): IWellKnown;
This is what I have in Circles (not pushed):

```
	/**
	 * @param Event $event
	 */
	public function handle(Event $event): void {
		if (!($event instanceof WellKnownEvent)) {
			return;
		}

		$wellKnown = $event->getWellKnown();
		if ($wellKnown->getService(IWellKnownManager::NODEINFO))
		$wellKnown->addLink(
			[
				'rel'  => Application::APP_REL,
				'href' => $this->urlGenerator->linkToRouteAbsolute('circles.Navigation.navigate')
			]
		);

		$this->debug('WellKnown request', ['wellKnown' => $wellKnown]);
	}
```


the result:
```
$ curl http://nc20.local/.well-known/nodeinfo | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0   1370      0 --:--:-- --:--:-- --:--:--  1386
{
  "links": [
    {
      "rel": "https://apps.nextcloud.com/apps/circles",
      "href": "http://nc20.local/index.php/apps/circles/"
    }
  ]
}
```

2020-12-09 10:03 UTC, nickvergessen commented on lib/private/WellKnown/Exceptions/NotManagedWellKnownRequestException.php
> +	public function __construct(int $errorCode = 404, string $message = "", int $code = 0, ?Throwable $previous = null) {
```suggestion
	public function __construct(int $errorCode = 404, string $message = '', int $code = 0, ?Throwable $previous = null) {
```

2020-12-09 10:05 UTC, nickvergessen commented on lib/public/WellKnown/Model/IWellKnown.php
> +	public function addLink(array $arr): IWellKnown;
```suggestion
	 * @param array $link
	 * @psalm-param array{rel: string, href: string} $link
	 *
	 * @return IWellKnown
	 * @since 21.0.0
	 */
	public function addLink(array $link): IWellKnown;
```

2020-12-09 11:20 UTC, ChristophWurst commented on lib/public/WellKnown/Event/WellKnownEvent.php
> +class WellKnownEvent extends Event {
https://docs.nextcloud.com/server/20/developer_manual/basics/events.html#naming-scheme

2020-12-09 11:20 UTC, ChristophWurst commented on lib/public/WellKnown/Model/IWellKnown.php
> +	public function isService(string $service): bool;
what is this magic string? a class name?

2020-12-09 15:27 UTC, daita commented
@ChristophWurst event renamed to WellKnownRequestEvent

2020-12-14 10:32 UTC, ChristophWurst commented on lib/public/WellKnown/Event/WellKnownEvent.php
> +class WellKnownEvent extends Event {
`WellKnownRequestEvent` still doesn't match the naming scheme. Your event doesn't have a verb. *Well-known request ???* *received*?

2020-12-14 10:38 UTC, ChristophWurst reviewed
I'm thinking aloud a bit.

Maybe this isn't the ideal API design. You're using an event to trigger an action. This is imperative thinking. Like *apps do your thing and update the object that I'm giving you*.

But what you essentially want to do is offer the apps a way to hook into the process of a well known request and add their custom things to the response.

How about we move this from events to registered handlers so that apps can register their *webfinger request handlers* in the bootstrap registration context. Those handlers are of a simple interface type that passes in the request and gets back the data we allow apps to specify.

Then, when a wellknown request is received, we ask the registration context for all of those handlers, iterate over them and ask them for their data, which we then combine and send back.

Does that make sense?

In general terms I'm really not a fan of using events where the emitting code expects some kind of mutation, either on the event or any other (global) state. Events should be more *passive*. Like just *hey, this happened. do whatever you want with this information* but don't expect any other code to even listen to this nor make any modifications.

2020-12-14 10:43 UTC, closed without merging

2020-12-14 15:28 UTC, ChristophWurst commented
Note to myself

* well known is defined in an RFC: https://tools.ietf.org/html/rfc5785
* webfinger is defined here: https://tools.ietf.org/html/rfc7033
* webfinger and nodeinfo are two aspects "we" are currently most interested in, but their formats aren't what *any* well known handler would return
* it's necessary that the request has to be processed by more than one app/handler -> we can't simply stop at the first handler that can process the request, other results have to be combined/merged
* we have some routes in place that redirect webfinger and nodeinfo requests to public.php, this is technical dept from 2018 said to be used for 15 only but we still have this today: https://github.com/nextcloud/server/pull/11396#discussion_r226184012
* we can't "just" register a route for `.well-known/{service}`, have a decent controller and testable code. We still need to go through public.php at least for webfinger and nodeinfo due to the technical dept