Add LoadAdditionalScriptsEvent for files_sharing
nextcloud/server pull request #21815
Opened 2020-07-13 14:10 UTC by juliushaertl

Move old the `OCA\Files::loadAdditionalScripts` and `OCA\Files::loadAdditionalScripts::publicShareAuth` events to our the public event API. An adapter is added as well to still dispatch the old events on the until the old ones are removed completely.

2020-07-13 14:14 UTC, MorrisJobke commented on apps/files_sharing/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +class LegacyLoadAdditionalScriptsAdapter implements IEventListener {
Mind to name it Listener instead of adapter?

2020-07-13 14:14 UTC, MorrisJobke commented on apps/files_sharing/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +		if (!($event instanceof LoadAdditionalScriptsEvent)) {
@ChristophWurst @kesselb Can't we type hint the event directly. Overwriting the method should be fine in a subclass, right?

2020-07-13 14:15 UTC, juliushaertl commented on apps/files_sharing/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +class LegacyLoadAdditionalScriptsAdapter implements IEventListener {
This is a shameless clone of https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/apps/files/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php#L36 but fine to adjust the naming from my side.

2020-07-13 14:15 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$this->eventDispatcher->dispatch(new LoadAdditionalScriptsEvent($share));
I guess it is `dispatchTyped` here and above.

2020-07-13 14:17 UTC, MorrisJobke commented
I just noticed that you still use the newer old way. The newest one is the `IEventDispatcher` 🙈  Let's have a quick coordination chat.

2020-07-13 14:19 UTC, MorrisJobke commented
https://github.com/nextcloud/server/issues/14552#issuecomment-654885240

2020-07-13 19:23 UTC, juliushaertl commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$this->eventDispatcher->dispatch(new LoadAdditionalScriptsEvent($share));
Yes, with the IEventDispatcher now.

2020-07-13 19:25 UTC, juliushaertl commented on apps/files_sharing/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +		if (!($event instanceof LoadAdditionalScriptsEvent)) {
Would be nice, but i guess since it is an interface we implement the signature needs to match exactly.

2020-07-13 20:22 UTC, MorrisJobke approved these changes
Code looks good and works 👍

2020-07-13 20:24 UTC, MorrisJobke commented
Rebased and autosquashed 🚀

2020-07-13 20:30 UTC, MorrisJobke commented
And I fixed the unit tests 🙈

2020-07-14 09:03 UTC, skjnldsv approved these changes

2020-07-14 09:07 UTC, ChristophWurst commented on apps/files_sharing/lib/Listener/LegacyLoadAdditionalScriptsAdapter.php
> +		if (!($event instanceof LoadAdditionalScriptsEvent)) {
yes you're not allowed to be more specific in the implementation

2020-07-14 09:12 UTC, ChristophWurst requested changes
A theoretical concern but it's easy to fix now than having another migration path for a public event that takes three years to get rid of.

2020-07-14 09:12 UTC, ChristophWurst commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
can we take a moment to brainstorm about the event name? IMO *load additional scripts* is very imperative and does not describe something that *is happening* but rather what to do.

what is the *event* the occurs? a sharing page being shown?

Ref https://docs.nextcloud.com/server/stable/developer_manual/app/events.html#naming-scheme

2020-07-14 09:44 UTC, rullzer commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
Sure I just copied the name...

2020-07-14 11:20 UTC, MorrisJobke commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
`BeforeTemplatePageBeingRenderedEvent`? A bit too much, but it's basically the `afterController` method that checks if it is a template response - see also https://github.com/nextcloud/server/pull/21822/files#diff-3115ab6a1e7c32d9316ae83878687fa1R56

Those two events should be named similarly.

2020-07-14 11:24 UTC, ChristophWurst commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
`BeforePageLoaded`?

2020-07-14 11:26 UTC, ChristophWurst commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
Or better `BeforePageRendered` because loaded sounds like something after it's transmitted to the client-side

2020-07-14 13:14 UTC, juliushaertl commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
I'd prefer `BeforeTemplateRendered` then as we don't use the page term anywhere.

2020-07-14 13:40 UTC, skjnldsv commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
Clearly, we definitely need to cleanup and split the events for files.
Like implementing the FileActions API, having one event to fire them all doesn't seems very productive.
I prefer more flexibility here :wink:

2020-07-14 18:52 UTC, MorrisJobke commented on apps/files_sharing/lib/Event/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
@juliushaertl mind to update this pr with your latest proposal?

2020-07-14 19:35 UTC, juliushaertl commented
Fixed, rebased and squashed.

2020-07-14 19:38 UTC, ChristophWurst approved these changes

2020-07-14 19:46 UTC, MorrisJobke commented on apps/files_sharing/lib/AppInfo/Application.php
> +		$dispatcher->addServiceListener(FilesSharingLoadAdditionalScriptsEvent::class, LegacyBeforeTemplateRenderedListener::class);
Please rename this here as well as it is an alias

2020-07-14 19:48 UTC, MorrisJobke approved these changes
Beside my little comment this looks good 👍

2020-07-15 07:04 UTC, MorrisJobke commented on apps/files_sharing/lib/AppInfo/Application.php
> +		$dispatcher->addServiceListener(FilesSharingLoadAdditionalScriptsEvent::class, LegacyBeforeTemplateRenderedListener::class);
Let me do it.

2020-07-15 07:08 UTC, MorrisJobke commented
Ready for merge 🚀

2020-07-15 07:08 UTC, juliushaertl commented on apps/files_sharing/lib/AppInfo/Application.php
> +		$dispatcher->addServiceListener(FilesSharingLoadAdditionalScriptsEvent::class, LegacyBeforeTemplateRenderedListener::class);
Thanks :heart:

2020-07-15 07:28 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$this->eventDispatcher->dispatchTyped(new LoadViewer());
We can do that? :O

2020-07-15 07:29 UTC, skjnldsv commented on apps/files_sharing/lib/Event/BeforeTemplateRenderedEvent.php
> +	 */
```suggestion
	/** @var IShare */
```

2020-07-15 07:35 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$this->eventDispatcher->dispatchTyped(new LoadViewer());
Yep - that's the new way and makes things fully typed and thus allows the be a bit more safe.

2020-07-15 07:37 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$this->eventDispatcher->dispatchTyped(new LoadViewer());
Also you just register for the `::class` and then the IDE finds properly all usages ;)

2020-07-15 17:56 UTC, rullzer approved these changes
Looks good!

2020-07-15 18:02 UTC, merged