Add real events to load additionalscripts
nextcloud/server pull request #21822
Opened 2020-07-13 20:30 UTC by rullzer

Should make even more lazy loading possible!

2020-07-13 20:33 UTC, MorrisJobke approved these changes

2020-07-13 20:33 UTC, MorrisJobke commented
New events should be documented in https://docs.nextcloud.com/server/19/developer_manual/app/events.html#available-events and old deprecations need to be added to #20953

2020-07-13 20:34 UTC, MorrisJobke commented
Please also fix the CS complains :)

2020-07-14 11:46 UTC, ChristophWurst requested changes

2020-07-14 11:46 UTC, ChristophWurst commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
`BeforePageRendered` or similar, like objected in the other PR for files_sharing

2020-07-14 11:46 UTC, ChristophWurst commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
can we just make this a flag on the other event?

2020-07-14 13:18 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
Do we really want to add now two levels of this? Because then we have the logic if something gets initialized and loaded during runtime and not during registration.

2020-07-14 13:20 UTC, ChristophWurst commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
Good point. But I guess if you listen for this you want to react to either of the two scenarios, right? Or is there something that would only care about one of the two?

2020-07-14 14:21 UTC, rullzer commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
For example notifications only needs to be loaded if you are logged in

2020-07-14 14:24 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
As discussed in the other PR: `BeforeTemplateRenderedEvent`

2020-07-14 14:25 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
#21815

2020-07-14 18:41 UTC, ChristophWurst commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
While I do get the argument that we might load too much in case of just a flag, The page load happens rather rarely and so that one unnecessarily loaded listener is okay-ish to me. I'm more in favor of a lean API.

2020-07-14 18:53 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsEvent.php
> +class LoadAdditionalScriptsEvent extends Event {
@rullzer  mind to update this or to the similar name as in the linked pr by @juliushaertl ?

2020-07-14 18:54 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
Fine with me

2020-07-15 07:11 UTC, MorrisJobke commented
Let me push some fixup commits here and then we can continue the discussion :)

2020-07-15 07:34 UTC, MorrisJobke commented on lib/public/AppFramework/Http/Events/LoadAdditionalScriptsLoggedInEvent.php
> +class LoadAdditionalScriptsLoggedInEvent extends Event {
I merged those two.

2020-07-15 07:34 UTC, MorrisJobke commented
@rullzer @ChristophWurst Give me your feedback :)

2020-07-15 07:34 UTC, MorrisJobke approved these changes

2020-07-15 09:44 UTC, kesselb commented on lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
> +			$this->legacyDispatcher->dispatch($legacyEventName, new GenericEvent());
Is a behavioural change :thinking: 

**Before** 

| | Is logged in | Is **not** logged in |
| ------------- |-------------|-----|
| EVENT_LOAD_ADDITIONAL_SCRIPTS | :heavy_check_mark:   | :heavy_check_mark:   |
| EVENT_LOAD_ADDITIONAL_SCRIPTS_LOGGEDIN | :heavy_check_mark:    |  :heavy_multiplication_x: |



**After** 

| | Is logged in | Is **not** logged in |
| ------------- |-------------|-----|
| EVENT_LOAD_ADDITIONAL_SCRIPTS | :heavy_multiplication_x:   | :heavy_check_mark:   |
| EVENT_LOAD_ADDITIONAL_SCRIPTS_LOGGEDIN | :heavy_check_mark:    |  :heavy_multiplication_x: |

2020-07-15 10:59 UTC, MorrisJobke commented on lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
> +			$this->legacyDispatcher->dispatch($legacyEventName, new GenericEvent());
I know, but it's now the same event. Thus it would trigger all code paths twice. So if you listen for the new event it will hold the `loggedIn` flag and you need to decide what you want to do with it in the listener code.

2020-07-15 11:15 UTC, ChristophWurst commented on lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
> +			$this->legacyDispatcher->dispatch($legacyEventName, new GenericEvent());
For the new event, yes, but what about the old one that we still emit? That behavior changed.

2020-07-15 11:37 UTC, MorrisJobke commented on lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.php
> +			$this->legacyDispatcher->dispatch($legacyEventName, new GenericEvent());
Right - let me add it then.

2020-07-15 11:54 UTC, ChristophWurst approved these changes

2020-07-15 17:45 UTC, rullzer commented
:rocket:

2020-07-15 17:45 UTC, rullzer commented
:+1: from me

2020-07-15 17:50 UTC, merged

2020-07-15 17:55 UTC, MorrisJobke commented
https://github.com/nextcloud/documentation/pull/2201

2020-07-15 17:58 UTC, MorrisJobke commented
#14552 to remove the legacy handler at some point in time.