Harden SSE key generation
nextcloud/server pull request #22018
Opened 2020-07-27 11:29 UTC by juliushaertl

There might be cases where multiple requests trigger the key generation
at the same time and the instance ends up with a non-fitting
public/private key pair. Therefore the whole key generation should be
locked. Other than that this makes sure that user key generation return
values are properly validated.

2020-07-28 06:44 UTC, juliushaertl commented
```
1) OCA\Encryption\Tests\Users\SetupTest::testSetupUser with data set #1 (false, true)
Failed asserting that false is identical to true.
```

2020-07-29 13:53 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +				$encryptedKey = $this->crypt->encryptPrivateKey($keyPair['privateKey'], $this->getMasterKeyPassword(), $this->masterKeyId);
What about line 192/213?

2020-07-29 13:53 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +				$encryptedKey = $this->crypt->encryptPrivateKey($keyPair['privateKey'], '');
What about line 168/178?

2020-07-29 13:58 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +				$this->lockingProvider->releaseLock('encryption-generateSharedKey', ILockingProvider::LOCK_EXCLUSIVE);
There is no unlock in the success case?

2020-07-29 13:59 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +				$this->lockingProvider->releaseLock('encryption-generateMasterKey', ILockingProvider::LOCK_EXCLUSIVE);
What about the releaseLock in the success case.

2020-07-29 13:59 UTC, MorrisJobke requested changes
See inline comments

2020-07-29 15:32 UTC, juliushaertl commented on apps/encryption/lib/KeyManager.php
> +				$encryptedKey = $this->crypt->encryptPrivateKey($keyPair['privateKey'], '');
What do you mean by that?

2020-07-29 15:32 UTC, juliushaertl commented on apps/encryption/lib/KeyManager.php
> +				$this->lockingProvider->releaseLock('encryption-generateMasterKey', ILockingProvider::LOCK_EXCLUSIVE);
Indeed, thanks. I pushed a fixup for that.

2020-07-30 09:11 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +					$this->publicShareKeyId . '.publicKey', $keyPair['publicKey'],
```suggestion
					$this->publicShareKeyId . '.' . $this->publicKeyId, $keyPair['publicKey'],
```

Something like this? Or am I wrong here?

2020-07-30 09:11 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +				$encryptedKey = $this->crypt->encryptPrivateKey($keyPair['privateKey'], '');
See other comment (I noticed that it was in the diff, but not in the whitespace cleaned diff)

2020-07-30 09:11 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +					$this->masterKeyId . '.publicKey', $keyPair['publicKey'],
```suggestion
					$this->masterKeyId . '.' . $this->publicKeyId, $keyPair['publicKey'],
```

2020-08-10 12:01 UTC, rullzer commented on apps/encryption/lib/KeyManager.php
> +					$this->publicShareKeyId . '.publicKey', $keyPair['publicKey'],
? I don't get what you want to suggest.

2020-08-10 13:56 UTC, juliushaertl commented on apps/encryption/lib/KeyManager.php
> +					$this->publicShareKeyId . '.publicKey', $keyPair['publicKey'],
Ah I see. Mainly replace the hardcoded string with the property that contains it ;)

2020-08-10 14:18 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +					$this->publicShareKeyId . '.publicKey', $keyPair['publicKey'],
> Ah I see. Mainly replace the hardcoded string with the property that contains it ;)

Yes - because you did this at most of the other places as well.

2020-08-14 14:33 UTC, MorrisJobke commented on apps/encryption/lib/KeyManager.php
> +			$this->log->error('A private master key is available but the public key could not be found. This should never happen.');
```suggestion
			$this->log->error('A public master key is available but the private key could not be found. This should never happen.');
```

2020-08-14 14:34 UTC, MorrisJobke approved these changes
Looks good beside the typo in the error message. 👍

2020-08-18 08:59 UTC, rullzer approved these changes
All good indeed besides the typo

2020-08-19 18:42 UTC, merged

2020-10-28 14:10 UTC, rullzer commented
/backport to stable19

2020-10-28 14:10 UTC, rullzer commented
/backport to stable18