contactsmanager shall limit number of results early
nextcloud/server pull request #22057
Opened 2020-07-30 10:54 UTC by blizzz

fixes #20009 cf. https://github.com/nextcloud/server/issues/20009#issuecomment-664643922

Optional arguments are added to the ContactsStore API, so it should be okay to backport it to 19. Support for limiting results is implemented down the stack already. Since the contactsmenu reduces results according to `sharing.maxAutocompleteResults` and the search filter is passed to the backend, limiting the possible results up front does not sacrifice anything, but improves performance.

2020-07-30 10:54 UTC, blizzz commented
/backport to stable19

2020-07-30 11:26 UTC, MorrisJobke commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			if ($offset !== null) {
Is `offset` always bound to a `limit`? Because otherwise I would just keep it separate.

2020-07-30 11:37 UTC, MorrisJobke requested changes

2020-07-30 11:37 UTC, MorrisJobke commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			if ($offset !== null) {
The are handled independent: https://github.com/nextcloud/server/blob/aab646a9d0f67f42fe8eb3398e6b4b726c501585/apps/dav/lib/CardDAV/CardDavBackend.php#L1004-L1009

I would move then the `if` statement out and then is good to go 👍

2020-07-30 11:37 UTC, georgehrke commented on lib/public/Contacts/ContactsMenu/IContactsStore.php
> +	public function getContacts(IUser $user, $filter, ?int $limit = null, ?int $offset = null);
🚨 This is a breaking change. 🚨

Not sure we should back-port this.

2020-07-30 11:41 UTC, MorrisJobke commented on lib/public/Contacts/ContactsMenu/IContactsStore.php
> +	public function getContacts(IUser $user, $filter, ?int $limit = null, ?int $offset = null);
Not really as those are optional parameters and the `IContactsStore` is implemented in the server side and not inside apps, or did I misunderstand something wrong?

2020-07-30 11:46 UTC, georgehrke commented on lib/public/Contacts/ContactsMenu/IContactsStore.php
> +	public function getContacts(IUser $user, $filter, ?int $limit = null, ?int $offset = null);
Ah, you are right. I always thought that apps could also implement their own `IContactsStore`, but I was wrong.

2020-07-30 19:37 UTC, blizzz commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			if ($offset !== null) {
> Is `offset` always bound to a `limit`? Because otherwise I would just keep it separate.

what's the point of having offset without limit?

2020-07-30 22:53 UTC, MorrisJobke commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			if ($offset !== null) {
API allows it 🤷‍♂️ Better not mess with consistent behavior across all those APIs. Other option would be to add this logic to all the other levels of this API stack

2020-07-31 10:25 UTC, blizzz commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			if ($offset !== null) {
also pgsql let's you do it indeed. You're right, I'll adjust.

2020-07-31 10:46 UTC, MorrisJobke approved these changes
Code looks good and makes sense 👍

2020-08-03 11:09 UTC, nickvergessen approved these changes

2020-08-03 12:31 UTC, skjnldsv approved these changes
:elephant:

2020-08-03 13:15 UTC, merged

2020-10-13 15:38 UTC, blizzz commented
/backport to stable18

2023-11-02 10:39 UTC, ChristophWurst commented
> not sacrifice anything, but improves performance.

The limit is passed down, but not the sort order. So the result correctness is only given if database sorts the same way as the PHP code does later on.

Let's say you have 100 contacts. The database sorts them by UID. You select the first 20 rows, then sort the rows by name. It's not the same result as fetching all 100 contacts, sorting them and then taking the first 20 entries.

2023-11-02 21:04 UTC, blizzz commented
You have too many results :sweat_smile: