Distribute preview folders in appdata in multibucket setup to multiple buckets
nextcloud/server pull request #22063
Opened 2020-07-30 20:22 UTC by MorrisJobke

* introduces a new IRootMountProvider to register mount points inside the root storage
* adds a AppdataPreviewObjectStoreStorage to handle the split between preview folders and bucket number

Pending ideas:

Migration ideas:

1) new subfolder that holds the new bucket mount points
    * bring in special code into the preview layer that only checks the previews in the multi bucket setup in this different subfolder. If not there: then the old ones can just be used. 
    * pro: migration could be done live because previews can be moved step by step over to the new way (maybe during access or just as a background job)
    * pro: existing setups don't need any migration (for all the non-multibucket setups) or can do them when really needed 
    * con: non-transparent and adds more complexity
2) keep the current naming and mount the bucket storages over the existing folder structure
    * to make the migration easier there might be the option to add code that tries to fetch the old previews
    * pro: no change to the preview code
    * pro: completely transparent and preview layer doesn't need any change
    * con: heavy migration (only) for multi bucket setups - there the previews need to be migrated to the new layout (or need to be dropped)

Todo:

* [ ] load those root mount providers
* [ ] tests for correct bucket association
* [ ] migration path from old to new way

Ref #22033

2020-07-30 21:55 UTC, MorrisJobke commented
> *
> * keep the current naming and mount the bucket storages over the existing folder structure

This is the preferred way of course because it provides the best long term maintainability.

2020-07-30 22:14 UTC, MorrisJobke commented
> > * keep the current naming and mount the bucket storages over the existing folder structure
> 
> This is the preferred way of course because it provides the best long term maintainability. Let's give it a try.

Seem to have worked:

* existing previews are loaded from the old bucket
* previews for new files will be put in a new bucket
* new previews for old files will be put in the old bucket, to have them all in one place

What is missing now is a migration tool to move previews step by step over to the new location. I would make this a CLI tool that can be triggered by the admin and allows to be canceled at any time.

2020-07-31 14:54 UTC, icewind1991 commented
We will also need to figure out some way to handle migrating the number of buckets.

For home storage we store the bucket for each user so they stay consistent if the bucket count is changed.

2020-07-31 18:41 UTC, MorrisJobke commented
> We will also need to figure out some way to handle migrating the number of buckets.

Ah right ... but then it's limited to the first amount of buckets, right? And with #22039 this should not be a problem anymore, right?

2020-08-03 12:54 UTC, icewind1991 commented
it would still be an issue in that currently, changing the bucket count on an existing setup is supported.

A really cheap and dirty way might be to separate the config of multibucket home storage, and multibucket preview storage, either as separate numbers, or always using 256 buckets for previews if enabled.

Combined with changing the postfix for preview storage to something like `-preview-$i` would completely separate the preview storage from the main buckets

2020-08-03 13:13 UTC, MorrisJobke commented
> A really cheap and dirty way might be to separate the config of multibucket home storage, and multibucket preview storage, either as separate numbers, or always using 256 buckets for previews if enabled.

I would just store the number of the bucket for a specific preview folder into the appconfig and then changing the maximum number of buckets would not be a problem anymore.


> Combined with changing the postfix for preview storage to something like `-preview-$i` would completely separate the preview storage from the main buckets

That's something we can do later on, right? With 256 buckets and a recommend 3.5 million objects per storage it would be nearly 900 million previews. Once this is reached we need to look into how to further spread this anyways.



> Combined with changing the postfix for preview storage to something like `-preview-$i` would completely separate the preview storage from the main buckets

That would also make it a bit easier, but can we guarantee, that those buckets always can be created? Are there some limits somewhere?

2020-08-03 13:51 UTC, icewind1991 commented
> I would just store the number of the bucket for a specific preview folder into the appconfig and then changing the maximum number of buckets would not be a problem anymore.

That would work yes, but I do think that there is benefit to splitting the preview bucket

> That would also make it a bit easier, but can we guarantee, that those buckets always can be created? Are there some limits somewhere?

multibucket already expects being able to create buckets, I'm not aware of any bucket count limit, but it's worth trying to verify this with redhat if we decide to go this route.

2020-08-03 16:18 UTC, MorrisJobke commented
> multibucket already expects being able to create buckets, I'm not aware of any bucket count limit, but it's worth trying to verify this with redhat if we decide to go this route.

I also realized this by reading the code. Will verify.

2020-08-03 16:19 UTC, MorrisJobke commented
I just pushed a first version of a migration command. Looks quite good locally, but needs extensive testing as well as some proper test cases.

2020-08-04 13:09 UTC, MorrisJobke commented
> * there is a memory leak in the migration tool, that adds ~3MB per preview folder (this leaves with only 700 preview folders being migrated for a 2GB memory limit)

I fixed this by the last fixup commit: 6a1e748011 - this changes from copy the file manually it now uses the `move()` method of the node API.

2020-08-06 09:51 UTC, MorrisJobke commented
I changed the migration script now to iterate on the preview folder via Node API instead of doing a big DB query. As of now the migration script only migrates previews that used the old path style (only the file ID `384` and not something like `0/5/8/4/c/e/5/384`). It will then migrate them into the new path style and move them to the correct bucket.

For generating previews in the old way I uncommented the lower part of the following diff. Then all previews are generated in the old way. Later I opened a browser to fill the previews. Once they are done I revert this again and used the other patch to throw an exception if a preview is generated (to be able to verify none are generated after the migration). I started the migration via `php occ maintenance:repair:multibucketpreviews -b`, cleared the browser cache and refreshed the page. Now all previews should still show up and the exception should not be thrown.


```diff 
diff --git a/lib/private/Preview/Generator.php b/lib/private/Preview/Generator.php
index f7aed987d8..a1eb3786e4 100644
--- a/lib/private/Preview/Generator.php
+++ b/lib/private/Preview/Generator.php
@@ -393,6 +393,8 @@ class Generator {
 	 * @throws \InvalidArgumentException if the preview would be invalid (in case the original image is invalid)
 	 */
 	private function generatePreview(ISimpleFolder $previewFolder, IImage $maxPreview, $width, $height, $crop, $maxWidth, $maxHeight, $prefix) {
+		// un-comment following line to prevent preview generation (to test that previews where properly migrated and are not generated again)
+		// throw new \Exception('Preventing preview generation.');
 		$preview = $maxPreview;
 		if (!$preview->valid()) {
 			throw new \InvalidArgumentException('Failed to generate preview, failed to load image');
diff --git a/lib/private/Preview/Storage/Root.php b/lib/private/Preview/Storage/Root.php
index 37ae175812..5017d7c17d 100644
--- a/lib/private/Preview/Storage/Root.php
+++ b/lib/private/Preview/Storage/Root.php
@@ -65,6 +65,8 @@ class Root extends AppData {
 
 	public function newFolder(string $name): ISimpleFolder {
 		$internalFolder = $this->getInternalFolder($name);
+		// un-comment to enforce old path (file IDs only) for preview folders
+		// $internalFolder = $name;
 		return parent::newFolder($internalFolder);
 	}
```

2020-08-06 11:57 UTC, MorrisJobke commented
A migration then looks like this:

```
$ php occ maintenance:repair:multibucketpreviews -b                                      255 ↵
This will migrate all previews from the old preview location to the new one.

Fetching previews that need to be migrated …
A total of 68 preview files need to be migrated.

The migration will always migrate all previews of a single file in a batch. After each batch the process can be canceled by pressing CTRL-C. This fill finish the current batch and then stop the migration. This migration can then just be started and it will continue.
Batch mode active: migration is started right away.


 0/68 [>---------------------------]   0% < 1 sec/< 1 sec Memory: 26.0 MiB 
 Starting …
 1/68 [>---------------------------]   1% < 1 sec/< 1 sec Memory: 38.0 MiB 
 Migrating 20 …
 2/68 [>---------------------------]   2%  1 sec/34 secs Memory: 46.0 MiB 
 Migrating 320 …
 3/68 [=>--------------------------]   4%  1 sec/23 secs Memory: 56.0 MiB 
 Migrating 321 …
 4/68 [=>--------------------------]   5%  1 sec/17 secs Memory: 58.0 MiB 
 Migrating 322 …
 5/68 [==>-------------------------]   7%  1 sec/14 secs Memory: 58.0 MiB 
 Migrating 323 …
 6/68 [==>-------------------------]   8%  1 sec/11 secs Memory: 60.0 MiB 
 Migrating 324 …
 7/68 [==>-------------------------]  10% 2 secs/19 secs Memory: 60.0 MiB 
 Migrating 325 …
 8/68 [===>------------------------]  11% 2 secs/17 secs Memory: 60.0 MiB 
 Migrating 326 …
 9/68 [===>------------------------]  13% 2 secs/15 secs Memory: 60.0 MiB 
 Migrating 327 …
10/68 [====>-----------------------]  14% 2 secs/14 secs Memory: 60.0 MiB 
 Migrating 328 …
11/68 [====>-----------------------]  16% 2 secs/12 secs Memory: 60.0 MiB 
 Migrating 329 …
12/68 [====>-----------------------]  17% 3 secs/17 secs Memory: 60.0 MiB 
 Migrating 330 …
13/68 [=====>----------------------]  19% 3 secs/16 secs Memory: 60.0 MiB 
 Migrating 331 …
14/68 [=====>----------------------]  20% 3 secs/15 secs Memory: 60.0 MiB 
 Migrating 332 …
15/68 [======>---------------------]  22% 3 secs/14 secs Memory: 60.0 MiB 
 Migrating 333 …
16/68 [======>---------------------]  23% 3 secs/13 secs Memory: 62.0 MiB 
 Migrating 334 …
17/68 [=======>--------------------]  25% 4 secs/16 secs Memory: 60.0 MiB 
 Migrating 335 …
18/68 [=======>--------------------]  26% 4 secs/15 secs Memory: 60.0 MiB 
 Migrating 336 …
19/68 [=======>--------------------]  27% 4 secs/14 secs Memory: 62.0 MiB 
 Migrating 337 …
20/68 [========>-------------------]  29% 4 secs/14 secs Memory: 62.0 MiB 
 Migrating 338 …
21/68 [========>-------------------]  30% 5 secs/16 secs Memory: 64.0 MiB 
 Migrating 339 …
22/68 [=========>------------------]  32% 5 secs/15 secs Memory: 62.0 MiB 
 Migrating 340 …
23/68 [=========>------------------]  33% 5 secs/15 secs Memory: 62.0 MiB 
 Migrating 341 …
24/68 [=========>------------------]  35% 5 secs/14 secs Memory: 62.0 MiB 
 Migrating 342 …
25/68 [==========>-----------------]  36% 5 secs/14 secs Memory: 62.0 MiB 
 Migrating 343 …
26/68 [==========>-----------------]  38% 6 secs/16 secs Memory: 62.0 MiB 
 Migrating 344 …
27/68 [===========>----------------]  39% 6 secs/15 secs Memory: 62.0 MiB 
 Migrating 345 …
28/68 [===========>----------------]  41% 6 secs/15 secs Memory: 62.0 MiB 
 Migrating 346 …
29/68 [===========>----------------]  42% 6 secs/14 secs Memory: 64.0 MiB 
 Migrating 347 …
30/68 [============>---------------]  44% 7 secs/16 secs Memory: 64.0 MiB 
 Migrating 348 …
31/68 [============>---------------]  45% 7 secs/15 secs Memory: 64.0 MiB 
 Migrating 349 …
32/68 [=============>--------------]  47% 7 secs/15 secs Memory: 64.0 MiB 
 Migrating 350 …
33/68 [=============>--------------]  48% 7 secs/14 secs Memory: 64.0 MiB 
 Migrating 351 …
34/68 [==============>-------------]  50% 8 secs/16 secs Memory: 64.0 MiB 
 Migrating 352 …
35/68 [==============>-------------]  51% 8 secs/16 secs Memory: 66.0 MiB 
 Migrating 353 …
36/68 [==============>-------------]  52% 8 secs/15 secs Memory: 66.0 MiB 
 Migrating 354 …
37/68 [===============>------------]  54% 9 secs/17 secs Memory: 66.0 MiB 
 Migrating 355 …
38/68 [===============>------------]  55% 9 secs/16 secs Memory: 66.0 MiB 
 Migrating 356 …
39/68 [================>-----------]  57% 9 secs/16 secs Memory: 66.0 MiB 
 Migrating 357 …
40/68 [================>-----------]  58% 9 secs/15 secs Memory: 66.0 MiB 
 Migrating 358 …
41/68 [================>-----------]  60% 10 secs/17 secs Memory: 66.0 MiB 
 Migrating 359 …
42/68 [=================>----------]  61% 10 secs/16 secs Memory: 66.0 MiB 
 Migrating 360 …
43/68 [=================>----------]  63% 10 secs/16 secs Memory: 68.0 MiB 
 Migrating 361 …
44/68 [==================>---------]  64% 10 secs/15 secs Memory: 68.0 MiB 
 Migrating 362 …
45/68 [==================>---------]  66% 11 secs/17 secs Memory: 68.0 MiB 
 Migrating 363 …
46/68 [==================>---------]  67% 11 secs/16 secs Memory: 68.0 MiB 
 Migrating 364 …
47/68 [===================>--------]  69% 11 secs/16 secs Memory: 68.0 MiB 
 Migrating 365 …
48/68 [===================>--------]  70% 11 secs/16 secs Memory: 68.0 MiB 
 Migrating 366 …
49/68 [====================>-------]  72% 11 secs/15 secs Memory: 70.0 MiB 
 Migrating 367 …
50/68 [====================>-------]  73% 12 secs/16 secs Memory: 70.0 MiB 
 Migrating 368 …
51/68 [=====================>------]  75% 12 secs/16 secs Memory: 68.0 MiB 
 Migrating 369 …
52/68 [=====================>------]  76% 12 secs/16 secs Memory: 68.0 MiB 
 Migrating 370 …
53/68 [=====================>------]  77% 12 secs/15 secs Memory: 68.0 MiB 
 Migrating 371 …
54/68 [======================>-----]  79% 13 secs/16 secs Memory: 68.0 MiB 
 Migrating 372 …
55/68 [======================>-----]  80% 13 secs/16 secs Memory: 70.0 MiB 
 Migrating 373 …
56/68 [=======================>----]  82% 13 secs/16 secs Memory: 70.0 MiB 
 Migrating 374 …
57/68 [=======================>----]  83% 13 secs/16 secs Memory: 70.0 MiB 
 Migrating 375 …
58/68 [=======================>----]  85% 14 secs/16 secs Memory: 70.0 MiB 
 Migrating 376 …
59/68 [========================>---]  86% 14 secs/16 secs Memory: 70.0 MiB 
 Migrating 377 …
60/68 [========================>---]  88% 14 secs/16 secs Memory: 70.0 MiB 
 Migrating 378 …
61/68 [=========================>--]  89% 14 secs/16 secs Memory: 70.0 MiB 
 Migrating 379 …
62/68 [=========================>--]  91% 14 secs/15 secs Memory: 70.0 MiB 
 Migrating 380 …
63/68 [=========================>--]  92% 15 secs/16 secs Memory: 70.0 MiB 
 Migrating 381 …
64/68 [==========================>-]  94% 15 secs/16 secs Memory: 70.0 MiB 
 Migrating 382 …
65/68 [==========================>-]  95% 15 secs/16 secs Memory: 70.0 MiB 
 Migrating 416 …
66/68 [===========================>]  97% 15 secs/15 secs Memory: 70.0 MiB 
 Migrating 576 …
67/68 [===========================>]  98% 16 secs/16 secs Memory: 70.0 MiB 
 Migrating 577 …
68/68 [============================] 100% 16 secs/16 secs Memory: 70.0 MiB 
 Migrating 584 …
```

2020-08-06 15:19 UTC, icewind1991 requested changes

2020-08-06 15:19 UTC, icewind1991 commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +				$newFoldername = implode('/', str_split(substr(md5($name), 0, 7))) . '/' . $name;
might be nice to make `OC\Preview\Storage\Root::getInternalFolder` static (or expose it in some other way and re-use that here.

That case if we ever decide to change this logic in the future we only have a single place where the folder paths are generated and they can never get out of sync

2020-08-06 15:19 UTC, icewind1991 commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +					foreach ($dirListing1 as $dir2) {
there should be a better way to do this then indenting 7 `foreach` levels deep :)

maybe an iterator/generator that yields all the different preview paths which can then be looped over.
that also remove the need to duplicate the signal handling

2020-08-06 15:19 UTC, icewind1991 commented on lib/private/Files/Mount/ObjectStorePreviewCacheMountProvider.php
> +	public function getRootMounts(IStorageFactory $loader): array {
since this now always generated 256 preview buckets, it might be nice to only trigger this if it's explicitly enabled, instead of enabling it automatically for all multibucket setups.

I would expect nextcloud creating 256 new buckets "spontaneously" after upgrade to quiet surprising for people

2020-08-06 15:29 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +					foreach ($dirListing1 as $dir2) {
Yep ... also thought about this, but in the end this way was just faster to implement. Yep not the smartest way, but some that just works.

2020-08-06 15:30 UTC, MorrisJobke commented on lib/private/Files/Mount/ObjectStorePreviewCacheMountProvider.php
> +	public function getRootMounts(IStorageFactory $loader): array {
Fine with me. Let me add then a config switch for that.

2020-08-06 15:30 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +				$newFoldername = implode('/', str_split(substr(md5($name), 0, 7))) . '/' . $name;
Mmmmh ... not 100% sure, but the static approach might be the best to keep the restructuring low.

2020-08-06 15:35 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +			if (preg_match('!^[0-9]{2,}$!', $name)) {
One thing I had in mind with this branch of the `if` statement:

Move it inside a general tool, that then just works on all instances and migrates the old way of `preview/FILEID` into the new one `preview/0/0/0/0/0/0/0/FILEID`. Then it would be not that multibucket specific and other setups benefit from it as well.

Additionally a second migration tool just holds the multi bucket migration that migrates from `preview/old-multibucket/0/0/0/0/0/0/0/FILEID` to `preview/0/0/0/0/0/0/0/FILEID`.

Does that sound like a good idea?

2020-08-06 15:56 UTC, icewind1991 commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +			if (preg_match('!^[0-9]{2,}$!', $name)) {
sounds good

2020-08-06 19:24 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +			if (preg_match('!^[0-9]{2,}$!', $name)) {
Actually it makes the whole thing easier. Let me create a separate PR for just this migration command.

2020-08-06 19:39 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +			if (preg_match('!^[0-9]{2,}$!', $name)) {
#22135 - there it is :)

2020-08-06 20:17 UTC, MorrisJobke commented on core/Command/Maintenance/RepairMultibucketPreviews.php
> +				$newFoldername = implode('/', str_split(substr(md5($name), 0, 7))) . '/' . $name;
Also done in #22135

2020-08-06 20:25 UTC, MorrisJobke commented
Okay - this is now ready for review. I took the most critical part of the migration script out into #22135. Now this PR only contains the code that introduces the multi buckets for previews. It will only add new files in them and load existing ones from the old location.

Ready for review 🚀

2020-08-07 01:04 UTC, icewind1991 approved these changes

2020-08-07 06:00 UTC, juliushaertl commented on lib/private/Preview/Storage/Root.php
> +		if ($this->isMultibucketPreviewDistributionEnabled) {
Ideally we should try with the new structure first

2020-08-07 06:07 UTC, juliusknorr approved these changes
Small comment, otherwise :+1: from my side.

2020-08-07 07:27 UTC, MorrisJobke commented on lib/private/Preview/Storage/Root.php
> +		if ($this->isMultibucketPreviewDistributionEnabled) {
Good point. Let me do this in a followup PR because this is unrelated to this changeset in general.

2020-08-07 07:28 UTC, merged

2020-08-07 07:29 UTC, MorrisJobke commented on lib/private/Preview/Storage/Root.php
> +		if ($this->isMultibucketPreviewDistributionEnabled) {
I just noticed that you are right. Was related to this PR -> anyways. I will move it one step downwards.

2020-08-07 07:38 UTC, MorrisJobke commented on lib/private/Preview/Storage/Root.php
> +		if ($this->isMultibucketPreviewDistributionEnabled) {
#22139 - I made it the last step instead of the first one.