App navigation via unified search
nextcloud/server pull request #22102
Opened 2020-08-04 14:24 UTC by nickvergessen

![Bildschirmfoto von 2020-08-04 16-23-12](https://user-images.githubusercontent.com/213943/89305362-d6fef080-d66e-11ea-871a-7c603ee942f9.png)

Branch targets #22099

2020-08-04 15:01 UTC, skjnldsv commented
Pls rebase :p

2020-08-04 15:34 UTC, jancborchardt commented
As discussed:

>  We could possibly add "Help" in results (referring to documentation). E.g. macOS also has these nice "Help" results when searching inside of an app via the app menu.

This should be sorted all the way down, below settings. Cause ideally settings already gives you the answer, and then "Help" is the last error prevention. :)

2020-08-05 14:42 UTC, nickvergessen commented
Rebased with order adjustments

2020-08-05 14:42 UTC, skjnldsv approved these changes

2020-08-05 14:45 UTC, skjnldsv commented on apps/settings/lib/Search/AppSearch.php
> +				'',
Btw, is there no other way for an API to have empty strings like that? Is that good practices?

2020-08-05 15:18 UTC, skjnldsv commented on apps/settings/lib/Search/AppSearch.php
> +		return -1;
Jan said it should always be the very top, so maybe something crazy like -50 ?

2020-08-05 15:23 UTC, skjnldsv commented on apps/settings/lib/Search/AppSearch.php
> +		return -1;
I'll do it in a followup, let get this in

2020-08-05 15:26 UTC, jancborchardt requested changes
Looks good! :+1: to @skjnldsv’s feedback, and also I found one entry which doesn’t really make sense – there’s possibly more which we might need to filter?
![image](https://user-images.githubusercontent.com/925062/89431937-d46ccb80-d740-11ea-8392-946c3419e3b0.png)

2020-08-05 15:27 UTC, jancborchardt approved these changes
My feedback can also be fixed in a follow-up tho.

2020-08-05 15:52 UTC, nickvergessen commented
> there’s possibly more which we might need to filter?

Well user status is registering a navigation link which is highjacked by JS. I'm not aware we have more of this, but now fixed by ignoring empty link items

Fix both issues.

2020-08-05 20:52 UTC, MorrisJobke approved these changes
How nice is this?!? :) I love it already 👍

2020-08-05 20:53 UTC, merged