[WIP] weather status used in dashboard
nextcloud/server pull request #22124
Opened 2020-08-06 09:00 UTC by eneiluj

I did more or less the same as the user status. It's inserted in dashboard statuses.

There's a new `weather_status` module that needs to be built.

It's an independent app in case we want to use it in Calendar for example.
It uses `api.met.no` to get forecasts and `nominatim.openstreetmap.org` to search and resolve locations.

One thing I'm not sure about: How to make sure the weather status script is loaded when browsing dashboard page. I did it in the dashboard template...

Todo:
* [ ] let the user choose to use the address set in personal settings to determine location and use it for weather
* [ ] remove debug logs
* [ ] improve backend error management

2020-08-06 11:29 UTC, jancborchardt commented
cc @berdosi of the Weather app, maybe you are interested to take a look at this? :) This is explicitly direct integration only (in Dashboard and possibly in Calendar), and it would still make sense to have a bespoke Weather app.

2020-08-07 12:52 UTC, juliushaertl commented on apps/weather_status/img/app-dark.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
You can minify these svgs with `./build/image-optimization.sh [YOUR_APP_PATH]` in the server repo.

2020-08-07 23:42 UTC, jancborchardt approved these changes
Aaaaawesome! :)

2020-08-08 07:55 UTC, splitt3r commented on apps/weather_status/appinfo/info.xml
> +            <id>user_status-menuitem</id>
```suggestion
            <id>weather_status-menuitem</id>
```

2020-08-08 07:55 UTC, splitt3r commented on apps/weather_status/appinfo/info.xml
> +    <author mail="eneiluj@posteo.net" >Julien Veyssier</author>
```suggestion
    <author mail="eneiluj@posteo.net">Julien Veyssier</author>
```

2020-08-08 07:56 UTC, splitt3r requested changes
Looks great 😍 small nitpicks

2020-08-09 07:04 UTC, splitt3r approved these changes

2020-08-09 07:07 UTC, splitt3r commented
The GitHub Actions failures look related but easy to fix :grin:

2020-08-09 09:55 UTC, splitt3r commented
I think you need to add your new app to https://github.com/nextcloud/server/blob/b585aefcea53d28b261a48f9c885351e286b5d60/build/integration/features/provisioning-v1.feature#L351. To make `integration-provisioning-v1` pass.

2020-08-10 12:43 UTC, eneiluj commented
@splitt3r Thanks for the hints. I can't figure out how to get rid of this last CI-drone failure... Any idea?

2020-08-10 12:48 UTC, juliushaertl commented on apps/weather_status/src/weather-status.js
> +// import store from './store'
:broom:

2020-08-10 12:49 UTC, juliushaertl commented on apps/weather_status/src/weather-status.js
> +	// store,
:broom:

2020-08-10 12:50 UTC, juliushaertl commented on apps/weather_status/src/weather-status.js
> +	// store,
No need for the const app at all :wink:

2020-08-10 13:32 UTC, splitt3r commented
> @splitt3r Thanks for the hints. I can't figure out how to get rid of this last CI-drone failure... Any idea?

I think that one is unrelated. Looks like the test fails in all recent MRs e.g. https://github.com/nextcloud/server/pull/22151#issuecomment-671220327.

2020-08-10 14:49 UTC, eneiluj commented
@juliushaertl History and code cleanup done, rebased on master, ready to merge :tada:.

2020-08-10 22:19 UTC, go2sh commented
You should Think about caching or do the weather requests on the client. Otherwise you might violate the tos of the api, especially on big instances.

2020-08-11 07:51 UTC, eneiluj commented
> You should Think about caching or do the weather requests on the client. Otherwise you might violate the tos of the api, especially on big instances. And thus might get blocked etc.

Thanks for the feedback.
I'd like to avoid letting the client do the requests to avoid changing the CSP.

With one request per hour, even if the request is cached on the client, it would be useless as we want a forecast update every hour.

I figured one request per hour per user was not so much, even with a large user number.

If caching was done on server side, it would factorize all requests for the same location. I'll probably do it but it's not trivial, it requires to store results, clean cache at some point...

2020-08-11 13:34 UTC, go2sh commented
How do you limit to 1 request per hour on the server. Through client caching?

2020-08-11 13:47 UTC, eneiluj commented
There is no limit if users reload the page, but the script is looping at 1 request/hour frequency.

No client caching for the moment, this would be a solution for multiple requests coming from the same user (page reload). I'll do it too.

Server side caching would be useful if many users are at the same location. To be continued.

2020-08-11 14:15 UTC, rullzer submitted a review, later dismissed
In general i think we should have a switch somewhere. Or at least tell the users that their data is send to 3rdparty services if they enable this.

Just doing this automatically is not really GDPR compliant.

2020-08-11 14:15 UTC, rullzer commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +					'User-Agent' => 'Nextcloud weather status'
I don't think this is enough.
See: https://api.met.no/doc/TermsOfService

2020-08-11 14:15 UTC, rullzer commented on apps/weather_status/src/App.vue
> +	</li>
Somehow somewhere we need to show attribution
See: https://api.met.no/doc/TermsOfService

2020-08-11 14:15 UTC, rullzer commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$weather = $this->requestJSON($url, $params);
some caching here would be good see the terms of service:

* Do not ask too often, and don't repeat requests until the time indicated in the Expires response header.
* Cache data locally and and use the If-Modified-Since request header to avoid repeatedly downloading the same data.

Just a simple distributed cache that stores the data for an hour or so can just directly return without fetching

2020-08-11 14:15 UTC, rullzer commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$weather = $this->requestJSON($url, $params);
Actually i think we have to reach out ot them. beause if all servers start using this it is likely we hit this:

Anything over 20 requests/second per application (total, not per client) requires special agreement. If you have a mobile app, this means the total traffic from all installations. For websites, this means the total for all servers and/or traffic coming directly from the browsers. Sites exceeding this limit are likely to be throttled, possibly also blocked if we cannot contact you for optimization.

2020-08-11 17:26 UTC, eneiluj commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +					'User-Agent' => 'Nextcloud weather status'
The new one is `NextcloudWeatherStatus/0.0.2 nextcloud.com`.

2020-08-11 17:26 UTC, eneiluj commented on apps/weather_status/src/App.vue
> +	</li>
Attributions are now in the menu. It takes a lot of space. Any idea where to move them? @jancborchardt In the "customize" modal?

2020-08-11 17:28 UTC, eneiluj commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$weather = $this->requestJSON($url, $params);
Distributed caching takes care or all requests and caches everything for 1 hour.

I'll reach out to them soon. Thanks for your review!

2020-08-12 09:54 UTC, eneiluj commented
"Last-Modified" is never set in Nominatim responses and always equals "now" for met.no. So using "If-Modified-Since" in requests will never lead to 304 response.

Here are the two things done for caching:
* Store results in distributed cache
* Reduce lat/lng precision to 3 digits to increase the cache hit ratio of reverse geocoding and weather requests. Still precise enough to get valid results :grin:.

The failing node check is caused (i think) by the dashboard files that were committed after a "npm run dev" and not "npm run build". The continuous-integration/drone/pr is apparently unrelated too.

So in my opinion: ready to merge.

2020-08-12 20:40 UTC, jancborchardt commented
Regarding 1 request per hour: Are the requests all sent on the full hour? Cause then it could still result in a DDoS – maybe we should randomize the check time slightly (I remember the API ToS requested something like that).

2020-08-13 07:56 UTC, eneiluj commented
@jancborchardt The 1req/hour loop is done on the client side and starts on page load. No problem.

Plus the 3 digits precision for lat/lng increase chances that if multiple users are in the same area, one will actually make the geocoding and weather requests and the others will get information from server side cache.

imho it's already good as it is.

2020-08-17 20:15 UTC, skjnldsv commented
Please squash commits and we get this in :rocket: :wink:

2020-08-17 21:19 UTC, skjnldsv commented on apps/weather_status/img/app-dark.svg
> +<svg width="280.5" height="280.5" version="1.1" viewBox="0 0 280.5 280.5" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><g transform="matrix(1.3333 0 0 -1.3333 -844.1 756.63)"><g transform=
```suggestion
<svg width="280.5" height="280.5" xmlns="http://www.w3.org/2000/svg"><path d="M140.22 210.04c38.48 0 69.78-31.3 69.78-69.78s-31.3-69.78-69.78-69.78c-38.47 0-69.78 31.3-69.78 69.78s31.3 69.78 69.78 69.78M132.8 38.9a7.43 7.43 0 0014.85 0V7.44a7.43 7.43 0 00-14.85 0V38.9M132.8 241.63v31.46a7.43 7.43 0 0014.85 0v-31.46a7.43 7.43 0 00-14.85 0M89.54 59.91a7.43 7.43 0 006.43-11.14L80.24 21.53a7.43 7.43 0 00-12.86 7.43L83.1 56.2a7.42 7.42 0 006.43 3.71M187.2 221.62a7.43 7.43 0 00-2.72 10.14L200.2 259a7.42 7.42 0 1012.86-7.42l-15.73-27.25a7.43 7.43 0 00-10.15-2.71M18.76 70.14a7.43 7.43 0 002.72 10.15L48.72 96a7.42 7.42 0 107.43-12.86L28.9 67.42a7.43 7.43 0 00-10.14 2.72M258.97 200.24l-27.25-15.73a7.43 7.43 0 00-7.42 12.87l27.24 15.73a7.4 7.4 0 0010.14-2.72 7.43 7.43 0 00-2.71-10.15M46.28 140.27c0-4.1-3.33-7.42-7.43-7.42H7.4a7.43 7.43 0 000 14.85h31.46c4.1 0 7.43-3.33 7.43-7.43M273.05 132.85h-31.46a7.43 7.43 0 000 14.85h31.46a7.43 7.43 0 000-14.85M48.73 184.51L21.5 200.24a7.43 7.43 0 107.42 12.86l27.25-15.73a7.43 7.43 0 00-7.43-12.86M251.54 67.42L224.3 83.15A7.43 7.43 0 00231.72 96l27.24-15.73a7.43 7.43 0 00-7.42-12.86M83.1 224.34l-15.73 27.24a7.43 7.43 0 0012.87 7.43l15.73-27.25a7.43 7.43 0 00-12.87-7.42M187.2 58.91a7.4 7.4 0 0010.14-2.71l15.73-27.25a7.43 7.43 0 10-12.86-7.42l-15.73 27.24a7.43 7.43 0 002.71 10.14"/></svg>
```

Cleaned up and simplified version

2020-08-17 21:20 UTC, skjnldsv commented on apps/weather_status/img/app.svg
> +<svg width="280.5" height="280.5" version="1.1" viewBox="0 0 280.5 280.5" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><g transform="matrix(1.3333 0 0 -1.3333 -844.1 756.63)"><g transform=
```suggestion
<svg width="280.5" height="280.5" xmlns="http://www.w3.org/2000/svg"><g fill="#fff"><path d="M140.22 210.04c38.48 0 69.78-31.3 69.78-69.78s-31.3-69.78-69.78-69.78c-38.47 0-69.78 31.3-69.78 69.78s31.3 69.78 69.78 69.78M132.8 38.9a7.43 7.43 0 0014.85 0V7.44a7.43 7.43 0 00-14.85 0V38.9M132.8 241.63v31.46a7.43 7.43 0 0014.85 0v-31.46a7.43 7.43 0 00-14.85 0M89.54 59.91a7.43 7.43 0 006.43-11.14L80.24 21.53a7.43 7.43 0 00-12.86 7.43L83.1 56.2a7.42 7.42 0 006.43 3.71M187.2 221.62a7.43 7.43 0 00-2.72 10.14L200.2 259a7.42 7.42 0 1012.86-7.42l-15.73-27.25a7.43 7.43 0 00-10.15-2.71M18.76 70.14a7.43 7.43 0 002.72 10.15L48.72 96a7.42 7.42 0 107.43-12.86L28.9 67.42a7.43 7.43 0 00-10.14 2.72M258.97 200.24l-27.25-15.73a7.43 7.43 0 00-7.42 12.87l27.24 15.73a7.4 7.4 0 0010.14-2.72 7.43 7.43 0 00-2.71-10.15M46.28 140.27c0-4.1-3.33-7.42-7.43-7.42H7.4a7.43 7.43 0 000 14.85h31.46c4.1 0 7.43-3.33 7.43-7.43M273.05 132.85h-31.46a7.43 7.43 0 000 14.85h31.46a7.43 7.43 0 000-14.85M48.73 184.51L21.5 200.24a7.43 7.43 0 107.42 12.86l27.25-15.73a7.43 7.43 0 00-7.43-12.86M251.54 67.42L224.3 83.15A7.43 7.43 0 00231.72 96l27.24-15.73a7.43 7.43 0 00-7.42-12.86M83.1 224.34l-15.73 27.24a7.43 7.43 0 0012.87 7.43l15.73-27.25a7.43 7.43 0 00-12.87-7.42M187.2 58.91a7.4 7.4 0 0010.14-2.71l15.73-27.25a7.43 7.43 0 10-12.86-7.42l-15.73 27.24a7.43 7.43 0 002.71 10.14"/></g></svg>
```

2020-08-17 21:22 UTC, skjnldsv reviewed
Lotds of svg have transforms filters, you can simplify them.
Passing them to https://jakearchibald.github.io/svgomg/ with precision 2 should be enough,  but make sure the visual looks the same. :)
It will round unwanted extreme float precision and remove unecessary transforms and matrix :wink:

2020-08-17 21:23 UTC, skjnldsv commented on apps/weather_status/lib/AppInfo/Application.php
> +			Util::addScript('weather_status', 'weather-status');
```suggestion
			Util::addScript(self::APP_ID, 'weather-status');
```

2020-08-17 21:24 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$this->version = $appManager->getAppVersion('weather_status');
```suggestion
		$this->version = $appManager->getAppVersion(Application::APP_ID);
```

Same goes for the other occurences?
Just cleanup :)

2020-08-17 21:25 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +	<li :class="{inline: inline }">
```suggestion
	<li :class="{inline }">
```

2020-08-17 21:27 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +			},
Looks like it calls for a const model with an enum :)

const options = [
	{
		icons: '',
		name: t('weather_status', '')
	},
	...
]

2020-08-17 21:28 UTC, skjnldsv commented on apps/weather_status/src/weather-status.js
> +Vue.prototype.$t = t
One or the other? Maybe not the two? :p

2020-08-17 21:28 UTC, skjnldsv commented on apps/weather_status/src/weather-status.js
> +__webpack_public_path__ = OC.linkTo('weather_status', 'js/')
Use `@nextcloud/router`

2020-08-17 21:29 UTC, skjnldsv reviewed
A few comments and cleanup here and there :wink:

2020-08-18 06:27 UTC, skjnldsv commented on apps/weather_status/lib/Capabilities.php
> +			'weather_status' => [
```suggestion
			Application::APP_ID => [
```

2020-08-18 07:36 UTC, eneiluj commented
@skjnldsv Thanks a lot for your review. Rebased and squashed again.

2020-08-18 11:06 UTC, juliusknorr approved these changes

2020-08-18 11:32 UTC, skjnldsv commented on apps/weather_status/appinfo/info.xml
> +    <description><![CDATA[Weather status]]></description>
Maybe a bit more descriptive text? :p

2020-08-18 11:35 UTC, MorrisJobke commented
One little thing:

* [ ] in a colored background you see that the elements are too close to each other - is this related to this PR or to the general dashboard one?

<img width="557" alt="Bildschirmfoto 2020-08-18 um 13 34 49" src="https://user-images.githubusercontent.com/245432/90508270-b303da80-e157-11ea-9afa-22fdf2543422.png">

2020-08-18 11:41 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	public function setLocation(string $address = '', $lat = null, $lon = null): array {
Missing docs

2020-08-18 11:41 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	public function usePersonalAddress(): array {
Missing docs

2020-08-18 11:41 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	public function setMode(int $mode): array {
Missing docs

2020-08-18 11:42 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$this->config->setUserValue($this->userId, 'weather_status', 'mode', $mode);
```suggestion
		$this->config->setUserValue($this->userId, Application::APP_ID, 'mode', $mode);
```

2020-08-18 11:42 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +			$this->config->setUserValue($this->userId, 'weather_status', 'address', $address);
```suggestion
			$this->config->setUserValue($this->userId, Applicarion:APP_ID, 'lat', $lat);
			$this->config->setUserValue($this->userId, Applicarion:APP_ID, 'lon', $lon);
			$address = $this->resolveLocation($lat, $lon);
			$address = $address ? $address : $this->l10n->t('Unknown address');
			$this->config->setUserValue($this->userId, Applicarion:APP_ID, 'address', $address);
```

2020-08-18 11:43 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +			$this->config->setUserValue($this->userId, 'weather_status', 'mode', self::MODE_MANUAL_LOCATION);
```suggestion
			$this->config->setUserValue($this->userId, Application:APP_ID, 'address', $formattedAddress);
			$this->config->setUserValue($this->userId, Application:APP_ID, 'lat', $addressInfo['lat']);
			$this->config->setUserValue($this->userId, Application:APP_ID, 'lon', $addressInfo['lon']);
			$this->config->setUserValue($this->userId, Application:APP_ID, 'mode', self::MODE_MANUAL_LOCATION);
```

2020-08-18 11:43 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$mode = $this->config->getUserValue($this->userId, 'weather_status', 'mode', self::MODE_MANUAL_LOCATION);
```suggestion
		$lat = $this->config->getUserValue($this->userId, Application:APP_ID, 'lat', '');
		$lon = $this->config->getUserValue($this->userId, Application:APP_ID, 'lon', '');
		$address = $this->config->getUserValue($this->userId, Application:APP_ID, 'address', '');
		$mode = $this->config->getUserValue($this->userId, Application:APP_ID, 'mode', self::MODE_MANUAL_LOCATION);
```

2020-08-18 11:43 UTC, skjnldsv commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +		$lon = $this->config->getUserValue($this->userId, 'weather_status', 'lon', '');
```suggestion
		$lat = $this->config->getUserValue($this->userId, Application:APP_ID, 'lat', '');
		$lon = $this->config->getUserValue($this->userId, Application:APP_ID, 'lon', '');
```

2020-08-18 11:45 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +const weatherOptions = {
Nice! :)

2020-08-18 11:45 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +		async bootstrap() {
Not very lear what bootstrap means nor what does it do :wink: :shrug:

2020-08-18 11:46 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +	background-image: url(./../img/sun.svg);
DOn't you need quotes? I'm impressed it works without nor does trow errors :)

2020-08-18 11:47 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +.lightrain {
```suggestion
.icon-lightrain {
```

Seems like a typo?

2020-08-18 11:49 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +				id="weather-status-menu-item__subheader"
BEM structure applies to classes, id is something that should be avoided

2020-08-18 11:51 UTC, skjnldsv commented on apps/weather_status/src/App.vue
> +	<li :class="{ inline }">
This class is a bit weird, I don't undrestand what it does. Can you maybe have a class wrapper with proper BEM syntax?

`.weather-status__menu .weather-status__menu--inline` :shrug:

2020-08-18 11:52 UTC, skjnldsv requested changes
See more comments :)

2020-08-18 11:59 UTC, nickvergessen commented on apps/weather_status/appinfo/info.xml
> +    <category></category>
@juliushaertl do we have a dashboard type already?

2020-08-18 12:12 UTC, eneiluj commented
> One little thing:
> 
>     * [ ]  in a colored background you see that the elements are too close to each other - is this related to this PR or to the general dashboard one?

@MorrisJobke It can be solved in both weather status or general dashboard. I would recommend to do it in general dashboard. It's been mentioned in #22214.

2020-08-18 12:36 UTC, juliushaertl commented on apps/weather_status/appinfo/info.xml
> +    <category></category>
yes, https://github.com/nextcloud/appstore/pull/737

2020-08-18 12:36 UTC, juliushaertl commented
> @MorrisJobke It can be solved in both weather status or general dashboard. I would recommend to do it in general dashboard. It's been mentioned in #22214.

I'll take care of that in the dashboard pr.

2020-08-18 12:58 UTC, eneiluj commented on apps/weather_status/src/App.vue
> +const weatherOptions = {
:smile_cat:

2020-08-18 13:02 UTC, eneiluj commented on apps/weather_status/src/App.vue
> +	<li :class="{ inline }">
It's just in case the status is displayed somewhere else. In this case, in the dashboard, we want it to be inline.

I just imitated what was done for the user status.

2020-08-18 13:05 UTC, eneiluj commented
@skjnldsv @nickvergessen Thanks a lot for the reviews! Rebased and squashed again.

I just need to add something to get the elevation because forecast service is very altitude-sensitive. I'll re-request your reviews later.

2020-08-19 14:09 UTC, nickvergessen commented
Looks weird when they touch, I think:

![Bildschirmfoto von 2020-08-19 16-08-13](https://user-images.githubusercontent.com/213943/90645523-52979a80-e236-11ea-8648-9fd59d84d9ec.png)

2020-08-19 14:12 UTC, eneiluj commented
> Looks weird when they touch, I think:

Spacing between statuses will be fixed in dashboard PR as mentioned earlier (https://github.com/nextcloud/server/pull/22124#issuecomment-675452247)

2020-08-19 14:24 UTC, nickvergessen requested changes
Some PHP coding style comments.

Also I noticed: my location is New York, my language en US and my locale en US. I should see the temperature in °F ? but it just says `23°` so I grab a jacket and go fetch my skiers? At least `23° C` needs to be shown, but if possible °F

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/appinfo/info.xml
> +    <version>0.0.2</version>
```suggestion
    <version>1.0.0</version>
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/appinfo/info.xml
> +    <summary>Weather status</summary>
```suggestion
    <summary>Weather status in your dashboard</summary>
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Controller/WeatherStatusController.php
> +	public function setMode($mode): DataResponse {
```suggestion
	public function setMode(int $mode): DataResponse {
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Controller/WeatherStatusController.php
> +	public function setMode($mode): DataResponse {
also missing from the doc block

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Controller/WeatherStatusController.php
> +	public function setLocation($address, $lat, $lon): DataResponse {
```suggestion
	public function setLocation(string $address, ?float $lat, ?float $lon): DataResponse {
```

also missing from the doc block

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	public function setLocation(string $address = '', $lat = null, $lon = null): array {
```suggestion
	 * @param string $address Any approximative or exact address
	 * @param float|null $lat Latitude in decimal degree format
	 * @param float|null $lon Longitude in decimal degree format
	 * @return array with success state and address information
	 */
	public function setLocation(string $address = '', ?float $lat = null, ?float $lon = null): array {
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	private function resolveLocation($lat, $lon) {
```suggestion
	 * @param float $lat Latitude in decimal degree format
	 * @param float $lon Longitude in decimal degree format
	 */
	private function resolveLocation(float $lat, float $lon): ?string {
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	private function getAltitude($lat, $lon): float {
```suggestion
	 * @param float $lat Latitude in decimal degree format
	 * @param float $lon Longitude in decimal degree format
	 * @return float altitude in meter
	 */
	private function getAltitude(float $lat, float $lon): float {
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/lib/Service/WeatherStatusService.php
> +	private function formatOsmAddress($json): ?string {
```suggestion
	private function formatOsmAddress(array $json): ?string {
```

2020-08-19 14:24 UTC, nickvergessen commented on apps/weather_status/src/App.vue
> +					? this.sixHoursTempForecast + '° ' + this.weatherText
Please avoid string concatenation like this and in weatherText
It only works in some languages.

2020-08-19 16:18 UTC, eneiluj commented
Recent changes:
* Elevation is now more precise (to get more precise temperature)
* Temperature is now displayed in Fahrenheit for those locales : 'en_US', 'en_MH', 'en_FM', 'en_PW', 'en_KY', 'en_LR'
* Bump to v1.0.0
* More details in info.xml summary
* Code style fixed

Rebased on master and commits squashed.

2020-08-19 17:40 UTC, MorrisJobke commented
@eneiluj Once rebased on current master Psalm will also be more happy because #22304 was merged.

2020-08-19 17:51 UTC, MorrisJobke commented
The remaining complain is just about more fixed stuff, just ignore for now. 🚀 good go

2020-08-19 17:54 UTC, eneiluj commented
@MorrisJobke There should be a CI job checking the validity of the CI jobs check code :wink: Thanks for the hint.

2020-08-19 18:46 UTC, MorrisJobke commented
> @MorrisJobke There should be a CI job checking the validity of the CI jobs check code 😉 Thanks for the hint.

I have already something in mind to avoid this mess, but one step after the other :)

2020-08-19 19:21 UTC, nickvergessen approved these changes
:elephant:

2020-08-19 19:21 UTC, nickvergessen commented on apps/weather_status/src/App.vue
> +		text: t('weather_status', 'Clear sky'),
You actually "string concatenate" quite hard here: `71.4 °F Clear sky at 2:00 AM`

As per https://docs.nextcloud.com/server/19/developer_manual/app/view/l10n.html#improving-your-translations that is quite bad. It would be better to have this strings as:

```suggestion
		text: t('weather_status', '{temperature} Clear sky at {time}'),
```

Than translators can make sure it matches their language. and you either string-replace the values in, or actually provide them as parameters to the translation.

2020-08-19 22:55 UTC, jancborchardt commented
Rebased now that the Dashboard background is merged, and fixed the small design issues (statuses touching, font size being too small, them not wrapping on mobile, background of weather status button looking different).

2020-08-19 22:55 UTC, jancborchardt approved these changes
Good from my side! :)

2020-08-20 06:05 UTC, merged

2020-08-20 06:20 UTC, skjnldsv commented
@eneiluj 
Geolocation doesn't work for me
I have the same as https://github.com/nextcloud/maps/issues/229

> Geolocation has been disabled in this document by Feature Policy

2020-08-20 06:30 UTC, rullzer commented
> @eneiluj
> Geolocation doesn't work for me
> I have the same as [nextcloud/maps#229](https://github.com/nextcloud/maps/issues/229)
> 
> > Geolocation has been disabled in this document by Feature Policy

AH yes you need to listen to the event when you show this and enable it. Let me see if I can do that.

2020-08-20 09:28 UTC, jancborchardt commented
Congrats on the merge! :) Finally it all works in concert together!

2020-08-20 09:30 UTC, eneiluj commented
@jancborchardt thanks! so nice to use everything without rebuilding :grin:. the design is simply awesome. thanks a lot!