merge activity settings for calendars, events and todos
nextcloud/server pull request #22134
Opened 2020-08-06 14:51 UTC by icewind1991

Signed-off-by: Robin Appelman <robin@icewind.nl>

2020-08-06 22:41 UTC, MorrisJobke approved these changes
Fine with me

2020-08-10 13:37 UTC, jancborchardt commented
Please review @nextcloud/calendar @nextcloud/tasks :)

2020-08-10 13:38 UTC, georgehrke commented
What is the intention here? Is there any related Github issue?

2020-08-11 18:52 UTC, rullzer commented
To have cleaner notifiation settings

2020-08-11 19:53 UTC, MorrisJobke commented
Before:
![Bildschirmfoto 2020-08-11 um 21 53 30](https://user-images.githubusercontent.com/245432/89942582-2029e400-dc1d-11ea-9179-c49597a281a3.png)
After:
![Bildschirmfoto 2020-08-11 um 21 53 18](https://user-images.githubusercontent.com/245432/89942579-1ef8b700-dc1d-11ea-84a2-5847290258bb.png)

2020-08-12 06:19 UTC, rullzer commented
> Before:
> ![Bildschirmfoto 2020-08-11 um 21 53 30](https://user-images.githubusercontent.com/245432/89942582-2029e400-dc1d-11ea-9179-c49597a281a3.png)
> After:
> ![Bildschirmfoto 2020-08-11 um 21 53 18](https://user-images.githubusercontent.com/245432/89942579-1ef8b700-dc1d-11ea-84a2-5847290258bb.png)

I think you switched before and after ;)

2020-08-12 08:48 UTC, rullzer approved these changes

2020-08-12 08:49 UTC, georgehrke reviewed
Code-wise the change is fine.

Not really happy about it though.

2020-08-12 08:57 UTC, tcitworld commented
Yeah, don't really like it either, pretty sure people won't be happy not having separate settings anymore. For instance, the deletion of a (shared) calendar is a pretty much important event that people may want to subscribe to without knowing of every event or task updates.

Why not use #22117 to create a proper dav group if the issue is too many checkboxes?

2020-08-13 03:08 UTC, rullzer commented
cc: @jancborchardt ^^^

2020-08-14 12:54 UTC, jancborchardt commented
To have the settings cleaner but also useful, we should not have the Calendar and Tasks settings in "Other activities" but rather a specific section "Calendar and Tasks" – I assume that’s what you meant @tcitworld, right?

In there we can then have entries for:

- A calendar was modified
- A calendar was deleted
- A calendar event was modified
- A calendar event was deleted
- A task was modified
- A task was deleted

Would that work @georgehrke @tcitworld?

2020-08-14 13:01 UTC, tcitworld commented
Right now we don't differentiate between calendar/event/tasks modifications or deletions, but yeah, that seems about right.

2020-08-19 14:02 UTC, nickvergessen requested changes

2020-08-19 14:02 UTC, nickvergessen commented on apps/dav/appinfo/info.xml
> -			<filter>OCA\DAV\CalDAV\Activity\Filter\Todo</filter>
Merging the settings fine by me, but the filter is really useful I think, as when you use fully interact with todos, the calendar changes are hard to find if they are all in one filter.

2020-08-19 14:05 UTC, nickvergessen commented
I think the list could be simplified, but this is the minimum:


- A calendar was modified (created, deleted, shared, ...)
- A calendar event was modified (created, deleted, updated same as files)
- A task was modified (created, deleted, updated same as files)

2020-08-20 20:07 UTC, jancborchardt commented
> I think the list could be simplified, but this is the minimum:
> * A calendar was modified (created, deleted, shared, ...)
> * A calendar event was modified (created, deleted, updated same as files)
> * A task was modified (created, deleted, updated same as files)

Then let’s do that and put it in a section "Calendar and tasks" so it’s not just in "Other". @icewind1991 can you do that?

2020-08-20 20:44 UTC, nickvergessen commented
No, he is on vacation

2020-08-25 17:13 UTC, icewind1991 commented
Changed:

![image](https://user-images.githubusercontent.com/1283854/91206131-2d070700-e6f6-11ea-8b78-5527d77a236b.png)

2020-08-25 19:18 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Setting/CalDAVSetting.php
> +		return $this->l->t("Calendar and tasks");
```suggestion
		return $this->l->t('Calendar and tasks');
```

2020-08-25 19:19 UTC, nickvergessen approved these changes

2020-08-26 13:56 UTC, merged