add personal addtional settign section
nextcloud/server pull request #22144
Opened 2020-08-07 19:51 UTC by dassio

in the [developer manual settings section](https://docs.nextcloud.com/server/stable/developer_manual/app/settings.html?highlight=settings),  there is a mentioning of `additional` default section, but it only appears on the admin part, not on the person part. resulting in apps that are meant for non-admin users can not use the default additional section, this pull request is to add the personal default `Additional settings`

2020-08-25 20:21 UTC, dassio commented
are there anyone who can help to review this one ?

2020-08-26 07:46 UTC, ChristophWurst approved these changes
Fine by me :)

2020-08-26 08:46 UTC, juliushaertl requested changes
There seems to be an issue that the section will still be shown empty if no additional settings are available, could you look into that again?

2020-08-26 08:47 UTC, juliushaertl commented
Ah seems to be related to the this settings class: https://github.com/nextcloud/server/blob/41b5e5923a44965e435d35d01b5009abb2dd5c97/apps/settings/lib/Settings/Personal/Additional.php#L30

2020-08-26 09:15 UTC, dassio commented
> Ah seems to be related to the this settings class:
> 
> https://github.com/nextcloud/server/blob/41b5e5923a44965e435d35d01b5009abb2dd5c97/apps/settings/lib/Settings/Personal/Additional.php#L30

@ChristophWurst , can we delete this empty settings, or we have any paticular reason to keep it ?

2020-08-26 12:55 UTC, dassio commented
@juliushaertl  @rullzer  @kesselb  please help to review 
I deleted the empty personal setting view

2020-09-01 08:10 UTC, dassio commented
can we merge this one now?  I just did a rebase on master

2020-09-01 08:13 UTC, juliushaertl commented on apps/settings/lib/Settings/Personal/Additional.php
> -		return new TemplateResponse('settings', 'settings/empty');
I'm not entirely sure about the complete removal yet, as it was a fallback for old settings registration iirc, so this would need to be checked if it still works.

2020-09-01 08:58 UTC, dassio commented on apps/settings/lib/Settings/Personal/Additional.php
> -		return new TemplateResponse('settings', 'settings/empty');
you are correct

I tried with this app [Ebook Reader 1.4.2](https://apps.nextcloud.com/apps/epubreader), is we remove this, we can't find the setting anymore 
I will add it back

2020-09-01 15:21 UTC, dassio commented on apps/settings/lib/Settings/Personal/Additional.php
> -		return new TemplateResponse('settings', 'settings/empty');
I reverted it back and fix the duplicate addtional issue, not sure how to make the empty addtional go away

2020-09-04 20:06 UTC, kesselb commented
> There seems to be an issue that the section will still be shown empty if no additional settings are available, could you look into that again?

Sounds like https://github.com/nextcloud/server/pull/22144 @juliushaertl @nickvergessen :thinking:

2020-09-05 14:41 UTC, dassio commented
blank addtional section removed @kesselb 


![addtional-section-flow-chart](https://user-images.githubusercontent.com/733502/92307397-6eb96c80-ef96-11ea-9e05-a512cfa7d941.jpg)

2020-09-05 14:56 UTC, kesselb commented
> blank addtional section removed @kesselb

Sorry. I don't know much about the settings area. It was not my intention to request changes. I just noticed the other pull requested and added a hint. We have to wait for the other reviews to specify the expected behaviour and how those pull requests work together.

2020-09-07 09:48 UTC, closed without merging

2020-09-07 09:49 UTC, dassio commented
solved by #22589

2020-09-09 11:18 UTC, nickvergessen commented
Sorry @dassio I didn't see your PR before creating mine, and since the one line diff on my is easier I guess that is why it got merged. Thanks for the work anyway!

2020-09-09 11:23 UTC, nickvergessen commented
> > this is because there is no an personal addtional section in the settings app, shouldn't we add the section instead of hacking the system ? it will make later comer much eaiser to understand the structure.
> 
> While I agree in general, the one liner is much easier to be backported. So let's make it properly (like in the admin section?) with your PR, and only do the minimal impact PR for the backporting