SSE: make legacy format opt in
nextcloud/server pull request #22218
Opened 2020-08-12 11:37 UTC by rullzer

Basically a switch (off by default for new installations) to support the legacy format or not.
This should hopefully allow us to kill the old ways at some point.

Future work:
- [ ] Write docs
- [ ] Setupcheck that checks for the config.php flag and links to the docs where we explain this
- [ ] occ command to scan the files to see if there are any files that use the old format

2020-08-12 11:47 UTC, ChristophWurst commented on lib/private/Repair/NC20/EncryptionLegacyCipher.php
> +			$this->config->setSystemValue('encryption.legacy_format_support', true);
how about only setting this if it's not set already? I don't think it's very likely to exist before, but maybe an admin put it there before the update

2020-08-12 12:23 UTC, rullzer commented on lib/private/Repair/NC20/EncryptionLegacyCipher.php
> +			$this->config->setSystemValue('encryption.legacy_format_support', true);
You mean they set it to false already? Yeah fair enough

2020-08-12 12:27 UTC, ChristophWurst commented on lib/private/Repair/NC20/EncryptionLegacyCipher.php
> +			$this->config->setSystemValue('encryption.legacy_format_support', true);
Exactly. Very unlikely, but better safe than sorry

2020-08-12 13:18 UTC, MorrisJobke commented
> * 
> * [x]  Setupcheck that checks for the config.php flag and links to the docs where we explain this [a77c891](https://github.com/nextcloud/server/commit/a77c891e924ef368a49ef56791fd0823ae4568dc)

Done

2020-08-12 14:41 UTC, ChristophWurst approved these changes

2020-08-17 09:51 UTC, nickvergessen approved these changes

2020-08-18 08:34 UTC, nickvergessen requested changes
Bail out immediately when you found a negative one.

2020-08-18 08:34 UTC, nickvergessen commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +					$clean = false;
```suggestion
					return false;
```

2020-08-18 08:34 UTC, nickvergessen commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +					$clean = false;
```suggestion
					return false;
```

2020-08-18 08:34 UTC, nickvergessen commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +					$result &= $this->scanFolder($output, '/' . $user);
```suggestion
					if (!$this->scanFolder($output, '/' . $user)) {
						$result = false;
						break 2;
					}
```

2020-08-18 08:36 UTC, rullzer commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +					$clean = false;
Well this of course depends. I think you'd want a list of all old fils right? Else you have to run it over and over again.

2020-08-18 11:57 UTC, nickvergessen commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +					$clean = false;
Ah right, yeah I missed the `$output->writeln(`

2020-08-18 11:57 UTC, nickvergessen commented on apps/encryption/lib/Command/ScanLegacyFormat.php
> +
github shows some warnings here?

2020-08-19 09:05 UTC, nickvergessen approved these changes
:shark:

2020-08-19 10:30 UTC, nickvergessen commented
Some failing tests are related, others need a rebase

2020-08-19 18:10 UTC, merged

2020-08-19 18:11 UTC, rullzer commented
Writing the docs is on my list for tomorrow

2020-08-24 08:06 UTC, rullzer commented
/backport to stable19

2020-08-28 19:07 UTC, kesselb commented
Don't forget the documentation :) We already have on issue report for the new setup check: https://github.com/nextcloud/server/issues/22478

2020-08-28 23:04 UTC, axheli commented
@rullzer What dose it mean by legacy format i enabled server side encryption when i installed NC 18. Do we need to stop using server side encryption ?

2020-08-29 10:56 UTC, yahesh commented
@axheli Legacy format here means the encryption scheme that was used before authenticated encryption was introduced back in 2016. When you first started using the SSE with NC 18 you are not using the legacy format.

2020-08-29 14:16 UTC, kesselb commented
I guess it's safe to ignore the warning for now. The condition to show the warning is wrong.

2020-08-29 14:22 UTC, axheli commented
@yahesh Got it thank you so much for explaining it.

2020-08-29 14:35 UTC, nickvergessen commented
Run `occ encryption:scan:legacy-format` to see which files use the legacy format.

2020-08-29 14:43 UTC, axheli commented
@nickvergessen running it. Going to check it out! I have a few servers but I think this one was created a long time ago.