re-index contacts with social profiles
nextcloud/server pull request #22222
Opened 2020-08-12 14:59 UTC by call-me-matt

follow-up from https://github.com/nextcloud/server/pull/22085

Signed-off-by: call-me-matt <nextcloud@matthiasheinisch.de>

2020-08-15 22:32 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +			// stop after 15min (to be continued with next chunk)
15sec, of course....

2020-08-19 14:35 UTC, nickvergessen requested changes

2020-08-19 14:35 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndex.php
> +		$query->select($query->createFunction('MAX(' . $query->getColumnName('cardid') . ')'))
```suggestion
		$query->select($query->func()->mad('cardid'))
```

2020-08-19 14:35 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndex.php
> +			->where('name=\'X-SOCIALPROFILE\'');
```suggestion
			->where($query->expr()->eq('name', $query->createNamedParameter('X-SOCIALPROFILE')));
```

2020-08-19 14:35 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndex.php
> +		$maxId = (int)$query->execute()->fetchColumn();
```suggestion
		$maxId = (int)$query->execute()->fetchColumn();
		
		if ($maxId === 0) {
			return;
		}
```

2020-08-19 14:35 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +			->where('p.name=\'X-SOCIALPROFILE\'')
```suggestion
			->where($query->expr()->eq('p.name', $query->createNamedParameter('X-SOCIALPROFILE')))
```

2020-08-19 14:35 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
Need a limit on this query and then loop the execution with different offsets instead.

2020-08-19 15:12 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndex.php
> +		$query->select($query->createFunction('MAX(' . $query->getColumnName('cardid') . ')'))
I suppose it's max? Or really mad?

2020-08-19 15:16 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
What do you mean? Currently it stops after 15sec and schedules a follow-up.

2020-08-19 19:24 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndex.php
> +		$query->select($query->createFunction('MAX(' . $query->getColumnName('cardid') . ')'))
max, sorry

2020-08-19 19:25 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
if you have 10k users you load 100k entries from the database, that's going to take a while and eat lots of memory, yeah.

2020-08-19 19:41 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
I would expect a deployment of that size to have enough memory for such a query. Or did you experience problems when executing these kind of tasks in past, for example [here](https://github.com/nextcloud/server/blob/master/apps/dav/lib/Migration/BuildCalendarSearchIndexBackgroundJob.php)?

2020-08-19 20:16 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +			$this->davBackend->updateCard($row['addressbookid'], $row['uri'], $row['carddata']);
@skjnldsv can you confirm this is a valid method in order to re-index?

2020-08-20 05:59 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
Fix is in https://github.com/nextcloud/server/pull/22311

Well this is also about contacts, not only users, so it can explode rather quickly in size, so better to be save than having people with bug reports on update.

2020-08-20 06:25 UTC, skjnldsv commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +			$this->davBackend->updateCard($row['addressbookid'], $row['uri'], $row['carddata']);
I cannot no, I have no idea.
cc @georgehrke

2020-08-20 07:05 UTC, georgehrke commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +			$this->davBackend->updateCard($row['addressbookid'], $row['uri'], $row['carddata']);
`updateCard` will do, yes.
Ideally we would just be calling `updateProperties`, but that method is protected

2020-08-20 15:20 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		$social_cards = $query->execute();
Yes, better safe than sorry... I have pushed an update, can you check? It's limiting the query, but if there are thousands of users there will be many background jobs to work off anyways. I am particularly interested, because I have introduced a way more demanding background job in https://github.com/nextcloud/contacts/pull/1745/

2020-08-20 18:51 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		// $query->selectDistinct('c.addressbookid', 'c.uri', 'c.carddata')
any idea how the distinct query can be applied here?

2020-08-25 08:13 UTC, nickvergessen commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		// $query->selectDistinct('c.addressbookid', 'c.uri', 'c.carddata')
Why do you want to distinct? We need to update all entries?

```suggestion
		$query->select('c.addressbookid', 'c.uri', 'c.carddata')
			->selectDistinct('c.id')
```

but since its the id column you dont select duplicates anyway, so should be fine without it.

2020-08-25 14:47 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		// $query->selectDistinct('c.addressbookid', 'c.uri', 'c.carddata')
Well, I am looking in the `cards_properties` for socialprofiles and then take the respective contacts from `cards` (so that I have only the ones with social profiles). But thinking about that now again, I guess the `card-properties` are in fact the indexed parameters, so that I cannot search in there and must take all contacts?

2020-08-25 15:11 UTC, call-me-matt commented on apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php
> +		// $query->selectDistinct('c.addressbookid', 'c.uri', 'c.carddata')
I have changed that now, see 69f3dca6f5

2020-09-11 09:17 UTC, kesselb commented
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result

2020-09-11 17:36 UTC, call-me-matt commented
> The autoloaders are not up to date

What exactly do I need to do?
If I run the mentioned script, it modifies the following files:

<details>
 <summary>Filelist</summary>

 - apps/accessibility/composer/composer/ClassLoader.php
 - apps/admin_audit/composer/composer/ClassLoader.php
 - apps/cloud_federation_api/composer/composer/ClassLoader.php
 - apps/comments/composer/composer/ClassLoader.php
 - apps/contactsinteraction/composer/composer/ClassLoader.php
 - apps/dav/composer/composer/ClassLoader.php
 - apps/dav/composer/composer/autoload_classmap.php
 - apps/dav/composer/composer/autoload_static.php
 - apps/encryption/composer/composer/ClassLoader.php
 - apps/federatedfilesharing/composer/composer/ClassLoader.php
 - apps/federation/composer/composer/ClassLoader.php
 - apps/files/composer/composer/ClassLoader.php
 - apps/files_sharing/composer/composer/ClassLoader.php
 - apps/files_trashbin/composer/composer/ClassLoader.php
 - apps/files_versions/composer/composer/ClassLoader.php
 - apps/lookup_server_connector/composer/composer/ClassLoader.php
 - apps/oauth2/composer/composer/ClassLoader.php
 - apps/provisioning_api/composer/composer/ClassLoader.php
 - apps/settings/composer/composer/ClassLoader.php
 - apps/sharebymail/composer/composer/ClassLoader.php
 - apps/systemtags/composer/composer/ClassLoader.php
 - apps/testing/composer/composer/ClassLoader.php
 - apps/twofactor_backupcodes/composer/composer/ClassLoader.php
 - apps/updatenotification/composer/composer/ClassLoader.php
 - apps/user_ldap/composer/composer/ClassLoader.php
 - apps/workflowengine/composer/composer/ClassLoader.php
 - lib/composer/composer/ClassLoader.php


</details>

But the output is not very convincing. I seems to be trapped in a loop?

<details>
 <summary>$ bash build/autoloaderchecker.sh</summary>

```bash
Composer found: checking for update
A preview release of the next major version of Composer is available (2.0.0-RC1), run "composer self-update --preview" to give it a try. See also https://github.com/composer/composer/releases for changelogs.
You are already using composer version 1.10.13 (stable channel).

Regenerating main autoloader
Generating optimized autoload files
Generated optimized autoload files containing 1306 classes

Regenerating autoloader for /var/www/nextcloud/apps/accessibility
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 7 classes

Regenerating autoloader for /var/www/nextcloud/apps/admin_audit
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 13 classes

Regenerating autoloader for /var/www/nextcloud/apps/cloud_federation_api
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 4 classes

Regenerating autoloader for /var/www/nextcloud/apps/comments
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 15 classes

Regenerating autoloader for /var/www/nextcloud/apps/contactsinteraction
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 10 classes

Regenerating autoloader for /var/www/nextcloud/apps/dav
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 223 classes

Regenerating autoloader for /var/www/nextcloud/apps/encryption
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 26 classes

Regenerating autoloader for /var/www/nextcloud/apps/federatedfilesharing
Generating optimized autoload files (authoritative)
Deprecation Notice: Class OCA\FederatedFileSharing\OCM\CloudFederationProviderFiles located in /var/www/nextcloud/apps/federatedfilesharing/lib/ocm/CloudFederationProviderFiles.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/nextcloud/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Generated optimized autoload files (authoritative) containing 13 classes

Regenerating autoloader for /var/www/nextcloud/apps/federation
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 14 classes

Regenerating autoloader for /var/www/nextcloud/apps/files
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 45 classes

Regenerating autoloader for /var/www/nextcloud/apps/files_sharing
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 63 classes

Regenerating autoloader for /var/www/nextcloud/apps/files_trashbin
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 34 classes

Regenerating autoloader for /var/www/nextcloud/apps/files_versions
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 27 classes

Regenerating autoloader for /var/www/nextcloud/apps/lookup_server_connector
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 3 classes

Regenerating autoloader for /var/www/nextcloud/apps/oauth2
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 13 classes

Regenerating autoloader for /var/www/nextcloud/apps/provisioning_api
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 9 classes

Regenerating autoloader for /var/www/nextcloud/apps/settings
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 47 classes

Regenerating autoloader for /var/www/nextcloud/apps/sharebymail
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 7 classes

Regenerating autoloader for /var/www/nextcloud/apps/systemtags
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 5 classes

Regenerating autoloader for /var/www/nextcloud/apps/testing
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 6 classes

Regenerating autoloader for /var/www/nextcloud/apps/twofactor_backupcodes
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 23 classes

Regenerating autoloader for /var/www/nextcloud/apps/updatenotification
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 9 classes

Regenerating autoloader for /var/www/nextcloud/apps/user_ldap
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 63 classes

Regenerating autoloader for /var/www/nextcloud/apps/workflowengine
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 30 classes

The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

</details>

2020-12-22 08:49 UTC, rullzer commented
Updated autoloaders.
Rebased. And squashed.

2020-12-22 12:17 UTC, rullzer approved these changes
Fine by me

2020-12-22 13:12 UTC, ChristophWurst approved these changes

2020-12-22 13:42 UTC, merged