Move contactsmenu to vue
nextcloud/server pull request #22274
Opened 2020-08-17 19:45 UTC by dk1a

Addresses #12905
Signed-off-by: Kirill Dmitriev <dk1a@protonmail.com>

2020-08-17 20:04 UTC, skjnldsv commented on core/src/OC/contactsmenu/App.vue
> +</template>
Hey! Thanks for doing this!
You can use the HeaderMenu here: https://github.com/nextcloud/server/blob/master/core/src/components/HeaderMenu.vue
https://github.com/nextcloud/server/blob/55473dd2eb042078b7fc5aef37e7b7fb614554fa/core/src/views/UnifiedSearch.vue#L23

I'll move it to @nextcloud/vue soon :)

2020-08-17 20:05 UTC, skjnldsv commented on core/src/OC/contactsmenu/Contact.vue
> +<!--
Please put this into proper components/views folders instead of the OC directory :)

2020-08-17 20:07 UTC, skjnldsv commented on core/src/init.js
> +	OC.ContactsMenu.$mount('#contactsmenu')
I'd rather have this integrated as a standalone entry point, like unified search :)
Check PR https://github.com/nextcloud/server/pull/21971 for reference

2020-08-19 07:28 UTC, dk1a commented on core/src/OC/contactsmenu/App.vue
> +</template>
Hey, thanks for the feedback, I tried to implement it

2020-08-19 07:29 UTC, dk1a commented
I moved the styles to vue components, but also left them in styles.scss, since it seems required by the jquery version of contactsmenu, not sure what to do with that one

2020-08-19 09:24 UTC, skjnldsv commented on core/src/components/ContactsMenu/Contact.vue
> +import $ from 'jquery'
Please do not use jQuery, you can use the Avatar component for this btw
https://nextcloud-vue-components.netlify.app/#/Components/Avatar

2020-08-19 09:24 UTC, skjnldsv commented on core/src/components/ContactsMenu/Contact.vue
> +import '../../jquery/placeholder'
Please do not use jQuery, you can use the Avatar component for this btw
https://nextcloud-vue-components.netlify.app/#/Components/Avatar

2020-08-19 09:28 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +				})
Please use async/await instead of then/catch

2020-08-19 09:30 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +	width: 350px;
The menu styling is already handled in the HeaderMenu component :)
https://github.com/nextcloud/server/blob/1a1b3e20e470a945dd9f5fab1d99174b10cbb141/core/src/components/HeaderMenu.vue#L197-L203

2020-08-20 06:28 UTC, skjnldsv commented on core/src/components/ContactsMenu/Contact.vue
> +	}
I'm confused, is this needed?
If so this is more like a bug in the nextcloud vue library :wink:

2020-08-20 06:54 UTC, skjnldsv requested changes

2020-08-20 06:54 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +}
The search needs to be sticky :)
https://github.com/nextcloud/server/blob/ea8f68bea6957ae459ff1ba6849b25354b3f0093/core/src/views/UnifiedSearch.vue#L34-L42
https://github.com/nextcloud/server/blob/ea8f68bea6957ae459ff1ba6849b25354b3f0093/core/src/views/UnifiedSearch.vue#L490-L512

2020-08-20 06:54 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +			<Contact v-for="(contact, index) in contacts" :key="index" :contact="contact" />
Do not use index as key, because the index of an Array is always the same, even if you remove/add entries. Use contact.id (though seems to be broken and null :thinking: )

2020-08-20 06:54 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +			this.loadContacts()
We need to comply to the min search length 
https://github.com/nextcloud/server/blob/7c56283c3ccb8f6d6ca6eeefd44a3db15d134da2/lib/private/Contacts/ContactsMenu/Manager.php#L66

2020-08-20 06:54 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +			<Contact v-for="(contact, index) in contacts" :key="index" :contact="contact" />
https://github.com/nextcloud/server/blob/7c56283c3ccb8f6d6ca6eeefd44a3db15d134da2/lib/private/Contacts/ContactsMenu/ContactsStore.php#L252-L254

Should be UID, not ID....

2020-08-20 06:54 UTC, skjnldsv commented on core/src/views/ContactsMenu.vue
> +				:aria-label="t('core', 'Contacts')" />
You don't need role/aria/tabindex here, this is taken care of by the HeaderMenu

2020-08-20 10:51 UTC, jancborchardt commented
Very very cool @dk1a! :) Awesome that you are looking at the Contacts menu.

Overall we always wanted to do more with that menu than what it is right now. Showing Contacts alone is just not very useful (especially sorted alphabetically) – it should include Talk conversations and also users on the instance.

Basically it should be a "People" menu. And it could be sorted by most recent interaction, e.g. who you last communicated with via Talk / who last sent you a message, or who you last shared with / last shared with you. It would basically be like:

> **Name of person**
> Subline with last interaction, like Talk message, or file share

(And of course their avatar on the left as now :)

For example for Talk messages:

> **Alex Lastname**
> 💬 Yeah that would be cool!

For Files sharing:

> **Sam Lastname**
> 📁 shared document.pdf

For Mail:

> **Blake Lastname**
> 💌 Re: Party planning

And so on. :) What do you think @dk1a @skjnldsv?

2020-08-20 13:19 UTC, skjnldsv commented
If you use the contacts vcf url and add `?photo` at the end, it will try to fetch the avatar.
Could be a nice combo with the Avatar component (that will fallback to a placeholder if the avatar image load fails)
ref https://github.com/nextcloud/server/issues/17483

2020-08-20 20:51 UTC, dk1a commented
> If you use the contacts vcf url and add `?photo` at the end, it will try to fetch the avatar.
> Could be a nice combo with the Avatar component (that will fallback to a placeholder if the avatar image load fails)
> ref #17483

Contacts already returned an avatar image, it just didn't work on the backend - fixed it

2020-08-21 06:09 UTC, skjnldsv commented on apps/accessibility/css/dark.scss
> +.contacts-menu__contacts-list a,
You can do it directly in the ContactsMenu.
Use `body.theme--dark` to narrow the selector :)

2020-08-25 09:13 UTC, skjnldsv commented
Any news @dk1a ? :)

2020-08-25 18:21 UTC, dk1a commented on core/src/views/ContactsMenu.vue
> +			this.loadContacts()
changed this in a previous commit; though is it intended that with minSearchStringLength>0 the contacts menu will be empty initially? That's how the backend did it, so I copied the behavior to frontend

2020-08-25 18:27 UTC, dk1a commented
I'd added min search length, moved dark style;
was also going to look at what other apps do with contactsmenu sometime this week.
Test failures seem unrelated, are they a problem?

2020-08-31 08:59 UTC, skjnldsv commented
Jsunit is legit.
Node / build too :)

2020-09-15 13:26 UTC, jancborchardt commented
> added min search length

Do we really want min search length? UX wise it’s always a bit of a hassle, and the current Contacts menu doesn’t have any minimum either.

2020-09-15 13:29 UTC, skjnldsv commented
> Do we really want min search length? UX wise it’s always a bit of a hassle, and the current Contacts menu doesn’t have any minimum either.

we have it everywhere. Unified search, sharing, contactsmenu... etc

2020-11-07 22:57 UTC, skjnldsv commented
Hey! Any news on this? :)
Now that we are into 21, could you rebase?
If you want to join, we have a community channel where we chat :wink: 
Are you interested?

2020-12-22 07:45 UTC, ChristophWurst commented
> Now that we are into 21, could you rebase?

We're in beta now. I'd say let's get this in in a few weeks when 21 was branched off. @dk1a could you please rebase and rebuild your branch to resolve the conflicts? Thanks :v:

2021-05-20 10:13 UTC, MorrisJobke commented
Let's close this for now. We can reopen it at any time again, but this one here just didn't got any update recently.

2021-05-20 10:13 UTC, closed without merging

2021-05-20 10:15 UTC, szaimen commented
@MorrisJobke May I suggest to just get rid of the contacts menu now that we have unified search?

2021-05-21 09:08 UTC, MorrisJobke commented
> @MorrisJobke May I suggest to just get rid of the contacts menu now that we have unified search?

cc @skjnldsv @ChristophWurst