Feature/noid/status dashboard
nextcloud/server pull request #22284
Opened 2020-08-18 13:33 UTC by georgehrke

![B5B71B69-B114-4B09-8ECD-DC1B74738C75](https://user-images.githubusercontent.com/1250540/90519353-32010f00-e168-11ea-9e43-8d2f19f80bed.png)

2020-08-18 14:26 UTC, jancborchardt requested changes
Super nice! :) Design feedback:
- [x] The icon should be black, we changed that for Files as well
- [x] The title is a bit long, let’s cut it to "Recent statuses"?
- [x] Should we add time info to the subline with a comma? Like "🌴 Vacationing, 3 days ago"

Edited by @georgehrke: Turned into checkboxes

2020-08-18 15:22 UTC, julien-nc requested changes
Very nice!

2020-08-18 15:22 UTC, eneiluj commented on apps/user_status/src/views/Dashboard.vue
> +		</template>
You don't need to redefine the default slot for `DashboardWidget` component. It already uses `DashboardWidgetItem`.

```suggestion
	<DashboardWidget
		id="user-status_panel"
		:items="items"
		:loading="loading">
```
with `items` being a computed prop like that:
```
items() {
    return this.statuses.map((s) => {
        return this.getWidgetItem(s)
    })
},
```

2020-08-18 15:34 UTC, georgehrke commented on apps/user_status/src/views/Dashboard.vue
> +		</template>
Excellent point!

2020-08-19 05:38 UTC, georgehrke commented
@juliushaertl @eneiluj Would you consider the misaligned empty content message an issue in nc/vue-dashboard?
(See original post)

2020-08-19 10:20 UTC, georgehrke commented
Rebased and squashed

2020-08-19 13:55 UTC, rullzer approved these changes

2020-08-20 09:31 UTC, jancborchardt commented on apps/user_status/src/views/Dashboard.vue
> +				{{ t('user_status', 'No recent status changes.') }}
We generally don’t use dots at the end of these headings. :)

2020-08-20 09:59 UTC, georgehrke commented on apps/user_status/src/views/Dashboard.vue
> +				{{ t('user_status', 'No recent status changes.') }}
https://github.com/nextcloud/server/pull/22321 will cause merge conflicts, so let's get #22321 in first, then i will rebase and fix the wording

2020-08-20 11:41 UTC, georgehrke commented
Rebased, squashed and fixed @jancborchardt's remark about the dot.

2020-08-20 12:49 UTC, rullzer commented
Needs a rebase. But then good to go I think

2020-08-20 13:44 UTC, georgehrke commented
Rebased again

2020-08-20 15:06 UTC, skjnldsv approved these changes

2020-08-20 15:06 UTC, merged