Emit unified search query
nextcloud/server pull request #22526
Opened 2020-08-31 20:04 UTC by raimund-schluessler

This PR emits a global event when the unified search is started or reset. Apps can use this to filter their content.

For the Tasks app this looks like this (with https://github.com/nextcloud/tasks/pull/1202):
![search](https://user-images.githubusercontent.com/2496460/91761168-c04bab00-ebd4-11ea-9d00-bd84a75d820c.gif)

A problem might be that the search is not persistent, as soon as the unified search input is closed, the filtering is reset. But this is by design of the search input, so I guess there is not much to do.

2020-09-01 04:32 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
```suggestion
			emit('nextcloud:unified-search', { query: this.query })
```

2020-09-01 04:32 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
```suggestion
			emit('nextcloud:unified-search', { query: this.query })
```

2020-09-01 04:32 UTC, skjnldsv requested changes
Thanks for taking care of this! :rocket: 
See comments :)

2020-09-01 04:33 UTC, skjnldsv commented
> A problem might be that the search is not persistent, as soon as the unified search input is closed, the filtering is reset

Let's address that in a followup, nice catch!

2020-09-01 07:03 UTC, raimund-schluessler commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
Fine with me. I just tried to follow what @ChristophWurst proposed in https://github.com/nextcloud/nextcloud-event-bus/issues/131#issuecomment-683660316.

2020-09-01 07:07 UTC, georgehrke commented
![D7D33D71-D781-4FCA-BD8A-01CD0FA6A647](https://user-images.githubusercontent.com/1250540/91813148-801b1580-ec32-11ea-9daf-d289d5163e0a.png)


@raimund-schluessler Looks like you committed the js files in dev mode. Please compile in production mode.

2020-09-01 07:07 UTC, raimund-schluessler commented
@skjnldsv I now wonder whether we should better `watch` `query` instead of emitting in the methods. Something like this

```js
watch: {
	query(query, oldQuery) {
		if (query !== oldQuery) {
			debounce(() => {
				emit('nextcloud:unified-search', { query: this.query })
			}, 200)
		}
	},
},
```

2020-09-01 07:08 UTC, raimund-schluessler commented
> 
> 
> ![D7D33D71-D781-4FCA-BD8A-01CD0FA6A647](https://user-images.githubusercontent.com/1250540/91813148-801b1580-ec32-11ea-9daf-d289d5163e0a.png)
> 
> @raimund-schluessler Looks like you committed the js files in dev mode. Please compile in production mode.

Hm, I don't often contribute to server, sorry. I will try to fix this.

2020-09-01 07:29 UTC, ChristophWurst commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
Tricky one. I'd say the action that is performed is that *a user searches*. So the name could be `nextcloud:unified-search:search` -> past tense hints the event is emitted *before* the actual search is performed, if we ever have an event for completion, it could be named `nextcloud:unified-search:searched`

2020-09-01 07:31 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
@ChristophWurst we literally just discussed this yesterday, did you change your mind? xD
This is emitted before. `nextcloud:unified-search:search` is fine :)

2020-09-01 07:37 UTC, skjnldsv commented
> We would be sure to really catch every change of query, even if it will be changed somewhere else in the future.

Well, we are catching any query change. You cannot change it from the outside (not sure we should).
And the only way to trigger it a second time with the same query would be to write some letters and erase them as fast as the current debounce. I'd like to stay clean and avoid watchers as this is not needed.

Unless you encountered some performance/usability issues, but I didn't :)

2020-09-01 07:40 UTC, ChristophWurst commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
I don't recall the details on naming but I don't think I suggested anything different than this, no?

2020-09-01 07:43 UTC, raimund-schluessler commented
> Unless you encountered some performance/usability issues, but I didn't :)

No, usability wise, I think it is ok. I just wondered whether it would be cleaner to only emit at a single place instead of in different methods. But I am fine either way.

2020-09-01 07:45 UTC, raimund-schluessler commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
`nextcloud:unified-search:search` sounds good to me and it seems like a consensus 😉 I will adjust the PR in the evening.

2020-09-01 07:46 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
I remembered specifically saying `nextcloud:unified-search-query` and you corrected saying `nextcloud:unified-search` was enough and the query in the object I think :p
But it doesn't matter, I might have misheard :see_no_evil: , let's go for your suggestion! :rocket:

2020-09-01 07:46 UTC, ChristophWurst commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
I made a typo. Read my comment again.

2020-09-01 07:55 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
> I made a typo. Read my comment again.

Still good, no?
This is emitted on input, so before anything else.

2020-09-01 07:56 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
@raimund-schluessler Maybe we can ignore the query clear event and replace it by a `emit('nextcloud:unified-search:close')` ?
That would solve your problem, no?

2020-09-01 08:03 UTC, raimund-schluessler commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
I don't know. When you close the search, the filter query needs to be cleared. Otherwise the filter will stay active indefinitely without a possibility to clear it. Or did I misunderstood something?

2020-09-01 08:24 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
> I don't know. When you close the search, the filter query needs to be cleared. Otherwise the filter will stay active indefinitely without a possibility to clear it. Or did I misunderstood something?

That would leave the implementation up to the dev, but you're right, how would you clear the query then?

2020-09-01 20:31 UTC, raimund-schluessler commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
I change it so it emits `emit('nextcloud:unified-search:close')` when closing the search and `emit('nextcloud:unified-search:search', { query: this.query })` when searching. While this doesn't solve the problem of the vanishing filtering, I think it still fits better than emitting a `search` on closing (and it is closer to how the old search behaved).

However, I wasn't sure about the correct event name, tbh. Please tell me if I got it wrong.

2020-09-01 20:31 UTC, raimund-schluessler commented on core/src/views/UnifiedSearch.vue
> +			emit('nextcloud:unified-search.update', { query: this.query })
Done.

2020-09-01 20:34 UTC, raimund-schluessler commented
I think I fixed it. However, the Node build fails, and I don't know why. It tells me there are uncommited changes. I also see them when I run `npm run build` locally, but I thought they are unrelated to my changes. Should I also commit them?

2020-09-02 05:52 UTC, skjnldsv approved these changes

2020-09-02 05:52 UTC, skjnldsv commented
/compile amend /

2020-09-02 06:25 UTC, skjnldsv commented
> I think I fixed it. However, the Node build fails, and I don't know why. It tells me there are uncommited changes. I also see them when I run `npm run build` locally, but I thought they are unrelated to my changes. Should I also commit them?

Yes, maybe master have an issue :shrug:

2020-09-02 06:59 UTC, raimund-schluessler commented
> 
> 
> > I think I fixed it. However, the Node build fails, and I don't know why. It tells me there are uncommited changes. I also see them when I run `npm run build` locally, but I thought they are unrelated to my changes. Should I also commit them?
> 
> Yes, maybe master have an issue 🤷

So, I should commit all files which are generated by `npm run build`?

2020-09-02 07:10 UTC, ChristophWurst approved these changes

2020-09-02 07:27 UTC, merged