Move to automated dependabot merging
nextcloud/server pull request #22642
Opened 2020-09-07 09:47 UTC by skjnldsv

Currently this auto merge patch releases.

While I think it's fine to auto-merge minor on other apps.
I'd be more cautious on server

cc @nextcloud/javascript

2020-09-07 09:59 UTC, ChristophWurst approved these changes

2020-09-07 09:59 UTC, ChristophWurst commented on .github/dependabot.yml
> +    timezone: Europe/Paris
But I want `Europe/Vienna`!

2020-09-07 12:26 UTC, georgehrke requested changes
The `dependabot.yml` is missing plenty of our current config:
![49244B25-F351-48D6-A810-F540FF9CC808](https://user-images.githubusercontent.com/1250540/92387577-13ae8380-f116-11ea-8488-3ed13ce70c3a.png)

2020-09-07 12:46 UTC, skjnldsv commented
Done @georgehrke !
I think it doesn't make sense to keep upgrading npm in /build for stablexx versions.
Testui integration has been removed from master now and is outdated.

2020-09-07 12:50 UTC, skjnldsv commented
Hum, actually, do we want to keep upgrading `/build/integration` for stablexx branches?
I would only upgrade main npm to be honest

2020-09-07 12:56 UTC, skjnldsv commented
![Capture d’écran_2020-09-07_14-56-08](https://user-images.githubusercontent.com/14975046/92389935-45c1e480-f11a-11ea-81cb-599fe837ffc8.png)
Damnit

2020-09-07 13:58 UTC, georgehrke approved these changes
Looks good to me, but i can't judge the part regarding the integration test suite.

2020-09-08 06:04 UTC, juliushaertl commented
> Hum, actually, do we want to keep upgrading /build/integration for stablexx branches?

Yeah just security updates i'd say for those.

We can just adjust the string of the branches when backporting the dependabot config to the stable branches.

2020-09-08 06:29 UTC, skjnldsv commented
> Yeah just security updates i'd say for those.
> 
> We can just adjust the string of the branches when backporting the dependabot config to the stable branches.

No, because dependabot doesn't check other branches than master
So we need to adjust master only.
Regarding security updates, I think they follow an independent release process. So it doesn't matter rather we have a dependabot config or not as long as it's enabled in https://github.com/nextcloud/server/network/alerts

2020-09-08 06:36 UTC, merged

2020-09-08 06:36 UTC, skjnldsv commented
https://github.com/nextcloud/server/network/updates