Update email address
nextcloud/server pull request #2276
Opened 2016-11-23 12:45 UTC by schiessle

update email address correctly if personal settings are changed.

cc @georgehrke 

fix https://github.com/nextcloud/server/issues/2235

2016-11-23 13:49 UTC, icewind1991 commented
:+1: code looks good

2016-11-23 13:59 UTC, georgehrke commented on settings/Controller/UsersController.php
> +				$user->setEMailAddress($email);
`saveUserSettings` which is called later in this message already sets the email address
https://github.com/nextcloud/server/blob/b4da5238acc2756f98f880dd6c005ca7edb9eb7a/settings/Controller/UsersController.php#L620

2016-11-23 16:19 UTC, schiessle commented
updated, should work now

2016-11-23 16:32 UTC, blizzz commented on settings/Controller/UsersController.php
> +			$oldDisplayName !== $data[AccountManager::PROPERTY_DISPLAYNAME]['value']
please put the && in the beginning of the next line for better readability

2016-11-23 16:32 UTC, blizzz commented on settings/Controller/UsersController.php
> +			$oldEmailAddress !== $data[AccountManager::PROPERTY_EMAIL]['value']
as above

2016-11-23 17:25 UTC, blizzz requested changes
Also fails:

1. As LDAP user without email address, go to personal page. 
2. Log out
3. On LDAP set the email address
4. Login as LDAP user and go to personal page

The email is missing, despite being read from LDAP (and written to oc_preferences). 

Could not test with local user because of #2279

2016-11-23 20:34 UTC, schiessle commented
@blizzz try my last commit. This should fix the ldap case. If it works I will add some tests

2016-11-24 09:10 UTC, schiessle commented
> Could not test with local user because of #2279

Should be fixed with my last commit , cc @nickvergessen please also have a look.

2016-11-24 10:07 UTC, nickvergessen commented
Works, thanks

2016-11-24 13:42 UTC, MorrisJobke commented
@schiessle ebfbcdae4cba7f1ab19e8f390c921c236dd0d6df is not signed-off

2016-11-24 14:17 UTC, blizzz requested changes

2016-11-24 14:17 UTC, blizzz commented on settings/Controller/UsersController.php
> +			&& !$this->groupManager->getSubAdmin()->isUserAccessible($this->userSession->getUser(), $user)
Heads up: IGroupManager does not define getSubAdmin() while the implementation does, so this works. There are other places with the same issue, so I'd say out of scope. Unit tests would fail, so it's a ticking bomb. Just to mention it.

2016-11-24 14:17 UTC, blizzz commented on settings/Controller/UsersController.php
> +		// for the permission of setting a email address
🙊

2016-11-24 14:17 UTC, blizzz commented on settings/Controller/UsersController.php
> +	public function setMailAddress($id, $mailAddress) {
perhaps set**Email**Address? I had postal in mind until line 791.

2016-11-24 14:17 UTC, blizzz commented on settings/Controller/UsersController.php
> +			]);
HTTP StatusCode?

2016-11-24 14:17 UTC, blizzz commented on tests/Settings/Controller/UsersControllerTest.php
> +use OC\ForbiddenException;
unused

2016-11-24 14:17 UTC, blizzz commented on tests/Settings/Controller/UsersControllerTest.php
> +		$user = $this->getMock(IUser::class);
getMock() is deprecated, use createMock()

2016-11-24 14:17 UTC, blizzz commented on tests/Settings/Controller/UsersControllerTest.php
> +		$user = $this->getMock(IUser::class);
see above

2016-11-24 14:17 UTC, blizzz commented on tests/Settings/Controller/UsersControllerTest.php
> +		$user = $this->getMock(IUser::class);
see above

2016-11-24 15:11 UTC, schiessle commented on settings/Controller/UsersController.php
> +		// for the permission of setting a email address
not my idea... copied the whole method from stale10 and earlier

2016-11-24 15:12 UTC, schiessle commented on settings/Controller/UsersController.php
> +			]);
same, here... As this worked for stable10 and earlier I don't want to mess around with it.

2016-11-24 15:13 UTC, schiessle commented
@blizzz did you tested it? Before I fix all the stuff and add unit tests it would be good to know if it is worth it.

2016-11-24 15:15 UTC, blizzz commented
> @blizzz did you tested it? Before I fix all the stuff and add unit tests it would be good to know if it is worth it.

I did the code review first.

2016-11-24 15:16 UTC, blizzz commented on settings/Controller/UsersController.php
> +			]);
k

2016-11-24 15:16 UTC, blizzz commented on settings/Controller/UsersController.php
> +		// for the permission of setting a email address
I know, I didn't say anything ;)

2016-11-24 15:25 UTC, blizzz commented
> Also fails:
>
>    As LDAP user without email address, go to personal page.
>    Log out
>    On LDAP set the email address
>    Login as LDAP user and go to personal page
>
> The email is missing, despite being read from LDAP (and written to oc_preferences).

@schiessle this works now 👌

2016-11-24 16:41 UTC, schiessle commented
great, so let me add you suggestions and some more tests and then we are ready to go

2016-11-24 18:24 UTC, schiessle commented
additional unit tests added and all comments addressed... final review round 😉

2016-11-25 10:34 UTC, blizzz approved these changes

2016-11-25 10:34 UTC, blizzz commented
:shipit:

2016-11-25 10:40 UTC, merged