Add Identityproof tests
nextcloud/server pull request #2285
Opened 2016-11-23 18:58 UTC by rullzer

* Add tests for Key
* Add tests for Manager
* Add tests for Signer
* Removed URLGenerator from signer

@LukasReschke

2016-11-23 19:29 UTC, LukasReschke requested changes

2016-11-23 19:29 UTC, LukasReschke commented on lib/private/Security/IdentityProof/Signer.php
> +			$location = strrpos($data['message']['signer'], '@');
Doesn't cover cases like `lukas@nextcloud.com@cloud.nextcloud.com` 🙈

2016-11-23 19:31 UTC, rullzer commented on lib/private/Security/IdentityProof/Signer.php
> +			$location = strrpos($data['message']['signer'], '@');
Yes it does. becase then your usename is `lukas@nextcloud.com` and not `lukas`.

2016-11-23 19:31 UTC, LukasReschke commented on lib/private/Security/IdentityProof/Signer.php
> +			$location = strrpos($data['message']['signer'], '@');
Oh. True 🙈 – My bad.

2016-11-23 19:31 UTC, LukasReschke approved these changes

2016-11-23 19:31 UTC, LukasReschke commented
LGTM

2016-11-24 21:39 UTC, rullzer commented
CC: @MorrisJobke @nickvergessen @icewind1991

2016-11-25 01:17 UTC, MorrisJobke commented
:+1:

2016-11-25 01:18 UTC, merged