Send password/activation link to new user
nextcloud/server pull request #2287
Opened 2016-11-23 19:03 UTC by tobiasKaminsky

As discussed here https://github.com/owncloud/core/issues/17398, I have implemented this for current nextcloud master.

Remaining discussion:
- should this be a new setting "send password link with email"?
- currently a password must be set: should I remove this if the new setting is enabled?

cc'ing all the one from the old issue: @MorrisJobke @jancborchardt @LukasReschke

2016-11-23 20:35 UTC, LukasReschke commented on settings/Controller/UsersController.php
> +								Crypto $crypto) {
ICrypto

2016-11-23 20:35 UTC, LukasReschke commented on lib/private/User/Manager.php
> +//		}
Let's just pass a long random password instead

2016-11-23 20:35 UTC, LukasReschke commented on settings/Controller/UsersController.php
> +					$this->config->setUserValue($username, 'core', 'lostpassword', $encryptedValue);
Should use a manager class somewhere

cc @rullzer Preferences where to put that?

2016-11-23 20:45 UTC, rullzer commented on settings/Controller/UsersController.php
> +					$this->config->setUserValue($username, 'core', 'lostpassword', $encryptedValue);
Maybe a generic `OC\User\LostPasswordManager` or whatever. So we have 1 place where we do the magic encryption of stuff.

Or maybe `LostPasswordManager` is not good since here the password is not lost. Just `PasswordManager`?

Mmmmm need to think. but putting it in `\OC\User` makes to me the most sense.

2016-11-23 20:46 UTC, rullzer commented
@tobiasKaminsky awesome stuff!

2016-12-03 20:38 UTC, adamish717 commented
Anyone get this working on v10? Or any other version? I'd love to find a way to just manually cram this in and make it work until it's built-in properly.

2016-12-16 00:11 UTC, jancborchardt commented
@tobiasKaminsky @LukasReschke @rullzer how do we continue here? :)

2016-12-16 15:41 UTC, rullzer commented
@adamish717 sorry but this will be NC12. We don't backport features.

2016-12-19 01:28 UTC, adamish717 commented
So does that mean nobody has gotten this working on 11? Or knows how?

2016-12-23 11:34 UTC, tobiasKaminsky commented
@adamish717 I have delevoped it on master, which was ~NC11, so this should work in NC11, but you will have to patch it by yourself.

2016-12-31 23:29 UTC, adamish717 commented
@tobiasKaminsky Thanks, I got it working smoothly. I'd made a minor mistake before that made it not work so I thought it was 'broken' when...I was broken :(

2017-01-06 14:44 UTC, MorrisJobke commented
@rullzer What is the status of this? Do you mind to fix the comments you had?

2017-01-11 12:56 UTC, rullzer commented on settings/Controller/UsersController.php
> +					$this->config->setUserValue($username, 'core', 'lostpassword', $encryptedValue);
So after thinking I'm still not sure. lets just get this in!

2017-01-11 12:57 UTC, rullzer approved these changes

2017-01-11 16:21 UTC, MorrisJobke commented
For me the email doesn't contain the reset link. And as an admin I still need to specify a password.

I would change the UX like this:

Don't do this as setting but as how Nextcloud reacts to input - change from this:

<img width="245" alt="bildschirmfoto 2017-01-11 um 17 16 54" src="https://cloud.githubusercontent.com/assets/245432/21856377/1842dfb0-d822-11e6-8ea6-be6a37d28c9b.png">

to a little info text that says "When the password of the new user is left empty an activation email with a link to set the password is send to the user."

<img width="257" alt="bildschirmfoto 2017-01-11 um 17 18 37" src="https://cloud.githubusercontent.com/assets/245432/21856389/24315e50-d822-11e6-9d10-00a3e9020928.png">

Then the initial email is either the normal welcome email (if the password is specified by the admin) or an advances welcome email that additionally also contains the password reset link to set the password the first time.

I just don't like to introduce yet another setting.

Opinions @nextcloud/designers ?

2017-01-11 17:25 UTC, skjnldsv commented
👍 with @MorrisJobke

2017-01-11 18:34 UTC, eppfel commented
@MorrisJobke I would argue otherwise. Yes, too much settings is not nice, but removing the password field would be a bigger advantage for admins, than having one more setting.

Creating 20 accounts, that's 20 more times hitting <kbd>⇥</kbd>.

If you want to keep it flexible, we could introduce a checkbox `generate password`/`send reset link`, because 'empty password input' equals 'random password/reset link is generated' and the only hint for this behavior is in the settings, is 👎 . The checkbox could be after the password field and disable and skipped, when a password is set (and of course removed with the password field, when default is set in the settings).

Maybe it would be good to get some Admins opinions on this. Who handles larger installations?
I know @ccoenen …

2017-01-11 22:25 UTC, ccoenen commented
I handle two installations right now, with a third that I'm just consulting on. Large deployments are done via scripts (to be released at some future point), so I don't have strong feelings on this one. As long as both is also possible via the provisioning API.

2017-01-12 07:16 UTC, enoch85 commented
@ccoenen 

>Large deployments are done via scripts (to be released at some future point)

Perfect for the Nextcloud VM. :)

2017-01-12 08:48 UTC, MorrisJobke commented
Big deployments also use LDAP. No need to optimize for some artificial use case ;)

2017-01-15 18:57 UTC, tobiasKaminsky commented
@MorrisJobke 
if "send password link" is enabled the password column should be invisible and the password check is skipped.
This was also initially tested by me :/

2017-02-15 17:34 UTC, MorrisJobke commented on lib/private/User/Manager.php
> +		if (trim($password) == '' && $this->config->getAppValue('core', 'umgmt_send_passwordlink', 'false') === 'false') {
This should be handled not in the `createUser()` but outside somewhere. Because this breaks for example the install process. Let me think about this one here.

2017-02-15 18:26 UTC, MorrisJobke approved these changes
I made the code a bit simpler. Removed the hack within the user manager and handle the password generation inside the UsersController. I remove the separate setting for now (we can add it afterwards if it is really needed, but I really tend to avoid as many settings as possible) and it works now for me fine. I also fixed the issue, that the setup was broken. 👍

2017-02-15 18:27 UTC, MorrisJobke commented
And I rebased it ;)

@rullzer @nickvergessen @blizzz @LukasReschke Please give this a final look. Thanks :)

2017-02-15 18:27 UTC, MorrisJobke commented
@tobiasKaminsky Sorry that this took so long 😕

2017-02-15 18:33 UTC, enoch85 commented
Wohaa! Finally! Loong wanted feature! :+1: :100: :1st_place_medal:

2017-02-15 18:59 UTC, tobiasKaminsky commented
@MorrisJobke thanks a lot. Great stuff!

2017-02-15 19:04 UTC, MorrisJobke commented
> @MorrisJobke thanks a lot. Great stuff!

You're welcome :) And I want to have this feature as well 😜

2017-02-15 19:17 UTC, xylo commented
Thanks a lot for this feature!

2017-02-15 19:20 UTC, LukasReschke commented on settings/templates/users/main.php
> +					When the password of the new user is left empty an activation email with a link to set the password is send to the user.
Shouldn't that use l10n?

2017-02-15 19:22 UTC, rullzer approved these changes

2017-02-15 19:25 UTC, MorrisJobke commented on settings/templates/users/main.php
> +					When the password of the new user is left empty an activation email with a link to set the password is send to the user.
Yep

2017-02-15 19:31 UTC, rullzer commented on settings/templates/users/main.php
> +					When the password of the new user is left empty an activation email with a link to set the password is send to the user.
Done

2017-02-16 00:07 UTC, MorrisJobke commented
I just added some unit tests and fixed the sign-off issue.

2017-02-16 06:07 UTC, skjnldsv requested changes
Need to check a thing, wait a sec.

2017-02-16 06:16 UTC, skjnldsv approved these changes
👍 Perfect!

2017-02-16 06:16 UTC, merged

2017-06-06 09:25 UTC, takenek commented
Hello Guys,
I use OwnCloud 9.1.4 but i don`t see option to send password/activation link to new user... i miss something or i need something mark/active in configuration? 
I got marked: "Send email to new user" and "Show email address"

But in e-mail i got only:
Hey there,
just letting you know that you now have an OwnCloud account.
Your username: test
Access it: https://test.taken.pl
Cheers! 
--
OwnCloud - 
https://test.taken.pl