improve handling of files we can't access in the scanner
nextcloud/server pull request #22943
Opened 2020-09-18 15:45 UTC by icewind1991

instead of erroring, remove the items from the cache.

this situation can be triggered if a user has access to a file but looses it afterwards

Signed-off-by: Robin Appelman <robin@icewind.nl>

2020-09-18 15:45 UTC, icewind1991 commented
/backport to stable20

2020-09-18 15:45 UTC, icewind1991 commented
/backport to stable19

2020-09-18 15:45 UTC, icewind1991 commented
/backport to stable18

2020-09-22 09:00 UTC, rullzer approved these changes
looks good

2020-09-22 09:17 UTC, juliushaertl approved these changes

2020-10-04 09:15 UTC, rullzer commented
static code analysis is not happy: https://github.com/nextcloud/server/pull/22943/checks?check_run_id=1134675980

2021-03-17 16:57 UTC, PVince81 commented
@icewind1991 rebase and fix psalm ?

2021-03-24 16:22 UTC, icewind1991 commented
rebasing made psalm happy

2021-03-24 16:22 UTC, icewind1991 commented
/backport to stable21

2021-03-25 08:15 UTC, MorrisJobke commented
I retriggered CI, because there were some SMB issues, that might be caused by this PR.

2021-03-30 19:43 UTC, rullzer commented
Still SMB issues it seems

2021-06-02 08:47 UTC, blizzz commented
@icewind1991 could you check the tests?

2021-06-02 09:22 UTC, blizzz commented
@icewind1991 could you check the tests?

2021-06-02 09:22 UTC, blizzz commented
@icewind1991 could you check the tests?

2021-06-16 11:38 UTC, blizzz commented
CI unhappy, 35 errors in samba tests

2023-03-14 22:02 UTC, max-nextcloud requested changes
fix samba (tests)

2023-04-05 19:36 UTC, merged