l10n: Add dots
nextcloud/server pull request #22961
Opened 2020-09-19 18:32 UTC by Valdnet

2020-09-20 09:14 UTC, kesselb commented
Mind to explain this change? I checked some other apps and summary and description does not end with a dot.

2020-09-20 11:59 UTC, Valdnet commented
@kesselb There are complex sentences in the application description that require correct punctuation. They can contain various signs such as: semicolon, colon, comma etc. And it must contain a dot at the end of the sentence.

> I checked some other apps and summary and description does not end with a dot.
They do not appear in some application descriptions because they are often duplicated errors by developers.

I am trying to improve to ensure consistency for the whole Nextcloud. Only in this way, when order and compliance with the spelling is certain, the Nextcloud instance will gain even more popularity among users.

2020-09-20 12:19 UTC, kesselb approved these changes

2020-09-20 14:54 UTC, nickvergessen commented
Too late, thuraday was string freeze, so translators can finish their work for Nextcloud 20. Will have to wait until 20 is out.

2020-09-23 08:31 UTC, jancborchardt commented on apps/contactsinteraction/appinfo/info.xml
> +	<summary>Manages interaction between users and contacts.</summary>
The summary is more like a short tagline and not a sentence. It should not have a dot at the end.

2020-09-23 08:37 UTC, ChristophWurst commented on apps/contactsinteraction/appinfo/info.xml
> +	<summary>Manages interaction between users and contacts.</summary>
I also often struggle with this. Can we have guidelines on these things in our dev or design docs?

2020-09-23 09:37 UTC, Valdnet commented on apps/contactsinteraction/appinfo/info.xml
> +	<summary>Manages interaction between users and contacts.</summary>
You have to take into account other punctuations that may appear in the summary. The slogan will look like an unfinished sentence.

2020-09-23 11:03 UTC, nickvergessen requested changes
Too late, 17th september was string freeze, so translators can finish their work for Nextcloud 20. Will have to wait until 20 is out.

2020-09-23 13:02 UTC, closed without merging