Support /.well-known/change-password URL
nextcloud/server pull request #22981
Opened 2020-09-20 20:38 UTC by beatbrot

[Google Chrome (since v86)](https://www.bleepingcomputer.com/news/google/google-chrome-is-making-it-easier-to-reset-compromised-passwords/) as well as safari and the iCloud keychain support the [.well-known/change-password URL](https://wicg.github.io/change-password-url/).

This PR adds support for that to nextcloud by modifying the default `.htaccess` file.

This is my first PR to nextcloud, so feedback is appreciated

2020-09-22 10:57 UTC, rullzer commented
I guess it will also need an update to the docs for nginx

2020-09-22 11:00 UTC, juliushaertl commented on .htaccess
> +  RewriteRule ^\.well-known/change-password /settings/user/security [R=301]
```suggestion
  RewriteRule ^\.well-known/change-password /index.php/settings/user/security [R=301]
```

Otherwise this might fail if htaccess.RewriteBase is not configured.

2020-09-22 11:19 UTC, brad2014 commented
> I guess it will also need an update to the docs for nginx

If nextcloud is hosted at a path inside a server (e.g. www.example.com/cloud/) or behind a reverse-proxy, then the ".well-known" redirects need to be added to the host webserver configuration, so the docs would require updating for apache, etc, as well as nginx.

2020-09-22 11:22 UTC, brad2014 commented on .htaccess
> +  RewriteRule ^\.well-known/change-password /settings/user/security [R=301]
Is there a reason you don't apply the "L" flag (last rule), as the other rewrites do?  Probably should.

2020-09-22 11:46 UTC, beatbrot commented on .htaccess
> +  RewriteRule ^\.well-known/change-password /settings/user/security [R=301]
@brad2014 I didn't add the L flag because I was not sure whether this actually was the last rule or not. But I guess, with the modifications of @juliushaertl, it definitely is, so I'll add that one

2020-09-24 14:25 UTC, beatbrot commented
@rullzer  @brad2014 So, should I also open a PR at [nextcloud/documentation](https://github.com/nextcloud/documentation)?

Also, do you understandy why CI fails?

2020-09-24 14:27 UTC, nickvergessen commented
The CI failure is random and unrelated

2020-09-24 14:39 UTC, kesselb requested changes
> Servers should redirect HTTP requests for an origin’s change password url to the actual page on which users may change their password by returning a response with a redirect status of 302, 303, or 307, and a Location header. [FETCH] [HTTP-SEMANTICS] Clients must handle such redirects when requesting a change password url.

> Note: The above paragraph restricts servers to using temporary redirect codes. See Issue 13.

https://w3c.github.io/webappsec-change-password-url/#semantics / https://github.com/w3c/webappsec-change-password-url/issues/13

2020-12-18 12:32 UTC, ChristophWurst commented
It's best if we add a handler based on the new API from https://github.com/nextcloud/server/pull/24702, then no special web server config will be requried.

2021-01-07 20:30 UTC, MorrisJobke commented
> It's best if we add a handler based on the new API from #24702, then no special web server config will be requried.

Implemente, so this one can be closed, right?

2021-01-07 20:30 UTC, closed without merging