filter out oc_mounts results from non existing users
nextcloud/server pull request #2299
Opened 2016-11-24 10:44 UTC by icewind1991

Sometimes oc_mount entries can be in the table for non existing users

2016-11-24 10:45 UTC, LukasReschke commented
Can we add a unit test for that?

2016-11-24 10:49 UTC, LukasReschke requested changes
Breaks stuff. 👎

2016-11-24 13:59 UTC, icewind1991 commented
@LukasReschke breakage on c.nc.c was caused by a separate issue

@rullzer @MorrisJobke  please review

2016-11-24 14:06 UTC, LukasReschke commented
> @LukasReschke breakage you discovered was caused by a separate issue

Do we have somebody working on that issue? 😉

2016-11-24 14:08 UTC, icewind1991 commented
> Do we have somebody working on that issue? 

There was a problem with mounts not being registered for users, while debugging I noticed the files_sharing app being disable (no idea how, for how long or why), after re-enabling it everything works again

2016-11-24 14:11 UTC, jospoortvliet commented
Hmmm if that breaks stuff perhaps it should not be something that can be disabled... because I bet we don't test that.

2016-11-24 14:12 UTC, icewind1991 commented
> Hmmm if that breaks stuff

"Disabling sharing breaks shares", more at 11

 :smile:

2016-11-24 14:18 UTC, jospoortvliet commented
Hehe ok thought it broke much more than shares. If just shares then fine, that is obvious.

Still a question how it got disabled, did the updater do that?

2016-11-24 14:20 UTC, MorrisJobke commented
Tested and works with existing setup 👍

2016-11-24 14:20 UTC, LukasReschke commented
> Hehe ok thought it broke much more than shares. If just shares then fine, that is obvious.
> Still a question how it got disabled, did the updater do that?

We have to have that fixed before we can do any beta or so. @icewind1991 can you try to reproduce the update situation on clonecloud or so? I also could offer an pre-update MySQL dump of c.nc.com

2016-11-24 14:28 UTC, LukasReschke approved these changes

2016-11-24 14:28 UTC, LukasReschke commented
LGTM

2016-11-24 14:28 UTC, merged

2016-12-07 17:38 UTC, blizzz commented
On a test upgrade against an instance with my production data, file_sharing was kept active after the update.

However, due to a the mysterious ```Webserver needs restart after upgrade``` – which I did not do – it caused theming to fail, because some old pathes where cached (PHP internal). Only Theming was affected though.