Handle owncloud migration to latest release
nextcloud/server pull request #23044
Opened 2020-09-25 10:11 UTC by juliushaertl

Steps to migrate from 10.5 to this branch
- make sure to have activity/files_pdfviewer/notifications/viewer/firstrunwizard installed
- run upgrade
- occ db:convert-filecache-bigint
- occ db:add-missing-columns

## Missing from the database diff between 10.5 and 20

- [ ] oc_activity -> app varchar 32 -> 255, add type to activity_filter key
- [ ] oc_authtoken -> loginname -> 255, add scope field
- [ ] oc_calendar components 20 -> 64
- [ ] oc_calendarsubscriptions lastmodified should be default null
- [ ] oc_cards -> add KEY `addressbookid_uri_index` (`addressbookid`,`uri`),
- [ ] oc_dav_job_status
- [ ] oc_dav_properties -> migrate to oc_properties
- [ ] oc_external_config -> value default null
- [ ] oc_federated_reshares -> share_id to bigint, remote_id varchar/int
- [ ] oc_files_trash auto_id bigint
- [ ] oc_jobs execution duration default -1/0
- [ ] oc_mounts -> add KEY `mounts_mount_id_index` (`mount_id`)
- [ ] oc_notifications -> only index names are different
- [x] oc_privatedata (can be ingored, moved to https://github.com/nextcloud/privatedata)
- [ ] oc_properties -> get user id from file id and path and store it, propertyvalue needs ot be longtext
- [ ] oc_share -> remove attributes
- [ ] oc_systemtags -> remove assignable
- [x] oc_trusted_servers (only comments added

## Others

- [ ] Proper fix for 75b7c2b
- [ ] db:add-missing-indices
  In SchemaException.php line 85: There is no column with name 'userid' on table 'oc_properties'.

2020-10-29 13:22 UTC, PVince81 commented
> oc_activity -> app varchar 32 -> 255, add type to activity_filter key

In a fresh install of NC 20 the app column still has 32 characters, same in activity master.
Not sure where that comes from.

2020-10-29 13:51 UTC, PVince81 commented
ok, got it, it's the other way around...

2020-10-29 14:46 UTC, PVince81 commented
regarding bigints I think we should add these to NC (and not convert bigint to int in NC)
the reason is most likely that the number of fileids/entries can become very high on huge instances

not sure if such change would be backported to NC 20 (if DB changes are allowed in minor releases), so might only arrive with NC 21 then ?

2020-10-29 14:50 UTC, PVince81 commented
oc_dav_job_status is for pending asynchronous/lazy operations: https://github.com/owncloud/core/blob/master/apps/dav/lib/DAV/LazyOpsPlugin.php#L65

we can delete it as it shouldn't contain any active entries during a migration

2020-10-29 14:55 UTC, PVince81 commented
oc_dav_properties is using fileid to map DAV properties so that they can survive renames

given that oc_properties only contains the path, DAV properties will likely get lost when renaming through some code paths.
see https://github.com/owncloud/core/issues/25563

maybe to keep oc_properties we could put a file id into the "propertiespath" column ?

2020-11-05 14:35 UTC, juliushaertl commented
Thanks a lot for digging into this already :) 

> regarding bigints I think we should add these to NC (and not convert bigint to int in NC)

Yes, definitely. At least bigint conversions are fine for minor releases if we let the user do the migration through `occ db:convert-filecache-bigint`

> not sure if such change would be backported to NC 20 (if DB changes are allowed in minor releases), so might only arrive with NC 21 then ?

@rullzer what do you think?

2020-11-27 14:50 UTC, juliushaertl commented
> Or in theory we could also discard (or keep for later) that table, in case whatever properties exist in there is anyway irrelevant for NC apps. Note that sometimes when Webdav is mounted as a Windows drive it will add a lot of Windows-specific properties. Deleting these shouldn't cause any issue as Windows would re-populate the next time.

I'd actually say we can go that way. We just recreate the table then with our format and mainly need to migrate oc_dav_properties from that to ours. For that migration I'm not entirely sure if there is any other relevant properties than calendar ones (cc @skjnldsv does store contacts some in there as well) we could just extract the user id from the propertypath, but my DAV internal knowledge is a bit limited in that regard. So any input welcome. Maybe @icewind1991 or @rullzer can also have a look if that makes sense.


For the ownCloud oc_dav_properties migration to oc_properties i would just try to match against /calendar/userid/ and extract the userid for our table format from that.
```
+----+------------------------+------------------------------------------+---------------+--------------+
| id | propertypath           | propertyname                             | propertyvalue | propertytype |
+----+------------------------+------------------------------------------+---------------+--------------+
|  1 | calendars/admin/sdfsdf | {http://owncloud.org/ns}calendar-enabled | 0             |            1 |
+----+------------------------+------------------------------------------+---------------+--------------+

becomes

+----+--------+--------------------------+------------------------------------------+---------------+
| id | userid | propertypath             | propertyname                             | propertyvalue |
+----+--------+--------------------------+------------------------------------------+---------------+
|  1 | jus    | calendars/admin/personal | {http://owncloud.org/ns}calendar-enabled | 0             |
+----+--------+--------------------------+------------------------------------------+---------------+

```

The propertytype introduced in https://github.com/owncloud/core/pull/37314 is also most likely irrelevant for us for now.

2020-12-03 13:55 UTC, rullzer commented
How did you get to that userid? shouldn't it be admin then?

2020-12-03 13:59 UTC, juliushaertl commented
Woops, must have been a copy past error when trying to align copied dumps from the the two instances i had. Yes that would of course be admin.

2020-12-07 18:45 UTC, nickvergessen requested changes

2020-12-07 18:45 UTC, nickvergessen commented on core/Migrations/Version13000Date20170718121200.php
> +				'notnull' => true,
:see_no_evil: should be 
```suggestion
				'notnull' => false,
```

Otherwise we can't save when the duration was <1 second

2020-12-07 18:45 UTC, nickvergessen commented on core/Migrations/Version13000Date20170718121200.php
> +				'default' => 0,
invalid default for oracle, as you said "not null"

2020-12-07 18:45 UTC, nickvergessen commented on core/Migrations/Version13000Date20170919121250.php
> +				'notnull' => true,
invalid default

2020-12-09 09:47 UTC, nickvergessen commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
:/ + 20 seconds for each app on installation. 
What's the diff with OC?

2020-12-09 11:05 UTC, juliushaertl commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
See the code below, basically the version and app id size doesn't match, meaning if we don't increase the size of the versions column the migrations will fail. Any other idea how we could solve that?

2020-12-09 11:14 UTC, juliushaertl commented on core/Migrations/Version13000Date20170919121250.php
> +				'notnull' => true,
Fixed, there were actually some more columns affected by that in the authtoken table

2020-12-09 12:00 UTC, nickvergessen commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
maybe wrap with something along:

https://github.com/nextcloud/server/blob/89ed2c37bf656ceb772bb6759c8977a7dc78b3fb/apps/files_sharing/lib/Migration/OwncloudGuestShareType.php#L78-L80

2020-12-09 12:01 UTC, nickvergessen commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
arg, dont have appconfig I guess

2020-12-09 12:35 UTC, juliushaertl commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
Ok, but we can just ignore the check if config is not available (e.g. on first install). Let me have  a look.

2020-12-09 12:43 UTC, juliushaertl commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
https://github.com/nextcloud/server/pull/23044/commits/f6da1c3f7b528c55fb2ad06e2038b3bfa2523133 seems to do the trick there.

2020-12-09 13:53 UTC, nickvergessen commented on lib/private/DB/MigrationService.php
> -		if ($this->connection->tableExists('migrations')) {
😻

2020-12-09 13:56 UTC, nickvergessen commented on lib/private/Repair/Owncloud/MoveAvatarsBackgroundJob.php
> +use Psr\Log\LoggerInterface;
something is unused

2020-12-09 13:57 UTC, nickvergessen approved these changes
🐘

2020-12-10 13:32 UTC, rullzer approved these changes

2020-12-10 13:32 UTC, merged

2020-12-10 20:33 UTC, rullzer commented
/backport to stable20

2020-12-22 13:28 UTC, PVince81 commented
seems we missed oc_share_external: https://github.com/nextcloud/server/issues/24813

2020-12-22 13:38 UTC, PVince81 commented on core/Migrations/Version21000Date20201120141228.php
> +			if ($table->hasColumn('systemtag')) {
wrong check, this should be "hasColumn('assignable')"

2021-01-12 14:58 UTC, dossantg commented
Is it possible to backport this PR for 19.0.7? I think the commit (c77e259) for indice on oc_cards can fix https://github.com/nextcloud/server/issues/23980 

But maybe i am wrong!