Fix null displayname crash as described in #21885
nextcloud/server pull request #23065
Opened 2020-09-27 11:55 UTC by TomG736

As discussed in #21885, `displayname` is sometimes Null when updating from older versions. This pull requests adds the code suggested in that issue by @dh-connect with modifications suggested by @kbzowski

2020-10-04 08:15 UTC, rullzer requested changes

2020-10-04 08:15 UTC, rullzer commented on lib/private/Group/Database.php
> +			if (isset($displayName) && trim($displayName) !== '') {
Do you want to check for `=== null`?

2020-10-04 18:35 UTC, TomG736 commented on lib/private/Group/Database.php
> +			if (isset($displayName) && trim($displayName) !== '') {
This was the suggestion I based the code from: https://github.com/nextcloud/server/issues/21885#issuecomment-688849551 
Just checking that it isn't null may be enough. Is having an empty displayname something that is allowed?

2020-10-31 14:55 UTC, skjnldsv commented
@TomG736 what is the status? :)

2021-02-25 21:00 UTC, Alekzanther commented
@rullzer This issue has been plaguing me (and many others) for a long time... It breaks large sections of Nextcloud. What's happening here? Isn't @TomG736:s fix good enough for now? Or are we missing something?

 @jospoortvliet do you know?

2021-03-17 16:55 UTC, PVince81 commented
@TomG736 can you rebase ?

If the fix as-is has already proven to work for many people in https://github.com/nextcloud/server/issues/21885 maybe we can take it as is ?

2021-03-17 23:06 UTC, TomG736 commented
Rebased back off current master

2021-03-18 07:15 UTC, PVince81 commented
Oracle fails:
```
1) Test\User\DatabaseTest::testSearch
Failed asserting that actual size 3 matches expected size 2.

/home/runner/work/server/server/tests/lib/User/Backend.php:114
/home/runner/work/server/server/tests/lib/User/DatabaseTest.php:125
```

Looks slightly related, but not sure

2021-03-18 07:18 UTC, PVince81 commented
looking closer, if the search finds 3 users containing "bar" instead of 2, maybe there's some random cleanup issue in the tests, likely unrelated. I'll restart the tests just in case...

2021-04-07 07:49 UTC, Alekzanther commented
> 
> 
> looking closer, if the search finds 3 users containing "bar" instead of 2, maybe there's some random cleanup issue in the tests, likely unrelated. I'll restart the tests just in case...

Did it work? There seems to be some "requested changes" (that don't really need to be addressed) blocking merge?

2021-04-07 07:50 UTC, Alekzanther commented on lib/private/Group/Database.php
> +			if (isset($displayName) && trim($displayName) !== '') {
@rullzer perhaps this is not required for this fix to get merged?

2021-05-20 10:17 UTC, MorrisJobke approved these changes
Makes sense 👍

2021-05-20 14:25 UTC, blizzz approved these changes

2021-05-25 19:13 UTC, merged

2021-06-23 13:11 UTC, szaimen commented
backport for stable21?

2021-09-10 10:23 UTC, blizzz commented
/backport to stable22

2021-09-10 10:24 UTC, blizzz commented
/backport to stable21

2021-09-10 10:24 UTC, blizzz commented
/backport to stable20

2021-09-10 11:11 UTC, szaimen commented
/backport to stable22

2021-09-10 11:29 UTC, szaimen commented
backprt to stable22 fails because it is already included in stable22

2021-09-10 11:37 UTC, blizzz commented
> backprt to stable22 fails because it is already included in stable22

makes sense :)