Restrict query when searching for versions of trashbin files
nextcloud/server pull request #23097
Opened 2020-09-29 15:10 UTC by juliushaertl

The current way of obtaining the versions from files in the trashbin is quite slow since it does a like operation on the unindexed name column. Since we know the full path of the file in the trashbin we can limit the search to the parent id. This should drastically speed up query times on large file cache tables.

We can ignore other things than single file restores since all usages have a separate code path for that.

2020-09-29 18:20 UTC, ChristophWurst approved these changes
:+1: :elephant:

2020-09-29 18:43 UTC, rullzer commented
nice one. but I'd really love the input from our storage overloard @icewind1991

2020-09-30 05:44 UTC, juliushaertl commented
Yes, I'd highly appreciate a closer look from @icewind1991 as well.

Some more comments on my validation paths since I also don't know that code very well.

I've tested this to still work when:
- Restore a file with versions
- Restore a file with versions from within a deleted folder
- Restore a deleted folder containing files with versions

View::searchCommon also includes mountpoints in the search, so this is no longer the case however I assumed there should never be any mountpoints inside of the /[uid]/files_trashbin/versions fake root.

https://github.com/nextcloud/server/blob/cfde74442c67b9a6e639536536c18e4c6d4f7a0e/lib/private/Files/View.php#L1653-L1671

2020-09-30 12:40 UTC, icewind1991 approved these changes

2020-10-03 10:21 UTC, rullzer commented
mmmm so for some reason the static analysis complains. Lets summon the wizards: @MorrisJobke @kesselb

2020-10-03 13:40 UTC, kesselb commented
Oh. I'm not sure what Psalm is complaining about :see_no_evil: 

- array_map always returns an array hence the is_array check is not longer required (but that should be a different line).
- `$matches =  array_map` there are two spaces before array_map (but this is also another line)
- `$ma` inside the foreach is resolved (by PHPStorm) to `mixed|OC\Files\Cache\CacheEntry`.

![image](https://user-images.githubusercontent.com/3902676/94993041-73ba0d80-058e-11eb-891e-5fe4fed39faa.png)

Mind to try the above version? I'm not sure if Psalm is reading the inline `/** @var **/` annotation. The above code works at least with PHPStrom and `$ma` is resolved correctly.

2020-10-06 14:19 UTC, nickvergessen commented on apps/files_trashbin/lib/Trashbin.php
> +			->andWhere($query->expr()->iLike('name', $query->createNamedParameter($pattern)));
`$pattern` is not wildcard sanitized? `IDBConnection::escapeLikeParameter`
So in case you have a file like `%` it will match all. Basically you need to `$query->createNamedParameter(\OC::$server->getDatabaseConnection()->escapeLikeParameter($basename($filename)) . $pattern')` and $pattern only contains the "last" part.

2020-10-06 14:20 UTC, nickvergessen requested changes

2020-10-06 14:20 UTC, nickvergessen commented on apps/files_trashbin/lib/Trashbin.php
> +			->andWhere($query->expr()->iLike('name', $query->createNamedParameter($pattern)));
`$pattern` is not wildcard sanitized? `IDBConnection::escapeLikeParameter`
So in case you have a file like `%` it will match all. Basically you need to `$query->createNamedParameter(\OC::$server->getDatabaseConnection()->escapeLikeParameter($basename($filename)) . $pattern')` and $pattern only contains the "last" part.

2020-10-07 09:22 UTC, juliushaertl commented
Let's see if psalm is happy with that

2020-10-07 11:12 UTC, MorrisJobke commented
> Let's see if psalm is happy with that

Looks good 👍 Even one error is "fixed". 😆

2020-10-07 11:17 UTC, MorrisJobke approved these changes
Code itself makes sense 👍

2020-10-14 13:35 UTC, MorrisJobke commented on apps/files_trashbin/lib/Trashbin.php
> +		$cache = $storage->getCache('');
`$storage` is not always available. See CI tests.

2020-10-14 14:39 UTC, juliushaertl commented on apps/files_trashbin/lib/Trashbin.php
> +		$cache = $storage->getCache('');
Pushed a fix, thanks for the pointer already.

2020-10-14 20:50 UTC, merged

2020-10-14 20:57 UTC, MorrisJobke commented
@juliushaertl Backport or not?

2020-11-03 09:50 UTC, MorrisJobke commented
ping @juliushaertl

2020-11-04 07:27 UTC, juliushaertl commented
/backport to stable20

2020-11-04 07:27 UTC, juliushaertl commented
/backport to stable19

2020-11-04 07:27 UTC, juliushaertl commented
/backport to stable18