also load app autoloader when located in /vendor
nextcloud/server pull request #23125
Opened 2020-10-01 16:17 UTC by icewind1991

with the phasing out of `app.php` apps can no longer load the autoloader from there themselves

See https://github.com/nextcloud/server/pull/21812

2020-10-01 16:24 UTC, icewind1991 commented
/backport to stable20

2020-10-02 07:35 UTC, ChristophWurst commented
> with the phasing out of `app.php` apps can no longer load the autoloader from there themselves

But you can `require_once` from the header of `Application.php`, no?

2020-10-06 20:14 UTC, MorrisJobke commented
> > with the phasing out of `app.php` apps can no longer load the autoloader from there themselves
> 
> But you can `require_once` from the header of `Application.php`, no?

Or just put it in `composer/autoloader.php`?

2020-10-06 20:55 UTC, juliushaertl approved these changes
:+1: from my side since vendor is actually the default target directory for installing composer packages without additional configuration of the vendor-dir

2020-11-10 07:54 UTC, ChristophWurst approved these changes
well fine I guess

2020-11-10 07:55 UTC, ChristophWurst commented
argh I'm so torn on this one. we have to check the file existence for every app. the os/fs will cache the result but still we do this. and if the require_once is in application.php (and we properly document this) it's explicit and less magical.

2020-11-10 11:29 UTC, MorrisJobke commented
> and if the require_once is in application.php (and we properly document this) it's explicit and less magical.

Sounds sane 👍

2020-11-10 14:31 UTC, ChristophWurst requested changes
Then I'll change my mind one more time. I'll do the docs update.

2021-03-26 14:18 UTC, closed without merging