Avoid browser autofill password recovery username
nextcloud/server pull request #23122
Opened 2020-10-01 09:47 UTC by eneiluj

This is an attempt to inhibit browser autofill for the username field in password recovery form. The field is now readonly until it gets user focus.

Apparently browsers ignore the "autocomplete" attribute.

2020-10-01 10:31 UTC, skjnldsv commented
I'm really not fond of this hack to be honest.
Yes browsers ignores the autocomplete attribute, but then this is up to the browsrs to fix it. Let's not clutter our code for such papercut i'd say.

Usually it's causing issues because we're using generic type-text IDs/names, like `id="user" name="user"` iirc.
Changing to a less generic string might lead to better results.

2020-10-01 10:35 UTC, skjnldsv commented
On a second though, why is this an issue btw?
I would find autocompletion quite relevant on a password reset form, no? (github is doing it for example, Google isn't though)

Here is what is working on google:

```html
<input type="email" autocomplete="off" spellcheck="false"
	aria-label="Phone or e-mail" name="identifier"
	value="" autocapitalize="none" id="recoveryIdentifierId">
```

2020-10-01 10:42 UTC, eneiluj commented
> why is this an issue btw?

Browser can suggest unrelated user names I guess. Users might think the suggestion comes from Nextcloud and not from the browser itself so they might trust it provides a good value instead of trying to type their actual user name. I'm not strongly confident my explanation is realistic :grin:.

So the question becomes: Do we want to avoid browser autofill?

> I'm really not fond of those hacks to be honest.

@skjnldsv Same for me. I was hoping someone had a better idea. So if we decide to inhibit autofill, would you be ok if I change the id and name attributes to "recovuser"?

2020-10-01 10:57 UTC, skjnldsv commented
> So the question becomes: Do we want to avoid browser autofill?

For me I think it's fine. :)

2020-10-03 09:43 UTC, rosito1 reviewed
- redacted -

2020-10-03 09:49 UTC, rosito1 requested changes

2020-10-03 09:49 UTC, rosito1 commented on core/src/components/login/ResetPassword.vue
> +			usernameReadonly: true,
erdy_erdy_

2020-10-03 09:49 UTC, rosito1 commented on core/src/components/login/ResetPassword.vue
>  					autocapitalize="off"
https://instagram.com/erdy_erdy_?igshid=gop9gj69a51j

2020-10-03 09:49 UTC, rosito1 commented on core/src/components/login/ResetPassword.vue
>  				autocomplete="<?php p($_['login_form_autocomplete']); ?>" autocapitalize="none" autocorrect="off"-->
https://instagram.com/erdy_erdy_?igshid=op6k4vgout1g

2020-10-03 09:49 UTC, rosito1 commented on core/src/components/login/ResetPassword.vue
> +			usernameReadonly: true,
erdy_erdy_

2020-10-03 09:50 UTC, rosito1 reviewed
https://instagram.com/erdy_erdy_?igshid=op6k4vgout1g

2020-10-26 17:39 UTC, eneiluj commented
@skjnldsv What do you think about emptying the username/email field when clicking on "forgot password"? This ensures the placeholder is shown and the user knows what the field is about.

2020-10-27 08:47 UTC, skjnldsv commented
> @skjnldsv What do you think about emptying the username/email field when clicking on "forgot password"? This ensures the placeholder is shown and the user knows what the field is about.

Not fond of, not having to type your username again is a nice flow.

2021-07-27 08:46 UTC, closed without merging

2021-08-16 13:13 UTC, jancborchardt commented
@eneiluj since you closed this, should we delete the branch too? :)