Feat/files sidebar cleanup standards
nextcloud/server pull request #23164
Opened 2020-10-03 22:37 UTC by skjnldsv

Long time needed! Before it gets too messy, let's do this!

This move the Vue requirement and allow any javascript to register a Tab.
The migration of existing tabs isn't too complicated (see Sharing Tab)

This also remove any dependency between the Sidebar and the Tab, before any library used my the Tab needed to be registered at the Sidebar level. Making it absolutely counter-intuitive and badly implemented.

2020-10-03 22:38 UTC, skjnldsv commented on apps/files/js/filelist.js
> +				}))
Legacy integration with backbone. At least it's cleaner now!

2020-10-03 22:44 UTC, skjnldsv commented
With that we should move the comments and version tabs tomorrow @rullzer what do you think? :)

2020-10-03 22:50 UTC, skjnldsv commented on apps/files/src/components/SidebarTab.vue
> +			this.render(this.$refs.mount, this.fileInfo)
@nextcloud/javascript shall we handle the unmount and destroy of the instance? What's best for performance?

Shall we have a dedicated setFileInfo function or something? Any suggestion? because we lose vue's reusability of virtual dom with this approach, we can't have everything I guess! :thinking:

2020-10-04 09:06 UTC, ChristophWurst commented on apps/files_sharing/src/files_sharing_tab.js
> +			render: (el, fileInfo) => {
is render called just once? is there anything like a re-render? should this be `mount` maybe?

2020-10-04 09:17 UTC, skjnldsv commented on apps/files_sharing/src/files_sharing_tab.js
> +			render: (el, fileInfo) => {
So unfortunately I discovered that there was a full reload of the tabs component on each file open.
Meaning each component gets discarded and not reused. I'm on it so speed up perfs.
But Ideally the fileInfo should be passed as a reference, unfortunately it seems that Vue.extend() just clone the propsData and it means we lose the automated reactivity of any object change :thinking: 

I'm investigating. But if that was not possible, we would need a dedicated `update` function I guess. How do you feel about that?

2020-10-04 11:52 UTC, skjnldsv commented on apps/files_sharing/src/files_sharing_tab.js
> +			render: (el, fileInfo) => {
Done

2020-10-05 09:55 UTC, skjnldsv commented
/compile amend /

2020-10-05 10:40 UTC, rullzer approved these changes
sure

2020-10-05 13:03 UTC, skjnldsv commented
Fixed jsunit

2020-10-05 13:06 UTC, skjnldsv commented
Missing reviewer, I thought I saw 2 :shrug:

2020-10-05 13:47 UTC, skjnldsv commented
Failures unrelated, waiting for last two acceptances tests!
Thanks @danxuliu for the talk pr already! :rocket:

2020-10-05 18:59 UTC, danxuliu commented
> Thanks @danxuliu for the talk pr already! :rocket:

My pleasure :-)

I found an issue, though, but I have not verified yet why it happens, so it may be a bug here or in the changes I made for Talk:
- Disable comments and versions, as they have not been ported yet
- Enable Talk in https://github.com/nextcloud/spreed/pull/4291
- Create a file
- Open the File menu actions of the file and click Details, so the sidebar opens on the first tab

The header for the _Chat_ tab will be the active one, but the contents of the tab will show the Sharing contents.

As I said it could very well be a bug in the Talk implementation, so it could be good to disable Talk and instead register a dummy tab which is shown before the Sharing tab to test this.

2020-10-06 11:53 UTC, danxuliu requested changes
The issue seems to be in this pull request:

- Disable comments and versions, as they have not been ported yet; also disable Talk if it was enabled from a previous test
- Add the following code in _apps/files_sharing/src/files_sharing_tab.js_ [before registering the Sharing tab](https://github.com/nextcloud/server/blob/82952e85f7bf578a8a29fb8d9bb244ae9c499077/apps/files_sharing/src/files_sharing_tab.js#L49) so two dummy tabs are created:
```
		OCA.Files.Sidebar.registerTab(new OCA.Files.Sidebar.Tab({
			id: 'aaa',
			name: 'Aaa',
			icon: 'icon-file',

			async mount(el, fileInfo, context) {
				const paragraph = document.createElement('p')
				const text = document.createTextNode('Hello world')
				paragraph.append(text)
				el.append(paragraph)
			},
			update(fileInfo) {
			},
			destroy() {
			},
		}))
		OCA.Files.Sidebar.registerTab(new OCA.Files.Sidebar.Tab({
			id: 'aaa2',
			name: 'Aaa2',
			icon: 'icon-file',

			async mount(el, fileInfo, context) {
				const paragraph = document.createElement('p')
				const text = document.createTextNode('Greetings world')
				paragraph.append(text)
				el.append(paragraph)
			},
			update(fileInfo) {
			},
			destroy() {
			},
		}))
```
- Rebuild JavaScript files
- In the Files app, create a file
- Open the File menu actions of the file and click Details, so the sidebar opens on the first tab

The header for the _Aaa_ tab will be the active one, but the contents of the tab will show the _Aaa_, _Aaa2_ and _Sharing_ contents (they might be vertically out of screen due to the `min-height: 100%` of the contents, check the scrollbar). When another tab is clicked the previous tab contents are hidden, although all those not clicked yet are still shown. Inspecting the DOM it can be seen that after the sidebar was originally opened all the sections were visible, but after selecting a specific tab the previous section style was changed to `display: none`.

2020-10-06 12:12 UTC, skjnldsv commented
> The header for the _Aaa_ tab will be the active one, but the contents of the tab will show the _Aaa_, _Aaa2_ and _Sharing_ contents (they might be vertically out of screen due to the `min-height: 100%` of the contents, check the scrollbar). When another tab is clicked the previous tab contents are hidden, although all those not clicked yet are still shown. Inspecting the DOM it can be seen that after the sidebar was originally opened all the sections were visible, but after selecting a specific tab the previous section style was changed to `display: none`.

Yes, this is fixed in upstream vue components.
Sorry, forgot about that https://github.com/nextcloud/nextcloud-vue/pull/1429

2020-10-06 12:12 UTC, skjnldsv commented
> * Disable comments and versions, as they have not been ported yet; also disable Talk if it was enabled from a previous test

Also, you can keep them, they are fully compatible with this new API btw :)

2020-10-06 19:05 UTC, danxuliu commented
> Yes, this is fixed in upstream vue components.

Cool :-) Should we wait for a new nextcloud-vue release and bump it in this pull request before merging?

> Also, you can keep them, they are fully compatible with this new API btw :)

Ah, sorry, I got confused by a previous comment. Great :-)

2020-10-06 19:06 UTC, danxuliu approved these changes
Tested (with https://github.com/nextcloud/nextcloud-vue/pull/1429) and works :+1:

But please do not merge before @skjnldsv had time to answer about the _nextcloud-vue_ bump ;-)

2020-10-06 21:17 UTC, skjnldsv commented
> But please do not merge before @skjnldsv had time to answer about the _nextcloud-vue_ bump ;-)

I'll release tomorrow! :rocket:

2020-10-07 07:06 UTC, skjnldsv commented
/compile amend /

2020-10-07 07:41 UTC, skjnldsv commented
/compile amend /

2020-10-07 09:13 UTC, merged

2020-11-13 10:39 UTC, PVince81 commented
Regression with file renames in share sidebar (and possibly others): https://github.com/nextcloud/server/issues/24101