Init vue comments tab
nextcloud/server pull request #23173
Opened 2020-10-04 13:33 UTC by skjnldsv

@rullzer

2020-10-04 15:00 UTC, kesselb commented on apps/comments/src/services/DavClient.js
> + * @copyright Copyright (c) 2019 John Molakvoæ <skjnldsv@protonmail.com>
It seems this file is in your stash for a while ;)

2020-10-04 15:10 UTC, skjnldsv commented on apps/comments/src/services/DavClient.js
> + * @copyright Copyright (c) 2019 John Molakvoæ <skjnldsv@protonmail.com>
Shhhhh :zipper_mouth_face:  :see_no_evil: :grin:

2020-10-16 21:06 UTC, skjnldsv commented
/compile /

2020-10-19 06:35 UTC, ChristophWurst requested changes, later dismissed

2020-10-19 06:35 UTC, ChristophWurst commented on apps/comments/lib/Event/LoadCommentsApp.php
> +class LoadCommentsApp extends Event {
1) Not a public API
2) This is a command, not an event

IMO there should be a tiny comments API for this. Like ``\OCP\Comments\ICommentsManager::load`` or ``\OCP\Comments\ICommentsManager::injectIntoPage``

2020-10-19 06:49 UTC, skjnldsv commented on apps/comments/lib/Event/LoadCommentsApp.php
> +class LoadCommentsApp extends Event {
> IMO there should be a tiny comments API for this. Like `\OCP\Comments\ICommentsManager::load` or `\OCP\Comments\ICommentsManager::injectIntoPage`

You're the php bootstrap expert! I was told to do it like that a while back with Viewer or Sidebar, I'll be happy to have a better way :)

2020-10-19 06:53 UTC, ChristophWurst commented on apps/comments/lib/Event/LoadCommentsApp.php
> +class LoadCommentsApp extends Event {
It's really not about bootstrap but what to use events for and what not. When you emit the event here you definitely expect something to happen. You're not signaling that something happened to let others react – that would be a true event.

We have the comments manager already. So this is just about adding a new method to the interface and implementing the few lines in the manager.

2020-10-19 07:53 UTC, ChristophWurst commented on lib/public/Comments/ICommentsManager.php
> +	public function load();
```suggestion
	public function load(): void;
```

2020-10-20 12:31 UTC, skjnldsv commented
/compile amend /

2020-10-20 12:36 UTC, ChristophWurst requested changes

2020-10-20 12:36 UTC, ChristophWurst commented on apps/comments/lib/AppInfo/Application.php
> +		$context->registerEventListener(
:fire:

2020-10-20 12:39 UTC, skjnldsv commented on apps/comments/lib/AppInfo/Application.php
> +		$context->registerEventListener(
Damn! Thanks

2020-10-20 12:39 UTC, skjnldsv commented
/compile amend /

2020-10-20 12:52 UTC, skjnldsv commented
/compile amend /

2020-10-20 12:54 UTC, ChristophWurst commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
sneaky

2020-10-20 12:54 UTC, rullzer commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
:snake:-y

2020-10-20 12:54 UTC, skjnldsv commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
Is it?
![Capture d’écran_2020-10-20_14-54-48](https://user-images.githubusercontent.com/14975046/96588652-38d10d00-12e4-11eb-84c3-3198e1ff6517.png)

2020-10-20 12:55 UTC, ChristophWurst approved these changes

2020-10-20 12:55 UTC, ChristophWurst commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
yes

2020-10-20 13:08 UTC, skjnldsv commented
Only took 16 minutes xD
![Capture d’écran_2020-10-20_15-08-09](https://user-images.githubusercontent.com/14975046/96590272-193ae400-12e6-11eb-8556-e09151097dbf.png)

2020-10-20 13:09 UTC, skjnldsv commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
IS IT?
![Capture d’écran_2020-10-20_15-09-11](https://user-images.githubusercontent.com/14975046/96590382-3bccfd00-12e6-11eb-908a-c6edf5fe054a.png)

2020-10-20 13:14 UTC, skjnldsv commented
Raaah, missing a lib update, final push™

2020-10-20 13:35 UTC, skjnldsv commented
Tests needs fixing, but the tests looks awful :cry:

2020-10-20 13:47 UTC, rullzer requested changes, later dismissed
Pressing enter doesn't submit the comment

2020-10-20 14:25 UTC, skjnldsv commented
> Tests needs fixing, but the tests looks awful

Fixed

> Pressing enter doesn't submit the comment

Fixed

2020-10-20 14:44 UTC, skjnldsv commented on lib/private/Collaboration/Collaborators/UserPlugin.php
> +						'subline' => $status['message'],
php 7.3 NODB tests are screaming 
```
1) Test\Collaboration\Collaborators\UserPluginTest::testSearch with data set #4 ('test', false, true, array(), array(), array(array('Test', array(0, 'test'), 'icon-user', null, array())), array(), true, Mock_IUser_27cf199a Object (...))
133 | Undefined index: message
134
```

What is the best way to make sure we have 'message' here @ChristophWurst @rullzer  ?

2020-10-20 14:54 UTC, ChristophWurst commented on package.json
> +    "@nextcloud/vue": "^3.0.0",
for the event of a Vue upgrade in Nextcloud I expect a cake delivered to my home so we can celebrate properly

2020-10-20 14:56 UTC, ChristophWurst commented on lib/private/Collaboration/Collaborators/UserPlugin.php
> +						'subline' => $status['message'],
what to you want to ensure? that it's always passed? hard to enforce with the array parameter.

how about a fallback with ``'subline' => $status['message'] ?? ''``?

2020-10-20 18:24 UTC, skjnldsv commented
```
[Tue Oct 20 17:17:00 2020] ArgumentCountError: Too few arguments to function OC\Comments\Manager::__construct(), 3 passed in /drone/src/apps/spreed/lib/Chat/CommentsManager.php on line 46 and exactly 4 expected at /drone/src/lib/private/Comments/Manager.php#73
[Tue Oct 20 17:17:00 2020] 127.0.0.1:46422 [200]: /ocs/v2.php/cloud/users/user0
[Tue Oct 20 17:17:00 2020] ArgumentCountError: Too few arguments to function OC\Comments\Manager::__construct(), 3 passed in /drone/src/apps/spreed/lib/Chat/CommentsManager.php on line 46 and exactly 4 expected at /drone/src/lib/private/Comments/Manager.php#73
```

Tests are failing on spreed, require a fix there

2020-10-20 18:44 UTC, rullzer approved these changes

2020-10-20 18:46 UTC, merged