Add command to list available routes
nextcloud/server pull request #23251
Opened 2020-10-07 08:42 UTC by PVince81

Can be useful for debugging or for setting up firewalls or gateways.

From https://github.com/owncloud/core/pull/28901 and https://github.com/owncloud/core/pull/28642

Tested manually with `occ security:routes` and `occ security:routes -d`

2020-10-07 09:13 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	 */
```suggestion
	/** @var IRouter */
```

2020-10-07 09:13 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	protected function configure() {
```suggestion
	protected function configure(): void {
```

2020-10-07 09:13 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	protected function execute(InputInterface $input, OutputInterface $output) {
```suggestion
	protected function execute(InputInterface $input, OutputInterface $output): int {
```

2020-10-07 09:14 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	private function buildController($name) {
```suggestion
	private function buildController(string $name): array {
```

2020-10-07 09:15 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	private function buildReflection($appName, $controllerName, $method) {
```suggestion
	private function buildReflection(string $appName, string $controllerName, string $method): ?\ReflectionMethod {
```

2020-10-07 09:15 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	private function listControllerNames($appName, $controllerName) {
```suggestion
	 * @return \Generator|string[]
	 */
	private function listControllerNames(string $appName, string $controllerName) {
```

2020-10-07 09:16 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	private function listMethodNames($method) {
```suggestion
	 * @return \Generator|string[]
	 */
	private function listMethodNames(string $method) {
```

2020-10-07 09:16 UTC, nickvergessen commented on lib/private/Route/Router.php
> +	public function getCollections() {
```suggestion
	public function getCollections(): array {
```

2020-10-07 09:17 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +/**
```suggestion
<?php

declare(strict_types=1);
/**
```

2020-10-07 09:17 UTC, nickvergessen requested changes
see comments

2020-10-07 09:22 UTC, PVince81 commented
thanks. seems this file was quite old already

2020-10-07 09:25 UTC, nickvergessen commented on core/Command/Security/ListRoutes.php
> +	protected function execute(InputInterface $input, OutputInterface $output): int {
TypeError: Return value of OC\Core\Command\Security\ListRoutes::execute() must be of the type int, none returned in /home/nickv/Nextcloud/21/server/core/Command/Security/ListRoutes.php:122


Please add `return 0;` at the end.

2020-10-07 09:29 UTC, nickvergessen commented
It lists `/ocsapp/` should we string replace that with `/ocs/v{version}.php/`?

2020-10-07 10:55 UTC, MorrisJobke commented on core/register_command.php
> +	$application->add(new OC\Core\Command\Security\ListRoutes(\OC::$server->getRouter()));
Let's use auto-wiring:

```suggestion
	$application->add(\OC::$server->get(\OC\Core\Command\Security\ListRoutes::class));
```

2020-10-07 10:56 UTC, MorrisJobke commented on lib/public/Route/IRouter.php
> +	 * @deprecated 9.0.0
🙈 

I guess we can remove the deprecated tag here. I see where it comes from, but it doesn't make sense to document the old deprecation.

2020-10-07 12:52 UTC, PVince81 commented on lib/public/Route/IRouter.php
> +	 * @deprecated 9.0.0
yeah... was not too fond of that bit...

2020-10-07 12:58 UTC, PVince81 commented
adjusted and squashed

2020-10-07 14:25 UTC, ChristophWurst commented on core/Command/Security/ListRoutes.php
> +			->setName('security:routes')
why is this in `security`?

2020-10-07 14:27 UTC, ChristophWurst commented on core/register_command.php
> +	$application->add(\OC::$server->get(OC\Core\Command\Security\ListRoutes::class));
if this is for debugging we should maybe only add it when debud mode is on, no?

2020-10-07 14:30 UTC, PVince81 commented on core/Command/Security/ListRoutes.php
> +			->setName('security:routes')
mostly because useful to evaluate what routes are available for firewalls/gateways/..., knowing what routes could be accessible

2020-10-12 09:14 UTC, PVince81 commented on core/register_command.php
> +	$application->add(\OC::$server->get(OC\Core\Command\Security\ListRoutes::class));
same comment as above: an admin can use it to find out what routes are exposed for firewall/gateway/... setup. sometimes there are strict firewalls in place and one needs to know what to add to the "allowed lists"

2020-10-12 15:29 UTC, MorrisJobke commented
* [ ] bug: `-d` option causes an exception for me:
```
php occ security:routes -d                                                                                                                                                       1 ↵
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
An unhandled exception has been thrown:
TypeError: preg_match_all() expects parameter 2 to be string, bool given in /Users/morris/Projects/nextcloud/server/core/Command/Security/ListRoutes.php:149
Stack trace:
#0 /Users/morris/Projects/nextcloud/server/core/Command/Security/ListRoutes.php(149): preg_match_all('/@([A-Z]\\w+)/', false, NULL)
#1 /Users/morris/Projects/nextcloud/server/core/Command/Security/ListRoutes.php(76): OC\Core\Command\Security\ListRoutes->buildController('logreader.log.g...')
#2 /Users/morris/Projects/nextcloud/server/apps2/deck/vendor/symfony/console/Command/Command.php(258): OC\Core\Command\Security\ListRoutes->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/morris/Projects/nextcloud/server/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/morris/Projects/nextcloud/server/apps2/deck/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/morris/Projects/nextcloud/server/apps2/deck/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Security\ListRoutes), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/morris/Projects/nextcloud/server/apps2/deck/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/morris/Projects/nextcloud/server/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/morris/Projects/nextcloud/server/console.php(100): OC\Console\Application->run()
#9 /Users/morris/Projects/nextcloud/server/occ(11): require_once('/Users/morris/P...')
#10 {main}% 
```

2021-05-20 10:19 UTC, MorrisJobke commented
@PVince81 🏓

2021-05-20 10:20 UTC, PVince81 commented
I have the feeling that there is no real use or interest for this feature, so I'll close it

2021-05-20 10:20 UTC, closed without merging