Improve user share suggestions #1963
nextcloud/server pull request #23265
Opened 2020-10-07 21:40 UTC by kinimodmeyer

@jancborchardt wrote the best way to start is to pick a issues with label "good first issue".
that´s why i just choosed this issue here from the list. :pick:  

- with this change you find user "Dominik Meyer" also when you search for "Dom Me" in the share dialog
- with this change you find user "Dominik Meyer" also when you enter his local share "uid@domain:port"

this is my first contribution so be friendly :smiley_cat: 

PS next to my code contribution is saw this code-comment:

> // sqlite doesn't like re-using a single named parameter here

i not understand this comment exactly, what is not possible with sqlite?
my change works in sqlite even tho i reuse the same column (uid), but i guess this comment means something else.

PPS i personally would love :smiling_face_with_three_hearts:  to find the user if you start with typing the lastname like "Meyer Dominik". but this is out of scope here i guess.

2020-10-11 10:41 UTC, kinimodmeyer commented
"continuous-integration/drone/pr" failed but i don´t see the reason in https://drone.nextcloud.com/nextcloud/server/33829/14/5 ? can someone give me a hint or is it a pipeline issue? how is the process overall here now.

2020-10-12 12:21 UTC, nickvergessen commented
It had a timeout, it's okay to ignore it.

2020-10-12 12:30 UTC, nickvergessen requested changes

2020-10-12 12:30 UTC, nickvergessen commented on lib/private/User/Database.php
> +		}
This should not be here from my pov.

2020-10-12 12:30 UTC, nickvergessen commented on lib/private/User/Database.php
> +		$displayNameParameter = '%' . str_replace(' ', '% ', $this->dbConn->escapeLikeParameter($search)) . '%';
```suggestion
		$displayNameParameter = '%' . implode('% %', array_map([$this->dbConn, 'escapeLikeParameter'], explode(' ', $search)))) . '%';
```

2020-10-13 12:08 UTC, kinimodmeyer commented on lib/private/User/Database.php
> +		}
thanks for your review @nickvergessen 
can you give me a little more information what you mean with this?
do you mean it should be in another class/method and somehow gets injected there?

2020-10-27 09:52 UTC, nickvergessen commented on lib/private/User/Database.php
> +		}
Well "federation a like" results are returned by other search plugins?

2022-11-07 14:01 UTC, closed without merging