Allow subscription to indicate that a userlimit is reached
nextcloud/server pull request #23278
Opened 2020-10-08 09:43 UTC by MorrisJobke

2020-10-08 10:07 UTC, rullzer requested changes
Nice stuff!

2020-10-08 10:07 UTC, rullzer commented on lib/private/Support/Subscription/Registry.php
> +			$this->logger->warning("Total user count was negative (users: $userCount, disabled: $disabledUsersCount)", ['app' => 'support']);
famous last words

2020-10-08 10:07 UTC, rullzer commented on lib/private/Support/Subscription/Registry.php
> +		$this->userCount = $userCount - $disabledUsersCount;
why do we store this? It should oly be called once right?

2020-10-08 10:18 UTC, MorrisJobke commented on lib/private/Support/Subscription/Registry.php
> +		$this->userCount = $userCount - $disabledUsersCount;
copy paste leftover :/

2020-12-02 08:47 UTC, MorrisJobke commented on lib/private/Support/Subscription/Registry.php
> +		// TODO notify admin about reached user limit
@rullzer How do we want to do this? Email? Notification only?

2020-12-02 09:07 UTC, MorrisJobke commented on lib/private/Support/Subscription/Registry.php
> +		// TODO notify admin about reached user limit
Implemented as notification via 2260c02e97

2020-12-02 09:08 UTC, MorrisJobke commented
/backport to stable20

2020-12-02 14:20 UTC, MorrisJobke commented
Ready for review 🚀

2020-12-02 15:23 UTC, rullzer approved these changes
Looks good! Didn't test in depth but a quick smoke test showed it OK. And the test seems sane!

2020-12-02 17:21 UTC, ChristophWurst approved these changes
Looks good!

2020-12-02 17:22 UTC, merged

2020-12-02 19:24 UTC, blizzz commented on lib/private/User/Manager.php
> +
heads up, this will not catch users provisioned by other backends

2020-12-02 19:39 UTC, rullzer commented on lib/private/User/Manager.php
> +
Yes we know
will come in follup PRs

2020-12-02 20:24 UTC, jospoortvliet reviewed
Looks good, just these changes would be nice :+1:

2020-12-02 20:43 UTC, MorrisJobke commented on core/Notification/CoreNotifier.php
> +			$notification->setLink('https://nextcloud.com/enterprise/order/');
Added to https://github.com/nextcloud/server/pull/24516

2020-12-02 20:43 UTC, MorrisJobke commented on core/Notification/CoreNotifier.php
> +			$notification->setParsedMessage($l->t('Add a subscription key to increase the user limit of this instance. For more information have a look at the Enterprise subscription page.'));
Added to https://github.com/nextcloud/server/pull/24516