Fix undefined index and consequential damages in versions code
nextcloud/server pull request #23295
Opened 2020-10-08 17:54 UTC by ChristophWurst

If the user has no space and there are no versions, there won't be an
`all` index in the versions entry. Hence this triggers a warning and
becomes `null`, afterwards `count`, `foreach` and friends will happily
throw even more warnings and errors because they don't want to play with
`null`. Thus adding a fallback to an empty array.

2020-10-08 17:54 UTC, ChristophWurst commented
/backport to stable20

2020-10-08 17:55 UTC, ChristophWurst commented
/backport to stable19

2020-10-08 18:06 UTC, rullzer approved these changes

2020-10-08 18:21 UTC, kesselb commented
Make sense. I also think there are some reports around for this.

2020-10-09 08:09 UTC, nickvergessen requested changes

2020-10-09 08:09 UTC, nickvergessen commented on apps/files_versions/lib/Storage.php
>  				$result = Storage::getAllVersions($uid);
```suggestion
				$result = self::getAllVersions($uid);
```

2020-10-09 08:09 UTC, nickvergessen commented on apps/files_versions/lib/Storage.php
>  				foreach ($result['by_file'] as $versions) {
so this could also be undefined. Maybe we instead fix `getAllVersions` to always include both keys as an empty array?

2020-10-09 13:24 UTC, MorrisJobke commented
@ChristophWurst I added a commit that added the changes the @nickvergessen proposed, because I think that is the better approach to deal with this.

2020-10-12 12:12 UTC, nickvergessen commented on apps/files_versions/lib/Storage.php
> +		if (!$threshold || $versions['all'] === []) {
```suggestion
		if (!$threshold || empty($versions['all'])) {
```

2020-10-12 12:12 UTC, nickvergessen approved these changes

2020-10-12 12:14 UTC, nickvergessen commented
DB tests are not happy. Seems to be the "random fail" but it failed on all DBs here, so not sure its unrelated?

2020-10-12 12:57 UTC, ChristophWurst commented
> DB tests are not happy. Seems to be the "random fail" but it failed on all DBs here, so not sure its unrelated?

Unfortunately also happening with other PRs right now

2020-10-12 20:17 UTC, MorrisJobke commented
> DB tests are not happy. Seems to be the "random fail" but it failed on all DBs here, so not sure its unrelated?

Fixed with #23391

2020-10-13 15:35 UTC, merged