Fix #17302: Add param to use grid view as default for share
nextcloud/server pull request #23471
Opened 2020-10-15 10:45 UTC by asdil12

To allow sharing image galeries via links and restore at least a
minimal set of the features that the gallery app used to have,
this allow to set the default view to grid on a shared link.

Just append `?show_grid=1` to the URL and the grid view will be
used by default.

This will only work for shared links.

2020-10-19 13:00 UTC, rullzer requested changes

2020-10-19 13:00 UTC, rullzer commented on apps/files_sharing/lib/Controller/ShareController.php
> +			$folder->assign('showgridview', ((bool) $_GET['show_grid']));
Just use a function parameter.

2020-10-19 13:09 UTC, asdil12 commented on apps/files_sharing/lib/Controller/ShareController.php
> +			$folder->assign('showgridview', ((bool) $_GET['show_grid']));
I'm not sure what you mean. I'm not really familiar with the codebase, though.

2020-10-19 17:31 UTC, skjnldsv commented
So, I'm kinda not super fond of such hidden parameters. They will be forgotten and are really not discoverable :thinking:

2020-10-19 17:35 UTC, asdil12 commented
So it might make sense to append this parameter automatically when sharing - either defaulting to the current setting of the user that is creating the link or adding a checkbox to the sharing dialog that will append this parameter to the url.

2020-11-07 23:17 UTC, skjnldsv commented
> So, I'm kinda not super fond of such hidden parameters. They will be forgotten and are really not discoverable

Yeah, sorry, that's a no from me.
Until we decide to set the grid view as default (if it happens), I don't think we want this.
cc @jancborchardt for the ux flow and default behavious.

As grid toggle won't be remembered for public shares without user auth, no idea what the default should be :thinking:

2020-11-07 23:17 UTC, closed without merging

2025-08-26 21:15 UTC, dijikul commented
This is still occurring in 2025.