Reverted commit 54a5f938f99 because of Bug #23174
nextcloud/server pull request #23507
Opened 2020-10-16 09:36 UTC by Cybso

Reverted commit 54a5f938f99 from @nickvergessen to fix bug #23174 which breaks upgrades to 18.0.10.

Maybe it would be better to fix the migration of oc_flow_operations instead, but I'm not familiar with this part of the code.

2020-10-16 09:46 UTC, nickvergessen commented
Yes need to fix flow instead @blizzz

2020-10-16 12:29 UTC, Cybso commented
@nickvergessen @blizzz I've reverted the revert and fixed the migration instead. Since I assume that the column 'entity' should never become Null when added, I've changed 'notnull' to true instead of removing the default value. Is this a valid fix for the problem?

2020-10-16 14:11 UTC, nickvergessen commented
Well empty strings are saved as Null in Oracle, so having an NotNull with default `''` is invalid and that's why we prevent it

2020-10-16 16:50 UTC, Cybso commented
Well, that's bad. While MariaDB obviously accepts adding "not null" columns without explicit default, SQLite does not:

Mariadb:
```
MariaDB [nextclouddev]> create table foobar (id int not null primary key);
Query OK, 0 rows affected (0.196 sec)

MariaDB [nextclouddev]> insert into foobar values (1);
Query OK, 1 row affected (0.030 sec)

MariaDB [nextclouddev]> insert into foobar values (2);
Query OK, 1 row affected (0.178 sec)

MariaDB [nextclouddev]> alter table foobar add column x char(10) not null;
Query OK, 0 rows affected (0.149 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [nextclouddev]> select * from foobar;
+----+---+
| id | x |
+----+---+
|  1 |   |
|  2 |   |
+----+---+
2 rows in set (0.001 sec)
```

SQLite:
```
sqlite> create table foobar (id int not null primary key);
sqlite> insert into foobar values (1);
sqlite> insert into foobar values (2);
sqlite> alter table foobar add column x char(10) not null;
Error: Cannot add a NOT NULL column with default value NULL
```

2020-10-19 13:10 UTC, blizzz approved these changes
@Cybso could you  squash the commits, please?

2020-10-19 13:13 UTC, MorrisJobke approved these changes

2020-10-19 18:01 UTC, Cybso commented
@blizzz I'm still not very familiar with the extended git features. I've used "git rebase -i HEAD~2" to squash the second commit with the first one, but when I try to push this to Github, I get the following error:

```
To github.com:Cybso/server.git
 ! [rejected]              23174-revert-commit-from-54a5f938f99 -> 23174-revert-commit-from-54a5f938f99 (non-fast-forward)
error: Fehler beim Versenden einiger Referenzen nach 'git@github.com:Cybso/server.git
```

Can you give me I hint how to fix this?

2020-10-19 18:02 UTC, ChristophWurst commented
> Can you give me I hint how to fix this?

You need `--force` ;)

2020-10-19 18:39 UTC, nickvergessen requested changes

2020-10-19 18:39 UTC, nickvergessen commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
We need a follow up migration which fixes existing instances?

2020-10-26 08:22 UTC, Cybso commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
I think it would be nice to have matching database definition across all instances, but exactly required. The module won't write any NULL values into this column, so at least for MySQL and SQLite it doesn't matter if it's true or false (cannot speak for Oracle). An alternative implementation would be to add a second call which updates the database definition to "NotNull = true" and removes the default value **after the table has been extended**.

@blizzz, what's your opinion?

2020-10-26 09:51 UTC, blizzz commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
Consistency and an expected state is to be preferred, otherwise we indeed may run into trouble in future changes. So, yes, a migration step would be ideal to add.

2020-11-10 21:02 UTC, Cybso commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
Sorry, I've tried, but at the moment I do not find the time to implement this second migration. Can someone take over?

2020-11-10 21:26 UTC, nickvergessen commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
I will

2020-11-10 21:27 UTC, nickvergessen commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'notnull' => false,
I will

2020-11-16 14:48 UTC, nickvergessen commented
Done in https://github.com/nextcloud/server/pull/23882

2020-11-16 14:48 UTC, closed without merging