Settings: new user row replaced by a modal
nextcloud/server pull request #23529
Opened 2020-10-16 18:50 UTC by Simounet

Hi there,
I know that I have to commit the compiled files but I need some help here. `make watch-js` changes files without me touching anything.
Another issue is that on modal opening, the HTML validation displays error on password and mail inputs. Did I miss something here because it wasn't an issue before.

Here is a screenshot of the result:
![nextcloud-settings-new-user-modal](https://user-images.githubusercontent.com/582666/96297354-00ce7f00-0ff1-11eb-98d1-4e38a0b810ff.png)

Linked to #23397.

Have a good night and stay safe.

2020-10-16 19:43 UTC, kesselb commented
/compile amend /

2020-10-16 19:45 UTC, kesselb commented
> make watch-js changes files without me touching anything.

I have the same issue from time to time. Usually fixed by rm -rf node_modules. Maybe not bad to use node 12.x. Super cool enhancement and much better then before :+1:

2020-10-16 20:04 UTC, Simounet commented
I tried to clean my env but it's not working. I'm running Node v12.14.1.

2020-10-21 16:17 UTC, axheli commented
@jancborchardt What do you think about this?

2020-10-22 09:28 UTC, Simounet commented
I put the display name first and the popin is larger.

![nextcloud-settings-new-user-modal-larger](https://user-images.githubusercontent.com/582666/96852602-9e92d580-1459-11eb-84cc-93319e969f64.png)

The last issue here is about the HTML validation when the popin appears.

2020-10-22 10:08 UTC, kesselb commented
cc @skjnldsv any idea why the form validation triggers on modal open?

2020-10-22 10:10 UTC, skjnldsv commented
> cc @skjnldsv any idea why the form validation triggers on modal open?

Probably a chaining events. Make sure you use an event stop on the button

2020-10-22 10:16 UTC, kesselb commented on apps/settings/src/components/UserList.vue
> +			<form v-show="showConfig.showNewUserForm"
Should also work without v-show as the modal already has v-if.

2020-10-22 10:23 UTC, kesselb commented
Or it's probably the default behaviour :thinking: 

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
https://mdn.github.io/learning-area/html/forms/form-validation/full-example.html

Each element with required get the :invalid state.

2020-10-22 10:24 UTC, skjnldsv commented
Ah, I misunderstod "form validation". I understood that as "submit". :)
Yes, it's normal if you use field types

2020-10-22 12:44 UTC, Simounet commented on apps/settings/src/components/UserList.vue
> +			<form v-show="showConfig.showNewUserForm"
You're absolutely right. I fixed it.

2020-10-22 12:45 UTC, Simounet commented
I get what was bothering me. Previous style override the red border so I put that here. It's not perfect but it's better than having red border without touching anything.

2020-10-22 18:34 UTC, axheli commented
> I put the display name first and the popin is larger.
> 
> ![nextcloud-settings-new-user-modal-larger](https://user-images.githubusercontent.com/582666/96852602-9e92d580-1459-11eb-84cc-93319e969f64.png)
> 
> The last issue here is about the HTML validation when the popin appears.

Looks good!! Nice work

2020-10-23 08:54 UTC, skjnldsv commented on apps/settings/src/components/UserList.vue
> +					type="text">
I disagree with his change. Displayname is optional, username is not. It should stay first :)

2020-10-23 08:55 UTC, skjnldsv commented on apps/settings/src/views/Users.vue
> +					window.newdisplayname.focus()
Same remark related tot he first field and userid/displayname swap

2020-10-23 08:55 UTC, skjnldsv commented on apps/settings/src/components/UserList.vue
> +	}
Please use the default Modal sizes. No need to use css :)
You can use the isMobile mixin and change between sizes accordingly

2020-10-23 08:56 UTC, skjnldsv commented on apps/settings/src/components/UserList.vue
> +	}
Seems like an odd change, why was it needed?

2020-10-23 08:57 UTC, skjnldsv requested changes
A few comments. Please abuse comments on your css code, especially v-deeps. Otherwise we don't know why you had to do it and maintaining is complicated :)

Same for other functions, it's a good habit to put more comments. It will get stripped for the build anyway, file size doesn't matter here.

2020-10-23 09:16 UTC, Simounet commented on apps/settings/src/components/UserList.vue
> +	}
Because of the default border of 1px on each side. Without changing the box sizing, I have 2 extra pixels.

2020-10-23 09:19 UTC, Simounet commented on apps/settings/src/components/UserList.vue
> +	}
We told me in the issue that the default width was to stretch. I will roll back to the default one. No problem. :)

2020-10-23 09:20 UTC, Simounet commented
Ahah, some people love comments where some others don't. I will remember that they are appreciated here. :)

2020-11-05 19:26 UTC, axheli commented
@Simounet How's this project going?

2020-11-05 21:10 UTC, skjnldsv commented
@Simounet please rebase :)

2020-11-06 08:33 UTC, Simounet commented
@axheli Everything is ok IMO.
@skjnldsv Done! :)

2020-11-12 11:35 UTC, Simounet commented
Everything is green on my side. :)

2020-11-12 11:49 UTC, skjnldsv approved these changes
Good from my side, but you need to adjust the acceptance tests :)

2020-11-17 10:43 UTC, juliushaertl commented
:ping_pong: @jancborchardt

2020-11-19 14:16 UTC, skjnldsv commented
> @juliushaertl added [2. developing](/nextcloud/server/labels/2.%20developing) and removed [3. to review](/nextcloud/server/labels/3.%20to%20review) labels

Why?

2020-11-19 14:18 UTC, juliushaertl commented
Because of the acceptance tests ;) I always considered tests as something in "developing" state.

2020-11-19 14:26 UTC, Simounet commented
I'm trying to fix that right now.

2020-11-19 14:30 UTC, Simounet commented
I would really appreciate any help to debug this "easily".

2020-11-26 12:27 UTC, juliushaertl commented
@danxuliu to the rescue

2020-11-27 07:42 UTC, danxuliu commented
I will not be able to check this until next week at least, sorry :-(

2020-11-27 08:01 UTC, Simounet commented
I remember a time when we could execute Selenium test directly in the browser to debug it and see what was wrong. Is it still a thing? I will look into that but if you already have a command, it would really be appreciated. :D

2020-11-27 08:24 UTC, skjnldsv commented
> Is it still a thing?

Yes, you can execute the run-local.sh script and access through vnc on localhost :)

2020-11-29 21:38 UTC, Simounet commented
Ok so I get deeper. It seems that this is not working on Firefox ~47 that is the version used with Selenium. It's working as expected on Firefox 83. I'm trying get the reason.

2020-11-30 02:40 UTC, axheli commented
Nice job Firefox 47 that was released back in June 2016 idk if we should really support that especially since that would be a security concern

2020-11-30 08:12 UTC, skjnldsv commented
> Nice job Firefox 47 that was released back in June 2016 idk if we should really support that especially since that would be a security concern

This is for testing only. We do not support FF47 on runtime.
We indeed know that our selenium testing is stuck on old version, upgrading is too complicated.
We need to migrate to a different acceptance test suite

2021-01-08 17:10 UTC, axheli commented
Hey guys any updates on this it would be very nice to have this in Nextcloud 21

2021-02-26 15:03 UTC, axheli commented
@Simounet is there still an issue with the code ?

2021-03-02 06:46 UTC, skjnldsv commented
I think the acceptance test fail is valid.
@Simounet can you rebase?

2021-03-02 09:22 UTC, eneiluj approved these changes
Code looks sane, the modal is much nicer!

2021-03-02 11:57 UTC, Simounet commented
I rebased and push. Just waiting for the CI.

2021-03-08 04:21 UTC, danxuliu commented
Sorry a lot for the delay.

#25991 updates the browser used in the acceptance tests to a recent version. With that recent version the dialog works as expected :-)

However, turns out that the header test was wrong! It was trying to add the user "user1", but [that user is already added when installing and configuring the server](https://github.com/nextcloud/server/blob/4679926511c9e845a26eb4c9ab606ce889feea21/tests/acceptance/installAndConfigureServer.sh#L38), so it is already added in all tests. Thus, even if the dialog worked properly, the test would also fail because adding the user would fail, the dialog would not be closed, and the following steps would fail. The header test is fixed by #25990

Due to all that this pull request should be rebased on master once #25990 and #25991 are both merged and everything should then work (I have also added a fixup commit to this pull request to do a minor adjustment).

2021-03-08 07:55 UTC, Simounet commented
I can't wait to see this PR merged! Thanks for the reply. I don't get why you removed my test to check if the modal is not here. Is it somewhere else on your PRs?

2021-04-21 11:18 UTC, danxuliu commented
#25991 has been finally merged, so I took the liberty to rebase this pull request to latest master :-)

> I don't get why you removed my test to check if the modal is not here. Is it somewhere else on your PRs?

Sorry, I missed the question. I removed the check because I think that it is not strictly needed in that scenario. When possible the acceptance tests should not go into specific details like whether a modal is used or not, and in this case it should be enough to just verify that the user was indeed added to the list to continue.

Of course it could happen that the modal was not properly closed, so a check for that could still be added in the scenarios related to user creation, or inside the step [`I create user :user with password :password`](https://github.com/nextcloud/server/blob/14b85f4eec959417db8e8ab3f765edaf18ba10d4/tests/acceptance/features/bootstrap/UsersSettingsContext.php#L236) (as that is a high level step that abstracts a "complex" action, and the modal being closed would be part of that action). But for me it still feels like something not being tested at the right scope, so I did not add it :-)

2021-04-21 11:23 UTC, andyxheli commented
this is finally happening 🙏🏻😁 super excited

2021-04-21 14:38 UTC, merged

2021-04-21 14:39 UTC, skjnldsv commented
All tests passed! Well done!!

2021-04-21 14:41 UTC, Simounet commented
Glad to see this finally merged! Thank you everyone for your support in my first real PR on this amazing piece of software.
Hope you'll enjoy this "feature" @andyxheli ! :D

2021-04-21 14:43 UTC, andyxheli commented
> Glad to see this finally merged! Thank you everyone for your support in my first real PR on this amazing piece of software.
> 
> Hope you'll enjoy this "feature" @andyxheli ! :D

Thank you so much brother for making this happen. Definitely will 😁 have a nice day.