Check if array elements exist before using them
nextcloud/server pull request #23645
Opened 2020-10-23 10:43 UTC by rullzer

It seems that in some recent upgrade here. Not always the entries we
expect are returned. So we should first check if they exist. As to not
spam the log.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2020-10-23 11:43 UTC, MorrisJobke approved these changes
code makes sense 👍

2020-10-23 11:44 UTC, MorrisJobke commented
I amended your commit, because there was one additional space behind the if statement.

2020-10-23 14:40 UTC, kesselb commented
Looks similar to https://github.com/nextcloud/server/pull/23591 :thinking:

2020-10-23 14:44 UTC, kesselb requested changes

2020-10-23 14:44 UTC, kesselb commented on apps/files_external/lib/Lib/Storage/AmazonS3.php
> +				if ((isset($result['Contents'][0]['Key']) && $result['Contents'][0]['Key'] === rtrim($path, '/') . '/')
It does not set directoryCache[$path] to false anymore.

2020-10-24 08:11 UTC, rullzer commented on apps/files_external/lib/Lib/Storage/AmazonS3.php
> +				if ((isset($result['Contents'][0]['Key']) && $result['Contents'][0]['Key'] === rtrim($path, '/') . '/')
Good point

2020-10-25 21:04 UTC, MorrisJobke commented
> I amended your commit, because there was one additional space behind the if statement.

Did it again, because you overwrote it 😝

2020-10-25 21:04 UTC, MorrisJobke approved these changes

2020-10-26 11:46 UTC, rullzer commented
/backport to stable20

2020-10-26 11:46 UTC, rullzer commented
/backport to stable19

2020-10-26 11:46 UTC, rullzer commented
/backport to stable18

2020-10-27 10:52 UTC, nickvergessen approved these changes

2020-10-27 10:55 UTC, merged