Add default font size
nextcloud/server pull request #23798
Opened 2020-10-30 14:32 UTC by GretaD

Add default font size on the variables

2020-10-30 14:33 UTC, GretaD commented
@skjnldsv should i do the same here: https://github.com/nextcloud/nextcloud-vue/blob/master/styleguide/assets/variables.css

2020-10-30 14:39 UTC, skjnldsv commented
You also need to use this value on our scripts now :)

Like there for example
https://github.com/nextcloud/server/blob/e1a0b3f98fb28ec3d193f32a85dd77795baf88f7/core/css/styles.scss#L92

2020-11-02 08:20 UTC, ma12-co approved these changes
:tada:

2020-11-02 08:24 UTC, ma12-co reviewed
The only thing is I wouldn't call it `font-size` only as it creates a bit of confusion with the css rule. Maybe `default-font-size` or `main-font-size`?

2020-11-02 08:39 UTC, skjnldsv commented
@ma12-co have you checked the code?
There is a conflict between your change using `.9375em;` and this variable.
Could your provide guidance to know what/where needs to be changed for the server styling to use this.
And why are we not using `px` but `em` :)
Thanks! :v:

2020-11-02 08:44 UTC, skjnldsv requested changes
Blocking to make sure we're also using the variable on the places where we have a font-size on server :)

Also see https://github.com/nextcloud/server/pull/23267

2020-11-02 13:40 UTC, ma12-co commented
> Could your provide guidance to know what/where needs to be changed for the server styling to use this.

I think it would be enough to set:
`font-size: var(--root-font-size)` here:
https://github.com/nextcloud/server/blob/e1a0b3f98fb28ec3d193f32a85dd77795baf88f7/core/css/styles.scss#L92

No need to use `em` values anymore imo, we were using it just because the browser's default font size is 16px and we were just multiplying it with different coefficients. I see no advantages in that.
Also, since you're doing this @GretaD, could you make a variable for `line-height` as well and replace the line below with it too? It should be 24px.
`line-height: var(--root-line-height)`
https://github.com/nextcloud/server/blob/e1a0b3f98fb28ec3d193f32a85dd77795baf88f7/core/css/styles.scss#L93

2020-11-02 16:11 UTC, GretaD commented
> Blocking to make sure we're also using the variable on the places where we have a font-size on server :)

you mean everywhere? Like where we have `font-size: 20px` -- i should do `font-size: $default-font-size +5 ` Or only where we use the default one.? I changed the ones you and Marco asked.

2020-11-02 16:46 UTC, skjnldsv commented
> you mean everywhere? Like where we have `font-size: 20px` -- i should do `font-size: $default-font-size +5 ` Or only where we use the default one.? I changed the ones you and Marco asked.

No, only where we use 15 (might even be some leftovers 14 somewhere, feel free to adjust)

2020-11-02 17:34 UTC, GretaD commented
> > you mean everywhere? Like where we have `font-size: 20px` -- i should do `font-size: $default-font-size +5 ` Or only where we use the default one.? I changed the ones you and Marco asked.
> 
> No, only where we use 15 (might even be some leftovers 14 somewhere, feel free to adjust)

good :) will update asap

2020-11-03 12:11 UTC, GretaD commented
ready for review, i think i changed all the default ones

2020-11-03 12:23 UTC, skjnldsv requested changes
You need to use the css variables not the scss ones :)

2020-11-03 12:23 UTC, skjnldsv commented on apps/settings/src/components/Markdown.vue
> +		font-size: $default-font-size;
```suggestion
		font-size: var(--default-font-size);
```

2020-11-03 12:23 UTC, skjnldsv commented on core/src/components/UnifiedSearch/SearchResult.vue
> +		font-size: $default-font-size;
```suggestion
		font-size: var(--default-font-size);
```

2020-11-03 12:23 UTC, skjnldsv commented on core/src/views/UnifiedSearch.vue
> +            font-size: $default-font-size;
```suggestion
            font-size: var(--default-font-size);
```

2020-11-03 12:54 UTC, GretaD commented on apps/settings/src/components/Markdown.vue
> +		font-size: $default-font-size;
ah damn

2020-11-03 14:03 UTC, skjnldsv approved these changes

2020-11-03 17:25 UTC, ma12-co approved these changes

2020-11-03 17:25 UTC, merged

2020-11-05 07:12 UTC, skjnldsv commented
/backport to stable20