Cleanup routing
nextcloud/server pull request #23819
Opened 2020-10-31 11:14 UTC by rullzer

Before this routing mess was very cyclic

Routers => get the routes.php => initiate the App => register the routes on the app => register the routes on the router

Now the router just takes the routes and parses them properly.

2020-11-03 08:34 UTC, MorrisJobke approved these changes
Tested and works 👍

2020-11-03 10:00 UTC, ChristophWurst commented on lib/private/Route/Router.php
> -			$application->registerRoutes($this, $routes);
`registerRoutes` is deprecated but it might be overridden by an app. I think we should still invoke the method, no?

2020-11-03 10:59 UTC, skjnldsv approved these changes

2020-11-03 11:04 UTC, ChristophWurst requested changes, later dismissed
making sure nobody clicks the shiny green merge button

https://github.com/nextcloud/server/pull/23819#discussion_r516546737

2020-11-03 11:46 UTC, rullzer commented on lib/private/Route/Router.php
> -			$application->registerRoutes($this, $routes);
pffff in theory... but then we will register the routes double....

2020-11-03 11:49 UTC, ChristophWurst commented on lib/private/Route/Router.php
> -			$application->registerRoutes($this, $routes);
@MorrisJobke could you check if anyone overwrites this in your famous *all apps* library?

2020-11-04 21:13 UTC, MorrisJobke commented on lib/private/Route/Router.php
> -			$application->registerRoutes($this, $routes);
Let's call it "many many many apps", because I guess there are quite some apps out there that I missed :(

2020-11-04 21:15 UTC, MorrisJobke commented on lib/private/Route/Router.php
> -			$application->registerRoutes($this, $routes);
Seems to not be overwritten by any of the apps I cloned.

2020-11-04 21:16 UTC, merged