Make sure root storage is valid before checking its size
nextcloud/server pull request #23982
Opened 2020-11-07 23:11 UTC by skjnldsv

Fix https://github.com/nextcloud/server/issues/23579

2020-11-07 23:11 UTC, skjnldsv commented
/backport to stable20

2020-11-07 23:11 UTC, skjnldsv commented
/backport to stable19

2020-11-09 07:47 UTC, rullzer requested changes

2020-11-09 07:47 UTC, rullzer commented on lib/private/Files/Storage/Wrapper/Quota.php
> +			}
Nope... you should properly return SPACE_NOT_COMPUTED then or something. Just retruning nothing seems weird.

2020-11-09 07:50 UTC, skjnldsv commented on lib/private/Files/Storage/Wrapper/Quota.php
> +			}
Done
Missed that

2020-11-09 08:56 UTC, MorrisJobke approved these changes
🙈

2020-11-09 09:51 UTC, ChristophWurst approved these changes

2020-11-09 10:03 UTC, merged