allow selecting multiple columns with SELECT DISTINCT
nextcloud/server pull request #24007
Opened 2020-11-09 16:44 UTC by icewind1991

Signed-off-by: Robin Appelman <robin@icewind.nl>

2020-11-09 16:44 UTC, icewind1991 commented
/backport to stable20

2020-11-09 17:20 UTC, nickvergessen requested changes

2020-11-09 17:20 UTC, nickvergessen commented on tests/lib/DB/QueryBuilder/QueryBuilderTest.php
> +		$this->queryBuilder->selectDistinct(['appid', 'value']);
Can't select distinct a clob on oracle 💥

2020-11-10 19:28 UTC, MorrisJobke approved these changes
Code makes sense 👍

2020-11-10 21:31 UTC, nickvergessen commented
Let me run this on oracle tomorrow

2020-11-16 18:44 UTC, nickvergessen approved these changes

2020-11-19 21:39 UTC, merged