#3903 add Background job for cleanup of unneeded remote storages
nextcloud/server pull request #24095
Opened 2020-11-13 08:10 UTC by european

Signed-off-by: Nils Werner <sammellog@gmail.com>

This change add a new background job to execute the command CleanupRemoteStorages

See #3903 for more details.

2022-12-14 15:28 UTC, max-nextcloud commented
Looks like this PR was overseen because it has no review was requested.
I'll rebase, resolve the conflicts and request a review.

2022-12-16 13:07 UTC, european commented
> @european I hope you don't mind if i squash your commits into one as the follow up commits are all fixing things in the first one.

all fine, I missed this PR as well after that. I was not sure how to continue, since it was my first pr I created for this project

2023-01-20 16:59 UTC, max-nextcloud approved these changes
Did not test it but code looks fine.

2023-01-22 22:18 UTC, max-nextcloud requested changes
Checked in with some colleagues about this pull request.

Instead of triggering the CLI command from the background job the logic should be in a service that is used by both, the Background Job and the CLI command.

That would also avoid using a `NullOutput` to hide the output.
Background jobs still may need to report errors so hiding the output entirely does not seem like a good idea.

2023-01-22 22:22 UTC, max-nextcloud commented
@european Sorry it took so long to get back to you in the first place.

Would you be willing to pick this up again? I'd be happy to follow up to make sure reviews happen and so on.

2024-02-27 13:17 UTC, skjnldsv commented
> @european Sorry it took so long to get back to you in the first place.
> 
> Would you be willing to pick this up again? I'd be happy to follow up to make sure reviews happen and so on.

I guess not :cry: 

@european 
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open and solve the various conflicts.

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2024-02-27 13:17 UTC, closed without merging