extend cache events
nextcloud/server pull request #24113
Opened 2020-11-13 16:05 UTC by icewind1991

- adds cache remove event
- expose storage id in event
- emit events during cache move

Signed-off-by: Robin Appelman <robin@icewind.nl>

2020-11-16 13:17 UTC, rullzer commented on lib/private/Files/Cache/Cache.php
> +				$this->eventDispatcher->dispatch(CacheInsertEvent::class, new CacheInsertEvent($this->storage, $file, $fileId, $storageId));
mmm these are the old events right.
Would it make sense to create new ones that we can use?

@ChristophWurst @MorrisJobke

2020-11-17 16:38 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +				$this->eventDispatcher->dispatch(CacheInsertEvent::class, new CacheInsertEvent($this->storage, $file, $fileId, $storageId));
why is a new event needed?

2020-11-17 17:33 UTC, ChristophWurst commented on lib/private/Files/Cache/Cache.php
> +				$this->eventDispatcher->dispatch(CacheInsertEvent::class, new CacheInsertEvent($this->storage, $file, $fileId, $storageId));
I think this was a misunderstanding. The event class extends ``\OCP\EventDispatcher\Event``, so this should be fine. With "old event" @rullzer referred to the deprecated GenericEvent I guess …

2020-11-17 17:36 UTC, ChristophWurst commented on lib/public/Files/Cache/CacheRemoveEvent.php
> +class CacheRemoveEvent extends AbstractCacheEvent {
`CacheEntryRemovedEvent`? https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#naming-scheme

2020-11-17 18:44 UTC, rullzer commented on lib/private/Files/Cache/Cache.php
> +				$this->eventDispatcher->dispatch(CacheInsertEvent::class, new CacheInsertEvent($this->storage, $file, $fileId, $storageId));
Ah my bad. Carry on

2020-11-19 21:50 UTC, MorrisJobke commented on lib/private/Files/Cache/Cache.php
> +				$this->eventDispatcher->dispatch(CacheRemoveEvent::class, new CacheRemoveEvent($this->storage, $sourcePath, $sourceId, $sourceCache->getNumericStorageId()));
use `dispatchTyped` and just pass the event. That does exactly the same, but without the problem of using different name and event type.

2020-11-19 21:51 UTC, MorrisJobke commented on lib/public/Files/Cache/CacheRemoveEvent.php
> +class CacheRemoveEvent extends AbstractCacheEvent {
But then we should also add new ones for `CacheUpdateEvent` and `CacheInsertEvent` and deprecate the old ones.

2020-11-19 21:52 UTC, MorrisJobke commented on lib/public/Files/Cache/CacheRemoveEvent.php
> +class CacheRemoveEvent extends AbstractCacheEvent {
And it should also state `extends Event implements ICacheEvent` because otherwise this detail is hidden in private namespace.

2020-11-26 14:54 UTC, icewind1991 commented
renamed the events

2020-11-26 15:21 UTC, ChristophWurst approved these changes

2020-11-30 21:02 UTC, MorrisJobke commented on lib/private/Files/Cache/Cache.php
> +			$this->eventDispatcher->dispatch(CacheEntryRemovedEvent::class, new CacheEntryRemovedEvent($this->storage, $entry->getPath(), $entry->getId(), $this->getNumericStorageId()));
```suggestion
			$this->eventDispatcher->dispatchTyped(new CacheEntryRemovedEvent($this->storage, $entry->getPath(), $entry->getId(), $this->getNumericStorageId()));
```

2020-11-30 21:03 UTC, MorrisJobke requested changes
code style needs to be run but then it looks good 👍

2020-12-02 15:23 UTC, icewind1991 commented
> code style needs to be run but then it looks good

done

2020-12-02 15:36 UTC, MorrisJobke approved these changes

2020-12-02 18:48 UTC, merged

2021-09-13 15:54 UTC, icewind1991 commented
/backport to stable20