WIP Send images to imaginary docker to generate previews
nextcloud/server pull request #24166
Opened 2020-11-16 21:22 UTC by PVince81

:warning: prototype mode :warning: 

@rullzer as mentioned :-)

To test:

1. `docker run -p 9090:9000 h2non/imaginary` (notice the port map difference to keep 9000 free for PHP debuggers...)
2. Edit Imaginary.php and change the hardcoded URL to wherever that docker is running
3. Upload some jpeg pictures and see the previews rendered

### Some issues/topics:

#### Preview manager issues

- [ ] why is the maxX/maxY always 4096 even though the UI is requesting less than 400x400 ? (did I find a bug?)
- [ ] BUG? even if setting only "Preview\Imaginary" in "enabledPreviewProviders", it still doesn't seem to be registered properly due to the other defaults. I was actually expecting "enabledPreviewProviders" to override the defaults. (did I find a bug?)

#### Imaginary preview topics

- [ ] $response->getBody() is a string, but should be a stream
- [ ] optional perf improvement: if we know a file to be on local non-encrypted storage, could send the file path directly to the docker (when running on same instance)
- [ ] gif not supported, it returns an error. might need more option
- [ ] seems we do need multipart here, PUT not supported :-/

- [ ] need to do some perf benchmarks and compare with the "native" way

2020-11-16 21:58 UTC, PVince81 commented
Quick benchmark with 4 jpg files with roughly the same size:
- with Imaginary: ~4.7 second
- native way: ~7.5 seconds

2020-11-17 07:51 UTC, rullzer commented
@PVince81 why not do this as an app?

2020-11-17 07:52 UTC, rullzer commented
> why is the maxX/maxY always 4096 even though the UI is requesting less than 400x400 ? (did I find a bug?)

No that was the part I also ran into when I wrote an imaginary app to play preview provider.
The preview provider is only used to generate the initial preview (so the highest resolution one)
Then we use GD to create the downsized images.

2020-11-17 08:19 UTC, PVince81 commented
> @PVince81 why not do this as an app?

because only a prototype for benchmarking, it's easier to push a PR that way.
in any case this is to be discussed first.
if worth it, we can make an app, yes.

I suspect we might need to tweak the preview manager to make it possible to override the default preview providers, which somehow didn't work when I tested (hence the early "return" in this PR)

2020-11-17 08:24 UTC, PVince81 commented
- [ ] should we use Imaginary also for the small resizes from the cached image instead of GD ? (make the preview manager support such operations by third parties ?)

2020-11-17 08:30 UTC, PVince81 commented
work to be continued in this app: https://github.com/rullzer/imaginary/issues/1

I'll leave the PR open until we have transferred the tasks and code

2022-02-11 01:06 UTC, CarlSchwan commented
Benchmarks with s3:

Small images (256x256):

* imaginary: ~0.7s
* current Image provider: ~0.4s

Bigger image: HD

* imaginary: ~1.5s
* current image providers: ~2.5s

So it seems that the overhead from the network is really only worth it for larger images there the multithreading of imaginary really helps. This should be most pictures as taking small 256x356 images is not really a thing anymore

2022-02-11 13:40 UTC, CarlSchwan commented
Found an issue, we don't get the width and height of the generated preview, so we currently assume it's 4096x4096 and this is causing an issue for small images (< 1000x1000) as we then generate an additional preview for nothing.

I made a PR upstream https://github.com/h2non/imaginary/pull/382 to solve this

2022-02-11 13:54 UTC, PVince81 commented on lib/private/Preview/Imaginary.php
> +		$baseUrl = $this->config->getSystemValueString('preview_imaginary_url', 'http://previews_hpb:8088');
don't hardcode default URL and log an error when not set

2022-02-15 09:46 UTC, PVince81 reviewed
Code looks fine to me. Can't approve as I'm co-author :smile: 

Did you test that the default config still uses the old preview provider ?

2022-02-15 10:02 UTC, CarlSchwan commented
> Code looks fine to me. Can't approve as I'm co-author 😄
> 
> Did you test that the default config still uses the old preview provider ?

Yes, I tested it when doing the benchmarks.

2022-02-15 10:30 UTC, come-nc reviewed
php-cs check is not happy on several files.

Do I understand correctly that for images smaller than the wanted preview size they are still streamed to the service and back? Could we avoid it?

Can you provide more details regarding fake implementations in StreamImage? Are these methods never called or is it just fine for them to misbehave? Shouldn’t some throw an Exception when called if they do not make sense?

2022-02-15 10:30 UTC, come-nc commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
Ok as $maxX and $maxY are int, but if this ever gets more complicated I’d feel better if it went through `http_build_query`

2022-02-15 10:45 UTC, CarlSchwan commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
> php-cs check is not happy on several files.
> 
> Do I understand correctly that for images smaller than the wanted preview size they are still streamed to the service and back? Could we avoid it?

A bit tricky, as we need to determine the image dimension and for that, we need to fetch the image from s3 and stream it to imaginary to determine the size (or use gd). That would IMHO make sense would be to not store the preview if it is the same size as the original image. This is actually easy to determine if this is the case but would need some bigger change in how we fetch the previews later on (currently just looking if a file with $name-max.$ext exists).

> Can you provide more details regarding fake implementations in StreamImage? Are these methods never called or is it just fine for them to misbehave? Shouldn’t some throw an Exception when called if they do not make sense?

The idea behind the StreamImage is that unlike the normal OC_Image we don't copy the images in the RAM (with gd), and then upload it to s3 directly without doing any further manipulation and instead just stream it back directly to S3 or to the file system (depending on the primary storage).

Throwing an exception is indeed a better idea (and easier to detect if we actually use one of the methods instead of silently giving a wrong result).

2022-02-15 10:46 UTC, artonge requested changes

2022-02-15 10:46 UTC, artonge commented on lib/private/Preview/Imaginary.php
> +		$client = $this->service->newClient();
```suggestion
		$httpClient = $this->httpClientService->newClient();
```

2022-02-15 10:46 UTC, artonge commented on lib/private/Preview/Imaginary.php
> +		$baseUrl = $this->config->getSystemValueString('preview_imaginary_url', 'invalid');
```suggestion
		$imaginaryUrl = $this->config->getSystemValueString('preview_imaginary_url', 'invalid');
```

2022-02-15 11:36 UTC, come-nc commented on lib/private/Preview/Imaginary.php
> +				]);
```suggestion
		$parameters = [
			'width' => $maxX,
			'height' => $maxY,
			'stripmeta' => 'true',
			'type' => 'jpeg',
		];

		try {
			$response = $httpClient->post(
				$imaginaryUrl . '/fit', [
					'query' => $parameters,
					'stream' => true,
					'content-type' => $file->getMimeType(),
					'body' => $stream,
					'nextcloud' => ['allow_local_address' => true],
				]);
```

I’m pretty sure you can do it like this, query entry is not documented for post in our http client class but I think guzzle will accept it on any request, the opposite would be weird.

2022-02-15 11:40 UTC, come-nc commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
> A bit tricky, as we need to determine the image dimension and for that, we need to fetch the image from s3 and stream it to imaginary to determine the size (or use gd). That would IMHO make sense would be to not store the preview if it is the same size as the original image. This is actually easy to determine if this is the case but would need some bigger change in how we fetch the previews later on (currently just looking if a file with $name-max.$ext exists).

Given the dimensions are returned in the header by the imaginary service, would there be any performance gain to close the connection if the header gives the same dimensions as original and stream the original instead?

2022-02-15 13:15 UTC, CarlSchwan commented on lib/private/Preview/Imaginary.php
> +				]);
it works

2022-02-23 08:34 UTC, PVince81 commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
@CarlSchwan @come-nc is this a blocker for merging ?

2022-02-24 16:02 UTC, CarlSchwan commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
No, it's not the current code has the same issue :(

2022-03-10 15:16 UTC, PVince81 commented on lib/private/Preview/Imaginary.php
> +			$baseUrl . "/fit?width=$maxX&height=$maxY&stripmeta=true&type=jpeg", [
then perhaps we can skip this

we have some future ideas about extracting exif metadata, so it would be possible to know the size in advance at that time

2022-03-16 11:51 UTC, juliushaertl approved these changes
Tested and works, code looks good as well 👍

2022-03-16 12:56 UTC, PVince81 commented
:+1: from me for the changes past my original commits

2022-03-16 12:57 UTC, CarlSchwan approved these changes
+1 for the commits not from me :laughing:

2022-03-17 04:39 UTC, Pytal approved these changes

2022-03-17 07:25 UTC, juliushaertl commented
Fixed the missing phpdoc on `IStreamImage`, CI should be happy now

2022-03-18 11:32 UTC, merged

2022-03-18 11:45 UTC, szaimen commented
backports?

2022-03-24 09:13 UTC, PVince81 commented
> backports?

no backport, this is a new feature and also brings in a new public interface