Update Version2000Date20190808074233.php
nextcloud/server pull request #24208
Opened 2020-11-18 20:51 UTC by jbowen116

Modify 'protected function ensureEntityColumns()' to set a default of ' '. Fixes the broken automatic update from 17.0.10 to 18.0.10. 

Specifically implements the solution commented here: https://github.com/nextcloud/server/issues/23174#issuecomment-714296723

2020-11-19 08:33 UTC, ChristophWurst commented
This doesn't seem right. If the column can contain empty strings, then it should be nullable. Oracle would choke on that as well, right @nickvergessen?

2020-11-19 08:43 UTC, blizzz commented
> This doesn't seem right. If the column can contain empty strings, then it should be nullable. Oracle would choke on that as well, right @nickvergessen?

This is also what I understand.

`default` should be removed then, I suppose?

2020-11-19 12:57 UTC, juliushaertl commented
Yes, see https://github.com/nextcloud/server/pull/24079/commits/32d7459d8b9f3918e42cfe80f3a9537528032997 for how to properly migrate a column from notnull => true, to notnull => false.

You will need to adjust the existing migration so that it is properly set on new Nextcloud installations as well as adding a new migration step to fix the column on existing installations.

2020-11-19 13:29 UTC, jbowen116 commented
> This doesn't seem right. If the column can contain empty strings, then it should be nullable. Oracle would choke on that as well, right @nickvergessen?

I agree with you. Before I considered looking at this code, I manually created that column and made it nullable. That didn't work for me, either. I assumed the code in the update was still choking on the changes (maybe trying to 're-do' the database changes?). It's almost certain there's a better fix than what I've proposed here...I don't love the idea of creating single-space DEFAULT entries, either.

2020-11-23 10:11 UTC, rullzer requested changes

2020-11-23 10:11 UTC, rullzer commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'default' => ' ',
Would not removing this be the proper way to go?

2020-11-23 11:12 UTC, juliushaertl commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'default' => ' ',
@blizzz Might know exactly but iirc the entity might be empty for old workflowengine rules from before Nextcloud 18 when migrating.

2020-11-23 17:58 UTC, blizzz commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'default' => ' ',
In 18 we have a repair steps that fills the column. This is done after migration, because the column in question did not exist in 17. Setting the default to `\OCA\WorkflowEngine\Entity\File::class` would then be the right thing, as this is what the post migration job would do to any column that appears empty. Which would render this part of the post-migration script unnecessary, if I do not oversee anything.

2020-11-23 20:09 UTC, MorrisJobke commented on apps/workflowengine/lib/Migration/Version2000Date20190808074233.php
> +				'default' => ' ',
@blizzz Mind to do this change in a PR directly?

2020-11-23 20:22 UTC, blizzz commented
replaced by https://github.com/nextcloud/server/pull/24315 for https://github.com/nextcloud/server/pull/24208#discussion_r528894725

2020-11-23 20:22 UTC, closed without merging