Use proper methods for display name retrieval
nextcloud/server pull request #24318
Opened 2020-11-23 22:53 UTC by MorrisJobke

* [ ] add removal to #23210

2020-11-23 22:57 UTC, blizzz approved these changes
code looks good

2020-11-24 07:01 UTC, skjnldsv commented on apps/files_sharing/lib/Cache.php
> +			$user = \OC::$server->get(IUserManager::class)->get($uid);
DI?

2020-11-24 07:02 UTC, skjnldsv commented on lib/private/TemplateLayout.php
> +			$user = \OC::$server->get(IUserSession::class)->getUser();
DI?

2020-11-24 07:02 UTC, skjnldsv commented on lib/private/TemplateLayout.php
> +			$user = \OC::$server->get(IUserSession::class)->getUser();
DI?

2020-11-29 20:43 UTC, MorrisJobke commented on lib/private/TemplateLayout.php
> +			$user = \OC::$server->get(IUserSession::class)->getUser();
Not used at all in this class 🙈

2020-11-29 20:43 UTC, MorrisJobke commented on lib/private/TemplateLayout.php
> +			$user = \OC::$server->get(IUserSession::class)->getUser();
Not used at all in this class 🙈

2020-11-29 20:45 UTC, MorrisJobke commented on apps/files_sharing/lib/Cache.php
> +			$user = \OC::$server->get(IUserManager::class)->get($uid);
Done ✅

2020-11-30 08:10 UTC, skjnldsv approved these changes

2020-11-30 13:49 UTC, ChristophWurst approved these changes

2020-11-30 14:09 UTC, MorrisJobke commented
CI says no ... let me remove the DI part again as it causes a lot of trouble at other places :/

2020-12-22 07:46 UTC, ChristophWurst commented
tech dept and not fully one -> let's move to 22

2021-03-30 19:48 UTC, rullzer commented
Kill or continue?

2021-04-01 16:52 UTC, MorrisJobke commented
> Kill or continue?

🔥 but the code and not the PR ... let me rebase and 🙏

2021-04-01 17:26 UTC, splitt3r requested changes

2021-04-01 17:26 UTC, splitt3r commented on apps/files_sharing/lib/SharedStorage.php
> +		$this->cache = new \OCA\Fwiles_Sharing\Cache(
```suggestion
		$this->cache = new \OCA\Files_Sharing\Cache(
```

2021-04-01 20:45 UTC, MorrisJobke commented on apps/files_sharing/lib/SharedStorage.php
> +		$this->cache = new \OCA\Fwiles_Sharing\Cache(
🙈 Thank you so much @splitt3r .... it's late already 🙈

2021-04-01 20:48 UTC, MorrisJobke commented
Rebased.

2021-04-05 11:57 UTC, splitt3r approved these changes

2021-04-28 13:06 UTC, J0WI commented
PHPUnit is not happy

2021-06-16 11:40 UTC, blizzz commented
@MorrisJobke could you check the tests?

2021-06-17 08:31 UTC, MorrisJobke commented
> @MorrisJobke could you check the tests?

Let's see if the latest change fixes it.

2021-06-17 16:17 UTC, merged