App password command
nextcloud/server pull request #24317
Opened 2020-11-23 22:18 UTC by SMillerDev

Add a command to generate app passwords. This will make it a lot easier for app developers to do full end-to-end tests and hopefully it'll also benefit some users.

I don't know much about the server code, so please point to other things you guys need in this PR.

2020-12-22 13:20 UTC, SMillerDev commented
@nextcloud/server-triage maybe?
 ![crickets](https://media.giphy.com/media/l2R013mIf1ZXdvoyI/giphy.gif)

2020-12-22 13:34 UTC, rullzer requested changes

2020-12-22 13:34 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> +			$code = $this->random->generate(128, ISecureRandom::CHAR_UPPER . ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS);
So this is not actually an app password but also creates an OAuth2 token?
Why is that? I think that should really be in the oauth app separatly.

2020-12-22 13:43 UTC, SMillerDev commented on core/Command/User/AddAppPassword.php
> +			$code = $this->random->generate(128, ISecureRandom::CHAR_UPPER . ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS);
That's probably because I'm not entirely sure where the app password is generated so I took the wrong code. I tried to make it only generate an app password, but it's hard to figure out where that is done currently in NC. 

Should I get rid of this part? Do you have a filename/line where the actual app passwords are currently generated so I can use that?

2020-12-22 14:39 UTC, skjnldsv commented
@SMillerDev please set development status label and milestone :)
That helps us knowing what to do with this pr.

2020-12-22 14:42 UTC, SMillerDev commented
It's that documented somewhere? Without the comment I would never have known.

2020-12-23 10:49 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> +			$code = $this->random->generate(128, ISecureRandom::CHAR_UPPER . ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS);
Ah no you don't need that part then. Let me see if I can push to your branch

2020-12-23 11:50 UTC, rullzer approved these changes
Fine by me for a first version!

2020-12-23 12:59 UTC, SMillerDev commented
Thanks for the help @rullzer . Do I need to do anything here?

2020-12-23 13:25 UTC, ChristophWurst commented
> It's that documented somewhere? Without the comment I would never have known.

https://docs.nextcloud.com/server/20/developer_manual/getting_started/codingguidelines.html#labels

2020-12-23 13:26 UTC, ChristophWurst commented on core/Command/User/AddAppPassword.php
> +				'read password from environment variable OC_PASS'
why not NC_PASS?

2020-12-23 13:27 UTC, ChristophWurst commented on core/Command/User/AddAppPassword.php
> +		$token = $this->random->generate(72, ISecureRandom::CHAR_UPPER.ISecureRandom::CHAR_LOWER.ISecureRandom::CHAR_DIGITS);
can we make the magic number 72 a constant somewhere so we use the same length in all code paths?

2020-12-23 15:10 UTC, SMillerDev commented on core/Command/User/AddAppPassword.php
> +				'read password from environment variable OC_PASS'
Because for account creation it's oc_pass, I could do both?

2020-12-23 15:29 UTC, SMillerDev commented on core/Command/User/AddAppPassword.php
> +		$token = $this->random->generate(72, ISecureRandom::CHAR_UPPER.ISecureRandom::CHAR_LOWER.ISecureRandom::CHAR_DIGITS);
I'm not sure why it's 72 to begin with, @rullzer any comment on this?

2020-12-28 10:32 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> +		$token = $this->random->generate(72, ISecureRandom::CHAR_UPPER.ISecureRandom::CHAR_LOWER.ISecureRandom::CHAR_DIGITS);
72 was done because of the bcrypt limit of 72 bytes

2020-12-30 12:29 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> +				'read password from environment variable OC_PASS'
Leave for now I guess

2020-12-30 12:32 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
This doesn't seem right

2020-12-30 12:53 UTC, SMillerDev commented on core/Command/User/AddAppPassword.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
How about this then?
```suggestion
 * @copyright Copyright (c) 2020, NextCloud, Inc.
```

2021-01-05 09:58 UTC, rullzer requested changes

2021-01-05 09:58 UTC, rullzer commented on core/Command/User/AddAppPassword.php
> +								AccessTokenMapper $accessTokenMapper) {
So just gave this another view.
This one can go right? As we are not using it now. Together with the property, include etc.

2021-01-05 09:58 UTC, rullzer commented on core/register_command.php
> +	$application->add(new OC\Core\Command\User\AddAppPassword(\OC::$server->getUserManager(), \OC::$server->get(\OC\Authentication\Token\IProvider::class), \OC::$server->get(\OCP\Security\ISecureRandom:
This one also need adujusting again then

2021-01-05 12:10 UTC, SMillerDev commented
Pushed the fix and resolved a deprecation notice in the command registration

2021-01-06 13:38 UTC, MorrisJobke approved these changes
Tested and works 👍

2021-01-06 14:35 UTC, merged