Make S3 MultipartUpload Concurrency Configurable - Address S3 Timeouts
nextcloud/server pull request #24330
Opened 2020-11-24 10:06 UTC by J-Light

Created a new service with the latest Nextcloud docker image with S3 backend. File 4GB and larger fail to upload. Issue discussed #20519 and in forums 

https://help.nextcloud.com/t/an-exception-occurred-while-uploading-parts-to-a-multipart-upload/47163
https://help.nextcloud.com/t/primary-storage-s3-files-large-more-than-4gb/59797
https://help.nextcloud.com/t/s3-primary-object-store-large-uploads-2gb-fail-with-exception-and-timeout-using-webdav-or-nextcloud-client-or-web-ui/67185
https://help.nextcloud.com/t/s3-random-storage-problem-on-large-files/72897

No concrete solution proposed. 

The Socket Timeout error by trial and error is down to Concurrency level used by AWS's S3 SDK. The default is 5 and it may be stressing the container or server environments. 

In my case setting this to a value of 3 explicitly resolved the issue of Socket Timeouts. 

The PR make this configurable with a default value the value used as default in the SDK. 

New to project to suggestions welcome.

2020-11-24 11:22 UTC, acsfer commented
Interesting. I wonder if setting it to `1` could not solve issues like https://github.com/nextcloud/server/issues/21958 or https://github.com/nextcloud/server/pull/23781 and kind-of simulate a non-multipart upload... 🤔

2020-11-24 11:31 UTC, FlorentCoppint approved these changes

2020-11-25 06:01 UTC, J-Light commented
@acsfer I think the idea is good. Since setting it to 3 I when from 100% failure to about 20 to 30% failure. I am going to keep this for a few more days to assess. Setting to 1 would also be a good default, its something I will be testing the coming days.

2021-01-11 04:46 UTC, J-Light commented
Any progress on this front? Upgraded my instance and noticed errors again and remembered I needed to include this.

2021-08-18 12:07 UTC, skjnldsv commented
/rebase

2021-08-18 14:21 UTC, juliushaertl requested changes

2021-08-18 14:21 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +			'concurrency' => $this->config->getSystemValue('objectstore.arguments.concurrency', 5),
This should rather be passed as a param of the existing object store configuration which are parsed in the S3ConnectionTrait, similar to how it is done for the uploadPartSize already:

https://github.com/nextcloud/server/blob/b73d275b37ecf0bd79e5c52b9bd51146fe371b3e/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L79

2022-07-28 09:56 UTC, PVince81 commented
@juliushaertl does this clash somehow with the [chunked upload PR](https://github.com/nextcloud/server/pull/27034) or is still relevant and useful in its own way ?

2022-08-24 20:47 UTC, sebastiansterk commented
Yes I agree as well. It is still relevant.

2023-03-06 14:02 UTC, timstoop commented
I'd like to point out that this is still relevant in 25.0.4.

2023-04-04 15:18 UTC, frittentheke commented
With https://github.com/nextcloud/server/pull/27034 merged, what does this PR then still improve / fix?

2023-04-04 15:34 UTC, juliushaertl commented
See https://github.com/nextcloud/server/pull/24330#issuecomment-1198366285

2024-02-27 13:18 UTC, skjnldsv commented
@J-Light would you be alright to address [Julius's comment](https://github.com/nextcloud/server/pull/24330#discussion_r691287226) :)

If not, I will close this PR for inactivity unless someone else is willing to take over :pray:

2024-02-27 14:09 UTC, frittentheke commented
> Still relevant I'd say, for cases where chunked upload is not working, e.g. using a random webdav client or Windows webdav mount.

@juliushaertl can you explain which components communicate via which protocol and where your proposed setting for concurrency come into play?

From what you said I imagine a WebDAV client uploading a large file to Nextcloud. That then uploads this large file to an S3 storage and uses multipart due to the file size to do so.

2024-02-28 02:00 UTC, J-Light commented
Not actively using or working on this anymore in large part due to this issue. Have moved to OCIS. Happy to close this given how old this is.

2024-03-21 18:01 UTC, closed without merging