Wrap display_name similarly to email to allow changes via occ
nextcloud/server pull request #24348
Opened 2020-11-24 14:57 UTC by noiob

This patch allows setting the display name via `occ user:setting <user> settings display_name`.

## Limitations

- as far as I can tell a new user won't necessarily have a display name set, so the property can't be read from this tool
- the `--delete` option won't work as the display name can't be set to an empty string, I've decided to just return an error

2020-11-25 05:47 UTC, skjnldsv commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
I don't think we use this key anywhere else :thinking:

2020-11-25 09:48 UTC, noiob commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
hm, maybe it should be `displayname`?

2020-11-25 11:14 UTC, ChristophWurst commented on core/Command/User/Setting.php
> +							$user->setDisplayName($input->getArgument('value'));
returns `false` if the user back-end doesn't support the operation. You might want to `return 1` as well here.

2020-11-25 11:16 UTC, ChristophWurst commented
But where would we ever use this value?

2020-11-25 11:49 UTC, noiob commented on core/Command/User/Setting.php
> +							$user->setDisplayName($input->getArgument('value'));
thanks, added some info as well

2020-11-25 11:55 UTC, noiob commented
@ChristophWurst I don't quite understand, this is just to be able to set and get the display name via occ, for example when the frontend isn't available? It seemed to me like it was better to use a config value rather than loading the value from the user every time, just like it's being done for email

2020-11-25 13:00 UTC, skjnldsv commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
No I mean, is this even needed?
The current displayname change was already implemented in the backend, right? Only the console command was missing?

2020-11-25 14:04 UTC, noiob commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
this line is needed so it can be read back by the occ command, check `setEMailAddress` in the same file

2020-11-25 14:19 UTC, skjnldsv commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
I don't understand, you added the setUserValue with the display_name key.
But you don't use it anywhere else and it's not used by any existing code either.

Does it not work when you remove this line?

2020-11-25 14:34 UTC, noiob commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
It's used by the code in `Setting.php`, when reading the `display_name` setting. See "Get a single setting" and "Read user settings" in [the documentation](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#user-commands) for an example

- ["Get a single setting"](https://github.com/nextcloud/server/blob/45b0491346df38ad6057cb4ecda67f9c9c8f90bd/core/Command/User/Setting.php#L174)
- ["Read user settings"](https://github.com/nextcloud/server/blob/45b0491346df38ad6057cb4ecda67f9c9c8f90bd/core/Command/User/Setting.php#L241)

It would be possible to read directly from the user but it would require special cases in `Setting.php` which is already quite convoluted

2020-11-30 09:45 UTC, ChristophWurst commented
> @ChristophWurst I don't quite understand, this is just to be able to set and get the display name via occ, for example when the frontend isn't available? It seemed to me like it was better to use a config value rather than loading the value from the user every time, just like it's being done for email

Same concern as raised by @skjnldsv and @juliushaertl in https://github.com/nextcloud/server/pull/24348#discussion_r530407269.

You set this new config value for the user. But as far as I can tell that's not read anywhere but the CLI command.

2020-11-30 09:48 UTC, noiob commented
@ChristophWurst Yes, that is correct, I'm trying to tell you that it's on purpose, because hard-coding access to the user property would add a lot of special cases in `Setting.php`

2020-11-30 10:06 UTC, skjnldsv commented on lib/private/User/User.php
> +				$this->config->setUserValue($this->uid, 'settings', 'display_name', $displayName);
Yes, but it doesn't work like that.
Emails are stored as user settings, but not displayname. You cannot just add a config out of nowhere that will not be used anywhere in the code but to output the OCC command :)

You need to have a dedicated condition for the displayname as this is stored in the users table and only accessible through the [`$user->getDisplayName()`](https://github.com/nextcloud/server/blob/9bf76d2bad08b2e8c8e6bab9f3e514515fb89058/lib/private/User/User.php#L130) method :wink:

2020-12-01 12:04 UTC, rullzer requested changes
Good stuff.

Could you address my comments. And squash your commits into one? Then we can get this in!

2020-12-01 12:04 UTC, rullzer commented on core/Command/User/Setting.php
> +								if ($user->getDisplayName() == $input->getArgument('value')) {
```suggestion
								if ($user->getDisplayName() === $input->getArgument('value')) {
```

2020-12-01 16:24 UTC, noiob commented
@rullzer fyi, I addressed your comments and squashed my commit, it just seems like Github didn't like the way I did it

2020-12-01 16:52 UTC, ChristophWurst approved these changes

2020-12-01 16:53 UTC, ChristophWurst commented
> Build was killed

FYI our sysadmins are doing some  maintenance on Drone right now, hence CI doesn't run

2020-12-01 21:42 UTC, MorrisJobke approved these changes
Code looks good 👍

2020-12-01 21:43 UTC, geep33 commented
Ya

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Morris Jobke <notifications@github.com>
Sent: Tuesday, December 1, 2020 2:42:49 PM
To: nextcloud/server <server@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [nextcloud/server] Wrap display_name similarly to email to allow changes via occ (#24348)


@MorrisJobke approved this pull request.

Code looks good 👍

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/nextcloud/server/pull/24348#pullrequestreview-542320037>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARULPN7WLQNUM5S3BH3YDZLSSVPNTANCNFSM4UA72VQQ>.

2020-12-01 21:43 UTC, MorrisJobke commented
> FYI our sysadmins are doing some maintenance on Drone right now, hence CI doesn't run

@noiob Do you mind to rebase again or just push again to this branch, so that CI is triggered again. Our CI system got an overhaul and existing jobs weren't migrated. So a retriggering is needed from the code side. Sorry for the inconvenience.

2020-12-02 12:58 UTC, noiob commented
@MorrisJobke I triggered the CI again but it's still failing, and I don't think it's my fault

2020-12-02 14:05 UTC, MorrisJobke commented
> @MorrisJobke I triggered the CI again but it's still failing, and I don't think it's my fault

Correct - this is an unreliable test :(

2020-12-02 14:05 UTC, merged