Migrate LDAP's install.php to a repair step
nextcloud/server pull request #24406
Opened 2020-11-27 06:47 UTC by ChristophWurst

Didn't test because I never reset my dev instance. So let's see if CI catches anything :)

2020-11-27 08:00 UTC, ChristophWurst commented
>  There was 1 failure:
> 
> 1) Test\InfoXmlTest::testClasses with data set #17 ('user_ldap')
> Asserting install-migration "OCA\User_LDAP\Migration\SetDefaultProvider" exists
> Failed asserting that false is true.
> 
> /home/runner/work/server/server/tests/lib/InfoXmlTest.php:119

:roll_eyes:

2020-11-27 09:10 UTC, juliushaertl approved these changes
Tested and works with settings up a fresh instance and connecting ldap. Config values are properly set

2020-11-27 10:58 UTC, nickvergessen approved these changes
:elephant:

2020-11-27 14:02 UTC, blizzz requested changes

2020-11-27 14:02 UTC, blizzz commented on apps/user_ldap/lib/Migration/SetDefaultProvider.php
> +
this can be dropped actually since not ignoring them is the default behaviour

2020-11-27 14:13 UTC, ChristophWurst commented on apps/user_ldap/lib/Migration/SetDefaultProvider.php
> +
:+1: done, and inlined the helper method as it's now only used from one place

2020-11-27 14:23 UTC, blizzz approved these changes
tested, works as advertized :four_leaf_clover:

2020-11-30 08:57 UTC, MorrisJobke commented
retriggered CI because there were some issues over the weekend.

2020-11-30 10:22 UTC, merged