Bump icewind/streams from 0.7.1 to 0.7.2
nextcloud/server pull request #24533
Opened 2020-12-03 10:04 UTC by ChristophWurst

For https://github.com/nextcloud/3rdparty/pull/470.

2020-12-03 10:15 UTC, MorrisJobke approved these changes

2020-12-03 10:16 UTC, MorrisJobke commented
Psalm is not happy :(

2020-12-03 10:30 UTC, ChristophWurst commented
Over method overwrites like ``\OC\Files\Stream\Encryption::wrapSource`` have to be adjusted. In this specific example we use a ``$mode`` param that got dropped.

@icewind1991 could you take care? I think you understand the changes best :v:

2020-12-04 08:13 UTC, rullzer commented
I think a lot of the psalm warnings here come because there are also a lot of fixes. So I think we actually had most in there already they are just slighyly modified.

The changes in streams itself are minimal. @MorrisJobke can you rerun psalm? Then I vote to just get it in.

2020-12-04 08:13 UTC, rullzer approved these changes

2020-12-04 08:31 UTC, ChristophWurst commented
> Then I vote to just get it in.

`` /home/runner/work/server/server/lib/private/Files/Stream/Encryption.php:201:69:error - MoreSpecificImplementedParamType: Argument 4 of OC\Files\Stream\Encryption::wrapSource has the more specific type 'string', expecting 'null|string' as defined by Icewind\Streams\WrapperHandler::wrapSource``

we should fix those

2020-12-04 08:41 UTC, MorrisJobke commented
> we should fix those

Yep - Ping me again once they are in.

2020-12-07 12:31 UTC, nickvergessen commented
Can we move this forward? It's currently blocking #24486  which needs a bump of 3rdparty to get the phonenumber lib in.

Or we can also unmerge the stream update until tests are ready, but we should get master unblocked soon!

2020-12-07 13:02 UTC, nickvergessen commented
Revert is in https://github.com/nextcloud/3rdparty/pull/546

2020-12-18 12:30 UTC, ChristophWurst commented
oudated

2020-12-18 12:31 UTC, ChristophWurst commented
let's keep it open for 22. but we need to redo the bump in 3rdparty

2020-12-23 18:25 UTC, rullzer approved these changes
sure

2020-12-28 09:02 UTC, ChristophWurst commented
Neat, CI passes.

2020-12-28 10:44 UTC, juliushaertl approved these changes

2020-12-29 07:54 UTC, rullzer requested changes

2020-12-29 07:54 UTC, rullzer commented on apps/workflowengine/lib/Check/FileMimeType.php
> +		if ($this->storage->file_exists($this->path) && is_string($path = $this->storage->getLocalFile($this->path))) {
I'm not a fan of this check and assign in 1 go. It doesn't make thing more clear IMO

2020-12-29 07:54 UTC, rullzer commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +				if ($preserveMtime && is_int($mtime = $sourceStorage->filemtime($sourceInternalPath))) {
same here

2020-12-29 07:54 UTC, rullzer commented on lib/private/Files/Stream/Encryption.php
> +	protected static function wrapSource($source, $context = [], $protocol = null, $class = null, $mode = 'r+') {
why was this needed?

2020-12-29 07:56 UTC, ChristophWurst commented on lib/private/Files/Stream/Encryption.php
> +	protected static function wrapSource($source, $context = [], $protocol = null, $class = null, $mode = 'r+') {
because it overwrites `\Icewind\Streams\WrapperHandler::wrapSource` and that method signature changed

2020-12-29 07:59 UTC, ChristophWurst commented on apps/workflowengine/lib/Check/FileMimeType.php
> +		if ($this->storage->file_exists($this->path) && is_string($path = $this->storage->getLocalFile($this->path))) {
:+1: reverted to old code

2020-12-29 07:59 UTC, ChristophWurst commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +				if ($preserveMtime && is_int($mtime = $sourceStorage->filemtime($sourceInternalPath))) {
:+1: reverted to old code

2020-12-29 10:23 UTC, rullzer approved these changes

2020-12-29 10:24 UTC, merged