Ldapi unix socket support
nextcloud/server pull request #24574
Opened 2020-12-06 12:31 UTC by zenlord

This branch adds ldapi:/// connection support to the user_ldap app (both backend code and frontend code)

2020-12-06 12:32 UTC, zenlord commented
Resolved #24497

2020-12-09 12:45 UTC, zenlord commented
@blizzz Sorry for my noob question, but is there anything I should or could do to proceed this PR? The codesniffer check fails, but not on a line that I have manipulated. If from now on, it's all out of my hands, that's fine with me ;)

2020-12-09 13:22 UTC, zenlord commented
Fixes #24497

2021-01-10 08:32 UTC, zenlord commented
@blizzz ping?

2021-04-11 09:52 UTC, zenlord commented
@blizzz just wanted to confirm that these patches still work on version 21.0.1.

2021-11-20 16:31 UTC, zenlord commented
@blizzz Patches still work with newest version (22.2.3)

2022-03-13 15:15 UTC, zenlord commented
@blizzz Patches still apply cleanly with version 22.2.5. System is running smoothly since the PR was created.

@jospoortvliet  Last ping from my end. First time collaborator to an open source project, and very disappointing to see absolutely noone cares.

2022-03-13 16:06 UTC, szaimen commented
/rebase

2022-03-14 09:15 UTC, come-nc reviewed
See comments.
Please also run `composer run cs:fix` for code style.

Does this only work with openldap?

2022-03-14 09:15 UTC, come-nc commented on apps/user_ldap/lib/Wizard.php
> +			$portSettings[] = ['port' => '', 'tls' => false];
This should only happen if ldapi is used to avoid surprises

2022-03-14 09:15 UTC, come-nc commented on apps/user_ldap/lib/Connection.php
> +		if(substr($this->configuration->ldapHost, 0, strlen('ldapi://')) != 'ldapi://') {
This test is done in a lot of places, could you add a method on configuration that contains this test?
```suggestion
		if ($this->configuration->usesLdapi()) {
```

2022-03-14 09:18 UTC, come-nc commented on apps/user_ldap/lib/Wizard.php
> +		// LDAPI unix socket support: why are tls values wrong here?
tls toggle here means starttls. Ports 7636 and 636 are for ldaps which does not use starttls.
Ports 7389 and 389 are first tried with starttls and then without if that fails.

2022-03-15 06:47 UTC, zenlord commented on apps/user_ldap/lib/Wizard.php
> +		// LDAPI unix socket support: why are tls values wrong here?
OK, removed those comments

2022-03-15 06:57 UTC, zenlord commented on apps/user_ldap/lib/Wizard.php
> +			$portSettings[] = ['port' => '', 'tls' => false];
Agree - will use the same test as used elsewhere in the file: (substr($this->configuration->ldapHost, 0, strlen('ldapi://')) != 'ldapi://')

2022-04-07 15:07 UTC, szaimen commented
@zenlord any update here? :)

2022-09-02 15:35 UTC, zenlord commented
@szaimen @blizzz @come-nc Finally got around resolving the comments made by @come-nc . Instead of doing a rebase, I have simply created a new clone, applied the original commits as a patch, made the code changes and then force-pushed the result to my fork. I hope this is acceptable, because going through all the merges required from rebasing against Nextcloud 20-something got dull very quickly :/

2022-09-02 15:38 UTC, zenlord commented on apps/user_ldap/lib/Wizard.php
> +			$portSettings[] = ['port' => '', 'tls' => false];
Done: https://github.com/nextcloud/server/pull/24574/commits/b13e69e4ebe87231e073492f177fdb04ed3e746a

2022-09-02 15:39 UTC, zenlord commented on apps/user_ldap/lib/Connection.php
> +		if(substr($this->configuration->ldapHost, 0, strlen('ldapi://')) != 'ldapi://') {
Done: https://github.com/nextcloud/server/pull/24574/commits/343ff3f37aed6f9ae147ea3d45c9843e23a84fd9

2022-09-02 15:40 UTC, szaimen commented
@zenlord thanks for the update! Can you please make sure to resolve DCO? See https://github.com/nextcloud/server/pull/24574/checks?check_run_id=8159237124 for some steps.

Thanks for your efforts!

2022-09-02 15:51 UTC, zenlord commented
@szaimen I think I was successful in doing that, and have pushed another commit to solve an issue raised by one of the checks

2022-09-02 15:53 UTC, szaimen commented
> @szaimen I think I was successful in doing that, and have pushed another commit to solve an issue raised by one of the checks

DCO looks good to me now, thanks!

2022-09-05 07:15 UTC, come-nc requested changes
Please change usesLdapi() return type to bool and adapt if checks accordingly.
Also, remove the config var uses_ldapi unless I missed something and it is actually used?

2022-09-05 07:15 UTC, come-nc commented on apps/user_ldap/lib/Wizard.php
> +		if ($this->configuration->usesLdapi() === 0) {
```suggestion
		if (!$this->configuration->usesLdapi()) {
```

2022-09-05 07:15 UTC, come-nc commented on apps/user_ldap/lib/Wizard.php
> +		if ($this->configuration->usesLdapi() === 0) {
```suggestion
		if (!$this->configuration->usesLdapi()) {
```

2022-09-05 07:38 UTC, zenlord commented on apps/user_ldap/lib/Configuration.php
> +		'usesLdapi' => null,
Deleted it again - my mistake

2022-09-05 07:39 UTC, zenlord commented
@come-nc All comments have been addressed - appreciate the hand-holding :/

2022-09-05 09:37 UTC, come-nc requested changes

2022-09-05 09:37 UTC, come-nc commented on apps/user_ldap/lib/Configuration.php
> +			'uses_ldapi' => 0,
```suggestion
```

2022-09-05 09:47 UTC, come-nc commented
@zenlord Apart from above comment, could you squash everything into one commit and fix DCO?
Most likely something like `git rebase -i HEAD~16` and replace all pick but the first one by "s".
And then git commit -s --amend to add the sign-off-by and please DCO bot. Then `git push --force-with-lease`.
You may want to push to a backup branch before just in case.

2022-09-05 10:59 UTC, zenlord commented
@come-nc I did perform the commands you shared, but had to manually solve some merge conflicts. I'm not sure whether my latest commit is now the single commit you've asked for?

2022-09-05 11:00 UTC, zenlord commented on apps/user_ldap/lib/Configuration.php
> +			'uses_ldapi' => 0,
Done

2022-09-09 14:54 UTC, zenlord commented
@come-nc Looks like this one is better: single commit and DCO is not complaining.

2022-09-12 07:39 UTC, come-nc approved these changes

2022-09-12 08:21 UTC, come-nc commented
25 is feature freezed so this will go into 26, waiting for 25 to branch out before merging into master.

Thank you for this contribution @zenlord !

2022-09-12 08:22 UTC, come-nc commented
(actually needs 1 more review so I put back to review label)

2022-10-20 13:06 UTC, CarlSchwan approved these changes

2022-10-20 13:07 UTC, CarlSchwan reviewed
Need a rebase (last one hopefully)

2022-11-23 15:00 UTC, szaimen commented
/rebase

2022-12-08 16:25 UTC, merged