Dcache worm
nextcloud/server pull request #24596
Opened 2020-12-07 17:31 UTC by kofemann

2021-02-11 09:50 UTC, rullzer commented
@kofemann as far I know you have been running with this in production for some time now right?
Any reason this PR is still a draft?

2021-02-12 14:21 UTC, kofemann commented
@rullzer We would like to run some tests to validate that other things (like apps) are not broken. Do you have a testsuite that we can run locally?

2022-01-28 10:38 UTC, PVince81 commented
the code looks fine to me in general, I'm hoping that the extra unlink will not cause much extra overhead, but we're talking about local storage anyway so should be fine. @icewind1991 thoughts ?

2022-01-28 10:38 UTC, PVince81 commented
@kofemann please rebase and resolve the conflicts

2022-01-28 10:39 UTC, PVince81 commented
regarding tests, at least the ones with regular storage, are already running in our CI so if something is broken we'll likely see this immediately

2022-01-28 14:36 UTC, kofemann commented
@PVince81 Thanks for the update. Actually, since 2 weeks we run this code with nextcloud 22.2.3 in a production. Up to now we haven't seen any issues.

2022-01-28 14:38 UTC, PVince81 commented
> @PVince81 Thanks for the update. Actually, since 2 weeks we run this code with nextcloud 22.2.3 in a production. Up to now we haven't seen any issues.

that's great to hear! I took the liberty to click "ready for review"

2022-02-07 15:24 UTC, PVince81 commented
some strange errors in multiple places:
```
1) Test\Cache\FileCacheTest::testGarbageCollectLeaveRecentKeys
InvalidArgumentException: Username is invalid because files already exist for this user
```

I'm wondering if the change in this PR somehow interferes with test cleanup, but I can't see how

2022-02-07 16:32 UTC, kofemann commented
This is obviously something that I have to look at. Is it possible to run the test manually?

2022-02-07 16:59 UTC, PVince81 commented
> This is obviously something that I have to look at. Is it possible to run the test manually?

see https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html#bootstrapping-nextcloud

this is how I usually test locally:
`./autotest.sh sqlite tests/lib/Cache/FileCacheTest.php`

2022-02-09 13:13 UTC, icewind1991 commented
I would expect a filesystem to be smart enough to handle the "truncate an existing file and write to it" case, but I'm fine adding some logic for it.

It should only `unlink` if the file already exists though.

2022-02-15 16:29 UTC, icewind1991 requested changes
Please add a check if the file exists before deleting it

2022-03-31 09:02 UTC, kofemann commented
I have added a coifing option control this behavior. A check before unlink will issue unnecessary stat call.

2022-04-13 14:36 UTC, CarlSchwan commented on lib/private/Files/Storage/Local.php
> +		if ($mode === 'w' && $this->unlinkOnTruncate) {
Mode can probably also be 'wb' and 'wb+'. This probably need to be handled too

2022-04-14 13:57 UTC, kofemann commented on lib/private/Files/Storage/Local.php
> +		if ($mode === 'w' && $this->unlinkOnTruncate) {
This probably makes sense. However, this is not what we have tested over past several months. I will have a look anyway...

2022-08-25 09:40 UTC, kofemann commented
rebased on top of current master

2022-09-16 08:51 UTC, PVince81 approved these changes
:+1:

2022-09-16 08:55 UTC, PVince81 commented
@kofemann the code looks fine. please sign off your commits, see https://github.com/nextcloud/server/pull/24596/checks?check_run_id=8012932504

I'll try and find a second reviewer to get this in. thanks!

2022-09-16 08:56 UTC, CarlSchwan approved these changes

2022-09-16 08:56 UTC, CarlSchwan commented on lib/private/Files/Storage/Local.php
> +	protected $unlinkOnTruncate;
```suggestion
	protected bool $unlinkOnTruncate;
```

2022-09-16 09:02 UTC, kofemann commented on lib/private/Files/Storage/Local.php
> +	protected $unlinkOnTruncate;
This looks reasonable, however other local variables don't explicitly specify the type.

2022-09-16 09:03 UTC, CarlSchwan commented on lib/private/Files/Storage/Local.php
> +	protected $unlinkOnTruncate;
Yeah, it is old code, but for new code it's nicer to have typing so that the static analysis can be more powerful

2022-09-16 09:10 UTC, kofemann commented on lib/private/Files/Storage/Local.php
> +	protected $unlinkOnTruncate;
👍🏼 fixed

2022-09-16 12:39 UTC, merged