Allow to force rename a conflicting calendar
nextcloud/server pull request #24604
Opened 2020-12-08 09:24 UTC by skjnldsv

Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

2020-12-08 09:25 UTC, skjnldsv commented
/backport to stable20

2020-12-08 09:29 UTC, skjnldsv commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
Looks good to me, but might be a bad thing to do?

2020-12-08 09:31 UTC, wiswedel commented
@skjnldsv 
Please don't forget to document the new parameter in https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst.

2020-12-08 09:38 UTC, skjnldsv commented
> @skjnldsv
> Please don't forget to document the new parameter in [nextcloud/documentation@`master`/admin_manual/configuration_server/occ_command.rst](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst?rgh-link-date=2020-12-08T09%3A31%3A32Z).

https://github.com/nextcloud/documentation/pull/5590

2020-12-08 12:31 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
The uri is also in the share table, the calendarobjects table, the calendarchanges table, .... or are those different values?

2020-12-08 13:36 UTC, skjnldsv commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
Ah, I should also have the --force check here too I guess?
Or I can unify and put everything under the same --force flag?

2020-12-08 16:04 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
well uri is (unique resource identifier). so you need to update all those tables with the same value? Otherwise the data can not be linked together anymore?

2020-12-09 07:07 UTC, skjnldsv commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
Yes, this is why the force option was here initially, we don't support this, we drop all shares when specified.

2020-12-09 08:13 UTC, tcitworld commented on apps/dav/lib/Command/MoveCalendar.php
> +		return null !== $this->calDav->getCalendarByUri(self::URI_USERS . $userDestination, $name);
I just thought that `calendars` and `calendarsubscriptions` might collide, maybe check into `calendarsubscriptions` as well?

2020-12-09 08:13 UTC, tcitworld commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
> The uri is also in the share table, the calendarobjects table, the calendarchanges table, .... or are those different values?

There's no uri in `dav_shares`, just `principaluri`. The `uri` fields in `calendarobjects` and `calendarchanges` refer to the `ics` files and are not related.
Shares refers to calendars by their resource ID, not by their URI. We don't drop shares most of the time, we only do it (with `--force`) when the new owner for the calendar is not a member of the group the calendar was previously shared with, or when the new owner was already a sharee of the calendar.
However, sharees need to update their calendar links (since the shared calendar uri contains the name of the owner, see the bottom of the `MoveCalendar.php` command).

2020-12-09 11:42 UTC, skjnldsv commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
@tcitworld I think I'll unify this into --force then.
That way we drop the shares at the same time, we're on the safe side. It also make sense in the "force move" wording of this command, if we force, better rename as well if conflicts?

You're good with that? :)

2020-12-09 13:14 UTC, tcitworld commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
Seems good to me, yes

2020-12-09 16:18 UTC, skjnldsv commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			->set('uri', $query->createNamedParameter($newUriName ?: $uriName))
Done

2020-12-09 18:22 UTC, tcitworld requested changes, later dismissed

2020-12-09 18:22 UTC, tcitworld commented on apps/dav/lib/Command/MoveCalendar.php
> +			->addOption('force', 'f', InputOption::VALUE_NONE, "Force the migration by removing existing shares and renaming calendars in case of conflicts")
lacks a `;`

2020-12-11 08:26 UTC, juliushaertl approved these changes
Tested and works :+1:

2020-12-11 10:15 UTC, skjnldsv commented
Test failure unrelated

2020-12-15 07:48 UTC, skjnldsv commented
Ping everyone!

2020-12-22 07:32 UTC, ChristophWurst approved these changes

2020-12-22 07:33 UTC, merged