adding a ShareDeletedEvent
nextcloud/server pull request #24610
Opened 2020-12-08 22:00 UTC by daita

seems it was missing since the Great Migration. should includes parent IShare, and children

2020-12-15 08:21 UTC, rullzer requested changes

2020-12-15 08:21 UTC, rullzer commented on lib/private/Share20/Manager.php
> +		$this->dispatcher->dispatchTyped(new Share\Events\ShareDeletedEvent($share, $deletedShares));
Mmm I'm wonering if we should not just make the event simpler. And just have the share.
And then also emit an event for all children that get deleted.

2020-12-23 10:10 UTC, rullzer approved these changes

2020-12-23 10:10 UTC, rullzer commented on lib/private/Share20/Manager.php
> +		$this->dispatcher->dispatchTyped(new Share\Events\ShareDeletedEvent($share, $deletedShares));
Cahnged that

2020-12-23 10:40 UTC, ChristophWurst approved these changes

2020-12-23 11:45 UTC, merged