personal settings: handle read-only parameters correctly
nextcloud/server pull request #2468
Opened 2016-12-02 11:38 UTC by schiessle

handle read-only parameters correctly, e.g. with a external user back-end like LDAP the users is not able to change their display name or email address.

You can test it by setting 'displayNameChangeSupport' to false:
https://github.com/nextcloud/server/blob/master/settings/personal.php#L169

2016-12-02 11:44 UTC, ChristophWurst requested changes
use quotes for attributes

2016-12-02 11:44 UTC, ChristophWurst commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
Did you mean 'class="hidden'"? 😉

2016-12-02 11:44 UTC, ChristophWurst commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
same

2016-12-02 11:53 UTC, schiessle commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
don't know why, but when I tested it the quotes where added automatically, when I wrote 'class="hidden"' the result was 'class=""hidden""' and didn't worked.

2016-12-02 11:55 UTC, schiessle commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
same answer as above... tested with Firefox and Chromium

2016-12-02 13:37 UTC, MorrisJobke commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
Umm ... that's why you should not escape it 🙈 

Use `print_unescaped` because it's actual HTML

2016-12-02 13:37 UTC, MorrisJobke commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
See answer above

2016-12-02 13:44 UTC, schiessle commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { p('class=hidden'); } ?>
changed

2016-12-02 15:21 UTC, MorrisJobke commented
- [ ] BUG: Changing the phone number or address in this read only mode (I did this with an LDAP user) the settings aren't stored. I get following response (and no feedback in the UI - only that the setting is gone after a refresh of the page): 

```json
{"status":"error","data":{"message":"E-Mail-Adresse konnte nicht ge\u00e4ndert werden"}}
```

2016-12-02 15:37 UTC, schiessle commented
I have a idea why this happens... Independent from this PR, I will have a look.

2016-12-02 15:45 UTC, MorrisJobke commented
> I have a idea why this happens... Independent from this PR, I will have a look.

Okay. Then this is good to go 👍

2016-12-03 10:14 UTC, MorrisJobke commented
@LukasReschke @nickvergessen Mind to review this one?

2016-12-05 08:19 UTC, ChristophWurst commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { print_unescaped('class="hidden"'); } ?>
On a side note: displayname is the only input we don't have a placeholder for.

2016-12-05 08:22 UTC, ChristophWurst commented on settings/templates/personal.php
>  			<em><?php p($l->t('For password recovery and notifications')); ?></em>
Papercut: let's hide this information if the email cannot be changed ;-)

2016-12-05 08:23 UTC, ChristophWurst commented
Aside from my nitpicking it works 👍

2016-12-05 08:59 UTC, schiessle commented on settings/templates/personal.php
> +				<?php if(!$_['displayNameChangeSupported']) { print_unescaped('class="hidden"'); } ?>
because we will always show something... getDisplayName falls back to the uid if no display name is set. So display name can never be empty

2016-12-05 09:00 UTC, schiessle commented on settings/templates/personal.php
>  			<em><?php p($l->t('For password recovery and notifications')); ?></em>
good point, will add this

2016-12-05 09:12 UTC, ChristophWurst approved these changes

2016-12-05 11:15 UTC, merged