Resolves #24699, Support ES2 and ECS instance providers for S3 buckets
nextcloud/server pull request #24700
Opened 2020-12-14 18:00 UTC by Imajie

Switch out specifically called out env and instanceProvider CredentialProvider for the defaultProvider, this adds support for running nextcloud in ECS instances and using the task role to provide permissions for S3 access.

New order for fallback is defined in [the AWS docs](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#defaultprovider-provider)

> It first attempts to load credentials from environment variables, then from an .ini file (an .aws/credentials file first, followed by an .aws/config file), and then from an instance profile (EcsCredentials first, followed by Ec2 metadata).

2020-12-14 20:02 UTC, cuppett commented
When we made the first change, I read the doc reference as saying "instance profile contains 2 paths, ECS then instance profile". Looking deeper at [the code](https://github.com/aws/aws-sdk-php/blob/5b59db8d5d3d5ce1e93b8c4de5908437cc2eb40f/src/Credentials/CredentialProvider.php#L105-L127), it appears not the case; they are separate and discrete.

However, this also has a side effect of picking up the user's $HOME directory. For whatever user ID the Nextcloud instance is running as, before ECS and instance profile, it would interrogate $HOME/.aws/credentials. Originally, I didn't want to introduce that wrinkle. It seemed too implicit & nuanced for shared hosting accounts, or folks running the docker container on a random machine under a random UID. Do we want to pick that up as well? I'm not sure.... 

If we do not want the $HOME director ini-file behavior, changing the code to something similar would have the desired effect to add the ECS case to the existing ENV and instance profile:

```php
$provider = CredentialProvider::memoize(
    CredentialProvider::chain(
        $this->paramCredentialProvider(),
        CredentialProvider::env(),
        CredentialProvider::ecsCredentials(),
        CredentialProvider::instanceProfile()
    )
);
```

It may make sense not to inject it unless it passes the same condition in the defaultProvider factory:

```php
!empty(getenv(EcsCredentialProvider::ENV_URI))
```

Happy to comment/review more if folks have thoughts or comments on this.

2020-12-14 20:33 UTC, Imajie commented
I changed it to use defaultProvider so if new methods were added by AWS it would presumably automatically pick them up, but if it's preferred I can update to specifically call out the order instead so there's more control of what's used.

2020-12-14 21:06 UTC, cuppett commented
> I changed it to use defaultProvider so if new methods were added by AWS it would presumably automatically pick them up, but if it's preferred I can update to specifically call out the order instead so there's more control of what's used.

It's definitely the way to go if we don't have reservations specifically about the user $HOME directory method being "in there".

2020-12-14 21:07 UTC, cuppett reviewed
When we made the first change, I read the doc reference as saying "instance profile contains 2 paths, ECS then instance profile". Looking deeper at [the code](https://github.com/aws/aws-sdk-php/blob/5b59db8d5d3d5ce1e93b8c4de5908437cc2eb40f/src/Credentials/CredentialProvider.php#L105-L127), it appears not the case; they are separate and discrete.

However, this also has a side effect of picking up the user's $HOME directory. For whatever user ID the Nextcloud instance is running as, before ECS and instance profile, it would interrogate $HOME/.aws/credentials. Originally, I didn't want to introduce that wrinkle. It seemed too implicit & nuanced for shared hosting accounts, or folks running the docker container on a random machine under a random UID. Do we want to pick that up as well? I'm not sure.... 

If we do not want the $HOME directory ini-file behavior, changing the code to something similar would have the desired effect to add the ECS case to the existing ENV and instance profile:

```php
$provider = CredentialProvider::memoize(
    CredentialProvider::chain(
        $this->paramCredentialProvider(),
        CredentialProvider::env(),
        CredentialProvider::ecsCredentials(),
        CredentialProvider::instanceProfile()
    )
);
```

It may make sense not to inject it unless it passes the same condition in the defaultProvider factory:

```php
!empty(getenv(EcsCredentialProvider::ENV_URI))
```

Happy to comment/review more if folks have thoughts or comments on this.

2020-12-14 21:45 UTC, cuppett requested changes
In reviewing [the code](https://github.com/aws/aws-sdk-php/blob/5b59db8d5d3d5ce1e93b8c4de5908437cc2eb40f/src/Credentials/CredentialProvider.php#L89-L103), we can actually exclude the ini files with a simpler change:

```php
$provider = CredentialProvider::memoize(
    CredentialProvider::chain(
        $this->paramCredentialProvider(),
        CredentialProvider::defaultProvider(['use_aws_shared_config_files' => false])
    )
);
```

(Double check my syntax.)

This should accomplish what we both were after, picking up any/all desirable future methods (including the current one), but not the $HOME directory ones.

2020-12-14 21:51 UTC, Imajie commented
I saw that option too, but it looks like a [little further down](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L109) it loads the same file from $HOME as a process credential provider, so it doesn't seem like that would fully exclude $HOME from being included

2020-12-14 22:10 UTC, cuppett commented
> I saw that option too, but it looks like a [little further down](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L109) it loads the same file from $HOME as a process credential provider, so it doesn't seem like that would fully exclude $HOME from being included

I'm not sure the $HOME is an issue. I'm just not familiar enough with all the different deployment models. If not a big issue, we can just have/take the original commit.

If we go further down this route (trying to avoid the $HOME directory), we should make the function look a bit more like defaultProvider and build up the explicit chain, adding param to the beginning, but including all the others (in order) and excluding those two ini/process calls. We'll want to pick up the WebIdentity one. Similar to the ECS method, that's the one which can use the [AWS IAM pod identity work](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) on EKS/OpenShift.

2020-12-14 22:36 UTC, cuppett commented
I've submitted a change to the aws-sdk-php. It seems awkward to re-use the same files for this other shell method without considering that config variable. Also, I'm rusty, but in Java, I didn't see the same sequence or a discrete process provider. Let's give it a minute to see what they say:

https://github.com/aws/aws-sdk-php/pull/2172

2020-12-15 00:25 UTC, cuppett commented
> Also, I'm rusty, but in Java, I didn't see the same sequence or a discrete process provider.

I found it.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L46-L52

The profile types are all lumped together:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/ProfilesConfigFile.java#L207-L216

And then, there's a toggle between ECS and instance profile "either/or" versus "both":

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.java#L58-L64

My first AWS SDK PR could take a minute, but I wouldn't mind chasing it with a couple more to make it behave more like the Java SDK. There's also some missing functionality for ECS full URI or an Authorization header in the PHP SDK.

Until then, we can do the most complete thing here with something like this:

```php
$provider = CredentialProvider::memoize(
	CredentialProvider::chain(
		$this->paramCredentialProvider(),
		CredentialProvider::env(),
		CredentialProvider::assumeRoleWithWebIdentityCredentialProvider(),
		!empty(getenv(EcsCredentialProvider::ENV_URI))
			? CredentialProvider::ecsCredentials()
			: CredentialProvider::instanceProfile()
	)
);
```

2020-12-15 18:49 UTC, cuppett commented
> I've submitted a change to the aws-sdk-php. It seems awkward to re-use the same files for this other shell method without considering that config variable. Also, I'm rusty, but in Java, I didn't see the same sequence or a discrete process provider. Let's give it a minute to see what they say:
> 
> [aws/aws-sdk-php#2172](https://github.com/aws/aws-sdk-php/pull/2172)

I've added commits which will allow this work:

```php
CredentialProvider::defaultProvider(['use_aws_shared_config_files' => false])
```

But until (if) that merges and then we have a bump in 3rdparty to pick it up, we'll need the full thing:

```php
$provider = CredentialProvider::memoize(
	CredentialProvider::chain(
		$this->paramCredentialProvider(),
		CredentialProvider::env(),
		CredentialProvider::assumeRoleWithWebIdentityCredentialProvider(),
		!empty(getenv(EcsCredentialProvider::ENV_URI))
			? CredentialProvider::ecsCredentials()
			: CredentialProvider::instanceProfile()
	)
);
```

2020-12-15 21:55 UTC, cuppett requested changes
Looks good, just double check the syntax (can't tell with the markup, but looks like a comma missing).

2020-12-15 21:55 UTC, cuppett commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +				CredentialProvider::assumeRoleWithWebIdentityCredentialProvider()
Does this line need a comma at the end?

2020-12-15 22:30 UTC, cuppett commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +				CredentialProvider::assumeRoleWithWebIdentityCredentialProvider()
Yeah, it popped in the automated tests: 
PHP Parse error:  syntax error, unexpected '!', expecting ')' in ./lib/private/Files/ObjectStore/S3ConnectionTrait.php on line 109

2020-12-16 00:14 UTC, cuppett approved these changes
Looks good. With any luck, next time we visit this file, we'll be able to use the simpler provider with the config option. Thanks!

2020-12-16 12:53 UTC, Imajie commented
You're welcome!

Looks like the test failures are all marked with "Unreliable test" is there a way to rerun that stage of the build?

2020-12-17 19:29 UTC, cuppett commented
AWS SDK change has merged. Once we bump to 3.171.1, we can switch over to:

```php
CredentialProvider::defaultProvider(['use_aws_shared_config_files' => false])
```
I'm guessing in the NC22 release.

2021-01-18 19:46 UTC, cuppett commented
@kesselb @rullzer Am I able to merge this or something else going on? I was thinking somebody would snarf this up in one of the betas.

2021-02-02 20:48 UTC, rullzer approved these changes

2021-02-02 20:48 UTC, merged

2021-02-02 20:48 UTC, rullzer commented
/backport to stable21