user_ldap : fix exception when LDAP user is a numeirc string like "1234"
nextcloud/server pull request #24748
Opened 2020-12-17 16:07 UTC by multiOTP

user_ldap : fix the userExistsOnLDAP($user) function, because PHP crashes if the LDAP user name is a numeric string like "1234"

2020-12-17 19:21 UTC, kesselb commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
You can merge the elseif with if as they do the same.

2020-12-17 19:50 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
the method requests string or a User instance. It would be good to figure out where the int  is coming from and fix this.

2020-12-17 21:43 UTC, multiOTP commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
In my case, I have LDAP usernames like "1234" and "5678", and as PHP is a weak typed language, the $user parameter, which is "1234", is seen as an int instead as a string.
It's just the real world :-) I found a customer where usernames are identification numbers !

2020-12-17 21:46 UTC, multiOTP commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
> You can merge the elseif with if as they do the same.

You're absolutely right, I've separated the two conditions during the debugging process, but changin only the line 294 will also fix the issue.

2020-12-18 02:06 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
> > the method requests string or a User instance. It would be good to figure out where the int is coming from and fix this.
> 
> In my case, I have LDAP usernames like "1234" and "5678", and as PHP is a weak typed language, the $user parameter, which is "1234", is seen as an int instead as a string.
> It's just the real world :-) I found a customer where LDAP usernames are identification numbers !

It is, but if you cast a number to string, it stays a string. So somewhere along the code the id is fetched and treated as int, not string. It should be casted to string. We type hint new methods, and when touching older ones we also do add type hints. That an int is ending up there should be taken care of earlier.

2020-12-18 08:19 UTC, multiOTP commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
> > > the method requests string or a User instance. It would be good to figure out where the int is coming from and fix this.
> > 
> > 
> > In my case, I have LDAP usernames like "1234" and "5678", and as PHP is a weak typed language, the $user parameter, which is "1234", is seen as an int instead as a string.
> > It's just the real world :-) I found a customer where LDAP usernames are identification numbers !
> 
> It is, but if you cast a number to string, it stays a string. So somewhere along the code the id is fetched and treated as int, not string. It should be casted to string. We type hint new methods, and when touching older ones we also do add type hints. That an int is ending up there should be taken care of earlier.

You're right blizzz, but even the fact to store an object or a string in the same parameter is quite strange. For sure, the $user is not casted when calling the userExistsOnLDAP function, but I let the development team of the user_ldap to check that, it will be easier for them to quickly found where they are calling the userExistsOnLDAP function:
Regards, and thanks for your feedback.

2020-12-27 11:38 UTC, kesselb requested changes

2020-12-27 11:38 UTC, kesselb commented on apps/user_ldap/lib/User_LDAP.php
> +		if (!is_object($user)) {
https://3v4l.org/UKVEs

is_object is a bad choice here.

2020-12-27 11:49 UTC, kesselb commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
```
if (is_int($user)) {
	\OC::$server->getLogger()->logException(new \RuntimeException('UserId is integer: ' + $user));
	$user = (string)$user;
}
```

Should log a stack trace to figure out which path calls the method with an integer.

2020-12-27 11:51 UTC, multiOTP commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
Ok I will do that to give you a feedback

2021-04-28 13:10 UTC, J0WI commented on apps/user_ldap/lib/User_LDAP.php
> +		if (!is_object($user)) {
Can we just move this after the `is_null()` condition below?

2023-03-14 17:13 UTC, max-nextcloud commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
@multiOTP Have you been able to gather a stack trace? Would be good to get to the root cause of this. I'd be happy to help with looking into this once we have a trace.

2023-03-14 17:14 UTC, max-nextcloud commented
@multiOTP would you be up to pick this up again? Anyone else wants to take this over and try to gather a stack trace as explained above?

2023-05-12 09:37 UTC, multiOTP commented on apps/user_ldap/lib/User_LDAP.php
> +		elseif (is_numeric($user)) {
> Have you been able to gather a stack trace? Would be good to get to the root cause of this. I'd be happy to help with looking into this once we have a trace.

Hello,
I've added stack tracing in version 25.0.6, and there is no more issue detection. it seems that the $user type is now casted correctly. I will re-open a ticket if I found something weird, but the root cause of this ticket has been fixed somewhere in a release.
Regards,

2024-02-27 13:20 UTC, skjnldsv commented
> @multiOTP would you be up to pick this up again? Anyone else wants to take this over and try to gather a stack trace as explained above?

I guess not :cry: 

@multiOTP 
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open and solve the various conflicts.

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2024-02-27 13:20 UTC, closed without merging