Allow SSO authentication to provide a user secret
nextcloud/server pull request #24837
Opened 2020-12-24 10:19 UTC by immerda

Allow Authentication\IApacheBackend to return a per-user secret. This
secret is used in lieu of a passwort to initialize the session.
This allows an SSO backend to support per-user encrypted files.

2021-05-26 08:27 UTC, MorrisJobke approved these changes
Makes sense to pass it here. 👍

2021-06-02 16:01 UTC, blizzz commented
moving to 23 since we are in feature freeze. CI is unhappy also.

2021-07-01 16:37 UTC, artonge commented
@immerda Can you rebase and try to make CI happy ?

2021-07-21 16:04 UTC, juliushaertl requested changes

2021-07-21 16:04 UTC, juliushaertl commented on lib/public/Authentication/IApacheBackend.php
> +	 * @since 21.0.0
```suggestion
	 * @since 23.0.0
```

2021-07-21 16:04 UTC, juliushaertl commented on lib/private/legacy/OC_User.php
> +				$pw = $secret === null ? '' : $secret;
```suggestion
				$password = $secret === null ? '' : $secret;
```

2021-07-21 16:04 UTC, juliushaertl commented on lib/private/legacy/OC_User.php
> +						'password' => $pw,
```suggestion
						'password' => $password,
```

2021-07-21 16:04 UTC, juliushaertl commented on lib/public/Authentication/IApacheBackend.php
> +	 * @since 21.0.0
Actually we could move this to a separate interface like `IProvideUserSecretBackend` to avoid breaking existing implementations on new Nextcloud releases. With that we could also avoid the null return value and check in OC_User and do a check there if the interface is implemented by the backend.

2021-07-21 18:43 UTC, MichaIng commented on lib/public/Authentication/IApacheBackend.php
> +	 * @since 21.0.0
To avoid confusion, the PR has been redone [here](https://github.com/nextcloud/server/pull/27929) as immerda seems to be not maintaining it here. The version string has been adjusted already, I'll do the same with pw => password. About the new interface, you need to tell me more in detail how to do that, over there, I guess this means a new script?

2021-07-22 07:21 UTC, immerda commented
Thanks @juliushaertl for the review and @MichaIng for pushing this further. The train is moving, so let's all move with it to #27929

2021-07-22 07:21 UTC, closed without merging

2021-07-22 07:22 UTC, juliushaertl commented on lib/public/Authentication/IApacheBackend.php
> +	 * @since 21.0.0
Ah indeed, I already wondered, because I though I already reviewed something similar but was not seeing my comments on this one :+1: