avoid fread on directories and unencrypted files
nextcloud/server pull request #24966
Opened 2021-01-05 10:15 UTC by jknockaert

Reworking the logic in order to first check the filecache and only then reading the fileheader.
This in order to solve #21578.

2021-01-05 10:17 UTC, jknockaert commented
@nextcloud/encryption Pls review. Also check the discussion of the issue I posted in #21578. That said, I didn't yet find out why this function is evaluated very often for keyfiles.

2021-01-05 10:44 UTC, jknockaert commented
Signed-off-by: Jasper Knockaert jasper@knockaert.nl

2021-01-05 11:50 UTC, jknockaert commented
Can anyone help with the testing? It is my understanding that in the tests the call to the cache was never evaluated, so I guess that should somewhere be caught now that it comes first.

2021-01-05 22:16 UTC, jknockaert commented
OK, with all checks passed now I think this one is ready for review. As for the `getHeader` function I'm pretty sure I fully understand the code and I think my implementation is fine; but still then I don't have a full overview of all use cases of this function so I may miss out on a corner case. As for the tests I somehow got it working; not sure though if I fully understand what I did here. I couldn't do any meaningful benchmarking so I can't say much on the impact of the changes introduced. I wouldn't expect it to matter much.

2021-01-07 15:51 UTC, axheli commented
@jknockaert I applied the below fix  and im not getting the errors anymore  

![image](https://user-images.githubusercontent.com/59488153/103913093-c810e400-50cd-11eb-8de3-4837990e7624.png)

2021-01-16 10:17 UTC, RedKage commented
I dont know what this is doing, nor am I a nextcloud maintainer.
However I think that IF can be simplified and be made more readable with

```
    if (!isset($result[Util::HEADER_ENCRYPTION_MODULE_KEY] && (!empty($result) || $exists)) {
        $result[Util::HEADER_ENCRYPTION_MODULE_KEY] = 'OC_DEFAULT_MODULE';
    }
```

2021-01-16 14:42 UTC, jknockaert commented
@RedKage Thanks; fixed.

2021-01-16 14:42 UTC, jknockaert commented
@ChristophWurst Any suggestion who to invite for a review?

2021-01-26 09:07 UTC, jknockaert commented
@nextcloud/encryption Can anyone review? This is a fairly minor patch that fixes errors with php7.4. It would be good to have it included in the next point release of nextcloud.

2021-01-27 20:43 UTC, moverduinsecov commented
Have applied changes manually, and so far everything looks fine.

2021-02-22 15:23 UTC, jknockaert commented
Can anyone review? This is a minor (and straightforward) patch that fixes errors with php7.4. It would be good to have it included in the next point release of nextcloud.

2021-02-23 20:04 UTC, axheli commented
@ChristophWurst Can you please have someone review this?

2021-03-03 15:21 UTC, axheli commented
@rullzer anyway we can get this approved? Please :)

2021-03-18 18:37 UTC, axheli commented
So who's going to approve this?

2021-03-19 16:42 UTC, icewind1991 approved these changes
I believe that this should be fine, but I haven't looked into the encryption logic for a long time

2021-04-03 12:39 UTC, jknockaert commented
Can anyone review pls? This PR was submitted three months ago and is limited to a reordering of logic in a single function.

2021-04-03 12:51 UTC, axheli commented
This is crazy we’re just asking for review and approval why dose it take so so long for a simple review.

2021-04-03 16:28 UTC, talesam commented
I saw that it has not yet been added to the nextcloud, how do I add it manually?

2021-04-03 18:23 UTC, vitormattos requested changes

2021-04-03 18:23 UTC, vitormattos commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
Does it make sense to do something if the file doesn't exist?
it seems to me that here it should be `if (!$exists)` and have a `return [];`
This simplifies the code below

2021-04-03 18:25 UTC, vitormattos commented
@icewind1991 

> I believe that this should be fine, but I haven't looked into the encryption logic for a long time

If the test passes, what's wrong? :-)

2021-04-03 18:29 UTC, jknockaert commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
I didn't change anything in this respect. This is pretty low level code, so I prefer not to change it too much. It's hard to predict the context of all the different cases in which this code is invoked.

2021-04-03 18:31 UTC, vitormattos commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
Without tests covering the scenarios it is difficult to review.

2021-04-03 18:35 UTC, jknockaert commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
Unfortunately the tests are not covering every use scenario, far from it. Otherwise the php error on deleting a folder would have been caught by a test. Unfortunately I only know the lower-level part of the encryption code in Nextcloud; I have little experience with the filesystem code.

2021-04-03 23:19 UTC, vitormattos commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
The test you changed just made the test not break, there are no new data to cover possible scenarios for the change.

The test method testGetHeaderAddLegacyModule has a @dataProvider with a list of possible scenarios and outputs (dataTestGetHeaderAddLegacyModule).

It is good practice to include the scenario that covers the identified bug and the scenarios that cover the changes you made to the code.

On the comment I made about the return [] when the file does not exist, looking at the data from the test scenarios, the only scenario that has $exists = false returns an empty array. It does not make sense that the file does not exist and the method returns a header for a file that does not exist.

2021-04-04 07:43 UTC, jknockaert commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
As for the testing you're correct, but I don't know how to write such a new test. It should take into account that only php 7.4 fails. And I am not sure what the filecache for a folder should be (I have little understanding of the filecache specification).
As for the `return []` comment I prefer to stick to the current implementation. There seems to be a case where `$realFile` does not exist but `$path` does; see e.g. https://github.com/nextcloud/server/blob/40fde94b4d019f5c1914225d5be6854241abeb9c/lib/private/Files/Storage/Wrapper/Encryption.php#L398
Also in `getHeaderSize()` it is implemented such that `$path` is updated if `$realFile` exists. I am not sure which scenario is covered here. It may be something to do with versioning, or with files on an external (mounted) storage. Perhaps we should leave it for a separate PR if there is a need to fix this.

2021-04-05 02:27 UTC, vitormattos commented on lib/private/Files/Storage/Wrapper/Encryption.php
>  			$path = $realFile;
I saw the tests better and also didn't identify new data scenarios.

2021-04-05 02:31 UTC, vitormattos approved these changes
It seems to be ok, there seems to be no need to create new test scenarios.

2021-04-06 11:45 UTC, merged

2021-04-06 11:48 UTC, jknockaert commented
Thanks @vitormattos and @icewind1991 for the reviews.

2021-04-08 16:12 UTC, axheli commented
@jknockaert 
@vitormattos 

Just updated to 20.0.9 and got this error dose this have anything to do with this ?

Error: Declaration of OC\Files\Stream\Encryption::wrapSource($source, $context, $protocol, $class, $mode = 'r+') should be compatible with Icewind\Streams\WrapperHandler::wrapSource($source, $context = Array, $protocol = NULL, $class = NULL) at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#201



Error: Declaration of OC\Files\Stream\Encryption::loadContext($name) should be compatible with Icewind\Streams\Wrapper::loadContext($name = NULL) at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#224
--

2021-04-08 16:17 UTC, vitormattos commented
It is in the same class but does not seem to be related to this pull request.

Looking at the log quickly, without a thorough analysis, the method changed in this pull request is not in the callstack of the log you posted.

2021-04-08 16:29 UTC, axheli commented
@vitormattos thank you for the quick reply. Im not sure what happen as soon as i update to 20.0.9 even if i open up a file or scroll throw the phones tab log files goes crazy. what do you suggest next for me to do ? 

![image](https://user-images.githubusercontent.com/59488153/114062862-9b4fa280-985d-11eb-817d-731045b88eb2.png)

2021-04-08 16:35 UTC, vitormattos commented
I suggest sending a new pull request solving this problem :)

The solution is already described in the log, it is necessary to implement, check the impacts, review the unit tests to ensure they are ok and send the pull request.

2021-04-08 16:36 UTC, axheli commented
I just did! i tagged you in it so maybe we can have someone look at it quicker :)

2021-04-08 16:39 UTC, vitormattos commented
You have opened an issue. Submit the pull request with the solution. The correction is simple, but it is necessary to check the impacts well.

2021-04-08 17:04 UTC, axheli commented
@vitormattos i would not know the solutions i don't code. maybe @jknockaert knows it but i dont

2021-04-08 17:36 UTC, jknockaert commented
@axheli Pls tag me. I may have time to have a look at it over the weekend.
That said, I think the filesystem code is in some need for a more thorough review and possibly rewrite.

2021-04-08 17:41 UTC, vitormattos commented
> I just did! i tagged you in it so maybe we can have someone look at it quicker :)

@jknockaert #26464

2021-04-08 17:44 UTC, axheli commented
@jknockaert Thank you so much :)

2021-05-28 19:48 UTC, andyxheli commented
Still an issue on Nextcloud 21.0.2 @LukasReschke can we please add this fix ?

2021-06-06 17:47 UTC, acsfer commented
/backport to stable21

2021-06-06 17:48 UTC, acsfer commented
/backport to stable20

2021-06-06 17:48 UTC, acsfer commented
/backport to stable19

2021-07-02 19:25 UTC, andyxheli commented
Hello everyone is anybody willing to  add this fix to the Next release 21.0.4 ?