Reply to option for sharebymail Issue #24139
nextcloud/server pull request #24978
Opened 2021-01-05 23:28 UTC by dems54

Should let users decide if anwsers to be sent to their account email, or to nextcloud server email

2021-01-11 21:33 UTC, dems54 commented
For review please : @skjnldsv @rullzer @ChristophWurst @juliushaertl

(I hope this is the right way to ask for reviewers, this is my first PR, many thanks 🙂)

2021-01-12 07:14 UTC, skjnldsv commented
Hey! Thanks :)
Can you rebase and squash your commits into one?

2021-01-12 08:09 UTC, juliushaertl commented on apps/sharebymail/lib/Settings/SettingsManager.php
> +	private $replyToInitiator = 'yes';
```suggestion
	private $replyToInitiatorDefault = 'yes';
```

2021-01-12 08:10 UTC, juliushaertl commented on apps/sharebymail/lib/Settings/SettingsManager.php
> +		return $replyToInitiator === 'yes';
```suggestion
		return $this->config->getAppValue('sharebymail', 'replyToInitiator', $this->replyToInitiatorDefault);
```

2021-01-12 08:12 UTC, juliushaertl approved these changes
Small nitpicks, otherwise fine by me :+1:

2021-01-12 09:39 UTC, dems54 commented
> Hey! Thanks :)
> Can you rebase and squash your commits into one?

Rebase and squash are OK. 
But I don't know why Static Code Analysis is now NOK ? It doesn't seem to relate to my commit...

2021-01-12 09:41 UTC, dems54 commented
> Small nitpicks, otherwise fine by me 👍

Good suggestions. 
This is my first PR : who must validte your propositions ?

2021-01-12 10:31 UTC, skjnldsv commented
> But I don't know why Static Code Analysis is now NOK ? It doesn't seem to relate to my commit...

No, it doesn't indeed. Just ignore

2021-01-12 10:31 UTC, skjnldsv approved these changes

2021-01-27 19:24 UTC, rullzer requested changes

2021-01-27 19:24 UTC, rullzer commented on apps/sharebymail/lib/Settings/SettingsManager.php
> +		return $this->config->getAppValue('sharebymail', 'replyToInitiator', $this->replyToInitiatorDefault);
getAppValue returns a string. But you say bool. Either you need to compare here (and thus return a bool). Or change the function signature.

2021-01-27 21:42 UTC, dems54 commented
Possible to merge this PR in NC20 or NC21 ?

2021-02-18 23:09 UTC, dems54 commented
@rullzer it's ok for you ?

2021-02-19 07:20 UTC, merged

2021-02-19 07:21 UTC, skjnldsv commented
NC22