Add setup check to verify that the used DB version is still supported…
nextcloud/server pull request #25016
Opened 2021-01-07 15:30 UTC by MorrisJobke

… in the next major release

2021-01-07 15:32 UTC, MorrisJobke commented
See https://github.com/nextcloud/documentation/pull/5895

2021-01-07 15:33 UTC, MorrisJobke commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +			case MySQL80Platform::class: # extends MySQL57Platform
I left all the platforms in here to have the full overview (except DB2 or MSSQLServer as we don't support them at all)

2021-01-07 17:35 UTC, nickvergessen requested changes

2021-01-07 17:35 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +						$this->description = $this->l10n->t('MySQL version "%s" is used. Nextcloud 21 will no longer support this version and requires MariaDB 8 or higher.', $row['Value']);
```suggestion
						$this->description = $this->l10n->t('MySQL version "%s" is used. Nextcloud 21 will no longer support this version and requires MySQL 8 or higher.', $row['Value']);
```

2021-01-07 18:42 UTC, ChristophWurst commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +		$this->check();
I'm not a fan of running actual class logic from the constructor. can we do this in `run`?

2021-01-07 19:36 UTC, MorrisJobke commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +		$this->check();
Then it depends on the fact that `run()` is called first, before fetching description for example.

2021-01-07 19:38 UTC, ChristophWurst commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +		$this->check();
Yes

2021-01-07 19:53 UTC, MorrisJobke commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +		$this->check();
Fixed

2021-01-07 21:03 UTC, MorrisJobke commented
Ready for review :)

2021-01-07 21:03 UTC, MorrisJobke commented
/backport to stable20

2021-01-08 07:28 UTC, rullzer requested changes

2021-01-08 07:28 UTC, rullzer commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +					if (version_compare($version, '10.4', '<')) {
```suggestion
					if (version_compare($version, '10.2', '<')) {
```

2021-01-08 12:23 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +					if (version_compare($version, '10.4', '<')) {
But 10.4 is the mysql8 compatible version?
Ref https://github.com/nextcloud/server/blob/stable16/lib/private/Setup/MySQL.php#L48-L56

2021-01-08 12:36 UTC, MorrisJobke commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +					if (version_compare($version, '10.4', '<')) {
Our docs say, that 10.2 works and CI runs against 10.1 🙈

2021-01-08 12:39 UTC, MorrisJobke commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +					if (version_compare($version, '10.4', '<')) {
I changed it to 10.2 for now. We can raise it later again, okay?

2021-01-11 08:54 UTC, MorrisJobke commented
@rullzer @ChristophWurst Ready for review :)

2021-01-11 10:17 UTC, rullzer commented on apps/settings/lib/SetupChecks/SupportedDatabase.php
> +					if (version_compare($version, '10.4', '<')) {
10.2 is still supported so yeah :)

2021-01-11 10:18 UTC, rullzer approved these changes
Looks good.
But didn't test

2021-01-11 12:57 UTC, ChristophWurst approved these changes

2021-01-11 13:21 UTC, merged