Fixes #24450 by making the icon grey only on hover and white otherwise.
nextcloud/server pull request #25023
Opened 2021-01-08 01:21 UTC by RafaOP

As described in #24450, the icon looks off in grey but, if just changed to white, it would be a white icon on white background on hover, which I solved by making the icon grey only on hover and otherwise white.

2021-01-19 21:39 UTC, MorrisJobke commented
cc @nextcloud/designers

2021-01-19 21:39 UTC, MorrisJobke commented
/backport to stable20

2021-02-02 20:46 UTC, rullzer commented
/backport to stable21

2021-04-28 15:56 UTC, MorrisJobke commented
I would like to get feedback from @nextcloud/designers on this one

2021-04-28 16:11 UTC, skjnldsv commented on core/css/icons.scss
> +.icon-filetype-text,
Hey! We have a dedicated function to automatically change the colours of svg.
You can use the same `@include icon-color('text', 'filetypes', $color-white, 1, true);` like we do here for example: https://github.com/nextcloud/server/blob/4f90766ba314171bbfc78d1e988307c50633e7f3/core/css/icons.scss#L266-L269

2021-04-28 16:12 UTC, skjnldsv commented on core/css/icons.scss
> +.icon-filetype-text,
That way you do not have to ship another white svg.

2021-04-28 18:47 UTC, jancborchardt approved these changes
:+1: design-wise, thanks for the fix @RafaOP! :)

2021-04-29 11:07 UTC, skjnldsv requested changes
see https://github.com/nextcloud/server/pull/25023#discussion_r622332522

2021-05-11 12:11 UTC, MorrisJobke commented on core/img/filetypes/text-white.svg
> +<?xml version="1.0" standalone="no"?>
This file is then also not needed anymore, right?

2021-05-17 07:34 UTC, MorrisJobke commented on core/img/filetypes/text-white.svg
> +<?xml version="1.0" standalone="no"?>
Yep - just remove it. You could also use `--amend` to add changes to your last commit and then force push via `git push --force-with-lease` (this will not overwrite if there were changes on the server inbetween your last pull and your push).

2021-05-30 08:17 UTC, skjnldsv commented on apps/theming/css/theming.scss
> +.icon-file, .icon-filetype-text, .icon-file-white:hover, .icon-file-white:focus {
@juliushaertl please confirm.
If so, it's good for me

2021-05-30 08:17 UTC, skjnldsv approved these changes
Ok for me if @juliushaertl is ok

2021-06-16 11:44 UTC, blizzz commented
CI is unhappy

2021-07-05 09:30 UTC, skjnldsv commented
/rebase

2021-07-05 11:45 UTC, skjnldsv commented
Please rebase @RafaOP

2021-07-14 13:39 UTC, juliushaertl requested changes
Some comments in regards to the theming, which would be good to adjust before getting this in. :wink:

2021-07-14 13:39 UTC, juliushaertl commented on apps/theming/css/theming.scss
> +.icon-file, .icon-filetype-text, .icon-file-white:hover, .icon-file-white:focus {
This does not seem to be the right place for just the focus styling. This should only apply for the button so it should rather be part of settings.scss if even needed as the button should have a focus/hover feedback already.

2021-07-14 13:39 UTC, juliushaertl commented on core/css/icons.scss
> +
`-white` is not ideal as the button will have a primary color adapted to the theming, so whenever there is a bright theme used the white fixed does not fit anymore. I'd suggest something like this:

```suggestion
.icon-file-primary,
.icon-filetype-primary {
	@include icon-color('text', 'filetypes', $color-primary-text, 1, true);
}

```

2023-03-07 19:18 UTC, blizzz commented
closing for inactivity, does not fit to current code base either

2023-03-07 19:18 UTC, closed without merging