File templates
nextcloud/server pull request #25090
Opened 2021-01-12 10:36 UTC by juliushaertl

- [x] API endpoint for fetching list of available template
- [x] API endpoint for creating a new file from a template
- [ ] API endpoint for configuring the user template directory
- [ ] Add templates directory to example files @jancborchardt 
- [ ] Create translated "Templates" directory on skeleton file setup

- [ ] Frontend
  - [ ] User template directory settings
  - [ ] Register file create actions for individual template types
  - [ ] Show modal on file creation
  - [ ] Open the file with the default file opener action after creating

## Possible follow up enhancements
- [ ] Check if we can just expose templates through the direct editing API for mobile clients

2021-01-14 10:53 UTC, skjnldsv commented
![Peek 14-01-2021 11-52](https://user-images.githubusercontent.com/14975046/104581590-1179aa00-565f-11eb-9866-a1a93e7f9496.gif)

2021-01-14 13:29 UTC, skjnldsv commented
![Peek 14-01-2021 14-28](https://user-images.githubusercontent.com/14975046/104596848-d8e4cb00-5674-11eb-89a9-c7eb49da7a27.gif)

2021-01-14 13:30 UTC, skjnldsv commented
> * API endpoint for configuring the user template directory

I think that is fine as is, no? Do we need a custom setting to allow users to change the folder name?

2021-01-14 13:48 UTC, juliushaertl commented
> I think that is fine as is, no? Do we need a custom setting to allow users to change the folder name?

I think we should still offer changing the path in case you have your templates somewhere else, but I'd leave that to @jancborchardt to decide.

2021-01-14 17:09 UTC, jancborchardt commented
Yoooo super nice work @juliushaertl! Already looks very good. 2 small pieces of feedback before I look more into the design and templates:
- [ ] Can you move the file name input into the "Pick a template" modal, on the top? Then it would be main heading "New text document" and an input field with "File name …" placeholder and below that "Pick a template".
- [ ] "Empty file" should go first in the list of templates

> I think we should still offer changing the path in case you have your templates somewhere else, but I'd leave that to @jancborchardt to decide.

Yes, probably makes sense to have that in the bottom left settings as "Templates folder". Especially if people just sync their normal folders and on different operating systems they have different naming conventions.

2021-01-15 07:03 UTC, juliushaertl commented
Forwarding all the praise for the nice looking UI to @skjnldsv :clap:

2021-01-15 07:11 UTC, skjnldsv commented
> * [ ]  Can you move the file name input into the "Pick a template" modal, on the top? Then it would be main heading "New text document" and an input field with "File name …" placeholder and below that "Pick a template".

No, that's not how the new file menu was designed.

> * "Empty file" should go first in the list of templates

:+1:

2021-01-26 16:35 UTC, juliushaertl commented
Time to get this in :ping_pong: for reviews

2021-01-27 14:23 UTC, rullzer commented
Found some things (maybe they can be done now or in a followup)

- [ ] For me (so on upgrade) when I set a template folder that options remains. Only upon refresh it goes away.
- [ ] I can't set an existing folder as template folder with the + menu
- [ ] I can't seem to change my template folder

2021-01-27 14:27 UTC, rullzer requested changes
See my comment. I guess some can be moved to follow up tickets some should be fixed here.
But the general concept with text works! Whoohoo

2021-01-27 14:58 UTC, juliushaertl commented
> - [ ] I can't seem to change my template folder

Yep, that was for now an accepted limitation when talking with @jancborchardt You can though still delete your old one and set a new one afterwards, though removing requires a reload because we have no way how we can detect that the folder got lost without doing additional requests.

> - [ ] With the corresponding text branch I get 2 entries to create text documents?

Moving to the text branch, might be just the bundles not being commited there yet.

2021-01-27 15:19 UTC, ChristophWurst commented on apps/files/src/templates.js
> +window.addEventListener('DOMContentLoaded', function() {
edge case and not even 100% sure about it but I think the callback is not run when the DOMContentLoaded fires before this script gets run

2021-01-27 15:26 UTC, ChristophWurst reviewed
some feedback on the OCP changes :)

2021-01-27 15:26 UTC, ChristophWurst commented on lib/public/Files/Template/CreatedFromTemplateEvent.php
> +class CreatedFromTemplateEvent extends Event {
```suggestion
class FileCreatedFromTemplateEvent extends Event {
```

:thinking:

2021-01-27 15:26 UTC, ChristophWurst commented on lib/public/Files/Template/ITemplateManager.php
> +	 * @param string $providerClass
add another line with `@psalm-param class-string<ICustomTemplateProvider>` for static analysis

2021-01-27 15:26 UTC, ChristophWurst commented on lib/public/Files/Template/ITemplateManager.php
> +	public function registerTemplateFileCreator(TemplateFileCreator $templateType): void;
ideally we do this via the register context of the bootstrap mechanism

2021-01-27 15:26 UTC, ChristophWurst commented on lib/public/Files/Template/Template.php
> +class Template implements \JsonSerializable {
final? since all methods are as well

2021-01-27 15:31 UTC, juliushaertl commented on apps/files/src/templates.js
> +window.addEventListener('DOMContentLoaded', function() {
I think that should be fine since we run this non-asynchronously. The same is used for various viewer integrations and I'm not aware that this has shown issues so far.

2021-01-27 17:22 UTC, juliushaertl commented
> some feedback on the OCP changes :)

Thanks a lot, makes all sense. I'll adjust that tomorrow morning.

2021-01-28 11:02 UTC, juliushaertl commented on lib/public/Files/Template/ITemplateManager.php
> +	public function registerTemplateFileCreator(TemplateFileCreator $templateType): void;
Moved to lazy registration as discussed.

2021-01-28 11:02 UTC, juliushaertl commented on lib/public/Files/Template/Template.php
> +	protected $templateType;
I made them private since the class is final now and added type hints.

2021-01-28 12:06 UTC, juliushaertl commented
/compile amend /

2021-01-28 12:08 UTC, ChristophWurst commented on lib/public/Files/Template/ITemplateManager.php
> +	 * @param callable(): TemplateFileCreator $callback A callback which returns the TemplateFileCreator instance to register
nit: ``@psalm-param callable():TemplateFileCreator $callback``

2021-01-28 12:10 UTC, ChristophWurst approved these changes
Code looks good

2021-01-28 12:20 UTC, ChristophWurst approved these changes
Tested with Text and works flawless (once I figured out how it actually works, I expected new entries in the + menu somehow)

:+1: :100: :shipit:

2021-01-28 12:29 UTC, rullzer approved these changes
Whoohoo let's go

2021-01-28 13:02 UTC, juliushaertl commented
Ok, bundles happy after i removed the stupid random files i committed :see_no_evil:

2021-01-28 13:07 UTC, juliushaertl commented
Follow up polishing tasks are in https://github.com/nextcloud/server/issues/25358

2021-01-28 15:17 UTC, merged

2022-06-09 08:10 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
> +				checkFilename: actionSpec.checkFilename
@juliushaertl do you recall why we're actually using this?

2022-06-09 08:29 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +				checkFilename: actionSpec.checkFilename
No I cannot remember anything in that regard 🙈 

Also no other occurrence in my local checkouts, so I'd say this can be dropped.