Add our own DB exception abstraction
nextcloud/server pull request #25091
Opened 2021-01-12 11:29 UTC by ChristophWurst

Right now our API exports the Doctrine/dbal exception. As we've seen
with the dbal 3 upgrade, the leakage of 3rdparty types is problematic as
a dependency update means lots of work in apps, due to the direct
dependency of what Nextcloud ships. This breaks this dependency so that
apps only need to depend on our public API. That API can then be vendor
(db lib) agnostic and we can work around future deprecations/removals in
dbal more easily.

Right now the type of exception thrown is transported as "reason". For
the more popular types of errors we can extend the new exception class
and allow apps to catch specific errors only. Right now they have to
catch-check-rethrow. This is not ideal, but better than the dependnecy
on dbal.

Follow-up to #24948

2021-01-12 11:58 UTC, MorrisJobke approved these changes
Code looks good 👍

2021-01-12 12:01 UTC, nickvergessen commented on lib/private/DB/ConnectionAdapter.php
> +use Doctrine\DBAL\Exception;
something complains on the imports

2021-01-12 12:02 UTC, nickvergessen commented on lib/private/DB/Migrator.php
> +	 * @throws Exception
missing import now that its in OCP?

2021-01-12 12:03 UTC, nickvergessen requested changes
👍🏼 apart of the comment

2021-01-12 13:15 UTC, ChristophWurst commented on lib/private/DB/ConnectionAdapter.php
> +use Doctrine\DBAL\Exception;
there was one unused below

2021-01-12 13:15 UTC, ChristophWurst commented on lib/private/DB/Migrator.php
> +	 * @throws Exception
no, that seems fine

2021-01-12 14:36 UTC, nickvergessen commented on lib/private/DB/Migrator.php
> +	 * @throws Exception
So `Doctrine\DBAL\Exception` is fine, not our exception? But looking this directly works with `\Doctrine\DBAL\Connection` I guess so.

2021-01-12 14:38 UTC, nickvergessen approved these changes
This will hit like a truck 🙈

2021-01-12 15:11 UTC, ChristophWurst commented on lib/private/DB/Migrator.php
> +	 * @throws Exception
Basically I kept it to Doctrine errors internally and only *convert* when they bubble up to the public API.

2021-01-12 15:12 UTC, ChristophWurst commented
> This will hit like a truck see_no_evil

Oh yes. But to be fair not only because of this PR. It will already hit hard since the original doctrine exception vanished. So it's just a matter of which new exception to listen for. And some of the now thrown exceptions were thrown before too. They were just not documented in our abstraction, but very present in the Doctrine signature.

2021-01-12 15:23 UTC, nickvergessen commented
Well all the `UniqueConstraintViolation` and so on still exist and worked (until this PR) Only the catch all didn't

2021-01-12 15:26 UTC, ChristophWurst commented
Right. I hadn't factored that in. But then these special exceptions were never documented to be thrown … :stuck_out_tongue:

2021-01-12 15:29 UTC, MorrisJobke commented
Psalm says no

2021-01-12 15:32 UTC, ChristophWurst commented
> Psalm says no

Look again. It's unrelated.

2021-01-12 15:36 UTC, MorrisJobke commented on lib/private/DB/Connection.php
> +	 * @throws \BadMethodCallException When trying to acquire a second lock*@throws Exception
```suggestion
	 * @throws \BadMethodCallException When trying to acquire a second lock
```

2021-01-12 15:38 UTC, ChristophWurst commented on lib/private/DB/Connection.php
> +	 * @throws \BadMethodCallException When trying to acquire a second lock*@throws Exception
I blame phpstorm

2021-01-12 15:41 UTC, MorrisJobke approved these changes

2021-01-12 19:40 UTC, rullzer commented on lib/public/DB/Exception.php
> +	public const REASON_CONSTRAINT_VIOLATION = 2;
so the plan is first to have this generic and then maybe at a later stage have constraint violation exceptions? Or just document it properly and have the callers check the reason?

2021-01-12 20:35 UTC, ChristophWurst commented on lib/public/DB/Exception.php
> +	public const REASON_CONSTRAINT_VIOLATION = 2;
Yes and yes. The generic way is that the just catch this exception and optonally compare the reason to a constant. And later we can have specific subclasses that can be caught

2021-01-14 11:02 UTC, rullzer approved these changes

2021-01-14 11:27 UTC, merged