extend ILDAPProvider to allow reading arbitrairy ldap attributes for users
nextcloud/server pull request #25128
Opened 2021-01-14 15:51 UTC by icewind1991

For allowing things like #24955 using public interfaces

2021-01-14 22:12 UTC, blizzz requested changes

2021-01-14 22:12 UTC, blizzz commented on lib/public/LDAP/ILDAPProvider.php
> +	public function getLDAPAttribute(string $uid, string $attribute): ?string;
call it `getUserAttribute`, please, to underline it's not about groups. The LDAP part should be clear through context.

2021-01-14 22:12 UTC, blizzz commented on apps/user_ldap/lib/LDAPProvider.php
> +		if (count($value) > 0) {
```suggestion
		if (is_array($value) && count($value) > 0) {
```

`$value` may be  `false`

2021-01-19 15:34 UTC, icewind1991 commented
@blizzz done

2021-01-22 13:28 UTC, MorrisJobke commented on lib/public/LDAP/ILDAPProvider.php
> +	 * @since 22.0.0
```suggestion
	 * @since 21.0.0
```

Let's do it for 21.

2021-01-22 13:28 UTC, MorrisJobke approved these changes
Code looks good, but some tests would be nice.

2021-01-22 13:28 UTC, MorrisJobke commented
/backport to stable20

2021-01-22 13:30 UTC, blizzz approved these changes

2021-01-22 13:31 UTC, merged

2021-01-22 15:15 UTC, MorrisJobke commented
> For allowing things like #24955 using public interfaces

Mind to submit this with the new API?

2021-01-22 15:16 UTC, MorrisJobke commented
> > 
> 
> Mind to submit this with the new API?

cc @blizzz @icewind1991

2021-03-29 12:22 UTC, MorrisJobke commented
> > For allowing things like #24955 using public interfaces
> 
> Mind to submit this with the new API?

@blizzz @icewind1991 Any news here?

2021-03-29 21:58 UTC, blizzz commented
Last was https://github.com/nextcloud/server/pull/25010#issuecomment-756114527

2021-03-31 13:57 UTC, icewind1991 commented
https://github.com/nextcloud/server/pull/26397