Add activity for display name change
nextcloud/server pull request #25148
Opened 2021-01-15 12:12 UTC by MorrisJobke

Looks then like this:

<img width="1188" alt="Bildschirmfoto 2021-01-15 um 13 12 17" src="https://user-images.githubusercontent.com/245432/104726085-4e16d580-5733-11eb-874b-0b15501b660f.png">

2021-01-15 12:28 UTC, nickvergessen commented on apps/settings/lib/Hooks.php
> +				->setSubject($subject, [$actor->getUID()]);
```suggestion
				->setSubject($subject, ['actor' => $actor->getUID()]);
```

It proofed to be better to name parameters. (Also needs adjusting in the provider)

2021-01-15 12:36 UTC, MorrisJobke commented on apps/settings/lib/Hooks.php
> +				->setSubject($subject, [$actor->getUID()]);
Fixed.

2021-01-15 13:15 UTC, nickvergessen approved these changes

2021-01-15 14:30 UTC, blizzz commented
let me see what happens when the name changed on LDAP and got synced down

2021-01-15 14:44 UTC, blizzz commented
> let me see what happens when the name changed on LDAP and got synced down

![Screenshot_20210115_154133](https://user-images.githubusercontent.com/2184312/104740397-31d16380-5748-11eb-884a-2e59be84f221.png)

That ideally should be something like "You display name was updated by the system". We had the same once with the email changed event as well.

2021-01-15 14:44 UTC, blizzz requested changes
https://github.com/nextcloud/server/pull/25148#issuecomment-760982438

2021-01-15 14:56 UTC, nickvergessen commented on apps/settings/lib/Activity/Provider.php
>  			$subject = $this->l->t('Your email address was changed by an administrator');
@blizzz its using the same method as emails :P

2021-01-15 15:34 UTC, blizzz commented on apps/settings/lib/Activity/Provider.php
>  			$subject = $this->l->t('Your email address was changed by an administrator');
It could have been the email notification, not activity. It's some time ago…

2021-01-15 15:42 UTC, blizzz commented on apps/settings/lib/Activity/Provider.php
>  			$subject = $this->l->t('Your email address was changed by an administrator');
Yes, in apps/settings/lib/Hooks.php, cf. https://github.com/nextcloud/server/pull/10687

2021-01-15 16:04 UTC, MorrisJobke commented on apps/settings/lib/Activity/Provider.php
>  			$subject = $this->l->t('Your email address was changed by an administrator');
We can of course also change it to "was changed by system", because the other one is just guessing that it was the admin. But as I don't know a command to change a displayname from the CLI (and even when) - it's fine to state that it was the system. Then we maybe change this for emails as well to that terminology. Okay?

2021-01-15 16:19 UTC, blizzz commented on apps/settings/lib/Activity/Provider.php
>  			$subject = $this->l->t('Your email address was changed by an administrator');
Since you cannot always tell apart whether it was an operator (admin or e.g. their cat) or business logic, it's probably okay to go with `system` only.

2021-01-18 11:12 UTC, blizzz commented
Works now, when it is updated by the system (occ or background job for instance) it is fine.

There is another edge case:

![Screenshot_20210118_115056](https://user-images.githubusercontent.com/2184312/104906011-71d05a80-5983-11eb-8192-f346e7edb9c9.png)

This was during normal operation of that user and due to cold cache. This can happen when the user is included in a search operation by someone else, then it was xyz who changed the displayname. But then the better change would be to not update the displayname on action, but leave it to the background job as well. Let me take care of that.

Users that are being soaked in for the first time do not see the activity. This is better not a race condition :D

Apart of that I expect the ajax-type job does not run with context of the logged in user.

2021-01-19 18:55 UTC, rullzer commented
So we are good to go?

2021-01-19 21:53 UTC, MorrisJobke commented
> So we are good to go?

It has false claims for LDAP users (stuff like "Your displayname was updated by AnotherUser" if the other user searched for something and your entry was updated by the system). I don't like this that much. Also back porting then the big change by @blizzz that changes the fetching of LDAP data is also something I don't fully like. :( 

Let's keep this a bit longer here. Maybe @blizzz has an idea how to nicely work around this situation.

2021-01-29 08:24 UTC, ChristophWurst commented
> Let's keep this a bit longer here. Maybe @blizzz has an idea how to nicely work around this situation.

Moved. We can still backport from 22 if the changes are small.

2021-06-02 16:04 UTC, blizzz commented
and am afraid once more to 23. still work to be done. and conflicts to resolve.

2021-08-09 08:27 UTC, skjnldsv commented
/rebase

2021-08-09 09:12 UTC, skjnldsv commented
Test are green. @blizzz wanna do something on top of that?

2021-08-09 09:20 UTC, blizzz commented
> Test are green. @blizzz wanna do something on top of that?

Don't remember without looking into it again. Went down the prio list a lot previously. I think #25148 was a requirement.

2022-02-07 10:40 UTC, MorrisJobke commented
Tricky to solve and most likely needs a more advanced way of doing it. Therefore I will close this one here. Feel free to take parts of this into a new PR.

2022-02-07 10:40 UTC, closed without merging