Add SGI and TGA preview support
nextcloud/server pull request #25268
Opened 2021-01-22 09:36 UTC by skjnldsv

Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

2021-01-22 09:46 UTC, skjnldsv commented on .mailmap
> +John Molakvoæ <skjnldsv@protonmail.com> John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
I know it's not directly related, but it updated some license header here as well, I guess it's still not that big of a change. Fell free to tell me if that's really stupid :)

2021-01-22 11:00 UTC, rullzer requested changes

2021-01-22 11:00 UTC, rullzer commented on resources/config/mimetypealiases.dist.json
> +	"image/targa": "image/tga"
duplicate

2021-01-22 11:00 UTC, rullzer commented on resources/config/mimetypealiases.dist.json
> +	"image/targa": "image/tga"
Or rather you need the other format right?

2021-01-22 12:03 UTC, skjnldsv commented on resources/config/mimetypealiases.dist.json
> +	"image/targa": "image/tga"
Yes, it's a typo, I meant to alias image/targa to image/tga only

2021-01-22 15:52 UTC, nickvergessen commented on .mailmap
> +John Molakvoæ <skjnldsv@protonmail.com> John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
add it to https://github.com/nextcloud/server/blob/master/.mailmap to map all those git user+email combinations to one entry

2021-01-23 09:47 UTC, rullzer approved these changes
Fine by me

2021-01-27 13:54 UTC, ChristophWurst approved these changes

2021-01-27 13:54 UTC, merged