feat(federatedfilesharing): log errors, as suggested by @maxbes
nextcloud/server pull request #25498
Opened 2021-02-05 10:59 UTC by faust64

Adds logs to the federatedfilesharing app, which should help in figuring out why a requests might have failed.

2021-02-08 08:09 UTC, rullzer requested changes

2021-02-08 08:09 UTC, rullzer commented on apps/federatedfilesharing/lib/Notifications.php
> +				\OC::$server->getLogger()->info(
Please inject the logger in the constructor. So you don't have to do all these \OC::$server calls.

2021-02-08 09:37 UTC, faust64 commented on apps/federatedfilesharing/lib/Notifications.php
> +				\OC::$server->getLogger()->info(
Sure. I've been looking at how it was done in `apps/user_ldap/lib/User_LDAP.php`, which also has those \OC::$server.  `apps/user_ldap/lib/Group_LDAP.php` does init its logger in constructor, though.
Not sure including `OCP\ILogger` is required. In doubt, I'll stick to what works in other apps.
Let me know if there's other stuff I could clean up.

2021-02-08 20:29 UTC, rullzer commented on apps/federatedfilesharing/lib/Notifications.php
> +		$this->logger = OC::$server->getLogger();
Ah sorry I should have been more clear.
Have the contstructor take the ILogger as argument. Then it gets injected (with automatically setting the app etc as well).

2021-02-09 06:50 UTC, faust64 commented on apps/federatedfilesharing/lib/Notifications.php
> +		$this->logger = OC::$server->getLogger();
oh, allright. Then something like `apps/weather_status/lib/Service/WeatherStatusService.php`?

2021-02-09 20:20 UTC, rullzer commented
Cool stuff. it seems the test need a fix as well. Could you have a look at that?

2021-02-11 13:42 UTC, faust64 commented
There's some ratelimit issue apparently, and a timeout during some mariadb initialization that I can find in other jobs as well, ... I guess the previous commit should be enough. Otherwise let me know @rullzer .

2021-03-03 01:42 UTC, faust64 commented
anyone?

2021-03-22 20:13 UTC, rullzer approved these changes

2021-03-22 20:21 UTC, MorrisJobke approved these changes
👍

2021-03-22 20:21 UTC, merged