catch notfound and forbidden exception in smb::getmetadata
nextcloud/server pull request #25659
Opened 2021-02-15 16:56 UTC by icewind1991

Handle those errors during scanning as files that don'

2021-02-15 19:34 UTC, rullzer requested changes
psalm says no

2021-02-16 13:35 UTC, icewind1991 commented
made psalm happy

2021-02-16 14:42 UTC, juliushaertl approved these changes

2021-02-23 16:06 UTC, icewind1991 commented
/backport to stable21

2021-02-23 16:06 UTC, icewind1991 commented
/backport to stable20

2021-03-05 07:49 UTC, rullzer approved these changes

2021-03-05 07:49 UTC, merged

2021-04-28 11:51 UTC, icewind1991 commented
/backport to stable19