[WIP] Fix user list infinite loading state in user settings
nextcloud/server pull request #25879
Opened 2021-03-02 13:28 UTC by eneiluj

"No users in here" message is shown when there actually are displayed users.

This is because `$state.loaded()` is not called when the retrieved user list length is less than the 25 limit. It has to be called at least once otherwise vue-infinite-loading shows the `no-results` slot.

`$state.loaded()` is now called if the `filteredUsers` computed prop is not empty.

Even if this works, wouldn't it be better to return more information from the `getUsers` store promise (like the actual number of retrieved users) and use it to choose if we call `$state.loaded()`?

2021-03-11 09:55 UTC, PVince81 requested changes, later dismissed

2021-03-11 09:55 UTC, PVince81 commented on apps/settings/src/components/UserList.vue
> +					if (!response) {
what if filteredUsers has zero entries due to the filter but the response was valid ?
as far as I can see there's some client side filtering happening also in the computed property `filteredUsers`

2021-03-11 10:25 UTC, eneiluj commented on apps/settings/src/components/UserList.vue
> +					if (!response) {
I think it works fine in the case you mention. If `filteredUsers` is empty then `$state.loaded()` is not called but the next user list request (with offset) is still done. `$state` is specific to the infinite loading component, it won't stop the request loop.

Checking if `filteredUsers` computed prop is empty is exactly what we need to determine if we should display the empty content message or not.

`(!response)` is true when request result is empty which means we received all users.

2021-03-26 09:42 UTC, rullzer commented
master is 22. Backport once merge if needed.

2021-07-02 14:58 UTC, szaimen commented
Any update here?

2021-07-02 15:08 UTC, eneiluj commented
@PVince81 Did you get a chance to test this PR and https://github.com/nextcloud/server/pull/25195 to check the difference?

2021-07-27 08:57 UTC, eneiluj commented
/compile amend /

2021-07-27 10:40 UTC, eneiluj commented
@PVince81 You're right, #25195 works better than my solution (except one small remaining problem mentioned at the end of this PR's description).

So this PR is now the same as #25195, rebased on master, conflicts resolved.

2021-07-27 10:42 UTC, eneiluj commented
/compile amend /

2021-07-28 04:14 UTC, Pytal commented on apps/settings/src/store/users.js
> +						return usersCount
```suggestion
```

2021-07-28 04:14 UTC, Pytal commented on apps/settings/src/store/users.js
> +					return 0
```suggestion
					return usersCount
```
Combined with the above makes it clearer :)

2021-07-28 04:14 UTC, Pytal commented on apps/settings/src/store/users.js
> +					return usersCount
```suggestion
```

2021-07-28 04:14 UTC, Pytal commented on apps/settings/src/store/users.js
> +				return 0
```suggestion
				return usersCount
```
Same :)

2021-07-28 05:24 UTC, skjnldsv commented
Let's get https://github.com/nextcloud/server/pull/28202 in before

2021-07-28 14:29 UTC, eneiluj commented
@Pytal Thanks for the review. Fixed, rebased on master and pushed.

@skjnldsv Yes sure. I'll ask the bot to compile when #28202 is in.

2021-07-29 00:18 UTC, Pytal approved these changes

2021-07-29 10:58 UTC, eneiluj commented
/compile amend /

2021-08-23 13:23 UTC, eneiluj commented
I don't know why `/drone/src/tests/acceptance/features/users.feature:48` scenario is failing. I followed it manually on a local test instance and it works fine...

2021-08-31 02:15 UTC, szaimen commented
/rebase

2021-08-31 02:15 UTC, szaimen commented
/compile amend /

2021-08-31 02:24 UTC, szaimen commented
/rebase

2021-08-31 09:32 UTC, szaimen commented
@benediktg please rebase

2021-09-01 16:07 UTC, eneiluj commented
@szaimen done

2021-09-03 09:43 UTC, szaimen approved these changes
LGTM :)

2021-09-03 09:43 UTC, merged

2021-09-03 10:47 UTC, szaimen commented
/backport to stable22

2021-09-03 10:47 UTC, szaimen commented
/backport to stable21

2021-09-03 10:47 UTC, szaimen commented
/backport to stable20

2021-09-03 11:26 UTC, szaimen commented
/backport to stable22

2021-09-03 12:12 UTC, eneiluj commented
I don't know why but this bug does not affect stable20 although the implementation is the same. Anyway, no need to backport to stable20 :grin:.

2021-09-03 13:22 UTC, szaimen commented
Thanks for the backports! :)