Check for app updates on disabled page
nextcloud/server pull request #2598
Opened 2016-12-09 21:07 UTC by rullzer

Fixes #2403

We need to check for updates of disabled apps so that if you update with
incompatible apps you at least get a chance to upgrade.

2016-12-09 21:14 UTC, nickvergessen requested changes

2016-12-09 21:14 UTC, nickvergessen commented on settings/Controller/AppSettingsController.php
> +					$newVersion = \OC\Installer::isUpdateAvailable($app['id'], $appFetcher);
Use `$this->appFetcher`

2016-12-09 21:18 UTC, rullzer commented on settings/Controller/AppSettingsController.php
> +					$newVersion = \OC\Installer::isUpdateAvailable($app['id'], $appFetcher);
ah mmm didn't see it was there...

2016-12-09 21:22 UTC, ChristophWurst commented on settings/Controller/AppSettingsController.php
> +						$app['update'] = $newVersion;
did you mean 'false'? 🙈

2016-12-09 21:23 UTC, ChristophWurst commented on settings/Controller/AppSettingsController.php
> +					if ($newVersion !== faslse) {
did you mean 'false'? 🙈

2016-12-09 21:31 UTC, rullzer commented on settings/Controller/AppSettingsController.php
> +					if ($newVersion !== faslse) {
maybe :stuck_out_tongue:

2016-12-09 23:16 UTC, nickvergessen approved these changes

2016-12-10 11:21 UTC, LukasReschke approved these changes

2016-12-10 11:21 UTC, merged