fix(26006): option to remove social links on user settings page
nextcloud/server pull request #26035
Opened 2021-03-09 22:27 UTC by faust64

As suggested in https://github.com/nextcloud/server/issues/26006
Makes social network buttons and "reasons to use nextcloud" link optional.

Disable by setting:

```
$CONFIG['show_reaons_use_nextcloud'] = false;
$CONFIG['show_social_buttons'] = false;
```

Defaults to enabled.

2021-03-10 09:21 UTC, kesselb requested changes

2021-03-10 09:21 UTC, kesselb commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
```suggestion
		$showReasonsUseNextcloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
```

2021-03-10 09:21 UTC, kesselb commented on apps/settings/templates/settings/personal/personal.info.php
> +		<?php if ((!empty($_['twitter']) || $_['lookupServerUploadEnabled']) && $_['show-social-button']) { ?>
Is not related to social buttons. Remove it.

2021-03-10 09:21 UTC, kesselb commented on apps/settings/templates/settings/personal/development.notice.php
> +	<?php if ($_['show-reasons-use-nextcloud'] == true) { ?>
```suggestion
	<?php if ($_['show-reasons-use-nextcloud'] === true) { ?>
```

2021-03-10 09:21 UTC, kesselb commented on apps/settings/templates/settings/personal/development.notice.php
> +	<?php if ($_['show-social-button'] == true) { ?>
```suggestion
	<?php if ($_['show-social-button'] === true) { ?>
```

2021-03-10 09:21 UTC, kesselb commented on apps/settings/lib/Settings/Personal/PersonalInfo.php
> +			'show-social-buttons' => $this->config->getSystemValue('show_social_buttons', true),
Remove it.

2021-03-10 09:27 UTC, kesselb commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
We may use app config here and for show social button.

`$this->config->getAppValue('settings', 'show_reasons_use_nextcloud', 'yes') === 'yes'`

2021-03-10 11:18 UTC, kesselb commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
@faust64 not resolved yet ;)

2021-03-10 11:46 UTC, faust64 commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
Isn't `$showReasonsUseNextcloud = $this->config->getSystemValue('show_reasons_use_nextcloud', 'yes') === 'yes';`  OK? Should I go back with `$this->config->getSystemValue('show_reasons_use_nextcloud', true);` ?
Or just realizing the comment below actually mentions `$this->config->getAppValue('settings', ...` instead of `getSystemValue`, is that it? Move that configuration from config.php, to the appconfig table?

2021-03-10 11:53 UTC, kesselb commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
> Move that configuration from config.php, to the appconfig table?

Yes. When possible use app config.

2021-03-10 12:10 UTC, faust64 commented on apps/settings/lib/Settings/Personal/ServerDevNotice.php
> +		$showReasonsUseNextCloud = $this->config->getSystemValue('show_reaons_use_nextcloud', true);
Sure, thanks for confirming.

2021-03-10 13:15 UTC, kesselb approved these changes, later dismissed

2021-03-10 13:15 UTC, kesselb commented
Looks okay code wise.

2021-03-10 14:43 UTC, jancborchardt commented
My take is: Nextcloud is an open source project available for free, and our goal is to offer an alternative to as many people as possible. This small reference to the code & community along with license, prompt to promote, and feature document is absolutely fine. The more people who know about it, the more people can also participate, and the software can also become better.

If someone really wants to hide it, they can do it via a simple line of CSS as @caro-m commented at https://github.com/nextcloud/server/issues/26006#issuecomment-794244863

But introducing settings for this means the opposite, as usual for settings: This needs to be maintained and ensured it always works, resulting in more busywork rather than time for enhancements and fixes.

2021-03-10 15:55 UTC, jospoortvliet commented
I agree with Jan. If you (as system administrator) have this huge urge to hide the fact that this is Nextcloud  - something that is legal but pretty uncool - then you can do it and maintain it yourself. I feel that as open source project, we have no obligation to make that too easy. Heck, we already make it easy to re-brand and remove the "Nextcloud - a safe home for all your data" slogan and link, too.

2021-03-10 15:56 UTC, jospoortvliet commented
(sorry, hit the wrong button here)

2021-03-22 19:35 UTC, rullzer commented
Closing per @jancborchardt @jospoortvliet comments

2021-03-22 19:35 UTC, closed without merging