Only perform login check during ownership transfer for encryption
nextcloud/server pull request #26149
Opened 2021-03-16 16:37 UTC by ChristophWurst

With most simple storage we actually want data to be transferable to new users, even before the target user has logged in for the first time. Hence I'm scoping the login check to only be run when encryption is actually in use.

2021-03-16 16:56 UTC, Jigsaw5279 requested changes

2021-03-16 16:56 UTC, Jigsaw5279 commented on apps/files/lib/Service/OwnershipTransferService.php
>  			throw new TransferOwnershipException("The target user is not ready to accept files. The user has at least to have logged in once.", 2);
This should probably reflect the new behavior

2021-03-16 23:18 UTC, blizzz commented
What's missing is that the file system is set up for the target users when they did not log in yet – then its not there and moving fails, with or without --move flag.

2021-03-19 12:49 UTC, blizzz commented
> The method OC\Server::getUserFolder has been marked as deprecated

2021-03-19 13:20 UTC, ChristophWurst commented
> The method OC\Server::getUserFolder has been marked as deprecated

Yeah … there is no easy replacement. I deprecated that one to slim down the public API.

I'll fix it in another PR.

![](https://i.kym-cdn.com/entries/icons/original/000/036/622/agnes.jpg)

2021-03-19 13:59 UTC, blizzz commented
> Yeah … there is no easy replacement. I deprecated that one to slim down the public API.

get → IRootFolder → getUserFolder?

> I'll fix it in another PR.

okidoki

2021-03-19 13:59 UTC, blizzz approved these changes

2021-03-19 19:47 UTC, MorrisJobke commented on apps/files/lib/Service/OwnershipTransferService.php
> +			|| !$this->encryptionManager->isReadyForUser($destinationUid)) {
That is a method that's not in the Interface. Do we want to put it there or declare that `$this->encryptionManager` is the implementation and not the interface even if it is in an app (it's still the files app which will always be shipped, but still)

2021-03-19 19:48 UTC, MorrisJobke commented on apps/files/lib/Service/OwnershipTransferService.php
> +			|| !$this->encryptionManager->isReadyForUser($destinationUid)) {
Or add it to the baseline 🙈

2021-03-19 19:49 UTC, ChristophWurst commented on apps/files/lib/Service/OwnershipTransferService.php
> +			|| !$this->encryptionManager->isReadyForUser($destinationUid)) {
Nah let's inject the implementation

2021-03-22 19:28 UTC, rullzer approved these changes

2021-03-22 19:28 UTC, merged

2021-03-22 19:49 UTC, MorrisJobke commented on apps/files/lib/Service/OwnershipTransferService.php
> +			|| !$this->encryptionManager->isReadyForUser($destinationUid)) {
This wasn't taken care of and Psalm will complain 🤯

2021-03-23 07:25 UTC, ChristophWurst commented on apps/files/lib/Service/OwnershipTransferService.php
> +			|| !$this->encryptionManager->isReadyForUser($destinationUid)) {
I know :shrug:

2021-05-03 11:30 UTC, blizzz commented
/backport to stable21

2021-05-03 11:30 UTC, blizzz commented
/backport to stable20