download files via POST request
nextcloud/server pull request #26155
Opened 2021-03-16 21:50 UTC by blizzz

Currently file downloads are triggered by a regular GET request through changing the window location. This can leak file names, but also limits the number of downloadable files for URL length restrictions. 

By switching to a POST request (thus through XHR) we can avoid both aspects. The downside with the chosen method is, that it does not stream the data: the UI is not blocked, but the browser's download progress does not kick in and the save dialog appears only after the file is downloaded. 

* [ ] Hence, there is not visual feedback. 

As far as I researched there is no way around with XHR (no stream support by design). Streams API offer support, alas – as far as i know - still would suffer the same problems around the built-in progress bar and save dialog (and cannot be backported for lack of IE support).

Another approach would be to use the progress indicator as with file uploads with downloads, too. But maybe I also oversaw an option?

2021-03-16 22:15 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +	async get(files, dir, downloadStartSecret) {
No! This is not compliant to our js coding style standards :grin:

2021-03-16 22:17 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +		).then(res => {
Don't use async-await and then

2021-03-16 22:18 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +export default class Download {
Doesn't need to be a class, you can export de function directly

2021-03-16 22:18 UTC, skjnldsv commented on apps/files/src/download.js
> +Object.assign(window.OCA.Files, { Download: new Download() })
Import the function directly and pass it as a reference instead of using `new`

2021-03-16 22:51 UTC, blizzz commented on apps/files/src/services/Download.js
> +	async get(files, dir, downloadStartSecret) {
Okay. What exactly?

2021-03-16 22:51 UTC, blizzz commented on apps/files/src/services/Download.js
> +		).then(res => {
Okay.

2021-03-16 22:52 UTC, blizzz commented on apps/files/src/services/Download.js
> +export default class Download {
Yes. I thought it's more flexible if it should ever be extended, but maybe over engineered.

2021-03-16 22:54 UTC, blizzz commented on apps/files/src/download.js
> +Object.assign(window.OCA.Files, { Download: new Download() })
Okay. (I took example of the several other places where we do it like that)

2021-03-16 23:29 UTC, blizzz commented
An alternative that would keep the browser's download progress would be to announce the download with a post-request, the returns a token, and then trigger the download again by GET but only providing the token as parameter.

2021-03-17 07:09 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +	async get(files, dir, downloadStartSecret) {
`export const get = async function(files, dir, downloadStartSecret) {`

2021-03-17 07:10 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +export default class Download {
No, it's not, if it should be extended, we can just add new exports. They are modules :)

You can put as many `export const xxx = function() {` :wink:

2021-03-17 07:11 UTC, skjnldsv commented on apps/files/src/download.js
> +Object.assign(window.OCA.Files, { Download: new Download() })
Can you point out where we do that? :)

2021-03-17 07:13 UTC, skjnldsv commented
> the browser's download progress does not kick in and the save dialog appears only after the file is downloaded.

For me that is a huge issue.
If we do this, like big hosting companyes are doing (mega was one of the first), we need to show a progress bar. What if the file is 20GB, will I have to wait for 1h to see the file save dialog?

2021-03-17 08:41 UTC, PVince81 commented
> An alternative that would keep the browser's download progress would be to announce the download with a post-request, the returns a token, and then trigger the download again by GET but only providing the token as parameter.

Somehow reminds me of pre-signed download URLs, which are a slightly different thing though.

2021-03-17 20:31 UTC, blizzz commented
> An alternative that would keep the browser's download progress would be to announce the download with a post-request, the returns a token, and then trigger the download again by GET but only providing the token as parameter.

This is now implemented.  

On smoke testing it of course turned out that sharing needs extra care. There is duplication to some degree, so that's still to tackle.

2021-03-17 20:34 UTC, blizzz commented on apps/files/src/download.js
> +Object.assign(window.OCA.Files, { Download: new Download() })
```
$ ack 'Object\.assign.*new'  apps/*/src/
apps/files_sharing/src/files_sharing_tab.js
35:Object.assign(window.OCA.Sharing, { ShareSearch: new ShareSearch() })
36:Object.assign(window.OCA.Sharing, { ExternalLinkActions: new ExternalLinkActions() })
37:Object.assign(window.OCA.Sharing, { ShareTabSections: new TabSections() })

apps/files/src/download.js
29:Object.assign(window.OCA.Files, { Download: new Download() })

apps/files/src/sidebar.js
36:Object.assign(window.OCA.Files, { Sidebar: new Sidebar() })

apps/files/src/files-app-settings.js
35:Object.assign(window.OCA.Files, { Settings: new Settings() })
```

2021-03-30 19:46 UTC, blizzz commented on apps/files/src/services/Download.js
> +export default class Download {
Turned it into  a function, this is how you like it now?

2021-03-30 19:46 UTC, blizzz commented on apps/files/src/services/Download.js
> +	async get(files, dir, downloadStartSecret) {
changed that, too, is it ok now?

2021-04-06 13:01 UTC, skjnldsv commented on apps/files/src/download.js
> +import download from './services/Download'
I would argue that the service file name is a bit too simple and confusing.
But it's no blocker: 

Something like ?
```suggestion
import download from './services/DownloadFileService'
```

2021-04-06 13:03 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +}
```suggestion
export default async function(files, dir, downloadStartSecret) {
	await res = axios.post(generateUrl('apps/files/registerDownload'), {
		files,
		dir,
		downloadStartSecret,
	})

	if (res.status === 200 && res.data.token) {
		const dlUrl = generateUrl('apps/files/ajax/download.php?token={token}',{
			token: res.data.token
		}
		OC.redirect(dlUrl)
	}
}
```

2021-04-06 13:05 UTC, skjnldsv requested changes

2021-04-06 13:05 UTC, skjnldsv commented on apps/files/src/services/Download.js
> +}
It's cleaner to use async/await than then/catch

```suggestion
export default async function(files, dir, downloadStartSecret) {
	const res = await axios.post(generateUrl('apps/files/registerDownload'), {
		files,
		dir,
		downloadStartSecret,
	})

	if (res.status === 200 && res.data.token) {
		const dlUrl = generateUrl('apps/files/ajax/download.php?token={token}',{
			token: res.data.token
		}
		OC.redirect(dlUrl)
	}
}
```

2021-04-06 13:50 UTC, blizzz commented on apps/files/src/download.js
> +import download from './services/Download'
Okay. Just, service is now duplicated (in the path), and what else do you download other than files? It's also actually executing a download. You could argue whether the business logic (register first, then execute), however I think that's an implementation detail here.

2021-04-06 13:54 UTC, blizzz commented on apps/files_sharing/lib/Controller/ShareController.php
> +	public function downloadShare(string $downloadToken) {
It's also debatable to keep this stable, definitely not to backport it. It might be the case that this is used by other tools (or scripts) in the wild to download files from shares.

2023-03-07 19:59 UTC, blizzz commented
unfinished and not and the table, closing.

2023-03-07 19:59 UTC, closed without merging