Validate the website field input to be a valid URL
nextcloud/server pull request #26259
Opened 2021-03-23 13:54 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2021-03-23 14:33 UTC, ChristophWurst approved these changes

2021-03-23 14:48 UTC, tcitworld requested changes

2021-03-23 14:48 UTC, tcitworld commented on lib/private/Accounts/AccountManager.php
> +			&& filter_var($data[self::PROPERTY_WEBSITE]['value'], FILTER_VALIDATE_URL) === false) {
Unfortunately `FILTER_VALIDATE_URL` does not work with IDNs, so either convert to punycode first, otherwise just use a basic regex to validate `http(s)://`.

2021-03-24 13:31 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> +			&& filter_var($data[self::PROPERTY_WEBSITE]['value'], FILTER_VALIDATE_URL) === false) {
urg, good to know

2021-04-22 14:34 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> +			&& filter_var($data[self::PROPERTY_WEBSITE]['value'], FILTER_VALIDATE_URL) === false) {
Fixed

2021-04-22 15:17 UTC, tcitworld approved these changes

2021-04-26 11:56 UTC, merged

2021-04-26 11:56 UTC, nickvergessen commented
/backport to stable21