OCC commands to delete calendars
nextcloud/server pull request #26421
Opened 2021-04-03 10:59 UTC by mattian

Closes #25771.
Add occ commands 'dav:delete-calendar' and 'dav:delete-birthday-calendar' to
delete user's calendars.

2021-04-13 12:00 UTC, tcitworld requested changes
Instead of a separate command to delete birthday calendars I would just go with a `--birthday` option for the `delete-calendar` command, which would set the calendar URI to `BirthdayService::BIRTHDAY_CALENDAR_URI`.

2021-04-13 12:00 UTC, tcitworld commented on apps/dav/lib/Command/DeleteCalendar.php
> +				$calendar = new Calendar(
The only benefit I see in using `new Calendar` instead of directly calling `calDav->deleteCalendar()` is removing the user from the share instead of actually deleting the calendar, but I don't think that's a good idea to do this.

To me, the user `uid` given *should always be* the calendar owner, and the command actually deleting a calendar.

2021-04-13 12:01 UTC, tcitworld commented on apps/dav/lib/Command/DeleteCalendar.php
> +				$calendar = new Calendar(
(Of course, it would need special handling for the birthday calendar case)

2021-04-13 14:45 UTC, victoriat31 approved these changes

2021-04-19 18:22 UTC, mattian commented on apps/dav/lib/Command/DeleteCalendar.php
> +				$calendar = new Calendar(
The reason for using `getCalendarsForUser` and `new Calendar` is, like you guessed, to provide the "unshare from me" feature like the GUI does and allow to delete or unshare every calendar listed by the `dav:list-calendars` command.  
Would you prefer a command option, another command or not to provide this feature at all?

2021-05-02 17:12 UTC, tcitworld commented on apps/dav/lib/Command/DeleteCalendar.php
> +				$calendar = new Calendar(
I think we can add shares management with another command (with a `dav:share` prefix) in another PR later, yes.

2021-05-14 07:14 UTC, tcitworld reviewed
Looks good to me now, but I recommend we wait for https://github.com/nextcloud/server/pull/26083 to be merged, then we can rebase on it and add a `-f` force parameter (which would be passed to CaldavBackend::deleteCalendar).

2021-05-18 11:25 UTC, mattian commented
Ok, thank you

2021-05-31 07:16 UTC, tcitworld commented
@mattian Please rebase on master and add the option to force delete calendars as discussed.

2021-05-31 20:15 UTC, mattian commented
done

2021-05-31 21:24 UTC, mattian commented
done

2021-06-02 17:08 UTC, ChristophWurst commented
@mattian please have a look at the inline annotations generated by psalm. a few types are not clear for the static analysis :)

2021-06-02 17:08 UTC, blizzz commented on apps/dav/lib/Command/DeleteCalendar.php
> +		$user = $input->getArgument('uid');
please cast to string to ensure this is string and silence the warnings

2021-06-02 17:08 UTC, blizzz commented on apps/dav/lib/Command/DeleteCalendar.php
> +	protected function configure() {
```suggestion
	protected function configure(): void {
```

2021-06-03 22:57 UTC, mattian commented on apps/dav/lib/Command/DeleteCalendar.php
> +		$user = $input->getArgument('uid');
A cast makes psalm complain about a `PossiblyInvalidCast` from array<array-key, string> to string. Annotating `$user` as a string variable seems to silence the warnings

2021-06-11 07:18 UTC, tcitworld approved these changes
Lint is happy

2021-06-11 07:23 UTC, ChristophWurst reviewed
Let's check if the duplicate logic of birthday calendars is necessary, the rest looks fine :+1:

2021-06-11 07:23 UTC, ChristophWurst commented on apps/dav/lib/Command/DeleteCalendar.php
> +		if ($name === BirthdayService::BIRTHDAY_CALENDAR_URI) {
isn't this already handled in ``\OCA\DAV\CalDAV\Calendar::delete``? Generally speaking the command should just be an entry point into the application's logic, so I would prefer to have as little logic in here as possible :)

2021-06-11 07:46 UTC, tcitworld commented on apps/dav/lib/Command/DeleteCalendar.php
> +		if ($name === BirthdayService::BIRTHDAY_CALENDAR_URI) {
Indeed, let's do something like this:
```php
$calendarInfo = $this->calDav->getCalendarByUri('principals/users/' . $user, $name);
[...]
$calendar = new \OCA\DAV\CalDAV\Calendar($this->caldav, $calendarInfo, $this->l10n, $this->config);
$calendar->disableTrashbin($force);
$calendar->delete();
```

2021-06-11 07:51 UTC, ChristophWurst commented on apps/dav/lib/Command/DeleteCalendar.php
> +		if ($name === BirthdayService::BIRTHDAY_CALENDAR_URI) {
or
```php
if ($force) {
    $calendar->disableTrashbin();
}
```
to avoid a change on the calendar just for this use case :)

2021-06-14 08:03 UTC, ChristophWurst approved these changes
Code looks good!

2021-06-14 08:03 UTC, merged

2021-06-14 08:04 UTC, ChristophWurst commented
@mattian FYI your commit isn't associated with your github user. You might want to add the email address to your account so you are correctly shown as contributor :)