Dashboard API for clients
nextcloud/server pull request #26430
Opened 2021-04-06 09:27 UTC by eneiluj

This brings a new dashboard API endpoint which provides a standardized way to get enabled widgets content for Nextcloud clients. For the moment, only widgets displaying an ordered list of items can be accessed by this API. It could be extended to other kinds of content later.

The new `WidgetItem` class is a generic representation of one widget element.
The initial IWidget interface can still be used by widgets. The new IAPIWidget interface just adds a `getItems` method which returns an array of `WidgetItem`.

Here are the changes made to GitHub integration dashboard widget to implement this client API:
https://github.com/nextcloud/integration_github/commit/e888d8f75059595c5c2c9c6f18c2efa1a08e2937#diff-322e5fa76010510d00333c44839783ab8b832362c8719b4b54ae08a6b99e853bR44

2021-04-06 11:05 UTC, nickvergessen commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboard#getWidgetItems', 'url' => '/api/widget-items', 'verb' => 'POST'],
Must use `ocs`  route, and since you get the data verb should be GET?

2021-04-06 11:07 UTC, nickvergessen commented on apps/dashboard/lib/Controller/DashboardController.php
> +			if (method_exists($widget, 'getItems') && in_array($widget->getId(), $userLayout)) {
```suggestion
			if ($widget instanceof IAPIWidget && in_array($widget->getId(), $userLayout)) {
```

2021-04-06 11:47 UTC, eneiluj commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboard#getWidgetItems', 'url' => '/api/widget-items', 'verb' => 'POST'],
Thanks for the review!
Yeah I chose POST because I thought it was not possible to pass JSON content in a GET request but it actually works fine :grin:.

2021-04-06 11:57 UTC, nickvergessen commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboard#getWidgetItems', 'url' => '/api/v1/widget-items', 'verb' => 'GET'],
This needs to be an `OCP\AppFramework\OCSController` so you can't have them both in the same controller

2021-04-06 12:28 UTC, eneiluj commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboard#getWidgetItems', 'url' => '/api/v1/widget-items', 'verb' => 'GET'],
:see_no_evil: Yes indeed.

2021-04-08 09:05 UTC, juliushaertl commented on lib/public/Dashboard/Model/WidgetItem.php
> +final class WidgetItem {
The WidgetItem should probably also have a link property so the integrating app can do something on click

2021-04-08 09:06 UTC, juliushaertl commented on lib/public/Dashboard/Model/WidgetItem.php
> +	 * Get the item icon URL
We probably should add some hint on the format and size/ratio here. Probably fine to just mention it should be a square svg or at least 44x44px on a bitmap format.

2021-04-08 09:07 UTC, juliushaertl reviewed
General structure seems fine, there are some php-cs and psalm failures besides my comments.

2021-04-08 09:09 UTC, juliushaertl commented
Once merged this should also be documented in https://docs.nextcloud.com/server/21/developer_manual/digging_deeper/dashboard.html

2021-04-08 11:58 UTC, eneiluj commented
@juliushaertl Thanks for the review. Link added, php-cs/psalm error fixed and rebased on master.

2021-04-13 18:15 UTC, juliushaertl commented on apps/dashboard/lib/Controller/DashboardApiController.php
> +	/** @var string */
```suggestion
	/** @var string|null */
```

2021-04-13 18:17 UTC, juliushaertl commented on lib/public/Dashboard/Model/WidgetItem.php
> +final class WidgetItem {
```suggestion
final class WidgetItem implements \JsonSerializable {
```

2021-04-13 18:18 UTC, juliushaertl commented on apps/dashboard/lib/Controller/DashboardApiController.php
> +				$items[$widget->getId()] = array_map(function (WidgetItem $item) {
There shouldn't be a need or the mapping if the WidgetItem implements JsonSerializable

2021-04-13 18:18 UTC, juliushaertl approved these changes
Some smaller additional comments but otherwise :+1:

2021-04-14 09:27 UTC, eneiluj commented on apps/dashboard/lib/Controller/DashboardApiController.php
> +				$items[$widget->getId()] = array_map(function (WidgetItem $item) {
What do you mean?
How would you serialize each item?

2021-05-21 14:20 UTC, MorrisJobke commented
🏓

2021-06-02 15:04 UTC, skjnldsv commented
Moved to 23

2021-06-08 13:10 UTC, eneiluj commented
@juliushaertl @MorrisJobke @skjnldsv Rebased on master, affected milestone 22 again (it does not break anything and it's ready).

I don't know why the `ci/drone/pr` fails...

2021-06-09 05:03 UTC, juliushaertl commented
From https://drone.nextcloud.com/nextcloud/server/6078/1/3

```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2021-06-09 05:04 UTC, juliushaertl commented
Other drone failures seem unrelated

2021-06-09 06:44 UTC, nickvergessen commented on apps/dashboard/lib/Controller/DashboardApiController.php
> +				$items[$widget->getId()] = array_map(function (WidgetItem $item) {
https://3v4l.org/n0PPI

2021-06-10 08:22 UTC, MorrisJobke approved these changes
Code looks good (beside the one nitpick) 👍

2021-06-14 07:49 UTC, juliushaertl commented
:ping_pong: @eneiluj

2021-06-14 12:18 UTC, skjnldsv commented
@artonge could you have a look at this and see if you can find any blockers? :)

2021-06-14 13:07 UTC, artonge commented
The code scanning warnings should get fixed. And it would be saner with Julius' suggestion for the JSON serialisation. Beside that, LGTM. But I might not be the best juge for php code yet :wink:

2021-06-14 13:08 UTC, artonge requested changes
Oh nop, comments are wrong.

2021-06-14 13:08 UTC, artonge commented on lib/public/Dashboard/IAPIWidget.php
> + * @since 22.0.0
`@since 23.0.0`

2021-06-14 13:08 UTC, artonge commented on lib/public/Dashboard/IAPIWidget.php
> +	 * @since 22.0.0
`@since 23.0.0`

2021-06-14 13:08 UTC, artonge commented on lib/public/Dashboard/Model/WidgetItem.php
> + * @since 22.0.0
`@since 23.0.0`

2021-06-14 13:08 UTC, artonge commented on lib/public/Dashboard/Model/WidgetItem.php
> +	 * @since 22.0.0
`@since 23.0.0`

2021-06-14 13:09 UTC, artonge commented on lib/public/Dashboard/Model/WidgetItem.php
> +	 * @since 22.0.0
And so on

2021-06-14 14:10 UTC, nickvergessen commented on lib/public/Dashboard/IAPIWidget.php
> + * @since 22.0.0
As far as I understood this shall go in before 22

2021-06-14 14:17 UTC, artonge commented on lib/public/Dashboard/IAPIWidget.php
> + * @since 22.0.0
Fooled by the comment of @skjnldsv :

> Moved to 23

But @eneiluj set the milestone to 22 after that.

2021-06-15 16:09 UTC, artonge commented on lib/public/Dashboard/IAPIWidget.php
> + * @since 22.0.0
So, ok for  22 ?

2021-06-15 16:10 UTC, artonge approved these changes

2021-06-15 19:36 UTC, juliushaertl commented
Rebased and pushed the updated autoloader.

2021-06-16 09:34 UTC, merged