Limit size of properties to 2048 characters
nextcloud/server pull request #26433
Opened 2021-04-06 16:03 UTC by LukasReschke

It is unreasonable to expect that one of these fields would be longer
than 2048 characters. Whilst some have definitely lower limits (such as
for phone numbers or domain names), a upper bound as sanity check makes
sense.

2021-04-06 17:26 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> +					throw new \InvalidArgumentException($propertyName . ' is too long');
```suggestion
					throw new \InvalidArgumentException($propertyName);
```

This way the clients receive the field ID and can show a proper localized message

2021-04-06 17:26 UTC, nickvergessen requested changes
See comment

2021-04-07 12:00 UTC, nickvergessen approved these changes

2021-04-08 09:55 UTC, rullzer approved these changes

2021-04-08 10:38 UTC, merged

2021-04-12 16:21 UTC, LukasReschke commented
/backport to stable21

2021-04-12 16:22 UTC, LukasReschke commented
/backport to stable20

2021-04-12 16:22 UTC, LukasReschke commented
/backport to stable19