[FEATURE] allow install via composer
nextcloud/server pull request #2644
Opened 2016-12-13 13:05 UTC by kaystrobach

2016-12-13 14:49 UTC, nickvergessen requested changes

2016-12-13 14:49 UTC, nickvergessen commented on composer.json
> +    "description": "Media gallery for ownCloud which includes previews for all media types supported by your ownCloud installation.",
*cough* no?

2016-12-14 08:03 UTC, MariusBluem commented on composer.json
> +    "description": "Media gallery for ownCloud which includes previews for all media types supported by your ownCloud installation.",
Replace it with: 

_A safe home for all your data. Access, share and protect your files, calendars, contacts, communication & more at home and in your enterprise._

2016-12-14 08:05 UTC, kaystrobach commented
changed as requested

2016-12-14 08:08 UTC, rullzer commented
This will fail hard I bet because the 3rdparty repo is a submodule.

2016-12-14 08:13 UTC, kaystrobach commented
I will try to get this fixed afterwards.

please see https://github.com/owncloud/core/issues/11973#issuecomment-74882008 for the same discussion in owncloud, i think it's pretty crucial to have full composer support in a midterm.
So security of libs can be easily checked with tools like:

See http://stackoverflow.com/questions/18100420/how-do-i-use-a-git-submodule-with-a-composer-loaded-library for details ... should work with `prefer-dist` option set.

2016-12-14 09:54 UTC, nickvergessen commented
> So security of libs can be easily checked with tools like:

Our libs are already handled by composer:
https://github.com/nextcloud/3rdparty/blob/master/composer.json

2016-12-14 10:18 UTC, kaystrobach commented
would be awesome to have that in the main composer.json to allow fast in reliable install via composer, this would also allow professional extension installations (with dependencies)

2016-12-16 11:23 UTC, LukasReschke commented
> please see owncloud/core#11973 (comment) for the same discussion in owncloud, i think it's pretty crucial to have full composer support in a midterm.

We won't go with a full composer alike approach anytime soon from my opinion as this moves libraries out of our control (e.g. random person can delete their libs) plus I yet fail to see some security features such as signing the library. I am not willed to accept situations where a third-party dev can randomly change the code that is offered to download for stability and security reasons.

But we do check the security of the libraries already using VersionEye for example.

2016-12-16 11:42 UTC, kaystrobach commented
How do you deploy nextxloud then?

Fork repo put submodules for each plugin in, use dotenv for conf?

2016-12-16 11:43 UTC, kaystrobach commented
Feels a bit strange to have more than composer.json + composer.lock in the dist forlder for deployment 😉

2016-12-16 11:46 UTC, LukasReschke commented
> How do you deploy nextxloud then?
> Fork repo put submodules for each plugin in, use dotenv for conf?

Download the ZIP or TAR from our webpage as officially documented 😉  – If one wanna use git, well, then one has to checkout whatever submodules an app may ship and figure that out for themselves.

2017-01-11 08:00 UTC, rullzer commented
Also there is the matter of not everything that is in the tarball being in the main repo. So you endup with a lot of git commands anyway.

So lets close this as nothing is happening. For installation please use the ZIP/TAR ball and if you want to use git then write a script that does all the additional checkouts.

2017-01-11 08:00 UTC, closed without merging