CompressionMiddleware: Add Brotli Compression
nextcloud/server pull request #26441
Opened 2021-04-07 15:51 UTC by aidanharris

This commit adds Brotli compression in addition to the existing GZip
compression. If a client requests either GZip or Brotli compression, Brotli is preferred.

Testing:

Ensure your PHP is configured with the [php-ext-brotli extension](https://github.com/kjdev/php-ext-brotli/). Systems without this extension should continue to work using GZip.

2021-04-09 09:29 UTC, kesselb reviewed
Thank you very much :+1:

2021-04-09 09:29 UTC, kesselb commented on lib/private/AppFramework/Middleware/CompressionMiddleware.php
> +		if (($allowGzip === false) && ($allowBrotli === false)) {
```suggestion
		if ($allowGzip === false && $allowBrotli === false) {
```

2021-04-09 09:29 UTC, kesselb commented on lib/private/AppFramework/Middleware/CompressionMiddleware.php
> +				$this->useGZip = false;
```suggestion
```

2021-04-09 09:29 UTC, kesselb commented on lib/private/AppFramework/Middleware/CompressionMiddleware.php
> +				$this->useGZip = false;
false seems the default

2021-04-13 18:14 UTC, rullzer requested changes
I'm not a nhuge fan of such checks. but so be it.
However if I'm not mistaken the RFC specifies to consider the order of the Accept encoding. So we should then properly parse it.

2021-04-13 19:57 UTC, kesselb commented
> So we should then properly parse it.

https://symfony.com/doc/current/components/http_foundation.html#accessing-accept-headers-data
https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/HttpFoundation/AcceptHeader.php
https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/HttpFoundation/AcceptHeaderItem.php

We use some symfony components but not symfony/http-foundation. However they already solved it properly. So that might be a starting point for us. If the license allows we may include it.

2022-12-17 16:50 UTC, kesselb commented
Hi @aidanharris,

We bundle symfony http-foundation since Nextcloud 25. 

Do you have time to look into this feature again?

2023-01-31 00:16 UTC, closed without merging