E-Mail-Reminder to all attendees is sent only by organizer
nextcloud/server pull request #26496
Opened 2021-04-10 16:00 UTC by christlang

When the organizer adds the reminder the nextcloud attendees only get 2 mails now.
* one from the organizer
* one for their own reminder

outside-users get only the mail from the organizer, because they have no own reminders

2021-04-11 14:56 UTC, tcitworld requested changes

2021-04-11 14:56 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		if ($userOfReminder && strcasecmp($userOfReminder->getEMailAddress(), key($organizer)) == 0) {
Make sure both `$userOfReminder` and `$organizer` are not `null`.
```suggestion
		if ($organizer !== null && $userOfReminder instanceof IUser && strcasecmp($userOfReminder->getEMailAddress(), key($organizer)) === 0) {
```

2021-04-11 14:56 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		if (!str_starts_with($organizer->getValue(), 'mailto:')) {
This is PHP 8 exclusive, so we can't use this yet.
```suggestion
		if (strcasecmp($organizer->getValue(), 'mailto:') !== 0) {
```

2021-04-11 14:58 UTC, tcitworld commented
Seems you need to update a test as well:
```
There was 1 failure:

1) OCA\DAV\Tests\unit\CalDAV\Reminder\NotificationProvider\EmailProviderTest::testSendWithAttendees
Expectation failed for method name is "validateMailAddress" when invoked at sequence index 1
Parameter 0 for invocation OCP\Mail\IMailer::validateMailAddress('uid1@example.com'): bool does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'foo1@example.org'
+'uid1@example.com'

/drone/src/apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php:127
/drone/src/apps/dav/tests/unit/CalDAV/Reminder/NotificationProvider/EmailProviderTest.php:340
```

2021-04-12 08:08 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/INotificationProvider.php
> +						 IUser $userOfReminder = null): void;
I find the name *user of reminder* confusing. Would owner be a better fit?

2021-05-06 09:14 UTC, EhiOnime commented
OK I think I found the solution to this problem by changing the SQL query in Reminder/Backend.php and adding a GroupBy clause to ensure that even if there are multiple entries in the database, it will return just one of them:

`--- lib/CalDAV/Reminder/Backend.php.orig	2021-02-19 09:49:36.000000000 +0100
+++ lib/CalDAV/Reminder/Backend.php	2021-05-06 10:56:17.252243326 +0200
@@ -70,5 +70,6 @@
 			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
 			->leftJoin('cr', 'calendarobjects', 'co', $query->expr()->eq('cr.object_id', 'co.id'))
-			->leftJoin('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'));
+			->leftJoin('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'))
+			->groupBy(['cr.event_hash','cr.type','cr.uid']);
 		$stmt = $query->execute();
 
`

2021-05-08 12:08 UTC, christlang commented
@EhiOnime I like your solution ;)

Have you tested it? Because you get only one reminder back from the sql-query only one will be performed. And in the next run the next run the next will be performed, isn't it?

2021-05-08 12:21 UTC, christlang commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		if ($userOfReminder && strcasecmp($userOfReminder->getEMailAddress(), key($organizer)) == 0) {
:+1:

2021-05-08 12:21 UTC, christlang commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		if (!str_starts_with($organizer->getValue(), 'mailto:')) {
:+1:

2021-05-08 12:22 UTC, christlang commented on apps/dav/lib/CalDAV/Reminder/INotificationProvider.php
> +						 IUser $userOfReminder = null): void;
somehow I like the reminder. Is reminderOwner okay for you?

2021-05-08 12:38 UTC, christlang commented
ah for the tests I have to install phpunit ...
https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html

2021-05-08 15:01 UTC, EhiOnime commented
Thank you for your emails.

Yes, unfortunately the single patch against the database query did not 
seems to have solve the problem completely as subsequent runs of the 
cron jobs will keep processing them one by one, so the users get 
multiple notifications just with some delay inbetween.

Please find attached a new patch on only the file EmailProvider.php that 
does a much better job, I think..

  Could you also help to test this ?
Kind regards


On 5/8/21 2:39 PM, cl wrote:
>
> ah for the tests I have to install phpunit ...
> https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html 
> <https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nextcloud/server/pull/26496#issuecomment-835343620>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AT7ATLOKMDSE2DX7AZ5XTF3TMUWHBANCNFSM42WURAPA>.
>

2021-05-09 06:02 UTC, EhiOnime commented
OK, here is the definite fix.
It adds a userManager object to EmailProvider.php and uses that to 
filter out any atendee email address belonging to
a nextcloud user.

Best

On 5/8/21 5:01 PM, Onime Clement wrote:
> Thank you for your emails.
>
> Yes, unfortunately the single patch against the database query did not 
> seems to have solve the problem completely as subsequent runs of the 
> cron jobs will keep processing them one by one, so the users get 
> multiple notifications just with some delay inbetween.
>
> Please find attached a new patch on only the file EmailProvider.php 
> that does a much better job, I think..
>
>  Could you also help to test this ?
> Kind regards
>
>
> On 5/8/21 2:39 PM, cl wrote:
>>
>> ah for the tests I have to install phpunit ...
>> https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html 
>> <https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub 
>> <https://github.com/nextcloud/server/pull/26496#issuecomment-835343620>, 
>> or unsubscribe 
>> <https://github.com/notifications/unsubscribe-auth/AT7ATLOKMDSE2DX7AZ5XTF3TMUWHBANCNFSM42WURAPA>.
>>
>

2022-02-03 07:51 UTC, christlang commented
your are welcome to finish this work, sorry for late response. You see I have not really the time to bring this to an end ;) thanks for taking over

2022-10-03 19:23 UTC, miaulalala commented
Closing in favour of #34417

2022-10-03 19:23 UTC, closed without merging