Files & Core accessibility fixes
nextcloud/server pull request #26548
Opened 2021-04-13 18:36 UTC by jancborchardt

Before | After
-|-
![Lighthouse score for files Accessibility: 81](https://user-images.githubusercontent.com/925062/114602589-11596c80-9c97-11eb-8261-68196667f377.png) | ![Lighthouse score for files Accessibility: 94](https://user-images.githubusercontent.com/925062/114602575-0c94b880-9c97-11eb-83e3-7b38351b2f3e.png)

Also tested with keyboard only and a screenreader.

The only thing remaining seems to be the `aria-controls` attribute of the search button. But I can’t figure out why, cause it does correspond to an element. Any idea @skjnldsv @GabeGabeT @szet0018 @RubyDo?
![Lighthouse accessibility notice about aria attribute of the search button](https://user-images.githubusercontent.com/925062/114602530-fedf3300-9c96-11eb-92bb-e3c093a0746c.png)

-----

Here some demo of before/after of the focus feedback for file list actions, since the other ones are mostly screenreader label fixes:

https://user-images.githubusercontent.com/925062/114603104-9cd2fd80-9c97-11eb-8fb3-e82e12bae674.mp4

https://user-images.githubusercontent.com/925062/114603105-9d6b9400-9c97-11eb-9228-f6ef80fd644b.mp4

2021-04-13 18:37 UTC, jancborchardt commented
/backport to stable21

2021-04-14 05:25 UTC, MarcoZehe requested changes
The file core/js/dist/unified-search.js is impossible to review, because its diff has over 42,554 changed lines. Is there something wrong with line endings maybe so that each line apears as a changed one? Please update the patch with a more readable diff.

2021-04-14 05:25 UTC, MarcoZehe commented on apps/settings/templates/settings/personal/personal.info.php
> +					<div class="federation-menu" tabindex="0" aria-label="<?php p($l->t('Change privacy level of profile picture')); ?>">
Why is this div focusable? It has no role and as far as I can see no keyboard handler. Same is true for the span inside. If that is somehow clickable, it needs to be keyboard actionable somehow. From the code above I don't see what this does. Same goes for all the ones in the forms below.

2021-04-14 05:25 UTC, MarcoZehe commented on apps/settings/templates/settings/personal/personal.info.php
>  					<label><?php p($l->t('Profile picture')); ?></label>
While you're here, please either make the label actually label something, via its for attribute pointing to an ID of an input or select or textarea, or find a better suited element. A label standing on its own is semantically incorrect.

2021-04-14 05:25 UTC, MarcoZehe commented on apps/settings/templates/settings/personal/personal.info.php
> +					<div class="federation-menu" tabindex="0" aria-label="<?php p($l->t('Change privacy level of full name')); ?>">
Is this focusable because you're going to change the actual menu items via aria-activedescendant? Otherwise, same questions as above for that other focusable div.

2021-04-14 06:28 UTC, skjnldsv commented
> The file core/js/dist/unified-search.js is impossible to review, because its diff has over 42,554 changed lines. Is there something wrong with line endings maybe so that each line apears as a changed one? Please update the patch with a more readable diff.

@MarcoZehe this one is the compiled bundle.
You need to review the source files: `core/src/views/UnifiedSearch.vue`

2021-04-14 07:12 UTC, MarcoZehe commented
@skjnldsv Ah, so these patches include two compiled sources, one of them minified? Geez... Yeah that vue source file didn't have anything suspicious, but the questions and requests from my other comments are still valid.

2021-04-15 11:24 UTC, jancborchardt commented on apps/settings/templates/settings/personal/personal.info.php
>  					<label><?php p($l->t('Profile picture')); ?></label>
Right, this must have been added because the other elements all only have one input field. I removed the label tag, since there are 3 labeled buttons in the section itself.

Also found further accessibility issues in there which are fixed now – thanks for the review! :)

2021-04-15 11:26 UTC, jancborchardt commented
Fixed the issues with the "Profile picture" section. But for @MarcoZehe’s other remark, a Javascript expert would have to take over.
@skjnldsv do you want to fix the remark in here, or would you prefer we merge this and do it in a follow-up? The div should ideally become a button, and if possible we can use the ActionMenu there since our components are accessible?

And thanks a ton @MarcoZehe for the review!

2021-04-15 15:25 UTC, skjnldsv approved these changes
:elephant:

2021-04-15 15:27 UTC, jancborchardt commented
@MarcoZehe I fixed your feedback about the label, the issue with the "divs which should be buttons" I would open as a separate issue and handle it separately, as for that I need a Javascripter to take over and it ideally shouldn’t block the merging of these fixes. Would that be ok?

2021-04-15 15:29 UTC, MarcoZehe commented
Yes, that would be fine.

2021-04-15 15:32 UTC, MarcoZehe approved these changes

2021-04-15 16:17 UTC, jancborchardt commented
Ah and for the record: The element is a div, but I tested with keyboard and screen reader and it does read "Change privacy level of profile picture" and the menu can be opened using space (and closed with Escape).

So mainly it is about just changing it to a button – I’m already working on preparing the follow-up pull request.

2021-04-15 16:20 UTC, jancborchardt commented
The failures seem unrelated. Can you confirm @rullzer @skjnldsv?

2021-04-15 16:41 UTC, jancborchardt commented
Actually almost fixed it already, but needed to use `<a>` instead of `<button>` – commit coming soon.

2021-04-15 16:49 UTC, jancborchardt commented
Ok, resolved the basics of the menu, but this will be properly fixed once we move the rest of settings to the Vue components as well which are accessible by default. :)

2021-04-19 08:20 UTC, ma12-co approved these changes

2021-04-19 20:01 UTC, jancborchardt commented
Now rebased several times, checks still failing. Seem unrelated, could you confirm @rullzer @ma12-co?

2021-04-20 11:51 UTC, jancborchardt commented
Failures unrelated: https://github.com/nextcloud/server/issues/26314

2021-04-20 11:51 UTC, merged