Allow admins to search for users by display name or email, per #1749
nextcloud/server pull request #2660
Opened 2016-12-13 22:21 UTC by justin-sleep

Tested with my 4 users. @hregnier, could you test this with your 30k users?

Signed-off-by: justin-sleep <justin@quarterfull.com>

2016-12-14 07:12 UTC, justin-sleep commented
Not sure why it's failing some tests on drone after I implemented the null array check.  Seems to be git cloning errors unrelated to my changes.

2016-12-14 08:36 UTC, hregnier commented
@justin-sleep thanks for your PR! It works on my 30k+ users, no lags or whatever.
By the way, as the comments says, partial strings for mail (and maybe display name?) would be great.
Thanks again!

2016-12-14 08:39 UTC, justin-sleep commented
@hregnier no problem! Partial strings for display name should actually already work, I've just tested it on my own server.  I'll see if I can figure out something for email, though.

2016-12-14 08:46 UTC, hregnier commented
@justin-sleep About display name, I didn't express myself well : For exemple I have a user who's DisplayName is "Doe John". I can't find him by typing "John Doe". But maybe that is a bug for the searchDisplayName function and needed another issue report?

2016-12-14 09:01 UTC, justin-sleep commented
Hmm, I see what you mean; that would certainly add more versatility to the search. Off the top of my head, a potential solution would be to split the display name into an array of strings ("sub-patterns") using space as a delimiter, than calling getDisplayName on each sub-pattern. I'll take a look at it.

2016-12-14 16:51 UTC, justin-sleep commented
@hregnier the latest commit I pushed should allow the more flexible display name matching you described.

2016-12-16 22:16 UTC, MorrisJobke requested changes

2016-12-16 22:16 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                else {
Please always use brackets for `if` blocks.

2016-12-16 22:31 UTC, MorrisJobke requested changes

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                $batch = array();
The indentation for this whole block seems to be wrong. Could you please check that you use tabs to indent? Thanks

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                else {
Please use `} else {` on a single line. Sorry for this nitpicking

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                $arrays = array();
Please don't use such generic names.

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                $arrays[0] = $this->userManager->search($pattern, $limit, $offset);
use `searchResult` or something more descriptive.

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                    $arrays[1] = $this->userManager->searchDisplayName($pattern, $limit, $offset);
Please use `displaynameSearchResult` or something more descriptive here instead of `$array[1]`

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                $arrays[2] = $this->userManager->getByEmail($pattern);
use `emailSearchResult` or something more descriptive here

2016-12-16 22:31 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                foreach ($arrays as $arr) {
Either build here the array of arrays or simply call array_merge three times. It's more crucial to have readable code instead of clever or smart code.

2016-12-18 14:39 UTC, MorrisJobke commented on settings/Controller/UsersController.php
> +                $arrays = array();
🙂

2016-12-20 10:12 UTC, hregnier commented
thanks @justin-sleep  it seems to works! Some bug appear (If i search "John " only one john on the dozens appear, but typing another letter or trim the space refresh the search) but it's not so disturbing compare to the improvement :)

2016-12-20 20:17 UTC, justin-sleep commented
@hregnier I'm having trouble replicating what you're describing.  This is what I'm doing to try to run into your bug:

- Create multiple users named John (e.g. display name is John Doe, John Goodman, etc.) with random usernames
- Type "John " into the search bar

But for me, this returns a list that contains every user whose display name contains John.  Could you clarify the properties of the users that aren't getting returned?

2016-12-21 08:07 UTC, hregnier commented
That's a problem. I can't get you clearer information because i can't find any pattern of the bug. 

Another example : I have a user who username is "Dupont Jean". I can't find him when I search "dupont jean" but find him with "jean dupont" ! But I do not have the same problem with every user... 

I understand you can't reproduce the bug. I can't show you a real set of users, although it should be usefull.

2017-01-26 05:14 UTC, MorrisJobke approved these changes
Works here 👍

2017-01-26 05:14 UTC, MorrisJobke commented
@blizzz Could you give this a try?

cc @nickvergessen @rullzer @schiessle @icewind1991

2017-01-26 09:19 UTC, nickvergessen requested changes

2017-01-26 09:19 UTC, nickvergessen commented on settings/Controller/UsersController.php
> +				$searchResults = array($uidSearchResult, $displayNameSearchResult, $emailSearchResult);
They all are arrays only, so you can simply do:
```php
$batch = array_merge($uidSearchResult, $displayNameSearchResult, $emailSearchResult);
```

2017-01-27 17:53 UTC, justin-sleep commented on settings/Controller/UsersController.php
> +				$searchResults = array($uidSearchResult, $displayNameSearchResult, $emailSearchResult);
Updated.

2017-01-30 12:53 UTC, blizzz requested changes
I am not sure I like this approach. Basically it forces this search behavior over all user backends. Especially in case of LDAP it would fire 2 searches (plus the local email lookup, unnecessarily) for "Joann Doe" while the LDAP backend supports this all already, in just one go. I'd prefer to have this implemented on the specific backend.

2017-02-28 09:51 UTC, ChristophWurst commented
@justin-sleep @nickvergessen @blizzz what's the status here? How can we proceed with this?

2017-03-02 22:41 UTC, justin-sleep commented
@ChristophWurst I haven't proceeded with the changes @blizzz requested.  I haven't looked into the codebase enough to know where the individual backends are located to implement the changes there rather than in UsersController, so if someone could point me to the backends I could give it a look.

2017-03-08 09:08 UTC, blizzz commented
@justin-sleep starting point for local  backend: https://github.com/nextcloud/server/blob/master/lib/private/User/Database.php

LDAP backend allows this already, so it does not need to be touched.

I have no overview about other backends.

2017-11-13 15:44 UTC, blizzz commented
moving to 14 due to freeze. @justin-sleep are you still interested in finishing it?

2017-11-14 16:47 UTC, MorrisJobke commented
The search for displayname is fixed with #7169

2017-11-14 22:42 UTC, MorrisJobke commented
There is only the search by email missing. And as it needs to be done in a similar place like #7169 I will close this and have opened a issue for this remaining thing in #7175.

2017-11-14 22:42 UTC, closed without merging