Add commands to manage tags via OCC
nextcloud/server pull request #26600
Opened 2021-04-16 16:53 UTC by noiob

I'm adding `tag:list`, `tag:add`, `tag:delete`, and `tag:edit` commands to OCC

2021-04-20 14:08 UTC, rullzer approved these changes

2021-04-20 14:10 UTC, rullzer commented on lib/public/SystemTag/ISystemTag.php
> +	public function getHumanReadableAccess(): string;
I'm not 100% sure if we'd want this in the public API. As then it can never be translated.
Also maybe a constant is better than just a string? @ChristophWurst

2021-04-20 14:31 UTC, nickvergessen requested changes
Couple of minor comments

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/Add.php
> +		$name = $input->getArgument('name');
check for empty name?

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/Add.php
> +	 */
```suggestion
```

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/Delete.php
> +	 */
```suggestion
```

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/Edit.php
> +			if ($input->getOption('name')) {
tag with name `'0'` is not accepted, I would check for null and empty string instead

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/ListCommand.php
> +	 * @param bool [$detailed=false]
```suggestion
```

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/ListCommand.php
> +	 */
```suggestion
```

2021-04-20 14:31 UTC, nickvergessen commented on core/Command/SystemTag/ListCommand.php
> +			);
call parent::configure() instead?

2021-04-20 14:31 UTC, nickvergessen commented on core/register_command.php
> +	$application->add(new OC\Core\Command\SystemTag\Add(\OC::$server->get(\OCP\SystemTag\ISystemTagManager::class)));
Add is highlighted weirdly, github failure or a received word?

2021-04-20 15:26 UTC, juliushaertl commented on core/Command/SystemTag/Edit.php
> +			$tag = array_values($tag_arr)[0];
```suggestion
		$tagArray = $this->systemTagManager->getTagsByIds($input->getArgument('id'));
		// returns an array, but we always expect 0 or 1 results

		if ($tagArray) {
			$tag = array_values($tagArray)[0];
```

to stick to https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#objects-functions-arrays-variables

2021-04-20 20:30 UTC, kesselb reviewed
Thanks :+1: Cool feature :partying_face:

2021-04-20 20:30 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +				'sets the \'name\' parameter',
`name of the tag`

2021-04-20 20:30 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +				'sets the `visible` and `assignable` parameters (public, restricted, invisible)',
`access level of the tag (public, restricted or invisible)`

2021-04-20 20:30 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +			->addOption(
can you try to remove the option here and call `parent::configure()` at the end of the method?

2021-04-26 09:47 UTC, noiob commented on core/Command/SystemTag/Edit.php
> +			if ($input->getOption('name')) {
ah, good catch

2021-04-26 09:47 UTC, noiob commented on core/register_command.php
> +	$application->add(new OC\Core\Command\SystemTag\Add(\OC::$server->get(\OCP\SystemTag\ISystemTagManager::class)));
hm, looks normal in my VS Code, Add doesn't seem to be a reserved word and there's other commands with the same name

2021-04-26 09:47 UTC, noiob commented on lib/public/SystemTag/ISystemTag.php
> +	public function getHumanReadableAccess(): string;
I just wanted to avoid code reuse in the commands. Not sure what would be a better solution? The result of this function could still be used as translation keywords

2021-05-03 14:27 UTC, noiob commented on lib/public/SystemTag/ISystemTag.php
> +	public function getHumanReadableAccess(): string;
I've decided to go ahead and implement a constant-based solution, which feels much cleaner. Please check it out and tell me what you thing

2021-05-10 12:59 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +			static $accessLevelLookup = [
```suggestion
			$accessLevelLookup = [
```

2021-05-10 12:59 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +			static $accessLevelLookup = [
I would prefer to make `$accessLevelLookup` a class constant.

2021-05-10 12:59 UTC, kesselb commented on core/Command/SystemTag/Delete.php
> +			);
```suggestion
			);
    parent::configure();
```

2021-05-10 12:59 UTC, kesselb commented on core/Command/SystemTag/Edit.php
> +			);
```suggestion
			);
    parent::configure();
```

2021-05-10 13:12 UTC, noiob commented on core/Command/SystemTag/Delete.php
> +			);
Is it really a good idea to give Delete an `output` option that doesn't do anything?

2021-05-11 08:20 UTC, kesselb commented on core/Command/SystemTag/Add.php
> +			static $accessLevelLookup = [
A class constant of Add class as start. I'm also fine with keeping it a local variable as long as the static goes.

2021-05-11 08:31 UTC, kesselb commented on core/Command/SystemTag/Delete.php
> +			);
No ;)

2021-05-11 10:25 UTC, noiob commented on core/Command/SystemTag/Add.php
> +			$this->writeArrayInOutputFormat($input, $output,
yeah, that's probably better, I was just using the same format as `list`

2021-05-11 10:25 UTC, noiob commented on core/Command/SystemTag/Add.php
> +			static $accessLevelLookup = [
All right

2021-05-18 07:36 UTC, juliushaertl commented on tests/Core/Command/SystemTag/EditTest.php
> +			->with($tagId)
This test fails as tagId is undefined.

2021-05-18 07:37 UTC, juliushaertl commented on lib/public/SystemTag/ISystemTag.php
> +	public const ACCESS_LEVEL_PUBLIC = 0;
@noiob Could you maybe already add the `@since` annotation for those constants? We can then see to extend the since checker in a separate pr as I expect there are plenty of constants where this would be currently missing.

2021-05-18 09:19 UTC, noiob commented on tests/Core/Command/SystemTag/EditTest.php
> +			->with($tagId)
it doesn't fail for me, which is great, because it's obviously not correct

2021-05-20 17:40 UTC, noiob commented on lib/public/SystemTag/ISystemTag.php
> +	/**#@+
I didn't add those extra character by accident, they're so the docblock applies to all constants, not just the first one:
https://codingexplained.com/coding/php/how-to-use-docblock-templates-in-phpdoc

2021-05-20 18:23 UTC, kesselb commented on lib/public/SystemTag/ISystemTag.php
> +	/**#@+
please add per constant. Our checker does not support /**#@+.

```
/**
 * @since 22.0.0
 */
```

2021-05-20 18:25 UTC, kesselb commented on lib/public/SystemTag/ISystemTag.php
> +	/**#@+
or ignore it for now and remove the comments. we can still add it later ;)

2021-05-20 18:32 UTC, noiob commented on lib/public/SystemTag/ISystemTag.php
> +	/**#@+
I found it in other places in the code, so I assumed it was supported

2021-05-20 18:47 UTC, kesselb approved these changes
LGTM :+1: 

My other comments are only suggestions. Not required to get it in.

2021-05-20 18:47 UTC, kesselb commented on core/Command/SystemTag/Edit.php
> +			if ($input->getOption('name') !== null && $input->getOption('name') !== '') {
```suggestion
			if (!empty($input->getOption('name'))) {
```

2021-05-20 18:47 UTC, kesselb commented on core/Command/SystemTag/Edit.php
> +		} else {
It's possible to remove the else block to improve readability.

2021-05-20 18:48 UTC, kesselb commented
```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2021-05-25 14:48 UTC, kesselb commented
I've rebased the branch on master: https://github.com/nextcloud/server/pull/27101
The acceptance tests does not fail: https://drone.nextcloud.com/nextcloud/server/5321

2021-05-25 14:53 UTC, MorrisJobke approved these changes
Code looks good 👍

2021-05-25 14:54 UTC, merged