Add option to exclude groups from creating link shares
nextcloud/server pull request #26727
Opened 2021-04-23 18:31 UTC by icewind1991

I would have hoped to solve this in a more generic "per group share settings" way but the way the code base interacts with the share settings is to messy to do that without a lot of rework (this PR includes *some* improvement in this area).

2021-04-26 11:58 UTC, tobiasKaminsky commented
How is this then shown to clients?
Is then just files_sharing -> public -> enabled: false?
(in capabilities)
So nothing needs to be done/tested on clients?

2021-04-26 17:49 UTC, icewind1991 commented
Clients should see the same from the capabilities response as if link shares were completely disabled

2021-04-29 08:07 UTC, rullzer approved these changes
Does the trick for me!

2021-04-29 08:09 UTC, rullzer commented
However, linting, psalm and phpunit are not happy

2021-05-12 11:20 UTC, juliushaertl commented on apps/files/list.php
> +$publicUploadEnabled = $shareManager->shareApiLinkAllowPublicUpload();
I couldn't find any usage of the data attribute where this value is assigned to but from a compatibility perspective we should probably preserve the yes/no values here:

```suggestion
$publicUploadEnabled = $shareManager->shareApiLinkAllowPublicUpload() ? 'yes' : 'no';
```

2021-05-12 11:24 UTC, juliushaertl requested changes
Small comment, otherwise code looks good and works as expected :+1:

2021-05-12 11:59 UTC, juliushaertl approved these changes

2021-05-21 13:35 UTC, MorrisJobke commented
CI is happy :)

2021-05-21 13:35 UTC, merged