Fix occ db:convert-type, issue #26085
nextcloud/server pull request #26855
Opened 2021-05-01 21:57 UTC by hankjordan

When using occ db:convert-type, the command fails with the following message:

```
Only strings, Literals and Parameters are allowed
```

This pull request fixes the error and resolves issue #26085 using the original poster's proposed solution.

---

Signed-off-by: Henry Jordan <hank@henryjordan.com>

2021-05-01 22:01 UTC, hankjordan commented
Note to maintainers: DCO check is wrong. Commit messages are correct.

2021-05-03 09:40 UTC, eneiluj requested changes
Looks fine but I didn't try it.

2021-05-03 09:40 UTC, eneiluj commented on lib/private/DB/QueryBuilder/QuoteHelper.php
> +		if ($string instanceof \Doctrine\DBAL\Schema\Column) {
```suggestion
		if ($string instanceof Column) {
```

And Column could be imported on top:
``` php
use Doctrine\DBAL\Schema\Column;
```

2021-05-03 14:00 UTC, kesselb commented
https://github.com/nextcloud/server/blob/68c8fa8235094e84dbee978b6dc73c2c9034ea12/core/Command/Db/ConvertType.php#L337-L348

I think we should fix it there. addOrderBy should not accept a column object.

2021-05-11 12:07 UTC, MorrisJobke approved these changes

2021-05-11 12:31 UTC, kesselb commented
![image](https://user-images.githubusercontent.com/3902676/117815199-86539e00-b265-11eb-8dc7-70f650720a16.png)

To pass the DCO check. For more details: https://github.com/nextcloud/server/pull/26855/checks?check_run_id=2492874912

2021-05-29 15:44 UTC, fareszr commented
can confirm this fixed the issue

2021-06-09 07:12 UTC, closed without merging