Separate Email Logo
nextcloud/server pull request #26871
Opened 2021-05-04 14:16 UTC by brueckner

This PR adds the ability to upload a separate logo for notification emails. 

![Screenshot - Google Chrome Canary - 2021-05-04 at 15-11](https://user-images.githubusercontent.com/459512/117010177-d3c38e80-acec-11eb-9109-65fdd47808ba.png)

I basically copied most of the funtionality from the 'logo' upload field and added a fallback check in `apps/theming/lib/ThemingDefaults.php`. If no email logo is provided, the default logo will be used and if that's not present either, the default nextcloud logo will be used.

### Related Issues:
- [Svg logo does not display correctly in email #15930](#15930)
- [SVG-logo not displaying in emails due to wrong useSvg flag in html src-code #25984](#25984) (could use separate PNG logo for emails)
- [Generated PNG logo images in in activity emails are blurry #11162](#11162)
- [SVG logo URL embedded in emails return SVG content, despite useSvg=0 #13895](#13895)

### Kind of related:
- [Logo not correctly displayed in share mails in Outlook ##25463](#25463)

2021-05-25 11:13 UTC, brueckner commented
I noticed that I didn't properly link to the issues I mentioned above. I fixed all of them and would still love to get some feedback. 🙄

2021-05-26 13:25 UTC, skjnldsv commented on apps/theming/lib/ThemingDefaults.php
> +			}
A bit more comments on the code please? :)
Maybe something like

> Fallback to logo if there is no emailLogo registered

2021-05-26 13:26 UTC, skjnldsv reviewed
Looks good, but don't hesitate to comment the code a bit further, it makes it easier to get the context at glance

2021-05-27 16:07 UTC, juliushaertl requested changes
I'd generally be ok with adding a setting for this, but I'd pull in @jancborchardt here for some additional checking. :wink:

2021-05-27 17:05 UTC, jancborchardt commented
> I'd generally be ok with adding a setting for this, but I'd pull in @jancborchardt here for some additional checking. :wink: 

@brueckner @juliushaertl is it not possible to fix the SVG-to-PNG generation?

As usual having a setting means that every single person has to set this, whereas if we would fix the generator, that'd be a whole lot of work saved for our end users.

2021-05-31 08:21 UTC, brueckner commented on apps/theming/lib/ThemingDefaults.php
> +	public function getLogo($useSvg = true, $emailLogo = false): string {
That a very good point, thanks for bringing it up! I was actually thinking about that at first, but was afraid to get complains with regards to code duplication. However, having done the refactor now it feels much, much better and is totally worth a little duplication imho. Especially with regards to your other comment about the SVG - the new `getEmailLogo` doesn't have to be concerned with SVGs now. I'm just not sure how to restrict the email logo upload field to certain mime-types... 🤔  Any idea?

2021-05-31 08:21 UTC, brueckner commented on apps/theming/lib/ThemingDefaults.php
> +			}
The new refactor based on @juliushaertl suggestion to extract it into a new `getEmailLogo` function greatly simplified the code, aligning it with the original `getLogo` function, so I think no additional comments are needed there. You're right though, I should've added some comments in this case. 👌

2021-05-31 08:21 UTC, brueckner commented on apps/theming/lib/ImageManager.php
> +			case 'emailLogo':
Yep, you're absolutely right! The refactored version (see my other comment below) has no support for an SVG version.

2021-05-31 08:30 UTC, brueckner commented
> > I'd generally be ok with adding a setting for this, but I'd pull in @jancborchardt here for some additional checking. 😉
> 
> @brueckner @juliushaertl is it not possible to fix the SVG-to-PNG generation?
> 
> As usual having a setting means that every single person has to set this, whereas if we would fix the generator, that'd be a whole lot of work saved for our end users.

It's not (only) about the blurry appearance of the logo, as some users have described in other issues. It's much more about that fact that you might want to have a completly different logo for your emails that suits the styling of the mails sent out by Nextcloud. The idea is to use the regular logo by default, so people don't _have_ to use the setting at all, but this is part of a theming app that is supposed to offer customization, so offering some additional customization options won't hurt anyone I suppose. ;) 

Sidenote: the current (refactored) verison _doe's not_ fall back to the regular site logo (yet). I wanted to wait for some feedback on it before going the extra mile.

2021-06-23 14:47 UTC, szaimen commented
@jancborchardt so how to proceed with this then?

2021-09-13 12:51 UTC, szaimen commented
/rebase

2021-09-13 14:53 UTC, juliushaertl commented
Having different logos might also be interesting here in cases where the small rendering of the email logo does not work well with the one that is supposed at the login page. The header logo can already be set separately but the one on used the login page might be considered for larger use and have detail that don't work well on the small size of the mail.

2021-11-17 21:49 UTC, kowalski7cc commented
At this point, manifest icon override could be added as well (so we can have different icons for the web app shortcut)

2022-06-28 10:57 UTC, M3taKn1ght commented
What is the current Status?

2024-02-27 17:42 UTC, closed without merging