l10n: Replace the apostrophe with double quotation
nextcloud/server pull request #26896
Opened 2021-05-06 12:46 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-05-06 16:28 UTC, rakekniven requested changes
Changes for tests are needed to complete checks.

2021-05-07 09:52 UTC, Valdnet commented
@rakekniven Do you know where to change in the test?

2021-05-12 08:55 UTC, rullzer approved these changes
Fine by me

2021-05-12 09:16 UTC, rakekniven approved these changes

2021-05-18 06:44 UTC, merged