Removing useless call to external class
nextcloud/server pull request #26890
Opened 2021-05-05 22:38 UTC by daita

Redundant check done in the provider itself, useless in here

2021-05-07 07:20 UTC, skjnldsv approved these changes

2021-05-07 07:21 UTC, skjnldsv requested changes
Let's remove the lines?

2021-05-07 08:58 UTC, daita commented
> Let's remove the lines?

done, mb.

2021-05-07 09:45 UTC, skjnldsv approved these changes

2021-05-07 19:14 UTC, daita commented
squashed

2021-05-10 09:05 UTC, juliushaertl approved these changes

2021-05-10 09:06 UTC, juliushaertl commented
Psalm baseline needs an update https://github.com/nextcloud/server/pull/26890/checks?check_run_id=2530339318

2021-05-21 08:40 UTC, daita commented
> Psalm baseline needs an update https://github.com/nextcloud/server/pull/26890/checks?check_run_id=2530339318

looks good now

2021-05-21 13:14 UTC, MorrisJobke commented
let me fix psalm here and then this can be merged.

2021-05-21 13:16 UTC, MorrisJobke commented
Drone was green - only psalm was red: https://drone.nextcloud.com/nextcloud/server/5224

2021-05-21 13:34 UTC, MorrisJobke commented
Psalm is unhappy ... seems that the code was actually needed.

2021-05-22 13:37 UTC, daita commented
let's close this, I fixed the API on my side. This will be rewrite using an API included to Core in NC23 anyway

2021-05-22 13:37 UTC, closed without merging