Add S3 SSE KMS key and bucketked encryption
nextcloud/server pull request #26899
Opened 2021-05-06 15:27 UTC by tsdicloud

This is a replacement pull request for #26001 due to diverse rebase problems on the original request.

It also contains fixes for
- 'verify_bucket_exists' instead of 'autocreate' in S3 config #26093
- fclose(): supplied resource is not a valid stream resource #23373

Let´s try again. Sorry for the unconventional retry...

2021-05-07 07:48 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +	public function writeObject($urn, $stream) {
Most likely an uninteded change during the rebase, please keep the mimetype parameter here

2021-05-07 07:49 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +			'params' => $this->getSseKmsPutParameters(),
The mimetype should also be preserved here

2021-05-07 07:50 UTC, juliushaertl reviewed
The current commit seems to revert the additional mimetype parameter of the writeObject method which was added in #26575 with that change adjusted, tests should also pass.

Looks fine otherwise from my side :+1:

2021-05-07 08:11 UTC, tsdicloud commented
I am working on the incompatibility.

2021-05-11 13:59 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +	}
There seem to be an issue with the conditions here. I'd assume that if both are empty then an empty array is returned (for setups where not encryption is used). Shouldn't this be if **not** empty for the two branches?

2021-05-12 13:45 UTC, tsdicloud commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +	}
True. Missed that taking the right version over from our setup. Will fix

2021-05-12 16:58 UTC, tsdicloud commented
I cannot identify the php-cs-check problem. My dev setup does not show any fix for the corresponding files. Please help!

2021-05-12 22:08 UTC, blizzz commented
> I cannot identify the php-cs-check problem. My dev setup does not show any fix for the corresponding files. Please help!

That's unrelated to your code – a change sneaked in into master. If you rebase to the current, it won't appear anymore.

2021-05-17 07:46 UTC, juliushaertl approved these changes

2021-05-17 15:36 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +			return;
```suggestion
```

2021-05-17 15:36 UTC, kesselb commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +			$encrypt_state = $this->connection->getBucketEncryption([
$encrypt_state is unused.

2021-05-17 17:58 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> - *
This will most likely be re-added by the license script. So better not remove it in the first place to keep the changeset clean.

2021-05-17 17:58 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$this->id = 'amazon::'.$params['bucket'];
This is most likely why the code style CI job fails. We keep spaces around operators in our code style.

2021-05-17 17:58 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$params['hostname'] = empty($params['hostname']) ? 's3.'.$params['region'].'.amazonaws.com' : $params['hostname'];
Same code style issue.

2021-05-17 18:06 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		if (isset($params['ssekmsbucketkeyid'])) {
This should be documented in "admin_manual/configuration_files/primary_storage.rst" of the documentation.

2021-05-17 18:06 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		} elseif (isset($params['ssekmskeyid'])) {
This should be documented in "admin_manual/configuration_files/primary_storage.rst" of the documentation.

2021-05-17 18:07 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$logger = \OC::$server->getLogger();
I don't fully like that approach but as this is a trait I have no other good idea how to properly inject this dependency. Maybe @ChristophWurst has an idea, otherwise this should be fine.

2021-05-17 18:07 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +			$logger->info('Bucket "'.$this->bucket.'" does not exist - creating it.', ['app' => 'objectstore']);
```suggestion
			$logger->info('Bucket "' . $this->bucket . '" does not exist - creating it.', ['app' => 'objectstore']);
```

2021-05-17 18:07 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +				throw new \Exception('The bucket will not be created because the name is not dns compatible, please correct it: '.$this->bucket);
```suggestion
				throw new \Exception('The bucket will not be created because the name is not dns compatible, please correct it: ' . $this->bucket);
```

2021-05-17 18:08 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +			throw new \Exception('Creation of bucket "'.$this->bucket.'" failed. '.$e->getMessage());
```suggestion
			throw new \Exception('Creation of bucket "' . $this->bucket . '" failed. ' . $e->getMessage());
```

2021-05-17 18:08 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +				$logger->info('Bucket key for "'.$this->bucket.'" is not set - adding it.', ['app' => 'objectstore']);
```suggestion
				$logger->info('Bucket key for "' . $this->bucket . '" is not set - adding it.', ['app' => 'objectstore']);
```

2021-05-17 18:08 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +				throw new \Exception('Putting configured bucket key to "'.$this->bucket.'" failed. '.$e->getMessage());
```suggestion
				throw new \Exception('Putting configured bucket key to "' . $this->bucket . '" failed. ' . $e->getMessage());
```

2021-05-17 18:09 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$base_url = $scheme.'://'.$this->params['hostname'].':'.$this->params['port'].'/';
Same code style issue.

2021-05-17 18:09 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +			$logger->debug('Bucket "'.$this->bucket.'" This bucket name is not dns compatible, it may contain invalid characters.',
Same code style issue.

2021-05-17 18:10 UTC, MorrisJobke commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> - *
Same as above

2021-05-17 18:13 UTC, MorrisJobke requested changes
Mostly code style nitpicks. Beside that it looks good 👍

2021-05-17 18:19 UTC, tsdicloud commented
Thanks for all the code hints. We will change this soon. But we found today a conceptual issue with bucket keys and default keys that may are used as a replacement. Also, we don´t need to send kms:id on read. Thus, we also need a little re-work of functionality and handling. Update will follow,.

2021-06-16 13:33 UTC, blizzz commented
Moving to  23 as we're in freeze and the last beta is just ahead

2021-06-16 13:36 UTC, ChristophWurst commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$logger = \OC::$server->getLogger();
:shrug:

2021-08-26 07:05 UTC, closed without merging