Let apps toggle an unread counter on app icons
nextcloud/server pull request #26939
Opened 2021-05-11 06:31 UTC by juliushaertl

![image](https://user-images.githubusercontent.com/3404133/121491586-60d9c180-c9d6-11eb-8594-6fb2c016b456.png)

The count value is currently hidden as we don't want to clutter the UI too much, but might be useful at some point.

It can either be updated during page load through the navigation manager `$navigationManager->setUnreadCounter('activity', 10);` or through JavaScript by calling `OC.setNavigationCounter('deck', 123)`

2021-05-11 06:33 UTC, juliushaertl commented on core/src/components/MainMenu.js
> +		setNavigationCounter(id, counter) {
I'm a bit undecided on the approach to take here, maybe we should rather listen to an event that might be emitted then by the apps through the event bus?

2021-05-11 06:57 UTC, ChristophWurst commented on core/src/components/MainMenu.js
> +		setNavigationCounter(id, counter) {
I'd advocate against the global variable approach, at least form an app API perspective. We can hide this in yet another `@nextcloud/xyz` package or add it to an existing one. Then we can also later on change the way this action propagates from an app to the server component.

2021-06-02 17:11 UTC, blizzz commented
what's the state here? moving to 23?

2021-06-10 08:32 UTC, juliushaertl commented on core/src/components/MainMenu.js
> +		setNavigationCounter(id, counter) {
OK, then lets keep the OC.setNavigationCounter for use in the additional package then which we then can use for offering a stable API. Unfortunately I don't think we have any fitting package for that already so it would need an additional one.

2021-06-10 08:39 UTC, juliushaertl commented
Ready review, we'd still need this for 22.

2021-06-10 11:21 UTC, blizzz commented
CI is unhappy

2021-06-10 11:39 UTC, artonge requested changes

2021-06-10 11:39 UTC, artonge commented on core/src/components/MainMenu.js
>  	// init the more-apps menu
Maybe cleaner ? But not tested.

```suggestion
			const appmenuElement = document.getElementById('appmenu').querySelector('[data-id="' + id + '"] svg')
			const appsElement = document.getElementById('apps').querySelector('[data-id="' + id + '"] svg')

			if (counter === 0) {
				appmenuElement.classList.remove('has-unread')
				appsElement.classList.remove('has-unread')
				appmenuElement.getElementsByTagName('image')[0].style.mask = ''
				appsElement.getElementsByTagName('image')[0].style.mask = ''

			} else {
				appmenuElement.classList.add('has-unread')
				appsElement.classList.add('has-unread')
				appmenuElement.getElementsByTagName('image')[0].style.mask = 'url(#hole)'
				appsElement.getElementsByTagName('image')[0].style.mask = 'url(#hole)'
			}

			appmenuElement.querySelector('.unread-counter').textContent = counter
			appsElement.querySelector('.unread-counter').textContent = counter
```

2021-06-15 19:46 UTC, juliushaertl commented on core/src/components/MainMenu.js
>  	// init the more-apps menu
Thanks, yes a bit nicer :)

Pushed without the last two lines as they only use the parent element.

2021-06-16 08:46 UTC, artonge approved these changes

2021-06-16 09:43 UTC, jancborchardt approved these changes
:+1: design-wise :)

2021-06-16 09:46 UTC, juliushaertl commented
Pushed another fix for the tests, waiting for CI to pass

2021-06-16 11:18 UTC, skjnldsv approved these changes

2021-06-16 13:35 UTC, blizzz commented
CI is unhappy

2021-06-17 01:26 UTC, Pytal approved these changes

2021-06-17 11:33 UTC, merged