Use MultipartUpload for uploading chunks to s3
nextcloud/server pull request #27034
Opened 2021-05-19 16:54 UTC by juliushaertl

This is a first attempt in getting some code to work on having chunked upload streaming the chunks directly to S3 so that the final MOVE request no longer needs to assemble the final file on the Nextcloud server.

Additional requirements on top of the current chunking API in order to trigger it:
1. Header `X-Nextcloud-Object-Chunking: 1` on each request
2. Header `X-Nextcloud-Object-Destination: files/user1/path/to/file.bin` on each request
  - required in order to be able to write to an already existing file without changing its file id as we need the urn oid when starting the multipart upload
3. Name of the chunk needs to be numeric between 1 and 10000
4. Each chunk must be between 5MB and 5GB (just the last can be of any size)

## How it currently works

- MKCOL The existing UploadFolder is still created
  - The MultipartUpload is initiated with either the existing file id or with a new temporary file .multipart in the UploadFolder
- The S3 UploadID and the results (ETag/PartId tuple) is stored in the DAV properties for the individual chunks)
- On MOVE the MultipartUpload will be completed and then either the filecache for the existing file is updated or for new files the uploaded object will be moved to the final location in the filecache only

<details>
<summary>New chunk upload test script</summary>

```
#!/bin/bash

FILENAME=$1
CHUNKSIZE=10
CHUNKS=$(seq 1 2)
TARGETPATH=""
SERVER=https://nextcloud.local
USER=admin
PASS=admin

for i in $CHUNKS; do
	dd if=/dev/random of=$i.bin bs=${CHUNKSIZE}M count=1 2>/dev/null
done

> local.bin
for i in $CHUNKS; do
	cat $i.bin >> local.bin
done

checkdl() {
	curl -s -u $USER:$PASS $SERVER/remote.php/dav/files/$USER/${TARGETPATH}${FILENAME} >download.bin
	md5sum local.bin
	md5sum download.bin
	if cmp -s "local.bin" "download.bin"; then
		echo "✅"
	else
		echo "❌"
	fi
}

checkdl
echo "MKCOL"
curl -X MKCOL -u $USER:$PASS $SERVER/remote.php/dav/uploads/$USER/chunk-asdfghj-$FILENAME -H 'Cookie: XDEBUG_SESSION=PHPSTORM' -H 'X-Nextcloud-Object-Chunking: 1' -H "X-Nextcloud-Object-Destination: files/${USER}/${TARGETPATH}${FILENAME}"

for i in $CHUNKS; do
	echo "PUT chunk " $(printf "%05d\n" $i)
	curl -X PUT -u $USER:$PASS $SERVER/remote.php/dav/uploads/$USER/chunk-asdfghj-$FILENAME/$(printf "%05d\n" $i) -T $i.bin -H 'Cookie: XDEBUG_SESSION=PHPSTORM' -H 'X-Nextcloud-Object-Chunking: 1' -H "X-Nextcloud-Object-Destination: files/${USER}/${TARGETPATH}${FILENAME}"
done

echo "MOVE"
time curl -X MOVE -u $USER:$PASS --header "Destination:$SERVER/remote.php/dav/files/$USER/${TARGETPATH}$FILENAME" $SERVER/remote.php/dav/uploads/$USER/chunk-asdfghj-$FILENAME/.file -H 'Cookie: XDEBUG_SESSION=PHPSTORM' -H 'X-Nextcloud-Object-Chunking: 1' -H "X-Nextcloud-Object-Destination: files/${USER}/${TARGETPATH}${FILENAME}"

checkdl

```
</details>

## Current issues

- Abstraction wise this seems like way to much object storage specific handling in the dav app code but as of now I cannot think of a proper way for a more generic API that could become part of the storage
- Metadata storage
  - Placeholder chunk files still create objects on the storage
  - DAV Properties are not properly cleaned up
  - Possible solution: We'd need a rather persistent way to store current uploads as well as their individual part results, so the only alternative would be to add a dedicated table for that
    - Doing that would probably help with abstracting the chunk handling a bit more away into the ObjectStorageStore
- Moving the final file
  - As the whole View and Storage code is based writing files based on streams I don't see a way to trigger the file creation or moving the new data into place through the existing storage APIs and I generally would prefer to keep the code then bundled in the new Chunking plugin rather than distributing it across DAV, file view and storage classes
- As new files are currently stored in the uploads directory of the user this approach does not yet work with multibucket setups where the destination is located on a different bucket than the uploading users home

2021-07-09 09:15 UTC, juliushaertl commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		$result = $this->objectStore->uploadMultipartPart($urn, $uploadId, (int)$chunkId, $data, $size);
`$uploadId` might be null here.

```
{
  "Code": 0,
  "CustomMessage": "--",
  "Exception": "TypeError",
  "File": "/var/www/nextcloud/lib/private/Files/ObjectStore/S3.php",
  "Line": 60,
  "Message": "OC\\Files\\ObjectStore\\S3::uploadMultipartPart(): Argument #2 ($uploadId) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php on line 641",
  "Trace": [
    {
      "class": "OC\\Files\\ObjectStore\\S3",
      "file": "/var/www/nextcloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php",
      "function": "uploadMultipartPart",
      "line": 641,
      "type": "->"
    },
    {
      "class": "OC\\Files\\ObjectStore\\ObjectStoreStorage",
      "function": "putChunkedFilePart",
      "type": "->"
    },
    {
      "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "function": "call_user_func_array",
      "line": 509
    },
    {
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "function": "__call",
      "type": "->"
    },
    {
      "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "function": "call_user_func_array",
      "line": 509
    },
    {
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "function": "__call",
      "type": "->"
    },
    {
      "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
      "function": "call_user_func_array",
      "line": 509
    },
    {
      "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
      "file": "/var/www/nextcloud/apps/dav/lib/Upload/ChunkingV2Plugin.php",
      "function": "__call",
      "line": 142,
      "type": "->"
    },
    {
      "class": "OCA\\DAV\\Upload\\ChunkingV2Plugin",
      "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
      "function": "beforePut",
      "line": 89,
      "type": "->"
    },
    {
      "class": "Sabre\\DAV\\Server",
      "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
      "function": "emit",
      "line": 456,
      "type": "->"
    },
    {
      "class": "Sabre\\DAV\\Server",
      "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
      "function": "invokeMethod",
      "line": 253,
      "type": "->"
    },
    {
      "class": "Sabre\\DAV\\Server",
      "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
      "function": "start",
      "line": 321,
      "type": "->"
    },
    {
      "class": "Sabre\\DAV\\Server",
      "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
      "function": "exec",
      "line": 336,
      "type": "->"
    },
    {
      "class": "OCA\\DAV\\Server",
      "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
      "function": "exec",
      "line": 36,
      "type": "->"
    },
    {
      "args": [
        "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
      ],
      "file": "/var/www/nextcloud/remote.php",
      "function": "require_once",
      "line": 167
    }
  ]
}
```

2021-07-09 09:20 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		$uploadId = $properties[self::OBJECT_UPLOAD_CHUNKTOKEN];
```
Undefined array key \"{http://nextcloud.org/ns}upload-target\" at /var/www/nextcloud/apps/dav/lib/Upload/ChunkingV2Plugin.php
Undefined array key \"{http://nextcloud.org/ns}upload-chunktoken\" at /var/www/nextcloud/apps/dav/lib/Upload/ChunkingV2Plugin.php
```

2021-07-09 09:20 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		$targetFile = $this->getTargetFile($targetPath);
with https://github.com/nextcloud/server/pull/27034/files#r666805510:
```
OCA\\DAV\\Upload\\ChunkingV2Plugin::getTargetFile(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/apps/dav/lib/Upload/ChunkingV2Plugin.php on line 140
```

2021-09-14 18:38 UTC, juliushaertl commented
@nextcloud/server-backend I didn't get that far in finishing this as expected, but some intermediate feedback on the approach with the storage abstraction and the chunking plugin would already be much appreciated.

2022-01-26 11:25 UTC, AndyScherzinger commented
/backport to stable-23

2022-01-26 11:25 UTC, AndyScherzinger commented
/backport to stable-22

2022-01-28 07:11 UTC, skjnldsv commented
/backport to stable22

2022-01-28 07:11 UTC, skjnldsv commented
/backport to stable23

2022-05-10 09:11 UTC, skjnldsv commented
/backport to stable24

2022-06-12 14:04 UTC, juliushaertl commented
@PVince81 This should be good for a first review round now. Failing integration tests on s3 have been tagged so we can look into them separately as they are not really related to this PR.

2022-06-17 14:22 UTC, PVince81 commented
@CarlSchwan @icewind1991 @artonge please review

2022-06-21 14:27 UTC, artonge commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	protected function sanitizeMtime($mtimeFromRequest) {
Could be replaced with https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/MtimeSanitizer.php, I think

2022-06-21 14:27 UTC, artonge commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		return $urn . '-' . $uploadId . '-' . ($key ? $key . '-' : '');
```suggestion
 		return $urn . '-' . $uploadId . ($key ? '-' . $key : '');
```

2022-06-21 14:40 UTC, artonge commented
Just tested with a 2Go file, and it works great!

2022-06-22 15:46 UTC, icewind1991 requested changes

2022-06-22 15:46 UTC, icewind1991 commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	private const DESTINATION_HEADER = 'X-S3-Multipart-Destination';
Tying the naming of this to S3 seem unnecessary and specifying the destination might be useful for non-s3 in the future.

2022-06-22 15:46 UTC, icewind1991 commented on apps/dav/lib/Capabilities.php
> +				's3-multipart' => $rootStorage->instanceOfStorage(ObjectStoreStorage::class) && $rootStorage->getObjectStore() instanceof IObjectStoreMultiPartUpload,
since there is no downside to just always setting the target header it would make sense imo to just always tell clients to send it

2022-06-22 15:46 UTC, icewind1991 commented on lib/private/Files/View.php
> +	public function writeChunkedFile(string $path, string $chunkToken) {
I would prefer not to add new methods to the old filesystem api and use the `Node` api only for new things

2022-06-22 15:48 UTC, icewind1991 commented
The reason for asking the client to give the target path in advance is to avoid having to do a rename (which S3 doesn't do natively) to the final path right?

It would still make sense to use S3 multipart even if when the client doesn't give the target path since the S3-internal copy needed to rename the file will still be faster than the current "assemble on final move".

2022-08-29 10:36 UTC, PVince81 commented
@juliushaertl can you address the review comments ?

2022-09-03 00:07 UTC, furrykef commented
I'm trying to use this branch, but it's not working for me. I try uploading a file and it apparently aborts after uploading 10 MB. There is no message, no partially completed file (either in Nextcloud's file view or in the back end), no nothing. If it helps, we're using Wasabi for our storage; there might be some kind of incompatibility (see https://wasabi-support.zendesk.com/hc/en-us/articles/360030872392-How-does-Wasabi-handle-multipart-uploads- ).

2022-09-24 14:17 UTC, furrykef commented
I'm disappointed to see this won't make it into Nextcloud 25. We're having [problems with uploading large files](https://help.nextcloud.com/t/several-issues-with-uploading-large-files-80-mib-to-s3-primary-storage/144956) and were hoping this would fix it. Our alternatives appear to be to use Nextcloud 23 or not use Nextcloud at all.

2022-10-27 08:22 UTC, tobiasKaminsky commented
For test: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html#simple-storage-service-s3

2022-10-27 08:43 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		$storage->putChunkedFilePart($targetFile->getInternalPath(), $uploadId, (string)$partId, $stream, $additionalSize);
- [ ] Check how S3 behaves in regards to listing the chunks when a chunk was only partly uploaded

2022-10-27 08:43 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	public function beforeMove($sourcePath, $destination): bool {
- [ ] Make sure that we don't require the header here so clients can keep their existing MOVE handling

2023-02-06 08:13 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	private const DESTINATION_HEADER = 'X-S3-Multipart-Destination';
Indeed, I moved this to just use the general Destination header on all request.

2023-02-06 08:15 UTC, juliushaertl commented on lib/private/Files/View.php
> +	public function writeChunkedFile(string $path, string $chunkToken) {
I refactored a bit to make mostly use of the node api from the chunking plugin. However needs some duplication on emitting legacy hooks as those are currently always triggered through the View or duplicated in dav app code.

2023-02-06 08:17 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +			$storage->processingCallback('writeChunkedFile', function () use ($lastTick) {
The idea was to keep connections open by sending spaces before the MOVE is finished. However I dropped this logic for now as the move request seem fast enough and this adds quite some complexity on top of it.

If we need some deferral mechanism like this we should consider it later maybe in a more generic way.

2023-02-06 08:29 UTC, juliushaertl commented
> The reason for asking the client to give the target path in advance is to avoid having to do a rename (which S3 doesn't do natively) to the final path right?

> It would still make sense to use S3 multipart even if when the client doesn't give the target path since the S3-internal copy needed to rename the file will still be faster than the current "assemble on final move".

We need some kind of enabler flag (which is now the Destination header on the MKCOL request since chunk names are now enforced to be numeric (between 1 and 10.000). With previous chunked upload implementations it could be any name that was sortable in the right order.

2023-03-03 15:53 UTC, icewind1991 commented on apps/dav/lib/Connector/Sabre/Node.php
> +	public function getAbsoluteInternalPath(): string {
"absolute" and "internal" are mutually exclusive, did you mean `getAbsolutePath`

2023-03-03 15:53 UTC, icewind1991 commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		$this->cache = \OCP\Server::get(ICacheFactory::class)->createDistributed(self::CACHE_KEY);
inject `ICacheFactory`?

2023-03-03 15:53 UTC, icewind1991 commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		}
what is the reason for the extra object store specific quota calculation here? we already check quota when uploading parts

2023-03-07 07:37 UTC, juliushaertl commented on apps/dav/lib/Connector/Sabre/Node.php
> +	public function getAbsoluteInternalPath(): string {
Removed as it was unused anyways

2023-03-07 07:37 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		$partId = (int)basename($request->getPath());
No, thanks for catching this. Addressed.

2023-03-07 07:38 UTC, juliushaertl commented on apps/dav/lib/Capabilities.php
>  		if ($this->config->getSystemValueBool('bulkupload.enabled', true)) {
Right, the capability is no longer needed as we are backward compatible now with the old upload mechanism

2023-03-08 12:07 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +		}
Mainly an extra safety check since it could happen that there was enough space during the upload of the parts but when putting the final file into place the quota exceeded.

2023-03-09 10:41 UTC, blizzz approved these changes
No blockers encountered, some suggestions nevertheless. If they are not consider for this PR, there should be a at least a follow up, please.

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	public function beforeDelete(RequestInterface $request, ResponseInterface $response) {
```suggestion
	public function beforeDelete(RequestInterface $request, ResponseInterface $response): bool {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +	public function prepareUpload($path): void {
```suggestion
	public function prepareUpload(string $path): void {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/FutureFile.php
> +	public function getPath() {
```suggestion
	public function getPath(): string {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/PartFile.php
> + * @author Thomas Müller <thomas.mueller@tmit.eu>
is it?

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/PartFile.php
> +	private $root;
```suggestion
	private Directory $root;
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/PartFile.php
> +	private $partInfo;
```suggestion
	/** @var _____[] */
	private array $partInfo;
```

array of what actually? Something from AWS i suppose.

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/PartFile.php
> +	public function getPath() {
```suggestion
	public function getPath(): string {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadFile.php
> +	public function getId() {
```suggestion
	public function getId(): int {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadFile.php
> +	public function getNode() {
```suggestion
	public function getNode(): File {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadFolder.php
> +	private $storage;
```suggestion
	private IStorage $storage;
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadFolder.php
> +				$cache = \OC::$server->getMemCacheFactory()->createDistributed(ChunkingV2Plugin::CACHE_KEY);
`getMemCacheFactory` is deprecated

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadFolder.php
> +	public function getStorage() {
```suggestion
	public function getStorage(): IStorage {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadHome.php
> +		$view = $this->getView();
return type hint?

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadHome.php
> +	private function getView() {
```suggestion
	private function getView(): View {
```

2023-03-09 10:41 UTC, blizzz commented on apps/dav/lib/Upload/UploadHome.php
> +	private function getStorage() {
```suggestion
	private function getStorage(): IStorage {
```

2023-03-09 10:41 UTC, blizzz commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		$result = $this->objectStore->uploadMultipartPart($urn, $writeToken, (int)$chunkId, $data, $size);
casting to int is safe here? (I bet it is, there is much known knowledge assumed in various parts)

2023-03-09 10:41 UTC, blizzz commented on lib/public/Files/ObjectStore/IObjectStoreMultiPartUpload.php
> + * @copyright Copyright (c) 2021 Julius Härtl <jus@bitgrid.net>
2023?

2023-03-09 10:41 UTC, blizzz commented on lib/public/Files/ObjectStore/IObjectStoreMultiPartUpload.php
> +	public function getMultipartUploads(string $urn, string $uploadId): array;
worth to document what's inside that array?

2023-03-09 10:41 UTC, blizzz commented on lib/public/Files/Storage/IChunkedFileWrite.php
> + * @copyright Copyright (c) 2021 Julius Härtl <jus@bitgrid.net>
2023?

2023-03-09 10:41 UTC, blizzz commented on lib/public/Files/Storage/IChunkedFileWrite.php
> +	public function putChunkedWritePart(string $targetPath, string $writeToken, string $chunkId, $data, int $size = null): ?array;
worth to document what's inside that array?

2023-03-09 12:14 UTC, blizzz commented
> No blockers encountered, some suggestions nevertheless. If they are not consider for this PR, there should be a at least a follow up, please.

As discussed with Julius, my annotations will be reflected in a follow up PR. 

Second reviewer needed.

2023-03-09 12:55 UTC, come-nc approved these changes

2023-03-09 12:55 UTC, come-nc commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +			return true;
log the exception at least in debug?

2023-03-09 12:55 UTC, come-nc commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +				throw new InsufficientStorage("Insufficient space in $this->uploadPath");
```suggestion
				throw new InsufficientStorage("Insufficient space in {$this->uploadPath}");
```
(personal readability preference, anything more complex than $var should go into {})

2023-03-09 12:55 UTC, come-nc commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +			return true;
log exception

2023-03-09 12:55 UTC, come-nc commented on lib/public/Files/ObjectStore/IObjectStoreMultiPartUpload.php
> +declare(strict_types=1);
It’s before copyright in other files, better to move it there for consistency

2023-03-09 12:55 UTC, come-nc commented on lib/public/Files/Storage/IChunkedFileWrite.php
> +declare(strict_types=1);
same

2023-03-09 12:55 UTC, merged

2023-03-09 12:56 UTC, blizzz commented
/backport to stable26

2023-03-09 13:47 UTC, juliushaertl commented on apps/dav/lib/Upload/ChunkingV2Plugin.php
> +			self::UPLOAD_TARGET_ID => $targetFile->getId(),
It will only be UploadFile|File which both have it, will adjust with the above type hint of getUploadFile

2023-03-09 15:15 UTC, pierreozoux commented
:rocket: 

This is amazing :) Thanks!

(hope it is ok to "pollute" github PR with praising :) it is easy to complain about bugs, but we should also learn to celebrate  :) )

2023-03-09 18:38 UTC, ir0nhide commented
@juliushaertl great work, thank you very much!
Looking at the newly added code in https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/S3.php, i am wondering if it is also required to add SSE-C headers here like done in e.g. https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/S3ObjectTrait.php#L62 to support https://github.com/nextcloud/server/pull/32798 with multipart upload?

2023-03-10 08:58 UTC, juliushaertl commented
> @juliushaertl great work, thank you very much!
> Looking at the newly added code in [`master`/lib/private/Files/ObjectStore/S3.php](https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/S3.php?rgh-link-date=2023-03-09T18%3A38%3A48Z), i am wondering if it is also required to add SSE-C headers here like done in e.g. [`master`/lib/private/Files/ObjectStore/S3ObjectTrait.php#L62](https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/S3ObjectTrait.php?rgh-link-date=2023-03-09T18%3A38%3A48Z#L62) to support #32798 with multipart upload?

Thanks, good catch indeed. I'll take care of that in the follow up.

2023-07-06 10:56 UTC, unteem commented
Awesome feature :) ! Thanks a lot

Are there any reasons for it not being backported to v25 ?

2023-07-06 10:57 UTC, AndyScherzinger commented
We usually only backport security fixes or critical bugfixes. Any kind of performance improvement as well as features gets pinned to the upcoming major release.