l10n: Spelling unification
nextcloud/server pull request #27063
Opened 2021-05-21 13:46 UTC by Valdnet

Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-05-24 09:36 UTC, rakekniven requested changes

2021-05-24 09:36 UTC, rakekniven commented on apps/updatenotification/src/components/UpdateNotification.vue
> +				return t('updatenotification', 'Could not connect to the App Store or returned no updates at all. Search manually for updates or make sure your server has access to the internet and can connect t
'Could not connect to the App Store or no updates have been returned at all.'

2021-05-24 09:42 UTC, rakekniven approved these changes

2021-05-25 08:35 UTC, MorrisJobke commented
/compile /

2021-05-25 08:35 UTC, MorrisJobke commented
@jospoortvliet Fine with you?

2021-05-25 08:35 UTC, MorrisJobke approved these changes

2021-05-25 19:07 UTC, gary-kim approved these changes

2021-05-25 19:10 UTC, MorrisJobke commented
/compile /

2021-06-01 10:06 UTC, Valdnet commented
@nickvergessen Can you merge it 😉?

2021-06-02 10:07 UTC, Valdnet commented
@nickvergessen So what are we doing with it?

2021-06-02 15:55 UTC, merged