[WIP] Dont allow reusing usernames
nextcloud/server pull request #27105
Opened 2021-05-25 19:23 UTC by LukasReschke

We have cases in which app developers forget to delete user data when a user is being deleted. This could be problematic as future users with the same username could then access this data.

This mitigates this risk a bit by not allowing reusing of usernames. That said, we still need to fix occurrences of these issues by deleting missed data.

# TODOs 

- [ ] Adjust DI for Manager
- [ ] Fix up code
- [ ] Listen to user deletion event and mark user name as used

2021-05-25 19:23 UTC, LukasReschke commented on .htaccess
> +ErrorDocument 404 /
```suggestion
```

2021-05-25 19:23 UTC, LukasReschke commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @deprecated 22.0.0 Use executeQuery or executeStatement
```suggestion
	 * @deprecated 22.0.0 Use executeQuery or executeUpdate
```

2021-05-25 19:26 UTC, LukasReschke commented on lib/private/User/Manager.php
> +
```suggestion

```

2021-05-25 19:51 UTC, nickvergessen commented on lib/private/User/UsernameDuplicationPreventionManager.php
> +	private const TABLE_NAME = 'previously_used_usernames';
```suggestion
	private const TABLE_NAME = 'previously_used_userids';
```

2021-05-25 19:52 UTC, nickvergessen commented on lib/private/User/UsernameDuplicationPreventionManager.php
> +		$result = $queryBuilder->select($queryBuilder->createFunction('COUNT(*)'))
```suggestion
		$result = $queryBuilder->select($queryBuilder->func()->count())
```

2021-05-25 20:38 UTC, LukasReschke commented on core/Migrations/Version22000Date20210525173326.php
> +		$table = $schema->createTable('previously_used_usernames');
```suggestion
		$table = $schema->createTable('previously_used_userids');
```

2021-05-25 20:46 UTC, nickvergessen requested changes

2021-05-25 20:46 UTC, nickvergessen commented on core/Migrations/Version22000Date20210525173326.php
> +		$table->addUniqueIndex(['user_id_hash'], 'user_id_hash');
Table needs a primary key. But you can use this column

2021-05-31 19:38 UTC, nickvergessen commented on apps/dav/tests/unit/Connector/Sabre/FileTest.php
> +		$this->user = 'test_user' . uniqid('', true);
```suggestion
		$this->user = self::getUniqueID('test_user');
```

2021-05-31 19:38 UTC, nickvergessen commented on apps/dav/tests/unit/Connector/Sabre/FileTest.php
> +		$this->user = 'test_user' . uniqid('', true);
same on the others

2021-05-31 19:40 UTC, nickvergessen commented on apps/files_sharing/tests/TestCase.php
> +		$this->TEST_FILES_SHARING_API_USER4 = $this->TEST_FILES_SHARING_API_USER4 . uniqid("", true);
also here

2021-05-31 19:42 UTC, nickvergessen commented on core/Migrations/Version22000Date20210525173326.php
> +		$table->setPrimaryKey(['user_id_hash'], 'uid_hash_idx');
```suggestion
		if (!$schema->hasTable('previously_used_userids')) {
			$table = $schema->createTable('previously_used_userids');

			$table->addColumn('user_id_hash', \OCP\DB\Types::STRING, [
				'notnull' => true,
				'length' => 128,
			]);

			$table->setPrimaryKey(['user_id_hash'], 'uid_hash_idx');
		}
```

2021-05-31 19:42 UTC, nickvergessen commented on core/Migrations/Version22000Date20210525173326.php
> +		$table->setPrimaryKey(['user_id_hash'], 'uid_hash_idx');
yes

2021-05-31 19:42 UTC, nickvergessen commented on lib/private/User/Manager.php
> +			throw new HintException($l->t("The user name has already been used previously."));
```suggestion
			throw new HintException($l->t('The user name has already been used previously.'));
```

2021-05-31 19:44 UTC, nickvergessen commented on tests/lib/AppTest.php
> +		} else if ($user === 'user2-') {
```suggestion
		} elseif ($user === 'user2-') {
```

2021-05-31 19:45 UTC, nickvergessen commented on tests/lib/AppTest.php
> +		} else if ($user === 'user3-') {
```suggestion
		} elseif ($user === 'user3-') {
```

2021-05-31 19:46 UTC, nickvergessen commented on tests/lib/User/UserDeletedListenerTest.php
> +		/** @var UsernameDuplicationPreventionManager|PHPUnit_Framework_MockObject_MockObject $usernameDuplicationPreventionManager */
```suggestion
		/** @var UsernameDuplicationPreventionManager|MockObject $usernameDuplicationPreventionManager */
```

and import the namespaces version

2021-05-31 19:47 UTC, nickvergessen approved these changes
Looks good, little bit of cleanup and good to go

2021-06-04 07:44 UTC, nickvergessen approved these changes

2021-06-04 07:45 UTC, nickvergessen commented
Should put into https://github.com/nextcloud/server/issues/26407 as I guess this will break the tests of a lot of apps :-X

2021-06-04 07:45 UTC, nickvergessen commented
There was 1 error:

1) OCA\Files_Sharing\Tests\External\ManagerTest::testAddShare
TypeError: Argument 1 passed to OCA\Files_Sharing\External\MountProvider::getMountsForUser() must implement interface OCP\IUser, null given, called in /home/runner/work/server/server/apps/files_sharing/tests/External/ManagerTest.php on line 139

/home/runner/work/server/server/apps/files_sharing/lib/External/MountProvider.php:75
/home/runner/work/server/server/apps/files_sharing/tests/External/ManagerTest.php:139
/home/runner/work/server/server/apps/files_sharing/tests/External/ManagerTest.php:174

2024-08-14 10:17 UTC, closed without merging