Fix Oracle query limit compliance in Comments
nextcloud/server pull request #27187
Opened 2021-05-27 11:17 UTC by Simounet

Hi there,
Resolving one more issue about Oracle query limit (#25036) on Nextcloud comments queries.
Could resolve #26493 and related to #4947.
Have a nice day and stay safe.

2021-05-27 14:13 UTC, andyxheli commented
@ChristophWurst @rullzer When you get a chance can you please review :)

2021-05-27 14:21 UTC, MorrisJobke approved these changes
Code looks good 👍

2021-05-27 15:22 UTC, blizzz requested changes

2021-05-27 15:22 UTC, blizzz commented on lib/private/Comments/Manager.php
> +			$result = $query->execute();
Am I wrong, or is only the last result set handled? Since this is always overwritten, but not processed here.

2021-05-27 15:26 UTC, Simounet commented on lib/private/Comments/Manager.php
> +			$result = $query->execute();
You're right. I should include the following lines with the `while`  using the `$result->fetch()`.

2021-05-27 23:02 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			$query = $this->dbConn->getQueryBuilder();
Do this once and only set the parameter in the loop

2021-05-28 08:31 UTC, ChristophWurst approved these changes
Didn't test but code looks good

2021-05-28 09:19 UTC, MorrisJobke commented
Failure is unrelated and a regression on master -> merge

2021-05-28 09:19 UTC, merged

2021-05-28 09:21 UTC, MorrisJobke commented
/backport to stable21

2021-05-28 11:24 UTC, MorrisJobke commented
/backport to stable21

2021-06-01 19:22 UTC, andyxheli commented
Once i added the changes that @nickvergessen implanted the server stopped working  Fix populating the array and closing the cursors #27316

{"reqId":"IaCrQFzY4jvDY9zBZ77j","level":4,"time":"2021-06-01T19:16:58+00:00","remoteAddr":"0.0.0.0","user":"admin","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/admin/","message":{"Exception":"Error","Message":"Call to undefined method OC\\DB\\QueryBuilder\\QueryBuilder::executeQuery()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":89,"function":"getNumberOfUnreadCommentsForObjects","class":"OC\\Comments\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":117,"function":"cacheDirectory","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1646,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Comments/Manager.php","Line":662,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"21.0.2.1","id":"60b688d036699"}

2021-06-24 12:13 UTC, andyxheli reviewed
Once i added the changes that @nickvergessen implanted in #27316 the server stopped working the code worked before the changes.

2021-07-02 14:38 UTC, andyxheli commented
@MorrisJobke Just wanted to let you know that this is not on NC 21.0.3