Update TwoFactorChallengeController.php
nextcloud/server pull request #27294
Opened 2021-05-30 20:25 UTC by pjft

For security reasons, we may want to monitor failures of 2FA challenges in order to ban attackers who might try to access compromised accounts but are stopped by the 2FA challenge.
Right now, the only hindrance is rate-limiting, but it's probably not enough.
It's my first attempt at doing any such changes, so I'm open to feedback or inputs here.
Keep up the great work.

2021-06-01 19:11 UTC, LukasReschke requested changes
This is a good idea and I do like it. But if you could move this to use Dependency Injection then that would be awesome! :)

2021-06-01 19:11 UTC, LukasReschke commented on core/Controller/TwoFactorChallengeController.php
> +		\OC::$server->getLogger()->warning("Two-factor challenge failed: $uid (Remote IP: $ip)");
Can you inject `ILogger` into the constructor and use that instead of the static access? :)

As an example this should help:

https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/lib/private/UserStatus/Manager.php#L40-L59

https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/lib/private/UserStatus/Manager.php#L97-L101

You'd also have to adjust the constructor in the test file probably: https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/tests/Core/Controller/TwoFactorChallengeControllerTest.php#L79

2021-06-01 20:33 UTC, pjft commented on core/Controller/TwoFactorChallengeController.php
> +		\OC::$server->getLogger()->warning("Two-factor challenge failed: $uid (Remote IP: $ip)");
Thanks for the reply. Sure, I'm happy to try it out - my availability isn't great, but I'll keep this on my to do list.

Also, I never did any PHP coding (though I do in plenty of others), so if I don't obey any specific guidelines from PHP, or do something that's a big no-no, do call me out on it, no offense taken :) 

If I run into any challenge, I may ask, but I believe you already send me a fair amount of things to run with. Thank you!

2021-06-19 20:37 UTC, pjft commented
@LukasReschke and @szaimen thanks for the feedback. 

I believe I did everything that should have been done and, from trying it out, it *magically* seems to work.

Now, as I mentioned, I never did PHP, so if I did anything that I shouldn't have, do call me out. Also, if you'd like me to squash the commits myself, change the error message or something, let me know.

Also, if you don't mind me asking - and here's the *magic* part for me - I couldn't, for the life of me, find where the TwoFactorChallengeController instance was created, so I was hoping that I would have to change something where it was created but... I didn't? If it isn't too much - nor too dumb of me - to ask, coming from C/C++ and other languages myself, can you help me understand _why_ I didn't have to do anything on where it is instanced?

I'd love to learn.

Thanks.

2021-06-21 11:01 UTC, LukasReschke commented
Thanks for the Pull Request - @pjft. This looks so far good to me from a code point of view 🚀 

Some nitpicks:

- We require the contributions to be DCO signed. You can read more about the DCO at https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work. You can see on https://github.com/nextcloud/server/pull/27294/checks?check_run_id=2866232850 the commands to add the DCO.
- To improve this a little bit more it would be cool to add a test that also verifies that the log entry was actually added. So when someone removes the log line, the tests would fail.
  - You'd probably want to add this test at https://github.com/nextcloud/server/blob/c5f5daa3c4635138c55c52fd78a577c8ebafaef5/tests/Core/Controller/TwoFactorChallengeControllerTest.php#L265-L297 something such as the following (not tested!)

```php
$this->request->expects($this->once())
                        ->method('getRemoteAddress')
                        ->willReturn('192.168.0.1');
$user->expects($this->once())
                        ->method('getUID')
                        ->willReturn('johndoe');
$this->logger->expects($this->once())
                        ->method('warning')
                        ->with('Two-factor challenge failed: johndoe (Remote IP: 192.168.0.1)');
```

That said, once the DCO is added I'd already be fine with merging this.

> Also, if you don't mind me asking - and here's the magic part for me - I couldn't, for the life of me, find where the TwoFactorChallengeController instance was created, so I was hoping that I would have to change something where it was created but... I didn't? If it isn't too much - nor too dumb of me - to ask, coming from C/C++ and other languages myself, can you help me understand why I didn't have to do anything on where it is instanced?

Good question :-) 

Our Dependency Injection system uses reflection to determine the class of the parameter. Here it saw `ILogger` and then looked up in https://github.com/nextcloud/server/blob/1776b41ca8002d1b36d3e333cdb662d01c30b739/lib/private/Server.php#L755 what implementation this interface links to. This class was then initialised.

https://docs.nextcloud.com/server/latest/developer_manual/basics/dependency_injection.html has some more details about this. See "Use automatic dependency assembly (recommended)"

The other part of the question is probably "How does Nextcloud know that this URL should invoke this controller"? This can be seen in https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/core/routes.php#L69. `TwoFactorChallenge` here means invoke the `TwoFactorChallengeController` of this application. (in this case: "core".

https://docs.nextcloud.com/server/latest/developer_manual/basics/routing.html has more details about this.

2021-06-21 19:55 UTC, pjft commented
@LukasReschke wow, thank you for the thorough explanation and useful links there. After reading it a few more times, and especially the https://docs.nextcloud.com/server/latest/developer_manual/basics/dependency_injection.html link, I now understand both what I missed when I was looking for things in the code, but also how it all works. Thank you!

In regards to the DCO, I tried to do it as intended, but the DCO stage of the tests didn't allow me to sign it with my actual name - it stated that it expected "pjft" instead, which is my GitHub username. Let me know if that is alright, or if there's something I should do to actually have it accept my actual name (which is _not_ pjft).

As for the test, I'll probably take a look at it - once again - in the coming days/weeks when I have a bit more time. I take it that I'd need to install PHPUnit, per the documentation, and try it out. It doesn't seem to be too hard, but we'll see how it goes. Thanks for the sample code and the idea of what kind of test would be acceptable.

Thank you and have a good week!

2021-07-07 11:32 UTC, pjft commented
Hi @LukasReschke , apologies for bothering. The merge seems to be blocked by a requested change from you, but I can't seem to find any other than the Dependency Injection, and the DCO which I'm not sure I did correctly.

Could you help me assess if I missed anything else?

Hope you're all doing well, and thanks for taking the time.

2021-07-07 11:42 UTC, LukasReschke approved these changes
It seems I haven't changed the state last time :)

2021-07-07 11:46 UTC, pjft commented
Thank you - apologies for the trouble. :) Happy Wednesday!

2021-08-19 10:40 UTC, ChristophWurst approved these changes

2021-08-19 10:40 UTC, merged