[downstream] Skip local shares in bkg scan and occ files:scan (#26590)
nextcloud/server pull request #2745
Opened 2016-12-19 08:42 UTC by rullzer

From https://github.com/owncloud/core/pull/26590

2016-12-19 14:05 UTC, icewind1991 commented on lib/private/Files/Utils/Scanner.php
> +			if ($storage->instanceOfStorage('OCA\Files_Sharing\ISharedStorage')) {
Should be `'OCA\Files_Sharing\SharedStorage'` else it will also exclude federated shares

2016-12-19 14:06 UTC, icewind1991 requested changes

2016-12-19 14:06 UTC, icewind1991 commented on lib/private/Files/Utils/Scanner.php
> +			if ($storage->instanceOfStorage('OCA\Files_Sharing\ISharedStorage')) {
Should be `'OCA\Files_Sharing\SharedStorage'` else it will also exclude federated shares

2016-12-19 18:54 UTC, rullzer commented on lib/private/Files/Utils/Scanner.php
> +			if ($storage->instanceOfStorage('OCA\Files_Sharing\ISharedStorage')) {
Done

2016-12-20 11:17 UTC, icewind1991 approved these changes

2016-12-20 21:40 UTC, MorrisJobke commented
Tests fail

2017-01-11 07:16 UTC, merged