make Provisioning API aware of multiple mails
nextcloud/server pull request #27474
Opened 2021-06-11 11:40 UTC by blizzz

This extends the provisioning API as following

## getUser

endpoint: `ocs/v2.php/cloud/users/2d42e983-a7a8-40b1-8e4a-b8afeb5244240b`

### Original response

```xml
<?xml version="1.0"?>
<ocs>
 <meta>…</meta>
 <data>
  …
  <email>person_11@example.org</email>
  <displayname>Isabel, Morgan (person_11)</displayname>
  …
 </data>
</ocs>
```

### New, with no additional mail set

```xml
…
  <email>person_11@example.org</email>
  <additional_mail/>
  <displayname>Isabel, Morgan (person_11)</displayname>
…
```

### New, with one or more additional mail set

```xml
…
  <email>person_11@example.org</email>
  <additional_mail>
   <element>test1@example.org</element>
   <element>test2@example.org</element>
   <element>test3@example.org</element>
  </additional_mail>
  <displayname>Isabel, Morgan (person_11)</displayname>
…
```

2021-06-11 11:57 UTC, blizzz commented
Wow, https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/instruction_set_for_users.html is lacking quite some methods

2021-06-11 22:36 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
>  				$userData[$key]['verified'] = self::NOT_VERIFIED;
Might not want to set this for collections :)

2021-06-14 12:13 UTC, skjnldsv commented
(please assign again when ready ;)

2021-06-21 23:50 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
It seems that this causes non-indexed properties (i.e. displayname) to be saved to the db as indexed, I'd fix it myself if I knew how to not break everything else 😅

2021-06-22 09:58 UTC, blizzz commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
the idea of the change was to go away from the indices, as it would be a to and fro with multivalue props

2021-06-22 10:57 UTC, blizzz commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
I forgot to adjust the verification state updater method.

2021-06-22 22:51 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +				$jsonData[$property][] = $data;
```suggestion
			if (!empty($data)) {
				$jsonData[$property][] = $data;
			}
```

2021-06-23 01:23 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
[Integration updates](https://github.com/nextcloud/server/pull/27379/commits/74849df8de97069d32ee5101af0c90690f9c24d3) have been made on the UI & Integration branch, though currently there is unexpected behaviour where additional emails are being written to the db but aren't being retrieved (i.e. when calling `$account = $this->accountManager->getAccount($user)`) any help would be appreciated :)

2021-06-24 03:58 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
Some collection specific code paths which are necessary for collections to be retrieved don't seem to be run e.g. `addMissingDefaultValues` expects collection properties to be nested while the `$data[] = [...]` statement flattens all the properties into a one-dimensional array :)

2021-06-25 18:04 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +				$jsonData[$property][] = $data;
Resolving as no longer applicable :)

2021-06-25 23:28 UTC, Pytal commented on lib/private/Accounts/AccountManager.php
> +			$data[] = [
Duplicate emails are able to be saved at the moment :) https://github.com/nextcloud-gmbh/server/issues/34#issuecomment-776518076

![image](https://user-images.githubusercontent.com/24800714/123493720-2d03bc00-d5d2-11eb-9251-359838ea8fec.png)

2021-06-25 23:39 UTC, Pytal commented
Duplicate emails are able to be saved at the moment, adjustments to prevent this should be made as per https://github.com/nextcloud-gmbh/server/issues/34#issuecomment-776518076 :)

![image](https://user-images.githubusercontent.com/24800714/123493720-2d03bc00-d5d2-11eb-9251-359838ea8fec.png)

2021-06-29 10:17 UTC, blizzz commented
> Duplicate emails are able to be saved at the moment, adjustments to prevent this should be made as per [nextcloud-gmbh/server#34 (comment)](https://github.com/nextcloud-gmbh/server/issues/34#issuecomment-776518076) :)
> 
> ![image](https://user-images.githubusercontent.com/24800714/123493720-2d03bc00-d5d2-11eb-9251-359838ea8fec.png)

yes, it it check box no. 5 of https://github.com/nextcloud/server/issues/26866. My intention is to do it in another PR to not bloat  this one.

2021-06-29 14:20 UTC, Pytal commented
> yes, it it check box no. 5 of #26866. My intention is to do it in another PR to not bloat this one.

Ahh yes forgot that was already on the list 😂

2021-06-30 01:21 UTC, Pytal approved these changes
🎉🎉🎉

2021-06-30 05:13 UTC, skjnldsv approved these changes

2021-06-30 05:13 UTC, merged

2021-06-30 05:13 UTC, skjnldsv commented
/backport to stable22

2021-06-30 05:53 UTC, nickvergessen requested changes

2021-06-30 05:53 UTC, nickvergessen commented on apps/provisioning_api/appinfo/routes.php
> +		['root' => '/cloud', 'name' => 'Users#editUserMultiValue', 'url' => '/users/{userId}/{collectionName}', 'verb' => 'PUT', 'requirements' => ['collectionName' => '^(?!enable$|disable$)[a-zA-Z0-0_]*$'
```suggestion
		['root' => '/cloud', 'name' => 'Users#editUserMultiValue', 'url' => '/users/{userId}/{collectionName}', 'verb' => 'PUT', 'requirements' => ['collectionName' => '^(?!enable$|disable$)[a-zA-Z0-9_]*$']],
```
🤔

2021-06-30 09:15 UTC, blizzz commented on apps/provisioning_api/appinfo/routes.php
> +		['root' => '/cloud', 'name' => 'Users#editUserMultiValue', 'url' => '/users/{userId}/{collectionName}', 'verb' => 'PUT', 'requirements' => ['collectionName' => '^(?!enable$|disable$)[a-zA-Z0-0_]*$'
https://github.com/nextcloud/server/pull/27723