Fix .webapp-nextcloud-<version> integrity error
nextcloud/server pull request #2748
Opened 2016-12-19 10:19 UTC by golodhrim

On Gentoo/Funtoo Systems there is next to a .webapp file also a .webapp-nextcloud-<version> file. upgraded from Owncloud they had the following fix in it. hope it can be included

2016-12-19 11:15 UTC, nickvergessen requested changes

2016-12-19 11:15 UTC, nickvergessen commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +￼         * containing these strings, are ignored.
weird characters on these lines, please delete

2016-12-19 11:55 UTC, LukasReschke commented
I'm absolutely not a fan of this, can distributors please stop putting random files into the source code?!?

2016-12-21 15:18 UTC, MorrisJobke commented
> I'm absolutely not a fan of this, can distributors please stop putting random files into the source code? But whatever … 😢

Is this good for review now?

2017-02-20 12:22 UTC, LukasReschke commented
This is a duplicate of https://github.com/nextcloud/server/pull/3113 and also opens a security hole.

2017-02-20 12:22 UTC, closed without merging