better error messages if the users home is not writable during scanning
nextcloud/server pull request #27538
Opened 2021-06-17 11:54 UTC by icewind1991

Signed-off-by: Robin Appelman <robin@icewind.nl>

2021-06-30 16:02 UTC, PVince81 commented
Fixes https://github.com/nextcloud/server/issues/26634

What's missing to finish this ?

2021-08-31 02:04 UTC, szaimen commented
> What's missing to finish this ?

Good question. Ping @icewind1991

2021-10-25 08:04 UTC, come-nc requested changes

2023-04-05 13:01 UTC, artonge approved these changes

2023-04-05 15:53 UTC, come-nc approved these changes

2023-04-05 15:53 UTC, merged