allow setting offset for dav search queries not limited to the users home storage
nextcloud/server pull request #27561
Opened 2021-06-18 13:00 UTC by icewind1991

multi-storage offset is cheap (enough) now

Signed-off-by: Robin Appelman <robin@icewind.nl>

2021-06-18 13:30 UTC, skjnldsv approved these changes

2021-06-18 13:59 UTC, juliushaertl requested changes

2021-06-18 13:59 UTC, juliushaertl commented on apps/dav/lib/Files/FileSearchBackend.php
> +		$offset = $limit->firstResult;
I guess the todo from 3 lines above can be removed then.

2021-06-22 18:38 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +		$offset = $limit->firstResult;
done

2021-06-22 18:57 UTC, juliushaertl approved these changes

2021-06-23 09:27 UTC, merged

2021-06-23 10:05 UTC, szaimen commented
🎉

2021-06-23 11:14 UTC, szaimen commented
Backport to stable21?