Check datadirectory owner, not config owner.
nextcloud/server pull request #27613
Opened 2021-06-22 18:25 UTC by Dreamsorcerer

2021-06-23 10:12 UTC, szaimen commented
cc @skjnldsv, @eneiluj, @icewind1991 and @ArtificialOwl for feedback on this

2024-02-27 17:45 UTC, skjnldsv commented
@Dreamsorcerer could you rebase and resolve conflicts? :)
Thanks a lot for your interest in that feature :bow:

2024-02-27 19:12 UTC, Dreamsorcerer commented
Updated

2024-02-27 19:17 UTC, skjnldsv requested changes

2024-02-27 19:19 UTC, Dreamsorcerer commented on console.php
>  		echo "Console has to be executed with the user that owns the file config/config.php" . PHP_EOL;
```suggestion
		echo "Console has to be executed with the user that owns the data directory" . PHP_EOL;
```

2024-02-27 19:22 UTC, skjnldsv approved these changes
I would prefer better commits messages 🙈
But I'm okay with the code 👍

2024-02-27 19:25 UTC, Dreamsorcerer commented
> I would prefer better commits messages 🙈 But I'm okay with the code 👍

Sure, but it's a trivial change. I assume it'll be squashed.

2024-02-27 19:27 UTC, skjnldsv commented
No, we do not squash, we want to preserve the commits history

2024-02-28 10:46 UTC, Altahrim commented on cron.php
> +		$configUser = fileowner($config->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data'));
```suggestion
		$dataDirectoryUser = fileowner($config->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data'));
```
Need to next lines too

2024-02-28 10:46 UTC, Altahrim commented on cron.php
>  			echo "Console has to be executed with the user that owns the file config/config.php" . PHP_EOL;
```suggestion
			echo "Console has to be executed with the user that owns the data directory" . PHP_EOL;
```

2024-02-28 10:46 UTC, Altahrim commented on console.php
> +	$configUser = fileowner($config->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data'));
```suggestion
	$dataDirectoryUser = fileowner($config->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data'));
```
Need to next lines too

2024-02-28 10:59 UTC, szaimen commented on cron.php
> +		$configUser = fileowner($config->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data'));
Maybe use getSystemValueString here?

2024-02-28 13:17 UTC, Altahrim approved these changes
:tada:

2024-02-28 16:43 UTC, Dreamsorcerer commented
Thanks for finishing it off, I'm a bit short on time at the moment, so was just making quick updates in the Github UI.

2024-02-28 17:40 UTC, merged

2024-04-30 15:00 UTC, szaimen commented
This breaks e.g. in https://github.com/nextcloud/all-in-one/discussions/4542#discussioncomment-9275002

2024-04-30 18:25 UTC, Dreamsorcerer commented
> This breaks e.g. in [nextcloud/all-in-one#4542 (comment)](https://github.com/nextcloud/all-in-one/discussions/4542#discussioncomment-9275002)

Why are the users different in this case? The upgrade needs write access to that directory, so seems like it'd make sense to me that it is owned by the same user.

Though thinking a little more about that check. Surely it only needs to check that we can write to the directory. I'm not clear why it checked the owner of the file in the first place...

2024-05-11 13:45 UTC, miccgn commented
> The upgrade needs write access to that directory, so seems like it'd make sense to me that it is owned by the same user.
Having write access to a directory doesn't necessarily mean you need to be the owner. In my case, using NFS, the owner is some UID even not existant on the local www server, but nevertheless www-data gets write access.

> Though thinking a little more about that check. Surely it only needs to check that we can write to the directory. I'm not clear why it checked the owner of the file in the first place...

Exactly.

So, how can I disable that check and get OCC back to work?

2024-05-11 13:48 UTC, Dreamsorcerer commented
> So, how can I disable that check and get OCC back to work?

Well, right now, comment out the code. That's what I've had to do for the past 3+ years while waiting for this PR to merge...

2024-05-11 18:15 UTC, miccgn commented
> > So, how can I disable that check and get OCC back to work?
> 
> Well, right now, comment out the code. That's what I've had to do for the past 3+ years while waiting for this PR to merge...

Thanks. Just did so - in both places (cron.php and console.php).

Probably a php function like is_writable() would be more appropriate for the task here.

2024-05-24 13:22 UTC, szaimen commented
Hi, we had to revert this pr: https://github.com/nextcloud/server/pull/45302
See https://github.com/nextcloud/server/pull/45307 on a new approach.