Remember current cipher
nextcloud/server pull request #27644
Opened 2021-06-24 00:06 UTC by J0WI

Follow up to #26323
In my case `getCipher()` is about 15 times faster and this function is called for each file.

2021-06-25 12:00 UTC, ChristophWurst commented on apps/encryption/lib/Crypto/Crypt.php
> +		$cipher = $config->getSystemValue('cipher', self::DEFAULT_CIPHER);
otoh this code is now performed before `getCypher` is even called. Could you move this into a private method and invoke from `getCypher` but return early when `$this->cipher` is already set to ensure the logic is only run once?

2021-06-29 11:26 UTC, J0WI commented on apps/encryption/lib/Crypto/Crypt.php
> +		$cipher = $config->getSystemValue('cipher', self::DEFAULT_CIPHER);
Psalm does not like this approach.
 >  Property $this->currentCipher with type string should already be set in the constructor

2021-06-29 11:26 UTC, ChristophWurst requested changes
Static analysis complains that the property isn't initialized

2021-06-29 11:26 UTC, ChristophWurst commented on apps/encryption/lib/Crypto/Crypt.php
> +	/** @var string */
```suggestion
	/** @var string|null */
```

2021-06-29 11:26 UTC, ChristophWurst commented on apps/encryption/lib/Crypto/Crypt.php
> +		if (!isset($this->currentCipher)) {
```suggestion
		if ($this->currentCipher === null) {
```

nitpick: if you flip the expression to !== then you can do an early return and save the indentation in the rest of the method ;)

2021-06-29 11:26 UTC, ChristophWurst commented on apps/encryption/lib/Crypto/Crypt.php
> +		$cipher = $config->getSystemValue('cipher', self::DEFAULT_CIPHER);
see my new review :)

2021-06-29 11:29 UTC, J0WI commented on apps/encryption/lib/Crypto/Crypt.php
> +		$cipher = $config->getSystemValue('cipher', self::DEFAULT_CIPHER);
> otoh this code is now performed before getCypher is even called.

Is there any case where the cipher can change during any operation?

2021-06-29 11:37 UTC, ChristophWurst commented on apps/encryption/lib/Crypto/Crypt.php
> +		$cipher = $config->getSystemValue('cipher', self::DEFAULT_CIPHER);
No. That is not my objection. My concern is that as soon as `Crypt` is injected into another class, the object is build and the constructor is ran. Sometimes the crypto methods will be used, otherwise they don't. If you put the default cipher resolution right into the constructor then you run this logic preemptively. By moiving it into a lazy method as you already did it's only run if really needed. I hope I'm expressing myself better now :v:

2021-06-29 11:42 UTC, ChristophWurst approved these changes
:shipit:

2021-06-29 12:12 UTC, LukasReschke approved these changes

2021-06-29 13:19 UTC, merged