Create rebase action
nextcloud/server pull request #27673
Opened 2021-06-25 13:22 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-06-25 13:25 UTC, skjnldsv approved these changes

2021-06-25 17:07 UTC, nickvergessen requested changes

2021-06-25 17:07 UTC, nickvergessen commented on .github/workflows/command-rebase.yml
> +    # On pull requests and if the comment starts with `/compile`
Compile or rebase?

2021-06-25 17:10 UTC, szaimen commented on .github/workflows/command-rebase.yml
> +    # On pull requests and if the comment starts with `/compile`
Good eye, needs to be fixed in the .github repo first.

2021-06-26 11:37 UTC, szaimen commented
Superseded by https://github.com/nextcloud/server/pull/27687

2021-06-26 11:37 UTC, closed without merging