Add IUrlGenerator::linkToDefaultPageUrl()
nextcloud/server pull request #27733
Opened 2021-06-30 14:23 UTC by PhrozenByte

Replaces the deprecated `\OC_Util::getDefaultPageUrl()` by `IUrlGenerator::linkToDefaultPageUrl()` and makes this API public.

I wanted to use this in https://github.com/nextcloud/cms_pico/commit/63898afc791e1c335adf1e4d6224b8962f7cc951, but there's simply no public API for this right now... Redirecting to login (which in turn redirects to to the default page) is a bad workaround...

2021-06-30 14:54 UTC, PhrozenByte commented
Not sure why Psalm complains that class `OC` doesn't exist - just within `RedirectToDefaultAppResponse` and not for the exact same line in `OC_Util` :confused: Any ideas?

2021-07-01 06:37 UTC, juliushaertl commented
> Not sure why Psalm complains that class OC doesn't exist - just within RedirectToDefaultAppResponse and not for the exact same line in OC_Util confused Any ideas?

I think that should be fine to add to the baseline as it doesn't really leak any private namespace class to OCP, but maybe @ChristophWurst can review as well :)

2021-07-01 06:38 UTC, juliushaertl approved these changes

2021-07-01 11:32 UTC, ChristophWurst requested changes
I would prefer to see `\OCP\AppFramework\Http\RedirectToDefaultAppResponse` deprecated in the same move so we can push people towards the usage of this new `IUrlGenerator::linkToDefaultPageUrl`. The new method is clean, is mockable and testable. The response class, however, uses the service locator anti pattern and is therefore no easy to test in apps.

So strong :+1: on this new method, but let's use the opportunity to phase out some technical debt :)

2021-07-01 11:32 UTC, ChristophWurst commented on lib/public/AppFramework/Http/RedirectToDefaultAppResponse.php
> +		$urlGenerator = \OC::$server->getURLGenerator();
```suggestion
		$urlGenerator = \OC::$server->get(\OCP\IURLGenerator::class);
```

2021-07-01 13:27 UTC, ChristophWurst approved these changes
Just a nitpick regarding annotations

Otherwise :shipit:

2021-07-01 13:27 UTC, ChristophWurst commented on lib/public/AppFramework/Http/RedirectToDefaultAppResponse.php
> -	 * @since 16.0.0
leave this and add a `@deprecated` as well

2021-07-01 14:44 UTC, PhrozenByte commented
I agree :+1: Done, just deprecated `RedirectToDefaultAppResponse` and removed the usage of `\OC::$server->getURLGenerator()` (old habits die slowly :laughing:).

Also tried to fix the unit tests (no idea why the tests suddenly started to fail... they should have failed from the beginning, but didn't for some reason), but I give up. Can please someone look into this (related changes: a43de10...1e5962a)? See https://github.com/nextcloud/server/pull/27733/checks?check_run_id=2963761891#step:7:4

Psalm is still complaining. Do you update Psalm's baseline, or how can I do this?

2021-07-30 13:34 UTC, PhrozenByte commented
Any ideas @juliushaertl @ChristophWurst ? I'm kinda stuck here... :disappointed:

2021-08-02 19:45 UTC, juliushaertl commented on lib/private/URLGenerator.php
> +		$this->appManager = $appManager;
I think the issue is that the app manager requires a working database and is therefore not properly injected when installing Nextcloud in the tests.

Currently I cannot think of an elegant workaround other than avoiding using DI for that or registering the service for the URLGenerator manually similar to https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Server.php#L957-L965, tough in that case I'd prefer the first option to just go with `\OC::$server->get(IAppManager::class)`

2021-08-04 17:07 UTC, PhrozenByte commented
This doesn't seem to be the issue :unamused: 

I tried switching from DI to `\OC::$server->get(IAppManager::class)` both in the test, as well as the class - and the issue persists. I even refactored the tests so that they definitely don't need a database connection, all dependencies are mocked now. Still no success.

Since I don't have a Oracle database at hand I can't reproduce this locally. All tests succeed locally:

```
$ phpunit-8 --configuration ./tests/phpunit-autotest.xml ./tests/lib/UrlGeneratorTest.php
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.16 with Xdebug 3.0.3
Configuration: /…/nextcloud/tests/phpunit-autotest.xml

.............................                                     29 / 29 (100%)

Time: 235 ms, Memory: 28.00 MB

OK (29 tests, 71 assertions)
```

The same is true for the touched `LoginControllerTest`, `TwoFactorChallengeControllerTest` and `UtilTest`.

Is there some OCI expert we might ask for help @juliushaertl ?

2021-08-05 08:18 UTC, juliushaertl commented
Its not OCI related as the other test runs on drone fail as well: https://drone.nextcloud.com/nextcloud/server/8246/10/4

At least on my local runs with `NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite tests/lib`, I can reproduce the failure and avoiding the DI of the app manager for the URLGenerator seems to solve that:

```
diff --git a/lib/private/URLGenerator.php b/lib/private/URLGenerator.php
index 7c97a76e25..f647031e01 100644
--- a/lib/private/URLGenerator.php
+++ b/lib/private/URLGenerator.php
@@ -71,13 +71,11 @@ class URLGenerator implements IURLGenerator {
 
        public function __construct(IConfig $config,
                                                                IUserSession $userSession,
-                                                               IAppManager $appManager,
                                                                ICacheFactory $cacheFactory,
                                                                IRequest $request,
                                                                Router $router) {
                $this->config = $config;
                $this->userSession = $userSession;
-               $this->appManager = $appManager;
                $this->cacheFactory = $cacheFactory;
                $this->request = $request;
                $this->router = $router;
@@ -307,7 +305,7 @@ class URLGenerator implements IURLGenerator {
                // find the first app that is enabled for the current user
                foreach ($defaultApps as $defaultApp) {
                        $defaultApp = \OC_App::cleanAppId(strip_tags($defaultApp));
-                       if ($this->appManager->isEnabledForUser($defaultApp)) {
+                       if (\OC::$server->getAppManager()->isEnabledForUser($defaultApp)) {
                                $appId = $defaultApp;
                                break;
                        }

```

2021-08-05 13:57 UTC, PhrozenByte commented
> At least on my local runs with `NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite tests/lib`, I can reproduce the failure and avoiding the DI of the app manager for the URLGenerator seems to solve that:

`php7.4-oci` succeeds wit this change, but [`nodb-php7.3`](https://drone.nextcloud.com/nextcloud/server/8261/9/4) fails. The reason why `TEST_SELECTION=DB` succeeds locally simply is because `--group DB` excludes the tests in question. The tests actually run with `TEST_SELECTION=NODB` - which fails locally, too.

Without mocking AppManager we can't test whether custom apps work as expected. Anyway, I feel like testing custom apps isn't really necessary, as long as we test that changing the default app causes a change in the default URL. Thus we test whether switching to the `settings` app as default app works now. It tests the same code path and succeeds, even though it's a slightly different test.

By the way, I still believe that the issues weren't actually caused by the tests in question. The tests were "real" unit tests before, i.e. any other class was mocked. You can prove this by running just this particular test without the latest changes with standard `phpunit`, it won't fail. I rather assume that these issues were caused by some other test that changed global state and some other test requiring these changes. I had this quite often in the past if tests change global state, any new test might change something just by chance, causing the test to fail. The only long-term solution is to remove resp. fix all unit tests not to change global state and not requiring other classes to be present (like AppManager here now).

Anyway... It's ready for merge now (apart from Psalm, but I assume you want to update the baseline yourself?). Thank you very much @juliushaertl :heart: 

> `NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite tests/lib`

Oh wow, didn't know this exists :see_no_evil: This definitely makes things easier.

2021-08-17 16:48 UTC, ChristophWurst commented on build/psalm-baseline-ocp.xml
> +      <code>\OC</code>
Hmm. I'm wondering if we can do better here. We put Psalm in place in OCP to get rid of these type leaks, not to create more of them.

But since this is for a now deprecated class I'm okay with this.

2021-09-28 17:48 UTC, PhrozenByte commented
@juliushaertl Since there were a lot of changes since your approval I don't want to merge right away, can you check again and if it seems suitable merge it? :rocket: :+1:

2021-10-05 11:06 UTC, juliushaertl approved these changes
Still good to go from my side :+1:

2021-10-05 11:06 UTC, merged