Automatically redirect calls to occ with the correct user to allow autocompletion
nextcloud/server pull request #2782
Opened 2016-12-20 13:49 UTC by nickvergessen

@schiessle @karlitschek as discussed. The only real disadvantage I can see with this is, that when you add the completion to your bashrc, everytime you open your terminal, you are prompted for your sudo password:
> [sudo] Passwort für nickv: 

Not sure if that is too confusing without any additional note, but that is the case for all solutions.

2016-12-20 13:51 UTC, karlitschek commented
hehe. nice!  👍

2016-12-20 16:11 UTC, MorrisJobke requested changes

2016-12-22 13:18 UTC, schiessle commented on core/console.php
> +		echo shell_exec('sudo -E -u ' . $configUser['name'] . ' php ' . __FILE__ . ' ' . implode(' ', $arguments) . ' ');
not only that the command exists, but also that the current user can actually execute it (needs to be in the sudoers list)

2016-12-22 13:55 UTC, nickvergessen commented on core/console.php
> +		echo shell_exec('sudo -E -u ' . $configUser['name'] . ' php ' . __FILE__ . ' ' . implode(' ', $arguments) . ' ');
Does it really matter? Yes it will error, but then again, this is only when people use a wrong command anyway? But sure I can try to fix this but...

2016-12-22 16:04 UTC, schiessle commented on core/console.php
> +		echo shell_exec('sudo -E -u ' . $configUser['name'] . ' php ' . __FILE__ . ' ' . implode(' ', $arguments) . ' ');
you are right @nickvergessen. I thought that in the case it will also fail if the admin is logged in as the right user (missed the if in L62).

2016-12-22 16:05 UTC, schiessle approved these changes

2017-01-05 11:24 UTC, nickvergessen commented
@MorrisJobke okay for you with my explanation?

2017-01-05 14:16 UTC, MorrisJobke commented
I still don't really like this: for example "./occ upgrade" will show exactly nothing until the whole command has finished. All the stuff we added are now encapsulated within an `shell_exec()` call that is synchronous.

2017-01-05 14:23 UTC, nickvergessen commented
> All the stuff we added are now encapsulated within an shell_exec() call that is synchronous.

Oo I didn't think about that, but yes makes "sense". But then again it's only for mis-uses which fail currently anyway.

2017-01-11 15:51 UTC, schiessle commented
I still like the way the problem is solved with this approach, but of course I also see the problem with shell_exec(). Therefore my suggestion: Replace occ with a shell script which does the magic you do now in console.php. Afaik we also discussed this option in the office, this way we avoid the problem with the synchronous shell_exec().

2017-04-03 19:21 UTC, rullzer commented
So what to do here gentlemen? @nickvergessen @MorrisJobke @schiessle

2017-04-03 20:53 UTC, MorrisJobke commented
> shell_exec(). Therefore my suggestion: Replace occ with a shell script which does the magic you do now in console.php. Afaik we also discussed this option in the office, this way we avoid the problem with the synchronous shell_exec().

This is the way to go if we want to do this magic. And the PR is the wrong approach as pointed out above. 👎 from me

2017-04-03 20:53 UTC, closed without merging