Update "Sending password by Nextcloud Talk failed" sentence
nextcloud/server pull request #27847
Opened 2021-07-07 10:25 UTC by szaimen

Fix https://github.com/nextcloud/server/issues/26973
Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-07 10:28 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
its a file or folder, not "an item" ?

2021-07-07 10:29 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
So then `file/folder` instead of `item` ?

2021-07-07 11:01 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
![grafik](https://user-images.githubusercontent.com/213943/124748457-7255b100-df23-11eb-951c-94ec892565da.png)


https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Share/IShare.php#L221-L228

Make a switch with getNodeType and have 2 translation strings

2021-07-07 11:13 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
Hm... instructions not clear enough. For getNodeType() we need the path and don't have it here at hand, only the file id, no?

2021-07-07 11:28 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
I'd vote for just changing the line to file/folder as it is only an error message and not that important...

2021-07-07 11:35 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
`$share->getNodeType()` should work just fine?
But I guess file/folder is also okay

2021-07-07 11:37 UTC, rakekniven reviewed
"Sending the password by Nextcloud Talk" for sharing a file or folder failed because Nextcloud Talk is not enabled.

Jm2c.

2021-07-07 11:40 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException($this->l->t('"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.'));
I've gone with https://github.com/nextcloud/server/pull/27847#pullrequestreview-700896481

2021-07-07 14:04 UTC, rakekniven requested changes
See my suggestion as comment above.

2021-07-07 14:09 UTC, szaimen commented
> See my suggestion as comment above.

I did implement it as you suggested...

2021-07-07 15:00 UTC, rakekniven approved these changes

2021-07-08 15:15 UTC, skjnldsv approved these changes

2021-07-08 16:15 UTC, merged