Fix add group button
nextcloud/server pull request #27864
Opened 2021-07-07 17:42 UTC by kesselb

Fix #27435

2021-07-07 17:43 UTC, kesselb commented
/compile amend settings

2021-07-07 17:45 UTC, LukasReschke approved these changes
🚀 🥳 🎉

2021-07-07 17:52 UTC, kesselb commented
/compile amend /

2021-07-07 18:50 UTC, Pytal requested changes

2021-07-07 18:50 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +			this.$refs.addGroup.editingValue = ''
```suggestion
			this.$refs.addGroup?.editingActive = true
			this.$refs.addGroup?.onMenuToggle(false)
			this.$nextTick(() => {
				this.$refs.addGroup?.$refs?.editingInput?.focusInput()
			})
		},

		hideAddGroupForm() {
			this.$refs.addGroup?.editingActive = false
			this.$refs.addGroup?.editingValue = ''
```
Some optional chaining safety :)

2021-07-07 20:09 UTC, kesselb commented on apps/settings/src/views/Users.vue
> +			this.$refs.addGroup.editingValue = ''
Hmm. Can $refs.addGroup be null? I would argue that something is broken if addGroup is null ;)

2021-07-07 21:47 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +			this.$refs.addGroup.editingValue = ''
good point 🤔 hadn't looked over all of it yet, refs here won't be null when the function is called :)

2021-07-07 21:47 UTC, Pytal approved these changes

2021-07-07 21:54 UTC, nickvergessen commented on apps/settings/src/views/Users.vue
> +			this.$refs.addGroup.editingValue = ''
$ref is null when triggered before mounted or mounted finished, don't recall atm.

2021-07-08 14:27 UTC, skjnldsv approved these changes

2021-07-08 14:27 UTC, skjnldsv commented
/backport to stable22

2021-07-08 14:28 UTC, skjnldsv commented
Please rebase and compile, you need to remove the extra settings files
```
	deleted:    apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js
	deleted:    apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js.map

```

2021-07-08 14:53 UTC, kesselb commented
> Please rebase and compile, you need to remove the extra settings files
> 
> ```
> 	deleted:    apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js
> 	deleted:    apps/settings/js/vue-settings-users-7f4f43139d7b1af5f465.js.map
> ```

Done

2021-07-08 15:21 UTC, merged