Fix svg icons disapearing in app navigation when text overflows
nextcloud/server pull request #27936
Opened 2021-07-13 10:28 UTC by CarlSchwan

The issue is caused by the icon being positionned with negative margins
and the `overflow: hidden` rule when hide the icon when the text
overflows. Remove positioning with negative margins.

This fix #23849
Closes #24378

2021-07-13 13:01 UTC, szaimen requested changes
Hm... I couldn't reproduce the initial issue on NC22.0.0...
![image](https://user-images.githubusercontent.com/42591237/125456037-62da69df-ad3f-47c2-9039-faf793203ee2.png)

2021-07-13 13:49 UTC, CarlSchwan commented
This is with a local instance and using git master (with Firefox) 

![image](https://user-images.githubusercontent.com/23653902/125463065-a6a91d9a-3532-44f7-a550-10d3bd1b0164.png)

On Chromium without this patch it's also working fine.

2021-07-13 14:14 UTC, szaimen approved these changes
You are right. I've overlooked that this only happens with Firefox.
Tested the PR successfully with Firefox and Chromium

2021-07-13 14:26 UTC, eneiluj approved these changes
Yup, tested with Firefox 89.

I think this can be backported to stable20, stable21 and stable22 as the issue seems to be the same. I didn't try to apply this commit in those branches though.

2021-07-13 14:32 UTC, szaimen commented
@CarlSchwan do you mind signing off your commits to pass the DCO check?
See https://github.com/nextcloud/server/pull/27936/checks?check_run_id=3055830036 for instructions.
Thank you!

2021-07-13 14:37 UTC, CarlSchwan commented
> @CarlSchwan do you mind signing off your commits to pass the DCO check?
> See https://github.com/nextcloud/server/pull/27936/checks?check_run_id=3055830036 for instructions.
> Thank you!

Done :) and added `format.signoff` to my git configs so that I don't have to think about it next time :)

2021-07-13 14:40 UTC, szaimen commented
Great! Thanks a lot! :)

2021-07-13 22:07 UTC, merged

2021-07-13 22:08 UTC, szaimen commented
/backport to stable22

2021-07-13 22:08 UTC, szaimen commented
/backport to stable21

2021-07-13 22:08 UTC, szaimen commented
/backport to stable20

2021-07-14 17:23 UTC, szaimen commented
I fear this PR has broken the files app:
Are you able to reproduce?
![image](https://user-images.githubusercontent.com/42591237/125665374-34282e18-fc72-48c1-a933-aae21894f2ba.png)

2021-07-14 17:28 UTC, eneiluj commented
Damn, yes I can see it too. We couldn't see it because of the style caching...
@CarlSchwan ^^

2021-07-14 17:33 UTC, CarlSchwan commented
Hmm I can't reproduce with firefox but I can with chromium. On it

2021-07-14 17:39 UTC, eneiluj commented
I can reproduce with both FF and Chromium. Did you try to reload without using the cache (just in case: CTRL+F5)?

2021-07-14 17:41 UTC, CarlSchwan commented
I created a patch that hopefully fix the issue (it does for me): https://github.com/nextcloud/server/pull/27973/files