Add autocompletion for password reset
nextcloud/server pull request #27949
Opened 2021-07-13 15:14 UTC by CarlSchwan

Using autocomplete="current-password" and autocomplete="new-password"
will help browser with integrated password managers to generate safe
password for the users.

See https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/password#allowing_autocomplete.

Close #27885

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2021-07-13 15:23 UTC, eneiluj commented
@szaimen Are you sure you want to assign this PR? Maybe you wanted to request reviews? :grin:

2021-07-13 15:24 UTC, szaimen commented
> Are you sure you want to assign this PR? Maybe you wanted to request reviews? 😁

You are right. I misclicked 😅

2021-07-13 15:51 UTC, eneiluj reviewed
Nice! This could also be done in login page and password reset page.
`core/src/components/login/LoginForm.vue`
`core/src/components/login/UpdatePassword.vue`

2021-07-13 16:11 UTC, CarlSchwan commented
> Nice! This could also be done in login page and password reset page.
> `core/src/components/login/LoginForm.vue`
> `core/src/components/login/UpdatePassword.vue`

Good idea :) Just did that and also unified the `autocapitalize="none" autocorrect="off"` behavior with the two places you linked. Not sure it's really needed since I expect browsers to be clever enough to not autocorrect password fields by default but at least it's consistent :)

2021-07-13 16:28 UTC, szaimen commented
/compile amend /

2021-07-13 16:36 UTC, szaimen commented
/compile amend /

2021-07-13 16:43 UTC, szaimen commented
Seems like the compile bot is broken today :(

2021-07-13 21:28 UTC, Pytal commented on core/src/components/login/LoginForm.vue
>  					autocapitalize="off"
```suggestion
					autocapitalize="none"
```
For consitency :)

2021-07-14 09:40 UTC, eneiluj requested changes

2021-07-14 09:40 UTC, eneiluj commented on core/src/components/login/UpdatePassword.vue
> +					autocomplete="current-password"
```suggestion
					autocomplete="new-password"
```
as it's the place where one sets a new password :grin:

2021-07-14 09:54 UTC, eneiluj approved these changes

2021-07-14 22:17 UTC, szaimen commented
Solved the conflicting files. But I fear there is still the need to compile and push the js.
`/compile amend /` unfortunatlely didn't work the last times...

2021-07-14 22:28 UTC, szaimen commented
/compile amend /

2021-07-14 22:45 UTC, Pytal approved these changes

2021-07-15 10:23 UTC, artonge commented
I compiled the files, but can't push on @CarlSchwan's branch :(

2021-07-15 10:40 UTC, CarlSchwan commented
I will compile the files and push them after lunch

2021-08-31 01:48 UTC, szaimen commented
/rebase

2021-08-31 01:53 UTC, szaimen commented
Unfortunately the fork seems to be still unpushable...

2021-10-25 10:24 UTC, merged