Fix IDN domain name not being allowed
nextcloud/server pull request #27961
Opened 2021-07-14 09:30 UTC by CarlSchwan

The filter_var function is unfortunately not perfect and doesn't support
domain with unicode as well as url with underscores. Replace usage with
a regex.

See https://bugs.php.net/search.php?cmd=display&search_for=FILTER_VALIDATE_URL

Closes #27906

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2021-07-14 11:55 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		return preg_match('#(https?://(\S*?\.\S*?|localhost))([\s)\[\]{},;"\':<]|\.\s|$)#i', $url) === 1;
I'd suggest to adjust the regex to also allow hostnames without the domain part other than localhost only

```suggestion
		return preg_match('#(https?://(\S*?\.*\S*?))([\s)\[\]{},;"\':<]|\.\s|$)#i', $url) === 1;
```

2021-07-14 11:55 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		return preg_match('#(https?://(\S*?\.\S*?|localhost))([\s)\[\]{},;"\':<]|\.\s|$)#i', $url) === 1;
Or just to safeguard, we could only use the regex as a fallback if the filter_var doesn't match:

```suggestion
		return filter_var($url, FILTER_VALIDATE_URL) !== false) || preg_match('#(https?://(\S*?\.\S*?|localhost))([\s)\[\]{},;"\':<]|\.\s|$)#i', $url) === 1;
```

2021-07-14 14:41 UTC, CarlSchwan commented on apps/theming/lib/Controller/ThemingController.php
> +		return preg_match('#(https?://(\S*?\.\S*?|localhost))([\s)\[\]{},;"\':<]|\.\s|$)#i', $url) === 1;
It turns out there is a idn_to_ascii function that makes it possible to then use filter_var. Fount it in https://github.com/nextcloud/server/issues/27546.

2021-07-14 19:09 UTC, juliushaertl approved these changes

2021-07-14 19:09 UTC, juliushaertl commented
Mind to squash to a single commit? :)

2021-07-14 21:05 UTC, blizzz approved these changes

2021-07-14 21:07 UTC, blizzz commented
CI is unhappy tho

2021-07-15 09:01 UTC, CarlSchwan commented
It's a bit weird that the ci report a failure for continuous-integration/drone/pr but in https://drone.nextcloud.com/nextcloud/server/7311 everything is green

2021-07-15 10:05 UTC, juliushaertl commented
> It's a bit weird that the ci report a failure for continuous-integration/drone/pr but in [drone.nextcloud.com/nextcloud/server/7311](https://drone.nextcloud.com/nextcloud/server/7311) everything is green

What about https://drone.nextcloud.com/nextcloud/server/7311/9/4 :wink: 

```

There were 4 failures:

1) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheetSuccess with data set #1 ('url', 'https://nextcloud.com/aaaaaaa...aaaaaa', 'Saved')
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
         'data' => Array (
-            'message' => 'Saved'
-            'serverCssUrl' => '/nextcloudWebroot/core/css/so...s.scss'
+            'message' => 'The given web address is not a valid URL'
         )
-        'status' => 'success'
+        'status' => 'error'
     )
     'headers' => Array (...)
     'cookies' => Array ()
-    'status' => 200
+    'status' => 400
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\EmptyContentSecurityPolicy Object (...)

/drone/src/apps/theming/tests/Controller/ThemingControllerTest.php:168

2) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheetSuccess with data set #6 ('imprintUrl', 'https://nextcloud.com/aaaaaaa...aaaaaa', 'Saved')
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
         'data' => Array (
-            'message' => 'Saved'
-            'serverCssUrl' => '/nextcloudWebroot/core/css/so...s.scss'
+            'message' => 'The given legal notice address is not a valid URL'
         )
-        'status' => 'success'
+        'status' => 'error'
     )
     'headers' => Array (...)
     'cookies' => Array ()
-    'status' => 200
+    'status' => 400
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\EmptyContentSecurityPolicy Object (...)

/drone/src/apps/theming/tests/Controller/ThemingControllerTest.php:168

3) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheetSuccess with data set #7 ('privacyUrl', 'https://nextcloud.com/aaaaaaa...aaaaaa', 'Saved')
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
         'data' => Array (
-            'message' => 'Saved'
-            'serverCssUrl' => '/nextcloudWebroot/core/css/so...s.scss'
+            'message' => 'The given privacy policy address is not a valid URL'
         )
-        'status' => 'success'
+        'status' => 'error'
     )
     'headers' => Array (...)
     'cookies' => Array ()
-    'status' => 200
+    'status' => 400
     'lastModified' => null
     'ETag' => null
     'contentSecurityPolicy' => OCP\AppFramework\Http\EmptyContentSecurityPolicy Object (...)

/drone/src/apps/theming/tests/Controller/ThemingControllerTest.php:168

4) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheetError with data set #1 ('url', 'http://example.com/aaaaaaaaaa...aaaaaa', 'The given web address is too long')
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\DataResponse Object (
     'data' => Array (
         'data' => Array (
-            'message' => 'The given web address is too long'
+            'message' => 'The given web address is not a valid URL'
         )
         'status' => 'error'
     )

/drone/src/apps/theming/tests/Controller/ThemingControllerTest.php:217

--
```

2021-07-15 13:51 UTC, CarlSchwan commented
It seems `idn_to_ascii` is kinda evil too and just abort when the URL is too long :(

A better solution would be either to just copy the UrlValidator::validate from symfony/validator or just depends on symfony/validator and use it for all kind of validations in Nextcloud (URL, email, date ...). For reference, this is the method: https://github.com/symfony/validator/blob/14337bdf9e2e0b2e3385c9e90f13325f0c95a4f9/Constraints/UrlValidator.php#L24

2021-07-19 10:31 UTC, tcitworld commented
> It seems idn_to_ascii is kinda evil too and just abort when the URL is too long :(

That's probably because it's made to handle domains, not full URIs. You could extract the hostname with `parse_url`, convert it, then `substr_replace` it in the URL.

But using the regex from SF Validator makes sense too.

2021-07-20 11:10 UTC, eneiluj requested changes

2021-07-20 11:10 UTC, eneiluj commented on lib/public/Util.php
> +		return preg_match($pattern, $url) !== false;
`isValidUrl` will always return true unless an error occurs in `preg_match`.
```suggestion
		return preg_match($pattern, $url) === 1;
```
https://www.php.net/manual/en/function.preg-match.php#refsect1-function.preg-match-returnvalues
Or maybe it is intentional. Is it?

2021-07-20 15:43 UTC, eneiluj requested changes, later dismissed
Apart from that, code looks good. Didn't try it though.

2021-07-20 15:43 UTC, eneiluj commented on apps/oauth2/lib/Controller/SettingsController.php
> +		if (!\OCP\Util::isValidUrl($redirectUri)) {
Sorry, small detail, `OCP\Util` could be imported: `use OCP\Util;`
```suggestion
		if (!Util::isValidUrl($redirectUri)) {
```
like it's done in `apps/theming/lib/Controller/ThemingController.php`

2021-07-20 15:43 UTC, eneiluj commented on apps/theming/lib/ThemingDefaults.php
> +				&& \OCP\Util::isValidUrl($link['url'])
Same here :grin:

2021-07-20 15:43 UTC, eneiluj commented on lib/private/Setup.php
> +			if (!\OCP\Util::isValidUrl($webRoot)) {
Here

2021-08-06 12:33 UTC, CarlSchwan commented on apps/theming/lib/ThemingDefaults.php
> +				&& \OCP\Util::isValidUrl($link['url'])
There was a Util class in the same file and it collided so I used an alias OCPUtil

2021-08-31 01:48 UTC, szaimen commented
What is missing here?

2021-10-22 12:16 UTC, juliusknorr approved these changes

2022-01-11 13:32 UTC, PVince81 commented
@CarlSchwan are you able to fix the tests ?

2022-03-04 11:23 UTC, szaimen commented
/backport to stable23

2022-03-04 11:23 UTC, szaimen commented
/backport to stable22

2022-03-05 16:02 UTC, szaimen commented
I fixed the conflicts and rebased

2022-03-05 16:14 UTC, szaimen commented
@CarlSchwan please fix the tests if possible :)

2022-03-09 18:55 UTC, CarlSchwan commented on tests/lib/Validator/ValidatorTest.php
> + * Copyright (c) 2012 Bernhard Posselt <dev@bernhard-posselt.com>
copy pasta :(

2022-03-10 07:34 UTC, tcitworld commented on lib/private/Validator/IConstraintValidator.php
> +namespace OC\Validator;
Not in OCP ?

2022-03-10 09:05 UTC, come-nc reviewed
What is not clear to me:
- if "The API is based on Symfony Validator", why not use symfony validator instead of coding our own?
- Why is there for each type (url, csscolor…) both a validator and a constraint, couldn’t that be only one class? Seems overly complicated. Is there sometimes several validators for the same constraint, or several constraints for the same validator?

2022-03-10 09:05 UTC, come-nc commented on lib/public/Validator/Violation.php
> +class Violation {
Maybe this should extends Error or Exception, to be able to get traces for debug, not sure

2022-03-10 10:06 UTC, CarlSchwan commented on lib/private/Validator/IConstraintValidator.php
> +namespace OC\Validator;
For now, since I'm trying to keep the interface surface small to make it possible to easily extend it in the future. I'm for example not completely sure that it is helpful to return an array of Violations, as for the moment all the validator are returning only one or zero violation.

If you have some usecase in mind that would require to have that in OCP, I'm happy to reconsider that (and in that case, I would also probably merge the Constraint and Validator).

2022-03-10 10:07 UTC, CarlSchwan commented on lib/private/Validator/IConstraintValidator.php
> +namespace OC\Validator;
For now, since I'm trying to keep the interface surface small to make it possible to easily extend it in the future. I'm for example not completely sure that it is helpful to return an array of Violations, as for the moment all the validator are returning only one or zero violation.

If you have some usecase in mind that would require to have that in OCP, I'm happy to reconsider that (and in that case, I would also probably merge the Constraint and Validator).

2022-03-10 10:11 UTC, CarlSchwan commented on lib/public/Validator/Violation.php
> +class Violation {
> What is not clear to me:
> 
>     * if "The API is based on Symfony Validator", why not use symfony validator instead of coding our own?

Because the Symfony Validator is really heavy in term of dependencies (e.g. requires HTTP foundation and many other core components of Symfony). It is not that reusable outside of Symfony :( 

>     * Why is there for each type (url, csscolor…) both a validator and a constraint, couldn’t that be only one class? Seems overly complicated. Is there sometimes several validators for the same constraint, or several constraints for the same validator?

For two reasons:

* Keep the validator itself as a private API that apps shouldn't use directly
* It would allow writing multiple Constraints that internally use the same Validator

But I agree it's a bit complicated and if we make `validate` a public API, then we could merge the two

2022-03-15 10:22 UTC, artonge approved these changes

2022-03-15 10:22 UTC, artonge commented on apps/settings/lib/Controller/CheckSetupController.php
> +			new NotBlank(),
Shouldn't Url already check for NotBlank?

2023-04-17 13:46 UTC, szaimen commented
conflicts :/

2024-03-10 11:25 UTC, closed without merging