Use login name to fix password confirm with ldap users
nextcloud/server pull request #2797
Opened 2016-12-21 09:15 UTC by nickvergessen

- [ ] loginname was not set for me on my first try, need to find out why and where.

cc @ChristophWurst for the above issue, i guess it was because of "remember me"

2016-12-21 09:52 UTC, nickvergessen commented
Already found the issue

2016-12-21 12:50 UTC, nickvergessen commented
Review @ChristophWurst @blizzz

2016-12-22 09:38 UTC, blizzz approved these changes

2016-12-22 10:53 UTC, MorrisJobke approved these changes
Tested and works 👍

2016-12-22 10:54 UTC, MorrisJobke commented
I only restarted CI because it timed out. :(

2016-12-22 11:59 UTC, LukasReschke requested changes
CI is failing – https://drone.nextcloud.com/nextcloud/server/3394/38

2017-01-05 12:11 UTC, ChristophWurst approved these changes
looks good

2017-01-05 13:44 UTC, LukasReschke approved these changes

2017-01-05 14:15 UTC, merged