Improve notcreatable permissions hint
nextcloud/server pull request #27980
Opened 2021-07-15 00:40 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-15 01:44 UTC, Pytal requested changes, later dismissed

2021-07-15 01:44 UTC, Pytal commented on apps/files/templates/list.php
> +			<?php p('⚠️ ' . $l->t('You don’t have permission to upload or create files here'))?>
Consider using an icon from vue-material-design-icons like `vue-material-design-icons/AlertOutline` instead of an emoji, for cross-platform consistency :)

2021-07-15 02:08 UTC, szaimen commented on apps/files/templates/list.php
> +			<?php p('⚠️ ' . $l->t('You don’t have permission to upload or create files here'))?>
Hm... Not sure how to do that. I'd rather leave this PR simple and try to add your suggestion as follow-up to this PR.
Are you fine with that? :)

2021-07-15 02:43 UTC, szaimen commented on apps/files/templates/list.php
> +			<?php p('⚠️ ' . $l->t('You don’t have permission to upload or create files here'))?>
found a way

2021-07-15 09:05 UTC, artonge approved these changes
Nice

2021-07-15 09:42 UTC, juliushaertl submitted a review, later dismissed

2021-07-15 09:42 UTC, juliushaertl commented on apps/files/templates/list.php
> +			<svg style="width:15px;height:15px" viewBox="0 0 24 24">
Please move this to a dedicated svg file and add it to icons.scss then

2021-07-15 10:37 UTC, szaimen commented on apps/files/templates/list.php
> +			<svg style="width:15px;height:15px" viewBox="0 0 24 24">
done

2021-07-15 17:46 UTC, Pytal submitted a review, later dismissed

2021-07-15 17:46 UTC, Pytal commented on core/img/actions/alert-outline.svg
> +<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
If this still works without these lines we should remove these, and make it all one line to decrease file size :)

2021-07-15 19:00 UTC, szaimen commented on core/img/actions/alert-outline.svg
> +<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
seems like this works, yes.
Done

2021-07-15 19:07 UTC, Pytal approved these changes

2021-07-15 21:12 UTC, merged

2021-07-15 21:12 UTC, szaimen commented
/backport to stable22

2021-07-15 21:12 UTC, szaimen commented
/backport to stable21

2021-07-15 21:12 UTC, szaimen commented
/backport to stable20

2021-07-15 21:26 UTC, szaimen commented
Hm... is the backport bot dead?

2021-07-15 21:35 UTC, szaimen commented
/backport to stable22

2021-07-15 21:37 UTC, Pytal commented
> Hm... is the backport bot dead?

@skjnldsv

2021-07-16 08:37 UTC, szaimen commented
/backport to stable22

2021-07-16 08:37 UTC, szaimen commented
/backport to stable21

2021-07-16 08:38 UTC, szaimen commented
/backport to stable20