Full name section Vuetified
nextcloud/server pull request #28028
Opened 2021-07-17 05:33 UTC by Pytal

Vuetified

2021-07-22 06:55 UTC, skjnldsv commented on apps/settings/templates/settings/personal/personal.info.php
> +			<div id="vue-displaynamesection" class="section"></div>
I think it would be cleaner to entirely move the whole page to vue now.
Meaning no more single-section injection on this template, just one big `ProfilePage` app like planned

2021-07-23 22:32 UTC, Pytal commented on apps/settings/templates/settings/personal/personal.info.php
> +			<div id="vue-displaynamesection" class="section"></div>
This PR involved quite a bit of rewriting to abstract the shared components, so to keep this PR small I'll keep this one to just this one section — with the entire page in Vue coming up :)

2021-07-26 08:37 UTC, artonge commented on apps/settings/templates/settings/personal/personal.info.php
> +			<div id="vue-displaynamesection" class="section"></div>
So, should we review, or wait for the other PR ?

2021-07-26 15:36 UTC, Pytal commented on apps/settings/templates/settings/personal/personal.info.php
> +			<div id="vue-displaynamesection" class="section"></div>
Yeah it's good to review :)

2021-07-27 02:39 UTC, Pytal commented
/rebase

2021-07-27 08:33 UTC, artonge requested changes, later dismissed

2021-07-27 08:33 UTC, artonge commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
Still dislike the `$nextTick` logic :(

2021-07-27 08:33 UTC, artonge commented on apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
> +const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})
That could prevent an exception

```suggestion
const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', { emails: {}})
```

2021-07-27 08:33 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
I think we have a convention on event nomenclature: https://github.com/nextcloud/nextcloud-event-bus#naming-convention

2021-07-29 01:47 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +		<div class="displayname-actions-container">
BEM'd it :)

2021-07-29 01:57 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
Unforetunately without it the values may be sporadically out-of-date, am open to other solutions though :)

2021-07-29 02:08 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
> +const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})
Wrote this similarly to other `loadState` calls in the codebase which don't handle errors — with your suggestion other errors will throw further down the chain. I've written up a potential solution which catches `loadState` errors, but would need more input from others to decide whether it's a good solution
```js
// main-personal-info.js
const EmailView = Vue.extend(EmailSection)

try {
	const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})

	new EmailView({
		propsData {
			additionalEmails,
			primaryEmail,
		},
	}).$mount('#vue-emailsection')
} catch (e) {
	logger.error('Could not load personalInfoParameters state', e)
}
```

2021-07-29 02:11 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
Open to suggestions :)

2021-07-29 02:12 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
I think that's for global events — open to suggestions though :)

2021-07-29 02:13 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
I think that's for global events — open to suggestions though :)

2021-07-29 02:16 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
Unfortunately without it the values may be sporadically out-of-date, am open to other solutions though :)

2021-07-29 09:17 UTC, artonge commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
I would favor using the values from the event to make the function pure.

```js
onDisplayNameChange(e) {
			this.$emit('update:displayName', e.target.value.trim())
			this.debounceDisplayNameChange(e.target.value.trim())
},
```

2021-07-29 09:21 UTC, artonge commented on apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
> +const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})
Yes, you are right, it makes sense to let `loadState` throw an error instead of creating more obscure errors down the chain. I don't even think that the extra `try/catch` is necessary.

2021-07-29 09:22 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
@skjnldsv any recommendations ?

2021-07-29 23:16 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
I would be fine with moving to a functional paradigm as well, although from what I've seen from the rest of our codebase and as recommended by @skjnldsv we're using a lot of `this.[propname]` in our Vue methods, so I think it would be best at least for now to keep it consistent :)

2021-07-29 23:17 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
I would be fine with moving to a functional paradigm as well, although from what I've seen from the rest of our codebase and as recommended by @skjnldsv we're using a lot of `this.[propname]` in our Vue methods, so I think it would be best at least for now to keep it consistent :) is that fine with you?

2021-07-29 23:20 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
> +const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})
Fail fast 😂, so is it fine with you if I keep it the same and let `loadState` throw if there are errors?

2021-07-29 23:21 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
@skjnldsv we can also add an eslint rule https://eslint.vuejs.org/rules/custom-event-name-casing.html#vue-custom-event-name-casing

2021-07-30 06:18 UTC, skjnldsv commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
Events should be kebab-case yeah.
The naming convention is for global events yes

2021-07-30 08:59 UTC, artonge commented on apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue
> +const { emails: { additionalEmails, primaryEmail } } = loadState('settings', 'personalInfoParameters', {})
Yes :smiley:

2021-07-30 09:05 UTC, artonge commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
Not that much, but if it is consistent with the rest of the codebase I guess I can look away when clicking Approve :)

2021-07-31 00:45 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
@skjnldsv should we keep it consistent or start writing in a more functional paradigm?

2021-07-31 00:46 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
@skjnldsv should we keep it consistent or start moving towards a more functional paradigm?

2021-07-31 00:48 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
Roger that @skjnldsv https://github.com/nextcloud/eslint-config/pull/175 :)

2021-08-04 00:53 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			this.$emit('addAdditional')
Fixup for kebab-case is in :)

2021-08-09 12:41 UTC, ChristophWurst commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
:+1: on more functional programming where it's practical

2021-08-10 08:55 UTC, skjnldsv commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayName.vue
> +			this.$nextTick(() => this.debounceDisplayNameChange())
> as recommended by @skjnldsv we're using a lot of `this.[propname]` in our Vue methods

Did I say that? I've been recommending the sync modifier approach quite a lot :wink: 
`nextTick` should indeed be a last resort :)

2021-08-16 20:26 UTC, Pytal commented
/compile /

2021-08-17 18:03 UTC, Pytal commented
/compile amend /

2021-08-17 23:15 UTC, Pytal commented
/compile amend /

2021-08-17 23:29 UTC, Pytal commented
/compile /

2021-08-17 23:31 UTC, Pytal commented
/compile /

2021-08-19 21:24 UTC, skjnldsv commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayNameSection.vue
> +		@submit.stop.prevent="() => {}">
Does it even make sense to have a form if we're not using the form submit methods? :)

2021-08-19 21:25 UTC, skjnldsv commented on apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
> +		},
I'm sure we have more than this to check against emails strings :wink:

2021-08-19 21:26 UTC, skjnldsv approved these changes

2021-08-19 21:26 UTC, skjnldsv commented
Good for me, other tiny comments can be addressed in follow-up :)

2021-08-20 08:46 UTC, nickvergessen commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +			{{ t('settings', accountProperty) }}
This does not work for translations (unless it is garanteed that the account property string is still being translated in another place)

2021-08-20 08:48 UTC, nickvergessen commented on apps/settings/src/constants/AccountPropertyConstants.js
> +	WEBSITE: 'Website',
```suggestion
	ADDRESS: t('settings', 'Address'),
	AVATAR: t('settings', 'Avatar'),
	DISPLAYNAME: t('settings', 'Full name'),
	EMAIL: t('settings', 'Email'),
	EMAIL_COLLECTION: t('settings', 'Additional Email'),
	PHONE: t('settings', 'Phone'),
	TWITTER: t('settings', 'Twitter'),
	WEBSITE: t('settings', 'Website'),
```

2021-08-23 23:06 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/DisplayNameSection/DisplayNameSection.vue
> +		@submit.stop.prevent="() => {}">
`form` has been removed, along with other validation improvements as we no longer use `checkValidity` from HTMLFormElement :)

2021-08-23 23:06 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
> +		},
Validation improved :)

2021-08-23 23:07 UTC, Pytal commented on apps/settings/src/constants/AccountPropertyConstants.js
> +	WEBSITE: 'Website',
Translated strings in :)

2021-08-23 23:07 UTC, Pytal commented
/compile /

2021-08-23 23:10 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/EmailSection/Email.vue
> +		},
Validation improved based on `FILTER_VALIDATE_EMAIL` :) https://github.com/nextcloud/server/blob/079f76ab12730eb9ea107bac9b4041cd136f2446/apps/provisioning_api/lib/Controller/UsersController.php#L841

2021-08-23 23:13 UTC, Pytal commented on apps/settings/src/constants/AccountPropertyConstants.js
> +	WEBSITE: 'Website',
Translated strings are in :)

2021-08-24 23:01 UTC, Pytal commented
/compile /

2021-08-26 20:07 UTC, juliusknorr approved these changes

2021-08-26 20:09 UTC, merged