let the owner restore files if they where moved out of a shared folder
nextcloud/server pull request #2802
Opened 2016-12-21 14:44 UTC by schiessle

add a copy to the owners trash bin if another user moves a file out of a shared folder

cc @nickvergessen

2016-12-21 15:18 UTC, icewind1991 requested changes

2016-12-21 15:18 UTC, icewind1991 commented on apps/files_trashbin/lib/Storage.php
> +			if($sourceOwner !== $targetOwner
comparing `$view->getFileInfo($oldPath)->getStorage() !== $view->getFileInfo($newPath)->getStorage() && $sourceStorage->instanceOfStorage(SharedStorage::class)` will be more robust in cases where you move between 2 shares.

2016-12-21 15:18 UTC, icewind1991 commented on apps/files_trashbin/lib/Storage.php
> +				&& $sourceStorage->instanceOfStorage(SharedStorage::class)
iirc using `SharedStorage::class` will throw an error when the sharing app is disabled, using the string directly should be fine

2016-12-21 15:19 UTC, icewind1991 commented
What happens if both users try to restore their separate copies?

2016-12-21 15:30 UTC, schiessle commented
> What happens if both users try to restore their separate copies?

The file is only in the trashbin the owner, so only he can restore it. If the owner restores it and later the share recipient tries to move it back he will get the typical conflict dialog. If the recipient first move it back and then the owner restores it the restored file will be names "file (restored).txt"

2016-12-21 16:08 UTC, icewind1991 approved these changes

2016-12-22 10:00 UTC, MorrisJobke approved these changes
Tested and works 👍

2016-12-22 10:00 UTC, merged