Added support for transferring incoming file shares.
nextcloud/server pull request #28118
Opened 2021-07-22 13:50 UTC by ipasanec

@PVince81 

- new option `--transfer-incoming-shares=1 | 0`
- new config.php option `'transfer-incoming-shares' => true | false`

The command line option overrules the config.php option.

2021-07-22 15:03 UTC, miaulalala submitted a review, later dismissed

2021-07-22 15:03 UTC, miaulalala commented on apps/files/lib/Command/TransferOwnership.php
> +					break;
If you assume `false` you can avoid this case

2021-07-22 15:03 UTC, miaulalala commented on apps/files/lib/Service/OwnershipTransferService.php
> +										/* string $path */): array {
If you don't need `$path` any more, you should remove it.

2021-07-23 09:35 UTC, ipasanec commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
I changed it.
I clarified in the description that only file shares are transferred.

2021-07-23 09:35 UTC, ipasanec commented on apps/files/lib/Command/TransferOwnership.php
> +					break;
I changed the code. I hope that I understood everything right.
But at least the code is shorter with same behaviour.

2021-07-23 09:36 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +										/* string $path */): array {
I removed it.
Thanks for the review!

2021-07-23 09:48 UTC, miaulalala commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
I saw that you changed line 95 to `false`. I'm sorry for confusing you here! - this should stay null, but you can add an additional parameter at the end of `addOption` to declare a default value that gets passed if the user does not specify a value, so you don't need to cover a `NULL` case at all.

So your code would look like this:

```php
)->addOption(
    'transfer-incoming-shares',
    null,
    InputOption::VALUE_OPTIONAL,
    'transfer incoming shares to destination user',
    false
);

```

2021-07-23 10:58 UTC, ipasanec commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
Learned something today :-)
I changed the default value to `'2'`. Because `'0' == false` the third case would never occur with `false`.

2021-07-23 11:47 UTC, miaulalala commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
Why do you need the third option?

2021-07-23 12:03 UTC, ipasanec commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
The third option is for looking up the config.php to define standard behaviour when no option is given.
Of course, it is debatable if this functionality should stay there. (originally it was a customer requirement)

2021-07-23 12:07 UTC, miaulalala commented on apps/files/lib/Command/TransferOwnership.php
> +				'transfer incoming shares to destination user'
Ah makes sense! :+1:

2021-08-09 05:15 UTC, PVince81 reviewed
Had a deeper look at the logic and added some comments

2021-08-09 05:15 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +						if ($share->getNodeId() === $destinationShare->getNodeId()) {
I wonder if we should have used the node id as key for the destination shares for faster lookup ?

this would remove the need to iterate over all destination shares several times and to remove entries in the middle

2021-08-09 05:15 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +							if ($destinationShare->getPermissions() < $share->getPermissions()) {
maybe add code comment: "keep the share which has the most permissions and discard the other one"

2021-08-09 05:15 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +					$this->userMountCache->clear();
I guess you could move this into the if condition below as we only need to refetch the node id when reassigning

2021-08-09 05:15 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +					if ($sameFileSharedWithDestination === false) {
if "$shareDeleted" is true, do we still need to come here ?

2021-08-16 07:21 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +			$shares = array_merge($shares, $sharePage);
I changed the assembly of the array. Maybe I shoud change it for the original code too?

2021-08-16 07:21 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +								   OutputInterface $output) {
Oops, done.

2021-08-16 07:23 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +						if ($share->getNodeId() === $destinationShare->getNodeId()) {
I changed it accordingly.

2021-08-16 07:23 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +							if ($destinationShare->getPermissions() < $share->getPermissions()) {
Done.

2021-08-16 07:25 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +					$this->userMountCache->clear();
I did it somehow. Due to the changed code structure it appears now two times in the code.

2021-08-16 07:26 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +					if ($sameFileSharedWithDestination === false) {
I think the new code structure resolved this.

2021-08-16 07:28 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +			$sharePage = $this->shareManager->getSharedWith($sourceUid, IShare::TYPE_USER, null, 50, $offset);
I nam uncertain how to document this. Do you mean a change of the command name, like `--transfer-incoming-usershares`?

2021-08-16 09:49 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +			$shares = array_merge($shares, $sharePage);
as you like. it's fine to leave it

2021-08-18 09:35 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +			$sharePage = $this->shareManager->getSharedWith($sourceUid, IShare::TYPE_USER, null, 50, $offset);
you could simply add a hint in the help text from the command's help

2021-08-18 10:52 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +			$sharePage = $this->shareManager->getSharedWith($sourceUid, IShare::TYPE_USER, null, 50, $offset);
I changed the help text of the command and of the option.

2021-08-18 19:57 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> + * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
oops, sneaky space

2021-08-18 20:02 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +										$addKeys = false): array {
please add type to make the bot happy

2021-08-18 21:18 UTC, PVince81 commented
- [ ] BUG: must not transfer incoming share if not in the requested path:
    - user2 shares "test" with user1
    - user1 creates dir "sub"
    - `occ files:transfer-ownership user1 user2 --path=sub -vvv --transfer-incoming-shares=1`
    - expected: "test" stays
    - actual: "test" was transferred even though it was not in "sub"

- [ ] BUG: transferred incoming share doesn't stay in folder
    - user2 shares "test" with user1
    - user1 creates dir "sub"
    - user1 moves "test" into "sub"
    - `occ files:transfer-ownership user1 user2 --path=sub -vvv --transfer-incoming-shares=1`
    - expected: "test" is inside "sub" for user2
    - actual: "test" is outside of "sub" and even outside the transferred folder

2021-08-18 21:27 UTC, PVince81 requested changes
Thanks for the changes so far.
I had a few more comments after doing some tests.

See test results above.
I also took the liberty to push an integration test to your branch for the reported cases :smile:

2021-08-18 21:27 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +					// Keep the share which has the most permissions and discard the other one.
I was not able to think of a scenario where a user is receiving the same node through different **user** shares.
It is usually possible by having a user share and group share with different permissions.

Did you have a scenario in mind ? Otherwise I'm not sure if we need this code, but keeping it doesn't hurt.

2021-08-19 08:19 UTC, ipasanec commented on apps/files/lib/Service/OwnershipTransferService.php
> +					$shares[] = $singleShare;
I had the fantas that it might be beneficial to performance(?)

2021-08-19 11:56 UTC, PVince81 commented on apps/files/lib/Service/OwnershipTransferService.php
> +					$shares[] = $singleShare;
Good question. I did a quick search but didn't find any post that didn't say "I didn't read the PHP engine code, but...".

I guess you can leave it, it doesn't hurt readibility

2021-08-27 14:14 UTC, PVince81 approved these changes
:+1: I hereby approve the code from @ipasanec 

second reviewer should also check my commits

2021-09-15 08:26 UTC, skjnldsv approved these changes

2021-09-15 08:26 UTC, merged

2021-09-15 09:48 UTC, PVince81 commented
/backport to stable22

2021-09-15 10:27 UTC, acsfer commented
Shouldn't be this documented too? 🤔

2021-09-15 12:14 UTC, PVince81 commented
I'll take care:

- [ ] update admin_docs for occ command
- [ ] add new setting in config.sample.php

2021-09-16 06:39 UTC, PVince81 commented
docs done!

2021-11-10 11:25 UTC, Vilasamuni commented
I've been looking for documentation about how to use this flag and it's not clear to me what the values mean. I've seen `--transfer-incoming-shares=1` and `--transfer-incoming-shares=2` but I haven't found any explanation of what `1` and `2` actually do.

I've got backups, but I'm wary about running commands on real-world data with flags that I don't understand.

Short term request: please explain to me what they do.
Medium term suggestion: update the documentation to make this clearer.

2021-11-10 12:51 UTC, ChristophWurst commented
> Short term request: please explain to me what they do.

https://github.com/nextcloud/server/pull/28118/files#diff-e299680f9e139f82c630e100e9a4750851e51598a493f185ce8fc7baf2544ea3R127-R147



> Medium term suggestion: update the documentation to make this clearer.

Please open a ticket at https://github.com/nextcloud/documentation/issues/new

2021-11-11 07:46 UTC, ipasanec commented
The basic usage is:
--transfer-incoming-shares=1 for transferring incoming shares explicitly and 0 for not transferring them explicitly.
This command line option overwrites the value of 'transferIncomingShares' in the config.php if set.
If nothing is set, neither in command line nor in config.php, incoming shares are not transferred.

The default value of '2' for an unset option is necessary to detect a missing value in the command line and give an error message to notify the user.
The only valid values for --transfer-incoming-shares are 0 or 1.

btw. there is no --include-incoming-shares option. (It was changed in the original project, hence some variables use 'include' in the name)