Add ETag validation to appstore requests
nextcloud/server pull request #2814
Opened 2016-12-22 08:50 UTC by rullzer

* If the ETag if present store it
* If a stored ETag is present then pass it along (with the original
response) to get
* Add tests
* Added files to classmap

2016-12-22 09:48 UTC, nickvergessen submitted a review, later dismissed

2016-12-22 09:48 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/Exception/NotModifiedException.php
> +namespace OC\App\AppStore\Fetcher\Exception;
header missing

2017-01-02 14:28 UTC, MorrisJobke approved these changes

2017-01-05 12:46 UTC, nickvergessen requested changes

2017-01-05 12:46 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +		if ($ETag !== null) {
docs say string, so `''` ?

2017-01-05 12:46 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +use OC\App\AppStore\Fetcher\Exception\NotModifiedException;
Does not exist anymore?

2017-01-05 12:46 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +	 * @throws NotModifiedException
Undefined class

2017-01-05 12:46 UTC, nickvergessen commented on lib/private/App/AppStore/Fetcher/Fetcher.php
> +		} catch (NotModifiedException $e) {
Undefined class

2017-01-05 15:36 UTC, rullzer commented
@nickvergessen please have another look

2017-01-09 13:55 UTC, nickvergessen approved these changes
works

2017-01-09 13:56 UTC, merged