WIP: Implement Admin Delegation
nextcloud/server pull request #28189
Opened 2021-07-27 10:43 UTC by CarlSchwan

## Current status

* settings can be marked as "allow-delegation" in the app info.xml file
* Once marked as allow-delegation they are available in a new setting category in the admin category. In it an admin can select some groups and give them access to the specified setting
* Once a normal user get access, they can see the new setting in their setting navigation bar and access it
* Controller using the new annotation in their action `@AuthorizedAdminSetting(OCA/<app>/Settings/AdminSettings.php)` can be used by the user (who has the authorization for the admin)

## Stuff that still needs to be done

* Tests, a lot of tests :)
* setAppValue and stuff
* When the app is disabled, the authorization should disappears too, not so sure how I want to do that yet unfortunately

2021-07-27 10:58 UTC, juliushaertl reviewed
Just skimmed it quickly, seems good from the general approach

2021-07-27 10:58 UTC, juliushaertl commented on lib/public/AppFramework/Http/ContentSecurityPolicy.php
> +	protected $evalScriptAllowed = true;
:warning:  Debugging leftover?

2021-07-27 10:58 UTC, juliushaertl commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +			if ($this->reflector->hasAnnotation('AuthorizedAdminSetting')) {
I'd give that a more descriptive name probably like AllowDeletegatedAdminAccess so that it is a bit more clear what it does

2021-07-27 10:58 UTC, juliushaertl commented
> When the app is disabled, the authorization should disappears too, not so sure how I want to do that yet unfortunately

Any specific reason you went for a app that just exposes the delegation settings? I think that could probably also just be part of settings and we can have a configuration option then to turn it off.

2021-07-27 11:00 UTC, juliushaertl commented on apps/adminrightsubgranting/.travis.yml
> +sudo: false
:fire: We don't use travis anymore

2021-07-27 11:02 UTC, juliushaertl commented on core/Migrations/Version23000Date20210721100600.php
> +			$table->addForeignKeyConstraint($groupTable, array("group_id"), array("gid"), array("onUpdate" => "CASCADE"));
I don't remember exactly but foreign key constraints caused issues on some database backends, so that would be something to test carefully.

2021-07-27 11:04 UTC, juliushaertl commented on core/Migrations/Version23000Date20210721100600.php
> +			$table->addForeignKeyConstraint($groupTable, array("group_id"), array("gid"), array("onUpdate" => "CASCADE"));
Also groups might not always be in that table for other user backends, so the better approach would be to listen to an event on group changes, however the gid is something that cannot be updated anyways in Nextcloud.

2021-07-27 11:05 UTC, juliushaertl commented on apps/adminrightsubgranting/lib/Service/AuthorizedGroupService.php
> +		$authorizedGroup->setGroupId($groupId);
Make sure to also cleanup in case the group itself gets removed

2021-07-27 11:40 UTC, CarlSchwan commented on apps/adminrightsubgranting/.travis.yml
> +sudo: false
We need to update the apps template generator then :) I could probably give it a try soon...

2021-07-27 11:42 UTC, CarlSchwan commented on core/Migrations/Version23000Date20210721100600.php
> +			$table->addForeignKeyConstraint($groupTable, array("group_id"), array("gid"), array("onUpdate" => "CASCADE"));
So I guess I will need to use IGroupManager to get the list of groups and won't be able to just join with one single SQL query with the oc_groups table :(

2021-07-29 13:22 UTC, CarlSchwan commented
So my next big problem to solve is how to handle the setAppValue and the `http://localhost/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/<key>` API. Currently the bigger problem is that an appvalue is not mapped to any setting, so if a user has authorization for a setting page, we can't know which appValue they are authorized to edit.

I believe adding a simple mapping `['key1" => AdminSetting::class, "key2" => ShareAdminSetting::class]` somewhere and use that to check if the user has could work but that sounds like a big change, unfortunately. Does anyone have a better idea? :)

2021-08-02 14:33 UTC, PVince81 commented
when setting up from scratch I get this on the CLI:
```
PHP Fatal error:  Cannot declare class OCA\AdminRightSubgranting\Migration\Version23000Date20210721100600, because the name is already in use in /srv/www/htdocs/server/core/Migrations/Version23000Date20210721100600.php on line 32
```

2021-08-02 14:44 UTC, PVince81 commented
@CarlSchwan do I understand correctly that this allows only a whole page of settings or a section, not specific setting strings ?

2021-08-02 20:51 UTC, juliushaertl commented
> So my next big problem to solve is how to handle the setAppValue and the `http://localhost/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/<key>` API. Currently the bigger problem is that an appvalue is not mapped to any setting, so if a user has authorization for a setting page, we can't know which appValue they are authorized to edit.
> 
> I believe adding a simple mapping `['key1" => AdminSetting::class, "key2" => ShareAdminSetting::class]` somewhere and use that to check if the user has could work but that sounds like a big change, unfortunately. Does anyone have a better idea? :)

I don't have a good idea right away, but that is somewhat related to the idea from https://github.com/nextcloud/server/issues/18465 where with a declarative definition of app config values we could indicate delegation of certain config keys. So maybe some kind of mapping could be an intermediate step to allow delegation of settings for now where it is required.

2021-08-02 21:00 UTC, juliushaertl commented on apps/settings/lib/Controller/AuthorizedGroupController.php
> +		}
Might be a bit shorter to use 
- `$groupsToAdd = array_diff($new, $old);`
- `$groupsToRemove = array_diff($old, $new);`

2021-08-03 11:24 UTC, CarlSchwan commented
> @CarlSchwan do I understand correctly that this allows only a whole page of settings or a section, not specific setting strings ?

@PVince81  Yes it allows a while page of settings and will display a section if at least one of the setting inside of it is authorized. For the specific setting strings, it's needed for the ISettings class to declare which setting string they can edit so that it's possible to modify these settings.

> I don't have a good idea right away, but that is somewhat related to the idea from #18465 where with a declarative definition of app config values we could indicate delegation of certain config keys. So maybe some kind of mapping could be an intermediate step to allow delegation of settings for now where it is required.

@juliushaertl The linked issue looks interesting. If we decide that this is something we want, it would probably be better to do it before finishing this feature otherwise we will have two mappings :(

2021-08-06 11:45 UTC, CarlSchwan commented on apps/settings/lib/Controller/AuthorizedGroupController.php
> +		}
Not really because the two array that are compared are not using the same format (JSON vs array of IGroup object)

2021-08-23 09:40 UTC, juliushaertl commented on lib/public/Settings/IDelegatedSettings.php
> +	public function getAuthorizedAppConfig(): array;
> @juliushaertl The linked issue looks interesting. If we decide that this is something we want, it would probably be better to do it before finishing this feature otherwise we will have two mappings :(

I'd say that is fine for now with the dedicated method as the other implementation idea was not scheduled yet, especially since the #18465 is a more complex change, I'd rather get this in first and move on.

2021-08-23 10:52 UTC, CarlSchwan commented on lib/public/Settings/IDelegatedSettings.php
> +	public function getAuthorizedAppConfig(): array;
Yeah, I looked shortly how the declarative configs could be done and there are quite a few edge cases that will need to be handled (e.g. LDAP configs with uses prefix for the different servers). It's material for another task.

2021-08-23 13:35 UTC, skjnldsv commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		$user = $userSession->getUser();
Dependency injection?

2021-08-23 13:36 UTC, skjnldsv commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		$isAdmin = $this->groupManager->isAdmin($user->getUID());
`Cannot call method getUID on possibly null value`

2021-08-23 13:38 UTC, skjnldsv commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +		//}
```suggestion
```

2021-08-23 13:40 UTC, skjnldsv commented on apps/settings/lib/Settings/Admin/Delegation.php
> +		$this->appName = Application::APP_ID;
Is this needed?

2021-08-23 13:40 UTC, skjnldsv commented on apps/settings/lib/Settings/Admin/Delegation.php
> +	protected $appName;
Is this needed?

2021-08-23 13:42 UTC, skjnldsv commented on apps/settings/lib/Settings/Admin/Sharing.php
> +	}
Nice, was wondering which approach you were gonna take! :+1:

2021-08-23 13:43 UTC, skjnldsv commented on apps/settings/src/main-admin-delegation.js
> +	},
You can pass that directly in the AdminDelegating.vue
You don't need to import the loadState in the main js entry.

2021-08-23 13:45 UTC, skjnldsv commented
Added a few comments that are no blockers imho.
Let's fix the CI first.

2021-08-24 09:38 UTC, CarlSchwan commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		$isAdmin = $this->groupManager->isAdmin($user->getUID());
I added an additional isLoggedIn check

2021-08-25 11:35 UTC, LukasReschke commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		}
Is there any specific reason we call this? In other places in the code we also don't call this and just trust our middleware :-)

2021-08-25 11:35 UTC, LukasReschke commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		$allowed = true;
Can we default to `false` here and explicitly set it to `true`? Or use `$allowed = $isAdmin`?

Feels otherwise like something that could break in the future :)

2021-08-25 11:35 UTC, LukasReschke commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	 * Find AuthorizedNote by id.
```suggestion
	 * Find AuthorizedGroup by id.
```

2021-08-25 11:35 UTC, LukasReschke commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	private $mapper;
```suggestion
	private AuthorizedGroupMapper $mapper;
```

Wouldn't this also be possible? :-) (or do we support older PHP releases that don't support this?)

2021-08-25 11:35 UTC, LukasReschke commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	public function findAll(): array {
Can we add a typehint of array of X here? :-)

2021-08-25 11:35 UTC, LukasReschke commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +			throw new NotFoundException($e->getMessage());
I'm a little bit reluctant with returning error exception content directly. Are we suer there's never something sensitive in here?

2021-08-25 11:35 UTC, LukasReschke commented on apps/settings/lib/Settings/Admin/Mail.php
>  	 */
```suggestion
	 * @param IConfig $config
	 * @param IL10N $l
	 */
```

2021-08-25 12:11 UTC, juliushaertl commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	private $mapper;
We still have 7.3 support and that is 7.4+ only https://php.watch/versions/7.4/typed-properties

2021-08-25 12:13 UTC, LukasReschke commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	private $mapper;
TIL! Thanks Julius :)

2021-08-25 12:13 UTC, CarlSchwan commented on apps/provisioning_api/lib/Controller/AppConfigController.php
> +		}
psalm wasn't happy see https://github.com/nextcloud/server/pull/28189#discussion_r693978021. Maybe the check could be just if $user !== null :)

2021-08-25 12:15 UTC, CarlSchwan commented on apps/settings/lib/Service/AuthorizedGroupService.php
> +	private $mapper;
Yeah unfortunately we still live in php 7.3 so we only have phpdoc for now.

2021-08-30 10:21 UTC, CarlSchwan commented
Made all the changes requested during the review. Please take a look at resources/app-info-shipped.xsd and resources/app-info.xsd for the xsd changes. The settings entries are also now correctly sorted and I renamed the user-facing strings from Admin right delegation to admin right privilege. 

While doing the xsd stuff, I also found a small typo fixed in https://github.com/nextcloud/server/pull/28646 Please review :D

2021-08-30 11:40 UTC, kesselb commented on apps/settings/lib/Controller/Errors.php
> +	protected function handleNotFound(\Closure $callback): DataResponse {
In mail we use a middleware to catch common exceptions and transform them into proper status codes: https://github.com/nextcloud/mail/blob/master/lib/Http/Middleware/ErrorMiddleware.php (just as  hint for a different approach).

`handleNotFound` is not called. Do we need this trait?

2021-08-30 11:45 UTC, CarlSchwan commented on apps/settings/lib/Controller/Errors.php
> +	protected function handleNotFound(\Closure $callback): DataResponse {
Not anymore it seems, I think I copied it from another place and when refactoring this code I also removed the usage

2021-09-01 21:17 UTC, kesselb reviewed
Nice work :+1: 

- please increase the version number in appinfo/info.xml (otherwise the tables are not created)
- add `@AuthorizedAdminSetting(settings=OCA\Settings\Settings\Admin\Overview)` to `MailSettingsController` (to make changing the mail settings work when delegated)
- ~changing the background job mode does not work. it seems that some logic in provisioning_api is missing. note that provisioning_api is a generic controller to update configuration values. we need some logic to allow certain configuration keys for delegated users in provisioning_api app or add a custom controller to settings app to change background mode.~ you already know :see_no_evil:

2021-09-01 21:28 UTC, CarlSchwan commented on lib/private/Settings/AuthorizedGroup.php
> +		$this->addType('id','integer');
Copied from https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#database, I will submit a PR tomorrow to change it there too

2021-09-01 21:32 UTC, CarlSchwan commented on lib/private/Settings/Manager.php
> +			$setting = $this->container->get($class);
hmm good question, I will revert and probably also migrate to the ContainerExceptionInterface :see_no_evil:

2021-09-02 08:47 UTC, kesselb commented on lib/private/Settings/AuthorizedGroup.php
> +		$this->addType('id','integer');
I think it's fine to have it as example in the app tutorial.

2021-09-02 19:47 UTC, CarlSchwan commented
> Nice work +1
> 
>     * please increase the version number in appinfo/info.xml (otherwise the tables are not created)

I'm not sure which one :D The migrations are in core, I guess I should move it to the setting applications and update the setting app version?

Otherwise, all the other comments have been worked on. I will be doing a few more tests tomorrow to make I didn't miss any other authorzedConfigs or controller stuff.

2021-09-02 20:52 UTC, kesselb commented
> I'm not sure which one :D The migrations are in core, I guess I should move it to the setting applications and update the setting app version?

Good point :laughing: I run into the missing tables when switching to your branch and bumped the version number in settings to trigger the db update. Indeed the migration does not belong to settings but the version bump was enough to trigger the migration. 

https://github.com/nextcloud/server/blob/3899dba3523a578b12285423fa433d3d2965158c/version.php#L29-L33 

Looks like the right number to increase.

2021-09-03 07:08 UTC, CarlSchwan commented
> > I'm not sure which one :D The migrations are in core, I guess I should move it to the setting applications and update the setting app version?
> 
> Good point laughing I run into the missing tables when switching to your branch and bumped the version number in settings to trigger the db update. Indeed the migration does not belong to settings but the version bump was enough to trigger the migration.
> 
> https://github.com/nextcloud/server/blob/3899dba3523a578b12285423fa433d3d2965158c/version.php#L29-L33
> 
> Looks like the right number to increase.

Yes it worked after changing this number I was prompted to update the server and the migration was run.

2021-09-03 09:56 UTC, skjnldsv approved these changes

2021-09-03 13:21 UTC, ChristophWurst commented
> settings can be marked as "allow-delegation" in the app info.xml file

Is this really necessary? You can already check if the setting implements the new interface. Isn't that enough? Feels like there could be some weird inconsistency between what's in the xml vs what the code says. I would take the code as single source of truth.

2021-09-17 10:30 UTC, CarlSchwan commented
> > settings can be marked as "allow-delegation" in the app info.xml file
> 
> Is this really necessary? You can already check if the setting implements the new interface. Isn't that enough? Feels like there could be some weird inconsistency between what's in the xml vs what the code says. I would take the code as single source of truth.

Sorry for the late reply, the allow-delegation thing in the app info.xml allows to simplify fetching of all the settings compatible with this feature and display them in the admin setting page. Let me see if I can find a simpler solution.

2021-09-17 10:36 UTC, ChristophWurst commented
> Sorry for the late reply, the allow-delegation thing in the app info.xml allows to simplify fetching of all the settings compatible with this feature and display them in the admin setting page. Let me see if I can find a simpler solution.

Yes but you can also get this info by checking the registered classes, right? You can check a class' interfaces without creating an instance: https://www.php.net/manual/en/function.class-implements.php. Just check if your new interface is in that list :)

2021-09-20 15:52 UTC, PVince81 commented
/compile amend /

2021-09-20 16:02 UTC, PVince81 reviewed
see comments, mostly code style issues

2021-09-20 16:02 UTC, PVince81 commented on lib/private/Settings/Manager.php
> +				return in_array(get_class($settings), $authorizedSettingsClasses);
add `true` for strict comparison, if applicable

2021-09-20 16:02 UTC, PVince81 commented on lib/private/Settings/Manager.php
> +				if (in_array(get_class($setting), $authorizedSettingsClasses)) {
add `true` for strict comparison ?

2021-09-20 16:09 UTC, CarlSchwan commented
/compile amend /

2021-09-20 16:29 UTC, PVince81 approved these changes
:+1:

2021-09-27 13:11 UTC, artonge requested changes
Nice work.

I mostly made some readability suggestions. Up to you to use them ;)

2021-09-27 18:14 UTC, ChristophWurst commented on core/Migrations/Version23000Date20210721100600.php
> +		if (!$schema->hasTable('authorized_groups')) {
Nitpick: IMO you can drop the if. The table won't be there. If it is, then Nextcloud ran the migration twice, which it must not.

2021-09-27 18:24 UTC, CarlSchwan commented
Thanks for the big review @artonge, I applied most of your comments. I will rebase tomorrow and do some more testing to make sure that there was no logic changes.

2021-09-28 09:52 UTC, artonge requested changes

2021-09-28 09:52 UTC, artonge commented on apps/settings/src/components/AdminDelegation/GroupSelect.vue
> +				 */
Can be remove, it was simply as a note for you :wink:

```suggestion
```

2021-09-28 09:52 UTC, artonge commented on apps/settings/src/components/AdminDelegation/GroupSelect.vue
> +				 */
Oh, and the import are not there, I added a comment for that too

2021-09-28 09:52 UTC, artonge commented on apps/settings/src/components/AdminDelegation/GroupSelect.vue
> +import axios from '@nextcloud/axios'
```suggestion
import Multiselect from '@nextcloud/vue/dist/Components/Multiselect'
import { generateUrl } from '@nextcloud/router'
import axios from '@nextcloud/axios'
import { showError } from '@nextcloud/dialogs'

import logger from './logger'
```

2021-09-28 09:52 UTC, artonge commented on apps/settings/src/components/AdminDelegation/GroupSelect.vue
> +		initialState: {
I don't have any proposition as I don't really understand what is the diff between `group` and `initialState` :sweat_smile:

2021-09-28 09:52 UTC, artonge commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> -			$templateParameters['admin'] = $this->formatAdminSections(
Oh, yes, this is only some template variable used in `apps/settings/templates/settings/frame.php`. Thanks

2021-09-28 09:52 UTC, artonge commented on apps/settings/src/components/AdminDelegation/GroupSelect.vue
> +		initialState: {
Actually, the original names might be better, no ?

`:groups="availableGroups" :initial-state="authorizedGroups"`

2021-09-28 10:00 UTC, CarlSchwan commented on apps/settings/lib/Controller/AuthorizedGroupController.php
> +		return new DataResponse(['valid' => true]);
I reverted this change, unfortunately it didn't work since the service expected the object and the transformation from object array to string array while clever broke this.

2021-09-29 09:00 UTC, CarlSchwan commented
/compile amend /

2021-09-29 11:28 UTC, CarlSchwan commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +		$this->userSession = $this->createMock(IUserSession::class);
I'm a bit confused, both authorizedGroupMapper and userSession are now null here when generating a mock for them. Does anybody has an idea why?

2021-09-29 12:26 UTC, PVince81 approved these changes
:+1: code looks good

2021-09-29 20:48 UTC, merged

2022-05-30 08:42 UTC, danxuliu commented
@CarlSchwan There is a change that [was going to be reverted](https://github.com/nextcloud/server/pull/28189#discussion_r700587967), but in the end it was not:
https://github.com/nextcloud/server/pull/28189/files#diff-50b846648bbc8a7ca74bae8cf096ee0297423bc236f56ba05c5f8a727519f615L109-R130
Was that just an oversight or is there a reason?

Due to that change if an app specifies a class that does not exist in the `<admin-section>` field of _info.xml_ the settings will not load. Of course in that case the app should be fixed :-) but until that happens it would be better if the rest of the settings still work and the error is simply logged.

2022-05-30 09:39 UTC, danxuliu commented
> > @CarlSchwan There is a change that [was going to be reverted](https://github.com/nextcloud/server/pull/28189#discussion_r700587967), but in the end it was not: https://github.com/nextcloud/server/pull/28189/files#diff-50b846648bbc8a7ca74bae8cf096ee0297423bc236f56ba05c5f8a727519f615L109-R130 Was that just an oversight or is there a reason?
> > Due to that change if an app specifies a class that does not exist in the `<admin-section>` field of _info.xml_ the settings will not load. Of course in that case the app should be fixed :-) but until that happens it would be better if the rest of the settings still work and the error is simply logged.
> 
> totally an oversight, I created #32655

Perfect, thanks!