Improve auto expiration hint
nextcloud/server pull request #28211
Opened 2021-07-28 10:59 UTC by szaimen

Fix #27496

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-28 11:47 UTC, szaimen commented
Failed test is unrelated, afaics

2021-07-28 11:47 UTC, szaimen commented
/backport to stable22

2021-07-28 11:47 UTC, szaimen commented
/backport to stable21

2021-07-28 11:47 UTC, szaimen commented
/backport to stable20

2021-07-28 12:01 UTC, artonge commented
Does this means that files will always expire and there is no way to keep the files in the trash for ever ?

2021-07-28 12:13 UTC, szaimen commented
> Does this mean that files will always expire and there is no way to keep the files in the trash forever?

Actually, I don't know. lets cc @PVince81 and @icewind1991 on this

2021-07-29 00:07 UTC, Pytal requested changes

2021-07-29 00:07 UTC, Pytal commented on apps/files_trashbin/lib/Command/ExpireTrash.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
```suggestion
			$output->writeln("Auto expiration is configured - keeps files and folders in the trash bin for 30 days and automatically deletes anytime after that if space is needed (note: files may not be deleted if space is not needed)");
```
As described here https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin :)

2021-07-29 00:07 UTC, Pytal commented on apps/files_versions/lib/Command/ExpireVersions.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
```suggestion
			$output->writeln("Auto expiration is configured - expiration will be handled automatically according to the expiration patterns detailed at the following link https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html.");
```
Mentioned link https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html :)

2021-07-29 00:08 UTC, Pytal commented
> Does this mean that files will always expire and there is no way to keep the files in the trash forever?

Users may disable expiration https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#:~:text=space%20is%20needed)-,disabled,auto%20clean%20disabled%2C%20files%20and%20folders%20will%20be%20kept%20forever,-Defaults%20to%20auto :)

2021-07-29 10:07 UTC, artonge commented on apps/files_trashbin/lib/Command/ExpireTrash.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
Much clearer :+1:

2021-08-01 11:30 UTC, acsfer commented on apps/files_trashbin/lib/Command/ExpireTrash.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
Agree

2021-08-08 18:40 UTC, szaimen commented on apps/files_trashbin/lib/Command/ExpireTrash.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
done

2021-08-08 18:40 UTC, szaimen commented on apps/files_versions/lib/Command/ExpireVersions.php
> +			$output->writeln("Auto expiration is configured - expiration will be handled automatically.");
done

2021-08-08 18:42 UTC, szaimen commented
Thanks for the good suggestions @Pytal :)

2021-08-08 20:06 UTC, szaimen commented
Failing test is unelated

2021-08-08 20:18 UTC, PVince81 commented
> > Does this mean that files will always expire and there is no way to keep the files in the trash forever?
> 
> Actually, I don't know. lets cc @PVince81 and @icewind1991 on this

according to config.sample.php, it's possible to disable this with: `trashbin_retention_obligation` => 'disabled'.
not sure how those settings map to the CLI output

2021-08-09 20:22 UTC, Pytal approved these changes

2021-08-09 20:38 UTC, szaimen commented
Failing test is unrelated

2021-08-16 08:52 UTC, artonge approved these changes

2021-08-16 10:16 UTC, merged