Allow to report the remoteAddress
nextcloud/server pull request #28227
Opened 2021-07-29 06:59 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-29 18:39 UTC, szaimen commented
I think the failing test is unrelated

2021-07-29 18:57 UTC, szaimen commented
I think the failing test is unrelated

2021-07-29 19:06 UTC, nickvergessen requested changes

2021-07-29 19:06 UTC, nickvergessen commented on apps/files_sharing/lib/Activity/Providers/Downloads.php
> +			$subject = $this->l->t('{file} downloaded via public link from {remote-address}');
This breaks on updates. Old translation and syntax needs to be retained and the parameters must be counted to decide which way to use

2021-07-29 19:06 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
I heavily dislike this. It logs ip addresses in a user accessible way (hello gdpr/dsgvo) before ips are only in sysadmin logs.

2021-07-29 19:08 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
Yes, actually, this was the whole idea of this PR. So removing it again will make this PR probably useless...

2021-07-29 19:11 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
I'd like to discuss whether it could be possible to do this nonetheless in a dsgvo conform way.
My argumentation would be based on the idea that you as owner of your files would want to know who is accessing your files via a public link because you might would act accordingly if there are e.g. too many addresses that access the shared file.

2021-07-29 19:13 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
Is there maybe a way to anonymize the ip address in a way where it can still be used to identify how many/from where the remote PC comes? any idea?

2021-07-29 19:15 UTC, szaimen commented on apps/files_sharing/lib/Activity/Providers/Downloads.php
> +			$subject = $this->l->t('{file} downloaded via public link from {remote-address}');
How do I do that? do you have an example code where I can see what you suggest here?

2021-07-29 19:29 UTC, Pytal commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
@LukasReschke

2021-07-29 20:18 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
I was thinking about anonymizing the ip-addresses like e.g. done here https://complianz.io/are-your-ip-addresses-anonymized/#:~:text=how%20anonymizing%20ip%20addresses%20works
What do you think?

2021-07-29 21:00 UTC, szaimen commented on apps/files_sharing/lib/Activity/Providers/Downloads.php
> +			$subject = $this->l->t('{file} downloaded via public link from {remote-address}');
I think I found a way to do it. please have a look again

2021-07-29 21:02 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
I've now added an appvalue which disables this by default. I hope this solves the need to implement the feature in a dsgvo conform way. If it should still needed, I think the best approach would be anonymizing the ip addresses as said before.

2021-07-30 07:20 UTC, skjnldsv approved these changes

2021-08-02 19:08 UTC, juliushaertl commented on apps/files_sharing/lib/Controller/ShareController.php
> +		if ($this->config->getAppValue('files_sharing', 'download_ip_address_activity', '0') === "1") {
Should be documented somewhere

2021-08-02 19:10 UTC, juliushaertl commented on lib/public/RichObjectStrings/Definitions.php
> +			'app' => 'files_sharing',
```suggestion
			'app' => 'core',
```

2021-08-08 18:45 UTC, szaimen commented
Lets wait with this for a second review of @nickvergessen but I'd honestly rather remove the configuration value again because ip-addresses get anonymized now which is hopefully a vaild approach on the dsgvo concerns that nickvergessen had.

2021-08-08 18:55 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
I've also added ip-anonymization and would like to remove the config option again.

2021-08-18 07:26 UTC, kesselb commented
> Some input from kesselb starting here and below https://cloud.nextcloud.com/call/wejc2q9q#message_771871

To summarize my input: 

A. Good to fix notification spam when a user plays a video
B. Fine by me to show the ip address for a download / play

But A and B should be independent of each other. My approach for A would be to extend the event merger with a generic way to compare one event with another. I would try to add a new method to IEvent that accepts an callable. Event merger check do we have a callable to compare the events. Probably a bit nice would be an additional interface and a decorator for IEvent.

2021-11-18 08:23 UTC, wagnbeu0 commented
So my current setup is to anonymize the IP Adresses in Apache itself by changing the last ipv4 digits to 0. Can this have an impact on this app?

2022-03-06 19:08 UTC, kemoantemo commented
Why is this not implemented until now?

2022-03-07 13:15 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$parameters[] = $remoteAddress;
changed the implementation to only fix the bug

2022-03-07 13:15 UTC, szaimen commented on lib/public/RichObjectStrings/Definitions.php
> +			'app' => 'files_sharing',
not needed anymore

2022-03-07 13:33 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				if (isset($remoteAddressHash)) {
isset should not be needed? It can never not be there. It's always an md5 of something?

2022-03-07 13:34 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
```suggestion
				$parameters[] = $remoteAddressHash;
```

2022-03-07 13:34 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
```suggestion
				$parameters[] = $remoteAddressHash;
```

isset should not be needed? It can never not be there. It's always an md5 of something?

2022-03-07 13:34 UTC, nickvergessen approved these changes

2022-03-07 13:39 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
right, psalm said the same thing :D

2022-03-07 13:39 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
right, psalm said the same thing :D

2022-03-07 13:40 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
fixed

2022-03-07 13:40 UTC, szaimen commented on apps/files_sharing/lib/Controller/ShareController.php
> +				}
fixed

2022-03-07 14:18 UTC, szaimen commented
/backport to stable22

2022-03-07 18:36 UTC, Pytal approved these changes

2022-03-07 19:47 UTC, szaimen commented
/rebase for checking if all checks pass

2022-03-07 20:48 UTC, merged