Add navigation via info.xml (#26785)
nextcloud/server pull request #2822
Opened 2016-12-22 11:34 UTC by LukasReschke

* Read navigation information from info.xml

* Load files navigation elements from info.xml

* Add comment about ignoring the exception

From https://github.com/owncloud/core/pull/26785

2016-12-22 11:46 UTC, LukasReschke commented on apps/files/appinfo/info.xml
> +	</navigation>
Once merged requires to be added to https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/api/v1/release/info.xsd as well.

2016-12-22 12:21 UTC, nickvergessen commented on apps/files/appinfo/info.xml
> +	</navigation>
What I dislike about this is it drops the name tag by default, uses firstCaseUpper(appname). I think it's a trap for apps which then will accidently not have this translated anymore.

2016-12-22 12:24 UTC, nickvergessen requested changes

2016-12-22 12:24 UTC, nickvergessen commented on apps/files/img/app.svg
> +<svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="32" width="32" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.or
no viewbox no minification

2016-12-22 12:24 UTC, nickvergessen commented on apps/files/appinfo/info.xml
> +	</navigation>
Also this looks like an app can only have one? Should we wrap it in a "navigations" so we can have muliple?
Or should those apps just use the programmatic way then instead?

2016-12-22 14:21 UTC, LukasReschke commented on apps/files/appinfo/info.xml
> +	</navigation>
> What I dislike about this is it drops the name tag by default, uses firstCaseUpper(appname). I think it's a trap for apps which then will accidently not have this translated anymore.

We should probably work on getting our CI scripts running then in a way that it supports the `lang=` tag as seen at http://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml

2017-01-02 14:32 UTC, MorrisJobke commented on apps/files/img/app.svg
> +<svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="32" width="32" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.or
Done

2017-01-05 12:51 UTC, nickvergessen commented on apps/files/appinfo/info.xml
> +	</navigation>
Can also adjust the travis thing to translate `<navigation><name>` when its provided?

2017-01-26 05:04 UTC, MorrisJobke approved these changes
Tested and works 👍 

Regarding multiple entries: I would keep the info.xml with one entry. For multiple entries the app needs to use the normal OCP API.

2017-01-26 09:16 UTC, nickvergessen commented on apps/files/appinfo/info.xml
> +	</navigation>
@MorrisJobke can we add this simply? Extracting `<navigation><name>` automatically to travis?

2017-01-26 21:47 UTC, MorrisJobke commented on apps/files/appinfo/info.xml
> +	</navigation>
> @MorrisJobke can we add this simply? Extracting <navigation><name> automatically to travis?

Create me a ticket - I will look into extending it 😉

2017-01-27 08:45 UTC, nickvergessen approved these changes
I made the name non-optional.
I'm fine with this now and will create the translation issue.

2017-01-27 17:25 UTC, MorrisJobke commented
:+1: (ignore CI -.- there seems to be an issue with the autoloader check - I guess they released a new version between Job #1 and #2 - so one failed and one succeeded)

I will merge this.

2017-01-27 17:25 UTC, merged