[RFC] Refactor image handling
nextcloud/server pull request #28279
Opened 2021-08-01 22:01 UTC by J0WI

There are various tickets about poor image handling in Nextcloud.

- https://github.com/nextcloud/server/issues/13099
- https://github.com/nextcloud/server/issues/13552
- https://github.com/nextcloud/server/pull/16158
- https://github.com/nextcloud/server/pull/24166

Nextcloud uses the `OC_Image` wrapper which uses GD. But GD is [slow](https://github.com/jcupitt/php-vips-bench#results) and does not support formats like SVG. That's why some modules (avatar, preview and theming app) have implemented their own image handling.

This draft aims to replace the legacy `OC_Image` class with a generic `Image` class and a set of compatible backends using GD, Imagick, Gmagick or Vips. It turned out, that the `IImage` interface itself does not provide all methods and not all of them are meaningful for all backends (notably the [obsolete](https://www.php.net/manual/en/class.gdimage.php) GD resource). There's also no simple way to add additional file format support.

An alternative approach would be to pull a high level image library like [intervention/image](https://packagist.org/packages/intervention/image) or [imagine/imagine](https://packagist.org/packages/imagine/imagine).

The goal is, to provide a generic image handling that uses the fastest backend and all common and modern file types available on the host. And last but not least, to replace direct Imagick usage in avatar, preview and theming app and finally deprecate the legacy `OC_Image` class.

2022-08-22 08:08 UTC, CarlSchwan commented
Nice work, I'll review it tomorrow

2022-08-29 13:37 UTC, icewind1991 requested changes
Overall a great step forward

2022-08-29 13:37 UTC, icewind1991 commented on lib/private/Image/Vips.php
> +			if ($mimeType !== null) {
probably makes sense to factor out the mimetype->imagetype logic so it can be reused

2022-09-02 16:45 UTC, icewind1991 commented on lib/private/Image/Common.php
> +		return $this->valid() ? $this->mimeType : '';
Exception is fine for me to, but returning a `?string` at least hints the type system that the result should be checked for validity

2022-10-23 08:47 UTC, skjnldsv commented
Looks like a greaaaaat step forward! 
There are quite a few `static-code-analysis` errors to fix before we can properly review this @J0WI 
Can you fix them? :)

2024-08-16 09:45 UTC, sorbaugh commented
Hello @J0WI, it seems that some of the tickets you mentioned in the original comment have already been addressed so some the points have been addressed. I'm reopening this complex topic and would like to treat this as an "Overview" issue and maybe rescope it to the remaining open issues 🚀

2026-06-09 14:30 UTC, susnux commented
Hello :wave: 
currently here have been no activity in the last years.
If this is still actual feel free to reopen the pull request and resolve the conflicts so we can incorporate it into Nextcloud.
Thank you very much for your contribution!

2026-06-09 14:30 UTC, closed without merging