Already pass size difference to the cache updater to avoid calculation of the folder size to update
nextcloud/server pull request #28310
Opened 2021-08-04 13:41 UTC by juliushaertl

With S3 the scanner will never return anything so the updater always falls back to a full size calculation. Since we know the transferred filesize during upload, we can pass it as an optional parameter then in order to directly update the parent folder sizes.

2021-08-04 21:01 UTC, Pytal commented on apps/dav/lib/Connector/Sabre/File.php
> +			$storage->getUpdater()->update($internalPath, null, ($count-$previousFileSize));
Would a more explicit name for the $count variable be better?

2021-08-05 08:50 UTC, artonge requested changes

2021-08-05 08:50 UTC, artonge commented on apps/dav/lib/Connector/Sabre/File.php
> +			$storage->getUpdater()->update($internalPath, null, ($writtenByteCount - $previousFileSize));
To prevent undefined variable error ?

```suggestion
			$sizeDifference = null;
			if (isset($previousFileSize) && isset($previousFileSize)) {
				$sizeDifference = $writtenByteCount - $previousFileSize;
			}

			// since we skipped the view we need to scan and emit the hooks ourselves
			$storage->getUpdater()->update($internalPath, null, $sizeDifference);
```

2021-09-02 18:46 UTC, juliushaertl commented
Pushed a fix for the comment and an additional commit for another case where we can speed up updating the size:

Additionally the sizeDifference is also passed in the View when creating directories (which always have a difference of 0) and when calling file_put_contents where we know the size difference from the storage return value. This avoids an unnecessary size calculation when creating user avatars where it would have calculated the size of the appdata_*/avatar folder for each user creation call which would cause a high read load on databases with lots of users.

2021-09-02 22:09 UTC, Pytal commented on lib/private/Files/View.php
> +					$size = $operation === 'file_put_contents' ? $result : $size;
```suggestion
					$size = null;
					if ($operation === 'mkdir') {
						$size = 0;
					} elseif ($operation === 'file_put_contents') {
						$size = $result;
					}
```
Perhaps a clearer control flow :)

2021-09-07 08:55 UTC, artonge approved these changes
Besides @Pytal's change request, it is fine by me

2021-09-07 21:07 UTC, Pytal approved these changes
Yep, other than the comment above, good with me :)

2021-09-09 13:28 UTC, blizzz commented
CI is unhappy

2021-09-10 16:08 UTC, juliushaertl commented on lib/private/Files/View.php
> +					$this->writeUpdate($storage, $internalPath, null, $size);
:boom: Debugging the CI failure showed that I'm actually introducing an issue here by passing the total size as the size difference. Need to think about how we could still gain the performance improvement differently then.

2022-10-14 21:06 UTC, juliushaertl commented on lib/private/Files/View.php
> +					$this->writeUpdate($storage, $internalPath, null, $size);
Fixed by getting the previous file size in case of a write operation

2022-10-16 10:48 UTC, szaimen commented
Still CI failures...

2022-10-17 14:33 UTC, szaimen commented
failing tests look related to me...

2022-10-17 14:55 UTC, juliushaertl commented
Sorry, read the output wrong, will have a look

2023-02-21 20:21 UTC, juliushaertl commented
I haven't found a proper way yet to pass this along. I'll close this for now, but will keep a note to probably discuss further for future performance optimizations.

2023-02-21 20:21 UTC, closed without merging