Language section Vuetified
nextcloud/server pull request #28423
Opened 2021-08-14 01:00 UTC by Pytal

### To Do

- [x]  Pass initial state from server to client
- [x]  Create service
- [x]  Rewrite php markup and functionality in Vue `apps/settings/templates/settings/personal/persona.info.php`
- [x]  Reload on change
- [ ]  Check PHP tests
- [ ]  Rename language strings in other apps

### Note: The `TODO` comments are out-of-scope for this PR and will be addressed separately in future PRs

Contributes to #27869

2021-08-16 22:07 UTC, Pytal commented
/compile /

2021-08-17 14:48 UTC, artonge approved these changes
Looks good

2021-08-17 14:48 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +    width: 100%;
lint

2021-08-17 23:11 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
> +			<optgroup label="––––––––––" />
The option separator, I've updated the markup so it's more semantically clear :)

2021-08-17 23:11 UTC, Pytal commented
/compile amend /

2021-08-17 23:14 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +    width: 100%;
I linted it and no output 🤔 these styles were copied from the settings headers that are federation scoped :)

2021-08-18 12:10 UTC, artonge approved these changes

2021-08-18 12:10 UTC, artonge commented on apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
> +				──────────
Not sure what is the goal here, but could `<optgroup>` be usefull ? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

2021-08-18 12:10 UTC, artonge requested changes
Oups, misclick on approve

2021-08-18 21:19 UTC, Pytal commented
/compile /

2021-08-18 21:41 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
> +				──────────
Separator for common languages and other languages 👇

![image](https://user-images.githubusercontent.com/24800714/129975548-fb06c824-4863-4780-aab9-a1781099011f.png)

Legacy PHP markup had an empty group for the separator using `optgroup`, this markup does the same thing and is more aligned with what the user sees :)

2021-08-18 21:43 UTC, Pytal commented
/compile /

2021-08-19 10:33 UTC, artonge commented on apps/settings/src/components/PersonalInfo/LanguageSection/Language.vue
> +				──────────
Hmm, yeah, makes more sens :) thanks

2021-08-19 21:14 UTC, Pytal commented
/compile /

2021-08-24 23:48 UTC, Pytal commented
/compile /

2021-08-26 16:09 UTC, skjnldsv approved these changes

2021-08-26 16:18 UTC, artonge approved these changes

2021-08-26 20:04 UTC, juliusknorr approved these changes

2021-08-27 05:57 UTC, merged