improve webmanifest
nextcloud/server pull request #28459
Opened 2021-08-16 19:40 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-08-16 22:32 UTC, szaimen commented
```php
if (strpos(str_replace($this->urlGenerator->getWebroot(), '', $this->request->getRequestUri()), '/index.php/') === 0) {
```

2021-08-23 12:33 UTC, szaimen commented
/backport to stable22

2021-08-23 13:02 UTC, eneiluj approved these changes
:+1: 
Works fine with an empty app summary.

2021-08-23 13:11 UTC, eneiluj commented
Additional hint to try this PR:
To add a website as an app on Chromium based browsers, open the hamburger menu -> more tools -> create shortcut

2021-08-23 20:18 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			$start_url = $this->urlGenerator->getBaseUrl();
```suggestion
			$shortName = $this->themingDefaults->getName();
			$startUrl = $this->urlGenerator->getBaseUrl();
```

2021-08-23 20:19 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			'start_url' => $start_url,
```suggestion
			'short_name' => $shortName,
			'start_url' => $startUrl,
```

2021-08-23 20:25 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			}
That won't work as linkTo will use the actuall apps directory, which is not what the app route itself will be. E.g. if you have a separate apps2 directory the generated url would be /index.php/apps2/myapp instead of /index.php/apps/myapp.

Also while most frontend apps provide such a route, there is no guarantee that this is the actual entrypoint.

I think the best approach here would be to either just use the current url or get the navigation manager and try to find the entry for the app id, but both also have their limitations.

2021-08-23 20:25 UTC, juliushaertl requested changes, later dismissed
See inline

2021-08-23 20:38 UTC, bessw commented
1. Would it be possible to make it "installable" by adding a serviceworker?
It doesn't need to be something complicated, a do nothing serviceworker would be enough:
```js
self.addEventListener('install', event => {
  console.log('Service Worker installing.')
})

self.addEventListener('activate', event => {
  console.log('Service Worker activating.')
})
self.addEventListener('fetch', event => {
  // … optionally respond to this fetch in a useful way
})
```

2. Maybe tasks shortcuts would also be an interesting option to open apps:
https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts

2021-08-23 21:21 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
@juliushaertl Thanks for the review!
What about doing it like this:
```suggestion
			if (strpos($this->request->getRequestUri(), '/index.php/') !== false) {
				$start_url = $this->urlGenerator->getBaseUrl() . '/index.php/apps/' . $app . '/';
			} else {
				$start_url = $this->urlGenerator->getBaseUrl() . '/apps/' . $app . '/';
			}
```
I just didn't wanted to hardcode the apps directory but if it is always like this, it maybe makes sense to do so...

2021-08-23 22:11 UTC, szaimen commented
> 1. Would it be possible to make it "installable" by adding a serviceworker?
>    It doesn't need to be something complicated, a do nothing serviceworker would be enough:
> 
> ```js
> self.addEventListener('install', event => {
>   console.log('Service Worker installing.')
> })
> 
> self.addEventListener('activate', event => {
>   console.log('Service Worker activating.')
> })
> self.addEventListener('fetch', event => {
>   // … optionally respond to this fetch in a useful way
> })
> ```

Thanks for the idea @bessw! As this PR is a PHP change only and I think that it makes more sense that every app that wants to provide a service worker should do this on its own, is this something for a follow up.



> 2. Maybe tasks shortcuts would also be an interesting option to open apps:
>    https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts

Not sure about that since I am not sure where it would be useful. If any app wants to do this it can already do so. The PR here only covers the most basic usecases which is fine because it is already much better than how it is currently.

2021-08-23 22:24 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
Either way this doesn't need to match everything as any app is free to overwrite the manifest on itself like e.g. the bookmarks app already does. This PR shall cover most cases (but not all) as it is already a big improvement over how it currently is.

2021-08-24 09:42 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			$start_url = $this->urlGenerator->getBaseUrl();
done

2021-08-24 09:42 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			'start_url' => $start_url,
done

2021-08-24 09:43 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
@juliushaertl I've done it now this way. please have another look :)

2021-08-24 10:17 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
What about checking if there is a route with '/' as 'url'?
If there is such a route, then `BASE_URL/apps/APP_ID/` is fine.
Otherwise use the current url.

2021-08-24 10:30 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
@eneiluj how can I get the currentl url via PHP? This would probably need to be called directly in the php template during loading, no?
`$this->request->getRequestUri()` in this function only returns e.g. `https://192.168.179.192/apps/theming/manifest/mail?v=13`.

2021-08-24 10:32 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
But as I said before it only shall cover most cases and not all and since the /apps/ directory is the default, I think this is fine because any app that wants to have more complicated routing can and should implement the webmanifest on its own, imho.

2021-08-24 10:39 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
Or were you talking about something else?

2021-08-24 10:44 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
I'm saying maybe `BASE_URL/apps/APP_ID/whatever` is the app entry point so `BASE_URL/apps/APP_ID/` leads to nowhere and user will be redirected to NC home page.

As for the custom app directory, I don't think it affects the routing (but I'm not sure, never used it).

2021-08-24 10:47 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
Ahh okay, no I don't think that this is a problem since all apps that I've tried have the trailing slash in the URL directly when I click on the link in the appmenu before the app is loaded (I think it is the default Nextcloud routing)
Apps that I've tried are those:
![image](https://user-images.githubusercontent.com/42591237/130603689-d8e31b3c-ca41-437f-bf11-8ec34705ae4b.png)

2021-08-24 10:51 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
It's not about the trailing slash. Some apps might have no route for '/'. Imagine if the contacts app could only be reached at `https://my.nc.org/index.php/apps/contacts/contact-list` and that `https://my.nc.org/index.php/apps/contacts/` would lead to nowhere.

2021-08-24 10:54 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
> how can I get the currentl url via PHP?

I didn't realize the apps get the manifest with a separate request... An easy solution would have been the referrer header but it's not provided in NC. Then I don't know how to get the current url in this context...:grin:

2021-08-24 10:57 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
> It's not about the trailing slash. Some apps might have no route for '/'. Imagine if the contacts app could only be reached at https://my.nc.org/index.php/apps/contacts/contact-list and that https://my.nc.org/index.php/apps/contacts/ would lead to nowhere.

If that would be the case the app would also not be reachable via the appmenu since when you click on an app in the appmenu it always opens `BASE_URL/apps/APP_ID/` so you must provide such a route because otherwise your app cannot be opened via the appmenu, as far as I understand it...

2021-08-24 11:04 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
The navigation item target is defined by the app.
It can be set in info.xml, like that:
https://github.com/eneiluj/cospend-nc/blob/8a4b09298f14bd184fc39452c61ce30069f43591/appinfo/info.xml#L52-L60
or by calling `INavigationManager::add` like that:
https://github.com/eneiluj/integration_openproject/blob/2bc55d2503a6b35e49bcdc089de18fe458ff638a/lib/AppInfo/Application.php#L75-95

It can be whatever we want, even something outside Nextcloud.

2021-08-24 11:12 UTC, szaimen commented on apps/theming/lib/Controller/ThemingController.php
> +			}
Okay but as this would be a very specific usecase I think apps that need this should overwrite the webmanifest in this case on their own which the bookmarks app already does, btw.

2021-08-24 11:16 UTC, eneiluj commented on apps/theming/lib/Controller/ThemingController.php
> +			}
Yeah I agree. I'm fine with `BASE_URL/apps/APP_ID/` since the beginning :grin:. It's better than using NC base url as ` start_url` anyway.

2021-08-24 11:16 UTC, eneiluj approved these changes

2021-08-24 13:19 UTC, icewind1991 approved these changes

2021-08-24 13:34 UTC, szaimen commented
@juliushaertl are you fine when I merge this or is there still somethings that needs to be addressed?

2021-08-25 10:19 UTC, juliushaertl approved these changes

2021-08-25 10:21 UTC, szaimen commented
Thanks for the approval! :)

2021-08-25 10:21 UTC, merged