Port isTargetAllowed to share 2.0
nextcloud/server pull request #2847
Opened 2016-12-23 12:03 UTC by LukasReschke

From https://github.com/owncloud/core/pull/26615

2016-12-23 13:14 UTC, LukasReschke commented
Tests are failing. 🚀

2016-12-23 16:02 UTC, schiessle commented on lib/private/Files/Mount/MoveableMount.php
> +	 * @since 11.0
since 12.0 in our case

2017-01-11 07:55 UTC, rullzer commented
@icewind1991 I'd like to get your opinion on this as well

2017-01-11 14:28 UTC, icewind1991 requested changes
I'm not happy with the way this checks if the target is shared (do we really not have an existing method to do that?), getting the node and iterating over parents is needlessly expensive

2017-01-11 14:28 UTC, icewind1991 commented on apps/files_sharing/lib/SharedMount.php
> +			$shares = $shareManager->getSharesByPath($targetNode);
Why does `byPath` want a `Node` instead of a path :see_no_evil:

2017-01-12 09:34 UTC, rullzer commented on apps/files_sharing/lib/SharedMount.php
> +			$shares = $shareManager->getSharesByPath($targetNode);
We use nodes everywhere. Was just naming stuff to be somewhat siilar to the old one (you should have complained when the code was reviewed :wink: )

2017-01-12 09:35 UTC, rullzer commented
@icewind1991 well give me my closure table and I can optimize it properly....

2017-04-03 19:17 UTC, rullzer commented
@icewind1991 could you have a look at the failing tests so we can get this in? I know you have some objections but lets fix them separatly.

2017-05-01 16:10 UTC, LukasReschke commented
@icewind1991 🏓

2017-05-01 16:11 UTC, MorrisJobke commented
Let me rebase this and get #3944 into this.

2017-05-01 16:21 UTC, MorrisJobke commented on apps/files_sharing/lib/SharedMount.php
> +		if (empty($targetNodes)) {
The first unit test fails here.

```
1) OCA\Files_Sharing\Tests\UpdaterTest::testDeleteParentFolder
Failed asserting that true is false.
/drone/src/github.com/nextcloud/server/apps/files_sharing/tests/UpdaterTest.php:105
```

2017-05-01 16:25 UTC, MorrisJobke commented
@icewind1991 Please have a look at the failing tests. Would be nice to get this in and I don't properly understand this :/

2017-05-09 02:01 UTC, MorrisJobke commented
Nothing for 12 anymore

2017-08-09 12:03 UTC, closed without merging