fix the search popup for everyone
nextcloud/server pull request #28585
Opened 2021-08-24 13:55 UTC by szaimen

Fix #28584
Signed-off-by: szaimen <szaimen@e.mail.de>

2021-08-24 13:58 UTC, szaimen commented
/backport to stable22

2021-08-24 13:58 UTC, szaimen commented
/backport to stable21

2021-08-24 13:58 UTC, szaimen commented
/backport to stable20

2021-08-24 14:10 UTC, szaimen commented
/compile amend /

2021-08-25 00:55 UTC, Pytal approved these changes

2021-08-25 07:04 UTC, PVince81 approved these changes
:+1:

assuming you also retested on mobile to make sure the other fix you did for it still works

2021-08-25 07:15 UTC, szaimen commented
Yes, it was tested successrully on mobile, too. But after thinking about it a bit more does the carret need a bit more love...

2021-08-25 08:29 UTC, skjnldsv requested changes

2021-08-25 08:29 UTC, skjnldsv commented on core/src/components/HeaderMenu.vue
> +		right: 0px;
We use the same design for non-vue header menu, no? Can you double check those changes are also applied properly?
Iirc the main issue with a fixed position is that it will not be relative to the button as per the original design requirements.

The change applies on the mobile view:  https://github.com/nextcloud/server/blob/cfb94c746992293993ba4c877f10ec3075a63353/core/css/mobile.scss#L141-L148

2021-08-25 08:30 UTC, skjnldsv commented
> [szaimen](/szaimen) requested review from [nextcloud/server-frontend](/orgs/nextcloud/teams/server-frontend), [PVince81](/PVince81), [juliushaertl](/juliushaertl) and [artonge](/artonge) and removed request for [nextcloud/server-frontend](/orgs/nextcloud/teams/server-frontend) [il y a 19 heures](#event-5200813992)

Please also check the git blame/review suggestions, as the author of this file, I should have been requested for reviews to avoid regressions :wink: 
![image](https://user-images.githubusercontent.com/14975046/130756389-9d80e4c1-e6bd-4248-9bb1-edf561431f74.png)

2021-08-25 09:35 UTC, szaimen commented
> Please also check the git blame/review suggestions, as the author of this file, I should have been requested for reviews to avoid regressions 😉
> ![image](https://user-images.githubusercontent.com/14975046/130756389-9d80e4c1-e6bd-4248-9bb1-edf561431f74.png)

Will do that in the future. I think I didn't ping you in the other one because you seemed to be very busy...

2021-08-25 09:36 UTC, szaimen commented on core/src/components/HeaderMenu.vue
> +		right: 0px;
This css code is unfortunately not applied on this element...

2021-08-25 10:15 UTC, szaimen commented
@skjnldsv I currently see no way to fix this for everyone (for mobile and for people that disabled the notifications app). The best solution would be if the carrot wasn't part of the element but instead created by the element that triggers the popup so that the carrot can be positioned absolute to the trigger element and the popup can be positioned fixed on the site. But this is unfortunately a bit over my level of skill. Maybe @Pytal or @artonge can help me here?

2021-08-31 11:47 UTC, szaimen commented
Another attempt is in https://github.com/nextcloud/server/pull/28660

2021-08-31 13:48 UTC, 488849 commented
#27844

2021-08-31 13:49 UTC, 488849 commented
27844

2021-08-31 16:26 UTC, closed without merging