Add S3 SSE KMS key and bucket key encryption
nextcloud/server pull request #28601
Opened 2021-08-26 07:03 UTC by juliushaertl

Originally proposed by @tsdicloud this is the rebased version of https://github.com/nextcloud/server/pull/26899 with pulling the changes from https://github.com/nextmcloud/server/compare/master..s3fragment without the already merged parts from https://github.com/nextcloud/server/pull/27877

- [x] Add option to set a SSE KMS id and enable usage of bucket key encryption
- [x] Replace 'verify_bucket_exists' with 'autocreate' as documented in https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html#simple-storage-service-s3 which is also used in other object storage implementations as described in #26093
- [x] Double check with working patch
  - [x] https://github.com/nextmcloud/server/blob/47c00d0724ec118076ea6fcd102d62112a6a8744/lib/private/Files/ObjectStore/S3ConnectionTrait.php
  - [x] https://github.com/nextmcloud/server/blob/47c00d0724ec118076ea6fcd102d62112a6a8744/lib/private/Files/ObjectStore/S3ObjectTrait.php

2021-11-02 10:43 UTC, artonge requested changes

2021-11-02 10:43 UTC, artonge commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +			] + $this->getSseKmsGetParameters());
`SseKmsPutParameters` is placed under a `config` property, `SseKmsGetParameters` is not, is this right?

2021-11-02 10:43 UTC, artonge commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$logger = \OC::$server->get(LoggerInterface::class);
No DI possible? :(

2021-11-02 12:13 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ConnectionTrait.php
> +		$logger = \OC::$server->get(LoggerInterface::class);
No unfortunately through how the constructor is used to instantiate new instances of that class with the parameters https://github.com/nextcloud/server/blob/57db6892b74b2db1b8006257f830231deb55525b/lib/private/Files/ObjectStore/S3.php#L35

2023-02-21 20:23 UTC, juliushaertl commented
Closing this for now as there is no current demand. This can be picked up to finish anytime of course.

2023-02-21 20:23 UTC, closed without merging