Nmc 430 -harmonizing of sharing permissions step 1
nextcloud/server pull request #28635
Opened 2021-08-29 13:46 UTC by TSI-yogeshshejwadkar

Folders
Internal Share:
we removed the checkboxes "Allow editing", "Allow creating" and "Allow deleting"
we added a radio button group containing the options: "Read only" (Nur Lesen), "Allow upload and editing" (Hochladen & Bearbeiten)
External Share: no changes
Link Share: no changes

Files
Internal Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)
External Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)
Link Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)

2021-08-29 14:09 UTC, kesselb commented
Hey :wave: 

it looks like a mistake, to me, that changes related to S3 and encryption are part of this pull request.

2021-08-30 06:33 UTC, juliushaertl commented
In addition the commit is missing a `Signed-of-by` message as described in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

2021-08-30 06:41 UTC, Salvador1313 commented
Это вы в этом знатоки. Я пока только на уровне физических символов
программирование придумывать начал.  До компьютерного тока недавно
добрался.  Смотрите сами как лучше будет....

вс, 29 авг. 2021 г., 16:46 TSI-yogeshshejwadkar ***@***.***>:

> Folders
> Internal Share:
> we removed the checkboxes "Allow editing", "Allow creating" and "Allow
> deleting"
> we added a radio button group containing the options: "Read only" (Nur
> Lesen), "Allow upload and editing" (Hochladen & Bearbeiten)
> External Share: no changes
> Link Share: no changes
>
> Files
> Internal Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> External Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> Link Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/nextcloud/server/pull/28635
> Commit Summary
>
>    - Add S3 SSE KMS key and bucketked encryption
>    - Keep miemtype handling for writeObject
>    - Fix syntax problem
>    - Fix decision tree for sending KMS key ref
>    - Use correct class reference in config
>    - Fix small syntax problem
>    - Changes done for harmonizing of sharing process step 1
>
> File Changes
>
>    - *M* apps/files_sharing/src/components/SharingEntry.vue
>    <https://github.com/nextcloud/server/pull/28635/files#diff-a767a3e36d22b92db810b48aae05bc3cad43c31de6afb17e926ad1dee6f4da31>
>    (103)
>    - *M* apps/files_sharing/src/components/SharingEntryLink.vue
>    <https://github.com/nextcloud/server/pull/28635/files#diff-925efc388ad4cfd3cd63a65c9f7ad90678c5c3b03079876cc76680bfa0618ec2>
>    (24)
>    - *M* lib/private/Files/ObjectStore/S3ConnectionTrait.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-32333c316cf51e92bd3b53808f0fe1eca1635fb1f62daba1469ce6694959f97c>
>    (185)
>    - *M* lib/private/Files/ObjectStore/S3ObjectTrait.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-030e38a9e621019981acf91654c1d8d3a12ab3150dbd9fcc4c280479b8c853db>
>    (118)
>    - *M* tests/lib/Files/ObjectStore/S3Test.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-5a2d5f4251d71bb114d2ee3bccd33a7a3c87d8891efa5abc6bb610d35616a464>
>    (4)
>
> Patch Links:
>
>    - https://github.com/nextcloud/server/pull/28635.patch
>    - https://github.com/nextcloud/server/pull/28635.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/28635>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVLIXAA7HMCO3QNCBZRBFYTT7I24DANCNFSM5DAIJWEQ>
> .
>

2021-08-30 07:05 UTC, juliushaertl commented
@Salvador1313 Please stick to english for comments as we use that as language for communication on our github organization. :wink:

2021-08-30 07:10 UTC, Salvador1313 commented
Так?


вс, 29 авг. 2021 г., 16:46 TSI-yogeshshejwadkar ***@***.***>:

> Folders
> Internal Share:
> we removed the checkboxes "Allow editing", "Allow creating" and "Allow
> deleting"
> we added a radio button group containing the options: "Read only" (Nur
> Lesen), "Allow upload and editing" (Hochladen & Bearbeiten)
> External Share: no changes
> Link Share: no changes
>
> Files
> Internal Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> External Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> Link Share:
> we removed the checkbox "Allow editing"
> we added a radio button group containing the options: "Read only" (Nur
> lesen), "Editing" (Bearbeiten)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/nextcloud/server/pull/28635
> Commit Summary
>
>    - Add S3 SSE KMS key and bucketked encryption
>    - Keep miemtype handling for writeObject
>    - Fix syntax problem
>    - Fix decision tree for sending KMS key ref
>    - Use correct class reference in config
>    - Fix small syntax problem
>    - Changes done for harmonizing of sharing process step 1
>
> File Changes
>
>    - *M* apps/files_sharing/src/components/SharingEntry.vue
>    <https://github.com/nextcloud/server/pull/28635/files#diff-a767a3e36d22b92db810b48aae05bc3cad43c31de6afb17e926ad1dee6f4da31>
>    (103)
>    - *M* apps/files_sharing/src/components/SharingEntryLink.vue
>    <https://github.com/nextcloud/server/pull/28635/files#diff-925efc388ad4cfd3cd63a65c9f7ad90678c5c3b03079876cc76680bfa0618ec2>
>    (24)
>    - *M* lib/private/Files/ObjectStore/S3ConnectionTrait.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-32333c316cf51e92bd3b53808f0fe1eca1635fb1f62daba1469ce6694959f97c>
>    (185)
>    - *M* lib/private/Files/ObjectStore/S3ObjectTrait.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-030e38a9e621019981acf91654c1d8d3a12ab3150dbd9fcc4c280479b8c853db>
>    (118)
>    - *M* tests/lib/Files/ObjectStore/S3Test.php
>    <https://github.com/nextcloud/server/pull/28635/files#diff-5a2d5f4251d71bb114d2ee3bccd33a7a3c87d8891efa5abc6bb610d35616a464>
>    (4)
>
> Patch Links:
>
>    - https://github.com/nextcloud/server/pull/28635.patch
>    - https://github.com/nextcloud/server/pull/28635.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/28635>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVLIXAA7HMCO3QNCBZRBFYTT7I24DANCNFSM5DAIJWEQ>
> .
>

2021-08-30 12:22 UTC, TSI-yogeshshejwadkar commented
> Hey 
> 
> it looks like a mistake, to me, that changes related to S3 and encryption are part of this pull request.

Removed the extra commits

2021-08-30 12:23 UTC, TSI-yogeshshejwadkar commented
> In addition the commit is missing a `Signed-of-by` message as described in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

Added the message

2021-08-30 13:47 UTC, szaimen commented
/compile amend /

2021-08-30 20:26 UTC, kesselb commented
| Before | After |
| --- | --- |
| ![Screenshot from 2021-08-30 22-09-19](https://user-images.githubusercontent.com/3902676/131399314-941f6b05-68d4-4da5-a376-5b25bb6d450f.png) | ![Screenshot from 2021-08-30 22-07-54](https://user-images.githubusercontent.com/3902676/131399343-fbfa8afe-7876-4e35-864d-1e1bbf35870e.png) |
| ![Screenshot from 2021-08-30 22-17-42](https://user-images.githubusercontent.com/3902676/131400579-196bde17-9a7e-4966-9c9a-28fe1ebfb36e.png) | ![Screenshot from 2021-08-30 22-23-47](https://user-images.githubusercontent.com/3902676/131400660-55ddbc7f-e1cc-4397-8563-b2630bdf7f08.png) 
| ![Screenshot from 2021-08-30 22-17-56](https://user-images.githubusercontent.com/3902676/131400784-0a07021a-687b-4bc6-9270-b4f390ef5a7a.png) | ![Screenshot from 2021-08-30 22-24-03](https://user-images.githubusercontent.com/3902676/131400772-13292499-7c59-4a25-86bf-82c3660c04f4.png)

2021-08-30 20:32 UTC, kesselb commented
Well done :+1: 

![image](https://user-images.githubusercontent.com/3902676/131401249-9fb0d7b6-a97c-4a70-9bc0-7e96eddf41e6.png)

To fix the CI: Build the changes locally (make build-js-production) and commit the above files.

2021-08-31 15:11 UTC, AndyScherzinger commented
@juliushaertl @skjnldsv is this really v23 or does this need to be backported to v22, sames question for #28636 of course

2021-09-01 03:19 UTC, TSI-yogeshshejwadkar commented
> Well done 
> 
> ![image](https://user-images.githubusercontent.com/3902676/131401249-9fb0d7b6-a97c-4a70-9bc0-7e96eddf41e6.png)
> 
> To fix the CI: Build the changes locally (make build-js-production) and commit the above files.

added the requested file. Thanks :)

2021-09-04 03:22 UTC, TSI-yogeshshejwadkar commented
Updated conflict production build files

2021-09-30 10:37 UTC, artonge requested changes

2021-10-04 11:37 UTC, jancborchardt commented on apps/files_sharing/src/components/SharingEntry.vue
> +						{{ t('files_sharing', 'Editing') }}
"Read and write" is very technical. @TSI-yogeshshejwadkar could you change the labels to "View only" and "Edit"?

2022-08-20 17:37 UTC, Leptopoda commented
Just found this pr and want to add my opinion ;)
What happened to the upload only option?
Sometimes sharing a folder to a group and letting people just drop their stuff into it without fearing vandalism or accidental breakage.

nevertheless looks like a nice peace of ux improvement for many othervise confused users; so thanks!

2022-09-13 13:41 UTC, jancborchardt commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +							{{ t('files_sharing', 'Editing') }}
Wording-wise it should be "Edit" as per mockup: https://github.com/nextcloud/server/issues/26691
"Read and write" sounds way too technical.

2022-09-13 13:41 UTC, jancborchardt commented on apps/files_sharing/src/components/SharingEntry.vue
> +						{{ t('files_sharing', 'Allow upload and editing') }}
No, this is correct, the more human way to write it. "Read / write" is too technical.

2023-08-02 17:45 UTC, closed without merging