NMC-552
nextcloud/server pull request #28643
Opened 2021-08-30 05:17 UTC by TSI-sangramdesai

Guest view below changes done

1. For Video separated download button form file name and size
2. For Image separated download button form file name and size

2021-08-30 05:52 UTC, Salvador1313 reviewed
b20da982f51f9611c2e9288f8f46be9f392ec33d

2021-08-30 05:59 UTC, Salvador1313 approved these changes

2021-08-30 14:31 UTC, juliushaertl commented
Please do not include the change in the 3rdparty submodule in here.

In addition the commit is missing a Signed-of-by message as described in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

2021-08-31 10:14 UTC, artonge requested changes

2021-08-31 10:14 UTC, artonge commented on apps/files_sharing/templates/public.php
> +								<div class="video-file-details">
Is the `video-file-details` class useful?

2021-08-31 10:14 UTC, artonge commented on apps/files_sharing/templates/public.php
> +						 <?php	if (strpos($_['mimetype'], 'image') === 0) { ?>
We can merge those two conditions into one:

```js
isset($_['mimetype']) && strpos($_['mimetype'], 'image') === 0
```

2021-08-31 10:16 UTC, artonge commented
I would also add some space above the `downloadFile` element. Adding the following in `apps/files_sharing/css/public.scss` should be enough:

```css
.directDownload #downloadFile {
	...    
	margin-top: 16px;
}
```

2021-09-01 12:05 UTC, TSI-sangramdesai commented on apps/files_sharing/templates/public.php
> +								<div class="video-file-details">
Removed

2021-09-01 12:05 UTC, TSI-sangramdesai commented on apps/files_sharing/templates/public.php
> +						 <?php	if (strpos($_['mimetype'], 'image') === 0) { ?>
Merged

2021-09-01 14:04 UTC, artonge approved these changes
Need DCO, else looks good :)

```bash
git rebase HEAD~6 --signoff
git push --force-with-lease origin NMC-552
```

2021-09-01 16:17 UTC, skjnldsv approved these changes

2021-09-01 19:24 UTC, Pytal commented on apps/files_sharing/templates/public.php
> +							<div class="directDownload">
We should use kebab-case for class and id names :)

2021-09-02 05:55 UTC, TSI-sangramdesai commented on apps/files_sharing/templates/public.php
> +							<div class="directDownload">
directDownload is original class
https://github.com/nextcloud/server/blob/master/apps/files_sharing/templates/public.php

2021-09-02 06:15 UTC, merged

2021-09-02 06:20 UTC, skjnldsv commented
/backport to stable22

2021-09-02 06:42 UTC, skjnldsv commented
/backport to stable22

2021-09-02 06:59 UTC, skjnldsv commented
/backport to stable22

2021-09-02 21:38 UTC, Pytal commented
/backport to stable22