NMC-533
nextcloud/server pull request #28645
Opened 2021-08-30 07:30 UTC by TSI-kavitasonawane

**Add button folder creation changes:**
Removed the functionality to enter a name to an added folder
Changed the function to add a folder: the folder will be created called "New folder" or "Neuer Ordner" with an activated rename function
if a folder called "Neuer Ordner" or "New folder" already exists, the created folder will have a counter like "New folder (2)"

**Add button text document creation changes:**
Removed the functionality to enter a name to an added text document
The document will be created called "New text document" or "Neues Textdokument" with an activated rename function
If a text document is exisitng and already called "New text document" or "Neues Textdokument", the created document will have a counter like "New text document (2)"

2021-08-31 14:46 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +    /**
Please use tabs instead of spaces as per https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html

2021-08-31 14:49 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +                    let uniqueName = self.fileList.getUniqueName(name);
Should be `const` since it is not changed afterwards.

@skjnldsv Are we fine these days with using let/const inside of plain js files, since we dropped IE11?

2021-08-31 14:50 UTC, 488849 commented on apps/files/js/newfilemenu.js
> +    /**
👍

2021-08-31 15:46 UTC, 488849 approved these changes

2021-09-01 07:30 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
> +                    let uniqueName = self.fileList.getUniqueName(name);
Hum, good question. I think it should be fine yes :)

2021-09-01 16:28 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
> +    /**
@TSI-kavitasonawane

2021-09-02 06:22 UTC, skjnldsv commented
> **Add button text document creation changes:**
> 
> * Removed the functionality to enter a name to an added text document
> * The document will be created called "New text document" or "Neues Textdokument" with an activated rename function
> * If a text document is exisitng and already called "New text document" or "Neues Textdokument", the created document will have a counter like "New text document (2)"

The folder changes works great.
But the file one is more subtle.
We also have the template feature, which when it exists allow to create from templates. Since we cannot change the name before, if the file already exists, it fails to create.
![image](https://user-images.githubusercontent.com/14975046/131792690-5c099143-02ec-4f79-8d12-2485032b1bbc.png)
![image](https://user-images.githubusercontent.com/14975046/131792728-e13f7451-6469-43a2-b08f-7c72f6fdd923.png)

2021-09-02 06:28 UTC, skjnldsv requested changes
See comments

2021-09-02 06:28 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
> +			OC.hideMenus();
Tabs please! :)

2021-09-02 06:28 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
>  		        }];
Tabs :)

2021-09-02 06:28 UTC, skjnldsv commented on apps/files/src/views/TemplatePicker.vue
> +				fileList.rename(this.name);
```suggestion
				fileList.rename(this.name)
```

2021-09-02 06:28 UTC, skjnldsv commented on apps/files/js/newfilemenu.js
> -				return false;
Basically, this feature is missing for the template creation.
My suggestion would be to automatically increment as we do it in other places:
`New document.md`, `New document (1).md`, `New document (2).md`... etc
And then the user can rename inline :)

2021-09-02 06:39 UTC, skjnldsv commented
Also, JSUnit fails:
```js
TOTAL: 6 FAILED, 809 SUCCESS


1) sets default text in field
     OCA.Files.NewFileMenu New file/folder
     Expected 0 to equal 2.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:73:26)
     Expected undefined to equal 'New folder'.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:74:25)

2) prevents entering invalid file names
     OCA.Files.NewFileMenu New file/folder
     Expected false to equal true.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:81:42)

3) prevents entering file names that already exist
     OCA.Files.NewFileMenu New file/folder
     Expected false to equal true.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:89:42)

4) creates directory when clicking on create directory field
     OCA.Files.NewFileMenu New file/folder
     Expected 'New folder' to equal 'some folder'.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:99:51)

5) calls action handler when clicking on custom item
     OCA.Files.NewFileMenu custom entries
     Expected 'New text file.txt' to equal 'some name'.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:144:42)

6) switching fields removes the previous form
     OCA.Files.NewFileMenu custom entries
     Expected 0 to equal 1.
    at Object.<anonymous> (apps/files/tests/js/newfilemenuSpec.js:148:41)
```

2021-09-02 08:28 UTC, artonge requested changes

2021-09-02 08:28 UTC, artonge commented on apps/files/js/newfilemenu.js
> +                	});
```suggestion
					const uniqueName = self.fileList.getUniqueName(name);
					let tempPromise = self.fileList.createDirectory(uniqueName);
					Promise.all([tempPromise]).then(() => {
						self.fileList.rename(uniqueName);
					});
```

2021-09-03 10:10 UTC, skjnldsv commented
Jsunit needs to be adapted again and tabs indent is still not fixed :)
@TSI-kavitasonawane

2021-09-20 13:32 UTC, jancborchardt commented
> We also have the template feature, which when it exists allow to create from templates. Since we cannot change the name before, if the file already exists, it fails to create.

@skjnldsv @TSI-kavitasonawane can we have the file name input field on the top of this template selector, in the same modal? This was also initially floated when we worked on it, but we postponed it.

2021-09-22 08:43 UTC, TSI-kavitasonawane commented
> Jsunit needs to be adapted again and tabs indent is still not fixed :)
> @TSI-kavitasonawane

@skjnldsv  I have done the changes.

2022-02-28 12:21 UTC, CarlSchwan commented on apps/files/js/filelist.js
> ++					self.addAndFetchFileInfo(targetPath, '', options).then(function(status, data) {
```suggestion
					self.addAndFetchFileInfo(targetPath, '', options).then(function(status, data) {
```

2022-02-28 12:21 UTC, CarlSchwan commented on apps/files/js/filelist.js
> +			if (fileNamesOld!=-1) {
```suggestion
			var fileNamesOld = this.files.findIndex(function(el) {
				return el.name === name
			})
			if (fileNamesOld !== -1) {
```

2022-02-28 12:21 UTC, CarlSchwan commented on apps/files/js/newfilemenu.js
> +                	});
```suggestion
					const uniqueName = self.fileList.getUniqueName(name)
					let tempPromise = self.fileList.createDirectory(uniqueName, { showDetailsView: false })
					Promise.all([tempPromise]).then(() => {
						self.fileList.rename(uniqueName)
					})
```

2022-02-28 13:25 UTC, TSI-kavitasonawane commented on apps/files/js/filelist.js
> ++					self.addAndFetchFileInfo(targetPath, '', options).then(function(status, data) {
@CarlSchwan  Done the suggested changes

2022-02-28 13:25 UTC, TSI-kavitasonawane commented on apps/files/js/filelist.js
> +			if (fileNamesOld!=-1) {
@CarlSchwan  Done the suggested changes.

2022-02-28 13:27 UTC, TSI-kavitasonawane commented on apps/files/js/newfilemenu.js
> +                	});
@CarlSchwan Added suggested changes.

2022-03-02 08:11 UTC, skjnldsv commented
I rebased, squashed, tested and fixed some details about the template picker.
So far it seems to work fine from me. I couldn't push to this branch, so please have a look at https://github.com/nextcloud/server/pull/31396

One regression is setting up the template folder, before it was asking for the name (you could change the template folder name), now it automatically create it under the name "Templates".
Note that renaming the folder _afterwards_ will _not_ work as we do not watch for file renaming to update the user's `TemplateDirectory` config
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Files/Template/TemplateManager.php#L256-L262

2022-03-02 11:18 UTC, juliushaertl commented
> One regression is setting up the template folder, before it was asking for the name (you could change the template folder name), now it automatically create it under the name "Templates".
Note that renaming the folder afterwards will not work as we do not watch for file renaming to update the user's TemplateDirectory config

Might be something where we could actually improve the template folder handling by storing the file id of it instead of the path. Then it would also survive general renames, but fine for a follow-up I'd say, as renaming wasn't supported before anyways.

2022-03-02 20:56 UTC, juliushaertl commented
Filed an issue about it in https://github.com/nextcloud/server/issues/31414

2023-05-03 09:48 UTC, closed without merging