NMC-464
nextcloud/server pull request #28644
Opened 2021-08-30 06:05 UTC by TSI-kavitasonawane

NMC-464:  We applied a strong tag for user input on the "no results" screen within the search function.

2021-08-30 07:10 UTC, juliushaertl requested changes

2021-08-30 07:10 UTC, juliushaertl commented on core/src/views/UnifiedSearch.vue
> +				{{ t('core', 'No results for') }} <strong>{{ t('query', query) }}</strong>
This approach might not work with all languages. The query parameter should stay part of the translate `t()` function so it can be embedded into the translated sentence as needed in the target language. Also the content in your strong tag would always just print "query" instead of the actual search term.

In order to highlight something within a full text string, you can use the `Highlight` component from our shared components library. https://nextcloud-vue-components.netlify.app/#/Components/Highlight

2021-08-30 07:21 UTC, Salvador1313 commented
С телефона открывать не хочет. а на компе никак не найду его



пн, 30 авг. 2021 г., 10:10 Julius Härtl ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In core/src/views/UnifiedSearch.vue
> <https://github.com/nextcloud/server/pull/28644#discussion_r698245773>:
>
> > @@ -76,7 +76,7 @@
>  			<SearchResultPlaceholders v-if="isLoading" />
>
>  			<EmptyContent v-else-if="isValidQuery" icon="icon-search">
> -				{{ t('core', 'No results for {query}', {query}) }}
> +				{{ t('core', 'No results for') }} <strong>{{ t('query', query) }}</strong>
>
> This approach might not work with all languages. The query parameter
> should stay part of the translate t() function so it can be embedded into
> the translated sentence as needed in the target language. Also the content
> in your strong tag would always just print "query" instead of the actual
> search term.
>
> In order to highlight something within a full text string, you can use the
> Highlight component from our shared components library.
> https://nextcloud-vue-components.netlify.app/#/Components/Highlight
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/28644#pullrequestreview-741337534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVLIXAAOL6OKEM37PWS5ZWDT7MVGNANCNFSM5DBEXVIQ>
> .
>

2021-08-30 07:29 UTC, Salvador1313 commented
Запускать дальше?

пн, 30 авг. 2021 г., 10:21 Сальвадор В близи ***@***.***>:

> С телефона открывать не хочет. а на компе никак не найду его
>
>
>
> пн, 30 авг. 2021 г., 10:10 Julius Härtl ***@***.***>:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In core/src/views/UnifiedSearch.vue
>> <https://github.com/nextcloud/server/pull/28644#discussion_r698245773>:
>>
>> > @@ -76,7 +76,7 @@
>>  			<SearchResultPlaceholders v-if="isLoading" />
>>
>>  			<EmptyContent v-else-if="isValidQuery" icon="icon-search">
>> -				{{ t('core', 'No results for {query}', {query}) }}
>> +				{{ t('core', 'No results for') }} <strong>{{ t('query', query) }}</strong>
>>
>> This approach might not work with all languages. The query parameter
>> should stay part of the translate t() function so it can be embedded
>> into the translated sentence as needed in the target language. Also the
>> content in your strong tag would always just print "query" instead of the
>> actual search term.
>>
>> In order to highlight something within a full text string, you can use
>> the Highlight component from our shared components library.
>> https://nextcloud-vue-components.netlify.app/#/Components/Highlight
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/nextcloud/server/pull/28644#pullrequestreview-741337534>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVLIXAAOL6OKEM37PWS5ZWDT7MVGNANCNFSM5DBEXVIQ>
>> .
>>
>

2021-08-30 07:35 UTC, juliushaertl commented
@Salvador1313 Not sure what you are saying with your comments here and in the other prs, but please stick to English for discussion here and keep discussion and comments limited to the topic of the pull request.

2021-08-30 14:29 UTC, juliushaertl commented
Please also make sure here to only include the required commit in the branch without the unrelated s3 changes

2021-09-01 07:27 UTC, skjnldsv commented
I wanted to push a fix, but you disabled users from editing your pull request @TSI-kavitasonawane 
You will find the fix for this in this pull request: https://github.com/nextcloud/server/pull/28682

Feel free to close this one

2021-09-01 08:00 UTC, TSI-kavitasonawane commented on core/src/views/UnifiedSearch.vue
> +				{{ t('core', 'No results for') }} <strong>{{ t('query', query) }}</strong>
@juliushaertl  I have done the changes as you mentioned in the comment. Please check it.

2021-09-01 11:38 UTC, szaimen commented
Done in https://github.com/nextcloud/server/pull/28682

2021-09-01 11:38 UTC, closed without merging