Add database ratelimiting backend
nextcloud/server pull request #28728
Opened 2021-09-06 14:40 UTC by LukasReschke

In case no distributed memory cache is specified this adds a database backend for ratelimiting purposes. Previously the ratelimit just failed.

# Test plan

- Disable a memory cache in `config.php`
- Enable the "Q&A Testing App" in the app settings
- Go to `/index.php/apps/testing/userAndAnonProtected` and click a few times. Verify that the requests fails due to hitting the ratelimit.
- Verify that expired ratelimit entries are removed by the background job

# TODO

- [ ] Revert unnecessary composer changes
- [ ] Add background job for cleanup

2021-09-06 15:55 UTC, LukasReschke commented
@skjnldsv This needs quite a careful review as it is quite a big change to backport 🙈

2021-09-07 11:14 UTC, ChristophWurst approved these changes

2021-09-07 11:14 UTC, ChristophWurst commented on core/Migrations/Version23000Date20210906132259.php
> + * Auto-generated migration step: Please modify to your needs!
:fire:

2021-09-07 11:14 UTC, ChristophWurst commented on lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
> + * @package OC\Security\RateLimiting\Backend
:fire:

2021-09-07 11:14 UTC, ChristophWurst commented on lib/private/Security/RateLimiting/Backend/IBackend.php
> +	 * Gets the amount of attempts for the specified method
```suggestion
	 * Gets the number of attempts for the specified method
```

if we're making things more clear :)

2021-09-07 19:09 UTC, LukasReschke commented
/backport to stable22

2021-09-07 19:09 UTC, LukasReschke commented
/backport to stable21

2021-09-07 19:09 UTC, LukasReschke commented
/backport to stable20

2021-09-08 09:11 UTC, LukasReschke commented
/backport to stable19

2021-09-08 09:58 UTC, ChristophWurst approved these changes

2021-09-13 08:26 UTC, nickvergessen requested changes

2021-09-13 08:26 UTC, nickvergessen commented on lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
> +		$qb->selectAlias($qb->createFunction('COUNT(*)'), 'count')
```suggestion
		$qb->select($qb->func()->count())
```

2021-09-13 08:26 UTC, nickvergessen commented on lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
> +			->setParameter('currentTime', $currentTime, 'datetime');
```suggestion
			->andWhere(
				$qb->expr()->gte('delete_after', $qb->createNamedParameter($currentTime, IQueryBuilder::PARAM_DATE))
			);
```

2021-09-13 08:26 UTC, nickvergessen commented on lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
> +			->setParameter('currentTime', $currentTime, 'datetime')
```suggestion
			->where(
				$qb->expr()->lte('delete_after', $qb->createNamedParameter($currentTime, IQueryBuilder::PARAM_DATE))
			);
```

2021-09-13 08:26 UTC, nickvergessen commented on core/Migrations/Version23000Date20210906132259.php
> +			$table->addColumn('delete_after', 'datetime', [
```suggestion
			$table->addColumn('delete_after', Types::DATETIME, [
```

2021-09-13 08:26 UTC, nickvergessen commented on core/Migrations/Version23000Date20210906132259.php
> +		return $schema;
```suggestion
			return $schema;
		}

		return null;
```

2021-09-13 08:27 UTC, nickvergessen commented
Looks good in general, just some minor changes

2021-09-13 08:54 UTC, LukasReschke commented
Missed to set the remote. Retesting.

2021-09-13 08:55 UTC, nickvergessen commented on lib/private/Security/RateLimiting/Backend/DatabaseBackend.php
> +			);
```suggestion
			)
```

2021-09-13 11:07 UTC, AndyScherzinger approved these changes

2021-09-13 11:07 UTC, merged