Profile page
nextcloud/server pull request #28751
Opened 2021-09-07 14:11 UTC by Pytal

Workable Hack In Progress

2021-10-12 14:21 UTC, ChristophWurst requested changes
Early feedback on the public API, hope you don't mind.

Public API is always to be taken with extra care. Once we define it, it can only be changed in non-breaking ways for the next three years.

2021-10-14 20:01 UTC, PVince81 reviewed
Went through the whole codebase and only few minor things caught the eye, see comments.

Would be good to avoid reformatting whole files in the future as it only creates noise when revieweing in an already big PR.

2021-10-15 17:51 UTC, skjnldsv approved these changes

2021-10-18 20:58 UTC, ChristophWurst approved these changes
Reviewed public API part and give it a smoke test

:+1: :shipit:

2021-10-19 06:03 UTC, merged