Introduce option to display the full path of the node a share originated from to the recipient
nextcloud/server pull request #2895
Opened 2016-12-30 16:34 UTC by seaneble

The default is to use the original node name as the node name for a newly created share. In special cases, this can lead to frustration on the receiving side, because a number of nodes all appear with the exactly same name.

Think about the following structure:

    /Project A
        /Plans (-> shared with Group "Example")
        /…
    /Projekt B
        /Plans (-> shared with Group "Example")
        /…

The group members suddenly find two new folders in their view, both with the name "Plans". Confusing.

For a project we developed a small configuration option, which, when enabled, creates the name of the target nodes as

  * "Project A | Plans"
  * "Project B | Plans"

The option can be switched on and off by administrators. One could also imagine the option to be available on the sharing panel or elsewhere.
We'd be glad to find this feature included in the core. What do others think about it?

Beware: First-time contribution to nextcloud. Please point out flaws, we'll be glad to fix them.

2017-01-02 14:15 UTC, MorrisJobke commented
@schiessle What about including this into the logic that adds the `(2)`. For shares it maybe makes sense to list the original parent folder too. On the other side this maybe exposes information that should not be exposed.

2017-01-02 15:01 UTC, icewind1991 commented
> What about including this into the logic that adds the (2). For shares it maybe makes sense to list the original parent folder too. On the other side this maybe exposes information that should not be exposed.

That also has the problem (compared to this PR) that it only applies the naming for the 2nd share

2017-01-02 15:03 UTC, icewind1991 requested changes

2017-01-02 15:03 UTC, icewind1991 commented on lib/private/Share20/Manager.php
> +			$current_node = $share->getNode();
Could be simplified to

```php
$userFolder = $this->rootFolder->getUserFolder($share->getShareOwner());
$path = $userFolder->getRelativePath($share->getNode()->getPath());
$label = str_replace('/', ' | ', $path);
```

Also it would be nice to have this path covered by tests

2017-01-02 15:43 UTC, rullzer commented
I'm not a fan of adding yet another switch to core. With paths we need to test and all that.

Solution that comes to mind is:

* Fire of a decent beforeShareEvent (passing the not yet shared share object).
* Let an app modify the target
* If the target is a duplicate it our (2) logic will add the next number etc anyways.

2017-01-11 10:20 UTC, schiessle commented
Thanks for your pull request @seaneble. I see why it could be a good idea to create unique names with something more meaningful like `(N)`. While in your example it make a lot of sense to use the parent directory as differentiator, I have some doubts that this is a useful pattern in general. Additionally people could consider this a privacy issue.

Like said by @rullzer I would like to avoid to have yet another sharing option. Instead I would like to explore possible solutions together with you how we can make this the default behavior, in a way that it makes sense for many use cases and without any privacy issues.

One idea I have in mind is to create a folder name like `Plans (from user1)`, `Plans (from user2)`,... Of course this wouldn't solve the problem if all the project plans are shared by the same user but it would create some additional and general useful information in case of a name collision. What do you think about it?

Also keep in mind that the recipients can rename and move shared files/folders around as they wish. If people work on different projects I consider it quite likely that they also have local folders for those projects. If someone shares with them files which belong to a specific project they don't have to keep it in their root folder but can move it to their local project folder and organize the files the way it fits best for them.

2017-01-11 11:23 UTC, seaneble commented
@schiessle I totally agree with all of your remarks. The Nextcloud team is obviously very thoughful about the future path for the software, which is something not all open source projects do. I also appreciate you taking the time to discuss this in depth.

If I'd have had both the time and the necessary knowledge, this is how I would have set up the feature:

![share-name](https://cloud.githubusercontent.com/assets/1255670/21846528/db0f923e-d7f7-11e6-882a-80cbf9f8a6f6.png)

This would make it possible to
  * keep the name of the node
  * overwrite it with an indication of hierarchy or context
  * overwrite it with an indication of ownership
  * enter any name one can think of

I think this would be a benefit for all kind of user personas.

All other solutions (mine, or your idea of adding "shared by users X") have limitations. On the other hand I think of the current behaviour as less then optimal. I think there are common enough use cases where a user might end up having more than one folder shared by one or a number of persons which all carry the same name and bear no other distinguishing marks. Difficult to keep them apart from the start without getting back to at least one of the sharing users. After renaming them, the problem goes away, but we could evade it in the first place.

2017-01-11 11:26 UTC, seaneble commented
I think I should add that there is a current project attached to this and also that there is a small amount of time available which we could use to contribute in the direction of this feature. As I am by no way a Nextcloud expert, some guidance etc. would be required.

2017-01-13 10:40 UTC, schiessle commented
@jancborchardt any thought about it? On one hand I think it could be nice to have a option to define a random name for a share (But maybe not with a large input field but with a small pen-icon next to it which expends to a input field if needed. On the other hand, as recipients can re-name shares as they whish, such a option could indicate a wrong sense of control to the owner.

For your project, @seaneble I would suggest to go the way with a event in the server sharing code and a small app on your side which just listen to it, manipulate the name the way you need it and return it. Does this work for you? I can take care of the the server-side event so that you can concentrate on the app.

2017-01-13 11:04 UTC, schiessle commented
@seaneble the hooks is already there, I just had to add one parameter. See my proposal here: https://github.com/nextcloud/server/pull/3061

2017-01-14 17:27 UTC, jancborchardt commented
> One idea I have in mind is to create a folder name like Plans (from user1), Plans (from user2),

@schiessle keep in mind that the Files app already shows the original sharer in the same line, next to the share icon, for that purpose. It would be duplicate information.

The only problem here seems to be that this is not propagated to the clients and mobile apps and displayed there. Is there a way we can do this @rullzer @nextcloud/android @nextcloud/ios? Something as simple as an avatar circle overlaid on the folder/file icon would be good.

If we do that, enumeration like `Plans` and `Plans (2)` would be enough, especially as then the recipient can rename as they want.

> On one hand I think it could be nice to have a option to define a random name for a share (But maybe not with a large input field but with a small pen-icon next to it which expends to a input field if needed. On the other hand, as recipients can re-name shares as they wish, such a option could indicate a wrong sense of control to the owner.

I don’t quite understand this. »Random name«?

2017-01-14 19:27 UTC, strugee commented
@jancborchardt I think by "random name" @schiessle meant that the user could choose arbitrary names, not something randomly-generated or whatever. The problem used there is that the sharer's notion of a useful filename will often not match that of the recipient, so the naming will be pointless a lot of the time.

2017-01-16 07:07 UTC, tobiasKaminsky commented
@janczorchardt
> The only problem here seems to be that this is not propagated to the clients and mobile apps and displayed there. Is there a way we can do this @rullzer @nextcloud/android @nextcloud/ios? Something as simple as an avatar circle overlaid on the folder/file icon would be good.

If this is information is accessible we can do this. But if we plan this, it should be consistent on all platforms (and then open/discuss the implementation in nextcloud/android).

2017-01-26 05:16 UTC, MorrisJobke commented
@jancborchardt ping

2017-02-07 18:46 UTC, eppfel commented
Yeah, this is a important decision. Neither 💧 📦 , nor G 🚗  got this right. 
I feel the "full-path" solution is not what users need, but rather a work around for lazy admins ^^So if communicate as @jancborchardt suggested, it might work.

Does this make sense? I think I'm to tired 😪 

🎉 🇪🇺

2017-02-20 12:03 UTC, seaneble commented
The customer in question cancelled the project and moved on to another solution.

2017-02-20 12:03 UTC, closed without merging