Improve log and allow duplicate notifications section
nextcloud/server pull request #29019
Opened 2021-10-01 14:11 UTC by nickvergessen

* Notifications is receiving a settings section and it's confusing for users if we add 2 different tabs for notifications and activity: https://github.com/nextcloud/notifications/pull/1074
So we want to have notifications section from both apps
* There is a log with an empty message

2021-10-04 09:56 UTC, artonge requested changes

2021-10-04 09:56 UTC, artonge commented on lib/private/Settings/Manager.php
>  				$this->log->info('', ['exception' => new \InvalidArgumentException('Section with the same ID already registered: ' . $sectionID . ', class: ' . $class)]);
This log also has an empty message, should it be fixed too?

2021-10-04 10:52 UTC, nickvergessen commented on lib/private/Settings/Manager.php
>  				$this->log->info('', ['exception' => new \InvalidArgumentException('Section with the same ID already registered: ' . $sectionID . ', class: ' . $class)]);
fixed

2021-10-04 11:03 UTC, artonge approved these changes
Front CI is somehow unhappy. Weird

2021-10-04 15:46 UTC, vitormattos commented on lib/private/Settings/Manager.php
> +			if ($sectionID !== 'connected-accounts' && $sectionID !== 'notifications' && isset($this->sections[$type][$sectionID])) {
I believe will make more readable the code if put the two first conditions on a method to  check for all sessionId names

2021-10-04 17:03 UTC, nickvergessen commented on lib/private/Settings/Manager.php
> +			if ($sectionID !== 'connected-accounts' && $sectionID !== 'notifications' && isset($this->sections[$type][$sectionID])) {
DOne

2021-10-05 10:28 UTC, vitormattos approved these changes

2021-10-05 13:09 UTC, merged