adding action.filename to FileActions
nextcloud/server pull request #29101
Opened 2021-10-06 21:24 UTC by ArtificialOwl

Simple solution to allow the configuration of a FileAction based on the name of a file

2021-10-07 09:04 UTC, artonge requested changes

2021-10-08 09:28 UTC, ArtificialOwl commented
renaming some params, squashed & rebased

2021-10-08 13:15 UTC, ArtificialOwl commented
Generally, if you want to add an action to the FileAction based on its name.

Personally, if you upload a Backup, you have stored somewhere (webdav/sftp/...), on your Nextcloud, you can right click on the file that containts metadata about the restoring point and 'Scan' it, so it will be available in your list of valid restoring point.

_Yay! screenshot!_
![Selection_059](https://user-images.githubusercontent.com/1038617/136563668-668dc565-61cf-43b6-a0cb-a11c94352d2f.png)

2021-10-12 09:59 UTC, artonge approved these changes

2021-10-12 21:58 UTC, Pytal approved these changes

2021-10-12 21:58 UTC, merged