Use flexbox for header and rearrange some elements
nextcloud/server pull request #2924
Opened 2017-01-03 16:28 UTC by ChristophWurst

this is just a little cleanup for https://github.com/nextcloud/server/issues/207

2017-01-03 16:30 UTC, ChristophWurst commented on core/css/styles.css
> -	max-width: 50%;
@skjnldsv if this line is active, the input is narrower on the right, which means some space between the input and the settings menu shows ups. Any idea what might cause that? I've tried different fixes but none solved it so far. The max-width is needed for narrow window sizes like on mobile to prevent the input take up too much space.

2017-01-03 19:50 UTC, skjnldsv commented on core/css/styles.css
> -	max-width: 50%;
Will look into it asap

2017-01-05 13:01 UTC, skjnldsv commented on core/css/styles.css
> -	max-width: 50%;
Almost have it. Will push it tonight!

2017-01-05 13:45 UTC, ChristophWurst commented
> Did you try if this breaks the notification UI?

Not yet, thanks for the hint

2017-01-05 17:58 UTC, skjnldsv commented
Pushed what I got so far.
You can now tweak the input width to fit. The issue is coming from it.

2017-01-09 13:05 UTC, ChristophWurst commented
Awesome, thank you @skjnldsv!

I added another small fix. Now it seems to work nicely, except for extremely narrow window sizes. There, the fixed search input width is too big.

2017-01-09 13:18 UTC, ChristophWurst commented
@nickvergessen apparently works with notifications too:
![bildschirmfoto von 2017-01-09 14-18-14](https://cloud.githubusercontent.com/assets/1374172/21767831/89045592-d676-11e6-8e2a-947cc19fa99e.png)

2017-01-09 13:23 UTC, ChristophWurst commented
> I added another small fix. Now it seems to work nicely, except for extremely narrow window sizes. There, the fixed search input width is too big.

@eppfel @jancborchardt @juliushaertl @skjnldsv not sure how much of an issue that is, but would be great if we can fix this too. Suggestions are very welcome :-)

2017-01-09 13:29 UTC, nickvergessen commented
Previously the notification icon was right of the search, but I guess it's okay

2017-01-09 13:43 UTC, ChristophWurst commented
> Previously the notification icon was right of the search, but I guess it's okay

We can change that of course. https://github.com/nextcloud/notifications/blob/643b3d8e26a821a2b5257064f9b9d8804e8e044d/js/app.js#L93-L94 modifies the relevant elements.

2017-01-14 16:14 UTC, jancborchardt submitted a review, later dismissed

2017-01-14 16:14 UTC, jancborchardt commented on core/templates/layout.user.php
> +			<div class="header-left">
You use an ID for header-right, but a class here. Better would be an ID here too. :)

2017-01-14 16:14 UTC, jancborchardt commented on core/css/header.scss
> +	#header-left #header-right {
Comma and line break missing I guess? Because header-right is a sibling of header-left, and not a child.

2017-01-14 16:14 UTC, jancborchardt commented on core/css/header.scss
> +	div.header-left {
As with the comment below, use an ID. Then also remove the `div` part because an ID (or class) is enough to identify. :)

2017-01-14 16:15 UTC, jancborchardt commented
@ChristophWurst @skjnldsv see my detail comments. Except if this is intentional of course, but it doesn’t look like it :)

2017-01-16 14:16 UTC, ChristophWurst commented
@jancborchardt @skjnldsv @nextcloud/designers please review. This little cleanup PR kinda blocks my work on https://github.com/nextcloud/server/issues/207 😉

2017-01-16 18:00 UTC, MorrisJobke requested changes
In Firefox the app name is in the middle of the header for public shares:

<img width="1370" alt="bildschirmfoto 2017-01-16 um 11 58 44" src="https://cloud.githubusercontent.com/assets/245432/21993994/28328280-dbe3-11e6-99fe-afbe834ded94.png">

In Chrome and Safari it is below the "Download" button on the very right:

![bildschirmfoto 2017-01-16 um 11 59 50](https://cloud.githubusercontent.com/assets/245432/21994018/489a7244-dbe3-11e6-97e0-1d78a7c38fd2.png)

2017-01-16 18:29 UTC, ChristophWurst commented
> In Firefox the app name is in the middle of the header for public shares:

Oh man, we kinda duplicate that HTML across the code base. I've found at least four php templates that have a familiar, but still different structure. Pure awesomeness. Let's see if I can fix this somehow. Gallery is also effected btw 🙌

2017-01-17 07:34 UTC, skjnldsv requested changes
The search icon is a little too low.

2017-01-17 07:34 UTC, skjnldsv commented on core/css/styles.scss
>  	margin-top: 9px;
Search box is too low. :)

2017-01-17 08:10 UTC, ChristophWurst commented on core/css/styles.scss
>  	margin-top: 9px;
fixed

2017-01-17 08:43 UTC, skjnldsv approved these changes

2017-01-17 08:43 UTC, skjnldsv commented
Very nice work!
Glad to see we're improving the css a lot! ;)

2017-01-17 08:58 UTC, ChristophWurst commented
I will take care of fixing Gallery in case this breaks something there too

2017-01-17 15:18 UTC, jancborchardt commented
> Gallery is also effected btw :raised_hands:

Video calls shared by link will be affected too ;) And maybe Collabora Office uses a separate template for the header too?

2017-01-17 19:50 UTC, ChristophWurst commented
> Video calls shared by link will be affected too ;) And maybe Collabora Office uses a separate template for the header too?

then someone will fix it ;-)

2017-01-19 05:32 UTC, MorrisJobke approved these changes
I rebased this, resolved the conflicts, tested it and it works like a charm 👍 

@ChristophWurst Could you please check that the rebase went fine (otherwise db5f164 is the old sha sum ;))

2017-01-19 05:37 UTC, skjnldsv commented
@MorrisJobke 😍

2017-01-19 09:37 UTC, ChristophWurst commented
> I rebased this, resolved the conflicts, tested it and it works like a charm 👍

❤️ 😗 thanks :-)

Will check it ASAP

2017-01-23 08:12 UTC, ChristophWurst commented
rebased again because it was conflicting with the changes from https://github.com/nextcloud/server/pull/3187/

New issues:
- [ ] search input lost its border
- [ ] public page broke completely

2017-01-23 18:15 UTC, MorrisJobke approved these changes
I tested this again and it looks fine 👍

2017-01-23 18:16 UTC, MorrisJobke commented
It will only need a little adjustment of the notification icon in the notifications app. I will do that.

2017-01-23 18:16 UTC, merged

2017-01-23 18:18 UTC, MorrisJobke commented
> It will only need a little adjustment of the notification icon in the notifications app. I will do that.

https://github.com/nextcloud/notifications/pull/58