Add option to restore automatic status
nextcloud/server pull request #29430
Opened 2021-10-25 12:45 UTC by CarlSchwan

Fix #29339

![image](https://user-images.githubusercontent.com/23653902/140367328-388fbb69-91c3-4f03-9cca-46c505947f10.png)

2021-11-04 15:41 UTC, CarlSchwan commented
/compile amend /

2021-11-04 15:59 UTC, nickvergessen commented on apps/user_status/src/store/backupUserStatus.js
> + * @copyright Copyright (c) 2020 Georg Ehrke
🙈

2021-11-04 15:59 UTC, nickvergessen commented on apps/user_status/src/store/userStatus.js
> +		commit('loadStatusFromServer', backupStatus)
Can't we return the new status on the revert API request? so we save a request and the round trip time?

2021-11-04 15:59 UTC, nickvergessen commented on apps/user_status/src/components/ResetStatus.vue
> +		</a>
As per https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#improving-your-translations please make the message a parameter in the translation, or use another line break and make the translated string "complete" e.g. `Reset status:` and use a real button?

2021-11-04 15:59 UTC, nickvergessen commented on apps/user_status/appinfo/routes.php
> +		['name' => 'UserStatus#getBackupStatus', 'url' => '/api/v1/user_status_backup', 'verb' => 'GET'],
```suggestion
		['name' => 'UserStatus#getBackupStatus', 'url' => '/api/v1/user_status/backup', 'verb' => 'GET'],
```

To align with other endpoints?

2021-11-04 16:02 UTC, nickvergessen commented
> Internal Server Error\nArgument 1 passed to OCA\\UserStatus\\Controller\\UserStatusController::setPredefinedMessage() must be of the type string, null given, called in server/lib/private/AppFramework/Http/Dispatcher.php on line 217 in file 'server/apps/user_status/lib/Controller/UserStatusController.php' line 133

2021-11-04 16:14 UTC, jancborchardt commented
This note should show below the input field for the status message though, as it's related to the message. Right?

2021-11-04 18:16 UTC, CarlSchwan commented on apps/user_status/src/store/backupUserStatus.js
> + * @copyright Copyright (c) 2020 Georg Ehrke
Some part of this files are adapted from apps/user_status/src/store/userStatus.js

2021-11-29 13:08 UTC, jancborchardt commented
> This note should show below the input field for the status message though, as it's related to the message. Right?

@CarlSchwan was that fixed? Also it seems this needs rebasing, mind updating the screenshot afterwards? :)

2022-06-10 15:22 UTC, PVince81 commented
did we not fix this differently ? or have plans for it in a different context ? @CarlSchwan @nickvergessen

2022-06-10 15:58 UTC, nickvergessen commented
This would still be highly appiciated

2022-06-16 14:57 UTC, jancborchardt requested changes
This note should show below the input field for the status message though, as it's related to the message.

2024-02-24 11:44 UTC, skjnldsv commented
cc @nickvergessen do we still need this?
also cc @ChristophWurst as it seems groupware also have meeting automated statuses

2024-02-24 12:51 UTC, closed without merging