Add an OCP for trusted domain helper
nextcloud/server pull request #29444
Opened 2021-10-26 11:29 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2021-10-26 12:03 UTC, LukasReschke approved these changes

2021-10-26 13:59 UTC, juliusknorr approved these changes

2021-10-26 14:56 UTC, ChristophWurst requested changes

2021-10-27 12:38 UTC, ChristophWurst approved these changes
Nitpicks, fine otherwise :)

2021-10-27 13:05 UTC, ChristophWurst approved these changes

2021-10-28 09:45 UTC, merged