Revamp profile visibility section
nextcloud/server pull request #29482
Opened 2021-10-29 02:43 UTC by Pytal

Revamp profile visibility settings by grouping dropdowns together into one section instead of one dropdown under every input field and make necessary improvements to the backend i.e. provide `appId` for sorting and dynamic `displayId`.

![image](https://user-images.githubusercontent.com/24800714/139773021-8fb44ee1-c5b7-440b-b196-258015d81aee.png)
![image](https://user-images.githubusercontent.com/24800714/139773024-f18c28e5-bdef-466a-bd5b-53e2c6e6bee0.png)

> The design of the entire settings page is not final and this new section was placed in a separate block pending an overhaul of the layout @nextcloud/designers 

Contributes to https://github.com/nextcloud/server/issues/28139

2021-11-02 01:40 UTC, Pytal commented
/compile amend /

2021-11-02 02:07 UTC, Pytal commented
Psalm errors seem unrelated 🤔

2021-11-02 12:41 UTC, artonge requested changes

2021-11-02 12:41 UTC, artonge commented on lib/private/Profile/ProfileManager.php
> +	public function getProfileConfig(IUser $targetUser, ?IUser $visitingUser, bool $includeMetadata = false): array {
Couldn't we remove the parameter and return the metadata by default?

2021-11-02 12:41 UTC, artonge commented on lib/private/Profile/ProfileManager.php
> +	private function filterProfileConfig(array $profileConfig): array {
Better naming? Something like that or better:

```suggestion
	private function filterNotStoredProfileConfig(array $profileConfig): array {
```

2021-11-02 12:48 UTC, CarlSchwan commented
> Psalm errors seem unrelated thinking

If you can reproduce this error locally, could you update the psalm baseline?

2021-11-02 12:48 UTC, CarlSchwan approved these changes
This looks so much better. Great work!

2021-11-02 16:52 UTC, skjnldsv commented
> If you can reproduce this error locally, could you update the psalm baseline?

Let's do that in another PR

2021-11-02 16:53 UTC, skjnldsv commented on apps/settings/css/settings.scss
> +}
Seems super specific and new, but not related to this PR :thinking:

2021-11-02 16:54 UTC, skjnldsv approved these changes
Some comments, otherwise good! :rocket:

2021-11-03 03:08 UTC, Pytal commented on lib/private/Profile/ProfileManager.php
> +	public function getProfileConfig(IUser $targetUser, ?IUser $visitingUser, bool $includeMetadata = false): array {
The thinking is that `getProfileConfig` should just be a minimal abstraction that returns the profile config from the database which just contains `visibility`, while `appId` and `displayId` is metadata for the frontend :)

2021-11-03 03:19 UTC, Pytal commented on lib/private/Profile/ProfileManager.php
> +	private function filterProfileConfig(array $profileConfig): array {
Did just that!

2021-11-03 03:21 UTC, Pytal commented on apps/settings/css/settings.scss
> +}
This is to make it so that clicking the "Edit your Profile visibility" anchor link scrolls smoothly to the new section instead of jumping instantly :)

2021-11-03 03:28 UTC, Pytal commented
> > If you can reproduce this error locally, could you update the psalm baseline?
> 
> Let's do that in another PR

Pinging @https://github.com/nextcloud/server/blob/master/.github/workflows/update-psalm-baseline.yml :)

2021-11-03 09:16 UTC, skjnldsv commented on apps/settings/css/settings.scss
> +}
I think that will impact everything else too then? Maybe just scope that to the visibility styling?

2021-11-03 09:33 UTC, artonge commented on lib/private/Profile/ProfileManager.php
> +	public function getProfileConfig(IUser $targetUser, ?IUser $visitingUser, bool $includeMetadata = false): array {
Is it ever used without asking for metadata?

I agree that this is a nitpick, but I dislike the use and accumulation of optional arguments. Maybe creating another method would be better.

2021-11-04 00:23 UTC, Pytal commented on lib/private/Profile/ProfileManager.php
> +	public function getProfileConfig(IUser $targetUser, ?IUser $visitingUser, bool $includeMetadata = false): array {
It is used without metadata most of the time and since the keys don't conflict functionality would not break, but for developer experience purposes I want to preserve the conceptual separation between the profile config on the database from the profile config with metadata so I opted to make a new `getProfileConfigWithMetadata` function :)

2021-11-04 00:24 UTC, Pytal commented
/compile amend /

2021-11-04 00:52 UTC, Pytal commented on apps/settings/css/settings.scss
> +}
It was already attempted to set this property on the scoped container which contains the elements, but in testing it seemed that setting on `html` was the only way it would work. As a js solution would be suboptimal I opted to place this in the styles of the component instead so that it would ony apply on the settings page with the component https://github.com/nextcloud/server/blob/19c62d051f8f007212a3846e8db20f41683d3c7c/apps/settings/src/components/PersonalInfo/ProfileSection/EditProfileAnchorLink.vue#L62-L70

2021-11-04 00:55 UTC, Pytal commented on lib/private/Profile/ProfileManager.php
> +	public function getProfileConfig(IUser $targetUser, ?IUser $visitingUser, bool $includeMetadata = false): array {
It is used without metadata most of the time and since the keys don't conflict functionality would not break, but for developer experience purposes I want to preserve the conceptual separation between the profile config on the database from the profile config with metadata so I opted to make a new `getProfileConfigWithMetadata` function :)

2021-11-04 07:32 UTC, merged

2021-11-04 10:05 UTC, artonge commented on apps/settings/css/settings.scss
> +}
Indeed tricky as the `scroll-behaviour` has to be set on the scrolling element, and in this case, it is `html`.
You can wrap the personal settings into a `<div>`, limit its height to `100vh -  $hearder-height` and set the `scroll-behaviour` on it. But I didn't find how to include the development notice at the bottom.

In any case, setting `scroll-behaviour` globally could be a good change. But might need some discussion...

2021-11-04 10:06 UTC, artonge commented on apps/settings/css/settings.scss
> +}
Oh, its merged already :sweat_smile:

2021-11-04 22:46 UTC, Pytal commented on apps/settings/css/settings.scss
> +}
> In any case, setting `scroll-behaviour` globally could be a good change. But might need some discussion...

Yes, would have to see if any current functionality depends on non-smooth `scroll-behavior`, though it'd most likely be purely cosmetic 🤔