Use unique combination of hostname/bucket/key for external storages
nextcloud/server pull request #29484
Opened 2021-10-29 11:28 UTC by juliushaertl

Avoid conflicts with the storage id of external s3 storages when the bucket name is the same for different mountpoints.

2021-10-29 11:33 UTC, CarlSchwan approved these changes

2021-10-29 11:34 UTC, nickvergessen approved these changes

2021-10-29 13:04 UTC, icewind1991 requested changes
Unfortunately this will need some kind of migration script.

Changing the storage id of an existing external storage will cause all fileids for the storage to change with all the effects that has

2021-11-04 12:11 UTC, juliushaertl commented
Added a migration step to rename the storage ids for all external storages using the "amazons3" backend, please have another look

2021-11-04 16:29 UTC, AndyScherzinger commented
@icewind1991 can you re-review with latest changes from @juliushaertl so we can provide it to the customer :) Thanks ❤️

2021-11-04 19:46 UTC, CarlSchwan requested changes
After enabling the app and applying this patch I get

```
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_external_mounts' doesn't exist
```

2021-11-04 19:46 UTC, CarlSchwan commented on apps/files_external/lib/Migration/Version1015Date20211104103506.php
> +	 * @throws Exception
```suggestion
	 * @throws Exception
	 * @return \OCP\DB\IResult|int 
```

2021-11-04 19:46 UTC, CarlSchwan commented on apps/files_external/lib/Migration/Version1015Date20211104103506.php
> +				$qb->executeStatement();
If you want to backport this, you probably should use this instead:

```suggestion
				$qb->execute();
```

2021-11-04 20:11 UTC, CarlSchwan commented
> After enabling the app and applying this patch I get
> 
> ```
> An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_external_mounts' doesn't exist
> ```

Found a fix, if apps/files_external/lib/Migration/Version1011Date20200630192246.php::changeSchema return null. The schema will be written immediately to the database, if it returns $schema, it will only write it in the next MigrationStep that returns null (or the last one).

2021-11-08 21:14 UTC, CarlSchwan approved these changes
Tested under this two scenarios and the migration worked now:

1. Setup Nextcloud with master branch =>  setup external storage with s3 => switch to this branch => migrations work
2. Setup Nextcloud with this branch, activating the files_external app works now and I can add an external storage

2021-11-09 10:43 UTC, CarlSchwan commented on apps/files_external/lib/Migration/Version1015Date20211104103506.php
> +
Copyright missing

2021-11-09 15:39 UTC, PVince81 approved these changes
:+1: please see comment about some thing to test

2021-11-09 15:39 UTC, PVince81 commented on apps/files_external/lib/Migration/Version1015Date20211104103506.php
> +			$oldId = Storage::adjustStorageId('amazon::' . $bucket);
please also test with a bucket name that has 60+ characters to force the DB storage id to be a md5, just in case

2021-11-09 17:16 UTC, juliushaertl commented
Also gave that another test run 👍 

Thanks for helping out here @CarlSchwan

2021-11-10 13:18 UTC, icewind1991 approved these changes
Did some basic testing for the migration

2021-11-10 14:56 UTC, merged

2021-11-10 14:56 UTC, CarlSchwan commented
/backport to stable22

2021-11-10 14:56 UTC, CarlSchwan commented
/backport to stable21

2021-11-10 14:56 UTC, CarlSchwan commented
/backport to stable20