Support LDAP dns longer than 255 characters
nextcloud/server pull request #29523
Opened 2021-11-02 15:25 UTC by come-nc

Adds an `ldap_full_dn` column to store the dn, and only store a sha256 hash in the `ldap_dn` which is shorter and can be indexed without trouble.
Migration still needs to be implemented.

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2021-11-02 15:35 UTC, nickvergessen requested changes

2021-11-02 15:35 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
> +			$table->addColumn('ldap_full_dn', Types::STRING, [
Can not modify existing migrations. You need a new one

2021-11-02 15:40 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
> +			$table->addColumn('ldap_full_dn', Types::STRING, [
Ok, I will move this to a new file

2021-11-02 16:19 UTC, come-nc commented
Note to self: we should look into which kind of hash fits the best what we need here. There are uuid v5, and other hash algorithm, unicity and performance should be compared to select the best fit.

2021-11-02 16:20 UTC, come-nc commented
Related bug ticket: https://github.com/nextcloud/server/issues/2213

2021-11-02 20:57 UTC, blizzz commented on apps/user_ldap/lib/Migration/Version1010Date20200630192842.php
> +			$table->addColumn('ldap_full_dn', Types::STRING, [
`occ migrations:generate` is your friend

2021-11-16 21:34 UTC, blizzz commented
/rebase

2021-11-16 22:00 UTC, blizzz requested changes
In the first Migration class, the final state of the table should be reflected for new installations. Not necessary to run the while migration history on a new install. So you can add the columns and alter the index in Version1010Date20200630192842.

The new Version1130Date20211102154716 is of course required and looks good as is, with the one remark I left there.

2021-11-16 22:01 UTC, blizzz commented
@nickvergessen what do you think about its backportability?

2021-11-16 22:03 UTC, blizzz commented
…while at changing DB it might be worth to add a simple index on directory_uuid, too, since this also may be used as sole WHERE column in queries.

2021-11-18 08:36 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey() || ($table->getPrimaryKeyColumns() !== ['owncloud_name'])) {
https://3v4l.org/D9LNm
It seems to work just fine.
And if the function does not return an array it will just evaluate to FALSE.

Not sure where this warning comes from.

2021-11-18 08:46 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +		$u = $this->getUpdateQuery($table);
You don't have to pay per character so for the future value readability over shortening :)

2021-11-18 09:50 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +		$u = $this->getUpdateQuery($table);
Was from a copy/paste of the other migrations, updated both of them in fd43e4e

2021-11-18 09:50 UTC, come-nc commented on apps/user_ldap/lib/Mapping/AbstractMapping.php
> +		return (string)hash('sha256', $fdn, false);
Fixed in f36e11e

2021-11-18 09:51 UTC, come-nc commented
> In the first Migration class, the final state of the table should be reflected for new installations. Not necessary to run the while migration history on a new install. So you can add the columns and alter the index in Version1010Date20200630192842.

Done in bb6906d

2021-11-18 09:52 UTC, come-nc commented
> …while at changing DB it might be worth to add a simple index on directory_uuid, too, since this also may be used as sole WHERE column in queries.

Done in c1ff024
Used a unique index as this column should be unique as well, tell me if this needs to be changed to something else.

2021-12-09 16:12 UTC, CarlSchwan commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +<?php
Copyright

2021-12-09 16:17 UTC, skjnldsv approved these changes

2021-12-09 16:17 UTC, CarlSchwan approved these changes

2021-12-09 16:18 UTC, merged

2021-12-09 16:19 UTC, skjnldsv commented
/backport to stable23

2021-12-09 16:19 UTC, skjnldsv commented
/backport to stable22

2021-12-09 16:19 UTC, skjnldsv commented
/backport to stable21

2021-12-09 16:19 UTC, skjnldsv commented
/backport to stable20

2021-12-09 16:22 UTC, CarlSchwan commented
Sorry for remembering that 2 minutes too late, but I think this is missing a version bump. Otherwise the migration won't run in our development instances.

2021-12-10 06:58 UTC, skjnldsv commented
@come-nc please do the backports manually :(