Fix wording on profile page
nextcloud/server pull request #29544
Opened 2021-11-04 01:15 UTC by Pytal

See title 👆

2021-11-04 01:27 UTC, Pytal commented
/compile amend /

2021-11-04 07:50 UTC, juliushaertl requested changes

2021-11-04 07:50 UTC, juliushaertl commented on core/src/views/Profile.vue
> +				: (this.displayname || this.userId) + ' ' + t('core', 'hasn\'t added any info yet')
Building sentences like that might not work in all languages, better include the name as a parameter in the translatable text.
```suggestion
				:  + t('core', '{user} hasn\'t added any info yet', { user: (this.displayname || this.userId) })
```

2021-11-04 23:10 UTC, Pytal commented
/compile amend /

2021-11-04 23:10 UTC, Pytal commented on core/src/views/Profile.vue
> +				: (this.displayname || this.userId) + ' ' + t('core', 'hasn\'t added any info yet')
Done!

2021-11-05 07:33 UTC, juliushaertl approved these changes

2021-11-08 10:56 UTC, artonge approved these changes

2021-11-23 00:11 UTC, Pytal commented
/compile amend /

2021-11-23 01:22 UTC, merged

2021-11-23 01:27 UTC, Pytal commented
/backport to stable23