Respect user enumeration settings on profile
nextcloud/server pull request #29559
Opened 2021-11-05 02:49 UTC by Pytal

The `shareapi_*` user enumeration settings are already respected and hide profile entrypoints (if needed) in the contacts menu, Avatar menu, and other areas which pass through `filterContacts` https://github.com/nextcloud/server/blob/e1c2c13585d5417db2ed490b2986c1ea04cd808d/lib/private/Contacts/ContactsMenu/ContactsStore.php#L150

This PR is for when users navigate to a user's profile page directly by the `/u/{userId}` URL and respects the user enumeration settings listed below.

- `shareapi_allow_share_dialog_user_enumeration`
- `shareapi_restrict_user_enumeration_to_group`
- `shareapi_restrict_user_enumeration_to_phone`

The user's profile will not be displayed and instead show the "Profile not found" error page if restricted by any of these settings.

> The `shareapi_restrict_user_enumeration_full_match` setting currently does not prevent exposure of full names and/or emails within the contacts menu and new conversation menu in Talk, so it is ignored in this PR.

Contributes to https://github.com/nextcloud/server/issues/28139

2021-11-05 09:00 UTC, nickvergessen requested changes

2021-11-05 09:00 UTC, nickvergessen commented on core/Controller/ProfilePageController.php
> +			if (!$this->shareManager->allowEnumeration()) {
```suggestion
			if ($this->shareManager->allowEnumerationFullMatch()) {
				// Full id match is allowed
			} elseif (!$this->shareManager->allowEnumeration()) {
```

2021-11-05 09:00 UTC, nickvergessen commented on core/Controller/ProfilePageController.php
> +						};
```suggestion
						}
```

2021-11-05 09:16 UTC, nickvergessen commented on core/Controller/ProfilePageController.php
> +				}
I already see us repeating this block in other places. Would make sense to abstract it away into new method inside the shareManager?

2021-11-05 09:20 UTC, nickvergessen commented on core/Controller/ProfilePageController.php
> +							&& !$this->knownUserService->isKnownToUser($targetUser->getUID(), $visitingUser->getUID())
UserPlugin logic is `||`

2021-11-05 09:46 UTC, nickvergessen commented on core/Controller/ProfilePageController.php
> +				}
PR in https://github.com/nextcloud/server/pull/29561 if we want to do that

2021-11-05 21:21 UTC, Pytal commented on core/Controller/ProfilePageController.php
> +				}
Good idea! Can use the new method in other places with another PR :)

2021-11-05 21:31 UTC, Pytal commented on core/Controller/ProfilePageController.php
> +							&& !$this->knownUserService->isKnownToUser($targetUser->getUID(), $visitingUser->getUID())
I tested this to reflect the contacts menu i.e. when the user is not shown contacts menu then direct navigation to profile page gives an error. Though there may be slight differences in results since we reimplement this logic across different places 🤔

2021-11-05 21:38 UTC, Pytal commented on core/Controller/ProfilePageController.php
> +							&& !$this->knownUserService->isKnownToUser($targetUser->getUID(), $visitingUser->getUID())
The two elseif's for group and phone should do the same — I tested this to reflect the contacts menu i.e. when the user is not shown contacts menu then direct navigation to profile page gives an error. Though there could be differences in results since we reimplement this logic across different places 🤔

2021-11-09 12:33 UTC, nickvergessen approved these changes
Brought in my feedback as new commit after talking to Chris about it

2021-11-09 12:54 UTC, skjnldsv commented on lib/private/Share20/Manager.php
> +	public function currentUserCanEnumerateTargetUser(?IUser $currentUser, IUser $targetUser): bool {
Would have been nice to have some tests for this one!
If possible before Thursday, let's try to have that, otherwise, let's merge

2021-11-09 13:30 UTC, juliushaertl approved these changes
:+1:

2021-11-09 13:41 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> +	public function currentUserCanEnumerateTargetUser(?IUser $currentUser, IUser $targetUser): bool {
Test added

2021-11-09 14:04 UTC, skjnldsv approved these changes

2021-11-09 22:49 UTC, merged