Polish availibility settings
nextcloud/server pull request #29590
Opened 2021-11-08 10:10 UTC by GretaD

Signed-off-by: greta <gretadoci@gmail.com>

2021-11-08 13:05 UTC, GretaD commented
sha d1c984e it looks like this:

![AVV_SETTIGS](https://user-images.githubusercontent.com/12728974/140746783-cc24df1e-181c-4108-b846-fa52fc1fff4c.png)

Im failing to understand why i cannot style add slot button. It is shown correctly only when we have 2 slots like on Friday.

2021-11-08 13:19 UTC, ChristophWurst commented
> Im failing to understand why i cannot style add slot button. It is shown correctly only when we have 2 slots like on Friday.

Where is it shown incorrectly?

2021-11-08 13:27 UTC, GretaD commented
> > Im failing to understand why i cannot style add slot button. It is shown correctly only when we have 2 slots like on Friday.
> 
> Where is it shown incorrectly?

All the other days is positioned a bit down. When we have one slot, or no slots.

2021-11-08 16:11 UTC, GretaD commented
![availabilitysettings](https://user-images.githubusercontent.com/12728974/140776442-f6e5883c-9098-4a5f-9340-618777c914d0.png)

2021-11-08 18:40 UTC, ChristophWurst requested changes

2021-11-08 18:40 UTC, ChristophWurst commented on apps/dav/src/views/Availability.vue
> +				<button
```suggestion
				<button :key="`add-slot-${day.id}`"
```

2021-11-09 10:07 UTC, ChristophWurst approved these changes

2021-11-09 10:07 UTC, ChristophWurst commented
/compile amend /

2021-11-09 16:58 UTC, st3iny approved these changes

2021-11-09 17:06 UTC, merged