Set 'app_password' in session only when using a permanent token
nextcloud/server pull request #29729
Opened 2021-11-16 10:52 UTC by eneiluj

Like mentioned there https://github.com/nextcloud/globalsiteselector/pull/51#issuecomment-968890543
Maybe we should check the token type to decide if `app_password` should be set in the session.

`getType()` is now declared in `IToken` and implemented by `PublicKeyToken` and `DefaultToken`.

2021-11-22 18:51 UTC, ChristophWurst reviewed
I will also test this a bit but form a code perspective this seems right :+1:

2021-12-29 10:27 UTC, juliushaertl approved these changes

2021-12-30 14:48 UTC, ChristophWurst approved these changes

2022-01-12 16:55 UTC, blizzz commented
CI's happiness would love to get to new heights

2022-04-07 13:09 UTC, blizzz commented
/rebase

2022-06-21 16:30 UTC, blizzz commented
/rebase

2022-06-21 16:57 UTC, blizzz commented on lib/private/Authentication/Token/PublicKeyToken.php
> +		return parent::getType();
@eneiluj can you address this? ^

2022-06-21 16:57 UTC, blizzz requested changes
CI

2022-07-01 08:08 UTC, eneiluj commented
@blizzz Psalm is happy now. Drone failure seems unrelated.

2022-07-01 08:12 UTC, ChristophWurst approved these changes

2022-07-05 11:12 UTC, blizzz commented
Seems to be related tbh. There is a test using a mock which has to return an int value, not null.

> 1) Test\Authentication\Token\PublicKeyTokenProviderTest::testGetToken
> TypeError: Return value of OC\Authentication\Token\PublicKeyToken::getType() must be of the type int, null returned
>
> /drone/src/lib/private/Authentication/Token/PublicKeyToken.php:204
> /drone/src/lib/private/Authentication/Token/PublicKeyTokenProvider.php:123
> /drone/src/tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php:355

2024-02-27 17:51 UTC, skjnldsv commented
Could your rebase and fix conflicts @julien-nc :see_no_evil: :bow:

2024-05-02 14:35 UTC, skjnldsv commented
Closing this pull request due to lack of recent activity and updates. We appreciate your contribution and encourage you to reopen or provide further updates if necessary. :relaxed: 
Our aim is to keep the project moving forward with active collaboration. Thank you for your understanding and continued support! :pray:

2024-05-02 14:35 UTC, closed without merging