Don't use the deprecated method
nextcloud/server pull request #29750
Opened 2021-11-17 14:28 UTC by nickvergessen

Heavily reduces the warning log spam on pages like activity which before printed a warning for each activity every 30 seconds

2021-11-17 14:36 UTC, PVince81 approved these changes
:+1:

strange that we don't have a new utility function for that though

2021-11-17 14:37 UTC, artonge approved these changes

2021-11-17 14:44 UTC, nickvergessen commented
> strange that we don't have a new utility function for that though

We have, and it's marked as deprecated. Also fine with reverting the deprecation:
https://github.com/nextcloud/server/blob/3e624dc39966f54c6d418eee2e8141fc5c21f751/core/src/OC/util.js#L129-L142

2021-11-17 14:57 UTC, juliushaertl requested changes

2021-11-17 14:57 UTC, juliushaertl commented on core/src/init.js
> +				relativeTime = moment(timestamp).fromNow()
If using `@@nextcloud/moment` this sould already be the case when just calling fromow():

https://github.com/nextcloud/nextcloud-moment/blob/master/test/index.test.js#L18

2021-11-17 14:58 UTC, juliushaertl commented on core/src/init.js
> +				relativeTime = moment(timestamp).fromNow()
![image](https://user-images.githubusercontent.com/3404133/142224486-44b9c7f1-5a0e-4f1e-873c-eeadd87eaa29.png)

Which is what gets overwritten in https://github.com/nextcloud/nextcloud-moment/blob/master/lib/index.ts#L22

2021-11-17 15:02 UTC, nickvergessen commented on core/src/init.js
> +				relativeTime = moment(timestamp).fromNow()
So actually we should split by the time diff < 0 and also use tonow?

2021-11-17 15:50 UTC, juliushaertl commented on core/src/init.js
> +				relativeTime = moment(timestamp).fromNow()
No, moment seems to handle that just fine with only calling fromNow:

```
moment(Date.now()-10).fromNow()
"vor ein paar Sekunden"
moment(Date.now()+10).fromNow()
"in ein paar Sekunden"
```

2022-01-14 10:34 UTC, nickvergessen commented on core/src/init.js
> +				relativeTime = moment(timestamp).fromNow()
Finally fixed

2022-01-14 10:38 UTC, juliushaertl approved these changes

2022-01-14 16:20 UTC, merged