Fix getting subnet of ipv4 mapped ipv6 addresses
nextcloud/server pull request #29835
Opened 2021-11-22 13:03 UTC by PVince81

:warning: my knowledge of IPv6 is very limited, so please help double checking whether this makes sense at all

2021-11-22 13:14 UTC, nickvergessen commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
```suggestion
		} elseif (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
```

Does this always mean there is an IPv4 inside? Or can it also be another ipv6?

2021-11-22 13:18 UTC, PVince81 commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
I found this in https://en.wikipedia.org/wiki/IPv6_address#Transition_from_IPv4 but the text doesn't fully match
also https://en.wikipedia.org/wiki/IPv6_address#Special_addresses

I can't say for sure but the more I read about this the more confused I am...

2021-11-22 13:23 UTC, juliushaertl commented on tests/lib/Security/Normalizer/IpAddressTest.php
> +				'::ffff:192.168.0.123/32',
I think the correct subnet mask for a IPv4 to IPv6 mapped address would be /128

2021-11-22 13:28 UTC, juliushaertl commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
Yes, last 32 bits of the ipv6 address are considered to be interpreted as IPv4 (if prefix matches ::ffff:)

Basically the whole IPv4 adress space is then mapped into `::ffff:0:0/96`. The thing I'm not sure about here is, if expanded notation as in `0000:0000:0000:0000:0000:ffff:7f00:0001` should also taken into consideration, which would be the same as `::ffff:127.0.0.1`

2021-11-22 13:30 UTC, come-nc commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
If I understand correctly the code you cannot know for sure the IP will be in canonical form yet?
How does the test behave if you add something like ['::0:ffff:192.168.0.123','::ffff:192.168.0.123/32'] ?

Otherwise from what I understand this prefix is reserved to IPv4 mapped addresses.

2021-11-22 13:45 UTC, PVince81 commented on tests/lib/Security/Normalizer/IpAddressTest.php
> +				'::ffff:192.168.0.123/32',
as discussed in chat we could agree to return the ipv4 form of subnet here, which would be "192.168.0.123/32"

2021-11-22 13:52 UTC, PVince81 commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
yeah, probably I'll use the regexp instead and limit it strictly to "::ffff:x.x.x.x" format ?
or how many more formats do we need to add there ?

2021-11-22 13:52 UTC, PVince81 commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
(also wondering why we're not using a library instead of writing own code like this)

2021-11-22 14:54 UTC, PVince81 commented on lib/private/Security/Normalizer/IpAddress.php
> +		} else if (substr(strtolower($this->ip), 0, 7) === '::ffff:') {
I've now used the binary form to detect all these, see last commit

2021-11-22 14:54 UTC, PVince81 commented on tests/lib/Security/Normalizer/IpAddressTest.php
> +				'::ffff:192.168.0.123/32',
done in last commit

2021-11-22 15:12 UTC, come-nc requested changes
Please fix the type declarations, it should please psalm as well.

2021-11-22 15:12 UTC, come-nc commented on lib/private/Security/Normalizer/IpAddress.php
> +	private function getEmbeddedIpv4($ipv6) {
Since this is a new function please strong type instead of docblock

2021-11-22 15:12 UTC, come-nc commented on lib/private/Security/Normalizer/IpAddress.php
> +	 * @return embedded IPv4 string or false if none was found
```suggestion
	 * @return false|string embedded IPv4 string or false if none was found
```

2021-11-22 15:13 UTC, come-nc commented on lib/private/Security/Normalizer/IpAddress.php
> +	private function getEmbeddedIpv4($ipv6) {
(only applicable for the parameter here, since return type is a union and we need to support PHP7)

2021-11-22 15:14 UTC, juliushaertl commented on lib/private/Security/Normalizer/IpAddress.php
> +	 * @return embedded IPv4 string or false if none was found
```suggestion
	 * @return string|false embedded IPv4 string or false if none was found
```

Or a bit cleaner maybe a nullable string instead of the mixed type

2021-11-22 15:15 UTC, juliushaertl commented on lib/private/Security/Normalizer/IpAddress.php
> +	 * @return embedded IPv4 string or false if none was found
Seems Côme was faster

2021-11-22 15:31 UTC, juliushaertl approved these changes
Looks good apart from the phpdoc issue that psalm has. LGTM once that is resolved

2021-11-22 16:31 UTC, come-nc requested changes

2021-11-22 16:31 UTC, come-nc commented on lib/private/Security/Normalizer/IpAddress.php
> +		$binary = inet_pton($ipv6);
```suggestion
	 * @return string|null embedded IPv4 string or null if none was found
	 */
	private function getEmbeddedIpv4(string $ipv6): ?string {
		$binary = inet_pton($ipv6);
```

2021-11-23 08:14 UTC, come-nc approved these changes

2021-11-23 08:42 UTC, PVince81 commented
failing test "log in with invalid user once fixed by admin" might be related: `/drone/src/tests/acceptance/features/login.feature:38` 

I'll investigate

2021-11-23 08:53 UTC, PVince81 commented
the test passes locally with docker, I wonder if it's timing related.
I'll restart CI just in case

2021-11-23 09:30 UTC, PVince81 commented
/backport to stable23

2021-11-23 09:30 UTC, PVince81 commented
/backport to stable22

2021-11-23 09:30 UTC, PVince81 commented
/backport to stable21

2021-11-23 09:36 UTC, merged