Do not clear all results when searching from users address books
nextcloud/server pull request #29879
Opened 2021-11-24 11:20 UTC by juliushaertl

Steps to reproduce:
- Have any additional addressbook enabled (e.g. contacts app with a contact "A contact user" that has the email "contact@example.com")
- Restrict autocompletion in sharing
- Search for "A contact" in the sharing dialog

Problem: The wide matches in
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Collaboration/Collaborators/MailPlugin.php#L239-L240 are always cleared even though this should only happen for the system address book (actual users of the instance)

2021-11-24 12:25 UTC, PVince81 approved these changes
:+1:

2021-11-24 12:46 UTC, nickvergessen requested changes
Can we have an integration test in https://github.com/nextcloud/server/blob/master/build/integration/collaboration_features/autocomplete.feature

2021-11-24 13:25 UTC, juliushaertl commented
Yes, will look into the integration tests and the failing unit tests:

```

1) Test\Collaboration\Collaborators\MailPluginTest::testSearch with data set #6 ('test', array(array('uid3', 'User3 @ Localhost'), array('uid2', 'User2 @ Localhost', array()), array('uid1', 'User @ Localhost', array('username@localhost'))), false, array(array(), array(array())), false, false)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'emails' => Array (
+        0 => Array (...)
     )
     'exact' => Array (...)
 )

/drone/src/tests/lib/Collaboration/Collaborators/MailPluginTest.php:133

2) Test\Collaboration\Collaborators\MailPluginTest::testSearch with data set #8 ('test@remote.com', array(array('uid3', 'User3 @ Localhost'), array('uid2', 'User2 @ Localhost', array()), array('uid1', 'User @ Localhost', array('username@localhost'))), false, array(array(), array(array(array('test@remote.com', 'test@remote.com', array(4, 'test@remote.com'))))), false, false)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'emails' => Array (
+        0 => Array (...)
     )
     'exact' => Array (...)
 )

/drone/src/tests/lib/Collaboration/Collaborators/MailPluginTest.php:133

3) Test\Collaboration\Collaborators\MailPluginTest::testSearch with data set #12 ('user space@remote.com', array(array('uid3', 'User3 @ Localhost'), array('uid2', 'User2 @ Localhost', array()), array('uid1', 'User @ Localhost', array('username@localhost'))), false, array(array(), array(array())), false, false)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'emails' => Array (
+        0 => Array (...)
     )
     'exact' => Array (...)
 )

/drone/src/tests/lib/Collaboration/Collaborators/MailPluginTest.php:133

--
```

2021-12-03 10:46 UTC, juliushaertl commented
Unit tests adjusted and added intergration tests to cover the MailPlugin with and without enumeration

2021-12-06 08:26 UTC, juliushaertl commented
@nickvergessen I'm a bit confused about the `shareapi_restrict_user_enumeration_full_match` when he parent sharing enumeration is enabled:

![image](https://user-images.githubusercontent.com/3404133/144811937-e772b92d-5df5-4787-ab9c-b2329b31457d.png)

It seems to have no effect in the current UserPlugin/MailPlugin implementation. Is that only relevant if general sharee enumeration is disabled? Also the naming in the UI seems to be confusing as it mentions **allow**, but in the setting itself it is **restrict**.

2021-12-06 08:27 UTC, juliushaertl commented
Basically with the above settings I'd expect to only get full matches, but it seems to return also wide matches for local users.

2021-12-06 14:56 UTC, nickvergessen commented
Explained it a bit in the chat.
The main idea is that when enumeration is restricted, we need an option to say if you are allowed to share/autocomplete/etc when you match the full user id/display name, or if you have to have a common group/phone number match in order to be able to do so.

2021-12-07 09:02 UTC, skjnldsv approved these changes

2021-12-07 09:25 UTC, nickvergessen commented on lib/public/Files/Cache/ICache.php
> +	 * @param array $data [$key => $value] the metadata to update, only thcccce fields provided in the array will be updated, non-provided values will remain unchanged
????

2021-12-08 11:34 UTC, juliushaertl commented on lib/public/Files/Cache/ICache.php
> +	 * @param array $data [$key => $value] the metadata to update, only thcccce fields provided in the array will be updated, non-provided values will remain unchanged
Whoops, sorry not sure how that got in. Addressed.

2021-12-08 11:34 UTC, juliushaertl commented
All tests pass now and remaining one seems unrelated when creating a folder in the sharing acceptance test.

2021-12-21 07:11 UTC, merged