Add hidden user folder
nextcloud/server pull request #29886
Opened 2021-11-24 15:57 UTC by icewind1991

this can be used by apps to have apps that are within the users home folder but are hidden from the normal ui bits.

Currently, the "hidden" part is achieved in the dav plugin excluding it from listing and file search excluding results inside it.

I had originally hoped to have the "hidden" logic be more low level instead of having to implement it separately in each api by my attempts for that didn't work out as they would defeat the purpose of the folder in the first place (having it accessible trough normal endpoints by path and fileid)

2021-11-24 16:14 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/Directory.php
> +		$hiddenName = 'hidden_' . \OC_Util::getInstanceId();
didn't we want it to also start with a dot ?

2021-11-24 16:16 UTC, PVince81 commented on lib/private/Files/Node/Folder.php
> +			$hiddenFolder = 'hidden_' . \OC_Util::getInstanceId();
is there a place where we could expose this as a function to avoid relying on convention only ?

2021-11-25 13:24 UTC, icewind1991 commented
added a function get generate the folder name and added a dot prefix

2021-11-29 15:24 UTC, skjnldsv approved these changes
A bit of tests would be awesome :see_no_evil:

2021-11-29 15:51 UTC, PVince81 commented
- [ ] BUG: create a folder "test" in the web UI then rename it to the hidden folder => this should not be possible
- [ ] BUG: rename hidden folder to another name => this should not be possible
- [ ] BUG: Webdav DELETE on hidden folder did not fail, and I can even recreate it manually
- I assume that a PROPFIND on the hidden folder should not be blocked ? it's not currently

there might be more

yeah, would be good to add maybe integration tests for this to confirm that all file operations are denied there or at least that the folder is protected in some way

2021-11-29 15:53 UTC, PVince81 commented
- [ ] BUG: I shouldn't be able to share the hidden folder with someone else (per API)
- [ ] BUG: while the folder is invisible in the web UI, if I try to create it, it will suddenly reappear with "could not create because it exists already" and suddenly I see it and can access it

2021-11-29 15:55 UTC, PVince81 commented
- [ ] don't create activity entries for any entries inside the hidden folder ? for example if apps are creating custom folders and files there

2022-01-24 14:35 UTC, artonge requested changes
From reading the code:

- What if the user creates a folder with the same name as the hidden folder but in a subfolder.

```
/
/.hidden_azeudhazud    <-- real hidden folder
/sub_folder
/sub_folder/.hidden_azeudhazud    <-- user creates this folder that should maybe not be hidden.
```

If I get this right, the created folder will be considered as hidden by `FileSystem::isPathHidden`.

Is this intended behaviour?

It makes sense if `userA` share his root folder with `userB`


```
/    <-- userB's root folder
/.hidden_azeudhazud    <-- userB's hidden folder
/usera_shared_root_folder    <-- what the name says
/usera_shared_root_folder/.hidden_azeudhazud    <-- userA's hidden folder that should be hidden
```

2022-01-24 14:35 UTC, artonge commented on lib/private/Files/Filesystem.php
> +	public static function isPathHidden($path): string {
```suggestion
	public static function isPathHidden($path): bool {
```

2022-01-24 14:35 UTC, artonge commented on apps/dav/lib/Connector/Sabre/Directory.php
> +		$hiddenName = Filesystem::getHiddenFolderName();
```suggestion
		$hiddenFolderName = Filesystem::getHiddenFolderName();
```

2022-01-24 14:35 UTC, artonge commented on lib/private/Files/Node/Folder.php
> +				if (strpos($mount->getMountPoint(), '/' . $hiddenFolder .'/') !== false) {
```suggestion
				if (Filesystem::isPathHidden($mount->getMountPoint())) {
```

2022-01-24 14:35 UTC, artonge commented on lib/private/Files/Node/Root.php
> +		$hiddenName = Filesystem::getHiddenFolderName();
```suggestion
		$hiddenFolderName = Filesystem::getHiddenFolderName();
```

2022-01-24 14:35 UTC, artonge commented on lib/private/Files/View.php
> +				if (strpos($mountPoint, '/' . $hiddenFolder .'/') !== false) {
```suggestion
				if (Filesystem::isPathHidden($mountPoint)) {
```

2024-08-14 10:19 UTC, closed without merging