Improve accessibility of the title of the settings
nextcloud/server pull request #29881
Opened 2021-11-24 13:11 UTC by CarlSchwan

Before every setting page had the same title and this is causing issues
for screenreaders since they can't differenciate the title of page. Now
a new variable is available for apps to declare the page subtitle.

This new variable is implemented for the settings app and while at it I
added a bit more type hinting to the stuff I touched :)

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2021-11-24 13:50 UTC, artonge requested changes

2021-11-24 13:50 UTC, artonge commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +
Weird to set this info here instead of near the place it's used.

I would move this in `getIndexResponse` and maybe create an `isActiveSection($type, $section)` method to prevent duplicate code.

Less state, more logic.

2021-11-25 08:17 UTC, come-nc commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +			]);
Is that different from : 
`$templateParams['pageTitle'] = $this->activeSection->getName();`
?

2021-11-25 08:17 UTC, come-nc commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +	 * @return list<array{anchor: string, section-name: string, active: bool, icon: string}>
Is it possible to change the return type of section’s getIcon() and getID() to fix the code scanning warning «MoreSpecificReturnType»?

2021-11-25 08:17 UTC, come-nc commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +	private function getIndexResponse(string $type, string $section): TemplateResponse {
Is $section the active section here? If so I agree with @artonge , something feels off in the logic about testing activeSection !== null.

2022-05-16 20:48 UTC, CarlSchwan commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +
done

2022-05-17 10:29 UTC, come-nc approved these changes

2022-05-17 12:54 UTC, artonge approved these changes

2022-09-06 14:56 UTC, merged