Default cache value for null user
nextcloud/server pull request #2998
Opened 2017-01-09 20:36 UTC by Loki3000

For guest users on every request executes query:
SELECT `uid`, `displayname` FROM `users` WHERE LOWER(`uid`) = LOWER(null)
as I see, uid can't be equal to null by design.

2017-01-09 20:38 UTC, rullzer requested changes

2017-01-09 20:38 UTC, rullzer commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
should be `'null'` (since it is a string)

2017-01-09 20:42 UTC, Loki3000 commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
No, NULL isn't string. 
You can check this by adding var_dump:
```
private function loadUser($uid) {
var_dump($uid); //for guest result is NULL
...
}
```

2017-01-09 20:46 UTC, rullzer commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
o wonderfull we don't pass anything. :wink: 
k lets see what CI says then :smile:

2017-01-09 20:46 UTC, rullzer approved these changes

2017-01-09 21:01 UTC, Loki3000 commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
I was trace sql requests and found that in some cases $uid could be ==''
So maybe it's better to modify as follows:
```
private function loadUser($uid) {
   if (empty($uid)) {
        $this->cache[$uid]=false;
        return true;
   }
...
}
```

2017-01-09 21:04 UTC, Loki3000 commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
Is it possible that login is '0' and $uid=='0'?

2017-01-10 09:06 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-01-10 09:06 UTC, MorrisJobke commented
Only sign-off check failed -> but this is a minor change -> merge

2017-01-10 09:06 UTC, merged

2017-01-10 13:15 UTC, nickvergessen commented on lib/private/User/Database.php
> +		$this->cache[null] = false;
Seems to not be an issue on setting:
https://3v4l.org/r2sJR
```php
$a = [];
$a[null] = 1;

var_dump(isset($a[null])); // true
var_dump(isset($a[''])); // true
var_dump(isset($a[0])); // false
var_dump(isset($a['0'])); // false
```

But `0` is an allowed user id, yes