fix #29986
nextcloud/server pull request #29996
Opened 2021-12-01 04:33 UTC by zordsdavini

this stopped upgrade

2021-12-01 08:42 UTC, PVince81 approved these changes
:+1:

2021-12-01 19:45 UTC, Pytal requested changes

2021-12-01 19:45 UTC, Pytal commented on core/Migrations/Version23000Date20210930122352.php
> +			$table->addUniqueIndex(['user_id'], 'pc_user_id');
```suggestion
			$table->addUniqueIndex(['user_id'], 'profile_config_user_id_idx');
```
Would suggest something more explicit :)

2021-12-01 19:45 UTC, Pytal commented
/backport to stable23

2021-12-02 18:40 UTC, Pytal approved these changes

2021-12-02 18:46 UTC, Pytal commented
Thanks @zordsdavini!

Last thing we need is a signoff for your commits with:
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

2021-12-02 18:47 UTC, Pytal commented
Thanks for the fix @zordsdavini!

We just need is a signoff for your commits with:
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

2021-12-02 18:54 UTC, Pytal commented
Thanks for the fix @zordsdavini!

2021-12-02 19:12 UTC, skjnldsv approved these changes

2021-12-03 00:31 UTC, Pytal commented
@skjnldsv @blizzz any idea on the drone failures?

2021-12-03 08:20 UTC, juliushaertl commented
Restarted drone

2021-12-03 10:38 UTC, blizzz requested changes, later dismissed
missing a  repair step to rename the index on existing setup

2021-12-03 20:05 UTC, Pytal commented
Fix now updates index name of original migration to fix new upgrades and adds a new migration for previously migrated setups to rename the existing index

2021-12-09 16:23 UTC, skjnldsv commented on core/Migrations/Version23000Date20211203110726.php
> +		return null;
```suggestion
		$table = $schema->getTable(self::TABLE_NAME);
		if ($table->hasIndex('user_id')) {
			$table->renameIndex('user_id', self::TABLE_NAME . '_user_id_idx');
			return $schema;
		}
		return null;
```

2021-12-09 16:28 UTC, skjnldsv approved these changes

2021-12-09 22:56 UTC, merged