Distributed caches are mem caches
nextcloud/server pull request #30072
Opened 2021-12-03 11:53 UTC by ChristophWurst

Memcached and Redis are instances of IMemcache. That interface is
superior as it has the fancy inc and dec helpers.

For app development it's nice if we can use memcache without an instanceof check.

2021-12-06 08:00 UTC, come-nc commented
Lots of tests needs to be adapted it seems. I do not understand the psalm error: "Type OCP\IMemcache for $lockingCache is always OCP\IMemcache".
Where do me see the file:line information for psalm errors from the CI?

2021-12-06 09:53 UTC, come-nc commented on apps/files_external/tests/Service/StoragesServiceTest.php
> +		;
```suggestion
		$cache = $this->cache = $this->createMock(IMemcache::class);
```

2021-12-06 09:54 UTC, come-nc commented on apps/theming/tests/ThemingDefaultsTest.php
> +		;
```suggestion
		$this->cache = $this->createMock(IMemcache::class);
```

2021-12-06 09:55 UTC, come-nc commented on apps/files_trashbin/tests/StorageTest.php
> +		$cache = $this->cache = $this->createMock(IMemcache::class);
```suggestion
		$cache = $this->createMock(IMemcache::class);
```

2021-12-06 09:58 UTC, come-nc requested changes
Seems like a case of batch replace gone wrong.
Lots of superflous "$this->cache =" and duplicated ";".

2022-04-01 15:07 UTC, closed without merging

2022-04-01 15:11 UTC, ChristophWurst commented
I've raised https://github.com/nextcloud/server/issues/31787 so this can be picked up later.