Remove non required db requests
nextcloud/server pull request #3007
Opened 2017-01-10 10:13 UTC by Loki3000

Remove SQL requests with empty UID for guests.

2017-01-10 10:23 UTC, MorrisJobke requested changes

2017-01-10 10:23 UTC, MorrisJobke commented on lib/private/Group/Database.php
> +
There should be no space at the end of a line.

2017-01-10 10:23 UTC, MorrisJobke commented on lib/private/Group/Database.php
> +		if (empty($uid)) return [];
Please always use curly brackets.

2017-01-10 11:36 UTC, nickvergessen requested changes

2017-01-10 11:36 UTC, nickvergessen commented on lib/private/Group/Database.php
> +		if (empty($uid)) {
Also falsely matches user with id `'0'`

2017-01-10 11:36 UTC, nickvergessen commented on lib/private/User/Database.php
> +			if (empty($uid)) {
Also falsely matches user with id `'0'`

2017-01-10 11:41 UTC, Loki3000 commented on lib/private/User/Database.php
> +			if (empty($uid)) {
I have asked here  [https://github.com/nextcloud/server/pull/2998#discussion_r95245581](url) about $uid=='0', but has no answer. So I was suppose it's not allowed.

2017-01-10 13:40 UTC, MorrisJobke requested changes

2017-01-10 13:40 UTC, MorrisJobke commented on lib/private/Group/Database.php
> +		if ($uid===null || $uid==='') {
please use spaces around the `===`.

2017-01-10 13:40 UTC, MorrisJobke commented on lib/private/User/Database.php
> +			if ($uid===null || $uid==='') {
please use spaces around the `===`.

2017-01-10 15:44 UTC, nickvergessen approved these changes

2017-01-11 09:44 UTC, rullzer commented
@Loki3000 could you squash your commits?

2017-01-11 10:34 UTC, Loki3000 commented
@rullzer sorry, I don't know how to do it.
According to [documentation](https://help.github.com/articles/about-pull-request-merges/) it could be made only by repository owner.

2017-01-11 10:40 UTC, rullzer commented
@Loki3000 see for example http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2017-01-11 11:37 UTC, rullzer approved these changes
Ah lets just get this in actually! THNX A LOT @Loki3000

2017-01-11 11:37 UTC, merged