Add option to disallow creation of local storages
nextcloud/server pull request #30111
Opened 2021-12-06 11:25 UTC by PVince81

Introduce a new config option to prevent web UI admins to create
or edit external storages of type "local".

Fixes https://github.com/nextcloud/server/issues/29973

- [x] TEST: occ command can create
- [x] TEST: cannot create local storages in web UI
- [x] TEST: existing local storages appear grey in web UI
- [x] TEST: test when allowed

Inspired from:
- https://github.com/owncloud/core/pull/27590
- https://github.com/owncloud/core/pull/27621/files?w=1

2021-12-06 16:12 UTC, PVince81 commented
I need to fix some tests:
```

1) OCA\Files_External\Tests\Controller\GlobalStoragesControllerTest::testAddStorage
--


ArgumentCountError:
 Too few arguments to function 
OCA\Files_External\Controller\GlobalStoragesController::__construct(), 7
 passed in 
/drone/src/apps/files_external/tests/Controller/GlobalStoragesControllerTest.php
 on line 59 and exactly 8 expected
```

2021-12-06 19:10 UTC, PVince81 commented
build is passing now, please review

2021-12-06 19:54 UTC, miaulalala approved these changes

2021-12-06 19:54 UTC, miaulalala commented on apps/files_external/templates/settings.php
> +	$canCreateNewLocalStorage = \OC::$server->getConfig()->getSystemValue('files_external_allow_create_new_local', false);
could you use the initial state provider here instead? Pure php in a template gives me the heebies ;)

2021-12-07 09:41 UTC, artonge requested changes

2021-12-07 09:41 UTC, artonge commented on apps/files_external/js/settings.js
> +		}
```suggestion
		var readOnly = backend.identifier === 'local' && !this._canCreateLocal
```

2021-12-07 09:41 UTC, artonge commented on apps/files_external/js/settings.js
> +		var readOnly = false;
```suggestion
```

2021-12-07 09:41 UTC, artonge commented on config/config.sample.php
> + * Defaults to ``false``
Shouldn't it default to `true` to keep to current behaviour?

2021-12-07 10:12 UTC, szaimen commented on config/config.sample.php
> + * Defaults to ``false``
Yes, I wonder as well. 
I understand the reason but I think for better discoverability it should be true. For instances where this feature is a security problem, it can then be manually disabled.

2021-12-13 10:06 UTC, PVince81 commented on apps/files_external/js/settings.js
> +		}
I find my version more readable

2021-12-13 10:07 UTC, PVince81 commented on apps/files_external/js/settings.js
> +		}
ah, but I forgot to remove console.log

ok, I'll clean up

2021-12-13 10:07 UTC, PVince81 commented on apps/files_external/templates/settings.php
> +	$canCreateNewLocalStorage = \OC::$server->getConfig()->getSystemValue('files_external_allow_create_new_local', false);
I'll see what I can do and if it's straightforward

2021-12-13 15:15 UTC, icewind1991 commented on apps/files_external/js/settings.js
> +		console.log(backend, this._canCreateLocal);
left over debug logging :see_no_evil:

2021-12-15 08:24 UTC, PVince81 commented on apps/files_external/templates/settings.php
> +	$canCreateNewLocalStorage = \OC::$server->getConfig()->getSystemValue('files_external_allow_create_new_local', false);
seems that apps/files_external has not be prepped for webpack, ES6 and Vue, so would need to first bootstrap all this before we can make use of initial state and other libs

I think this would blow up the scope of this PR and would rather do so separately.

2021-12-15 08:25 UTC, PVince81 commented
fixed the `readOnly` var, I replaced it with an inline statement now as it was used only in one location
and removed console.log and redid a quick test

2021-12-16 09:56 UTC, artonge approved these changes

2021-12-16 10:12 UTC, merged

2022-03-07 15:39 UTC, icewind1991 commented
/backport to stable23

2022-03-07 15:39 UTC, icewind1991 commented
/backport to stable22