l10n: Add dot at the end of an sentence
nextcloud/server pull request #30123
Opened 2021-12-07 06:20 UTC by rakekniven

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

2022-01-16 15:46 UTC, Valdnet approved these changes

2022-01-16 17:04 UTC, nickvergessen requested changes

2022-01-16 17:04 UTC, nickvergessen commented on apps/updatenotification/src/components/UpdateNotification.vue
> +				: n('updatenotification', '<strong>%n</strong> app has no compatible version for this Nextcloud version available.', '<strong>%n</strong> apps have no compatible version for this Nextcloud versio
```suggestion
				: n('updatenotification', '<strong>%n</strong> app has no compatible version for this Nextcloud version available.', '<strong>%n</strong> apps have no compatible version for this Nextcloud version available.', this.missingAppUpdates.length)
```

2022-01-17 08:14 UTC, skjnldsv approved these changes

2022-01-17 08:15 UTC, skjnldsv commented
@rakekniven please remember to use labels :)

2022-01-17 09:57 UTC, nickvergessen commented
/compile amend /

2022-01-17 10:24 UTC, nickvergessen commented
> Conflicting files
apps/updatenotification/js/updatenotification.js
apps/updatenotification/js/updatenotification.js.map 

Oh come on bot

2022-01-18 08:25 UTC, skjnldsv commented
> > Conflicting files
> > apps/updatenotification/js/updatenotification.js
> > apps/updatenotification/js/updatenotification.js.map
> 
> Oh come on bot

classic! Always rebase before compiling :wink:

2022-01-20 08:33 UTC, rakekniven commented
Could somone please resolve this conflict of packed js files and merge? Thanks.

2022-01-21 08:14 UTC, nickvergessen approved these changes

2022-01-21 08:14 UTC, merged