Smooth time remaining, bitrate and stabilize user information
nextcloud/server pull request #30147
Opened 2021-12-07 21:07 UTC by Phlogi

Improving the upload progress bar's "Time remaining".
Tested with a single large file and multiple smaller files. 

Besides the existing moving average, a smoothing factor is introduced for the time remaining display as well as the bitrate. 
Furthermore, half of the buffer needs to be filled before the first prediction is displayed to the user. This reduces volatile and jumping durations towards the user and improves usability.

2021-12-08 17:35 UTC, CarlSchwan reviewed
Very cool feature, I left some code style but I didn't test it yet locally. I will give it a try tomorrow :)

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +					if (bufferIndex % 4 == 0){
```suggestion
					if (bufferIndex % 4 === 0) {
```

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +					if (smoothBitrate == null){
```suggestion
					if (smoothBitrate === null) {
```

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +					if (bufferIndex == bufferSize - 1){
```suggestion
					if (bufferIndex === bufferSize - 1) {
```

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +					if (smoothRemainingSeconds == null){
```suggestion
					if (smoothRemainingSeconds === null) {
```

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +					if (diffSize <= 0){
```suggestion
					if (diffSize <= 0) {
```

2021-12-08 17:35 UTC, CarlSchwan commented on apps/files/js/file-upload.js
> +				var lastUpdate, lastSize, bufferSize, buffer, bufferIndex, bufferTotal, smoothRemainingSeconds, smoothBitrate;
Ideally declare the new variables near where you are using them. This makes the code easier to read and not look like very old-style C code ;)

2021-12-08 17:59 UTC, Phlogi commented on apps/files/js/file-upload.js
> +				var lastUpdate, lastSize, bufferSize, buffer, bufferIndex, bufferTotal, smoothRemainingSeconds, smoothBitrate;
Well, these need to persist over calling the individual functions using them, so I put them here (not 100% sure if that is necessary). I might have just followed the existing place in the source.

2022-02-15 16:34 UTC, Phlogi commented
Any update?

2022-04-12 09:30 UTC, szaimen requested changes
I just tested this and somehow the speed does not seem to work correctly:
![image](https://user-images.githubusercontent.com/42591237/162928916-5cec703d-a978-49f1-a6f6-170e4c5e5b03.png)

2022-04-12 09:31 UTC, artonge requested changes
Also, canceling an upload seems to fail now

2022-04-18 19:38 UTC, Phlogi commented on apps/files/js/file-upload.js
> +						smoothRemainingSeconds = smoothing * (bufferTotal / bufferSize) + ((1-smoothing) * smoothRemainingSeconds);
It should check for undefined. 
`					if (smoothRemainingSeconds === undefined){`

Same for the bitrate:

`					if (smoothBitrate === undefined){`

I just tested this and the `NaN` problem is fixed.

2022-04-18 19:41 UTC, Phlogi commented
> Also, canceling an upload seems to fail now

I can reproduce this, however I don't think it's related to the change here. I see a 404 in the frontend:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6451003/163866533-c72036e6-2809-45ef-ac88-c54f6efb6a88.png">


Here is the message I see in the debug log on the server side: 

```
{
  "reqId": "QCf3mPDlqWTxKByNmFtN",
  "level": 3,
  "time": "2022-04-18T19:24:22+00:00",
  "remoteAddr": "192.168.1.244",
  "user": "webadmin",
  "app": "core",
  "method": "PUT",
  "url": "/remote.php/dav/uploads/webadmin/web-file-upload-5368d4c4d0bf8c192c21c77fb3e39e95-1650309856915/0",
  "message": "unable to rename, source directory is not writable : uploads/web-file-upload-5368d4c4d0bf8c192c21c77fb3e39e95-1650309856915",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
  "version": "22.2.3.0"
}
{
  "reqId": "QCf3mPDlqWTxKByNmFtN",
  "level": 3,
  "time": "2022-04-18T19:24:22+00:00",
  "remoteAddr": "192.168.1.244",
  "user": "webadmin",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/uploads/webadmin/web-file-upload-5368d4c4d0bf8c192c21c77fb3e39e95-1650309856915/0",
  "message": "renaming part file to final file failed $renameOkay: false, $fileExists: false)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
  "version": "22.2.3.0"
}
{
  "reqId": "QCf3mPDlqWTxKByNmFtN",
  "level": 4,
  "time": "2022-04-18T19:24:22+00:00",
  "remoteAddr": "192.168.1.244",
  "user": "webadmin",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/uploads/webadmin/web-file-upload-5368d4c4d0bf8c192c21c77fb3e39e95-1650309856915/0",
  "message": "Could not rename part file to final file",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
  "version": "22.2.3.0",
  "exception": {
    "Exception": "Sabre\\DAV\\Exception",
    "Message": "Could not rename part file to final file",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 155,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php",
        "line": 45,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1098,
        "function": "createFile",
        "class": "OCA\\DAV\\Upload\\UploadFolder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 333,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 166,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
    "Line": 295,
    "CustomMessage": "--"
  }
}
```

2022-04-19 09:47 UTC, szaimen commented
> Also, canceling an upload seems to fail now

@artonge this is unrelated, afaik.
I think it is failing in master and stable24 too...

2023-08-16 13:03 UTC, merged

2023-08-16 13:07 UTC, szaimen commented
Interesting approach to merge it into a different branch in our org :)