Only wildcard search if enumeration is allowed
nextcloud/server pull request #30156
Opened 2021-12-08 15:42 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2021-12-08 15:46 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/MailPlugin.php
> +				'wildcard' => $this->shareeEnumeration,
I think we would still be fine to search with wild cards in the personal addressbooks, but it would result in the same unindexed query again, or we have to make sure it uses the index for the addressbook id then

2021-12-08 15:48 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			} else if (!$escapePattern) {
```suggestion
			} elseif (!$escapePattern) {
```

2021-12-08 15:48 UTC, CarlSchwan approved these changes

2021-12-08 16:00 UTC, skjnldsv approved these changes

2021-12-08 16:01 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/MailPlugin.php
> +				'wildcard' => $this->shareeEnumeration,
Solved by moving the wildcarding one level down

2021-12-08 16:04 UTC, nickvergessen commented on lib/public/Contacts/IManager.php
> +	 * 	- 'fullmatch' - Whether matching on full detail in system addresss book is allowed
Should document the since before final merge

2021-12-08 16:04 UTC, nickvergessen commented on lib/public/IAddressBook.php
> +		 * 	- 'wildcard' - Whether the search should use wildcards
Should document the since before final merge

2021-12-08 16:30 UTC, nickvergessen commented
Fixed more entry points to first specify a limit where we only use the first entry anyway, use strict search where we only work with a full value anyway (like resolving a known cloudid) and opted out of the system addressbook when we later on skipped that anyway

2021-12-08 16:32 UTC, artonge commented on apps/federatedfilesharing/lib/Notifier.php
> +			'strict_search' => true,
`strict_search` should be removed everywhere, no?

2021-12-08 16:36 UTC, artonge approved these changes

2021-12-08 16:36 UTC, artonge commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +		$useWildcards = !\array_key_exists('wildcard', $options) || $options['wildcard'] !== false;
Or add it to this condition

```suggestion
		$useWildcards = !(array_key_exists('wildcard', $options) && $options['wildcard'] === true) || (array_key_exists('strict_search', $options) && $options['strict_search'] === true);
```

2021-12-08 16:45 UTC, nickvergessen commented on apps/federatedfilesharing/lib/Notifier.php
> +			'strict_search' => true,
No, it's fine on the calls to the contacsmanager. I just forgot to convert it there to the wildcrad flag for the other addressbooks

2021-12-08 16:46 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +		$useWildcards = !\array_key_exists('wildcard', $options) || $options['wildcard'] !== false;
Or that, yeah

2021-12-08 17:28 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/AddressBookImpl.php
> +	 * 	- 'wildcard' - Whether the search should use wildcards
```suggestion
	 * 	- 'wildcard' - Whether the search should use wildcards
	 * @psalm-param ?array{types: ?bool, escape_like_param: ?bool, limit: ?int, offset: ?int, wildcard: ?string} $options
```

Unrelated improvement that could be added at the same time for better static analysis :) The same should be added to the other method definitions.

2021-12-08 17:55 UTC, nickvergessen commented on apps/federatedfilesharing/lib/Notifier.php
> +			'strict_search' => true,
Implemented

2021-12-08 17:55 UTC, nickvergessen commented on apps/dav/lib/CardDAV/AddressBookImpl.php
> +	 * 	- 'wildcard' - Whether the search should use wildcards
Added

2021-12-08 18:06 UTC, artonge requested changes

2021-12-08 18:06 UTC, artonge commented on lib/private/ContactsManager.php
> +			$strictSearch = !\array_key_exists('strict_search', $options) || $options['strict_search'] !== false;
Will be `true` if `strict_search` key does not exist.

```suggestion
			$strictSearch = array_key_exists('strict_search', $options) && $options['strict_search'] == true;
```

2021-12-08 18:07 UTC, nickvergessen commented on lib/private/ContactsManager.php
> +			$strictSearch = !\array_key_exists('strict_search', $options) || $options['strict_search'] !== false;
ops, that's right

2021-12-08 18:07 UTC, CarlSchwan commented on lib/private/ContactsManager.php
> +			$strictSearch = !\array_key_exists('strict_search', $options) || $options['strict_search'] !== false;
=== and not ==

2021-12-08 18:11 UTC, artonge commented on lib/private/ContactsManager.php
> +			$strictSearch = !\array_key_exists('strict_search', $options) || $options['strict_search'] !== false;
Yes, forgot a `=` in my suggestion. Conditions are hard :(

2021-12-08 18:25 UTC, nickvergessen commented on lib/private/ContactsManager.php
> +			$strictSearch = !\array_key_exists('strict_search', $options) || $options['strict_search'] !== false;
fixed

2021-12-08 18:27 UTC, artonge approved these changes

2021-12-08 18:44 UTC, CarlSchwan approved these changes

2021-12-09 09:18 UTC, merged

2021-12-13 12:34 UTC, artonge commented
/backport to 22

2021-12-13 12:44 UTC, nickvergessen commented
/backport to 23