Filter out sensitive appconfig values
nextcloud/server pull request #3023
Opened 2017-01-11 10:43 UTC by nickvergessen

Fix #2915 

@MorrisJobke @LukasReschke

2017-01-11 16:13 UTC, MorrisJobke requested changes
Please fix the failing unit tests

2017-01-12 10:41 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-01-12 11:22 UTC, blizzz commented on lib/private/AppConfig.php
> +		return false;
Why do we return unconditional false?

2017-01-12 11:25 UTC, nickvergessen commented on lib/private/AppConfig.php
> +		return false;
The method is deprecated anyway
and I just wanted to make it match the defined `@return bool`. Also it's very discussable if deleting non existing items should return true (entry does not exist anymore afterwards) or false (could not delete).

2017-01-17 09:45 UTC, ChristophWurst commented on lib/private/AppConfig.php
> +	 * @deprecated 8.0.0 use method setAppValue of \OCP\IConfig
Why is this deprecated since 8? Was the annotation missing?

2017-01-17 09:56 UTC, nickvergessen commented on lib/private/AppConfig.php
> +	 * @deprecated 8.0.0 use method setAppValue of \OCP\IConfig
It's mentioned on the interface since 8, but the implementation was missing the hint, therefor the fancy EA plugin of phpstorm complained that the method implements a deprecated interface without being deprecated itself.

2017-01-17 10:01 UTC, ChristophWurst commented on lib/private/AppConfig.php
> +	 * @deprecated 8.0.0 use method setAppValue of \OCP\IConfig
makes sense 👍

2017-01-17 10:01 UTC, ChristophWurst approved these changes

2017-01-17 10:01 UTC, merged