l10n: Correct spelling
nextcloud/server pull request #30240
Opened 2021-12-13 09:24 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-12-13 11:19 UTC, skjnldsv approved these changes

2021-12-13 11:26 UTC, come-nc approved these changes

2021-12-13 12:48 UTC, rakekniven requested changes

2021-12-13 12:48 UTC, rakekniven commented on apps/encryption/templates/altmail.php
> +print_unescaped($l->t("Hey there,\n\nThe administrator enabled server-side-encryption. Your files were encrypted using the password \"%s\".\n\nPlease login to the web interface, go to the section \"B
admin -> administration

2021-12-13 12:48 UTC, rakekniven commented on apps/encryption/templates/mail.php
> +						print_unescaped($l->t('Hey there,<br><br>The administrator enabled server-side-encryption. Your files were encrypted using the password <strong>%s</strong>.<br><br>Please login to the web inter
admin -> administration

2021-12-13 12:49 UTC, rakekniven commented on apps/encryption/templates/mail.php
> +						print_unescaped($l->t('Hey there,<br><br>The administrator enabled server-side-encryption. Your files were encrypted using the password <strong>%s</strong>.<br><br>Please login to the web inter
Keep it neutral like we do in other new strings.

2021-12-13 12:49 UTC, rakekniven commented on apps/encryption/templates/altmail.php
> +print_unescaped($l->t("Hey there,\n\nThe administrator enabled server-side-encryption. Your files were encrypted using the password \"%s\".\n\nPlease login to the web interface, go to the section \"B
Keep it neutral like we do in other new strings.

2021-12-13 12:59 UTC, Valdnet commented on apps/encryption/templates/altmail.php
> +print_unescaped($l->t("Hey there,\n\nThe administrator enabled server-side-encryption. Your files were encrypted using the password \"%s\".\n\nPlease login to the web interface, go to the section \"B
> admin -> administration

I was wondering about that too, and found it to be a person as administrator.

> Keep it neutral like we do in other new strings.

Done 😉.

2021-12-13 13:00 UTC, rakekniven approved these changes

2021-12-13 13:00 UTC, Valdnet commented on apps/encryption/templates/mail.php
> +						print_unescaped($l->t('Hey there,<br><br>The administrator enabled server-side-encryption. Your files were encrypted using the password <strong>%s</strong>.<br><br>Please login to the web inter
Done 😉.

2021-12-13 15:53 UTC, merged

2022-01-07 20:59 UTC, rakekniven commented
Do we want to backport such changeds to latest supported NC versions?

2022-02-02 06:17 UTC, rakekniven commented
/backport stable23

2022-09-04 11:31 UTC, Valdnet commented
@szaimen This text string still exists unchanged in Transifex. Can you check why?

2022-09-04 11:34 UTC, szaimen commented
Sorry no idea

2022-09-04 12:23 UTC, szaimen commented
doesnt look like it...