Add oauth2_clients migration for Owncloud
nextcloud/server pull request #30276
Opened 2021-12-15 09:50 UTC by artonge

2021-12-16 16:12 UTC, ChristophWurst requested changes

2021-12-16 16:12 UTC, ChristophWurst commented on lib/private/Repair/Owncloud/MigrateOauthTables.php
> +		$schema = new SchemaWrapper($this->db);
Maybe I just haven't seen any such code before, but building those migrations by hand and outside of regular migrations feels like something is off.

Why is this not done in a regular migration?

2021-12-20 12:03 UTC, artonge commented on apps/oauth2/lib/Migration/Version010402Date20190107124745.php
> +		// The identifier column comes from Owncloud, skip this migration as long as the repair step as not been ran to rename the column.
Indeed, I corrected the comment. The migration does not need to be run as the Owncloud migration step will add the index to the column later.

2021-12-20 12:04 UTC, artonge commented on lib/private/Repair/Owncloud/MigrateOauthTables.php
> +		$schema = new SchemaWrapper($this->db);
It is not a regular migration but a repair step. I took inspiration from existing ones: https://github.com/nextcloud/server/tree/master/lib/private/Repair/Owncloud

2021-12-20 12:05 UTC, artonge commented
/backport to stable23

2021-12-20 12:08 UTC, artonge commented
Limiting backport to stable22 for now. Should we backport this to older versions too? Not sure if the migration path is `OC v10 -> NC20 -> ...` or `OC v10 -> NC latest`

2021-12-27 14:49 UTC, splitt3r commented on apps/oauth2/lib/Migration/Version010402Date20190107124745.php
> +		// Skip this migration if the 'identifier' column from ownCLoud is present, as the 'client_identifier' column would not exists.
```suggestion
		// Skip this migration if the 'identifier' column from ownCloud is present, as the 'client_identifier' column would not exists.
```

2021-12-27 14:49 UTC, splitt3r commented on lib/private/Repair/Owncloud/MigrateOauthTables.php
> +	 * MoveAvatars constructor.
This needs to be updated.

2021-12-27 14:50 UTC, splitt3r commented on lib/private/Repair/Owncloud/MigrateOauthTables.php
> +			$output->info("oauth2_clients table does not exists.");
```suggestion
			$output->info("oauth2_clients table does not exist.");
```

2022-01-04 16:22 UTC, artonge commented
/rebase

2022-03-24 10:23 UTC, artonge commented
/rebase

2022-03-24 17:11 UTC, PVince81 approved these changes
:+1:

2022-03-24 17:16 UTC, Pytal approved these changes

2022-03-28 09:14 UTC, merged