l10n: Separate words and add dots
nextcloud/server pull request #30284
Opened 2021-12-15 16:38 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-12-16 11:01 UTC, rakekniven commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
@Valdnet Have you tried it with the code statement? Does this render correctly?

2021-12-16 16:40 UTC, Valdnet commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
> Have you tried it with the code statement?

No. I matched this text string with the following text string where `code` is used:

https://github.com/nextcloud/server/blob/9a37ca9b480c9cd3ea6474db2c6f52908c653aaf/lib/private/legacy/OC_Util.php#L923

> Does this render correctly?

If `code` displays correctly for the variable `'hint'` then I think it will be correct for `'error'` too.

2021-12-17 14:59 UTC, rakekniven commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
@Valdnet Ok for me. Let us see if a developer of the server app can check that.

2021-12-18 13:30 UTC, Valdnet commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
@blizzz @skjnldsv @ChristophWurst Please give your opinion on the use of `code` and approve.

2021-12-19 09:47 UTC, skjnldsv approved these changes

2021-12-19 10:06 UTC, skjnldsv commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
Didn't see this, not sure tbh

2021-12-20 07:32 UTC, Valdnet commented on lib/private/legacy/OC_Util.php
> +				'error' => $l->t('<code>mbstring.func_overload</code> is set to <code>%s</code> instead of the expected value <code>0</code>.', [$iniWrapper->getString('mbstring.func_overload')]),
This is a text string in php, so it should display correctly:
Example:

![obraz](https://user-images.githubusercontent.com/47037905/146728204-c444c543-eda3-4590-88d8-b9d92f65db82.png)

Also, I believe that this is the correct syntax. 

Transifex also correctly displays `code`. Example for another text string:

![obraz](https://user-images.githubusercontent.com/47037905/146728550-081a8725-1709-4b17-8bc5-438084ade893.png)

2021-12-20 13:33 UTC, miaulalala approved these changes

2021-12-20 14:32 UTC, rakekniven approved these changes

2021-12-20 18:05 UTC, Valdnet commented
@nickvergessen Please merge 😉.

2022-01-04 16:12 UTC, nickvergessen commented
> Please merge wink.

Why me? Anyone can. You don't need to wait until I'm back from vacations :P

2022-01-04 16:13 UTC, nickvergessen requested changes
But there are 2 failing unit tests which need fixing first

2022-01-05 14:45 UTC, Valdnet commented
> You don't need to wait until I'm back from vacations :P

I didn't know you were on vacation 😁.

> But there are 2 failing unit tests which need fixing first

Which mistakes are you writing about? If they are, how do you fix them?

2022-01-05 15:23 UTC, nickvergessen commented
![Bildschirmfoto von 2022-01-05 16-23-26](https://user-images.githubusercontent.com/213943/148242811-f3d14d70-642f-4c43-87c9-735160c41aae.png)

2022-01-05 17:04 UTC, Valdnet commented
> But there are 2 failing unit tests which need fixing first

Done 😉.

2022-01-07 09:20 UTC, merged