Migrate to Symfony Mailer using rector
nextcloud/server pull request #30349
Opened 2021-12-20 10:36 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

See https://github.com/nextcloud/server/issues/29731

2021-12-20 10:42 UTC, come-nc commented
Thir rector is clearly not enough for the migration, left instances of Swift in the code:
```
lib/private/Mail/Mailer.php:            return new Attachment(new \Swift_Attachment($data, $filename, $contentType));
lib/private/Mail/Mailer.php:            return new Attachment(\Swift_Attachment::fromPath($path, $contentType));
lib/private/Mail/Mailer.php:                    $mailLogger = new \Swift_Plugins_Loggers_ArrayLogger();
lib/private/Mail/Mailer.php:                    $mailer->registerPlugin(new \Swift_Plugins_LoggerPlugin($mailLogger));
lib/private/Mail/Mailer.php:            $mailer->send($message->getSwiftMessage(), $failedRecipients);
lib/private/Mail/Mailer.php:     * SwiftMailer does currently not work with IDN domains, this function therefore converts the domains
lib/private/Mail/Mailer.php:     * FIXME: Remove this once SwiftMailer supports IDN
lib/private/Mail/Message.php: * Class Message provides a wrapper around SwiftMail
lib/private/Mail/Message.php:           $this->swiftMessage->attach($attachment->getSwiftAttachment());
lib/private/Mail/Message.php:    * SwiftMailer does currently not work with IDN domains, this function therefore converts the domains
lib/private/Mail/Message.php:    * FIXME: Remove this once SwiftMailer supports IDN
lib/private/Mail/Message.php:    * Get's the underlying SwiftMessage
lib/private/Mail/Message.php:   public function setSwiftMessage(\Symfony\Component\Mime\Email $swiftMessage): void {
lib/private/Mail/Message.php:    * Get's the underlying SwiftMessage
lib/private/Mail/Message.php:   public function getSwiftMessage(): \Symfony\Component\Mime\Email {
lib/private/Mail/Attachment.php:        /** @var \Swift_Mime_Attachment */
lib/private/Mail/Attachment.php:        public function __construct(\Swift_Mime_Attachment $attachment) {
lib/private/Mail/Attachment.php:         * @return \Swift_Mime_Attachment
lib/private/Mail/Attachment.php:        public function getSwiftAttachment(): \Swift_Mime_Attachment {
lib/private/SystemConfig.php:                           // Legacy Swift (https://github.com/nextcloud/server/pull/17696#discussion_r341302207)
lib/private/SystemConfig.php:                           // Swift v2
lib/private/SystemConfig.php:                           // Swift v3
lib/private/SystemConfig.php:                           // Swift v2
lib/private/SystemConfig.php:                           // Swift v3
```

2022-09-30 14:33 UTC, come-nc commented
/rebase

2022-10-04 09:18 UTC, come-nc commented
Known missing things:

- [ ] setStreamOptions support. This seems not possible with symfony/mailer. https://github.com/nextcloud/server/issues/12702 seems to suggest that it is mainly used to accept self-signed certificate, maybe we can look into supporting that one usecase if possible.
- [ ] timeout setting is currently commented out. Probably possible to fix that but I did not find yet where.

2022-10-04 09:23 UTC, ChristophWurst approved these changes

2022-10-05 07:55 UTC, come-nc commented
Stream options and timeout support are back. Just have to use getStream on the transport and work directly on the stream.

So, tests are green, but I did not actually test that this is able to send any email. Anyone has a setup to test this? Does the CI test it?

2022-10-05 07:58 UTC, come-nc commented
Ouh, there is still something fishy, the send method is supposed to return the failedRecipient but I did not find how to do that.

2022-10-05 08:20 UTC, come-nc commented
> Ouh, there is still something fishy, the send method is supposed to return the failedRecipient but I did not find how to do that.

Also lots of problems spotted by psalm.

- [ ] `mail_smtpauthtype` option config will have to be deprecated, symfony/mailer select authmethod automatically and do not support forcing it.

2022-10-05 08:45 UTC, come-nc commented
From the code:
```
	 * SwiftMailer does currently not work with IDN domains, this function therefore converts the domains
	 * FIXME: Remove this once SwiftMailer supports IDN
```
- [ ] Check if symfony/mailer support IDN and we can get rid of this

2022-10-05 09:22 UTC, come-nc commented
> Ouh, there is still something fishy, the send method is supposed to return the failedRecipient but I did not find how to do that.

There is no way to do that so it returns an empty array. The method description said this is not always available anyway, and errors can be thrown when sending fails.

2022-10-14 11:30 UTC, miaulalala approved these changes

2022-11-21 14:00 UTC, come-nc commented on lib/private/Mail/Mailer.php
> +			null,
This null is a boolean used to indicate if tls should be used.
If null is given, the logic is:
```php
        if (null === $tls) {
            if (465 === $port) {
                $tls = true;
            } else {
                $tls = \defined('OPENSSL_VERSION_NUMBER') && 0 === $port && 'localhost' !== $host;
            }
        }
        if (!$tls) {
            $stream->disableTls();
        }
        if (0 === $port) {
            $port = $tls ? 465 : 25;
        }
```

It’s not clear for me if we should keep passing null or if we should somehow plug `mail_smtpsecure` config option in there.

2022-11-21 15:54 UTC, come-nc commented
TODO:
- Figure out if `mail_smtpsecure` should be dropped or re-implemented (see https://github.com/nextcloud/server/pull/30349#issuecomment-1268107105 and https://github.com/nextcloud/server/pull/30349#discussion_r1028074804 )
- Drop `mail_smtpauthtype`
- Test that mail sending still works
- Test as much as possible
- Remove workaround code pointed by https://github.com/nextcloud/server/pull/30349#issuecomment-1268135892 and see if it still works for addresses with IDN in it. If yes remove this workaround. If not update the comment.
- Document changes in behavior, API and configuration.

@PVince81 @ChristophWurst I’d say maybe a week of work?

2023-01-16 14:21 UTC, miaulalala commented
We might be able to remove the egulias package as symphony mailer includes its own validator: https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/EmailValidator.php

2023-01-19 17:40 UTC, miaulalala commented on lib/private/Mail/Mailer.php
> +			null,
STARTTLS with port 578 can't be enforced any longer. The automatic config will use it if the server advertises STARTTLS, but there is no config option any longer.

If explicit TLS (465) in the config.php or settings is set, we still use that and set the $tls param to true.

2023-01-19 18:23 UTC, ChristophWurst commented on lib/private/Mail/Message.php
> +		if (!empty($this->getBcc())) {
check can probably be skipped if passing empty arrays into cc/bcc is allowed

2023-01-24 13:27 UTC, ChristophWurst commented
Tested with my personal SMTP test account that had already been set up for older releases and it still works :+1:

2023-01-25 11:22 UTC, juliushaertl commented
https://github.com/nextcloud/3rdparty/pull/1179 is merged

2023-01-30 14:59 UTC, come-nc commented on lib/private/Mail/Mailer.php
> +	 * @return array []|string[] $failedRecipients
```suggestion
	 * @return string[] $failedRecipients
```

2023-01-30 15:00 UTC, come-nc commented
(I cannot approve as author of the PR, but I hereby approve what @miaulalala did :+1: )

2023-01-30 16:03 UTC, miaulalala commented on lib/private/Mail/Mailer.php
> +	 * @return array []|string[] $failedRecipients
but it can also be an empty array when sending works

2023-01-30 16:24 UTC, tcitworld commented on lib/private/Mail/Mailer.php
> +	 * @return array []|string[] $failedRecipients
`string[]` covers empty arrays already :)

2023-01-30 16:37 UTC, miaulalala commented
documentation ticket here: https://github.com/nextcloud/documentation/issues/9600

2023-01-30 16:38 UTC, miaulalala commented on lib/private/Mail/Mailer.php
> +	 * @return array []|string[] $failedRecipients
I didn't know that! will change it

2023-01-31 09:46 UTC, ChristophWurst commented
> There were 10 errors:

2023-02-01 15:57 UTC, ChristophWurst reviewed
Looks sane otherwise

2023-02-01 15:57 UTC, ChristophWurst commented on apps/settings/lib/Controller/MailSettingsController.php
> +use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
unused?

2023-02-01 15:57 UTC, ChristophWurst commented on config/config.sample.php
> +// 'mail_smtpauthtype' => 'LOGIN',
drop if not used anymore?

2023-02-01 15:57 UTC, ChristophWurst commented on lib/public/Mail/IMailer.php
> +	 * @deprecated 26.0.0 Implicit validation is done in \OC\Mail\Message::setRecipients
just deprecate. the rest is internal info no API user should depend on

2023-02-01 15:57 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	 * @return array [] | string[]
`array[]` means two-dimensional array. It is the same as `mixed[][]`.

do we need the getter in the public interface?

2023-02-01 15:57 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
only expose if really required on the public interface

2023-02-01 16:14 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
elaborate

2023-02-01 16:16 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
In `send` you get an IMessage. Throw an InvalidArgumentException if someone passes an object that is not an instance of the Message implementation created by `createMessage`. After this check you can safely assume that you have a Message, not just an IMessage and call Message::getSubject

2023-02-01 16:16 UTC, tcitworld commented on lib/public/Mail/IMailer.php
> +	 * @deprecated 26.0.0 Implicit validation is done in \OC\Mail\Message::setRecipients
I don't think it should be depreciated though. There are valid uses of checking if an email's syntax is valid without sending an email at the same time.

2023-02-01 16:18 UTC, tcitworld commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
Could be useful in some kind of treatment to the emails after they're built, such as prefixing them.

2023-02-01 16:20 UTC, tcitworld commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
It's not *needed* though, it's fine

2023-02-01 16:21 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	public function getSubject(): string;
Let's expose the getter when we need it. Until then: YAGNI :)

2023-02-02 08:40 UTC, ChristophWurst commented on lib/public/Mail/IMailer.php
> +	 * @deprecated 26.0.0 Implicit validation is done in \OC\Mail\Message::setRecipients
You are right. This migration has nothing to do with the validation. Validation can still make sense without sending a message :+1:

2023-02-02 08:42 UTC, ChristophWurst requested changes

2023-02-02 08:42 UTC, ChristophWurst commented on lib/public/Mail/IMailer.php
> +	 * @deprecated 26.0.0
let's undo this. email validation is still useful

2023-02-02 09:19 UTC, ChristophWurst approved these changes

2023-02-02 10:42 UTC, merged

2023-02-21 14:14 UTC, miaulalala commented
@DaphneMuller https://github.com/nextcloud/documentation/issues/9600 is the documentation ticket

2023-07-08 16:53 UTC, joshtrichards commented
Indirectly completes #29333