Allow DAV Object properties
nextcloud/server pull request #30368
Opened 2021-12-21 15:29 UTC by tcitworld

The current implementation only saves them as string. It seems they can be more complex than that, and that objects were saved directly.

You may find such objects saved in some production databases by executing:
```sql
SELECT * from oc_properties where propertyvalue = 'Object';
```

This seems to cause issues in some particular cases (https://github.com/nextcloud/calendar/issues/3551) like the calendar trashbin because of things like this and (apparently ?) Apple devices:
https://github.com/nextcloud/server/blob/0b01103137aea94c65f784980dfec645958faaf7/apps/dav/lib/CalDAV/CalDavBackend.php#L3208-L3211

This commit adds a repair job to clean all of these "broken" properties values, adds a new database column to save the type of the property, and handles converting from and to correct values.

Implementation is very similar to SabreDAV's own PDO backend: https://github.com/nextcloud/3rdparty/blob/4921806dfb1c5c309eac60195ed34e2749baf3c1/sabre/dav/lib/DAV/PropertyStorage/Backend/PDO.php

2021-12-21 15:32 UTC, tcitworld commented on apps/dav/lib/Migration/RemoveObjectProperties.php
> +			->where($query->expr()->eq('propertyname', $query->createNamedParameter(self::RESOURCE_TYPE_PROPERTY)))
**Important note** : I chose to delete only `{DAV:}resourcetype` properties because they were the ones involved in the calendar issue, but there might be more concerned `propertyname`s.

I didn't want to directly remove the condition on `propertyname` in case there's some legitimate `Object` `propertyvalue`s, (which seems however unlikely).

2021-12-21 15:45 UTC, tcitworld commented on apps/dav/lib/Migration/RemoveObjectProperties.php
> +			->where($query->expr()->eq('propertyname', $query->createNamedParameter(self::RESOURCE_TYPE_PROPERTY)))
Found two extra property names affected:
* `{http://calendarserver.org/ns/}me-card` 
* `{urn:ietf:params:xml:ns:caldav}schedule-calendar-transp`

2022-02-15 09:25 UTC, tcitworld commented
I think this is a better way to handle things than converting to string https://github.com/nextcloud/server/pull/30771

2022-05-16 12:39 UTC, come-nc commented on apps/dav/lib/DAV/CustomPropertiesBackend.php
> +						);
Why the extra tab? Previous indentation seemed correct.

2022-05-16 12:43 UTC, come-nc requested changes

2022-05-16 12:43 UTC, come-nc commented on apps/dav/lib/DAV/CustomPropertiesBackend.php
> +			case null:
```suggestion
```
The int type does not allow null.
Maybe you meant `default:`?

2022-05-16 12:43 UTC, come-nc commented on apps/dav/lib/Migration/Version1024Date20211221144219.php
> +			'default' => 1 // CustomPropertiesBackend::PROPERTY_TYPE_STRING
You can use the constant here, no?

2022-05-16 12:43 UTC, come-nc commented on apps/dav/lib/Migration/Version1024Date20211221144219.php
> +		return $schema;
Please check if the column exists and return a changed schema only if needed, otherwise return null.

2022-05-16 13:02 UTC, tcitworld commented on apps/dav/lib/DAV/CustomPropertiesBackend.php
> +			case null:
Copied without thinking from the Sabre implementation. The database field doesn't accept nullable values in any case, so we're safe.

2022-05-16 13:02 UTC, tcitworld commented on apps/dav/lib/DAV/CustomPropertiesBackend.php
> +						);
IDE stuff. `cs-fixer` didn't catch it :thinking:

2022-05-16 13:59 UTC, come-nc approved these changes

2022-06-10 15:06 UTC, PVince81 approved these changes
Makes sense, old known issue :+1: 

Also will likely solve issues with Oracle when storing complex props as I rembember issues there

2022-06-10 15:07 UTC, merged

2022-06-10 15:08 UTC, PVince81 commented
25 only as it adds a new column and might be an expensive upgrade