Add comments reactions
nextcloud/server pull request #30379
Opened 2021-12-22 18:12 UTC by vitormattos

Changes on app comments to resolve https://github.com/nextcloud/spreed/issues/1920

2021-12-22 18:16 UTC, vitormattos commented
static tests fixed on #30370

2021-12-27 16:08 UTC, ChristophWurst commented on lib/private/Comments/Comment.php
> +	public function setReactions(?array $reactions): IComment {
document the array type with phpdoc. is this an array of strings?

2021-12-27 16:08 UTC, ChristophWurst commented on lib/public/Comments/IComment.php
> +	 * @return array e.g. ["👍":1]
```suggestion
	 * @return string[] e.g. ["👍":1]
```

2021-12-27 16:08 UTC, ChristophWurst commented on lib/public/Comments/IComment.php
> +	 * @param array|null $reactions e.g. ["👍":1]
```suggestion
	 * @param string[]|null $reactions e.g. ["👍":1]
```

and are there legitimate use cases where assigning `null` makes sense? Otherwise I would limit the API to assignments of non-null array.

2022-01-02 19:15 UTC, nickvergessen requested changes

2022-01-02 19:15 UTC, nickvergessen commented on core/Migrations/Version24000Date20211222112246.php
> +			$table->addIndex(['parent_id'], self::TABLE_NAME . '_parent_id_index');
Table names are prefixed automatically on some dbs same for an `_IDX` suffix, so keep the index names short:
```suggestion
			$table->addIndex(['reaction'], 'comment_reaction');
			$table->addIndex(['parent_id'],  'comment_parent');
```

2022-01-02 19:15 UTC, nickvergessen commented on core/Migrations/Version24000Date20211222112246.php
> +			$table->addUniqueIndex(['parent_id', 'actor_type', 'actor_id', 'reaction'], self::TABLE_NAME . '_unique_index');
```suggestion
			$table->addUniqueIndex(['parent_id', 'actor_type', 'actor_id', 'reaction'], 'comment_reaction_unique');
```

2022-01-02 19:15 UTC, nickvergessen commented on core/Migrations/Version24000Date20211222112246.php
> +			$table = $schema->createTable(self::TABLE_NAME);
Please wrap in a second if, in case the first part is there already because a backup was restored

2022-01-02 19:15 UTC, nickvergessen commented on lib/private/Comments/Comment.php
> +	 * @return array<integer, string> e.g. ["👍":1]
description does not match example

2022-01-02 19:15 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	private function getCommentsOnList(array $objectIds): array {
Comment with array of strings?

2022-01-02 19:29 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	private function getCommentsOnList(array $objectIds): array {
This is a private method to get all reaction comments.

2022-01-03 10:05 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	private function getCommentsOnList(array $objectIds): array {
I implemented docblock to make more clearly

2022-01-03 12:13 UTC, nickvergessen commented on lib/private/Comments/Comment.php
> +	 * @return array<string, integer> e.g. ["👍":1]
![Bildschirmfoto von 2022-01-03 13-12-15](https://user-images.githubusercontent.com/213943/147929027-edd7f707-fc68-46b2-8e81-66257f0ba570.png)

> Code scanning
>
> ImplementedReturnTypeMismatch
>
> Error
> The inherited return type 'array<int, string>' for OCP\Comments\IComment::getReactions is different to the implemented return type for OC\Comments\Comment::getreactions 'array<string, int>'

2022-01-03 12:13 UTC, nickvergessen commented on lib/private/Comments/Comment.php
> +	public function setReactions(?array $reactions): IComment {
> Code scanning
>
> ImplementedParamTypeMismatch
>
> Error
> Argument 1 of OC\Comments\Comment::setReactions has wrong type 'array<string, int>|null', expecting 'array<int, string>|null' as defined by OCP\Comments\IComment::setReactions

2022-01-03 12:14 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
Argument 1 of OCP\DB\QueryBuilder\IQueryBuilder::from expects string, OCP\DB\QueryBuilder\IQueryFunction provided with a __toString method

2022-01-03 12:36 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
Internally the method will call [QuoteHelper::quoteColumnName](https://github.com/nextcloud/server/blob/master/lib/private/DB/QueryBuilder/QuoteHelper.php#L51) and if the argument is string, will apply the quotes, I used createFunction to don't apply quotes. Without this will return \`(SELECT...)\`

2022-01-03 12:42 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
Maybe, we can use `Literal` on place of `createFunction`

2022-01-03 12:45 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
I copied the pattern `createFunction.*getSql` from other places on this repository that `getSql` was used to create sub-query.

2022-01-04 13:13 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	private function sumReactions(IComment $comment): void {
Feels a bit weird that you insert a reaction/reply and not the comment itself.
I would just take a `$commentId` here and the calling function can either hand in `$comment->getParentId()` or `$comment->getId()`

2022-01-11 08:56 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
```suggestion
			->from((string) $jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
```

2022-01-11 15:32 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->from($jsonQuery->createFunction('(' . $totalQuery->getSQL() . ')'), 'json');
Isn't possible pass subselect as string to method `from` because he will interpret as a table name and will put table prefix on query.
I fixed making possible the `from` method also accept `IQueryFunction`.

2022-01-12 11:50 UTC, nickvergessen requested changes

2022-01-12 11:50 UTC, nickvergessen commented on core/Migrations/Version24000Date20211222112246.php
> +			$table->addColumn('actor_type', 'string', [
```suggestion
			$table->addColumn('actor_type', Types::STRING, [
```

2022-01-12 11:50 UTC, nickvergessen commented on core/Migrations/Version24000Date20211222112246.php
> +			$table->addColumn('actor_id', 'string', [
```suggestion
			$table->addColumn('actor_id', Types::STRING, [
```

2022-01-12 11:50 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	private function getCommentsOnList(array $objectIds): array {
This is a bit confusing as there is an object_id column on the comments table.

Let's go with this instead:
```suggestion
	private function getCommentsById(array $commentIds): array {
```

2022-01-12 11:50 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	 * Get all comments on list
It's not all, it's all that where found. Either the docs should say that comments might be missing, or it should throw when an id is given which is not in the result set?

2022-01-12 12:02 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	 * Get all comments on list
Not, this is a private method, the commentsIds list will be generated by `retrieveAllReactions` and this method only will be executed if have commentsIds. I will move the condition to execute `getCommentsOnList` to him.

2022-01-12 14:40 UTC, nickvergessen approved these changes

2022-01-13 12:46 UTC, nickvergessen requested changes

2022-01-13 12:46 UTC, nickvergessen commented on tests/lib/Comments/ManagerTest.php
> +		if (\OC::$server->getDatabaseConnection()->getDatabasePlatform() instanceof MySQLPlatform && $params['charset'] !== 'utf8mb4') {
```suggestion
		if (!\OC::$server->getDatabaseConnection()->supports4ByteText()) {
```

2022-01-13 12:46 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			if ($comment->getVerb() === 'reaction') {
You need to check `$this->dbConn->supports4ByteText()` when adding a reaction and basically prevent all reactions when not supported.

2022-01-13 12:50 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			if ($comment->getVerb() === 'reaction') {
true

2022-01-13 15:33 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			throw new NotFoundException('This database do not support reactions');
```suggestion
			throw new NotFoundException('The database does not support reactions');
```

2022-01-14 09:24 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			->groupBy('r.reaction');
Need to order by reactions and limit to ~20 entries, so we don't run into issues with the summary column size

2022-01-14 09:28 UTC, juliushaertl commented on lib/private/Comments/Manager.php
> +			return;
For API consumers it would probably be more obvious if that throws an Exception here (and in other places where the reaction support is checked, but I might be lacking some context.

2022-01-14 09:30 UTC, juliushaertl commented on lib/private/Comments/Manager.php
> +		return $this->dbConn->supports4ByteText();
Do we already expose this somewhere so that clients can determine if a server supports it or would this be handled on the talk side then?

2022-01-14 10:05 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +		return $this->dbConn->supports4ByteText();
Talk will have a capability for it's clients.

2022-01-14 10:10 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->groupBy('r.reaction');
This is a good place to put one `order by` with `DESC`.

The column that store the summary have 4000 chars.
Considering that `{"👈🏾":1},` (emoji+color and only 1 reaction) have 15 bytes, the max possible size will be 265 different types of reactions.

2022-01-14 10:17 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			->groupBy('r.reaction');
Maybe, a good security rule is check the size of reaction char to limit to 8 bytes on `prepareCommentForDatabaseWrite` method because for now is possible use any string to react.

2022-01-14 10:21 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			->groupBy('r.reaction');
> Maybe, a good security rule is check the size of reaction char to limit to 8 bytes on prepareCommentForDatabaseWrite method because for now is possible use any string to react.

From my POV the API provider (e.g. Talk) should take care of this.

> The max possible size will be 265 different types of reactions.

Oh, I had a factor-10 error here. I thought its 20*20 = 4k but it's 400. Okay never the less lets then order and limit to 200 (although anything above 20 items is not a useful summary anymore, but we can take care of that in Talk.

2022-01-14 11:14 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +			return;
Will be a good practice that all clients run the method `supportReactions` to check if reactions is supported.

I don't see problems to throw error here.

`\DomainException` is a good type of error?

2022-01-14 12:17 UTC, juliushaertl commented on lib/private/Comments/Manager.php
> +		return $this->dbConn->supports4ByteText();
Makes sense :+1:

2022-01-14 12:22 UTC, juliushaertl commented on lib/private/Comments/Manager.php
> +			return;
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/PreConditionNotMetException.php#L36 would fit from the name (just not from the code comment it has

2022-01-14 12:29 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +			return;
Or you add a dedicated Exception in https://github.com/nextcloud/server/tree/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Comments (there are 3 already)

2022-01-17 09:52 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +		if ($comment->getVerb() === 'reaction' && strlen($comment->getMessage()) > 8) {
```suggestion
		if ($comment->getVerb() === 'reaction' && mb_strlen($comment->getMessage()) > 8) {
```

2022-01-17 09:54 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	 * @throws PreConditionNotMetException
I can't find it (but the comment might be right and instead we need to check it before trying to save it.

2022-01-17 09:55 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		$orderByClause = ' WITHIN GROUP(ORDER BY ' . $orderBy . ')';
Since this is not working we said we don't do it.
Instead order the result of your subquery

2022-01-17 09:57 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +				'json'
```suggestion
			->orderBy('total', 'DESC')
			->setMaxResults(20);

		$jsonQuery = $this->dbConn->getQueryBuilder();
		$jsonQuery
			->selectAlias(
				$jsonQuery->func()->concat(
					$jsonQuery->expr()->literal('{'),
					$jsonQuery->func()->groupConcat('colonseparatedvalue', ','),
					$jsonQuery->expr()->literal('}')
				),
				'json'
```

2022-01-17 10:20 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +				'json'
If remove this, Oracle will fail because he don't respect the ORDER BY on query.

2022-01-17 10:24 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	 * @throws PreConditionNotMetException
This will throw on internal reaction methods. I used `throwIfNotSupportReactions`.

2022-01-17 10:26 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +				'json'
But the order inside the summary is not too important, consumers of the API can do that again. We just need to make sure that the summary is the most used reactions and that will be the case already as per subquery.
The order on groupConcat does not work everywhere so we shouldn't have it.

2022-01-17 11:07 UTC, nickvergessen approved these changes

2022-01-19 10:31 UTC, nickvergessen commented
> Conflicting files
> lib/composer/composer/autoload_classmap.php
> lib/composer/composer/autoload_static.php

2022-01-20 13:10 UTC, CarlSchwan approved these changes

2022-01-20 17:07 UTC, danxuliu requested changes
The asserts from `testReactionAddAndDelete` are not executed, and there might be a missing call to `throwIfNotSupportReactions()` in `retrieveAllReactionsWithSpecificReaction()`.

The other comments are just things that would be nice to have, but not really needed.

2022-01-20 17:07 UTC, danxuliu commented on tests/lib/Comments/ManagerTest.php
> +	public function providerTestGetReactionComment(): array {
It would be nice to test more cases, like getting a reaction from a specific message when the same reaction is in several messages, or verifying that an exception is thrown if the reaction is not found.

2022-01-20 17:20 UTC, vitormattos commented on core/Migrations/Version24000Date20211222112246.php
> + * Auto-generated migration step: Please modify to your needs!
true!

2022-01-21 09:29 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	public function retrieveAllReactionsWithSpecificReaction(int $parentId, string $reaction): ?array {
Good observation, I will push with `throwIfNotSupportReactions();`

2022-01-21 14:08 UTC, merged