Sort app scripts topologically by its dependencies
nextcloud/server pull request #30385
Opened 2021-12-23 00:15 UTC by mejo-

Implement a proper topological sorting algorithm. Based on the
implementation by https://github.com/marcj/topsort.php

Throws a CircularDependencyException if a circular dependency is
detected.

Fixes: #30278

2021-12-23 10:04 UTC, mejo- commented
Not sure whether we want the CircularDependencyException to be thrown. We also could skip that if we don't consider circular dependencies a problem (in certain cases they can result in broken dependency chains).

2021-12-23 13:32 UTC, mejo- commented
> Not sure whether we want the CircularDependencyException to be thrown. We also could skip that if we don't consider circular dependencies a problem (in certain cases they can result in broken dependency chains).

Thinking about it again, it's not a good idea to fail hard here by throwing an exception and we should just log an error instead. Agreed?

2021-12-23 15:48 UTC, mejo- commented
> Thinking about it again, it's not a good idea to fail hard here by throwing an exception and we should just log an error instead. Agreed?

I removed the CircularDependencyException. Instead, the circular dependency is now merely logged as an error if detected.

2021-12-27 06:45 UTC, skjnldsv approved these changes, later dismissed

2021-12-27 09:13 UTC, ChristophWurst requested changes

2021-12-27 09:13 UTC, ChristophWurst commented on lib/public/Util.php
> +			self::$scriptDeps[$application] = (object)[
:-1: We don't use objects this way. Preferably create your own little POPO with getters/setters and use that as your typed data structure or use an untyped associative array.

2021-12-27 09:13 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
This probably comes down to my personal preferences, but let's try our best to avoid any statics. Static variables and methods should be used as rare as possible. This algorithm could be moved into a sideeffect free helper class that works in a functional way: you pass in an array of scripts and their dependencies and as a result you get the sorted scripts. Then use this functionality in here. The algorithm itself will be 100% unit testable. The ugliness of static APIs can be hidden in here until we find a better way.

In summary: static API to add a script can stay. Internals of the algorithm can be improved.

Your future self, coworkers, static analysis and your IDE will thank you :)

2021-12-27 09:47 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
On another thought: the server and this area is not my direct responsibility. If others are okay with this code then I'll revoke my remarks :v:

2021-12-27 10:49 UTC, mejo- commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
Mh, I'm happy to implement your suggestions. But not sure whether I get the picture. I thought that all functions in Util.php were static for performance reasons. You suggest to outsource the whole topologicial sorting into a separated class - but its functions would need to be static as well in order to use them in the static function `getScripts()`, no?

2021-12-27 10:56 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
You can take the registered scripts from the static variable, create an instance of the algorithm class, pipe the data through it and return the result.

2021-12-27 11:08 UTC, mejo- commented on lib/public/Util.php
> +			self::$scriptDeps[$application] = (object)[
Agreed. You mean like this?: https://github.com/nextcloud/server/pull/30385/commits/9ff203cceeabd41efbd8f6b21adb383ea003877b

2021-12-27 11:32 UTC, ChristophWurst commented on lib/public/Util.php
> +			self::$scriptDeps[$application] = (object)[
Yes :)

2021-12-27 12:18 UTC, mejo- commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
Did this now: https://github.com/nextcloud/server/pull/30385/commits/0b5adc805a61732ba49a3aff74c4ac4c53a5d22e Is that how you meant it?

2021-12-27 12:18 UTC, mejo- commented on lib/public/Util.php
> +			self::$scriptDeps[$application] = (object)[
Yay :blush:

2021-12-28 15:28 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
Looks good! Move the inputs from the constructor args to the method, the `sortedScriptDeps` to a local variable of `sort` and it's perfect :)

You get bonus points if you inject a `LoggerInterface` via the constructor and use that instead of ``\OCP\Util::writeLog`` :wink:

2021-12-28 18:14 UTC, mejo- commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
> Looks good! Move the inputs from the constructor args to the method, the `sortedScriptDeps` to a local variable of `sort` and it's perfect :)

Thanks @ChristophWurst :blush:

Done the first now in https://github.com/nextcloud/server/pull/30385/commits/cb763035f63a582dac4372c8195665de883a5617. `$this->sortedScriptDeps` cannot be local to `sort()` as it's updated by `topSortVisit()`, no?
 
> You get bonus points if you inject a `LoggerInterface` via the constructor and use that instead of `\OCP\Util::writeLog` wink

Done in https://github.com/nextcloud/server/pull/30385/commits/86a90fe10930779242c76d48b1ec989f81c4cb82

2021-12-29 07:43 UTC, skjnldsv commented on lib/private/AppScriptSort.php
> +		$this->logger = \OC::$server->get(LoggerInterface::class);
Not possible via DI ?

2021-12-29 07:44 UTC, skjnldsv approved these changes
This took a crazy turn! Code looks good, tests too! :rocket: 
Awesome work!

2021-12-29 07:49 UTC, juliushaertl approved these changes

2021-12-29 07:50 UTC, juliushaertl commented
Psalm failure unrelated

2021-12-29 08:42 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
You could pass it through `topSortVisit` by reference. Same for `scriptDeps`.

2021-12-29 12:08 UTC, mejo- commented on lib/private/AppScriptSort.php
> +		$this->logger = \OC::$server->get(LoggerInterface::class);
I wouldn't know how - at least not if used by static class/function `Util::getScripts()`. Or maybe there's a way and I simply don't know about it? :thinking:

2021-12-29 12:09 UTC, mejo- commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
What would be the advantage of passing `sortedScriptDeps` on and on through all iterations of `topSortVisit()` over making it a global variable to the class?

2021-12-29 12:57 UTC, ChristophWurst commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
It will be free of side effects

2021-12-29 12:58 UTC, ChristophWurst commented on lib/private/AppScriptSort.php
> +		$this->logger = \OC::$server->get(LoggerInterface::class);
add it as regular constructor arg and in Util you use `\OC::$server->get(AppScriptSort::class)` instead of `new AppScriptSort()`. DI will resolve the argument and build the sort algorithm instance for you.

2021-12-29 13:37 UTC, mejo- commented on lib/private/AppScriptSort.php
> +		$this->logger = \OC::$server->get(LoggerInterface::class);
Uh nice, thanks for the explanation :heart_eyes: Implemented now in b770347537b8a516fed855f04f32485d1fe6cda8. It also has the advantage that we can check for `$logger->error()` being called in the unit test, which allows to test the circular dependency detection.

2021-12-29 13:38 UTC, mejo- commented on lib/public/Util.php
> +	private static function topSortVisit(object $app, array &$parents = null): void {
I see. Not sure whether I fully get why this is relevant here, but implemented as you requested nevertheless :wink: See 4a94d0109641a66e52d6aad5856391cd8cec2594

2021-12-29 15:35 UTC, ChristophWurst approved these changes
:+1: :shipit:

2021-12-29 15:38 UTC, mejo- commented
> This took a crazy turn!

Soooo true :see_no_evil: :zany_face: 

I wouldn't have expected this to become such a ride. Thanks a lot to @ChristophWurst and @skjnldsv for guiding me!

2021-12-29 16:20 UTC, mejo- commented
Seems like I'm not allowed to merge - maybe due to the (unrelated) psalm test failures? :thinking: Could someone with super powers merge? :grimacing:

2021-12-29 16:23 UTC, merged

2022-01-06 13:48 UTC, CarlSchwan commented on lib/public/Util.php
> +use OC\AppScriptDependency;
Unfortunately, this causes an psalm warning, since now OCP depends on OC. This wasn't found earlier since psalm was broken but it appear on https://github.com/nextcloud/server/pull/30508

I'm not sure if we can ignore this issue and just add it to the baseline or if we should fix it

2022-01-10 10:13 UTC, juliushaertl commented on lib/public/Util.php
> +use OC\AppScriptDependency;
Fine to add to the baseline from my perspective as it is only used in the method implementation and not exposed in any kinds.