Add group_concat aggregator function
nextcloud/server pull request #30393
Opened 2021-12-23 12:37 UTC by vitormattos

Returns a string which is the concatenation of all non-NULL values of _expression_

You can read more about different implementations on:
[MySQL](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat), [SQLite](https://sqlite.org/lang_aggfunc.html#group_concat), [Oracle](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LISTAGG.html), [PostgreSQL](https://www.postgresql.org/docs/current/functions-aggregate.html) and PostgreSQL [aggregate expression](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES) usage.

2021-12-27 15:51 UTC, ChristophWurst reviewed
I'm not familiar with this but if all our databases support this then I'm fine with adding support for it :+1:

Code looks good. Didn't do any functional tests.

2021-12-27 15:51 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat('collumn') -- with comma as separator (default separator)
```suggestion
	 * groupCouncat('column') -- with comma as separator (default separator)
```

2021-12-27 15:51 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat('collumn', ';') -- with different separator
```suggestion
	 * groupCouncat('column', ';') -- with different separator
```

2021-12-27 15:51 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat(new Literal('DISTINCT collumn'), null) -- without separator
`Literal` is not part of our public API, is it? Remove it from the examples.

2021-12-28 14:19 UTC, vitormattos commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat(new Literal('DISTINCT collumn'), null) -- without separator
This sounds a bad smell but is necessary to maintain compatible with the pattern of implementation of other abstractions on FunctionBuilder class.

If I use $qb->expr()->literal('DISTINCT column') will generate `'DISTINCT column'` with \` or \" because all functions on FunctionBuilder have a condition to pass the argument to `quoteColumnName` function if the argument isn't a object.

I put the example to show how use DISTINCT operator.

2021-12-29 08:52 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat(new Literal('DISTINCT collumn'), null) -- without separator
I think I see the problem but this still means you document a use case that is not usable for apps. `Literal` is an internal class. Apps must not use it.

2021-12-29 13:02 UTC, vitormattos commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat(new Literal('DISTINCT collumn'), null) -- without separator
done.

2021-12-29 13:32 UTC, ChristophWurst approved these changes

2022-01-03 10:17 UTC, come-nc requested changes

2022-01-03 10:17 UTC, come-nc commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat('column', ';') -- with different separator
```suggestion
	 * groupConcat('column') -- with comma as separator (default separator)
	 *
	 * groupConcat('column', ';') -- with different separator
```

2022-01-03 10:48 UTC, vitormattos commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * groupCouncat('column', ';') -- with different separator
Thanks!

2022-01-03 13:17 UTC, come-nc commented
Does this needs some kind of tests?

2022-01-03 15:08 UTC, come-nc commented
The added test is failing.

2022-01-03 16:15 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . "$separator)");
```suggestion
		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . ", $separator)");
```

Will add a real unit test with real data

2022-01-03 16:18 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . "$separator)");
Since order is not supported here, should we drop it from the API?

2022-01-03 16:21 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . "$separator)");
Order isn't mandatory. This function works fine without order on SQLite

2022-01-03 16:24 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LISTAGG(' . $this->helper->quoteColumnName($expr) . ", '$separator')$orderByClause");
Once the orderBy is inside the function brackets and once outside?
Doesn't look correct to me.

2022-01-03 16:26 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LISTAGG(' . $this->helper->quoteColumnName($expr) . ", '$separator')$orderByClause");
Yes, this broken on tests. I will push the fix.

2022-01-03 16:29 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . "$separator)");
I saw now that the CI don't run tests using SQLite. i fixed the comma and did a `push -f`

2022-01-03 16:34 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
> +		return new QueryFunction('string_agg(' . $this->helper->quoteColumnName($expr) . ", '$separator'$orderByClause)");
I'll reproduce the suggested scenario locally and return here with response.

2022-01-03 17:49 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LISTAGG(' . $this->helper->quoteColumnName($expr) . ", '$separator')$orderByClause");
will break when seperator is `'`
Why not use `$this->connection->quote()` like in the base method?

2022-01-03 17:52 UTC, nickvergessen requested changes

2022-01-03 17:52 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
> +		return new QueryFunction('string_agg(' . $this->helper->quoteColumnName($expr) . ", '$separator')");
also here, `$this->connection->quote()` ?

2022-01-03 17:52 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +use Doctrine\DBAL\Exception;
Found violation(s) of type: no_unused_imports

2022-01-03 17:52 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		$separator = $this->helper->quoteColumnName($separator);
Should this be ...?
```suggestion
		$separator = $this->connection->quote($separator);
```

2022-01-03 18:20 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		$separator = $this->helper->quoteColumnName($separator);
true

2022-01-03 18:27 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/SqliteFunctionBuilder.php
> +		return new QueryFunction('GROUP_CONCAT(' . $this->helper->quoteColumnName($expr) . "$separator)");
order removed.

2022-01-03 18:29 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LISTAGG(' . $this->helper->quoteColumnName($expr) . ", '$separator')$orderByClause");
On Oracle is mandatory use the `WITHIN GROUP` after `LISTAGG`
![image](https://user-images.githubusercontent.com/1079143/147965999-9c081db9-ac98-4624-9a7b-77eca311354b.png)

2022-01-04 00:37 UTC, vitormattos commented on lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
> +		return new QueryFunction('string_agg(' . $this->helper->quoteColumnName($expr) . ", '$separator'$orderByClause)");
I reproduced and fixed using cast:

```sql
CREATE TABLE test (
	counter int NULL
);

INSERT INTO test VALUES (1), (2), (3)

SELECT STRING_AGG(cast(counter as varchar), ',') FROM test
```

2022-01-04 16:19 UTC, nickvergessen approved these changes

2022-01-04 16:24 UTC, ChristophWurst approved these changes

2022-01-04 16:34 UTC, merged