Make sure to get file model in template picker
nextcloud/server pull request #30440
Opened 2021-12-29 14:12 UTC by eneiluj

If the template picker creates a file which is not immediately rendered in the file list, it fails to get the FileInfoModel (which is then passed to the default file action). This does not break the Text app because its file action does not use the FileInfoModel. It does break the OnlyOffice app (and maybe others) file creation from a template.

The template picker fails to get the model because `FileList::getModelForFile()` relies on the DOM and the freshly created file is sometimes not added/rendered.

The created file item is not rendered if the target position is out of what's currently visible/loaded.

Fortunately, `FileList::addAndFetchFileInfo()` fetches the file metadata and we can use it to generate the file model in the template picker.
I switched from `await` to `.then()` because I couldn't find another way to get the promise result when multiple parameters are passed to `resolve()`.

We have to be careful when backporting this. So far, I saw that a few changes are necessary to make it work in stable22.

2021-12-29 14:37 UTC, artonge commented on apps/files/src/views/TemplatePicker.vue
> +				fileList?.addAndFetchFileInfo(this.name).then((status, data) => {
Not pretty, but might simply the code:

```suggestion
                // Use an intermediary `then` to bundle 'status' and 'data' in one destructurable object.
				const { status, data } = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => ({status, data}))
```

2021-12-29 14:51 UTC, juliushaertl approved these changes
Could not trigger it myself but change seems good :+1:

2021-12-29 16:43 UTC, eneiluj commented on apps/files/src/views/TemplatePicker.vue
> +				fileList?.addAndFetchFileInfo(this.name).then((status, data) => {
@artonge That's exactly what I was looking for. Thank you dear JS ninja :grin:.
Rebased on master. Now uses this shorter and (almost) elegant solution.

2021-12-30 07:13 UTC, skjnldsv commented
Lint failures

2021-12-30 09:14 UTC, artonge requested changes

2021-12-30 09:14 UTC, artonge commented on apps/files/src/views/TemplatePicker.vue
> +				const { status, data } = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => ({status, data}))
Should fix linting issues:

```suggestion
				const { status, data } = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => ({ data }))
```

2021-12-30 09:41 UTC, eneiluj commented on apps/files/src/views/TemplatePicker.vue
> +				const { status, data } = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => ({status, data}))
We can even go to:
``` javascript
const data = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => data)
```

Rebased and done.

2021-12-30 09:50 UTC, artonge commented on apps/files/src/views/TemplatePicker.vue
> +				const { status, data } = await fileList?.addAndFetchFileInfo(this.name).then((status, data) => ({status, data}))
Indeed :laughing:

2021-12-30 09:52 UTC, artonge approved these changes

2021-12-30 09:57 UTC, eneiluj commented
This can be backported in 21, 22 and 23 IMO.

2021-12-30 10:00 UTC, artonge commented
/compile amend /

2021-12-30 10:00 UTC, artonge commented
/backport to 23

2021-12-30 10:00 UTC, artonge commented
/backport to 22

2021-12-30 10:00 UTC, artonge commented
/backport to 21

2021-12-30 13:13 UTC, artonge commented
CI failure is unrelated. Merge when you want @eneiluj :)

2021-12-30 13:54 UTC, merged

2021-12-30 13:59 UTC, acsfer commented
/backport to stable23

2021-12-30 13:59 UTC, acsfer commented
/backport to stable22

2021-12-30 13:59 UTC, acsfer commented
/backport to stable21