[WIP] Calendar events email reminders
nextcloud/server pull request #3044
Opened 2017-01-12 13:35 UTC by tcitworld

I've started that a few weeks ago so please don't look at it right now.

2017-01-12 15:23 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		if (!is_null($this->dispatcher)) {
can not be null, since it's not nullable in the constructor?

2017-01-12 15:24 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		if (!is_null($this->dispatcher)) {
same here

2017-01-12 15:24 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		if (!is_null($this->dispatcher)) {
and here

2017-01-12 15:31 UTC, nickvergessen submitted a review, later dismissed
What I dislike about this is all the duplication of notifications we will get with that.
The plan is to have notifications integrated into the mobile and desktop clients as well. So when you have an event coming up, you will have 4 notifications (laptop nextcloud, laptop calendar, phone nextcloud, phone calendar).

That is why I always stayed away from this notifications. Might make sense to have them in the web ui, but I think most people have at least one client running which already gives the notifications....

2017-01-12 15:31 UTC, nickvergessen commented on apps/dav/appinfo/app.php
> +		'id' => 1,
id is `'dav_reminders'`

2017-01-12 15:31 UTC, nickvergessen commented on apps/dav/appinfo/app.php
> +		'name' => 'dav'
Should be translated and user friendly. In this case maybe "Calendar reminders"

2017-01-12 15:32 UTC, nickvergessen commented on apps/dav/appinfo/app.php
> +		'id' => 1,
And also use that in the notifier itself as identifier.

2017-02-26 15:55 UTC, georgehrke commented
> That is why I always stayed away from this notifications. Might make sense to have them in the web ui, but I think most people have at least one client running which already gives the notifications....

@nickvergessen 
The calendar standard defines different kinds of alarms. [Audio, display and email.](https://tools.ietf.org/html/rfc5545#page-73).
E-Mail alarms should obviously only be triggered when the user actually asked for an email :)

2017-04-03 19:18 UTC, rullzer commented
What is the status here? Can this be reviewed soon?

2017-06-02 08:45 UTC, georgehrke commented
@tcitworld What's your schedule for this feature? :)

2017-06-30 13:05 UTC, tcitworld commented
Will change this to work on the backend already used for Activities made by @nickvergessen

2017-07-13 09:18 UTC, tcitworld commented
Should emails reminders be sent to all `ATTENDEES` or just nextcloud users ?

2017-07-13 15:00 UTC, georgehrke commented
> Should emails reminders be sent to all ATTENDEES or just nextcloud users ?

Did you check any  RFC for an answer on that? :)

2017-07-17 08:26 UTC, tcitworld commented
When the action is "EMAIL", the alarm MUST include a "DESCRIPTION"
      property, which contains the text to be used as the message body,
      a "SUMMARY" property, which contains the text to be used as the
      message subject, and one or more "ATTENDEE" properties, which
      contain the email address of attendees to receive the message.  It
      can also include one or more "ATTACH" properties, which are
      intended to be sent as message attachments.  When the alarm is
      triggered, the email message is sent.

      [...]

      In an EMAIL alarm, the intended alarm effect is for an email
      message to be composed and delivered to all the addresses
      specified by the "ATTENDEE" properties in the "VALARM" calendar
      component.  The "DESCRIPTION" property of the "VALARM" calendar
      component MUST be used as the body text of the message, and the
      "SUMMARY" property MUST be used as the subject text.  Any "ATTACH"
      properties in the "VALARM" calendar component SHOULD be sent as
      attachments to the message.

@georgehrke @jancborchardt  Today, when you set an alarm, you are not automatically added as an attendee, but I guess you would like to get the notifications anyway. 
What about people with whom the calendar is shared (a group, for instance) ? Should they automatically get the notifications too while not manually added to `ATTENDEES` (they can be a lot) ?

Maybe an issue in calendar repo to automatically add yourself as an attendee ? Or another one to add a group as attendee ?

2017-07-17 08:27 UTC, tcitworld commented
Also, if someone plz have a look why my notifications aren't displayed. :'(

2017-07-17 10:04 UTC, jancborchardt commented
Sharing an event with someone should mean they are invited to add themselves as attending. But not set them as attending automatically.

2017-07-17 11:42 UTC, tcitworld commented
> add themselves as attending

Would like to discuss more on that on the calendar app repo, maybe a easier way to add yourself as an attendee ? Would also be great if someone could tell me how Apple's iCal handle this for instance.

2017-10-13 10:17 UTC, pixelipo commented
Hi @tcitworld any status on this? It's a killer feature for me and if there's a bounty, I'm willing to pitch in.

Also if you need some dev/design help, let me know.

2017-10-13 10:22 UTC, tcitworld commented
[No bounty](https://www.bountysource.com/issues/43294685-implement-calendar-notifications-by-email-sent-from-the-server) yet. Feel free to have a look and add answers to my questions.

2017-11-11 16:29 UTC, georgehrke commented
Not sure if there is a little confusion here:

We are talking about different kinds of attendees here.
There can be attendees in VEvents, the one you see in the event editor, and there are inside VAlarm blocks. The latter one are for sending out e-mail addresses. You can be an attendee inside the VAlarm block without being an actual attendee of the event.

> What about people with whom the calendar is shared (a group, for instance) ?

See my comment in https://github.com/nextcloud/server/issues/679#issuecomment-277437446

> Should they automatically get the notifications too while not manually added to ATTENDEES (they can be a lot) ?

They should be able to manage their own VAlarm block for each event and hence be able to add themselves for reminders. Not sure about the default here.
If u are an actual attendee of the event, you should get a notification too.

> Maybe an issue in calendar repo to automatically add yourself as an attendee ?

Yep, please open one :)

> Or another one to add a group as attendee ?

Maybe. It's important to provide an opt-out mechanism here imho.

2017-11-14 13:39 UTC, MorrisJobke commented
@nickvergessen @tcitworld @georgehrke It doesn't look like something for 13, right?

2017-11-14 13:39 UTC, georgehrke commented
No, we will have to postpone it

2017-11-15 02:54 UTC, Sebastian-Pohl commented
Hello everybody, is the e-mail reminder in Nextcloud calendar app not working at all yet? If so, I do not have to check if me e-mail settings are somehow wrong. Same for ownCloud: Has it ever worked or is it a feature request here, too, to be implemented in the near future? Thank you, Sebastian

2017-11-19 09:02 UTC, FredMa01 commented
Hi 
same question than Sebastian about remind and new evenements notifications mails. 
The android app Etar propose remind mail but it doesnt work...
Thanks
Fred

2017-11-19 10:58 UTC, georgehrke commented
> is the e-mail reminder in Nextcloud calendar app not working at all yet? 

Nope, it's not implemented yet. That's what this pull request is about.

>  Same for ownCloud: Has it ever worked or is it a feature request here, too, to be implemented in the near future?

Never worked, not aware of it being implemented at the moment, don't know about feature requests at ownCloud

2018-01-22 11:12 UTC, ClepToManix commented
Hello, i have setuped the mail notify in my nc and this is still workling, but ive found a possibiltiy in calendar app to remind me via e-mail. If i checked this box my nextcloud still saying, that
E-mail reminders have not yet been implemented in the CalDAV server. What i have to do? Found nothing in documentation -.-

2018-01-27 17:49 UTC, georgehrke commented
@tcitworld Can you estimate how much work is left here? :) 

What do you think about putting this up as a potential GSOC project?

2018-04-27 10:26 UTC, msharp1 commented
Hi, what's the status of this PR ? That's a must-have (and essential) feature to compete with Google...

2018-05-04 14:17 UTC, Nono-m0le commented
Hi Guys,
I'm also very interested to have the feature (and the github notification).
IMO, I don't want to rely on any apps but want to get only mail notification.
still IMO, we should be able to email existing cloud user and non-existing/external email as well.

2018-06-29 07:47 UTC, MorrisJobke commented
Nothing for 14 it seems -> moved to 15

2018-07-11 13:49 UTC, ulph0 commented
hi, left a feature request on nextcloud HP could you please tell me if @tcitworld or anyone else is still working on this and if not, tell me a starting point if i would like to do this for nextcloud?

2018-08-23 17:41 UTC, tcitworld commented
> Also, I think it is important to have another type of notification, that is not a EMAIL, DISPLAY or AUDIO, but a HOOK to be used by another app.

Could be done through https://tools.ietf.org/id/draft-daboo-valarm-extensions-04.html#URI-ACTION

2018-11-07 14:42 UTC, MorrisJobke commented
I guess we need to move this to 16 😢

2018-12-04 08:22 UTC, StCyr commented
Hello, 

are there still things for which we can help in this matter?

I'm running NC 14.

Br,

Cyrille

2019-01-28 16:48 UTC, georgehrke commented
> @tcitworld tcitworld force-pushed the dav-email-reminders  branch from a34c46f to c9b4ec0 14 days ago

Any update on this? :)

2019-01-28 17:40 UTC, tcitworld commented
> Any update on this? :)

Advancing one step after another, you're free to have a look. ;)

2019-02-24 16:34 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php
> +    }
I would prefer an `addProvider()` method but I'm not sure how to instantiate things properly and where to do that.

2019-02-24 16:35 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		$this->setLangForUser($user);
This is dirty.

2019-02-25 13:42 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php
> +    }
Also registration of a provider should not require an instance, but the class name only.

2019-02-25 13:44 UTC, nickvergessen submitted a review, later dismissed

2019-02-25 13:44 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		var_dump('Sending email');
:see_no_evil:

2019-02-25 13:44 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		$this->setLangForUser($user);
Yeah, this looks wrong. Instead just pass in the language similar to notifications:
https://github.com/nextcloud/notifications/blob/master/lib/Controller/EndpointController.php#L92

2019-02-25 14:06 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php
> +    }
How can I instantiate providers then ? Through `SimpleContainer` in https://github.com/nextcloud/server/blob/master/apps/dav/lib/AppInfo/Application.php ?

2019-02-25 14:06 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +		var_dump('Sending email');
WIP's in the title. :)

2019-02-25 14:08 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php
> +    }
https://github.com/nextcloud/server/blob/e24d5552814440f5c01ea3769f88ac2e0fcdb348/lib/private/Activity/Manager.php#L178-L196

2019-02-25 15:05 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php
> +    }
Thanks ! :+1:

2019-03-16 18:05 UTC, tcitworld commented
Okay, this seems ready.

What it looks like:
## Email
![Capture d’écran du 2019-03-16 18-37-02](https://user-images.githubusercontent.com/2197836/54479505-b33ece80-481d-11e9-968d-83ca27179367.png)

## Notifications
![Capture d’écran du 2019-03-16 18-59-26](https://user-images.githubusercontent.com/2197836/54479509-b6d25580-481d-11e9-8b7d-6a1a6a0664e8.png)
(Browser notifications come as well)

2019-03-18 22:30 UTC, jospoortvliet commented
Exciting ;-)

2019-03-27 19:03 UTC, rullzer commented
So CI is green. Lets get this in early once branched off

2019-04-16 15:27 UTC, jospoortvliet commented
We're branched off, can I ping ping ping everyone ;-)
Time to merge all features :tada:

2019-05-15 07:28 UTC, georgehrke commented
note to myself: 
Checklist: 
- [ ] what happens if i set up a reminder in the past
- [ ] test recurring events
- [ ] test recurrence exceptions
- [ ] are future reminders properly deleted when deleting an event
- [ ] ...

2019-05-15 07:50 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
> +	public const NOTIFICATION_TYPE = 'DISPLAY';
Maybe it would be good to handle both `DISPLAY` and `AUDIO` with the PushProvider for now.

At least, until we have proper audio notifications. Having a display instead of an audio notification is still better than not receiving the notification at all.

2019-05-15 09:06 UTC, georgehrke commented
>  test recurring events

Recurring events are not supported at the moment. I would be fine with merging this without recurring events support for now, but I'm wondering whether we should already adapt the database structure to support it.

2019-05-15 13:15 UTC, georgehrke commented
On MySQL i get the following error message: "An exception occurred while executing 'INSERT INTO `oc_calendar_reminders` (`uid`, `calendarid`, `objecturi`, `type`, `notificationdate`, `eventstartdate`) VALUES(?, ?, ?, ?, ?, ?)' with params [\"admin\", \"1\", \"5b673f82-9610-8d49-954a-7dab14d22caf.ics\", \"DISPLAY\", 1559828700, 1559829600]:\n\nSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1559828700' for column 'notificationdate' at row 1"

2019-05-16 08:23 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/AbstractNotificationProvider.php
> +    public function send(VCalendar $vcalendar, string $calendarDisplayName, IUser $user): void {}
Maybe turn this into an abstract function to force subclasses to properly implement it?

2019-06-14 07:51 UTC, georgehrke commented
ping @tcitworld :)

2019-07-02 11:08 UTC, wiswedel commented
anyone motivated to move forward here?

2019-07-02 11:09 UTC, georgehrke commented
@wiswedel I will for Nc 18. But right now it's time to polish the 17 release.

2019-08-07 11:11 UTC, georgehrke commented
Todo for myself:
- [ ] Support for `RELATED=END` is missing.

2019-08-07 13:40 UTC, tcitworld commented
> Support for RELATED=END is missing.

Odd, `VAlarm::getEffectiveTriggerTime()` should handle it.

2019-08-07 14:00 UTC, georgehrke commented
Let me double check then, sorry. I only checked the code.

2019-08-08 12:28 UTC, georgehrke commented
- [ ] This also needs a background job to fill oc_dav_reminders for existing entries

2019-08-11 16:29 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +//			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
Todo: remove this comment before merging. 
it's only useful for testing to always trigger some reminders.

2019-08-12 11:59 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
@rullzer Do you know if this could cause any issue with certain mail servers? 

(Instead of sending out one email per attendee, we are only sending one email per language)

2019-08-12 17:34 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
Any reason to do this?
I guess the 99% of events do not ahve more than 10 attendees right?

2019-08-12 18:07 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
An individual event probably not, but on a big instance it will not be uncommon to send out reminders for dozens of events at  a time, turning 10 attendees per event into hundreds of emails.

2019-08-12 18:14 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
I'm fine with changing it, just thought it would be nice to take off load of the background-job and let the mailserver take care of sending out the individual emails.

2019-08-12 18:21 UTC, hockdudu requested changes

2019-08-12 18:21 UTC, hockdudu commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +			if ($this->hasL10NForLang($lang)) {
Shouldn't this check be negated?

```suggestion
			if (!$this->hasL10NForLang($lang)) {
```

2019-08-12 18:22 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +			if ($this->hasL10NForLang($lang)) {
Indeed, let me fix that.

2019-08-12 19:18 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
As far as I know most mailservers will accept this. But it might look weird.
You get stuff in you mail server like 'undisclosed-recipient' in the to field. Which looks silly IMO.

2019-08-12 19:20 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
ok, let me change it tomorrow

2019-08-13 07:53 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				->setBcc($emailAddresses);
Also it means the email can't be personalized for each attendee (even though we don't use this right now), so yeah, better send an email for each attendee.

2019-08-13 09:28 UTC, fancycode commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				try {
While you're at it: it would be great if you could dispatch an event here containing the message. This can be subscribed by other apps so they can modify / extend the message before it is sent out.

2019-08-13 09:31 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +				try {
Can we do that in a  separate PR please? We are planning to release a beta of 17 later this week, so this has to get in if we want it in 17.

2019-08-13 12:59 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php
> +use DateTimeImmutable;
`\DateTime` and `\DateTimeImmutable`

2019-08-13 18:22 UTC, rullzer requested changes
In general I'm all for merging this. I'm sure there are things we didn't think of yet. But lets get this in before it gets to huge.

I just wonder about the migration change.

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php
> +use OC\BackgroundJob\QueuedJob;
please use the one in OCP

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +class Backend {
I'm fine with this for now. But it might make sense to try to eventually convert this to the Entity stuff of the appframework.

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/Notifier.php
> +			$title = $this->l10n->t('%s (%s ago)', [$title, $diffLabel]);
So i guess we either have to give good hints to the translators. Or we have to somehow fix this later to have proper translations. Because I can already see languages where this looks weird.

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +	public const REMINDER_TYPE_EMAIL = 'EMAIL';
If we have the types here. Shouldn't we just reference them from the providers themselfs?

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			case '\OCA\DAV\CalDAV\CalDavBackend::createCalendarObject':
Ah magic string ;)
But yeah lets do it for now.

2019-08-13 18:22 UTC, rullzer commented on apps/dav/lib/Migration/Version1004Date20170825134824.php
> +
uhm... why this? Then old intsallations won't be the the same as new ones...
If you want to change the attributes it should be handled in a migration

2019-08-13 18:57 UTC, georgehrke commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +	public const REMINDER_TYPE_EMAIL = 'EMAIL';
as in have a method `getSupportedTypes`?

2019-08-13 18:59 UTC, georgehrke commented on apps/dav/lib/Migration/Version1004Date20170825134824.php
> +
No clue what i did here, but not on purpose. Let me revert this.

2019-08-15 13:45 UTC, rullzer commented
Depends on https://github.com/nextcloud/3rdparty/pull/321

2019-08-15 13:51 UTC, rullzer approved these changes
Looks good.
Lets see if phan is happy and get it in.

2019-08-15 19:21 UTC, merged

2019-09-10 07:29 UTC, remmesa commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +	public const REMINDER_TYPE_EMAIL = 'EMAIL';
if you configure email reminder alert to calendar on nextcloud already please send step to configure take me

2019-09-10 07:34 UTC, remmesa commented
> Also, if someone plz have a look why my notifications aren't displayed. :'(

2019-09-10 07:35 UTC, remmesa commented
cloud to give me your ducement to configure email reminder alert to calendar on nextcloud

2019-12-04 15:57 UTC, Mic92 commented
Is this part of 17.0.1?