Make sure different webroots use different cached paths
nextcloud/server pull request #3046
Opened 2017-01-12 14:00 UTC by nickvergessen

Fix #2190

I guess we can do this.

@rullzer @LukasReschke

2017-01-12 14:30 UTC, LukasReschke commented
I'd prefer mixing domain and URL into https://github.com/nextcloud/server/blob/00c3f807db59f69cac37429f1b4be424720371e3/lib/private/Server.php#L371-L392

2017-01-12 14:58 UTC, nickvergessen commented
Ah Server root is already in there, sounds a lot easier. The question is whether that is done late enough?

2017-01-26 04:06 UTC, MorrisJobke requested changes

2017-01-26 04:06 UTC, MorrisJobke commented on lib/private/Server.php
> +				$prefix = md5($instanceId . '-' . $version . '-' . $path . '-' . \OC::$WEBROOT);
`$WEBROOT` only contains the path not the domain: `/server` this is the webroot of my server.

2017-01-26 09:06 UTC, nickvergessen commented on lib/private/Server.php
> +				$prefix = md5($instanceId . '-' . $version . '-' . $path . '-' . \OC::$WEBROOT);
That is actually what we are trying to fix, not domain awareness, but subpath awareness. Domains are not cached in imagePath(), because the method only returns relative paths ;)

2017-01-26 21:36 UTC, MorrisJobke approved these changes

2017-01-27 08:19 UTC, nickvergessen commented
@LukasReschke I changed it to the way you wanted, can I get a review now?

2017-01-27 09:14 UTC, LukasReschke approved these changes

2017-01-27 09:14 UTC, merged