Handle LocalServerException when scanning external shares
nextcloud/server pull request #30468
Opened 2022-01-03 08:19 UTC by CarlSchwan

When remoteIsOwnCloud trows LocalServerException, the storage is
unavailable and instead of crashing the scanner, ignore the specific
storage.

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2022-01-03 08:19 UTC, CarlSchwan commented
/backport to stable23

2022-01-03 08:19 UTC, CarlSchwan commented
/backport to stable22

2022-01-03 08:19 UTC, CarlSchwan commented
/backport to stable21

2022-01-05 10:29 UTC, szaimen commented on apps/files_sharing/lib/External/Scanner.php
> +				return parent::scan($path, $recursive, $recursive, $lock);
```suggestion
				return parent::scan($path, $recursive, $reuse, $lock);
```

2022-01-05 10:30 UTC, szaimen commented on apps/files_sharing/lib/External/Scanner.php
> +				return parent::scan($path, $recursive, $recursive, $lock);
See https://github.com/nextcloud/server/pull/30492

2022-01-05 12:58 UTC, artonge requested changes

2022-01-05 12:58 UTC, artonge commented on apps/files_sharing/lib/External/Scanner.php
> +			return;
Shouldn't the exception be logged?

2022-01-05 17:24 UTC, CarlSchwan commented on apps/files_sharing/lib/External/Scanner.php
> +			return;
Done, unfortunately, LoggerInterface can't have dependency injection since it's created directly and is not a service.

2022-01-05 19:15 UTC, nickvergessen commented on apps/files_sharing/lib/External/Scanner.php
> +				->warning('Trying to scan files inside invalid external storage: ' . $this->storage->getRemote());
getRemote is only the URL of the server. Since this is "LocalServerException", that should be known already. Maybe additionally store the mount point and id, so one can start checking which share is actually the problem?

2022-01-06 16:38 UTC, skjnldsv approved these changes

2022-01-07 09:16 UTC, nickvergessen approved these changes

2022-01-09 17:37 UTC, CarlSchwan commented
Ci failure unrelated

2022-01-09 17:37 UTC, merged