Fix primary key change in user_ldap migration
nextcloud/server pull request #30568
Opened 2022-01-10 11:09 UTC by come-nc

Use a backup table to copy the data, drop table and recreate it with
 correct primary key, then copy the data back and drop the backup table.

Fix https://github.com/nextcloud/server/issues/30539

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-01-10 12:32 UTC, blizzz commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +		if (!$schema->hasTable('twofactor_backup_codes')) {
`twofactor_backup_codes`?

2022-01-10 13:07 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +		if (!$schema->hasTable('twofactor_backup_codes')) {
Bad copy paste, see new version.

2022-01-10 17:34 UTC, blizzz commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +			]);
Otherwise looks good, would test. But state is still developing?

2022-01-10 18:13 UTC, nickvergessen requested changes

2022-01-10 18:13 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
Logic from here onwards looks wild.
I would vote to remove all the logic parts and simply do the double copy/create in any case to make sure you didn't create a loop hole somewhere.

2022-01-10 18:13 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +		$table = $schema->createTable('ldap_group_mapping');
You can not create a table again in the same migration where you drop it, as the dropping happens only after the migration and so the new tbale will be gone.

2022-01-11 08:05 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
I want to avoid having a double copy for new installations that do not need the migration.

2022-01-11 08:05 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +		$table = $schema->createTable('ldap_group_mapping');
I was afraid of this, does it mean I need 4 migration classes?

2022-01-11 08:08 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +			]);
If you know of a better way for copy/pasting from table to table I’ll take it, I used https://github.com/nextcloud/spreed/blob/dc518c46a710e13485feb0977b0f1343eea6d2ec/lib/Migration/Version10000Date20201015134000.php#L185 as an example, I am not fluent in Doctrine.
I did not test the migration yet as I was expecting something like https://github.com/nextcloud/server/pull/30568#discussion_r781431812 to come up.

2022-01-11 08:55 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +		$table = $schema->createTable('ldap_group_mapping');
* create backup + copy data
* remove orig
* create orig + copy data
* remove backup

yes.

2022-01-11 08:55 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
well new installs will have no content so it's quick?

2022-01-11 10:22 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
I guess, but it still feels weird to create 3 tables where one is needed in installation process

2022-01-11 10:23 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +		$table = $schema->createTable('ldap_group_mapping');
Ok, will do

2022-01-11 17:55 UTC, blizzz commented on apps/user_ldap/lib/Migration/Version1130Date20220110154718.php
> +	public function __construct(IDBConnection $dbc) {
lacks a use statement

2022-01-11 17:58 UTC, blizzz commented on apps/user_ldap/lib/Migration/Version1130Date20220110154717.php
> +			]);
i have found some ideas how it could go, but nothing that earned my trust. Let's leave it like this instead of opening another construction site.

2022-01-11 17:59 UTC, nickvergessen approved these changes

2022-01-11 17:59 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/GroupMappingMigration.php
> +class GroupMappingMigration extends SimpleMigrationStep {
```suggestion
abstract class GroupMappingMigration extends SimpleMigrationStep {
```

2022-01-11 17:59 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if ($table->getPrimaryKeyColumns() !== ['owncloud_name']) {
Mind to comment which case there could be? From this file it's either none (then it's created) or `'owncloud_name'`

2022-01-12 12:54 UTC, nickvergessen commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
But the installation never does it. It is taking a fast trip to the end and only generates the final result

2022-01-13 09:51 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if ($table->getPrimaryKeyColumns() !== ['owncloud_name']) {
In 23 primary key for ldap_group_mapping was ldap_dn, which is the reason for all this.
It was changed in https://github.com/nextcloud/server/pull/29523/files#diff-305e20bed2077c1acd13cbf1051427e1179e19d0bfa3054635a99a83827e01a3R89-R95

2022-01-13 11:07 UTC, come-nc commented on apps/user_ldap/lib/Migration/Version1130Date20211102154716.php
> +				if (!$table->hasPrimaryKey()) {
I had to switch to always creating the table in the end because of other problems with mysql it was easier this way.

2022-01-13 11:24 UTC, come-nc commented
Ok, I tested the migration and had to refactor a bit, as enlarging the ldap_dn column on ldap_group_mapping was failing because it was a primary key. So now it always goes through the double copy/drop to get the ldap_group_mapping table in the right shape. It worked for my test but I only tested mysql.
I also had to update the autoloader which triggered a lot of small psalm changes, not sure if expected or not.

2022-01-13 12:37 UTC, nickvergessen commented
> Conflicting files
apps/dav/composer/composer/installed.php 

Maybe you can revert the autoloading paart and then only commit the modified files in apps/user_ldap?

2022-01-13 12:40 UTC, nickvergessen approved these changes
LGTM apart from the psalm/composer change

2022-01-13 13:01 UTC, skjnldsv commented
Please rebase so we can merge :)

2022-01-13 13:09 UTC, come-nc commented
Rebased and removed the autoloader update, can someone which understand this stuff do the autoloader update?

2022-01-13 13:24 UTC, nickvergessen commented
```sh
bash build/autoloaderchecker.sh
git add apps/user_ldap/composer/composer/autoload_*
git commit
git restore apps/
```

Done

2022-01-13 13:51 UTC, come-nc commented
/backport to stable22

2022-01-13 13:51 UTC, come-nc commented
/backport to stable20

2022-01-13 15:07 UTC, come-nc commented
Drone failure is unrelated

2022-01-13 16:43 UTC, blizzz commented
With the latest commit, migration run through like a hot knife through butter! :medal_sports: @come-nc

2022-01-13 16:45 UTC, blizzz approved these changes

2022-01-14 08:20 UTC, merged