Fix idn emails not working in shares
nextcloud/server pull request #30600
Opened 2022-01-11 14:45 UTC by CarlSchwan

Fix #30595

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2022-01-11 15:06 UTC, tcitworld requested changes
You can use `OCP\Mail::validateMailAddress` that already has the IDN check.
https://github.com/nextcloud/server/blob/796764aafd318cfeedf6d19af4551e846a40ac94/lib/private/Mail/Mailer.php#L216-L249

2022-01-11 15:07 UTC, PVince81 approved these changes
:+1:

2022-01-11 15:13 UTC, PVince81 commented
if possible for this code path would be good to add unit tests with an IDN address

2022-01-12 13:32 UTC, tcitworld commented on apps/sharebymail/lib/ShareByMailProvider.php
> +			$this->logger->error($e->getMessage(), [
I think this should be the other way around, the message as first argument, and the whole exception as `"exception"` context key, so that it's future proof for the migration to `LoggerInterface`.

2022-01-12 15:11 UTC, tcitworld commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		if ($this->mailer->validateMailAddress($share->getSharedWith())) {
Off-topic, but that `getSharedWith()` should return an array, according to the interface, and therefore not be used as a string here.

2022-01-12 15:12 UTC, tcitworld approved these changes

2022-01-12 15:16 UTC, CarlSchwan commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		if ($this->mailer->validateMailAddress($share->getSharedWith())) {
Did I miss something? Looking at the interfaces `lib/public/Share/IShare.php::getSharedWith` returns a string, it's `lib/public/Share/IManager.php::getSharedWith` that returns an array.

2022-01-12 15:34 UTC, tcitworld commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		if ($this->mailer->validateMailAddress($share->getSharedWith())) {
Correct, I was mistaken.

2022-01-12 16:31 UTC, CarlSchwan commented
I'm looking into the php unit failures, strange that is works locally for me :/

2022-01-12 19:35 UTC, CarlSchwan commented
I found why the tests seemed to work locally and fixed them :)

2022-01-13 08:22 UTC, PVince81 approved these changes
:+1:

2022-01-13 08:24 UTC, merged

2022-01-13 11:14 UTC, CarlSchwan commented
/backport to stable23

2022-01-13 11:14 UTC, CarlSchwan commented
/backport to stable21