Improve recommended apps installation
nextcloud/server pull request #30615
Opened 2022-01-12 03:50 UTC by Pytal

Now with the satisfaction of clicking a button :)

| Before | After |
| ---       | ---     |
| <img src="https://user-images.githubusercontent.com/24800714/149059627-e1314577-3790-4d7f-9a63-5abf77f5a238.png" /> | <img src="https://user-images.githubusercontent.com/24800714/149059964-61abb795-ad04-4b5d-9f06-bcc03d446173.png" /> |

Then installation proceeds as normal
![image](https://user-images.githubusercontent.com/24800714/149059706-93da1cf6-7fbf-4878-8e4e-ca0db6939c1f.png)

2022-01-12 03:50 UTC, Pytal commented
/compile amend /

2022-01-12 03:51 UTC, Pytal commented
/backport to stable23

2022-01-12 03:51 UTC, Pytal commented
/backport to stable22

2022-01-12 03:51 UTC, Pytal commented
/backport to stable21

2022-01-12 10:15 UTC, artonge requested changes

2022-01-12 10:15 UTC, artonge commented on core/src/components/setup/RecommendedApps.vue
> +		},
Can we use async/await and try/catch here ?

2022-01-12 10:17 UTC, artonge commented
I would say having the list of recommended apps before starting the install is nice too. Not sure if we should go on with this change.

2022-01-12 16:34 UTC, PVince81 approved these changes
:+1: code looks fine

optionally see Louis' comment

2022-01-12 19:49 UTC, Pytal commented on core/src/components/setup/RecommendedApps.vue
> +		},
`async`hronized

2022-01-12 19:51 UTC, Pytal commented on core/src/components/setup/RecommendedApps.vue
> +		},
`async`hronized :)

2022-01-12 19:53 UTC, Pytal commented
Now updated to show the recommended apps alongside the install button

2022-01-12 19:53 UTC, Pytal commented
/compile amend /

2022-01-12 20:04 UTC, artonge approved these changes
Code looks code !

2022-01-13 11:45 UTC, szaimen approved these changes
Seems to work 👍

Maybe we could think about removing the checkbox now that you need to press a button to start the installation of the apps either way:
![image](https://user-images.githubusercontent.com/42591237/149324578-a9ac37ff-c0d8-472e-b60e-04f813dcc7ff.png)

Also we could think about renaming the desciption of the button from `Finish installation` to `Continue installation` as this is not the last step if you don't uncheck the `Install recommended apps` checkbox?

2022-01-14 19:51 UTC, Pytal commented
/compile amend /

2022-01-14 19:55 UTC, Pytal commented
Checkbox removed and wording updated, plus updated screenshots

2022-01-14 22:48 UTC, szaimen approved these changes
Works 👍 
(but didn't review the code)

Thanks for adressing my comment :)

2022-01-17 08:15 UTC, skjnldsv approved these changes

2022-01-17 08:16 UTC, merged