Do chuncked job deletion
nextcloud/server pull request #30768
Opened 2022-01-20 09:49 UTC by CarlSchwan

This is helpful in cases where we are deleting tons jobs at the same
time in a gallera cluster. This doesn't happen often but this can create
issues.

Test plan:

1. Use https://github.com/nextcloud/quota_warning/pull/88
2. Change max to 1
3. Enabled/Disable quota_warning app and see jobs getting successfully
   added and removed

2022-01-20 10:08 UTC, nickvergessen approved these changes

2022-01-20 15:13 UTC, nickvergessen commented on lib/private/BackgroundJob/JobList.php
>  		$query->execute();
```suggestion

		// Add galera safe delete chunking if using mysql
		// Stops us hitting wsrep_max_ws_rows when large row counts are deleted
		if ($this->connection->getDatabasePlatform() instanceof MySQLPlatform) {
			// Then use chunked delete
			$max = 100000;

			$query->setMaxResults($max);
			do {
				$deleted = $query->execute();
			} while ($deleted === $max);
		} else {
			// Dont use chunked delete - let the DB handle the large row count natively
			$query->execute();
		}
```

What went wrong here :D

2022-01-20 15:15 UTC, nickvergessen requested changes
See failing test and comment.
You duplicated a lot of code by accident and the arguemnt is changed and with your current code double json_encoded, so deleting fails

2022-01-20 17:29 UTC, acsfer commented
Wouldn't 10K (instead of 100K) be a little more conservative and less deadlock prone on a Galera?

2022-01-20 18:53 UTC, nickvergessen commented
> Wouldn't 10K (instead of 100K) be a little more conservative and less deadlock prone on a Galera?

Maybe we use a const in OCP then, so it can be used by apps and we need to only change 1 place in the future if adjusting makes sense, ref: 
https://github.com/nextcloud/activity/blob/master/lib/Data.php#L359-L374

2022-03-11 12:40 UTC, nickvergessen approved these changes

2022-03-11 13:09 UTC, PVince81 approved these changes
:+1:

2022-03-11 15:58 UTC, skjnldsv commented
Fixup needs rebase

2022-03-18 11:29 UTC, merged