Supercharge Issues template
nextcloud/server pull request #30778
Opened 2022-01-20 18:21 UTC by acsfer

More easy to fill, more accurate bug reports. :)

2022-01-20 20:55 UTC, nickvergessen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      label: PHP engine version
```suggestion
      label: Web server
```

2022-01-20 20:56 UTC, nickvergessen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      render: shell
json? or does not work?

2022-01-20 20:57 UTC, nickvergessen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      required: true
I always find it weird if expected behaviour comes before the steps.

2022-01-20 21:18 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      render: shell
AFAIK, only `shell` and `markdown` are allowed. Shell just inserts back-ticks to format the code.

2022-01-20 21:21 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      required: true
Fixed

2022-01-21 08:34 UTC, szaimen reviewed
Thanks for doing this! :)

Is there maybe a way to test this out before merging so that we make sure that everything works?

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +labels: ["bug", "needs triage"]
```suggestion
labels: ["bug", "0. Needs triage"]
```

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +          - Check if your Nextcloud Server is up to date. If not, we recommend that you update it first.
```suggestion
          - Check if your Nextcloud Server is up to date. If not, we recommend that you update it first. See https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule for supported versions.
```

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Official SNAP package"
Maybe add "Official All in One appliance" here as well? See https://github.com/nextcloud/all-in-one

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
What do choose here in case of a docker image or AIO or Snap?

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
In case of an unsupported webserver (everything except apache) we probably need its config, no?
Maybe we could also add a checkbox that confirms that the admin has made sure that the config is up-to-date with the config stated in the docs? e.g. https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

2022-01-21 08:34 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
What about an option for a reverse proxy?

2022-01-21 08:40 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Docker or Snap will run in an OS too, no? AS we can't list all the OS out there, listing the 4 more common and an Other options seems reasonable :)

2022-01-21 08:42 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
IMO, asking for things that are unrelated in the 1st template just bothers me. Ex. the log outputs an erros totally unrelated with the Webserver, why am I asked for its config? :)

2022-01-21 08:46 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Because sometimes e.g. the nginx config isn't up-to-date with the docs and updating it solves old, already fixed issues :)

2022-01-21 08:46 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +          - Check if your Nextcloud Server is up to date. If not, we recommend that you update it first.
Fixed.

2022-01-21 08:51 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Official SNAP package"
Fixed

2022-01-21 08:51 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
OK let's wait for other opinion on this one.

2022-01-21 08:51 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Snap technically runs on any Linux OS, Docker as well, so in case of snap should the OS not play a role at all. In case of Docker you are probably asking for the OS inside the container which should be more clear in the template, imo.

2022-01-21 08:53 UTC, acsfer commented
I am not aware of a "Preview before commit" on this.
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

2022-01-21 08:54 UTC, szaimen commented
> I am not aware of a "Preview before commit" on this.
> See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

okay, maybe I need to spin up a test repo for this one then and copy the template there for a test :)

2022-01-21 08:57 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
a good example on this why I think its necessary might be this: https://github.com/nextcloud/server/issues/16194#issuecomment-744481544

2022-01-21 09:04 UTC, acsfer commented
Screenshot added to the initial post.

2022-01-21 09:25 UTC, szaimen commented
Thanks for the screenshot! :)

I wonder is there a reason why
- config report
- list of activated apps
- nextcloud logs

are not required?

2022-01-21 09:28 UTC, acsfer commented
Yeah let's require them (user can always put Dummy content there...) 👍

2022-01-21 10:05 UTC, szaimen commented
@acsfer do you mind updating your testrepo with the latest changes? :)

2022-01-21 10:23 UTC, acsfer commented
@szaimen done

2022-01-21 10:26 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Official SNAP package"
@acsfer seems like your change got lost somehow?

2022-01-21 10:38 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Official SNAP package"
got lost with https://github.com/nextcloud/server/pull/30778/commits/6f8d35e0a4870f1403586ee37045177b8b506ea7

2022-01-21 11:05 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Official SNAP package"
re-added with https://github.com/nextcloud/server/pull/30778/commits/492e73b47efbddfea462acefd7134fb6b3f39501

2022-01-24 09:32 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
For docker, the OS will probably be always the same. I don't think that a lot of people are creating their own image from scratch.

Maybe simply change "base operating system"? But I think it is fine like that.

2022-01-24 09:37 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Well, i don't think that a issue template can fit all cases perfectly, unless github allows, in the future, some `if` conditions so everything can be more accurate :)

2022-01-24 09:39 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Same as https://github.com/nextcloud/server/pull/30778#discussion_r790559534 otherwise, if i check Apache, why must i confirm that I've applied those params? :)

2022-01-24 09:43 UTC, artonge requested changes
That's a nice quality of life improvement for bug reporters! :tada:

2022-01-24 09:43 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
This will need to be updated every few months. I do not have a solution besides using a text field, but we should be aware that this is additional maintenance work.

2022-01-24 09:43 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
+ sqlite and oracle?

2022-01-24 09:43 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
LDAP can be used in pairs with SAML., Internal user backend too. Can we use checkbox here instead of a select ?

2022-01-24 09:55 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Implemented

2022-01-24 09:55 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
Makes sense, implemented.

2022-01-24 09:59 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
jep, but changing that around once a year in one template should be fine, imo

2022-01-24 10:00 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
okay, fine by me then. Once github allows logic inside the template, we could think about implementing such a check then.

2022-01-24 10:05 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
I got it, but how do you ask that extra question **only if** you are using a reverse proxy?

2022-01-24 10:48 UTC, artonge approved these changes

2022-01-24 11:04 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
@artonge what do you think about that?

2022-01-24 11:04 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
hm... maybe just don't require an answer on this?

2022-01-25 07:41 UTC, acsfer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
My opinion is: the listed options covers 95% of deployments out there; in case there is another kind of setup, the "Other" option applies and further information should be filled in the "Additional info" field. Because, as already said, we will never cover 100% of configurations

2022-01-25 09:33 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
I think that the template is already very long so let's not add a new question to it. Else we can also add database and PHP configuration files, and maybe network architecture, the brand of the hard drive...

2022-01-25 09:35 UTC, artonge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
@szaimen Your example should be covered by checking for existing issues.

2022-01-25 09:38 UTC, szaimen approved these changes
lgtm then 👍

(we can still improve it going forward)

2022-01-25 09:38 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
fine by me then

2022-01-25 09:38 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "Other"
fine by me then

2022-01-25 09:39 UTC, szaimen commented
samba test failure is unrelated

2022-01-25 09:39 UTC, merged

2022-01-31 09:58 UTC, PVince81 commented
@acsfer great that filling out is easier.

however most of the mandatory fields are getting in the way, can we limit them to:
- steps to reproduce
- expected result
- actual result
- versions

this can usually be enough to reproduce obvious bugs in most cases
the probability of getting an answer is then proportional to the amount of information give

2022-01-31 10:01 UTC, PVince81 commented
like, for example I'm annoyed to have to provide signing status for my local dev instance for an issue that got reported to me by third parties and is clearly reproducible locally

2022-01-31 10:11 UTC, acsfer commented
@PVince81 I'll submit a PR on this.

2022-01-31 10:14 UTC, nickvergessen commented
https://github.com/nextcloud/server/pull/30932