Increase 2fa backup codes entropy
nextcloud/server pull request #3078
Opened 2017-01-16 10:25 UTC by ChristophWurst

Fixes https://github.com/nextcloud/server/issues/2708

cc @Wikinaut

2017-01-16 10:39 UTC, nickvergessen requested changes

2017-01-16 10:39 UTC, nickvergessen commented on apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
> +			$code = $this->random->generate(self::$CODE_LENGTH, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789');
while at it, use:
```php
$code = $this->random->generate(self::$CODE_LENGTH, ISecureRandom::CHAR_UPPER . ISecureRandom::CHAR_DIGITS);

2017-01-16 12:14 UTC, ChristophWurst commented on apps/twofactor_backupcodes/lib/Service/BackupCodeStorage.php
> +			$code = $this->random->generate(self::$CODE_LENGTH, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789');
thanks for the tip. fixed it

2017-01-16 14:06 UTC, nickvergessen approved these changes

2017-01-18 15:08 UTC, LukasReschke approved these changes

2017-01-18 15:08 UTC, merged