WIP: Built-in profiler
nextcloud/server pull request #30823
Opened 2022-01-24 09:23 UTC by CarlSchwan

A nice side project, I started working last weekend, still very much in progress

![image](https://user-images.githubusercontent.com/23653902/150755558-f08d47b9-08db-4427-b2bc-8577a49ea7e0.png)

![image](https://user-images.githubusercontent.com/23653902/150755606-bc67734c-a509-46a4-b51f-00ced5e32352.png)

![image](https://user-images.githubusercontent.com/23653902/150755631-63eeea84-f1e5-48a5-aa75-9c0484d43098.png)

2022-01-29 16:20 UTC, CarlSchwan commented
![image](https://user-images.githubusercontent.com/23653902/151668568-00a877d5-97c5-47cc-8e93-676fcb47f22c.png)

There is now a debug toolbar that also link to the profiler of the AJAX requests made in the background :)

2022-02-09 23:45 UTC, CarlSchwan commented
![image](https://user-images.githubusercontent.com/23653902/153309540-6df90474-43b9-47cd-80a2-ecadb2d7b3a3.png)

More progress now with a cache module

2022-03-03 17:10 UTC, come-nc requested changes
There seem to be files and copyrights from accessibility app that are not needed here (fonts, img…)

2022-03-03 17:10 UTC, come-nc commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Remove this from PR

2022-03-03 17:10 UTC, come-nc commented on apps/dav/lib/Profiler/ProfilerPlugin.php
> +		$this->request = $request;
profiler is not assigned

2022-03-03 17:10 UTC, come-nc commented on apps/dav/lib/Profiler/ProfilerPlugin.php
> +use OC\Profiler\Profiler;
Should be from OCP

2022-03-03 17:10 UTC, come-nc commented on apps/profiler/README.md
> +> This app provide multiple features to ease the use of nextcloud.
Does it?

2022-03-03 17:10 UTC, come-nc commented on apps/profiler/appinfo/info.xml
> +	<summary>Accessibility options for nextcloud</summary>
Nope

2022-03-03 17:13 UTC, PVince81 commented on apps/dav/lib/Server.php
> +		$this->profiler->setEnabled($config->getSystemValue('debug', false));
use "profiler" as key
some people might disable "debug" mode and use log conditions instead
also debug mode disables caching so not necessarily wanted on production systems

2022-03-03 17:15 UTC, PVince81 commented on apps/profiler/appinfo/info.xml
> +	<version>1.0.0</version>
consider moving to a separate repo and app store, so we can update it more often ?

2022-03-03 17:15 UTC, PVince81 commented on apps/profiler/appinfo/routes.php
> +	'ocs' => [
remove

2022-03-03 17:17 UTC, PVince81 commented on apps/profiler/lib/Controller/MainController.php
> +		$this->initialState->provideInitialState('profiler-categories', $this->profiler->dataProviders());
camel or kebab ?

2022-03-03 17:22 UTC, PVince81 commented on apps/profiler/src/components/ProfileHeader.vue
> +			return new Date(this.profile.time * 1000).toUTCString()
you can use the `moment()` library from core for proper formatting

2022-03-03 17:22 UTC, PVince81 commented on apps/profiler/src/components/QueryExplaination.vue
> +		<div v-if="true || explaination.data[0].length > 0">
explaination=>explanation

2022-03-03 17:24 UTC, PVince81 commented on apps/profiler/src/services.js
> +
empty?

2022-03-03 17:26 UTC, PVince81 commented on apps/profiler/src/toolbar.js
> +	if (ret = allHeaders.match(/^Symfony-Debug-Toolbar-Replace:\s+(.*)$/im)) {
we don't have this, right ?

2022-03-03 17:31 UTC, PVince81 commented on lib/private/Profiler/Profiler.php
> +		$this->storage = new FileProfilerStorage('/var/www/html/data/profiler');
hard coded path?

2022-03-03 17:33 UTC, PVince81 commented on lib/public/DataCollector/IDataCollector.php
> + * SPDX-License-Identifier: MIT
check license, because Nextcloud is AGPL

2022-03-14 14:45 UTC, CarlSchwan commented
ui is now at https://github.com/CarlSchwan/nextcloud-profiler

2022-03-14 16:09 UTC, come-nc commented on apps/dav/lib/Profiler/ProfilerPlugin.php
> +use OC\Profiler\Profiler;
```suggestion
```

2022-03-14 16:11 UTC, come-nc commented on apps/dav/lib/Server.php
> +		$this->server->addPlugin(new ProfilerPlugin($this->request, $this->profiler));
There is only one argument to ProfilerPlugin constructor I think?

2022-03-14 16:12 UTC, come-nc commented on apps/dav/lib/Server.php
> +			$eventLogger = \OC::$server->get(IEventLogger::class);
```suggestion
		if ($this->profiler->isEnabled()) {
```

2022-03-14 16:16 UTC, come-nc commented on apps/user_ldap/lib/LDAP.php
> +				$carry[] = !is_resource($item) ? $item : '(resource)';
Why are resource excluded? Ldap resources are replaced by objects in PHP >= 8.1, do they need to be excluded as well?

2022-03-14 16:49 UTC, CarlSchwan commented on apps/user_ldap/lib/LDAP.php
> +				$carry[] = !is_resource($item) ? $item : '(resource)';
I mostly copied the logic that was used to excludes the resources also for the file logger.

The reason is that resources can sometimes be tricky and can't be copied or read without side effects, which might cause some unexpected issues.

2022-03-15 08:13 UTC, come-nc commented on apps/user_ldap/lib/LDAP.php
> +				$carry[] = !is_resource($item) ? $item : '(resource)';
But what is done with those args after?
I know that LDAP objects will throw if serialized for instance. Thus they cannot be kept in session.

2022-03-15 10:38 UTC, artonge reviewed
There are still a lot of code scanning errors

2022-03-15 14:41 UTC, CarlSchwan commented
> There are still a lot of code scanning errors

fixed now

2022-03-15 15:12 UTC, come-nc commented
`@since` comments are needed in all new files in `lib/public`: https://drone.nextcloud.com/nextcloud/server/16694/1/3
You also need to run `composer run cs:fix`.

And there are missing return types on some of the new methods, please add them.

2022-03-15 16:10 UTC, come-nc commented on apps/user_ldap/lib/LDAP.php
> +				$carry[] = !isResource($item) ? $item : '(resource)';
```suggestion
				$carry[] = !$this->isResource($item) ? $item : '(resource)';
```
Same for the other one.

2022-03-16 15:17 UTC, artonge approved these changes

2022-03-30 08:14 UTC, skjnldsv approved these changes
:elephant:

2022-03-30 09:39 UTC, come-nc commented on apps/user_ldap/lib/LDAP.php
> +			}, []);
```suggestion
			$args = array_map(
				fn ($item) => ($this->isResource($item) ? '(resource)' : $item),
				$this->curArgs
			);
```

2022-03-30 09:39 UTC, come-nc commented on apps/user_ldap/lib/LDAP.php
> +			}, []);
(and same for second instance below)

2022-03-30 09:41 UTC, come-nc commented on config/config.sample.php
> +'profiler' => false,
Could this be a config option in the profiler app settings instead?

2022-03-30 09:47 UTC, come-nc commented on lib/private/DB/DbDataCollector.php
> +	protected $logger;
Can you rename it to avoid confusion with LoggerInterface instances we have in some many classes? $debugStack?

2022-03-30 09:52 UTC, CarlSchwan commented on config/config.sample.php
> +'profiler' => false,
not really because if it's in the app config then we need to do a DB query before we know if we can enable the profiler or not

2022-03-30 11:52 UTC, come-nc approved these changes

2022-03-30 12:10 UTC, come-nc commented
From drone:
```
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::add
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::loadProfileFromResponse
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::loadProfile
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::saveProfile
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::find
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::dataProviders
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::isEnabled
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::setEnabled
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfiler::collect
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getToken
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setToken
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getTime
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setTime
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getUrl
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setUrl
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getMethod
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setMethod
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getStatusCode
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setStatusCode
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::addCollector
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getParent
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setParent
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getParentToken
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getChildren
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setChildren
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::addChild
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getCollectors
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::setCollectors
@since or @deprecated tag is needed in PHPDoc for OCP\Profiler\IProfile::getCollector
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\IDataCollector::collect
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\IDataCollector::reset
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\IDataCollector::getName
PHPDoc is needed for OCP\DataCollector\AbstractDataCollector::getName
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\AbstractDataCollector::reset
PHPDoc is needed for OCP\DataCollector\AbstractDataCollector::__sleep
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\AbstractDataCollector::serialize
@since or @deprecated tag is needed in PHPDoc for OCP\DataCollector\AbstractDataCollector::unserialize
PHPDoc is needed for OCP\DataCollector\AbstractDataCollector::jsonSerialize
```

2022-03-31 19:48 UTC, nickvergessen commented on lib/private/DB/DbDataCollector.php
> +/**
declare strict?

2022-03-31 19:48 UTC, nickvergessen commented on lib/private/DB/ObjectParameter.php
> +
strict?

2022-03-31 19:48 UTC, nickvergessen commented on lib/private/Memcache/LoggerWrapperCache.php
> +/**
strict?

2022-03-31 19:48 UTC, nickvergessen commented on lib/private/Memcache/ProfilerWrapperCache.php
> +/**
strict?

2022-03-31 19:48 UTC, nickvergessen commented on lib/private/Profiler/Profile.php
> +/**
strict

2022-03-31 19:48 UTC, nickvergessen commented on lib/public/DataCollector/AbstractDataCollector.php
> +declare(strict_types=1);
before header

2022-03-31 19:48 UTC, nickvergessen commented on lib/public/DataCollector/IDataCollector.php
> +declare(strict_types=1);
before header

2022-03-31 19:48 UTC, nickvergessen commented on lib/public/Profiler/IProfile.php
> +/**
strict?

2022-04-04 10:56 UTC, merged