Minor optimizations for saving user personal information
nextcloud/server pull request #30863
Opened 2022-01-26 20:14 UTC by CarlSchwan

* Remove double hook: the OC_User::changeUser triggers an
OC\AccountManager::userUpdated and the app is already listening to this
signal in its Application definition

* Make createCard not check if a card exists if we already checked
  previously. We also don't try to get the card if the user is disabled
  as we don't use the card in this case

* Don't make AccountManager::deleteUser, delete the user twice

We this change we go from 102 DB requests to ~81 DB requests when saving
a user email address. Still way too much in my opinion but it's a start :)

Future improvements:

* Batch insert card properties: instead of doing 6-8 inserts at a time, do all of
  them at the same time
* Batch modify user properties, currently if you modify 4 properties, each time
  you trigger various hooks to regenerate the addressbook card and the birthday
  calendar, and create an audit log entry, activity entry, ...

2022-01-26 22:10 UTC, nickvergessen requested changes

2022-01-26 22:10 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> -		$this->deleteUserData($user);
This is needed otherwise there is data left in the data table which is used for search?

2022-01-26 22:11 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> -		$this->deleteUserData($user);
I guess you missread the table name

2022-01-26 22:26 UTC, CarlSchwan commented on lib/private/Accounts/AccountManager.php
> -		$this->deleteUserData($user);
Oh yeah now it make sense there is an deleteUser and deleteUserData table, I couldn't spot the difference.

2022-01-26 22:29 UTC, CarlSchwan commented
Todo: fix tests

2022-01-27 08:13 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				->andWhere($q->expr()->eq('uid', $q->createNamedParameter($uid)))
Do you think it is worth it to have an index on `(addressbookid, uid)` as well?

2022-01-27 11:37 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				->andWhere($q->expr()->eq('uid', $q->createNamedParameter($uid)))
If I'm reading the code correctly, there is already an index defined in apps/dav/lib/Migration/Version1004Date20170924124212.php ?

2022-01-27 11:44 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				->andWhere($q->expr()->eq('uid', $q->createNamedParameter($uid)))
There's one on `addressbookid`, and another on `addressbookid, uri`, not on `addressbookid, uid`.

2022-01-27 11:48 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				->andWhere($q->expr()->eq('uid', $q->createNamedParameter($uid)))
I guess it depends on if `addressbookid` as index is enough and there are usually not many cards with the same `addressbookid` but different `uid`. I don't have enough insight into the app to see how exactly this is used.

Adding indexes makes writing slower but reading faster, it's not a solution for all the problems :/

2022-01-27 12:10 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				->andWhere($q->expr()->eq('uid', $q->createNamedParameter($uid)))
From what I can see from old analysis data, the index on `addressbookid` is very used, but not the `addressbookid, uri` one. Will do extensive analysis later.
Non blocking anyway.

2022-02-17 18:07 UTC, nickvergessen approved these changes

2022-02-24 16:11 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +		if ($checkAlreadyExists) {
TODO check if we can just insert and then catch the exception if it's already exists

2022-02-24 16:12 UTC, come-nc approved these changes

2022-03-02 20:10 UTC, CarlSchwan commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +		if ($checkAlreadyExists) {
there is no unique indexes on this fields :/ so not possible

2022-05-13 06:30 UTC, skjnldsv commented
Seems to be still broken

2022-05-13 10:56 UTC, CarlSchwan commented
ci failures unrelared (due to the toast.scss change)

2022-05-13 10:56 UTC, merged