added parameter default values
nextcloud/server pull request #3087
Opened 2017-01-16 14:43 UTC by j-ed

referring to: https://github.com/nextcloud/server/issues/3069

Based on a source code analysis (looking for getSystemValue() function) I added the default values of the parameters.

- Unfortunately for several parameters different default values are used in the source code and my question how this should be addressed has not been answered yet. Examples:
```
getSystemValue('dbtype', 'sqlite')
getSystemValue('dbtype', '')
getSystemValue('dbtype')
```

- For other parameters contradictory values are used. Examples:
```
getSystemValue('preview_max_x', 2048)
getSystemValue('preview_max_x', 1024)
or
getSystemValue('preview_max_y', 2048)
getSystemValue('preview_max_y', 1024)
```

- Additionally some of the parameters have still not been adjusted for Nextcloud. Examples:
```
getSystemValue('dbname', 'owncloud')
getSystemValue('dbtableprefix', 'oc_')
```

2017-01-16 15:05 UTC, nickvergessen approved these changes

2017-01-16 15:26 UTC, oparoz commented
:+1:

2017-01-16 17:44 UTC, MorrisJobke commented on config/config.sample.php
> + * Where user files are stored.The SQLite database is also stored here, when
Space before `The` missing

2017-01-16 19:18 UTC, j-ed commented on config/config.sample.php
> + * Where user files are stored.The SQLite database is also stored here, when
[x] fixed.

2017-01-16 19:34 UTC, nickvergessen commented on config/config.sample.php
> + * * Desktop client: ```https://nextcloud.com/install/#install-clients```
should be two ticks only on each side, not 3

2017-01-17 02:25 UTC, MorrisJobke commented
@j-ed Sorry for not bringing this up earlier: we require a sign-off for your commits. You can read the details here: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

Thanks for the contribution and it now looks good. Once the sign-off is added to the commits we can merge it :)

2017-01-17 02:26 UTC, MorrisJobke commented
> Thanks for the contribution and it now looks good. Once the sign-off is added to the commits we can merge it :)

Then also CI gets green ;)

2017-01-17 09:46 UTC, nickvergessen requested changes

2017-01-17 09:46 UTC, nickvergessen commented on config/config.sample.php
>  'minimum.supported.desktop.version' => '2.0.0',
I'd also adjust the sample value here to match the default.

2017-01-17 09:46 UTC, nickvergessen commented on config/config.sample.php
> + * Default to ``themes/`` in Nextcloud directory
No, this is not the theme directory, but the actual theme. This has no default value:
`Defaults to the theming app which is shipped since Nextcloud 9`

2017-01-17 09:46 UTC, nickvergessen commented on config/config.sample.php
> + * Defaults to ``''`` (empty string)
defaults to null

2017-01-17 09:46 UTC, nickvergessen commented on config/config.sample.php
> + * Defaults to ``''`` (empty string)
It's an array and has no default value.

2017-01-17 10:04 UTC, ChristophWurst commented
> nickvergessen requested changes

I've adjusted the label accordingly

2017-01-17 11:17 UTC, j-ed commented on config/config.sample.php
>  'minimum.supported.desktop.version' => '2.0.0',
fixed typo after double-checking which default is used in the source code.

2017-01-17 11:17 UTC, j-ed commented on config/config.sample.php
> + * Default to ``themes/`` in Nextcloud directory
[x] done.

2017-01-17 11:17 UTC, j-ed commented on config/config.sample.php
> + * Defaults to ``''`` (empty string)
default information removed.

2017-01-17 11:17 UTC, j-ed commented on config/config.sample.php
> + * Defaults to ``''`` (empty string)
[x] done.

2017-01-17 11:19 UTC, j-ed commented
@MorrisJobke I've added a 'Signed-off-by:" line to my last commit.

2017-01-18 00:27 UTC, MorrisJobke commented
> @MorrisJobke I've added a 'Signed-off-by:" line to my last commit.

It needs to be done for all commits. I will squash them into one and merge this here then.

2017-01-18 00:30 UTC, MorrisJobke commented
> It needs to be done for all commits. I will squash them into one and merge this here then.

Done in https://github.com/nextcloud/server/pull/3133

2017-01-18 00:30 UTC, closed without merging