Update ICommentsManager with reaction methods
nextcloud/server pull request #30888
Opened 2022-01-27 16:13 UTC by vitormattos

Objective: update https://github.com/ChristophWurst/nextcloud_composer/ with reaction methods.

The script [build.sh](https://github.com/ChristophWurst/nextcloud_composer/blob/master/build.sh) only get `lib/public classes`.
The reaction methods was implemented on `lib/private/Comments/Manager.php`

2022-01-28 15:43 UTC, nickvergessen commented on lib/public/Comments/ICommentsManager.php
> +	public function retrieveAllReactionsWithSpecificReaction(int $parentId, string $reaction): ?array;
```suggestion
	public function retrieveAllReactionsWithSpecificReaction(int $parentId, string $reaction): array;
```

Should be changed on the Manager too. always returns an array. In worst case it's empty.
Null should not be returned

2022-01-28 15:44 UTC, nickvergessen commented on lib/public/Comments/ICommentsManager.php
> +	public function supportReactions(): bool;
Sort this before the other methods, so retrieveAllReactions and retrieveAllReactionsWithSpecificReaction which are very similar are next to each other?

2022-01-28 15:44 UTC, nickvergessen requested changes
See the null comment

2022-02-01 12:46 UTC, nickvergessen approved these changes

2022-02-02 19:50 UTC, danxuliu requested changes
Other than the comments, :+1: 

As the commits after the first one mostly* fix code introduced in the first commit it would be better to squash them in a single commit.

*There is also a reordering of existing code, but as it is reordered to adjust to the public interface for simplicity squashing in a single commit would still be fine (although I would extract it to its own commit, but in this case I am OK with squashing everything :-P )

2022-02-02 19:50 UTC, danxuliu commented on lib/private/Comments/Manager.php
> +	 * @param string $reaction
There is no `$reaction` parameter.

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @param string $reaction
There is no `$reaction` parameter.

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @since 24.0.0
`throwIfNotSupportReactions()` is called in the implementation, so `Throws PreConditionNotMetException when the system haven't the minimum requirements to use reactions` and `@throws PreConditionNotMetException` are missing in the documentation.

2022-02-02 19:50 UTC, danxuliu commented on lib/private/Comments/Manager.php
>  	 * @since 24.0.0
`Throws PreConditionNotMetException when the system haven't the minimum requirements to use reactions` and `@throws PreConditionNotMetException` are missing in the documentation.

2022-02-02 19:50 UTC, danxuliu commented on lib/private/Comments/Manager.php
> +	 * @return IComment[]
Typically `return` is above `throws`.

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @return IComment[]
Typically `return` is above `throws`.

2022-02-02 19:50 UTC, danxuliu commented on lib/private/Comments/Manager.php
> +	 * @param integer $parentId
`integer` or `int`?

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @param integer $parentId
`integer` or `int`?

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @param integer $parentId
`integer` or `int`?

2022-02-02 19:50 UTC, danxuliu commented on lib/public/Comments/ICommentsManager.php
> +	 * @return boolean
`boolean` or `bool`?

2022-02-02 20:16 UTC, vitormattos commented on lib/private/Comments/Manager.php
> +	 * @param integer $parentId
Two ways works on docblocks but looking the pattern on this file, I will change to int

2022-02-02 20:22 UTC, vitormattos commented on lib/public/Comments/ICommentsManager.php
> +	 * @return boolean
Isn't a pattern, on this class have methods with two formats, but, following most methods, I will change to bool

2022-02-03 05:51 UTC, danxuliu commented
@vitormattos It looks like you force pushed twice and in the second force push you reverted the changes back to the previous commit, could you check? Thanks!

2022-02-03 15:55 UTC, danxuliu approved these changes

2022-02-04 08:38 UTC, merged