Move all children of a folder in a single query
nextcloud/server pull request #3089
Opened 2017-01-16 15:37 UTC by icewind1991

- Adds function builder to the query builder for easier constructing of complex query functions and cross db compatibility
- Make `md5` and `concat` work across supported databases
- Move all children of a folder in a single query by doing the path and path_hash manipulation in sql

[comparison](https://blackfire.io/profiles/compare/72cb7951-1deb-4ad5-8d98-7311a73b6097/graph) when renaming a folder with ~500 files

2017-01-16 16:58 UTC, nickvergessen requested changes

2017-01-16 16:58 UTC, nickvergessen commented on tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
> +		$this->assertEquals('oobar', $query->execute()->fetchColumn());
So this is starting with index 1 not 0 like in php, odd... should we adjust it?
At least it should be documented

2017-01-16 17:00 UTC, schiessle commented on lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
> +/**
Please use the license header as documented here with the "or any later part": https://docs.nextcloud.com/server/12/developer_manual/general/codingguidelines.html#license-headers

Thanks!

2017-01-18 14:48 UTC, icewind1991 commented on tests/lib/DB/QueryBuilder/FunctionBuilderTest.php
> +		$this->assertEquals('oobar', $query->execute()->fetchColumn());
It is documented in the functions docs.

I thought about adjusting it but it seems better to me to be consistent with sql behavior

2017-01-18 14:48 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/ExpressionBuilder/SqliteExpressionBuilder.php
> +/**
fixed

2017-01-26 04:32 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-02-07 13:04 UTC, icewind1991 commented
@nickvergessen @schiessle @rullzer please (re)review

2017-02-20 14:22 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +		return new QueryFunction('CONCAT(' . $this->helper->quoteColumnName($x) . ', ' . $this->helper->quoteColumnName($y) . ')');
Missing tests

2017-02-20 14:47 UTC, icewind1991 commented
@nickvergessen @schiessle @rullzer *poke*

2017-02-20 21:15 UTC, LukasReschke requested changes

2017-02-20 21:15 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +		if ($length) {
Let's make a SQL injection as unlikely as possible, I'd appreciate an additional check on the type.

2017-02-20 21:15 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +	public function substring($input, $start, $length = null) {
Also a typehint on $input for IParameter to make SQL Injections as unlikely as possible?

2017-02-20 21:15 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +		if ($length) {
Also while at it check for $start as well :)

2017-02-20 21:15 UTC, LukasReschke commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * @param mixed $y The seccond input string
Also: What is mixed? Can we limit this a bit more to forbid strings? I don't really like the idea of potential SQL injections too much :)

2017-02-20 21:15 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +	public function md5($input) {
Also a typehint on $input for IParameter to make SQL Injections as unlikely as possible?

2017-02-20 21:15 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LOWER(DBMS_OBFUSCATION_TOOLKIT.md5 (input => UTL_RAW.cast_to_raw(' . $this->helper->quoteColumnName($input) .')))');
Not covered by tests.

2017-02-21 12:18 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +	public function md5($input) {
`IParameter` is to strict since I need to use md5 on the result of a function

2017-02-21 12:26 UTC, icewind1991 commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * @param mixed $y The seccond input string
Just plain strings are always interpreted as column names. if you actually want to use a string you need to use the `ILitteral`

This is true for all query builder stuff

2017-02-21 12:26 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/FunctionBuilder/OCIFunctionBuilder.php
> +		return new QueryFunction('LOWER(DBMS_OBFUSCATION_TOOLKIT.md5 (input => UTL_RAW.cast_to_raw(' . $this->helper->quoteColumnName($input) .')))');
It is, we just dont run oci tests

2017-02-21 13:45 UTC, icewind1991 commented on lib/public/DB/QueryBuilder/IFunctionBuilder.php
> +	 * @param mixed $length The length of the substring
`IFunction|IParameter|ILiteral|string` would be the correct type for all of them (ignore the `null`)

But on all other places in query builder land we just use `mixed` and I would prefer to keep them consistent

2017-02-21 13:48 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +		return new QueryFunction('CONCAT(' . $this->helper->quoteColumnName($x) . ', ' . $this->helper->quoteColumnName($y) . ')');
https://github.com/nextcloud/server/pull/3089/files#diff-e1614c809893212b87688c2a0525144eR43

2017-02-21 13:49 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/FunctionBuilder/PgSqlFunctionBuilder.php
> +		return new QueryFunction($this->helper->quoteColumnName($x) . ' || ' . $this->helper->quoteColumnName($y));
https://github.com/nextcloud/server/pull/3089/files#diff-e1614c809893212b87688c2a0525144eR43

2017-02-21 13:49 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
> +		return parent::like($x, $y, $type) . " ESCAPE '\\'";
added

2017-02-21 13:49 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +					throw $e;
fixed

2017-02-22 09:20 UTC, LukasReschke commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +	public function md5($input) {
I consider this really confusing though. I bet many people will think: "Oh. It is an MD5. I don't need to escape that." and forget that we don't hash in PHP but pass it to the DB.

2017-03-26 18:44 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/FunctionBuilder/FunctionBuilder.php
> +	public function md5($input) {
if you pass a plain string it wont work anyway, since plain strings are interperted as collumn names

2017-03-26 19:06 UTC, icewind1991 commented
@nickvergessen @LukasReschke please re-review

2017-03-30 07:50 UTC, rullzer commented
conflicts!

2017-03-30 10:58 UTC, icewind1991 commented
rebased!

2017-03-30 12:08 UTC, rullzer approved these changes
Lets do this!

2017-03-30 12:08 UTC, merged

2017-06-28 21:21 UTC, marcelklehr commented on lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
> +		return parent::like($x, $y, $type) . " ESCAPE '\\'";
This change likely causes this pr (https://github.com/nextcloud/bookmarks/pull/368) to fail on nc12+ :/