Show the parent folders in the breadcrumb menu when on a child entry.
nextcloud/server pull request #30925
Opened 2022-01-30 15:49 UTC by paierlep

Previously, clicking on an menu item in the breadcrumb menu removed the
parent entries of the path, i.e.:
Clicking on the "to" entry in "/path/to/some/folder" changed the
breadcrumb menu to show only the "/path/to" entries.
With this change the breadcrumb menu changes this behaviour as the full
path is still visible (and usable) but with the "to" entry beeing
highlighted.

Closes #1079
cc @nextcloud/designers @nextcloud/javascript @jancborchardt @szaimen

Signed-off-by: Christian Paier <hallo+git@cpaier.com>

2022-01-31 10:28 UTC, nimishavijay commented
Sounds great! Would it be possible to post screenshots of the before/after to make it easier to see the design changes? :)

2022-01-31 15:57 UTC, paierlep commented
Yes sure:
The breadcrumb renders as usually when viewing a folder:
![in_child_folder](https://user-images.githubusercontent.com/1857463/151827056-9ad82050-d604-4edf-ad62-570929ec4ed0.png)

Clicking on one of the parent folders gives a slightly different behavior:
![clicking_on_parent](https://user-images.githubusercontent.com/1857463/151827053-e196b102-54d7-4b53-8a07-19984c2e6d0a.png)

2022-01-31 18:46 UTC, nimishavijay approved these changes
🚀

2022-02-01 10:20 UTC, szaimen reviewed
Would it be possible to adjust the gaps so that the gaps in before and after look the same?
![image](https://user-images.githubusercontent.com/42591237/151951164-1cb0ba6f-76e2-49c4-b119-ce55e4c0430b.png)

2022-02-01 10:52 UTC, nimishavijay commented
There is a new breadcrumbs component, this would just be integrated with that, correct?

2022-02-01 11:36 UTC, artonge commented
> There is a new breadcrumbs component, this would just be integrated with that, correct?

No, the new breadcrumbs component is in vue, and this touches legacy code :(.

2022-02-01 11:40 UTC, artonge requested changes

2022-02-01 11:40 UTC, artonge commented on apps/files/js/breadcrumb.js
> +					$menuItem.find('a').attr('href', this.getCrumbUrl(parts[Math.max(this.activeItemIndex, 0)], j));
@skjnldsv 

You introduce `this.getCrumbUrl(part, j));` in https://github.com/nextcloud/server/pull/7051. Did you mean `menuPart` instead of `part`?

`part` would mean the latest item in the previous for loop. `menuPart` would mean the current item in the current loop.

If `menuPart`, then let's use `menuPart` instead of the proposed change.

2022-02-01 11:40 UTC, artonge commented on apps/files/js/breadcrumb.js
> +				if (i === this.activeItemIndex) {
```suggestion
				if (pathToHere === this.dir) {
					this.activeItemIndex = i
```

2022-02-01 11:40 UTC, artonge commented on apps/files/js/breadcrumb.js
> +
```suggestion
```

2022-02-01 11:40 UTC, artonge commented on apps/files/js/breadcrumb.js
> +				this.breadcrumbs[this.activeItemIndex + 2].append(view.$el);
While testing, there was an error when `this.dir === '/'. This helped:

```suggestion
				if (this.breadcrumbs.length > 2) {
					this.breadcrumbs[this.activeItemIndex + 2].append(view.$el);
				}
```

2022-02-01 20:43 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +				this._getMaxDepthDir(dir, this.maxDepthDir || "");
that's a very good - and much better idea. I've changed it accordingly!

2022-02-01 20:44 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +				if (i === this.activeItemIndex) {
Thx - Adopted this as well

2022-02-01 20:45 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +
... and finally this one also is added

2022-02-01 20:46 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +				this.breadcrumbs[this.activeItemIndex + 2].append(view.$el);
Thank you for finding this!

2022-02-01 20:47 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +					$menuItem.find('a').attr('href', this.getCrumbUrl(parts[Math.max(this.activeItemIndex, 0)], j));
This part felt very odd to be honest. I thought that this is because of the "old fashioned style" in this code - but I agree, `menuPart` feels more natural here.

2022-02-01 20:49 UTC, paierlep commented
> Would it be possible to adjust the gaps so that the gaps in before and after look the same? ![image](https://user-images.githubusercontent.com/42591237/151951164-1cb0ba6f-76e2-49c4-b119-ce55e4c0430b.png)

No problem - I've changed the scss file accordingly:

![Screenshot from 2022-02-01 21-41-34](https://user-images.githubusercontent.com/1857463/152049023-5e1c8d72-1eca-4cf4-98b1-17e3e5b3969b.png)
![Screenshot from 2022-02-01 21-41-57](https://user-images.githubusercontent.com/1857463/152049078-a82982c6-fa25-4058-955f-203e1b2db147.png)

2022-02-02 09:28 UTC, artonge commented
Need a rebase on master to make the `continuous-integration/drone/pr` work

`git rebase origin/master`

2022-02-03 08:10 UTC, skjnldsv commented on apps/files/js/breadcrumb.js
> +					$menuItem.find('a').attr('href', this.getCrumbUrl(parts[Math.max(this.activeItemIndex, 0)], j));
> You introduce this.getCrumbUrl(part, j)); in https://github.com/nextcloud/server/pull/7051. Did you mean menuPart instead of part?

It was in 2017, safe to say I don't recall at all :see_no_evil:

2022-02-03 09:15 UTC, szaimen commented
> No problem - I've changed the scss file accordingly:
> 
> ![Screenshot from 2022-02-01 21-41-34](https://user-images.githubusercontent.com/1857463/152049023-5e1c8d72-1eca-4cf4-98b1-17e3e5b3969b.png) ![Screenshot from 2022-02-01 21-41-57](https://user-images.githubusercontent.com/1857463/152049078-a82982c6-fa25-4058-955f-203e1b2db147.png)

Thanks! looks much better to me now :)

2022-02-03 09:15 UTC, szaimen approved these changes
tested and works 👍
(but didn't review the code)

2022-02-03 10:20 UTC, artonge commented on apps/files/js/breadcrumb.js
> +					$menuItem.find('a').attr('href', this.getCrumbUrl(parts[Math.max(this.activeItemIndex, 0)], j));
Just checked on master, and when the breadcrumb is squeezed into '...', items that are in the '...' all link to the same URL. So it feels like a never noticed bug.

Let's use `menuPart` @paierlep :).

```suggestion
 					$menuItem.find('a').attr('href', this.getCrumbUrl(menuPart, j)); 
```

2022-02-03 19:25 UTC, paierlep commented on apps/files/js/breadcrumb.js
> +					$menuItem.find('a').attr('href', this.getCrumbUrl(parts[Math.max(this.activeItemIndex, 0)], j));
Yes - I've already changed it as my tests also showed that `menuPart` should be correct!

2022-02-03 19:40 UTC, paierlep commented
> Need a rebase on master to make the `continuous-integration/drone/pr` work
Rebasing did not help with  sqlite-php7.4-samba-non-native (No code coverage driver is available)

2022-02-08 13:51 UTC, artonge approved these changes

2022-02-08 13:52 UTC, merged

2022-02-08 14:21 UTC, raimund-schluessler commented
> There is a new breadcrumbs component, this would just be integrated with that, correct?

No, the nextcloud/vue breadcrumb component does not support this. If this is really desired, we would need to modify it.

But I have to admit, I find the behavior confusing. It takes more attention to figure out, which folder is currently open. And while this is a personal feeling that might change when getting used to it, there is also an objective usability problem with this solution.

See this screenshot. Which folder is currently open?
![Screenshot 2022-02-08 at 15-10-42 Even more folders - Files - Nextcloud](https://user-images.githubusercontent.com/2496460/153005040-6d8e9d35-491a-489a-b35a-668b35659d27.png)

The currently open folder is hidden, because the breadcrumb bar is to long. So it is not possible to see which folder is open.

And even clicking the three-dots menu does not give a hint, because the currently open folder ("Even more folders" in this case) is not bold.
![Screenshot 2022-02-08 at 15-11-15 Even more folders - Files - Nextcloud](https://user-images.githubusercontent.com/2496460/153005330-8da6c4d7-02fd-4f07-8e2a-73e0b9a123d2.png)

The second point can be fixed by making the folder that is open bold in the three-dots menu. For the first issue, I don't see a solution using this approach, to be honest.
@jancborchardt How does Nautilus handle this?

2022-02-08 20:10 UTC, paierlep commented
Thank you for reviewing @artonge, @szaimen, @nimishavijay!

@raimund-schluessler nautilus seems to omit the first folders of the path, for a nested set of folders from a to z the outcome on the folder "u" only shows the folders "f" to "u":
![Screenshot from 2022-02-08 20-58-27](https://user-images.githubusercontent.com/1857463/153066038-4f799c81-beda-44f5-a8c4-8647f9868d9f.png)

Therefore getting to the root folder is only possible by clicking on the "f" folder first.
To add my 2 cents:
I prefer the dropdown menu from above screenshot. Additionally I think it could look something like this:
```
Home > ... > Active Folder > ... > Deepest Child Folder
```

With the ... being one of those placeholders with dropdown menu from the screenshot. Best solution would be of course if there is a lot more space to expand this to, i.e.:
```
Home > ... > Parent Folder > Active Folder > Child Folder > ... > Deepest Child Folder
```

2022-02-09 11:09 UTC, jancborchardt commented
So @nimishavijay and I checked back on how it’s done elsewhere. Since I initially opened the issue https://github.com/nextcloud/server/issues/1079 because Nautilus did it, checking with it now, they don’t do it anymore. Neither does e.g. Google Drive or Dropbox.

Hence considering all the issues and possible confusion this brings, it’s probably best to not do this after all – @paierlep sorry about that, we should have kept the issue up to date. :\

@raimund-schluessler what do you think?

2022-02-10 18:17 UTC, paierlep commented
@jancborchardt don't worry, I could have asked before so it is totally on me.

Nevertheless I am still think that there is some usage to a feature like that. I am also wondering where you got the information about the other examples: I've shown you how nautilus is doing it above, and Google Drive does more or less what I've proposed already (I do not have a dropbox account anymore - so no way comparing that for me):
![Screenshot from 2022-02-10 19-12-13](https://user-images.githubusercontent.com/1857463/153470110-aeb5f49d-d0ed-405b-8ec6-3a212311f46a.png)

So in my opinion the mechanism to directly jump into one of the parent folders is **totally** useful, but should be done much more carefully (compared to this change) i.e. to handle those "edgecases" @raimund-schluessler brought up.

2022-03-11 09:42 UTC, szaimen commented
So should thid be reverted?