Calendar migration
nextcloud/server pull request #30963
Opened 2022-02-02 03:57 UTC by Pytal

TODO drop all code for testing purposes and integrate with user_migration app API

2022-02-02 08:41 UTC, tcitworld commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
Could show a message telling the path of the export. Optionally with a `-q` quiet flag.

2022-02-02 08:41 UTC, tcitworld commented on apps/dav/lib/Command/Import.php
> +				'Path to the *.ics file',
Should probably be able to handle multiple .ics files at once, or an archive.

2022-02-02 08:41 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +					if (!isset($properties['{http://nextcloud.com/ns}refresh-interval'])) {
Not needed here, this is just for when calendars are exported for subscriptions.

2022-02-02 08:41 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			);
Add `VObjectReader::OPTION_FORGIVING`

2022-02-02 08:41 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +					"BEGIN:VCALENDAR\n",
`VCALENDAR` can hold other components than `VEVENT`, such as `VTIMEZONE`, `VALARM` or `VTODO`. We shouldn't drop them.
https://datatracker.ietf.org/doc/html/rfc5545#section-3.6

2022-02-03 04:39 UTC, Pytal commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
All cli stuff is for testing purposes and will be dropped since this implementation will register with and be invoked by the occ command of https://github.com/nextcloud/user_migration

2022-02-03 04:39 UTC, Pytal commented on apps/dav/lib/Command/Import.php
> +				'Path to the *.ics file',
Yes this will be brought inline with the export functionality

2022-02-03 04:39 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +					"BEGIN:VCALENDAR\n",
Yes more components will be brought in

2022-02-03 04:41 UTC, Pytal commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
All cli stuff is for testing purposes and will be dropped since this implementation will register with and be invoked by the occ command of https://github.com/nextcloud/user_migration, see https://github.com/nextcloud/user_migration/pull/27

2022-02-14 15:40 UTC, tcitworld commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
Maybe it makes sense to have https://github.com/nextcloud/server/issues/564 independently of exporting the whole account?

2022-02-15 02:56 UTC, Pytal commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
Yes it would, for now the focus is on integrating this into https://github.com/nextcloud/user_migration for full user migration, after which the shared code may be abstracted and more granular functionality may be added for https://github.com/nextcloud/server/issues/564

2022-02-15 02:56 UTC, Pytal commented on apps/dav/lib/Command/Export.php
> +			$this->calendarMigrator->export($user, $output);
Yes it would, for now though the focus is on integrating this into https://github.com/nextcloud/user_migration for full user migration, after which the shared code may be abstracted and more granular functionality may be added for https://github.com/nextcloud/server/issues/564

2022-02-24 05:42 UTC, Pytal commented
Pending merge of required PRs

2022-02-24 05:42 UTC, Pytal commented
Keeping as a draft pending merge of required PRs

2022-02-24 05:46 UTC, Pytal commented
Ready for review, but keeping as a draft for now pending merge of required PRs

2022-02-24 05:48 UTC, Pytal commented
Ready for review but keeping as a draft for now pending merge of required PRs

2022-02-24 08:47 UTC, tcitworld reviewed
Some quick remarks

2022-02-24 08:47 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +use function Safe\substr;
This is probably not intended.

2022-02-24 08:47 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +		$calendarId = $this->calDavBackend->createCalendar($principalUri, $calendarUri, [
Did you try using calling the SabreDAV server instead of calling the backend directly? Seems like it would be more fool-proof and easier to have common code with contacts export?
```php
$resourceType = ['{DAV:}collection', '{urn:ietf:params:xml:ns:caldav}calendar'];
$this->sabreDavServer->createCollection($calendarUri, new MkCol($resourceType, $properties));
```
and for calendar objects
```php
$this->sabreDavServer->createFile($uri, $data);
```

2022-02-24 08:47 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			? '-//SabreDAV//SabreDAV ' . SabreDavVersion::VERSION . '//EN'
Let's use our own `PRODID` so we know where the calendar comes from.
For reference:
https://github.com/nextcloud/server/blob/6da8a6d62adde9b1ed011a7a18d43984cf5a27a8/apps/dav/lib/CalDAV/BirthdayService.php#L266

2022-02-24 09:47 UTC, come-nc requested changes
Nice work, and good job on the unit test!

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +		throw new CalendarMigratorException();
Please invert the if and throw early it’s way easier to read.

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +					// Allow this exception as invalid (e.g. deleted) calendars are not to be exported
```suggestion
					// Allow this exception as invalid (e.g. deleted) calendars are not to be exported
					return null;
```

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			$output->writeln("<error>Error exporting <$userId> calendars</error>");
Please let the exception throw so that the migration service may chose to abort export.

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +		$calendarTimezones = array_values(array_filter(
array_values not needed since this var is only used for foreach

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			$this->calDavBackend->deleteCalendar($calendarId, true);
Please report this error in the output.

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +				throw new FilesystemException("Failed to read file: \"$filename\"");
pass $e as previous exception for trace?

2022-02-24 09:47 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			if ($exportDestination->addFileContents(CalendarMigrator::EXPORT_ROOT . $filename, $vCalendar->serialize()) === false) {
Please import relevant Application class and use Application::APP_ID as root folder for everything.
So calendars would go in /{Application::APP_ID}/calendars

2022-02-25 04:07 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +use function Safe\substr;
This was intended to have errors thrown instead of returning false as detailed in https://github.com/thecodingmachine/safe

2022-02-25 04:09 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +		$calendarId = $this->calDavBackend->createCalendar($principalUri, $calendarUri, [
I did not, what do others think @ChristophWurst @miaulalala ?

2022-02-25 04:12 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +				throw new FilesystemException("Failed to read file: \"$filename\"");
This exception would actually never be thrown as I checked again, so I changed it to throw on any Throwable

2022-02-25 08:52 UTC, tcitworld commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +use function Safe\substr;
Okay, I thought it was just a wrong IDE import. It might be worth it to catch this exception correctly then?

2022-02-28 09:23 UTC, come-nc requested changes

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			throw new CalendarMigratorException();
```suggestion
			throw new CalendarMigratorException('Failed to get unique calendar URI', 0, $e);
```

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			throw new CalendarMigratorException();
Why catch and rethrow the same class here?

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +				throw new CalendarMigratorException();
Fill the message for exceptions it will help debug.

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			$output->writeln('No version for ' . static::class . ', skipping import…');
This is inconsistent with setting $this->mandatory to true.
I would vote for leaving mandatory to false as it should not hurt to import a user which comes from an instance without this migrator.

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +				throw new CalendarMigratorException();
Same as other places, please put a message, and pass $e as $previous parameter of the constructor.

2022-02-28 09:23 UTC, come-nc commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +					throw new CalendarMigratorException();
Set a message

2022-02-28 09:23 UTC, come-nc commented on lib/public/Calendar/ICalendar.php
> +	public function getUri();
As this is a new function, please strong type.
```suggestion
	public function getUri(): string;
```

2022-03-02 01:59 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			$output->writeln('No version for ' . static::class . ', skipping import…');
Removed the mandatory override

2022-03-02 01:59 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +			throw new CalendarMigratorException();
Was supposed to be cleaned up, and now it is

2022-03-03 08:24 UTC, come-nc approved these changes

2022-03-08 02:16 UTC, Pytal commented on apps/dav/lib/UserMigration/CalendarMigrator.php
> +		$calendarId = $this->calDavBackend->createCalendar($principalUri, $calendarUri, [
Since this PR is only for calendar we can keep the calendar-specific way for now and add the shared abstraction in a separate PR in preparation for contacts which will be done next

2022-03-10 10:19 UTC, miaulalala approved these changes

2022-03-10 19:34 UTC, merged

2022-03-10 19:35 UTC, Pytal commented
Code may be shared with CalendarMigrator for future work on https://github.com/nextcloud/server/issues/564

The suggestion in https://github.com/nextcloud/server/pull/30963#discussion_r813653699 will be trialed in a future ContactsMigrator