Fix for #3112
nextcloud/server pull request #3113
Opened 2017-01-17 09:00 UTC by LeCoyote

Adds support for filename pattern exclusion in integrity check. Allows ignoring of Gentoo's webapp files.

2017-01-17 09:03 UTC, nickvergessen commented
@LeCoyote thanks for your patch, can you sign-off your commit please?
For more information see: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

2017-01-17 09:31 UTC, LeCoyote commented
I can, but the code is not mine so I do not wish to claim any undue credit for this. Is there a standard way to mention this in the commit message, in addition to the signature?

2017-01-17 09:47 UTC, nickvergessen commented
So where is the code from?

2017-01-17 09:52 UTC, ChristophWurst commented
> So where is the code from?

Taken from https://github.com/owncloud/core/pull/26782

2017-01-17 09:53 UTC, LeCoyote commented
I realize I only mentioned this in the bug report. The code is from the owncloud repository, so at least license won't be a problem, right?

2017-01-17 09:55 UTC, nickvergessen commented
In this case you can still sign-off, because the sign-off does not mean "I'm the author", but "I tried my best to check that the license of the patch is compatible with the license Nextcloud is shipped with."

2017-01-17 10:07 UTC, LeCoyote commented
Commit message should now be signed. Sorry about the noise, my git skills obviously need some polishing…

2017-01-17 13:42 UTC, LeCoyote commented
Not sure what the mysqlmb4 test is about, but the (finally clean) patch doesn't change anything sql-related. If there's anything I need to change in the PR, just let me know :)

2017-01-26 04:33 UTC, MorrisJobke commented
> LeCoyote commented 9 days ago
> Not sure what the mysqlmb4 test is about

Ignore it - this sadly happens from time to time :(

2017-01-26 04:40 UTC, MorrisJobke commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +			['.webapp-owncloud-obee', false],
The tests are with `owncloud` but the one listed above is with `nextcloud`. This looks 🐟y

2017-01-26 10:20 UTC, LeCoyote commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +			['.webapp-owncloud-obee', false],
Meh… should have noticed that, my bad. Fixed now.

2017-01-26 21:49 UTC, MorrisJobke commented
@LukasReschke Could you check this out? Just to be sure, that verification still works 😉

2017-02-20 12:19 UTC, LukasReschke requested changes

2017-02-20 12:19 UTC, LukasReschke commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +			return false;
There's no unit test for this case.

2017-02-20 12:19 UTC, LukasReschke commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		'/^\.webapp-nextcloud-.*/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
Please be more specific on the regular expression here. Otherwise a file such as `.webapp-nextcloud-foo.php` could be uploaded and may be interpreted.

2017-02-20 12:21 UTC, LukasReschke commented
Also as usual my remark: I have very few understanding why packaging tools decide to randomly patch stuff in the software. Also as this will break if someone wants to use the Nextcloud updater etc…

2017-02-20 17:18 UTC, LeCoyote commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		'/^\.webapp-nextcloud-.*/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
As I said, the code is from owncloud. I'm happy to change that though.

2017-02-20 17:19 UTC, LeCoyote commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +			return false;
What about tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php ?
I've never looked into unit tests before, some guidance would be appreciated :)

2017-02-20 17:26 UTC, LeCoyote commented
> Also as usual my remark: I have very few understanding why packaging tools decide to randomly patch stuff in the software.
The packaging tools doesn't patch anything. It just leaves a file in the folder. The counter-argument here might be that NC is a little too picky here. Why fail the integrity test without making it an option for the admin to mark a file as safe?
The updater issue will be the same with any package manager, it's not Gentoo-specific.

2017-09-13 15:30 UTC, MorrisJobke commented
> Also as usual my remark: I have very few understanding why packaging tools decide to randomly patch stuff in the software. Also as this will break if someone wants to use the Nextcloud updater etc…

As this does not seem to be a solution that we would like to accept. I will close this PR here. Thanks for contributing anyway @LeCoyote

2017-09-13 15:30 UTC, closed without merging

2017-10-31 10:26 UTC, okias commented
@MorrisJobke may I ask about some constructive idea, which you might accept? After more than year, wwe still have broken integrity check in Gentoo https://github.com/nextcloud/server/issues/3112

2017-10-31 11:23 UTC, svoop commented
A constructive idea which we could contribute to would indeed be very welcome. The problem with the status quo: The only way to get rid of the warning is to disable the integrity check altogether which will lead to potentially dangerous Nextcloud installations.

The `.webapp` files on Gentoo won't go away – ever. Waiting for this to happen is no option at all.

2018-02-25 12:16 UTC, jdunn0 commented
> Also as usual my remark: I have very few understanding why packaging tools decide to randomly patch stuff in the software. Also as this will break if someone wants to use the Nextcloud updater etc…

It's worth noting that the file `.webapp-nextcloud-[installedversion]` is a not related to a random patch, it's put there by webapp-config for the purpose of identifying the web app and the version installed in a specific directory (usually $vhost_root/htdocs/[appname]) so that webapp-config can handle removing the web app or upgrading the web app installed to that directory in the future.

The `.webapp-nextcloud-[installedversion]` file actually contains a list of installed files, what types they are and it appears a hash of each file so webapp-config can verify that a directory contains whats the web app it should when the user wants to remove or upgrade the web app in the directory.

webapp-config has a few types for files that specific what permissions the file has and if it can be overwritten on upgrade.
Those types are owner server-owned (owned by web server user), config-owned (owned by web server user and should not be replaced on upgrade) and virtual (files hard linked or copied from `/usr/share/webapps/[app name]/[version] that are usually owned by root).
For directories, the same applies except instead of virtual there is default-owned which are directories that by default are owned by root.

Thus to update the files and directories with a type of virtual or default-owned then you have to use webapp-config (either manually or automatically when run by portage after installing a new version) as the NextCloud updater will not have the permissions to do so as these files and directories are usually owned by root.

It seems most of the functions provided by the NextCloud updater and the Integrity Check are not necessary when using Portage and webapp-config to install and update NextCloud.

The only thing that the Integrity Check does that Portage and webapp-config do not do is to make sure that every file in the NextCloud directory is suppose to be there so if some extra file appears due a mistake or via malicious code then the NextCloud administrator could be notified about it.
So the Integrity checker should just ignore the `.webapp-nextcloud-[installedversion]` file as it does other files like `.DS_Store` and `Thumbs.db`.
I listed a couple ways to do that on issue #3112 that might work better, another person also posted a better pattern for the code in this pull request to use so instead of exclude all files that start with `.webapp-nextcloud-`, it does a better job at only matching the correct file.