Add optional WebDav propfind properties to count sub elements
nextcloud/server pull request #31193
Opened 2022-02-15 15:52 UTC by eneiluj

This allows requesting `{http://owncloud.org/ns}subfolders` and `{http://owncloud.org/ns}subfiles` PROPFIND properties which results in getting the number of files and directories contained by the element:
``` xml
<oc:subfolders>10</oc:subfolders>
<oc:subfiles>58</oc:subfiles>
```
This can be useful in a folder tree view of a WebDav client to know in advance if a directory can be expanded without having to use depth=2 and make the Dav response potentially a lot bigger.

2022-02-15 16:08 UTC, eneiluj commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const SUBFOLDER_COUNT_PROPERTYNAME = '{http://owncloud.org/ns}subfolders';
I just copied an existing one and did not pay attention. I'll change it to nc. Thanks for the remark.

2022-02-15 16:19 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +					if ($child instanceof Directory) {
```suggestion
					if ($child instanceof \OCA\DAV\Connector\Sabre\Directory) {
```

2022-02-15 16:19 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +					if ($child instanceof File) {
```suggestion
					if ($child instanceof \OCA\DAV\Connector\Sabre\File) {
```

2022-02-16 08:15 UTC, tobiasKaminsky commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +				foreach ($node->getChildren() as $child) {
With this approach two times full loop over getChildren is needed.
Is it possible to combine this do only one loop if SUBFILE_COUNT_PROPERTYNAME or SUBFOLDER_COUNT_PROPERTYNAME is used?
Then within in this single loop you can count both, files and folders and return depending on the query.

Should be way faster/less cost intensive in all cases.

2022-02-16 09:03 UTC, PVince81 commented
@eneiluj once the spec is clear, please also add those to the documentation

2022-02-16 09:34 UTC, eneiluj commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +				foreach ($node->getChildren() as $child) {
it is possible to factorize indeed. Thanks for the remark.

2022-02-16 09:35 UTC, eneiluj commented
@PVince81 Sure.
And if you have a better idea for the prop names, fine by me.

2022-02-21 11:54 UTC, juliushaertl commented
How about contained-file-count and contained-folder-count for the naming?

2022-03-18 15:12 UTC, tcitworld requested changes

2022-03-18 15:12 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +				|| in_array(self::SUBFILE_COUNT_PROPERTYNAME, $requestProperties, true)) {
```suggestion
				|| in_array(self::SUBFOLDER_COUNT_PROPERTYNAME, $requestProperties, true)) {
```

Also using `array_intersect` might be faster than the OR statement since most queries will execute both of the conditions.

2022-03-20 10:22 UTC, juliushaertl commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +			$requestProperties = $propFind->getRequestedProperties();
```suggestion
			$requestProperties = $propFind->getRequestedProperties();
			$nbFiles = null;
			$nbFolders = null;
```

To avoid a potential undefined variable warning

2022-03-20 10:22 UTC, juliushaertl approved these changes

2022-03-21 09:02 UTC, tcitworld approved these changes

2022-03-21 10:33 UTC, merged

2022-03-21 10:34 UTC, eneiluj commented
/backport to stable23

2022-03-21 10:34 UTC, eneiluj commented
/backport to stable22