Add Transactional trait for atomic DB operations
nextcloud/server pull request #31205
Opened 2022-02-16 09:55 UTC by ChristophWurst

2022-02-16 10:51 UTC, nickvergessen approved these changes
LGTM it's quite simple and might work for most places at least

2022-02-17 08:45 UTC, come-nc requested changes

2022-02-17 08:45 UTC, come-nc commented on lib/public/AppFramework/Db/Transactional.php
> +trait Transactional {
I’ve seen all interfaces being named IStuff and traits TThing, so this should be TTransactional I think?

2022-02-17 08:45 UTC, come-nc commented on lib/public/AppFramework/Db/Transactional.php
> +	 * @psalm-return T
Please add a small description of what is returned by the method

2022-02-17 10:13 UTC, come-nc approved these changes

2022-02-17 10:27 UTC, CarlSchwan approved these changes
Very nice 👍

2022-02-17 11:48 UTC, merged