brute force protection for api calls
nextcloud/server pull request #3120
Opened 2017-01-17 13:44 UTC by schiessle

Add a new annotation "BruteForceProtection" to enable brute force protection for API calls. Additionally the annotation can have a parameter to define the action to block different actions idependently.

ToDo:

- [ ] Unit Tests
- [ ] Adjust login code to use the new annotation

cc @LukasReschke @nickvergessen

2017-01-17 13:46 UTC, nickvergessen commented on lib/private/AppFramework/Utility/ControllerMethodReflector.php
> +		return array_key_exists($name, $this->annotations);
I never understood why people use array_key_exists, just use `return isset($this->annotations[$name]);`?

2017-01-17 13:47 UTC, nickvergessen requested changes

2017-01-17 13:47 UTC, nickvergessen commented on lib/private/Security/Bruteforce/Throttler.php
> +	public function sleepDelay($ip, $action = 'JUSTFORTESTING') {
This kills the default value, so all requests only use entries with `JUSTFORTESTING` action.

2017-01-17 13:57 UTC, schiessle commented on lib/private/AppFramework/Utility/ControllerMethodReflector.php
> +		return array_key_exists($name, $this->annotations);
because:

`isset(array['key']))` will return false if the value of the key is null (['key' => null]).

2017-01-17 13:57 UTC, schiessle commented on lib/private/Security/Bruteforce/Throttler.php
> +	public function sleepDelay($ip, $action = 'JUSTFORTESTING') {
fixed

2017-01-17 16:14 UTC, nickvergessen commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +	/** @var  Throttler | \PHPUnit_Framework_MockObject_MockObject */
no spaces around the `|`:
https://www.phpdoc.org/docs/latest/guides/types.html#multiple-types-combined

2017-01-17 16:15 UTC, nickvergessen commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +		/** @var ControllerMethodReflector | \PHPUnit_Framework_MockObject_MockObject $reader */
same here

2017-01-17 16:24 UTC, schiessle commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +	/** @var  Throttler | \PHPUnit_Framework_MockObject_MockObject */
Until now I used this always with spaces. PHPStorm doesn't have a issue with it and your link also doesn't say that it is mandatory that there are no spaces, so I assume that it is "just" a coding style issue... Correct me if I'm wrong.

2017-01-17 16:43 UTC, LukasReschke commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +	/** @var  Throttler | \PHPUnit_Framework_MockObject_MockObject */
> If you look at our code it is at least 50:50

And if you look just along the lines above it is all written together. So let's be consistent here and not add yet another format into this file.

2017-01-18 08:22 UTC, schiessle commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +	/** @var  Throttler | \PHPUnit_Framework_MockObject_MockObject */
That's an argument. 😉

2017-01-18 08:35 UTC, schiessle commented
@LukasReschke @nickvergessen changed...

2017-01-18 09:00 UTC, nickvergessen approved these changes

2017-01-18 10:51 UTC, LukasReschke approved these changes
Good stuff and works nicely :) 🚀

2017-01-18 11:10 UTC, LukasReschke commented
Note that there may be some other things to consider, one of them is that you may in some cases couple this also with an user and not only an IP.

For example one may want to protect the Sharing API but targetting an IP here would be too generic. There we'd have to target on an user, and also we may want to have a parameter that allows the amount of specific actions before something is considered malicious.

2017-01-18 16:23 UTC, merged