handle invilid type when listing directory in smb
nextcloud/server pull request #31215
Opened 2022-02-16 14:25 UTC by icewind1991

just handle it as an empty directory

Signed-off-by: Robin Appelman <robin@icewind.nl>

2022-02-16 14:40 UTC, CarlSchwan approved these changes

2022-02-17 08:39 UTC, come-nc requested changes

2022-02-17 08:39 UTC, come-nc commented on apps/files_external/lib/Lib/Storage/SMB.php
> +				return;
This does not respect the return type: `@return \Icewind\SMB\IFileInfo[]`
Reading the rest it seems this is actually a generator?
So `@return \Generator<\Icewind\SMB\IFileInfo>` would be correct.

2022-02-18 15:42 UTC, icewind1991 commented on apps/files_external/lib/Lib/Storage/SMB.php
> +				return;
Yes, I believe that this return type hint wasn't an option when originally added

2022-02-21 10:09 UTC, come-nc approved these changes

2022-03-17 16:25 UTC, merged