Temporary passwords for public non-anonymous protected shares (ie: files shared with an email recipient).
nextcloud/server pull request #31220
Opened 2022-02-16 17:36 UTC by StCyr

This PR implements https://github.com/nextcloud/server/issues/31005

With this change, passwords protecting public non-anonymous shares become temporary: They have an expiration time and a background job changes them to some random undisclosed value when their expiration time is passed.

To request a new temporary password, recipients use a new "request password" button that is added to protected public non-anonymous shares' authentication page. This button serves the same functionality as the "request password" button implemented by Talk (ie: To identify the person requesting the password), except that, here, the person identifies herself by proving she knows the email address with which the file is shared with (ie: she types her email address, and if it matches the email address with which the file is shared the person is considered "identified" and a new temporary password is sent to that email address). Of course, identification via a Talk session takes precedence when the share has its "video verification" attribute checked.

I'm waiting for your reviews and welcome your comments which I hope will be constructive 

Cyrille

2022-02-16 18:31 UTC, nickvergessen commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +			// QUESTION: SHALL I RESPECT PASSWORD POLICY HERE (WHEN USED)?
I think you have to

2022-02-17 10:03 UTC, StCyr commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +			// QUESTION: SHALL I RESPECT PASSWORD POLICY HERE (WHEN USED)?
It seems much more easier than I thought 😅

2022-03-01 09:37 UTC, PVince81 commented
did you forget to push something ?
<img width="554" alt="image" src="https://user-images.githubusercontent.com/277525/156143513-9463e939-61ce-43fe-867b-4dec2d8550ca.png">

- [ ] please run `build/autoloaderchecker.sh`

2022-03-01 09:44 UTC, PVince81 commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +class ResetExpiredPasswordsJob extends TimedJob {
you can ignore these warnings, we'll need to fix the base class

2022-03-01 09:47 UTC, PVince81 commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +		// I THINK SO, BECAUSE EVERYTHING HAPPENS ON THE SERVER, HENCE ON THE SAME TZ
usually the timezone of server is supposed to be UTC, so should be fine

2022-03-01 09:48 UTC, PVince81 commented on apps/files_sharing/lib/Controller/ShareController.php
> +	$this->eventDispatcher->dispatchTyped($event);
please fix indent

2022-03-01 09:48 UTC, PVince81 commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$password = $event->getPassword() ?? $password = \OC::$server->getSecureRandom()->generate(20);
there's a second "=" in the line, please double check

2022-03-01 09:49 UTC, come-nc commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$password = $event->getPassword() ?? $password = \OC::$server->getSecureRandom()->generate(20);
```suggestion
		$password = $event->getPassword() ?? \OC::$server->getSecureRandom()->generate(20);
```

2022-03-01 09:51 UTC, PVince81 commented
- [ ] BUG: enter key not working when entering email address to request from

2022-03-01 09:55 UTC, PVince81 commented
- [ ] BUG: need to clear the (public) session info as soon as opening the "request password" page

Steps:

1. Share a folder with user "another@example.com"
2. Set a password "test"
3. Open the email
4. Open the link
5. Enter the password "test" => this authenticates you for the link
6. Open the link again
7. Click "request access"
8. Enter email address

Expected result: receive email with new password
Actual result: no email and the share folder appears directly, because of the previous session data

2022-03-01 09:59 UTC, PVince81 commented on apps/files_sharing/lib/Controller/ShareController.php
> +	protected function generatePassword() {
looks like this method is unused ?

2022-03-01 11:14 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$password = $event->getPassword() ?? $password = \OC::$server->getSecureRandom()->generate(20);
and inject in constructor instead of using `\OC::$server`

2022-03-01 14:27 UTC, PVince81 requested changes
I've added some comments and found some issues, please have a look

2022-03-01 14:27 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
this will likely break implementations and might need a new version of the interface

wondering if there's another way by having or deriving this info from the IShare object directly

2022-03-01 14:27 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function validateIdentity(IShare $share, $identityToken);
this will need a new version of the interface to add new methods

I know we have multiple implementations of share provider, but not sure if we have multiple share managers or just one

2022-03-01 14:28 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
before adding a new interface let's check if there are really more implementations of IManager or just one

2022-03-01 20:25 UTC, StCyr commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +class ResetExpiredPasswordsJob extends TimedJob {
Hmm I've a general remark about the necessity of this background job: 

I've created another branch (https://github.com/nextcloud/server/commits/enhancement/31005/temporary-passwords-v2), building on this one and adding 2 commits, where password's expiration time is checked in IManager::checkPassword (see https://github.com/nextcloud/server/commit/576de4bb8098777b4725921604be259add0eb95a) hence making this background job unnecessary anymore.

I believe it's a better solution than this background job. Could you please have a look and take a stand?

2022-03-01 20:39 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareController.php
> +	protected function generatePassword() {
It's declared abstract in AuthPublicShareController.php and used there.

2022-03-01 20:52 UTC, StCyr commented on core/js/publicshareauth.js
> +	var passwordRequestButton = document.getElementById('request-password-button-not-talk');
if you want. But, I believe it's best to keep it technology-agnostic for if later we implement other means to request passwords (eg: by sms)

2022-03-01 21:02 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareController.php
> +	$this->eventDispatcher->dispatchTyped($event);
fixed in 2bc5788ef0599c5290f0e27557bfa63cd1372cee

2022-03-01 21:02 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$password = $event->getPassword() ?? $password = \OC::$server->getSecureRandom()->generate(20);
fixed in 2bc5788ef0599c5290f0e27557bfa63cd1372cee

2022-03-01 21:02 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareController.php
> +		$password = $event->getPassword() ?? $password = \OC::$server->getSecureRandom()->generate(20);
fixed in 2bc5788ef0599c5290f0e27557bfa63cd1372cee

2022-03-02 15:32 UTC, PVince81 commented on apps/files_sharing/lib/Controller/ShareController.php
> +	protected function generatePassword() {
alright, I didn't realize that ShareController was already extending it as I didn't see it in the diff. all good

2022-03-02 15:36 UTC, PVince81 commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +class ResetExpiredPasswordsJob extends TimedJob {
@StCyr yes, let's use your approach without the background job which checks on-demand

2022-03-02 15:36 UTC, PVince81 commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +		// I THINK SO, BECAUSE EVERYTHING HAPPENS ON THE SERVER, HENCE ON THE SAME TZ
please remove the comment from the code when ready :smile:

2022-03-02 16:09 UTC, PVince81 commented on apps/files_sharing/lib/Controller/ShareController.php
> +	protected function validateIdentity(string $identityToken): bool {
please remove the type hint to allow null

2022-03-04 10:51 UTC, PVince81 commented
it might be ok to extend the IManager interface as it's only "for use", see new discussion here: https://github.com/nextcloud/server/pull/31447

2022-03-04 10:51 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
might be ok, see https://github.com/nextcloud/server/pull/31447

2022-03-06 19:38 UTC, StCyr commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +		// I THINK SO, BECAUSE EVERYTHING HAPPENS ON THE SERVER, HENCE ON THE SAME TZ
Well, the background job idea is discarded => https://github.com/nextcloud/server/pull/31220#discussion_r817814581

2022-03-06 19:41 UTC, StCyr commented on apps/files_sharing/lib/BackgroundJob/ResetExpiredPasswordsJob.php
> +class ResetExpiredPasswordsJob extends TimedJob {
on-demand check implemented (via 71ae5a077cb788a16d5f90ba2d958eb208900e5f and 9ef1c59c61249d1818087526f0d3b01ab4790196), together with configurable password expiration time

2022-03-06 19:54 UTC, StCyr commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
Hmmm.... Anyway, I'm wondering if this new feature (ie: not sending a temporary password upon public authenticate share creation) is really needed... Eventually, it's not that much of an issue if a temporary password is sent to the recipient upon share creation, rather than waiting for the recipient to explicitely requesting it.

I'm thinking about reverting this change. What's your opinion?

2022-03-07 15:23 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
there are scenarios where one might want to manually set a specific password to make it easier for the other person to type (or it's something they gave them already on paper or another medium), so we should allow for still supporting such scenarios

now, I'm not sure if this applies to this piece of code specifically ?

2022-03-09 14:53 UTC, StCyr commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
That's my point: I initially thought it was necessary to drop support for this scenario. So, we are now on the same line and commit ea4531aaaa6eb9fb3859e05b69ab773bfbfe7437 restores that functionality

2022-03-09 14:53 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareController.php
> +	protected function validateIdentity(string $identityToken): bool {
you mean the `@return bool`?

2022-03-09 15:42 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
perfect, thanks a lot!

2022-03-13 08:45 UTC, StCyr commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
Hi @PVince81,

I'm unresolving this discussion because we would like to implement this feature of not sending the password via email in some cases eventually, and we understand that modifying the IManager interface is not an issue.

Also, we would like to make it clear that this PR, as it is currently implemented, completly drops support for permanent passwords for shares shared via email (except for shares created before the implementation of this PR): Once this PR gets implemented, all passwords set to protect a share shared via email will be temporary and expire after the delay specified by the `share_temporary_password_expiration_interval` system value, or 15 minutes by default; Your comment  https://github.com/nextcloud/server/pull/31220#discussion_r820812356 (specifically the phrase `(or it's something they gave them already on paper or another medium)`) makes us think we might not be aligned on this point.

2022-03-14 17:14 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
hi Cyrille, you're right about misalignment, thanks for spotting

I'll get this clarified internally as this would be a change of behavior

2022-03-17 07:27 UTC, skjnldsv commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
Hey @StCyr, after a bit of thoughts, we decided we would need a config switch.
Old behaviour would be off by default. :)

2022-03-18 14:36 UTC, StCyr commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
> Hey @StCyr, after a bit of thoughts, we decided we would need a config switch. Old behaviour would be off by default. :)

A new checkbox in the share menu?

![image](https://user-images.githubusercontent.com/8179031/159022812-8db57106-dcb1-40ed-a3ba-96e2354d5077.png)

2022-03-22 08:38 UTC, PVince81 commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
rather a config switch in config.php to switch it globally

2022-03-23 21:19 UTC, StCyr commented on lib/public/Share/IManager.php
> +	public function updateShare(IShare $share, bool $sendPassword = false);
implemented in c9940b194af8c59e0355c1d2660e614c67d99af6

I believe the PR is feature complete now. Do you want me to rebase and squash it?

2022-03-25 13:33 UTC, StCyr commented
> @StCyr when I try setting up Nextcloud I get this:
> 
> ```
> PHP Fatal error:  Declaration of OCA\FederatedFileSharing\FederatedShareProvider::create(OCP\Share\IShare $share) must be compatible with OCP\Share\IShareProvider::create(OCP\Share\IShare $share, bool $sendPassword = true) in /srv/www/htdocs/server/apps/federatedfilesharing/lib/FederatedShareProvider.php on line 171
> Installation failed
> ```
> 
> can you have a look ?
> 
> once this is resolved I think you can squash

Fixed in afbda38543e99e03d931dbb62cdcf07d9f3d7b48 

But I've seen that spreed's RoomShareProvider also implements the IShareProvider interface... Maybe I should avoid modifying this interface eventually...

2022-03-31 07:49 UTC, StCyr commented
Hello @PVince81,

Shall I rebase and squash now?

Do you want me to write a summary of the functional changes that have been implemented? Something else?

2022-04-04 09:28 UTC, StCyr commented
Here's a summary of the functional changes implemented:

- files_sharing createShare API:
  make password temporary for email shares (unless otherwise instructed by system config)
- files_sharing updateShare API:
  make password temporary for email shares (unless otherwise instructed by system config)
- sharebymail create: 
	Only send password when permanent password is enforced via system config; When using temporary passwords, 
	the password shall only be sent to the guest when she requests it from the UI.
	Note that sharebymail's update() function isn't changed, allowing the share owner to set an arbitrary temporary
	password and have it sent to the guest anyway.
- Manager checkPassword:
	When verifying the password of a public share, make sure it hasn't expired first.
- showShare API:
	Changes to allow guest to ask a temporary password. To do so, guest will do the following:
		1- Click on a new "Request password" button
		2- Upon clicking on the button, the guest is prompted to enter his email address
			2a- If the entered email address matches the share's shared_with property, a new temporary
			    share password is generated and sent to the user via email.
			2b- If the entered email address doesn't match the share's shared_with property, the guest
			    is presented with an error message telling him that he's not authorized to request a
			    password for this share.
		3- At any time, the user can click on a new "Back" button to return to the password prompt page.

2022-04-07 13:59 UTC, PVince81 commented
@StCyr CI is failing, can you squash and rebase ?

2022-04-07 14:00 UTC, PVince81 commented
never mind, I see you did one hour ago. weird

2022-04-07 14:01 UTC, PVince81 commented
I saw a bunch of those, possibly related ?
```
2) OCA\Files_Sharing\Tests\Controller\ShareAPIControllerTest::testUpdateLinkShareEnablePublicUpload with data set #0 (null, 'true', null, 'password')
Undefined variable $shareType
```

2022-04-07 15:51 UTC, PVince81 commented
@StCyr we'll take it from here, thanks a lot!

2022-04-07 15:55 UTC, PVince81 commented on apps/sharebymail/tests/ShareByMailProviderTest.php
> -		$this->mailer->expects($this->once())->method('send');
is this obsolete or more difficult to test ?

2022-04-07 15:57 UTC, PVince81 commented on apps/sharebymail/tests/ShareByMailProviderTest.php
> -		$this->mailer->expects($this->once())->method('send');
probably we should duplicate the test to test the old behavior when the setting is set

2022-04-07 16:05 UTC, PVince81 commented
fixed the issue, rebased and squashed

next up: check the last issues, I hope at least CI passes now

2022-04-07 18:28 UTC, PVince81 commented
ran php:cs, rebuilt assets, merged suggestions from @CarlSchwan 

now hoping for green CI

2022-04-07 18:31 UTC, PVince81 commented
not that easy
```
"PHP Fatal error:  Declaration of OC\Share20\Share::setPasswordExpirationTime($passwordExpirationTime = null) must be compatible with OCP\Share\IShare::setPasswordExpirationTime($passwordExpirationTime = null): OCP\Share\IShare in /home/runner/work/server/server/lib/private/Share20/Share.php on line 469"
```

I'll have a look later

2022-04-07 19:01 UTC, CarlSchwan commented on lib/public/Share/IShare.php
> +	public function setPasswordExpirationTime($passwordExpirationTime = null): self;
```suggestion
	public function setPasswordExpirationTime($passwordExpirationTime = null): IShare;
```

2022-04-07 19:03 UTC, CarlSchwan commented on lib/public/Share/IShare.php
> +	public function getPasswordExpirationTime(): string;
```suggestion
	public function getPasswordExpirationTime(): ?string;
```

2022-04-07 19:10 UTC, CarlSchwan commented on lib/public/Share/IShare.php
> +	 * @return self The modified object
```suggestion
	 * @return self The modified object
	 * @since 24.0.0
```

2022-04-07 19:10 UTC, CarlSchwan commented on lib/public/Share/IShare.php
> +	 * Get the password's expiration time of this share.
```suggestion
	 * Get the password's expiration time of this share.
	 * @since 24.0.0
```

2022-04-07 19:10 UTC, CarlSchwan commented on lib/public/AppFramework/AuthPublicShareController.php
> +	 * @since 14.0.0
```suggestion
	 * @since 24.0.0
```

Should this event be part of the public API?

2022-04-09 20:24 UTC, StCyr commented
Hi @PVince81 @CarlSchwan,

I've fixed the unit tests (and added a new one to validate that password is not sent via email when temporary passwords are enabled).

Also, the test `testCreateSendPasswordByTalkWithEnforcedPasswordProtection` was failing because of an unexpected functional change imho. So, I've updated the function `ShareByMailProvider::create()` to allow sending password to the share owner in that case.

2022-04-11 14:50 UTC, PVince81 commented
@StCyr thanks a lot!

2022-04-11 16:23 UTC, CarlSchwan approved these changes

2022-04-11 20:06 UTC, StCyr commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			// Catches invalid format for system value 'share_temporary_password_expiration_interval'
I have added a logging and squashed my commits

2022-04-11 21:14 UTC, CarlSchwan commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			// Catches invalid format for system value 'share_temporary_password_expiration_interval'
Ok cool, i will merge this tomorrow morning unless Vincent bewt me to it 😉

2022-04-12 07:45 UTC, PVince81 approved these changes
:+1:

2022-04-12 07:46 UTC, PVince81 commented
failing test unrelated and has just been fixed on master

merging

2022-04-12 07:46 UTC, merged

2022-04-12 20:34 UTC, PVince81 commented
seems a bug has sneaked in, the expiration date column never changes for me on master, raised here: https://github.com/nextcloud/server/issues/31951

2022-04-12 20:39 UTC, PVince81 commented
and some UX feedback: https://github.com/nextcloud/server/issues/31952