🚧 Fine grained filesystem setup 🚧
nextcloud/server pull request #31265
Opened 2022-02-18 15:07 UTC by icewind1991

- [ ] Unify/cleanup filesystem setup
  - [ ] Move root mount setup to mountprovider
  - [ ] Move fs setup/teardown handling to it's own class
  - [ ] Call new fs setup from all the old places to remain compatible
- [ ] Cache mountprovider for each mount for user
- [ ] Setup only mounts from relevant mount providers when accessing the filesystem
- [ ] Ensure cached mounts get updated when needed

2022-03-17 19:13 UTC, icewind1991 commented
Ok, I think this is done for review/testing

Particular attention should be given to situations that change what mounts are available for a user (adding/removing shares/external storages/etc) and making sure file listings reflect these changes

2022-03-21 11:27 UTC, come-nc commented on lib/private/Files/Config/UserMountCache.php
> +		}
This is hard to read.
I tried refactoring into a do…while with an exit condition but the handling of the last steps is hard to understand.
Also, it seems dirname may end on `\` rather than `/` on windows: https://www.php.net/manual/en/function.dirname.php

2022-03-21 11:27 UTC, come-nc commented on lib/private/Files/Node/Root.php
> +						return $folder;
Is it returned and not cached on purpose here? (Same question for line 395)

2022-03-21 11:27 UTC, come-nc commented on lib/private/Files/SetupManager.php
> +		return in_array($user->getUID(), $this->setupUsers, true);
How often are those used? Would it make sense to store uids as keys in the array to speed up look up and avoid in_array?
 ```suggestion
		return $this->setupUsers[$user->getUID()] ?? false;
```

2022-03-24 14:03 UTC, PVince81 commented on lib/private/Files/Config/UserMountCache.php
> +	public function getMountsInForPath(IUser $user, string $path): array {
what are "mounts in for path" ? if not a typo, please add a PHP Doc

2022-03-24 14:07 UTC, PVince81 commented on lib/private/Files/SetupManager.php
> +	private function userFullySetup(IUser $user) {
name is confusing, it half sounds like `isUserFullySetup()` but the code is performing an action

did you mean `fullySetupUser($user)` ?

2022-03-24 14:08 UTC, PVince81 commented on lib/private/Files/SetupManager.php
> +			$this->cache->set($user->getUID(), true, 5 * 60);
please make this configurable in config.php

am also wondering if we should make the configuration value "0" mean "caching logic fully disabled" if easy to do

2022-03-24 14:10 UTC, PVince81 commented on lib/private/Files/SetupManager.php
> +				if (!in_array($cachedMount->getMountProvider(), $setupProviders)) {
no strict comparison needed I guess ?

2022-03-24 14:12 UTC, PVince81 reviewed
code looks good overall, see some minor comments and also the part about making the timeout configurable

2022-03-24 14:29 UTC, PVince81 commented
- [ ] BUG: rename received share in web UI and click on it immediately: current folder opens, not subdir. after reclicking it navigates in. perhaps the cache clear is slightly delayed ?

2022-03-24 14:49 UTC, icewind1991 commented on lib/private/Files/Config/UserMountCache.php
> +		}
Paths in nextcloud are always normalized to `/`

2022-03-24 15:19 UTC, icewind1991 commented
> BUG: rename received share in web UI and click on it immediately: current folder opens, not subdir. after reclicking it navigates in. perhaps the cache clear is slightly delayed ? (reproduced multiple times, even after waiting for 6s)

Should be fixed now

2022-03-24 15:25 UTC, come-nc commented on lib/private/Files/Config/UserMountCache.php
> +		}
Please at least add a comment explaining what this loop does. If possible refactor to have an exit condition other than true.

2022-03-24 16:24 UTC, artonge commented on apps/files_sharing/lib/SharedMount.php
> +		$this->eventDispatcher->dispatchTyped(new InvalidateMountCacheEvent($this->user));
Same, could you explain what is the purpose of `InvalidateMountCacheEvent`?

2022-03-24 16:29 UTC, icewind1991 commented on apps/files_external/lib/Service/StoragesService.php
> +		$this->eventDispatcher->dispatchTyped(new InvalidateMountCacheEvent(null));
This forces a full setup to be done the next time (which also rebuilds the cache) since the available external storages for a user might have changed

2022-03-24 16:30 UTC, icewind1991 commented on apps/files_sharing/lib/SharedMount.php
> +		$this->eventDispatcher->dispatchTyped(new InvalidateMountCacheEvent($this->user));
It signals that the available mounts might have changed so a full setup should be performed the next time

2022-03-24 16:35 UTC, PVince81 commented on lib/private/Files/SetupManager.php
> +				$this->cache->set($user->getUID(), true, 5 * 60);
you should actually use the value

2022-03-24 16:37 UTC, artonge requested changes

2022-03-24 16:37 UTC, artonge commented on lib/private/Files/Config/MountProviderCollection.php
> +		return $this->getMountsForFromProviders($user, $this->providers);
```suggestion
 		return $this->getUserMountsForProviders($user, $this->providers);
```

2022-03-24 16:37 UTC, artonge commented on lib/private/Files/Config/MountProviderCollection.php
> +		return $this->getMountsForFromProviders($user, $providers);
```suggestion
 		return $this->getUserMountsForProviders($user, $providers);
```

2022-03-24 16:39 UTC, artonge commented on lib/private/Files/Config/MountProviderCollection.php
> + 	public function getUserMountsForProviderClass(IUser $user, string $mountProviderClass): array {
Not sure where this is used, might need to rename where it is called too

2022-03-24 16:42 UTC, PVince81 approved these changes
:+1:

2022-03-24 16:42 UTC, artonge approved these changes

2022-03-24 16:43 UTC, Pytal approved these changes

2022-03-24 17:22 UTC, PVince81 commented
@icewind1991 phpcs unhappy, can you fix ?

2022-03-24 20:08 UTC, PVince81 commented
all necessary tests passed successfully in previous builds and my recent changes are not related to those

the last commit was to satisfy "checkers" and that one passes now

merging...

2022-03-24 20:08 UTC, merged