Add --dry-run option for AddMissingIndices cmd
nextcloud/server pull request #31304
Opened 2022-02-21 14:59 UTC by artonge

Signed-off-by: Louis Chemineau <louis@chmn.me>

2022-02-21 15:24 UTC, artonge commented on core/register_command.php
> +	$application->add(new OC\Core\Command\Db\AddMissingIndices(\OC::$server->get(\OC\DB\Connection::class), \OC::$server->get(\OC\DB\DryRunConnection::class), \OC::$server->getEventDispatcher()));
I might be missing a step to get this to work properly.

I get the following error when calling `occ`:

```
OCP\AppFramework\QueryException: Could not resolve params! in lib/private/AppFramework/Utility/SimpleContainer.php:138
```

No idea what I am doing wrong, I could use some PHP wizard.

2022-02-21 18:43 UTC, ChristophWurst requested changes
this works and the changes are minimal, but they come at a cost

if we can I would prefer to have something more future proof and maintainable.

2022-02-21 18:43 UTC, ChristophWurst commented on lib/private/DB/Connection.php
> +	public function setDryRun(bool $value) {
I don't think this is the right place to remember this

2022-02-21 18:43 UTC, ChristophWurst commented on core/Command/Db/AddMissingPrimaryKeys.php
> +		$this->dispatcher->addListener('\OC\DB\Migrator::executeSql', fn ($event) => $output->writeln($event->getSubject()));
is there any other way to structure this? the existing core code that we have to maintain is really painful to debug and change whenever we use this event indirection. take a look at the updater code for example and try to figure out how the pieces fit together.

moreover events identified by name/string are deprecated in symfony. hence we will have to restructure this code most certainly soon.

2022-02-21 18:46 UTC, ChristophWurst commented on lib/private/DB/Connection.php
> +	public function setDryRun(bool $value) {
to emphasize what this does: you are setting a property on a singleton. this is practically a global variable. your code will have side effects that not only influence the execution the main task here but anything else that gets triggered along that way.

move away from a global and pass this context-specific information into the method call where you invoke the migration.

2022-02-21 19:09 UTC, nickvergessen commented on lib/private/DB/Connection.php
> +	public function setDryRun(bool $value) {
I think this should be on the migrator or on the `migrateToSchema` function, not the DB connection "statefully" as it only affects schema changes?

2022-02-21 19:32 UTC, nickvergessen commented on lib/private/DB/Connection.php
> +	public function setDryRun(bool $value) {
I think this should be on the migrator or on the `migrateToSchema` function, not the DB connection "statefully" as it only affects schema changes?

2022-02-22 11:26 UTC, artonge commented on core/Command/Db/DryRunConnectionDecorator.php
> +	}
Copypasta from `OC\DB\Connection`. Would be better to not duplicate code but that would mean making the method public.

2022-02-22 11:33 UTC, artonge commented on lib/private/DB/Connection.php
> +	public function setDryRun(bool $value) {
Thanks for the input :)

I changed the approach and went for an almost decorator logic. There are still some caveats though, see other comments.

2022-02-22 11:36 UTC, artonge commented on core/Command/Db/AddMissingColumns.php
> +		$schema = new SchemaWrapper($this->wrapperConnection);
I had to store the original connection object into another property as I was getting a typing error at this line.

To go with the full decorator logic and prevent this, I would have to create an interface for the \OC\DB\Connection class.

2022-02-22 12:08 UTC, nickvergessen commented on core/Command/Db/DryRunConnectionDecorator.php
> +	}
Why do you want to add so much overhead when it could be done with a boolean directly inserted into the `migrateToSchema` method that is affected?

2022-02-22 12:13 UTC, nickvergessen commented on core/Command/Db/DryRunConnectionDecorator.php
> +	}
I noticed this complexity also when working on https://github.com/nextcloud/server/pull/30973 + https://github.com/nextcloud/activity/pull/722
So especially when it can be prevented by doing a boolean on the actual method, I think we should try to avoid it.
It's currently creating more pitfalls then it helps in the end :D

2022-02-22 12:25 UTC, ChristophWurst commented on core/Command/Db/AddMissingColumns.php
> +		$schema = new SchemaWrapper($this->wrapperConnection);
\OCP\IDBConnection?

2022-02-22 12:36 UTC, nickvergessen commented on core/Command/Db/AddMissingColumns.php
> +		$schema = new SchemaWrapper($this->wrapperConnection);
Doesn't really work. \OC\DB\ConnectionAdapter is a OCP\IDBConnection and takes \OC\DB\Connection as an argument.
\OC\DB\Connection extends \Doctrine\DBAL\Connection and is therefor fixed in some places and can not get return types, etc.

2022-02-22 13:01 UTC, artonge commented on core/Command/Db/DryRunConnectionDecorator.php
> +	}
> Why do you want to add so much overhead when it could be done with a boolean directly inserted into the `migrateToSchema` method that is affected?

The idea was to not have to edit every `migrateToSchema` call to pass a new value and to handle the returned value like so:

```php
$sqlQueries = $this->connection->migrateToSchema($schema->getWrappedSchema(), $dryRun);

if ($sqlQueries != null) {
	$output->write($sqlQueries);
}
```

I feel like it is much more maintainable to have a central place to handle this logic. Also, we don't rely on the hope that the next person who makes a change would remember to add this logic.

2022-02-22 18:43 UTC, nickvergessen commented on core/Command/Db/DryRunConnectionDecorator.php
> +	}
I think it's much more fragile to have hopes for a non break of the decoration pattern (and viola, it broke already with https://github.com/nextcloud/server/pull/30973 and the activity PR)

Calls to migrateToSchema should be rather limited and so I think this is the saver approach and also much better testable and easier to write tests for.

2022-02-24 11:56 UTC, ChristophWurst commented on core/Command/Db/AddMissingColumns.php
> +				if ($dryRun && $sqlQueries != null) {
```suggestion
				if ($dryRun && $sqlQueries !== null) {
```

2022-02-24 11:56 UTC, ChristophWurst commented on lib/private/DB/Connection.php
> +	 * @return string|null
document what this string is

2022-02-24 12:01 UTC, artonge commented on core/Command/Db/AddMissingColumns.php
> +				if ($dryRun && $sqlQueries != null) {
Oups, done

2022-02-24 12:01 UTC, artonge commented on lib/private/DB/Connection.php
> +	 * @return string|null
And done too :)

2022-02-24 12:38 UTC, nickvergessen approved these changes

2022-02-24 12:38 UTC, nickvergessen commented on core/Command/Db/AddMissingIndices.php
> +	private function addCoreIndexes(OutputInterface $output, bool $dryRun ) {
```suggestion
	private function addCoreIndexes(OutputInterface $output, bool $dryRun): void {
```

2022-02-24 12:38 UTC, nickvergessen commented on core/Command/Db/AddMissingColumns.php
> +	private function addCoreColumns(OutputInterface $output, bool $dryRun) {
```suggestion
	private function addCoreColumns(OutputInterface $output, bool $dryRun): void {
```

2022-02-24 12:38 UTC, nickvergessen commented on core/Command/Db/AddMissingPrimaryKeys.php
> +	private function addCorePrimaryKeys(OutputInterface $output, bool $dryRun) {
```suggestion
	private function addCorePrimaryKeys(OutputInterface $output, bool $dryRun): void {
```

2022-02-24 15:16 UTC, ChristophWurst approved these changes

2022-02-24 15:16 UTC, ChristophWurst requested changes
please squash? :)

2022-02-28 08:57 UTC, come-nc approved these changes

2022-02-28 08:59 UTC, ChristophWurst approved these changes

2022-02-28 08:59 UTC, merged