Fix #31303: Make reminder notification behaviour selectable..
nextcloud/server pull request #31337
Opened 2022-02-24 13:22 UTC by D0n1elT

Fixes https://github.com/nextcloud/server/issues/31303 and https://github.com/nextcloud/calendar/issues/3946.
 
![grafik](https://user-images.githubusercontent.com/16420080/155531821-ef86fd10-c50f-4082-a0da-2492b38e6a12.png)

I'm open for your opinions. ^^
And please check my spelling, I'm not native. :D

2022-02-24 14:11 UTC, tcitworld requested changes

2022-02-24 14:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +	public function processReminders(IConfig $config):void {
IConfig should be injected through autoload in the constructor, not passed here.

2022-02-24 14:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +				$users = array();
```suggestion
				$users = [];
```

2022-02-24 14:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			if ($config->getAppValue('dav', 'dontSendEventRemindersToSharedGroupMembers', 'no') === 'no') {
Rename to `sendEventRemindersToSharedGroupMembers` and use `yes`.

2022-02-24 14:13 UTC, tcitworld commented
Maybe we can add left-padding to this element to make it clear it belongs to the same group as above, like in the sharing admin settings?

2022-02-24 15:10 UTC, D0n1elT commented
> Maybe we can add left-padding to this element to make it clear it belongs to the same group as above, like in the sharing admin settings?

![grafik](https://user-images.githubusercontent.com/16420080/155551135-dc9c21d8-1ce2-49fa-83f1-bc41b5d419c8.png)

Requested changes are made.

2022-02-24 15:18 UTC, D0n1elT commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +	public function processReminders(IConfig $config):void {
Could you provide docs about the autoloader, please? I didn't grasp the concept of it yet.

2022-02-24 15:21 UTC, tcitworld commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
Might not be group shares but direct user-shares too.

2022-02-24 15:24 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
How would you phrase this?

2022-02-24 15:27 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
`Send notifications to all shared users of an event and not only to the organizer and attendees.` ?

2022-02-24 15:29 UTC, tcitworld commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
Something like `Send notifications to calendar sharees as well`.

2022-02-24 15:31 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
`Send notifications to calendar sharees as well as to the organizer and attendees.` ?

2022-02-24 15:34 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +			<em v-html="sendEventRemindersHelpText" />
Will be removed.

2022-02-24 15:36 UTC, tcitworld commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
We can move the second part of the sentence above, something like : `reminders are always sent to organizers and attendees`.

2022-02-24 15:39 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
Like this?

2022-02-24 15:41 UTC, D0n1elT commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Send reminder notifications not to shared group members.') }}
Like this?

![grafik](https://user-images.githubusercontent.com/16420080/155557101-0779620f-4c5f-4bd0-9a4f-66b4e2fd5807.png)

2022-02-25 13:36 UTC, D0n1elT commented
One of the failing tests:
```html
FAIL apps/dav/src/views/CalDavSettings.spec.js
  ● Console

    console.error
      [Vue warn]: Property or method "sendEventRemindersToSharedGroupMembers" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
      
      found in
      
      ---> <CalDavSettings>
             <Root>

    > 1 | <template>
        | ^
      2 | 	<div class="section">
      3 | 		<h2>{{ $t('dav', 'Calendar server') }}</h2>
      4 | 		<!-- Can use v-html as:
```

I don't get it, do you know what that means? @tcitworld

2022-03-16 13:20 UTC, D0n1elT commented
@tcitworld, @miaulalala, @ChristophWurst

I've had some problems with CI but think this PR is ready for another review now.

2022-03-17 18:54 UTC, tcitworld commented on apps/dav/src/views/CalDavSettings.vue
> +				{{ $t('dav', 'Reminders are always sent to organizers and attendees.' )}}
```suggestion
				{{ $t('dav', 'Reminders are always sent to organizers and attendees.') }}
```

2022-03-17 18:54 UTC, tcitworld commented on apps/dav/src/views/CalDavSettings.vue
> +		<p style="padding-left: 28px">
Please use a class instead defined in a `<style lang="scss" scoped>` block below.

2022-03-18 10:38 UTC, D0n1elT commented
Hey @tcitworld,

Changes are done. Can you review again? ^^

2022-03-18 10:44 UTC, tcitworld approved these changes
Just needs to test that the failing test is not a flaky one but LGTM overall.

2022-03-18 10:44 UTC, tcitworld commented on apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
> +      style="padding-left: 28px;"
Was this snapshot updated to reflect latest changes?

2022-03-18 10:47 UTC, D0n1elT commented on apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
> +      style="padding-left: 28px;"
Oof, I forgot to compile.

2022-03-18 10:55 UTC, D0n1elT commented on apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
> +      style="padding-left: 28px;"
Actually, running `make` again produces no diff. ^^
So this should be good to go.

2022-03-18 11:01 UTC, D0n1elT commented on apps/dav/src/views/__snapshots__/CalDavSettings.spec.js.snap
> +      style="padding-left: 28px;"
Should be done now.

2022-03-21 14:48 UTC, D0n1elT commented
> Just needs to test that the failing test is not a flaky one but LGTM overall.

All checks pass now: LGTM? ^^

2022-03-21 19:00 UTC, ChristophWurst approved these changes
LGTM

2022-03-21 19:00 UTC, merged

2022-03-21 19:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			if ($this->config->getAppValue('dav', 'sendEventRemindersToSharedGroupMembers', 'yes') === 'no') {
Of course I forgot to say we should rename `sendEventRemindersToSharedGroupMembers` to `sendEventRemindersToSharedUsers`, as the share can be done with groups as well as direct users. :see_no_evil:

2022-03-22 11:20 UTC, D0n1elT commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			if ($this->config->getAppValue('dav', 'sendEventRemindersToSharedGroupMembers', 'yes') === 'no') {
https://github.com/nextcloud/server/pull/31660/