Make sure common and main core scripts are loaded first
nextcloud/server pull request #31387
Opened 2022-03-01 10:41 UTC by skjnldsv

I don't have a better way right now. 
The new topologic sorting does _not_ allow core to depend on itself as we are now sorting priorities per app and not per script.

2022-03-01 11:16 UTC, CarlSchwan approved these changes

2022-03-01 15:04 UTC, come-nc approved these changes

2022-03-01 15:33 UTC, nickvergessen commented
1) Test\UtilTest::testAddScript
Failed asserting that 12 matches expected 3.

/home/runner/work/server/server/tests/lib/UtilTest.php:275

2022-03-01 20:41 UTC, Pytal approved these changes

2022-03-01 21:24 UTC, nickvergessen requested changes
Test fail with 7.4

2022-03-04 08:33 UTC, skjnldsv commented
> Test fail with 7.4

Hum, why? :thinking:

2022-03-04 08:49 UTC, nickvergessen commented on lib/public/Util.php
> +		usort($sortedScripts, function ($value1, $value2) {
https://www.php.net/manual/en/function.usort.php

> ### Note:
>
>    If two members compare as equal, they retain their original order. Prior to PHP 8.0.0, their relative order in the sorted array was undefined.

This is why.

2022-03-04 08:52 UTC, nickvergessen commented on lib/public/Util.php
> +		usort($sortedScripts, function ($value1, $value2) {
Possible workaround:

```php
$sortedScripts = array_flip($sortedScripts);
unset($sortedScripts['core/js/main']);
unset($sortedScripts['core/js/common']);
$sortedScripts = array_flip($sortedScripts);
array_unshift($sortedScripts, 'core/js/main', 'core/js/common');
```

Or don't we want to add them all the time?

2022-03-04 08:56 UTC, nickvergessen commented on lib/public/Util.php
> +		usort($sortedScripts, function ($value1, $value2) {
If they are optional:


```php
		$sortedScripts = array_flip($sortedScripts);
		$reAddMain = isset($sortedScripts['core/js/main']);
		unset($sortedScripts['core/js/main']);
		$reAddCommon = isset($sortedScripts['core/js/common']);
		unset($sortedScripts['core/js/common']);
		$sortedScripts = array_flip($sortedScripts);

		if ($reAddMain) {
			array_unshift($sortedScripts, 'core/js/main');
		}
		if ($reAddCommon) {
			array_unshift($sortedScripts, 'core/js/common');
		}
```

2022-03-04 09:26 UTC, nickvergessen approved these changes

2022-03-04 13:37 UTC, merged