User account migration
nextcloud/server pull request #31382
Opened 2022-03-01 04:13 UTC by Pytal

https://github.com/nextcloud/user_migration migrator which enables export and import of a user's account info

2022-03-01 08:36 UTC, come-nc requested changes
This PR should also take care of registering the migrator.

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +	private function getExtension(string $mimeType): string {
We should try to use a generic common solution for this.
One solution is to depend upon mime component from symfony, but if we do not require it yet it feels overkill.

An other one is to extend https://github.com/nextcloud/server/blob/master/lib/private/Files/Type/Detection.php with this feature, as this class already contains a map for mimetype -> extension, we just need to add a function to get the information out. (and decide whether we add this function to OCP and where)

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +	private function getExtension(string $mimeType): string {
(but maybe this function can be removed, see comments on avatar export)

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +			$avatarData = $avatar->get(-1)->data();
You can use getFile instead of get, and then you will not need to guess the extension. But that means you need to store the filename somewhere to know what to import when importing. Maybe an avatar.json that contains the filename, or we store this in account.json, or…

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +		foreach ($data as $propertyName => $propertyData) {
Maybe add a function to Account to be able to set all properties at once? Given json serialization is already in this class. Not sure about this, just a suggestion.

Also, how does this behave when a property is not in the json file?
We have to anticipate the case where we import into an existing user which might have data in the Account, will all fields get overridden even if empty in the export? (I’m not saying it should or should not, I’m asking what the behavior is so that we can think about it, and decide what we want)

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +			if (str_starts_with($filename, 'avatar.')) {
sounds like a dangerous solution

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigrator.php
> +			if (str_starts_with($filename, 'avatar.')) {
Maybe we should just have an "avatar" folder with only one file in it being the avatar, at least it’s reliable?

2022-03-01 08:36 UTC, come-nc commented on lib/private/Accounts/AccountMigratorException.php
> +class AccountMigratorException extends Exception {
Should extend UserMigrationException, which should be moved to OCP and added as @throws for import and export functions in IMigrator.

2022-03-02 03:41 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +			if (str_starts_with($filename, 'avatar.')) {
We would still have to detect the extension to get the path for `getFileContents($path)` in both scenarios anyways so we can narrow it down to the two cases of `avatar.jpg` and `avatar.png`

2022-03-02 03:50 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +		foreach ($data as $propertyName => $propertyData) {
Extending the Account with a `setAllProperties` sounds good

The json serialized account is always populated with all account properties by https://github.com/nextcloud/server/blob/master/lib/private/Accounts/AccountManager.php#L644-L728

Regarding the import over an existing account it would make sense that the imported data overrides existing data, but we'd probably need to think about this more or give the user an option to only add and not delete data

2022-03-02 03:51 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +			$avatarData = $avatar->get(-1)->data();
The returned file from `getFile()` is actually a SimpleFile for some reason which errors on calling the undefined `getExtension()` method, as above I will see about extending SimpleFile

Using the existence of an `avatar.(jpg|png)` file as the single source of truth is more than sufficient and putting the filename in a separate json file would only add a potential discrepancy and unecessary complexity

2022-03-02 03:59 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +			if (str_starts_with($filename, 'avatar.')) {
Just handling `avatar.jpg` and `avatar.png` are sufficient to avoid an unecessary folder

2022-03-02 04:01 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +			if (str_starts_with($filename, 'avatar.')) {
Only handling an `avatar.jpg` or `avatar.png` is sufficient to avoid an unecessary folder

2022-03-03 05:50 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +	private function getExtension(string $mimeType): string {
Done in https://github.com/nextcloud/server/pull/31418

2022-03-03 05:53 UTC, Pytal commented
Drafting pending required PRs in description

2022-03-04 19:39 UTC, Pytal commented
@blizzz json serialized collections output the below with duplicated keys alongside the regular account properties
```json
{
  "displayname": {
    "name": "displayname",
    "value": "admin",
    "scope": "v2-federated",
    "verified": "0",
    "verificationData": ""
  },
  "additional_mail": {
    "additional_mail": [
      {
        "name": "additional_mail",
        "value": "a@b.com",
        "scope": "v2-local",
        "verified": "0",
        "verificationData": ""
      },
      {
        "name": "additional_mail",
        "value": "a@b.org",
        "scope": "v2-local",
        "verified": "0",
        "verificationData": ""
      }
    ]
  }
```
We could return just the properties without the collectionName in https://github.com/nextcloud/server/blob/master/lib/private/Accounts/AccountPropertyCollection.php#L106 to fix this

Do you think this a good option or should we override the serializion in https://github.com/nextcloud/server/blob/master/lib/private/Accounts/Account.php#L109 for collections?

2022-03-08 02:08 UTC, Pytal commented on lib/private/Accounts/AccountMigrator.php
> +		foreach ($data as $propertyName => $propertyData) {
Done in https://github.com/nextcloud/server/pull/31488

2022-03-18 04:11 UTC, Pytal commented
Ready for review after all required PRs have got in

2022-03-21 10:41 UTC, come-nc reviewed
I think that as this migrator is now in the settings app it should import/export from a folder named after settings Application::APP_ID.
This makes it consistent with other migrators, and avoids people taking inspiration from this migrator to put things at the archive export root folder.

2022-03-21 13:07 UTC, artonge approved these changes

2022-03-22 08:11 UTC, come-nc approved these changes

2022-03-22 08:11 UTC, merged