add new button component
nextcloud/server pull request #31409
Opened 2022-03-02 16:55 UTC by vanpertsch

**Before**
![Screenshot 2022-03-02 at 16 21 47](https://user-images.githubusercontent.com/38529028/156405548-d9ccfc77-bd95-45a1-ae2d-f17a14b51a87.png)
![Screenshot 2022-03-02 at 16 22 53](https://user-images.githubusercontent.com/38529028/156405580-e7e7b108-4ddb-4913-8d0a-aded224e0410.png)
![Screenshot 2022-03-02 at 16 23 03](https://user-images.githubusercontent.com/38529028/156405616-2e98877d-0c40-495e-8bc8-561ea37212dc.png)

**After**

2022-03-04 18:15 UTC, Pytal approved these changes
Other than the quick aria label fix :)

2022-03-04 18:15 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +				:aria-label="t('settings', 'Add email')"
```suggestion
				:aria-label="t('settings', 'Add additional email')"
```

2022-03-09 12:35 UTC, vanpertsch commented
/compile amend /

2022-03-09 12:41 UTC, vanpertsch commented
/compile amend /

2022-03-14 09:32 UTC, vanpertsch commented
@jancborchardt do you agree with the change of the button here?

2022-03-14 10:03 UTC, jancborchardt commented
The tertiary button style would look better here, and it's also closer to how the button was before. :)

2022-03-14 11:35 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +		height: 44px;
Is it necessary to set the height? Is the default not working?

2022-03-15 09:13 UTC, vanpertsch commented on apps/settings/src/components/PersonalInfo/shared/HeaderBar.vue
> +		height: 44px;
you are right. Changed the negativ margin to -6px and the default button min-height is working. thx

2022-03-15 09:15 UTC, vanpertsch commented
/compile amend /

2022-03-15 09:23 UTC, artonge approved these changes

2022-03-16 14:31 UTC, marcoambrosini requested changes
We shouldn't use buttons type "secondary" for now, see [frontenders chat](https://cloud.nextcloud.com/call/dxbbx4jy)

2022-03-16 15:08 UTC, marcoambrosini approved these changes
uups sorry I saw the screenshot and thought you were using it

2022-03-21 09:37 UTC, vanpertsch commented
/compile amend /

2022-03-21 13:53 UTC, vanpertsch commented
/compile amend /

2022-03-22 09:00 UTC, merged