user_ldap fix ldap connection resets
nextcloud/server pull request #31421
Opened 2022-03-03 10:14 UTC by come-nc

First commit is a patch sent to a customer to fix a problem where LDAP connection was reseted during executeRead, and because the connection resource var was not managed consistently the get first entry would fail.
Patch was tested and approved by customer.
The second commit is a clean up of typing.

2022-03-08 08:44 UTC, nickvergessen commented on apps/user_ldap/lib/Access.php
> +			$count = $this->count($filter, [$base], $attr, $limit, $offset ?? 0);
Also in follow up places?

2022-03-08 09:24 UTC, come-nc commented on apps/user_ldap/lib/Access.php
> +			$count = $this->count($filter, [$base], $attr, $limit, $offset ?? 0);
Done in df29acb

2022-03-08 09:37 UTC, PVince81 commented on apps/user_ldap/lib/Access.php
> -		if (!is_null($attr) && !is_array($attr)) {
please double check removal

2022-03-08 09:42 UTC, PVince81 requested changes
looks good in general, please check the one comment about suspicious code removal

2022-03-08 13:23 UTC, come-nc commented on apps/user_ldap/lib/Access.php
> -		if (!is_null($attr) && !is_array($attr)) {
Ok I misread earlier, the check was if the $attr is neither null nor an array, which is not possible because it is typed array|null.
So the removal is fine.

2022-03-08 14:02 UTC, PVince81 approved these changes
:+1:

2022-03-10 21:43 UTC, blizzz requested changes
one concern

2022-03-10 21:43 UTC, blizzz commented on apps/user_ldap/lib/Access.php
> +		$cookie = '';
I think we have to resort to null here for behaviour of LDAP servers, cf. comment on line 1175ff.

2022-03-16 10:26 UTC, blizzz approved these changes

2022-03-17 08:13 UTC, merged