improve overwrite cli url setup check
nextcloud/server pull request #31430
Opened 2022-03-03 17:09 UTC by szaimen

Close https://github.com/nextcloud/server/issues/31429

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-03-03 22:13 UTC, szaimen commented
/rebase

2022-03-03 22:33 UTC, szaimen commented
/backport to stable23

2022-03-03 22:33 UTC, szaimen commented
/backport to stable22

2022-03-03 22:36 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		$suggestedOverwriteCliUrl = $this->request->getServerProtocol() . '://' . $this->request->getInsecureServerHost() . \OC::$WEBROOT;
Does anyone know if `\OC::$WEBROOT` can have a trailing slash?

2022-03-04 07:23 UTC, nickvergessen requested changes, later dismissed
Can you state what the improvement is?
From reading the code the improvement is that you can now have false positives for a warning?

2022-03-04 07:23 UTC, nickvergessen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		// In case of a false positive, simply ignore the suggestion
We are aware of many instances which have multiple addresses they are accessed with.
Showing a warning for them is a bit meh imho.

This is exactly why the check was implemented this way: if it is set we are okay and the URL will be visible in emails anyway.

2022-03-04 07:23 UTC, nickvergessen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if ($suggestedOverwriteCliUrl === rtrim($currentOverwriteCliUrl, "/")) {
```suggestion
		if ($suggestedOverwriteCliUrl === rtrim($currentOverwriteCliUrl, '/')) {
```

2022-03-04 08:21 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		// In case of a false positive, simply ignore the suggestion
I agree that this is a bit meh. Let me change this check to simply check if it is a valid url.

2022-03-04 09:36 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		$suggestedOverwriteCliUrl = $this->request->getServerProtocol() . '://' . $this->request->getInsecureServerHost() . \OC::$WEBROOT;
not needed anymore

2022-03-04 09:39 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
>  		}
I don't know if we really should set it automatically as we risk to set it to the wrong URL. Showing the warning in the overview is more easy to debug and fix then setting it to the wrong value, imho.

2022-03-04 09:39 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		// In case of a false positive, simply ignore the suggestion
done

2022-03-04 09:39 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if ($suggestedOverwriteCliUrl === rtrim($currentOverwriteCliUrl, "/")) {
not needed anymore

2022-03-04 09:46 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
>  		}
@nickvergessen opinions on this?

2022-03-04 10:48 UTC, juliushaertl commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
Might have issues with IDN domains, but could use https://github.com/nextcloud/server/pull/27961 once merged for the validation

2022-03-04 11:09 UTC, PVince81 commented on apps/settings/lib/Controller/CheckSetupController.php
>  		}
yeah, "check setup" is not "repair setup", so only show a warning

2022-03-04 11:11 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
>  		}
Thanks and great! will remove the code then :)

2022-03-04 11:14 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
adressed

2022-03-04 11:14 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
>  		}
done

2022-03-04 11:17 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (Util::isValidUrl($currentOverwriteCliUrl)) {
- [ ] Needs https://github.com/nextcloud/server/pull/27961

2022-03-09 21:27 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (Util::isValidUrl($currentOverwriteCliUrl)) {
seems like the PR is not backportable unfortunately :/

2022-03-09 21:30 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
Is everyone, especially @juliushaertl fine if we do it like this for now?
After merging, I will change it in Carls PR to use his validation logic but since I want to backport this we will not have the validation logic in place. 
For me the most important change of this PR is to make admins aware of this config which it does. Since it is only the admin panel, it is in my opinion no big problem if it is sometimes false-positive because of the faulty filter.

2022-03-10 10:48 UTC, juliushaertl commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
Yes, fine with me :)

2022-03-10 10:48 UTC, juliushaertl approved these changes

2022-03-10 10:58 UTC, szaimen commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
great, thanks! :)

2022-03-10 11:09 UTC, PVince81 commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
:+1:

2022-03-10 11:11 UTC, CarlSchwan commented on apps/settings/lib/Controller/CheckSetupController.php
> +		if (filter_var($currentOverwriteCliUrl, FILTER_VALIDATE_URL)) {
👍

2022-03-10 11:11 UTC, CarlSchwan approved these changes

2022-03-10 11:40 UTC, szaimen commented
Thanks everyone! Merging then :)

2022-03-10 11:41 UTC, merged

2022-03-10 11:41 UTC, szaimen commented
/backport to stable23

2022-03-10 11:41 UTC, szaimen commented
/backport to stable22