fix User Counts updates on user add/remove
nextcloud/server pull request #31484
Opened 2022-03-07 19:44 UTC by petre2dor

Fix for #27607 
I refactored the existing code that update the counts on user enable/disable and added code to update the counts on user add/remove

Signed-off-by: Petre T <petre.tudor@dorkfarm.com>

2022-03-07 23:26 UTC, szaimen commented
/compile amend /

2022-03-08 07:50 UTC, skjnldsv commented
@petre2dor could you enable us to change this pr? :)

![image](https://user-images.githubusercontent.com/14975046/157191088-9d0750ff-e5b5-49d2-b5db-6dff0841ad94.png)

2022-03-08 07:56 UTC, petre2dor commented
Hi @skjnldsv,
That checkbox is already checked.
![image](https://user-images.githubusercontent.com/676869/157191747-a54a2dbe-d620-4067-9c10-a9031cf2f1ba.png)

2022-03-09 04:46 UTC, Pytal commented
/compile amend /

2022-03-09 04:47 UTC, Pytal commented
👆 attempt 2

2022-03-09 14:23 UTC, szaimen commented
> I guess it would probably make sense to push this to a branch in this repo and invite Petre to the org for easier collaboration...

@skjnldsv would you be able to do so? :)

2022-03-22 09:34 UTC, petre2dor commented
Hi everyone, 
Just a friendly reminder about this PR in the hope we can move this along.

Thanks :)

2022-03-22 10:45 UTC, szaimen commented
@petre2dor thanks for the ping! I would be able to push your changes to a branch in this repo but I fear I am not able to invite you to the org which would mean that you would not be able to push to the new branch...

Apart from that, you can also fix the `Node` workflow by compiling the js locally and pushing it to the branch.

2022-03-22 11:07 UTC, artonge requested changes

2022-03-22 11:07 UTC, artonge commented on apps/settings/src/store/users.js
> +		// this.commit('updateUserCounts', { user, actionType: enabled ? 'enable' : 'disable' })
I would prefer the `enable`/`disable` action type so the `update` one is not wrongly used in the future.

2022-03-22 11:07 UTC, artonge commented on apps/settings/src/store/users.js
> +		case 'update':
To not duplicate the code you can handle both `enable` and ` disable` like so:

```
		case 'enable':
		case 'disable':
			...
```

and keeping the current logic

2022-03-23 08:47 UTC, skjnldsv commented
> @skjnldsv would you be able to do so? :)

invited @petre2dor

2022-03-24 10:30 UTC, szaimen commented
> invited @petre2dor

@petre2dor did you accept? then I could push your changes to a new branch...

2022-03-24 10:32 UTC, petre2dor commented
> > invited @petre2dor
> 
> @petre2dor did you accept? then I could push your changes to a new branch...

Yes, I did today. Thanks!
I'll make my changes today or tomorrow.

2022-03-24 10:34 UTC, szaimen commented
> Yes, I did today. Thanks!
> I'll make my changes today or tomorrow.

Shall I push your changes to the new branch in the meantime or do you want to make your new changes first and then push it to the new branch afterwards?

2022-03-24 11:05 UTC, petre2dor commented
> > Yes, I did today. Thanks!
> > I'll make my changes today or tomorrow.
> 
> Shall I push your changes to the new branch in the meantime or do you want to make your new changes first and then push it to the new branch afterwards?

Please push my changes to a new branch first. 
I destroyed my dev machine and I need to rebuild it. No need to use my fork and switch later to Nexcloud repo.

2022-03-24 11:20 UTC, szaimen commented
Superseded by https://github.com/nextcloud/server/pull/31697

2022-03-24 11:20 UTC, closed without merging

2022-03-24 11:20 UTC, szaimen commented
> Please push my changes to a new branch first.
> I destroyed my dev machine and I need to rebuild it. No need to use my fork and switch later to Nexcloud repo.

done with https://github.com/nextcloud/server/pull/31697

2022-03-24 20:29 UTC, petre2dor commented on apps/settings/src/store/users.js
> +		case 'update':
thanks for the review @artonge. I made the chenges and pushed here https://github.com/nextcloud/server/pull/31697
please review it again