Improve user migration api
nextcloud/server pull request #31516
Opened 2022-03-10 10:55 UTC by come-nc

- Add base exception class to be used by migrators and add appropriate `@throws` documentation
- Add pathExists method to have an efficient way to test if a folder or a file exists (previously one had to use `in_array($path, $importSource->getFolderListing('parent/'))`)
- Add getOriginalUid as single point of truth to get the original uid of the imported account, which may differ from the uid of the imported account in the end. This is useful information for instance to detect files comment which are from the imported user.

2022-03-10 16:13 UTC, CarlSchwan approved these changes

2022-03-10 17:16 UTC, Pytal approved these changes

2022-03-10 20:03 UTC, Pytal commented
Trigger CI rerun

2022-03-11 08:42 UTC, nickvergessen requested changes
The autoloaders are not up to date

2022-03-11 08:42 UTC, nickvergessen commented on lib/public/UserMigration/UserMigrationException.php
> +class UserMigrationException extends \Exception {
PHPDoc is needed for OCP\UserMigration\UserMigrationException::UserMigrationException

2022-03-11 08:42 UTC, nickvergessen commented on lib/public/UserMigration/UserMigrationException.php
> +class UserMigrationException extends \Exception {
Missing `@since`

2022-03-11 19:14 UTC, Pytal approved these changes
Other than the changes mentioned by @nickvergessen

2022-03-14 13:45 UTC, nickvergessen approved these changes

2022-03-15 02:17 UTC, merged