add icons to navigation of personal & admin settings
nextcloud/server pull request #3151
Opened 2017-01-19 02:14 UTC by jancborchardt

Before & after:
![capture du 2017-01-19 02-27-02](https://cloud.githubusercontent.com/assets/925062/22091045/0515df18-ddf5-11e6-94b3-e74840061e07.png) ![capture du 2017-01-19 02-26-35](https://cloud.githubusercontent.com/assets/925062/22091044/050bed32-ddf5-11e6-805a-c955f3ea2497.png)

![capture du 2017-01-19 03-11-08](https://cloud.githubusercontent.com/assets/925062/22091046/08d62c7a-ddf5-11e6-8375-cbd71fd9bd6b.png) ![capture du 2017-01-19 03-10-45](https://cloud.githubusercontent.com/assets/925062/22091047/08dcc8be-ddf5-11e6-9f8b-4bbc74cb646e.png)

This brings it in line with the other apps like Files, Activity, Mail, etc. :)
Please review @nextcloud/designers 

A possible future improvement would be to instead of hardcoding the icons via the settings.css to get them from the app icon itself. cc @schiessle @nickvergessen @juliushaertl do you have an idea about the feasibility of that?

2017-01-19 03:42 UTC, MorrisJobke commented
I also fixed that the themed color is used:

![bildschirmfoto 2017-01-18 um 21 39 12](https://cloud.githubusercontent.com/assets/245432/22092923/082532d6-ddc7-11e6-96ad-014c4ed1ff14.png)

2017-01-19 03:48 UTC, MorrisJobke commented
Looks really nice, but the serverinfo app is missing an icon:

<img width="330" alt="bildschirmfoto 2017-01-18 um 21 48 15" src="https://cloud.githubusercontent.com/assets/245432/22093025/ce56a5e8-ddc7-11e6-8da5-eab151e86706.png">

2017-01-19 03:53 UTC, MorrisJobke reviewed
Looks nice, but we maybe should add the entry for the serverinfo app. I also added the viewBox elements where they were missing. 😉

2017-01-19 05:54 UTC, skjnldsv commented
I like it a lot too :)

2017-01-19 07:23 UTC, nickvergessen requested changes

2017-01-19 07:23 UTC, nickvergessen commented on settings/css/settings.css
> +.nav-icon-survey_client {
This is cheating and should be part of the api instead, otherwise apps that add their own sections dont have one....
I can do that...

2017-01-19 08:07 UTC, skjnldsv commented on settings/css/settings.css
> +.nav-icon-survey_client {
This should probably be in icons.scss.

2017-01-19 09:45 UTC, nickvergessen commented
I fixed the admin section, so the icons are now part of the API.
However I'm still not happy with the hack on the personal page, because apps can not get their icons displayed there without making changes in the server repo. But I guess we have to live with that until the personal page is rebuild with the new settings api as well.

2017-01-19 09:45 UTC, nickvergessen approved these changes

2017-01-19 09:50 UTC, nickvergessen commented
Setting to develop because test will fail

2017-01-19 12:36 UTC, jancborchardt commented on settings/css/settings.css
> +.nav-icon-survey_client {
@nickvergessen yup, that's why I mentioned it would be nicer to get it from the app! :) Would be cool if you can do that.
I looked in the activity app also but there you din't use the standard way with the ul class="with-icon" and instead of background-image use img elements. If possible we should use the standard as styled in the apps.css.

2017-01-19 12:39 UTC, jancborchardt commented on settings/css/settings.css
> +}
This is what I mean – it doesn't use the same way as we do in Files, or Mail etc.

We should standardize that everywhere. Also cc @skjnldsv @eppfel regarding the design / HTML/CSS guidelines we want to improve.

2017-01-19 12:44 UTC, eppfel commented on settings/css/settings.css
> +}
Yeah, I actually surrendered on nextcloud/nextcloud.com#140 for now. We need to find a more engaging, agile way to work on this. Let's talk @ FOSDEM about that...

2017-01-19 13:37 UTC, jancborchardt commented
@nickvergessen awesome! Just one thing: We should use the same method as we specified in the apps.css, which is the one we use in Files and Mail etc. Now there’s a discrepancy in method, and this even results in the spacing being different from the one in Files.

2017-01-19 14:07 UTC, nickvergessen commented
@jancborchardt Well activity uses image-paths as well and we need that when we want to make use of them in android/desktop apps as well.
Also images work without the android app needing to know all nextcloud apps, since its just a path you follow.

2017-01-19 22:21 UTC, MorrisJobke approved these changes
Awesome sauce 🥇

2017-01-19 22:21 UTC, MorrisJobke commented
I fixed the "failing tests" -> I added the missing autoloader dump ;)

2017-01-23 14:14 UTC, jancborchardt commented
Ok, I just need to fix the whitespace of the icons then to make it exactly the same as with the code from apps.css

:no_entry_sign: until then

2017-01-23 23:43 UTC, jancborchardt commented
Or rather, will fix in a follow-up pull request since it’s separate.

2017-01-23 23:45 UTC, jancborchardt commented
@MorrisJobke @nickvergessen what about the codecov failure?

2017-01-24 00:37 UTC, MorrisJobke commented
> @MorrisJobke @nickvergessen what about the codecov failure?

You just need to increase the coverage of all of you changed lines: That means: you change a line of PHP that isn't covered yet: you better cover it otherwise it will likely fail if you don't have enough coverage on other code paths ;)

2017-01-24 16:04 UTC, skjnldsv commented
Drone stalled on 5.6 again. I restarted the tests. 🙈 🙉 🙊

2017-01-24 16:56 UTC, merged

2017-01-24 16:57 UTC, skjnldsv commented
👍

2017-01-24 19:09 UTC, MorrisJobke commented
Looks really nice now:
<img width="269" alt="bildschirmfoto 2017-01-24 um 13 08 46" src="https://cloud.githubusercontent.com/assets/245432/22262382/491d94ea-e236-11e6-90aa-7fd78a660492.png">

2017-01-26 10:48 UTC, jancborchardt commented
Yup, damn nice and consistent :) good work all around!

Now the only place missing icons is Help :)