disable web updater by default on instances with more than 100 users
nextcloud/server pull request #31537
Opened 2022-03-11 11:24 UTC by szaimen

Close https://github.com/nextcloud/server/issues/31533

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-03-11 11:38 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
Anyone knows why psalm fails here or how to fix psalm=

2022-03-11 11:53 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
Seems like this is not a new warning: https://github.com/nextcloud/server/blob/cec00df21c8d212c4eb07836972d2ac73aa1b59c/build/psalm-baseline.xml#L4321

2022-03-11 11:58 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
I might have found a solution with https://github.com/nextcloud/server/pull/31537/commits/4fc52f36131b20abb5c41eb95900f2fb1ab7ff8b

2022-03-11 12:04 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
I am doing the same with https://github.com/nextcloud/server/pull/31537/commits/6b79d40e2c6cb75c1cbb23eb9d7d10d470ce4522

2022-03-11 13:18 UTC, CarlSchwan commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
correct fix would be something like this: https://github.com/nextcloud/server/pull/31542

2022-03-11 15:47 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
Thanks! Will try the same 👍

2022-03-11 18:21 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
seems like it works :)

2022-03-11 18:21 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$backendUsers = $backend->countUsers();
seems like it works :)

2022-03-12 11:59 UTC, szaimen commented
/rebase

2022-03-14 12:24 UTC, szaimen commented
/rebase

2022-03-14 17:39 UTC, szaimen commented
Not sure why this is now failing:
![image](https://user-images.githubusercontent.com/42591237/158229493-c6868cba-4ae8-4f83-8253-be2431572018.png)
Any hint?

2022-03-17 20:34 UTC, tcitworld requested changes

2022-03-17 20:34 UTC, tcitworld commented on apps/updatenotification/lib/Controller/AdminController.php
> +			if ($backend->implementsActions(Backend::COUNT_USERS)) {
```suggestion
			if ($backend instanceof ICountUsersBackend) {
```

Then you can remove the PHPDoc annotation.

2022-03-17 20:36 UTC, CarlSchwan commented on apps/updatenotification/lib/Controller/AdminController.php
> +			if ($backend->implementsActions(Backend::COUNT_USERS)) {
Not really because not all the backend explicitly extends ICountUsersBackend. This should be changed and I already adapted a few days ago user_ldap, but there is probably more to do

2022-03-17 20:38 UTC, tcitworld requested changes

2022-03-17 20:38 UTC, tcitworld commented on apps/updatenotification/lib/Controller/AdminController.php
> +			if ($backend->implementsActions(Backend::COUNT_USERS)) {
We can at least add this as a `TODO` comment

2022-03-17 20:44 UTC, szaimen commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +		$this->userManager = $this->createMock(IUserManager::class);
Thanks! Any pointer how to do that?

2022-03-17 20:45 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +			if ($backend->implementsActions(Backend::COUNT_USERS)) {
Will add a todo 👍

2022-03-18 19:40 UTC, szaimen commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +		$this->userManager = $this->createMock(IUserManager::class);
@tcitworld ? :)

2022-03-18 19:55 UTC, tcitworld commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +		$this->userManager = $this->createMock(IUserManager::class);
It's rather complex if you're not used to it. :)

Some reading: https://phpunit.readthedocs.io/en/9.5/test-doubles.html#mock-objects

This is something that should cover most cases, but I wrote it without testing it.

```php
$backend1 = $this->createMock(UserInterface::class);
$backend2 = $this->createMock(UserInterface::class);
$backend3 = $this->createMock(UserInterface::class);

$backend1->expects($this->once())->method('implementsActions')->with(Backend::COUNT_USERS)->willReturn(false);
$backend2->expects($this->once())->method('implementsActions')->with(Backend::COUNT_USERS)->willReturn(true);
$backend3->expects($this->once())->method('implementsActions')->with(Backend::COUNT_USERS)->willReturn(true);

$backend1->expects($this->never())->method('countUsers');
$backend2->expects($this->once())->method('countUsers')->with()->willReturn(false);
$backend3->expects($this->once())->method('countUsers')->with()->willReturn(5);

$this->userManager->expects($this->once())->method('getBackends')->with()->willReturn([$backend1, $backend2, $backend3]);
```

2022-03-18 19:55 UTC, tcitworld commented on apps/updatenotification/lib/Controller/AdminController.php
> +		$disabledUsers = $this->config->getUsersForUserValue('core', 'enabled', 'false');
Note that the count will be invalid as soon as a backend doesn't support counting users but provided many now disabled users.

2022-03-21 08:53 UTC, szaimen commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +		$this->userManager = $this->createMock(IUserManager::class);
Thanks! Will have a look at this :)

2022-03-21 08:53 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +		$disabledUsers = $this->config->getUsersForUserValue('core', 'enabled', 'false');
Thanks! Though I only copied the logic so the other place has the culprit, too.

2022-03-21 10:33 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +			if ($backend->implementsActions(Backend::COUNT_USERS)) {
done

2022-03-21 14:12 UTC, tcitworld approved these changes

2022-03-21 15:03 UTC, artonge approved these changes

2022-03-21 22:01 UTC, szaimen commented on apps/updatenotification/lib/Controller/AdminController.php
> +		return true;
I honestly find my syntax better understandable but either of the suggestions is fine by me, too 👍

2022-03-21 22:11 UTC, szaimen commented
Assigning @PVince81 for the final review and decision if this is good to merge or if we need a different approach for this :)

2022-03-22 09:34 UTC, PVince81 commented
@szaimen 

I'd prefer a big warning in the web UI close to the upgrade button (and optionally even have a confirmation popup after clicking it). The warning should link to the docs about the recommended command-line upgrade procedure.

also, the way of the current code would make it look like a bug if someone had 99 users in the last update and then have 100, and then "suddenly" they cannot upgrade any more, I can imagine bug reports "web updater button has disappeared since last update" or something alike

2022-03-22 09:46 UTC, skjnldsv approved these changes

2022-03-22 10:47 UTC, szaimen commented
> I'd prefer a big warning in the web UI close to the upgrade button (and optionally even have a confirmation popup after clicking it). The warning should link to the docs about the recommended command-line upgrade procedure.
> 
> also, the way of the current code would make it look like a bug if someone had 99 users in the last update and then have 100, and then "suddenly" they cannot upgrade any more, I can imagine bug reports "web updater button has disappeared since last update" or something alike

Thanks! So a better way for this would be having a different method for it to be able to show a big warning based on that? Is that correct?

2022-03-24 09:16 UTC, szaimen commented
> Thanks! So a better way for this would be having a different method for it to be able to show a big warning based on that? Is that correct?

@PVince81 could you please answer that? :)

2022-03-24 19:35 UTC, PVince81 commented
> > I'd prefer a big warning in the web UI close to the upgrade button (and optionally even have a confirmation popup after clicking it). The warning should link to the docs about the recommended command-line upgrade procedure.
> > also, the way of the current code would make it look like a bug if someone had 99 users in the last update and then have 100, and then "suddenly" they cannot upgrade any more, I can imagine bug reports "web updater button has disappeared since last update" or something alike
> 
> Thanks! So a better way for this would be having a different method for it to be able to show a big warning based on that? Is that correct?

yes. technically, not sure how you would return that information.
maybe return it together with the update version information?

2022-03-24 22:44 UTC, szaimen commented
/compile amend /

2022-03-24 22:47 UTC, szaimen commented
/compile amend /

2022-03-24 22:59 UTC, szaimen commented
/compile amend /

2022-03-24 23:30 UTC, szaimen commented
Screenshot:
![image](https://user-images.githubusercontent.com/42591237/160026374-a5e1d462-8fd8-49b0-af72-46783cb207ba.png)

2022-03-25 07:24 UTC, PVince81 commented on apps/updatenotification/lib/Settings/Admin.php
> +					$this->logger->warning('Can not determine user count for ' . get_class($backend), ['app' => 'updatenotification']);
I'd say ignore. Because if one backend already said 100+ then the warning is displayed.
And if the current count is less then there's nothing we can do anyway.

2022-03-25 07:25 UTC, PVince81 commented on apps/updatenotification/lib/Settings/Admin.php
> +		$disabledUsersCount = count($disabledUsers);
I'm wondering if we should also count disabled users.

The reason is because the migrations is going to process their data anyway and contribute to increasing the update time, and update time is the concern when using the web updater.

2022-03-25 08:41 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +					$this->logger->warning('Can not determine user count for ' . get_class($backend), ['app' => 'updatenotification']);
Okay

2022-03-25 08:41 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +		$disabledUsersCount = count($disabledUsers);
Makes sense

2022-03-25 09:03 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +					$this->logger->warning('Can not determine user count for ' . get_class($backend), ['app' => 'updatenotification']);
done

2022-03-25 09:03 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +		$disabledUsersCount = count($disabledUsers);
done

2022-03-28 15:06 UTC, PVince81 commented on apps/updatenotification/lib/Settings/Admin.php
> +			$this->logger->warning("Total user count was negative (users: $userCount)", ['app' => 'updatenotification']);
since we don't substract anything, a negative value is very unlikely, so perhaps we can just remove this block

2022-03-28 15:07 UTC, PVince81 approved these changes
:+1: after fixing the minor comments

2022-03-28 17:12 UTC, Pytal commented on apps/updatenotification/lib/Settings/Admin.php
> +	// Copied from https://github.com/nextcloud/server/blob/a06001e0851abc6073af678b742da3e1aa96eec9/lib/private/Support/Subscription/Registry.php#L187-L214
```suggestion
	/**
	 * @see \OC\Support\Subscription::getUserCount() implementation reference
	 */
```

2022-03-28 19:06 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +			// TODO: change below to 'if ($backend instanceof ICountUsersBackend) {'
yes

2022-03-28 19:12 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +			$this->logger->warning("Total user count was negative (users: $userCount)", ['app' => 'updatenotification']);
good point!

2022-03-28 19:13 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +			$this->logger->warning("Total user count was negative (users: $userCount)", ['app' => 'updatenotification']);
fixed

2022-03-28 19:13 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +	// Copied from https://github.com/nextcloud/server/blob/a06001e0851abc6073af678b742da3e1aa96eec9/lib/private/Support/Subscription/Registry.php#L187-L214
good idea!

2022-03-28 19:13 UTC, szaimen commented on apps/updatenotification/lib/Settings/Admin.php
> +	// Copied from https://github.com/nextcloud/server/blob/a06001e0851abc6073af678b742da3e1aa96eec9/lib/private/Support/Subscription/Registry.php#L187-L214
done

2022-03-28 19:50 UTC, szaimen commented
S3 failure unrelated

2022-03-28 19:50 UTC, merged

2022-03-28 19:51 UTC, szaimen commented
/backport to stable23

2022-03-28 19:51 UTC, szaimen commented
/backport to stable22