Contacts migration
nextcloud/server pull request #31673
Opened 2022-03-23 03:48 UTC by Pytal

### To Do
- [ ] Export and import
- [ ] Integration tests

2022-03-24 08:26 UTC, tcitworld commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . $vCard->{'FN'} . '" containing invalid contact data');
As a fallback?
```suggestion
					$output->writeln('Skipping contact "' . ($vCard->{'FN'} || $vCard->{'UID'}). '" containing invalid contact data');
```

2022-03-25 04:46 UTC, Pytal commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . $vCard->{'FN'} . '" containing invalid contact data');
FN is required since vCard version 4.0 https://en.wikipedia.org/wiki/VCard#Properties so it seems safe

2022-03-26 02:49 UTC, Pytal commented
@tcitworld I've tried the way suggested in https://github.com/nextcloud/server/pull/30963#discussion_r813653699 and it seems to have the same results but adds more code than the CardDavBackend way, so unless there is a notable benefit I'll stick with the current CardDavBackend way as it's cleaner and helps abstract away complexity

2022-03-29 15:48 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +		['uri' => $uri] =  $addressBookInfo;
This is a fancy way of writing `$uri = $addressBookInfo['uri'];` right?
What if this key does not exists?
I think the check `if (empty($addressBookInfo)) {` should be changed to `if (!isset($addressBookInfo['uid'])) {`

2022-03-29 15:48 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . $vCard->FN . '" containing invalid contact data');
```suggestion
					$output->writeln('Skipping contact "' . ($vCard->FN ?? 'null') . '" containing invalid contact data');
```

2022-03-29 15:48 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			$output->writeln('Error creating contact "' . $vCard->FN . '", skipping…');
same thing

2022-03-29 15:48 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . $vCard->FN . '" containing invalid contact data');
Same

2022-03-29 15:48 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			[$initialAddressBookUri, $suffix] = $splitFilename;
Isn’t the uri in the data? I thought filename had special character removed, I would feel better if it had no special meaning.

2022-03-29 15:49 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . $vCard->{'FN'} . '" containing invalid contact data');
The validation problem could come from notset FN no? Better be safe than sorry when already in error handling, I suggested ?? 'null'

2022-03-30 00:52 UTC, Pytal commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			[$initialAddressBookUri, $suffix] = $splitFilename;
The uri is not contained in the data and is used as the filename in the existing download address book logic when clicking the button in the UI https://github.com/sabre-io/dav/blob/130abb7017f56e0d99b04eb94b041e000a8e9b39/lib/CardDAV/VCFExportPlugin.php#L93, I would like to have the uri derived from the filename on import as it is used this way on export as well

There would be no errors purely from the export/import filenames as implemented but if this is still a concern let's address it outside of this PR

2022-03-30 07:39 UTC, come-nc requested changes

2022-03-30 07:39 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +		['uri' => $uri] =  $addressBookInfo;
```suggestion
		$uri = $addressBookInfo['uri'];
```

2022-03-30 07:39 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . ($vCard->FN ?? null) . '" containing invalid contact data');
This still anoys psalm, you put `null` instead of `'null'`. You need to concatenate with a string.

2022-03-30 07:39 UTC, come-nc commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +					$output->writeln('Skipping contact "' . ($vCard->FN ?? null) . '" containing invalid contact data');
(same for the two other instances of this)

2022-03-30 21:36 UTC, come-nc approved these changes

2022-04-07 15:33 UTC, PVince81 commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			$basename = preg_replace('/[^a-zA-Z0-9-_ ]/um', '', $name) . '_' . date('Y-m-d');
check if we have such utilities maybe in the static Filesystem class

2022-04-07 15:36 UTC, PVince81 commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			$this->cardDavBackend->getAddressBooksForUser($principalUri),
fix the warning ?

2022-04-07 15:36 UTC, PVince81 approved these changes
:+1:

2022-04-07 15:36 UTC, merged

2022-04-20 21:51 UTC, Pytal commented on apps/dav/lib/UserMigration/ContactsMigrator.php
> +			$basename = preg_replace('/[^a-zA-Z0-9-_ ]/um', '', $name) . '_' . date('Y-m-d');
> `Filesystem::normalizePath()`

Not needed as this is a different use case