Start theming providers
nextcloud/server pull request #31751
Opened 2022-03-29 20:19 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2022-03-30 14:58 UTC, come-nc requested changes, later dismissed

2022-03-30 14:58 UTC, come-nc commented on apps/theming/lib/Controller/ThemingController.php
> +		$theme = $this->themesService->getThemes()[$themeId];
```suggestion
		$theme = $this->themesService->getThemes()[$themeId] ?? null;
```

2022-03-30 14:58 UTC, come-nc commented on apps/theming/lib/Service/ThemeInjectionService.php
> +			return !!$theme->getMediaQuery();
```suggestion
			return (bool)$theme->getMediaQuery();
```

2022-03-30 14:58 UTC, come-nc commented on apps/theming/lib/Service/ThemeInjectionService.php
> +			return !!$theme->getMediaQuery();
Or even
```suggestion
			return ($theme->getMediaQuery() !== '');
```

2022-03-30 14:58 UTC, come-nc commented on apps/theming/lib/Service/ThemesService.php
> +			$highContrastTheme->id		=> $highContrastTheme,
```suggestion
			$defaultTheme->getId()			=> $defaultTheme,
			$darkTheme->getId()				=> $darkTheme,
			$darkHighContrastTheme->getId()	=> $darkHighContrastTheme,
			$highContrastTheme->getId()		=> $highContrastTheme,
```

2022-03-31 10:36 UTC, skjnldsv commented on apps/theming/lib/Controller/ThemingController.php
> +			$variable .= "$variable:$value; ";
Not in css no :)
That would be invalid and discarded

2022-04-21 12:20 UTC, skjnldsv commented
/compile /

2022-04-21 13:15 UTC, szaimen commented
@skjnldsv could you please clarify which apps/parts of Nextcloud should be checked for problems when reviewing this PR?
Thank you :)

2022-04-21 13:16 UTC, CarlSchwan approved these changes
The code looks fine to me

I would propose to merge it sooner than later even if there are some small issues that can be fixed in follow-up as we are in the beginning of a release cycle.

2022-04-21 13:19 UTC, skjnldsv commented
> The code looks fine to me
> 
> I would propose to merge it sooner than later even if there are some small issues that can be fixed in follow-up as we are in the beginning of a release cycle.

My thoughts as well.
I added some phpunit tests, fixed the old ones and psalm.
There will most likely be quite a few follow-ups, but that's a good first step.

2022-04-21 13:24 UTC, skjnldsv commented
@juliushaertl there will most likely also be stuff I missed on the old magic Theming was doing. I removed most that I could, but I am sure I missed a few. Any help welcome on understanding anything that might be missing now. :pray:

2022-04-21 13:26 UTC, skjnldsv commented
> @skjnldsv could you please clarify which apps/parts of Nextcloud should be checked for problems when testing this PR? Thank you :)

I'll edit the main post for review requirements :)

2022-04-21 13:28 UTC, szaimen commented
> > @skjnldsv could you please clarify which apps/parts of Nextcloud should be checked for problems when testing this PR? Thank you :)
> 
> I'll edit the main post for review requirements :)

thanks :)

2022-04-21 14:02 UTC, szaimen commented
There are many things that are broken and not working correctly. most important are probably the missing logo on the login screen the the default light mode clashing with the prefer color scheme media query.

<details>
<summary>click to expand</summary>


a few things are broken:
- [ ] missing login logo: ![image](https://user-images.githubusercontent.com/42591237/164472220-11167a56-0fa0-4197-8720-3bbd5d0230cd.png)
- [ ] the text is more grey than before: ![image](https://user-images.githubusercontent.com/42591237/164472487-ae322327-47b2-4e50-a7a3-f9532636e844.png)
- [ ] this text too: ![image](https://user-images.githubusercontent.com/42591237/164472564-1a67fba2-a49a-4f38-95d7-313464061948.png)
- [ ] should hovering be dark in light mode? ![image](https://user-images.githubusercontent.com/42591237/164472682-fe67cf78-8e9c-4b22-a6ea-a8e2ae74318e.png)
- [ ] same: ![image](https://user-images.githubusercontent.com/42591237/164472737-052770bf-4e74-4ab0-86bc-f9a9edd5277c.png)
- [ ] also: ![image](https://user-images.githubusercontent.com/42591237/164472846-2e75ede6-fcf9-4c86-a5e2-579b4d29657d.png)
- [ ] missing icons, also black popup in light mode? ![image](https://user-images.githubusercontent.com/42591237/164472943-a99a3338-23a1-4a57-a52f-005590c8de25.png)
- [ ] in general it seems to respect my dark mode system setting but not for all elements
- [ ] it is strange that the default them will use the media query ![image](https://user-images.githubusercontent.com/42591237/164473506-396e07d8-4107-4a0c-9f32-fa09dc4e036a.png)
- [ ] the dyslexia font does not work for me: ![image](https://user-images.githubusercontent.com/42591237/164473737-c7de4ff0-82cb-48a2-977c-9a9ed90de1ee.png)
- [ ] viewer buuttons in light mode with high contrast does not respect this: ![image](https://user-images.githubusercontent.com/42591237/164473995-d7a17b09-a4d3-46ec-acc9-beeb669b50a6.png)
- [ ] icons in dark with high contrast dont look correct: ![image](https://user-images.githubusercontent.com/42591237/164474191-5c192c2e-ba5a-4ebf-9276-0e97cec97ec2.png)
- [ ] also in dark mode the icons are not correct: ![image](https://user-images.githubusercontent.com/42591237/164474372-fcc8587e-0b2a-4655-97fb-c9c25b8195bc.png)
- [ ] in dark mode font does not look correct: ![image](https://user-images.githubusercontent.com/42591237/164474438-d5358977-4cb0-4fac-bc23-414726fe87ec.png)
- [ ] opening public links breaks the text color again: ![image](https://user-images.githubusercontent.com/42591237/164474672-eec5b91c-580c-466e-8d11-db220054b7db.png)
- [ ] same for the text app: ![image](https://user-images.githubusercontent.com/42591237/164474759-7f363f14-260b-4377-b113-fc321dbe1a43.png)
- [ ] I could go on...


</details>

2022-04-21 14:02 UTC, szaimen requested changes, later dismissed
There are many things that are broken and not working correctly. most important are probably the missing logo on the login screen the the default light mode clashing with the prefer color scheme media query. Also the theming logo and picture options dont seem to work as expected.

<details>
<summary>click to expand</summary>


a few things are broken:
- [ ] missing login logo: ![image](https://user-images.githubusercontent.com/42591237/164472220-11167a56-0fa0-4197-8720-3bbd5d0230cd.png)
- [ ] the text is more grey than before: ![image](https://user-images.githubusercontent.com/42591237/164472487-ae322327-47b2-4e50-a7a3-f9532636e844.png)
- [ ] this text too: ![image](https://user-images.githubusercontent.com/42591237/164472564-1a67fba2-a49a-4f38-95d7-313464061948.png)
- [ ] should hovering be dark in light mode? ![image](https://user-images.githubusercontent.com/42591237/164472682-fe67cf78-8e9c-4b22-a6ea-a8e2ae74318e.png)
- [ ] same: ![image](https://user-images.githubusercontent.com/42591237/164472737-052770bf-4e74-4ab0-86bc-f9a9edd5277c.png)
- [ ] also: ![image](https://user-images.githubusercontent.com/42591237/164472846-2e75ede6-fcf9-4c86-a5e2-579b4d29657d.png)
- [ ] missing icons, also black popup in light mode? ![image](https://user-images.githubusercontent.com/42591237/164472943-a99a3338-23a1-4a57-a52f-005590c8de25.png)
- [ ] in general it seems to respect my dark mode system setting but not for all elements
- [ ] it is strange that the default them will use the media query ![image](https://user-images.githubusercontent.com/42591237/164473506-396e07d8-4107-4a0c-9f32-fa09dc4e036a.png)
- [ ] the dyslexia font does not work for me: ![image](https://user-images.githubusercontent.com/42591237/164473737-c7de4ff0-82cb-48a2-977c-9a9ed90de1ee.png)
- [ ] viewer buuttons in light mode with high contrast does not respect this: ![image](https://user-images.githubusercontent.com/42591237/164473995-d7a17b09-a4d3-46ec-acc9-beeb669b50a6.png)
- [ ] icons in dark with high contrast dont look correct: ![image](https://user-images.githubusercontent.com/42591237/164474191-5c192c2e-ba5a-4ebf-9276-0e97cec97ec2.png)
- [ ] also in dark mode the icons are not correct: ![image](https://user-images.githubusercontent.com/42591237/164474372-fcc8587e-0b2a-4655-97fb-c9c25b8195bc.png)
- [ ] in dark mode font does not look correct: ![image](https://user-images.githubusercontent.com/42591237/164474438-d5358977-4cb0-4fac-bc23-414726fe87ec.png)
- [ ] opening public links breaks the text color again: ![image](https://user-images.githubusercontent.com/42591237/164474672-eec5b91c-580c-466e-8d11-db220054b7db.png)
- [ ] same for the text app: ![image](https://user-images.githubusercontent.com/42591237/164474759-7f363f14-260b-4377-b113-fc321dbe1a43.png)
- [ ] These options don't seem to work as expected: ![image](https://user-images.githubusercontent.com/42591237/164475827-aa8b4fd4-eb4a-48e4-adb1-d6fd5f088ba1.png)

- [ ] I could go on...


</details>

2022-04-21 17:07 UTC, skjnldsv commented
> a few things are broken

Fixed the login

The rest will be fixed in followups :)

2022-04-21 17:13 UTC, szaimen commented
I'll retest in a second 👍

2022-04-21 17:23 UTC, szaimen reviewed
the dashboard app is still a bit broken in dark mode: 
![image](https://user-images.githubusercontent.com/42591237/164515842-12e11f50-11a8-471c-9c16-2aef1124cd1a.png)

and the files app too:
![image](https://user-images.githubusercontent.com/42591237/164515796-ac5ee350-46a1-4afd-8640-7b191f3471bd.png)
![image](https://user-images.githubusercontent.com/42591237/164515912-3227f192-c1ac-4a87-a61e-2769250b750a.png)

Also dyslexia still does not work for me, don't know why...

But okay to me to do this in a follow-up

2022-04-22 07:06 UTC, szaimen commented
We should add this to breaking change of 25 (e.g. that the accessibility app is now included in theming...)

2022-04-22 09:19 UTC, skjnldsv commented
> But okay to me to do this in a follow-up

Will do! :rocket:

2022-04-22 09:20 UTC, skjnldsv approved these changes
Will address design improvements in followups

2022-04-22 10:08 UTC, skjnldsv commented
integration-setup-features failure unrelated

2022-04-22 10:20 UTC, szaimen commented
@skjnldsv Did you find a fix for the dyslexic prpblem?

2022-04-22 10:24 UTC, skjnldsv commented
> @skjnldsv Did you find a fix for the dyslexic problem?

Yes, will add as followup, just using the generateUrl should be enough

2022-04-22 10:32 UTC, merged

2022-04-23 11:05 UTC, skjnldsv commented
> @skjnldsv something to look into it next week, but I think this broke one integration test

I wondered this too, but I cannot reproduce locally :thinking:

2022-09-06 09:38 UTC, zak39 commented
Is it possible to declare sccs in a Vue template ?

2022-09-06 09:39 UTC, skjnldsv commented
> Is it possible to declare sccs in a Vue template ?

Yes, we use scss in vue apps almost everywhere :)