Require a recent phpunit version in integration and acceptance
nextcloud/server pull request #31761
Opened 2022-03-30 14:14 UTC by come-nc

Otherwise build with PHP>8 will fail as PHPUnit 6 does not support it

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-03-31 08:00 UTC, danxuliu requested changes
Changing `Assert::assertContains` to `Assert::assertStringContainsString` is also needed in some integration tests; there might be other changes needed too, but I have not checked.

2022-04-04 11:47 UTC, nickvergessen approved these changes

2022-05-24 11:16 UTC, CarlSchwan commented on build/integration/composer.json
> +    "phpunit/phpunit": "^8 | ^9",
```suggestion
    "phpunit/phpunit": "^9",
```

> Please note that [PHPUnit 8 is only supported until February 5, 2021](https://phpunit.de/supported-versions.html). Also note that PHP 7.2 [is no longer actively supported](https://secure.php.net/supported-versions.php).

2022-05-24 18:45 UTC, CarlSchwan approved these changes

2022-05-24 19:09 UTC, danxuliu approved these changes
I fixed the remaining failures, rebased on latest master and squashed the fixups; CI is happy, so :+1:

2022-05-24 20:18 UTC, merged