fix default value for logdateformat
nextcloud/server pull request #3178
Opened 2017-01-20 02:09 UTC by MorrisJobke

- fixes #3107 
- no functional change - only streamlines to use the very same code instead of different codes for the same value

cc @j-ed

2017-01-20 07:38 UTC, nickvergessen approved these changes

2017-01-23 09:01 UTC, icewind1991 requested changes

2017-01-23 09:01 UTC, icewind1991 commented on lib/private/Console/TimestampFormatter.php
> +		$timestampInfo = $time->format($this->config->getSystemValue('logdateformat', \DateTime::ISO8601));
`\DateTime::ISO8601` isn't actually ISO8601 (https://secure.php.net/manual/de/class.datetime.php#datetime.constants.iso8601),  `DateTime::ATOM` is the one you're looking for

2017-01-23 11:08 UTC, nickvergessen commented on lib/private/Console/TimestampFormatter.php
> +		$timestampInfo = $time->format($this->config->getSystemValue('logdateformat', \DateTime::ISO8601));
wow php, Y U not add `@deprecated` :(

2017-01-23 19:36 UTC, MorrisJobke commented on lib/private/Console/TimestampFormatter.php
> +		$timestampInfo = $time->format($this->config->getSystemValue('logdateformat', \DateTime::ISO8601));
Sadly not what we currently log: https://secure.php.net/manual/en/function.date.php (the `c` also contains the colon) ... and I will for sure not change this format 🙈

2017-01-23 19:38 UTC, MorrisJobke commented on lib/private/Console/TimestampFormatter.php
> +		$timestampInfo = $time->format($this->config->getSystemValue('logdateformat', \DateTime::ISO8601));
@karlitschek I'm open for changing this to proper ISO8601 - we just need to make sure we put it into the release notes.

2017-01-23 20:39 UTC, icewind1991 commented
Can we use actual ISO8601 instead of the almost ISO8601 with the notice?

2017-01-24 00:18 UTC, MorrisJobke commented
> Can we use actual ISO8601 instead of the almost ISO8601 with the notice?

But then we break all (log management) setups that rely on the fact that our log date contains the `:` 😉

2017-01-26 04:11 UTC, MorrisJobke commented
@icewind1991 can we get this in and decide on the log time format afterwards? Thanks :)

2017-01-27 10:02 UTC, icewind1991 approved these changes

2017-01-27 11:08 UTC, merged

2017-01-30 14:02 UTC, nickvergessen commented
Actually you now changed the format: https://3v4l.org/MRe6f
```
var_dump(date('c'));
var_dump(date(\DateTime::ISO8601));
var_dump(date(\DateTime::ATOM));
---
string(25) "2017-01-30T15:00:45+01:00"
string(24) "2017-01-30T15:00:45+0100"
string(25) "2017-01-30T15:00:45+01:00"
```

So I will adjust this to ATOM

2017-01-30 16:46 UTC, MorrisJobke commented
> Actually you now changed the format:

I'm now totally confused ... -.- the PHP doc says something different.

2017-01-30 16:48 UTC, MorrisJobke commented
> I'm now totally confused ... -.- the PHP doc says something different.

Ah okay - got it.

2017-01-30 16:48 UTC, MorrisJobke commented
> Ah okay - got it.

I compared the new format not to the new format but to itself 🙈