Add settings to ignore second display name in search
nextcloud/server pull request #31932
Opened 2022-04-11 16:35 UTC by artonge

When LDAP backend is used and a second Display name property is set, the display name value will look like that: "First Display Name (Second Display Name)". This break user search when autocomplete is deactivated.

This PR adds a setting to match the first display name with a totally not bulletproof regexp.

Fix https://github.com/nextcloud-gmbh/customer-feature-requests/issues/6

2022-04-11 17:01 UTC, PVince81 commented on lib/private/Collaboration/Collaborators/UserPlugin.php
> +				(strtolower(preg_replace('/ (.*)$/', '', $userDisplayName)) === $lowerSearch && $shareeEnumerationIgnoreSecondDisplayName) ||
maybe swap the conditions so we don't run the regexp code if the flag is disabled (conditions are executed from left to the right)

2022-04-12 07:30 UTC, PVince81 reviewed
Looks nice. Can you also add a unit test ? I see we already have a Collaborators/UserPluginTest

2022-04-12 12:07 UTC, artonge commented
> Looks nice. Can you also add a unit test ? I see we already have a Collaborators/UserPluginTest

Done

2022-04-12 14:38 UTC, PVince81 approved these changes
Nice, thanks a lot! :+1:

2022-04-12 14:43 UTC, blizzz requested changes

2022-04-12 14:52 UTC, artonge commented on lib/private/Collaboration/Collaborators/UserPlugin.php
> +				($this->shareeEnumerationFullMatchIgnoreSecondDisplayName && strtolower(preg_replace('/ \(.*\)$/', '', $userDisplayName)) === $lowerSearch) ||
Yes, why not :)

2022-04-12 14:56 UTC, artonge commented on lib/private/Collaboration/Collaborators/UserPlugin.php
> +				($this->shareeEnumerationFullMatchIgnoreSecondDisplayName && strtolower(preg_replace('/ \(.*\)$/', '', $userDisplayName)) === $lowerSearch) ||
Done

2022-04-13 07:44 UTC, blizzz approved these changes

2022-04-13 07:52 UTC, merged

2022-05-09 13:45 UTC, artonge commented
/backport to stable22

2022-05-09 13:46 UTC, artonge commented
/backport to stable23

2022-05-11 13:06 UTC, artonge commented
/backport to stable24