Update core to PHP 7.4 standard
nextcloud/server pull request #31948
Opened 2022-04-12 15:57 UTC by CarlSchwan

- Typed properties
- Port to LoggerInterface

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

2022-04-12 16:28 UTC, artonge commented on core/Command/App/Update.php
>  use OCP\ILogger;
Remove?

2022-04-12 16:28 UTC, artonge commented on core/Command/Encryption/ChangeKeyStorageRoot.php
> +use OC\URLGenerator;
Not sure why it's added

2022-04-12 16:28 UTC, artonge commented on core/Controller/AvatarController.php
> +								?string $userId,
Why optional?

2022-04-12 16:28 UTC, artonge commented on core/Controller/ClientFlowLoginController.php
> +	private function isValidToken($stateToken): bool {
```suggestion
	private function isValidToken(string $stateToken): bool {
```

2022-04-12 16:28 UTC, artonge commented on core/Controller/SearchController.php
> +use Psr\Log\LoggerInterface;
`use OCP\ILogger;` was not removed

2022-04-12 16:28 UTC, artonge commented on core/Controller/TwoFactorChallengeController.php
> +use Psr\Log\LoggerInterface;
`use OCP\ILogger;` was not removed

2022-04-12 16:35 UTC, artonge commented on core/Controller/AvatarController.php
> +								?string $userId,
Should this be reflected on line 62?

2022-04-13 11:18 UTC, CarlSchwan commented
found some issues, don't merge

2022-04-13 14:19 UTC, blizzz requested changes
cd. https://github.com/nextcloud/server/pull/31948#issuecomment-1097930067

2022-05-05 14:58 UTC, come-nc reviewed
Please rebase and fix or explain the issues

2022-05-06 13:50 UTC, CarlSchwan commented
> found some issues, don't merge

Fixed the issues found last time and all the unit tests now pass (needed to change from ILogger to LoggerInterface there too)

2022-05-09 08:53 UTC, come-nc requested changes

2022-05-09 08:53 UTC, come-nc commented on core/Command/App/Update.php
> +						]);
```suggestion
						$this->logger->error('Failure during update of app "' . $appId . '"', [
							'app' => 'app:update',
							'exception' => $e,
						]);
```

2022-05-09 08:53 UTC, come-nc commented on lib/private/Repair/NC22/LookupServerSendCheck.php
> +	private IConfig$config;
Maybe cs:fix would fix those?

2022-05-09 09:24 UTC, come-nc approved these changes

2022-05-09 09:37 UTC, CarlSchwan commented on core/Command/Encryption/DecryptAll.php
> +			return 1;
To me this is more readable. There is no need for an else block if we already return in the if bloc. This makes the code less nested and more linear.

2022-05-24 07:24 UTC, come-nc commented
@artonge @blizzz Should be good for merging now?

2022-05-30 12:36 UTC, artonge approved these changes

2022-05-30 12:37 UTC, merged