[WIP] Make apps settings tabular
nextcloud/server pull request #3195
Opened 2017-01-22 16:30 UTC by eppfel

Based on https://github.com/nextcloud/server/pull/2533#issuecomment-267641134 I introduced a table for the installed apps and removed Authors and description from the apps, because this view is mostly for managing your installation. (And shortened the "Enable only for specific groups" -> "Limit to groups")

I introduce a category "All installed" and set it as default. This view is sorted be enabled/disabled -> level (official/not) -> natural (name, ...)

We have to discuss which info is essential (Link to store/docs/repo/...). For now I introduced a link to the store, but this breaks on apps, which are not from the store. How do I get this data from an App? Internal only works to get apps, which are delivered with Nextcloud.

- [ ] Which info to show and how (view in store)
- [ ] Introduce a proper table header (we could use this to remove the "limit to groups" completely)
- [ ] tooltip for enable-groups
- [ ] icons are not perfectly in the middle, yet 
- [ ] Tests

@nextcloud/designers

2017-01-22 16:33 UTC, eppfel commented
![app-tabular kopie](https://cloud.githubusercontent.com/assets/1899308/22183900/c3163cf8-e0c8-11e6-894f-b412ca598037.png)

2017-01-22 16:35 UTC, skjnldsv commented
@eppfel Nice for an easy search. You may want to reduce the opacity of icons to 0.5 though :)

2017-01-22 16:44 UTC, eppfel commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
@skjnldsv any concerns with this?

2017-01-22 16:46 UTC, skjnldsv commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
Why not use opacity?

2017-01-22 16:46 UTC, eppfel commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
I would like to change this to color: rgba($color, .5) with the switch to scss

2017-01-22 16:47 UTC, eppfel commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
The border is transparent as well then

2017-01-22 16:47 UTC, skjnldsv commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
Where will the $color var comes from?

I havent implemented the variables yet :)

2017-01-22 16:54 UTC, eppfel commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
I do not plan to switch to scss with this PR 😁 Just was not sure, if it safe to switch

2017-01-22 16:55 UTC, skjnldsv commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
Test and we'll see :p

2017-01-22 17:02 UTC, skjnldsv commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
hum, since this is located outside core/css it won't work.
The function isn't implemented yet.

It's planned though :)

2017-01-22 17:04 UTC, skjnldsv commented on settings/css/settings.css
> +	color: rgba(85,85,85,.5);
Hum bis: in fact it will work. But I cant't guarantee that it will properly yet :/

2017-01-23 06:39 UTC, jancborchardt commented
Hmm, I’m not entirely sure about this since we will want to make screenshots more important in the future. Also it corresponds to a grid view that we might want to introduce for the Files app.

What do you think here @LukasReschke @MorrisJobke?

2017-01-23 06:41 UTC, jancborchardt commented
> I introduce a category "All installed" and set it as default.

The default view should be a new category »All apps«. Changing category just for installing apps is what’s already cumbersome right now. ;)

2017-01-23 09:57 UTC, eppfel commented
Just to make this clear again. This is only for __installed apps__. Appstore categories will be in another PR (see #3194) and I am positive on the larger screenshots.

> Hmm, I’m not entirely sure about this since we will want to make screenshots more important in the future.

I think we have to acknowledge that there are two major use-cases. 
1. Installing new apps
    1. explorative: What (new) apps are there?
    1. targeted: I want to install x?
1. Manage apps
    1. targeted: App x is not useful/broken/etc. and I want to remove it?
    1. targeted: The updater disabled some Apps, let's see and reenable.
    1. targeted: There are updates, do them.

I think the explorative use is very seldom and you might do this in the appstore right now.
The targeted new install will probably be by a search in an "All available apps" category (see #3194 ) and 
All managing use-cases are (mostly) directed and in my experience happen more often. The tabular view is just too show more apps in one view. And screenshots not add anything here, because you already know the apps and probably remember their icons.

Mac app store for example:

![appstore-explore](https://cloud.githubusercontent.com/assets/1899308/22198911/ec7ce43a-e158-11e6-9c19-f662c75215dc.png)
![appstore-bought](https://cloud.githubusercontent.com/assets/1899308/22198915/ee5dbfcc-e158-11e6-9c15-a15a7d220c95.png)

> The default view should be a new category »All apps«. Changing category just for installing apps is what’s already cumbersome right now. ;)

"All installed": The idea is to manage installed apps in one place, rather than two (disabled / enabled).
We can introduce the "All available" in a next step and set it default then, but still I would like introduce "All installed" because with more and more apps in the store, these might disturb the user. What's your take on that @jancborchardt ?

Further. installing new apps happens less often, so another click is unproblematic IMO. And once selected the category changes,. So even if you install a bunch of new apps with a new installation, you hit "All available" once and then search the apps you need one after another.


And I need feedback on leaving out meta, like author aso.

2017-01-23 13:55 UTC, Espina2 commented
This is very good. The offical tag is just weird, it looks like a button. Can we transform this in a normal text style? @eppfel @jancborchardt

2017-01-23 15:55 UTC, jancborchardt commented
@eppfel ok, agree on the layout. I thought about it more too, and thanks a lot for the added design reasoning. :)

> "All installed": The idea is to manage installed apps in one place, rather than two (disabled / enabled).

Installed == enabled though. We should not introduce another word or concept here. Maybe we should switch the wording from »Enabled / Not enabled« to »Installed / Not installed« (and »Install / Uninstall« on the buttons) but definitely not use both words at the same time.

> Further. installing new apps happens less often, so another click is unproblematic IMO.

Installing new apps is definitely as big of a use case as managing the current ones is. See also the existing issue: »All apps« category in apps management #126


Another thing btw talking about simplifying and streamlining the management: We should link from the list of installed apps to the settings section of each app. :) Also cc @nickvergessen

2017-01-23 17:34 UTC, eppfel commented
That's how it looks right now.
<img width="1210" alt="bildschirmfoto 2017-01-23 um 17 49 41" src="https://cloud.githubusercontent.com/assets/1899308/22213434/88f33b62-e194-11e6-85a0-d3352713a4c9.png">

>  The offical tag is just weird, it looks like a button. Can we transform this in a normal text style?

@Espina2 Yes, this needs rework. We might want to introduce batches/chips?
But the question is, do we need this info there anyway?

<img width="710" alt="bildschirmfoto 2017-01-23 um 17 58 17" src="https://cloud.githubusercontent.com/assets/1899308/22213772/a12223be-e195-11e6-9c3a-a9d1ebcef5e1.png">

> Installed == enabled though. We should not introduce another word or concept here. Maybe we should switch the wording from »Enabled / Not enabled« to »Installed / Not install

@jancborchardt 
But technically there is a difference.
- Installed / not installed: is the app present on your installation or not
- enabled / not enabled: is the app active and can be used

I believe admins care for the difference.

After reading #126 "All installed" does exactly this (even the sorting). But I guess you want the appstore categories included as well, right?

I move the discussion about the apps management structure / navigation / categories to the overview issue #3194

2017-01-23 18:09 UTC, Espina2 commented
Another problem is the iconography used to represent the apps is not unique enough. We already use the same icons to others things... But in the other hand I know its hard to have more unique icons on this... 

Anyway its looks a lot better @eppfel .

2017-01-25 10:36 UTC, eppfel commented
Ok, I want to get this in, so let's _warp_ things up. 

![warp speed](http://i.imgur.com/hqNC1Qw.gif)

I'll postpone:

- Which info to show and how (view in store) -> Bigger issue and should be easy to integate later into the tabular layout
- Introduce table header -> for now columns are self-explanatory
- tooltip for enable-groups -> kind of dependents on the two previous points

The two questions remaining is

#### 1. the navigation:

I propose: Drop enabled and disabled and make it into one category: "Enabled/Disabled" or "Installed". Either way, it is an improvement to have all _installed_ apps in one view. See #3194 for broader discussion.

#### 2. dynamic sorting

When enabling an app should the list be sorted and the app jump up. I say we leave the app, where it is, to not confuse the user.

2017-01-25 14:27 UTC, claell commented
1. I agree that your proposal of the category "installed" offers the same functionality as "enabled" and "disabled". So they can be dropped.
However I'd change the name to not confuse the user to something like "downloaded". Installed means the same as enabled to me.
This clarifies the whole situation a bit more. When I first used the app store I did not know what exactly "enabled" and "disabled" is and that there can be downloaded but not enabled apps.

2. How are the apps sorted right now? Alphabetically? It might be helpful to have some order and having all enabled apps on top might lead to better usability. If this is not done dynamically I'd propose to leave the position where it is when inside the category and show it resorted on next visit.

2017-01-25 14:52 UTC, eppfel commented
1. Maybe we have to rethink, the enabled / disabled,  installed / not installed paradigm then. E.g. Do not differentiate at all

2. As stated above, sorting is enabled -> official -> name. Opening a category triggers sorting automatically.

2017-01-25 16:17 UTC, claell commented
2. Sorry didn't read that carefully enough. To me it makes sense to leave it that way to avoid confusing the user as you said. It probably wouldn't be good to have an app move to the top right after the user clicks on "enable".

2017-02-21 14:52 UTC, jancborchardt commented
@eppfel any update here, or a minimum version we can merge? :) Would be cool to get this in for Nextcloud 12.

2017-02-22 23:10 UTC, eppfel commented
> 1. the navigation:
>
>I propose: Drop enabled and disabled and make it into one category: "Enabled/Disabled" or "Installed". Either way, it is an improvement to have all installed apps in one view. See #3194 for broader discussion.

@jancborchardt This decision blocks this PR right now.

2017-03-28 19:27 UTC, jancborchardt commented
@eppfel sorry for  the late reply!

> I propose: Drop enabled and disabled and make it into one category: "Enabled/Disabled" or "Installed"

I fully agree with that. Let’s just call it »Your apps« as other appstores do it similarly. Sort enabled apps first of course.

@eppfel is it possible to get this in for Nextcloud 12? Would be awesome to, and please ask if you need help. :)

2017-03-28 23:42 UTC, jancborchardt commented
@eppfel I’d say let’s merge this and do further adjustments in separate pull requests … it’s getting too big and we just need to move forward. :)

2017-03-29 00:29 UTC, MorrisJobke commented
Only two items:

* [ ] show spinner for changing the different sections in the middle (like on the initially loading)
![bildschirmfoto 2017-03-28 um 18 26 12](https://cloud.githubusercontent.com/assets/245432/24433209/5bdba254-13e4-11e7-8621-288508b4d827.png)
* [ ] show a spinner for the images of the app store apps (and a placeholder for those that don't have one - otherwise it looks broken)
![bildschirmfoto 2017-03-28 um 18 25 49](https://cloud.githubusercontent.com/assets/245432/24433233/77067dce-13e4-11e7-90af-3cd9b3f0fc5a.png)

2017-03-29 10:08 UTC, jancborchardt commented
Will look into the spinner.

How can I check for if an app doesn’t have an image? cc @BernhardPosselt @eppfel?

2017-03-29 10:10 UTC, BernhardPosselt commented
The screenshots attribute on the returned JSON will be empty, see http://nextcloudappstore.readthedocs.io/en/latest/restapi.html#get-all-apps-and-releases

Unsure however how this is implemented in the server @LukasReschke

2017-04-04 16:26 UTC, MorrisJobke commented
@jancborchardt Ping

2017-04-05 06:06 UTC, eppfel commented
> @jancborchardt Ping

Pong.

I can look at it thursday

2017-04-05 19:44 UTC, eppfel commented
@jancborchardt @nextcloud/designers 

Removing `limit to groups` on mobile view looks cleaner. But removing/hiding functionality completely from the user feels wrong.
<img width="660" alt="bildschirmfoto 2017-04-05 um 21 00 21" src="https://cloud.githubusercontent.com/assets/1899308/24722201/21eb375c-1a43-11e7-8bbf-68b3eee9f6ea.png">

I know it looks shit and I don't have another idea, right now, still...
Anyone ideas, opinions?
<img width="487" alt="bildschirmfoto 2017-04-05 um 21 03 50" src="https://cloud.githubusercontent.com/assets/1899308/24722413/eeae2ae2-1a43-11e7-872e-5be7c73eb5f9.png">

2017-04-10 10:05 UTC, jancborchardt commented
@eppfel I made it so it’s visible still when there’s a bit of space and only hides when very narrow. Just because next to the disable/enable button it’s the only really important piece (cause it’s interactive). Does that not work?

2017-04-10 16:17 UTC, MorrisJobke commented
@jancborchardt What about https://github.com/nextcloud/server/pull/3195#issuecomment-289945782 ?

2017-04-24 22:24 UTC, jancborchardt commented
All issues fixed and rebased too. Ready for review @nextcloud/javascript @nextcloud/designers! :)

2017-04-25 03:49 UTC, MorrisJobke approved these changes
Tested and works :+1: I restarted the CI because JS unit tests failed with a connection timeout.

2017-04-25 03:59 UTC, MorrisJobke commented
Mmmmh ... `"/drone/src/github.com/nextcloud/server/core/vendor/DOMPurify/dist/purify.min.js" were excluded or matched by prior matchers.`

@LukasReschke You touched this lately. Any idea?

2017-04-25 06:18 UTC, ChristophWurst requested changes
Looks great!

Only two remarks:

1. "Limit to groups" is not aligned with the checkbox
![bildschirmfoto von 2017-04-25 08-13-25](https://cloud.githubusercontent.com/assets/1374172/25371166/83982f0e-298f-11e7-84eb-04ccb1a3ab39.png)

2. During enabling/disabling an app, the button text is wider and therefore causes the columns to change their size. This look a bit odd.

2017-04-25 08:21 UTC, jancborchardt commented
@ChristophWurst 

> "Limit to groups" is not aligned with the checkbox

This seems to be an issue in master actually. Will see to fix via a different PR.

> During enabling/disabling an app, the button text is wider and therefore causes the columns to change their size. This look a bit odd.

Yes, but this only occurs on narrow sizes and will be variable with languages anyway. There’s no immediate way I can think of adjusting that. We should check it out after _feature_ freeze, ok? :)

2017-04-25 08:23 UTC, ChristophWurst approved these changes
Fine by me

2017-04-25 09:33 UTC, LukasReschke commented
> Mmmmh ... "/drone/src/github.com/nextcloud/server/core/vendor/DOMPurify/dist/purify.min.js" were excluded or matched by prior matchers.
>
> @LukasReschke You touched this lately. Any idea?

Not a lot of ideas since it works locally but https://github.com/nextcloud/server/pull/4486 could be it.

2017-04-25 13:25 UTC, MorrisJobke commented
Okay - the JSUnit failure is unrelated -> merge it.

2017-04-25 13:25 UTC, merged

2017-04-25 13:27 UTC, MariusBluem commented
Awesome 🎉🙈

2017-04-25 14:16 UTC, jancborchardt commented
Awesome work @eppfel! :tada: