Start porting Admin audit to new events
nextcloud/server pull request #32019
Opened 2022-04-19 18:43 UTC by CarlSchwan

2022-04-20 09:15 UTC, nickvergessen commented on apps/admin_audit/lib/Actions/Auth.php
> +			$this->logout($event->getUser()->getUID());
PossiblyNullReference reported by psalm.
I know it can't occure, but may we add a check around it?

2022-04-20 09:19 UTC, nickvergessen commented on apps/user_ldap/lib/Jobs/Sync.php
> +				$this->dispatcher,
missing from constructor?

2022-04-25 10:56 UTC, nickvergessen commented on apps/user_ldap/lib/Jobs/Sync.php
> +			$this->dispatcher = $argument['dispatcher'];
I can not approve this 🦺 
The dispatcher should never be written into the database just like any other dependency.

I think this is from legacy cases where background jobs didn't have DI (I assume from the function doc `"fixes" DI`) and it basically always uses the else. But it should just go into the normal constructor nowadays

2022-04-25 15:29 UTC, nickvergessen requested changes
Or am I missing something?

2022-04-25 15:29 UTC, nickvergessen commented on apps/user_ldap/lib/Jobs/Sync.php
> +	public function __construct(Manager $userManager) {
```suggestion
	public function __construct(Manager $userManager, IEventDispatcher $dispatcher) {
```

2022-04-25 15:29 UTC, nickvergessen commented on apps/user_ldap/lib/Jobs/Sync.php
> +		$this->dispatcher = \OC::$server->get(IEventDispatcher::class);
```suggestion
		$this->dispatcher = $dispatcher;
```

2022-04-25 16:42 UTC, CarlSchwan commented on apps/user_ldap/lib/Jobs/Sync.php
> +	public function __construct(Manager $userManager) {
Sorry I pushed intermediate stuff :( There are only two class that needs to be set manually in the test and the rest is all using DI

2022-04-26 05:59 UTC, nickvergessen approved these changes
Half 🐘

2022-04-26 09:52 UTC, come-nc commented on apps/user_ldap/ajax/clearMappings.php
> +use OCP\User\Events\BeforeUserIdUnAssignedEvent;
I think unassigned is one word and it should be `BeforeUserIdUnassignedEvent`, no?

2022-04-26 09:52 UTC, come-nc commented on apps/admin_audit/lib/Actions/UserManagement.php
> +		if ($event instanceof UserDeletedEvent) {
elseif would be better for all those ifs unless I’m missing something.

2022-04-26 09:52 UTC, come-nc commented on apps/user_ldap/lib/Jobs/Sync.php
> +use OCA\User_LDAP\User\User;
sort the imports please

2022-04-26 09:52 UTC, come-nc commented on apps/user_ldap/lib/Jobs/Sync.php
> +	) {
Was this change tested?

2022-04-26 09:52 UTC, come-nc commented on apps/user_ldap/lib/Mapping/AbstractMapping.php
> +		} while (count($fdnsSlice) === 1000);
```suggestion
		} while (count($fdnsSlice) >= 1000);
```
Or is that too paranoid?

2022-04-26 09:52 UTC, come-nc commented on lib/composer/composer/autoload_classmap.php
> +    'OCP\\User\\Events\\UserIdAssignedEvent' => $baseDir . '/lib/public/User/Events/UserIdAssignedEvent.php',
Where are the two other ones?

2022-04-26 09:52 UTC, come-nc commented on lib/public/User/Events/BeforeUserIdUnassignedEvent.php
> +	private string $name;
It’s not clear to me right away what name is in those events, it is the nextcloud name of the user? Is that called name in all user related events?

2022-04-26 09:52 UTC, come-nc commented on lib/public/User/Events/BeforeUserIdUnassignedEvent.php
> +class BeforeUserIdUnAssignedEvent extends Event {
Are those events generic and not LDAP specific?

2022-04-26 09:53 UTC, blizzz reviewed
Questions

2022-04-26 09:53 UTC, blizzz commented on apps/admin_audit/lib/Actions/GroupManagement.php
> +			$this->addUser($event->getGroup(), $event->getUser());
UserRemovedEvent → addUser? 🤔

2022-04-26 09:54 UTC, blizzz commented on lib/public/User/Events/BeforeUserIdUnassignedEvent.php
> +class BeforeUserIdUnAssignedEvent extends Event {
Should be treated as generic.

2022-05-05 19:56 UTC, CarlSchwan commented on apps/user_ldap/lib/Jobs/Sync.php
> +	) {
the cron job ran without issue multiple times, unit tests are also happy.

2022-05-24 07:31 UTC, come-nc commented on apps/admin_audit/lib/Actions/GroupManagement.php
> +		} else if ($event instanceof GroupDeletedEvent) {
```suggestion
		} elseif ($event instanceof UserRemovedEvent) {
			$this->removeUser($event->getGroup(), $event->getUser());
		} elseif ($event instanceof GroupCreatedEvent) {
			$this->createGroup($event->getGroup());
		} elseif ($event instanceof GroupDeletedEvent) {
```

2022-05-24 07:31 UTC, come-nc commented on apps/admin_audit/lib/Actions/UserManagement.php
> +		} else if ($event instanceof PasswordUpdatedEvent) {
```suggestion
		} elseif ($event instanceof UserDeletedEvent) {
			$this->delete($event->getUser()->getUID());
		} elseif ($event instanceof UserChangedEvent) {
			$this->change($event);
		} elseif ($event instanceof UserIdAssignedEvent) {
			$this->assign($event->getUserId());
		} elseif ($event instanceof UserIdUnassignedEvent) {
			$this->unassign($event->getUserId());
		} elseif ($event instanceof PasswordUpdatedEvent) {
```

2022-06-21 10:02 UTC, come-nc approved these changes

2022-06-24 08:49 UTC, blizzz requested changes

2022-06-24 08:49 UTC, blizzz commented on apps/user_ldap/lib/Proxy.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
make $dispatcher static, otherwise it will be null on the next runs.

2022-06-27 08:49 UTC, come-nc commented on apps/user_ldap/lib/Proxy.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
Why? Is that specific to IEventDispatcher?

2022-06-27 10:36 UTC, come-nc commented on apps/user_ldap/lib/Proxy.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
Ok understood, nice catch.

2023-03-13 17:55 UTC, tcitworld commented
I've pulled most of this in #37193, **apart from** the heavier refactoring from `AbstractMapping` that isn't related.

2023-03-13 18:18 UTC, tcitworld commented
Closing here in favor of https://github.com/nextcloud/server/pull/37193

2023-03-13 18:18 UTC, closed without merging