Fix scanning app data with metadata
nextcloud/server pull request #32033
Opened 2022-04-21 08:01 UTC by CarlSchwan

Previously we were listening to changes in the appdata folder but an
appdata scan didn't set up the file system, so the view was unavailable.

**Test plan:**

1. `rm -rf data/appdata_...../preview data/<user>/Media`
2. `occ files:scan-app-data`
3. `occ files:scan <user>`

No errors and the files and metadata are correctly removed from the
database too.

2022-04-21 08:16 UTC, artonge commented on lib/private/Metadata/FileEventListener.php
> +				// the file system.
If this is not supposed to happen, I would throw an exception here instead of returning.

2022-04-21 08:24 UTC, CarlSchwan commented on lib/private/Metadata/FileEventListener.php
> +				// the file system.
Not sure this is a good idea to throw an error as this would abord the scan but I should definitively at least log it as an error.

2022-04-22 07:52 UTC, skjnldsv approved these changes

2022-04-22 09:32 UTC, skjnldsv commented on lib/private/Metadata/FileEventListener.php
>  	private IMetadataManager $manager;
```suggestion
	private IMetadataManager $manager;
	private LoggerInterface $logger;
```

2022-04-22 09:32 UTC, skjnldsv requested changes

2022-04-22 09:32 UTC, skjnldsv commented on lib/private/Metadata/FileEventListener.php
> +				$this->log->error('Detecting deletion of a file with possible metadata but file system setup is not setup', [
```suggestion
				$this->logger->error('Detecting deletion of a file with possible metadata but file system setup is not setup', [
```

2022-04-22 09:32 UTC, skjnldsv commented on lib/private/Metadata/FileEventListener.php
>  	private IMetadataManager $manager;
```suggestion
	private IMetadataManager $manager;
	private LoggerInterface $logger;
```

2022-04-22 14:10 UTC, skjnldsv approved these changes

2022-04-25 13:49 UTC, PVince81 approved these changes
:+1:

2022-04-25 13:50 UTC, merged

2022-04-25 13:50 UTC, PVince81 commented
/backport to stable24