Check maintenance window time when using WebCron
nextcloud/server pull request #32107
Opened 2022-04-23 13:49 UTC by k-popov

The patch moves maintenance window check earlier so that
maintenance window was respected when using both system cron
and WebCron. Before the change webcron used to select
**only** time-sensitive tasks.

Signed-off-by: Kirill Popov <kirill.s.popov@gmail.com>

2022-04-23 14:17 UTC, nickvergessen reviewed
Tkme sensitivity should only be considered for cron, not for web or ajax

2022-04-23 15:13 UTC, nickvergessen requested changes

2022-04-23 15:13 UTC, nickvergessen commented on cron.php
> +			$job = $jobList->getNext($onlyTimeSensitive);
The actual fix would be to just inject false here or change the default of the method

2022-04-23 15:38 UTC, k-popov commented on cron.php
> +			$job = $jobList->getNext($onlyTimeSensitive);
Could you please comment why?
I'm running NextCloud in Kubernetes and thus I can't use system cron daemon. Having Kubernetes' `CronJob` is a solution - it runs periodically and "curl's" `cron.php`. In this setup I still have short background jobs and time-sensitive ones which I want to run during maintenance hours.

2022-04-24 12:09 UTC, k-popov commented
I've opened #32109 with argument default change.

2022-04-24 12:09 UTC, closed without merging

2022-04-25 10:31 UTC, nickvergessen commented on cron.php
> +			$job = $jobList->getNext($onlyTimeSensitive);
Explanation in https://github.com/nextcloud/server/issues/30899#issuecomment-1108360345