cache the storage info for 5 min
nextcloud/server pull request #3214
Opened 2017-01-23 13:55 UTC by icewind1991

For most external storages getting the storage info is expense

Since the storage info doesn't change often we cache it for 5 min

[comparison when using fed. share](https://blackfire.io/profiles/compare/b057d8a2-b828-4fbf-a97f-72c78b3a1026/graph)

2017-01-23 16:43 UTC, MorrisJobke commented
Does that also mean that when you are uploading still the old storage info is used and you maybe could upload more than allowed?

2017-01-23 16:45 UTC, icewind1991 commented
Free space is still checked on upload

2017-01-23 19:25 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-01-24 08:47 UTC, nickvergessen requested changes

2017-01-24 08:47 UTC, nickvergessen commented on lib/private/legacy/helper.php
> +		$cached = $memcache->get($rootInfo ? '__root__' : $path);
memcached has a limit of 250 chars. So you need to sha1 or something the path here.

2017-01-24 10:18 UTC, icewind1991 commented on lib/private/legacy/helper.php
> +		$cached = $memcache->get($rootInfo ? '__root__' : $path);
Done

2017-01-24 12:23 UTC, nickvergessen approved these changes

2017-01-24 12:49 UTC, merged

2017-02-16 18:03 UTC, MorrisJobke commented on lib/private/legacy/helper.php
> +		}
This is not unique across users. So this exposed the storage info of the user in the cache to all other users. Therefore I reverted this. #3515

Please come up with a proper implementation. And also take care of invalidate the cache when setting the quota.