Fix getting shares in a folder on Oracle
nextcloud/server pull request #32185
Opened 2022-04-27 12:48 UTC by CarlSchwan

Reported here https://github.com/nextcloud/server/issues/28960#issuecomment-1110912934

CC @nicro87

2022-04-27 12:49 UTC, CarlSchwan commented on lib/private/Share20/DefaultShareProvider.php
> +		if (count($childMountRootIds) === 0) {
maybe could be replaced by a do while loop, not sure that is the more elegant here ...

2022-04-28 07:41 UTC, nicro87 commented
carry forward from comment https://github.com/nextcloud/server/issues/28960#issuecomment-1110912934
---

Hi @CarlSchwan

I tried your fix and it works for me. All errors are gone.

Thanks again for the quick help,
Nico

2022-04-28 08:37 UTC, come-nc requested changes

2022-04-28 08:37 UTC, come-nc commented on lib/private/Share20/DefaultShareProvider.php
> +		if (count($childMountRootIds) === 0) {
What about:
```
if (count($childMountRootIds) === 0) {
  $chunks = [[]];
} else {
  $chunks = array_chunk($childMountRootIds, 1000);
}
```

And then the same foreach as below?

2022-05-02 10:09 UTC, come-nc approved these changes

2022-05-09 13:24 UTC, artonge approved these changes

2022-05-09 13:24 UTC, artonge commented on lib/private/Share20/DefaultShareProvider.php
> +		}
Don't know, might be more readable :)

```suggestion
		$chunks = array_chunk($childMountRootIds, 1000);

		// Force the request to be run when there is 0 mount.
		if (count($chunks) === 0) {
			$chunks = [[]];
		}
```

2022-05-12 18:58 UTC, merged

2022-09-21 09:25 UTC, PVince81 commented
/backport to stable24