WIP: Fix performance problem when searching for users in the groupfolder app
nextcloud/server pull request #32201
Opened 2022-04-28 06:45 UTC by CarlSchwan

Todo:

- [ ] Add tests
- [ ] Add new method in a new interface

2022-05-03 07:47 UTC, come-nc commented on apps/user_ldap/lib/GroupPluginManager.php
> +				return -1;
Document this situation in `@return`
Is this correctly handled in the calling code? When does it happen, why not throwing as the function can already throw in some cases?

2022-05-03 07:47 UTC, come-nc commented on apps/user_ldap/lib/GroupPluginManager.php
> +				return [];
Same thing, even worse because here a gid was passed so if it is not existing it should trigger a not found error I suppose?

2022-05-03 07:47 UTC, come-nc commented on apps/user_ldap/lib/Group_LDAP.php
> +	protected CappedMemoryCache $cachedNestedGroups;
I can see the merging conflict hell approaching with the nested group refactor PR, but let’s do this.
We should definitely try to merge the nested group refactor while 25 is still young though, to move forward on this subject.

2022-05-03 07:47 UTC, come-nc commented on apps/user_ldap/lib/Group_LDAP.php
> -		parent::__construct($access);
No constructor in parent?
Maybe call it even if empty?

2022-05-03 07:47 UTC, come-nc commented on apps/user_ldap/lib/Group_Proxy.php
> +			if (is_array($backendUsers)) {
This is not always true?

2022-05-03 07:47 UTC, come-nc commented on lib/private/Diagnostics/QueryLogger.php
> +			$this->index++;
Why this change? The previous syntax with `[]` is not working with CappedMemoryCache?

2022-05-03 07:47 UTC, come-nc commented on lib/private/Group/Database.php
> +			}
```suggestion
			// TODO maybe also fetch the displayname directly here
			$users[] = new LazyUser($row['uid'], $displayNameCache, $userManager, $row['displayname'] ?? null);
```

Also why $displayNameCache and $userManager are not get from \OC::$server in LazyUser class instead?

2022-05-03 07:47 UTC, come-nc commented on lib/private/Group/Group.php
> -	 * @return \OC\User\User[]
`@return IUser[]`

2022-05-03 07:50 UTC, CarlSchwan commented on apps/user_ldap/lib/GroupPluginManager.php
> +				return -1;
Actually probably the returned value should be 0

2022-05-03 07:52 UTC, CarlSchwan commented on lib/private/Diagnostics/QueryLogger.php
> +			$this->index++;
Yeah CappedMemoryCache expects a key of the type string

2022-05-03 07:52 UTC, CarlSchwan commented on lib/private/Group/Database.php
> +			}
Because then you need to get the value for each iteration of the loop

2022-05-03 07:55 UTC, CarlSchwan commented on apps/user_ldap/lib/GroupPluginManager.php
> +				return [];
I looked a bit and we usually check if the groupDetails returned is empty or false when using the legacy signature.

This should indeed be better documented

2022-05-05 15:34 UTC, come-nc approved these changes

2022-05-05 20:59 UTC, blizzz requested changes
All nice, with the one downside that the search now happens on terms of the group backend. Group backends able to contain users of mixed user backends thus do not utilize the search methods of the user backends. For example, when normally you can find "Jeanne Doe" of LDAP by her employee number 123456, you cannot achieve the same when search for her in the local group. The sad thing of course is that the owning user backend does not know about this relationship, so searching there will would also be painfully slow (likely better than now, but still). 

With that in mind, this approach may be acceptable with this known limitation (that should be documented somewhere). Additional the slower search can be offered still and enabled via config option – and as opt-in. Searching for display name* and email is the default case after all.

*also there might be different results

2022-05-05 20:59 UTC, blizzz commented on apps/user_ldap/lib/GroupPluginManager.php
> +			return $count;
```suggestion
			return (int)$plugin->countUsersInGroup($gid,$search);
```
?

2022-05-05 20:59 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +	public function countUsersInGroup(string $gid, string $search = ''): int {
maybe nullify it…  when a count is not provided for reasons the various reasons, return 0 is technically not correct. It didn't doublecheck consumers, but syntactically it would be more reasonable. Can still be cast to int if necessary.

2022-05-05 20:59 UTC, blizzz commented on apps/user_ldap/lib/Group_Proxy.php
> +	public function countUsersInGroup(string $gid, string $search = ''): int {
with the comment earlier, would also returning `?int`.

2022-05-05 20:59 UTC, blizzz commented on apps/user_ldap/lib/Group_Proxy.php
> +			$users = array_merge($users, $backendUsers);
utilize `handleRequest` to only search that backend that actually owns the group.

2022-05-05 20:59 UTC, blizzz commented on lib/private/Group/Manager.php
> +		$search = trim($search);
you may have now an unnecessary trim execution ;)

2022-05-05 23:00 UTC, CarlSchwan commented on apps/user_ldap/lib/Group_LDAP.php
> +	public function countUsersInGroup(string $gid, string $search = ''): int {
Unfortunately it's not possible :( the interface defined the return type not nullable https://github.com/nextcloud/server/blob/master/lib/public/Group/Backend/ICountUsersBackend.php

2022-05-13 13:33 UTC, CarlSchwan commented on lib/private/Group/Manager.php
> +		$search = trim($search);
The ldap backend do a trim as far I can tell, but not the database backend. Best to do it here to be sure that it's done at least once everywhere

2022-05-13 13:54 UTC, CarlSchwan commented
> All nice, with the one downside that the search now happens on terms of the group backend. Group backends able to contain users of mixed user backends thus do not utilize the search methods of the user backends. For example, when normally you can find "Jeanne Doe" of LDAP by her employee number 123456, you cannot achieve the same when search for her in the local group. The sad thing of course is that the owning user backend does not know about this relationship, so searching there will would also be painfully slow (likely better than now, but still).

According to the code, the search happens like this with this patch:

- OC\Group\Manager::displayNamesInGroup
- OC\Group\Group::searchUsers - Call searchInGroup for each group backend
  - Database backend: will look for any displayname+userId with the corresponding gid
  - LDAP backend: merge the results of `getUsersInPrimaryGroup`, `getUsersInGidNumber` and `_groupMembers` (recursive)

Before:

- OC\Group\Manager::displayNamesInGroup
- OC\User\UserManager::searchDisplayName with an high limit
    - Database backend:  will look for any displayname+userId discarding the gid information
    - LDAP backend: call getUsers that then do an LDAP query with `getFilterPartForUserSearch`
- In the resulting results, look if they are part of the group
   - Database backend: a db query for each user matching the search filtr
   - LDAP backend: search if the user is in the primary group and if not do `__groupMembers` (recursive) and check if the user is found in the group members returned

So to me, this seems equivalent just faster and cleaner, unless I obliviously missed something. Maybe we should do a call on Monday to discuss this if you have time?

2022-05-25 07:41 UTC, CarlSchwan commented
ping :)

2022-05-30 07:56 UTC, CarlSchwan commented
friendly ping :)

2022-05-30 10:29 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +	public function countUsersInGroup(string $gid, string $search = ''): int {
Ok

2022-05-30 10:40 UTC, blizzz requested changes

2022-05-30 10:40 UTC, blizzz commented on lib/public/Group/Backend/ABackend.php
> +		foreach ($this->usersInGroup($gid, $search, $limit, $offset) as $userId) {
Database`s `usersInGroup` is coupled to match with the Database User backend. It would not find users of other databases when a search term is provided.

2022-06-07 10:13 UTC, artonge approved these changes

2022-06-13 15:20 UTC, CarlSchwan commented
@blizzz I reverted the changes for the search and found out instead other areas where we could improve the perf by quite a bit:

- When searching with the database group backend, cache the displayname
- Implement a batch groupExists and getGroupDetails methods (with a fallback when not implemented).

In total, with 1100 LDAP groups, these changes reduce the SQL query count from 1125 to 13. The LDAP query count is still very high (>6000) but I have a PR in groupfolder to reduce it to 30.

I'll try to split the change into multiple self-contained PRs to make it easier to review :)

2022-06-13 17:01 UTC, CarlSchwan commented
First split https://github.com/nextcloud/server/pull/32866

2024-02-27 17:37 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open and solve the various conflicts.

2024-02-27 17:37 UTC, closed without merging