Respect user settings in php.ini if they are big enough
nextcloud/server pull request #32216
Opened 2022-04-29 06:26 UTC by mickenordin

In the admin guide:
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

it is mentioned that you can tweek:
* max_input_time
* max_execution_time

in order to enable larger file uploads. However, the current codebase
will hard code these values to one hour, no matter what the user sets in
php.ini.

This patch will allow the user to set these settings in php.ini and they
will be respected, if and only if, they are set to something bigger than
3600 seconds.

2022-04-29 06:27 UTC, mickenordin commented
This fixes #32209

2022-04-29 11:33 UTC, szaimen commented
Thanks for your PR! can you please solve DCO (see https://github.com/nextcloud/server/pull/32216/checks?check_run_id=6223623697)? Thank you!

2022-04-29 12:51 UTC, mickenordin commented
> Thanks for your PR! can you please solve DCO (see https://github.com/nextcloud/server/pull/32216/checks?check_run_id=6223623697)? Thank you!

Sure, fixed.

2022-04-29 15:50 UTC, artonge commented on lib/base.php
> +		@ini_set('max_execution_time', strval($biggest_max_execution_time));
Seems a bit complicated, would a simpler version work?

```suggestion
	if (intval(@ini_get('max_execution_time')?? 0) < 3600) {
		@ini_set('max_execution_time', strval(3600));
	}
```

2022-04-29 21:42 UTC, solracsf commented on lib/base.php
> +		@ini_set('max_execution_time', strval($biggest_max_execution_time));
Well, i don't really appreciate @ in the code...but it's my own opinion.
Better to check the function exists before calling it instead.

2022-04-30 14:43 UTC, mickenordin commented on lib/base.php
> +		@ini_set('max_execution_time', strval($biggest_max_execution_time));
I have implemented the simpler solution now :)

2022-05-01 19:21 UTC, kesselb commented
Thanks for sending a pull request :+1: 

The above code should work and allow an administrator to pick a higher value. 

I think the actual issue here is that we configure `max_execution_time` and `max_input_time` at all. That code should go and we introduce a setup check to inform the administrator that an update for php.ini / user.ini / .htaccess is required to configure good limits. This auto configuration approach might be nice but it's always a pain if one needs a higher limit. My take here is that Nextcloud should not try to auto configure the environment but tell the administrator what's necessary. Less magic => less pain ;)

Also keep in mind that almost **every** request is executing this code. It's already bad to have the ini_set calls (with suppress operator) here. If we merge this patch we check on each time if there is a higher limit and if not run the ini_set call. I don't think that removing those calls will improve the performance yet it's still bad.

2022-05-02 08:42 UTC, CarlSchwan commented
> Thanks for sending a pull request +1
> 
> The above code should work and allow an administrator to pick a higher value.
> 
> I think the actual issue here is that we configure `max_execution_time` and `max_input_time` at all. That code should go and we introduce a setup check to inform the administrator that an update for php.ini / user.ini / .htaccess is required to configure good limits. This auto configuration approach might be nice but it's always a pain if one needs a higher limit. My take here is that Nextcloud should not try to auto configure the environment but tell the administrator what's necessary. Less magic => less pain ;)
> 
> Also keep in mind that almost **every** request is executing this code. It's already bad to have the ini_set calls (with suppress operator) here. If we merge this patch we check on each time if there is a higher limit and if not run the ini_set call. I don't think that removing those calls will improve the performance yet it's still bad.

For shared hosting providers, it's often not possible to modify the ini files, this is probably the reason why this is done like this currently.

2022-05-02 09:17 UTC, solracsf commented
> For shared hosting providers, it's often not possible to modify the ini files, this is probably the reason why this is done like this currently.

For shared hosting, most of the time, both are disabled (ini files and ini_set())

2022-05-02 11:38 UTC, mickenordin commented
> Thanks for sending a pull request 👍
> 
> The above code should work and allow an administrator to pick a higher value.
> 
> I think the actual issue here is that we configure `max_execution_time` and `max_input_time` at all. That code should go and we introduce a setup check to inform the administrator that an update for php.ini / user.ini / .htaccess is required to configure good limits. This auto configuration approach might be nice but it's always a pain if one needs a higher limit. My take here is that Nextcloud should not try to auto configure the environment but tell the administrator what's necessary. Less magic => less pain ;)
> 
> Also keep in mind that almost **every** request is executing this code. It's already bad to have the ini_set calls (with suppress operator) here. If we merge this patch we check on each time if there is a higher limit and if not run the ini_set call. I don't think that removing those calls will improve the performance yet it's still bad.

I am not married to either solution, I just want to be able to change the setting and not have it hard coded, which I think is the worst solution of them all.

This patch is proposed because it is backwards compatible with the old solution. I don't know if removing the hard coded value altogether will break stuff for a lot of people on shared hosting or for people who did not have to think about this untill now. I also don't think there is a lot of performance penalty with doing it this way so it shouldn't be a problem, but if you guys would rather remove the hard coded value that is fine too for me. :)

2022-05-02 11:44 UTC, solracsf commented
Sure, this is a "problem" of all `ini_set()` calls at `lib/base.php` ;)

2022-05-09 14:28 UTC, artonge requested changes

2022-05-09 14:28 UTC, artonge commented on lib/base.php
> +		if (intval(@ini_get('max_execution_time')?? 0) < 3600) {
```suggestion
		if (intval(@ini_get('max_execution_time') ?? 0) < 3600) {
```

2022-05-09 14:28 UTC, artonge commented on lib/base.php
> +		if (intval(@ini_get('max_input_time')?? 0) < 3600) {
```suggestion
		if (intval(@ini_get('max_input_time') ?? 0) < 3600) {
```

2022-05-09 14:28 UTC, artonge commented on lib/base.php
> +			@set_time_limit(strval(max(intval(@ini_get('max_execution_time')),intval(@ini_get('max_input_time')))));
```suggestion
			@set_time_limit(max(intval(@ini_get('max_execution_time')), intval(@ini_get('max_input_time'))));
```

2022-05-16 08:16 UTC, mickenordin commented on lib/base.php
> +		if (intval(@ini_get('max_input_time')?? 0) < 3600) {
Fixed

2022-05-16 08:16 UTC, mickenordin commented on lib/base.php
> +			@set_time_limit(strval(max(intval(@ini_get('max_execution_time')),intval(@ini_get('max_input_time')))));
Fixed

2022-05-16 10:08 UTC, artonge approved these changes

2022-05-16 18:04 UTC, Pytal approved these changes

2022-05-17 08:14 UTC, merged

2022-08-22 21:33 UTC, szaimen commented
/backport to stable24

2022-08-22 21:47 UTC, szaimen commented
/backport to stable22

2022-08-22 21:47 UTC, szaimen commented
/backport to stable23