Don't use hash to check if binding worked
nextcloud/server pull request #32246
Opened 2022-05-02 19:50 UTC by CarlSchwan

using password_hash is expensive and should be used for hashing
passwords when saving them in the database. Here we just want to see if
the bind was already done with the given password.

Time spent on testing.nextcloud.com for password hashing 160ms:

![image](https://user-images.githubusercontent.com/23653902/166315485-3ccff8db-5986-4992-babe-887d87da40e8.png)

2022-05-03 07:53 UTC, come-nc requested changes
Maybe name it sum instead of hash and use a fast checksum method like sha instead?
I dislike storing the clear password in a random variable, it might cause problems down the road.

2022-05-03 07:54 UTC, come-nc commented
> Maybe name it sum instead of hash and use a fast checksum method like sha instead? I dislike storing the clear password in a random variable, it might cause problems down the road.

This sum could be of dn+prefix+pwd to test if the bind was with the same parameters in one comparison.

2022-05-03 08:16 UTC, CarlSchwan commented
> Maybe name it sum instead of hash and use a fast checksum method like sha instead? I dislike storing the clear password in a random variable, it might cause problems down the road.

I switched to an md5 hash instead. It's still quite useless in my opinion since the password is already accessible in clear from the app config database, so adding a hash to compare two strings is not required even if the string is confidential.

At least with md5, the hashing will be quite a bit faster.

2022-05-03 09:05 UTC, come-nc commented
> I switched to an md5 hash instead. It's still quite useless in my opinion since the password is already accessible in clear from the app config database, so adding a hash to compare two strings is not required even if the string is confidential.

Yeah I know we store the data but the idea is to not have it in too many variables to not encourage its use everywhere, and be able to track each use by looking at configuration reads.

2022-05-03 09:10 UTC, come-nc commented on apps/user_ldap/lib/Connection.php
> +			'hash' => md5($this->configPrefix . $this->configuration->ldapAgentPassword),
```php
￼			'sum' => md5($this->configuration->ldapAgentName . $this->configPrefix . $this->configuration->ldapAgentPassword),
```

2022-05-03 09:10 UTC, come-nc commented on apps/user_ldap/lib/Connection.php
> +			&& md5($this->configPrefix . $this->configuration->ldapAgentPassword) === $this->bindResult['hash']
```php
			&& md5($this->configuration->ldapAgentName . $this->configPrefix . $this->configuration->ldapAgentPassword) === $this->bindResult['sum']
```
and remove the dn comparison.
You can also replace `count($this->bindResult) !== 0` by `isset($this->bindResult['sum'])` to please psalm.

2022-05-03 09:10 UTC, come-nc commented on apps/user_ldap/lib/Connection.php
> +			'hash' => md5($this->configPrefix . $this->configuration->ldapAgentPassword),
(and remove the dn and hash keys)

2022-05-05 16:04 UTC, come-nc approved these changes

2022-05-05 16:09 UTC, PVince81 approved these changes
:+1:

2022-05-05 16:09 UTC, merged

2022-05-05 16:09 UTC, CarlSchwan commented
/backport to stable23

2022-05-05 16:09 UTC, CarlSchwan commented
/backport to stable22

2022-05-05 17:56 UTC, blizzz commented
sha256 over md5 to be more robust against collisions