try to fix the dns_get_record problem
nextcloud/server pull request #32243
Opened 2022-05-02 17:39 UTC by szaimen

Fix https://github.com/nextcloud/server/issues/28105

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-05-03 08:01 UTC, come-nc requested changes

2022-05-03 08:01 UTC, come-nc commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
You cannot fix a PHP warning with a try/catch.
You would have to use the `@` operator to suppress warnings.

But problem is this may hide real problems in some cases.

2022-05-03 08:04 UTC, szaimen commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
okay good to know, thanks!

2022-05-03 08:05 UTC, szaimen commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
basically it looks like this is an issue in php-src and fixed in newer releases. So we should discuss if we should fix this here for people that run outdated php versions and cannot upgrade or simply say we cannot fix it here...

2022-05-03 08:08 UTC, come-nc commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
There are also valid errors in the user commenting the issue, some of them were able to fix the errors by fixing their configuration or data.

This is why I am not sure hiding the warning is a good idea, but the problem is that we loop on all 3 kind of records and ask for each one inividually, and it seems if a CNAME is not there (and I suppose there is never a CNAME and an A at the same time) the function triggers a warning. If this is true then yes we need to suppress warning.

2022-05-03 08:11 UTC, szaimen commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
> and it seems if a CNAME is not there (and I suppose there is never a CNAME and an A at the same time) the function triggers a warning. If this is true then yes we need to suppress warning.

so basically we could supress the warning for CNAME if an A or AAAA record was found? Not sure how to refactor the logic though to make that possible...

2022-05-03 09:03 UTC, come-nc commented on lib/private/Http/Client/DnsPinMiddleware.php
> +
I am not comfortable enough with these things to answer this.

My advice would be test it under normal use (no DNS or network problem) and see if the warning pops up. If yes, then add the `@` error suppressing operator to the call to dns_get_record, if not do no touch anything.

2022-05-04 08:37 UTC, szaimen commented
Closing as it seems to be fixed in newer php releases.

2022-05-04 08:37 UTC, closed without merging