Remove SCSSCacher and compile scss files with npm-sass
nextcloud/server pull request #32261
Opened 2022-05-04 08:02 UTC by skjnldsv

Replace https://github.com/nextcloud/server/pull/31743

2022-05-04 12:56 UTC, CarlSchwan commented on apps/theming/css/theming.css
> +/* Error: Undefined variable.
What is the goal of this file?

2022-05-04 12:56 UTC, CarlSchwan commented on lib/composer/bamarni/composer-bin-plugin/LICENSE
> +Copyright (c) 2016 Bilal Amarni
Don't add this, maybe we should qdd it to . gitignore

2022-05-04 14:57 UTC, skjnldsv commented on apps/theming/css/theming.css
> +/* Error: Undefined variable.
This one is broken and a leftover from the old theming :)

2022-05-04 14:57 UTC, skjnldsv commented on lib/composer/bamarni/composer-bin-plugin/LICENSE
> +Copyright (c) 2016 Bilal Amarni
I'll remove it :)

2022-05-05 10:57 UTC, CarlSchwan commented
To give a small performance overview in term of db requests

**loading dashboard page:**
- before: 19
- after: 12

**loading photo page:**
- before: 34
- after: 22

**loading files page:**
- before: 31
- after: 23

This is will a hot redis cache, will a cold cache before the numbers were always above 100 and after this patch: the number is almost the same with and without hot cache. So really nice improvement :)

2022-05-05 12:08 UTC, artonge commented on apps/theming/css/theming.css
> +/* Error: Undefined variable.
Will the file be removed then?

2022-05-05 12:13 UTC, skjnldsv commented on core/css/functions.scss
> +	// $color: string.unquote($color);
It's only used by the icon-color functions, I think we could also drop those methods and the svg colour endpoint :wink:

2022-05-06 17:53 UTC, kesselb commented
cc @MorrisJobke as we talked about removing the scss cacher a while ago :sunglasses:

2022-05-12 08:21 UTC, PVince81 commented
- [ ] BUG: tag icon missing on the files left sidebar for me:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/277525/168025529-4849f76d-36a2-42e7-8a3e-65f803a4504b.png">

I had to force refresh to get the other sidebar icons to appear in the first place, I guess this is expected

2022-05-12 08:24 UTC, PVince81 commented
- [ ] BUG: checkboxes not rendering properly in share dropdown

<img width="186" alt="image" src="https://user-images.githubusercontent.com/277525/168026033-0a52218e-27ca-4349-88ad-97a271b195be.png">

when ticked it appears fine

2022-05-12 08:24 UTC, PVince81 commented
- [ ] BUG: file picker (move/copy mode) is missing icons

<img width="446" alt="image" src="https://user-images.githubusercontent.com/277525/168026261-d995d13f-7062-4264-86c1-35198a82c378.png">

2022-05-12 08:27 UTC, PVince81 commented
- [ ] BUG: favorite star missing on icon in file list

<img width="526" alt="image" src="https://user-images.githubusercontent.com/277525/168026691-32e6f1cf-f09a-4310-b2ba-c3984451f0a1.png">

2022-05-12 08:28 UTC, PVince81 commented
I see icons missing also for other apps like activity but I assume that those apps will need to be adjusted separately anyway, we could do that after merging.

I still think we should at least fix my findings above as they are from code in the server repo

2022-05-12 08:31 UTC, PVince81 requested changes
See comments about missing icons, checkboxes

2022-05-12 09:24 UTC, skjnldsv commented
Addressed @PVince81 :)
Also found some other fixups from Vanessa :rocket:

2022-05-13 06:42 UTC, nickvergessen commented
> Conflicting files
core/css/toast.scss
dist/workflowengine-workflowengine.js
dist/workflowengine-workflowengine.js.map

2022-05-13 10:12 UTC, PVince81 approved these changes
:+1: looks fine now

next up: adjust all apps we know of

2022-05-13 12:16 UTC, CarlSchwan commented
Tested again and works fine here :)

2022-05-13 12:18 UTC, CarlSchwan approved these changes

2022-05-13 14:13 UTC, skjnldsv commented
Rebased, ready to get in

2022-05-13 14:54 UTC, nickvergessen approved these changes
Totally looked at the full diff and made sure it works in every corner case like it should

2022-05-13 15:28 UTC, merged

2022-05-13 15:29 UTC, szaimen commented
🎉🎉🎉🎉🎉

2022-05-16 11:32 UTC, MorrisJobke commented
Nice @skjnldsv! Thanks for moving this one forward 🥳