Allow scanning for metadata with occ scan:file --metadata
nextcloud/server pull request #32309
Opened 2022-05-09 12:21 UTC by CarlSchwan

This is an option since the scanning will take longer with the metadata scanning

Currently, the getNodeForPath function also needs to be fixed since the path manipulation with array_shift shouldn't be required, but I have no idea what to do instead. This was copied from the hookconnector class

2022-05-10 13:40 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +		array_shift($pathParts);
I think you can add an argument to `explode` to only do so for the first three or something and then keep the rest

did you check if using Filesystem::resolvePath would work here ?

2022-05-10 13:40 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +		array_shift($pathParts);
I think you can add an argument to `explode` to only do so for the first three or something and then keep the rest

did you check if using Filesystem::resolvePath would work here ?

2022-06-22 11:08 UTC, CarlSchwan commented on apps/files/lib/Command/Scan.php
> +		array_shift($pathParts);
The issue is that these array_shift shouldn't even exists :( This should work:

```php
 		$info = Filesystem::getFileInfo($path);
```

2022-06-22 15:13 UTC, icewind1991 requested changes

2022-08-15 00:47 UTC, matiasdelellis commented
Just testing NC25...
Well, with the new view in the photos app, it should be integrated for that...

2022-10-19 15:21 UTC, closed without merging