additional logging when mkdir fails for object storage
nextcloud/server pull request #32314
Opened 2022-05-09 14:58 UTC by icewind1991

Signed-off-by: Robin Appelman <robin@icewind.nl>

2022-05-09 15:01 UTC, CarlSchwan approved these changes

2022-06-10 14:04 UTC, PVince81 requested changes, later dismissed

2022-06-10 14:04 UTC, PVince81 commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			$this->logger->warning("Tried to create an object store folder that already exists");
can you log the path also ?

2023-04-05 15:54 UTC, come-nc approved these changes

2023-04-06 07:33 UTC, skjnldsv approved these changes

2023-04-17 21:42 UTC, merged