add data from the users profile to the provisioning api
nextcloud/server pull request #3232
Opened 2017-01-24 13:25 UTC by schiessle

add additional data from the users profile to the output of the previsioning api.

Example call:

````
curl -X GET http://admin:admin@localhost/master/ocs/v1.php/cloud/users/admin -H  "OCS-APIRequest: true"
````

Result:

````
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <enabled>true</enabled>
  <quota>
   <free>338696790016</free>
   <used>7438874</used>
   <total>338704228890</total>
   <relative>0</relative>
   <quota>-3</quota>
  </quota>
  <email>user@foo.de</email>
  <displayname>admin</displayname>
  <phone></phone>
  <address></address>
  <webpage></webpage>
  <twitter>schiessle</twitter>
 </data>
</ocs>
````

2017-01-24 13:26 UTC, schiessle commented
needed for https://github.com/nextcloud/android/issues/554 cc @mario

2017-01-24 14:16 UTC, nickvergessen commented
Works, but just as info, neither phone nor address have any guaranteed format, right?

2017-01-24 14:17 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								AccountManager $accountManager,
Why does this not have a public interface?

2017-01-24 14:18 UTC, schiessle commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								AccountManager $accountManager,
Because until now it was only used internally. Sure if more apps use it a public interface makes sense.

2017-01-24 15:00 UTC, schiessle commented
@mario @nickvergessen endpoints are now unified, as discussed.

2017-01-24 15:47 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		$data['display-name'] = $targetUserObject->getDisplayName();
I fear we have to add this instead of changing it? Otherwise it breaks the existing usage?

2017-01-24 15:54 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		$data['display-name'] = $targetUserObject->getDisplayName();
So this should be renamed/changed in `getCurrentUser()`

2017-01-25 04:02 UTC, MorrisJobke approved these changes
Works 👍

2017-01-25 08:37 UTC, nickvergessen requested changes
Needs fixing

2017-01-25 10:21 UTC, schiessle commented
@nickvergessen should work now

2017-01-25 10:29 UTC, nickvergessen approved these changes

2017-01-25 14:44 UTC, merged