Remove OCP\App and OCP\BackgroundJob
nextcloud/server pull request #32363
Opened 2022-05-12 15:37 UTC by CarlSchwan

Both deprecated since NC 23

IAppManager is the replacement for OCP\App unfortunately it can't be
dependency injected in classes used by the installer otherwise the
the database connection is initialized too early

## Test plan

1. Tests work locally
2. psalm and cs:fix are happy
3. The webui seems to still work :)

2022-05-16 12:24 UTC, come-nc approved these changes
BackgroundJob was unused?
Any chance of removing OC_App?

2022-05-16 14:49 UTC, CarlSchwan commented
> BackgroundJob was unused?

`OCP\BackgroundJob` was unused and did nothing. This is not the same thing as `OCP\BackgroundJob\IJob` and co

> Any chance of removing OC_App?

I wish but let's do that step by step ;) there is a few api still missing in OCP\App\IAppManager to be a full replacement

2022-05-20 20:02 UTC, kesselb requested changes

2022-05-20 20:02 UTC, kesselb commented on tests/lib/Encryption/UtilTest.php
> +			Server::get(IAppManager::class),
computer says no ;)

```
1) Test\Encryption\UtilTest::testGetEncryptionModuleId with data set #0 ('', array())
--

TypeError: 
Argument 4 passed to OC\Encryption\Util::__construct() must implement 
interface OCP\IConfig, instance of OC\App\AppManager given, called in 
/drone/src/tests/lib/Encryption/UtilTest.php on line 51
```

2022-05-20 20:07 UTC, CarlSchwan commented on tests/lib/Encryption/UtilTest.php
> +			Server::get(IAppManager::class),
fixed

2022-05-20 22:47 UTC, kesselb commented on core/templates/layout.base.php
> +		<link rel="mask-icon" sizes="any" href="<?php print_unescaped(image_path('core', 'favicon-mask.svg')); ?>" color="<?php p($theme->getColorPrimary()); ?>">
```
{
  "Exception": "RuntimeException",
  "Message": "image not found: image:favicon-mask.svg webroot: serverroot:\/drone\/src",
  "Code": 0,
  "Trace": [
    {
      "file": "\/drone\/src\/lib\/private\/legacy\/template\/functions.php",
      "line": 242,
      "function": "imagePath",
      "class": "OC\\URLGenerator",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/core\/templates\/layout.user.php",
      "line": 37,
      "function": "image_path"
    },
    {
      "file": "\/drone\/src\/lib\/private\/Template\/Base.php",
      "line": 180,
      "args": [
        "\/drone\/src\/core\/templates\/layout.user.php"
      ],
      "function": "include"
    },
    {
      "file": "\/drone\/src\/lib\/private\/Template\/Base.php",
      "line": 150,
      "function": "load",
      "class": "OC\\Template\\Base",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/private\/legacy\/OC_Template.php",
      "line": 181,
      "function": "fetchPage",
      "class": "OC\\Template\\Base",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/private\/legacy\/OC_Template.php",
      "line": 212,
      "function": "fetchPage",
      "class": "OC_Template",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/public\/AppFramework\/Http\/TemplateResponse.php",
      "line": 213,
      "function": "fetchPage",
      "class": "OC_Template",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
      "line": 178,
      "function": "render",
      "class": "OCP\\AppFramework\\Http\\TemplateResponse",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/private\/AppFramework\/App.php",
      "line": 172,
      "function": "dispatch",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/lib\/private\/Route\/Router.php",
      "line": 298,
      "function": "main",
      "class": "OC\\AppFramework\\App",
      "type": "::"
    },
    {
      "file": "\/drone\/src\/lib\/base.php",
      "line": 1021,
      "function": "match",
      "class": "OC\\Route\\Router",
      "type": "->"
    },
    {
      "file": "\/drone\/src\/index.php",
      "line": 36,
      "function": "handleRequest",
      "class": "OC",
      "type": "::"
    }
  ],
  "File": "\/drone\/src\/lib\/private\/URLGenerator.php",
  "Line": 273,
  "CustomMessage": "--"
}
```

computer is still a bit unhappy. some of the integration tests are failing.

2022-05-20 22:48 UTC, kesselb submitted a review, later dismissed

2022-06-10 13:59 UTC, PVince81 approved these changes
:+1: long overdue

I suggest you grep the release tarball in case you find more usages in apps

2022-06-10 13:59 UTC, PVince81 commented
and there are conflicts

2022-07-22 21:38 UTC, blizzz commented
CI is unhappy

2022-08-08 15:05 UTC, merged