Port share by mail settings to vue
nextcloud/server pull request #32464
Opened 2022-05-17 16:36 UTC by CarlSchwan

2022-05-17 16:37 UTC, CarlSchwan commented
I'm not sure why npm is doing so much dist changes :(

2022-05-18 06:53 UTC, skjnldsv commented
/rebase

2022-05-18 06:58 UTC, skjnldsv commented
/compile amend /

2022-05-18 07:05 UTC, skjnldsv approved these changes

2022-05-18 11:18 UTC, CarlSchwan commented on apps/sharebymail/src/components/AdminSettings.vue
> +</script>e
```suggestion
</script>
```

2022-05-18 12:08 UTC, artonge requested changes

2022-05-18 12:08 UTC, artonge commented on apps/sharebymail/src/components/AdminSettings.vue
> +		:doc-url="sharingFederatedDocUrl">
`sharingFederatedDocUrl` seems to be not declared anywhere.

2022-05-18 12:08 UTC, artonge commented on apps/sharebymail/src/components/AdminSettings.vue
> +			replyToInitiator,
This also work, and you can remove the declaration of the intermediate variables above.

```suggestion
			sendPasswordMail: loadState('sharebymail', 'sendPasswordMail'),
			replyToInitiator: loadState('sharebymail', 'replyToInitiator'),
```

2022-05-19 14:12 UTC, artonge approved these changes

2022-05-19 15:45 UTC, merged