Add setting to set a different primary color for dark themes
nextcloud/server pull request #32500
Opened 2022-05-19 14:05 UTC by artonge

The primary color can be in-adapted to dark theme, this new settings allow to choose a different one.
If the color for dark theme is not set, it will default to the primary one.

![Screencast from 19-05-2022 15:57:37](https://user-images.githubusercontent.com/6653109/169312638-18ad70c1-c8d0-4419-a9c7-2463433297be.gif)

2022-05-19 14:39 UTC, CarlSchwan approved these changes

2022-05-19 14:42 UTC, artonge commented on apps/theming/lib/ThemingDefaults.php
> +			null
Why not, but I would love a rational :)

2022-05-19 15:20 UTC, artonge commented on apps/theming/lib/ThemingDefaults.php
> +			null
Ok, psalm was not happy :sweat_smile:

2022-05-19 18:48 UTC, Pytal approved these changes

2022-05-20 06:33 UTC, skjnldsv requested changes
Blocking

2022-05-20 07:21 UTC, skjnldsv commented
see for fix https://github.com/nextcloud/server/pull/32509

2022-05-31 06:49 UTC, closed without merging