Revert api break
nextcloud/server pull request #32555
Opened 2022-05-23 11:00 UTC by CarlSchwan

2022-05-23 11:10 UTC, nickvergessen approved these changes

2022-05-23 12:36 UTC, come-nc requested changes

2022-05-23 12:36 UTC, come-nc commented on lib/private/User/LazyUser.php
> +	public function getBackend() {
You can leave it in the implementation, it’s the interface that needs to not add the return type.
Return type is covariant in PHP.

2022-05-23 12:36 UTC, come-nc commented on lib/private/User/User.php
> +	public function getBackend() {
```suggestion
	public function getBackend(): ?UserInterface {
```

2022-05-24 07:05 UTC, come-nc approved these changes

2022-05-24 07:06 UTC, merged