Port federatedfilesharing personal settings to vue
nextcloud/server pull request #32561
Opened 2022-05-23 15:33 UTC by CarlSchwan

2022-05-25 17:48 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				Facebook
```suggestion
				{{ t('federatedfilesharing', 'Facebook') }}
```

2022-05-25 17:48 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				Twitter
```suggestion
				{{ t('federatedfilesharing', 'Twitter') }}
```

2022-05-25 17:48 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				Diaspora
```suggestion
				{{ t('federatedfilesharing', 'Diaspora') }}
```

2022-05-27 17:09 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +
Should add a license header here as well

2022-05-27 17:09 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				@click.prevent="copyCloudId()">
```suggestion
				@click.prevent="copyCloudId">
```

2022-05-27 17:09 UTC, Pytal commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				<xml>{{ htmlCode }}</xml>
```suggestion
				<pre>{{ htmlCode }}</pre>
```

2022-05-30 13:23 UTC, artonge requested changes

2022-05-30 13:23 UTC, artonge commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +	.cloudIdText {
Snake case for class names

2022-06-15 13:31 UTC, CarlSchwan commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +			return `padding:10px;background-color:${this.color};color:${this.textColor};border-radius:3px;padding-left:4px;`
no since this.color and this.textColor are dynamic and are coming from the backend. I could probably use a CSS variable and then update this CSS variable but this would make the code significantly more complex

2022-06-15 14:10 UTC, artonge commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +			return `padding:10px;background-color:${this.color};color:${this.textColor};border-radius:3px;padding-left:4px;`
What about https://v2.vuejs.org/v2/guide/class-and-style.html#With-Components= ?

2022-06-15 14:11 UTC, artonge commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +			return `padding:10px;background-color:${this.color};color:${this.textColor};border-radius:3px;padding-left:4px;`
Same for the other place

2022-06-15 14:45 UTC, CarlSchwan commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +			return `padding:10px;background-color:${this.color};color:${this.textColor};border-radius:3px;padding-left:4px;`
I could indeed use something like `:style="{ backgroundImage: `url(${logoPathAbsolute})` }"` but since we still need `backgroundStyle` and `linkStyle` computed properties for the raw html output and we would need to keep both the `<style>` + `:style={}` stuff in sync with the computed properties. This is likely to go out of sync, so I prefer to keep it that way with the 2 computed properties, that are used for both the rendered button as well as the HTML code to copy

2022-06-15 15:24 UTC, artonge approved these changes

2022-06-27 17:55 UTC, Pytal approved these changes

2022-06-27 17:55 UTC, merged