Add profile data to provisioning api stable11
nextcloud/server pull request #3259
Opened 2017-01-25 13:21 UTC by schiessle

backport of https://github.com/nextcloud/server/pull/3232

2017-01-26 03:27 UTC, MorrisJobke requested changes

2017-01-26 03:27 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +			$result['display-name'] = $result['displayname'];
```
{"reqId":"KRAJ10EAy8L+Su0X2vz7","remoteAddr":"::1","app":"PHP","message":"Cannot use object of type OCP\\AppFramework\\Http\\DataResponse as array at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/apps\/provisioning_api\/lib\/Controller\/UsersController.php#248","level":3,"time":"2017-01-26T03:26:07+00:00","method":"GET","url":"\/server\/ocs\/v1.php\/cloud\/user","user":"admin","version":"11.0.1.2"}
```

2017-01-26 03:29 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +			$result['display-name'] = $result['displayname'];
Same on `master`, but I'm pretty sure, that I tested this in the other PR review 😕 

@schiessle Could you fix this on master and then cherry-pick the fix to this PR. Thanks :)

2017-01-26 10:10 UTC, schiessle commented on apps/provisioning_api/lib/Controller/UsersController.php
> +			$result['display-name'] = $result['displayname'];
yes, there is even a unit test which should fail in this case... Will have a look.

2017-01-26 10:35 UTC, schiessle commented
@MorrisJobke last commit should fix it

2017-01-26 21:27 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-02-10 11:59 UTC, LukasReschke approved these changes

2017-02-10 12:00 UTC, merged