Fix User profile picture when performing the search
nextcloud/server pull request #32635
Opened 2022-05-27 19:48 UTC by andyxheli

Signed-off-by: Andy Xheli <axheli@axtsolutions.com>

Before 
![image](https://user-images.githubusercontent.com/59488153/140980158-b9108161-57ab-48b4-ae6f-98ec4e72775a.png)

After
![2022-05-27 14_47_23-Dashboard - AXTSolutions Cloud](https://user-images.githubusercontent.com/59488153/170780178-9cb19a84-f24b-4b2b-aacb-b4ec80576819.png)

Fix for #31065

2022-06-06 18:25 UTC, andyxheli commented
@CarlSchwan Can you please review

2022-06-09 21:39 UTC, juliushaertl commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = "/index.php/avatar/$uid/64";
This url should probably be built using IURLGenerator and we might need to have special handling for the viability settings, but the change in general makes sense I think.

@nickvergessen Didn't you mention a while back in chat a case on our instance where the contacts menu endpoint was not returning an avatar for a user? Could be related

2022-09-02 18:22 UTC, andyxheli commented
Hey guys! Anyway we can look into this also. I think it would be nice to have this in NC 25. 

Currently in NC 25

![image](https://user-images.githubusercontent.com/59488153/188214899-4d7dc384-1f2c-427c-bc89-a5b2bb73927e.png)

2022-09-03 15:29 UTC, andyxheli commented
Sorry I think that was a mistak. Clicked on accident for rereview!

2022-09-16 16:27 UTC, CarlSchwan commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = "/index.php/avatar/$uid/64";
```suggestion
			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
```

Something like this

2022-09-16 16:40 UTC, andyxheli commented
@CarlSchwan suggested has been applied

2022-09-16 18:16 UTC, andyxheli commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
@CarlSchwan Once i applied line 290 the contact with uploaded images disappeared from the menu and soon as i applied $avatar = "/index.php/avatar/$uid/64"; back they came back

2022-09-16 21:10 UTC, CarlSchwan commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
oh should probably be 'core.Avatar.getAvatar' instead

2022-09-16 21:31 UTC, andyxheli commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
Okay, ill give that a try and let you know! thanks :)

2022-09-16 21:35 UTC, andyxheli commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
No luck same results with $avatar = $this->urlGenerator->linkToRoute('core.Avatar.getAvatar', ['userId' => $uid, 'size' => 64]);

2022-09-19 04:46 UTC, nickvergessen requested changes

2022-09-19 04:46 UTC, nickvergessen commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRoute('core.getAvatar', ['userId' => $uid, 'size' => 64]);
Not sure if casing matters, also it should be an absolute URL
```suggestion
			$avatar = $this->urlGenerator->linkToRouteAbsolute('core.avatar.getAvatar', ['userId' => $uid, 'size' => 64]);
```

2022-09-19 14:05 UTC, andyxheli reviewed
Signed-off-by: Andy Xheli <axheli@axtsolutions.com>

Tested on NC 24 & 25 and it works as it should

2022-09-20 16:44 UTC, Pytal commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +			$avatar = $this->urlGenerator->linkToRouteAbsolute('core.avatar.getAvatar', ['userId' => $uid, 'size' => 64]);
```suggestion
			$uid = $contact['UID'];
			$entry->setId($uid);
			$avatar = $this->urlGenerator->linkToRouteAbsolute('core.avatar.getAvatar', ['userId' => $uid, 'size' => 64]);
```

2022-09-20 17:35 UTC, Pytal approved these changes

2022-09-26 14:18 UTC, andyxheli commented
Hi all, any updates on this on being in NC 25 ?

2022-09-29 12:10 UTC, blizzz approved these changes

2022-09-29 12:11 UTC, blizzz commented
@andyxheli CI is unhappy:

 There was 1 failure:

1) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsWithoutBinaryImage
Failed asserting that '' is null.

/drone/src/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:166

that test needs adjustements apparently

2022-09-29 13:29 UTC, andyxheli commented
Thank you! @blizzz 

@Pytal Do you have any suggestions on that needs to be done on ? 

There was 1 failure:


Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsWithoutBinaryImage
Failed asserting that '' is null.
/drone/src/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:166

2022-09-29 18:50 UTC, Pytal commented
This looks to be from the return value of `linkToRouteAbsolute()` so would say that `urlGenerator` needs to be mocked, @blizzz might know more here though?

2022-10-01 18:49 UTC, blizzz commented
Actually the test was ensuring(!) that avatar is null.  Now it is not anymore as every time an avatar url is being created. The mock would at least return an empty string, and not null. `testGetContactsWithoutAvatarURI` does not fail however? A bit confusing when your not totally in the logic, it feels a bit that the tests were out of touch with the changes of the ContactsStore.

2022-10-01 19:04 UTC, blizzz commented
Best probably to do as @Pytal  suggested: mock url generator to return a dummy url and expect this.

Something like this

```diff
diff --git a/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php b/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
index aa609aedbb9..dfdd67fbb23 100644
--- a/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
+++ b/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
@@ -140,6 +140,10 @@ class ContactsStoreTest extends TestCase {
    public function testGetContactsWithoutBinaryImage() {
        /** @var IUser|MockObject $user */
        $user = $this->createMock(IUser::class);
+       $this->urlGenerator->expects($this->any())
+           ->method('linkToRouteAbsolute')
+           ->with('core.avatar.getAvatar', $this->anything())
+           ->willReturn('https://urlToNcAvatar.test');
        $this->contactsManager->expects($this->once())
            ->method('search')
            ->with($this->equalTo(''), $this->equalTo(['FN', 'EMAIL']))
@@ -163,7 +167,7 @@ class ContactsStoreTest extends TestCase {
        $entries = $this->contactsStore->getContacts($user, '');
 
        $this->assertCount(2, $entries);
-       $this->assertNull($entries[1]->getAvatar());
+       $this->assertSame('https://urlToNcAvatar.test', $entries[1]->getAvatar());
    }
 
    public function testGetContactsWithoutAvatarURI() {
```

(didn't run tests against it)

2022-10-01 23:31 UTC, andyxheli commented
Thanks @blizzz do we need to create a new pr on this? I'd anyone welling to help me on this please :)

2022-10-03 13:54 UTC, blizzz commented
@andyxheli could you add them as commit to this PR?

2022-10-03 14:19 UTC, andyxheli commented
@blizzz All done :)

2022-10-05 08:36 UTC, merged

2022-10-05 08:36 UTC, blizzz commented
/backport to stable25

2023-02-15 21:28 UTC, szaimen commented
This seemingly broke avatars of vcf-contacts.

 See https://github.com/nextcloud/server/pull/36735

2023-02-15 21:40 UTC, andyxheli commented
@szaimen would this also fix https://github.com/nextcloud/server/issues/34503 ? under See https://github.com/nextcloud/server/pull/36735

2023-02-15 21:41 UTC, szaimen commented
> @szaimen would this also fix #34503 ?

No.

2023-02-15 21:46 UTC, andyxheli commented
Okay, thanks. Just checking so we did have duplicate issues.