Uses IShare::TYPE_... in Server.php rather than the obsolete Constants
nextcloud/server pull request #32647
Opened 2022-05-29 17:31 UTC by StCyr

It doesn't look like those search plugins are used somewhere else....

hmmm.... Here might be another attention point though:

https://github.com/nextcloud/server/blob/5a12e8f906ea5075193d88963cbdf805a097f626/lib/private/legacy/OC_App.php#L257

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

2022-05-30 06:49 UTC, nickvergessen commented
> Here might be another attention point though:

Any app can register a provider:
https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml#L129

2022-05-30 07:18 UTC, CarlSchwan approved these changes

2022-05-30 07:20 UTC, CarlSchwan commented
> > Here might be another attention point though:
> 
> Any app can register a provider: https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml#L129

Yeah so would be good to double check if external apps like talk and circle still work

2022-05-30 08:55 UTC, StCyr commented
> > > Here might be another attention point though:
> > 
> > 
> > Any app can register a provider: https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml#L129
> 
> Yeah so would be good to double check if external apps like talk and circle still work

Indeed.

IIUC, plugins registered via an app are processed via [server/lib/private/legacy/OC_App.php](https://github.com/nextcloud/server/blob/5a12e8f906ea5075193d88963cbdf805a097f626/lib/private/legacy/OC_App.php#L257) and this won't work anymore with my change.

Should I just add a test in `lib/private/Collaboration/Collaborators/Search.php`?

```php
	public function registerPlugin(array $pluginInfo) {
---		$shareType = constant(Share::class . '::' . $pluginInfo['shareType']);
+++	if (str_starts_with($pluginInfo['shareType'], 'SHARE_TYPE') {
+++              $shareType = constant(Share::class . '::' . $pluginInfo['shareType']);
+++	else {
+++              $shareType = $pluginInfo['shareType'];
+++         }
		if ($shareType === null) {
			throw new \InvalidArgumentException('Provided ShareType is invalid');
		}
```

and create issues in identified apps?

2022-05-30 10:28 UTC, nickvergessen requested changes
Blocking merge until apps have been fixed

2022-05-30 10:28 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/Search.php
> +		$shareType = $pluginInfo['shareType'];
So your proposal is:

```suggestion
		if (str_starts_with($pluginInfo['shareType'], 'SHARE_TYPE') {
			$shareType = constant(Share::class . '::' . $pluginInfo['shareType']);
		} else {
			$shareType = $pluginInfo['shareType'];
		}
```

2022-05-30 10:28 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/Search.php
> +		$shareType = $pluginInfo['shareType'];
How about:
```suggestion
		if (str_starts_with($pluginInfo['shareType'], 'SHARE_TYPE') {
			$shareType = constant(IShare::class . '::' . substr($pluginInfo['shareType'], 6));
		} else {
			$shareType = $pluginInfo['shareType'];
		}
```

This way we still get rid of the old constats?

2022-05-30 10:29 UTC, nickvergessen commented on lib/private/Collaboration/Collaborators/Search.php
> +		$shareType = $pluginInfo['shareType'];
Please also note that $shareType is a int after `constant()` but not with your code.
So should use the following on the else branch
```php
		$shareType = (int) $pluginInfo['shareType'];
```

2023-03-24 11:08 UTC, juliushaertl requested changes
@StCyr Any update on this? Any chance you could open issues for the apps that need fixing? For backward compatiblity we could also go the str_starts_with approach that was commented already.

2024-03-15 14:58 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open and solve the various conflicts.

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2024-03-15 14:58 UTC, closed without merging