add brute force protection for public link authentication
nextcloud/server pull request #3265
Opened 2017-01-25 17:19 UTC by schiessle

fix https://github.com/nextcloud/server/issues/3219 

cc @LukasReschke @michag86

2017-01-25 17:45 UTC, michag86 commented
This does only apply the delay on link login? But it does not create a record if a wrong password is entered?

2017-01-25 20:47 UTC, schiessle commented
It also creates a record in the database, otherwise we couldn't delay the login on multiple failed attempts

2017-01-25 20:51 UTC, michag86 commented
I testest it only on 10.0.3. When I try to login with wrong password on Link share, there is no new record in bruteforce attempts created.

2017-01-25 21:04 UTC, LukasReschke commented
> I testest it only on 10.0.3. When I try to login with wrong password on Link share, there is no new record in bruteforce attempts created.

The annotation is only available in master aka the coming 12.x.

2017-01-26 01:04 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-01-26 01:04 UTC, MorrisJobke commented
CI failures are unrelated. 😢

2017-01-26 01:05 UTC, MorrisJobke commented
@skjnldsv Easy to test: create a public link share with password: type in the password wrong: from attempt to attempt it should take longer (after 5-8 attempts you will notice it ;))

2017-01-26 01:21 UTC, LukasReschke requested changes

2017-01-26 01:21 UTC, LukasReschke commented on apps/files_sharing/lib/Controller/ShareController.php
> +	 * @BruteForceProtection publicLinkAuth
Thinking about it more I'm not entirely sure if this is the best approach to solve this. This will make opening different password protected shares a pain. I think we need to add logic below in 185 manually otherwise this can backfire :(

2017-01-26 05:55 UTC, schiessle commented on apps/files_sharing/lib/Controller/ShareController.php
> +	 * @BruteForceProtection publicLinkAuth
I think it you brute force a public link it is fine if other links are slowed down as well. Why should we allow to brute force a second link if you failed on the first one? 

Note, if you just typed the wrong password once ore twice by accident, the impact will be minimal and can be ignored.

2017-01-26 11:03 UTC, LukasReschke approved these changes

2017-01-26 11:04 UTC, LukasReschke commented
Talked to @schiessle and we'll add a new annotation for the time that the data is stored. :) 👍 for me for now thus.

2017-01-26 11:05 UTC, merged

2017-01-26 12:34 UTC, skjnldsv commented
@MorrisJobke Sorry, I was at work, I took too long! 😢 
![michael_caine](https://cloud.githubusercontent.com/assets/14975046/22331496/0eb0cf4c-e3cc-11e6-9568-161232746831.gif)