Fix get avatar authorization
nextcloud/server pull request #32697
Opened 2022-06-02 01:44 UTC by Pytal

See title 👆

2022-06-02 01:44 UTC, Pytal commented
/backport to stable24

2022-06-02 01:44 UTC, Pytal commented
/backport to stable22

2022-06-02 11:49 UTC, blizzz approved these changes
Perhaps some tests though?

2022-06-03 05:25 UTC, juliushaertl requested changes

2022-06-03 05:25 UTC, juliushaertl commented on lib/private/Avatar/AvatarManager.php
> +				if ($requestingUser !== null) {
This doesn't match with how the `SCOPE_LOCAL` was working before:

https://github.com/nextcloud/server/blob/4d26a9afa01aaf069e29a62f4e9547c34156ea01/lib/public/Accounts/IAccountManager.php#L51

Is that an intended change? If so maybe you can elaborate a bit about the reasoning :)

2022-06-03 18:49 UTC, Pytal commented on lib/private/Avatar/AvatarManager.php
> +				if ($requestingUser !== null) {
Fixed it! The changes before were based on semantics i.e. "🔒 Local" seemed like it'd be more restrictive

2022-06-07 10:18 UTC, artonge commented on lib/private/Avatar/AvatarManager.php
> +		return new PlaceholderAvatar($folder, $user, $this->logger);
Unreachable code, no ?

2022-06-07 10:18 UTC, artonge commented on lib/private/Avatar/AvatarManager.php
> +					return new UserAvatar($folder, $this->l, $user, $this->logger, $this->config);
I would keep the previous comments if they are still valid.

2022-06-07 23:52 UTC, Pytal commented on lib/private/Avatar/AvatarManager.php
> +		return new PlaceholderAvatar($folder, $user, $this->logger);
Will be hit after the break in the switch statement above i.e. when the requesting user is not logged in

2022-06-07 23:58 UTC, Pytal commented on lib/private/Avatar/AvatarManager.php
> +					return new UserAvatar($folder, $this->l, $user, $this->logger, $this->config);
Added back comment explanations not already expressed clearly by the code

2022-06-08 08:06 UTC, artonge approved these changes

2022-06-08 23:27 UTC, Pytal commented
CI failure unrealated

2022-06-08 23:27 UTC, Pytal commented
CI failure unrelated

2022-06-08 23:27 UTC, merged