Augment keyboard accessibility of the contacts menu
nextcloud/server pull request #32736
Opened 2022-06-06 19:30 UTC by Pytal

### To Do

- [x]  Fix focus border not visible in light mode
- [x]  Remove bottom border style erroneously applied to the elements within the contact
    - This was likely meant to remove the border for the last contact in the list but the border will be preserved to improve scannability
- [x]  Restore top contact action
  - Previous related changes can be found in https://github.com/nextcloud/server/pull/31931
- [x]  Navigate to and activate other actions with the keyboard

### Example

![image](https://user-images.githubusercontent.com/24800714/172233278-62ef8fca-0bc5-468d-a104-2cd68a3d3be6.png)

2022-06-07 11:01 UTC, artonge approved these changes

2022-06-07 14:01 UTC, PVince81 approved these changes
:+1:

2022-06-07 14:01 UTC, PVince81 commented
/compile amend /

2022-06-07 14:01 UTC, PVince81 commented
ah, actually this needs a rebase first @Pytal

2022-06-07 16:11 UTC, artonge requested changes

2022-06-07 16:12 UTC, artonge commented on core/css/header.scss
> +		box-shadow: inset 0 0 0 2px var(--color-primary);
If not, I did this one: https://github.com/nextcloud/server/pull/32742

2022-06-07 17:01 UTC, Pytal commented on core/css/header.scss
> +		box-shadow: inset 0 0 0 2px var(--color-primary);
Right the white outline is better, I've reverted the `header.scss` change and copied https://github.com/nextcloud/server/pull/32742/files#diff-38df8905a050af6ad588db71a76ddba1cae3f77e804073b8931c3e0fbaf731ec over here

2022-06-08 08:04 UTC, artonge approved these changes

2022-06-08 23:31 UTC, merged