Respect minSearchStringLength in CardDavBackend
nextcloud/server pull request #32766
Opened 2022-06-08 14:29 UTC by artonge

2022-06-08 14:34 UTC, tcitworld commented on apps/dav/appinfo/v1/carddav.php
> +$cardDavBackend = new CardDavBackend($db, $principalBackend, \OC::$server->getUserManager(), \OC::$server->getGroupManager(), \OC::$server->get(\OCP\EventDispatcher\IEventDispatcher::class), \OC::$se
You'll need to adapt a lot of tests too

2022-06-08 14:40 UTC, tcitworld requested changes
The only places where this is used are

https://github.com/nextcloud/server/blob/de6b0dadbe5190325d0507ba1438880d772d8a8a/apps/dav/lib/Search/ContactsSearchProvider.php#L128-L136

https://github.com/nextcloud/server/blob/de6b0dadbe5190325d0507ba1438880d772d8a8a/apps/dav/lib/CardDAV/AddressBookImpl.php#L121

I think it makes more sense to benefit from IConfig autoinjection in these classes instead of doing it here.

2022-06-09 10:45 UTC, artonge commented
Updated, ready for review now :)

2022-06-09 10:46 UTC, artonge commented
/backport to stable24

2022-06-09 10:47 UTC, artonge commented
/backport to stable23

2022-06-09 10:47 UTC, artonge commented
/backport to stable22

2022-06-09 11:22 UTC, PVince81 commented
@ChristophWurst can you validate that this enhancement (or old undiscovered bug) is ok ?

2022-06-10 13:20 UTC, miaulalala approved these changes
LGTM

2022-06-10 14:02 UTC, tcitworld requested changes
This function is not only used for auto-completion, this will also affect not returning anymore results at all for emails shorter than the threshold.

From what I can see, this will break a few things indirectly relying on `searchUserPrincipals` though `Sabre\DAVACL\Plugin::principalSearch`, when the full email is shorter that the search such as
- `Sabre\DAVACL\Plugin::principalPropertySearchReport` (might be fine) 
- `Sabre\CalDAV\Schedule\Plugin::getFreeBusyForEmail` (no more free/busy 💥)
- `OCA\DAV\CalDAV\Schedule\Plugin::isAvailableAtTime` (same)

2022-06-23 14:19 UTC, closed without merging