Add comments expire date
nextcloud/server pull request #32863
Opened 2022-06-13 15:35 UTC by vitormattos

Related: https://github.com/nextcloud/spreed/pull/7327

2022-06-13 18:01 UTC, nickvergessen requested changes

2022-06-13 18:01 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	public function deleteMessageExpiredAtObject(string $objectType, string $objectId): int {
please move up to the other delete functions (then you also might see the thing about returning a boolean which I commented on the interface)

2022-06-13 21:45 UTC, nickvergessen commented on lib/public/Comments/ICommentsManager.php
> +	 * @return boolean true if rows was deleted
```suggestion
	 * @return boolean true if at least one row was deleted
```
or
```suggestion
	 * @return boolean true if rows were deleted
```

2022-06-14 08:44 UTC, nickvergessen commented
Tested with our instance:
```sql
SELECT COUNT(*) FROM oc_comments;
+----------+
| COUNT(*) |
+----------+
|  1059368 |
+----------+

ALTER TABLE `oc_comments` ADD `expire_date` DATETIME NULL AFTER `reactions`; 
Query OK, 0 rows affected (0.028 sec)
Records: 0  Duplicates: 0  Warnings: 0

ALTER TABLE `oc_comments` ADD INDEX `expire_date` (`expire_date`); 
Query OK, 0 rows affected (2.084 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

So sounds good.

2022-06-14 14:42 UTC, vitormattos commented
Now, can I squash the commits?

2022-06-14 14:51 UTC, nickvergessen commented
> Now, can I squash the commits?

Sounds good to me

2022-06-14 14:52 UTC, nickvergessen approved these changes

2022-06-14 14:53 UTC, nickvergessen commented
you need to run `bash build/autoload...` and commit the changed files in `lib/composer/composer/autoload_*` (not the `installed.php` and `InstalledVersion.php`)

2022-06-15 19:18 UTC, blizzz requested changes
CI is unhappy

expire_date is also not exposed in DAV API, making it inconsistent with the other features. Cf. apps/dav/lib/Comments/CommentNode.php

2022-06-15 19:18 UTC, blizzz commented on tests/lib/Comments/ManagerTest.php
> +		$comment = $manager->get(strval($ids[1]));
```suggestion
		$comment = $manager->get((string)$ids[1]);
```

micro optimization :)

2022-06-15 19:18 UTC, blizzz commented on tests/lib/Comments/ManagerTest.php
> +				$manager->get(strval($id));
```suggestion
				$manager->get((string)$id);
```

2022-06-15 19:27 UTC, nickvergessen commented
> expire_date is also not exposed in DAV API

Neither is the optional `refernce_id` that we added for talk specifically. I think that's fine.

2022-06-15 19:34 UTC, blizzz commented
> > expire_date is also not exposed in DAV API
> 
> Neither is the optional `refernce_id` that we added for talk specifically. I think that's fine.

Does not mean it is not worth to add it there as well. The reference id has of course less meaning for file comments. The expiry date would be more relevant, but on the other hand the web ui does not offer this option either. Thus, I also agree it is okay to leave it out, nevertheless worth to point out that this is done deliberately.

2022-06-20 15:08 UTC, vitormattos commented on tests/lib/Comments/ManagerTest.php
> +		$comment = $manager->get(strval($ids[1]));
I did other test to check the opcode in site 3v4l.org using the follow code:

```php
echo (string) 1;
echo strval(1);
```
...and the opcode of second row have one more step, a return:

```
line      #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
    3     0  E >   CAST                                          6  ~0      1
          1        ECHO                                                     ~0
    4     2        CAST                                          6  ~1      1
          3        ECHO                                                     ~1
          4      > RETURN                                                   1
```

https://3v4l.org/ZGBcX/vld

2022-06-24 08:25 UTC, blizzz commented on tests/lib/Comments/ManagerTest.php
> +		$comment = $manager->get(strval($ids[1]));
Ok, it was intval vs int-casting. Never mind then!

2022-06-24 08:27 UTC, blizzz approved these changes

2022-06-24 08:28 UTC, merged

2022-07-13 07:02 UTC, nickvergessen commented
Missing a version bump