Optimize retrieving display name when searching for users in a group
nextcloud/server pull request #32866
Opened 2022-06-13 16:59 UTC by CarlSchwan

This is a recurrent scenario where we are searching for users and then for
each user, we fetch the displayName. This is inefficient, so instead try
to do one query to fetch everything (e.g. Database backend) or use the
already existing DisplayNameCache helper.

Splitted from https://github.com/nextcloud/server/pull/32201

2022-06-14 06:57 UTC, come-nc commented on lib/private/User/Manager.php
> +		$displayNameCache = \OCP\Sserver::get(DisplayNameCache::class);
:snake: :snake:

2022-06-21 09:11 UTC, come-nc commented on lib/private/Group/Database.php
> +		$displayNameCache = \OC::$server->get(DisplayNameCache::class);
\OCP\Server?

2022-06-21 09:14 UTC, come-nc commented on lib/private/Group/Group.php
> +	 * @depreacted 25.0.0 Use searchUsers instead (same implementation)
```suggestion
	 * @deprecated 25.0.0 Use searchUsers instead (same implementation)
```

2022-06-21 09:17 UTC, come-nc commented on lib/public/GroupInterface.php
> +	 * @depreacted 25.0.0 Use searchInGroup instead, for performance reasons
```suggestion
	 * @deprecated 25.0.0 Use searchInGroup instead, for performance reasons
```

2022-06-21 09:21 UTC, come-nc commented on tests/lib/Group/ManagerTest.php
> -		$this->userManager->expects($this->any())
$this->never() ?

2022-06-23 07:02 UTC, come-nc commented on lib/public/Group/Backend/ABackend.php
> +		$displayNameCache = Server::get(DisplayNameCache::class);
missing use statement for DisplayNameCache, IUserManager and LazyUser

2022-08-15 10:11 UTC, icewind1991 requested changes

2022-08-15 10:11 UTC, icewind1991 commented on lib/private/Group/Database.php
> +	public function searchInGroup(string $gid, string $search = '', int $limit = -1, int $offset = 0): array {
Given that this seems to do the same amount of work as `usersInGroup`, it makes sense to have `usersInGroup` call this and map the results to just the uid

2022-08-15 10:11 UTC, icewind1991 commented on lib/private/Group/Database.php
> +		$query->leftJoin('g', 'users', 'u', $query->expr()->eq('g.uid', 'u.uid'))
missing `;`

2022-08-15 10:11 UTC, icewind1991 commented on lib/public/GroupInterface.php
> +	public function searchInGroup(string $gid, string $search = '', int $limit = -1, int $offset = 0): array;
for compatibility with 3rdparty group backends it might make more sense to add a new extension interface for this and have the group manager handle the fallback to `usersInGroup`+`LazyUser`

2022-10-16 17:58 UTC, CarlSchwan commented on lib/public/GroupInterface.php
> +	public function searchInGroup(string $gid, string $search = '', int $limit = -1, int $offset = 0): array;
Done

2022-10-17 09:32 UTC, come-nc approved these changes

2022-10-17 09:32 UTC, come-nc commented on lib/private/User/Manager.php
> +		$displayNameCache = \OCP\Server::get(DisplayNameCache::class);
unused?

2022-12-22 14:05 UTC, come-nc commented
We should decide if the array returned by usersInGroup and searchInGroup is using the uid as key or integers.
This is currently not consistent and why the tests fails.

I would say usersInGroup need to use int for BC, but searchInGroup could use uid as it may be handy in some cases.

2023-01-02 17:16 UTC, come-nc commented
This is ready for review I think.
I would like to test and confirm that it reduces requests though.

2023-05-01 15:55 UTC, icewind1991 approved these changes

2023-05-02 14:42 UTC, merged