allow storing multiple mounts for the same rootid in the mount cache
nextcloud/server pull request #32877
Opened 2022-06-14 13:58 UTC by icewind1991

currently `[$userId, $rootId]` is used as the unique key for storing mounts in the mount cache,
however there are cases where the same rootid is mounted in multiple places for a user which currently leads to not all of those mounts being added to the cache.

Previously this didn't matter as the mount cache was only used to list users with access to a specific file, so a user having access to the file multiple times didn' change anything.

With 24 the mount cache is used for more cases and multiple mounts for the same id becomes relevant.
While I think there isn't a real negative effect atm besides missing the optimized path we should ensure that the mounts are properly listed

Signed-off-by: Robin Appelman <robin@icewind.nl>

2022-06-14 13:59 UTC, icewind1991 commented
Motivation for fixing this is the virtualfolder app which makes it easy to have the same rootid mounted multiple times

2022-06-28 09:53 UTC, come-nc approved these changes

2022-06-28 09:57 UTC, come-nc requested changes
Actually the tests on files_sharing are failing with:
`OCP\Share\Exceptions\GenericShareException: Could not get proper share mount for 1228. Failing since else the next calls are called with null`

2022-07-27 15:12 UTC, PVince81 commented
@icewind1991 can you clean up the PR ?

2023-04-13 15:20 UTC, icewind1991 commented
switched adding the new index to "add missing indexes" instead of the db migration to prevent slow db migration.

2023-04-17 08:27 UTC, come-nc approved these changes
:elephant:

2023-04-24 09:03 UTC, artonge approved these changes

2023-05-02 13:40 UTC, merged

2023-05-02 13:41 UTC, icewind1991 commented
/backport to stable26

2023-05-02 13:41 UTC, icewind1991 commented
/backport to stable25