Remove at matcher in theming tests
nextcloud/server pull request #32900
Opened 2022-06-16 13:57 UTC by come-nc

2022-06-16 18:36 UTC, blizzz requested changes
uncommit .htaccess changes pls

2022-06-16 18:36 UTC, blizzz commented on .htaccess
> +ErrorDocument 404 /
ah-oh

2022-06-20 07:52 UTC, blizzz approved these changes

2022-06-21 09:05 UTC, CarlSchwan approved these changes

2022-06-21 09:45 UTC, merged