Add batch methods in user backends
nextcloud/server pull request #32912
Opened 2022-06-17 09:25 UTC by CarlSchwan

This allows for faster group search with significantly less DB traffic

Splited from #32201 for easier review

2022-06-17 10:17 UTC, szaimen commented on lib/private/Group/Database.php
> +			while ($row = $result->fetch()) {
?

2022-06-20 09:22 UTC, come-nc requested changes

2022-06-20 09:22 UTC, come-nc commented on apps/user_ldap/lib/Group_Proxy.php
> +			if ($exits) {
```suggestion
			$exists = $this->handleRequest($gid, 'groupExists', [$gid]);
			if ($exists) {
```

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Database.php
> +		foreach (array_chunk($gids, 1000) as $chunk) {
```suggestion
		foreach (array_chunk($notFoundGids, 1000) as $chunk) {
```
No?

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Database.php
> +				$details[$row['gid']] = $row['displayname'];
What’s $details?

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Database.php
> +		foreach (array_chunk($gids, 1000) as $chunk) {
Same as above

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Manager.php
> +	protected function getGroupsObject(array $gids, array $displayNames = []): array {
```suggestion
	protected function getGroupObjects(array $gids, array $displayNames = []): array {
```

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Manager.php
> +				foreach ($groupDatas as $gid => $groupData) {
From what I get of getGroupsDetails implementation $groupData here is a string containing the display name no?

2022-06-20 09:22 UTC, come-nc commented on lib/private/Group/Manager.php
> +						// take the display name from the first backend that has a non-null one
Last not first, since you overwrite

2022-06-21 09:00 UTC, come-nc commented on lib/public/GroupInterface.php
> +	 *
Missing @return

2022-06-21 09:00 UTC, come-nc commented on lib/public/GroupInterface.php
> +	public function getGroupsDetails(array $gids): array;
Why is this not in IGroupDetailsBackend?

2022-06-21 09:00 UTC, CarlSchwan commented on lib/private/Group/Database.php
> +				$details[$row['gid']] = $row['displayname'];
```suggestion
				$details[$row['gid']] = ['displayName' => $row['displayname']];
```

2022-07-25 09:32 UTC, come-nc commented on apps/user_ldap/lib/Group_Proxy.php
> +			if ($exits) {
```suggestion
			$exists = $this->handleRequest($gid, 'groupExists', [$gid]);
			if ($exists) {
```

2022-07-25 09:32 UTC, come-nc commented on lib/private/Group/Database.php
> +		foreach (array_chunk($gids, 1000) as $chunk) {
Still valid

2022-07-25 09:32 UTC, come-nc commented on lib/private/Group/Manager.php
> +						// take the display name from the first backend that has a non-null one
Still valid

2022-08-02 13:36 UTC, come-nc approved these changes

2022-08-02 22:22 UTC, CarlSchwan commented
Failing tests are related

2022-09-02 21:16 UTC, blizzz commented on lib/public/Group/Backend/ABackend.php
> +				$existringGroups[] = $gid;
consider making the $gid (also) the key to enable a faster lookup (depends on client usage of course)

2022-09-02 21:16 UTC, blizzz commented on lib/public/Group/Backend/IGroupDetailsBackend.php
> +	public function getGroupsDetails(array $gids): array;
compatibility break

2022-09-05 07:03 UTC, come-nc commented on lib/public/Group/Backend/ABackend.php
> +				$existringGroups[] = $gid;
```suggestion
				$existingGroups[] = $gid;
```
How come psalm does not catch this typo?

2022-10-20 10:46 UTC, CarlSchwan commented on lib/public/Group/Backend/IGroupDetailsBackend.php
> +	public function getGroupsDetails(array $gids): array;
This is why there is a default implementation in ABackend that call getGroupDetails

2022-10-20 10:49 UTC, CarlSchwan commented on lib/public/Group/Backend/ABackend.php
> +				$existringGroups[] = $gid;
Fixed

2023-04-27 09:30 UTC, come-nc commented on lib/public/Group/Backend/IGroupDetailsBackend.php
> +	public function getGroupsDetails(array $gids): array;
@blizzz So what is the verdict here, does this need a new interface?

2023-05-09 15:50 UTC, come-nc commented
Discussed this internally, should be moved to a new interface.

2023-09-05 13:43 UTC, come-nc commented
> Discussed this internally, should be moved to a new interface.

Added the interface, rebased, fixed tests and psalm reports.

2023-09-05 14:13 UTC, Altahrim commented on lib/private/Group/Database.php
> +				$notFounsGids[] = $gid;
```suggestion
				$notFoundGids[] = $gid;
```
There are some of them :)

2023-09-05 14:13 UTC, Altahrim commented on lib/private/Group/Database.php
> +				$existingGroups[] = (string)$row['gid'];
What is the reason to cast them as `string`?

2023-09-05 14:15 UTC, come-nc commented on lib/private/Group/Database.php
> +				$existingGroups[] = (string)$row['gid'];
So that psalm does not complain about the return type.
The database methods do not guarantee at typing level to return string, it’s typed as mixed.
I think that in this case it’s supposed to always be string but I’m not sure, I know there have been surprises about db drivers return null for empty string in the past.

2023-09-07 14:17 UTC, Altahrim approved these changes

2023-09-07 14:17 UTC, Altahrim commented on lib/private/Group/Database.php
> +				->executeQuery();
Nit: I was wondering if it's possible to build the query once and execute it multiple times (like a prepared query) but I don't find how. 
If someone have info about it ^^

2023-09-07 15:03 UTC, come-nc commented on lib/private/Group/Database.php
> +				->executeQuery();
Yes like this https://github.com/nextcloud/server/blob/master/lib/private/Comments/Manager.php#L681

2023-09-07 15:08 UTC, come-nc commented on lib/private/Group/Database.php
> +				->executeQuery();
d18bb7e9bb0b350f65157f648e0c5c8c8f0282cf :wink:

2023-09-11 09:11 UTC, merged