make timeout for brute force operation configurable
nextcloud/server pull request #3295
Opened 2017-01-27 11:27 UTC by schiessle

General default is 12 hours, default for API calls is 10 minutes. If you want to adjust it for your API call use:

````
/**
 * @BruteForceProtection <myapi>
 * @BruteForceProtectionTimeout <seconds>
 */
````

2017-01-27 11:34 UTC, nickvergessen requested changes

2017-01-27 11:34 UTC, nickvergessen commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +			[false, 60, 600],
test float, double and `int.string`

2017-01-27 17:12 UTC, MorrisJobke commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +			[true, 60.3, 600],
I don't get this. Why should 60.3 create a timeout of 600?

2017-01-27 17:12 UTC, MorrisJobke commented on tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
> +			[true, 60.3, 600],
Ah - it's the default

2017-01-30 12:46 UTC, blizzz commented
Read through the connected issues, but it is not clear to me where this benefits us? Why would someone set different values?

2017-01-30 13:53 UTC, blizzz commented
from IRC:

> <BernhardPosselt> i think thats the wrong way to do it
> <BernhardPosselt> apart from that you will break compat with doctrine annotations (if you ever want to go that way)
> <BernhardPosselt> if it should be configurable, then put it into a section inside the config.php
> <BernhardPosselt> one that applies to every request because brute force protection protects against password guessing, so if you add a smaller period you will weaken everything

2017-02-01 20:20 UTC, schiessle commented
> Read through the connected issues, but it is not clear to me where this benefits us? Why would someone set different values?

In the annotations we usually use it to protect against public API calls, e.g. if people send you a federated share. There we want to avoid that people can spam you with hundreds of federated shares, etc. in a few minutes. Therefore it makes sense to have a shorter timespan here.

2017-02-01 21:04 UTC, BernhardPosselt commented
Sounds to me like API rate limiting which is AFAIK not yet built in and serves a different usecase than brute force protection

2017-02-01 21:06 UTC, BernhardPosselt commented
Because brute force protection only works on failed login attempts, correct @LukasReschke ?

2017-02-01 21:29 UTC, nickvergessen commented
That is why we build the API, so it can be on other things too, not only on failed login attempts...

2017-02-01 22:07 UTC, BernhardPosselt commented
I see, then you probably want to rename the annotations to something like 

    @RateLimit(1000)

which would limit the number of requests per caller to maybe 1000 per hour.

2017-02-01 22:08 UTC, BernhardPosselt commented
Check out http://www.django-rest-framework.org/api-guide/throttling/ for more inspiration ;D (that's what we use for the app store)

2017-02-14 13:42 UTC, LukasReschke commented
I have been thinking whether it would make sense to add a function `increaseThrottler` to `\OCP\AppFramework\Controller`. That way in the controller you'd have to call:

`$this->increaseThrottler()` to increase the counter, this is especially useful for the case where we want to use this annotation for a bruteforce protection. The function would basically just increase the amount, the sleep would still be done by the annotation.

For the use-case of API rate limiting one would just have to add that at the start of the function. That would give us way more flexibility here. Also that will solve the problem with https://github.com/nextcloud/server/pull/3265 as we could simply only increase the counter when the password is wrong.

Thoughts?

2017-02-14 13:50 UTC, LukasReschke commented
Or we could go with a `@RateLimit(1000)` one which automatically counts. And a separate one `@BruteforceProtection` one which needs to call `$this->increaseThrottler()`.

2017-02-20 11:40 UTC, nickvergessen commented
Sounds good to me

2017-04-12 18:38 UTC, LukasReschke commented
Replaced by https://github.com/nextcloud/server/pull/4336

2017-04-12 18:38 UTC, closed without merging