Add a single public api for resolving a cloud id to a user and remote and back
nextcloud/server pull request #3297
Opened 2017-01-27 15:16 UTC by icewind1991

Instead of having at least 3 different implementations that might not all behave in the same way.

Additionally, having a single api point makes it easier to add more "fancy" ways to resolve the cloud id such as the various ways described in https://github.com/nextcloud/server/issues/782

2017-02-06 14:28 UTC, icewind1991 commented
All green, @schiessle @MorrisJobke @rullzer please review

2017-02-07 00:24 UTC, MorrisJobke requested changes
Please add tests for the new classes

2017-02-08 15:11 UTC, icewind1991 commented
Rebased and added tests

2017-02-09 02:58 UTC, MorrisJobke approved these changes

2017-02-09 09:18 UTC, nickvergessen requested changes
Only minor things mostly, but please add it to `lib/private/AppFramework/DependencyInjection/DIContainer` so it can be auto injected in apps

2017-02-09 09:18 UTC, nickvergessen commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		$share->setSharedWith(rtrim($cloudId->getId(), '/'));
that should be done by `getId()`

2017-02-09 09:18 UTC, nickvergessen commented on lib/private/Federation/CloudId.php
> +}
missing new line

2017-02-09 09:18 UTC, nickvergessen commented on lib/private/Federation/CloudId.php
> + *
Missing ` @license GNU AGPL version 3 or any later version`

2017-02-09 09:18 UTC, nickvergessen commented on lib/private/Federation/CloudIdManager.php
> + *
Missing ` @license GNU AGPL version 3 or any later version`

2017-02-09 09:18 UTC, nickvergessen commented on lib/public/Federation/ICloudId.php
> +}
new line

2017-02-09 09:18 UTC, nickvergessen commented on lib/public/Federation/ICloudId.php
> + *
Missing ` @license GNU AGPL version 3 or any later version`

2017-02-09 09:18 UTC, nickvergessen commented on lib/public/Federation/ICloudIdManager.php
> + *
Missing ` @license GNU AGPL version 3 or any later version`

2017-02-09 09:18 UTC, nickvergessen commented on lib/public/Federation/ICloudIdManager.php
> +}
new line

2017-02-09 12:33 UTC, icewind1991 commented
@nickvergessen all fixed

2017-02-09 13:46 UTC, nickvergessen approved these changes

2017-02-09 13:54 UTC, merged