Improve local IP detection
nextcloud/server pull request #33031
Opened 2022-06-27 14:50 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-06-27 14:51 UTC, come-nc commented
/backport to stable24

2022-06-27 14:51 UTC, come-nc commented
/backport to stable23

2022-06-27 15:03 UTC, CarlSchwan approved these changes

2022-06-27 15:36 UTC, tcitworld commented on lib/private/Http/Client/LocalAddressChecker.php
> +		if ((bool)filter_var($ip, FILTER_VALIDATE_IP) && in_array($ip, $localIps)) {
Why not put the condition in the above check since the thrown exception and the log are the same?

2022-06-27 16:43 UTC, ChristophWurst approved these changes

2022-06-28 06:53 UTC, come-nc commented on lib/private/Http/Client/LocalAddressChecker.php
> +		if ((bool)filter_var($ip, FILTER_VALIDATE_IP) && in_array($ip, $localIps)) {
But we know $ip is a string and the array contains only string, so it seems useless?

2022-06-28 06:58 UTC, ChristophWurst commented on lib/private/Http/Client/LocalAddressChecker.php
> +		if ((bool)filter_var($ip, FILTER_VALIDATE_IP) && in_array($ip, $localIps)) {
Better safe than sorry.

2022-06-28 09:36 UTC, come-nc commented on lib/private/Http/Client/LocalAddressChecker.php
> +		if ((bool)filter_var($ip, FILTER_VALIDATE_IP) && in_array($ip, $localIps)) {
I grouped them

2022-06-28 13:16 UTC, kesselb commented
Does it make sense to add the $localIps check to https://github.com/nextcloud/server/blob/0c049919151f47c0136cd8462d08b398c455de18/lib/private/Http/Client/LocalAddressChecker.php#L55 as well?

2022-06-28 14:46 UTC, come-nc commented
Good catch, I suppose it makes sense

2022-06-29 12:33 UTC, ChristophWurst approved these changes

2022-06-29 13:08 UTC, icewind1991 requested changes

2022-06-29 13:08 UTC, icewind1991 commented on lib/private/Http/Client/LocalAddressChecker.php
> +		$localIps = ['100.100.100.200'];
This should check against the entire 100.64.0.0/10 instead of just the single ip.

(and add a comment about why this ip range is being checked for)

2022-07-12 09:44 UTC, come-nc commented
/rebase

2022-07-26 08:49 UTC, CarlSchwan approved these changes

2022-07-26 09:39 UTC, merged