Paths added to messages and message cleanup
nextcloud/server pull request #33061
Opened 2022-06-29 12:38 UTC by pboguslawski

This mod adds path to error messages. Without it it's difficult for example
to find what path causes permission problems.

Related: https://help.nextcloud.com/t/ocp-files-notpermittedexception-could-not-create-folder/133818
Related: https://help.nextcloud.com/t/could-not-create-folder-false-error/65962/
Author-Change-Id: IB#1121253

2022-06-29 12:45 UTC, CarlSchwan approved these changes
Make sense to me, thanks!

2022-06-30 17:52 UTC, kesselb requested changes, later dismissed
Hi, thanks for your pull request :+1: 

Please rebase this branch to master. Our usual process here is that every change goes to master and is backported (usually by a bot) if necessary.

2022-07-01 09:35 UTC, pboguslawski commented
Just force pushed this branch with commit fcb4943071803716d8b7d51c973b440278f18c6d; this commit was created from master and DCO is present now - please change target branch of this PR from `stable24` to `master`.

2022-07-04 10:09 UTC, miaulalala approved these changes

2022-07-04 11:12 UTC, szaimen commented
/rebase

2022-07-27 15:00 UTC, PVince81 commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
please don't change the copyright of the whole file

I guess maybe your IDE made this change ?

2022-07-27 15:01 UTC, PVince81 commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
```suggestion
 * @copyright Copyright (c) 2016, ownCloud, Inc.
```

2022-07-27 15:15 UTC, pboguslawski commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
Removed copyright. We add it intentionally to fulfill the AGPL requirement 5a:
https://www.gnu.org/licenses/agpl-3.0.en.html

2022-07-27 15:34 UTC, tcitworld commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
You can use the `@author` doctype below instead

2022-07-27 15:51 UTC, pboguslawski commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
> You can use the @author doctype below instead

Please point to formal sentence that states that @author way is correct for AGPL. Seems that more standard/common is adding Copyright notice (vide [[1]](https://opensource.google/documentation/reference/copyright), [[2]](https://opensource.stackexchange.com/questions/8639/gpl-v3-0-is-there-a-standard-format-for-modification-notice)).

2022-07-27 15:56 UTC, tcitworld commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
I don't make such a claim, this was just a suggestion.

https://github.com/nextcloud/server/blob/master/contribute/HowToApplyALicense.md proves you right anyway.

2022-07-29 08:24 UTC, PVince81 commented on lib/private/Files/Node/Folder.php
> + * @copyright Copyright (c) 2022 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
thanks, I wasn't aware of that practice as it seems very rare that people add a second copyright notice line.

then this is fine :+1:

2022-07-29 08:26 UTC, PVince81 commented
@pboguslawski do you might also adding a signed-off clause as per https://github.com/nextcloud/server/pull/33061/checks?check_run_id=7544272332 ? the DCO part is also stated in https://github.com/nextcloud/server/blob/master/contribute/HowToApplyALicense.md

2022-07-29 11:36 UTC, pboguslawski commented
DCO fixed.

2022-10-17 09:50 UTC, ChristophWurst commented
Unsure if failing CI is related or not. Could you please rebase to the latest `master` to have another clean CI run?

2022-11-04 12:35 UTC, pboguslawski commented
Current master merged to this PR.

2023-01-12 14:55 UTC, ChristophWurst approved these changes

2023-01-12 14:55 UTC, ChristophWurst commented
Failing CI unrelated

2023-01-24 09:21 UTC, come-nc commented
/rebase

2023-03-14 16:28 UTC, come-nc approved these changes

2023-03-14 16:28 UTC, merged