Remake Twitter handle saving with Vue
nextcloud/server pull request #33217
Opened 2022-07-13 00:27 UTC by Pytal

2022-07-13 11:01 UTC, tcitworld commented on apps/settings/src/components/PersonalInfo/TwitterSection/TwitterSection.vue
> +		<Twitetr :twitter.sync="twitter.value"
Typo
```suggestion
		<Twitter :twitter.sync="twitter.value"
```

2022-07-15 20:33 UTC, Pytal commented
Keeping as draft pending merge of

- [ ] https://github.com/nextcloud/server/pull/33206

2022-07-28 08:58 UTC, artonge requested changes
Nice cleanup :)

2022-07-28 08:58 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/AccountPropertyInput.vue
> +			:id="name"
Fragile as it can lead to duplicate ids. I would at least make it more specific, like `profile-form-${name}`. Bonus if there is a random string :D, but might be overkill and cumbersome.

2022-07-28 08:58 UTC, artonge commented on apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
> +		<AccountPropertyInput v-bind.sync="property"
Would it make sense to merge `AccountPropertyInput` and `AccountPropertySection` ? They share common props, and `AccountPropertySection` does not add a lot of logic. But maybe `AccountPropertyInput` is used standalone somewhere else?

2022-07-29 00:13 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue
> +		<AccountPropertyInput v-bind.sync="property"
Makes sense, merged :)

2022-07-29 12:06 UTC, artonge approved these changes

2022-08-09 03:11 UTC, Pytal commented
Rebased and review-ready

2022-08-10 20:49 UTC, PVince81 commented
@Pytal this PR seems to contain a lot more changes than just the Twitter handle, in case it's not a mistake, please adjust the PR title and description

2022-08-11 01:27 UTC, Pytal commented
> @Pytal this PR seems to contain a lot more changes than just the Twitter handle, in case it's not a mistake, please adjust the PR title and description

Title updated, description already adjusted and commits already split between modularization and Twitter section

2022-08-25 15:21 UTC, PVince81 commented
@Pytal rebase needed and also a second review

2022-08-25 21:40 UTC, PVince81 approved these changes
:+1:

2022-08-25 21:40 UTC, merged