WIP: Birthday Calendar Reminder Setting
nextcloud/server pull request #33251
Opened 2022-07-17 13:07 UTC by cneukom

Closes https://github.com/nextcloud/server/issues/1505.

2022-07-17 16:38 UTC, cneukom commented on apps/dav/lib/CalDAV/BirthdayService.php
> +				$this->updateCalendar($cardUri, $cardData, $book, (int) $calendar['id'], $type, $reminderOffset);
Fixed in 9eb276b20b051c31b349671600961c60d94ad175

2022-07-17 16:38 UTC, cneukom commented on apps/dav/lib/CalDAV/BirthdayService.php
> +				$this->updateCalendar($cardUri, $cardData, $book, (int) $calendar['id'], $type, $reminderOffset);
Fixed in 9eb276b20b051c31b349671600961c60d94ad175

2022-07-17 16:38 UTC, cneukom commented on apps/dav/lib/CalDAV/BirthdayService.php
> +				$this->updateCalendar($cardUri, $cardData, $book, (int) $calendar['id'], $type, $reminderOffset);
Fixed in 9eb276b20b051c31b349671600961c60d94ad175

2022-07-18 09:07 UTC, miaulalala commented
Performance check fails bc remote is not origin.

2022-07-18 09:08 UTC, miaulalala requested changes

2022-07-18 09:08 UTC, miaulalala commented on apps/dav/lib/CalDAV/BirthdayService.php
> +									?string $reminderOffset):void {
please initialise this with `null` just in case any other app uses the method.

2022-07-18 13:57 UTC, tcitworld commented on apps/dav/lib/CalDAV/BirthdayService.php
> +									?string $reminderOffset):void {
It's a private method :)

2022-07-19 09:15 UTC, miaulalala approved these changes
LGTM

2022-07-25 16:17 UTC, tcitworld approved these changes

2022-07-26 18:59 UTC, merged