Fix accessibility of input fields
nextcloud/server pull request #33259
Opened 2022-07-18 11:35 UTC by CarlSchwan

Input fields require a 44x44 pixels target size, this makes all the
input fields and buttons use that size.

Bonus is that now the input fields and buttons now have the same size as
the new vue button and this looks less weird than the previous state
with controls of different sizes.

See https://www.w3.org/WAI/WCAG21/Understanding/target-size.html

Screenshots:

![image](https://user-images.githubusercontent.com/23653902/179502364-01dfc82c-8b71-4b44-9c9e-f6e8bed6f83c.png)

![image](https://user-images.githubusercontent.com/23653902/179502881-4740346d-2e88-4e36-8e09-126a9251450a.png)

![image](https://user-images.githubusercontent.com/23653902/179502969-bfb37765-fa6e-4f99-ac74-83bae879114c.png)

2022-07-18 13:33 UTC, jancborchardt requested changes
The left/right padding needs to be adjusted, currently it’s way too little. It should be visually the same as the top/bottom padding. (Also compare to the select dropdown e.g. for language, where the left/right padding is better but actually a bit too much.)

2022-07-27 09:51 UTC, CarlSchwan commented
> The left/right padding needs to be adjusted, currently it’s way too little. It should be visually the same as the top/bottom padding. (Also compare to the select dropdown e.g. for language, where the left/right padding is better but actually a bit too much.)

I updated the screenshots to include the new paddings

2022-07-27 10:17 UTC, artonge submitted a review, later dismissed

2022-07-27 14:50 UTC, PVince81 commented
@CarlSchwan if this is ready for re-review, please re-request review from Jan-C instead of leaving it blocking

2022-07-27 18:36 UTC, Pytal submitted a review, later dismissed
Other than the comment below

2022-07-27 18:36 UTC, Pytal commented on apps/user_ldap/lib/Group_LDAP.php.rej
> +
This file should be removed

2022-07-27 21:44 UTC, jancborchardt approved these changes
Looks good now! :)

2022-07-28 07:33 UTC, jancborchardt commented on core/css/inputs.scss
>  	font-size: 13px;
Btw @CarlSchwan while upping the size, we could also adjust this to be the default font size (15px), then it would look less strange and be legible too. As per https://github.com/nextcloud/nextcloud-vue/issues/2172

2022-07-28 14:31 UTC, CarlSchwan commented
Probably also best to wait for https://github.com/nextcloud/nextcloud-vue/pull/2868 to get merged to adapt the style/size as much as possible to the new view component

2022-08-10 20:44 UTC, PVince81 commented
@CarlSchwan still ready to merge then ? it's green!

2022-08-11 09:38 UTC, CarlSchwan commented
Adapted to the new style of Nextcloud vue components and change the font size to 15px

![image](https://user-images.githubusercontent.com/23653902/184105585-6a923d49-0ee4-44eb-9a40-332b2f0d5985.png)

2022-08-11 10:13 UTC, nickvergessen commented
Somehow this is limiting the width of selects by default very much.

Talk code in both screenshots is unmodified

Before | After
---|---
![Bildschirmfoto vom 2022-08-11 12-12-17](https://user-images.githubusercontent.com/213943/184112055-af2c20c4-f6a3-4a3c-b43f-caff08acfe01.png) | ![Bildschirmfoto vom 2022-08-11 12-12-28](https://user-images.githubusercontent.com/213943/184112060-d605b41b-0a01-44aa-8490-88200e0f75e8.png)

2022-08-11 10:19 UTC, nickvergessen commented on core/css/inputs.scss
>  input[type='reset'] {
you effectively removed select from this so the size doesn't grow to `width:auto` anymore causing the outlined issue in talks admin settings (and many other)

2022-08-11 12:59 UTC, CarlSchwan commented on core/css/inputs.scss
>  input[type='reset'] {
Should be fixed now

2022-08-11 13:06 UTC, nickvergessen commented on core/css/inputs.scss
>  input[type='reset'] {
Yes, fixed

2022-08-12 06:37 UTC, nickvergessen commented
This brings in various regressions all over the place which I kind a dislike on the last day.

### Talk participant search
![Bildschirmfoto vom 2022-08-12 08-30-16](https://user-images.githubusercontent.com/213943/184297865-20cd692b-d072-47f1-9e7a-4b32709e51d2.png)

### Talk room filter pushes off the + button
![Bildschirmfoto vom 2022-08-12 08-31-02](https://user-images.githubusercontent.com/213943/184297870-4e0ad541-f073-469d-b22a-b3ff53c2e43f.png)

### Multiselects (Vue component) get white background aspects?!
Before | After
---|---
![Bildschirmfoto vom 2022-08-12 08-33-49](https://user-images.githubusercontent.com/213943/184297872-c38fa4b0-0780-4cc0-a570-cc0101e6785f.png) | ![Bildschirmfoto vom 2022-08-12 08-34-01](https://user-images.githubusercontent.com/213943/184297873-8f943980-8928-4019-9fad-cfe9c20c559b.png)
![Bildschirmfoto vom 2022-08-12 08-36-17](https://user-images.githubusercontent.com/213943/184298095-fe666910-d16d-4812-8b70-6cc309958fb2.png) | ![Bildschirmfoto vom 2022-08-12 08-36-06](https://user-images.githubusercontent.com/213943/184298099-4e8e1b6b-d131-4987-8379-3b72c7df6545.png)

While I get the point of making all inputs look the same, last minutes enforcements like this are a bit painful.

2022-08-12 06:46 UTC, nickvergessen commented
### Elements get double borders
![Bildschirmfoto vom 2022-08-12 08-38-57](https://user-images.githubusercontent.com/213943/184299190-1fdea8b6-1b6c-4680-a593-16e5fd2f2b30.png)
![Bildschirmfoto vom 2022-08-12 08-44-04](https://user-images.githubusercontent.com/213943/184299199-7b83c921-90e9-49ac-8cf1-f01b5d9558c1.png)

### Share input is white
![Bildschirmfoto vom 2022-08-12 08-39-37](https://user-images.githubusercontent.com/213943/184299191-c46f9c3b-9651-4e56-9cb8-b8eaf788771f.png)

### Combined submit button looks weird
![Bildschirmfoto vom 2022-08-12 08-41-02](https://user-images.githubusercontent.com/213943/184299194-1d73337f-0cbe-4fb9-ad11-883e9d3deb2e.png)

### Contacts menu button stretched

Before | After
---|---
![Bildschirmfoto vom 2022-08-12 08-42-56](https://user-images.githubusercontent.com/213943/184299196-a47d8dc9-c410-4585-96c9-163d5585da59.png) | ![Bildschirmfoto vom 2022-08-12 08-43-07](https://user-images.githubusercontent.com/213943/184299198-9bb8991d-6647-4b07-a8f1-cf0e677a7c1b.png)

2022-08-12 06:46 UTC, nickvergessen requested changes
See above

2022-08-12 07:06 UTC, PVince81 commented
@CarlSchwan for now we're first aiming for AA, not AAA, so merging this isn't critical if it's only about target size

2022-08-12 10:39 UTC, CarlSchwan commented
From the list of issues reported by @nickvergessen only the search field component issue remains and this should probably just be ported to the proper TextField component with a leading icons

2022-08-25 21:46 UTC, PVince81 commented
oops, I merged @Pytal's #33217 and now there's conflicts again with your changes :-/

2022-08-25 23:35 UTC, Pytal commented
🤔 looks like we just need to adapt the styles in https://github.com/nextcloud/server/blob/master/apps/settings/src/components/PersonalInfo/shared/AccountPropertySection.vue#L192-L265 @CarlSchwan

2022-08-26 11:07 UTC, CarlSchwan commented
> oops, I merged @Pytal's #33217 and now there's conflicts again with your changes :-/

rebased :) let's hope it is the last time

2022-08-26 11:49 UTC, nickvergessen commented
> Conflicting files
dist/core-main.js.map 

Merged by @CarlSchwan 
https://github.com/nextcloud/server/commit/aa150b9f85a2543fdbac8e73b5e6f8bb39f125f4

Shame on him!

2022-08-26 12:04 UTC, miaulalala approved these changes
:elephant:

2022-08-26 12:06 UTC, skjnldsv approved these changes
:elephant: :elephant:

2022-08-26 12:20 UTC, PVince81 approved these changes
:+1: (we got a nice tour of this yesterday)

2022-08-26 17:46 UTC, skjnldsv commented
/rebase

2022-08-26 17:59 UTC, merged