Redesign login boxes for better accessibility
nextcloud/server pull request #33265
Opened 2022-07-18 15:59 UTC by CarlSchwan

2022-07-18 16:09 UTC, jancborchardt commented
Looks great! :) 2 things:
- For the first screenshot, "Access forbidden" should be marked up as a heading, right?
- These are all wide boxes, do you have a screenshot of the login view (with the username & password boxes) as well?

2022-07-19 06:34 UTC, CarlSchwan commented
> For the first screenshot, "Access forbidden" should be marked up as a heading, right?

Right this was a preexisting issue, fixed now ;)

> These are all wide boxes, do you have a screenshot of the login view (with the username & password boxes) as well?

I updated all the box to not be wide anymore by default unless specified otherwise like on the exception page. Screenshots of the new states are updated

2022-07-19 09:24 UTC, jancborchardt requested changes
Very nice, looks so good now! :) Only 2 things:
- [ ] There is focus feedback on the username/password input field, but they don’t have a default border. Either using the component, or `border: 2px solid var(--color-border)` would look nice.
- [ ] From the screenshots, all the scenarios except the internal server error look better with the narrow style – so I’d say let’s change the "Connect to your account" and "Account access" to narrow style. :)

2022-07-20 12:40 UTC, nimishavijay approved these changes
All the screenshots look great! :) 
Not sure if this is relevant to this PR but we should change everything that was full opacity black `#000000` to `--color-main-text`, it's especially visible in the screenshot with the app icons.

2022-07-20 15:53 UTC, nickvergessen requested changes

2022-07-20 15:53 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +			{{ t('core', 'Loading apps…') }}
Since it's not shortcutting the word "apps" the space is required

2022-07-20 15:53 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +			{{ t('core', 'Installing apps…') }}
Since it's not shortcutting the word "apps" the space is required

2022-07-20 15:53 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +			<Button type="tertiary-no-background"
```suggestion
			<Button type="tertiary"
```

No background should only be used inside of inputs

2022-07-20 15:53 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +		}
```suggestion
		filter: var(--background-invert-if-dark);
```

2022-07-20 15:53 UTC, nickvergessen commented on core/src/views/Login.vue
> +					</small>
Either linebreak both or none 😿

2022-07-20 15:53 UTC, nickvergessen commented on core/templates/installation.php
> +	<div class="buttons"><input type="submit" class="primary" value="<?php p($l->t('Install')); ?>" data-finishing="<?php p($l->t('Installing…')); ?>"></div>
Since it's not shortcutting the word "installing" the space is required

2022-07-20 15:53 UTC, nickvergessen commented on core/templates/layout.guest.php
> +<html class="ng-csp nc-<?php p($_['major_version']); ?>" data-placeholder-focus="false" lang="<?php p($_['language']); ?>" data-locale="<?php p($_['locale']); ?>" >
I don't think we should start this.

2022-07-20 15:53 UTC, nickvergessen commented on core/templates/layout.public.php
> +<html class="ng-csp nc-<?php p($_['major_version']); ?>" data-placeholder-focus="false" lang="<?php p($_['language']); ?>" data-locale="<?php p($_['locale']); ?>" >
Same here. This is just going to bring us to a hell....

2022-07-20 15:53 UTC, nickvergessen commented on core/templates/loginflowv2/authpicker.php
> +		<a href="<?php p($urlGenerator->linkToRouteAbsolute('core.ClientFlowLoginV2.grantPage', ['stateToken' => $_['stateToken'], 'user' => $_['user']])) ?>"  tabindex="-1">
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

> A negative value is useful when you have off-screen content that appears on a specific event. The user won't be able to focus any element with a negative tabindex using the keyboard, but a script can do so by calling the focus() [method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus).

doesn't sound like the correct usecase?

2022-07-20 15:53 UTC, nickvergessen commented on lib/private/TemplateLayout.php
> +		$this->assign('major_version', \OCP\Util::getVersion()[0]);
😿

2022-07-20 15:53 UTC, nickvergessen commented on core/css/guest.css
> +}
those names -.-

2022-07-20 17:51 UTC, Pytal commented on core/css/guest.css
> +}
Are we introducing in-house Tailwind CSS?

2022-07-21 06:31 UTC, CarlSchwan commented on core/templates/loginflowv2/authpicker.php
> +		<a href="<?php p($urlGenerator->linkToRouteAbsolute('core.ClientFlowLoginV2.grantPage', ['stateToken' => $_['stateToken'], 'user' => $_['user']])) ?>"  tabindex="-1">
I replaced the `<a>` with a `<form>` and this should do the trick without having two element tab focusable but doing the same

2022-07-21 06:31 UTC, CarlSchwan commented on core/src/components/setup/RecommendedApps.vue
> +			{{ t('core', 'Installing apps…') }}
reverted, but this feels weird. Is this convention documented somewhere?

2022-07-21 08:24 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +			{{ t('core', 'Installing apps…') }}
@rakekniven @jancborchardt anyone has a link?

2022-07-22 11:11 UTC, nickvergessen requested changes

2022-07-22 11:11 UTC, nickvergessen commented on core/src/components/login/LoginButton.vue
>  	}
🙈  I was about to find where this breaks, but you do it intentionally.
I think it would be time to follow the common pattern and have a useful icon (not `->`) or no icon.

Also the icon is now on all buttons (social login, registration, ...) which looks awkward

2022-07-22 11:11 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +			<Button type="tertiary-no-background"
This is still not resolved?

2022-07-22 11:11 UTC, nickvergessen commented on core/src/views/Login.vue
> +					key="login">
invalid attribute?!

2022-07-22 11:11 UTC, nickvergessen commented on core/src/views/Login.vue
> +							@abort="resetPassword = false" />
Text is not readable in dark mode:
![Bildschirmfoto vom 2022-07-22 13-10-27](https://user-images.githubusercontent.com/213943/180427356-774fd254-9bd4-4907-9c48-05b9598f3796.png)

2022-07-22 11:11 UTC, nickvergessen commented on core/src/views/Login.vue
> +				</template>
```suggestion
```

No duplicate icons please

2022-07-22 11:21 UTC, nickvergessen commented on core/src/views/Login.vue
> +						{{ t('core', 'Forgot password?') }}
TExt is not readable on dark mode

![Bildschirmfoto vom 2022-07-22 13-10-27](https://user-images.githubusercontent.com/213943/180429095-c2c3c781-e572-46cd-bc7a-71661e4f2fbb.png)

2022-07-25 07:36 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +		}
```suggestion
		filter: var(--background-invert-if-dark);
```

To respect the user preference in case they overwrite the browser prefers setting?
Or does it not work on the install/update page?

2022-07-25 17:28 UTC, AndyScherzinger commented
@jancborchardt looking at the screenshot
![install3](https://user-images.githubusercontent.com/23653902/179971602-857d97a4-30ba-4c55-ae3a-98d23ca15136.png)

shouldn't "Cancel" rather be "Skip" ?

2022-07-25 17:31 UTC, CarlSchwan commented
> @jancborchardt looking at the screenshot ![install3](https://user-images.githubusercontent.com/23653902/179971602-857d97a4-30ba-4c55-ae3a-98d23ca15136.png)
> 
> shouldn't "Cancel" rather be "Skip" ?

It should, good catch

2022-07-25 17:37 UTC, AndyScherzinger commented
Thanks for caring and for taking care @CarlSchwan 💙

2022-07-26 08:04 UTC, CarlSchwan commented
> Thanks for caring and for taking care @CarlSchwan blue_heart

Fixed :)

I would say this is good to go now. There might be some apps that need to be adapted after this change but I for the moment checked most of them and everything seems to still work fine

2022-07-26 08:13 UTC, nickvergessen commented on core/src/components/setup/RecommendedApps.vue
> +				{{ t('core', 'Cancel') }}
```suggestion
				{{ t('core', 'Skip') }}
```

2022-07-26 08:14 UTC, nickvergessen commented
> It should, good catch

forgot to push? Or Push failed?

2022-07-26 08:38 UTC, CarlSchwan commented
> > It should, good catch
> 
> forgot to push? Or Push failed?

forgot to push :(

2022-07-26 09:33 UTC, nickvergessen approved these changes

2022-07-27 07:28 UTC, nickvergessen commented on core/templates/loginflow/authpicker.php
>  		</a>
```suggestion
		</from>
```

2022-07-27 10:37 UTC, merged

2022-07-27 21:25 UTC, jancborchardt commented
@CarlSchwan this looks so damn cool, and is much more accessible on top of it. Great work! ✨