Rename files settings on the bottom left
nextcloud/server pull request #33306
Opened 2022-07-21 12:31 UTC by PVince81

Part of https://github.com/nextcloud/server/issues/32350

<img width="253" alt="image" src="https://user-images.githubusercontent.com/277525/180213915-ad8d6461-c7c5-4f83-8242-0b15623f2f30.png">

2022-07-21 13:01 UTC, jancborchardt requested changes

2022-07-21 13:01 UTC, jancborchardt commented on apps/files/templates/appnavigation.php
> +				<?php p($l->t('Files Settings')); ?>
```suggestion
				<?php p($l->t('Files settings')); ?>
```

2022-07-21 14:03 UTC, jancborchardt approved these changes

2022-07-21 14:10 UTC, nimishavijay approved these changes

2022-07-21 19:08 UTC, Pytal approved these changes

2022-07-21 19:12 UTC, Pytal commented
CI failure seems related to this https://github.com/nextcloud/server/blob/6c42874f04477a9741089bd4763ad47ad4130b2f/tests/acceptance/features/bootstrap/SettingsMenuContext.php#L143

2022-07-22 09:44 UTC, merged

2022-07-22 16:11 UTC, PVince81 commented
I'll push a follow up PR

2022-07-22 16:19 UTC, PVince81 commented
@Pytal I checked the related code and it all looks related to the top right menu, not the bottom left. weird

2022-07-22 16:22 UTC, PVince81 commented
@Pytal this is the actual issue: ` Nextcloud test server could not be started (Exception)`

it's just a coincidence that the test scenario contains a reference to settings, and here it means the settings page from the top right menu