disabling command line updater
nextcloud/server pull request #3333
Opened 2017-01-31 09:03 UTC by samuelstein

from my point of view it is very annoying that the user will be pushed to update the installation on command line if he uses ldap or has more than 50 users.
It is especially problematic on shared hosters. I disabled the check.

2017-01-31 09:24 UTC, nickvergessen requested changes
Well the problem is, that on shared hosting also php might be limited so it is very likely that the update runs into a timeout leaving your instance in a non-recoverable unknown state between too versions.

That is why this was added in first place. You might remove that yourself every time, or add a config option or something that is to be used on own risk. But it should not be removed because it is annoying, it's helping.

2017-01-31 14:47 UTC, MorrisJobke commented
@blizzz is there a cheap way to detect if the user count on LDAP is below/above 50? Then I guess it's okay to keep web updater enabled

2017-01-31 19:11 UTC, blizzz commented
> @blizzz is there a cheap way to detect if the user count on LDAP is below/above 50? Then I guess it's okay to keep web updater enabled

In principle yes… The LDAP Backend has the wonderful method of ``countUsers`` that takes a limit argument. There is however no API to access it. So it requires extra code to get into it.

An alternative way is to check how many folders are located in the data directory (as user:report does), however, if LDAP users have their home directories somewhere else, this would not be caught, and fail.

Also, you could have a look how many Users are mapped in the LDAP mappings table. The Mapping class is easy to instantiate and provides a ``list`` method, allowing to specify a limit. Checking this with a limit of 51 and checking the result should suffice. Also, this is not 100% and can report more users than are currently available, but it does not cause a false positive on a big instance, as would counting directories.

Hard-wired this is feasible to be solved with 5 LOCs

```php
if($apps->isInstalled('user_ldap')) {
    $ldapUserMapper = new \OCA\User_LDAP\Mapping\UserMapping(\OC::$server->getDatabaseConnection());
    $mappedUsers = $ldapUserMapper->getList(0, 51);
    $tooBig = count($mappedUsers) === 51;
}
```

(coded dryly)

There is no proper way via UserManager unfortunately. And to have this solved properly, any backend should be able to tell if it is too big or not. We could extent an API to include a user count with limit parameter and the User Manager could just have a convenience method (is~~Great~~BigInstance() e.g.).

2017-02-01 06:54 UTC, nickvergessen commented
Check via Accounts Manager? Or prefernces login timestamp

2017-02-01 09:09 UTC, samuelstein commented
@nickvergessen i understand the problem with script timeouts on shared hosters. but the problem will not be solved when the user will be pushed to use the commandline (most shared webspaces even don't over such an interface).
better solution would be to make it in **config.php** configurable if you want to update it via webupdater. then the risk is on the shoulder of the admin.

2017-02-01 12:44 UTC, blizzz commented
> Check via Accounts Manager? Or prefernces login timestamp

AccountManager does not have useful methods as of now,  but the timestamp would also give you an idea indeed.

@samuelstein I get you concerns, however I second that having the web updater on without checks is more likely to cause big trouble to admins (that also often do not have the insights!) than having the precaution. Improving the ``$tooBig`` indicator is the safer approach.

2017-02-16 22:44 UTC, MorrisJobke commented
Okay ... so we are not going to delete this code, but I will look into make it possible for installations with LDAP and less than 50 people to run the web based updater.

2017-02-16 22:44 UTC, closed without merging

2017-02-16 22:46 UTC, MorrisJobke commented
> Okay ... so we are not going to delete this code, but I will look into make it possible for installations with LDAP and less than 50 people to run the web based updater.

To not lose this idea: #3518