Fix typos in lib/public subdirectory
nextcloud/server pull request #33381
Opened 2022-07-27 13:00 UTC by luzpaz

Found via `codespell -q 3 -S l10n -L jus ./lib/private`

Signed-off-by: luz paz <luzpaz@github.com>

2022-07-27 14:43 UTC, PVince81 approved these changes
:+1: looks fine

2022-07-28 07:15 UTC, come-nc requested changes

2022-07-28 07:15 UTC, come-nc commented on lib/public/Accounts/IAccount.php
> +	 * Returns the requests property collection (multi-value properties)
```suggestion
	 * Returns the requested property collection (multi-value properties)
```

2022-07-28 10:22 UTC, luzpaz commented
Squashed. Shall I also rebase or not necessary?

2022-07-28 11:34 UTC, come-nc approved these changes

2022-07-28 11:35 UTC, come-nc commented
> Squashed. Shall I also rebase or not necessary?

I do not think a rebase is needed, but the DCO bot is somehow unhappy, can you look into it?

2022-07-28 13:20 UTC, luzpaz commented
Not sure why.

2022-07-28 13:26 UTC, szaimen commented
I think it expects a different mail but this is not a problem and we can just set it to skip, afaics.

2023-05-10 09:49 UTC, skjnldsv approved these changes

2023-05-10 09:50 UTC, skjnldsv commented
Please fix conflict and we can merge

2023-05-11 08:26 UTC, merged