Fix update when viewer is not installed
nextcloud/server pull request #33457
Opened 2022-08-04 08:55 UTC by CarlSchwan

Since the viewer app is not shipped with server, currently with a fresh clone of
the server repo it is impossible to do an update.

2022-08-04 09:19 UTC, PVince81 commented
should we limit the check for git clones ? this can be detected by checking if versions.php contains "git" as the update channel, there are some APIs to read it

2022-08-16 07:22 UTC, PVince81 commented
seems pef ci fails because of viewer, ex: https://github.com/nextcloud/server/runs/7844066536?check_suite_focus=true

2022-08-16 19:28 UTC, skjnldsv commented
https://github.com/nextcloud/server/blob/1c60ff5936bf9c8358072023aeafa8a7ccd0c800/core/shipped.json#L59 maybe?

2022-08-17 08:36 UTC, CarlSchwan commented
> https://github.com/nextcloud/server/blob/1c60ff5936bf9c8358072023aeafa8a7ccd0c800/core/shipped.json#L59
> maybe?

but then viewer won't be enabled by default anymore if I understand correctly :( 

Also the ci is currently unhappy with my fix :(

2022-08-17 08:40 UTC, PVince81 commented
@CarlSchwan adding to shipped.json is independent from "default_enable". most other shipped apps are also enabled by default, ex: user_status

2022-08-17 10:52 UTC, skjnldsv requested changes
AH, no, I meant that some logic behind might be at cause.
But we need to keep the always_enabled on. Viewer can _not_ be disabled as it will break tons of areas. We took the decision a while back.

2022-08-17 10:53 UTC, skjnldsv commented
> @CarlSchwan adding to shipped.json is independent from "default_enable". most other shipped apps are also enabled by default, ex: user_status

The difference is that you can disable `user_status` without issues.

2022-08-30 08:50 UTC, closed without merging