Extract GPS data from EXIF
nextcloud/server pull request #33511
Opened 2022-08-11 17:29 UTC by artonge

:warning: Currently half broken:

Some work has been done by @CarlSchwan here: https://github.com/nextcloud/server/pull/31839/files#diff-696d573a441e273811747c682474b6b94c726470441f35092a30824bdb7553f9R18

But the `exif_read_data` call does not work, and probably never worked. One possible explanation is that the resource is wrapped. From the README https://github.com/icewind1991/streams:

> Note: due to php's internal stream buffering the $count passed to the read callback will be equal to php's internal buffer size (8192 on default) an not the number of bytes requested by fopen() 

As it works when the stream is not wrapped, it might be an explanation for why the `exif_read_data` call fails? If it, would it be possible to retrieve the original stream to provide it to `exif_read_data`? If not, could add a method on the wrapper class to retrieve the original stream?

The last option would be to use the file path, but it won't work for S3 buckets.

2022-08-24 14:47 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$nativeFileDescriptorStream = fopen('php://temp', 'rw');
I think we have a function `getLocalFile` (?) to return the path to a local file, it will be downloaded to a temp file when necessary

2022-08-24 14:47 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
if exif_read_data is so troublesome, should we look for another library that does this the right way ?

2022-08-24 14:50 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$nativeFileDescriptorStream = fopen('php://temp', 'rw');
check if this works: https://www.getid3.org/

2022-08-24 15:50 UTC, CarlSchwan commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
exif read data is part of the standard library of php

the only other alternative is a pel, a php5 library https://github.com/pel/pel

2022-08-24 17:37 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
ah, I posted it in the wrong thread.

I meant to say that we already have https://www.getid3.org/ in composer.json, so we might as well use that.
they added support for extracting from streams recently IIRC (something I think I saw together with @skjnldsv)

2022-08-24 17:46 UTC, CarlSchwan commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
It's just using exif read data internally https://github.com/JamesHeinrich/getID3/blob/e54782d655120e5993ceeca9fb0e01895255ed07/getid3/module.graphic.jpg.php#L80

2022-08-25 08:05 UTC, come-nc reviewed
A few remarks.

Regarding copying the stream to a temp one, I have no idea if this is avoidable.

2022-08-25 08:05 UTC, come-nc commented on lib/private/Metadata/Provider/ExifProvider.php
> +			[$degree, $dividend] = explode('/', $rawDegree);
If dividend is not always there as suggested by the ?? 1 below, this will trigger PHP warnings.
You need to use something like:
```
			$parts = explode('/', $rawDegree);
			return floatval($parts[0])/floatval($parts[1] ?? 1);
```

2022-08-25 08:05 UTC, come-nc commented on lib/private/Metadata/Provider/ExifProvider.php
> +		}, $coordinates);
Maybe also validate that $coordinates contains 3 values? We have to consider exif data as user input I think, so it might be broken in several ways.

2022-08-25 14:14 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +			$exifData['size'] = $size;
No need indeed

2022-08-25 14:30 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
From https://github.com/nextcloud/server/pull/33518 it worked just fine with our stream wrappers as long as it wasn't using `ANY_TAG`, please check if requesting `COMPUTED,GPS` instead of `ANY_TAG` works

2022-08-25 14:31 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
Tested, and it does not

2022-08-25 15:45 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
Either way we need a better solution here as this approach is unacceptable for performance

2022-08-25 15:51 UTC, felhe commented
Just adding my two cents, but the recent changes by @CarlSchwan also made the size property from the EXIF metadata available as a DAV property ([see here](https://github.com/nextcloud/server/pull/31839/files#diff-1d6ed4804160da213bc58248990a6936622ce53100a23535d207dba153f7e759)). Wouldn't it be useful to expose the GPS coordinates to the WebDAV PROPFIND as well? @CarlSchwan @icewind1991

2022-08-25 16:04 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$nativeFileDescriptorStream = fopen('php://temp', 'rw');
https://github.com/nextcloud/server/blob/master/lib/private/Preview/Movie.php#L100 yes, it's `getLocalFile($path)`

2022-08-25 16:20 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
some findings in the PHP C:
- it uses fseek() to find the size: https://github.com/php/php-src/blob/master/ext/exif/exif.c#L4409
- https://github.com/php/php-src/blob/master/ext/exif/exif.c#L3770

2022-08-25 16:23 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
@artonge is that the error you got ? https://github.com/php/php-src/blob/master/ext/exif/exif.c#L3849

I think you told me that the stream is likely returning only 8k which is usually the default for a PHP fread, even when asking to get more.

maybe we can debug into our stream code to see if there's a layer where we might limit it to 8k blocks instead of returning the full thing.

@icewind1991 do you happen to have an idea given this insight ?

2022-08-25 16:24 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
maybe test with a jpg file that doesn't contain a thumbnail because thumbnails in EXIF are likely to be bigger than 8k, and I'm guessing that other exif fields would be smaller. this could also confirm my theory

2022-08-25 21:38 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
> @artonge is that the error you got ? https://github.com/php/php-src/blob/master/ext/exif/exif.c#L3849

Looks like it yes

2022-08-25 21:47 UTC, PVince81 commented
> Just adding my two cents, but the recent changes by @CarlSchwan also made the size property from the EXIF metadata available as a DAV property ([see here](https://github.com/nextcloud/server/pull/31839/files#diff-1d6ed4804160da213bc58248990a6936622ce53100a23535d207dba153f7e759)). Wouldn't it be useful to expose the GPS coordinates to the WebDAV PROPFIND as well? @CarlSchwan @icewind1991

that's the plan already, it should be automatically exposed once it exists in the database

2022-08-26 12:27 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
@icewind1991 https://github.com/icewind1991/Streams/blob/master/README.md `Note: due to php's internal stream buffering the $count passed to the read callback will be equal to php's internal buffer size (8192 on default) an not the number of bytes requested by fopen()`

can we work around the stream buffering caching ? is it possible to disable it temporarily if it causes wrong byte counts to be returned ? "

2022-08-26 12:29 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
aha, maybe we can call this https://www.php.net/manual/en/function.stream-set-read-buffer.php with "0" before passing the stream to `exif_read_data` @artonge

2022-08-26 12:56 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
In my testing $data = exif_read_data($fileDescriptor, 'COMPUTED,GPS', true); works with local storage but not with s3 storage, will investigate further

2022-08-26 14:04 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
Issue was caused by the exif methods trying to use `fseek(0, FSEEK_END)` + `ftell` to try and get the size of the file, which fails with s3.

https://github.com/nextcloud/server/pull/33718 fixes this, with that applied `$data = exif_read_data($fileDescriptor, 'COMPUTED,GPS', true);` works as expected with s3 primary storage

2022-08-29 10:42 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
@icewind1991 great that you managed to solve it !

does it mean that in the `exif_read_data` case there will be reconections required or are we able to dodge them with your PR ?

2022-08-29 14:37 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
Currently trying to seek to the end of the file will fail which causes the "filesize detection" in the exif code to fail, with the PR seeking to the end will succeed (it will still fail if you then try to read from the end, but it just needs to do the `ftell` anyway)

2022-09-16 13:06 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +		$data = exif_read_data($nativeFileDescriptorStream, 'ANY_TAG', true);
https://github.com/nextcloud/server/pull/33718 is merged, so this should work now

2022-09-16 13:06 UTC, PVince81 commented
/rebase

2022-09-16 13:06 UTC, PVince81 commented
need to be retested / redone with the old way because now the exif extration is supposed to work as @icewind1991 said
the fix for fseek was in https://github.com/nextcloud/server/pull/33718

2022-09-30 13:46 UTC, artonge commented
Done and working as expected.

2022-10-01 13:32 UTC, icewind1991 requested changes
Seems good otherwise

2022-10-01 13:32 UTC, icewind1991 commented on apps/files/lib/Command/Scan.php
> +		$info = Filesystem::getFileInfo('/' . implode('/', $pathParts));
`$this->root->get($path)` and you can `try`/`catch` that to handle the non existing file cases

2022-10-01 13:32 UTC, icewind1991 commented on lib/private/Metadata/Provider/ExifProvider.php
> +			$data = exif_read_data($fileDescriptor, 'ANY_TAG', true);
`ANY_TAG` caused issues in my testing in the past where using `COMPUTED` worked just fine. or is this fixed with the `chunk_size` change?

2022-10-01 15:11 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +			$data = exif_read_data($fileDescriptor, 'ANY_TAG', true);
I think this is fixed by `chunk_size`, at least I don't have any issue with my testing files now. It would be awesome if you could test with yours, but I am pretty confident :).

2022-10-10 13:39 UTC, artonge commented
/backport to stable25

2022-10-10 13:40 UTC, artonge commented
@icewind1991, @PVince81, @come-nc, please review :)

2022-10-10 14:45 UTC, come-nc requested changes

2022-10-10 14:45 UTC, come-nc commented on apps/files/lib/Command/Scan.php
> +	private View $view;
Where is it used?

2022-10-10 14:45 UTC, come-nc commented on apps/files/lib/Command/Scan.php
> +use OC\Files\Node\File;
Why not `OCP\Files\File`?

2022-10-10 14:45 UTC, come-nc commented on lib/private/Metadata/FileMetadataMapper.php
> +		if ($id === null) {
```suggestion
		if ($groupName === null) {
```

2022-10-10 14:45 UTC, come-nc commented on lib/private/Metadata/FileMetadataMapper.php
> +		unset($properties['group_name']);
unset these before checking `count($properties)` maybe?

2022-10-10 14:45 UTC, come-nc commented on lib/private/Metadata/FileMetadataMapper.php
> +			$value = $entity->$getter();
There is no cleaner way?
What is in `$updated`?

2022-10-10 14:45 UTC, come-nc commented on lib/private/Metadata/Provider/ExifProvider.php
> +		}
No log, even debug?

2022-10-10 15:06 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +				'Add missing file metadata'
the answer to these questions should go in the description and/or documentation as other admins will have them :smile:

2022-10-10 15:57 UTC, artonge commented on apps/files/lib/Command/Scan.php
> +	private View $view;
Nowhere, removed :)

2022-10-10 16:29 UTC, artonge commented on lib/private/Metadata/FileMetadataMapper.php
> +		unset($properties['group_name']);
I refactored the method as it was indeed a bit confusing. It was originally a copy past from:

https://github.com/nextcloud/server/blob/1cd05a06fafcca6d115ec4e4b210704439c1ab14/lib/public/AppFramework/Db/QBMapper.php#L184-L224

I made it more specific to our needs.

2022-10-10 16:30 UTC, artonge commented on lib/private/Metadata/FileMetadataMapper.php
> +			$value = $entity->$getter();
See above comment

2022-10-10 16:35 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +		}
Right, I added a warning.

2022-10-10 16:35 UTC, artonge commented on apps/files/lib/Command/Scan.php
> +use OC\Files\Node\File;
No reason :) fixed

2022-10-11 07:17 UTC, PVince81 commented on lib/private/Metadata/Provider/ExifProvider.php
> +	private static function gpsDegreesToDecimal($coordinates, ?string $hemisphere): float {
optionally we could have stored the raw value from the metadata and compute this later on, either during location grouping and/or photos app

I assume this is reversible in case we need the original data again

2022-10-11 07:17 UTC, PVince81 approved these changes
:+1: please double check the perf bot

2022-10-11 08:22 UTC, come-nc approved these changes
Apart from small change on logger, approved

2022-10-11 08:22 UTC, come-nc commented on lib/private/Metadata/Provider/ExifProvider.php
> +			$this->logger->warning("Couldn't extract metadata for ".$file->getId(), [$ex]);
```suggestion
			$this->logger->warning("Couldn't extract metadata for ".$file->getId(), ['exception' => $ex]);
```

2022-10-11 08:27 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +			$this->logger->warning("Couldn't extract metadata for ".$file->getId(), [$ex]);
Oh, that's what `array` means

2022-10-11 08:29 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +	private static function gpsDegreesToDecimal($coordinates, ?string $hemisphere): float {
I didn't think anyone would use the original format without converting it first, so better do it here once and for all.

2022-10-11 09:41 UTC, PVince81 commented
@artonge please also make sure the new CLI args are present in the documentation

2022-10-11 12:11 UTC, merged

2023-08-02 10:47 UTC, mpivchev commented
We want to use this on iOS and Android clients to fetch location data without downloading the full res image + exif. To me it looks like this code only does the process of obtaining the info but we can't request it from client.