Fix background in login page
nextcloud/server pull request #33539
Opened 2022-08-15 09:49 UTC by CarlSchwan

- Bring background image back as it disapeared during the scsscacher deletion
- Fix background-size

2022-08-15 09:52 UTC, miaulalala approved these changes

2022-08-15 09:56 UTC, nickvergessen commented on core/css/guest.css
> +	background-image: var(--image-background, url('../img/background.png')), linear-gradient(40deg, #0082c9 0%, #30b6ff 100%);
This gradient needs to be overwritten by the theming app.

2022-08-16 06:32 UTC, skjnldsv requested changes

2022-08-16 06:32 UTC, skjnldsv commented on apps/theming/lib/Themes/DefaultTheme.php
> +			$variables["--image-$image"] = "url('".$this->imageManager->getImageUrl($image, true, $this->primaryColor)."')";
Sorry, but no.
This is a weird feature. If I select my own image as a login, I do not want this weird overlay containing apps icons

2022-08-16 06:32 UTC, skjnldsv commented on core/css/guest.css
> +	background-image: var(--image-background, url('../img/background.png')), var(--gradient-primary-background);;
You're removing features here.
The login page has three options (by order of priority):
1. the user uploaded a custom background image
2. the user disabled the background image for primary only
3. the default Nextcloud background.svg
4. Nextcloud default linear gradient

With your changes, I cannot remove the background image anymore

If I revert ba3f5337f356ac51a1b1d012c09f3e4ed6c096e3 from https://github.com/nextcloud/server/pull/33452, this works again
![Peek 16-08-2022 08-31](https://user-images.githubusercontent.com/14975046/184812917-0abc627e-ee93-4063-b947-abb33badfb5c.gif)

2022-08-16 06:42 UTC, skjnldsv commented on core/css/guest.css
> +	background-image: var(--image-background, url('../img/background.png')), var(--gradient-primary-background);;
https://github.com/nextcloud/server/pull/33452#issuecomment-1216210947

2022-08-16 06:55 UTC, skjnldsv commented
Fix in https://github.com/nextcloud/server/pull/33556
and https://github.com/nextcloud/firstrunwizard/pull/731

2022-08-16 08:12 UTC, closed without merging