Proof of concept: Redesign app-content
nextcloud/server pull request #33568
Opened 2022-08-16 22:02 UTC by CarlSchwan

![image](https://user-images.githubusercontent.com/23653902/184992982-ad6c56d8-eb3c-4ea1-a7e5-eb553ca22610.png)

2022-08-16 22:09 UTC, juliushaertl commented on core/css/apps.scss
> +    background-color: rgba(255, 255, 255, 0.8);
We should add a new variable for the main background with higher opacity

2022-08-17 11:23 UTC, jancborchardt commented on core/css/apps.scss
> +    background: url('/apps/dashboard/img/kamil-porembinski-clouds.jpg');
This path needs to be adjusted cause currently it doesn’t work if Nextcloud is in a subfolder. :)

2022-08-17 12:10 UTC, skjnldsv requested changes

2022-08-17 12:10 UTC, skjnldsv commented on core/css/apps.scss
> +    overflow-y: scroll;
Will break mobile browsers and create tons of issues.
This is a breaking point. The body needs to scroll, not the content.
This create layout, performances and ux issues

2022-08-17 13:01 UTC, CarlSchwan commented on core/css/apps.scss
> +    overflow-y: scroll;
What would you suggest instead?

2022-08-17 13:07 UTC, skjnldsv commented on core/css/apps.scss
> +    overflow-y: scroll;
Keep the body scrolling, like twitter, google, github, etc etc.
We took a hard step towards that direction a long time ago and it was already a mess to adjust all apps.

2022-08-17 13:08 UTC, skjnldsv commented on core/css/apps.scss
> +    overflow-y: scroll;
`height: calc(100vh - 50px - 8px);` especially will not work on all browsers, this will generate extra scrolling in some browsers as it will not refer to 100% of the screen size on all devices unfortunately.

Body being reactive to 100% is the only proper source of truth in reactivity

2022-08-18 08:58 UTC, jospoortvliet commented on core/css/apps.scss
> +    overflow-y: scroll;
Could we separate mobile from desktop here? The extra spacing on mobile does seem a waste of space anyhow... Just a thought...

2022-08-18 09:17 UTC, skjnldsv commented on core/css/apps.scss
> +    overflow-y: scroll;
No, this will be a nightmare to manage.
It also create performance/rendering issues on desktop, not just mobile

2022-08-18 09:25 UTC, jancborchardt commented on core/css/apps.scss
> +    overflow-y: scroll;
> Could we separate mobile from desktop here? The extra spacing on mobile does seem a waste of space anyhow... Just a thought...

Just FYI, the spec is already that on mobile, the outer margins would be reduced from 8px to 0. But the issue with scroll containers is different from what it seems like.

2022-08-18 10:16 UTC, skjnldsv commented on core/css/apps.scss
> +    overflow-y: scroll;
Yes, my point was managing different scrolls behaviour for mobile/desktop.

> No, this will be a nightmare to manage.

2022-08-26 11:40 UTC, juliushaertl commented
- [ ] BUG: Recent/share file list control header sticky position is off
- [ ] BUG: External storage file list to wide and causes horizontal scrolling
- [ ] BUG: Notification menu is missing arrow indicator (maybe already before)

2022-08-26 11:51 UTC, juliushaertl commented
- [ ] Activity: Check infinite scrolling behavior
- [ ] Profile: Add back background color on main content
- [x] Help looks fine
- [x] Settings: Look fine in general

- [ ] BUG: Theming - Take removed background image into account
- [ ] Consider positioning of toast messages
![Screenshot 2022-08-26 at 13 49 51](https://user-images.githubusercontent.com/3404133/186897147-698ae279-9292-4299-bc2a-2dd0d6aa918b.png)

2022-08-28 06:34 UTC, skjnldsv commented on apps/files/src/views/Sidebar.vue
> +				document.querySelector('#content').classList.remove('with-sidebar--full')
Oooof, Will be tricky.
Maybe we should add some kind of automated watcher in the content or something? Maybe a MutationObserver or something?
There might be people using their own Sidebar for example, not only the Files Sidebar :)

Maybe that should just be in the vue components? :thinking: 

Also, if we could, I would be up using data attributes for such targets now, like @nextcloud/cypress is doing. Something like `data-app-content`

2022-08-28 19:31 UTC, juliushaertl commented on apps/files/src/views/Sidebar.vue
> +				document.querySelector('#content').classList.remove('with-sidebar--full')
This so far seems only necessary for the files sidebar when it is displayed next to the viewer modal, which is a rather special case and we only need this as the sidebar is part of `#content`.

I'd still say a generic solution would make a lot of sense, but then we should also move the full sidebar styling to the component.

I'd split this to a separate ticket.

2022-08-28 19:32 UTC, juliushaertl commented on apps/theming/lib/Themes/DefaultTheme.php
> +		if ($appManager->isEnabledForUser('dashboard')) {
This should probably be a dedicated stylesheet that is loaded by the dashboard app or be a core user config value.

2022-08-29 16:32 UTC, jancborchardt commented
FYI @raimund-schluessler @jotoeri @tcitworld @tacruc @Rello since you are very active in the Vue components and/or in app development, it would be awesome if you can test this! :) Then we can make sure to adjust stuff that doesn’t work yet.

2022-08-29 16:53 UTC, juliushaertl commented
For further reference, the tracking issue is in https://github.com/nextcloud/server/issues/33736 and the vue components related changes in https://github.com/nextcloud/nextcloud-vue/pull/3091

2022-08-29 17:32 UTC, Rello commented
@jancborchardt thank you for the notice.
unfortunately I am still not on vue with Analytics with my components. But as e.g. recently I added drag&drop for the navigation tree/folders in my app, I am not sure if I could actually go there at all. but thank you for the reminder!

2022-08-29 17:33 UTC, juliushaertl commented
Might already be worth testing this PR with your app then, as for non-vue apps this PR should include the required container and styling changes.

2022-08-31 06:59 UTC, juliushaertl commented on apps/files/src/views/Sidebar.vue
> +				document.querySelector('#content').classList.remove('with-sidebar--full')
Added to the top list for follow ups

2022-08-31 08:26 UTC, ChristophWurst approved these changes, later dismissed
Tested with Dashboard, Calendar and Mail. Looks fine!

2022-08-31 08:26 UTC, juliushaertl commented on apps/theming/lib/Themes/DefaultTheme.php
> +		$appManager = Server::get(IAppManager::class);
Added a task to clean this up with https://github.com/nextcloud/server/pull/33733 once the customizable backgorund image is moved to core.

2022-08-31 08:53 UTC, PVince81 commented
- [ ] contrast quite low, might not pass accessibility test:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/277525/187639327-b30dfa4d-eb96-4fac-94cd-143a62a1133a.png">

2022-08-31 08:56 UTC, PVince81 commented
- [ ] BUG: rename box overlaps with the thumbnail
<img width="259" alt="image" src="https://user-images.githubusercontent.com/277525/187639750-1d40e141-2bd6-41ed-b22d-d2bd346a2fa8.png">

2022-08-31 08:59 UTC, PVince81 commented
- [ ] BUG: design: settings panel in sidebar, separation a bit too weak

<img width="183" alt="image" src="https://user-images.githubusercontent.com/277525/187640499-6ec15555-363a-4576-9a8c-1bf582bcde81.png">

2022-08-31 09:01 UTC, PVince81 commented
- [x] TEST: public link folder (+ scroll)
- [ ] TEST: public link file page
- [x] TEST: files drop page (+ scroll)

2022-08-31 09:03 UTC, PVince81 commented
- [ ] is it by design that I need to scroll down to see the file name ? if not, the image needs to be slightly reduced by default to remove the scrollbar
- [ ] BUG: public link image share, footer overlaps with scrollbar:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/277525/187641239-842b2355-cef2-42fc-929b-dc08e6b3aac1.png">

2022-08-31 09:05 UTC, PVince81 commented
- [ ] BUG: left sidebar icons not aligned vertically
<img width="309" alt="image" src="https://user-images.githubusercontent.com/277525/187641740-5b8fa591-c802-4728-b531-e0fac43bb801.png">

2022-08-31 09:08 UTC, jancborchardt commented
> is it by design that I need to scroll down to see the file name ? if not, the image needs to be slightly reduced by default to remove the scrollbar

@PVince81 the file name is in the title on the top left so I’d say that’s fine. :)

2022-08-31 09:12 UTC, PVince81 commented
- [ ] BUG: issue with horizontal resize and sidebar responsiveness in files app

![resize-sidebar-issue](https://user-images.githubusercontent.com/277525/187643108-ec671551-9b92-495a-852f-10e7628dc2e2.gif)

2022-08-31 09:22 UTC, PVince81 commented
- [ ] BUG: profile settings page layout looks broken and fields are missing
<img width="812" alt="image" src="https://user-images.githubusercontent.com/277525/187645275-d4e8e237-1c69-4ce9-8a6a-8f3491f29fe5.png">

2022-08-31 09:23 UTC, PVince81 commented
- [ ] BUG: design: settings page arrow

<img width="134" alt="image" src="https://user-images.githubusercontent.com/277525/187645499-6bc3431a-e103-486a-9401-7cc3521b556e.png">

2022-08-31 09:24 UTC, PVince81 commented
- [ ] BUG: settings page layout issues, maybe some CSS rules missing there?

<img width="624" alt="image" src="https://user-images.githubusercontent.com/277525/187645710-b167de55-bf89-41e0-94c8-fb00490a3dc3.png">

2022-08-31 09:31 UTC, PVince81 commented
error pages looks ok

<img width="432" alt="image" src="https://user-images.githubusercontent.com/277525/187647287-e7eeb56f-15f9-4d0a-86d8-aebb1832b991.png">

2022-08-31 09:33 UTC, PVince81 commented
- [ ] BUG: theme background is bleeding through at the bottom (I've changed the theme color to orange)
<img width="878" alt="image" src="https://user-images.githubusercontent.com/277525/187647539-90ef78c7-e6ea-491d-bc1c-322144c27d89.png">

2022-08-31 09:35 UTC, PVince81 commented
- [ ] BUG: apps page missing scrollbar despite more content. I guess we haven't fixed it yet ?

2022-08-31 09:39 UTC, PVince81 commented
- [ ] TEST: TOTP auth page looks fine
<img width="216" alt="image" src="https://user-images.githubusercontent.com/277525/187648753-20e35c7e-b333-4a33-b988-666cb9a472ed.png">

2022-08-31 09:41 UTC, PVince81 commented
- [ ] BUG: download button is using theme color (I guess theme will be adressed later):
<img width="223" alt="image" src="https://user-images.githubusercontent.com/277525/187649199-3778de85-c28a-43fe-8ffc-478272354f51.png">

2022-08-31 09:42 UTC, PVince81 commented
- [x] TEST: password prompt page works fine
<img width="179" alt="image" src="https://user-images.githubusercontent.com/277525/187649339-e33e2759-8a6f-4803-9dbf-be4e96ec9622.png">

2022-08-31 09:50 UTC, CarlSchwan commented
More bugs in the apps/users management: (tested with the related nextcloud-vue PR)

![image](https://user-images.githubusercontent.com/23653902/187650459-63b3498a-209f-47ed-b139-3117cdfdc9f8.png)

![image](https://user-images.githubusercontent.com/23653902/187650710-fae02c67-2474-4fe6-99df-4487f3377a74.png)

2022-08-31 11:07 UTC, ChristophWurst commented
> More bugs in the apps/users management: (tested with the related nextcloud-vue PR)

Just noticed the same. The users list doesn't scroll.

2022-08-31 12:17 UTC, ChristophWurst reviewed
User management and Mail (third column - message content) doesn't scroll. When I tested earlier it was a short messages with no scrolling :roll_eyes:

2022-08-31 12:33 UTC, tacruc commented
Just a few questions on how to test this?
So maps in the current version seams to work, but it still looks like the old stile.
I guess need to use the poc/redesign branch of vue-components? 
If this is the case? Will this components then still work in NC 25? Or Do we need a version for NC26 with the new vue-components and one vor NC25 with the old vue components?

2022-08-31 13:05 UTC, tacruc commented
- [ ] Contacts app Add new address book dialog, red boundary around submit button looks wired to me.
![image](https://user-images.githubusercontent.com/402891/187684611-bbe888b4-d9a8-4f69-af80-011522ce66e5.png)
With mouse over:
![image](https://user-images.githubusercontent.com/402891/187685195-62c0ab7b-fea7-441b-9d52-b28a1abd986c.png)

2022-08-31 16:23 UTC, juliushaertl approved these changes

2022-08-31 18:01 UTC, PVince81 commented on core/css/apps.scss
> +	opacity: 0.7px;
opacity in pixels ?!

2022-08-31 18:03 UTC, PVince81 approved these changes
:+1: see comments, not critical, to be processed separately

2022-08-31 18:24 UTC, juliushaertl commented
Seems acceptance tests fail more than expected. @danxuliu Maybe you have some time to help out as well? Otherwise I'll need to see tomorrow how to run them locally.

2022-08-31 18:36 UTC, juliushaertl commented
Pushed a quick commit including the dist bundles with the vue components lib branch, to see if that improves the acceptance test situation

2022-08-31 20:27 UTC, blizzz commented
conflicts

2022-09-01 01:59 UTC, danxuliu commented
> Seems acceptance tests fail more than expected. @danxuliu Maybe you have some time to help out as well?

Without the dist bundles it was not possible to scroll in the list of apps, which caused some of the _apps.feature_ errors (not being able to click elements out of the view).

Regarding the errors in the sharing features, with the default window size used in the acceptance tests when the navigation bar and the right side bar are both open the file list is now too narrow, so it is not possible to descend into the subfolders and that causes the tests to fail (the error does not state that clearly because it is assumed and not verified that descending was successful). The difference from the previous design is just a few pixels, but it is the difference between a very very narrow yet clickable folder name and a too narrow and unclickable folder name :shrug:

A possible solution could be to close the side bar before descending into the sub folders, or maybe to click on the folder icon rather than the name. In either case it should be a quick fix, I can try to do that "tomorrow" (but you will probably read it "today" :-P ).

Regarding the theming related errors from what I can see now the header is transparent, and therefore changing the colour in the Theming app does not change the background colour of the header. Is that correct? In that case those acceptance tests should be removed as they are no longer relevant. I can do that once confirmed.

>  Otherwise I'll need to see tomorrow how to run them locally.

For reference, `./run.sh features/XXXX.feature` in _tests/acceptance_ :-) (you will need Docker, for further details please refer to the documentation in `run.sh`).

2022-09-01 08:02 UTC, PVince81 commented
with vnc I saw that sometimes the file list looks like this, so selenium might not be able to click on the files:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/277525/187863714-c60e31f5-33c4-431f-b901-8a759c0d0cde.png">

2022-09-01 08:02 UTC, PVince81 commented
a quick fix for the latter is to add a step to close the details sidebar

2022-09-01 11:39 UTC, danxuliu commented
As agreed with @juliushaertl and @PVince81 I have replaced the commit that added a waitFor in `isVisible` with the existing `WaitFor::elementToBeEventuallyShown` in the needed places, and replaced the commit that closed the sidebar with a commit that maximies the browser window before running the tests, thus making the window wide enough to make the file name clickable without additional steps.

As I had to force push I have also moved the commit `TESTING Try to run acceptance tests against vue components pr` to the end, as I guess that it will need to be replaced with a bump of JS files or something like that.

Hopefully I did not miss anything and CI will pass now :crossed_fingers:

2022-09-01 12:30 UTC, danxuliu commented
`app-files-sharing-link.feature:14` passes when run locally, so failure should be unrelated.

2022-09-01 13:58 UTC, juliushaertl commented
Seems one additional failure at features/app-files-sharing.feature:422 but passes locally. @danxuliu Shall we also consider that unrelated?

2022-09-01 15:03 UTC, juliushaertl commented
Thanks for checking that. All other failures seem unrelated.

2022-09-01 15:03 UTC, merged

2022-09-01 15:42 UTC, juliushaertl commented on apps/files/src/views/Sidebar.vue
> +				document.querySelector('#content').classList.remove('with-sidebar--full')
Filed as https://github.com/nextcloud/nextcloud-vue/issues/3148

2022-09-01 16:51 UTC, skjnldsv commented
```
Sidebar.vue:464 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at o.setFullScreenMode (Sidebar.vue:464)
    at a.beforeOpen (Viewer.vue:449)
    at Viewer.vue:460
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at jg (Pencil.vue?12b8:19)
    at a (Pencil.vue?12b8:19)
    at Pencil.vue?12b8:19
    at new Promise (<anonymous>)
```

2022-09-01 17:39 UTC, juliushaertl commented on apps/files/js/files.js
> +		var scrollingArea = FileList.$container;
Dragging seems to be broken in general with the new scroll container - filed https://github.com/nextcloud/server/issues/33816

2022-09-01 17:40 UTC, juliushaertl commented
Filed all inline reportings with the `ui-refresh-feedback` label so we get a better overview:

https://github.com/nextcloud/server/labels/ui-refresh-feedback