Move findBinaryFinder and isFunctionEnabled away from OC_Helper
nextcloud/server pull request #33593
Opened 2022-08-18 08:58 UTC by CarlSchwan

findBinaryFinder is now a service that is still private but with some
minor optimization (remove the hasKey check).

isFunctionEnabled is now in OCP\Util

Both functions are still kept but all internal usage in nextcloud/server
were migrated to the new usage, so we can remove it in 26.

Before: 2 redis cache requests either hasKey and get or hasKey and set

![image](https://user-images.githubusercontent.com/23653902/185353984-bc22b02a-6d8d-4741-a63e-26be1b9defe8.png)

Now: 1 redis cache request (get) or 2 redis cache requests (get and set)

![image](https://user-images.githubusercontent.com/23653902/185354906-df3b35a2-808a-4ba5-84f1-108d6fe1c608.png)

2022-08-18 10:08 UTC, blizzz approved these changes

2022-08-19 10:09 UTC, nickvergessen commented on lib/private/legacy/OC_Helper.php
>  	public static function is_function_enabled($function_name) {
```suggestion
	public static function is_function_enabled(string $function_name): bool {
```

2022-08-19 10:12 UTC, nickvergessen commented on lib/private/BinaryFinder.php
> +class BinaryFinder {
OCP interface ?

2022-08-22 09:52 UTC, come-nc requested changes

2022-08-22 09:52 UTC, come-nc commented on tests/lib/LargeFileHelperGetFileSizeTest.php
> +		if (!\OC\Util::isFunctionEnabled('exec')) {
```suggestion
		if (!\OCP\Util::isFunctionEnabled('exec')) {
```

2022-08-23 11:12 UTC, ChristophWurst commented on lib/private/legacy/OC_Helper.php
> +	public static function is_function_enabled(string $function_name): booo {
:ghost:

2022-08-23 11:14 UTC, ChristophWurst approved these changes

2022-08-23 12:02 UTC, come-nc commented on lib/private/Mail/Mailer.php
> +				$sendmail = \OCP\Server::get(BinaryFinder::class)->findBinaryPath('sendmail');
```suggestion
				$sendmail = \OCP\Server::get(IBinaryFinder::class)->findBinaryPath('sendmail');
```

2022-08-23 12:03 UTC, come-nc commented on lib/private/Server.php
> +				$c->get(BinaryFinder::class)
```suggestion
				$c->get(IBinaryFinder::class)
```

2022-08-23 12:59 UTC, come-nc approved these changes

2022-08-24 07:40 UTC, nickvergessen approved these changes

2022-08-24 07:40 UTC, nickvergessen commented on lib/private/Mail/Mailer.php
> +				$sendmail = \OCP\Server::get(IBinaryFinder::class)->findBinaryPath('sendmail');
DI?

2022-08-24 08:29 UTC, CarlSchwan commented on lib/private/Mail/Mailer.php
> +				$sendmail = \OCP\Server::get(IBinaryFinder::class)->findBinaryPath('sendmail');
I tried but that involves quite a lot of change a bit everywhere

2022-08-24 11:09 UTC, merged