[WIP] Implement webdav SEARCH
nextcloud/server pull request #3360
Opened 2017-02-02 17:28 UTC by icewind1991

Still WIP, but submitting so the clients can start with it, functionality wise it should be ready for clients to start using the API

- [ ] requires https://github.com/nextcloud/3rdparty/pull/34
- [ ] needs proper test coverage

- Adds a mechanism to describe more complex search queries
- Extend the cache to support doing these searches
- Expose the new search mechanism in `\OCP\Files\Folder`
- Implement [rfc5323 SEARCH](https://tools.ietf.org/html/rfc5323) to expose this to the world

Clients can do a search by firing a SEARCH request at `nextcloud/remote.php/dav` with a search body as described by the rfc

For an example of a somewhat complex query that is possible with this api see [this example request](https://gist.github.com/icewind1991/335d0559cbefa666e7895287189879e7)

cc @mario

2017-02-08 16:56 UTC, icewind1991 commented
Fixes #3253

2017-02-15 06:51 UTC, MorrisJobke requested changes
Doesn't work:

```
$ curl -X SEARCH http://192.168.99.100/server/remote.php/dav -u admin:admin    
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this SEARCH method.</s:message>
</d:error>
```

2017-02-15 13:10 UTC, icewind1991 commented
@MorrisJobke you need to send a request body

    curl -u test:test -X SEARCH  https://localcloud.icewind.me/remote.php/dav -H "content-Type: text/xml" --data '<?xml version="1.0"?>
     <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
     <d:basicsearch>
         <d:select>
             <d:prop>
                 <oc:fileid/>
                 <d:getcontenttype/>
                 <d:getetag/>
                 <oc:size/>
             </d:prop>
         </d:select>
         <d:from>
             <d:scope>
                 <d:href>/files/test</d:href>
                 <d:depth>infinity</d:depth>
             </d:scope>
         </d:from>
         <d:where>
             <d:like>
                 <d:prop>
                     <d:getcontenttype/>
                 </d:prop>
                 <d:literal>text/%</d:literal>
             </d:like>
         </d:where>
         <d:orderby/>
     </d:basicsearch>
  </d:searchrequest>'

2017-02-15 13:16 UTC, MorrisJobke commented
I send it but it seems I forgot the text/xml header - let me retry then

2017-02-15 13:21 UTC, LukasReschke commented on apps/dav/lib/Files/FileSearchBackend.php
> +		var_dump(array_map(function (Node $node) {
expected? 😉

2017-02-15 13:28 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +		var_dump(array_map(function (Node $node) {
Leaving debug code in production saves me from having to create a debug patch in the future 😄

2017-02-15 16:09 UTC, MorrisJobke commented
If I create a folder `files/test` I only get this as answer:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>Search is only supported on directories</s:message>
</d:error>
```

2017-02-15 16:18 UTC, icewind1991 commented
@MorrisJobke can you paste the full request you made?

2017-02-15 16:37 UTC, MorrisJobke commented
```
$ curl -X SEARCH https://example.org/remote.php/dav -u admin:admin -i -H "content-Type: text/xml" --data '<?xml version="1.0"?> 
 <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
 <d:basicsearch>
     <d:select>
         <d:prop>
             <oc:fileid/>
             <d:getcontenttype/>
             <d:getetag/>
             <oc:size/>
         </d:prop>
     </d:select>
     <d:from>
         <d:scope>
             <d:href>/files/test</d:href>
             <d:depth>infinity</d:depth>
         </d:scope>
     </d:from>
     <d:where>
         <d:like>
             <d:prop>
                 <d:getcontenttype/>
             </d:prop>
             <d:literal>text/%</d:literal>
         </d:like>
     </d:where>
     <d:orderby/>
</d:basicsearch>
</d:searchrequest>'

HTTP/1.1 404 Not Found
Date: Wed, 15 Feb 2017 16:36:52 GMT
...
Content-Length: 226
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Principal with name test not found</s:message>
</d:error>
```

2017-02-15 16:40 UTC, MorrisJobke commented
<img width="834" alt="bildschirmfoto 2017-02-15 um 10 40 43" src="https://cloud.githubusercontent.com/assets/245432/22984528/3b7a49d2-f36b-11e6-9d77-89dfacadd675.png">

2017-02-17 21:59 UTC, icewind1991 commented
@MorrisJobke the `scope` paths are relative to the dav root (`remote.php/dav`), so settings the scope to `files/test` searches in the root folder of the `test` user

2017-02-20 19:04 UTC, MorrisJobke commented
> @MorrisJobke the scope paths are relative to the dav root (remote.php/dav), so settings the scope to files/test searches in the root folder of the test user

Tested and works 👍 

cc @marinofaggiana I tested it against your test setup and it works 😃

2017-02-22 01:04 UTC, MorrisJobke commented
For this body:

```xml
<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:basicsearch><d:select><d:prop><d:displayname/></d:prop></d:select><d:from><d:scope><d:href>/files/admin</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>Documents</d:literal></d:like></d:where></d:basicsearch></d:searchrequest>
```


I get following response:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>TypeError: Argument 4 passed to OC\Files\Search\SearchQuery::__construct() must be of the type array, null given, called in /var/www/nextcloud/apps/dav/lib/Files/FileSearchBackend.php on line 177</s:message>
</d:error>
```

2017-02-22 09:12 UTC, LukasReschke commented
>   <s:message>TypeError: Argument 4 passed to OC\Files\Search\SearchQuery::__construct() must be of the type array, null given, called in /var/www/nextcloud/apps/dav/lib/Files/FileSearchBackend.php on line 177</s:message>

General note: Can we avoid leaking error messages? They can sometimes contain sensitive content :)

2017-02-22 17:25 UTC, icewind1991 commented
@MorrisJobke can you retry with the updated 3rdparty

2017-02-24 06:13 UTC, MorrisJobke commented
> @MorrisJobke can you retry with the updated 3rdparty

I now get:

```xml
HTTP/1.1 207 Multi-Status

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```

😕

2017-02-24 14:13 UTC, icewind1991 commented
@MorrisJobke what is the request you're trying?

2017-02-28 05:25 UTC, MorrisJobke commented
> @MorrisJobke what is the request you're trying?

https://github.com/nextcloud/server/pull/3360#issuecomment-281534251

2017-02-28 11:38 UTC, mario commented
@icewind1991 when doing OPTIONS, search doesn't seem to be among supported methods?

2017-02-28 12:18 UTC, icewind1991 commented
Works for me:


    curl -I -X OPTIONS  -u test:test https://localcloud.icewind.me/remote.php/dav
    ...
    Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT, SEARCH

2017-02-28 12:25 UTC, mario commented
Ok will check once again.
On Tue, 28 Feb 2017 at 13:18, Robin Appelman <notifications@github.com>
wrote:

> Works for me:
>
> curl -I -X OPTIONS  -u test:test https://localcloud.icewind.me/remote.php/dav
> ...
> Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT, SEARCH
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/3360#issuecomment-283024581>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAWsubNeTyFPZjT7PiHSMFwDzucPUUKks5rhBCYgaJpZM4L1ZwO>
> .
>

2017-02-28 13:01 UTC, mario commented
@icewind1991 would something like this work with your implementation, since it doesn't look like the current libs supports that draft entirely:

 <d:searchrequest xmlns:d="DAV:" dcr:="http://www.day.com/jcr/webdav/1.0" >
    <dcr:xpath>//sv:node[@sv:name='myapp:paragraph'][1]</dcr:xpath>
 </d:searchrequest>

cc @AndyScherzinger @tobiasKaminsky 

Otherwise we might look into how we can either extend it use or use (possibly?) another lib just for this particular use case if such a thing exists.

2017-02-28 19:05 UTC, MorrisJobke commented
```
There were 4 errors:
1) Test\Files\Cache\CacheTest::testSearchByQuery
Undefined index: storage_mtime
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:168
...
```

2017-03-01 14:45 UTC, icewind1991 commented
all rebased, tests green and ready to merge from my POV

Any further polish/fixes can be added later, since this only touches existing stuff minimally it shouldn't break existing stuff.

2017-03-01 18:31 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-03-01 18:35 UTC, MorrisJobke commented
I merged 3rdparty and updated the submodule ;)

2017-03-01 18:58 UTC, mario commented
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this SEARCH method.</s:message>
</d:error>

Ideas? :)

2017-03-01 19:00 UTC, MorrisJobke commented
> Ideas? :)

How did you send it? Is the content-type header set properly? Is the body correctly formed?

2017-03-01 19:02 UTC, mario commented
<?xml version="1.0" encoding="UTF-8"?><searchrequest xmlns="DAV:"><basicsearch><select><allprop/></select><from><scope><href>/files/mario</href><depth>infinity</depth></scope></from><where><like><prop><getcontenttype/></prop><literal>text/%</literal></like></where></basicsearch></searchrequest>

2017-03-01 19:04 UTC, mario commented
Ah yes, I remember I do not see SEARCH in allowed methods. Investigating.

2017-03-01 19:24 UTC, mario commented
Ok, so two things:

- OPTIONS doesn't respond with SEARCH at all
- difference between /dav vs /webdav? Android seems to be using /webdav and that doesn't work, while /dav works.

2017-03-01 19:51 UTC, mario commented
OK so I managed to quickly hack a working basic search grammar so I think I can do this properly as well.

The two questions above still stand though, and also why isn't allprop supported?

cc @icewind1991

2017-03-01 20:14 UTC, mario commented
Options started showing SEARCH.

2017-03-01 22:30 UTC, MorrisJobke commented
> OPTIONS doesn't respond with SEARCH at all

Needs to be added by @icewind1991 




> difference between /dav vs /webdav? Android seems to be using /webdav and that doesn't work, while /dav works.

remote.php/webdav only contains the webdav of the current user. remote.php/dav contains everything and is also properly namespaced to the user. So `remote.php/webdav/abc` is for the user `admin` the same as `remote.php/dav/files/admin/abc` and for user `test` the same as `remote.php/dav/files/test/abc`. The webdav is the old way and the dav the new way also containing browsable calendar, adressbook, ... ;)

```
dav:/remote.php/dav/> ls
Listing collection `/remote.php/dav/': succeeded.
Coll:   addressbooks                           0  Dez 31  1969
Coll:   calendars                              0  Dez 31  1969
Coll:   comments                               0  Dez 31  1969
Coll:   files                                  0  Dez 31  1969
Coll:   principals                             0  Dez 31  1969
Coll:   public-calendars                       0  Dez 31  1969
Coll:   systemtags-relations                   0  Dez 31  1969
Coll:   systemtags                             0  Dez 31  1969
Coll:   uploads                                0  Dez 31  1969
```

2017-03-02 07:31 UTC, mario commented
> OPTIONS doesn't respond with SEARCH at all
> Needs to be added by @icewind1991

When using /dav it responds properly, so no worries.

2017-03-02 08:14 UTC, mario commented
Got the DAV vs WEBDAV part explained by @nickvergessen :)

2017-03-02 09:15 UTC, marinofaggiana commented
@mario i have lost several days for webdav -> dav 😱

2017-03-02 09:27 UTC, mario commented
Hehe. Took me a bit of looking at the differences between mine and Robin
query, but luckily not days hehe :)

On Thu, 2 Mar 2017 at 10:15, Marino Faggiana <notifications@github.com>
wrote:

> @mario <https://github.com/mario> i have lost several days for webdav ->
> dav 😱
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/3360#issuecomment-283598983>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAWsouTEKKtfF2cG5KjMD4qx4ElRM4Rks5rhoiygaJpZM4L1ZwO>
> .
>

2017-03-02 12:14 UTC, icewind1991 commented
> and also why isn't allprop supported?

Can add `allprop` in a follow up PR, but it shouldn't be used by the clients for search since each requested prop will add a (sometimes significant) cost to the query so only the properties that are actually needed should be requested

2017-03-02 12:15 UTC, mario commented
Right, cool @icewind1991 :)

2017-03-02 12:23 UTC, icewind1991 commented
@MorrisJobke @rullzer @LukasReschke can this be merged?

2017-03-03 02:14 UTC, MorrisJobke approved these changes

2017-03-04 15:43 UTC, marinofaggiana commented
Is changed API ??? i have a response error with my driver ...

2017-03-06 14:43 UTC, marinofaggiana commented
ping @icewind1991

2017-03-06 14:43 UTC, icewind1991 commented
@marinofaggiana please describe the error you're getting instead of having us guess

2017-03-06 14:45 UTC, marinofaggiana commented
curl -u admin:nextcloudiosapp -X SEARCH https://ios-demo.weasel.rocks/remote.php/dav -H "content-Type: text/xml" --data '<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:basicsearch><d:select><d:prop><oc:fileid/><d:getcontenttype/><d:getetag/><oc:size/><oc:favorite/></d:prop></d:select><d:from><d:scope><d:href>/files/admin</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>Nextcloud%</d:literal></d:like></d:where><d:orderby/></d:basicsearch></d:searchrequest>'

2017-03-06 14:46 UTC, marinofaggiana commented
curl -u admin:XXXXXXXX -X SEARCH https://ios-demo.weasel.rocks/remote.php/dav -H "content-Type: text/xml" --data '<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:basicsearch><d:select><d:prop><oc:fileid/><d:getcontenttype/><d:getetag/><oc:size/><oc:favorite/></d:prop></d:select><d:from><d:scope><d:href>/files/admin</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>Nextcloud%</d:literal></d:like></d:where><d:orderby/></d:basicsearch></d:searchrequest>'

2017-03-06 14:49 UTC, marinofaggiana commented
@icewind1991 this is the response :  

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this SEARCH method.</s:message>
</d:error>

2017-03-07 10:44 UTC, marinofaggiana commented
@icewind1991 @MorrisJobke please info for this issue.

2017-03-07 14:32 UTC, mario commented
So search basically works, so please +1 all of you.

After that, I just need it extended to support oc:favorite in a query because filter-files won't work for Android atm.

2017-03-07 14:47 UTC, marinofaggiana commented
@mario 
<?xml version=\"1.0\"?><oc:filter-files xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\" xmlns:nc=\"http://nextcloud.org/ns\"><oc:filter-rules><oc:favorite>1</oc:favorite></oc:filter-rules><d:prop>

2017-03-07 14:50 UTC, mario commented
@marinofaggiana using that our Android lib doesn't want to parse the propstat so I don't get the properties back.

2017-03-07 14:52 UTC, marinofaggiana commented
Modify the lib ?

2017-03-07 15:09 UTC, mario commented
Not something I feel comfortable doing under these kind of deadlines.

2017-03-08 00:03 UTC, MorrisJobke commented
Sorry - I screwed up the instance. It should work now. :( @marinofaggiana @icewind1991

2017-03-08 07:58 UTC, rullzer approved these changes

2017-03-08 12:09 UTC, merged

2018-01-15 13:28 UTC, barrydegraaff commented
@mario good work. I have been playing around with WebDAV SEARCH on nextcloud 12.0.4 and integrate it in Zimbra Nextcloud Client (https://github.com/Zimbra-Community/owncloud-zimlet)

Mostly I can make it work, but I have issues searching for files with more than 2 search words.
So I would like to search for all files that match: word1, word2 and word3. So far I can only make Nextcloud look for word1 and word2. The 3rd word is ignored. Where can I find good documentation on webdav search?

       curl -u user:password -X SEARCH https://nextcloud.example.com/nextcloud/remote.php/dav -H "content-Type: text/xml" --data '<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:basicsearch><d:select><d:prop>oc:fileid/<d:getcontentlength/><d:getlastmodified/><d:getcontenttype/><d:getetag/>oc:size/oc:favorite/</d:prop></d:select><d:from><d:scope><d:href>/files/user</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:and><d:like><d:prop><d:displayname/></d:prop><d:literal>%word1%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word2%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word3%</d:literal></d:like></d:and></d:where><d:orderby><d:order><d:prop><d:displayname/></d:prop><d:ascending/></d:order><d:order><d:prop><d:getlastmodified/></d:prop><d:ascending/></d:order></d:orderby></d:basicsearch></d:searchrequest>'
 
 
        curl -u user:password -X SEARCH https://nextcloud.domain.com/nextcloud/remote.php/dav -H "content-Type: text/xml" --data '<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:basicsearch><d:select><d:prop>oc:fileid/<d:getcontentlength/><d:getlastmodified/><d:getcontenttype/><d:getetag/>oc:size/oc:favorite/</d:prop></d:select><d:from><d:scope><d:href>/files/user</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:and><d:like><d:prop><d:displayname/></d:prop><d:literal>%word1%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word2%</d:literal></d:like></d:and></d:where><d:orderby><d:order><d:prop><d:displayname/></d:prop><d:ascending/></d:order><d:order><d:prop><d:getlastmodified/></d:prop><d:ascending/></d:order></d:orderby></d:basicsearch></d:searchrequest>'

So here only the first 2 words are matched, the 3rd is ignored... is there a limit of 2 in AND?
      <d:where><d:and><d:like><d:prop><d:displayname/></d:prop><d:literal>%word1%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word2%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word3%</d:literal></d:like></d:and></d:where>

2018-01-15 13:37 UTC, barrydegraaff commented
https://www.ietf.org/rfc/rfc5323.txt
5.7.  Boolean Operators: DAV:and, DAV:or, and DAV:not

   The DAV:and operator performs a logical AND operation on the
   expressions it contains.

Can anyone help me to do a WebDAV Search to nextcloud with more than 2 words to look for in displayname, I think the XML example, is according to the spec, but maybe I misread.

      <d:where><d:and><d:like><d:prop><d:displayname/></d:prop><d:literal>%word1%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word2%</d:literal></d:like><d:like><d:prop><d:displayname/></d:prop><d:literal>%word3%</d:literal></d:like></d:and></d:where>

2018-01-15 13:40 UTC, icewind1991 commented
How I understood the spec (and implemented it) is that DAV:and and DAV:or only take 2 arguments,
you can nest multiple and/or statements to get your desired effect

2018-01-15 13:50 UTC, barrydegraaff commented
@icewind1991 thanks, that makes it a bit harder to implement on the client side. It would be nice if the rfc said `The operator takes two arguments.` instead of `The DAV:and operator performs a logical AND operation on the expressions it contains.` I would not read 2 in that.

2018-01-15 14:05 UTC, barrydegraaff commented
@icewind1991 I am thinking about asking julian reschke (his name is on the rfc) and see what he says.

But should the server return a 501 Not Implemented error if I do something that is outside the webdav spec? Aka an AND with 3 criteria = 501. Now it parses only the first 2.

2018-01-15 14:34 UTC, reschke commented
I agree that RFC 5323 could be clearer, but AFAIR, we would have said "two" if we had intended to restrict it to two operands.

2018-01-15 20:04 UTC, icewind1991 commented
I will see if I can extend the implementation to allow for arbitrary number of arguments

2018-01-16 08:29 UTC, barrydegraaff commented
@icewind1991 thanks!

2018-01-16 11:55 UTC, rullzer commented
I just noticed this as well.

Since and is associative you can just do 

```a AND b AND c AND d```

and transform it into 

```((a AND b) AND c) AND d)```

2018-01-16 12:25 UTC, icewind1991 commented
Fix is [here](https://github.com/nextcloud/server/pull/7882)

2018-02-25 11:44 UTC, pinkylabs commented
The [example from @MorrisJobke ](https://github.com/nextcloud/server/pull/3360#issuecomment-280063038) does not work if 'where' element is omitted.

This works OK:
```
<?xml version="1.0" encoding="utf-16"?>
<searchrequest xmlns="DAV:">
  <basicsearch>
    <select>
      <prop>
        <getcontenttype />
        <getetag />
      </prop>
    </select>
    <from>
      <scope>
        <href>/files/pinky/tmp</href>
        <depth>infinity</depth>
      </scope>
    </from>
    <where>
      <like>
        <prop>
          <getcontenttype />
        </prop>
        <literal>text/%</literal>
      </like>
    </where>
  </basicsearch>
</searchrequest>
```
This fails with error 400
```
<?xml version="1.0" encoding="utf-16"?>
<searchrequest xmlns="DAV:">
  <basicsearch>
    <select>
      <prop>
        <getcontenttype />
        <getetag />
      </prop>
    </select>
    <from>
      <scope>
        <href>/files/pinky/tmp</href>
        <depth>infinity</depth>
      </scope>
    </from>
  </basicsearch>
</searchrequest>
```

As far as I understand DTD, the only mandatory elements are select and from: 
```
<!ELEMENT basicsearch   (select, from, where?, orderby?, limit?) >
```
See [section 5.2](https://tools.ietf.org/html/rfc5323#section-5.2)

2018-02-25 18:39 UTC, rullzer commented
@pinkylabs please open a new issue.