Use cached getDisplayName method
nextcloud/server pull request #33605
Opened 2022-08-18 11:47 UTC by miaulalala

instead of the current slower `$usermanager->get($user)->getDisplayName()`

Fixes #33598

2022-08-18 11:54 UTC, nickvergessen requested changes

2022-08-18 11:54 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Activity/Provider/Base.php
> +		return $this->userManager->getDisplayName($uid);
```suggestion
		return $this->userManager->getDisplayName($uid) ?? $uid;
```

2022-08-18 11:54 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			$row['displayname'] = $row['displayname'] . ' (' . $this->userManager->getDisplayName($name) . ')';
```suggestion
			$row['displayname'] = $row['displayname'] . ' (' . ($this->userManager->getDisplayName($name) ?? $uid) . ')';
```

2022-08-18 11:54 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$sender = $this->userManager->getDisplayName($this->userId);
```suggestion
			$sender = $this->userManager->getDisplayName($this->userId) ?? $this->userId;
```

2022-08-18 11:54 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$displayName = $row['displayname'] . ' (' . $this->userManager->getDisplayName($name) . ')';
```suggestion
			$displayName = $row['displayname'] . ' (' . ($this->userManager->getDisplayName($name) ?? $name) . ')';
```

2022-08-18 12:16 UTC, tcitworld reviewed
With @nickvergessen's suggestions

2022-08-18 12:16 UTC, tcitworld commented on apps/dav/lib/CalDAV/Activity/Provider/Base.php
> +	protected function getUserDisplayName(string $uid): string {
You could directly rewrite `generateUserParameter` using `userManager->getDisplayName()` and removing the `userDisplayNames` property, as it is the only use of `getUserDisplayName` (classes inheriting from `Base` do not use it either).

2022-08-23 06:49 UTC, tcitworld commented
Needs a rebase after https://github.com/nextcloud/server/pull/33615

2022-08-23 07:56 UTC, miaulalala commented
> Needs a rebase after #33615

will be done when squashing the fixups

2022-08-23 08:02 UTC, nickvergessen requested changes, later dismissed

2022-08-23 08:02 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$sender = $this->userManager->getDisplayName($this->userId) ?? $this->userId;
```suggestion
			$sender = $this->userManager->getDisplayName($this->userId);
			if ($sender !== null) {
				// getDisplayName automatically uses the uid
				// if no display-name is set
				$senderName = $sender;
			}
```

It's a weird edge case, in case the sender would not exist.
If you don't care and want to keep it simple at least the variable name needs fixing:
```suggestion
			$senderName = $this->userManager->getDisplayName($this->userId) ?? $this->userId;
```

2022-08-23 13:44 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$sender = $this->userManager->getDisplayName($this->userId) ?? $this->userId;
no it's fine, I will remove the `??` for the userId.

It will check both variables further down anyway.

2022-08-24 07:37 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$sender = $this->userManager->getDisplayName($this->userId);
```suggestion
			$senderName = $this->userManager->getDisplayName($this->userId) ?? $this->userId;
```

2022-08-25 09:10 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$sender = $this->userManager->getDisplayName($this->userId);
``getDisplayName(string $uid): ?string`` -> no guarantee that you'll get a value. The method might as well give you `null`. This will happen for unknown users.

2022-08-31 12:22 UTC, miaulalala commented
The `$senderName` variable doesn't need a check on null as it's checked again later and it will use the `$sender` if the `$senderName` is null.

2022-08-31 12:30 UTC, tcitworld commented
> The $senderName variable doesn't need a check on null as it's checked again later and it will use the $sender if the $senderName is null.

But  `$sender` is the email, not the uid. Also for the definition of `$fromName` it's not handled properly.

2022-08-31 12:41 UTC, miaulalala commented
> > The $senderName variable doesn't need a check on null as it's checked again later and it will use the $sender if the $senderName is null.
> 
> But `$sender` is the email, not the uid. Also for the definition of `$fromName` it's not handled properly.

The fallback for not having a display name is the email, yes. Which is fine in this case, that is a good way to handle not having a Display Name for the sender when it comes to emails.

Added a null check on the `$senderName` for the `$fromName`, thanks for pointing that out.

2022-08-31 13:11 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		$fromName = $l10n->t('%1$s via %2$s', [$senderName ?? $sender, $this->defaults->getName()]);
I can be convinced for `$meetingInviteeName` to use the email as default in the email body, but putting an entire email into here is very unusual.
The `From` header would look like: `someone@somewhere.org via Nextcloud Instance <noreply@nextcloud.instance>`

2022-09-05 13:38 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		$fromName = $l10n->t('%1$s via %2$s', [$senderName ?? $sender, $this->defaults->getName()]);
well I'm open for suggestions - it's better than `via Nextcloud Instance <noreply@nextcloud.instance>`, no?

2022-09-05 16:26 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		$fromName = $l10n->t('%1$s via %2$s', [$senderName ?? $sender, $this->defaults->getName()]);
Why not keep the `uid via NC Instance` behaviour?

2022-09-05 20:15 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		$fromName = $l10n->t('%1$s via %2$s', [$senderName ?? $sender, $this->defaults->getName()]);
fair point

2022-09-07 22:39 UTC, miaulalala commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			$row['displayname'] = $row['displayname'] . ' (' . $this->userManager->getDisplayName($name) ?? $name . ')';
fixed

2022-09-07 22:39 UTC, miaulalala commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$displayName = $row['displayname'] . ' (' . $this->userManager->getDisplayName($name) ?? $name . ')';
fixed

2022-09-12 15:21 UTC, nickvergessen commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			$row['displayname'] = $row['displayname'] . ' (' . ($this->userManager->getDisplayName($name) ?? $name ?? '') . ')';
```suggestion
			$row['displayname'] = $row['displayname'] . ' (' . ($this->userManager->getDisplayName($name) ?? ($name ?? '')) . ')';
```

to give clarity about the order?

2022-11-03 11:35 UTC, ChristophWurst approved these changes
Looks good

2022-11-03 12:23 UTC, nickvergessen approved these changes

2022-11-03 12:58 UTC, merged