This disables the cookie check when authorization headers are send.
nextcloud/server pull request #3361
Opened 2017-02-02 20:10 UTC by brantje

I had a really hard time detecting my redirecting errors.

Finally found them, seems that when the extension calls an endpoint (with an Authorization header set) it send the cookies with them, and no way to disable that.
Nextcloud see's the cookie's and does a check on them using `passesLaxCookieCheck` and `cookieCheckRequired`.
In my opinion the cookie check is not needed when using an Authorization header, since you already supply the credentials with it.

Really hope that this could get merged fast, since this is the major blocker for releasing the passman extension.

2017-02-02 20:22 UTC, skjnldsv submitted a review, later dismissed
I'm okay with this. 👍 

@nextcloud/security ?

2017-02-02 20:26 UTC, LukasReschke requested changes
This has a negative security impact. Please explain more detailed what problem you're facing at the moment and then we can take a closer look.

2017-02-02 20:28 UTC, skjnldsv commented
That's what I was afraid of :/
Code looks good and works, but don't know a thing about security on this side of nextcloud!
Thanks for your feedback @LukasReschke 👍

2017-02-02 20:30 UTC, brantje commented
`Please explain more detailed what problem you're facing at the moment and then we can take a closer look.`
The problem occurs when a user is logged into the nextcloud instance.
When my extension sends an `xhr` request (which uses the Authorization header) to the instance it sends the session cookie with them.
That is where it fails, and goes crazy and causes an infinite loop.

2017-02-02 21:20 UTC, brantje commented
Another side effect of placing cookies when a request is made with Authorization headers is that they are instantly logged into the Nextcloud instance with the credentials they supplied in the Authorization header.

2017-02-03 20:24 UTC, animalillo commented
I also agree that if you are using basic auth method cookies make no sense at all.
Example: a request from a "super thin" client or an specific hardware client, which will discard  your cookies because most of the time that's not worth or even feasible to handle on some hardware.
Our problem with the extension is just the tip of the trouble this can cause.

2017-02-05 21:55 UTC, brantje commented
@LukasReschke Can you update us? We really want to release the extension....

2017-02-06 11:32 UTC, tapir commented
Is there any update on the issue? What kind of negative security impact are you talking about  @LukasReschke?

2017-02-06 11:48 UTC, LukasReschke commented
>Is there any update on the issue? What kind of negative security impact are you talking about @LukasReschke?

This basically allows bypassing the Same-Site cookie check completely.

> Extension source: -removed-

This does not really encourage me to dig into this pull request 😉  – Please post at least a minimum working example of your code so that I can see what you are in detail doing here.

2017-02-06 11:51 UTC, brantje commented
At the moment source is private until we solve this.

Code for making the api request is here: https://gist.github.com/brantje/d7ef651807204c830a1c2bfcd7164359

2017-02-06 11:54 UTC, LukasReschke commented
> At the moment source is private until we solve this.

Then please provide a minimum working example of JS code that showcases the problem.  The JS code you've pasted is not what I'd consider minimal example. (e.g. not something that I can easily paste in my browser console and have it do something)

2017-02-06 11:57 UTC, brantje commented
Signup on https://git.passman.cc and i will give you access to the repo.
Creating a new extension to debug this is a waste of time, and can be done with the passman extension.

2017-02-06 12:17 UTC, brantje commented
Just found a new problem.
I've setup the extension with `UserB`.
`UserB` logs out of the nextcloud instance.
`UserA` signs on, does some things in nextcloud
Then the extension does a refresh to get new data.
Suddenly `UserA` is logged out and `UserB` is logged in.

Looks like an account take over, because nextcloud sets cookies when HTTP_AUTH is used.

2017-02-06 12:27 UTC, LukasReschke commented
> Looks like an account take over, because nextcloud sets cookies when HTTP_AUTH is used.

This is the expected behaviour as otherwise the sync clients would need to do an reauthentication action on every attempt which is not really performant and also may result in external network calls. (e.g. LDAP / …)

I don't really see any issue here. Quite frankly, Basic Auth is not the ideal candidate when it comes to authenticating. – Though at the moment it's the primary authentication mechanism but we'll have in the mid- to long-term some more token based authentications in offer.

When doing a Basic Auth you'll be issued HTTP cookies and can then either to decide to reuse those or not. If you reuse them it is however also expected that your application is properly consuming cookies. (i.e. resends all of them and not only a subset)

If you want more flexibility right now you probably want to write your own SyncControllers that can handle authentication the way you require them to be.

2017-02-06 12:27 UTC, maestroi commented
@brantje you are telling me thatlt its easy to do a crossite request forgery than 👎

2017-02-06 12:40 UTC, brantje commented
@maestroi Yes, but @LukasReschke pointed out thats 'by design'

2017-02-06 12:45 UTC, brantje commented
Source will be published when the extension is on the Chrome App store.
I'll submit it this afternoon

2017-02-07 22:35 UTC, brantje commented
@LukasReschke ivd mailed the extension source. The issue should be reproducible without passman.

2017-02-09 13:16 UTC, brantje commented
Closing, issue solved.

2017-02-09 13:16 UTC, closed without merging