Add css variables for blur background
nextcloud/server pull request #33610
Opened 2022-08-18 12:53 UTC by juliushaertl

- Add css variables for blurred background
- Move dashboard to new variables

2022-08-18 16:02 UTC, GretaD approved these changes
looks good

2022-08-18 16:47 UTC, skjnldsv commented on apps/theming/lib/Themes/DefaultTheme.php
> +			'--image-main-background' => "url('" . $this->urlGenerator->imagePath('core', 'app-background.jpg') . "')",
Can't we customize that?

2022-08-18 16:52 UTC, skjnldsv commented on apps/theming/lib/Themes/DefaultTheme.php
> +				$variables["--image-$image"] = "url('" . $imageUrl . "')";
Duplicate of the line 216, no?

2022-08-19 01:25 UTC, jancborchardt approved these changes

2022-08-19 07:12 UTC, skjnldsv requested changes
See comments

2022-08-19 08:08 UTC, juliushaertl commented on apps/theming/lib/Themes/DefaultTheme.php
> +				$variables["--image-$image"] = "url('" . $imageUrl . "')";
No, --image-main-background has a fallback to the cloud image, while the other one --image-background only represents just the theming image.

2022-08-19 08:09 UTC, juliushaertl commented on apps/theming/lib/Themes/DefaultTheme.php
> +			'--image-main-background' => "url('" . $this->urlGenerator->imagePath('core', 'app-background.jpg') . "')",
It will be overwriten further down with the theming image. Taking the customised dashboard image into account will be a follow up.

2022-08-19 08:13 UTC, skjnldsv commented on apps/theming/lib/Themes/DefaultTheme.php
> +			'--image-main-background' => "url('" . $this->urlGenerator->imagePath('core', 'app-background.jpg') . "')",
Ah right I get it now!
Could use a tad more comments :wink:

2022-08-19 08:13 UTC, skjnldsv approved these changes

2022-08-19 09:55 UTC, juliushaertl commented
/compile

2022-08-19 12:35 UTC, skjnldsv commented
Fixed tests

2022-08-19 13:30 UTC, merged