Log attempted user name on failed password reset attempts
nextcloud/server pull request #33623
Opened 2022-08-19 16:32 UTC by NoSleep82

i would be useful to know who is trying to reset the password (misspelled username or email, ex user or some sort of attack)

Signed-off-by: NoSleep82 <52562874+NoSleep82@users.noreply.github.com>

2022-08-21 09:12 UTC, skjnldsv requested changes

2022-08-21 09:12 UTC, skjnldsv commented on core/Controller/LostController.php
> +				throw new ResetPasswordException('User ' . $user . ' is disabled');
```suggestion
				throw new ResetPasswordException('User ' . $user->getUID() . ' is disabled');
```

2022-08-21 17:49 UTC, skjnldsv approved these changes

2022-08-22 09:24 UTC, blizzz approved these changes

2022-08-22 09:24 UTC, merged