Fix ETAG returned by bulk upload
nextcloud/server pull request #33659
Opened 2022-08-23 15:01 UTC by come-nc

Refresh Node object to get fresh fileinfo data after touch.
Should fix https://github.com/nextcloud/desktop/issues/4243

Problem was that $node->touch updates mtime but not etag. @icewind1991 do you know of a cleaner way to refresh the etag after calling touch?

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-08-23 15:23 UTC, artonge requested changes

2022-08-23 15:23 UTC, artonge commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +				$node = $this->userFolder->getById($node->getId());
```suggestion
					$node = $this->userFolder->getById($node->getId())[0];
```

2022-08-23 16:00 UTC, come-nc commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +				$node = $this->userFolder->getById($node->getId());
So how come it worked when @mgallien tested it :thinking:

2022-08-24 15:24 UTC, mgallien commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +				$node = $this->userFolder->getById($node->getId());
tested again on stable24 branch with bulk upload advertised in capabilities and I can confirm that it works
without `[0]` I get an exception no idea how I missed it when testing

2022-08-24 15:24 UTC, mgallien approved these changes
works fine
desktop client manages to bulk upload and receives a valid etag with this change

2022-08-25 10:11 UTC, artonge approved these changes

2022-08-25 12:14 UTC, merged