CSS changes for better distinction between user name and full name
nextcloud/server pull request #33669
Opened 2022-08-24 08:45 UTC by Jerome-Herbinet

![2022-08-24_10-39](https://user-images.githubusercontent.com/33763786/186373166-c86f4ccb-22ed-4f15-84b4-e637e614c70d.png)

Signed-off-by: Jérôme Herbinet jerome.herbinet@arawa.fr

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

2022-08-24 10:02 UTC, szaimen approved these changes
Lgtm but didn't test

2022-08-24 10:11 UTC, skjnldsv approved these changes

2022-08-24 10:46 UTC, Jerome-Herbinet commented on apps/settings/css/settings.scss
> +
I'll do it.

2022-08-24 10:55 UTC, szaimen commented on apps/settings/css/settings.scss
> +					}
Here seems to be some whitespace behind the bracket that should be removed

2022-08-24 10:56 UTC, szaimen commented on apps/settings/css/settings.scss
> +				}
Here as well?

2022-08-24 10:57 UTC, Jerome-Herbinet commented on apps/settings/css/settings.scss
> +
@szaimen I solved it, but I did have to add "Signed-off-by: ..." in my commit's description ?

2022-08-24 13:20 UTC, skjnldsv commented on apps/settings/css/settings.scss
> +
You have to sign your commits yes @Jerome-Herbinet 
Sign off your commits using `git commit -sm "Your commit message"`

2022-08-24 14:18 UTC, Jerome-Herbinet commented on apps/settings/css/settings.scss
> +					}
Done

2022-08-24 14:18 UTC, Jerome-Herbinet commented on apps/settings/css/settings.scss
> +				}
Done

2022-08-24 14:19 UTC, Jerome-Herbinet commented on apps/settings/css/settings.scss
> +
Thanks @skjnldsv ;  i've reverted my commit, and i have done a new one ... which is signed.
@szaimen it's OK

2022-08-24 14:21 UTC, Jerome-Herbinet commented
What is in the commit branch ? is this normal ? any problem ?
[3rdparty](https://github.com/nextcloud/server/pull/33669/files#diff-c16cb0249ed0e5de41d9e31fd3ca629585140a3a21b90b5ddffb467e8463d2a1)
Viewed
Submodule [3rdparty](https://github.com/nextcloud/3rdparty) updated 164 files

2022-08-24 14:22 UTC, jancborchardt requested changes
Good idea! Some design feedback:
- [ ] We never use italic cause it is not so easily legible
- [ ] Instead, we could bold the display name
- [ ] Display name should show in first row, then account name, so it doesn't look weird with a bold subline
- [ ] That variable looks non-standard, we only use either color-main-text or color-text-maxcontrast. But if we bold the display name, we don't need to reduce the color of the account name.

2022-08-24 15:15 UTC, szaimen commented
> What is in the commit branch ? is this normal ? any problem ? [3rdparty](https://github.com/nextcloud/server/pull/33669/files#diff-c16cb0249ed0e5de41d9e31fd3ca629585140a3a21b90b5ddffb467e8463d2a1) Viewed Submodule [3rdparty](https://github.com/nextcloud/3rdparty) updated 164 files

This change needs to be reverted. See https://stackoverflow.com/questions/30275691/removing-subproject-commit-from-github/30275888#30275888

2022-08-25 07:20 UTC, Jerome-Herbinet commented
> 

@szaimen I think I've removed it ; can you tell me if it's OK ?

2022-08-25 07:22 UTC, Jerome-Herbinet commented
> Good idea! Some design feedback:
> 
>     * [ ]  We never use italic cause it is not so easily legible
> 
>     * [ ]  Instead, we could bold the display name
> 
>     * [ ]  Display name should show in first row, then account name, so it doesn't look weird with a bold subline
> 
>     * [ ]  That variable looks non-standard, we only use either color-main-text or color-text-maxcontrast. But if we bold the display name, we don't need to reduce the color of the account name.

@jancborchardt thanks for your suggestions ; I'll take care of it.

2022-08-25 08:01 UTC, Jerome-Herbinet commented
* following

2022-08-25 13:10 UTC, szaimen commented on .gitmodules
> -	url = https://github.com/nextcloud/3rdparty.git
hm... seems like following my link removed too much :/

@skjnldsv do you know how to fix that?

2022-08-25 13:11 UTC, szaimen commented
@Jerome-Herbinet thanks! Can you please post a new screenshot? That would be great!

2022-08-25 13:30 UTC, Jerome-Herbinet commented
> @Jerome-Herbinet thanks! Can you please post a new screenshot? That would be great!

@szaimen here it is :
![2022-08-25_15-29](https://user-images.githubusercontent.com/33763786/186677972-a9baf415-837f-4371-9f65-68c4d4884ca2.png)

2022-08-25 13:31 UTC, szaimen commented
cc @jancborchardt

2022-08-25 15:23 UTC, jancborchardt commented
@Jerome-Herbinet almost :) could you:
- Unbold the account name, as the display name is already bold
- Put display name in the first line, accoint in the second (not soo important if difficult)

2022-08-25 15:27 UTC, skjnldsv commented on .gitmodules
> -	url = https://github.com/nextcloud/3rdparty.git
Nope :(

2022-08-25 15:39 UTC, Jerome-Herbinet commented on .gitmodules
> -	url = https://github.com/nextcloud/3rdparty.git
@StCyr une idée ?

2022-08-25 16:17 UTC, Jerome-Herbinet commented
> @Jerome-Herbinet almost :) could you:
> 
>     * Unbold the account name, as the display name is already bold
> 
>     * Put display name in the first line, accoint in the second (not soo important if difficult)

@jancborchardt in fact the text isn't bold ; the other screenshot boldness is certainly due to the default font of my Ubuntu Laptop.

Here is a screenshot of the same NC instance, under Manjaro. 

![scr](https://user-images.githubusercontent.com/33763786/186710584-16ff02b3-83ea-433f-98de-f7b4114d375d.jpg)

So do you want me to bold something ?

And about putting the display name in first position, I won't be able to do it my self (sorry).

2022-08-25 16:48 UTC, jancborchardt commented
@Jerome-Herbinet ah got it, thanks for the screenshot! Then I'd only say it would be nice to bold the display name (best use a `<strong>` tag for semantic markup).

2022-08-26 08:11 UTC, Jerome-Herbinet commented
> @Jerome-Herbinet ah got it, thanks for the screenshot! Then I'd only say it would be nice to bold the display name (best use a `\<strong\>` tag for semantic markup).

Done @jancborchardt 
![2022-08-25_15-29](https://user-images.githubusercontent.com/33763786/186854952-21e369d0-c795-4b88-8a5f-dc70b90c3568.png)
Display name is bold ... event if on my "day" computer, difference between bold and not bold texte isn't very visible ... (with "strong") and display name and user name are inverted now.

2022-08-26 08:16 UTC, Jerome-Herbinet commented
As a newbie as code contributor, I made an error, by committing [5f9962d](https://github.com/Jerome-Herbinet/server/commit/5f9962d427863f635a4d1d2ac93e1a884e3d8808) ... I think I've cancelled it, can you confirm ? (sorry for the mess, I'm learning).

2022-08-26 08:17 UTC, Jerome-Herbinet commented
I'm concerned about submodule problem ; do you have a tip to solve it ?

2022-09-20 13:26 UTC, Jerome-Herbinet commented
Hello,
If the Submodule problem is not solvable, do you advise me to close this PR and to create a new one (hopping that it will work better) ?

2022-09-20 13:28 UTC, szaimen commented
> If the Submodule problem is not solvable, do you advise me to close this PR and to create a new one (hopping that it will work better) ?

Yesy that is probably a good idea. Thanks!

2022-09-20 13:34 UTC, Jerome-Herbinet commented
> > If the Submodule problem is not solvable, do you advise me to close this PR and to create a new one (hopping that it will work better) ?
> 
> Yesy that is probably a good idea. Thanks!

OK @szaimen, I close it and tell you when the new PR is created (I'll cross the fingers).

2022-09-20 13:34 UTC, closed without merging