Improve bulk upload and add a config switch for it
nextcloud/server pull request #33697
Opened 2022-08-25 12:48 UTC by come-nc

Fix https://github.com/nextcloud/server/issues/33691

2022-08-25 13:12 UTC, szaimen commented on apps/dav/lib/Capabilities.php
> +		if ($this->config->getSystemValueBool('bulkupload.enabled', false)) {
hm... I think the idea was to enable it by default.

cc @PVince81

2022-08-25 13:44 UTC, come-nc commented on apps/dav/lib/Capabilities.php
> +		if ($this->config->getSystemValueBool('bulkupload.enabled', false)) {
Yeah but it needs to be confirmed working first :-P

2022-08-25 13:52 UTC, CarlSchwan approved these changes

2022-08-25 13:53 UTC, PVince81 commented on apps/dav/lib/Capabilities.php
> +		if ($this->config->getSystemValueBool('bulkupload.enabled', false)) {
I think you can set it to true at least for master, if we're optimistic :smile: 

we can then delay the backports until proven stable

2022-08-26 12:45 UTC, mgallien requested changes

2022-08-26 12:45 UTC, mgallien commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +					"permissions" => $node->getPermissions(),
this gives the numerical value as stored in filecache table instead of the text form that is expected by the desktop client

2022-08-26 12:47 UTC, mgallien commented
matching pull request on desktop client side https://github.com/nextcloud/desktop/pull/4869

2022-08-26 13:18 UTC, PVince81 commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +					"fileid" => $node->getId(),
yeah, the file id exposed specifically for clients is not the true one, it's a computed value. The latter is only used by clients.

@come-nc you need to use `$node->getFileId()` instead (a bit unfortunate that the two methods have similar name)

2022-08-29 06:56 UTC, PVince81 commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +					"permissions" => $node->getPermissions(),
yeah, like with fileid there's a specific format for clients. use `$node->getDavPermissions()` instead

2022-08-29 07:34 UTC, come-nc commented on apps/dav/lib/BulkUpload/BulkUploadPlugin.php
> +					"fileid" => $node->getId(),
It appears both getFileId and getDavPermissions are methods of `OCA\DAV\Connector\Sabre\Node` and not `OCP\Files\Node`.
What is the correct way for getting a `OCA\DAV\Connector\Sabre\Node` instance?

2022-08-29 12:53 UTC, mgallien approved these changes
thanks
works nicely

2022-08-29 14:44 UTC, come-nc commented
Remaining test failure unrelated.

2022-08-29 16:30 UTC, CarlSchwan commented on lib/public/Util.php
> +	public static function getDavFileId(int $id): string {
I prefer to have that in a DavUtil class to not put too much stuff in the already big Util class

2022-08-30 10:22 UTC, merged