Fix for Win Clients sometimes not connecting
nextcloud/server pull request #3370
Opened 2017-02-03 22:51 UTC by Flole998

Fix for Win Clients sometimes not connecting We discovered this during investigation of Issue #2887

2017-02-06 11:58 UTC, LukasReschke commented
So with "Win Client" you refer to Windows Explorer, correct?

2017-02-06 14:10 UTC, Flole998 commented
Yes, I am refering to Windows Explorer.

2017-02-07 23:39 UTC, MorrisJobke commented
@Flole998 Could you try this one here: https://github.com/nextcloud/server/pull/2986

2017-02-07 23:50 UTC, MorrisJobke commented
@michag86 Could you try this one for your windows clients?

2017-02-10 14:37 UTC, michag86 commented
Works 👍

2017-02-10 20:18 UTC, MorrisJobke requested changes

2017-02-10 20:18 UTC, MorrisJobke commented on .htaccess
> +  RewriteRule ^$         /remote.php/webdav/          [L,R=302]
This only works for the root directory and if the RewriteBase is set. Please add this to https://github.com/nextcloud/server/blob/d548329543b6cbda2686a8523e163c8a87b2ab09/lib/private/Setup.php#L448-L448 and remove the leading `/` before `remote.php` to be compatible with sub folders. Then this is good to go in

2017-02-10 20:28 UTC, michag86 commented on .htaccess
> +  RewriteRule ^$         /remote.php/webdav/          [L,R=302]
In my case RewriteBase was not in use and ist works.

And it's only required for the root directory. If Nextcloud ist installed in a sub directory, the problem does not occour.

2017-02-10 21:13 UTC, MorrisJobke commented on .htaccess
> +  RewriteRule ^$         /remote.php/webdav/          [L,R=302]
> And it's only required for the root directory. If Nextcloud ist installed in a sub directory, the problem does not occour.

But we would redirect to /remote.php/webdav/ instead of ´/sub/remote.php/webdav/`... even if it is never requested like this it could cause huge headaches.

@lukasreschke @nickvergessen Opinions of introducing a rewrite condition that works and fixes a problem if installed in root, but creates a redirect to "outside of nextcloud" for the sub directory install, but there it is never requested by Windows anyways. (I tested this and it works)

2017-02-10 21:13 UTC, MorrisJobke approved these changes

2017-02-10 21:19 UTC, michag86 commented on .htaccess
> +  RewriteRule ^$         /remote.php/webdav/          [L,R=302]
If Nextcloud ist installed in a sub directory, the "RewriteRule ^$" in the .htaccess of the sub directory will do nothing. Or am I wrong?

2017-02-10 21:58 UTC, MorrisJobke commented on .htaccess
> +  RewriteRule ^$         /remote.php/webdav/          [L,R=302]
> If Nextcloud ist installed in a sub directory, the "RewriteRule ^$" in the .htaccess of the sub directory will do nothing. Or am I wrong?
 
It does, because it get's only the stuff handed in within it's subdirectory. And then it redirect to the root (because of the leading slash in `/remote.php/dav`). Therefore I tested this with windows and it doesn't request the subdirectory.

2017-02-17 03:14 UTC, MorrisJobke commented
@rullzer @nickvergessen @icewind1991 @schiessle @LukasReschke Please review this one

2017-02-17 03:14 UTC, MorrisJobke commented
> Works 👍

@LukasReschke I would merge this one, because @michag86 also tested this.

2017-03-01 19:06 UTC, MorrisJobke approved these changes

2017-03-01 19:07 UTC, merged

2017-03-02 11:22 UTC, chises commented
i am sorry but both fixes (.htaccess and lib/base.php) are not working for me. since OC 11.0.1 i got the issue that Windows Explorer asks 3 times for a username and Password
Apache Access logs:

> 10.10.10.1 - - [02/Mar/2017:12:21:21 +0100] "OPTIONS /remote.php/webdav HTTP/1.1" 401 4479 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"
> 10.10.10.1 - - [02/Mar/2017:12:21:21 +0100] "OPTIONS / HTTP/1.1" 200 3489 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"
> 10.10.10.1 - - [02/Mar/2017:12:21:21 +0100] "PROPFIND /remote.php/webdav HTTP/1.1" 401 1563 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"
> 10.10.10.1 - - [02/Mar/2017:12:21:24 +0100] "OPTIONS /remote.php/webdav HTTP/1.1" 401 4477 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"
> 10.10.10.1 -user [02/Mar/2017:12:21:24 +0100] "OPTIONS /remote.php/webdav HTTP/1.1" 503 1161 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"
>

2017-03-02 11:30 UTC, Flole998 commented
401 means unauthorized. It doesnt recognize your password. However, not related to this. Open a new issue please, however I do not think it is an issue. Also this is for nextcloud, I will assume that OC was just a typo. If your issue is really an owncloud issue, this is clearly the wrong place.

2017-03-02 20:08 UTC, chises commented
i am sorry, OC was a typo.
i try to find the issue myself. if i stuck i will create a new issue :) TY so far