showUpdate funciton allows updated messages
nextcloud/server pull request #3371
Opened 2017-02-04 05:53 UTC by m3ntalsp00n

Updates the "reloading page in 5 seconds" to countdown then reload - addresses issue #3354

2017-02-07 21:34 UTC, MorrisJobke commented on core/js/js.js
> +     					}
Indentation of (same with 2 lines above).

2017-02-07 21:38 UTC, MorrisJobke commented on core/js/js.js
> +						OC.Notification.showUpdate(t('core', 'Problem loading page, reloading in ' + (seconds - timer) + ' seconds'));
Pleas use `n()` instead of `t()` for proper l10n. This then looks like this: `n('core', 'Problem loading page, reloading in %n second', 'Problem loading page, reloading in %n seconds', seconds - timer)`

2017-02-07 21:38 UTC, MorrisJobke requested changes
See my inline comments

2017-02-07 21:39 UTC, MorrisJobke commented
Once they are addressed this is good to go in. 👍

2017-02-08 06:48 UTC, m3ntalsp00n commented on core/js/js.js
> +     					}
Omg, i hate tabs :)

2017-02-08 06:48 UTC, m3ntalsp00n commented on core/js/js.js
> +						OC.Notification.showUpdate(t('core', 'Problem loading page, reloading in ' + (seconds - timer) + ' seconds'));
Nifty 👍

2017-02-09 02:46 UTC, MorrisJobke commented
The sign-off for your commit is missing 😉 Please check out https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

Thanks

2017-02-09 02:50 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-02-10 13:47 UTC, blizzz approved these changes

2017-02-10 13:47 UTC, merged