Move app menu to vue
nextcloud/server pull request #33728
Opened 2022-08-28 19:25 UTC by juliushaertl

Move app menu to vue in preparation for further adjustments of #33568

2022-08-28 19:40 UTC, juliushaertl commented on core/src/components/AppMenu.vue
> +	overflow: hidden;
This cuts off the app title at the first/last item

2022-08-29 10:54 UTC, CarlSchwan commented
The focus frame is now touching the border of the header, causing some contrast issue since there is no clear separation between the focus frame and outside the focus frame.

![image](https://user-images.githubusercontent.com/23653902/187185193-89ee74b8-666f-42ca-95bb-21a0a2647842.png)

2022-08-29 11:00 UTC, szaimen commented
@juliushaertl would it be possible to add an API for re-ordering the apps or hiding some of them? I am thinking about the apporder app that will probably break after this PR...

2022-08-29 16:47 UTC, juliushaertl commented
> @juliushaertl would it be possible to add an API for re-ordering the apps or hiding some of them? I am thinking about the apporder app that will probably break after this PR...

Possible yes, but not planned yet. There is some long discussion about this in https://github.com/nextcloud/server/issues/4917

2022-08-29 17:26 UTC, juliushaertl commented
@CarlSchwan Addressed :)

2022-08-30 10:30 UTC, artonge commented on core/src/components/AppMenu.vue
> +		window.addEventListener('resize', this.resize)
FYI, there is a "new" [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) interface to detect size change on a specific object.

But `addEventListener` works in this case, so feel free to ignore.

2022-08-30 20:06 UTC, juliushaertl commented on core/src/components/AppMenu.vue
> +		window.addEventListener('resize', this.resize)
Switched over as that may cover cases where the container gets resized during loading if not all right side menu entries are rendered in time (even through not likely).

2022-08-31 06:27 UTC, artonge approved these changes

2022-08-31 06:43 UTC, skjnldsv approved these changes

2022-08-31 08:21 UTC, ChristophWurst approved these changes

2022-08-31 09:46 UTC, PVince81 commented
there are JS test failures related to snap/snapper that need to be adjusted
maybe we changed the width?

2022-08-31 11:08 UTC, juliushaertl commented
Thanks @danxuliu ❤️

2022-08-31 11:52 UTC, jancborchardt requested changes
Some details:
- [x] The active indicator is a bit low down, would be nice if it’s visually inbetween the icon and the content. Just a few px further up :)
- [ ] With a light background selected from the Dashboard, is the same logic of making the header bar icons dark, so they are visible?
- [ ] As per the video, the focus effect is still overlapping the text, or is the vid outdated, as in @CarlSchwan’s comment it also looked different?

2022-08-31 12:24 UTC, juliushaertl commented
>  With a light background selected from the Dashboard, is the same logic of making the header bar icons dark, so they are visible?

Something we can do once the background image is a global option: https://github.com/nextcloud/server/pull/33733

> As per the video, the focus effect is still overlapping the text, or is the vid outdated, as in @CarlSchwan’s comment it also looked different?

I didn't touch that yet, to first get the major change in, still tracked as open in https://github.com/nextcloud/server/issues/33741

> The active indicator is a bit low down, would be nice if it’s visually inbetween the icon and the content. Just a few px further up :)

Will adjust.

2022-08-31 12:39 UTC, juliushaertl commented
<img width="930" alt="Screenshot 2022-08-31 at 14 39 17" src="https://user-images.githubusercontent.com/3404133/187680328-baf36d16-495e-4350-9d2f-725378048ad0.png">

@jancborchardt

2022-08-31 12:42 UTC, szaimen commented on core/src/init.js
> +const breakpointMobileWidth = 1024
not sure about this... yet another place where we need to maintain this number...

2022-08-31 13:14 UTC, jancborchardt approved these changes
Looks super nice! :)

2022-08-31 13:20 UTC, CarlSchwan approved these changes

2022-08-31 14:16 UTC, juliushaertl commented
Failure unrelated

2022-08-31 14:17 UTC, merged