File widget for references
nextcloud/server pull request #33755
Opened 2022-08-30 13:19 UTC by juliushaertl

2022-09-01 13:44 UTC, eneiluj reviewed
Awesome. Some little remarks.

Also, how do we register a ReferenceProvider? I suppose there is an extra `registerReferenceProvider` to `IRegistrationContext`, right?

2022-09-01 13:44 UTC, eneiluj commented on apps/files/src/reference-files.js
> +/*
```suggestion
/**
```

2022-09-01 13:44 UTC, eneiluj commented on apps/files/src/views/ReferenceFileWidget.vue
> +	},
As this component will probably be taken as example by developers, maybe we should include the `richObjectType` prop here even if it's not used. It would help to see this prop's type at least :grin:.

2022-09-01 17:49 UTC, juliushaertl commented
> Also, how do we register a ReferenceProvider? I suppose there is an extra registerReferenceProvider to IRegistrationContext, right?

Yes :)

2022-09-01 17:50 UTC, juliushaertl commented on apps/files/src/views/ReferenceFileWidget.vue
> +	},
Will write a quick example doc to add that :)

2022-09-01 18:08 UTC, juliushaertl commented
I've split the event out to get it in separately. https://github.com/nextcloud/server/pull/33818

2022-09-02 08:34 UTC, eneiluj approved these changes
:tada:

2023-03-01 10:39 UTC, marcelklehr approved these changes
:elephant:

2023-03-01 11:57 UTC, julien-nc requested changes
The dialog appears with padding in the picker modal:
![image](https://user-images.githubusercontent.com/11291457/222132596-06be605b-3811-4e79-b1a2-2e6dbb3ccd0f.png)
I guess this can be partially solved in this implementation but would also maybe require adjustments in the picker implementation.

Also there are 2 close buttons, one from the picker, one from the dialog. We could hide the one from the dialog IMO.

2023-03-01 11:57 UTC, julien-nc commented on apps/files/src/views/FileReferencePickerElement.vue
> +				'Select file or folder to link to',
Translation?

2023-03-01 11:57 UTC, julien-nc commented on apps/files/src/views/ReferenceFileWidget.vue
> +.widget-file {
This could have `flex-grow: 1;`
This is how it looks for me in Text:
![image](https://user-images.githubusercontent.com/11291457/222131536-8285f923-f860-4a76-9230-dfcb22ec1c72.png)
and in Talk:
![image](https://user-images.githubusercontent.com/11291457/222131635-6e65098b-3797-4e8c-97a2-c4e47a6aae2e.png)

2023-03-02 08:58 UTC, juliushaertl commented on apps/files/src/views/ReferenceFileWidget.vue
> +.widget-file {
Difference in text is fixed with https://github.com/nextcloud/text/pull/3856

2023-03-02 10:10 UTC, julien-nc commented
@juliushaertl It seems that `dist/files-reference-files.js` is not included in your commits.
If I compile it locally, it loads but then the widget and custom picker are not registered and I get
`[link picker] files reference provider is discoverable but does not have any related search provider or custom picker component registered` in the browser console log.

2023-03-02 12:58 UTC, julien-nc approved these changes
Awesome!

2023-03-02 21:15 UTC, juliushaertl commented
Failures unrelated

2023-03-02 21:15 UTC, merged