Set focus to input field for login form
nextcloud/server pull request #34050
Opened 2022-09-13 12:54 UTC by kesselb

- [x] Needs https://github.com/nextcloud/nextcloud-vue/pull/3240

Fix:

TypeError: this.$refs.user.focus is not a function
TypeError: this.$refs.password.focus is not a function

Fixes https://github.com/nextcloud/server/issues/34077

2022-09-13 12:59 UTC, CarlSchwan approved these changes

2022-09-13 13:12 UTC, raimund-schluessler commented on core/src/components/login/LoginForm.vue
> +			this.$refs.user.$refs.inputField.$refs.input.focus()
This targets an `NcInputField` which has no inputField ref.
```suggestion
			this.$refs.user.$refs.input.focus()
```

2022-09-13 13:13 UTC, raimund-schluessler requested changes
See https://github.com/nextcloud/server/pull/34050/files#r969609424

2022-09-13 13:15 UTC, raimund-schluessler commented on core/src/components/login/LoginForm.vue
> +			this.$refs.user.$refs.inputField.$refs.input.focus()
Sorry, nevermind, it targets an `NcTextField` which of course has an inputField ref. So all good.

2022-09-13 13:15 UTC, raimund-schluessler approved these changes

2022-09-13 13:17 UTC, kesselb commented on core/src/components/login/LoginForm.vue
> +			this.$refs.user.$refs.inputField.$refs.input.focus()
Thanks for your review :+1:

2022-09-13 16:28 UTC, kesselb commented
Carl suggested to use the `autofocus` attribute. 

Pull Request for component library (to forward autofocus attribute): https://github.com/nextcloud/nextcloud-vue/pull/3245

I suggest to still merge this pull request and migrate to autofocus attribute as follow up.

2022-09-15 20:00 UTC, PVince81 commented
conflict :-/

2022-09-15 20:30 UTC, kesselb commented
Recompiled to fix the conflicts :ghost:

2022-09-16 06:09 UTC, tobiasKaminsky commented
Works from client/UI side 👍

2022-09-16 06:27 UTC, PVince81 commented
@kesselb recompiling is not enough. You need to rebase first... (I made the same mistake recently...)

2022-09-16 08:52 UTC, kesselb commented
Thanks for heads up :+1: 

https://github.com/nextcloud/server/pull/33512 changed core-common.js so another rebase and recompile is necessary :v: 

Should be good now. Let's hope nothing else is merged in the meantime :sunglasses:

2022-09-16 09:49 UTC, merged

2022-11-18 08:07 UTC, szaimen commented
@skjnldsv can we revert this after https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.1.0-beta.1?