[stable11] Make sure ownCloud 8.2 activities also can get displayed
nextcloud/server pull request #3412
Opened 2017-02-09 11:18 UTC by nickvergessen

Backport #3394 

@LukasReschke @MorrisJobke

2017-02-09 13:44 UTC, LukasReschke requested changes
Tests seem to fail?

2017-02-09 13:55 UTC, nickvergessen commented
Yes, a new test was added and it assumed 2 backports were there.
Added them now

2017-02-10 07:35 UTC, MorrisJobke approved these changes
Tested and still works 👍

2017-02-10 09:43 UTC, LukasReschke approved these changes

2017-02-10 09:44 UTC, merged