Move theming images to AppData
nextcloud/server pull request #3413
Opened 2017-02-09 11:21 UTC by juliushaertl

Since we have a dedicated app data folder there is no need to store theming files directly in the data folder any more. 

Fixes https://github.com/nextcloud/server/issues/1725

2017-02-09 12:15 UTC, nickvergessen requested changes

2017-02-09 12:15 UTC, nickvergessen commented on apps/theming/lib/Controller/ThemingController.php
> +	 * @return Http\FileDisplayResponse|NotFoundResponse
Please fully import the class name

2017-02-09 12:15 UTC, nickvergessen commented on apps/theming/tests/Controller/ThemingControllerTest.php
> +		$this->appData = $this->getMockBuilder('OCP\Files\IAppData')->getMock();
`$this->appData = $this->createMock(\OCP\Files\IAppData::class);`
Same for the other cases

2017-02-09 12:15 UTC, nickvergessen commented
Looks good otherwise

2017-02-09 16:15 UTC, juliushaertl commented
@nickvergessen Thanks for the comments. Changes are pushed. :)

2017-02-09 16:30 UTC, nickvergessen commented on apps/theming/tests/Controller/ThemingControllerTest.php
>  			->getMock();
Also replace all calls to `getMockBuilder()` with calls to `createMock()`
It also automatically calls `->disableOriginalConstructor()->getMock()`

2017-02-10 09:42 UTC, juliushaertl commented
@nickvergessen Fixed as well, I've restarted the drone build, since it was only the mysqlmb4 build that looked like it has timed out somehow.

2017-02-13 22:04 UTC, LukasReschke requested changes

2017-02-13 22:04 UTC, LukasReschke commented on apps/theming/lib/Controller/ThemingController.php
> +			$folder = $this->appData->newFolder('images');
This line doesn't seem to be covered by a test :)

2017-02-16 14:14 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			$folder = $this->appData->newFolder('images');
Those are now covered as well. :)

2017-02-16 14:15 UTC, juliushaertl commented
@nickvergessen @LukasReschke Thanks for your comments. Fixes have been pushed. :wink:

2017-02-20 14:26 UTC, nickvergessen approved these changes
Works

2017-02-20 14:49 UTC, juliushaertl commented
I've just pushed the last commit again with the missing signoff message.

2017-02-22 09:16 UTC, LukasReschke approved these changes

2017-02-22 09:16 UTC, merged

2017-02-22 09:16 UTC, LukasReschke commented
🚀