Fixed exception thrown when logging in as an LDAP user due to a direc…
nextcloud/server pull request #34141
Opened 2022-09-19 16:34 UTC by Adambean

Fixed exception thrown when logging in as an LDAP user due to a directory not having password policy attributes available.

https://github.com/nextcloud/server/issues/33622

Signed-off-by: Adam Reece <adam@reece.wales>

2022-10-13 16:01 UTC, Adambean commented on apps/user_ldap/lib/User/User.php
> +			if (is_null($result) || !is_array($result) || empty($result[0]) || !is_array($result[0])) {
Check is wrong. This variable being null as a result of the LDAP search is precisely the cause of the bug. A null check needs to happen here.

2022-12-19 15:35 UTC, come-nc requested changes

2022-12-19 15:35 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			if (is_null($result) || !is_array($result) || empty($result[0]) || !is_array($result[0])) {
Are you sure it is null and not false?
I’m pretty sure it can never be null.

Also, if you do not have ppolicy you should leave "Default password policy DN" empty and this code will never run.

2022-12-19 19:15 UTC, Adambean commented on apps/user_ldap/lib/User/User.php
> +			if (is_null($result) || !is_array($result) || empty($result[0]) || !is_array($result[0])) {
Hello,

Just checked again on OC 25.0.2. `$result` is an empty array, which would be why my additional checks (is not an array, or 1st element unset, or 1st element is not an array) trap the problem before the 1st element of the (expected to be) array is accessed.

2023-02-11 20:50 UTC, bash2121 commented
Hello,
I have this bug and i have resolv this issue with your help. Thank you.
All works for existing account.
But now, when i create new account in my ldap, i have this error

Exception: array_key_exists(): Argument https://github.com/nextcloud/server/pull/2 ($array) must be of type array, null given in file '/var/www/html/nextcloud/do.do.fr/apps/user_ldap/lib/User/User.php' line 653

And i request error when i try login.
Can you help me please.

2023-02-12 00:00 UTC, Adambean commented
> Hello, I have this bug and i have resolv this issue with your help. Thank you. All works for existing account. But now, when i create new account in my ldap, i have this error
> 
> Exception: array_key_exists(): Argument #2 ($array) must be of type array, null given in file '/var/www/html/nextcloud/do.do.fr/apps/user_ldap/lib/User/User.php' line 653
> 
> And i request error when i try login. Can you help me please.

You already asked that in the issue. Your comment isn't directly related to this pull request.

2024-02-24 11:41 UTC, closed without merging