Create a checksum of the config file in memory
nextcloud/server pull request #34146
Opened 2022-09-19 19:15 UTC by m4t3uz

This fixes a massive performance bug when opcache is enabled.

Signed-off-by: Mateus de Lima Oliveira <mateus@ativarsoft.com>

2022-09-21 16:37 UTC, kesselb commented
As reference: https://github.com/nextcloud/server/pull/34099

Thanks for creating a new version of your pull request :+1: 

Our usual workflow is that pull request target master as branch. 
If necessary a patch is backported to the stable* branches (if possible by a bot). 

Please don't forget to add the logging output (as requsted in the old pull request) to figure out what the **actual** issue is. The configuration file is only rewritten (and the opcache cleared) when a change is detected:

https://github.com/nextcloud/server/blob/c2dafb099781a31745749ae399cf864b2a195000/lib/private/Config.php#L158-L164

2022-09-21 16:37 UTC, kesselb requested changes
Target branch: master

2022-09-21 16:50 UTC, m4t3uz commented
@kesselb

The log is empty, Daniel.

2022-09-21 16:54 UTC, kesselb commented
Hey, when you change the target branch you may need to rebase your pull request. Right now all commits from stable24 which are not in master are also referenced.

2022-09-21 17:59 UTC, m4t3uz commented
@kesselb, I have no idea how to resolve those rebase conflicts.

2022-09-21 18:16 UTC, kesselb commented
It depends a bit on your local setup.

When people are working with a fork they usually add another remote "upstream".

`git remote add upstream git@github.com:nextcloud/server.git`

Then run `git fetch upstream`. 

Afterwards rebase your local branch with the upstream changes `git rebase -i upstream/master`. 

GitHub documentation: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks

2022-12-19 08:30 UTC, come-nc requested changes

2022-12-19 08:30 UTC, come-nc commented on lib/private/Config.php
> +		if ($this->getLastChecksum() == $currentChecksum)
This will never be true, the checksum computed from file use the whole file content while the current one use only the data.

2023-03-09 11:27 UTC, blizzz commented
Any reason this PR is against stable24? Do we have a equivalent for master?

2023-03-09 11:44 UTC, closed without merging

2023-03-09 11:45 UTC, kesselb commented
Closing the pull request due to inactivity.