Make sure the instance is in maintenance mode before reseting opcache…
nextcloud/server pull request #34143
Opened 2022-09-19 18:05 UTC by m4t3uz

opcache_reset was being called when there is an update available but the user has not upgraded yet so the instance gets awfully slow if it can be upgraded somehow. This patch ensures that the instance is in maintenance mode. It means that the administrator of the instance is expecting and wants an upgrade.

2022-11-04 16:40 UTC, PVince81 approved these changes
:+1: makes sense

2022-11-07 08:55 UTC, come-nc commented on lib/base.php
>  				if (!((bool) $systemConfig->getValue('maintenance', false))) {
Am I reading that wrong or is that if the instance is *NOT* in maintenance mode?

2022-11-07 09:23 UTC, artonge commented on lib/base.php
>  				if (!((bool) $systemConfig->getValue('maintenance', false))) {
!false === true
I think it is correct

2022-11-07 09:24 UTC, artonge commented on lib/base.php
>  				if (!((bool) $systemConfig->getValue('maintenance', false))) {
Hmm, I think you are right

2022-11-07 14:09 UTC, come-nc requested changes
![explain](https://user-images.githubusercontent.com/91878298/200330690-5edbfa9b-1670-41cc-87b1-659b7a323fb9.gif)

2022-11-07 14:11 UTC, come-nc commented
No offense intended @ativarsoft , I realize the gif looks a bit agressive. Was supposed to be funny.

The question is do you agree the if says the opposite of your PR description?
Did you test your PR and is it having a positive effect for you?
Is the code wrong or the description, or am I wrong?

2022-11-08 04:30 UTC, ativarsoft commented
The code and the description are both correct and I've been running that code for a while now without any problems. I changed it before the last update on stable so this code is proven to work. I should have written my description more clearly. Sorry.

2023-03-09 11:28 UTC, blizzz commented
Any reason this PR is against stable24? Do we have a equivalent for master?

2023-06-22 09:51 UTC, blizzz commented
closing for inactivity

2023-06-22 09:51 UTC, closed without merging