Rename users to account or person
nextcloud/server pull request #34178
Opened 2022-09-21 15:45 UTC by PVince81

Replace translated texts in comments, files_sharing, core and lib.

Missing to be clarified:
--- ./lib/l10n/de.json ---
Sharing %s failed, because this item is already shared with user %s
--- ./core/l10n/de.json ---
Error opening the user status modal, try hard refreshing the page

@jancborchardt ideas ?

2022-09-21 17:12 UTC, PVince81 commented
I've fixed the unit tests locally, I'll push after I see the acceptance test results... some rely on texts/labels sometimes

2022-09-21 18:43 UTC, PVince81 commented
this is getting complicated because the users page is using some core strings so I'd need to replace some of them

and in https://github.com/nextcloud/server/pull/34179 replace the rest.

so, let's do this: I'll merge https://github.com/nextcloud/server/pull/34179 into this PR and fix the tests at once

2022-09-21 19:17 UTC, PVince81 commented
I've pushed even more renames here

2022-09-21 19:18 UTC, PVince81 commented
/compile amend /

2022-09-22 07:32 UTC, PVince81 commented
as it's a bit late considering the string freeze and also the fact that other apps need adjusting as well, let's not merge this for 25.0.0 but 25.0.1 could do

this would give us time also to properly review all the strings that were replaced and see how they look like in context

2022-10-19 15:30 UTC, PVince81 commented
@jancborchardt I rechecked and it seems the only place where "User status" is visible is for admins as it's the name of the app that can be disabled. And it appears in few debug messages, but that's all. Should we leave it as is ?

2022-10-19 15:40 UTC, PVince81 commented
Rebased and renamed "User documentation" to "Usage documentation"

2022-10-21 13:38 UTC, PVince81 commented
rebased and recompiled

@jancborchardt would be good if you could review.
you should also be able to test this locally

2023-01-26 17:35 UTC, jancborchardt approved these changes
Sorry for late review, thought I had already approved. Looks good to me! :)

2023-01-26 17:36 UTC, jancborchardt commented
@Pytal maybe a review from a native speaker? :)

2023-01-27 09:33 UTC, nickvergessen commented
There is no way this will merge :P 
Either should have happened right away, or now be split in smaller chunks

2023-03-18 21:55 UTC, PVince81 commented
someone should take over if this is still of interest

2023-04-25 12:17 UTC, AndyScherzinger commented
/compile amend /

2023-04-25 14:41 UTC, skjnldsv requested changes

2023-04-25 14:41 UTC, skjnldsv commented on apps/encryption/templates/settings-admin.php
> +					<?php p($l->t("The recovery key is an extra encryption key that is used to encrypt files. It allows the recovery of an account's files in case its password was forgotten.")) ?>
```suggestion
					<?php p($l->t("The recovery key is an additional encryption key used to encrypt files. It is used to recover files from an account if the password is forgotten.")) ?>
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +			$message_t = $this->l->t('Sharing %1$s failed, because this item is already shared with account %2$s', [$share->getNode()->getName(), $shareWith]);
```suggestion
			$message_t = $this->l->t('Sharing %1$s failed, because this item is already shared with the account %2$s', [$share->getNode()->getName(), $shareWith]);
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/js/statusmanager.js
> +			placeholder_username: t('files_external', 'Account name'),
```suggestion
			placeholder_username: t('files_external', 'Login'),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Command/Notify.php
> +				$output->writeln('<error>Account name and/or password required</error>');
```suggestion
				$output->writeln('<error>Login and/or password required</error>');
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/OpenStack/OpenStackV2.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/OpenStack/OpenStackV3.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/OpenStack/Rackspace.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/Password/Password.php
> +			->setText($l->t('Account name and password'))
```suggestion
			->setText($l->t('Login and password'))
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/Password/Password.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/Password/UserProvided.php
> +				(new DefinitionParameter('user', $l->t('Account name')))
```suggestion
				(new DefinitionParameter('user', $l->t('Login')))
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Auth/PublicKey/RSAPrivateKey.php
> +				new DefinitionParameter('user', $l->t('Account name')),
```suggestion
				new DefinitionParameter('user', $l->t('Login')),
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Backend/SMB_OC.php
> +				(new DefinitionParameter('username_as_share', $l->t('Account name as share')))
```suggestion
				(new DefinitionParameter('username_as_share', $l->t('Login as share')))
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/lib/Lib/Storage/Swift.php
> +			throw new StorageBadConfigException("API Key or password, Account name, Bucket and Region have to be configured.");
```suggestion
			throw new StorageBadConfigException("API Key or password, Login, Bucket and Region have to be configured.");
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_external/templates/settings.php
> +			   placeholder="<?php p($l->t('Account name')) ?>"/>
```suggestion
			   placeholder="<?php p($l->t('Login')) ?>"/>
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +				throw new OCSNotFoundException($this->l->t('Please specify a valid person to share with'));
```suggestion
				throw new OCSNotFoundException($this->l->t('Please specify a valid account to share with'));
```

2023-04-25 14:41 UTC, skjnldsv commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						:aria-label="t('settings', 'Edit account')"
I think it make sense

2023-04-25 14:41 UTC, skjnldsv commented on core/Command/Maintenance/Install.php
> +			->addOption('database-user', null, InputOption::VALUE_REQUIRED, 'Account name to connect to the database')
```suggestion
			->addOption('database-user', null, InputOption::VALUE_REQUIRED, 'Login to connect to the database')
```

2023-04-25 14:41 UTC, skjnldsv commented on core/Command/Maintenance/Install.php
> +			->addOption('admin-user', null, InputOption::VALUE_REQUIRED, 'Account name of the admin account', 'admin')
```suggestion
			->addOption('admin-user', null, InputOption::VALUE_REQUIRED, 'Login of the admin account', 'admin')
```

2023-04-25 14:41 UTC, skjnldsv commented on core/Command/User/Add.php
> +				'Account name used in the web UI (can contain any characters)'
```suggestion
				'Login used in the web UI (can contain any characters)'
```

2023-04-25 14:41 UTC, skjnldsv commented on core/Command/User/AddAppPassword.php
> +				'Account name to add app password for'
```suggestion
				'Login to add app password for'
```

2023-04-25 14:41 UTC, skjnldsv commented on core/Command/User/ResetPassword.php
> +				'Account name to reset password'
```suggestion
				'Login to reset password'
```

2023-04-25 14:41 UTC, skjnldsv commented on core/src/components/login/LoginForm.vue
> +				return t('core', 'Wrong account name or password.')
```suggestion
				return t('core', 'Wrong login or password.')
```

2023-04-25 14:41 UTC, skjnldsv commented on core/src/components/login/PasswordLessLoginForm.vue
> +				<label for="user" class="infield">{{ t('core', 'Account name or email') }}</label>
```suggestion
				<label for="user" class="infield">{{ t('core', 'Login or email') }}</label>
```

2023-04-25 14:41 UTC, skjnldsv commented on core/src/components/login/PasswordLessLoginForm.vue
> +					:aria-label="t('core', 'Account name or email')"
```suggestion
					:placeholder="t('core', 'Login or email')"
					:aria-label="t('core', 'Login or email')"
```

2023-04-25 14:41 UTC, skjnldsv commented on core/templates/installation.php
> +			<label for="adminlogin"><?php p($l->t('Account name')); ?></label>
```suggestion
			<label for="adminlogin"><?php p($l->t('Login')); ?></label>
```

2023-04-25 14:41 UTC, skjnldsv commented on core/templates/loginflow/authpicker.php
> +			<label for="user" class="infield"><?php p($l->t('Account name')) ?></label>
```suggestion
			<input type="text" name="user" id="user" placeholder="<?php p($l->t('Login')) ?>">
			<label for="user" class="infield"><?php p($l->t('Login')) ?></label>
```

2023-04-25 14:41 UTC, skjnldsv commented on core/templates/loginflowv2/authpicker.php
> +			<label for="user" class="infield"><?php p($l->t('Account name')) ?></label>
```suggestion
			<input type="text" name="user" id="user" placeholder="<?php p($l->t('Login')) ?>">
			<label for="user" class="infield"><?php p($l->t('Login')) ?></label>
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup.php
> +			$error[] = $l->t('Set an admin account name.');
```suggestion
			$error[] = $l->t('Set an admin login.');
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/AbstractDatabase.php
> +			$errors[] = $this->trans->t("Enter the database account name and name for %s", [$this->dbprettyname]);
```suggestion
			$errors[] = $this->trans->t("Enter the database login and name for %s", [$this->dbprettyname]);
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/AbstractDatabase.php
> +			$errors[] = $this->trans->t("Enter the database account name for %s", [$this->dbprettyname]);
```suggestion
			$errors[] = $this->trans->t("Enter the database login for %s", [$this->dbprettyname]);
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/MySQL.php
> +			throw new \OC\DatabaseSetupException($this->trans->t('MySQL account name and/or password not valid'),
```suggestion
			throw new \OC\DatabaseSetupException($this->trans->t('MySQL login and/or password not valid'),
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/OCI.php
> +			$errors[] = $this->trans->t("Enter the database account name and name for %s", [$this->dbprettyname]);
```suggestion
			$errors[] = $this->trans->t("Enter the database login and name for %s", [$this->dbprettyname]);
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/OCI.php
> +			$errors[] = $this->trans->t("Enter the database account name for %s", [$this->dbprettyname]);
```suggestion
			$errors[] = $this->trans->t("Enter the database login for %s", [$this->dbprettyname]);
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/OCI.php
> +			throw new \OC\DatabaseSetupException($this->trans->t('Oracle account name and/or password not valid'),
```suggestion
			throw new \OC\DatabaseSetupException($this->trans->t('Oracle login and/or password not valid'),
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/Setup/PostgreSQL.php
> +			throw new \OC\DatabaseSetupException($this->trans->t('PostgreSQL account name and/or password not valid'),
```suggestion
			throw new \OC\DatabaseSetupException($this->trans->t('PostgreSQL login and/or password not valid'),
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException($l->t('The account name is already being used'));
```suggestion
			throw new \InvalidArgumentException($l->t('This login is already in use'));
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException($l->t('Only the following characters are allowed in an account name:'
```suggestion
			throw new \InvalidArgumentException($l->t('Only the following characters are allowed in a login:'
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException($l->t('A valid account name must be provided'));
```suggestion
			throw new \InvalidArgumentException($l->t('A valid login must be provided'));
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException($l->t('Account name must not consist of dots only'));
```suggestion
			throw new \InvalidArgumentException($l->t('The login must not consist of dots only'));
```

2023-04-25 14:41 UTC, skjnldsv commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException($l->t('Account name is invalid because files already exist for this user'));
```suggestion
			throw new \InvalidArgumentException($l->t('An account with files already exists for this login'));
```

2023-04-25 14:41 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/LoginPageContext.php
> +		return Locator::forThe()->xpath("//*[@class = 'input-field__helper-text-message input-field__helper-text-message--error' and normalize-space() = 'Wrong account name or password.']")->
```suggestion
		return Locator::forThe()->xpath("//*[@class = 'input-field__helper-text-message input-field__helper-text-message--error' and normalize-space() = 'Wrong login or password.']")->
```

2023-04-25 14:41 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/SettingsContext.php
> +				describedAs("Allow account name autocompletion to accounts within the same groups checkbox in Sharing section in Administration Sharing Settings");
```suggestion
				describedAs("Allow login autocompletion to accounts within the same groups checkbox in Sharing section in Administration Sharing Settings");
```

2023-04-25 14:41 UTC, skjnldsv commented on tests/acceptance/features/bootstrap/SettingsContext.php
> +				describedAs("Allow account name autocompletion to accounts within the same groups checkbox input in Sharing section in Administration Sharing Settings");
```suggestion
		return Locator::forThe()->checkbox("Allow login autocompletion to accounts within the same groups")->
				describedAs("Allow login autocompletion to accounts within the same groups checkbox input in Sharing section in Administration Sharing Settings");
```

2023-04-25 14:43 UTC, skjnldsv commented
```
1) OC\Core\Controller\OCSControllerTest::testGetIdentityProofWithNotExistingUser
440 | Failed asserting that two objects are equal.
441 | --- Expected
442 | +++ Actual
443 | @@ @@
444 | OCP\AppFramework\Http\DataResponse Object (
445 | 'data' => Array (
446 | -        0 => 'User not found'
447 | +        0 => 'Account not found'
448 | )
449 | 'headers' => Array (...)
450 | 'cookies' => Array ()
451 |  
452 | /drone/src/tests/Core/Controller/OCSControllerTest.php:200
```

2023-04-26 12:41 UTC, AndyScherzinger commented on apps/files_external/js/statusmanager.js
> +			placeholder_username: t('files_external', 'Account name'),
Woudn't login === credentials rather than the * name ?

2023-04-26 12:44 UTC, AndyScherzinger commented on apps/settings/src/components/UserList/UserRowSimple.vue
> +						:aria-label="t('settings', 'Edit account')"
Yeah, according to Jan we should always to have the First word upper cased, all the others should follow the actual casing from the language, not influenced by the fact that it is a heading.

2023-04-26 12:46 UTC, skjnldsv commented on apps/files_external/js/statusmanager.js
> +			placeholder_username: t('files_external', 'Account name'),
Yes, isn't it what it is about?

2023-04-26 20:50 UTC, AndyScherzinger commented
Just came to my mind @skjnldsv is this PR even merge-able in anyway since all those changes would need to be backported so a single commit will always fail hard and is impossible to manually resolve/redo, no?

2023-04-27 05:42 UTC, skjnldsv commented
> a single commit will always fail hard and is impossible to manually resolve/redo, no?

Hard to tell, sometimes it's alright, sometimes not.
A manual cherry pick would allow you to use any mergetool and resolve conflicts one by one (while the rest of the changes works)

2023-05-02 14:37 UTC, skjnldsv commented on apps/files_external/js/statusmanager.js
> +			placeholder_username: t('files_external', 'Account name'),
This is external storage configs :)
`Login name` then

2023-05-22 08:58 UTC, ChristophWurst approved these changes
changes in dav look good

2023-05-23 08:40 UTC, skjnldsv approved these changes

2024-01-18 20:30 UTC, ArtificialOwl commented on apps/files/lib/Activity/Provider.php
> +			$subject = str_replace('{user}', $this->activityLang->t('"remote person"'), $subject);
why not _'remote account'_ ?

2024-01-18 20:30 UTC, ArtificialOwl commented on apps/files_sharing/appinfo/info.xml
> +		This application enables people to share files within Nextcloud. If enabled, the admin can choose which groups can share files. The applicable people can then share files and folders with other peo
in some places, _shares_ are mentioned related to `'accounts and groups'` while in few other places, to `'people and groups'`

2024-01-18 20:30 UTC, ArtificialOwl approved these changes

2024-01-18 20:59 UTC, AndyScherzinger commented
/compile /

2024-01-18 21:01 UTC, AndyScherzinger commented on apps/files/lib/Activity/Provider.php
> +			$subject = str_replace('{user}', $this->activityLang->t('"remote person"'), $subject);
@jancborchardt for feedback

2024-01-18 21:01 UTC, AndyScherzinger commented on apps/files_sharing/appinfo/info.xml
> +		This application enables people to share files within Nextcloud. If enabled, the admin can choose which groups can share files. The applicable people can then share files and folders with other peo
@jancborchardt for feedback

2024-02-13 17:19 UTC, AndyScherzinger approved these changes

2024-02-13 20:28 UTC, merged