Expose clearing the profiles and fix it
nextcloud/server pull request #34188
Opened 2022-09-22 10:36 UTC by CarlSchwan

2022-09-22 11:52 UTC, CarlSchwan commented
/backport to stable25

2022-09-22 12:20 UTC, juliushaertl approved these changes

2022-10-03 14:29 UTC, icewind1991 requested changes

2022-10-10 11:27 UTC, CarlSchwan commented on lib/private/Profiler/FileProfilerStorage.php
> +			if (is_file((string)$file)) {
fixed

2022-10-14 15:08 UTC, icewind1991 approved these changes

2022-10-14 15:35 UTC, merged

2022-10-14 15:35 UTC, CarlSchwan commented
/backport to stable25