Don't run cron.php for 14min but only 4
nextcloud/server pull request #34266
Opened 2022-09-26 16:12 UTC by marcelklehr

Apparently cron.php runs for 14min but is called every 5 minutes.
Is there a reason for the discrepancy?

Original issue: https://github.com/nextcloud/recognize/issues/335

2022-09-26 16:22 UTC, nickvergessen commented
> Is there a reason for the discrepancy?

Yes, on bigger instances it often happens that one execution in parallel is not enough, so we use this to run ~3 in parallel.

2022-09-26 16:22 UTC, nickvergessen requested changes
This is intended

2022-09-26 18:29 UTC, nickvergessen commented
> On smaller instances it can create high load, though

How so? if there are no jobs, nothing is being done?

2022-11-17 14:08 UTC, marcelklehr commented
>> On smaller instances it can create high load, though
> How so? if there are no jobs, nothing is being done?

I meant small as in a Raspberry Pi for example. People running nextcloud on there may not have the resources to run 3 cron jobs in parallel.

2022-11-18 07:33 UTC, juliushaertl commented
> Yes, on bigger instances it often happens that one execution in parallel is not enough, so we use this to run ~3 in parallel.

Shouldn't we rather recommend to setup multiple cron jobs then? That way admins stay in control on how many parallel processes are running and can adapt that to the available resources.

2023-01-11 08:40 UTC, kc9jud commented
Alternatively, this "maximum number of simultaneous cron jobs" should be configurable.

2023-01-11 08:53 UTC, kc9jud commented
> Yes, on bigger instances it often happens that one execution in parallel is not enough, so we use this to run ~3 in parallel.

@nickvergessen On one end we have "resource-constrained systems which can only handle a single simultaneous execution". On the opposite end of the spectrum where there are "resource-rich systems with lots of available cores/parallelism" and "large instances where one execution is not enough". I don't think "`cron.php` takes longer than 5 minutes" actually gives you enough information to distinguish between the two scenarios, so some configuration flag (either in Nextcloud itself or via scheduling multiple cron jobs) is needed.

2023-07-27 11:58 UTC, closed without merging