Url encode the web dav url for copying
nextcloud/server pull request #34289
Opened 2022-09-27 11:47 UTC by miaulalala

2022-09-27 11:47 UTC, miaulalala commented
/backport to stable25

2022-09-27 11:47 UTC, miaulalala commented
/backport to stable24

2022-09-27 11:48 UTC, miaulalala commented
/backport to stable23

2022-09-27 11:48 UTC, miaulalala commented
/backport to stable22

2022-09-27 11:51 UTC, nickvergessen requested changes

2022-09-27 11:51 UTC, nickvergessen commented on apps/files/templates/appnavigation.php
> +				   value="<?php p(urlencode($_['webdav_url'])); ?>"/>
You actually want to urlencode the parameter being added into route

2022-09-27 11:55 UTC, szaimen reviewed
also a test would be good, I guess

2022-09-27 12:04 UTC, nickvergessen commented on apps/files/lib/Controller/ViewController.php
> +		$nav->assign('webdav_url', \OCP\Util::linkToRemote('dav/files/' . urlencode($user)));
```suggestion
		$nav->assign('webdav_url', \OCP\Util::linkToRemote('dav/files/' . rawurlencode($user)));
```

I think? Always forget which one was better

2022-09-27 13:13 UTC, miaulalala commented on apps/files/lib/Controller/ViewController.php
> +		$nav->assign('webdav_url', \OCP\Util::linkToRemote('dav/files/' . urlencode($user)));
I think rawurlencode:

[If you are encoding path segment, use rawurlencode().
If you are encoding query component, use urlencode().](https://www.gyrocode.com/articles/php-urlencode-vs-rawurlencode/)

2022-09-27 13:15 UTC, szaimen reviewed
@miaulalala can you add a teste for this?

2022-09-27 14:28 UTC, nickvergessen approved these changes

2022-09-28 13:05 UTC, PVince81 approved these changes
:+1:

2022-09-28 13:05 UTC, PVince81 commented
@miaulalala please squash

2022-10-02 08:36 UTC, miaulalala commented
/rebase

2022-10-02 10:11 UTC, skjnldsv approved these changes

2022-10-02 12:28 UTC, merged