Use color preset of shipped background as primary color
nextcloud/server pull request #34298
Opened 2022-09-28 02:43 UTC by Pytal

Auto-refreshing the new primary color requires https://github.com/nextcloud/server/pull/34204

2022-09-28 02:50 UTC, Pytal commented on apps/theming/lib/ThemingDefaults.php
> +			return BackgroundService::SHIPPED_BACKGROUNDS['kamil-porembinski-clouds.jpg']['primary_color'];
Went ahead and used the accesible `#00639a` instead of `#0082c9` here as well if `$color` doesn't match the regex, good with you @jancborchardt?

2022-09-28 08:28 UTC, blizzz commented
master is still 26, please trigger a backport if necessary

2022-09-28 13:51 UTC, blizzz commented
Also CI is unhappy

2022-09-28 18:36 UTC, szaimen commented
/backport to stable25

2022-09-28 18:37 UTC, szaimen commented
Conflicts

2022-09-28 19:19 UTC, jancborchardt commented on apps/theming/lib/ThemingDefaults.php
> +			return BackgroundService::SHIPPED_BACKGROUNDS['kamil-porembinski-clouds.jpg']['primary_color'];
Where is that color used? Cause while for button backgrounds and heading texts, we should use the accessible shade – if it's for full backgrounds or header backgrounds, we should use our brand color.

2022-09-28 19:32 UTC, Pytal commented on apps/theming/lib/ThemingDefaults.php
> +			return BackgroundService::SHIPPED_BACKGROUNDS['kamil-porembinski-clouds.jpg']['primary_color'];
This specific line is just a fallback for when the theming color from the DB is not a valid HEX color code

The full background (including header) was initially using the accessible primary color as well but will adjust that here to use the brand color instead specifically for the full background

2022-09-28 21:14 UTC, szaimen requested changes
seems to work mostly but there seem to be some bug to happen when you change your personal theming and visit the admin theming. the primary color is then set to the one of the personal color although it should still be the default Nextcloud color IIRC
See 
![image](https://user-images.githubusercontent.com/42591237/192889994-167521e8-ba66-44e8-bfb1-944aa7746b69.png)

2022-09-29 02:01 UTC, Pytal commented
> seems to work mostly but there seem to be some bug to happen when you change your personal theming and visit the admin theming. the primary color is then set to the one of the personal color although it should still be the default Nextcloud color IIRC

Expected for now as the purpose of this PR is to use the shipped background color preset and the larger feature that splits admin and user theming will be done as the pieces fall into place

2022-09-29 07:30 UTC, szaimen commented
> Expected for now as the purpose of this PR is to use the shipped background color preset and the larger feature that splits admin and user theming will be done as the pieces fall into place

Fine by me as long as the issue gets addressed in a follow up 👍

2022-09-29 07:31 UTC, szaimen approved these changes

2022-10-01 16:30 UTC, st3iny approved these changes
Very nice!

Idea for a followup: Make it work with custom images too.

2022-10-01 16:34 UTC, szaimen commented
Please fix the tests, if green we green we can merge

2022-10-03 15:40 UTC, jancborchardt approved these changes

2022-10-03 19:08 UTC, blizzz commented
/rebase

2022-10-03 19:08 UTC, blizzz commented
pretty sure it needs CI fixes nevertheless

2022-10-04 08:31 UTC, szaimen commented
@Pytal can you please fix the CI?

2022-10-04 23:59 UTC, szaimen commented
Only one test to go!

2022-10-05 07:47 UTC, skjnldsv approved these changes
Works ! :rocket:

2022-10-05 07:52 UTC, merged