Disable sharing calendars via link when sharik via link is disabled
nextcloud/server pull request #34372
Opened 2022-10-01 21:46 UTC by pboguslawski

This mod disallows sharing calendars via link when `shareapi_allow_links` is disabled.

Related: https://github.com/nextcloud/calendar/issues/525
Related: https://github.com/nextcloud/calendar/issues/4399
Author-Change-Id: IB#1126264
Signed-off-by: Pawel Boguslawski <pawel.boguslawski@ib.pl>

2022-10-01 22:58 UTC, miaulalala requested changes

2022-10-01 22:58 UTC, miaulalala commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			throw new NotFound('Node with name \'' . $uri . '\' could not be found');
Please use an exception that reflects what is happening: `\Sabre\DAV\Exception\Forbidden` would be a better exception to use here.

2022-10-01 22:58 UTC, miaulalala commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		// Sharing via link must be enabled.
```suggestion
		// Sharing via link is allowed by default, but if the option is set it should be checked.
```

2022-10-01 22:58 UTC, miaulalala commented
Thanks for your PR!  A couple small change requests only :)

2022-10-02 09:04 UTC, tcitworld requested changes

2022-10-02 09:04 UTC, tcitworld commented on apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
> +			// Sharing via link must be enabled.
It might be better to just avoid registering the SabreDAV plugin altogether when the feature is disabled:
https://github.com/nextcloud/server/blob/905753be42af7e8c5af304b0d3c93f5d9bcea789/apps/dav/lib/Server.php#L184-L187

Otherwise you would need to avoid exposing the plugin features as well.
https://github.com/nextcloud/server/blob/905753be42af7e8c5af304b0d3c93f5d9bcea789/apps/dav/lib/CalDAV/Publishing/PublishPlugin.php#L86-L89
https://github.com/nextcloud/server/blob/905753be42af7e8c5af304b0d3c93f5d9bcea789/apps/dav/lib/CalDAV/Publishing/PublishPlugin.php#L138

2022-10-02 12:48 UTC, miaulalala commented on apps/dav/lib/CalDAV/CalDavBackend.php
>  	public function getPublicCalendars() {
Let's deprecate it then please @tcitworld

2022-10-02 13:53 UTC, tcitworld commented on apps/dav/lib/CalDAV/CalDavBackend.php
>  	public function getPublicCalendars() {
Well as it's still being used in the tests we can refactor them remove it altogether. Even though the method is public it's kind of a private API, and I don't seem to find anywhere it's been used anyway.

2022-10-14 11:20 UTC, pboguslawski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +			throw new NotFound('Node with name \'' . $uri . '\' could not be found');
Fixed in bfd8c622d99f24d7769db39b095ce00176e6da8a.

2022-10-14 11:21 UTC, pboguslawski commented on apps/dav/lib/CalDAV/CalDavBackend.php
>  	public function getPublicCalendars() {
Fixed in bfd8c622d99f24d7769db39b095ce00176e6da8a.

2022-10-14 11:21 UTC, pboguslawski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		if ($this->config->getAppValue('core', 'shareapi_allow_links', 'yes') === 'no' ) {
Fixed in bfd8c622d99f24d7769db39b095ce00176e6da8a.

2022-10-14 11:21 UTC, pboguslawski commented on apps/dav/lib/CalDAV/Publishing/PublishPlugin.php
> +			// Sharing via link must be enabled.
Fixed in bfd8c622d99f24d7769db39b095ce00176e6da8a.

2022-10-14 11:38 UTC, tcitworld approved these changes

2022-10-14 13:31 UTC, ChristophWurst approved these changes

2022-10-28 16:55 UTC, pboguslawski commented
Current solution (unregistering plugin) does [not work correctly](https://github.com/nextcloud/calendar/pull/4572#issuecomment-1295231692) so please hold with merging until final solution is proposed.

2022-10-28 18:12 UTC, tcitworld commented
@pboguslawski That's correct, thanks for checking! Sadly the AllowedSharingModes didn't fallback as I planned when the plugin was unregistered, so I made #34873 to extract exposing this information into it's own plugin. That should do it, please have a go and test.

2022-10-29 09:25 UTC, pboguslawski commented
Replaced with https://github.com/nextcloud/server/pull/34873.

2022-10-29 09:25 UTC, closed without merging