Added parameter to disallow calendar subscription via link
nextcloud/server pull request #34387
Opened 2022-10-02 14:40 UTC by pboguslawski

Added calendar application config parameter `allow_subscribe_link` to disallow calendar subscription via link (i.e. for internal Nextcloud setups). Use

```
occ config:app:set calendar allow_subscribe_link --value 'yes'
```

to allow (default if not set) and

```
occ config:app:set calendar allow_subscribe_link --value 'no'
```

to disallow calendar subscription via link.

Author-Change-Id: IB#1126265
Signed-off-by: Pawel Boguslawski <pawel.boguslawski@ib.pl>

2022-10-02 14:50 UTC, tcitworld requested changes

2022-10-02 14:50 UTC, tcitworld commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +		if ($this->config->getAppValue('calendar', 'allow_subscribe_link', 'yes') === 'no') {
This should be directly disabled through not registering the plugin here: 
https://github.com/nextcloud/server/blob/754cef369b694c5a58f006ceafe7e9a943c7770f/apps/dav/lib/Server.php#L180

2022-10-28 14:02 UTC, tcitworld commented on apps/dav/lib/Server.php
> +			if (\OC::$server->getConfig()->getAppValue('calendar', 'allow_subscribe_link', 'yes') === 'yes') {
```suggestion
			if (\OC::$server->getConfig()->getAppValue('dav', 'allow_subscribe_link', 'yes') === 'yes') {
```
Makes more sense in the `dav` app. Needs https://github.com/nextcloud/calendar/pull/4573 to be adjusted too.

2022-10-28 14:29 UTC, tcitworld commented on apps/dav/lib/Server.php
> +			if (\OC::$server->getConfig()->getAppValue('calendar', 'allow_subscribe_link', 'yes') === 'yes') {
The calendar app is only a CalDAV client, settings in this app should only concern UI stuff. You can use subscriptions without the calendar app (for instance with DAVx5).

To make things clear from other dav stuff I suggest you rename `allow_subscribe_link` in `allow_calendar_subscriptions`.

2022-10-28 14:51 UTC, pboguslawski commented on apps/dav/lib/Server.php
> +			if (\OC::$server->getConfig()->getAppValue('calendar', 'allow_subscribe_link', 'yes') === 'yes') {
Thanks for clarification. Param name [changed](https://github.com/nextcloud/server/pull/34387/commits/6128163b8a56a7c3f13d7a4f56beb74d6d7622eb) to `dav.allow_calendar_link_subscriptions` to distinguish it from other subscription methods.

2022-10-28 15:33 UTC, tcitworld approved these changes
Please squash your commits

2022-10-28 16:12 UTC, pboguslawski commented
> Please squash your commits

Don't see such option in github UI nor have spare time for such cleanup outside now. Please consider [squashing on merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) if you still see it valuable or just accept PR as is with all history included.

2022-10-31 15:24 UTC, ChristophWurst commented
We've tried to squash the PR for you but we lack the permission to push to your fork.

2022-11-02 08:39 UTC, closed without merging

2022-11-02 08:43 UTC, pboguslawski commented
Deleted branch by accident which closed this PR - sorry. Please find squashed PR on
https://github.com/nextcloud/server/pull/34920