Issue#34305: Added dynamically adjustment for footer height
nextcloud/server pull request #34391
Opened 2022-10-03 00:12 UTC by RyanAveritt

Footer height is dynamically adjusted to 95px if one of the legal links is set; originally 65px. (first-time contributor)

2022-10-16 05:55 UTC, RyanAveritt commented
Checking in; is there anything else I need to do? Also, any feedback and/or advice would be highly welcomed.

2022-10-16 09:23 UTC, skjnldsv requested changes

2022-10-16 09:23 UTC, skjnldsv commented on core/js/public/publicpage.js
> +    if(document.querySelectorAll("a.legal").length > 0) document.getElementById("body-public").querySelector('footer').style = 'height: 95px'
```suggestion
    if (document.querySelectorAll('a.legal').length > 0) {
    	document.getElementById('body-public').querySelector('footer').style = 'height: 95px'
  	}
```

2022-10-16 09:24 UTC, skjnldsv commented on core/js/public/publicpage.js
> +    if(document.querySelectorAll("a.legal").length > 0) document.getElementById("body-public").querySelector('footer').style = 'height: 95px'
But I think @szaimen have another fix somewhere?
I'm not super sure this is the way to go :thinking:

2022-10-16 09:33 UTC, jotoeri commented
Wouldnt it be better to have a class `footer--large` or so in `public.css` and insert the class (dynamically) on the template? That would insert it from ground up instead of altering the height afterwards. 🤔 
https://github.com/nextcloud/server/blob/5ab021c6bf93952dc0b81a3b62626df2936245c5/core/css/public.scss#L70
https://github.com/nextcloud/server/blob/5ab021c6bf93952dc0b81a3b62626df2936245c5/core/templates/layout.public.php#L94

2022-10-16 10:28 UTC, szaimen commented
+1 for a the global css variable approach

2022-10-16 11:08 UTC, skjnldsv commented
> +1 for the global css variable approach

Careful about too much variables, we're defeating the initial goal of them

2022-10-16 11:14 UTC, jotoeri commented
> > +1 for the global css variable approach
> 
> Careful about too much variables, we're defeating the initial goal of them

Nah, was not thought as global variable (from my side), but just a class overriding the height:
```
footer {
    height: 65px;

    .footer--large {
        height: 80px;
    }
}

```

2022-10-16 11:15 UTC, szaimen commented
> > +1 for the global css variable approach
> 
> Careful about too much variables, we're defeating the initial goal of them

Right. However since we have mutliple places where we need to reuse that one, I guess adding one for that is probably the best idea...

2022-10-16 11:19 UTC, szaimen commented
See https://github.com/nextcloud/server/search?q=%24footer-height

2022-10-16 11:24 UTC, jotoeri commented
> See https://github.com/nextcloud/server/search?q=%24footer-height

Uhm, maybe i understood wrong, but aren't these just variables within the scss sheet, but will be compiled to fixed numbers within the finally loaded css? Which is sth. different than global css variables `var(--footer-height)`, that could be used within apps then?

2022-10-16 11:25 UTC, szaimen commented
> Uhm, maybe i understood wrong, but aren't these just variables within the scss sheet, but will be compiled to fixed numbers within the finally loaded css? Which is sth. different than global css variables `var(--footer-height)`, that could be used within apps then?

indeed. That is why I would push towards a global css variable that could get reused.

2022-10-16 11:41 UTC, jotoeri commented
> That is why I would push towards a global css variable that could get reused or changed

Ok 👍 . But then my question was related to give a hint to RyanAveritt on where the variable `var(--footer-height)` can be calculated (depending on the footer-content) and inserted into the loaded variables. This i don't know currently by my own, so i can't tell anything on that. Probably somewhere in the theming app, which also produces the footer-content?

2022-10-16 11:45 UTC, szaimen commented
> Ok 👍 . But then my question was related to give a hint to RyanAveritt on where the variable `var(--footer-height)` can be calculated (depending on the footer-content) and inserted into the loaded variables. This i don't know currently by my own, so i can't tell anything on that. Probably somewhere in the theming app, which also produces the footer-content?

I don't know if we can make a logic from that. Rather changing the varialbe to e.g. 95px if impressum gets activated?

2022-10-16 11:49 UTC, jotoeri commented
> Rather changing the varialbe to e.g. 95px if impressum gets activated?

Yeah, thats what i meant. 😄 Just probably a bit bad formulated. Having a variable, that is either 65px or 95px. (While 95 seems a bit much to me, 80px or even less should suffice iirc. https://github.com/nextcloud/server/pull/30586)

2024-02-24 11:40 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

2024-02-24 11:40 UTC, closed without merging