computerFileSize(): allow comma as decimal-point
nextcloud/server pull request #34425
Opened 2022-10-04 13:34 UTC by rubo77

This should fix the issue  #18468 (Cannot set user quota with uneven values using locales that use a comma as decimal separator)

Signed-off-by: Ruben Barkow-Kuder <rubo77@users.noreply.github.com>

2022-10-04 13:44 UTC, rubo77 commented
maybe we should use this instead of replaceAll, which is not supported by oder browsers:

    replace(new RegExp(",","gm"),".")

2022-10-04 18:14 UTC, szaimen commented
Replaceall should be fine IIRC https://caniuse.com/?search=replaceall

2022-10-04 18:16 UTC, szaimen commented on core/src/OC/util.js
> +		const s = string.toLowerCase().replaceAll(',', '.').trim()
I still need to test this but what happens if you enter multiple dots?

2022-10-05 04:14 UTC, rubo77 commented
> Replaceall should be fine IIRC https://caniuse.com/?search=replaceall

Firefox 76 is only 2 years old: may 5, 2020.

I think, we should still support it

2022-10-05 04:16 UTC, rubo77 commented on core/src/OC/util.js
> +		const s = string.toLowerCase().replaceAll(',', '.').trim()
Dots stay, only commas are replaced with dots

2022-10-05 04:19 UTC, rubo77 commented
Please test this with a German or French locale in your browser

2022-10-10 21:10 UTC, szaimen requested changes
Thanks for your PR! 

I just tested this and it seems to work on the first glance. However after reloading the page, only whole values are applied so this would need an additional fix somewhere else.

2022-10-14 20:52 UTC, rubo77 commented
@szaimen could you please take over this pr then? I have no idea, where to search for

2022-10-17 19:26 UTC, szaimen commented
> @szaimen could you please take over this pr then? I have no idea, where to search for

I would like to but unfortunately I do not know where to look at either. Maybe someone of @nextcloud/server-frontend knows?

2024-02-24 11:40 UTC, closed without merging