Filter out backup user status (those beginning with _ as userId)
nextcloud/server pull request #34569
Opened 2022-10-13 07:08 UTC by tobiasKaminsky

Fix #34464 

Maybe it is smarter to do it directly on DB level, but I failed to do so…

2022-10-13 07:26 UTC, nickvergessen approved these changes

2022-10-13 07:26 UTC, nickvergessen commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
> +						&& !str_starts_with($status->getUserId(), "_");
```suggestion
						&& !str_starts_with($status->getUserId(), '_');
```

2022-10-13 07:26 UTC, nickvergessen commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
>  				$this->service->findAllRecentStatusChanges($limit + 1, 0),
Will never be an issue on page one, as everyone with a backup status should have a newer other status, but in theory page 2 could be empty because of this, as you first get a set of statuses and then filter out some.

2022-10-13 07:27 UTC, nickvergessen commented
/backport to stable25

2022-10-13 07:31 UTC, CarlSchwan approved these changes

2022-10-13 07:32 UTC, CarlSchwan requested changes
Actually doing that on the db status is a better idea. Can i push yo your branch?

2022-10-13 08:04 UTC, tobiasKaminsky commented
> Actually doing that on the db status is a better idea. Can i push yo your branch?

Sure! I just was not able to do it, knowledge wise.
Else I would also have done it, as it is the cleaner way and also has not drawbacks as Joas mentioned.

2022-10-13 09:43 UTC, YasinAshorian approved these changes

2022-10-13 13:31 UTC, julien-nc commented
@CarlSchwan I hope you don't mind me pushing here. I just fixed your typo leading to a syntax error.

2022-10-13 13:31 UTC, julien-nc approved these changes

2022-10-13 13:52 UTC, tobiasKaminsky commented
> "message": "Internal Server Error\nAn exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column '_%' in 'where clause'"

2022-10-13 14:22 UTC, PVince81 commented on apps/user_status/lib/Db/UserStatusMapper.php
> +				$qb->expr()->notLike('user_id', '_%')
need to use the escaping function for LIKE @julien-nc

2022-10-13 16:46 UTC, nickvergessen requested changes

2022-10-14 04:36 UTC, tobiasKaminsky commented
This works now!  Thanks Joas!

2022-10-14 07:16 UTC, nickvergessen approved these changes

2022-10-14 12:48 UTC, merged