fix imigration type hints
nextcloud/server pull request #34562
Opened 2022-10-12 17:26 UTC by rullzer

2022-10-27 20:30 UTC, miaulalala approved these changes
Thanks Roeland, I just ran into this

2022-10-28 07:26 UTC, rullzer commented
> Thanks Roeland, I just ran into this

well it still does boom it seems.
But feel free ot have a look and push potential fixes ;)

2022-10-28 10:47 UTC, miaulalala requested changes

2022-10-28 10:47 UTC, miaulalala commented on lib/public/Migration/SimpleMigrationStep.php
> +	public function changeSchema(IOutput $output, \Closure $schemaClosure, array $options): ?ISchemaWrapper {
I think this will make all old migrations go kaboom...

2022-10-28 11:29 UTC, miaulalala commented on core/Command/Db/Migrations/GenerateCommand.php
> -	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
this now makes static analysis go :fire: in migration generation.

2023-02-20 15:01 UTC, miaulalala commented
@rullzer feel free to continue but I'm out, this breaks all apps unfortunately

2024-08-13 09:36 UTC, closed without merging