Fix navigation pixel flickering
nextcloud/server pull request #34605
Opened 2022-10-14 12:36 UTC by skjnldsv

fix https://github.com/nextcloud/server/issues/34591

Margin is not included in the hovering.

2022-10-14 12:36 UTC, skjnldsv commented
/backport to stable25

2022-10-14 12:41 UTC, szaimen approved these changes
LGTM but didnt test

2022-10-18 08:53 UTC, skjnldsv commented
/rebase

2022-10-18 17:50 UTC, juliusknorr approved these changes

2022-10-18 18:21 UTC, szaimen requested changes
just tested this and doesnt seem to resolve the issue competely:

https://user-images.githubusercontent.com/42591237/196512812-ae41c55a-5110-4cac-b529-ed7e591fdc04.mp4

2022-10-18 18:24 UTC, nickvergessen commented
The PR is not compiled. Did you compile locally?

2022-10-18 18:26 UTC, szaimen commented
however if Julius found that it works for him in testing, I am fine with the change

2022-10-26 15:46 UTC, skjnldsv commented
/rebase

2022-10-26 15:57 UTC, szaimen commented
I can still reproduce this issue with this branch. Just tried again.

2022-10-26 15:59 UTC, szaimen commented
This is my test instance and even tried in a new incognito tab and session.

```
docker run -it \
--name nextcloud-easy-test \
-p 8444:443 \
-e TRUSTED_DOMAIN=10.6.0.1 \
-e SERVER_BRANCH=fix/navigation-flicker \
-e COMPILE_SERVER=1 \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

2023-09-02 07:43 UTC, closed without merging