fix checkmark for theme settings in dark mode
nextcloud/server pull request #34613
Opened 2022-10-14 15:36 UTC by szaimen

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/195885621-b96be39b-269e-4aeb-8efe-da5405ea0843.png) | ![image](https://user-images.githubusercontent.com/42591237/195885554-73a95e2b-14ad-4128-94f4-a0c01635a45b.png) |

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-10-14 15:36 UTC, szaimen commented
/backport to stable25

2022-10-14 17:30 UTC, skjnldsv commented on apps/theming/src/components/BackgroundSettings.vue
> +				filter: var(--background-invert-if-dark);
The checkmark is not above a main background, using this value does not make sense.

It should already be fixed with https://github.com/nextcloud/server/blob/f49ccd140fd5ada0aa640f6642464ad149c980e6/apps/theming/src/components/BackgroundSettings.vue#L50

What you really want is using `var(--original-icon-checkmark-white)` instead of `var(--icon-checkmark-white)` to prevent the auto dark/bright invert.
Or even better, use a material design icon instead and set the color via css on those two selectors
https://github.com/nextcloud/server/blob/f49ccd140fd5ada0aa640f6642464ad149c980e6/apps/theming/src/components/BackgroundSettings.vue#L257-L271

2022-10-14 17:31 UTC, skjnldsv submitted a review, later dismissed
See comment

2022-10-18 16:59 UTC, szaimen commented on apps/theming/src/components/BackgroundSettings.vue
> +				background-image: var(--original-icon-checkmark-white);
@skjnldsv it seems like this variable is not set. How can I create it?

2022-10-25 12:08 UTC, skjnldsv commented on apps/theming/src/components/BackgroundSettings.vue
> +				background-image: var(--original-icon-checkmark-white);
Seems set for me :thinking:

2022-11-08 13:25 UTC, szaimen commented
This works now :)

2022-11-08 13:32 UTC, szaimen commented
/compile

2022-11-08 15:01 UTC, skjnldsv requested changes
Already part of https://github.com/nextcloud/server/pull/34696

2022-11-08 15:02 UTC, skjnldsv approved these changes
But for backports on 25, I guess it make sense sure

2022-11-08 17:57 UTC, Pytal approved these changes

2022-11-08 17:58 UTC, merged

2022-11-08 18:21 UTC, szaimen commented
/backport 1e48661238d4f6e7792d17eccebe5b711255467d to stable25