Port files_versions to vue
nextcloud/server pull request #34769
Opened 2022-10-24 11:32 UTC by CarlSchwan

Simplify code and make it use our standard components, will be helpful when adding more features in the future

2022-10-24 12:20 UTC, PVince81 commented
is the border shadow around the thumbnail on purpose ? are we using this style elsewhere ?

is it on purpose that the row buttons are more blue-ish than the ones in the header ?

2022-10-24 12:24 UTC, CarlSchwan commented
> is the border shadow around the thumbnail on purpose ? are we using this style elsewhere ?

Yeah I added them because otherwise the preview is just looking really weird for any text document (and files versions is primarely used for text documents)

![image](https://user-images.githubusercontent.com/23653902/197524621-c571a1fa-5044-4133-a0f6-7c8db69539d6.png)

Alternative we could add either a more subtle shadow or a simple border 

@jancborchardt @nimishavijay what do you think?

> is it on purpose that the row buttons are more blue-ish than the ones in the header ?

It's using secondary action type and not the ternary action type, not sure what is the appropriate here as we don't have any guidelines documented somewhere :(

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +				<NcButton v-tooltip="t('files_version', 'Download this version')"
files_versions (missing s)

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +					:aria-label="t('files_version', 'Restore this version')"
to make it unique, include the name / datetime in the aria-label + tooltip

remember: a11y tools can make you "list all links/buttons" in the web page, so their names should be unique

I wonder if we should even go further and make it: "Restore version $version of file $fileName" as aria-label and tooltip

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +function getDavRequest() {
so the new webdav lib still doesn't make it easy to create propfind bodies ?

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +	const formatter = new Intl.RelativeTimeFormat('en-US', {
I think we're using "moment" JS everywhere, why not here ?

or was there a plan to move away ?

even if we don't use moment, such code would then need to be either in the global JS code in core or in a @nextcloud/... lib somewhere

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +	const fileVersion = version.filename.split('/').reverse()[0] // basename
`import { basename } from "@nextcloud/paths"`

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +		dateTime: Intl.DateTimeFormat('en-US', { dateStyle: 'full' })
use "moment"

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +		url: '/remote.php/dav' + version.filename,
maybe use "joinPaths" from `@nextcloud/paths` just to be sure of no missing slashes

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +		async getVersions() {
would call it fetchVersions() because "get" usually implies a getter that will return values, but you're not returning anything here

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +				showSuccess(t('files_versions', 'Old version restored'))
maybe remove "Old" because a version might not be specifically old

2022-10-24 12:34 UTC, PVince81 commented on apps/files_versions/src/views/VersionTab.vue
> +	.downlaod-button {
typo

2022-10-24 14:19 UTC, CarlSchwan commented on apps/files_versions/src/views/VersionTab.vue
> +	const formatter = new Intl.RelativeTimeFormat('en-US', {
Moment homepage is recomanding against using moment https://momentjs.com/docs/#/-project-status/ 

But yeah let's migrate to Intl later

2022-10-24 14:19 UTC, CarlSchwan commented on apps/files_versions/src/views/VersionTab.vue
> +function getDavRequest() {
yeah see https://github.com/perry-mitchell/webdav-client#custom-properties :(

2022-10-24 14:19 UTC, CarlSchwan commented on apps/files_versions/src/views/VersionTab.vue
> +					:aria-label="t('files_version', 'Restore this version')"
fixed

2022-10-25 09:39 UTC, skjnldsv commented on apps/files_versions/src/views/VersionTab.vue
> +			<li v-for="version in versions" class="version">
Elements in iteration expect to have 'v-bind:key' directives

2022-10-25 09:41 UTC, skjnldsv commented
A few eslint issues to fix :)

2022-10-25 10:17 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +			<li v-for="version in versions" class="version">
:robot:

2022-10-25 12:22 UTC, CarlSchwan commented
> > Yeah I added them because otherwise the preview is just looking really weird for any text document (and files versions is primarely used for text documents)
> 
> @CarlSchwan no problem, that's what we have `border: 1px solid var(--color-border);` for. ;) And remember the border radius too – just like we do for e.g. Mail attachments and the file list. (Is this a component yet?)
> 
> Drop shadow here does not really make sense as nothing is elevated. :) That is, the text linked with the preview would not have a drop shadow either.

changed to a simple border :) and I updated the PR description with the latest visual

2022-10-25 12:36 UTC, skjnldsv approved these changes

2022-10-25 14:15 UTC, artonge requested changes
Beside the logger comment, feel free to ignore the others as they are not crucial :)

2022-10-25 14:15 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +			client,
Does the client really needs to be in the component's data ?

2022-10-25 14:15 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +}
I would put those in a different js file.

2022-10-25 14:15 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +				console.debug('restoring version', version.url)
```suggestion
				logger.debug('restoring version', version.url)
```

2022-10-25 14:15 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +				console.error('Could not restore version', exception)
```suggestion
				logger.error('Could not restore version', {exception})
```

2022-10-25 14:15 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +				console.debug('restoring version', version.url)
Not sure if `logger.debug` takes more than 1 arg.

2022-10-25 14:21 UTC, artonge requested changes

2022-10-25 14:21 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +			<li v-for="version in versions" class="version" key="version.url">
Also, I would have used `NcListItem`
https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitem

2022-10-25 14:23 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +			<li v-for="version in versions" class="version" key="version.url">
`NcListItem` is a `<li>` inside, so it is almost a drop in replacement

2022-10-26 11:18 UTC, jancborchardt commented
Gave design feedback in the improvement PR at https://github.com/nextcloud/server/pull/34771/#pullrequestreview-1156318450 :)

2022-10-26 12:57 UTC, CarlSchwan commented
> - [x]  The wording of the menu is much too complex – as per the spec at https://github.com/nextcloud-gmbh/customer-feature-requests/issues/189#issuecomment-1257905430 it can simply be: "Name this version" (or "Edit version name" if name is set), "Download version", "Restore version" and "Delete version".

Done, this is now using the shorter name. I used the longer name previously because it was inline buttons and we needed for accessibility that the buttons are not the same

> - [ ] The icon in the tab header can be the same as the one you used for the emptycontent and the buttons

Unfortunately this is not possible because the tabs are using the old icons with class and not the vue material icons and there is no way yet to use a material icon with the current API :cry:

2022-10-26 13:00 UTC, CarlSchwan commented on apps/files_versions/src/views/VersionTab.vue
> +			<li v-for="version in versions" class="version" key="version.url">
I switched to NcListItem :)

2022-10-26 14:59 UTC, CarlSchwan commented
@jancborchardt took me 3 hours but I managed to make material icons works, and used the opportunity to move comments and files sharing to also use proper vue icons!

![image](https://user-images.githubusercontent.com/23653902/198061739-bcb5789f-51d8-409a-a4e2-d22a52018039.png)

The material icons are bigger than the old icons, but that needs to be fixed in nextcloud-vue (or port everything to use vue icons)

2022-10-26 15:24 UTC, artonge approved these changes
Looks good to me

2022-10-26 15:25 UTC, skjnldsv requested changes
See comment in https://github.com/nextcloud/activity/pull/981/files#r1005821285

2022-11-10 09:45 UTC, artonge commented
@skjnldsv I move the icon to plain SVG. Can you validate this approach ?
- I add to create a `raw?` `resourceQuery` for webpack to be able to import raw SVG instead of data URLs.
- I also created a `iconSvg` on the `Tab` class.

2022-11-10 13:36 UTC, skjnldsv commented on apps/files/src/models/Tab.js
> +		this._iconSvg = iconSvg
Doesn't seems to be used? `this._iconSvgSanitized` seems to be the one?

2022-11-10 13:37 UTC, skjnldsv commented on apps/files/src/views/Sidebar.vue
> +			fill: var(--color-main-text);
```suggestion
			fill: currentColor;
```

2022-11-10 13:37 UTC, skjnldsv commented on apps/files/src/views/Sidebar.vue
> +			fill: var(--color-main-text);
Careful abou tthe width/height too, you could lead to stretched svg :thinking: 
They're not all square iirc :)

2022-11-10 13:38 UTC, skjnldsv commented on apps/files_versions/src/files_versions_tab.js
> +window.addEventListener('DOMContentLoaded', function () {
```suggestion
window.addEventListener('DOMContentLoaded', function() {
```

2022-11-10 13:38 UTC, skjnldsv commented
@artonge added comments :)
But we're close to completion! :rocket:

2022-11-10 15:38 UTC, artonge commented on apps/files/src/models/Tab.js
> +		this._iconSvg = iconSvg
Ah, yes, forgot to clean that up. Thanks

2022-11-10 15:40 UTC, artonge commented on apps/files/src/views/Sidebar.vue
> +			fill: var(--color-main-text);
Didn't know that one, tahnks

2022-11-10 15:55 UTC, artonge commented on apps/comments/src/comments-tab.js
> +import MessageReplyText from '@mdi/svg/svg/message-reply-text.svg?raw'
Disabled eslint for those errors, no idea why it is failing.

2022-11-24 11:18 UTC, skjnldsv approved these changes

2022-11-28 16:36 UTC, artonge commented
Rebased. Will merge when CI is green

2022-11-29 09:20 UTC, merged