update browser warning
nextcloud/server pull request #34776
Opened 2022-10-24 15:45 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-10-24 15:46 UTC, come-nc approved these changes
Better than before anyway :shrug:

2022-10-25 06:11 UTC, skjnldsv requested changes
See comment, I think the wording could be improved and the punctuation is a bit too strong :)

2022-10-25 22:57 UTC, szaimen commented
/rebase

2022-10-25 23:02 UTC, szaimen commented
/compile

2022-10-26 08:07 UTC, skjnldsv approved these changes

2022-10-26 08:07 UTC, merged