Allow app to register a download provider
nextcloud/server pull request #34956
Opened 2022-11-03 17:59 UTC by artonge

This allows to provide a file content for a given dav path.

2022-11-04 11:28 UTC, CarlSchwan commented on lib/private/AppFramework/Bootstrap/RegistrationContext.php
> +	public function registerFileDownloadProvider(string $appId, string $class): void {
this should be added to the public interface

2022-11-04 11:28 UTC, CarlSchwan commented on lib/private/AppFramework/Bootstrap/RegistrationContext.php
> +	private $fileDownloadProviders = [];
```suggestion
	private array $fileDownloadProviders = [];
```

2022-11-08 05:53 UTC, nickvergessen commented on lib/public/Files/IFileDownloadProvider.php
> +interface IFileDownloadProvider {
> The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result

2022-11-08 06:58 UTC, nickvergessen requested changes

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +	 * @PublicPage
> The DownloadController is accessible from a logged-out user. (@PublicPage)

Please make use of the rate limit then, so guests can not DDoS the server:
https://github.com/nextcloud/server/blob/6312c0df6949955d1cd59c3dd444268e0773293c/lib/private/AppFramework/Middleware/Security/RateLimitingMiddleware.php#L42-L43

Should also add brute force protection and log attempts for guessing share tokens https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php#L44

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +					$provider = \OCP\Server::get($registration->getService());
can we do this once and outside of the loop? The result should not change, but it's more light weight

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +		$files = json_decode($files);
```suggestion
		$files = json_decode($files, true);
```

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +		if (count($files) === 0) {
Should we have an upper limit as well? Server can easily run into a timeout anyway.

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +			$this->addNode($response, $node, str_replace($commonPrefix, '', $filePath));
This does not look correct. If you want to cut of the common prefix you need to use `substr`.

Currently if the commonPrefix ends up being  `files` **all** occurrences of `files` will be replaced: `files/admin/My files/` will continue with `/admin/My /`

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +	private function getCommonPrefix(string $str1, string $str2): string {
What is the goal of this function? It looks very dangerous and I don't think it does what you think it does?

`?files=['photos/sharedalbums/bob/img.png','photos/sharedalbums/bar/img.png']` has commonPrefix of `photos/sharedalbums/b` and then try to find notes like `ob/img.png` and `ar/img.png`?!

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Provider/FileDownloadProvider.php
> +		$filePath = str_replace("files/$userId", '', $davPath);
same here, use `substr`

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Provider/FileDownloadProvider.php
> +		$userId = explode('/', $davPath)[1];
Can save some work:
```suggestion
		$userId = explode('/', $davPath, 3)[1];
```

At the same time we can prevent a little log on invalid input:
```suggestion
		$userId = explode('/', $davPath, 3)[1] ?? null;
```

2022-11-08 06:58 UTC, nickvergessen commented on lib/public/AppFramework/Bootstrap/IRegistrationContext.php
> +	 * @since 25.0.0
```suggestion
	 * @since 26.0.0
```

2022-11-08 06:58 UTC, nickvergessen commented on lib/public/Files/IFileDownloadProvider.php
> +	public function getNode(string $davPath): ?Node;
Please document that `davPath` is arbitrary user input and was in no way validatated or verified

2022-11-08 06:58 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +			$this->addNode($response, $node, str_replace($commonPrefix, '', $filePath));
Also if you only request one file, everything will be cut away and you get a zip with a `download` file inside which is missing the file name and extension

2022-11-08 16:48 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +		if (count($files) === 0) {
Difficult to predict from the number of files. Also, what to do if we reach a timeout ? Because this prevent users from downloading their files. We can maybe create a background job that will make the file available at a specific URL.

Would checking for the `execTime = currentTime` - `startTime` in the loop make sense? If `execTime` is bigger than `timeoutTime`, we can return with an message saying, "Download will be available later at `url`".

Same thing with the size. Not sure how the zip is created, but if this is in memory, then this will lead to OOM. So when the size reaches `2Gb`, we can also return the same message.

2022-11-08 17:01 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +		$files = json_decode($files);
Not sure if it makes sense. `$files` looks like `['path1', 'path2, ...]` so not associative.
Is there another reason for `true` to make sense?

2022-11-08 17:02 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +					$provider = \OCP\Server::get($registration->getService());
True, done

2022-11-08 17:12 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +	 * @PublicPage
Shouldn't there be a way to indicate failed guess attempts for brute force protection ? Like in:

https://github.com/nextcloud/photos/blob/05c3c2f2271b5ee58c1a0b9a7b3f55573230d20b/lib/Sabre/PublicAlbumAuthBackend.php#L53-L60

2022-11-08 17:27 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +			$this->addNode($response, $node, str_replace($commonPrefix, '', $filePath));
Ah, yes, I forgot to fix the initialization of `$commonPrefix`

Switched to:

```php
[$firstPrefix,] = \Sabre\Uri\split($files[0]);
$commonPrefix = $firstPrefix;
```

And also switched to `substr`.

2022-11-08 17:40 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +	private function getCommonPrefix(string $str1, string $str2): string {
It's to prevent having a zip file with this kind of hierarchy:

```txt
files/
├─ userId/
│  ├─ folderName/
│  │  ├─ theFileIWant.txt
```

But only
```txt
theFileIWant.txt
```

Note that  `$commonPrefix` is not used for searching, but only for building the zip.

However, your concern is still valid. The best way would be to be able to split the path and then compare the parts. But I am not sure that we have a proper way to do that in PHP. Any tips ?

2022-11-08 17:49 UTC, artonge commented on lib/public/Files/IFileDownloadProvider.php
> +interface IFileDownloadProvider {
They are, I think.
Should I commit `installed.php` and `autoload.php` too ?

2022-11-08 17:50 UTC, artonge commented on lib/public/Files/IFileDownloadProvider.php
> +interface IFileDownloadProvider {
Ah, no, ok, there are now :)

2022-11-08 17:52 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +	 * @PublicPage
Yes for brute force protection is `$response->throttle();`

For rate limiting this is not needed as rate limiting always kicks in.

2022-11-08 17:55 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +		$files = json_decode($files);
Right, so as long as it's a normal packaged string array it works. with adding `, true` you can be a bit more forgiving to weird frontends (e.g. if they filter out things from the array afterwards and have gaps in their keys
https://3v4l.org/2I20A

2022-11-08 17:56 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +	private function getCommonPrefix(string $str1, string $str2): string {
`explode('/', $path)` and then compare the segments?

2022-11-08 17:59 UTC, nickvergessen commented on apps/files/lib/Controller/DownloadController.php
> +		[$firstPrefix,] = \Sabre\Uri\split($files[0]);
Psalm complains: `Function Sabre\Uri\split does not exist`

```suggestion
		[$firstPrefix,] =explode('/', $files[0], 2);
```
should work fine

2022-11-11 16:02 UTC, icewind1991 commented
What is the value of adding this new system over adding a dav collection for photos for downloading the files?

2022-12-16 16:25 UTC, PVince81 commented
@artonge see Robin's previous comment. I don't remember why we'd need this for the new Photos app and whether we used another approach. Can you check ?

2023-02-02 11:02 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +		$files = json_decode($files);
Your link shows an example with an object and not an array. I'll keep the actual behavior, as being strict is not really a bad thing.

2023-02-02 11:16 UTC, artonge commented on apps/files/lib/Controller/DownloadController.php
> +		[$firstPrefix,] = \Sabre\Uri\split($files[0]);
Was afraid that file names could contain `'\/'`. Especially files coming from windows. But we apparently do that everywhere, so it should be safe.

2023-02-02 11:24 UTC, artonge commented
> What is the value of adding this new system over adding a dav collection for photos for downloading the files?

The issue with the current system is that we can't download files that are not shared to us.

As the album feature in photos does not use our sharing system, the current download system is not aware that a user has access to a given file through an album share.

This new controller allows to download a file based on its DAV path, allowing apps to provide or not a content for the path.

2024-08-14 10:19 UTC, closed without merging