Add alt to the logo, adapt css for logo
nextcloud/server pull request #35071
Opened 2022-11-10 09:49 UTC by JuliaKirschenheuter

A11y issue regarding alt text for logo on multiple pages

2022-11-10 09:53 UTC, JuliaKirschenheuter commented
hope i've covered all public / logged in pages
I was not sure about translation: can i leave it like i've done or should i do it different (pleas tell me how)?

2022-11-11 08:46 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
this breaks theming

2022-11-11 08:46 UTC, ChristophWurst commented on core/css/server.css
> -  background-image: var(--image-logoheader, var(--image-logo, url("../img/logo/logo.svg")));
the image is a css var so it can be overwritten by the theming app

2022-11-11 08:46 UTC, ChristophWurst commented
/backport to stable25

2022-11-11 09:15 UTC, JuliaKirschenheuter commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
could you please pasta a screenshot? I've tested it yesterday and haven't seen it

2022-11-11 09:36 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
:spaghetti:

2022-11-11 09:40 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
| `master` | `fix/384-missing_alt_text_for_logo_on_multiple_pages` |
|---|---|
| ![Bildschirmfoto vom 2022-11-11 10-39-25](https://user-images.githubusercontent.com/1374172/201312176-fc0d1dae-beb4-4411-8f57-9b9d1aa2056d.png) | ![Bildschirmfoto vom 2022-11-11 10-39-51](https://user-images.githubusercontent.com/1374172/201312204-831013ea-c83d-4b19-9db2-6460f9535d02.png) |

2022-11-11 09:41 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
The logo is set in `/settings/admin/theming`

2022-11-11 09:47 UTC, ChristophWurst commented
In my humble research I found https://css-tricks.com/replace-the-image-in-an-img-with-css/ and https://stackoverflow.com/questions/17705768/is-it-possible-to-change-img-src-attribute-using-css as possible approaches for the css-overwritten logo in the case of theming.

2022-11-11 10:10 UTC, JuliaKirschenheuter commented on core/css/server.css
> -  background-image: var(--image-logoheader, var(--image-logo, url("../img/logo/logo.svg")));
yes, but image should be an ```<img>``` with source to image. Why should i replace it here and don't use a ```<img scr=''>```

2022-11-11 10:56 UTC, JuliaKirschenheuter commented on core/templates/layout.guest.php
> +							<img class="logo" src="/core/img/logo/logo.svg" alt="Nextcloud logo"/>
should work now

2022-11-11 13:00 UTC, ChristophWurst requested changes
The default logo is no longer replaced but simply overlapped

![image](https://user-images.githubusercontent.com/1374172/201345570-b2523c2f-028f-4a94-88ac-ded86443f528.png)

2022-11-16 14:12 UTC, ChristophWurst requested changes

2022-11-16 14:12 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
Shouldn't it be "Nextcloud logo" instead of "Logo Nextcloud" and translated?

2022-11-16 14:12 UTC, ChristophWurst commented on core/templates/layout.public.php
> +			<img class="logo logo-icon svg" alt="<?= p($l->t('Logo')).' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
use a placeholder for the parameter, not string concatenation. this allows translators to rearrange the order of words.

2022-11-16 14:12 UTC, ChristophWurst commented on core/templates/layout.user.php
> +					<img class="logo logo-icon" alt="<?= p($l->t('Logo')).' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
same string concatenation issue

2022-11-22 15:47 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
This is still the case. I'm not a native speaker but "Nextcloud logo" sounds more like English than "Logo Nextcloud". @Pytal what shall we use?

2022-11-22 18:15 UTC, Pytal commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
"Nextcloud logo" for english in the source code and translators will be able to translate accordingly

2022-11-23 10:51 UTC, JuliaKirschenheuter commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
I don't know how to make it work. The first parameter inside of ```$l->t``` is "always" a text, the second param: phpVar. Otherwise this won't work

2022-11-23 12:01 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
```alt="<?php p($l->t('%s logo', [$theme->getName()])); ?>"```

2022-11-23 14:10 UTC, JuliaKirschenheuter commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?= 'Logo'.' '.$theme->getName() ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
ah, ok. I haven't used ```'%s logo'``` in a right way. Thank you

2022-11-23 14:58 UTC, ChristophWurst requested changes
Breaks the logo if there is a custom theme logo

![Bildschirmfoto vom 2022-11-23 15-56-03](https://user-images.githubusercontent.com/1374172/203577941-6a859333-25b3-47b1-bd46-8a808cde3a06.png)

The image points to ``/apps/theming/image/logo?useSvg=1&v=47`` which returns a 404

2022-11-23 14:59 UTC, ChristophWurst commented
My custom logo is actually also broken on `master`. I'm investigating.

2022-11-23 15:06 UTC, ChristophWurst commented
There is very likely a bug that drops the theme image. I'm not able to find a faulty commit with git bisect. Ignoring for now. This change seems to work.

2022-11-23 15:06 UTC, ChristophWurst approved these changes
Works

2022-11-26 01:37 UTC, Pytal commented on core/templates/layout.public.php
> -			</span>
Reason for the removal?

2022-11-28 07:49 UTC, JuliaKirschenheuter commented on core/templates/layout.public.php
> -			</span>
In another PR I've moved this lines to <main>

https://github.com/nextcloud/server/blob/b51063d1c9a93e9e12ead27b7a9103e646c021b7/core/templates/layout.public.php#L83-L87

should i move this part back / or place it in both parts?

2022-11-28 19:50 UTC, Pytal commented on core/templates/layout.public.php
> -			</span>
I see no need to duplicate this then :)

2022-11-28 19:51 UTC, Pytal approved these changes

2022-11-29 15:47 UTC, JuliaKirschenheuter commented
/rebase

2022-11-30 09:04 UTC, JuliaKirschenheuter commented
/compile amend /

2022-11-30 10:15 UTC, ChristophWurst commented
```
Undefined index: logoUrl

/drone/src/core/templates/layout.guest.php:38
```

2022-11-30 13:59 UTC, ChristophWurst commented on core/templates/layout.guest.php
> +							<img class="logo" alt="<?php p($l->t('%s logo', [$theme->getName()])); ?>" src="<?= $_['logoUrl'].$theme->getLogo(); ?>">
``occ config:system:set logo_url --value="https://nextcloud.com/blog/press_releases/nextcloud-hub-3-release-ai-photos/"`` breaks this. The logo URL can come from config or themeing or both.

```suggestion
							<img class="logo" alt="<?php p($l->t('%s logo', [$theme->getName()])); ?>" src="<?= $_['logoUrl'] ?? $theme->getLogo(); ?>">
```

2022-11-30 17:39 UTC, ChristophWurst approved these changes

2022-12-01 07:28 UTC, JuliaKirschenheuter commented
/compile amend /

2022-12-01 16:45 UTC, JuliaKirschenheuter commented
/compile amend /

2022-12-06 18:54 UTC, szaimen commented
Conflicts...

2022-12-08 09:36 UTC, merged

2023-01-17 11:02 UTC, danxuliu commented
[This removed the title](https://github.com/nextcloud/server/pull/35071/files#diff-56002c421732a268945da541cbcd7dc2e595e1c60501fd49c627c0bd5f936b4aL42-L48) and, therefore, [the name of the shared file in the public share page](https://github.com/nextcloud/server/blob/54031e370ac05b127d4bc799de99ce1b643adcbb/apps/files_sharing/lib/Controller/ShareController.php#L546). Is this known / expected or should I open an issue about it?

**Before:**
![Public-Share-Header-Title-Before](https://user-images.githubusercontent.com/26858233/212881497-bd890653-18da-4fd1-9a43-3e21b1eda680.png)

**After:**
![Public-Share-Header-Title-After](https://user-images.githubusercontent.com/26858233/212881561-72e0b9e4-8e4f-4caa-8a8a-f1d66377d6b6.png)

2023-01-17 11:36 UTC, st3iny commented
> [This removed the title](https://github.com/nextcloud/server/pull/35071/files#diff-56002c421732a268945da541cbcd7dc2e595e1c60501fd49c627c0bd5f936b4aL42-L48) and, therefore, [the name of the shared file in the public share page](https://github.com/nextcloud/server/blob/54031e370ac05b127d4bc799de99ce1b643adcbb/apps/files_sharing/lib/Controller/ShareController.php#L546). Is this known / expected or should I open an issue about it?
> 
> **Before:** ![Public-Share-Header-Title-Before](https://user-images.githubusercontent.com/26858233/212881497-bd890653-18da-4fd1-9a43-3e21b1eda680.png)
> 
> **After:** ![Public-Share-Header-Title-After](https://user-images.githubusercontent.com/26858233/212881561-72e0b9e4-8e4f-4caa-8a8a-f1d66377d6b6.png)

Yes, please open a new issue so that it won't get lost.

2023-01-17 13:41 UTC, skjnldsv commented
Reverted.
https://github.com/nextcloud-gmbh/server/issues/384#issuecomment-1385421837