provide api to convert link to mail share
nextcloud/server pull request #3513
Opened 2017-02-16 15:50 UTC by schiessle

Providing a endpoint for the old API to send a public link by mail. In our case we will create a full featured mail share.

I tested it by repeating the API call with Curl, but would be good to test it with the actual sync client to make sure that's really the end point they use.

@rullzer can you test this with the upcoming sync client to see if it works as expected.

2017-02-16 15:51 UTC, LukasReschke requested changes

2017-02-16 15:51 UTC, LukasReschke commented on core/Controller/LegacyShareController.php
> +	 * @NoCSRFRequired
Nope.

2017-02-16 15:53 UTC, schiessle commented on core/Controller/LegacyShareController.php
> +	 * @NoCSRFRequired
oh, left over from testing...

2017-02-17 13:28 UTC, schiessle commented
Looked at the source code of the client and saw that it doesn't use the server to send the link by mail, instead it just opens the desktop mail client with the link

2017-02-17 13:28 UTC, closed without merging