Add backend for version naming
nextcloud/server pull request #35160
Opened 2022-11-14 17:19 UTC by artonge

## TODO

- [x] Create `oc_files_versions` table with `id`, `file_id`?, `version_id`, `name`, and `author` for future.
- [ ] Plug into DAV plugin
- [ ] Check current ajax routes
- [ ] Expose endpoint to name a version
- [ ] Expose endpoint to create a new version from the current version
- [ ] Expose endpoint to delete a version
- [ ] Checkout S3 and group folders implementation as Carl raise some concerns
- [ ] Remove experimental flag on UI

### Follow up

- [ ] Use COPY instead of MOVE when restoring version, so that it stays in the history (if not already the case)
- [ ] Disable cleanup of named version in [`files_versions/lib/Storage.php`](https://github.com/nextcloud/server/blob/ea377578ad50809c13e792acfa2bc1bd6b94df24/apps/files_versions/lib/Storage.php#L558-L572)

Need https://github.com/nextcloud/server/pull/35080

2022-11-14 18:49 UTC, tcitworld commented
>  Checkout S3 [...] implementation as Carl raise some concerns

Yeah, since automatic expiration of versions is handled by the S3 platform itself, `oc_files_versions` will reference non-existing versions. Maybe there's a way to set a flag on S3's side to avoid the expiration for the named versions?

2022-11-14 21:11 UTC, juliushaertl commented
> Checkout S3 and group folders implementation as Carl raise some concerns

cc @mejo- as I remember there also was a groupfolder-like version backend in collectives.

2022-11-15 07:49 UTC, PVince81 commented
regarding S3, this would only be handled in S3 if the app https://github.com/nextcloud/files_versions_s3
idea: we could disable the permanent version feature when this app is enabled to avoid unwanted side effects

2022-11-15 07:51 UTC, PVince81 commented
we will also need to figure out how to backfill old versions that existed before this feature
probably we just do it on-demand because scanning all files would take a while

on-demand would mean that if there are no entries in the table for a given file id, we check on disk and do a one-shot scan to populate the table for said file id

2022-11-15 11:10 UTC, artonge commented
> we will also need to figure out how to backfill old versions that existed before this feature

How about we keep the current logic and only use the table to store versions with a name ?
Then we just populate the versions with their name.

Something like:

```js
versions = existingLogicToGetVersionsFor(fileId)
namedVersions = newLogicToGetNamedVersionsFor(fileId) // so we just add this line
versions = merge(version, namedVersions) // and this line
return versions
```

2022-11-16 16:18 UTC, artonge commented
After discussion, let's load versions data on demand, ie. when the user opens the sidebar or during expiration.
Need to check concurrence issue when initing entries for a file.

2022-11-16 16:28 UTC, artonge commented on apps/files_versions/lib/Migration/Version1020Date20221114144058.php
> +		]);
@juliushaertl Should I add a column for the author(s?).

1. This means that we need the spec now.
    1.1 Only 1 author by version. I think that is not what you want.
    1.2 Storing the authors as a JSON array ? But we can't search by author then. Maybe not an issue.
    1.3 Having one entry by author for each version ? This leads to a lot of duplicate data. 
2. We can also store this info in another table `oc_files_versions_authors`

I think 1.2 or 2. would make the most sense.

2022-11-21 16:20 UTC, juliushaertl commented on apps/files_versions/lib/Migration/Version1020Date20221114144058.php
> +		]);
I don't have a use case for filtering in mind right now, so I'd say going with a json column is fine. If that makes the implementation more straight forward I would even say it could be additional to the current author column (so just for additional authors), as we probably always have one "main" author anyways due to the fact that the filesystem is always being setup as one specific user.

2022-11-23 13:12 UTC, artonge commented
Changed base to include https://github.com/nextcloud/server/pull/35080 as discussed

2022-11-23 14:14 UTC, CarlSchwan commented on apps/files_versions/lib/Db/VersionsMapper.php
> + * @extends QBMapper<Version>
```suggestion
 * @extends QBMapper<VersionEntity>
```

2022-11-28 15:32 UTC, artonge commented on apps/files_versions/lib/Capabilities.php
> +				'version_labeling' => $this->config->getSystemValueBool('enable_version_labeling', true),
How could I check if 'files_s3_versions' and 'groupfolders' are installed to disable the capabilities?

2022-11-28 15:33 UTC, artonge commented on apps/files_versions/lib/Capabilities.php
> +				'version_deletion' => $this->config->getSystemValueBool('enable_version_deletion', true),
How can I check if 'files_s3_versions' and 'groupfolders' are installed to disable the capabilities?

2022-11-29 10:40 UTC, CarlSchwan approved these changes
:+1:

2022-11-30 09:49 UTC, szaimen requested changes, later dismissed
@artonge for making the sidebar mobile-compliant, please use this prop: https://github.com/nextcloud/nextcloud-vue/issues/3524#issuecomment-1331889120. Thanks! :)

2022-11-30 11:47 UTC, icewind1991 commented on apps/files_versions/lib/Migration/Version1020Date20221114144058.php
> +		]);
it probably makes same to store the same int, `IMimeTypeLoader` provides the methods for mapping between them

2022-11-30 16:57 UTC, artonge commented
- [ ] Server installation is failing. Apparently, having a hook that require `$userFolder` is not possible.

2022-12-01 16:05 UTC, artonge commented
- [ ] Unit tests are failing now because of hooks not being wired up correctly

2022-12-06 12:57 UTC, artonge commented on apps/files_versions/appinfo/info.xml
> +	<version>1.20.0</version>
Change to v1.19.1

2022-12-22 09:36 UTC, artonge commented
@skjnldsv I could need a review on the cypress part, to harmonize it with your initial work. I also tweaked the GH action file. Also, if you have time, a review on the front-end part is always welcome :)

2022-12-27 15:59 UTC, artonge commented
/rebase

2023-01-19 11:00 UTC, ArtificialOwl approved these changes

2023-01-19 11:01 UTC, ArtificialOwl commented
some points:

- frontend: `undefined` as name of the version when creating a new file,
- backend: might be interesting to store in the table the `fileId` of the version/backup file

2023-01-26 10:08 UTC, artonge commented
/rebase

2023-01-30 09:40 UTC, merged

2023-02-21 13:10 UTC, DaphneMuller commented
hello @artonge 
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

2023-02-21 14:41 UTC, artonge commented
Did the admin one, but forgot the user doc

Admin: https://github.com/nextcloud/documentation/pull/9618
User: https://github.com/nextcloud/documentation/pull/9649