Smaller performance optimizations
nextcloud/server pull request #35223
Opened 2022-11-17 09:38 UTC by juliushaertl

This is a collection of smaller performance improvements in different areas that I've found when looking at some profiles in regards to class loading, dependency injection and server initialization. The commit messages contain more details about the individual changes.

- Avoid container dance for appName
- Skip querying the app container for server namespace
- Take some shortcut when setting up the application class
- Use single resource locator instance
- Set apcu prefix for composer
- Cache available languages locally

2022-11-17 09:43 UTC, ChristophWurst commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +				throw new QueryException('skipping to server container');
AFAIR exceptions always come with a bit of a cost due to capturing the current context information before the process continues in the catch block. So I wonder how much impact the throw has here and if there is a more elegant way to go to the server container without the use of exceptions.

2022-11-17 11:06 UTC, juliushaertl commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +				throw new QueryException('skipping to server container');
Nothing I could catch with profiling, but I pushed an attempt without throwing.

2022-11-18 08:35 UTC, ChristophWurst approved these changes

2022-11-21 08:23 UTC, come-nc requested changes

2022-11-21 08:23 UTC, come-nc commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +	private $appName;
```suggestion
	private string $appName;
```
Or if it may be null in some cases, at least add a phpdoc type of `?string`

2022-11-21 08:23 UTC, come-nc commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +		$isServerClass = strpos($name, 'OCP\\') === 0 || strpos($name, 'OC\\') === 0;
I think we have a polyfill for str_starts_with, so we can use it instead of strpos.
It’s more readable and most likely more efficient on recent PHP versions.

2022-11-21 08:23 UTC, come-nc commented on lib/private/TemplateLayout.php
> +		static $jsLocator = null;
It can be a classic property with a call to Server::get to fill it, no?

2022-11-21 10:36 UTC, come-nc commented on lib/private/ServerContainer.php
> +		if (strpos($name, 'OCA\\') !== 0) {
str_starts_with

2022-11-21 10:36 UTC, come-nc commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +		} elseif ($this->appName === 'settings' && strpos($name, 'OC\\Settings\\') === 0) {
str_starts_with

2022-11-21 10:36 UTC, come-nc commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +		} elseif ($this->appName === 'core' && strpos($name, 'OC\\Core\\') === 0) {
str_starts_with

2022-11-21 10:36 UTC, come-nc commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +		} elseif (strpos($name, \OC\AppFramework\App::buildAppNamespace($this->appName) . '\\') === 0) {
str_starts_with

2022-11-21 10:36 UTC, come-nc commented on lib/private/TemplateLayout.php
> +		static $jsLocator = null;
:+1:

2022-11-21 11:21 UTC, nickvergessen commented on lib/private/ServerContainer.php
> +		if (strpos($name, 'OCA\\') !== 0) {
That is PHP 8.0+

2022-11-21 12:16 UTC, juliushaertl commented on lib/private/ServerContainer.php
> +		if (strpos($name, 'OCA\\') !== 0) {
We ship a polypill with https://github.com/nextcloud/3rdparty/blob/e0b9473487114accdba2e5a829ba763589ce5860/symfony/polyfill-php80/bootstrap.php#L32 but I need to double check if is is actually being loaded

2022-11-21 12:32 UTC, juliushaertl commented on lib/private/ServerContainer.php
> +		if (strpos($name, 'OCA\\') !== 0) {
Yes, seems through: https://github.com/nextcloud/3rdparty/blob/e0b9473487114accdba2e5a829ba763589ce5860/symfony/polyfill-php80/composer.json#L27

2022-11-21 12:44 UTC, juliushaertl commented
Resource locator tests need another check, looking into that

2022-12-07 22:23 UTC, CarlSchwan approved these changes
nice work :)

2022-12-08 09:35 UTC, merged