Use a dedicated LDAP host and port for background jobs if configured
nextcloud/server pull request #35229
Opened 2022-11-17 13:57 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-11-30 14:27 UTC, artonge requested changes

2022-11-30 14:27 UTC, artonge commented on apps/user_ldap/lib/Connection.php
> +			$isBackupHost = (trim($this->configuration->ldapBackupHost) !== "")
Would it make sense to rename to `hasBackupHost` to make it more obvious what this variable contains ?

2022-11-30 14:27 UTC, artonge commented on apps/user_ldap/lib/Connection.php
> +				&& (!\OC::$CLI || !$this->configuration->ldapBackgroundHost);
Hard to read, and adds conditions unrelated to the backup host.
I would split into another variable and make the config check more explicit:

```suggestion
				$shouldUseBackgroundHost = \OC::$CLI && (trim($this->configuration->ldapBackgroundHost) !== "");
```

2022-11-30 14:27 UTC, artonge commented on apps/user_ldap/lib/Connection.php
>  			if ($isBackupHost || $isOverrideMainServer) {
And make this condition more explicit

```suggestion
			if (($isBackupHost || $isOverrideMainServer) && !shouldUseBackgroundHost) {
```

2022-12-01 09:33 UTC, come-nc commented
I pushed a commit to make code clearer, but it makes it clear that there is a logic flaw:

When in CLI, background host is used and backuphost is not used even if backgroundhost do not answer. But, if backuphost is used by web UI because a fallback, then it will be used in CLI as well because of the cache.

So we need to decide to either:

- [ ] Fallback to backuphost even for CLI if backgroundhost do not anwser
- [ ] Never use backuphost in CLI event if backgroundhost is not answering, we use no fallback

(These is considering there is a backgroundhost configured, if not we always fallback if needed to keep the same behavior as before)

2022-12-01 09:34 UTC, come-nc commented
(There is also the question what to do when backup host is forced from admin settings, should that apply to cli if there is a background host?)

2022-12-01 09:39 UTC, blizzz commented
>  Fallback to backuphost even for CLI if backgroundhost do not anwser

I would say so (provided that backuphost differs from background host)

2022-12-01 09:51 UTC, come-nc commented
> > Fallback to backuphost even for CLI if backgroundhost do not anwser
> 
> I would say so (provided that backuphost differs from background host)

Ok, makes sense to me to always fallback to the backup if first host is not answering.
It also means forcing backup applies everywhere, which is more intuitive.

The problem with that is that we’ll need to split cache into 2 vars, to not go to backup for CLI when main is down but backgroundHost is still working.
I’ll implement that.

2022-12-19 11:28 UTC, come-nc commented
/rebase

2022-12-19 11:41 UTC, artonge approved these changes

2022-12-19 13:16 UTC, come-nc commented
rebased

2022-12-20 10:44 UTC, blizzz approved these changes
looks good

2022-12-20 10:47 UTC, merged