Save the scope of an auth token in the session
nextcloud/server pull request #3526
Opened 2017-02-17 14:42 UTC by icewind1991

And re-use the saved scope when no other scope has been set

2017-02-17 18:58 UTC, LukasReschke requested changes
I'll add an integration test to that before we merge it.

2017-02-17 18:58 UTC, LukasReschke commented on lib/private/Lockdown/LockdownManager.php
> +				$this->scope = $sessionScope;
Not covered by tests :)

2017-04-05 16:02 UTC, LukasReschke approved these changes
Added integration tests for this with https://github.com/nextcloud/server/pull/3526/commits/1d3e391ad8b9eadefab8eaa8239e6901b8466f01. Let's see if they pass :)

2017-04-05 20:05 UTC, rullzer approved these changes

2017-04-05 20:05 UTC, merged

2017-04-05 21:02 UTC, LukasReschke commented
stable11: https://github.com/nextcloud/server/pull/4225