[stable11] Backport of Fix Broken UUID Attribute Detection #3521
nextcloud/server pull request #3528
Opened 2017-02-17 21:25 UTC by blizzz

2017-02-18 10:31 UTC, LukasReschke requested changes
Tests seem to fail. Can you check on that?

2017-02-20 17:53 UTC, blizzz commented
> Tests seem to fail. Can you check on that?

I knew exactly this would fail on exactly this point. 🤔

2017-02-20 19:00 UTC, MorrisJobke approved these changes
Looks good and didn't explode 👍

2017-02-20 20:34 UTC, LukasReschke approved these changes

2017-02-20 20:34 UTC, merged