Theming using SCSS variables
nextcloud/server pull request #3531
Opened 2017-02-18 09:40 UTC by juliushaertl

Requires #3256

Custom themes as well as the theming app will get a lot simpler with #3256. We can just overwrite the existing SCSS variables and can drop most of the string concatenated CSS code inside of the ThemingController. 

There will be also much less maintenance work for the theming app in order to keep up with any CSS code changes.

@skjnldsv @nextcloud/theming @nextcloud/designers 

### Custom themes

With this you can apply a different color scheme to custom themes like this:

```
class OC_Theme {
	public function getScssVariables() {
		return [
			'color-primary' => '#000000',
			'color-primary-text' => '#ffffff',
                        'color-main-text' => '#ffffff',
                        'color-main-background' => '#333333'
		];
	}
}
```

### ToDo

- [ ] Theming code cleanup
- [ ] Fix tests

2017-02-18 09:42 UTC, skjnldsv commented on apps/theming/lib/Controller/ThemingController.php
> +				'#header .logo, ' .
Can't we pass the logo as a variable too? :D

2017-02-18 09:43 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +			$this->config->setAppValue('core', 'scss.variables', md5($injectedVariables));
I would rather like to use ICache here but since there is no caching enabled as a default, we would be generating the css code on every request. It's a little missuse of the appConfig but since it is loaded into memory on every request, there is no overhead when requesting existing files. We only have one database update per changing scss variables. Feedback for that would be nice.

2017-02-18 09:44 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +				'#header .logo, ' .
Should be possible. I'll have a look. :)

2017-02-18 09:47 UTC, skjnldsv commented on lib/private/Template/SCSSCacher.php
> +			$this->config->setAppValue('core', 'scss.variables', md5($injectedVariables));
Isn't cache enable my default no matter we have redis/memcache enabled? 
Isn't there a filecaching fallback for this purpose only?

2017-02-18 09:52 UTC, skjnldsv commented on lib/private/Template/SCSSCacher.php
> +			$this->config->setAppValue('core', 'scss.variables', md5($injectedVariables));
yep, I 've been using the ICache function on my fbsync extension since a year and I remember it was working before I enabled redis iirc :)

2017-02-18 09:56 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +			$this->config->setAppValue('core', 'scss.variables', md5($injectedVariables));
At least it was not on my simple dev setup. 

https://github.com/nextcloud/server/blob/master/lib/private/Server.php#L393-L406 looks like it was because PHPUNIT was enabled. Not sure if it is ok to regenerate everytime in dev setups, it is so slow then :(

2017-02-18 10:04 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +			$this->config->setAppValue('core', 'scss.variables', md5($injectedVariables));
> https://github.com/nextcloud/server/blob/master/lib/private/Server.php#L393-L406 looks like it was because PHPUNIT was enabled. Not sure if it is ok to regenerate everytime in dev setups, it is so slow then :(

The define there should only trigger if PHPUnit is actually running (e.g. on test execution)

2017-02-20 12:41 UTC, LukasReschke submitted a review, later dismissed
I like it 🚀 

Some nitpicks in the other comments here, mainly about unit tests and questions :)

2017-02-20 12:41 UTC, LukasReschke commented on apps/theming/lib/ThemingDefaults.php
> +	public function getScssVariables() {
Needs PHPDoc and a small unit test :)

2017-02-20 12:41 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +	public function __construct(ILogger $logger, IAppData $appData, IURLGenerator $urlGenerator, IConfig $config, \OC_Defaults $defaults) {
I'd prefer adding each of them on a newline to keep the code easier to read without having to scroll :)

2017-02-20 12:41 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +	private function variablesChanged($fileNameCSS, ISimpleFolder $folder) {
Tests please :)

2017-02-20 12:41 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +			if ($cachedFile->getMTime() < filemtime($variablesFile)
I suppose this block is because of updates in dev environments?

2017-02-20 12:41 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +	public function resetCache() {
Does this have to be public?

2017-02-20 12:41 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +	public function getInjectedVariables() {
Does this have to be public?

2017-02-20 16:36 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +	public function resetCache() {
I made those public so i can add unit test for those easily later on.

2017-02-20 16:38 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +			if ($cachedFile->getMTime() < filemtime($variablesFile)
Right. Otherwise changing anything in variables.scss will not trigger regenerating the css files.

2017-02-20 16:39 UTC, LukasReschke commented on lib/private/Template/SCSSCacher.php
> +	public function resetCache() {
You can also test private methods. Check `\Test\TestCase::invokePrivate`.

2017-02-20 16:40 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +	public function resetCache() {
But we can also cover them just with the existing public methods.

2017-02-20 16:48 UTC, juliushaertl commented on lib/private/Template/SCSSCacher.php
> +	public function resetCache() {
Ah nice :+1: I wasn't aware of that.

2017-03-24 11:11 UTC, juliushaertl commented
Time for review.

2017-03-24 11:11 UTC, juliushaertl commented
@nextcloud/theming

2017-03-24 11:45 UTC, nickvergessen submitted a review, later dismissed

2017-03-24 11:45 UTC, nickvergessen commented on apps/theming/lib/ThemingDefaults.php
> +	 * @param IRootFolder $appData
class needs changing as well

2017-03-26 14:01 UTC, LukasReschke submitted a review, later dismissed
Logo is disappearing with this. Let me try to find the  responsible code :)


GET http://10.211.55.7/stable9//stable9/core/img/logo.svg?v=1 404 (Not Found)

The one /stable9/ seems too much.

2017-03-26 15:04 UTC, LukasReschke commented on apps/theming/lib/ThemingDefaults.php
> +		$variables['image-login-background'] = "'../../".$this->getBackground()."'";
```
/* override styles for login screen in guest.css */
/* line 42, /media/psf/stable9/apps/theming/css/theming.scss */
#header .logo, #header .logo-icon {
  background-size: contain;
  background-image: url(../../..//stable9/core/img/logo.svg?v=1);
}
```

Generated URL is wrong :)

2017-03-26 22:08 UTC, MorrisJobke commented
Failing tests (weirdly there is now a `/owncloud/` in the path 😕 

```
There were 3 failures:
1) OCA\Theming\Tests\ThemingDefaultsTest::testGetLogoDefault
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://localhost/core/img/logo.svg'
+'http://localhost/owncloud/core/img/logo.svg'
/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:443
2) OCA\Theming\Tests\ThemingDefaultsTest::testGetLogoCustom
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://localhost/index.php/apps/theming/logo'
+'http://localhost/owncloud/index.php/apps/theming/logo'
/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:458
3) OCA\Theming\Tests\ThemingDefaultsTest::testGetScssVariables
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'theming-cachebuster' => ''0''
-    'image-logo' => ''http://localhost/index.php/apps/theming/logo''
+    'image-logo' => ''http://localhost/owncloud/index.php/apps/theming/logo''
     'image-login-background' => ''/index.php/apps/theming/logi...round''
     'color-primary' => '#000000'
     'color-primary-text' => '#ffffff'
 )
/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:490
```

2017-04-10 19:51 UTC, rullzer commented
Needs a rebase

2017-04-21 20:42 UTC, MorrisJobke commented
> Needs a rebase

Squashed and rebased, but I haven't tested it.

2017-04-21 20:43 UTC, MorrisJobke commented
Just in case I messed something up I also have a local backup branch available ;)

2017-04-22 09:59 UTC, juliushaertl commented
@MorrisJobke Works as expected. I've just added another commit that ensures that the css files will be reloaded if theming values are changed. Ready for review, I think. @nextcloud/theming

2017-04-24 10:04 UTC, nickvergessen requested changes

2017-04-24 10:04 UTC, nickvergessen commented on apps/theming/lib/ThemingDefaults.php
> +		return $this->urlGenerator->linkToRouteAbsolute('theming.Theming.getLogo') . '?v=' . $cacheBusterCounter;
Breaks HTML mails, will have a look.

2017-04-24 10:24 UTC, nickvergessen approved these changes

2017-04-24 14:15 UTC, MorrisJobke commented
```
There was 1 failure:
1) OCA\Theming\Tests\ThemingDefaultsTest::testGetLogoDefault
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/core/img/logo.svg?v=0'
+'/owncloud/core/img/logo.svg?v=0'
/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:457
```

@nickvergessen Could you have a look?

2017-04-24 19:34 UTC, rullzer commented on apps/theming/tests/ThemingDefaultsTest.php
> +		$this->assertEquals('/core/img/logo.svg?v=0', $this->template->getLogo());
Yeah this breaks because https://github.com/nextcloud/server/blob/master/apps/theming/lib/ThemingDefaults.php#L144 adds the \OC::$WEBROOT but https://github.com/nextcloud/server/blob/master/apps/theming/lib/ThemingDefaults.php#L169 does not.

Which feels very wrong...

2017-04-25 09:44 UTC, nickvergessen commented on apps/theming/tests/ThemingDefaultsTest.php
> +		$this->assertEquals('/core/img/logo.svg?v=0', $this->template->getLogo());
both should add the webroot...

2017-04-25 09:45 UTC, nickvergessen commented on apps/theming/tests/ThemingDefaultsTest.php
> +		$this->assertEquals('/core/img/logo.svg?v=0', $this->template->getLogo());
I adjusted the test

2017-04-25 09:46 UTC, nickvergessen commented on apps/theming/tests/ThemingDefaultsTest.php
> +		$this->urlGenerator = \OC::$server->query(IURLGenerator::class);
why was this replaced anyway... I will revert this as well

2017-04-25 12:34 UTC, jancborchardt commented
@juliushaertl @nickvergessen @rullzer @skjnldsv is there anything specifically blocking it, or anything to change/add? Seems to work well. :)

2017-04-25 13:48 UTC, MorrisJobke commented
Failing test is due to the JS unit problem - see #4494 for a fix.

2017-04-25 13:56 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-04-25 13:56 UTC, merged