Don't count range download in download limit
nextcloud/server pull request #35324
Opened 2022-11-22 10:22 UTC by CarlSchwan

I tried to still count the first or the last range but this is not really reliable since we send two range `0-` at the beginning (one for the preview and one for the video) and the last range `xxxxxxxxx-` is also called multiple times

2022-11-22 10:26 UTC, szaimen commented
The fix looks good to me in general. I wonder if we should revert https://github.com/nextcloud/server/pull/28227 now that this is fixed?

2022-11-22 11:00 UTC, szaimen commented
@nickvergessen I think it would be good if you would also add your concerns on that PR :)

2022-11-22 11:10 UTC, nickvergessen commented
Yeah, I have nothing to say to this. This allows to trick out the download limit completely by just always downloading with range `0-`. Even for text files, documents, images, etc. not only streamed items. Maybe it can be limited to that kind of resources?

2022-11-22 11:17 UTC, skjnldsv requested changes

2022-11-22 11:17 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareController.php
> +		if (!isset($_SERVER['HTTP_RANGE'])) {
Please document the use case

2022-11-22 13:02 UTC, CarlSchwan commented on apps/files_sharing/lib/Controller/ShareController.php
> +		if (!isset($_SERVER['HTTP_RANGE'])) {
Done

2022-11-22 13:53 UTC, skjnldsv commented
> Yeah, I have nothing to say to this. This allows to trick out the download limit completely by just always downloading with range `0-`. Even for text files, documents, images, etc. not only streamed items. Maybe it can be limited to that kind of resources?

@PVince81 since we talked about it this morning.
I think it's ok to not bind this to videos only. What about audio? When does it stop? :see_no_evil: 

The download limit by itself is not a perfect science and we made sure to communicate that. Anyone with decent skills can counter this and download the file then distribute it outside. Even with or without range protection. :shrug:

2022-11-22 16:34 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareController.php
> +				$isVideoAutio = str_starts_with($node->getMimeType(), 'video/') || str_starts_with($node->getMimeType(), 'audio/');
```suggestion
				$isVideoAudio = str_starts_with($node->getMimeType(), 'video/') || str_starts_with($node->getMimeType(), 'audio/');
```

2022-11-22 16:38 UTC, szaimen requested changes
I need an answer on this:
https://github.com/nextcloud/server/pull/35324#issuecomment-1323435010

2022-11-22 16:46 UTC, skjnldsv commented
> The fix looks good to me in general. I wonder if we should revert #28227 now that this is fixed?

Might be a good idea yes

2022-11-22 21:44 UTC, nickvergessen commented
Why that? The activity spam would just come back?
Also with the change in this PR we can't move the activity app over, as it would not create an event anymore when the viewer is used to look at it.

#28227 was only for activities, not for the download limit counter.

2022-12-16 16:08 UTC, PVince81 commented
if possible, let's see if switching to a header "X-NC-Viewer" would work there and have the download limit app ignore such requests: https://github.com/nextcloud/files_pdfviewer/pull/654#issuecomment-1323403799

2024-08-14 10:19 UTC, closed without merging