cURL time out
nextcloud/server pull request #35461
Opened 2022-11-28 14:09 UTC by jlssmt

* Resolves: --

## Summary
Fixed cURL regarding: 
https://help.nextcloud.com/t/curl-error-28-operation-timed-out-after-30000-milliseconds-with-0-bytes-received-federated-nextcloud/113088

## TODO
--

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-11-28 22:04 UTC, kesselb commented
Reason for 30 seconds: https://github.com/nextcloud/server/pull/16972

Afaik, we overwrite the default timeout if necessary, but default should stay 30.

2023-01-11 16:20 UTC, PVince81 commented
would it make sense to make the timeout configurable, specifically for federated shares ?

2023-03-21 10:35 UTC, come-nc requested changes
Increasing timeout here does not feel like a good solution.
If the problem only arise for big files there may be a problem with how the connection is handled. It should start recieving data fast even if the file is big.

2023-09-03 14:16 UTC, nicoduck commented
Since this currently affects me with downloading a big file from a federated share, I'd like to see that as a configuration option.

2023-09-04 09:27 UTC, kesselb commented
Fixed by https://github.com/nextcloud/server/pull/38292

2023-09-04 09:27 UTC, closed without merging

2023-09-04 09:34 UTC, kesselb commented
OCA\Files_Sharing\External\Storage extends OC\Files\Storage\DAV.

Therefore, the value of `davstorage.request_timeout` apply. 

There are additional HTTP requests in `OCA\Files_Sharing\External\Storage.getShareInfo` and `OCA\Files_Sharing\External\Storage.getShareInfo.testRemoteUrl` not using the parent class timeouts. If someone runs into timeouts, feel free to send another pull request and adjust `private $timeout` to `protected $timeout` and use them in the child class.