Update rich-workspace visibility
nextcloud/server pull request #35474
Opened 2022-11-29 05:39 UTC by luka-nextcloud

Signed-off-by: Luka Trovic <luka@nextcloud.com>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-11-30 15:37 UTC, Raudius commented on apps/files/js/newfilemenu.js
> +			let menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
Minor nitpick: this should be `const` instead of `let`

Other than this, PR looks good!

2022-12-05 21:30 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +				shouldShow: actionSpec.shouldShow || (() => true)
```suggestion
				shouldShow: actionSpec.shouldShow,
```

Should be enough as the filter would still include it if it is undefined

2022-12-06 08:56 UTC, luka-nextcloud commented on apps/files/js/newfilemenu.js
> +				shouldShow: actionSpec.shouldShow || (() => true)
The render function looks for `showMenu: true` in order to consider adding the menu item so I think we need this.

2022-12-06 10:26 UTC, max-nextcloud commented
Nice. Cypress is passing. No idea what drone is doing here.

2022-12-08 13:19 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +				shouldShow: actionSpec.shouldShow || (() => true)
Just tested and the suggestion works as the undefined value will evaluate to true with `!item.showMenu` which means that the item is always shown if no showMenu is passed.

2022-12-08 13:20 UTC, juliushaertl requested changes
There is one more thing that I haven't thought of upfront that would be that we don't need an input for the folder description. The new file action should trigger directly on click.

Something like this seems to do the trick there:
```diff
diff --git a/apps/files/js/newfilemenu.js b/apps/files/js/newfilemenu.js
index e38801ac6b4..1d618a1a8c6 100644
--- a/apps/files/js/newfilemenu.js
+++ b/apps/files/js/newfilemenu.js
@@ -81,10 +81,18 @@
                        if (action === 'upload') {
                                OC.hideMenus();
                        } else {
-                               event.preventDefault();
-                               this.$el.find('.menuitem.active').removeClass('active');
-                               $target.addClass('active');
-                               this._promptFileName($target);
+                               var actionItem = _.filter(this._menuItems, function(item) {
+                                       return item.id === action
+                               }).pop();
+                               if (typeof actionItem.useInput === 'undefined' || actionItem.useInput === true) {
+                                       event.preventDefault();
+                                       this.$el.find('.menuitem.active').removeClass('active');
+                                       $target.addClass('active');
+                                       this._promptFileName($target);
+                               } else {
+                                       actionItem.actionHandler();
+                                       OC.hideMenus();
+                               }
                        }
                },

@@ -204,7 +212,8 @@
                                fileType: actionSpec.fileType,
                                actionHandler: actionSpec.actionHandler,
                                checkFilename: actionSpec.checkFilename,
-                               shouldShow: actionSpec.shouldShow || (() => true)
+                               shouldShow: actionSpec.shouldShow,
+                               useInput: actionSpec.useInput,
                        });
                },
```

2022-12-15 14:59 UTC, max-nextcloud commented on apps/files/js/newfilemenu.js
> +        useInput: actionSpec.useInput,
This looks off in terms of indention. I think it uses spaces not tabs.

2022-12-22 09:02 UTC, juliushaertl approved these changes

2023-01-19 13:46 UTC, max-nextcloud requested changes
All in all looks good. Just one confusion with the `shouldShow` parameter.

2023-01-19 13:46 UTC, max-nextcloud commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
If i understand this correctly you want it to show if `item.shouldShow` is not set or it's a function and the function returns true.

If `shouldShow` is false this will still show. If `shouldShow` is true it will not show, right?
I think that's confusing and might cause errors.

Instead i suggest:
```suggestion
			const menuItems = this._menuItems.filter(item => !item.shouldShow?.() ?? true)
```

MDN has docs for the [? operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and the [?? operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing).

2023-01-19 18:36 UTC, luka-nextcloud commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
@max-nextcloud The filter function only returns the entries for which the conditions set are true.
So only the entries for which `shouldShow` is not defined and those for which `shouldShow` is a function that return true will be displayed.

2023-01-19 22:32 UTC, max-nextcloud commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
@luka-nextcloud - what happens if shouldShow is `false` or `true` ?

2023-01-25 14:36 UTC, juliushaertl commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
I'd say the more explicit check if shouldShow is a function makes sense as otherwise passing true or false as values . 

`shouldShow?.()` still seems to trigger an error in that case:

![Screenshot 2023-01-25 at 15 36 25](https://user-images.githubusercontent.com/3404133/214591518-fd69e145-a601-41b6-8581-46c76bfa24ea.png)

2023-01-25 15:05 UTC, luka-nextcloud commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
@max-nextcloud 
First of all, `shouldShow` can not be a bool, it should be a function.
If shouldShow is false, the entry won't be shown.
If shouldShow returns true as a function then it'll be shown.

2023-01-31 08:14 UTC, max-nextcloud approved these changes
Nice to see this finalized.
I still disagree about the way `shouldShow` is handled. But there's no point in arguing about this forever.

2023-01-31 08:18 UTC, max-nextcloud commented on apps/files/js/newfilemenu.js
> +			const menuItems = this._menuItems.filter(item => !item.shouldShow || (item.shouldShow instanceof Function && item.shouldShow() === true))
> `shouldShow?.()` still seems to trigger an error in that case:

Interesting `?.()` seems to only work with undefined - not with false. I learned something today :)

2023-01-31 08:54 UTC, juliushaertl commented
Failures unrelated.

2023-01-31 08:54 UTC, merged