Copy to clipboard with link instead of button
nextcloud/server pull request #35527
Opened 2022-12-01 00:26 UTC by Pytal

Addendum to https://github.com/nextcloud/server/pull/35240

Based on feedback from:
- https://github.com/nextcloud/server/issues/35505#issuecomment-1331743638
- https://github.com/nextcloud/server/pull/35240#issuecomment-1328003979

2022-12-01 00:26 UTC, Pytal commented
/backport to stable25

2022-12-01 08:20 UTC, skjnldsv commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +				:href="shareLink"
We can also use `role="button"` if really necessary

2022-12-01 08:20 UTC, skjnldsv approved these changes

2022-12-01 08:23 UTC, skjnldsv commented
@Pytal Generally speaking, please use the revert action in those cases. So it's clear that this is a revert of a previous commit. 
https://github.com/nextcloud/server/pull/35533

2022-12-01 08:23 UTC, skjnldsv requested changes
@Pytal Generally speaking, please use the revert action in those cases. So it's clear that this is a revert of a previous commit. 
https://github.com/nextcloud/server/pull/35533

2022-12-01 17:38 UTC, Pytal commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +				:href="shareLink"
Needs https://github.com/nextcloud/nextcloud-vue/pull/3532

2022-12-01 17:40 UTC, Pytal commented
> @Pytal Generally speaking, please use the revert action in those cases. So it's clear that this is a revert of a previous commit. #35533

As described in the description this is an addendum to https://github.com/nextcloud/server/pull/35240 not a revert, as it keeps the material design icons

2022-12-02 15:16 UTC, skjnldsv commented
> As described in the description this is an addendum to https://github.com/nextcloud/server/pull/35240 not a revert, as it keeps the material design icons

What about the tests ?

2022-12-02 18:13 UTC, Pytal commented
> What about the tests ?

Since it's in one commit then reverting would also revert what we want to keep, would you suggest reverting the commit then re-adding the changes we want to keep?

2022-12-02 18:17 UTC, skjnldsv commented
Generally speaking, I think it's more clear, when someone is out of context, what really happened if we revert a breaking PR.
Then you can open another PR and add back the changes for the material design icon.
Which are actually not at all what the original PR was designed to change.

If I have to pinpoint something later on and move up the blame history, not being clear that this PR was a revert because of a regression, it's going to make it harder.

Anyway... Not going to debate that further :grin:

2022-12-02 18:32 UTC, Pytal commented
Closing in favour of https://github.com/nextcloud/server/pull/35533 + followup PR with new material design icons

2022-12-02 18:32 UTC, closed without merging