Extend reference API for (future) frontend picker
nextcloud/server pull request #35557
Opened 2022-12-02 12:49 UTC by julien-nc

refs #31667

We forgot something in the specs: the fontend only knows the list of registered widgets to render references. We need more information for the available providers (title, icon etc...) to feed the reference picker. I can think of 2 ways to go:
* provide more information when registering the reference widget in the frontend (feels weird because widgets are just for rendering, the picker stuff should be independent)
* add a new "registerProvider" function to `vue-richtext`
* add an API endpoint to get info on the available providers

I went with the API endpoint. (Or did I miss something obvious?)

* 2 new interfaces:
    * IDiscoverableReferenceProvider for reference providers that can be discovered by the frontend
    * ISearchableReferenceProvider for discoverable ones that support search
* 1 new method to get those providers in ReferenceManager
* 1 new route/controller method

So, a reference provider can support multiple search providers. Thinking out loud: We need to be careful to properly render heterogeneous search results in the frontend.

2022-12-02 14:00 UTC, juliushaertl commented on core/Controller/ReferenceApiController.php
> +	 * @throws NotFoundExceptionInterface
Better catch them in the controller and return a defined error then

2022-12-02 14:00 UTC, juliushaertl commented on lib/private/Collaboration/Reference/ReferenceManager.php
> +			];
Maybe we can move the transition from the objects to the array structure (for the json response) to the controller.

2022-12-02 14:00 UTC, juliushaertl commented on lib/public/Collaboration/Reference/IDiscoverableReferenceProvider.php
> +	public function getIconClass(): string;
Shall we use an icon url instead so that clients can also make use of the API if needed?

2022-12-02 17:16 UTC, julien-nc commented on core/Controller/ReferenceApiController.php
> +	 * @throws NotFoundExceptionInterface
:+1:

2022-12-02 17:17 UTC, julien-nc commented on lib/private/Collaboration/Reference/ReferenceManager.php
> +			];
:+1:

2022-12-02 17:17 UTC, julien-nc commented on lib/public/Collaboration/Reference/IDiscoverableReferenceProvider.php
> +	public function getIconClass(): string;
:+1:

2022-12-05 12:13 UTC, julien-nc commented
@juliushaertl Where can we listen to `RenderReferenceEvent` to provide the provider list as an initial state?

In other words, in server, where can we call (and where does it makes sense to call) `IRegistrationContext::registerEventListener(RenderReferenceEvent::class, ...)` ?

I've seen similar-ish stuff in `lib/base.php` but it didn't feel right/straightforward to put it there...

2022-12-05 21:13 UTC, juliushaertl commented
Same feeling that there could be a better place but I also added one to base.php in the first PR:

2022-12-06 18:31 UTC, julien-nc commented
Thanks, gotta problem though. Just added https://github.com/nextcloud/server/pull/35557/commits/311527e58ffb02604335761265dfaca25b6c2c0a

I don't know why but I can't inject `IInitialState` in the listener class. Server logs say:
```
Could not load event listener service OC\\Collaboration\\Reference\\RenderReferenceEventListener:
Could not resolve initialStateService! Class \"initialStateService\" does not exist. 
Make sure the class is auto-loadable by the Nextcloud server container
```

But `initialStateService` is just the name of the listener class attribute :thinking: 

I don't get why `IReferenceManager` can be injected just fine. I tried to use `\OC::$server->get()` in the  listener's `handle()` method, same problem.

I also tried injecting `\OCP\Server` (which works) and then use it to get `IInitialState`. Slightly better error log message but still no luck:
```
Could not resolve OCP\\AppFramework\\Services\\IInitialState! Class can not be instantiated
```

Any idea?

2022-12-06 20:34 UTC, juliushaertl commented
`IInitialState` is only available within an apps context through the [apps DI container.](https://github.com/nextcloud/server/blob/41b2466d35dd65138c02a3a8934839742020fb92/lib/private/AppFramework/DependencyInjection/DIContainer.php#L333)

However you can inject the `IInitialStateService` directly e.g. as in https://github.com/nextcloud/server/blob/2d98cd1dafb3adbcad5d9af9245f44aec583de2e/lib/private/Template/JSConfigHelper.php#L298

2022-12-07 09:19 UTC, julien-nc commented
@juliushaertl Thanks. Done, works.

I thought `base.php` was in the 'core' app context :grin:.

I didn't try to inject `IInitialStateService` because it's deprecated. Any problem with that?

2022-12-07 19:43 UTC, juliushaertl commented
> I didn't try to inject IInitialStateService because it's deprecated. Any problem with that?

At least there is no replacement yet for core parts that need to inject initial state. And the new interface just wraps the deprecated, so while apps should use the new one, the deprecated one should still be fine within the affected core code base.

2022-12-20 13:35 UTC, julien-nc commented
I don't get the remaining psalm check failure:
```
Error: lib/private/Collaboration/Reference/RenderReferenceEventListener.php:45:21: 
InvalidArgument: Incompatible types found for T 
(OCP\Collaboration\Reference\RenderReferenceEvent is not in OCP\EventDispatcher\Event)
(see https://psalm.dev/004)
```

It's fine for https://github.com/nextcloud/server/blob/4d0403009d8449a88faf7ffc3c6df196c5ac9948/lib/private/Collaboration/Reference/File/FileReferenceEventListener.php#L42-L44

2023-01-19 10:09 UTC, julien-nc commented
@juliushaertl This is ready for review IMO. Nothing more to add for now.

Some recent additions to this PR:
* a new OCS API endpoint to update the "last used timestamp" of a provider
* inject the provider timestamps with initial state on RenderReferenceEvent

2023-01-19 11:09 UTC, juliushaertl commented
Pushed a fix for the psalm error

2023-01-24 11:35 UTC, julien-nc commented
There were changes to the 3rdparty submodule in your fixup commit. It's now rebased and I got rid of the 3rdparty changes.

2023-01-25 11:28 UTC, juliushaertl requested changes
Noticed that I still had some comments piled up from the review, but not sent 🙈

2023-01-26 12:22 UTC, julien-nc commented on lib/private/Collaboration/Reference/ReferenceManager.php
> +			$providerId = preg_replace('/^provider-last-use_/', '', $key);
Let's even use Php 8 stuff (str_starts_with) since Php 7 support was dropped by the server and this won't be backported.

2023-01-26 12:22 UTC, julien-nc commented on lib/private/Collaboration/Reference/ReferenceManager.php
> +		if (array_search($providerId, $providerIds, true) !== false) {
:+1:

2023-01-26 12:22 UTC, julien-nc commented on core/Controller/ReferenceApiController.php
> +		return new DataResponse(['success' => true]);
We could have referenceManager::touchProvider() return a boolean to let the caller if it was successful or not. It's now like that.

2023-01-26 12:22 UTC, julien-nc commented on core/Controller/ReferenceApiController.php
> +		if ($this->userId !== null) {
It does not hurt to still return the info about whether it was successful or not. Done.

2023-01-26 12:23 UTC, julien-nc commented on core/Controller/ReferenceApiController.php
> +	 * @return DataResponse
Since most of us still add phpdoc info even when it is explicitely done in the code, I'm following. But I'm fine with only putting things that add info in phpdoc blocks.

2023-01-26 12:23 UTC, julien-nc commented on core/Controller/ReferenceApiController.php
> +			return $provider->jsonSerialize();
ADiscoverableReferenceProvider now implements JsonSerializable but if we don't serialize manually, it is not done by the DataResponse...

2023-01-26 12:24 UTC, julien-nc commented
@marcelklehr @juliushaertl Thanks for the review.

2023-01-26 12:27 UTC, marcelklehr approved these changes

2023-01-26 21:47 UTC, juliushaertl approved these changes

2023-01-26 21:47 UTC, juliushaertl commented
Rebased and squashed the fixup commits and updated the autoloader.

2023-01-27 11:35 UTC, merged

2023-01-29 08:58 UTC, nickvergessen commented
Please document in https://github.com/nextcloud/server/issues/34692

2023-02-21 13:08 UTC, DaphneMuller commented
hello @julien-nc 
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

2023-05-30 09:45 UTC, DaphneMuller commented
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'pending documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!