Update static code analysis workflow with PHP 8.1
nextcloud/server pull request #35634
Opened 2022-12-06 21:22 UTC by MichaIng

* Resolves: # 

## Summary
Update static code analysis workflow with PHP 8.1 and give the workflow some additional love:
- Align indentation
- Update checkout action
- Use bourne shell syntax and do not force bash (which it's the default anyway)
- Prefer command group over subshell
- Do not use && condition if we want to following command to run in any case
- Single-line run command by using "test" instead of leading bracket and without the need for another subshell

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x]] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-06 21:38 UTC, MichaIng commented
```console
Error: apps/encryption/lib/Crypto/Crypt.php:138:33: InvalidArgument: Argument 1 of openssl_pkey_export expects OpenSSLAsymmetricKey|OpenSSLCertificate|array{OpenSSLAsymmetricKey|OpenSSLCertificate|string, string}|string, resource provided (see https://psalm.dev/004)
Error: apps/encryption/lib/Crypto/Crypt.php:142:43: InvalidArgument: Argument 1 of openssl_pkey_get_details expects OpenSSLAsymmetricKey, resource provided (see https://psalm.dev/004)
Error: apps/encryption/lib/Crypto/Crypt.php:163:13: InvalidReturnType: The declared return type 'resource' for OCA\Encryption\Crypto\Crypt::getOpenSSLPKey is incorrect, got 'OpenSSLAsymmetricKey|false' (see https://psalm.dev/011)
Error: apps/encryption/lib/Crypto/Crypt.php:167:[10](https://github.com/nextcloud/server/actions/runs/3633580255/jobs/6130751067#step:6:11): InvalidReturnStatement: The inferred type 'OpenSSLAsymmetricKey|false' does not match the declared return type 'resource' for OCA\Encryption\Crypto\Crypt::getOpenSSLPKey (see https://psalm.dev/128)
Error: core/Command/Log/Manage.php:193:8: TypeDoesNotContainType: list<string> does not contain false (see https://psalm.dev/056)
```

Probably there is a reason why this is still running with PHP 7.4 🙂: https://www.php.net/manual/en/function.openssl-pkey-export.php#refsect1-function.openssl-pkey-export-changelog

Does it break PHP 7.4 support when updating to the new classes, while it is backwards compatible with the old classes?

Not sure whether its worth it to add these errors to the baseline, or leaving it at PHP 7.4 until support is dropped (which is probably done already with NC26)?

2022-12-07 09:05 UTC, CarlSchwan commented
I would keep 7.4 at least till we drop it (hopefully soon)

What do you think @come-nc ?

2022-12-07 10:44 UTC, MichaIng commented
It probably even marks sense to check against the oldest supported PHP version, since newer versions are usually/obviously backwards-compatible. The workflow was however set to use PHP 7.4 when it was the newest supported version, before PHP 8.0 was even released.

Let me know, then I'll revert, so only the other minor updates are done.

_Self-reminder: Redo and don't forget `git add` for showing the correct `build/psalm-baseline-ocp.xml` diff in last line._

2022-12-08 08:56 UTC, come-nc commented
> Does it break PHP 7.4 support when updating to the new classes, while it is backwards compatible with the old classes?

It’s not different classes it’s different object types, resources were turned into objects by PHP. This is not backward compatible so we have to wait out until the resource-using versions of PHP are dropped before being able to type correctly. See https://php.watch/articles/resource-object

Sadly 7.4 support is not officially dropped yet, even on master, so I would say go back to 7.4 is the easiest.
When we drop it we bump to 8.0 and fix the typing.

On the rest of the changes, I have no strong opinion I do not really understand it.
But I would like to see those changes in https://github.com/nextcloud/.github and use those here if possible.
It may require a bit trickery since current yml in there is for applications, and not core. But it would be un improvement to have a common workflow for both.

2022-12-09 14:52 UTC, MichaIng commented
Okay, I'll revert that. Ah, I didn't know about the templates repo yet, but cannot find this workflow or parts of it inside. Do you mean it should be added?

2022-12-12 09:14 UTC, come-nc commented
> Okay, I'll revert that. Ah, I didn't know about the templates repo yet, but cannot find this workflow or parts of it inside (aside of psalm test, but quite different). Do you mean it should be added?

Ok, so I spoke too soon and since my last comment support for 7.4 was actually dropped officially for master…
But it does not have to be done in this PR it can happen separately.

Regarding nextcloud/.github, yes for static analysis this repo is not using a workflow from there, which is what I would’ve like to fix if possible. There is a psalm template in there but tailored for applications I think, maybe it can be adapted to support both applications and server?

2022-12-12 09:16 UTC, nickvergessen commented
Psalm template is at https://github.com/nextcloud/.github/blob/master/workflow-templates/psalm.yml
But for apps it's much simpler as we don't have 3rdparty to checkout etc.

2022-12-12 09:33 UTC, MichaIng commented
This one could be simplified as well. E.g. the last two steps are informational only. The baseline diff  (removals) are covered by the automatic base line update workflow and if there is a positive diff, Psalm will fail and show the diff, isn't it?

2022-12-16 17:17 UTC, ChristophWurst commented on .github/workflows/static-code-analysis.yml
> +          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
`submodules: true` is sufficient: https://github.com/actions/checkout#usage

2022-12-18 05:18 UTC, MichaIng commented on .github/workflows/static-code-analysis.yml
> +          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
`submodules: recursive` to preserve the current behaviour, isn't it?

2023-01-12 15:13 UTC, ChristophWurst commented on .github/workflows/static-code-analysis.yml
> +          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
Whatever gets the job done :)

2023-01-13 07:42 UTC, ChristophWurst approved these changes

2023-01-16 08:47 UTC, come-nc commented
Please see https://github.com/nextcloud/server/pull/34997 which contains changes to this workflow already

2023-01-16 08:48 UTC, come-nc requested changes
:no_entry_sign:

2023-01-16 12:46 UTC, closed without merging