Invert header if primary is bright and background disabled
nextcloud/server pull request #35666
Opened 2022-12-08 08:48 UTC by skjnldsv

Fix #35664

2022-12-08 08:56 UTC, PVince81 approved these changes
:+1:

2022-12-08 10:10 UTC, skjnldsv commented on apps/theming/lib/Themes/CommonThemeTrait.php
> +			$variables['--color-background-plain'] = $this->defaultPrimaryColor;
This change is intentional.
We're in the admin section, we should use `defaultPrimaryColor` instead of `primaryColor`
If logged in, this var will be overruled below in the user section

2022-12-08 14:19 UTC, artonge requested changes

2022-12-08 14:20 UTC, artonge commented on apps/theming/lib/Themes/CommonThemeTrait.php
> +			$variables['--color-background-plain'] = $this->defaultPrimaryColor;
Could you explain their differences ?

2022-12-08 14:51 UTC, skjnldsv commented on apps/theming/lib/Themes/CommonThemeTrait.php
> +			$variables['--color-background-plain'] = $this->defaultPrimaryColor;
defaultPrimaryColor = admin defined, instance-wide
primaryColor = user, active for current session

2022-12-08 15:14 UTC, artonge approved these changes

2022-12-08 18:04 UTC, Pytal approved these changes

2022-12-08 21:28 UTC, merged

2022-12-08 21:28 UTC, skjnldsv commented
Failure unrelated




```
And I see that the contact "user0" in the Contacts menu is not shown                                                      # ContactsMenuContext::iSeeThatTheContactInTheContactsMenuIsNotShown()
158 | Failed asserting that true is false.
```
<br class="Apple-interchange-newline">

2023-07-06 19:25 UTC, skjnldsv commented on cypress/e2e/theming/admin-settings.cy.ts
> +describe.only('Remove the default background with a bright color', function() {
```suggestion
describe('Remove the default background with a bright color', function() {
```

:roll_eyes:

2023-07-06 19:34 UTC, artonge commented on cypress/e2e/theming/admin-settings.cy.ts
> +describe.only('Remove the default background with a bright color', function() {
And now, everybody knows

2023-07-06 19:43 UTC, skjnldsv commented on cypress/e2e/theming/admin-settings.cy.ts
> +describe.only('Remove the default background with a bright color', function() {
I'll take the walk of shame :see_no_evil:

2023-07-06 19:54 UTC, skjnldsv commented on cypress/e2e/theming/admin-settings.cy.ts
> +describe.only('Remove the default background with a bright color', function() {
https://github.com/nextcloud/server/pull/39203