some sharing settings
nextcloud/server pull request #3567
Opened 2017-02-21 17:24 UTC by schiessle

allow the administrator to define a min length of the search string before we start auto-completion and a max number of results per search query.

2017-02-21 17:41 UTC, MorrisJobke commented
Nonono.... why? this is something that doesn't make sense. Why should an admin be able to set the max results to be 100? or 1? From an UX perspective this could go really wrong and for no real reason.


What is the story behind this?

2017-02-21 17:47 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$threshold = $this->config->getSystemValue('sharing.minSearchStringLength', 0);
0 is not the default we had before. Because this is handled in JS.

2017-02-21 17:48 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$maxResults = $this->config->getSystemValue('sharing.maxAutocompleteResults', 0);
we should have a max setting here. It doesn't make sense to allow to return 50 or 100 results.

2017-02-21 17:49 UTC, MorrisJobke commented on config/config.sample.php
> + * Default is unlimited (value set to 0).
Please add a "only only only change this if you really really know what you are doing" ...

2017-02-21 17:50 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +			return new Http\DataResponse($this->result);
No test coverage for this.

2017-02-21 17:50 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +			$perPage = min($perPage, $maxResults);
Not tested.

2017-02-21 17:50 UTC, MorrisJobke requested changes
:-1:

2017-02-21 17:53 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$threshold = $this->config->getSystemValue('sharing.minSearchStringLength', 0);
See this as in: It's likely that this will not work at all, because the search is triggered in JS.

2017-02-21 18:11 UTC, schiessle commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$threshold = $this->config->getSystemValue('sharing.minSearchStringLength', 0);
It is default, before we searched already for the first character -> default min length = 0

2017-02-21 18:13 UTC, schiessle commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$maxResults = $this->config->getSystemValue('sharing.maxAutocompleteResults', 0);
No, if the administration set the max to 100 but someone asks for 200 we should just return 100 because this was the max set b the administration. The max is a hard requirement not just a "suggestion"

2017-02-21 18:14 UTC, schiessle commented on config/config.sample.php
> + * Default is unlimited (value set to 0).
Sorry, that's in no way a dangerous setting so I will not add a warning. Having such warning only lead user to ignore serious warnings

2017-02-21 18:15 UTC, schiessle commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +			return new Http\DataResponse($this->result);
No test coverage for the whole method

2017-02-21 18:17 UTC, schiessle commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +			$perPage = min($perPage, $maxResults);
Same here. If we accepted the whole method without tests it is disproportionate to ask for tests for the whole method just because I added 6 lines. But I can move this lines to a separate method and write tests for them of you really want tests for reading a configuration value

2017-02-21 19:45 UTC, nickvergessen requested changes

2017-02-21 19:45 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +			return new Http\DataResponse($this->result);
please fully include this class

2017-02-21 19:45 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$maxResults = $this->config->getSystemValue('sharing.maxAutocompleteResults', 0);
cast to int for better/save php behaviour

2017-02-21 19:45 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$threshold = $this->config->getSystemValue('sharing.minSearchStringLength', 0);
cast to int for better/save php behaviour

2017-02-21 19:46 UTC, LukasReschke commented on config/config.sample.php
> + * Default is unlimited (value set to 0).
I find that setting pretty useless tbh. Fully agree with Morris.

2017-02-21 23:11 UTC, MorrisJobke commented
I'm fine with the UX part now:

<img width="298" alt="bildschirmfoto 2017-02-21 um 13 01 06" src="https://cloud.githubusercontent.com/assets/245432/23189456/991c0228-f858-11e6-90ad-6d53e86e9654.png">

<img width="291" alt="bildschirmfoto 2017-02-21 um 13 01 13" src="https://cloud.githubusercontent.com/assets/245432/23189461/9e2599c8-f858-11e6-82f5-fe9211d24ac6.png">

<img width="643" alt="bildschirmfoto 2017-02-21 um 17 05 40" src="https://cloud.githubusercontent.com/assets/245432/23189486/b0f8abee-f858-11e6-85d9-9da8c09d92e4.png">

<img width="694" alt="bildschirmfoto 2017-02-21 um 17 05 48" src="https://cloud.githubusercontent.com/assets/245432/23189491/b4f4893e-f858-11e6-911a-9fb3776992bb.png">

2017-02-21 23:12 UTC, MorrisJobke commented on config/config.sample.php
> + * Default is unlimited (value set to 0).
Fine by me

2017-02-21 23:25 UTC, MorrisJobke approved these changes
I'm fine with this now 👍

2017-02-22 14:15 UTC, nickvergessen approved these changes

2017-02-22 14:16 UTC, nickvergessen commented
My code comments are resolved. I abstain from the content of the PR however. I don't think the settings are really of high-use

2017-02-22 14:22 UTC, jancborchardt reviewed
This is not exposed in the admin settings, only in the config.php, right? (Cause it shouldn’t be …)

2017-02-22 14:22 UTC, jancborchardt commented on core/js/sharedialogview.js
> +					'At least {count} character are needed for autocompletion',
»_is_ needed«, right?

2017-02-22 15:29 UTC, schiessle commented on core/js/sharedialogview.js
> +					'At least {count} character are needed for autocompletion',
thanks... fixed!

2017-02-22 15:30 UTC, merged