Edits made
nextcloud/server pull request #35691
Opened 2022-12-09 05:58 UTC by clivinghouse

Signed-off-by: chl5158 <79345446+clivinghouse@users.noreply.github.com>

## Summary
This is my first pull req. I have skimmed over the requirements to contribute to this project, I believe I have met the projects requirements. Please let me know if I have missed anything! I have only made some grammatical edits. Couple added periods here, some sentence restructuring there.

## TODO

- [ ] Review of grammar.
- [ ] make sure edits don't misconstrue previous meanings.

## Checklist

~~- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)~~ **N/A**
- [X] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
~~- [X ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included~~ **N/A**
~~- [ ] Screenshots before/after for front-end changes~~ **No Changes**
~~- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required~~ Directly changing docs N/A
~~- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)~~ N/A

2022-12-09 19:51 UTC, clivinghouse commented
@szaimen thank you for the title improvement!

2022-12-12 09:00 UTC, come-nc commented on README.md
> +Third-party components are handled as git submodules which have to be initialized first. Git checkout invoking `git submodule update --init` or a similar command is needed, for details see [Git docum
The sentence lost its meaning, it was only missing a comma after «invoking»

2022-12-12 13:52 UTC, clivinghouse commented
@come-nc, thank you for taking the time to look over my pull request. I am going to take a look at your corrections in a bit. I have to complete my finals today. Again, thank you for looking over this!

2022-12-12 16:44 UTC, clivinghouse commented on README.md
> +You can also [get support from Nextcloud](https://nextcloud.com/support)!
My thoughts for this change was, since the link takes you to the support page of Nextcloud, it is support from next cloud. the supporting documents linked on the page are from the next cloud community. It's semantically indifferent to me i just thought it made sense that the help was coming from the community. What are your thoughts?

2022-12-12 16:49 UTC, clivinghouse commented on README.md
> +- [🐘 Mastodon](https://mastodon.xyz/@nextcloud)
This is valid, they are both valid. i guess i just like it more. it's personal choice. if you don't like it that is ok. we can keep it the original. 
```suggestion
* [📋 Forum](https://help.nextcloud.com)
* [👥 Facebook](https://www.facebook.com/nextclouders)
* [🐣 Twitter](https://twitter.com/Nextclouders)
* [🐘 Mastodon](https://mastodon.xyz/@nextcloud)
```

2022-12-12 17:12 UTC, clivinghouse reviewed
Waiting for feedback from @come-nc.

2022-12-12 17:12 UTC, clivinghouse commented on README.md
> +- 📦 Buy one of our awesome [**devices** ](https://nextcloud.com/devices/) with Nextcloud preinstalled.
Oh my bad. then does this seem fair to change to?
```suggestion
- 📦 Buy one of the awesome [**devices listed here**](https://nextcloud.com/devices/) with Nextcloud preinstalled.
```

2022-12-12 17:12 UTC, clivinghouse commented on README.md
> +and much more... 😍
This is valid. I guess i just like it more. it's personal choice. if you don't like it that is ok. we can keep it the original.
```suggestion
There are many ways to contribute, of which development is only one! Find out [how to get involved](https://nextcloud.com/contribute/). This includes a translator, designer, tester, helping others, and much more! 😍
```
I did change it a little to make it easier to read.

2022-12-12 17:12 UTC, clivinghouse commented on README.md
> +Third-party components are handled as git submodules which have to be initialized first. Git checkout invoking `git submodule update --init` or a similar command is needed, for details see [Git docum
I can see your point.
```suggestion
Third-party components are handled as git submodules which have to be initialized first. So aside from the regular git checkout invoking, `git submodule update --init` or a similar command is needed. For details see [Git documentation](https://git-scm.com/docs/user-manual).
```
Do you agree to adding a link to the git documentation?

2023-02-01 17:23 UTC, clivinghouse commented
since this was mentioned in the next release do i need to have this reviewed again @come-nc?

2023-02-02 13:57 UTC, come-nc commented
> since this was mentioned in the next release do i need to have this reviewed again @come-nc?

No, readme is not really tied to releases to my knowledge.

2023-02-02 18:31 UTC, jospoortvliet commented on README.md
> +You can also [get support from Nextcloud](https://nextcloud.com/support)!
I agree with Come it's a little confusing. You can get support from multiple sources, from Nextcloud GmbH to Nextcloud-community-members or, well, your neighboor or something ;-)

But it's support for Nextcloud-the-product in all cases. So I'd rather say that.

2023-02-02 18:35 UTC, jospoortvliet commented on README.md
> +**A safe home for all of your data.**
```suggestion
**Regain control over your data**
```
Let's use the slogan from our front page, not this super old one! Fresh and tasty.

2023-02-02 18:36 UTC, jospoortvliet commented on README.md
> +Do you want to learn more about how you can use Nextcloud to access, share and protect your files, calendars, contacts, communication and more at home and/or in your organization? [**Learn about all
```suggestion
Do you want to learn more about how you can use Nextcloud to access, share and protect your files, calendars, contacts, communication and more at home and/or in your organization? [**Learn about all our Features**](https://nextcloud.com/hub/).
```
Good, but we should also update that link - athome is gone, let's just point to the product page - hub!

2023-02-02 18:38 UTC, jospoortvliet commented on README.md
> +- ☑️ [**Simply sign up**](https://nextcloud.com/signup/) with one of our providers either through our website or through our apps directly.
No, the change is correct, it's OUR apps (android, iOS, desktop) through which you can sign up with a third party provider ;-) So this is actually good.

2023-02-02 18:39 UTC, jospoortvliet commented on README.md
> +- 🖥 [**Install**](https://nextcloud.com/install/#instructions-server) a server by yourself on your hardware.
Yeah, I think thats fine honestly. Everything is appliances these days, ppl expect a docker. And we deliver :D

2023-02-02 20:47 UTC, jospoortvliet commented on README.md
> +Third-party components are handled as git submodules which have to be initialized first. Git checkout invoking `git submodule update --init` or a similar command is needed, for details see [Git docum
But in what you propose, you put the comma wrong. People need to invoke the command 'git submodule' etc, so the coma should be after 'checkout', not after invoking:

> So aside from the regular git checkout, invoking `git submodule update --init` or a similar command is needed. For details see [Git documentation](https://git-scm.com/docs/user-manual)

2023-02-02 20:48 UTC, jospoortvliet requested changes
See my feedback - once merged/improved, I'm good with this and it can be merged!

2023-02-03 17:50 UTC, clivinghouse commented on README.md
> +Third-party components are handled as git submodules which have to be initialized first. Git checkout invoking `git submodule update --init` or a similar command is needed, for details see [Git docum
```suggestion
Third-party components are handled as git submodules which have to be initialized first. So aside from the regular git checkout, invoking `git submodule update --init` or a similar command is needed. For details see [Git documentation](https://git-scm.com/docs/user-manual).
```

so like this @jospoortvliet?

2023-02-03 17:53 UTC, clivinghouse commented on README.md
> +- ☑️ [**Simply sign up**](https://nextcloud.com/signup/) with one of our providers either through our website or through our apps directly.
```suggestion 
☑️ [**Simply sign up**](https://nextcloud.com/signup/) with one of our providers either through our website or through apps (Android, iOS, Desktop) directly.
```

would this be good then? @jospoortvliet

2023-03-26 18:23 UTC, jospoortvliet approved these changes

2023-11-10 04:24 UTC, closed without merging

2023-11-10 07:38 UTC, jospoortvliet commented
thanks @clivinghouse !!