According to issue #3553, the default logtimezone is always UTC
nextcloud/server pull request #3576
Opened 2017-02-22 12:35 UTC by robert-scheck

2017-02-22 22:25 UTC, MorrisJobke commented
Then I would go for remove this setting at all. cc @LukasReschke @nickvergessen Okay?

2017-02-22 22:29 UTC, nickvergessen commented
What? No? you can overwrite it in the config file. It's just set to UTC by default. No need to remove the setting. We can remove the `set()` call, yes. But not the config option.

2017-02-22 22:30 UTC, MorrisJobke commented on lib/private/Setup.php
> +			$config->setSystemValue('logtimezone', 'UTC');
Okay. Right - remove this entry just completely. The default is UTC anyways on all other calls.

2017-02-22 22:30 UTC, MorrisJobke requested changes
See comment

2017-02-23 14:52 UTC, LukasReschke commented
@MorrisJobke @nickvergessen Happier now? :)

2017-02-23 15:09 UTC, nickvergessen approved these changes

2017-02-23 21:36 UTC, MorrisJobke approved these changes

2017-02-23 21:36 UTC, merged