Rename SabrePublicPluginEvent to BeforeSabrePubliclyLoadedEvent
nextcloud/server pull request #35789
Opened 2022-12-15 16:29 UTC by julien-nc

And run build/autoloaderchecker.sh

refs #35621 #35784

2022-12-15 16:30 UTC, ChristophWurst requested changes
New file missing?

2022-12-15 16:30 UTC, ChristophWurst commented on apps/updatenotification/composer/composer/installed.php
> -        'reference' => 'e35bcc9381246a8ec3da96e78e9771ef6044a6d4',
not stricly necessary. composer is a bit weird with those references. IIRC they change every time you commit …

2022-12-15 16:35 UTC, ChristophWurst requested changes

2022-12-15 16:35 UTC, ChristophWurst commented on lib/public/BeforeSabrePubliclyLoadedEvent.php
```suggestion

/**
 * <description of the event>
 *
 * @since 26.0.0
 */
```

2022-12-15 16:35 UTC, julien-nc commented on apps/updatenotification/composer/composer/installed.php
> -        'reference' => 'e35bcc9381246a8ec3da96e78e9771ef6044a6d4',
Meaning we should rollback those changes?

2022-12-15 16:35 UTC, ChristophWurst commented on apps/updatenotification/composer/composer/installed.php
> -        'reference' => 'e35bcc9381246a8ec3da96e78e9771ef6044a6d4',
you can but don't have to

2022-12-15 16:44 UTC, ChristophWurst approved these changes

2022-12-16 08:51 UTC, julien-nc commented
/backport to stable25

2022-12-16 08:52 UTC, julien-nc commented
/backport to stable24

2022-12-16 08:52 UTC, julien-nc commented
/backport to stable23

2022-12-16 10:40 UTC, PVince81 approved these changes
:+1:

2022-12-16 10:40 UTC, merged

2023-01-16 10:33 UTC, nickvergessen commented
Please document in https://github.com/nextcloud/server/issues/34692

2023-01-23 09:52 UTC, julien-nc commented
> Please document in #34692

:+1: Done

2023-02-21 13:04 UTC, DaphneMuller commented
hello @julien-nc 
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

2023-05-30 09:45 UTC, DaphneMuller commented
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'pending documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!