Replace custom tooltips with native one for files sharing
nextcloud/server pull request #35785
Opened 2022-12-15 14:46 UTC by JuliaKirschenheuter

**Resolves only js/jQuery part of: https://github.com/nextcloud/server/issues/35654**

## Summary

- [ ]  Replace custom tooltips with native ones in js files for files_sharing
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-16 07:54 UTC, JuliaKirschenheuter commented
I was not able to test: 

https://localhost/apps/files/?dir=/&view=deletedshares
https://localhost/apps/files/?dir=/&view=pendingshares

Reviewers: please help me with it

2022-12-16 08:02 UTC, ChristophWurst commented
> Reviewers: please help me with it

Could you tell us what to test exactly?

2022-12-16 08:04 UTC, ChristophWurst requested changes

2022-12-16 08:04 UTC, ChristophWurst commented on apps/files_sharing/js/files_drop.js
> +			$('[data-toggle="tooltip"]')
drop this line

2022-12-16 08:04 UTC, ChristophWurst commented on apps/files_sharing/js/files_drop.js
> +			$('[data-toggle="tooltip"]')
same

2022-12-16 08:04 UTC, ChristophWurst commented on apps/files_sharing/src/share.js
> +			var html = '<span class="remoteAddress" title="' + text(tooltip) + '">'
where does `text` come from and what does it do?

2022-12-16 10:09 UTC, JuliaKirschenheuter commented on apps/files_sharing/src/share.js
> +			var html = '<span class="remoteAddress" title="' + text(tooltip) + '">'
was a misconception. reverting

2022-12-16 10:37 UTC, PVince81 approved these changes
:+1:

2022-12-21 14:52 UTC, ShGKme reviewed
It looks good to me.
I have checked that `.tooltip()` method is not used anywhere else.

It doesn't brakes anything, but maybe also remove `data-toggle="tooltip"` attribute from HTML templates. This attr is not used now.

2022-12-21 14:52 UTC, ShGKme commented on apps/files_sharing/js/files_drop.js
>  		},
Maybe also remove this attribute from HTML templates? It is not used anymore.
https://github.com/nextcloud/server/blob/master/apps/files_sharing/js/templates/files_drop.handlebars#L1

2022-12-21 15:33 UTC, JuliaKirschenheuter commented on apps/files_sharing/js/files_drop.js
>  		},
done, thank you!

2022-12-21 17:07 UTC, ShGKme approved these changes
👍

2022-12-22 08:52 UTC, PVince81 approved these changes
:+1:

2022-12-22 08:53 UTC, PVince81 commented
@JuliaKirschenheuter in this specific case, please recompile by running `./build/compile-handlebars-templates.sh`
it's a rare case because we usually don't touch the legacy handlebars templates

2022-12-23 09:07 UTC, merged

2022-12-28 13:35 UTC, ChristophWurst commented
/backport to stable25