Avoid using the word 'password' in the APP_TOKEN_CREATED activity
nextcloud/server pull request #35820
Opened 2022-12-19 11:50 UTC by julien-nc

The activity message `You created app password "{token}"` can make some users freak out because they might think they produced something insecure to access their account.

What do you think?

2022-12-19 11:55 UTC, artonge reviewed
Not sure about 'sessions', but 'password' does indeed not reflect what it actually is.
Maybe @nimishavijay or @jancborchardt have an opinion ?

2022-12-19 12:26 UTC, julien-nc commented
@artonge Thanks for the remark. I used "session" because app passwords are listed in the "Devices & sessions" block of the user security settings.

2022-12-22 08:03 UTC, miaulalala requested changes, later dismissed

2022-12-22 08:03 UTC, miaulalala commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
why not use the wording you used in the ticket? 
```suggestion
				$subject = $this->l->t('You created a session with "{token}"');
```

2022-12-27 10:24 UTC, julien-nc commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
@miaulalala Because I realized "You created a session with DEVICE_NAME" is not completely accurate as you can manually create app passwords and give them an arbitrary name. App passwords can be created in many other contexts than a client's login flow.
So this message is more generic.
What do you think?

2022-12-27 14:41 UTC, miaulalala commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
hm yes it makes sense from a dev perspective, but it feels like a grammatical error if you don't have the technical background. I leave the decision up to you :)

2022-12-27 22:31 UTC, nimishavijay commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
I think it can be useful to have the wording "app password" in the activity to help people relate to the action in settings, but you are right that seeing `You created the app password "Samsung"` is a bit alarming because it makes me think the password here is "Samsung". 

What do you think about: `You created an app password for the session [session name]` ?

2022-12-28 10:02 UTC, miaulalala commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
Or how about we specifically say it's a label? ` You created an app password with session name [session name]`.

2023-01-02 09:42 UTC, julien-nc commented on apps/settings/lib/Activity/Provider.php
> +				$subject = $this->l->t('You created the session "{token}"');
How about a mix of both your suggestions?
`You created an app password for a session named "{token}"`

2023-01-02 14:07 UTC, nimishavijay approved these changes

2023-01-02 15:22 UTC, miaulalala approved these changes

2023-01-02 15:31 UTC, merged

2023-01-02 15:33 UTC, julien-nc commented
@miaulalala As it's not a security fix but still something that makes some users feel their account is insecure, do we backport to 25?

2023-01-09 09:52 UTC, jancborchardt commented
Doesn't this make it sound more technical and even scarier? Is there no standard for a way to call these things (I thought it was "app passwords")? :)