Implement occ maintenance:mode --check-if-disabled
nextcloud/server pull request #35830
Opened 2022-12-19 22:18 UTC by leegarrett

Signed-off-by: Lee Garrett <lgarrett@rocketjump.eu>

* Resolves: # #35704

## Summary
Add a parameter that can be used in scripts. Returns 0 when there is no maintenance mode, and 1 if there is.

## TODO

- [ ] Test coverage?

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-20 08:14 UTC, CarlSchwan approved these changes

2022-12-20 08:32 UTC, skjnldsv requested changes
I find the working confusing
Maintenance mode is not "disabled", it's either `on` or `off`.
The meaning is different

2022-12-20 10:14 UTC, leegarrett commented
> I find the working confusing Maintenance mode is not "disabled", it's either `on` or `off`. The meaning is different

I'm open for a different wording. `--check-if-off`? `--is-off`?

2022-12-20 10:25 UTC, leegarrett commented
I just used the wording from similar calls, btw:
```
www-data@nextcloud:~/nextcloud$ php ./occ maintenance:mode
Maintenance mode is currently disabled
```

2022-12-20 10:44 UTC, MichaIng commented
What do you think about making it a little shorter, like `--is-disabled`, or also inverted `--is-enabled` (so true is "enabled", probably slightly more intuitive)?

2022-12-20 10:48 UTC, MichaIng commented
I like the short variant `--is-disabled` or `--is-off`. Not sure whether "disabled" is so bad, not only as it's used by CLI output as well, but also I personally use it. But I'm no native English speaker.

Also probably `--is-enabled`/`--is-on` is a little more intuitive, so true is "enabled"/"on"?

2022-12-20 11:12 UTC, leegarrett commented
> I like the short variant `--is-disabled` or `--is-off`. Not sure whether "disabled" is so bad, not only as it's used by CLI output as well, but also I personally use it. But I'm no native English speaker.
> 
> Also probably `--is-enabled`/`--is-on` is a little more intuitive, so true is "enabled"/"on"?

I'd also avoid negations is settings/options. Maybe `--is-normal-mode`? No idea what the opposite of maintenance mode is called in nextcloud terminology.

2022-12-20 11:36 UTC, JojoBr0 commented
> > I find the working confusing Maintenance mode is not "disabled", it's either `on` or `off`. The meaning is different
> 
> I'm open for a different wording. `--check-if-off`? `--is-off`?

How about `--status` ?

`0` means maintenance:mode is off
`1` means maintenance:mode is on

2022-12-20 15:50 UTC, skjnldsv commented
> --status

Seems like a good idea? What do you all prefer?
If you all are ok with `--check-if-disabled`, I don't mind that much, and we can merge as is :)

2022-12-21 03:43 UTC, MichaIng commented
Mi fear that with `--status` some would need to regularly lookup or test whether `true` is on or off 😄, hence prefer one self-explaining in this regards.

I'm personally for `--is-on`, short, no negation and it's clear that true means "on". And in the same turn or dedicated PR, some CLI and web UI outputs can be aligned so that maintenance mode is either "on" or "off" instead of "enabled"/"disabled", following `--on`/`--off` as well.

2022-12-21 13:43 UTC, leegarrett commented
After some pondering I'm also throwing `--is-up` into the ring. This avoids any negation, and refers to "up", as opposed to being "down for maintenance". What do y'all think about this?

2022-12-21 14:20 UTC, skjnldsv commented
> I'm personally for `--is-on`, short, no negation and it's clear that true means "on". And in the same turn or dedicated PR, some CLI and web UI outputs can be aligned so that maintenance mode is either "on" or "off" instead of "enabled"/"disabled", following `--on`/`--off` as well.

I second that, `occ maintenance:mode --is-on` is straightforward and self explanatory

2022-12-22 03:15 UTC, MichaIng commented
> So, the server is up for maintenance? 🙈

The same possible confusion came to my mind: IMHO, it should be as clear as possible whether on/up refers to Nextcloud (up == maintenance off) or the maintenance mode (up/on == Nextcloud down). Since currently `maintenance:mode` command names and output all refers to the maintenance mode (`on`/`enabled` == Nextcloud down), that should be kept, at best re-using the same wording (`on`/`off` instead of `up`/`down`) to rule out any confusion.

2022-12-22 16:01 UTC, leegarrett commented
How about `./occ status --rc-only`? 0 for running fine, 1 for maintance mode, and we have 2-254 for any other future conditions that could mean degraded operation.

2022-12-26 14:09 UTC, skjnldsv commented
> occ maintenance:mode --is-on

Different goals and discussion

Can you adjust this PR to `occ maintenance:mode --is-on` please? :)

2022-12-26 14:11 UTC, skjnldsv commented
Ah, I see https://github.com/nextcloud/server/pull/35873

They serve different purpose IMHO, so I would keep both (one is api-oriented, while this one is human-oriented)

2022-12-27 08:43 UTC, leegarrett commented
> Ah, I see #35873
> 
> They serve different purpose IMHO, so I would keep both (one is api-oriented, while this one is human-oriented)

Both PRs are intended to be used by machines, not humans. I retract this PR over #35873, as the latter is more expandable in the future.

2022-12-28 01:36 UTC, closed without merging