Modify user_ldap checkPassword to not fetch records from ldap each time because of extremely high CPU usage!
nextcloud/server pull request #35867
Opened 2022-12-22 11:45 UTC by akhil1508

## Summary
- Currently on each `checkPassword` call, [the function `getLDAPUserByLoginName` is called](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L180)
- This calls `fetchListOfUsers` which is defined [here](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/Access.php#L858)
- So on each authentication request:
  - there is first an admin bind to LDAP(if not already existing)
  - a search request to LDAP
  - a bunch of SQL UPDATEs from calling [`batchApplyUserAttributes`](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/Access.php#L892)
  - [a user BIND to LDAP](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L201) to check if credentials are valid
 

- DAV mobile clients(for example [DAVx5](https://github.com/bitfireAT/davx5-ose)) don't support token auth or oauth yet. This means that they pass the username and password on every single sync request
- We have an NC instance serving around 100 DAV sync requests every second
- For every sync request the LDAP logs look like(admin bind + search for user):
```
conn=1687813954 fd=21 ACCEPT from IP=*** (IP=***)
conn=1687813954 op=0 BIND dn="***" method=128
conn=1687813954 op=0 BIND dn="***" mech=SIMPLE bind_ssf=0 ssf=0
conn=1687813954 op=0 RESULT tag=97 err=0 qtime=0.000014 etime=0.000156 text=
conn=1687813954 op=1 SRCH base="***" scope=2 deref=0 filter="***"
conn=1687813954 op=1 SRCH attr=entryuuid nsuniqueid objectguid guid ipauniqueid dn uid samaccountname memberof 
conn=1687813954 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000027 etime=0.000332 nentries=1 text=
```
- followed by BIND(to check user credentials)
```
conn=1687813956 fd=51 ACCEPT from IP=*** (IP=***)
conn=1687813956 op=0 BIND dn="***" method=128
conn=1687813956 op=0 BIND dn="***" mech=SIMPLE bind_ssf=0 ssf=0
conn=1687813956 op=0 RESULT tag=97 err=0 qtime=0.000012 etime=0.004391 text=
```
- CPU Usage by openldap is extremely high! CPU usage by database is similarly extremely high but lower compared to LDAP

### Proposed solution here

- Get username and dn from cache if existing
  - Use the [loginName2UserName](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L117) function that will fetch the ldap record and update attributes if it is not in cache
- Check credentials with BIND but don't process attributes again 
  - [`$user->processAttributes`](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L206) here seems redundant as it is already done during the `getLDAPUserByLoginName` function call
- Will save ~0.5ms per auth request if user already cached
  - Doesn't sound like too big a deal but with 100 auth requests per second, this can definitely help the load issue
- Will also avoid  ~12 SQL UPDATE operations on each authentication request
  - ~6 if user is not cached yet 

Please do let me know if there are any pitfalls to this and if the ldap record fetching and processing on every single authentication request happens for a reason..

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-02 17:11 UTC, come-nc commented
Hello, thanks for looking into this!

> ### Proposed solution here
> * Get username and dn from cache if existing
>   
>   * Use the [loginName2UserName](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L117) function that will fetch the ldap record and update attributes if it is not in cache

This means that the new users will not be able to login until cache expires, which may lead to worse user experience on some setups.

> * Check credentials with BIND but don't process attributes again
>   
>   * [`$user->processAttributes`](https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L206) here seems redundant as it is already done during the `getLDAPUserByLoginName` function call

Same thing here, forcing attributes update from LDAP on login is most likely to improve user experience and avoid having to wait on background job to see a change applied in Nextcloud.

So, I think it was on purpose that cache is not used in checkPassword. That said, it’s of course a big problem if that gets triggered on each request for DAV requests in some cases.

We should try to see if we can find a middle ground here, maybe look into cache but if user does not exist, force an LDAP search?
For the update of DB data I’m not sure, maybe we can not force it, but it does seem handy to be able to force refresh by logging out then in. But if the data is from cache anyway it does make sense to push to DB though…

@blizzz Thoughts?

2023-01-02 18:11 UTC, akhil1508 commented
@come-nc 
> This means that the new users will not be able to login until cache expires, which may lead to worse user experience on some setups.

This is fine imo as the function `loginName2Username` does first check cache and if user not existing, it fetches from LDAP as seen over [here](https://github.com/nextcloud/server/blob/7ee61ddb75eafaf4c3fe6c45971fd2ede005fa6d/apps/user_ldap/lib/User_LDAP.php#L126)

> Same thing here, forcing attributes update from LDAP on login is most likely to improve user experience and avoid having to wait on background job to see a change applied in Nextcloud.

This is true for sure; my only counter-point is that the cache usually does reset much quicker than the background job run time(especially with lots of users) so the user is fetched from LDAP much more frequently than the bg job(just not everytime). Otherwise, maybe we could even set a config value in `config.php` for this and if set to true(defaulting to false), we can fetch from cache or otherwise fetch and update attributes on every single login.

> We should try to see if we can find a middle ground here, maybe look into cache but if user does not exist, force an LDAP search?

This is already done, please see my point about the `loginName2Username` function above :)

> For the update of DB data I’m not sure, maybe we can not force it, but it does seem handy to be able to force refresh by logging out then in. But if the data is from cache anyway it does make sense to push to DB though…

For me its okay to update once on every cache reset but if other users want the update every time, we can use a config option for this as mentioned above.

2023-01-03 07:45 UTC, come-nc commented
> > This means that the new users will not be able to login until cache expires, which may lead to worse user experience on some setups.
> 
> This is fine imo(new users will be able to login) as the function `loginName2Username` does first check cache and if user not existing, it fetches from LDAP as seen over [here](https://github.com/nextcloud/server/blob/7ee61ddb75eafaf4c3fe6c45971fd2ede005fa6d/apps/user_ldap/lib/User_LDAP.php#L126)

No, if the user does not exists `false` is cached: https://github.com/nextcloud/server/blob/7ee61ddb75eafaf4c3fe6c45971fd2ede005fa6d/apps/user_ldap/lib/User_LDAP.php#L138

On the next call if `false` is cached it is returned without LDAP request:
https://github.com/nextcloud/server/blob/7ee61ddb75eafaf4c3fe6c45971fd2ede005fa6d/apps/user_ldap/lib/User_LDAP.php#L121-L123

2023-01-03 07:52 UTC, akhil1508 commented
@come-nc 
> On the next call if false is cached it is returned without LDAP request

Fair point. My bad, didn't notice the strict comparison against null. I try to see how we can achieve correct behaviour where we fetch if not cached.

2023-01-04 09:41 UTC, akhil1508 commented
@come-nc What about something like:

```php
public function loginName2UserName($loginName, bool $overrideCacheIfFalse = false) {
		$cacheKey = 'loginName2UserName-' . $loginName;
		$username = $this->access->connection->getFromCache($cacheKey);

		$overrideCache = $overrideCacheIfFalse && $username === false;
		if ($username !== null && !$overrideCache) {
			return $username;
		}
               ....
}
```

And then:

```php
public function checkPassword($uid, $password) {
	$username = $this->loginName2UserName($uid);
        ...
```

2023-01-12 12:03 UTC, akhil1508 commented
@come-nc @blizzz @icewind1991 Anything? Please comment if possible if it is okay overall(does not break authentication) so I can test on our servers to see if load goes down a lot by this..

Thanks a lot :)

2023-01-12 15:36 UTC, come-nc commented
> @come-nc @blizzz @icewind1991 Anything? Please comment if possible if it is okay overall(does not break authentication) so I can test on our servers to see if load goes down a lot by this..
> 
> Thanks a lot :)

Yes it looks good enough that you can test it.

2023-01-12 16:22 UTC, blizzz commented
Mh, Attributes are not processed i.e. not updated anymore now on login despite no cache hit. It will be done only for newly mapped users. Unless I oversaw something?

2023-01-12 16:27 UTC, akhil1508 commented
> Mh, Attributes are not processed i.e. not updated anymore now on login despite no cache hit. It will be done only for newly mapped users. Unless I oversaw something?

@blizzz If no cache hit we proceed to https://github.com/nextcloud/server/blob/5c4b4bde1b2da872c3e03846954214a8aa8c598e/apps/user_ldap/lib/User_LDAP.php#L126 so they are processed

2023-01-12 19:05 UTC, akhil1508 commented
> Mh, Attributes are not processed i.e. not updated anymore now on login despite no cache hit. It will be done only for newly mapped users. Unless I oversaw something?
@blizzz Handled now. Please check.

2023-01-13 22:48 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +			if (!$user instanceof User) {
What was the reason for having the password check done before fetching the user object? It also might be an `OfflineUser`, against which a bind should not happen.

2023-01-13 22:48 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +	public function loginName2UserName($loginName, bool $ignoreCacheIfFalseFound = false, bool $processUserAttributes = false) {
If i see it correctly, this method is called with only `false, false` and `true, true` combinations of the bools. Perhaps simplify the signature and use just one marker.

2023-01-16 10:14 UTC, akhil1508 commented on apps/user_ldap/lib/User_LDAP.php
> +	public function loginName2UserName($loginName, bool $ignoreCacheIfFalseFound = false, bool $processUserAttributes = false) {
Fixed.

2023-01-16 10:32 UTC, akhil1508 commented on apps/user_ldap/lib/User_LDAP.php
> +			if (!$user instanceof User) {
Infact, do you think we can skip this check entirely as the `NotOnLDAP` exception is already handled in the `loginName2Username` function?

2023-01-16 10:34 UTC, akhil1508 commented on apps/user_ldap/lib/User_LDAP.php
> +			if (!$user instanceof User) {
I do move it before password check, seems like a redundant check to me, but anyway, the warning might be helpful. 

Do let me know if it is okay to remove :)

2023-01-17 14:07 UTC, akhil1508 commented
@blizzz Seems like I removed reviewers by mistake and am unable to re-add :/

Please do re-add when @come-nc and @icewind1991 when possible

2023-01-19 12:21 UTC, akhil1508 commented
@come-nc @blizzz @icewind1991 It seems good on test servers. Do you think it's okay to put into production as it is currently as server load is crazy high..

2023-08-08 07:56 UTC, come-nc approved these changes

2023-09-22 12:20 UTC, blizzz approved these changes

2023-09-22 12:21 UTC, blizzz commented
It's important to note that this a behavorial change. A user update cannot be triggered anymore by logging out and in again. Only by time (via backend jobs), or the admin.

2023-09-22 12:22 UTC, blizzz commented
could you rebase again, for CI?

2023-09-28 09:20 UTC, akhil1508 commented
@blizzz Done

But some of my earlier commits were unverified, I can't sign off as there are so many merge commits that show up locally... Should I open a new PR with the same changes?

2023-09-28 09:21 UTC, akhil1508 commented
> It's important to note that this a behavorial change. A user update cannot be triggered anymore by logging out and in again. Only by time (via backend jobs), or the admin.

> Only by time (via backend jobs)

Also by time, when cache resets..

2023-09-28 10:49 UTC, akhil1508 commented
@blizzz @come-nc  Finally ready to merge, I did force push, verify my commits and then pull master again

2023-11-13 10:18 UTC, blizzz commented
@akhil1508 I tried to rebase, but have no permissions on the remote branch to push.

2023-11-13 10:47 UTC, tcitworld commented
@blizzz Probably the same issue as https://github.com/nextcloud/server/pull/35459#issuecomment-1779160743

2023-11-13 10:52 UTC, blizzz commented
> @blizzz Probably the same issue as [#35459 (comment)](https://github.com/nextcloud/server/pull/35459#issuecomment-1779160743)

I think it's a config flag somewhere whether you allow other participants to push or not.

2023-11-15 14:24 UTC, akhil1508 commented
>  I tried to rebase, but have no permissions on the remote branch to push.

It's because of https://github.com/nextcloud/server/pull/35459#issuecomment-1779160743

Should I rebase again now?

2023-11-15 20:25 UTC, blizzz commented
> > I tried to rebase, but have no permissions on the remote branch to push.
> 
> It's because of [#35459 (comment)](https://github.com/nextcloud/server/pull/35459#issuecomment-1779160743)
> 
> Should I rebase again now? Is it okay if I add a replacement PR based out of latest master?

Both is fine, you're. I'd like to have the drone tests run again to be on the safe side, then ideally with latest master.

2024-02-23 15:56 UTC, skjnldsv commented
@akhil1508 please rebase or allow maintainers to edit the pr :)

2024-03-20 17:35 UTC, akhil1508 commented
> please rebase or allow maintainers to edit the pr :)

@skjnldsv Sorry, I was inactive for a while  there. So if I re-base, it shows a lot more changes than in this PR. Can I provide a replacement PR for this one based out of master?

2024-03-20 17:45 UTC, akhil1508 commented
@skjnldsv Disregard the earlier comment, I managed to rebase :)

Also squashed commits into one, should be ready to merge if changes look good

2024-03-21 14:14 UTC, come-nc requested changes

2024-03-21 14:14 UTC, come-nc commented on apps/user_ldap/lib/User_LDAP.php
> +		if (!$username) {
```suggestion
		if ($username === false) {
```
To avoid trouble if username is `'0'`

2024-03-21 14:34 UTC, akhil1508 commented on apps/user_ldap/lib/User_LDAP.php
> +		if (!$username) {
Good idea :+1: 

Fixed @come-nc

2024-03-21 17:07 UTC, come-nc approved these changes

2024-03-21 17:10 UTC, akhil1508 commented
@come-nc Should I squash again or are two commits okay?

2024-03-25 08:24 UTC, come-nc commented
> @come-nc Should I squash again or are two commits okay?

Two commits are okay. Ideally it’s better if you reword commits to follow https://www.conventionalcommits.org/en/v1.0.0/

I’m sorry but I’m gonna postpone that PR to 30, I do not feel comfortable merging something which touches LDAP login that close to the release.

2024-04-08 03:34 UTC, akhil1508 commented
> I’m sorry but I’m gonna postpone that PR to 30, I do not feel comfortable merging something which touches LDAP login that close to the release.

@come-nc Why not the next minor version release? :thinking:

2024-04-08 08:27 UTC, come-nc commented
> > I’m sorry but I’m gonna postpone that PR to 30, I do not feel comfortable merging something which touches LDAP login that close to the release.
> 
> @come-nc Why not the next minor version release? 🤔

We always merge first to a major branch. Then it can be backported to stable29 if it makes sense, but after the release.

2024-08-16 10:38 UTC, akhil1508 commented
> Nice PR! Let's see that we get it added to 30 🚀

@sorbaugh Do you need anything from my side to make the merge?

2024-08-16 10:42 UTC, skjnldsv commented
@akhil1508 if possible, could you fix the ldap test failure in `apps/user_ldap/tests/User_LDAPTest.php:235` ?
Do you need help with it? :)

```
1) OCA\User_LDAP\Tests\User_LDAPTest::testCheckPasswordUidReturn
TypeError: Mock_Access_94083a34::areCredentialsValid(): Argument #1 ($name) must be of type string, null given, called in /home/runner/actions-runner/_work/server/server/apps/user_ldap/lib/User_LDAP.php on line 162

/home/runner/actions-runner/_work/server/server/apps/user_ldap/lib/User_LDAP.php:162
/home/runner/actions-runner/_work/server/server/apps/user_ldap/tests/User_LDAPTest.php:184

2) OCA\User_LDAP\Tests\User_LDAPTest::testCheckPasswordPublicAPI
TypeError: Mock_Access_94083a34::areCredentialsValid(): Argument #1 ($name) must be of type string, null given, called in /home/runner/actions-runner/_work/server/server/apps/user_ldap/lib/User_LDAP.php on line 162

/home/runner/actions-runner/_work/server/server/apps/user_ldap/lib/User_LDAP.php:162
/home/runner/actions-runner/_work/server/server/lib/private/User/Manager.php:231
/home/runner/actions-runner/_work/server/server/lib/private/User/Manager.php:201
/home/runner/actions-runner/_work/server/server/apps/user_ldap/tests/User_LDAPTest.php:235
```

2024-08-16 10:56 UTC, akhil1508 commented
>  Do you need help with it? :)

@skjnldsv Yes please. It doesn't seem like my changes should break unit tests. Is it maybe related to being up to date with master? Should I merge master into the branch again?

2024-08-16 11:17 UTC, skjnldsv commented
@akhil1508 could you enable us to make modifications to this branch?
There should be an option at the bottom right 
![image](https://github.com/user-attachments/assets/26d99e7e-4735-4ebf-8081-088e696e45e8)

If possible avoid merging master into this branch, it's preferable if you rebase instead (to avoid creatring a merge commit) :)

2024-08-16 11:21 UTC, akhil1508 commented
@skjnldsv Is it OK if I add a new PR from a personal fork?

Organization forks don't allow maintainer modifications https://github.com/orgs/community/discussions/5634

2024-08-16 11:24 UTC, skjnldsv commented on apps/user_ldap/lib/User_LDAP.php
> +		$dn = $this->access->username2dn($username);
This is the issue that makes the tests fail.

In [this function](https://github.com/nextcloud/server/blob/d4229f9f590a2c3107906c21116d05edc7f13127/apps/user_ldap/tests/User_LDAPTest.php#L151-L202), you need to add something like

```php
$this->access->expects($this->any())
			->method('username2dn')
			->with($this->equalTo('roland'))
			->willReturn('dnOfRoland,dc=test');
```

I'll let you double check the values, as I'm not sure if the dn is correct, I lack ldap knowledge :)

2024-08-16 11:57 UTC, akhil1508 commented
>  It's alright, I think rebasing to master and addressing my last comment should do it :)

```
git remote add upstream https://github.com/nextcloud/server.git
git fetch upstream
git rebase -i upstream/master
```

@skjnldsv I did this and now we have a lot of changes 🤔

2024-08-16 12:27 UTC, akhil1508 commented
@skjnldsv  Rebased and also attempted to fix the unit test

2024-08-16 13:16 UTC, skjnldsv commented
Cypress & Performance testing failure expected
We'll ignore the `unconventional commits` for this one :wink: 
If you create future PRs, please follow the conventional commits pattern :stuck_out_tongue_winking_eye:

2024-08-16 13:17 UTC, merged

2024-08-16 13:17 UTC, skjnldsv commented
Thank you for your patience and commitment @akhil1508 !! :tada: :tada:

2024-08-16 13:19 UTC, akhil1508 commented
@skjnldsv 

> Thank you for your patience and commitment @akhil1508 !! 🎉 🎉

And thanks to you too! :)