Implement occ status command via return codes v2 (Fixes: #35704)
nextcloud/server pull request #35873
Opened 2022-12-22 23:46 UTC by leegarrett

Signed-off-by: Lee Garrett <lgarrett@rocketjump.eu>

* Resolves: #35704

## Summary
This is an improved version of my earlier PR  #35830. This is now a parameter to `status`, so it allows for adding more return codes later, which can then for example be consumed in systemd units, or monitoring checks.

It adds a parameter that can be used in scripts. `./occ status -e` returns 0 when operating normally, and 1 if there is maintenance mode, 2 if `./occ upgrade` is required.

## TODO

- [ ] Test coverage?

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-23 07:53 UTC, nickvergessen reviewed
Otherwise you would need to add a tab on each line

2022-12-23 07:53 UTC, nickvergessen commented on core/Command/Status.php
> +		} else {
```suggestion
		}

```

2022-12-23 07:53 UTC, nickvergessen commented on core/Command/Status.php
> +		}
```suggestion
```

2022-12-25 07:03 UTC, leegarrett commented on core/Command/Status.php
> +		}
Both fixed in the newest branch push.

2022-12-25 07:47 UTC, nickvergessen approved these changes

2023-01-02 09:18 UTC, come-nc requested changes

2023-01-02 09:18 UTC, come-nc commented on core/Command/Status.php
> +
```suggestion
			if ($maintenanceMode === true) {
				/* Checks maintenance mode first */
				return 1;

```
And same change for the 2 other comments.

2023-01-02 19:26 UTC, leegarrett commented on core/Command/Status.php
> +
I've push a new commit that fixes the indentation of all three comments.

2023-01-03 07:50 UTC, come-nc commented
@leegarrett Code style checker still complains, this time about empty lines and spacing: https://github.com/nextcloud/server/actions/runs/3824719618/jobs/6507559027

Also for the comments I’d prefer if you avoid using `#`.

2023-01-03 07:51 UTC, come-nc commented
Also last commit is missing signoff and DCO complains: https://github.com/nextcloud/server/pull/35873/checks?check_run_id=10400685089

2023-01-03 10:00 UTC, leegarrett commented
> @leegarrett Code style checker still complains, this time about empty lines and spacing: https://github.com/nextcloud/server/actions/runs/3824719618/jobs/6507559027
> 
> Also for the comments I’d prefer if you avoid using `#`.

I've hopefully fixed the issue now. Since the 2nd commit wasn't signed off, I've now just squashed it with the first, removed the extra whitespace, and removed the comments. They didn't add much information, anyway.

2023-01-03 11:05 UTC, come-nc commented on core/Command/Status.php
> +		}
Would it make sense to move this to after the call to writeArrayInOutputFormat ?
Or is there a reason to remove output when having the exit code?

2023-01-03 11:06 UTC, come-nc approved these changes
See my question on output, but otherwise looks good, codesniffer and DCO are both happy. Failure in drone is unrelated.

2023-01-03 11:48 UTC, nickvergessen commented on core/Command/Status.php
> +		}
Done

2023-01-03 14:35 UTC, leegarrett commented on core/Command/Status.php
> +		}
Yes, you don't want output e.g. in `ExecCondition` for a system service, as this will also be logged in the unit every time and pollutes the logs unnecessarily. We can however add it back conditionally with `-v` if you see any use of this output.

2023-01-03 14:38 UTC, leegarrett commented
Not sure if resolved conversations get notified, so here's a copy/paste of it:

Yes, you don't want output e.g. in `ExecCondition` for a system service, as this will also be logged in the unit every time and pollutes the logs unnecessarily. We can however add it back conditionally with `-v` if you see any use of this output.

2023-01-03 14:41 UTC, nickvergessen commented
> Not sure if resolved conversations get notified, so here's a copy/paste of it:

They do,

> Yes, you don't want output e.g. in ExecCondition for a system service, as this will also be logged in the unit every time and pollutes the logs unnecessarily. We can however add it back conditionally with -v if you see any use of this output.

That makes sense. Will make it so.

2023-01-04 08:51 UTC, merged

2023-01-18 13:12 UTC, leegarrett commented
Hello, can we also get this backported to v25?

2023-01-18 13:42 UTC, nickvergessen commented
/backport to stable25

2023-01-19 07:34 UTC, solracsf commented
No documentation on this?

2023-01-19 08:27 UTC, nickvergessen commented
Should be added to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html yes.
@leegarrett  could you extend the documentation at https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst
Otherwise raising an issue in https://github.com/nextcloud/documentation/issues with a link to this PR would be helpful too.

2023-01-31 17:17 UTC, leegarrett commented
FYI, the doc update PR is at https://github.com/nextcloud/documentation/pull/9583

2023-02-21 13:04 UTC, DaphneMuller commented
hello @leegarrett 
Thank you so much for your work on this pull request! This ticket seems to still have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

2023-02-21 13:33 UTC, nickvergessen commented
It's linked above https://github.com/nextcloud/documentation/pull/9583