Remove unneeded UpdateCertificateStore.
nextcloud/server pull request #3589
Opened 2017-02-23 03:28 UTC by MorrisJobke

as discussed @LukasReschke

2017-02-23 04:25 UTC, MorrisJobke commented
@rullzer @nickvergessen @LukasReschke @blizzz @schiessle @icewind1991 Sorry for this really long list, but while looking at those repair steps I noticed that we run a lot of them during update and most of them are not needed anymore, but are run anyway. I hope to make the upgrade a bit faster for bigger instances or at least drop some unused code from our code base. So please give this is brief check and review.

2017-02-23 04:26 UTC, MorrisJobke commented
Dropping 32 * 💯 lines of code ... not existing code is bug free code 😎

2017-02-23 09:05 UTC, nickvergessen requested changes

2017-02-23 09:05 UTC, nickvergessen commented on lib/private/Repair/AssetCache.php
> -		$output->info('Asset cache cleared.');
Btw do we do that with our theming as well? I think we need to regenerate colored/themed and compiled files from the scss stuff on update, to make sure the new files are used?

2017-02-23 09:05 UTC, nickvergessen commented on lib/private/Repair/Preview.php
> -				$thumbnailsFolder = $child->getPath() . '/thumbnails';
We could execute this for one release all the time. New previews are in appdata_*/previews

2017-02-23 14:39 UTC, rullzer approved these changes

2017-02-23 14:39 UTC, rullzer commented
Went trough the list. Makes sense to me.

2017-02-23 21:18 UTC, MorrisJobke commented on lib/private/Repair/AssetCache.php
> -		$output->info('Asset cache cleared.');
Makes sense - cc @juliushaertl 

I would not add this to this PR, but as a separate one.

2017-02-23 21:19 UTC, MorrisJobke commented on lib/private/Repair/Preview.php
> -				$thumbnailsFolder = $child->getPath() . '/thumbnails';
Not really needed, because they will not be generated anymore. Why should we cleanup something that is already cleaned up. Nextcloud 11 already created the new previews and already cleaned it up. So no need to still clean it up during 12. Even if this wouldn't do much, but still it's code that doesn't do anything.

2017-02-23 21:53 UTC, LukasReschke approved these changes

2017-02-23 21:56 UTC, MorrisJobke commented on lib/private/Repair/AssetCache.php
> -		$output->info('Asset cache cleared.');
#3604

2017-02-23 21:57 UTC, MorrisJobke commented
@nickvergessen I will merge this now. I commented on your remarks and opened for one a separate ticket. I hope that is okay.

2017-02-23 21:57 UTC, merged

2017-02-24 07:48 UTC, nickvergessen commented on lib/private/Repair/Preview.php
> -				$thumbnailsFolder = $child->getPath() . '/thumbnails';
Actually this was only executed from 7.0.2 to 7.0.4
See https://github.com/nextcloud/server/pull/3589/files#diff-376668a10f221bc362471979106bfea9L192

I also verified with my instance and I still have GBs in these folders although I'm running 11.0.1

2017-02-24 08:08 UTC, rullzer commented on lib/private/Repair/Preview.php
> -				$thumbnailsFolder = $child->getPath() . '/thumbnails';
Ah probabaly because of gallery. The gallery shipped with 11 is not using the public endpoint yet.