Replace custom tooltips with native tooltips in personal and administration settings
nextcloud/server pull request #35901
Opened 2022-12-28 10:35 UTC by JuliaKirschenheuter

* Resolves: https://github.com/nextcloud/server/issues/35886

## Summary

Replace custom tooltips with native tooltips in personal and administration settings sections besides "Mobile & desktop", "Privacy" and "System"

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-28 10:37 UTC, ChristophWurst requested changes

2022-12-28 10:37 UTC, ChristophWurst commented on apps/settings/src/components/AppDetails.vue
> +				rel="noreferrer noopener">{{ t('settings', 'Visit websitg') }} ↗</a>
typo

2022-12-28 11:42 UTC, ChristophWurst approved these changes
The disappearance of ``dist/icons.css`` is once again suspicious

2022-12-28 13:38 UTC, ChristophWurst commented
/backport to stable25

2023-01-10 15:32 UTC, artonge approved these changes

2023-01-10 17:55 UTC, Pytal approved these changes

2023-01-11 08:11 UTC, PVince81 commented
@JuliaKirschenheuter  please check handlebars failure

2023-01-11 14:22 UTC, merged

2023-01-17 07:20 UTC, JuliaKirschenheuter commented
/backport to stable25

2023-01-17 07:32 UTC, ChristophWurst commented
Time for https://docs.nextcloud.com/server/latest/developer_manual/getting_started/development_process.html#manual-backport

2023-01-17 21:14 UTC, nickvergessen commented
> - [ ] Screenshots before/after for front-end changes

Wondering why there are frontend changes without screenshots. The template should help to remind you about them.

Here are the screenshots:
Before | After
---|---
![Bildschirmfoto vom 2023-01-17 22-08-38](https://user-images.githubusercontent.com/213943/213013027-9ea1b185-9689-42ca-b82f-7ea577b47843.png) | ![Bildschirmfoto vom 2023-01-17 22-09-07](https://user-images.githubusercontent.com/213943/213013033-70c46d12-7dc3-4f29-bc90-ea200d4ad6fd.png)

Can you fix that in a follow up? Thanks

2023-01-18 14:06 UTC, JuliaKirschenheuter commented
> Can you fix that in a follow up? Thanks

Thank you! Of coarse i will fix it. As a follow-up