ExifProvider.php: handle unhandled exception
nextcloud/server pull request #35932
Opened 2022-12-31 19:02 UTC by luxifr

Signed-off-by: luxifr <luxifer@luxifer.fyi>

* Resolves: #35931 

## Summary
Handle unhandled exception to keep files:scan run from crashing when it encounters a file with invalid exif data.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [N/A] Screenshots before/after for front-end changes
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) is not required
- [X] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2022-12-31 21:48 UTC, shyim commented on lib/private/Metadata/Provider/ExifProvider.php
> +			} catch (\Exception $ex) {
Can you not check explicit the exception you want to catch? Or maybe \Throwable is better as it includes anything :)

2023-01-01 00:33 UTC, luxifr commented on lib/private/Metadata/Provider/ExifProvider.php
> +			} catch (\Exception $ex) {
I'll change it into `\Throwable` then - please keep in mind I'm not a PHP developer, so I didn't know that was broader - I basically just replicated existing error handling in the code a few lines up. 

Catching only the error in question isn't helpful in this case though imho, because a) the ErrorException it throws in case of an ostensibly corrupt file isn't even documented and b) in any case it should just ignore the file and not crash the whole file scan, so 🤷🏼‍♀️.

2023-01-04 16:16 UTC, artonge approved these changes

2023-02-03 11:56 UTC, marcelklehr commented on lib/private/Metadata/Provider/ExifProvider.php
> +			} catch (\Throwable $ex) {
I don't think this will work:

```
php > try {getimagesize('foobar');} catch(\Throwable $e){}
PHP Warning:  getimagesize(foobar): Failed to open stream: No such file or directory in php shell code on line 1
```

2023-02-06 09:11 UTC, artonge commented on lib/private/Metadata/Provider/ExifProvider.php
> +			} catch (\Throwable $ex) {
Probably same reason as in https://github.com/nextcloud/server/pull/36420#issuecomment-1408653542

2023-04-15 12:30 UTC, szaimen commented on lib/private/Metadata/Provider/ExifProvider.php
> +				$this->logger->warning("Couldn't get image for ".$file->getId(), ['exception' => $ex]);
Sane as in https://github.com/nextcloud/server/pull/36420/files
```suggestion
				$sizeResult = @getimagesizefromstring($file->getContent());
			} catch (\Exception $ex) {
				$this->logger->info("Couldn't get image for ".$file->getId(), ['exception' => $ex]);
```

2023-04-27 08:04 UTC, come-nc requested changes

2023-04-27 08:04 UTC, come-nc commented on lib/private/Metadata/Provider/ExifProvider.php
> +			} catch (\Throwable $ex) {
This would work from scan command because scan command converts warning into Exception, but that’s really ugly. It should be handled in Scan command as it is the one doing the conversion.

2023-04-27 08:54 UTC, come-nc commented
See https://github.com/nextcloud/server/pull/37944 instead

2023-04-27 08:55 UTC, closed without merging

2023-05-26 07:24 UTC, digidax commented
Bug still present in 26.0.2 when using Android App Folder Sync:
![grafik](https://github.com/nextcloud/server/assets/5276312/25f1e16a-e867-4057-b728-d45c37c43a71)