Code fixes from PR 34997
nextcloud/server pull request #35943
Opened 2023-01-02 14:14 UTC by come-nc

Split code fixes commits from https://github.com/nextcloud/server/pull/34997 to make the diff shorter.

2023-01-02 15:58 UTC, nickvergessen commented on apps/dav/lib/Connector/Sabre/File.php
> +					$expected = (int)$_SERVER['CONTENT_LENGTH'];
Will we run into issues with 32bit and float?

2023-01-02 16:01 UTC, nickvergessen requested changes
Good apart from the (int) casting on file size (content length) which makes my alarms ring

2023-01-02 16:08 UTC, YasinAshorian approved these changes

2023-01-02 16:16 UTC, come-nc commented on apps/dav/lib/Connector/Sabre/File.php
> +					$expected = (int)$_SERVER['CONTENT_LENGTH'];
No I don’t think so, I never saw an HTTP request with a size larger than 4GB
Content length should always fit an int I think.
And there is already the same cast on line 295.

2023-01-03 13:09 UTC, nickvergessen commented on apps/dav/lib/Connector/Sabre/File.php
> +					$expected = (int)$_SERVER['CONTENT_LENGTH'];
Ah, nevermind then

2023-01-03 13:09 UTC, nickvergessen approved these changes

2023-01-03 13:31 UTC, skjnldsv approved these changes

2023-01-03 13:32 UTC, merged