Add "MFA Verified" check to workflowengine
nextcloud/server pull request #36045
Opened 2023-01-09 11:58 UTC by michielbdejong

This PR goes together with:
* #35555
* https://github.com/nextcloud/user_saml/pull/668 
* https://github.com/nextcloud/globalsiteselector/pull/80

It allows the creation of work flows that depend on whether the logged-in user has passed MFA Verification for the current session or not.

2023-01-09 14:54 UTC, nickvergessen requested changes

2023-01-09 14:54 UTC, nickvergessen commented on apps/workflowengine/lib/Check/MfaVerified.php
> +		$mfaVerified = $this->session->get('user_saml.samlUserData')["mfa_verified"][0];
```suggestion
		$mfaVerified = $this->session->get('user_saml.samlUserData')["mfa_verified"][0] ?? false;
```

2023-01-09 14:54 UTC, nickvergessen commented on apps/workflowengine/lib/Check/MfaVerified.php
> +			return $mfaVerified != '1'; // checking whether the current user is not MFA-verified
```suggestion
		if (strtolower($value) === 'true') {
			return $mfaVerified === '1'; // checking whether the current user is MFA-verified
		} else {
			return $mfaVerified !== '1'; // checking whether the current user is not MFA-verified
```

2023-01-09 14:54 UTC, nickvergessen commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
and is not?

That would allow e.g. to use access control to block access to folders for people that did not 2fa

2023-01-10 11:30 UTC, michielbdejong commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
Yes, this is a default boolean dropdown (@mrvahedi68 will provide some screenshots of it later today); the `operator`of the check is always "is" and the `value` of the check can be "true" or "false".

So that way both "MFA verified is true" and "MFA verified is false" are available. Indeed, for blocking access to a folder you would create a rule to `"block access" if "MFA verified is false"`.

2023-01-10 11:38 UTC, michielbdejong commented
Not sure why `checkers` is failing in https://drone.nextcloud.com/nextcloud/server/28345/1/3
The failure for `integration-contacts-menu` seems unrelated.

2023-01-10 12:44 UTC, michielbdejong commented
Ah, need to run `bash build/autoloaderchecker.sh`

2023-01-10 15:21 UTC, mrvahedi68 commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
You can see here to screenshots of it. We have a dropdown with only one field `'is verified?`  and another textbox with a hint (`true`) that user can input anything. So We have a check at [this](https://github.com/nextcloud/server/pull/36045/files/d6c2541dd170160719bccd7d96f75d71e240c10f#diff-324119d2db6f3d5a6d7546558dd8011e16e04683d83c4d29d69ff5f250f353d1R75) function to validate user input. (you can see a related screenshot below). Based on this rule admin can restrict access to files by MFA verified is false or true.


![closed](https://user-images.githubusercontent.com/34796044/211589253-31bc14ed-81de-4ad6-93d5-c56ec1167bf6.jpg)
![opened](https://user-images.githubusercontent.com/34796044/211589261-e1896dcf-7259-4042-8fac-d89ab1d38050.jpg)
![invalid](https://user-images.githubusercontent.com/34796044/211590209-6d97d75a-7518-4fe7-9654-9361df8e3ef4.jpg)

2023-01-10 15:58 UTC, nickvergessen commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
Ah okay. Because that is trouble some with translations and admins using different langauges, I would recomment to:

* Operation:
    * is
    * is not
* Value (hard coded to):
    * verified

2023-01-10 16:00 UTC, nickvergessen commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
When you use a dedicated component you can even remove the input field for the value.

2023-01-15 13:40 UTC, mrvahedi68 commented on apps/workflowengine/src/components/Checks/file.js
> +			{ operator: 'is', name: t('workflowengine', 'is verified?') },
I changed the source and use the new approach you described above. 
Now we have only one drop-down with two values and no other inputs.
You can find screenshots at the flowing.
@nickvergessen 

![opened](https://user-images.githubusercontent.com/34796044/212544127-ecb8e9e5-b1bf-4303-8e1c-ef7fcb725366.jpg)
![selected](https://user-images.githubusercontent.com/34796044/212544130-69c6a527-7a40-495e-807c-fa2a080b1317.JPG)

2023-01-17 07:37 UTC, nickvergessen commented
> The failing test seems unrelated

Failing lint and node are related. Fixable with:

```
npm ci && npm run lint:fix
make build-js-production
```
And then commit.

If you fail to do that, that's no problem, we can easily take that over.

2023-02-24 12:09 UTC, michielbdejong commented
This PR seems to be using the wrong branch, will recreate it.

2023-02-24 12:09 UTC, closed without merging