spaces are allowed in userids
nextcloud/server pull request #36067
Opened 2023-01-10 12:26 UTC by szaimen

Address https://github.com/nextcloud/nextcloud-vue/pull/3468#issuecomment-1325068316

Supersedes https://github.com/nextcloud/server/pull/35363

2023-01-10 14:39 UTC, nickvergessen commented on apps/user_ldap/lib/Access.php
> +		$name = preg_replace('/[^a-zA-Z0-9 _.@-]/u', '', $name);
Not sure if this does not break existing ldap accounts. Can someone confirm?

Otherwise we could just fix the user manager for now and keep ldap not supporting spaces

2023-01-10 14:42 UTC, szaimen commented on apps/user_ldap/lib/Access.php
> +		$name = preg_replace('/[^a-zA-Z0-9 _.@-]/u', '', $name);
Would be fine for me as well. @come-nc or @blizzz please confirm

2023-01-12 10:34 UTC, come-nc commented on apps/user_ldap/lib/Access.php
> +		$name = preg_replace('/[^a-zA-Z0-9 _.@-]/u', '', $name);
https://github.com/nextcloud/server/pull/35363#discussion_r1031246002

2023-01-12 10:35 UTC, szaimen commented on apps/user_ldap/lib/Access.php
> +		$name = preg_replace('/[^a-zA-Z0-9 _.@-]/u', '', $name);
Yup, lets leave the decision then to @blizzz ...

2023-01-12 10:36 UTC, come-nc approved these changes
I would feel better if you leave user_ldap alone on this matter, as I do not see what good it can bring to let it maps users with spaces in uid.
But it should work either way.

2023-01-12 16:27 UTC, blizzz requested changes
^

2023-01-12 22:03 UTC, szaimen commented on apps/user_ldap/lib/Access.php
> +		$name = preg_replace('/[^a-zA-Z0-9 _.@-]/u', '', $name);
removed the change from user_ldap 👍

2023-01-12 22:04 UTC, szaimen commented
> > I would feel better if you leave user_ldap alone on this matter, as I do not see what good it can bring to let it maps users with spaces in uid.
> > But it should work either way.
> 
> Seconded.

done 👍

2023-01-13 03:20 UTC, nickvergessen approved these changes

2023-01-13 09:45 UTC, blizzz approved these changes

2023-01-13 09:45 UTC, merged