OCS API endpoint to resend welcome message
nextcloud/server pull request #3607
Opened 2017-02-24 06:03 UTC by MorrisJobke

* send a POST request to ocs/v1.php/cloud/users/USERNAME/resendWelcomeMessage to trigger
  the welcome message to be send
* fixes #3367

example curl statement:

  curl -i https://example.org/ocs/v1.php/cloud/users/USERNAME/resendWelcomeMessage -H  "OCS-APIRequest: true" -u admin:password -X POST

cc @nickvergessen @blizzz @schiessle

2017-02-24 06:04 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		// FIXME: set users language in email
Currently there is no way to change the used language. Or did I miss something. It would be nice to inject it somehow into the TemplateResponse or overwrite it.

2017-02-24 07:57 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		// FIXME: set users language in email
I wouldn't know any either...
Activity app abuses a template variable to work around this:
https://github.com/nextcloud/activity/blob/f83a0d7e8cc4e60f7ea6a45e590ef273e9c91081/lib/MailQueueHandler.php#L276-L276
https://github.com/nextcloud/activity/blob/3d803c18340eb6d90419db7a66c13a4a7e8d0a19/templates/email.notification.php#L25-L25

2017-02-24 08:03 UTC, nickvergessen requested changes

2017-02-24 08:03 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								\OC_Defaults $defaults,
I'm not sure this injects the correct theming, did you try?

2017-02-24 08:03 UTC, nickvergessen commented on apps/provisioning_api/appinfo/routes.php
> +		['root' => '/cloud', 'name' => 'Users#resendWelcomeMessage', 'url' => '/users/{userId}/resendWelcomeMessage', 'verb' => 'POST'],
I hate camelcase URLs, just use `/welcome` ?

2017-02-24 08:03 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	 * @throws OCSForbiddenException
Can't see that

2017-02-24 15:21 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								\OC_Defaults $defaults,
That's what the Settings\UserController also does 🙈

2017-02-24 15:21 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	 * @throws OCSForbiddenException
Right 👍

2017-02-24 18:39 UTC, MorrisJobke commented
Please test again @nickvergessen

2017-02-24 18:47 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								\OC_Defaults $defaults,
Doesn't seem to work 🙈 

Let me try to fix it.

2017-02-24 19:09 UTC, MorrisJobke commented on apps/provisioning_api/lib/Controller/UsersController.php
> +								\OC_Defaults $defaults,
Found a way to fix this and it works now. As a side effect also the same bug for the initial welcome email is fixed by this. And it also works with disabled theming 😉

2017-02-28 22:30 UTC, MorrisJobke commented
I rebased to fix the merge conflicts.

2017-03-01 16:11 UTC, MorrisJobke commented
@icewind1991 @rullzer @LukasReschke @nickvergessen Please review

2017-03-02 08:55 UTC, nickvergessen approved these changes
Works

2017-03-03 12:50 UTC, rullzer approved these changes
Fine lets do this! :+1:

2017-03-03 12:50 UTC, merged