Announce trusted server endpoints
nextcloud/server pull request #3611
Opened 2017-02-24 11:06 UTC by schiessle

Create new endpoints to exchange the shared secret between trusted servers (to make it more align with the other public endpoints we have regarding federation) and announce it as "ocs-provider"

A additional PR will follow where we make use of it.

2017-02-24 16:16 UTC, LukasReschke requested changes
Tests need to be adjusted :)

2017-03-09 09:40 UTC, schiessle commented
tests are adjusted, please review... Thanks!

2017-03-09 10:14 UTC, schiessle commented
failing tests are unrelated, please ignore

2017-03-09 10:19 UTC, nickvergessen approved these changes
Code looks good, although I don't quite know what this is used for and why we can't use the old URL, I guest that is what the provider endpoint would be for?

2017-03-09 13:24 UTC, schiessle commented
@nickvergessen announcing the endpoints is needed to allow other solutions like Pydio to implement it. While we are on it, I unified it because all the other endpoint are under cloud/ as well

2017-03-09 13:27 UTC, rullzer commented on lib/private/OCS/Provider.php
> +		if ($this->appManager->isEnabledForUser('federation')) {
I don't link this :P But yeah no better way currently I guess.

2017-03-09 13:27 UTC, rullzer approved these changes

2017-03-09 13:39 UTC, merged

2017-03-09 13:41 UTC, schiessle commented on lib/private/OCS/Provider.php
> +		if ($this->appManager->isEnabledForUser('federation')) {
yes, at some point we should allow apps to register OCS providers instead of relying on this internal file. Or maybe all defined OCS route should be published automatically? Anyway, that's nothing for this PR