fix(autoloading): Add missing autoloaders for shipped apps
nextcloud/server pull request #36112
Opened 2023-01-12 09:10 UTC by ChristophWurst

* Resolves: n/a

## Summary

Shipped apps in this repo have their own authorative (optimized) composer autoloader. But not all of them. The apps still work, but we need a dynamic PSR4 autoloader that has to access the filesystem to check for class existence. Furthermore I'm assuming that with each app autoloader we add, there is a chance that multiple autoloaders try to load a certain file.

By adding the few missing autoloaders I was able to reduce `php occ` runtime by 1.1%. `GET <host>/status.php` improved from 209.50 requests per second to 222.31 request per second or 5.6%.

The autoloader was missing for the following apps
* dashboard
* files_external
* theming
* weather_status

I assume that distributed Nextcloud setups with the php code on shared storage will see an even bigger performance improvement.

## 100x`php occ` benchmark

```time for i in `seq 1 100`; do php occ; done```

<details>

### 100x occ before

real    0m41,152s
user    0m34,222s
sys     0m6,934s

### 100x occ after

real    0m40,692s
user    0m33,853s
sys     0m6,850s
</details>

## Apache Bench

``ab -n 1000 -c 20 https://localhost/status.php``

<details>

### Before
```
$ ab -n 1000 -c 20 https://localhost/status.php
This is ApacheBench, Version 2.3 <$Revision: 1901567 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software:        nginx/1.22.1
Server Hostname:        localhost
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,4096,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        localhost

Document Path:          /status.php
Document Length:        174 bytes

Concurrency Level:      20
Time taken for tests:   4.773 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      1409108 bytes
HTML transferred:       174000 bytes
Requests per second:    209.50 [#/sec] (mean)
Time per request:       95.464 [ms] (mean)
Time per request:       4.773 [ms] (mean, across all concurrent requests)
Transfer rate:          288.29 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        7   15  14.6     10     117
Processing:    22   79  21.5     76     173
Waiting:       22   78  21.5     76     173
Total:         42   93  26.9     88     265

Percentage of the requests served within a certain time (ms)
  50%     88
  66%     98
  75%    106
  80%    115
  90%    125
  95%    135
  98%    159
  99%    197
 100%    265 (longest request)
```

### After
```
$ ab -n 1000 -c 20 https://localhost/status.php
This is ApacheBench, Version 2.3 <$Revision: 1901567 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software:        nginx/1.22.1
Server Hostname:        localhost
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,4096,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        localhost

Document Path:          /status.php
Document Length:        174 bytes

Concurrency Level:      20
Time taken for tests:   4.498 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      1409112 bytes
HTML transferred:       174000 bytes
Requests per second:    222.31 [#/sec] (mean)
Time per request:       89.964 [ms] (mean)
Time per request:       4.498 [ms] (mean, across all concurrent requests)
Transfer rate:          305.92 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        7   13  13.5     10     115
Processing:    23   76  21.5     71     153
Waiting:       23   76  21.5     71     153
Total:         44   89  25.9     82     251

Percentage of the requests served within a certain time (ms)
  50%     82
  66%     91
  75%     97
  80%    103
  90%    124
  95%    140
  98%    155
  99%    194
 100%    251 (longest request)
```
</details>

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-12 09:12 UTC, PVince81 approved these changes
:+1: nice catch

any reason why our build autoloader script did not cover those ? otherwise CI would have caught this discrepancy, would be good to add a step there for that

2023-01-12 09:14 UTC, ChristophWurst commented
> any reason why our build autoloader script did not cover those ? otherwise CI would have caught this discrepancy, would be good to add a step there for that

``if [[ -e ${app}/composer/composer.json ]]; then``

Only apps that have the composer file are checked

2023-01-12 09:19 UTC, juliushaertl approved these changes

2023-01-12 09:20 UTC, juliusknorr requested changes
files_external seems to have some issues still according to CI:

Migration step 'OCA\Files_External\Migration\Version1011Date20200630192246' is unknown
[15](https://github.com/nextcloud/server/actions/runs/3900761480/jobs/6661803873#step:5:16)

2023-01-12 09:21 UTC, st3iny approved these changes

2023-01-12 09:42 UTC, ChristophWurst commented
> otherwise CI would have caught this discrepancy, would be good to add a step there for that

Added

2023-01-12 09:56 UTC, ChristophWurst commented
> files_external seems to have some issues still according to CI:
> 
> Migration step 'OCA\Files_External\Migration\Version1011Date20200630192246' is unknown [15](https://github.com/nextcloud/server/actions/runs/3900761480/jobs/6661803873#step:5:16)

Typo in the PSR4 spec

2023-01-12 11:21 UTC, tcitworld commented on .github/workflows/s3-external.yml
> +          ./occ app:enable -vvv --force ${{ env.APP_NAME }}
**nitpick:** This doesn't seem related.

2023-01-12 11:21 UTC, tcitworld commented on core/Command/App/Enable.php
> -			$this->exitCode = 1;
**nitpick:** This doesn't seem related.

2023-01-12 11:26 UTC, ChristophWurst commented on core/Command/App/Enable.php
> -			$this->exitCode = 1;
This will be dropped as well

2023-01-12 11:26 UTC, ChristophWurst commented on .github/workflows/s3-external.yml
> +          ./occ app:enable -vvv --force ${{ env.APP_NAME }}
I will drop https://github.com/nextcloud/server/pull/36112/commits/a7928205951a7db0a9624167c4b5f8417093be04 with the final rebase

2023-01-12 16:21 UTC, nickvergessen commented on build/autoloaderchecker.sh
> +		echo "${app} is not shipped. Ignoring autoloader regeneration:w"
```suggestion
		echo "${app} is not shipped. Ignoring autoloader regeneration"
```

Trying to close an editor or something?

2023-01-17 07:33 UTC, nickvergessen approved these changes

2023-01-30 15:36 UTC, ChristophWurst commented
CI is not happy about the theming app changes :s

2023-03-17 13:24 UTC, closed without merging