Fix calendar emails to be outlook compatible
nextcloud/server pull request #36118
Opened 2023-01-12 13:42 UTC by ChristophWurst

* Resolves: # 

## Summary

Resubmit and formatted version of https://github.com/nextcloud/server/pull/34324

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-12 16:58 UTC, tcitworld approved these changes

2023-01-16 11:26 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +				'UTF-8'
Will this still show the ics as a downloadable attachment? I guess it depends on each client implementation. Could we maybe do both? Attach inline and as a separate file?

2023-01-16 11:44 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +				'UTF-8'
Then please take over the PR. These are not my changes.

2023-01-16 13:20 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +				'UTF-8'
IIRC Thunderbird doesn't have any issue with that.

2023-01-27 14:56 UTC, ChristophWurst commented
@miaulalala would this be realistic to finish for 26?

2023-02-01 10:14 UTC, miaulalala commented
Questionable if symfony supports this: https://github.com/symfony/symfony/issues/44557

I will look into it tomorrow

2023-02-20 17:25 UTC, miaulalala commented
The attachment is embedded now, but I have no outlook client to test this. @merlinwoff  can you please try?

2023-02-20 17:36 UTC, ChristophWurst commented
The rebase went sideways

2023-02-20 18:00 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	 * @param $charset: Character Set (e.g. UTF-8)
`@param type name description`, e.g. `@param string $body body of the MIME part`

2023-02-20 18:16 UTC, ChristophWurst reviewed
:smiling_face_with_tear:

2023-02-20 18:16 UTC, ChristophWurst commented on lib/public/Mail/IMessage.php
> +	 * @param string $body  body of the MIME part
```suggestion
	 * @param string $body body of the MIME part
```

2023-05-10 10:10 UTC, miaulalala approved these changes

2023-05-10 10:10 UTC, merged

2023-05-14 05:37 UTC, nickvergessen requested changes
Please mention in the 27 changes issue

2023-05-14 05:37 UTC, nickvergessen commented on lib/public/Mail/IMessage.php
> +	 * @since 26.0.0
27

2023-05-14 05:37 UTC, nickvergessen commented on lib/public/Mail/IMessage.php
> +	public function attachInline(string $body, string $name, string $contentType = null): IMessage;
`?string $contentType = null`

2023-05-30 09:42 UTC, DaphneMuller commented
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!