Add workflow for 32bits testing
nextcloud/server pull request #36120
Opened 2023-01-12 14:53 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

* Resolves: #36072

## Summary

Add 32bits to CI and fix errors

## TODO

- [ ] Have a working 32bits PHPUnit CI step
- [ ] Refine which tests it runs or not
- [ ] Fix errors
- [ ] Refine when this CI step runs or not
- [ ] Backport CI step (and fixes if needed) to stable25

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-12 15:27 UTC, come-nc commented
```
There were 2 failures:

1) Test\User\UserTest::testSetQuota
Expectation failed for method name is "setUserValue" when invoked 1 time(s)
Parameter 3 for invocation OCP\IConfig::setUserValue('foo', 'files', 'quota', '0 B', null) does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'23 TB'
+'0 B'

/__w/server/server/lib/private/User/User.php:526
/__w/server/server/tests/lib/User/UserTest.php:744

2) Test\User\UserTest::testSetQuotaAddressNoChange
OCP\IConfig::setUserValue('foo', 'files', 'quota', '0 B', null) was not expected to be called.

/__w/server/server/lib/private/User/User.php:526
/__w/server/server/tests/lib/User/UserTest.php:831
```

So it works.

But either we do not have enough tests on quota or they are not run by the selection I’ve put, because I expected type errors as well on file sizes.
We need to add tests specifically for files over 4GB I guess.

There is also a whole bunch of:
```
1) OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest::testCalendarQuery with data set "all" (array(0, 1, 2, 3), array(), array())
ValueError: Epoch doesn't fit in a PHP integer

/__w/server/server/apps/dav/lib/CalDAV/CalDavBackend.php:2738
/__w/server/server/apps/dav/lib/CalDAV/CalDavBackend.php:1209
/__w/server/server/apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php:221
/__w/server/server/apps/dav/tests/unit/CalDAV/CalDavBackendTest.php:426
```

2023-01-20 14:49 UTC, come-nc commented
(rebased)

2023-01-23 10:46 UTC, come-nc commented
For the `ValueError: Epoch doesn't fit in a PHP integer` errors from dav tests, they are triggered by calling `getTimestamp` on `DateTime` objects for dates after 2038.
We need to decide whether we want to support events after 2038 in dav/calendar or not for 32bits, which would imply retyping all timestamps in there to int|float. Other solution is to document it as known limitation on 32bits and skip those tests on 32bits.
ping @PVince81 @AndyScherzinger

2023-01-23 16:50 UTC, AndyScherzinger commented
> support events after 2038

I'd be fine to document it as a known limitation, that 32-bit can't handle dates past that time.

2023-01-24 07:06 UTC, ChristophWurst commented
review was wrongly requested because the PR was set for review already. put it back to draft.

2023-01-30 11:01 UTC, come-nc commented
> * [ ]  Document that events past 2038 (check actual limit) are not supported on 32bit

- [ ] Document that events before EPOCH are not supported either on 32bit

2023-01-30 13:30 UTC, come-nc commented
CI is now passing, rebased on master, ready for review.
I’ve set the 32bit CI to run once a day at 1:15 am, what do you think @AndyScherzinger ?

2023-01-30 15:47 UTC, AndyScherzinger commented
> I’ve set the 32bit CI to run once a day at 1:15 am, what do you think

@come-nc sounds good to me, time and interval wise 👍

2023-01-30 17:15 UTC, artonge approved these changes

2023-01-30 17:15 UTC, artonge commented on lib/private/legacy/OC_Response.php
> +			if ($length > PHP_INT_MAX && stripos(PHP_SAPI, 'apache') === 0) {
Check if we should do that all the time

2023-01-30 17:42 UTC, come-nc commented on lib/private/legacy/OC_Response.php
> +			if ($length > PHP_INT_MAX && stripos(PHP_SAPI, 'apache') === 0) {
We checked with @artonge and it should be fine

2023-01-30 19:36 UTC, come-nc commented
I fixed psalm warning, but drone testing is failing with:
```
173	There was 1 error:
174	
175	1) Test\Files\ViewTest::testLockBasicOperationUnlocksAfterCancelledHook with data set #14 ('filesize', array('dir'), 'dir', null, 1, 1, 1, null, 100)
176	ParseError: syntax error, unexpected token "|", expecting "{"
177	
178	/drone/src/lib/private/Files/View.php:1182
179	/drone/src/lib/private/Files/View.php:415
180	/drone/src/tests/lib/Files/ViewTest.php:2092
```

I have no idea where this comes from, there is no "|" character at the line it’s giving. I’m failing to reproduce locally so far.

2023-01-31 10:39 UTC, artonge commented
> I have no idea where this comes from, there is no "|" character at the line it’s giving. I’m failing to reproduce locally so far.

I think it refers to that: https://github.com/nextcloud/server/blob/39aeecff46748673899b9288f81e98c50a647192/lib/private/Files/Storage/Local.php#L245 (that's the method called by `/drone/src/lib/private/Files/View.php:1182` is think)

Is drone using a PHP version compatible with this syntax ?

2023-02-02 10:32 UTC, come-nc commented on lib/public/Util.php
> +	public static function numericToNumber(string|float|int $number): int|float {
In the end I’ve left these types and added a cast to string instead, this makes sure the method wil cast for float to int if the value fit in an int

2023-02-02 10:33 UTC, come-nc commented
> > I have no idea where this comes from, there is no "|" character at the line it’s giving. I’m failing to reproduce locally so far.
> 
> I think it refers to that:
> 
> https://github.com/nextcloud/server/blob/39aeecff46748673899b9288f81e98c50a647192/lib/private/Files/Storage/Local.php#L245
> 
> (that's the method called by `/drone/src/lib/private/Files/View.php:1182` I think)
> Is drone using a PHP version compatible with this syntax ?

No it uses PHP 8.0.26, and I checked on 3v4l, the syntax you link to is accepted.

I rebased on master and pushed fixes to Louis remarks.

2023-02-02 13:37 UTC, come-nc commented
Extracted the complete stacktrace:
```
[sqlite-php8.0:81] ParseError: syntax error, unexpected token "|", expecting "{" in phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code:3
[sqlite-php8.0:82] Stack trace:
[sqlite-php8.0:83] #0 phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/Generator.php(345): PHPUnit\Framework\MockObject\MockClass->generate()
[sqlite-php8.0:84] #1 phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/Generator.php(121): PHPUnit\Framework\MockObject\Generator->getObject()
[sqlite-php8.0:85] #2 phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/Invocation.php(149): PHPUnit\Framework\MockObject\Generator->getMock()
[sqlite-php8.0:86] #3 phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/InvocationHandler.php(129): PHPUnit\Framework\MockObject\Invocation->generateReturnValue()
[sqlite-php8.0:87] #4 phar:///usr/local/bin/phpunit/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code(24): PHPUnit\Framework\MockObject\InvocationHandler->invoke()
[sqlite-php8.0:88] #5 /drone/src/lib/private/Files/View.php(1182): Mock_Temporary_b8d464a7->filesize()
[sqlite-php8.0:89] #6 /drone/src/lib/private/Files/View.php(415): OC\Files\View->basicOperation()
[sqlite-php8.0:90] #7 [internal function]: OC\Files\View->filesize()
[sqlite-php8.0:91] #8 /drone/src/tests/lib/Files/ViewTest.php(2093): call_user_func_array()
[sqlite-php8.0:92] #9 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1254): Test\Files\ViewTest->testLockBasicOperationUnlocksAfterCancelledHook()
[sqlite-php8.0:93] #10 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(920): PHPUnit\Framework\TestCase->runTest()
[sqlite-php8.0:94] #11 phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php(596): PHPUnit\Framework\TestCase->runBare()
[sqlite-php8.0:95] #12 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(706): PHPUnit\Framework\TestResult->run()
[sqlite-php8.0:96] #13 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(506): PHPUnit\Framework\TestCase->run()
[sqlite-php8.0:97] #14 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(506): PHPUnit\Framework\TestSuite->run()
[sqlite-php8.0:98] #15 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(506): PHPUnit\Framework\TestSuite->run()
[sqlite-php8.0:99] #16 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(506): PHPUnit\Framework\TestSuite->run()
[sqlite-php8.0:100] #17 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(487): PHPUnit\Framework\TestSuite->run()
[sqlite-php8.0:101] #18 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(129): PHPUnit\TextUI\TestRunner->run()
[sqlite-php8.0:102] #19 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(98): PHPUnit\TextUI\Command->run()
[sqlite-php8.0:103] #20 /usr/local/bin/phpunit(1091): PHPUnit\TextUI\Command::main()
[sqlite-php8.0:104] #21 {main}
```
We may have hit a phpunit bug, not sure.

2023-02-02 14:54 UTC, come-nc commented
> We may have hit a phpunit bug, not sure.

Confirmed, should be fixed by phpunit update which was published in the docker image.

2023-02-02 15:00 UTC, come-nc commented
Rebased

2023-02-03 08:29 UTC, nickvergessen commented on lib/public/Files/Storage.php
> +	public function filesize(string $path): false|int|float;
This will break storage providers implementing this interface?

2023-02-03 08:29 UTC, nickvergessen commented on lib/public/Files/Storage/IStorage.php
> +	public function filesize(string $path): false|int|float;
This will break storage providers implementing this interface?

2023-02-03 08:29 UTC, nickvergessen commented on lib/public/Files/SimpleFS/ISimpleFile.php
> +	public function getSize(): int|float;
Needs documentation at least when we assume it does not have apps implementing it

2023-02-03 08:29 UTC, nickvergessen commented on tests/lib/Encryption/UtilTest.php
> +	 * @group BrokenTests
Please remove or better rebase on top of https://github.com/nextcloud/server/pull/36504

2023-02-03 08:29 UTC, nickvergessen commented on tests/lib/Route/RouterTest.php
> + * @group RoutingWeirdness
what

2023-02-06 07:54 UTC, come-nc commented on lib/public/Files/Storage.php
> +	public function filesize(string $path): false|int|float;
Yes but it will ensure they support 32bits.
I can move OCP type changes to phpdoc know that tests are passing if it is preferred.
But sadly it will also mean removing lots of typing from private classes implementing these interfaces, and it is this typing which allowed to catch a lot of 32bits related errors with the tests.

2023-02-06 07:57 UTC, come-nc commented on tests/lib/Route/RouterTest.php
> + * @group RoutingWeirdness
This group of tests only pass on drone, not on github CI or locally.
But they only fail when run as part of some group of tests, if you run only this class you have no trouble.
It has to do with include_once and how phpunit handles resetting the state between tests, I **think**.
At some point I had to stop trying to fix them and just skip them as their failure is not related to 32bit.

So I added them to a group that I skip in 32bit CI.

2023-02-06 08:10 UTC, come-nc commented on tests/lib/Encryption/UtilTest.php
> +	 * @group BrokenTests
rebased

2023-02-06 08:54 UTC, nickvergessen commented on lib/public/Files/Storage.php
> +	public function filesize(string $path): false|int|float;
Yeah I'm drawn apart. Could do a voting/opinion gathering

2023-02-06 20:44 UTC, nickvergessen commented
Github is complaining 🙈

2023-02-06 21:11 UTC, come-nc commented on lib/public/Files/Storage.php
> +	public function filesize(string $path): false|int|float;
Moved it to phpdoc

2023-02-07 07:34 UTC, nickvergessen approved these changes

2023-02-07 08:01 UTC, ChristophWurst requested changes, later dismissed
Breaking changes in the public API and we are past feature freeze

2023-02-07 08:01 UTC, ChristophWurst commented on lib/public/Files/SimpleFS/ISimpleFile.php
> +	public function getSize(): int|float;
Also apps that just work against the interface need to adjust for this.

2023-02-07 08:13 UTC, nickvergessen commented on lib/public/Files/FileInfo.php
> +	 * @return int|float
Is it actually breaking, or just making sure everyone is handling the floats that always where returned by 32bit systems.

2023-02-07 08:18 UTC, come-nc commented
The drone samba failure passes locally so false positive I think.
The kerberos one I’m failing to run locally. @icewind1991 Any idea?

2023-02-07 08:18 UTC, come-nc commented on lib/public/Files/FileInfo.php
> +	 * @return int|float
No, it always returned float of 32 bit, the documentation was just lying.

2023-02-07 08:24 UTC, ChristophWurst commented on lib/public/Files/FileInfo.php
> +	 * @return int|float
Fair enough.

2023-02-07 08:25 UTC, come-nc commented on lib/public/Files/SimpleFS/ISimpleFile.php
> +	public function getSize(): int|float;
Well this is the only way to not crash on 32bit for files over 2G. So application do have to handle float, but before they had to handle TypeError in the same situation, so I do not think this will bring any difference, if they rely on the var being int they will have a TypeError thrown from their code instead of being thrown from inside OC.

2023-02-07 10:09 UTC, come-nc commented
Samba kerberos failure actually seems to be #36314

2023-02-07 10:16 UTC, come-nc commented
/rebase

2023-02-07 13:08 UTC, merged

2023-02-21 13:02 UTC, DaphneMuller commented
hello @come-nc  
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

2023-03-22 13:40 UTC, MichaIng commented
@come-nc 
Why was this never backported to NC25? It is high likely what fixes quotas on NC26 while it is still broken on NC25. It is is overall to much/large, we could also cherry-pick some commits?

2023-03-27 10:02 UTC, come-nc commented
> @come-nc Why was this never backported to NC25? It is high likely what fixes quotas on NC26 while it is still broken on NC25. It is is overall to much/large, we could also cherry-pick some commits?

Several reasons, mainly this was fixed through strong typing using union type `int|float` which is only available on PHP 8.0 and higher, and thus cannot be used on 25.
So backporting would have meant doing it again using phpdoc instead of real typing.

Also you can see I had to change things in lib/public (OCP), which we tend to avoid on bugfix releases.

2023-03-27 11:21 UTC, MichaIng commented
Okay, makes sense. Then it will be some detectives work to find the part which fixes quota usage on Nextcloud 25. Or the monkeys task to translate all union types to phpdoc comments for backporting everything 😄. I'll see if I can do that, excluding CI and unrelated stuff.

> Also you can see I had to change things in lib/public (OCP), which we tend to avoid on bugfix releases.

In this cases it fixes bugs, so I think it is necessary. But I also think most of these are in NC25 already (phpdoc).

2023-04-21 18:33 UTC, MichaIng commented
PR up which backports most of the changes done here: #37877