Discover federatedsharing endpoints
nextcloud/server pull request #3614
Opened 2017-02-24 15:11 UTC by schiessle

Discover remote end points to exchange system address book in order to work with multiple cloud solutions

follow-up on https://github.com/nextcloud/server/pull/3611

2017-03-15 15:10 UTC, nickvergessen commented on apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
>  			$this->notifications = new Notifications(
this should be auto injectable, but we can do that in a new PR.

2017-03-15 15:17 UTC, nickvergessen requested changes

2017-03-15 15:17 UTC, nickvergessen commented on lib/private/Server.php
> +		return $this->query('OCSDiscoveryService');
`query(DiscoveryService::class)` should work too, then you can also remove the registration?

2017-03-15 15:17 UTC, nickvergessen commented on lib/private/Server.php
> +		return $this->query('OCSDiscoveryService');
Please also add:
```php
$this->registerService(IDiscoveryService::class, function($c) {
			return $this->getServer()->getOCSDiscoveryService();
		});
```
to `lib/private/AppFramework/DependencyInjection/DIContainer.php`

2017-03-16 09:16 UTC, schiessle commented on apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
>  			$this->notifications = new Notifications(
Not sure why we did it this way. It looks like that, at least in the past, it wasn't possible to inject it during runtime. That's why we set it to "null" by default, injected it for testing but created it directly during runtime.

I don't want to do general refactoring in this PR. So let's check this and change it if possible in a follow-up PR

2017-03-16 09:53 UTC, rullzer commented on apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
>  			$this->notifications = new Notifications(
I guess it is a relic before we had proper DI for apps. But agreed lets fix later!

2017-03-16 10:02 UTC, schiessle commented on lib/private/Server.php
> +		return $this->query('OCSDiscoveryService');
I added the second one.

Your first suggestion fails with this error:

````
{"reqId":"4EaQcnpW8N96XSC1kmDM","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve cacheFactory! Class cacheFactory does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('cacheFactory')\\n#1 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/ServerContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('cacheFactory')\\n#2 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(73): OC\\\\ServerContainer->query('cacheFactory')\\n#3 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OC\\\\\\\\OCS\\\\\\\\Discover...')\\n#5 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/ServerContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OC\\\\\\\\OCS\\\\\\\\Discover...')\\n#6 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Server.php(878): OC\\\\ServerContainer->query('OC\\\\\\\\OCS\\\\\\\\Discover...')\\n#7 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/apps\\\/federatedfilesharing\\\/lib\\\/AppInfo\\\/Application.php(102): OC\\\\Server->getOCSDiscoveryService()\\n#8 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/apps\\\/federatedfilesharing\\\/lib\\\/AppInfo\\\/Application.php(85): OCA\\\\FederatedFileSharing\\\\AppInfo\\\\Application->initFederatedShareProvider()\\n#9 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/apps\\\/federatedfilesharing\\\/appinfo\\\/app.php(42): OCA\\\\FederatedFileSharing\\\\AppInfo\\\\Application->getFederatedShareProvider()\\n#10 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(209): require_once('\\\/home\\\/schiesbn\\\/...')\\n#11 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(150): OC_App::requireAppFile(Object(OCA\\\\FederatedFileSharing\\\\AppInfo\\\\Application))\\n#12 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(125): OC_App::loadApp('federatedfilesh...')\\n#13 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/base.php(953): OC_App::loadApps()\\n#14 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","level":3,"time":"2017-03-16T09:36:43+00:00","method":"GET","url":"\/master\/index.php\/apps\/files\/","user":"admin","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.13"}
````

So I didn't implemented it yet. I saw the same error for another class in my log, I will add a separate issue so that we can sort it out. Once it is fixed we can change it here in a follow up PR

2017-03-21 16:03 UTC, schiessle commented
I think all comments are addressed... can we get this in? @rullzer @nickvergessen @icewind1991 ? Thanks!

2017-03-23 13:45 UTC, nickvergessen approved these changes
Works together with https://github.com/nextcloud/server/pull/3825

2017-03-27 08:54 UTC, rullzer approved these changes

2017-03-30 08:00 UTC, rullzer commented
@schiessle conflicts... could you resolve them?

Then afterwards I can have a look at the DI. since that changed slightly...

2017-04-05 18:29 UTC, schiessle commented
@rullzer merge conflicts solved, you can now look at the DI if you want

2017-04-12 13:25 UTC, rullzer commented
Good to go now I think!

2017-04-12 14:01 UTC, merged