[stable25] Fix/35886 replace custom tooltips with native one for personal and administration settings stable25
nextcloud/server pull request #36197
Opened 2023-01-17 16:38 UTC by JuliaKirschenheuter

- [x] :warning: This backport had conflicts and is incomplete

backport of #35901

2023-01-17 16:40 UTC, ChristophWurst requested changes

2023-01-17 21:06 UTC, nickvergessen commented on apps/settings/src/components/PersonalInfo/shared/FederationControlAction.vue
> -		{{ isSupportedScope ? tooltip : tooltipDisabled }}
Now the button has no text and no icon anymore?!

2023-01-17 21:06 UTC, nickvergessen commented on apps/theming/src/components/BackgroundSettings.vue
> +<<<<<<< HEAD
👀

2023-01-17 21:10 UTC, nickvergessen requested changes

2023-01-17 21:10 UTC, nickvergessen commented on apps/settings/src/components/PersonalInfo/shared/FederationControlAction.vue
> -		{{ isSupportedScope ? tooltip : tooltipDisabled }}
Ah, this is the thing I tried to find recently which breaks the profile fields in master:
Before | After
---|---
![Bildschirmfoto vom 2023-01-17 22-08-38](https://user-images.githubusercontent.com/213943/213013027-9ea1b185-9689-42ca-b82f-7ea577b47843.png) | ![Bildschirmfoto vom 2023-01-17 22-09-07](https://user-images.githubusercontent.com/213943/213013033-70c46d12-7dc3-4f29-bc90-ea200d4ad6fd.png)

2023-01-18 14:09 UTC, JuliaKirschenheuter commented
@nickvergessen 

Thank you! I will fix that problem as a follow-up ticket on master + will create a follow-up backport to stable25. Could we merge this PR or should i just close this one?

2023-01-18 21:49 UTC, nickvergessen commented
You can also just restore the deleted line in this pr and then we merge?
The we don't have to backport a second pr?

2023-01-19 11:31 UTC, nickvergessen commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
>  				@click.prevent="copyCloudId">
Something for a follow up, but there is no feedback on this. Others have a toast notification top right to say `Copied!` etc.

2023-01-19 11:31 UTC, nickvergessen approved these changes

2023-01-19 16:15 UTC, JuliaKirschenheuter commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
>  				@click.prevent="copyCloudId">
Thanks: https://github.com/nextcloud/server/pull/36250

2023-01-19 16:43 UTC, ChristophWurst commented
> fixup! build locally

FYI this is not how fixup commits are structured. Git won't be able to resolve what commit you are fixing up.

2023-01-19 16:46 UTC, ChristophWurst approved these changes

2023-01-19 19:15 UTC, Pytal approved these changes

2023-01-20 10:12 UTC, merged