allow sharees to edit certain calendar properties for themselves
nextcloud/server pull request #3620
Opened 2017-02-25 13:26 UTC by georgehrke

fixes #1463

2017-02-25 13:28 UTC, georgehrke commented
- [ ] `OCA\DAV\Files\CustomPropertiesBackend` has no test class yet -> add one

2017-03-01 12:25 UTC, georgehrke commented
please review @MorrisJobke @nickvergessen @rullzer

You can test this together with https://github.com/nextcloud/calendar/pull/354

The current problem in master:
Only the sharer can edit properties of a calendar. Sharees have to use the name / color given by the sharer.

What this branch fixes:
Sharees are now able to define a color / name on their own. Their choice doesn't affect the sharer nor any other sharees

2017-03-01 12:49 UTC, nickvergessen requested changes

2017-03-01 12:49 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Calendar.php
> +		// if calendar is shared, changes has to be made in properties table
...changes have to be made...

2017-03-01 12:49 UTC, nickvergessen commented on apps/dav/lib/Files/CustomPropertiesBackend.php
> +		if (substr($path, 0, 10) === 'calendars/' && substr_count($path, '/') === 2) {
this is `lib/Files` please register a copy instead which is living in `lib/CalDAV`

2017-03-01 12:49 UTC, nickvergessen commented on apps/dav/tests/unit/Files/CustomPropertiesBackendTest.php
> +}
missing NL

2017-03-01 12:57 UTC, georgehrke commented on apps/dav/lib/Files/CustomPropertiesBackend.php
> +		if (substr($path, 0, 10) === 'calendars/' && substr_count($path, '/') === 2) {
Yeah, I'm not to happy about this either.

But this plugin used to handle all custom properties :/
https://github.com/nextcloud/server/blob/master/apps/dav/lib/Server.php#L47
https://github.com/nextcloud/server/blob/master/apps/dav/lib/Server.php#L186

There is a more generic version at https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php but that's not used at all.

2017-03-01 13:03 UTC, georgehrke commented on apps/dav/tests/unit/Files/CustomPropertiesBackendTest.php
> +}
done

2017-03-03 22:24 UTC, georgehrke commented on apps/dav/lib/Files/CustomPropertiesBackend.php
> +		if (substr($path, 0, 10) === 'calendars/' && substr_count($path, '/') === 2) {
@nickvergessen What's your call on this?

This code is already hit when setting custom properties on calendars (e.g. `{http://owncloud.org/ns}calendar-enabled`).
As far as I can tell sabre provides no way to register different plugins based on the base path (like `calendars/` or `files/`)

The problem is imho not that we add calendar specific code to something in `Files/`, but rather that something in `Files/` manages custom properties for calendars and contacts in the first place.

2017-03-06 11:12 UTC, nickvergessen commented on apps/dav/lib/Files/CustomPropertiesBackend.php
> +		if (substr($path, 0, 10) === 'calendars/' && substr_count($path, '/') === 2) {
Yeah as said, just register a new one that handles caldav and one for carddav?
If that is possible it would be my call

2017-03-27 17:23 UTC, georgehrke commented
renamed OCA\DAV\Files\CustomPropertiesBackend -> OCA\DAV\DAV\CustomPropertiesBackend because it contains non-files specific code and was always used by CalDAV and CardDAV as well.

2017-04-03 12:40 UTC, schiessle approved these changes
tested and it works. Also the code looks good to me

2017-04-03 18:12 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-04-03 18:12 UTC, merged