Specify the parameters of FederatedFileSharing controllers
nextcloud/server pull request #36214
Opened 2023-01-18 11:46 UTC by nickvergessen

## Summary

In order to get closer to OpenAPI all controllers should be up to the state of art how to defining the parameters so they are documented.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-18 11:48 UTC, provokateurin commented
Shouldn't the parameters also be documented in the comment with explanations?

2023-01-18 11:49 UTC, nickvergessen commented
> Shouldn't the parameters also be documented in the comment …

Did that, just repushed because I forgot it on the first method

> … with explanations?

Not sure I'm fully qualified to provide this.

2023-01-18 11:51 UTC, provokateurin commented
Explanations could be copied from https://github.com/cs3org/OCM-API/blob/develop/spec.yaml

2023-01-18 12:00 UTC, provokateurin commented
It also doesn't matter too much right now, I'd just copy them later

2023-01-18 12:49 UTC, provokateurin requested changes

2023-01-18 12:49 UTC, provokateurin commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +	public function move(int $id, ?string $token = null, ?string $remote = null, ?string $remote_id = null) {
psalm complains remote can't be null so i guess it should not be nullable here?

2023-01-18 13:47 UTC, nickvergessen commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +	public function move(int $id, ?string $token = null, ?string $remote = null, ?string $remote_id = null) {
Previous controller code allowed it, but yeah it would have broken on that call then.
So save to assume it never was called with that.
Actually I assume all of the parameters were mandatory. It was just not enforce and defaulted to null and I'm unsure if anything else would break anything.

2023-01-18 13:49 UTC, provokateurin commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +	public function move(int $id, ?string $token = null, ?string $remote = null, ?string $remote_id = null) {
if it would fail with null values anyway, why not move it to an earlier stage where it fails before the method is even called

2023-01-19 08:30 UTC, nickvergessen commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +	public function move(int $id, ?string $token = null, ?string $remote = null, ?string $remote_id = null) {
I guess we could copy the types from https://github.com/cs3org/OCM-API/blob/develop/spec.yaml ?
Because that is what others would send anyway?

2023-01-19 09:25 UTC, provokateurin commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +	public function move(int $id, ?string $token = null, ?string $remote = null, ?string $remote_id = null) {
No, this API isn't implementing OCM (see discussion in the chat group)

2023-01-24 13:06 UTC, nickvergessen commented
Closing for now as it's the wrong endpoint

2023-06-14 07:23 UTC, provokateurin commented
This is relevant now. I reopened because I would have just created the same PR again.

2023-06-14 07:28 UTC, provokateurin approved these changes

2023-06-14 10:11 UTC, ChristophWurst approved these changes

2023-06-14 14:00 UTC, merged