Share type sciencemesh
nextcloud/server pull request #36228
Opened 2023-01-18 20:07 UTC by michielbdejong

* Resolves: #36227 

## Summary

Add the sciencemesh share type in all the places where share types are enumerated.

2023-01-19 16:17 UTC, solracsf commented
Can you look at PSALM + failed tests?

2023-01-25 07:47 UTC, juliushaertl requested changes
Looks reasonable, just two minor comments inline :)

2023-01-25 07:47 UTC, juliushaertl commented on apps/files_sharing/lib/Controller/DeletedShareAPIController.php
> +				$result = array_merge($result, $this->getSciencemeshShareHelper()->formatShare($share));
Seems like valid error since the getSciencemeshShareHelper is only defined in the ShareAPIController

2023-01-25 07:47 UTC, juliushaertl commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +				throw new OCSForbiddenException($this->l->t('Sharing %s failed because the back end does not support room shares', [$node->getPath()]));
```suggestion
				throw new OCSForbiddenException($this->l->t('Sharing %s failed because the back end does not support sciencemesh shares', [$node->getPath()]));
```

2023-01-26 12:06 UTC, michielbdejong commented on apps/files_sharing/lib/Controller/DeletedShareAPIController.php
> +				$result = array_merge($result, $this->getSciencemeshShareHelper()->formatShare($share));
Thanks! This was resolved.

2023-01-30 13:41 UTC, michielbdejong commented
Hm, only one 'spreed' integration test is failing now https://drone.nextcloud.com/nextcloud/server/29215/45/4
It's missing a file from autoload.php
I'll try to run this test in a dev environment.

2023-02-01 08:21 UTC, michielbdejong commented
@juliushaertl can you have a look please when you have time?

2023-02-08 12:02 UTC, michielbdejong commented
@juliushaertl please let us know if there is anything else we can do, we are waiting for this to be merged asap if possible.

2023-02-10 16:04 UTC, nickvergessen commented on lib/private/Share/Constants.php
> +	 * @deprecated 21.0.0 - use IShare::TYPE_SCIENCEMESH instead
When it's already deprecated, don't add it anymore?

2023-02-11 08:05 UTC, michielbdejong commented on lib/private/Share/Constants.php
> +	 * @deprecated 21.0.0 - use IShare::TYPE_SCIENCEMESH instead
I changed it to `// Note to developers: do not add new share types here`

2023-02-13 20:10 UTC, juliushaertl commented on lib/private/Share/Constants.php
> +    // Note to developers: Do not add new share types here
```suggestion
	// Note to developers: Do not add new share types here
```

2023-02-14 10:26 UTC, michielbdejong commented on lib/private/Share/Constants.php
> +    // Note to developers: Do not add new share types here
Thanks! I think this is the change I committed in https://github.com/nextcloud/server/pull/36228/commits/ddd991df4a59e26e8008593c177f41fd214c18c9 - it should be 1 tab, right?

2023-02-14 10:29 UTC, michielbdejong commented on lib/private/Share/Constants.php
> +    // Note to developers: Do not add new share types here
The GitHub viewer here has 8-space tabs and the one for https://github.com/nextcloud/server/commit/ddd991df4a59e26e8008593c177f41fd214c18c9 displays 4-space tabs. Also, when I click 'Sign off and commit suggestion' here, nothing happens, so I think this is correct OK now.
Will double-check this after the rebase.

2023-02-17 13:39 UTC, juliushaertl approved these changes
Code looks good 👍 

Mind to do another rebase to latest master to retriever the failed tests? Looks unrelated to me though...

2023-02-21 10:44 UTC, michielbdejong commented
> This workflow requires approval from a maintainer.

2023-02-24 14:27 UTC, michielbdejong commented
@skjnldsv can you maybe approve the workflows so this can be merged?

2023-02-24 14:29 UTC, michielbdejong commented
This has been stuck for 11 days now...

2023-03-02 08:25 UTC, michielbdejong commented
@juliushaertl Please merge this today if possible.

2023-03-07 09:08 UTC, michielbdejong commented
I'm giving a presentation about this at 3pm.
I think @karlitschek said we are maybe already too late for release 26 and we should target this to release 27 now?
What is the next step here? It would be great if this can still be merged today, before my presentation!

2023-03-08 13:37 UTC, juliushaertl approved these changes

2023-03-08 13:59 UTC, AndyScherzinger commented
@artonge can you look into the updating of the js bundle please? Thanks in advance

2023-03-08 15:40 UTC, artonge approved these changes

2023-03-08 17:31 UTC, juliushaertl commented
Closing as https://github.com/nextcloud/server/pull/37139 has been merged

2023-03-08 17:31 UTC, closed without merging