[WIP] Port user menu
nextcloud/server pull request #36232
Opened 2023-01-19 02:12 UTC by Pytal

* For https://github.com/nextcloud/server/issues/36201

## Summary

Move PHP user menu markup to Vue wrapped by NcHeaderMenu

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-25 02:15 UTC, Pytal commented
/backport to stable25

2023-01-25 06:00 UTC, nickvergessen commented on core/src/views/UserMenu.vue
> +		:aria-label="t('core', 'Open user menu')">
This was:
```suggestion
		:aria-label="t('core', 'Open settings menu')">
```

not sure which is better.

2023-01-25 06:01 UTC, nickvergessen reviewed
Not breaking the external sites app, if that is why my review was requested.
From the technical changes in this PR I'm the wrong person to judge

2023-01-25 06:15 UTC, juliushaertl commented on lib/private/TemplateLayout.php
> +			$this->initialState->provideInitialState('core', 'settingsNavEntries', $settingsNavigation);
Do we still need the above `settingsnavigation` template variable?

2023-01-25 06:16 UTC, juliushaertl commented on core/templates/layout.user.php
> +				<div id="settings"></div>
Maybe we could give this a more descriptive id in the same run?

2023-01-25 06:18 UTC, juliushaertl commented on apps/user_status/src/menu.js
> +const mountMenu = () => {
Can we be fully sure that the UserMenu has already been rendered at this point? Otherwise this might need some way of handling to not end up with a menu without the profile link which might become hard to debug later on.

2023-01-25 06:19 UTC, juliushaertl reviewed
Just some smaller comments, but looks good otherwise 👍

2023-01-25 06:22 UTC, nickvergessen commented on lib/private/TemplateLayout.php
> +			$this->initialState->provideInitialState('core', 'settingsNavEntries', $settingsNavigation);
Wondered the same, but I guess we do for other templates.

2023-01-25 06:28 UTC, juliushaertl commented on lib/private/TemplateLayout.php
> +			$this->initialState->provideInitialState('core', 'settingsNavEntries', $settingsNavigation);
`layout.user.php` seems to be the only occurrence

2023-01-26 02:04 UTC, Pytal commented on core/src/views/UserMenu.vue
> +		:aria-label="t('core', 'Open user menu')">
Not sure either but thinking was that the menu contains more than just settings, @nimishavijay @jancborchardt what should we label this?

2023-01-26 02:05 UTC, Pytal commented on lib/private/TemplateLayout.php
> +			$this->initialState->provideInitialState('core', 'settingsNavEntries', $settingsNavigation);
Removed!

2023-01-26 02:06 UTC, Pytal commented on core/templates/layout.user.php
> +				<div id="settings"></div>
Now `id="user-menu"`

2023-01-26 02:13 UTC, Pytal commented on apps/user_status/src/menu.js
> +const mountMenu = () => {
Should be as this is only executed when UserMenu has been mounted and emits `core:user-menu:mounted`

This only works as long as `apps/user_status/src/menu.js` is loaded before `core/src/components/UserMenu.js`, but if `UserMenu.js` loads and emits `core:user-menu:mounted` before `menu.js` can subscribe to the event then it wouldn't

For this I adjusted the logic to handle both cases

2023-01-26 06:07 UTC, skjnldsv commented on apps/user_status/src/menu.js
> +	const mountPoint = document.querySelector('li[data-id="user_status-menu-entry"]')
`data-id` ?

This doesn't seem like a valid selector to use for a mountpoint.
a proper `id=` should be used. Data selectors have a different purpose

2023-01-26 06:21 UTC, skjnldsv requested changes

2023-01-26 06:21 UTC, skjnldsv commented on apps/user_status/src/menu.js
> +	const mountPoint = document.querySelector('li[data-id="user_status-menu-entry"]')
`data-id` ?

This doesn't seem like a valid selector to use for a mountpoint.
a proper `id=` should be used. Data selectors have a different purpose

2023-01-26 06:21 UTC, skjnldsv commented on core/src/views/UserMenu.vue
> +		<nav class="user-menu__nav">
Missing `aria-label` https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role

2023-01-26 06:21 UTC, skjnldsv commented on apps/user_status/src/menu.js
> +	const mountPoint = document.querySelector('li[data-id="user_status-menu-entry"]')
I just saw that was what was used in the first place... :see_no_evil: 
Fee free to adjust this

2023-01-26 06:21 UTC, skjnldsv commented on apps/user_status/src/menu.js
> +	const mountPoint = document.querySelector('li[data-id="user_status-menu-entry"]')
While it's probably what everyone else is using, (like [firstrunwizard](https://github.com/nextcloud/firstrunwizard/blob/4ce69aef027411d52fba85eb63d46cde28cca5f1/js/about.js#L2)), they are also using various obsolete selectors like `#expanddiv`. So this PR is a breaking change anyway.
I would fall back and adjust to a simple `id`

2023-01-26 06:22 UTC, skjnldsv commented on core/src/views/UserMenu.vue
> +		:aria-label="t('core', 'Open user menu')">
If no reply from the design team, the original strings should be used.
Keep in mind there is also admin entries in here. `user menu` might also be misleading

2023-01-27 02:34 UTC, Pytal commented on apps/user_status/src/menu.js
> +	const mountPoint = document.querySelector('li[data-id="user_status-menu-entry"]')
Using `id` now with required https://github.com/nextcloud/firstrunwizard updates:
- https://github.com/nextcloud/firstrunwizard/pull/815
- https://github.com/nextcloud/firstrunwizard/pull/816

2023-01-27 08:13 UTC, skjnldsv approved these changes, later dismissed

2023-01-27 23:26 UTC, szaimen commented
I tested this together with https://github.com/nextcloud/firstrunwizard/pull/816 and clicking on `Personal settings` leads to internal server error. Also the firstrunwizard entry is in the list somehow not shown...

<details>
<summary>Click to show</summary>

![image](https://user-images.githubusercontent.com/42591237/215224424-758304d4-8e58-4fc6-aa04-6350382c3419.png)

</details>
<details>
<summary>Tested with </summary>

```
docker run -it \
--name nextcloud-easy-test \
-p 127.0.0.1:8443:443 \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
-e SERVER_BRANCH=enh/a11y-user-menu \
-e FIRSTRUNWIZARD_BRANCH=enh/a11y-user-menu-id \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

2023-01-30 19:05 UTC, nimishavijay commented on core/src/views/UserMenu.vue
> +		:aria-label="t('core', 'Open user menu')">
Agreed with @skjnldsv that it could be misleading, also we're trying not to use the wording "user" so "settings menu" is probably a better fit anyway

2023-01-30 20:20 UTC, szaimen commented on core/src/views/UserMenu.vue
> +		:aria-label="t('core', 'Open user menu')">
For the admin, it is personal settings...

2023-02-04 00:27 UTC, Pytal commented
Rebased

2023-02-07 21:35 UTC, szaimen approved these changes
Tested together with https://github.com/nextcloud/firstrunwizard/pull/816 and works now but didnt review the code.

(Looks like the internal server issue was somehow caused by the viewer app not being installed).

2023-02-09 17:48 UTC, artonge approved these changes

2023-02-11 03:22 UTC, merged