Update.js: countdown feedback before redirect
nextcloud/server pull request #3624
Opened 2017-02-25 19:19 UTC by marncz

Sorry for creating another PR but trying to get the process of committing right, hope you don't mind :) still learning git...

Fixes issue #1559

![image](https://cloud.githubusercontent.com/assets/9304594/23334069/29bb95da-fb8f-11e6-84ad-c0c541e7b2e8.png)

2017-02-28 18:25 UTC, MorrisJobke requested changes

2017-02-28 18:25 UTC, MorrisJobke commented on core/js/update.js
> +						$('<p>'+t('core', 'The update was successful. Redirecting you to Nextcloud in ')+'<span id="countdown"></span></p>')
This should be done differently. We support plural translations and this is needed here, because some languages have a different way to build a sentence.

```js
n('core', 'The update was successful. Redirecting you to Nextcloud in %n second.', 'The update was successful. Redirecting you to Nextcloud in %n seconds.', count)
```

So it's best to give the `<p>` an id and then update the whole string 😉

2017-03-03 12:52 UTC, marncz commented on core/js/update.js
> +						$('<p>'+t('core', 'The update was successful. Redirecting you to Nextcloud in ')+'<span id="countdown"></span></p>')
hmm, was not sure about the translation :)

thanks, that's a cool approach

2017-03-10 21:22 UTC, rullzer commented on core/js/update.js
> +						$('<p>'+t('core', 'The update was successful. Redirecting you to Nextcloud in ')+'<span id="countdown"></span></p>')
@marncz could you update your PR?

2017-03-13 13:07 UTC, ChristophWurst requested changes

2017-03-13 13:07 UTC, ChristophWurst commented on core/js/update.js
> +				 $("#countdown").html(i + " second");
- [ ] TODO: not translated
- [ ] TODO: use `.text(...)` instead

2017-03-13 13:07 UTC, ChristophWurst commented on core/js/update.js
> +			}, (4 - i) * 1000);
Kinda looks like a magic number. How about passing this constant as parameter too to make it a bit more explicit, like self.updateCountdown(i, 4), where the second parameter is named something like `from`

2017-03-14 19:50 UTC, marncz commented on core/js/update.js
> +			}, (4 - i) * 1000);
sure, working on those changes

2017-03-14 19:57 UTC, marncz commented on core/js/update.js
> +						$('<p>'+t('core', 'The update was successful. Redirecting you to Nextcloud in ')+'<span id="countdown"></span></p>')
@rullzer working on it now

2017-03-14 20:36 UTC, marncz commented
Done changes you pointed out, hope it's better now. Thanks for your patience! :) learned a lot

2017-03-14 21:29 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-03-14 22:29 UTC, ChristophWurst reviewed
One little formatting issue, besides that it looks very good now. Thanks :-)

2017-03-14 22:29 UTC, ChristophWurst commented on core/js/update.js
> +				  .removeClass('icon-loading-dark');
unnecessary whitespace change 😉

2017-03-16 06:56 UTC, rullzer commented
very nice @marncz 
Keep those PRs coming!

Also you could join our irc channel #nextcloud-dev on freenode if you are interested :)

2017-03-16 06:56 UTC, rullzer approved these changes

2017-03-16 06:56 UTC, merged

2017-03-28 21:52 UTC, jancborchardt commented
@marncz nice! :) Welcome to the community  – I added you to the Nextcloud organization as well and also to the `@nextcloud/javascript` team :)

2017-03-31 09:04 UTC, marncz commented
@jancborchardt 
Thanks! Looking for more issues to work on :)