feat(files) Update quota when updating storage statistics
nextcloud/server pull request #36301
Opened 2023-01-23 14:03 UTC by tpayen

* Resolves: #36300 [Files] Atomatically refresh quota of current folder when using folders with custom quota 

## Summary

It's free to update the quota at the same time as the storage statistics. This is very useful for folders with different quotas (like groupfolders)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-25 01:25 UTC, Pytal approved these changes

2023-01-25 15:06 UTC, artonge approved these changes

2023-01-25 15:08 UTC, artonge requested changes
Might actually be irelevant with https://github.com/nextcloud/server/pull/36002

@skjnldsv can you confirm?

2023-01-30 15:31 UTC, tpayen commented
> We should maybe discuss what it should look like when we're seeing a folder-quota. That could be confusing.

In fact I think it works just like any e-mail application (like Thunderbird or Roundcube for the ones I'm most familliar with) the quota shown is relative to the current mailbox/folder and that's pretty clear

2023-01-31 10:12 UTC, skjnldsv commented
@nimishavijay @jancborchardt, currently thi sis how it look:
![image](https://user-images.githubusercontent.com/14975046/215731284-6f972ff1-6b0a-4a47-9f92-eaea34cce18c.png)

When we enter a folder that have a different quota, could you tell us what it should look like? If we just adjust the display of the image above, I am afraid it would be confusing to the user to see their quota suddenly change. How can we make sure they understand the current folder they're in have a different quota than their global storage? :)

2023-01-31 14:54 UTC, nimishavijay commented
> I am afraid it would be confusing to the user to see their quota suddenly change.

Definitely agreed. A simple enough idea is: if the user is in a special folder, add the folder name to the end of the space info with a middle dot separator (looks great but will probably be ellipsised for most folder names) or on a new line (folder names more visible).

How it would look (switched the positions of the progress bar and text so that the progress bar remains closer to the quota info):
![image](https://user-images.githubusercontent.com/52440189/215791046-e418c099-212a-45b9-9f0f-a5521623947a.png)

![image](https://user-images.githubusercontent.com/52440189/215791272-78a5b34c-e229-4011-947e-19e7ad1b5762.png)

What do you think? I'm leaning towards the second one because it is more clear :)

2023-01-31 16:14 UTC, skjnldsv commented
Got it @nimishavijay 
Will do for 26 and above.

@tpayen considering this changed, we might drop that PR and only do this for the upcoming nc version

2023-02-01 10:00 UTC, tpayen commented
> @tpayen considering this changed, we might drop that PR and only do this for the upcoming nc version

Clearly, I close this one

2023-02-01 10:00 UTC, closed without merging