Allow configuring the location of the `appdata_[instanceid]` folder
nextcloud/server pull request #36337
Opened 2023-01-24 21:20 UTC by summersab

Allow configuring the location of the `appdata_[instanceid]` folder

Signed-off-by: summersab <arthur.summers@gmail.com>

* Resolves: #12873

## Summary
This allows administrators to change the location of the `appdata_[instanceid]` folder by specifying an `appdataroot` value in `config.php`. This is especially useful when using shared storage, object storage as primary storage (storing `appdata_[instanceid]` in an object store is extremely slow), etc.

## TODO

- [ ] Regardless of `appdataroot` being set, the function should really return `$rootFolder` and not `$rootFolder->get($folderName)`. The current code will store files in `/appdata_[instanceid]/appdata_[instanceid]` when an `appdataroot` is provided and `/appdata_[instanceid]` in normal operation (i.e. it will create a `/appdata_[instanceid]` folder on the mount point instead of writing directly to the mount point itself). Some apps such as OnlyOffice expect the `appdata_[instanceid]` folder to be in reference to the system root:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/504884f16ce2b66e45a66579aa3cdf0fd0197330/lib/templatemanager.php#L53

However, I am having permission issues. The system is able to create files and folders at the mount point, but when it tries to read the folders, they don't appear to exist, and errors are thrown. It seems to occur at this function: https://github.com/nextcloud/server/blob/75d7203f579f5761fc921d9506579bec48ebab74/lib/private/Files/Node/Folder.php#L161

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-25 08:43 UTC, tcitworld commented on lib/private/Files/AppData/AppData.php
> -	private IRootFolder $rootFolder;
**nitpick (blocking):** Type to a `LazyRoot` then.

2023-01-25 08:44 UTC, tcitworld commented on lib/private/Files/AppData/AppData.php
> +	private  $rootFolder;
**nitpick (blocking):** A `LazyRoot` is still an `IRootFolder`.

2023-01-25 11:58 UTC, kesselb commented
Thanks :+1: 

Can you have a look at tests/lib/Files/AppData/AppDataTest.php?

![image](https://user-images.githubusercontent.com/3902676/214557609-adae2be1-37a5-4d92-89d1-ad1de490c076.png)

2023-01-25 20:55 UTC, summersab commented on lib/private/Files/AppData/AppData.php
> +	private  $rootFolder;
Okay, I've never made a PR to a major project, before. How do I update a PR? I thought maybe pushing a change to my branch would update the PR, but that didn't work.

2023-01-26 23:58 UTC, summersab commented
@kesselb - I hope I did that right? I've never made a commit to a project as big as this.

2023-01-27 03:30 UTC, summersab commented
Does anyone know how to fix the issue of being able to write directly to the mount point instead of having to create a directory inside of the mount? It's some sort of permission issue. Without fixing it, anyone who uses this feature will have apps like OnlyOffice break.

2023-02-01 19:59 UTC, summersab commented
I hate to tag _everyone_, but I need a little help if this is to make it into NC 26.
@ArtificialOwl @icewind1991 @blizzz @kesselb @tcitworld 

I noticed that by default, the `appdata` folder has permissions of:
`OC::$server->getRootFolder()->get('/appdata_[instanceid]')->getPermissions() == 31`

After I add my mount point, I checked the same location (which is now the mount point of my storage instead of just a folder inside `/`), and I get permissions of 23. So, I tried adding a storage wrapper to the mount point like this. However, I STILL get permissions of 23. What am I doing wrong?

```
$this->rootFolder = new LazyRoot(function () use ($rootFolder, $systemConfig) {
	return $rootFolder;
	if ($appdataroot = $systemConfig->getValue('appdataroot', null)) {
		$instanceId = $systemConfig->getValue('instanceid', null);
		if ($instanceId === null) {
			throw new \RuntimeException('no instance id!');
		}

		$folderName = 'appdata_' . $instanceId;
		$storageFactory = new \OC\Files\Storage\StorageFactory();
		$storageFactory->addStorageWrapper('permissions_all', function ($mountPoint, IStorage $storage, IMountPoint $mount) {
			return new PermissionsMask([
				'storage' => $storage,
				'mask' => Constants::PERMISSION_ALL,
			]);
			return $storage;
		});

		$arguments = [
			'datadir' => $appdataroot,
		];
		$storage = new LocalRootStorage($arguments);
		$mount = new MountPoint($storage, $folderName, $arguments, $storageFactory);

		\OC::$server->getMountManager()->addMount($mount);

		// This is what ought to be returned - the root for AppData should be the actual root, not a folder inside the root
		return $rootFolder;//->get($folderName);
	}
	return $rootFolder;
});
```

2023-02-06 12:19 UTC, summersab commented
I thought I might nudge @icewind1991 since they seem like the most authoritative person when it comes to storage and mounts in NC. Thanks in advance for any help you can provide.

2023-02-08 15:53 UTC, summersab commented
I am still having trouble getting the mount point to have the correct permissions. I have tried a number of different methods, and this is one of them. Take note of the `perm` values at the end. How do I get the `/appdata_[instanceid]/` mount point to have permissions of 31 and operate as if it were a folder?
```
$this->rootFolder = new LazyRoot(function () use ($rootFolder, $systemConfig) {
	if ($appdataroot = $systemConfig->getValue('appdataroot', null)) {
		$instanceId = $systemConfig->getValue('instanceid', null);
		if ($instanceId === null) {
			throw new \RuntimeException('no instance id!');
		}

		$folderName = 'appdata_' . $instanceId;
		\OC\Files\Filesystem::initInternal($folderName);
		$arguments = [
			'datadir' => $appdataroot,
		];

		$mount = new MountPoint(LocalRootStorage::class, '/' . $folderName, $arguments, \OC::$server->getStorageFactory());
		\OC::$server->getMountManager()->addMount($mount);

		// Evaluates to 31
		$perm1 = $mount->getStorage()->getPermissions('');
		
		// Evaluates to 31; functionally the same as above
		$perm2 = \OC::$server->getMountManager()->getAll()["/$folderName/"]->getStorage()->getPermissions('');

		// Evaluates to 23. As such, `newFolder` will be able to create folders at the mount point, but `getFolder` cannot access them
		$perm3 = $rootFolder->get("/$folderName/")->getPermissions();
	}

	return $rootFolder;
}
```

2023-02-09 17:10 UTC, nickvergessen commented
Something went wrong with your rebase.

Try:
```
git checkout master
# Replace nextcloud with the name of the remote, if you don't know, post the result of `git remote -v`
git pull nextcloud master
git checkout appdata_location
git rebase -i nextcloud/master
# Remove all commits which are not yours, then save and exit
git push --force origin appdata_location
```

2023-02-09 17:25 UTC, summersab commented
> Something went wrong with your rebase.

Yeah, I'm not the best with git, yet. I think I fixed it.

My latest commit also fixes the issue I was having trouble with (being unable to use the root of the new mount as `appdata_[instanceid]`. It was a issue with the caching and `LocalRootScanner`. In short, the PR now works as intended.

2023-02-14 18:17 UTC, summersab commented
I do not understand why the tests are failing. Why on earth is it trying to compare `appdataroot` and `instanceid`?
```
1) Test\Files\AppData\AppDataTest::testGetFolder
Expectation failed for method name is "getValue" when invoked zero or more times
Parameter 0 for invocation OC\SystemConfig::getValue('instanceid', null) does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'appdataroot'
+'instanceid'
```

I have been stepping through the PHPUnit code, and the `InvocationHandler` is deciding that the invocation of `OC\SystemConfig::getValue('instanceid', null)` somehow matches `OC\SystemConfig::getValue('appdataroot', null)` despite the parameters being different. That makes no sense.

2023-02-14 23:43 UTC, summersab commented
I'm not sure that the errors in CI are related to me, and I'm not sure about the performance-8,0 check. Happy to fix them, though!

2023-02-17 09:01 UTC, jonas-w commented
@summersab i don't know much about the nextcloud CI/CD nor php, but i'm watching this issue as i want this feature too. I see that you are 334 commits behind, maybe the CI issues were already fixed in master, you would need to rebase your branch to master.

2023-02-17 18:32 UTC, summersab commented
Thanks for the comment, @jonas-w, and I'm glad someone else is wanting this feature.

I just merged and rebased, but now, I have two commits. I'm pretty sure one of the tests requires that there be only one commit. I don't think I want to squash my commit and the merged commit from upstream, though. I'm a novice with git, so I don't want to do much more and mess things up.

2023-02-20 16:12 UTC, szaimen commented
@summersab I can take care of rebasing if you want...

2023-02-20 21:01 UTC, szaimen commented
I had a look at the tests and https://github.com/nextcloud/server/actions/runs/4226966799/jobs/7340960268 and https://github.com/nextcloud/server/actions/runs/4226966804/jobs/7340960157 definitely seem to be caused by this PR.
But https://github.com/nextcloud/server/actions/runs/4226966796/jobs/7340959942 is not.

2023-02-23 20:30 UTC, summersab commented
@szaimen - I don't know what I did, and I certainly don't know how to fix it. My branch is all junked, now. Great.

2023-02-24 17:27 UTC, szaimen commented
> Fetching submodule 3rdparty
> fatal: remote error: upload-pack: not our ref

this one seems to be unrealted. Thanks for fixing the tests!

2023-06-25 17:02 UTC, susnux commented
Your branch is broken, something with the rebase gone wrong.

2023-06-25 17:34 UTC, summersab commented
Hmm - I'm not sure what went wrong. I decided to pick up this PR again after getting busy, so here's what I did:
```
git switch master
git fetch --all
git switch appdata_location
git rebase master
git push origin appdata_location  --force-with-lease
```

The rebase gave no indication of conflicts when I ran it - it only appeared once I checked over here. So, I edited the file, made a commit, rebased/squashed, and pushed again. Any suggestions?

2023-07-11 14:37 UTC, szaimen commented
Why is this still wip? Seems like tests are passing?

2023-07-11 14:54 UTC, summersab commented
> Why is this still wip? Seems like tests are passing?

@szaimen, I made it a draft because I suck at rebasing, and I didn't want to send notifications to the world. This should be good to merge, though - it's been ready for approval for awhile (in my opinion).

2023-07-13 17:19 UTC, summersab commented
Rebased on the latest master. Should be good to go.

Any chance of this getting merged in time for v27?

2023-07-18 12:37 UTC, summersab commented
> Sorry, the time frame for 27 is already over.

Okay, what is the process of getting this merged regardless of the v27 release?

2023-07-18 13:13 UTC, kesselb commented
> Okay, what is the process of getting this merged regardless of the v27 release?

If time allows, someone will look into your pull request.

2023-08-23 16:05 UTC, summersab commented on config/config.sample.php
> +'appdataroot' => '',
Good call! Done.

2023-08-25 13:45 UTC, summersab commented
Hmm - not sure why CI is angry with me. It looks like there might have been a network blip when trying to build?

cypress-summary doesn't provide anything useful, and the two runners are throwing errors on an EventDispatcher instance (which my PR doesn't touch):
`Error: Call to undefined method OC\Server::getEventDispatcher() in /var/www/html/console.php:94`

2023-08-28 13:16 UTC, nickvergessen commented on config/config.sample.php
> + * multiple Nextcloud systems. Defaults to `datadirectory` if unset.
> … when using shared storage for ``appdata_INSTANCEID`` between
> * multiple Nextcloud systems. …

This should not be mentioned and is not supported. Meta data of those files is stored in the database. Each Nextcloud server MUST use their own set of this data and it MUST NOT be shared between different installations.

2023-09-07 21:56 UTC, summersab commented on config/config.sample.php
> + * multiple Nextcloud systems. Defaults to `datadirectory` if unset.
Ah, I didn't realize that. I haven't run a multiserver installation, yet.

Fixed.

2023-09-11 15:11 UTC, blizzz commented on config/config.sample.php
> + * multiple Nextcloud systems. Defaults to `datadirectory` if unset.
I would even pledge for having a warning there, against configuring the same data dir for two or more instances. Only because it is mentioned, it does not mean some people would try exactly this.

2023-09-22 09:41 UTC, icewind1991 requested changes

2023-09-22 09:41 UTC, icewind1991 commented on lib/private/Files/AppData/AppData.php
> +				$storage = new LocalRootStorage($arguments);
This should just be `Local` not `LocalRootStorage`

2023-09-22 09:41 UTC, icewind1991 commented on lib/private/Files/AppData/AppData.php
> +		$this->rootFolder = new LazyRoot(function () use ($rootFolder, $systemConfig) {
Why are you creating a new `LazyRoot`?

2023-09-22 09:41 UTC, icewind1991 commented on lib/private/Files/Cache/LocalRootScanner.php
> +		return $path === '' || str_starts_with($path, 'appdata_') || str_starts_with($path, '__groupfolders') || str_starts_with($mountPoint, '/appdata_');
If you want to stop the scanner from touching the new appdata mountpoint, you can instead create a storage with a "noop" scanner.

2024-02-15 17:58 UTC, susnux commented
> Is there still work that needs to be done here? Seems like this has been idle for quite some time.

See the unresolved comments above, so yes there is work to be done.
But feel free to fork and contribute on the feature :)

2024-05-02 14:40 UTC, skjnldsv commented
Closing this pull request due to lack of recent activity and updates. We appreciate your contribution and encourage you to reopen or provide further updates if necessary. :relaxed: 
Our aim is to keep the project moving forward with active collaboration. Thank you for your understanding and continued support! :pray:

2024-05-02 14:40 UTC, closed without merging

2024-05-02 14:58 UTC, luxzg commented
Wait, you closed an issue due to inactivity, issue that had already started development and people are actively waiting for it? If you want activity I will repost comment here every week so issue is "active". I don't think that's what is expected, and is usually considered spam on GitHub, but after this closing it seems this project has different code of conduct - "spam us if you want the feature".

Please be reasonable and keep the issue open until it is finished, reviewed and accepted.

It was planned for NC 26, then 27, 28, 29... I have no words...

2024-05-02 15:15 UTC, ChristophWurst commented
> It was planned for NC 26, then 27, 28, 29...

For your information: assigning to a milestone is not a sign of planning. All PRs are moved to the next milestone after the branch-off.
This PR is waiting for the author or someone else to finish the work, then it can be merged. The requested changes had been pending for half a year.

2024-05-02 15:24 UTC, luxzg commented
Ok, sorry for misinterpreting the closing comment, it was just for this commit which indeed got stale, not the original issue. Hopefully someone will step up to finish the needed work.