fix(CI): Install composer dependencies of Talk
nextcloud/server pull request #36389
Opened 2023-01-26 14:29 UTC by nickvergessen

* Resolves: N/A

## Summary

Ref https://github.com/nextcloud/spreed/pull/8578
Found in https://github.com/nextcloud/server/pull/36310#issuecomment-1405068637

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-26 14:35 UTC, ChristophWurst approved these changes
:pray:

2023-01-26 18:13 UTC, danxuliu requested changes
[CI is not happy](https://drone.nextcloud.com/nextcloud/server/29226/45/3):
```
+ composer install --no-dev
/bin/sh: composer: not found
```

2023-01-27 02:09 UTC, vitormattos commented on .drone.yml
> +  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
Have a problem during execution of `composer install`:

```
  - bamarni/composer-bin-plugin 1.8.2 requires composer-plugin-api ^2.0 -> no matching package found.
```

The composer version of this image is very old:

https://github.com/nextcloud/docker-ci/blob/master/php8.0/Dockerfile#L18

2023-01-27 08:41 UTC, ChristophWurst commented
you can also use `ci` as prefix for conventional commits. tools that generate changelogs would then hide the commit. a fix would be listed as a fix on the product. end of nitpick.

2023-01-27 09:04 UTC, nickvergessen commented
So, we are green and good again :)

2023-01-27 09:20 UTC, blizzz approved these changes

2023-01-27 09:29 UTC, merged