Do not open the sidebar automatically on small widths
nextcloud/server pull request #36409
Opened 2023-01-27 13:12 UTC by szaimen

2023-01-27 13:15 UTC, adityaraute requested changes

2023-01-27 13:15 UTC, adityaraute commented on apps/files/js/filelist.js
> +						if (document.documentElement.clientWidth < 1024 / 2) {
What is the purpose of 1024 / 2? Why not put a value directly

2023-01-27 13:17 UTC, szaimen commented on apps/files/js/filelist.js
> +						if (document.documentElement.clientWidth < 1024 / 2) {
fixed

2023-02-02 18:03 UTC, szaimen commented
/backport to stable25

2023-02-02 18:09 UTC, Pytal approved these changes

2023-02-03 06:44 UTC, skjnldsv approved these changes

2023-02-03 09:08 UTC, szaimen commented
CI failure inrelated

2023-02-03 09:08 UTC, merged

2023-02-03 10:27 UTC, ChristophWurst commented
/backport to stable25

2023-02-03 10:28 UTC, ChristophWurst commented
testing https://github.com/nextcloud/backportbot/pull/364

2023-02-03 10:28 UTC, szaimen commented
Already manually backported. But we can close it again...

2023-02-03 10:29 UTC, ChristophWurst commented
> testing [nextcloud/backportbot#364](https://github.com/nextcloud/backportbot/pull/364)

I know.

2023-02-03 10:40 UTC, ChristophWurst commented
Yay. It fails :tada: