user_status: Add OpenAPI spec
nextcloud/server pull request #36408
Opened 2023-01-27 12:20 UTC by provokateurin

## Summary

Adapts the code to make it friendly for https://github.com/nextcloud-gmbh/openapi-extractor and add the automatically generated spec.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-30 10:52 UTC, come-nc requested changes

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Controller/HeartbeatController.php
> +								StatusService    $service) {
This spacing is not consistent with the rest of the code base.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Several `@return` is not allowed it seems, see psalm errors.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Controller/HeartbeatController.php
> -		/** @psalm-suppress UndefinedInterfaceMethod */
You need to put back this psalm-suppress comment, or to fix the psalm error in an clean way.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Controller/PredefinedStatusController.php
> +	 * @return DataResponse<PredefinedStatus[]> 200
DataResponse is not a template in the current code base. Remove the parameter or update the docblocks of DataRepsonse to make it a template.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Controller/PredefinedStatusController.php
>  		}));
```suggestion
		return new DataResponse(array_filter($this->predefinedStatusService->getDefaultStatuses(), fn (PredefinedStatus $status) => $status->isVisible()));
```
In this instance using the `fn` keyword is improving readability I think.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/ClearAt.php
> +	public function __construct(protected string $type, protected string|int $time) {
```suggestion
	public function __construct(
		protected string $type, 
		protected string|int $time,
	) {
```

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/PredefinedStatus.php
> +	public function __construct(protected string $id, protected string $icon, protected string $message, protected ?ClearAt $clearAt, protected ?bool $visible) {
Same thing, one property per line please.

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/PrivateUserStatus.php
> +	public function __construct(protected string $userId, protected ?string $message, protected ?string $messageId, protected bool $messageIsPredefined, protected ?string $icon, protected int|ClearAt|nu
Same

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/PredefinedStatus.php
> +		return $this->visible != false;
```suggestion
		return $this->visible ?? false;
```
Would it be possible to instead type the property as bool and have a default value in constructor?

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/PredefinedStatus.php
> +			'visible' => $this->visible,
It’s okay to have null here in the json?

2023-01-30 10:52 UTC, come-nc commented on apps/user_status/lib/Model/Response/PublicUserStatus.php
> +	public function __construct(protected string $userId, protected ?string $message, protected ?string $icon, protected int|ClearAt|null $clearAt, protected string $status) {
One prop per line

2023-02-01 07:42 UTC, provokateurin commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Yeah this is still a problem I have no solution for. I really need to have this working, but I don't know how. Only a single return annotation is kind of impossible or will get really ugly.

2023-02-01 07:44 UTC, provokateurin commented on apps/user_status/lib/Controller/PredefinedStatusController.php
>  		}));
Didn't know that existed!

2023-02-01 07:56 UTC, provokateurin commented on apps/user_status/lib/Model/Response/PredefinedStatus.php
> +			'visible' => $this->visible,
Not sure, I've gone with the default value now so it will never be null.

2023-02-08 22:04 UTC, provokateurin commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Wdym? We probably found a solution for this problem, but I first need to test it.

2023-02-09 07:44 UTC, nickvergessen commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
https://www.php.net/manual/de/language.attributes.syntax.php it something we could use in Nextcloud 26+ as it requires PHP8+

Sample in https://github.com/nextcloud/server/pull/36363

2023-02-09 07:58 UTC, provokateurin commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Hm I see, but it wouldn't help with static analysis, right? The idea seems pretty good though.

2023-02-09 15:48 UTC, christianlupus commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
If you define am attribute and scan statically for that attribute, you can find these. You might be able to use reflections to let the PHP parser do the scanning even. 
As PHP 7 is EOL, it should be good to go in general.
You could add a parameter to the attribute that contains an array. The keys would be the status codes and the value either a string of even a structure to describe the status.

2023-02-09 16:07 UTC, provokateurin commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Yes, but this won't help psalm validate the code in the method, right?

2023-02-09 20:43 UTC, christianlupus commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Maybe i got the problem wrong. Are you concerned about static code analysis using psalm or about the extraction of the API specification from the code?
For psalm a single return should be sufficient, right?

2023-02-09 23:08 UTC, provokateurin commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	 * @return DataResponse 400 Invalid status to update
Both. Please let us discuss this in https://github.com/nextcloud/server/issues/36513#issuecomment-1424276606

2023-02-10 21:36 UTC, closed without merging