Allow empty route for navigation entries
nextcloud/server pull request #36449
Opened 2023-01-31 03:19 UTC by Pytal

## Summary

Some apps register navigation entries with empty routes e.g. https://github.com/nextcloud/server/blob/9035be6b81fc527a57dcbbbb424dc9a84aef832b/apps/user_status/appinfo/info.xml#L18

This allows these entries to pass `xmllint` used in https://github.com/nextcloud/.github/blob/ff4a6f1eacb53e4d3b5721e57743eb64242178a7/workflow-templates/lint-info-xml.yml

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-01-31 03:19 UTC, Pytal commented
/backport to stable25

2023-01-31 06:15 UTC, nickvergessen commented
- [ ] patch also in appstore

2023-01-31 06:15 UTC, nickvergessen commented
- [ ] patch also in appstore

2023-01-31 06:53 UTC, nickvergessen commented on resources/app-info-shipped.xsd
> -        <xs:restriction base="non-empty-string">
Instead allowing empty, just allow no occurrences of the route tag?🤔
Sounds easier and more straight forward, but might require additional PHP fallbacks

2023-01-31 08:27 UTC, JuliaKirschenheuter approved these changes

2023-01-31 09:14 UTC, nickvergessen commented
- [ ] Should also edit https://github.com/nextcloud/server/blob/master/resources/app-info.xsd
- [ ] Also edit appstore https://github.com/nextcloud/appstore/blob/d13958626c7a20e33032289e79dab155a967075b/nextcloudappstore/api/v1/release/info.xsd

2023-01-31 09:14 UTC, nickvergessen requested changes
See comments

2023-01-31 17:28 UTC, Pytal commented on resources/app-info-shipped.xsd
> -        <xs:restriction base="non-empty-string">
Was exactly the initial idea, but because this is needed for https://github.com/nextcloud/server/pull/36232 for NC25 accessibility, the minimally invasive solution here prevents the need to backport some potentially breaking changes to i.e. https://github.com/nextcloud/server/blob/ca3f53ab88b06c8ceea5d7991ff40641a9820728/lib/private/NavigationManager.php and https://github.com/nextcloud/server/blob/ca3f53ab88b06c8ceea5d7991ff40641a9820728/lib/private/App/InfoParser.php

2023-02-01 08:50 UTC, nickvergessen commented on resources/app-info-shipped.xsd
> -        <xs:restriction base="non-empty-string">
Here is the necessary PHP patch:
```diff
diff --git a/lib/private/NavigationManager.php b/lib/private/NavigationManager.php
index b78d9fa1ed8..f24a2f0ac25 100644
--- a/lib/private/NavigationManager.php
+++ b/lib/private/NavigationManager.php
@@ -315,7 +315,8 @@ class NavigationManager implements INavigationManager {
 				$id = $nav['id'] ?? $app . ($key === 0 ? '' : $key);
 				$order = isset($nav['order']) ? $nav['order'] : 100;
 				$type = isset($nav['type']) ? $nav['type'] : 'link';
-				$route = $nav['route'] !== '' ? $this->urlGenerator->linkToRoute($nav['route']) : '';
+				$route = $nav['route'] ?? '';
+				$route = $route !== '' ? $this->urlGenerator->linkToRoute($route) : '';
 				$icon = isset($nav['icon']) ? $nav['icon'] : 'app.svg';
 				foreach ([$icon, "$app.svg"] as $i) {
 					try {
```

2023-02-03 01:24 UTC, Pytal commented
Superseded by https://github.com/nextcloud/server/pull/36508

2023-02-03 01:24 UTC, closed without merging