Feature/ldap update profile
nextcloud/server pull request #36565
Opened 2023-02-06 15:43 UTC by march42

* Resolves: #32085

## Summary
Implement feature, to update user profile data from LDAP attributes.
Add configuration items for LDAP attribute mapping (Administration - LDAP/AD integration - Advanced - User Profile Attributes)
Add methods for user profile properties to lib/private/User/User.php
Add connections for LDAP attributes to user profile properties

## TODO
- [ ] Testing with various setting and scenario

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
Hopefully! I am unsure, how to check and eventually edit.
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
![Screenshot (Nextcloud 2)](https://user-images.githubusercontent.com/5712929/217013965-ec751920-6d14-45de-9455-5044e1b63eea.png)
![Screenshot (1)](https://user-images.githubusercontent.com/5712929/217010632-5ab0f259-1d96-4f7f-8220-b455f9386cb3.png)

- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
[currently](https://github.com/march42/nextcloud-documentation/tree/feature/ldap_update_profile) seperate PR following
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-13 08:59 UTC, come-nc reviewed
The feature will be popular I think but the code needs to be refined.
Also we must be very careful about performance in user_ldap, this should have no performance impact when not used.

@Pytal Can you review this? It’s a lot related to the profile system.

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		if (is_null($profileScope) || '' === $profileScope || 'unset' === $profileScope) {
```suggestion
		if ($profileScope === '' || $profileScope === 'unset') {
```
But when is it 'unset' ?

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```
What are these unset for?

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +	private function updateProfile(string $property, $valueFromLDAP, $scope=null) {
```suggestion
	 */
	private function updateProfile(string $property, $valueFromLDAP, ?string $scope=null): void {
```

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			return $value;
```suggestion
			return;
```

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			return '';
```suggestion
			return;
```

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +				$user = $this->userManager->get($this->uid);
For each configured profile property you will fetch the user again. You should prepare an array of profile values to apply and give that to your method, which could then fetch the user only once.

2023-02-13 08:59 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			$this->config->deleteUserValue($this->getUsername(), 'user_ldap', $property);
profile properties need to be set both on user and in config?

2023-02-13 08:59 UTC, come-nc commented on lib/private/User/User.php
> +	public function getProfilePropertyValue($property): ?string {
Are you sure all those proxy methods are needed? What prevents user_ldap from getting the account itself?

2023-02-14 10:05 UTC, march42 reviewed
cleanup: remove unneeded unset

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
habit: cleaning up the memory used, to ease garbage collection
I would remove all but the last, to unclutter it

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 10:05 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
```suggestion
```

2023-02-14 11:36 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		if (is_null($profileScope) || '' === $profileScope || 'unset' === $profileScope) {
When choosen in the advanced configuration tab. The administrator chooses profileScope from unset, v2-private, v2-local, v2-federated, v2-published. If using 'unset' it means the user can set these self in the profile.

2023-02-14 12:33 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +				$user = $this->userManager->get($this->uid);
Sounds good, I will look into this.

2023-02-15 00:14 UTC, Pytal commented on lib/public/IUser.php
> +	 * @since 25.0.0
```suggestion
	 * @since 27.0.0
```

2023-02-15 00:14 UTC, Pytal commented on lib/public/IUser.php
> +	 * @since 25.0.0
```suggestion
	 * @since 27.0.0
```

2023-02-15 00:14 UTC, Pytal commented on lib/public/IUser.php
> +	 * @since 25.0.0
```suggestion
	 * @since 27.0.0
```

2023-02-15 00:14 UTC, Pytal commented on lib/public/IUser.php
> +	 * @since 25.0.0
```suggestion
	 * @since 27.0.0
```

2023-02-15 00:14 UTC, Pytal commented on lib/private/User/User.php
> +	 * @return string|null AccountProperty value
```suggestion
	 * @return ?string AccountProperty value
```

2023-02-15 00:14 UTC, Pytal commented on lib/private/User/User.php
> +	 * @return string|null AccountProperty scope
```suggestion
	 * @return ?string AccountProperty scope
```

2023-02-15 00:14 UTC, Pytal commented on lib/private/User/User.php
> +	 * @return string|null AccountProperty verified
```suggestion
	 * @return ?string AccountProperty verified
```

2023-02-17 14:14 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +			$this->config->deleteUserValue($this->getUsername(), 'user_ldap', $property);
No, I remove this. I used it to easily check the data with `occ user:setting` command.

2023-02-27 10:10 UTC, march42 commented
I reworked the code:

- prepare and propagate an array with the profile data from LDAP and fetching user just once. Like @come-nc suggested.
- added Fediverse profile property
- did some cleanup and simplification
- fixed messages from psalm

2023-02-27 13:54 UTC, come-nc requested changes
See my last comment, please go through the accountmanager instead of adding methods to `OCP\User`.

Also, could you please detail how this will behave for multivalue fields from LDAP?

Regarding scope, if I understand correctly the admin can force a given scope for all profile data synced from LDAP?
What happens if the user then changes the scope?

Is it possible for the admin to leave the scope option empty to let users decide the scope of each information?

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		if(0 < count($profileValues)) {
```suggestion
		if (count($profileValues) > 0) {
```

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		unset($attr);
I’m still not comfortable with those unset, we are not micromanaging memory anywhere else in our code like this.

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		if(0 == count($profileValues)) {
```suggestion
		if (count($profileValues) == 0) {
```

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			if (isset($propertyValue[0])) {
This is always true, no?

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			/** @var string $propertyValue */
```suggestion
			/** @var string[] $propertyValue */
```

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +				/** @var string $value */
```suggestion
```

2023-02-27 13:54 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +					$this->logger->error('property does not exist: '.$property.' for user '.$this->getUsername().'', ['app' => 'user_ldap']);
```suggestion
					$this->logger->error('property does not exist: '.$property.' for user '.$this->getUsername().'', ['app' => 'user_ldap', 'exception' => $e]);
```

2023-02-27 13:54 UTC, come-nc commented on lib/private/User/User.php
> +	public function getProfilePropertyValue($property): ?string {
You should use `IAccountManager::getAccount($user)` to get the account,
then `IAccount::setProperty` for each property, and then `IAccountManager::updateAccount($account)`.

There is no need to add methods to OCP\IUser for this.

2023-02-27 13:57 UTC, come-nc commented
> I have found, that some commits are not correctly signed-off. Seems to be like all commits through GitHub Desktop. So I would probably best rebase the branch before you finally merge it. Any suggestions?

You can use `rebase` with `--signoff` option.
For instance `git rebase HEAD~25 --signoff` will add a signoff to the last 25 commits.

2023-02-28 14:54 UTC, come-nc commented
> Now, you got me a little pissed, because you were unspecific and I think I'm not supposed to read your mind. I'll be specific, so we could find an agreement on how to handle. First of all. I feel unappreciated, even unseen. I created my branch in May 2022, after issue 32085 was opened. see [#32085 (comment)](https://github.com/nextcloud/server/issues/32085#issuecomment-1119313753) I invested time, to package my quick'n'dirty hack and pretty it up, before committing to GitHub. I updated the documentation, run numerous test and checked different scenarios. Nobody seemed to care, until February 2023, when I was asked to make a pull request. 

I’m sorry you feel that way, that was not my intention of course.
I do not follow feature requests in the issues closely as we already have a lot on our plate. So I only became aware of this when the PR was open and I got pinged for a review.
I’m used to reviewing code from collegues and being picky about it, to try to merge the best code as possible. Sorry if that felt like too much complains, your work is appreciated of course. As I previously stated I think this feature will be welcomed by users.

> I don't need this to be integrated. I don't have any intentions on wasting my time or your time. I have two working solutions and patching after update is done in minutes. If this is unwanted or unappreciated, I'm happy with closing and deletion. This is your call to make. After your suggestions two weeks ago I took time, to rework the code and test on current version 25 and version 26 beta 3 and 4. […] I took time, to rewrite the code and even more time to test it and cleanup the coding. Now I have to go back and do it again, because your suggestions were too cautious phrased. I'm not very happy with this and I will have to make time for this next weekend. 

I am happy with the refactoring you did regarding fetching the user and I do not think it overlaps that much with going through the account intead of `OCP\IUser`.
Only the calls to `$user->setProfileProperty` will need to change on user_ldap side.

> 2. What do you want me to do with those unset. I don't want you to be uncomfortable. I did, what I thought was intended. Looking at the original code of processAttributes, for example version 25 starting line 162, you can see a number of unset($attr) in lines 172, 192, 201, 232. I used that present code as guideline for my coding. I am pretty unaffected by wether or not those are present. I’m still not comfortable with those unset, we are not micromanaging memory anywhere else in our code like this. Like I said, You are doing it in your code exactly in the questioned processAttributes function. What should I do to make you comfortable? 3. I will take time, to ckeck and test this specifically and add more clearification to the documentation.

Thank you for the pointers on processAttribute, that’s code from before I joined Nextcloud, I did not see much unset in the rest of the code.
I was just afraid by merging those unset of setting a precedent and having unsets added everywhere in the code. Because I do not understand why these local vars should be unset more than any other.
@blizzz Do you remember what is the rationale behind the `unset` calls in `processAttribute`?

Thank you for your details on scope handling, that sounds quite reasonable.

If this is eating too much of your time I can take it from here if your prefer.

2023-03-07 19:36 UTC, march42 commented
> I’m sorry you feel that way, that was not my intention of course.
> I’m used to reviewing code from collegues and being picky about it, to try to merge the best code as possible.
> Sorry if that felt like too much complains,

Thanks. I needed to address it anyways.
I'm here with you. I, myself too, love being picky about coding and following rules.
I felt like being pushed to decide things, not my decision to make. Espacially the `unset` commands. I would have just removed all of them, if you had just told me to do so. I was just not willing to make this decision on my own.

> I am happy with the refactoring you did regarding fetching the user and I do not think it overlaps that much with going through the account intead of `OCP\IUser`. Only the calls to `$user->setProfileProperty` will need to change on user_ldap side.

Thanks. Now I have done the rest, like you suggested and I removed the added code from IUser interface.

> If this is eating too much of your time I can take it from here if your prefer.

Thank you for the offer. I think I have it almost finished for now. I finished the code and finally did the rebase. For now, I'm testing and trying to find scenarios where it fails or crashes.

2023-03-07 19:47 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +		$accountManager = \OC::$server->get(IAccountManager::class);
Is this a good way to get an accountManager instance, to work with?

2023-03-07 20:01 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +				$scope = ($profileScope ? $profileScope : ($accountProperty->getScope() ? $accountProperty->getScope() : AccountManager::DEFAULT_SCOPES[$property]));
I got the idea, that `AccountManager::DEFAULT_SCOPES[$property]` doesn't get changed by setting `account_manager.default_property_scope` in `config.php` - do I need to check this config setting extra?

2023-03-09 15:10 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +		$accountManager = \OC::$server->get(IAccountManager::class);
```suggestion
		$accountManager = Server::get(IAccountManager::class);
```
This with a `use OCP\Server` at the beginning of the file is the preferred way now.
The best is to use DI (Dependency Injection) in the constructor, but here for a user object it’s more complicated because it’s not a singleton. In this instance I think it’s fine to use a get here.

2023-03-09 15:16 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +				$scope = ($profileScope ? $profileScope : ($accountProperty->getScope() ? $accountProperty->getScope() : AccountManager::DEFAULT_SCOPES[$property]));
DEFAULT_SCOPES is a const, it never changes.
You can see in AccountManager.php line 674 that it merges that with values from the config file to build the actual default scope.

Ideally you should not have to use AccountManager since it’s in `OC` and not `OCP`.
But it seems you found a missing feature from OCP here.
So either we’d need to add a getPropertyDefaultScope method to `OCP\IAccountManager`, or a magic value to give setProperty when wanting to use the default scope. (either null or a new IAccountManager::VISIBILITY_DEFAULT)
@Pytal What do you think, did I miss something?

2023-03-09 15:21 UTC, come-nc commented on apps/user_ldap/lib/User/User.php
> +			catch (PropertyDoesNotExistException $e) { // thrown at getProperty
It can be thrown by getProperty if the property do not exist. You should leave it there, if Account is ever modified to remove one of the property you use we will get a clean handling instead of a misterious crash. Better safe than  sorry

2023-03-09 15:33 UTC, come-nc approved these changes
Apart from the tiny default scope question, all good!

Just tested and confirm it works.

2023-03-10 08:32 UTC, march42 commented on apps/user_ldap/lib/User/User.php
> +				$scope = ($profileScope ? $profileScope : ($accountProperty->getScope() ? $accountProperty->getScope() : AccountManager::DEFAULT_SCOPES[$property]));
Looking into the code again, I think about removing the scope handling from my code and only use `Account::getProfileScope`

- I added this, to make sure all profile data stays on my server setting `v2-local`
- using the `config.php` `account_manager.default_property_scope` is more flexible and the user stays in control
- I want to rely on the defaults - using config.php and existing mechanisms
- new user will have empty profile with default scope applied
- if user changes property scope it will be used (CAN be both, pro and con ... and IS users choice)

2023-03-17 11:15 UTC, Pytal commented
Are the FIXMEs still to be done in this PR @march42?

2023-03-18 19:27 UTC, march42 commented
> Are the FIXMEs still to be done in this PR @march42?

@Pytal yes. I couldn't find a scenario, where those two checks against null in User.php (line 590 and 596) updateProfile will be true. I left them in there for "better safe than sorry" purpose.

Currently I'm doing some more testing and digging and found another question with profile handling. If I set phoneNumber to "0971..." in LDAP it gets formated to "+49971..." in user profile. And the next check in updateProfile (line 615) it get set again. I found this is not a big performance issue and think I need to add to documentation and clearify for the LDAP admin how the attributes should be prepared.
While checking with multi line attributes streetAddress and userBiography I noticed streetAddress has CRLF line ending and userBiography has a $ dollar sign instead of CR or LF. Here I need to double check again, where those difference comes from - OpenLDAP server or the configuration client. And I want to check Nextcloud, how multi line property should be formated here.
So, I was/am thinking about adding data formatting to processAttributes, at least for multi line values.

2023-03-20 08:08 UTC, come-nc commented
> Currently I'm doing some more testing and digging and found another question with profile handling. If I set phoneNumber to "0971..." in LDAP it gets formated to "+49971..." in user profile. And the next check in updateProfile (line 615) it get set again. I found this is not a big performance issue and think I need to add to documentation and clearify for the LDAP admin how the attributes should be prepared. While checking with multi line attributes streetAddress and userBiography I noticed streetAddress has CRLF line ending and userBiography has a $ dollar sign instead of CR or LF. Here I need to double check again, where those difference comes from - OpenLDAP server or the configuration client. And I want to check Nextcloud, how multi line property should be formated here. So, I was/am thinking about adding data formatting to processAttributes, at least for multi line values.

The $ thing is the postal address format in LDAP: https://www.rfc-editor.org/rfc/rfc4517#section-3.3.28
This is the complicated thing about allowing the admin to choose any attribute to map, there are many different syntaxes out there.

2023-03-20 12:25 UTC, march42 commented
> The $ thing is the postal address format in LDAP: https://www.rfc-editor.org/rfc/rfc4517#section-3.3.28
Yes, thank you, you're absolutely right. I did not remember this.

> This is the complicated thing about allowing the admin to choose any attribute to map, there are many different syntaxes out there.
And in most cases I would just tell the admin which syntax I want/need.
Last year I thought about implementing a formating syntax instead of plain attribute names. So the admin could format like "street+<CR>+postalCode+<SPACE>+l" and I decided this would be too much and dropped it.
My second thought was using the attributes syntax OID and mapping based on that. And right now I think this would be my preffered way to go.

BTW: now I can explain the reformatting of my phone numbers - E.123 format in LDAP allows many different syntaxes, i used international with dashes for separation, while E.164 in Nextcloud wants international without delimiters.

BUT: every checking and formatting here can/will have a performance impact.

2023-03-23 14:23 UTC, march42 commented
> Are the FIXMEs still to be done in this PR @march42?

@Pytal I finished and removed the FIXMEs.

2023-03-31 00:25 UTC, Pytal approved these changes

2023-03-31 10:23 UTC, march42 commented
I changed my LDAP directory and have `nextcloud-user-profile.schema` a modified version of @blizzz `nextcloud.schema` (i think from the univention app) with attributes for all the fields added. I have no idea, where to put this or/and if I should ignore.

2023-04-04 16:47 UTC, blizzz commented
> I changed my LDAP directory and have `nextcloud-user-profile.schema` a modified version of @blizzz `nextcloud.schema` (i think from the univention app) with attributes for all the fields added. I have no idea, where to put this or/and if I should ignore.

That .schema file is an old format to define LDAP schemas, which may be imported to the LDAP server. This is nothing Nextcloud deals with.

2023-04-17 21:49 UTC, szaimen commented
Merge?

2023-04-20 09:03 UTC, march42 commented
> Merge?

If you're asking me, then yes.

2023-04-20 09:23 UTC, merged

2023-04-20 09:53 UTC, come-nc commented
There are open questions in https://github.com/nextcloud/documentation/pull/9614