Add events to `QueryBuilder` class
nextcloud/server pull request #36572
Opened 2023-02-07 06:21 UTC by summersab

## Summary
This provides events before and after the execution of QueryBuilder objects in order to modify QueryBuilder elements, the query results, or both. While it may seem like this is only useful for niche applications, there are valid instances where intercepting DB queries and results are extremely useful (or even necessary).

One application that I have implemented for my organization is adding column-level encryption on a per-user basis. Without being able to access the QueryBuilder class immediately before execution, this integration would be impossible.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-07 06:25 UTC, summersab commented
I didn't see how to implement tests for `Event` or `EventDispatcher` classes. There are tests for the deprecated dispatcher. There is also the ability to create a mock `IEventDispatcher`, but my class doesn't create a new `IEventDispatcher` - rather, it gets the class from `OC::$server`.

That said, if there are applicable tests which I need to implement, I would be happy to add them.

2023-02-07 07:12 UTC, nickvergessen commented
> or even generate query-level logs

This is already available by setting the following config:
https://github.com/nextcloud/server/blob/dde5c46a3eb7c6dcee47795590619ccd393577d2/config/config.sample.php#L2225-L2232

Regarding the events:From my POV this looks like an interesting idea, but it has the option to fail very hard performance-wise.

Regarding column encryption: Also any user that has access to the database mostlikely also has access to the source code, so the encryption is not helping a lot. Which use/attack case are you trying to prevent?

2023-02-07 08:13 UTC, summersab commented
> Regarding the events:From my POV this looks like an interesting idea, but it has the option to fail very hard performance-wise.

Yes, this is true - if used incorrectly, these events can be a huge performance failure. However, based on my early usage of this code, there really isn't a noticible performance hit when done well. (Also, let's be honest. Plenty of integrations have the _potential_ for bad performance unless you build them right. Some would be even worse than this). 

> Regarding column encryption: Also any user that has access to the database mostlikely also has access to the source code, so the encryption is not helping a lot. Which use/attack case are you trying to prevent?

The integration I wrote uses `AES_ENCRYPT`/`AES_DECRYPT` (MariaDB) or `pgcrypto` (PostgreSQL) in combination with the `IProvideUserSecretBackend` class to encrypt user data in the DB using a user-specific secret. Based on the tables and columns present in a given query, my code adds the required functions to the `QueryBuilder` object in order to encrypt and decrypt user data. It may seem questionable, but it works  quite well, and I have not noticed a performance hit.

That said, yes - this is a very unique implementation with very specific use-cases, and it could lead to negative effects. However, those use-cases DO exist. Also, there are other NC APIs that can impact performance even worse when used incorrectly.

Thank you for your feedback. Let me know if you have further questions, comments, or suggestions - happy to discuss!

2023-02-07 09:50 UTC, nickvergessen commented
> in combination with the IProvideUserSecretBackend class to encrypt user data in the DB using a user-specific secret

I get that, but the server might need to write data without the user password being available (e.g. in a background job, or when others trigger an update of "your" data. So the server is able to encrypt/decrypt and therefor also the sysadmin and any one that hacks themselves access to the server.
That's the reason why I wonder which of the attack vectors you are trying to prevent.

2023-02-07 15:20 UTC, summersab commented
Well, I decided to use `IProvideUserSecretBackend` in my implementation (which comes with a number of limitations like you mentioned like background jobs - I have taken this into account with my setup). It is also possible to use something like the NC server secret for encrypting database columns, and all features work as expected.

Database encryption is my particular use-case for this PR, but I am sure there are other reasons why these events might be usefulm

2023-02-07 20:46 UTC, summersab commented
@nickvergessen, I took some metrics to address the subject of performance. This is not the most scientific calculation, but it provides a rough estimate. I created a contact in NC and edited it multiple times. Then, I enabled my `QueryBuilder` events and encryption logic, created a new contact, and edited it the same way. This was done on a pretty small VM with 1vCPU and 8GB RAM. Here are the results:
```
# of Queries  Avg (Default)    Avg (Encrypted)  Difference         Query
6             0.0009931723277  0.00150179863    0.0005086263021    DELETE FROM `*PREFIX*cards_properties` WHERE (`cardid` = :dcValue1) AND (`addressbookid` = :dcValue2)
36            0.0005187855826  0.00106041299    0.0005416274071    INSERT INTO `*PREFIX*cards_properties` (`addressbookid`, `cardid`, `name`, `value`, `preferred`) VALUES(:dcValue1, :dcValue2, :name, :value, :preferred)
6             0.0003132025401  0.000682870547   0.0003696680069    SELECT `id` FROM `*PREFIX*cards` WHERE (`uri` = :dcValue1) AND (`addressbookid` = :dcValue2)
18            0.0004307428996  0.0009056540097  0.0004749111101    SELECT `id`, `uri`, `lastmodified`, `etag`, `calendarid`, `size`, `calendardata`, `componenttype`, `classification`, `deleted_at` FROM `*PREFIX*calendarobjects` WHERE (`calendarid` = :dcValue1) AND (`uri` = :dcValue2) AND (`calendartype` = :dcValue3)
30            0.0004283030828  0.002046084404   0.001617781321     SELECT `id`, `uri`, `lastmodified`, `etag`, `size`, `carddata`, `uid` FROM `*PREFIX*cards` WHERE (`addressbookid` = :dcValue1) AND (`uri` = :dcValue2) LIMIT 1
5             0.001100826263   0.002524375916   0.001423549652     UPDATE `*PREFIX*cards` SET `carddata` = :dcValue1, `lastmodified` = :dcValue2, `size` = :dcValue3, `etag` = :dcValue4, `uid` = :dcValue5 WHERE (`uri` = :dcValue6) AND (`addressbookid` = :dcValue7)
```

Again, this is just _my_ use-case for adding `Event` dispatchers to the `QueryBuilder` class. There are probably other uses. With that said, it is pretty clear that the performance hit is negligible.

2023-02-13 05:15 UTC, summersab commented
What else is required for this PR? I'm not sure how to make CI happy...

2023-02-14 08:31 UTC, nickvergessen commented
> The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result

But the biggest problem is technical. This is a very fragile thing to be added. It comes with great risk (performance and listing to the event while triggering a SQL query will cause an infinite loop) and therefore we are currently unsure if this is the way to go, especially since the target usecase is soo limited. It does not even prevent admins from doing "bad" things, as they have access to the keys as well. So the only thing it would help against is when your database storage is stolen but not the nextcloud one?

2023-02-14 16:13 UTC, summersab commented
I completely understand the concerns regarding the events being very fragile and risky. However, I would like to respectfully push back a little.

Many existing events in NC are fragile, risky, can lead to infinite loops, and allow admins to do bad things. There are events that allow developers to interact with the authentication process, user/group creation, and even password updates. Are there really that many use cases for `OCP\Security\Events\GenerateSecurePasswordEvent`? As far as I can see, it is only used by the `password_policy` app. However, it IS available for all developers to use if they wish. That would allow them to do some pretty bad things.

My proposed events really aren't much different. Yes, the use cases are limited, but so are many events. That doesn't mean that there aren't valid use cases.

Yes, directly accessing database queries is generally avoided because it is risky, but there are TONS of internal elements of the NC framework already exposed to developers. Many of them are just as risky.

Yes, this could lead to infinite loops if improperly used, but even the most benign APIs can lead to infinite loops if not used correctly. This has happened to every developer at some point.

I think this is the nature of open source and security. Systems should be as malleable as possible (even if it is risky) so developers don't have to "hack" system internals. In turn, developers should make their code available for public review and scrutiny. With that in mind, which option is more responsible?
1. I could fork NC, edit these classes, and implement my code. This would allow me to move forward, but I would have to edit core files, and it breaks the code signing in NC.
2. I could continue to politely petition for this PR to officially provide access to the `QueryBuilder` class even though there are risks and very few use cases (ahem - `GenerateSecurePasswordEvent`). This would make NC more malleable so I can write a proper integration for NC without hacking into core classes.

Either method will accomplish the same goal, but I think the second option is much more responsible. That is why I am pursuing it.

2023-02-17 19:33 UTC, summersab commented
Any thoughts on how to better structure this and still provide the same sort of functionality, @nickvergessen? It's a touchy integration, but I'd like to stop overriding classes in my NC instances. Plus, I could provide my app that enables per-user column encryption, and I think a lot of people would benefit from that.

2023-02-20 07:43 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/Events/AfterQueryExecuted.php
> +namespace OC\DB\QueryBuilder\Events;
Should be moved to the public namespace `OCP` and located in `lib/public/...`

2023-02-20 07:43 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/Events/BeforeQueryExecuted.php
> +namespace OC\DB\QueryBuilder\Events;
Should be moved to the public namespace `OCP` and located in `lib/public/...`

2023-02-20 15:54 UTC, summersab commented on lib/private/DB/QueryBuilder/Events/BeforeQueryExecuted.php
> +namespace OC\DB\QueryBuilder\Events;
Done - thank you!

2023-02-20 16:00 UTC, nickvergessen commented
You modified 3rdparty? That should not be needed.

On that note, what is needed is `bash build/autoload....`

2023-02-23 19:00 UTC, summersab commented
Crap. I don't know how I managed to modify 3rdparty. That certainly wasn't intentional. I'm trying to figure out how to revert all of this - sorry for being such a noob.

2023-02-24 13:05 UTC, summersab commented
@nickvergessen, the postgres11-php8.0 CI test is failing because Postgres fails to respond. I don't think this is an issue with my code - the test just failed to properly run, I believe.

2023-02-24 13:11 UTC, nickvergessen commented
Yeah, seems unrelated

2023-02-24 14:56 UTC, summersab commented
Looks like I've finally gotten this past CI - hurrah!

Sorry for being such a noob on this PR. It's my first PR to a project this complex, so I had a lot to learn.

2023-02-28 20:28 UTC, summersab commented
@nickvergessen - my docblocks had issues, but I sorted them. Everything looks good except the `performance-8.0` check. It's failing on cloning `3rdparty` even though I don't touch those libs in my PR. The same thing happened in another PR I have open, and a maintainer said it didn't appear to be caused by me.

Let me know it there's anything else I need to do for this PR. Thank you for all of your help and patience!

2023-03-01 08:55 UTC, nickvergessen commented
Yeah should be unrelated here too. Mostlikely because it's a fork and not pushed to our org

2023-03-01 16:21 UTC, summersab commented
Cool. Anything else I need to do for review and approval except patiently wait on the devs (who are swamped with finalizing v26)?

2023-03-02 16:31 UTC, nickvergessen commented
> Anything else I need to do for review and approval

I guess it's fine

2023-03-06 09:05 UTC, ChristophWurst reviewed
My (opinionated) design review

https://event-driven.io/en/whats_the_difference_between_event_and_command/

2023-03-06 09:05 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/Events/AfterQueryExecuted.php
> +	public function setQueryBuilder(IQueryBuilder $queryBuilder) {
I'm not a fan of mutable events and therefore would prefer to not have any setters on this object

dispatching an event should allow other code to hook into another application event (something that happened), not alter it in my opinion

2023-03-06 09:05 UTC, ChristophWurst commented on lib/public/DB/QueryBuilder/Events/BeforeQueryExecuted.php
> + * @since 26.0.0
27

2023-03-06 09:06 UTC, ChristophWurst commented
> [ChristophWurst](/ChristophWurst) added the [ pending documentation ](/nextcloud/server/labels/pending%20documentation)

New OCP api requires documentation. E.g. https://docs.nextcloud.com/server/18/developer_manual/app/events.html#available-events

2023-07-08 15:49 UTC, joshtrichards commented
Linked open Issue this PR is associated with seems to be #28923

2023-07-14 11:52 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/Events/AfterQueryExecuted.php
> +class AfterQueryExecuted extends Event {
According to https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#naming-scheme this should be named:
```suggestion
class QueryExecutedEvent extends Event {
```

2023-07-14 11:52 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/Events/AfterQueryExecuted.php
> +	public function setQueryBuilder(IQueryBuilder $queryBuilder) {
While I agree, I think the idea here was to exactly do that. The planned app rewrites the queries and decrypts the results where needed

2023-07-14 11:52 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/Events/BeforeQueryExecuted.php
> +class BeforeQueryExecuted extends Event {
According to https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#naming-scheme this should be named:
```suggestion
class BeforeQueryExecutedEvent extends Event {
```

2023-07-18 13:58 UTC, nickvergessen requested changes

2023-07-18 13:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		$event = new AfterQueryExecuted($this, $result);
```suggestion
		$event = new QueryExecutedEvent($this, $result);
```

2023-07-18 13:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		$event = new BeforeQueryExecuted($this);
```suggestion
		$event = new BeforeQueryExecutedEvent($this);
```

2023-07-18 13:58 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +use OCP\DB\QueryBuilder\Events\AfterQueryExecuted;
```suggestion
use OCP\DB\QueryBuilder\Events\BeforeQueryExecutedEvent;
use OCP\DB\QueryBuilder\Events\QueryExecutedEvent;
```

2023-07-18 13:58 UTC, nickvergessen commented on 3rdparty
I guess this is a bug from rebasing.

2023-07-18 14:27 UTC, summersab commented on 3rdparty
Yeah, I'm not sure what happened, here. Anything I need to do to resolve?

2023-07-18 14:31 UTC, summersab commented on lib/public/DB/QueryBuilder/Events/BeforeQueryExecuted.php
> +class BeforeQueryExecuted extends Event {
> While I agree, I think the idea here was to exactly do that. The planned app rewrites the queries and decrypts the results where needed

This is correct. However, I CAN get by with just executing the query in my app and setting the result - the QueryBuilder::execute method checks for the existence of a result and uses that if necessary. I added the setter just as a convenience. I believe I can take it out and still have the same functionality.

2023-07-19 15:33 UTC, summersab commented on lib/private/DB/QueryBuilder/QueryBuilder.php
> +		$this->dispatcher = \OC::$server->get(IEventDispatcher::class);
I think I can make that happen. However, I'm going to push back a little. There are a number of places throughout Nextcloud where this exact method is used (many of which include you as an author, actually):
https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/core/Application.php#L85

https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/lib/private/Files/Cache/Cache.php#L127

https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/apps/dav/lib/Server.php#L107

https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/apps/dav/lib/RootCollection.php#L67

If I were to inject it as a constructor argument, I would need to edit anywhere the QueryBuilder is instantiated, correct (looks like `OC\DB\Connection` is the only place)?

2023-07-19 15:36 UTC, summersab commented on lib/public/DB/QueryBuilder/Events/AfterQueryExecuted.php
> +	public function setQueryBuilder(IQueryBuilder $queryBuilder) {
> While I agree, I think the idea here was to exactly do that. The planned app rewrites the queries and decrypts the results where needed

As noted elsewhere in the discussion:

This is correct. However, I CAN get by with just executing the query in my app and setting the result - the QueryBuilder::execute method checks for the existence of a result and uses that if necessary. I added the setter just as a convenience, if I recall. I believe I can take it out and still have the same functionality.

2023-07-20 15:36 UTC, summersab commented
> > [ChristophWurst](/ChristophWurst) added the [ pending documentation ](/nextcloud/server/labels/pending%20documentation)
> 
> 
> New OCP api requires documentation. E.g. https://docs.nextcloud.com/server/18/developer_manual/app/events.html#available-events

I opened the following PR as a draft so it can be merged pending the approval of this PR:
https://github.com/nextcloud/documentation/pull/10791

2023-07-21 23:18 UTC, summersab commented
Okay, why does updating the autoloaders wind up modifying some two dozen files with my PR? That's not right, but if I don't, CI isn't happy. I'm not sure what's going on, here.

2023-07-23 13:28 UTC, tcitworld commented
Keep the changes in `lib/`, drop the ones in `apps/`.

2023-07-24 16:16 UTC, summersab commented
> Keep the changes in `lib/`, drop the ones in `apps/`.

I didn't make any changes to apps. I just ran the composer update script, and it decided to modify all of these. Why?

2024-08-03 16:43 UTC, closed without merging