Refactor app loading
nextcloud/server pull request #36591
Opened 2023-02-07 16:05 UTC by come-nc

## TODO

- [ ] Move loadApp to AppManager
- [ ] Move away from server::get as much as possible
- [ ] Move needed methods to AppManager to avoid calling OC_App
- [ ] TBC…

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-08 15:25 UTC, come-nc commented
This is not bringing the expected performance boost, but it does cleanup things and move away from legacy OC_App, so I think it’s still worth to be merged.

2023-02-08 17:29 UTC, ChristophWurst commented
> This is not bringing the expected performance boost, but it does cleanup things and move away from legacy OC_App, so I think it’s still worth to be merged.

Clean code > fast code :wink:

2023-02-08 17:34 UTC, ChristophWurst approved these changes
Looks good

2023-02-08 17:34 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +			// TODO check if this if makes sense
todo in this PR or later?

2023-02-08 17:34 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +			if (in_array($type, $appTypes)) {
pass `true` for strict comparison

2023-02-08 17:34 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +	 * @return array
```suggestion
	 * @return string[]
```

2023-02-08 17:34 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +		if (count($this->appTypes) == 0) {
```suggestion
		if (count($this->appTypes) === 0) {
```

or

```suggestion
		if (empty($this->appTypes)) {
```

2023-02-08 17:34 UTC, ChristophWurst commented on lib/private/legacy/OC_App.php
> +	 * @deprecated 26.0.0 call \OC::$server->get(IAppManager::class)->isType($app, $types)
```suggestion
	 * @deprecated 26.0.0 use IAppManager::isType
```

to not encourage service locators

2023-02-08 17:35 UTC, ChristophWurst commented
Nit: clean up the git history. Either in the three steps described in the PR or one atomic change. Future bisectors will thank you :)

2023-02-09 08:49 UTC, come-nc commented on lib/private/App/AppManager.php
> +			// TODO check if this if makes sense
The sooner the better.
The problem here is that I had to keep checks in OC_App before calling the AppManager loadApps, because when not installed we cannot built the AppManager. I do not know if this is the same for maintenance flag or if we can check it here instead.

2023-02-09 12:08 UTC, come-nc commented
Squashed and rebased on master

2023-02-10 13:14 UTC, juliusknorr approved these changes

2023-02-13 07:36 UTC, juliushaertl commented
Conflicts ;)

2023-02-13 10:07 UTC, come-nc commented
> Conflicts ;)

:disappointed: These are not easy to fix, the loadApp method modifications from @icewind1991 about event logging need to be transposed in the appmanager instead

2023-03-20 14:34 UTC, merged

2023-03-26 07:55 UTC, nickvergessen requested changes
Please document in https://github.com/nextcloud/server/issues/37039

2023-03-26 07:55 UTC, nickvergessen commented on lib/public/App/IAppManager.php
> +	 * @since 26.0.0
```suggestion
	 * @since 27.0.0
```

2023-03-26 07:55 UTC, nickvergessen commented on lib/public/App/IAppManager.php
> +	 * @since 26.0.0
```suggestion
	 * @since 27.0.0
```

2023-03-26 07:55 UTC, nickvergessen commented on lib/public/App/IAppManager.php
> +	 * @since 26.0.0
```suggestion
	 * @since 27.0.0
```

2023-03-26 07:55 UTC, nickvergessen commented on lib/public/App/IAppManager.php
> +	 * @since 26.0.0
```suggestion
	 * @since 27.0.0
```

2023-03-26 07:55 UTC, nickvergessen commented on lib/private/legacy/OC_App.php
> +	 * @deprecated 26.0.0 use IAppManager::isType
```suggestion
	 * @deprecated 27.0.0 use IAppManager::isType
```

2023-03-26 07:55 UTC, nickvergessen commented on lib/private/legacy/OC_App.php
> +	 * @deprecated 26.0.0 use IAppManager::loadApp
27 (and for the others too)