optimize LazyUserFolder::getMountPoint
nextcloud/server pull request #36609
Opened 2023-02-08 12:50 UTC by icewind1991

no need to do a full setup when we can just get the mountpoint we want.

2023-02-08 14:36 UTC, come-nc requested changes
Psalm is angry

2023-02-14 12:29 UTC, icewind1991 commented
made psalm happy

2023-02-14 13:56 UTC, come-nc approved these changes

2023-02-16 09:22 UTC, juliushaertl approved these changes

2023-03-09 08:46 UTC, merged

2023-03-09 08:47 UTC, blizzz commented
@icewind1991 should this be backported to 26?