Fix/35626 no heading nor tab index for settings pages
nextcloud/server pull request #36640
Opened 2023-02-09 15:29 UTC by JuliaKirschenheuter

* Resolves: https://github.com/nextcloud/server/issues/35626

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-10 13:25 UTC, JuliaKirschenheuter commented
/backport to stable25

2023-02-10 14:39 UTC, nickvergessen requested changes

2023-02-10 14:39 UTC, nickvergessen commented on apps/settings/src/router.js
> +		document.getElementById('pageHeadingLevel2').textContent = `${t('settings', 'Subsection: ')} ${metaTitle}`
Breaks translations

https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#improving-your-translations

2023-02-10 14:39 UTC, nickvergessen commented on core/templates/layout.user.php
> +				<?php p($l->t('Section').': ').p(!empty($_['application'])?$_['application']:''); ?>
Breaks translations
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#improving-your-translations

2023-02-10 14:39 UTC, nickvergessen commented on core/templates/layout.user.php
> +				<?php p($l->t('Subsection').': ').p(!empty($_['pageTitle'])?$_['pageTitle']:''); ?>
Breaks translations
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#improving-your-translations

2023-02-10 14:39 UTC, nickvergessen commented on core/templates/layout.user.php
> +			<h1 class="hidden-visually">
Iirc only 1 h1 is allowed per page. T
So this makes all pages with an existing h1 not valid anymore

2023-02-10 14:39 UTC, nickvergessen commented on core/templates/layout.user.php
> +				<?php p($l->t('Section').': ').p(!empty($_['application'])?$_['application']:''); ?>
Also I'm really unsure about the Section and Subsection words being added. They seem to not add useful information (and bring troubles with translations and more)

I would try to not add this generic in the layout templates but fix it in the content area of the app which might even have a matching h1 and h2 already

2023-02-10 14:50 UTC, JuliaKirschenheuter commented on core/templates/layout.user.php
> +			<h1 class="hidden-visually">
sure, thanks. wanted to take it away, but forgotten. Such heading with always same content make no sense.

2023-02-10 14:54 UTC, JuliaKirschenheuter commented
@michaelnissenbaum could you please tell your opinion about naming of new headings. Or please suggest which one could sound better. Thank you!

2023-02-13 14:27 UTC, JuliaKirschenheuter commented on apps/settings/src/router.js
> +		document.getElementById('pageHeadingLevel2').textContent = `${t('settings', 'Subsection: ')} ${metaTitle}`
thanks

2023-02-13 14:28 UTC, JuliaKirschenheuter commented on core/templates/layout.user.php
> +				<?php p($l->t('Section').': ').p(!empty($_['application'])?$_['application']:''); ?>
ok, thanks

2023-03-02 11:09 UTC, ChristophWurst requested changes

2023-03-02 11:09 UTC, ChristophWurst commented on apps/settings/src/router.js
> +import Accessibility from '../../../core/src/OCP/accessibility'
import the function directly

2023-03-02 11:09 UTC, ChristophWurst commented on core/src/OCP/accessibility.js
> +	 * Set a page title to h1 header
```suggestion
	 * Set the page heading
```

2023-03-02 11:09 UTC, ChristophWurst commented on core/src/OCP/accessibility.js
> +	setPageTitle(pageTitle) {
```suggestion
	setPageHeading(heading) {
```

because the title of a page is easily confused with document title

2023-03-02 11:09 UTC, ChristophWurst commented
The new `OCP.Accessibility` function should go into the developer documentation

2023-03-02 14:23 UTC, ChristophWurst commented on apps/settings/src/router.js
> +import Accessibility from '../../../core/src/OCP/accessibility.js'
Import only the function you need plase, not the full module

2023-03-02 14:23 UTC, JuliaKirschenheuter commented on apps/settings/src/router.js
> +import Accessibility from '../../../core/src/OCP/accessibility'
in a case of core/src/OCP/accessibility.js i'm exporting default object with functions and not 2 independent functions. In this case it is not possible to make an destruction 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

2023-03-02 15:54 UTC, ChristophWurst commented on apps/settings/src/router.js
> +import Accessibility from '../../../core/src/OCP/accessibility'
You can change the module to have a named export of the free function `setPageHeading` and also use that function in the default export object. This should help with tree shaking.

2023-03-03 11:57 UTC, JuliaKirschenheuter commented on apps/settings/src/router.js
> +import Accessibility from '../../../core/src/OCP/accessibility'
Am i resolved this issue?

2023-03-03 12:59 UTC, JuliaKirschenheuter commented
/backport to stable26

2023-03-06 09:12 UTC, ChristophWurst commented on core/src/OCP/accessibility.js
> + * @param {string} [heading] page title from the history api
```suggestion
 * @param {string} heading page title from the history api
```

https://jsdoc.app/tags-param.html

2023-03-06 09:12 UTC, ChristophWurst commented on core/src/OCP/accessibility.js
> + */
nit

```suggestion
 * @since 27.0.0
 */
```

although this should probably be dropped from the future backport PR

2023-03-06 09:12 UTC, ChristophWurst commented on core/templates/layout.user.php
> +				<?php p(!empty($_['pageTitle'])?$_['pageTitle']:''); ?>
I think the logic should be to fall back to `$theme->getName()` instead of an empty string if pageTitle is not set

2023-03-06 09:48 UTC, ChristophWurst approved these changes
Code looks good

2023-03-06 12:08 UTC, ChristophWurst commented
Let's stick with fixups until the second approval and passing CI (with the exception of the fixup check)

![Bildschirmfoto vom 2023-03-06 13-07-07](https://user-images.githubusercontent.com/1374172/223106146-8cbd133c-25b6-4726-a20b-8d28306985f0.png)

^ makes it very hard to follow your latest pushes

2023-03-06 15:52 UTC, artonge approved these changes
Small nitpick, else it looks good :)

2023-03-06 15:52 UTC, artonge commented on core/src/OCP/accessibility.js
> +	const headingEl = document.getElementById('pageHeadingLevel1')
Let's use snake case for the id: `page-heading-level-1`

2023-03-06 19:06 UTC, Pytal approved these changes

2023-03-08 07:08 UTC, merged

2023-05-30 09:41 UTC, DaphneMuller commented
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!