FIX: Add feedback on user settings when no results
nextcloud/server pull request #3671
Opened 2017-03-01 20:28 UTC by gsambrotta

Add visual feedback for users when searching in users settings and no results is found.

Fix #1070

Please review @nextcloud/javascript @nextcloud/designers

2017-03-01 20:32 UTC, jancborchardt commented
Awesome! :) Congrats on your first pull request to Nextcloud, Gio!

Just one things:
- [ ] When you search for a user and there is no result, and you then create that user, the emptycontent still stays and the header is still gone. Let’s see if we can fix that case too :)

2017-03-01 20:52 UTC, ChristophWurst requested changes

2017-03-01 20:52 UTC, ChristophWurst commented on settings/js/users/users.js
> +					emptyContainer.find('h2 strong').html();
This will *get* the HTML content, hence this function invocation doesn't have any effect. Did you want to clear the element?

2017-03-01 20:52 UTC, ChristophWurst commented on settings/js/users/users.js
> +		var emptyContainer = $userList.siblings('.emptycontent');
To align with the variable naming conventions (especially in this file), name the variable `$emptyContainer` since it's a jQuery object :wink:

2017-03-01 20:52 UTC, ChristophWurst commented on settings/js/users/users.js
> +					emptyContainer.find('h2 strong').html(pattern);
`.html(…)` is dangerous. Could you use `.text(…)` instead?

2017-03-01 20:52 UTC, ChristophWurst commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
This will probably not work for all languages. I'm sure @nickvergessen knows a trick for this 😉

2017-03-01 20:53 UTC, ChristophWurst commented on settings/js/users/users.js
> +					emptyContainer.find('h2 strong').html();
See http://api.jquery.com/html/#html1

2017-03-01 22:01 UTC, jancborchardt commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
@ChristophWurst it’s similar the emptycontent message in the Files app search – but yeah, there it’s constructed via Javascript I think.

2017-03-01 22:04 UTC, ChristophWurst commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
It will always show something like *No user found for*. The *strong* tag won't be propagated with the desired value this way..

2017-03-01 22:10 UTC, gsambrotta commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
@ChristophWurst do you mean to add something like this: 
`$emptyContainer.find('h2').text(t('settings', 'No user found for ') + "<strong>" + pattern + "<strong>' ");`

Maybe i understood wrong but the filter value is it currently display in the strong tag. I personally think is more elegant write the translation in the html but if translation won't work like that i will change with the javascript translation.

2017-03-01 22:10 UTC, gsambrotta commented on settings/js/users/users.js
> +					emptyContainer.find('h2 strong').html(pattern);
oh, yes!

2017-03-01 22:10 UTC, gsambrotta commented on settings/js/users/users.js
> +					emptyContainer.find('h2 strong').html();
ah, yes, good point.

2017-03-02 08:41 UTC, nickvergessen requested changes

2017-03-02 08:41 UTC, nickvergessen commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
Should be something like:
```js
$emptyContainer.find('h2').text(t('settings', 'No user found for <strong>{pattern}</strong>', {pattern: pattern}));
```

2017-03-02 08:42 UTC, nickvergessen commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
HTML within the pattern placeholder should be escaped automatically with this way.

2017-03-02 16:14 UTC, gsambrotta commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
i see! will do, thanks

2017-03-03 11:48 UTC, jancborchardt commented on settings/templates/users/part.userlist.php
> +	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
Yup, in @nickvergessen’s example the single quotes are also removed – which I wanted to recommend doing. :) They are not necessary because there’s already bolding.

2017-03-03 13:56 UTC, gsambrotta commented
@jancborchardt i fix also the new user case. Now when user attempt to create a new user, search is reset and it comes back to initial status

2017-03-06 10:31 UTC, nickvergessen approved these changes
Works nicely

2017-03-06 23:48 UTC, jancborchardt commented
Awesome, looks good to me! What’s up with the CI failures?

@ChristophWurst are your concerns addressed? :)

2017-03-07 06:42 UTC, ChristophWurst reviewed
looks good

2017-03-07 06:43 UTC, ChristophWurst approved these changes

2017-03-07 14:26 UTC, jancborchardt commented
@ChristophWurst @nickvergessen @MorrisJobke what about the build failures? They look like they are not entirely relevant to this PR, but I’m not an expert. ;)

2017-03-07 14:35 UTC, ChristophWurst commented
> @ChristophWurst @nickvergessen @MorrisJobke what about the build failures? They look like they are not entirely relevant to this PR, but I’m not an expert. ;)

They ran into a timeout, as shown by drone :-)

2017-03-07 14:37 UTC, gsambrotta commented
@jancborchardt  thanks! I try to re-run the building couple of time (since i cannot understand what the failing tests are about ) and some of them passed but others similar failed. 
@ChristophWurst any suggestion on how to make them pass?

2017-03-07 14:38 UTC, jancborchardt commented
> They ran into a timeout, as shown by drone :-)

So how do we continue? Just merge, or rerun them until all pass? :)

2017-03-07 14:39 UTC, ChristophWurst commented
> So how do we continue? Just merge, or rerun them until all pass? :)

They fail almost all the time. Different issue, thus we can ignore this here 😉

2017-03-07 14:51 UTC, merged

2017-03-07 14:51 UTC, nickvergessen commented
TImeout happens, can be ignored if nothing DB related was changed and at least one of the DB tests passed.

2017-03-07 15:00 UTC, MorrisJobke commented
:/ I have no idea what the timeouts are caused by, but we ahould debug it somehow

2017-03-07 19:37 UTC, jancborchardt commented
Yeeeehaaa @gsambrotta congrats on your first pull request to Nextcloud and fixing a nice issue! :tada:  :)