Add label and switch ocdialog close button to button element
nextcloud/server pull request #36772
Opened 2023-02-18 06:26 UTC by Pytal

- For https://github.com/nextcloud/server/issues/36715

## Summary

Before | After
--- | ---
![image](https://user-images.githubusercontent.com/24800714/219844908-559f7397-6828-467d-9dbc-3efa1daed7ef.png) | ![image](https://user-images.githubusercontent.com/24800714/219844909-54afca13-8f56-44cf-aa86-4b92766ea1dc.png)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-18 06:28 UTC, Pytal commented
/backport to stable25

2023-02-18 11:22 UTC, szaimen approved these changes
LGTM but didnt test

2023-02-20 11:25 UTC, artonge commented on core/src/jquery/css/jquery.ocdialog.scss
> +	top: 5px;
I think we are supposed to use multiple of 4 for spacing. Is there a rationale behind 5?

2023-02-22 02:27 UTC, Pytal commented on core/src/jquery/css/jquery.ocdialog.scss
> +	top: 5px;
Nope :) switched to `4px`

2023-02-22 09:31 UTC, artonge commented on core/src/jquery/ocdialog.js
> +				const $closeButton = $(`<button class="oc-dialog-close" aria-label="${t('core', 'Close')}"></button>`)
'Close dialog' ?

2023-02-22 09:31 UTC, artonge approved these changes

2023-02-24 14:38 UTC, JuliaKirschenheuter requested changes
please see the comment from @artonge

2023-03-06 16:13 UTC, JuliaKirschenheuter approved these changes

2023-03-06 16:14 UTC, JuliaKirschenheuter commented
/backport to stable26

2023-03-07 00:37 UTC, merged