fix: Adapt the menubar to the primary color if a custom backgorund image has been set
nextcloud/server pull request #36808
Opened 2023-02-22 11:46 UTC by juliushaertl

## Steps to reproduce:

- Set white as a primary color
- Set a bright background image as the admin
- Disable user theming (personal background image)

## Before

App icons where white on white

## After

App icons properly adapt to the primary color

2023-03-01 09:47 UTC, skjnldsv approved these changes
Could you also add a use case for this in the cypress tests please?

2023-03-01 17:28 UTC, szaimen requested changes
This doesnt seem to work if you choose a dark primary color. Also the app title in the heading doesnt seem to be inverted correctly...

2023-03-02 07:04 UTC, skjnldsv commented
We kinda had that discussion with https://github.com/nextcloud/server/issues/35482
If we want to apply a different rule following the primary, then we need to apply some overriding variables to the header element

2023-03-02 07:52 UTC, juliushaertl commented
Won't have time looking into that further this week, so If anyone wants to jump in feel free. Otherwise I'll check again somewhen next week.

2023-03-24 10:00 UTC, MichaIng commented
Related: #37379
Avatar and status icon get inverted as well, so it must be taken care that only app icons are inverted.

2023-04-14 09:09 UTC, skjnldsv commented on apps/theming/lib/Themes/CommonThemeTrait.php
> +		// Adapt the menubar to the primary color if a custom backgorund image has been set
```suggestion
		// Adapt the menubar to the primary color if a custom background image has been set
```

2023-04-14 09:12 UTC, skjnldsv approved these changes
One tiny comment, but all good otherwise

2023-04-14 09:12 UTC, skjnldsv commented
/backport to stable26

2023-04-14 09:12 UTC, skjnldsv commented
/rebase

2023-04-14 09:13 UTC, skjnldsv commented
/compile amend /

2023-04-14 09:17 UTC, skjnldsv commented
/rebase

2023-04-14 09:20 UTC, szaimen commented
@skjnldsv the PR hasnt changed since I reviewed it so what shall I review here?

2023-12-29 09:26 UTC, juliushaertl commented
I revived this and pushed a cypress test.

> This doesnt seem to work if you choose a dark primary color. Also the app title in the heading doesnt seem to be inverted correctly...

I could not reproduce this anymore

2023-12-29 09:31 UTC, juliushaertl commented
Thinking more about it i don't think this is the right approach, as long as we have no detection or setting for if the background is dark or bright, we can only make it work in either combination. The primary color is only a good indicator for inverting app icons if no background is used. Will close this.

2023-12-29 09:31 UTC, closed without merging