apps/dav: add some OSX specific quirks.
nextcloud/server pull request #36800
Opened 2023-02-21 20:26 UTC by rotdrop

* Resolves: #17053

## Summary

Following @georgehrke suggestion in the  linked issue this PR adds a special `QuirksPlugin` which tweaks report requests from the half-eaten-apple OS to include the `apply-to-principal-collection-set` flag.

This is done by a Sabre ServerPlugin with  `beforeMethod:*` listener which decodes the HTTP_USER_AGENT and a `report` listener which then tweaks a `{DAV:}principal-property-search` report request to have the flag set.

## TODO

- [ ] implement tests

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-02-21 20:36 UTC, rotdrop commented
Actually, the delegation dialog and the participants dialog of the OSX calendar app in "Ventura" now finds the principals. Inviting participants seems to work, delegation is still flaky: the delegation is transmitted to the NC server but the OSX calendar app somehow has problems with the response. This might be the problem mentioned here https://github.com/nextcloud/server/issues/17053#issuecomment-529233283.

2023-02-21 20:46 UTC, rotdrop commented
> This is done by a Sabre ServerPlugin with `beforeMethod:*` listener which decodes the HTTP_USER_AGENT and a `report` listener which then tweaks a `{DAV:}principal-property-search` report request to have the flag set.

What can be used in place of the asterisk? Parsing the user-agent with a regexp is probably a little bit costly, and here only necessary for the report requests.

2023-02-23 09:06 UTC, miaulalala requested changes, later dismissed

2023-02-23 09:06 UTC, miaulalala commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
**suggestion**: rename the plugin to make it's purpose clearer
```suggestion
class ApplePlugin extends ServerPlugin {
```

2023-02-23 16:49 UTC, rotdrop commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
Maybe rather `MacOsQuirksPlugin`. Where it might be that further quirks might be needed also for IOS and perhaps other clients, so one could also collect all necessary quirks in one single plugin and keep the original name. But I do not care too much. I would keep the nasty "quirks" word in the name to make it clear that this does not exploit grand feature of MacOS but works around some of its well known bugs.

2023-02-23 18:48 UTC, rotdrop commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
Maybe then also related to a proper naming of the plugin: is it known whether this bugs is specific to the OSX calendar app or also exists in the IOS app? I vaguely remember a user who complained not to be able to add participants to an event on her iphone or ipad.

2023-02-24 10:18 UTC, miaulalala commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
Fair, I would just like to have the usage for the plugin clearer, but `MacOsQuirksPlugin` is fine for me. I don't know about IOs , but it sounds likely that the same bugs / "quirks" appear there too. So maybe make it `AppleQuirksPlugin`?

2023-02-24 10:39 UTC, rotdrop commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
Yeah, AppleQuirksPlugin is just fine.

Concerning IOS: yesterday I have asked a friend to schedule a test event from her IPhone or -Tab and she was not even offered the possibility to invite people (but she assured that she can invite people to events in non-Nextcloud calendars). Actually, the calendar was a shared calendar. So that might be the issue here.

At least IOS behaves different from OSX where I can invite people (even successfully when something like this plugin is in effect).

Still AppleQuirksPlugin is  fine. I would also rather no write yet another plugin in case IOS also needs some tweaks but rather add the corresponding "quirks" to this plugin. We will see.

2023-02-24 10:52 UTC, rotdrop commented on apps/dav/lib/Connector/Sabre/QuirksPlugin.php
> +class QuirksPlugin extends ServerPlugin {
I have renamed the plugin, so this should be "resolved".

2023-02-26 15:36 UTC, tcitworld approved these changes
Thanks, looks greak!

2023-02-26 15:36 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/AppleQuirksPlugin.php
> +class AppleQuirksPlugin extends ServerPlugin {
**suggestion:** I'd like a small comment explaining what the plugin does and the context. :)

2023-02-27 13:37 UTC, rotdrop commented on apps/dav/lib/Connector/Sabre/AppleQuirksPlugin.php
> +class AppleQuirksPlugin extends ServerPlugin {
I have addressed this in 43ada458bcc. The comment could also be shorter, in particular if at some time anything else should be added.

2023-02-28 18:59 UTC, tcitworld commented
Do you mind reverting your composer-related changes other than adding the new class in `apps/dav/composer/composer/autoload_static.php` and the second part of `apps/dav/composer/composer/autoload_classmap.php`? You likely have a different composer version installed that cause the rest of the changes.

Please squash your commits as well.

2023-02-28 19:04 UTC, rotdrop commented
> Do you mind reverting your composer-related changes other than adding the new class in `apps/dav/composer/composer/autoload_static.php` and the second part of `apps/dav/composer/composer/autoload_classmap.php`? You likely have a different composer version installed that cause the rest of the changes.

I have probably just a recent composer version installed, which no longer support PHP 5. But for the question: I do not mind at all. However, ideally the Nextcloud core developers would just regenerate the autoload-files with whatever composer version they usually use. I think without the composer changes at least the continuous integration test has no chance to succeed.

> Please squash your commits as well.

I do not mind, but isn't this done automatically during merge? Doesn't matter, I'll squash them.

2023-02-28 19:05 UTC, rotdrop commented
> > Please squash your commits as well.
> 
> I do not mind, but isn't this done automatically during merge? Doesn't matter, I'll squash them.

Actually, I would suggest to squash all commits with the exception of the composer changes.

2023-02-28 19:12 UTC, rotdrop commented
> > > Please squash your commits as well.
> > 
> > 
> > I do not mind, but isn't this done automatically during merge? Doesn't matter, I'll squash them.
> 
> Actually, I would suggest to squash all commits with the exception of the composer changes.

@tcitworld In order to avoid unnecessary work I'll wait for a response from your side. Of course, it is not a problem to just squash all commits in to one, I just think that it makes sense to keep all generated files separate from the real changes.

2023-03-03 08:42 UTC, tcitworld commented
> However, ideally the Nextcloud core developers would just regenerate the autoload-files with whatever composer version they usually use. 

Yeah, I guess this is done one in a while, but let's not create conflits if we can avoid them.

> I do not mind, but isn't this done automatically during merge?

This is not enabled for this repository, not sure why, probably Github drops Sign-off information during squashing.

2023-03-07 15:25 UTC, rotdrop commented
> Do you mind reverting your composer-related changes other than adding the new class in `apps/dav/composer/composer/autoload_static.php` and the second part of `apps/dav/composer/composer/autoload_classmap.php`? You likely have a different composer version installed that cause the rest of the changes.
> 
> Please squash your commits as well.

I have just also squashed the composer changes into the remaining single commit.

2023-03-13 10:38 UTC, miaulalala approved these changes

2023-03-13 10:46 UTC, merged

2023-03-22 15:47 UTC, labor4 commented
Are there intentions to backport to NC 26 ?

2023-11-28 21:01 UTC, z3ky commented
Does this plugin still works? If yes, how do I activate it?

2024-11-06 22:14 UTC, JohnPritchard commented
I am brand spanking new to NextCloud, I have just completed installation for the first time. I'm running Nextcloud Hub 9 (30.0.1) -- which I assume means I'm running NextCloud 30.0.1.
Is this "plugin" still relevant? How do I install/enable it?
Many thanks in advance for any help and/or advice.

2024-11-06 22:24 UTC, labor4 commented
> I am brand spanking new to NextCloud, I have just completed installation for the first time. I'm running Nextcloud Hub 9 (30.0.1) -- which I assume means I'm running NextCloud 30.0.1. Is this "plugin" still relevant? How do I install/enable it? Many thanks in advance for any help and/or advice.

This is not a plugin but a code change. It has been implemented.

2024-11-07 10:01 UTC, JohnPritchard commented
That's great news!
Indeed I can connect to my NextCloud Calendar Server from macOS (15 == Sequoia) and iOS (18). I see events created via the webUI in macOS and iOS and vice versa.
But unfortunately I am still having trouble setting up delegates, can I/should I report the issues here? Or there somewhere else I should make an Issue/bug report/...

2024-11-07 11:38 UTC, labor4 commented
> That's great news! Indeed I can connect to my NextCloud Calendar Server from macOS (15 == Sequoia) and iOS (18). I see events created via the webUI in macOS and iOS and vice versa. But unfortunately I am still having trouble setting up delegates, can I/should I report the issues here? Or there somewhere else I should make an Issue/bug report/...

This issue  is closed and outdated. 

When you think there is still a problem, create a new bug report/issue. 

btw. as a side note: apple is notorious for bending their own standards. myself i skipped the apple-side delegation and delegate via the nextcloud web interface, which will reflect back to apple calendar app. but in any case your contribution is valuable so if you describe the symptoms/observations closely and post a report, thats the way to confront this problem.

2024-11-07 13:16 UTC, JohnPritchard commented
Hi labor4,
Thanks for the clear instructions...
I can easily appreciate that it is caused by Apple bending... it is also entirely possible I've not got everything quite right, I just spent several hours getting my half-working SSL certificate verification working 100% -- I had to provide the SSLCACertificateFile of my certificate provider, which I hadn't realised.

In the meantime, it would be great if I can set up delegatation **via the nextcloud web interface**, but I've not been able to find that, would you be so kind as to point me in the right direction?

In any case, many thanks for your help and assistance.
J

2024-11-07 14:08 UTC, rotdrop commented
> Hi labor4, Thanks for the clear instructions... I can easily appreciate that it is caused by Apple bending... it is also entirely possible I've not got everything quite right, I just spent several hours getting my half-working SSL certificate verification working 100% -- I had to provide the SSLCACertificateFile of my certificate provider, which I hadn't realised.
> 
> In the meantime, it would be great if I can set up delegatation **via the nextcloud web interface**, but I've not been able to find that, would you be so kind as to point me in the right direction?
> 
> In any case, many thanks for your help and assistance. J

Nope, AFAIK this is still not exposed in the web interface, though it should be supported by the calendar backend. See here:

https://github.com/nextcloud/calendar/issues/2706

2024-11-07 16:07 UTC, labor4 commented
thanks

given said issue (still valid?), we maybe speak of different technical things. 

i tested it a while ago and „shared“ a cal to another user in web, and found it to be handed down to apple calender, seemingly in a way that was transparent (as in „does not know“) to the client. how this really differentiates against a proper „caldav delegation“ i do not know.

i did have the (unproven) suspicion that this may be a „dontworry“ replacement method for this need that works better. same way NC finally ditched the apple-specific calendar-invitation chaos and went the more cross/stable google-way with mails and links. but thats just my guts speaking. 🙏😁

carefull testing for usability by the user is advised, i guess. 

sorry. dont know more.

2024-11-07 16:26 UTC, rotdrop commented
> thanks
> 
> given said issue (still valid?), we maybe speak of different technical things.
> 
> i tested it a while ago and „shared“ a cal to another user in web, and found it to be handed down to apple calender, seemingly in a way that was transparent (as in „does not know“) to the client. how this really differentiates against a proper „caldav delegation“ i do not know.
> 
> i did have the (unproven) suspicion that this may be a „dontworry“ replacement method for this need that works better. same way NC finally ditched the apple-specific calendar-invitation chaos and went the more cross/stable google-way with mails and links. but thats just my guts speaking. 🙏😁
> 
> carefull testing for usability by the user is advised, i guess.
> 
> sorry. dont know more.

"delegation" means that you let someone else edit your calendars on behalf of yourself, you remain the organizer. It is not visible that it wasn't you who edited things. The use case is e.g. when "the big boss" delegates his calendars to a clerk who manages his appointments.

This is different from a shared writable calendar, here the person who creates an event is the organizer which then in general is different from the owner of the calendar.

And yes: if you share a calendar to someone else then this calendar will appear in that other ones caldav collection and is visible through the caldav protocol.

And yes: the issue a mentioned in my previous post is still valid, it is still not possible to manage calendar delegation in the frontend.