Remove deprecated OC_User::isLoggedIn
nextcloud/server pull request #3682
Opened 2017-03-02 15:54 UTC by whitekiba

2017-03-02 17:47 UTC, MorrisJobke requested changes

2017-03-02 17:47 UTC, MorrisJobke commented on lib/private/legacy/user.php
> -	/**
We need to keep this one, because it's only deprecated for under 1 year. It doesn't hurt to leave it there. The other changes look good

2017-03-02 18:10 UTC, ChristophWurst commented on lib/private/legacy/user.php
> -	/**
isn't this an internal class, hence the deprecation policy doesn't hold?

2017-03-02 19:03 UTC, whitekiba commented on lib/private/legacy/user.php
> -	/**
I modified the commit as requested.

2017-03-02 21:50 UTC, MorrisJobke commented
Could you add the sign-off. For more details see https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

2017-03-02 22:03 UTC, whitekiba commented
sign-off is added to the commit

2017-03-03 03:58 UTC, MorrisJobke commented on lib/private/legacy/user.php
> -	/**
I don't want to mess just because of this tiny change. It doesn't kill us to leave it for now and remove this later.

2017-03-03 03:59 UTC, MorrisJobke approved these changes
Changes make sense and some testing didn't revealed problems. 👍

2017-03-03 04:00 UTC, MorrisJobke commented
Thanks a lot for your contribution @whitekiba 👍 

We really appreciate it and you are welcome to join our IRC channel at #nextcloud-dev on Freenode :) If you look for other issues to work on, then check out the starter issue label: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22starter+issue%22

🚀

2017-03-03 04:01 UTC, MorrisJobke commented
@whitekiba Just regarding merging this: we have to policy of two review to allow a merge 😉

2017-03-03 08:23 UTC, rullzer approved these changes

2017-03-03 08:23 UTC, merged