Execute UpdateLanguageCode only once
nextcloud/server pull request #3684
Opened 2017-03-02 18:14 UTC by MorrisJobke

* followup to #1377

2017-03-02 22:20 UTC, nickvergessen commented on lib/private/Repair/NC12/UpdateLanguageCodes.php
> +		if ($this->config->getAppValue('core', 'languageCodesUpdatedNC12', false)) {
just compare the version number instead of introducing a new config that will then be around forever?

2017-03-03 03:47 UTC, MorrisJobke commented on lib/private/Repair/NC12/UpdateLanguageCodes.php
> +		if ($this->config->getAppValue('core', 'languageCodesUpdatedNC12', false)) {
We also do this in other NC11 repair steps 🙈 

Maybe we namespace them to easily clean up. But I will change this one to the version number too.

2017-03-03 08:20 UTC, rullzer approved these changes

2017-03-03 10:59 UTC, nickvergessen requested changes

2017-03-03 10:59 UTC, nickvergessen commented on tests/lib/Repair/NC12/UpdateLanguageCodesTest.php
> +		$outputMock = $this->createMock(IOutput::class);
Add something like:
```php
		$outputMock->expects($this->never())
			->method('info');
```

Otherwise this test always passes, even when I raise the version number

2017-03-03 11:02 UTC, nickvergessen approved these changes

2017-03-03 11:02 UTC, nickvergessen commented on tests/lib/Repair/NC12/UpdateLanguageCodesTest.php
> +		$outputMock = $this->createMock(IOutput::class);
Did it myself

2017-03-03 12:51 UTC, merged