bump the hub number
nextcloud/server pull request #36881
Opened 2023-02-27 20:13 UTC by blizzz

2023-02-27 20:44 UTC, skjnldsv approved these changes

2023-02-27 20:48 UTC, AndyScherzinger approved these changes

2023-02-27 21:05 UTC, nickvergessen requested changes
config/CAN_INSTALL must stay

2023-02-28 08:07 UTC, nickvergessen approved these changes

2023-02-28 12:43 UTC, merged