Add "MFA Verified" check to workflowengine
nextcloud/server pull request #37195
Opened 2023-03-13 14:35 UTC by michielbdejong

Rebase of #36045

This PR goes together with:
* #35555
* https://github.com/nextcloud/user_saml/pull/668 
* https://github.com/nextcloud/globalsiteselector/pull/80

It allows the creation of work flows that depend on whether the logged-in user has passed MFA Verification for the current session or not.

2023-03-14 09:01 UTC, nickvergessen requested changes

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/lib/Manager.php
> -		$cache = $this->cacheFactory->createDistributed('flow');
Your rebase went wrong

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/lib/Manager.php
> -		try {
Your rebase went wrong

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/lib/Manager.php
> -		$cache->set('events', $operations, 3600);
Your rebase went wrong

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/lib/Manager.php
> -			try {
Your rebase went wrong

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/lib/Manager.php
> -		$this->cacheFactory->createDistributed('flow')->remove('events');
Your rebase went wrong

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/src/components/Checks/MfaVerifiedValue.vue
> +  <div>
Expected "\t" character, but found " " character

2023-03-14 09:01 UTC, nickvergessen commented on apps/workflowengine/src/components/Checks/MfaVerifiedValue.vue
> +</style>
```suggestion
```

SHould be able to remove it when emtpy?

2023-03-15 11:11 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -		$cache = $this->cacheFactory->createDistributed('flow');
Fixed.

2023-03-15 11:12 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -		try {
Fixed.

2023-03-15 11:12 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -		$cache->set('events', $operations, 3600);
Fixed.

2023-03-15 11:12 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -			if (!$operation->isAvailableForScope((int) $row['type'])) {
Fixed.

2023-03-15 11:12 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -			try {
Fixed.

2023-03-15 11:14 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> -		$this->cacheFactory->createDistributed('flow')->remove('events');
Fixed

2023-03-15 11:14 UTC, mrvahedi68 commented on apps/workflowengine/lib/Manager.php
> +	public function validateOperation($class, $name, array $checks, $operation, string $entity, array $events) {
Fixed.

2023-03-15 11:15 UTC, mrvahedi68 commented on apps/workflowengine/src/components/Checks/MfaVerifiedValue.vue
> +  <div>
Fixed.

2023-03-15 11:15 UTC, mrvahedi68 commented on apps/workflowengine/src/components/Checks/MfaVerifiedValue.vue
> +</style>
Removed.

2023-04-03 11:40 UTC, mickenordin commented
Any news on getting this merged?

2023-04-03 15:41 UTC, juliushaertl commented on apps/workflowengine/lib/Check/MfaVerified.php
> +	use TFileCheck;
Any reason to make this a file only check? This could be a generic `ICheck` implementation I think.

2023-04-03 15:41 UTC, juliushaertl commented on apps/workflowengine/src/components/Checks/file.js
> +		name: t('workflowengine', 'multi-factor authentication'),
```suggestion
		name: t('workflowengine', 'SAML multi-factor authentication'),
```

2023-04-03 15:42 UTC, juliusknorr requested changes
Some comments, but generally looks good 👍

2023-04-04 06:42 UTC, juliushaertl commented
I was mainly referring to https://github.com/nextcloud/server/pull/37195/files#diff-324119d2db6f3d5a6d7546558dd8011e16e04683d83c4d29d69ff5f250f353d1R62 but might be missing some context there. If there are other sources for this flag to be set it would be good to have a code comment inline as well. I might be overseeing something but as far as I understand the passed over options by the GSS also originate from user_saml. 

Noting that user_saml is not exclusively for SAML but can also provide other SSO mechanisms maybe I should rather have asked for "SAML/SSO multi-factor authentication" as the user facing wording there. Would that be a better fit?

2023-04-04 11:14 UTC, navid-shokri commented on apps/workflowengine/src/components/Checks/file.js
> +		name: t('workflowengine', 'multi-factor authentication'),
So as I can remember About the flow. we were using the session to check the MFA flag of the user authentication. So the SAML is just used when the user is logging in using an OIDC/SAML authentication provider. it seems that the `using multi-factor authentication` phrase is more general and meaning full.  

@mrvahedi68, please adjust us.

2023-04-04 11:41 UTC, michielbdejong commented
Thanks for raising this @juliushaertl - the Check should actually be looking for 3 sources of MFA info as we tested in https://github.com/pondersource/nextcloud-mfa-awareness/blob/7011a58/mfachecker/lib/Controller/PageController.php#L33-L53 - we forgot to add all 3 of them as we moved the code into the Check. Sorry! Will be fixed in https://github.com/pondersource/nextcloud-mfa-awareness/issues/54 and then it will no longer be SAML-only and no longer be a misnomer. :)

2023-04-06 10:26 UTC, mrvahedi68 commented on apps/workflowengine/lib/Check/MfaVerified.php
> +	use TFileCheck;
Updated.

2023-04-17 12:59 UTC, mrvahedi68 commented
@juliushaertl @nickvergessen Accepted change requests, Rebased and Ready to merge.

2023-04-19 07:50 UTC, nickvergessen commented
It heavily conflicts at the moment it seems. can you rebase again?

2023-04-25 04:23 UTC, mrvahedi68 commented on apps/workflowengine/lib/Check/MfaVerified.php
> +			return $mfaVerified === '1'; // checking whether the current user is MFA-verified
Yes, that's it, Will change it.

2023-05-09 11:16 UTC, michielbdejong commented
Continued in #37914

2023-05-09 11:16 UTC, closed without merging