Move admin_audit hooks to proper event listeners
nextcloud/server pull request #37193
Opened 2023-03-13 10:26 UTC by tcitworld

Requires #35677

## Summary

Moves all of the hooks used by `admin_audit` to event listeners, where appropriate typed events already exist.

- Bases itself on  #35677 to have app management events
- Adds a new `ConsoleEventV2` typed event to replace the legacy `ConsoleEvent` event in OCP (already depreciated). However, this doesn't seem used anywhere else, so we could replace it straight away.
- Adds preview details on the `BeforePreviewFetchedEvent` event

Part of #14552. Follow # to track all of the hooks left.

## TODO

- [ ] Add tests for the new listeners

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-13 15:24 UTC, come-nc commented
Is that different/better than https://github.com/nextcloud/server/pull/32019 ?

2023-03-13 16:21 UTC, tcitworld commented
I missed this one, thanks. :see_no_evil: 

Well, there's more stuff in mine. I'll simply take the LDAP stuff from Carl's PR, and take over https://github.com/nextcloud/server/pull/32018 as well.

2023-03-13 18:16 UTC, tcitworld commented on apps/admin_audit/lib/Listener/SharingEventListener.php
> +			'path' => $share->getNode()->getPath(),
**question:** Unfortunately, this makes extra requests to get the Node. Should the share hold this information?

2023-03-14 17:09 UTC, come-nc commented on apps/admin_audit/lib/Listener/SharingEventListener.php
> +			'path' => $share->getNode()->getPath(),
Extra PHP calls? Or extra database queries?
Does not seem that overkill to me.

2023-03-14 17:09 UTC, come-nc commented on lib/public/Console/ConsoleEventV2.php
> +/**
strict types

2023-03-14 17:09 UTC, come-nc commented on lib/public/User/Events/BeforeUserIdUnassignedEvent.php
> +
strict types

2023-03-14 17:10 UTC, come-nc commented
Please strict type the hell out of this, return types on all new methods and strict_type declare on all new files, otherwise nice cleanup!

2023-05-03 09:18 UTC, blizzz requested changes
some remarks, but nothing fundamental

2023-05-03 09:18 UTC, blizzz commented on apps/admin_audit/lib/Listener/SharingEventListener.php
> +		match ($share->getShareType()) {
The type could also be parameterized, saving some lines. It's not translated after all.

2023-05-03 09:18 UTC, blizzz commented on apps/admin_audit/lib/Listener/UserManagementEventListener.php
> +class UserManagementEventListener extends Action implements IEventListener {
there are more issues with the docblock, check the static scanner remarks

2023-05-03 09:18 UTC, blizzz commented on apps/user_ldap/lib/Jobs/Sync.php
> +		$this->accessFactory = new AccessFactory(
It should be safe to inject the AccessFactory directly.

2023-05-03 09:18 UTC, blizzz commented on lib/private/Console/Application.php
> +								MemoryInfo $memoryInfo, Defaults $defaults) {
codes style, one argument per line pls

2024-09-09 15:00 UTC, come-nc commented
@tcitworld Can I take over this one?

2024-09-09 17:30 UTC, tcitworld commented
Yes please, I don't even want to have a look at the conflicts! :see_no_evil:

2024-09-13 14:26 UTC, come-nc commented
Supplanted by https://github.com/nextcloud/server/pull/47865

2024-09-13 14:26 UTC, closed without merging