file-upload.js modified : Remaining upload time corrected
nextcloud/server pull request #3727
Opened 2017-03-06 11:35 UTC by Sarthika15170

Hi
I have tried to resolve the issue 'Remaining upload time is wrong :#3647'  . Changes are from line 976 to 1040 .

2017-03-06 14:19 UTC, ChristophWurst reviewed
some nitpicks :)

2017-03-06 14:19 UTC, ChristophWurst commented on apps/files/js/file-upload.js
> +                    $('#uploadprogressbar').tipsy({gravity:'n', fade:true, live:true});
please use tabs instead of spaces

2017-03-06 14:19 UTC, ChristophWurst commented on apps/files/js/file-upload.js
> +					var timeStringMobile = "";
use single quotes

2017-03-06 14:19 UTC, ChristophWurst commented on apps/files/js/file-upload.js
> +					if(bufferIndex2<20)
use curly braces for the if and else branch

2017-03-08 19:32 UTC, jancborchardt commented on apps/files/js/file-upload.js
> +                    $('#uploadprogressbar').tipsy({gravity:'n', fade:true, live:true});
Also, didn’t we change from tipsy to tooltip?

2017-03-08 19:36 UTC, ChristophWurst commented on apps/files/js/file-upload.js
> +                    $('#uploadprogressbar').tipsy({gravity:'n', fade:true, live:true});
Yup! @xx621998xx please revert this change

2017-03-09 07:01 UTC, MorrisJobke commented
And remove the executable bit from the JS file (10644 -> 10755 in the git diff indicates, that the executable flag was set)

2017-03-09 07:02 UTC, MorrisJobke commented on apps/files/js/file-upload.js
> +					if(bufferIndex2<20)
... and spaces around the operator ;)

2017-03-09 07:05 UTC, MorrisJobke commented
Beside that it looks good :)

2017-03-16 12:18 UTC, nickvergessen requested changes
Executable bit needs to go.

2017-03-16 12:18 UTC, nickvergessen commented on apps/files/js/file-upload.js
> +						bufferIndex2 = (bufferIndex2 + 1);
Just do `bufferIndex2++;` instead?

2017-03-16 12:18 UTC, nickvergessen commented on apps/files/js/file-upload.js
> +							smoothRemainingSeconds = (bufferTotal/bufferIndex2);
please remove the brackets

2017-03-16 12:18 UTC, nickvergessen commented on apps/files/js/file-upload.js
> +						 smoothRemainingSeconds = (bufferTotal / bufferSize);
same here

2017-03-16 20:56 UTC, MorrisJobke commented on apps/files/js/file-upload.js
> +					{
brackets in one line:
```js
if(remainingSeconds >= 0) {
```

2017-03-16 20:57 UTC, MorrisJobke commented on apps/files/js/file-upload.js
> +					if(bufferIndex2<20)
brackets in one line, space after if, spaces around operator:
```js
if (bufferIndex2 < 20) {
```

2017-03-16 20:57 UTC, MorrisJobke commented on apps/files/js/file-upload.js
> +							smoothRemainingSeconds = bufferTotal / bufferIndex2;
Indentation is off - seems to be spaces instead of tabs.

2017-03-16 20:58 UTC, MorrisJobke commented on apps/files/js/file-upload.js
> +					else
Brackets on same line:

```js
} else {
```

2017-03-16 20:58 UTC, MorrisJobke commented
Sorry for nitpicking.

2017-03-17 12:05 UTC, nickvergessen commented
I removed the executable bit and added some more hardening in 
https://github.com/nextcloud/server/pull/3896

Thanks for your contribution @xx621998xx  🎉

2017-03-17 15:14 UTC, closed without merging