Add a getAttributes to IControllerMethodReflector
nextcloud/server pull request #37279
Opened 2023-03-16 18:34 UTC by nickvergessen

As discussed in https://github.com/nextcloud/server/pull/36928#discussion_r1131224444

Looking at the diff, I'm not sure it's worth it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-16 18:42 UTC, ChristophWurst commented
I'm on the fence here. It's a small enhancement in all fairness.

2023-03-16 18:59 UTC, vitormattos requested changes

2023-03-16 18:59 UTC, vitormattos commented on lib/private/AppFramework/Utility/ControllerMethodReflector.php
> +	protected ?\ReflectionMethod $reflection;
To be more specific because exist other types of reflections:

```suggestion
	protected ?\ReflectionMethod $reflectionMethod;
```

2023-03-17 13:06 UTC, come-nc approved these changes
:+1: I like it

2023-03-17 13:15 UTC, come-nc commented on lib/private/AppFramework/Utility/ControllerMethodReflector.php
> +	 * @template T of Attribute
Attribute classes do not extend Attribute class, which is final. So you cannot do that.

2023-03-17 16:09 UTC, nickvergessen commented
Exactly my thoughts after seeing the resulting PR.
So also tend to close it now and continue as before

2023-04-14 11:40 UTC, closed without merging