fix: add logging for failed fopen operations that don't throw exceptions
nextcloud/server pull request #37284
Opened 2023-03-17 13:38 UTC by miaulalala

Add logging that shows some more file details when the fopen operation returns false.

2023-03-17 14:33 UTC, icewind1991 requested changes

2023-03-17 14:33 UTC, icewind1991 commented on lib/private/Streamer.php
> +						\OCP\Util::writeLog('core', 'unable to open file for stream: ' . print_r($file, true) , ILogger::ERROR);
please use `LoggerInterface` instead of the deprecated `writeLog`

2023-04-07 10:46 UTC, miaulalala commented
Tests are passing on master

2023-06-22 10:07 UTC, blizzz commented
What do we do with this PR now?

2023-08-21 07:05 UTC, miaulalala commented
> What do we do with this PR now?

Nothing

2023-08-21 07:05 UTC, closed without merging