Artonge/fix_files_version_cypress_tests
nextcloud/server pull request #37345
Opened 2023-03-22 12:55 UTC by artonge

In files_versions cypress tests, we wait for 1000ms between each versions uploads to make sure that the server properly create a version. Under 1s the serve does not create a version.

This commit increases the wait time as it might help to ensure that the time span is enough between two uploads.

Signed-off-by: Louis Chemineau <louis@chmn.me>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-22 15:38 UTC, skjnldsv approved these changes

2023-03-22 15:38 UTC, skjnldsv commented on cypress/e2e/files_versions/filesVersionsUtils.ts
> +	cy.wait(1500)
```suggestion
	// A new version will not be created if the changes occur
	// within less than one second of each other.
	cy.wait(1500)
```

2023-03-22 15:41 UTC, skjnldsv requested changes
We're not using docker compose?

2023-03-22 15:41 UTC, skjnldsv commented on .github/workflows/cypress.yml
> +        run: docker-compose --project-directory cypress logs > nextcloud.log
We're not using docker compose?

2023-03-22 15:42 UTC, skjnldsv commented on .github/workflows/cypress.yml
> +        run: docker-compose --project-directory cypress logs > nextcloud.log
Also, it should not be run on the component testing runner :)

2023-03-22 17:56 UTC, artonge commented on .github/workflows/cypress.yml
> +        run: docker-compose --project-directory cypress logs > nextcloud.log
Indeed, good catch, copy pasting does not always work !

2023-03-22 17:57 UTC, artonge commented on .github/workflows/cypress.yml
> +        run: docker-compose --project-directory cypress logs > nextcloud.log
Not sure how to exclude component testing. Try `${{ matrix.containers !== 'component' }}`

2023-03-22 19:09 UTC, skjnldsv commented on .github/workflows/cypress.yml
> +        run: docker-compose --project-directory cypress logs > nextcloud.log
No need for the `${{}}` https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

2023-03-30 12:29 UTC, artonge commented
Strongly suspecting auto expiration from deleting files, let's see

2023-04-03 12:21 UTC, artonge reviewed
@skjnldsv I managed to get the tests working again. I was tricked by the auto expiration process...

The culprit is that I move the `occ config:system:set versions_retention_obligation` call from `dockerNode.ts` to `version_expiration.cy.ts`.

Note that: 

- I extended the cypress workflow to extract logs and data directory. Can be remove but seems useful. Ok to keep?
- The change also contains logic to use a random file name instead of 'test.txt'. Not needed, but it's here and it works.

2023-04-03 12:21 UTC, artonge commented on cypress.config.ts
> +				}
Needed to extract logs and data directory

2023-04-04 08:41 UTC, come-nc reviewed
It should only upload log and data on failure, no?

2023-04-04 08:41 UTC, come-nc commented on .github/workflows/cypress.yml
> +        if: ( success() || failure() ) && matrix.containers != 'component'
`( success() || failure() )` is not always true? :thinking:

2023-04-04 08:48 UTC, artonge commented on .github/workflows/cypress.yml
> +        if: ( success() || failure() ) && matrix.containers != 'component'
Yes, it is uneeded. Let's reduce our data consumption :)

2023-04-04 09:18 UTC, skjnldsv approved these changes
Looks good! :+1:

2023-04-04 09:30 UTC, come-nc approved these changes

2023-04-04 11:42 UTC, merged

2023-04-04 15:04 UTC, artonge commented
/backport to stable26