Don't send Clear-Site-Data header to Safari
nextcloud/server pull request #37405
Opened 2023-03-25 22:59 UTC by solracsf

## Summary

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data#browser_compatibility only Safari don't support it; Firefox supports it but it is disabled by default, so i think it's ok to leave it here.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-26 10:07 UTC, skjnldsv commented
Do we gain anything to just not send it if safari?
Wouldn't safari just ignore the header?

If so, we should not even bother and send it for all browsers, no?

2023-03-26 13:04 UTC, solracsf commented
Sure but as i didn't knew the reason why some were balcklisted i assumed it was a compatiblity issue; but yes, this is just a header, browsers will just ignore it if unsupported.

2023-03-26 13:15 UTC, solracsf commented
@blizzz I've changed the code accordingly.

2023-03-27 08:43 UTC, artonge approved these changes

2023-03-28 05:46 UTC, skjnldsv approved these changes

2023-03-28 05:46 UTC, skjnldsv requested changes
`tests/Core/Controller/LoginControllerTest.php:160` needs a fix :)

2023-03-28 10:23 UTC, skjnldsv approved these changes

2023-03-28 12:02 UTC, merged

2023-10-30 15:24 UTC, joshtrichards commented
The blacklist was due to #17784 which is Chrome/Chromium specific and apparently still a problem in the field (e.g. see #41196).

2023-10-30 19:44 UTC, HLFH commented
I have added this PR that fixes the issue: https://github.com/nextcloud/server/pull/41204.