the breadcrumb navigation represents a list and should best be implemented as such
nextcloud/server pull request #37453
Opened 2023-03-28 15:25 UTC by JuliaKirschenheuter

* Resolves: #36918

## Summary

Adjust breadcrumb navigation structure to the navigation list.
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2023-03-28 17-24-34](https://user-images.githubusercontent.com/6078378/228287765-ffb7adf1-f792-4602-b91c-bdfee47b51e5.png) | ![Screenshot from 2023-03-28 17-16-18](https://user-images.githubusercontent.com/6078378/228287447-40ad8a46-0e46-456f-ae5f-32038e9aa62c.png)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-29 08:48 UTC, artonge commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
@skjnldsv Just to make sure that we do not have to redo this fix in a month. Did you use `nav`/`ul`/`li` element in your F2V work ?

2023-03-29 09:06 UTC, JuliaKirschenheuter commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
and a second question: could i backport this change to stable25 or would it be a breaking change?

2023-03-29 09:15 UTC, artonge commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
I think it is fine to backport it.

2023-03-29 09:52 UTC, artonge approved these changes

2023-03-29 10:34 UTC, JuliaKirschenheuter commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
@skjnldsv i guess i have to adjust styles in deck repo too, right: stable25, stable26 and master?

2023-03-29 10:46 UTC, skjnldsv commented on apps/files/templates/list.php
> +<nav aria-label="<?php p($l->t('Breadcrumb navigation'))?>" class="files-controls">
Not sure about that label, I would describe it better? like `Current folder breadcrumb trail` maybe ?
https://www.w3.org/WAI/WCAG21/Techniques/general/G65

2023-03-29 11:05 UTC, skjnldsv commented
When the screen is too narrow, the menu appear and show the hidden breadcrumbs items.
Keyboard accessibility is covered, whis is good. But I wonder if we should just hide the breadcrumbs visually. That way the screen readers could
- ignore the actions menu
- still read and understand the full nav

2023-03-29 11:14 UTC, JuliaKirschenheuter commented
> When the screen is too narrow, the menu appear and show the hidden breadcrumbs items.

The same behavior i saw in master. I think it should be a different ticket to fix it. 

> Keyboard accessibility is covered, whis is good. But I wonder if we should just hide the breadcrumbs visually. That way the screen readers could
> 
> * ignore the actions menu
> * still read and understand the full nav

Regarding narrow screens? If yes, then yes, we can just hide breadcrumbs visually and from screen readers

2023-03-29 11:16 UTC, JuliaKirschenheuter commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
i can open a ticket regarding https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcBreadcrumbs/NcBreadcrumbs.vue and fix there too

2023-03-29 11:26 UTC, JuliaKirschenheuter commented on apps/files/templates/list.php
> +<nav aria-label="<?php p($l->t('Breadcrumb navigation'))?>" class="files-controls">
Good idea, but to implement it would take more time. The main issue of this ticket was a wrong structure of navigation. I think we can take it to the next improvements. I will ask Michael if current solution is ok.

2023-03-29 14:38 UTC, skjnldsv commented
> Regarding narrow screens? If yes, then yes, we can just hide breadcrumbs visually and from screen readers

Yes, that's what I meant. ANd the menu should be hidden from the screen readers

2023-04-03 13:28 UTC, JuliaKirschenheuter commented on apps/files/templates/list.php
> +<nav aria-label="<?php p($l->t('Breadcrumb navigation'))?>" class="files-controls">
I've removed `aria-label` for now. It is not really required (semantic is right now) and better to fix it in NcVue

2023-04-03 13:29 UTC, JuliaKirschenheuter commented
> Yes, that's what I meant. ANd the menu should be hidden from the screen readers

I would like to make one fix in NcVue. For now i would like to live this fix only for html semantic structure.

2023-04-03 13:35 UTC, artonge approved these changes

2023-04-03 13:35 UTC, artonge commented on apps/files/js/breadcrumb.js
> +				this.$el.append($crumbList);
Won't this add the crumbList multiple times ?

2023-04-03 13:35 UTC, artonge requested changes
See last review

2023-04-03 13:43 UTC, JuliaKirschenheuter commented on apps/files/js/breadcrumb.js
> +		this.$el = $('<ul class="breadcrumb"></ul>');
NcVue issue: https://github.com/nextcloud/nextcloud-vue/issues/3951

2023-04-03 13:51 UTC, JuliaKirschenheuter commented on apps/files/js/breadcrumb.js
> +				this.$el.append($crumbList);
Thank you. Corrected

2023-04-03 14:24 UTC, artonge approved these changes

2023-04-03 18:10 UTC, Pytal approved these changes

2023-04-04 12:54 UTC, merged

2023-04-05 09:14 UTC, juliushaertl commented
@JuliaKirschenheuter This seems to have broken styling on the file picker as the DOM structure wasn't adjusted there.

You can see that the Home icon and bread crumb separators are missing in the failing text CI:
https://cloud.cypress.io/projects/hx9gqy/runs/9324/test-results/2ff09836-0f4f-4bcb-8db8-c2c6f45de6d8/screenshots?reviewViewBy=FAILED&utm_source=github&utm_medium=failed&utm_campaign=view+test+screenshots&roarHideRunsWithDiffGroupsAndTags=1

We try to click the home icon to go back which fails since this PR was merged.

2023-04-05 09:17 UTC, juliushaertl commented
Looking into a fix

2023-04-05 11:23 UTC, JuliaKirschenheuter commented
> This seems to have broken styling on the file picker as the DOM structure wasn't adjusted there.

Thank you @juliushaertl for fixing it. As i've replaced a structure i haven't found a usage in a file picker. I will pay more attention next time and make a double check if something was not adjusted 👍