Refactor OCP\Share\IShare ID to int
nextcloud/server pull request #37466
Opened 2023-03-29 14:55 UTC by provokateurin

## Summary

There is a lot of confusion in the code about what the type of IShare ID is. In the database it's an integer, so I switched it to int everywhere where it is possible. Sadly this doesn't apply to all places, because sometimes you get the id of a remote share and those have to be handled as strings for compatibility reasons.

I also thought that we could make everything a string and only convert it to an integer for the database queries to remove all the different types and have it only as string. IMO this is the easier solution, but also makes the code more fragile since future devs might not be aware that the ids have to be valid integers although they are typed as string everywhere.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-03-29 15:28 UTC, ChristophWurst commented on lib/public/Share/IShare.php
> +	 * @return int
this is a breaking change if the phpdoc is/was correct

2023-03-29 15:31 UTC, provokateurin commented on lib/public/Share/IShare.php
> +	 * @return int
I know, how do I document it except for adding it to the 27 changes issue?
I think technically it's not even a breaking change since the casting from/to int/string should always work.

2023-03-29 18:07 UTC, provokateurin commented on lib/public/Share/IShare.php
> +	 * @return int
Would you still consider it a breaking change, since it definitely changes the outline of the interface, but it's only a bugfix and has been broken anyway?

2023-03-30 06:56 UTC, ChristophWurst commented on lib/public/Share/IShare.php
> +	 * @return int
in the light of your findings it is probably not a breaking change

2023-03-30 07:00 UTC, ChristophWurst reviewed
Good clean-up. Let's enforce the types while we're here.

2023-03-30 07:14 UTC, provokateurin commented
Yes, I forgot that. Better do it now

2023-03-30 07:23 UTC, nickvergessen requested changes
While I get the point, this again is going to break lot of things down the road.

2023-03-30 07:25 UTC, provokateurin commented on lib/public/Share/IShare.php
> +	 * @return int
Ah shit I forgot that it parses the int and converts it to a string. So while it was set to int everywhere, it's actually always a string... dead end again lol

2023-03-30 07:26 UTC, closed without merging

2023-03-30 07:26 UTC, nickvergessen commented on lib/public/Share/IShare.php
> +	 * @return int
And similar code is also found in apps. So since it's public API it has to stay or be announced 3 years in advance *sigh*

* Talk https://github.com/nextcloud/spreed/blob/5f096c611cf5fa879941e9fd85a9d8ac869d6845/lib/Files/Util.php#L108
* Text https://github.com/nextcloud/text/blob/f8b122502316a02581185add11bc8b9941097ba2/lib/Controller/WorkspaceController.php#L157

2023-03-30 07:27 UTC, provokateurin commented on lib/public/Share/IShare.php
> +	 * @return int
I wanna cry :sob: