feat(files): implement shift-select
nextcloud/server pull request #37639
Opened 2023-04-07 09:50 UTC by skjnldsv

- When selecting a file, we store its reference
- When using Shift+select, we use the previous reference to select all files in between
- If the clicked file is already selected, we update the selection from the saved reference

![Peek 07-04-2023 11-49](https://user-images.githubusercontent.com/14975046/230587616-cd6ebec4-cc3e-454a-a8a1-ecdcdedadf31.gif)

PS: I'll wait before compiling assets to avoid rebasing

Fix #3484 
cc @jancborchardt @nimishavijay for UX

2023-04-07 11:10 UTC, skjnldsv commented
An additional question for the design team, do we still want the "range select" option ?
It was implemented to mitigate the fact that we didn't support the shift+select option, correct? Do we still need it?

2023-04-10 17:47 UTC, Pytal approved these changes

2023-04-10 17:47 UTC, Pytal commented on apps/files/src/store/keyboard.ts
> +/* eslint-disable */
```suggestion

```

2023-04-10 17:47 UTC, Pytal commented on apps/files/src/store/keyboard.ts
> +				if (!event) event = window.event as MouseEvent | KeyboardEvent
```suggestion
				if (!event) {
					event = window.event as MouseEvent | KeyboardEvent
				}
```

2023-04-10 17:47 UTC, Pytal commented on apps/files/src/store/paths.ts
> +				return (service: string, path: string): FileId|undefined => {
```suggestion
				return (service: string, path: string): ?FileId => {
```

2023-04-11 08:42 UTC, szaimen commented
I get an error during compiling while trying to test this:
![image](https://user-images.githubusercontent.com/42591237/231105484-0dd79a6d-4797-475b-b33a-a57aa6b5eea3.png)

2023-04-11 09:21 UTC, skjnldsv commented on apps/files/src/store/paths.ts
> +				return (service: string, path: string): FileId|undefined => {
`?FileId` !== `FileId|undefined` :)

2023-04-11 09:48 UTC, szaimen requested changes
This doesnt work in my testing.

I made a screen recording. See:
<details>
<summary>Click here</summary>


https://user-images.githubusercontent.com/42591237/231123568-1de9230b-d85e-4f99-8d70-ea6c0c9dc212.mp4



</details>

2023-04-11 10:37 UTC, skjnldsv commented
> Good question. For people who do not use a keyboard, this could be a nice way to select multiple files. It is hidden away in the 3 dot menu so I think it is okay to keep :)

Will do in a dedicated PR :+1:

2023-04-11 10:45 UTC, szaimen approved these changes
Works now but didnt review the code

2023-04-11 11:56 UTC, merged