fix(dav): Parse sender PARTSTAT in REPLYs
nextcloud/server pull request #37645
Opened 2023-04-07 13:23 UTC by miaulalala

* Resolves: #36554

## Summary

Parse the PARTSTAT of the sender if the iMIP method is `REPLY`. Will make iMIP emails more fany and tell the recipient if the attendee has accepted, declined or tentatively accepted in the mail itself:

| Before | After |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/7427347/230615651-e918e7e0-cde5-4138-9130-36198ce3354f.png) | ![image](https://user-images.githubusercontent.com/7427347/230614756-43a1d565-1ae8-4ab1-b06c-7a5fbe709230.png) | 

(Strings need to be translated yet)
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-07 13:23 UTC, miaulalala commented
/backport to stable26

2023-04-07 13:54 UTC, tcitworld commented on apps/settings/templates/settings/admin/additional-mail.php
> +	'LOGIN' => $l->t('AUTOCONFIG')
**nitpick (blocking):** Unrelated changes

2023-04-07 13:54 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$partstat = $replyingAttendee->offsetGet('PARTSTAT');
**issue (blocking):** As psalm noticed, doesn't handle `$replyingAttendee` being null.

2023-04-07 13:54 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +					$template->addHeading($this->l10n->t('%1$s has tentatively accepted your invitation', [$sender]));
**suggestion (non-blocking):** If any other people have ideas to make this sentence clearer, there's probably room for improvement.

2023-04-07 13:55 UTC, tcitworld commented
Nice improvement!

2023-04-07 13:56 UTC, miaulalala commented on apps/settings/templates/settings/admin/additional-mail.php
> +	'LOGIN' => $l->t('AUTOCONFIG')
ugh yeah

2023-04-11 11:27 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +					$template->addHeading($this->l10n->t('%1$s has tentatively accepted your invitation', [$sender]));
```suggestion
					$template->addHeading($this->l10n->t('%1$s has provisionally accepted your invitation', [$sender]));
```

maybe?

2023-04-12 18:17 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +					$template->addHeading($this->l10n->t('%1$s has tentatively accepted your invitation', [$sender]));
Leaving this for now, it's technically correct (the best kind of correct).

2023-04-12 18:21 UTC, AndyScherzinger approved these changes

2023-04-12 18:41 UTC, fabricemous commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +					$template->addHeading($this->l10n->t('%1$s has tentatively accepted your invitation', [$sender]));
@miaulalala I agree. I see no way to improve this. Unless your are making that line longer or when shuffling the direct object of that sentence.

2023-04-13 10:51 UTC, fabricemous approved these changes
Seen it and I think this is best sentence to use

2023-04-13 14:46 UTC, ChristophWurst requested changes, later dismissed

2023-04-13 14:46 UTC, ChristophWurst commented on apps/settings/templates/settings/admin/additional-mail.php
> +					<span class="icon-info" title="<?php p($l->t('Authentication method will be detected automatically')); ?>"></span>
unrelated

2023-04-17 21:49 UTC, merged