feat(SpeechToText): Add SpeechToText provider API
nextcloud/server pull request #37674
Opened 2023-04-11 13:06 UTC by marcelklehr

## Summary
Implement an OCP API register and call SpeechToText providers

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-12 07:00 UTC, juliushaertl commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
Since we talked about the path being a temp location, we may not be able to do this because the cron job may not run on the same physical server as where the job gets scheduled. So maybe we need to require having the file in the root folder

2023-04-12 07:00 UTC, juliushaertl commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
Another option might be to just pass the context and emit an event also before transcribing that could just provide the file then as a local copy

2023-04-12 08:48 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
> So maybe we need to require having the file in the root folder


That would not scale for transcripting talk recordings, or am I missing something?

2023-04-12 09:51 UTC, marcelklehr commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
Why would it not scale? The recordings are stored in some user folder eventually, right?

2023-04-12 09:53 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
> The recordings are stored in some user folder eventually, right?

Ah okay, if that is meant with rootfolder yeah. I thought it meant root as in /temp, server root, etc.

2023-04-12 09:54 UTC, juliushaertl commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(string $path): string;
Yes, I was referring to the data folder as in either user files or appdata

2023-04-12 14:52 UTC, marcelklehr commented on lib/public/SpeechToText/ISpeechToTextProvider.php
> +	public function transcribeFile(File $file): string;
Changed this now to take a File instead of a path

2023-04-12 15:26 UTC, nickvergessen requested changes

2023-04-12 15:26 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function scheduleFileTranscription(string $path, array $context): void;
Also use `OCP\Files\File` here?

The unclear defined `context` is a bit weird as well.
Maybe just enforce a pattern? Things that come to mind:

- app id
- user
- file id (also solved by working with the Node everywhere)
- time of request

In case you are storing it somewhere the data length might be limited (e.g. 4k chars for background jobs).

So maybe just use a `referenceId` which is `<appid>-sha1(*)` this way we have a fixed non-colliding layout and also a very defined type and max length?

2023-04-12 15:26 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function transcribeFile(string $path) : string;
```suggestion
	public function transcribeFile(string $path): string;
```

2023-04-12 15:26 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function transcribeFile(string $path) : string;
What is the returned string? The transcribe? A path to a file with the transcribe?

Also this method should work on a node?

2023-04-12 15:26 UTC, nickvergessen commented on lib/public/SpeechToText/Events/TranscriptionFinishedEvent.php
> +		private bool $successful,
Could also make this class abstract and have a dedicated Success and Failed event extending this one?

2023-04-12 15:26 UTC, nickvergessen commented on lib/private/SpeechToText/TranscriptionJob.php
> +namespace OC\SpeechToText;
missing declare strict_types + author + copyright

2023-04-12 15:26 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$node = $this->rootFolder->get($path);
I would prefer to not do another roundtrip. In most cases the app should have the node already and would just pass that one on

2023-04-12 15:26 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$node = $this->rootFolder->get($path);
Same here, just require the node to be injected

2023-04-12 16:49 UTC, marcelklehr commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function scheduleFileTranscription(string $path, array $context): void;
I was trying to spare you the need to do book-keeping and potentially having to create another db table just for this identifier. I like simply using the file Id, would this be enough, do you think, to simply drop the context param altogether?

2023-04-12 16:51 UTC, marcelklehr commented on lib/public/SpeechToText/Events/TranscriptionFinishedEvent.php
> +		private bool $successful,
:+1:

2023-04-12 18:03 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function scheduleFileTranscription(string $path, array $context): void;
Should be fine as long as not 2 apps/actions do the same file :P

2023-04-13 09:37 UTC, marcelklehr commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function scheduleFileTranscription(string $path, array $context): void;
Should still be fine in that case, as it's the same content then, no?

2023-04-13 10:15 UTC, marcelklehr commented on lib/private/SpeechToText/TranscriptionJob.php
> +namespace OC\SpeechToText;
Fixed

2023-04-13 13:12 UTC, nickvergessen requested changes

2023-04-13 13:12 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +		return !empty($context->getTranslationProviders());
**issue (blocking):** 
```suggestion
		return !empty($context->getSpeechToTextProviders());
```

2023-04-13 13:12 UTC, nickvergessen commented on lib/public/SpeechToText/Events/TranscriptionFailedEvent.php
> +class TranscriptionFailedEvent extends AbstractTranscriptionEvent {
**issue (blocking):** InvalidDocblock

> lib/public/SpeechToText/Events/TranscriptionFailedEvent.php:29:1: InvalidDocblock: PHPDoc is required for classes/interfaces in OCP. (see https://psalm.dev/008)

2023-04-13 13:12 UTC, nickvergessen commented on lib/public/SpeechToText/Events/AbstractTranscriptionEvent.php
> +		private int $fileIdId
**suggestion:** you have the node object in all cases already, just pass that one through the events, to avoid the listeners having to load the node themselves (we will do it otherwise for each listener individually).

2023-04-13 13:17 UTC, marcelklehr commented on lib/public/SpeechToText/Events/AbstractTranscriptionEvent.php
> +		private int $fileIdId
I initially wanted to use the Node object directly, but we actually do not have the node object in all cases, eg. in case the file was removed before the background job is run. For the successful case we definitely have the Node object, but then the API would be different between successful and failed :shrug: I don't mind either way, personally, I like it better the way it is now, but of course it's less performant.

2023-04-13 17:45 UTC, marcelklehr commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
Note to self: Using the jobs table as a queue is a bad idea if the jobs take longer than 5mins (which they do)

2023-04-13 21:22 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
Should still be fine? Jobs are reserved with a timestamp lock. Only becomes problematic after 1h, then the log is ignored

2023-04-14 05:41 UTC, marcelklehr commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
I was thinking because multiple jobs may run at the same time if we leave it like this. That may not be expected for admins. If they set up a worker or even multiple for these it's fine, but for a normal 1machine-server it would clog up the CPUs.

2023-04-17 13:17 UTC, marcelklehr commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
This one is kinda hard to do, as querying jobs inside a job class will likely manipulate the current job object :/

2023-04-17 13:17 UTC, marcelklehr commented on lib/public/SpeechToText/Events/AbstractTranscriptionEvent.php
> +		private int $fileIdId
I've added a nullable File argument to the Abstract Event class now

2023-04-17 13:34 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			}
```suggestion
```

Should not be needed. It's already dealt with inside:
https://github.com/nextcloud/server/blob/d74044f6341e93861d820f21b6d37a2f98e1ef60/lib/private/BackgroundJob/JobList.php#L70

2023-04-17 13:58 UTC, nickvergessen approved these changes

2023-04-17 14:25 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +		$provider = current($this->getProviders());
I wonder if we should instead loop over all providers (maybe they are language dependent) and return the result from the first one that was successful. Similar to the translation API:
https://github.com/nextcloud/server/blob/3e6329838158892e3b89c7e5116fa313c282a8a1/lib/private/Translation/TranslationManager.php#L66-L80

2023-04-17 14:36 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	 * @throws RuntimeException If the transcription failed for other reasons
**Suggestion:** Not applicable on scheduled transcript

2023-04-17 14:37 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	 * @returns string The transcription of the the passed media file
**Suggestion:**
```suggestion
	 * @returns string The transcription of the passed media file
```

2023-04-17 14:38 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	public function transcribeFile(File $file) : string;
Coding style:
```suggestion
	public function transcribeFile(File $file): string;
```

2023-04-17 14:44 UTC, marcelklehr commented on lib/private/SpeechToText/SpeechToTextManager.php
> +		$provider = current($this->getProviders());
Yeah, good point, will change this

2023-04-17 15:24 UTC, julien-nc reviewed
Just a few small remarks.

2023-04-17 15:24 UTC, julien-nc commented on lib/private/SpeechToText/SpeechToTextManager.php
> +					'exception' => $e
```suggestion
					'exception' => $e,
```
Nitpicking.

2023-04-17 15:24 UTC, julien-nc commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$class = $providerRegistration->getService();
```suggestion
		foreach ($context->getSpeechToTextProviders() as $providerServiceRegistration) {
			$class = $providerServiceRegistration->getService();
```
Just a suggestion.

2023-04-17 16:31 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +		throw new RuntimeException('Could not transcribe file');
Missing import?
Class, interface or enum named OC\SpeechToText\RuntimeException does not exist

2023-04-18 08:00 UTC, nickvergessen commented on lib/private/SpeechToText/TranscriptionJob.php
> +		$fileId = $argument['fileId'];
We never do this in background jobs. Whatever is meant to be given is expected.

2023-04-18 19:56 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
Looking at talk, we might want to store the acting user as well.
Will try to analyse tomorrow if the transript could end up for a wrong user when the recording was already shared to a room. But it would also lighten the logic in the background job if we additionally add the user.

2023-04-19 09:26 UTC, marcelklehr commented on lib/private/SpeechToText/SpeechToTextManager.php
> +			$this->jobList->add(TranscriptionJob::class, ['fileId' => $file->getId()]);
Added the user now as a job argument

2023-04-19 10:26 UTC, nickvergessen commented on lib/private/SpeechToText/SpeechToTextManager.php
> +	public function scheduleFileTranscription(File $file): void {
As discussed, to make app live easier, we should allow passing in `string $appId` and `?string $userId` here and emit return them on events

2023-04-19 10:41 UTC, nickvergessen commented on lib/public/SpeechToText/ISpeechToTextManager.php
> +	 * @param string $userId The user that triggered this request (only for convenience, will be available on the TranscriptEvents)
```suggestion
	 * @param ?string $userId The user that triggered this request (only for convenience, will be available on the TranscriptEvents)
```

2023-04-19 11:43 UTC, nickvergessen approved these changes

2023-04-19 12:52 UTC, julien-nc approved these changes

2023-04-19 13:06 UTC, marcelklehr commented
Documentation pr: https://github.com/nextcloud/documentation/pull/10085

2023-04-19 14:29 UTC, merged

2023-04-19 15:36 UTC, nickvergessen commented
Don't forget to add an entry in https://github.com/nextcloud/server/issues/37039 referencing this PR and the documentation page

2023-04-19 17:51 UTC, marcelklehr commented
Isn't #37039 only for (breaking) changes? I didn't know we also add additions there, that's also why I didn't add the translations API there. Will add this, though.

2023-04-19 18:38 UTC, nickvergessen commented
> that's also why I didn't add the translations API there.

Yeah I complained about this already.

No, it used to be breaking changes only, but now it's basically the OCP changelog.