app type extended_authentication
nextcloud/server pull request #37680
Opened 2023-04-11 20:10 UTC by ArtificialOwl

2023-04-12 09:51 UTC, ArtificialOwl commented
/backport to stable26

2023-04-12 09:52 UTC, ArtificialOwl commented
/backport to stable25

2023-04-12 10:21 UTC, blizzz requested changes
Please add new type also to `resources/app-info.xsd` and `resources/app-info-shipped.xsd` (this will need a PR to the appstore as well)

2023-04-12 10:23 UTC, blizzz commented
Unsure about the name, it is not saying much, however to my mind nothing great is coming either. I could think of `umbrella_authentication` or `catchall_authentication`  or `supre_authentication` but it is not necessarily better, latter might be confusing even. So, wording not a blocker, but open for improvements.

2023-04-12 10:29 UTC, ArtificialOwl commented
> 

good luck with that :-D
`extended_authentication` already took me a while. But the more I see it, the more it makes sense for me (from the `globalsiteselector` point of view).

2023-04-12 10:35 UTC, ArtificialOwl commented
> Please add new type also to `resources/app-info.xsd` and `resources/app-info-shipped.xsd` (this will need a PR to the appstore as well)

done and squashed

2023-04-12 10:40 UTC, blizzz approved these changes

2023-04-12 13:18 UTC, icewind1991 approved these changes

2023-04-12 14:22 UTC, merged

2023-05-31 12:32 UTC, ChristophWurst commented
This change may affect app devs and should be documented