Factorize query for searching contacts
nextcloud/server pull request #3770
Opened 2017-03-08 11:05 UTC by tcitworld

Detecting this as slow mysql queries.

It changes from
```
SELECT c.carddata, c.uri 
FROM oc_cards c 
WHERE c.id IN (
   SELECT DISTINCT cp.cardid 
   FROM oc_cardsproperties cp 
   WHERE (
      (
          (cp.name = 'EMAIL') AND (cp.value COLLATE UTF8 general_ci LIKE '%P%')
       ) OR (
          (cp.name = 'FN') AND (cp.value COLLATE UTF8_general_ci LIKE '%P%'))
       ) AND (cp.addressbookid = '2'
   )
);
```
to something like
```
SELECT c.carddata, c.uri
FROM oc_cards c
WHERE c.id IN (
    SELECT DISTINCT cp.cardid 
    FROM oc_cardsproperties cp 
    WHERE (
        (
            (cp.name = 'EMAIL') OR (cp.name = 'FN')
        ) AND (cp.value COLLATE UTF8_general_ci LIKE '%P%')
        ) AND (cp.addressbookid = '2')
    );
```

2017-03-08 11:11 UTC, nickvergessen requested changes

2017-03-08 11:11 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
>  		$query2->andWhere($query2->expr()->eq('cp.addressbookid', $query->createNamedParameter($addressBookId)));
move this up, should be the first thing checked.

2017-03-08 13:18 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
>  		$query2->andWhere($query2->expr()->eq('cp.addressbookid', $query->createNamedParameter($addressBookId)));
Fixed.

2017-03-09 20:25 UTC, rullzer requested changes

2017-03-09 20:25 UTC, rullzer commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
This should be before the value match.

2017-03-10 08:41 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +				$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
Fixed

2017-03-10 13:39 UTC, rullzer approved these changes

2017-03-16 12:29 UTC, nickvergessen submitted a review, later dismissed

2017-03-16 12:29 UTC, nickvergessen commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
This seems to not be added to the query anymore. orX() returns the query part, but you are not adding it to query2?

2017-04-04 08:38 UTC, ChristophWurst commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
@tcitworld ping :)

2017-04-04 09:44 UTC, tcitworld commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
Hmm, I need to test it again. I guess I forgot something while correcting reviews.

2017-04-19 01:23 UTC, MorrisJobke commented on apps/dav/lib/CardDAV/CardDavBackend.php
> +			$query2->expr()->orX($query2->expr()->eq('cp.name', $query->createNamedParameter($property)));
@tcitworld Any news? How likely is this to be ready to merge within the next week?

2017-04-21 18:44 UTC, rullzer commented
Fixed the query. @MorrisJobke @nickvergessen please have a look.

2017-04-21 19:22 UTC, MorrisJobke approved these changes
Tested and still works 👍

2017-04-21 19:25 UTC, MorrisJobke commented
@tcitworld Could I ask you to add a sign-off to your commit? Then this is ready for merge. https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

2017-04-27 03:25 UTC, MorrisJobke commented
Minimal change only -> merge

2017-04-27 03:25 UTC, merged