fix: Skip registering mount points for missing owner node
nextcloud/server pull request #37736
Opened 2023-04-14 12:45 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-14 16:09 UTC, skjnldsv approved these changes

2023-04-17 15:31 UTC, come-nc approved these changes
The root problem is in the move logic no, it should somehow update the share info?

2023-04-20 13:31 UTC, icewind1991 requested changes
This is a pretty expensive operation to perform for each incoming share and will kill performance for users with a large number of incoming shares.

2023-04-20 13:32 UTC, icewind1991 commented
It's probably better to catch this error when the user tries to interact with the broken. That way it doesn't have to run this check for N shares

2024-06-25 16:12 UTC, juliushaertl commented
I lack time to finish this, so I'll close for now. We can reopen anyways if we need.

2024-06-25 16:12 UTC, closed without merging