add an admin check for db file locking
nextcloud/server pull request #37766
Opened 2023-04-17 09:46 UTC by szaimen

See https://www.reddit.com/r/NextCloud/comments/12orc84/tip_always_configure_redis_for_file_locking/

2023-04-17 11:25 UTC, nickvergessen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
Only show this when redis/memcache is there?

2023-04-17 12:22 UTC, szaimen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
You mean if redis/memcached is not used?

2023-04-17 12:28 UTC, nickvergessen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
If they are used in general, but not for locking.

If no redis/memcached is there, there is already a message about it, so no need to add a second one:
![image](https://user-images.githubusercontent.com/213943/232483928-3f4cf96e-4902-42c9-8481-934a624ceaf4.png)

2023-04-17 12:34 UTC, szaimen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
Ah I see. Let me investigate then

2023-04-17 16:14 UTC, pulsejet approved these changes

2023-04-17 17:20 UTC, nickvergessen requested changes

2023-04-17 17:20 UTC, nickvergessen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
Then let's use a less aggressive wording, because there is no performance issue with many small user-count instances

```suggestion
							msg: t('core', 'The database is used for transactional file locking. To enhance performance, please configure memcache, if available. See the {linkstart}documentation ↗{linkend} for more information.')
```

2023-04-17 22:00 UTC, szaimen commented on apps/settings/tests/Controller/CheckSetupControllerTest.php
> +			->willReturn(true);
![image](https://user-images.githubusercontent.com/42591237/232620254-16ffc169-c8bc-443e-909a-d1dda0629bac.png)

2023-04-18 04:24 UTC, nickvergessen commented on apps/settings/tests/Controller/CheckSetupControllerTest.php
> +			->method('hasDBileLocking')
```suggestion
			->method('hasDBFileLocking')
```

2023-04-18 09:34 UTC, szaimen commented on apps/settings/tests/Controller/CheckSetupControllerTest.php
> +			->method('hasDBileLocking')
oh man 🙈😅

2023-04-18 09:35 UTC, szaimen commented on core/js/setupchecks.js
> +							msg: t('core', 'The database is used for transactional file locking. This will lead to performance issues. Use redis for transactional file locking to improve the performance. See the {linksta
done

2023-04-18 09:45 UTC, nickvergessen approved these changes

2023-04-18 11:31 UTC, merged