chore(assets): Require scour 0.38.2 (Ubuntu LTS 22.04+) for SVG optimization
nextcloud/server pull request #37763
Opened 2023-04-17 08:58 UTC by nickvergessen

* Resolves: # 36014

## Summary

* Pin scour version minimum
* Optimize all SVGs
* Optimize new PNGs and JPGs

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-19 14:04 UTC, jancborchardt commented on cypress/fixtures/image.jpg
Is this something we should touch? Or should this also be excluded/ignored?

2023-04-19 14:05 UTC, jancborchardt commented on build/integration/data/coloured-pattern-non-square.png
This we should probably exclude as well?

2023-04-19 14:05 UTC, jancborchardt commented on build/integration/data/green-square-256.png
This we should probably exclude as well?

2023-04-19 14:06 UTC, jancborchardt requested changes
Added comments on 3 images I’m not sure we should touch – otherwise it looks good! :)

2023-04-24 07:07 UTC, come-nc approved these changes

2023-04-24 07:08 UTC, ChristophWurst approved these changes
Nit: squash the commits into one to keep our git history light

2023-04-24 07:49 UTC, jancborchardt approved these changes

2023-04-24 09:53 UTC, merged