fix(files/fileactions.js): Do not show copy action when user doesn't …
nextcloud/server pull request #37802
Opened 2023-04-18 16:22 UTC by marcelklehr

…have update permissions

fixes #37729

* Resolves: #37729

<details>
<summary>Screencasts</summary>

Before
![Peek 2023-04-18 18-20](https://user-images.githubusercontent.com/986878/232841227-f360e68c-044d-4478-a7c5-ea322952a51d.gif)

After
![Peek 2023-04-18 18-18](https://user-images.githubusercontent.com/986878/232841259-d75607be-b888-430f-abad-d81671643ce4.gif)

</details>

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-19 08:32 UTC, artonge requested changes
Shouldn't the user be allowed to copy a file if he can read it?

2023-04-19 10:02 UTC, artonge commented
No, it is rather technical. If I can read the file, then copying is possible, either by copy-pasting, or if the software allows it, with one click.

I also just check and Nautilus is allowing copying read-only files. Same with bash.

2023-04-19 12:42 UTC, skjnldsv commented
> or we fix it in the backend to make it possible to copy files when the user has read permissions. I'll let you fight this out with @jancborchardt

I think this is the way to go as this is what I would expect from a dav endpoint.
The question here is where does it fail? When you copy, does it fail on the READ check, or on the WRITE permission of the destination folder?

2023-04-25 10:54 UTC, marcelklehr commented
Seems like the permission error stems from here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/DAV/ViewOnlyPlugin.php

2023-04-26 21:29 UTC, jancborchardt commented
Sorry, I assumed the backend was as intended. If not, then I would agree that this is rather something to fix in the backend. :)

2023-04-28 10:35 UTC, marcelklehr commented on apps/files_sharing/src/share.js
> +					if ((fileData.permissions & OC.PERMISSION_UPDATE) === 0) {
```
> (1 & 2 === 0)
0
> (1 & 2) === 0
true
```

:rage:

2023-04-28 10:56 UTC, marcelklehr commented
/rebase

2023-04-28 10:57 UTC, marcelklehr commented
It turns out, there was already code for this, but it didn't work.

2023-05-02 07:19 UTC, come-nc commented on apps/files_sharing/src/share.js
> +					if ((fileData.permissions & OC.PERMISSION_UPDATE) === 0) {
I always feel we do not put enough parenthesis in Nextcloud code, I tend to be paranoid about these things. There are so many operators it’s too hard to remember all priorities by heart.

2023-05-02 12:42 UTC, artonge approved these changes

2023-05-02 12:52 UTC, come-nc approved these changes

2023-05-02 13:45 UTC, marcelklehr commented
/compile

2023-05-03 08:57 UTC, merged

2023-06-07 07:52 UTC, marcelklehr commented
/backport to stable26

2023-06-07 07:52 UTC, marcelklehr commented
/backport to stable25

2023-06-07 08:26 UTC, marcelklehr commented
/backport af66537 to stable25

2023-06-07 17:40 UTC, solracsf commented
/backport to stable27

2023-06-07 19:21 UTC, solracsf commented
/backport https://github.com/nextcloud/server/commit/af665378f8428963f899f568a6cd5de9e233e82e to stable27