Add security information (IP and browser) to the password reset email
nextcloud/server pull request #37808
Opened 2023-04-18 23:41 UTC by susnux

* Resolves: #4345

## Summary
Add some metadata like the IP address and the browser type to the password reset mail for fraud detection.

## Screenshots

before | after
---|---
![image](https://user-images.githubusercontent.com/1855448/232927414-d08f654b-90b3-4885-afe0-9015b68533d5.png) | ![image](https://user-images.githubusercontent.com/1855448/232927855-95dcd9fc-1989-4a0c-adb6-235051bcb78c.png)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes

2023-04-19 07:12 UTC, nickvergessen requested changes

2023-04-19 07:12 UTC, nickvergessen commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
I would rephrase and reorder this information

> ## Password reset
>
> A password resset was requested from %1$s (IP address) and using %2$s.
> If you have not requested the password reset, then ignore this email.
> Otherwise, click the following link to reset your password.

2023-04-19 07:12 UTC, nickvergessen commented on core/Controller/LostController.php
> +			$platform = $this->l10n->t('unknown');
we should make sure that it does not show "unknown" when reset is done via a mobile app or the desktop client.

2023-04-19 22:24 UTC, susnux commented on core/Controller/LostController.php
> +			$platform = $this->l10n->t('unknown');
Good point, fixed.

2023-04-19 22:24 UTC, susnux commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
I have added that additional paragraph because of this comment: https://github.com/nextcloud/server/issues/4345#issuecomment-296418122

2023-04-20 04:34 UTC, nickvergessen commented on core/Controller/LostController.php
> +			$platform = $this->l10n->t('unknown');
Can you add the Talk clients too? 😅

2023-04-20 04:44 UTC, nickvergessen commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
So I checked all reset password emails in my inbox and most of them did not have information like this.
But if they did, it was the first information given.

cc @jancborchard for your 6y old comment

2023-04-20 04:45 UTC, nickvergessen commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
So I checked all reset password emails in my inbox and most of them did not have information like this.
But if they did, it was the first information given.

cc @jancborchardt for your 6y old comment

2023-04-20 07:55 UTC, come-nc commented
Stupid question maybe, but is there no data privacy implications here?
This is sending the IP and browser of a web visitor to another person by email. I understand in this case it’s the web visitor’s fault for entering the email address of someone else but laws may not be that precise?

2023-04-20 08:28 UTC, tobiasKaminsky commented
It is. Server is processing ip address and thus user must be informed prior to it.
(other services, e.g. Google go even further and try to locate ip address, to give user a better info where the login attempt was done, e.g "user tried to log in near Frankfurt")

As far as I know we do not ship by default such an information, so I tend to not include this at all.

2023-05-09 15:22 UTC, skjnldsv commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
also cc @nimishavijay :)

2023-05-09 15:33 UTC, nickvergessen commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
As per GDPR officer we can not do this:
https://github.com/nextcloud/server/pull/37808#issuecomment-1515931164

2023-05-11 08:27 UTC, skjnldsv commented on core/Controller/LostController.php
> +			htmlspecialchars($this->l10n->t('Security notice: This password reset was requested from following IP address and browser: %1$s (%2$s).', [ $this->request->getRemoteAddress(), $platform ]))
Then closing :)

2023-05-11 08:27 UTC, skjnldsv commented
As per GDPR officer we can not do this:
https://github.com/nextcloud/server/pull/37808#issuecomment-1515931164

2023-05-11 08:27 UTC, closed without merging

2023-05-11 15:15 UTC, susnux commented
Would it make sense to only include the browser?