Fix background color of external devices with errors on dark color theme
nextcloud/server pull request #37807
Opened 2023-04-18 21:43 UTC by susnux

* Resolves: #37373

## Summary
Currently if a external device has errors the background color of the files entry is hard coded, which will be unreadable on dark color mode.
To fix this I just overlay the background with semi transparent red color.

## Screenshots

before | after
---|---
![image](https://user-images.githubusercontent.com/1855448/232911520-3709ea67-cae3-4df2-b188-6725be5a1e1b.png) | ![image](https://user-images.githubusercontent.com/1855448/232911553-21a52cd6-6da4-4110-94e7-dc079f891407.png)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-18 21:43 UTC, susnux commented
/backport to stable25
/backport to stable26

2023-04-18 21:46 UTC, szaimen commented on apps/files_external/css/external.css
> +	background-color: #f002;
how would that look in light mode?

2023-04-18 23:48 UTC, susnux commented on apps/files_external/css/external.css
> +	background-color: #f002;
Bright color theme:

before | after
---|---
![image](https://user-images.githubusercontent.com/1855448/232928574-d72b9b51-4f00-4ac4-a80f-a08be67224fb.png) | ![image](https://user-images.githubusercontent.com/1855448/232928550-d921a34f-bcb2-4821-b9c6-1ed4c6620bec.png)

2023-04-18 23:49 UTC, szaimen approved these changes
looks fine from the screenshots

2023-04-19 10:08 UTC, skjnldsv requested changes

2023-04-19 10:08 UTC, skjnldsv commented on apps/files_external/css/external.css
> +	background-color: #f002;
I'm really not fond of hex syntax for alpha values :confused: 
```suggestion
	background-color: rgba(255, 0, 0, 0.13);
```

2023-04-19 22:04 UTC, susnux commented on apps/files_external/css/external.css
> +	background-color: #f002;
:+1:  fixed

2023-04-19 22:45 UTC, Pytal approved these changes

2023-04-20 06:37 UTC, skjnldsv approved these changes

2023-04-20 06:37 UTC, merged

2023-04-20 07:00 UTC, szaimen commented
/backport to stable26