debug log requests made by dav external storage/shares
nextcloud/server pull request #37818
Opened 2023-04-19 11:30 UTC by icewind1991

And add an event to the profiler while we're at it.

2023-04-19 15:17 UTC, blizzz commented on lib/private/Files/Storage/DAV.php
> +			$this->logger->debug("dav request to external storage: " . $request->getAbsoluteUrl() . " took " . round($elapsed * 1000, 1) . "ms");
'app' context would be useful to be able to set a log condition on it.

2023-04-20 09:40 UTC, come-nc commented on lib/private/Files/Storage/DAV.php
> +			$elapsed = microtime(true) - $lastRequestStart;
That works?
What is the scope of the `$lastRequestStart` var, PHP detects that both functions are using it and keeps it alive until both functions are deleted?

2023-04-20 13:04 UTC, icewind1991 commented on lib/private/Files/Storage/DAV.php
> +			$elapsed = microtime(true) - $lastRequestStart;
Yes, capturing it with the closure keeps the var alive. The trick only works because it's captured by reference though (else the closures get their unique copy).

2023-04-20 13:57 UTC, come-nc commented
@icewind1991 You pushed a change to 3rdparty

2023-04-20 15:32 UTC, blizzz requested changes
accidental bump to 3rdparty

2023-04-21 16:18 UTC, icewind1991 commented
fixed

2023-04-21 16:19 UTC, blizzz approved these changes

2023-04-24 07:22 UTC, come-nc approved these changes

2023-04-25 12:12 UTC, merged