Add api to change the remote of an incoming federated share
nextcloud/server pull request #3788
Opened 2017-03-09 15:51 UTC by icewind1991

required for user migration.

2017-03-09 19:56 UTC, rullzer requested changes

2017-03-09 19:56 UTC, rullzer commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +		$token = isset($_POST['token']) ? $_POST['token'] : null;
Please use function arguments for this (the appframework is your friend!)

2017-03-10 09:07 UTC, schiessle commented on apps/federatedfilesharing/appinfo/routes.php
> +		['root' => '/cloud', 'name' => 'RequestHandler#modify', 'url' => '/shares/{id}/modify', 'verb' => 'POST'],
Not sure if "modify" is to generic here, in L33 we have a end-point to change the permissions which is also some kind of "modify". I would prefer a name which actually describes what we modify. Maybe "move"?

2017-03-10 09:15 UTC, schiessle requested changes

2017-03-10 09:15 UTC, schiessle commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +			->set('remote', $qb->createNamedParameter($cloudId->getRemote()))
We want to set here the new `$remote` and not the old one, right?

2017-03-10 09:15 UTC, schiessle commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +			->set('owner', $qb->createNamedParameter($cloudId->getUser()))
Here we also want to set a new owner which should have been send along the request, not the one which was already set before

2017-03-10 13:35 UTC, icewind1991 commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +			->set('remote', $qb->createNamedParameter($cloudId->getRemote()))
`$cloudId` is created from the new `$remote`

2017-03-10 13:48 UTC, icewind1991 commented on apps/federatedfilesharing/appinfo/routes.php
> +		['root' => '/cloud', 'name' => 'RequestHandler#modify', 'url' => '/shares/{id}/modify', 'verb' => 'POST'],
done

2017-03-10 13:48 UTC, icewind1991 commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +		$token = isset($_POST['token']) ? $_POST['token'] : null;
done

2017-03-10 15:34 UTC, schiessle approved these changes

2017-03-15 16:32 UTC, rullzer approved these changes

2017-03-15 16:32 UTC, merged

2017-03-16 12:06 UTC, nickvergessen commented on apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
> +		$newRemoteId = $this->request->getParam('remote_id', $id);
This should simply be arguments to the function, it works for all parameters, not just those that are mentioned in the URL.
if you add `@param int` it will also automatically be casted then...