feat: Reword login form disabled warning #37949
nextcloud/server pull request #37953
Opened 2023-04-27 13:26 UTC by moan0s

* Resolves: #37949

## Summary

Rewords & restyles the warning used when the nextcloud login form is disabled

## TODO

- [ ] Decide if warning should be removed ([this PR](https://github.com/nextcloud/server/pull/37952) or if the text should be replaced (this PR)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-27 13:34 UTC, szaimen approved these changes
This PR is preferred by me over https://github.com/nextcloud/server/pull/37952. Just one small suggestion, see below.

2023-04-27 13:34 UTC, szaimen commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administrator.') }}
```suggestion
				<NcNoteCard type="warning" :title="t('core', 'Login form is disabled.')">
					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
```

2023-04-27 13:35 UTC, moan0s commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administrator.') }}
Okay :) Thanks for the quick response!

2023-04-27 13:46 UTC, skjnldsv approved these changes

2023-04-27 14:09 UTC, nimishavijay reviewed
Great catch, already a good improvement! left a comment with some slight changes in wording :)

2023-04-27 14:09 UTC, nimishavijay commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
For sure an improvement! :) Wondering if the wording of the first sentence could be simpler, maybe "Logging in using account name and password is disabled."? pinging @jancborchardt for opinions on wording :)

2023-04-27 14:14 UTC, moan0s commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
I think as users usually use an account name and password in the SSO login this could be puzzling? But I agree the wording could be simpler and I am not totally against this wording :)
Another idea: 

> Logging in via Nextcloud is disabled. Use another [...]

2023-04-27 14:37 UTC, jancborchardt commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
Mix of both and shortened:

If there are other options available:

> Login via Nextcloud account is disabled. Use another login option or contact your administration.

And if there are no other options available

> Login via Nextcloud account is disabled. Please contact your administration for other login options.

What do you think?

2023-04-27 15:48 UTC, moan0s commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
I think that works. My preference would be to to not show any warning (an info would be okay) as long as there is another login option.

Here is the version with `success`. I think that a `NcNoteCard` type `info` would be nice here (e.g. in blue) as `success` is not fitting, neither is `warning`. The easy way would be to show no message (just remove the else clause).

```html
        <div v-else-if="!alternativeLogins.length">
            <transition name="fade" mode="out-in">
                <NcNoteCard type="warning" :title="t('core', 'Login form is disabled.')">
                    {{ t('core', 'Login via Nextcloud account is disabled. Please contact your administration for other login options.') }}
                </NcNoteCard>
            </transition>
        </div>
        <div v-else>
            <transition name="fade" mode="out-in">
                <NcNoteCard type="success" :title="t('core', 'Login form is disabled.')">
                    {{ t('core', 'Login via Nextcloud account is disabled. Use another login option or contact your administration.') }}
                </NcNoteCard>
            </transition>
        </div>


```

2023-04-27 17:52 UTC, nimishavijay commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
Could you please share a screenshot so that it's easy for everyone to review the design? :)

2023-04-27 19:32 UTC, moan0s commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
I'll try (don't have a dev environment currently, will try to set it up)

2023-04-27 22:21 UTC, moan0s commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
Okay, got it

### NO alternative login configured

![No alternative login](https://user-images.githubusercontent.com/25753802/234999012-f125d47b-7f2b-41e0-9992-fe29b4985f77.jpeg)

### Alternative login is configured

**Option 1**
![image](https://user-images.githubusercontent.com/25753802/234999178-6819a10c-6fc8-435f-bb62-8c5c25dbdf10.png)

I think this version is okay, but the green checkmark is not ideal

**Option 2**

This the alternative where we drop the information altogether (when alternative login is configured, else the first screenshot applies)
![No extra information](https://user-images.githubusercontent.com/25753802/234999854-855be0d1-e293-4a2b-a006-dfe091cb4b52.png)

**Option 3**

And finally an alternative with a custom text that is neither warning, not success
![image](https://user-images.githubusercontent.com/25753802/235002802-3dcc8c7b-e91d-40aa-a340-3c20b7191e4f.png)

**Option 4**
Implement a new "info" typ of `NcNoteCard` that just provides additional information to the user.
As I have no experience with vue/anything frontend this would probably be to challenging for me to implement

2023-04-28 09:29 UTC, nimishavijay commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
Option 4 looks good to me! In fact, I'm certain that we have used an `info` notecard in Files for indicating when you are in a Collectives folder.

![image](https://user-images.githubusercontent.com/52440189/235108935-d9ae9400-b4b0-4acb-8f22-dab9c8bf30a9.jpg)

If this is not a variant of the notecard yet, it certainly should be! Instead of introducing another color, we could just use the primary color as the accent like in the Files screenshot.

- `--color-primary` for the icon and border  
- `--color-primary-light` for the background
- the same icon you suggested :) 

Feel free to open an issue about it in the [vue components repository](https://github.com/nextcloud/nextcloud-vue/) :)

2023-05-08 12:05 UTC, jancborchardt commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
@moan0s I really like your rewording plus style change to notecard-info. A blue info style is really missing – and yes I'd say let's make it blue (always, not depending on theme) as that's a standard for info color.

Since you say you have no Vue or general frontend experience, maybe @szaimen can help you contribute this to our Vue components library. :)

2023-05-08 14:09 UTC, szaimen commented on core/src/views/Login.vue
> +					{{ t('core', 'The Nextcloud login form is disabled. Use another login option if available or contact your administration.') }}
See https://github.com/nextcloud/nextcloud-vue/pull/4063#discussion_r1187487487 and below

2023-05-19 09:12 UTC, szaimen requested changes, later dismissed
Needs a new Nextcloud vue 8.x version now to get released, updated here in server. Then we can rebase this branch and afterwards include the change here.

2023-05-19 09:13 UTC, szaimen commented on apps/files/js/app.js
> +						),
unrelated change?

2023-05-19 09:13 UTC, szaimen commented on core/src/views/Login.vue
>  				<NcNoteCard type="warning" :title="t('core', 'Login form is disabled.')">
```suggestion
				<NcNoteCard type="info" :title="t('core', 'Login form is disabled.')">
```

2023-05-19 09:15 UTC, moan0s commented on apps/files/js/app.js
> +						),
Yes, don't know how it got there

2024-01-26 15:07 UTC, timonegk commented
I would also approve this change, any chance of merging it in the near future?

2024-03-17 18:56 UTC, susnux approved these changes

2024-03-17 18:58 UTC, susnux commented on apps/files/js/app.js
> +						),
Due to a rebase issue

2024-03-17 20:21 UTC, susnux commented
Rebased - but I think drone does not work on forks?

2024-03-19 08:14 UTC, merged