PoC: SystemTags endpoint to return tags used by a user with meta data
nextcloud/server pull request #37961
Opened 2023-04-27 20:34 UTC by blizzz

## Summary

Target case is photos app: when visiting the tags category, all systemtags of the whole cloud are retrieved. In subequent steps the next tag is requested until the browser view is filled with tag tiles (i.e. previews are requested just as well).

With this approach, we incorpoate the dav search and look for user related tags that are used by them, and already returns the statistics (number of files tagged with the respective tag) as well as a file id for the purpose to load the preview. This defaults to the file with the highest id.

Call:
```bash
curl -s -u 'user:password' \
  'https://my.nc.srv/remote.php/dav/systemtags-current' \
  -X PROPFIND -H 'Accept: text/plain' \
  -H 'Accept-Language: en-US,en;q=0.5'  -H 'Depth: 1' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  --data @/home/doe/request-systemtag-props.xml
```

With request-systemtag-props.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:">
        <d:prop xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
                <oc:id/>
                <oc:display-name/>
                <oc:user-visible/>
                <oc:user-assignable/>
                <oc:can-assign/>
                <nc:files-assigned/>
                <nc:reference-fileid/>
        </d:prop>
</d:propfind>
```

Example output:
```xml
  …
  <d:response>
    <d:href>/master/remote.php/dav/systemtags/84</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>84</oc:id>
        <oc:display-name>Computer</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-assignable>true</oc:user-assignable>
        <oc:can-assign>true</oc:can-assign>
        <nc:files-assigned>42</nc:files-assigned>
        <nc:reference-fileid>924022</nc:reference-fileid>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/systemtags/97</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>97</oc:id>
        <oc:display-name>Bear</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-assignable>true</oc:user-assignable>
        <oc:can-assign>true</oc:can-assign>
        <nc:files-assigned>1</nc:files-assigned>
        <nc:reference-fileid>923422</nc:reference-fileid>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  …
```

## TODO

- [ ] Performance testing with a serious data set 
- [ ] Reconsider pragmatic architectual choices (quick PoC)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-04-28 07:56 UTC, blizzz commented on apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
> +		$result = $userFolder->getSystemTags('image');
Accurate, the method is not included in the Interface so far.

2023-04-28 07:56 UTC, blizzz commented on lib/private/Files/Node/Folder.php
> +	protected function getCachesAndMountpointsForSearch(bool $limitToHome = false): array {
https://psalm.dev/docs/annotating_code/type_syntax/array_types/#list-shapes
I must oversee something?

2023-04-28 09:09 UTC, marcelklehr commented on lib/private/Files/Node/Folder.php
> +	protected function getCachesAndMountpointsForSearch(bool $limitToHome = false): array {
I don't see it either :/

2023-05-04 10:11 UTC, blizzz commented
Added support for media types and updated the information in the summary. 

Compared to the first commit, it's a little breaking, for filtering image files was hardcoded. To achive the same results run the query against `/remote.php/dav/systemtags-current/image`, otherwise tags relevant to any file type are returned.

2023-05-04 10:13 UTC, marcelklehr commented
Can we call the endpoint something more meaningful than systemtags-current?

2023-05-04 10:18 UTC, AndyScherzinger approved these changes
fine by me except other peoples comments of course. And would also love to have this in for 27 even if we might optimize further in the future or have a complete new solution for certain things regarding tags.

Also, given the time I think Beta2 would be fine.

2023-05-04 10:22 UTC, marcelklehr approved these changes

2023-05-04 10:31 UTC, blizzz commented
> Can we call the endpoint something more meaningful than systemtags-current?

We can, but do you have suggestions? Tbh, I am not super happy about it either, but was so far the best I could think of:

- "-current" says it is about tags that are in use at this time

And i disregarded following ideas, because

- "-used" could be appropriate, but it has a touch of the past, or could be misinterpreted as something trashed
- "-recent" could suggest that valid, but older tags would not be considered
- "-active" could be misleading (what is inactive?)
- "-user" could be misleading to be user-only tags

2023-05-04 10:46 UTC, blizzz commented
> fine by me except other peoples comments of course. And would also love to have this in for 27 even if we might optimize further in the future or have a complete new solution for certain things regarding tags.
>
> Also, given the time I think Beta2 would be fine.

Beta2 is fine, just one thing that is missing is also that we extend `Folder` with public methods, and that should be reflected in the PHP API. We should refrain from touching `\OCP\Files\Folder` as it has at least 8 implementations, which it would break. So we'll have to add a public interface, but when we do it, we should be sure about it.

Thus said I am not one hundred percent convinced our additions should stay in the Folder implementation, however there is some of the logic we need. We could have a SytemTag specific collection that could wrap it and so have little changes there, but would have a hard dependency on the Folder implementation (if only on few specific parts).

Or we expose what is consolidated here as `getCachesAndMountpointsForSearch` as PHP API, that can be then consumed by new SystemTag specific classes and have better separation.

Would love to have @icewind1991​'s opinion on it.

2023-05-04 10:51 UTC, marcelklehr commented
> We can, but do you have suggestions?

How about

* `systemtags-in-use`
* `systemtags-assigned`

2023-05-04 13:14 UTC, blizzz commented
> > We can, but do you have suggestions?
> 
> How about
> 
>     * `systemtags-in-use`
> 
>     * `systemtags-assigned`

`systemtags-assigned` sounds good to me, and yes, clearer than `current`.

2023-05-04 14:53 UTC, icewind1991 requested changes
Overall approach seems fine.

Not a big fan of adding it as a public method to folder but not sure if there is a better option

2023-05-04 14:53 UTC, icewind1991 commented on apps/dav/lib/SystemTag/SystemTagsInUseCollection.php
> +			$node = new SystemTagNode($tag, $user, false, \OCP\Server::get(ISystemTagManager::class));
inject `ISystemTagManager`?

2023-05-04 14:53 UTC, icewind1991 commented on lib/private/Files/Node/Folder.php
> +	public function getSystemTags(string $mediaType, int $limit = 0, int $offset = 0): array {
this could use a more descriptive name, something like `getUsedSystemTagsInFolder` or something

2023-05-04 14:53 UTC, icewind1991 commented on lib/private/Files/Node/Folder.php
> +			$query = $this->queryFromOperator(new SearchComparison(ISearchComparison::COMPARE_LIKE, 'systemtag', '%'), null, $limit, $offset);
does adding this operator do anything? `LIKE '%'` seems to be always true to me

2023-05-04 19:10 UTC, blizzz commented on lib/private/Files/Node/Folder.php
> +			$query = $this->queryFromOperator(new SearchComparison(ISearchComparison::COMPARE_LIKE, 'systemtag', '%'), null, $limit, $offset);
It's a shortcut to get a query to pass to `$searchHelper->findUsedTagsInCaches()`. Certainly this can be solved more elegantly. It was born out of the need to have something ready to bring Magenta back to a working state/environment.

2023-05-04 19:13 UTC, blizzz commented
> Not a big fan of adding it as a public method to folder but not sure if there is a better option

@icewind1991 yes feeling the same. One way to reduce the footprint would be to expose `getCachesAndMountpointsForSearch` only (new interface like  `ISearchAwareFolder` or something like that), then the rest  of the logic can be moved to classes withing the SystemTags namespace.

2023-05-05 19:24 UTC, blizzz commented on lib/private/Files/Node/Folder.php
> +	protected function getCachesAndMountpointsForSearch(bool $limitToHome = false): array {
this psalm version does not know such composed lists

2023-05-05 19:27 UTC, blizzz commented
> > Not a big fan of adding it as a public method to folder but not sure if there is a better option
> 
> @icewind1991 yes feeling the same. One way to reduce the footprint would be to expose `getCachesAndMountpointsForSearch` only (new interface like `ISearchAwareFolder` or something like that), then the rest of the logic can be moved to classes withing the SystemTags namespace.

But of course that leaves the changes within `OC\Files\Cache\`.  I have repressed it somehow, and from the hip not a quick solution for it. I've got a commit ready to do the former that I can push, if it makes a big difference.

Or we indeed keep it provide as it is for now, just to have it merged. And have time to rethink internal structure and the PHP API, and be it for 28. I am a bit concerned though that the follow up would compete with other important tasks.

2023-05-09 11:08 UTC, icewind1991 commented on lib/private/Files/Node/Folder.php
> +			$query = $this->queryFromOperator(new SearchComparison(ISearchComparison::COMPARE_LIKE, 'systemtag', '%'), null, $limit, $offset);
I suspect that this might interfere with picking an index so it would be better to have another way to flag that the query should join on thags.

2023-05-09 22:01 UTC, blizzz commented
@icewind1991 moved it to the search helper as suggested

2023-05-10 15:42 UTC, blizzz commented on lib/private/Files/Node/Folder.php
> +			$query = $this->queryFromOperator(new SearchComparison(ISearchComparison::COMPARE_LIKE, 'systemtag', '%'), null, $limit, $offset);
The behaviour appears same, however (checking with Postgrest) at some we'll have an `Index Scan using oc_systemtag_pkey on oc_systemtag systemtag  (cost=0.14..13.54 rows=69 width=20)` where the poential cost is slighlty lower when the comparison is not included. 13.54 instead of 13.72.

2023-05-11 08:13 UTC, blizzz commented
failing drone CI tests unrelated

2023-05-11 08:15 UTC, blizzz commented
Will need manual backports to 26 and 25

2023-05-11 08:16 UTC, merged

2023-05-11 08:17 UTC, blizzz commented
/backport to stable26

2023-05-11 08:19 UTC, AndyScherzinger commented
/backport to stable25

2023-05-16 11:17 UTC, blizzz commented
backports created manually