Add label to "default quota" multiselect
nextcloud/server pull request #38075
Opened 2023-05-04 13:42 UTC by JuliaKirschenheuter

* Resolves: #36923 

## Summary

Correct label for "default quota" multiselect. No visual changes.

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2023-05-04 15-39-41](https://user-images.githubusercontent.com/6078378/236222951-3e43b11b-5045-4238-aa27-1d627e703674.png) | ![Screenshot from 2023-05-04 15-17-29](https://user-images.githubusercontent.com/6078378/236222921-3acb9d34-eef3-4b56-9afe-aba802aaa75c.png)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-04 13:59 UTC, artonge reviewed
Can we take the opportunity to switch to NcSelect?
https://nextcloud-vue-components.netlify.app/#/Components/NcSelect

2023-05-05 11:40 UTC, JuliaKirschenheuter commented
> Can we take the opportunity to switch to NcSelect? https://nextcloud-vue-components.netlify.app/#/Components/NcSelect

I've converted NcMultiselect to NcSelect but have 2 problems: 

1. `:close-on-select="false"` seems not to work. I would like to record this odd behavior but unfortunately can't. Somehow it si not possible.

2. Have a problem with 'unlimited', If i'm choosing it -> 'none' will be shown. After page reloading i get correct 'unlimited'.

@Pytal , @susnux could you please check out this state and help me with correction? Thanks a lot!

2023-05-05 13:01 UTC, susnux commented
>     2. Have a problem with 'unlimited', If i'm choosing it -> 'none' will be shown. After page reloading i get correct 'unlimited'.

Because the `setDefaultQuota` sets the label to the id which is *undefined*, one had to `defaultQuota` in this case to `unlimitedQuota`. (I hope it was ok to push this directly? Feel free to squash / revert  :) )

2023-05-05 13:40 UTC, susnux requested changes

2023-05-05 13:40 UTC, susnux commented on apps/settings/src/views/Users.vue
>  				<NcAppNavigationSettings>
```suggestion
				<NcAppNavigationSettings :exclude-click-outside-selectors=".vs__dropdown-menu">
```

To fix closing if you click the dropdown menu  you will have to add it to the exclude list of the *click outside* trigger.

2023-05-05 13:40 UTC, susnux commented on apps/settings/src/views/Users.vue
> +							:close-on-select="false"
```suggestion
```
Not needed. Probably you want the dropdown (not the settings) to close as soon as you select a quota.

2023-05-05 14:21 UTC, JuliaKirschenheuter commented on apps/settings/src/views/Users.vue
> +							:close-on-select="false"
thank you!

2023-05-05 14:27 UTC, JuliaKirschenheuter commented on apps/settings/src/views/Users.vue
>  				<NcAppNavigationSettings>
unfortunately i can't see this prop in current Nc Vue version and can't build server with this prop too ;(

2023-05-05 14:32 UTC, JuliaKirschenheuter commented
> Because the `setDefaultQuota` sets the label to the id which is _undefined_, one had to `defaultQuota` in this case to `unlimitedQuota`. (I hope it was ok to push this directly? Feel free to squash / revert :) )

Thank you! Absolutely fine! Works

2023-05-05 15:00 UTC, susnux commented on apps/settings/src/views/Users.vue
>  				<NcAppNavigationSettings>
Its in the docs: https://nextcloud-vue-components.netlify.app/#/Components/App%20containers/NcAppNavigation?id=ncappnavigationsettings

But currently broken (fix is not released yet), to work we have to wait for 7.11.3.

2023-05-08 16:02 UTC, susnux commented on apps/settings/src/views/Users.vue
>  				<NcAppNavigationSettings>
> But currently broken (fix is not released yet), to work we have to wait for 7.11.3.

It is merged and should now work if you rebase the PR :)

2023-05-09 23:24 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +							@open="validateQuota"
```suggestion
							@option:created="validateQuota"
```
Seems to match https://vue-select.org/api/events.html#option-created?

2023-05-09 23:24 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +			if (quota === 'none') quota = this.unlimitedQuota
```suggestion
			if (quota === 'none') {
				quota = this.unlimitedQuota
			}
```

2023-05-09 23:26 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +							@open="validateQuota"
And needed the quota arg https://github.com/nextcloud/server/blob/784059fb3800636521d1e8af152bdac7b7f716ae/apps/settings/src/views/Users.vue#L382

2023-05-09 23:26 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +							@open="validateQuota"
And needed for the quota arg https://github.com/nextcloud/server/blob/784059fb3800636521d1e8af152bdac7b7f716ae/apps/settings/src/views/Users.vue#L382

2023-05-10 12:24 UTC, JuliaKirschenheuter commented on apps/settings/src/views/Users.vue
> +							@open="validateQuota"
have i resolved it?

2023-05-10 12:42 UTC, artonge approved these changes
Looks good

2023-05-10 12:42 UTC, artonge commented
Have you checked whether the quota is actually changed in the DB?

2023-05-10 13:09 UTC, JuliaKirschenheuter commented
> Have you checked whether the quota is actually changed in the DB?

I've checked it by reloading a page and by expecting a same value as set before. Should i double check in DB? Which table should i check for it? Thank you!

2023-05-10 22:59 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +							@open="validateQuota"
Don't think it works currently as the `:taggable="true"` is needed as described in https://vue-select.org/api/events.html#option-created

Also you'll have to make sure the quota passed to `validateQuota()` is a string and not an object

2023-05-11 14:10 UTC, susnux requested changes
Currently adding custom quotas is broken :/

2023-05-11 14:59 UTC, JuliaKirschenheuter commented on apps/settings/src/views/Users.vue
> +							@option:created="validateQuota"
Thank you!

2023-05-11 23:49 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +							:close-on-select="true"
```suggestion
```
Can be removed due to being the same as the default https://github.com/nextcloud/nextcloud-vue/blob/6969815a25b44486a3ccd2d86f27e40b6578b40d/src/components/NcSelect/NcSelect.vue#L594-L602

2023-05-18 22:45 UTC, Pytal approved these changes

2023-05-20 11:49 UTC, susnux commented on apps/settings/src/views/Users.vue
>  		 * @return {Promise|boolean}
Doc type does not match anymore

```suggestion
		 * @return {object} The validated quota object or unlimited quota if input is invalid
```

2023-05-20 11:50 UTC, susnux commented on apps/settings/src/views/Users.vue
> +				quota =  OC.Util.humanFileSize(OC.Util.computerFileSize(quota))
```suggestion
				quota = OC.Util.humanFileSize(OC.Util.computerFileSize(quota))
```

2023-05-20 11:50 UTC, susnux approved these changes
Besides that two minor comments everything is fine :smiley:

2023-05-23 13:01 UTC, artonge approved these changes

2023-05-23 13:33 UTC, merged