[user_status] Improve user online status modal
nextcloud/server pull request #38127
Opened 2023-05-08 15:21 UTC by susnux

* Resolves: #37097

## Summary
1. Fix the predefined statuses buttons to implement a role (radio) instead of being just tabable divs
    * Also set role to radiogroup of list container to group the predefined statuses
 2. Group custom message input elements and assign label to emoji selector
 3. Add missing `radiogroup` role to online status selector

## TODO
For 1: I have also created a commit where I use real radio buttons (in the background) for the predefined statuses, so the question is should I push it here too? Do we want native radio buttons instead? What do you think @Pytal @JuliaKirschenheuter ?

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes **no visual changes**
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-08 23:14 UTC, Pytal commented
Let's go with real radio inputs @susnux as it's the recommended way https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role#sect1 :)

2023-05-09 23:16 UTC, Pytal approved these changes

2023-05-11 12:58 UTC, susnux commented
/compile

2023-05-11 13:05 UTC, nickvergessen commented
Can we have before and after screenshots?

2023-05-11 13:23 UTC, Antreesy approved these changes
No visual changes (before => after), except for one:
* when selected 'button' is not in focus, it now keep selected styles
![image](https://github.com/nextcloud/server/assets/93392545/36090fdf-5b35-4290-b64f-eec685a3437b)

No blocking changes, except for redundant class

2023-05-11 13:24 UTC, Antreesy requested changes
And please rebuild

2023-05-11 14:22 UTC, susnux commented on apps/user_status/src/components/PredefinedStatus.vue
>  	}
We should then use it also for `OnlineStatusSelect.vue`

2023-05-11 14:28 UTC, susnux commented
/compile

2023-05-11 14:31 UTC, Antreesy approved these changes
:seal:

2023-05-15 12:37 UTC, susnux commented
rebased

2023-05-15 20:01 UTC, merged