fix(login): Make login form and footer look like a dashboard panel
nextcloud/server pull request #38131
Opened 2023-05-08 22:56 UTC by susnux

* Resolves: #36950

## Summary
1. Make the background of the login form look like a dashboard panel.
2. Add the same background style to the footer so it is independent of the background image / color and fulfill the contrast requirements.

## Screenshots

what | before | after
---|---|---
shot footer | ![Screenshot 2023-05-09 at 00-36-55 Nextcloud](https://user-images.githubusercontent.com/1855448/236953689-31a10684-d1b7-4e62-8575-6b850ce175fc.png)|![image](https://user-images.githubusercontent.com/1855448/236954845-afe080ea-1dcf-4621-ac30-929dad302381.png)
long footer | ![Screenshot 2023-05-09 at 00-38-35 Nextcloud](https://user-images.githubusercontent.com/1855448/236953672-f2472f50-8ae2-4ac1-8a21-3af740ded239.png)|![image](https://user-images.githubusercontent.com/1855448/236954751-bc0b558b-846c-4021-a37b-cb766cbf8c5c.png)
`color: white; background: black;`¹ |![Screenshot 2023-05-09 at 00-37-26 Nextcloud](https://user-images.githubusercontent.com/1855448/236953682-9be37ad6-4b5a-4d69-beb9-7d1881bb907c.png)|![image](https://user-images.githubusercontent.com/1855448/236954794-fbaa95c4-06f7-41f5-a45a-24f6f9430110.png)

¹: Like the issue: if the user agent uses a custom default browser theme

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes

2023-05-09 05:10 UTC, solracsf commented
IMO, the same type or border radius should be applied.

![image](https://user-images.githubusercontent.com/12234510/236999543-65af1165-20d2-4f84-b8d1-b5927a032fc6.png)

2023-05-09 13:16 UTC, susnux commented
@szaimen @solracsf there was a design discussion in the linked issue and also here https://github.com/nextcloud/server/issues/35482#issuecomment-1534723358, so I just picked the pill style as it seems to be the preferred one (?).

> maxbe also make it the same width like the login background?

I do not think that works, because the footer text is much wider, looks like this:

![image](https://github.com/nextcloud/server/assets/1855448/a5a23928-e059-4b28-a1e6-8a690885f203)

2023-05-09 14:36 UTC, solracsf commented
No problem, but from a design perspective, it makes no sense (to me) to have multiple border radius ;-)

2023-05-09 14:37 UTC, nimishavijay commented
I would vote for pill style too, so that it reflects how it looks in the dashboard (border-radius-large boxes, and the smaller buttons are pill shaped). What do you think? And agreed about the width, it might make the height too big, especially for translations. 

What do you think about the existing padding being reduced such that the height of the div is 44px? It could look like this:

<img src="https://github.com/nextcloud/server/assets/52440189/619ea9f6-dd33-4978-a185-fa94a9424fbe" width=50% height=50%>

2023-05-09 15:00 UTC, szaimen commented
with reduced padding it indeed looks much better 👍

2023-05-11 10:54 UTC, susnux commented
@nimishavijay is it very important that the footer is not wider than the login box?
Because for English it works, but most other languages I tried (French, Spanish, Portuguese, German) require more space (about 10 to 30px more).

I personally think that less height but wider footer look better:

Spanish (`min-width: 300px`) | Portuguese (`width: 300px`)
---|---
![image](https://github.com/nextcloud/server/assets/1855448/edf6eb56-5d5f-4b71-a99f-cb8a139ce315) | ![image](https://github.com/nextcloud/server/assets/1855448/2d0dbe13-8e6a-494b-9a45-608781424113)

2023-05-11 11:44 UTC, nimishavijay commented
> Because for English it works, but most other languages I tried (French, Spanish, Portuguese, German) require more space 

Oh it was a misunderstanding! I agreed with your point about the width, so it doesn't need to be limited :)

2023-05-11 11:45 UTC, nimishavijay approved these changes
Latest screenshots look great! Good to go design-wise :) 🚀

2023-05-11 15:58 UTC, jancborchardt approved these changes
Looks great @susnux! :) I’d actually say we could use an even larger border-radius for the login box as well – the same as for the content when logged in: `var(--body-container-radius)`. What do you think?

2023-05-11 16:12 UTC, susnux commented
> I’d actually say we could use an even larger border-radius for the login box as well – the same as for the content when logged in: `var(--body-container-radius)`. What do you think?

@jancborchardt 
I intended to make it consistent with the dashboard panels, which use `--border-radius-large`:
https://github.com/nextcloud/server/blob/9d2d3d482bce004d134dd87d7b37c3dfb6513412/apps/dashboard/src/DashboardApp.vue#L416

As the login box is more a panel than the main content box (?)

2023-05-11 16:43 UTC, jancborchardt commented
Right, that makes sense @susnux – considering that the Dashboard panels are older than the redesign though, I’d say it’s better to align with the redesign. :) Especially since the new added container around the footer looks rounder than the login form container otherwise.

And actually the dashboard panels also look better with the bigger border-radius (`var(--body-container-radius)` corresponds to 28px)

Login screen with bigger border radius | Dashboard panel with bigger border radius
-|-
![image](https://github.com/nextcloud/server/assets/925062/856744d7-f122-4045-8f35-9ba0f7c1eb98)|![image](https://github.com/nextcloud/server/assets/925062/cf6337e8-bd43-4da6-8501-499affc6ccc5)

2023-05-15 12:26 UTC, susnux commented on core/src/views/Login.vue
> +	min-width: 320px;
Yes, seems to work fine, even on quite low resoultion (350px width) it looks ok.

For example the login page on 350px:
English (medium size text) | Portuguese (long text)
---|---
![image](https://github.com/nextcloud/server/assets/1855448/27d14e2d-2786-407a-b0a0-41096bf6e9ec)|![image](https://github.com/nextcloud/server/assets/1855448/3f0c7f2c-f3f2-40d1-b0cf-857dc5cdd338)

2023-05-15 13:28 UTC, szaimen requested changes
I just tested this and it needs a fix for mobile:

![image](https://github.com/nextcloud/server/assets/42591237/b12516bd-238b-47ff-ab80-3a547a4b16c9)

2023-05-15 13:29 UTC, szaimen commented on core/src/views/Login.vue
> +	min-width: 320px;
As you can see is this overlapping on the left and right but fine by me...

2023-05-15 14:03 UTC, susnux commented
@szaimen yes, cache issue... Happens because that css variable is set to `0px` for mobile view. Fixed it.

2023-05-15 14:03 UTC, susnux commented on core/src/views/Login.vue
> +	min-width: 320px;
Fixed for mobile

2023-05-15 14:11 UTC, szaimen approved these changes
Tested and seems to work now but didnt review the code

2023-05-15 16:32 UTC, jancborchardt approved these changes
Seems good to me! And now looks very nice with the 2 similar roundings. :) Nice job @susnux

2023-05-16 21:36 UTC, szaimen commented
CI failure unrelated

2023-05-16 21:36 UTC, merged