Support Circles
nextcloud/server pull request #3813
Opened 2017-03-12 21:21 UTC by daita

This PR will add support to a non-admin group shares.

It includes:
- call to the Circles Sharees API to search for Circles when the user want to share a file/folder.
- call to the Circles Share Provider when browsing files (as file owner and as shared user) and editing rights/permissions.

WARNING: There is a known bug with the resharing of the content of a Circle. This need to be fixed !

Note: I know, I haven't signed any push ...

2017-03-12 21:33 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +//		if (\OCP\App::isEnabled('circles')) {
Remove it 😉

2017-03-12 21:34 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		if (array_key_exists('circles', $result['exact'])) $this->result['exact']['circles'] = $result['exact']['circles'];
Always use `{` and `}` for `if` and a new line for the stuff inside of the block

2017-03-12 21:36 UTC, MorrisJobke commented on apps/files_sharing/tests/js/sharedbreadcrumviewSpec.js
> +		it('Render shared if dir is shared by link', function() {
`... is shared by circle`

2017-03-12 21:37 UTC, MorrisJobke commented
> Note: I know, I haven't signed any push ...

Just squash all of those commits into one and sign it then 😉

2017-03-12 22:12 UTC, daita commented
@MorrisJobke I fixed the code style

2017-03-13 13:02 UTC, rullzer requested changes

2017-03-13 13:02 UTC, rullzer commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			$circle = \OCA\Circles\Api\Circles::detailsCircle($shareWith);
This will fail hard if the app is not installed... Of course then there probabaly won't be a circle share. But if the app gets disabled or so. It will most likely do :boom:

2017-03-13 13:02 UTC, rullzer commented on apps/files_sharing/lib/SharedStorage.php
> +		$this->init();
@icewind1991 please comment.

2017-03-13 14:46 UTC, icewind1991 commented on apps/files_sharing/lib/SharedStorage.php
> +		$this->init();
👎 will have a massive impact on performance

2017-03-13 16:22 UTC, daita commented on apps/files_sharing/lib/SharedStorage.php
> +		$this->init();
even with the check on the value ?
> if ($this->initialized) { } 

The issue I had (if I remember well) is that superStorage was null

2017-03-13 16:30 UTC, daita commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			$circle = \OCA\Circles\Api\Circles::detailsCircle($shareWith);
it is in createShare, so I doubt anyone could create a share to a Circle if the app is not enabled, but I will add a condition on `(\OCP\App::isEnabled('circles'))`

2017-03-14 11:43 UTC, daita commented
@MorrisJobke @rullzer @icewind1991  Fixed the few stuff you were asking

2017-03-17 05:21 UTC, MorrisJobke commented
> Note: I know, I haven't signed any push ...

Squash all commits, sign off this commit and then I would say this can get in :)

2017-03-17 05:21 UTC, MorrisJobke approved these changes

2017-03-17 20:46 UTC, MorrisJobke commented
Let's continue in #3906 - next time just force push to the same branch to overwrite the github version and update the GitHub PR 😉

2017-03-17 20:46 UTC, closed without merging