Admin audit app: optimization according to PHP 8
nextcloud/server pull request #38176
Opened 2023-05-10 11:37 UTC by danialRahimy

## Summary

optimization according to PHP 8 in the admin audit app.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-10 12:04 UTC, tcitworld commented
It seems your branch has derived a lot from current `master`. Can you make things clean?

2023-05-10 12:44 UTC, danialRahimy commented
> It seems your branch has derived a lot from current `master`. Can you make things clean?

I did this.
Thanks.

2023-05-10 12:59 UTC, tcitworld commented on apps/admin_audit/lib/BackgroundJobs/Rotate.php
> +	public function __construct(ITimeFactory    $time,
**nitpick:** Remove the extra spaces
```suggestion
	public function __construct(ITimeFactory $time,
```

2023-05-10 12:59 UTC, tcitworld commented on apps/admin_audit/lib/Actions/Action.php
>  	}
**nitpick:** Remove the extra lines
```suggestion
	public function __construct(private IAuditLogger $logger) {}
```

2023-05-10 13:11 UTC, tcitworld commented on apps/admin_audit/lib/Actions/Action.php
>  	}
There is [a PHP-CS configuration ruleset](https://github.com/nextcloud/server/blob/master/.php-cs-fixer.dist.php). See https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#php

2023-07-03 07:24 UTC, tcitworld approved these changes

2023-07-03 07:58 UTC, danialRahimy commented
@tcitworld 

ChristophWurst removed reviewers, and according to the rules **At least 2 approving reviews are required by reviewers with write access.** What should I do?

2023-07-03 08:56 UTC, come-nc commented on apps/admin_audit/lib/Actions/Action.php
> +	public function __construct(private IAuditLogger $logger) {}
```suggestion
	public function __construct(
		private IAuditLogger $logger,
	) {}
```
This code style makes diff prettier and properties more obvious.

2023-07-03 08:56 UTC, come-nc commented on apps/admin_audit/lib/BackgroundJobs/Rotate.php
> +								private IConfig $config) {
```suggestion
			public function __construct(
				ITimeFactory $time,
				private IConfig $config,
			) {
```

2023-07-03 09:12 UTC, danialRahimy commented on apps/admin_audit/lib/Actions/Action.php
> +	public function __construct(private IAuditLogger $logger) {}
Thanks, in future Pull requests I'll use these code styles.

2023-07-03 09:22 UTC, danialRahimy commented on apps/admin_audit/lib/BackgroundJobs/Rotate.php
> +								private IConfig $config) {
Thanks, in future Pull requests I'll use these code styles.

2023-07-05 08:43 UTC, ChristophWurst requested changes

2023-07-05 08:43 UTC, ChristophWurst commented on apps/admin_audit/lib/BackgroundJobs/Rotate.php
>  	public function __construct(ITimeFactory $time,
```suggestion
```

2023-07-05 09:42 UTC, danialRahimy commented on apps/admin_audit/lib/BackgroundJobs/Rotate.php
>  	public function __construct(ITimeFactory $time,
These changes are already done.

2023-07-05 09:55 UTC, blizzz approved these changes

2023-07-05 09:59 UTC, ChristophWurst approved these changes
Please squash your commits into one

2023-07-05 11:26 UTC, danialRahimy commented
> Please squash your commits into one

I committed my changes on the master, and I pull the master after my first commit and so I can't squash all of my commits into one. I just squash two last ones.

2023-07-05 12:17 UTC, ChristophWurst commented
Squashed the commits for you

2023-07-05 13:53 UTC, merged