Update icewind/streams to 0.7.7, and remove it from explicit deps in files_external
nextcloud/server pull request #38195
Opened 2023-05-11 10:07 UTC by come-nc

## Summary

Solves psalm issues about return types in files_external.
A bit weird that we have icewind/streams is two places but it’s a dependency of icewind/smb which is only pulled in files_external, so not sure this is fixable.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-11 12:47 UTC, icewind1991 requested changes

2023-05-11 12:47 UTC, icewind1991 commented on apps/files_external/3rdparty/composer.json
> -		"icewind/streams": "0.7.4",
iirc. the explicit requirement was added to ensure that both copies of the library are at the same version so that no matter which of the copies wins the autoload race we get the same code.

2023-05-11 13:39 UTC, provokateurin approved these changes

2023-05-12 16:40 UTC, icewind1991 approved these changes

2023-05-15 07:12 UTC, merged