Update CODEOWNERS
nextcloud/server pull request #38200
Opened 2023-05-11 13:09 UTC by bigcat88

task from @DaphneMuller

2023-05-11 13:14 UTC, bigcat88 commented
Probably someone should add write access to this repo for
https://github.com/orgs/nextcloud/teams

I do not know how to do that(

2023-05-11 13:16 UTC, nickvergessen requested changes
As per discussion the CODEOWNER should be mapped to the `/appinfo/info.xml` for the apps.
Whether or not the owners fully subscribe to the apps path is up to them

2023-05-11 13:16 UTC, nickvergessen commented on .github/CODEOWNERS
> +/apps/files                         @nextcloud/files
> This CODEOWNERS file contains errors …

Groups do not work

2023-05-11 13:16 UTC, nickvergessen commented on .github/CODEOWNERS
> +/apps/twofactor_backupcodes         @st3iny @miaulalala @Pytal
this is duplicated in line 33 with another user list.

2023-05-11 13:39 UTC, bigcat88 commented on .github/CODEOWNERS
> +/apps/files                         @nextcloud/files
replaced with group members

2023-05-11 13:39 UTC, DaphneMuller commented
hey @nickvergessen , shall we have a chat about it 1:1? I tasked Alexander with this. The idea is that community PR's get assigned faster to the right people. I don't see why what Alexander did is a problem for you, maybe you can rephrase or explain me?

2023-05-11 14:10 UTC, ChristophWurst commented
For transparency please keep the discussion here

2023-05-11 14:39 UTC, ChristophWurst requested changes
@ChristophWurst vs @Pytal

2023-05-11 14:39 UTC, ChristophWurst commented on .github/CODEOWNERS
> +/apps/files/appinfo/info.xml                  @skjnldsv @ChristophWurst @ArtificialOwl @come-nc @artonge @icewind1991 @szaimen @susnux @Fenn-CS
```suggestion
/apps/files/appinfo/info.xml                  @skjnldsv @Pytal @ArtificialOwl @come-nc @artonge @icewind1991 @szaimen @susnux @Fenn-CS
```

2023-05-11 14:39 UTC, ChristophWurst commented on .github/CODEOWNERS
> +/apps/updatenotification/appinfo/info.xml     @ChristophWurst @JuliaKirschenheuter
```suggestion
/apps/updatenotification/appinfo/info.xml     @Pytal @JuliaKirschenheuter
```

2023-05-11 14:43 UTC, ChristophWurst commented on .github/CODEOWNERS
> -*/TwoFactorAuth/*                  @ChristophWurst @miaulalala @nickvergessen
I intentionally set myself as owner of this path pattern. Please leave this in place

2023-05-11 16:40 UTC, bigcat88 commented on .github/CODEOWNERS
> -*/TwoFactorAuth/*                  @ChristophWurst @miaulalala @nickvergessen
so we can mark this as resolved?

2023-05-11 17:08 UTC, Pytal commented on .github/CODEOWNERS
> +/apps/files                         @nextcloud/files
Teams should work according to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file?

2023-05-12 07:48 UTC, nickvergessen commented on .github/CODEOWNERS
> +/apps/twofactor_backupcodes/appinfo/info.xml  @st3iny @miaulalala @ChristophWurst
```suggestion
/apps/twofactor_backupcodes/appinfo/info.xml  @st3iny @miaulalala @ChristophWurst
/apps/twofactor_backupcodes                   @ChristophWurst @miaulalala @nickvergessen
```

2023-05-12 08:59 UTC, nickvergessen approved these changes
Reordered the groups and added "section headlines"

2023-05-12 09:59 UTC, ChristophWurst requested changes
Only checked my own responsibilities but not any other mapping of gmbh employees to this code owners file

2023-05-12 10:12 UTC, ChristophWurst approved these changes
Please squash

Looks ok but didn't check every owner in detail

2023-05-12 10:38 UTC, nickvergessen commented
> Please squash

Or we save the precious CI time since 5 jobs finished already.

2023-05-12 11:01 UTC, ChristophWurst commented
Reabse with skipci

2023-05-12 11:20 UTC, bigcat88 commented
> Reabse with skipci

should I create a new PR with these changes and [skip ci] or someone else will do it?

2023-05-12 11:36 UTC, merged