create correct VCard and return correct error codes
nextcloud/server pull request #3825
Opened 2017-03-13 13:49 UTC by schiessle

- fix vcard creation to avoid having multiple "uids"
- fix controller middleware to only process related exceptions

2017-03-15 15:47 UTC, nickvergessen commented
Looks good, but are there any docs for the last commit? the change looks odd?!

2017-03-15 16:41 UTC, rullzer requested changes

2017-03-15 16:41 UTC, rullzer commented on apps/dav/lib/CardDAV/Converter.php
> +							$vCard->add('PHOTO', $image->data(), ['ENCODING' => 'b', 'TYPE' => $image->mimeType()]);
No when vcards hold binary data bad things happen

2017-03-16 09:09 UTC, schiessle commented on apps/dav/lib/CardDAV/Converter.php
> +							$vCard->add('PHOTO', $image->data(), ['ENCODING' => 'b', 'TYPE' => $image->mimeType()]);
sabreDAV encodes it as base64 automatically, check the result in the db after running: `sudo -u www-data ./occ dav:sync-system-addressbook`

Also see the corresponding tests which check for base64 encoded representation and not for binary data:  https://github.com/nextcloud/server/pull/3825/files#diff-4a7b91a5b6e2e8b8735b9e8c5603fcdbR149

2017-03-16 09:50 UTC, rullzer commented on apps/dav/lib/CardDAV/Converter.php
> +							$vCard->add('PHOTO', $image->data(), ['ENCODING' => 'b', 'TYPE' => $image->mimeType()]);
Aaah my bad. I was under the impression we were doing vcard v4. :+1:

2017-03-16 09:50 UTC, rullzer approved these changes

2017-03-23 13:44 UTC, nickvergessen commented
Tested and works with self signed certs now after my last fix.

2017-03-23 13:44 UTC, nickvergessen approved these changes

2017-03-23 14:08 UTC, LukasReschke requested changes
Also: "Your test case is not allowed to access the database." :)

2017-03-23 14:08 UTC, LukasReschke commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
![create](https://cloud.githubusercontent.com/assets/878997/24251472/89b879c6-0fda-11e7-986d-49e31c3bf5de.jpeg)

2017-03-23 17:34 UTC, nickvergessen commented on apps/dav/lib/CardDAV/SyncService.php
> +	protected function getCertPath() {
Since this is get, return it with this method?

2017-03-24 13:33 UTC, merged

2017-03-24 13:40 UTC, schiessle commented
stable11: https://github.com/nextcloud/server/pull/4029