fix(caldav): Catch invalid events for reminder generation
nextcloud/server pull request #38301
Opened 2023-05-16 08:58 UTC by ChristophWurst

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-16 12:20 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +				$masterHash = $this->getEventHash($recurrenceException);
**nitpick:** 
```suggestion
				$masterHash = $this->getEventHash($masterItem);
```

2023-05-16 12:20 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			} catch (Throwable $e) {
**question:** Which exceptions do you except to be sent here? From what I can see serializing properties, using `implode` and `md5` shouldn't throw anything.

2023-05-17 14:14 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			} catch (Throwable $e) {
``Call to a member function serialize() on null at apps/dav/lib/CalDAV/Reminder/ReminderService.php:261``

Added it to the PR description too. We saw this on a production instance, during the upgrade from an old version. Apparently there can be events without a DTSTART.

2023-05-30 19:27 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			} catch (Throwable $e) {
Do you have any ideas for a better place to catch this? We might be able to skip invalid events all together for the reminder processing.

2023-05-31 06:57 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			} catch (Throwable $e) {
Not catching, but we can simply validate events in `getAllVEventsFromVCalendar`.

Something like:
```php
if (!$child->DTSTART) {
  continue
}
```

2023-05-31 09:55 UTC, tcitworld requested changes

2023-05-31 09:55 UTC, tcitworld commented on apps/dav/tests/unit/CalDAV/Reminder/ReminderServiceTest.php
> +		$this->backend->expects($this->exactly(2))
**question:** Shouldn't the method never be called?

2023-05-31 12:35 UTC, tcitworld approved these changes

2023-05-31 17:11 UTC, ChristophWurst commented
/backport to stable27

2023-05-31 17:11 UTC, ChristophWurst commented
/backport to stable26

2023-05-31 17:11 UTC, ChristophWurst commented
/backport to stable25

2023-05-31 18:18 UTC, kesselb approved these changes

2023-05-31 18:23 UTC, hamza221 approved these changes

2023-06-01 09:37 UTC, merged

2023-06-01 11:42 UTC, ChristophWurst commented
/backport to stable25

2023-06-01 11:42 UTC, ChristophWurst commented
the backport worked locally