weather_status: Improve contrast of favorite icon
nextcloud/server pull request #38333
Opened 2023-05-17 02:34 UTC by susnux

* Resolves: #36969

## Summary
Do not use a yellow icon but the default colored one and use the `StarOff` icon for removing a favorite instead of using `StarOutline`.

This also adds a feature: The current selected favorite is highlighted by setting the icon color to the primary color.

## screenshots
before | after
---|---
![image](https://github.com/nextcloud/server/assets/1855448/cff14d07-9a0b-43b3-9f33-e8aff87f4027)|![image](https://github.com/nextcloud/server/assets/1855448/c774f392-2f69-451f-a7af-44d8bc939361)
![image](https://github.com/nextcloud/server/assets/1855448/98b07670-1ac6-468b-b896-4a5dcb1affe6)|![image](https://github.com/nextcloud/server/assets/1855448/2deaa765-7474-4ff4-b6db-a21d8ed023d9)
![image](https://github.com/nextcloud/server/assets/1855448/28fb87db-fa88-4628-a533-448b11f324a9)|![image](https://github.com/nextcloud/server/assets/1855448/9ea1ba7e-8a86-452e-8a3f-ae38a70bfd19)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes

2023-05-17 09:57 UTC, szaimen commented
@nimishavijay @jancborchardt I think we need to think here how to properly display the current state: enabled <-> disabled

2023-05-17 13:19 UTC, susnux commented
> @nimishavijay @jancborchardt I think we need to think here how to properly display the current state: enabled <-> disabled

Yes, mainly we should  decide whether we want to keep the yellow star or not, because we have the same problem on the files list (yellow star on white background => too low contrast).

2023-05-17 21:58 UTC, jancborchardt requested changes
StarOff looks strange, cause it looks as if a click on it would remove the star.

Instead we should use the "non-filled" star icon for the state when it's not a favorite, that is more common.

Regarding color, just dark is fine, or do we find maybe a dark yellow/gold that still looks like a star color? In dark mode it can/must of course be light yellow.

2023-05-17 22:26 UTC, susnux commented
> do we find maybe a dark yellow/gold that still looks like a star color

@jancborchardt yellow will not work on white background, but dark golden at least fulfills the AA criteria. Will look like this:
![image](https://github.com/nextcloud/server/assets/1855448/4e54ce15-f738-4ffb-86a6-5d211d3c4cd4)
![image](https://github.com/nextcloud/server/assets/1855448/111034c9-c81b-4dfe-9c16-6a269d75175c)

Do you think this looks better than the default color?

2023-05-18 09:36 UTC, jancborchardt commented
@susnux yep, I would say that dark gold is good! It at least conveys a little bit of a star color, otherwise favorite gets lost in the sea of other functions.

(Different issue, but we should probably also make sure that the "Delete" icon in all the action menus is colored accordingly – also something for the Penpot library @nimishavijay )

2023-05-18 09:38 UTC, jancborchardt approved these changes

2023-05-18 18:44 UTC, Pytal approved these changes

2023-05-18 18:44 UTC, Pytal commented on apps/weather_status/src/App.vue
> +	//color: var(--color-primary-element)!important;
```suggestion
```

2023-05-19 17:12 UTC, susnux commented
I had to adjust the color slightly to `#a08b00` to guarantee the contrast even when hovered.

2023-05-20 19:21 UTC, Fenn-CS approved these changes

2023-05-25 23:11 UTC, szaimen commented
Conflicts

2023-05-26 12:15 UTC, susnux commented
> Conflicts

Resolved

2023-05-26 13:25 UTC, merged