fix(carddav): Check enumeration settings for all SAB methods
nextcloud/server pull request #38423
Opened 2023-05-23 15:53 UTC by ChristophWurst

## Summary

The system address book has to repsect sharing enumeration settings in all code paths.

## TODO

- [x] Fix checks

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-05-23 17:12 UTC, ChristophWurst commented on apps/dav/lib/CardDAV/SystemAddressbook.php
> +		if ($user->getBackendClassName() === 'Guests' || !$shareEnumeration || !$shareEnumerationGroup && $shareEnumerationPhone) {
todo: remove. this is unrelated

2023-05-24 17:13 UTC, ChristophWurst commented
/backport to stable27

2023-05-24 19:40 UTC, nickvergessen requested changes

2023-05-24 19:40 UTC, nickvergessen commented on apps/dav/lib/CardDAV/SystemAddressbook.php
> +		if (!$shareEnumeration || !($shareEnumerationGroup && $shareEnumerationPhone)) {
Below function has
```suggestion
		if (!$shareEnumeration || (!$shareEnumerationGroup && $shareEnumerationPhone)) {
```

And it looks more sane/compatible with previous behaviour?

2023-05-24 20:53 UTC, nickvergessen approved these changes

2023-05-24 20:57 UTC, AndyScherzinger approved these changes

2023-05-25 07:48 UTC, JohannesGGE approved these changes
tested the group restriction. Works :100:

2023-05-25 08:15 UTC, merged