feat: add width and height to BeforePreviewFetchedEvent
nextcloud/server pull request #38679
Opened 2023-06-06 21:30 UTC by kesselb

## Summary

user_usage_report keeps a counter for files read.[^1]

The app uses

- OC_Filesystem::read hook
- Event listener (the legacy one) for IPreview::EVENT

Request for previews do not trigger the hook, hence the additional event listener. 
The thumbnails for a list or grid view should not count, so we need the width and height.

[^1]: https://github.com/nextcloud/user_usage_report/blob/c12e97d84033818af27ae5cf659c88f743137be7/lib/AppInfo/Application.php#L51

## TODO

- [ ] CI

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-06-07 11:16 UTC, ChristophWurst requested changes

2023-06-07 11:16 UTC, ChristophWurst commented on lib/public/Preview/BeforePreviewFetchedEvent.php
> +		private int $height) {
The two new required constructor arguments form a breaking change for apps creating an instance, e.g. to dispatch their own event.

Can we assume that apps don't do that? Then the change could be ok.

Otherwise I would prefer to make the two new properties optional and nullable, document that in three versions (nextcloud 31) the arguments are required and only then make them non-null.

2023-06-09 16:36 UTC, tcitworld commented
Would you mind adding more details while we're at it? What I added in https://github.com/nextcloud/server/pull/37193 for admin_audit (`crop`, `mode` and `mimetype`).

2023-06-12 09:48 UTC, kesselb commented
@tcitworld added crop and mode.

2023-06-19 19:01 UTC, ChristophWurst approved these changes

2023-06-20 06:45 UTC, tcitworld approved these changes

2023-06-23 06:32 UTC, tcitworld approved these changes

2023-06-23 06:35 UTC, ChristophWurst approved these changes

2023-06-23 06:36 UTC, ChristophWurst commented on lib/public/Preview/BeforePreviewFetchedEvent.php
> +		private int $width = 0,
I wonder if it's better to have wrong data (0x0px image) or null values when the emitter doesn't pass values

2023-06-23 12:53 UTC, kesselb commented on lib/public/Preview/BeforePreviewFetchedEvent.php
> +		private int $width = 0,
True True

2023-06-23 13:19 UTC, ChristophWurst approved these changes

2023-06-23 13:23 UTC, ChristophWurst approved these changes
Psalm sugar

2023-06-23 13:23 UTC, ChristophWurst commented on lib/public/Preview/BeforePreviewFetchedEvent.php
> +	public function getMode(): ?string {
```suggestion
	/**
	 * @since 28.0.0
	 * @return null|IPreview::MODE_*
	 */
	public function getMode(): ?string {
```

2023-06-23 13:23 UTC, ChristophWurst commented on lib/public/Preview/BeforePreviewFetchedEvent.php
>  	 */
```suggestion
	 * @param string|IPreview::MODE_*
	 */
```

2023-06-23 14:28 UTC, kesselb commented on lib/public/Preview/BeforePreviewFetchedEvent.php
>  	 */
Good idea

2023-06-26 10:15 UTC, st3iny approved these changes

2023-06-26 11:53 UTC, kesselb commented
Documentation: https://github.com/nextcloud/documentation/pull/10674

2023-06-26 11:53 UTC, merged