Verify personal data
nextcloud/server pull request #3869
Opened 2017-03-16 14:07 UTC by schiessle

Allow users to verify their email address, twitter account and webpage for the lookup server

2017-03-16 20:50 UTC, MorrisJobke commented on apps/lookup_server_connector/appinfo/app.php
> +	$lookupServer = $config->getSystemValue('lookup_server', '');
No default value?

2017-03-16 20:51 UTC, MorrisJobke commented on config/config.sample.php
> +'lookup_server' => 'https://lookup.nextcloud.com/users',
I guess the `/users` needs to be removed here.

2017-03-16 20:51 UTC, MorrisJobke commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +	private $lookupServer = 'https://lookup.nextcloud.com';
Use the default while fetching from the config instead.

2017-03-17 12:12 UTC, nickvergessen commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +								$lookupServer = '') {
👎

2017-03-20 12:48 UTC, schiessle commented on config/config.sample.php
> +'lookup_server' => 'https://lookup.nextcloud.com/users',
no, that's how our current lookup server is configured. That's also how it is in stable11

2017-03-20 13:11 UTC, schiessle commented on apps/lookup_server_connector/appinfo/app.php
> +	$lookupServer = $config->getSystemValue('lookup_server', '');
The default value is that nothing is configured and than the lookup connector will fall back to the default URL.

2017-03-20 13:12 UTC, schiessle commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +	private $lookupServer = 'https://lookup.nextcloud.com';
I prefer to have one place where the default defined in one place instead of spread around in multiple places. This makes it much easier to change it if necessary.

2017-03-20 13:14 UTC, schiessle commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +								$lookupServer = '') {
Related to: https://github.com/nextcloud/server/pull/3869#discussion_r106896494
In most cases people will just use the default value. People who use this class shouldn't have to think about it or even know the default server.

2017-03-20 13:15 UTC, schiessle commented
Thanks for the early review. But keep in mind that most code will probably change before it is ready to review. That's a early development branch.

2017-04-06 14:11 UTC, schiessle commented
@jancborchardt please don't forget the icons we discussed during the hackweek.... Thanks!

2017-04-06 16:52 UTC, MorrisJobke commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +	private $lookupServer = 'https://lookup.nextcloud.com';
The problem I see with this approach: How to set "no lookup server"?

2017-04-07 08:44 UTC, schiessle commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +	private $lookupServer = 'https://lookup.nextcloud.com';
there is always one configured lookup server. That's also the case for Nc11. You can disable the whole functionality in the admin settings, no need to play around with config.php variables.

2017-04-07 17:51 UTC, MorrisJobke commented
@jancborchardt Please fix the layout:

<img width="574" alt="bildschirmfoto 2017-04-07 um 12 51 21" src="https://cloud.githubusercontent.com/assets/245432/24812739/f1cbb30e-1b90-11e7-8489-5534c9477e74.png">

2017-04-10 13:00 UTC, schiessle commented
@MorrisJobke for now the text label are just there to allow me to work on the actual functionality, I didn't put a lot of energy in getting the layout right (although I have to say that it looks better on my screen 😉 ).

Still waiting for some nice icons by @jancborchardt. Bonus points for Jan if he adds them directly to this branch with the right layout 😉

2017-04-18 21:12 UTC, MorrisJobke commented
@jancborchardt Please have a look at this or this will not land in 12.

2017-04-23 02:44 UTC, jancborchardt commented
Sorry, have been drowning in notifications – will check it out.

2017-04-24 09:25 UTC, schiessle commented
@jancborchardt Thanks. As discussed we need three icons:

* not verified
* verification in progress
* verified

2017-04-24 10:25 UTC, schiessle commented
@jancborchardt I just pushed the last changes for the code. The strings "verification in progress", "verified", "click to verify" here https://github.com/nextcloud/server/pull/3869/commits/24e1395964f51a83698d970c74534f91993c0f9f#diff-e999cb367e8eac4edfd688b687c55730L114 need to be replaced with nice looking icons. Maybe it make sense to keep the strings as a tooltip.

Email has the status "verification in progress" and "verifed" only and is not clickable because email verification doesn't need any additional user interaction. The lookup server send automatically a verification mail if you set an new email address and we check in the background if the verification was completed.

2017-04-25 13:40 UTC, jancborchardt commented
@schiessle what do you think about these icons:
![verification](https://cloud.githubusercontent.com/assets/925062/25388149/45fe8dd0-29cd-11e7-9bed-f1e2567a4e0c.png)
1. Click to verify
2. Verification in progress
3. Verified
4. and 5: Error state – which one do you prefer?

2017-04-25 15:33 UTC, schiessle commented
@jancborchardt looks nice. I'm not sure if we need a error state. My plan was to just go back from "verify in progress" to "not verified" and then the user can start again. Can you commit the icons? Thanks!

2017-04-25 16:05 UTC, jancborchardt commented
@schiessle I added the icons and also would say we simplify the wording to:
- Verify (cause »click« isn’t on mobile ;)
- Verifying …
- Verified

Can you make all the changes for that, let me know, and then I fix the last layout issues?

2017-04-26 08:04 UTC, schiessle commented
@jancborchardt verification buttons are in and they look really nice! 😃 

Can you have a look at the layout, there are still some glitches on different window sizes. Thanks!

2017-04-26 08:39 UTC, nickvergessen commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$lookupServerUrl = $this->config->getSystemValue('lookup_server', 'https://lookup.nextcloud.com');
Please `rtrim('/')` because people will mostlikely add a trailing slash, which might or might not cause problems...

2017-04-26 08:41 UTC, nickvergessen commented on lib/private/Accounts/AccountManager.php
> +					'verified' => '0',
constant?

2017-04-26 08:46 UTC, nickvergessen requested changes

2017-04-26 08:46 UTC, nickvergessen commented on settings/BackgroundJobs/VerifyUserData.php
> +		$this->logger = $logger !== null ? $logger : \OC::$server->getLogger();
kill all this, DI for background jobs is working fine nowerdays

2017-04-26 08:46 UTC, nickvergessen commented on settings/BackgroundJobs/VerifyUserData.php
> +			$this->lookupServerUrl = $config->getSystemValue('lookup_server', 'https://lookup.nextcloud.com');
rtrim

2017-04-26 08:46 UTC, nickvergessen commented on settings/BackgroundJobs/VerifyUserData.php
> +			$this->lookupServerUrl = \OC::$server->getConfig()->getSystemValue('lookup_server', 'https://lookup.nextcloud.com');
only use the DI way

2017-04-26 08:46 UTC, nickvergessen commented on settings/templates/personal.php
> +		<p>It can take up to 24 hours before the account is displayed as verified.</p>
missing translation same in the 3 lines above

2017-04-26 08:46 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verify.svg') . '" title="Verify"');
title not translated, same above

2017-04-26 08:46 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verifying.svg') . '" title="Verifying..."');
Use `…` and translation

2017-04-26 08:46 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verifying.svg') . '" title="Verifying..."');
... + t

2017-04-26 09:56 UTC, jancborchardt commented
@schiessle are you going to rebase before? Then I’ll wait with checking the layout

2017-04-26 10:55 UTC, schiessle commented
@jancborchardt rebased, please have a look. Thanks.

2017-04-26 11:31 UTC, jancborchardt commented
Fixed the layout to use the `.popovermenu` as we do for the file actions and the federationScopeMenu too. Here’s a mockup how it will look like when shown via .removeClass('hidden') and positioned with top/right which needs to be done via JS:
![capture du 2017-04-26 13-19-15](https://cloud.githubusercontent.com/assets/925062/25432355/68cfb278-2a84-11e7-9966-1b1073595328.png)

@schiessle can you adjust the code to use a `class="verification-dialog"` instead of the ID, and like with the federationScopeMenu I think we need to place the dialog directly next to each verification icon.
Basically it should work like we already did in the federationScopeMenu.

2017-04-26 11:51 UTC, schiessle commented
@nickvergessen all your comments are addressed, please have a final look code wise

2017-04-26 11:53 UTC, schiessle commented
@jancborchardt while your mockup looks great I'm not sure how to make this happen, especially in the remaining few hours. Maybe @ChristophWurst or @rullzer could have a look? I think you also created the other popover menus.

2017-04-26 11:54 UTC, schiessle commented on settings/templates/personal.php
> +		<p>It can take up to 24 hours before the account is displayed as verified.</p>
added it for the "It can take up to 24 hours...", the other two strings are just placeholder and will never be shown to the user

2017-04-26 12:09 UTC, schiessle commented on settings/css/settings.css
>  #personal-settings-container .verify-action {
@jancborchardt  that's wrong. Only "verify-action" should have a pointer in mouse over. Email verification doesn't has a popover and therefore never should show a mouse pointer. I will fix it. Just want to make sure that we don't change it back and forth. 😉

2017-04-26 12:17 UTC, jancborchardt commented
Ok so I switched the code to use individual popovers instead of one main one:
![capture du 2017-04-26 14-14-21](https://cloud.githubusercontent.com/assets/925062/25433984/d14064e6-2a8a-11e7-9ff7-2fa4e135013e.png)

All the styling works out of the box. The only changes we need to make:
- [ ] Switch the JS to use the class '.verification-dialog` which is an element right inside the `<div class="verify">`
- [ ] Check if it correctly closes again on clicking outside and opening other menus also, as menus should

cc @nextcloud/javascript

2017-04-26 12:43 UTC, blizzz commented on apps/lookup_server_connector/lib/UpdateLookupServer.php
> +	private $lookupServer = 'https://lookup.nextcloud.com';
you can still have the default server stored in a const, if you need it in several places, and use it as default parameter. It's a more intuitive and especially consistent.

2017-04-26 15:04 UTC, jancborchardt commented on settings/js/personal.js
> +			var dialog = $(this).closest('.verify').children('.verification-dialog');
Maybe this can also be simplified since `.verification-dialog` is the element directly after the `.verify-action` element which this click handler is bound to.

Any idea @nextcloud/javascript @MorrisJobke @ChristophWurst?

2017-04-26 16:40 UTC, jancborchardt commented
@schiessle I would also show the verification button for fields when they are not public yet. Verification is always good.

2017-04-26 17:12 UTC, jancborchardt commented
@schiessle I made the verification icons also show for private fields (as said above) and fixed the width – please do not make it so wide, it’s just too huge to read and also doesn’t work well on mobile. ;) Now it’s right under the input field and looks nice.

Todo:

- [ ] The verification icon should show directly when there is a value put into the field. Currently done via PHP so it will be only visible after a hard refresh → bad. Any help @nextcloud/javascript?
- [ ] On mobile, the icon is a bit shifted. I’ll look into that.

2017-04-26 17:31 UTC, jancborchardt commented
@schiessle I will try to get some JS help to directly show the fields when something has been put into there. ;)

2017-04-26 18:29 UTC, schiessle commented
> I will try to get some JS help to directly show the fields when something has been put into there. ;)

Not needed, it is already done! 😃 

But I don't understand this commit: https://github.com/nextcloud/server/pull/3869/commits/47b203d7255e99a028e67c113bb46ab452cff447

It doesn't make any sense to ask the lookup server to verify your email address, twitter handle or webpage if the data is not published to the lookup server.

2017-04-26 18:35 UTC, schiessle commented
@jancborchardt please check the verification dialog for the website. There the signature is much longer because we don't have to deal with 140char limit. Not sure how to fit this into the popup

2017-04-26 19:47 UTC, jancborchardt commented
@nickvergessen are your concerns addressed? If so can you re-review? :)

2017-04-27 03:05 UTC, MorrisJobke commented
The feedback is very cumbersome. You click on the icon and nothing happens. Then after some while (when the request is back) the icon changes to the blue one and you need to click on it a second time to see the steps. Also those steps look really ugly:

<img width="626" alt="bildschirmfoto 2017-04-27 um 00 03 13" src="https://cloud.githubusercontent.com/assets/245432/25466171/1d1cdd3e-2add-11e7-9e1a-16aaa61e372b.png">

This need to be more straightforward. The UX currently is really bad :/ It took me a while to discover this even if I actively search for it.

2017-04-27 08:36 UTC, nickvergessen commented
For me the personal page is totally broken:
> ![nextcloud_-_2017-04-27_10 35 45](https://cloud.githubusercontent.com/assets/213943/25474933/520f8c6e-2b35-11e7-9e1c-36b0c99f8ff1.png)

2017-04-27 09:02 UTC, schiessle commented
@MorrisJobke don't know what happens on your system. Are you sure to have the latest version? For example the text overflow in your screenshot is fixed with https://github.com/nextcloud/server/pull/3869/commits/ea9c4b297d4d25bd5f4344630648bf3b2921a203 for me.

Also I don't understand the workflow you describe. I just need to click once, the popup shows up and the icon changes.

2017-04-27 09:11 UTC, schiessle commented
@nickvergessen no idea what's happening on your side. Can anyone reproduce this? I can't...

2017-04-27 09:25 UTC, nickvergessen requested changes

2017-04-27 09:25 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verifying.svg') . '" title="' . \OC::$server->getL10N()->t('Verifying…') . '"');
`p($l->t(` no need to get the class all the time again...

2017-04-27 09:25 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verifying.svg') . '" title="' . \OC::$server->getL10N()->t('Verifying…') . '"');
And thats for all templates

2017-04-27 09:41 UTC, nickvergessen commented
there have been invalid calls to getL10n without the appid, which broke it for me, because I have display_errors enabled...
Fixed with my last commit

2017-04-27 09:46 UTC, nickvergessen commented
### Steps
1. Enter a website
2. Make it public
3. Click on the verify thingy, copy the file name
4. Go to your filesystem and create the file
4. Click anywhere (simulating you went to filesystem and just clicked on your browser again)
5. The verify window is closed and you can not open it anymore, so you can not get the content of the file....

2017-04-27 09:54 UTC, schiessle commented
@nickvergessen I know... I'm already working on a solution

2017-04-27 09:55 UTC, nickvergessen submitted a review, later dismissed

2017-04-27 09:55 UTC, nickvergessen commented on settings/templates/personal.php
> +				print_unescaped(' title="' . $_['websiteMessage'] . '""');
double `""` at the end...
btw ` title="` could also be in the template directly, no need to wrap it with print_unescapced....
Also the message could then use `p(` to avoid problems with translations

2017-04-27 09:55 UTC, nickvergessen commented on settings/templates/personal.php
> +						print_unescaped('src="' . image_path('core', 'actions/verify.svg') . '"');
same here, move `src="` out of the php code and use `p(` for the image

2017-04-27 09:56 UTC, nickvergessen commented on settings/templates/personal.php
> +						<p><?php p(\OC::$server->getL10N('settings')->t('It can take up to 24 hours before the account is displayed as verified.'));?></p>
use `$l->t(` instead of creating a new instance of the lang

2017-04-27 09:56 UTC, nickvergessen commented on settings/templates/personal.php
> +						<p><?php p(\OC::$server->getL10N('settings')->t('It can take up to 24 hours before the account is displayed as verified.'));?></p>
use `$l->t(` instead of creating a new instance of the lang

2017-04-27 10:36 UTC, schiessle commented
@nickvergessen you should now be able to re-open the verification dialog

2017-04-27 15:24 UTC, LukasReschke commented on settings/BackgroundJobs/VerifyUserData.php
> +		$url = rtrim($argument['data'], '/') . '/well-known/' . 'CloudIdVerificationCode.txt';
As per the RFC that should be `.well-known`.

https://tools.ietf.org/html/rfc5785

2017-04-27 15:24 UTC, LukasReschke commented on settings/Controller/UsersController.php
> +				$msg = $this->l10n->t('In order to verify your Website store following content in your web-root at \'CloudIdVerificationCode.txt\' (please make sure that the complete text is in one line):');
Mhm. The code seems to check against `.well-known/CloudIdVerificationCode.txt` instead.

2017-04-27 15:54 UTC, schiessle commented on settings/Controller/UsersController.php
> +				$msg = $this->l10n->t('In order to verify your Website store following content in your web-root at \'CloudIdVerificationCode.txt\' (please make sure that the complete text is in one line):');
good catch, will update the text

2017-04-27 15:54 UTC, schiessle commented on settings/BackgroundJobs/VerifyUserData.php
> +		$url = rtrim($argument['data'], '/') . '/well-known/' . 'CloudIdVerificationCode.txt';
indeed, just a type... will fix

2017-04-27 15:59 UTC, schiessle commented
@LukasReschke issues fixed

2017-04-27 16:17 UTC, MorrisJobke commented
> Also I don't understand the workflow you describe. I just need to click once, the popup shows up and the icon changes.

Works now, but a loading indicator is still something I would like to see here. If your connection to the server is slow there is no feedback and later the popup appear magically.

2017-04-27 16:50 UTC, LukasReschke commented on settings/personal.php
> +			$message = $l->t('Verifying');
Shouldn't that be "verified"?

2017-04-27 18:24 UTC, jancborchardt commented
> Works now, but a loading indicator is still something I would like to see here. If your connection to the server is slow there is no feedback and later the popup appear magically.

Yes, the popup should open immediately. No reason to have that blocked by the server connection cause it’s just info in the popup which will take you time to do anyway.

2017-04-28 07:22 UTC, LukasReschke approved these changes
Good enough for me

2017-04-28 07:32 UTC, rullzer approved these changes
Fine by me for now. Lets do small fixes later!

2017-04-28 07:33 UTC, rullzer requested changes
But failing tests....

2017-04-28 09:07 UTC, schiessle commented
spinner can be added in the bugfixing / polishing phase. I will look at the failing tests

2017-04-28 09:23 UTC, schiessle commented
> Yes, the popup should open immediately. No reason to have that blocked by the server connection cause it’s just info in the popup which will take you time to do anyway.

it updates the account table which triggers a hook which again triggers a update send to the lookup server. At the moment we try once in real time to update the server and if it fails we create a cronjob to retry later. I will look into the possibility to add a spinner once the pr is merged

2017-04-29 02:42 UTC, MorrisJobke commented
I rebased to trigger CI - restarting is not possible for the jobs before the drone mess up. :/

2017-04-29 03:02 UTC, MorrisJobke approved these changes
Tested and works:+1:

2017-04-29 03:38 UTC, MorrisJobke commented
unit tests run fine -> merge

2017-04-29 03:38 UTC, merged