[stable27] Store encrypted OAuth2 client secrets
nextcloud/server pull request #38707
Opened 2023-06-08 12:20 UTC by julien-nc

Manual backport of #38398 and #38701

I kept the original migration version so it does not reflect the actual app version. Is it fine?

2023-06-09 08:59 UTC, szaimen approved these changes
🐘

2023-06-12 12:56 UTC, ChristophWurst requested changes
https://github.com/nextcloud/server/pull/38398#issuecomment-1587263501

2023-06-12 16:17 UTC, ChristophWurst approved these changes

2023-06-19 11:12 UTC, julien-nc commented
Failing Cypress tests are related with files_versions and theming.
https://github.com/nextcloud/server/actions/runs/5309936925/jobs/9611378026?pr=38707

2023-06-19 11:12 UTC, merged