Add a Dependabot configuration to autoupdate GitHub action versions
nextcloud/server pull request #38737
Opened 2023-06-10 20:07 UTC by kurtmckee

* Resolves: No issue filed

## Summary

GitHub workflow logs show that some of the actions are running on Node 12, which is deprecated and will be removed soon. [[example from a recent run](https://github.com/nextcloud/server/actions/runs/5231339838)]

This can be addressed by adding a Dependabot configuration for GitHub action versions. Therefore this PR targets a Dependabot configuration for ongoing updates, rather than updating the action versions as a one-off.

I've added sign-off signatures to my git commits. Please let me know if I overlooked anything that needs to be addressed.

Thanks for your work on NextCloud!

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-06-12 08:20 UTC, Fenn-CS requested changes
Thank you! This looks great according to official [GitHub notes.](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

One minor change request, can we just leave this as weekly? And leave the default `Once-a-week` timing for Github (Scheduled on Mondays?)

_Consideration: We could also make this monthly, I don't think actions change so fast._

2023-06-12 08:20 UTC, Fenn-CS commented on .github/dependabot.yml
> +    timezone: Europe/Paris
```suggestion
```

2023-06-12 11:01 UTC, kurtmckee commented on .github/dependabot.yml
> +    timezone: Europe/Paris
I don't have any preference at all, so I just want to confirm before signing off and committing your suggestion:

All other Dependabot updates are scheduled for "Saturdays at 3:00am Europe/Paris", so I simply copied that schedule. If I make this change, I think that it will introduce Dependebato PRs on a noticeably different schedule than the others.

Please confirm that's acceptable and intended, and I'll take your suggestion and add that new commit. 👍

2023-06-12 12:55 UTC, susnux approved these changes

2023-06-12 13:01 UTC, kurtmckee commented on .github/dependabot.yml
> +    timezone: Europe/Paris
@Fenn-CS Please let me know if this change is required, or if following the other Dependabot schedules in the file is acceptable.

I think you'll need to update your review to "Approve" for this to be eligible for merging.

2023-06-12 19:48 UTC, Fenn-CS commented on .github/dependabot.yml
> +    timezone: Europe/Paris
@kurtmckee Sorry for the delay! Too many notifications....

2023-06-12 19:48 UTC, Fenn-CS approved these changes
Thank you!

2023-06-12 19:49 UTC, Fenn-CS commented
We would then wait for CI to get green :)

2023-06-12 19:58 UTC, kurtmckee commented
Thanks, @Fenn-CS! I want CI to go green, too.

It appears the failures are unrelated to this change, however, and that many recent commits to the default git branch have failed for varying reasons. Would it be an option to re-run the failed CI jobs to see if they clear up on a second run?

2023-06-12 20:00 UTC, Fenn-CS commented
You could rerun, but usually I just wait when I know it's unrelated.

It would magically become green if it can :)

2023-06-12 20:04 UTC, kurtmckee commented
I'm not able to independently re-run the failed jobs. Is that something you're able to re-run?

2023-06-12 22:05 UTC, szaimen commented
CI failure unrelated

2023-06-12 22:05 UTC, merged

2024-02-21 12:09 UTC, Fenn-CS commented
@skjnldsv Not a big deal, so if we are having too many depenabot pr's to review that no one has time to look at, it makes sense to revert.

2024-02-21 12:12 UTC, Fenn-CS commented
>     The update cadence seems aggressive; it could be tuned to "monthly" instead of "weekly"

I am also fine with this.

2024-02-21 13:07 UTC, kurtmckee commented
Dependabot supports batched updates. [Here's an example PR] from one of my repositories, with all available GitHub actions updates rolled into a single PR.

2024-02-21 16:20 UTC, skjnldsv commented
> The update cadence seems aggressive; it could be tuned to "monthly" instead of "weekly"

good for me too