Uses PHP8's constructor property promotion in core/Command and /
nextcloud/server pull request #38775
Opened 2023-06-12 15:52 UTC by fsamapoor

Following https://github.com/nextcloud/server/pull/38636, https://github.com/nextcloud/server/pull/38637, and https://github.com/nextcloud/server/pull/38638 PRs, I have made the required adjustments to the `/core/Command/` namespace as well.

I figured I should split the changes into multiple PRs to make reviewing the changes easier.

This PR refactors `/core/Command` and `/core/Command/TwoFactorAuth` classes by using PHP8's constructor property promotion to remove redundant lines and make the code cleaner.

2023-06-13 07:18 UTC, come-nc requested changes

2023-06-13 07:18 UTC, come-nc commented on core/Command/TwoFactorAuth/Disable.php
> +		protected IUserManager $userManager,
This is defined in Base class already.
The way this is currently done is really ugly, so a refactor is needed.
A constructor needs to be added in Base which takes `$userManager` as parameter.

2023-06-20 07:33 UTC, artonge commented on core/Command/TwoFactorAuth/Disable.php
> +		protected IUserManager $userManager,
@fsamapoor can you address the comment?

2023-06-20 11:54 UTC, fsamapoor commented on core/Command/TwoFactorAuth/Disable.php
> +		protected IUserManager $userManager,
@come-nc Sorry about the delayed changes. I hope I did it right.

2023-06-20 12:46 UTC, artonge approved these changes

2023-06-20 13:32 UTC, come-nc requested changes

2023-06-20 13:32 UTC, come-nc commented on core/Command/TwoFactorAuth/Cleanup.php
> +		protected IUserManager $userManager,
```suggestion
		IUserManager $userManager,
```

2023-06-20 13:32 UTC, come-nc commented on core/Command/TwoFactorAuth/Disable.php
> +		protected IUserManager $userManager,
```suggestion
		IUserManager $userManager,
```

2023-06-20 13:32 UTC, come-nc commented on core/Command/TwoFactorAuth/Enable.php
> +		protected IUserManager $userManager,
```suggestion
		IUserManager $userManager,
```

2023-06-20 13:32 UTC, come-nc commented on core/Command/TwoFactorAuth/Enforce.php
> +	public function __construct(private MandatoryTwoFactor $mandatoryTwoFactor) {
```suggestion
	public function __construct(
		private MandatoryTwoFactor $mandatoryTwoFactor,
	) {
```

2023-06-20 13:32 UTC, come-nc commented on core/Command/Check.php
> +	public function __construct(private SystemConfig $config) {
```suggestion
	public function __construct(
		private SystemConfig $config,
	) {
```

2023-06-20 13:32 UTC, come-nc commented on core/Command/TwoFactorAuth/State.php
> +		protected IUserManager $userManager,
```suggestion
		IUserManager $userManager,
```

2023-06-20 13:37 UTC, nfebe approved these changes
Thank you!

2023-06-20 13:39 UTC, Fenn-CS commented on core/Command/TwoFactorAuth/Cleanup.php
> +		protected IUserManager $userManager,
Would this not reduce them to ordinary parameters?

2023-06-20 15:37 UTC, fsamapoor commented on core/Command/TwoFactorAuth/Cleanup.php
> +		protected IUserManager $userManager,
It would. The thing is it is being passed to the constructor of the parent (Base) class and would be available via inheritance in the child classes. as well

2023-06-20 16:29 UTC, Fenn-CS commented on core/Command/TwoFactorAuth/Cleanup.php
> +		protected IUserManager $userManager,
Right, thanks!

2023-06-21 08:34 UTC, artonge requested changes
> There was 1 error:
>
> 1) Core\Command\TwoFactorAuth\CleanupTest::testCleanup
> ArgumentCountError: Too few arguments to function OC\Core\Command\TwoFactorAuth\Cleanup::__construct(), 1 passed in  /drone/src/tests/Core/Command/TwoFactorAuth/CleanupTest.php on line 47  and exactly 2 expected
>
> /drone/src/core/Command/TwoFactorAuth/Cleanup.php:36
> /drone/src/tests/Core/Command/TwoFactorAuth/CleanupTest.php:47

2023-06-24 22:15 UTC, artonge approved these changes

2023-06-24 22:16 UTC, artonge commented
@come-nc

2023-06-26 08:10 UTC, come-nc approved these changes

2023-06-26 08:38 UTC, merged