Enable version features again with S3 versioning
nextcloud/server pull request #38794
Opened 2023-06-13 13:23 UTC by bensmrs

## Summary

After nextcloud/files_versions_s3#28 is merged, we can enable version features with the S3 versioning backend again.

2023-06-13 13:43 UTC, icewind1991 approved these changes

2023-06-13 15:01 UTC, artonge requested changes
Is support for deleting and labeling versions was added to `files_versions_s3`?

2023-06-13 16:16 UTC, bensmrs commented
> Is support for deleting and labeling versions was added to `files_versions_s3`?

Yes, it has been implemented by nextcloud/files_versions_s3#27

2023-06-13 16:24 UTC, Fenn-CS approved these changes

2023-06-13 17:51 UTC, artonge approved these changes

2023-06-13 17:51 UTC, artonge commented
Awesome @bensmrs. Can you fix DCO ?

2023-06-13 18:25 UTC, joshtrichards commented
@bensmrs You add other email addresses in GH without messing with your primary one: 

https://github.com/settings/emails

2023-06-13 18:31 UTC, bensmrs commented
It’s already the case…
![IMG_8771](https://github.com/nextcloud/server/assets/25688414/9a298288-bfa2-4f3d-a6e5-b663b4c7912c)

2023-06-13 19:45 UTC, merged

2023-06-13 19:46 UTC, artonge commented
Done @bensmrs, thanks a lot for pushing this !! :tada:

2023-07-04 14:06 UTC, icewind1991 commented
/backport to stable27