[WIP] New user modal
nextcloud/server pull request #38826
Opened 2023-06-15 00:50 UTC by Pytal

- For https://github.com/nextcloud/server/issues/37091

## Summary

WIP

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-06-17 01:12 UTC, Pytal commented
/compile amend /

2023-06-19 10:11 UTC, artonge approved these changes
Fancy.
Not tested, and probably need a double check as there is an eslint error.

2023-06-19 10:28 UTC, szaimen approved these changes
Tested and seems to work but didnt review the code. 

Looks much better now! :)

2023-06-19 23:28 UTC, nimishavijay requested changes, later dismissed
Nice! Great improvement :) Some points regarding the "One of either password or email..." message, no other feedback, looks great :)

- [ ] We could show it as a subline under both the password and email fields to avoid confusion? Then the "(required)" next to the labels can also be removed. This way if the form is submitted without either of those fields filled, it's easy to indicate the error as the field already has the sublines for info. What do you think? cc @nextcloud/designers
- [ ] If we are not doing that, the message should be left aligned with the rest of the labels
- [ ] Would the wording "Either password or email is required" be better? @jancborchardt and @Pytal

2023-06-20 02:52 UTC, marcoambrosini approved these changes

2023-06-20 16:11 UTC, szaimen commented
@Pytal drone failure apparently related

2023-06-21 04:14 UTC, Pytal commented
> Nice! Great improvement :) Some points regarding the "One of either password or email..." message, no other feedback, looks great :)
> 
> * [ ]  We could show it as a subline under both the password and email fields to avoid confusion? Then the "(required)" next to the labels can also be removed. This way if the form is submitted without either of those fields filled, it's easy to indicate the error as the field already has the sublines for info. What do you think? cc @nextcloud/designers

Duplicating the text as sublines seems strange 🤔

For invalid input the native form validation should suffice
![image](https://github.com/nextcloud/server/assets/24800714/879162b2-c54a-4ed2-b0eb-eb1d5f6a967f)

> * [x]  If we are not doing that, the message should be left aligned with the rest of the labels
> * [x]  Would the wording "Either password or email is required" be better? @jancborchardt and @Pytal

2023-06-21 15:26 UTC, JuliaKirschenheuter approved these changes
Tested ;) Works, code looks good

2023-06-21 18:26 UTC, szaimen commented on apps/settings/src/components/Users/NewUserModal.vue
> +			return t('settings', 'Username (required)')
Small suggestion (not sure if we use that somewhere but would possibly make sense to make clear that it cannot be changed afterwards?):

```suggestion
			return t('settings', 'User id (required)')
```

2023-06-21 18:26 UTC, szaimen commented on apps/settings/src/components/Users/NewUserModal.vue
> +				:label="t('settings', 'Display name')"
Maybe?

```suggestion
				:label="t('settings', 'Display name of user')"
```

2023-06-21 18:29 UTC, Pytal commented on apps/settings/src/components/Users/NewUserModal.vue
> +			return t('settings', 'Username (required)')
@nimishavijay?

2023-06-21 18:29 UTC, Pytal commented on apps/settings/src/components/Users/NewUserModal.vue
> +				:label="t('settings', 'Display name')"
@nimishavijay?

2023-06-21 23:13 UTC, merged

2023-06-21 23:14 UTC, Pytal commented
What do you think about @szaimen's wording suggestions for follow-up @jancborchardt?