Introduce LanguageModel OCP API
nextcloud/server pull request #38854
Opened 2023-06-16 11:29 UTC by marcelklehr

* Resolves: #38578 

## Summary

## TODO

- [ ] Ethical AI rating
- [ ] Setting default provider per task type

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-06-23 11:00 UTC, julien-nc reviewed
Noice!

> * [ ] Setting default provider per task type

Any idea on how this would be done? We could start and avoid thinking about making this appear in the UI. How would the information be set and stored? occ command, OCS endpoint? Stored in a dedicated table? Consumed by the manager's runTask method so it would really reflect the current value?

2023-06-26 09:39 UTC, marcelklehr commented on lib/private/LanguageModel/LanguageModelManager.php
> +	public function runTask(ILanguageModelTask $task): string {
Consumers can call `runTask` to run it synchronously or `scheduleTask` to run it asynchronously.

> Some tasks might be short enough to run synchronously.

Genereally I'd only recommend calling runTask in background tasks.

> How would the consumers deal with asynchronicity? The UI would poll until the task has run?

Yes. `scheduleTask` sets the task id which allows to poll using `getTask` of the Manager or the Controller.

2023-06-26 10:06 UTC, marcelklehr commented
>  > Setting default provider per task type
>
> Any idea on how this would be done?

I think it would make sense to do this in a new PR together with the settings for translations and STT.

2023-06-27 08:40 UTC, kesselb commented on lib/public/AppFramework/Bootstrap/IRegistrationContext.php
> +	 * @since 27.0.0
```suggestion
	 * @since 28.0.0
```

2023-06-27 11:53 UTC, kesselb commented on lib/private/LanguageModel/LanguageModelManager.php
> +		return !empty($context->getSpeechToTextProviders());
```suggestion
		return count($context->getSpeechToTextProviders()) > 0;
```

2023-06-27 11:53 UTC, kesselb commented on lib/private/LanguageModel/LanguageModelManager.php
> +		return !empty($context->getSpeechToTextProviders());
or `$context->getSpeechToTextProviders() !== []`;

2023-06-27 11:53 UTC, kesselb commented on lib/private/LanguageModel/LanguageModelManager.php
> +		return !empty(array_filter($this->getAvailableTasks(), fn ($class) => $task instanceof $class));
```suggestion
		return count(array_filter($this->getAvailableTasks(), fn ($class) => $task instanceof $class)) > 0;
```

2023-06-27 11:56 UTC, kesselb commented
Looks nice, thank you!

I've suggested replacing !empty with count() > 0. Backstory is https://localheinz.com/articles/2023/05/10/avoiding-empty-in-php/#content-array which advises against using empty, when the code is properly typed.

2023-06-27 13:23 UTC, marcelklehr commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * @throws \ValueError If the task could not be found
yeah, didn't want to create a new class. Do you have a better fitting class at hand? Of should I just create a new class?

2023-06-27 13:26 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * @throws \ValueError If the task could not be found
I've seen other cases where a generic *NotFoundException* could be handy. Right now we only have one for DB operations. Using that one here feels wrong. We could add a generic one to OCP, like `\OCP\Common\Exception\NotFoundException`

2023-06-27 14:53 UTC, marcelklehr commented on lib/public/LanguageModel/TopicsTask.php
> +		}
Good idea! I managed to fix it :)

2023-06-27 17:40 UTC, ChristophWurst commented on lib/public/LanguageModel/FreePromptTask.php
> -	public function visitProvider(ILanguageModelProvider $provider): string {
nit: you can leave the native type in addition so PHP does a runtime check

2023-06-27 18:25 UTC, marcelklehr commented on lib/public/LanguageModel/FreePromptTask.php
> -	public function visitProvider(ILanguageModelProvider $provider): string {
I think I tried that but psalm wouldn't have it

2023-06-28 10:27 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelProvider.php
> +	public function prompt(string $prompt): string;
> There might be tasks in the future that require more params, but we can add those as normal params then

That will be a breaking change then because implementers of the OCP API have to adjust. If you use an object you can add additional methods without adjusting implementers of an interface.

We used the same trick for the bootstrap context for example.

2023-06-28 11:39 UTC, marcelklehr commented on lib/public/LanguageModel/ILanguageModelProvider.php
> +	public function prompt(string $prompt): string;
> That will be a breaking change then

Mh, I don't think it would, as new tasks will get a new interface, like ISummaryProvider here

2023-06-28 11:40 UTC, marcelklehr commented on lib/public/LanguageModel/ILanguageModelProvider.php
> +	public function prompt(string $prompt): string;
So, I think we might add new tasks (as new interfaces) but probably not new params for existing tasks.

2023-06-28 11:46 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelProvider.php
> +	public function prompt(string $prompt): string;
Alright

2023-06-28 13:12 UTC, ChristophWurst commented on lib/private/LanguageModel/Db/TaskMapper.php
> +		$entity->setLastUpdated(time());
not testable (reminds me that this PR doesn't have unit tests)

inject the time factory

2023-06-28 13:18 UTC, marcelklehr commented on lib/public/LanguageModel/FreePromptTask.php
> -	public function visitProvider(ILanguageModelProvider $provider): string {
Ah, I have to use psalm-param. got it.

2023-06-28 14:19 UTC, marcelklehr commented
I've never written tests for server before, so please bear with me. I hope this first commit goes in the right direction :)

2023-06-28 20:41 UTC, ChristophWurst commented on tests/lib/LanguageModel/LanguageModelManagerTest.php
> +			\OC::$server->get(IServerContainer::class),
inject mocks please

2023-07-03 10:14 UTC, marcelklehr commented
Tests are in :)

2023-07-05 12:52 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * with the \OCP\LanguageModel\Events\TaskFinishedEvent
how can an app associate the task dispatched here when `TaskSuccessfulEvent` is emitted?

2023-07-05 12:56 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * with the \OCP\LanguageModel\Events\TaskFinishedEvent
specifically for https://github.com/nextcloud/mail/issues/8508 I need to know which user and which thread has been summarized. Would it make sense if apps could pass an identifier when the task is scheduled that is exposed as getter on the event?

2023-07-05 12:59 UTC, ChristophWurst commented
> I've never written tests for server before

Are you familiar with the concept of unit tests, integration tests and their differences? Asking because right now the tests do *a lot* and are not isolated and therefore probably not the fastest. In my opinion there should be full coverage with real unit tests and integration tests for selected paths that are most important.

2023-07-05 13:48 UTC, marcelklehr commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * with the \OCP\LanguageModel\Events\TaskFinishedEvent
In the current state this method sets the task ID on the task and people can set userId and appId on the task object which will be persisted.

> Would it make sense if apps could pass an identifier when the task is scheduled that is exposed as getter on the event?

We can do that, yeah. What were you thinking? A string? Or an int? Or something more complex?

2023-07-05 14:09 UTC, marcelklehr commented
Hey :)

> Are you familiar with the concept of unit tests, integration tests and their differences?

I'm somewhat familiar with unit and integration tests. I tend to not buy into unit tests and rather go with integration tests, as I feel unit tests have a low return on investment.

> Asking because right now the tests do a lot and are not isolated and therefore probably not the fastest.

I did mock most if not all of the unrelated classes. Currently it takes 6s for me.

> In my opinion there should be full coverage with real unit tests and integration tests for selected paths that are most important.

I will get to writing unit tests, then :) Can we finalize the API first, then? That would avoid blocking you for implementing the downstream stuff and me for the docs.

2023-07-05 14:50 UTC, ChristophWurst commented
Done right, unit tests will make you structure code into easier chunks and they can test all the nifty edge cases without the heavy setup cost.

> I did mock most if not all of the unrelated classes. Currently it takes 6s for me.

That's a lot IMO. The server has thousands of tests. If every feature is tested like this we make test execution unreasonable for local changes.

Mail's full unit test suitefor comparison:

```
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.7
Configuration: tests/phpunit.unit.xml

...............................................................  63 / 595 ( 10%)
............................................................... 126 / 595 ( 21%)
............................................................... 189 / 595 ( 31%)
............................................................... 252 / 595 ( 42%)
............................................................... 315 / 595 ( 52%)
............................................................... 378 / 595 ( 63%)
............................................................... 441 / 595 ( 74%)
............................................................... 504 / 595 ( 84%)
............................................................... 567 / 595 ( 95%)
............................                                    595 / 595 (100%)

Time: 00:01.936, Memory: 26.00 MB

OK (595 tests, 1537 assertions)

real    0m2,958s
user    0m2,653s
sys     0m0,218s
```

But let's not get sidetracked. I'm not directly responsible for this repo so I'll leave the decisions to the server devs.

I'll put my focus back on the usability of the API for https://github.com/nextcloud/mail/issues/8508 :+1:

2023-07-05 14:51 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * with the \OCP\LanguageModel\Events\TaskFinishedEvent
I think a string would be most flexible. Apps can come up with their own format for it, be it serialized json or something else.

2023-07-05 17:48 UTC, ChristophWurst reviewed
:+1: Looks usable for the Mail thread summarization once we have a generic identification property to map successful summaries back to their corresponding threads. App ID and user ID is not sufficient.

2023-07-05 17:48 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelTask.php
> +	public function getStatus(): int;
```suggestion
	 * @return ILanguageModelTask::STATUS_*
	 * @since 28.0.0
	 */
	public function getStatus(): int;
```

2023-07-05 17:48 UTC, ChristophWurst commented on lib/public/LanguageModel/ILanguageModelTask.php
> +	 * @param int $status
```suggestion
	 * @param ILanguageModelTask::STATUS_* $status
```

2023-07-06 07:48 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
I just realized this may not be ideal from a security perspective. There is no authentication in any way here so people can just guess an id and leak private data :/

2023-07-06 07:52 UTC, ChristophWurst commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
Drop `@PublicPage` and compare the task's user ID with the current user ID?

2023-07-06 08:57 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
The idea was for guests to also be able to call this API, though. For this we'd need PublicPage. However, any guest could then request any other guest's tasks. :/

2023-07-06 09:32 UTC, marcelklehr commented on lib/private/LanguageModel/Db/Task.php
> +		]);
Not sure how I can avoid this

2023-07-06 09:54 UTC, ChristophWurst commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
With guest you mean anonymous users, not a user generated by https://github.com/nextcloud/guests/, right? Because the latter does have a session and is logged in.

2023-07-06 10:16 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
Right, yes.

2023-07-06 10:22 UTC, ChristophWurst commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
You could add a flag for tasks and results that are considered public and only allow access to those

2023-07-06 10:30 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
Mh, thinking about this more, it's probably unlikely that anonymous users will schedule tasks with private data

2023-07-06 10:42 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function getTask(int $id): DataResponse {
I added the userId === task->userId check now, I think this should be good enough.

2023-07-06 10:55 UTC, come-nc commented on lib/private/LanguageModel/Db/Task.php
> +		]);
Not clear to me. What is the return type of Task::fromParams seen by psalm?

2023-07-06 10:57 UTC, marcelklehr commented on lib/private/LanguageModel/Db/Task.php
> +		]);
OCP\AppFramework\Db\Entity::fromParams declares `static` as its return type

2023-07-06 12:39 UTC, come-nc commented on lib/private/LanguageModel/Db/Task.php
> +		]);
I’m lost then, Task::fromParams has to return a Task. Not sure what bugs psalm.

2023-07-06 13:05 UTC, ChristophWurst commented on lib/private/LanguageModel/Db/Task.php
> +		]);
This could be a Psalm bug https://psalm.dev/r/f5530d3538

2023-07-06 13:06 UTC, ChristophWurst commented on lib/private/LanguageModel/Db/Task.php
> +		]);
https://psalm.dev/r/6f8dde5356 this is very strange. Note how `Task::fromParams` results in different types for $t1 and $temp

2023-07-06 13:14 UTC, ChristophWurst commented on lib/private/LanguageModel/Db/Task.php
> +		]);
You can help Psalm by saving the new task into a variable and spec'ing a type: https://psalm.dev/r/e2837a5e3e

2023-07-06 13:31 UTC, marcelklehr commented
I added the 'identifier' prop

2023-07-06 14:59 UTC, come-nc requested changes

2023-07-06 14:59 UTC, come-nc commented on lib/private/LanguageModel/Db/Task.php
> +
copyright and strict_types missing, same for TaskMapper

2023-07-06 14:59 UTC, come-nc commented on lib/private/LanguageModel/LanguageModelManager.php
> +	public function getAvailableTasks(): array {
Or 
```suggestion
	public function getAvailableTaskClasses(): array {
```
?

2023-07-06 14:59 UTC, come-nc commented on lib/private/LanguageModel/LanguageModelManager.php
> +		return count(array_filter($this->getAvailableTasks(), fn ($class) => $task instanceof $class)) > 0;
Hard to read and suboptimal, use a foreach and stop at first true?

2023-07-06 14:59 UTC, come-nc commented on lib/private/LanguageModel/TaskBackgroundJob.php
> +		$this->setAllowParallelRuns(false);
Maybe add a comment to explain why

2023-07-06 14:59 UTC, come-nc commented on lib/public/Common/Exception/NotFoundException.php
> +	public function __construct($msg) {
```suggestion
	public function __construct(string $msg) {
```

2023-07-06 14:59 UTC, come-nc commented on lib/public/LanguageModel/AbstractLanguageModelTask.php
> +use OC\LanguageModel\Db\Task;
Nope. Cannot use `OC` from `OCP`.

2023-07-06 14:59 UTC, come-nc commented on lib/public/LanguageModel/Events/TaskFailedEvent.php
> +		private string $errorMessage) {
```suggestion
	public function __construct(
		ILanguageModelTask $task,
		private string $errorMessage,
	) {
```

2023-07-06 14:59 UTC, come-nc commented on lib/public/LanguageModel/ILanguageModelManager.php
> +	 * with the \OCP\LanguageModel\Events\TaskFinishedEvent
There is no `\OCP\LanguageModel\Events\TaskFinishedEvent`

2023-07-06 14:59 UTC, come-nc commented on lib/public/LanguageModel/ILanguageModelProvider.php
> + * This is the minimum interface is implemented by apps that
```suggestion
 * This is the minimum interface that is implemented by apps that
```
or "which"?

2023-07-06 14:59 UTC, come-nc commented on tests/lib/LanguageModel/LanguageModelManagerTest.php
> +		$this->eventDispatcher->addListener(TaskSuccessfulEvent::class, function (TaskSuccessfulEvent $event) use (&$successfulEventFired, $task) {
It would be better to mock the event listener and expect the method call instead.

2023-07-06 14:59 UTC, come-nc commented on tests/lib/LanguageModel/LanguageModelManagerTest.php
> +		// Topics are not implemented by both the vanilla provider and the full provider
Then why is it called TestFullLanguageModelProvider if it is not full :-P

2023-07-06 15:04 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +	 */
It's optional for now

2023-07-07 07:46 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	public function schedule(string $text, string $type, ?string $appId, string $identifier = ''): DataResponse {
Yes

2023-07-07 09:34 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +	 */
Done

2023-07-07 09:38 UTC, marcelklehr commented on lib/private/LanguageModel/LanguageModelManager.php
> +			}
A follow up PR will add admin settings for all AI APIs to set a preference

2023-07-07 09:40 UTC, provokateurin requested changes

2023-07-07 09:40 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +	 * @return DataResponse<Htpp::STATUS_NOT_FOUND|Http::STATUS_INTERNAL_SERVER_ERROR, array{message:string}>|DataResponse<Http::STATUS_OK,array{task: array{id: int,type:string,status: ILanguageModelTas
```suggestion
	 * @return DataResponse<Htpp::STATUS_NOT_FOUND|Http::STATUS_INTERNAL_SERVER_ERROR, array{message: string}>|DataResponse<Http::STATUS_OK, array{task: array{id: int, type: string, status: ILanguageModelTask::STATUS_*, userId: string, appId: string, input: string, output: string, identifier: string}}, array{}>
```

Please use spaces then it will get more readable. Also applies to the other controller methods.

2023-07-07 09:40 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +	 * @return DataResponse<Http::STATUS_OK,array{task: array{id: int,type:string,status: ILanguageModelTask::STATUS_*,userId: string, appId: string,input: string,output: string, identifier: string}},ar
`ILanguageModelTask::STATUS_*` is not going to work with openapi-extractor, you will have to type it as int. Same for the controller method below.

2023-07-07 11:27 UTC, marcelklehr commented
Tests with --exclude-group DB,SLOWDB on master currently take 01:00.693 on my machine, while this branch takes 01:00.377 :shrug:

2023-07-07 11:32 UTC, marcelklehr commented
Should I add a capability for this OCS API? There's no docs on how this works, sadly.

2023-07-07 11:50 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			]);
@marcelklehr I think you are just missing the return type annotation on the jsonSerialize method of the AbstractLanguageModelTask

2023-07-07 11:53 UTC, provokateurin requested changes

2023-07-07 11:53 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +	 * @return DataResponse<Http::STATUS_OK,array{task: array{id: int, type: string, status: int, userId: string, appId: string, input: string, output: string, identifier: string}},array{}> | DataRespon
```suggestion
	 * @return DataResponse<Http::STATUS_OK, array{task: array{id: int, type: string, status: int, userId: string, appId: string, input: string, output: string, identifier: string}}, array{}>| DataResponse<Http::STATUS_PRECONDITION_FAILED|Http::STATUS_BAD_REQUEST, array{message: string}, array{}>
```

For the union operator I wouldn't use spaces, just after every comma

2023-07-07 11:59 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			]);
$task is a ILanguageModelTask here, though and that method comes from the Json serialize interface :/

2023-07-11 13:05 UTC, provokateurin submitted a review, later dismissed

2023-07-11 13:05 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
This annotation has to be on the method itself and not here where it is used

2023-07-11 13:05 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			$json = $task->jsonSerialize();
Same again with the annotation

2023-07-11 13:28 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
The method is not from me, though

2023-07-11 13:33 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
Works fine for me

2023-07-11 14:10 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
This is where the method comes from: https://github.com/nextcloud/server/pull/38854/files#diff-4fcc874a025d38b83e66c558753978cb0f31ddc369330fc6fa03bd3721eace4bR32

2023-07-11 14:13 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
You just need to set the annotation on the class that implements it (which should be https://github.com/nextcloud/server/pull/38854/files#diff-aa82def10581f49d1d2fc84749d32c130bab07f186a728ed92c8686875535d24R149).

2023-07-12 11:58 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
Setting a \@method annotation on AbstractLanguageModelTask will not work, because that's not the type I'm using. I'm using ILanguageModelTask. Setting an \@method annotation on that interface has no effects.

2023-07-12 12:12 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
Psalm knows what implementations exist and it correctly infers the type from the implementation even if you always give it the interface. I know it works because I've already done it a few times in the server repo.

2023-07-12 12:40 UTC, marcelklehr commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
> Psalm knows what implementations exist and it correctly infers the type from the implementation even if you always give it the interface.

That sounds like a dangerous feature.

I tried both 

```
@psalm-method array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} jsonSerialize()
```

on the AbstractLanguageModel class and 

```
@return array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string}
``` 

on the method implementation. It infers mixed in both cases as the result of jsonSerialize().

2023-07-12 12:42 UTC, provokateurin commented on core/Controller/LanguageModelApiController.php
> +			/** @var array{id: int|null, type: string, status: int, userId: string|null, appId: string, input: string, output: string|null, identifier: string} $json */
Hm, feel free to just remove all the API annotations, I will fix this later

2023-07-17 08:38 UTC, come-nc approved these changes

2023-07-17 08:38 UTC, come-nc commented on lib/private/TextProcessing/Manager.php
> +use \OCP\TextProcessing\Task as OCPTask;
```suggestion
use OCP\TextProcessing\Task as OCPTask;
```

2023-07-17 08:38 UTC, come-nc commented on lib/public/TextProcessing/Events/TaskSuccessfulEvent.php
> +}
```suggestion
class TaskSuccessfulEvent extends AbstractTextProcessingEvent {
}
```

This is the same, no?

2023-07-19 10:35 UTC, julien-nc requested changes
Nice!

2023-07-19 10:35 UTC, julien-nc commented on lib/public/TextProcessing/Task.php
> +		}
This will prevent scheduling app-defined task types. Maybe this could rather check if the type is in `OC\TextProcessing\Manager::getAvailableTaskTypes()`.

2023-07-19 10:35 UTC, julien-nc commented on lib/private/TextProcessing/Manager.php
> +		]);
Best case scenario, the job runs next time cron.php is executed, right?
If so, maybe we could think about allowing providers to say they will be fast and run the task immediately. All good for now, just thinking ahead.

2023-07-19 10:38 UTC, julien-nc commented on core/Controller/TextProcessingApiController.php
> +	public function taskTypes(): DataResponse {
As discussed, maybe it makes sense to have another endpoint to list the providers (maybe grouped by task type).

Also, maybe we could include the "selected provider" for each task type in the result of this `taskTypes` method.

WDYT?

2023-07-19 11:10 UTC, marcelklehr commented on core/Controller/TextProcessingApiController.php
> +	public function taskTypes(): DataResponse {
Do we really need the providers on the frontend though? I think we would usually want to hide them, no?

2023-07-19 13:42 UTC, marcelklehr commented on core/Controller/TextProcessingApiController.php
> +	public function taskTypes(): DataResponse {
> the "selected provider" for each task type

I tend to think this should be hidden from the user. Only the admin should see this.

> maybe it's useful for the settings part where admins can choose the "default" provider for each task type

I'll deal with that in the follow up PR :)

2023-07-19 14:53 UTC, julien-nc approved these changes
:tada:

2023-07-21 09:20 UTC, merged

2023-07-21 09:21 UTC, marcelklehr commented
Docs: https://github.com/nextcloud/documentation/pull/10714

2023-07-21 18:26 UTC, AndyScherzinger commented
@marcelklehr backport to 27 needed?

2023-07-22 08:55 UTC, marcelklehr commented
@AndyScherzinger Yes! If we backport now, this is gonna land in 27.0.2, though.

2023-07-22 09:06 UTC, AndyScherzinger commented
Ah, right 👍

Good point 🫣

2023-08-09 07:21 UTC, marcelklehr commented
/backport to stable27

2023-08-13 13:13 UTC, nickvergessen commented on lib/public/Common/Exception/NotFoundException.php
> +namespace OCP\Common\Exception;
This is quite an anti pattern and we really try hard to get rid of the `OC_Util` and `OCP\Util`, so let's not start the next thing we can never change because it is used by multiple mechanisms in different ways.

Can we deprecate this (or even revert since it was never released apart from beta) and instead add a dedicated TaskNotFound exception inside the text processing namespace?

2023-08-13 13:13 UTC, nickvergessen commented on lib/private/TextProcessing/Manager.php
> +			throw new NotFoundException('Could not find task with the provided id');
As per other comment, either (re)throw `DoesNotExistException` which is already a generic exception with the same meaning, or a dedicated TaskNotFound

2023-08-15 20:18 UTC, marcelklehr commented on lib/public/Common/Exception/NotFoundException.php
> +namespace OCP\Common\Exception;
It was suggested to me by other reviewers :shrug: 
I'm on vacation until end of August. Feel free to change this in my absence.

2023-08-16 06:38 UTC, nickvergessen commented on lib/public/Common/Exception/NotFoundException.php
> +namespace OCP\Common\Exception;
Just read up on the comments... alright then :(

And enjoy your hols! 😎