Properly handle deleted users in UserMountCache
nextcloud/server pull request #3888
Opened 2017-03-17 00:29 UTC by MorrisJobke

When encountering entries from a deleted user, discard such entries.

* downstream of https://github.com/owncloud/core/pull/27028

@icewind1991 Does that make sense? You added the array_filter before and upstream added the deletion as well.

2017-03-17 08:33 UTC, nickvergessen requested changes

2017-03-17 08:33 UTC, nickvergessen commented on lib/private/Files/Config/UserMountCache.php
> +			// user does not exist any more, delete all mounts of that user directly
So in case your user backend (like ldap) has a hick-up or is temporarily wrong configured, everything will be whiped?
Sounds a bit odd, not sure if we should do this. I agree with the rest of this PR, but I'm not a friend of this delete query.

2017-03-17 13:32 UTC, icewind1991 requested changes
Would be better to just delete the rows when a user is deleted

2017-03-22 23:43 UTC, MorrisJobke commented
> Would be better to just delete the rows when a user is deleted

@icewind1991 Could you create a PR for that?

2017-03-22 23:43 UTC, MorrisJobke commented
> @icewind1991 Could you create a PR for that?

Or adjust this PR. Maybe the unit tests are still valid.

2017-08-08 17:20 UTC, closed without merging