fix(core): Do not invert app menu text color
nextcloud/server pull request #38897
Opened 2023-06-19 10:57 UTC by Hephi2

* Also fixes other cypress test
* Build assets

* Fixes #38759 
See #38776

2023-06-19 13:58 UTC, mejo- commented
Cypress test failures seem unrelated. The last merge to `stable27` also failed to run any Cypress e2e tests: https://github.com/nextcloud/server/actions/runs/5311915284/jobs/9615820016

2023-06-19 14:06 UTC, mejo- commented
I have no idea why the psalm test fails. Apparently it didn't fail on former `stable27` PRs, but this PR doesn't touch anything related :thinking:

2023-06-19 14:09 UTC, mejo- approved these changes

2023-06-19 14:10 UTC, mejo- requested changes

2023-06-19 14:10 UTC, mejo- commented on core/src/components/AppMenu.vue
> -		opacity: .7;
This seems unrelated and a failure in the manual backport @Hephi2, no?

2023-06-19 14:13 UTC, szaimen requested changes
3rdparty should not get updated here

2023-06-19 14:13 UTC, szaimen commented on core/src/components/AppMenu.vue
> -		opacity: .7;
indeed

2023-06-20 09:15 UTC, mejo- approved these changes

2023-06-20 09:16 UTC, szaimen approved these changes
backport looks good

2023-06-20 11:17 UTC, merged