Sharing dialog: make autocomplete sorting case insensitive
nextcloud/server pull request #3889
Opened 2017-03-17 00:38 UTC by MorrisJobke

* downstream of https://github.com/owncloud/core/pull/26950

cc @nextcloud/javascript @nextcloud/sharing for review

2017-03-17 00:45 UTC, MorrisJobke commented
I tested this and it works 👍

2017-03-17 08:22 UTC, nickvergessen requested changes

2017-03-17 08:22 UTC, nickvergessen commented on core/js/sharedialogview.js
> +								return OC.Util.naturalSortCompare(a.label, b.label);
This is wrong, the list is sorted on php, when that behaves incorrect we need to fix it there. Otherwise each page is sorted correctly, while the results should be on different pages.

2017-03-17 08:30 UTC, nickvergessen commented on core/js/sharedialogview.js
> +								return OC.Util.naturalSortCompare(a.label, b.label);
My suggestion would be:
```diff
diff --git a/lib/private/User/Database.php b/lib/private/User/Database.php
index a281572ad5..dfbd995fb2 100644
--- a/lib/private/User/Database.php
+++ b/lib/private/User/Database.php
@@ -193,7 +193,7 @@ class Database extends Backend implements IUserBackend {
 
                $displayNames = array();
                $query = \OC_DB::prepare('SELECT `uid`, `displayname` FROM `*PREFIX*users`'
-                       . $searchLike .' ORDER BY `uid` ASC', $limit, $offset);
+                       . $searchLike .' ORDER BY LOWER(`displayname`), LOWER(`uid`) ASC', $limit, $offset);
                $result = $query->execute($parameters);
                while ($row = $result->fetchRow()) {
                        $displayNames[$row['uid']] = $row['displayname'];
@@ -279,7 +279,7 @@ class Database extends Backend implements IUserBackend {
                        $searchLike = ' WHERE LOWER(`uid`) LIKE LOWER(?)';
                }
 
-               $query = \OC_DB::prepare('SELECT `uid` FROM `*PREFIX*users`' . $searchLike . ' ORDER BY `uid` ASC', $limit, $offset);
+               $query = \OC_DB::prepare('SELECT `uid` FROM `*PREFIX*users`' . $searchLike . ' ORDER BY LOWER(`uid`) ASC', $limit, $offset);
                $result = $query->execute($parameters);
                $users = array();
                while ($row = $result->fetchRow()) {
diff --git a/lib/private/User/Manager.php b/lib/private/User/Manager.php
index 3d016700ee..77741efcc7 100644
--- a/lib/private/User/Manager.php
+++ b/lib/private/User/Manager.php
@@ -254,7 +254,7 @@ class Manager extends PublicEmitter implements IUserManager {
                         * @var \OC\User\User $a
                         * @var \OC\User\User $b
                         */
-                       return strcmp($a->getDisplayName(), $b->getDisplayName());
+                       return strcmp(strtolower($a->getDisplayName()), strtolower($b->getDisplayName()));
                });
                return $users;
        }
```

2017-03-22 23:12 UTC, MorrisJobke commented
@nickvergessen I fixed it according to your recommendation. Only drawback with that: Groups are not sorted within the users list, but they are just concatenated at the end of the list.

2017-03-23 16:27 UTC, nickvergessen commented
Yeah, but thats intentional I think

2017-03-23 16:27 UTC, nickvergessen approved these changes

2017-03-23 20:42 UTC, ChristophWurst approved these changes

2017-03-23 20:44 UTC, ChristophWurst commented on core/js/tests/specs/sharedialogviewSpec.js
> +			])).toEqual(true);
Test fails with
```
PhantomJS 2.1.1 (Linux 0.0.0) OC.Share.ShareDialogView autocompletion of users is sorted naturally FAILED
	Expected false to equal true.
core/js/tests/specs/sharedialogviewSpec.js:565:15
```

2017-03-23 21:41 UTC, MorrisJobke commented on core/js/tests/specs/sharedialogviewSpec.js
> +			])).toEqual(true);
Fixed 🙈

2017-03-24 05:45 UTC, merged