Add cancel button for when user entry is being edited
nextcloud/server pull request #38952
Opened 2023-06-23 01:02 UTC by JeaNugroho

* Resolves: #22608

## Summary
Add a cancel button between checkmark button and three-dot button for when user entry is being edited.
### Before
![Screen Shot 2023-06-22 at 8 02 07 PM](https://github.com/nextcloud/server/assets/35510082/fddd8aa8-0fdf-4d52-993f-58f1023b9948)

### After
![Screen Shot 2023-06-21 at 10 40 21 PM](https://github.com/nextcloud/server/assets/35510082/e56dc22e-7e4c-4b9b-8a56-d43ef91fcab4)

## Potential next steps
[This comment](https://github.com/nextcloud/server/issues/22608#issuecomment-751663701) may be the next fix to make user experience more intuitive and straightforward. I personally would think that the user editing process would be like this if I were a new user to the app. I can certainly implement a way to make this happen, either in the same PR or in the next PR after this one's completed.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-06-23 07:54 UTC, Fenn-CS requested changes
Thank you so far! Left an inline comment.

2023-06-23 07:54 UTC, Fenn-CS commented on apps/settings/src/components/Users/UserRow.vue
>  						@click="editing = false" />
```suggestion
```

Perhaps? I mean the check and the cancel appears to do the same thing, so it's even more confusing or misleading because it could imply that the `check` is to validate the action.

We should probably remove it or make the check validate all "line edits"

2023-06-23 11:20 UTC, JeaNugroho commented on apps/settings/src/components/Users/UserRow.vue
>  						@click="editing = false" />
@Fenn-CS I agree with you here that this is one of the fixes. 

However, I have a rough thought on how to implement the check button click as a validation to all line edits. This would mean submit any changes to the user fields by clicking on that check button and omit the "submit individual field changes by clicking on the arrow button in each field" functionality. I can add this as another commit to this PR. If it turns out that the fix is way harder than I thought, then I'll resort to deleting the check button.

Would you say the same?

2023-06-25 00:46 UTC, JeaNugroho commented on apps/settings/src/components/Users/UserRow.vue
>  						@click="editing = false" />
@Fenn-CS I might think that it's best to follow your suggestion. I just realized there could be more complicated things happening while editing the user entries. For e.g., an authorization popup can appear while editing one of the fields. This fix you suggested gives a minimum change that wouldn't bother other features that I have yet to know.

I've also added an additional commit to omit the `:inline="2"` bind since we deleted the checkmark button. Please let me know if I can change any other things, otherwise I'm happy if this PR can be completed and changes can be merged. This'd my first PR for Nextcloud and open source contribution =)

2023-06-30 08:30 UTC, artonge reviewed
Watch out as the component has been heavily modified recently, so your change might need to be adapted.

https://github.com/nextcloud/server/pull/38839

2023-06-30 22:24 UTC, nimishavijay requested changes
Super nice! :) Only one tiny thing to nitpick: All the icons in a column should be center-aligned ideally. So the buttons should be moved slightly to the right, so that the close icon is nicely aligned with all the edit icons above it :)

2023-07-01 10:01 UTC, Fenn-CS commented on apps/settings/src/components/Users/UserRow.vue
>  						@click="editing = false" />
Thanks for you contribution @JeaNugroho !

This now makes better sense to me.

2023-07-01 10:04 UTC, Fenn-CS reviewed
This now looks ok to me however,

- There's a review about alignment which you should address
- Update the screenshot in the description to reflect the new changes

And we would be good to go! Thank you for your contribution :)

2023-07-01 14:04 UTC, susnux commented
This needs to be rebased as the @artonge said it was heavily modified.
The settings are not saved when pressing the check button "done" but when you save a field. Similar to all other settings on Nextcloud which are saved on change rather than that there is a "save" button.

2023-07-04 04:18 UTC, JeaNugroho commented
Have just rebased! I'll try to fix the alignment and update the original commit with the new screenshot of the layout. And then when any of the required CI checks fail, I hope someone can provide guidance for that 😊

@Fenn-CS @susnux @artonge @nimishavijay

2023-07-04 21:48 UTC, JeaNugroho commented
@Fenn-CS @artonge @susnux 
We now clearly know that we need to fix eslint and Node. I recall from a different PR I'm doing, we need to run `npm run build` to fix Node and run `npm run lint:fix` to fix eslint. So I don't mess this PR like the other one, in what sequence do I have to run these? And are there any other commands or things should I do before, after, or in between these two commands?

2023-07-04 22:23 UTC, Fenn-CS commented
@JeaNugroho  you should lint and then build ideally! 

However there are some merge conflicts in your PR, check the files tab closely. I would leave some inline comments to help you see them.

2023-07-04 22:24 UTC, Fenn-CS commented on apps/settings/src/components/Users/UserRow.vue
> +>>>>>>> 7a2938b01f3 (Add cancel button for when user entry is being edited)
```suggestion
```

Merge conflict, and deleting this line is not the solution though you want to work with perhaps your code editor to help you resolve the conflicts.

2023-07-04 22:25 UTC, Fenn-CS commented on apps/settings/src/components/Users/UserRow.vue
> +<<<<<<< HEAD
```suggestion
```

Another conflict marker

2023-07-04 22:25 UTC, Fenn-CS commented on apps/settings/src/components/Users/UserRow.vue
> +=======
```suggestion
```

Conflict.

2023-07-06 02:13 UTC, Pytal commented
Thanks @JeaNugroho! We have some more modifications incoming, would it be fine with you if we revisit this after merging https://github.com/nextcloud/server/pull/39050 to prevent conflicts?

2023-12-28 02:35 UTC, joshtrichards commented
#39050 has been merged, @JeaNugroho. So feel free to proceed. :)

2024-08-03 16:43 UTC, closed without merging