Refactors lib/private/Accounts classes
nextcloud/server pull request #38978
Opened 2023-06-24 09:32 UTC by fsamapoor

Following [previous PRs taking advantage of PHP8's constructor property promotion](https://github.com/nextcloud/server/pulls?q=is%3Apr+author%3Afsamapoor+Uses+PHP8%27s+constructor+property+promotion) in `/core/` namespace, I have also made the required adjustments to the classes in `/lib/private/Accounts` namespace.

The improvements in this PRs include but are not limited to:
- Using PHP8's constructor property promotion
- Adding return types
- Adding types to properties
- Removing redundant docblocks

2023-06-24 15:58 UTC, Fenn-CS approved these changes
Looks okay! +1 on the more precise match.

Thank you

2023-06-30 22:51 UTC, solracsf commented
CI is failing.

2023-07-02 08:50 UTC, fsamapoor commented
@solracsf Thank you for the heads up. I wasn't aware that the failing CI was in fact a result of failing test cases. I have fixed the failing tests and everything seems to be fine now.

2023-07-05 10:34 UTC, blizzz requested changes
small nitpick

2023-07-05 10:34 UTC, blizzz commented on lib/private/Accounts/AccountManager.php
> +		private IFactory $factory,
```suggestion
		private IFactory $l10nFactory,
```

rename this for readbility/clarity, factory alone is a bit broad

2023-07-05 10:59 UTC, blizzz approved these changes

2023-07-05 11:08 UTC, fsamapoor commented on lib/private/Accounts/AccountManager.php
> +		private IFactory $factory,
@blizzz Thanks. Other than making it more readable, I searched the codebase and almost all other classes also used this convention. So keeping it consistent is always good.

2023-07-05 13:52 UTC, blizzz commented
failing tests unrelated => merging

2023-07-05 13:52 UTC, merged