Refactors lib/private/FullTextSearch
nextcloud/server pull request #38996
Opened 2023-06-25 19:43 UTC by fsamapoor

Following [previous PRs taking advantage of PHP8's constructor property promotion](https://github.com/nextcloud/server/pulls?q=is%3Apr+author%3Afsamapoor+Uses+PHP8%27s+constructor+property+promotion) in `/core/` namespace, I have also made the required adjustments to the classes in `/lib/private/FullTextSearch` namespace.

The improvements in this PRs include:

- Using PHP8's constructor property promotion
- Using early returns
- Adding return types
- Adding types to properties
- Removing redundant docblocks

2023-06-27 18:54 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/IndexDocument.php
> +	protected ?IIndex $index;
Hello @ArtificialOwl. Would you please help me how to type the `$index` and `$access` properties?

The `getIndex(): IIndex` method returns `$this->index` and then there is the `hasIndex(): bool` method that checks if the index is defined (`$this->index !== null`).

Meaning it might be `null`, but the return type of the `getIndex(): IIndex` should remain `IIndex` because of the implemented interface.

So on the one hand it should be typed as nullable, on the other hand, it shouldn't.
Is there anything I am missing here? How should I type these parameters?

2023-07-04 15:53 UTC, icewind1991 approved these changes

2023-10-05 10:56 UTC, come-nc requested changes

2023-10-05 10:56 UTC, come-nc commented on lib/private/FullTextSearch/FullTextSearchManager.php
> +		if ($this->searchService === null) {
Why?
Please revert this change

2023-10-05 10:56 UTC, come-nc commented on lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php
> +	) {
Parameters were mandatory before, you change them to optional

2023-10-06 15:04 UTC, fsamapoor commented on lib/private/FullTextSearch/FullTextSearchManager.php
> +		if ($this->searchService === null) {
Will do. First of all, let me thank you again for your timely reviews and feedback. Really appreciate that.

These are the changes that I suggested a while back. Now that I'm more familiar with your taste, I wouldn't suggest these kinds of changes in my future PRs.

Personally, I find single condition checks a lot more readable and easier to follow, so I try to shape a happy path with  single guard clauses. Nothing wrong with the previous implementation though. Most of these kinds of decisions come down to personal preferences and as long as I shoot my shot to test the waters and be familiar with your preferences, I'm fine with reverting every single suggestion that I make.

2023-10-06 15:06 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php
> +	) {
Thank you. Good catch! Should I remove the default values?

2023-10-06 15:07 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/IndexDocument.php
> +	protected ?IIndex $index;
@come-nc Would you please help me here as well?

2023-10-09 06:53 UTC, Fenn-CS approved these changes

2023-10-09 07:50 UTC, come-nc commented on lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php
> +	) {
Yes, because they were unused anyway I think, they were always overwritten by the constructor

2023-10-09 07:51 UTC, come-nc commented on lib/private/FullTextSearch/Model/IndexDocument.php
> +	protected ?IIndex $index;
I do not have time to dig into it, sorry

2023-10-09 09:19 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/IndexDocument.php
> +	protected ?IIndex $index;
No problem. I'll do my best.

2023-10-10 07:08 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php
> +	) {
Addressed and rebased.

2023-10-10 07:09 UTC, fsamapoor commented on lib/private/FullTextSearch/FullTextSearchManager.php
> +		if ($this->searchService === null) {
Addressed and rebased.

2023-11-07 07:40 UTC, fsamapoor commented
@come-nc Anything I need to change in this PR?

I believe the integration workflow may have timed out.

2023-11-07 08:12 UTC, come-nc commented on lib/private/FullTextSearch/Model/IndexDocument.php
>  	}
For me `index` should be typed `?IIndex`, and maybe `getIndex` will need to have a check and a throw.

2023-11-09 08:07 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/IndexDocument.php
>  	}
Thank you. Please take a look and let me know if I replicated the existing exception behavior in the app correctly.

2023-11-09 09:17 UTC, come-nc approved these changes

2023-11-09 09:19 UTC, come-nc commented
@fsamapoor autoloaders are not up to date, probably because of the new Exception class, please run build/autoloaderchecker.sh and commit the files with new classes.

2023-11-09 10:44 UTC, fsamapoor commented
> @fsamapoor autoloaders are not up to date, probably because of the new Exception class, please run build/autoloaderchecker.sh and commit the files with new classes.

Done.

2023-11-09 10:48 UTC, ChristophWurst commented on lib/composer/composer/autoload_classmap.php
> +    'OCP\\FullTextSearch\\Exceptions\\FullTextSearchIndexNotAvailableException' => $baseDir . '/lib/public/FullTextSearch/Exceptions/FullTextSearchIndexNotAvailableException.php',
this should be committed :+1:

2023-11-09 10:48 UTC, ChristophWurst commented on apps/workflowengine/composer/composer/installed.php
> +        'reference' => 'c8456a1129f98e6ae16ce6adf4ad60044eb3b94a',
this should not

2023-11-09 10:56 UTC, fsamapoor commented on apps/workflowengine/composer/composer/installed.php
> +        'reference' => 'c8456a1129f98e6ae16ce6adf4ad60044eb3b94a',
@ChristophWurst Thank you for reviewing the changes. This is just an example, right? Basically, `lib/composer/composer` should be the only directory subject to change and no other changes in the `apps` namespace should be committed.

2023-11-09 11:07 UTC, ChristophWurst commented on apps/workflowengine/composer/composer/installed.php
> +        'reference' => 'c8456a1129f98e6ae16ce6adf4ad60044eb3b94a',
The apps/*/composer dirs are still to be committed if an app's autoloader class map changes.

It's specifically the `reference` that we don't commit. It constantly changes. If composer files changed, it's helpful to use git add with the patch option like `git add -p` and only select the good parts :)

2023-11-09 11:08 UTC, ChristophWurst commented on lib/public/FullTextSearch/Exceptions/FullTextSearchIndexNotAvailableException.php
> +class FullTextSearchIndexNotAvailableException extends \Exception {
is this used anywhere?

2023-11-09 11:10 UTC, fsamapoor commented on lib/private/FullTextSearch/Model/IndexDocument.php
> +		}
@ChristophWurst This is where we introduced the new exception.

2023-11-09 11:14 UTC, fsamapoor commented on apps/workflowengine/composer/composer/installed.php
> +        'reference' => 'c8456a1129f98e6ae16ce6adf4ad60044eb3b94a',
Yes. All of the changes in the `app` directory were reference changes, so I rebased and did not include them anymore. Thank you for the detailed explanation, Christoph!

2023-11-09 11:20 UTC, ChristophWurst approved these changes

2024-02-23 18:38 UTC, merged