Move Interface Definitions to the ServerContainer
nextcloud/server pull request #3901
Opened 2017-03-17 13:36 UTC by rullzer

Followup of https://github.com/nextcloud/server/pull/3897
Implementation of https://github.com/nextcloud/server/issues/2043#issuecomment-287348294

This should allow us to the interface defintions to the servercontainer. So we don't duplicate everything for each App.

2017-03-17 18:47 UTC, MorrisJobke commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
Why is the false here needed? Shouldn't it try the server container from the app container and done?

2017-03-17 19:01 UTC, rullzer commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
To avoid possible endless loops. Like if you request a non existing class.

2017-03-19 20:05 UTC, LukasReschke approved these changes

2017-03-19 20:16 UTC, BernhardPosselt commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
Is there a way to maybe fix this by overriding the method in the server container instead?

2017-03-19 20:17 UTC, rullzer commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
This is in the servercontainer. The thing is that once we call the query method of the servercontainer we don't know which container called that.

2017-03-19 20:21 UTC, rullzer commented
So 1 thing I did think of is:

Assume that in the server there is a registeredService `Foo` that wants a service `Bar` Injected.

Now if an app `myApp` overwrites `Bar` and wants `Foo` injected. Then that will not happen with this code. Since when looking for `Foo` we no longer search for `Bar` in the apps container.

Mmmm. let me set this back to develop to think some more.

2017-03-19 20:23 UTC, rullzer commented
I'll see if I can come up with some tests to check the behavior we want. Should make discussing a bit easier.

2017-03-19 20:31 UTC, BernhardPosselt requested changes

2017-03-19 20:31 UTC, BernhardPosselt commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
ok, lol my bad :D

2017-03-19 20:31 UTC, BernhardPosselt commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
Ah right, i mean the method above which is defined in the DIContainer

2017-03-19 20:31 UTC, BernhardPosselt commented on lib/private/ServerContainer.php
> +				return $appContainer->query($name, false);
Ah got it, the inerhitance hierarchy is borked. The DIContainer is the base container for apps, however the server container also uses it.

Then I'd say simply subclass it and replace it here: https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/App.php#L68

2017-03-19 20:56 UTC, BernhardPosselt commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +			if ($checkServerContainer === false) {
```php
if (strpos(OC\App::buildAppNamespace($this->query('AppName')), $name) !== 0) {
    return $this->getServer()->query($name);
}
```

2017-03-19 20:58 UTC, BernhardPosselt requested changes

2017-03-19 20:58 UTC, BernhardPosselt commented on lib/private/AppFramework/DependencyInjection/DIContainer.php
> +			if ($checkServerContainer === false) {
Only forwards the request to the server container if the classes lie somewhere else. If you swap out interfaces from the server in your own container it wont hit the server container since you don't hit the catch block

2017-03-20 09:21 UTC, MorrisJobke commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
😱

2017-03-20 09:22 UTC, rullzer commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
yeah yeah fixed. It just still sucks that I can't just do a `git commit -a` because I ran the testsuite.

2017-03-20 11:42 UTC, nickvergessen requested changes

2017-03-20 11:42 UTC, nickvergessen commented on lib/private/Server.php
> +		$this->registerService(IDBConnection::class, function (Server $c) {
Needs adjustments in the unit tests as well
https://github.com/nextcloud/server/blob/b62b82c2ded5a27effb7ef2f40f266f12db8e590/tests/lib/TestCase.php#L141-L141

2017-03-20 11:42 UTC, nickvergessen commented on lib/private/Server.php
> +		$this->registerService(IDBConnection::class, function (Server $c) {
PS its multiple times.

2017-03-20 16:13 UTC, nickvergessen approved these changes

2017-03-20 17:31 UTC, BernhardPosselt commented
Looks good I think 👍

2017-03-20 17:31 UTC, BernhardPosselt approved these changes

2017-03-20 18:40 UTC, MorrisJobke commented
@rullzer Could you have a look why that many integration tests fail?

2017-03-21 07:52 UTC, rullzer commented
@MorrisJobke yes on it. It is because doing it half isn't going to work ;)

2017-03-21 10:06 UTC, merged

2017-03-21 16:18 UTC, icewind1991 commented
💥 causes infinite recursing in DI for me 💥

2017-03-21 16:27 UTC, icewind1991 commented
Seems to be caused by apps where there namespace is not equal to their app id (`files_automatedtagging` vs `\OCA\FilesAutomatedTagging`)

2017-03-21 19:19 UTC, rullzer commented
@icewind1991 mmm fuck. yeah of course that could happen. Let me fix a PR for that. I think we have a way around it.