Refactors lib/private/Lock
nextcloud/server pull request #39108
Opened 2023-07-02 20:09 UTC by fsamapoor

## Summary
Following [previous PRs taking advantage of PHP8's constructor property promotion](https://github.com/nextcloud/server/pulls?q=is%3Apr+author%3Afsamapoor+Uses+PHP8%27s+constructor+property+promotion) in `/core/` namespace, I have also made the required adjustments to the classes in `/lib/private/Lock` namespace.

The improvements in this PR include:

- Using PHP8's constructor property promotion
- Using match expression
- Adding types to properties

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-13 20:11 UTC, Fenn-CS approved these changes
LGTM, thank you!

2023-09-21 07:59 UTC, come-nc requested changes
I dislike the match uses, I find them a lot less readable.

Also there is a problem with how the $ttl property is handled, see comments.

2023-09-21 07:59 UTC, come-nc commented on lib/private/Lock/DBLockingProvider.php
> +		protected int $ttl = 3600,
ttl property is from parent class, it’s ugly to redeclare it here.

2023-09-21 07:59 UTC, come-nc commented on lib/private/Lock/DBLockingProvider.php
> +		protected int $ttl = 3600,
```suggestion
		int $ttl = 3600,
```
Maybe add a constructor to parent class to be able to call parent::__construct($ttl) ?

2023-09-21 07:59 UTC, come-nc commented on lib/private/Lock/MemcacheLockingProvider.php
> +		protected int $ttl = 3600,
Same

2023-09-26 06:35 UTC, fsamapoor commented
> I dislike the match uses, I find them a lot less readable.
> 
> Also there is a problem with how the $ttl property is handled, see comments.

Thank you, Come, for reviewing the PR. I really appreciate the timely feedback. I'm suggesting changes that I believe will improve code readability. However, I have no hard feelings if you prefer to revert or disregard them, as you are the maintainer.

Having said that, I've received multiple positive feedbacks in previous PRs regarding the use of `match` statements, and I personally try to minimize the use of `else` statements as much as I can.

I've moved the `ttl` property to the parent class. Please review the changes and let me know if I should revert the `match` statements.

2023-09-26 07:08 UTC, come-nc commented
> Thank you, Come, for reviewing the PR. I really appreciate the timely feedback. I'm suggesting changes that I believe will improve code readability. However, I have no hard feelings if you prefer to revert or disregard them, as you are the maintainer.
> 
> Having said that, I've received multiple positive feedbacks in previous PRs regarding the use of `match` statements, and I personally try to minimize the use of `else` statements as much as I can.
> 
> I've moved the `ttl` property to the parent class. Please review the changes and let me know if I should revert the `match` statements.

Yes please revert the `match` statements. There is no need for minimizing the `else` statements, `else` is a perfectly fine language construct.
I only find `match` interesting for simple cases where an input value directly implies an output value. When there is more logic than that it quickly looks like perl oneliners.
And I especially find `match(true)` really non-intuitive.

2023-09-26 07:21 UTC, fsamapoor commented
> > Thank you, Come, for reviewing the PR. I really appreciate the timely feedback. I'm suggesting changes that I believe will improve code readability. However, I have no hard feelings if you prefer to revert or disregard them, as you are the maintainer.
> > Having said that, I've received multiple positive feedbacks in previous PRs regarding the use of `match` statements, and I personally try to minimize the use of `else` statements as much as I can.
> > I've moved the `ttl` property to the parent class. Please review the changes and let me know if I should revert the `match` statements.
> 
> Yes please revert the `match` statements. There is no need for minimizing the `else` statements, `else` is a perfectly fine language construct. I only find `match` interesting for simple cases where an input value directly implies an output value. When there is more logic than that it quickly looks like perl oneliners. And I especially find `match(true)` really non-intuitive.

Done. Thank you for the explanation. Squashed the commits as well for a clean history.

2023-09-26 14:58 UTC, come-nc approved these changes

2023-09-26 14:58 UTC, merged