[RFC][OC\Files]: Support QingStor Object Storage
nextcloud/server pull request #3910
Opened 2017-03-18 05:43 UTC by Xuanwo

QingStor Object Storage provides low-cost and reliable online
storage service with unlimited storage space, high read and
write performance, high reliability and data safety, fine-grained
access control, and easy to use API.

This commit will allow nextcloud users to use QingStor Object
Storage as primary storage. And it's a RFC so far, because unit
test, external storage support have not been added.

Signed-off-by: Xuanwo <xuanwo@yunify.com>

2017-03-18 09:33 UTC, LukasReschke requested changes
Thanks a lot for your change request. Generally speaking, can you give us any numbers about the distribution of QingStor? Unless this is really widely used I feel that this should rather be implemented in a dedicated app instead of added to the core.

2017-03-18 14:52 UTC, Xuanwo commented
[QingStor](https://www.qingcloud.com/qingstor) is the Object Storage service provided by [QingCloud](https://www.qingcloud.com/) ,  which is one of the most popular cloud service provider  in China,  it has been in public service for over a year, and it's still growing fast. Besides, we also provide QingStor as on-premise service.
And we are going to publish AppCenter 2.0 service very soon,  AppCenter 2.0 is the application (PaaS/SaaS) framework for QingCloud like AppStore for iOS. We will provide nextcloud as one of the apps in the AppCenter 2.0 platform with no charge on the service itself, instead, we only charge for the resource, e.g. the virtual machine.
From our p.o.v, having the patch merged in will be good for either QingCloud and Nextcloud community, we are looking forward to have the patch merged in.

2017-03-19 23:41 UTC, MorrisJobke commented
I would also go for a dedicated app, because this would bring 19k new lines of code into the core and we want to slim it down.

@rullzer @icewind1991 Is it possible to do this as an app?

2017-03-20 04:09 UTC, osier commented
Hi, @MorrisJobke 

What we want is the NextCloud app running on QingCloud AppCenter uses QingStor bucket as the storage  backend without configuration,  will doing it as an app archieve the goal ?

2017-03-20 07:46 UTC, rullzer commented
*should (tm)* be possible to do as app. Or else we should invest some resources to make it so. @icewind1991 should know more.

2017-03-20 16:51 UTC, icewind1991 commented
I agree that this should be created as a separate app.

Since the objectstore class is directly referenced in the config no separate logic should be needed to register an app provided backend.

The easiest way to automatically have a hosted Nc instance use the object store would be to pre-seed objectstore configuration for a new instance.

2017-04-04 09:52 UTC, rullzer commented
Ok so lets do this as an app. As it keeps the server slimmer and allows for easier updating of the app.

@Xuanwo would you be able to create a first draft of the app?
Feel free to ping @icewind1991 and/or me for feedback. Or join [irc for a chat](https://webchat.freenode.net/?channels=nextcloud-dev)

2017-04-04 09:52 UTC, closed without merging

2017-04-05 03:07 UTC, Xuanwo commented
@rullzer I'll have a try.