Refactors /Metadata, /Migration, and /Net namespaces in /lib/private/
nextcloud/server pull request #39109
Opened 2023-07-02 20:33 UTC by fsamapoor

## Summary

Following [previous PRs taking advantage of PHP8's constructor property promotion](https://github.com/nextcloud/server/pulls?q=is%3Apr+author%3Afsamapoor+Uses+PHP8%27s+constructor+property+promotion) in `/core/` namespace, I have also made the required adjustments to the classes in `/lib/private/Metadata`, `/lib/private/Migration`, and `/lib/private/Net` namespaces.

The improvements in this PR include:

- Using PHP8's constructor property promotion
- Adding return types
- Adding types to properties
- Removing redundant docblocks

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-13 19:45 UTC, Fenn-CS requested changes
You added return types to some functions so you might want to add type hints as well.

Please do verify, that the suggestions I made tie with the expected function types, for example `$app` does not have a function annotation at the top but I am guessing it would be a string.

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/ConsoleOutput.php
> +	public function info($message): void {
```suggestion
	public function info(string $message): void {
```

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/ConsoleOutput.php
> +	public function advance($step = 1, $description = ''): void {
```suggestion
	public function advance(int $step = 1, string $description = ''): void {
```

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/SimpleOutput.php
> +	public function startProgress($max = 0): void {
```suggestion
	public function startProgress(int $max = 0): void {
```

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/SimpleOutput.php
> +	public function advance($step = 1, $description = ''): void {
```suggestion
	public function advance(int $step = 1, string $description = ''): void {
```

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/ConsoleOutput.php
> +	public function startProgress($max = 0): void {
```suggestion
	public function startProgress(int $max = 0): void {
```

2023-07-13 19:45 UTC, Fenn-CS commented on lib/private/Migration/BackgroundRepair.php
> +	protected function run($argument): void {
```suggestion
	protected function run(array $argument): void {
```

2023-07-14 08:14 UTC, fsamapoor commented on lib/private/Migration/ConsoleOutput.php
> +	public function info($message): void {
I would love to, but this is not something that could be done right now. The interfaces do not have parameter type hints at the moment, and changing the interfaces would cause an absolute overhaul in the codebase.

![Screenshot from 2023-07-14 11-31-09](https://github.com/nextcloud/server/assets/4992968/31f3d429-5b4d-4a24-87bb-6bf1e5cb51f6)


I do my best to make improvements as much as I can, with the hope that eventually, the codebase would evolve into much more strict and precise definitions.

Now that we're talking about it, are there any plans in place to update the interfaces with type hints and return types?

2023-07-14 08:14 UTC, fsamapoor commented on lib/private/Migration/ConsoleOutput.php
> +	public function advance($step = 1, $description = ''): void {
Addressed above.

2023-07-14 08:14 UTC, fsamapoor commented on lib/private/Migration/SimpleOutput.php
> +	public function startProgress($max = 0): void {
Addressed above.

2023-07-14 08:14 UTC, fsamapoor commented on lib/private/Migration/SimpleOutput.php
> +	public function advance($step = 1, $description = ''): void {
Addressed above.

2023-07-14 08:14 UTC, fsamapoor commented on lib/private/Migration/ConsoleOutput.php
> +	public function startProgress($max = 0): void {
Addressed above.

2023-07-14 08:19 UTC, fsamapoor commented on lib/private/Migration/BackgroundRepair.php
> +	protected function run($argument): void {
Same. Except for this time, it is an abstract class that has not parameter type hint for the `run` method and not an interface.

2023-07-14 12:46 UTC, fsamapoor commented on lib/private/Migration/BackgroundRepair.php
> +	protected function run($argument): void {
Same. Except for this time, it is an abstract class that does not have the type hint for the `run` method's parameter an not the interface.

2023-07-14 14:40 UTC, Fenn-CS commented on lib/private/Migration/ConsoleOutput.php
> +	public function info($message): void {
No worries for this then.

2023-07-14 14:41 UTC, Fenn-CS commented on lib/private/Migration/BackgroundRepair.php
> +	protected function run($argument): void {
No worries.

2023-07-14 14:43 UTC, Fenn-CS approved these changes

2023-08-17 17:58 UTC, artonge approved these changes

2023-11-07 19:47 UTC, ChristophWurst approved these changes

2023-11-07 19:47 UTC, merged