Refactor lib/private/Remote
nextcloud/server pull request #39163
Opened 2023-07-05 13:26 UTC by shdehnavi

## Summary
The required adjustments have been made to the classes in `/lib/private/Remote ` namespace.

The improvements:

- Using PHP8's constructor property promotion
- Adding return types
- Adding throws types
- Adding types to properties
- Using PHP8's `match` expression instead of `switch`

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-06 18:27 UTC, ChristophWurst commented on lib/private/Remote/Instance.php
>  		$status = $this->getStatus();
getStatus needs finer type annotation for Psalm to acknowledge that this method will always return a string

2023-07-06 18:27 UTC, ChristophWurst commented on lib/private/Remote/Instance.php
>  		$status = $this->getStatus();
status might be `null`

2023-07-06 23:04 UTC, shdehnavi commented on lib/private/Remote/Instance.php
>  		$status = $this->getStatus();
It's addressed in the next commit

2023-07-14 13:46 UTC, nickvergessen commented on lib/private/Remote/User.php
> +	public function getUsedSpace(): int {
this and all other quota related fields can also be float

2023-07-14 13:58 UTC, shdehnavi commented on lib/private/Remote/User.php
> +	public function getUsedSpace(): int {
It's addressed in the next commit

2023-07-17 08:56 UTC, nickvergessen requested changes

2023-07-17 08:56 UTC, nickvergessen commented on lib/private/Remote/Credentials.php
>  	 */
```suggestion
```

2023-07-17 08:56 UTC, nickvergessen commented on lib/private/Remote/Credentials.php
>  	 */
```suggestion
```

2023-07-17 08:56 UTC, nickvergessen commented on lib/private/Remote/Credentials.php
>  	 */
```suggestion
```

2023-07-17 08:56 UTC, nickvergessen commented on lib/private/Remote/Instance.php
> +		$url,
```suggestion
		string $url,
```

2023-07-17 08:56 UTC, nickvergessen commented on lib/private/Remote/User.php
>  	 */
```suggestion
```

Also on all other getters.

2023-07-18 09:47 UTC, nickvergessen commented on lib/private/Remote/User.php
>  	 */
```suggestion
```

Also the rest of the file

2024-08-03 16:43 UTC, closed without merging