refactor core/Middleware
nextcloud/server pull request #39176
Opened 2023-07-05 18:17 UTC by shdehnavi

## Summary
The required adjustments have been made to the classes in the `/core/Middleware ` namespace.

The improvements:

- Adding return types
- Adding throws types
- Adding types to properties

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-18 08:27 UTC, come-nc requested changes

2023-07-18 08:47 UTC, come-nc approved these changes

2023-09-29 08:04 UTC, fsamapoor approved these changes

2023-10-02 08:32 UTC, come-nc commented
> Error: core/Middleware/TwoFactorMiddleware.php:73:7: TypeDoesNotContainType: Cannot resolve types for $controller - OCP\AppFramework\Controller does not contain OCA\TwoFactorNextcloudNotification\Controller\APIController (see https://psalm.dev/056)

2023-10-30 08:29 UTC, closed without merging