## Summary The required adjustments have been made to the classes in `/lib/private/Remote ` namespace.  The improvements:  - Using PHP8's constructor property promotion - Adding return types - Adding throws types - Adding types to properties - Using PHP8's `match` expression instead of `switch`  ## Checklist  - Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting) - [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commitsRefactor core/Command/App
nextcloud/server pull request #39183
Opened 2023-07-06 08:01 UTC by shdehnavi

## Summary
The required adjustments have been made to the classes in `/core/Command/App ` namespace.

The improvements:

- Adding return types
- Adding throws types

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-06 18:30 UTC, ChristophWurst approved these changes

2023-07-17 08:29 UTC, nickvergessen requested changes

2023-07-17 08:29 UTC, nickvergessen commented on core/Command/App/Install.php
> +	 * @throws \Exception
Since this is not a planned throw, but only happens when the server code is broken, I would not document them.

2023-07-18 08:48 UTC, shdehnavi commented on core/Command/App/Install.php
> +	 * @throws \Exception
It's removed in the next commit

2023-07-18 09:44 UTC, nickvergessen commented on core/Command/App/Install.php
> +use Psr\Container\NotFoundExceptionInterface;
unused import

2023-09-29 08:07 UTC, fsamapoor approved these changes

2023-09-29 08:30 UTC, nickvergessen approved these changes

2024-02-23 18:46 UTC, merged