Refactor "substr" calls to improve code readability
nextcloud/server pull request #39216
Opened 2023-07-07 01:24 UTC by shdehnavi

## Summary
Replacing `substr` with `str_starts_with` and `str_ends_with` in the `/lib/private` namespace to improve code readability

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-20 07:49 UTC, fsamapoor approved these changes
Much much better. Thanks!
Other than the comment I left, looks good to me.

2023-07-20 07:49 UTC, fsamapoor commented on lib/private/DateTimeFormatter.php
> +		if (!str_ends_with($format, '*') && !str_ends_with($format, '*')) {
Aren't these the same?

2023-07-20 12:52 UTC, shdehnavi commented on lib/private/DateTimeFormatter.php
> +		if (!str_ends_with($format, '*') && !str_ends_with($format, '*')) {
Thank you, it's addressed in the next commit

2023-08-17 17:43 UTC, artonge approved these changes

2023-08-17 17:43 UTC, artonge commented on lib/private/DateTimeFormatter.php
> +		if (!str_ends_with($format, '*')) {
```suggestion
		if (!str_ends_with($formatDate, '^') && !str_ends_with($formatDate, '*')) {
```

I think the duplication was due to a bad copy-pasting. Having `*` or `^` at the end of the format seem on purpose and make sense if you look at the documentation of the library that we use. Same as on line 292.

https://punic.readthedocs.io/en/3.4.0/_static/api/class-Punic.Calendar.html
![Screenshot from 2023-08-17 19-38-51](https://github.com/nextcloud/server/assets/6653109/372166fb-f100-49b5-8e27-71b61cf3968c)

2023-09-05 13:00 UTC, come-nc requested changes

2023-09-07 07:40 UTC, come-nc approved these changes

2023-09-21 14:34 UTC, icewind1991 approved these changes

2023-09-21 14:34 UTC, merged