Refactor core/Controller
nextcloud/server pull request #39212
Opened 2023-07-07 00:53 UTC by shdehnavi

## Summary
The required adjustments have been made to the classes in `/core/Controller ` namespace.

The improvements:

- Adding return types
- Adding throws types
- Adding types to properties
- Replacing qualifiers with imports
- Updating doc blocks
- Using PHP8's `str_starts_with` and `str_ends_with` instead of `substr`

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-14 14:06 UTC, shdehnavi commented on core/Controller/LoginController.php
> +	 * @return Response
You are right, It's addressed in the next commit

2023-07-14 14:06 UTC, shdehnavi commented on core/Controller/PreviewController.php
> +	 * @param string $mode
It's addressed in the next commit

2023-07-14 14:09 UTC, shdehnavi commented on core/Controller/PreviewController.php
> +		string $mode = 'fill'): DataResponse|Response|FileDisplayResponse {
it's addressed in the next commit

2023-07-17 08:47 UTC, artonge commented on core/Controller/ClientFlowLoginController.php
> +	 * @return Response|StandaloneTemplateResponse|RedirectResponse
As nickvergessen said, 

> usually we remove types from the doc block when they are reflected in the methods signature as they are just error prone to be missed on updates.

So you can remove the doc block comments for all methods that now have their type in their signature :)

2023-07-17 08:50 UTC, nickvergessen requested changes

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/ClientFlowLoginController.php
> +										string $clientIdentifier = ''): Response|StandaloneTemplateResponse|Http\RedirectResponse {
```suggestion
										string $clientIdentifier = ''): Response|StandaloneTemplateResponse|RedirectResponse {
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/ContactsMenuController.php
>  	 * @return JSONResponse|\JsonSerializable
```suggestion
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/CssController.php
>  	public function getCss(string $fileName, string $appName): Response {
```suggestion
	 * @return FileDisplayResponse|NotFoundResponse
	 */
	public function getCss(string $fileName, string $appName): FileDisplayResponse|NotFoundResponse {
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/JsController.php
>  	public function getJs(string $fileName, string $appName): Response {
```suggestion
	 * @return FileDisplayResponse|NotFoundResponse
	 */
	public function getJs(string $fileName, string $appName): FileDisplayResponse|NotFoundResponse {
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/LoginController.php
>  	 * @return RedirectResponse
```suggestion
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/PreviewController.php
> +	 * @throws NotPermittedException
```suggestion
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/PreviewController.php
> +	 * @throws InvalidPathException
```suggestion
	 * @return DataResponse|FileDisplayResponse
```

or you remove the whole doc block and change the end of the signature to:
```
string $mode) : DataResponse|FileDisplayResponse {
```

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/ProfileApiController.php
> +	 * @throws Exception
```suggestion
	 * @throws OCSBadRequestException
	 * @throws OCSForbiddenException
	 * @throws OCSNotFoundException
```

The other things should not be needed as they are indicated by the method signature or not planned to happen/be catched (general exception)

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/TwoFactorChallengeController.php
> +	 * @throws \Exception
```suggestion
```
Not part of the API.

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/TwoFactorChallengeController.php
> +	 * @throws \Exception
```suggestion
```
Not part of the API.

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/TwoFactorChallengeController.php
> +	 * @throws \Exception
```suggestion
```
Not part of the API.

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/TwoFactorChallengeController.php
> +	 * @throws \Exception
```suggestion
```
Not part of the API.

2023-07-17 08:50 UTC, nickvergessen commented on core/Controller/WellKnownController.php
>  	 * @return Response
```suggestion
```

2023-07-19 12:31 UTC, shdehnavi commented on core/Controller/ClientFlowLoginController.php
> +	 * @return Response|StandaloneTemplateResponse|RedirectResponse
It's addressed in the commit

2023-07-19 18:49 UTC, nickvergessen requested changes

2023-07-19 18:49 UTC, nickvergessen commented on core/Controller/LoginController.php
> +use OCP\AppFramework\Http\Response;
I don't see this being used in the diff. Is it an unused import?

2023-07-19 18:49 UTC, nickvergessen commented on core/Controller/PreviewController.php
> +	 * @throws InvalidPathException
See this

2023-07-19 18:49 UTC, nickvergessen commented on core/Controller/PreviewController.php
> +	 * @throws NotPermittedException
See this

2023-07-19 18:49 UTC, nickvergessen commented on core/Controller/ProfileApiController.php
> +	 * @throws Exception
another open comment here

2023-07-19 18:49 UTC, nickvergessen commented on core/Controller/TwoFactorChallengeController.php
> +	public function solveChallenge(string $challengeProviderId, string $challenge, string $redirect_url = null): RedirectResponse {
```suggestion
	public function solveChallenge(string $challengeProviderId, string $challenge, ?string $redirect_url = null): RedirectResponse {
```

2024-08-03 16:43 UTC, closed without merging