Refactor comments app
nextcloud/server pull request #39236
Opened 2023-07-07 18:57 UTC by shdehnavi

## Summary
The required adjustments have been made to the `comments` app.

The improvements:

- Using PHP8's constructor property promotion
- Adding return types
- Adding types to properties
- Updating doc blocks
- Converting `isset` ternary to null coalescing operator

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-07-17 08:26 UTC, nickvergessen requested changes

2023-07-17 08:26 UTC, nickvergessen commented on apps/comments/lib/Activity/Listener.php
>  	 */
```suggestion
```

2023-07-17 08:26 UTC, nickvergessen commented on apps/comments/lib/Activity/Provider.php
> +		protected IURLGenerator $url, protected ICommentsManager $commentsManager,
```suggestion
		protected IURLGenerator $url,
		protected ICommentsManager $commentsManager,
```

2023-07-17 08:26 UTC, nickvergessen commented on apps/comments/lib/Controller/NotificationsController.php
>  	 */
```suggestion
```

2023-07-17 08:26 UTC, nickvergessen commented on apps/comments/lib/Search/Result.php
> +		public string $authorName,
Please keep this as before, so the `@deprecated 20.0.0` annotation is still on the member

2023-07-17 15:29 UTC, shdehnavi commented on apps/comments/lib/Search/Result.php
> +		public string $authorName,
It's addressed in the next commit

2023-07-17 15:31 UTC, shdehnavi commented on apps/comments/lib/Activity/Listener.php
>  	 */
It's addressed in the next commit

2023-07-17 15:31 UTC, shdehnavi commented on apps/comments/lib/Activity/Provider.php
> +		protected IURLGenerator $url, protected ICommentsManager $commentsManager,
It's addressed in the next commit

2023-07-17 15:31 UTC, shdehnavi commented on apps/comments/lib/Controller/NotificationsController.php
>  	 */
It's addressed in the next commit

2023-07-18 09:40 UTC, nickvergessen approved these changes

2023-09-28 05:45 UTC, fsamapoor approved these changes

2023-09-28 06:17 UTC, skjnldsv approved these changes

2023-09-28 07:27 UTC, merged

2023-09-28 07:27 UTC, skjnldsv commented
Cypress fails because fork master is not up to date, merging...

2023-09-28 07:43 UTC, fsamapoor commented
> Cypress fails because fork master is not up to date, merging...

Thank you for taking the time to explain why the Cypress tests have been failing for the past weeks.