Refactor lib/private
nextcloud/server pull request #39249
Opened 2023-07-09 09:14 UTC by shdehnavi

## Summary
The required adjustments have been made to the following classes under `/lib/private ` namespace:
- `PreviewManager.php`
- `Repair.php`
- `RedisFactory.php`
- `Search.php`
- `Server.php`
- `ServerContainer.php`

The improvements:

- Using PHP8's constructor property promotion
- Adding return types
- Adding types to properties
- Updating doc blocks

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-08-14 16:54 UTC, fsamapoor commented
Could you please resolve the conflicts?

2024-05-02 15:38 UTC, skjnldsv approved these changes

2024-05-06 07:57 UTC, come-nc requested changes

2024-05-06 10:47 UTC, nickvergessen commented on lib/private/Server.php
> +	public function getCalendarManager(): \OCP\Calendar\IManager {
deprecated since 20 means we can even remove it when not actively used in shipped apps or server  :P

2024-08-03 16:43 UTC, closed without merging