Bump CS Fixer rules to follow latest Nextcloud standards
nextcloud/server pull request #39271
Opened 2023-07-10 12:04 UTC by Altahrim

## Summary
Update PHP CS coding standards to lastest Nextcloud standards

2023-07-17 14:55 UTC, come-nc reviewed
I think you should also change platform to php: 8.0 in the same composer.json file

2023-07-18 08:10 UTC, come-nc commented on core/Migrations/Version13000Date20170718121200.php
> +		//		}
Just remove the dead code, no?

2023-07-18 08:10 UTC, come-nc commented on core/Migrations/Version16000Date20190207141427.php
> +			//			$table->addUniqueIndex(['collection_id', 'resource_type', 'resource_id'], 'collres_unique_res');
Same

2023-07-18 08:10 UTC, come-nc commented on core/Migrations/Version17000Date20190514105811.php
> +			//			$table->addUniqueIndex(['fileid'], 'fce_fileid_idx');
Same

2023-07-18 08:10 UTC, come-nc commented on core/Migrations/Version20000Date20201109081915.php
> +		//		$result = $this->ensureColumnIsNullable($schema, 'credentials', 'user') || $result;
Same

2023-07-18 12:12 UTC, nickvergessen requested changes

2023-07-18 12:12 UTC, nickvergessen commented on core/Migrations/Version13000Date20170718121200.php
> -//			$table->addUniqueIndex(['objecttype', 'objectid', 'systemtagid'], 'mapping');
Please keep all the comments in migration files.
They are useful search results.
When dealing with old database schemas it's very useful to be able to quickly search if something is custom, or we modified/dropped it in a later version, etc.

2023-07-18 12:12 UTC, nickvergessen commented on core/Migrations/Version13000Date20170718121200.php
> -
Keep

2023-07-18 12:12 UTC, nickvergessen commented on core/Migrations/Version17000Date20190514105811.php
> -//			$table->addUniqueIndex(['fileid'], 'fce_fileid_idx');
Keep

2023-07-18 12:12 UTC, nickvergessen commented on core/Migrations/Version20000Date20201109081915.php
> -//		$result = $this->ensureColumnIsNullable($schema, 'credentials', 'user') || $result;
Keep

2023-07-18 12:12 UTC, nickvergessen commented on core/Migrations/Version13000Date20170718121200.php
> +		//		}
No :(

2023-07-18 12:14 UTC, nickvergessen commented on tests/lib/Encryption/ManagerTest.php
> -//	/**
SHould not be deleted? Someone should reenable and then fix the test instead? :P

2023-07-18 12:15 UTC, nickvergessen commented on tests/lib/Files/FilesystemTest.php
> -//		\OC\Files\Filesystem::file_put_contents('/foo', 'foo');
I would keep/fix those. They seem to hint some debugging steps in case the test doesn't work anymore

2023-07-18 13:37 UTC, nickvergessen approved these changes

2023-07-18 13:58 UTC, come-nc approved these changes

2023-07-20 08:35 UTC, come-nc commented
@skjnldsv You’ve put milestone 29 for this on purpose? Does it mean we should wait for 28 branch off before merging?

2023-08-30 10:48 UTC, nickvergessen commented
> Does it mean we should wait for 28 branch off before merging?

The current idea is to do and merge it directly before the branch-off to break as few PRs as possible and to be still able to somewhat normally use the backport bot to stable28 then

2023-09-26 10:05 UTC, come-nc requested changes

2023-09-26 10:05 UTC, come-nc commented on vendor-bin/cs-fixer/composer.json
> +			"php": "8.0"
```suggestion
			"php": "8.1"
```

2023-10-10 04:51 UTC, nickvergessen commented on lib/composer/bamarni/composer-bin-plugin/.github/workflows/phpstan.yml
Install with `--no-dev` ?

2023-10-10 04:54 UTC, nickvergessen commented on vendor-bin/cs-fixer/composer.json
> +			"php": "8.1"
Currently it seems like 28 has to continue to support 8.0.2+

2023-10-30 15:25 UTC, Altahrim commented on lib/composer/bamarni/composer-bin-plugin/.github/workflows/phpstan.yml
Well spotted!
They were not supposed to be there :)

2023-11-23 09:13 UTC, nickvergessen commented
Now is the time

2023-11-23 09:15 UTC, nickvergessen commented
rebasing with dropping the `cs:fix` and running it afterwards again

2023-11-23 09:35 UTC, blizzz approved these changes

2023-11-23 10:40 UTC, merged