Add optional to add backtrace to log items
nextcloud/server pull request #39275
Opened 2023-07-10 13:33 UTC by icewind1991

Disabled by default (for now?) due to the increased log size.

2023-07-14 16:34 UTC, blizzz approved these changes

2023-07-16 09:16 UTC, Fenn-CS requested changes

2023-07-16 09:16 UTC, Fenn-CS commented on lib/private/Log.php
> +		$logBacktrace = $this->config->getValue('log.backtrace', false);
How does anyone know that this config option exists?

- Is it documented?
- Is it in the config template?

Otherwise, someone has to know this snippet of code exists to attempt using that which means it could potentially be dead-code without the above?

2023-07-17 13:08 UTC, blizzz commented
Added an entry to config.sample.php (which is auto-synced to docs.nc.c).

2023-07-20 16:28 UTC, Pytal approved these changes

2023-07-20 16:29 UTC, AndyScherzinger approved these changes

2023-07-20 17:30 UTC, merged