files_trashbin: Add OpenAPI spec
nextcloud/server pull request #39320
Opened 2023-07-11 15:15 UTC by provokateurin

## Summary

From https://github.com/nextcloud/server/pull/36666. Adds the necessary annotations and descriptions.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-07-11 15:22 UTC, bigcat88 requested changes

2023-07-11 15:22 UTC, bigcat88 commented on apps/files_trashbin/openapi.json
> +                            "default": 1
maybe `-1`?

2023-07-11 15:31 UTC, provokateurin commented on apps/files_trashbin/openapi.json
> +                            "default": 1
Fixed it, there was a missing minus when parsing the default value.

2023-07-11 15:33 UTC, bigcat88 approved these changes

2023-07-12 01:21 UTC, Pytal commented on apps/files_trashbin/openapi.json
> +                            "default": 0
```suggestion
                            "type": "boolean",
                            "default": false
```

2023-07-12 01:21 UTC, Pytal commented on apps/files_trashbin/openapi.json
> +                        "description": "Whether to crop the preview",
```suggestion
                        "description": "Whether to not crop the preview",
```

2023-07-12 05:17 UTC, provokateurin commented on apps/files_trashbin/openapi.json
> +                            "default": 0
This is due to a quirk how booleans are handled by the server. Any value will result in `true`, except when sending a `0` which will turn into `false`. In theory [`allowEmptyValue`](https://swagger.io/docs/specification/describing-parameters/#nullable) exists and could be used to describe this case with the value being a boolean, but none of the generators that are widely used implement it (https://github.com/search?q=repo%3AOpenAPITools%2Fopenapi-generator%20allowEmptyValue&type=code). For the clients that are generated with them all boolean parameters would be broken, that's why the integer variant is used here.

2023-07-12 07:29 UTC, skjnldsv approved these changes

2023-07-13 01:30 UTC, Pytal approved these changes

2023-07-13 05:17 UTC, merged