Make .devcontainer independent of processor architecture
nextcloud/server pull request #39464
Opened 2023-07-18 16:03 UTC by tsdicloud

* Resolves: https://github.com/nextcloud/server/issues/39461[#39461]

## Summary
Removed hardcoded arm64 architecture in install script within Dockerfile by an automatic architecture detection.
The containerization will now tear in packages for the detected architecture (if available), which makes Apple Silicone
working.

## Checklist
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Run Dev Container on Apple Silicone and Intel now.

2023-07-18 16:06 UTC, szaimen approved these changes

2023-07-18 17:05 UTC, Pytal approved these changes

2023-07-18 17:54 UTC, susnux approved these changes

2023-09-05 14:08 UTC, joshtrichards requested changes
Remove the personal/proprietary settings that don't belong in the PR.

2023-09-05 14:08 UTC, joshtrichards commented on .devcontainer/nmcsetup.sh
This PR appears to include a bunch of unrelated changes. Was that intentional?

2023-11-06 21:22 UTC, AndyScherzinger commented on .devcontainer/nmcsetup.sh
I'd say keep them as an example for custom setup, like separated here, which can be adapted by others

2023-11-06 21:24 UTC, AndyScherzinger commented on .devcontainer/nmcsetup.sh
@tsdicloud feel free to remove the nmc specific files of course, since I would expect you wouldn't want them in the Nextcloud repo instead of just the nmc one

2024-08-03 16:43 UTC, closed without merging