Improve sharing flow
nextcloud/server pull request #39472
Opened 2023-07-19 01:13 UTC by Fenn-CS

## Summary

Resolves: https://github.com/nextcloud/server/issues/26691

2023-08-07 00:21 UTC, Fenn-CS commented
# Share Details View

Share details | Share advanced (optional checks off) | Share details advanced (optional checks on)
-|-|-
![share-details](https://github.com/nextcloud/server/assets/14317775/f7683e10-267f-4b04-a4f5-b44388be2fd0) | ![share-details-advanced-checks-off](https://github.com/nextcloud/server/assets/14317775/62fafa8c-7f38-43d8-bf36-c2e5d9c86137) | ![share-details-advanced](https://github.com/nextcloud/server/assets/14317775/6fc7c616-4ebb-4375-814d-b715bc697e6f)

2023-08-07 19:20 UTC, nimishavijay commented
Looks super nice! 🚀 :) 
Some feedback from my side:
- [ ] The folder name under "Edit share link" can be removed, since it's already there in the top of the sidebar. Instead, if there is a share label set that can be shown in place of the folder name
- [ ] So the folder icon next to it can also be replaced by a [share icon](https://fonts.google.com/icons?selected=Material%20Icons%3Ashare%3A) 
- [ ] We could also add a few pixels of spacing between the icon and the text, and remove a bit of spacing between the "Edit share link" and its subline if it's shown. 
- [ ] The icon for the "Advanced settings" button can be the [expand more icon](https://fonts.google.com/icons?selected=Material%20Icons%3Aexpand_more%3A)
- [ ] If the advanced settings are open, will clicking on "Advanced settings" button hide it again? Ideally it should, and in that case we can use the [expand less icon](https://fonts.google.com/icons?selected=Material%20Icons%3Aexpand_less%3A) instead
- [ ] The "Delete link" button can be styled to look like a tertiary icon-only button
- [ ] Generally we use sentence case for wording, so a captial letter only at the starting of the wording for each element:
  - [ ] Edit Share Link --> Edit share link
  - [ ] View only (Default) --> View only (default)
  - [ ] File Drop --> File drop
  - [ ] Advanced Settings --> Advanced settings

That's all from my side! It already looks great! :)

2023-08-08 07:39 UTC, jancborchardt reviewed
> The folder name under "Edit share link" can be removed, since it's already there in the top of the sidebar. Instead, if there is a share label set that can be shown in place of the folder name

- [ ] Here is also the place to show what type the share is. With a person (show the avatar on the left), or a link share (show link icon on the left).
- [ ] And the buttons on the bottom need to be sticky if the viewport is too small.

2023-08-09 19:18 UTC, Fenn-CS commented
### Share flow updates

- Includes "missing detail" add here : https://github.com/nextcloud/server/issues/26691#issuecomment-1671537196
- [x] The folder name under "Edit share link" can be removed, since it's already there in the top of the sidebar. Instead, if there is a share label set that can be shown in place of the folder name
- [x] So the folder icon next to it can also be replaced by a [share icon](https://fonts.google.com/icons?selected=Material%20Icons%3Ashare%3A) 
- [x] The "Delete link" button can be styled to look like a tertiary icon-only button
- [x] Generally we use sentence case for wording, so a captial letter only at the starting of the wording for each element:
- [x] Some function wiring on the UI


Share view| Share details | Share advanced (most optional checks off) | Share details advanced (more optional checks on)
-|-|-|-
![share-flow-1](https://github.com/nextcloud/server/assets/14317775/5845eb21-c59a-45db-859e-399dd5f90298) | ![share-flow-2](https://github.com/nextcloud/server/assets/14317775/2b5b7cb4-d06e-4c1c-b6c1-87c5d8d29f66) | ![share-flow-3](https://github.com/nextcloud/server/assets/14317775/e7b7b341-e90e-4135-afb9-5d9722772bdc) | ![share-flow-4](https://github.com/nextcloud/server/assets/14317775/da2b4e1b-a0cb-4e88-b905-c86ecd282051)

2023-08-10 09:52 UTC, jancborchardt requested changes
- [ ] **When adding a new person or creating a new link, the detail view should always be opened. The share should only be created when you click "Share & copy link"**
- [ ] **The "File drop" option should not show up for internal shares as we only have that for share links**
- [ ] **"Share link" should use the same share details interface as internal shares**

## Share view
- [ ] The arrow-down icon is too complex, it should only be a simple triangle icon as per mockup: https://pictogrammers.com/library/mdi/icon/triangle-small-down/
- [ ] The "Can view/edit/share/file drop" is too wide, only needs to be as wide as the text is.
- [ ] The text of the "Share link" and the person "Ambe Bandolo" does not left-align with each other
- [ ] Also the circles on the left for Share link and avatar are much bigger than before, leading to them being bigger than the 2 below for "Others with access" and "Internal link". All of them should be same size
- [ ] "Advanced Settings" --> "Advanced settings" (sentence case, only first word capitalized)

## Share details & advanced
- [ ] **Instead of duplicating the share icon left of "Share with [Person]", if possible the avatar should be shown there.**
- [ ] **The subline can be removed, as the filename already shows on the top**
- [ ] **The list entry "Custom permissions" as per the spec: "Does not show by default and is merely informative." Only if "custom permissions" in advanced settings are checked and modified. And if custom permissions are set, that should also be reflected in the top selector by "Custom settings" being selected.**
- [ ] **The subline of "Custom permissions" is intended to reflect what is actually set in the custom permissions. So in the 4th screenshot it should say "Read". If that is too complex, better remove the subline altogether.**
- [ ] **"Delete link" should be renamed to "Delete share" (both for links and internal shares)**
- [ ] **Clicking "Delete link" should also close the detail view**
- [ ] The "Advanced" settings can just always be expanded and not toggleable.
- [ ] We need to make sure that the "Cancel" and "Share & copy link" are sticky on the bottom
- [ ] The "Cancel" button being half the width looks a bit massive. Could you make both buttons only be as wide as their contents, Cancel flush left and "Share & copy link" flush right?


I bolded the ones I consider most important. :)

2023-08-10 11:12 UTC, szaimen requested changes, later dismissed
The new sharing flow does not seem to work for link shares yet:
<details><summary>Screenshot</summary>
<p>
<img src="https://github.com/nextcloud/server/assets/42591237/2f4402e5-95be-4d11-a82c-7524047c12d6" />
</p>
</details>

2023-08-14 13:53 UTC, jancborchardt requested changes, later dismissed
Further things which came up in the Hub 6 design review:
→ All moved up to the other review at https://github.com/nextcloud/server/pull/39472#pullrequestreview-1571500093

2023-08-16 11:40 UTC, Fenn-CS commented
Share flow updates

Share view| Share details | Share advanced (most optional checks off) | Share details advanced (more optional checks on)
-|-|-|-
 Coming soon | ![share-2](https://github.com/nextcloud/server/assets/14317775/d91e085e-e5d0-4366-9f17-ef2536987ee2) | ![share-3](https://github.com/nextcloud/server/assets/14317775/dabc93ae-b64b-4df6-9587-0a505fc45ec3) | ![share-4](https://github.com/nextcloud/server/assets/14317775/1702b161-1f51-48d1-92b1-aab17747a06a)

2023-08-16 14:56 UTC, artonge commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +			options: ['View only', 'Can edit', 'File drop'],
Those need to be translated.

2023-08-16 14:56 UTC, artonge commented on apps/settings/src/components/UserList/UserRow.vue
Copy-pasting from the user list? Is this needed here?

2023-08-16 16:18 UTC, juliushaertl reviewed
A first round of code comments

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					{{ t('file_sharing', 'Share & copy link') }}
Copy is not implemented yet, but this raises a question for me to @jancborchardt:

Should it be the same button when creating new shares for users/groups/circles? Should it then copy the internal link?

In addition, should the button have a different label when updating an existing share or just always stick with "Share" as the action, even though the share might already exist?

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			let title = 'Share with '
Should be translated, ideally also with the shareWithDisplayName parameter included, so that translators have context. This should work, but we may nee to think about a fallback for types that don't have a shareWithDisplayName

```suggestion
			let title = t('Share with {displayName}', { displayName: this.share.shareWithDisplayName })
```

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingTab.vue
> +			this.showSharingDetailsView = !this.showSharingDetailsView
@jancborchardt  The showSharingDetailsView should also be reset if switching to a different file in the sidebar i think, right? Question then is how to handle unsaved changes to the share data. Blocking the change might get tricky.

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			sharingPermission: 'rw',
Would be nice to have constants for different predefined share permissions that not use a bitmask

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<span style="display: none;"><label /></span>
Probably not needed?

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<NcInputField :value="shareLabel" :label-visible="true" :label="t('file_sharing', 'Share label')" />
Share labels are only possible for links/email shares as far as I see

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<NcCheckboxRadioSwitch :checked.sync="hideDownload">
Only possible for link/email shares

2023-08-16 16:18 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<NcCheckboxRadioSwitch :checked.sync="setPassword">
Only possible for link/email shares

2023-08-16 17:05 UTC, juliushaertl commented
Missing functional aspects from a quick test run:

- [ ] Creating shares does not work
- [ ] Editing user shares does not work -> leads to empty sidebar
- [ ] Updating shares not tested
- [ ] Quick permission change dropdown doesn't work on link/email shares
- [ ] QA: Needs side by side testing if all old options are possible or also properly limited with the new one

2023-08-16 17:08 UTC, juliushaertl commented
@jancborchardt What I couldn't find in the spec was how additional share links can be created. Currently this is in the three dots menu next to an existing share link, but from my understanding the icon should lead to the details view now. How would a user then add an additional link?

2023-08-16 17:41 UTC, Fenn-CS commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				title = title + this.share.shareWithDisplayName
Thanks, done.

2023-08-17 10:12 UTC, jancborchardt commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					{{ t('file_sharing', 'Share & copy link') }}
Yes, good points:
**For the MVP, we can just go for the wording: "Save share"** @Fenn-CS – then it works for both internal and link shares and copy doesn’t need to be implemented.

> Should it be the same button when creating new shares for users/groups/circles? Should it then copy the internal link?

That would be ideal, but yes probably something for next iteration.

2023-08-17 10:17 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			sharingPermission: 'rw',
https://github.com/nextcloud/server/blob/f3fa006484c6dc7f3dd2504ea005dc3689ed4d44/apps/files_sharing/src/lib/SharePermissionsToolBox.js#L32-L37

2023-08-17 10:23 UTC, jancborchardt commented on apps/files_sharing/src/views/SharingTab.vue
> +			this.showSharingDetailsView = !this.showSharingDetailsView
> The showSharingDetailsView should also be reset if switching to a different file in the sidebar i think, right?

Yep, that needs to be reset @Fenn-CS.

- MVP could be to just drop the changes as if "Cancel" was pressed
- For the future we can think of showing a notice

2023-08-17 10:26 UTC, jancborchardt commented
> @jancborchardt What I couldn't find in the spec was how additional share links can be created. Currently this is in the three dots menu next to an existing share link, but from my understanding the icon should lead to the details view now. How would a user then add an additional link?

As discussed in the call, once the share link is ported to the new flow, the 3 dot menu should have 2 entries:
- Link settings
- Add another link

2023-08-17 10:27 UTC, jancborchardt commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					{{ t('file_sharing', 'Share & copy link') }}
This is done already by @Fenn-CS :)

2023-08-18 08:31 UTC, juliushaertl commented on apps/files_sharing/src/mixins/SharesMixin.js
> +		isExternalShare() {
external share is used as internal wording for ferderated shares in the backend, maybe rather call this `isPublicShare`?

2023-08-18 08:33 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +		},
I was thinking about this approach a bit and would have a suggestion to simplify this. We could only have a `share` property which then always has the same structure independent of if the share already exists or not. The only difference would be that a non-existing share that is in creating would not have share id yet as it doesn't exist in the backend. This could simplify the overal logic quite a bit. What do you think about that?

2023-08-18 10:31 UTC, Fenn-CS commented
From @juliushaertl (Putting this as a comment to follow up later if can't fit in here)

> I was thinking about this approach a bit and would have a suggestion to simplify this. We could only have a share property which then always has the same structure independent of if the share already exists or not. The only difference would be that a non-existing share that is in creating would not have share id yet as it doesn't exist in the backend. This could simplify the overal logic quite a bit. What do you think about that?

2023-08-18 10:37 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			this.queueUpdate('permissions')
I think the attributes would be missing for the "allow download" permission on internal shares, see https://github.com/nextcloud/server/blob/stable27/apps/files_sharing/src/components/SharingEntry.vue#L446-L450 for reference

2023-08-18 11:55 UTC, marcoambrosini reviewed
Sorry for the late review, for some reason this pr doesn't run properly in my development environment so @Fenn-CS kindly walked me through the feature in a call. I also thought there was no time for making design adjustments anymore, that's why I didn't comment on the mockups before. So anyway here are my thoughts:

The main issue I find here is the attempt to pack complex share settings in a sidebar tab. 
  
I think the use of a sidebar is warranted if 2 conditions are met: 
**1) I need to to perform actions related to the content** (the files list in this case) 
**2) There's a usability gain given by not loosing sight of the content while I use the functionality in the sidebar**
If these are not both met, we should put complex flows front and center, give proper spacing to everything and take the attention away from the rest of the UI.

In this case, while it's maybe nice to be able to have a list of shares in the sidebar, **once we want to edit a share and dive into its settings, the files list doesn't matter anymore, so condition 2) is not met.**
At that point I don't need to see the files list, so we're free to bring up (you guessed it) a nice spacious dialog where we can articulate all the complexity. 
I think that's the reason why all our competitors do it that way.

2023-08-22 07:31 UTC, juliushaertl commented on apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
> +		background-color: #ffffff;
Please use css variables for any hardcoded color values, otherwise dark mode is broken:

![Screenshot 2023-08-22 at 09 28 19](https://github.com/nextcloud/server/assets/3404133/2573060c-c4c3-42f2-8960-46239fdc01a2)

2023-08-22 07:32 UTC, juliushaertl commented on apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
> +		<div v-if="showDropdown" class="share-select-dropdown-container">
Follow up: This is not accessible, we should use proper elements to make this keyboard navigatable and usable by screen readers

2023-08-24 15:03 UTC, Fenn-CS commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					@update:value="onExpirationChange" />
With `NcActionInputFiled` providing `new Date(share.expireDate)` would initialize the component correctly this does not work for `NcInputFiled` on the other hand `NcDateTimePicker` does not respond to the `update:value` event.

So I have both inputs so testers can see how each behave side by side and provide me with some context on what could be going on here.

cc: @artonge @juliushaertl

2023-08-29 08:32 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			} else if (this.config.isDefaultRemoteExpireDateEnabled && isRemoteShare) {
```suggestion
			} else if (this.config.isDefaultRemoteExpireDateEnabled && this.isRemoteShare) {
```

2023-08-29 08:34 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			if (this.config.isDefaultInternalExpireDateEnabled && (this.isGroupShare || this.isUserShare)) {
I'd prefer switching the condition order to make this easier to understand:

```suggestion
			if ((this.isGroupShare || this.isUserShare) && this.config.isDefaultInternalExpireDateEnabled) {
```

Same for the others

2023-08-29 08:41 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<NcCheckboxRadioSwitch :disabled="canChangeHideDownload"
Should only be visible on link or mail shares

2023-08-29 08:59 UTC, juliushaertl commented on apps/files_sharing/src/mixins/SharesMixin.js
> +			const shareType = this.share.shareType ?? this.share.type
Why are there two different properties for that?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/components/SharingEntryQuickShareSelect.vue
> +			this.selectedOption = this.preSelectedOption
Couldn't `selectedOption` be initialized in `data` ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/components/SharingInput.vue
> -				id: `${result.value.shareType}-${result.value.shareWith}`,
Not needed anymore ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/components/SharingInput.vue
> -				id: `${result.value.shareType}-${result.value.shareWith}`,
Is it to discriminate whether the share exists or not in `ShareDetails.js` ?
If so, I would instead add a property as this `id` might be used somewhere.

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/mixins/SharesMixin.js
> +			const shareType = this.share.shareType ?? this.share.type
Same, why are there two ways of accessing the type ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			<span>
Useless `span` ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<h1>{{ title }}</h1>
`h1` might be confusing here. I would use a `div`. @JuliaKirschenheuter do you have an opinion ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<NcInputField v-if="isPublicShare"
Use `NcTextField` https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcInputField/NcInputField.vue#L25-L29

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +		},
Don't `shareRequestValue` contains `fileInfo` and `share` ? Isn't it redundant ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			setCustomPermissions: false,
I would rename to `showCustomPermissions`

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			sharingPermission: BUNDLED_PERMISSIONS.ALL.toString(),
Couldn't this be inferred from the share's permissions ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			advancedSectionAccordionExpanded: false,
Just to keep a consistent naming scheme: `showAdvancedSettings`

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					this.share.password = await GeneratePassword()
There might be a simpler way of doing this, like generating the password when the share object is created. But this works.

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				if (this.isNewShare && !this.allowsFileDrop) {
Why is this condition needed ? Or why does the share object does not contain the permissions ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +					|| new Date(new Date().setDate(new Date().getDate() + 1))
There might be an easier way of doing this with `@nextcloud/moment`

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				return new Date(new Date().setDate(new Date().getDate() + 1 + this.config.defaultInternalExpireDate))
Same, moment could help here.

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +		hasFileDropPermissions() {
`isFileDropPermissions`

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				perms.push('Update')
Only one to be capitalized ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +		console.debug('config', this.config)
To remove

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +		},
Why is this method needed ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			if (this.share.share_type) {
Why is there `share.share_type` and `share.type` ?

2023-08-29 09:43 UTC, artonge commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				this.share.type = this.share.shareType
And `share.shareType` ?

2023-08-29 09:46 UTC, juliushaertl commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				<h1>{{ title }}</h1>
I'd say it should be the level below what the sidebar header is using

2023-08-29 09:59 UTC, artonge requested changes
Critical:

- [ ] When updating the share, if I do not touch the password, it is still updated to something else.
- [ ] The advances settings are not saved if changed on a new share
- [ ] When switching from "Custom permissions" to "View only", I end up with "Allow upload and editing" selected
- [ ] When settings "View only" with the quick settings, and then reload, the quick settings show "Custom permissions"
- [ ] Setting the expiration date on a new user share does not work
- [ ] Setting the expiration date saves the changes, when it should not
- [ ] Setting the custom permissions saves the changes, when it should not

Follow-ups:

- [ ] The list of permissions below "Custom permissions" should reflect the current permissions
- [ ] Switching between permissions presets should not close the advanced settings view
- [ ] The content of the sidebar is scrollable when it should only be the content of the share tab
![Screenshot from 2023-08-29 11-52-15](https://github.com/nextcloud/server/assets/6653109/7e844261-a80a-41fb-a8d4-5a8cfb9f7575)
- [ ] A deleted share link is still visible if I do not reload the page

UI comments:

- [ ] Button at the bottom of the details view should not move when scrolling to the bottom
- [ ] Related resources should not appear in the details view
- [ ] "Delete share" button text seems smaller than other buttons

2023-08-29 10:15 UTC, artonge requested changes
UI comments

- [ ] Button at the bottom of the details view should not move when scrolling to the bottom
- [ ] Related resources should not appear in the details view

2023-08-29 10:47 UTC, jancborchardt commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				perms.push('Update')
To clarify: In the subline of "Custom permissions", only the first word should be capitalized.

2023-08-29 11:26 UTC, Fenn-CS commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				perms.push('Update')
It's the case, the function that handles that corrects this, but fixed for consistency.

2023-08-30 09:03 UTC, artonge commented on apps/files_sharing/src/views/SharingTab.vue
> +			<SharingDetailsTab :file-info="shareDetailsData.fileInfo"
Any reason to use `shareDetailsData.fileInfo` instead of `fileInfo` ?

2023-08-30 15:12 UTC, artonge approved these changes

2023-08-30 15:26 UTC, AndyScherzinger approved these changes

2023-08-30 16:07 UTC, artonge commented
Backport to stable27: https://github.com/nextcloud/server/pull/40166

2023-08-30 21:18 UTC, merged