fix(CardDAV): set owner-principal, displayname properties for SAB
nextcloud/server pull request #39525
Opened 2023-07-21 10:34 UTC by miaulalala

Found in https://github.com/nextcloud/server/pull/38397

## Summary
The SAB has no owner principal even though it is a "shared" address book - the system user shares it will all users automatically.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-07-21 10:34 UTC, miaulalala commented
/backport to stable27

2023-07-21 11:21 UTC, ChristophWurst approved these changes

2023-07-21 12:14 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/Principal.php
> +				'{DAV:}displayname' => $name,
Shouldn't the display name be translated?

2023-07-21 12:53 UTC, JohannesGGE approved these changes

2023-07-24 14:52 UTC, tcitworld requested changes

2023-07-24 14:52 UTC, tcitworld commented on apps/dav/lib/Connector/Sabre/Principal.php
> +				'{DAV:}displayname' => $this->languageFactory->get('dav')->t($name),
**nitpick:** This won't work for string extraction. Hardcode `"System Addressbook"` instead.

2023-07-25 11:42 UTC, miaulalala commented on apps/dav/lib/Connector/Sabre/Principal.php
> +				'{DAV:}displayname' => $this->languageFactory->get('dav')->t($name),
Needs to be "Accounts" afaik

2023-07-25 12:02 UTC, tcitworld commented
```
1) OCA\DAV\Tests\unit\CardDAV\AddressBookTest::testPropPatchNotShared
Expectation failed for method name is "updateAddressBook" when invoked at least 1 times.
Expected invocation at least 1 times but it occurred 0 time(s).
```

2023-07-25 15:08 UTC, tcitworld approved these changes

2023-08-16 08:17 UTC, merged