AI admin settings
nextcloud/server pull request #39567
Opened 2023-07-25 12:25 UTC by marcelklehr

* Resolves: -

## Summary
Adds an admin settings section for AI settings, allowing admins to specify the precedence of machine translation providers, set the speech-to-text provider to use and select which text processing provider to use for which task.

![image](https://github.com/nextcloud/server/assets/986878/18c73af4-0be2-4b9e-93a8-4f698c9002e4)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-07-27 22:25 UTC, susnux commented
Nice! But keep in mind vuedragable is not accessible, so there is no way to reorder by using the keyboard, this needs to be done by the user of the component itself.

2023-07-28 09:48 UTC, marcelklehr commented
@susnux How would you go about adding a11y here?

2023-07-28 10:34 UTC, susnux commented
> How would you go about adding a11y here?

For Forms I suggested this one: https://github.com/nextcloud/forms/pull/1532

So basically either implement key event listeners (arrow up / down) or add additional buttons for ordering

2023-07-28 10:58 UTC, marcelklehr commented
![image](https://github.com/nextcloud/server/assets/986878/c24204aa-9bc1-4d92-af99-2121e2982ad7)

2023-07-28 10:59 UTC, marcelklehr commented
/compile

2023-07-28 13:57 UTC, julien-nc requested changes
Awesome, tested with a FreePrompt, a Summarize and an Outline TP provider.
The fallback works just fine if a provider fails.

Small string changes requested but all the rest LGTM.

I'm also wondering if all the unrelated stuff belongs here but since these are nice fixes, why not letting them in this.

About accessibility, there could be 2 buttons to move items up and down.

2023-07-28 13:57 UTC, julien-nc commented on apps/settings/src/components/AdminAI.vue
> +					{{ t('settings', 'No apps are currently installed that provide Speech-To-Text functionality') }}
```suggestion
					{{ t('settings', 'None of your currently installed apps provide Speech-To-Text functionality') }}
```

2023-07-28 13:57 UTC, julien-nc commented on apps/settings/src/components/AdminAI.vue
> +				<p>{{ t('settings', 'No apps are currently installed that provide Text processing functionality') }}</p>
```suggestion
				<p>{{ t('settings', 'None of your currently installed apps provide Text processing functionality') }}</p>
```

2023-07-28 13:57 UTC, julien-nc commented on apps/settings/src/components/PersonalInfo/AvatarSection.vue
> +		</h3>
A bit out of scope but why not. :grin:

2023-07-28 14:07 UTC, marcelklehr commented on apps/settings/src/components/PersonalInfo/AvatarSection.vue
> +		</h3>
Yeah, I added one commit that does a lint:fix :shrug:

2023-07-28 14:08 UTC, marcelklehr commented
> About accessibility, there could be 2 buttons to move items up and down.

Already added :) (see screenshot above)

2023-07-31 19:26 UTC, Pytal commented on apps/settings/src/components/AdminAI.vue
> +					<NcButton aria-label="Move down" type="tertiary" @click="settings['ai.translation_provider_preferences'].splice(i+1, 0, ...settings['ai.translation_provider_preferences'].splice(i, 1)); saveChan
Should move the long click handlers into methods

2023-07-31 19:26 UTC, Pytal commented on apps/settings/src/components/PersonalInfo/AvatarSection.vue
> +		</h3>
Thanks for the lint fixes! Let's keep these scoped next time as there are a lot 🤯

2023-07-31 19:26 UTC, Pytal commented on core/Migrations/Version28000Date20230728104802.php
> +			$table->addColumn('last_updated', 'integer', [
```suggestion
			$table->addColumn('last_updated', Types::INTEGER, [
```

2023-08-01 10:10 UTC, julien-nc approved these changes

2023-08-01 10:11 UTC, julien-nc commented
/compile

2023-08-01 10:11 UTC, julien-nc commented
@Pytal Thanks for the review. Your changes have been implemented.
Rebased on master.

2023-08-01 10:35 UTC, julien-nc commented
/compile

2023-08-01 10:57 UTC, julien-nc commented
/compile

2023-08-01 11:11 UTC, julien-nc commented
/compile

2023-08-01 17:12 UTC, Pytal approved these changes

2023-08-02 12:54 UTC, julien-nc commented
Cypress failure is related with user settings.
acceptance-app-files failure is related with a file action menu button.

2023-08-02 12:55 UTC, merged

2023-08-02 22:23 UTC, kesselb commented
The failing TextProcessingTest looks related:

![image](https://github.com/nextcloud/server/assets/3902676/9fda4348-93cc-407d-840a-e5d08ddeba00)

2023-08-02 22:52 UTC, kesselb commented
Fix: https://github.com/nextcloud/server/pull/39684