[wip] ocm controller
nextcloud/server pull request #39574
Opened 2023-07-26 00:43 UTC by ArtificialOwl

2023-07-31 11:23 UTC, AndyScherzinger commented
also looping in @glpatcern

2023-07-31 12:47 UTC, AndyScherzinger commented
/backport to stable26

2023-08-01 13:10 UTC, come-nc reviewed
I also agree with @Altahrim that json_* calls should throw on error.

2023-08-01 22:06 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +		if ($this->isSafeUrl(parse_url($endPoint, PHP_URL_PATH) ?? '')) {
I just took example on the ocs integration,

There is a validity check of the object that can be done to confirm object fit the documentation.
Locally, the endpoint should be fine and remotely, if object is not valid discovery() throws exception.

2023-08-01 22:10 UTC, ArtificialOwl commented on core/Controller/OCMController.php
> +				Http::STATUS_NOT_FOUND
500 is good enough ?

2023-08-01 22:12 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +	public function setResourceTypes(array $resourceTypes): self {
`resourceTypes` is the name of the parameter in the documentation while being closer to be a 'unique resource per type'.
Should I rename the method to `addResourceType()` ?

2023-08-01 22:14 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +			   parse_url($this->getEndPoint(), PHP_URL_HOST)) {
it confirms the generated object fit the documentation, based on required values on some parameters.

2023-08-01 22:16 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +	}
taken from ocs-provider, I guess it was to limit strange address sent by remote instance services.

2023-08-01 22:17 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +		}
can be removed since json_decode() throw on error :)

2023-08-01 22:19 UTC, ArtificialOwl commented on lib/private/OCM/OCMDiscoveryService.php
> +			}
Let's imagine we upgrade the protocol; this would ignore cached old protocol :-]

2023-08-02 10:04 UTC, ArtificialOwl commented on lib/private/OCM/Model/OCMProvider.php
> +		}
i will keep the import() method the way it is

2023-08-03 07:30 UTC, Altahrim approved these changes

2023-08-03 09:22 UTC, come-nc commented on lib/private/OCM/Model/OCMProvider.php
> +		if ($this->isSafeUrl(parse_url($endPoint, PHP_URL_PATH) ?? '')) {
I’d feel safer with an exception. If it’s not expected to happen this is what exceptions are for.

2023-08-03 09:22 UTC, come-nc commented on lib/private/OCM/Model/OCMProvider.php
> +	public function setResourceTypes(array $resourceTypes): self {
I’d like if all methods/vars were renamed to the same thing yes either resource or resourceType no strong opinion on which but the same one everywhere.

2023-08-03 09:25 UTC, come-nc commented on lib/private/OCM/Model/OCMProvider.php
> +	}
Yeah this seems too strict on some things and not enough on others :-/
We should not validate such things by homemade regex, but it should be clear what we’re trying to test there to know which kind of validation would be appropriate.

2023-08-10 13:06 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Capabilities.php
> +		if (!$pos) {
nice aesthetic catch

2023-08-11 12:00 UTC, nickvergessen commented on apps/cloud_federation_api/lib/Capabilities.php
> +	 * @return array {
The space is breaking?

2023-08-11 12:03 UTC, nickvergessen requested changes

2023-08-11 12:03 UTC, nickvergessen commented on apps/files_sharing/lib/External/Storage.php
> +				   || $this->testRemoteUrl($this->getRemote() . '/ocm-provider/')
this looks crucial, is it breaking compatibility with older versions?

2023-08-11 13:15 UTC, ArtificialOwl commented on apps/files_sharing/lib/External/Storage.php
> +				   || $this->testRemoteUrl($this->getRemote() . '/ocm-provider/')
no, the url `/ocm-provider/index.php` exists for a while now, it was just not used.

2023-08-11 13:59 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Capabilities.php
> +	 * @return array {
i think the issue is that the @return in the inherited class is more documented than the interfaced, the space just trigger the check

2023-08-15 15:33 UTC, glpatcern commented
@AndyScherzinger @ArtificialOwl as I see you're finalizing this work (quite more significant than expected!), can you please comment on https://github.com/nextcloud/server/pull/39574#discussion_r1291379005 ?

Note that we currently had to introduce [a hack in Reva](https://github.com/cs3org/reva/blob/master/internal/http/services/ocmprovider/ocmprovider.go#L155-L160) to compensate the lack of semantic versioning in Nextcloud.

2023-08-16 06:44 UTC, glpatcern commented
Thanks to you for the effort, we have nicely converging goals! As for the test, these days I'm off and following things a bit on the side. I mentioned this PR to the collaborators that first identified the issue, let's see what can be done.

As for the versioning, you're fully right, independently from supporting "the other way around" a server can always assume to access remote servers with the 1.0 protocol. And I'd even insist to allow any 1.x, not only `1.1`: we may have a `1.2` hopefully in the near future!

2023-08-16 09:10 UTC, MahdiBaghbani commented
Hi, thanks for the PR 😄. 
As @glpatcern is off, I'll try to test this PR branch with our software (Reva, ScienceMesh) in this week.

2023-08-16 10:55 UTC, ArtificialOwl commented
last commit:

- added `1.1`
- ignoring minor increment on the version: `1.0.0` is considered `1.0`

2023-08-25 08:03 UTC, ArtificialOwl commented
(integration error not related)

2023-09-01 14:05 UTC, glpatcern commented
I summarize here the details posted at https://github.com/sciencemesh/nc-sciencemesh/issues/42#issuecomment-1697669567

Currently, part of the problematic calls described in #39001 are still there, in particular a non-compliant `POST /index.php/apps/files_sharing/shareinfo` instead of the OCM-compliant `PROPFIND http://<shared-secret>:@<remotehost>/<remote-path-exposed-by-ocm-provider>`.

I have sent a share (<shared-secret> and <remote-host>) to @ArtificialOwl by email, not sure you got it, that can be used as an OCM 1.0 compliant endpoint to test Nextcloud against. That should help you identify what makes Nextcloud _as a client_ issue those calls.

2023-09-08 09:12 UTC, glpatcern approved these changes
With the last fix (using basic auth on the `PROPFIND` according to the OCM standard) I confirm we have got interoperability working with our Reva-based EFSS.

2023-09-14 16:05 UTC, come-nc commented on lib/private/OCM/Model/OCMProvider.php
> +		$resourceTypes = []; // this is needed for psalm
```suggestion
		$resourceTypes = [];
```

2023-09-20 14:35 UTC, ArtificialOwl commented on apps/files_sharing/lib/External/Storage.php
> +				   || $this->testRemoteUrl($this->getRemote() . '/ocm-provider/')
@nickvergessen can you not block the merge ? :-]

2023-09-20 18:16 UTC, merged

2023-09-20 18:44 UTC, glpatcern commented
Glad to see this was merged. What are your plans for a backport to Nextcloud 27 and 26?

2023-09-29 05:20 UTC, ChristophWurst commented
Adds new APIs to lib/public so we need documentation.

2023-09-29 06:37 UTC, nickvergessen commented
Seems like https://github.com/nextcloud/server/blob/f174e4a0575284fd6eb14ec2365962213093441f/lib/private/Setup.php#L540 should have been adjusted as well and we need to trigger it during the update.

Additionally this breaks servers with `index.php/…` routes (default) ❓ 
The endpoint used to be `/ocm-provider` and with clean urls it still is. But when the server uses `index.php/…` routes, it is now actually moved to `index.php/ocm-provider` ?

Also https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html need adjusting (and therefore needs to be mentioned in https://docs.nextcloud.com/server/stable/admin_manual/release_notes/upgrade_to_27.html

Since this was also backported to 26 (😕 ) also https://docs.nextcloud.com/server/stable/admin_manual/release_notes/upgrade_to_26.html needs to be adjusted.
It's very unfortunate to have a huge massive change like this in a normal patch release. 

cc @sorbaugh

2023-09-29 07:02 UTC, sorbaugh commented
@nickvergessen huge appreciation for leading the debugging effort 🙏 Will align with @ArtificialOwl to get this dealt with.

2023-10-02 18:24 UTC, ArtificialOwl commented
> Seems like
> 
> https://github.com/nextcloud/server/blob/f174e4a0575284fd6eb14ec2365962213093441f/lib/private/Setup.php#L540
> should have been adjusted as well and we need to trigger it during the update.

If #40745 resolves the issue, as it add a line to the original `.htaccess`, we might not need to trigger anything.

> Additionally this breaks servers with `index.php/…` routes (default) ❓ The endpoint used to be `/ocm-provider` and with clean urls it still is. But when the server uses `index.php/…` routes, it is now actually moved to `index.php/ocm-provider` ?

I were not able to reproduce this issue with patched instance.
Previously, default setup were fine and I could only reproduce the reported issue on an instance with configured `htaccess.RewriteBase` 

> 
> Also https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html need adjusting (and therefore needs to be mentioned in https://docs.nextcloud.com/server/stable/admin_manual/release_notes/upgrade_to_27.html

I am not even a user of nginx, i require help on this task; but it might just be an adjustment on a comment section.

2023-10-04 09:50 UTC, nickvergessen commented
> I am not even a user of nginx, i require help on this task; but it might just be an adjustment on a comment section.

Me neither, but basically you replicate the change from htaccess and the Setup class into the docs. All needed patterns should be there already.

2023-11-01 20:12 UTC, kesselb commented
> Additionally this breaks servers with index.php/… routes (default) ❓
The endpoint used to be /ocm-provider and with clean urls it still is. But when the server uses index.php/… routes, it is now actually moved to index.php/ocm-provider ?

Yep, also reported via support. 

I fear this pull request unintentional added hard requirement for apache's mod_rewrite.

2023-11-01 20:35 UTC, kesselb commented
> Yep, also reported via support.
> 
> I fear this pull request unintentional added hard requirement for apache's mod_rewrite.
> 

Sorry, I mixed something up. 

The new ocm-provider should also work without mod_rewrite.
That's done by using `ErrorDocument 404 /index.php/error/404`.
To allow overriding ErrorDocument in .htaccess we need at least AllowOverride FileInfo.

2023-11-02 07:42 UTC, AndyScherzinger commented
So ignore your comment or something we need to take action on @kesselb

2023-11-02 08:11 UTC, nickvergessen commented
I have the issue every time on my dev instance. federation is not working until I ran `occ maintenance:update:htaccess` after installing the server.

2023-11-02 09:10 UTC, nickvergessen commented
The following patch makes it work again:
```diff
diff --git a/lib/private/Federation/CloudFederationProviderManager.php b/lib/private/Federation/CloudFederationProviderManager.php
index ea2f0dd7575..4e2a559ce8a 100644
--- a/lib/private/Federation/CloudFederationProviderManager.php
+++ b/lib/private/Federation/CloudFederationProviderManager.php
@@ -116,6 +116,7 @@ class CloudFederationProviderManager implements ICloudFederationProviderManager
                try {
                        $ocmProvider = $this->discoveryService->discover($cloudID->getRemote());
                } catch (OCMProviderException $e) {
+                       $this->logger->debug($e->getMessage(), ['exception' => $e]);
                        return false;
                }
 
diff --git a/lib/private/OCM/OCMDiscoveryService.php b/lib/private/OCM/OCMDiscoveryService.php
index ac9bf2a3965..10d460b34da 100644
--- a/lib/private/OCM/OCMDiscoveryService.php
+++ b/lib/private/OCM/OCMDiscoveryService.php
@@ -105,6 +107,9 @@ class OCMDiscoveryService implements IOCMDiscoveryService {
                                'exception' => $e,
                                'remote' => $remote
                        ]);
+                       if (!str_ends_with($remote, '/index.php')) {
+                               return $this->discover($remote . '/index.php', $skipCache);
+                       }
                        throw new OCMProviderException('error while requesting remote ocm provider');
                }
 
```

2023-11-02 09:14 UTC, nickvergessen commented
I'm not sure what exactly `ErrorDocument 404 /index.php/error/404` does, but yeah with that line in .htaccess the request seems to work.

2023-11-02 09:44 UTC, nickvergessen commented
Simply always requesting index.php also works (tested with our instance and locally), so I sent that as a patch in https://github.com/nextcloud/server/pull/41234

2023-11-02 11:56 UTC, kesselb commented
> I'm not sure what exactly ErrorDocument 404 /index.php/error/404 does, but yeah with that line in .htaccess the request seems to work.

It tells apache2 to forward a 404 error to our index.php to handle it. 
Our implementation then maps the request to the actual ocm-controller. 

I haven't heard back from the customer, but I assume that they have AllowOverride None and therefore the ErrorDocument in .htaccess has no effect.