fix(l10n): Password column header
nextcloud/server pull request #39599
Opened 2023-07-27 18:15 UTC by Pytal

## Summary

Fix https://github.com/nextcloud/server/issues/39572

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-07-28 06:20 UTC, rakekniven requested changes
Thanks for the change.
Unfortunately I did understand the string itself.
You described the usage in the UI, but the translators asking for context.

What does "Password or insufficient permissions message" mean?
Is it "Password message or insufficient permissions message"?
Or is it about a password?

2023-07-31 18:45 UTC, Pytal commented
/compile amend /

2023-08-11 22:03 UTC, Pytal commented on apps/settings/src/components/Users/UserListHeader.vue
> +				// TRANSLATORS This string is for a column header labelling either a password or a message that the current user has insufficient permissions
The header itself would only show the label while the cells underneath it contain user passwords, though technically the passwords are not actually shown for security reasons but can be edited in edit mode

2023-08-16 22:49 UTC, susnux approved these changes

2023-08-17 07:45 UTC, rakekniven approved these changes

2023-08-17 13:49 UTC, merged