Backport of #39614
nextcloud/server pull request #39671
Opened 2023-08-02 08:05 UTC by Fenn-CS

Backport of https://github.com/nextcloud/server/pull/39614

2023-08-02 16:19 UTC, ArtificialOwl approved these changes

2023-08-02 19:30 UTC, nickvergessen requested changes
Didn't check the test file, but you can execute the test locally before pushing

2023-08-02 19:40 UTC, nickvergessen approved these changes
Cherry-picked the original command from icewind and adjusted the `: void` in the test file which was the conflict.

2023-08-02 19:44 UTC, AndyScherzinger approved these changes

2023-08-02 20:01 UTC, blizzz approved these changes

2023-08-03 07:16 UTC, merged

2023-08-03 07:17 UTC, Fenn-CS commented
CI, fail is erratic and unrelated.