improve di performance for cache
nextcloud/server pull request #39889
Opened 2023-08-15 16:42 UTC by icewind1991

not really the cleanest, but `Cache` is to deeply integrated to add a ton of DI parameters without being a major pain

2023-08-18 11:50 UTC, AndyScherzinger approved these changes

2024-02-10 09:01 UTC, skjnldsv commented on apps/files_external/tests/Service/StoragesServiceTest.php
> +		$storageCache = new \OC\Files\Cache\Storage($rustyStorageId, true, \OC::$server->get(IDBConnection::class));
```suggestion
		use OCP\Server;
		$storageCache = new \OC\Files\Cache\Storage($rustyStorageId, true, Server::get(IDBConnection::class));
```

2024-02-10 09:02 UTC, skjnldsv commented on apps/files_external/tests/Service/StoragesServiceTest.php
>  use OCP\IUser;
```suggestion
use OCP\IDBConnection;
use OCP\IUser;
use OCP\Server;
```

2024-02-10 09:02 UTC, skjnldsv commented on apps/files_external/tests/Service/StoragesServiceTest.php
> +		$storageCache = new \OC\Files\Cache\Storage($rustyStorageId, true, \OC::$server->get(IDBConnection::class));
```suggestion
		$storageCache = new \OC\Files\Cache\Storage($rustyStorageId, true, Sserver::get(IDBConnection::class));
```

2024-02-10 09:03 UTC, skjnldsv commented on lib/private/Files/Cache/Wrapper/CacheWrapper.php
> +				$dependencies = \OC::$server->get(CacheDependencies::class);
```suggestion
				$dependencies = Server::get(CacheDependencies::class);
```

2024-02-10 09:03 UTC, skjnldsv commented on lib/private/Files/Cache/Wrapper/CacheWrapper.php
>  use OCP\Files\Search\ISearchQuery;
```suggestion
use OCP\Files\Search\ISearchQuery;
use OCP\Server;
```

2024-02-10 09:03 UTC, skjnldsv commented on lib/private/Files/Storage/Common.php
> +			$dependencies = \OC::$server->get(CacheDependencies::class);
```suggestion
			$dependencies = Server::get(CacheDependencies::class);
```

2024-02-10 09:03 UTC, skjnldsv requested changes
See comments

2024-02-12 18:09 UTC, icewind1991 commented
> See comments

fixed

2024-02-13 08:39 UTC, skjnldsv approved these changes

2024-02-13 08:40 UTC, merged