Refactor files trashbin app
nextcloud/server pull request #39883
Opened 2023-08-15 12:20 UTC by danialRahimy

## Summary

I did these items in a single file `apps/files_trashbin/lib/Trashbin.php` for two reasons:
1. Pull request hasn't been a lot of changes.
2. I was not sure about some changes.

- Return early
- Change the const name for more readability
- Add functions' return type
- Update doc types

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-08-16 06:40 UTC, nickvergessen commented on apps/files_trashbin/lib/Trashbin.php
> +	 * @throws ContainerExceptionInterface
I'm very much against these.
They are not expected and not part of the API. If they happen it's not a user / API consumer fault, but basically the whole nextcloud is offline/broken.

2023-08-16 08:25 UTC, danialRahimy commented on apps/files_trashbin/lib/Trashbin.php
> +	 * @throws ContainerExceptionInterface
You're right, and I appreciate your input.
I'll revert the changes to their previous state.

2023-08-19 10:49 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	public static function ensureFileScannedHook($params): void {
```suggestion
	public static function ensureFileScannedHook(array $params): void {
```

2023-08-19 10:50 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	public static function getUidAndFilename($filename): array {
```suggestion
	public static function getUidAndFilename(string $filename): array {
```

2023-08-19 10:50 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	public static function getLocations($user): array {
```suggestion
	public static function getLocations(string $user): array {
```

2023-08-19 10:51 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	public static function getLocation($user, $filename, $timestamp): bool|string {
```suggestion
	public static function getLocation(string $user, string $filename, string $timestamp): bool|string {
```

2023-08-19 10:51 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	private static function setUpTrash($user): void {
```suggestion
	private static function setUpTrash(string $user): void {
```

2023-08-19 10:52 UTC, Fenn-CS commented on apps/files_trashbin/lib/Trashbin.php
> +	private static function copyFilesToUser($sourcePath, $owner, $targetPath, $user, $timestamp): void {
```suggestion
	private static function copyFilesToUser(string $sourcePath, string $owner, string $targetPath, string $user, int $timestamp): void {
```

2023-08-19 10:54 UTC, Fenn-CS requested changes
Since this is just a refactor and no main functional change you can just use build in type hinting for PHP... I left a few examples but not all, most of the functions can use built in type hinting and that would allow you to delete the comment annotations at the top (leaving behind just the exceptions)

2024-08-03 16:43 UTC, closed without merging