fix(files): Fix legacy files list sorting
nextcloud/server pull request #39919
Opened 2023-08-16 18:14 UTC by susnux

* Resolves: #38758

## Summary
The sorting was not saved since files2vue changes in Nextcloud 27, as a new API endpoint was introduced and the old one was dropped without adjusting the legacy file list to use it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-08-16 18:14 UTC, susnux commented
/backport to stable27

2023-08-16 20:35 UTC, susnux commented
@skjnldsv after f2v this is not required on master, but we need this for stable27.

2023-08-17 07:01 UTC, skjnldsv requested changes, later dismissed
Let's wait for https://github.com/nextcloud/server/pull/39808 please :pray: 
That way you can also use the cypress selectors

https://github.com/nextcloud/server/blob/feat/f2v/files/cypress/e2e/files.cy.ts

2023-08-17 09:36 UTC, susnux commented
> Let's wait for #39808 please 🙏 That way you can also use the cypress selectors

@skjnldsv maybe I should just submit to stable27 directly as it is not needed on master after that PR anymore? :)

2023-08-18 12:29 UTC, susnux commented
Changed the base to stable27, as this is no longer needed for master (thanks to f2v :) ).

Sorry for the noise Github assigned everyone for a short moment...

2023-08-18 13:08 UTC, AndyScherzinger approved these changes

2023-08-18 13:52 UTC, artonge approved these changes

2023-08-19 14:22 UTC, merged