fix(CardDAV): allow disabling of the system address book
nextcloud/server pull request #39925
Opened 2023-08-17 07:00 UTC by miaulalala

via config option and OCC command

* Resolves: https://github.com/nextcloud/server/issues/38880

## Summary
Allow admins to disable the System Addressbook systemwide.

This might cause complaints from connected clients if the SAB is the default addressbook in their env.

## TODO

- [x] Documentation

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-08-17 14:44 UTC, ChristophWurst commented
config:app:set/delete should be sufficient. we don't need dedicated commands right now: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#config-commands

2023-08-18 06:13 UTC, miaulalala commented
/backport to stable27

2023-08-18 09:05 UTC, tcitworld requested changes
I feel like just adding an `if` to the above block where the system address book is added in the first place would be much more efficient, why not do that instead?

(in any case, you need to get the `getAppValue` call outside of the `array_map` so that it doesn't get called for each iteration)

2023-08-21 08:19 UTC, tcitworld commented on apps/dav/lib/CardDAV/UserAddressBooks.php
> +			$objects = array_filter(array_map(function (array $addressBook) {
**question:** Still needed?

2023-08-21 11:20 UTC, miaulalala commented on apps/dav/lib/CardDAV/UserAddressBooks.php
> +			$objects = array_filter(array_map(function (array $addressBook) {
No, thanks!

2023-08-21 11:41 UTC, tcitworld approved these changes

2023-08-21 11:45 UTC, tcitworld reviewed
Code is fine but I didn't check if that has other consequences elsewhere.

2023-08-21 11:45 UTC, tcitworld commented on apps/dav/lib/CardDAV/UserAddressBooks.php
> +		$systemAddressBookDisabled = $this->config->getAppValue('dav', 'system_addressbook_disabled', 'no') === 'yes';
**suggestion:** Now that I think about it, is `disabled` the correct term, since it continues to exist and is synced by `SyncService` for federation? Maybe `system_addressbook_exposed` instead (with default to `'yes'`) ?

2023-08-21 14:16 UTC, miaulalala commented on apps/dav/lib/CardDAV/UserAddressBooks.php
> +		$systemAddressBookDisabled = $this->config->getAppValue('dav', 'system_addressbook_disabled', 'no') === 'yes';
hm that's true but that is no different than the situation before we added the SAB. Federation sync has always been happening

2023-08-21 15:08 UTC, tcitworld commented on apps/dav/lib/CardDAV/UserAddressBooks.php
> +		$systemAddressBookDisabled = $this->config->getAppValue('dav', 'system_addressbook_disabled', 'no') === 'yes';
Well no, the system address book was exposed only on the `principals/system/system` principal, not on all principals.

2023-09-01 09:30 UTC, andrey18106 approved these changes

2023-09-01 10:51 UTC, miaulalala commented
Failing cypress test is unrelated methinks:


```
  Login with a new user and open the files app
    1) "after all" hook for "See the default file welcome.txt in the files list"


  0 passing (7s)
  1 failing

  1) Login with a new user and open the files app
       "after all" hook for "See the default file welcome.txt in the files list":
     CypressError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
```

2023-09-01 16:01 UTC, merged

2023-09-01 17:19 UTC, mbiebl commented
Applied this patch and everything is working nicely again after disabling the SAB. Thanks a lot!

2023-09-01 19:38 UTC, sudoer commented
I was able to comment out this block of code, and I saw that the "Accounts" address book was no longer exported, as we had hoped.  So I am looking forward to the configuration-based fix soon.

I did have a question.  When this pull request is merged, how would someone set the configuration option?  Is it in a config file?  Or is there an "occ" command to set the option?  Is it eventually stored in the database, or in the code?  I imagine this question is a bit outside of the scope of this PR, but it sure would help to have a pointer to how to enable/disable it.  Thanks!

2023-09-02 08:07 UTC, tcitworld commented
```sh
php occ config:app:set dav system_addressbook_exposed --value=no
```

2023-09-04 11:20 UTC, MicKress commented
Hi, I have a question. Will the deactivation of system address book only be possible via occ-Command or will there be an point in the administration panel? If you have a managed nextcloud, you cannot often work with occ-commands. Best Regards

2024-05-13 09:59 UTC, exuded commented
Hello, when using the command [given in the documentation](https://docs.nextcloud.com/server/latest/admin_manual/groupware/contacts.html#system-address-book), I get the following error:
![CleanShot 2024-05-13 at 11 56 35](https://github.com/nextcloud/server/assets/52626442/b70a60c4-14f9-4ef6-b950-1a0225c22745)

 I am a bit confused because in the command is no "-a" part