Enable caldav push notifications by default
nextcloud/server pull request #40103
Opened 2023-08-29 14:19 UTC by hamza221

* Resolves: [#39862](https://github.com/nextcloud/server/issues/39862)

## Summary

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-08-30 08:50 UTC, hamza221 commented
> I don't understand how it answers #39158, sorry. :(

it doesn't, it answers https://github.com/nextcloud/server/issues/39862

2023-08-31 11:18 UTC, GretaD approved these changes
i only checked the vue and js changes

2023-08-31 11:38 UTC, miaulalala approved these changes

2023-09-06 09:15 UTC, ChristophWurst requested changes

2023-09-06 09:15 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
> -		if ($this->config->getAppValue('dav', 'sendEventRemindersPush', 'no') !== 'yes') {
like @tcitworld said we should flip the default value but leave the option to turn the feature *off*

2023-09-08 14:39 UTC, tcitworld approved these changes

2023-09-11 06:05 UTC, ChristophWurst approved these changes

2023-09-11 06:06 UTC, ChristophWurst commented
Failure of ``OCA\DAV\Tests\unit\CalDAV\Reminder\NotificationProvider\PushProviderTest::testNotSend`` and similar are related

2023-09-12 11:16 UTC, ChristophWurst approved these changes
Time to squash

2023-09-13 08:50 UTC, merged

2024-02-06 11:26 UTC, ChristophWurst commented
Needs admin docs for how to set sendEventRemindersPush and an entry in the admin upgrade section for 28