enh(settings): Add groups accessibly
nextcloud/server pull request #40110
Opened 2023-08-30 01:01 UTC by Pytal

- For https://github.com/nextcloud/server/issues/37090

## Summary

Before | After
--- | ---
![image](https://github.com/nextcloud/server/assets/24800714/5b4dfdda-95d9-4b62-a861-b0fd86d5c336) | ![image](https://github.com/nextcloud/server/assets/24800714/976867f4-5769-4697-b20e-e52b17c0f0c0)

## TODO

- [ ] Tests

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-08-30 01:13 UTC, marcoambrosini reviewed
@Pytal I would still prefer to have a heading in the menu that states what's the current operation that the user is undergoing, similar to contacts. 

Something like 
heading of the tooltip "Create group"
Label of the input: "Group name"

2023-08-30 18:07 UTC, Pytal commented
> @Pytal I would still prefer to have a heading in the menu that states what's the current operation that the user is undergoing, similar to contacts.
> 
> Something like heading of the tooltip "Create group" Label of the input: "Group name"

Done!

Also moved the actions next to the "Groups" navigation caption

2023-08-30 20:49 UTC, ShGKme requested changes
Works and looks good. But we should avoid using `$children` when possible.

2023-08-30 20:49 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> +			this.$refs.navigationCaption.$children[0].opened = false
IMO, this is very not a Vue way and explicit to manipulate `NcAction` by `$refs.navigationCaption.$children[0]`. It's very easy to break by change `NcAppNavigationCaption`.

Also, `$children` is removed in Vue and will break during Vue 3 migration. See: https://v3-migration.vuejs.org/breaking-changes/children.html

2023-08-30 20:49 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> +			this.$refs.navigationCaption.$children[0].opened = false
As an alternative way here I can propose to add new data property like `isAddGroupOpen` and use `open` prop of `NcAction`. We can pass it directly on `NcAppNavigationCaption`, it is proxied. Then instead of

```js
this.$refs.navigationCaption.$children[0].opened = false
```

we can pass `false` to this property:

```js
this.isAddGroupOpen = false
```

2023-08-30 20:49 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> -
Thank for cleaning up the component and removing unused code!

2023-08-31 23:59 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +			this.$refs.navigationCaption.$children[0].opened = false
Will also need to proxy listeners with https://github.com/nextcloud-libraries/nextcloud-vue/pull/4494 too

2023-10-10 12:44 UTC, ShGKme approved these changes

2023-10-10 12:44 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> +						:aria-label="loadingAddGroup ? t('settings', 'Creating group…') : t('settings', 'Create group')"
I'm not sure, but ше seems that we usually add a space before `…`, don't we?

```suggestion
						:aria-label="loadingAddGroup ? t('settings', 'Creating group …') : t('settings', 'Create group')"
```

2023-10-10 12:44 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> +								@submit="createGroup" />
`trailing-button-label` by default has `aria-label="Clear text"`, but maybe we should fix it on the `NcActionInput` side

2023-10-10 12:44 UTC, ShGKme commented on apps/settings/src/views/Users.vue
> +				showError(t('settings', 'Please enter a valid group name'))
Can we show it in a `hint-text` of the input?

2023-10-10 23:44 UTC, Pytal commented on apps/settings/src/views/Users.vue
> +								@submit="createGroup" />
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4632

2023-10-11 04:21 UTC, marcoambrosini approved these changes

2023-10-11 07:02 UTC, JuliaKirschenheuter approved these changes

2023-10-11 09:54 UTC, ShGKme approved these changes

2023-10-11 18:54 UTC, merged