Refactor `OC\Server::getEncryptionKeyStorage`
nextcloud/server pull request #40133
Opened 2023-08-30 01:27 UTC by summersab

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-15 12:11 UTC, skjnldsv approved these changes

2024-03-15 15:58 UTC, Altahrim approved these changes

2024-03-15 15:59 UTC, Altahrim requested changes

2024-03-15 15:59 UTC, Altahrim commented on lib/private/Encryption/EncryptionWrapper.php
> +use OCP\Encryption\Keys\IStorage;
```suggestion
use OCP\Encryption\Keys\IStorage as EncryptionKeysStorage;
```

2024-05-30 13:03 UTC, artonge approved these changes

2024-05-30 13:31 UTC, Altahrim approved these changes

2024-06-04 13:46 UTC, merged