[WIP] enh(settings): Load from disabled users endpoint
nextcloud/server pull request #40169
Opened 2023-08-31 00:49 UTC by Pytal

- Base branch https://github.com/nextcloud/server/pull/39756

## Summary

WIP

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-11 08:27 UTC, come-nc requested changes
User count seems broken, also avatar of freshly disabled users do not load.

2023-10-02 07:59 UTC, come-nc commented on apps/settings/src/components/UserList.vue
> +			}
Hum, what if I load the list, enable a user from the list, and then scroll to the end? Length will be 24, no?

2023-10-03 22:57 UTC, Pytal commented on apps/settings/src/components/UserList.vue
> +			}
Nope, only `filteredUsers` would change while `users` which contains all users loaded would stay the same

2023-10-09 10:01 UTC, come-nc commented
It works for disabled user list but for active user list it does not load the next ones when scrolling to the end it seems @Pytal

2023-10-17 09:10 UTC, artonge approved these changes

2023-10-19 09:36 UTC, come-nc commented
This is still not working correctly for me for active user list.
The problem is that with LDAP backend it returns more users than the limit, because the limit is applied to each backend indivdually. This may be seen as a bug but has been this way for a long time. (and fixing that brings perf questions)

So the test that user count is a multiple of 25 does not work, in may case the first request with limit 25 and offset 0 returns 37 users (25 from ldap, the rest from DB).
What you need to test to know if there are no more users is if the number of returned users is less than the limit.

Note that for disabled users endpoint it behaves better and will slice to return only 25 users when limit is 25, but maybe it’s still safer to consider 25 users **or more** valid sizes for non-complete answer.

2023-11-30 13:27 UTC, come-nc approved these changes

2023-12-01 01:49 UTC, susnux approved these changes

2023-12-01 16:42 UTC, merged