Server side checksum verification
nextcloud/server pull request #4023
Opened 2017-03-23 23:48 UTC by MorrisJobke

* downstream of https://github.com/owncloud/core/pull/27097

2017-03-24 06:29 UTC, MorrisJobke commented
We maybe put also https://github.com/owncloud/core/pull/27345 in this PR

2017-03-24 07:41 UTC, rullzer commented on apps/files/lib/Capabilities.php
> +				'supportedTypes' => ['SHA1'],
maybe we should also offer something else :wink:

2017-03-24 07:43 UTC, rullzer commented
Just to explain. This is not checksum verification as far as I can tell from a quick look.
It is still using the stored checksum on the server.

2017-03-24 13:47 UTC, icewind1991 requested changes
Let me fix this up a bit before merging

2017-03-24 17:16 UTC, MorrisJobke commented
> Let me fix this up a bit before merging

Tests are still failing

2017-04-13 06:08 UTC, MorrisJobke commented
@icewind1991 Could you have a look at the tests?

2017-04-19 01:18 UTC, MorrisJobke commented
> @icewind1991 Could you have a look at the tests?

Ping

2017-04-27 03:19 UTC, MorrisJobke commented
Continued in #4520

2017-04-27 03:19 UTC, closed without merging