Add "MFA Verified" check to workflowengine
nextcloud/server pull request #40235
Opened 2023-09-04 13:21 UTC by michielbdejong

Rebase of #39471

2023-09-04 15:21 UTC, come-nc reviewed
Looks good, did not test

2023-09-04 15:21 UTC, come-nc commented on apps/workflowengine/lib/Check/MfaVerified.php
> +/** @psalm-suppress PropertyNotSetInConstructor */
```suggestion
```
Both properties are set in the constructor, why the suppress?

2023-09-04 15:21 UTC, come-nc commented on apps/workflowengine/lib/Check/MfaVerified.php
> +	protected $session;
```suggestion
	protected IL10N $l;
	protected ISession $session;
```

2023-09-21 09:56 UTC, mrvahedi68 commented on apps/workflowengine/lib/Check/MfaVerified.php
> +/** @psalm-suppress PropertyNotSetInConstructor */
Done in https://github.com/nextcloud/server/pull/40235/commits/6c821f1d50fcf9a91f400ac5c5a89382787e6021

2023-09-21 09:56 UTC, mrvahedi68 commented on apps/workflowengine/lib/Check/MfaVerified.php
> +	protected $session;
Done in https://github.com/nextcloud/server/pull/40235/commits/6c821f1d50fcf9a91f400ac5c5a89382787e6021

2023-09-25 09:51 UTC, mickenordin commented
Can this be merged if it looks good?

2023-10-04 19:38 UTC, michielbdejong commented
@come-nc what is the next step in the process now?

2023-10-12 10:25 UTC, michielbdejong commented
@ArtificialOwl can you maybe have a look?

2023-10-25 12:07 UTC, michielbdejong commented
I'm worried about the lack of communication here, @mickenordin can you ask your NC support contact for advice?

2023-11-06 13:01 UTC, michielbdejong commented
@skjnldsv Thanks for mentioning this PR for NC 28! Will you be the person merging it? Anything we can do to help you?

Note that the conflicting files in the dist folders are easy to leave out and then rebuild after you merge!

2023-11-07 11:50 UTC, skjnldsv commented
@michielbdejong you're missing two reviews.
Unfortunately, while this looks like a good feature, all the engineers are busy on other tasks with higher priorities :(

Pinging maintainers: @blizzz and @juliushaertl

2023-11-13 09:56 UTC, blizzz commented
With beta from last week, we're behind feature freeze for 28 :anguished:

2023-11-13 10:06 UTC, blizzz requested changes

2023-11-13 10:06 UTC, blizzz commented on apps/workflowengine/lib/Check/MfaVerified.php
> +		}
Not so fond to have foreign app specific code here in a server app. Better, if we would dispatch an Event that app can listen to. This would also avoid dealing with opaque data structures that may change in their apps unnoticed.

2023-11-13 10:06 UTC, blizzz commented on apps/workflowengine/lib/Manager.php
> +				$this->container->query(MfaVerified::class),
```suggestion
				$this->container->get(MfaVerified::class),
```
would be the non-depracated method to use

2023-12-30 18:55 UTC, michielbdejong commented on apps/workflowengine/lib/Check/MfaVerified.php
> +		}
Maybe our app can call `window.OCA.WorkflowEngine.registerCheck` on the client-side and `OCA\WorkflowEngine\Manager::registerCheck` on the server-side and then this whole PR is maybe not even needed... will try that!

2024-01-09 13:57 UTC, michielbdejong commented on apps/workflowengine/lib/Check/MfaVerified.php
> +		}
Ah that worked!

2024-01-09 13:59 UTC, closed without merging

2024-01-09 13:59 UTC, michielbdejong commented
I succeeded in adding this check inside https://github.com/pondersource/mfazones instead of adding it to nextcloud/server, so we can close this PR. If anyone wants to use the `MFA Verified?` check then they can make it available on their server by installing the `mfazones` app. Thanks for your help!