fix(f2v): Files list loading with spaces in uid
nextcloud/server pull request #40313
Opened 2023-09-07 00:08 UTC by Pytal

## Summary

Before | After
--- | ---
![image](https://github.com/nextcloud/server/assets/24800714/918ea293-d856-4b52-85b8-a36bb218e80b) | ![image](https://github.com/nextcloud/server/assets/24800714/85442669-63dc-4357-b6ca-5c94b44615cb)

- Create dav client with correctly encoded root url `…/dav/files/test user/` → `…/dav/files/test%20user/`

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-07 05:14 UTC, AndyScherzinger approved these changes

2023-09-07 06:24 UTC, artonge approved these changes

2023-09-07 06:30 UTC, skjnldsv requested changes

2023-09-07 18:23 UTC, Pytal commented on apps/files/src/services/WebdavClient.ts
> +export const rootPath = `/files/${encodeURIComponent(getCurrentUser()?.uid || '')}`
https://github.com/nextcloud-libraries/nextcloud-files/pull/759

2023-09-07 18:50 UTC, Pytal commented
Now correctly encodes single quotes as defined in https://github.com/nextcloud/server/blob/eb5510188ecc721bf43ad615b22d99bd98b46ee3/lib/private/User/Manager.php#L706

2023-09-08 07:14 UTC, skjnldsv commented on apps/files/src/services/WebdavClient.ts
> +		.replaceAll('\'', '%27')
We should not hae to replace quotes, they are allowed in an URL according to [rfc2396](https://www.ietf.org/rfc/rfc2396.txt)

I think the webdav have an issue:
Here are the exact two same breakpoints:
| Without quote in userId | With quote in userId |
|:---------:|:------:|
|![2023-09-08_09-13](https://github.com/nextcloud/server/assets/14975046/9b3d3494-eed3-4f2d-baf5-d389b8d37fa6)|![image](https://github.com/nextcloud/server/assets/14975046/fddf221a-4cd0-4b71-8431-0986f4d357e2)|

2023-11-24 03:12 UTC, Pytal commented
Superseded by https://github.com/perry-mitchell/webdav-client/pull/360

2023-11-24 03:12 UTC, closed without merging