fix: Pass parent to NonExistingFile instances
nextcloud/server pull request #40312
Opened 2023-09-06 18:10 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-07 06:36 UTC, skjnldsv approved these changes

2023-09-07 08:00 UTC, come-nc commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
Can you go into the details of what breaks without this and why is the lazy parent not enough?

2023-09-07 08:04 UTC, juliushaertl commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
getParent used to just directly get it in https://github.com/nextcloud/server/pull/38150/files#diff-edc136e5646ea4171607db53b38833e8f6caaacc64874a0a850aa4444f0a56edL303-R309 but now always makes use of the file info which is not available for a nonexisting file.

2023-09-07 09:08 UTC, come-nc commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
Then wouldn’t the right fix be to check for fileinfo presence before calling getParentId on it and fallback on previous behavior if fileInfo is not there? I’m afraid there might be other side effects we missed.

2023-09-07 09:23 UTC, juliushaertl commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
Yeah might be indeed a good idea, will check that

2023-09-07 19:49 UTC, juliushaertl commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
Pushed a more generic approach but still passing the parent to the NonExistingFile to avoid an extra queries in that case.

2023-09-11 08:01 UTC, come-nc approved these changes

2023-09-11 08:01 UTC, come-nc commented on lib/private/Files/Node/Node.php
> +			// Manually the parent if the current node doesn't have a file info yet
```suggestion
			// Manually fetch the parent if the current node doesn't have a file info yet
```
Or get? But a word is missing there I think.

2023-09-11 13:31 UTC, juliushaertl commented on lib/private/Files/Node/Node.php
> +			// Manually the parent if the current node doesn't have a file info yet
Yep, fixed

2023-09-11 13:31 UTC, juliushaertl commented
I cannot see the same psalm error locally :/

2023-09-11 13:37 UTC, icewind1991 commented on tests/lib/Files/Node/NodeTest.php
> +		$this->root->expects($this->any())
You can just remove the `expects` altogether

2023-09-11 13:40 UTC, icewind1991 requested changes, later dismissed

2023-09-11 13:40 UTC, icewind1991 commented on lib/private/Files/Node/File.php
> +		return new NonExistingFile($this->root, $this->view, $path, $this->root->get(dirname($path)));
> to avoid an extra queries in that case.

doesn't it just move the query to the constructor call here?

As is it always does the "get parent" query even when `getParentId` isn't called, without this it only does the query when `getParentId` is called

2023-09-12 13:42 UTC, icewind1991 approved these changes

2023-09-13 10:00 UTC, merged