feat: update sign up link in share pages
nextcloud/server pull request #40368
Opened 2023-09-11 16:25 UTC by luka-nextcloud

* Resolves: https://github.com/nextcloud-gmbh/customer-feature-requests/issues/255

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-11 20:28 UTC, juliushaertl commented on lib/private/TemplateLayout.php
> +			$signUpLink = $this->config->getSystemValueString('registration_link', $urlGenerator->getAbsoluteURL('/index.php/signup/'));
```suggestion
			$signUpLink = $this->config->getSystemValueString('registration_link', 'https://nextcloud.com/signup/');
```

2023-09-11 20:30 UTC, juliushaertl commented on lib/private/TemplateLayout.php
> +			$appManager = \OCP\Server::get(IAppManager::class);
We should also make sure that `showSimpleSignUpLink` assigned above is still true if a custom URL is configured.

2023-09-11 20:30 UTC, juliushaertl requested changes
Two small additions, otherwise this seems fine 👍

2023-09-15 12:00 UTC, juliushaertl approved these changes

2023-09-17 11:56 UTC, icewind1991 commented on lib/private/TemplateLayout.php
> +				$showSimpleSignup = true;
do we want to set this back to true if is was set to false on line 198?

2023-09-19 08:41 UTC, luka-nextcloud commented on lib/private/TemplateLayout.php
> +				$showSimpleSignup = true;
Yes, it should be. As juliushaertl has suggested [here](https://github.com/nextcloud/server/pull/40368/files/e92d396200e5536b2daa3d78c10e594b6ed5538e#r1322043083).

2023-10-31 08:45 UTC, mejo- approved these changes
Looks sensible :ok_hand:

2023-10-31 09:49 UTC, Altahrim approved these changes

2023-11-21 10:22 UTC, merged