Make logo in header clickable in the shared file view
nextcloud/server pull request #40439
Opened 2023-09-15 15:17 UTC by Koc

## Summary
Now we use same `logo_url` settings for shared file view that are used for normal user view.

![image](https://github.com/nextcloud/server/assets/191082/a4805906-65e4-4cc5-a0bd-01eec7997f4e)

## Open questions
- How to deal if `logo_url` is not configured? Use home link (like now) or make logo non-clickable?

## How to test
1. update `config/config.php` with
    ```php
      'logo_url' => 'https://google.com',
    ```
1. share file by creating public link
1. open shared link
1. click on logo

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-15 16:33 UTC, artonge approved these changes

2023-09-15 16:57 UTC, Fenn-CS approved these changes

2023-09-27 15:05 UTC, skjnldsv requested changes

2023-09-27 15:05 UTC, skjnldsv commented on core/templates/layout.public.php
> +				<a href="<?php print_unescaped($_['logoUrl'] ?: link_to('', 'index.php')); ?>"
Falling back to index.php seems counter intuitive.
You're in a public page, redirecting will ask the current user to log in. WHich make no sense in terms of context.

I would only set the link if logoUrl is set, otherwise have no link at all.

2023-10-03 21:36 UTC, Koc commented on core/templates/layout.public.php
> +				<a href="<?php print_unescaped($_['logoUrl'] ?: link_to('', 'index.php')); ?>"
done

2023-10-04 01:47 UTC, susnux approved these changes

2023-10-04 06:12 UTC, skjnldsv approved these changes

2023-10-04 06:49 UTC, merged