make Settings of Personal and Admin into own views
nextcloud/server pull request #40544
Opened 2023-09-20 18:43 UTC by privatemaker

This is my first PHP contribution to Nextcloud, as far as I can tell no tests were required, but if so please advise further. If accepted, this resolves #40490

## Summary

I created the following new methods in `CommonSettingsTrait.php`

- `getPersonalResponse()`
- `getAdminResponse()`

I think this is better than conditionals in `getIndexResponse` as it is more locked down ([no trailing elseif](https://github.com/nextcloud/server/blob/9a70c1e78ab55378421e24a53d34225f30529e18/apps/settings/lib/Controller/CommonSettingsTrait.php#L143-L145)) and makes room for future adjustments respective to only Personal or Admin areas. This comes at the expense of being slightly less DRY of repeated lines.

## Checklist

- [x] Screenshots in issue #40490
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-20 20:29 UTC, szaimen approved these changes
Thanks a lot for the contribution! Tested and works great! :)

2023-09-21 08:34 UTC, skjnldsv approved these changes

2023-09-21 08:36 UTC, nickvergessen commented on apps/settings/templates/settings/personal.php
> +		<li class="app-navigation-caption"><?php p($l->t('Personal')); ?></li>
Note: This is now always shown, while it before was only shown for admin users that saw both section blocks.

I would be okay with removing it, we don't have captions in other places if there is only 1 block

2023-09-21 08:37 UTC, skjnldsv reviewed
Please fix the indents issues. I see spaces and wrong indents ;)

2023-09-21 10:07 UTC, jancborchardt commented on apps/settings/templates/settings/personal.php
> +		<li class="app-navigation-caption"><?php p($l->t('Personal')); ?></li>
I’d say it’s still nice to have as a general info of where you are, especially now that we are newly splitting it. But I’m fine with either, if there is a strong preference. :)

2023-09-21 10:08 UTC, szaimen commented on apps/settings/templates/settings/personal.php
> +		<li class="app-navigation-caption"><?php p($l->t('Personal')); ?></li>
I would also keep it

2023-09-21 11:29 UTC, privatemaker commented on apps/settings/templates/settings/admin.php
> +				$anchor = \OC::$server->getURLGenerator()->linkToRoute('settings.AdminSettings.index', ['section' => $form['anchor']]);
@nickvergessen what is the policy on deprecations? Is this something I should fix in my pull-request since I am introducing a new file into the tree?

2023-09-21 11:32 UTC, privatemaker commented on apps/settings/templates/settings/personal.php
> +		<li class="app-navigation-caption"><?php p($l->t('Personal')); ?></li>
I think having a title heading for the larger section (Settings, Administration) that a user is in no matter the sub-section (Security, Appearance...) is good practice- hence my choice to leave this in.

2023-09-24 15:11 UTC, kesselb requested changes
[Admin right privilege / Administration privileges](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/admin_delegation_configuration.html) is broken.

2023-09-24 15:11 UTC, kesselb commented on apps/settings/tests/Controller/PersonalSettingsControllerTest.php
> +		$user = \OC::$server->getUserManager()->createUser($this->adminUid, 'mylongrandompassword');
This looks weird ;)

Adding `@group DB` says a test needs a database connection.
Afaict the test only works with mocked data and therefore does not require a db.

```
Index: apps/settings/tests/Controller/PersonalSettingsControllerTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/settings/tests/Controller/PersonalSettingsControllerTest.php b/apps/settings/tests/Controller/PersonalSettingsControllerTest.php
--- a/apps/settings/tests/Controller/PersonalSettingsControllerTest.php	(revision bb2353ae4a18e95dc4ca6346ad696c0e371453e5)
+++ b/apps/settings/tests/Controller/PersonalSettingsControllerTest.php	(date 1695568072588)
@@ -40,13 +40,6 @@
 use PHPUnit\Framework\MockObject\MockObject;
 use Test\TestCase;
 
-/**
- * Class PersonalSettingsControllerTest
- *
- * @group DB
- *
- * @package Tests\Settings\Controller
- */
 class PersonalSettingsControllerTest extends TestCase {
 
 	/** @var PersonalSettingsController */
@@ -76,16 +69,6 @@
 			$this->settingsManager,
 			$this->userSession,
 		);
-
-		$user = \OC::$server->getUserManager()->createUser($this->adminUid, 'mylongrandompassword');
-		\OC_User::setUserId($user->getUID());
-		// \OC::$server->getGroupManager()->createGroup('admin')->addUser($user);
-	}
-
-	protected function tearDown(): void {
-		// \OC::$server->getUserManager()->get($this->adminUid)->delete();
-
-		parent::tearDown();
 	}
 
 	public function testIndex() {
@@ -102,7 +85,10 @@
 		$idx = $this->personalSettingsController->index('test');
 
 		$expected = new TemplateResponse('settings', 'settings/personal', [
-			'forms' => ['personal' => []],
+			'forms' => [
+				'personal' => [],
+				'admin' => [],
+			],
 			'content' => ''
 		]);
 		$this->assertEquals($expected, $idx);
Index: apps/settings/tests/Controller/AdminSettingsControllerTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/settings/tests/Controller/AdminSettingsControllerTest.php b/apps/settings/tests/Controller/AdminSettingsControllerTest.php
--- a/apps/settings/tests/Controller/AdminSettingsControllerTest.php	(revision bb2353ae4a18e95dc4ca6346ad696c0e371453e5)
+++ b/apps/settings/tests/Controller/AdminSettingsControllerTest.php	(date 1695568055144)
@@ -27,6 +27,7 @@
 namespace OCA\Settings\Tests\Controller;
 
 use OCA\Settings\Controller\AdminSettingsController;
+use OCA\Settings\Settings\Personal\ServerDevNotice;
 use OCP\AppFramework\Http\TemplateResponse;
 use OCP\Group\ISubAdmin;
 use OCP\IGroupManager;
@@ -38,13 +39,6 @@
 use PHPUnit\Framework\MockObject\MockObject;
 use Test\TestCase;
 
-/**
- * Class AdminSettingsControllerTest
- *
- * @group DB
- *
- * @package Tests\Settings\Controller
- */
 class AdminSettingsControllerTest extends TestCase {
 
 	/** @var AdminSettingsController */
@@ -62,7 +56,6 @@
 	/** @var ISubAdmin|MockObject */
 	private $subAdmin;
 	/** @var string */
-	private $adminUid = 'lololo';
 
 	protected function setUp(): void {
 		parent::setUp();
@@ -83,16 +76,6 @@
 			$this->groupManager,
 			$this->subAdmin
 		);
-
-		$user = \OC::$server->getUserManager()->createUser($this->adminUid, 'mylongrandompassword');
-		\OC_User::setUserId($user->getUID());
-		\OC::$server->getGroupManager()->createGroup('admin')->addUser($user);
-	}
-
-	protected function tearDown(): void {
-		\OC::$server->getUserManager()->get($this->adminUid)->delete();
-
-		parent::tearDown();
 	}
 
 	public function testIndex() {
@@ -115,10 +98,6 @@
 			->willReturn([]);
 		$this->settingsManager
 			->expects($this->once())
-			->method('getPersonalSections')
-			->willReturn([]);
-		$this->settingsManager
-			->expects($this->once())
 			->method('getAllowedAdminSettings')
 			->with('test')
 			->willReturn([5 => $this->createMock(ServerDevNotice::class)]);
@@ -126,7 +105,10 @@
 		$idx = $this->adminSettingsController->index('test');
 
 		$expected = new TemplateResponse('settings', 'settings/admin', [
-			'forms' => ['admin' => []],
+			'forms' => [
+				'personal' => [],
+				'admin' => [],
+			],
 			'content' => ''
 		]);
 		$this->assertEquals($expected, $idx);
```

2023-09-25 14:48 UTC, nickvergessen commented on apps/settings/composer/composer/installed.php
> +        'reference' => '1b774d74ea236e5c276211ee4916484f931eedba',
happens by `bash build/autoloader…`
It's okay

2023-09-29 06:40 UTC, JuliaKirschenheuter commented
Please adapt your changes to two independent `nav`'shttps://github.com/nextcloud/server/pull/40576/files 
Thank you!

2024-08-03 16:43 UTC, closed without merging