[PoC] inline svg files
nextcloud/server pull request #4059
Opened 2017-03-25 21:33 UTC by rullzer

Saves loading a lot of resources. And since the css file is cached
anyway this can save precious seconds.

Todo:
- [ ] CI job to check
- [ ] Look for more files to use
- [ ] Some places we use background-url but in some places we still use img stags. The img tags can't be repalced by this method.

@ChristophWurst as discussed.

2017-03-26 06:15 UTC, MorrisJobke commented on core/css/iconsinline.scss
> + * @license GNU AGPL version 3 or any later version
Could we add a message here saying: "This file is automatically generated"?

2017-03-26 06:16 UTC, MorrisJobke commented on build/inlineicons.php
> +<?php
Also execute this on CI and throw an error if there is a change. 😉

2017-03-26 06:17 UTC, MorrisJobke requested changes
Some refinements, but looks good code wise :)

2017-03-26 06:24 UTC, MorrisJobke commented
This alone removes 13 of 129 requests of the files app (10%) 🙌

2017-03-26 07:43 UTC, rullzer commented on build/inlineicons.php
> +<?php
Yeah was thinking about that as well of course

2017-03-28 23:30 UTC, MorrisJobke commented
May be an alternative to #3790

2017-03-29 17:29 UTC, jancborchardt commented
We would need a way that the »build process« for this is automated. Also, the icons.scss file has other things than just .svg links. :)

2017-03-29 17:30 UTC, rullzer commented
Lets kill this. We can only do this properly if we would have a compile step or something for it (like scss or javascript). For now not worth it I think...

2017-03-29 17:30 UTC, closed without merging

2017-04-04 20:20 UTC, jancborchardt commented
Ref https://github.com/nextcloud/server/issues/1066 if we want to work on anything like that again. :)