fix(userstatus): Sync migration version number with app version
nextcloud/server pull request #40614
Opened 2023-09-25 12:25 UTC by ChristophWurst

## Summary

The migration version number was synced with server in https://github.com/nextcloud/server/pull/28403. The app was at 1.3.0. Now we are at 1.8.0 and it just feels wrong to continue the out-of-sync naming in https://github.com/nextcloud/server/pull/40564.

Renaming causes the migration to run again if it hasn't run already. It's adjusted to not cause an issue in that case.

I'm also open for other ideas that bring the versioning state into consistency.

## TODO

- [x] Adjust version number
- [x] Test an upgrade/migration

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-25 14:27 UTC, nickvergessen approved these changes
🙈

2023-09-25 14:28 UTC, nickvergessen requested changes

2023-09-25 14:28 UTC, nickvergessen commented on apps/user_status/lib/Migration/Version1030Date20210809144824.php
> +class Version1030Date20210809144824 extends SimpleMigrationStep {
If the app was `1.3.0` the expected name would be:
```suggestion
class Version1003Date20210809144824 extends SimpleMigrationStep {
```

2023-09-26 11:40 UTC, nickvergessen approved these changes

2023-09-26 11:53 UTC, st3iny approved these changes
LGTM!

2023-09-26 13:22 UTC, kesselb approved these changes

2023-09-26 13:46 UTC, ChristophWurst commented
mysql job timed out after 1h -> ignore

2023-09-26 13:46 UTC, merged