Adding dav resource for avatars
nextcloud/server pull request #4062
Opened 2017-03-26 03:42 UTC by MorrisJobke

* downstream of https://github.com/owncloud/core/pull/26872

@rullzer @mario @marinofaggiana @AndyScherzinger @tobiasKaminsky Might be interesting for you. Then you don't need  private APIs anymore and can also fetch it via WebDAV ;)

2017-03-26 06:39 UTC, MariusBluem commented
@schiessle for federated profile pictures in sharing dialog 😁

2017-03-26 07:28 UTC, rullzer commented
So, few things.

* WHEE!
* The extension might be problematic for clients
* I'm not really happy this loads the image resource into memory again. We should just dump the file.

Anyway. Will look into it.

2017-03-26 09:27 UTC, LukasReschke requested changes
Will do some changes to satisfy coverage and CI style.

2017-03-26 09:34 UTC, LukasReschke approved these changes

2017-03-26 10:10 UTC, rullzer requested changes

2017-03-26 10:10 UTC, rullzer commented on apps/dav/lib/Avatars/AvatarNode.php
> +		$image = $this->avatar->get($this->size);
I don't like this as it gets an image. Instead of just a file...

2017-03-26 10:11 UTC, rullzer commented
Also no caching headers are set. Which would mean that if we switch over this will result in a shitload of requests to the server again

2017-03-26 10:18 UTC, rullzer commented
Altough I'm not sure how we can set caching headers....

2017-03-26 13:37 UTC, LukasReschke requested changes

2017-03-26 13:37 UTC, LukasReschke commented on apps/dav/lib/Avatars/AvatarNode.php
> +			impagejpeg($res);
Message: Call to undefined function OCA\DAV\Avatars\impagejpeg()

@rullzer 😉 – Also time to add tests to this 😝

2017-03-26 13:45 UTC, LukasReschke commented
> Altough I'm not sure how we can set caching headers....

Probably something like `\OCA\DAV\CardDAV\ImageExportPlugin`?

2017-03-29 09:23 UTC, rullzer approved these changes

2017-03-29 09:24 UTC, rullzer commented
Ok lets get this in and fixup the remaining stuff later.

2017-03-29 16:30 UTC, MorrisJobke commented
Tested and works 👍

2017-03-29 16:30 UTC, merged