Set visible label for input field
nextcloud/server pull request #40643
Opened 2023-09-26 14:34 UTC by JuliaKirschenheuter

* Part of https://github.com/nextcloud/server/issues/37082

## Summary

Set visible label for input field (probably not so nice, but this is an old implementation and this have to be accessible too)

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2023-09-26 16-17-56](https://github.com/nextcloud/server/assets/6078378/c7254982-859a-4492-9e95-0a8ad32bd871) | ![Screenshot from 2023-09-26 16-17-36](https://github.com/nextcloud/server/assets/6078378/0b684272-e66e-449d-aea3-9c0a35a1d131)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-26 14:56 UTC, ShGKme commented
Looks a bit weird... Would it be valid here to use "This action requires you to confirm your password" as a label?

2023-09-26 21:22 UTC, artonge approved these changes

2023-09-27 10:04 UTC, JuliaKirschenheuter commented
> Looks a bit weird... Would it be valid here to use "This action requires you to confirm your password" as a label?

I think "This action requires you to confirm your password" is too long for a label. That would change width of modal window too.
Would you have some other suggestion? But actually we can do all improvements after a11y certification.

2023-09-27 15:57 UTC, JuliaKirschenheuter commented
@nimishavijay would you approve it?

2023-09-27 16:35 UTC, nimishavijay commented
Would using a password field with an internal label work? 


https://github.com/nextcloud/server/assets/52440189/8c4f237a-f1ea-4f4f-aa4a-a8dd8454a3db


If not, then I propose the following changes:

![image](https://github.com/nextcloud/server/assets/52440189/28b44868-3281-4960-9bff-103ec848631b)

- [ ] Change heading to "Confirm your password"
- [ ] Change subline to "This action needs authentication"
- [ ] Use an external label, but on the same row as the input field

2023-10-05 12:06 UTC, ShGKme requested changes

2023-10-05 12:06 UTC, ShGKme commented on core/src/OC/password-confirmation.js
After migrating got `@nextcloud/password-confirmation` all the private methods and properties are not used anymore.

So we need to remove as well:
- [ ] properties:
  - [ ] `callback`
  - [ ] 'pageLoadTime'
- [ ] `init` method and its usage in `src/core/init.js`
  - [ ] including its usage
- [ ] `_confirmPassword`

---

`requiresPasswordConfirmation` is still needed, but its implementation must be replaced with `isPasswordConfirmationRequired` from the same package

---

Then, I think we should also mark these methods of OC as deprecated in favor of the package

2023-10-05 12:22 UTC, JuliaKirschenheuter commented on core/src/OC/password-confirmation.js
> * pageLoadTime

If i would remove `pageLoadTime` then i have to remove ore replace `serverTimeDiff` and `timeSinceLogin` as well as `requiresPasswordConfirmation` method. Should i remove all this logic?

2023-10-06 14:44 UTC, ShGKme approved these changes

2023-10-06 14:45 UTC, ShGKme commented
@artonge Do you want to re-review after a large change?

2023-10-06 16:33 UTC, susnux approved these changes

2023-10-06 17:25 UTC, Pytal commented on core/src/OC/password-confirmation.js
> +import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
`isPasswordConfirmationRequired` is not exported https://github.com/nextcloud-libraries/nextcloud-password-confirmation/blob/607a4f425adcff19f6ea56df1d4ba13762129ee0/src/main.ts#L10 ?

2023-10-06 18:54 UTC, ShGKme commented on core/src/OC/password-confirmation.js
> +import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
nice catch

2023-10-09 08:13 UTC, JuliaKirschenheuter commented on core/src/OC/password-confirmation.js
> +import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
needs new release https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/614

2023-10-09 08:49 UTC, JuliaKirschenheuter commented on core/src/OC/password-confirmation.js
> +import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/609

2023-10-09 16:25 UTC, ShGKme commented on core/src/OC/password-confirmation.js
> +import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
We also need to import styles here.

It works because they were already imported from another place, but we cannot count on that:
- May break if another place changes
- May break on chunks separating

```suggestion
import { confirmPassword, isPasswordConfirmationRequired } from '@nextcloud/password-confirmation'
import '@nextcloud/password-confirmation/style.css'
```

2023-10-12 23:02 UTC, Pytal approved these changes
Still needs https://github.com/nextcloud/server/pull/40874

Otherwise good

2023-10-17 14:54 UTC, ShGKme commented
Cypress `users_modify` seems to be a flaky test, works fine locally:
![image](https://github.com/nextcloud/server/assets/25978914/eee6433a-f438-4cf6-b85a-d1e1a503dc66)

Another test is a known problem

2023-10-17 14:55 UTC, JuliaKirschenheuter commented
failing tests are unrelated

2023-10-17 14:55 UTC, merged