feat(database): Add replacements for deprecated fetch and fetchAll
nextcloud/server pull request #40655
Opened 2023-09-27 12:36 UTC by ChristophWurst

## Summary

DBAL deprecated these and will remove them it in the future.

## TODO

- [x] Add missing methods
- [x] Delegate deprecations

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
  - https://github.com/nextcloud/documentation/pull/11183
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-27 12:47 UTC, nickvergessen requested changes

2023-09-27 12:47 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @since 21.0.0
```suggestion
	 * @since 28.0.0
```

2023-09-27 12:47 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	public function fetchFirstColumn(): array;
should be mixed?

2023-09-27 12:47 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @return list<list<mixed>>
Wrong comment and return type

2023-09-27 12:47 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAssociative, fetchNumeric or fetchOne
This will be painful :D 
Touching all the queries yet again (after query() replacement)

2023-09-27 12:55 UTC, ChristophWurst commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAssociative, fetchNumeric or fetchOne
https://getrector.com/

2023-10-05 11:30 UTC, ChristophWurst commented on lib/public/DB/IResult.php
> +	public function fetchFirstColumn(): array;
it returns the first column of all results as array<mixed>

2023-10-05 13:32 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * Returns an array containing all of the result rows represented as numeric arrays
comment is the same as from `fetchAllNumeric(` ?

2023-10-06 04:39 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAssociative, fetchNumeric or fetchOne
Also use the deprecation line from the docs here explaining the default replacement?

2023-10-06 09:46 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAssociative instead of fetch(), fetchNumeric instead of fetch(\PDO::FETCH_NUM) and fetchOne instead of fetch(\PDO::FETCH_COLUMN)
```suggestion
	 * @deprecated 28.0.0 use fetchAssociative instead of fetch(), fetchNumeric() instead of fetch(\PDO::FETCH_NUM) and fetchOne() instead of fetch(\PDO::FETCH_COLUMN)
```

## 🤪

2023-10-06 09:46 UTC, nickvergessen commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAllAssociative instead of fetchAll(), fetchAllNumeric instead of fetchAll(FETCH_NUM) and fetchOne instead of fetchAll(FETCH_COLUMN)
```suggestion
	 * @deprecated 28.0.0 use fetchAllAssociative instead of fetchAll(), fetchAllNumeric() instead of fetchAll(FETCH_NUM) and fetchFirstColumn() instead of fetchAll(FETCH_COLUMN)
```


## 🤪

2023-10-06 11:25 UTC, ChristophWurst commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAllAssociative instead of fetchAll(), fetchAllNumeric instead of fetchAll(FETCH_NUM) and fetchOne instead of fetchAll(FETCH_COLUMN)
I'm tired, boss

2023-10-06 11:29 UTC, blizzz commented on lib/public/DB/IResult.php
> +	 * @deprecated 28.0.0 use fetchAssociative instead of fetch(), fetchNumeric instead of fetch(\PDO::FETCH_NUM) and fetchOne instead of fetch(\PDO::FETCH_COLUMN)
and more brackets for lonely `fetchAssociative`!

2023-10-06 11:32 UTC, blizzz commented on lib/public/DB/IResult.php
> +	public function fetchFirstColumn(): array;
The description is not phrased clearly about that imo, and for better consistency perhaps consider renaming the method to  `fetchAllFirstColumns` or something like that?

2026-05-20 19:04 UTC, ChristophWurst commented
Superseded by #56494

2026-05-20 19:04 UTC, closed without merging