fix(autocomplete): Fix missing user status on autocomplete endpoint
nextcloud/server pull request #40660
Opened 2023-09-27 14:42 UTC by nickvergessen

* Discovered by @Antreesy when working with participant suggestions in Talk

## Summary

Regression from https://github.com/nextcloud/server/commit/1be836273ddba6e0ddb3509a1d898535df9fd169#diff-8a51ce62a02e28659acaa3f84252600107a22d2eb093d950f2c9c16fe6b96c8e 
It seems the "empty string" default had confused @provokateurin but the status value was actually always an array, as per: https://github.com/nextcloud/server/blob/6427863443883c434ed39a16ec0531abd746fad6/lib/private/Collaboration/Collaborators/UserPlugin.php#L155-L162

I now added an integration test to confirm it's working and stays working. I left the default/empty value untouched as empty string and basically restored the array data when a status is present.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-27 14:45 UTC, provokateurin commented
So it can be a string that is just the same object in JSON? I still can't make sense of this API

2023-09-27 14:47 UTC, nickvergessen commented
> So it can be a string that is just the same object in JSON? I still can't make sense of this API

No, it's a empty-string or an array as per OpenAPI doc block.

The JSON object is just used in Integration tests, because Behat can not handle nested arrays in TableNodes, so I json-encode the status array there

2023-09-27 14:50 UTC, provokateurin commented
I see, but why the empty string instead of just null? This makes the API way more complex than it needs to be (although this is probably just for historical reasons).

2023-09-27 14:53 UTC, nickvergessen commented
> I see, but why the empty string instead of just null?

Because it was [empty string since adding the values back in 2021](https://github.com/nextcloud/server/commit/83755b7b02bc6f1a76f46a732b2595c0c5326346) and yes I might have made a mistake there. But now clients could rely on it.

> This makes the API way more complex than it needs to be (although this is probably just for historical reasons).

## 🤷🏼

2023-09-27 14:55 UTC, provokateurin approved these changes

2023-09-27 15:04 UTC, provokateurin requested changes

2023-09-27 15:05 UTC, marcelklehr approved these changes

2023-09-27 15:12 UTC, Antreesy approved these changes
tested against Talk app:

B | A
-- | --
![Screenshot from 2023-09-27 17-10-53](https://github.com/nextcloud/server/assets/93392545/09165a03-03b4-4ed5-840b-6ece30efa314) | ![Screenshot from 2023-09-27 17-09-55](https://github.com/nextcloud/server/assets/93392545/bae9d558-fedd-4ac9-ae25-39e837160af8)

2023-09-28 11:56 UTC, provokateurin approved these changes

2023-09-28 12:03 UTC, nickvergessen commented on core/Controller/AutoCompleteController.php
>  				/** @var ?string $status */
Had to go with 
```
				/** @var ?array{status: string, message: ?string, icon: ?string, clearAt: ?int} $status */
```

Otherwise psalm complained

2023-10-04 08:12 UTC, merged