Correct typos and add quotation marks
nextcloud/server pull request #40698
Opened 2023-09-29 07:51 UTC by Valdnet

Corrects typos and unifies spelling for "occ" commands.

2023-09-29 10:17 UTC, blizzz approved these changes

2023-09-29 11:03 UTC, rakekniven approved these changes

2023-09-29 11:15 UTC, blizzz commented
there is at least one pedantic test that also needs updating: OCA\Settings\Tests\Controller\CheckSetupControllerTest::testCheck

2023-09-29 11:15 UTC, blizzz requested changes
CI fix

2023-09-29 12:01 UTC, miaulalala approved these changes

2023-10-02 15:47 UTC, Valdnet commented
> there is at least one pedantic test that also needs updating: OCA\Settings\Tests\Controller\CheckSetupControllerTest::testCheck

Done 😉.

2023-10-02 16:18 UTC, rakekniven approved these changes

2023-10-03 17:15 UTC, miaulalala approved these changes

2023-10-10 23:48 UTC, susnux approved these changes

2023-10-11 13:25 UTC, merged