Remove space
nextcloud/server pull request #40700
Opened 2023-09-29 08:00 UTC by Valdnet

2023-09-29 09:54 UTC, rakekniven approved these changes

2023-09-29 09:57 UTC, szaimen approved these changes

2023-09-29 09:58 UTC, szaimen commented
/compile

2023-09-29 10:15 UTC, blizzz requested changes

2023-09-29 10:15 UTC, blizzz commented on apps/files_sharing/src/views/SharingDetailsTab.vue
>  				title = title + this.share.shareWithDisplayName
correct me if i am wrong, but the space is missing then here where it is concatenated with the display name.  At least here, didn't check further.
```suggestion
			let title = t('files_sharing', 'Share with') + " "
			if (this.share.type === this.SHARE_TYPES.SHARE_TYPE_USER) {
				title = title + this.share.shareWithDisplayName
```

2023-10-04 10:37 UTC, szaimen commented
@Valdnet this needs a manual rebase and then you can run the compile command again

2023-10-04 11:17 UTC, blizzz commented
@nickvergessen was my suggestion actually ok, or are there smarter/better ways? perhaps also with RTL in mind?

2023-10-04 12:49 UTC, nickvergessen commented on apps/files_sharing/src/views/SharingDetailsTab.vue
>  				title = title + this.share.shareWithDisplayName
As per https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#improving-your-translations this is not good.
It would be better to have a full t() in each of the else-if branches?

2023-11-06 21:26 UTC, AndyScherzinger commented
@Valdnet do you want to take care of the manual rebase and fix the issues from the comments or close and started from scratch?

2023-11-07 14:38 UTC, closed without merging