feat: Email option in `occ use:add` command
nextcloud/server pull request #40726
Opened 2023-09-30 06:27 UTC by kyteinsky

* Resolves: #25319 

## Summary
Builds upon #29368 

This adds an occ command option (`email`) during the addition of a user to auto-generate a password and send it to the email address provided along with a password reset link if:
1. `password-from-env` option was not passed
2. `email` is given and valid

## Docs
* Related: [docs#11160](https://github.com/nextcloud/documentation/pull/11160)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-09-30 10:07 UTC, nickvergessen requested changes

2023-09-30 10:07 UTC, nickvergessen commented on core/Command/User/Add.php
> +use Egulias\EmailValidator\EmailValidator;
Please use the public API instead
https://github.com/nextcloud/server/blob/master/lib/public/Mail/IMailer.php#L103C17-L103C17

2023-09-30 10:07 UTC, nickvergessen commented on tests/Core/Command/User/AddTest.php
> +		yield 'Valid E-Mail' => [
Please don't yield. Just return an array

2023-09-30 20:57 UTC, nickvergessen commented on core/register_command.php
> +	), \OC::$server->get(\OCP\Mail\IMailer::class), \OC::$server->get(\OC\AllConfig::class), \OC::$server->get(\OCA\Settings\Mailer\NewUserMailHelper::class), \OC::$server->get(\OCP\EventDispatcher\IEve
```suggestion
	$application->add(\OCP\Server::get( OC\Core\Command\User\Add::class));
```

2023-10-02 08:21 UTC, come-nc commented on core/Command/User/Add.php
> +		private ISecureRandom $secureRandom
```suggestion
		private ISecureRandom $secureRandom,
```

2023-10-02 08:21 UTC, come-nc commented on core/register_command.php
> +	$application->add(\OC::$server->get(\OC\Core\Command\User\Add::class));
```suggestion
	$application->add(\OCP\Server::get(\OC\Core\Command\User\Add::class));
```

2023-10-02 08:21 UTC, come-nc commented on core/Command/User/Add.php
> +			$user->setSystemEMailAddress($email);
The call to setSystemEMailAddress should be done even if core/newUser.sendEmail is no. Or it should trigger an error if `--email` is set while `newUser.sendEmail` is off.

2023-10-04 09:48 UTC, nickvergessen approved these changes
Not blocking, but with the comments the code would be simpler/easier to read in the future

2023-10-04 09:48 UTC, nickvergessen commented on core/Command/User/Add.php
> +		} elseif (\mb_strlen($input->getOption('email')) > 0) {
![grafik](https://github.com/nextcloud/server/assets/213943/266a9a00-665f-48da-a7e3-b00278fe6610)

```suggestion
		} elseif ($input->getOption('email') !== '') {
```

2023-10-04 09:48 UTC, nickvergessen commented on core/Command/User/Add.php
> +			$output->writeln(\sprintf('Display name set to "%s"', $user->getDisplayName()));
```suggestion
			$output->writeln('Display name set to "' . $user->getDisplayName() . '"');
```

Keep it simple? :)

2023-10-10 08:53 UTC, come-nc requested changes
This is still not good for when `newUser.sendEmail` is off, this will generate a random password but not send it.
Using `--email` should not change how password is handled, unless `newUser.sendEmail` is on and `password-from-env` was not given.

This needs to work and set email:
`occ user:add --password-from-env --email bob@example.com bob`
This needs to work and set email, if `newUser.sendEmail` is off it should ask for password same as without `--email`:
`occ user:add --email bob@example.com bob`

2024-02-26 08:12 UTC, come-nc approved these changes

2024-02-26 08:23 UTC, kyteinsky commented
is performance regression something to worry about? Seems unrelated to this PR.

2024-02-26 10:50 UTC, merged

2024-02-26 10:50 UTC, come-nc commented
> is performance regression something to worry about? Seems unrelated to this PR.

It is unrelated.

2024-02-26 11:39 UTC, b3nks commented
Great! Thanks a lot for that! :blue_heart: