adjust color of focus-visible to be better visible
nextcloud/server pull request #40783
Opened 2023-10-05 10:17 UTC by szaimen

Fix https://github.com/nextcloud/server/issues/40710

2023-10-05 13:27 UTC, JuliaKirschenheuter reviewed
should we use a same styles as from https://github.com/nextcloud-libraries/nextcloud-vue/issues/4193 like (?)


`outline: 2px solid var(--color-main-text) !important;
 box-shadow: 0 0 0 4px var(--color-main-background) !important;
`

2023-10-05 13:28 UTC, szaimen commented
> should we use a same styles as from [nextcloud-libraries/nextcloud-vue#4193](https://github.com/nextcloud-libraries/nextcloud-vue/issues/4193) like (?)
> 
> `outline: 2px solid var(--color-main-text) !important; box-shadow: 0 0 0 4px var(--color-main-background) !important; `

I don't think this is needed here honestly :)

2023-10-05 13:29 UTC, JuliaKirschenheuter requested changes
i think then we would be on a same state like everywhere else

2023-10-05 13:29 UTC, JuliaKirschenheuter commented on core/css/apps.scss
> +				box-shadow: var(--color-main-text) inset 0 0 0 2px;
outline: 2px solid var(--color-main-text) !important;
		box-shadow: 0 0 0 4px var(--color-main-background) !important;

2023-10-05 13:31 UTC, JuliaKirschenheuter commented
@jancborchardt what would you say?

2023-10-05 14:19 UTC, jancborchardt commented
I'd agree with you @JuliaKirschenheuter, we should have it consistently everywhere with the black + white border as this catches all cases and is very visible.

2023-10-06 14:06 UTC, szaimen commented on core/css/apps.scss
> +				box-shadow: var(--color-main-text) inset 0 0 0 2px;
done

2023-10-06 14:18 UTC, susnux approved these changes

2023-10-09 14:31 UTC, JuliaKirschenheuter approved these changes
could you please build everything?

2023-10-09 14:40 UTC, szaimen commented
> could you please build everything?

Yes, will do a rebase and build and merge :)

2023-10-09 14:41 UTC, szaimen commented
/compile amend /

2023-10-09 15:20 UTC, szaimen commented
/compile amend /

2023-10-09 16:48 UTC, merged