Pass IConfig by constructor to Group_LDAP
nextcloud/server pull request #40839
Opened 2023-10-09 20:32 UTC by blizzz

Addendum to #40443 – injects `IConfig` as DI to `Group_LDAP` and in this act simplifies the unit tests somewhat, reducing duplication.

2023-10-10 08:36 UTC, come-nc requested changes

2023-10-10 08:36 UTC, come-nc commented on apps/user_ldap/tests/Group_LDAPTest.php
> +		$this->config = $this->createMock(IConfig::class);
Dynamic properties? :skull:

2023-10-10 08:36 UTC, come-nc commented on apps/user_ldap/tests/Group_LDAPTest.php
> +		$this->groupBackend = new GroupLDAP($this->access, $this->pluginManager, $this->config);
Also missing property

2023-10-10 08:39 UTC, blizzz commented on apps/user_ldap/tests/Group_LDAPTest.php
> +		$this->config = $this->createMock(IConfig::class);
Ha, IDE did not show warning, as it should.

2023-10-10 12:44 UTC, come-nc approved these changes

2023-10-11 12:05 UTC, blizzz commented
merging into #40443  as i have a follow up needed for that, based on this work.

2023-10-11 12:05 UTC, merged