feat: Allow to configure the app menu order in the frontend
nextcloud/server pull request #40844
Opened 2023-10-09 22:34 UTC by susnux

* Resolves: #4917 

## Summary
Front end of the app ordering feature.

This allows to define the app order in the main menu bar on a per-user basis (backend see https://github.com/nextcloud/server/pull/40617 ).

### Screencast

https://github.com/nextcloud/server/assets/1855448/de6267ae-626c-45aa-81ee-23d1918265c4

**If the admin set up a default app, it will be shown as the first list element but the user can not modify it:**
![image](https://github.com/nextcloud/server/assets/1855448/3e813235-4cc1-49c9-8a56-47f4f074427b)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-10 10:08 UTC, come-nc requested changes
(I did not review the code of frontend part)

I tested and there is an issue with the admin defined default apps, if the admin sets several default apps, they all appear as greyed out in the user configuration screen, while the order is actually not this one.

Setting several default apps is only useful for fallback when an application is not enabled for a user.

If you want to change that to allow the admin to force the order, it needs to be taken into account by the UI which is not currently the case.

Also when setting admin default app after user defined apporder, default app appears first in settings but not in menu. Not sure where/how to fix that properly. Does backend need to be modified to always show default app first in menu?

2023-10-10 10:08 UTC, come-nc commented on lib/private/App/AppManager.php
> +	public function setDefaultAppForUser(?string $appId, ?IUser $user = null): void {
Is that used?
core/defaultapp is kind of deprecated since it will fallback on first app if not set, and the UI advertise that first one is always default.
So the UI should only empty core/defaultapp whenever apporder is set, never set it.

2023-10-10 10:08 UTC, come-nc commented on apps/theming/lib/Listener/BeforePreferenceListener.php
> +		private AppManager $appManager,
```suggestion
		private IAppManager $appManager,
```
Only use OCP from applications

2023-10-10 10:22 UTC, susnux commented on apps/theming/lib/Listener/BeforePreferenceListener.php
> +					return;
Yes it is not needed as it default to false.
I just did this like the previous code by only setting true if valid, but not false.

2023-10-10 15:08 UTC, come-nc commented on apps/theming/lib/Listener/BeforePreferenceListener.php
> +					return;
Please add the comment for future code readers.

2023-10-10 15:13 UTC, come-nc reviewed
It is now working perfectly.
The json version in the setting switched to string keys, not sure if intended?
It’s not a big deal as for PHP JSON objects and arrays are the same thing. I just noticed `[1]` became `{"0":1}`

2023-10-10 15:14 UTC, come-nc commented on lib/private/NavigationManager.php
> +		$defaultApp = $this->appManager->getDefaultAppForUser($this->userSession->getUser(), false);
Trouble here it seems ^

2023-10-10 15:28 UTC, susnux commented on lib/private/NavigationManager.php
> +		$defaultApp = $this->appManager->getDefaultAppForUser($this->userSession->getUser(), false);
@come-nc yes but not sure:
1. Make that second parameter public API
2. Switch NavigationManager to use OC\App\AppManager directly

The doc comment already has set the AppManager as value...

2023-10-10 15:38 UTC, come-nc commented on lib/private/NavigationManager.php
> +		$defaultApp = $this->appManager->getDefaultAppForUser($this->userSession->getUser(), false);
Seems easier and cleaner to just add it to the interface.
Add a comment for when the parameter was added like https://github.com/nextcloud/server/blob/54a286f76d800915b830a45461540bffa1b031f0/lib/public/Share/IManager.php#L327

2023-10-10 23:22 UTC, susnux commented on lib/private/NavigationManager.php
> +					] : []),
Fixed (sadly we still need PHP 8.0)

2023-10-10 23:25 UTC, susnux commented on apps/theming/lib/Listener/BeforePreferenceListener.php
> +					return;
done

2023-10-12 08:00 UTC, come-nc approved these changes

2023-10-12 11:11 UTC, szaimen reviewed
Tested and seems to generally work fine and generally looks good from design perspective. However some small remarks. See below

2023-10-12 11:11 UTC, szaimen commented on apps/theming/src/components/AppOrderSelectorElement.vue
> +import IconChevronUp from 'vue-material-design-icons/ChevronUp.vue'
Can we please use ArrowDown and ArrowUp like in my mockup? I think chevorns are usually rather used for expanding which it does not here :)

2023-10-12 11:11 UTC, szaimen commented on apps/theming/src/components/UserAppMenuSection.vue
> +	<NcSettingsSection :name="t('theming', 'App menu settings')">
Maybe we should rather name it Navigation Bar settings to be consistent with the text below?

2023-10-12 11:11 UTC, szaimen commented on apps/theming/src/components/admin/AppMenuSection.vue
> +	<NcSettingsSection :name="t('theming', 'App menu settings')">
Maybe we should rather name it Navigation Bar settings to be consistent with the text below?

2023-10-12 11:11 UTC, szaimen commented on apps/theming/src/components/admin/AppMenuSection.vue
> +	<NcSettingsSection :name="t('theming', 'App menu settings')">
or rather default app settings for navigation bar?

2023-10-18 07:19 UTC, skjnldsv approved these changes
Works fine, but:
- [ ] When keyboard-navigating, clicking an arrow loses focus. We should keep the focus to one of those items
- [ ] There is no way to reset the default order (nor to know the initial order)

2023-10-18 10:17 UTC, szaimen approved these changes
LGTM from design perspective :)

2023-10-19 20:03 UTC, susnux commented
> * [ ]  When keyboard-navigating, clicking an arrow loses focus. We should keep the focus to one of those items
> 
>     * [ ]  There is no way to reset the default order (nor to know the initial order)

Will do so in a follow up as this PR is already to crowded.

2023-10-19 22:54 UTC, merged

2024-02-20 22:25 UTC, ichier commented
> > * [ ]   When keyboard-navigating, clicking an arrow loses focus. We should keep the focus to one of those items
> > * [ ]   There is no way to reset the default order (nor to know the initial order)
> 
> Will do so in a follow up as this PR is already to crowded.

its great that all this has been adressed! thanx! works like a charm.
and its a nice feature, that even users can do it. but way more important is, that admins can set up a reasonable default that makes sense. (Only powerusers sort stuff themselves, normal people suffer from bad to memorize UI.)
i'm now migrating to 28 (after just having it tested) and i can initially set our previous apporder for all users via SQL. but i don't wanna do it manually for every new user that might come.
would be great if added! i personally don't need UI for that, config.php would be just fine. (and should be quite simple then?)

2024-02-20 22:28 UTC, susnux commented
@ichier feel free to open a feature request issue here to keep that tracked.

BTW the two points you quoted are resolved.

2025-02-25 22:21 UTC, Felitendo commented
@susnux this is great, but is there also a way to set the default order for every nextcloud user? I would really need this feature

2025-03-01 19:10 UTC, susnux commented
@Felitendo as you can read one comment above - no there is no way for a admin defined default, you can make this part of your provisioning process.
Feel free to open a feature request though.