Change `flex-direction` for input field
nextcloud/server pull request #40872
Opened 2023-10-11 14:26 UTC by JuliaKirschenheuter

* Part of https://github.com/nextcloud/server/issues/36965

Change `flex-direction` to prevent horizontal scrolling

## Summary

🏚️ Before | 🏡 After
---|---
![image](https://github.com/nextcloud/server/assets/6078378/f6bf3337-3961-4a65-8cf7-205455c3d73e) | ![Screenshot from 2023-10-11 16-14-58](https://github.com/nextcloud/server/assets/6078378/4fc72484-3b23-40f0-a797-6fd0f183417e)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-11 15:04 UTC, szaimen requested changes
This does not seem to work for me:
![image](https://github.com/nextcloud/server/assets/42591237/c7dad5b1-dd85-4bc2-9f2b-f35598375bb2)

2023-10-11 15:04 UTC, szaimen commented on apps/user_status/src/components/ClearAtSelect.vue
> +	}
I think media queries need to be at root and cannot be put into any class or anything...

2023-10-12 08:23 UTC, JuliaKirschenheuter commented on apps/user_status/src/components/ClearAtSelect.vue
> +	}
made alternative solution

2023-10-12 08:51 UTC, szaimen approved these changes
Works fine now in my testing. 

However this detail still looks a bit weird, however could potentially be fixed in a follow-up:

![image](https://github.com/nextcloud/server/assets/42591237/d375756b-f647-4439-9cb6-cb4ff430779f)

2023-10-12 18:37 UTC, Pytal approved these changes

2023-10-16 11:27 UTC, ShGKme approved these changes

2023-10-16 11:28 UTC, ShGKme commented
Cypress and Drone tests are unrelated

2023-10-16 13:07 UTC, susnux commented
> Cypress and Drone tests are unrelated

Yes but the commits need to be squashed (fixup)

2023-10-16 13:08 UTC, susnux approved these changes

2023-10-17 16:00 UTC, ShGKme commented
Cypress fail unrelated

2023-10-17 16:09 UTC, merged