fix(scheduling): don't send iMIP emails to rooms / resources
nextcloud/server pull request #40876
Opened 2023-10-11 16:54 UTC by miaulalala

## Summary

The current iMIP plugin doesn't check for the CU type of the attendee and sends an invitation regardless.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] ~~Screenshots before/after for front-end changes~~
- [ ] ~~Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required~~
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-11 16:55 UTC, miaulalala commented
/backport to stable27

2023-10-11 16:55 UTC, miaulalala commented
/backport to stable26

2023-10-11 16:55 UTC, miaulalala commented
/backport to stable25

2023-10-11 17:09 UTC, tcitworld requested changes

2023-10-11 17:09 UTC, tcitworld commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		if (\in_array($type, ['RESOURCE', 'ROOM', 'UNKNOWN'])) {
Some random software will probably use some `X-SPECIAL-THING` so it would be safer to just check if we are an individual or a group.
https://www.kanzaki.com/docs/ical/cutype.html

But then the method name should be something else, something like `canEmailToType`.

2023-10-12 13:34 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		if (\in_array($type, ['RESOURCE', 'ROOM', 'UNKNOWN'])) {
We use this logic in other parts of the code as well:

https://github.com/nextcloud/server/blob/62739ecf6cecbe55832b5e280360c882e3a2f6cf/apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php#L256-L260

Rooms and Resources are part of our ecosystem, which sets the proper CUTYPE.

I'd rather one email too many gets sent than just dropping everything that is not an INDIVIDUAL or GROUP.

We don't handle other specific X-TYPE properties so I don't see a reason to start now.

2023-10-12 15:36 UTC, tcitworld approved these changes

2023-10-12 16:49 UTC, ChristophWurst reviewed
Noice

2023-10-12 16:49 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +		if($this->imipService->isRoomOrResource($attendee)) {
^ add a null check just to be safe?

2023-10-12 16:49 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$type = ($cuType instanceof Parameter) ? strtoupper($cuType->getValue()) : 'INDIVIDUAL';
^ again not sure if this can ever happen and a CUTYPE parameter has no value? `ATTENDEE;CUTYPE:mailto:ietf-calsch@example.org`?! :see_no_evil:

2023-10-12 16:49 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		if (\in_array($type, ['RESOURCE', 'ROOM', 'UNKNOWN'])) {
```suggestion
		if (\in_array($type, ['RESOURCE', 'ROOM', 'UNKNOWN'], true)) {
```

2023-10-12 16:49 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$this->logger->debug('No invitation sent as recipient is room or resource');
```suggestion
			$this->logger->debug('No invitation sent as recipient is room or resource', [
			    'attendee' => $attendee->getValue(),
			]);
```

if we want to make this easier to debug in production

2023-10-12 19:29 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$this->logger->debug('No invitation sent as recipient is room or resource');
Smort

2023-10-12 19:37 UTC, miaulalala commented
Re: https://github.com/nextcloud/server/pull/40876#discussion_r1357099361
The instanceof check should take care of that, no?

2023-10-12 19:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			$this->logger->debug('No invitation sent as recipient is room or resource');
ALso this might blow up in our faces with email aliases btw. Will open a follow up ticket.

2023-10-13 07:58 UTC, ChristophWurst commented
> Re: [#40876 (comment)](https://github.com/nextcloud/server/pull/40876#discussion_r1357099361)
> The instanceof check should take care of that, no?

You are checking the parameter object, not its value.

2023-11-02 14:07 UTC, miaulalala commented
> > Re: [#40876 (comment)](https://github.com/nextcloud/server/pull/40876#discussion_r1357099361)
> > The instanceof check should take care of that, no?
> 
> You are checking the parameter object, not its value.

But the ternary should take care of that?

2023-11-02 21:49 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$type = ($cuType->getValue() !== null) ? strtoupper($cuType->getValue()) : 'INDIVIDUAL';
How? :/

2023-11-03 09:22 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$type = ($cuType->getValue() !== null) ? strtoupper($cuType->getValue()) : 'INDIVIDUAL';
getValue is not a pure function. Psalm can't assume that two calls to it always return null: https://psalm.dev/r/4f2b301039

2023-11-03 09:22 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$type = ($cuType->getValue() !== null) ? strtoupper($cuType->getValue()) : 'INDIVIDUAL';
calling getValue *could* change internal state. The method is free to return null one time and string another.

2023-11-03 10:56 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$type = ($cuType->getValue() !== null) ? strtoupper($cuType->getValue()) : 'INDIVIDUAL';
Ohhh interesting! Thanks for the info!

2023-11-06 18:38 UTC, miaulalala commented
Failing tests are integration-sharees and interation-tags. Both ran out of time (1:00:00).

2023-11-06 18:49 UTC, blizzz approved these changes

2023-11-06 20:52 UTC, merged