Add custom apps translation scripts and image path for consistency
nextcloud/server pull request #40898
Opened 2023-10-13 08:14 UTC by akhil1508

* Resolves: https://github.com/nextcloud/server/issues/40897

## Summary
- Add checks for custom app translations and images

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-13 09:39 UTC, kesselb requested changes
I'm unsure about this change in general.
I have plenty of apps in apps-extra and see the requests for the translation files.

2023-10-13 09:39 UTC, kesselb commented on lib/private/Template/JSResourceLocator.php
> +			$found += $this->appendScriptIfExist($this->serverroot, 'custom_apps/'.$script);
It's possible to pick a different name than custom_apps and therefore this approach is wrong.

2023-10-13 10:28 UTC, akhil1508 commented
> I'm unsure about this change in general.
> I have plenty of apps in apps-extra and see the requests for the translation files.

For me, `occ app:install calendar`  installed it in `custom_apps` folder. I don't see the requests for `custom_apps/calendar/l10n/$lang.js` for any language. Nor if I modify via theme..

2023-10-13 14:54 UTC, akhil1508 commented on lib/private/Template/JSResourceLocator.php
> +			$found += $this->appendScriptIfExist($this->serverroot, 'custom_apps/'.$script);
Yes, my bad. Different approach now :)

2023-10-17 13:45 UTC, kesselb commented on lib/private/Template/JSResourceLocator.php
> +			foreach (\OC::$APPSROOTS AS $appRoot) {
```suggestion
			foreach (\OC::$APPSROOTS as $appRoot) {
```

2023-10-17 13:47 UTC, kesselb commented
@juliushaertl @skjnldsv I'm totally unsure if the patch makes sense, we need it, etc .. :see_no_evil: 

However, I dislike the ability to modify files from apps via a theme.

2023-10-17 19:27 UTC, juliushaertl commented
I'm all in for dropping the theme generally once we have proper ways to achieve its mainly used functionality  otherwise https://github.com/nextcloud/server/issues/27433

I think for now the change makes sense, to ensure that the legacy theme mechanism works as expected with custom app paths.

2023-10-17 19:28 UTC, juliushaertl approved these changes
Would be good to squash the commits into one, otherwise this seems good.

2023-10-19 09:10 UTC, akhil1508 commented
> Would be good to squash the commits into one

@juliushaertl Squashed

2023-10-27 11:37 UTC, susnux approved these changes

2023-10-30 15:18 UTC, juliushaertl commented
Failures seem unrelated.

2023-10-30 15:18 UTC, merged