Reduce left margin of files list header
nextcloud/server pull request #40905
Opened 2023-10-13 14:10 UTC by JuliaKirschenheuter

* Part of: https://github.com/nextcloud/server/issues/36965
* Resolves: files overview part

## Summary

🏚️ Before | 🏡 After
---|---
 ![image](https://github.com/nextcloud/server/assets/6078378/e1115406-fc97-4cad-aa1c-bc7d3cc99ae2) | ![Screenshot from 2023-10-13 15-57-49](https://github.com/nextcloud/server/assets/6078378/74d11bca-8a42-46d9-b58d-27dcd2796f43)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-13 14:14 UTC, szaimen commented on apps/files/src/views/FilesList.vue
> +$navigationToggleSize: 45px;
isn't our baseline that usually 44px? maybe we should use the normal variable here? WDYT @skjnldsv

2023-10-13 14:46 UTC, skjnldsv requested changes
Okay, I had to dig into this so we can move forward
- [ ] 1: Fix the min-width on the nav in the vue components (like mentioned [here](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4640#pullrequestreview-1674090462))
- [ ] 2: Add a `	max-width: 100%;` on the `.files-list__header`

Then it will be fixed.
![Peek 13-10-2023 16-47](https://github.com/nextcloud/server/assets/14975046/01007257-fc98-4f33-9ee8-50b94f9902e5)

2023-10-17 09:16 UTC, skjnldsv approved these changes

2023-10-17 10:38 UTC, skjnldsv commented
The mixin is broken, fixed in https://github.com/nextcloud/server/commit/11728d69d9701e783fa2799d15de7ec0577dc36d

2023-10-17 17:47 UTC, Pytal approved these changes

2023-10-17 19:41 UTC, AndyScherzinger approved these changes

2023-10-17 22:02 UTC, merged