Append to body all selects inside of user table
nextcloud/server pull request #40902
Opened 2023-10-13 10:03 UTC by JuliaKirschenheuter

### ☑️ Resolves

* Part of https://github.com/nextcloud/server/issues/36965
* Fixes: NcSelect is broken so far table will be moved to left or right
* After state is a bit better, but don't know how to fix this issue completely. Probably it is ok to leave it like it is now.

### 🖼️ Screenshots

🏚️ Before

![Peek 2023-10-11 10-18](https://github.com/nextcloud/server/assets/6078378/ea3e51ee-7ac3-4a97-96b3-94f7f4021f25)

 🏡 After

![Peek 2023-10-16 11-42](https://github.com/nextcloud/server/assets/6078378/5fa87435-c7fe-46f2-840f-9f7165500c4f)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-13 13:53 UTC, szaimen requested changes
Based on your video, the select dropdown still overlaps?

2023-10-13 17:53 UTC, Pytal commented
> > Based on your video, the select dropdown still overlaps?
> 
> Yes, but not so much as before.

Reply in the same comment !?🤪

2023-10-13 17:53 UTC, Pytal commented
> @Pytal do you have some other ideas?

Pushed a fix :)

2023-10-16 08:48 UTC, JuliaKirschenheuter commented
> Pushed a fix :)

Thank you!

2023-10-16 08:54 UTC, szaimen reviewed
Still looks a bit weird if there are not enough user rows but otherwise it works fine now :)

![image](https://github.com/nextcloud/server/assets/42591237/4225729c-88e4-4808-95f4-1c331c601a84)

2023-10-16 09:50 UTC, susnux approved these changes

2023-10-16 10:45 UTC, ShGKme requested changes
Works with select great now, but there is an extra border in the table footer now now

2023-10-16 10:45 UTC, ShGKme commented on apps/settings/src/components/Users/shared/styles.scss
> +		border-bottom: 1px solid var(--color-border);
This adds an unwanted bottom border to the users count in the end:

![image](https://github.com/nextcloud/server/assets/25978914/018f10f6-8fa4-4b24-945f-74129d6ace9f)

2023-10-16 22:40 UTC, Pytal approved these changes

2023-10-17 08:56 UTC, ShGKme approved these changes

2023-10-17 08:56 UTC, merged