chore(files): split FileEntry Preview
nextcloud/server pull request #40917
Opened 2023-10-14 13:53 UTC by skjnldsv

Ref: https://github.com/nextcloud/server/issues/39914Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

2023-10-14 13:54 UTC, skjnldsv commented on apps/files/src/components/VirtualList.vue
> +			})
@artonge :star_struck:

2023-10-16 10:30 UTC, artonge commented on apps/files/lib/Service/UserConfig.php
> +		],
Just a thought: once the new metadata API is done, we could store that per folder, would be fancy, no ?

2023-10-16 10:33 UTC, artonge reviewed
As this is mostly moving code around, should we give a closer look to a specific area? Beside the virtual list improvement ;)

2023-10-16 12:39 UTC, skjnldsv commented on apps/files/lib/Service/UserConfig.php
> +		],
There has been some requests. Like https://github.com/nextcloud/server/issues/15170

2023-10-16 12:40 UTC, skjnldsv commented on apps/files/src/components/FileEntry/FileEntryBlank.vue
> +export default Vue.extend({
This file needs to go before rebase

2023-10-16 15:20 UTC, artonge approved these changes

2023-10-16 15:20 UTC, artonge commented
Beware, the base branch seems off

2023-10-17 06:16 UTC, skjnldsv commented
> Beware, the target branch seems off

On purpose, please also review https://github.com/nextcloud/server/pull/40854

2023-10-17 09:47 UTC, szaimen requested changes
I tested this and in general it seems to work fine :)

But it seems to be broken on mobile currently:
![image](https://github.com/nextcloud/server/assets/42591237/b8f0f120-39f5-428d-83a7-461a50cf66b7)
![image](https://github.com/nextcloud/server/assets/42591237/ae70a844-e104-42f2-8c65-22992400e492)

Also for the first elements the 3-dot menu is not shown:
![image](https://github.com/nextcloud/server/assets/42591237/08591ae4-9c61-4a69-9307-083ca251f652)

And the list view is currently broken:
![image](https://github.com/nextcloud/server/assets/42591237/c8d19368-c81e-44b1-a4f5-0c61e0979ad7)

2023-10-17 10:31 UTC, szaimen reviewed
The issues are fixed but the toggle is not shown anymore at all:
![image](https://github.com/nextcloud/server/assets/42591237/d7a35176-aa8e-481b-98b2-f245df6d414a)

2023-10-17 10:37 UTC, skjnldsv commented
Also done @szaimen

2023-10-17 10:38 UTC, skjnldsv commented
PS: not recompiling as I see other PRs are probably going in too

2023-10-17 10:46 UTC, szaimen reviewed
Last problem and then ready to go:

on small displays and If in grid view and opening the dropdown on the right it shows multiple scroll bars:
![image](https://github.com/nextcloud/server/assets/42591237/e1874d44-da06-4901-8964-19da271e59dd)

2023-10-17 10:50 UTC, szaimen approved these changes
Problem shall be fixed in follow-up

2023-10-17 11:55 UTC, merged