Check expiry enforcement for all share types
nextcloud/server pull request #40933
Opened 2023-10-16 14:29 UTC by Fenn-CS

We should check that a maximum expiry date has been enforced for all shares and NOT JUST FOR internal shares before enforcing a UI max date, like in commit 9757e680e2f643fe19432255c4142e96fbc88df5

Resolves : _no issue_

2023-10-16 15:10 UTC, artonge approved these changes

2023-10-16 15:47 UTC, come-nc reviewed
Enforcing now works for all three kind of shares.

But default seems broken for remote share it’s not applied?

2023-10-16 16:48 UTC, Fenn-CS commented
> Enforcing now works for all three kind of shares.
> 
> But default seems broken for remote share it’s not applied?

Added [commit](https://github.com/nextcloud/server/pull/40933/commits/963b86b7c024dd40518f4f30e07a22a6d862aa58) to fix it.  Which also turns addresses and issue that existing of not being able to not set default if desired. Thanks @come-nc

2023-10-19 09:15 UTC, come-nc commented
Hum, forced default expiration date now works for all cases, but for default value it uses the normal share default value for all 3 cases, even email and remote share, which should use their own default.

2023-10-19 09:20 UTC, come-nc commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				}
This is not an elseif so it overrides previous date value.

2023-10-19 09:27 UTC, come-nc commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				}
```suggestion
				/* Set default expiration dates if set */
				if (this.isPublicShare && this.config.isDefaultExpireDateEnabled) {
					this.share.expireDate = this.config.defaultExpirationDate.toDateString()
				} else if (this.isRemoteShare && this.config.isDefaultRemoteExpireDateEnabled) {
					this.share.expireDate = this.config.defaultRemoteExpirationDateString.toDateString()
				} else if (this.config.isDefaultInternalExpireDateEnabled) {
					this.share.expireDate = this.config.defaultInternalExpirationDate.toDateString()
				}
```
This change fixes the behavior.

2023-10-20 07:59 UTC, come-nc commented
I had to run «npm run build» to fix the admin UI, so something is fishy in the commited dist. You will have to rebase on master and rebuild anyway.

Also, there is a problem:

1. Set a default expiration date on all 3 types
2. Force it for email share and not for the others
3. Share with a user
4. Date is enforced while it should not

Please test thoroughly requesting for review again.

2023-10-20 08:00 UTC, come-nc requested changes
Enforcing is not working correctly (enforcing email enforces for local share, did not test other combinations)

2023-10-20 08:48 UTC, Fenn-CS commented
> I had to run «npm run build» to fix the admin UI, so something is fishy in the commited dist. You will have to rebase on master and rebuild anyway.
> 
> Also, there is a problem:
> 
>     Set a default expiration date on all 3 types
>     Force it for email share and not for the others
>     Share with a user
>     Date is enforced while it should not
> 
> Please test thoroughly requesting for review again.

Sorry @come-nc it appears it merge conflict resolution overwrote some of the update, during a rebase.

2023-10-20 12:16 UTC, come-nc approved these changes
:partying_face:

2023-10-20 12:37 UTC, Fenn-CS commented
/compile amend /

2023-10-22 09:52 UTC, Fenn-CS commented
/compile amend /

2023-10-22 15:31 UTC, Fenn-CS commented
/compile amend /

2023-10-22 16:40 UTC, Fenn-CS commented
/compile amend /

2023-10-23 07:32 UTC, merged

2023-12-13 12:46 UTC, marcelklehr commented
Can we please backport this to stable27?

2023-12-13 13:55 UTC, susnux commented
Looks like this is already on stable27? At least when I cherry pick it is empty. cc @Fenn-CS

2023-12-13 14:10 UTC, Fenn-CS commented
@susnux it is : https://github.com/nextcloud/server/pull/40928

2023-12-13 14:18 UTC, Fenn-CS commented
@marcelklehr it has commits from both issues.