Reduce width of sharing entry
nextcloud/server pull request #40963
Opened 2023-10-18 14:51 UTC by JuliaKirschenheuter

* Part of https://github.com/nextcloud/server/issues/36965
* Fixes "Files right sidebar"

## Summary

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![image](https://github.com/nextcloud/server/assets/6078378/45fcb978-e3dd-4ade-957b-48de637a95b7) | ![Screenshot from 2023-10-18 16-30-24](https://github.com/nextcloud/server/assets/6078378/d42f9609-fee9-4490-af6e-75d67334df51)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-18 16:47 UTC, Pytal approved these changes

2023-10-19 07:51 UTC, ShGKme commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +		min-width: 70%;
`min-width: 70%` fixes the issue on a small screen.

But `80%` is always a bit not the same as other elements.

What about replacing the fixed 80/70% width with flex-grow? Then it will always have just all the space between buttons on all screens.

(with `min-width: 0;` to with overlapping issue)

Large screen | Small screen
---|---
**Current master** `width: 80%; min-width: 80%` | .
![image](https://github.com/nextcloud/server/assets/25978914/b79157eb-73d2-4036-bc71-c283f7fdae1d) | ![image](https://github.com/nextcloud/server/assets/25978914/48757b8d-0f6a-4032-8d69-b208e718b2d0)
**This PR** `width: 80%; min-width: 70%` | .
![image](https://github.com/nextcloud/server/assets/25978914/8e6c59cf-5e5f-473b-b935-bddbb78176d3) | ![image](https://github.com/nextcloud/server/assets/25978914/763ded84-a903-48d7-83c8-e19ed94ab256)
**Proposal** `flex: 1 0; min-width: 0;` | .
![image](https://github.com/nextcloud/server/assets/25978914/c3e52db3-5fba-4dad-aa32-b49e96832366) | ![image](https://github.com/nextcloud/server/assets/25978914/07961cdd-2833-48d9-a085-5ef55b2f163b)

2023-10-19 08:56 UTC, JuliaKirschenheuter commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +		min-width: 70%;
Thanks a lot! Done

2023-10-19 09:02 UTC, ShGKme requested changes

2023-10-19 09:02 UTC, ShGKme commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +		min-width: 0;
With `flex: 1 0` there should not be fixed `width: 80%;`. Otherwise, the base size is still 80% and it is broken on a small screen.

2023-10-19 09:03 UTC, ShGKme commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +		min-width: 0;
`width: 80%;` is the main problem, it makes a shift on both small and large screens, because `80% != 100% - buttons and avatars`

2023-10-19 09:31 UTC, ShGKme reviewed
There is also a second component that has exactly the same styles which has the same issue in this place: `SharingEntry.vue`

![image](https://github.com/nextcloud/server/assets/25978914/74dbf947-b7d3-42ba-894f-47d5acd71ca6)

Let's fix it as well.

2023-10-19 12:07 UTC, ShGKme approved these changes

2023-10-19 12:29 UTC, JuliaKirschenheuter commented
failed continuous-integration/drone/pr tests are not related

2023-10-19 15:08 UTC, merged