fix(tests): Only run tests on CI that are needed
nextcloud/server pull request #40986
Opened 2023-10-19 14:53 UTC by susnux

## Summary

Do not run PHP unit tests when only JS code is changed, should save us some CI time.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

2023-10-19 20:11 UTC, nickvergessen requested changes

2023-10-19 20:11 UTC, nickvergessen commented on .github/workflows/lint-php-cs-when-unrelated.yml
> +# This workflow is provided via the organization template repository
This does not work as I found out the hard way. Please see github.com/nextcloud/.github for updated logic

2023-10-19 20:38 UTC, susnux commented on .github/workflows/lint-php-cs-when-unrelated.yml
> +# This workflow is provided via the organization template repository
Good to know! Move to the new logic :)

2023-10-19 21:27 UTC, pulsejet commented
Don't know enough about this part

2023-10-20 08:42 UTC, skjnldsv approved these changes

2023-10-20 14:01 UTC, nickvergessen commented on .github/workflows/lint-eslint.yml
> +              - 'src/**'
same question for this, does it match code `core/src/` and `apps/**/src/` or only root src?

2023-10-20 14:16 UTC, susnux commented on .github/workflows/lint-eslint.yml
> +              - 'appinfo/info.xml'
I wonder if we can remove that line, why would be need to lint the JS code if the appinfo is changed?

2023-10-20 14:52 UTC, nickvergessen commented on .github/workflows/lint-eslint.yml
> +              - 'appinfo/info.xml'
Because that is on releases/branch off which is a sane snapshot. But yeah less useful in server than in apps

2023-10-20 15:11 UTC, susnux commented on .github/workflows/lint-eslint.yml
> +              - 'src/**'
Fixed!

2023-10-20 19:32 UTC, susnux commented
I think this is good now :)
Drone is unrelated :wink:

2023-10-27 11:52 UTC, nickvergessen approved these changes

2023-10-27 11:52 UTC, merged