feat(files): support nested actions
nextcloud/server pull request #41010
Opened 2023-10-20 10:38 UTC by skjnldsv

Fix https://github.com/nextcloud/server/issues/39718

![Peek 20-10-2023 12-36](https://github.com/nextcloud/server/assets/14975046/fa6dae05-f23a-4579-81a3-7a67dadac0c3)

2023-10-20 10:40 UTC, skjnldsv commented on apps/files/src/init.ts
> +}))
Obviously testing purpose

2023-10-20 10:41 UTC, skjnldsv commented
Setting as draft, please review anyway, then I'll release a new files lib update and we can rebase/compile/merge :rocket:

2023-10-20 13:45 UTC, skjnldsv commented
> I am not completely sure if possible but from design perspective maybe a menu should rather be shown like this for example:
> 
> ![image](https://user-images.githubusercontent.com/42591237/276948975-a239cc36-2948-4217-a253-a85fada6294f.png)
> 
> (quick and dirty mockup)
> 
> WDYT @nextcloud/designers

That's exactly what is written in the first post :grimacing:

2023-10-20 13:46 UTC, szaimen commented
> That's exactly what is written in the first post 😬

sorry, skipped this section 😅

2023-10-24 23:53 UTC, Pytal reviewed
For rich functionality other action types, i.e. NcAction* components, should be supported in addition to the simple button action

For the reminder feature at least NcActionInput would be needed

2023-10-25 06:10 UTC, skjnldsv commented
> For rich functionality other action types, i.e. NcAction* components, should be supported in addition to the simple button action

That was not part of the plan :see_no_evil: 
That would mean we're scoping our API to be locked with the vue component, which I think we should not. IIRC from our discussion with the design team, there was only one "rich" element, which was the date picker, and that can be mitigated or worked around I think. :thinking: 

Quick thinking on our options, but for the custom date picker, we could:
- Mount a datepicker somewhere and trigger the browser date picker
- Use a popup

2023-10-25 07:51 UTC, marcoambrosini reviewed
I think that for this we should use floating-vue's submenus
https://floating-vue.starpad.dev/guide/component#sub-menu

https://github.com/nextcloud/server/assets/26852655/5b5ded99-e949-4b75-a04d-f2c887e11bf4

2023-10-25 07:57 UTC, skjnldsv commented
@marcoambrosini irrelevant here, we're not impelmenting a new design.
Any menu like yours needs to be discussed globally and handled in the vue components.

here we're implementing the same layout as other apps as it's been decided a while ago
Please raise your ticket in https://github.com/nextcloud-libraries/nextcloud-vue

2023-10-25 09:29 UTC, nimishavijay commented
> I think that for this we should use floating-vue's submenus

Hm, I agree that I see this cascading submenu more in desktop applications, but it also has more edge cases where it could look not so ideal, for example in mobile view, at the right edge of the screen, etc. I am okay with the paginated submenu we have atm. 

> Still showing the provided icon and putting a chevron icon at the end would be nice, but it's not supported by the vue components afaik

Agreed, best way forward here, but if not possible we could just stick to the provided icon rather than changing it to a chevron.

In the sublevel, I would also say instead of "Back" we show the parent level item text to help with understanding which level you are at.

It would also be nice to include an animation for the transition to make it look smoother, sort of like this:

https://github.com/nextcloud/server/assets/52440189/bf75d801-b499-40f6-b55f-03f83107df35

2023-10-25 14:58 UTC, skjnldsv commented
> In the sublevel, I would also say instead of "Back" we show the parent level item text to help with understanding which level you are at.

Will be done here

For the following points:
>> Still showing the provided icon and putting a chevron icon at the end would be nice, but it's not supported by the vue components afaik
>
> Agreed, best way forward here, but if not possible we could just stick to the provided icon rather than changing it to a chevron.
>
> It would also be nice to include an animation for the transition to make it look smoother, sort of like this:

This is for the vue components

2023-10-25 17:29 UTC, Pytal commented
> * Use a popup: [Use a dialog for custom date form instead of including it in the action menu spreed#10202](https://github.com/nextcloud/spreed/issues/10202)

+1 for popup

Since this would be a new component we'd need final approval from designers and some way to have the native datetime picker expanded in the dialog without having to click the input first

2023-11-02 11:08 UTC, jancborchardt reviewed
I’d say it does work and is nice – but agree that an animation for the Vue component is needed to communicate better what happens. :)

2023-11-02 11:08 UTC, jancborchardt commented
And cc @marcoambrosini since he brought up https://github.com/nextcloud/spreed/issues/10202

2023-11-03 18:00 UTC, skjnldsv commented
@Pytal please review the logic!
Especially the condition on where a reminder is shown or not, as I wasn't part of the original discussions! I used your services, so I think it should be good.
But here are a few questions to be safe
1. Is it normal that depending on the time of day, only some options are visible?
2. Is this feature enabled for all nodes, no matter what they are and what permissions they have? (folder/files, etc etc)

2023-11-04 00:35 UTC, Pytal commented
> 1. Is it normal that depending on the time of day, only some options are visible?

Yes this is by design

> 2. Is this feature enabled for all nodes, no matter what they are and what permissions they have? (folder/files, etc etc)

Yes, if you can see (read) the file then you should be able to set a reminder on it

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.scss
> +.files-list__row-action-set-reminder-3 {
Target `.files-list__row-action-set-reminder-custom` instead and use margin-top, etc. ? As the "Next week" action is not always rendered

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +		id: `set-reminder-${option.dateTimePreset}`,
Let's change DateTimePreset to a string enum then if it's used this way

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +		title: () => `${option.ariaLabel} – ${getVerboseDateString(dateTime)}`,
```suggestion
		displayName: () => `${option.label} – ${getDateString(dateTime)}`,
		title: () => `${option.ariaLabel} – ${getVerboseDateString(dateTime)}`,
```
En dash

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +export const actions = [laterToday, tomorrow, thisWeekend, nextWeek].map((option): FileAction|null => {
Let's extract this anonymous function to a `const computeAction` and write this as `.map(computeAction).filter(Boolean)` for readability

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/components/SetCustomReminderModal.vue
> +			if (this.customDueDate === '') {
```suggestion
			if (this.customDueDate === null) {
```
Since https://github.com/nextcloud-libraries/nextcloud-vue/pull/4540/commits/05d58f63c7f34558226fa248377693d8c3f09cbf

2023-11-04 00:36 UTC, Pytal commented on apps/files_reminders/src/services/customPicker.ts
> +	console.debug('CustomReminderModal', mount, CustomReminderModal)
```suggestion
```

2023-11-07 10:41 UTC, skjnldsv commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +		id: `set-reminder-${option.dateTimePreset}`,
Done

2023-11-07 14:14 UTC, susnux requested changes
The focus handling does not work properly:
If you click (keyboard) on "set reminder" the submenu opens but the focus is not set on the submenu's first element.

Also if you click the back button the first submenu is reopend, but the focus is not on the "set reminder" entry.

In both cases the focus is on some random non visible element.

2023-11-07 17:09 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +export const actions = [laterToday, tomorrow, thisWeekend, nextWeek]
Since the presence of the action should be evaluated ideally on click instead of on script execution I think the FileAction enabled callback needs to be set to something like `() => Boolean(getDateTime(option.dateTimePreset))` to be more reactive

2023-11-07 17:11 UTC, skjnldsv commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +export const actions = [laterToday, tomorrow, thisWeekend, nextWeek]
Can be improved later

2023-11-07 17:15 UTC, susnux approved these changes
:elephant: a11y in follow up?

2023-11-07 17:16 UTC, Pytal approved these changes

2023-11-08 07:53 UTC, merged