Explicitly close the directory stream
nextcloud/server pull request #41013
Opened 2023-10-20 13:20 UTC by solracsf

## Summary

The directory handle `$dh` is explicitly closed using `closedir($dh)` to release resources after iterating through the directory.
This ensures proper resource management.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-23 06:48 UTC, Altahrim approved these changes

2023-10-23 07:50 UTC, nickvergessen approved these changes

2023-10-23 10:31 UTC, artonge approved these changes

2023-10-25 12:56 UTC, icewind1991 requested changes
When the function returns the handles get dropped and the resources cleaned up automatically. Manually closing the handles only makes a difference if there is a significant amount of work being done without dropping the handle.

2023-10-25 18:08 UTC, solracsf commented
You're right, closing then as there is no point to do it. 👍

2023-10-25 18:08 UTC, closed without merging