optimize UserMountCache::registerStorage
nextcloud/server pull request #41057
Opened 2023-10-23 11:33 UTC by icewind1991

Simplify the logic a bit and use less intermediate arrays

2023-11-13 11:03 UTC, blizzz requested changes
Missing required annotation, otherwise :+1:

2023-11-13 11:03 UTC, blizzz commented on lib/public/Files/Config/ICachedMountInfo.php
> +	public function getKey(): string;
missing @since annotation

2023-11-16 10:38 UTC, Altahrim commented on lib/public/Files/Config/ICachedMountInfo.php
> +	public function getKey(): string;
Just added it :)

2023-11-16 10:38 UTC, blizzz approved these changes

2023-11-16 13:00 UTC, juliushaertl approved these changes

2023-11-16 13:00 UTC, juliushaertl requested changes
Ah wait CI shows some issue:

```
PHP Fatal error:  Nesting level too deep - recursive dependency? in /home/runner/work/server/server/lib/private/Files/Config/UserMountCache.php on line 130
```

2023-11-16 15:07 UTC, juliushaertl commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Unrelated :)

2023-11-16 15:08 UTC, Altahrim commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Arf yes, I don't know why it's modified… Thanks!

2023-11-16 15:31 UTC, juliushaertl approved these changes

2023-11-16 17:30 UTC, merged