Check if the node has a null ID before deleting in preview watcher
nextcloud/server pull request #41067
Opened 2023-10-23 15:15 UTC by akhil1508

* Resolves: https://github.com/nextcloud/server/issues/36463

## Summary
- A lot of unnecessary `rmdir` calls are done on the preview directory

- After investigating, here are the findings to justify the fix:
  - As per https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/private/Files/FileInfo.php#L164 there is a return type of `int` or `null`
  - A `null` return by this method call over [here](https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/private/Preview/Watcher.php#L64) makes sure that an empty string is passed to `$this->appData->getFolder()`
  - As per the logic, for an empty string this will return the preview folder i.e. `appdata_*****/preview` in our case
  - There is then an attempt to delete this entire folder

- On our instance we did find logs that a delete is attempted on the entire preview folder as per https://github.com/nextcloud/server/issues/36463#issuecomment-1766963639
- Further, by logging I could confirm that `$node->getId()` is indeed null in one case leading to consistent triggering of this `rmdir`
- One case is the upload of a partial file (`.part` extension)
  - The Nextcloud clients avoid this but certain DAV clients allow to upload to nextcloud servers
  - This kind of file is ignored by [`isPartialFile`](https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/public/Files/Cache/IScanner.php#L75) 
  - In this example a file with the `.part` extension succesfully triggers an `rmdir` of the entire preview directory 

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-24 09:55 UTC, CarlSchwan commented on lib/private/Preview/Watcher.php
> +			if (is_null($node->getId())) {
I wonder if you have a backtrace for when the deleteNode is called with a node without a node id.

It might be a good idea to fix it at the source (if possible)

2023-10-24 17:03 UTC, akhil1508 commented on lib/private/Preview/Watcher.php
> +			if (is_null($node->getId())) {
The stack trace was in the issue https://github.com/nextcloud/server/issues/36463#issuecomment-1766963639 

I add it to the description of this PR :+1:

2023-10-24 17:07 UTC, akhil1508 commented on lib/private/Preview/Watcher.php
> +			if (is_null($node->getId())) {
Yep @tcitworld seems the hook is indeed fired from here :+1: 

@CarlSchwan @tcitworld If you could suggest what would be the best way to fix it at the source, I will do it like that. As it will take me more time to understand the core code fully and you probably already know better :)

2023-10-25 07:57 UTC, tcitworld approved these changes

2023-10-25 07:57 UTC, tcitworld commented on lib/private/Preview/Watcher.php
> +			if (is_null($node->getId())) {
I don't think there's a better way to do that, looks fine to me.

2023-10-31 08:27 UTC, skjnldsv approved these changes
Doesn't hurt!

2023-11-02 10:45 UTC, artonge requested changes
@come-nc IIRC, you looked into the `null` file id on some file events. Is it similar?

2023-11-06 09:35 UTC, come-nc approved these changes

2023-11-06 09:36 UTC, come-nc commented
> @come-nc IIRC, you looked into the `null` file id on some file events. Is it similar?

Not really, here it’s expected for the node to have no id since it’s new, I think. In the cases I looked into it was paths outside the user directory which ended up trigerring events on null paths.

2023-11-06 10:28 UTC, artonge approved these changes

2024-01-18 10:46 UTC, merged

2024-01-19 09:37 UTC, SystemKeeper commented
@blizzz backport? 🤔

2024-01-19 15:25 UTC, blizzz commented
I understand it was first discovered on 25, so since then everything is affected.

2024-01-19 15:26 UTC, blizzz commented
/skjnldsv-backport to stable28

2024-01-19 15:26 UTC, blizzz commented
/skjnldsv-backport to stable27

2024-01-19 15:27 UTC, blizzz commented
/skjnldsv-backport to stable26

2024-01-20 04:49 UTC, susnux commented
/backport to stable28

2024-01-22 09:56 UTC, SystemKeeper commented
Hm, does backporting not work if it’s from a fork?

2024-01-22 19:56 UTC, susnux commented
> getDefaultTextColorPrimary

cc @skjnldsv

2024-06-03 11:07 UTC, popos123 commented
hi, i see that fix was implemented in version 29.0.1? becouse i have this bug on the nevest version too
![image](https://github.com/nextcloud/server/assets/43697578/d50e049f-e50c-4c92-a457-8c50164f84c2)

2024-06-20 00:11 UTC, chrisborell commented
Still occuring for me in [Nextcloud Hub 8] (29.0.2)

![Screenshot 2024-06-20 at 10 09 39 am](https://github.com/nextcloud/previewgenerator/assets/52059185/d17cfdcf-966f-4d40-86a8-636c86276486)