Respect custom webroot in setup form
nextcloud/server pull request #41189
Opened 2023-10-29 17:53 UTC by HolonProduction

* Resolves: #41188

## Summary

Passes an url generator to the installation template and uses it to generate an absoluteUrl.

2023-10-30 10:51 UTC, kesselb requested changes

2023-10-30 10:51 UTC, kesselb commented on core/templates/installation.php
> +<form action="<?php $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
```suggestion
<form action="<?= $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
```

If you generate the url you should also echo it ;)

It should also work to remove the action attribute because the default is then the current page.

2023-10-30 11:16 UTC, kesselb commented on core/templates/installation.php
> +<form action="<?php $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
```suggestion
<form method="post" class="guest-box install-form">
```

Would be my favorite.

2023-10-30 18:25 UTC, HolonProduction commented on core/templates/installation.php
> +<form action="<?php $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
I wasn't sure on this since the template isn't directly linked to `index.php`. But giving it a second thought setting it to `index.php` makes assumptions about the location of the form as well so yeah that's probably the best solution.

2023-10-31 08:36 UTC, skjnldsv approved these changes
Code make sense and worked for me

2024-03-08 11:29 UTC, kesselb approved these changes

2024-03-12 16:47 UTC, Altahrim commented
@HolonProduction  CI failures seems unrelated.
Can you reabse and reword your commit to use [conventional commit](https://www.conventionalcommits.org/) please?

2024-03-12 19:06 UTC, HolonProduction commented
Done

2024-03-14 07:16 UTC, merged