remove comments tab from files
nextcloud/server pull request #41201
Opened 2023-10-30 17:51 UTC by sorbaugh

## Summary

This is the the second part of a two part Pull Request to move code from the comments app found in server to the activity app.

Here is the other PR: https://github.com/nextcloud/activity/pull/1387

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-10-31 11:52 UTC, nickvergessen requested changes, later dismissed

2023-10-31 11:52 UTC, nickvergessen commented on apps/comments/src/comments-app.js
> -import CommentsInstance from './services/CommentsInstance.js'
The comments feature is actually part of the public API (3 years deprecation required?):
https://github.com/nextcloud/server/blob/4d2217073acf6ed844bd006c102e403e7978e813/lib/private/Comments/Manager.php#L1615-L1623

It allows apps to include comments with:
* 2 lines of PHP:
    *  https://github.com/nextcloud/announcementcenter/blob/main/lib/Controller/PageController.php#L103
    * https://github.com/nextcloud/announcementcenter/blob/main/lib/Listener/CommentsEntityListener.php#L57
* 6 lines of JS/Vue:
    * https://github.com/nextcloud/announcementcenter/blob/main/src/App.vue#L148-L154

---

If we decide not to keep this (which I think is a bummer, but also it's not good documented atm and so only used by 1 app with this way, other apps reimplemented comments manually) at least the comments manager also needs adjusting to not import a non-existing file and also help developers realize the feature was removed without prior notice.

2023-10-31 11:54 UTC, nickvergessen commented
Setting https://github.com/nextcloud/server/labels/pending%20documentation because it's needed in case the feature is being deprecated or removed directly.

2023-10-31 12:19 UTC, skjnldsv commented on apps/comments/src/comments-app.js
> -import CommentsInstance from './services/CommentsInstance.js'
> 3 years deprecation required?

It's an OCA api, it doesn't follow that rule :)
(I used OCA for that exact reason, because this is not an official API)

2023-10-31 13:04 UTC, nickvergessen commented on apps/comments/src/comments-app.js
> -import CommentsInstance from './services/CommentsInstance.js'
https://github.com/nextcloud/server/blob/77355a8a79898a03d4f45e853e3d99c9a633509b/lib/public/Comments/ICommentsManager.php#L478-L483

PHP is `OCP` with "Load the Comments app into the page"
As said, we can violate it, make the function no-op / log a fatal error and continue, so app developers have a better trace.
But then it should at least be documented in the "Removed API" section of https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#id4

2023-10-31 15:07 UTC, sorbaugh commented
Thanks for pointing it out! For context, the comments feature is being moved to the activity repo, so this is one of two pull requests.
https://github.com/nextcloud/activity/pull/1387

2023-10-31 20:25 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> -		$this->initialStateService->provideInitialState('comments', 'max-message-length', IComment::MAX_MESSAGE_LENGTH);
```
		$this->logger->critical('Method ' . __METHOD__ . ' is no-op because comments feature was moved');
```

2023-10-31 20:27 UTC, nickvergessen commented on lib/private/Comments/Manager.php
> +	 * Function is no-op because comments feature was moved
```suggestion
	 * Load the Comments app into the page
```

2023-10-31 20:27 UTC, nickvergessen commented on lib/private/Comments/Manager.php
>  	 * @since 21.0.0
```suggestion
	 * @since 21.0.0
	 * @deprecated 28.0.0 - Function is no-op because comments feature was moved to the activity app
```

2023-10-31 20:27 UTC, nickvergessen commented on lib/private/Comments/Manager.php
>  	 * @since 21.0.0
This change must also be applied on `lib/public/Comments/ICommentsManager.php`

2023-10-31 21:58 UTC, sorbaugh commented on lib/private/Comments/Manager.php
> -		$this->initialStateService->provideInitialState('comments', 'max-message-length', IComment::MAX_MESSAGE_LENGTH);
Added :)

2023-10-31 21:59 UTC, sorbaugh commented on lib/private/Comments/Manager.php
>  	 * @since 21.0.0
Adjusted :)

2023-10-31 22:01 UTC, nickvergessen commented on lib/private/Comments/Manager.php
>  	 * @since 21.0.0
You removed the useful description instead of adding the deprecation

2023-11-02 14:08 UTC, artonge approved these changes

2023-11-02 14:40 UTC, artonge commented on apps/comments/src/comments.js
Is this file still needed?

2023-11-02 14:40 UTC, artonge commented on apps/comments/src/activitytabviewplugin.js
What was the use of this file?

2023-11-02 14:48 UTC, artonge requested changes
Actually, most of this need to be kept as 

> if activity app is disabled and comments app enabled:
        show comments tab as-is

2023-11-15 13:25 UTC, susnux commented
closing in favor of https://github.com/nextcloud/server/pull/41491
(for reuse code and not duplicate comments code to activity app)

2023-11-15 13:25 UTC, closed without merging