enh(TextProcessing): Add IProvider2
nextcloud/server pull request #41271
Opened 2023-11-03 15:26 UTC by marcelklehr

## Summary
Since we added the TextProcessing API in 27.1 some shortcomings have presented themselves, which I seek to improve with this PR.

Additions in this PR:

- allow providers to obtain current task's userId
- allow providers to expose average task runtime
- IManager now also exposes a runOrSchedule() method which takes into account this runtime estimation
- the schedule OCS API endpoint now uses runOrSchedule to avoid always scheduling a background job which has a max-delay of 5min even if the provider would be done in a few seconds, like the OpenAI provider for example.

## Todo

- [ ] Check and possible extend tests

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-03 15:35 UTC, julien-nc requested changes

2023-11-03 15:35 UTC, julien-nc commented on core/Migrations/Version28000Date20231103104802.php
> +			]);
We usually check if the column is there already.

2023-11-06 10:34 UTC, come-nc commented on core/Controller/TextProcessingApiController.php
> +	 * @return DataResponse<Http::STATUS_OK, array{task: CoreTextProcessingTask}, array{}>|DataResponse<Http::STATUS_INTERNAL_SERVER_ERROR|Http::STATUS_BAD_REQUEST|Http::STATUS_PRECONDITION_FAILED, arra
The new error code is not documented below

2023-11-06 10:34 UTC, come-nc commented on core/Controller/TextProcessingApiController.php
> +			} catch(\RuntimeException) {
Same thing as in the other PR, should be a custom exception if it has a special meaning.

2023-11-06 10:34 UTC, come-nc commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
But do we know if this task will be run by this specific provider? It seems they are not bound together.

2023-11-06 10:34 UTC, come-nc commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
Also canUseProvider is not checked

2023-11-06 10:34 UTC, come-nc commented on lib/public/TextProcessing/IProvider2.php
> +interface IProvider2 extends IProvider {
```suggestion
interface IProviderWithExpectedRuntime extends IProvider {
```
Or something descriptive like that

2023-11-06 11:40 UTC, marcelklehr commented on core/Controller/TextProcessingApiController.php
> +	 * @return DataResponse<Http::STATUS_OK, array{task: CoreTextProcessingTask}, array{}>|DataResponse<Http::STATUS_INTERNAL_SERVER_ERROR|Http::STATUS_BAD_REQUEST|Http::STATUS_PRECONDITION_FAILED, arra
We never document 500 I believe

2023-11-06 11:42 UTC, provokateurin commented on core/Controller/TextProcessingApiController.php
> +	 * @return DataResponse<Http::STATUS_OK, array{task: CoreTextProcessingTask}, array{}>|DataResponse<Http::STATUS_INTERNAL_SERVER_ERROR|Http::STATUS_BAD_REQUEST|Http::STATUS_PRECONDITION_FAILED, arra
Nope, those don't need a description. The openapi-extractor (or the CI job that runs it) will tell you if there is something wrong.

2023-11-06 11:42 UTC, marcelklehr commented on lib/public/TextProcessing/IProvider2.php
> +interface IProvider2 extends IProvider {
IProviderWithExpectedRuntimeAndUserId :thinking: ?

2023-11-06 11:53 UTC, marcelklehr commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
Good point!

2023-11-06 11:56 UTC, marcelklehr commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
runTask also calls getPreferredProviders, so unless the settings were changed in the meantime it's fairly certain that we'll get the same provider, I'd say

2023-11-06 13:49 UTC, marcelklehr commented on lib/public/TextProcessing/IProvider2.php
> +interface IProvider2 extends IProvider {
Personally I'm in favor of IProvider2 because it supersedes IProvider and is not just an addendum

2023-11-06 14:12 UTC, come-nc commented on lib/public/TextProcessing/IProvider2.php
> +interface IProvider2 extends IProvider {
But will you ever be able to discard the previous one? For user backends we use addendums, and here you could split into `IExpectedRuntimeAwareProvider` and `IUserAwareProvider`.
But yeah fine with `IProvider2` if you know what you’re doing.

2023-11-06 14:13 UTC, come-nc commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
Yeah it’s this whole «likely provider» thing which is scaring me out. But I do not have the big picture here, what is it doing?
Why is it not taking the task as parameter to return expected runtime?

2023-11-06 15:11 UTC, marcelklehr commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
A provider already knows which task type it is used for and I deemed that information good enough to determine the expected runtime. We could pass in the full task with the input text as well, but the basic idea is that we want to know: Will the task be done within 10 seconds or will it take 50 mins?

2023-11-07 08:06 UTC, come-nc commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
It’s not possible for a provider to register for several task types?

2023-11-07 10:16 UTC, marcelklehr commented on lib/private/TextProcessing/Manager.php
> +		if ($provider instanceof IProvider2) {
Nope. One provider per task type

2023-11-07 11:02 UTC, marcelklehr commented on lib/public/TextProcessing/IProvider2.php
> +interface IProvider2 extends IProvider {
I decided to split IProvider2 into `IProviderWithUserId` and `IProviderWithExpectedRuntime`

2023-11-07 11:04 UTC, marcelklehr commented on lib/public/TextProcessing/IProvider2.php
> +	public function getExpectedRuntime(): int;
I think Runtime is quite salient, but I'm not particular about this. Any other opinions?

2023-11-08 11:47 UTC, julien-nc commented on lib/public/TextProcessing/IProvider2.php
> +	public function getExpectedRuntime(): int;
What about `getExpectedRunTime` with a capital T for Time?
I'm fine with `getExpectedRunTime` or `getExpectedProcessingDuration`.

2023-11-08 14:49 UTC, marcelklehr commented on lib/public/TextProcessing/IProvider2.php
> +	public function getExpectedRuntime(): int;
It's also called getExpectedRuntime in the TextToImage API already

2023-11-08 15:35 UTC, julien-nc requested changes
LGTM. Small remarks.

2023-11-08 15:35 UTC, julien-nc commented on lib/private/TextProcessing/Manager.php
> +	public function runOrScheduleTask(OCPTask $task) : bool {
```suggestion
	public function runOrScheduleTask(OCPTask $task): bool {
```
:grin:

2023-11-08 15:35 UTC, julien-nc commented on lib/private/TextProcessing/Manager.php
> +		[$provider, ] = $this->getPreferredProviders($task);
```suggestion
		[$provider,] = $this->getPreferredProviders($task);
```

2023-11-08 15:35 UTC, julien-nc commented on lib/public/TextProcessing/IProviderWithUserId.php
> +	public function setUserId(?string $userId): string;
```suggestion
	public function setUserId(?string $userId): void;
```
Right?

2023-11-08 21:22 UTC, julien-nc approved these changes

2023-11-09 12:37 UTC, come-nc approved these changes

2023-11-10 13:14 UTC, marcelklehr commented
Docs are here: https://github.com/nextcloud/documentation/pull/11273

2023-11-13 09:49 UTC, merged