Support live photos
nextcloud/server pull request #41308
Opened 2023-11-06 15:07 UTC by artonge

- Step 2 of https://github.com/nextcloud/server/issues/40242 

### Changes

- [x] Hide `.mov` file when it has a `live-photo` metadata.
- [x] Show a play icon on `.png` file when it has a `live-photo` metadata.

### Visuals

![image](https://github.com/nextcloud/server/assets/6653109/52b9a3f0-7118-4dbf-8354-a39bd2c3d02d)
![image](https://github.com/nextcloud/server/assets/6653109/cd935884-55eb-4717-9249-fe3c7b3ea4ad)

### Questions

- Where to put the filter logic?
- Should we hard code the play icon in the `FileEntryPreview` component or create an API?

2023-11-08 16:04 UTC, skjnldsv commented
> We should probably improve the contrast of the overlay icon like for the star icon

Do it with css

2023-11-08 16:09 UTC, skjnldsv requested changes, later dismissed

2023-11-08 16:09 UTC, skjnldsv commented on apps/files/src/views/FilesList.vue
> +				.filter(({ attributes: { hidden } }) => hidden !== true)
Sorry, fancy but unreadable.
```suggestion
				.filter(file => file?.attributes?.hidden !== true)
```

2023-11-08 16:09 UTC, skjnldsv commented on apps/files/src/init.ts
> +initLivePhotos()
Why are we not registering the `registerDavProperty('nc:metadata-files-live-photo')` here too?
We migrated away from side-effect action import :)

2023-11-08 16:26 UTC, artonge commented on apps/files/src/init.ts
> +initLivePhotos()
It is not side effect import, the registration is done in `initLivePhotos()`.
This was just to not "pollute" the init script with feature specific code, and keep it all in one file.

2023-11-08 16:35 UTC, skjnldsv commented on apps/files/src/init.ts
> +initLivePhotos()
Indeed! No preference then, I see both points :)

2023-11-09 09:16 UTC, ArtificialOwl approved these changes
back-end part is 👍

2023-11-09 11:50 UTC, susnux approved these changes
some nits

2023-11-09 11:50 UTC, susnux commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const HIDDEN_PROPERTYNAME = '{http://nextcloud.org/ns}hidden';
Probably needs to go in here: https://github.com/nextcloud/documentation/blob/cd26ad08b1713d78750e1789aa4b992e34343d5d/developer_manual/client_apis/WebDAV/basic.rst#supported-properties

2023-11-09 11:50 UTC, susnux commented on apps/files/src/components/FileEntry/FileEntryPreview.vue
> +		<OverlayIcon :is="fileOverlay"
This will break once we migrate to vue3 so you can already prepare by using `<component>` instead:
```suggestion
		<component :is="fileOverlay"
```

2023-11-09 11:50 UTC, susnux commented on apps/files/src/components/FileEntry/FileEntryPreview.vue
> +			class="files-list__row-icon-overlay" />
Alternatively:
```suggestion
		<PlayCircleIcon v-if="isLivePhoto" class="files-list__row-icon-overlay" />
```

Then drop `fileOverlay` and add a computed:
```js
// computed: {
isLivePhoto() {
    return isLivePhoto(this.source)
}
```

2023-11-09 11:50 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +				.filter(file => file)
```suggestion
```
Not needed to call filter twice, this is already checked in the next one

2023-11-09 12:20 UTC, artonge commented on apps/files/src/components/FileEntry/FileEntryPreview.vue
> +			class="files-list__row-icon-overlay" />
No, as we want a generic solution, like for folders

2023-11-09 12:21 UTC, artonge commented on apps/files/src/views/FilesList.vue
> +				.filter(file => file)
The first one checks if a file is `undefined` or null, the second one checks the content of the hidden property. So not a duplicate check, or I misunderstood your comment?

2023-11-09 12:24 UTC, artonge commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const HIDDEN_PROPERTYNAME = '{http://nextcloud.org/ns}hidden';
I added the documentation tag on the PR

2023-11-09 12:26 UTC, artonge commented
Cypress failure unrelated

2023-11-09 12:26 UTC, artonge commented
Cypress failure unrelated

2023-11-09 13:41 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +				.filter(file => file)
Never mind I thought it would be `===` but in this case it makes no sense

2023-11-09 13:41 UTC, susnux approved these changes

2023-11-09 22:53 UTC, artonge commented
CI failure unrelated

2023-11-09 22:53 UTC, merged