fix: Allow to set app order on navigation entries added by closures
nextcloud/server pull request #41341
Opened 2023-11-08 13:25 UTC by susnux

## Summary
Some apps, e.g. talk, use the navigation manager to inject the navigation entry instead of using the appinfo.xml
This caused issues as the app property was not set.

This moves some logic from init of the NavigationManager to the add function and refactors the app order config to use navigation IDs rather than app names + index of navigation from appinfo.xml

Also adjusted frontend code for that change.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-08 23:50 UTC, juliushaertl approved these changes

2023-11-09 08:24 UTC, come-nc commented on lib/private/NavigationManager.php
> +		$entry['order'] = $this->customAppOrder[$id]['order'] ?? $entry['order'] ?? 100;
I’d put that into the if to avoid messing with non-link navigation entries

2023-11-09 08:24 UTC, come-nc commented on tests/lib/App/AppManagerTest.php
> +				'{"settings":{"app":"settings","order":1},"files":{"app":"files","order":2]}',
```suggestion
				'{"settings":{"app":"settings","order":1},"files":{"app":"files","order":2}}',
```

Also, where is app key used?

2023-11-09 10:01 UTC, susnux commented on tests/lib/App/AppManagerTest.php
> +				'{"settings":{"app":"settings","order":1},"files":{"app":"files","order":2]}',
In AppManager to figure out the default app for a user. Otherwise you would have to somehow map an ID to a app which is not possible as the ID can be chosen without any restrictions on closures.

2023-11-09 10:32 UTC, susnux commented on lib/private/NavigationManager.php
> +		$entry['order'] = $this->customAppOrder[$id]['order'] ?? $entry['order'] ?? 100;
Done :heavy_check_mark:

2023-11-09 12:53 UTC, come-nc approved these changes

2023-11-09 12:54 UTC, come-nc requested changes

2023-11-09 12:55 UTC, susnux commented on lib/private/App/AppManager.php
>  					$defaultApps = array_keys($customOrders);
:face_exhaling:

2023-11-09 12:57 UTC, come-nc commented on lib/private/NavigationManager.php
> +			$entry['default'] = ($entry['app'] ?? false) === $this->defaultApp;
What does having default to true does? Because it will be true for all links of the default app this way. If an app has several links, maybe only the first one should have default to true?

2023-11-09 12:57 UTC, come-nc commented on tests/lib/App/AppManagerTest.php
> +				'{"settings":{"app":"settings","order":1},"files":{"app":"files","order":2}}',
We should have a test with several links for a same app, and a test with a closure thing

2023-11-09 13:11 UTC, susnux commented on lib/private/NavigationManager.php
> +			$entry['default'] = ($entry['app'] ?? false) === $this->defaultApp;
Thats the problem of "defaultApp" as we do not have a default app but a default navigation route.

This way we set all routes of that app to default, so all routes of that app are sorted first (with their respective order) and then all other apps follow.

So app1 has `a: order 2` and `b: order 3` as navigation entries, app2 has `c: order 1`.
If you set app1 as default it will look like:
`a, b, c`

If you only set the first route as `default=true`, it looks like:
`a, c, b`

2023-11-09 15:42 UTC, susnux commented on tests/lib/App/AppManagerTest.php
> +				'{"settings":{"app":"settings","order":1},"files":{"app":"files","order":2}}',
Done

2023-11-09 16:53 UTC, come-nc commented on lib/private/NavigationManager.php
> +			$entry['default'] = ($entry['app'] ?? false) === $this->defaultApp;
This is not my experience.
If I add a Photo2 to photos info.xml and I set it first, with Photo third, I get this:
![Screenshot_20231109_175153](https://github.com/nextcloud/server/assets/91878298/66ab544d-d3d5-4bae-92cb-e28939b3f151)

So the order I set in the settings is respected even if I separate a and b.

2023-11-09 17:01 UTC, come-nc approved these changes
The `default` situation is not clear to me but it’s working as expected. (Also I do not know of any application actually registering several links?)

2023-11-10 19:23 UTC, susnux commented on lib/private/App/AppManager.php
> +					// filter only entries with app key (when added using closures or NavigationManager::add the app is not guranteed to be set)
Yes but the "app" is not guaranteed to be set, because for closures / entries added not from appinfo.xml the caller has to set it and we can not set it if not set as we do not know the app.
We can also not enforce it as that would be breaking.

2023-11-10 19:32 UTC, susnux commented on lib/private/NavigationManager.php
> +			$entry['default'] = ($entry['app'] ?? false) === $this->defaultApp;
Yes but that is for the case where you set default app but not the apporder:
Having a second entry for files:
![Screen Shot 2023-11-10 at 20 26 51](https://github.com/nextcloud/server/assets/1855448/f6eb328c-2131-4161-aaf8-9e2ba1c78868)
Setting files as the default app:
![Screen Shot 2023-11-10 at 20 31 12](https://github.com/nextcloud/server/assets/1855448/84f32b17-5321-490d-90dc-1a95cc0cd103)

2023-11-14 09:54 UTC, blizzz commented
/compile /

2023-11-14 16:48 UTC, AndyScherzinger commented on lib/private/App/AppManager.php
> +					// filter only entries with app key (when added using closures or NavigationManager::add the app is not guranteed to be set)
unresolved for the moment as marked to check again

2023-11-14 17:53 UTC, blizzz commented
/compile /

2023-11-14 20:45 UTC, merged