feat(caldav): Create personal event for out-of-office messages
nextcloud/server pull request #41340
Opened 2023-11-08 12:29 UTC by ChristophWurst

* Resolves: https://github.com/nextcloud/server/issues/41337

## Summary

Create and maintain an event in a user's personal calendar when they configure an out of office message.

## TODO

- [x] Create event when OOO is set
- [x] Update event when OOO is updated
- [x] Delete event when OOO is deleted before it ends
- [x] Bug when OOO event is deleted by user and causes a trash bin conflict when deleted again by the system

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-10 19:25 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
I want to write an event and find the same object again when the OOO data changes or gets cleared. Forcing a stable file name is not great because this only works once. After the first deletion there is an entry in the trash bin and the second event can not be moved.

Are there good alternatives or should I just try to disable the trash bin for this automatic event? @miaulalala @tcitworld?

2023-11-13 15:05 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
I could adjust the emitted event so it also transports the previous OOO values. That allows me to find the old event searching by date range.

2023-11-13 15:31 UTC, tcitworld commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
In that case could you use the object UID instead of it's URI ?

2023-11-13 15:43 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
What do you mean?

2023-11-13 16:19 UTC, tcitworld commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
Finding the old event through it's UID instead of it's date range should be faster. Sorry, last message wasn't clear.

2023-11-13 16:47 UTC, tcitworld commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
There's little constraints on UID (alphanumeric + `-`), so you can build your own UID based on deterministic things (user, timestamp).

2023-11-13 16:59 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
I think that's more or less what I tried with `"out_of_office_$token.ics"`. The ID is unique and stable.

It gets problematic if
1) OOO info is created -> integration creates event
2) OOO is changed -> integration deletes previous event, creates new
2) OOO is changed again -> integration deletes previous event :boom: because there would be two "out_of_office_123.ics" in the trash bin now

2023-11-13 17:58 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
Found a better way. I'm just replacing the contents :)

2023-11-13 18:22 UTC, tcitworld commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
Make sure to create an entry into `calendar_changes` too then.

2023-11-13 18:45 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +	}
I'm going through `\Sabre\CalDAV\CalendarObject::put`, so that happens automagically :)

2023-11-14 10:08 UTC, miaulalala requested changes

2023-11-14 10:08 UTC, miaulalala commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +				'VERSION' => '2.0',
If you initialise the object with `new VCalendar()` you don't need to set the defaults manually. You're also missing the ['prodid' which is REQUIRED but MUST NOT occur more than once](https://datatracker.ietf.org/doc/html/rfc5545#section-3.6).

2023-11-14 10:08 UTC, miaulalala commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +			]);
```suggestion
			$vCalendar = new VCalendar();			
			$vCalendar->add($vtimezone);
			// I think this works, but otherwise intialise a new VEvent with the $vCalendar as root.
			$vCalendar->add(
				'VEVENT' => [
					'SUMMARY' => $shortMessage,
					'DESCRIPTION' => $longMessage,
					'STATUS' => 'CONFIRMED',
					'DTSTART' => $start->setTimezone($calendarTimeZone)->setTime(0, 0),
					'DTEND' => $end->setTimezone($calendarTimeZone)->setTime(0, 0),
					'X-NEXTCLOUD-OUT-OF-OFFICE' => $data->getId(),
				],
			]);
```

2023-11-14 10:08 UTC, miaulalala commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +		} else {
early return is possibe here too.

2023-11-14 10:08 UTC, miaulalala commented
You can leave as is except for the PRODID.

2023-11-14 10:43 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +		} else {
not a fan of this tbh because this structure doesn't eliminate any indentation and is more prone to bugs because one has to remember to add early returns everywhere

2023-11-14 10:43 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +				'VERSION' => '2.0',
fixed!

2023-11-14 12:03 UTC, miaulalala requested changes

2023-11-14 12:03 UTC, miaulalala commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +			$vCalendar->add($vtimezone);
Did you mean this?

```suggestion
			$vtimezone = $vtimezoneObj->VTIMEZONE;
			$calendarTimeZone = $vtimezone->getTimeZone();
			$vCalendar->add($calendarTimeZone);
```

2023-11-14 12:32 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +			$vCalendar->add($vtimezone);
No because I want to add the full VTIMEZONE, not the TZID

2023-11-14 12:32 UTC, ChristophWurst commented on apps/dav/lib/Listener/OutOfOfficeListener.php
> +			$vCalendar->add($vtimezone);
Test it

2023-11-14 12:38 UTC, miaulalala approved these changes

2023-11-14 14:51 UTC, AndyScherzinger approved these changes

2023-11-14 14:53 UTC, merged

2023-12-11 11:02 UTC, tcitworld commented
@ChristophWurst  #42142 made me notice I had never submitted my review. Added two comments directly on commit itself since I can't post it anymore.
https://github.com/nextcloud/server/commit/5b7a5474b9fe9bc08f65f48c115ea08ecac5a73c