fix(s3): support SSE-C headers for the MultipartCopy call
nextcloud/server pull request #41366
Opened 2023-11-09 18:33 UTC by ir0nhide

Since a few weeks, I see a lot of HTTP 400 Bad Request errors on HeadObject calls in my Nextcloud logs.
Furthermore I realized, that it is no longer possible to copy a file using the Web-UI.
After further investigations I found out, that this problem is related to the switch to MultipartCopy for copyObject operations on S3 Object Storages.

Looking into the code of the AWS PHP SDK, MultipartCopy executes a headObject request to retrieve the metadata of the source object:
https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartCopy.php#L193
Unfortunately, this request is executed without adding any additional Headers like SSE-C, so that this call fails on setups using SSE-C.

To fix this issue, the source object's metadata can be fetched by a separate headObject request and directly provided to the MultipartCopy object as an input argument, skipping the included headObject request (https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartCopy.php#L196).

This Pull Requests fixes the broken copyObject function on Nextcloud setups using SSE-C for Primary S3 Object Storage.

2023-11-09 19:00 UTC, juliushaertl commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +		] + $this->getSSECParameters());
```suggestion
		$source_metadata = $this->getConnection()->headObject([
			'Bucket' => $this->getBucket(),
			'Key' => $from,
		] + $this->getSSECParameters());
```

2023-11-09 19:00 UTC, juliushaertl requested changes
Small codestyle comment, but otherwise this looks good 👍

2023-11-09 20:14 UTC, ir0nhide commented
@juliushaertl thank you for the review, codestyle should be better now.

2023-11-09 21:35 UTC, juliushaertl approved these changes

2023-11-10 07:47 UTC, solracsf commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +		$source_metadata = $this->getConnection()->headObject([
```suggestion
		$sourceMetadata = $this->getConnection()->headObject([
```

2023-11-10 07:47 UTC, solracsf commented on lib/private/Files/ObjectStore/S3ObjectTrait.php
> +			"source_metadata" => $source_metadata
```suggestion
			"source_metadata" => $sourceMetadata
```

2023-11-10 07:49 UTC, solracsf commented
Small comment as we normaly use camelCase for variables. Good otherwise.

2023-11-10 08:18 UTC, ir0nhide commented
@solracsf thanks for the review, should be fixed now.

2023-11-10 08:37 UTC, solracsf approved these changes

2023-11-15 07:24 UTC, merged

2023-11-15 07:25 UTC, juliushaertl commented
/backport to stable27