Unified sharing options
nextcloud/server pull request #4136
Opened 2017-03-29 08:04 UTC by schiessle

* Allow to set a expire date for all shares, also internal ones
* Allow to password protect mail shares fix https://github.com/nextcloud/server/issues/4078, fix https://github.com/nextcloud/server/issues/2357

2017-03-29 17:23 UTC, jancborchardt commented
@schiessle let me know when it’s ready for review or if you need design fixes.

Is there still the issue that clicking further down on the date picker will close the menu? Maybe then @nextcloud/javascript folks can help you. :)

2017-03-29 17:30 UTC, schiessle commented
@jancborchardt you can already try it out and review it. All the functionality is there. At the moment I just adjust and fix some unit tests in the background.

Following issues exists:

- If you select a date on the datepicker the permissions popover closes. Would be nice if we could find a way to keep it open, cc @nextcloud/javascript 

- If you set a password for a internal share you see a spinner on save which is not positioned correctly, maybe you or @nextcloud/designers can help here with some css magic

2017-03-29 22:23 UTC, TeeDizzle commented
@schiessle and @jancborchardt: Thank you for your work and pushing this into the right direction. 
I just set up an instance based on the new branch and found the password function not to work for me. I can set a password for a share via webmailer and the share will be protected but the password will not be accepted (The password is wrong. Try again.) trying to open the link. The same behaviour I experience sharing and password protecting a link manually, here aditionally a never disappearing spinner shows up indicating some incomplete action.
Last but not least I really hope you will find a way to make the current automatic sending of the share password via webmailer optional and not a default to meet **previous** security standards. Please refer to my comments on [#2357](https://github.com/nextcloud/server/issues/2357) for this.

2017-03-30 09:38 UTC, schiessle commented
@TeeDizzle Thanks for testing. I will look into the password check issue. The plan is also to have a admin setting "Send password by mail" which you can disable if you wish.

2017-03-30 09:42 UTC, TeeDizzle commented
@schiessle: Great to hear that, thank you so much. I will keep the test instance updated as you proceed and continue to report back.

2017-03-30 13:51 UTC, nickvergessen commented
~~I get~~
> ~~Error while sharing~~
~~Invalid date. Format must be YYYY-MM-DD~~

~~When setting a password for a mail share.~~

Works perfectly. Nice roundhouse kick for all the sharing feature requests 🎉

2017-03-30 13:55 UTC, nickvergessen submitted a review, later dismissed
Needs an entry in capabilities

2017-03-30 16:23 UTC, schiessle commented
@nickvergessen capabilities added

2017-03-31 06:03 UTC, diopgm commented
hi - wanted to give it a try, but can't get it patched:
https://help.nextcloud.com/t/how-do-i-implement-a-change-pullrequest-available-on-github/10827/2
any help appreciated!

2017-03-31 06:57 UTC, supremesyntax commented
@diopgm 
This is how i did it. This downloads the complete server code to set up a new virtual host for testing for example
1. git clone https://github.com/nextcloud/server.git
2. cd server
3. git submodule update --init
4. git checkout -t origin/expire-date-for-all-shares
5. git pull

2017-03-31 07:17 UTC, diopgm commented
sorry, i dont want to hijack this thread for my troubles :)
but thanks supremesyntax for this input, although i would like to update my regular nextcloud installation, not create a new virtual host - as this is still not a productive system yet
also, i'm not familiar with what happens behind the curtain through these commands :)
but thanks for your input :+1:

2017-03-31 08:15 UTC, supremesyntax commented
@schiessle @jancborchardt Just got a port forward from my admin for e-mail smtp access. I have tested the e-mail function after a fresh "git pull" and it looks good to me. seems like a good compromise between bringing back the old "send password protected link" function and unifying the input fields. i will talk to some end-user to get their point of view and see if this would get accepted and will report back next week. good work!

2017-03-31 09:12 UTC, diopgm commented
version 12?
well, thats a bit disappointing :( 
its probably miles away still, and i would like to have the feature in the documentation back (send mail links) and thought this here would be my best try :(
seems like i have to switch to a different sw then, to fulfill the users request in time now :( too bad, liked nc so far
thanks supremesyntax for your input
anyone let me know if there is a way to get that documented feature back into 11.0.2

2017-03-31 09:18 UTC, schiessle commented
@diopgm There is no way to backport such large features. And Nextcloud 12 is not that far away as you might think, even if I can tell you a exact release day at the moment.

2017-03-31 10:22 UTC, diopgm commented
ok, thanks for the info!

2017-03-31 12:51 UTC, rullzer commented
For some reason the .. menu for link shares is always visible it seems

2017-03-31 12:59 UTC, rullzer submitted a review, later dismissed

2017-03-31 12:59 UTC, rullzer commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
:see_no_evil:

2017-03-31 12:59 UTC, rullzer commented
Mmmm sombody with more javascript foo has to look at this... summoning @MorrisJobke   @ChristophWurst

2017-03-31 13:08 UTC, schiessle commented
@supremesyntax thanks for your feedback

> Edit: Important! It is still possible to share via e-mail without the password is being set!! This should not be possible. I have set 'Enforce password protection'. Somehow you should respect this. So do not send out the e-mail with the link before password is set when admin settings say so!

I don't think we can easily provide a similiar workflow for mail shares. On link shares this is relatively easy, once you click on the link-share checkbox we show you first the password field and then the link. For share by mail this is not really possible because it all starts with entering a email address and then you have to set the password in the permissions drop down. 

> The option 'Set default expiration date' is also not respected when sharing stuff via e-mail. In my understanding the expiration date should be automatically preset and ticked when sharing an object if admin made the choice.

I think we could do this but in order to do it we would need to move the settings from the "public link section" to the general share settings which would rise the question how to handle enforced expiration dates, see below.

> Enforcing the expiration date is also not respected.

I thought about this already as well. Now that you can set the expire date for all shares we could also apply the enforced and suggested expire date to all shares. But I skipped it for now because I considered it to restrictive. In order to make it easy to understand it I think there are only two options: Only apply it to link shares (that's the current behavior) or apply it to all shares. Applying it to link shares and to some shares created by the share dialog is to confusing, in my opinion. But I'm open for more opinions, e.g. @jancborchardt 

While discussing this please also keep in mind that through the new "social sharing" option in 12 (https://github.com/nextcloud/socialsharing) you will be able to share normal public links again by mail. So there is still the option to disable share by mail completely, if you really want to.

Enforcing the expiration date is also not respected.

2017-03-31 13:41 UTC, supremesyntax commented
@schiessle ok i see your points. 

> I don't think we can easily provide a similiar workflow for mail shares. On link shares this is relatively easy, once you click on the link-share checkbox we show you first the password field and then the link. For share by mail this is not really possible because it all starts with entering a email address and then you have to set the password in the permissions drop down.

I would think of these 2 cases:

enforce password off:
1. enter e-mail
2. choose e-mail address with (email) appendix
3. boom it should be sent

enforce password on:
1. enter e-mail
2. choose e-mail address with (email) appendix 
3. e-mail should not be sent but be greyed out until you enter a password
4. after you have entered the password both e-mails (link / password) should be sent.

Otherwise i will have to live by the term 'security before convenience' and disable mail shares in general if that will be possible in 12

> I think we could do this but in order to do it we would need to move the settings from the "public link section" to the general share settings which would rise the question how to handle enforced expiration dates, see below.

> I thought about this already as well. Now that you can set the expire date for all shares we could also apply the enforced and suggested expire date to all shares. But I skipped it for now because I considered it to restrictive. In order to make it easy to understand it I think there are only two options: Only apply it to link shares (that's the current behavior) or apply it to all shares.

Why not give the admin the choice to handle things separately? Just give both options.
Expiration date suggestion/enforcement under Public link section **and** general share section

2017-03-31 13:46 UTC, schiessle commented
> For some reason the .. menu for link shares is always visible it seems

which menu do you mean? For me everything looks OK. Do you have a screenshot?

2017-03-31 13:50 UTC, schiessle commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
fixed

2017-03-31 15:22 UTC, schiessle commented
>> For some reason the .. menu for link shares is always visible it seems

> which menu do you mean? For me everything looks OK. Do you have a screenshot?

Do you mean this? As described in the issue I see this behavior also on master, not only on this branch: https://github.com/nextcloud/socialsharing/issues/9

2017-03-31 15:24 UTC, rullzer commented
ah yes. OK I'll look into that than :wink:

2017-04-03 06:56 UTC, ChristophWurst submitted a review, later dismissed

2017-04-03 06:56 UTC, ChristophWurst commented on apps/files_sharing/lib/Capabilities.php
> +			$res['user']['expire_date']['enabled'] = true;
duplication of https://github.com/nextcloud/server/pull/4136/files#diff-ce11fa52acdfc132e8854ee17e90c873R92 ?

2017-04-03 06:56 UTC, ChristophWurst commented on apps/files_sharing/lib/Capabilities.php
> +			$res['user']['expire_date']['enabled'] = true;
is `$res['user']['expire_date']` set anywhere?

2017-04-03 06:56 UTC, ChristophWurst commented on apps/files_sharing/tests/MigrationTest.php
> +				$this->assertSame(null, $share['share_with']);
FYI: you could use `$this->assertNull(…)` too

2017-04-03 06:56 UTC, ChristophWurst commented on apps/files_sharing/tests/MigrationTest.php
> +				$this->assertSame(null, $share['password']);
same here

2017-04-03 06:56 UTC, ChristophWurst commented on apps/sharebymail/js/settings-admin.js
> +	$('#sendPasswordMail').on("change", function() {
use single quotes `'` instead please

2017-04-03 06:56 UTC, ChristophWurst commented on apps/sharebymail/js/settings-admin.js
> +        }
seems like you've used spaces instead of tabs. Please replace them and fix the indentation ;-)

2017-04-03 06:56 UTC, ChristophWurst commented on apps/sharebymail/js/settings-admin.js
> +$(document).ready(function () {
`$(function() {` is shorter and does the same 😉

2017-04-03 06:56 UTC, ChristophWurst commented on apps/sharebymail/lib/ShareByMailProvider.php
> +		$subject = (string)$this->l->t('Password to access »%s« shared to you by %s', array($filename, $initiatorDisplayName));
I think we only use the short array syntax everywhere now

2017-04-03 06:56 UTC, ChristophWurst commented on lib/public/Share/IShare.php
> +	 * @param \DateTime | null $expireDate
AFAIK there must not be any space between the alternatives, like `\DateTime|null`

2017-04-03 08:17 UTC, schiessle commented on apps/files_sharing/lib/Capabilities.php
> +			$res['user']['expire_date']['enabled'] = true;
one is for group shares and one for user shares.

2017-04-03 08:18 UTC, schiessle commented on lib/public/Share/IShare.php
> +	 * @param \DateTime | null $expireDate
at least for phpstorm it doesn't make a difference.

2017-04-03 08:39 UTC, schiessle commented
@ChristophWurst thanks for your review. I think all comments are addressed with my last commits. Do you think you can have a look at the issue with the date picker, to avoid that the underlaying popover is closed while you select a date from the datepicker? This would be great! 😃

2017-04-03 09:20 UTC, ChristophWurst commented
@schiessle the problem is that the datepicker is *outside* the menu, hence the click event is interpreted as if one clicks somewhere else and thus we close the menu. From inspecting the code I can tell that the datepicker is apparently an element in the body, probably placed by jquery UI.
I can't think of any non-hacky solution right now. Do we use a similar menu + datepicker combo somewhere else? Then I could check how we do that there.

2017-04-03 10:35 UTC, schiessle commented
> the problem is that the datepicker is outside the menu, hence the click event is interpreted as if one clicks somewhere else and thus we close the menu.

That's also my conclusion

> From inspecting the code I can tell that the datepicker is apparently an element in the body, probably placed by jquery UI.

Yes, afaik the date picker gets placed by jquery at the bottom of the page as far as I can tell if I inspect the code during runtime.

> Do we use a similar menu + datepicker combo somewhere else? Then I could check how we do that there.

Not that I'm aware of, maybe the calendar? cc @georgehrke 

Isn't it possible to do something with preventDefault(), etc to prevent the event to happen? I tried it already and couldn't get it working  but maybe I added it to the wrong place... Or something like "if datepicker is open, don't close the popover" but that would probably one of the hacky solutions you mentioned 😉

2017-04-03 18:01 UTC, MorrisJobke commented
> Isn't it possible to do something with preventDefault(), etc to prevent the event to happen? I tried it already and couldn't get it working but maybe I added it to the wrong place... Or something like "if datepicker is open, don't close the popover" but that would probably one of the hacky solutions you mentioned.

Yep - that is also the only way I have in mind, but it's hacky, because we then would need to put this logic into the basic popover code :/

2017-04-04 07:23 UTC, jospoortvliet commented
* [ ] Shouldn't it be possible for a single file share to be editable (Collabora Online...)?
* [ ] should a folder share to a group not also have the Secure drop feature?

2017-04-04 13:00 UTC, schiessle commented
>  Shouldn't it be possible for a single file share to be editable (Collabora Online...)?

Yes, it is on my ToDo. Will do it in a seperate PR. This is already large enough ;)

> should a folder share to a group not also have the Secure drop feature?

no, internally we don't have something like secure drop. This would need a whole new UI. You see a folder, navigate into it and see the secure drop screen instead of the folders content. Might be a nice idea, but not for this PR

2017-04-04 13:56 UTC, schiessle commented
> Yep - that is also the only way I have in mind, but it's hacky, because we then would need to put this logic into the basic popover code :/

If this is the only solution we can think of we should probably do it. Better a hacky solution on source code level than a shitty UX.

Just one more idea from my side? Would it be possible to embed the calendar drop down in the popover? This would solve it as well, but maybe it would look bad if we resize the popover if we show/hide the calendar.... Just thinking.

2017-04-05 11:32 UTC, blizzz commented
You can embed the date picker into a div easily. It needs some more changes to act properly (perhaps hide the text input then), but it will be unusable/ugly with small screen sizes.

```diff
diff --git a/core/js/sharedialogshareelistview.js b/core/js/sharedialogshareelistview.js
index b77e825f3f..378cfb8b92 100644
--- a/core/js/sharedialogshareelistview.js
+++ b/core/js/sharedialogshareelistview.js
@@ -476,7 +476,7 @@
            var li = element.closest('li[data-share-id]');
            var shareId = li.data('share-id');
            var expirationDatePicker = '#expirationDatePicker-' + this.cid + '-' + shareId;
-           $(expirationDatePicker).datepicker({dateFormat : 'dd-mm-yy'});
+           $(expirationDatePicker).closest('div').datepicker({dateFormat : 'dd-mm-yy'});
            $(expirationDatePicker).focus();
        },
 
```

![spectacle v21873](https://cloud.githubusercontent.com/assets/2184312/24703539/e2df475e-1a03-11e7-9e25-aa8b7a1b4e00.png)

Not sure what's better… to make this work properly or try to find a not-too bad way to figure out how to not close the popup menu.

2017-04-05 12:03 UTC, schiessle commented
For me it looks quite good as long as the sidebar fits on the screen, see (that's a 300px wide screen, browser zoom 100%):

![expire](https://cloud.githubusercontent.com/assets/1589737/24704527/5a02e0e4-1a08-11e7-8b65-f3efca3c4643.png)

If I reduce the browser zoom I can make the window smaller and it still fits on the screen. If I keep the browser zoom and make the window smaller parts of the sidebar start to disappear (also if the dropdown is closed). So I would say that as long as it looks good as long as the sidebar fits on the screen this is fine.

2017-04-05 12:13 UTC, blizzz commented
Mine looks different, properly only with a width of >=14235px. No idea why it looks so much different for you 🤷‍ design folks to the rescue :D

2017-04-05 12:17 UTC, schiessle commented
while playing around and trying to remove the input field as long as the datepicker is open I observed a functional issue with this approach. If I put the datepicker in the popover div the change event is no longer triggered if I select a date.

2017-04-05 13:24 UTC, blizzz commented
[onSelect](https://api.jqueryui.com/datepicker/#option-onSelect) is your friend.

```diff
diff --git a/core/js/sharedialogshareelistview.js b/core/js/sharedialogshareelistview.js
index b77e825f3f..ede01654be 100644
--- a/core/js/sharedialogshareelistview.js
+++ b/core/js/sharedialogshareelistview.js
@@ -476,7 +476,15 @@
            var li = element.closest('li[data-share-id]');
            var shareId = li.data('share-id');
            var expirationDatePicker = '#expirationDatePicker-' + this.cid + '-' + shareId;
-           $(expirationDatePicker).datepicker({dateFormat : 'dd-mm-yy'});
+           var view = this;
+           $(expirationDatePicker).closest('div').datepicker({
+               dateFormat : 'dd-mm-yy',
+               onSelect:
+                   function (expireDate) {
+                       view.setExpirationDate(shareId, expireDate);
+                   },
+               showButtonPanel: true
+           });
            $(expirationDatePicker).focus();
        },
 

```

Plus you can kill the whole onChangeExpirationDate method.

Needs some other things then, though: 
* cancel is not possible. The button panel should show up, but doesnt for me
* showing and hiding it is very noisy

2017-04-05 14:53 UTC, schiessle commented
With the help of @blizzz I have put the calendar now inside the popover. Works quite nicely and I think it looks good

> cancel is not possible. The button panel should show up, but doesnt for me

it get's hidden by closing the drop-down. Imho it doesn't hurt if it stays open as long as the dropdown is open. If you clicked on "set expire date" by accident you can also hide it by clicking the checkbox again.

> showing and hiding it is very noisy

I removed the input field when the date picker is shown. This makes it look more smooth in my opinion and looks quite good.

2017-04-05 14:55 UTC, schiessle commented
from my point of view that's ready to review

2017-04-05 19:36 UTC, jospoortvliet commented
Tested locally. I had some issues with the setting of a password but that might be a local problem. I suggest to try and set a password, try one that will be denied by policy ("test"), unset it, try to set it again. If that works - my problem is local.
The calendar gets a bit small but it works even on 1280x720.

The rest worked from what I could tell, nice work ;-)

2017-04-06 09:35 UTC, schiessle commented
@jospoortvliet Thanks for testing. The issue was introduced by some other changes we did on master in parallel. I adjusted the code to match this changes. Everything should work now again. 😃

2017-04-06 13:31 UTC, schiessle commented
Would be awesome to get this in... @rullzer @nickvergessen @ChristophWurst all your comments are addressed. Please do a final review. Thanks!

2017-04-06 16:29 UTC, MorrisJobke commented
* [ ] If the date is set and you close and open the drop down again, then the date is invisible and only visible on hover:
<img width="410" alt="bildschirmfoto 2017-04-06 um 11 26 21" src="https://cloud.githubusercontent.com/assets/245432/24765028/f01dfac4-1abb-11e7-950c-678768e267fe.png">

This is caused by this entry:

```
.bubble li .menuitem, .app-navigation-entry-menu li .menuitem, .popovermenu li .menuitem {
    -ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=50)' !important;
    filter: alpha(opacity=50) !important;
    opacity: 0.5 !important;
}
```

@jancborchardt Please have a look. The menu opacity thing is a nightmare :/ Too much resets and too much `!important`s

2017-04-06 16:29 UTC, MorrisJobke requested changes
See my comment

2017-04-07 08:52 UTC, schiessle commented
@MorrisJobke I can't reproduce it. This is how it looks for me:

![permissions](https://cloud.githubusercontent.com/assets/1589737/24792885/1e17a8b6-1b80-11e7-8aa7-3fd5dac26f02.png)

After I set the expire date, close and re-open the permission drop down. Tested with Firefox 52.0.2 and Chromium 57.0.2987.98

I saw some screenshots from @jospoortvliet yesterday which also looked OK.

2017-04-07 09:03 UTC, rullzer commented
Mmm why does it display the timestamp... I can look into that part... it should just show the date.

2017-04-07 09:15 UTC, schiessle commented
@rullzer good question. It shows what the share API returns. Maybe we need to re-format it before we show it. Or change the share API that it returns the right format right away.

2017-04-07 09:17 UTC, rullzer commented
Nah we need to parse it trough moment... I can do that later

2017-04-07 09:18 UTC, rullzer commented
Basically I the date should be localized. So our american users get their weird date format as well

2017-04-07 12:49 UTC, rullzer commented
okidoki date now looks sane...

2017-04-07 12:49 UTC, rullzer approved these changes
We'll probabaly find some bugs later. But for now lets do this!

2017-04-07 17:52 UTC, MorrisJobke commented
> Tested with Firefox 52.0.2 and Chromium 57.0.2987.98. Which Browser did you used?

Chrome and Safari. But let me recheck.

2017-04-07 18:46 UTC, jancborchardt commented
Fixed the transparency issue – just made everything full opacity because the checkmarks indicate if it’s checked.

Also fixed the font-weight of the »Unshare« entry.

2017-04-07 19:53 UTC, MorrisJobke commented
> okidoki date now looks sane...

Not here. I guess @jancborchardt has overwritten your changes.

2017-04-07 22:12 UTC, MorrisJobke approved these changes
Tested and works now 👍

2017-04-07 22:14 UTC, merged

2017-04-08 17:14 UTC, jancborchardt commented
> Not here. I guess @jancborchardt has overwritten your changes.

Just for the record: I didn’t overwrite anything. ;)

2017-04-10 09:05 UTC, schiessle commented
Was my mistake :/