Match slashes in ../{id} resource routes
nextcloud/server pull request #4138
Opened 2017-03-29 09:15 UTC by rullzer

Fixes #2954

Before we could match on <prefix>/{id} however if the id contains a /
this would not match properly. But since we define the resource routes
internally we now make sure that we match all chars (up until the ?).

to test:

1. create a group `foo/bar`
2. Delete the group

Before: nope
Now: yes, master

CC: @hirschrobert

2017-03-29 12:03 UTC, nickvergessen requested changes
I think we should specify that on the routes which are affected:
https://github.com/nextcloud/notifications/blob/master/appinfo/routes.php#L24

Not in general. And with your current approach I think you even kill existing restrictions?

2017-03-29 12:05 UTC, nickvergessen commented
This will also cause problems with:
`/groups/{groupId}` vs. `/groups/{groupId}/subadmins` ?! (provisioning api) also the name does not match there, so they still wouldnt allow slashes...

2017-03-29 12:08 UTC, rullzer commented
we don't do it in general. Only for resources like https://github.com/nextcloud/server/blob/master/settings/routes.php#L40

I see no use case where you'd generate a resource url like `<prefix>/foo/bar` and only want to match on foo and ignore bar (because bar will be ignored as the resources specifies itself as `<prefix>/{id}`)

2017-03-29 17:14 UTC, rullzer commented
@nickvergessen so this way now or are you going to rewrite it to use the provisioning api?

2017-03-30 12:53 UTC, nickvergessen approved these changes
yeah let's try it

2017-04-04 20:52 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-04-04 20:52 UTC, merged

2017-04-18 20:57 UTC, MorrisJobke commented
Reverted in #4381