Migrate old metadata table to the new ones
nextcloud/server pull request #41465
Opened 2023-11-14 15:29 UTC by artonge

Signed-off-by: Louis Chemineau <louis@chmn.me>

2023-11-14 16:17 UTC, artonge commented
Pinging nick just for DB expertise

2023-11-14 16:19 UTC, nickvergessen requested changes, later dismissed
Missing autoloader update

2023-11-14 16:22 UTC, nickvergessen commented on core/Migrations/Version280000Date20231114135824.php
> +		private IFilesMetadataManager $filesMetadataManager,
We try to avoid using services in upgrade mechanisms at any cost. If the OCP interface changes at some point, no one has an old state to test if the result still works as expected.

If time permits I would recommend to switch to plain IDBConnection / IQueryBuilder implementation

2023-11-15 17:32 UTC, artonge commented on core/Migrations/Version280000Date20231114135824.php
> +		private IFilesMetadataManager $filesMetadataManager,
I move the migration to a repair step. Thanks for the warning :)

2023-11-15 20:53 UTC, ArtificialOwl approved these changes

2023-11-16 08:08 UTC, AndyScherzinger approved these changes

2023-11-16 08:10 UTC, Altahrim commented on core/BackgroundJobs/MigrateMetadataJob.php
> +				$deleteQuery->executeStatement();
Each pass should be in a transaction, no?
```suggestion
				$this->connection->startTransaction();
				$metadata = $this->filesMetadataManager->getMetadata($row['id'], true);

				switch ($row['group_name']) {
					case 'size':
						$metadata->setArray('photos-size', json_decode($row['value'], true));
						break;
					case 'gps':
						$metadata->setArray('photos-gps', json_decode($row['value'], true));
						break;
					case 'photos_place':
						$metadata->setString('photos-place', $row['value'], true);
						break;
				}

				$this->filesMetadataManager->saveMetadata($metadata);
				$deleteQuery->setParameter('id', $row['id']);
				$deleteQuery->setParameter('group_name', $row['group_name']);
				$deleteQuery->setParameter('value', $row['value']);
				$deleteQuery->executeStatement();
				$this->connection->commit();
```

2023-11-16 08:10 UTC, Altahrim commented on core/BackgroundJobs/MigrateMetadataJob.php
> +				return;
Maybe indicate we reached the time limit and the job should be relaunched?

2023-11-16 08:19 UTC, artonge commented on core/BackgroundJobs/MigrateMetadataJob.php
> +				return;
It is a background job, it will be restarted by itself ;)

2023-11-16 08:21 UTC, artonge commented on core/BackgroundJobs/MigrateMetadataJob.php
> +				$deleteQuery->executeStatement();
True, but I'll make it per chunk, meaning select + inserts + deletes, instead of per entry.

2023-11-16 08:38 UTC, artonge commented on core/BackgroundJobs/MigrateMetadataJob.php
> +				$deleteQuery->executeStatement();
Done :+1:

2023-11-16 10:14 UTC, Altahrim approved these changes

2023-11-16 10:20 UTC, merged

2023-11-19 23:02 UTC, MichaIng commented
It seems we have a chicken&egg issue here when upgrading via web UI: The page throws an internal server error, caused by the missing `files_metadata` table, before the migration can be even applied:
```
{"reqId":"HxcBDrK6I4FzTVtUfi8b","level":4,"time":"2023-11-19T23:46:40+01:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/files/preview-service-worker.js","message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_files_metadata' doesn't exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/106.0.0.0 (Edition developer)","version":"28.0.0.3","exception":{"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_files_metadata' doesn't exist","Code":1146,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1938,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1880,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1105,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":261,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":337,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":377,"function":"executeQuery","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php","line":171,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1324,"function":"get","class":"OC\\Files\\Cache\\Cache","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1374,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":203,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":161,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/AppData/AppData.php","line":132,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ImageManager.php","line":365,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ImageManager.php","line":101,"function":"getRootFolder","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php","line":432,"function":"getImage","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php","line":403,"function":"getCustomFavicon","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/var/www/nextcloud/lib/private/URLGenerator.php","line":222,"function":"replaceImagePath","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/template/functions.php","line":249,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/nextcloud/core/templates/layout.guest.php","line":20,"function":"image_path"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":180,"args":["/var/www/nextcloud/core/templates/layout.guest.php"],"function":"include"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":139,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":170,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":211,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":182,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1117,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":49,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_files_metadata' doesn't exist","Code":1146,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":132,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1098,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":261,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":337,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":377,"function":"executeQuery","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php","line":171,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1324,"function":"get","class":"OC\\Files\\Cache\\Cache","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1374,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":203,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":161,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/AppData/AppData.php","line":132,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ImageManager.php","line":365,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ImageManager.php","line":101,"function":"getRootFolder","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php","line":432,"function":"getImage","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/var/www/nextcl [...]

2023-11-20 09:19 UTC, artonge commented
I think a similar issue has already been fixed. @ArtificialOwl maybe when could add another check?

> Btw, is it intended that there is now both: file_metadata as well as files_metadata?
Yes, the former is supposed to be deleted.

FYI, the logs are not caused by this PR.

2023-11-20 09:27 UTC, nickvergessen commented
It's of course a bit weird that `GET /nextcloud/index.php/apps/files/preview-service-worker.js` is ran on any page, including the updater...

2023-12-02 15:35 UTC, MichaIng commented
I retested on a fresh default Nextcloud 27 installation, switched to beta channel, and ran into the same error with NC 28 RC2. The web interface, where one should be able to run the database upgrade/migrations, throws:
![image](https://github.com/nextcloud/server/assets/28480705/0714315d-8e45-4444-a9f8-a58a9ec4e593)

The logs are paste above already. Yes, this PR does not cause the logs/error, but it does not solve it (which it aims to) when using the web updater, since the new table is expected before this migration can run. Let me know whether I should open a new issue for this, as it is serious and must block NC 28 release.

2023-12-02 15:54 UTC, nickvergessen commented
Please raise a new issue, add the feedback 28 label and ping AndyScherzinger