feat(comments): Plug in comments into activity sidebar tab if available
nextcloud/server pull request #41491
Opened 2023-11-15 11:24 UTC by susnux

* Resolves: #658 
* Replaces: #41483 
* Requires: https://github.com/nextcloud/activity/pull/1416

## Summary
This is a more stable approach than #41483, if activity is enabled we plug into their stream and provide the comments.

### Screenshot

https://github.com/nextcloud/server/assets/1855448/d414c961-a7c6-4b73-bdc8-f5724e2e7aa0

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-15 11:31 UTC, AndyScherzinger approved these changes

2023-11-15 12:28 UTC, artonge approved these changes

2023-11-15 13:50 UTC, nickvergessen requested changes
This breaks the comments API when used by other apps again, as pointed out in the previous PR

2023-11-15 15:30 UTC, nickvergessen commented
> Did you test this?

yes, something is hardcoding the object type to `files` and try tomorrow again (or you install https://github.com/nextcloud/announcementcenter and try it yourself)

2023-11-15 16:08 UTC, susnux commented
OK I know whats going on here... Have I ever said I hate mixins?
I had some weird issues were the type was not set, so I set it to files, well turns out the comments API sets it using mixins syntax from hell. I will fix this.

2023-11-15 23:15 UTC, susnux commented
Should be fixed now @nickvergessen 

<details>
I really do not like code that hides what happens, in this case the comment type was injected only in one of the entry points as as a Mixin (**!**) instead of declaring it a prop so you know that it is there are need to be set / can be set.
</details>

2023-11-16 09:01 UTC, come-nc commented on apps/comments/src/comments-tab.js
> +	// Do mount own tab but mount into activity
```suggestion
	// Do not mount own tab but mount into activity
```
Typo?

2023-11-16 10:33 UTC, artonge commented
Rebased and fixed come's comment

2023-11-16 10:39 UTC, nickvergessen commented
Public API still doesn't work here. But now we have a different error:
![grafik](https://github.com/nextcloud/server/assets/213943/83e84d2b-00fd-4072-a9e2-77ef750185ff)

2023-11-16 10:41 UTC, nickvergessen commented on apps/comments/src/mixins/CommentMixin.js
> +		commentsType: {
ressourceId is the counter part/ID to this, so ressourceType would be more matching?

2023-11-16 10:46 UTC, nickvergessen requested changes

2023-11-16 10:46 UTC, nickvergessen commented on apps/comments/src/mixins/CommentView.ts
> +		commentsType: {
```suggestion
		ressourceType: {
```

2023-11-16 10:46 UTC, nickvergessen commented on apps/comments/src/mixins/CommentView.ts
> +					itemType: 'files',
can we use the `ressourceType` here?

2023-11-16 10:46 UTC, nickvergessen commented on apps/comments/src/services/CommentsInstance.js
> +			...options,
undefined is not handled here.

2023-11-16 10:46 UTC, nickvergessen commented on apps/comments/src/services/CommentsInstance.js
> +			...options,
When modifying my app from
```js
 new OCA.Comments.View('announcement')
```
to
```js
 new OCA.Comments.View('announcement', {})
```

it works, but maybe we can avoid this breaking

2023-11-16 10:46 UTC, nickvergessen commented on apps/comments/src/views/Comments.vue
> +			:comments-type="commentsType"
also resource-type and resourceType everywhere here?

2023-11-16 10:50 UTC, susnux commented on apps/comments/src/mixins/CommentView.ts
> +		commentsType: {
Did not change it, the name was used before

2023-11-16 10:51 UTC, susnux commented on apps/comments/src/mixins/CommentView.ts
> +		commentsType: {
But I can change it if you like

2023-11-16 10:52 UTC, artonge commented on apps/comments/src/mixins/CommentMixin.js
> +		commentsType: {
`commentsType` was already used in the code. Let's keep it like that

2023-11-16 10:52 UTC, artonge commented on apps/comments/src/mixins/CommentView.ts
> +		commentsType: {
Let's keep it like that

2023-11-16 10:53 UTC, susnux commented on apps/comments/src/services/CommentsInstance.js
> +			...options,
Well this only worked by luck as the "API" of comments never had that part optional
`* @param  {object} options the vue options (propsData, parent, el...)`
instead of 
`* @param  {object|undefined} options the vue options (propsData, parent, el...)`

But yes I can make this optional.

2023-11-16 10:53 UTC, artonge commented on apps/comments/src/services/CommentsInstance.js
> +			...options,
Will push a fix

2023-11-16 10:54 UTC, artonge commented on apps/comments/src/views/Comments.vue
> +			:comments-type="commentsType"
As said, outside of the scope of this PR

2023-11-16 10:57 UTC, artonge commented
@nickvergessen I tested with annoncement center. Should be fine now :)

2023-11-16 10:59 UTC, susnux commented on apps/comments/src/mixins/CommentMixin.js
> +		commentsType: {
Did not change any naming there but yes can do so

2023-11-16 11:00 UTC, susnux commented
@nickvergessen resolved you comments should be fine now

2023-11-16 11:04 UTC, nickvergessen commented
> Oh we did this simultaneously :/

All hail to `git push --force-with-lease` I guess

2023-11-16 11:08 UTC, nickvergessen commented
Now the hardcoded `files` is back? 
`/remote.php/dav/comments/files/1`

2023-11-16 11:14 UTC, nickvergessen commented
> Now the hardcoded files is back?

Only on posting, loading old comments works properly

2023-11-16 12:02 UTC, susnux commented
> Now the hardcoded files is back?

There is no hardcoded 'files', only if you do not set the appropriate `ressourceType` it falls back to files by default.

Here:
https://github.com/nextcloud/announcementcenter/blob/91188b48845c3b2175eefd4fd4ecff2036a7d70e/src/App.vue#L150C35-L150C62

No resource type is set, what ressource type do you expect it to use?

2023-11-16 12:06 UTC, nickvergessen commented
> No resource type is set, what ressource type do you expect it to use?

The first argument is the resource type!?

2023-11-16 13:17 UTC, nickvergessen commented
There were some mixing of the property name making it fallback to the default `'files'`
I added a commit (and merged the recompile into the previous commit)

But now it works in files and announcements.

2023-11-16 13:18 UTC, nickvergessen approved these changes

2023-11-16 14:02 UTC, susnux commented
Cypress is unrelated (flaky user-creation test)

2023-11-16 17:25 UTC, merged