Improve date-range logic for global search
nextcloud/server pull request #41507
Opened 2023-11-15 15:07 UTC by Fenn-CS

- Allow future dates in custom date range
- Fix date ranges for example, before now, today range was roughly between `now()` to `now() + a few milli seconds`

Resolves : https://github.com/nextcloud/server/issues/41492, https://github.com/nextcloud/server/issues/41381

## Summary

## TODO

## High
- [ ] Mail previews not right 
- [ ] Broken folder icon in files results
- [ ] Messages: avatar in circles not squares
- [ ] “Search in app” is only available for a few apps (remove links)

## Medium
- [ ] Contacts filter shouldn’t be available if contacts app is not available 
- [ ] No space for icons in modified

## Low
- [ ] Apply range primary to the right 
- [ ] Date range filter -> custom date range
- [ ] Apply range -> Search in date range
- [ ] Text in people regular not bold
- [ ] Close icon material design icon "close" instead of "close-thick"
- [ ] Cursor pointer instead on hovering close icon
- [ ] Avatar in filter chips shouldn't be clickable and size should be 24px

2023-11-20 10:20 UTC, Fenn-CS commented
This should get reviewed and merged, so smaller follow up prs get in faster, it makes things faster and gets as much as possible into the regular build schedule.

2023-11-20 10:46 UTC, artonge approved these changes

2023-11-20 13:18 UTC, Fenn-CS commented
/compile amend /

2023-11-20 16:08 UTC, Fenn-CS commented
/compile amend /

2023-11-20 17:00 UTC, Fenn-CS commented
/compile amend /

2023-11-21 10:21 UTC, Fenn-CS commented
/compile amend /

2023-11-21 10:33 UTC, Fenn-CS commented
/compile amend /

2023-11-21 12:28 UTC, susnux requested changes
missing appkey for translation, this will not work :/

2023-11-21 12:28 UTC, susnux commented on core/src/components/GlobalSearch/CustomDateRangeModal.vue
> +		:title="t('Custom date range')"
```suggestion
		:title="t('core', 'Custom date range')"
```

2023-11-21 12:33 UTC, susnux commented on core/src/components/GlobalSearch/SearchResult.vue
> +			<div class="result-items__item-icon"
Either this or set `alt=""` on the `<img>` tag. But I think hiding it is correct here as this is pure representation (images).

```suggestion
			<div aria-hidden="true"
				class="result-items__item-icon"
```

2023-11-21 12:40 UTC, susnux commented on core/src/components/GlobalSearch/SearchResult.vue
> +			thumbnailHasError: false,
Maybe we need a:
```js
watch: {
    thumbnailUrl() {
        this.thumbnailHasError = false
    }
}
```

Because if this component is recycled because of changing results and the thumbnail has an error, the new result will also show the thumbnail error.
If this happens depends on whether the component will be recycled by `GlobalSearchModal` or not (depending on the `key` value in the `v-for` look).

2023-11-21 13:27 UTC, susnux approved these changes

2023-11-21 14:26 UTC, merged