Added option to disable Edit Locally menu option
nextcloud/server pull request #41582
Opened 2023-11-17 17:05 UTC by Koc

* Resolves: -

## Summary
Many of our users has no installed software for edit file locally. This leads to struggling with mentioned menu option. For me this option also does nothing for any file format. So as an option - we can add a way to disable it completely.

by default:
![image](https://github.com/nextcloud/server/assets/191082/730d00ea-1aa4-4c6f-9d2b-72d0381853e0)

with option
```php
# config/config.php

<?php
$CONFIG = array (
  // ...
  'disable_edit_locally' => true,
);
```
![image](https://github.com/nextcloud/server/assets/191082/edccb934-cc11-4170-9c52-ab937700a4f1)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-17 19:40 UTC, Koc commented on apps/files/lib/Controller/ViewController.php
> +			'disableEditLocally' => $this->config->getSystemValueString('disable_edit_locally', 0),
fixed

2023-11-21 23:53 UTC, Koc commented
Test failures [looks unrelated](https://drone.nextcloud.com/nextcloud/server/44280/9/4)

2023-12-04 23:09 UTC, Koc commented
@blizzz @solracsf @AndyScherzinger hey mates, any chance to review this small PR? :pray:

2023-12-05 08:39 UTC, solracsf commented
`config.php` option should also be documented.

2023-12-05 17:41 UTC, Pytal requested changes
We should move away from PHP template params and use `provideInitialState` on backend + `loadState` from `@nextcloud/initial-state` on frontend

2023-12-07 17:12 UTC, Pytal commented on apps/files/src/actions/editLocallyAction.ts
> +let disableEditLocally = loadState('files', 'disable_edit_locally', false)
```suggestion
const disableEditLocally = loadState('files', 'disable_edit_locally', false)
```

2023-12-08 08:42 UTC, jancborchardt requested changes
Rather than having a switch to disable this altogether, wouldn’t the proper approach here be that the desktop client communicates if a relevant desktop app can be handled? And if the desktop client is not available or installed for the account, then we can disable the entry too (not sure if we already do this).

@tobiasKaminsky @mgallien is this possible?

I understand this is probably more complicated to code, but then there is 0 additional configuration.

2023-12-11 11:05 UTC, jancborchardt commented
> For me this option also does nothing for any file format.

@Koc not even for file formats where you have a handler installed, and you have the Nextcloud desktop client installed? This is a real issue we should fix then for everyone. Simply allowing some people to disable the feature altogether does not fix the original issue unfortunately. :)

2023-12-20 15:15 UTC, mgallien commented
> Rather than having a switch to disable this altogether, wouldn’t the proper approach here be that the desktop client communicates if a relevant desktop app can be handled? And if the desktop client is not available or installed for the account, then we can disable the entry too (not sure if we already do this).
> 
> @tobiasKaminsky @mgallien is this possible?
> 
> I understand this is probably more complicated to code, but then there is 0 additional configuration.

technically would require (as far as I understand) to have an extension in your browser (like [keepass integration](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/) or plasma desktop integration) that would be able to communicate with the desktop client (or other software) and check for their presence
feasible and we would know what to do but still a significant effort

2023-12-27 09:27 UTC, jancborchardt commented
@mgallien ok, no, requiring a browser extension would not be feasible. I thought we could know whether the browser currently in use and the desktop client are on the same system for example, as they are connected by the server.

Then @sorbaugh @AndyScherzinger cc regarding that off-switch for this feature, seems fine if it is only a config.php setting?

2024-08-03 16:43 UTC, closed without merging