fix(papercut) - rerendered submenu actions for time sensitive actions
nextcloud/server pull request #41670
Opened 2023-11-22 17:48 UTC by emoral435

* Resolves #41336

## Summary
Changes submenu loading to re-render the actions in the submenu, as the items could potentially be time dependent. As of now, the items within the submenu are only loaded when dependencies change, or upon initial loading of the page, but by loading it whenever the user clicked the button, they wont have to reload the page, saving them an extra click ✅

## BEFORE
![piM9LcEWjP](https://github.com/nextcloud/server/assets/110193237/3053e8b9-6bd3-4cfe-88ef-f896d95eb7ca)

## AFTER
![jFihBodbD6](https://github.com/nextcloud/server/assets/110193237/7f144336-4b82-42fe-a2e2-99e835447381)

## TODO

- [x] Since the presence of the action should be evaluated ideally on click instead of on script execution I think the FileAction enabled callback needs to be set to something like () => Boolean(getDateTime(option.dateTimePreset)) to be more reactive
- [x] Made it so that when an action within the dropdown changes the openedSubmenu dependency, reloads only the submenu action and doesn't change other computed dependencies, which would slow down the loading of the page

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-22 17:49 UTC, emoral435 commented
will compile assets once reviews look good!

2023-11-23 03:36 UTC, Pytal commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +import type { LogLevel } from '@nextcloud/logger'
```suggestion
```

2023-11-23 03:36 UTC, Pytal commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
>  		return null
```suggestion
```
This check should be removed

Now `getDateTime()` should be called and the returned Date used in the displayName, title, and exec methods instead

2023-11-27 23:52 UTC, emoral435 commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
>  		return null
I see what you mean, I am updating any area with the current dateTime variable with a call to getDateTime()

2023-11-28 01:43 UTC, susnux requested changes, later dismissed
Why is 3rdparty changed?

2023-11-28 01:48 UTC, Pytal approved these changes
Thanks! Just gotta remove 3rdparty changes 🙈

2023-11-28 15:20 UTC, emoral435 commented
/compile amend/

2023-11-29 23:45 UTC, emoral435 commented
/compile amend /

2023-11-30 01:22 UTC, Pytal commented
Let's squash these commits into one @emoral435 :)

2023-12-05 08:59 UTC, skjnldsv commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +		// same as enabledSubmenuActions computed function, but instead as a method to be able to
Really not sure about this, the implementation looks very unusual.
Why would only sub-menus allowed to auto refresh?

I think this is something that should be fixed in a different way maybe?
Have you tried returning a reference for the displayName and have that reference change? Is the menu not already updating as is? I think ""in theory"" having dynamic string updated on render should already work.
The issue is that we're returning a string from  `displayName` or `title` instead of a `reference` to a string, so vue doesn't see any change :thinking:

2023-12-05 18:33 UTC, emoral435 commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +		// same as enabledSubmenuActions computed function, but instead as a method to be able to
Yep, as of right now, I am trying to think of a clever way to have the submenu actions refresh so that time dependent actions are loaded depending on the time when the user clicked, and not when the page got loaded. 

I am trying to see ways around the caching such that we do not recompute too much so that the clients side does not slow down, so I will give what you said and other methods as well a shot

2023-12-06 08:21 UTC, skjnldsv reviewed
Please also remove the last `.filter(Boolean) as FileAction[]` then :)

2023-12-06 19:48 UTC, Pytal commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +		// same as enabledSubmenuActions computed function, but instead as a method to be able to
Seems to work so fine with me ⏲

2023-12-08 17:00 UTC, emoral435 commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +		// same as enabledSubmenuActions computed function, but instead as a method to be able to
I tried this out on my local dev, its fine with me as well! I like this solution, ties back to the original issue discussing how refreshing the submenu on every click may slow down performance :) submitting my pr changes right now

2023-12-09 02:27 UTC, emoral435 commented on apps/files_reminders/src/actions/setReminderSuggestionActions.ts
> +	+
Yep, embarrassed that got caught LOL, thank you!

2023-12-09 03:21 UTC, emoral435 commented
/compile /

2023-12-12 07:34 UTC, skjnldsv approved these changes

2023-12-12 07:34 UTC, merged

2023-12-12 07:35 UTC, skjnldsv commented
/backport to stable28