fix(files): Allow to drag and drop new files also on empty directories
nextcloud/server pull request #41693
Opened 2023-11-23 13:46 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/41534

## Summary
Move the drag and drop from the files table to the files list, to allow drag and drop upload in empty folders (where no table is shown but an empty content message).
Also unregister the drag and drop listeners on component destroy, which was causing errors like `this.$refs.table undefined`.

Cleanup not used styles from the drag and drop notice.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-23 13:52 UTC, susnux commented
/backport to stable28

2023-11-23 14:45 UTC, artonge requested changes, later dismissed

2023-11-23 14:45 UTC, artonge commented on apps/files/src/components/DragAndDropNotice.vue
> +export default defineComponent({
What's the difference?

2023-11-23 14:45 UTC, artonge commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
Let's keep extensions

2023-11-23 14:45 UTC, artonge commented on apps/files/src/components/FilesListVirtual.vue
> +import { action as sidebarAction } from '../actions/sidebarAction.js'
Those are not js files, right ?

2023-11-23 14:45 UTC, artonge commented on apps/files/src/views/FilesList.vue
> +import { action as sidebarAction } from '../actions/sidebarAction.js'
Same, are those really js files ?

2023-11-23 15:42 UTC, ShGKme commented on apps/files/src/components/DragAndDropNotice.vue
> +export default defineComponent({
`defineComponent` exists in both Vue 2 and Vue 3 => simpler migration in Nextcloud 29

(40 days left until Vue 2 End Of Life)

2023-11-23 16:08 UTC, susnux commented on apps/files/src/components/FilesListVirtual.vue
> +import { action as sidebarAction } from '../actions/sidebarAction.js'
No but Typescript does not allow to import `.ts` files, so you either can import Typescript without extensions or with `.js`.
See Typescript and ESLint errors otherwise

2023-11-23 16:08 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +import { action as sidebarAction } from '../actions/sidebarAction.js'
See above, `.ts` is invalid within Typescript files.

2023-11-23 17:06 UTC, Pytal commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
Could use https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions as webpack already resolves `.ts` files?

2023-11-23 19:04 UTC, artonge commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
I don't understand the logic behind forbidding .ts import 🤔 
Having extensions helps with readability, so if it is possible to keep them, let's keep them.
Having the wrong extension is even worth, so I would rather have no extension.

2023-11-23 19:11 UTC, susnux commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
> Could use https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions 

Yes but from Typescript this will not be allowed as stated in the docs of that flag:
> This flag is only allowed when --noEmit or --emitDeclarationOnly is enabled

Meaning Typescript itself only allows it for "declarations only"-Typescript code.

> I don't understand the logic behind forbidding .ts import 🤔

The logic is that Typescript does not change any imports, meaning importing `foo.ts` will write `foo.ts` to the output making it invalid. So Typescript internally maps files to the output extension [1]:
* `.ts` -> `.js`
* `.cts` -> `.cjs`
* `.mts` -> `.mjs`

When importing, Typescript uses that logic to map the `.js` import to the `.ts` source file.

I agree this makes not that much sense when using bundlers (there are a lot of comments about this on the Typescript project).

[1] https://www.typescriptlang.org/docs/handbook/modules/theory.html

2023-11-23 19:28 UTC, susnux commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
But I think we can use it if we adjust ESLint and out TS config. As we already using bundler, we can also set `emitDeclarationOnly`.

2023-11-23 19:43 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +import { action as sidebarAction } from '../actions/sidebarAction.js'
See above

2023-11-23 19:43 UTC, susnux commented on apps/files/src/components/FilesListVirtual.vue
> +import type { UserConfig } from '../types'
Done see 3rd commit

2023-11-23 22:46 UTC, Pytal approved these changes

2023-11-23 23:50 UTC, AndyScherzinger approved these changes

2023-11-27 11:25 UTC, artonge commented on apps/files/tsconfig.json
Is it necessary to have a custom config for files?

2023-11-27 13:52 UTC, susnux commented on apps/files/tsconfig.json
Yes as other apps might not use Typescript in Vue files. If we do this globally Typescript would complain for JS only Vue files.

2023-11-27 13:58 UTC, susnux commented on apps/files/tsconfig.json
(but I tested right now and at least with current Volar it works even with the global config, so I can move it if you like @artonge )

2023-11-27 14:04 UTC, artonge commented on apps/files/tsconfig.json
That would be better, the less custom config we have, the easier it is to understand what's up :)

2023-11-27 14:29 UTC, artonge approved these changes

2023-11-27 18:06 UTC, merged

2023-12-01 23:20 UTC, susnux commented
/backport to stable28