Improve personal settings layout
nextcloud/server pull request #41718
Opened 2023-11-24 03:05 UTC by marcoambrosini

* Resolves: # 

## Summary
One column layout regardless of the width, like in other settings sections. Currently, it's centered, but it can also be moved to the left like in other sections. I just thought it looked better centered.
I think that this is a massive improvement in clarity and usability of this page, and a very low-hanging fruit too.

**Before**

[Screencast from 2023-11-24 10-45-10.webm](https://github.com/nextcloud/server/assets/26852655/cf17fa95-20d9-476b-8f39-00eb7f732d99)

**After**

[Screencast from 2023-11-24 11-58-26.webm](https://github.com/nextcloud/server/assets/26852655/354af987-9589-4834-9851-d3c4eaf5105c)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-24 03:11 UTC, marcoambrosini commented
/compile amend /

2023-11-28 17:07 UTC, szaimen submitted a review, later dismissed
I like it and looks good from the screenrecording 👍
But didnt test

2023-12-04 11:39 UTC, jancborchardt commented
This seems a bit extreme towards the other side, no? The information density is very low and the input fields / selects are uncharacteristically wide.

It would make sense to have a 2-column interface, with avatar, profile and groups in the left column (like now) and all the input field things in the right column. That would be more condensed while at the same time not strangely wide.

(Another issue with the layout or rather the UX is this whole "Profile visibility" section on the bottom which basically duplicates all the fields above. It would be great if we can combine that as well – but should be a separate concern of course.)

2023-12-04 11:39 UTC, jancborchardt requested changes, later dismissed
This seems a bit extreme towards the other side, no? The information density is very low and the input fields / selects are uncharacteristically wide.

It would make sense to have a 2-column interface, with avatar, profile and groups in the left column (like now) and all the input field things in the right column. That would be more condensed while at the same time not strangely wide.

(Another issue with the layout or rather the UX is this whole "Profile visibility" section on the bottom which basically duplicates all the fields above. It would be great if we can combine that as well – but should be a separate concern of course.)

2023-12-11 03:38 UTC, marcoambrosini commented
@jancborchardt how would the left column behave on scroll? 

If the concern is the width of the input, we can narrow the columns. Most other settings pages are one column too.

2023-12-18 05:25 UTC, marcoambrosini commented
I like the idea of having everything in one line, but I think that since this already improves things a lot, we should merge and then iterate. We can arbitrarily reduce the width as we see fit without having to justify the empty space as long as the layout improves the user experience.

Ref: google settings
![Group 1](https://github.com/nextcloud/server/assets/26852655/4dc4351d-ec41-421a-b02e-b72dbeabc7e7)

2023-12-18 12:41 UTC, jancborchardt commented
> I think that since this already improves things a lot, we should merge and then iterate over the actual design.

@marcoambrosini I disagree on this – as said this goes too far in the other extreme direction. 2 columns would be the proper fix.

> how would the left column behave on scroll?

It can just scroll up and out of view, no need for stickyness there for now.

@nimishavijay nice on the mockup indeed! Great also since this is the start of a new cycle, this could go in as an immediate follow-up for this.

2023-12-19 02:05 UTC, marcoambrosini commented
@jan do you mean like this?  I think it's worse than 1 column, especially given that when we scrolled down it's still 1 column, just awkwardly placed on the screen.
 
[Screencast from 2023-12-19 10-59-57.webm](https://github.com/nextcloud/server/assets/26852655/6de2887c-79cc-4050-8383-7d14c42b489e)

2023-12-19 09:59 UTC, marcoambrosini commented
--> invert and align to the left

2023-12-21 13:05 UTC, jancborchardt commented
@marcoambrosini another point: "Language" and "Locale" can move to the other column as they are personal (more like group memberships and quota usage) and don’t really fit with the others which are profile fields.

2024-03-11 16:20 UTC, marcoambrosini commented
/compile

2024-03-11 16:23 UTC, marcoambrosini commented
/compile

2024-03-12 07:33 UTC, marcoambrosini commented
@Fenn-CS it needs to scroll because with everything we added it's unlikely to fit in the height of the screen. The profile picture is on the right because otherwise when that column is scrolled away, the other column would be in an odd position: not at the center of the screen and not left aligned either.

2024-03-18 12:02 UTC, szaimen commented
Great, looks much better layout-wise :)
Though I wonder is it expected that each section has a different width and aligning now?
See 
![localhost_8443_index php_settings_user (3)](https://github.com/nextcloud/server/assets/42591237/07e7e990-5613-4738-b90f-f1bd4cb88f84)

2025-09-04 08:37 UTC, jancborchardt reviewed
@marcoambrosini @kra-mo this seems to be a nice thing to update once the forms/settings style improvements are in btw: https://github.com/nextcloud-libraries/nextcloud-vue/issues/7124

2026-03-24 10:37 UTC, jancborchardt commented
Closing this as duplicate of or rather being superseded by https://github.com/nextcloud/server/issues/57008 as we meanwhile also have new components. (Just FYI @marcoambrosini)

2026-03-24 10:37 UTC, closed without merging