Fix/handle-duplicate-reminder
nextcloud/server pull request #41740
Opened 2023-11-24 16:47 UTC by hamza221

* Resolves: #41695

## Summary

## 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-11-27 13:16 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +			->groupBy('cr.notification_date', 'cr.event_hash');
should it be the other way around? would it be possible to have a collision of notification date by two independent events of two or more users?

you will have to add all projected columns into the group clause because you are not allowed to have them in the SELECT otherwise, at least for strict databases: https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html.

2023-11-27 15:44 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +				$uniqueReminders[] = $reminder;
Can't you just use a keyed array for `$uniqueReminders` instead of having an extra `$seen` array, and use `array_values` in the `foreach`?

2023-12-13 15:34 UTC, hamza221 commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +			->groupBy('cr.notification_date', 'cr.event_hash');
AFAIK there should be one db entry for each recurrence independently from users . 

> would it be possible to have a collision of notification date by two independent events of two or more users?

we're grouping by`'cr.event_hash'` so it shouldn't affect independent events as far as I understand, no?

2024-04-09 15:20 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +			->groupBy('cr.notification_date', 'cr.event_hash');
I think @ChristophWurst was just suggesting to group by `cr.event_hash`, then per `cr.notification_date`, which makes more sense to me as well.

2024-04-09 18:37 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +			->groupBy('cr.notification_date', 'cr.event_hash');
```suggestion
			->groupBy('cr.event_hash', 'cr.notification_date');
```

Yep. If the hash and the date is equal we fully deduplicate.
If the hash differs but the date is equal we leave the duplicates.

2024-04-10 05:44 UTC, tcitworld reviewed
Code looks good, tests says no

2024-04-10 07:21 UTC, tcitworld requested changes
We need the type as well.

2024-04-10 07:21 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/ReminderService.php
> +			$key = $reminder['notification_date']. $reminder['event_hash'];
As you can see in the test change you made, the key should also contain the `$reminder['type']`, as you can have two reminder of different types on the same date for the same event.

2024-04-10 07:21 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri','cr.notification_date', 'cr.event_hash'])
```suggestion
		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri','cr.notification_date', 'cr.event_hash', 'cr.type'])
```

2024-04-10 07:21 UTC, tcitworld commented on apps/dav/lib/CalDAV/Reminder/Backend.php
> +			->groupBy('cr.event_hash', 'cr.notification_date');
```suggestion
			->groupBy('cr.event_hash', 'cr.notification_date', 'cr.type');
```

2024-04-10 07:21 UTC, tcitworld commented on apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php
> -		$this->assertCount(2, $rows);
Adding the reminder type should allow you to revert these changes.

2024-04-16 10:31 UTC, ChristophWurst commented
@szaimen wrong button?

2024-04-16 11:04 UTC, szaimen commented
> @szaimen wrong button?

Apparently. Sorry, not sure how this happened

2024-08-01 15:43 UTC, tcitworld approved these changes
Just cs issues

2024-08-01 15:43 UTC, tcitworld commented on apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php
> +
white space :eyes:

2024-08-01 15:43 UTC, tcitworld commented on apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php
> -
bye bye new line :cry:

2024-08-12 17:01 UTC, ChristophWurst approved these changes

2024-08-13 10:33 UTC, merged