ILazyConfig
nextcloud/server pull request #41755
Opened 2023-11-26 19:25 UTC by ArtificialOwl

2023-11-28 09:47 UTC, come-nc commented on lib/private/LazyConfig.php
> +		$result = $qb->execute();
```suggestion
		$result = $qb->executeQuery();
```

2023-11-28 10:13 UTC, come-nc commented on core/Migrations/Version29000Date20231126110901.php
> +		return $schema;
```suggestion
		if (!$schema->hasTable('appconfig_lazy')) {
			$table = $schema->createTable('appconfig_lazy');
			$table->addColumn('app_id', Types::STRING, ['length' => 32]);
			$table->addColumn('extra', Types::STRING, ['length' => 32]);
			$table->addColumn('config_key', Types::STRING, ['length' => 64]);
			$table->addColumn('config_value', Types::TEXT);

			$table->setPrimaryKey(['app_id', 'config_key'], 'lazy_app_prim');
			$table->addIndex(['app_id', 'extra'], 'lazy_app_id_i');
			$table->addIndex(['app_id', 'extra', 'config_key'], 'lazy_app_id_key_i');
			return $schema;
		}

		return null;
```

2023-12-07 13:08 UTC, nickvergessen commented on core/Migrations/Version29000Date20231126110901.php
> +		$table->addColumn('sensitive', Types::SMALLINT, ['length' => 1, 'notnull' => true, 'default' => '0']);
```suggestion
		$table->addColumn('lazy_group', Types::STRING, ['length' => 32, 'notnull' => false, 'default' => '']);
		$table->addColumn('sensitive', Types::SMALLINT, ['length' => 1, 'notnull' => true, 'default' => 0]);
```

2023-12-08 06:55 UTC, nickvergessen requested changes
Really not a fan of the caching strategy.
It sounds really risky to get database and cache out of sync easily with a long running task in OCC or request, etc.

As per chat however I like the general idea of having a lazy "block" and even more integrating the sensitive part directly.

Speaking of sensitive some apps use the `ICrypto::encrypt()` and `ICrypto::dectrypt()`. We could include that into the methods and help developers again to not have security optionally?

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IConfig.php
> +	 * @deprecated - load IAppConfig directly
```suggestion
	 * @deprecated 29.0.0 Use {@see IAppConfig} directly
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @see self::getAllValues()
```suggestion
	 * @deprecated 29.0.0 Use {@see getAllValues()}
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @deprecated use getAllValues()
```suggestion
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @deprecated use getAllValues()
```suggestion
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @see self::getAllValues()
```suggestion
	 * @deprecated 29.0.0 Use {@see getAllValues()}
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> -	public function getApps();
Can not break public API, needs to be deprecated for 3 years.

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * For debug purpose.
Is this meant to be used by apps? I guess no?
I would not put it into the public API

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function unsetKey(string $app, string $key): void;
Let's stay with delete as name?!

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function unsetAppKeys(string $app): void;
Let's stay with delete as name?!

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueString(string $app, string $key, string $value, bool $lazy = false, ?bool $sensitive = null): bool;
New method, let's force developers to do it properly.
Sensitive can not really have 3 states. Either it is sensitive or not.

```suggestion
	public function setValueString(string $app, string $key, string $value, bool $lazy = false, bool $sensitive = false): bool;
```

I would even argue that security should not be optional and neither should be the sensitive flag?

```suggestion
	public function setValueString(string $app, string $key, string $value, bool $sensitive, bool $lazy = false): bool;
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueInt(string $app, string $key, int $value, bool $lazy = false, ?bool $sensitive = null): bool;
See comment on setValueString

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueFloat(string $app, string $key, float $value, bool $lazy = false, ?bool $sensitive = null): bool;
See comment on setValueString

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueBool(string $app, string $key, bool $value, bool $lazy = false, ?bool $sensitive = null): bool;
See comment on setValueString

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueBool(string $app, string $key, bool $value, bool $lazy = false, ?bool $sensitive = null): bool;
That being said, can a boolean be sensitive?

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function setValueArray(string $app, string $key, array $value, bool $lazy = false, ?bool $sensitive = null): bool;
See comment on setValueString

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @param string $lazy name of the lazy group
```suggestion
	 * @param bool $lazy set config as lazy loaded
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 */
```suggestion
```

Each method needs to indicate this anyway

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * If config key belongs to a lazy group, the name of the lazy group needs to be specified.
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * If config key belongs to a lazy group, the name of the lazy group needs to be specified.
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * If config key belongs to a lazy group, the name of the lazy group needs to be specified.
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * If config key belongs to a lazy group, the name of the lazy group needs to be specified.
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * If config key belongs to a lazy group, the name of the lazy group needs to be specified.
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> + * **Note:** Lazy group are not linked to app ids. Multiple app can share the same
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/public/IAppConfig.php
> + * Each group, called _lazy group_, is only loaded in memory when one its config
Lazy is not a string/name anymore

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +		($lazy) ? $cache = &$this->lazyCache : $cache = &$this->fastCache;
Inline assignment of hell 🙈 
You even need to silence psalm for it …

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +		($lazy) ? $cache = &$this->lazyCache : $cache = &$this->fastCache;
Also here

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +		/** @psalm-suppress UndefinedVariable */
Instead of surpressing, fix the code and do it properly:
```suggestion
		if ($lazy) {
			$cache = &$this->lazyCache;
		} else {
			$cache = &$this->fastCache;
		}
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$this->getValueString($app, $key, $default ? 'true' : 'false'), ['1', 'true', 'yes', 'on'], $lazy
```suggestion
			$this->getValueString($app, $key, $default ? 'true' : 'false', $lazy), ['1', 'true', 'yes', 'on']
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			return (is_array($value)) ? $value : [$value];
Clean code in new methods is better then allowing bad patterns from the start:
```suggestion
			return is_array($value) ? $value : [];
```

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$lazy ? $this->lazyLoaded = true : $this->fastLoaded = true;
no inline assignments

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +	 * @param bool $lazy search within lazy config (since 29.0.0)
Add as `@since` tag?

2023-12-08 06:55 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$this->storeDistributedCache();
The data in your cache can be really old,
could be multiple minutes if this is done at the last jobs of a cron run, and you would then store previous old appconfigs again.

2023-12-08 09:26 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +		/** @psalm-suppress UndefinedVariable */
i'll do that, but I am more inclined to think that this is an issue with psalm, not my code :-]

2023-12-08 09:32 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			$this->storeDistributedCache();
should we compare the local/internal cached value with the one in database when doing operation like update/delete ? or store a random string/token in database to implement some versioning ?

2023-12-08 09:47 UTC, ArtificialOwl commented on lib/public/IAppConfig.php
> +	public function unsetKey(string $app, string $key): void;
I am okay as long as we know for sure that replacing the `deleteKey()` and `deleteApp()` wont break anything

2023-12-08 09:47 UTC, ArtificialOwl commented on lib/public/IAppConfig.php
> +	 * For debug purpose.
i am fine with public(), Circles needs it

2023-12-08 10:49 UTC, nickvergessen commented on lib/private/AppConfig.php
> +	 * @param bool $lazy search within lazy config (since 29.0.0)
Multiple sinces are allowed

2023-12-15 05:28 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			);
```suggestion
			$value = json_decode(
				$this->getValueString($app, $key, $defaultJson, $lazy), true, 512, JSON_THROW_ON_ERROR
			);
```

or

```suggestion
			$value = json_decode(
				$this->getValueString($app, $key, $defaultJson, $lazy), true, flags: JSON_THROW_ON_ERROR
			);
```

2023-12-15 05:42 UTC, nickvergessen reviewed
We should add a type option to `occ config:app:set` similar to `occ config:system:set`, so you can change an app config and retain the type info.

2023-12-15 05:42 UTC, nickvergessen commented on lib/private/AppConfig.php
>  		}
```suggestion
		} catch (JsonException $e) {
			$this->logger->error(
				'could not setValueArray', ['app' => $app, 'key' => $key, 'exception' => $e]
			);
			throw $e;
		}
```

This is too important. It basically means the function did not operate at all. This should not go silent. App authors need to change their code immediately, so this should log as error and throw hard.

2023-12-15 05:42 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			throw new AppConfigIncorrectTypeException('conflict with value type from database');
Let's log this as an error (because it again means app authors need to do something, or administrators manipulated data wrongly) with the information which key was expected which type and what type it actually was

2023-12-15 05:42 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			);
```suggestion
			$value = json_decode(
				$this->getValueString($app, $key, $defaultJson, $lazy), true, 512, JSON_THROW_ON_ERROR
			);
```

or

```suggestion
			$value = json_decode(
				$this->getValueString($app, $key, $defaultJson, $lazy), true, flags: JSON_THROW_ON_ERROR
			);
```

2023-12-18 07:28 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			);
nice catch

2023-12-18 07:30 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			throw new AppConfigIncorrectTypeException('conflict with value type from database');
@nickvergessen we keep the exception, or no exception thrown ?

2023-12-18 07:33 UTC, ArtificialOwl commented
> We should add a type option to `occ config:app:set` similar to `occ config:system:set`, so you can change an app config and retain the type info.

in this PR ?

2023-12-18 08:07 UTC, ArtificialOwl commented
anyone willing to confirm the fail test 

```
--

There was 1 failure:

1) Test\DB\QueryBuilder\FunctionBuilderTest::testConcatString with data set "2 columns: string real and int literal" (Closure Object (...))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'12'
+'22'

/home/runner/work/server/server/tests/lib/DB/QueryBuilder/FunctionBuilderTest.php:62
```
as it is working locally

2024-01-02 13:37 UTC, icewind1991 commented
Not a fan of using bitflags for the type and sensitive flags. Rather just have a separate bool for the sensitive flag and int/enum for the type.

2024-01-04 22:44 UTC, ArtificialOwl commented
> Not a fan of using bitflags for the type and sensitive flags. Rather just have a separate bool for the sensitive flag and int/enum for the type.

Might not be the best but I really wanted to keep it as less invasive as possible in database. 
This is readonly (no index/search will be done on the value itself), and might allow us to add small other boolean bitflag in the future without creating a new field to the table

2024-01-08 16:23 UTC, come-nc commented on lib/private/SystemConfig.php
> +	public function __construct(private Config $config) {
```suggestion
	public function __construct(
		private Config $config,
	) {
```

2024-01-08 16:23 UTC, come-nc commented on lib/public/IAppConfig.php
> +	 * **WARNING:** ignore lazy filtering
Not clear, does that means lazy keys are always returned or never, or something else?

2024-01-08 16:23 UTC, come-nc commented on lib/public/IAppConfig.php
> +	 * @since 7.0.0
`@since` should be 29.0.0 for all new functions on this interface

2024-01-08 16:23 UTC, come-nc commented on lib/public/IAppConfig.php
> +	 * For debug purpose.
circles need it for debug or normal usage?

2024-01-09 10:28 UTC, come-nc commented on lib/private/AppConfig.php
> +	): int {
```suggestion
	): int|float {
```
If you want bigint support on 32bit

2024-01-09 10:28 UTC, come-nc commented on lib/private/AppConfig.php
> +		}
```suggestion
		return match (strtolower($type)) {
			'mixed' => IAppConfig::VALUE_MIXED,
			'string' => IAppConfig::VALUE_STRING,
			'integer' => IAppConfig::VALUE_INT,
			'float' => IAppConfig::VALUE_FLOAT,
			'boolean' => IAppConfig::VALUE_BOOL,
			'array' => IAppConfig::VALUE_ARRAY,
			default => throw new AppConfigIncorrectTypeException('Unknown type ' . $type),
		};
```
Same thing but simpler no?

2024-01-09 10:28 UTC, come-nc commented on lib/private/AppConfig.php
> +		return (($needle & $type) !== 0);
```suggestion
		return (($needle & $type) === $needle);
```
This would support testing several flags at the same time I think

2024-01-11 14:10 UTC, come-nc commented on lib/private/AppConfig.php
> +		return $apps;
No https://www.php.net/manual/en/function.array-merge.php

2024-01-11 15:30 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +		return (($needle & $type) !== 0);
no needed

2024-01-11 16:49 UTC, come-nc approved these changes

2024-01-11 16:52 UTC, artonge approved these changes

2024-01-12 09:11 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$this->logger->warning('type stored in database is not correct', ['exception' => $e, 'type' => $type]);
This spams `Unknown numeric type 0` very heavily for me.

2024-01-12 09:11 UTC, nickvergessen commented on lib/public/IAppConfig.php
> + * @since 29.0.0 supports lazy loading
this differs from the actual implementation. Use either and make sure it doesn't mention the lazy groups :P

2024-01-12 09:11 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public const VALUE_ARRAY = 64;
please add the `@since`

2024-01-12 09:11 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	public function getValueBigInt(string $app, string $key, int|float $default = 0, bool $lazy = false): int|float;
Still not sure when this should be used, also the docs don't help to decide.
When I store e.g. a "file id" which could be BIGINT on DB level, should I use this, or MUST I use this?

2024-01-12 09:11 UTC, nickvergessen commented on lib/public/IAppConfig.php
> +	 * @see getValueArray()
I would remove all those duplicate references, just "bloats" the doc block from my pov.
```suggestion
```

2024-01-12 09:15 UTC, nickvergessen commented
❌ Drone failures are related!

2024-01-12 19:31 UTC, ArtificialOwl commented on lib/public/IAppConfig.php
> +	public function getValueBigInt(string $app, string $key, int|float $default = 0, bool $lazy = false): int|float;
`setValueBigInt`/`getValueBigInt` is supposed to help supports huge integer above 2,147,483,647 (on 32bits) or 9,223,372,036,854,775,807, as php converts them to float (mostly for 32 bits support ;p)



if I comment this exception
https://github.com/nextcloud/server/pull/41755/files#diff-3921e92ccf03a5dc1400f57821a7bc829b242e7691ff1991cda3a3c431fabc6aR201-R203

This is the behavior:
```
$ ./occ config:app:set toto1 toto2 --value 9223372036854775808 --type integer
Config value 'toto2' for app 'toto1' is now set to '9223372036854775807', stored as integer in fast cache
```

As you can see, the `int` value is cap, using an int|float would avoid this by switching to float (only) when needed.
The other solution would be to type `setValueInt()`/`getValueInt()` with `float|int`, but it also means that value is not `int` at 100% and I don't think we want this.

This is currently not implemented, but if we allow the use of bigint type in the occ command, this would be the behavior
```
$ ./occ config:app:set toto1 toto2 --value 9223372036854775808 --type bigint
Config value 'toto2' for app 'toto1' is now set to '9.2233720368548E+18', stored as integer in fast cache
$ ./occ config:app:set toto1 toto2 --value 9223372036854775807 --type integer
Config value 'toto2' for app 'toto1' is now set to '9223372036854775807', stored as integer in fast cache
```

2024-01-15 11:21 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			$this->logger->warning('type stored in database is not correct', ['exception' => $e, 'type' => $type]);
I am interested how you came to this as type should not be 0 in database

2024-01-15 11:54 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$this->logger->warning('type stored in database is not correct', ['exception' => $e, 'type' => $type]);
Mostlikely from `occ config:app:set -vvv ${dir##*/} enabled --value="no"` which I have in my set up script to force disable all apps as an option.
The point is more that there will be a lot of "dirty" instances already out there and spaming their logs with warnings when the admin can not know what to do about it is meh.

2024-01-15 15:12 UTC, nickvergessen reviewed
Okay otherwise

2024-01-15 15:12 UTC, nickvergessen commented on lib/private/AppConfig.php
> +			$this->logger->debug('You are trying to store an integer value around/above 2,147,483,647. This is a reminder that reaching this theoretical limit on 32 bits system will result to an exception.');
```suggestion
			$this->logger->debug('You are trying to store an integer value around/above 2,147,483,647. This is a reminder that reaching this theoretical limit on 32 bits system will throw an exception.');
```

2024-01-15 15:12 UTC, nickvergessen commented on core/Command/Config/App/SetConfig.php
> +					$updated = $this->appConfig->updateType($appName, $configName, $type);
> Argument 3 of OC\AppConfig::updateType cannot be null, possibly null value provided

2024-01-15 15:37 UTC, ArtificialOwl commented on lib/public/IAppConfig.php
> +	public function getValueBigInt(string $app, string $key, int|float $default = 0, bool $lazy = false): int|float;
fixed by removing `setValueBigInt`/`getValueBigInt`. Also, using setValueInt() with huge integer value, close to the 32bits limit will generate a debug log entry.

2024-01-15 15:37 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			$cache = &$this->fastCache;
fixed in all places

2024-01-15 22:31 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +			$this->logger->warning('type stored in database is not correct', ['exception' => $e, 'type' => $type]);
I cannot reproduce this issue and will merge as it is right now.
By default, `occ config:app:set` set value as mixed. 

The only issue that I am seeing when using the `occ config:app:set` is that during the upgrading process, between the files are changed and the upgrade process is run.

Maybe we can edit the database (adding type+lazy field) already in 28 so we don't have error about missing field during the upgrade steps

2024-01-16 09:36 UTC, nickvergessen approved these changes
At least needs an issue in the guests app to make them aware of the breakage that is coming their way:
https://github.com/nextcloud/guests/blob/master/lib/AppConfigOverwrite.php

2024-01-16 09:39 UTC, merged

2024-01-25 07:58 UTC, juliushaertl commented
Just noticed we also have two different IAppConfig classes (one generic and one as a app framework service). The app framework service should probably also get adapted to cover the new API as currently it is just a wrapper for the deprecated methods: https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/AppFramework/Services/IAppConfig.php

2024-01-25 08:49 UTC, nickvergessen commented
Should we just deprecate it? we shouldn't have 2 similar interfaces like this?

2024-01-25 08:55 UTC, juliushaertl commented
I still like the service approach to simplify and not need to pass in the app id which makes the api a bit easier for app developers and and more restrictive to not mess with other apps configs

2024-01-25 09:03 UTC, nickvergessen commented
Ah, missed that bit. It's basically what I abstracted away in talk by using my own config class :D

2024-03-11 09:38 UTC, ChristophWurst commented on core/Command/Config/App/SetConfig.php
> +			)
This would be important for https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#setting-a-single-configuration-value. @ArtificialOwl @sorbaugh please document this soon :pray:

2024-09-23 13:17 UTC, joshtrichards commented on core/Command/Config/App/SetConfig.php
> +			)
Array handling still needs to be documented. Particularly since it's diverged from `system`: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#setting-an-array-configuration-value