Add reference to issue template app
nextcloud/server pull request #4189
Opened 2017-04-02 20:14 UTC by LukasReschke

@jospoortvliet Thoughts? We talked about that in the S-Bahn in Stuttgart on Friday :-)

If okay I'll merge this also on other repositories. But make sure the text is fine first :)

2017-04-02 20:20 UTC, MariusBluem requested changes
See my comment ... Rest seems to be fine 👍

2017-04-02 20:20 UTC, MariusBluem commented on issue_template.md
> +Make sure to remove all sensitive contents such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
*content* is uncountable. 😁

2017-04-03 10:11 UTC, jospoortvliet approved these changes

2017-04-03 10:12 UTC, merged

2017-04-03 10:26 UTC, jospoortvliet commented
TODO: port to the other repo's. Will work on that later today.

2017-04-05 08:09 UTC, nickvergessen commented
@jospoortvliet @MariusBluem please help review these:

### Updated issue_template.md
https://github.com/nextcloud/survey_client/pull/56
https://github.com/nextcloud/spreed/pull/280
https://github.com/nextcloud/quota_warning/pull/3
https://github.com/nextcloud/nextcloud_announcements/pull/23
https://github.com/nextcloud/files_downloadactivity/pull/14
https://github.com/nextcloud/files_automatedtagging/pull/26
https://github.com/nextcloud/files_accesscontrol/pull/60
https://github.com/nextcloud/announcementcenter/pull/80
https://github.com/nextcloud/activity/pull/134
https://github.com/nextcloud/notifications/pull/73

### New issue_template.md + contributing.md
https://github.com/nextcloud/external/pull/15
https://github.com/nextcloud/files_pdfviewer/pull/27
https://github.com/nextcloud/files_retention/pull/24
https://github.com/nextcloud/files_texteditor/pull/34
https://github.com/nextcloud/firstrunwizard/pull/38
https://github.com/nextcloud/logreader/pull/47
https://github.com/nextcloud/password_policy/pull/39
https://github.com/nextcloud/serverinfo/pull/87
https://github.com/nextcloud/templateeditor/pull/19
https://github.com/nextcloud/user_saml/pull/108

2017-04-05 08:22 UTC, jospoortvliet commented
All reviewed and merged. I pronounce this action DONE ;-)