fix(dav): Make current ooo info time-dependent
nextcloud/server pull request #41962
Opened 2023-12-01 09:53 UTC by ChristophWurst

* Helps resolve https://github.com/nextcloud/spreed/issues/11059

## Summary

* If there is an out of office absence info and it happens now -> return data
* Else: return no data

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-12-01 09:56 UTC, nickvergessen requested changes
This will break the option for clients or potential admin features in the feature to show OOO in the form, etc.

Please let's not do this 🙈 
We should check the applicable time in talk, it's on the way.

2023-12-01 10:04 UTC, nickvergessen commented on apps/dav/lib/Controller/OutOfOfficeController.php
>  	public function getCurrentOutOfOfficeData(string $userId): DataResponse {
I'm fine with that change, but we should always return the data on the API so it can be used for multiple use cases (like settings + showing in chat, etc).

2023-12-01 10:14 UTC, ChristophWurst commented
OOF. But the endpoint was specifically designed to only return data if it's currently active.

Do we need two endpoints?

2023-12-01 10:23 UTC, Antreesy approved these changes
Tested, works as expected, returning 404, if OoO is not in the effect yet (or expired)

Also wanted to ask about second endpoint. I understand that it might be useful for clients to get that data beforehand, but that's not the general case, I'd say

2023-12-01 10:24 UTC, ChristophWurst commented
> I would say no, a simple date check on the returned date easily tells if it's applicable or not?

No, it's not, because you don't know the timezone of the other user.

Pushed another version. The old endpoint to get the absence data independent of time is back. In addition there is a timezone-aware endpoint that only returns data if the absence happens right now.

2023-12-01 10:25 UTC, nickvergessen commented on apps/dav/appinfo/routes.php
> +		['name' => 'out_of_office#getOutOfOffice', 'url' => '/api/v1/outOfOffice/{userId}', 'verb' => 'GET'],
requires openapi.json update `bash build/openapi-checker.sh` (or something alike)

2023-12-01 10:49 UTC, ChristophWurst commented
API changed another time for the new return type. Please let me know if it's usable.

2023-12-01 10:51 UTC, provokateurin approved these changes
OpenAPI looks good

2023-12-01 11:00 UTC, nickvergessen commented on lib/public/User/IOutOfOfficeData.php
> +	 *  }
This needs to go to ResponseDefinitions.php and then be used as type in the annotation

2023-12-01 11:07 UTC, ChristophWurst commented on lib/public/User/IOutOfOfficeData.php
> +	 *  }
This doesn't feel right. Then the public API is based on private API, no? I'm trying to get the definitions into this interface, then use them from the controller.

2023-12-01 11:27 UTC, nickvergessen commented on apps/dav/lib/Controller/OutOfOfficeController.php
> +	 * @return DataResponse<Http::STATUS_OK, OutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
It's reading the ResponseDefinitions.php and not actually eating/evaluating PHP code.

So temporary fix duplicate the data format to ResponseDefinitions.php

2023-12-01 11:28 UTC, nickvergessen commented on lib/public/User/IOutOfOfficeData.php
> +	 *  }
> Then the public API is based on private API, no?

Right, should duplicate in that case.

2023-12-01 11:41 UTC, ChristophWurst commented on apps/dav/lib/Controller/OutOfOfficeController.php
> +	 * @return DataResponse<Http::STATUS_OK, OutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
oof

2023-12-01 11:47 UTC, ChristophWurst commented
/backport to stable28

2023-12-01 11:47 UTC, ChristophWurst commented on apps/dav/lib/Controller/OutOfOfficeController.php
>  	public function getCurrentOutOfOfficeData(string $userId): DataResponse {
Included in the latest push

2023-12-01 12:14 UTC, provokateurin commented on apps/dav/lib/ResponseDefinitions.php
> + * @psalm-type DAVOutOfOfficeData2 = array{
I'd prefer if they extend a common type alias. Also, why are there two definitions that seem very similar?

2023-12-01 12:19 UTC, ChristophWurst commented on apps/dav/lib/ResponseDefinitions.php
> + * @psalm-type DAVOutOfOfficeData2 = array{
Because of https://github.com/nextcloud/server/pull/41962#pullrequestreview-1759433208

2023-12-01 12:24 UTC, ChristophWurst commented on apps/dav/lib/ResponseDefinitions.php
> + * @psalm-type DAVOutOfOfficeData2 = array{
What is a common type alias?

2023-12-01 12:43 UTC, ChristophWurst commented on apps/dav/lib/ResponseDefinitions.php
> + * @psalm-type DAVOutOfOfficeData2 = array{
Done

2023-12-01 12:57 UTC, provokateurin commented on apps/dav/lib/ResponseDefinitions.php
>   * }
I have no idea how the backend works, but is there no way to align these a bit more? Why is the ID an int for one endpoint and a string for another? `status` and `shortMessage` also sound similar, are they different things?

2023-12-01 12:57 UTC, nickvergessen approved these changes

2023-12-01 12:59 UTC, provokateurin commented on apps/dav/lib/ResponseDefinitions.php
> + * @psalm-type DAVOutOfOfficeData2 = DAVOutOfOfficeDataCommon&array{
Ok @nickvergessen already said it as well https://github.com/nextcloud/server/pull/41962#discussion_r1412073831

2023-12-01 15:41 UTC, ChristophWurst commented on apps/dav/lib/ResponseDefinitions.php
>   * }
I agree but we are in RC3 and I don't want to cause explosions right now.

2023-12-01 15:46 UTC, provokateurin commented on apps/dav/lib/ResponseDefinitions.php
>   * }
maybe a simple cast to int here is ok for now and it can be fixed later.

2023-12-01 15:50 UTC, ChristophWurst commented on apps/dav/lib/ResponseDefinitions.php
>   * }
maybe it's ok, maybe it's not. that is the risk I don't want to take at this stage

2023-12-01 15:51 UTC, provokateurin commented on apps/dav/lib/ResponseDefinitions.php
>   * }
Ok then keep it :woman_shrugging:

2023-12-04 18:59 UTC, ChristophWurst commented on apps/dav/lib/Controller/OutOfOfficeController.php
> +	 * @return DataResponse<Http::STATUS_OK, DAVCurentOutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
it's called *consistency*

2023-12-04 19:25 UTC, nickvergessen commented
OpenAPI needs rebuild 🙈

2023-12-05 09:49 UTC, ChristophWurst commented
CI is happy now. @nickvergessen are you, too?

2023-12-05 09:50 UTC, nickvergessen approved these changes

2023-12-05 09:52 UTC, merged