Draft: Add UserConfigChangedEvent
nextcloud/server pull request #42039
Opened 2023-12-05 15:59 UTC by akhil1508

- For https://github.com/nextcloud/server/issues/41938

2023-12-05 16:02 UTC, akhil1508 commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
Cannot use DI for this as it is used in `base.php` over [here](https://github.com/nextcloud/server/blob/fd06f0c72de958855d535230b79583b30b9763b1/lib/base.php#L168)

2024-09-16 12:59 UTC, skjnldsv commented
Hey @akhil1508 
Thanks for the rebase! Let me ask for reviews, and see how we can help you move thi sforward :+1:

2024-09-16 15:45 UTC, come-nc commented on lib/composer/composer/autoload_static.php
> +        'OCP\\' =>
I guess you opened and save the file with an editor which removed trailing spaces, no? Please make sure the file in git matches the result of composer install --no-dev

2024-09-16 15:45 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> +	 * @since 30.0.0
```suggestion
	 * @since 31.0.0
```
You have to up those to 31 now :-/

2024-09-16 15:45 UTC, come-nc commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
Is that the right link? The Allconfig constructor does not call setUserValue.

2024-09-17 13:08 UTC, akhil1508 commented on lib/public/User/Events/UserConfigChangedEvent.php
> +	 * @since 30.0.0
Done

2024-09-17 13:11 UTC, akhil1508 commented on lib/composer/composer/autoload_static.php
> +        'OCP\\' =>
> I guess you opened and save the file with an editor which removed trailing spaces, no?

@come-nc Yes :| 

> Please make sure the file in git matches the result of composer install --no-dev

Done. So I ran `composer install --no-dev` and then discarded changes for the other files:

-  `composer/ClassLoader.php`
- `composer/installed.php`
- `composer/autoload_real.php`
- `composer/InstalledVersions.php`
- `autoload.php`

Is that okay?

2024-09-17 13:16 UTC, akhil1508 commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
@come-nc I believe I meant to say:

1. `AllConfig` is instantiated in `base.php` as `new \OC\AllConfig(new \OC\SystemConfig(self::$config))`
2. If I add `IEventListener $eventListener` in the constructor for DI in this class (the usual way), it could be problematic. I remember it causing errors when I first wrote this code, but maybe  I should re-test? 🤔

2024-09-18 06:24 UTC, come-nc commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
Yes please, the event listener is available early so I would be surprised if this is called even earlier. Maybe for login time :thinking: 
If some value change call do not trigger the event we need to document that.

2025-08-01 09:02 UTC, skjnldsv commented
Still some comments to address :)
@akhil1508 to you need help?

2025-08-04 07:13 UTC, akhil1508 commented
@skjnldsv Apologies, I look into finishing up this PR now :)

2025-08-04 07:46 UTC, akhil1508 commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
@come-nc so if I use DI to set the event dispatcher, I will have to replace https://github.com/nextcloud/server/blob/fd06f0c72de958855d535230b79583b30b9763b1/lib/base.php#L168

with 

```php
new \OC\AllConfig(new \OC\SystemConfig(self::$config), new EventDispatcher(new SymfonyDispatcher(...), ))
```
This doesn't look like the best solution to me :|


I did test `new \OC\AllConfig(new \OC\SystemConfig(self::$config), Server::get(IEventDispatcher::class))` and this gets me the error: 

```
Error: Typed static property OC::$server must not be accessed before initialization in /var/www/html/lib/public/Server.php:55
Stack trace:
#0 /var/www/html/lib/base.php(174): OCP\Server::get('OCP\\EventDispat...')
```

Could you advise?

2025-08-04 16:18 UTC, come-nc commented on lib/private/AllConfig.php
> +			$dispatcher = \OC::$server->get(IEventDispatcher::class);
My bad, AllConfig really is used really early, before the dispatcher can be injected.
So keep your solution, simple use the non-deprecated version:
```suggestion
			$dispatcher = \OCP\Server::get(IEventDispatcher::class);
```

2025-08-04 16:21 UTC, come-nc requested changes
Wait, but actually this needs to got into UserConfig, because AllConfig delegates to UserConfig, and some code path will use directly UserConfig, so if you do not want to miss events you need to dispatch from `OC\Config\UserConfig`.
(that was changed in 31 which is why we missed it when first reviewing this I think)

2025-08-04 16:22 UTC, come-nc commented
(And UserConfig supports DI :tada: so the dispatcher can be injected there)

2025-08-05 08:46 UTC, akhil1508 commented
@come-nc  indeed! I made the required changes to `UserConfig.php` now, let me know if the approach looks okay

2025-08-05 10:08 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> + * @since 31.0.0
```suggestion
 * @since 32.0.0
```
I’m sorry about the running gag, but this needs to be bumped to 32 now :see_no_evil: (and all the other `@since` as well).
Also, it would be good to add the new attribute `Listenable`, see https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/api.html#php-public-api

2025-08-05 10:08 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> +	}
```suggestion
	/**
	 * @since 32.0.0
	 */
	public function __construct(
		private string $userId,
		private string $appId,
		private string $key,
		private mixed $value,
		private mixed $oldValue = null,
	) {
		parent::__construct();
	}
```
Constructor property promotion makes it pretty :sparkles:

2025-08-05 10:08 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> +	 * @return string
```suggestion
```
Strong type is enough, same for the others.

2025-08-07 07:32 UTC, akhil1508 commented
@come-nc thanks for the review, resolved your comments

2025-08-07 11:07 UTC, come-nc approved these changes
Tiny nitpick to pass CI, but code looks good now.
Can you also squash/edit commits to please the conventionnal commits CI?

2025-08-07 11:07 UTC, come-nc commented on lib/private/Config/UserConfig.php
> +		protected IEventDispatcher $dispatcher
```suggestion
		protected IEventDispatcher $dispatcher,
```
I think `composer run cs:fix` would fix it as well.

2025-08-07 11:07 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> +#[Listenable(since: '32.0.0')]
Not sure what the tool will say but you may have to still add the `@since` phpdoc tag.
Ignore this comment if CI is green.

2025-08-07 11:07 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> + */
```suggestion
/**
 * SPDX-FileCopyrightText: 2025 Murena SAS <akhil.potukuchi.ext@murena.com>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
```
We use SPDX headers now for licensing. Changing to this should turn the REUSE CI green.

2025-08-07 11:07 UTC, come-nc commented on lib/public/User/Events/UserConfigChangedEvent.php
> +#[Listenable(since: '32.0.0')]
Yep: Error: lib/public/User/Events/UserConfigChangedEvent.php:32:1: InvalidDocblock: PHPDoc is required for classes/interfaces in OCP. (see https://psalm.dev/008)
```suggestion
/** @since 32.0.0 */
#[Listenable(since: '32.0.0')]
```

2025-08-07 11:08 UTC, come-nc commented
`composer run cs:fix` is needed for the order of imports as well

2025-08-08 14:50 UTC, akhil1508 commented
>  Can you also squash/edit commits to please the conventionnal commits CI?

@come-nc Squashed

2025-08-14 15:51 UTC, come-nc commented
Tests needs to be adapted

Example error:
```
365) Test\lib\Config\UserConfigTest::testClearCacheAll
ArgumentCountError: Too few arguments to function OC\Config\UserConfig::__construct(), 6 passed in /home/runner/actions-runner/_work/server/server/tests/lib/Config/UserConfigTest.php on line 294 and exactly 7 expected

2025-08-29 13:26 UTC, akhil1508 commented
> Tests needs to be adapted

@come-nc sorry, missed that. Fixed now

2025-09-26 08:05 UTC, AndyScherzinger approved these changes

2025-09-26 08:16 UTC, susnux approved these changes
Looks good, but the versions need to be adjusted

2025-09-26 08:16 UTC, susnux commented on lib/public/User/Events/UserConfigChangedEvent.php
> +#[Listenable(since: '32.0.0')]
Also for the tags below


```suggestion
/** @since 33.0.0 */
#[Listenable(since: '33.0.0')]
```

2025-09-26 09:01 UTC, akhil1508 commented
> Looks good, but the versions need to be adjusted

@susnux done, also rebased and squashed commits

2025-09-26 10:08 UTC, susnux approved these changes

2025-09-26 16:55 UTC, provokateurin approved these changes

2025-09-26 16:57 UTC, merged

2026-01-28 13:20 UTC, susnux commented
Needs documentation here:
https://github.com/nextcloud/documentation/blob/1a0415c8bf1541e90ae0b4da487a362a51a1cfe2/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_33.rst?plain=1#L182