Revert "Improve shared status button"
nextcloud/server pull request #42041
Opened 2023-12-05 16:40 UTC by skjnldsv

This reverts commit c2c5994d7069464b9e69a54ce2c660a1a340c711.

Sorry @marcoambrosini, I cannot approve the previous PR:
1. using deep selectors is not acceptable to me
2. you're changing this for all actions, while only the sharing got request
3. a comment was written by a lead with another lead reaction and got completely ignored

2023-12-05 16:58 UTC, artonge approved these changes

2023-12-05 17:07 UTC, Pytal approved these changes

2023-12-05 17:14 UTC, susnux approved these changes

2023-12-05 17:27 UTC, skjnldsv commented
I'll have a look with the design team to make sure we keep the previous issue fixed too

2023-12-05 23:13 UTC, marcoambrosini commented
Aside from the execution, admittedly poor and rushed, I just want to register that I did this reluctantly and didn't agree much with the set of changes proposed for this button. Nor with how fast they were rushed in without exploring other solutions.
So I thought of this as a temporary hack, while waiting to have have shared separate shared and owner columns.

2023-12-06 07:42 UTC, skjnldsv commented
All good, Marco :)
if the button style must go, then it must go! But without global styling

2023-12-06 14:03 UTC, jancborchardt requested changes
> I'll have a look with the design team to make sure we keep the previous issue fixed too

Could we make sure that we don’t revert it without addressing that part here already?
The specification / mockup exists at https://github.com/nextcloud/server/issues/37208, and as long as design-wise it looks like that, you are expert regarding implementation. :)

2024-01-17 08:46 UTC, blizzz commented
What about this PR, it appears stale?

2024-12-03 08:17 UTC, closed without merging