feat(settings): add occ commands to handle admin delegation
nextcloud/server pull request #42064
Opened 2023-12-06 15:21 UTC by Altahrim

## Summary
Add commands to handle admin delegation settings: 
  - `settings:admin-delegation:show`: show current delegation
  - `settings:admin-delegation:add`: add a delegation to a group
  - `settings:admin-delegation:remove`: remove a delegation from a group 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-12-06 16:34 UTC, artonge requested changes

2023-12-06 16:34 UTC, artonge commented on apps/settings/lib/Command/AdminDelegation/Add.php
> +			->setDescription('add delegated settings')
```suggestion
			->setDescription('add setting delegation to a group')
```

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Add.php
> +			->setName('settings:admin-delegation:add')
```suggestion
			->setName('admin-delegation:add')
```

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Remove.php
> +			->setName('settings:admin-delegation:remove')
```suggestion
			->setName('admin-delegation:remove')
```

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Show.php
> +			->setName('settings:admin-delegation:show')
```suggestion
			->setName('admin-delegation:show')
```

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Add.php
> +	}
```suggestion
```
Seens identical to the Base class method?

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Remove.php
> +	}
```suggestion
```

2023-12-06 18:46 UTC, Pytal commented on apps/settings/lib/Command/AdminDelegation/Show.php
> +	}
```suggestion
```

2023-12-07 08:47 UTC, come-nc commented on apps/settings/lib/Command/AdminDelegation/Show.php
> +		$sections = $this->settingManager->getAdminSections();
```suggestion
		$sections = $this->settingManager->getAdminSections();
```
Seems unused?

2023-12-07 10:36 UTC, Altahrim commented on apps/settings/lib/Command/AdminDelegation/Show.php
> +		$sections = $this->settingManager->getAdminSections();
Completely!

2023-12-07 14:18 UTC, Altahrim commented on apps/settings/lib/Command/AdminDelegation/Add.php
> +	}
Yes, I wasn't sure and forgot to check… Thanks!

2023-12-07 16:06 UTC, come-nc approved these changes
Tested and works

2023-12-07 17:17 UTC, Pytal approved these changes

2023-12-12 17:02 UTC, artonge approved these changes

2023-12-13 09:06 UTC, merged

2023-12-13 09:20 UTC, Altahrim commented
/backport to stable28