Rename "global search" to "unified search"
nextcloud/server pull request #42094
Opened 2023-12-07 11:27 UTC by Fenn-CS

- Changes appearances of "Global search" to "Unified search" in UI
- Refactors code, to remove usage of term "GlobalSearch" in files and code structure
- Rename old unified search to `legacy-unified-search`

2023-12-07 11:37 UTC, AndyScherzinger approved these changes

2023-12-07 11:48 UTC, AndyScherzinger commented
/backport to stable28

2023-12-07 12:53 UTC, Fenn-CS commented
/compile

2023-12-11 15:05 UTC, susnux commented on core/src/views/UnifiedSearchModal.vue
> +			:class="'unified-search__date-range'"
```suggestion
			class="unified-search__date-range"
```

2023-12-11 15:17 UTC, susnux requested changes
Tested and no search is loaded at all because of this error:

```
Uncaught Error: Could not find initial state limit-default of unified-search
    r index.es.mjs:13
    54201 UnifiedSearchService.js:30
    Webpack 5
        o
        c
        O
        <anonymous>
        <anonymous>
index.es.mjs:13:14

```

2023-12-11 15:31 UTC, Fenn-CS commented
> Tested and no search is loaded at all because of this error:
> 
> Uncaught Error: Could not find initial state limit-default of unified-search
>     r index.es.mjs:13
>     54201 UnifiedSearchService.js:30
>     Webpack 5
>         o
>         c
>         O
>         <anonymous>
>         <anonymous>
> index.es.mjs:13:14

This change does not contain the build, did you watch or build? I can't see this?

2023-12-11 16:15 UTC, emoral435 approved these changes
Tested this out in my dev setup and works, also looked over the code and it looks good to me 👍

2023-12-11 16:15 UTC, emoral435 commented
> Tested and no search is loaded at all because of this error:

I think it is because of not running npm build or watch, as @Fenn-CS mentioned. After running watch, the app works as expected on my dev setup with no error

2023-12-12 13:04 UTC, Fenn-CS commented
@susnux Since, you left a change request on this, I would like you to take a look one more time, thank you!

2023-12-12 19:45 UTC, susnux approved these changes

2023-12-12 20:13 UTC, merged

2023-12-12 20:22 UTC, Fenn-CS commented
backport to stable28

2023-12-12 20:23 UTC, Fenn-CS commented
/backport to stable28

2023-12-13 11:25 UTC, Fenn-CS commented
/backport to stable28