Removed path to datadir in exception
nextcloud/server pull request #4210
Opened 2017-04-05 00:11 UTC by MorrisJobke

* downstream of https://github.com/owncloud/core/pull/26643
* fixed #2046

2017-04-05 07:04 UTC, rullzer approved these changes
Fine by me

2017-04-05 12:30 UTC, nickvergessen commented on lib/private/legacy/util.php
> +					'error' => 'Your Data directory is not writable',
lowercase `data` ?

2017-04-05 12:31 UTC, nickvergessen requested changes

2017-04-05 12:31 UTC, nickvergessen commented on lib/private/legacy/util.php
> +					'error' => $l->t('Your Data directory is readable by other users'),
lowercase `data`

2017-04-05 12:31 UTC, nickvergessen commented on lib/private/legacy/util.php
> +				'error' => $l->t('Your Data directory must be an absolute path'),
lowercase `data`

2017-04-05 12:31 UTC, nickvergessen commented on lib/private/legacy/util.php
> +				'error' => $l->t('Your Data directory  is invalid'),
lowercase `data`

2017-04-05 12:31 UTC, nickvergessen commented on lib/private/legacy/util.php
> +					'error' => 'Your Data directory is not writable',
lowercase `data`

2017-04-10 09:14 UTC, nickvergessen approved these changes

2017-04-10 10:43 UTC, merged