Tooltip outside click, should abort share creation
nextcloud/server pull request #42126
Opened 2023-12-08 16:23 UTC by Fenn-CS

- It's unexpected that click outside a tooltip would proceed with the action that could be carried out inside the tooltip.
- Allow user to finish typing date before formatting

Resolves : https://github.com/nextcloud/server/issues/42046, https://github.com/nextcloud/server/issues/42114

2023-12-11 16:19 UTC, artonge requested changes
Some files seem unrelated

2023-12-11 20:07 UTC, Fenn-CS commented on apps/files_trashbin/tests/js/appSpec.js
> + * @author Vincent Petry <vincent@nextcloud.com>
Thank you!

2023-12-11 20:19 UTC, Fenn-CS commented
/compile

2023-12-11 22:27 UTC, artonge approved these changes

2023-12-12 19:26 UTC, susnux approved these changes

2023-12-12 19:29 UTC, merged

2023-12-12 20:21 UTC, Fenn-CS commented
backport to stable28

2023-12-12 20:21 UTC, Fenn-CS commented
backport to stable27

2023-12-12 20:22 UTC, Fenn-CS commented
/backport to stable28

2023-12-12 20:22 UTC, Fenn-CS commented
/backport to stable27

2023-12-13 11:33 UTC, Fenn-CS commented
/backport to stable28

2023-12-13 11:33 UTC, Fenn-CS commented
/backport to stable27

2024-01-15 08:38 UTC, skjnldsv commented
/skjnldsv-backport c179408a0dd8710f7b515179aab3dd9407794b0c 04e87337211351127cd02a0404936de8cb1b0837 to stable28