handle copy of live photos
nextcloud/server pull request #42170
Opened 2023-12-12 09:25 UTC by ArtificialOwl

- uses of handleMove() during the `BeforeNodeCopiedEvent` to check the doability of copying both files.
- handleCopy() called during the `NodeCopiedEvent` to generate a copy of the linked file.

2023-12-12 09:38 UTC, artonge commented on apps/files/lib/Listener/SyncLivePhotosListener.php
> +	private function handleMove(Event $event, Node $peerFile, bool $prepForCopyOnly = false): void {
Or extract the logic into a separate method?

2023-12-12 09:38 UTC, artonge commented on apps/files/lib/Listener/SyncLivePhotosListener.php
> +	private function handleMove(Event $event, Node $peerFile, bool $prepForCopyOnly = false): void {
```suggestion
	private function handleMove(AbstractNodesEvent $event, Node $peerFile, bool $prepForCopyOnly = false): void {
```

2023-12-12 09:38 UTC, artonge commented on apps/files/lib/Listener/SyncLivePhotosListener.php
> +		$this->pendingRenames[$sourceFile->getId()] = $peerFile->getId();
Could even be a simple boolean as we do not use the value in the end.

2024-02-08 10:53 UTC, artonge approved these changes

2024-02-15 15:47 UTC, ArtificialOwl commented
/backport to stable28

2024-03-04 16:33 UTC, artonge commented on lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
> +	public function __construct(Node $source, Node $target, private bool &$run) {
How can the listener gives the new value of `$run` back to the emitter?

2024-03-04 16:38 UTC, icewind1991 commented on lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
> +	public function __construct(Node $source, Node $target, private bool &$run) {
add a getter so `HookConnector` can retrieve it

2024-03-05 10:43 UTC, artonge commented on lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
> +	public function __construct(Node $source, Node $target, private bool &$run) {
That sounds smart.  @ArtificialOwl will you have the time to update the other event listeners too ? :D

2024-03-07 21:55 UTC, skjnldsv commented on lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
> +	public function __construct(Node $source, Node $target, private bool &$run) {
@ArtificialOwl :eyes:

2024-03-07 23:32 UTC, ArtificialOwl commented on lib/public/Files/Events/Node/BeforeNodeCopiedEvent.php
> +	public function __construct(Node $source, Node $target, private bool &$run) {
Tested few other ways but the simplest seems to have the HookController catching new event `AbortedEventException` and update `$arguments['run']`. Throwing the exception also stop the event propagation.

@icewind1991 @artonge please re-review

2024-03-08 10:30 UTC, icewind1991 requested changes

2024-03-08 10:30 UTC, icewind1991 commented on lib/public/Files/Events/Node/BeforeNodeDeletedEvent.php
> -	public function abortOperation(\Throwable $ex = null) {
This is part of the public api so we can't remove it without a deprecation period.

You could change it to just throw the `AbortedEventException`

2024-03-08 10:30 UTC, icewind1991 commented on lib/public/Files/Events/Node/BeforeNodeRenamedEvent.php
> -	public function abortOperation(\Throwable $ex = null) {
same here

2024-03-08 13:39 UTC, icewind1991 approved these changes

2024-03-08 13:45 UTC, artonge approved these changes

2024-03-08 14:51 UTC, merged

2024-03-08 17:04 UTC, ArtificialOwl commented
@artonge based on the size of the changes and the need for this feature, do we want to backport to 28 ?

2024-03-09 11:33 UTC, artonge commented
I would say no, but not for me to decide, @sorbaugh

2024-06-29 18:22 UTC, squid-f commented
Hi. Just updated to 29.0.3 and the error persists : 
` AbortedEventException Cannot delete the video part of a live photo
delete process aborted `

2024-11-06 14:09 UTC, kesselb commented
/backport to stable28