Translate me-text in unified search people filter
nextcloud/server pull request #42205
Opened 2023-12-13 11:22 UTC by Fenn-CS

Follow up : https://github.com/nextcloud/server/pull/42167

2023-12-13 11:53 UTC, artonge approved these changes

2023-12-13 12:09 UTC, nickvergessen requested changes

2023-12-13 12:09 UTC, nickvergessen commented on core/src/services/UnifiedSearchService.js
> +			fullName: t('core', 'Me'),
```suggestion
			fullName: authenticatedUser.displayName,
```
I think the own display name is better? Also removes the question if it should be "me" or "myself"

Cc @jancborchardt

2023-12-13 12:42 UTC, nimishavijay commented on core/src/services/UnifiedSearchService.js
> +			fullName: t('core', 'Me'),
Yes, generally we try to avoid using any variant of "Me" in the UI, so display name will work better :)

2023-12-13 13:55 UTC, nickvergessen commented on core/src/services/UnifiedSearchService.js
> +			fullName: t('core', 'Me'),
![grafik](https://github.com/nextcloud/server/assets/213943/6a4d160e-151e-4fca-8f79-19cc46e191d6)

2023-12-13 13:56 UTC, nickvergessen approved these changes

2023-12-14 11:41 UTC, Fenn-CS commented
/compile

2023-12-14 11:52 UTC, nickvergessen commented
I had pushed and compiled it already -.-

2023-12-14 12:51 UTC, merged