Allow searching file by fileid
nextcloud/server pull request #4222
Opened 2017-04-05 13:14 UTC by icewind1991

Fixes https://github.com/nextcloud/server/issues/4193

Note that multiple results can be returned for a single id since a user can have access to single file trough multiple paths

2017-04-05 13:16 UTC, nickvergessen requested changes

2017-04-05 13:16 UTC, nickvergessen commented on apps/dav/lib/Files/FileSearchBackend.php
> +			new SearchPropertyDefinition(FilesPlugin::INTERNAL_FILEID_PROPERTYNAME, true, true, false, SearchPropertyDefinition::DATATYPE_NONNEGATIVE_INTEGER),
please move up to `// queryable properties`

2017-04-05 13:23 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +			new SearchPropertyDefinition(FilesPlugin::INTERNAL_FILEID_PROPERTYNAME, true, true, false, SearchPropertyDefinition::DATATYPE_NONNEGATIVE_INTEGER),
done

2017-04-06 20:39 UTC, rullzer commented
@tobiasKaminsky can you verify if this works for you?

2017-04-06 21:09 UTC, nickvergessen approved these changes

2017-04-10 13:57 UTC, rullzer approved these changes
Seems to do the job :+1:

2017-04-10 13:57 UTC, merged

2017-04-10 14:54 UTC, tobiasKaminsky commented
Nice, thank you 👍

2017-06-16 16:18 UTC, MorrisJobke commented
@icewind1991 @tobiasKaminsky Do you have an example for this and could maybe document this?