fix(ooo): add new ooo status with new emoji
nextcloud/server pull request #42304
Opened 2023-12-15 10:18 UTC by miaulalala

* Resolves: https://github.com/nextcloud/server/issues/42300

## Summary
The OOO status set the predefined vacation status which is awkward when you're out sick :sneezing_face: 

| Before | After |
|--------|--------|
|  ![image](https://github.com/nextcloud/server/assets/7427347/7f9a717d-1cf2-4b6b-98a5-4dc75acf224b) | ![image](https://github.com/nextcloud/server/assets/7427347/ceb63e5b-c1a7-45a0-831e-e0382818fb96) | 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-12-15 10:19 UTC, miaulalala commented
/backport to stable28

2023-12-15 10:20 UTC, GretaD approved these changes
looks better

2023-12-15 10:48 UTC, nickvergessen commented on lib/public/UserStatus/IUserStatus.php
> +	 * @since 25.0.0
nop

2023-12-15 10:53 UTC, miaulalala commented on lib/public/UserStatus/IUserStatus.php
> +	 * @since 25.0.0
i cri evry tim

2023-12-18 09:34 UTC, nickvergessen commented on lib/public/UserStatus/IUserStatus.php
> +	 * @since 28.0.1
```suggestion
	 * @since 28.0.2
```

2023-12-18 09:35 UTC, nickvergessen requested changes
All good apart from the version in the docs

2023-12-18 10:33 UTC, miaulalala commented
> All good apart from the version in the docs

This is ok to go in to 28.0.1

2023-12-18 10:35 UTC, miaulalala commented on lib/public/UserStatus/IUserStatus.php
> +	 * @since 28.0.1
Will go into 28.0.1

2023-12-18 10:37 UTC, bigcat88 approved these changes

2023-12-18 10:39 UTC, nickvergessen approved these changes
LGTM didn't test

2023-12-18 10:51 UTC, miaulalala commented
@blizzz approval for 28.0.1

2023-12-18 11:41 UTC, merged