enh(dashboard): changed h1 to say Dashboard instead of Nextcloud
nextcloud/server pull request #42381
Opened 2023-12-19 16:11 UTC by emoral435

☑️ Resolves #42267

🖼️ Screenshots

🏚️ Before
![image](https://github.com/nextcloud/server/assets/110193237/a0ec6b6f-7e93-4ea0-aed9-108236416a10) 
🏡 After
![image](https://github.com/nextcloud/server/assets/110193237/a6779ab8-5cce-4619-8bc0-f04e5ac1aabc)

🚧 Summary
In order to make the dashboard / main page more accessible, the heading will be changed to something more descriptive, such as 'Dashboard'. I checked out the rest of the dashboard controller, and there seemed to be no usage of the translator, but if there is, it is preferable to use it here in this change for the header.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-12-19 16:12 UTC, emoral435 commented
/backport to stable28

2023-12-19 16:13 UTC, ShGKme approved these changes

2023-12-19 16:13 UTC, ShGKme requested changes

2023-12-19 16:13 UTC, ShGKme commented on apps/dashboard/lib/Controller/DashboardController.php
> +			'pageTitle' => 'Dashboard',
Probably it should be translated

2023-12-19 16:19 UTC, emoral435 commented on apps/dashboard/lib/Controller/DashboardController.php
> +			'pageTitle' => 'Dashboard',
agreed - just didnt see it in the other parts of the codebase, but I will try to see how to get this done :)

2023-12-19 16:21 UTC, susnux commented on apps/dashboard/lib/Controller/DashboardController.php
> +			'pageTitle' => 'Dashboard',
Inject `IL10N` in constructor as e.g. `l10n` then you can use `$this->l10n->t('dashboard', 'Dashboard')`

2023-12-19 16:23 UTC, emoral435 commented on apps/dashboard/lib/Controller/DashboardController.php
> +			'pageTitle' => 'Dashboard',
Gotcha! Will do right now (I am totally paying attention to the call we are in right now... haha 😅)

2023-12-19 16:48 UTC, ShGKme approved these changes

2023-12-19 16:51 UTC, susnux approved these changes

2023-12-20 22:30 UTC, merged

2024-01-15 13:26 UTC, ShGKme commented
A regression: it also changes the `<title>`, so it is now `Dashboard - Dashboard - Nextcloud`

2024-01-16 15:29 UTC, emoral435 commented
> A regression: it also changes the `<title>`, so it is now `Dashboard - Dashboard - Nextcloud` instead of `Dashboard - Nextcloud`

Ah, so complete honesty - I do not know how Nextcloud handles regressions like this. Should we open a new issue for this? And if its not too big, where is the title being affect? Maybe I can take a look at it :)