fix(files): move focus to sidebar on open
nextcloud/server pull request #42444
Opened 2023-12-22 02:07 UTC by ShGKme

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-07 09:25 UTC, JuliaKirschenheuter approved these changes
Works great too! Thank you!

2024-02-07 11:48 UTC, JuliaKirschenheuter commented
/compile /

2024-02-07 13:25 UTC, emoral435 approved these changes
Outside of a minor nitpick, LGTM! 🐘💙

2024-02-07 13:25 UTC, emoral435 commented on apps/files/src/views/Sidebar.vue
> +			// Only focus the tab, when the current file/tab in changed in aleady opened sidebar
```suggestion
			// Only focus the tab when the current file/tab selected is already opened in the sidebar
```

2024-02-07 14:22 UTC, ShGKme commented
> /compile /

This PR require `@nextcloud/vue` update first

2024-02-07 15:36 UTC, ShGKme commented on apps/files/src/views/Sidebar.vue
> +			// Only focus the tab, when the current file/tab in changed in aleady opened sidebar
I fixed some typos:
```
// Only focus the tab when the selected file/tab is changed in already opened sidebar
```

But kept the old meaning. It is used not when this file/tab was selected, but when any file/tab was selected and the sidebar was opened.

2024-02-07 15:41 UTC, emoral435 commented on apps/files/src/views/Sidebar.vue
> +			// Only focus the tab, when the current file/tab in changed in aleady opened sidebar
Ahhh - gotcha! 💙

2024-02-07 17:47 UTC, skjnldsv commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +				:aria-label="mountType === 'shared' && action.id === 'sharing-status' ? action.title([source]) : actionDisplayName(action)"
That seems really specific, where is this coming from and what does it have to do with that PR? :)

2024-02-07 17:51 UTC, skjnldsv requested changes
See comment

2024-02-07 19:08 UTC, ShGKme commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +				:aria-label="mountType === 'shared' && action.id === 'sharing-status' ? action.title([source]) : actionDisplayName(action)"
From the next one line (`title` prop) and the content of the button 7 lines below. I can move it to a new PR, but a button must have a label or text.

2024-02-07 23:05 UTC, ShGKme commented
/backport to stable28

2024-02-08 00:03 UTC, ShGKme commented
- Rebased onto `master` with required `@nextcloud/vue` changes
- Fixing labeling of inline files actions is moved to another PR

2024-02-08 00:03 UTC, ShGKme commented on apps/files/src/components/FileEntry/FileEntryActions.vue
> +				:aria-label="mountType === 'shared' && action.id === 'sharing-status' ? action.title([source]) : actionDisplayName(action)"
@skjnldsv moved to another PR

2024-02-08 07:57 UTC, skjnldsv approved these changes

2024-02-08 07:57 UTC, merged

2024-02-08 10:45 UTC, JuliaKirschenheuter commented
/backport to stable28