Ignore shared Collective mounts when scanning files
nextcloud/server pull request #42497
Opened 2023-12-27 12:22 UTC by arnowelzel

* Resolves: #42496

## Summary

When scanning files using `occ files:scan`, shared Collective mounts trigger "Path not found" error messages. This change will make sure that that Collective mounts will be ignored.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2023-12-27 12:22 UTC, arnowelzel commented
/backport to stable28

2023-12-27 19:14 UTC, emoral435 commented on lib/private/Files/Utils/Scanner.php
>  			// don't scan received local shares, these can be scanned when scanning the owner's storage
If you have the time, it would be really appreciated to add the new collective check to the comment :) not needed though

2023-12-27 19:15 UTC, emoral435 approved these changes
Nice change, looks good to me :)

2023-12-27 19:16 UTC, emoral435 commented
Fast review ~!

2023-12-27 21:50 UTC, arnowelzel commented on lib/private/Files/Utils/Scanner.php
>  			// don't scan received local shares, these can be scanned when scanning the owner's storage
Done ;-)

2024-01-02 10:57 UTC, artonge approved these changes
Looks good, but let's wait for @max-nextcloud or @JonasMayerDev input :)

2024-01-02 11:33 UTC, max-nextcloud commented
@mejo- is the better person when it comes to backend changes.

I have some uninformed questions though...
* What will happen if collectives is not installed and the used class is not available?
  Will php be happy with that?
* You are talking about a `shared collective` - are you referring to a collective that has been explicitly shared by link or a normal collective with multiple members?

In general it seems not ideal to me to have collectives specific code in server. I wonder if we could instead make `CollectiveStorage` a `SharedStorage` as that could happen on the collectives side of things.

2024-01-02 11:37 UTC, max-nextcloud commented
I remember that collectives storage was designed closely to what groupfolders does. Does this issue not occur with groupfolders ? How is the groupfolders implementation different from collectives?

2024-01-02 12:03 UTC, arnowelzel commented
> @mejo- is the better person when it comes to backend changes.
> 
> I have some uninformed questions though...
> 
> * What will happen if collectives is not installed and the used class is not available?
>   Will php be happy with that?

I tested this case and had no problem without Collectives installed, since `instanceOfStorage()` will only check the class name and it should not matter, if the class actually exists.

But I agree it would be better not to rely on multiple classes here but instead have a common method which can be used. Maybe adding a method `isShared()` to the `Storage` interface may help. This sould return `true` by `SharedStorage` or `CollectiveStorage` and otherwise `false` so the scanner knows when to ignore the storage:

```
			// don't scan shared storages, these can be scanned when scanning the owner's storage
			if ($storage->isShared()) {
				continue;
			}
``` 

However this would involve substantial refactoring of the backend code.

> * You are talking about a `shared collective` - are you referring to a collective that has been explicitly shared by link or a normal collective with multiple members?

I refer to a normal collective which is shared with multiple members of a circle.

2024-02-23 15:39 UTC, skjnldsv commented
@max-nextcloud @mejo- any update?

2024-02-23 15:40 UTC, skjnldsv commented on lib/private/Files/Utils/Scanner.php
> +			if ($storage->instanceOfStorage(SharedStorage::class) || $storage->instanceOfStorage(CollectiveStorage::class)) {
I'm wondering if we don't need to check if the class exists before ? :thinking: 
@come-nc @icewind1991

2024-02-24 16:18 UTC, skjnldsv commented
@arnowelzel psalm said no

2024-02-24 16:49 UTC, arnowelzel commented on lib/private/Files/Utils/Scanner.php
> +			if ($storage->instanceOfStorage(SharedStorage::class) || $storage->instanceOfStorage(CollectiveStorage::class)) {
Strange - it works without problems for me. Maybe then the more thorough refactoring implementing an additional interface method as suggested, is a better. I'll have a look into this.

2024-02-25 01:35 UTC, arnowelzel commented
Since using the class name of the Collective storage is not possible in any way without triggering a psalm error I changed the test as following:

```php
			// don't scan received local shares or collectives, these can be scanned when scanning the owner's storage
			if (substr($storage->getId(), 0, 6) !== 'home::') {
				continue;
			}
```

The idea here is, that only home storages should get scanned. Recieved shared storage start with `shared::` and Collectives, which trigger the error, report IDs as `local::` followed by the physical path. However I don't know if any other storages which should indeed be scanned, also report an ID starting with something different from `home::`.

I also noticed the following code in `\OCA\Collectives\Mount\CollectiveStorage` - maybe in the past this problem was mitigated by using `NoopScanner` which does not exist any longer?

```php
	public function getScanner($path = '', $storage = null): Scanner {
		if (!$storage) {
			$storage = $this;
		}
		if ($storage->instanceOfStorage(ObjectStoreStorage::class)) {
			// NoopScanner is private API and kept here for compatibility with older releases
			$storage->scanner = class_exists(NoopScanner::class) ? new NoopScanner($storage) : new ObjectStoreScanner($storage);
		} elseif (!isset($storage->scanner)) {
			$storage->scanner = new Scanner($storage);
		}
		return $storage->scanner;
	}
```

2024-03-07 22:55 UTC, mejo- commented
Probably @icewind1991 is the best to decide whether it's a good idea to limit scanning to `home` storages.

2024-03-08 10:54 UTC, icewind1991 requested changes

2024-03-08 10:54 UTC, icewind1991 commented on lib/private/Files/Utils/Scanner.php
> +			if (substr($storage->getId(), 0, 6) !== 'home::') {
This will break scanning of external storages.

2024-03-08 10:55 UTC, icewind1991 commented
What is stopping the collectives from being scanned correctly in the first place?

2024-03-08 12:11 UTC, arnowelzel commented on lib/private/Files/Utils/Scanner.php
> +			if (substr($storage->getId(), 0, 6) !== 'home::') {
What ID do external storages have?

2024-03-08 12:13 UTC, arnowelzel commented
> What is stopping the collectives from being scanned correctly in the first place?

They are shared storages like `SharedStorage` and thus don't provide a physical path which can be scanned.

2024-03-08 13:15 UTC, icewind1991 commented on lib/private/Files/Utils/Scanner.php
> +			if (substr($storage->getId(), 0, 6) !== 'home::') {
they all have different prefixes, in general attempts to filter by storage id is imprecise at best.

2024-03-08 13:15 UTC, icewind1991 commented
If they can't be scanned at all then having them use ` NoopScanner` is probably the best (shared storage should also move to that really)

2024-03-08 13:16 UTC, arnowelzel commented
> If they can't be scanned at all then having them use ` NoopScanner` is probably the best (shared storage should also move to that really)

Well - `NoopScanner` does not exist any longer.

2024-03-08 13:37 UTC, icewind1991 commented
Right, it got moved to `ObjectStoreScanner` when it got slightly less noop, should be good to still use that one or just create your own

2024-03-08 13:42 UTC, arnowelzel commented
> Right, it got moved to `ObjectStoreScanner` when it got slightly less noop, should be good to still use that one or just create your own

It seems, this is what Collectives is using right now - but it does not work. See https://github.com/nextcloud/collectives/blob/main/lib/Mount/CollectiveStorage.php#L62-L74:

```php
public function getScanner($path = '', $storage = null): Scanner {
		if (!$storage) {
			$storage = $this;
		}
		if ($storage->instanceOfStorage(ObjectStoreStorage::class)) {
			// NoopScanner is private API and kept here for compatibility with older releases
			$storage->scanner = class_exists(NoopScanner::class) ? new NoopScanner($storage) : new ObjectStoreScanner($storage);
		} elseif (!isset($storage->scanner)) {
			$storage->scanner = new Scanner($storage);
		}
		return $storage->scanner;
	}
```

2025-08-22 22:46 UTC, arnowelzel commented
Since no one has an idea about this I suggest to close this. The code is way outdated anyway.

2025-08-22 22:46 UTC, closed without merging