Disable lookupserver upload
nextcloud/server pull request #4250
Opened 2017-04-07 09:54 UTC by schiessle

Allow the admin to disable the possibility to publish user specific data on the lookup server.

fixes the "turn off showing phone number, address, WWW, Twitter" part of https://github.com/nextcloud/server/issues/3821 

cc @KB7777

2017-04-07 17:41 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-04-10 05:51 UTC, ChristophWurst requested changes
some nitpicks, the rest looks good though

2017-04-10 05:51 UTC, ChristophWurst commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		return ($result === 'yes') ? true : false;
the `($result === 'yes')` part already results in a proper boolean value, no need for the ternary operator here 😉 

We could even shorten this to
```php
return $this->config->getAppValue('files_sharing', 'lookupServerUploadEnabled', 'yes') === 'yes';
```

2017-04-10 07:44 UTC, schiessle commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		return ($result === 'yes') ? true : false;
completely right, that's happen if you copy&paste methods and only replace the relevant parts 😉 

I will not do the last step you suggested because I think this makes it harder to debug but will simplify the return statement

2017-04-10 08:11 UTC, ChristophWurst approved these changes

2017-04-10 09:04 UTC, merged