add capabilities for share by mail
nextcloud/server pull request #4251
Opened 2017-04-07 13:45 UTC by schiessle

add share by mail capabilities so that the clients know if the share provider is available or not

2017-04-07 14:22 UTC, nickvergessen commented on apps/files_sharing/lib/Capabilities.php
> +		if ($this->appManager->isEnabledForUser('sharebymail')) {
just do this in the share by mail app instead?

2017-04-07 14:33 UTC, schiessle commented on apps/files_sharing/lib/Capabilities.php
> +		if ($this->appManager->isEnabledForUser('sharebymail')) {
I put it here so that all sharing capabilities all grouped together under "sharing". We also have the federated sharing capabilities here and not in the federation app... but yes, I'm also a bit undecided here. Other opinions? @rullzer @MorrisJobke?

2017-04-07 15:24 UTC, nickvergessen commented on apps/files_sharing/lib/Capabilities.php
> +		if ($this->appManager->isEnabledForUser('sharebymail')) {
the capabilities are all merged together. So just do:
```php
return [
	'files_sharing' => [
		'mailshare' => [
			'enabled' => true,
		],
	],
];
```

and it works

2017-04-07 17:43 UTC, MorrisJobke requested changes

2017-04-07 17:43 UTC, MorrisJobke commented on apps/files_sharing/lib/Capabilities.php
> +		if ($this->appManager->isEnabledForUser('sharebymail')) {
Yep - please go for the solution by @nickvergessen

2017-04-10 09:02 UTC, schiessle commented
updated

2017-04-10 09:58 UTC, nickvergessen commented on apps/sharebymail/lib/Capabilities.php
> +		return ['sharebymail' => true];
I'd also have this being an array.
Otherwise there is a type change between `sharebymail` in 11 and 12. (not all languages that use our api are un-typed... Just make it an array with `enabled` ?

2017-04-10 09:59 UTC, nickvergessen requested changes

2017-04-10 09:59 UTC, nickvergessen commented on apps/sharebymail/lib/AppInfo/Application.php
> +	public function __construct(Settings $settings, array $urlParams = array()) {
Application class must not have non-default parameters.

2017-04-10 09:59 UTC, nickvergessen commented on apps/sharebymail/lib/AppInfo/Application.php
> +		Util::connectHook('\OCP\Config', 'js', $this->settings, 'announceShareProvider');
Please create the class here

2017-04-10 10:08 UTC, nickvergessen commented on apps/sharebymail/lib/AppInfo/Application.php
> +	public function __construct(Settings $settings, array $urlParams = array()) {
https://github.com/nextcloud/server/blob/1614b310ef0e4871dc5f21630e887010e0fb22bc/lib/private/Route/Router.php#L374-L375

2017-04-10 10:08 UTC, schiessle commented on apps/sharebymail/lib/Capabilities.php
> +		return ['sharebymail' => true];
If you compare it with other capabilities you will see that this is nothing new. Also In think a "enable" property doesn't make sense because it implies that there is also a "disable" while that's not the case.

2017-04-10 10:15 UTC, nickvergessen commented on apps/sharebymail/lib/AppInfo/Application.php
> +	public function __construct(Settings $settings, array $urlParams = array()) {
Yeah until the app hosts a route, or we add similar code somewhere else.

2017-04-10 10:26 UTC, schiessle commented on apps/sharebymail/lib/Capabilities.php
> +		return ['sharebymail' => true];
... but I see the point with potential other languages, so I will change it even if it is ugly 😉

2017-04-10 10:59 UTC, nickvergessen approved these changes

2017-04-10 16:23 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-04-10 17:48 UTC, merged