Cancel PR #37405, remove regression code
nextcloud/server pull request #42544
Opened 2024-01-02 08:57 UTC by HLFH

* Resolves: #41196

## Summary

It cancels PR #37405, removes all the regression code.
This issue is it has been 9 months than the logout takes 30 seconds on Chrome-like browsers since this PR.
If anything was interesting in the highly damaging PR #37405, I highly recommend to add any feature-related PR in a separate PR, as this one is only meant to fix a critical bug, which makes Nextcloud unusable.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-02 09:33 UTC, artonge requested changes
Let's keep the HTTPS check :)

2024-01-02 09:33 UTC, artonge commented on core/Controller/LoginController.php
> +		if (!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])) {
```suggestion
		if (
			$this->request->getServerProtocol() === 'https' &&
			!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])
		) {
```

2024-01-02 09:34 UTC, artonge commented on core/Controller/LoginController.php
> +		if (!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])) {
Can you also add a link to [this issue](https://github.com/nextcloud/server/issues/41196) in a comment so we do not remove the condition again in the future?

2024-01-02 14:32 UTC, szaimen approved these changes
LGTM with the changes by @artonge

2024-01-04 20:37 UTC, HLFH commented
I signed-off your commit. @artonge
I don't know if we need to add anything in `LoginControllerTest.php` with your commit.

2024-01-08 09:48 UTC, artonge approved these changes

2024-01-08 09:49 UTC, artonge commented
Drone is not triggered. Merging.

2024-01-08 09:49 UTC, merged

2024-01-08 13:12 UTC, nickvergessen commented
> Drone is not triggered. Merging.

Drone is actually red due to this PR:
```
Runtime:       PHP 8.2.14
Configuration: phpunit-autotest.xml

FFF............                                                   15 / 15 (100%)

Time: 00:00.049, Memory: 30.00 MB

There were 3 failures:

1) Tests\Core\Controller\LoginControllerTest::testLogoutWithoutToken
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\RedirectResponse Object (
     'headers' => Array (
         'Location' => '/login'
-        'Clear-Site-Data' => '"cache", "storage"'
     )
     'cookies' => Array ()
     'status' => 303

/home/nickv/Nextcloud/29/server/tests/Core/Controller/LoginControllerTest.php:160

2) Tests\Core\Controller\LoginControllerTest::testLogoutNoClearSiteData
Expectation failed for method name is "isUserAgent" when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

3) Tests\Core\Controller\LoginControllerTest::testLogoutWithToken
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\RedirectResponse Object (
     'headers' => Array (
         'Location' => '/login'
-        'Clear-Site-Data' => '"cache", "storage"'
     )
     'cookies' => Array ()
     'status' => 303

/home/nickv/Nextcloud/29/server/tests/Core/Controller/LoginControllerTest.php:214
```

Drone is configured to no longer work on forks due to some security implications.

It is recommended to fork the PR into our org for now when they are good.

Can you follow up to make CI green again?

2024-02-10 22:42 UTC, HLFH commented
@artonge Can this with https://github.com/nextcloud/server/pull/42633 be backported for stable-28 branch? For 28.0.3 release :)

2024-02-12 11:57 UTC, artonge commented
/backport to stable28

2024-02-12 11:58 UTC, artonge commented
@HLFH can you ensure that https://github.com/nextcloud/server/pull/42633 is included in the created PR?

2024-02-13 01:12 UTC, susnux commented on core/Controller/LoginController.php
>  			$response->addHeader('Clear-Site-Data', '"cache", "storage"');
I think this should have been fixed in the master pr. Instead of excluding Chrome just drop the cache part.

Thats what slows chrome down, because of a 7 years old chrome bug...

2024-02-21 11:02 UTC, skjnldsv commented on core/Controller/LoginController.php
>  			$response->addHeader('Clear-Site-Data', '"cache", "storage"');
:eyes: