deprecated sysconfig 'enable_file_metadata'
nextcloud/server pull request #42628
Opened 2024-01-08 13:47 UTC by ArtificialOwl

2024-01-08 13:52 UTC, artonge approved these changes

2024-01-14 22:19 UTC, solracsf approved these changes

2024-02-23 18:39 UTC, skjnldsv requested changes
Can you add context to this?
Also this is not a deprecation, this is a complete removal? :thinking:

2024-03-08 14:26 UTC, ArtificialOwl commented
> Can you add context to this? Also this is not a deprecation, this is a complete removal? 🤔

This tag is was related to previous concept for metadata and it is not used anymore since the new API for Metadata

2024-03-09 08:18 UTC, skjnldsv approved these changes

2024-03-11 12:00 UTC, merged