enh(core): replaced previous native a element with NcButton
nextcloud/server pull request #42636
Opened 2024-01-08 15:41 UTC by emoral435

* Resolves: #42596

## Summary
Replaces native <a/> element with the NcButton primary button, that works with contrast, defines the role of the <a/> element as `role="button"`, keeps the same logic, and added the `<img/>` elements alt attribute.

Once this passes all reviews, I will remove all the commented out code unless you guys wish to leave it there :)

## 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![firefox_P7wrQ33Da0](https://github.com/nextcloud/server/assets/110193237/8824efd8-17dc-4b3a-abb5-2e8cba8a534d) | ![firefox_EloQYE2bqV](https://github.com/nextcloud/server/assets/110193237/20c1e865-08b3-429a-8d15-9da4fd05970a)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-08 15:56 UTC, ShGKme requested changes

2024-01-08 20:17 UTC, emoral435 commented on core/src/components/Profile/PrimaryActionButton.vue
> +		:aria-label="`Send Mail To ${href}`"
Ah, nice catch! Because this button in general opens the users native mail application, I will mention that in the message and leave it as simple as that in the new PR. If you think something else would be more descriptive, please tell me :)

2024-01-08 23:23 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
> +		:aria-label="`Send Mail To ${href}`"
> Because this button in general opens the users native mail application

This button show the first action, but it can be anything in theory. Email, phone, Talk.

But I've missed that this button has a slot, so it has actual text content. In this case there is no need in `aria-label`. Moreover, this is an issue if `aria-label` and the text are different.

2024-01-08 23:26 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
>  		<slot />
Such slot description may make sense in `@nextcloud/vue`, because it generates public documentation based on the text, but here it is redundant. The component is used only in 1 place right here, and default slot is used for the main content of the button as it is expected to be.

2024-01-09 00:20 UTC, emoral435 commented on core/src/components/Profile/PrimaryActionButton.vue
> +		:aria-label="`Send Mail To ${href}`"
Gotcha! Will remove the aria-label then 🫡

2024-01-09 07:32 UTC, ShGKme approved these changes
Everything looks fine now, thank you for the changes. 

Don't forget to remove the commented lines :p

2024-01-09 13:51 UTC, emoral435 commented
Gotcha! Will remove the comments now that you have cleared it :)

2024-01-09 14:06 UTC, emoral435 commented
Gotcha! Will remove the comments now that you have cleared it :) Also dont mind the cherry pick, that was a mistake!

2024-01-09 14:17 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
> +				alt="" />
I've missed that it is not covered by `NcButton`. Icon should be manually inverted with
```
filter: var(--primary-invert-if-dark)
```

Otherwise it is always dark...

![image](https://github.com/nextcloud/server/assets/25978914/5b2fd7db-ec8c-4322-82f1-6d182aa3e5bc)

2024-01-09 14:27 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
> +				alt="" />
Hmm, or not

2024-01-09 14:27 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
> +				alt="" />
Your screenshot has black text and mine has white...

2024-01-09 14:29 UTC, emoral435 commented on core/src/components/Profile/PrimaryActionButton.vue
> +				alt="" />
Whoops, I meant the newest commit that I am working on right now. Have not pushed it yet :0

2024-01-09 14:32 UTC, emoral435 commented on core/src/components/Profile/PrimaryActionButton.vue
> +				alt="" />
![firefox_frMCz55zrI](https://github.com/nextcloud/server/assets/110193237/22dd22a7-647d-4a98-9441-9a2a2e0bfb65)
With the newest commit, this is how the button will look like on light and dark mode :o

2024-01-09 14:35 UTC, emoral435 commented
/backport to stable28

2024-01-09 14:36 UTC, ShGKme commented on core/src/components/Profile/PrimaryActionButton.vue
> +
ESLint: 
```
/home/shgk/nextcloud/server/core/src/components/Profile/PrimaryActionButton.vue
  28:24  warning  Expected 1 line break after opening tag (`<NcButton>`), but 2 line breaks found  vue/multiline-html-element-content-newline
  31:4   warning  Disallow self-closing on HTML void elements (<img/>)                             vue/html-self-closing
```

2024-01-09 14:38 UTC, ShGKme approved these changes

2024-01-09 18:43 UTC, susnux approved these changes

2024-01-09 18:43 UTC, merged