Declarative settings
nextcloud/server pull request #42661
Opened 2024-01-09 15:07 UTC by andrey18106

## Summary

_This is draft PR text_

This PR introduces Declarative settings implementation that allows PHP apps and ExApps (AppAPI) to register simple schema of settings that will be rendered by server. Settings storage could be handled either by internal storage (by server), or implemented by apps using provided events:

1. `GetDeclarativeSettingsValueEvent`
2. `SetDeclarativeSettingsValueEvent`

To register schema apps can utilize either `IRegistrationContext->registerDeclarativeSettings` method to pass their schema (`IDeclarativeSettingsForm`) or listen to `RegisterDeclarativeSettingsFormEvent` and pass their schema there.

All supported fields displayed on screenshots below and available in `testing (QA testing)` app. These form types declared in `OCP\Settings\DeclarativeSettingsTypes`.

![Screen Shot 2024-01-09 at 16 53 00](https://github.com/nextcloud/server/assets/29692256/3ea19846-598b-4da6-8a04-64bcc6470188)
![Screen Shot 2024-01-09 at 16 53 16](https://github.com/nextcloud/server/assets/29692256/94169935-0b67-4c56-aee7-86adb993fb91)
![Screen Shot 2024-01-09 at 16 53 49](https://github.com/nextcloud/server/assets/29692256/06613359-a649-4971-8701-cd0c1bff3a0f)

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-10 08:10 UTC, bigcat88 commented on lib/public/Settings/DeclarativeSettingsTypes.php
> +	public const CHECKBOX_ATTRIBUTES = ['id', 'title', 'description', 'type', 'label', 'default'];
Does any line of code reference this?

2024-01-11 10:01 UTC, julien-nc requested changes
* [x] We could revert all changes made in the provisioning_api app
* [x] The horizontal separator between fields can be removed IMO. A separator between setting sections is enough
* [ ] Maybe we should use `label` instead of `label-inside` for NcInputField. To be discussed
* [ ] Field values are not validated yet, should we introduce the regexp attribute now?
* [ ] Fields should not be 100% wide. Let's try: as wide as possible, max 400px
* [ ] generateUrl does not work anymore in this branch, let's rebase on master. We need to remove the changes to compiled assets for an easier rebase
* [ ] For multi select, the label could be placed above and the hint below
* [ ] Same for single checkbox

2024-02-09 12:20 UTC, bigcat88 commented on lib/public/Settings/GetDeclarativeSettingsValueEvent.php
> +		if ($this->value !== null) {
No exception should be thrown here

2024-02-12 13:37 UTC, provokateurin commented on apps/provisioning_api/composer/composer/autoload_static.php
Change needs to be dropped

2024-02-12 14:19 UTC, andrey18106 commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +			$this->initialState->provideInitialState('declarative-settings-forms', $this->declarativeSettingsManager->getFormsWithValues($this->userSession->getUser(), $type, $section));
@provokateurin Should we adjust interface to expect nullable user instance or suppress this psalm error?

2024-02-12 14:22 UTC, provokateurin commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +			$this->initialState->provideInitialState('declarative-settings-forms', $this->declarativeSettingsManager->getFormsWithValues($this->userSession->getUser(), $type, $section));
We will always have a user present so we can just ignore the error.

2024-02-12 14:43 UTC, andrey18106 commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +				$templateParams['content'] .= join(array_map(fn (string $id) => '<div id="' . $app . '_' . $id . '"></div>', $ids));
@provokateurin this also can be suppressed and then we are ready to review with green CI.

2024-02-12 14:49 UTC, provokateurin commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +				$templateParams['content'] .= join(array_map(fn (string $id) => '<div id="' . $app . '_' . $id . '"></div>', $ids));
Yes, psalm doesn't know that it will be used, so it can be suppressed.

2024-02-12 19:07 UTC, andrey18106 commented
/compile

2024-02-13 17:57 UTC, provokateurin commented on apps/settings/appinfo/routes.php
> +		['name' => 'DeclarativeSettings#setValue', 'url' => '/settings/api/declarative', 'verb' => 'POST', 'root' => ''],
This route needs to be in the `ocs` section. Then the spec will be updated correctly.

2024-02-13 18:10 UTC, andrey18106 commented on apps/settings/appinfo/routes.php
> +		['name' => 'DeclarativeSettings#setValue', 'url' => '/settings/api/declarative', 'verb' => 'POST', 'root' => ''],
Should be correct now

2024-02-14 10:29 UTC, julien-nc requested changes
Very nice! Thanks for implementing tests.

Minor comments, otherwise :+1:

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/lib/Controller/PersonalSettingsController.php
> +		IEventDispatcher $eventDispatcher,
Are `$coordinator` and `$eventDispatcher` really used? If so, this needs an explanation comment.

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +			:aria-label="t('settings', '{app} declarative setting field: {name}', { app: formApp, name: t(formApp, formField.title) })"
```suggestion
			:aria-label="t('settings', '{app}\'s declarative setting field: {name}', { app: formApp, name: t(formApp, formField.title) })"
```

Also the name translation part needs an explanation comment about why it works with forms registered by class and by event. And for the event case, why it works with Php apps and exApps.

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +				'declarative-form-field-text': isTextFormFields(formField),
```suggestion
				'declarative-form-field-text': isTextFormField(formField),
```

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +				'declarative-form-field-radio': formField.type === 'radio'
These type values should be constants IMO.

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +		},
The body of this computed prop does not contain any prop/data that can change. So it will never be computed again.
It could be a method:
``` js
isTextFormFields(formField) {
	return ['text', 'password', 'email', 'tel', 'url', 'search', 'number'].includes(formField.type)
},
```

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +					this.$set(formField, 'value', +formField.value)
Add small comment about the `+` effect.

2024-02-14 10:29 UTC, julien-nc commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +		}, 1000),
Nitpick
```suggestion
		onChangeDebounced: debounce(formField => {
			this.updateDeclarativeSettingsValue(formField)
		}, 1000),
```

2024-02-14 10:29 UTC, julien-nc commented on lib/private/Settings/DeclarativeManager.php
> +				return false;
For some/all types, the placeholder could not be mandatory. Wdyt?

2024-02-14 10:35 UTC, julien-nc requested changes

2024-02-14 10:35 UTC, julien-nc commented on lib/private/Settings/DeclarativeManager.php
> +				$this->config->setAppValue($app, $fieldId, $value);
We could use `IAppConfig` since `IConfig::setAppValue` is deprecated.

2024-02-14 10:35 UTC, provokateurin commented on apps/settings/lib/Controller/DeclarativeSettingsController.php
> +	public function setValue(string $app, string $formId, string $fieldId, mixed $value): DataResponse {
Instead of implementing it separately it will be done like the forms where the value is already in the data.

2024-02-20 08:26 UTC, bigcat88 commented on apps/settings/lib/Controller/DeclarativeSettingsController.php
> +			$this->logger->error("Failed to set declarative settings value: " . $e->getMessage());
@provokateurin forgot about this

2024-02-21 17:12 UTC, andrey18106 commented on apps/settings/src/components/DeclarativeSettings/DeclarativeSection.vue
> +		}, 1000),
With arrow func we'll lose context (closure) for `this.updateDeclarativeSettingsValue(formField)` call inside it, so I can't use it.

2024-02-21 17:16 UTC, andrey18106 commented on lib/private/Settings/DeclarativeManager.php
> +				$this->config->setAppValue($app, $fieldId, $value);
The new `IAppConfig` has only explicitly typed methods, what should we use then? `setValueString`?

2024-02-21 17:34 UTC, andrey18106 commented on lib/private/Settings/DeclarativeManager.php
> +				return false;
Yeah, agree, it's not needed

2024-02-23 08:07 UTC, ChristophWurst commented
Nitpick on https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#naming-scheme

 * GetDeclarativeSettingsValueEvent -> DeclarativeSettingsValueRequestedEvent
 * SetDeclarativeSettingsValueEvent -> DeclarativeSettingsValueSetEvent

Then the event name explains what happens (the *event*) and is less imperative.

2024-02-23 08:08 UTC, ChristophWurst commented on lib/public/Settings/SetDeclarativeSettingsValueEvent.php
> +namespace OCP\Settings;
```suggestion
namespace OCP\Settings\Event;
```

suggestion for a better location. many other lib/public/* have a dedicated namespace for event classes

2024-03-07 13:32 UTC, julien-nc approved these changes

2024-03-07 13:32 UTC, andrey18106 commented
/compile

2024-03-08 11:48 UTC, ChristophWurst commented
Still contains fixups. Mind just squashing this into one commit? It seems the second to last commits are just fixes for the first

2024-03-08 14:28 UTC, julien-nc commented
Psalm failure is unrelated (missing `getTeamResourceProviders` registration context method).

2024-03-11 11:02 UTC, bigcat88 approved these changes
Hope this will be merged in `Beta 2`..

2024-03-12 12:19 UTC, andrey18106 commented
@ChristophWurst @blizzz 
rebased PR again,
psalm error unrelated, can we force-merge it?

2024-03-12 15:27 UTC, Altahrim commented
Psalm error is related.
Method is deleted in https://github.com/nextcloud/server/pull/42661/files#diff-6f7fce46b3b19b872adcab3426e155b80766fd2b10feabc70ae29cbac2433a40L900 and still used in `TeamManager.php`

2024-03-12 15:32 UTC, nickvergessen commented on lib/public/Settings/Events/DeclarativeSettingsGetValueEvent.php
> +<?php
Declare strict + copyright missing in event files

2024-03-12 15:32 UTC, nickvergessen commented on lib/public/Settings/IDeclarativeManager.php
> +<?php
declare strict

2024-03-12 15:32 UTC, nickvergessen commented on lib/public/Settings/IDeclarativeSettingsForm.php
> +<?php
also here and in other files you added

2024-03-12 17:05 UTC, merged