feat(AppFramework): Add Route attribute
nextcloud/server pull request #42801
Opened 2024-01-15 14:06 UTC by provokateurin

## Summary

A new routing method that should make it easier for new developers. It avoids having to manually verify the connection between the layers of the routes and the controllers.

The changes to the openapi.json file are annoying but required because the order of the routes changed. You can verify there were no changes using http://play.jd-tool.io. Since there is no diff we can also be sure I migrated all routes correctly.

I did some benchmarking and would consider the slight drop in performance to be acceptable. It is about 2-5ms which is not noticable and there are many other factors in a remote HTTP connection that cause way more delay (tests were done on localhost). I have some ideas which could be tried to improve the performance a bit (but there is no guarantee that they will).

Only the 99th percentile is really relevant as the longest request can also be a fluke (see in the baseline testing for the capabilities endpoint). All tests were done with 10k requests on the standalone PHP webserver with SQLite and without any caching configured.

The core test is to check for changes in parsing the routes and the test with Talk (which has not been migrated) is to check the impact on apps with many routes. The total number of enabled apps has no performance impact on this new mechanism.

Before:
```log
$ ab -n 10000 -H "OCS-APIRequest: true" http://localhost:8080/ocs/v2.php/cloud/capabilities
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /ocs/v2.php/cloud/capabilities
Document Length:        1220 bytes

Concurrency Level:      1
Time taken for tests:   143.307 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      25310186 bytes
HTML transferred:       12200000 bytes
Requests per second:    69.78 [#/sec] (mean)
Time per request:       14.331 [ms] (mean)
Time per request:       14.331 [ms] (mean, across all concurrent requests)
Transfer rate:          172.48 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    12   14   4.0     13     354
Waiting:       12   14   4.0     13     353
Total:         12   14   4.0     13     354

Percentage of the requests served within a certain time (ms)
  50%     13
  66%     14
  75%     14
  80%     15
  90%     17
  95%     19
  98%     21
  99%     22
 100%    354 (longest request)

$ ab -n 10000 -H "OCS-APIRequest: true" -H "Authorization: Bearer bgN7T-A4q9p-QTT5C-QcFEK-57wfc" http://localhost:8080/ocs/v2.php/apps/spreed/api/v4/room
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /ocs/v2.php/apps/spreed/api/v4/room
Document Length:        7612 bytes

Concurrency Level:      1
Time taken for tests:   260.035 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      89919180 bytes
HTML transferred:       76120000 bytes
Requests per second:    38.46 [#/sec] (mean)
Time per request:       26.003 [ms] (mean)
Time per request:       26.003 [ms] (mean, across all concurrent requests)
Transfer rate:          337.69 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    23   26   4.2     24     269
Waiting:       23   26   4.2     24     267
Total:         23   26   4.2     24     269

Percentage of the requests served within a certain time (ms)
  50%     24
  66%     26
  75%     27
  80%     28
  90%     31
  95%     33
  98%     35
  99%     37
 100%    269 (longest request)
```

Now:
```log
$ ab -n 10000 -H "OCS-APIRequest: true" http://localhost:8080/ocs/v2.php/cloud/capabilities
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /ocs/v2.php/cloud/capabilities
Document Length:        1220 bytes

Concurrency Level:      1
Time taken for tests:   147.590 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      25309812 bytes
HTML transferred:       12200000 bytes
Requests per second:    67.76 [#/sec] (mean)
Time per request:       14.759 [ms] (mean)
Time per request:       14.759 [ms] (mean, across all concurrent requests)
Transfer rate:          167.47 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    13   15   2.5     14      42
Waiting:       12   14   2.5     13      41
Total:         13   15   2.5     14      42

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     14
  75%     15
  80%     16
  90%     18
  95%     20
  98%     22
  99%     24
 100%     42 (longest request)

$ ab -n 10000 -H "OCS-APIRequest: true" -H "Authorization: Bearer bgN7T-A4q9p-QTT5C-QcFEK-57wfc" http://localhost:8080/ocs/v2.php/apps/spreed/api/v4/room
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /ocs/v2.php/apps/spreed/api/v4/room
Document Length:        7612 bytes

Concurrency Level:      1
Time taken for tests:   279.000 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      89920016 bytes
HTML transferred:       76120000 bytes
Requests per second:    35.84 [#/sec] (mean)
Time per request:       27.900 [ms] (mean)
Time per request:       27.900 [ms] (mean, across all concurrent requests)
Transfer rate:          314.74 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    24   28   5.3     26     360
Waiting:       24   27   5.2     26     359
Total:         24   28   5.3     27     360

Percentage of the requests served within a certain time (ms)
  50%     27
  66%     27
  75%     28
  80%     29
  90%     34
  95%     38
  98%     39
  99%     42
 100%    360 (longest request)
```

Depends on openapi-extractor: https: [...]

2024-01-15 14:28 UTC, provokateurin commented
No idea why OpenAPI changes (seems to use the old version?), but the openapi-extractor PR needs to be merged first anyway.

2024-01-15 14:55 UTC, nickvergessen reviewed
We discussed at another point recently that all future API work should be using OCS routes so APIs can also be used by mobile/desktop clients.

Could make this more clear by biasing the constant names.

---

Other than that, as mentioned I love the idea as it will reduce conflicts, amount of file and bring the 2 things that depend on each other closer together.

2024-01-15 14:55 UTC, nickvergessen commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
```suggestion
	 * Corresponds to the `ocs` key in routes.php
	 * @since 29.0.0
	 */
	public const TYPE_API = 'ocs';
```

2024-01-15 14:55 UTC, nickvergessen commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_INDEX = 'routes';
```suggestion
	 * Corresponds to the `routes` key in routes.php
	 * @since 29.0.0
	 */
	public const TYPE_FRONTPAGE = 'routes';
```

2024-01-15 15:03 UTC, nickvergessen commented
Since we use the Symfony router under the hood. Would there be an issue extending/using it's attribute as a base? We ship it already: https://github.com/nextcloud/3rdparty/blob/8a78b41c955bb3530a5c25f187e3dc96091dadd7/symfony/routing/Annotation/Route.php

Ref https://symfony.com/doc/current/routing.html

That could even allow us to remove more routing code in the future?

2024-01-15 15:06 UTC, provokateurin commented
> Would there be an issue extending/using it's attribute as a base?

I didn't know about this. Removing routing code sounds good, but this attribute also supports a lot of stuff that we don't support in our routing yet. I don't think that is a good idea :/

2024-01-15 15:09 UTC, provokateurin commented
(I only migrated core and one other app to ensure it works for both since they are handled a bit different in the router)

2024-01-15 16:52 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
`Route(Route::TYPE_OCS, ` is quite long, can we have `OcsRoute` and `FrontPageRoute` instead?
Also, I think there is a resource or collection feature in routes.php where you give an endpoint and it creates routes for post/put/delete/get, no? With the attribute we lose that? (May not be important though)

2024-01-15 17:24 UTC, provokateurin commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
I thought about having separate attributes, but I find it more ugly and it duplicates all everything since only the class name would be different. The only way I see is to add attributes that extend the existing attribute.

You are talking about resources, but with this PR we lose absolutely nothing. It's just an additional way to define routes and it just doesn't support resources. We could add it in the future with another attribute, but it's a feature that is rarely used so I doubt the effort is worth it.

2024-01-16 08:24 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
> You are talking about resources, but with this PR we lose absolutely nothing. It's just an additional way to define routes and it just doesn't support resources. We could add it in the future with another attribute, but it's a feature that is rarely used so I doubt the effort is worth it.

I’d really like if we use only one way of declaring routes in the end, so for me if we add this we should deprecate routes.php, otherwise it’s confusing.
But yeah I’m not that concerned for `resources` I never used it myself I just thought it was worth mentionning.

2024-01-16 08:34 UTC, provokateurin commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
There are also other cases where routes need to be defined that can not be done using attributes (e.g. PublicShareController or CORS).
I tend to agree that we should deprecate routes.php, but we should probably never remove support for it.

2024-01-16 08:46 UTC, juliushaertl commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
Would also prefer two separate attributes for readability

2024-01-16 08:48 UTC, juliushaertl commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
Or (not sure if that works with attributes) we could make the the type optional with a default to OCS, so that developers only need to specify it for frontpage contollers

2024-01-16 08:53 UTC, provokateurin commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
Default value feels dangerous, I would rather not go with that option

2024-01-16 08:54 UTC, provokateurin commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_OCS = 'ocs';
I'll add two attributes that simply extend the current attribute

2024-01-16 09:56 UTC, ChristophWurst commented
Blackfire analysis:
* /login https://blackfire.io/profiles/compare/25ecda33-f01e-46d8-a45f-774c8db2a460/graph
* /ocs/v2.php/cloud/capabilities https://blackfire.io/profiles/compare/9093963f-b6d3-43bb-b695-18a97090dadb/graph

Every comparison is primed with a simple curl to warm caches.
Every test is run with 10 samples to get more accurate numbers.

2024-01-16 10:06 UTC, provokateurin commented
@ChristophWurst thanks for the profiling. When I did my testing I found that even with 1k requests I got very different results every time. At 10k it was quite stable.

To everyone: Do you think the performance hit is acceptable or not?

2024-02-05 12:56 UTC, julien-nc requested changes
Code looks good and works fine.

The performance hit seems acceptable to me.

2024-02-05 12:59 UTC, provokateurin commented
This branch is currently broken if navigate to the root of the instance. Any other URL will work fine. I'm looking into it already.

2024-02-12 09:43 UTC, come-nc commented on lib/private/AppFramework/Routing/RouteConfig.php
> +		 * This is also save on the PHP side because class and method names collide regardless of the casing.
```suggestion
		 * This is also safe on the PHP side because class and method names collide regardless of the casing.
```

2024-02-12 09:43 UTC, come-nc commented on lib/private/AppFramework/Routing/RouteParser.php
> +		 * This is also save on the PHP side because class and method names collide regardless of the casing.
```suggestion
		 * This is also safe on the PHP side because class and method names collide regardless of the casing.
```

2024-02-12 09:43 UTC, come-nc commented on lib/private/Route/Router.php
> +						continue;
https://www.php.net/manual/en/reflectionfunctionabstract.getattributes.php

getAttributes could be used with `ReflectionAttribute::IS_INSTANCEOF` to avoid filtering ourselves?

2024-02-12 09:43 UTC, come-nc commented on lib/private/Route/Router.php
> +					$serializedRoute['name'] = substr($class->getShortName(), 0, -10) . '#' . $method->getName();
No strtolower here?

2024-02-12 09:43 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public function getVerb(): ?string {
```suggestion
	public function getVerb(): string {
```

2024-02-12 10:16 UTC, provokateurin commented on lib/private/Route/Router.php
> +					$serializedRoute['name'] = substr($class->getShortName(), 0, -10) . '#' . $method->getName();
No, those routes will be passed on to the parseRoute method which will convert it to lowercase.

2024-02-12 10:22 UTC, provokateurin commented on lib/private/Route/Router.php
> +						continue;
Works, very nice improvement :+1:

2024-02-12 10:35 UTC, provokateurin commented
CI failure is fixed, it was just another case of the casing problem with matching legacy routes.

2024-02-12 10:43 UTC, julien-nc approved these changes
:+1:

2024-02-12 13:38 UTC, come-nc approved these changes

2024-02-12 13:38 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/ApiRoute.php
> +/**
```suggestion
<?php

declare(strict_types=1);

/**
```

2024-02-12 13:38 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/FrontpageRoute.php
> +/**
```suggestion
<?php

declare(strict_types=1);

/**
```

2024-02-12 13:38 UTC, come-nc commented on lib/public/AppFramework/Http/Attribute/Route.php
> +/**
```suggestion
<?php

declare(strict_types=1);

/**
```

2024-02-15 13:57 UTC, nickvergessen commented on apps/user_status/lib/Controller/HeartbeatController.php
> +	#[ApiRoute(verb: 'PUT', url: '/api/v1/heartbeat')]
it was OCS?

2024-02-15 14:06 UTC, nickvergessen commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_API = 'ocs';
missing `@since` (Ref  https://github.com/nextcloud/server/pull/43581/files#diff-1701be546807fc8bd1d573dd5f48a53aa14647d1d8212c9f6db671f7813a304eR45-R46 )

2024-02-15 14:06 UTC, nickvergessen commented on lib/public/AppFramework/Http/Attribute/Route.php
> +	public const TYPE_FRONTPAGE = 'routes';
missing `@since`

2024-02-21 13:09 UTC, merged