enh(files): Allow to copy files into same directory
nextcloud/server pull request #42889
Opened 2024-01-17 15:28 UTC by susnux

* Bring back: #10825 
* Resolves https://github.com/nextcloud/server/issues/18846
* Resolves https://github.com/nextcloud/server/issues/10441
* Resolves: https://github.com/nextcloud/server/issues/41768

## Summary

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-18 11:33 UTC, skjnldsv requested changes

2024-01-18 11:33 UTC, skjnldsv commented on apps/files/src/actions/moveOrCopyAction.ts
> +	const makeUniqueName = (node: Node, otherNodes: Node[]|FileStat[]) => {
We already have a method and pattern for that :)
https://github.com/nextcloud/server/blob/9f157d7f8030a1f7a9455be10810ee11f1cb15f0/apps/files/src/newMenu/newFolder.ts#L59-L67

2024-01-18 12:58 UTC, skjnldsv commented on apps/files/src/actions/moveOrCopyAction.ts
> +	const makeUniqueName = (node: Node, otherNodes: Node[]|FileStat[]) => {
Ah, I have no preferences, I used the old behavior, which was just the number! Please adjust the method then so we have whatever the design team approved! :+1:

2024-01-18 13:53 UTC, artonge commented on apps/files/src/actions/moveOrCopyAction.ts
> +	if (destination.path.startsWith(node.path) && destination.path !== node.path) {
Does it prevent moving a folder into itself? Not sure how it could happen, but still.
```js
destination.path = "/a/b"
node.path = "/a/b"

destination.path.startsWith(node.path) === true
(destination.path !== node.path) === false
```

I think the following would work:
```suggestion
	if (destination.path.startsWith(node.path) && (destination.path !== node.path || node.type === Folder)) {
```

But warning, I might simply be confused.

2024-01-18 13:53 UTC, artonge commented on apps/files/src/actions/moveOrCopyAction.ts
> +				// If we do not allow overwriting than find an unique name
```suggestion
				// If we do not allow overwriting then find an unique name
```

2024-01-18 17:22 UTC, susnux commented on apps/files/src/actions/moveOrCopyAction.ts
> +	if (destination.path.startsWith(node.path) && destination.path !== node.path) {
No the whole `&& ...` can be dropped.

Because if your target folder is `/foo/bar` then ofcourse I can not move `/foo` into it, but I can also not move `/foo/bar` into it, and I am even not allowed to copy it into itself, because if both have the same path I try:
`/foo/bar` -> `/foo/bar` leading to `/foo/bar/bar` which is also not allowed.

To clone that directory you would need to pass `/foo` as the destination and then the check is ok as it was.

2024-01-18 17:25 UTC, skjnldsv commented on apps/files/src/actions/moveOrCopyAction.ts
> +	const makeUniqueName = (node: Node, otherNodes: Node[]|FileStat[]) => {
Perfect!!  Thanks @susnux :)

2024-01-18 18:22 UTC, artonge approved these changes

2024-01-19 14:33 UTC, emoral435 commented on apps/files/src/utils/fileUtils.ts
> +}
Seems like if you move folders with no extension name, getUniqueName clips the last letter from the file when you append the suffix to the end of the new file name:

![image](https://github.com/nextcloud/server/assets/110193237/c424f62f-0043-4a67-b197-9051ac82192f)

Probably due to files not having extensions, so might have to add a check for that for files

2024-01-19 14:34 UTC, emoral435 requested changes
Just needs the file part and it LGTM!!

2024-01-19 19:26 UTC, susnux commented
@emoral435 can you check again if that still happens for you?

2024-01-19 19:46 UTC, emoral435 approved these changes
Checked, and it works perfectly for me now :) sorry for being nitpicky!

2024-01-19 20:05 UTC, emoral435 commented
@skjnldsv before we merge this in, it still says that you have requested changes. I'm 99% sure your fine with this, but just to make sure, all the changes now are fine by you, correct? :)

2024-01-20 11:32 UTC, skjnldsv approved these changes

2024-01-20 14:56 UTC, skjnldsv commented
/backport eaad30c b29c0cc a289fdd to stable28

2024-01-20 15:05 UTC, merged