fix(userstatus): CALL status should overwrite MEETING status
nextcloud/server pull request #42896
Opened 2024-01-17 17:29 UTC by miaulalala

* Resolves: https://github.com/nextcloud/server/issues/42451

## Summary

When a meeting status is set, the call status will not be written if a backup exists. The code now shortcuts this single scenario and overwrites the existing status "In a meeting" with the "In a call" status irregardless of a backup status, since both are automated status and will revert to the backup after their respective automation has run.

This also fixes the issue of having a call while "in a meeting" is set, leaving the call, and the meeting status not coming back after.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-17 17:30 UTC, miaulalala commented
/backport to stable28

2024-01-19 12:33 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Status/StatusService.php
> +		if($currentStatus !== null && $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
what would be messed up?

2024-01-19 13:16 UTC, miaulalala commented on apps/dav/lib/CalDAV/Status/StatusService.php
> +		if($currentStatus !== null && $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
I've had that in my local env. The timestamp is updated, thus the DTSTART is lower than the timestamp - which leads to a reset because no event is found (which is wrong).

2024-01-24 12:48 UTC, ChristophWurst commented on apps/user_status/lib/Service/StatusService.php
> +		}
:+1: makes sense

2024-01-25 05:41 UTC, nickvergessen requested changes

2024-01-25 05:41 UTC, nickvergessen commented on apps/dav/lib/CalDAV/Status/StatusService.php
> +		if($currentStatus !== null && $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
One of the unit tests fails, so I wonder if the test is actually right and the code here wrong?
Should it be:
```suggestion
		// Only update the status if it's neccesary otherwise we mess up the timestamp
		if ($currentStatus === null || $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
```

Otherwise the event status will only be set, when you had any status before?

2024-01-25 10:09 UTC, nickvergessen approved these changes

2024-01-25 10:10 UTC, nickvergessen commented
/backport! to stable28

2024-01-25 11:25 UTC, ChristophWurst approved these changes

2024-01-25 11:25 UTC, merged

2024-01-25 11:29 UTC, nickvergessen commented
Already done in https://github.com/nextcloud/server/pull/43107