[wip] improve index on appconfig
nextcloud/server pull request #42903
Opened 2024-01-18 01:38 UTC by ArtificialOwl

follow-up of #42820

- [x] removing `appconfig_configkey_key` index on single field configkey as there is no search on this field
- [x] index on `lazy`
- [ ] should we remove `appconfig_appid_key` as we already have the pair `appid`+`configkey` as primary key ?

2024-01-23 10:58 UTC, artonge approved these changes

2024-01-23 13:32 UTC, nickvergessen commented on core/Migrations/Version29000Date20231126110901.php
> +		$changed = false;
this migration executed already. You can not queue another one before it neither should you modify it.
Please generate 2 new migrations. If the changed from this here should be skipped, you can comment out the code, but you need another migration making sure the stuff is removed and then another migration to add the things again with the correct type.

2024-01-23 15:06 UTC, ArtificialOwl commented on core/Migrations/Version29000Date20231126110901.php
> +		$changed = false;
I have created a [core/Migrations/Version29000Date20231126110900.php](https://github.com/nextcloud/server/pull/42903/files#diff-679f3baf9ad965a15ccb3ed83f05b6230389dd9f70b0fa7c4b6e650cb5957eee) that drops erroneous field `lazy` so we can switch to integer

2024-01-23 17:57 UTC, nickvergessen requested changes

2024-01-23 17:57 UTC, nickvergessen commented on core/Migrations/Version28000Date20231126110901.php
> +class Version28000Date20231126110901 extends SimpleMigrationStep {
```suggestion
class Version29000Date20240123... extends SimpleMigrationStep {
```
Please generate a proper new migration that executes **after** the already existing one, so there is a proper stream line of migrations and an easy traceable DB state of instanced running dailies or git.

2024-01-23 17:57 UTC, nickvergessen commented on core/Migrations/Version28000Date20231126110901.php
> +		}
```suggestion
```
Don't check against pre requirements.

2024-01-23 17:57 UTC, nickvergessen commented on core/Migrations/Version29000Date20231126110900.php
> +class Version29000Date20231126110900 extends SimpleMigrationStep {
```suggestion
class Version29000Date20240123... extends SimpleMigrationStep {
```
As above, this should have a later version and timestamp to have a linear DB state

2024-01-23 17:57 UTC, nickvergessen commented on core/Migrations/Version29000Date20231126110901.php
> +		$changed = false;
The changes in this file should still be reverted. You can comment out the lazy field and wrong indices, but only comment out, not do any code level changes.

2024-01-23 18:47 UTC, nickvergessen commented on core/Migrations/Version28000Date20231126110901.php
> +class Version28000Date20231126110901 extends SimpleMigrationStep {
Okay I see only now that you changed the version number in the backport. That should not have happened.

Anyway, we should still have the new and fixing migration with a 2401... Timestamp at the end of the chain and the 28...2311 migrations both unchanged from previous PRs.

2024-01-24 20:15 UTC, ArtificialOwl commented
I have estimated that a full squash+rebase was a lot better as I reverted a lot of code:

- upstream of #42820 to master
- commenting most of the code from `Version28000Date20231126110901` upstream of #42820 to master (+ explication)
- commenting most of the code of previous migration step `Version28000Date20231126110901 ` (+ explication)
- new migration step `Version29000Date20240124132201` to remove previous boolean `lazy` field and related indexes, fix `type` to **unsigned** and remove useless index on `configkey`.
- new migration step `Version29000Date20240124132202` to create a **smallint** `lazy` field.
- keep migration fall back on reading app config values to keep upgrade compatibility with versions prior to 28.0.2
- switching write/read request to `lazy` field from managing a **boolean** to managing a **smallint**
- remove `lazy` from select list if known when calling `loadConfig()`

2024-01-25 11:32 UTC, nickvergessen approved these changes

2024-01-25 11:32 UTC, nickvergessen commented on core/Migrations/Version29000Date20240124132201.php
> + * Create new fields for type and lazy loading in appconfig for the new IAppConfig API.
```suggestion
 * Create new column for type and remove previous lazy column in appconfig (will be recreated by Version29000Date20240124132202) for the new IAppConfig API.
```

2024-01-25 11:32 UTC, nickvergessen commented on core/Migrations/Version29000Date20240124132202.php
> + * Create new fields for type and lazy loading in appconfig for the new IAppConfig API.
```suggestion
 * Create new column and index for lazy loading in appconfig for the new IAppConfig API.
```

2024-01-26 10:53 UTC, merged