fix(files): fixed home aria-label and desc logic
nextcloud/server pull request #42950
Opened 2024-01-18 23:49 UTC by emoral435

* Resolves: #41895 
## Summary
The home section of the breadcrumbs was a component supplied by Vue. Since it was supplied by Vue, it does not use our custom translator, so it seems as if it's aria-label was never translated. I also cleaned up the aria-description logic a bit!

## Screenshots for the new changes
<img width="992" alt="image" src="https://github.com/nextcloud/server/assets/110193237/18458b27-3944-4346-a637-e7257c3c10d3">

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-18 23:54 UTC, ShGKme requested changes

2024-01-18 23:54 UTC, ShGKme commented on apps/files/src/components/BreadCrumbs.vue
> +				<Home :size="20" :aria-label="t('files', 'Home')"/>
The label should be on the interactive element itself — on the button. `NcBreadbrumb` sets it via the `name` prop. So the issue is probably in the data, where `name` "Home" is not translated here, in the `section` object.

2024-01-19 00:29 UTC, emoral435 commented
Woops - pushed too soon. Will erase this comment once I find it, but the translation might be needed from another file etc. Will look into this!

2024-01-19 00:52 UTC, emoral435 commented on apps/files/src/components/BreadCrumbs.vue
> +				<Home :size="20" :aria-label="t('files', 'Home')"/>
That's odd. I checked, and when the `name` member in the `sections` object always will have the 'home' section translated:
<img width="524" alt="image" src="https://github.com/nextcloud/server/assets/110193237/60a6bb2a-de1f-4377-a863-751eb7520124">
So the fact that we even see the name 'Home' means that it should be translated, no?

2024-01-19 01:54 UTC, Pytal commented
I just checked on master and it is already translated correctly 💡

![image](https://github.com/nextcloud/server/assets/24800714/610935d0-18ef-4ba8-b190-f89fbe7af7d2)

2024-01-19 01:57 UTC, Pytal commented
Seems @szaimen checked with German where it is not translated so no issue code-wise

2024-01-19 11:12 UTC, szaimen commented
> Seems @szaimen checked with German where it is not translated so no issue code-wise

indeed, looks like it...

2024-01-19 13:40 UTC, emoral435 commented
@Pytal @ShGKme I still propose that this PR get merged. Upon checking the master branch, it appears that the last breadcrumb doesn't have that aria-description that we proposed to keep :/

![image](https://github.com/nextcloud/server/assets/110193237/ba1839fc-a7db-4ea2-af71-f408539b4eed)

This PR still fixes that! Updated the main summary for the PR though

2024-01-19 18:49 UTC, Pytal approved these changes

2024-01-19 18:56 UTC, emoral435 commented on apps/files/src/components/BreadCrumbs.vue
> +				<Home :size="20" :aria-label="t('files', 'Home')"/>
Turns out it was just due to the fact that the German translation is still untranslated, but the PR still holds value :)

2024-01-19 18:59 UTC, emoral435 commented
/compile /

2024-01-19 19:00 UTC, emoral435 commented
/skjnldsv-backport ea765cfdd35d7f935b82b9d4dd438015a1d9e7e0 to stable28

2024-01-20 12:03 UTC, skjnldsv commented
/backport to stable28

2024-01-20 12:05 UTC, skjnldsv approved these changes

2024-01-20 12:21 UTC, merged