Expose dashboard layout and statuses API
nextcloud/server pull request #42973
Opened 2024-01-19 22:27 UTC by provokateurin

## Summary

I cleaned up the format that was used by the API, migrated the existing endpoints to OCS (the LayoutApiController never had a route so it was not possible to update the layout or statuses before) and added endpoints to get the current layout and statuses.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-03 14:50 UTC, julien-nc requested changes
Looks good. A few minor change suggestions.

2024-05-03 14:50 UTC, julien-nc commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboardApi#updateStatuses', 'url' => '/statuses', 'verb' => 'POST'],
Don't you wanna use the new routing system here?

2024-05-03 14:50 UTC, julien-nc commented on apps/dashboard/src/DashboardApp.vue
> +			this.enabledStatuses.push(app);
```suggestion
			this.enabledStatuses.push(app)
```

2024-05-03 14:50 UTC, julien-nc commented on apps/dashboard/src/DashboardApp.vue
> +			i = this.registeredStatus.findIndex((s) => s === app)
```suggestion
			const i = this.enabledStatuses.findIndex((s) => s === app)
			if (i !== -1) {
				this.enabledStatuses.splice(i, 1)
			}
			const j = this.registeredStatus.findIndex((s) => s === app)
```
And adjust the rest of the method.
I had to read it twice to realize why i was not a const. Slightly clearer like this IMO. We can afford declaring one more integer.

2024-05-03 15:34 UTC, provokateurin commented on apps/dashboard/appinfo/routes.php
> +		['name' => 'dashboardApi#updateStatuses', 'url' => '/statuses', 'verb' => 'POST'],
Sure why not, this PR was written before it was in place.

2024-05-05 13:58 UTC, julien-nc approved these changes
:+1:

2024-05-10 06:34 UTC, st3iny approved these changes
Tested and works.

Nit: I would prefer the new routes to be `/api/v1/...` as they are the first versions of the respective APIs.

2024-05-10 07:30 UTC, provokateurin commented
Yeah I first had them as v1, but I'm not sure what makes most sense here. To me it would feel a bit weird that older versions support v2 but not all of the updated v1, so I went with v3 instead :woman_shrugging:

2024-05-10 07:45 UTC, provokateurin commented
Just a rebase to fix CI

2024-05-10 08:21 UTC, merged