fix(files): Make the navigation reactive to view changes and show also sub routes as active
nextcloud/server pull request #42992
Opened 2024-01-20 23:56 UTC by susnux

## Summary
This resolves two issues with the files app navigation:

1. The navigation was not reactive as the `currentView` is a computed value but all source objects are **not** reactive (`@nextcloud/files` Navigation). So to ensure changes to the navigation can be detected the object is made observable.
2. Removed the `exact` prop on the app navigation as otherwise it will not show `all files` active if you visited a file like `apps/files/files/123`.
3. Minor type fixes in `Navigation.vue`

### Screenshots
#### Before
Pay attention that while the navigation changes the file list does not. Also not that no navigation is active within a subfolder.

https://github.com/nextcloud/server/assets/1855448/2f8f4447-5ca2-45ef-b4c9-1fdd23e9321e

#### After
See that navigation works and the file list is updated + also in subfolders the navigation is kept active.

https://github.com/nextcloud/server/assets/1855448/a25aa9fa-7769-477c-9dba-661aa93db49f

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-20 23:57 UTC, susnux commented
/backport to stable28

2024-01-21 08:46 UTC, skjnldsv commented on apps/files/src/views/Navigation.vue
> +				allow-collapse
Feels really weird to me :thinking: 
Now it looks like an html attribute instead. I would have kept it as a bool tbh

2024-01-21 08:46 UTC, skjnldsv submitted a review, later dismissed
> Removed the exact prop on the app navigation as otherwise it will not show all files active if you visited a file like apps/files/files/123.

Now it does this, which is a regression.
I think we need our custom `exact` checker :thinking: 
![image](https://github.com/nextcloud/server/assets/14975046/af75b6ed-3d34-4ff0-bc76-e37394919b40)

2024-01-21 15:43 UTC, ShGKme commented on apps/files/src/views/Navigation.vue
> +				allow-collapse
IMO, it is a Vue-way, following the HTML standard and being short philosophy.

Like in HTML, Vue proffers us to keep the same HTML-like experience in templates with components.

```html
<input required="required" disabled="disabled" />
<!-- used as -->
<input required disabled />
<!-- same in components -->
<NcInput required disabled />
```

There are even ESLint rules for this, though uncategorized.

https://eslint.vuejs.org/rules/prefer-true-attribute-shorthand.html

> Now it looks like an html attribute instead

I think that there is no such meaning in binding. `v-bind` only means that the value is a dynamic, JS expression, applied to both prop and HTML attributes. And at the same time not having binding like `name="staticString"` doesn't mean that it is an HTML attribute and not a prop.

https://eslint.vuejs.org/rules/no-useless-v-bind.html

2024-01-21 18:10 UTC, susnux commented
> Now it does this, which is a regression.
> I think we need our custom `exact` checker 🤔

I do not think we need such a complex solution, I think we can go for the moment with just checking the view we are in.
This fixes the initial issue and will not lead to that regression.

I pushed a fix that only disables `exact` for the files view.

We might later add a `exact` property to the View entry itself to let them decide, but thats up for discussion in a future iteration(?).

2024-01-21 19:08 UTC, susnux commented
Looks like this now:

https://github.com/nextcloud/server/assets/1855448/dba75335-405e-44c6-a849-c10e7af14b0a

2024-01-22 14:07 UTC, emoral435 commented on apps/files/lib/Activity/Helper.php
> +	public function getFavoriteFilePaths($user) {
nitpick: here, for style consistency between functions in this file, shouldn't we have the paremeter (user, in this case) have its type declared? and its return type as well. Bit nitpicky on my part though

`($user)` => `(string $user) : array`

2024-01-22 14:17 UTC, susnux commented on apps/files/lib/Activity/Helper.php
> +	public function getFavoriteFilePaths($user) {
makes sense :)

2024-01-22 14:43 UTC, emoral435 reviewed
Overall, love this PR. I'm just getting assigned to more files-related issues for the spring sprint, and my advice was to ping you whenever I have a question or draft a PR, so seeing your code genuinely supports my growth here, and I will def ping you to review my PR's because the code quality here is really good. Just a few comments and nitpicks and this is perfect, I tried it on my local dev env and it also works :)

2024-01-22 14:43 UTC, emoral435 commented on apps/files/src/views/favorites.ts
> +export const generateFolderView = function(folder: IFavoriteFolder, index = 0): View {
also another nitpick - since this gets the favorite folders, do you think that we should name the function something more descriptive? Something along the lines of `generateFavoriteFolderView`?

2024-01-22 14:43 UTC, emoral435 commented on apps/files/src/views/Navigation.vue
> +					list[view.parent!] = [...(list[view.parent!] || []), view]
question: ignore if this is not applicable, but are we sure that each view does have a parent? Is it possible that the view could have no parent, for instance, if it was the top level file path (for instance, the view you get when you immediately open `All Files`)?

If this is not applicable, feel free to ignore this :)

2024-01-22 14:43 UTC, emoral435 commented on apps/files/src/views/Navigation.vue
> +		useExactRouteMatching(view: View) {
addition: since this returns a bool, for code consistancy, `useExactRouteMatching(view: View): bool` makes sense here

2024-01-22 16:46 UTC, skjnldsv commented on apps/files/src/views/Navigation.vue
> +				allow-collapse
Agree to disagree then :)

2024-01-22 19:44 UTC, susnux commented on apps/files/src/views/Navigation.vue
> +				allow-collapse
Agree to revert this as unrelated then

2024-01-24 08:52 UTC, skjnldsv commented
What I don't get is that it worked before.
v28.0.0 and v28.0.1 doesn't have that reactivity issue.

What broke it in between?

2024-01-24 12:11 UTC, susnux commented on apps/files/src/views/Navigation.vue
> +					list[view.parent!] = [...(list[view.parent!] || []), view]
See two lines above: `.filter(view => !!view.parent)` 

After that we are sure :)

2024-01-24 12:13 UTC, susnux commented on apps/files/src/views/Navigation.vue
> +		useExactRouteMatching(view: View) {
It is inferred automatically (your IDE show that it is boolean) but yes be a bit more explicit :)

2024-01-24 12:20 UTC, susnux commented
> What I don't get is that it worked before.

I wonder how it worked before because that object was never made reactive?

2024-01-24 12:36 UTC, skjnldsv commented
> I wonder how it worked before because that object was never made reactive?

It's a key from an object, which is passed as a reference, it should be reactive by default.
Something changed with the `2.7.16` update, feel free to try it yourself :shrug:

2024-01-24 13:11 UTC, susnux commented
> It's a value from an object, which is passed as a reference, it should be reactive by default.

How should it be reactive? As far as I know Vue 2 only the `data` object is made reactive on instantiation by adding `getters` and `setters` for their properties. But not objects which you assign to the vue instance like the `$navigation`?

2024-01-24 13:17 UTC, ShGKme commented
> > It's a value from an object, which is passed as a reference, it should be reactive by default.
> 
> How should it be reactive? As far as I know Vue 2 only the `data` object is made reactive on instantiation by adding `getters` and `setters` for their properties. But not objects which you assign to the vue instance like the `$navigation`?

Also any object that was assigned to another reactive object property. So if navigation was assigned to the property of another reactive object anywhere, it also becomes reactive.

A guess - maybe we have components (libs) with different Vue versions built-in. I just found that computed from one component is not reactive in another in Text after provide, but it works in other places.

2024-01-24 13:31 UTC, susnux commented
Checked that but our libraries externalize `vue` and in server I checked that there is only one `vue` version used for building.

2024-01-24 13:33 UTC, ShGKme commented
> Checked that but our libraries externalize `vue` and in server I checked that there is only one `vue` version used for building.

I always have a lot of `"You are running Vue in development mode."` messages in the console. One Vue package instance makes only one log...

2024-01-24 13:39 UTC, ShGKme commented
At least apps like tab apps are separated apps with Vue inside.

2024-01-24 14:39 UTC, emoral435 approved these changes
Outside of the weird regression found by @skjnldsv , this PR looks good to me! :)

2024-01-24 15:56 UTC, skjnldsv commented
> So if navigation was assigned to the property of another reactive object anywhere, it also becomes reactive.

Yep!
It will make any object reactive if you pass the reference somewhere.
We use it all over the place in sidebar or those old js APIs that worked alongside vue those last few years :shrug:

2024-01-24 17:11 UTC, skjnldsv approved these changes

2024-01-24 21:46 UTC, susnux commented
/compile

2024-01-24 21:46 UTC, susnux commented
Well but does this work with different Vue versions?
Because the `Navigation` is kept globally, so possible different (external) apps can access it and you have no control over the vue version used.

(And I think completely broken when using Vue 3 which uses Proxy thus the original object is never modified).

2024-01-24 21:47 UTC, susnux commented
/backport to stable28

2024-01-25 01:36 UTC, ShGKme reviewed
I have `/Foo/Bar/Bar` folders. `Foo` and `Bar` are favorite. before both were listed, now only Bar... Is it intended change?

Before | After
---|---
![image](https://github.com/nextcloud/server/assets/25978914/8c2c3268-ed2d-4130-8013-efe5ac9006f1) | ![image](https://github.com/nextcloud/server/assets/25978914/de1e6327-9867-4102-bfe4-6913f53c7aea)

2024-01-25 01:36 UTC, ShGKme commented on apps/files/src/main.ts
> +const Navigation = Vue.observable(getNavigation())
Random thought, wouldn't it be better to return reactive navigation from the `getNavigation`?

2024-01-25 01:36 UTC, ShGKme commented on apps/files/src/views/favorites.ts
> +		const newFavoriteFolder = { path: node.path, fileid: node.fileid! } as IFavoriteFolder
```suggestion
		const newFavoriteFolder: IFavoriteFolder = { path: node.path, fileid: node.fileid! }
```

2024-01-25 02:07 UTC, susnux commented
> I have `/Foo/Bar/Bar` folders. `Foo` and `Bar` are favorite. before both were listed, now only Bar... Is it intended change?

@ShGKme Resolved, a typo in the PHP.

2024-01-25 02:44 UTC, ShGKme requested changes
I have `/foo/bar/` both favorite. Initially "All favorites" is open

![image](https://github.com/nextcloud/server/assets/25978914/92a9dee9-0ae9-4fe0-a608-83f6d7bb7bb4)

Depending on how I go to the `bar`, I have different result and selected button on the navigation.

If I go from the files list (All favorites is open), I see no content.

Click from the favorites list | Click from the files list
---|---
![image](https://github.com/nextcloud/server/assets/25978914/4ef12bd2-1ca8-4fb5-8ea2-43be8200268c) | ![image](https://github.com/nextcloud/server/assets/25978914/bc611a9f-6d46-4db3-a627-0a9dc76b284d)

2024-01-25 11:40 UTC, susnux commented
> Depending on how I go to the `bar`, I have different result and selected button on the navigation.

Resolved this

https://github.com/nextcloud/server/assets/1855448/f273ec43-4cbb-4b8c-81ad-4ddb77726035

2024-01-25 12:50 UTC, ShGKme commented
> Resolved this

It still doesn't fully work for me. It fixes the navigation active, but the content is not displayed.

Try to add some content to the "Bar" folder. It must be listed then Favorites/Bar is open from the navigation.

2024-01-25 13:45 UTC, susnux commented
I think it is unrelated, but another bug. This also happens on master, the problem here is that `dir` is set to `/bar` while it should be `/foo/bar`

2024-01-25 14:09 UTC, susnux commented
@ShGKme pushed a commit that fixes also that issue, you can try again :)

2024-01-25 15:44 UTC, ShGKme approved these changes
Works now 🥳

2024-01-25 15:47 UTC, merged