Fix/files new menu
nextcloud/server pull request #42993
Opened 2024-01-21 00:54 UTC by susnux

* Resolves: #42097
* Resolves: #41260

## Summary
Most important: This brings back the ability to select a folder name before creating it - this is required for shares where you can create but not update.

This feature is reused for all new-menu entries, meaning also for new template folder and new files like new text files if **text** app is installed.

Moreover this fixes:
* The file name is not editable: see above
* The file entry is not highlighted: This was already possible or planned as the styles were available but the class was not assigned, this is now done.
* The file does not open automatically after confirming the new name: This was more tricky as files does not provide e.g. `files:node:open` but opening a file is left as a action provided by the viewer app. So this is now handled by searching for the *view* action and if not available then at least open the sidebar for more details.

### New workflow (screen cast)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-21 00:55 UTC, susnux commented
/backport to stable28

2024-01-21 08:57 UTC, skjnldsv requested changes, later dismissed
Very very clean!!! :rocket: 
Aside from the `files:node:focus`, looks good to me! Thank you so much :)

2024-01-21 08:57 UTC, skjnldsv commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
Not acceptable imho, an event is not meant to trigger a reaction like a focus.

If you want to focus the node, you need to change the URL and provide a new fileId, the filelist will scroll it in the current view
https://github.com/nextcloud/server/blob/3f77b543e3ee55177f87ca845d31bb7d2776d467/apps/files/src/components/FilesListVirtual.vue#L234-L242
https://github.com/nextcloud/server/blob/b1a9017f5fbe15a6fe3ccb592ff000661ce2e3ad/apps/files/src/components/VirtualList.vue#L245-L251

I would say the `scrollTo` needs to be updated then so it also focuses :)

2024-01-21 18:12 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
> an event is not meant to trigger a reaction like a focus.

But we have an event for opening the sidebar?

2024-01-21 19:18 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
I mean I could drop all the event related parts, but then you might help me understanding why `openfile=true` only works if you reload the page (hard reload) with that in the query. While when only adding it through the router is does not work.

2024-01-22 16:37 UTC, skjnldsv commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
> But we have an event for opening the sidebar?

Because it was poorly done to have a simpler relationship with legacy code iirc

2024-01-22 16:39 UTC, skjnldsv commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
> you might help me understanding why `openfile=true` only works if you reload the page (hard reload) with that in the query.

Because it's only provided by the backend via initialstate.
If you want reactivity to it, you need to implement it on the front too, similarely to the fileid change watched that scrolls to the file

2024-01-29 15:13 UTC, susnux commented on apps/files/src/views/FilesList.vue
> +		subscribe('files:node:focus', this.onFocusNode)
@skjnldsv I pushed a commit implementing reactive `openfile` instead of that event, please review :)

2024-01-31 12:21 UTC, skjnldsv approved these changes
Other than the highlight simplification we talked about, I'm good for this :+1: 
Awesome work!

Btw, related issue: https://github.com/nextcloud/server/issues/21609

2024-01-31 19:17 UTC, susnux commented
> Other than the highlight simplification we talked about, I'm good for this 👍

Removed that :+1:

2024-02-08 21:34 UTC, AndyScherzinger approved these changes

2024-02-08 21:34 UTC, AndyScherzinger commented
:shipit:

2024-02-08 21:40 UTC, nickvergessen commented
Doesn't seem to work for Text files,
but works nicely for folders <3

2024-02-09 01:23 UTC, merged

2024-03-01 16:16 UTC, Luncheon3462 commented
Not fixed in 28.0.3 While I can create a file name, the document does not open.   Correct behavior is creating a file name and then the document should open automatically.   NC27 works fine/appropriately.

2024-03-01 16:59 UTC, susnux commented
If you do not have any templates, this indeed does not work. Somehow I missed on of the `node:focus` events when removing them.