feat(core): Expose the confirm password endpoint
nextcloud/server pull request #43000
Opened 2024-01-21 19:32 UTC by provokateurin

## Summary

This allows non-web clients to confirm the password in order to use endpoints that require it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-21 20:17 UTC, nickvergessen requested changes

2024-01-21 20:17 UTC, nickvergessen commented on core/Controller/LoginController.php
> -	 * @license GNU AGPL version 3 or any later version
You can not change the license

2024-01-21 20:20 UTC, provokateurin commented on core/Controller/LoginController.php
> -	 * @license GNU AGPL version 3 or any later version
But the license is already in the header? I thought this was a copy paste mistake :woman_shrugging: Does it even make sense to have a specific license for a part of the code in a file (especially since the licenses are the same)?

2024-01-22 09:09 UTC, come-nc approved these changes

2024-01-22 09:40 UTC, nickvergessen requested changes
Sending auth data should pass the password check:
https://github.com/nextcloud/server/blob/7f2fdd884354a1ab2f07228d7b1c3839139c4378/lib/private/User/Session.php#L605

The problem is you are sending auth + cookies, so we use the cookies only and the line above is never ran. We should fix the PasswordConfirmMiddleware to check if auth data was provided with the request.

2024-01-22 16:41 UTC, provokateurin commented
My testing confirms:
- Basic auth without cookies works
- Bearer auth never works (regardless of cookies)

2024-01-22 16:41 UTC, closed without merging

2024-02-20 07:05 UTC, provokateurin commented
After the discussions in https://github.com/nextcloud/server/pull/43034 we came to the conclusion that this PR makes more sense and is less susceptible to any additional security holes the other PR could open up.

2024-02-20 07:06 UTC, provokateurin commented
Bleh should have re-opened before pushing, will create a new PR