fix: update re-share if shared-by user has been revoked
nextcloud/server pull request #43025
Opened 2024-01-22 14:24 UTC by luka-nextcloud

* Resolves: #42407

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-29 14:02 UTC, luka-nextcloud commented on lib/private/Share20/Manager.php
> +			}
I don't think deleting all shares of whole re-share hierarchy is a good approach. It might cause performance issue if sharing item is a folder that has a lot of children. So, I will come up with another fix.

2024-02-05 18:29 UTC, luka-nextcloud commented
@artonge I've updated as you requested, please check again.

2024-02-06 10:26 UTC, artonge reviewed
Can you add comments to clarify what each `if` group does?

I am also wondering if we could find this shares with the following query:

```sql
SELECT
	f.fileid,
	f.path,
	f.storage,
	s.id as share_id,
	s.uid_owner as share_owner,
	s.uid_initiator as share_initiator,
	s.share_with as share_recipient
FROM
	oc_filecache f
	JOIN oc_share s ON f.fileid = s.file_source
	AND s.uid_initiator NOT IN (
		SELECT
			user_id
		FROM
			oc_mounts m
		WHERE
			f.storage = m.storage_id
	)
```

If so, then we could have a background job to remove them every hour or so like https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/DeleteOrphanedSharesJob.php, which might be easier than the current solution.

2024-02-06 19:08 UTC, luka-nextcloud commented
> Can you add comments to clarify what each `if` group does?
> 
> I am also wondering if we could find this shares with the following query:
> 
> ```sql
> SELECT
> 	f.fileid,
> 	f.path,
> 	f.storage,
> 	s.id as share_id,
> 	s.uid_owner as share_owner,
> 	s.uid_initiator as share_initiator,
> 	s.share_with as share_recipient
> FROM
> 	oc_filecache f
> 	JOIN oc_share s ON f.fileid = s.file_source
> 	AND s.uid_initiator NOT IN (
> 		SELECT
> 			user_id
> 		FROM
> 			oc_mounts m
> 		WHERE
> 			f.storage = m.storage_id
> 	)
> ```
> 
> If so, then we could have a background job to remove them every hour or so like https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/DeleteOrphanedSharesJob.php, which might be easier than the current solution.

@artonge It only works if the shared-by user refreshes his files list after his share has revoked. So, I don't think this query would do the job.

2024-06-03 07:50 UTC, come-nc commented on apps/files_sharing/lib/Command/FixBrokenShares.php
> + */
```suggestion
/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
```

2024-06-03 07:50 UTC, come-nc commented on apps/files_sharing/lib/Command/FixBrokenShares.php
> +	}
```suggestion
	public function __construct(
		private OrphanHelper $orphanHelper,
	) {
		parent::__construct();
	}
```

2024-06-03 07:50 UTC, come-nc commented on apps/files_sharing/lib/Command/FixBrokenShares.php
> +		return 0;
```suggestion
		return static::SUCCESS;
```

2024-06-03 07:50 UTC, come-nc commented on apps/files_sharing/lib/OrphanHelper.php
> +				return $mount->getUser()->getUID();
Can you explain the logic in a comment here?
A file can have several owners and only one of them will be returned randomly, right? We may end up with less permissions than expected, no?

2024-06-06 09:46 UTC, come-nc requested changes

2024-06-06 09:46 UTC, come-nc commented on apps/files_sharing/lib/OrphanHelper.php
> +			->where($query->expr()->eq('id', $query->createNamedParameter($shareId)));
```suggestion
			->where($query->expr()->eq('id', $query->createNamedParameter($shareId, IQueryBuilder::PARAM_INT)));
```

2024-06-06 09:46 UTC, come-nc commented on apps/files_sharing/lib/Command/FixBrokenShares.php
> +			if (!empty($owner)) {
```suggestion
			if ($owner !== null) {
```
`'0'` is a valid userid.

2024-06-06 09:46 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		}
This checks the user does not have access to the same file/folder through another share, right?

But it does not check the same thing for subfiles/subfolders, while still deleting shares of children below.

This PR should contains tests showing behavior in different scenarios where shares should be deleted or should not to validate that it behaves correctly.

2024-06-17 18:12 UTC, luka-nextcloud commented
@come-nc Could you please review again? All checks have passed now.

2024-06-20 14:49 UTC, come-nc commented on apps/files_sharing/lib/OrphanHelper.php
> +		IUserMountCache $userMountCache
```suggestion
		IUserMountCache $userMountCache,
```

2024-06-20 14:49 UTC, come-nc commented on lib/private/Share20/Manager.php
> +					$this->deleteShare($child);
For subfiles you did not check that the user still has access to it, I think?

2024-06-20 14:49 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		}
Instead of doing all this to check if the user still has access to the file or not, does it not make more sense to directly check if the user has access to the file? We must have some tooling for that, no?

2024-06-21 11:42 UTC, luka-nextcloud commented on lib/private/Share20/Manager.php
> +		}
@come-nc  I cannot find another way to check this logic. Could you provide some suggestions?

2024-06-24 09:05 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		}
Get the user folder of the user and use `getFirstNodeById` would work I think.

2024-06-24 09:09 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		}
(Note that this would only work after deleting the share)

2024-06-24 15:30 UTC, come-nc commented
@luka-nextcloud After talking with Robin, actually the ownership transfer is supposed to update the owner of the share so there should be no problem in the first place?

2024-06-24 17:30 UTC, luka-nextcloud commented
@come-nc Does it mean that these changes are enough for this issue?

![image](https://github.com/nextcloud/server/assets/89908051/94760fcc-286a-4f7d-9e54-400fddca3a75)

![image](https://github.com/nextcloud/server/assets/89908051/17c0a200-7787-412d-9281-8c4f31f0dce8)

2024-06-25 08:37 UTC, come-nc commented
> @come-nc Does it mean that these changes are enough for this issue?
> 
> ![image](https://private-user-images.githubusercontent.com/89908051/342436323-94760fcc-286a-4f7d-9e54-400fddca3a75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDQ1ODIsIm5iZiI6MTcxOTMwNDI4MiwicGF0aCI6Ii84OTkwODA1MS8zNDI0MzYzMjMtOTQ3NjBmY2MtMjg2YS00ZjdkLTllNTQtNDAwZmRkY2EzYTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNmUzYmVlMDVlNDZlNjZiMTUzMmM2M2M4NmM3NWRjOGZjYjMzYjM0NGVjZDA1NWEyMDA5N2Q5MTIyZDk1ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qU0K80zXkWT8qAhYJvTl7MFT2J8h6IfIIKl5LeVi27Y)
> 
> ![image](https://private-user-images.githubusercontent.com/89908051/342436365-17c0a200-7787-412d-9281-8c4f31f0dce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDQ1ODIsIm5iZiI6MTcxOTMwNDI4MiwicGF0aCI6Ii84OTkwODA1MS8zNDI0MzYzNjUtMTdjMGEyMDAtNzc4Ny00MTJkLTkyODEtOGM0ZjMxZjBkY2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzBmYTc2MmNhODZiMTM0NzdjZjdiMzAzZDU3ZTVkNmY4ODlhZTMxM2MxMzk2M2ZjYjhlNmJkMTczZGVkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKd58bLcI46jOVTJpcwpkhyB5EhAqbHZEf6T90Q-P88)

No, the second diff looks like it will cause trouble by arbitrary changing sharedBy of shares.

I lost track of what you are trying to fix, can you explain how to reproduce your problem? Why do you remove the exception handling removing invalid shares in OwnershipTransferService?

2024-06-25 14:27 UTC, luka-nextcloud commented
@come-nc
- Reproduce steps:
1. UserA share Folder1 to UserB
2. UserB share Folder1 to UserC
3. UserA deleted sharing to UserB
4. UserA transfer Folder1 to UserD
-> UserC lost access to Folder1. When UserC open sharing tab of Folder1, the error message `Error: Could not get proper share mount for . Failing since else the next calls are called with null` returned.

- Issue occurred because the sharing of UserB to UserC was not deleted or updated after UserA deleted sharing to UserB. Then, when UserA transfering Folder1 to UserD, that re-share record cannot be transferred because it throws `GenericShareException` error.

2024-06-27 12:39 UTC, come-nc commented
> @come-nc
> 
> * Reproduce steps:
> 
> 1. UserA share Folder1 to UserB
> 2. UserB share Folder1 to UserC
> 3. UserA deleted sharing to UserB
> 4. UserA transfer Folder1 to UserD
>    -> UserC lost access to Folder1. When UserC open sharing tab of Folder1, the error message `Error: Could not get proper share mount for . Failing since else the next calls are called with null` returned.
> 
> * Issue occurred because the sharing of UserB to UserC was not deleted or updated after UserA deleted sharing to UserB. Then, when UserA transfering Folder1 to UserD, that re-share record cannot be transferred because it throws `GenericShareException` error.

UserC already loses access to Folder1 after step 3, right?
At that point the sharing tab shows no error?

2024-06-27 14:54 UTC, luka-nextcloud commented
@come-nc 
> UserC already loses access to Folder1 after step 3, right?

No, UserC didn't lose access to Folder1 after step3. This is the issue we are trying to fix.

> At that point the sharing tab shows no error?

No error.

2024-07-10 08:22 UTC, luka-nextcloud commented
@come-nc 
**Original problem:**
Re-share was not deleted when parent share deleted. Then, it caused error while transferring ownership.

**Reproduce steps:**
Mentioned above.

**Solution:**
Delete the re-share and its children when parent share is deleted.

2024-08-12 07:31 UTC, come-nc commented on lib/private/Share20/Manager.php
> +							$this->deleteShare($child);
Why is generalCreateCheck method not directly run on `$child` instead?
I do not understand the logic in hasNodeAccess, it searches for other shares of the same node but only directly to the user?

Also, the code is duplicated between user shares and group shares, please first compute an array of target users and then loop on it.

2024-08-13 19:04 UTC, luka-nextcloud commented on lib/private/Share20/Manager.php
> +							$this->deleteShare($child);
@come-nc Ok, I have checked again. The logic in `hasNodeAccess` was not really correct. It missed some cases. So, I removed that function and updated approach for `deleteReshare`. First collect related user ids, then collect the re-share by those users, finally do `generalCreateCheck` on those re-share records.

2024-08-19 08:51 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		];
From what I see in `getSharesInFolder` you can use `$providers = $this->factory->getAllProviders();` to directly get all providers without caring for the share type. Unless we explicitely only want to fetch for some type here?

2024-08-19 08:51 UTC, come-nc commented on lib/private/Share20/Manager.php
> +				$shares = $provider->getSharesBy($userId, $shareType, $node, false, -1, 0);
Why do you pass `false` for `$reshares` flag here but `true` in the call to `getSharesInFolder` below?

2024-08-19 14:31 UTC, icewind1991 commented on apps/files_sharing/lib/OrphanHelper.php
> +			// Only the mount of owner has the internal path value
I don't think this is true

2024-08-19 16:28 UTC, luka-nextcloud commented on lib/private/Share20/Manager.php
> +		];
We still need share type for calling `getSharesBy()` at line 1059.

2024-08-19 16:29 UTC, luka-nextcloud commented on apps/files_sharing/lib/OrphanHelper.php
> +			// Only the mount of owner has the internal path value
@icewind1991 Could you provide a suggestion?

2024-08-20 08:04 UTC, come-nc commented on lib/private/Share20/Manager.php
> +		];
Indeed, I missed that.

2024-08-20 11:48 UTC, icewind1991 commented on apps/files_sharing/lib/OrphanHelper.php
> +			// Only the mount of owner has the internal path value
You can check if `$mount` is a `HomeMountPoint` and then use `$mount->getUser()`

2024-11-21 09:40 UTC, come-nc commented on apps/files_sharing/lib/OrphanHelper.php
> +			if ($mount->getMountPoint() === $userHomeMountPoint) {
I was wrong, $mount here is actually an instance of CachedMountFileInfo and it seems there’s no easy way to get a MountPoint/HomeMountPoint instead.

Let’s keep it that way if it works.
I’d like @icewind1991 to approve this just in case there is a corner case we missed.

2024-11-21 09:41 UTC, come-nc approved these changes

2024-11-25 13:43 UTC, icewind1991 commented on apps/files_sharing/lib/OrphanHelper.php
> +			if ($mount->getMountPoint() === $userHomeMountPoint) {
Didn't realize `$mount` is a `CachedMountInfo`, then checking the mountpoint is probably the easiest.

2024-11-25 14:21 UTC, icewind1991 approved these changes

2024-11-25 17:20 UTC, merged

2024-12-03 07:49 UTC, luka-nextcloud commented
/backport to stable28

2024-12-03 08:10 UTC, luka-nextcloud commented
/backport to stable29

2024-12-03 08:10 UTC, luka-nextcloud commented
/backport to stable30