fix(session): Set last-password-confirm for token logins
nextcloud/server pull request #43034
Opened 2024-01-22 18:21 UTC by provokateurin

## Summary

This allows using app passwords for endpoints which require password confirmation. Unlike previous investigations suggested this fixes it regardless of the cookies.

For history: https://github.com/nextcloud/server/pull/43000

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-22 18:24 UTC, provokateurin commented
/backport to stable27

2024-01-24 12:35 UTC, nickvergessen approved these changes

2024-01-24 12:44 UTC, ChristophWurst reviewed
Honestly not sure if this is what password confirmation protected endpoints were designed for.

Is there anything preventing session tokens to be used as app passwords to work around password confirmation?

2024-01-24 12:47 UTC, provokateurin commented
If you only have session cookies then you are missing the Authorization header and the method will return false before running the added line.

2024-01-24 12:51 UTC, ChristophWurst commented
I mean someone intentionally sending the session token as auth header to bypass password protection when they acquired a user session but don't know the password

2024-01-24 13:13 UTC, provokateurin commented
Using an app password is completely fine, since you can already workaround this limitation by using basic auth with the app password as the password (and if you don't know the username you can get it from an endpoint that doesn't require password auth.

2024-01-24 13:15 UTC, ChristophWurst requested changes

2024-01-24 13:15 UTC, ChristophWurst commented on lib/private/User/Session.php
> +		$this->session->set('last-password-confirm', $this->timeFactory->getTime());
tested and confirmed that this is processed when a request is sent with a bearer token that is a session id.

if we want this, then it should be moved into the if above.

2024-01-24 13:15 UTC, provokateurin commented
We might want to move the cookie check before the token check and always early return if the cookie is set so the token login is never tried: https://github.com/nextcloud/server/blob/master/lib/base.php#L1145-L1153

2024-01-24 13:16 UTC, provokateurin commented on lib/private/User/Session.php
> +		$this->session->set('last-password-confirm', $this->timeFactory->getTime());
Ah I see, the names are not useful unless you also read the comments...
I guess that would fix the problem then?

2024-01-24 13:19 UTC, ChristophWurst commented
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/sudo-mode is what I'm referring to.

I am not sure if an app password or session token qualifies as enough proof for sensitive operations that require the user password in a web session.

2024-01-24 13:22 UTC, provokateurin commented
I somewhat agree, but as I said it is already possible to workaround this limitation, even if you only have an app password.
Other tokens shouldn't be allowed though.

2024-01-24 13:31 UTC, ChristophWurst commented
> it is already possible to workaround this limitation

how? `\OC\AppFramework\Middleware\Security\PasswordConfirmationMiddleware::beforeController` doesn't check for app_password

2024-01-24 13:35 UTC, provokateurin commented
I don't know, but I know it works because I've used it already many times.

2024-02-11 14:38 UTC, bigcat88 commented
I always thought this behavior was intended since we already get a lot of requests from clients who are afraid to use app_password.
This change will scare them even more.

Imagine the situation:

You create an application password for the file sync client and you are an administrator.
These changes will allow the application to send your application password somewhere, and the hacker will be able to create a new user with admin rights and covertly act on their behalf from another location.
Without support for API scopes, this change is dangerous.

Do you have any thoughts on this @nickvergessen as you already accepted it?

2024-02-11 17:15 UTC, provokateurin commented
I see your point.
What I see as a failure is the differentiation between user and admin changes. There are a bunch of user settings which you are only allowed to change by confirming the password, but generally they are not harmful.
On the other side there are the admin endpoints that need password confirmation where this makes much more sense.
Maybe we should reconsider which endpoints really need password confirmation and which endpoints don't.

I was talking to @ChristophWurst the other day and brought up the idea again that it should just be possible to do the actual password confirmation when you only have an app password: https://github.com/nextcloud/server/pull/43000
This way it is still secured by asking the user to enter their password which matches the current behaviour on web.
So far that option seems to be more sensible as it will mimic the current state and just allow all clients to use password protected endpoints without opening up any potential security holes.

2024-02-13 09:28 UTC, nickvergessen commented
> I was talking to ChristophWurst the other day and brought up the idea again that it should just be possible to do the actual password confirmation when you only have an app password:

Yeah I think that makes sense. I missed somehow that you only have an app password and not the real password.

2024-02-20 07:04 UTC, provokateurin commented
Closing in favor of https://github.com/nextcloud/server/pull/43000

2024-02-20 07:06 UTC, closed without merging