New emails for sharebymail
nextcloud/server pull request #4307
Opened 2017-04-11 21:51 UTC by MorrisJobke

* I added a new method to allow adding a single button with no width constraints
* escape the texts of the heading, body and button text with `htmlspecialchars` (is this enough, @LukasReschke ) - this was needed to show also file names in there and not cause code injection (the escaping is only done in the HTML emails and not in the text emails
* migrate share email and the password notification email

2017-04-11 21:52 UTC, MorrisJobke commented
Followup to #4304 and #4244

2017-04-11 21:54 UTC, MorrisJobke commented
Before:

<img width="629" alt="bildschirmfoto 2017-04-11 um 16 25 44" src="https://cloud.githubusercontent.com/assets/245432/24932542/9055d2b8-1ed7-11e7-99a8-09040c1a76d4.png">

After:

<img width="655" alt="bildschirmfoto 2017-04-11 um 16 26 35" src="https://cloud.githubusercontent.com/assets/245432/24932540/905219ca-1ed7-11e7-94ec-fd56a4bdc22b.png">
<img width="690" alt="bildschirmfoto 2017-04-11 um 16 25 49" src="https://cloud.githubusercontent.com/assets/245432/24932541/90548930-1ed7-11e7-99d4-be2e25941923.png">

2017-04-11 21:55 UTC, MorrisJobke commented
@nextcloud/designers I'm also open for new wordings of the emails, because it's a lot of duplicate text. Maybe you have better ideas. cc @Espina2

2017-04-12 06:52 UTC, rullzer approved these changes
Awesome stuff. Lets do this!

2017-04-12 08:23 UTC, LukasReschke commented
Rebased upon master.

2017-04-12 09:19 UTC, schiessle requested changes
The HTML mail looks awesome! But the text mail looks strange:

````
admin shared »welcome.txt« with you

admin shared »welcome.txt« with you. Click the button below to open it.

Open »welcome.txt«: http://localhost/master/index.php/s/RPGlwrxTJr2lrm5
--
Nextcloud - a safe home for all your data
This is an automatically generated email, please do not reply.
````

Can we fix this?

2017-04-12 09:26 UTC, nickvergessen commented
i will fix

2017-04-12 09:37 UTC, LukasReschke commented
> escape the texts of the heading, body and button text with htmlspecialchars (is this enough, @LukasReschke ) - this was needed to show also file names in there and not cause code injection (the escaping is only done in the HTML emails and not in the text emails

Not entirely sure about that. For example in the activity app we would have an email that uses something like:

> $emailTemplate->addBodyText($l->t('There was some activity at %s', [$this->urlGenerator->getAbsoluteURL('/')]));

In this case having HTML allowed here for URLs (and a separate text for plain text) may be very useful. Also I think sometimes some stuff like `<strong>` may be useful as well. Thoughts?

2017-04-12 09:40 UTC, LukasReschke commented
Also HTML may be useful when embedding icons like the activity state icons. Just a thought though :-)

2017-04-12 10:51 UTC, schiessle commented
I fixed the footer for the plain text mails.

The plain text mail looks now better, also with the changes by @nickvergessen :

![mail](https://cloud.githubusercontent.com/assets/1589737/24954116/424c73fe-1f7e-11e7-81b4-036ffe5f42c5.png)

Although I think the "Click the button below to open it." still sounds a bit strange for a plain-text mail. I think the best would be to create two separate templates. This way we can make sure that we have a useful text in both cases and that we have reasonable line breaks (something <= 80 chars).

2017-04-12 10:56 UTC, nickvergessen commented
@schiessle `addBodyText` has two parameters, just make use of it.

2017-04-12 10:59 UTC, Espina2 commented
I think you can more information like that. @MorrisJobke 

![shared folder](https://cloud.githubusercontent.com/assets/11150206/24954459/6223756c-1f77-11e7-93d5-6ff478261f6b.png)

2017-04-12 11:57 UTC, enoch85 commented
@Espina2 Just plain perfection.

2017-04-12 12:37 UTC, schiessle commented
@nickvergessen I saw it. The "problem" is that we then have to split it up in two "addBodyText()" calls which will result in a line break, right?

2017-04-12 12:43 UTC, schiessle commented
As expected it looks rather ugly on the html mail if it put in in two "addBodyText()" calls because of the line breaks:

![mail](https://cloud.githubusercontent.com/assets/1589737/24958083/6227a0a8-1f8e-11e7-97f9-06f9117c1dc8.png)

2017-04-12 13:34 UTC, nickvergessen commented
Not sure what you did, but I made two little commits and it looks good

2017-04-12 15:14 UTC, schiessle approved these changes

2017-04-12 15:33 UTC, MorrisJobke commented
Tested and works nice 👍

2017-04-12 15:34 UTC, MorrisJobke commented
@Espina2 Looks nice, but something for a followup. First of all we should get rid of the super ugly way. ;)

2017-04-12 17:14 UTC, MorrisJobke commented on lib/private/Mail/EMailTemplate.php
> +		$this->plainBody .= PHP_EOL . '-- ' . PHP_EOL;
When you update stuff like this, then you should also update the unit tests. Let me do this.

2017-04-12 17:42 UTC, MorrisJobke commented
I fixed the unit tests. Looks good now from my side 👍

2017-04-12 19:23 UTC, merged