Move modal outside of the Version component.
nextcloud/server pull request #43084
Opened 2024-01-24 14:47 UTC by artonge

This is for accessibility, to have the `NcListItem` (`<li>`) as a direct child of the `<ul>`

Before | After
-- | --
![image](https://github.com/nextcloud/server/assets/6653109/86d769be-3434-4e20-bc26-e18e5ac872ce) | ![Screenshot from 2024-01-24 15-48-13](https://github.com/nextcloud/server/assets/6653109/9740f0aa-23f8-4e9c-9390-fdcfbb72b267)

Diff is big, but is mostly white spaces, moved code, and a rewrite in ts of `versions.js`.

2024-01-24 15:16 UTC, JuliaKirschenheuter approved these changes
Thank you Louis!

2024-01-24 15:55 UTC, emoral435 approved these changes

2024-01-24 16:04 UTC, Fenn-CS approved these changes
Looks good!

2024-01-24 17:51 UTC, ShGKme requested changes

2024-01-24 17:55 UTC, ShGKme commented on apps/files_versions/src/views/VersionTab.vue
> +		<VirtualScrolling :sections="sections"
Before | After
---|---
![image](https://github.com/nextcloud/server/assets/25978914/7129395d-0330-4a37-a77e-3c3fe213461a) | ![image](https://github.com/nextcloud/server/assets/25978914/af94bceb-20ae-495a-9b02-b8732db8f9a7)
![image](https://github.com/nextcloud/server/assets/25978914/d23855b0-445b-4a1d-8039-db55a89ff3b4) | ![image](https://github.com/nextcloud/server/assets/25978914/3ffe7b30-83e1-4e72-93dc-edc83cc06dfd)

2024-01-25 09:25 UTC, artonge commented on apps/files_versions/src/views/VersionTab.vue
> +		<VirtualScrolling :sections="sections"
Good catch, thanks.
Fixed

2024-01-25 10:54 UTC, ShGKme approved these changes

2024-01-25 14:43 UTC, susnux commented
cypress is related and needs fixing

2024-01-26 18:07 UTC, merged

2024-01-27 08:16 UTC, JuliaKirschenheuter commented
/backport to stable28