fix(CI): MySQL unit tests, use LTS for code coverage and drop EOL
nextcloud/server pull request #43170
Opened 2024-01-27 13:22 UTC by susnux

## Summary
1. Use the LTS version of MySQL for the code coverage instead of an EOL version
2. Test LTS (8.0) and the latest version (8.3) (lower + upper bound) and drop EOL version 8.1

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-28 07:11 UTC, nickvergessen requested changes

2024-01-28 07:11 UTC, nickvergessen commented on .github/workflows/phpunit-mysql.yml
> -        image: ghcr.io/nextcloud/continuous-integration-mysql-${{ matrix.mysql-versions }}:latest
We should add it on our CI instead, so we have backups

2024-01-29 10:38 UTC, nickvergessen submitted a review, later dismissed

2024-01-31 16:05 UTC, skjnldsv approved these changes

2024-01-31 16:06 UTC, nickvergessen approved these changes

2024-01-31 16:06 UTC, merged