Feat: Narrow search to single conversation in unified search
nextcloud/server pull request #43189
Opened 2024-01-29 11:22 UTC by Fenn-CS

Resolves : https://github.com/nextcloud/server/issues/42914

2024-02-06 10:06 UTC, jancborchardt reviewed
Looks good, 2 details:
- [ ] As @marcoambrosini said: Rename the current "Conversations" filter to "Talk" for better clarity
- [ ] The "In conversation" should be moved further up so it is grouped with the other Talk-related filters

2024-02-06 13:29 UTC, nickvergessen requested changes, later dismissed

2024-02-06 13:29 UTC, nickvergessen commented on core/src/components/UnifiedSearch/ConversationsListModal.vue
This is very problematic and does not belong into the server repository (as mentioned in the chat).
Approaches similarly to existing integrations with Talk and Deck, Maps, Notes, Tasks and all the other things should be taken, so that server just allows a "registration of additional filters/places" and when clicking on it, talk is taking over and just responding with the selected filter value.

2024-02-08 08:00 UTC, marcoambrosini commented
> The reason this was not done straight way is because the providers

I think it's better to do it properly in the backend no?

2024-02-08 08:07 UTC, marcoambrosini reviewed
Looks good! The only thing that I would add is a search box on top of the places filter too. These can be a lot (see our company instance) and it might also get confusing. 
It would be also great to set up search aliases, for example if someone searches  "Chat", they're also presented with the "talk" and "conversation" filters.

2024-02-12 16:37 UTC, Fenn-CS commented
The context of the PR has changed and actual UI changes that his PR initially contained are now in : https://github.com/nextcloud/spreed/pull/11575

2024-02-16 08:00 UTC, Antreesy commented on core/src/store/index.js
> +import Vuex from 'vuex';
Could you rewrite it to Pinia store, maybe? We'll migrate to it anyway sooner or later, there's no need to increase future efforts

2024-02-19 15:20 UTC, Antreesy commented on core/src/unified-search.js
> +import { useSearchStore } from '../src/store/unified-search-external-filters.js'
You need to register Pinia same way as Vuex:
```js
import { createPinia, PiniaVuePlugin } from 'pinia'
Vue.use(PiniaVuePlugin)
const pinia = createPinia()
export default new Vue({..., pinia, ...})
```

2024-02-19 15:45 UTC, Fenn-CS commented on core/src/unified-search.js
> +import { useSearchStore } from '../src/store/unified-search-external-filters.js'
Right, sorry about that, looks like I got a cache-false positive when I tested if Pinia would work with the registration.

2024-02-19 16:10 UTC, Antreesy approved these changes
As I said, I've nothing against changes. Please align with Design team and Joas based on this API PR: https://github.com/nextcloud/spreed/pull/11456

Maybe you need to use 'talk-message-current' provider?

2024-02-19 16:33 UTC, Fenn-CS commented
> Maybe you need to use 'talk-message-current' provider?

I [asked](https://github.com/nextcloud/spreed/pull/11575#discussion_r1489370174) and got confirmation from @nickvergessen that the existing provider is correct.

So mentioning here for further alignment, sending extra parameters to that provider, does nothing.

cc: @Altahrim

2024-02-19 16:40 UTC, nickvergessen commented
`talk-message` is the search provider that accepts the filter.
There is also an integration test that the API if called like specified, does the filtering correctly.

2024-02-19 20:19 UTC, Fenn-CS commented
Looking at 

https://github.com/nextcloud/spreed/blob/978922ee73e74f15c2ffe3fd83800edb6d2b01af/tests/integration/features/bootstrap/FeatureContext.php#L2452-L2459 it does look like we expect the user to type the search query to include the room? according to regex `'/conversation:ROOM\((?P<name>\w+)\)`?

Or at least that we need the request like that? In the chats what @Altahrim explained was that we simple need to pass `?term=hello&conversation=<token>` for the filtering to work. 

Please, am I missing something? 

Otherwise, If the user is expected to type strings that match `'/conversation:ROOM\((?P<name>\w+)\)` I think it should be parsed at the front-end at still sent simply using the query structure above? 

Looking at same snippet it seems to suggest @Antreesy  is right that we should use `talk-message-current'` instead as `talk-message` has descriptive text "search in other rooms"


cc: @nickvergessen

2024-02-19 20:37 UTC, nickvergessen commented
> it does look like we expect the user to type the search query to include the room? according to regex `/conversation:ROOM\((?P<name>\w+)\)`?

This is just because the integration test has only 1 field. But the code you linked to is exactly the important one. It removes the conversation bit from the query and adds `&conversation=<token>`

So yeah:
> `?term=hello&conversation=<token>`

This is exactly what is expected. `/search/providers/talk-message/search?term=hello&conversation=<token>` to be specific

`talk-message-current` only searches in the conversation that is the `from=/call/<token2>`, so no. `talk-message` must be used for the filter plugin.

2024-02-19 21:40 UTC, Fenn-CS commented
The URL's being sent look like `/search/providers/talk-message/search?term=uni&from=/apps/spreed/&conversation=qbhbdutu` @nickvergessen kindly test and review at your earliest convenience.

Thank you.

2024-02-20 11:03 UTC, nickvergessen commented
Seems to be working after compiling locally (because you didn't commit that yet).

>  The "In conversation" should be moved further up so it is grouped with the other Talk-related filters

This however is currently still missing and impossible for Talk to do.
Maybe we can add a "priority" to the registration object like the normal search providers have?

Another thing I noticed is that `In conversation` is shown as headline instead of `Messages` when no filter is active:
![grafik](https://github.com/nextcloud/server/assets/213943/0b6bf45a-3b48-4a2d-af52-4aef35eeed9d)

But that we can also have a look at later. Maybe we can resolve that in Talk itself.

2024-02-21 11:58 UTC, Fenn-CS commented
> Seems to be working after compiling locally (because you didn't commit that yet).
> 
> > 
>     The "In conversation" should be moved further up so it is grouped with the other Talk-related filters
> 
> This however is currently still missing and impossible for Talk to do.
> Maybe we can add a "priority" to the registration object like the normal search providers have?


The order is currently not influenced in anyway at the frontend level as that's arrange in the backend. We have some options like :

- Adding priority as suggested : But the question of what is the priority arises? Any app can set a priority that would override the priorities sent from the backend? (As whatever priority we set has to be relative to the other ones, hence to achieve the desire results we need to kinda hard code a priority and do frontend reordering, or copy the  algorithm to calculate priority from the backend to frontend yet making sure the inputs to calculate the priority is/are available)

- We could just arrange the filters in alphabetical order (?)

----

> Another thing I noticed is that In conversation is shown as headline instead of Messages when no filter is active:

- That has to be updated in spreed/talk. 

Brings the question of pluralization, we think figure out how to handle pluralization because ones the filter is not applied it is still considered a provider and in a case such as the one above it should read Messages but not sure whether when a particular conversation is applied is should read the same thing.

2024-02-27 13:54 UTC, Fenn-CS commented
@nickvergessen PS, had time to read my comments?

2024-02-27 14:24 UTC, nickvergessen commented
> But the question of what is the priority?

Integer, just like with the normal providers on the PHP api

> We could just arrange the filters in alphabetical order 

Sounds like the worst option and still doesn't allow to group Talk options together

2024-02-27 22:02 UTC, Fenn-CS commented
> Integer, just like with the normal providers on the PHP api

It is sure an int, but the chosen integer if being set from the front-end needs to carefully picked to make sure it ranks just at the right position in this case grouping with talk. How do we write that algorithm in a way that prevents any app that implements the filter plugin API from distorting the order by simply setting higher values?

What seems easily achievable at this point, is creating a front-end ordering mechanism that simply inserts the new filters immediately after the last filter from a specific provider, without regard to any integer. The result is that, filters would be grouped according to providers, but all filters attached via the plugin API would appear in the order in which they were attached.


@nickvergessen would you consider this a middle-ground compromise?

2024-02-28 06:35 UTC, nickvergessen commented
Ah you don't have the priority in the frontend, the backend sorts it and does not expose it.

I guess that sounds like the best option then

2024-03-04 08:31 UTC, Fenn-CS commented
/compile

2024-03-04 14:45 UTC, ChristophWurst commented on core/src/store/unified-search-external-filters.js
> + * @copyright Copyright (c) 2021 Fon E. Noel NFEBE <me@nfebe.com>
happy new year

2024-03-04 14:45 UTC, ChristophWurst commented on core/src/views/UnifiedSearchModal.vue
> +			console.debug('Search scope set to conversation', addFilterEvent)
leftover?

2024-03-04 14:45 UTC, ChristophWurst commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
not sure about the approach. are we returning to globals for public API?

if so, please move this into ``core/src/OCP/index.js``. otherwise `OCP.UnifiedSearch` only exists if `core/src/unified-search.js` is bundled.

2024-03-04 14:46 UTC, ChristophWurst commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
> not sure about the approach. are we returning to globals for public API?

For comparison see the other exports in core/src/OCP/index.js. We are trying to get away from globals. They make core and app scripts fragile to loading order issues.

2024-03-04 15:57 UTC, Fenn-CS commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
@ChristophWurst Makes sense, given that, this already has a matching PR in spreed merged and there is existing work going for files would you be up for:

1. Creating a follow up issue to move this to `core/src/OCP/index.js` (I see it makes more sense there, we can even change that to ts and use properly types with the module system used there)....

2. Merge this and do 1, as follow up PR

To meet release schedule for these features?

2024-03-04 16:02 UTC, Fenn-CS commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
Other minor remarks handled.

2024-03-04 16:30 UTC, ChristophWurst commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
In both cases we will introduce this global function as public API. That means it has to stay for at least three major releases.

If this has to go in today then we can only add the proper API for 30, deprecate this approach, keep the parallel systems for two more releases and then drop the deprecated function again.

2024-03-04 16:37 UTC, ChristophWurst commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
@skjnldsv @susnux any other ideas for a pragmatic way forward?

2024-03-04 16:43 UTC, Fenn-CS commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
> In both cases we will introduce this global function as public API. That means it has to stay for at least three major releases.
> 
> If this has to go in today then we can only add the proper API for 30, deprecate this approach, keep the parallel systems for two more releases and then drop the deprecated function again.

Make sense, we can also deprecate it immediately after and still keep for two releases to allow a good update window. That should not be the problem because we have two apps that currently implement the API and we are the maintainers.

2024-03-04 16:54 UTC, skjnldsv commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
> we have two apps that currently implement the API

talk and?

2024-03-04 17:05 UTC, skjnldsv commented on core/src/store/unified-search-external-filters.js
> +		registerExternalFilter({ id, appId, label, callback, icon }) {
Can you write it in typescript and add proper typings so we know what to expect? :)

2024-03-04 17:09 UTC, Fenn-CS commented on core/src/store/unified-search-external-filters.js
> +		registerExternalFilter({ id, appId, label, callback, icon }) {
I already did in a follow up PR that introduces the files filter using same API : https://github.com/nextcloud/server/pull/43963/commits/a996c21d4b9d51961a34b3f71fe35ca134df4509

2024-03-04 17:10 UTC, skjnldsv requested changes, later dismissed

2024-03-04 17:10 UTC, skjnldsv commented on core/src/unified-search.js
> +window.OCP.UnifiedSearch = {
Agreed with @ChristophWurst, it's a no go from me.
Such API deserves its own handling in a lib package and proper typings so it can be documented and easily used.

2024-03-04 17:10 UTC, skjnldsv commented on core/src/views/UnifiedSearchModal.vue
> +		subscribe('nextcloud:unified-search:add-filter', this.handlePluginFilter)
That's a no from me, using an event to actually handle this registrations are not a stable way to do so.

I'd suggest using a proper registration like the event bus or the file actions is doing.

2024-03-04 17:10 UTC, skjnldsv commented on core/src/views/UnifiedSearchModal.vue
> +				providerFilter.callback()
What is a callback? What does it do?
A callback that is called without any parameters is odd to me.

2024-03-05 00:06 UTC, emoral435 reviewed
Overall, good PR! I agree with the API choices that the other reviewers have mentioned. Perhaps for tomorrows team call / Thursday PR chat's, you can schedule something to be aligned with the team, because I understand the time conflicts are not easy ahaha :)

2024-03-05 10:35 UTC, Fenn-CS commented on core/src/unified-search.js
> +		searchStore.registerExternalFilter({ id, appId, name, label, callback, icon })
@emoral435 That's because in unified search `name` is used for the display labels, meanwhile in the code base register action functions use labels just as labels. 

However, there is a follow up commit that improves the situation : https://github.com/nextcloud/server/pull/43963/commits/a996c21d4b9d51961a34b3f71fe35ca134df4509

2024-03-05 10:56 UTC, Fenn-CS commented on core/src/views/UnifiedSearchModal.vue
> +			const existingFilterIndex = this.filteredProviders.findIndex(existing => existing.id === providerFilter.id)
I am not sure what you are asking but yes, filter id's can clash and that's why this overwrite check exist.

2024-03-05 16:17 UTC, emoral435 commented on core/src/unified-search.js
> +		searchStore.registerExternalFilter({ id, appId, name, label, callback, icon })
Ah, I see now! A bit rough, but I see now that the follow up commit will help this out. That should reduce some of the confusion surrounding this :)

2024-03-05 16:20 UTC, emoral435 commented on core/src/views/UnifiedSearchModal.vue
> +			const existingFilterIndex = this.filteredProviders.findIndex(existing => existing.id === providerFilter.id)
Ah, my bad, I did not explain this well. What I am saying is that this check only finds *one* conflicting filter id's, no? What if there where more conflicting id's? 

> However, if you would like, this certainly can be made as another issue, due to time constraints (release coming up, and this is not a major edge case)

I still stick by this though :)

2024-03-05 16:32 UTC, Antreesy commented
Clicking on `Load more results` changes the filtering method (or drops some query params at least). Is it expected?

[Screencast from 05.03.2024 17:29:31.webm](https://github.com/nextcloud/server/assets/93392545/53722ab4-8479-4481-ac07-4a61f7b2bc71)

2024-03-05 22:54 UTC, emoral435 approved these changes
Outside of cases where to make the code clearer and more maintainable for the future, good PR :) Discussed with others, and the API deprecation can be handled later, just make sure to address https://github.com/nextcloud/server/pull/43189#issuecomment-1979172940 and its all good to me!

2024-03-06 01:06 UTC, Fenn-CS commented
/compile /

2024-03-06 01:28 UTC, Fenn-CS commented
> Outside of cases where to make the code clearer and more maintainable for the future, good PR :) Discussed with others, and the API deprecation can be handled later, just make sure to address https://github.com/nextcloud/server/pull/43189#issuecomment-1979172940 and its all good to me!

Sure thanks, would address that in follow up https://github.com/nextcloud/server/pull/43963 which is on its way in, I think it's best this goes in now so at the very least the spreed filter is working by feature freeze.

2024-03-06 10:07 UTC, merged