fix(provisioning_api): Translate exceptions shown in the frontend
nextcloud/server pull request #43234
Opened 2024-01-31 12:05 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/13820

## Summary
This exception messages are used by the front end to be displayed to the user, using hint exceptions would be quite breaking as hint exceptions are handled as HTTP error 500 for OCS controllers.
But I think it should be ok to simply translate the messages as for programmatically usage you should not use the message but the status code.

Also fixed some minor deprecation issue.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-01-31 12:19 UTC, rakekniven submitted a review, later dismissed

2024-01-31 13:43 UTC, susnux commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				throw new OCSException($this->l10n->t('Not viable to remove user from the last group you are SubAdmin of'), 105);
> Here you use "SubAdmin" or "subadmin". Please align all occurences. My vote goes to "sub-admin"

Done :white_check_mark:

2024-01-31 13:45 UTC, susnux commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				throw new OCSException($this->l10n->t('Not viable to remove user from the last group you are SubAdmin of'), 105);
>  btw. I do not get the meaning of this sentence

If I understand this correctly a sub-admin is not allowed to remove a user from all groups that user is sub-admin of, meaning the user must stay sub-admin of at least one groupe (maybe @nickvergessen, as the author, can help)?

2024-01-31 15:30 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				throw new OCSException($this->l10n->t('Not viable to remove user from the last group you are SubAdmin of'), 105);
yeah I think so, to avoid users that are managed by no one

2024-01-31 15:32 UTC, nickvergessen requested changes, later dismissed

2024-01-31 15:32 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				$newUser->setSystemEMailAddress($email);
Please don't make functional changes in a PR named "Translate…" Also those are not the same and infact it might be impossible to manage the system email address. So this should stay as `setEMailAddress`

2024-01-31 15:32 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +					$targetUser->setSystemEMailAddress($value);
```suggestion
					$targetUser->setEMailAddress($value);
```

2024-01-31 15:59 UTC, susnux commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				$newUser->setSystemEMailAddress($email);
Well just wanted to get rid of the deprecation warning and the docs say it is just an alias so one would expect both to be equal:

```php
	/**
	 * set the email address of the user
	 *
	 * It is an alias to setSystemEMailAddress()
	 *
	 * @param string|null $mailAddress
	 * @return void
	 * @since 9.0.0
	 * @deprecated 23.0.0 use setSystemEMailAddress() or setPrimaryEMailAddress()
	 */
	public function setEMailAddress($mailAddress);
```

But I understand this is not the scope of this PR.

2024-01-31 16:03 UTC, susnux commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				$newUser->setSystemEMailAddress($email);
Reverted that change.
But if both functions are really not identical that doc-comment is really misleading.

2024-01-31 16:08 UTC, nickvergessen commented on apps/provisioning_api/lib/Controller/UsersController.php
> +				$newUser->setSystemEMailAddress($email);
Hmm was not aware of the deprecation, maybe I have wrong memory in my head

2024-01-31 18:44 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +					throw new OCSException('Sub-admin group does not exist', 102);
Missing the translation?

2024-01-31 18:44 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +					throw new OCSException('Cannot create sub-admins for admin group', 103);
Missing translation?

2024-01-31 18:44 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +					throw new OCSForbiddenException('No permissions to promote sub-admins');
Missing translation?

2024-01-31 18:58 UTC, susnux commented
@Pytal also added translations for the missing exceptions - at least where it makes sense.

2024-01-31 19:13 UTC, Pytal approved these changes

2024-02-01 07:29 UTC, nickvergessen approved these changes

2024-02-01 15:55 UTC, merged