[IAppConfig] format values based on type
nextcloud/server pull request #43258
Opened 2024-02-01 12:28 UTC by ArtificialOwl

format values based on type:

original:
```
{
    "key1": "value1",
    "key2": "value0",
    "key6": "1",
    "key7": "{\"test1\":1,\"test2\":2}",
    "test8": "1",
    "key3": "value0",
    "key4": "3",
    "key5": "3.14"
}
```

new:

```
{
    "key1": "value1",
    "key2": "value0",
    "key6": true,
    "key7": {
        "test1": 1,
        "test2": 2
    },
    "test8": true,
    "key3": "value0",
    "key4": 3,
    "key5": 3.14
}
```

2024-03-05 22:47 UTC, emoral435 approved these changes
🐘

2024-03-15 12:24 UTC, ArtificialOwl commented on lib/private/AppConfig.php
> +					}
I am better personally without null value.

2024-03-15 12:25 UTC, ArtificialOwl commented
I have found a performance issue as this PR would load lazy config values when searching for the enabled apps at boot.
This is fixed, and test should be green now 🤞

2024-03-15 22:48 UTC, emoral435 approved these changes

2024-03-16 12:30 UTC, skjnldsv commented
```
There was 1 failure:

1) Test\AppConfigTest::testLazyConfigNotLoaded
It seems lazy config values are loaded during the boot of Nextcloud ?
Failed asserting that true matches expected false.

/home/runner/work/server/server/tests/lib/AppConfigTest.php:231
```

2024-03-19 10:51 UTC, ArtificialOwl commented
> ```
> There was 1 failure:
> 
> 1) Test\AppConfigTest::testLazyConfigNotLoaded
> It seems lazy config values are loaded during the boot of Nextcloud ?
> Failed asserting that true matches expected false.
> 
> /home/runner/work/server/server/tests/lib/AppConfigTest.php:231
> ```

test was not related to the PR. I will implement it in a separated PR

2024-03-19 10:57 UTC, skjnldsv requested changes
I would have liked this covered in Tests before we get this in

2024-03-19 11:12 UTC, closed without merging