enh: update desktop client unsupported version (403) error message
nextcloud/server pull request #43281
Opened 2024-02-02 09:42 UTC by camilasan

The user should get a more friendly warning when their desktop client version is not supported anymore by the server. See #nextcloud/desktop/issues/6273

### Before:

![before](https://github.com/nextcloud/server/assets/241266/103358ae-2f3d-404e-a9ea-4dcd552834c6)

###  After:

![after](https://github.com/nextcloud/server/assets/241266/4c89b379-de61-4791-bb11-36076183d395)

### Systray message
![systray](https://github.com/nextcloud/server/assets/241266/24a0fb27-c4b9-4dae-8a14-e9e35a6a35f0)

* Resolves: https://github.com/nextcloud/desktop/issues/6273

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-03 07:37 UTC, solracsf requested changes
Tests must be fixed.

2024-02-06 11:29 UTC, solracsf commented
What about adding a link on the message to `customclient_desktop` link?
This could lead to a better UX after all (upgrade one-click away!) :)

https://github.com/nextcloud/server/blob/ee6a62a8c17ef6df29ab02a2882b254e9918f88c/config/config.sample.php#L1105-L1117

2024-02-08 20:59 UTC, solracsf commented
@camilasan I was more thinking about a clickable link (if it can be done).
Otherwise, the full link is too much noise IMO :(

2024-02-12 15:15 UTC, nimishavijay commented
Agreed with @solracsf that the link could be hidden. What do you think about adding the link to the text "version 3.0.0 or later"? Would that be possible :)

```
Unable to connect to Nextcloud.
This version of the client is unsupported. Upgrade to [version 3.0.0 or later](https://nextcloud.com/install/#install-clients).
```

2024-02-22 13:59 UTC, solracsf approved these changes
Fine by me. 👍 
_Maybe just update the 1st post with an updated screenshot of the final version._

2024-02-28 09:59 UTC, jancborchardt requested changes
Seems good if it’s a clickable link like @solracsf suggested. :) 

Another detail: In the settings it says "Unable to connect to Nextcloud" and in the notification "Network error" – both of these are different and neither really seem correct for the issue?
Maybe rather it should say "Connection issue" @camilasan?

2024-03-06 18:04 UTC, jancborchardt approved these changes

2024-09-07 14:23 UTC, susnux approved these changes

2024-09-07 14:24 UTC, merged

2024-09-07 17:02 UTC, solracsf commented on apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php
> +			throw new \Sabre\DAV\Exception\Forbidden("This version of the client is unsupported. Upgrade to <a href=\"$customClientDesktopLink\">version $minimumSupportedDesktopVersion or later</a>.");
Ideally, this should be a translated string 😿 
Maybe in a follow-up PR.