fix(db): remove redundant indices in properties
nextcloud/server pull request #43339
Opened 2024-02-04 22:47 UTC by JohannesGGE

* Resolves: #42588 

## Summary
Remove index `property_index` and `properties_pathonly_index` because `properties_path_index` already covers column `userid` and `propertypath`

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-05 08:19 UTC, solracsf commented
Same as https://github.com/nextcloud/server/pull/43340#discussion_r1477806274

2024-02-14 16:59 UTC, miaulalala approved these changes

2024-02-15 07:40 UTC, ChristophWurst commented on core/Migrations/Version29000Date20240131122720.php
> +		}
`properties_path_index` is an index on (userid, propertypath). `properties_pathonly_index` is an index on (propertypath). The database can use properties_pathonly_index for queries on userid and userid+propertypath, but **not** for queries that only access propertypath.

> In general, a database can use a concatenated index when searching with the leading (leftmost) columns. An index with three columns can be used when searching for the first column, when searching with the first two columns together, and when searching using all columns.

https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys

2024-02-15 07:42 UTC, ChristophWurst requested changes
properties_pathonly_index must stay

2024-02-19 08:25 UTC, ChristophWurst approved these changes
:sunglasses:

2024-02-19 14:20 UTC, merged