feat: Migrate LinkReferenceProvider to OCP
nextcloud/server pull request #43355
Opened 2024-02-05 13:33 UTC by kyteinsky

* Resolves: # 

## Summary
This would be useful to eleminate the need for using this OC class
when an app dev wants to implement a custom reference provider
for the web client but wants to fall back on opengraph for mobile
clients.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-05 13:34 UTC, kyteinsky commented
It could've been an abstract class in OCP but that would interfere with `ADiscoverableReferenceProvider.php` so that idea was dropped.  
Please squash before merge. The two commits are separated for ease of review only.

2024-02-14 10:43 UTC, julien-nc requested changes
Minor comment.

Then :+1: :blue_heart:

2024-02-14 10:43 UTC, julien-nc commented on lib/private/Collaboration/Reference/LinkReferenceProvider.php
> +/** @deprecated 29.0.0 */
```suggestion
/** @deprecated 29.0.0 Use OCP\Collaboration\Reference\LinkReferenceProvider instead */
```

2024-02-14 12:22 UTC, julien-nc approved these changes

2024-02-14 12:26 UTC, juliushaertl approved these changes

2024-02-14 12:27 UTC, juliushaertl commented
> The autoloaders are not up to date
> Please run: bash build/autoloaderchecker.sh

2024-02-14 12:40 UTC, kyteinsky commented
there are a lot of changed hashes in the apps. Should that be included in the commit?  
```diff
apps/admin_audit/composer/composer/installed.php

-        'reference' => 'b1797842784b250fb01ed5e3bf130705eb94751b',
+        'reference' => '49969705de01aff43cf2e6b662e5c96bd48a3b27',
```

2024-02-15 05:56 UTC, merged