[Bug]: fix titles of pages (dashboard, apps-settings, users-settings) #43327
nextcloud/server pull request #43396
Opened 2024-02-06 14:58 UTC by arublov

* Resolves: #43327

## Summary

1. Remove pageTitle from Dashboard (remove duplication)
2. Changed on Settings/App from (Apps - Apps - Nextcloud) to (Settings - Apps - Nextcloud)
3. Changed on Users from (Users - Users - Nextcloud) to (Settings - Users - Nextcloud)

2024-02-07 09:58 UTC, JuliaKirschenheuter approved these changes

2024-02-07 16:27 UTC, emoral435 requested changes
Everything looks good, but this would introduce a new regression and an accessibility issue (regression in question being #42267)

![image](https://github.com/nextcloud/server/assets/110193237/ba8dd988-659f-40cc-9218-5a5fc76a143b)

The heading is now not descriptive enough. I personally think this is fine - but this is not up to me, as the checker for accessibility described this as being a breaking feature, in terms of accessibility, so it needs to be something different. Everything else looks good, so once that is fixed everything should be good to go :)

2024-02-14 14:40 UTC, emoral435 commented on core/templates/layout.user.php
> +				p(!empty($_['application'])?$_['application'].' - ':'');
Yes, that would fix the issue (both the current, and the original). cc @arublov would you like to finish this, or would you want me to pick it up? either is fine :) Thank you for the contribution 💙

2024-02-14 14:56 UTC, arublov commented on core/templates/layout.user.php
> +				p(!empty($_['application'])?$_['application'].' - ':'');
@emoral435 , yes, of course I'd like to finish it! 

I actually brought this up on a call with @ChristophWurst today, so yes, I'd like to see it through :)
I'll get started on it right away.

Thanks for your comment :)

2024-02-14 15:18 UTC, arublov commented
@emoral435 Done ✅

2024-02-14 15:25 UTC, arublov commented
And I see this PR into stable28, should I change this? 
Or leave it and it's ok? 
Because this is an old PR and I was creating it from stable28, now I yes, understand that it has to be created from a master.

2024-02-14 15:25 UTC, szaimen commented
![Screenshot_20240214_162520_Brave](https://github.com/nextcloud/server/assets/42591237/fd6ceb35-5382-4056-a554-894bcac98970)
👀

2024-02-14 15:28 UTC, arublov commented
> ![Screenshot_20240214_162520_Brave](https://private-user-images.githubusercontent.com/42591237/304784668-fd6ceb35-5382-4056-a554-894bcac98970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjQ2NTYsIm5iZiI6MTcwNzkyNDM1NiwicGF0aCI6Ii80MjU5MTIzNy8zMDQ3ODQ2NjgtZmQ2Y2ViMzUtNTM4Mi00MDU2LWE1NTQtODk0YmNhYzk4OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1MjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzODRhN2VjODcxOGQ1OTg0MDE0MjNmOTZkNzA5OWE3NzcyMzE2NDgzOWYyNmYwMjk0ZjhkM2RlZTM0NWU3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pH-fAdjoVUgCQABFjlDI4Ugv-_ddAYvUt7LKLQ4HtyU) 👀

yeap, I asked that above, okay, let's close this PR and create a new, right?

> ![Screenshot_20240214_162520_Brave](https://private-user-images.githubusercontent.com/42591237/304784668-fd6ceb35-5382-4056-a554-894bcac98970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjQ3ODgsIm5iZiI6MTcwNzkyNDQ4OCwicGF0aCI6Ii80MjU5MTIzNy8zMDQ3ODQ2NjgtZmQ2Y2ViMzUtNTM4Mi00MDU2LWE1NTQtODk0YmNhYzk4OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNDg2YzE2OTQ4N2MyYmE0NTdmMTExYmVkYmQ5YzlkZWI4MjdmMTA5ODI2ZjBkMjY4OGU3YWYxNzVkZTA5MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTP7NjNnekPDdi5XcS4Pn_TlYDrWhmBATTPgFPV-7gk) 👀 Can we please target master first?

yeap, I asked that above, okay, let's close this PR and create a new, right?

2024-02-14 15:29 UTC, closed without merging

2024-02-14 15:35 UTC, emoral435 commented
@arublov Yep! Just tag us as reviewers and we will approve and get it merged :) 💙