fix: Do not store public/private keys if passwords are not stored for auth tokens
nextcloud/server pull request #43447
Opened 2024-02-08 10:33 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-08 10:48 UTC, nickvergessen commented
### 💡 Ideas

- [ ] Add a repair step to remove the data when the config is set
- [ ] Add a setupcheck that gives you a hint for potential performance improvements if you are not using mail provisioned accounts nor external storage with user account auth
- [ ] Similarly the setupcheck should error if the config is flipped, but you are actually using one of the above

2024-02-09 13:57 UTC, icewind1991 approved these changes

2024-02-13 09:59 UTC, nickvergessen approved these changes

2024-02-13 15:52 UTC, juliushaertl commented
Repair step does not seem necessary as once rotating would already skip updating the fields.

Setup checks would be great idea, but would consider that separate (I have a local branch but trying to collect what we can check for now in the issue itself).

Tests should also cover the new scenario now.

2024-02-13 18:02 UTC, ChristophWurst reviewed
I think what's missing is the handling of going from no passwords/keys to auth tokens with keys. Then we have to generate the key pairs like we currently do for all new auth tokens.

---

Big :+1: performance wise

## Before

```
Benchmark
        Average number of seconds to run all queries: 35.473 seconds
        Minimum number of seconds to run all queries: 24.515 seconds
        Maximum number of seconds to run all queries: 42.470 seconds
        Number of clients running queries: 10
        Average number of queries per client: 10
```

## After

```
Benchmark
        Average number of seconds to run all queries: 1.760 seconds
        Minimum number of seconds to run all queries: 1.735 seconds
        Maximum number of seconds to run all queries: 1.787 seconds
        Number of clients running queries: 10
        Average number of queries per client: 10
```

That is 5% the time needed, or a speedup of 20.

https://github.com/ChristophWurst/authtoken-index-bench

2024-02-13 18:04 UTC, ChristophWurst commented
> Repair step does not seem necessary as once rotating would already skip updating the fields.

Regular auth tokens are not necessarily rotated, are they? I think they are tokens that would never "lose" their keys. In that case, an occ command to empty the full column could be helpful.

2024-02-14 19:11 UTC, ChristophWurst commented on lib/private/Authentication/Token/PublicKeyTokenProvider.php
>  			$hashedPassword = $this->hashPassword($password);
I've tried to fix it but this is not easy. On current master we iterate over all tokens of the user, read the public key and ecrypt the new password.
On this branch, we still want to set the password when auth.storeCryptedPassword===true. If auth.storeCryptedPassword was false before, there could be tokens without public/private keys. We can't just generate a key pair on demand because the token (app password) is used to symmetrically encrypt the private key. We don't have this information.
We could decide to not set a password for tokens generated without one, but this may lead to a strange UX. Like if the admin switches to auth.storeCryptedPassword===true, then a connected desktop client has to be disconnected and connected again to be able to authenticate on external storage :s

2024-02-15 07:22 UTC, ChristophWurst commented on lib/private/Authentication/Token/PublicKeyTokenProvider.php
>  			$hashedPassword = $this->hashPassword($password);
What we can do is generate missing key pairs when tokens are finally used, then set the password at the next login.

Something like

1. Admin disables passwords in auth tokens
2. User logs in
3. User connects desktop client
4. Admin enables passwords in auth tokens
5. User logs in -> desktop auth token remains without password
6. Desktop client connects -> key pair is generated, password field stays empty
7. User logs in -> desktop auth token is updated with the login password

It is a bit of a slow process, but it's a better process than leaving passwordless tokens passwordless forever.

2024-02-15 08:09 UTC, ChristophWurst requested changes
https://github.com/nextcloud/server/pull/43447#discussion_r1488336850

to avoid accidental merge

2024-04-19 09:31 UTC, ChristophWurst commented on lib/private/Authentication/Token/PublicKeyTokenProvider.php
>  			$hashedPassword = $this->hashPassword($password);
Pushed the missing logic for ^.

1. Generate key pair when the token is used
2. Assign password when the user logs in with the login password

This allows instances to go from passwordless to "passwordful" auth tokens

2024-04-19 09:33 UTC, ChristophWurst commented on lib/private/Authentication/Token/PublicKeyTokenProvider.php
> +			$this->generateNewKey($dbToken, null, $token);
This is called twice when I use app passwords for OCS

```
PublicKeyTokenProvider.php:247, OC\Authentication\Token\PublicKeyTokenProvider->checkToken()
PublicKeyTokenProvider.php:187, OC\Authentication\Token\PublicKeyTokenProvider->getToken()
Manager.php:135, OC\Authentication\Token\Manager->getToken()
Session.php:549, OC\User\Session->isTokenPassword()
Session.php:449, OC\User\Session->logClientIn()
Session.php:602, OC\User\Session->tryBasicAuthLogin()
base.php:1135, OC::handleLogin()
v1.php:63, {main}()
```

and

```
PublicKeyTokenProvider.php:247, OC\Authentication\Token\PublicKeyTokenProvider->checkToken()
PublicKeyTokenProvider.php:187, OC\Authentication\Token\PublicKeyTokenProvider->getToken()
Manager.php:135, OC\Authentication\Token\Manager->getToken()
Session.php:804, OC\User\Session->validateToken()
Session.php:363, OC\User\Session->login()
Session.php:463, OC\User\Session->logClientIn()
Session.php:602, OC\User\Session->tryBasicAuthLogin()
base.php:1135, OC::handleLogin()
v1.php:63, {main}()
```

This could give us a terrible case for a causal read.

2026-06-16 19:34 UTC, juliusknorr commented
I do not have capacity to finish this. Feel free to take it over if needed. Will close this for now.

2026-06-16 19:34 UTC, closed without merging