enh(log): exit log() earlier if no crashreport registered
nextcloud/server pull request #43529
Opened 2024-02-12 14:44 UTC by ArtificialOwl

2024-02-12 19:11 UTC, ArtificialOwl commented
_(failing test not related)_

2024-02-13 14:08 UTC, icewind1991 requested changes
This would break `BeforeMessageLoggedEvent`

2024-02-14 10:42 UTC, ArtificialOwl commented
> This would break `BeforeMessageLoggedEvent`

I added a `hasListeners()` and exit the method if no `BeforeMessageLoggedEvent` is registered. 
Not sure the performance gain anymore. 
Your thoughts ?

2024-02-14 12:59 UTC, icewind1991 commented on lib/private/Log.php
> +		if ($level < $minLevel && (($this->crashReporters?->hasReporters() ?? false) === false)) {
missing the `hasListeners` check here

2024-02-14 15:00 UTC, ArtificialOwl commented on lib/private/Log.php
> +		if ($level < $minLevel && (($this->crashReporters?->hasReporters() ?? false) === false)) {
this fix a known issue ?

2024-02-14 15:33 UTC, icewind1991 approved these changes
log events still work

2024-02-23 20:56 UTC, skjnldsv approved these changes

2024-02-23 20:56 UTC, merged