Correctly calculate used space for quota with external storage
nextcloud/server pull request #4357
Opened 2017-04-16 00:32 UTC by Ardinis

issue #4348

2017-04-18 11:03 UTC, icewind1991 requested changes

2017-04-18 11:03 UTC, icewind1991 commented on lib/private/legacy/helper.php
> +			$rootInfo = \OC\Files\Filesystem::getFileInfo($path, $includeExtStorage);
This should be `'ext'`, when using `true` it also includes incoming shares

2017-04-19 08:24 UTC, Ardinis commented on lib/private/legacy/helper.php
> +			$rootInfo = \OC\Files\Filesystem::getFileInfo($path, $includeExtStorage);
I am not sure of what you are meaning here.
By using $includeExtStorage external storage are counted in quota calculation for the used part.

2017-04-19 12:23 UTC, icewind1991 commented on lib/private/legacy/helper.php
> +			$rootInfo = \OC\Files\Filesystem::getFileInfo($path, $includeExtStorage);
You can pass `'ext'` as the seccond argument of `getFileInfo` to have it include external storages but not shares.

When passing `true` it includes both shares and external storages

2017-04-20 11:21 UTC, icewind1991 requested changes

2017-04-20 11:21 UTC, icewind1991 commented on lib/private/legacy/helper.php
> +			$rootInfo = \OC\Files\Filesystem::getFileInfo($path, 'ext');
It should still only apply external storages when the config is set.

```php
$rootInfo = \OC\Files\Filesystem::getFileInfo($path, $includeExtStorage ? 'ext' : false);
```

2017-04-28 10:59 UTC, rullzer commented
@Ardinis could you address the comments of @icewind1991 ?

2017-04-29 13:58 UTC, MorrisJobke approved these changes

2017-04-29 14:04 UTC, MorrisJobke commented
Could you also have a look at the failing unit test:

```
1) Test\HelperStorageTest::testGetStorageInfoIncludingExtStorageWithNoUserQuota
Failed asserting that 22 matches expected 5.
/drone/src/github.com/nextcloud/server/tests/lib/HelperStorageTest.php:162
```

And could you squash all your commits into one, because 3 commits is a bit much for a 1 line change :wink:

And if this commit then also would have a sign-off I would be more than happy :) https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

2017-05-11 16:38 UTC, MorrisJobke commented
I fixed the unit tests: #4816

2017-05-11 16:38 UTC, closed without merging