Move oc_file_metadata.metadata migration to a background job
nextcloud/server pull request #43580
Opened 2024-02-14 16:08 UTC by artonge

Fix https://github.com/nextcloud/server/issues/43571

2024-02-15 09:47 UTC, nickvergessen requested changes, later dismissed

2024-02-15 09:47 UTC, nickvergessen commented on core/BackgroundJobs/MetadataMigrationJob.php
> +		$schema->getTable('oc_file_metadata')->dropColumn('metadata');
Doing DB schema changes in background jobs is not okay!

2024-02-15 14:16 UTC, artonge commented on core/BackgroundJobs/MetadataMigrationJob.php
> +		$schema->getTable('oc_file_metadata')->dropColumn('metadata');
Should I move that in a repair step?

2024-02-21 10:38 UTC, nickvergessen commented on core/BackgroundJobs/MetadataMigrationJob.php
> +		$schema->getTable('oc_file_metadata')->dropColumn('metadata');
Or you just add it as a migration step on the next major?

2024-02-21 12:03 UTC, artonge commented on core/BackgroundJobs/MetadataMigrationJob.php
> +		$schema->getTable('oc_file_metadata')->dropColumn('metadata');
But it would be impossible to know whether all the data has been migrated.

2024-02-22 10:41 UTC, artonge commented on core/BackgroundJobs/MetadataMigrationJob.php
> +		$schema->getTable('oc_file_metadata')->dropColumn('metadata');
I moved the logic into the repair step, should be cleaner :)

2024-02-22 15:47 UTC, skjnldsv commented
```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh

```

2024-02-22 16:00 UTC, nickvergessen commented on lib/private/Repair/AddMetadataMigrationJob.php
> +		if ($result->rowCount() === 0) {
Should write to output that we are performing a schema change, in case it takes long

2024-02-22 17:05 UTC, sorbaugh approved these changes

2024-02-22 17:06 UTC, nickvergessen commented on core/BackgroundJobs/MetadataMigrationJob.php
> +			->where($selectQuery->expr()->neq('metadata', $selectQuery->createNamedParameter(''), IQueryBuilder::PARAM_STR))
Also notEmptyString here, sorry

2024-02-22 17:33 UTC, ArtificialOwl approved these changes

2024-02-22 19:33 UTC, merged

2024-11-25 16:25 UTC, max-nextcloud commented
/backport to stable26