enh(setting): Migrate OCM / OCS provider tests to SetupCheck
nextcloud/server pull request #43607
Opened 2024-02-15 17:13 UTC by susnux

## Summary

Migrate the ocs-provider and ocm-provider from legacy to SetupCheck.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-19 13:53 UTC, come-nc requested changes, later dismissed

2024-02-19 13:53 UTC, come-nc commented on apps/settings/tests/SetupChecks/OcxProvicersTest.php
> +	private $setupcheck;
```suggestion
	private IL10N $l10n;
	private IConfig $config;
	private IURLGenerator $urlGenerator;
	private IClientService $clientService;
	private LoggerInterface $logger;
	private OcxProviders $setupcheck;
```

2024-02-19 13:53 UTC, come-nc commented on apps/settings/lib/SetupChecks/OcxProviders.php
> +			'admin-nginx',
You need to use the url generator to build the link here, see the other checks for inspiration

2024-02-19 18:58 UTC, susnux commented on apps/settings/tests/SetupChecks/OcxProvicersTest.php
> +	private $setupcheck;
Not sure here we use the comments everywhere else and at least for me removing them breaks my IDE as then `$this->setupcheck->expects($this->exactly(2))` will be undefined as `OcxProviders` has no method `expects` but only `MockObject` has.

2024-02-19 18:58 UTC, susnux commented on apps/settings/lib/SetupChecks/OcxProviders.php
> +			'admin-nginx',
Ah yes sorry!

2024-02-20 07:53 UTC, nickvergessen commented on apps/settings/tests/SetupChecks/OcxProvicersTest.php
> +	private $setupcheck;
```suggestion
	private IL10N|MockObject $l10n;
	private IConfig|MockObject $config;
	private IURLGenerator|MockObject $urlGenerator;
	private IClientService|MockObject $clientService;
	private LoggerInterface|MockObject $logger;
	private OcxProviders|MockObject $setupcheck;
```

2024-02-20 07:59 UTC, come-nc commented on apps/settings/tests/SetupChecks/OcxProvicersTest.php
> +	private $setupcheck;
Hum yeah never thought about that, I always typed as the target interface/class.
You’d need an intersection type to be precise I suppose, but that’s not possible on 8.0.

2024-02-26 14:04 UTC, susnux commented
Resolved all comments, please re-review :)

2024-02-27 10:56 UTC, skjnldsv approved these changes

2024-02-27 10:58 UTC, skjnldsv commented
```diff
- enh(setting): Migrate OCM / OCS provider tests to SetupCheck 
+ feat(setting): Migrate OCM / OCS provider tests to SetupCheck 
```

2024-02-27 11:08 UTC, come-nc approved these changes

2024-02-28 14:02 UTC, merged