enh: breadcrumbs icons are now more visually descriptive
nextcloud/server pull request #43604
Opened 2024-02-15 15:25 UTC by emoral435

* Resolves #43569
* Needs nextcloud-libraries/nextcloud-vue#5216

## Summary
* Changed the name path to be something more descriptive for the "/" path, such as the view name
* All base path urls "/". now are accompanied with descriptive text. perhaps aria-description is no longer needed?

🏡 After
-
![firefox_FroddX5muA](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/92754606-71d9-4fae-b3b4-77ca17d6b148)
-

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-15 15:26 UTC, emoral435 commented
/backport 9923cc77dbb87ba448f6111b42bb1b775646dc15 to stable28

2024-02-15 15:35 UTC, emoral435 commented on apps/files/src/components/BreadCrumbs.vue
> +				return t('files', '{viewName}', {viewName: this.$navigation.active.name}) // FOR TRANSLATORS: gets the views current name, e.g. "All files", "Recent", "Favorites" etc
Gotcha! I wasn't sure if this was the use case for the third argument in t, but will change!

2024-02-15 16:15 UTC, skjnldsv approved these changes

2024-02-15 16:16 UTC, skjnldsv requested changes

2024-02-15 16:16 UTC, skjnldsv commented on apps/files/src/components/BreadCrumbs.vue
> +				return t('files', this.$navigation.active.name)
Huuu, no
```suggestion
				return this.$navigation.active.name || t('files', 'Home')
```

2024-02-16 01:50 UTC, emoral435 commented on apps/files/src/components/BreadCrumbs.vue
> +				return t('files', this.$navigation.active.name)
Agree with this change, translating the already translated view name was a mistake on my part, thank you for the catch!

2024-02-16 09:35 UTC, skjnldsv reviewed
Could we also use the Section icon line 38 ?

2024-02-16 14:32 UTC, emoral435 commented
![firefox_GwmTNd6Mwx](https://github.com/nextcloud/server/assets/110193237/5e3169f6-196f-40e2-98e6-759fe62fc95a)

I think this looks much cleaner now, good suggestion!

2024-02-16 15:01 UTC, szaimen commented
> I think this looks much cleaner now, good suggestion!

Agreed 🤩

2024-02-16 15:02 UTC, skjnldsv commented on apps/files/src/components/BreadCrumbs.vue
>  			</template>
I think otherwise it will display the icon for all `index > 0`

``suggestion
			<template v-if="index === 0" #icon>
				<NcIconSvgWrapper v-if="section.icon" :size="20" :svg="section.icon" />
				<Home v-else :size="20"/>
			</template>
```

2024-02-16 15:03 UTC, skjnldsv commented
/backport to stable28

2024-02-16 15:10 UTC, skjnldsv approved these changes

2024-02-16 15:34 UTC, szaimen approved these changes
LGTM from design perspective :)

2024-02-16 15:43 UTC, skjnldsv commented
/compile

2024-02-16 16:08 UTC, merged

2024-02-16 16:13 UTC, skjnldsv commented
/backport to stable28

2024-02-16 16:22 UTC, skjnldsv commented
wtf

2024-02-16 16:23 UTC, skjnldsv commented
/backport to stable28

2024-02-16 16:30 UTC, skjnldsv commented
/backport to stable28