fix(AppFramework): Correctly implement CSRF checks
nextcloud/server pull request #43699
Opened 2024-02-20 16:16 UTC by provokateurin

## Summary

These changes ensure that actually all the CSRF protection methods can be correctly used.
Previously they were nested in weird ways (cookie and header) and a lot of the code was just horrible and incorrect.
If a request passes any of the CSRF protections then it is good to go, but before this change for some scenarios you had to pass multiple ones.
The tests were also not great and many quite obsolete so I had to fix that as well.
As far as I can see there were no security problems before and this does not open any new ones :tm:

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-02-21 08:01 UTC, nickvergessen requested changes
Seems to break cypress?

2024-02-21 08:05 UTC, ChristophWurst commented on lib/private/AppFramework/Http/Request.php
> +		return $this->getHeader('OCS-APIREQUEST') || $this->passesStrictCookieCheck() || $this->passesCSRFTokenCheck();
this means the check passes if strict cookies are sent but no or an invalid no CSRF token. should it be `&&`?

2024-02-21 10:07 UTC, provokateurin commented on lib/private/AppFramework/Http/Request.php
> +		return $this->getHeader('OCS-APIREQUEST') || $this->passesStrictCookieCheck() || $this->passesCSRFTokenCheck();
From my understanding either of the methods are fine, so this should be correct.

2024-02-22 15:23 UTC, come-nc commented
Code looks good but I do not know the situation well enough to say if it’s okay to require only one method to pass.

2024-02-28 16:07 UTC, provokateurin commented on lib/private/AppFramework/Http/Request.php
> +		return $this->getHeader('OCS-APIREQUEST') || $this->passesStrictCookieCheck() || $this->passesCSRFTokenCheck();
I started reading some literature about this topic and you are right.
By allowing the request if it passes the cookie check an evil actor that is already on your server could send you a compromised link (e.g. as a Talk message) and it would execute just fine because you are already on the correct host and send the cookies.

To my understanding the cookie check is actually not doing anything at all and doesn't give us any additional protection, because it will not protect against the attack mentioned above and the other methods already provide sufficient protection (especially since very old browsers (7+ years) treat same-site cookies as normal cookies).

The header is a sufficient way to protect against CSRF attacks because there is no way for an attacker to set it in a malicious request.

2024-02-28 18:54 UTC, ChristophWurst commented on lib/private/AppFramework/Http/Request.php
> +		return $this->getHeader('OCS-APIREQUEST') || $this->passesStrictCookieCheck() || $this->passesCSRFTokenCheck();
Makes sense!

2024-03-14 12:27 UTC, provokateurin commented
I rewrote this PR from scratch with the new information I had. This should be much easier to review. The main problem before was concerning the cookie checks which I didn't understand correctly, but now I also added documentation for the next people who will look at it...

2024-03-14 14:48 UTC, come-nc reviewed
In the end what is the behavior change brought by this PR?

2024-03-14 14:53 UTC, provokateurin commented
It allows using the OCS-APIRequest header to bypass CSRF checks. For clients this is necessary, so they don't have to deal with CSRF tokens. Both methods are safe, but the former was not possible until now.

2024-03-14 15:26 UTC, nickvergessen commented
So nothing for 29 during freeze :speak_no_evil:

2024-03-14 15:27 UTC, provokateurin commented
I guess so :/

2024-04-02 13:36 UTC, provokateurin commented
Since the branch-off is done, can I get reviews to get it into Nextcloud 30?

2024-04-02 14:01 UTC, come-nc approved these changes

2024-05-03 13:28 UTC, provokateurin commented
@nickvergessen @ChristophWurst Can I get your reviews?

2024-05-03 14:32 UTC, Altahrim commented on lib/private/AppFramework/Http/Request.php
> +	 * If the OCS-APIRequest is set or a valid CSRF token is sent the request will to pass.
```suggestion
	 * If the OCS-APIRequest is set or a valid CSRF token is sent the check will succeed.
```

2024-05-03 14:32 UTC, Altahrim commented on lib/private/AppFramework/Http/Request.php
> +		}
I think we can move this condition before the `passesStrictCookieCheck`. It saves a few calls.

2024-05-03 14:32 UTC, Altahrim commented on lib/private/AppFramework/Http/Request.php
> +	 * In case the OCS-APIRequest header is set or the user has no session, we don't to check the cookies because the client is not a browser and thus doesn't need CSRF checks.
```suggestion
	 * In case the OCS-APIRequest header is set or the user has no session, we don't need to check the cookies because the client is not a browser and thus doesn't need CSRF checks.
```

2024-05-03 15:30 UTC, provokateurin commented on lib/private/AppFramework/Http/Request.php
> +		}
I agree, although I think it makes sense to always validate the cookies. If invalid cookies are sent they should be rejected regardless of the header.

2024-05-05 21:57 UTC, nickvergessen commented on tests/lib/AppFramework/Http/RequestTest.php
> +	public function testFailsCSRFCheckWithInvalidToken($invalidToken) {
We usually try to follow the pattern `test...MethodName...ScenarioDescription()`, since the method to test is called `passesCSRFCheck()` the old name matches the pattern, but I also see how it can be confusing in this case. The problem is the actual method name, but we should also not change that... So maybe just stick with the old name of test cases.

2024-05-06 04:11 UTC, provokateurin commented on tests/lib/AppFramework/Http/RequestTest.php
> +	public function testFailsCSRFCheckWithInvalidToken($invalidToken) {
Ah I see, I thought the `passes` was from the it passes/fails and not from the method name. I agree that the method name is not good :+1:

2024-05-06 07:16 UTC, Altahrim commented on lib/private/AppFramework/Http/Request.php
> +		}
According to the *current* code, `passesStrictCookieCheck` basically return `true` if `OCS-APIRequest`  is not empty. It saves two function call.
Your solution is more future proof ^^

2024-05-06 07:16 UTC, Altahrim approved these changes

2024-05-10 07:06 UTC, bigcat88 approved these changes

2024-07-25 15:47 UTC, provokateurin commented
I made a minimal version of these changes that only include the actual fix and leaves out all the refactoring and documentation: https://github.com/nextcloud/server/pull/46760

2024-07-27 14:33 UTC, closed without merging