fix(files): Open new file when created from template
nextcloud/server pull request #43941
Opened 2024-03-01 17:30 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/42097

## Summary
Fix a small bug from https://github.com/nextcloud/server/pull/42993 where the, not implemented, `node:focus` event was used instead of changing the route.

### Screencast

https://github.com/nextcloud/server/assets/1855448/32d3ad84-634a-448c-80b0-ebd7ee38df66

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-01 17:31 UTC, susnux commented
/backport to stable28

2024-03-04 16:22 UTC, skjnldsv approved these changes

2024-03-05 10:54 UTC, Pytal requested changes

2024-03-05 10:54 UTC, Pytal commented on apps/files/src/views/TemplatePicker.vue
> +					{ dir: node.dirname, openfile: 'true' },
```suggestion
					{ dir: node.dirname, openfile: true },
```
From the code it should be boolean? https://github.com/nextcloud/server/blob/d65e46f31367e65b03d4ab829baeacbece04850a/apps/files/src/components/FilesListVirtual.vue#L212

2024-03-05 17:13 UTC, Pytal approved these changes

2024-03-05 17:20 UTC, skjnldsv commented on apps/files/src/views/TemplatePicker.vue
> +					{ dir: node.dirname, openfile: 'true' },
the API doesn't accept boolean :)
But that did trigger an interesting question, and after checking, if you want `&openfile` and not `&openfile=true`, which I thought the boolean would do, you need to use `null` :see_no_evil: 

![image](https://github.com/nextcloud/server/assets/14975046/f5711ea2-50c5-4dd1-9a08-d584d345a1e6)

2024-03-05 17:21 UTC, skjnldsv commented on apps/files/src/views/TemplatePicker.vue
> +					{ dir: node.dirname, openfile: 'true' },
Also, the openfile watcher is watching the computed, which doesn't care about the value, it just checks if it's there or not ;)
https://github.com/nextcloud/server/blob/8be4704e1125b6eb6fe17a58c8b54c651fa40c0c/apps/files/src/components/FilesListVirtual.vue#L159-L161

2024-03-05 17:21 UTC, merged

2024-03-05 22:56 UTC, susnux commented
/backport to stable28