feat: Provide app-updated notifications for users
nextcloud/server pull request #43967
Opened 2024-03-03 21:38 UTC by susnux

* Part of #9165 

## Summary
This provides information on what changed on an app update for users:
If notifications are enabled users will receive a notification for an app update if that app is enabled for that user.
The update notification is only provided if a changelog exists, to allow technical changelog and user changelogs following logic is applied:
As per appstore documentation *CHANGELOG.md* is used for technical changelogs (e.g. developers or administrators).
For users the *CHANGELOG.{code}.md* file is used (`{code}` is the language code), and it falls back to *CHANGELOG.en.md* if the requested language is missing.

Meaning: For user changelog *CHANGELOG.{lang}.md* with fallback *CHANGELOG.en.md* is used, for admins or developers use *CHANGELOG.md*.

**This is best tested with:** 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-04 01:35 UTC, nickvergessen requested changes

2024-03-04 01:35 UTC, nickvergessen commented on apps/updatenotification/lib/Controller/APIController.php
> +		protected Manager $manager,
Undefined class, missing autoloader update

2024-03-04 01:35 UTC, nickvergessen commented on apps/updatenotification/lib/BackgroundJob/ResetToken.php
> +class ResetToken extends TimedJob {
This breaks queued jobs?

2024-03-04 01:35 UTC, nickvergessen commented on apps/updatenotification/lib/Notification/AppUpdateNotifier.php
> +					$l->t('{app} was updated to version %1$s', [$appInfo['version']]),
Make version a highlight parameter so it's visible?

2024-03-04 01:35 UTC, nickvergessen commented on lib/public/RichObjectStrings/Definitions.php
> +		'app-changelog' => [
API feature freeze was already and this needs adjustments in all the mobile and desktop clients.

Also the notification is unusable on them because the content is generated via a hack with frontend code at the moment instead of the notification message containing all the information that is needed to display it.

Maybe it would be better to go with a WEB action button (exists already for various things) at the moment that opens a frontpage/webview and therefore does not need client changes

2024-03-04 01:35 UTC, nickvergessen commented on apps/updatenotification/lib/Notification/AppUpdateNotifier.php
> +						'type' => 'app-changelog',
This is problematic at this point

2024-03-04 01:35 UTC, nickvergessen commented on apps/updatenotification/lib/Notification/AppUpdateNotifier.php
> +				'{changes}',
When apps don't understand a parameter type, they simply replace it with the name in bold. So mobile and desktop clients will show the app name as a message.

You added the actual message into the vue handling in the notifications app, which is not very good for these cases.

But even then, the notification is quite useless in mobile apps. I'd go with an action (not parameter) with WEB type, and then you could do the magic dialog on that page when loaded from a client, and when clicked from the web interface you can intercept the action and instead of redirecting open the modal/dialog directly.

2024-03-04 10:12 UTC, susnux commented on apps/updatenotification/appinfo/routes.php
> +		['name' => 'API#getAppList', 'url' => '/api/{apiVersion}/applist/{newVersion}', 'verb' => 'GET', 'requirements' => ['apiVersion' => '(v1(\.\d)?)']],
Ah ok, tried to follow the REST API here. But will revert

2024-03-04 10:26 UTC, susnux commented on apps/updatenotification/lib/BackgroundJob/AppUpdatedNotifications.php
> +			if ($guestsEnabled && ($user->getBackend() instanceof ('\OCA\Guests\UserBackend'))) {
Same like with the announcementcenter, but will ask if the feature should be also provided for guests.

BTW, removing the brackets will result in errors of my IDE and if I understand PHP syntax here correctly only classes can be passed, any strings for class names need to be put into brackets?

![Screenshot_20240304_112420](https://github.com/nextcloud/server/assets/1855448/b8ccf173-3da4-473e-9aa3-426374c549df)

2024-03-04 10:28 UTC, susnux commented on apps/updatenotification/lib/BackgroundJob/ResetToken.php
> +class ResetToken extends TimedJob {
You mean the rename? So I should let it be located where it was?
Dont you think it makes sense to group them into `BackgroundJob` folder?

Maybe remove all scheduled jobs and reschedule after update with the new name?

2024-03-04 10:41 UTC, susnux commented on apps/updatenotification/lib/Controller/APIController.php
> +		protected Manager $manager,
No it is included in the classmap and autoloader, but no idea why reported that

2024-03-05 11:08 UTC, susnux commented
How to test?
Install current master and enable the "QA testing" app, then checkout this branch which will update that app and should show you then a updated notification for "QA testing" like in the initial post.

2024-03-05 12:07 UTC, nickvergessen commented on apps/updatenotification/lib/BackgroundJob/AppUpdatedNotifications.php
> +			if ($guestsEnabled && ($user->getBackend() instanceof ('\OCA\Guests\UserBackend'))) {
Ah, I missed the string part on the phone. I guess instanceof only works when the class is known, unlike `::class`.

But you could use `$user->getBackendClassName === \OCA\Guests\UserBackend::class` then?

2024-03-05 12:09 UTC, nickvergessen commented on apps/updatenotification/lib/BackgroundJob/ResetToken.php
> +class ResetToken extends TimedJob {
> You mean the rename? So I should let it be located where it was?
> …
> Maybe remove all scheduled jobs and reschedule after update with the new name?

That would work.

> Dont you think it makes sense to group them into BackgroundJob folder?

Of course it's cooler, but only if it doesn't cause issues, so make sure existing tokens are reset properly and I'm fine. (Basically just queue the job once on migration? - Didn't fully check but that should work?)

2024-03-05 14:35 UTC, come-nc commented
@susnux installation is failing in CI

2024-03-05 16:36 UTC, come-nc commented on apps/updatenotification/lib/Manager.php
> +		$index = array_key_first(
Comment needed

2024-03-06 10:39 UTC, nickvergessen commented on apps/updatenotification/lib/Controller/ChangelogController.php
> +		$changes = explode("\n", $changes, 2);
Argument 2 of explode cannot be null, possibly null value provided

2024-03-06 15:21 UTC, come-nc approved these changes

2024-03-06 16:54 UTC, nickvergessen commented on apps/updatenotification/lib/AppInfo/Application.php
> +		$appConfig = \OCP\Server::get(IAppConfig::class);
Is 
```json
{"reqId":"gddlfa00oTI7KGIJDRfl","level":4,"time":"2024-03-06T17:48:16+01:00","remoteAddr":"","user":"--","app":"updatenotification","method":"","url":"--","message":"Error during app service registration: Could not resolve OCP\\AppFramework\\Services\\IAppConfig! Class can not be instantiated","userAgent":"--","version":"29.0.0.6","exception":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCP\\AppFramework\\Services\\IAppConfig! Class can not be instantiated","Code":0,"Trace":[{"file":"…/lib/private/AppFramework/Utility/SimpleContainer.php","line":146,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"…/lib/private/ServerContainer.php","line":173,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"…/lib/private/AppFramework/Utility/SimpleContainer.php","line":64,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"…/lib/public/Server.php","line":55,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"…/apps/updatenotification/lib/AppInfo/Application.php","line":63,"function":"get","class":"OCP\\Server","type":"::"},{"file":"…/lib/private/AppFramework/Bootstrap/Coordinator.php","line":142,"function":"register","class":"OCA\\UpdateNotification\\AppInfo\\Application","type":"->"},{"file":"…/lib/private/AppFramework/Bootstrap/Coordinator.php","line":94,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"…/lib/private/Installer.php","line":128,"function":"runLazyRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"…/core/Command/App/Enable.php","line":110,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"…/core/Command/App/Enable.php","line":80,"function":"enableApp","class":"OC\\Core\\Command\\App\\Enable","type":"->"},{"file":"…/appspackaged/photos/vendor/symfony/console/Command/Command.php","line":298,"function":"execute","class":"OC\\Core\\Command\\App\\Enable","type":"->"},{"file":"…/appspackaged/photos/vendor/symfony/console/Application.php","line":1040,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"…/appspackaged/photos/vendor/symfony/console/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"…/appspackaged/photos/vendor/symfony/console/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"…/lib/private/Console/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"…/console.php","line":113,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"…/occ","line":11,"args":["…/console.php"],"function":"require_once"}],"File":"…/lib/private/AppFramework/Utility/SimpleContainer.php","Line":130,"message":"Error during app service registration: Could not resolve OCP\\AppFramework\\Services\\IAppConfig! Class can not be instantiated","exception":{},"CustomMessage":"Error during app service registration: Could not resolve OCP\\AppFramework\\Services\\IAppConfig! Class can not be instantiated"}}
```

What you just pushed? Or is the problem why I don't see notifications?

2024-03-06 21:54 UTC, susnux commented on apps/updatenotification/lib/Migration/Version011901Date20240305120000.php
> +		$hasOldResetToken = $this->joblist->has('\OCA\UpdateNotification\ResetTokenBackgroundJob', null);
TIL! Nice to know thought it would fail if the class is unavailable.

2024-03-06 21:58 UTC, susnux commented on apps/updatenotification/lib/AppInfo/Application.php
> +		$appConfig = \OCP\Server::get(IAppConfig::class);
Wrong DI, fixed that

2024-03-07 09:06 UTC, nickvergessen commented on apps/updatenotification/lib/Migration/Version011901Date20240305120000.php
> +		$hasOldResetToken = $this->joblist->has('\OCA\UpdateNotification\ResetTokenBackgroundJob', null);
> Nice to know thought it would fail if the class is unavailable.

Nop, still works, but the IDE and Psalm will at least tell you that it doesn't know the class.

2024-03-07 18:34 UTC, sorbaugh approved these changes

2024-03-07 18:35 UTC, AndyScherzinger approved these changes

2024-03-07 21:44 UTC, merged