feat: allow limit unified search to folder
nextcloud/server pull request #43963
Opened 2024-03-03 10:54 UTC by Fenn-CS

## Summary

* Resolves: https://github.com/nextcloud/server/issues/42915

## TODO

- [ ] ...

2024-03-05 22:31 UTC, emoral435 commented on core/src/unified-search.ts
> +    callback: () => void;
Can this callback function have a bit more clarification on what it should handle / output / what state it changes? I agree with the other reviewers that this is a bit generic

2024-03-07 12:56 UTC, Fenn-CS commented on core/src/unified-search.ts
> +    callback: () => void;
However that would need another PR in spreed so I added this to list of todo's for the API rewrite.

https://github.com/nextcloud/server/issues/44060

2024-03-07 13:05 UTC, Fenn-CS reviewed
Invitation to check if provider and structure of call is correct...

cc: @Altahrim 

Thanks in advance :)

2024-03-07 13:05 UTC, Fenn-CS commented on apps/files/src/plugins/search/folderSearch.ts
> +								filterParams: { path: folder.attributes.filename },
This would to requests such as

```sh
GET http://local.nextcloud.test/ocs/v2.php/search/providers/files/search?term=m&from=/apps/files/files/100?dir=/&path=/files/Admin/Notes
```

Where `/files/Admin/Notes` is that `path` query passed, however, this call returns empty results when it should not in manual tests...

2024-03-07 13:44 UTC, skjnldsv requested changes

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +		console.debug('Initializing unified search plugin: folder search from files app')
No console.debug please.
Use a logger

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +
Please import your own translate in your components and use `window.OCA` instead
```suggestion
```

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +(function(OC: any, OCA: any, t: any) {
You do not need to register your init this way

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +import { getFilePickerBuilder } from '@nextcloud/dialogs';
```suggestion
import type { Node } from '@nextcloud/files'

import { emit } from '@nextcloud/event-bus'
import { getFilePickerBuilder } from '@nextcloud/dialogs';
import { getRequestToken } from '@nextcloud/auth'
import { imagePath } from '@nextcloud/router'
import { translate, translatePlural } from '@nextcloud/l10n'

import Vue from 'vue'
import '@nextcloud/dialogs/style.css'
```

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +							console.debug('Folder picked', nodes[0])
No console.debug

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +								filterParams: { path: folder.attributes.filename },
```suggestion
								filterParams: { path: folder.dirname },
```

https://nextcloud-libraries.github.io/nextcloud-files/classes/File.html#dirname

2024-03-07 13:44 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +	// eslint-disable-next-line
```suggestion
```

This should not be needed unless you actually dynamically import components

2024-03-07 14:22 UTC, skjnldsv commented on apps/files/src/plugins/search/folderSearch.ts
> +    });
```suggestion
	const OCA = window.OCA
	if (!OCA.UnifiedSearch) {
		return;
	}

	logger.info('Initializing unified search plugin: folder search from files app');
	OCA.UnifiedSearch.registerFilterAction({
		id: 'files',
		appId: 'files',
		label: t('files', 'In Folder'),
		icon: imagePath('files', 'app.svg'),
		callback: () => {
			const filepicker = getFilePickerBuilder('Pick plain text files')
				.addMimeTypeFilter('httpd/unix-directory')
				.allowDirectories(true)
				.addButton({
					label: 'Pick',
					callback: (nodes: Node[]) => {
						logger.info('Folder picked', { folder: nodes[0] })
						const folder = nodes[0]
						emit('nextcloud:unified-search:add-filter', {
							id: 'files',
							payload: folder,
							filterUpdateText: t('files', 'Search in folder: {folder}', { folder: folder.basename }),
							filterParams: { path: folder.path },
						})
					},
				})
				.build()
			filepicker.pick()
		},
	})
```

2024-03-07 14:51 UTC, skjnldsv approved these changes

2024-03-07 16:32 UTC, Fenn-CS commented on apps/files/src/plugins/search/folderSearch.ts
> +		label: t('files', 'In Folder'),
Thanks fixed.

2024-03-07 16:33 UTC, Fenn-CS reviewed
For reviewers.

2024-03-07 16:33 UTC, Fenn-CS commented on apps/files/composer/composer/autoload_static.php
> +class ComposerStaticInitFiles {
There is separate commit for this formatting change, done my cs:fix to help reviewers.

2024-03-07 16:39 UTC, susnux approved these changes

2024-03-07 16:45 UTC, Fenn-CS commented
/compile /

2024-03-07 17:42 UTC, emoral435 approved these changes

2024-03-07 19:16 UTC, blizzz commented
@Fenn-CS signoff is missing in commit 3f1fb419073e35d96d73d3edce6cba45867a85c5

2024-03-07 19:20 UTC, Fenn-CS commented
> @Fenn-CS signoff is missing in commit https://github.com/nextcloud/server/commit/3f1fb419073e35d96d73d3edce6cba45867a85c5

Thanks for catching, resolved :)

2024-03-07 19:59 UTC, blizzz commented
other CI is also red though :(

2024-03-07 20:13 UTC, Fenn-CS commented
/compile /

2024-03-07 20:47 UTC, merged