fix/file widget viewer
nextcloud/server pull request #44076
Opened 2024-03-08 08:16 UTC by juliushaertl

- fix: Open viewer on simple file widget
- chore: Bump bundles

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-08 11:30 UTC, mejo- approved these changes

2024-03-08 15:03 UTC, skjnldsv requested changes
It was done on purpose, you cannot open viewer on text as text us already using viewer. It will close the text app.

Can you explain the context? :)

2024-03-09 08:17 UTC, skjnldsv commented
> I don't quite remember how the behavior was if this is triggered trough text in viewer still

It wasn't. The Vue event was missing a stop and therefore the behaviour was unstable and still opening the file as if the link was clicked.

I suggest the following, until we support multiple viewer, on top of checking if Viewer supports the mime, please also check if a file is already opened in it. 
Something like `!OCA.Viewer.file` should work 😊

2024-03-11 07:20 UTC, juliushaertl commented
Thanks, adjusted

2024-03-11 13:53 UTC, emoral435 approved these changes

2024-03-11 17:07 UTC, merged