Update AppItem.vue
nextcloud/server pull request #44096
Opened 2024-03-08 19:20 UTC by linuzer

fix scrolling for Safari-Browser.
#42249

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-12 11:43 UTC, ShGKme requested changes

2024-03-12 11:43 UTC, ShGKme commented on apps/settings/src/components/AppList/AppItem.vue
>    right: 0;
Removing `position: absolute` should be together with `inset` values - `top`, `left` etc. They doesn't work for static position. And without absolution position the whole `::after` doesn't work, it has no size.

But this pseudo-element `::after` was added intentionally. It allowed to click on the table row like it is a link. Without it, you need to click exactly on the text to open sidebar.

If it is removed, we need some alternative here. Or find the reason, why having it breaks Safari. I'll have a look in 2-3 hours on Safari.

![image](https://github.com/nextcloud/server/assets/25978914/b509e75b-582b-4a4e-8883-001ca0bf7ea3)

2024-03-12 23:40 UTC, ShGKme commented on apps/settings/src/components/AppList/AppItem.vue
>    right: 0;
This is a known Safari behavior. According to the standard, `position` behavior on `TR` is not defined. While it works fine in other browsers, Safari does not allow to set the position.

https://bugs.webkit.org/show_bug.cgi?id=240961

2024-03-17 18:35 UTC, linuzer commented on apps/settings/src/components/AppList/AppItem.vue
>    right: 0;
I see what you say, but unfortunately I am not able to provide a better solution.

For the time being until someone finds a better solution or Safari provides a fix, I personally would prefer to have a working app management page with a "too-small" link on the app-name rather than a broken page. But that's just my 2 cents.

2024-03-19 16:12 UTC, ShGKme commented
Fixed in https://github.com/nextcloud/server/pull/44236

2024-03-19 16:12 UTC, closed without merging

2024-03-19 22:22 UTC, linuzer commented on apps/settings/src/components/AppList/AppItem.vue
>    right: 0;
No, thank you for this far better solution! 👍