feat: Refactor app & account management UI code
nextcloud/server pull request #44092
Opened 2024-03-08 18:07 UTC by susnux

## Summary

1. Separate app store from account management
2. Split app and account management into better maintainable smaller pieces
   * Separate app content and app navigation component
   * Also split app store sidebar into own components for each tab.
   * The details tab now includes the same information like the sidebar on `apps.nextcloud.com`
3. Everything I needed to touch more then copy paste was refactored to TypeScript
4. Start using Pinia for the app store (currently only the navigation -> rest will be follow up)
5. Fix #42998 by using inline icons for the app navigation
   * Use same icons on the app store navigation as used for `apps.nextcloud.com`  that got a recent design overhaul.

## Screenshots

![Screenshot 2024-03-08 at 18-42-21 Office   text - Apps - Nextcloud](https://github.com/nextcloud/server/assets/1855448/bcfdf13e-e9af-4640-a834-cb74124a2f79)
![Screenshot 2024-03-08 at 18-42-14 Office   text - Apps - Nextcloud](https://github.com/nextcloud/server/assets/1855448/f359a45a-d3b2-4329-916f-8d6989eacf58)
![Screenshot 2024-03-08 at 18-42-07 Office   text - Apps - Nextcloud](https://github.com/nextcloud/server/assets/1855448/4bcdfbb9-1ebd-4bfa-99b3-65f1190c3902)
![Screenshot 2024-03-08 at 18-34-40 Office   text - Apps - Nextcloud](https://github.com/nextcloud/server/assets/1855448/ff932aaa-07ab-4869-a25c-f43b02658a36)
![Screenshot 2024-03-08 at 18-32-47 Integration - Apps - Nextcloud](https://github.com/nextcloud/server/assets/1855448/61d36480-e8e7-4024-86b5-d968a9d06c0d)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-10 17:11 UTC, emoral435 reviewed
Really great PR, loved seeing `typeof === 'undefined'` 👀

2024-03-10 20:30 UTC, susnux commented on apps/settings/src/composables/useAppIcon.ts
> +		return path ? `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="${path}" /></svg>` : null
Good idea! Fixed

2024-03-10 20:33 UTC, susnux commented on apps/settings/src/views/AppStore.vue
> +	- @copyright Copyright (c) 2018 Julius Härtl <jus@bitgrid.net>
Not really we use both... but reverted here :)

2024-03-10 22:10 UTC, emoral435 commented on apps/settings/src/components/AppStoreSidebar/AppReleasesTab.vue
> +import { computed, watch } from 'vue'
I do not mind! Especially because we will eventually be migrating to Vue3. I do not know if we will be sticking with options vs composition api, I prefer composition, but we will see 😋

2024-03-10 22:11 UTC, emoral435 approved these changes
really nice :)

2024-03-11 09:33 UTC, artonge approved these changes

2024-03-11 09:33 UTC, artonge commented on apps/settings/src/main-apps-users-management.ts
> +Vue.prototype.OCA = window.OCA
Is it still needed?

2024-03-11 09:33 UTC, artonge commented on apps/settings/src/views/AppStore.vue
> +const instance = getCurrentInstance()
Forgotten todo, or is it not possible now?

2024-03-11 09:37 UTC, szaimen requested changes, later dismissed
Looks great in general, but would be good if possible to have the button to download and enable in the header and not hidden in a tab. 
Dirty mockup: 
![image](https://github.com/nextcloud/server/assets/42591237/82387cdc-996c-4def-b2e1-68222f160d68)

2024-03-11 12:38 UTC, susnux commented on apps/settings/src/views/AppStore.vue
> +const instance = getCurrentInstance()
No this is a todo for a follow up - it is already too messy. Will do so soon but has no priority for beta2 tomorrow.

2024-03-11 12:40 UTC, susnux commented
> Looks great in general, but would be good if possible to have the button to download and enable in the header and not hidden in a tab.

@szaimen I fully agree, this is a leftover from the old / current design. But I would really like to do that in a follow up. This PR is already too huge. Is that ok for you?

2024-03-11 12:43 UTC, szaimen commented
> @szaimen I fully agree, this is a leftover from the old / current design. But I would really like to do that in a follow up. This PR is already too huge. Is that ok for you?

yes, fine for me. Shall I create an issue so that it doesnt get lost or do you want?

2024-03-11 15:21 UTC, merged

2024-03-29 16:03 UTC, gp994 commented
I've just upgraded Nextcloud to 28.0.4 but the bug on Safari is still present.
In which Version will it be fixed?
Thanks a lot

2024-03-29 16:20 UTC, susnux commented
@gp994 this one is not fixing safari. This bug was fixed for Nextcloud 29 here: https://github.com/nextcloud/server/pull/44236
And a backport is pending for Nextcloud 28 here: https://github.com/nextcloud/server/pull/44327