feat: author displayname and avatar on versions
nextcloud/server pull request #44109
Opened 2024-03-09 20:58 UTC by emoral435

**This is a stacked PR**
* Requires nextcloud-libraries/nextcloud-vue#5388
* Requires nextcloud/server#44049
* Resolves #35512 
* Resolves nextcloud-gmbh/customer-feature-requests#16

## Summary
With the aforementioned PR's, this PR will allow file_version to display the author and avatar for each version

🏡 New View
---|
![Code_Ek3YHm9VcZ](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/4647f14e-a09f-4147-bc80-86c6b5868ef5)|

## TODO
- [ ] Currently, the author name is just their UID. I still need to query for the authors display name, but then this PR should be done :)

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-14 13:53 UTC, emoral435 commented
This PR will only show the visual changes once NcVue gets a bump to use one of the chained PR's, but for now, no breaking changes are introduced with this PR, so this can get in before I go on vacation 👀

2024-03-14 13:59 UTC, susnux commented on apps/files_versions/src/components/Version.vue
> +					<div>•</div>
I think here a `v-if="versionLabel"` is missing?

2024-03-14 15:30 UTC, artonge approved these changes

2024-03-14 15:30 UTC, artonge commented on apps/files_versions/src/components/Version.vue
> +		<template #name>
Can the `name` attribute be removed then?

2024-03-14 16:10 UTC, nimishavijay requested changes
Awesome! What a cool feature! :) 
- [ ] I would only suggest that the positions of the avatar and name be exchanged, and the avatar size be decreased so that it looks a bit more like a user bubble
- [ ] everything in the first time can be in `--color-main-text` and everything on the subline can be `--color-text-maxcontrast` :)

![image](https://github.com/nextcloud/server/assets/52440189/bff74e94-b75e-499a-b9a9-456f301207ee)

2024-03-14 17:48 UTC, susnux commented on apps/files_versions/src/components/Version.vue
> +		<template #name>
should be

2024-03-14 19:24 UTC, emoral435 commented on apps/files_versions/src/components/Version.vue
> +		<template #name>
yep ! I didn't catch that, thank you :)

2024-03-14 21:00 UTC, emoral435 commented on apps/files_versions/src/components/Version.vue
> +					<div>•</div>
Yep! added :)

2024-03-14 21:07 UTC, emoral435 commented
<img width="357" alt="image" src="https://github.com/nextcloud/server/assets/110193237/fada52f5-5e05-4ba9-9358-a8cf99772cf6">

@nimishavijay 
I moved around the icon and the display name, and then fixed the coloring of the text :)

2024-03-14 21:13 UTC, susnux approved these changes

2024-03-15 02:27 UTC, emoral435 commented
waiting for a bump to `NcVue` and then this PR is ready :)

2024-03-15 09:48 UTC, nimishavijay approved these changes
🚀

2024-03-15 19:25 UTC, susnux commented
/compile

2024-03-15 22:44 UTC, merged

2024-06-14 13:22 UTC, Mika-6-9 commented
Hi,
Will this change be put on Nextcloud 27 and 28?