Added rate limit bypass for app_api requests
nextcloud/server pull request #44154
Opened 2024-03-12 10:21 UTC by nc-fkl

* Resolves: # 

## Summary

When doing a request via app_api the rate limiting prevents more than 5 requests per 2 minutes, with checking if the app_api session exsists we bypass the rate limiting for app_api requests.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

* Resolves: #

2024-03-12 10:23 UTC, nc-fkl commented
/backport to stable28

2024-03-12 10:28 UTC, nickvergessen requested changes
It's not okay to generally disable ratelimit like this.

Can you maybe point out which endpoint is a problem?

2024-03-12 10:29 UTC, bigcat88 approved these changes
Please, make squash commit with force push with correct message for "Block unconventional commits" check.

Added logic in this PR for me looks good, requests from ExApps should always bypass any rate limits.

2024-03-12 10:32 UTC, nickvergessen commented
> requests from ExApps should always bypass any rate limits.

Why is that? We have several API endpoints which have a rate limit also for logged in users.

2024-03-12 10:38 UTC, nc-fkl commented
> > requests from ExApps should always bypass any rate limits.
> 
> Why is that? We have several API endpoints which have a rate limit also for logged in users.
Hi,

we need to utilize ``/ocs/v2.php/textprocessing/schedule```multiple times in a short period of time, but every >= 6th request is failing because of ```429 too many requests```which is coming from the rate-limiting.

As a example we want to utilize some AI features for summarizing a long chatlog. We need to split the chatlog into multiple chunks (lets say 10 chunks) and for each we need to do a request to the ```/ocs/v2.php/textprocessing/schedule``` endpoint. 
For the first 5 its going well but then the rate limiting is blocking us to process the other requests also, therefore and also for other app_api requests in the future, we need to bypass the rate limiting for app_api requests.

2024-03-12 10:39 UTC, bigcat88 commented
> Why is that? We have several API endpoints which have a rate limit also for logged in users.

We need this for the Summurize bot (which was supposed to be released a week(?) ago..) calling text-processing endpoints to schedule a summarization task.
The bot does not have a user context; it is called from the background task.
As a result, it falls into the Anonymous rate limit (5 requests).
But the user rate limit is not enough for us too(20 requests), if the number of chats is more than 20, then the user rate limit will also work..

2024-03-12 10:42 UTC, nickvergessen commented
Then let's either bump or remove the user limit from that endpoint for now.
But removing rate limit completely is not an option!

2024-03-12 10:43 UTC, nickvergessen commented
Or additionally we add a AppAPIRateLimit attribute additionally which is checked in case the session flag is there and we fall back to the UserRateLimit if it's not set.

2024-03-12 10:48 UTC, bigcat88 commented
> Then let's either bump or remove the user limit from that endpoint for now. 

value of rate limit will depend on size of the Nextcloud instance, we can not know the value.

removing rate limit form that endpoint completely will allow to easy ddos cloud without even an account, as that endpoint allows anonymous access already..



> Or additionally we add a AppAPIRateLimit attribute additionally which is checked in case the session flag is there and we fall back to the UserRateLimit if it's not set.

Good proposal

2024-03-12 10:53 UTC, nickvergessen commented
> removing rate limit form that endpoint completely will allow to easy ddos cloud without even an account, as that endpoint allows anonymous access already.

Well AppAPI is not anonymous, right? So it should be using the UserRateLimit, and you could simply adjust that to 100 per second.
You will need to do something alike also with an AppAPIRateLimit anyway.

2024-03-12 10:57 UTC, bigcat88 commented
> Well AppAPI is not anonymous, right

Summarise bot is anonymous, it is not triggered by user, it is triggered by background job once a day, so we can't not know what "userId" to use in requests.

2024-03-12 11:09 UTC, bigcat88 commented
My proposal: we have such a concept in ExApp as a “system application” - it is indicated by a separate flag.
These applications are able to impersonate the user and they do not interact directly with users, and Summarize Chat Bot is the first system application, afaik.

We can make sure that this flag is added to the session and add a check for this flag, and remove the rate limit only for such system applications.

Will this be ok?

_Ordinary ExApps really don’t need a separate RateLimit, as they always have a UserId._

2024-03-14 08:19 UTC, nickvergessen commented
I guess so, but we are running out of time (behind API and feature freeze)

2024-03-15 16:05 UTC, nc-fkl commented
> I guess so, but we are running out of time (behind API and feature freeze)

As @bigcat88 mentioned, we are now checking in the session for ```app_api_system``` - it shouldn't break anything. Are you fine with that @nickvergessen ?

2024-03-15 16:32 UTC, bigcat88 commented
> I guess so, but we are running out of time (behind API and feature freeze)

From my humble point of view, this is not a new feature, but rather a bug fix that we missed when implementing AppAPI authentication.
Bypassing two-factor authentication and CORS was treated like a bugfix..

2024-03-18 17:09 UTC, nickvergessen approved these changes

2024-03-18 20:04 UTC, bigcat88 commented
**cypress** errors look unrelated

2024-03-19 08:32 UTC, merged

2024-03-19 08:57 UTC, bigcat88 commented
/backport to stable28