Add listener and interfaces to allow versions migration accros storages
nextcloud/server pull request #44187
Opened 2024-03-14 09:18 UTC by artonge

2024-03-21 15:43 UTC, artonge commented on apps/files_versions/lib/Listener/FileEventsListener.php
> +		// If different backends, do nothing.
True. Wondering if we should also copy the versions when copying across storage. But that can be a follow-up.

2024-03-21 15:53 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +/** @template-implements IEventListener<BeforeNodeRenamedEvent> */
True, I'll see if I can manage the error I had initially.

2024-03-21 15:54 UTC, artonge commented on apps/files_versions/lib/Versions/LegacyVersionsBackend.php
> +					throw new Exception('Fail to open version file.');
True

2024-03-21 15:57 UTC, artonge commented on apps/files_versions/lib/Versions/LegacyVersionsBackend.php
> +				$userView->getFileInfo($newVersionPath);
Copied too

2024-03-21 15:58 UTC, artonge commented on apps/files_versions/lib/Versions/LegacyVersionsBackend.php
> +		$userView = new View('/' . $user->getUID());
First make it work, then refactor :see_no_evil:

2024-03-21 16:00 UTC, artonge commented on apps/files_versions/lib/Versions/LegacyVersionsBackend.php
> +			if ($version->getTimestamp() !== $source->getMTime()) {
That would be an update to `IVersion`, which is implemented by other backend, so I would say yes, and also not that much better than the current check.

2024-03-21 16:00 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if (!($source instanceof File)) {
... I'll investigate

2024-03-25 11:43 UTC, artonge commented on cypress/e2e/files_versions/version_cross_storage_move.cy.ts
> +	it('Also moves versions when bob moves the file out of a received share', () => {
Refactored to be more expicit

2024-03-25 11:43 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +/** @template-implements IEventListener<BeforeNodeRenamedEvent> */
Pushed

2024-03-25 11:44 UTC, artonge commented on apps/files_versions/lib/Listener/FileEventsListener.php
> +		// If different backends, do nothing.
Implemented handling for cross storage copy.

2024-03-25 13:02 UTC, come-nc commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if ($event instanceof NodeRenamedEvent || $event instanceof NodeCopiedEvent) {
Why is that needed, does NodeRenamedEvent not contain the source node?

2024-03-25 15:16 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if ($event instanceof NodeRenamedEvent || $event instanceof NodeCopiedEvent) {
It contains a source node, but it is a `NonExistingFile`, which means no directly listing

2024-03-25 15:16 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if (!($source instanceof File)) {
Refactored to handle directory move and copy. The code now also moves and copies children

2024-03-25 15:59 UTC, come-nc commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if ($event instanceof NodeRenamedEvent || $event instanceof NodeCopiedEvent) {
But using the source file from the BeforeNodeRenamedEvent at that point works? I’d expect it to fail also to list children as the files were renamed already. It is for folder moving that you need directory listing on source?
Can’t you list on the target?

2024-03-26 09:28 UTC, come-nc approved these changes

2024-03-26 12:49 UTC, icewind1991 requested changes, later dismissed

2024-03-26 12:49 UTC, icewind1991 commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if ($event instanceof BeforeNodeRenamedEvent) {
You're listening for `BeforeNodeCopiedEvent` but not doing anything with it

2024-03-26 12:49 UTC, icewind1991 commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +					$sourceChild = $source->get($targetChild->getName());
is there any reason for not using the same method as used for renames.

The "rename logic" gets the nodes from a `getDirectoryListing` per folder while this has to do a `get` for every child. So the "rename logic" should be significantly more efficient.

2024-03-26 12:49 UTC, icewind1991 commented on apps/files_versions/lib/Versions/IVersionsImporterBackend.php
> +	 * @param Node $target - The target is not yet created.
This is triggered by the "after" events from what I can tell, so the target would already have been created.

(and source might not exist anymore)

2024-03-26 12:59 UTC, emoral435 approved these changes
small nitpicks, but overall good PR :)

2024-03-26 12:59 UTC, emoral435 commented on apps/files_versions/lib/Listener/FileEventsListener.php
> +		$targetBackend = $this->versionManager->getBackendForStorage($target->getStorage());
since this is repeated a decent amount and can have further use, is it possible to wrap this into a helper function within version manager? Make sense semantically, since the version manager seems like it would be able to manage two versions backends to check if they are compatible :) If not though, this is fine

2024-03-26 13:05 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +		if ($event instanceof BeforeNodeRenamedEvent) {
True, removed.

2024-03-26 13:07 UTC, artonge commented on apps/files_versions/lib/Listener/VersionStorageMoveListener.php
> +					$sourceChild = $source->get($targetChild->getName());
I think it failed in some way, let me finish testing on the groupfolder side, and I'll try it again.

2024-03-26 15:42 UTC, artonge commented on apps/files_versions/lib/Listener/FileEventsListener.php
> +		$targetBackend = $this->versionManager->getBackendForStorage($target->getStorage());
Thinking about it more, it won't reduce the number of line that much, as we would only replace the condition.
So I'll pass :)

2024-03-26 17:51 UTC, merged