Added Direct Link to Codespace
nextcloud/server pull request #44246
Opened 2024-03-16 03:18 UTC by RajeevDash007

* Resolves: #43979

## Summary
added the following link to directly spin up a new instance for better assistance to developer:
https://github.com/codespaces/new?hide_repo_select=true&ref=master&repo=60243197&skip_quickstart=true

2024-03-16 03:22 UTC, RajeevDash007 commented
@joshtrichards Please Review this PR

2024-03-16 03:25 UTC, RajeevDash007 commented
@RayBB please review this PR

2024-03-16 08:06 UTC, RajeevDash007 commented
@Antreesy please review this

2024-03-16 08:13 UTC, Antreesy commented
I'm lacking knowledge for that. Please align with issue opener first

2024-03-17 11:01 UTC, RayBB commented
The link you added is good. Adding a note that it takes 5+ minutes (maybe someone should time it)? Would also be valuable.

And you probably should remove those changes to that htaccess file.

2024-03-17 12:17 UTC, skjnldsv requested changes

2024-03-17 12:17 UTC, skjnldsv commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Please drop this change

2024-03-17 12:35 UTC, RajeevDash007 commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Changes done

2024-03-17 12:37 UTC, RajeevDash007 commented
> The link you added is good. Adding a note that it takes 5+ minutes (maybe someone should time it)? Would also be valuable.
> 
> And you probably should remove those changes to that htaccess file.

Chages Done 👍

2024-03-17 12:46 UTC, skjnldsv commented
> > The link you added is good. Adding a note that it takes 5+ minutes (maybe someone should time it)? Would also be valuable.
> > And you probably should remove those changes to that htaccess file.
> 
> Changes Done 👍

Please clean the commits history then :)
- Use [conventionalcommits](https://www.conventionalcommits.org/) message syntax
- Only have one commit that describe the change

2024-03-17 12:53 UTC, RajeevDash007 commented
Okay sure

2024-03-17 16:10 UTC, closed without merging