feat(ObjectStore): Make the S3 `concurrency` option configurable
nextcloud/server pull request #44252
Opened 2024-03-16 20:26 UTC by susnux

* Closes: https://github.com/nextcloud/server/pull/24330

## Summary

Based on this: https://github.com/nextcloud/server/pull/24330#issuecomment-1198366285

So this makes the concurrency option configurable which might help in some cases, but still defaults to 5 like the S3 SDK is doing.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-03-17 01:11 UTC, susnux commented
No idea whats up with Cypress, but that is unrelated...

2024-03-18 09:40 UTC, Altahrim approved these changes

2024-03-21 10:54 UTC, come-nc requested changes

2024-03-21 15:25 UTC, susnux commented on lib/private/Files/ObjectStore/S3ConfigTrait.php
> +<?php
done :heavy_check_mark:

2024-03-21 17:04 UTC, come-nc approved these changes

2024-03-21 18:01 UTC, merged

2024-03-25 08:20 UTC, come-nc commented
@susnux https://github.com/nextcloud/server/actions/runs/8413780258/job/23036516249 Sorry I missed that, you cannot type sizes as `int`, it breaks on 32bits, you should use `int|float`.