Add user verification to webauthn challenges
nextcloud/server pull request #44442
Opened 2024-03-24 11:26 UTC by p1gp1g

Require user verification if all tokens are registered with UV flag, else discourage it

* Resolves: #41599
* Previously work on #34389 (by @ChristophWurst)

## Summary

## TODO
- [x] Recommend UV (user verification with a PIN) during device registration
- [x] Require UV during authentication if all tokens are registered with UV
- [x] Discourage UV during authentication if any token is registered without UV \*
- [x] Previously registered token are considered without UV to avoid locking out a user

\* Currently, this is always discouraged

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-09 13:38 UTC, p1gp1g commented
Is it possible to add the security label to this PR (like #34389 had) ?

@blizz: I see you've changed the milestone, I wonder if it's possible to reconsider. I know you have several requests in the queue and need to prioritize things. But currently using a hardware token for passwordless authentication weakens authentication security in a way: anyone with physical access to that token can get an authenticated session.

2024-05-01 01:54 UTC, blizz commented
@blizzz three z's

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 30 Apr 2024 at 7:48 pm, ***@***.***> wrote:   


Hello there,
Thank you so much for taking the time and effort to create a pull request to our Nextcloud project.

We hope that the review process is going smooth and is helpful for you. We want to ensure your pull request is reviewed to your satisfaction. If you have a moment, our community management team would very much appreciate your feedback on your experience with this PR review process.

Your feedback is valuable to us as we continuously strive to improve our community developer experience. Please take a moment to complete our short survey by clicking on the following link: https://cloud.nextcloud.com/apps/forms/s/i9Ago4EQRZ7TWxjfmeEpPkf6

Thank you for contributing to Nextcloud and we hope to hear from you soon!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-01 08:23 UTC, st3iny requested changes
Thank you for the pull request :smiley: 

I rebased, fixed conflicts, tested locally with 2 keys and made some necessary changes to the code.

## My Changes

1. Made `user_verification` column nullable to make it compatible with all databases.
2. Bumped `@since 29.0.0` to `@since 30.0.0` etc.
3. Made some minor changes to avoid checking in already deprecated code.

## Tests

It works good so far. I tested it with a key protected by a PIN (user verification) and one that has no pin. The PIN prompt is only shown when just the protected key is configured.

## Bugs

However, there is one bug/caveat:
1. Set up one key A with a PIN and one key B without.
2. Observe the `oc_webauthn` table and see that `user_verification` is correctly set to 1 and 0 (A, B).
3. Log out and log in using a device.
4. Use the protected key (-> no PIN is prompted as expected).
5. Observe the `oc_webauthn` table and see that `user_verification` was overwritten to 0 and 0 (A, B).

The credential is saved and overwritten each time a log in is performed which causes the user verification to be reset. I stepped through the code and it seems that the Webauthn library calls our `CredentialRepository::saveCredentialSource()` method on each login. Note that this only happens when at least one key without a PIN is configured.

I think we should handle this case a bit better by either not overwriting during logins or finding another solution.

2024-05-02 07:27 UTC, p1gp1g commented
Thanks for your review

One solution would be to change the authentication challenge from DISCOURAGED to PREFERRED when one of the key doesn't have UV.

It has the benefits to:
- Allow to update the UV of a key without having to re-register it
- Protect against someone who get a key which can use UV to directly use it in a browser: UV will be asked.

Downside:
- It can give a false sense of security. Users can think that the UV is required even if they have a non-secure key registered, while it is possible to bypass this UV for all keys.

I think the downside is dangerous. Not overwriting the key is probably a better solution

2024-05-02 15:32 UTC, st3iny commented
> I think the downside is dangerous. Not overwriting the key is probably a better solution

This is the route I chose for now. Now, the user verification is never downgraded from `true` to `false`. It works without having the potential downside you mentioned.

Existing users won't be affected. Only new devices will be affected and if a user wants to benefit from UV they have to remove all existing keys and re-register them with UV.

2024-05-02 15:33 UTC, st3iny approved these changes
Tested and works. Remaining feedback has been addressed.

2024-07-18 07:26 UTC, p1gp1g commented
Hello, is anything blocking this PR ?

2024-07-18 08:40 UTC, ChristophWurst approved these changes
Thanks a lot

This drowned in my notifications, sorry

Left some minor feedback

2024-07-18 08:40 UTC, ChristophWurst commented on core/Migrations/Version29000Date20240324113502.php
> + */
See https://github.com/nextcloud/server/blob/master/contribute/HowToApplyALicense.md#apply-a-license-to-a-new-file please. We recently switched to SPDX headers

2024-07-18 08:40 UTC, ChristophWurst commented on lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialEntity.php
> + * @since 30.0.0
I think this since attribute might be misinterpreted by tools and make it look like the whole class is new in 30

2024-07-18 09:19 UTC, p1gp1g commented on lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialEntity.php
> + * @since 30.0.0
Some other files do it, but they have a comment after the _since_
https://github.com/nextcloud/server/blob/master/lib/public/IAppConfig.php
https://github.com/nextcloud/server/blob/master/lib/public/SystemTag/SystemTagsEntityEvent.php
https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Utility/ITimeFactory.php

2024-07-18 11:52 UTC, nickvergessen commented on lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialEntity.php
> + * @since 30.0.0
Maybe you can find out the original since and then add that and a second `@since` with a comment of your changes?

2024-07-18 12:04 UTC, p1gp1g commented on core/Migrations/Version29000Date20240324113502.php
> + */
Do you mind suggesting a diff ?

2024-07-18 12:06 UTC, p1gp1g commented on lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialEntity.php
> + * @since 30.0.0
So, just adding a comment ?
```suggestion
 * @since 30.0.0 Add userVerification attribute
```

2024-07-18 12:57 UTC, ChristophWurst commented on core/Migrations/Version29000Date20240324113502.php
> + */
```
/**
 * SPDX-FileCopyrightText: 2024 [your name] [<your email address>]
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
```

2024-07-18 13:24 UTC, p1gp1g commented on lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialEntity.php
> + * @since 30.0.0
Done

2024-07-18 13:25 UTC, ChristophWurst approved these changes

2024-08-14 10:34 UTC, p1gp1g commented
So this PR is tagged with "to release" and won't be release ? This is sad because this is a security fix

Fortunately there is a workaround for admin who cares about their user security: https://github.com/nextcloud/server/issues/41599#issuecomment-2056581293 and users should be aware to not use passkeys until this is merged or there is the workaround

2024-08-15 08:56 UTC, nickvergessen commented
> So this PR is tagged with "to release" and won't be release ?

Well I guess it just slipped, as CI didnt work for the fork and therefore the PR never turned green.

I will send a local PR so CI passes and then it should go in

2024-08-15 09:04 UTC, nickvergessen commented
Running in https://github.com/nextcloud/server/pull/47253

2024-08-15 09:22 UTC, p1gp1g commented
Thanks a lot for your feedback, I hope the CI will be OK

2024-08-15 09:53 UTC, nickvergessen commented
- Merged for 31 in https://github.com/nextcloud/server/pull/47253
- Backported for 30 in https://github.com/nextcloud/server/pull/47255

2024-08-15 09:53 UTC, closed without merging

2024-08-15 09:54 UTC, nickvergessen commented
THanks for the contribution @p1gp1g and sorry for the miss

2024-08-15 10:18 UTC, p1gp1g commented
No problem for the miss, and thank you !

2024-08-16 06:37 UTC, skjnldsv commented
@p1gp1g @be-ing, sorry for the late reply!
We did some cleanup, on old opened PR, but haven't replied to all of them yet :see_no_evil: 

Thanks @nickvergessen for the help, glad to see this moving forward!!
Have a nice Friday then a nice weekend everyone! :sun_with_face: