WIP : Respect empty `expiryDate` value in server
nextcloud/server pull request #44485
Opened 2024-03-26 13:06 UTC by Fenn-CS

Resolves : https://github.com/nextcloud/server/issues/44219

2024-04-30 10:14 UTC, Fenn-CS commented
Related changes : https://github.com/nextcloud/server/pull/44912

2024-04-30 11:22 UTC, Fenn-CS commented
/backport to stable29

2024-04-30 11:22 UTC, Fenn-CS commented
/backport to stable28

2024-04-30 11:22 UTC, Fenn-CS commented
/backport to stable27

2024-04-30 11:45 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> -		// If expiredate is empty set a default one if there is a default
but you are removing the default functionality?

2024-04-30 12:07 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
> -		// If expiredate is empty set a default one if there is a default
Yes :)... Since the users now have the opportunity to modify this settings before a share is created. `i.e` the user can see on the share creation menu, that an expiry date is required and can either allow the default or remove if not enforced.

Leaving this default functionality means, we always force shares to have expiry dates even when that's not the users intention.

2024-04-30 12:43 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> -		// If expiredate is empty set a default one if there is a default
The problem is that currently existing clients and app might rely on the default and not populate it via the UI or send it with each request.
So this is a breaking change that is impossible to discover and will lead to a lot of shares not expiring although they should.

2024-04-30 13:37 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
> -		// If expiredate is empty set a default one if there is a default
I see. This breaking change is inevitable if we would solve https://github.com/nextcloud/server/issues/44219 though.

I am not sure but perhaps I could introduce checks for clients/app calls.

Another though is that `Manager` class is only part of the private API and maybe all we need to do is make sure the apps we maintain that uses the non public share interface are updated?

2024-04-30 14:02 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> -		// If expiredate is empty set a default one if there is a default
> Another though is that Manager class is only part of the private API and maybe all we need to do is make sure the apps we maintain that uses the non public share interface are updated?

I meant apps like Android, iOS and our Desktop Client:
- https://github.com/nextcloud/server/blob/490f545006024ad982c801b5c986ff8d03826821/apps/files_sharing/lib/Controller/ShareAPIController.php#L574
- https://github.com/nextcloud/server/blob/490f545006024ad982c801b5c986ff8d03826821/apps/files_sharing/lib/Controller/ShareAPIController.php#L648-L656

That being said, the update also supports it, but basically you need to set it to `''` (empty string) not null when updating a share and removing a expiration date.

Seems to work when updating, just not when creating, as the check is always executed then.
So instead of tampering with `validateExpirationDateInternal` like this, I would try to get the information into the share object that no expirationDate was sent and in https://github.com/nextcloud/server/blob/ec5133b739eabc76271789504b4dbb91a534f552/lib/private/Share20/Manager.php#L423 instead of only checking `$expirationDate === null` you also check whether it was sent with the empty string, and only set the default date when it was not sent as empty string.

2024-04-30 17:03 UTC, nfebe reviewed
Backtracked on the initial radical and breaking approach where, we allow defaults to be set entire by the client.

Propose new approach: 

- If client sends empty string, then do not set any defaults
- Set defaults it no `expireDate` is sent
- Set default if `expireDate` sent is null

2024-04-30 17:17 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +				$share->setExpirationDate('');
Since, `null` is the basis for setting default expiration date in the share manager for new shares, we just can't set this to null here.

2024-04-30 17:18 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +				$share->setExpirationDate('');
```suggestion
				$share->setExpirationDate(null);
```

Since, `null` is the basis for setting default expiration date in the share manager for new shares, we just can't set this to null here.


But can be done much later in `validateExpirationDateInternal` and `validateExpirationDateLink`

2024-04-30 22:16 UTC, provokateurin commented on lib/public/Share/IShare.php
> +	 * @param \DateTime|string|null $expireDate
```suggestion
	 * @param \DateTime|''|null $expireDate
```
To avoid any other string than the empty string. I'm questioning a bit if this couldn't be solved differently because two "null" values are not great

2024-05-01 04:13 UTC, nickvergessen requested changes, later dismissed

2024-05-01 04:13 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> +		// Hence no validation required
This is not correct. If the enforcement is enabled you still have to.

2024-05-01 04:13 UTC, nickvergessen commented on lib/private/Share20/Manager.php
> +		// Hence no validation required
Same here

2024-05-01 04:13 UTC, nickvergessen commented on lib/public/Share/IShare.php
> +	 * @param \DateTime|string|null $expireDate
Which is why i would have added another prop for this. Also helps to improve the enforcement handling above

2024-05-02 08:04 UTC, come-nc reviewed
I have to say I do not understand why the share object has to carry the information of whether a default date was used, it should simply contain the date. So this new method in IShare is not logical to me.

Code around this sounds quite convoluted.

2024-05-02 08:04 UTC, come-nc commented on lib/private/Share20/Share.php
> -	/** @var string */
You’re gonna get trouble with all this strong typing. I tried it in the psalm update PR and typing in this class is inconsistent between props and methods. Main problem is the class can be used to represent an incomplete share while some code path expect it to be complete.

I’d advice not touching the typing or do it in a separate PR which fixes the problems.

2024-05-02 08:34 UTC, come-nc commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSNotFoundException($this->l->t('Invalid date, date format must be YYYY-MM-DD'));
`	 * @throws OCSNotFoundException Creating the share failed
`
Apparently not :thinking: 
This API is really weird.

2024-05-02 08:42 UTC, come-nc commented
> I have to say I do not understand why the share object has to carry the information of whether a default date was used, it should simply contain the date. So this new method in IShare is not logical to me.
> 
> Code around this sounds quite convoluted.

Ok I’m starting to understand, the share object is used both to convey the parameter for creation and the final created object, this is quite bad.
So I do not see a better way than what you did for storing the info without a bigger refactor.
I do not understand the name `setOverwriteFalsyExpirationDate` though.
Why not `setNoExpirationDate(bool)` ?

2024-05-02 09:12 UTC, nickvergessen commented on lib/public/Share/IShare.php
> +	public function setOverwriteFalsyExpirationDate(bool $overwriteFalsyExpirationDate);
```suggestion
	public function setNoExpirationDate(bool $noExpirationDate);
```
etc

2024-05-02 15:45 UTC, Fenn-CS commented
> I do not understand the name setOverwriteFalsyExpirationDate though.
> Why not setNoExpirationDate(bool) ?

The method name `setOverwriteFalsyExpirationDate` was chosen for its explicitness in indicating that the method controls whether to overwrite falsy values, such as `null` or an empty string (`''`), in the `expireDate` field. 

Because, that is exactly what the method and its corresponding property is currently used for in the code, we use it to decide if we want to **overwrite** the value of `$expireDate` when it has *falsy* values (`null`, `''`, `0'`, etc) ...

However, following your suggestion, I have changed the name to `setNoExpirationDate(bool)` as it might be easier especially for non-native English speakers to grab.

2024-05-02 15:46 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
>  	protected function validateExpirationDateLink(IShare $share) {
Yes the method is in use.

2024-05-02 15:47 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
> +			$share->setExpirationDate(null);
Yes because `''` (empty string) value would lead to `DBAL` exceptions when trying to convert a string into value that should be stored on a `nullable` `datetime` field.

2024-05-02 16:15 UTC, Fenn-CS commented on lib/private/Share20/Share.php
> -	/** @var string */
Moved to : https://github.com/nextcloud/server/pull/45156

2024-05-02 16:17 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
>  			$expirationDate->setTime(0, 0, 0);
@come-nc  not clear here please...

2024-05-02 16:28 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSNotFoundException($this->l->t('Invalid date, date format must be YYYY-MM-DD'));
To avoid more back and forth for something unrelated moved to : https://github.com/nextcloud/server/pull/45157

2024-05-02 16:32 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
>  			$expirationDate->setTime(0, 0, 0);
Figured.

2024-05-03 08:12 UTC, nickvergessen commented
Would really be good to add a new test into https://github.com/nextcloud/server/tree/058b69eef02be9bfa77e9b6a1d12d15f29ac6b0c/build/integration/sharing_features which proves the thing you fixed, so it does not get reverted at some point and no test fails :P

2024-05-06 08:12 UTC, come-nc commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +	 * @param ?string $expireDate The expiry date of the share in the user's timezone (UTC) at 00:00.
```suggestion
	 * @param ?string $expireDate The expiry date of the share in the user's timezone at 00:00.
```
The user’s timezone is not always UTC

2024-05-06 08:12 UTC, come-nc commented on lib/private/Share20/Manager.php
> +			$share->setExpirationDate(null);
But expirationDate is null or DateTime it cannot be `''` in the share object.

2024-05-06 08:12 UTC, come-nc commented
I agree that we need tests for this.

2024-05-21 16:57 UTC, blizzz commented
Is it possible to get some momentum into this PR? With regard to Red CI and the suggested test?

2024-05-22 14:07 UTC, Fenn-CS reviewed
WIP commit present.

2024-05-22 14:07 UTC, Fenn-CS commented on build/integration/sharing_features/sharing-v1.feature
> +  Scenario: Creating a new share with expiration date removed, when default expiration is set
Would fix up commit to main changes once tests are approved

2024-05-23 12:17 UTC, Fenn-CS commented on lib/private/Share20/Manager.php
> +		if(!(empty($expirationDate) && $share->getNoExpirationDate() && !$isEnforced)) {
Does not make a difference, would update.

```suggestion
		if(!($share->getNoExpirationDate() && !$isEnforced)) {
```

2024-05-23 12:18 UTC, Fenn-CS reviewed
If `noExpirationDate` is set to true and no enforcement no validation is needed irresepective of the value of `expirationDate`

2024-05-23 12:33 UTC, Fenn-CS commented on build/integration/sharing_features/sharing-v1.feature
> +      | expiration ||
@artonge In case you are wondering this is what the test suite is complaining about.

Context:

- We updated the backend to not set expiry date when an empty value is sent
- So when the expiry is created it returns expiration that should be nullable or an empty space.
- So next step is to try `| null |` currently I am passing `||` and not sure how Gherkin would parse that.

2024-05-23 12:44 UTC, artonge approved these changes

2024-05-23 13:01 UTC, come-nc commented on lib/public/Share/IShare.php
> +	 * @since 27.0.0
```suggestion
	 * @since 29.0.0
```
And then adapted in backports

2024-05-23 13:01 UTC, come-nc commented on lib/public/Share/IShare.php
> +	 * @since 27.0.0
(same for  `getNoExpirationDate`)

2024-05-23 13:14 UTC, come-nc approved these changes

2024-05-23 14:40 UTC, merged

2024-05-28 17:17 UTC, ShGKme commented
This breaks uploading in Talk which expects `$expireDate` to be `string`

2024-05-28 20:16 UTC, blizzz commented
> This breaks uploading in Talk which expects `$expireDate` to be `string`

Also on 27?

2024-05-29 07:30 UTC, Antreesy commented
> Also on 27?

Confirm for stable27
![image](https://github.com/nextcloud/server/assets/93392545/54dbc357-e214-41f4-8777-731c8fa8e6d2)

2024-07-18 10:17 UTC, nickvergessen commented on lib/public/Share/IShare.php
> +	public function getNoExpirationDate();
@Fenn-CS Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(all changes in lib/public/)

2024-07-21 13:27 UTC, Fenn-CS commented on lib/public/Share/IShare.php
> +	public function getNoExpirationDate();
https://github.com/nextcloud/documentation/pull/12051