fix #42647 Unnecessary 2FA UI message updated
nextcloud/server pull request #44594
Opened 2024-03-31 14:40 UTC by jadjoud

* Resolves: #42647 

## Summary
Added a conditional statement for the message rendering

![image](https://github.com/nextcloud/server/assets/118366366/b2953ca0-0992-44f5-9d5f-eeadb935e752)

![image](https://github.com/nextcloud/server/assets/118366366/085bda48-91ce-4c47-ba76-d4869bed2acd)

@kesselb this is the fixed PR

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-02 13:40 UTC, kesselb commented
Thank you, always great to see new contributors :+1:

Here is a brief explanation of how to set up a local dev environment https://github.com/nextcloud/server?tab=readme-ov-file#join-the-team-

A good start to wrap a v-if template block. To make that actually work, you also need to add the actual variable `isTwoFactorEnabled` to the data function also gather the information "is 2fa enabled for the given user" from the backend. 

The patch below should provide the necessary data from the backend and use it in the vue component. 

```
Index: apps/files/lib/Controller/ViewController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/files/lib/Controller/ViewController.php b/apps/files/lib/Controller/ViewController.php
--- a/apps/files/lib/Controller/ViewController.php	(revision 28ee87b4c4cb3f82af1fb2caaa0218b635750e90)
+++ b/apps/files/lib/Controller/ViewController.php	(date 1712064072302)
@@ -35,6 +35,7 @@
  */
 namespace OCA\Files\Controller;
 
+use OC\Authentication\TwoFactorAuth\Registry;
 use OCA\Files\Activity\Helper;
 use OCA\Files\AppInfo\Application;
 use OCA\Files\Event\LoadAdditionalScriptsEvent;
@@ -98,7 +99,8 @@
 		ITemplateManager $templateManager,
 		IManager $shareManager,
 		UserConfig $userConfig,
-		ViewConfig $viewConfig
+		ViewConfig $viewConfig,
+		private Registry $twoFactorRegistry,
 	) {
 		parent::__construct($appName, $request);
 		$this->urlGenerator = $urlGenerator;
@@ -203,7 +205,8 @@
 		\OCP\Util::addStyle('files', 'merged');
 		\OCP\Util::addScript('files', 'main');
 
-		$userId = $this->userSession->getUser()->getUID();
+		$user = $this->userSession->getUser();
+		$userId = $user->getUID();
 
 		// Get all the user favorites to create a submenu
 		try {
@@ -270,6 +273,15 @@
 		$this->initialState->provideInitialState('templates_path', $this->templateManager->hasTemplateDirectory() ? $this->templateManager->getTemplatePath() : false);
 		$this->initialState->provideInitialState('templates', $this->templateManager->listCreators());
 
+		$isTwoFactorEnabled = false;
+		foreach ($this->twoFactorRegistry->getProviderStates($user) as $providerId => $providerState) {
+			if ($providerId !== 'backup_codes' && $providerState === true) {
+				$isTwoFactorEnabled = true;
+			}
+		}
+
+		$this->initialState->provideInitialState('isTwoFactorEnabled', $isTwoFactorEnabled);
+
 		$response = new TemplateResponse(
 			Application::APP_ID,
 			'index',
Index: apps/files/src/views/Settings.vue
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/files/src/views/Settings.vue b/apps/files/src/views/Settings.vue
--- a/apps/files/src/views/Settings.vue	(revision 28ee87b4c4cb3f82af1fb2caaa0218b635750e90)
+++ b/apps/files/src/views/Settings.vue	(date 1712064510627)
@@ -152,6 +152,7 @@
 			appPasswordUrl: generateUrl('/settings/user/security#generate-app-token-section'),
 			webdavUrlCopied: false,
 			enableGridView: (loadState('core', 'config', [])['enable_non-accessible_features'] ?? true),
+			isTwoFactorEnabled: (loadState('files', 'isTwoFactorEnabled', false))
 		}
 	},
 

```

2024-04-02 13:42 UTC, kesselb commented
Removing myself as reviewer because I'm not familiar enough with 2fa and the files settings component.

2024-04-02 23:16 UTC, jadjoud commented
@kesselb 
Thank you so much for your help!

I will try to make the necessary changes ASAP

2024-04-03 08:24 UTC, pboguslawski commented
When message is rendered only with 2FA enabled, should not contain `If you have enabled 2FA` any more probably.

Removing myself as reviewer because we're not using 2FA with nc so cannot test it.

2025-07-16 15:56 UTC, skjnldsv requested changes

2025-07-16 15:56 UTC, skjnldsv commented on apps/files/src/views/Settings.vue
> +			<template v-if="isTwoFactorEnabled">
This variable doesn't exist?
You need to check of we have a capability for it or else inject the variables from the Controller yourself :)

2025-07-24 21:52 UTC, closed without merging

2025-07-24 21:53 UTC, kesselb commented
Thanks again @JED-B for taking the initiative :+1: 

We've integrated it through https://github.com/nextcloud/server/pull/54020.