Fix sharing a password protected link
nextcloud/server pull request #4462
Opened 2017-04-24 09:48 UTC by danxuliu

There are two issues at play here. First, when the password is updated in a shared link the password is double hashed (the plain text password is hashed and, then, the hash is hashed again and set as the password). Due to this the authentication always fails, as the hash of the plain text password does not match the hash of the hash of the plain text password.

And second, although it does not prevent setting the password, if the password is set without problems the working icon does not dissappear, which can make the user think that the password is still being set (note that it is not the same as in #4260, as that seems to refer to the working icon for sharing the link itself, not for setting a password).

Both issues are fixed by this pull request.

(Some files of this pull request conflict with those in other pull request that I have opened; I will rebase this pull request or the other one as needed if they got merged)

2017-04-24 11:07 UTC, rullzer requested changes
Nice catch! I'll give it a test run

2017-04-24 11:07 UTC, rullzer commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Don't commit .htaccess ;)

2017-04-24 11:21 UTC, danxuliu commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Ugh, sorry, I got bitten by `git add -u`. How embarrasing... Fixed now :)

2017-04-24 11:22 UTC, ChristophWurst commented on core/js/sharedialoglinkshareview.js
> +				success: function(model) {
in terms of readability, I'd prefer to move this to a `complete` callback, then we don't have any duplication with the error callback. AFAIK the options object passed here is will be passed to jQuery - which has that callback.

2017-04-24 11:22 UTC, ChristophWurst commented on lib/private/Share20/Manager.php
> +	private function updateSharePasswordIfNeeded($share, $originalShare) {
would be cool to use php's type hints in the method signature

2017-04-24 11:22 UTC, ChristophWurst commented on tests/acceptance/features/core/Actor.php
> +	public function __construct(\Behat\Mink\Session $session, $baseUrl, &$sharedNotebook) {
why do we need a reference here?

2017-04-24 11:51 UTC, danxuliu commented on lib/private/Share20/Manager.php
> +	private function updateSharePasswordIfNeeded($share, $originalShare) {
Done!

2017-04-24 12:06 UTC, danxuliu commented on core/js/sharedialoglinkshareview.js
> +				success: function(model) {
No, the options object is passed to [`updateShare`](https://github.com/nextcloud/server/blob/58f959864abbce05af586a162fde2fc10b039478/core/js/shareitemmodel.js#L203), but it does not pass it to jQuery; instead, if the `jQuery.ajax` call succeeds, it refreshes the model and then calls the `success` callback given in the options, if any. In the same way, if the `jQuery.ajax` call fails, it calls the `error` callback given in the options, if any.

I can extend `updateShare` to always call a `complete` callback if given, if you want (I say `complete` (the old jQuery name) instead of `always` (the current one) for consistency with the names currently used for the option callbacks (`success`and `error`)).

2017-04-24 12:08 UTC, danxuliu commented on tests/acceptance/features/core/Actor.php
> +	public function __construct(\Behat\Mink\Session $session, $baseUrl, &$sharedNotebook) {
Please correct me if I am wrong, but as far as I know arrays are passed by value in PHP. The array has to be shared by every Actor object, so I used a reference to a single array.

2017-04-24 13:07 UTC, ChristophWurst commented on core/js/sharedialoglinkshareview.js
> +				success: function(model) {
Okay, sorry, wrong assumption. Then I'm fine with it either way. Adding `always` would be the ideal solution, but you can also leave it as it is now.

2017-04-24 13:11 UTC, ChristophWurst commented on tests/acceptance/features/core/Actor.php
> +	public function __construct(\Behat\Mink\Session $session, $baseUrl, &$sharedNotebook) {
Yeah, you're right, they are indeed passed by value
```
php > $x = [1, 2];
php > $y = $x;
php > $x[] = 3;
php > print_r($y);
Array
(
    [0] => 1
    [1] => 2
)
```

2017-04-24 17:44 UTC, rullzer approved these changes

2017-04-24 17:44 UTC, rullzer commented
Seems to do the trick!
Again awesome stuff @danxuliu

2017-04-24 20:33 UTC, danxuliu commented
@ChristophWurst 
>  Adding always would be the ideal solution, but you can also leave it as it is now.

I went for the ideal solution ;) I called the callback `complete`, although if you prefer I can rename it to `always`.

@rullzer 
>  Again awesome stuff @danxuliu

Thanks again :)

2017-04-25 10:39 UTC, schiessle commented
Great work, I did some manual testing also with share by mail and everything works great! 👍

2017-04-25 10:39 UTC, schiessle approved these changes

2017-04-25 10:44 UTC, schiessle commented
@ChristophWurst anything open from your side? Otherwise I would vote for "merge". 😃

2017-04-25 10:47 UTC, ChristophWurst approved these changes

2017-04-25 10:49 UTC, rullzer commented
Seems the tests failed... I restarted lets see...

2017-04-25 12:12 UTC, rullzer commented
Ok seems OK now. => merge

2017-04-25 12:12 UTC, merged