feat(trashbin): Add deleted by property
nextcloud/server pull request #44643
Opened 2024-04-03 17:58 UTC by Pytal

- Part of https://github.com/nextcloud/server/issues/14917

## Summary

- Store and provide a new `trashbin-deleted-by` DAV property

- Example PROPFIND request data
```xml
<?xml version="1.0"?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:prop>
    <oc:fileid />
    <d:displayname />
    <d:getlastmodified />
    <d:getcontenttype />
    <oc:size />
    <oc:owner-id />
    <oc:share-types />
    <nc:sharees />
    <nc:share-download-limits />
    <nc:trashbin-filename />
    <nc:trashbin-deletion-time />
    <nc:trashbin-original-location />
    <nc:trashbin-title />
    <nc:trashbin-deleted-by />
  </d:prop>
</d:propfind>
```

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-04 08:48 UTC, Altahrim commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
> +			'notnull' => false,
It seems we don't really uses the `null`, we can avoid it: 
```suggestion
			'notnull' => true,
```
Empty string should be enough if value isn't filled.

2024-04-04 09:01 UTC, tcitworld commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
> +			'notnull' => false,
Don't you need to enforce a default value in that case?

2024-04-04 18:41 UTC, Pytal commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
> +			'notnull' => false,
Now using notnull + default empty string

2024-04-04 18:42 UTC, Pytal commented on apps/files_trashbin/lib/Trash/TrashManager.php
> +		return $user;
Yes, good catch! Using `empty` check

2024-04-09 11:10 UTC, icewind1991 requested changes
This would cause a query for every trash item in the trashbin.

2024-04-09 11:11 UTC, icewind1991 commented
How about adding it to `ITrashItem` instead so the value can be retrieved when listing trash items

2024-04-17 22:43 UTC, Pytal commented
Switched the column back to nullable to fix potential migration errors with oracle which converts empty string to null

2024-04-22 14:12 UTC, icewind1991 approved these changes

2024-04-23 07:00 UTC, sorbaugh approved these changes

2024-04-23 07:06 UTC, come-nc reviewed
Did you test that with groupfolders?

2024-04-23 07:06 UTC, come-nc commented on apps/files_trashbin/lib/Trash/LegacyTrashBackend.php
> +			/** @psalm-suppress UndefinedInterfaceMethod */
```suggestion
```
Why is that needed? You added it to the interface, it should find it.

2024-04-23 07:06 UTC, come-nc commented on apps/files_trashbin/lib/Trash/TrashItem.php
> +		$this->deletedBy = $deletedBy;
You need to remove these lines, the point of constructor property promotion is that it’s done automagically.

2024-04-23 07:06 UTC, come-nc commented on apps/files_trashbin/lib/Trashbin.php
>  			if (isset($array[$row['id']])) {
I think this `if` is useless and autovivification can be used. You should be able to simply use the inside of the `if` branch and drop the rest.

2024-04-23 23:24 UTC, Pytal commented on apps/files_trashbin/lib/Trash/LegacyTrashBackend.php
> +			/** @psalm-suppress UndefinedInterfaceMethod */
This is not for the method but the array key access as public FileInfo does not support it but private does https://github.com/nextcloud/server/blob/5b85562784be0c10cb885d2865f66cf6e959f90b/lib/private/Files/FileInfo.php#L124-L137

2024-04-23 23:26 UTC, Pytal commented
> Did you test that with groupfolders?

Seems it breaks groupfolders as it implements a custom trash backend, documented the change here https://github.com/nextcloud/documentation/pull/11757

2024-04-23 23:42 UTC, merged

2024-04-24 05:08 UTC, nickvergessen commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
When adding a migration file you need to bump the version of the app so updates are triggered

2024-04-24 05:11 UTC, nickvergessen commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
Sent in https://github.com/nextcloud/server/pull/45000

2024-04-24 16:13 UTC, Pytal commented on apps/files_trashbin/lib/Migration/Version1020Date20240403003535.php
Oop missed that part, thanks!