Move retry logic to the QueryBuilder
nextcloud/server pull request #44718
Opened 2024-04-08 11:48 UTC by artonge

Signed-off-by: Louis Chemineau <louis@chmn.me>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-08 14:11 UTC, nickvergessen commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @param int $retryLimit - Retry the query up to $retryLimit times in case of a RetryableException. Initially equal to 4.
I don't think we should have retries by default :-X

2024-04-08 14:55 UTC, artonge commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @param int $retryLimit - Retry the query up to $retryLimit times in case of a RetryableException. Initially equal to 4.
Unsure about it either, but note that this is only for `RetryableException`, we don't try forever, and there is a log, so it won't go unnoticed.

Not sure what the argument against would be, that is why I set the default to 4. But I do not have any strong opinion, so I am fine either way.

2024-04-08 16:04 UTC, come-nc approved these changes

2024-04-09 08:20 UTC, juliushaertl commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @param int $retryLimit - Retry the query up to $retryLimit times in case of a RetryableException. Initially equal to 4.
Retries only work if the whole transaction is retried, so I'm also more in favor of making this an opt-in to not cause unexpected behaviour there when developers don't think about this and just call execute.

2024-04-09 08:33 UTC, artonge commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @param int $retryLimit - Retry the query up to $retryLimit times in case of a RetryableException. Initially equal to 4.
> Retries only work if the whole transaction is retried

So it does not really make sense to have that logic here, no? I think I start to understand the value of https://github.com/nextcloud/server/blob/050c6d53b38d6737a49c13d4e6a20a6062160503/lib/public/AppFramework/Db/TTransactional.php#L94 :sweat_smile:

2024-04-09 13:30 UTC, icewind1991 requested changes
I think retrying by default is a bad idea and can lead to unexpected behavior for developers

2024-04-17 13:29 UTC, artonge commented on lib/public/DB/QueryBuilder/IQueryBuilder.php
> +	 * @param int $retryLimit - Retry the query up to $retryLimit times in case of a RetryableException. Initially equal to 4.
Default is now set to 0

2024-04-17 13:34 UTC, closed without merging