chore(files): Switch widget to primary color
nextcloud/server pull request #44806
Opened 2024-04-13 00:42 UTC by Pytal

## Summary

- Switch widget to primary color
![image](https://github.com/nextcloud/server/assets/24800714/c5b9273d-2aac-42bd-9aed-972634c0504c)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-13 00:42 UTC, Pytal commented
/backport to stable29

2024-04-13 07:10 UTC, szaimen approved these changes
LGTM but didnt test

2024-04-15 11:10 UTC, jancborchardt requested changes
Folder icons should indeed be primary color, but text documents not. :) If it’s a .doc/.odt, it has a distinct blue color, not primary (and this seems to be plain text, right?) @Pytal the correct coloring is in https://github.com/nextcloud/server/issues/44340#issue-2195826948

2024-04-15 11:19 UTC, susnux commented on apps/files/src/views/ReferenceFileWidget.vue
> +				<FileIcon v-else :size="88" fill-color="var(--color-primary-element)" />
```suggestion
				<FileIcon v-else :size="88" />
```

2024-04-16 09:49 UTC, jancborchardt approved these changes
Thank you! :)

2024-04-16 10:07 UTC, susnux approved these changes

2024-04-16 10:19 UTC, merged