Enable more psalm rules
nextcloud/server pull request #44818
Opened 2024-04-14 06:18 UTC by provokateurin

## Summary

Enables a few more useful rules:
- MissingThrowsDocblock: Ensures every method has the appropriate `@throws` annotations
- InvalidOperand: Ensures values/variables of different types are not used in an operation without explicit casting (e.g. `'test' . 123`
- UnusedPsalmSuppress: Reports on unused supresses

I only fixed the problems of the last rule because there weren't a lot, but the first two ones I added to the baseline. Those errors will only show up for new or refactored code.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-14 06:45 UTC, nickvergessen requested changes
> MissingThrowsDocblock: Ensures every method has the appropriate @throws annotations

I do not agree with this.
Only expected throws should be documented.
Any method that does do anything with the DB, Redis, Ldap, ... would otherwise document to throw them and every consumer starts to wrap hundreds of catches or has their IDE crying about unhandled exceptions.

2024-04-14 07:20 UTC, st3iny requested changes
I agree with Joas. Explicit error handling like in Go and Rust is nice but it's already to late to enforce that in our codebase.

Only relevant exceptions should be listed to make the caller aware of possible errors. The decision is up to the developer.

2024-04-15 06:57 UTC, come-nc commented on core/Controller/OCMController.php
> +	 * @psalm-suppress UnusedPsalmSuppress
:upside_down_face:

2024-04-15 07:04 UTC, provokateurin commented on core/Controller/OCMController.php
> +	 * @psalm-suppress UnusedPsalmSuppress
Yeah this piece of code is somehow very broken :grimacing:

2024-05-30 15:02 UTC, closed without merging