refactor(sharingDetails): Show correct share target
nextcloud/server pull request #44839
Opened 2024-04-15 21:15 UTC by Fenn-CS

The share details page should show the target email or user/server to which
the user is creating the share.

| Before email | Before federation | After email | After federation |
| ----------------  | ---------------------- | --------------- | --------------------- |
| ![before-email](https://github.com/nextcloud/server/assets/14317775/e28a415e-04d5-4adc-87a4-442defc4f6e4) | ![before-federation](https://github.com/nextcloud/server/assets/14317775/5b2fa26b-7e52-4069-b6a2-e19701b014f9)| ![after-email](https://github.com/nextcloud/server/assets/14317775/e5277677-eafc-462f-8c6f-56d4a17d4e2e) | ![after-federation](https://github.com/nextcloud/server/assets/14317775/17e724c1-3513-4ff8-a3ec-de92c93e3fb1) |

2024-04-15 21:15 UTC, Fenn-CS commented
/backport to stable29

2024-04-15 21:15 UTC, Fenn-CS commented
/backport to stable28

2024-04-15 21:15 UTC, Fenn-CS commented
/backport to stable27

2024-04-16 05:43 UTC, kesselb commented
Please use the right type for your commit message. Refactoring is changing code without changing behavior.

2024-04-16 08:21 UTC, artonge approved these changes

2024-04-16 09:16 UTC, susnux requested changes

2024-04-16 09:16 UTC, susnux commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +				return t('files_sharing', this.share.id ? 'Create share' : 'Update share')
This does not work as you might expect, this only works if you use exact the same strings in another place, as the l10n extraction does only handle plain strings.

```suggestion
				if (this.share.id) {
					// Share already exists
					return t('files_sharing', 'Update share')
				} else {
					return t('files_sharing', 'Create share')
				}
```

2024-04-16 17:18 UTC, Fenn-CS commented
/compile

2024-04-16 18:17 UTC, susnux commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			    return (() => {
why is this a function?

2024-04-17 02:28 UTC, Fenn-CS commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +			    return (() => {
Maintaining lexical structure of the switch case to avoid lint errors.

2024-04-18 10:13 UTC, Fenn-CS commented
/backport to stable29

2024-04-18 10:13 UTC, Fenn-CS commented
/backport to stable28

2024-04-18 10:14 UTC, Fenn-CS commented
/backport to stable27

2024-04-18 13:01 UTC, susnux approved these changes
thank you!

2024-04-18 13:01 UTC, merged

2024-04-18 13:06 UTC, Fenn-CS commented
/backport to stable28

2024-04-18 13:06 UTC, Fenn-CS commented
/backport to stable27