Support multiple scopes in DAV search
nextcloud/server pull request #44858
Opened 2024-04-16 14:13 UTC by artonge

Instead of making the search on the targeted folders, the current approach does it on the user's root folder, with some extra conditions applied on the path.

This allows the following scope in WebDAV `SEARCH` requests:

```xml
<d:from>
	<d:scope>
		<d:href>/files/user1/a</d:href>
		<d:depth>infinity</d:depth>
	</d:scope>
	<d:scope>
		<d:href>/files/user1/b</d:href>
		<d:depth>infinity</d:depth>
	</d:scope>
</d:from>
```

This can be tested with the following PR in Photos: https://github.com/nextcloud/photos/pull/2426
With that PR, the SQL request will look like that:

```sql
SELECT
	file.fileid,
	[...]
FROM
	oc_filecache file
	[...]
WHERE
	[...]
	AND (
		path COLLATE utf8mb4_general_ci LIKE "files/a/%"    -- <-- ADDED CONDITION
		OR path COLLATE utf8mb4_general_ci LIKE "files/b/%" -- <-- ADDED CONDITION
	)
	AND (
		storage = 1
		AND (
			path = "files"
			OR path LIKE "files/%"
		)
	)
ORDER BY
	[...]
LIMIT
	200
```

2024-04-16 16:09 UTC, icewind1991 requested changes
If there is only a single folder, doing the search on the folder is more efficient as it can filter down the storages it searches in

2024-04-16 16:09 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +			$scopes[] = new SearchComparison(
It will also need to filter by the correct storage id

2024-04-16 16:47 UTC, artonge commented on apps/dav/lib/Files/FileSearchBackend.php
> +			$scopes[] = new SearchComparison(
This is only needed for performance, not for the results, right?

Also, when making the search from the user's root folder, the filter for all sub storage is already present in the query, so the conditions would appear twice, no?

As an example, I added the result of `getQueryFilterForStorage` to the mix:

```sql
SELECT
	[...]
FROM
	[...]
WHERE
	[...]
	AND (
		(
			storage = 1
			AND path COLLATE utf8mb4_general_ci LIKE "files/Photos/%"
		)
		OR (
			storage = 2
			AND (
				path = "__groupfolders/1"
				OR path LIKE "\_\_groupfolders/1/%"
			)
			AND path COLLATE utf8mb4_general_ci LIKE "__groupfolders/1/%"
		)
	)
	AND (
		(
			storage = 1
			AND (
				(path = "files")
				OR (path LIKE "files/%")
			)
		)
		OR (
			storage = 2
			AND (
				(path = "__groupfolders/1")
				OR (path LIKE "\_\_groupfolders/1/%")
			)
		)
	)
ORDER BY
	[...]
LIMIT
	[...]
```

2024-04-16 16:55 UTC, artonge commented on apps/dav/lib/Files/FileSearchBackend.php
> +			$scopes[] = new SearchComparison(
But maybe having this storage filter still help for performances

2024-04-17 07:50 UTC, artonge commented on apps/dav/lib/Files/FileSearchBackend.php
> +			$scopes[] = new SearchComparison(
I also added a special handling for single folder searches.

2024-04-17 13:47 UTC, emoral435 commented on apps/dav/lib/Files/FileSearchBackend.php
> +			case 0:
nice switch cases! :)

2024-04-17 13:48 UTC, emoral435 approved these changes
This LGTM. In terms of optimization, I am generally unknowledgeable here, but the code logic makes sense :)

2024-04-22 07:22 UTC, come-nc commented on apps/dav/lib/Files/FileSearchBackend.php
> +		return $this->rootFolder->get($fileInfo->getPath());
If I send a query with the path to a file as scope, what kind of error to I get back?

2024-04-22 14:16 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +			$scopes[] = new SearchComparison(
Adding the storage id's there is required for correctness. Otherwise it can return results from a different storage but with the same internal path.

In your example, if the user also had an external storage that contained a `files/Photos` folder, it would return results from that folder even though it's not on of the folders searched

2024-04-22 14:28 UTC, icewind1991 commented on apps/dav/lib/Files/FileSearchBackend.php
> +		return $this->rootFolder->get($fileInfo->getPath());
Line 166 will throw a "Search is only supported on directories"

2024-04-22 14:32 UTC, icewind1991 approved these changes

2024-04-22 15:15 UTC, artonge commented on apps/dav/lib/Files/FileSearchBackend.php
> +		return $this->rootFolder->get($fileInfo->getPath());
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>Search is only supported on directories</s:message>
</d:error>
```

2024-04-22 15:24 UTC, merged

2024-04-22 15:27 UTC, artonge commented
/backport to stable29