fix(files): Close sidebar and update fileid when current node is deleted
nextcloud/server pull request #44897
Opened 2024-04-17 15:52 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/44637

## Summary

In case we remove a node for which the sidebar is currently open, we need to do two things:
1. Close and reset the sidebar
2. Change the current fileid in the current route

This is needed because we do not change the route to the trashbin, but stay on the current route.
So we need to change the current fileid to the parent folder.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-17 15:52 UTC, susnux commented
/backport to stable29

2024-04-17 16:04 UTC, artonge commented on apps/files/src/actions/deleteAction.ts
>  			return true
Maybe we could listen to the node deleted event in `Navigation.vue` and handle that there?
Feels out of topic here.

2024-04-17 16:14 UTC, susnux commented on apps/files/src/actions/deleteAction.ts
>  			return true
Yes and no, as I think we hack the behavior here (line 147-150) of not moving to the trash bin, so we should make sure to sanitize the route.

If we put this into the navigation (still not sure it fits there) and we would then want to move to trashbin here later, then we have two router calls conflicting.

Meaning I am fine with both, but both do not feel perfect to me :/

2024-04-22 14:53 UTC, emoral435 commented on apps/files/src/actions/deleteAction.ts
>  			return true
If I had to choose, I would agree with the behavior being kept here. Just in case other features in the future use this, I think it makes sense if they all use the same functionality, but if there is consensus to bring this to `Navigation.vue` as well, that is fine with me!

2024-04-22 15:04 UTC, emoral435 approved these changes
I think this makes sense to me to put this here, as other features would most likely want to follow the same functionality. But if others decide to move this elsewhere, it is fine by me!

2024-05-30 16:51 UTC, skjnldsv commented on apps/files/src/views/Sidebar.vue
> +		onNodeDeleted(node) {
that is the clean way :+1:

2024-05-30 16:52 UTC, skjnldsv commented on apps/files/src/actions/deleteAction.ts
> +					{ view: view.id, fileid },
Do we actually need to provide the fileid?
I think nulling it and keeping the dir parameter should still work, without the need for an extra fetch.

But this is not a big deal, I'll let you be the judge of that :+1:

2024-05-30 16:52 UTC, skjnldsv approved these changes

2024-05-30 16:56 UTC, skjnldsv requested changes
Wait :see_no_evil:

2024-05-30 17:00 UTC, skjnldsv requested changes
Wait :see_no_evil: 

Actually, I think we're mixing two different approaches here.
I would agree with Louis, whichever service handle the routing should monitor itself.

I think having the same type of handling as you did on the sidebar would be cleaner.
The action is not really responsible for the routing, it doesn't care. It deletes the file and send the event.

The routing is managed by the FileList, if a file disappear, it should be the one adjusting the fileid param.

> If we put this into the navigation (still not sure it fits there) and we would then want to move to trashbin here later, then we have two router calls conflicting.

I fail to understand why we would have conflicting rule? If a file is removed from the list (moved or deleted), and the fileid is still in the URL, we should fallback to the folder fileid. What we're doing here on the deleteAction does also apply to the moveOrCopyAction :)

2024-05-31 10:31 UTC, susnux commented
@skjnldsv I refactored the deleted node handling of the current view.
So instead of doing it within the action, the action does not care about it now, it is moved to the view like handling updated nodes.

2024-05-31 10:49 UTC, skjnldsv approved these changes

2024-06-04 10:39 UTC, artonge approved these changes

2024-06-04 11:43 UTC, merged