fix: add missing ClearGeneratedAvatarCacheCommand in autoload_static
nextcloud/server pull request #44915
Opened 2024-04-18 08:18 UTC by yemkareems

fix: add missing ClearGeneratedAvatarCacheCommand.php in autoload_static.php and declare strict_types for the new file as suggested 

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-18 08:38 UTC, artonge requested changes

2024-04-18 08:38 UTC, artonge commented on lib/composer/composer/autoload_static.php
> +        'OC\\Core\\Command\\User\\ClearGeneratedAvatarCacheCommand' => __DIR__ . '/../../..' . '/core/Command/User/ClearGeneratedAvatarCacheCommand.php',
Conflicts with https://github.com/nextcloud/server/pull/44886/files#diff-590bf0226c83824761fbf7bc57bf2b9a154c9303a649ad0c2b12ee558787a410R1179

2024-04-18 09:05 UTC, yemkareems commented on lib/composer/composer/autoload_static.php
> +        'OC\\Core\\Command\\User\\ClearGeneratedAvatarCacheCommand' => __DIR__ . '/../../..' . '/core/Command/User/ClearGeneratedAvatarCacheCommand.php',
@artonge Merged master branch to resolve the conflict

2024-04-18 11:48 UTC, artonge approved these changes

2024-04-18 11:49 UTC, artonge requested changes
Please rebase on top of master instead of merging it into this branch

2024-04-19 07:51 UTC, szaimen approved these changes

2024-04-20 09:14 UTC, artonge approved these changes

2024-04-20 09:15 UTC, merged