Better wordings in the new user modal
nextcloud/server pull request #44931
Opened 2024-04-19 08:55 UTC by Jerome-Herbinet

I've made some wording improvements ; those are more clear, IMO.
Should do what you see below. Tests from reviewers required ; thanks by advance to them.

## Before 
![2024-04-19_10-51](https://github.com/nextcloud/server/assets/33763786/aabdf177-ae88-4055-b821-4c13da210aca)

# After 
![2024-04-19_10-52](https://github.com/nextcloud/server/assets/33763786/ac6c5787-fdee-472b-91dc-db41fa9f871b)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-19 16:27 UTC, Pytal reviewed
Good idea though seems a bit long, will have to see what designers think :)

2024-04-19 20:05 UTC, susnux commented on apps/settings/src/components/Users/NewUserModal.vue
> +					{{ t('settings', 'Manages user(s) in the following group(s)') }}
I think the current wording is
```suggestion
					{{ t('settings', 'Manages accounts in the following group(s)') }}
```

2024-04-22 13:29 UTC, jancborchardt requested changes
Added 2 suggestions, simplifying the language.

Also, we shouldn’t ever use the "(s)" singular/plural writing like "group(s)". Either we write only the plural (as in my suggestion), or we programmatically check:
- If nothing or multiple are put in, use plural
- If only 1 is put in, use singular

2024-04-22 13:29 UTC, jancborchardt commented on apps/settings/src/components/Users/NewUserModal.vue
> +					{{ !settings.isAdmin ? t('settings', 'Groups (required)') : t('settings', 'Belongs to the following group(s)') }}
```suggestion
					{{ !settings.isAdmin ? t('settings', 'Groups (required)') : t('settings', 'Member of the following groups') }}
```

2024-06-13 14:59 UTC, jancborchardt approved these changes
Sounds good to me! :)

2024-06-13 14:59 UTC, jancborchardt commented
@Pytal @susnux could you check again? :)

2024-06-13 16:25 UTC, Pytal commented on apps/settings/src/components/Users/NewUserModal.vue
> +					{{ !settings.isAdmin ? t('settings', 'Groups (required)') : t('settings', 'Member of the following groups') }}
```suggestion
					{{ !settings.isAdmin ? t('settings', 'Member of the following groups (required)') : t('settings', 'Member of the following groups') }}
```

2024-06-19 19:16 UTC, Pytal commented
Looks good! Can you squash the commits @Jerome-Herbinet?

2024-06-24 22:13 UTC, susnux commented
Squashed and rebased

2024-06-24 22:13 UTC, susnux approved these changes

2024-06-24 22:39 UTC, Pytal approved these changes
![image](https://github.com/nextcloud/server/assets/24800714/febd4abb-5df1-426a-b255-6c9a5e31628d)
💃💃

2024-06-24 22:52 UTC, merged