fix(i18n): Changed grammar
nextcloud/server pull request #44945
Opened 2024-04-20 20:05 UTC by rakekniven

Reported at Transifex.

2024-04-29 13:59 UTC, nickvergessen commented on apps/files/js/mainfileinfodetailview.js
> +					starAltText: isFavorite ? t('files', 'Favoured') : t('files', 'Favorite'),
```suggestion
					starAltText: isFavorite ? t('files', 'Favoured') : t('files', 'Favour'),
```
But might need a translators hint then to make clear it's a "verb"?
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#provide-context-hints-for-translators

2024-09-19 09:47 UTC, nickvergessen commented on apps/files/js/mainfileinfodetailview.js
> +					starAltText: isFavorite ? t('files', 'Favoured') : t('files', 'Favour'),
IIRC this does not work well. the translator hint is only used on the first translation, but maybe it was only in vue files

2024-09-19 09:50 UTC, nickvergessen commented
/compile /

2024-09-19 10:17 UTC, nickvergessen approved these changes

2024-09-19 10:19 UTC, Altahrim approved these changes

2024-09-19 10:21 UTC, miaulalala requested changes

2024-09-23 14:08 UTC, nickvergessen commented
> Conflicting files
> - apps/files/js/mainfileinfodetailview.js
> - apps/files/js/tagsplugin.js 

Both got deleted. So if we want to backport we should copy this commit to stable30 and redo the PR for master

2024-09-24 05:29 UTC, merged