fix(contactsMenu): Attach user cloud to each contact entry
nextcloud/server pull request #44954
Opened 2024-04-22 08:44 UTC by Fenn-CS

The contact entry should carry cloud information, this can help to fix various issues including:

- Displaying correct avatar links for federated users

This can also lead to UI improvements in the frontend where, it's federated contacts are shown with a marker or indicator on the UI.

* Resolves: https://github.com/nextcloud/server/issues/44319

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-04-22 15:42 UTC, Fenn-CS reviewed
To solve this issue we could simple use the `isUser` property of the contact along side `isNouser` boolean of [`NcAvatar`](https://nextcloud-vue-components.netlify.app/#/Components/NcAvatar) to show the text generated icons.

However, here:

- I instead try to link to the actual avatars on the remote server, since the links public
- I am adding the cloud data to be passed to the frontend

Problems:

- This code is able to load the avatars from a federated server but would like to "Content Security Policy" errors if the remote server is unsecured.

-----

There are other places in the code base such as [here](https://github.com/nextcloud/server/blob/097f04c8b78851eb556d9dd1de2786be5e5f9aa5/apps/comments/lib/Search/CommentsSearchProvider.php#L75) where the current approach is used but we could swap if this attempt to directly load the avatars from the federated server is successful/useful.


@nickvergessen since you are familiar with section of the code, does this approach make sense?

2024-04-22 17:32 UTC, nickvergessen requested changes

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +				preg_match('/^(.*?)@(https?:\/\/.*?)$/', $contact['CLOUD'][0], $matches);
Please use the `ICloudManager::resolve()` method instead?

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/Contacts/ContactsMenu/Entry.php
> +	 * @return array{id: int|string|null, fullName: string, avatar: string|null, topAction: mixed, actions: array, lastMessage: '', emailAddresses: string[], profileTitle: string|null, profileUrl: strin
cloud should be called cloudId to be more clear and the type should be the array you define in the other file

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/Federation/CloudId.php
> +	public function jsonSerialize(): array {
Should implement the interface JsonSerializable?

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +				$avatar = $this->urlGenerator->linkToRemoteRouteAbsolute($remoteServer, 'core.avatar.getAvatar', ['userId' => str_replace('/', ' ', $username), 'size' => 64]);
This assumes every cloud ID is a nextcloud? 🫣

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/URLGenerator.php
> +	public function linkToRemoteRouteAbsolute(string $remote, $routeName, array $arguments = []): string {
This should not be here or on the public interface

2024-04-22 17:32 UTC, nickvergessen commented on lib/private/Federation/CloudId.php
> +	public function jsonSerialize(): array {
That being said, should be on the public interface?

2024-04-22 17:34 UTC, nickvergessen commented
> does this approach make sense

From my POV it's not okay...

2024-04-22 19:48 UTC, Fenn-CS commented
Based on conversation with @nickvergessen, this needs more effort especially as the content security policy can't changed to allow all trusted servers.

So this would remain in draft in favor of : https://github.com/nextcloud/server/pull/44972

Eventually, I could copy the proxy strategy from https://github.com/nextcloud/spreed/blob/main/lib/Controller/AvatarController.php#L244 where the server downloads the image and sends in on the instance URL.

2025-07-11 12:04 UTC, closed without merging

2025-07-11 12:10 UTC, skjnldsv commented
Closing as stale and EOL branch.
If still required, please resume your work on it by rebasing and requesting for reviews again :pray: