feat: TaskProcessing API
nextcloud/server pull request #45094
Opened 2024-04-29 14:38 UTC by marcelklehr

## Summary

## TODO

- [ ] Clean up old tasks
- [ ] Check if user has access to files
- [ ] OCS API

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-03 08:27 UTC, julien-nc reviewed
Yay, it looks gooood. Didn't make a full review yet, just using it for the work on the assistant.
It breaks NC though. I tried to rebase on master, no luck.
```
PHP Fatal error:  Class OC\\Files\\Node\\LazyR
oot contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Files\\IRootFolder::getAppDataDirectoryName) in /var/www/html/dev
/server/lib/private/Files/Node/LazyRoot.php on line 39
```

2024-05-03 08:27 UTC, julien-nc commented on lib/public/TaskProcessing/Events/AbstractTextProcessingEvent.php
> +abstract class AbstractTextProcessingEvent extends Event {
```suggestion
abstract class AbstractTaskProcessingEvent extends Event {
```

Or maybe it's intentional?

2024-05-03 08:29 UTC, marcelklehr commented on lib/public/TaskProcessing/Events/AbstractTextProcessingEvent.php
> +abstract class AbstractTextProcessingEvent extends Event {
oopsa

2024-05-03 09:19 UTC, julien-nc commented on lib/public/TaskProcessing/IProvider.php
> +	public function getTaskType(): string;
```suggestion
	public function getTaskTypeId(): string;
```
Maybe

2024-05-03 09:55 UTC, marcelklehr commented on lib/public/TaskProcessing/IProvider.php
> +	public function getTaskType(): string;
:+1:

2024-05-05 16:15 UTC, julien-nc requested changes
A bump of the server version is needed to trigger the migration step.

2024-05-05 16:15 UTC, julien-nc commented on lib/public/TaskProcessing/Task.php
> +			'id' => $this->getId(),
```suggestion
			'id' => $this->getId(),
			'type' => $this->getTaskTypeId(),
```
We need the type here otherwise it's not included when getting a task with `/ocs/v2.php/taskprocessing/task/TASK_ID` for example.

2024-05-06 07:15 UTC, marcelklehr commented on lib/public/TaskProcessing/Task.php
> +			'id' => $this->getId(),
Wow. Nice catch!

2024-05-06 07:33 UTC, marcelklehr commented
> A bump of the server version is needed to trigger the migration step.

Like this?

version.php
```diff
-$OC_Version = [30, 0, 0, 0];
+$OC_Version = [30, 0, 0, 1];
```

2024-05-06 09:20 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     optionalOutputShape: CoreTaskProcessingShape[],
Having two separate arrays for optional/non-optional is a bit annoying to use as an API consumer. I'd prefer a simple boolean value in the CoreTaskProcessingShape that indicates if it is optional or not.

2024-05-06 09:20 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     id: ?int,
How can the id be null? I haven't looked at the implementation, but this looks counter intuitive to me.

2024-05-06 09:20 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
id is an abbreviation for identifier, so this field name is really confusing.

2024-05-06 09:20 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     progress: ?float
Is this 0-1 or 0-100? In the later case I'd prefer an int without any decimal places (as that would likely be imprecise anyway and not helpful for the end user).

2024-05-06 09:20 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     status: 0|1|2|3|4|5,
Could the integer statuses be replaced by discrete strings? That is more human readable and also easier to work with as an API consumer because it is already clear from the value what the status means without looking into the source code or docs.

2024-05-06 09:35 UTC, come-nc commented on core/Controller/TaskProcessingApiController.php
> +				'inputShape' => array_map(fn (ShapeDescriptor $descriptor) => $descriptor->jsonSerialize(), $taskType['inputShape']),
Do you really need to do that by hand? 
I’m pretty sure json_encode will call jsonSerialize recursively.
Or is it because DataResponse does not always serialize to json?

2024-05-06 09:41 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +				'inputShape' => array_map(fn (ShapeDescriptor $descriptor) => $descriptor->jsonSerialize(), $taskType['inputShape']),
It does, so this is indeed not necessary and it shouldn't be called explicitly to avoid returning json inside xml when the API is used in XML mode.

2024-05-06 09:43 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +				'inputShape' => array_map(fn (ShapeDescriptor $descriptor) => $descriptor->jsonSerialize(), $taskType['inputShape']),
The jsonSerialize method is abused a little bit because it doesn't actually return json and only converts it to an array. If the API is used in json mode then it wouldn't be necessary, but for xml it is. It's also needed for psalm because it doesn't know the method would be called automatically and thus would only see the class and not the array.

2024-05-06 09:54 UTC, come-nc commented on core/Controller/TaskProcessingApiController.php
> +					$ids += $task->getInput()[$key];
```suggestion
				$value = $task->getInput()[$key];
				if (is_array($value)) {
					$ids += $value;
```
Avoid calling the method several times.

2024-05-06 09:54 UTC, come-nc commented on core/Controller/TaskProcessingApiController.php
> +						$ids += $task->getOutput()[$key];
This will also avoid inconsistencies like this `getInput` vs `getOutput` confusion.

2024-05-06 09:54 UTC, come-nc commented on core/Controller/TaskProcessingApiController.php
> +			$this->taskProcessingManager->getUserTask($taskId, $this->userId);
Is this call necessary? If yes add a comment explaining why.

2024-05-06 09:54 UTC, come-nc commented on core/Migrations/Version30000Date20240429122720.php
> +			$table->addIndex(['last_updated'], 'tasks_updated');
Name seems dangerously generic, might clash no? Don’t we have a naming pattern or something?

2024-05-06 09:54 UTC, come-nc commented on lib/composer/composer/autoload_static.php
> +        ),
Should not appear here I think, not sure.

2024-05-06 09:54 UTC, come-nc commented on lib/private/AppFramework/Bootstrap/RegistrationContext.php
> +	private $taskProcessingProviders = [];
```suggestion
	private array $taskProcessingProviders = [];
```

2024-05-06 09:54 UTC, come-nc commented on lib/private/AppFramework/Bootstrap/RegistrationContext.php
> +	private $taskProcessingTaskTypes = [];
```suggestion
	private array $taskProcessingTaskTypes = [];
```

2024-05-06 09:54 UTC, come-nc commented on lib/private/TaskProcessing/Db/Task.php
> +		$taskEntity = Task::fromParams([
```suggestion
	public static function fromPublicTask(OCPTask $task): self {
		/** @var Task $taskEntity */
		$taskEntity = self::fromParams([
```

2024-05-06 09:54 UTC, come-nc commented on lib/private/TaskProcessing/Manager.php
> +				$providers[$provider->getId()] = $provider;
No need to check for id clash?

2024-05-06 09:54 UTC, come-nc commented on lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
> +		} catch (NotFoundException $e) {
When does this happen?
If cleaning text2image throws, audio2text will never be cleaned.

2024-05-06 09:56 UTC, come-nc commented on core/Controller/TaskProcessingApiController.php
> +				'inputShape' => array_map(fn (ShapeDescriptor $descriptor) => $descriptor->jsonSerialize(), $taskType['inputShape']),
That’s unfortunate. Most of the code in the API controller is serializing by hand.

2024-05-06 09:58 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
This should be absolutely avoided to prevent shadowing mismatches. Annotate the return type of the jsonSerialize instead to get it working.

2024-05-06 09:58 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +			return new DataResponse([]);
Return null instead of an empty array whenever possible (unless it is actually an empty array).

2024-05-06 10:48 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
This naming is consistent with previous APIs, e.g. the text processing API. The purpose of the property is for apps to be able to reference other entities in their tasks without having to create a new table mapping task id to their internal id.

2024-05-06 10:49 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     progress: ?float
It's 0-1

2024-05-06 10:51 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
I see, I'd still prefer if a more expressive name would be used. We don't need to align this with existing APIs, we can fix it right here.

2024-05-06 10:52 UTC, marcelklehr commented on core/Migrations/Version30000Date20240429122720.php
> +			$table->addIndex(['last_updated'], 'tasks_updated');
I've never heard of a naming pattern tbh, would be great

2024-05-06 10:59 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
I know. I wasn't able to get it working without this.

2024-05-06 11:02 UTC, marcelklehr commented on lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
> +		} catch (NotFoundException $e) {
It happens when no tasks involving files or the mentioned task types have been run yet as the folders are created on demand.

2024-05-06 11:06 UTC, provokateurin commented on core/Migrations/Version30000Date20240429122720.php
> +			$table->addIndex(['last_updated'], 'tasks_updated');
Yeah, the index names need to be completely unique for postgres

2024-05-06 11:07 UTC, provokateurin commented on lib/composer/composer/autoload_static.php
> +        ),
Just don't commit these files (or run `composer i --no-dev` but that also causes a different diff)

2024-05-06 11:09 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
I'm sure this is possible, I'll give it a try

2024-05-06 11:19 UTC, provokateurin requested changes

2024-05-06 11:19 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +	 * @param array<string, mixed> $input Input text
Not only text, right?

2024-05-06 11:19 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +	 * @return list<mixed>
Should be int and not mixed

2024-05-06 11:19 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     output: ?array<string, mixed>,
I'm not happy about these mixed types, can we narrow them down in a sensible way?

2024-05-06 11:27 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     output: ?array<string, mixed>,
Yeah, I was just lazy.. I'll make it more specific :)

2024-05-06 11:36 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     output: ?array<string, mixed>,
You could also define them as a separate type alias so you can easily reuse them everywhere.

2024-05-06 12:45 UTC, come-nc commented on lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
> +		} catch (NotFoundException $e) {
And you know for a fact that all 3 folders are created together, it’s not possble to have only one of them?

2024-05-06 12:54 UTC, marcelklehr commented on lib/private/TaskProcessing/RemoveOldTasksBackgroundJob.php
> +		} catch (NotFoundException $e) {
No, I already fixed it :)

2024-05-06 12:57 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
because it is nullable. When a consumer creates a task, they don't know the ID of the task. The id is only set after it's scheduled.

2024-05-06 13:00 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
But isn't it referring to the ID in the database which must be know right after creation? Otherwise it should be fine to have it nullable if the API can return tasks that have it their ID set to null.

2024-05-06 14:15 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +			$json = $task->jsonSerialize();
the Task class represents a data object which exists before the data is entered into the db

2024-05-06 14:15 UTC, julien-nc commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
identificator? :grin: 
custom_id?

2024-05-06 14:17 UTC, marcelklehr commented on lib/composer/composer/autoload_static.php
> +        ),
The point of committing these files is to appease the autoloader checker

2024-05-06 14:23 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
i do think being consistent between APIs of the same software project is a value worth striving for.

2024-05-06 14:38 UTC, marcelklehr commented on lib/composer/composer/autoload_static.php
> +        ),
cc @ChristophWurst as the person who introduced barmani's composer plugin

2024-05-06 14:39 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     optionalOutputShape: CoreTaskProcessingShape[],
I vote for keeping it like this, because I'm lazy

2024-05-06 14:39 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     output: ?array<string, mixed>,
Should be better now

2024-05-06 16:08 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     optionalOutputShape: CoreTaskProcessingShape[],
In my opinion single arrays make it a lot easier to iterate and create UI elements for. I'm not vetoing, but I also don't see the point in not making it a bit nicer.

2024-05-07 07:04 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
In principle yes, but I think it was already wrong to call it `id` and `identifier` in the previous APIs, so we can fix it here. I'd go with `custom_id` like Julien suggested.

2024-05-07 10:19 UTC, marcelklehr commented on lib/composer/composer/autoload_static.php
> +        ),
And how should I know what to add? Doesn't seem like an ideal process

2024-05-07 10:24 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     identifier: ?string,
Alright, I'm not willing to have a fight over this.

2024-05-07 10:30 UTC, ChristophWurst commented on lib/composer/composer/autoload_static.php
> +        ),
It's far from ideal. The ideal solution would be to stop vendoring PHP dependencies.

2024-05-07 11:35 UTC, julien-nc requested changes

2024-05-07 11:35 UTC, julien-nc commented on core/Migrations/Version30000Date20240429122720.php
> +			$table->addIndex(['user_id', 'app_id', 'custom_id'], 'taskp_tasks_uid_appid_ident');
```suggestion
			$table->addIndex(['user_id', 'app_id', 'custom_id'], 'taskp_tasks_uid_appid_cid');
```
Nitpicking

2024-05-08 07:53 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     optionalOutputShape: CoreTaskProcessingShape[],
:+1:

2024-05-08 15:32 UTC, julien-nc requested changes
Another partial review:
* We could use (optional) default values for input shape fields. It might not make sense in many cases but for example: "number of images" for TextToImage could have 1 as default value. Wdyt?
* The assistant needs a manager method AND/OR an endpoint to get all user's tasks (with a task type ID optional filter). Wdyt?
* [minor] CSRF might not be needed for `taskprocessing/tasks/{taskId}/file/{fileId}`, not a big deal, I currently add the requesttoken GET param to display images in the UI.
* Task result files stored in data/appdata_iid/core/TaskProcessing/ are empty for the TextToImage task type (at least). I tried 2 providers (OpenAI and Replicate which are providers for the old TTI API).

2024-05-10 05:09 UTC, marcelklehr commented
* The assistant needs a manager method AND/OR an endpoint to get all user's tasks **fixed** :heavy_check_mark: 
 * [minor] CSRF might not be needed for taskprocessing/tasks/{taskId}/file/{fileId} **fixed** :heavy_check_mark: 
 * Task result files stored in data/appdata_iid/core/TaskProcessing/ are empty for the TextToImage task type. **fixed** :heavy_check_mark:

2024-05-10 07:05 UTC, marcelklehr commented
> The manager is unable to read input files if they are in a user's storage.

Can you check if it works now?

2024-05-10 11:24 UTC, julien-nc requested changes
> The assistant needs a manager method AND/OR an endpoint to get all user's tasks fixed ✔️

Yay. Small mistake. It works with my suggested change.

> [minor] CSRF might not be needed for taskprocessing/tasks/{taskId}/file/{fileId} fixed ✔️

Thanks :ok_hand: 

> Task result files stored in data/appdata_iid/core/TaskProcessing/ are empty for the TextToImage task type. fixed ✔️

Yay, fixed.

> The manager is unable to read input files if they are in a user's storage

Still fails

[read.input.file.txt](https://github.com/nextcloud/server/files/15274330/read.input.file.txt)

2024-05-10 11:24 UTC, julien-nc commented on lib/private/TaskProcessing/Manager.php
> +			$taskEntities = $this->taskMapper->findUserTasksByApp($userId, $taskTypeId, $customId);
```suggestion
			$taskEntities = $this->taskMapper->findByUserAndTaskType($userId, $taskTypeId, $customId);
```

2024-05-10 11:24 UTC, julien-nc commented on lib/public/TaskProcessing/IManager.php
> +	 * @param string|null $taskTypeId The task type id to filter by
```suggestion
	 * @param string|null $taskTypeId The task type id to filter by
	 * @param string|null $customId
```

2024-05-10 11:37 UTC, julien-nc commented
@marcelklehr 

* How do we deal with context write? I think it makes sense now to have a ContextWrite task type defined in server so we can have specific instruct strings in each provider. It would also remove one more "custom UI" and "custom logic" in the assistant. :soap: (this is a soap)
* We should talk about how/when `SynchronousBackgroundJob` is queued. As it is always in the job list, the worker constantly runs it which is weird when there is no task. Do you think it would be possible to only queue it when needed? I'm thinking:
    * Queue the job when scheduling a task
    * The job queues itself only if there is still at least one scheduled task

2024-05-13 06:24 UTC, marcelklehr commented
> I think it makes sense now to have a ContextWrite task type defined in server

Great idea!

> Do you think it would be possible to only queue it when needed?

Totally makes sense!

2024-05-13 08:01 UTC, marcelklehr commented
> The manager is unable to read input files if they are in a user's storage.

Can you check if it works now?

2024-05-13 09:45 UTC, julien-nc commented
@marcelklehr Now I get `OCA\\OpenAi\\SpeechToText\\STTProvider::transcribeFile(): Argument #1 ($file) must be of type OCP\\Files\\File, false given, called in /blabla/server/lib/private/TaskProcessing/Manager.php on line 364`.

You can reproduce by using the STT provider in integration_openai and the `enh/task-processing-api-support` branch of the assistant (don't forget to compile the JS). I can give you an OpenAI API key if you want.

2024-05-13 09:52 UTC, marcelklehr commented
That's a new error :tada: and a different bug. Now it should work.

2024-05-13 09:52 UTC, julien-nc commented
About queuing only when needed: So now the job is queued each time a task is scheduled and "re-queued" when it finishes if there still are some scheduled tasks, right?
If so, in the manager::schedule method, the bg job should probably better be scheduled only if it's not already scheduled, otherwise we can end up with the job being queued multiple times. Wdyt?

Thanks for adding the ContextWrite task type!

2024-05-13 09:53 UTC, marcelklehr commented
> If so, in the manager::schedule method, the bg job should probably better be scheduled only if it's not already scheduled, otherwise we can end up with the job being queued multiple times.

I don't think it  can be queued multiple times, actually... Let me check

2024-05-13 09:58 UTC, julien-nc commented
> I don't think it can be queued multiple times, actually... Let me check Yep, jobs are unique by class and argument.

Yay!

> I don't think it can be queued multiple times, actually... Let me check Yep, jobs are unique by class and argument.

It works now! You're faster than light.

2024-05-13 12:25 UTC, julien-nc approved these changes

2024-05-14 07:30 UTC, provokateurin requested changes

2024-05-14 07:30 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     type: int,
Could this be a string enum instead? That would make it a lot easier to use IMO

2024-05-14 07:30 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     mandatory: bool,
I'd say `required` is a more common term for this, but it doesn't really make a difference.

2024-05-14 07:30 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     outputShape: CoreTaskProcessingShape[],
```suggestion
 *     inputShapes: CoreTaskProcessingShape[],
 *     outputShapes: CoreTaskProcessingShape[],
```
Since they are an array the names should be plural as well.

2024-05-14 07:30 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     output: ?array<string, numeric|list<numeric>|string|list<string>>,
I think it would make sense to move this type to a separate type and reuse it

2024-05-14 07:30 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     output: ?array<string, numeric|list<numeric>|string|list<string>>,
```suggestion
 *     output: null|array<string, numeric|list<numeric>|string|list<string>>,
```
The question mark can be overlooked quickly and for me personally it's hard to parse if it means the first type can also be null or the whole type can be null, so this makes it clear what you want (though both should work).

2024-05-14 07:33 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     outputShape: CoreTaskProcessingShape[],
I disagree. It's the shape of the input. It's one input (because it's input once) so one shape.

2024-05-14 08:05 UTC, provokateurin approved these changes

2024-05-14 08:08 UTC, provokateurin commented on core/ResponseDefinitions.php
> + *     outputShape: CoreTaskProcessingShape[],
Hm that makes sense, how about just `input` and `output`?

2024-05-14 08:16 UTC, marcelklehr commented on core/ResponseDefinitions.php
> + *     outputShape: CoreTaskProcessingShape[],
Well it's not an input but just the shape of the input to be :)

2024-05-14 08:20 UTC, marcelklehr commented
:tada: :blue_heart:

2024-05-14 08:21 UTC, provokateurin commented
(Please note my last comment before merging)

2024-05-15 09:43 UTC, merged

2024-07-18 10:10 UTC, nickvergessen commented on lib/public/Files/IRootFolder.php
> +	public function getAppDataDirectoryName(): string;
@marcelklehr Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(all changes in lib/public/)