fix(Redis): catch `RedisException`s for operational core on redis fai…
nextcloud/server pull request #45154
Opened 2024-05-02 13:19 UTC by kyteinsky

…lure

## Summary
When redis connection fails, i.e. the redis server is unavailable, an uncaught `RedisException` is thrown which causes issues with the whole system, rendering it unusable for that duration. This happens only when redis is configured as the cache provider and is unreachable.  
The goal is to catch those exceptions and make it behave like it would when no cache provider is configured.

It should also solve the issue where the server-side encryption app gets disabled after multiple redis exceptions. (untested as of writing)

Known issues:
1. Lock mechanism does not work well when redis is offline, which in turn affects apps like text. (https://github.com/nextcloud/server/blob/master/lib/private/Lock/MemcacheLockingProvider.php#L87 is one affected place)

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-05 15:49 UTC, joshtrichards commented
Related: #14995

2024-05-10 15:22 UTC, kyteinsky commented
> I view this as a valid exception. It's intentional: something is broken in the configured service environment.

Sure, but if you see it this way, cache should not be an essential component for a system to function. It should just fetch the data from the original source if the cache is not available like a cache miss. And we do inform the admin of the broken part through the logs.

> Isn't this just painting over an environmental or config matter? If ones Redis service is going offline, that is what needs to be addressed.

Maybe we could improve the offline state handling, this is mainly aimed at the intermittent connection issues with the cache server.

> I'm not a fan of continuing on if the Redis service disappears. Particularly since Transactional File Locking is generally configured to use it when it's present.

Yeah, that is an issue not yet addressed. One possible solution could be to use the ArrayCache when the default cache is not available (even in clustered setups?). Please inform me here if I misunderstood the transactional file locking mechanism.

> Do you have a reference for this matter?

```
"{""reqId"":""<req_id>""";level:3;"time:""2024-03-11T00:45:15+00:00""";"remoteAddr:""REDACTED""";;"app:""no app in context""";"method:""GET""";;"message:""App encryption threw an error during app.php load and will be disabled: read error on connection to REDACTED:6379""";"userAgent:""Mozilla/5.0 (compatible; phpservermon/3.5.2; +https://github.com/phpservermon/phpservermon)""";"version:""27.1.5.2""";"exception:{""Exception"":""RedisException""";"Message:""read error on connection to REDACTED:6379""";Code:0;"Trace:[{""file"":""/var/www/html/lib/private/Memcache/Redis.php""";line:75;"function:""get""";"class:""RedisCluster""";"type:""->""";"args:[""<random_uuid>/user_backend_map<random_uuid>""]}";"{""file"":""/var/www/html/lib/private/Memcache/WithLocalCache.php""";line:24;"function:""get""";"class:""OC\\Memcache\\Redis""";"type:""->""";"args:[""<random_uuid>""]}";"{""file"":""/var/www/html/lib/private/User/Manager.php""";line:169;"function:""get""";"class:""OC\\Memcache\\WithLocalCache""";"type:""->""";"args:[""<random_uuid>""]}";"{""file"":""/var/www/html/lib/private/Files/SetupManager.php""";line:374;"function:""get""";"class:""OC\\User\\Manager""";"type:""->""";"args:[""files_encryption""]}";"{""file"":""/var/www/html/lib/private/Files/SetupManager.php""";line:381;"function:""getUserForPath""";"class:""OC\\Files\\SetupManager""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Files/Mount/Manager.php""";line:97;"function:""setupForPath""";"class:""OC\\Files\\SetupManager""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Files/Filesystem.php""";line:306;"function:""find""";"class:""OC\\Files\\Mount\\Manager""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Files/View.php""";line:1145;"function:""resolvePath""";"class:""OC\\Files\\Filesystem""";"type:""::""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Files/View.php""";line:528;"function:""basicOperation""";"class:""OC\\Files\\View""";"type:""->""";"args:[""file_exists""";/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey]};"{""file"":""/var/www/html/lib/private/Encryption/Keys/Storage.php""";line:268;"function:""file_exists""";"class:""OC\\Files\\View""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Encryption/Keys/Storage.php""";line:228;"function:""getKey""";"class:""OC\\Encryption\\Keys\\Storage""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""]}";"{""file"":""/var/www/html/lib/private/Encryption/Keys/Storage.php""";line:120;"function:""getKeyWithUid""";"class:""OC\\Encryption\\Keys\\Storage""";"type:""->""";"args:[""/files_encryption/OC_DEFAULT_MODULE/pubShare_<id1>.publicKey""";null]};"{""file"":""/var/www/html/apps/encryption/lib/KeyManager.php""";line:624;"function:""getSystemUserKey""";"class:""OC\\Encryption\\Keys\\Storage""";"type:""->""";"args:[""pubShare_<id1>.publicKey""";OC_DEFAULT_MODULE]};"{""file"":""/var/www/html/apps/encryption/lib/KeyManager.php""";line:169;"function:""getPublicShareKey""";"class:""OCA\\Encryption\\KeyManager""";"type:""->""";args:[]};"{""file"":""/var/www/html/apps/encryption/lib/Users/Setup.php""";line:62;"function:""validateShareKey""";"class:""OCA\\Encryption\\KeyManager""";"type:""->""";args:[]};"{""file"":""/var/www/html/apps/encryption/lib/AppInfo/Application.php""";line:55;"function:""setupSystem""";"class:""OCA\\Encryption\\Users\\Setup""";"type:""->""";args:[]};"{""file"":""/var/www/html/apps/encryption/appinfo/app.php""";line:37;"function:""setUp""";"class:""OCA\\Encryption\\AppInfo\\Application""";"type:""->""";"args:[[""OC\\Encryption\\Manager""]]}";"{""file"":""/var/www/html/lib/private/App/AppManager.php""";line:525;"args:[""/var/www/html/apps/encryption/appinfo/app.php""]";"function:""require_once""}";"{""file"":""/var/www/html/lib/private/App/AppManager.php""";line:416;"function:""requireAppFile""";"class:""OC\\App\\AppManager""";"type:""::""";"args:[[""OCA\\Encryption\\AppInfo\\Application""]]}";"{""file"":""/var/www/html/lib/private/App/AppManager.php""";line:216;"function:""loadApp""";"class:""OC\\App\\AppManager""";"type:""->""";"args:[""encryption""]}";"{""file"":""/var/www/html/lib/private/legacy/OC_App.php""";line:126;"function:""loadApps""";"class:""OC\\App\\AppManager""";"type:""->""";"args:[[""filesystem""";logging]]};"{""file"":""/var/www/html/lib/base.php""";line:1051;"function:""loadApps""";"class:""OC_App""";"type:""::""";"args:[[""filesystem""";logging]]};"{""file"":""/var/www/html/index.php""";line:38;"function:""handleRequest""";"class:""OC""";"type:""::""";args:[]}];"File:""/var/www/html/lib/private/Memcache/Redis.php""";Line:75;"message:""App encryption threw an error during app.php load and will be disabled: read error on connection to REDACTED:6379""";exception:{};"CustomMessage:""App encryption threw an error during app.php load and will be disabled: read error on connection to REDACTED:6379""}}"
```

2024-05-17 15:30 UTC, ChristophWurst commented
I'm okay with letting Nextcloud run when Redis goes down, but

1) Make sure there is error logging on a high level
2) Only if transactional file locking does not rely on it (it would allow inconsistencies otherwise at the switch from Redis to database and back, especially if Redis is up and down often)

2024-05-21 14:30 UTC, icewind1991 commented
- I think this is fine with file locking:
  - It won't fallback to DB locking silently since that is based on if redis is configured, not if redis can be connected
  - acquiring/changing locks look they will fail hard (correctly) when the redis operation fails. (though `releaseLock` might need some changes)
- 5m seems like a long timeout, especially since there is little cost to trying and failing to connect
- Probably makes sense to retry with a small (<1s) delay before returning `null` to transparently handle intermittent failures
- Logging needs to be added when the redis fails

2024-06-05 07:19 UTC, nickvergessen requested changes
> The goal is to catch those exceptions and make it behave like it would when no cache provider is configured.

From my perspective this is not a good idea.
File locks that have been created are ignored, new locks that are created during this time are ignored once the redis server is back again. Same things for bruteforce attempts, rate limits, ....

I think if an admin is okay with "running the server without redis for the timebeing" they can simply uncomment the redis config themselves.

2024-06-05 07:19 UTC, nickvergessen commented on lib/private/RedisFactory.php
> +			$this->config->setValue('redis.conn_cooldown', \time());
This will fail hard as well if the config is not writable. Similarly it will be an issue if numerous requests try to write the config file at the same time.

2024-06-05 07:22 UTC, nickvergessen commented on lib/private/RedisFactory.php
> +				$this->logger->info('Redis connection is in cooldown, skipping connection attempt');
I would still log this as error, or warning at least.
Info is below the default and now there is no "wall of logs" anymore that would immediatelly tell a sysadmin that a server was down/is offline/...

2024-06-06 10:11 UTC, kyteinsky commented
After some more discussions, it feels like the approach is too wide-ranged. We were mainly trying to prevent the encryption app from getting disabled when redis is down, but we will use a more direct approach to cover that specific case.

2024-06-06 10:11 UTC, closed without merging