fix(dav): Try basic auth for ajax WebDAV requests
nextcloud/server pull request #45207
Opened 2024-05-06 18:22 UTC by susnux

## Summary

Allow using basic auth with ajax requests on WebDAV.
The idea why the code was added in the first place was to ensure that if basic auth fails the user gets not asked by the browser for the correct credentials.
We still keep this behavior by throwing a 401 error in case of failed basic auth.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-07 10:47 UTC, susnux commented
The problem gets visible because previous versions of `@nextcloud/axios` were not setting the header, but the latest version will set the `X-Requested-With` header by default.

Meaning the alternative to this is to drop the `X-Requested-With: XMLHttpRequest` from axios requests to DAV like we were doing with current versions (currently we do not set `X-Requested-With` for ajax requests to DAV to prevent this.
So I think this solution here is cleaner than faking the kind of request :sweat_smile:

2024-05-07 14:26 UTC, come-nc approved these changes

2024-05-07 14:26 UTC, come-nc commented on apps/dav/tests/unit/Connector/Sabre/AuthTest.php
> +	/** @var ISession|MockObject */
```suggestion
	/** @var ISession&MockObject */
```

2024-05-07 14:26 UTC, come-nc commented on apps/dav/tests/unit/Connector/Sabre/AuthTest.php
> +	/** @var ISession|MockObject */
(and all the others)

2024-05-08 07:35 UTC, nickvergessen requested changes, later dismissed
Blocking temporarily

2024-06-18 15:43 UTC, icewind1991 approved these changes

2024-06-20 10:28 UTC, merged

2024-08-08 12:32 UTC, sorbaugh commented
/backport to stable29