Update pdf icon
nextcloud/server pull request #45218
Opened 2024-05-07 11:06 UTC by marcoambrosini

| Before | After |
| - | - | 
| <img width="574" alt="Screenshot 2024-05-07 at 13 04 28" src="https://github.com/nextcloud/server/assets/26852655/5fcec74e-0e47-4bb1-9d3d-db301515d24a"> | <img width="574" alt="Screenshot 2024-05-07 at 13 03 31" src="https://github.com/nextcloud/server/assets/26852655/93bf008c-0faa-433c-972f-040af528ede9"> |

2024-05-07 11:11 UTC, susnux commented on core/img/filetypes/application-pdf.svg
> +<path d="M76 12H20C15.6 12 12 15.6 12 20V76C12 80.4 15.6 84 20 84H76C80.4 84 84 80.4 84 76V20C84 15.6 80.4 12 76 12ZM38 46C38 49.2 35.2 52 32 52H28V60H22V36H32C35.2 36 38 38.8 38 42V46ZM58 54C58 57.2
Should we not use the MDI icon?

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3M9.5 11.5C9.5 12.3 8.8 13 8 13H7V15H5.5V9H8C8.8 9 9.5 9.7 9.5 10.5V11.5M14.5 13.5C14.5 14.3 13.8 15 13 15H10.5V9H13C13.8 9 14.5 9.7 14.5 10.5V13.5M18.5 10.5H17V11.5H18.5V13H17V15H15.5V9H18.5V10.5M12 10.5H13V13.5H12V10.5M7 10.5H8V11.5H7V10.5Z" fill="#FF2116" /></svg>
```

2024-05-07 12:37 UTC, jancborchardt requested changes, later dismissed
As discussed with @marcoambrosini, we should keep the previous coloring of the icon because it looks less intense and much better together with the default folder color.

2024-05-07 12:37 UTC, marcoambrosini commented on core/img/filetypes/application-pdf.svg
> +<path d="M76 12H20C15.6 12 12 15.6 12 20V76C12 80.4 15.6 84 20 84H76C80.4 84 84 80.4 84 76V20C84 15.6 80.4 12 76 12ZM38 46C38 49.2 35.2 52 32 52H28V60H22V36H32C35.2 36 38 38.8 38 42V46ZM58 54C58 57.2
You mean dropping the svg file and using the one from the library?

2024-05-13 09:29 UTC, ShGKme approved these changes

2024-05-13 09:31 UTC, susnux approved these changes

2024-05-13 13:50 UTC, merged

2024-05-13 16:13 UTC, AndyScherzinger commented
/backport to stable29

2024-05-14 08:31 UTC, jancborchardt approved these changes