fix(settings): define a 'heartbeat' route, so SecurityHeaders can handle redirected root
nextcloud/server pull request #45228
Opened 2024-05-08 00:05 UTC by smokris

## Problem
On sites where the root (`/`) path is redirected (e.g. when using the [Social login plugin](https://github.com/zorn-v/nextcloud-social-login)), the Admin Overview page incorrectly shows errors about security headers not being set:

> Some headers are not set correctly on your instance - The `X-Robots-Tag` HTTP header is not set to `noindex,nofollow`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. - The `X-Permitted-Cross-Domain-Policies` HTTP header is not set to `none`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. For more details see the documentation ↗.

## Analysis
In `lib/base.php`, the request path `/heartbeat` is [handled specially by returning early](https://github.com/nextcloud/server/blob/c60de5bea094ff1b1791bb6bc630ab20df39553d/lib/base.php#L1003), but no formal route is defined for it.

`OCA\Settings\SetupChecks\SecurityHeaders` [calls `URLGenerator::linkToRoute('heartbeat')`](https://github.com/nextcloud/server/blob/c60de5bea094ff1b1791bb6bc630ab20df39553d/apps/settings/lib/SetupChecks/SecurityHeaders.php#L60), but the generated URL is emptystring, since there's no route defined by that name.

It then performs a request on the root (`/`) path (instead of the expected `/heartbeat` path).  On sites where the root path redirects, `SecurityHeaders` then incorrectly analyzes the headers _of the redirect_, instead of analyzing the headers _of the Nextcloud heartbeat page_.

## Proposed solution
Define a `heartbeat` route, so that `URLGenerator::linkToRoute('heartbeat')` returns `/heartbeat` as the `SecurityHeaders` test seems to expect.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [~] Screenshots before/after for front-end changes — N/A
- [~] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required — N/A
- [~] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes) — N/A

2024-05-10 13:57 UTC, provokateurin requested changes
It would be good to add a test to the setup checks that validates that the check now works.

2024-05-10 13:57 UTC, provokateurin commented on core/routes.php
> +$this->create('heartbeat', '/heartbeat')->get();
So what happens when the route is called? Which code path handles it?

2024-05-10 13:57 UTC, provokateurin commented on tests/lib/Route/RouterTest.php
> +	private $router;
```suggestion
	private Router $router;
```

2024-05-10 14:02 UTC, provokateurin commented
TBH I've never seen this warning on my local dev instance, can you tell me how to reproduce it?

2024-05-13 09:32 UTC, come-nc commented on core/routes.php
> +$this->create('heartbeat', '/heartbeat')->get();
https://github.com/nextcloud/server/blob/master/lib/base.php#L1003

2024-05-13 09:35 UTC, come-nc commented
I cannot tell if adding a route like this is the right fix for this. The heartbeat short circuits a lot of things so it cannot be put in a controller.
It is still a supported URL endpoint so maybe it’s fine to add it like that?

2024-05-22 08:42 UTC, cdammanintopix commented
Hello,
Thank you for this fix.
Without it, I had the following issue in my logs:
```
{
  "reqId": "xxxxxxxxxx",
  "level": 1,
  "time": "2024-05-22T08:09:18+00:00",
  "remoteAddr": "xxxxxxxxxx",
  "user": "xxxxxxxxxx",
  "app": "no app in context",
  "method": "GET",
  "url": "/settings/ajax/checksetup",
  "message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
  "userAgent": "xxxxxxxxxx",
  "version": "29.0.0.19",
  "exception": {
    "Exception": "Symfony\\Component\\Routing\\Exception\\RouteNotFoundException",
    "Message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 410,
        "function": "generate",
        "class": "Symfony\\Component\\Routing\\Generator\\UrlGenerator",
        "type": "->",
        "args": [
          "heartbeat",
          [],
          1
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/CachingRouter.php",
        "line": 65,
        "function": "generate",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "heartbeat",
          [],
          false
        ]
      },
      {
        "file": "/var/www/html/lib/private/URLGenerator.php",
        "line": 103,
        "function": "generate",
        "class": "OC\\Route\\CachingRouter",
        "type": "->",
        "args": [
          "heartbeat",
          []
        ]
      },
      {
        "file": "/var/www/html/apps/settings/lib/SetupChecks/SecurityHeaders.php",
        "line": 60,
        "function": "linkToRoute",
        "class": "OC\\URLGenerator",
        "type": "->",
        "args": [
          "heartbeat"
        ]
      },
      {
        "file": "/var/www/html/lib/private/SetupCheck/SetupCheckManager.php",
        "line": 51,
        "function": "run",
        "class": "OCA\\Settings\\SetupChecks\\SecurityHeaders",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/settings/lib/Controller/CheckSetupController.php",
        "line": 179,
        "function": "runAll",
        "class": "OC\\SetupCheck\\SetupCheckManager",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 232,
        "function": "check",
        "class": "OCA\\Settings\\Controller\\CheckSetupController",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 138,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          [
            "OCA\\Settings\\Controller\\CheckSetupController"
          ],
          "check"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          [
            "OCA\\Settings\\Controller\\CheckSetupController"
          ],
          "check"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 338,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Settings\\Controller\\CheckSetupController",
          "check",
          [
            "OC\\AppFramework\\DependencyInjection\\DIContainer"
          ],
          [
            "settings.checksetup.check"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1050,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/settings/ajax/checksetup"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 49,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php",
    "Line": 144,
    "message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
    "exception": [],
    "CustomMessage": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist."
  },
  "id": "xxxxxxxxxx"
}
```
Applying this change fixed the issue.

2024-06-13 22:35 UTC, joshtrichards commented
Added a link to issue #44234 since this is a potential fix for that.

2024-06-18 14:30 UTC, come-nc approved these changes

2024-06-18 15:09 UTC, provokateurin approved these changes

2024-06-18 15:19 UTC, come-nc commented
/backport to stable29

2024-06-18 15:29 UTC, merged

2024-07-10 18:13 UTC, andreas-bulling commented
I've upgraded to 29.0.3 and I still see the error in the log

2024-07-10 19:30 UTC, joshtrichards commented
That's because it's scheduled for the upcoming maintenance release via #45956