feat: add ability to sort by last login
nextcloud/server pull request #45249
Opened 2024-05-10 11:06 UTC by yemkareems

Enhancement for https://github.com/nextcloud-gmbh/customer-feature-requests/issues/425

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-10 18:49 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	public function getUsers(string $search = '', ?int $limit = null, int $offset = 0, string $orderBy = 'lastLogin', string $sort = 'DESC'): DataResponse {
```suggestion
	public function getUsers(string $search = '', ?int $limit = null, int $offset = 0, string $orderBy = 'uid', string $sort = 'ASC'): DataResponse {
```
We should not break the existing sort order

2024-05-10 18:49 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	 * @param string $sort ASC or DESC
```suggestion
	 * @param string $sort asc or desc
```
Would use lowercase like our other API endpoints

2024-05-10 18:49 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	public function getUsersDetails(string $search = '', ?int $limit = null, int $offset = 0, string $orderBy = 'lastLogin', string $sort = 'DESC'): DataResponse {
```suggestion
	public function getUsersDetails(string $search = '', ?int $limit = null, int $offset = 0, string $orderBy = 'uid', string $sort = 'asc'): DataResponse {
```
Same to not break the sort order + lowercase sort param

2024-05-11 17:25 UTC, kesselb commented on lib/private/User/Database.php
> +				$query->expr()->eq('appid', $query->expr()->literal($appId)),
This change breaks searching by email.

1) Open user management
2) Click on the search icon on the upper right next to your profile picture
3) Enter an email address of a user

=> No result on this branch

The left join is there to look up a user by the email address. 
A subselect for lastLogin (similar to the preferences join) should work.

2024-05-11 17:25 UTC, kesselb commented on lib/private/User/Database.php
> +				$query->expr()->eq('appid', $query->expr()->literal($appId)),
```
Index: lib/private/User/Database.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/private/User/Database.php b/lib/private/User/Database.php
--- a/lib/private/User/Database.php	(revision 1b86b6c7f67d1fbc2936a76289e93df2a6e63445)
+++ b/lib/private/User/Database.php	(date 1715447859568)
@@ -275,25 +275,32 @@
 
 		$query = $this->dbConn->getQueryBuilder();
 
-		$appId = 'settings';
-		$configKey = 'email';
-		if($orderBy == 'lastLogin') {
-			$appId = 'login';
-			$configKey = 'lastLogin';
+		if ($orderBy === 'lastLogin') {
+			$lastLoginSubSelect = $this->dbConn->getQueryBuilder();
+			$lastLoginSubSelect->select('configvalue')
+				->from('preferences', 'p2')
+				->where($lastLoginSubSelect->expr()->andX(
+					$lastLoginSubSelect->expr()->eq('p2.userid', 'uid'),
+					$lastLoginSubSelect->expr()->eq('p2.appid', $lastLoginSubSelect->expr()->literal('login')),
+					$lastLoginSubSelect->expr()->eq('p2.configkey', $lastLoginSubSelect->expr()->literal('lastLogin')),
+				));
+			$orderByExpression = $query->createFunction('(' . $lastLoginSubSelect->getSQL() .')');
+		} else {
+			$orderByExpression = $query->func()->lower('displayname');
 		}
 
-		$query->select('uid', 'displayname')
+		$query->select('uid', 'displayname', $orderByExpression)
 			->from($this->table, 'u')
 			->leftJoin('u', 'preferences', 'p', $query->expr()->andX(
 				$query->expr()->eq('userid', 'uid'),
-				$query->expr()->eq('appid', $query->expr()->literal($appId)),
-				$query->expr()->eq('configkey', $query->expr()->literal($configKey)))
+				$query->expr()->eq('appid', $query->expr()->literal('settings')),
+				$query->expr()->eq('configkey', $query->expr()->literal('email')))
 			)
 			// sqlite doesn't like re-using a single named parameter here
 			->where($query->expr()->iLike('uid', $query->createPositionalParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%')))
 			->orWhere($query->expr()->iLike('displayname', $query->createPositionalParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%')))
 			->orWhere($query->expr()->iLike('configvalue', $query->createPositionalParameter('%' . $this->dbConn->escapeLikeParameter($search) . '%')))
-			->orderBy($query->func()->lower('configvalue'), $sort)
+			->orderBy($orderByExpression, $sort)
 			->addOrderBy('uid_lower', 'ASC')
 			->setMaxResults($limit)
 			->setFirstResult($offset);

```

2024-05-11 17:25 UTC, kesselb commented on lib/private/User/Database.php
> +				$query->expr()->eq('appid', $query->expr()->literal($appId)),
If getDisplayNames is called from getUsers (the route the user management xhr request is using) the list is sorted again in: https://github.com/nextcloud/server/blob/4560ddd706d2ced7fb47487cf57095513ae2de70/lib/private/User/Database.php#L428

2024-05-11 17:25 UTC, kesselb commented on lib/private/User/Manager.php
> +		switch ($orderBy.' '.$sort) {
Sorting here only works with $limit and $offset null, for paginated requests the result will be wrong.

2024-05-11 17:25 UTC, kesselb commented on lib/private/User/Manager.php
> +		switch ($orderBy.' '.$sort) {
Sorting here only works with $limit and $offset null, for paginated requests the result will be wrong.

2024-05-28 10:58 UTC, yemkareems commented on lib/private/User/Database.php
> +				$query->expr()->eq('appid', $query->expr()->literal($appId)),
Changed the query to support  email based search and removed the sort in Database.php

2024-06-06 15:46 UTC, Pytal commented on apps/provisioning_api/lib/Controller/UsersController.php
> +										 string $sortOrder = 'desc'
```suggestion
	public function getLastLoggedInUsers(string $search = '',
										 ?int   $limit = null,
										 int    $offset = 0,
										 string $sortOrder = 'desc'
```
Let's keep it simple as we only need sorting by last login

2024-06-26 07:59 UTC, yemkareems commented on lib/public/IUserManager.php
> +	public function search($pattern, $limit = null, $offset = null, $orderBy = 'uid', $sort = 'ASC');
@kesselb reverted these changes and implemented a new endpoint that will not break the LDAP

2024-06-26 08:01 UTC, yemkareems commented on lib/private/User/Database.php
> +				$query->expr()->eq('appid', $query->expr()->literal($appId)),
@kesselb Reverted these changes and implemented a new users/recent endpoint to get the users sorted based on lastLogin asc or desc

2024-06-26 08:05 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +										 string $sortOrder = 'desc'
users/recent will work as it is without any params (default sort is by lastLogin desc) and in case asc/desc is required frontend can pass users/recent?offset=0&limit=25&search=&sortOrder=asc&sortBy=lastLogin params accordingly.

2024-07-02 09:39 UTC, come-nc commented on apps/provisioning_api/lib/Controller/UsersController.php
> +							fn (IUser $user): bool => !$user->isEnabled()
Why is this filtering disabled users?

2024-07-02 09:39 UTC, come-nc commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		}
This whole branch is returning the wrong thing.

2024-07-02 09:39 UTC, come-nc commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		}
Maybe we should not support subadmins here, because perf of sorting all group members by last login may be terrible? @artonge ?

2024-07-02 09:39 UTC, come-nc commented on lib/private/AllConfig.php
> +		$orderByExpression = $query->createFunction('(' . $lastLoginSubSelect->getSQL() .')');
This feels unefficient to me, but maybe I’m wrong, wouldn’t a second join be faster ?
ping @Altahrim

2024-07-02 09:39 UTC, come-nc commented on lib/private/User/Manager.php
> +		}
This part has nothing to do here, it’s about disabled users.
@yemkareems please test your PR more in depth before asking for reviews.

2024-07-02 09:39 UTC, come-nc commented on lib/public/IConfig.php
> +	public function getLastLoggedInUsers($search);
It should also contain the limit, and maybe the offset, to be efficient.

2024-07-02 09:39 UTC, come-nc commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		?int   $limit = null,
limit should not default to null, and maybe not even be nullable, otherwise you just get a list of all users.

2024-07-03 10:56 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		}
@come-nc I had a call with @artonge on this and it was decided we will support last login sorting for admin alone and not for subadmin and groups

2024-07-03 10:58 UTC, yemkareems commented on lib/private/AllConfig.php
> +		$orderByExpression = $query->createFunction('(' . $lastLoginSubSelect->getSQL() .')');
@come-nc, @Altahrim Intially this was written in getDisplayNames and that broke the search by email. I ll refactor this query only to sort by lastLogin configvalue desc

2024-07-03 11:00 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		?int   $limit = null,
Will default the limit to 25

2024-07-04 07:14 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +							fn (IUser $user): bool => !$user->isEnabled()
@come-nc removed the references to old disabled users code

2024-07-04 07:15 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		}
Sub admin and groups are not supported. Hence removed this

2024-07-04 07:17 UTC, yemkareems commented on lib/private/User/Manager.php
> +		}
@come-nc Sorry about the old code leftover here. Removed the old disabled users code and added the limit and offset to the query and cleaned it up here

2024-07-04 07:17 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		?int   $limit = null,
Added offset and limit to the query

2024-07-04 07:18 UTC, yemkareems commented on lib/public/IConfig.php
> +	public function getLastLoggedInUsers($search);
Added offset and limit to the query

2024-07-04 07:19 UTC, yemkareems commented on lib/private/AllConfig.php
> +		$orderByExpression = $query->createFunction('(' . $lastLoginSubSelect->getSQL() .')');
Refactored this query to similar to getDisplayNames query to make it better

2024-07-04 08:22 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +		?int   $limit = null,
Limit is defaulted to null and if no limit is given all users are fetched ordered by last login desc and if limit, offset and search are given the result set is fetched accordingly @come-nc @Pytal

2024-07-04 08:42 UTC, come-nc requested changes

2024-07-04 08:42 UTC, come-nc commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	 * @NoAdminRequired
```suggestion
```
Since you removed subadmin handling, this should be for admins only now.

2024-07-04 09:13 UTC, yemkareems commented on apps/provisioning_api/lib/Controller/UsersController.php
> +	 * @NoAdminRequired
Removed the doc block and if condition

2024-07-04 09:14 UTC, yemkareems commented on lib/private/AllConfig.php
> +	 * Gets the list of users based on their lastLogin info asc or desc
Changed comment

2024-07-04 09:15 UTC, yemkareems commented on lib/private/AllConfig.php
> +	}
negative limit and offset throwing up is handled in controller. So removed the same here

2024-07-04 09:15 UTC, yemkareems commented on lib/private/User/Manager.php
> +
Removed this method and used the config directly in controller

2024-07-04 09:52 UTC, come-nc requested changes

2024-07-04 09:52 UTC, come-nc commented on lib/private/AllConfig.php
> +			->orWhere($query->expr()->iLike('configvalue', $query->createPositionalParameter('%' . $this->connection->escapeLikeParameter($search) . '%')))
This only makes sense to search in email, but this will not work because you join on configkey lastLogin.
So either you have to join twice with `preferences` if you want search to work in email address, or you should remove this line and search will not search in email address.

2024-07-04 09:52 UTC, come-nc commented on lib/private/AllConfig.php
> +		$displayNames = [];
Why is this var called $displayNames? It contains uids.
```suggestion
		$uids = [];
```

2024-07-04 09:52 UTC, come-nc commented on lib/private/AllConfig.php
> +		while ($row = $result->fetch()) {
```suggestion
		while (($row = $result->fetch()) !== false) {
```
You have to check against false with a strong check to not stop on a uid being `'0'` which is valid.

2024-07-04 09:52 UTC, come-nc commented on lib/private/AllConfig.php
> +		$query->select('uid', 'displayname')
```suggestion
		$query->selectDistinct('uid')
```
You do not use displayname so no need to select it.
And if you use selectDistinct you can avoid using uid as key in the foreach loop below and can return a list which is better than an associative array.
You can even return $result->fetchAll in column mode.

2024-07-04 09:52 UTC, come-nc commented on lib/private/AllConfig.php
> +		$displayNames = [];
```suggestion
		$result = $query->executeQuery();
		$uids = $result->fetchAll(\PDO::FETCH_COLUMN);
		$result->closeCursor();
		return $uids;
```
Like that, if you only select uid with distinct you can use this simple code block instead of a while.

2024-07-04 09:52 UTC, come-nc commented on lib/public/IConfig.php
> +	 * @return array of user IDs
```suggestion
	 * @return list<string> list of user IDs
```

2024-07-04 12:18 UTC, yemkareems commented on lib/private/AllConfig.php
> +			->orWhere($query->expr()->iLike('configvalue', $query->createPositionalParameter('%' . $this->connection->escapeLikeParameter($search) . '%')))
Will add a extra join to have the search with email intact

2024-07-04 12:27 UTC, yemkareems commented on lib/private/AllConfig.php
> +		$displayNames = [];
changed it to uids

2024-07-04 12:27 UTC, yemkareems commented on lib/private/AllConfig.php
> +		$query->select('uid', 'displayname')
used selectDistinct and fetchAll

2024-07-04 13:05 UTC, come-nc commented on lib/private/AllConfig.php
> +	 * @return array of user IDs
```suggestion
	 * @return list<string> list of user IDs
```
To please psalm

2024-07-04 13:16 UTC, come-nc approved these changes

2024-07-04 15:03 UTC, artonge approved these changes

2024-07-04 15:03 UTC, artonge commented
Rebased

2024-07-05 00:50 UTC, Pytal commented on lib/public/IConfig.php
> +	 * Gets the list of users based on their lastLogin info asc or desc
```suggestion
	 * Gets the list of users sorted by lastLogin, from most recent to least recent
```
Since we can't choose asc or desc, copied from the other method

2024-07-05 00:51 UTC, Pytal approved these changes

2024-07-05 08:46 UTC, artonge commented
You probably need to fix the openapi check

2024-07-05 08:54 UTC, kesselb requested changes, later dismissed
Why IConfig/AllConfig? :confused:

2024-07-05 10:22 UTC, yemkareems commented
> Why IConfig/AllConfig? 😕

It is mostly in the lines of the getDisabledUsers which calls IUserManager/Manager which internally calls IConfig/AllConfig. The Manager was not required because we just wanted the list of user and the LazyUser in the Manager was not required. So i did IConfig/AllConfig

2024-07-05 10:58 UTC, kesselb commented
`IConfig` is the public api to create/read/update/delete configuration values, either from configuration file, app config, or user preferences. 

I assume `getDisabledUsers` uses `getUsersForUserValue` because that's the way to retrieve user preferences. 

`getLastLoggedInUsers` does not belong in IConfig and should go somewhere else. The UserManager looks like a good place, but please check with Louis, and we are already using the QueryBuilder there, regrettably not via DI.

2024-07-08 07:59 UTC, come-nc commented
> `IConfig` is the public api to create/read/update/delete configuration values, either from configuration file, app config, or user preferences.
> 
> I assume `getDisabledUsers` uses `getUsersForUserValue` because that's the way to retrieve user preferences.
> 
> `getLastLoggedInUsers` does not belong in IConfig and should go somewhere else. The UserManager looks like a good place, but please check with Louis, and we are already using the QueryBuilder there, regrettably not via DI.

I disagree, it’s reading in the configuration table so it’s better situated in IConfig than IUserManager, no?

2024-07-08 09:16 UTC, artonge commented
I agree with @kesselb, this seems way too specific to be located in `IConfig`.

2024-07-08 09:21 UTC, yemkareems commented
> I agree with @kesselb, this seems way too specific to be located in `IConfig`.

Sure @kesselb , @artonge i ll move this to UserManager/Manager as suggested

2024-07-08 12:29 UTC, artonge approved these changes

2024-07-09 07:45 UTC, merged

2024-07-18 09:51 UTC, nickvergessen commented on lib/public/IUserManager.php
> +	public function getLastLoggedInUsers(?int $limit = null, int $offset = 0, string $search = ''): array;
Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1