feat(log): Allow to combine log.conditions to only log (app&user)
nextcloud/server pull request #45277
Opened 2024-05-13 08:27 UTC by nickvergessen

* Resolves: # 

## Summary

Improve log conditioning to allow only debug logging entries for user & app, dedicated log level for each condition and "log message contains" additionally.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-13 10:20 UTC, come-nc commented on lib/private/Log.php
> +					if (!isset($option['apps']) && !isset($option['loglevel']) && !isset($option['message'])) {
I do not understand this inside `if`

2024-05-13 10:21 UTC, come-nc commented on config/config.sample.php
> +	'matches' => [
```suggestion
	'and' => [
```
Or is that too nerdy?

2024-05-13 10:21 UTC, come-nc commented on config/config.sample.php
> +	'matches' => [
```suggestion
	'allof' => [
```
maybe?

2024-05-13 17:00 UTC, nickvergessen commented on config/config.sample.php
> +	'matches' => [
I had that at some point all ready, but my mind couldn't settle if it's allof or anyof and then I wondered if it's more understandable for people

2024-05-14 10:22 UTC, miaulalala requested changes

2024-05-14 10:22 UTC, miaulalala commented on lib/private/Log.php
>  		}
Extract this into it's own method:

```suggestion:

	/**
	 * @param array $logCondition
	 * @param string $userId
	 * @return bool
	 * @throws \Psr\Container\ContainerExceptionInterface
	 * @throws \Psr\Container\NotFoundExceptionInterface
	 */
	private function processLogConditions(array $logCondition): ?bool {
		/**
		 * check for a special log condition - this enables an increased log on
		 * a per request/user base
		 * If the log condition is null, we need to check the for user, otherwise we skip
		 */
		if($this->logConditionSatisfied !== null) {
			return $this->logConditionSatisfied;
		}
		// check for secret token in the request
		if (isset($logCondition['shared_secret']) && $this->checkLogSecret($logCondition['shared_secret'])) {
			return true;
		}

		// check for user
		if (isset($logCondition['users'])) {
			$user = \OCP\Server::get(IUserSession::class)->getUser();

			if ($user === null) {
				// User is not known for this request yet
				return null;
			}

			if (in_array($user->getUID(), $logCondition['users'], true)) {
				// if the user matches set the log condition to satisfied
				return true;
			}
		}
		return null;
	}
```
I hope I understood the point of `null` for the `$this->logConditionSatisfied` correctly

2024-05-14 10:22 UTC, miaulalala commented on lib/private/Log.php
> +	}
Early return

```suggestion
		if ($request->getMethod() === 'PUT' &&
			!str_contains($request->getHeader('Content-Type'), 'application/x-www-form-urlencoded') &&
			!str_contains($request->getHeader('Content-Type'), 'application/json')) {
			return hash_equals($conditionSecret, '');
		}

		// if token is found in the request change set the log condition to satisfied
		return hash_equals($conditionSecret, $request->getParam('log_secret', ''));
	}
```

2024-05-14 10:22 UTC, miaulalala commented on lib/private/Log.php
> +			}
Run through the function recursively maybe?
```suggestion
				$loglevel = $this->getLogLevel($option, $option['message'] ?? $message);
			}
```

2024-05-16 17:31 UTC, nickvergessen commented on lib/private/Log.php
> +			}
I didn't understand this one.
Fixed all the other comments

2024-05-16 18:16 UTC, miaulalala approved these changes

2024-07-30 11:51 UTC, AndyScherzinger approved these changes

2024-07-30 12:25 UTC, come-nc approved these changes

2024-07-30 13:05 UTC, merged