feat: Add back searching in disabled user list
nextcloud/server pull request #45370
Opened 2024-05-16 14:18 UTC by come-nc

* Resolves: #44936 

## Summary

When disabled users where moved to their own endpoint we overlooked search, so adding it back.
The search is done case-insensitive in uid and display name.

## TODO

- [ ] Decide if we should also search in email field, and implement it
- [ ] Decide if the BC break is ok or should be avoided with a new interface

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-16 14:59 UTC, come-nc commented
> ## TODO
> * [x]  Decide if we should also search in email field, and implement it

Implemented.

> * [ ]  Decide if the BC break is ok or should be avoided with a new interface

I think this is fine, because a class implementing the interface for 30 also implements the one for 28.0.0, as it’s only a new parameter.
So, as the breaking is minimal and it’s easy for concerned apps (and that’s only apps implementing a user backend with special disabled user treatment, so only user_ldap to my knowlegde) to support all Nextcloud versions.

2024-05-16 15:00 UTC, come-nc commented
/compile /

2024-05-16 15:07 UTC, provokateurin reviewed
I would prefer separate methods for searching quite a lot over changing the behavior of the existing methods. Would that be possible or is it too much work or impractical?

2024-05-16 15:29 UTC, provokateurin commented
Ok in light of the discussion in https://github.com/nextcloud/server/issues/44936 it makes sense to extend the existing endpoint instead of creating a new one

2024-05-16 16:08 UTC, artonge approved these changes
So BC is not a real BC?

2024-05-16 17:00 UTC, Pytal requested changes

2024-05-16 17:00 UTC, Pytal commented on lib/public/User/Backend/IProvideEnabledStateBackend.php
> +	 * @since 30.0.0 $search parameter added
```suggestion
```
Same here

2024-05-17 08:39 UTC, Altahrim approved these changes

2024-05-21 10:12 UTC, come-nc commented on lib/public/User/Backend/IProvideEnabledStateBackend.php
> +	 * @since 30.0.0 $search parameter added
I planned on changing it in the backport but maybe already in this one we can use `@since 28.0.6 $search parameter added` ?

2024-05-21 16:13 UTC, Pytal commented on lib/public/User/Backend/IProvideEnabledStateBackend.php
> +	 * @since 30.0.0 $search parameter added
Good idea, let's go with that then 🚀

2024-05-21 16:16 UTC, provokateurin commented on lib/public/User/Backend/IProvideEnabledStateBackend.php
> +	 * @since 30.0.0 $search parameter added
IMO in the main branch it should be 30.0.0 and then for 29 and 28 it should be 28.x.x and 29.x.x respectively. It should not be 28.0.0/29.0.0 as those versions don't actually have the parameter.

2024-05-21 16:39 UTC, Pytal approved these changes

2024-05-23 07:10 UTC, come-nc commented
/compile /

2024-05-23 12:51 UTC, merged

2024-05-23 12:52 UTC, come-nc commented
/backport to stable28

2024-07-18 09:49 UTC, nickvergessen commented
Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id2