feat(TaskProcessingApi): Add endpoint for getting the next task
nextcloud/server pull request #45391
Opened 2024-05-17 09:56 UTC by provokateurin

## Summary

The ExApps need a way to get the next task.
@marcelklehr I think there is a bug as the tasks are not marked as running when the getNextScheduledTask method of the service is called (or maybe it was also intentional and the endpoint should do it manually).

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-17 11:01 UTC, marcelklehr commented
Ah, I missed this, yes.

> @marcelklehr I think there is a bug as the tasks are not marked as running when the getNextScheduledTask method of the service is called (or maybe it was also intentional and the endpoint should do it manually).

Yeah, let's do this manually directly in the endpoint

2024-06-05 06:46 UTC, bigcat88 commented
We need endpoint for getting nextTask by specifying multiple task_types. 
One provider can process multiple task types and we do not want to spam NC with one nextTask request for each task_type.

Or just to change `string $taskTypeId` to array of strings.

2024-06-05 08:40 UTC, julien-nc requested changes
* I agree with @marcelklehr that it makes more sense to change the task status to "running" in the controller method.
The `Manager::getNextScheduledTask` method might be used in some context where we don't want to change to task status.

* Also, how about having a `setTaskRunning` parameter (with `true` as default value) in `TaskProcessingApiController::getNextScheduledTask` ? Just in case one wants to get the next scheduled task without actually processing it.

* About requesting multiple task types in `getNextScheduledTask`, much needed indeed. @marcelklehr Would you go with another endpoint or change the current one?

2024-06-05 08:44 UTC, provokateurin commented
I don't see a reason why you would ever need to know the next task without also running it at the same time, but I can change it if you really want :woman_shrugging:

2024-06-05 08:47 UTC, marcelklehr commented
> I don't see a reason why you would ever need to know the next task without also running it at the same time

The synchronous background job will re-schedule itself based on the fact whether there is another job waiting to be executed.

2024-06-05 08:47 UTC, marcelklehr commented
> Would you go with another endpoint or change the current one?

We can add this to the current endpoint.

2024-06-07 06:42 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +					'name' => 'llm2:tinyllama-1.1b-chat-v1.0.Q4_0:summary',
The only remaining part that needs to be implemented. Waiting on an answer from @marcelklehr

2024-06-07 06:57 UTC, nickvergessen requested changes

2024-06-07 06:57 UTC, nickvergessen commented on core/Controller/TaskProcessingApiController.php
> +	public function getNextScheduledTask(array $taskTypeIds): DataResponse {
this method is callable for any user and it will freely give out any scheduled tasks of other users.

2024-06-07 09:48 UTC, nickvergessen commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +		if ($this->hasAnnotationOrAttribute($reflectionMethod, 'ExAppRequired', ExAppRequired::class) && (!$this->userSession instanceof Session || $this->userSession->getSession()->get('app_api') !== true
Could also not introduce the annotation (and then simply directly only check for the attribute)

2024-06-10 19:33 UTC, bigcat88 commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +		if ($this->hasAnnotationOrAttribute($reflectionMethod, 'ExAppRequired', ExAppRequired::class) && (!$this->userSession instanceof Session || $this->userSession->getSession()->get('app_api') !== true
Suggestion:

1. Rename `#[ExAppRequired]` to `#[ExAppRoute]`
2. Add check for `ExAppRoute` in `if (!$this->isLoggedIn) {` at line 134

This will ensure that ExApp can call non public endpoints, and this still can be used with/without `PublicPage` and not change the logic of other attributes(like SubAdminRequired).

2024-06-17 09:39 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
>  			// Check if the current user can access the task
Nope, this is how Marcel implemented the authorization check. I didn't change anything there.

2024-06-17 13:30 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
>  			// Check if the current user can access the task
Comment can be removed as only ExApps can call this endpoint, but it was also insecure because there was no actual check. I thought this was done automatically by getting the task, but apparently this was meant as a TODO and not as an explanation.

2024-06-17 13:41 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
>  			// Check if the current user can access the task
It was meant as an explanation, when the line still read `getUserTask` ;)

2024-06-17 14:06 UTC, bigcat88 commented
ExApp needs to call these APIs to process tasks:

`getNextScheduledTask`
`getFileContents`
`setProgress`
`setResult`

more precisely, there should be two versions of **getFileContents** - one for the UI with `userId` and other one for ExApp with `[ExAppRequired]` without checking for `userId`

cause only having those 4 endpoint ExApp can have no "system" flag to process tasks from what I see

2024-06-19 10:34 UTC, nickvergessen commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +			if ((!$this->userSession instanceof Session || $this->userSession->getSession()->get('app_api') !== true)) {
```suggestion
			if (!$this->userSession instanceof Session || $this->userSession->getSession()->get('app_api') !== true) {
```

2024-06-19 10:36 UTC, nickvergessen commented on lib/public/TaskProcessing/IManager.php
> +	public function getPreferredProvider(string $taskType);
But you can't specify what you prefer?
It returns the first one matching the taskType?

```suggestion
	public function getFirstProviderForTaskType(string $taskType);
```

2024-06-19 10:36 UTC, nickvergessen approved these changes
The security middleware looks good now

2024-06-19 10:40 UTC, marcelklehr commented on lib/public/TaskProcessing/IManager.php
> +	public function getPreferredProvider(string $taskType);
It's a stand-in implementation until we implement the settings UI for the preferred providers

2024-06-24 10:47 UTC, marcelklehr approved these changes

2024-06-28 14:57 UTC, bigcat88 commented
I didn't change the logic inside "getNextScheduledTask" - but it doesn't seem right to me for these reasons:

1. `$task->setStatus(Task::STATUS_RUNNING);` won't write anything to the database, right?
2. Reading and writing to the database must be atomic within “getNextScheduledTask” (so that two requests for processing a task in parallel do not receive the same task)
3. I didn’t understand the logic at all why `$providerIds` is there as input and what it should do, that’s why I didn’t change the entry to atomic inside “getNextScheduledTask”

2024-06-28 15:54 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +			$task->setStatus(Task::STATUS_RUNNING);
Ah, yes, good point @bigcat88, this needs to be persisted

2024-06-28 16:16 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +	 *
```suggestion
     * 
	 * It could be that a provider is looking for new tasks but the task type of the next scheduled task is actually configured to be run with a different provider
```

2024-06-28 16:21 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +			if (!in_array($provider->getId(), $providerIds, true)) {
Imagine the task queue is as follows


````
1. free_prompt
2. summarize
````

and the configuration for the preferred providers says

```
free_prompt: context_chat
summarize: llm2-llama-3
```

Then llm2 calls this endpoint with `getNextScheduledTask([free_prompt, summarize], [llm2-llama-3])`

What will happen is:

 - getNextScheduledTask will return the free_prompt task
 - But that is configured to be run by context_chat
 - So, the endpoint returns NotFoundResponse, even though there is the summarize task waiting that fulfills the requirements of the request

2024-06-28 19:19 UTC, bigcat88 commented on core/Controller/TaskProcessingApiController.php
> +			if (!in_array($provider->getId(), $providerIds, true)) {
then we all this logic should do on the database level with query with automatic changing of `status` to `running` upon selecting task.

will try to do that...

2024-06-29 11:02 UTC, bigcat88 approved these changes

2024-07-01 10:59 UTC, AndyScherzinger approved these changes

2024-07-01 11:11 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +		try {
```suggestion
		try {
				// restrict $providerIds to providers that are configured as preferred for the passed task types
				$providerIds = array_values(array_intersect(array_unique(array_map(fn($taskTypeId) => $this->taskProcessingManager->getPreferredProvider($taskTypeId)->getId(), $taskTypeIds)), $providerIds));
				// restrict $taskTypeIds to task types that can actually be run by one of the now restricted providers
				$taskTypeIds = array_values(array_filter($taskTypeIds, fn($taskTypeId) => in_array($this->taskProcessingManager->getPreferredProvider($taskTypeId)->getId(), $providerIds, true));
				if (count($providerIds) === 0 || count($taskTypeIds) === 0) {
						return new DataResponse(null, Http::STATUS_NO_CONTENT);
				}
```

This will short circuit in cases where the passed providers are not configured as preferred for some of the passed task types.

## Example 1

```
configuration:
  summarize: llm2-llama3
  free_prompt: context_chat
```

Request:
```
GET /taskprocessing/tasks_provider/next

providerIds:
  - llm2-llama3
  - llm2-llama2
 taskTypeIds:
  - free_prompt
  - summarize
```

The endpoint will reduce the inputs to


```
$providerIds = [llm2-llama3]
$taskTypeIds = [summarize]
```

This will avoid unnecessary loops due to querying for free_prompt tasks.

## Example 2

```
configuration:
  summarize: llm2-llama3
  free_prompt:  llm2-llama3
```

Request:
```
GET /taskprocessing/tasks_provider/next

providerIds:
  - context_chat
 taskTypeIds:
  - free_prompt
```

The endpoint will reduce the inputs to

```
$providerIds = []
$taskTypeIds = []
```

This will avoid making a db request alltogether.

2024-07-01 12:48 UTC, marcelklehr approved these changes

2024-07-01 12:54 UTC, nickvergessen commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
This is now in "openapi-administration" while it's not accessible for administrators.
Should add `#[OpenAPI(scope: 'app_api')` or something a like?

2024-07-01 13:07 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
Mmh, @julien-nc are you using this endpoint in assistant?

2024-07-01 13:27 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
I think fixing this in openapi-extractor is better, but a separate scope is also useful in addition. This can be done indepdently in openapi-extractor though.

2024-07-01 13:28 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
@marcelklehr this endpoint can't not be used by assistant due to ExAppRequired, but the getFileContents endpoint can be used instead.

2024-07-01 14:17 UTC, marcelklehr commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
Ah, yes, I was confused.

2024-07-01 14:21 UTC, provokateurin commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
@nickvergessen I'll add a new scope to the OpenAPI attribute and then automatically move all endpoints to that scope that have the ExAppRequired attribute, just like we do with the administration scope.

2024-07-01 14:27 UTC, nickvergessen commented on core/Controller/TaskProcessingApiController.php
> +	#[ExAppRequired]
Makes sense, thanks

2024-07-01 14:28 UTC, provokateurin commented
Yeah I saw it, will fix all of it

2024-07-01 17:10 UTC, julien-nc approved these changes

2024-07-01 17:10 UTC, merged

2024-07-18 09:57 UTC, nickvergessen commented on lib/public/TaskProcessing/IManager.php
> +	public function lockTask(Task $task): bool;
@provokateurin Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(all changes in lib/public/)

2024-07-18 10:18 UTC, provokateurin commented on lib/public/TaskProcessing/IManager.php
> +	public function lockTask(Task $task): bool;
I think for this particular change it makes more sense to include it in https://github.com/nextcloud/server/pull/45094 because the whole documentation for that is missing in the first place.
I'll document the new attribute though.