feat: Add support for webhook listeners
nextcloud/server pull request #45475
Opened 2024-05-23 09:23 UTC by come-nc

## Summary

Add support for registering webhooks as listeners of events.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-05-23 13:55 UTC, ChristophWurst reviewed
Code looks good! How will this be used? Can we assume that apps know their webhook listeners when the app is just *registered* and the system isn't fully booted yet?

2024-05-23 15:28 UTC, come-nc commented
> Code looks good! How will this be used?

Plan is to use that for integration of an external workflow engine, but architecture is not final yet.
One problem is we’d prefer if the webhook gets called only on certains conditions, but then we end up with `apps/workflowengine` complexity.

> Can we assume that apps know their webhook listeners when the app is just _registered_ and the system isn't fully booted yet?

Hum, what is not accessible at that point?
If I want to have an app which search in its database and user settings to know which webhooks to register, will that work?

2024-05-23 15:58 UTC, ChristophWurst commented
> > Can we assume that apps know their webhook listeners when the app is just _registered_ and the system isn't fully booted yet?
> 
> Hum, what is not accessible at that point? If I want to have an app which search in its database and user settings to know which webhooks to register, will that work?

That works. Anything that is provided by other apps might be missing. Say information from a user backend.

If you always want to wire a specific event to  webhook listeners it's fine. But the lack of this information could be critical when you need to conditionally register webhooks. I haven't yet understood the full picture of the new automations so this might not be necessary.

https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html#nextcloud-20-and-later for my original ideas and thoughts about the two step register/boot process.

2024-05-28 10:05 UTC, come-nc commented
Webhooks are moved to an application with registrations in DB instead. They will also need to support filtering of events triggerring the webhook.

- [ ] Skeleton app
- [ ] API to register webhooks
- [ ] occ command to list them
- [ ] Actually call the webhooks, through background jobs
- [ ] Serialize the event to the webhook
- [ ] Add a filtering system

2024-05-28 14:16 UTC, come-nc commented
- [ ] Store app id from appapi header if available

2024-06-04 12:37 UTC, marcelklehr commented on apps/webhooks/lib/ResponseDefinitions.php
> + *     eventFilter?: array<mixed>,
Is this still failing?

2024-06-04 12:40 UTC, come-nc commented
Follow-up:

- [ ] Extract user filter from eventFilter so that the listener is not even registered depending on logged in user
- [ ] Same for group membership

2024-06-04 12:49 UTC, come-nc commented on apps/webhooks/lib/ResponseDefinitions.php
> + *     eventFilter?: array<mixed>,
Changed it to `array<string,mixed>`. It’s not exactly right because you can have an array of filters with integer keys I think, but it’s close enough and psalm type system does not allow us to define nested arrays correctly.

2024-06-04 12:49 UTC, marcelklehr commented on apps/webhooks/lib/ResponseDefinitions.php
> + *     eventFilter?: array<string,mixed>,
It might be possible to define a recursive type, to avoid the "mixed" here, but I'm not sure

2024-06-04 13:28 UTC, come-nc commented on apps/webhooks/lib/ResponseDefinitions.php
> + *     eventFilter?: array<string,mixed>,
https://github.com/vimeo/psalm/issues/5739 nope

2024-06-05 11:44 UTC, julien-nc requested changes
Works great! A few minor comments and questions.

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Controller/WebhooksController.php
> +		?array $authData,
Are we sure that authData will always be an array? Even with other future auth methods?

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Db/WebhookListener.php
> +	public function setAuthDataClear(?array $data): void {
Nitpicking: I think it's enough to call those methods `getAuthData` and `setAuthData`. I feel like current names are ambiguous. Or maybe `getDecryptedAuthData` and `setEncryptedAuthData`. Not a big deal anyway.

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Db/WebhookListenerMapper.php
> +	public function addWebhookListener(
Missing some method return types and PhpDoc blocks (useful for `@throws` IMO).

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Listener/WebhooksEventListener.php
> +			/* Event is not serializable, we fallback to reflection to still send something */
Noice!

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Migration/Version1000Date20240527153425.php
> +			$table->addColumn('id', Types::INTEGER, [
```suggestion
			$table->addColumn('id', Types::BIGINT, [
```

2024-06-05 11:44 UTC, julien-nc commented on apps/webhooks/lib/Service/PHPMongoQuery.php
> +		if(empty($documents) || empty($query)) {
php-cs will probably complain about the syntax. Should we avoid checking this file or fix the code style?

2024-06-05 12:29 UTC, nickvergessen commented on apps/webhooks/lib/AppInfo/Application.php
> +				$eventName,
Should we block certain event names and allow apps to defined blocked events?
E.g. login events should not send the users password to other servers.

2024-06-05 12:29 UTC, nickvergessen commented on apps/webhooks/lib/Migration/Version1000Date20240527153425.php
> +				'length' => 256,
In talk we used 4k length for the url. Not sure 256 might be enough in all cases

2024-06-06 08:41 UTC, come-nc commented on apps/webhooks/appinfo/info.xml
> +		<command>OCA\Webhooks\Command\Index</command>
`ListCommand`, like `user:list`?

2024-06-06 08:44 UTC, come-nc commented on apps/webhooks/lib/Db/WebhookListener.php
> +	public function setAuthDataClear(?array $data): void {
It’s not possible, `getAuthData` and `setAuthData` are the magical setter/getter for the DB column. (And they are used by the mapper so we cannot make them encrypt/decrypt).
If we want to use those names I need to rename the DB column to `auth_data_encrypted` or something. Do you want me to do that? I’m fine with both approach.

2024-06-06 08:51 UTC, julien-nc commented on apps/webhooks/appinfo/info.xml
> +		<command>OCA\Webhooks\Command\Index</command>
Yes, `ListCommand` is more explicit, I think `ListWebhooks` matches more with `webhooks:list`.

2024-06-06 08:53 UTC, come-nc commented on apps/webhooks/lib/Service/PHPMongoQuery.php
> +		if(empty($documents) || empty($query)) {
https://github.com/nextcloud/server/actions/runs/9367363495/job/25786877013?pr=45475
`php-cs` is happy, I ran `cs:fix` on the file already.

2024-06-06 08:55 UTC, come-nc commented on apps/webhooks/lib/BackgroundJobs/WebhookCall.php
> +			if ($statusCode >= 200 && $statusCode < 300) {
Yeah I messed it up, inverting the branch content, nice catch.

2024-06-06 08:58 UTC, come-nc commented on apps/webhooks/lib/Controller/WebhooksController.php
> +		} catch (Exception $e) {
Was supposed to be `\Exception` like the other methods, fixing it.

2024-06-06 09:03 UTC, julien-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +				$eventName,
Nice catch, yes, all authentication-related events should be "blacklisted". It's difficult to list all those dispatched by community apps but those should be enough:
* all auth events from core
* user_ldap
* user_saml
* user_oidc

@nickvergessen Do you think of any other kind of event that should be avoided?

2024-06-06 09:05 UTC, julien-nc commented on apps/webhooks/lib/Db/WebhookListener.php
> +	public function setAuthDataClear(?array $data): void {
Oh right, no let's not rename the DB columns. Maybe we can find more explicit names. Maybe current names are fine... :grin:

2024-06-06 09:06 UTC, provokateurin commented
I'm unsubscribing from this PR for now, please ping me if you need a review of the (Open)API.

2024-06-06 09:18 UTC, come-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
Yes, see https://github.com/nextcloud/server/blob/9fc8959d9d236667c4761f11d7e935c22a374f0b/apps/webhooks/lib/Db/WebhookListenerMapper.php#L134
For the cache to make sense it needs to be in session, should I add that in the mapper or in the `Application` class?

2024-06-06 09:24 UTC, come-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +				$eventName,
That’s a good point.
Then I think we should remove the fallback and only allow `\JsonSerializable` implementors to be listened to.
Then an application can decide to not implement it to disallow webhooks or to only serialize some properties (ie not the password for PostLoginEvent). @julien-nc @nickvergessen what do you think?

2024-06-06 09:27 UTC, nickvergessen commented on apps/webhooks/lib/AppInfo/Application.php
> +				$eventName,
> or to only serialize some properties (ie not the password for PostLoginEvent).

Sounds good.

2024-06-06 09:29 UTC, nickvergessen commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
> For the cache to make sense it needs to be in session, should I add that in the mapper or in the Application class?

I prefer to keep the mapper plain, to know when a SQL query is fired.
If you use this in more places in the future you could move it to a service file.
So for now I would put it into Application

2024-06-06 14:26 UTC, come-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
See https://github.com/nextcloud/server/pull/45475/commits/57c5ddbd207fa8b7565f49a6e1ca2fa85814603d , but if this caching was done in the mapper instead, I could reset the cache whenever a webhook is inserted or updated, what do you think?

2024-06-06 14:39 UTC, nickvergessen commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
so time for a service? :P 
Or the mapper is the service.
Could also have a private uncached function there which is called by the "public" cached function.

2024-06-06 14:52 UTC, come-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
I prefer if the mapper is the service, splitting this in two classes sounds overkill to me, + it weakens the idea that all db access should go through these functions. (what I mean is that if the caching is in the service it might miss calls directly on the mapper).

The Application class cannot use DI, so moving the cache to the mapper. Incomming.

2024-06-06 15:01 UTC, come-nc commented on apps/webhooks/lib/AppInfo/Application.php
> +		$configuredEvents = $mapper->getAllConfiguredEvents();
https://github.com/nextcloud/server/pull/45475/commits/0cbb36e232ddb91950f226cd2ea35ccf46b3c7c7

2024-06-07 09:59 UTC, julien-nc approved these changes

2024-06-07 11:39 UTC, nickvergessen commented on apps/webhooks/lib/BackgroundJobs/WebhookCall.php
> +		$options = [];
might make sense to add verify with our certificate manager as well:
```
'verify' => $this->certificateManager->getAbsoluteBundlePath(),
```

Just learned about this today, but it then allows to easily also set up requests against self-signed servers by using the `occ security:certificate:import` command

2024-06-07 11:42 UTC, nickvergessen commented on apps/webhooks/lib/Db/WebhookListenerMapper.php
> +		?array $authData,
Should we start adding:
```suggestion
		#[\SensitiveParameter]
		?array $authData,
```
for new things at least?

2024-06-10 06:47 UTC, marcelklehr commented on apps/webhooks/lib/Migration/Version1000Date20240527153425.php
> +				'length' => 4096,
$ php occ app:enable webhooks
Column "oc_webhook_listeners"."uri" is type String, but exceeding the 4.000 length limit.

2024-06-10 07:26 UTC, marcelklehr commented on apps/webhooks/lib/Controller/WebhooksController.php
> +				AuthMethod::from($authMethod ?? AuthMethod::None->value),
This causes a HTTP 500 if $authMethod is not recognized

2024-06-10 09:48 UTC, marcelklehr commented
It seems the node events that you added the interface to are not actually emitted at the moment. I can only see the old `\\OCP\\Files::preWrite` ones

2024-06-10 12:10 UTC, come-nc commented
> It seems the node events that you added the interface to are not actually emitted at the moment. I can only see the old `\\OCP\\Files::preWrite` ones

They are, I tested with a NodeWrittenEvent and the webhook was called. Please detail what scenario you tested and which event firing was missing and I’ll look into it.

2024-06-10 12:23 UTC, come-nc commented
- [ ] webhooks app id is already used on appstore, we should rename.

2024-06-10 12:32 UTC, marcelklehr commented on apps/webhooks/lib/BackgroundJobs/WebhookCall.php
> +					$options['headers'] = array_merge($options['headers'], $authHeaders);
"Exception": "TypeError",
    "Message": "array_merge(): Argument #1 must be of type array, null given",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/marcel/code/server/apps/webhooks/lib/BackgroundJobs/WebhookCall.php",
        "line": 42,
        "function": "array_merge"
      },

2024-06-11 07:49 UTC, marcelklehr requested changes

2024-06-11 07:50 UTC, come-nc commented on apps/webhook_listeners/lib/Controller/WebhooksController.php
> +				AuthMethod::from($authMethod ?? AuthMethod::None->value),
I want the valueerror, I just need to catch it and turn in into the proper OCS api response.

2024-06-11 08:54 UTC, marcelklehr commented
> They are, I tested with a NodeWrittenEvent and the webhook was called. Please detail what scenario you tested and which event firing was missing and I’ll look into it.

Nevermind, as discussed, it was the leading backslash that caused this

2024-06-11 13:07 UTC, marcelklehr approved these changes

2024-06-11 14:31 UTC, merged

2024-07-18 10:07 UTC, nickvergessen commented on lib/public/EventDispatcher/IWebhookCompatibleEvent.php
> +interface IWebhookCompatibleEvent {
@come-nc Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(all changes in lib/public/)