feature: Improved Recurrence Invitations Messages
nextcloud/server pull request #45547
Opened 2024-05-28 11:27 UTC by SebastianKrupinski

* Resolves: #38686

## Summary
Improved Recurrence Invitations Messages

2024-06-24 11:50 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReaderRRule.php
> +		if (isset($this->until)) {
```suggestion
		if ($this->until instanceof \DateTimeInterface) {
```

isset is totally fine because until is typed as \DateTimeInterface|null. 
I prefer the instanceof version for the better readability.

2024-06-24 11:50 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReaderRRule.php
> +			// temporarly store current reccurance date and counter
```suggestion
			// temporarily store current recurrence date and counter
```

2024-06-24 11:50 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReaderRRule.php
> +			// iterate over occurances until last one (subtract 2 from count for start and end occurance)
```suggestion
			// iterate over occurrences until last one (subtract 2 from count for start and end occurrence)
```

2024-06-24 11:50 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReaderRRule.php
> +			// restore current reccurance date and counter
```suggestion
			// restore current recurrence date and counter
```

2024-06-24 11:50 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReaderRRule.php
> +			// return last recurrance date
```suggestion
			// return last recurrence date
```

2024-06-25 06:37 UTC, st3iny requested changes

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/EventReader.php
> +	public function __construct(VCalendar|VEvent|array|string $input, ?string $uid = null, ?DateTimeZone $timeZone = null) {
Please split this to multiple static constructor functions and keep the constructor minimal. The `if`/`elseif` statements are hard to follow and maintain.

It will also be easier to deprecate some of the functions in the future.

E.g.
```
public static function fromVCalendar(/* [...] */): self {
}

public static function fromVEventArray(/* [...] */): self {
}

// etc.
```

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/EventReaderRDate.php
> +		}
```suggestion
		
		return null;
```

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime = $this->l10n->l('time', $er->startDateTime(), ['width' => 'short']) . (($er->startTimeZone() != $er->endTimeZone()) ? ' (' . $er->startTimeZone()->getName() . ')': '');
Please refactor the ternary operator. This line is hardly readable.

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime = $this->l10n->l('time', $er->startDateTime(), ['width' => 'short']) . (($er->startTimeZone() != $er->endTimeZone()) ? ' (' . $er->startTimeZone()->getName() . ')': '');
Please refactor the ternary operator. This line is hardly readable.

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime = $this->l10n->l('time', $er->startDateTime(), ['width' => 'short']) . (($er->startTimeZone() != $er->endTimeZone()) ? ' (' . $er->startTimeZone()->getName() . ')': '');
Please refactor the ternary operator. This line is hardly readable.

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$days = implode(', ', array_map(function ($value) { return $this->l10n->t($value); }, $er->recurringDaysOfWeekNamed()));
I'm not sure if `$this->l10n->t($value)` will work. AFAIK, the strings inside `t()` have to be literals and variables can't be used directly.

Did you test it using a different language setting?

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$oldMeetingWhen = $eventReaderPrevious->recurs() ? $this->generateWhenStringRecurring($eventReaderPrevious) : $this->generateWhenStringSingular($eventReaderPrevious);
It makes sense to keep the `generateWhenString()` method and refactor it a bit. The result of this ternary operator is used multiple times and its code is currently duplicated.

```php
private function generateWhenString(EventReader $reader): string {
	if ($eventReaderPrevious->recurs()) {
		return $this->generateWhenStringRecurring($eventReaderPrevious);
	}

 	return $this->generateWhenStringSingular($eventReaderPrevious);
}
```

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$data['meeting_when'] = $eventReaderCurrent->recurs() ? $this->generateWhenStringRecurring($eventReaderCurrent) : $this->generateWhenStringSingular($eventReaderCurrent);
See above regarding `generateWhenString()`.

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$newMeetingWhen = $eventReaderCurrent->recurs() ? $this->generateWhenStringRecurring($eventReaderCurrent) : $this->generateWhenStringSingular($eventReaderCurrent);
See above regarding `generateWhenString()`.

2024-06-25 06:37 UTC, st3iny commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			default => $this->l10n->t('Could not generate event recurrence statement')
I think it would be better to throw here because all 8 cases are covered anyway.

E.g. `throw new \Exception('Unreachable match case');`

The same also applies to the other similar methods in this class.

2024-06-25 06:39 UTC, st3iny reviewed
In general there are a lot of ternary operators. I'm not a big fan because they sacrifice readability for brevity.

I tagged the ones that are a bit problematic from my point of view. I'd also prefer some of the others to be refactored to regular if statements but have no hard opinions.

E.g. there are a lot of `return cond ? a : b` constructs.

---

It would also be nice to have some exemplary screenshots of the new messages or concrete steps for testing.

2024-06-25 07:48 UTC, kesselb commented on apps/dav/lib/CalDAV/EventReader.php
> +	public function __construct(VCalendar|VEvent|array|string $input, ?string $uid = null, ?DateTimeZone $timeZone = null) {
Good suggestion. 
Do we need all those ways to initialize the reader?

2024-06-25 07:59 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		$days = implode(', ', array_map(function ($value) { return $this->l10n->t($value); }, $er->recurringDaysOfWeekNamed()));
They have to be literals, yes. The l10n extraction tool can only look at the code statically. Variables can't be processed

2024-06-25 20:55 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			default => $this->l10n->t('Could not generate event recurrence statement')
@st3iny so I though of doing this but the trade off is that throwing an error would cause the event NOT to be saved. Since the email sending is done before we save the event to the database, I didn't want a missed match case to cause data loss.

2024-06-25 21:13 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$oldMeetingWhen = $eventReaderPrevious->recurs() ? $this->generateWhenStringRecurring($eventReaderPrevious) : $this->generateWhenStringSingular($eventReaderPrevious);
@st3iny you're right make sense to handle the if in a sub routine.

2024-06-25 21:30 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime = $this->l10n->l('time', $er->startDateTime(), ['width' => 'short']) . (($er->startTimeZone() != $er->endTimeZone()) ? ' (' . $er->startTimeZone()->getName() . ')': '');
How is this for a readability?

```
$startTime = $this->l10n->l('time', $er->startDateTime(), ['width' => 'short']);
$startTime .= $er->startTimeZone() != $er->endTimeZone() ? ' (' . $er->startTimeZone()->getName() . ')' : '';
```

2024-06-25 22:06 UTC, SebastianKrupinski commented
> It would also be nice to have some exemplary screenshots of the new messages or concrete steps for testing.

For testing just create a new calendar event with at least one attendee that has a valid email address.

Here are some screenshots of the new messages...

Singleton Partial Day Event

![Screenshot 2024-06-25 174246](https://github.com/nextcloud/server/assets/165827823/41e43588-b6c6-4714-a88a-34daed9ec064)

Singleton Complete Day Event

![Screenshot 2024-06-25 175756](https://github.com/nextcloud/server/assets/165827823/4403f16d-2719-4ff5-a9af-9c1e06590b69)

Recurring Daily Event

![Screenshot 2024-06-25 174523](https://github.com/nextcloud/server/assets/165827823/09649100-96ad-46ea-a75a-67e620064a0d)

Recurring Weekly Event

![Screenshot 2024-06-25 174959](https://github.com/nextcloud/server/assets/165827823/ebc5cc03-ea6f-401a-8563-69f0a046f122)

Recurring Bi-Weekly Event

![Screenshot 2024-06-25 175235](https://github.com/nextcloud/server/assets/165827823/fbd14e3a-f541-4c0f-8653-e0d1cedb3090)

Recurring Month Event with Absolute Date

![Screenshot 2024-06-25 175425](https://github.com/nextcloud/server/assets/165827823/93062466-a414-49af-9159-4cc00c06f967)

Recurring Monthly Event with Relative Date

![Screenshot 2024-06-25 175615](https://github.com/nextcloud/server/assets/165827823/1a20e54b-a608-4c20-a4ca-97abea5b7bb4)

2024-06-26 01:01 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/EventReader.php
> +	public function __construct(VCalendar|VEvent|array|string $input, ?string $uid = null, ?DateTimeZone $timeZone = null) {
@kesselb 
So I modeled this constructor after the original EventIterator from SaberDAV...

https://github.com/sabre-io/vobject/blob/1b388aab5cdbcb75a09be25f2e9119fc4463ae59/lib/Recur/EventIterator.php#L92

They have 3 different input formats, VCalendar, VEvent and an array of VEvents. I added the string so that the class can be more flexible and use full in the future.

2024-06-26 01:09 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/EventReaderRDate.php
> +		}
> 

This would be a redundant return of the same value... solved it by removing the else and brakets

2024-07-04 09:23 UTC, ChristophWurst approved these changes

2024-07-04 10:40 UTC, miaulalala requested changes

2024-07-04 10:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/EventReader.php
> +
```suggestion

		if (is_null($this->rruleIterator) && is_null($this->rdateIterator)) {
			return null;
		}
		
		// retrieve rrule conclusion date
		if (isset($this->rruleIterator)) {
			$rrule = $this->rruleIterator->concludes();
			// evaluate if rrule conclusion is null
			// if this is null that means the recurrence is infinte
			if ($rrule === null) {
				return null;
			}
		}
		
		// retrieve rdate conclusion date
		if (isset($this->rdateIterator)) {
			$rdate = $this->rdateIterator->concludes();
		}
		
		// evaluate if both rrule and rdate have date
		if (isset($rdate) && isset($rrule)) {
			// return the highest date
			return (($rdate > $rrule) ? $rdate : $rrule);
		} 
		
		if (isset($rrule)) {
			return $rrule;
		} 
			
		return $rdate;

```

2024-07-04 10:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/EventReader.php
> +		return [];
same early return as per above

2024-07-04 10:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/EventReader.php
> +	public function recurrenceDate(): DateTime | null {
```suggestion
	public function recurrenceDate(): ?DateTime {
```

2024-07-04 10:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/EventReader.php
> +		}
```suggestion
		return null;
```

2024-07-04 10:40 UTC, miaulalala commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		return [$interval, $scale];
```suggestion
		if ($dateInterval->y > 0) {
			$interval = $dateInterval->y;
			$scale = ($dateInterval->y > 1) ? 'years' : 'year';
			return [$interval, $scale];
		} 
		if ($dateInterval->m > 0) {
			$interval = $dateInterval->m;
			$scale = ($dateInterval->m > 1) ? 'months' : 'month';
			return [$interval, $scale];
		} 
		if ($dateInterval->d >= 7) {
			$interval = (int)($dateInterval->d / 7);
			$scale = ((int)($dateInterval->d / 7) > 1) ? 'weeks' : 'week';
			return [$interval, $scale];
		} 
		if ($dateInterval->d > 0) {
			$interval = $dateInterval->d;
			$scale = ($dateInterval->d > 1) ? 'days' : 'day';
			return [$interval, $scale];
		} 
		if ($dateInterval->h > 0) {
			$interval = $dateInterval->h;
			$scale = ($dateInterval->h > 1) ? 'hours' : 'hour';
			return [$interval, $scale];
		}
		
		$interval = $dateInterval->i;
		$scale = 'minutes';
		return [$interval, $scale];
```

2024-07-04 18:46 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime .= $er->startTimeZone() != $er->endTimeZone() ? ' (' . $er->startTimeZone()->getName() . ')' : '';
This check is needed when an event started today with timezone A and ends tomorrow with timezone B, like the summer time shift?

2024-07-04 18:46 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$endTime = $this->l10n->l('time', $er->endDateTime(), ['width' => 'short']) . ' (' . $er->endTimeZone()->getName() . ')';
We don't need the check for the timezone here?

2024-07-04 18:46 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		}
I think it would help a bit to move this block to an own function to reduce duplicate code. 

```php
	public function generateStartAndEndTime(EventReader $eventReader): array
	{
		if ($eventReader->entireDay()) {
			return ['', ''];
		}

		$startTime = $this->l10n->l('time', $eventReader->startDateTime(), ['width' => 'short']);
		$endTime = $this->l10n->l('time', $eventReader->endDateTime(), ['width' => 'short']);

		if ($eventReader->startTimeZone() !== $eventReader->endTimeZone()) {
			$startTime .= ' (' . $eventReader->startTimeZone()->getName() . ')';
			$endTime .= ' (' . $eventReader->endTimeZone()->getName() . ')';
		}

		return [$startTime, $endTime];
	}
```

And call it like `[$startTime, $endTime] = $this->generateStartAndEndTime($er);`

2024-07-05 08:51 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/EventReader.php
> +
This would break the logic of the function and even if I fix the logic I would be double testing test variables for null.

But thank you for the suggestion of the NullSafe operator this will be very useful in other parts of the code.

2024-07-05 08:57 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$endTime = $this->l10n->l('time', $er->endDateTime(), ['width' => 'short']) . ' (' . $er->endTimeZone()->getName() . ')';
Ah, I guess the idea is to show only one timezone if they are the same.

2024-07-05 11:41 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$endTime = $this->l10n->l('time', $er->endDateTime(), ['width' => 'short']) . ' (' . $er->endTimeZone()->getName() . ')';
yup

2024-07-05 11:56 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +			$startTime .= $er->startTimeZone() != $er->endTimeZone() ? ' (' . $er->startTimeZone()->getName() . ')' : '';
This is check is need to produce a different when line depending on weather an event is a full day or not

2024-07-05 11:59 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		}
I would leave this as is, that way if design wants custom formatting for singleton events to differ from recurring event then it can be adjusted per case.

2024-07-17 15:29 UTC, AndyScherzinger approved these changes

2024-07-17 15:29 UTC, st3iny approved these changes
LGTM! Extensive unit tests are great.

2024-07-18 08:04 UTC, miaulalala approved these changes

2024-07-18 10:57 UTC, merged