add option zimbra in ldap app
nextcloud/server pull request #4567
Opened 2017-04-27 20:01 UTC by johuder33

this PR allow us to connect zimbra LDAP with the user_ldap app, now zimbra users can login with their zimbra account to Nextcloud.

2017-04-28 10:19 UTC, blizzz commented
@johuder33 thanks for your contribution! May I ask you to look into:

1. Could you sign-off your commit (-s parameter in git commit, [more info](https://github.com/nextcloud/server/pull/1481))

2. @johuder33 since I have no resources, are you OK with being added to @nextcloud/ldap group, in case anything (issue, PR, …) related to Zimbra appears?

3. Can you add comments in the code how the format for Zimbra members looks like? 

4. What is the context of the change in dynamic groups (new lines 660ff)?

5. Please keep the new lines at the end of the files

2017-05-02 19:44 UTC, johuder33 commented
@blizzz Ok, I will modify the code and explain it too.

2017-05-03 12:29 UTC, go2sh commented
I just had a quick look. Wouldn't it be nice to have a general approach for Group Membership with E-Mails. There are some other ObjectClasses which work the same way only a different attribute. We could make group membership attributes configurable with a switch weather it contains a email address or a user id.

2017-05-03 15:24 UTC, johuder33 commented
@go2sh Thank you for your suggestion, right now I working on this, I hope for the next days I can make your suggestion, it would be nice too. I will considere your comment for the next PR. 👍

2017-05-05 13:54 UTC, johuder33 commented
@blizzz the changes are done, please add me to the group @nextcloud/ldap, there's not problem with that.

Any doubt you have please let me know.

2017-05-08 09:33 UTC, ChristophWurst commented
> igned-off-by: Juorder Gonzalez quiñonez <juordergonzalezquinonez@MBPdeJuorder2.home>

FYI looks like your git config is not set to your real email address 😉 That's also why GitHub doesn't recognize it's your commit.

2017-05-10 08:55 UTC, blizzz requested changes

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +			$dns = array();
these days you can use short notation ``$dns = [];`` :)

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +			// loop througth array members
typo

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +								// split the email of each member eg. member_name@zimbra.com
intendentation here and the following four lines appears wrong

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +			foreach($members as $mailOfMember) {
It seems this can take a lot of time on big groups with many members. Do you think it is possible to use the  provided ``$uid`` attribute and attempt to look up the user directly?

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +						$pos = strpos($dynamicGroup['dn'][0], ',');
did you test this against groups having a ,  in  their cn?

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +							$groups[] = $membershipGroup;
This should be dealt with  ``$this->access->dn2groupname``, because we rely on mappings here and avoid name collisions (e.g. with groups from other backends). Adding the group just like this won't have it mapped and further operations against this group might not work.

2017-05-10 08:55 UTC, blizzz commented on apps/user_ldap/lib/Group_LDAP.php
> +				$filter = $this->access->combineFilterWidthAnd(array(
Typo in method name,  it should be ``combineFilterWithAnd``

2017-05-10 08:58 UTC, blizzz commented
@johuder33 thanks a lot! Please see my review comments, important points are a typo  in method name, one worry about  group mapping and a question on speeding up one part. I also invited you to the group.

2017-11-13 16:01 UTC, blizzz commented
@johuder33 any update? i move it 14 due to feature freeze.

2018-03-07 22:16 UTC, MorrisJobke commented
No feedback for 10 months -> closing

😢

2018-03-07 22:16 UTC, closed without merging