Use isRetryable to catch retryable exceptions
nextcloud/server pull request #45768
Opened 2024-06-10 16:03 UTC by artonge

I probably tested before switching to the non deprecated method `executeStatement`.
This method wraps the exception in a `DbalException` which provides the handy `isRetryable` method.

2024-06-11 16:19 UTC, mgallien requested changes
does not work
exception below
```
{
  "reqId": "NUQ2oEs9xatUlVpYSuAD",
  "level": 3,
  "time": "2024-06-11T16:15:44+00:00",
  "remoteAddr": "192.168.21.4",
  "user": "john",
  "app": "webdav",
  "method": "MOVE",
  "url": "/remote.php/dav/trashbin/john/trash/bigFolder3.d1718122530",
  "message": "An exception occurred while executing a query: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
  "version": "26.0.13",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\DeadlockException",
    "Message": "An exception occurred while executing a query: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
    "Code": 1213,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1814,
        "function": "convert",
        "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          [
            "Doctrine\\DBAL\\Query"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1749,
        "function": "handleDriverException",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          [
            "Doctrine\\DBAL\\Query"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1163,
        "function": "convertExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          "UPDATE `oc_filecache` SET `storage` = ?, `path_hash` = MD5(CONCAT(?, SUBSTR(`path`, ?))), `path` = CONCAT(?, SUBSTR(`path`, ?)) WHERE (`storage` = ?) AND (`path` LIKE ?)",
          [
            3,
            "files/bigFolder3",
            44,
            "files/bigFolder3",
            44,
            3,
            "files\\_trashbin/files/bigFolder3.d1718122530/%"
          ],
          [
            1,
            2,
            1,
            2,
            1,
            1,
            2
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/private/DB/Connection.php",
        "line": 295,
        "function": "executeStatement",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          "UPDATE `oc_filecache` SET `storage` = ?, `path_hash` = MD5(CONCAT(?, SUBSTR(`path`, ?))), `path` = CONCAT(?, SUBSTR(`path`, ?)) WHERE (`storage` = ?) AND (`path` LIKE ?)",
          [
            3,
            "files/bigFolder3",
            44,
            "files/bigFolder3",
            44,
            3,
            "files\\_trashbin/files/bigFolder3.d1718122530/%"
          ],
          [
            1,
            2,
            1,
            2,
            1,
            1,
            2
          ]
        ]
      },
```

2024-06-11 21:35 UTC, artonge commented
> does not work

Are you sure? I can reproduce consistently without the PR, and I hardly get a failure with it.

2024-06-12 08:00 UTC, mgallien approved these changes
works fine
I was wrong since I still had changes from https://github.com/nextcloud/server/pull/45761
thanks

2024-06-12 08:01 UTC, artonge commented
/backport to stable29

2024-06-12 08:01 UTC, artonge commented
/backport to stable28

2024-06-12 08:01 UTC, artonge commented
/backport to stable27

2024-06-12 08:01 UTC, artonge commented
/backport to stable26

2024-06-12 08:03 UTC, skjnldsv approved these changes

2024-06-12 08:08 UTC, merged