fix: rename split into two as before rename and after rename
nextcloud/server pull request #45845
Opened 2024-06-13 07:33 UTC by yemkareems

rename logged as beforeRename and afterRename, and in both placegetInternalPath is used in place of getPath to make it consistent across the logs

So now we ll have two log entries when rename happens with from and to getting logged separately

{"reqId":"7SJtZiOQno7ZVY3N7wu6","level":1,"time":"2024-06-13T04:09:43+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"admin_audit","method":"MOVE","url":"/remote.php/dav/files/admin/nc.logs.txt","message":"File with id "2263" renamed from "/nc.logs.txt"","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","version":"30.0.0.1","data":{"app":"admin_audit"}}

{"reqId":"7SJtZiOQno7ZVY3N7wu6","level":1,"time":"2024-06-13T04:09:43+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"admin_audit","method":"MOVE","url":"/remote.php/dav/files/admin/nc.logs.txt","message":"File with id "2263" renamed to "/nc1.logs.txt"","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","version":"30.0.0.1","data":{"app":"admin_audit"}}

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-06-13 07:47 UTC, kyteinsky commented on apps/admin_audit/lib/AppInfo/Application.php
>  		);
maybe put `BeforeNodeRenamedEvent` before `NodeRenamedEvent`? It is still fine if not.

2024-06-13 07:47 UTC, kyteinsky approved these changes

2024-06-13 09:01 UTC, artonge approved these changes

2024-06-13 09:01 UTC, artonge commented on apps/admin_audit/lib/Actions/Files.php
> +		);
Don't log here, simply store the `$source`, or even simply the `oldpath` in a mapping `id => $source`.

2024-06-13 12:07 UTC, yemkareems commented on apps/admin_audit/lib/Actions/Files.php
> +		);
passed it as renameParams and logging only once in afterRename function

2024-06-13 15:26 UTC, artonge commented on apps/admin_audit/lib/Actions/Files.php
> +	private array|null $renameParams = null;
```suggestion
	private array $renamedNodes = [];
```

2024-06-13 15:26 UTC, artonge commented on apps/admin_audit/lib/Actions/Files.php
> +		$this->renameParams = $params;
```suggestion
		$this->renameParams[$source->getId()] = $source;
```

2024-06-13 15:26 UTC, artonge commented on apps/admin_audit/lib/Actions/Files.php
> +			$renameParams = $this->renameParams;
```suggestion
			$originalSource = $this->renameParams[$target->getId()];
```

2024-06-13 15:26 UTC, artonge commented on apps/admin_audit/lib/Actions/Files.php
> +				'oldpath' => $renameParams['oldpath'],
```suggestion
				'oldpath' => mb_substr($originalSource->getInternalPath(), 5),
```

2024-06-13 15:27 UTC, artonge requested changes
To prevent having it merged

2024-06-17 09:09 UTC, artonge approved these changes

2024-06-20 06:06 UTC, merged

2024-11-28 16:09 UTC, come-nc commented
This broke admin_audit when renaming into a share or groupfolder, because `getInternalPath` returns a path relative to the mountpoint, not to the user folder.