fix(files): Ignore right click for default action
nextcloud/server pull request #45861
Opened 2024-06-13 13:22 UTC by artonge

Follow up of https://github.com/nextcloud/server/pull/45571

2024-06-13 13:23 UTC, artonge commented
/backport! to stable28

2024-06-13 13:24 UTC, skjnldsv approved these changes

2024-06-13 13:27 UTC, skjnldsv approved these changes

2024-06-13 13:28 UTC, susnux commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
This should not be committed

2024-06-13 13:28 UTC, susnux commented on apps/files/src/components/FileEntryMixin.ts
> +			if (event.button === 2) {
Should we ignore all non-main buttons? I mean if I press my tertiary button I would not expect the action to be performed.
The only button I am not sure about is middle-mouse button for opening in new tab?

```suggestion
			if (event.button != 2) {
```

2024-06-13 13:31 UTC, artonge commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Arg, thanks

2024-06-13 13:32 UTC, artonge commented on apps/files/src/components/FileEntryMixin.ts
> +			if (event.button === 2) {
From what I understand,
0 is left
1 is middle
2 is right
3 and above is whatever

`if (event.button >= 1) {` ?

2024-06-13 14:10 UTC, nickvergessen requested changes, later dismissed

2024-06-13 14:10 UTC, nickvergessen commented on apps/files/src/components/FileEntryMixin.ts
> +				retrurn
```suggestion
				return
```

2024-06-13 14:12 UTC, artonge commented on apps/files/src/components/FileEntryMixin.ts
> +				retrurn
:face_exhaling:

2024-06-13 16:50 UTC, blizzz approved these changes

2024-06-13 17:29 UTC, susnux commented on apps/files/src/components/FileEntryMixin.ts
> +			if (event.button === 2) {
Makes sense

2024-06-14 08:16 UTC, skjnldsv approved these changes

2024-06-14 08:16 UTC, merged

2024-06-14 08:36 UTC, blizzz commented
/backport to stable29

2024-06-14 08:36 UTC, blizzz commented
/backport to stable28