fix(caldav): lower scheduling table size warning
nextcloud/server pull request #45974
Opened 2024-06-19 13:05 UTC by miaulalala

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-06-19 13:06 UTC, nickvergessen approved these changes

2024-06-19 13:06 UTC, miaulalala commented
/backport to stable29

2024-06-19 13:06 UTC, miaulalala commented
/backport to stable28

2024-06-19 13:07 UTC, miaulalala commented
/backport to stable27

2024-06-20 08:33 UTC, ChristophWurst approved these changes

2024-06-20 08:33 UTC, ChristophWurst commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than 50 000 rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive')
nit: make the number a variable so it can be changed without the need for a new translation string. it will also allow you to move the magic number into a constant

2024-06-20 09:10 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than 50 000 rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive')
Was thinking the same :P

2024-06-25 13:33 UTC, ChristophWurst requested changes

2024-06-25 13:33 UTC, ChristophWurst commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than ' . self::MAX_SCHEDULING_ENTRIES . ' rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive')
you have to use a placeholder.
concatenated strings can not be translated

2024-06-27 09:30 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than %s rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive.', [
Is it worth a plural now? :speak_no_evil:

2024-06-27 11:58 UTC, miaulalala commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than %s rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive.', [
wdym? `row(s)`?

2024-06-27 12:50 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than %s rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive.', [
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#php
```
    public function getAuthors($count, $city) {
        // Translation with plural
        return $this->l->n(
            '%n author is currently in the city %1$s',  // singular string
            '%n authors are currently in the city %1$s',  // plural string
            $count, // number to decide which plural to use
            [$city] // further parameters are possible
        );
    }
```

So maybe hardcoding is better :-X

2024-06-27 12:54 UTC, ChristophWurst commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than %s rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive.', [
We'll always use this in the thousands so singular/plural distinction will never be used. Let's translate a single string with a placeholder

2024-06-27 13:00 UTC, nickvergessen commented on apps/settings/lib/SetupChecks/SchedulingTableSize.php
> +				$this->l10n->t('You have more than %s rows in the scheduling objects table. Please run the expensive repair jobs via occ maintenance:repair --include-expensive.', [
So, refresh your review and we are good to go :P

2024-07-17 06:54 UTC, ChristophWurst approved these changes

2024-07-17 13:36 UTC, merged