Signed requests
nextcloud/server pull request #45979
Opened 2024-06-19 13:49 UTC by ArtificialOwl

untested code

2024-07-11 08:12 UTC, nickvergessen requested changes, later dismissed

2024-07-11 08:12 UTC, nickvergessen commented on lib/public/Migration/Attributes/TableCreation.php
Unrelated

2024-07-11 08:12 UTC, nickvergessen commented on lib/private/Security/Signature/Model/SignedRequest.php
> +		$this->digest = 'SHA-256=' . base64_encode(hash("sha256", utf8_encode($body), true));
```suggestion
		$this->digest = 'SHA-256=' . base64_encode(hash('sha256', utf8_encode($body), true));
```

2024-07-11 08:12 UTC, nickvergessen commented on lib/private/Security/Signature/SignatureManager.php
> +		$this->logger->debug('[<<] incoming signed request', ['body length' => strlen($body)]);
:broom:

2024-07-11 08:12 UTC, nickvergessen commented on core/Migrations/Version30000Date20240101084401.php
> +				'length' => 127
Please use 512 like we do for "remote" in external shares:
```suggestion
				'length' => 512,
```

2024-07-11 08:12 UTC, nickvergessen commented on lib/private/Security/Signature/SignatureManager.php
> +	private function insertSignatory(ISignatory $signatory): void {
By now our Entity+QBMapper pattern is widely adapted. Any reason why you didn't go for it and instead went back to doing all this manually again?

2024-07-11 08:12 UTC, nickvergessen commented on lib/private/Security/Signature/SignatureManager.php
> +		$qb->where($qb->expr()->eq('`key_id_sum`', $qb->createNamedParameter($this->hashKeyId($signatory->getKeyId()))));
```suggestion
		$qb->where($qb->expr()->eq('key_id_sum', $qb->createNamedParameter($this->hashKeyId($signatory->getKeyId()))));
```

2024-07-11 12:25 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
> +			$this->confirmShareOrigin($signedRequest, $notification['sharedSecret'] ?? '');
this would not break it as I send the exception for the exact same reason of a missing 'sharedSecret' entry in the notifications request. The only thing is that I do this check earlier than others but I can add a prefix if you want (while I dont feel like necessary myself)

2024-07-11 12:30 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +	private function insertSignatory(ISignatory $signatory): void {
no real reason other that personal preference

2024-07-11 12:39 UTC, nickvergessen commented on apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
> +			$this->confirmShareOrigin($signedRequest, $notification['sharedSecret'] ?? '');
> this would not break it as I send the exception for the exact same reason of a missing 'sharedSecret' entry in the notifications request.

Nextcloud Talk is sending a data field `'sharedSecret'` and you either overwrite that and it breaks Talk Federation with older servers or you need to use a different key

2024-10-30 20:18 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
> +			$this->confirmShareOrigin($signedRequest, $notification['sharedSecret'] ?? '');
As said before, I only use this entry because it exists in the OCM protocol and doing so to compare that the origin of the reshare request, based on the token (and the linked recipient stored in the database), confirm the identity used to sign the request.

If Talk is using this endpoint to initiate anything, signature are to be required

2024-11-14 14:39 UTC, artonge approved these changes

2024-11-14 14:55 UTC, come-nc commented on apps/cloud_federation_api/lib/Capabilities.php
> +use NCU\Security\PublicPrivateKeyPairs\Exceptions\KeyPairException;
```suggestion
use NCU\Security\KeyPairs\Exceptions\KeyPairException;
```
Might be bikeshedding, but PublicPrivateKeyPair sounds redundant?

2024-11-14 14:55 UTC, come-nc commented on apps/cloud_federation_api/lib/Capabilities.php
> +		return ['ocm' => json_decode(json_encode($this->provider->jsonSerialize()), true)];
Is the `json_decode(json_encode(` really needed?

2024-11-14 14:55 UTC, come-nc commented on apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
> +		throw new IncomingRequestException('host is empty');
This should be checked before the port to avoid returning ':239'

2024-11-14 14:55 UTC, come-nc commented on build/integration/federation_features/cleanup-remote-storage.feature
> +    And the list of returned shares has 1 shares
What change results in this being needed?

2024-11-14 14:55 UTC, come-nc commented on lib/private/Federation/CloudFederationProviderManager.php
> +			return $client->post($uri, $signedPayload ?? $payload);
code is duplicated 4 times, please wrap it in a method.

2024-11-14 14:55 UTC, come-nc commented on lib/private/OCM/OCMSignatoryManager.php
> +class OCMSignatoryManager implements ISignatoryManager {
Why is it injected using the class name in applications if it has an interface?

2024-11-14 14:55 UTC, come-nc commented on lib/private/Security/PublicPrivateKeyPairs/KeyPairManager.php
> + * and lazy loading.
It should use its own table, it’s a bad habit to put everything into appconfig.

2024-11-14 14:55 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +		ISignatoryManager $signatoryManager,
Why is that not injected? It creates a dependency loop?

2024-11-14 14:55 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	public function signOutgoingRequestIClientPayload(
```suggestion
	public function signOutgoingRequestPayload(
```

2024-11-14 14:55 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	}
Is there no mapper and entities for signatories?

2024-11-14 14:55 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	}
I have Déjà-vu about this code

2024-11-15 10:24 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Capabilities.php
> +		return ['ocm' => json_decode(json_encode($this->provider->jsonSerialize()), true)];
it is only requested for psalm as jsonSerialize returns serializable objects

2024-11-15 10:24 UTC, ArtificialOwl commented on apps/cloud_federation_api/lib/Capabilities.php
> +use NCU\Security\PublicPrivateKeyPairs\Exceptions\KeyPairException;
done

2024-11-15 10:34 UTC, ArtificialOwl commented on lib/private/OCM/OCMSignatoryManager.php
> +class OCMSignatoryManager implements ISignatoryManager {
`ISignatoryManager` is not limited to OCM, it is an independant API that could be used to sign request for any other protocol. the idea is to generate its own way to obtain (ie. discovery) the needed information for `SignatureManager` to sign/verify payload

2024-11-15 10:36 UTC, ArtificialOwl commented on lib/private/Security/PublicPrivateKeyPairs/KeyPairManager.php
> + * and lazy loading.
I think it is the main idea of appconfig to avoid creating a new table for only few entries, and the lazy loading helps keeping it light

2024-11-15 23:46 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +	}
yes, fixed

2024-11-18 08:40 UTC, ArtificialOwl commented
Since last review, new commit:

- switching to `IdentityProof` 
- removing features not fully related to this PR
- fixing some edge use case on federationId,
- fixing an issue to extract the origin of a notification on a reshare,
- fixing test by adding threads to httpd,
- fixing all comments/requests from previous reviews
- upgrading version to trigger database migration

2024-11-18 14:01 UTC, come-nc commented on apps/cloud_federation_api/lib/Capabilities.php
> +		return ['ocm' => json_decode(json_encode($this->provider->jsonSerialize()), true)];
@provokateurin Any idea how to avoid it?

2024-11-18 14:42 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	private function signingOutgoingRequest(IOutgoingSignedRequest $signedRequest): void {
```suggestion
	private function signOutgoingRequest(IOutgoingSignedRequest $signedRequest): void {
```

2024-11-18 14:52 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +			'algorithm="' . $this->getChosenEncryption($signedRequest->getAlgorithm()) . '"',
```suggestion
			'algorithm="' . $signedRequest->getAlgorithm() . '"',
```
Why not this directly?

2024-11-18 14:55 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	}
If you use an enum backed by a string you should not then write your own methods to translate it to and from string, use the ones from PHP.

Also the enum can host the method to translate to opensslalgo int.

2024-11-18 14:57 UTC, come-nc commented on lib/private/Security/Signature/SignatureManager.php
> +	private function manageDeprecatedSignatory(?ISignatory $knownSignatory): void {
```suggestion
	private function checkDeprecatedSignatory(?ISignatory $knownSignatory): void {
```

2024-11-20 09:18 UTC, nickvergessen commented on apps/cloud_federation_api/lib/Capabilities.php
> +		return ['ocm' => json_decode(json_encode($this->provider->jsonSerialize()), true)];
https://github.com/nextcloud/server/pull/45979/files#diff-16c946a83c0045d121ec926b69acadd4ccad303eb46144b3dfd087664522b8b2R212
```
publicKey: ISignatory|null,
```

I think this is the problem, instead you need to jsonSerialize that already and make it an array

2024-11-21 04:17 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +	private function manageDeprecatedSignatory(?ISignatory $knownSignatory): void {
the purpose is not to check but to set an action in case the remote instance does not provide signatory/public key anymore. Base on the type of link between the 2 instances, some action is performed

2024-11-21 11:25 UTC, come-nc requested changes
There should be a mapper for signatory
There should not be a digest sent to openssl_* which is creating a digest by itself.
clearSignature should be renamed to something more appropriate.

2024-11-22 12:28 UTC, ArtificialOwl commented on lib/private/Security/Signature/Model/OutgoingSignedRequest.php
> +			$value = $headers[$element];
wtf.

2024-11-22 12:40 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +		}
it is set by the 3rd party `ISignatoryManager` that will decide how must be handle a change of the remote public key

2024-11-22 18:00 UTC, ArtificialOwl commented on lib/private/Security/Signature/Model/IncomingSignedRequest.php
> +			preg_match('/"([^"]+)"/', $v, $var);
I know mine is working, what should I expected different from yours ?

2024-11-25 09:48 UTC, come-nc commented on lib/private/Security/Signature/Model/IncomingSignedRequest.php
> +			preg_match('/"([^"]+)"/', $v, $var);
https://regex101.com/r/BPNH0j/1
Yours will match quotes even if there is unexpected stuff around.
Mine makes sure that quotes are first and last characters.

2024-11-26 10:26 UTC, sorbaugh commented
Hello, due to the importance of having this issue merged, please let's postpone all approach-related optimization to later. If this PR checks this boxes, please let's approve and merge:

- [ ] PR fixes the issue / adds the feature as intended
- [ ] PR is backport compatible (needs a config switch that's OFF by default, needs to work with the OCM ecosystem)

After that we should update the documentation about the config switch.

Thanks! 🙏

2024-11-27 13:03 UTC, ArtificialOwl commented on lib/private/Security/Signature/Model/SignedRequest.php
> +		$this->digest = 'SHA-256=' . base64_encode(hash('sha256', utf8_encode($body), true));
I am not a fan of signing a document including part of content that could be generated from the outside. Using a checksum of the content (with a base64 encoding on top) makes everything more random. It also limit the size of the data sent to be signed which (I think) should be better (theoretically) to ensure the private key private

2024-11-27 13:04 UTC, ArtificialOwl commented on lib/private/Security/Signature/Model/OutgoingSignedRequest.php
> +	 * @return IOutgoingSignedRequest
i'll have a look

2024-11-27 13:04 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +		$signedRequest->setClearSignature(implode("\n", $estimated));
i'll get a new term

2024-11-28 13:02 UTC, come-nc commented on lib/private/Security/Signature/Model/SignedRequest.php
> +		$this->digest = 'SHA-256=' . base64_encode(hash('sha256', utf8_encode($body), true));
That is already what openssl_sign is doing. You do not need to prepare a hash before hand.
openssl_sign takes a hash method as a parameter, which it applies to the string before encryption to create the signature.
Why hash twice? It’s both a performance loss and a security issue because you rely on 2 hash methods and one of them being broken is enough.

2024-12-02 14:30 UTC, ArtificialOwl commented on lib/private/Security/Signature/Model/SignedRequest.php
> +		$this->digest = 'SHA-256=' . base64_encode(hash('sha256', utf8_encode($body), true));
This is the process described in [RFC 9421: HTTP Message Signatures](https://datatracker.ietf.org/doc/rfc9421/)

Our implementation does not use the same syntax that the one defined in that RFC but the process stay the same.
The syntax used here is closer to ActivityPub/Mastodon.

There is this article describing the verification of Mastodon's HTTP message signatures in PHP: https://shkspr.mobi/blog/2024/02/a-simpleish-guide-to-verifying-http-message-signatures-in-php/ and the code from this PR is based on my previous work on `social`

2024-12-02 15:25 UTC, come-nc commented on lib/public/OCM/IOCMProvider.php
> +	public function getSignatory(): ?Signatory;
Should remove those from OCP, at least for now.

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/IIncomingSignedRequest.php
> +	public function setOrigin(string $origin): IIncomingSignedRequest;
```suggestion
```

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setDigestAlgorithm(DigestAlgorithm $algorithm): self;
```suggestion
```

Should only be on outgoing requests

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSigningElements(array $elements): self;
Should be on outgoing requests

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSignatureData(array $data): self;
Should not be set from outside?

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSignature(string $signature): self;
Same thing.

2024-12-02 15:25 UTC, come-nc commented on lib/unstable/Security/Signature/Model/Signatory.php
> +	}
Needs to add metadata to updated fields

2024-12-03 10:43 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSigningElements(array $elements): self;
this is also used on incoming request to reconstruct the signature

2024-12-03 10:45 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSignature(string $signature): self;
used in both incoming/outgoing

2024-12-03 10:51 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSignatureData(array $data): self;
set from outgoing/incoming

2024-12-03 14:06 UTC, come-nc commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSigningElements(array $elements): self;
Where?
```
> grep -R setSigningE lib apps/**.php core
lib/unstable/Security/Signature/ISignedRequest.php:     public function setSigningElements(array $elements): self;
lib/private/Security/Signature/Model/OutgoingSignedRequest.php:         $this->setSigningElements(
lib/private/Security/Signature/Model/SignedRequest.php: public function setSigningElements(array $elements): self {
lib/private/Security/Signature/Model/IncomingSignedRequest.php:         $this->setSigningElements($details);
```

I only see it being called internally, should not be part of the interface for incoming request, we do not get to chose the signing elements for an incoming request, it’s written in the headers.

2024-12-03 14:24 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/IIncomingSignedRequest.php
> +	public function setOrigin(string $origin): IIncomingSignedRequest;
done

2024-12-03 14:26 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setDigestAlgorithm(DigestAlgorithm $algorithm): self;
done

2024-12-03 17:02 UTC, ArtificialOwl commented on lib/private/Security/Signature/SignatureManager.php
> +	private function insertSignatory(ISignatory $signatory): void {
switched to QBMapper

2024-12-03 17:03 UTC, ArtificialOwl commented on lib/unstable/Security/Signature/ISignedRequest.php
> +	public function setSigningElements(array $elements): self;
misinterpretation of your review, this is now as expected

2024-12-03 20:09 UTC, come-nc approved these changes

2024-12-04 10:48 UTC, merged

2024-12-04 12:43 UTC, nickvergessen commented on core/Migrations/Version31000Date20240101084401.php
> +				'default' => '[]'
```sql
mysql> DESCRIBE oc_sec_signatory;
+--------------+-----------------+------+-----+---------+----------------+
| Field        | Type            | Null | Key | Default | Extra          |
+--------------+-----------------+------+-----+---------+----------------+
| id           | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| key_id_sum   | varchar(127)    | NO   | MUL | NULL    |                |
| key_id       | varchar(512)    | NO   |     | NULL    |                |
| host         | varchar(512)    | NO   |     | NULL    |                |
| provider_id  | varchar(31)     | NO   | MUL | NULL    |                |
| account      | varchar(127)    | YES  |     |         |                |
| public_key   | longtext        | NO   |     | NULL    |                |
| metadata     | longtext        | NO   |     | NULL    |                |
| type         | smallint        | NO   |     | 9       |                |
| status       | smallint        | NO   |     | 0       |                |
| creation     | int unsigned    | YES  |     | 0       |                |
| last_updated | int unsigned    | YES  |     | 0       |                |
+--------------+-----------------+------+-----+---------+----------------+
12 rows in set (0,00 sec)
```

Seems this does not work. TEXT fields can not have a default.

2024-12-04 13:27 UTC, nickvergessen commented on core/Migrations/Version31000Date20240101084401.php
> +				'default' => '[]'
This breaks Talk integration tests on:
MySQL
```
{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'metadata' doesn't have a default value"
```

2024-12-05 20:50 UTC, juliusknorr commented on core/Migrations/Version31000Date20240101084401.php
> +				'default' => '[]'
I think there is another failure with oracle catched by richdocuments integration tests:

```
{"Exception":"Exception","Message":"Cannot assign null to property NCU\\Security\\Signature\\Model\\Signatory::$account of type string in file '\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/Entity.php' line 149","Code":0,"Trace":[{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/AppFramework\/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Route\/Router.php","line":306,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/base.php","line":1019,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":146,"Previous":{"Exception":"TypeError","Message":"Cannot assign null to property NCU\\Security\\Signature\\Model\\Signatory::$account of type string","Code":0,"Trace":[{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/Entity.php","line":59,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/QBMapper.php","line":315,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/QBMapper.php","line":375,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Security\/Signature\/Db\/SignatoryMapper.php","line":56,"function":"findEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Security\/Signature\/SignatureManager.php","line":326,"function":"getByKeyId","class":"OC\\Security\\Signature\\Db\\SignatoryMapper","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Security\/Signature\/SignatureManager.php","line":140,"function":"getStoredSignatory","class":"OC\\Security\\Signature\\SignatureManager","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Security\/Signature\/SignatureManager.php","line":108,"function":"confirmIncomingRequestSignature","class":"OC\\Security\\Signature\\SignatureManager","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/apps\/cloud_federation_api\/lib\/Controller\/RequestHandlerController.php","line":339,"function":"getIncomingSignedRequest","class":"OC\\Security\\Signature\\SignatureManager","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/apps\/cloud_federation_api\/lib\/Controller\/RequestHandlerController.php","line":104,"function":"getSignedRequest","class":"OCA\\CloudFederationAPI\\Controller\\RequestHandlerController","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":200,"function":"addShare","class":"OCA\\CloudFederationAPI\\Controller\\RequestHandlerController","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/AppFramework\/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/private\/Route\/Router.php","line":306,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/base.php","line":1019,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/Entity.php","Line":149},"message":"Cannot assign null to property NCU\\Security\\Signature\\Model\\Signatory::$account of type string in file '\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/Entity.php' line 149","exception":{},"CustomMessage":"Cannot assign null to property NCU\\Security\\Signature\\Model\\Signatory::$account of type string in file '\/home\/runner\/actions-runner\/_work\/richdocuments\/richdocuments\/lib\/public\/AppFramework\/Db\/Entity.php' line 149"}
```