feat(files_sharing): add `new file request` option
nextcloud/server pull request #46007
Opened 2024-06-20 12:03 UTC by skjnldsv

closes https://github.com/nextcloud/server/issues/45446

2024-07-09 09:20 UTC, skjnldsv commented on lib/private/DB/Connection.php
> +			// $this->logger->log(
REMOVE

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> -use OCP\AppFramework\Http;
This causes the psalm error below because now `Http::STATUS_OK` is unknown.

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $mailSend = null
why is this a string and not a boolean?

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $mailSend = null,
same here

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +	 * @param string[] $emails a list of emails to send the notification to
Param does not exist (but `password`)

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestDatePassword.vue
> +<!--
Vue naming schema would be to always keep the "parent" name.
`NewFileRequestDialogIntro`
`NewFileRequestDialogDatePasswort`
`NewFileRequestDialogFinish`

See https://vuejs.org/style-guide/rules-strongly-recommended.html#tightly-coupled-component-names

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestDatePassword.vue
> +		deadline: {
I think it would make thing clearer to call it `expirationDate`

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestDatePassword.vue
> +		showPassword() {
good point we should expose a function from the component so you can programmatically show the password without access to private internals :)

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +				<IconClipboard v-else :size="20" @click="copyShareLink" />
Having click listeners on non-interactive elements (icons here) is bad and will cause accessibility warning / maybe even errors.

Instead just use `click-trailing-button` which you already do for the clipboard one, so just adjust the function (see below).

```suggestion
				<IconCheck v-if="isCopied" :size="20" />
				<IconClipboard v-else :size="20" />
```

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +				showError(this.t('files_sharing', 'Clipboard is not available'))
We could add a fallback for local networks, had a lot of complains about that.
Like
```suggestion
				window.prompt(t('files_sharing', 'Automatically copying failed, please copy the sharelink manually:') this.shareLink)
```

2024-07-09 09:59 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +			if (!navigator.clipboard) {
```suggestion
			if (this.isCopied) {
				this.isCopied = false
				return
			}
			if (!navigator.clipboard) {
```

2024-07-09 10:00 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $mailSend = null
Was discussed somehow this will cause an issue

2024-07-09 10:01 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $mailSend = null
Because it doesn't work, see the other booleans types like `publicUpload` or `sendPasswordByTalk`

2024-07-09 10:01 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestDatePassword.vue
> +<!--
Good call :+1:

2024-07-09 10:01 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +		<form ref="form"
I think because of changing content you need `aria-live="polite"`

2024-07-09 10:02 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +				<IconClipboard v-else :size="20" @click="copyShareLink" />
Yeah, I did this before and the click did not work either. That's why I tried to move it to the icon element. That is temporary :+1: 
I need to double check again

2024-07-09 10:06 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +		<form ref="form"
Thanks! I wanted to ask the accessibility team, I wasn't sure about how to handle that

2024-07-09 10:14 UTC, come-nc approved these changes
Reviewed PHP only, all good except from psalm errors to fix. (and openapi)

2024-07-09 10:15 UTC, skjnldsv commented on apps/sharebymail/lib/ShareByMailProvider.php
> +			$e = new HintException('Failed to send share by mail. Could not find a valid email address: ' . join(', ', $emails),
It is logged as error right below :)

2024-07-09 10:16 UTC, skjnldsv commented on apps/sharebymail/lib/ShareByMailProvider.php
> +				if ($passwordExpire === false || $share->getSendPasswordByTalk()) {
Didn't touch that part, that's how it was before.
It's compatible with Mail shares in general, but we don't use it from the File Request feature :)

2024-07-09 10:20 UTC, artonge commented on apps/files_sharing/src/models/Share.js
> +			return attribute.scope === 'fileRequest' && attribute.key === 'enabled' && attribute.value === true
Shouldn't it be based on the permissions and not an extra attribute?

2024-07-09 10:20 UTC, artonge commented on apps/files_sharing/src/new/newFileRequest.ts
> +		// determine requirements
```suggestion
		// TODO: determine requirements
```

2024-07-09 10:22 UTC, artonge commented on lib/public/Share/IAttributes.php
> +	 * @param bool|string|array|null $value value
Isn't it a breaking change?

2024-07-09 10:26 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +			const regExpEmail = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
Not sure how much sense such a regex makes, it often does not sattiesfies all valid cases, I would recommend to use the following which only has 2 limitiations on valid emails:
1. @ is only allowed once (in theory you can have it quoted in valid emails like `"my@home"@domain.com`
2. Require a TLD, in theory you can have just the hostname for local networks

`/^[^@]+@[^@]+\.[^.]{2,}$/`

And then the backend should verify it properly as we have the tool for it:
https://nextcloud-server.netlify.app/classes/ocp-mail-imailer#method_validateMailAddress

2024-07-09 10:26 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestIntro.vue
> +			<NcTextArea :value="note"
There is no label outside, the legend labels only the fieldset but not the text area.
So the textarea is missing a label for accessibility.

I would remove the fieldset and instead make it a `div` and move the legend text to the built-in `label` prop of the textarea, as there is only one field inside the fieldset.

Otherwiese add an ID to the legend and `aria-labelledby` to the text area

2024-07-09 10:26 UTC, susnux commented on apps/files_sharing/src/components/SharingEntryLink.vue
> +			const hasDisabledDownload = (shareAttribute) => shareAttribute.scope === 'permissions' && shareAttribute.key === 'download'&& shareAttribute.value === false
Maybe keep it readable :sweat_smile:  (or at least add a space between `'download' and '&&') ;)

```suggestion
			const hasDisabledDownload = (shareAttribute) => 
				shareAttribute.scope === 'permissions'
				&& shareAttribute.key === 'download'
				&& shareAttribute.value === false
```

2024-07-09 10:26 UTC, susnux commented on apps/files_sharing/src/new/newFileRequest.ts
> +		const NewFileRequestDialog = new Vue({
You can just use `spawnDialog` helper from `@nextcloud/dialogs` if you like :)

2024-07-09 10:26 UTC, susnux commented on apps/sharebymail/lib/ShareByMailProvider.php
> +	protected function sendPassword(IShare $share, string $password, array $emails) {
why removing the return type? I think we should in general do the opposite.
So probably should be `: void` and in line 357 you forgot to remove the `return false`

2024-07-09 12:33 UTC, skjnldsv commented on apps/sharebymail/lib/ShareByMailProvider.php
> +	protected function sendPassword(IShare $share, string $password, array $emails) {
Refactor issue :)
I had some pending changes to push which  included the boolean being back

2024-07-09 12:35 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +			const regExpEmail = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
This is the regex mail uses

2024-07-09 12:42 UTC, skjnldsv commented on apps/files_sharing/src/models/Share.js
> +			return attribute.scope === 'fileRequest' && attribute.key === 'enabled' && attribute.value === true
is it really a permission though?

2024-07-09 12:42 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +			<span class="dialog__actions-separator" />
I'll let them speak for themselves when I ask for a design review

2024-07-09 12:43 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +			const regExpEmail = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
https://github.com/nextcloud/mail/blob/1b2f3a012fb8be2ac2ec6dc5fb4294bff9a4e618/src/components/AccountForm.vue#L649

2024-07-10 12:56 UTC, jancborchardt commented
@skjnldsv could you add some screenshots? :) And cc @nimishavijay for the design

2024-07-12 10:27 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $sendMail = null
This should just be a boolean

2024-07-12 10:27 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $sendMail = null,
Boolean as well

2024-07-12 10:27 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +	 * @param string $password optional, the password to check against. Necessary for password protected shares.
```suggestion
	 * @param string $password the password to check against. Necessary for password protected shares.
```

No need to say it's optional, since it has a default value

2024-07-12 11:07 UTC, Fenn-CS reviewed
For commit => feat(files_sharing): add new file request option.

2024-07-12 11:07 UTC, Fenn-CS commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestDatePassword.vue
> +			enforcePasswordForPublicLink: window.OC.appConfig.core.enforcePasswordForPublicLink === true,
I don't think it's this is needed we have https://github.com/nextcloud/server/blob/master/apps/files_sharing/src/services/ConfigService.js

```js
import Config from '../services/ConfigService.js

export default {
	data() {
		return {
			config: new Config(),
			}
		}
}
```

All of those then become available in template via `this.config.*` using the `ShareMixin` would provide this out of the box (but could bloat this too)

2024-07-12 11:07 UTC, Fenn-CS commented on apps/files_sharing/src/components/NewFileRequestDialog/FileRequestFinish.vue
> +			isShareByMailEnabled: getCapabilities()?.files_sharing?.sharebymail?.enabled === true,
Present in `this.config.isMailShareAllowed`

2024-07-12 11:47 UTC, susnux requested changes, later dismissed
Some comments, but especially a lot of interactive elements / input elements are missing an accessible name, which is a real issue.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +				throw new OCSForbiddenException('You are not allowed to send mail notifications');
Why is this not translated? (the one above is)

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +					throw new OCSForbiddenException('You are not allowed to send mail notifications');
Same here, why not translated but others are?

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +			aria-labelledby="file-request-dialog-description"
This is not a label but a description, you can use `aria-describedby` here but please use a short descriptive label (the aria label is the accessible name but you use two sentences here as a name).

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				{{ t('files_sharing', 'Collect files from others even if they don\'t have an account.') }}
I am not 100% sure about our guidelines here, but I would think we do not use abbreviations

```suggestion
				{{ t('files_sharing', 'Collect files from others even if they do not have an account.') }}
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +			<span class="dialog__actions-separator" />
I think it would be good to have this clarified as IIRC the Jan wanted all buttons to be on the same side of dialogs separated by color (primary actions vs secondary action) (from when I created the filepicker).
Would be good to have things like this all consistent by design.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +import type { AxiosError } from 'axios'
You can import from `@nextcloud/axios`, no need to mess with eslint disable comments here

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				return this.t('files_sharing', 'Close')
see not above

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				{{ t('files_sharing', 'Where should these files go ?') }}
```suggestion
				{{ t('files_sharing', 'Where should these files go?') }}
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				const destinationInput = form.querySelector('input[name="destination"]') as HTMLInputElement
Always very confusing to mess with elements not part of the component, this makes it hard to find out where this is coming from and prone to break because now this component needs to know about other components templates.
Instead it is recommended to only access the component, e.g. you could expose a `validate` method on the component an call that in this step to let the component handle the validation.

This makes the relationships clear.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +			const shareUrl = generateOcsUrl('apps/files_sharing/api/v1/shares/' + this.share.id)
```suggestion
			const shareUrl = generateOcsUrl('apps/files_sharing/api/v1/shares/{id}', { id: this.share.id })
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +			const shareUrl = generateOcsUrl('apps/files_sharing/api/v1/shares/' + this.share.id + '/send-email')
```suggestion
			const shareUrl = generateOcsUrl('apps/files_sharing/api/v1/shares/{id}/send-email', { id: this.share.id })
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +	:deep(fieldset) {
Is this really needed? You have full control over the components so a `deep` should not be needed here, instead you could just have either shared styles or make it a component for consistent layout (also simplifies by dividing into smaller).

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +	:deep(.dialog__actions) {
see above

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +		color: var(--color-text-maxcontrast);
not resolved

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +					:label-outside="true"
I do not see any linked the label?

I think it would be better to just add the "inside" label here, could be simple as `Password`.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +			<legend>{{ t('files_sharing', 'What password should be used for the request ?') }}</legend>
```suggestion
			<legend>{{ t('files_sharing', 'What password should be used for the request?') }}</legend>
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +				id="file-request-dialog-expirationDate"
unused id?

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +				:hide-label="true"
I do not see any label? This needs to have either a linked label or just use the inline one

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogFinish.vue
> +				<IconClipboard v-else :size="20" @click="copyShareLink" />
```suggestion
				<IconCheck v-if="isCopied" :size="20" />
				<IconClipboard v-else :size="20" />
```

No interaction listeners on non interactive elements.
This should be done in `copyShareLink`

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogFinish.vue
> +				:label="t('files_sharing', 'Send link via email')"
```suggestion
				:label="t('files_sharing', 'Recipients email address')"
```

or just `Email address` or similar, as this label currently sounds like a checkbox instead of an address input

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogFinish.vue
> +			return window.location.protocol + '//' + window.location.host + generateUrl('/s/') + this.share.token
```suggestion
			return generateUrl('/s/{token}', { token: this.share.token }, { baseURL: getBaseUrl() })
```

(`getBaseUrl` from `@nextcloud/router`)

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogFinish.vue
> +		},
Really going into that rabbit hole? I am pretty sure this does not cover all valid cases.
We validate on server properly so I think we can just use something that validates that it is roughly an email like `/[^@]+@[^@]+\.[a-z]{2,}/` (this covers all valid emails except for local (without TLD) and for quoted `@` in name part.

But feel free to ignor this :)

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
Where is the label? The `legend` is not automatically associated with the input but with the fieldset.
So the fieldset has a name, but the input does not. Both need an accessible name.

Maybe add at least an `aria-label` like `Request subject`.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				{{ t('files_sharing', 'What are you requesting ?') }}
```suggestion
				{{ t('files_sharing', 'What are you requesting?') }}
```

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
Same here no accessible name.

2024-07-12 11:47 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
Same here no accessible name

2024-07-12 12:52 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		?string $sendMail = null
No, it doesn't work. See other legacy values like `$hideDownload` or `$publicUpload`, they need to be string for god knows why.
I don't want to change those areas as well. I'll be consistent with the legacy implementation for now :)

2024-07-12 13:03 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				const destinationInput = form.querySelector('input[name="destination"]') as HTMLInputElement
I'd say, for an input component with a name attribute, `input[name="destination"] is a pretty clean approach.
I ain't gonna rewrite a `validate` implementation on the nextcloud vue components. That would mean we have to do it for like 5+ different components which are far out of scope here

2024-07-12 13:05 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				{{ t('files_sharing', 'Collect files from others even if they don\'t have an account.') }}
That sentence came right from Jan. I'll adjust anyway, no big deal

2024-07-12 13:28 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				:aria-label="t('files_sharing', 'Continue')"
Just to note: You do not need aria labels if the button already has text (it does not hurt, but if the button has text the aria label should never be different from the text so it makes it easier to only maintain on location).

2024-07-12 13:29 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				{{ t('files_sharing', 'Previous') }}
Visual and accessible name differ, this is an accessibility issue.

2024-07-12 13:30 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +				id="file-request-dialog-expirationDate"
oh.

2024-07-12 13:31 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +				:hide-label="true"
```suggestion
				:hide-label="true"
				:label="t('files_sharing', 'Expiration date')"
```

2024-07-12 13:33 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogDatePassword.vue
> +					:label-outside="true"
```suggestion
					:label="t('files_sharing', 'Password')"
```

or 

```suggestion
					:aria-label="t('files_sharing', 'Password')"
```

2024-07-12 13:33 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				{{ t('files_sharing', 'Previous') }}
Noted for followup! :+1: 
Thanks

2024-07-12 13:35 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
```suggestion
				:label="t('files_sharing', 'Request subject')"
```

or

```suggestion
				:aria-label="t('files_sharing', 'Request subject')"
				:label-outside="true"
```

2024-07-12 13:37 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
```suggestion
				:label="t('files_sharing', 'Upload destination')"
```

or

```suggestion
				:aria-label="t('files_sharing', 'Upload destination')"
				:label-outside="true"
```

2024-07-12 13:38 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog/NewFileRequestDialogIntro.vue
> +				:label-outside="true"
```suggestion
				:label="t('files_sharing', 'Note for recipient')"
```

or

```suggestion
				:aria-label="t('files_sharing', 'Note for recipient')"
				:label-outside="true"
```

2024-07-12 13:39 UTC, susnux commented
List of accessibility bugs I think that needs to be resolved before  (unrelated to design or code style or other):
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675905122
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675928843
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675932604
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675935792
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675716753
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675939663
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675942342
- [ ] https://github.com/nextcloud/server/pull/46007/files#r1675944287

2024-07-12 13:45 UTC, susnux commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +				{{ t('files_sharing', 'Previous') }}
Simple:

```suggestion
				{{ t('files_sharing', 'Previous step') }}
```

2024-07-12 14:19 UTC, nfebe approved these changes

2024-07-12 14:21 UTC, susnux approved these changes
thank you so much!

2024-07-12 18:35 UTC, merged

2024-07-18 10:16 UTC, nickvergessen commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
@skjnldsv Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(escpecially this "breakage", but also all changes in lib/public/ (even if you type only))

2024-07-18 13:34 UTC, skjnldsv commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
![image](https://github.com/user-attachments/assets/5c52d9a7-8949-4b08-ac86-08dd6c27edea)

2024-07-18 14:19 UTC, juliushaertl commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
Also FYI @tobiasKaminsky since this is actually used when you want to set the attribute through the OCS API.

2024-07-19 07:16 UTC, tobiasKaminsky commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
which attribute? :see_no_evil:

2024-07-19 09:09 UTC, juliushaertl commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
Share attributes for the "Allow download" option on internal shares, not sure if clients make use of that

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-share-api.html#share-attributes

<img width="347" alt="Screenshot 2024-07-19 at 11 07 33" src="https://github.com/user-attachments/assets/b9d065b8-367e-497c-9438-faa29154b855">

2024-07-19 11:42 UTC, skjnldsv commented on lib/public/Share/IAttributes.php
> +	 * @since 30.0.0, `enabled` was renamed to `value`
https://github.com/nextcloud/documentation/pull/12043