feat(cache): CLI should not fail on missing memcache
nextcloud/server pull request #46151
Opened 2024-06-26 22:25 UTC by MichaIng

* Resolves: #27608

## Summary
but fallback to NullCache. This can be the case if APCu is used without `apc.enable_cli=1`. APCu (and ArrayCache) however runs within the PHP instance and hence cannot be shared between CLI and web or used as distributed cache. The CLI call can hence only create or invalidate entries for itself. For short-living CLI calls, this is theoretically a downsides regarding performance and resource usage, and Nextcloud must not have any issues using the dummy NullCache instead of an isolated freshly created and destroyed APCu or ArrayCache instance.

This partly reverts https://github.com/nextcloud/server/pull/25770. The fallback was removed, because CLI calls started to hang after https://github.com/nextcloud/server/pull/25440. The reason however was not that a cache is generally required for CLI calls, but because the previously logged warning invoked the user backend, which invoked again the caching backend, causing a loop.

This commit re-adds the fallback without logging a warning. For mentioned reasons, it is okay to fallback to NullCache silently.

The motivation is to make `apc.enable_cli=1` optional, and that hence the documentation about it can be removed. We should not enforce admins to enable APCu for CLI calls, which is reasonably disabled by default. This also reduces requirements for hosting providers to support Nextcloud.
__________________
Since APCu and ArrayCache for the web instance cannot be invalidated from CLI, the documentation could mention this instead. Theoretically, config changes, Nextcloud or app upgrades can require a local cache invalidation. Hence, in case one faces issues, a PHP server restart could be required. The same is true when OPcache revalidation time is long or has been disabled. This PR however does not chance anything about this fact.

## TODO

- [ ] Remove/Replace `apc.enable_cli=1` warning about from documentation: https://docs.nextcloud.com/server/29/admin_manual/configuration_server/caching_configuration.html#id1

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-06-27 08:47 UTC, nickvergessen requested changes
I'm fine when you limit this to APCu.
But Redis and others should fail hard on CLI as well when they are not working properly.

2024-06-30 15:54 UTC, MichaIng commented
Makes sense. If Redis, memcached or ArrayCache fail, there is a general issue. Also they all do not need to be "created" for a CLI instance, the ArrayCache really is just a PHP array that does not consume any memory when not filled.

2024-07-01 04:51 UTC, nickvergessen commented on lib/private/Memcache/Factory.php
> +				$localCacheClass = self::NULL_CACHE;
Wouldn't ARRAY_CACHE be better? Could still help in cron and occ commands?

2024-07-01 14:13 UTC, MichaIng commented on lib/private/Memcache/Factory.php
> +				$localCacheClass = self::NULL_CACHE;
Not sure. The question is whether cache entries created by typical cron/occ jobs are also reused by them within the same call. Otherwise, ArrayCache would just cause a raising memory usage (based with cache entries are created) without a performance benefit.

Checking my instance, most entries seem to be web UI related. Maybe someone has more insights or examples of apps/cron/occ jobs which are reusing cache content more often. But I guess this is not the case, and all a CLI ArrayCache would do is raising memory usage, while it runs.

2024-07-11 04:38 UTC, nickvergessen approved these changes

2024-08-01 08:03 UTC, AndyScherzinger commented
🏓 @st3iny since requested for 2nd review 😃

2024-10-29 14:28 UTC, skjnldsv approved these changes
:elephant:

2024-10-29 14:28 UTC, merged

2024-10-29 15:38 UTC, MichaIng commented
Docs update: #12332