better handling of preview generation errors
nextcloud/server pull request #4620
Opened 2017-05-01 12:24 UTC by icewind1991

Prevents failing hard when working with corrupted images

2017-05-01 15:47 UTC, MorrisJobke commented
Makes sense but I could not verify that it failed before. I took a document and renamed it to .png and triggered the occ preview:generate-all - before and after there is no error.

2017-05-01 20:05 UTC, icewind1991 commented
You need an actual corrupted image, not just a wrongly named one

2017-05-01 20:26 UTC, rullzer approved these changes
Makes sense!

2017-05-01 21:01 UTC, MorrisJobke commented
> You need an actual corrupted image, not just a wrongly named one

Do you have one?

2017-05-01 21:48 UTC, MorrisJobke commented
I also added some error handling for the other endpoints that uses that method.

2017-05-01 21:48 UTC, MorrisJobke approved these changes

2017-05-02 11:41 UTC, rullzer requested changes

2017-05-02 11:41 UTC, rullzer commented on lib/private/Preview/Generator.php
> +		if (!$preview->valid()) {
Shouldn't this be moved up?  Like right after the getImage call?

2017-05-02 11:44 UTC, icewind1991 commented on lib/private/Preview/Generator.php
> +		if (!$preview->valid()) {
done

2017-05-02 19:49 UTC, rullzer approved these changes

2017-05-02 19:49 UTC, merged