fix permissions of mountpoints
nextcloud/server pull request #4623
Opened 2017-05-01 13:38 UTC by icewind1991

Properly prevent people from moving/renaming mountpoints

2017-05-01 14:51 UTC, LukasReschke commented
Does this fix https://github.com/nextcloud/groupfolders/issues/7? Any more information would be appreciated. Thanks.

2017-05-01 20:00 UTC, rullzer requested changes

2017-05-01 20:03 UTC, icewind1991 commented on lib/private/Files/View.php
> +					$data['permissions'] = $data['permissions'] & (\OCP\Constants::PERMISSION_ALL - (\OCP\Constants::PERMISSION_UPDATE | \OCP\Constants::PERMISSION_DELETE));
This was copied from `getFolderContents` I can change both

2017-05-01 20:04 UTC, icewind1991 commented
> Does this fix nextcloud/groupfolders#7? Any more information would be appreciated. Thanks.

Yes, but it still shows rename/move as option in the ui, will have to look into that issue seperate

2017-05-02 20:04 UTC, rullzer commented on lib/private/Files/View.php
> +					$data['permissions'] = $data['permissions'] & (\OCP\Constants::PERMISSION_ALL - (\OCP\Constants::PERMISSION_UPDATE | \OCP\Constants::PERMISSION_DELETE));
Ah well leave as is for now then.

2017-05-02 20:05 UTC, rullzer approved these changes

2017-05-02 20:28 UTC, MorrisJobke approved these changes

2017-05-02 20:28 UTC, merged

2017-05-04 03:10 UTC, MorrisJobke commented
Reverted in #4684 

@icewind1991 Please have a loot at this.

2017-05-04 03:10 UTC, MorrisJobke commented
@LukasReschke FYI regarding release stuff.

2017-05-06 07:06 UTC, LukasReschke commented
:-/