allow using the full height of the header for the logo
nextcloud/server pull request #4633
Opened 2017-05-01 17:18 UTC by icewind1991

Before

![image](https://cloud.githubusercontent.com/assets/1283854/25587095/cbe53a6e-2ea2-11e7-8597-f0265054c832.png)

After

![image](https://cloud.githubusercontent.com/assets/1283854/25587099/d3b7ee6c-2ea2-11e7-9e8c-04718ce7cd58.png)

The stock logo will still have the same size since that one is also limited by width

2017-05-01 19:18 UTC, MorrisJobke commented
cc @nextcloud/designers

2017-05-01 21:24 UTC, MorrisJobke commented
The Nextcloud logo stays the same in size and the branded one looks like this (before and after)

![bildschirmfoto 2017-05-01 um 18 20 35](https://cloud.githubusercontent.com/assets/245432/25595527/65949004-2e9b-11e7-9c32-a06ca778beb9.png)
![bildschirmfoto 2017-05-01 um 18 24 11](https://cloud.githubusercontent.com/assets/245432/25595528/65e17496-2e9b-11e7-8905-07bbb22d479a.png)


I think it's okay to reduce the padding. It allows more flexibility what to show there.

2017-05-01 21:25 UTC, MorrisJobke approved these changes

2017-05-02 13:46 UTC, jancborchardt requested changes
I’m a bit skeptical here … the logo seems to be so small only because you have a bunch of padding, no? In @MorrisJobke’s test it becomes apparent that using the full height can result in a very ugly header, and we don’t want people to accidentally have ugly themes.

2017-05-02 14:01 UTC, MorrisJobke commented
> I’m a bit skeptical here … the logo seems to be so small only because you have a bunch of padding, no? In @MorrisJobke’s test it becomes apparent that using the full height can result in a very ugly header, and we don’t want people to accidentally have ugly themes.

I also thought about this. So we just say: remove the padding from the logo and use the CSS padding. Fine by me too.

Let's close this here then.

2017-05-02 14:01 UTC, closed without merging