feat(Reference): Add public API endpoints to get references
nextcloud/server pull request #46378
Opened 2024-07-09 16:18 UTC by mejo-

Calling the public API endpoints will check for matching registered reference providers that implement `IPublicReferenceProvider` and call their respective functions. If no matching provider is found, the default `LinkReferenceProvider` will be used to provide open graph data.

The frontend reference widget components will call these endpoints from unauthorized sessions, e.g. in public shares.

The origin URL is passed to `resolveReferencePublic()` as additional information for the reference provider to determine the access scope. Since the main usecase will be public shares, the origin URL will contain the share token (e.g. Talk, Collectives or Text documents), so the respective reference providers can determine whether the share has access to the linked resource.

`getCacheKeyPublic` also gets the origin URL so it can scope the cached entry, e.g. to the share token.

Contributes to #45978

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-09 16:32 UTC, juliushaertl reviewed
Haven't tested yet but looks good from a first read

2024-07-09 16:32 UTC, juliushaertl commented on core/Controller/ReferenceApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/extractPublic', root: '/references')]
We should have some rate limit on that as well

2024-07-09 16:36 UTC, mejo- commented on core/Controller/ReferenceApiController.php
> +	public function resolveOnePublic(string $reference, string $origin): DataResponse {
I'm a bit unsure about passing the origin URL as additional information. While it should usually contain the share token, every reference provider has to implement their own logic to extract the share token from it then, and every reference provider would have to support different origin URL formats anyway, to support resolving target URLs within the same share but in another app.

E.g. when referencing a Collectives share link within the same share from Files, the Collectives reference provider would need to parse the origin URL for file sharing and collectives sharing link format.

Maybe a better approach is to expect the share token as parameter to the public API calls instead of `origin` and let the frontend extract the sharing token from `document`. In other words, `NcReferenceList` would do something like `const shareToken = document.getElementById('sharingToken').value` and all apps implementing public share pages would need to make sure this element exists.

2024-07-10 09:53 UTC, mejo- commented on core/Controller/ReferenceApiController.php
> +	public function resolveOnePublic(string $reference, string $origin): DataResponse {
As discussed with @juliushaertl, implemented this now.

2024-07-10 09:55 UTC, mejo- commented on core/Controller/ReferenceApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/extractPublic', root: '/references')]
Indeed, fixed now.

2024-07-16 17:20 UTC, juliushaertl approved these changes

2024-07-17 10:18 UTC, max-nextcloud requested changes
One comment that will need to be addressed I think.

2024-07-17 10:18 UTC, max-nextcloud commented on lib/private/Collaboration/Reference/ReferenceManager.php
> +			$reference = $matchedProvider->resolveReferencePublic($referenceId, $sharingToken);
![grafik](https://github.com/user-attachments/assets/40e6b6a8-8929-49ae-ae52-b328e09b941a)
Is fixed.

2024-07-17 10:18 UTC, max-nextcloud commented on core/Controller/ReferenceApiController.php
> +	public function extractPublic(string $text, string $sharingToken, bool $resolve = false, int $limit = 1): DataResponse {
You are rate limiting here - which is good. But at the same time you allow resolving aka requesting a large number of resources in a single request, right?
There seems to be no limit to `limit`. Are we using more than 1 anyway? What's the highest limit we actually use?

2024-07-17 10:18 UTC, max-nextcloud commented on core/Controller/ReferenceApiController.php
> +	public function resolvePublic(array $references, string $sharingToken, int $limit = 1): DataResponse {
Same as above. Would be good to have a limit for limit.

2024-07-17 10:57 UTC, mejo- commented on core/Controller/ReferenceApiController.php
> +	public function extractPublic(string $text, string $sharingToken, bool $resolve = false, int $limit = 1): DataResponse {
Good catch. Limited `$limit` to maximum 15 now in public endpoints.

2024-07-17 12:16 UTC, max-nextcloud approved these changes

2024-07-17 12:35 UTC, merged

2024-07-18 10:04 UTC, nickvergessen commented on lib/public/Collaboration/Reference/IPublicReferenceProvider.php
> +interface IPublicReferenceProvider extends IReferenceProvider {
@mejo- Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(also all other API additions/changes in lib/public/)

2024-07-18 13:12 UTC, mejo- commented on lib/public/Collaboration/Reference/IPublicReferenceProvider.php
> +interface IPublicReferenceProvider extends IReferenceProvider {
Done so now in https://github.com/nextcloud/documentation/pull/12037. The HTTP API additions got already documented with https://github.com/nextcloud/documentation/pull/12030

2024-07-22 09:23 UTC, julien-nc reviewed
A bit late to the party... LGTM

2024-07-22 09:23 UTC, julien-nc commented on lib/public/Collaboration/Reference/LinkReferenceProvider.php
> +class LinkReferenceProvider implements IReferenceProvider, IPublicReferenceProvider {
`IPublicReferenceProvider` extends `IReferenceProvider` so `LinkReferenceProvider` could just extend `IPublicReferenceProvider`, right?