feat(security): restrict admin actions to IP ranges
nextcloud/server pull request #46473
Opened 2024-07-12 14:28 UTC by Altahrim

## Summary
Restrict admin actions to IP ranges
When administrator IP address is not in specified range, all admin actions are hidden/forbidden.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-12 14:44 UTC, kesselb commented on lib/private/AppFramework/Middleware/Security/Exceptions/AdminIpNotAllowedException.php
> + */
```suggestion
/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
```

2024-07-12 15:48 UTC, solracsf commented on lib/private/Security/RemoteIpAddress.php
> +		if (false === $allowedAdminRanges = $this->config->getSystemValue('allowed_admin_ranges', false)) {
```suggestion
		if (false === $allowedAdminRanges = $this->config->getSystemValueBool('allowed_admin_ranges', false)) {
```

2024-07-15 07:59 UTC, nickvergessen requested changes
No in-if assignments please

2024-07-15 07:59 UTC, nickvergessen commented on lib/private/Security/RemoteIpAddress.php
> +		if (false === $allowedAdminRanges = $this->config->getSystemValue('allowed_admin_ranges', false)) {
```suggestion
		$allowedAdminRanges = $this->config->getSystemValue('allowed_admin_ranges', false)
		if (allowedAdminRanges === false) {
```

2024-07-15 07:59 UTC, nickvergessen commented on lib/private/Security/RemoteIpAddress.php
> +		if (count($allowedAdminRanges) === 0) {
```suggestion
		if (empty($allowedAdminRanges)) {
```

2024-07-15 14:28 UTC, Altahrim commented on lib/private/Security/RemoteIpAddress.php
> +		if (count($allowedAdminRanges) === 0) {
Why this one?

2024-07-16 08:54 UTC, Altahrim commented on lib/private/Security/RemoteIpAddress.php
> +		if (false === $allowedAdminRanges = $this->config->getSystemValue('allowed_admin_ranges', false)) {
We could probably automate this: https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php

2024-07-17 11:30 UTC, nickvergessen commented on lib/private/Security/RemoteIpAddress.php
> +		if (count($allowedAdminRanges) === 0) {
Micro-optimization. Don't count if you just want to know it if's empty.

2024-07-17 11:31 UTC, nickvergessen commented on lib/private/Security/RemoteIpAddress.php
> +		if (false === $allowedAdminRanges = $this->config->getSystemValue('allowed_admin_ranges', false)) {
Well, we want to allow `while ($row = $query->fetch())` but basically nothing else :see_no_evil:

2024-07-17 11:33 UTC, nickvergessen approved these changes
Definitely needs documentation, so that other "admin alike endpoints" are aware and can integrate it and use `IGroupManager::isAdmin()` instead of checking for the admin group.

2024-07-19 13:58 UTC, joshtrichards commented
Related open issues this PR may close: #29294 & #38609

2024-07-19 14:06 UTC, nickvergessen commented on lib/private/Server.php
> +		$this->registerAlias(\OCP\Security\Ip\Factory::class, \OC\Security\Ip\Factory::class);
```suggestion
		$this->registerAlias(\OCP\Security\Ip\IFactory::class, \OC\Security\Ip\Factory::class);
```

2024-07-19 14:09 UTC, nickvergessen requested changes

2024-07-19 14:09 UTC, nickvergessen commented on lib/public/Security/Ip/IFactory.php
> +	 * @throws on invalid range
```suggestion
	 * @throws \InvalidArgumentException on invalid range
```

2024-07-19 14:09 UTC, nickvergessen commented on lib/public/Security/Ip/IFactory.php
> +	 * @throws on invalid IP
```suggestion
	 * @throws \InvalidArgumentException on invalid IP
```

2024-07-19 14:09 UTC, nickvergessen commented on lib/private/Security/Ip/RemoteAddress.php
> +	public function matches(IRange... $ranges): bool {
those could be removed now as they are no longer used?

2024-07-19 14:09 UTC, nickvergessen commented on lib/private/Security/Ip/RemoteAddress.php
> +	}
Also this?

2024-07-19 14:09 UTC, nickvergessen commented on lib/private/Server.php
> +		$this->registerAlias(\OCP\Security\Ip\Factory::class, \OC\Security\Ip\Factory::class);
```suggestion
		$this->registerAlias(\OCP\Security\Ip\IFactory::class, \OC\Security\Ip\Factory::class);

2024-07-19 14:43 UTC, Altahrim commented on lib/private/Security/Ip/RemoteAddress.php
> +	public function matches(IRange... $ranges): bool {
This is part of the interface so RemoteAddress can be used as a IAddress, not sure if it's best to remove it or not

2024-07-22 06:40 UTC, nickvergessen approved these changes

2024-07-22 07:43 UTC, sorbaugh approved these changes

2024-07-22 08:10 UTC, merged

2024-07-22 08:39 UTC, szaimen commented
Hi, I wonder, would it make sense to document this under https://docs.nextcloud.com/server/latest/admin_manual/installation/harden_server.html?

2024-07-24 09:20 UTC, Altahrim commented
Added here: https://github.com/nextcloud/documentation/pull/12059