Migration Attributes
nextcloud/server pull request #46476
Opened 2024-07-12 20:33 UTC by ArtificialOwl

2024-07-15 07:37 UTC, ChristophWurst commented on lib/public/Migration/Attributes/MigrationWeight.php
> +	case HEAVY = 'heavy'; // migration is estimated to be heavy and time consuming
This is out of scope. We don't want to guess this. We don't know if adding a column is light or heavy.

2024-07-15 07:40 UTC, ChristophWurst commented
> * `TableCreation`
> 
> * `TableDeletion`
> 
> * `FieldAdd`
> 
> * `FieldChange`
> 
> * `FieldRemove`
> 
> * `IndexAdd`
> 
> * `IndexRemove`

Ease the naming and avoid ambiguity by using standard sql terms

* CreateTable
* DeleteTable
* AddColumn
* ModifyColumn (consider more specific attributes for type change, rename, etc)
* DropColumn
* AddIndex
* DropIndex

2024-07-15 13:04 UTC, ArtificialOwl commented on lib/public/Migration/Attributes/MigrationWeight.php
> +	case HEAVY = 'heavy'; // migration is estimated to be heavy and time consuming
_removed_

2024-07-18 11:43 UTC, ChristophWurst commented on lib/public/Migration/Attributes/TableMigrationAttribute.php
> +		string $table = '',
```suggestion
		string $table,
```

table migrations without a name are impossible. the table name has to be mandatory

2024-07-18 11:43 UTC, ChristophWurst commented on lib/public/Migration/Exceptions/AttributeException.php
> +class AttributeException extends Exception {
this is only used internally, move to oc

2024-07-19 05:48 UTC, ChristophWurst commented
@AndyScherzinger this does not close https://github.com/nextcloud/server/issues/45943. It's the first of five changes

2024-07-19 05:53 UTC, ChristophWurst requested changes
* All new classes, their methods and properties require `@since 30.0.0`
* All new classes require unit test coverage

2024-07-19 05:53 UTC, ChristophWurst commented on lib/public/Migration/Attributes/DeleteTable.php
> +class DeleteTable extends MigrationAttribute {
```suggestion
class DropTable extends MigrationAttribute {
```

2024-07-19 05:53 UTC, ChristophWurst commented on lib/public/Migration/Attributes/IndexType.php
> +	case UNIQUE = 'unique'; // migration should be light and quick
we don't want to estimate

2024-07-26 13:58 UTC, ArtificialOwl commented on lib/public/Migration/Attributes/TableMigrationAttribute.php
> +		string $table = '',
should be make it mandatory for any migration attribute ?

2024-07-26 14:09 UTC, ChristophWurst commented on lib/public/Migration/Attributes/TableMigrationAttribute.php
> +		string $table = '',
Yes

2024-07-29 11:54 UTC, ChristophWurst commented on lib/public/Migration/Attributes/MigrationAttribute.php
> +	 * @param array $notes notes about the migration
@since is not inherited. You have to add it to *all* methods

2024-07-29 11:56 UTC, ArtificialOwl commented on lib/public/Migration/Attributes/MigrationAttribute.php
> +	 * @param array $notes notes about the migration
oups!

2024-07-29 12:47 UTC, ArtificialOwl commented
_psalm error not related: https://github.com/nextcloud/server/pull/46846_

2024-07-29 13:07 UTC, ArtificialOwl commented
when using an install made from repository (with apps/testing/ available):

**generate metadata from current install:**
>     ./occ migrations:generate-metadata > /tmp/nc.metadata

**enable testing app:**
>     ./occ app:enable testing

**delete migration from db:**
>     DELETE FROM oc_migrations WHERE `oc_migrations`.`app` = 'testing' AND `oc_migrations`.`version` = '30000Date20240102030405'

**preview _future_ migrations:**
>     ./occ migrations:preview /tmp/nc.metadata     


_result:_
![image](https://github.com/user-attachments/assets/74960d48-b21b-4a37-9149-23eaae5b0fcb)

2024-07-30 13:08 UTC, ChristophWurst approved these changes
Attributes look good

2024-07-30 13:33 UTC, sorbaugh approved these changes

2024-07-30 13:54 UTC, merged

2024-07-30 16:56 UTC, ArtificialOwl commented
/backport to stable29

2025-08-29 05:37 UTC, ChristophWurst commented
<img width="1506" height="1002" alt="image" src="https://github.com/user-attachments/assets/4abf9dcd-a5d7-4d5a-84fb-3e981afc8058" />

Developer docs were updated but admin docs are still missing