Fix for missing Rich Link Preview
nextcloud/server pull request #4648
Opened 2017-05-01 23:32 UTC by newhinton

Those commits should add the missing information for rich link previews in apps and social media link previews

2017-05-02 11:15 UTC, ChristophWurst commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
I think this should be escaped somehow, e.g. quotes in the title or slogan could mess up the HTML otherwise.

2017-05-06 07:13 UTC, LukasReschke commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
Mhm? `p()` already escapes :-)

2017-05-06 07:25 UTC, ChristophWurst commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
right… nvm

2017-05-08 08:38 UTC, juliusknorr requested changes

2017-05-08 08:38 UTC, juliushaertl commented on core/templates/layout.user.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
Do we need this in the layout.user.php file? This file will not be crawled by any of the services since it requires login, right?

2017-05-08 08:38 UTC, juliushaertl commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
apps/files_sharing/lib/Controller/ShareController.php is already setting opengraph headers. Those should not be doubled. :wink:

2017-05-08 08:39 UTC, juliushaertl commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareController.php#L403-L409

2017-05-16 18:40 UTC, jancborchardt commented on core/templates/layout.base.php
> +		<meta property="og:description" content="<?php p($theme->getTitle()); p(" - ");  p($theme->getSlogan()); ?>"/>
@newhinton can you fix this? :)

2017-07-03 18:27 UTC, jancborchardt commented
@newhinton any update here? :) @ChristophWurst @juliushaertl maybe we should complete this fix so we get it in?

2017-07-11 21:38 UTC, juliushaertl commented
I'll check that out.

2017-07-11 21:59 UTC, newhinton commented
Sorry, but i dont have time to find out how to add those headers properly :/

2017-09-02 14:39 UTC, juliushaertl commented
Closing this in favour of #6342. Thanks @newhinton for the initial effort.

2017-09-02 14:39 UTC, closed without merging