feat(preview): introducing new class ImaginaryPDF
nextcloud/server pull request #46508
Opened 2024-07-13 11:31 UTC by ernolf

* Resolves: #42175

* Replaces: #46447

## Summary
Document previews often appear as minimal, almost blank "miniatures" that can inadvertently reveal content, which may not always be desired.
Many users prefer having document icons instead of these previews.
The classic preview provider settings have considered this preference.

feat: Add separate provider for Imaginary PDF handling

- Refactor Imaginary to handle only image mimetypes.
- Introduce ImaginaryPDF class to handle PDF mimetypes.
- Register ImaginaryPDF in PreviewManager.

This allows for more granular control over which mimetypes are processed by Imaginary.

The approach from #46447 was too cumbersome and deviated too much from the uniform handling of preview providers. This approach has now fully implemented the suggestions and ideas from there.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-15 08:42 UTC, kesselb commented on lib/private/PreviewManager.php
> +		$this->registerCoreProvider(Preview\ImaginaryPDF::class, '/application\/pdf/');
```suggestion
		$this->registerCoreProvider(Preview\ImaginaryPDF::class, Preview\ImaginaryPDF::supportedMimeTypes());
```

2024-07-15 11:30 UTC, ernolf commented
> The rebase went bad

Yes. Fixed. Sory for the noise.

2024-07-15 11:31 UTC, ernolf commented on lib/private/PreviewManager.php
> +		$this->registerCoreProvider(Preview\ImaginaryPDF::class, '/application\/pdf/');
[c2b2045](https://github.com/nextcloud/server/pull/46508/commits/c2b20453e47bab0e4d01c6829cf06d30e2efadb2)

2024-07-17 08:28 UTC, kesselb requested changes

2024-07-17 08:28 UTC, kesselb commented on lib/private/Preview/ImaginaryPDF.php
> +	public function getMimeType(): string {
```suggestion
	public static function supportedMimeTypes(): string
```

It won't work otherwise.

2024-07-17 08:29 UTC, kesselb commented
Please revert all changes to the autoloaders in `apps/`

2024-07-17 17:08 UTC, ernolf commented on lib/private/Preview/ImaginaryPDF.php
> +	public function getMimeType(): string {
9f48093b7bf23b9b3f80858528ef9b9fb62b0e7d

> It won't work otherwise.

Yes. Because of a41ed809f9c10c9532e974af95911933ded047c3 😉

2024-07-22 09:18 UTC, szaimen reviewed
an illustrator file is basically also only a pdf file, so should probably be included the imaginarypdf as well I guess

2024-07-22 09:18 UTC, szaimen commented on lib/private/Preview/Imaginary.php
> +		return '/(image\/(bmp|x-bitmap|png|jpeg|gif|heic|heif|svg\+xml|tiff|webp)|application\/illustrator)/';
```suggestion
		return '/(image\/(bmp|x-bitmap|png|jpeg|gif|heic|heif|svg\+xml|tiff|webp)/';
```

2024-07-22 09:18 UTC, szaimen commented on lib/private/Preview/ImaginaryPDF.php
> +		return '/application\/pdf/';
```suggestion
		return '/application\/(illustrator|pdf)/';
```

2024-07-25 11:50 UTC, ernolf commented
> an illustrator file is basically also only a pdf file, so should probably be included the imaginarypdf as well I guess

Did you read https://github.com/nextcloud/server/pull/46447#issuecomment-2226867819

I wouldn't classify Illustrator files as PDF files, they are more like (non text-)postscript files, which are of course all very closely related. In the narrowest sense, they are vector-based graphics. What convinced me not to include them in PDF is that they have the file extension .ai and not .pdf and therefore are not assigned a unique icon in Nextcloud like is the case with PDF.
I'm happy to be convinced otherwise, but I personally know .ai files as a graphic element that is used (among other) in PDF files.
It would be possible to add an additional class ImaginaryIllustrator instead, but then the same question would arise as with all other MIME types.

Mi aim was to clearly devide pure PDF documents - they have a good Icon which is way better than any preview thumb - from other, not (pure PDF) documents.

2024-07-25 11:58 UTC, szaimen commented
> Did you read [#46447 (comment)](https://github.com/nextcloud/server/pull/46447#issuecomment-2226867819)

No I havent.

> I wouldn't classify Illustrator files as PDF files, they are more like (non text-)postscript files, which are of course all very closely related. In the narrowest sense, they are vector-based graphics. What convinced me not to include them in PDF is that they have the file extension .ai and not .pdf and therefore are not assigned a unique icon in Nextcloud like is the case with PDF. I'm happy to be convinced otherwise, but I personally know .ai files as a graphic element that is used (among other) in PDF files. It would be possible to add an additional class ImaginaryIllustrator instead, but then the same question would arise as with all other MIME types.
> 
> My aim was to clearly devide pure PDF documents - they have a good Icon which is way better than any preview thumb - from other, not (pure PDF) documents.

Fine by me then 👍

2024-07-25 11:59 UTC, szaimen approved these changes
LGTM but didnt test

2024-07-25 15:05 UTC, kesselb commented
Thank you! 

I rebased your pr, updated the autoloaders again and squashed the commits.

2024-07-25 15:05 UTC, kesselb approved these changes

2024-07-25 21:17 UTC, merged

2024-07-25 21:39 UTC, kesselb commented
Docs: https://github.com/nextcloud/documentation/pull/12061