feat: Add folder tree to sidebar
nextcloud/server pull request #46596
Opened 2024-07-18 02:00 UTC by Pytal

## Summary

- Resolves https://github.com/nextcloud/server/issues/15253

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-25 10:22 UTC, artonge commented on apps/files/src/services/FolderTree.ts
> +		return `${folderTreeId}-${mountType}-${folder.attributes.parentid}` // Include mount type as fileids may conflict across storage mounts
You could also have two files with the same id from the same kind of mount, no?

2024-07-25 10:22 UTC, artonge commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const PARENTID_PROPERTYNAME = '{http://nextcloud.org/ns}parentid';
I don't understand why this is needed

2024-07-25 10:22 UTC, artonge commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
Could contain a very large list of folders, so would increase the response size. And most of the content won't be needed. Have you considered fetching the need folder list from the frontend?

2024-07-25 16:16 UTC, Pytal commented on apps/files/src/services/FolderTree.ts
> +		return `${folderTreeId}-${mountType}-${folder.attributes.parentid}` // Include mount type as fileids may conflict across storage mounts
Good point, would mount id work?

2024-07-25 16:19 UTC, Pytal commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const PARENTID_PROPERTYNAME = '{http://nextcloud.org/ns}parentid';
We need to provide the parentid and register it as a default dav property so when a node is created i.e. https://github.com/nextcloud/server/blob/d5bb37ab0d872fb4bdb1ec61809c575a46341a25/apps/files/src/services/DropServiceUtils.ts#L139 then the new child view shows up in the tree correctly nested under its parent

2024-07-25 16:28 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
From my measurements on the impact on load time this is negligible. With a few folders the total resource transfer size (compressed) over the network is 4355kB bytes and with 1000 folders it is 4370kB

The time for retrieving the $folderTreeFolders data is 10ms and 50ms for 1000 folders in my testing

2024-07-25 16:35 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
Also better UX to have the tree available immediately instead of it popping up some time after the rest of the navigation is shown

2024-07-25 17:35 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
What about the backend computation time?
We have customers with 1M+ folders, this makes it synchronous. I'm afraid of the performances impact

2024-07-25 17:38 UTC, skjnldsv commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const PARENTID_PROPERTYNAME = '{http://nextcloud.org/ns}parentid';
Can't we just use the path to create the tree?
Do we actually need any ID at all?

2024-07-25 17:39 UTC, susnux commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const PARENTID_PROPERTYNAME = '{http://nextcloud.org/ns}parentid';
Yes especially as files no longer "rely" on fileid but the source, we could simply build the tree using the node source property

2024-07-25 17:40 UTC, skjnldsv requested changes
Blocking, some of the comments are too important imho

2024-07-25 17:43 UTC, susnux reviewed
I am not sure computing the whole list on the backend is a good idea, especially on every request.
Especially as we can have the views collapsed we could instead just load the folders needed for the currently expanded view list

2024-07-25 18:46 UTC, Pytal commented on apps/files/src/components/FileEntry/FileEntryName.vue
> +				emit('files:node:renamed', node)
Will change to `{ newName: string, oldName: string }` 👍

2024-07-25 18:54 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
@icewind1991 do you know of a trick to generate a list of deepest paths from a user folder?

2024-07-25 19:01 UTC, Pytal commented on apps/files/src/services/FolderTree.ts
> +		return `${folderTreeId}-${mountType}-${folder.attributes.parentid}` // Include mount type as fileids may conflict across storage mounts
Changing to use source as discussed :)

2024-07-25 23:51 UTC, Pytal commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +	public const PARENTID_PROPERTYNAME = '{http://nextcloud.org/ns}parentid';
Parent id removed

2024-07-26 09:19 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
What about just implementing this method?

2024-07-26 09:58 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
`apps/files/lib/Controller/ApiController.php`
```php
	/**
	 * Returns a folder tree of the user's files.
	 *
	 * @NoAdminRequired
	 *
	 * @return JSONResponse
	 */
	public function getFolderTree($maxDepth = 10): JSONResponse {
		$depth = 0;
		$nodes = $this->rootFolder->getUserFolder($this->userSession->getUser()->getUID())->getDirectoryListing();

		/**
		 * @param \OCP\Files\Node[] $nodes
		 * @param int $depth
		 * @param int $maxDepth
		 */
		function getChildren(Array $nodes, $depth = 0, $maxDepth = 10): array {
			if ($depth >= $maxDepth) {
				return [];
			}

			$children = [];
			foreach ($nodes as $node) {
				if (!($node instanceof Folder)) {
					continue;
				}

				$children[] = [
					'basename' => basename($node->getPath()),
					'name' => $node->getName(),
					'children' => getChildren($node->getDirectoryListing(), $depth + 1, $maxDepth),
				];
			}
			return $children;
		}

		return new JSONResponse(getChildren($nodes, $depth, $maxDepth));
	}
```

With 2500 folders, a max depth of 10 takes 650ms, which is a lot!
A depth of 5 takes 350ms

2024-07-26 10:13 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
I tried the Search method and it was over 4 times slower (>2.5 seconds)

2024-07-26 12:49 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
Ok, quick brain thrust:
1. Load the page as master currently does
2. Async fetch the file tree and render it on the sidebar
3. Add a user config to disable the file tree

2024-07-26 15:55 UTC, icewind1991 commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
Having a limited-depth endpoint with possible requesting deeper items when navigating the tree seems like the only option that isn't guaranteed to explode on scalability.

2024-07-26 16:02 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
> What about the backend computation time?

Posted above

> 10ms for a few folders and 50ms for 1000 folders

Need to run some more benchmarks

2024-07-26 16:07 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
Will need to run some benchmarks

How did you measure the times @skjnldsv? I will run the same on my system

For the 50ms 1000 folders measurement search I used microtime, and that includes calling $folder getters as well not just the search

2024-07-26 16:11 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
> How did you measure the times @skjnldsv? I will run the same on my system

Called on ocs api endpoint with fetch. It's not php compute, but real request times

2024-07-26 23:51 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
> I tried the Search method to compute the same type of array and it was over 4 times slower (>2.5 seconds)

Tested full request times and getting the opposite with search being 4 times faster, weird... 🤔

2024-07-30 12:36 UTC, icewind1991 commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
which one is faster will be highly dependent on the instance.

Given the performance tradeoffs, my approach would be to have the client only request a single level of the folder structure at a time.

While this does mean that there is a bit of loading every time a folder is expanded, it's the only option that wouldn't cause performance issues imo.

2024-07-30 12:37 UTC, icewind1991 requested changes, later dismissed
(Leaving this as a review to note that I find the performance questions/discussion to be blocking)

2024-07-30 12:53 UTC, skjnldsv commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
@icewind1991 would have been nice sure, but the specifications seems to not have been thoroughly thought with performance in mind. The entire tree is always displayed, there is currently no expectations on when to stop from the initial feature planning (Maybe it's time to think this through now before it bites us later)

2024-07-30 15:49 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
By default the expanded state of each folder is persisted so if 20 folders are expanded then on first load this would mean making 20 separate requests

How about not storing the expanded state of folder tree views specifically then a request is made only when a folder is expanded on click?

2024-07-30 15:58 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
Any of these edge cases can be addressed in separate PRs as we should get a first version in that works for the average instance

2024-07-30 16:03 UTC, sorbaugh commented on apps/files/lib/Controller/ViewController.php
> +			$folders = $userFolder->search($searchQuery);
I think we should really tackle the performance issues but would also do so during the rest of NC30 beta in separate PRs as Pytal suggested to have a working version. 

That means proceeding to merge as soon as we have a stable version.

This way we can already get some field testing and even confirm/disconfirm the concerns. A win-win in my opinion.

2024-07-31 01:26 UTC, Pytal commented on apps/files/lib/Controller/ViewController.php
> +		$this->initialState->provideInitialState('folderTreeFolders', $folderTreeFolders);
Fetching from the frontend now 👍

2024-07-31 02:04 UTC, Pytal commented
@provokateurin the openapi script crashes, maybe you know how to fix it?

2024-08-01 06:02 UTC, skjnldsv commented on apps/files/src/components/FileEntry/FileEntryName.vue
> +					oldSource: `${dirname(this.source.source)}/${oldName}`,
what about just `new`/`old` ?
Or `newSource`/`oldSource` to stay consistent?

2024-08-01 06:03 UTC, skjnldsv commented on apps/files/src/store/viewConfig.ts
> +				}, { params })
why?

2024-08-01 14:21 UTC, skjnldsv approved these changes
Comments to be addresses later :+1:

2024-08-01 15:32 UTC, sorbaugh approved these changes

2024-08-01 16:25 UTC, Pytal commented on apps/files/src/store/viewConfig.ts
> +				}, { params })
Needed as the source is used as the view id but was thinking in GET, adjusted to send view and key as request data now

2024-08-01 18:48 UTC, merged

2024-08-01 18:49 UTC, Pytal commented on apps/files/src/components/FileEntry/FileEntryName.vue
> +					oldSource: `${dirname(this.source.source)}/${oldName}`,
Will do in a followup :)

2024-08-01 20:35 UTC, skjnldsv commented
Congrats :tada: :tada: :tada:

2024-08-01 21:58 UTC, nickvergessen commented
The `#[ApiRoute(verb: 'GET', url: '/api/v1/folder-tree')]` takes down our server and makes browsers freeze.
Had to shortcut it with:
```
		return new JSONResponse([], Http::STATUS_INTERNAL_SERVER_ERROR, [], JSON_FORCE_OBJECT);
```

2024-08-07 10:33 UTC, frake65 commented
> The `#[ApiRoute(verb: 'GET', url: '/api/v1/folder-tree')]` takes down our server and makes browsers freeze. Had to shortcut it with:
> 
> ```
> 		return new JSONResponse([], Http::STATUS_INTERNAL_SERVER_ERROR, [], JSON_FORCE_OBJECT);
> ```

So this works for me. - What exactly should the code in function "getFolderTree()" be doing?

2024-08-07 17:29 UTC, Pytal commented
We are working on optimizing this feature @frake65, though the page might be too unresponsive with very large trees there is an "Enable folder tree" checkbox located in the Files settings dialog which can be toggled per-user and will prevent the endpoint from being called completely

2024-08-08 10:38 UTC, frake65 commented
Have removed the shortcut and am now using the toggle.
Sorry to say, but this implementation seems to be still buggy to me - not only slow:
From a users view point at this time I get a file tree, where folder names do not match the folders that they link to at all, but have random names (from sowhere within the file tree).
What should be the order of the folder names by the way? - Alphabetically would be my first guess.

In my opinion probably this feature should be postponed