fix(caldav): fixed initial sync and double processing
nextcloud/server pull request #46623
Opened 2024-07-19 00:28 UTC by SebastianKrupinski

* Resolves: #44127

## Summary
- Initial sync no longer returns deleted items
- fixed double processing of results when doing a follow up sync

2024-07-19 05:34 UTC, ChristophWurst requested changes
* Always use prepared statements with parameters
* Add a test to ``\OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest``

2024-07-19 05:34 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having(new Literal('MAX(operation) < 3'));
```
$qb->expr()->lt(
  $qb->func()->max('operation'),
  $qb->createNamedParameter(3),
)
```

2024-07-19 11:53 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having(new Literal('MAX(operation) < 3'));
Done, I've replaced the Literal with a prepared statement. 

As for the tests OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest already has tests for the getChangesForCalendar function. Its tested 6 times.

2024-07-19 12:21 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having(new Literal('MAX(operation) < 3'));
> As for the tests OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest already has tests for the getChangesForCalendar function. Its tested 6 times.

I mean a test specifically for the initial sync and whether it includes deleted items

2024-07-27 21:59 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having(new Literal('MAX(operation) < 3'));
Done

2024-07-29 11:16 UTC, st3iny reviewed
This is also a (minor) performance optimization as we do `$qb->func()->max('operation')` instead of a busy loop now :+1: 

I'm gonna give this a test but looks good so far.

2024-07-29 11:16 UTC, st3iny commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					// forced (PARAM_INT) is needed for doctriane with Sqlite, for the value to be used as an intager without quotes
```suggestion
					// forced (PARAM_INT) is needed for doctrine with Sqlite, for the value to be used as an integer without quotes
```

2024-07-29 11:16 UTC, st3iny commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having($qb->expr()->lt($qb->func()->max('operation'), $qb->createNamedParameter(3, $qb::PARAM_INT)));
Magic number 3? What does 3 mean in this context?

2024-07-29 11:17 UTC, st3iny commented on apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
> +
```suggestion
```

2024-07-29 11:17 UTC, st3iny commented on apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
> +
```suggestion
```

2024-07-29 11:17 UTC, st3iny commented on apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
> +
```suggestion
```

2024-07-29 15:52 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					->having($qb->expr()->lt($qb->func()->max('operation'), $qb->createNamedParameter(3, $qb::PARAM_INT)));
The magic number is the deleted item operation value. There is no constant defined in the class it's hard coded every where.

2024-07-29 15:54 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalDavBackend.php
> +					// forced (PARAM_INT) is needed for doctriane with Sqlite, for the value to be used as an intager without quotes
Done

2024-07-29 15:58 UTC, SebastianKrupinski commented on apps/dav/tests/unit/CalDAV/AbstractCalDavBackend.php
> +
Done

2024-07-29 16:30 UTC, SebastianKrupinski commented on apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
> +	public function testCalendarSynchronization(): void {
I agree making it easier to see what failed is very helpful. But I think using a custom assert message might be better, that way we don't need to setup multiple tests that do basically the same thing and can group things more logically, less code and less testing time.

How is this for a failure message? The second line.

```
1) OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest::testCalendarSynchronization
Failed test delta sync state with modified/deleted events in calendar
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'syncToken' => 6
     'added' => Array (
-        0 => 'eventVnNOXM4Zb6xvK'
     )
     'modified' => Array (
-        0 => 'eventxuOQWjKl5G5JQ'
     )
     'deleted' => Array (
-        0 => 'eventsQDXnXVcvfN3M'
     )
 )
```

2024-07-30 07:15 UTC, st3iny commented on apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
> +	public function testCalendarSynchronization(): void {
I like the approach :+1:

2024-07-30 08:23 UTC, st3iny requested changes

2024-07-30 08:23 UTC, st3iny commented on apps/dav/lib/CalDAV/CalDavBackend.php
>  					->from('calendarchanges')
This seems dangerous to me. Why do we pull calendar changes on the initial sync?

The problem is that calendar changes are periodically trimmed so the changes table might not contain data about all events.

Shouldn't the initial sync fetch all events from the `calendarobjects` table like before?

2024-07-30 13:55 UTC, miaulalala approved these changes

2024-07-30 17:15 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalDavBackend.php
>  					->from('calendarchanges')
As per our call... (face palm)... did realize that the operations just get truncated every few months... They should be selectively pruned to only include the last operation for each object...  Adjusted the code to accommodate truncation...

2024-07-30 17:17 UTC, SebastianKrupinski commented on apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
> +	public function testCalendarSynchronization(): void {
Perfect

2024-07-31 12:55 UTC, st3iny approved these changes
LGTM! Refactoring of the incremental sync case is a (minor) performance improvement. Additional unit tests are always welcome.

2024-08-07 05:25 UTC, ChristophWurst approved these changes

2024-08-07 12:49 UTC, merged