feat(TaskProcessing): Implement enums and default values
nextcloud/server pull request #46722
Opened 2024-07-24 13:36 UTC by marcelklehr

## Summary
This adds Enum types to input and outputs of Tasks and allows providers to specify the values of those enums, as well as default values for any input slots.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-24 13:37 UTC, julien-nc approved these changes
:rocket: :boom: :+1: :heart:

2024-07-24 13:47 UTC, provokateurin approved these changes
Quick, feature freeze is tomorrow :D

2024-07-24 16:28 UTC, julien-nc requested changes

2024-07-24 16:28 UTC, julien-nc commented on lib/private/TaskProcessing/Manager.php
> +		$spec = array_reduce($defaultSpecs, fn ($carry, $spec) => $carry + $spec, []);
This always writes default values even when a value is set in the submitted input.

2024-07-24 16:49 UTC, julien-nc requested changes

2024-07-24 16:49 UTC, julien-nc commented on lib/private/TaskProcessing/Manager.php
> +		return $spec + $input;
```suggestion
		$spec = array_reduce($defaultSpecs, fn ($carry, $spec) => array_merge($carry, $spec), []);
		return array_merge($spec, $input);
```

This always writes default values even when a value is set in the submitted input.

2024-07-25 08:11 UTC, julien-nc approved these changes

2024-07-25 09:03 UTC, marcelklehr reviewed
I approve

2024-07-25 09:03 UTC, merged

2024-07-25 09:03 UTC, marcelklehr commented
Woop wooop