Update line height
nextcloud/server pull request #46876
Opened 2024-07-30 12:22 UTC by marcoambrosini

2024-07-30 12:29 UTC, Antreesy commented on apps/theming/css/default.css
>    --default-font-size: 15px;
Maybe add a small font size, as you're touching it?
```suggestion
  --default-font-size: 15px;
  --font-size-small: 13px;
```

2024-07-30 12:31 UTC, marcoambrosini commented on apps/theming/css/default.css
>    --default-font-size: 15px;
Was going to do it in a separate pr, but ok

2024-07-30 12:49 UTC, ShGKme requested changes

2024-07-30 12:49 UTC, ShGKme commented on apps/theming/css/default.css
> +  --default-line-height: 1.5em;
Setting `em` as line-height is not correct. This is an absolute value which means "1.5 * this element font-size". That means if you have 1.5em on a 15px parent, then all the children have 1.5 * 15 = 22.5px line height. Not matter what font-size they have, it's exactly 22.5px even for 100px and 10px font-size.

Only using unitless multiplier means "x1.5 of font-size", so children with 100px font size will have 150px line height, and 10px font-size will have 15px line height.

```suggestion
  --default-line-height: 1.5;
```

2024-07-30 12:49 UTC, ShGKme commented on apps/theming/css/default.css
>    --default-font-size: 15px;
Agree of creating PR to no mix creating a new variable (feature) and fixing line-height (design change).

2024-07-30 12:54 UTC, ShGKme commented on apps/theming/css/default.css
> +  --default-line-height: 1.5em;
Example: https://codepen.io/ShGKme/pen/abgpYKB

2024-07-30 13:16 UTC, ShGKme commented
A bit sad part is that 15 doesn't scale well in int numbers... It makes a text element having 22.5 height, which may result in some side effects. (It is different from 22 or 23 px)

Having also grid baseline 16px, shouldn't we make font-size also 16, so it multiplies by 1.5 well, and lies on `4px * n` grid including 1.5 * 16 = 24px?

2024-07-31 12:58 UTC, ShGKme approved these changes

2024-07-31 13:01 UTC, Antreesy approved these changes

2024-07-31 15:20 UTC, merged