Fix/account menu
nextcloud/server pull request #46880
Opened 2024-07-30 13:19 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/46460

## Summary

Make the account menu use NcListItem to automatically follow the new design rules.

### Screenshots
before|after
---|---
![Bildschirmfoto_20240730_144744](https://github.com/user-attachments/assets/75ebcad5-819b-4541-bb93-68def4d27fb7)|![Bildschirmfoto_20240730_151009](https://github.com/user-attachments/assets/876a66e0-ed97-484d-8331-28fe161e31d2)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-07-31 11:18 UTC, jancborchardt requested changes, later dismissed
Thanks @susnux! :) So it does look a bit strange, some detail points:
- [x] The icons seem to have grown, or is this an illusion?
- [x] Top padding above "admin" username is less than on the left, should be equidistant
- [ ] The right margin (or padding) is very little, visible at "Appearance and accessibility"

2024-07-31 11:20 UTC, susnux commented
> * The icons seem to have grown, or is this an illusion?

Made them 20px like everywhere else, before it they were 16px

2024-07-31 19:23 UTC, susnux commented
> Thanks @susnux! :) So it does look a bit strange, some detail points:
> 
>     * [ ]  The icons seem to have grown, or is this an illusion?

I made them 20px but now reverted to 16px.

>     * [ ]  Top padding above "admin" username is less than on the left, should be equidistant

Was already the same as inline padding (4px grid baseline), you see this if the entry is active and get primary coloring. but adjusted a bit.

>     * [ ]  The right margin (or padding) is very little, visible at "Appearance and accessibility"

Increased both to 8px (2* grid baseline).

2024-08-01 07:16 UTC, marcoambrosini commented
@susnux why not action menu for this?

2024-08-01 12:12 UTC, susnux commented
> why not action menu for this?

@marcoambrosini what do you mean? Naming? Or using NcActions?
If you mean NcActions, than we can not use that because they have more complex render logic and do not allow arbitrary content, but this menu does allow apps to register custom entries which is not possible with NcActions.

2024-08-05 11:31 UTC, susnux commented
@marcoambrosini @jancborchardt what do you think of the changes now? Can we go with it or should I adjust it?

2024-08-05 11:49 UTC, marcoambrosini approved these changes

2024-08-05 20:25 UTC, nimishavijay approved these changes

2024-08-06 07:41 UTC, merged