#41935 smtp: allow self-signed certificates on localhost
nextcloud/server pull request #46957
Opened 2024-08-01 15:42 UTC by Cybso

Pull request as suggested by [joshtrichards](https://github.com/joshtrichards) in #41935

* Resolves: 
  * #41935 
  * #37329 
  * #37694 
  * #38957 
  * #39452 
  * #39538 
  * #40073
  * and maybe more

## Summary

A mailserver listening on localhost can never have a valid TLS certificate and it does not require one. This patch enabled `allow_self_signed` and disables `verify_peer` and `verify_peer_name` when `mail_smtphost` equals `localhost` or `127.0.0.1`.

2024-08-02 14:21 UTC, szaimen commented on lib/private/Mail/Mailer.php
> +		} else if ($mailSmtphost === 'localhost' || $mailSmtphost === '127.0.0.1') {
In theory we could even add this if no valid host was provided, e.g. by using such a filter: https://github.com/nextcloud/all-in-one/blob/c9b97220d0175914c3ee8c7199949376f7bfe3b0/php/src/Data/ConfigurationManager.php#L274-L295

However this sounds like magic and not sure if we want to actually do this automatically.

WDYT @nextcloud/server-backend @miaulalala

2024-08-02 15:17 UTC, kesselb commented
```
1) Test\Mail\MailerTest::testStreamingOptionsWrongType
Failed asserting that 1 matches expected 0.

/home/runner/actions-runner/_work/server/server/tests/lib/Mail/MailerTest.php:291
```

2024-08-02 15:33 UTC, Cybso commented
> ```
> 1) Test\Mail\MailerTest::testStreamingOptionsWrongType
> Failed asserting that 1 matches expected 0.
> 
> /home/runner/actions-runner/_work/server/server/tests/lib/Mail/MailerTest.php:291
> ```

I will adapt the test as soon as it is clear whether this pull request has a chance of being accepted or not.

2024-08-05 09:18 UTC, miaulalala requested changes

2024-08-05 09:18 UTC, miaulalala commented on lib/private/Mail/Mailer.php
> +			));
I'm of two minds here - one is that it indeed makes localhosts work without any setup, which, as you stated has confused many users due to how the Symfony Mailer works. OTOH I'm not entirely happy with overwriting config options per default.

I think there's some middle ground here: check if the `ssl` option is set and only overwrite it if a) the host is `localhost || 127.0.0.1` and b) if the option doesn't already exist in the `$currentStreamingOptions`

I also think it doesn't need to be an elseif but can be an if condition on it's own. Something like:

```suggestion
		} 
		$local = ['localhost', '127.0.0.1']; // You could make this a constant
		if (in_array($mailSmtphost, $local) && !isset($currentStreamingOptions['ssl'])) {
			$currentStreamingOptions = $stream->getStreamOptions();
			$currentStreamingOptions = array_merge_recursive($currentStreamingOptions, array(
				'ssl' => array(
					'allow_self_signed' => true,
					'verify_peer' => false,
					'verify_peer_name' => false
				)
			));
```

2024-08-05 09:31 UTC, kesselb commented
https://github.com/symfony/symfony/pull/53621 (but it will take a while until we are on mailer 7.1)

2026-01-30 14:11 UTC, szaimen commented
Hi, we have a checkbox now to allow insecure certificates: https://github.com/nextcloud/server/pull/57544/changes#diff-d611085ec819ab74b9abec857410a14d726ea1b1c0b84dc0d99bd88be39f54d0R165-R167 so this can be closed imho

<img width="1250" height="212" alt="image" src="https://github.com/user-attachments/assets/5e666a19-4a91-4d3c-80ee-fc9362c20e28" />

2026-02-02 09:09 UTC, miaulalala commented
Thanks so much for your time and effort @Cybso ! https://github.com/nextcloud/server/pull/57544/ will hopefully solve the issues with self signed certificates (and servers that advertise TLS but don't actually support it).

2026-02-02 09:09 UTC, closed without merging