Checkbox template field type
nextcloud/server pull request #47290
Opened 2024-08-16 20:03 UTC by elzody

## Summary
This PR will introduce a checkbox type when filling templates.
Part of [nextcloud/richdocuments#3917](https://github.com/nextcloud/richdocuments/issues/3917)

## TODO

- [ ] Testing, will be implemented on the richdocuments side and linked here when ready.

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-20 21:02 UTC, jancborchardt requested changes
Very nice! :) The switch should be left of the text though as per component, no? https://nextcloud-vue-components.netlify.app/#/Components/NcCheckboxRadioSwitch

![image](https://github.com/user-attachments/assets/0d54aa4a-449d-4109-b510-3c3e19762eab)

2024-08-20 21:49 UTC, elzody commented
@jancborchardt Indeed, it was a bit foolish of me to change this in retrospect. Will change and re-request review when ready :)

2024-08-21 11:03 UTC, juliushaertl commented on lib/public/Files/Template/Field.php
> +	public function __construct(
So unfortunately since we are in API freeze this is nothing we can merge normally. However since the richdocuments app is the only app using it, it would be ok from my perspective.

FYI @AndyScherzinger In case you'd speak out against that.

2024-08-21 11:03 UTC, juliushaertl commented on lib/public/Files/Template/Field.php
> +	public ?bool $checked = null;
Do we rather wan to reuse $value and make it a mixed type? That would make it more flexible if we extend further with a `\DateTime` object or others in the future.

2024-08-21 20:41 UTC, skjnldsv commented on lib/public/Files/Template/Field.php
> +	public function __construct(
> So unfortunately since we are in API freeze this is nothing we can merge normally

Because this is planned to be backported?

2024-08-21 21:01 UTC, AndyScherzinger commented on lib/public/Files/Template/Field.php
> +	public function __construct(
Yes, since this is build and used only by richdocuments and used for the templating implementation it ships starting with 30.

2024-08-26 17:51 UTC, juliushaertl commented on lib/public/Files/Template/Field.php
>  class Field implements \JsonSerializable {
Can be abstract if we now always define a subclass for each type

2024-08-26 17:51 UTC, juliushaertl commented on lib/public/Files/Template/Field.php
> +	public function setValue(mixed $value): void {
Can also be abstract

2024-08-26 17:53 UTC, juliushaertl commented on lib/public/Files/Template/Field.php
> +		return array_merge([], ...$jsonProperties);
I think with the individual classes we do not need the dynamic property iteration here.

2024-08-26 17:53 UTC, juliushaertl reviewed
Generally fine, just some small comments

2024-08-26 20:19 UTC, jancborchardt approved these changes
Looks nice design-wise! :)

2024-08-27 15:30 UTC, kesselb approved these changes

2024-08-27 15:53 UTC, elzody commented
/backport to stable30

2024-08-27 16:28 UTC, susnux commented on apps/files/src/components/TemplateFiller.vue
> +<script>
why reverting to JS?

2024-08-27 16:30 UTC, susnux commented on apps/files/src/components/TemplateFiller.vue
> +		trackInput([index, name, value]) {
I would recommend not to use positional array for this but names objects, makes spotting issues easier :sweat_smile:

2024-08-27 16:45 UTC, elzody commented on apps/files/src/components/TemplateFiller.vue
> +<script>
Wasn't using TypeScript in this file, but if it makes it more consistent with the rest of the files I can leave it as TS.

2024-08-27 17:33 UTC, elzody commented on apps/files/src/components/TemplateFiller.vue
> +		trackInput([index, name, value]) {
Do you mean then emitting something like this instead?

```diff
diff --git a/apps/files/src/components/TemplateFiller/TemplateRichTextField.vue b/apps/files/src/components/TemplateFiller/TemplateRichTextField.vue
index e794abd7e16..a6137a1df36 100644
--- a/apps/files/src/components/TemplateFiller/TemplateRichTextField.vue
+++ b/apps/files/src/components/TemplateFiller/TemplateRichTextField.vue
@@ -15,7 +15,7 @@
                        :label="fieldLabel"
                        :label-outside="true"
                        :placeholder="field.content"
-                       @input="$emit('input', [field.index, 'content', value])" />
+                       @input="input" />
        </div>
 </template>
 
@@ -53,6 +53,16 @@ export default defineComponent({
                        return 'text-field' + this.field.index
                },
        },
+       
+       methods: {
+               input() {
+                       $emit('input', {
+                               index: this.field.index,
+                               property: 'content',
+                               value: this.value,
+                       })
+               }
+       },
 })
 </script>
```

2024-08-27 20:15 UTC, merged