fix: Display 'Leave share' instead of 'Delete'
nextcloud/server pull request #47339
Opened 2024-08-20 09:43 UTC by marcelklehr

## Summary

In files in the "Shared With Me" view, shares' context menu display a "Delete" entry when it should say "Leave this share". This PR fixes that.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-20 12:05 UTC, skjnldsv approved these changes

2024-08-20 12:08 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		$result['mount-type'] = $node->getFileInfo()->getMountPoint()->getMountType();
Weird! `getFileInfo` in the [private class exists](https://github.com/nextcloud/server/blob/dae7c159f728a90ffa53247d6e033abdae5d2bd6/lib/private/Files/Node/Node.php#L80), but is not declared [in the interface](https://github.com/nextcloud/server/blob/dae7c159f728a90ffa53247d6e033abdae5d2bd6/lib/public/Files/Node.php)

2024-08-20 12:12 UTC, skjnldsv requested changes
Please open against `master`
![image](https://github.com/user-attachments/assets/a6153b5f-cc5d-490b-ba73-3a6c8dc283bc)

2024-08-20 12:14 UTC, skjnldsv commented
God dammit

2024-08-20 12:17 UTC, skjnldsv approved these changes

2024-08-20 12:35 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		$result['mount-type'] = $node->getFileInfo()->getMountPoint()->getMountType();
Seems like that is done on purpose as that class just wraps the fileinfo, why not using:

```suggestion
		$result['mount-type'] = $node->getMountPoint()->getMountType();
```

2024-08-20 12:40 UTC, skjnldsv commented on lib/public/Files/Node.php
> +	public function getFileInfo(bool $includeMountPoint = true);
I guess this is some old legacy thing, let's drop this, your approach is far cleaner

2024-08-20 12:44 UTC, skjnldsv commented on lib/public/Files/Node.php
> +	public function getFileInfo(bool $includeMountPoint = true);
This is also because the `\OCA\DAV\Connector\Sabre\Node` does not extend the FileInfo
https://github.com/nextcloud/server/blob/4bbcbc520620b59c19f058fa79e107ee1a8ce275/apps/dav/lib/Connector/Sabre/FilesPlugin.php#L335

Similar name, different classes :see_no_evil:

2024-08-20 13:19 UTC, marcelklehr commented
Sorry for opening against stable28, I thought master was fixed already

2024-08-20 13:56 UTC, artonge approved these changes

2024-08-20 13:58 UTC, marcelklehr commented
/backport to stable30

2024-08-20 13:58 UTC, marcelklehr commented
/backport to stable29

2024-08-20 13:58 UTC, marcelklehr commented
/backport to stable28

2024-08-20 14:42 UTC, skjnldsv commented
I need to fix unit tests

2024-08-20 15:40 UTC, susnux approved these changes

2024-08-21 19:49 UTC, skjnldsv commented
Stop rebasing @AndyScherzinger , tests needs fixing

2024-08-21 19:56 UTC, AndyScherzinger commented
Sure thing @skjnldsv - thought it's about tests elsewhere and a rebase might help 😅

2024-08-22 08:04 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		}
This is coming from here: https://github.com/nextcloud/server/blob/6002566d929f8160bd85dc642f86e0616f0f394e/apps/files_sharing/lib/Controller/ShareAPIController.php#L601-L605

That is weird and I don't get it.
@schiessle, it's a long stretch, but maybe you remember why? Why do single-file shares cannot have delete permissions?

2024-08-22 11:55 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		}
Not 100% related, but how would be separate the two things then:
1. Leave the share
2. Remove the file

2024-08-22 14:35 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		}
We don't,
- if it's a root mount and you're now the owner, -> delete share
- if it's not a root mount and you're not the owner, then it's a file shared with your -> delete (if share permission allowed)

2024-09-06 16:03 UTC, marcelklehr commented
Oof, this turned out to be a deeper rabbit hole than I anticipated. Thank you for digging into this @skjnldsv :blue_heart:

2024-09-06 19:35 UTC, skjnldsv commented
> Oof, this turned out to be a deeper rabbit hole than I anticipated. Thank you for digging into this @skjnldsv :blue_heart: 

Yeah 🥲🫠🫠🫠

2024-09-06 19:36 UTC, skjnldsv commented
Still a few tests to adjust 😅

2024-09-11 11:42 UTC, merged

2024-09-11 11:49 UTC, skjnldsv commented
/backport to stable29

2024-09-11 11:52 UTC, skjnldsv commented
/backport to stable29

2024-09-11 11:53 UTC, skjnldsv commented
/backport to stable29