Move preferred install method to top spot
nextcloud/server pull request #47582
Opened 2024-08-28 15:19 UTC by fulldecent

## Summary

Move the preferred installation method (All-In-One) to the top position when reporting bugs.

Likewise for the latest supported PHP version.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-28 16:30 UTC, susnux approved these changes
makes sense

2024-08-28 16:35 UTC, szaimen requested changes
Blocking for now. Reason: https://github.com/nextcloud/server/pull/38393#issue-1719270118

2024-08-28 17:36 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
lets not do this

2024-08-28 17:36 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - "PHP 8.0"
Fine by me

2024-08-28 18:26 UTC, susnux commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
But those lazy people will keep selecting a wrong one then, no?

2024-08-28 18:31 UTC, fulldecent commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
No. The lazy people will leave it as the default option which is blank

2024-08-28 18:38 UTC, solracsf commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
My honest opinion? I would remove this section: 1) in 9.9 out of 10 bug reports, this doesn't matter, 2) a lot of people doesn't answer correctly 3) and, if really needed for debug purposes, this could always be asked. 💭

2024-08-28 18:39 UTC, susnux commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
@solracsf I fully agree, especially because it makes the form so long that important information is skipped while this unimportant information is added.

2024-08-28 20:08 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
Sounds good to me to remove this section

2024-08-29 07:49 UTC, AndyScherzinger approved these changes

2024-08-29 09:41 UTC, szaimen commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> -        - "Official All-in-One appliance"
done

2024-08-29 09:42 UTC, szaimen approved these changes
LGTM

2024-08-29 09:54 UTC, skjnldsv approved these changes

2024-08-29 09:54 UTC, merged