fix: Add repair step to restore primary color after separating primary and background
nextcloud/server pull request #47586
Opened 2024-08-28 18:17 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/46980

## Summary

Not sure about the user color part, but at least it works :sweat_smile: 
Meaning not sure if that query would not take long on large instances.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-28 18:18 UTC, susnux commented
/background to stable30

2024-08-28 22:39 UTC, AndyScherzinger commented
/backport to stable30

2024-08-29 08:01 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		private IConfig $config,
```suggestion
		private IAppConfig $config,
```

2024-08-29 08:01 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +			$this->config->setAppValue(Application::APP_ID, 'background_color', $defaultColor);
```suggestion
			$this->config->getValueString(Application::APP_ID, 'background_color', $defaultColor);
```

2024-08-29 08:01 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		$defaultColor = $this->config->getAppValue(Application::APP_ID, 'color', '');
```suggestion
		$defaultColor = $this->config->getValueString(Application::APP_ID, 'color', '');
```

2024-08-29 08:02 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +			$this->config->setAppValue(Application::APP_ID, 'primary_color', $defaultColor);
```suggestion
			$this->config->setValueString(Application::APP_ID, 'primary_color', $defaultColor);
```

2024-08-29 08:02 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +			$this->config->deleteAppValue(Application::APP_ID, 'color');
```suggestion
			$this->config->deleteKey(Application::APP_ID, 'color');
```

2024-08-29 08:03 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		$migrated = $this->config->getAppValue('theming', 'nextcloud_30_migration', 'false') === 'true';
```suggestion
		$migrated = $this->config->getValueBool('theming', 'nextcloud_30_migration', false) === true;
```

2024-08-29 08:03 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		$userThemingEnabled = $this->config->getAppValue('theming', 'disable-user-theming', 'no') !== 'yes';
```suggestion
		$userThemingEnabled = $this->config->getValueString('theming', 'disable-user-theming', 'no') !== 'yes';
```

2024-08-29 08:03 UTC, skjnldsv commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		$this->config->setAppValue('theming', 'nextcloud_30_migration', 'true');
```suggestion
		$this->config->setValueBool('theming', 'nextcloud_30_migration', true);
```

2024-08-29 08:04 UTC, skjnldsv requested changes, later dismissed
use `IApmpConfig` please :)

2024-08-29 11:28 UTC, susnux commented
> use IAppConfig please :)

If it is fixed now, then I love to. It had a really bad bug that you cannot mix `IConfig->setAppValue` and e.g. `IAppConfig->setValueBool`.
Meaning you have to migrate **every** access to that value to the types access, in every place. Otherwise after using the typed access you can no longer access it with the `IConfig` variant.

One recent place were we needed to fix this: https://github.com/nextcloud/server/pull/46991

2024-09-02 08:53 UTC, come-nc requested changes, later dismissed
The config key to check if repair step ran already is too ugly, please use a migration instead which by design run only once.

2024-09-02 08:53 UTC, come-nc commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +	public function run(IOutput $output) {
```suggestion
	public function run(IOutput $output): void {
```

2024-09-02 08:53 UTC, come-nc commented on apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php
> +		}
Then this should be put in a migration and not a repair step?

2024-09-02 15:17 UTC, susnux commented
@come-nc I refactored this again, but we need to put parts of the migration into a background job. As we need to iterate a list of users which could take long if many users had custom backgrounds.

I reused the logic from the `dashboard -> theming` repair step / background job.

So it is now working correctly for me:

### Screen recording
#### Setup

[Bildschirmaufnahme_20240902_165334.webm](https://github.com/user-attachments/assets/77f12cdd-32b2-4947-844e-060513251a5b)


#### After Upgrade to Nextcloud 30 / 31

Please note the wrong colors in the beginning, I triggered the migration then and reload the page:

[Bildschirmaufnahme_20240902_170942.webm](https://github.com/user-attachments/assets/176b41a1-f388-4bec-8554-94d21e33d7c9)

2024-09-03 08:29 UTC, come-nc commented
Psalm is quite angry

2024-09-03 08:45 UTC, come-nc commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +		$userIds = $notSoFastMode ? array_slice($allUserIds, 0, 1000) : $allUserIds;
```suggestion
		$userIds = array_slice($allUserIds, 0, 1000);
```
No need to check count first, `array_slice` will take care of it.

2024-09-03 08:45 UTC, come-nc commented on apps/theming/lib/Service/BackgroundService.php
> +		if ($this->userId === null) {
Is it on purpose that the test is on `$this->userId` and not `$userId`?
Looks fishy

2024-09-03 08:45 UTC, come-nc commented on apps/theming/lib/Service/BackgroundService.php
> +		$this->getAppDataFolder()->newFile('background.jpg', $file->fopen('r'));
```suggestion
		$this->getAppDataFolder()->newFile('background.jpg', $handle);
```
I suppose?

2024-09-05 09:42 UTC, susnux commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
Having a look at the definition: We explicitly handle functions passed, so this works. Probably just not in the public interface.
But otherwise we have to way to create sub queries.

2024-09-05 13:51 UTC, susnux commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
See https://github.com/nextcloud/server/blob/9f9884930609addad3e37325731fb5406dd3aa44/lib/private/db/querybuilder/querybuilder.php#L1317-1320

2024-09-09 09:00 UTC, come-nc commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
Either you cast to string or you change the IQueryBuilder/QueryBuilder leftJoin method to accept IQueryFunction for the second parameter.

2024-09-09 14:28 UTC, susnux commented on apps/theming/lib/Migration/Version2006Date20240905111627.php
> +	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options) {
```suggestion
	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
```

2024-09-09 14:28 UTC, susnux commented on apps/theming/lib/Migration/Version2006Date20240905111627.php
> +	public function preSchemaChange(IOutput $output, Closure $schemaClosure, array $options) {
```suggestion
	public function preSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
```

2024-09-09 15:42 UTC, susnux commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
Done :heavy_check_mark:

2024-09-09 15:43 UTC, come-nc commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
But that’s what the QueryBuilder is doing in the end, so what’s the difference?

2024-09-09 15:46 UTC, susnux commented on apps/theming/lib/Jobs/RestoreBackgroundImageColor.php
> +				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
If a string is passed the `getTableName` function will prepend `'*PREFIX*'` to the string, if a `IQueryFunction` is passed it is only cast to string but no prefix is added.

2024-09-10 16:02 UTC, come-nc approved these changes

2024-09-11 10:23 UTC, ArtificialOwl approved these changes
code looks good

2024-09-11 13:10 UTC, merged