fix(theming): Fix broken values when using default line height for calculations
nextcloud/server pull request #47648
Opened 2024-08-30 19:39 UTC by Pytal

## Summary

Fix the default line height variable breaking calculated values. In devtools there is no indication that the declaration is invalid but the style is not applied as the value is invalid e.g. `1.5 + (2 * 4px) = 1.5 + 8px` is invalid as the unitless value canoot be added to the px value

Now `(1.5 * 15px) + (2 * 4px) = 22.5px + 8px` is valid

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-08-30 22:05 UTC, susnux requested changes
The value is valid, `line-height` can just be a numeric factor.
This is essential for calculations of different elements with different font sizes, so this is just the relative line height.

See also https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#line-height

---

This value `default-line-height` can be used on any element regardless if the element uses `font-size: var(--default-font-size);` or `font-size: var(--font-size-small)`.
Instead if you need the line height of an element you do not need any variable, but simply can use `1lh` this is the CSS unit for one line height of that element.

2024-08-30 22:06 UTC, susnux commented on core/css/public.scss
> +	--footer-height: calc(var(--default-line-height) + 2 * var(--default-grid-baseline));
So instead you need to multiply the line height with the font size, or much easier:

```suggestion
	--footer-height: calc(1lh + 2 * var(--default-grid-baseline));
```

2024-08-30 22:06 UTC, susnux commented on core/css/public.scss
> +		--footer-height: calc(2 * var(--default-line-height) + 3 * var(--default-grid-baseline));
```suggestion
		--footer-height: calc(2lh + 3 * var(--default-grid-baseline));
```

2025-04-02 17:19 UTC, susnux approved these changes

2025-04-02 17:22 UTC, AndyScherzinger approved these changes

2025-04-02 17:30 UTC, skjnldsv approved these changes

2025-04-02 17:31 UTC, merged