fix(Notification): Validate key value types of rich object parameters
nextcloud/server pull request #47662
Opened 2024-08-31 15:05 UTC by provokateurin

## Summary

A lot of apps set invalid rich object parameters for notifications. Most common are integer ids were the casting was forgotten.

Technically this is not a breaking change since the apps triggering this behavior are just broken, but we are way to late into the cycle to backport this to 30 and have everyone fix their apps, so I'm not doing that (let alone backport it to older versions).

Not sure if this needs to have some upgrade docs, please let me know.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-02 05:16 UTC, provokateurin commented
One non-breaking backportable alternative would be to just cast the keys and values automatically and only log a debug messages. That doesn't force everyone to immediately fix their apps and we could still make it throw an error later when hopefully everyone has seen the debug logs.

2024-09-02 09:04 UTC, nickvergessen requested changes

2024-09-02 09:04 UTC, nickvergessen commented on lib/private/Notification/Notification.php
> +			foreach ($parameter as $key => $value) {
This should be done by the [IValidator](https://github.com/nextcloud/server/blob/master/lib/private/RichObjectStrings/Validator.php) instead and the setRich* methods should call it (so its also run when a parsed message was set by the provider already)

2024-09-09 18:39 UTC, provokateurin commented
Adjusted all the other uses of the validator to have the right types.

2024-09-10 07:41 UTC, come-nc approved these changes

2024-09-10 13:37 UTC, nickvergessen approved these changes

2024-09-10 15:40 UTC, merged