fix(files): Check if target path is a descendant of the shared folder
nextcloud/server pull request #47756
Opened 2024-09-04 20:26 UTC by solracsf

* Resolves: # 

## Summary

Check is overly broad because it triggers if the target path starts with the shared folder's path, even if the target path is a sibling or a nested folder that is not actually within the shared folder.

The function should check if the target path is a direct descendant of the shared folder path rather than just starting with it. This can be done by ensuring that the target path either matches the shared path exactly or has a `/` immediately following the shared folder path.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-04 22:22 UTC, susnux approved these changes

2024-09-04 22:24 UTC, susnux reviewed
Would be great if you could add a test for this case to `tests/lib/Files/ViewTest.php`

2024-09-05 04:12 UTC, provokateurin requested changes
Change looks good, but please add a test

2024-09-05 05:10 UTC, solracsf commented
I'm on a vacation for the next weeks since this morning, if someone could commit a test it would be great, otherwise I'll do when i'm back. 🛸

2024-09-05 06:07 UTC, provokateurin approved these changes

2024-09-05 07:38 UTC, solracsf commented
/backport to stable30

2024-09-05 07:38 UTC, solracsf commented
/backport to stable29

2024-09-05 08:40 UTC, provokateurin commented
/backport to stable28

2024-09-05 08:41 UTC, provokateurin commented
CI failure is unrelated but already fixed on master. Please rebase to fix it

2024-09-05 09:19 UTC, solracsf commented
> /backport to stable28

@provokateurin unless i'm wrong, `stable28` doesn't seem to have the same codebase

2024-09-05 09:31 UTC, provokateurin commented
> CI failure is unrelated but already fixed on master. Please rebase to fix it

Sorry I was wrong about this, it is still broken on master :/ But it's easy to spot because it only affects oracle and all other phpunit jobs should be green.

> unless i'm wrong, stable28 doesn't seem to have the same codebase

Sorry, I didn't look into it. Is 28 affected by the same bug or not? Because if it is affected and the code is incompatible we need a different solution.

2024-09-05 09:36 UTC, solracsf commented
Well, the report is about 29 only, and that fonction was reworked on 29 only at that time (no backport to 28).
https://github.com/nextcloud/server/pull/43791

So, I believe 28 is not affected.

2024-09-05 09:57 UTC, provokateurin commented
Ok, sounds good then.

2024-09-05 16:55 UTC, susnux approved these changes

2024-09-06 01:58 UTC, merged