fix(caldav): Do not load IMipPlugin before user auth and session is c…
nextcloud/server pull request #47790
Opened 2024-09-05 19:53 UTC by SebastianKrupinski

Back port for #45081

Do not load IMipPlugin before user is authenticated and user session is initialized

2024-09-05 19:59 UTC, miaulalala requested changes
Please remove the commented out code, otherwise it looks good!

2024-09-05 19:59 UTC, miaulalala commented on apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
> +		*/
```suggestion
```

2024-09-05 20:11 UTC, SebastianKrupinski commented on apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
> +		*/
Done

2024-09-05 20:18 UTC, miaulalala approved these changes

2024-10-02 09:30 UTC, Altahrim approved these changes

2024-10-02 09:30 UTC, merged