feat: add iMip Request Handling
nextcloud/server pull request #47826
Opened 2024-09-07 22:32 UTC by SebastianKrupinski

* Resolves: #8458

## Summary
* added iMip request handling to automatically update calendar events

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-08 08:19 UTC, tcitworld commented on apps/dav/lib/CalDAV/CalendarImpl.php
> +	public function isWritable(): bool {
Don't you want to add those to `OCP\Calendar\ICalendar` as well?

2024-09-08 18:22 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalendarImpl.php
> +	public function isWritable(): bool {
Hi @tcitworld,

Good point!

2024-09-08 18:36 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalendarImpl.php
> +	public function isWritable(): bool {
Well I had a look at this, but it seems that CalendarImpl does NOT implement ICalendar "class CalendarImpl implements ICreateFromString, IHandleImipMessage" so there seems to be no reason to add the isWritable to the ICalendar interface, unless I am missing something.

2024-09-09 07:30 UTC, ChristophWurst requested changes

2024-09-09 07:30 UTC, ChristophWurst commented on lib/private/Calendar/Manager.php
> +					$calendar->handleIMipMessage('', $calendarData); // sabre will handle the scheduling behind the scenes
What Psalm says. You have to make sure $calendar is ICreateFromStringAndHandleImipMessage. ICreateFromString does not have a handleIMipMessage.

2024-09-09 17:52 UTC, SebastianKrupinski commented on lib/private/Calendar/Manager.php
> +					$calendar->handleIMipMessage('', $calendarData); // sabre will handle the scheduling behind the scenes
I will DM you on this

2024-09-16 13:37 UTC, ChristophWurst reviewed
CS

2024-09-16 13:37 UTC, ChristophWurst commented on lib/private/Calendar/Manager.php
> +		// convert calendar string data to calendar object
Comments that duplicate what the code clearly does make it harder to read the code. Please remove them.

Do add comments when the code is not self-explanatory.

2024-09-16 13:37 UTC, ChristophWurst commented on lib/private/Calendar/Manager.php
> +		// determine if event contains a uid
Another perfect example

2024-10-17 12:27 UTC, SebastianKrupinski commented on lib/private/Calendar/Manager.php
> +					$calendar->handleIMipMessage('', $calendarData); // sabre will handle the scheduling behind the scenes
Fixed. Instance of made psalm happy.

2024-10-17 12:44 UTC, SebastianKrupinski commented on lib/private/Calendar/Manager.php
> +		// determine if event contains a uid
Done

2024-10-17 12:44 UTC, SebastianKrupinski commented on lib/private/Calendar/Manager.php
> +		// convert calendar string data to calendar object
Done

2024-10-17 13:59 UTC, ChristophWurst commented on lib/public/Calendar/ICalendar.php
> +	public function isWritable(): bool;
I am not sure if ICalendar is only implemented in the server. There can be apps that implement ``\OCP\Calendar\ICalendarProvider`` and return their own implementations of ICalendar. This change would break them until they add isWritable and isShared. See ``ICreateFromString`` and ``IHandleImipMessage``. The same trick might be needed here.

2024-10-17 21:42 UTC, SebastianKrupinski commented on lib/public/Calendar/ICalendar.php
> +	public function isWritable(): bool;
Originally I left these to methods out of the Interface and only put them in the implementation but that made psalm grumpy.

```
ERROR: UndefinedInterfaceMethod - lib/private/Calendar/Manager.php:263:46 - Method OCP\Calendar\ICreateFromString::isWritable does not exist (see https://psalm.dev/181)
ERROR: UndefinedInterfaceMethod - lib/private/Calendar/Manager.php:263:73 - Method OCP\Calendar\ICreateFromString::isShared does not exist (see https://psalm.dev/181)
```

What if I added these to methods to the psalm ignore list? And left them commented out in the interface with a note for later, that way we can give developers a version or two to implement them?

2024-10-18 04:31 UTC, ChristophWurst commented on lib/public/Calendar/ICalendar.php
> +	public function isWritable(): bool;
That's a hack. Psalm complains rightfully. App developers have the interface as contract. Anything that's not in the interface must not be called, so it would also not be usable in Mail.
If you want to learn more about this, read up on the paradigm *program to an interface, not an implementation* :)

2024-10-20 22:28 UTC, SebastianKrupinski commented on lib/public/Calendar/ICalendar.php
> +	public function isWritable(): bool;
Done

2024-10-21 15:41 UTC, st3iny reviewed
I tried to test it locally but it did not work. I sent an invite from another external service, added it to my calendar and then moved the event in the external service. A `REQUEST` with the new dates was sent and received but the event was not updated.

The problem is that no recipient is added to iMIP messages with method `REQUEST` in https://github.com/nextcloud/server/blob/7a2fe4a84046961e69b80fb002689c87cabf7c3a/apps/dav/lib/CalDAV/CalendarImpl.php#L237-L247

This causes the local delivery to fail in https://github.com/nextcloud/3rdparty/blob/b3cc57b68388b68e4d4dcf0ddcd8c7ba455dd840/sabre/dav/lib/CalDAV/Schedule/Plugin.php#L418-L423 because no recipient is set and thus no principal is available.

I think another if/else branch needs to be added to the statement above.

---

Please let me know in case I'm doing something wrong.

2024-10-21 22:02 UTC, SebastianKrupinski commented
> Please let me know in case I'm doing something wrong.

Nope, this was my blunder, I somehow overwrote or left out the code changes in CalendarImpl::handleIMipMessage(), I don't remember at this point, its been over a month. Logic is fixed. The fun of working on multiple issues in the same file.

2024-10-22 18:23 UTC, st3iny approved these changes
Tested and works beautifully now. Thanks!

2024-10-22 18:23 UTC, st3iny commented on apps/dav/lib/CalDAV/CalendarImpl.php
> +		elseif ($iTipMessage->method === 'REPLY') {
```suggestion
		} elseif ($iTipMessage->method === 'REPLY') {
```

:nerd_face: (sorry)

2024-10-23 15:24 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/CalendarImpl.php
> +		elseif ($iTipMessage->method === 'REPLY') {
Lol. No worries, adjusted.

2024-11-04 08:59 UTC, ChristophWurst approved these changes

2024-11-08 02:27 UTC, merged

2024-11-08 02:29 UTC, SebastianKrupinski commented
@ChristophWurst should we back port this to 30?

2024-11-11 15:47 UTC, ChristophWurst commented
This PR adds a new API. We generally don't backport these. So it's a no here.