feat: Reset route if neither the Viewer of the Sidebar is open
nextcloud/server pull request #47920
Opened 2024-09-12 12:35 UTC by artonge

When the viewer or the sidebar is opened, we add the fileid to the route.
When both of them are closed, we do not remove the fileid from the route.
This means that, upon reload, the sidebar will be opened even though it was closed previously.

This PR ensure that the fileid is removed from the route when both the Sidebar and the Viewer are closed.

https://github.com/user-attachments/assets/f363228c-d365-49e3-954c-0bbfaae19763

2024-09-12 14:30 UTC, susnux commented on apps/files/src/components/FilesListVirtual.vue
> +			if (OCA.Viewer.file === '') {
It feels wrong having access to `OCA.Viewer` here, is is not enough the check if `openFile` is set?
That would make it independent of the Viewer in this place.

Meaning the viewer should reset `openfile` on close.
So on sidebar close there are only two states:
1. `openfile` is set: do not remove the fileid
2. `openfile` is not set: also remove the fileid

2024-09-12 14:33 UTC, artonge commented on apps/files/src/components/FilesListVirtual.vue
> +			if (OCA.Viewer.file === '') {
Makes sense as we are also relying on `openfile` for the other way.

2024-09-12 16:33 UTC, susnux approved these changes
makes sense (ideally add a cypress tests), only thing I am not sure about if this really should be inside the virtual file list. But code makes sense and seems to work fine.

2024-09-13 08:47 UTC, artonge commented on apps/files/src/components/FilesListVirtual.vue
> +import { subscribe, unsubscribe } from '@nextcloud/event-bus'
:people_hugging:

2024-09-14 19:22 UTC, skjnldsv approved these changes

2024-09-14 19:24 UTC, skjnldsv requested changes
Wait for it

2024-09-14 19:44 UTC, skjnldsv approved these changes

2024-09-14 21:49 UTC, merged

2024-09-15 08:05 UTC, skjnldsv commented
Backports ?

2024-09-15 08:58 UTC, artonge commented
/backport to stable30

2024-09-15 08:58 UTC, artonge commented
/backport to stable29

2024-09-15 08:58 UTC, artonge commented
/backport to stable28