Fix (slow) move on same object bucket.
nextcloud/server pull request #47986
Opened 2024-09-14 21:06 UTC by cfiehe

This commit fixes the issue #47856. When you upload a file into a group folder and when you use a single S3 bucket as primary storage, the final move operation hangs for a long time. In the background, Nextcloud initiates a copy-delete sequence from the bucket into the bucket, with causes a lot unnecessary overhead. Nextcloud thinks that the file must be imported to another storage and does not recognize that everything is done on the same object bucket. In that case, the import step can be completely skipped, which saves time, network bandwidth and reduces the load on the object storage.

The behavior improves a lot with https://github.com/nextcloud/server/pull/46013. However, there are still some put messages that are being sent to the object storage when you use an object storage as primary storage and upload files into a group folder.

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-15 05:27 UTC, provokateurin commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			if ($sourceStorage->getObjectStore()->getStorageId() === $this->getObjectStore()->getStorageId()) {
```suggestion
		if ($sourceStorage->getId() === $this->getId()) {
```
Judging from the docs for IStorage::getId() this should be enough, although I don't know if there is a guarantee two different storages will absolutely never have the same ID, so your approach would be a lot safer then. @icewind1991 should know this in more detail.

2024-09-15 05:27 UTC, provokateurin commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			if ($sourceStorage->getObjectStore()->getStorageId() === $this->getObjectStore()->getStorageId()) {
```suggestion
		if ($sourceStorage->instanceOfStorage(ObjectStoreStorage::class) && $sourceStorage->getObjectStore()->getStorageId() === $this->getObjectStore()->getStorageId()) {
```

2024-09-15 07:49 UTC, cfiehe commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			if ($sourceStorage->getObjectStore()->getStorageId() === $this->getObjectStore()->getStorageId()) {
I had the same idea, too. In the groupfolders scenario, source and target storage are represented by different objects, both having a different type: One is of the type `HomeObjectStoreStorage`, the other one of type `ObjectStoreStorage`. The identifiers returned by `getId()` are different. However, when you have an object store as primary storage, both storage objects use the same underlying bucket. In order to cover this scenario, I think using the bucket identifier returned by `IObjectStore#getStorageId()` is a safe method for checking bucket equality.

2024-09-15 08:16 UTC, provokateurin commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			if ($sourceStorage->getObjectStore()->getStorageId() === $this->getObjectStore()->getStorageId()) {
Ok makes sense! Please apply the other suggestion I gave below then.

2024-09-15 08:16 UTC, provokateurin requested changes
Needs some tests to verify the behavior and prevent regressions.

2024-09-15 11:46 UTC, cfiehe reviewed
Looks good to me. Changes committed :-).

2024-09-15 12:19 UTC, provokateurin commented
Tests are still missing though.

2024-09-15 12:36 UTC, cfiehe commented
> Tests are still missing though.

I hope, that the object store tests from https://github.com/nextcloud/server/tree/master/tests/lib/Files/ObjectStore will give us a hint, if this change causes harm.

2024-09-15 12:49 UTC, provokateurin commented
Sure there shouldn't be any regressions from this change, but we also need a test that ensures the new behavior is present. So please add a test that moves a file on an object storage and ensures this case is triggered.

2024-09-15 16:46 UTC, provokateurin approved these changes
Awesome! This is a really good improvement :blue_heart:

2024-09-15 17:00 UTC, provokateurin commented
You need to follow the conventional commit format, so the commit message should be something like `fix(ObjectStoreStorage): Remove unnecessary move on same bucket`.

2024-09-15 19:22 UTC, provokateurin commented
No problem, we are here to help :) I just realized though that I made a mistake myself and ideally it would be `perf(...): ...` to indicate that it improves performance. You don't need to change it though, just something to keep in mind for the future.

2024-09-15 20:27 UTC, cfiehe commented
It seems that pull requests from a fork are not supported. Should I close this one here and create a new one based on https://docs.nextcloud.com/server/latest/developer_manual/getting_started/development_process.html?

2024-09-15 20:29 UTC, provokateurin commented
No I think it's fine for this since it only changes backend stuff and your change is covered by tests.

2024-09-16 12:20 UTC, icewind1991 approved these changes

2024-09-16 12:24 UTC, provokateurin commented
@sorbaugh can you merge?

2024-09-16 13:24 UTC, cfiehe commented
> @cfiehe please don't rebase, it is not necessary unless there actually are conflicts.

Oh, sorry.

2024-09-17 14:35 UTC, merged

2024-09-17 14:36 UTC, sorbaugh commented
aaand merged! Thanks @cfiehe for your contribution!!

2024-10-29 15:20 UTC, unteem commented
This does not only improve perfs but fixes a bug when you have an object storage as primary. In that case without this change, when object in unlinked it is deleted and as the object copied is the same than the original one, if object being moved is actually deleted. In the end you can see your moved objects in your nextcloud interface but it has been deleted in your object store. 

Please backport it, this a pretty dangerous bug, we had thousands of files being deleted (we can provide guidelines to restore it for those who also face this issue).

2024-10-29 15:53 UTC, pierreozoux commented
/backport to stable28

2024-10-29 16:21 UTC, provokateurin commented
I'm not convinced this needs to be backported to fix a bug. Are there any reports about it already?

2024-10-29 16:33 UTC, hrenard commented
We have experienced the issue on multiple Nextcloud instances at IndieHosters.

It could lead to data loss on buckets without versioning. So I think it's pretty serious.

2024-10-29 16:36 UTC, acazenave commented
Like @unteem said, it is quitting an impacting bug. 
Easy to reproduce : Move a file to a folder owned by someone-else (file in shared folder to user root / or local file to share folder). 
Then file is removed on S3.

2024-10-29 16:42 UTC, provokateurin commented
But the file isn't just deleted from the S3. This change only skips deleting and uploading the same content again.
Please show me some existing bug reports about this, I'm really confused how suddenly a few people comment here that it apparently is such a big problem.

2024-10-29 17:24 UTC, provokateurin commented
CC @icewind1991

2024-10-29 17:42 UTC, MaximeMaW commented
We also had tens of files removed, using v28.0.11.

2024-10-30 08:32 UTC, provokateurin commented
The problem is the tests added in this PR were broken (as all of our object storage tests weren't executed by CI it wasn't noticed) and @icewind1991 made some fixes, but they didn't get backported and there were so many changes I'm not sure what is needed to make it work.

2024-10-30 08:42 UTC, unteem commented
we could just remove the tests ? Do you want me to make a PR with just the fix and not the tests ? 
The soonest we get this pushed the best

2024-10-30 08:54 UTC, artonge commented
@unteem would be awesome if you could look into fixing the tests. The fixes are known, it is a matter of extracting them from follow-up PRs. Here are some pointers:
- https://github.com/nextcloud/server/pull/48145/files#diff-d73dbd864b8f342ceb685fb0183bf02089083718f65d7ebbfc9fde69de8e76bd
- https://github.com/nextcloud/server/pull/48205/files#diff-ab2e0d08c90f2c2c02fb8f0e4b882737edc377d149113644507d2e6aa9407884

2024-10-31 13:02 UTC, danxuliu commented
The regression when moving files fixed by this pull request can be tested in the following way:
- Setup Nextcloud with S3 as primary storage
- Add users _admin_ and _user0_
- As _admin_, create a folder (`curl --user admin:admin --request MKCOL --header "OCS-APIRequest: true" "http://127.0.0.1:8000/remote.php/dav/files/admin/sub"`)
- Upload a file into that folder (`curl --user admin:admin --upload-file /PATH/TO/test.txt --header "OCS-APIRequest: true" http://127.0.0.1:8000/remote.php/dav/files/admin/sub/test.txt`)
- Share the folder with _user0_ (`curl --user admin:admin --request POST --header "OCS-APIRequest: true" "http://127.0.0.1:8000/ocs/v1.php/apps/files_sharing/api/v1/shares?path=sub&shareType=0&shareWith=user0"`)
- As _user0_, move the file from the shared folder to the root (`curl --user user0:123456 --request MOVE --header "OCS-APIRequest: true" --header "Destination: http://127.0.0.1:8000/remote.php/dav/files/user0/test.txt" "http://127.0.0.1:8000/remote.php/dav/files/user0/sub/test.txt"`)
- Try to get the file (`curl --user user0:123456 --request GET --header "OCS-APIRequest: true" "http://127.0.0.1:8000/remote.php/dav/files/user0/test.txt"`)

Before 9597072ada7c0b9b7ee0d6e790a8422eab73572a an internal error is returned, and the logs show that the object could not be got from the storage. After 9597072ada7c0b9b7ee0d6e790a8422eab73572a the contents of the file are returned as expected.

However, the regression was not introduced in 3e12e1e7898903f6ef26f21db8bc21e7b29f0868, but in bd740ac0b012da697085d4244b890f931a3b1fd2. Therefore, through backports it was introduced in [Nextcloud 30.0.0](https://github.com/nextcloud/server/pull/47484), [Nextcloud 29.0.7](https://github.com/nextcloud/server/pull/47486) and [Nextcloud 28.0.11](https://github.com/nextcloud/server/pull/48213). Backports to [Nextcloud 27](https://github.com/nextcloud/server/pull/47487) and [Nextcloud 26](https://github.com/nextcloud/server/pull/47488) are still open and not merged.

2024-10-31 14:19 UTC, unteem commented
It is the combination of https://github.com/nextcloud/server/commit/3e12e1e7898903f6ef26f21db8bc21e7b29f0868 and how it is used in https://github.com/nextcloud/server/commit/3e12e1e7898903f6ef26f21db8bc21e7b29f0868 that is causing the issue. 

Since this first one when object are copied the `fileid` are not changed (which is a good think) but in moveFromStorage the file is copied then deleted. It was ok before as when an object was copied a new one with a new id was created. 
This issue only happens when you are in the same storage. Lets say I move an object from my primary storage to a secondary storage, a new object will be created and its fine. 

That is why this PR fixes it.

2024-11-06 17:06 UTC, artonge commented
> /backport to stable28

Isn't it already backported?

2024-11-06 17:30 UTC, icewind1991 commented
only 30 got this change so far

2024-11-07 06:56 UTC, provokateurin commented
> only 30 got this change so far

I tried to backport locally and the change is already on stable28.
https://github.com/nextcloud/server/pull/48985