refactor: Replace class strings with ::class constants
nextcloud/server pull request #48047
Opened 2024-09-15 20:11 UTC by ChristophWurst

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-15 20:27 UTC, miaulalala approved these changes

2024-09-15 20:46 UTC, st3iny approved these changes

2024-09-16 08:20 UTC, nickvergessen commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
What happened here?

2024-09-16 08:26 UTC, nickvergessen requested changes

2024-09-16 08:26 UTC, nickvergessen commented on lib/base.php
> +			\OC\User\Database::class,
This should breaking the events:
https://3v4l.org/ccpQf

If you adjusted the original event to also no longer provide the `\` old listeners will be broken.
Same for the `listen()` emitter things.

Potential solution: strip leading slashes when listeners and emits are down inside Util/Emitter-trait

2025-03-10 11:36 UTC, ChristophWurst commented
Conflicts like crazy -> redo in smaller steps

2025-03-10 11:36 UTC, closed without merging