feat: mail provider settings
nextcloud/server pull request #48134
Opened 2024-09-17 11:48 UTC by SebastianKrupinski

* Resolves: #https://github.com/nextcloud/server/issues/5080

2024-09-17 13:45 UTC, susnux commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +/** @template-implements IEventListener<DeclarativeSettingsRegisterFormEvent> */
```suggestion
/** @template-implements IEventListener<DeclarativeSettingsGetValueEvent|DeclarativeSettingsRegisterFormEvent|DeclarativeSettingsSetValueEvent> */
```

2024-09-17 13:46 UTC, susnux commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +	private function handleSetValue(Event $event) {
```suggestion
	private function handleSetValue(Event $event): void {
```

2024-09-17 14:23 UTC, SebastianKrupinski commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +/** @template-implements IEventListener<DeclarativeSettingsRegisterFormEvent> */
Ty

2024-09-17 16:19 UTC, SebastianKrupinski commented
@marcoambrosini

2024-09-17 17:34 UTC, kesselb requested changes, later dismissed
config.sample.php needs an update

2024-09-17 17:34 UTC, kesselb commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +			'description' => $this->l->t('System e-mails are messages generated automatically by Nextcloud. They are sent for example when a share is created or when inviting attendees to a calendar event..')
> They are sent for example when a share is created

I find it weird to use "share is created" as an example because we don't use the mail provider there.

2024-09-17 17:34 UTC, kesselb commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +				$this->config->setSystemValue('mail_providers_disabled', $event->getValue());
I don't know how you planned the feature with @ChristophWurst, but changing values in config.php via web admin is tricky. 

Examples:

1) config_is_read_only = true
2) multiple config files (the additional configuration files overwrite the values in config.php, setSystemValue modifies only config.php not the additional configuration files)
3) The unfinished and undocumented "overwrite configuration variables via env" feature may overload the variable as well.

That's all unrelated to this pull request, but the incomplete handling in our configuration classes is the reason that we usually don't change config.php via web admin. 

I recommend against adding a ui with system config as backend.

2024-09-17 17:34 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
```suggestion
			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
```

Must be documented in https://github.com/nextcloud/server/blob/master/config/config.sample.php.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html is also generated from the config.sample.php.

2024-09-17 17:34 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
```suggestion
			if ($this->config->getSystemValueBool('mail_providers_disabled', false)) {
```

2024-09-17 17:34 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
Easier to use/read: mail_providers_enabled with default true

2024-09-17 17:56 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
This is what design wanted...

2024-09-17 17:58 UTC, SebastianKrupinski commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +				$this->config->setSystemValue('mail_providers_disabled', $event->getValue());
This feature functions identical to the new Windows support feature that was put in last month

2024-09-17 18:03 UTC, kesselb commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +			'description' => $this->l->t('System e-mails are messages generated automatically by Nextcloud. They are sent for example when a share is created or when inviting attendees to a calendar event..')
I'm quite sure that design wanted a description of what the feature actually does. I can't imagine that design asked you to mention in the description that this feature toggle affects the behavior of the sharebyemail provider, whereas it doesn't affect it.

2024-09-17 18:35 UTC, provokateurin commented on apps/settings/lib/Listener/MailSettingsEventListener.php
Please at least use https://github.com/nextcloud/server/blob/master/apps/testing/lib/Settings/DeclarativeSettingsForm.php if you really want to do this.

2024-09-19 09:56 UTC, marcoambrosini commented on apps/settings/lib/Listener/MailSettingsEventListener.php
> +			'description' => $this->l->t('System e-mails are messages generated automatically by Nextcloud. They are sent for example when a share is created or when inviting attendees to a calendar event..')
Yep, if we don't use the mail provider there than the example is wrong and we should change it to something that is actually affected by the setting

2024-09-24 01:30 UTC, SebastianKrupinski commented
![image](https://github.com/user-attachments/assets/f218d781-d840-492e-b304-1535f5b93b94)

Latest version

2024-09-24 09:48 UTC, marcoambrosini approved these changes
✅ from design

2024-09-24 10:19 UTC, kesselb commented
The Linter is failing.

2024-10-07 10:53 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getValueInt('core', 'mail_providers_disabled', 0) === 0) {
Yep, therefore I suggested it ;)

2024-10-07 11:03 UTC, kesselb commented on apps/settings/lib/Settings/Admin/SystemMail.php
> +			'title' => $this->l->t('System Mails'),
I spoke with Marco, and he's okay with adjusting the text to make the feature easier to understand.

2024-10-07 11:07 UTC, kesselb commented on apps/settings/lib/Settings/Admin/SystemMail.php
> +			'description' => $this->l->t('System emails are automatically generated by Nextcloud when people perform actions like inviting others to calendar events.'),
I believe it would be really helpful to adjust the description here, making the function easier to understand.

2024-10-07 20:08 UTC, kesselb commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getValueInt('core', 'mail_providers_disabled', 0) === 0) {
Just in case you meant "does not" instead of "does" ;)

`DeclarativeSettingsTypes::STORAGE_TYPE_INTERNAL`: Does not support booleans

`DeclarativeSettingsTypes::STORAGE_TYPE_EXTERNAL`: The controller will emit an even, the rest is up to you and therefore we can use booleans here.

2024-10-21 12:58 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getSystemValueInt('mail_providers_disabled', 0) === 0) {
The forms do not work properly with boolean types, to make it less confusing I made it an integer, this way we don't need to cast them. But sure I've made change.

2024-10-21 13:02 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +			if ($this->config->getValueInt('core', 'mail_providers_disabled', 0) === 0) {
>DeclarativeSettingsTypes::STORAGE_TYPE_INTERNAL: Does not support booleans

>DeclarativeSettingsTypes::STORAGE_TYPE_EXTERNAL: The controller will emit an even, the rest is up to you and therefore we can use booleans here.

Its not the retrieving and saving that does not work properly, the actual forms don't handle boolean properly. So they need to be case to integers either way, which then is confusing. But sure, done.

2024-10-21 13:06 UTC, SebastianKrupinski commented on apps/settings/lib/Listener/SystemMailSettingsListener.php
> +		$event->setValue(
Sure

2024-10-21 13:07 UTC, SebastianKrupinski commented on apps/settings/lib/Listener/SystemMailSettingsListener.php
> +		switch ($event->getFieldId()) {
sure

2024-10-24 20:57 UTC, keunes commented on apps/settings/lib/Settings/Admin/SystemMail.php
> +			'description' => $this->l->t('System emails are automatically generated by Nextcloud when people perform actions like inviting others to calendar events.'),
This setting & explanation would only be available/visible from a certain Nextcloud version, right? If so, the 'version 30' could be dropped I think? (Only the Mail version would need to be mentioned, as the other condition is already fulfilled by definition).

2024-11-12 16:56 UTC, kesselb commented on apps/settings/lib/Settings/Admin/SystemMail.php
> +			'description' => $this->l->t('System emails are automatically generated by Nextcloud when people perform actions like inviting others to calendar events.'),
> Mail provider enables sending emails directly through the user’s personal email account. At present, this functionality is limited to calendar invitations. It requires Nextcloud Mail 4.1 and an email account in Nextcloud Mail that matches the user's email address in Nextcloud.

2024-11-13 13:31 UTC, kesselb approved these changes

2024-11-13 13:31 UTC, merged

2024-11-13 13:31 UTC, kesselb commented
/backport to stable30