feat(deps): Upgrade phpseclib to v3
nextcloud/server pull request #48183
Opened 2024-09-18 17:58 UTC by susnux

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-11-05 22:48 UTC, susnux commented
Problem with this:
`Checker::createSignatureData` does create a different signature... No idea what is happening the parameters are the same.

2025-07-08 15:19 UTC, joshtrichards commented
Perhaps `phpseclib2_compat` as an intermediate step for v31+ (or at least v32+)?

https://phpseclib.com/docs/why#phpseclib2_compat

2025-09-26 01:15 UTC, joshtrichards commented on apps/files_external/lib/Lib/Auth/PublicKey/RSAPrivateKey.php
> +		$auth->withPassword($this->config->getSystemValue('secret', ''));
```suggestion
		$auth = $auth->withPassword($this->config->getSystemValue('secret', ''));
```
v3 is immutable

2025-09-26 01:16 UTC, joshtrichards commented on apps/files_external/lib/Lib/Auth/PublicKey/RSAPrivateKey.php
> +			$auth->withPassword('');
```suggestion
			$auth = $auth->withPassword('');
```

2025-09-26 01:43 UTC, joshtrichards commented on apps/files_external/lib/MountConfig.php
L220 for v3

	private static function getCipher() {
		$cipher = new AES('cbc');

2026-01-15 23:03 UTC, terrafrost commented on apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
> +			$auth = RSACrypt::loadPrivateKey(
Might be nice to support EC / DSA keys as well. One can do that thusly:

```php
$auth = \phpseclib3\Crypt\PublicKeyLoader::load(
    $storage->getBackendOption('private_key'),
    $this->config->getSystemValue('secret', '');
);
if (!$auth instanceof \phpseclib3\Crypt\Common\PrivateKey) {
    throw new \Exception('A private key needs to be loaded - not a ' . $auth::class . ' key');
}
```
I suppose it might also be worthwhile to realize that if no key can be detected (eg. you try to load a PHP file as a key) then a `\phpseclib3\Exception\NoKeyLoadedException` will be thrown.

That said, if more than just RSA keys are going to be supported then renaming the class would prob be appropriate as well.

2026-07-19 19:15 UTC, susnux commented on apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
> +			$auth = RSACrypt::loadPrivateKey(
Please open a feature request and if you like also implement that then as a contribution.
We would be happy to review such contribution :)

But for this pull request new features are out-of-scope.

2026-07-20 09:58 UTC, susnux commented on apps/files_external/lib/Lib/Storage/SFTPReflection.php
Any options on this solution?
Should we keep the "performance" streams with reflection or drop them completely and just use the library streams?

2026-07-20 14:20 UTC, nickvergessen commented
Should document this change, as it breaks at least 2 shipped apps (app_api, nextcloud_announcements) by removing phpseclib 2, and integration_discourse because it ships phpseclib 3 without mozart/namespacing it

2026-07-21 11:55 UTC, susnux commented
> as it breaks at least 2 shipped apps

we can add the phpseclib_compat package to add intermediate support for those apps.

2026-07-21 12:07 UTC, nickvergessen commented
> we can add the phpseclib_compat package to add intermediate support for those apps.

Documenting it now and early should be good enough

2026-07-21 13:07 UTC, miaulalala requested changes
Did some benchmarking, scripts and instructions in the linked gist below. 

Ran `SFTPReadStream`/`SFTPWriteStream` against plain `SFTP::get()`/`put()` to check whether the pipelining they're meant to provide actually pays off.

### Setup: 
- standalone PHP script, real phpseclib3 v3.0.55 via Composer, the three files from this branch dropped in unmodified, against a local `atmoz/sftp` container. Tested both on localhost and with ~30ms latency injected via `tc netem` inside the container, to approximate a real remote host.

### Results (medians over 5 runs):

localhost, no injected latency, 20 MiB:
- write: public `put()` 247ms vs. reflection stream 9,659ms (~39x slower)
- read: public `get()` 238ms vs. reflection stream 218ms (roughly even)

~30ms injected latency, 1 MiB:
- write: public `put()` 844ms vs. reflection stream 1,641ms (~1.9x slower)
- read: public `get()` 883ms vs. reflection stream 1,173ms (~1.3x slower)

The reflection streams were slower than the public API in pretty much every condition I tried, not faster. I checked this isn't a benchmark artifact (MD5 of the round-tripped file matches the input, so no silent retries).

`SFTPWriteStream::stream_flush()` sends one 64 KiB packet and immediately blocks on `read_put_responses(1)` per chunk. Fully synchronous, not pipelined. 

phpseclib3's own public `put()` already queues up to `NET_SFTP_UPLOAD_QUEUE_SIZE` (1024) packets before batch-reading responses, i.e. it already does the windowed upload the custom stream's docblock claims to add, and does it better. 

`SFTPReadStream` does have one-chunk read-ahead, which is why it's closer, but it still trails `get()` once latency is added.

Script + full setup/repro instructions: https://gist.github.com/miaulalala/ef2ed83521e515984dc26ed8bd60a154

AI was used to create the scripts and benchmark data, so please reconfirm with your own local setup. If those numbers are confirmed for someone else too, I'd vote for dropping the custom streams and using the library's public API.

ETA: added some latency runs in the gist, too, if you're interested.

2026-07-21 13:40 UTC, CarlSchwan approved these changes
I feel like having up to date security relevant dependency is more important than performance

2026-07-21 13:41 UTC, susnux commented
@miaulalala thats the wrong comparison, simple put / get will always be faster.
But this is about streams as we need stream API. So the proper comparison would be custom streams vs phpseclib streams.

We optimize for round trips, so latency needs to be taken into account for the write stream.
With that in mind the benchmark results are different:

| RTT | Size | Op | Custom | phpseclib built-in | Speedup (custom ÷ phpseclib) |
|-------|-------|-------|-------------|--------------------|------------------------------|
| ~0 ms (LAN) | 1 MB | write | 1.84 MB/s | 33.58 MB/s | 0.05× |
| ~0 ms (LAN) | 1 MB | read | 297.88 MB/s | 29.48 MB/s | 10.1× |
| ~0 ms (LAN) | 8 MB | write | 1.94 MB/s | 31.38 MB/s | 0.06× |
| ~0 ms (LAN) | 8 MB | read | 315.47 MB/s | 27.30 MB/s | 11.6× |
| ~0 ms (LAN) | 32 MB | write | 1.90 MB/s | 38.23 MB/s | 0.05× |
| ~0 ms (LAN) | 32 MB | read | 420.94 MB/s | 37.20 MB/s | 11.3× |
| ~20 ms | 1 MB | write | 1.31 MB/s | 0.25 MB/s | 5.2× |
| ~20 ms | 1 MB | read | 7.86 MB/s | 0.25 MB/s | 31.8× |
| ~20 ms | 8 MB | write | 1.68 MB/s | 0.25 MB/s | 6.7× |
| ~20 ms | 8 MB | read | 20.02 MB/s | 0.25 MB/s | 80.2× |
| ~20 ms | 32 MB | write | 1.69 MB/s | 0.25 MB/s | 6.7× |
| ~20 ms | 32 MB | read | 21.35 MB/s | 0.25 MB/s | 84.9× |

Benchmark source: https://gist.github.com/susnux/77ccaaf3b3e7b7779d7f9725ea22eb69

2026-07-21 18:30 UTC, miaulalala approved these changes

2026-07-21 21:08 UTC, merged

2026-07-22 19:58 UTC, susnux commented
Documentation in https://github.com/nextcloud/documentation/pull/15366