Add rector config
nextcloud/server pull request #48223
Opened 2024-09-19 17:18 UTC by come-nc

## Summary

And so it begins…

1. Added rector in a vendor-bin
2. Added a mostly-empty configuration
3. Applied to apps folder

Long term goal is to apply rectors from https://github.com/nextcloud-libraries/rector to core code. We’ll need to be extra careful with folders like lib/public because they use some deprecated stuff on purpose I think.
So not sure if the best way forward is to add more rules or more folders.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-19 17:32 UTC, provokateurin requested changes
Can you add a script like https://github.com/nextcloud/groupfolders/blob/532f734b9d729a3c29a7371faf0bb85a24e0b311/composer.json#L26? This makes it a lot easier to use rector.

2024-09-19 17:32 UTC, provokateurin commented on rector.php
> +	])
Please put this into the first commit

2024-09-19 18:36 UTC, provokateurin requested changes

2024-09-19 18:36 UTC, provokateurin commented on rector.php
> +		__DIR__ . '/apps',
Make sure to exclude any git ignored paths like cs-fixer

2024-09-20 15:07 UTC, provokateurin commented
Uhm is it really supposed to run on 50323 files? To me it looks like it includes way too much.

2024-09-20 15:54 UTC, come-nc commented
> Uhm is it really supposed to run on 50323 files? To me it looks like it includes way too much.

1877 for me

2024-09-20 19:18 UTC, provokateurin commented
Maybe because I have my cloned apps in apps/ as well, and then it also scans all the vendors of those and so on.
When ignoring everything that git ignores it should work though.

2024-09-20 19:22 UTC, provokateurin approved these changes
Works, you only need to make the CI happy.

2024-09-23 12:39 UTC, nickvergessen approved these changes

2024-09-23 13:10 UTC, merged