[WeatherStatus] Support more weather codes, change icons, fix style
nextcloud/server pull request #48353
Opened 2024-09-25 11:18 UTC by julien-nc

closes #30551 #47702 

This branch is based on the one of #47702.

* Use icons provided by met.no at https://github.com/metno/weathericons
* Support more weather codes (a few snow ones)
* Fix location icon with dark theme
* Only use icons from `@mdi/svg`
* Fix alignment and color issues
* Make a difference between when no location has been set and when the weather code is unknown/unsupported

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/375a697b-659d-4876-9c5a-1df04ee842e4) | ![image](https://github.com/user-attachments/assets/1e3edc1c-9b27-4401-bdec-583bb47a9592) |
| ![image](https://github.com/user-attachments/assets/80a01fcd-fcda-47b0-b045-c2e2a151f496) | ![image](https://github.com/user-attachments/assets/f8592382-b6d9-4b46-b1a1-0fec19ff191a) |

2024-09-25 13:13 UTC, artonge approved these changes

2024-09-25 13:35 UTC, susnux commented on apps/weather_status/src/App.vue
> +	width: 28px;
Magic value? Why 28px?
Our default icons are 16px (which is ~20px MDI icon size)

2024-09-25 13:35 UTC, susnux commented on apps/weather_status/src/App.vue
> +							class="favorite-color" />
Normally we do not use the favorite color in menus, it was used here to mark the current selected.
So this now changes the behavior as you can no longer see if the current address is a favorite.

Fine with me, but cc @nextcloud/designers

2024-09-25 13:43 UTC, susnux commented on apps/weather_status/img/met.no.icons/clearsky_day.svg
All the new files are missing the license information in `.reuse/dep5`.

Meaning you have to remove the part
```
Files: apps/weather_status/img/cloud-cloud.svg apps/weather_status/img/cloud-dots.svg apps/weather_status/img/cross.svg apps/weather_status/img/drop.svg apps/weather_status/img/fog.svg apps/weather_status/img/half-sun.svg apps/weather_status/img/heavy-rain.svg apps/weather_status/img/light-rain.svg apps/weather_status/img/moon-cloud-heavy-rain.svg apps/weather_status/img/moon-cloud-light-rain.svg apps/weather_status/img/moon-cloud-rain.svg apps/weather_status/img/moon-cloud.svg apps/weather_status/img/moon-small-cloud.svg apps/weather_status/img/moon.svg apps/weather_status/img/rain.svg apps/weather_status/img/snow.svg apps/weather_status/img/sun-cloud-heavy-rain.svg apps/weather_status/img/sun-cloud-light-rain.svg apps/weather_status/img/sun-cloud-rain.svg apps/weather_status/img/sun-cloud.svg apps/weather_status/img/sun-small-cloud.svg apps/weather_status/img/sun.svg apps/weather_status/img/thunder.svg apps/weather_status/img/umbrella.svg
Copyright: 2024 Designed by Freepik, titusurya <https://www.freepik.com/author/titusurya> at <https://www.freepik.com/free-vector/coloured-weather-icons-collection_895655.htm>
License: LicenseRef-freepikLicense
```

and replace with

```
Files: apps/weather_status/img/met.no.icons/*.svg
Copyright: 2015-2017 NRK og Meteorologisk institutt
License: MIT
```

2024-09-25 13:45 UTC, susnux requested changes
License information is important

2024-09-25 14:09 UTC, julien-nc commented on apps/weather_status/src/App.vue
> +						<img :src="futureWeatherIconUrl" class="weather-image" alt="t('weather_status', 'Future weather icon')">
🙈 👍

2024-09-25 14:22 UTC, julien-nc commented on apps/weather_status/src/App.vue
> +							class="favorite-color" />
Brought back the previous behaviour.

2024-09-25 14:23 UTC, julien-nc commented on apps/weather_status/src/App.vue
> +	width: 28px;
I don't mind using 20px. It's just less visible.
I just raised the size as much as possible to make it easier to see/identify the icon. These weather icons are slightly more important than classic ones IMO.

2024-09-25 14:40 UTC, susnux commented on apps/weather_status/src/App.vue
> +	width: 28px;
I agree, but then maybe:
```css
    width: calc(var(--default-clickable-area) - 2 * var(--default-grid-baseline));
```

2024-09-25 14:42 UTC, susnux commented on apps/weather_status/src/App.vue
> +						<img :src="futureWeatherIconUrl" class="weather-image">
Needs to be an empty alt tag to make it hidden in accessible tree:

```suggestion
						<img :src="futureWeatherIconUrl" alt="" class="weather-image">
```

2024-09-25 14:42 UTC, susnux commented on apps/weather_status/src/App.vue
> +				<img v-else :src="weatherIconUrl" class="weather-image">
```suggestion
				<img v-else :src="weatherIconUrl" alt="" class="weather-image">
```

2024-09-25 14:43 UTC, susnux commented on apps/weather_status/src/App.vue
>  				:close-after-click="true"
```suggestion
			<NcActionButton :close-after-click="true"
```

(Sadly) our code style requires this

2024-09-25 14:45 UTC, susnux commented
> License information is important

Thank you for fixing, `LicenseRef-freepikLicense` is now unused so you need to remove that from `/Licenses` directory :)

2024-09-25 14:54 UTC, susnux approved these changes

2024-09-25 14:54 UTC, susnux commented on apps/weather_status/src/App.vue
> +	width: 20px;
If you prefer bigger icons:

```suggestion
	width: calc(var(--default-clickable-area) - 2 * var(--default-grid-baseline));
```

2024-09-25 15:24 UTC, julien-nc commented
/compile

2024-09-25 15:42 UTC, julien-nc commented
/compile

2024-09-25 16:25 UTC, merged

2024-10-22 09:04 UTC, jancborchardt commented
@julien-nc very nice – just one detail: The previous icons worked a bit nicer with the style of Nextcloud, is there a specific reason they got replaced? If not I think it would be good to keep using the previous ones, if that’s ok with you? :)