refactor(apps): Use PHP 5.5 features
nextcloud/server pull request #48362
Opened 2024-09-26 07:24 UTC by provokateurin

## Summary

Setting rector PHP level to 5.3 and 5.4 did not lead to any changes so we can start at 5.5 right away.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-26 07:36 UTC, nickvergessen requested changes

2024-09-26 07:36 UTC, nickvergessen commented on apps/admin_audit/lib/AppInfo/Application.php
> +		Util::connectHook(\OCA\Files_Trashbin\Trashbin::class, 'post_restore', $trashActions, 'restore');
This was created by Christoph the other day.
It is a breaking change:
```php
var_dump('\OCA\Files_Trashbin\Trashbin' === \OCA\Files_Trashbin\Trashbin::class);
// bool(false)
```

We can only do this, if we modify the hooker itself and basically trim leading slashes on connect and emit

2024-09-26 11:04 UTC, provokateurin commented on apps/admin_audit/lib/AppInfo/Application.php
> +		Util::connectHook(\OCA\Files_Trashbin\Trashbin::class, 'post_restore', $trashActions, 'restore');
So the comparison fails, but shouldn't the ::class result in the exact same string content?
Maybe I'm missing something here.

2024-09-26 11:05 UTC, provokateurin commented
Another problem as Psalm reported it: Class strings for classes from apps outside of server don't work. Using stubs for that should be fine, right? And there shouldn't be any problem with loading that code even if the class is not available?

2024-09-26 12:22 UTC, come-nc commented on apps/admin_audit/lib/AppInfo/Application.php
> +		Util::connectHook(\OCA\Files_Trashbin\Trashbin::class, 'post_restore', $trashActions, 'restore');
`\OCA\Files_Trashbin\Trashbin::class` is `'OCA\Files_Trashbin\Trashbin'` without the first `\`

2024-09-26 12:24 UTC, come-nc commented
> Another problem as Psalm reported it: Class strings for classes from apps outside of server don't work. Using stubs for that should be fine, right? And there shouldn't be any problem with loading that code even if the class is not available?

Yeah psalm is annoying with that. It’s perfectly valid to use `\My\Fully\Qualified\Name::class` even if the class does not exists, it still works.

2024-09-26 12:29 UTC, come-nc commented
The only problematic place with starting / should be connectHook, which we should get rid of anyway.
So maybe we first migrate away from hooks in apps before applying this?

2024-09-26 12:36 UTC, provokateurin commented on apps/admin_audit/lib/AppInfo/Application.php
> +		Util::connectHook(\OCA\Files_Trashbin\Trashbin::class, 'post_restore', $trashActions, 'restore');
I see, in the preview IntelliJ displayed it to me with the leading backslash :woman_shrugging:

2024-09-26 12:36 UTC, provokateurin commented
>  So maybe we first migrate away from hooks in apps before applying this?

Sounds good :+1:

2024-10-07 08:16 UTC, closed without merging

2024-10-07 08:16 UTC, provokateurin commented
Closing for now since there is nothing directly actionable here.