fix(ShareAPI): Send mails for mail shares by default
nextcloud/server pull request #48381
Opened 2024-09-26 11:08 UTC by Fenn-CS

## Summary

It looks like, the frontend it needs to provide the `sendMail` param for the backend to decide whether mails would be sent.

Our UI does not have that at the moment so it should default to sending emails always for mail shares.

Not exactly sure how this was handled earlier but this is a good starting point.

Resolves : https://github.com/nextcloud/server/issues/48012

## Checklist

- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-26 11:38 UTC, provokateurin approved these changes
Fix makes sense, curious how it broke though.

2024-09-26 11:38 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			$sendMailBool = filter_var($sendMail, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
```suggestion
			$sendMailBool = $sendMail === 'true';
```
Just check if the value is `true` and disregard everything else as false.

2024-09-26 12:09 UTC, come-nc commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			$sendMailBool = filter_var($sendMail, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
You can directly do `$share->setMailSend($sendMail === 'true');` in the else block.

2024-09-26 13:08 UTC, Fenn-CS commented
/backport to stable30

2024-09-26 13:37 UTC, come-nc approved these changes

2024-09-30 11:13 UTC, provokateurin commented
Why rebase it so often?

2024-09-30 12:35 UTC, Fenn-CS commented
> Why rebase it so often?

Some tests that seem unrelated (cypress especially are failing consistently)...

Re-basing triggers a rerun, but also add the latest updates on master in case something that broke the tests has been resolved. (Because a bunch of other PRs are failing tests too)...

2024-10-07 07:27 UTC, Fenn-CS reviewed
This breaks "File Requests"

https://github.com/nextcloud/server/blob/363ba6b0f5b99583e789695f19dcd96db00508ef/apps/files_sharing/lib/Controller/ShareAPIController.php#L721-L727


Why?

- File requests are sent with an empty string for `shareWith` which the backend uses to check if a shareWith value is available (poorly so)
- The file requests shareType is 4, which is mail share and I am not sure why that is.

2024-10-07 08:07 UTC, provokateurin approved these changes

2024-10-07 08:07 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if (!empty($shareWith) && !is_null($shareWith) && $shareType === IShare::TYPE_EMAIL) {
```suggestion
			if ($shareType === IShare::TYPE_EMAIL) {
```
You don't need these checks because the comparison already handles these cases (and psalm doesn't like it either)

2024-10-07 08:07 UTC, provokateurin requested changes
Oops

2024-10-07 08:15 UTC, provokateurin commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +					shareType: ShareType.Link,
Not sure about this, @skjnldsv what was the idea behind this?

2024-10-07 08:56 UTC, Fenn-CS commented
Add some more context on why the tests are failing and some related stuff with a plausible fix:

Share type setting can be changed (current solution), this seems to prevent the sendMail function for file requests as at now but since the links can be copied and shared, it's way better than breaking email shares on prod.

2024-10-08 08:49 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +					shareType: ShareType.Link,
I only take showers :shower:

2024-10-08 08:49 UTC, skjnldsv requested changes
Blocking, will discuss this in chat for easier comprehension

2024-10-08 08:52 UTC, skjnldsv commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +					shareType: ShareType.Link,
No, a mail share is a link share.
They both behave the same way. A link share does NOT send emails, if we start doing this, then we would break the default sharing rule that admin allows to send emails or not.

If admin allowed email shares, then a file request allow users to add emails and send the notifications
If admin does NOT, then users can only create a share link file request, and have to manually give the link to the recipients :)

2024-10-08 08:56 UTC, skjnldsv commented
> This breaks "File Requests"
> 
> * File requests are sent with an empty string for `shareWith` which the backend uses to check if a shareWith value is available (poorly so)
> * The file requests shareType is 4, which is mail share and I am not sure why that is.

File requests allow to add emails in attributes instead of shareWith. ShareWith does NOT support multiple recipients, and that was the only way to /cleanly/ do it without rewriting the API.
That being said, we allow shareWith to be empty (as for link shares), only if you specify some mails as attributes. This also allow to create a share wthout sending the mails straight away and specify the recipients as a later step.
It's a cleaner UX as you can enter emails OR manually copy the link with token, which we would not have without creating the share.

TLDR:
create share > get token > copy link or edit share to set recipients

2024-10-08 08:58 UTC, skjnldsv commented
My fix would be to set the `sendMail` param to true by default, as file requests set it to false anyway :thinking: 
https://github.com/nextcloud/server/blob/e089e4081108bf93991130c99012ee095aa873bc/apps/files_sharing/lib/Controller/ShareAPIController.php#L568

2024-10-23 20:58 UTC, Fenn-CS commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +					shareType: ShareType.Link,
I don't think this is the right place to check for that. 

A file request is (correct me if I am wrong) : Simply a link that you can send to someone to "requests files"...

The means of sending the link can either be:

- Manually copying the link and sending
- Automatic via mail (after you must have already created the link share)

----

Why should the means for sending the "File request" (link) modify change what a file request is? Does the mail not simply the link ?

My thoughts are, if the admin setting must be enforced, it must be enforced at the step where the user is asked to add emails in file request.

The thing already breaks with emails concerning without even knowing whether the user would end up wanting to send the file request link via email or not.

2024-10-23 21:04 UTC, Fenn-CS commented on apps/files_sharing/src/components/NewFileRequestDialog.vue
> +					shareType: ShareType.Link,
> If admin allowed email shares, then a file request allow users to add emails and send the notifications
> If admin does NOT, then users can only create a share link file request, and have to manually give the link to the recipients :)

Also this seems pretty mixed up, why should the setting for "allowed email shares" affect whether a link should be sent to users via mail or not? 

It a convenience thing and even if it was not "File drop" (now "File requests") really had nothing to do with email shares?

In other words if we have something that is actually called "e/mail shares" the admin setting that controls or disables that should not control two things because in my opinion a "File requests" is not a mail share. (Because all mail shares are links shares sent via mail, but link shares are not and should mail shares even if they are sent via mail)

2024-10-23 21:05 UTC, Fenn-CS commented
> My fix would be to set the sendMail param to true by default, as file requests set it to false anyway 🤔

and what about other things that use the API without specifying what goes to `sendMail`???

2024-10-24 09:58 UTC, susnux commented
> and what about other things that use the API without specifying what goes to sendMail???

Agree, we can not change default behavior as this would be a breaking change.

2024-10-24 09:59 UTC, susnux commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if (!empty($shareWith) && $shareType === IShare::TYPE_EMAIL) {
hm I thought we do not use `empty` for strings?

2024-10-24 13:34 UTC, skjnldsv commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> -		}
That should still be needed to send the email after creation

2024-10-24 13:40 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> -		}
True

2024-10-24 13:41 UTC, skjnldsv approved these changes

2024-10-24 14:37 UTC, provokateurin requested changes

2024-10-24 14:37 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if ($shareType === IShare::TYPE_EMAIL && strlen($shareWith) !== 0) {
```suggestion
			if ($shareType === IShare::TYPE_EMAIL && $shareWith !== null && strlen($shareWith) > 0) {
```

$shareWith can be null as well and this would fail without a proper check.

2024-10-24 15:54 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if ($shareType === IShare::TYPE_EMAIL && strlen($shareWith) !== 0) {
Actually no, `strlen(null) === 0`  is true.

2024-10-24 16:05 UTC, Fenn-CS commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if ($shareType === IShare::TYPE_EMAIL && strlen($shareWith) !== 0) {
Hmmm, looks like this is deprecated on `php8.2+` though I tested it and it worked.

2024-10-24 16:28 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +			if ($shareType === IShare::TYPE_EMAIL && strlen($shareWith) !== 0) {
Ok fine by me then, although it would be better to explicitly check it for the future.

2024-10-24 16:28 UTC, provokateurin approved these changes

2024-10-24 16:28 UTC, merged