fix(settings): Sort all settings - incl declarative settings - by priority
nextcloud/server pull request #48424
Opened 2024-09-27 19:44 UTC by susnux

* Resolves: #47109 

## Summary

Previously declarative settings were sorted by priority but behind the "native" settings, this is now fixed, meaning a declarative setting with higher priority than an `ISetting` will be correctly rendered before that `ISetting` in the settings list.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-09-27 19:45 UTC, susnux commented
cc @SebastianKrupinski

2024-09-28 06:03 UTC, provokateurin requested changes
Psalm is not happy, please fix

2024-09-28 06:03 UTC, provokateurin commented on apps/settings/lib/Controller/CommonSettingsTrait.php
>  	private function getIndexResponse(string $type, string $section): TemplateResponse {
These params don't exist

2024-09-28 06:03 UTC, provokateurin commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +				throw new NotAdminException('Logged in user does not have permission to access these settings.');
Causality between this error message and empty settings might not be there, something else could cause no settings to be returned.

2024-09-28 08:25 UTC, susnux commented on apps/settings/lib/Controller/CommonSettingsTrait.php
> +				throw new NotAdminException('Logged in user does not have permission to access these settings.');
This is not new just moved.
If there is another error than the other error should throw, this only happens if the current user does not have permissions (required for admin delegation where normal users can see parts of the admin settings).

2024-09-28 12:19 UTC, provokateurin approved these changes

2024-09-28 16:07 UTC, SebastianKrupinski approved these changes
Tested. Works great!

2024-09-28 17:45 UTC, merged