chore: Move from Twitter to X
nextcloud/server pull request #48486
Opened 2024-10-01 12:56 UTC by Fenn-CS

## Description

Update twitter logo

Resolves : https://github.com/nextcloud/server/issues/48408

## Screenshots

| Before | After |
| ---------- | ------- |
|![old-devnotes](https://github.com/user-attachments/assets/577ee749-9a37-4032-8e65-890d41d5b4db) | ![Screenshot from 2024-10-01 14-50-32](https://github.com/user-attachments/assets/1fea2ff2-1d3f-4340-aaee-39156fe09164) |

2024-10-01 12:58 UTC, Fenn-CS commented on apps/settings/templates/settings/personal/development.notice.php
> +				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="M 2
@JuliaKirschenheuter @marcoambrosini any tips on how to properly generate the path in that it centralizes itself in the circle path?

Maybe a tool? Too bad I can't write in svg :grin:

2024-10-01 16:14 UTC, provokateurin commented on apps/settings/templates/settings/personal/development.notice.php
> +				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="M 2
```suggestion
				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="m 3.384891,2.6 c -0.3882,0 -0.61495,0.4362184 -0.39375,0.7558594 L 6.5841098,8.4900156 2.9770785,12.707422 C 2.7436785,12.979821 2.9370285,13.4 3.2958285,13.4 H 3.694266 c 0.176,0 0.3430313,-0.07714 0.4570313,-0.210938 L 7.294266,9.5065156 9.6602817,12.887891 C 9.8762817,13.208984 10.25229,13.4 10.743485,13.4 h 1.900391 c 0.3882,0 0.61575,-0.436688 0.39375,-0.754688 L 9.2466097,7.2195156 12.682547,3.1941408 C 12.881744,2.9601408 12.715528,2.6 12.407473,2.6 h -0.506566 c -0.175,0 -0.34186,0.076453 -0.45586,0.2197656 L 8.5405785,6.2058438 6.3790317,3.1132812 C 6.1568442,2.7913687 5.6965004,2.6 5.3958285,2.6 Z" fill="var(--color-main-background)"/></svg>',
```
Centered it with Inkscape

2024-10-01 16:15 UTC, provokateurin commented on apps/settings/templates/settings/personal/development.notice.php
> +				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="M 2
```suggestion
				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="m 3.384891,2.6 c -0.3882,0 -0.61495,0.4362184 -0.39375,0.7558594 L 6.5841098,8.4900156 2.9770785,12.707422 C 2.7436785,12.979821 2.9370285,13.4 3.2958285,13.4 H 3.694266 c 0.176,0 0.3430313,-0.07714 0.4570313,-0.210938 L 7.294266,9.5065156 9.6602817,12.887891 C 9.8762817,13.208984 10.25229,13.4 10.743485,13.4 h 1.900391 c 0.3882,0 0.61575,-0.436688 0.39375,-0.754688 L 9.2466097,7.2195156 12.682547,3.1941408 C 12.881744,2.9601408 12.715528,2.6 12.407473,2.6 h -0.506566 c -0.175,0 -0.34186,0.076453 -0.45586,0.2197656 L 8.5405785,6.2058438 6.3790317,3.1132812 C 6.1568442,2.7913687 5.6965004,2.6 5.3958285,2.6 Z" fill="var(--color-main-background)"/></svg>',
```
Centered it with Inkscape

2024-10-01 16:15 UTC, provokateurin requested changes

2024-10-01 16:15 UTC, provokateurin commented on apps/settings/templates/settings/personal/development.notice.php
> +				$l->t('Follow us on x'),
```suggestion
				$l->t('Follow us on X'),
```

2024-10-02 08:33 UTC, Fenn-CS commented on apps/settings/templates/settings/personal/development.notice.php
> +				'<svg aria-hidden="true" width="50" height="50" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="8" fill="var(--color-text-maxcontrast)"/><path d="M 2
thanks @provokateurin looks way better.

2024-10-02 08:42 UTC, szaimen approved these changes
LGTM but didnt test

2024-10-02 09:57 UTC, Fenn-CS commented
/backport to stable30

2024-10-02 10:03 UTC, provokateurin approved these changes

2024-10-02 10:03 UTC, merged