[taskprocessing] new command to get a task from a task ID
nextcloud/server pull request #48496
Opened 2024-10-01 15:22 UTC by julien-nc

Also, include error_message in list and get commands results.

2024-10-01 16:06 UTC, kyteinsky approved these changes
yayy :tada:

2024-10-01 16:09 UTC, provokateurin requested changes

2024-10-01 16:09 UTC, provokateurin commented on core/Command/TaskProcessing/GetCommand.php
> +				'User for whom the addressbook will be created'
Wrong argument description

2024-10-01 16:09 UTC, provokateurin commented on core/Command/TaskProcessing/GetCommand.php
> +			->setDescription('get task')
A description that is more than the command name would be helpful

2024-10-01 16:09 UTC, provokateurin commented on core/Command/TaskProcessing/GetCommand.php
> +		$jsonTask['error_message'] = $task->getErrorMessage();
Why is `error_message` not already in the array from jsonSerialize()?

2024-10-01 16:09 UTC, provokateurin commented on core/Command/TaskProcessing/ListCommand.php
> +			$jsonTask['error_message'] = $task->getErrorMessage();
Same here

2024-10-01 18:31 UTC, julien-nc commented on core/Command/TaskProcessing/GetCommand.php
> +		$jsonTask['error_message'] = $task->getErrorMessage();
Because there are "Db" task entities and public tasks (different class). The public class is meant to be returned by the API. We don't want the error message in the API responses.

2024-10-01 18:58 UTC, provokateurin approved these changes

2024-10-01 21:42 UTC, merged

2024-10-02 08:07 UTC, marcelklehr commented
:tada: Thank you!