chore: Replace Twitter & Diaspora links and text
nextcloud/server pull request #48520
Opened 2024-10-02 09:37 UTC by Fenn-CS

- Use Twitters new name "X"
- Remove Diaspora social and include Mastodon instead

Resolves : https://github.com/nextcloud/server/issues/48409

## Screenshots

2024-10-02 09:57 UTC, Fenn-CS commented
/backport to stable30

2024-10-02 09:59 UTC, Fenn-CS commented
/compile

2024-10-02 10:03 UTC, provokateurin requested changes

2024-10-02 10:03 UTC, provokateurin commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				{{ t('federatedfilesharing', 'Formerly Twitter') }}
```suggestion
				{{ t('federatedfilesharing', 'X (formerly Twitter)') }}
```
I think it is preferred to have it this way (or just remove the entire Twitter part).

2024-10-02 10:46 UTC, artonge commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +					<svg width="20"
No other way to have the X icon?

2024-10-02 11:07 UTC, szaimen commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				{{ t('federatedfilesharing', 'Formerly Twitter') }}
I think keeping the twitter part is better. Since X is not really a word imo

2024-10-02 11:16 UTC, provokateurin commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				{{ t('federatedfilesharing', 'Formerly Twitter') }}
Agreed, just shows this rename was stupid

2024-10-02 12:46 UTC, Fenn-CS commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +					<svg width="20"
I tried a couple they all look really, so I just used a vector of the real x logo

2024-10-02 13:20 UTC, provokateurin commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +					<svg width="20"
What about the license of the icon then?

2024-10-02 13:32 UTC, Fenn-CS commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +					<svg width="20"
I don't know any to be honest, it's just a copy and paste of the centralized version you made.

2024-10-07 15:10 UTC, susnux commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				{{ t('federatedfilesharing', 'Mastodon') }}
This is a brand name so we do not need to translate it

```suggestion
				Mastodon
```

2024-10-07 16:28 UTC, susnux commented on apps/federatedfilesharing/src/components/PersonalSettings.vue
> +				{{ t('federatedfilesharing', 'Mastodon') }}
but not related

2024-10-07 16:29 UTC, susnux approved these changes
Just replaced the icons with the proper ones from `core/img` for legal reasons.

![Screenshot 2024-10-07 at 18-14-26 Sharing - Personal settings - Nextcloud](https://github.com/user-attachments/assets/d474fa7e-8203-47c2-ac8a-51a647716ce8)
![Screenshot 2024-10-07 at 18-14-18 Sharing - Personal settings - Nextcloud](https://github.com/user-attachments/assets/5b8c1a30-db18-4f71-b694-6f6f48b513e5)

2024-10-07 16:31 UTC, provokateurin approved these changes

2024-10-07 18:48 UTC, susnux commented
/compile

2024-10-08 19:02 UTC, merged