fix: do not reduce count for subadmins if they are members of group
nextcloud/server pull request #48532
Opened 2024-10-02 13:32 UTC by Antreesy

* Follow-up to #48437

## Summary

Counter on sidebar doesn't reflect the actual number of group members, if subadmin is a member too.
For each group, counter is reduced by 1, and for 'All accounts', counter is reduced by amount of groups subadmin is in.

Commented out lines to not mess much with a code and backports.

There is a comment:
> we prevent subadmins from looking up themselves so we lower the count of the groups he belongs to

but I don't see a point of it, since we fetch and show yourself in the list anyway, so just removing inconsistency

Before | After
-- | --
<img width="395" alt="image" src="https://github.com/user-attachments/assets/cfa7aa13-e5b9-4a09-92d5-0dfe88c9783b"> | <img width="387" alt="image" src="https://github.com/user-attachments/assets/ba6de883-d348-4b04-8d06-0fddd6de3ea3">
_Subadmin: 'alice', member of 'test group' and 'test group 2'_

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-02 14:23 UTC, provokateurin requested changes

2024-10-02 14:23 UTC, provokateurin commented on apps/settings/lib/Controller/UsersController.php
> +					// }
Just get rid off the whole thing, I agree it doesn't make much sense to do these subtractions.

2024-10-02 14:23 UTC, provokateurin commented
/backport to stable30

2024-10-02 14:23 UTC, provokateurin commented
/backport to stable29

2024-10-02 14:23 UTC, provokateurin commented
/backport to stable28

2024-10-02 16:43 UTC, provokateurin approved these changes

2024-10-04 18:03 UTC, blizzz approved these changes

2024-10-04 18:03 UTC, merged

2024-10-04 18:21 UTC, Antreesy commented
/backport to stable30