fix(BackgroundJobs): Adjust intervals and time sensitivities
nextcloud/server pull request #48600
Opened 2024-10-07 15:39 UTC by provokateurin

## Summary

Some jobs were running a bit too frequent and some were also marked as time sensitive even though their interval was quite high.
There are some more jobs that could probably run less often, but I wasn't sure about them so I left them for now.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-07 16:52 UTC, nickvergessen requested changes

2024-10-07 16:52 UTC, nickvergessen commented on core/BackgroundJobs/CleanupLoginFlowV2.php
> +		$this->setInterval(self::TIME_INSENSITIVE);
```suggestion
		$this->setInterval(60 * 60);
		$this->setTimeSensitivity(self::TIME_SENSITIVE);
```
Should run hourly

2024-10-07 16:52 UTC, nickvergessen commented on lib/private/Preview/BackgroundCleanupJob.php
> +		$this->setInterval(24 * 60 * 60);
I think this also should run more often. But I'm fine with the sensitivity

2024-10-08 08:50 UTC, st3iny approved these changes
DAV, twofactor and preview related changes look good.

2024-10-08 08:56 UTC, nickvergessen approved these changes

2024-10-08 10:25 UTC, merged

2024-11-25 07:28 UTC, provokateurin commented
/backport to stable30

2024-11-25 07:28 UTC, provokateurin commented
/backport to stable29

2024-11-25 07:28 UTC, provokateurin commented
/backport to stable28