feat(settings): migrate AppAPI ExApps management to settings
nextcloud/server pull request #48665
Opened 2024-10-11 15:59 UTC by andrey18106

## Summary

This PR migrates the UI for ExApp management to default Apps management page (settings app).
On backend side in settings app there is only addition for initial state for ExApps UI.
All ExApp related logic is in separate store that uses backend API part of AppAPI.
Also small fix for markdown render.

## TODO

- [ ] Requires https://github.com/nextcloud/app_api/pull/417 AppAPI side changes
- [ ] Backport both to stable30

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-14 13:31 UTC, bigcat88 approved these changes
Checked, the functionality works.

2024-10-14 14:56 UTC, susnux requested changes
Nothing very critical but a lot of stuff summing up. See comments.

2024-10-14 14:56 UTC, susnux commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$exAppFetcher = Server::get(\OCA\AppAPI\Fetcher\ExAppFetcher::class);
This probably should be part of server somewhen^^

@provokateurin do you think we can have stubs here or will have to fill up the baseline?

2024-10-14 14:56 UTC, susnux commented on apps/settings/lib/Controller/AppSettingsController.php
> +					}
This seems very dangerous in the server core, as this is a lot of external logic we do not even have stubs for.
Would be better if there would be a simple `init` command which would do all of this within the *app_api* app.
Like we have for other external stuff where we just inject a manager and then call things like
- `manager->getUpdate()`
- `manager->init()`

or similar, but here logic that might break is included directly into the server.

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +			<div v-if="(listView && !app.preview && !app?.app_api) || (!listView && !screenshotLoaded && !app?.app_api)" class="icon-settings-dark" />
This is getting very unreadable, could this be spilt into better readable computed properties?

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +				return this.app && Object.hasOwn(this.app?.status, 'action') && (this.app.status.action === 'init' || this.app.status.action === 'healthcheck')
Why not simply

```suggestion
				return this.app?.status?.action === 'init' || this.app?.status?.action === 'healthcheck'
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +				return this.app && Object.hasOwn(this.app?.status, 'action') && this.app.status.action === 'deploy'
same here

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +				if (this.app && Object.hasOwn(this.app?.status, 'action') && this.app.status.action === 'deploy') {
Same here, why the `hasOwn`? You can just use the optional chaining operator to simplify the code:

```suggestion
				if (this.app?.status?.action === 'deploy') {
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +					return t('app_api', '{progress}% Deploying', { progress: this.app.status?.deploy })
Why is the `deploy` chained with a `?`? If it can be undefined here you need to have a proper fallback value as otherwise the string does not work. So if it really can be undefined then probably:

```suggestion
					return t('app_api', '{progress}% deploying …', { progress: this.app.status?.deploy ?? '0' })
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +				if (this.app && Object.hasOwn(this.app?.status, 'action') && this.app.status.action === 'deploy') {
Same here with the `hasOwn`...

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +					return t('app_api', '{progress}% Initializing', { progress: this.app.status?.init })
same with the `hasOwn` as above, but also the string has wrong case:

```suggestion
					return t('app_api', '{progress}% initializing …', { progress: this.app.status?.init })
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +					return t('app_api', 'Healthchecking')
This will cause confusion 1. by users 2. by translators, so better make it more explaining what it is (especially as this is not a normal English word).

```suggestion
					return t('app_api', 'Health checking')
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/mixins/AppManagement.js
> +					return t('app_api', '{progress}% Initializing', { progress: this.app.status?.init })
This must never be undefined, add a fallback if it can be undefined otherwise remove the `?`.

```suggestion
					return t('app_api', '{progress}% initializing …', { progress: this.app.status?.init ?? '0' })
```

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/store/app_api_apps.js
> +		showError(t('app_api', 'An error occurred during the request. Unable to proceed.') + '<br>' + error.error.response.data.data.message, { isHTML: true })
Is this really needed, does the message contain **USER** information? Or is this just technical information?
If it has user information (not just technical), then rephrase the message as it will be likely truncated as the first part is even every long.

If it contains user facing information then just show that, as the first part is really unhelpful, otherwise just show the first part and log the error.

2024-10-14 14:56 UTC, susnux commented on apps/settings/src/store/app_api_apps.js
Please do not add new Vuex stores, even settings already has started to use Pinia.
There  should not be any new stuff for Vuex as we are already working on a migration and this just adds more work.

2024-10-14 15:43 UTC, julien-nc reviewed
I'm not sure how likely it is to happen in a production environment but in my dev setup, some apps don't have a licence so when clicking on their list item, the sidebar does not open.
![image](https://github.com/user-attachments/assets/159f1b61-944e-497f-b0d5-d70440627539)

2024-10-15 15:58 UTC, susnux commented
> I'm not sure how likely it is to happen in a production environment but in my dev setup, some apps don't have a licence so when clicking on their list item, the sidebar does not open.

How can this happen? I was pretty sure the license is a required field in appinfo.xml thus the appstore should deny uploading such an app?

2024-10-16 23:19 UTC, andrey18106 commented on apps/settings/src/store/app_api_apps.js
This part is originally a clone of the current old Vuex store for apps, if we rewrite the part from AppAPI that we are merging, then we should rewrite the current one in one place and update all the components relying on them? What would be the suggested approach?

2024-10-16 23:21 UTC, andrey18106 commented
> > I'm not sure how likely it is to happen in a production environment but in my dev setup, some apps don't have a licence so when clicking on their list item, the sidebar does not open.
> 
> How can this happen? I was pretty sure the license is a required field in appinfo.xml thus the appstore should deny uploading such an app?

It's a Test Deploy app, or any other `manual-install` type ExApp, it has no appstore information, only short info from DB.

2024-10-16 23:23 UTC, andrey18106 commented on apps/settings/src/store/app_api_apps.js
> +		showError(t('app_api', 'An error occurred during the request. Unable to proceed.') + '<br>' + error.error.response.data.data.message, { isHTML: true })
Not sure, it wasn't changed because it was originally clone from the settings "apps" Vuex store. Will remove.

2024-10-16 23:24 UTC, andrey18106 commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$exAppFetcher = Server::get(\OCA\AppAPI\Fetcher\ExAppFetcher::class);
AppAPI is shipped since 30.0.1

2024-10-23 16:17 UTC, susnux reviewed
Thank you! Some more comments, then it should be fine.

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/app-types.ts
> +	update: string | null
```suggestion
	update?: string
```

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/app-types.ts
> +	removable: boolean
This should already be inherited by the appstore app (is also available there)

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppDaemonBadge.vue
> +import type { IDeployDaemon } from '../../app-types.ts'
nit pick

```suggestion
import type { IDeployDaemon } from '../../app-types.ts'
import { mdiFileChart } from '@mdi/js'
import NcIconSvgWrapper from '@nextcloud/vue/dist/Components/NcIconSvgWrapper.js'
```

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +			<svg v-else-if="listView && app.preview && !app?.app_api"
```suggestion
			<svg v-else-if="listView && app.preview && !app.app_api"
```

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +			<NcButton v-if="app.canUnInstall || app.canUninstall"
```suggestion
			<NcButton v-if="app.canUnInstall"
```

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +		mdiCogOutline,
This is not an component but a string. Should go into `setup`

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +				:path="mdiCogOutline()"
```suggestion
				:path="mdiCogOutline"
```

see below

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppList/AppItem.vue
> +		},
Just put `mdiCogOutline` into setup.

```suggestion
```

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
> +			<div v-if="appAuthors" class="app-details__section">
How can this not be defined? `author` is a required field:

https://github.com/nextcloud/appstore/blob/5c1825f4b1f594e74e96a23518c4ef58e1671cf8/nextcloudappstore/api/v1/release/info.xsd#L19

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
> +			<div v-if="appCategories" class="app-details__section">
Categories is a required field, how can it be not defined?

https://github.com/nextcloud/appstore/blob/5c1825f4b1f594e74e96a23518c4ef58e1671cf8/nextcloudappstore/api/v1/release/info.xsd#L27C35-L27C43

2024-10-23 16:17 UTC, susnux commented on apps/settings/src/views/AppStoreSidebar.vue
> +				<AppDaemonBadge v-if="app?.app_api && app?.daemon" :daemon="app.daemon" />
```suggestion
				<AppDaemonBadge v-if="app.app_api && app.daemon" :daemon="app.daemon" />
```

2024-10-23 16:31 UTC, andrey18106 commented on apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
> +			<div v-if="appAuthors" class="app-details__section">
ExApps that are manually installed (`manual-install` deploy type) - doesn't have appstore information and info.xml on the server to compose these data, only short information from DB (`oc_ex_apps`), added this just for them, but can be kept like that, it just would be empty section with heading.

2024-10-24 12:35 UTC, susnux commented on apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue
> +			<div v-if="appAuthors" class="app-details__section">
So external apps do not provide those meta data? Because manual installed (not from app store) apps still provide the info.xml
Probably external apps should also provide the same information then, but descoped from this PR.
So see this as resolved, yet I would expect the app_api to provide all required appinfo fields to Nextcloud for their apps.

2024-10-24 12:37 UTC, susnux approved these changes
I did not test with external app but code looks sane, as we need to backport (there will be a refactor on master soon, so lets get this in first).

2024-10-27 16:31 UTC, provokateurin commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$exAppFetcher = Server::get(\OCA\AppAPI\Fetcher\ExAppFetcher::class);
I would try to avoid stubs of apps in server (the other way is fine and useful). Apps guarantee compatibility with certain server versions and not the other way around, so it can get dirty easily.

2024-10-29 12:06 UTC, andrey18106 commented
/compile

2024-10-29 13:24 UTC, andrey18106 commented
/compile

2024-10-29 18:54 UTC, andrey18106 commented
/compile

2024-10-29 18:59 UTC, andrey18106 commented
/backport to stable30

2024-10-29 19:24 UTC, merged