fix(share): Return empty string if no label is set
nextcloud/server pull request #48673
Opened 2024-10-12 15:54 UTC by susnux

* Resolves: https://github.com/nextcloud/server/issues/48629

## Summary

While the database supports NULL, the typing has always said it only returns *string*. So to not break any apps that might trust the typings we should return `''` if the database is set to `NULL`.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-12 15:54 UTC, susnux commented
/backport to stable30

2024-10-12 16:57 UTC, kesselb approved these changes

2024-10-13 06:39 UTC, provokateurin requested changes
Oh then you can actually revert https://github.com/nextcloud/server/pull/47551 where I thought this was intended but wrongly documented!
It was already broken before 30 as well, so please backport to 29 and 28 as well.

2024-10-14 12:14 UTC, susnux commented
> Oh then you can actually revert https://github.com/nextcloud/server/pull/47551 where I thought this was intended but wrongly documented!

I am not sure. The PHP documentation is only stating strings, but the DB accepts null. I personally think `null` is much better for representing the empty label then an empty string. But then again we would break some usage of the API if you trust the doc comments.

2024-10-14 12:14 UTC, come-nc commented
I thought some DB will treat null and empty string the same anyway and so we cannot differentiate in DB, no?

2024-10-14 13:17 UTC, susnux commented
> Oh then you can actually revert https://github.com/nextcloud/server/pull/47551 where I thought this was intended but wrongly documented!

Done

2024-10-14 13:23 UTC, provokateurin approved these changes

2024-10-14 13:40 UTC, come-nc approved these changes

2024-10-14 17:10 UTC, merged

2024-10-14 17:10 UTC, susnux commented
/backport to stable29

2024-10-14 17:37 UTC, provokateurin commented
@susnux not 28?

2024-10-16 18:39 UTC, susnux commented
/backport to stable28