[stable29] fix: Shipped apps should include the Nextcloud version in the cache buster
nextcloud/server pull request #48700
Opened 2024-10-14 16:11 UTC by susnux

Manual backport of https://github.com/nextcloud/server/pull/48650

2024-10-14 16:29 UTC, provokateurin approved these changes

2024-10-15 09:24 UTC, come-nc approved these changes

2024-10-30 08:00 UTC, Altahrim commented
CI error sounds related

2024-10-30 08:37 UTC, provokateurin requested changes
Agreed, @susnux please take a look

2024-10-30 09:50 UTC, provokateurin approved these changes

2024-10-30 11:03 UTC, susnux commented
:writing_hand: todo for later: Move everything from that horrible constructor to the render function or similar.
Due to that we can not even mock that class (partially) because everything is already accessed in the constructor before you can configure the methods...

2024-10-30 12:10 UTC, merged