feat(files): Expose chunked upload config via capabilities
nextcloud/server pull request #48758
Opened 2024-10-17 07:50 UTC by provokateurin

## Summary

Part of https://github.com/nextcloud/server/issues/47682.
`@nextcloud/upload` PR to come.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-17 10:38 UTC, susnux commented on apps/files/lib/App.php
>  		];
Does not hurt, but in general I think we do not need to add new stuff we have in capabilities.

2024-10-17 10:40 UTC, susnux approved these changes

2024-10-18 23:40 UTC, skjnldsv requested changes, later dismissed

2024-10-18 23:40 UTC, skjnldsv commented on apps/files/lib/App.php
> -		$maxChunkSize = (int)Server::get(IConfig::class)->getAppValue('files', 'max_chunk_size', (string)(100 * 1024 * 1024));
We need a migration. This app config is used by many admins

2024-10-19 05:49 UTC, provokateurin commented on apps/files/lib/App.php
> -		$maxChunkSize = (int)Server::get(IConfig::class)->getAppValue('files', 'max_chunk_size', (string)(100 * 1024 * 1024));
Is it there is no documentation about it and also no frontend to change it.

2024-10-19 13:17 UTC, susnux commented on apps/files/lib/App.php
> -		$maxChunkSize = (int)Server::get(IConfig::class)->getAppValue('files', 'max_chunk_size', (string)(100 * 1024 * 1024));
But many users use it and it was often suggested to use in our forums.
So safest would be to add a Migration file where you just transfer the value from app config to system config and delete the app config value afterwards.

2024-10-19 13:53 UTC, provokateurin commented on apps/files/lib/App.php
> -		$maxChunkSize = (int)Server::get(IConfig::class)->getAppValue('files', 'max_chunk_size', (string)(100 * 1024 * 1024));
Sure, I'll add that :+1:

2024-10-21 09:50 UTC, susnux commented on apps/files/lib/Migration/ChunkedUploadConfigRepairStep.php
Is this needed as a repair step? I think this only needed one, no?
So a normal migration would be the easiest as it automatically only runs once.

2024-10-21 11:00 UTC, yemkareems approved these changes

2024-10-21 11:42 UTC, susnux approved these changes

2024-10-21 13:46 UTC, merged