fix(apps-store): Remove apps from force-enabled state when uninstalled
nextcloud/server pull request #48855
Opened 2024-10-23 11:41 UTC by susnux

## Summary

If an app is force-enabled and then uninstalled the force-enabled state was kept. This is now removed, so when the app should be re-installed the compatibility should be reevaluated.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-23 15:47 UTC, provokateurin commented on lib/private/App/AppManager.php
> +	public function ignoreNextcloudRequirementForApp(string $appId, bool $enabled = true): void {
This parameter in conjunction with the method name is a bit ugly.
Would it be possible to have this logic in a separate method instead?

2024-10-23 18:12 UTC, susnux commented on lib/private/App/AppManager.php
> +	public function ignoreNextcloudRequirementForApp(string $appId, bool $enabled = true): void {
How would you name the method? `unignore...`?

2024-10-23 18:18 UTC, provokateurin commented on lib/private/App/AppManager.php
> +	public function ignoreNextcloudRequirementForApp(string $appId, bool $enabled = true): void {
or `removeIgnore...`, but your suggestion is also fine.

2024-10-24 14:46 UTC, artonge commented on lib/private/App/AppManager.php
> +	public function ignoreNextcloudRequirementForApp(string $appId, bool $enabled = true): void {
Can't we prop whether the app is enabled from this method instead of passing the info in the params?

2024-10-29 13:06 UTC, provokateurin requested changes

2024-10-29 13:06 UTC, provokateurin commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
```suggestion
			// If this app was force enabled, remove the force-enabled-state
			$this->appManager->removeOverwriteNextcloudRequirement($appId);
			$this->appManager->clearAppsCache();
```
Is the property missing the typing?

2024-10-29 13:06 UTC, provokateurin commented on apps/settings/lib/Controller/AppSettingsController.php
> +		$appManager->overwriteNextcloudRequirement($appId);
```suggestion
		$appId = $this->appManager->cleanAppId($appId);
		$this->appManager->overwriteNextcloudRequirement($appId);
```

2024-10-29 15:22 UTC, susnux commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
No but this is not a public method.

2024-10-29 16:22 UTC, provokateurin commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
Wdym?

2024-10-29 16:32 UTC, susnux commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
> $this->appManager->removeOverwriteNextcloudRequirement($appId)

Would end up in the baseline, so casting it fist to the private implementation.

2024-10-29 16:38 UTC, provokateurin commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
Ah ok, then ignore my comments.

2024-10-29 16:38 UTC, provokateurin approved these changes

2024-11-04 16:12 UTC, come-nc commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
At this point you might as well inject the private class directly in the constructor property, no?
Hopefully DI has the alias, or you can add it?

2024-11-11 20:15 UTC, susnux commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
Done

2024-11-11 20:39 UTC, skjnldsv approved these changes

2024-11-12 08:34 UTC, come-nc requested changes

2024-11-12 08:34 UTC, come-nc commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appManager->clearAppsCache();
```suggestion
			// If this app was force enabled, remove the force-enabled-state
			$this->appManager->removeOverwriteNextcloudRequirement($appId);
			$this->appManager->clearAppsCache();
```

2024-11-12 08:34 UTC, come-nc commented on apps/settings/lib/Controller/AppSettingsController.php
> +		$appManager->overwriteNextcloudRequirement($appId);
```suggestion
		$appId = $this->appManager->cleanAppId($appId);
		$this->appManager->overwriteNextcloudRequirement($appId);
```

2024-11-18 10:50 UTC, come-nc approved these changes
clean

2024-11-18 13:10 UTC, susnux commented
Adjusted the test :heavy_check_mark:

2024-11-18 13:37 UTC, merged