Fallback to default favicon
nextcloud/server pull request #4888
Opened 2017-05-15 22:01 UTC by juliushaertl

Respond with the default Nextcloud favicon/touchicon instead of a 404 status.

Fix for https://github.com/nextcloud/server/issues/3428

Please review @nextcloud/theming

2017-05-15 22:05 UTC, juliushaertl commented
cc @caco3

2017-05-16 20:28 UTC, MorrisJobke commented
```
curl -X HEAD http://192.168.99.100/server/apps/theming/icon/core -i
HTTP/1.1 200 OK
...
Content-Disposition: inline; filename=""
Content-Length: 2918
Content-Type: text/html; charset=UTF-8
```

* [ ] the content type is wrong

2017-05-17 08:12 UTC, juliushaertl commented
@MorrisJobke Fixed :wink:

2017-05-17 11:58 UTC, rullzer requested changes

2017-05-17 11:58 UTC, rullzer commented on apps/theming/lib/Controller/IconController.php
> +			$fileAccessHelper = \OC::$server->query(FileAccessHelper::class);
Any reason not to inject this so you can do proper unit testing?

2017-05-17 11:58 UTC, rullzer commented on apps/theming/lib/Controller/IconController.php
> +			$fileAccessHelper = \OC::$server->query(FileAccessHelper::class);
Same here

2017-05-17 15:23 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-05-18 08:46 UTC, juliushaertl commented on apps/theming/lib/Controller/IconController.php
> +			$fileAccessHelper = \OC::$server->query(FileAccessHelper::class);
No, guess that was why i started using it :see_no_evil: 

Fixed.

2017-05-18 21:29 UTC, LukasReschke approved these changes

2017-05-18 21:30 UTC, merged