feat: Add `allowed_view_extensions` config node
nextcloud/server pull request #48903
Opened 2024-10-26 00:24 UTC by Koc

## Summary
It isn't possible to view jpg files if they were shared without allow downloading. 

<details><summary>:mag: Reproducer</summary>
<p>
Share file without download possibility

![image](https://github.com/user-attachments/assets/ec480e7e-1e81-4700-ac06-c4d289621f50)

Try to view file as share recipient
![image](https://github.com/user-attachments/assets/a5914e26-940a-4235-92ae-02f1164574a8)
</p>
</details> 

To fix that we can introduce a new `allowed_view_extensions` config node.

```php
  'allowed_view_extensions' => [
    'jpg',
    'jpeg',
    'png',
    // ...
  ]
```

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-26 19:10 UTC, max-nextcloud commented
<details>
<summary>
I added a comment  in the text PR - crossposting here.
</summary>
@Koc Thanks a lot for addressing this. The current state is really confusing.

I'm not sure your proposed solution is really what we want. Before diving into the code I think we should clarify that with @nextcloud/designers .

We're always hesitant to add config options. However this config would not be exposed in the UI I assume. But the problematic scenario would remain for files which are not part of the `allowed_view_extensions` config.

I know the permission setting to prevent downloads is messy. I personally think that this should not exist for the filetypes you list as one can never prevent a screenshot or a copy and paste download. But I'll wait to hear what the designers say.
</details>

2024-10-28 10:39 UTC, susnux requested changes
I think this needs some discussion, as this allows to prevent the use case this settings was meant for.
And also I think this implementation is a bit dangerous as it will allow the download using the WebDAV endpoint, so the whole point of "prevent download" is circumvented.

2025-05-06 12:05 UTC, max-nextcloud commented
I had another look at this today. When originally introduced the 'prevent download' option was only available for office mime types:
https://github.com/nextcloud/server/pull/32482/files#diff-a767a3e36d22b92db810b48aae05bc3cad43c31de6afb17e926ad1dee6f4da31R425-R439

I just tried and now i can also apply it to markdown documents. Might make sense to investigate when and why this change happened.

2025-05-12 15:27 UTC, max-nextcloud commented
> When originally introduced the 'prevent download' option was only available for office mime types:

I had another look at this today with @juliusknorr - turns out the option always blocked all downloads and viewing - it was just using a wrong title on the setting.

We came up with a longer term plan, the first step of which would be the creation of a boolean setting that changes the behavior of internal files regarding `disable downloads` to the one of public shares with their `hide download` setting.

Make this setting default to `hide download` on new instances. If possible only set it to `prevent download` on existing instances if there are internal shares with download disabled.

I'm not sure if this would be a meaningful way to continue this PR. Keeping it open for now.

2025-07-01 13:11 UTC, closed without merging