fix(apps-store): Fix exception on generating preview url for installed app screenshot
nextcloud/server pull request #48912
Opened 2024-10-27 11:39 UTC by claucambra

## Summary

Some installed apps meant for older server versions might unexpectedly offer up screenshot values in a non-string format (e.g. health). Avoid an exception by checking first if the first app screenshot is indeed a string and only then trying to create the $proxyPreviewUrl
## TODO

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [X] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Screenshots before/after for front-end changes
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-10-28 06:40 UTC, nickvergessen requested changes

2024-10-28 06:40 UTC, nickvergessen commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appScreenshot = $app['screenshot'][0];
there are apps without screenshots, so the isset is needed …

Or we make it default to null now as there is a `is_string` check afterwards
```suggestion
			$appScreenshot = $app['screenshot'][0] ?? null;
```

2024-10-28 06:51 UTC, claucambra commented on apps/settings/lib/Controller/AppSettingsController.php
> +			$appScreenshot = $app['screenshot'][0];
Thanks for catching this, I took your suggestion

2024-10-28 06:55 UTC, nickvergessen commented
I'll amend the actual fix...

2024-10-28 07:30 UTC, nickvergessen approved these changes

2024-10-28 10:16 UTC, susnux approved these changes
TIL: Do not trust the appinfo XSD.

2024-10-28 10:32 UTC, merged

2024-10-28 13:19 UTC, nickvergessen commented
> TIL: Do not trust the appinfo XSD.

Well the problem is a bit that PHP's XML engine makes things a string until they appear multiple times :see_no_evil:

2024-11-01 14:46 UTC, joshtrichards commented
/backport to stable30