Add the option to provide a groupname and only see its' members in occ group:list
nextcloud/server pull request #49016
Opened 2024-10-30 13:21 UTC by Keeper-of-the-Keys

Improvements/TODO:

## Summary
As the title states this adds an optional groupname argument to `occ group:list` so you can see the members of just that group.

Now you can do `occ group:list groupname`

If the change is welcome I can work on the further needed steps to get it in.

## TODO
1. Fail/return error if group doesn't exist
2. Only print the members and not the groupname

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
~~- [ ] Screenshots before/after for front-end changes~~
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-11-02 19:34 UTC, Keeper-of-the-Keys commented
@joshtrichards Hey thanks for tagging/milestoning!

Is there anything I can do to help move things along?

2025-01-09 09:06 UTC, come-nc requested changes

2025-01-09 09:06 UTC, come-nc commented on core/Command/Group/ListCommand.php
> +		$groups = $this->groupManager->search((string)$input->getArgument('groupid'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
That’s not ideal, If there are groups `abc` and `abc1` and you use group:list abc you will get both groups?

That said, maybe it’s actually better and we should just document the argument to be a search string and not a group name? Not sure.

I think we should document this as search string and merge it, and in an other PR add a `--list-members` option to `group:info`, that’s what make the most sense to me.

2025-01-09 09:06 UTC, come-nc commented on core/Command/Group/ListCommand.php
> +				'groupid',
```suggestion
				'searchstring',
```

2025-01-09 09:06 UTC, come-nc commented on core/Command/Group/ListCommand.php
> +				'Group id to show only the members of that group',
```suggestion
				'Filter the groups to only those matching the search string',
```

2025-01-09 09:06 UTC, come-nc commented on core/Command/Group/ListCommand.php
> +		$groups = $this->groupManager->search((string)$input->getArgument('groupid'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
```suggestion
		$groups = $this->groupManager->search((string)$input->getArgument('searchstring'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
```

2025-01-12 22:24 UTC, Keeper-of-the-Keys commented on core/Command/Group/ListCommand.php
> +		$groups = $this->groupManager->search((string)$input->getArgument('groupid'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
That sounds like a good way of doing it.

Ideally if no group matching the searchstring is found an error/non zero exit state should also happen I think.

2025-01-16 16:11 UTC, come-nc commented on core/Command/Group/ListCommand.php
> +		$groups = $this->groupManager->search((string)$input->getArgument('groupid'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
Hello,

Do you intend to keep working on this PR or do you want me to take over? (I would most likely simply merge my suggestions below and get it merged).

I do not think it’s necessary to exit with failure on empty search result, that’s a valid result.

2025-01-30 11:50 UTC, Keeper-of-the-Keys commented on core/Command/Group/ListCommand.php
> +		$groups = $this->groupManager->search((string)$input->getArgument('groupid'), (int)$input->getOption('limit'), (int)$input->getOption('offset'));
Hey, sorry about the slow reply, I got so many mails that I did not notice I had been asked a question.

I don't mind either way, if you want me to merge your suggestions that is fine by me or if you want to do it.

I would love to help where I can of course, just let me know what/how you need me to help.

2025-02-03 10:07 UTC, come-nc approved these changes

2025-02-03 10:25 UTC, Altahrim approved these changes

2025-02-03 12:10 UTC, merged

2025-02-03 13:06 UTC, come-nc commented
@Keeper-of-the-Keys Thank you for your contribution!
Would you be interested in a guest account on our Nextcloud Talk instance ? It hosts a dev chat for community. I can send an invite to the email you used in the commits if that’s okay with you.

2025-02-06 08:57 UTC, Keeper-of-the-Keys commented
> @Keeper-of-the-Keys Thank you for your contribution! Would you be interested in a guest account on our Nextcloud Talk instance ? It hosts a dev chat for community. I can send an invite to the email you used in the commits if that’s okay with you.

Thank you, I hope I can contribute more.

If I want to "think" more about refining this particular feature would the nc talk be the place or is it better to do that here?