Fix logo being too big on log in page, fix #4585
nextcloud/server pull request #4910
Opened 2017-05-16 18:35 UTC by jancborchardt

Please review @nextcloud/designers @MorrisJobke @MariusBluem @juliushaertl – it was caused by theming changes. Removing them makes theming still work, and fixes the issue with the logos being way too big, for example even touching the .warning box on error pages.

Before / after:
<img width="1165" alt="bildschirmfoto 2017-05-14 um 22 30 38" src="https://cloud.githubusercontent.com/assets/245432/26041749/fec7236e-38f4-11e7-9387-d3495e53f057.png">
<img width="1000" alt="bildschirmfoto 2017-05-14 um 22 30 27" src="https://cloud.githubusercontent.com/assets/245432/26041750/fecca154-38f4-11e7-9ccf-508696cf766d.png">

2017-05-16 20:21 UTC, MorrisJobke requested changes
Cuts of parts of the image if it is in portrait format. 👎

2017-05-19 14:20 UTC, juliushaertl commented
@jancborchardt I've added another commit to keep the logo stretched to the container when custom themed logos are used.

@MorrisJobke Was that what you were talking about above? Or is it a different issue?

2017-05-19 16:12 UTC, MorrisJobke commented
> @MorrisJobke Was that what you were talking about above? Or is it a different issue?

Yes - works now.

2017-05-19 16:12 UTC, MorrisJobke approved these changes
Tested and works now 👍

2017-05-19 18:49 UTC, LukasReschke approved these changes

2017-05-19 18:50 UTC, merged

2017-05-19 18:50 UTC, LukasReschke commented
@jancborchardt If you want this backported then please open a backport for stable12. Note that it likely will only be included with Nextcloud 12.0.1.

2017-05-19 19:04 UTC, juliushaertl commented
I think we should backport this. PR at #4976