Exclude groups for sharing
nextcloud/server pull request #49217
Opened 2024-11-12 08:55 UTC by T0mWz

See also issue https://github.com/nextcloud/server/issues/49198

Certain application or configuration options require the use of groups. Think of enabling certain apps for a specific group of the option to restrict autocomplete with sharing for only users in a specific group.
When you make use of these options, it can only result in large groups. When someone accidentally shares data with such a group then, it can have data impact in addition to large system impact.

Example array response which we got in on line; https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareesAPIController.php#L200

```
Array
(
    [exact] => Array
        (
            [users] => Array
                (
                )

            [groups] => Array
                (
                )

            [remotes] => Array
                (
                )

            [remote_groups] => Array
                (
                )

            [emails] => Array
                (
                )

            [circles] => Array
                (
                )

            [rooms] => Array
                (
                )

        )

    [users] => Array
        (
            [0] => Array
                (
                    [label] => jupyterUser
                    [subline] => 
                    [icon] => icon-user
                    [value] => Array
                        (
                            [shareType] => 0
                            [shareWith] => jupyterUser
                        )

                    [shareWithDisplayNameUnique] => jupyterUser
                    [status] => Array
                        (
                        )

                )

        )

    [groups] => Array
        (
            [0] => Array
                (
                    [label] => jupyter
                    [value] => Array
                        (
                            [shareType] => 1
                            [shareWith] => jupyter
                        )

                )

            [1] => Array
                (
                    [label] => jupyter1
                    [value] => Array
                        (
                            [shareType] => 1
                            [shareWith] => jupyter1
                        )

                )

        )

    [remotes] => Array
        (
        )

    [remote_groups] => Array
        (
        )

    [emails] => Array
        (
        )

    [lookup] => Array
        (
        )

    [circles] => Array
        (
        )

    [rooms] => Array
        (
        )

    [lookupEnabled] => 1
)
```

From this result we will filter the group `jupyter` as example. 
Array will contain a list of groups which will be excluded for sharing purposes.
```
vi config.php
..
  'blacklisted_groups' =>
  array(
     0 => "admin",
     1 => "jupyter",
     2 => "all_employees",
  ),
..
```

2024-11-13 09:16 UTC, provokateurin requested changes
Please add a test for this

2024-11-13 09:16 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
```suggestion
		// Get a list of groups to exclude from search results
		$sharingDisabledGroups = $this->config->getSystemValue('sharing.disabled_groups', true);
```

This name is too generic for a system option and `blacklist` should be avoided (it's better and clearer to use `blocklist`).

2024-11-13 09:16 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
```suggestion
		// Get a list of groups to exclude from search results
		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', []);
```
The default value needs to be an empty array, as otherwise the later code will fail if the config is not set.

2024-11-13 09:16 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		    $this->result['groups'] = array_values($this->result['groups']);
```suggestion
		    $this->result['groups'] = array_values(array_filter($this->result['groups'], function($group) use ($blacklisted_groups) {
		        return !in_array($group['label'], $blacklisted_groups);
		    }));
```

2024-11-13 09:16 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		    $this->result['exact']['groups'] = array_values($this->result['exact']['groups']);
```suggestion
		    $this->result['exact']['groups'] = array_values(array_filter($this->result['exact']['groups'], function($group) use ($blacklisted_groups) {
		        return !in_array($group['label'], $blacklisted_groups);
		    }));
```

2024-11-13 09:17 UTC, provokateurin commented
Also some documentation in https://github.com/nextcloud/documentation about this would be nice as well.

2024-11-13 09:17 UTC, sorbaugh commented
@tomwezepoel thanks for the contribution and good luch with the reviews!

2024-11-13 09:25 UTC, provokateurin requested changes
Additionally to excluding groups from the search results we should actually prevent creating shares with one of the groups as the recipient. This needs to be implemented in the ShareAPIController.

2024-11-13 09:44 UTC, nfebe commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
```suggestion
		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
		if (!is_array($blacklisted_groups)) {
		    $blacklisted_groups = [];
		}
```

Graceful handling of non array is passed? This can be needless if the source if SURE to provide arrays (when probably not configurable)

2024-11-13 09:50 UTC, artonge reviewed
- [ ] Maybe that logic would fit better in `lib/private/Collaboration/Collaborators/GroupPlugin.php`?
- [ ] The current solution limits which groups you can search for, but don't limit which you can share with. This is probably the place to add that logic: https://github.com/nextcloud-gmbh/server/blob/1d69ffa48948bbcebc892cc89cd8b551940c58eb/lib/private/Share20/Manager.php#L491-L492
- [ ] You'll also need to add checkbox in the admin settings. Probably in `apps/settings/lib/Settings/Admin/Sharing.php`

2024-11-13 09:51 UTC, nfebe reviewed
DRY adjustments and possible type guard addition

2024-11-13 09:51 UTC, nfebe commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
```suggestion
		$blacklisted_groups = $this->config->getSystemValue('blacklisted_groups', true);
		if (!is_array($blacklisted_groups)) {
		    $blacklisted_groups = [];
		}
```

Graceful handling of non array is passed? This can be needless if the source if SURE to provide arrays (when probably not configurable)

2024-11-13 09:51 UTC, nfebe commented on apps/files_sharing/lib/Controller/ShareesAPIController.php
> +		}
```suggestion
       $filterBlacklistedGroups = function ($groups) use ($blacklisted_groups) {
            return array_values(array_filter($groups, function ($group) use ($blacklisted_groups) {
                return isset($group['label']) && !in_array($group['label'], $blacklisted_groups);
            }));
        };

        if (isset($this->result['groups'])) {
            $this->result['groups'] = $filterBlacklistedGroups($this->result['groups']);
        }

        if (isset($this->result['exact']['groups'])) {
            $this->result['exact']['groups'] = $filterBlacklistedGroups($this->result['exact']['groups']);
        }
```

Since the filter logic is repeated, you can use an inline closure..... of define a function outside this method.

2024-11-14 09:21 UTC, T0mWz commented
Thanks for all your feedback, really appreciated. 👍  😃 
We will dive into it!

2024-12-30 17:43 UTC, joshtrichards commented
Closing since it's superseded by replacement PR #49897

2024-12-30 17:43 UTC, closed without merging