chore(profile): move profile app from core to apps
nextcloud/server pull request #49244
Opened 2024-11-13 08:58 UTC by skjnldsv

Fix https://github.com/nextcloud/server/issues/29323

Cleanup core a bit more

2024-11-13 09:06 UTC, provokateurin commented on apps/profile/src/views/Profile.vue
This file is completely new, did you forget to remove the old code? I don't see where you deleted it.

2024-11-13 09:06 UTC, provokateurin commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
> +					$this->urlGenerator->linkToRoute('profile.ProfilePage.index', ['targetUserId' => $widgetData['userId']])
I'm not sure if we consider this a breaking change?
I would be fine merging it, but it could lead to errors elsewhere.
Somewhere in the routing code there is a piece that allows overriding routes, so maybe you can add this there so even the old route will still work.

2024-11-13 09:08 UTC, skjnldsv commented on apps/profile/src/views/Profile.vue
Apparently I forgot yeah! Fixing asap

2024-11-13 09:09 UTC, skjnldsv commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
> +					$this->urlGenerator->linkToRoute('profile.ProfilePage.index', ['targetUserId' => $widgetData['userId']])
> Somewhere in the routing code 

:magic_wand: :mage_woman: any clue oh mighty wizard? :grin:

2024-11-13 09:39 UTC, provokateurin commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
> +					$this->urlGenerator->linkToRoute('profile.ProfilePage.index', ['targetUserId' => $widgetData['userId']])
Found it: https://github.com/nextcloud/server/blob/a489d88a2b2203cffdd08f4a5f1ae03a497bc52f/lib/private/Route/Router.php#L385

2024-11-13 10:38 UTC, skjnldsv commented on apps/user_status/lib/Dashboard/UserStatusWidget.php
> +					$this->urlGenerator->linkToRoute('profile.ProfilePage.index', ['targetUserId' => $widgetData['userId']])
Amazing, thanks!!

2024-11-13 10:57 UTC, provokateurin requested changes
LGTM, just the versions need to be adjusted

2024-11-13 10:57 UTC, provokateurin commented on apps/profile/appinfo/info.xml
> +		<nextcloud min-version="30" max-version="30"/>
```suggestion
		<nextcloud min-version="31" max-version="31"/>
```

2024-11-13 12:16 UTC, provokateurin approved these changes

2024-11-13 17:26 UTC, susnux commented on apps/profile/appinfo/info.xml
> +	<author>Chris Ng</author>
Copy paste error? If yes, how about this for new apps by company:

```suggestion
	<author>Nextcloud GmbH</author>
```

2024-11-13 17:27 UTC, susnux commented on apps/profile/appinfo/info.xml
> +-->
New file?
```suggestion
  - SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
  - SPDX-License-Identifier: AGPL-3.0-or-later
-->
```

2024-11-13 17:28 UTC, susnux commented on apps/profile/appinfo/info.xml
> +	<author>Chris Ng</author>
(same as we do in theming app)

2024-11-14 08:59 UTC, come-nc approved these changes

2024-11-14 10:07 UTC, merged