feat(systemtags): add color support
nextcloud/server pull request #49295
Opened 2024-11-14 19:17 UTC by skjnldsv

![image](https://github.com/user-attachments/assets/477d4e54-d73b-4a58-83a6-53080daa651b)Signed-off-by: skjnldsv <skjnldsv@protonmail.com>

2024-11-15 10:09 UTC, skjnldsv commented
Amazing... :facepalm: 
![image](https://github.com/user-attachments/assets/14d27deb-30e1-42fe-af4a-8df5a0aefe54)

2024-11-20 13:09 UTC, jancborchardt approved these changes
Looks very very nice! I have no feedback. @marcoambrosini?

2024-11-20 13:11 UTC, jancborchardt requested changes, later dismissed
Sorry actually I do have 2 pieces of feedback :D 
- [ ] The popover seems to be very slightly misaligned to the left:
   ![Screenshot From 2024-11-20 14-10-17](https://github.com/user-attachments/assets/8ff90950-b3cc-412d-bd36-9118d6897786)
- [x] There is a stray triangle here: 
   ![image](https://github.com/user-attachments/assets/626a5d66-eae5-43ca-96fd-703cd00fdec9)

2024-11-20 14:03 UTC, marcoambrosini commented
Yep, just those things, which both seem related to the popover positioning. I'll wait for review ping

2024-11-21 07:44 UTC, skjnldsv commented
> * There is a stray triangle here

Lol, it's the scrollbar behind :grin:

2024-11-21 07:52 UTC, skjnldsv commented
@jancborchardt There is also the inline tag display missing on this PR.
But I read many of your comments on the topic from [here](https://github.com/nextcloud/server/issues/6778) and [here](https://github.com/nextcloud/server/issues/6424

I'll keep them like they are right now, no background and color the text+border only, following the WCAG contrast of course.

Quick example (⚠️  contrast not calculated)
![image](https://github.com/user-attachments/assets/d250e122-83c6-45cd-b952-dd6382eeea9f)

2024-12-05 07:56 UTC, marcelklehr commented on lib/private/SystemTag/SystemTagManager.php
> +			->setParameter('color', $color);
Should we validate the color value in the backend? Currently users of the DAV endpoint and the OCP API can just insert anything, I think.

2024-12-05 09:11 UTC, artonge commented on lib/private/SystemTag/SystemTagManager.php
> +			->setParameter('color', $color);
Other option would be to change it during the display to be accessible

2024-12-05 11:30 UTC, artonge approved these changes

2024-12-05 14:34 UTC, marcelklehr commented on lib/private/SystemTag/SystemTagManager.php
> +			->setParameter('color', $color);
So we have to validate on every client that wants to display colors?

2024-12-05 14:37 UTC, marcelklehr commented on lib/private/SystemTag/SystemTagManager.php
> +			->setParameter('color', $color);
This query will throw an SQL exception when you pass 7 characters for example

2024-12-05 18:47 UTC, skjnldsv commented on lib/private/SystemTag/SystemTagManager.php
> +			->setParameter('color', $color);
let me add a quick check :+1:

2024-12-06 08:00 UTC, marcelklehr approved these changes

2024-12-06 09:43 UTC, merged

2024-12-06 12:52 UTC, disaster123 commented
Thanks a lot for this. What is the planend release Version?

2024-12-07 04:51 UTC, marcelklehr commented
@disaster123 Nextcloud 31 Hub 10