fix: don't set 'name' on null metadata
nextcloud/server pull request #49291
Opened 2024-11-14 16:24 UTC by icewind1991

Otherwise the metadata ends up being an array with just the name set.

2024-11-14 16:27 UTC, provokateurin commented
Why is this bad?

2024-11-14 16:29 UTC, icewind1991 commented
> Why is this bad?

Any code using this will assume that a non-null result contains the expected set of metadata, not just a name

2024-11-14 23:18 UTC, provokateurin commented
I see. I also forgot that setting a key on null actually turns it into an array... PHP is fun

2024-11-14 23:18 UTC, provokateurin requested changes

2024-11-14 23:18 UTC, provokateurin commented on lib/private/Files/Storage/Wrapper/Encoding.php
> +		if ($entry) {
```suggestion
		if ($entry !== null) {
```

2024-12-03 18:30 UTC, provokateurin approved these changes

2024-12-03 20:47 UTC, come-nc approved these changes

2024-12-03 20:47 UTC, merged