feat: Allow editing public share token
nextcloud/server pull request #49317
Opened 2024-11-15 23:55 UTC by Pytal

## Summary

- Resolve #45440

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-12-17 08:21 UTC, provokateurin requested changes
Looks mostly good to me :+1:

2024-12-17 08:21 UTC, provokateurin commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		if (!preg_match('/^[a-z0-9-]+$/i', $token)) {
The regex already checks for at least one character, so the first check is not necessary.
Then the entire method can also be a lot simpler by directly returning the result.

2024-12-17 08:21 UTC, provokateurin commented on apps/files_sharing/src/services/TokenService.ts
> +		return token
I would rather just fail completely. There is no good reason the token generation will fail and the methods to generate the tokens could diverge in the future.

2024-12-17 08:21 UTC, provokateurin commented on apps/files_sharing/src/views/SharingDetailsTab.vue
> +						:helper-text="t('files_sharing', 'Set the public share link token to something easy to remember or generate a new token. It is not recommended to use a guessable token for shares which contain
@nextcloud/designers what do you think about this message? I think we should have something better that doesn't first incentivize using something easy and then reverting that in the second sentence

2024-12-17 08:21 UTC, provokateurin commented on apps/settings/src/components/AdminSettingsSharingForm.vue
> +					{{ t('settings', 'Shares with easily guessable tokens may be accessed easily') }}
Two times "easily" in one sentence, this doesn't sound good :sweat_smile:

2024-12-17 08:21 UTC, provokateurin commented on core/templates/layout.public.php
> +				p(!empty($_['pageTitle']) && !empty($_['application']) && $_['pageTitle'] !== $_['application'] ? $_['pageTitle'] . ' - ' : '');
Why this change?

2024-12-17 08:21 UTC, provokateurin commented on lib/private/Share20/Manager.php
> +		return $this->config->getAppValue('core', 'shareapi_allow_custom_tokens', 'no') === 'yes';
Please use a real boolean value instead of this

2025-01-04 00:21 UTC, Pytal commented on apps/files_sharing/lib/Controller/ShareAPIController.php
> +		if (!preg_match('/^[a-z0-9-]+$/i', $token)) {
It seems more maintainable to me to explicitly check the length separately to avoid accidently merging a switch from e.g. `+` to `*` in the regex

2025-01-04 00:23 UTC, Pytal commented on core/templates/layout.public.php
> +				p(!empty($_['pageTitle']) && !empty($_['application']) && $_['pageTitle'] !== $_['application'] ? $_['pageTitle'] . ' - ' : '');
Noticed a bug when testing but can do this separately

2025-01-04 00:25 UTC, Pytal commented on lib/private/Share20/Manager.php
> +		return $this->config->getAppValue('core', 'shareapi_allow_custom_tokens', 'no') === 'yes';
Good idea 👍

The other methods do it the same way so I will split off this into a refactor PR

2025-01-06 07:01 UTC, provokateurin requested changes

2025-01-06 07:01 UTC, provokateurin commented on lib/private/Share20/Manager.php
> +		return $this->config->getAppValue('core', 'shareapi_allow_custom_tokens', 'no') === 'yes';
That won't work as it would break existing usage.
Please fix it for this new value in this PR, all the other values can not be changed.

2025-01-10 07:05 UTC, provokateurin approved these changes
Nice!

2025-01-15 09:37 UTC, sorbaugh approved these changes

2025-01-15 11:08 UTC, susnux commented
/compile

2025-01-15 22:39 UTC, Pytal commented
/compile

2025-01-15 23:51 UTC, Pytal commented
/compile

2025-01-16 00:25 UTC, merged

2025-04-22 10:26 UTC, ALLADMINdotRU commented
31.0.2 если в названии ссылки есть символ подчеркивания , то ссылка не работает
Шаги по воспроизведению
Поделиться каталогом с публичной ссылкой
Измените ссылку на что-то, содержащее символ нижнее подчеркивание.
Открыть ссылку в новом окне

2025-04-22 10:36 UTC, susnux commented
@ALLADMINdotRU allowed characters are only letters, numbers and the dash. If you need underscores open a feature request.