fix(files_sharing): Do not wrap password policy exception into a generic one
nextcloud/server pull request #49366
Opened 2024-11-19 10:39 UTC by come-nc

Let the controller access the HintException and show the error to the user.

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-11-19 11:08 UTC, susnux approved these changes

2024-11-19 11:08 UTC, susnux commented on lib/private/Share20/Manager.php
> +		$this->dispatcher->dispatchTyped(new ValidatePasswordPolicyEvent($password));
Still disappointed that this is done using exceptions rather than setting property on the even like `isValid`...

2024-11-19 11:56 UTC, tobiasKaminsky requested changes
Unfortunately this does not fix it

2024-11-19 12:24 UTC, provokateurin approved these changes

2024-11-19 13:35 UTC, come-nc commented
> Unfortunately this does not fix it

I’m out of ideas

2024-11-25 10:33 UTC, come-nc commented
> Do you need more info how to reproduce it? Me as Android dev cannot really help, expect of steps to reproduce…

Do you have a full stacktrace for the Exception? (with this PR applied on server side)

2024-12-10 15:00 UTC, come-nc commented
@tobiasKaminsky Can you test again? It should be good now, message should be back and error code should be 400.

2024-12-11 06:07 UTC, tobiasKaminsky commented
This works now without any modification on client side :tada:

2024-12-11 06:07 UTC, tobiasKaminsky approved these changes

2024-12-12 13:03 UTC, tobiasKaminsky commented
@come-nc can we merge this? :blue_heart:

2024-12-12 16:51 UTC, merged