fix(status): Avoid session creation for status requests
nextcloud/server pull request #49406
Opened 2024-11-20 17:27 UTC by solracsf

* Resolves: https://github.com/nextcloud/server/issues/11125

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-11-20 18:18 UTC, szaimen commented on lib/base.php
> +		$isStatusRequest = str_starts_with($request->getRequestUri(), '/status.php');
Shouldnt that be str_ends_with or am I missing something?

2024-11-20 19:05 UTC, solracsf commented on lib/base.php
> +		$isStatusRequest = str_starts_with($request->getRequestUri(), '/status.php');
Well, after reading I think neither should be used here since we're looking for an exact match, not at the start or at the end. I'll fix this. 👌🏻

2024-11-20 19:10 UTC, solracsf commented on lib/base.php
> +		$isStatusRequest = str_starts_with($request->getRequestUri(), '/status.php');
Fixed.

2024-11-20 19:12 UTC, szaimen commented on lib/base.php
> +		if ($request->getRequestUri() === '/status.php') {
And what about subdir instaolations? Or is the part before stripped from the uri?

2024-11-21 06:35 UTC, juliusknorr approved these changes

2024-11-21 06:36 UTC, solracsf commented on lib/base.php
> +		if ($request->getRequestUri() === '/status.php') {
My bad, you're right. Thanks. 🥇

2024-11-21 08:35 UTC, szaimen approved these changes
LGTM but didnt test

2024-11-21 13:46 UTC, nickvergessen requested changes

2024-11-21 13:53 UTC, nickvergessen commented on lib/base.php
> +		if (str_ends_with($request->getRequestUri(), '/status.php')) {
```suggestion
		if (str_ends_with($request->getScriptName(), '/status.php')) {
```

should do, ref:
https://github.com/nextcloud/server/blob/381077028adf388a7081cf42026570c6be47b198/apps/workflowengine/lib/Check/RequestURL.php#L60-L63

2024-11-21 13:59 UTC, solracsf commented on lib/base.php
> +		if (str_ends_with($request->getRequestUri(), '/status.php')) {
Thanks. 👍 Do you believe it's a better option than `OC::$SUBURI` already available in base.php?

2024-11-21 18:15 UTC, nickvergessen approved these changes
But since we have a valid request class in the place already, it should be fine

2024-11-22 09:41 UTC, merged

2025-03-01 15:24 UTC, szaimen commented
Hey,  it looks like this broke the security scanner. See https://help.nextcloud.com/t/update-nextcloud-to-31-0-0-now-scaner-showing-rating-a/218485/13. So revert?

2025-03-01 15:28 UTC, nickvergessen commented
Requests from scanner 1/month or 1/year
Requests from sync clients which don't need this 1.000.000 * x

We can add a force header to do the session or we scan a second endpoint.

2025-03-03 09:19 UTC, szaimen commented
Resolved by https://github.com/nextcloud/server/pull/51184