feat: Two Factor API
nextcloud/server pull request #49443
Opened 2024-11-23 00:12 UTC by SebastianKrupinski

Ability to check/enable/disable configured 2FA with API endpoint

Request State
```
POST /twofactor/state

{
	"users": ["admin", "user1", "user2"]
}
```

Request Disable
```
POST /twofactor/disable

{
	"users": {
			"admin": ["backup_codes","totp"],
			"user1": ["totp"],
			"user2": ["backup_codes"]
	}
}
```

Request Enable
```
POST /twofactor/enable

{
	"users": {
			"user1": ["totp"],
			"user2": ["totp"]
	}
}
```

2024-12-02 15:43 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +	 * @return DataResponse<Http::STATUS_OK, list{string: list{string: bool}}, array{}>
```suggestion
	 * @return DataResponse<Http::STATUS_OK, array<string, array<string, bool>>, array{}>
```

2024-12-02 15:45 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +		return new DataResponse([], Http::STATUS_NOT_FOUND);
return empty list is illegal :crying_cat_face: 
```suggestion
		return new DataResponse(null, Http::STATUS_NOT_FOUND);
```

2024-12-02 15:45 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +	 * @return DataResponse<Http::STATUS_OK|Http::STATUS_NOT_FOUND, list{string: bool}, array{}>
```suggestion
	 * @return DataResponse<Http::STATUS_O, array<string, bool>, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
```

2024-12-15 10:41 UTC, nickvergessen requested changes, later dismissed

2024-12-15 10:41 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +	#[PublicPage]
```suggestion
```

2024-12-15 10:41 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +	#[PublicPage]
```suggestion
```

2024-12-15 10:41 UTC, nickvergessen commented on core/Controller/TwoFactorApiController.php
> +	#[PublicPage]
```suggestion
```

2024-12-28 10:46 UTC, provokateurin commented
All the endpoints are only intended to be used by admins?
This PR lacks context that explains for what feature this is needed.

2024-12-28 13:28 UTC, SebastianKrupinski commented
> All the endpoints are only intended to be used by admins? This PR lacks context that explains for what feature this is needed.

Apologies, didn't realize I did not link the issue ticket. I've updated the description.

2025-01-06 07:06 UTC, provokateurin approved these changes
Fine by me

2025-01-07 06:38 UTC, ChristophWurst reviewed
Looks good otherwise

2025-01-07 06:38 UTC, ChristophWurst commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
This should be a GET

2025-01-15 14:42 UTC, SebastianKrupinski commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
Hey,

The reason this is a POST is because its pretty messy to send an array of user names in a GET url.

This command retrieves the states for specific users not just one user.

POST /twofactor/state

{
	"users": ["admin", "user1", "user2"]
}

2025-01-15 14:46 UTC, provokateurin commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
It is possible using this syntax: `?user[]=a&user[]=b`, but indeed very ugly. Not sure what is better here :sweat_smile:

2025-01-15 14:53 UTC, ChristophWurst commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
GET is the right verb here. If the arguments make the URL ugly so be it.

As an alternative you could drop the bulk operation aspect. It's not a concept I've seen with any other Nextcloud APIs. If there is only one user, like with the occ command, the URL will become "pretty" again.

2025-01-15 15:56 UTC, ChristophWurst requested changes

2025-01-15 15:56 UTC, ChristophWurst commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
POST is still used here.

2025-01-15 16:31 UTC, provokateurin commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
Agreed, if there is no need to query multiple users at once then it is much better to only implement it for a single user.

2025-01-15 16:51 UTC, SebastianKrupinski commented on core/Controller/TwoFactorApiController.php
> +	#[ApiRoute(verb: 'POST', url: '/state', root: '/twofactor')]
Well the idea behind the bulk operation was that an external system can check the state of 2fa on a 100+ accounts at the same time instead of doing 100 requests.

But if you insist on this being a GET then having this as an array makes it ugly. I'll change it.

2025-01-16 07:57 UTC, ChristophWurst approved these changes

2025-01-16 07:57 UTC, ChristophWurst commented on core/Controller/TwoFactorApiController.php
> +class TwoFactorApiController extends \OCP\AppFramework\OCSController {
import ocscontroller

2025-01-18 19:03 UTC, merged