feat(systemtags): add setting to block non admin to create system tags
nextcloud/server pull request #49514
Opened 2024-11-27 08:31 UTC by Altahrim

## Summary
Allows admins to restrict tag creation to admins only

## TODO
- [ ] Add frontend switch in system tags settings
- [ ] Change display on tag selection for users who can't create tags

## Checklist
- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2025-01-06 19:37 UTC, nfebe commented
### Frontend switch

| Enabled | Disabled |
| ---------- | ------------  |
| ![enabled-tag-creation-non-admins](https://github.com/user-attachments/assets/068642d6-51eb-40b6-8846-a3cb65164cdf) | ![disabled-tag-creation-non-admins](https://github.com/user-attachments/assets/cddc02d9-405d-40f5-a6c0-6d8f9f512f2e) |


### Error view

| Error | NA |
| --------| ----  |
| ![error-cant-update-systag](https://github.com/user-attachments/assets/bebbf6cb-e298-438b-ab9b-ea0a60a5517c) | NA |

2025-01-13 15:15 UTC, sorbaugh approved these changes

2025-01-13 15:24 UTC, provokateurin approved these changes
Only minor things, LGTM

2025-01-14 08:46 UTC, Altahrim commented on lib/private/SystemTag/SystemTagManager.php
> +		return $this->groupManager->isAdmin($user->getUID());
I feel it gives less info: if it's  `everyone_can_create = false` you don't know who can create tags (even if it's probably an admin)

2025-01-14 09:03 UTC, provokateurin approved these changes

2025-01-14 11:08 UTC, skjnldsv commented on apps/systemtags/src/components/SystemTagsCreationControl.vue
> +			{{ t('settings', 'Allow only admins to create tags (enable or disable).') }}
```suggestion
			{{ t('settings', 'Restrict tag creation to admins only (enable or disable).') }}
```

2025-01-14 11:11 UTC, skjnldsv commented on apps/systemtags/src/components/SystemTagsCreationControl.vue
> +			{{ t('settings', 'Enable') }}
```suggestion
			{{ t('settings', 'Restrict tag creation to admins only') }}
```

2025-01-14 11:14 UTC, skjnldsv requested changes

2025-01-14 11:14 UTC, skjnldsv commented on apps/systemtags/src/components/SystemTagsCreationControl.vue
> +			{{ t('settings', 'Allow only admins to create tags (enable or disable).') }}
```suggestion
			{{ t('settings', 'If enabled, regular accounts will be restricted from creating new tags but will still be able to assign and remove them from their files.') }}
```

Weird phrasing otherwise and not proper a11y description of the following NcCheckboxRadioSwitch.
You shouldn't have to specify "enable/disable" if the main description convey the direction (Thus my suggestion: use "restrict")

2025-01-14 11:14 UTC, skjnldsv commented on apps/systemtags/src/components/SystemTagsCreationControl.vue
> +			{{ t('settings', 'Enable') }}
```suggestion
			{{ t('settings', 'Restrict tag creation to admins only') }}
```

2025-01-16 11:24 UTC, nfebe commented
/compile

2025-01-16 12:37 UTC, skjnldsv approved these changes

2025-01-18 22:11 UTC, nfebe commented
/compile

2025-01-20 12:15 UTC, Altahrim commented
/compile

2025-01-20 19:21 UTC, Altahrim commented
/compile amend

2025-01-21 09:34 UTC, nfebe commented
/compile

2025-01-21 11:56 UTC, artonge reviewed
Nitpicking on the naming. But not blocking :)

2025-01-21 11:56 UTC, artonge commented on apps/settings/lib/Settings/Admin/Server.php
> +		$this->initialStateService->provideInitialState('onlyAdminsCanCreateSystemTags', $this->appConfig->getValueString('systemtags', 'only_admins_can_create', 'true'));
```suggestion
		$this->initialStateService->provideInitialState('restrictSystemTagsCreationToAdmin', $this->appConfig->getValueString('systemtags', 'restrict_creation_to_admin', 'true'));
```

2025-01-21 12:55 UTC, Altahrim commented on apps/settings/lib/Settings/Admin/Server.php
> +		$this->initialStateService->provideInitialState('onlyAdminsCanCreateSystemTags', $this->appConfig->getValueString('systemtags', 'only_admins_can_create', 'true'));
Yep, that's better :)

2025-01-21 13:32 UTC, Altahrim commented
/compile

2025-01-21 13:54 UTC, artonge approved these changes

2025-01-22 19:02 UTC, nfebe commented
/compile

2025-01-22 19:39 UTC, merged

2025-03-05 08:35 UTC, skjnldsv commented on apps/settings/lib/Settings/Admin/Server.php
> +		$this->initialStateService->provideInitialState('restrictSystemTagsCreationToAdmin', $this->appConfig->getValueString('systemtags', 'restrict_creation_to_admin', 'true'));
The value is NOT stored as a boolean in the backend, but as an integer @Altahrim 
![image](https://github.com/user-attachments/assets/0b838394-2f4c-4fdc-8332-a0cf69a3bacb)

2025-03-05 08:41 UTC, skjnldsv commented on apps/systemtags/src/files_actions/bulkSystemTagsAction.ts
> +		}
@nfebe why are we preventing the entire bulk tagging action if creation is disabled?
It does NOT mean we cannot apply tags....

2025-03-05 08:48 UTC, skjnldsv commented on apps/systemtags/src/files_actions/bulkSystemTagsAction.ts
> +		}
Will fix in followup