feature: added new FavouriteWidget to display favorite files in dashboard widget
nextcloud/server pull request #49534
Opened 2024-11-28 07:07 UTC by yemkareems

feature: added new FavouriteWidget to display favorite files in dashboard widget

added a new widget to display favorite files in dashboard and to show a link to more favorites to apps/files/favorites. if max count of favorites of 50 is reached then also 'No favorites' is displayed

![image](https://github.com/user-attachments/assets/bdb25599-771d-4ed0-b29c-8a158f5d5a22)

fixes: https://github.com/nextcloud/server/issues/23308

* Resolves: # 

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-11-28 14:22 UTC, come-nc commented on apps/files/composer/composer/autoload_static.php
>  class ComposerStaticInitFiles
There is an issue in this file, please run `build/autoloaderchecker.sh` and commit the result without modifications

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +	}
```suggestion
	public function __construct(
		private IIUserSession $userSession,
		private IIL10N $l10n,
		private IIURLGenerator $urlGenerator,
		private IIMimeTypeDetector $mimeTypeDetector,
		private IIUserManager $userManager,
		private IITagManager $tagManager,
		private IIRootFolder $rootFolder,
		private IIPreview $previewManager,
	) {
	}
```
Use promoted properties on new classes.

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +class FavouriteWidget implements IWidget, IIconWidget, IAPIWidget, IAPIWidgetV2, IButtonWidget {
Are all these interfaces required? IWidget is inherited anyway, and for apiwidget are both v1 and v2 needed? I never touched dashboard widgets before, asking to be sure.

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return Application::APP_ID;
We may have other files related widget later no?
```suggestion
		return Application::APP_ID.'-favourites';
```

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return $this->l10n->t('Favorites');
Is it `Favorite` ou `Favourite`? We should be consistent in code and UI and filenames.

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return null;
Should link to favorites view, no?

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		//Util::addScript(Application::APP_ID, 'recommendations-dashboard');
```suggestion
```

2024-11-28 14:22 UTC, come-nc commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return;
That’s not doing anything?

2024-11-28 15:23 UTC, AndyScherzinger commented
Looping in @jancborchardt for

> if max count of favorites of 50 is reached then also 'No favorites' is displayed

This seems unintuitive since "no favorites" implies `count==0` but it is actually `count>=50`. So I would expect something like "too many favorites to display" or show the 50 and a "more" element/button.

Or I misunderstand the description @yemkareems 😄

2024-11-29 14:46 UTC, skjnldsv commented
Following Andy's comment, I would actually say we show the last xx updated favorites (like 20 :shrug: )

2024-12-02 08:37 UTC, sorbaugh commented
> Following Andy's comment, I would actually say we show the last xx updated favorites (like 20 🤷 )

I agree that this would be a good approach. cc @jancborchardt

2024-12-02 08:56 UTC, jancborchardt requested changes
> Following Andy's comment, I would actually say we show the last xx updated favorites (like 20 🤷 )

Sounds good to me as well!

Also 2 smaller things:
- [x] The title should be "Favorite files" so it's clearer what it is. (Just like we say "Recommended files")
- [x] The icon can be a favorite star to show a little difference

2024-12-02 08:59 UTC, sorbaugh commented
> > Following Andy's comment, I would actually say we show the last xx updated favorites (like 20 🤷 )
> 
> Sounds good to me as well!
> 
> Also 2 smaller things:
> 
> * [ ]  The title should be "Favorite files" so it's clearer what it is. (Just like we say "Recommended files")
> * [ ]  The icon can be a favorite star to show a little difference

cc @yemkareems

2024-12-02 11:08 UTC, yemkareems commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return;
Yes in case of any javascript or css we can use this. For now removed the user logic as well

2024-12-02 11:08 UTC, yemkareems commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		}
Removed the limit logic as irrespective of the limit only 6 files are displayed in the ui

2024-12-02 11:11 UTC, yemkareems commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +		return $this->l10n->t('Favorites');
Renamed to Favorite as it is named so in the file listing

2024-12-02 11:13 UTC, yemkareems commented on apps/files/lib/Dashboard/FavouriteWidget.php
> +class FavouriteWidget implements IWidget, IIconWidget, IAPIWidget, IAPIWidgetV2, IButtonWidget {
Removed IWidget, IAPIWidget and the rest are required

2024-12-02 11:16 UTC, yemkareems commented
> Looping in @jancborchardt for
> 
> > if max count of favorites of 50 is reached then also 'No favorites' is displayed
> 
> This seems unintuitive since "no favorites" implies `count==0` but it is actually `count>=50`. So I would expect something like "too many favorites to display" or show the 50 and a "more" element/button.
> 
> Or I misunderstand the description @yemkareems 😄

Irrespective of the limit the ui is showing only the latest 6. Hence removed the limit logic here and after 6 items, More favorites button is displayed which takes the user to file listing.

2024-12-02 11:18 UTC, yemkareems commented
> > Following Andy's comment, I would actually say we show the last xx updated favorites (like 20 🤷 )
> 
> Sounds good to me as well!
> 
> Also 2 smaller things:
> 
> * [x]  The title should be "Favorite files" so it's clearer what it is. (Just like we say "Recommended files")
> * [x]  The icon can be a favorite star to show a little difference

Changed the title and icon. The icon star loads with a grey color color initially and then it changes to black. The SVG is black however.

2024-12-02 11:20 UTC, yemkareems commented
Initial icon load

![image](https://github.com/user-attachments/assets/8ce2c795-eb68-422d-aa30-c6ecee9097d6)

After a while

![image](https://github.com/user-attachments/assets/1629cf49-2e4b-4221-bbed-77ba49454b7a)

2024-12-02 11:43 UTC, AndyScherzinger commented
I think @nickvergessen fixed this a while ago for all icons until then, maybe you remember the PR @nickvergessen ?

2024-12-02 11:44 UTC, AndyScherzinger commented
@yemkareems I would remove the circular masking, we don't have it in the files interface nor any other list in the dashboard except for avatars

2024-12-02 12:32 UTC, jancborchardt commented
> @yemkareems I would remove the circular masking, we don't have it in the files interface nor any other list in the dashboard except for avatars - see for reference in your screenshots: recommended files

Yep agree, missed this somehow. Circular masking is only for avatars. File previews get a little border-radius and filetype icons should be displayed as is.

2024-12-02 13:03 UTC, nickvergessen requested changes

2024-12-02 13:03 UTC, nickvergessen commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +		return $this->urlGenerator->getAbsoluteURL('index.php/apps/files/favorites');
```suggestion
		return $this->urlGenerator->linkToRouteAbsolute('files.View.indexView', ['view' => 'favorites']);
```

2024-12-02 13:03 UTC, nickvergessen commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +					'files.viewcontroller.showFile', ['fileid' => $node->getId()]
```suggestion
					'files.view.showFile', ['fileid' => $node->getId()]
```

2024-12-02 13:03 UTC, nickvergessen commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +				$this->urlGenerator->getAbsoluteURL('index.php/apps/files/favorites'),
same here as above

2024-12-02 13:03 UTC, nickvergessen commented on lib/composer/composer/autoload_psr4.php
> +    'Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
`composer i --no-dev` and re-commit

2024-12-04 06:50 UTC, yemkareems commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +	public function getItems(string $userId, ?string $since = null, int $limit = 7): array {
I have sliced the array to contain only limit number of items. I tried using since also but there is no date field in oc_vcategory_to_object to know when favorite was added but since is required so left it as it is in getItemsV2

2024-12-04 06:52 UTC, yemkareems commented
> @yemkareems I would remove the circular masking, we don't have it in the files interface nor any other list in the dashboard except for avatars - see for reference in your screenshots: recommended files

I had to change the DashboardApp.vue to have <div class="panel--content" :id="`panel-${panels[panelId].id}`"> in place of <div class="panel--content"> to have the id of the app and apply styles specific to the app

2024-12-04 07:07 UTC, yemkareems commented
Most of the ui issues are addressed. Recommendation app has filename and extension in different classes and ui looks black and grey for the same. Except this and titles most of the ui is made similar to the Recommendation app

![image](https://github.com/user-attachments/assets/0d1afc5f-4db5-4fc9-aae8-350386217138)

2024-12-04 07:17 UTC, yemkareems commented on lib/composer/composer/autoload_psr4.php
> +    'Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
For some reason this change is not reflecting as expected. I will check and update it correctly

2024-12-04 12:57 UTC, come-nc submitted a review, later dismissed

2024-12-04 12:57 UTC, come-nc commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +		return array_slice($favoriteNodes, 0, $limit);
You should not slice, you should count in the foreach and stop at `$limit`. Otherwise you are building a lot of WidgetItem instances for nothing.

2025-01-09 09:48 UTC, come-nc reviewed
A small change to avoid computing one more node than necessary and helping with code readability, but otherwise all good.

2025-01-09 09:48 UTC, come-nc commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +				}
```suggestion
				$favoriteNodes[] = new WidgetItem(
					$node->getName(),
					'',
					$url,
					$icon,
					(string)$node->getCreationTime()
				);
				$count++;
				if($count >= $limit) {
					break;
				}
```

2025-01-13 11:02 UTC, jancborchardt approved these changes
Looks good to me design-wise!

2025-01-13 13:28 UTC, provokateurin requested changes

2025-01-13 13:28 UTC, provokateurin commented on apps/files/css/style.css
> + * SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
:eyes:

2025-01-13 13:28 UTC, provokateurin commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +				}
I think this logic is probably not necessary, since the endpoint also implements a fallback if no preview is available.

2025-01-13 13:28 UTC, provokateurin commented on apps/files/lib/Dashboard/FavoriteWidget.php
> + * SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
:eyes:

2025-01-13 13:28 UTC, provokateurin commented on apps/files/css/style.css
API widgets should not have custom CSS.
From my testing it seems this mostly changes the rounded corners to be more square which can also be achieved by implementing IOptionWidget.
Please also remove the added id field in DashboardApp.vue.

2025-01-14 16:10 UTC, susnux commented on apps/files/lib/Dashboard/FavoriteWidget.php
> +				}
Yes only need to set `mimeFallback`

2025-01-14 16:54 UTC, susnux commented on apps/files/css/style.css
No only for clients, its not implemented on frontend correctly.
Fixing that.

2025-01-14 17:18 UTC, provokateurin approved these changes
Backend looks good, can't judge frontend

2025-01-14 17:18 UTC, provokateurin commented on apps/dashboard/src/DashboardApp.vue
> +					<div class="panel--content" :id="`panel-${panels[panelId].id}`">
```suggestion
					<div class="panel--content">
```
Unnecessary addition left-over from before

2025-01-15 09:39 UTC, merged