fix(updater): Stop expiring secret prematurely
nextcloud/server pull request #49578
Opened 2024-12-01 19:53 UTC by joshtrichards

* Resolves: nextcloud/updater#574 
* Resolves: #45714

## Summary

#43967 introduced a regression in the handling of the expiration of `updater.secret`. The result is that `updater.secret` is expired at the next job interval (~10 minutes). If the web Updater takes >10 minutes this prevents it from continuing. 

* Fixed expiration handling
* Added logging when we expire the secret
* Added cleanup of the `updater.secret.created` value when we expire a secret
* Added handling for `config_is_read_only` in the `AdminController`
* Changed `ResetToken` background job unit tests to catch the scenario addressed by this PR
* Expanded `ResetToken` background job unit tests to catch more scenarios
* Expanded `AdminController` unit tests

## TODO

- [ ] Tests: Confirm new tests are working (I eliminated the `static` used in the `ResetToken` test since it didn't seem to serve a purpose but I may have broken it so may require another look)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-12-01 20:08 UTC, joshtrichards commented
/backport to stable30

2024-12-01 20:09 UTC, joshtrichards commented
/backport to stable29

2024-12-01 21:41 UTC, nickvergessen requested changes, later dismissed

2024-12-01 21:41 UTC, nickvergessen commented on apps/updatenotification/lib/BackgroundJob/ResetToken.php
>  		$secretCreated = $this->appConfig->getValueInt('core', 'updater.secret.created', $this->time->getTime());
```suggestion
		$secretCreated = $this->appConfig->getValueInt('core', 'updater.secret.created');
		if ($secretCreated === 0) {
			...
```

Should handle the "does not even exist" case.
Or should we even always try the delete of the `updater.secret`, when the timestamp is missing?

2024-12-01 21:41 UTC, nickvergessen commented on apps/updatenotification/lib/BackgroundJob/ResetToken.php
> -		if ($secretCreated >= 172800) {
What an oversight 🙈

2024-12-01 21:41 UTC, nickvergessen commented on apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php
> +		$this->invokePrivate($this->resetTokenBackgroundJob, 'run', [null]);
```suggestion
		static::invokePrivate($this->resetTokenBackgroundJob, 'run', [null]);
```

Static is the correct/new stuff. `$this->invokePrivate` actually generates a warning in IDEs?

Ref https://github.com/nextcloud/server/commit/ffb3a3e33a2b0468a39ab9f11cf8f63f020bd0bb

2024-12-01 21:41 UTC, nickvergessen commented on apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php
> +	public function testRunWithNotExpiredToken(): void { // Affirm if updater.secret.created <48 hours ago then `updater.secret` is left alone
Make the comment part of the function name, so the failing test explains it right away without diving into test code,
Otherwise at least make it a proper doc block above the test case

2025-05-16 10:41 UTC, heeplr commented
Any news on this?

Issue #610 just happened again when updating from 30.0.10 to 30.0.11 (download took very long).

2025-05-16 13:59 UTC, susnux commented on apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php
> +	public function testRunWithNotExpiredToken(): void { // Affirm if updater.secret.created <48 hours ago then `updater.secret` is left alone
```suggestion
	/**
	 * Affirm if updater.secret.created <48 hours ago then `updater.secret` is left alone.
	 */
	public function testKeepSecretWhenCreatedRecently(): void {
```

2025-05-16 14:08 UTC, susnux commented
/backport to stable31

2025-05-16 14:39 UTC, come-nc approved these changes

2025-05-16 14:49 UTC, susnux approved these changes

2025-10-21 09:29 UTC, artonge commented
- Rebased
- Fixed php-cs error
- Fixed unit test error

2025-10-21 14:26 UTC, merged

2025-10-21 14:34 UTC, artonge commented
/backport to stable32

2025-11-23 19:14 UTC, SystemKeeper commented
Looks like this will now log a warning on each run, as the default value from `getValueInt` was removed and no check for non-zero values was added. https://help.nextcloud.com/t/warning-updatenotification-cleared-old-updater-secret-that-was-created-1763885703-seconds-ago-every-hour/236299

2025-11-25 08:22 UTC, gvanteylingen commented
Experiencing same log issue Cleared old `updater.secret` that was created xxxxxx seconds ago, twice every 65 minutes after updating to 32.0.2.