Fix `occ integrity:check-app` and Admin panel "rescan" deliver inconsistent results
nextcloud/server pull request #49577
Opened 2024-12-01 13:50 UTC by ehfd

* Resolves: #17801 

## Summary

This issue fixes the behavior discrepancy between the `occ integrity:check-app` command and the Admin panel "rescan" button.
The fix allows `occ integrity:check-app` to gracefully skip the signature check of the app instead of throwing an exception, as instructed in https://github.com/nextcloud/server/issues/17801#issuecomment-2326854333.

## TODO

- [ ] Independent code testing and validation by a reviewer. Check the below `custom_apps` apps that do not ship with signatures. `bookmarks` is a good example (https://github.com/nextcloud/bookmarks/issues/1941).

<details>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- apporder
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- bookmarks
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- bruteforcesettings
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- drawio
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- event_update_notification
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- impersonate
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- metadata
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- previewgenerator
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- twofactor_admin
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- twofactor_totp
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- twofactor_u2f
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [apporder] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [bookmarks] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [bruteforcesettings] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [drawio] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [event_update_notification] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [impersonate] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [metadata] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [previewgenerator] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [twofactor_admin] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [twofactor_totp] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [twofactor_u2f] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

</details>

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes - Not applicable
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required - Not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes) - NC 28, 29, 30

CC @joshtrichards @simonspa @szaimen

2024-12-08 11:55 UTC, ehfd commented
No labels, nothing? @joshtrichards @simonspa @szaimen

2024-12-10 14:24 UTC, joshtrichards requested changes
I think the only thing missing that I see (for parity) is an `isShipped()` check (shipped apps are always verified; if they're missing a signature file something is wrong so we still want to throw an exception for those). Looks reasonable otherwise.

https://github.com/nextcloud/server/blob/f9fcc5b17025e34c42ad53fa4401e8b79064c75f/lib/private/IntegrityCheck/Checker.php#L541-L553 

I'm mildly tempted to add another return/exit code (`3` maybe) so that automated runners can easily detect if things only passed due to a missing signature file, but that opens a can of worms we should probably avoid right now (i.e. auditing the return codes we use across our `occ` commands; adding one arbitrarily right now just creates later tech debt... so probably easier to *add* that code later when/if deemed important I guess).

2024-12-10 14:25 UTC, joshtrichards commented
Hi @ehfd - Thanks for the ping and PR. And sorry for the delay.

2024-12-10 14:35 UTC, joshtrichards commented
> Identify unit testing requirements.

Hmm. I don't currently see any test coverage for the `integrity` command namespace themselves:

https://github.com/nextcloud/server/tree/f5f9691f387473982bff7d9788fe3350979e7cbc/tests/Core/Command

Might be a good opportunity to add some. :)

We do have test coverage for the underlying `IntegrityCheck\Checker` itself however at least.

2024-12-14 10:20 UTC, ehfd commented
https://github.com/nextcloud/server/pull/49577#pullrequestreview-2492495612
@joshtrichards Requested changes are implemented. I agree that returning a new exit code should be something for the future.

2024-12-14 16:16 UTC, ehfd commented
@nickvergessen This was because I copied from: https://github.com/nextcloud/server/blob/2651d4964ec26696b5f8b1f5db48588a5d09ab01/lib/private/IntegrityCheck/Checker.php#L49

2024-12-14 16:23 UTC, ehfd commented on core/Command/Integrity/CheckApp.php
> +		private ?IAppManager $appManager,
This was a typo.

2024-12-16 14:20 UTC, nickvergessen commented on core/Command/Integrity/CheckApp.php
> +			$output->writeln('<info>App signature not found, skipping app integrity check</info>', OutputInterface::VERBOSITY_VERBOSE);
I think yellow is better, and from my pov it should be printed by default:
```suggestion
			$output->writeln('<comment>App signature not found, skipping app integrity check</comment>');
```

Otherwise good in general

2024-12-16 20:15 UTC, nickvergessen approved these changes

2024-12-17 00:47 UTC, ehfd commented
Changed titles to conventional commits and force-pushed. @joshtrichards ready when you're ready.

2024-12-17 13:25 UTC, miaulalala approved these changes
Thank you!

2024-12-18 08:19 UTC, merged

2024-12-18 08:34 UTC, nickvergessen commented
Thanks a lot @ehfd
I just noticed there was a checkbox for unit tests, you can send them in a follow up if you want to