fix(files_versions): fix undefined success message
nextcloud/server pull request #49664
Opened 2024-12-05 10:46 UTC by skjnldsv

Fix weird error messages and improve layout by displaying empty label placeholder
![2024-12-05_11-38](https://github.com/user-attachments/assets/83683f81-1f4a-4c08-8ee6-6333f5d3cd8e)

2024-12-05 10:47 UTC, skjnldsv commented
/backport to stable30

2024-12-05 10:47 UTC, skjnldsv commented
/backport to stable29

2024-12-05 12:36 UTC, come-nc commented
- Fixes https://github.com/nextcloud/server/issues/37055

2024-12-05 12:38 UTC, come-nc approved these changes

2024-12-05 17:19 UTC, Pytal reviewed
iirc it was a design decision to not show a label when not named @artonge @nimishavijay?

2024-12-05 19:28 UTC, skjnldsv commented
> iirc it was a design decision to not show a label when not named @artonge @nimishavijay?

It honestly looks weird without. It feels like a bug where some part of the UI is missing.
Especially between Initial version and Current Version
![image](https://github.com/user-attachments/assets/0c139617-bdfe-45e5-939b-fb9ddf2b414c)

2024-12-13 13:57 UTC, Wendy-Russo commented
i tried your branch using the command and the notification still shows undefined

2024-12-13 14:30 UTC, nimishavijay commented
It was indeed a deliberate decision! :) most versions are not saved, so if they had a generic name the version list would just have many many duplicated "Unnamed version" labels. For versions that are not saved I'd keep then unnamed but use a more distinct identifier for the toast message, like the date ("Version from 10 days ago restored") :)

2024-12-19 15:22 UTC, come-nc commented
> It was indeed a deliberate decision! :) most versions are not saved, so if they had a generic name the version list would just have many many duplicated "Unnamed version" labels. For versions that are not saved I'd keep then unnamed but use a more distinct identifier for the toast message, like the date ("Version from 10 days ago restored") :)

I agree with @skjnldsv that this looks like a bug when looking at the UI like in https://github.com/nextcloud/server/pull/49664#issuecomment-2521228970 .
If this is a blocker we should revert this part of the PR and still merge the rest because the current toast message with undefined is definitely problematic and has been reported by customers.

2024-12-20 15:16 UTC, jancborchardt requested changes
As @nimishavijay saod, it is intentional to only highlight versions with a name, as they likely are important.

Highlighting all versions and naming them "Unnamed version" makes everything important (and thus nothing), makes it seem like you are forced to name every version, and makes it look unfinished.

For unnamed versions, we could say "Edited by [account bubble]", but not bold that. Only bold specifically named versions.

2024-12-22 16:26 UTC, skjnldsv commented
> "Edited by [account bubble]", but not bold that.

Good alternative, thanks Nimisha and Jan! :+1:

2025-05-29 12:11 UTC, closed without merging