Harden user_status API
nextcloud/server pull request #49797
Opened 2024-12-11 09:26 UTC by provokateurin

## Summary

Issues found with https://github.com/nextcloud/server/issues/47825

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-12-11 19:50 UTC, skjnldsv approved these changes

2024-12-12 13:10 UTC, come-nc approved these changes

2024-12-12 13:10 UTC, come-nc commented on apps/user_status/lib/Controller/StatusesController.php
> +	 * @param non-negative-int|null $offset Offset for finding statuses
I’m curious, I guess a lot of places in the API expects a positive int and type it as int, why change this one in particular?

2024-12-12 13:10 UTC, come-nc commented on apps/user_status/lib/Controller/UserStatusController.php
> +		private ?string $userId,
Is there any chance to explain psalm and friends that such a property cannot be null when calling an authenticated method?

2024-12-12 13:38 UTC, provokateurin commented on apps/user_status/lib/Controller/StatusesController.php
> +	 * @param non-negative-int|null $offset Offset for finding statuses
I found this one because the fuzzer used -1 which triggered an unexpected error.
I didn't search for these problems, but the underlying typing could be improved to find more of them.

2024-12-12 13:40 UTC, provokateurin commented on apps/user_status/lib/Controller/UserStatusController.php
> +		private ?string $userId,
I don't think that is possible and even then we'd still have a problem because the DI will fail when you don't send the authentication (regardless if the method needs it or not).

2024-12-14 06:48 UTC, oleksandr-nc approved these changes

2024-12-14 07:13 UTC, nickvergessen commented on apps/user_status/lib/Controller/UserStatusController.php
> +		private ?string $userId,
Yeah we have this error regularly in our logs from various apps. 
I'm just always drawn apart how to handle it as allowing null in the constructor basically means you have to handle it manually in each method or have psalm complaining there

2024-12-14 07:15 UTC, nickvergessen requested changes

2024-12-14 07:15 UTC, nickvergessen commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
I want to check this on Monday, so please don't merge before

2024-12-14 10:03 UTC, provokateurin commented on apps/user_status/lib/Controller/UserStatusController.php
> +		private ?string $userId,
I think we could be handling it more gracefully and letting controllers specify it as non-null if they know it has to be there for every method. Currently if the DI fails weird things happen, for example for a DELETE request it just returns 200 (which is how I found this with the fuzzer).

2024-12-15 12:18 UTC, nickvergessen commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
The only place returning/exposing `UserStatusPredefined` is filtering by that attribute, so it is actually:
```suggestion
 *     visible: true,
```

But it sounds like the field should never have been exposed at all, as it's internal preparation. So I would say the best option would be:
```suggestion
```

But that needs some code in the controller to convince Psalm

2024-12-17 12:07 UTC, provokateurin commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
> But that needs some code in the controller to convince Psalm

A simple `unset()` should do it

2024-12-18 07:35 UTC, nickvergessen commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
yes, just meant it needs to touch the actual code

2024-12-18 07:35 UTC, nickvergessen commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
Hopefully no client would use this field yet ;)

2024-12-18 07:39 UTC, provokateurin commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
Right, because this is in fact a breaking change.
So either we go with my change or we always set it to true (which has the same meaning as undefined here).

2024-12-18 07:53 UTC, nickvergessen commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
But your change widens the API and could subsequently break it :P 
I'd say we change it to:
```suggestion
 *     visible: true,
```
Because that is what is currently returned on the API

2024-12-18 07:57 UTC, provokateurin commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
The relevant code is `return !array_key_exists('visible', $status) || $status['visible'] === true;` which means the value can be either `true` or not present. So the more correct signature would be `visible?: true`, but it has to be marked as not required either way.

2024-12-18 08:00 UTC, provokateurin commented on apps/user_status/lib/ResponseDefinitions.php
> + *     visible?: bool,
Ah but I think we can actually safely remove the field from the output. It is either not present or `false` in the data, so it actually never appears in the output. Even though the spec was broken before, any client must have already handled this in some way.

2024-12-18 08:58 UTC, nickvergessen approved these changes

2024-12-18 10:46 UTC, merged