feat(lexicon): configurable default value
nextcloud/server pull request #49848
Opened 2024-12-13 14:54 UTC by ArtificialOwl

This feature require that the config key is listed in the Config Lexicon.

- add a new system config key `'lexicon.default.userconfig'` that overwrite default userconfig value:
```
   'lexicon.default.userconfig' => ['core' => ['lang' => 'fr']],
```
- add a new system config key `'lexicon.default.userconfig.enforced'` that lock config value to default:
```
   'lexicon.default.userconfig.enforced' => ['core' => ['lang' => true]],
```

_(enforced default value will be chosen from the one stored in `config.php`, the one set in the lexicon then to the one from the code)_

- add a `CoreConfigLexicon` for `'core'` config keys

**also some improvement in the resource management**

- extract default value only if needed,
- lazy conversion of default to string.

2024-12-15 11:59 UTC, nickvergessen commented on lib/private/Config/UserConfig.php
> +		// with 'lexicon.default.userconfig' => [<app>.<key> => 'my value'], in config.php
```suggestion
		// with 'lexicon.default.userconfig' => [<app> => [<key> => 'my value']], in config.php
```
Better nested arrays than magic string concatenation?

2024-12-16 15:25 UTC, ArtificialOwl commented on lib/private/Config/UserConfig.php
> +		// with 'lexicon.default.userconfig' => [<app>.<key> => 'my value'], in config.php
could be, mine seems just more human readable

2025-01-09 09:41 UTC, come-nc commented on core/Command/Config/App/GetConfig.php
> +			$configValue = $this->appConfig->getValueMixed($appName, $configName, $defaultValue ?? '');
This is weird, it means adding `--default-value "A"` may result in returning `"B"` instead of exiting. It will confuse most people.

2025-01-09 09:41 UTC, come-nc commented on lib/private/Config/Lexicon/CoreConfigLexicon.php
> + * @since 31.0.0
```suggestion
```
No need for `@since` in `lib/private`.

2025-01-09 09:41 UTC, come-nc commented on lib/private/Config/UserConfig.php
>  	 * @throws TypeConflictException
Document `@return `to explain what the bool means please.

2025-01-09 09:41 UTC, come-nc commented on lib/private/Config/UserConfig.php
> +			return true; // if key exists there should be no need to extract default
I’m pretty sure we do not use inline comments at the end of lines like this in the rest of the code, I’m surprised it’s allowed by our code checker.
Could you move those to be on the line before what they document?

2025-01-09 10:39 UTC, ArtificialOwl commented on core/Command/Config/App/GetConfig.php
> +			$configValue = $this->appConfig->getValueMixed($appName, $configName, $defaultValue ?? '');
ok, reverting

2025-01-09 10:40 UTC, ArtificialOwl commented on lib/private/Config/Lexicon/CoreConfigLexicon.php
> + * @since 31.0.0
removing, but i still think it can still be useful to help working on backport

2025-01-09 10:41 UTC, ArtificialOwl commented on lib/private/Config/UserConfig.php
> +			return true; // if key exists there should be no need to extract default
ok

2025-01-09 10:47 UTC, nickvergessen commented on lib/private/Config/Lexicon/CoreConfigLexicon.php
> + * SPDX-License-Identifier: AGPL-3.0-only
```suggestion
 * SPDX-License-Identifier: AGPL-3.0-or-later
```

2025-01-09 10:48 UTC, nickvergessen commented on lib/unstable/Config/Lexicon/ConfigLexiconEntry.php
also change the license here please

2025-01-09 10:50 UTC, come-nc requested changes

2025-01-09 10:52 UTC, nickvergessen commented on lib/unstable/Config/Lexicon/ConfigLexiconEntry.php
Applies to all files in `Lexicon/`

2025-01-13 13:37 UTC, come-nc approved these changes

2025-01-13 13:37 UTC, come-nc commented on lib/private/Config/Lexicon/CoreConfigLexicon.php
> + * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
```suggestion
 * SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
```
Happy new year!

But nitpicking really. :door: :runner:

2025-01-13 14:33 UTC, sorbaugh approved these changes

2025-01-14 16:12 UTC, merged