fix: change translation logic to handle plurals better
nextcloud/server pull request #49852
Opened 2024-12-13 23:22 UTC by SebastianKrupinski

* Resolves: #https://github.com/nextcloud/server/issues/49756

## Summary
- Altered phrase generation logic to work better with plurals and time intervals
- Added more test to cover all possible scenarios 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-12-13 23:24 UTC, SebastianKrupinski commented
/backport to stable30

2024-12-13 23:27 UTC, SebastianKrupinski commented
Code added in 30, do not backport further.

2024-12-14 12:08 UTC, rakekniven approved these changes

2024-12-16 08:07 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		return match ([$occurrenceIn['scale'], !empty($occurrence2), !empty($occurrence3)]) {
would a null or empty string comparison work too to replace `empty`?

https://dev.to/klnjmm/never-use-empty-function-in-php-4pb0

2024-12-16 14:37 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +				'',
This seems to work correctly as is...

Singular
![image](https://github.com/user-attachments/assets/43508022-dae7-430f-816d-5df0832c1033)

Plural
![image](https://github.com/user-attachments/assets/b8ebfe00-0125-4c19-aed8-7a94afc4e449)

2024-12-16 14:37 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +				'In a minute on %1$s for the entire day',
See above

2024-12-16 14:37 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		return match ([$occurrenceIn['scale'], !empty($occurrence2), !empty($occurrence3)]) {
Yes, a isset() will work also.

2024-12-16 14:37 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +				'',
See comment above

2024-12-16 14:41 UTC, SebastianKrupinski commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +				'',
$occurring['interval'] = is a time interval (0+ integer) it will never be empty.

2024-12-16 15:20 UTC, ChristophWurst commented on apps/dav/lib/CalDAV/Schedule/IMipService.php
> +		return match ([$occurrenceIn['scale'], !empty($occurrence2), !empty($occurrence3)]) {
Please use an explicit null and empty string comparison. Isset has unexpecte side effects too https://dev.to/aleksikauppila/using-isset-and-empty-hurts-your-code-aaa

2024-12-18 09:26 UTC, ChristophWurst approved these changes

2024-12-18 16:27 UTC, ChristophWurst requested changes
Needs a squash for clean git history.

Requesting as change so this isn't merged prematurely.

2024-12-19 13:54 UTC, ChristophWurst approved these changes

2024-12-24 12:17 UTC, st3iny requested changes
Still not clean. Please rebase when updating the branch instead of merging master into your work branch.

2024-12-27 16:03 UTC, st3iny approved these changes

2025-01-07 08:49 UTC, merged

2025-01-07 09:19 UTC, st3iny commented
We did it, after 20 attempts :tada: :tada: :tada:

2025-01-07 09:25 UTC, SebastianKrupinski commented
> We did it, after like 20 attempts 🎉 🎉 🎉

🤣 🤣 🤣  Yeah, tell me about it.

Now we can have the same fun with the backport