[WIP] feat: file conversion provider
nextcloud/server pull request #49922
Opened 2024-12-18 23:09 UTC by elzody

* Part of: https://github.com/nextcloud/server/issues/49603

## Summary

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

2024-12-19 21:48 UTC, juliusknorr commented on lib/public/Conversion/IConversionManager.php
> +	public function convert(File $file, string $targetMimetype): File;
I'm still unsure if we rather should return either a stream or just a path to a temporary file here

2024-12-19 21:50 UTC, juliusknorr commented on lib/public/Conversion/ConversionMimeTuple.php
> +		private string $to,
Something i haven't thought about but we could also make the target mime types an array here, but no strong opinion here from my side.

2024-12-20 20:13 UTC, elzody commented on lib/public/Conversion/IConversionManager.php
> +	public function convert(File $file, string $targetMimetype): File;
Indeed, I have been wondering as well. I will have to think on it for a bit, which would be better. Maybe we can also have a discussion on it next week in a call

2024-12-20 20:16 UTC, elzody commented on lib/public/Conversion/ConversionMimeTuple.php
> +		private string $to,
Hmm, do you mean that, in the scenario where the provider can convert the same MIME type to multiple other MIME types, instead of registering multiple `ConversionMimeTuple`s for the same original MIME type with different output MIME types, it would just be one and could have an array of output MIME types it can convert it to?

2024-12-20 21:04 UTC, elzody commented on lib/public/Conversion/IConversionManager.php
> +	public function convert(File $file, string $targetMimetype): File;
Since we probably want this to work well with the workflow engine, maybe it would make more sense to return a file path. Maybe, if a target destination is passed to the API endpoint, we could convert the file with the appropriate conversion provider, then store the file there and return its location/metadata in the response. Or, if no destination is provided, we could just use a temporary location?

For the interfaces though, maybe it would rather make sense to leave them as they are, so if the providers are called another way (say from the same app which implements it) the developer could just use it however they like. But not sure how you want to go about it.

2024-12-27 16:26 UTC, juliusknorr commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
Something just came to my mind is that for integrating the user interface we may also want additional metadata for the target formats. 

We can probably get the file extension from our mimetype mapping, but wondering if we need to have more details, like a display name. Similar to save dialogs that came to my mind:


<img width="475" alt="Screenshot 2024-12-27 at 17 26 10" src="https://github.com/user-attachments/assets/219beb6b-2974-4125-baaf-f0d7d4226f87" />

2024-12-27 16:28 UTC, juliusknorr commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
@sorbaugh Has the files team already discussed any UI parts with designers? I'd say we can start with this PR and could extend/adapt on demand later on as well.

2025-01-09 13:54 UTC, skjnldsv commented on core/Controller/ConversionApiController.php
> +		try {
Maybe also check the parent folder CREATE permissions?

2025-01-09 15:34 UTC, elzody commented on core/Controller/ConversionApiController.php
> +		try {
This is a good point. I just did some testing by sharing a view-only folder with a document in it to another user, and it will already throw an `OCP\Files\NotPermittedException` if it cannot write to the destination ([L122](https://github.com/nextcloud/server/blob/e91c44701430f8b3ce9c5fe98621aa7380544ffc/lib/private/Conversion/ConversionManager.php#L122)), which then returns something like this in the network response via an `OCSException`:

```json
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 999,
      "message": "Could not create path \"/alice/files/Bobs_Shared_Folder/converted_file.pdf\""
    },
    "data": []
  }
}
```

I can still implement an explicit check if necessary, though. What do you think?

2025-01-09 21:22 UTC, provokateurin commented on core/Controller/ConversionApiController.php
IMO this should be called FileConversionApiController.
The current name in the context of core is too generic.
Alternatively this could be moved to the files app, then the controller name is fine with me.

2025-01-09 21:24 UTC, provokateurin commented on config/config.sample.php
> + * Default: 100 megabytes
```suggestion
 * Default: 100 MiB
```
I think you mean mibibytes (base 1024 and not 1000 like we use it everywhere else) and using the abbreviation is a bit more common.

2025-01-09 21:24 UTC, provokateurin commented on core/Controller/ConversionApiController.php
The same thing also applies to everything in lib/, the name is too generic with out the Files prefix.

2025-01-09 22:20 UTC, elzody commented on core/Controller/ConversionApiController.php
Seems like an easy enough change, I am fine with changing it for the extra specificity I suppose.

2025-01-10 07:21 UTC, skjnldsv commented on core/Controller/ConversionApiController.php
> +		try {
> I can still implement an explicit check if necessary, though

I am usually in favour of clear sanity checks.
Because if something breaks/changes in the following methods, we'll have no way of knowing it.

2025-01-10 08:58 UTC, skjnldsv commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
Ah, I literally [added a similar comment](https://github.com/nextcloud/server/pull/49922/files#r1910018136) eheh

Two options I think:
1. We stop using `getSupportedMimeTypes` and go back to a singular `getSupportedMimeType`, and we basically use the name, only one Provider per destination mime
2. We turn this into a `mime => l10n` array, so we know the end name of each mime :)

2025-01-13 22:40 UTC, elzody commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
Hopefully my new additions satisfy this need -- was a bit difficult understanding how you wanted it, but it more or less serves the purpose.

2025-01-14 07:31 UTC, provokateurin requested changes
Very nice! I only have a few smaller things to not, feel free to ignore the most nit picky ones :sweat_smile:

2025-01-14 07:31 UTC, provokateurin commented on apps/files/lib/Capabilities.php
> +				'conversions' => $this->fileConversionManager->getMimeTypes(),
```suggestion
				'file_conversions' => $this->fileConversionManager->getMimeTypes(),
```

2025-01-14 07:31 UTC, provokateurin commented on apps/files/lib/Capabilities.php
> +	 * @return array{files: array{'$comment': ?string, bigfilechunking: bool, blacklisted_files: list<mixed>, forbidden_filenames: list<string>, forbidden_filename_basenames: list<string>, forbidden_fil
```suggestion
	 * @return array{files: array{'$comment': ?string, bigfilechunking: bool, blacklisted_files: list<mixed>, forbidden_filenames: list<string>, forbidden_filename_basenames: list<string>, forbidden_filename_characters: list<string>, forbidden_filename_extensions: list<string>, chunked_upload: array{max_size: int, max_parallel_count: int}, file_conversions: list<array{from: string, to: array<string, string>}>}}
```
I believe this is the correct typing.

2025-01-14 07:31 UTC, provokateurin commented on lib/public/Files/Conversion/IConversionManager.php
> +	 * @return array<ConversionMimeTuple>
```suggestion
	 * @return list<ConversionMimeTuple>
```

2025-01-14 07:31 UTC, provokateurin commented on apps/files/lib/Controller/ConversionApiController.php
> +	#[OpenAPI(scope: OpenAPI::SCOPE_DEFAULT)]
```suggestion
```
Not needed

2025-01-14 07:31 UTC, provokateurin commented on apps/files/lib/Controller/ConversionApiController.php
> +			'path' => PathHelper::getRelativePath($userFolder->getInternalPath(), $convertedFile) ?? $convertedFile,
The fallback makes no sense to me. If the relative path can't be computed then an exception should be thrown.

2025-01-14 07:31 UTC, provokateurin commented on apps/files/tests/Controller/ConversionApiControllerTest.php
> +	private $user;
Please make them strong typed.

2025-01-14 07:31 UTC, provokateurin commented on apps/files/lib/Capabilities.php
> +				'conversions' => $this->fileConversionManager->getMimeTypes(),
You also need to map them and call jsonSerialize() for the typing to be correct.

2025-01-14 07:31 UTC, provokateurin commented on lib/private/Files/Conversion/ConversionManager.php
> +			array_push($mimeTypes, $provider->getSupportedMimeType());
```suggestion
			$mimeTypes[] = $provider->getSupportedMimeType();
```
A bit more modern (and IMO readable) syntax, but doesn't really matter in the end.

2025-01-14 07:31 UTC, provokateurin commented on lib/private/Files/Conversion/ConversionManager.php
> +		$threshold = $this->config->getValue('max_conversion_filesize', 100);
```suggestion
		$threshold = $this->config->getValue('max_file_conversion_filesize', 100);
```

2025-01-14 07:31 UTC, provokateurin commented on config/config.sample.php
> +'max_conversion_filesize' => 100,
```suggestion
'max_file_conversion_filesize' => 100,
```

2025-01-14 07:31 UTC, provokateurin commented on lib/public/Files/Conversion/ConversionMimeTuple.php
> +	 * @param array<string,string> $to The desired MIME type for the file mapped to its translated name
```suggestion
	 * @param array<string, string> $to The desired MIME type for the file mapped to its translated name
```

2025-01-14 07:31 UTC, provokateurin commented on lib/public/Files/Conversion/ConversionMimeTuple.php
> +	 * @since 31.0.0
You should type the return type of this method, otherwise psalm doesn't really check the types later on when jsonSerialize() is called.

2025-01-14 07:31 UTC, provokateurin commented on lib/private/Files/Conversion/ConversionManager.php
> +		$threshold = $this->config->getValue('max_conversion_filesize', 100);
Wouldn't it make sense to also check that the threshold is a sensible value? Otherwise an admin might configure something like 100 GiB and break their instance. I'm not sure what a reasonable limit is, especially when it comes to high resolution photos or long (high resolution) videos.

2025-01-14 07:31 UTC, provokateurin commented on lib/public/Files/Conversion/IConversionManager.php
> +	 * @return bool
```suggestion
```
Not needed

2025-01-14 07:31 UTC, provokateurin commented on lib/public/Files/Conversion/IConversionProvider.php
> +	 * @return ConversionMimeTuple
```suggestion
```
Not needed

2025-01-14 08:35 UTC, juliusknorr commented on lib/private/Files/Conversion/ConversionManager.php
> +		$threshold = $this->config->getValue('max_conversion_filesize', 100);
I don't see a risk of breaking the instance here. If an admin configures long timeouts then it should be fine. At some point we may rather want to have background workers that do an async conversion so we don't run into timeouts (which is the main reason for adding this), but this was discussed out of scope due to the short-term scheduling with @AndyScherzinger.

2025-01-14 15:09 UTC, juliusknorr commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
Is it just a single tuple for each provider now? I think for others like collabora it might be easier to rather return an array of tuples, bug agree, the general format seems good like this.

2025-01-14 15:23 UTC, skjnldsv commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
I personally have no preferences on that part of the API.
As long as I have both the mime and its associated translatable string, I'm ok with it :+1:

2025-01-14 15:26 UTC, elzody commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
I also agree it would be more efficient when you have a lot of conversion options (like we do with Collabora) to be able to specify them with one provider, but also have the option to use multiple providers to separate some logic if necessary

2025-01-14 15:33 UTC, provokateurin commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
Shouldn't the `from` part then also be an array so each provider can advertise multiple source mime types at once?

2025-01-14 15:54 UTC, juliusknorr commented on apps/testing/lib/Conversion/ConversionProvider.php
> +			'image/png',
> I also agree it would be more efficient when you have a lot of conversion options (like we do with Collabora) to be able to specify them with one provider, but also have the option to use multiple providers to separate some logic if necessary

One provider with multiple tuples seems a bit more flexible still. That way you can still have multiple provider classes if the implementation differs.

> Shouldn't the from part then also be an array so each provider can advertise multiple source mime types at once?

Could also. I feel like a plain list is a bit easier to read and maintain, but no strong opinion there.

2025-01-15 08:51 UTC, provokateurin approved these changes

2025-01-15 08:51 UTC, provokateurin commented on lib/private/Files/Conversion/ConversionManager.php
> +			$mimeTypes = array_merge($mimeTypes, $providerMimeTypes);
Calling array_merge() in a loop is expensive. Instead you can do it like this:

```php
$mimeTypes = [];

foreach ($this->getProviders() as $provider) {
	$mimeTypes[] = $provider->getSupportedMimeTypes();
}

$mimeTypes = array_merge(...$mimeTypes);
```

2025-01-15 12:35 UTC, juliusknorr approved these changes

2025-01-15 13:07 UTC, AndyScherzinger approved these changes

2025-01-15 13:18 UTC, juliusknorr commented on apps/files/lib/Capabilities.php
> +					return $mimeTuple->jsonSerialize();
It looks like this part is failing to serialize to xml in the integration tests, but have not checked locally, so not sure what the best way to fix this is.

```
{
  "reqId": "6YTbALAvT2hTLsT4X3ec",
  "level": 3,
  "time": "2025-01-14T22:43:50+00:00",
  "remoteAddr": "::1",
  "user": "admin",
  "app": "PHP",
  "method": "GET",
  "url": "/ocs/v1.php/cloud/capabilities",
  "message": "ValueError: XMLWriter::writeElement(): Argument #2 ($content) must be a valid element name, \"image/png\" given at /home/runner/actions-runner/_work/server/server/lib/private/AppFramework/OCS/BaseResponse.php#149",
  "userAgent": "GuzzleHttp/7",
  "version": "31.0.0.9",
  "data": {
    "app": "PHP"
  }
}

2025-01-15 13:46 UTC, provokateurin commented on apps/files/lib/Capabilities.php
> +					return $mimeTuple->jsonSerialize();
Hm yeah that is tricky, seems like `/` is forbidden as tag name (makes sense since it is part of the XML syntax).
The output format could be changed so that it's no longer used as a key but the entire data structure is a list and the source format is just a property of the objects in the list.

2025-01-15 16:02 UTC, skjnldsv commented
As a followup, it would be nice to add some integration tests.
Should be easy to test :
- the api response on failure 
- the proper new png file after the api conversion endpoint have been reached

2025-01-15 23:02 UTC, merged

2025-01-16 07:28 UTC, skjnldsv commented
:tada: :tada: :tada:

2025-01-16 08:31 UTC, juliusknorr commented on apps/files/lib/Controller/ConversionApiController.php
> +			throw new OCSException($e->getMessage());
We should log the exception here and rather return a generic error message as the exception message may leak server internals. Also the trace is lost.

2025-01-16 08:34 UTC, juliusknorr commented on lib/public/Files/Conversion/ConversionMimeTuple.php
> +	 * @param list<array{mime: string, name: string}> $to The desired MIME type for the file mapped to its translated name
@elzody @skjnldsv I just noticed when implementing a simple pandoc provider, that we may also want to have the extension as a separate property for target formats. We list it in the name, but I assume for automatically generating a file with the new extension we should also have it directly accessible so it can be used to build the target file name on the frontend side?

2025-01-16 09:17 UTC, skjnldsv commented on lib/public/Files/Conversion/ConversionMimeTuple.php
> +	 * @param list<array{mime: string, name: string}> $to The desired MIME type for the file mapped to its translated name
Not sure I follow :thinking:

2025-01-16 09:38 UTC, juliusknorr commented on lib/public/Files/Conversion/ConversionMimeTuple.php
> +	 * @param list<array{mime: string, name: string}> $to The desired MIME type for the file mapped to its translated name
Just FYI @elzody .. @skjnldsv had a quick call and noticed that the API only works with passing a destination, without we lack the ability to build the new destination filename. @skjnldsv will look into that as a follow up for the frontend.

We also had another discussion round on https://github.com/nextcloud/server/pull/49922#discussion_r1915000815 and decided to do a small change on the tuple drop the array to to have one tuple for each from-to mapping to be more strict on the api and not have the php array