feat(federation): auto-accept shares from trusted servers
nextcloud/server pull request #49973
Opened 2024-12-26 12:51 UTC by skjnldsv

Fix https://github.com/nextcloud/server/issues/34550

2024-12-26 12:51 UTC, skjnldsv commented
/backport! 9a437d3 fecf818 to master

2024-12-26 16:11 UTC, skjnldsv commented on apps/files_sharing/lib/External/Manager.php
> +		}
Reaaaaaaaally not fond of this :see_no_evil: 
I  haven't figured out a better approach yet, because the entire file is written from a user session pov.
If this is coming from another server, we still need to process this properly :thinking:

2025-01-06 10:13 UTC, come-nc reviewed
A bit of nitpick, apart from that backend code looks good.

2025-01-06 10:13 UTC, come-nc commented on apps/federation/tests/BackgroundJob/GetSharedSecretTest.php
> +
```suggestion
	private MockObject&IConfig $config;
```

2025-01-07 08:58 UTC, skjnldsv commented on apps/federation/lib/Controller/SettingsController.php
> +			return new JSONResponse([
Completely forgot about those :facepalm:

2025-01-07 15:10 UTC, provokateurin requested changes
Some things that could be improved over the old code, if you're already migrating it anyway :see_no_evil:

2025-01-07 15:59 UTC, skjnldsv commented on apps/federation/js/settings-admin.js
> +            OC.getRootPath() + '/ocs/v2.php/apps/federation/trusted-servers',
Well, standalone vanilla js files are getting rare around here :wink:

2025-01-07 16:18 UTC, skjnldsv commented on apps/federation/lib/Controller/SettingsController.php
> +			'status' => 'ok',
Will do then :)

2025-01-09 10:48 UTC, skjnldsv commented on apps/federation/lib/Controller/SettingsController.php
> +		}
Well, the only Exception thrown here is because the server was not found.
But I can cover that use case sure

2025-01-09 11:57 UTC, skjnldsv commented on apps/federation/lib/Controller/SettingsController.php
> +		$id = $this->trustedServers->addServer(trim($url));
Not according to the db Handler.
If so, then the OCSMiddleware will take care of it and return a 500 error

2025-01-09 14:33 UTC, come-nc commented on apps/federation/lib/Controller/SettingsController.php
> +			$this->logger->error($e->getMessage(), ['app' => 'federation']);
```suggestion
			$this->logger->error($e->getMessage(), ['exception' => $e]);
```
app is automatic when using DI, and exception should be provided when available to help debug.

2025-01-09 14:35 UTC, come-nc approved these changes

2025-01-09 14:37 UTC, come-nc commented on apps/federation/lib/TrustedServers.php
> +	 * @throws Exception
```suggestion
	 * @throws \Exception
```
`Exception` here refers to \OC\DB\Exception which is in the use statements, but you are throwing `\Exception`.

2025-01-09 14:39 UTC, skjnldsv commented on apps/federation/lib/TrustedServers.php
> +	 * @throws Exception
done

2025-01-09 14:39 UTC, skjnldsv commented on apps/federation/lib/Controller/SettingsController.php
> +			$this->logger->error($e->getMessage(), ['app' => 'federation']);
done

2025-01-09 15:38 UTC, ChristophWurst approved these changes
Looks sane, didn't test

2025-01-09 15:38 UTC, ChristophWurst commented on apps/federatedfilesharing/src/components/AdminSettings.vue
> +.settings-subsection__name {
nit: use scss and move this into `.settings-subsection`?

2025-01-09 15:38 UTC, ChristophWurst commented on apps/federation/lib/Controller/SettingsController.php
> +		$servers = array_map(function ($server) {
nit: introduce a new variable instead of repurposing the old one.

```suggestion
		$redactedServers = array_map(function ($server) {
```

2025-01-09 15:38 UTC, ChristophWurst commented on apps/federation/lib/Controller/SettingsController.php
> +			throw new OCSNotFoundException($this->l->t('No server found with ID: %s', [$id]));
It *could* be something else as well, other than *server not found*. Log the exception at debug level.

2025-01-09 15:39 UTC, provokateurin approved these changes

2025-01-09 15:39 UTC, merged

2025-01-09 15:39 UTC, ChristophWurst commented
I did not expect the fast merge :x