Prefer custom theme over the theming app
nextcloud/server pull request #5070
Opened 2017-05-23 14:10 UTC by juliushaertl

This PR will prevent the theming app from loading its CSS/JavaScript/Images in case a custom theme is used.

This occured in https://github.com/nextcloud/server/issues/5036 and https://github.com/nextcloud/server/issues/3094 

I think this is better default behavior.

2017-05-30 09:56 UTC, nickvergessen commented on lib/private/URLGenerator.php
> -			$path =  \OC::$WEBROOT . "/themes/$theme/apps/$app/img/$basename.png";
Accident?

2017-05-30 11:20 UTC, juliushaertl commented on lib/private/URLGenerator.php
> -			$path =  \OC::$WEBROOT . "/themes/$theme/apps/$app/img/$basename.png";
Yes, fixed that. Thanks.

2017-06-13 22:57 UTC, MorrisJobke commented
@juliushaertl Conflicts.

2017-06-19 22:42 UTC, MorrisJobke approved these changes
Works

2017-07-05 14:23 UTC, MorrisJobke commented
Please review ;)

2017-07-06 09:12 UTC, nickvergessen commented
Works

2017-07-06 09:12 UTC, nickvergessen approved these changes

2017-07-06 09:13 UTC, nickvergessen commented
```
There were 2 failures:
1) OCA\Theming\Tests\UtilTest::testIsAlreadyThemedFalse
Expectation failed for method name is equal to <string:getSystemValue> when invoked 1 time(s)
Parameter 0 for invocation OCP\IConfig::getSystemValue('theme', '') does not match expected value.
'theme' does not match expected type "array".
/drone/src/github.com/nextcloud/server/apps/theming/lib/Util.php:208
/drone/src/github.com/nextcloud/server/apps/theming/tests/UtilTest.php:189
2) OCA\Theming\Tests\UtilTest::testIsAlreadyThemedTrue
Expectation failed for method name is equal to <string:getSystemValue> when invoked 1 time(s)
Parameter 0 for invocation OCP\IConfig::getSystemValue('theme', '') does not match expected value.
'theme' does not match expected type "array".
/drone/src/github.com/nextcloud/server/apps/theming/lib/Util.php:208
/drone/src/github.com/nextcloud/server/apps/theming/tests/UtilTest.php:199
```

2017-07-06 09:13 UTC, nickvergessen requested changes
Tests fail

2017-07-12 12:20 UTC, juliushaertl commented
@nickvergessen Fixed :wink:

2017-07-13 11:41 UTC, nickvergessen approved these changes

2017-07-13 11:41 UTC, merged