Change slogan to “Your Secure Workspace”
nextcloud/server pull request #5109
Opened 2017-05-25 09:39 UTC by MariusBluem

* according to https://github.com/nextcloud/nextcloud.com/commit/d698ddba6a29f8074de9e601bcdb84c7cacf2055

Is it needed to adjust the `l10n`-files? 🤔 @MorrisJobke 

Signed-off-by: Marius Blüm <marius@lineone.io>

2017-05-26 04:09 UTC, LukasReschke requested changes

2017-05-26 04:09 UTC, LukasReschke commented on tests/data/emails/new-account-email-custom.html
> -</html>
I think by adding a newline here you broke the tests :-)

See https://drone.nextcloud.com/nextcloud/server/8336/2

2017-05-26 09:10 UTC, nickvergessen commented
> Is it needed to adjust the l10n-files?

No ❗️

2017-05-26 09:11 UTC, nickvergessen commented
I dislike this change.

2017-05-28 09:41 UTC, jospoortvliet commented
I would certainly wait. We changed the slogan on the front page after some discussion where we couldn't come to a clear agreement so decided to try and see what ppl say ;-)

Still waiting, didn't hear any spontaneous comments yet...

2017-05-29 07:37 UTC, closed without merging