the 10px make's a scrollbar at bottom
nextcloud/server pull request #5113
Opened 2017-05-25 18:29 UTC by blackcrack

Hi,

the patting 3px 3px 3px 10px 
makes to become at bottom an scrollbar and looks terrible ,
for remove it, to make at all 3px around and the "error" it is resolved
and we have a clean Contactsearchbar menu at bottom
with only a scrollbar at right side :)

best regards
Blacky

2017-05-25 18:48 UTC, MariusBluem commented
Please have a look into our [Contribution Guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md) ... Please sign-off your commits (Developer Certificate of Origin)

Can you post a screenshot before and after this change?

2017-05-25 19:14 UTC, blackcrack commented
Hi Marius :)
no, i have no screenshoot, but it is fast verified, edit the css-file and change the entry
by a running instance ..

and sign-off ? how works that ?
best regards
Blacky

2017-05-25 19:21 UTC, MariusBluem commented
Well ... I have tested your PR already, and for me - there was no visible change. This is, why I have requested a screenshot 😅

You will find the information about signing-off commits in the Contribution Guidelines, i've linked above. 

Example:

`Signed-off-by: John Doe <john.doe@example.com>`

Simply add this to your commits comment, or do this via a `git commit --signoff`

2017-05-25 19:32 UTC, blackcrack commented
well, i have see a scrollbar at bottom ..
and my email ever publishing whant i do not because the whole bots, i become enough spam.
My mail it is on my Github accound and if i make crap, become i am an bann on github, so, i can maybe
Signed-off-by Blackcrack  but not with my full mailadress..
because this is deposited at Github ;)

2017-05-25 20:22 UTC, jancborchardt commented
As @MariusBluem already commented, it would be really great to post a screenshot. :) It makes design changes so much quicker to verify and everyone knows what you wanted to change.

2017-05-26 03:57 UTC, blackcrack commented
wegen so einer kleinen änderung dann noch so ne arbeit.. und dafür bekom
ich nicht mal geld von euch..
beim nächsten mal überleg ich mir ob ich so was bei euch verbessere..
danke !

2017-05-26 05:40 UTC, MariusBluem commented
Please have a very close look into our Code of Conduct (https://nextcloud.com/code-of-conduct/) ... unfortunately, we discuss this topic (contribution and offense) not the first time with you :(

Of course we know Nextcloud, and its features - but if you change something, it would be really nice to know exactly *what* you have wanted to change, since some changes may not only fix your issue - they will introduce new ones too ;)

However ... Thank you for your screenshots 🙈 We are now seeing the intention of this PR - and will review this PR as soon as possible 😉

2017-05-26 05:55 UTC, blackcrack commented
\*thumps up\*

2017-05-26 08:28 UTC, MariusBluem commented
I have just reviewed the issue you are reporting, and the fix you are providing. Unfortunately, I am not seeing this scrollbar you are talking about. 

**Safari:**
<img width="499" alt="bildschirmfoto 2017-05-26 um 10 17 32" src="https://cloud.githubusercontent.com/assets/19711361/26486806/fb3be91c-41fc-11e7-826a-c7f15995a214.png">

**Google Chrome:**
<img width="483" alt="bildschirmfoto 2017-05-26 um 10 17 01" src="https://cloud.githubusercontent.com/assets/19711361/26486847/272eb220-41fd-11e7-8977-f2f08464d72e.png">

**Mozilla Firefox:**
<img width="615" alt="bildschirmfoto 2017-05-26 um 10 24 13" src="https://cloud.githubusercontent.com/assets/19711361/26486943/8690c0d2-41fd-11e7-924b-3a70c704ceb0.png">

2017-05-26 10:20 UTC, blackcrack commented
in Apple Macintosh  ?

2017-05-26 11:19 UTC, MariusBluem commented
> in Apple Macintosh ?

Yes.

> the Safary looks like the Round Button stay over at bottom .. ?

Already reported: #5119 

> now would interested on IE in Win7 (damn, i have forgotten to do that *g*

Somebody with Windows needs to test this 😉

2017-05-26 11:33 UTC, blackcrack commented
JC, do what for your stand position \*bg\*

2017-05-26 13:45 UTC, juliusknorr requested changes
Having a smaller padding doesn't work here, since the avatars are then no longer aligned correctly. We should get rid of the fixed width here, that seems to cause the scroll bars when text gets ellipsised:

https://github.com/nextcloud/server/pull/5113/files#diff-786abfdec65b6ba7b37e0daff7bc3b5eL1136

2017-05-26 14:24 UTC, blackcrack commented
and a lil' tip
.menu, this should rename as .contactssearchmenu because many can be a menu,
likely more well giving different names (also for found more easy) as very short and no striking/distinctive names and have later more heavy ..

best regards
blacky

2017-05-30 14:43 UTC, jancborchardt commented
Yeah, I can’t see the scrollbar either. (That’s why the screenshots are also useful since we can not reproduce. ;)

Agree with @juliushaertl – probably we need to do some flexbox here.

> .menu, this should rename as .contactssearchmenu because many can be a menu

It’s specifically for that reason that we used that class. :) Because it works with the existing CSS and Javascript to give the proper style and also close other open `.menu` elements when opening a new one.

2017-06-06 20:26 UTC, juliushaertl commented
> Yeah, I can’t see the scrollbar either. (That’s why the screenshots are also useful since we can not reproduce. ;)

You can just create a contact with a very long name, that will be ellipsized, then the scollbar will show up.

2017-09-14 13:48 UTC, jancborchardt commented
So how do we continue here @juliushaertl @blackcrack? Adjust this, or scrap and start over?

2017-09-14 13:57 UTC, juliushaertl commented
I see no need to change the class naming there since it is just our general menu style, right? Anyway we should fix the issue with a scroll bar when you have really long names in the contacts menu.

2017-10-27 12:24 UTC, MorrisJobke commented
As there is no feedback here, I will close this for now. The contact menu should be fixed in a separate PR.

2017-10-27 12:24 UTC, closed without merging