Update layout.user.php
nextcloud/server pull request #5200
Opened 2017-05-31 17:03 UTC by stobbsm

The icon for more apps was set to always be white, which didn't respect having a contrast on lighter colours.
Changed it to the generic "icon-more" class so it can be seen on light backgrounds.

Signed-off-by: Matthew Stobbs <matthew@sproutingcommunications.com>

2017-06-01 06:52 UTC, juliusknorr requested changes
Thanks for your pull request. Just moving to icon-more will break default behavior and make the icon always black.

Best way to adjust this is to overwrite the icon image in apps/theming/css/theming.scss.

2017-06-01 15:40 UTC, stobbsm commented
Changed by adding a specific selector the theming.scss as suggested. Works on my production server.

I've never had to update a pull request before. Did the branch update automatically get pushed through?

2017-06-19 22:40 UTC, MorrisJobke commented
@stobbsm Sorry to say so, but this was fixed by @juliushaertl in #5450.

Thanks for your effort anyway. You maybe could check out other starter issues: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22starter+issue%22

I will close this one here then.

2017-06-19 22:40 UTC, closed without merging

2017-06-20 17:33 UTC, juliushaertl commented
@stobbsm Sorry about that. I remembered that i saw some issue with the three dots menu but i couldn't find your pull request when searching for it.