Now using dynamic percentual appmenu limit
nextcloud/server pull request #5244
Opened 2017-06-04 01:30 UTC by patschi

PR for using percentual appmenu limit like discussed in #5135. Further discussions in the linked issue.

2017-06-08 15:54 UTC, jancborchardt commented
@nextcloud/designers let’s review! :)

@karlitschek what do you think about this approach?

2017-06-08 17:46 UTC, karlitschek commented
nice 👍

2017-06-09 14:28 UTC, jancborchardt approved these changes
Seems better now! :)

2017-06-09 14:29 UTC, jancborchardt commented
@juliushaertl @eppfel @MorrisJobke @pixelipo what do you think?

2017-06-09 20:51 UTC, pixelipo reviewed
Definitely doesn't look crowded - on my FullHD screen, I get 12 apps in that limit:
![image](https://user-images.githubusercontent.com/4129927/26993742-d1b156fe-4d64-11e7-9195-d617660fd7ce.png)
I think 50% would be ok as well, but using more than 12 apps on a daily basis seems like an edge case anyway...If one needs more, one should use browser bookmarks...

2017-06-09 20:51 UTC, pixelipo commented on core/js/js.js
> +		var availableWidth = (($('#header-left').width() - $('#nextcloud').width()) / 100 * usePercentualAppMenuLimit);
Why not just multiply by 0.33? It would get the same result and decimal is an acceptable representation for percentage.

2017-06-09 20:51 UTC, pixelipo commented on core/js/js.js
>  		var appCount = Math.floor((availableWidth)/44);
I'm not a big fan of hardcoded values. Since we are already fetching logo and app-menu widths from DOM, why not fetch single-app-width as well? It would save us one headache if/when Nextcloud gets redesigned...

2017-06-09 22:13 UTC, patschi commented on core/js/js.js
>  		var appCount = Math.floor((availableWidth)/44);
Tested fine using `$(appList).width()`. Or any other prefered solution from your side?

2017-06-09 22:16 UTC, patschi commented on core/js/js.js
> +		var availableWidth = (($('#header-left').width() - $('#nextcloud').width()) / 100 * usePercentualAppMenuLimit);
Well, it's just a personal preference. I'm fine with decimal notation as well.

2017-06-10 10:29 UTC, jancborchardt commented
> I think 50% would be ok as well, but using more than 12 apps on a daily basis seems like an edge case

Yup, let's leave it at 33% because we also discussed different values before. :) Your other comments are good!

2017-06-10 12:27 UTC, pixelipo commented on core/js/js.js
>  		var appCount = Math.floor((availableWidth)/44);
Perfect!

2017-06-10 19:46 UTC, pixelipo approved these changes

2017-06-10 21:09 UTC, juliushaertl commented
I'm not that happy with the 33%. I usually have my browser on one half of the screen and that way only 4 icons are visible. Not sure if most people have their browser on full screen, but for picking a higher percentage number would make more sense.

![2017-06-10-230356_1920x1079_scrot](https://user-images.githubusercontent.com/3404133/27006325-87b52616-4e31-11e7-9849-7eb33bb09b40.png)

2017-06-10 22:58 UTC, jancborchardt commented
Right, also just saw that. I agree and it's different than we specified. Because here it's in desktop mode (more than 768px width) and hence at least the 8 icons (or 7 + menu) should be shown.

- Mobile (sub 768px): Show as many as possible with a bit of margin
- Desktop: Use max 33% of header width but show at least 8 icons (or 7+menu)

Ok?

2017-06-13 19:24 UTC, eppfel requested changes
..as others mentioned before. It does not show enough icons on lower resolutions

2017-06-14 09:11 UTC, juliushaertl commented
@eppfel @jancborchardt I've pushed a commit to fix that. Please review.

![2017-06-14-105912_340x79_scrot](https://user-images.githubusercontent.com/3404133/27124697-2d559598-50f2-11e7-9661-bdda86a28f2d.png)
![2017-06-14-105930_433x87_scrot](https://user-images.githubusercontent.com/3404133/27124703-302fbba4-50f2-11e7-8f19-48860d4582e5.png)
![2017-06-14-105953_742x86_scrot](https://user-images.githubusercontent.com/3404133/27124711-33ade986-50f2-11e7-9734-93b8a1b0f1a2.png)
![2017-06-14-110025_1438x88_scrot](https://user-images.githubusercontent.com/3404133/27124716-369e8e98-50f2-11e7-8a78-ed1c1be91b84.png)

2017-06-14 09:14 UTC, jancborchardt approved these changes
Seems good now! :)

2017-06-14 10:22 UTC, eppfel approved these changes

2017-06-14 16:36 UTC, merged

2018-05-23 19:57 UTC, ASmith- commented
Why isn't there a Nextcloud administrator option to change a hard-coded default 33% etc.? To me it makes no sense whatsoever to present a 60% Blank Tool Bar to users and hide 11 active tool icons in the ... additional tool app bin forcing users to hunt and peck for them at best. Uses want to see active tools at a mere glance, hiding a majority into a overflow bin to keep the top tool bar Empty Space makes no possible sense whatsoever. Let the individual administrators set and determine the % of empty tool bar space if need be on this.