using login.portal.url to redirect users when password change
nextcloud/server pull request #5255
Opened 2017-06-05 17:05 UTC by daita

This will just add an entry in Personal with a link to the Portal.
This does not remove the current part of the Personal where you can change your password.

2017-06-05 17:07 UTC, daita commented
![selection_004](https://cloud.githubusercontent.com/assets/1038617/26794490/fe6f91a6-4a08-11e7-8e15-0f19133bde40.png)

2017-06-05 17:12 UTC, MorrisJobke commented on settings/templates/personal.php
> +		<input id="passwordbutton" type="submit" value="<?php p($l->t('Change your password from the Portal')); ?>" />
I guess we should not use the term portal, because a user doesn't know this concept.

2017-06-05 17:14 UTC, daita commented on settings/templates/personal.php
> +		<input id="passwordbutton" type="submit" value="<?php p($l->t('Change your password from the Portal')); ?>" />
Yeah, also my english is random. Can we find a better text than `Change your password from the Portal` ?

2017-06-05 17:16 UTC, daita commented
Also, I have no idea how to remove the current paragraph that allow to change password:

https://github.com/nextcloud/server/blob/master/lib/private/User/User.php#L321

2017-06-05 17:25 UTC, MorrisJobke commented on settings/templates/personal.php
> +		<input id="passwordbutton" type="submit" value="<?php p($l->t('Change your password from the Portal')); ?>" />
"Change password"

2017-06-05 20:27 UTC, MorrisJobke commented
The sign-off was missing (see https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work) and I fixed it.

2017-06-05 20:27 UTC, MorrisJobke approved these changes

2017-06-06 03:20 UTC, nickvergessen commented
Can we reuse https://github.com/nextcloud/server/blob/master/config/config.sample.php#L258 for this?

2017-06-06 04:00 UTC, MorrisJobke commented
> Can we reuse https://github.com/nextcloud/server/blob/master/config/config.sample.php#L258 for this?

Would make sense. 👍

2017-06-06 08:31 UTC, daita commented
What is this doing ? replacing the change password thing, or allowing a reset of your password from the login page of nextcloud ?

2017-06-06 11:39 UTC, nickvergessen commented
It replaces the reset password form with a link to another website where this can be done, in cases where nc can not change the password. So sounds like it is the same

2017-06-06 13:10 UTC, MorrisJobke commented
> It replaces the reset password form with a link to another website where this can be done, in cases where nc can not change the password. So sounds like it is the same

Ah no - this changes the password reset page, but not the password change. So it's not really the same.

2017-06-12 23:29 UTC, MorrisJobke commented
@nickvergessen @LukasReschke Re-review please.

2017-06-12 23:29 UTC, MorrisJobke commented
> This will just add an entry in Personal with a link to the Portal.
> This does not remove the current part of the Personal where you can change your password.

I would combine that. Either show the one or the other.

2017-06-13 10:25 UTC, nickvergessen requested changes

2017-06-13 10:25 UTC, nickvergessen commented on settings/templates/personal.php
> +		<input id="passwordbutton" type="submit" value="<?php p($l->t('Change your password')); ?>" />
use `<a class="button">` and kill the form please...

2017-06-13 11:24 UTC, LukasReschke commented
I don't really like this approach, I'd either prefer this to be handled via an app or just as a patch sent to the customer in question…

2017-06-13 15:52 UTC, LukasReschke requested changes
I have been looking a little bit more into this and I believe we should solve it the following way:

1. Register a personal page with `\OCP\App::registerPersonal`
2. Use CSS or the JSLoader to move this up

```js
var settingsUrl = OC.generateUrl('/settings/personal');
if(window.location.pathname === settingsUrl) {
	var layout = $('#mySettingsDivChangeThis').detach();
	layout.insertAfter('#passwordform');
}
```

2017-06-13 15:54 UTC, MorrisJobke commented
Let me look into this.

2017-06-13 16:30 UTC, closed without merging