Simplified Nextcloud logo icon
nextcloud/server pull request #5288
Opened 2017-06-07 14:13 UTC by pixelipo

This is part of the SVG optimization task #5157 

Nextcloud logo code has been simplified, but at the same time it's more human-readable.

I've changed the size to more traditional values (256*128). Circles are a bit fatter than they used to be (+0.5px at 128px width). If that is an issue, I can change their width to 21.5px.

`logo-icon.svg` is deprecated since new `logo.svg` is already much smaller in weight.

I've combined `.logo` and `.logo-icon` - this is not strictly needed, I can revert if @nextcloud-design disagrees. It requires adding `logo` class to tags that have `logo-icon` class in apps - mainly where pages are shared publicly, e.g. Calendar.

PNG images and favicons were not edited.

Signed-off-by: Marin Treselj <marin@pixelipo.com>

2017-06-07 22:43 UTC, MorrisJobke commented
cc @nextcloud/designers

2017-06-13 23:10 UTC, MorrisJobke commented
@pixelipo Could I ask you to resolve the conflict?

2017-06-14 09:24 UTC, jancborchardt commented
We need to check this with theming also cc @nextcloud/theming

2017-06-14 09:41 UTC, juliusknorr requested changes

2017-06-14 09:41 UTC, juliushaertl commented on apps/theming/css/theming.scss
> -	@if $theming-logo-mime != '' {
That should not be removed, otherwise we have https://github.com/nextcloud/server/issues/4585 again.

2017-06-14 09:46 UTC, jancborchardt commented on apps/theming/css/theming.scss
> -	@if $theming-logo-mime != '' {
Yeah … when seeing the "contain" I was reminded of something too :D

2017-06-14 10:50 UTC, pixelipo commented
@MorrisJobke I just managed to royally screw up this PR while attempting a rebase :-1:

I guess I'll have to create a new one...

2017-06-14 10:57 UTC, jancborchardt commented
@pixelipo happens to all of us sometimes. ;) It's always best to test the rebase locally, then in case it's broken the last good version is still in the main repository. :)

2017-06-14 10:59 UTC, pixelipo commented on apps/theming/css/theming.scss
> -	@if $theming-logo-mime != '' {
Well, if we want to limit this logo to 175px, as is defined [here](#diff-f6ba04997c6dcc9cec0389d9ef83e358L105), than the solution would be to simply change the width of the `.logo` element. Why is it set to 252px if it never fills that space?

2017-06-14 11:06 UTC, juliushaertl commented
@pixelipo You should be able to just create a new branch from master and run `git cherry-pick de9088d` to pick the commit from this PR.

2017-06-14 11:13 UTC, closed without merging

2017-06-14 11:13 UTC, pixelipo commented
Replaced by #5407 @juliushaertl @jancborchardt please review over there