don't send invitation emails for past events
nextcloud/server pull request #5304
Opened 2017-06-08 09:56 UTC by georgehrke

fixes #2855

2017-06-12 20:13 UTC, LukasReschke submitted a review, later dismissed

2017-06-12 20:13 UTC, LukasReschke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
I'm usually not really a fan of configuration values. Is there a reason we do really need to have that one? 🙈 

Also stuff in the app config is usually easier to deploy on clusters :)

2017-06-12 20:17 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
see #2800, #3830
some people run into issues with our server side scheduling and just want to keep sending their invitations via thunderbird.
or they just don't like that invitations are sent out by the server's email address, not their own one.

2017-06-12 20:18 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
also https://github.com/nextcloud/server/issues/2345

2017-06-12 20:19 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
Not sure we will ever change that value on clusters.

2017-06-27 22:48 UTC, kosli commented
any update on merging this pull request?

2017-06-28 20:26 UTC, georgehrke commented
@kosli There is still something missing, see the first post. Won't have time to look into this before the weekend.

2017-06-29 08:23 UTC, kosli commented
@georgehrke ups, I didn't see the ToDo on top. Thanks!

2017-07-17 10:40 UTC, georgehrke commented
rebased

2017-07-17 10:41 UTC, georgehrke commented
One thing I wasn't sure about:

Should it not send out invitations for any events in the past or only for events that are older than 2 weeks / month ?

2017-07-18 18:23 UTC, jospoortvliet commented
I wouldn't sent out any invitations for past events, after all those either have been sent already or the user decided not to sent them...

2017-07-23 07:39 UTC, georgehrke commented
Backport to review once this is merged: https://github.com/nextcloud/server/pull/5841

2017-08-22 10:54 UTC, ggeorgg commented
Import of a calendar in a fresh nextcloud 12.0.1 with these changes applied is working. The option to turn off resending invitation mails via the config setting is also working.

2017-08-24 07:53 UTC, jospoortvliet commented
@LukasReschke happy with the changes/feedback from Georg? It'd be nice to get this in so 12.0.3 will not resent all these invitations 😢

2017-08-24 09:57 UTC, ggeorgg commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
Besides this configuration value, it would be more intuitive to have a checkbox when importing a calendar. The user itself, who has no access to the config.php should be able to decide whether to send invitaions for future events or not while importing a calendar.

2017-08-24 10:02 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
> it would be more intuitive to have a checkbox when importing a calendar

Or maybe never sent invitations on import? 
Anyway, that's out of scope for this pr.
Let's continue the discussion here: https://github.com/nextcloud/calendar/issues/576

2017-08-27 08:58 UTC, tcitworld approved these changes

2017-08-30 19:04 UTC, MorrisJobke requested changes

2017-08-30 19:04 UTC, MorrisJobke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
I would also not make it a server wide setting. Just remove the added stuff (compared to the backport) and then we can get this in.

2017-09-05 11:12 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
Ok, I will remove that commit for now.
I would anyway still like to add this feature in the future.

Should I just implement it via the appconfig table?

2017-09-05 11:30 UTC, MorrisJobke approved these changes

2017-09-06 20:48 UTC, merged

2017-09-07 08:19 UTC, jospoortvliet commented
AWESOME!