fix moving folders out of a cache jail
nextcloud/server pull request #5424
Opened 2017-06-15 12:01 UTC by icewind1991

Fixes https://github.com/nextcloud/server/issues/3502

@plrunner @mrieser @bat553 please verify if this fixes the problem for you

2017-06-15 12:42 UTC, warnerbryce commented
Hello @icewind1991 

How can i test this fix i don't have this path in my cloud : tests/lib/Files/Cache/Wrapper/CacheJailTest.php

I have the CacheJail.php in lib/private/Files/Cache/Wrapper/ 

Does this CacheJailTest.php is necessary ?

2017-06-15 13:10 UTC, LukasReschke commented
> Does this CacheJailTest.php is necessary ?

This is only the unit test, it is not packaged within the final releases. So you don't have to replace that file, it's only for our automated tests relevant :)

2017-06-16 09:05 UTC, nickvergessen submitted a review, later dismissed

2017-06-16 09:20 UTC, LukasReschke commented
@icewind1991 Can we have a repair step here? If possible a live repair step to not block the upgrade and in multiple smaller steps.

2017-06-16 11:02 UTC, LukasReschke submitted a review, later dismissed
This change works for me locally, but we need to have a way to repair older installations. But there's another desktop client bug … let me try to reproduce this and file to the client repo 🙈

2017-06-16 14:59 UTC, icewind1991 commented
note that this issue is completely reproducible without the client by moving files from the web ui

2017-06-20 12:35 UTC, bat553 commented
I have not yet been able to apply the fix but I wanted to report that this bug also happened when we create a shared folder.

2017-06-20 14:33 UTC, icewind1991 commented
@LukasReschke added repair step

2017-06-20 16:09 UTC, LukasReschke commented
@nickvergessen Can you review the repair step? THX!

2017-06-20 17:19 UTC, nickvergessen commented
@icewind1991 please write a unit test for the repair step.
Should be fairly easy?!

2017-06-21 13:52 UTC, icewind1991 commented
@nickvergessen done

2017-06-21 21:51 UTC, MorrisJobke commented
I updated this here to do:

* move the repair step into a NC13 folder
* add a version number check to only run the repair step once

2017-06-21 21:54 UTC, MorrisJobke approved these changes
Tested and works 👍 (also the repair step properly cleans it up)

2017-06-22 06:45 UTC, LukasReschke commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		if (version_compare($versionFromBeforeUpdate, '13.0.0.1', '<')) {
Can we adjust this to either:

- Use an appconfig value
- Also check for 12.0.1 as we want to backport this one :)

2017-06-22 20:39 UTC, MorrisJobke commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		if (version_compare($versionFromBeforeUpdate, '13.0.0.1', '<')) {
> Use an appconfig value

This needs to be cleaned up later.



> Also check for 12.0.1 as we want to backport this one :)

Okay - if this is 12.0.1 then I will add it as well.

2017-06-24 09:04 UTC, LukasReschke requested changes

2017-06-24 09:04 UTC, LukasReschke commented on tests/lib/Repair/RepairInvalidPathsTest.php
> +use OC\Repair\RepairInvalidPaths;
Test not passing, you moved that file 😉

2017-06-29 08:40 UTC, JiriMON commented
Seems to work ok for moving folders/files out of a cache jail, but still seeing some occurrences of duplicate files as #3502. Tested on 12.0.0.29 - manually backported from changed files.

2017-07-01 09:50 UTC, jospoortvliet commented
Note that it results in lost data :cry: :scream: 
I updated a file on my laptop but it doesn't sync to my desktop, even though both clients claim to be up to date.

2017-07-03 12:25 UTC, icewind1991 commented
@LukasReschke please re-review

2017-07-06 15:59 UTC, daita commented
Tried to reproduce #3502 with linux client (2.3.2beta, build 13) and this branch. No can do. Works fine for me.

2017-07-06 16:31 UTC, MorrisJobke commented
> Tried to reproduce #3502 with linux client (2.3.2beta, build 13) and this branch. No can do. Works fine for me.

Seeing as :+1: -> merging

2017-07-06 16:31 UTC, merged

2017-07-06 16:31 UTC, MorrisJobke commented
@icewind1991 please create the backport PR ;)