[Files external] Add support for 2048 and 4096 bit RSA key generation
nextcloud/server pull request #5556
Opened 2017-06-29 07:43 UTC by rullzer

2017-06-29 22:26 UTC, LukasReschke requested changes

2017-06-29 22:26 UTC, LukasReschke commented on apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
> -		return $rsa->createKey(self::CREATE_KEY_BITS);
I guess we can remove CREATE_KEY_BITS then from the class as it seems unused?

2017-06-30 07:14 UTC, rullzer commented on apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
> -		return $rsa->createKey(self::CREATE_KEY_BITS);
yep

2017-06-30 13:50 UTC, icewind1991 approved these changes
makes sense

2017-07-04 15:37 UTC, MorrisJobke approved these changes

2017-07-04 15:37 UTC, merged