Enhance privacy of contactsmenu fixes #5107
nextcloud/server pull request #5585
Opened 2017-07-02 12:22 UTC by LEDfan

This filter outs all contacts which shouldn't be visible according to the rules in #5107.

2017-07-07 11:33 UTC, ChristophWurst requested changes
Some early feedback. I haven't had a closer look yet, nor did I test this. Will do ASAP.
Thanks!

2017-07-07 11:33 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +	 *  3. if the ``shareapi_only_share_with_group_members config option is
Should be
```
`shareapi_only_share_with_group_members`
```
I guess

2017-07-07 11:33 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$excludedGroups = $this->config->getAppValue('core', 'shareapi_exclude_groups', 'no') === 'yes' ? true : false;
` ? true : false` is not necessary, the `===` check will already result in a boolean value.

2017-07-07 11:33 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$ownGroupsOnly = $this->config->getAppValue('core', 'shareapi_only_share_with_group_members', 'no') === 'yes' ? true : false; // whether to filter out all users which doesn't have the same group as
same as above

2017-08-03 23:24 UTC, rotanid commented
milestone nextcloud 13?? i would definitely call this serious privacy problem a regression that has to be fixed with the next maintenance release.

2017-08-05 07:38 UTC, ChristophWurst submitted a review, later dismissed
Tested and works as expected. Thanks a lot 👍 

I've left some comments regarding coding style.

2017-08-05 07:38 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +	 * @param $entries Entry[]
should be `@param Entry[] $entries`

2017-08-05 07:38 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +	private function filterContacts(IUser $self, Array $entries) {
`array` instead of `Array`

2017-08-05 07:38 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +	 * @return array the filtered contacts
`@return Entry[]`

2017-08-05 07:38 UTC, ChristophWurst commented on lib/private/Contacts/ContactsMenu/ContactsStore.php
> +		$skipLocal = false; // whether to filter out local users
move inline comments to a new line please

2017-08-05 07:38 UTC, ChristophWurst commented on tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php
> +		$this->config->expects($this->at(0)) ->method('getAppValue')
great to have this tested 👍

2017-08-05 14:19 UTC, LEDfan commented
@ChristophWurst I addressed your issues, thanks for testing.

@rotanid I do agree with you.
@karlitschek should this be backported to 12?

2017-08-05 20:04 UTC, karlitschek commented
i think this should be backported

2017-08-06 09:50 UTC, LEDfan commented
I just realized that the `ContactsStore` API probably should be public, so apps who interact with the contacts menu knows which contacts are available in the menu. E.g. in the Chat app we want to limit chatting to the users available in the Contacts menu (i.e. filtered by this PR)

An alternative way could be to move the filtering to the `ContactsManager` API.

What do you think?

2017-08-14 09:48 UTC, LEDfan commented
@ChristophWurst I fixed a bug and also updated the findOne method because that wasn't filtered already.

2017-08-31 17:08 UTC, LEDfan commented
@MorrisJobke @LukasReschke @blizzz @rullzer @schiessle @nickvergessen @georgehrke Excuse me for pinging you all 😄 , but can someone please review this? There are many people asking for this.

Also please point out your opinion about https://github.com/nextcloud/server/pull/5585#issuecomment-320496777 and https://github.com/nextcloud/server/issues/5107#issuecomment-322807688

Thanks!

2017-09-15 12:29 UTC, LukasReschke commented
I'll review this and additionally revert https://github.com/nextcloud/server/commit/56a9084dd2f9a5726a74e1e789773558fade8b44 in here and add the handling here itself.

2017-09-15 12:32 UTC, LukasReschke commented
Rebased upon master.

2017-09-15 14:04 UTC, LukasReschke commented
I added https://github.com/nextcloud/server/compare/5896176d69...705432ca6f, in particular:

- Searching for email addresses with `shareapi_allow_share_dialog_user_enumeration` is now possible again as it was in stable11: 

<img width="585" alt="screen shot 2017-09-15 at 16 02 36" src="https://user-images.githubusercontent.com/878997/30485955-55142afa-9a2f-11e7-820d-b8ca324b4229.png">
<img width="761" alt="screen shot 2017-09-15 at 16 02 42" src="https://user-images.githubusercontent.com/878997/30485956-55197744-9a2f-11e7-9e8a-6d9368715495.png">

- The contacts menu in the top right show contacts if a full UID or the full email has been searched for:

<img width="440" alt="screen shot 2017-09-15 at 16 03 41" src="https://user-images.githubusercontent.com/878997/30485993-75622d20-9a2f-11e7-8cf2-310f0a39e5e9.png">
<img width="399" alt="screen shot 2017-09-15 at 16 03 35" src="https://user-images.githubusercontent.com/878997/30485994-75b8eaac-9a2f-11e7-9e2a-8a9be026dd4f.png">

Note that the search is on "UID" and "EMAIL". So "FN" is not searched.

2017-09-15 14:26 UTC, LukasReschke approved these changes
Works 👍

2017-09-15 19:04 UTC, danxuliu approved these changes
CI complains because reverted commit was not signed, but as it is a revert commit it is not a big deal.

Tested and works; code looks good (but, please, next time do not mix code style changes and behaviour changes in the same commit!) 👍

2017-09-16 11:06 UTC, LEDfan commented
@LukasReschke thanks for taking care of this!

> Note that the search is on "UID" and "EMAIL". So "FN" is not searched.

Is there a reason for? E.g. on LDAP you as user would know the FN but not the username?

2017-09-16 11:52 UTC, LukasReschke commented
> Is there a reason for? E.g. on LDAP you as user would know the FN but not the UID?

Mainly because we have a business requirement requiring this behaviour: Filtering via UID / EMAIL should be possible but for whatever reason filtering to FN shouldn't be possible.

cc @oparoz Or would filtering for FN here also be acceptable? Your call 😉

2017-09-18 12:25 UTC, merged

2017-09-18 15:35 UTC, LukasReschke commented
Backport at https://github.com/nextcloud/server/pull/6554