[stable12] Add recovery key on public upload
nextcloud/server pull request #5630
Opened 2017-07-06 09:15 UTC by schiessle

In order to decide if a recovery key needs to be added we always
need to check the files owner settings and not the settings of
the currently logged in user.

backport of https://github.com/nextcloud/server/pull/5629

2017-07-12 10:46 UTC, nickvergessen requested changes
Works

2017-07-12 10:46 UTC, nickvergessen approved these changes

2017-07-14 10:47 UTC, blizzz commented on apps/encryption/lib/Crypto/Encryption.php
> +			$publicKeys = $this->keyManager->addSystemKeys($accessList, $publicKeys, $this->owner);
I assumed it is ensured somehow that ``begin()`` is run first, and this ``$this->owner`` is never ``null``?

2017-07-17 11:05 UTC, schiessle commented on apps/encryption/lib/Crypto/Encryption.php
> +			$publicKeys = $this->keyManager->addSystemKeys($accessList, $publicKeys, $this->owner);
good catch, I will double check

2017-07-17 11:24 UTC, schiessle commented on apps/encryption/lib/Crypto/Encryption.php
> +			$publicKeys = $this->keyManager->addSystemKeys($accessList, $publicKeys, $this->owner);
@blizzz I added a explicit check, can you review it (also the stable11 and master version) Thanks!

2017-07-20 09:01 UTC, blizzz approved these changes
Looks good

2017-07-20 12:27 UTC, merged