add occ app:install command
nextcloud/server pull request #5644
Opened 2017-07-07 06:45 UTC by sualko

fix #1599

This new command downloads the specific app from the app store, but doesn't enable it.

2017-07-07 09:26 UTC, nickvergessen requested changes

2017-07-07 09:26 UTC, nickvergessen commented on core/Command/App/Install.php
> +			$allApps = \OC_App::getAllApps();
Since the apps you want to install are not available locally, you can also not autocomplete them.

I'd just delete the `complete*` methods and the `implements CompletionAwareInterface`

2017-07-07 09:26 UTC, nickvergessen commented
But nice otherwise

2017-07-07 10:38 UTC, juliusknorr submitted a review, later dismissed

2017-07-07 10:38 UTC, juliushaertl commented on core/Command/App/Install.php
> +			$output->writeln('Error: ' . $ex->getMessage());
Should be $e (see line above)

2017-07-07 11:24 UTC, ChristophWurst commented on core/Command/App/Install.php
> +	public function __construct() {
unused and thus can be removed.

2017-07-07 11:24 UTC, ChristophWurst commented on core/Command/App/Install.php
> +			$installer = new Installer(
@nickvergessen do we have DI for commands? I'd prefer injecting an object over building it manually. This approach could fail as soon as the constructor parameters of change. Or maybe we could at least query the class from the DI container and have it constructed automatically.

2017-07-07 11:29 UTC, nickvergessen commented on core/Command/App/Install.php
> +			$installer = new Installer(
We have "semi-injection": https://github.com/nextcloud/server/blob/master/core/register_command.php#L63

So you can build it outside. Not sure if you can do `\OC::$server->query(Installer::class)` there thou.

2017-07-07 11:32 UTC, sualko commented on core/Command/App/Install.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
What's about the copyright header? How should it look like?

2017-07-07 11:39 UTC, nickvergessen commented on core/Command/App/Install.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
If the logic is yours add yourself
If it code from oc leave as is

2017-07-07 11:45 UTC, sualko commented on core/Command/App/Install.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
It's more or less from [app.php#L363](https://github.com/nextcloud/server/blob/60398b919be713ddb1813956061fee638c54317a/lib/private/legacy/app.php#L363), so I leave it for now.

2017-07-07 11:53 UTC, enoch85 commented
Would it be possible to add a switch for enable like `--enable`?

2017-07-07 13:17 UTC, enoch85 commented
Tested and it gives me this:

```
root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ app:install videocalls
An unhandled exception has been thrown:
Error: Class 'OC\Core\Command\Db\Migrations\StatusCommand' not found in /var/www/nextcloud/core/register_command.php:89
Stack trace:
#0 /var/www/nextcloud/lib/private/Console/Application.php(94): require_once()
#1 /var/www/nextcloud/console.php(91): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

2017-07-07 13:34 UTC, enoch85 commented
OK, it works now (just patched the register_command.php instead), but it asks for `app-id` I think it should work with the name as well, not just app-id.

2017-07-07 13:47 UTC, enoch85 commented
:+1: from me.

2017-07-07 13:48 UTC, enoch85 commented
Also, would it be possible to backport to 12?

2017-07-10 08:33 UTC, nickvergessen commented
> Also, would it be possible to backport to 12?

You know we don't backport features ;)

2017-07-10 19:06 UTC, enoch85 commented
> You know we don't backport features ;)

Oh right, don't know why I forgot about that.

2017-07-11 14:58 UTC, sualko commented
> Would it be possible to add a switch for enable like --enable?

I think this would duplicate the code of the `app:enable` command. Anything else to do, or are we able to merge this?

2017-07-13 11:12 UTC, enoch85 commented
@nickvergessen @juliushaertl Does this look OK to you? I tested and it works in current state.

2017-07-13 11:15 UTC, nickvergessen commented
> I think this would duplicate the code of the `app:enable` command. Anything else to do, or are we able to merge this?

I think a simple enable flag (yes|no) would be okay, if you want to enable it for a group the second call is fine I'd say...

2017-07-13 11:15 UTC, nickvergessen approved these changes

2017-07-21 11:12 UTC, rullzer approved these changes
Can probabaly use some polishing later on. But awesome stuff!

2017-07-21 11:34 UTC, enoch85 commented
@juliushaertl And what about you? :)

2017-07-21 20:21 UTC, MorrisJobke commented
There is only one thing missing: the sign-off. See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work how to do it. It's basically one line in the commit message of every commit.

2017-07-21 20:23 UTC, sualko commented
That's right, I only signed-off the first commit. What's the best practice for such an case? Rebase and sign-off, or add sign-off to every commit?

2017-07-21 20:33 UTC, MorrisJobke commented
> That's right, I only signed-off the first commit. What's the best practice for such an case? Rebase and sign-off, or add sign-off to every commit?

Both ways work. Whatever you find more useful. If the commits should stay: sign-off every single one. If they could also be combined and it still makes sense to have all in one commit then do this and sign-off this single commit.

2017-07-21 21:10 UTC, sualko commented
done

2017-07-21 21:12 UTC, enoch85 commented
Yaay! Finally. :D 

No `--enable` trigger though? :/

2017-07-21 21:45 UTC, MorrisJobke commented
Okay - CI still fails, because there is a new class and the autoloader file needs an update: Simply call `bash build/autoloaderchecker.sh` and then add the changes to the commit ;)

2017-07-21 21:45 UTC, MorrisJobke commented
> No --enable trigger though? :/

Step by step. Let's get this in and then look into this.

2017-07-22 09:24 UTC, rullzer commented
> No --enable trigger though? :/

I'd even argue to not add it at all. Command should be simple and clean and we should aim for that and not duplicate stuff.

My feeling is this will be mostly used in scripts. So then it is just an extra line. In all the other cases it is something you do very rarely. So the extra command is fine IMO.

2017-07-22 09:56 UTC, enoch85 commented
> Command should be simple and clean and we should aim for that and not duplicate stuff.

The app command is called `install` while it's really just downloading the app folder. Maybe we should call this command `app:download` instead? ;) What I mean is that `app:install` should also enable the app, else it's not "installed". IMHO.

If it's possible to add it I don't see any reason *not* to. It's not complicating things, it makes it easier. But as @MorrisJobke said, another PR.

2017-07-22 17:54 UTC, sualko commented
Mh, it failed again. Does someone know why?

2017-07-24 13:08 UTC, MorrisJobke commented
> Mh, it failed again. Does someone know why?

Yep - there was a bug in master, which is fixed now. Just rebase your PR and it should work ;)

2017-07-25 08:27 UTC, sualko commented
>  it should work ;)

It doesn't :cry:

2017-07-25 08:39 UTC, MorrisJobke commented
> It doesn't 😢

Because your master is 18 days old 😉 Also update master and then rebase again ;)

2017-07-25 10:17 UTC, MorrisJobke requested changes

2017-07-25 10:17 UTC, MorrisJobke commented on core/Command/App/Install.php
> +		} catch(Exception $e) {
Phan CI job says no:

```
core/Command/App/Install.php:63 PhanUndeclaredClassCatch Catching undeclared class \OC\Core\Command\App\Exception
core/Command/App/Install.php:64 PhanUndeclaredClassMethod Call to method getMessage from undeclared class \OC\Core\Command\App\Exception
```

https://drone.nextcloud.com/nextcloud/server/359/38

2017-07-25 10:17 UTC, MorrisJobke commented on core/Command/App/Install.php
> +		} catch(Exception $e) {
I guess adding a leading `\` fixes it 😉

2017-07-25 17:00 UTC, enoch85 commented
@sualko Stil failing. :/

2017-07-25 18:33 UTC, sualko commented
I know and it gets annoying, because those tests fail with messages like the following:

```
PHP Warning:  Redis::connect(): connect() failed:
```

```
Waiting for Selenium
```

```
Parse error: ./build/.phan/plugins/SqlInjectionCheckerPlugin.php:22
```

```
creating sqlite db
  [OCP\Files\NotFoundException] 
```

Those are not very helpful and for me it looks like there is a more general issue in the test setup, because if you look at the commit history of the master branch there are only :x:.

2017-07-25 18:35 UTC, enoch85 commented
@MorrisJobke Are tests broken?

2017-07-26 07:28 UTC, MorrisJobke commented
> @MorrisJobke Are tests broken?

We are still struggling with the docker setup. Sorry for this. I try to get this resolved as soon as possible.

2017-07-26 11:01 UTC, nickvergessen commented
> bash build/autoloaderchecker.sh
> git add lib/composer/
> git commit
> git push

Still needs this, then more tests should pass ;)

2017-07-26 11:32 UTC, sualko commented
@nickvergessen I did this and some more tests succeeded, but the next test run failed with a message that I should run the command again. To my surprise the command removed the lines again. My conclusion is, that I will wait for Morris ok to rerun those tests.

2017-07-26 12:34 UTC, MorrisJobke commented
As of now it looks like the tests are actually broken. Somehow the class can't be loaded. Could you please run `bash build/autoloaderchecker.sh` and commit the result (it is needed anyways - another test failure will be fixed by this 😉)

2017-07-26 12:38 UTC, sualko commented
There are no changes to commit after running `bash build/autoloaderchecker.sh`. I also rebased with `git rebase -i master` and tried again.

2017-07-26 12:40 UTC, sualko commented
```
$ bash build/autoloaderchecker.sh
Global composer found: checking for update
You are already using composer version 1.4.2 (stable channel).

Regenerating autoloader
Generating optimized autoload files

Autoloader up to date. Carry on
```

2017-07-26 15:11 UTC, MorrisJobke commented
> There are no changes to commit after running bash build/autoloaderchecker.sh. I also rebased with git rebase -i master and tried again.

Okay ... then my diff was out of date, because now the changes to the composer files are shown. Sorry for the hassle then.

And sorry for the CI mess. We are currently recovering from the long backlog.

2017-07-27 12:48 UTC, sualko commented
> Okay ... then my diff was out of date

No, it was my fail. I don't know why, but the namespace was missing. After adding it, the autoloaderchecker did his job.

2017-07-27 13:36 UTC, MorrisJobke commented
Ignore the 3 drone timeouts ... those are due to a bit overload on that system as of now. Should be fixed soon.

2017-07-27 13:36 UTC, merged

2017-07-27 15:32 UTC, enoch85 commented
> MorrisJobke merged commit c7757b0 into master  2 hours ago

Yaay!