[12] fix moving folders out of a cache jail
nextcloud/server pull request #5655
Opened 2017-07-08 11:30 UTC by icewind1991

Backport of https://github.com/nextcloud/server/pull/5424

2017-07-10 07:08 UTC, MorrisJobke approved these changes
Works 👍

2017-07-11 13:55 UTC, LukasReschke commented
Do we have some idea about the performance here if you have like 20 million files in the file cache? What is the execution time here?

If this would take ages we may need to have a repair step if someone enters a folder or so.

2017-07-12 09:47 UTC, rullzer commented
@LukasReschke well it *should* only happen on files that got corrupted. And if you have 20k corrupted files then we still should fix them all... 

From my POV a PR that fixes it properly on update is way better than all kinds of dark magic when entering a folder... because that will basically require extra queries on each access...

2017-07-12 09:48 UTC, rullzer requested changes

2017-07-12 09:48 UTC, rullzer commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		return $query->execute()->fetchAll();
Can't this be way to huge if you have some big corrupted shares for example?

2017-07-12 10:33 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		return $query->execute()->fetchAll();
Agreed, it should be chunked somehow... Otherwise the MySQL server will go away

2017-07-12 10:35 UTC, nickvergessen requested changes

2017-07-12 10:35 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->update('filecache')
Please create this only once and just set the parameters afterwards

2017-07-12 10:35 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->select('fileid')
Please create this only once and just set the parameters afterwards

2017-07-12 10:35 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->update('filecache')
Please create this only once and just set the parameters afterwards

2017-07-12 10:35 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->delete('filecache')
Please create this only once and just set the parameters afterwards

2017-07-12 11:34 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->select('fileid')
While I agree that that would be the best thing to do in theory, it adds to much code complexity for the expected gain in this case.

2017-07-12 11:40 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		return $query->execute()->fetchAll();
switched to a generator that fetches rows seperate

2017-07-12 12:05 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->select('fileid')
How I see it is that we execute this like 100.000 times on our instance. Not sure if that is "negligible"?

2017-07-12 12:09 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		while ($row = $result->fetch()) {
this still selects potentially 100k entries or more in one query and kills the database server.

It's not php having the problem. Please just use a limit and loop this method until the result set is empty....

2017-07-12 13:51 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		while ($row = $result->fetch()) {
fixed

2017-07-12 13:51 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->delete('filecache')
fixed

2017-07-12 13:52 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->update('filecache')
fixed

2017-07-12 13:52 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->update('filecache')
fixed

2017-07-12 13:52 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +		$query = $builder->select('fileid')
fixed

2017-07-13 09:48 UTC, MorrisJobke commented
@icewind1991 Please rebase to fix the autoloader failure.

2017-07-13 12:40 UTC, icewind1991 commented
> @icewind1991 Please rebase to fix the autoloader failure.

Done

2017-07-13 14:02 UTC, rullzer approved these changes
Looks good to me. Lets do this!

2017-07-13 14:35 UTC, merged

2017-07-13 14:39 UTC, MorrisJobke commented
Ported the added fixes to master: #5715