Proof of concept #5593 - inline SVG icon for icon-contacts
nextcloud/server pull request #5682
Opened 2017-07-11 12:18 UTC by pixelipo

I added `core/img/places/contacts.svg` icon inline, replacing CSS implementation as `background-image`

This would solve some weird css class names and allow for a great flexibility with theming icons.

it should work across all supported browsers.

I also noticed that an almost identical icon is used in dropdown settings menu in lib/private/NavigationManager.php#211 - this solution would work there as well, but it would require changing the toggle method.

2017-07-14 08:48 UTC, jancborchardt commented
Couldn't test it yet but I just have one concern: Shouldn't we keep the white fill in the SVG source to make sure the icon is displayed white no matter what? (Then again, all CSS loads together so header background and icon color are there at the same time, so probably a non-issue?)

2017-07-14 11:02 UTC, pixelipo commented
Exactly, shouldn't be an issue.

I'd like to keep black as default because it's a default in SVG and because most of the icons in NC are black by default as well. So you always know that if you need a light version, just use `icon-white`.

2017-07-17 10:03 UTC, jancborchardt commented
Fine by me then :)

2017-07-24 14:14 UTC, MorrisJobke approved these changes
Looks good 👍

2017-07-24 14:23 UTC, pixelipo commented
I just noticed that there was an earlier effort to try optimizing icon delivery: #4059 plus the open issue #1066

This PR is a more direct inlining (HTML instead of CSS). It also gives us much greater flexibility (ability to make svg modifications with css). It might not work for all icons, but it can definitely remove most of the calls

2017-07-24 16:03 UTC, Espina2 requested changes

2017-07-24 16:03 UTC, Espina2 commented on core/templates/layout.user.php
> +						<?php include('core/img/places/contacts.svg'); ?>
This can have errors you should use file_get_contents instead. There are plenty of articles that talk about this.

2017-07-28 12:12 UTC, pixelipo commented
You're right, @Espina2 - I wasn't thinking it through :stuck_out_tongue: 

Fixed now.

2017-07-29 12:33 UTC, Espina2 approved these changes

2017-08-02 16:16 UTC, MorrisJobke commented on core/templates/layout.user.php
> +						<?php echo file_get_contents('core/img/places/contacts.svg'); ?>
@LukasReschke Security problem? Yes or no?

2017-08-02 16:27 UTC, MorrisJobke commented
Rebased to fix failing CI

2017-08-02 18:06 UTC, LukasReschke commented on core/templates/layout.user.php
> +						<?php echo file_get_contents('core/img/places/contacts.svg'); ?>
The include here isn't really optimal, it's not a security issue per se at the moment but depends on the include orders etc.

I'd prefer a proper absolute inclusion: 

```
<?php echo file_get_contents(__DIR__ . '/../img/places/contacts.svg'); ?>
```

2017-08-02 18:49 UTC, merged

2017-08-03 07:23 UTC, pixelipo commented on core/templates/layout.user.php
> +						<?php echo file_get_contents('core/img/places/contacts.svg'); ?>
OK @LukasReschke - I'll update this when I move on to inlining other SVG icons

2017-08-03 15:02 UTC, nickvergessen commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
The icon was used by other apps, such as activity, can we bring this back please?

2017-08-03 15:05 UTC, Ivansss commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
Same with spreed app.

2017-08-03 15:08 UTC, nickvergessen commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
Also the white image is now the dark one. Can we try to avoid such changes?

2017-08-03 15:17 UTC, nickvergessen commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
Also firstrunwizard: https://github.com/nextcloud/firstrunwizard/blob/2fef8d8c08a17f6f1ac7f9cc237cdc575bb7fec4/templates/wizard.php#L51

2017-08-03 15:18 UTC, nickvergessen commented on core/css/icons.scss
> -.icon-contacts {
Also here, css is public api, we can not simply drop them

2017-08-03 15:22 UTC, nickvergessen commented on settings/js/federationsettingsview.js
> +			$icon.removeClass('icon-contacts');
This is not working:

> ![bildschirmfoto vom 2017-08-03 17-20-18](https://user-images.githubusercontent.com/213943/28929411-25eba220-7870-11e7-8f26-76849eca81a1.png)

2017-08-03 15:29 UTC, pixelipo commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
@nickvergessen there is no need for both icons. CSS in this PR already supports both white and black versions (and all colours you can think of, for that matter). That's the whole point of this PR.

This is nothing but a proof of concept. It has the potential of halving the amount of server requests per pageload, immensely simplifying (and enhancing) theming as well as giving designers the whole colour palette to work with. It will also be much easier to maintain icons.

The idea is to migrate **all** the icons to inline and this, of course, is a huge task, bound to bring some issues in the process. If Nextcloud is not up for that, then just revert this PR and no harm done.

On the other hand, I'm up for creating PRs for all affected apps if you want me to. It's up to you guys. cc @MorrisJobke @jancborchardt 

P.S. I need to have a look at this `image_path` method - perhaps a similar one might be created for pasting svg code into templates...

2017-08-03 15:40 UTC, nickvergessen commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
Well the issue is, that we also have mobile clients which get these icon urls delivered via APIs
So yes we need them to continue working ;) and they need to be available as plain icons. Not everything is using CSS and can be inlined ;)

Don't get me wrong, I'm always for lesser requests to the server. But this can also be done without dropping the current css rules and without renaming the existing images  ;)

Just have it additionally specially when its a PoC PR 😉

2017-08-03 16:31 UTC, MorrisJobke commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
What about just adding the icons back to the repo? Then continue to move forward with the CSS approach for the web UI?

2017-08-04 08:41 UTC, pixelipo commented on core/img/places/contacts-dark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewbox="0 0 32 32"><path d="M9.24 6.67c-1.955 0-3.613 1.43-3.613 3.275.014.583.066 1.302.414 2.823v.037l.038.038c.112.32.275.503.49.753
@MorrisJobke not that easy, in this PR I'm still using `icon-contacts` css - but only  because of `[class^='icon-']` declarations.

I think I will just create a new folder **core/svg/**, populate it with inline-svg versions of icons and create a new set of css rules like this `[class^='svg-']`. That will make sure we stay backwards compatible but allow any app or page to convert to the inline-svg solution.

I'm also considering the idea of creating a new PHP method (and maybe a compatible JS function as well) for fetching/injecting SVG by class(file)name. Is there any existing PHP class that could host such a method?

2017-09-28 17:25 UTC, skjnldsv commented
Any news on this?
I'm honestly quite fond of the filter solution. This doesn't require anything from us or devs to update tjeir apps as we can manage this from core.

The only downside is buttons with texts. We'll need to revert the text colour before applying the filter. Otherwise we'll have a reverted text too!

And we already dropped a lot of support for IE11. To be fair, it's not a game breaking change. IE11 users will just have their icons with the wrong colour. Clearly still usable! And we need to realise that our users are not the common global user. I'd like to see some stats, if available, of the browsers share on the nextcloud users. I would be very surprise to see more than 0.1% of IE11. :)

2017-09-29 09:18 UTC, nickvergessen commented
See https://github.com/nextcloud/server/pull/5985 ?!