Removed cast to integer in getSize
nextcloud/server pull request #5744
Opened 2017-07-15 18:20 UTC by 1manprojects

Fixes - Wrong or no sizes of files/folders #5031 for 32-bit systems a direct cast to integer causes problems.

2017-07-16 07:33 UTC, derkostka approved these changes

2017-07-16 07:33 UTC, derkostka commented
Works ! Please consider for 12.0.1 @MorrisJobke 
👍

2017-07-16 08:28 UTC, MorrisJobke commented
Was added in #4001 🙈 

cc @nickvergessen @rullzer @icewind1991

2017-07-17 11:45 UTC, icewind1991 requested changes
If this is causing problems on 32bit systems it should be changed to `0 + ` instead of just removing it

2017-07-17 11:57 UTC, 1manprojects commented
How would a change to 0+ help in this situation. PHP will automacily change a integer value on overflow to a float unless it is casted. Casting the filesize directly to int would always couse problems on certain files if they are large enough.

2017-07-17 12:56 UTC, icewind1991 commented
doing a `0 +` will ensure that the value is cast to a numeric value if it is a string (which is, from what I can tell, the reason the cast is there in the first place) without running into int size issues

2017-07-17 13:21 UTC, 1manprojects commented
Thanks for the info , @icewind1991. I changed the commit so it will be cast to a numeric value with 0 +.

2017-07-17 13:21 UTC, icewind1991 approved these changes

2017-07-18 20:34 UTC, rullzer approved these changes

2017-07-18 21:43 UTC, merged

2017-07-18 21:44 UTC, MorrisJobke commented
@1manprojects Could I ask you to open another PR against stable12 for the backport? Thanks

2017-07-18 21:44 UTC, MorrisJobke commented
And congratulations to your first contribution to Nextcloud 🎉

2017-07-23 23:53 UTC, yamlfd commented
Please backport to 12.0.1

2017-07-24 09:14 UTC, 1manprojects commented
Well technically this could also affect 64-bit system if a foldersize of filesize is large then the 64-bit integer range however this is a very large number.

2017-07-24 13:58 UTC, yamlfd commented
I can only say that I have e.g 550 files of 10-20mb each in a folder and the sum counter on upper folder overview is zero. There is no file thst is 2gb or larger in the folder. All files have just max 25mb. In a sum it is nearly 7.2gb in these folders. I also have orher folders with smaller files and less mb and they are also 0mb in nextcloud web interface. I hope i do not need to wait until 13.0 to see this issue resolved.

2017-07-24 17:59 UTC, derkostka commented
It must be a different issue then, you would need billions of files of that size to reach the 64 Bit, today, this is impossible. 

Are you sure that you have a 64 Bit Php installation?

2017-07-24 23:29 UTC, yamlfd commented
Not sure... how can I find out? The OS is 64bit... Debian 9. I suspect every package is x64 that is embedded, but I could be wrong. Let me know how to find out, please.

`System | Linux euve256470 3.16.0-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64
`

2017-07-26 10:39 UTC, nickvergessen commented
Just run:
```
php -r "echo PHP_INT_MAX;"
```
If the result is `9223372036854775807` its 64, if it is `4294967296` you have 32 bits

2017-07-26 18:08 UTC, yamlfd commented
Ok, 64bit php as expected... should I debug something on DB level to help you identify the root cause of the 0 counters? I have made a brand new install with 12.0. No upgrade... I'm have only 1 week expierence with nextcloud itself.

2017-07-28 22:50 UTC, yamlfd commented
I tested `sudo -u www-data php occ files:scan` and now the counters are no longer 0. However this does not explain how this could have happened. I guess I do not need a cron task that runs `files:scan`, isn't it? It should be done automatically on upload... All my files have been uploaded via drag and drop to a brand new v12 installation. And I hope HTTP2 is not a possible reason for this...

2017-07-29 05:32 UTC, derkostka commented
Good. Now you've done several tests. I think if there is a problem then it is not related to this change. Http2 is unrelated, as you expect, and the files scan is not needed to be run within cron.

I'd ask you to open a new ticket and attach a detailed log, if that is possible. Maybe we can find the root cause that way.

2017-07-29 05:41 UTC, derkostka commented
Created a PR (#5925) for 12.0.1, please review. Thanks !