Fix oracle
nextcloud/server pull request #5816
Opened 2017-07-20 18:17 UTC by nickvergessen

* Aliases need to be escaped on oracle
* Oracle does not support `\PDO::FETCH_KEY_PAIR`

Todo:
* Write a executing test for the join stuff

2017-07-20 18:46 UTC, ArtificialOwl submitted a review, later dismissed

2017-07-20 18:48 UTC, daita commented
[![.](https://media.giphy.com/media/iiS84hOJXh1Pq/giphy.gif)]()

2017-07-21 10:37 UTC, icewind1991 requested changes

2017-07-21 10:37 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/QuoteHelper.php
> +				return '`' . $alias . '`.*';
use `quoteAlias` here?

2017-07-21 12:02 UTC, nickvergessen commented
Current status:
```
Tests: 10416, Assertions: 30206, Errors: 10, Failures: 32, Warnings: 4, Skipped: 155.
```

2017-07-21 12:06 UTC, LukasReschke commented
> Tests: 10416, Assertions: 30206, Errors: 10, Failures: 32, Warnings: 4, Skipped: 155.

Do you have a Docker container that we can integrate in CI here? If you give me the Dockerfile I can take care of this.

2017-07-21 12:08 UTC, nickvergessen commented
Yes: https://github.com/nextcloud/server/blob/9a34c5051fca9c4e6f42669a524818efaa1abb81/autotest.sh#L328-L344

Compile the instant client:
https://github.com/nextcloud/travis_ci/pull/3/files#diff-608568045fbb5cacfc717c4a4c65194eR15

Install oci8 from pecl:
```
pecl channel-update pecl.php.net
pecl install oci8
```

2017-07-22 10:48 UTC, nickvergessen commented
@icewind1991 can you have a look at:
```
There were 3 failures:

1) Test\Repair\RepairInvalidPathsTest::testRepairNonDuplicate
Failed asserting that false is true.

/home/nickv/Nextcloud/13/server/tests/lib/Repair/RepairInvalidPathsTest.php:80

2) Test\Repair\RepairInvalidPathsTest::testRepairDuplicate
Failed asserting that true is false.

/home/nickv/Nextcloud/13/server/tests/lib/Repair/RepairInvalidPathsTest.php:112

3) Test\Repair\RepairInvalidPathsTest::testRepairMultipleNonDuplicate
Failed asserting that false is true.

/home/nickv/Nextcloud/13/server/tests/lib/Repair/RepairInvalidPathsTest.php:145
```

The tests are too abstract to see where it fails...

2017-07-24 09:20 UTC, nickvergessen commented on lib/private/DB/QueryBuilder/QuoteHelper.php
> +				return '`' . $alias . '`.*';
Actually quote alias uses this one, so nop...
Maybe just the name is wrong nowerdays, but I dont want to break the public api

2017-07-24 16:11 UTC, nickvergessen commented
okay should be ready now, apart from the invalid paths and https://github.com/nextcloud/server/issues/5862

will have a look tomorrow if I can fix them somehow...

2017-07-25 10:26 UTC, nickvergessen commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +				$builder->expr()->isNotNull('p.name')
I think this will make MySQL and others fail. If so we need to introduce a is(Not)EmptyString method. The problem is that oracle stores empty strings as `null` when the column is nullable...
@icewind1991 can you confirm?

2017-07-25 11:01 UTC, icewind1991 commented on lib/private/Repair/NC13/RepairInvalidPaths.php
> +				$builder->expr()->isNotNull('p.name')
Yes, I guess adding such a method would be the best way to handle that

2017-07-25 13:58 UTC, icewind1991 commented on lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php
> +	public function isNotEmptyString($x) {
`nonEmptyString` sounds better to me

2017-08-02 07:53 UTC, nickvergessen commented
@daita @icewind1991 ready to review again, in case you want to help get this sad story done

2017-08-02 09:40 UTC, daita commented
tested some apps, tested some page, worked. Circles is not working :]

I think we should provide a patch to AMX so they test it on their setup with their apps and see how is it going on.

2017-08-02 14:04 UTC, ArtificialOwl approved these changes

2017-08-02 18:54 UTC, MorrisJobke approved these changes
Code looks good and still works here with MySQL and Sqlite 👍

2017-08-02 18:54 UTC, MorrisJobke commented
CI failure is fixed on master.

2017-08-02 18:54 UTC, merged

2017-08-02 18:55 UTC, MorrisJobke commented
@nickvergessen Backport to stable12 or not?

2017-08-03 12:18 UTC, MorrisJobke commented
> @nickvergessen Backport to stable12 or not?

Just from the chat with @oparoz and @nickvergessen: We should backport ;)

2017-08-03 14:47 UTC, nickvergessen commented
Backport in https://github.com/nextcloud/server/pull/5966

But added 3 tasks which I need to do tomorrow