extend the identity proof manager to allow system wide key pairs
nextcloud/server pull request #5870
Opened 2017-07-25 10:19 UTC by schiessle

extend the identity proof manager to allow system wide key pairs

2017-07-25 15:48 UTC, LukasReschke requested changes
PHPDoc needs a small chance otherwise I think this is okay but would like @rullzer's thoughts as well :)

2017-07-25 15:48 UTC, LukasReschke commented on lib/private/Security/IdentityProof/Manager.php
>  	 * Generate a key for $user
PHPDoc lies now :)

2017-07-25 15:48 UTC, LukasReschke commented on lib/private/Security/IdentityProof/Manager.php
> +	 * get instance wide public and private key
Uppercase the first letter here :)

2017-07-26 10:45 UTC, nickvergessen commented
Looks good otherwise

2017-07-26 11:01 UTC, rullzer commented
So... uhm... on the one hand sure...

So the collision chance is practically zero. I just want to point out that it still could happen. So if anything is encrypted with this and a collision does happen you will be out of luck. (And you'll not even know in the current state).

I don't know what you want to do it with. But if loss of this key due to collision is really an issue. Maybe also hash it?

/me will now go out of paranoid mode

2017-07-26 12:02 UTC, schiessle commented
@rullzer what kind of collision do you mean? That there is a user with the same uid as the instance id? In this case I don't see how a hash would help, there you have the same risk that you have a uid which is the same as the hash of the instance id.

Even if this collision would happen, this would "only" mean that this one user would use the same key as the system. I don't see how this would resolve in data lose.

2017-07-26 12:03 UTC, rullzer commented
Ah fair enough. Ok lets do it then.

2017-07-26 12:13 UTC, schiessle commented
@LukasReschke I updated the documentation

2017-07-27 12:32 UTC, LukasReschke commented
> @rullzer what kind of collision do you mean? That there is a user with the same uid as the instance id? In this case I don't see how a hash would help, there you have the same risk that you have a uid which is the same as the hash of the instance id.

Hash collisions are super unlikely and there is no known hash collision for sane hash mechanisms such as SHA-512. (and having a username that is multiple terrabytes or gigabytes long, this won't work with our DB scheme anyways :)) 

As in the future this here, could be extended in a way that a user may be able to export or import their private certificate or such having a collision here would be problematic. Especially as the instance id is known to the public and some instances have registrations apps or guest apps etc…

I'd prefer moving the systemkey in another folder thus or add a prefix to user keys starting with `user-` and a prefix to system keys starting with `system-` and as a fallback we read the old files. (or we even add a migration step, which shouldn't be super hurtful as I doubt that there are many instances with many of those keys yet as they are only generated on-demand)

2017-07-27 13:08 UTC, schiessle commented
> Hash collisions are super unlikely and there is no known hash collision for sane hash mechanisms such as SHA-512.

It is not about hash collisions. It is about whether it is more likely that there will be a user with uid === instanceID or uid === hash(instanceId), I think there is no real difference. Both are extreme unlikely but of course could happen.

> I'd prefer moving the systemkey in another folder thus or add a prefix to user keys starting with user- and a prefix to system keys starting with system- and as a fallback we read the old files. 

I think just moving the systemkey to a subfolder wouldn't help much. There you also have the risk of a name collision. I will look into the possibility to add a prefix for each key.

2017-07-27 13:21 UTC, LukasReschke commented
> It is not about hash collisions. It is about whether it is more likely that there will be a user with uid === instanceID or uid === hash(instanceId), I think there is no real difference. Both are extreme unlikely but of course could happen.

1. Have registration app installed
2. Have someone register with the instance id as username

The instance id is publicly known knowledge as it's the cookie name 🙈

2017-07-27 14:54 UTC, schiessle commented
I added now a prefix `user-` and `system-` to avoid name collisions

2017-08-10 19:17 UTC, rullzer approved these changes

2017-08-23 13:42 UTC, schiessle commented
@LukasReschke waiting for your +1 😉

2017-08-24 16:35 UTC, LukasReschke approved these changes

2017-08-24 16:36 UTC, merged