Fix preview of theming
nextcloud/server pull request #5981
Opened 2017-08-04 13:05 UTC by danxuliu

Pull request #5429 made cached SCSS files depend on a hash of the base URL, so the _/css/core/server.css_ file does no longer exist; as the file can not be loaded the _"Loading preview"_ message is never removed and the _"Saved"_ message is never shown.

As it now depends on the hash of the base URL the file to be reloaded can no longer be hardcoded, so the DataResponse from the controller now provides the full URL to the _server.css_ file that has to be reloaded (if any).

Fixes #5975

Acceptance tests for the preview after setting and resetting the color in the Theming app are also included in this pull request.

2017-08-04 14:37 UTC, danxuliu commented
Oops, I had forgotten to add the acceptance tests for the Theming app to Drone; it is fixed now.

2017-08-04 21:34 UTC, MorrisJobke commented
You are awesome!!!! 🚀 😍

Thanks again for helping that much 👍

2017-08-04 21:41 UTC, MorrisJobke requested changes

2017-08-04 21:41 UTC, MorrisJobke commented on apps/theming/js/settings-admin.js
> +			serverCssUrl = '/' + serverCssUrl;
This doesn't work for instances that are in a subfolder. It needs to be the full URL. linkToAbsolute or something like that should exist, which prepends you the webroot.

2017-08-08 08:55 UTC, danxuliu commented on apps/theming/js/settings-admin.js
> +			serverCssUrl = '/' + serverCssUrl;
> This doesn't work for instances that are in a subfolder. It needs to be the full URL.

Totally right; [getCachedSCSS removes the webroot](https://github.com/nextcloud/server/blob/517dfdda0dfe928836e32db2dfffe04545abfe8e/lib/private/Template/SCSSCacher.php#L297).

> linkToAbsolute or something like that should exist, which prepends you the webroot.

I have used `Util::linkTo` instead, as `Util::linkToAbsolute` adds the webroot, but also the protocol and server host.

2017-08-08 09:03 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-08-09 10:14 UTC, nickvergessen approved these changes

2017-08-09 10:15 UTC, nickvergessen commented
Tests fail:
```
There were 8 failures:

1) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheet
```

2017-08-09 10:17 UTC, nickvergessen submitted a review, later dismissed
Tests

2017-08-09 11:48 UTC, MorrisJobke commented
And please rebase on master - we updated the drone config 🙈

2017-08-10 11:14 UTC, danxuliu commented
@nickvergessen 
> Tests fail

:facepalm: Yes, I forgot to check the tests. And not only that, I also used a deprecated method (`OC\Util::linkTo`). Both are fixed now.

@MorrisJobke 
> And please rebase on master - we updated the drone config 🙈

Done.

2017-08-10 11:59 UTC, MorrisJobke commented
> Edit: By the way, I have noticed that the commit order in the GitHub interface is messed up (as it is ordered chronologically instead of parent->child); I can change their timestamp and push again so they are showed in the right order for easier review if you want.

No - just leave it as it is :) That's fine :)

2017-08-10 12:19 UTC, MorrisJobke approved these changes
Tested again and works 👍 Code looks good

2017-08-10 12:22 UTC, rullzer approved these changes

2017-08-10 12:23 UTC, merged

2017-08-10 12:25 UTC, MorrisJobke commented
Huge thanks again @danxuliu for this awesome help here 👍 

Could I ask you to open  the backport to stable12? That would be nice :)

2017-08-10 12:32 UTC, danxuliu commented
> Huge thanks again @danxuliu for this awesome help here 👍

My pleasure :-)

> Could I ask you to open the backport to stable12? That would be nice :)

Here you have (yes, I had it prepared already :-P ): #6067