Enable changing passwords in user_ldap
nextcloud/server pull request #600
Opened 2016-07-27 11:10 UTC by GitHubUser4234

This has been discussed  at #25114 and covers the "Ability to change LDAP password" part that is described there. Password policy related errors should be able to be displayed for both LDAP and AD users. The committed source code is fully functional in this regard. Unit test will be added tomorrow.

2016-07-27 12:28 UTC, schiessle commented
Great stuff! :smiley: 

Can you update the license header of the new files you added to this scheme https://docs.nextcloud.com/server/9/developer_manual/general/codingguidelines.html#license-headers

Thanks!

2016-07-27 13:44 UTC, MorrisJobke commented
Could I ask you to remove the 6 merge commits. Those clutter the history.

A rebase on our master is a lot cleaner (git history wise). That would be awesome :)

2016-07-28 09:36 UTC, andreas-p commented
The setPassword method lacks encryption. In addition, please check if the ldap entry is a sambaSamAccount and change that password accordingly if present.
I don't have the time to provide a PR at the moment, but I could contribute the encryption code that I'm using in a not-yet-and-hopefully-soon-obsolete app.

2016-07-28 10:23 UTC, GitHubUser4234 commented
> The setPassword method lacks encryption. In addition, please check if the ldap entry is a sambaSamAccount and change that password accordingly if present.
> I don't have the time to provide a PR at the moment, but I could contribute the encryption code that I'm using in a not-yet-and-hopefully-soon-obsolete app.

Password hashing/encryption had been considered but won't be in it because

1. it prevents LDAP server password policy enforcement
2. it can actually be done by the LDAP server itself

2016-07-28 10:26 UTC, GitHubUser4234 commented
Alright, unit tests are committed :blush:  , @blizzz would be great if you could have a first look when convenient :sweat_smile:

2016-07-28 11:22 UTC, andreas-p commented
The ldap_mod_replace function will set the password as plaintext by default. AFAIK the ldap passwd verb isn't supported in PHP, so you need to encrypt yourself.

If some ldap installations need plaintext, please make it configurable.

2016-07-28 14:10 UTC, GitHubUser4234 commented
> The ldap_mod_replace function will set the password as plaintext by default. AFAIK the ldap passwd verb isn't supported in PHP, so you need to encrypt yourself.
> 
> If some ldap installations need plaintext, please make it configurable.

Please have a look at the second point

_2. it can actually be done by the LDAP server itself_

This means that the LDAP server can be configured to use password storage schemes like SSHA, CRYPT etc. indepently from the client. Meaning the client sends the plain password and the server handles hashing by its own. Therefore it is generally not required for the client to hash passwords. If you have different requirements, it is suggested you come over to IRC and discuss it before opening a new PR.

2016-07-28 14:32 UTC, LukasReschke commented on apps/user_ldap/lib/User_LDAP.php
> +	 *
Unnecessary newline

2016-07-28 14:32 UTC, LukasReschke commented on apps/user_ldap/lib/User_LDAP.php
> +			\OCP\Util::writeLog('user_ldap',
Use `getLogger` as well?

2016-07-29 07:19 UTC, GitHubUser4234 commented
Thanks @LukasReschke for commenting, applied according.

2016-07-29 08:23 UTC, andreas-p commented
The ldap server can do the password hashing itself if the correct api is used, but only if the server is requested to do so. ldapmodify does NOT trigger this (modifyRequest), you need to use ldappasswd instead (extendedRequest with modifyPasswordOID, implementing RFC3062). You're currently using the wrong ldap call, bypassing the server password procedures.

2016-07-29 09:37 UTC, GitHubUser4234 commented
> The ldap server can do the password hashing itself if the correct api is used, but only if the server is requested to do so. ldapmodify does NOT trigger this (modifyRequest), you need to use ldappasswd instead (extendedRequest with modifyPasswordOID, implementing RFC3062). You're currently using the wrong ldap call, bypassing the server password procedures.

Besides the fact that exops like ldappasswd are not supported by PHP, ldapmodify is the correct way to go. Just a hint for you: google for "ppolicy_hash_cleartext". Btw, this PR has been tested with password hashing enabled on the LDAP server and works as expected.

2016-07-29 09:55 UTC, andreas-p commented
ppolicy is still marked experimental, and certainly only installed on a minority of ldap servers in use. Yes, sadly RFC3062 isn't supported in PHP. For extended password handling on the server side, modify is obviously NOT the recommended way. There's a reason for ldappasswd being a dedicated tool.
You can not seriously require ldap backend administrators to reconfigure the server to have hashed passwords again. Applying the PR as-is would impose negative security implications, silently degrading passwords to plaintext. What about existing OC/NC installations using user_ldap, and now being confronted with unwanted plaintext passwords they can't fix because for whatever reason the backend won't get ppolicy?

2016-07-29 11:20 UTC, GitHubUser4234 commented
> ppolicy is still marked experimental, 
This is not a discussion about ppolicy. This PR neither relies on it nor does it need it. But besides, in older OpenLDAP 2.3 docs it states clearly that ppolicy _"is production quality and considered stable enough for use in production environments"_.

> You can not seriously require ldap backend administrators to reconfigure the server to have hashed passwords again. Applying the PR as-is would impose negative security implications, silently degrading passwords to plaintext. What about existing OC/NC installations using user_ldap, and now being confronted with unwanted plaintext passwords they can't fix because for whatever reason the backend won't get ppolicy?

LDAP passwords have always been plaintext in existing installations. And for the reasons lined out above, there will be no need to hash them.

2016-07-29 12:01 UTC, go2sh commented
> LDAP passwords have always been plaintext in existing installations. And for the reasons lined out above, there will be no need to hash them.

Since when have LDAP passwords been plaintext? A least for the installations I run, they are all hashed. As far as I know Microsoft uses some kind of  encryption/hashes for AD.

2016-07-29 13:18 UTC, andreas-p commented
slapd has password-hash or OlcPasswordHash, but this is effective only if ldap_password is used.

2016-07-29 16:22 UTC, GitHubUser4234 commented
> Since when have LDAP passwords been plaintext? A least for the installations I run, they are all hashed. As far as I know Microsoft uses some kind of encryption/hashes for AD.

The context is about nextCloud which acts as the LDAP client. Existing installations send plaintext passwords to the LDAP server for binding. It is up to the LDAP server to determine how passwords are stored.

2016-07-29 16:34 UTC, andreas-p commented
Binding and storing are non-related. Binding password may be transferred plaintext (hopefully secured by TLS), but advising the server to store plaintext passwords is outdated. Yes, may the server decide how to encrypt, see RFC3062. You are effectively bypassing default encryption mechanisms, so you' re responsible.

2016-07-29 17:02 UTC, GitHubUser4234 commented
> Binding and storing are non-related. 

Exactly, and it should stay like that! If you introduced client side hashing, then the binding would also become effected, as it would have to use the same hashing mechanism.

>  but advising the server to store plaintext passwords is outdated. 

Don't know where you got that advice from, it's surely not recommended.

> Yes, may the server decide how to encrypt, see RFC3062. You are effectively bypassing default encryption mechanisms, so you' re responsible.

Hey, stay cool. Maybe you should educate yourself about why client side hashing is basically senseless, http://security.stackexchange.com/questions/53594/why-is-client-side-hashing-of-a-password-so-uncommon would be start. There are rare cases where it would make sense to hash passwords both at client and server sides, but that is utterly out of scope here.

2016-07-29 18:06 UTC, andreas-p commented
The server will happily bind with the non-encrypted password against any known hashed password. We're talking about STORING an unencrypted password only, which happens by your implementation.

2016-07-30 02:56 UTC, GitHubUser4234 commented
> The server will happily bind with the non-encrypted password against any known hashed password. We're talking about STORING an unencrypted password only, which happens by your implementation.

To repeat it for the third and last time: Not the client determines how passwords are stored, but the server. This PR is based on this assumption. If you have different requirements, then discuss it in IRC and/or try to open a PR by your own.

2016-07-30 09:01 UTC, andreas-p commented
... and you're BYPASSING server side encryption using ldap_modify. Read about ldap_password.

2016-08-10 09:45 UTC, blizzz commented
My late feedback:
* we don't want to do fancy hashing on the client side
* we need work around ldappasswd
* going with ldapmodify for now is all we can do
* [ ] next to the checkbox should be information that the password is sent in plaintext to the ldap server and transport encryption is a must. and also, that the LDAP server should be configured to deal with that.
* [ ] a documentation section shall be added that explains this in details and points to ways to configure popular LDAP servers. And maybe a statement that if this is not feasible, the feature should just not be used.
* or, alternatively, indeed we can offer some hashing options use a select box instead of a checkbox.

2016-08-10 11:10 UTC, andreas-p commented
Not viable to require to reconfigure probably >90% of ldap servers around, especially if it requires a module that says "experimental not for production use" as of openldap 2.4.44

Requiring transport encryption isn't solving anything and is even misleading; this is about STORING unencrypted passwords unintentionally.

Make hash algorithm configurable including PLAINTEXT for those exotic ppolicy users, everything solved. Hashing doesn't really hurt, does it? Apparently even the password attribute name must be configurable, e.g. for ActiveDirectory.

2016-08-10 11:24 UTC, GitHubUser4234 commented
> Not viable to require to reconfigure probably >90% of ldap servers around, 

Proof? 

> especially if it requires a module that says "experimental not for production use" as of openldap 2.4.44

Nonsense, read [http://www.openldap.org/faq/data/cache/1204.html](http://www.openldap.org/faq/data/cache/1204.html) . And again, not a discussion of thirdparty products.

> Requiring transport encryption isn't solving anything and is even misleading; this is about STORING unencrypted passwords unintentionally.

Nope, changing passwords is disabled by default. Enabling it comes with intentions.

> Make hash algorithm configurable including PLAINTEXT for those exotic ppolicy users, everything solved. Hashing doesn't really hurt, does it? Apparently even the password attribute name must be configurable, e.g. for ActiveDirectory.

Feel free to implement it in an enhancing PR.

2016-08-10 12:46 UTC, andreas-p commented
ppolicy isn't active in debian by default, neither in freebsd, and afaics not when installing from sources, so the >90% is just a guess. If offering pwd change via nextcloud, it's only pragmatic to use nextcloud's password policy as well. Installing a server side module (if you can so at at all) to save some 50 lines of code is quite invasive.

Password changing isn't defined in base LDAPV3, intentionally left to the server implementation, so offering password change is 3rd party specific anyway.
I'm not interested in AD, just want to prevent a potentially dangerous "enhancement".

2016-08-10 13:48 UTC, GitHubUser4234 commented
> ppolicy isn't active in debian by default, neither in freebsd, and afaics not when installing from sources, so the >90% is just a guess. 

It comes with OpenLDAP by default and just because it isn't enabled by default, it doesn't say anything about how often it is used. Just don't bend reality in your favor.

> If offering pwd change via nextcloud, it's only pragmatic to use nextcloud's password policy as well. Installing a server side module (if you can so at at all) to save some 50 lines of code is quite invasive.

If you want features meeting your requirements, then open a PR by your own. But don't demand from others to do the work for you. Even when you (quote from above) "don't have the time".

> Password changing isn't defined in base LDAPV3, intentionally left to the server implementation, so offering password change is 3rd party specific anyway.
> I'm not interested in AD, just want to prevent a potentially dangerous "enhancement".

Dangerous is nothing here, except maybe your demanding attitude. Password changing is disabled by default, and a proper documentation will be in place.

2016-08-16 08:59 UTC, GitHubUser4234 commented
@blizzz : 

There is a little hiccup with AD's `unicodePwd `attribute. It is write-only and the previously discussed approach to check for a value of `unicodePwd` to determine AD mode wouldn't work, so there seem to be only 2 options left:

1. Both AD DS and AD LDS have a `userPassword `attribute by default, but while it is set as `unicodePwd `alias by default on AD LDS, this is not the case on AD DS. Require AD users who want to use the changing password feature to configure the `fUserPwdSupport` char of the dSHeuristics with the target to employ `userPassword `as `unicodePwd` alias.
2. Add a checkbox in the user_ldap wizard to indicate AD mode

Personally, I'd say let's go for 1) as it's cleaner and sounds like a reasonable requirement under these circumstances.

Your opinion is highly appreciated, thanks a lot :smiley:

2016-08-18 09:40 UTC, blizzz commented
> Both AD DS and AD LDS have a userPasswordattribute by default, but while it is set as unicodePwdalias by default on AD LDS, this is not the case on AD DS. Require AD users who want to use the changing password feature to configure the fUserPwdSupport char of the dSHeuristics with the target to employ userPasswordas unicodePwd alias.

Well, it could be a possibility to limit that use case.

@karlitschek @oparoz do we know about other use cases where this feature is desired? And what the setups are?

> Add a checkbox in the user_ldap wizard to indicate AD mode

No, no such checkboxes. We shall discover (and reevaluate) capabilities.

> There is a little hiccup with AD's unicodePwdattribute. It is write-only

@GitHubUser4234 did you try to detect it using a presence filter? Whether the ``unicodePwd=*`` against the user record returns a result?

2016-08-18 10:53 UTC, GitHubUser4234 commented
> @GitHubUser4234 did you try to detect it using a presence filter? Whether the unicodePwd=* against the user record returns a result?

Sorry, I don't have an AD installation at hand, but from the official doc at https://msdn.microsoft.com/en-us/library/cc223248.aspx the answer would be:

_The unicodePwd attribute is never returned by an LDAP search._

2016-08-18 17:18 UTC, GitHubUser4234 commented
> >>@GitHubUser4234 did you try to detect it using a presence filter? Whether the unicodePwd=* against the user record returns a result?

>>Sorry, I don't have an AD installation at hand, but from the official doc at https://msdn.microsoft.com/en-us/library/cc223248.aspx the answer would be:

>>_The unicodePwd attribute is never returned by an LDAP search._

>Ok, however it does not includes it's usage in a presence filter, or does it? It's enough to know it is set on a record.

Well, I guess nothing is more definite than trying it out. Do you guys happen to have AD installation where a simple search using the filter could be executed :grinning: ?  Otherwise I would try to quickly install one from scratch on Monday (have a day off tommorrow)

2016-08-19 09:35 UTC, blizzz commented
Not currently, unfortunately, I also need to get one set up.

2016-08-19 10:58 UTC, karlitschek commented
@blizzz This sounds good but I don't have an overview over all the usecases. Maybe @oparoz nows more.

2016-08-22 09:16 UTC, GitHubUser4234 commented
@blizzz : Installed a Windows Server 2012 evaluation today, setup an AD DS instance and created a user "tester". While a search using `givenName=*` returned a result, `unicodePwd=*` unfortunately didn't. I hope the testcases are valid, please tell me otherwise. The finding can be seen from the following screenshots:

Using `givenName=*`:
![image](https://cloud.githubusercontent.com/assets/16538178/17849515/b8d63dfc-688b-11e6-9517-763829d98dea.png)

Using `unicodePwd=*`:
![image](https://cloud.githubusercontent.com/assets/16538178/17849587/155a8506-688c-11e6-85d9-078a6d4e1f26.png)

2016-08-22 10:40 UTC, blizzz commented
@GitHubUser4234 ah, too bad :( could you verify that it is set?

2016-08-22 11:01 UTC, GitHubUser4234 commented
@blizzz : Yep, the password was set during user creation and the user is able to login to Windows using it.

2016-08-23 08:15 UTC, GitHubUser4234 commented
@blizzz :  Ok, so the code and the documentation are ready for review.  For the documentation please see https://github.com/nextcloud/documentation/compare/master...GitHubUser4234:master . Thanks :smiley:

2016-08-23 09:37 UTC, oparoz commented
Good doc, thanks!

2016-08-23 09:49 UTC, andreas-p commented
NOT happy with the documentation. olcPasswordHash does enable password hashing already (unless it is dodged wilfully by not using the recommended tools/protocols to change the password. Main intention of ppolicy is implementing the password policy, not password store encryption).

2016-08-23 10:03 UTC, GitHubUser4234 commented
> NOT happy with the documentation. olcPasswordHash does enable password hashing already (unless it is dodged wilfully by not using the recommended tools/protocols to change the password. Main intention of ppolicy is implementing the password policy, not password store encryption).

Read what has been said above about exops and ldappasswd.

2016-08-23 10:14 UTC, andreas-p commented
exops/ldappasswd not supported in php is a client side problem. Don't make it a server-side problem by requiring ppolicy.

2016-08-30 14:40 UTC, GitHubUser4234 commented
@blizzz : the source code has been rebased and is ready for review, thanks a lot :sweat_smile:

2016-10-10 12:49 UTC, blizzz requested changes
- [ ] Cannot enable the password change feature. The checkmark gets set on the checkbox, but it is never really saved. No save request to the server is sent.

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +			| ((intval($this->access->connection->turnOnPasswordChange) === 1)?(\OC\User\Backend::SET_PASSWORD):0))
while you're at it, could you include \OC\User:Backend in a use statement, and we can replace this just with Backend:: in your change line and the lines before? :)

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +	 * @param \OCA\User_LDAP\Access $access mock
type ``\OCA\User_LDAP\Access|\PHPUnit_Framework_MockObject_MockObject`` makes the IDE happy to work with the test framework's methods.

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +	 * @expectedException OC\HintException
prepend a \ to OC please

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$backend = new UserLDAP($access, $this->getMock('\OCP\IConfig'));
``getMock`` is deprecated, replace with ``createMock``, please. Also, provide the argument as IConfig::class instead of  a plain string. This makes it easier to find usages of that interface, do semi-automated changes, etc.

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$backend = new UserLDAP($access, $this->getMock('\OCP\IConfig'));
see above

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$result = $backend->setPassword('roland', 'dt');
you can omit ``$result`` when it is unused.

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/tests/User_LDAPTest.php
> +	}
It'd also like to see a unit test against a case when setting the password is disabled.

2016-10-10 12:49 UTC, blizzz commented on apps/user_ldap/templates/settings.php
> +				<p><label for="ldap_turn_on_pwd_change"><?php p($l->t('Enable LDAP password changes per user'));?></label><input type="checkbox" id="ldap_turn_on_pwd_change" name="ldap_turn_on_pwd_change" value=
I wonder whether we should have a brief attention message right to the checkbox.  "New password is sent as plain text to LDAP" for instance. What do you think?

2016-10-10 12:58 UTC, blizzz commented
Oh, and please do  a commit with signing off (-s flag in git commit) so that the CI is happy. Needs a rebase, too.

2016-10-11 06:50 UTC, GitHubUser4234 commented
>  Cannot enable the password change feature. The checkmark gets set on the checkbox, but it is never really saved. No save request to the server is sent.

Uhm, could you please try to clear the browser cache (to refresh files like js)? I just retried and it's still working here...otherwise this might require some discussion in IRC to debug further 😜

2016-10-11 06:53 UTC, GitHubUser4234 commented on apps/user_ldap/lib/LDAP.php
> +	public function setPassword($link, $userDN, $password) {
Oh, the method names are related to the native PHP LDAP methods, now that you say it I'm seeing it, too 😆

2016-10-11 07:28 UTC, GitHubUser4234 commented on apps/user_ldap/lib/LDAP.php
> +						throw new HintException(!empty($extended_error)?$extended_error:$errorMsg, '', $errorCode);
Uhm, yes, the intention is to display the error message returned by the password policy module / AD straight to the user. For example it would say

![image](https://cloud.githubusercontent.com/assets/16538178/19262032/51cbd08c-8fc7-11e6-9072-15572ba6d2c2.png)

Maybe this needs further discussion in IRC.

2016-10-11 07:45 UTC, GitHubUser4234 commented on apps/user_ldap/lib/Access.php
> +			return false;
Oh, I just copied that approach from the `readAttribute` method. If I understood correctly, I should instead replace the check with an "allow password changes check".

2016-10-11 07:50 UTC, GitHubUser4234 commented on apps/user_ldap/lib/User_LDAP.php
> +			return false;
Also just copied from the `checkPassword `method 😆  Ok, so if understood correctly, I just removed this check.

2016-10-11 08:47 UTC, GitHubUser4234 commented on apps/user_ldap/lib/User_LDAP.php
> +			return $this->access->setPassword($this->access->username2dn($uid), $password);
Great :)

2016-10-11 08:47 UTC, GitHubUser4234 commented on apps/user_ldap/lib/User_LDAP.php
> +			| ((intval($this->access->connection->turnOnPasswordChange) === 1)?(\OC\User\Backend::SET_PASSWORD):0))
Absolutely!

2016-10-11 09:09 UTC, GitHubUser4234 commented on apps/user_ldap/tests/User_LDAPTest.php
> +	 * @param \OCA\User_LDAP\Access $access mock
Ok~

2016-10-11 09:09 UTC, GitHubUser4234 commented on apps/user_ldap/tests/User_LDAPTest.php
> +	 * @expectedException OC\HintException
Ok~

2016-10-11 09:09 UTC, GitHubUser4234 commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$backend = new UserLDAP($access, $this->getMock('\OCP\IConfig'));
Ok~

2016-10-11 09:09 UTC, GitHubUser4234 commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$result = $backend->setPassword('roland', 'dt');
Ok~

2016-10-11 09:09 UTC, GitHubUser4234 commented on apps/user_ldap/tests/User_LDAPTest.php
> +		$backend = new UserLDAP($access, $this->getMock('\OCP\IConfig'));
Ok~

2016-10-11 10:47 UTC, GitHubUser4234 commented on apps/user_ldap/templates/settings.php
> +				<p><label for="ldap_turn_on_pwd_change"><?php p($l->t('Enable LDAP password changes per user'));?></label><input type="checkbox" id="ldap_turn_on_pwd_change" name="ldap_turn_on_pwd_change" value=
Sure, that's fine.

2016-10-11 10:58 UTC, blizzz commented on apps/user_ldap/lib/Access.php
> +			return false;
Yes

2016-10-11 11:00 UTC, blizzz commented on apps/user_ldap/lib/User_LDAP.php
> +			return false;
Yes. Per se it is correct to catch an Exception at some point, however I think it should not happen in this part. We learned from past the methods returning false or null in error cases are very bad to handle and haunt us at night.

2016-10-11 11:06 UTC, closed without merging

2016-10-12 08:59 UTC, GitHubUser4234 commented on apps/user_ldap/lib/User_LDAP.php
> +			return false;
Hehe, I understand and the icon describes it well 😆

2016-10-12 10:24 UTC, blizzz commented
:information_source:  Continuation on https://github.com/nextcloud/server/pull/1715 for reasons.