Harden count user logic on upgrade
nextcloud/server pull request #6002
Opened 2017-08-07 08:01 UTC by MorrisJobke

In addition to #6001 and #5695

2017-08-07 08:38 UTC, LukasReschke requested changes

2017-08-07 08:38 UTC, LukasReschke commented on lib/base.php
> +					\OC::$server->getLogger()->logException($e, ['level' => \OCP\Util::INFO, 'app' => 'core');
:bomb: :bomb:

ParseError: syntax error, unexpected ')', expecting ']' in /drone/src/github.com/nextcloud/server/pull/6002/lib/base.php:350

2017-08-07 08:56 UTC, LukasReschke approved these changes

2017-08-07 09:11 UTC, nickvergessen commented
I don't get what this is for. `countUsers` only touches the database backends, they should work?
Accounts table is not touched by this...

2017-08-07 09:12 UTC, nickvergessen approved these changes
... but sure, anything is better than an exception

2017-08-07 09:19 UTC, MorrisJobke commented
> I don't get what this is for. countUsers only touches the database backends, they should work?
> Accounts table is not touched by this...

I just want to avoid, that upstream somehow renames this table and then our backend will not be able to count anymore. But we can also not run this code and fix it once it happens. It could also be the case, that a column is renamed or so.

2017-08-08 17:24 UTC, MorrisJobke commented
Makes no sense at all -> closing

2017-08-08 17:24 UTC, closed without merging