Do not log WebDAV maintenance mode exception
nextcloud/server pull request #6132
Opened 2017-08-15 12:48 UTC by MorrisJobke

Log the maintenance mode exception only in debug level. Fixes #6124

How to test:

* enable maintenance mode
* enable log level 0 (debug)
* access webdav (PROPFIND against root for example)
* before: maintenance mode is logged in error log level (4)
* after: maintenance mode is logging in debug level (0)
* additional: update needed should still be logged in error level

2017-08-15 12:48 UTC, MorrisJobke commented
@mwries please test this as well 😉

2017-08-15 12:57 UTC, LukasReschke requested changes

2017-08-15 12:57 UTC, LukasReschke commented on apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
> +			($exceptionClass === 'Sabre\DAV\Exception\ServiceUnavailable' && $ex->getMessage() === 'System in maintenance mode.')) {
I'd prefer a custom exception in `\OCA\DAV\Connector\Sabre\MaintenancePlugin::checkMaintenanceMode` and then match also on `::class`. 

Right now this, for example, doesn't catch the `Upgrade needed`. A custom exception would help here.

2017-08-15 12:57 UTC, LukasReschke commented on apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
> +			[4, 'Upgrade needed', new InvalidPath('Upgrade needed')],
InvalidPath?

2017-08-15 12:57 UTC, MorrisJobke commented on apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
> +			[4, 'Upgrade needed', new InvalidPath('Upgrade needed')],
Ummm sorry -.-

2017-08-15 12:58 UTC, MorrisJobke commented on apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
> +			($exceptionClass === 'Sabre\DAV\Exception\ServiceUnavailable' && $ex->getMessage() === 'System in maintenance mode.')) {
The problem is, that then the webdav response would change

2017-08-15 12:58 UTC, MorrisJobke commented on apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
> +			($exceptionClass === 'Sabre\DAV\Exception\ServiceUnavailable' && $ex->getMessage() === 'System in maintenance mode.')) {
And the "upgrade needed" should also not be catched, because this is more fishy I think and worth to log.

2017-08-15 13:01 UTC, MorrisJobke commented on apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
> +			($exceptionClass === 'Sabre\DAV\Exception\ServiceUnavailable' && $ex->getMessage() === 'System in maintenance mode.')) {
This would change then the response too:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error
	xmlns:d="DAV:"
	xmlns:s="http://sabredav.org/ns">
	<s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
	<s:message>System in maintenance mode.</s:message>
</d:error>
```

2017-08-15 13:39 UTC, LukasReschke approved these changes

2017-08-15 14:17 UTC, nickvergessen approved these changes

2017-08-15 19:26 UTC, merged

2017-10-13 10:34 UTC, nickvergessen commented
Reported again, time to backport?
https://github.com/nextcloud/server/issues/6824

2017-10-23 09:23 UTC, MorrisJobke commented
> Reported again, time to backport?

I'm open for this. Stable12 should be okay.

2017-10-23 09:23 UTC, MorrisJobke commented
Let me do it

2017-10-23 09:41 UTC, MorrisJobke commented
Backport to stable12 in #6908