Downstream 26539 & 28074
nextcloud/server pull request #6149
Opened 2017-08-16 08:55 UTC by MorrisJobke

This is a downstream of https://github.com/owncloud/core/pull/28074 and https://github.com/owncloud/core/pull/26539 to make it easy to test. #26539 is also needed for #6146  (to review: look into both commits separately)

* set up the storage on master (doesn't need to be valid credentials)
* before: broken, because of unknown configuration
* after: working and showing that it is currently not connected - also the admin/user can delete the invalid config

I tested it and it works nicely. 👍

2017-08-16 11:53 UTC, icewind1991 requested changes

2017-08-16 11:53 UTC, icewind1991 commented on apps/files_external/lib/Lib/Storage/InvalidStorage.php
> +class InvalidStorage {
There is an `OC\Files\Storage\FailedStorage` that should probably bne reused instead

2017-08-16 19:47 UTC, MorrisJobke commented on apps/files_external/lib/Lib/Storage/InvalidStorage.php
> +class InvalidStorage {
I rebased this. Sadly I wasn't apply to make this change here happen. @icewind1991 Could you please help me here? Thanks

2017-08-21 08:00 UTC, MorrisJobke commented
I removed the commits regarding the handling of storages and made a separate PR out of it. This is now ready for review.

2017-08-21 08:00 UTC, MorrisJobke commented
Please re-review.

2017-08-21 08:07 UTC, LukasReschke approved these changes

2017-08-21 15:04 UTC, rullzer approved these changes

2017-08-21 20:11 UTC, merged