Add meta information to emails for better customisation
nextcloud/server pull request #6255
Opened 2017-08-24 15:55 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2017-08-26 09:42 UTC, MorrisJobke requested changes

2017-08-26 09:42 UTC, MorrisJobke commented on apps/sharebymail/lib/ShareByMailProvider.php
> +											\DateTime $expiration) {
Should be allowed to be set to `null` otherwise shares without an expiration date will fail with:

```
TypeError: Argument 5 passed to OCA\\ShareByMail\\ShareByMailProvider::sendMailNotification() must be an instance of DateTime, null given, called in apps/sharebymail/lib/ShareByMailProvider.php on line 351 at apps/sharebymail/lib/ShareByMailProvider.php#376
```

2017-08-26 09:47 UTC, MorrisJobke approved these changes

2017-08-26 10:14 UTC, icewind1991 approved these changes

2017-08-26 11:32 UTC, rullzer commented
Failing tests

2017-08-26 12:50 UTC, nickvergessen commented on apps/sharebymail/lib/ShareByMailProvider.php
> +											\DateTime $expiration) {
`\DateTime $expiration = null` is better?

2017-08-26 15:57 UTC, MorrisJobke commented
> Failing tests

Fixed

2017-08-26 16:53 UTC, merged

2017-08-28 15:48 UTC, MorrisJobke commented on apps/sharebymail/lib/ShareByMailProvider.php
> +											\DateTime $expiration) {
Correct 👍