Generate system wide key pair
nextcloud/server pull request #6285
Opened 2017-08-28 12:15 UTC by schiessle

backport of https://github.com/nextcloud/server/pull/5870

cc @LukasReschke @rullzer

2017-08-29 08:06 UTC, rullzer approved these changes

2017-08-29 08:06 UTC, rullzer commented on lib/private/Repair/NC13/RepairIdentityProofKeyFolders.php
> +namespace OC\Repair\NC13;
Kind of a lie ;)

2017-08-29 08:06 UTC, rullzer commented on lib/private/Repair/NC13/RepairIdentityProofKeyFolders.php
> +		if (version_compare($versionFromBeforeUpdate, '13.0.0.1', '<=')) {
:boom:

2017-08-29 08:06 UTC, rullzer requested changes
See above

2017-08-29 08:58 UTC, schiessle commented
good catch @rullzer ! My last commit should fix it. Please have a look. If everything is fine I will also port it back to master.

2017-08-29 13:47 UTC, LukasReschke submitted a review, later dismissed
CI failing: 

```
The autoloader is not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2017-08-30 12:36 UTC, rullzer requested changes

2017-08-30 12:36 UTC, rullzer commented on lib/private/Repair/NC12/RepairIdentityProofKeyFolders.php
> +	private function repair() {
This function seems fine here. But if you backport this the master repair step has to be fixed. Else this will run again on the upgrade to 13. Which is not what you want.

2017-08-30 14:40 UTC, schiessle commented on lib/private/Repair/NC12/RepairIdentityProofKeyFolders.php
> +	private function repair() {
that's exactly what I said here https://github.com/nextcloud/server/pull/6285#issuecomment-325600617 😉 Let's get this in and then I will forward-port the changes to the repair step

2017-08-30 14:46 UTC, rullzer commented on lib/private/Repair/NC12/RepairIdentityProofKeyFolders.php
> +	private function repair() {
Fine then :)

2017-08-30 14:47 UTC, rullzer approved these changes

2017-08-30 18:34 UTC, MorrisJobke commented
Fixed the autoloader

2017-08-30 18:43 UTC, MorrisJobke approved these changes

2017-08-30 19:31 UTC, merged