print generated encryption key passwords directly after generating the keys…
nextcloud/server pull request #6320
Opened 2017-08-31 11:50 UTC by weizenspreu

…so that errors during the encryption do not lead to a potentially massive data loss

2017-09-04 12:25 UTC, MorrisJobke commented
cc @nextcloud/designers

2017-09-06 14:52 UTC, nickvergessen approved these changes

2017-09-06 14:57 UTC, skjnldsv approved these changes

2017-09-06 15:05 UTC, LukasReschke approved these changes

2017-09-06 15:06 UTC, LukasReschke requested changes
```
1) OCA\Encryption\Tests\Crypto\EncryptAllTest::testEncryptAll
922s
121
Expectation failed for method name is equal to <string:encryptAllUsersFiles> when invoked at sequence index 1.
922s
122
Mocked method does not exist.
922s
123
```

Tests failing :)

2017-09-08 09:44 UTC, nickvergessen commented on apps/encryption/tests/Crypto/EncryptAllTest.php
> +                $encryptAll->expects($this->at(1))->method('outputPasswords')->with();
whitespace breakage

2017-09-08 16:48 UTC, MorrisJobke commented
Could I ask you to sign-off the commits: For details see https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

Thanks

2017-09-08 16:51 UTC, MorrisJobke commented
It would also be nice to have only one commit.(squash them into one and then add the sign-off message there)

Regarding the CI timeouts: they are fixed on current master - so a rebase to the current master would be nice as well. Sorry for this mess :/

2017-09-11 11:11 UTC, weizenspreu commented
Proceeds here... https://github.com/nextcloud/server/pull/6448

2017-09-11 11:11 UTC, closed without merging