Resend notification email
nextcloud/server pull request #6322
Opened 2017-08-31 13:32 UTC by MorrisJobke

This is an extract of the PHP backend code for #6276 

I would like to hear your feedback on this. The idea is to have then later an entry in the share list inside of the 3 dots menu that says "resend share notification" and is an way for the sharer to resend the notification. This PR basically is the base for this, to provide the needed API endpoints.

cc @jancborchardt form a UX point of view: does it make sense to introduce such a functionality?

I tested #6276 and it worked fine there. I had a view at the code and it looks fine. 👍

2017-09-04 15:38 UTC, MorrisJobke commented
@nickvergessen @rullzer @danxuliu Please review - I would like to get this ASAP into stable12.

2017-09-05 03:00 UTC, danxuliu requested changes
Only the two last commits (_Add method to send again a mail notification for a share_ and _Add API endpoint to resend an e-mail notification for a share_) should be included; the other four commits are required only to provide extended data about the shares, like the e-mail of the sharee, in the share dropdown. However, if the action to resend the notification is not included in the dropdown those changes are not needed.

Note, however, that whether an e-mail address is set in the user profile or not should be provided by [_formatShare_ in _ShareAPIController_](https://github.com/nextcloud/server/blob/2060ff591bc0ab2a5600d40acc4020849075b2c9/apps/files_sharing/lib/Controller/ShareAPIController.php#L118) in order for the front-end to be able to know whether to show the action to resend e-mail notification or not in the share menu (it should be taken into account in [sharedialogshareelistview.js](https://github.com/nextcloud/server/blob/master/core/js/sharedialogshareelistview.js) and [shareitemmodel.js](https://github.com/nextcloud/server/blob/master/core/js/shareitemmodel.js)), but I would change that in a different pull request, even for the PHP part.

In any case, even if we said _we will add the extended data for the dropdown anyway just in case it is useful in the future_ (personally I would not do that), the [commit _Extend getUsers to return the e-mail addresses if available_](https://github.com/nextcloud/server/pull/6322/commits/fbb931b2dba2904eb4e1398a952bf0ab25316f53) __must be amended__ before merging; in order to make it as flexible as possible I returned the e-mail address for the user if available, but I forgot to take into account the visibility settings set for the e-mail address in the user profile. Therefore, even if the user set the e-mail address as _Private_ and thus only visible to herself her e-mail address would be sent anyway to the sharer (it would not be shown in the UI, but it could be get by checking the HTTP response)! Instead of sending the e-mail address it should be changed to just sending whether the user has an e-mail address set or not (but, again, personally I would drop the first four commits entirely).

2017-09-05 09:51 UTC, jancborchardt commented
I'm unsure if it's necessary from a UX point of view. It makes it seem like notifications could have errors sending … and on the other hand, if the first notification wasnt seen, why would the new one? Would you not then ask the person via a different channel to verify?

2017-09-08 14:18 UTC, nickvergessen commented
This needs fixing after https://github.com/nextcloud/server/pull/6414

So it also injects the language

2017-09-18 10:10 UTC, closed without merging