Refactor webroot detection in resource locator
nextcloud/server pull request #6332
Opened 2017-09-01 09:55 UTC by tux-rampage

The current implementation breaks installations with symlinks to
directories inside the webroot (i.E. apps).

With this change both variants, directory and symlinks) will be detected
correctly.

Fixes: #6028

2017-09-04 15:28 UTC, MorrisJobke commented
One positive feedback already: https://github.com/nextcloud/server/issues/6028#issuecomment-326953110

2017-09-04 15:34 UTC, MorrisJobke requested changes

2017-09-04 15:34 UTC, MorrisJobke commented on lib/private/Template/ResourceLocator.php
> +	{
Please put it on the end of the line before this.

2017-09-04 15:34 UTC, MorrisJobke commented on lib/private/Template/ResourceLocator.php
> +			if ($realpath && ($realpath != $root)) {
Please use `!==`

2017-09-04 16:11 UTC, MorrisJobke approved these changes
Code change makes sense and still works 👍

2017-09-04 16:12 UTC, MorrisJobke commented
> Code change makes sense and still works 👍

Comments from above still apply of course 😉

2017-09-06 15:39 UTC, tux-rampage commented on lib/private/Template/ResourceLocator.php
> +	{
What do you men? Putting the method to the bottom of the class?

2017-09-06 15:42 UTC, tux-rampage commented
Do you want me to push a squashed commit, or will it be OK to simply push the requested changes?

2017-09-06 17:04 UTC, skjnldsv commented on lib/private/Template/ResourceLocator.php
> +	{
He means the bracket on the end of line :)

2017-09-06 17:37 UTC, MorrisJobke commented
> Do you want me to push a squashed commit, or will it be OK to simply push the requested changes?

Squashed would be awesome :)

2017-09-06 19:37 UTC, tux-rampage commented
Added style fixes as requested - squashed commit

2017-09-06 19:45 UTC, skjnldsv approved these changes
Very nice!

2017-09-06 20:51 UTC, merged

2017-09-07 08:46 UTC, leonklingele-work commented on lib/private/Template/CSSResourceLocator.php
> -				$tmpRoot = realpath($root);
This removed var is still used in line 134 which results in error msgs: `Undefined variable: tmpRoot`

2017-09-07 08:48 UTC, skjnldsv commented on lib/private/Template/CSSResourceLocator.php
> -				$tmpRoot = realpath($root);
Nice catch, I ashamed to have missed that! 🙈

2017-09-07 19:40 UTC, tux-rampage commented
True, should I add another PR?

2017-09-07 19:42 UTC, skjnldsv commented
@tux-rampage yes :)