Rename "LDAP" to "LDAP/AD-integration"
nextcloud/server pull request #6356
Opened 2017-09-04 09:57 UTC by MariusBluem

@nextcloud/ldap

Signed-off-by: Marius Blüm <marius@lineone.io>

2017-09-04 10:00 UTC, MorrisJobke requested changes

2017-09-04 10:00 UTC, MorrisJobke commented on apps/user_ldap/templates/settings.php
> +	<h2><?php p($l->t('LDAP/AD-integration')); ?></h2>
remove the dash please

2017-09-04 10:36 UTC, MariusBluem commented on apps/user_ldap/templates/settings.php
> +	<h2><?php p($l->t('LDAP/AD-integration')); ?></h2>
We do it in the same way in the left menu :)

2017-09-04 10:43 UTC, MorrisJobke commented on apps/user_ldap/templates/settings.php
> +	<h2><?php p($l->t('LDAP/AD-integration')); ?></h2>
Then fix it there too I would say 😆

2017-09-04 11:54 UTC, MariusBluem commented on apps/user_ldap/templates/settings.php
> +	<h2><?php p($l->t('LDAP/AD-integration')); ?></h2>
👍

2017-11-27 08:50 UTC, MorrisJobke commented on apps/user_ldap/templates/settings.php
> +	<h2><?php p($l->t('LDAP / AD integration')); ?></h2>
Fixed to be the same everywhere: see https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/apps/user_ldap/lib/Settings/Section.php#L64

2017-11-27 08:50 UTC, MorrisJobke approved these changes

2017-11-27 09:01 UTC, LukasReschke approved these changes

2017-11-27 09:31 UTC, merged