Theming app support for chrome manifest.json file
nextcloud/server pull request #6451
Opened 2017-09-11 13:11 UTC by juliushaertl

This PR will make the manifest.json file from #4091 being themed with the theming app values. It is also added on the login page now. I also moved the decision logic if an image should be overwritten by the theming app out of the URLGenerator, so we don't have more and more if statements in there in case we want to theme more images.

@nextcloud/theming

2017-09-11 15:28 UTC, LukasReschke requested changes

2017-09-11 15:28 UTC, LukasReschke commented on apps/theming/lib/Controller/ThemingController.php
> +			"name" => $this->themingDefaults->getName(),
Single quotes pls :)

2017-09-11 15:51 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			"name" => $this->themingDefaults->getName(),
Sure. Fixed it in the other files as well. :wink:

2017-09-11 19:33 UTC, LukasReschke approved these changes

2017-09-11 20:51 UTC, MorrisJobke approved these changes

2017-09-11 20:52 UTC, MorrisJobke commented
Two tests are failing:

```
1) OCA\Theming\Tests\ThemingDefaultsTest::testReplaceImagePath with data set #2 ('core', 'favicon.ico')
Failed asserting that false matches expected 'themingRoute?v=0'.

/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:630

2) OCA\Theming\Tests\ThemingDefaultsTest::testReplaceImagePath with data set #3 ('core', 'favicon-touch.png')
Failed asserting that false matches expected 'themingRoute?v=0'.

/drone/src/github.com/nextcloud/server/apps/theming/tests/ThemingDefaultsTest.php:630
```

2017-09-11 20:53 UTC, MorrisJobke commented
```
Analysing /drone/src/github.com/nextcloud/server/apps/theming/lib/ThemingDefaults.php
 1 errors
    line  272: OC_App - Static method of private class must not be called
```

2017-09-12 03:19 UTC, skjnldsv approved these changes
Ok here

2017-09-12 03:19 UTC, skjnldsv commented on core/templates/layout.guest.php
> +		<link rel="manifest" href="<?php print_unescaped(image_path('', 'manifest.json')); ?>">
Feels wrong to use a function named 'image_path' for a manifest, but if ti works.. :)
We should consider renaming it though!

2017-09-12 07:08 UTC, juliushaertl commented on core/templates/layout.guest.php
> +		<link rel="manifest" href="<?php print_unescaped(image_path('', 'manifest.json')); ?>">
Yeah, something like resource_path would make more sense indeed. But image_path is already used for the manifest file and also works with the old theme mechanism.

2017-09-12 07:37 UTC, MorrisJobke commented
Still failing

2017-09-12 12:57 UTC, skjnldsv commented on core/templates/layout.guest.php
> +		<link rel="manifest" href="<?php print_unescaped(image_path('', 'manifest.json')); ?>">
That's why I approved anyway! :)

2017-09-12 13:10 UTC, merged