First prototype of animated background and logo on log in
nextcloud/server pull request #6507
Opened 2017-09-14 14:54 UTC by jancborchardt

Now this is only a first prototype to see if this would work. Ever so slightly nice animated background, and animated logo just like on the website. Please review @karlitschek @skjnldsv @MorrisJobke @pixelipo 

Things left to do:
- [ ] Adjust the background image so it’s repeatable (basically cut something off the bottom right and adjust the height so it links)
- [ ] Adjust the size of the logo so it’s not blurry
- [ ] Check all occurences of the logo to make it work there too

2017-10-02 16:38 UTC, karlitschek commented
I like it. Nice subtil animation. Two small issues. The animated logo shows up fine on Chrome but not on Safari. Not sure why. And the animated background picture looks not totally balanced with some empty spots and some totally full spots. 
But in general super awesome!!

2017-10-02 16:39 UTC, karlitschek commented
@jancborchardt

2017-10-24 07:21 UTC, pixelipo commented on core/css/guest.css
> +	-webkit-animation: background-animation 240s linear 0s normal none infinite;
@jancborchardt two issues with this:
1) vendor prefixes should **never** be used in production-level software. They were introduced as means to test work-in-progress CSS specifications.
2) `animation` spec has been finalized and implemented by all web browsers (IE9 and lower don't support it either way), so prefix usage in this case is deprecated

2017-10-24 07:25 UTC, pixelipo commented on core/css/guest.css
> +@-webkit-keyframes background-animation {
Same as above, with that difference that this one is required for Android browser <5

2017-10-24 07:26 UTC, pixelipo commented on core/css/guest.css
> +	-webkit-animation: logo-animation 2s steps(33) forwards;
same as above, @jancborchardt

2017-10-24 10:27 UTC, MorrisJobke commented
Just to let you know: this causes high CPU load in Chrome and Safari for me. And it's not because I use low end hardware (MacBook Pro from Mid 2015 with an i7)

2017-10-24 12:51 UTC, pixelipo requested changes
Please remove vendor prefixes

2017-10-24 13:18 UTC, jancborchardt commented
@MorrisJobke oh, that's a killer. Can you isolate if it's the background movement or the logo animation?

2017-10-24 13:24 UTC, skjnldsv commented
It's definitely the background, I go from 7% to 45% when activated. i5@desktop.

2017-10-24 13:28 UTC, jancborchardt commented
Ouf, ok then we should absolutely not do that, not worth it. I thought CSS animations were supposed to be more performant?

Or does anyone know how we could do it differently.

2017-10-24 13:40 UTC, skjnldsv commented
Seems to be relative to the transition you used: https://stackoverflow.com/a/35908679/3885878
Could you try with an image in a separate div maybe?

2017-10-26 14:04 UTC, jancborchardt commented
@skjnldsv according to that post, with Gecko (Firefox) and Webkit (Safari) the issue would still be there cause it’s quite a long animation. :\

2017-10-26 14:07 UTC, skjnldsv commented
@jancborchardt Anyway, I'm not quite sure an animation like that is really necessary.
Imho, I like the logo identity, but this feels very heavy and I rather have my fixed bg than this. :)

![capture d ecran_2017-10-26_16-07-44](https://user-images.githubusercontent.com/14975046/32057537-d2ebc804-ba67-11e7-9dd6-646ac7fe553f.png)

2017-10-31 12:16 UTC, pixelipo commented
It's a very nice animation, but I think login page should be as lean as possible. I propose we scrap this until better times (faster CSS animations and/or SVG animation)

2017-11-03 11:10 UTC, jancborchardt commented
I separated out the log in logo animation at https://github.com/nextcloud/server/pull/7050 because the background animation is too much performance penalty at little gain. The log in page is not visible for long anyway.

2017-11-03 11:23 UTC, Espina2 commented
You can animate css properties that make the whole layout paint again. When you want to do css animations always use transform properties. They use graphic acceleration, and don't need to apply a paint on every single element.

You can take a look on browser rendering optimization free course by Google.

2017-11-03 11:42 UTC, Espina2 commented
BTW can you please provide a gif or a video in what you did? 

Suggestion: If you want more feedbacks you should always include a before and after of the whole page, if is some interaction include a small video to show what you did. I sometimes have 5/10 minutes to see all the github notifications, Im seeing on my phone and I can go to a local installation switch the branch and take a look. This is very time consuming... So, if we do that, its clearly more easy and straight forward to everyone give feedback.

2017-11-13 15:53 UTC, jancborchardt commented
Continued in https://github.com/nextcloud/server/pull/7050

2017-11-13 15:53 UTC, closed without merging