Allow templating of email subjects
nextcloud/server pull request #6515
Opened 2017-09-15 09:04 UTC by nickvergessen

2017-09-15 14:14 UTC, MorrisJobke requested changes
Unit tests fail

2017-09-18 16:30 UTC, LukasReschke submitted a review, later dismissed
Autoloader is not up-to-date

2017-09-27 11:21 UTC, nickvergessen commented
Rebased, please review

2017-09-27 13:59 UTC, MorrisJobke requested changes

2017-09-27 13:59 UTC, MorrisJobke commented on lib/private/Mail/Mailer.php
> +	 * @param IMessage|Message $message Message to send
`IMessage` is fully enough here.

2017-09-27 13:59 UTC, MorrisJobke commented on lib/public/Mail/IMessage.php
> +	public function setTemplate(IEMailTemplate $emailTemplate);
I would call it `useTemplate()` just to make it more clear why the template is passed in - to use it as base for the subject, html and plain body. And also write this in the description of the interface.

2017-09-27 14:10 UTC, MorrisJobke commented
Beside that it works nice 👍

2017-09-27 14:23 UTC, nickvergessen commented on lib/private/Mail/Mailer.php
> +	 * @param IMessage|Message $message Message to send
No, because we use methods of the non public api in here ;)

2017-09-27 14:24 UTC, nickvergessen commented on lib/public/Mail/IMessage.php
> +	public function setTemplate(IEMailTemplate $emailTemplate);
I thought the same, but it only extracts them once, so when you change them later they are not updated anymore.
But I think set is also misleading there, suggestions welcome

2017-09-27 14:34 UTC, MorrisJobke commented on lib/public/Mail/IMessage.php
> +	public function setTemplate(IEMailTemplate $emailTemplate);
Then still `useTemplate()` makes most sense and is fine - even if it is used only once.

2017-09-28 08:47 UTC, nickvergessen commented on lib/public/Mail/IMessage.php
> +	public function setTemplate(IEMailTemplate $emailTemplate);
Done and rebased

2017-09-28 15:11 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-10-18 13:11 UTC, rullzer approved these changes

2017-10-18 13:41 UTC, merged