Migrate ID columns to bigint
nextcloud/server pull request #6563
Opened 2017-09-19 10:54 UTC by nickvergessen

For better scaling

2017-09-19 11:13 UTC, rullzer approved these changes
Fine by me

2017-09-19 14:57 UTC, LukasReschke submitted a review, later dismissed
Merge conflict

2017-09-19 18:10 UTC, nickvergessen commented
Yeah, as to be expected. I will rebase after #6564

2017-09-20 07:11 UTC, nickvergessen commented
Rebased, ready for review and merge

2017-09-22 07:10 UTC, nickvergessen commented
@LukasReschke please review, so this is available early in dailies and master for testing

2017-09-26 12:13 UTC, MorrisJobke requested changes

2017-09-26 12:13 UTC, MorrisJobke commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
This one is not executed at all. :/

My migrations table for dav looks like this:

```

dav | 1004Date20170825134824
dav | 1004Date20170919104507
dav | 1004Date20170924124212
```

2017-09-26 12:38 UTC, rullzer commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
Ah I bet that is ebcause we merged the other migration to dav.

2017-09-26 13:07 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
Yeah need to rebase and change the timestamp to be newer... 
#JustDevProblems....

Will have a look separate if we can detect not executed migrations and run them individually

2017-09-26 13:36 UTC, MorrisJobke commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
> Will have a look separate if we can detect not executed migrations and run them individually

isn't that the idea of migrations? xD I thought it will just be checked what was already done and what not and then execute all not executed ones.

2017-09-26 13:57 UTC, rullzer commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
No the issue is you need to do it sequentially. So you can't just insert a new one in the middle. Because that could lead to inconsistencies.

2017-09-26 14:10 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
Exactly, I would also only allow this for debug,...

2017-09-26 14:17 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1004Date20170919103422.php
> +class Version1004Date20170919103422 extends BigIntMigration {
Okay actually it should have worked, the problem is another PR bumped the version number for the dav app on master already, therefor no update was done at all.

Fixed it now.

2017-09-27 08:25 UTC, MorrisJobke requested changes

2017-09-27 08:25 UTC, MorrisJobke commented on apps/dav/lib/Migration/Version1004Date20170926103422.php
> +			'calendars' => ['id', 'calendarid'],
```
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'calendarid' on table 'oc_calendars'.
```

2017-09-27 13:20 UTC, nickvergessen commented on apps/dav/lib/Migration/Version1004Date20170926103422.php
> +			'calendars' => ['id', 'calendarid'],
Stupid copy and paste, but I checked the dav tables and it looks good now.

2017-09-27 13:45 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-09-27 13:47 UTC, MorrisJobke commented
I also fixed the autoloader.

2017-09-29 08:55 UTC, nickvergessen commented
What, postgres fails?
```
Error while trying to create admin user: An exception occurred while executing 'ALTER TABLE oc_personal_settings ALTER id TYPE BIGSERIAL':

SQLSTATE[42704]: Undefined object: 7 ERROR: type "bigserial" does not exist
```

2017-09-29 09:11 UTC, nickvergessen commented
Copied https://github.com/owncloud/core/pull/28364

2017-09-29 10:23 UTC, MorrisJobke approved these changes
Still working fine 👍

2017-09-29 10:23 UTC, merged