Check if Section/Settings exist by its id/section
nextcloud/server pull request #6575
Opened 2017-09-19 16:23 UTC by daita

2017-09-19 16:26 UTC, daita commented
First, there is no test unit yet. This is a just an overview of the issue and its fix.

During upgrade, if an app change the classname of a admin-settings page, or an admin-section, we start to have duplicate in the database.

This PR will fix the request that check if a Setting Page or Section already exist by checking its Id or Section, instead of checking on the classname.

2017-09-20 07:23 UTC, nickvergessen commented
The problem is IDs may not be unique.
But I guess this doesn't really matter, since the behaviour is undefined then anyway...

With https://github.com/nextcloud/server/issues/6382 this would be gone too...

2017-09-20 07:26 UTC, nickvergessen requested changes
I would go for the other way and drop the table completly.

2017-09-20 07:26 UTC, nickvergessen commented on lib/private/Settings/Manager.php
> +			$settings->getSection(),
This at least is wrong, there are multiple classes which are added to the same section. So this at least breaks stuff...

2017-09-20 07:51 UTC, daita commented on lib/private/Settings/Manager.php
> +			$settings->getSection(),
Yeah, was also thinking that we could also delete everything related to I'd on upgrade and feed the table again

2017-09-20 08:21 UTC, nickvergessen commented on lib/private/Settings/Manager.php
> +			$settings->getSection(),
Or delete the table, and read the stuff from the filesystem directly, because we read that anyway to check if we need to trigger an update and to load:
* navigation links
* activity stuff
* commands
* migrations
* ....

2017-09-20 08:36 UTC, daita commented on lib/private/Settings/Manager.php
> +			$settings->getSection(),
Seems to be the cleaner way to do this. Rebuild from scratch during upgrade.

2017-11-27 12:43 UTC, MorrisJobke commented
> With #6382 this would be gone too...

Let go for #6382 instead.

2017-11-27 12:43 UTC, closed without merging