Make ContactsStore a public API
nextcloud/server pull request #6637
Opened 2017-09-25 10:57 UTC by LEDfan

This makes the ContactsStore a public API which can be used by apps. As I described here: https://github.com/nextcloud/server/pull/5585#issuecomment-320496777 this is needed for e.g. the Chat app to know which users are allowed to Chat with other users.

2017-09-25 11:35 UTC, ChristophWurst requested changes
Looks good so far, just some minor documentation/code style issues

2017-09-25 11:35 UTC, ChristophWurst commented on lib/public/Contacts/ContactsMenu/IContactsStore.php
> +interface IContactsStore {
missing `@since` annotations on both the interface and its methods

2017-09-25 11:35 UTC, ChristophWurst commented on lib/public/Contacts/ContactsMenu/IContactsStore.php
> +}
new line missing

2017-10-01 07:16 UTC, LEDfan commented
@ChristophWurst done

2017-12-03 15:31 UTC, LEDfan commented
This is still tagged for NC 13, does this mean it will be merged before 13? I forgot about the featue-freeze to bump this in time...
Thanks!

2017-12-08 15:44 UTC, MorrisJobke commented
> This is still tagged for NC 13, does this mean it will be merged before 13? I forgot about the featue-freeze to bump this in time...
> Thanks!

We plan to do the beta2 soon (at least middle of next week, looking at the other open PRs). I would like to have feedback from @rullzer or @ChristophWurst on this one here.

2017-12-08 15:44 UTC, MorrisJobke commented
And please fix the conflicts ;)

2017-12-09 13:09 UTC, LEDfan commented
@MorrisJobke I fixed the conflicts.

2017-12-10 09:24 UTC, MorrisJobke commented
@LEDfan Because you added a new PHP class could you dump the autoloader again:

```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result
```

2017-12-10 10:34 UTC, ChristophWurst requested changes

2017-12-10 10:34 UTC, ChristophWurst commented on lib/private/Server.php
> +		$this->registerService(\OCP\Contacts\ContactsMenu\IContactsStore::class, function(Server $c) {
Register it as alias with `$this->registerAlias(\OCP\Contacts\ContactsMenu\IContactsStore::class, \OC\Contacts\ContactsMenu\ContactsStore);` and the DI container will resolve the constructor args automatically. This also prevents the contacts store being instantiated twice.

2017-12-10 11:00 UTC, LEDfan commented
@MorrisJobke @ChristophWurst thanks, I updated the PR :smile:

2017-12-10 11:11 UTC, ChristophWurst approved these changes
Changes look good

2017-12-11 15:30 UTC, blizzz approved these changes

2017-12-11 15:30 UTC, blizzz commented
more conflicts @LEDfan

2017-12-11 16:20 UTC, MorrisJobke commented
Fixed the conflicts in the server container. Nothing crucial.

2017-12-11 17:17 UTC, MorrisJobke commented
Ah ... and conflicts again in the same file ... let me rebase a last time 🙈

2017-12-11 19:04 UTC, merged