Add api clients for talking to remote clouds
nextcloud/server pull request #6651
Opened 2017-09-26 15:14 UTC by icewind1991

We're getting more and more places where we need to talk to remote nextcloud instances, instead of each app having to figure out the \stuff for themselves, it would be better to have some common stuff in core.

Todo:

- [ ] figure out a proper way how to test this

2017-09-26 15:56 UTC, nickvergessen requested changes

2017-09-26 15:56 UTC, nickvergessen commented on lib/private/Remote/Api/OCS.php
> +		return new User($this->request('get', '/ocs/v1.php/cloud/users/' . $userId));
1. Please use `v2.php`
2. this endpoint only works authenticated?!

2017-09-26 15:56 UTC, nickvergessen commented on lib/private/Remote/Api/OCS.php
> +		return $this->request('get', '/ocs/v1.php/cloud/capabilities');
v2.php

2017-09-26 15:56 UTC, nickvergessen commented on lib/private/Remote/User.php
> +		return $this->data['twitter'];
This is 12+ only and will throw undefined index when being called against 11

2017-09-26 15:56 UTC, nickvergessen commented
Good idea to abstract that away 👍

2017-09-26 15:57 UTC, nickvergessen commented
As for testing, use functional tests and run the same server behind 2 addresses, like its done for the federation tests?

2017-09-27 08:46 UTC, MorrisJobke commented on lib/private/Remote/Api/OCS.php
> +		return new User($this->request('get', '/ocs/v1.php/cloud/users/' . $userId));
It is authenticated: https://github.com/nextcloud/server/pull/6651/files#diff-bd9df1a4708539bdbb70c6ef51d3862dR66

2017-09-27 08:47 UTC, MorrisJobke commented on lib/private/Remote/Credentials.php
> +	public function __construct($user, $password) {
Should then be added to the stack trace cleaner to not leak passwords in the log file.

2017-09-27 10:18 UTC, nickvergessen commented on lib/private/Remote/Api/OCS.php
> +		return new User($this->request('get', '/ocs/v1.php/cloud/users/' . $userId));
Yeah lol, but you need valid credentials of the same or an admin user on the third party instance...
I think this is just an example, but it's a bad one I wouldn't ship.

2017-09-27 11:52 UTC, icewind1991 commented on lib/private/Remote/Api/OCS.php
> +		return new User($this->request('get', '/ocs/v1.php/cloud/users/' . $userId));
> this endpoint only works authenticated

Yes

2017-10-02 15:09 UTC, icewind1991 commented on lib/private/Remote/Credentials.php
> +	public function __construct($user, $password) {
That is for exceptions that are thrown inside the method, since this method won't throw exceptions it's unneeded

2017-10-06 14:00 UTC, icewind1991 commented
Added tests and plugic api,

ready to review @rullzer @nickvergessen

2017-10-18 11:14 UTC, icewind1991 commented
Please review @rullzer @nickvergessen @schiessle

2017-10-18 12:26 UTC, nickvergessen commented
Fine by me, although I would like to not have the interfaces in OCP for now, so we can test them in one release before finalizing them.

👍

2017-10-18 13:15 UTC, icewind1991 commented
They are added to the public api since they will be part of the migration api which needs to be implemented by apps

2017-10-19 09:59 UTC, LukasReschke requested changes

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Api/ApiBase.php
> +				throw new \InvalidArgumentException('Invalid method ' . $method);
Add `@throw` to the PHPDoc

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Api/ApiCollection.php
> +	private $clientService;
Type annotations here would be nice :)

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Api/ApiFactory.php
> +	private $clientService;
Type annotations here would be nice :)

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Instance.php
> +	private $status;
Typehint missing

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Instance.php
> +		$status = $this->cache->get($key);
Can we permanently store the result of this somewhere? Just because otherwise we're prone to downgrade attacks if an adversary blocks the 443 port.

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Instance.php
> +	private function downloadStatus($url) {
PHPDocs would be nice :)

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/InstanceFactory.php
> +	private $clientService;
Typehints would be nice :)

2017-10-19 09:59 UTC, LukasReschke commented on lib/public/Remote/IInstanceFactory.php
> +	 * @param $url
string?

2017-10-19 09:59 UTC, LukasReschke commented on lib/private/Remote/Api/OCS.php
> +		return new User($this->request('get', 'cloud/users/' . $userId));
This seems pretty error-prone, especially since the User class is just accessing the array data. Can we have more issets in the User class and some sanity check on the response?

2017-10-19 13:38 UTC, icewind1991 commented
@LukasReschke all done.

It now separately caches if a remote supports https and refuses to downgrade to http

2017-10-23 08:49 UTC, LukasReschke requested changes

2017-10-23 08:49 UTC, LukasReschke commented on lib/private/Remote/Instance.php
> +				if ($status = $this->cache->get($httpsKey)) {
Please cache in IAppConfig or so 😇

2017-12-08 15:42 UTC, MorrisJobke approved these changes

2017-12-11 14:24 UTC, rullzer approved these changes
Lets get this in!

2017-12-11 14:28 UTC, merged