Respect future dates in time span
nextcloud/server pull request #6735
Opened 2017-10-03 06:11 UTC by dartcafe

Added checks for time/date comparision and return the corresponding strings, whether the checked time is in the future or in the past. Regarding formatDateSpan() and formatTimeSpan(). #6722

2017-10-03 06:14 UTC, dartcafe commented
Maybe there is a better method. How is the translation done? Some terms get translated, some not.

2017-10-04 09:40 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +		    If ($future) {
Please use lowercase `if` everywhere

2017-10-04 09:40 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +		If ($timestamp > $baseTimestamp) {
Use this instead of the if:
`$future = $timestamp > $baseTimestamp;`

2017-10-04 09:41 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +			} else if ($dateInterval->y == 0 && $dateInterval->m == 0) {
indentation was messed up

2017-10-04 16:34 UTC, dartcafe commented
@nickvergessen Thanks for review. I corrected the issues.

2017-10-05 07:55 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
Btw in the meantime we fixed the `t()` method, so it does the `(string) ` on the return, so you don't need to do that anymore.
But I would be fine merging like this.

2017-10-05 07:55 UTC, nickvergessen approved these changes

2017-10-05 08:34 UTC, dartcafe commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
That wasn't my code, so I am afraid, that I do something with consequences, I cannot see before. So I don't want to touch the `(string)` thing, now.  😕

2017-10-05 09:44 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
I added the commit for you :)

2017-10-07 09:29 UTC, dartcafe commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
Just for understanding: What does `return (string) $expression` do, when it can be omitted?

2017-10-09 09:34 UTC, nickvergessen commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
`(string)` makes sure the result is a string, it was not the case until Nextcloud 11 for the `t()` method. But we fixed this now, so there is no need to do this anymore.

2017-10-09 12:21 UTC, dartcafe commented on lib/private/DateTimeFormatter.php
> +				return (string) $l->t('tomorrow');
Ah. Thanks. I could imagine, that this was the goal, but I did not find any documantation about this.

2017-10-12 13:45 UTC, blizzz requested changes
Code is good! 

Just a formality: you need to signoff your commits (-s switch in git commit) to satisfy the tests.

2017-10-13 10:50 UTC, dartcafe commented
@blizzz I generated a gpg key and imported it to my account, but I am working with the github desktop locally and I have no idea, how to sign the commits now.

2017-10-13 22:12 UTC, dartcafe commented
@blizzz  I am getting mad, trying to resign th eold commits. Any hint?

2017-10-15 06:43 UTC, dartcafe commented
I hope, i didn't cause to much trouble. I made a new PR for this change, where I managed to sign off the commit. So I close this one and hope, that #6837 will get merged.

2017-10-15 06:43 UTC, closed without merging