Add Updates section to app management
nextcloud/server pull request #6739
Opened 2017-10-03 13:09 UTC by juliushaertl

Add updates section to the apps management (fixes #838)

![bildschirmfoto vom 2017-10-03 14-33-08](https://user-images.githubusercontent.com/3404133/31126597-8d7022f2-a84c-11e7-8703-fcad426a30e3.png)

2017-10-03 14:25 UTC, skjnldsv requested changes
After an update, the counter is set to -1! :)
Otherwise, great addition! Works nicely! 

![capture d ecran_2017-10-03_16-24-17](https://user-images.githubusercontent.com/14975046/31130350-711183b6-a857-11e7-86f3-4651559f838b.png)

2017-10-03 14:50 UTC, juliushaertl commented
@skjnldsv Thanks. Fixed with the latest commit.

2017-10-03 14:52 UTC, skjnldsv approved these changes

2017-10-03 15:00 UTC, skjnldsv commented
@juliushaertl I think we should hide the section if no updates are available :)

2017-10-03 15:02 UTC, skjnldsv requested changes
Message for no updates available is not good! :)

![capture d ecran_2017-10-03_17-01-33](https://user-images.githubusercontent.com/14975046/31132235-97f3c228-a85c-11e7-8ea4-81bcbdfd79ac.png)

Also, I think we should hide the section if no updates are available :)

2017-10-03 16:16 UTC, juliushaertl commented
@skjnldsv I'd prefer to keep the section even if it is empty. That way users might remember where to check for updates if they come back. 

This is how it looks now, when there are no updates available:
![bildschirmfoto vom 2017-10-03 18-11-56](https://user-images.githubusercontent.com/3404133/31135906-d54f9584-a866-11e7-9fe5-49e16609664b.png)

2017-10-03 17:01 UTC, juliushaertl commented
Hm maybe we should hide it then. There is a background job for fetching updates and I don't think we need an option to manually check. Any thoughts on that @nextcloud/designers

2017-10-04 09:17 UTC, nickvergessen commented on settings/js/apps.js
> +					console.log(updateCategory);
🙈

2017-10-04 09:22 UTC, nickvergessen commented
> Hm maybe we should hide it then.

I agree, hide the section when empty (just like play store and others do it as well)
Makes little sense to have it, when there are no updates pending

2017-10-04 12:26 UTC, juliushaertl commented
@nickvergessen @skjnldsv Fixed. The updates category is now hidden. It will be shown if an update get available while the user is browsing the page.

2017-10-04 12:47 UTC, nickvergessen approved these changes

2017-10-04 13:21 UTC, jancborchardt commented
@juliushaertl Actually, and sorry I only realize this now – with »Show apps with available updates first« #6740 by you this seems to be not necessary anymore. :)

I would prefer if it’s nicely integrated simply by sorting up, and not with the additional view. It’s duplicated otherwie. Sorry for the late realization, but thanks for the two great pull requests! :) What do you think?

2017-10-04 13:35 UTC, skjnldsv commented
@jancborchardt I don't mind the extra section. I find it easier to search what you need. Users can't directly know that the updates are on top of the list, while with the section, there is no confusion possible.

2017-10-04 13:35 UTC, skjnldsv approved these changes

2017-10-04 14:15 UTC, jancborchardt commented
Hm, then maybe we should add a heading, like for the bundles? I really think that we should keep the navigation lean and not list everything possible.

2017-10-04 14:17 UTC, jancborchardt commented
Cause that will make the list clearer in general – also for »Enabled apps« and »Disabled apps«. Because currently they are sorted properly, but don’t have any section separation which would be nice. Then we could also simply cut those sidebar entries out and just have »Your apps«.

2017-10-04 14:19 UTC, skjnldsv commented
Still disagree with that (sorry! 🙈). I dislike having to scroll to search. Restricting views are a big plus on this. I rather click to se that scroll x time to get to the section I need. I have a lot apps installed. :)

2017-10-04 14:19 UTC, juliushaertl commented
> Hm, then maybe we should add a heading, like for the bundles? I really think that we should keep the navigation lean and not list everything possible.

That really depends on how much apps you have installed/enabled. You never realize if you have a long list that you need to scroll down to find disabled apps there. A quick filter in the sidebar gives the user a hint that there is other stuff to look for.

2017-10-04 15:50 UTC, jancborchardt commented
Ok, but for apps with an update I think it's still valid. There will likely never be so many apps at the same time with an update that you need to scroll.

But my feelings on this aren't soo strong that I feel arguing against you more, so ok. ;)

2017-10-10 12:57 UTC, merged

2017-10-24 09:27 UTC, georgehrke commented
This pull-request doesn't seem to introduce an `Update all` button. Is there a dedicated pr or issue for that? :)

2017-10-24 09:43 UTC, juliushaertl commented
> This pull-request doesn't seem to introduce an Update all button. Is there a dedicated pr or issue for that? :)

Not that I'm aware of, but that is a neat idea.

2017-10-24 13:11 UTC, jancborchardt commented
@georgehrke @juliushaertl mind opening a new isue for it? Or is anyone already working on a pull request? :)