Allow multiple settings and sections per app
nextcloud/server pull request #6759
Opened 2017-10-04 14:36 UTC by nickvergessen

Sample https://github.com/nextcloud/spreed/pull/427

2017-10-04 15:33 UTC, Ivansss approved these changes

2017-10-05 08:59 UTC, blizzz requested changes
tests/lib/Settings/ManagerTest.php fails: ``Invalid argument supplied for foreach()``

2017-10-06 09:27 UTC, blizzz approved these changes

2017-10-06 09:28 UTC, blizzz commented
tested and works

2017-10-06 09:29 UTC, merged