Opt out of IMip CalDAV Plugin
nextcloud/server pull request #6811
Opened 2017-10-11 11:15 UTC by georgehrke

2017-10-15 13:52 UTC, georgehrke commented
to test this:
- setup email properly
- make sure option is enabled
- create event (in the future) with attendee
- make sure email was sent
- disable option 
- create event (in the future) with attendee
- make sure email was not sent

2017-10-16 10:09 UTC, nickvergessen commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = (\OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes');
Remove brackets

2017-10-16 10:12 UTC, nickvergessen requested changes

2017-10-16 10:12 UTC, nickvergessen commented on apps/dav/js/settings-admin-caldav.js
> +	var url = OC.generateUrl('/apps/dav/setSendInvitations');
Use `OCP.AppConfig.setValue('dav', 'sendInvitations', ...)`

Then you can drop your controller as well

2017-10-16 10:12 UTC, nickvergessen commented on apps/dav/lib/Server.php
> +		$sendInvitations = (\OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes');
remove brackets

2017-10-16 11:36 UTC, georgehrke commented on apps/dav/js/settings-admin-caldav.js
> +	var url = OC.generateUrl('/apps/dav/setSendInvitations');
Good hint! Will change that accordingly

2017-10-16 11:50 UTC, georgehrke commented
removed brackets and using `OCP.AppConfig` now ✅

2017-10-16 14:51 UTC, nickvergessen approved these changes

2017-10-19 09:23 UTC, nickvergessen requested changes

2017-10-19 09:23 UTC, nickvergessen commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes';
Remove this useless variable and put the code directly into the if?

2017-10-19 09:29 UTC, LukasReschke approved these changes

2017-10-19 09:30 UTC, georgehrke commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes';
wouldn't `if(\OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes') { ...` look really weird?

2017-10-19 09:43 UTC, nickvergessen commented on apps/dav/appinfo/v1/caldav.php
> +$sendInvitations = \OC::$server->getConfig()->getAppValue('dav', 'sendInvitations', 'yes') === 'yes';
well same goes for this assignment ;)

2017-10-19 09:57 UTC, merged

2018-02-18 13:22 UTC, kosli commented
I tested the latest 13.0 release together with thunderbird lightning and even if the sending of the invitations is disabled on the NC side, TB doesn't ask about sending emails. Only if i disable the line with the schedule plugin ($server->addPlugin(new \OCA\DAV\CalDAV\Schedule\Plugin());) then it works as expected -> TB asks if it should send an invitation to the attendees. Can somebody confirm this? (after doing the change in Server.php you need to use the "reset calendar cache" option in TB).