Add attachment support to emails
nextcloud/server pull request #6867
Opened 2017-10-18 13:46 UTC by nickvergessen

For testing, apply the following patch and then share something by mail
```diff
diff --git a/apps/sharebymail/lib/ShareByMailProvider.php b/apps/sharebymail/lib/ShareByMailProvider.php
index f610a1a5fa..7cab340368 100644
--- a/apps/sharebymail/lib/ShareByMailProvider.php
+++ b/apps/sharebymail/lib/ShareByMailProvider.php
@@ -428,6 +428,16 @@ class ShareByMailProvider implements IShareProvider {
                }
 
                $message->useTemplate($emailTemplate);
+               $a = $message->createAttachment();
+               $a->setFilename('abc.txt')
+                       ->setContentType('text/plain')
+                       ->setBody('abcdefghijklmnopqrstuvwxyz');
+               $message->attach($a);
+               $a = $message->createAttachment();
+               $a->setFilename('background.png')
+                       ->setContentType('image/png')
+                       ->setBody(file_get_contents(__DIR__ . '/../../../core/img/background.png'));
+               $message->attach($a);
                $this->mailer->send($message);
        }
 
```

2017-10-18 14:13 UTC, georgehrke commented
Code looks good, can we have a test for `lib/private/Mail/Attachment.php`?

2017-10-19 08:56 UTC, LukasReschke requested changes
> ->setBody(file_get_contents(__DIR__ . '/../../../core/img/background.png'));

Your example seems to say we should also add a wrapper for Swift_Attachment::fromPath() which will also save memory 
🙂

See also https://swiftmailer.symfony.com/docs/messages.html#attaching-dynamic-content

2017-10-19 09:07 UTC, nickvergessen commented
Done

2017-10-19 09:16 UTC, LukasReschke commented on lib/private/Mail/Message.php
> +	 * @param string $contentType
string|null

2017-10-19 09:19 UTC, LukasReschke approved these changes

2017-10-24 07:33 UTC, ChristophWurst commented on lib/private/Mail/Message.php
> +	public function attach(IAttachment $attachment) {
API-ergonomics-wise I'm curious why an attachment has to be added while it's created by a factory method of the message. For convenience, the attachment could be attached right away. Or am I missing a use case where you attache an attachment to another message maybe?

2017-10-24 07:35 UTC, ChristophWurst commented on lib/private/Mail/Message.php
> +	public function attach(IAttachment $attachment) {
Somehow I think that the `createAttachment` method would better fit into the `IMailer` interface https://github.com/nextcloud/server/blob/master/lib/public/Mail/IMailer.php

2017-10-25 07:27 UTC, nickvergessen commented on lib/private/Mail/Message.php
> +	public function attach(IAttachment $attachment) {
Done

2017-10-30 16:59 UTC, rullzer approved these changes
Fine by me. @ChristophWurst you are also fine now?

2017-10-30 17:33 UTC, georgehrke approved these changes

2017-10-30 17:33 UTC, merged