Fix flow
nextcloud/server pull request #6879
Opened 2017-10-19 15:11 UTC by mario

This fixes the new authentication flow as in:

- puts the protocol in the returned server url
- puts the proper path in the returned server url

2017-10-19 15:13 UTC, nickvergessen commented on tests/Core/Controller/ClientFlowLoginControllerTest.php
> +		$expected = new Http\RedirectResponse('nc://login/http://server:example.com&user:MyLoginName&password:MyGeneratedToken');
same here

2017-10-19 15:16 UTC, mario commented
@nickvergessen fixed

2017-10-19 15:16 UTC, mario commented
I tested, it works, but I don't know if tests work xD

2017-10-19 15:17 UTC, nickvergessen requested changes

2017-10-19 15:17 UTC, nickvergessen commented on tests/Core/Controller/ClientFlowLoginControllerTest.php
> +			->willReturn('http://example.com');
this is cheating? make sure it actually calls `getServerProtocol` ?!

2017-10-19 15:18 UTC, mario commented on tests/Core/Controller/ClientFlowLoginControllerTest.php
> +			->willReturn('http://example.com');
Hm actually wouldnt it return example.com? Since it's just getServerHost ... Tests need better thinking xD

2017-10-19 15:29 UTC, mario commented on tests/Core/Controller/ClientFlowLoginControllerTest.php
> +			->willReturn('http://example.com');
Done!

2017-10-19 15:36 UTC, mario commented
Can we get this in 12 as well? It's important ...

2017-10-19 17:06 UTC, mario commented
@nickvergessen all should be fixed.

2017-10-19 18:13 UTC, rullzer commented
Why do we need this?

I think we should only allow the new flow with https.

If that can't be then just first try https and if that fails http.

Also. The user already entered an url with protocol to get to this stage. Can't you just fetch the protocol from the url entered?

2017-10-19 18:26 UTC, mario commented
a) I don't want to guess (possible two network queries instead of one)
b) We could use the initially entered protocol, but I'd still prefer to have it returned (I trust the server more than I do the client)
c) This makes it possible to use subfolders (example.com/nextcloud) whereas it wouldn't work with the original flow

Also, while allowing all this only with HTTPS is a noble idea, reality is different :)

2017-10-23 07:52 UTC, rullzer commented on core/Controller/ClientFlowLoginController.php
> +			$serverPath = $this->request->getServerProtocol() . "://" . $this->request->getServerHost() . substr($this->request->getRequestUri(), 0, strpos($this->request->getRequestUri(), "/index.php"));
This won't work if you have pretty urls. Since then you don't have index.php

2017-10-23 07:55 UTC, mario commented on core/Controller/ClientFlowLoginController.php
> +			$serverPath = $this->request->getServerProtocol() . "://" . $this->request->getServerHost() . substr($this->request->getRequestUri(), 0, strpos($this->request->getRequestUri(), "/index.php"));
Do you have an alternative suggestion? Even on Android for login flow we always use index.php.

2017-10-23 08:10 UTC, mario commented on core/Controller/ClientFlowLoginController.php
> +			$serverPath = $this->request->getServerProtocol() . "://" . $this->request->getServerHost() . substr($this->request->getRequestUri(), 0, strpos($this->request->getRequestUri(), "/index.php"));
Got an idea. Testing.

2017-10-23 08:22 UTC, mario commented on core/Controller/ClientFlowLoginController.php
> +			$serverPath = $this->request->getServerProtocol() . "://" . $this->request->getServerHost() . substr($this->request->getRequestUri(), 0, strpos($this->request->getRequestUri(), "/index.php"));
Added support for pretty urls.

2017-11-01 10:10 UTC, nickvergessen commented on core/Controller/ClientFlowLoginController.php
> +			$serverPostfix = "";
Please use single quotes

2017-11-01 10:10 UTC, nickvergessen commented on core/Controller/ClientFlowLoginController.php
> +			$serverPath = $this->request->getServerProtocol() . "://" . $this->request->getServerHost() . $serverPostfix;
single quotes

2017-11-01 10:10 UTC, nickvergessen commented on core/Controller/ClientFlowLoginController.php
> +				$serverPostfix = substr($this->request->getRequestUri(), 0, strpos($this->request->getRequestUri(), "/index.php"));
same here and below

2017-11-01 10:12 UTC, nickvergessen commented
Should we merge this then? Or does it break existing stuff etc?

2017-11-08 19:48 UTC, mario commented
@nickvergessen updated.

2017-11-08 23:02 UTC, MorrisJobke commented
Conflict :/

2017-11-08 23:28 UTC, closed without merging