Updated OpenGraph title to display folder name
nextcloud/server pull request #6905
Opened 2017-10-22 19:51 UTC by mastix

When sharing a folder via Facebook, WhatsApp & Co (any platform that makes use of OpenGraph) the display title was "Nextcloud - a safe home for all your data" and the description was the actual name of the folder. This should not be the case, so I changed the display title to display the folder name and the description now displays the form OpenGraph title. Google and Dropbox actually work the same way.

It looks much better now. :)

2017-10-23 12:02 UTC, MorrisJobke requested changes
Looks good beside the whitespace changes.

2017-10-23 12:02 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
> +        	\OCP\Util::addHeader('meta', ['property' => "og:image", 'content' => $shareTmpl['previewImage']]);
Looks like you replaced the tabs here with spaces. Could you revert that to tabs please? Then the diff should also look better.

2017-10-23 12:02 UTC, MorrisJobke commented on apps/files_sharing/lib/Controller/ShareController.php
> +
Please also remove this added line. There is already an empty line here.

2017-10-24 06:38 UTC, mastix commented
Ok - lesson learned: Never fix a bug on Github directly. I'll use my IDE and will try it again.

2017-10-24 07:10 UTC, mastix commented
Updated PR.

2017-10-24 23:51 UTC, MorrisJobke approved these changes
Tested and works 👍

2017-10-24 23:53 UTC, MorrisJobke commented
One more thing: all commit need a sign-off message. Check out https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work to know why and how. Best would be to squash the two commits and add this sign-off message.

Thanks

2017-10-25 06:11 UTC, ChristophWurst approved these changes
Makes sense and changes look good

2017-10-25 07:15 UTC, nickvergessen approved these changes

2017-10-25 16:31 UTC, MorrisJobke commented
Let me take care of squashing and all 😉

2017-10-25 16:34 UTC, MorrisJobke commented
Merge as squashed version 30460b52df via 4cb4d03184

2017-10-25 16:34 UTC, closed without merging

2017-10-25 16:35 UTC, MorrisJobke commented
Thanks for your contribution @mastix 👍 🚀 

Maybe you want to look into other small issues - we collect them under the starter issue label: https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+issue%22