Update .htaccess
nextcloud/server pull request #6953
Opened 2017-10-25 09:01 UTC by chriseqipe

Send 401 on OPTIONS / HTTP/1.1 request coming from windows WebDAV service. Redirection as implemented before did not work and did not start the MS WebClient Service.  
This way the WebClient Service on Windows starts automatically on request.

2017-11-27 14:38 UTC, LukasReschke commented
Thanks for your pull request! 🚀 

Can you give us reproduction steps and more information on what issues this fixes? Just so that we can verify this on our own as well :)

2017-11-27 14:38 UTC, LukasReschke requested changes
See comment.

2017-11-29 22:52 UTC, chriseqipe commented
Have a look at this screencast: 
https://www.youtube.com/watch?v=T50ZYrNBaeo
It's the same on nextcloud as on owncloud...

2018-05-23 15:22 UTC, MorrisJobke commented
There is a different approach for this in #9542 - let's continue there. Thanks for your contribution anyways.

2018-05-23 15:22 UTC, closed without merging