Fixed serious grammatical error
nextcloud/server pull request #6963
Opened 2017-10-25 20:20 UTC by LeeConnelly12

Sounds better.

2017-10-25 20:40 UTC, juliusknorr requested changes

2017-10-25 20:40 UTC, juliushaertl commented on README.md
> +Several apps included by default are regular releases such as [firstrunwizard](https://github.com/nextcloud/firstrunwizard) or [gallery](https://github.com/nextcloud/gallery) are missing in `master`
Shouldn't it be: Several apps are included by default in regular app releases ...

2017-10-25 21:27 UTC, LeeConnelly12 commented on README.md
> +Several apps included by default are regular releases such as [firstrunwizard](https://github.com/nextcloud/firstrunwizard) or [gallery](https://github.com/nextcloud/gallery) are missing in `master`
Yeah I agree, sounds better.

2017-11-27 08:27 UTC, MorrisJobke commented on README.md
> +Several apps included by default are regular releases such as [firstrunwizard](https://github.com/nextcloud/firstrunwizard) or [gallery](https://github.com/nextcloud/gallery) are missing in `master`
Fixed in #7298

2017-11-27 08:28 UTC, MorrisJobke commented
Closing - see #7298 for this fix.

2017-11-27 08:28 UTC, closed without merging