Improve timepicker design, align to datepicker
nextcloud/server pull request #7054
Opened 2017-11-03 14:04 UTC by jancborchardt

Basically the equivalent of Redesign jQuery UI datepicker #5713 :), also ref "Include a timepicker into server" #6348.

Please review @nextcloud/designers @georgehrke @raimund-schluessler 

I didn’t mess with any layout for now to not make it too big – but ideally we also improve that. This is mainly a quick fix for Nextcloud 13 because the timepicker is one of the only ugly jQuery UI parts left.

You can test in the Calendar app (positioning needs to be fixed there @georgehrke):

Before:
![screenshot from 2017-11-03 15-02-54](https://user-images.githubusercontent.com/925062/32377475-18720cda-c0a8-11e7-82ab-454449909456.png)

After:
![screenshot from 2017-11-03 14-58-00](https://user-images.githubusercontent.com/925062/32377476-1894c54a-c0a8-11e7-9c99-16a8b13853b8.png)

2017-11-03 14:09 UTC, skjnldsv requested changes

2017-11-03 14:09 UTC, skjnldsv commented on core/css/header.scss
> +.ui-timepicker.ui-widget {
We have an issue with this line iirc. This needs to have its own properties I think! :/

2017-11-03 14:09 UTC, skjnldsv commented on core/css/header.scss
> +.ui-timepicker.ui-widget {
Found it: #7007

2017-11-03 14:10 UTC, pixelipo submitted a review, later dismissed
@jancborchardt I think a vertical separator between hours and minutes should be added.

2017-11-03 14:10 UTC, pixelipo commented on core/css/styles.scss
> +.ui-widget.ui-timepicker {
@jancborchardt you don't want to just add classes to exiting datepicker declarations (lines 990-1066)?

2017-11-03 14:10 UTC, pixelipo commented on core/css/styles.scss
> +	margin-top: 10px !important;
Why is the `!important` required? Is there some CSS downstream affecting this? if so, it should either be moved before styles.scss or declarations in it should be dropped

2017-11-03 14:11 UTC, pixelipo commented on core/css/header.scss
> +.ui-timepicker.ui-widget {
@skjnldsv I still don't understand what's the issue there.

2017-11-03 14:12 UTC, jancborchardt commented on core/css/styles.scss
> +	margin-top: 10px !important;
Because in the header.scss we need to call it via this, to apply the popover styles:
```
 #navigation,
.ui-datepicker,
.ui-timepicker.ui-widget
```
Cause .ui-timepicker on its own is actually used inside the widget again (for the hours block and minutes block). And then we need to use the same identifier again in the styles.scss.

2017-11-03 14:13 UTC, jancborchardt commented on core/css/styles.scss
> +.ui-widget.ui-timepicker {
The structure is ever so slightly different that copying and adjusting seemed to make more sense. If you see a good way to combine it yes, however I think it’s better to separate it.

2017-11-03 14:14 UTC, jancborchardt commented on core/css/header.scss
> +.ui-timepicker.ui-widget {
Ok, but this is separate from this pull request because it also applies to master. So let’s fix it in a separate PR, ok? :)

2017-11-03 14:15 UTC, jancborchardt commented on core/css/styles.scss
> +	margin-top: 10px !important;
(It’s a bummer, I know, stupid structure they put there. ;) It looks quite funny if we only use .ui-timepicker in the header.scss ;D)

2017-11-03 15:14 UTC, ChristophWurst commented
> @jancborchardt I think a vertical separator between hours and minutes should be added.

Seconded.

2017-11-03 15:25 UTC, raimund-schluessler commented
> @jancborchardt I think a vertical separator between hours and minutes should be added.

I agree. Maybe more whitespace would already be enough to separate it better.

2017-11-03 15:26 UTC, jancborchardt commented
Added the vertical separator, good call:
![screenshot from 2017-11-03 16-25-31](https://user-images.githubusercontent.com/925062/32381742-c1586352-c0b3-11e7-9050-466d0d4eff27.png)
(Also tried it with a bit less height, only between the time selection and not the headings – didn’t look as good.)

2017-11-03 15:27 UTC, jancborchardt commented
Btw, is it possible to cut the leading zeroes off? It looks very strange and unusual, "09" vs simply "9".

2017-11-04 12:23 UTC, skjnldsv commented on core/css/header.scss
> +.ui-timepicker.ui-widget {
Okay! :)

2017-11-04 12:25 UTC, skjnldsv submitted a review, later dismissed
Looks great except a small opacity issue :)

2017-11-04 12:25 UTC, skjnldsv commented on core/css/styles.scss
> +				opacity: .8;
![capture d ecran_2017-11-04_13-22-44](https://user-images.githubusercontent.com/14975046/32405329-886397c8-c163-11e7-8ac3-beb3897fcb44.png)

2017-11-04 20:21 UTC, jancborchardt commented on core/css/styles.scss
> +				opacity: .8;
This is deliberate to separate the "more important" hours from the minutes, in addition to the separation line (it was there before).

2017-11-04 20:22 UTC, skjnldsv commented on core/css/styles.scss
> +				opacity: .8;
The opacity?

2017-11-04 23:23 UTC, jancborchardt commented on core/css/styles.scss
> +				opacity: .8;
Yes, the .8 opacity on the minutes.

2017-11-05 04:02 UTC, skjnldsv commented on core/css/styles.scss
> +				opacity: .8;
It feels strange to have two blue colors then

2017-11-06 04:34 UTC, skjnldsv commented on core/css/header.scss
>  	width: 160px;
Could you also change the line 227 to fit the variable background (I know it's not related, but since we're at it... 😝) 😄
`border-bottom-color: rgba(255, 255, 255, .97);`

2017-11-06 04:38 UTC, skjnldsv commented on core/css/header.scss
>  	width: 160px;
Could you also change the line 227 to fit the variable background (I know it's not related, but since we're at it... 😝) 😄
`border-bottom-color: rgba(255, 255, 255, .97);`

2017-11-06 04:43 UTC, skjnldsv commented
I also change the line 227 to fit the variable background (I know it's not related, but since we're at it... 😝) 😄
border-bottom-color: rgba(255, 255, 255, .97);

https://github.com/nextcloud/server/blob/153415c54b3cc966d32a1934409b87a079d051e7/core/css/header.scss#L227

2017-11-06 11:45 UTC, jancborchardt commented
Fixed, let’s get it in :)

2017-11-06 11:45 UTC, merged