CSSResourceLocator: account for symlinks in app path
nextcloud/server pull request #7061
Opened 2017-11-04 06:50 UTC by kyrofa

Currently, if the app path includes a symlink, the calculated webDir will be incorrect when generating SCSS and CSS will break.

This PR fixes #6028 by using realpath when retrieving app path, which makes these issues go away.

2017-11-04 06:53 UTC, kyrofa commented
I'd love to cover this in a test if anyone can point me in the right direction.

2017-11-07 09:47 UTC, MorrisJobke commented
> I'd love to cover this in a test if anyone can point me in the right direction.

cc @skjnldsv @juliushaertl

2017-11-07 09:47 UTC, MorrisJobke commented
I guess we need the same for the JSCombiner?

2017-11-07 10:05 UTC, skjnldsv commented
Is this related to #5289?

2017-11-07 11:21 UTC, juliushaertl commented
> I'd love to cover this in a test if anyone can point me in the right direction.

I guess you could write a unit test for that with creating a symlink using http://php.net/manual/en/function.symlink.php. It seems that the CSSResourceLocator class is not unit-tested at all: https://github.com/nextcloud/server/tree/master/tests/lib/Template

2017-11-07 18:00 UTC, kyrofa commented
> Is this related to #5289?

I'm not sure. It's certainly possible.

2017-11-07 22:53 UTC, kyrofa commented
@MorrisJobke I'm assuming you're talking about the JSResourceLocator? Assuming so, I've pushed that change here as well.

@juliushaertl I've also pushed tests for both JSResourceLocator as well as CSSResourceLocator that tests the functionality introduced here.

2017-11-08 09:41 UTC, MorrisJobke commented
> @juliushaertl I've also pushed tests for both JSResourceLocator as well as CSSResourceLocator that cover the functionality introduced here. I assume they're run automatically in CI, right? Or do I need to alter another file somewhere?

They run automatically (if they are located in a tests/ folder), but cause a Fatal error: 

```
PHP Fatal error:  Cannot redeclare Test\Template\randomString() (previously declared in /drone/src/github.com/nextcloud/server/tests/lib/Template/CSSResourceLocatorTest.php:47) in /drone/src/github.com/nextcloud/server/tests/lib/Template/JSResourceLocatorTest.php on line 46
```

2017-11-08 21:16 UTC, kyrofa commented
> They run automatically (if they are located in a tests/ folder), but cause a Fatal error:

Thanks @MorrisJobke, all fixed up and ready for review.

2017-11-09 10:01 UTC, juliushaertl commented
@kyrofa Do you have some steps to reproduce the issue/test the pr? Symlinking the apps folder doesn't cause the issue on my setup.

2017-11-09 23:15 UTC, kyrofa commented
Sure thing @juliushaertl. Note that while the fix is done in the ResourceLocators, the bug doesn't bite until CSS is generated (which is then cached). The problem isn't quite as simple as "app paths with symlinks don't work", the app path in question actually needs to be within a webroot that is a symlink, so let's use the default apps as an example.

1. Get a completely clean, not-installed Nextcloud
2. The webroot needs to be a symlink, so instead of `/var/www/nextcloud`, put Nextcloud in `/var/www/actual-nextcloud`.
3. Now create `/var/www/nextcloud` as a symlink pointing to `/var/www/actual-nextcloud` (webserver should be pointing to the symlink).
4. Before installing, add an `apps_paths` item pointing to the default apps, but use the symlink path for it, not the real one, e.g.:
```
<?php
$CONFIG = array (
  'instanceid' => 'oc4ugkbj34v5',
  'apps_paths' => array(
        array(
                # Note the use of nextcloud instead of actual-nextcloud
                'path'=> '/var/www/nextcloud/apps',
                'url' => '/apps',
                'writable' => true,
        ),
  ),
);
```

Now you've set things up such that:

1. The CSS has not yet been generated since Nextcloud is not installed
2. The webroot, which is a symlink, will be resolved into `/var/www/actual-nextcloud`
3. When the CSS is generated, that webroot will be used to rewrite URLs for the apps, but the app path will still be `/var/www/nextcloud/apps/foo` and the rewrite will go sideways, creating invalid URLs to assets, thus bad CSS.

Go ahead and install Nextcloud now, and you'll see things like this:

![image](https://user-images.githubusercontent.com/946674/32634505-decc2138-c560-11e7-80ad-7877f9a60bd1.png)

2017-11-12 14:48 UTC, juliusknorr requested changes

2017-11-12 14:48 UTC, juliushaertl commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Shouldn't we also do this after the check if the app_path is empty like it is done in in the CSSResourceLocator? Otherwise $real_app_path still might be the working directory for empty app paths.

2017-11-12 14:49 UTC, juliusknorr requested changes
Thanks @kyrofa I could reproduce it and your fix works great for that.

2017-11-12 15:49 UTC, kyrofa commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Yeah the diff is hiding that from you, expand is a little below this. It's done [here](https://github.com/nextcloud/server/pull/7061/files#diff-e75d752a35a50ba300698850b35f80efR89).

2017-11-12 16:09 UTC, kyrofa commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Although this will cause weird behavior with using the cwd for l10n, huh. I refactored it just a tad to account for that.

2017-11-13 06:39 UTC, MorrisJobke commented
The failed unit test is unrelated.

2017-11-13 08:03 UTC, juliushaertl commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Can't you just move the check got app_path and app_url in front of the realpath call? That way we don't append any js sources at cwd.

2017-11-13 17:11 UTC, kyrofa commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Not without changing the `l10n` behavior. I don't claim to be an expert in the code, of course, but right now if a `l10n` file doesn't exist, the error is ignored. If we move the check above that logic, we start raising an error instead.

2017-11-14 06:43 UTC, juliusknorr approved these changes

2017-11-14 06:44 UTC, juliushaertl commented on lib/private/Template/JSResourceLocator.php
> +		$real_app_path = realpath($app_path);
Ah, ok, makes sense to keep it like this i guess. 👍

2017-11-14 12:57 UTC, MorrisJobke approved these changes

2017-11-14 12:58 UTC, merged

2017-11-14 15:38 UTC, kyrofa commented
Can we get this back into stable12 as well? It's the last remaining issue for the snap.

2017-11-14 16:43 UTC, MorrisJobke commented
> Can we get this back into stable12 as well? It's the last remaining issue for the snap.

Could you open a backport to the stable12 branch as PR?

2017-11-14 17:36 UTC, kyrofa commented
> Could you open a backport to the stable12 branch as PR?

Sure thing! #7170