Show proper error page even if the config.php has syntax errors
nextcloud/server pull request #7073
Opened 2017-11-06 08:37 UTC by MorrisJobke

* place syntax error in config.php
* open Nextcloud
* before: white page
* after: error page

2017-11-06 08:45 UTC, ChristophWurst requested changes

2017-11-06 08:45 UTC, ChristophWurst commented on index.php
> +		throw $e;
is this really necessary? I guess we can just `exit(1)` here

2017-11-06 09:10 UTC, MorrisJobke commented on index.php
> +		throw $e;
Yes I would leave it in here to log it to the PHP log by the PHP runtime. Otherwise the exception is omitted completely and not easy to find.

2017-11-06 09:33 UTC, ChristophWurst commented on index.php
> +		throw $e;
Right, that makes sense. Thanks for clarifying 😉

2017-11-06 09:34 UTC, ChristophWurst approved these changes

2017-11-07 15:21 UTC, rullzer approved these changes

2017-11-07 15:28 UTC, merged