Use apps versions to generate suffix when possible
nextcloud/server pull request #7244
Opened 2017-11-22 13:00 UTC by skjnldsv

- Reduce the hash to 8 chars (readability) 
- Generate hash based on apps versions if possible and not nextcloud version

2017-11-24 13:23 UTC, MorrisJobke commented
What I did:

* open browser
* noted down the hash of a CSS that was generated from SCSS: `/server/css/files_sharing/d1b66d1f58bf8c563feed8479657874b-mergedAdditionalStyles.css`
* changed the version of files_sharing to `1.5.1` from `1.5.0`
* actual: same hash
* expected: different hash

@skjnldsv What did I wrong?

2017-11-27 15:24 UTC, skjnldsv commented
@MorrisJobke It's the hash after the `.css`
You need to disable the debug mode though.

2017-11-29 13:10 UTC, nickvergessen submitted a review, later dismissed

2017-11-29 13:10 UTC, nickvergessen commented on lib/private/TemplateLayout.php
> +			$appName = end(explode('/', $app));
![bildschirmfoto von 2017-11-29 14-09-54](https://user-images.githubusercontent.com/213943/33376712-0f6558c4-d50f-11e7-8550-64527e24dace.png)

2017-11-29 13:10 UTC, nickvergessen commented on lib/private/TemplateLayout.php
> +	protected function getVersionHashSuffix($app=false) {
Missing spaces around `=`

2017-11-29 13:13 UTC, nickvergessen commented on lib/private/TemplateLayout.php
> +			$appName = end(explode('/', $app));
css-file-suffix-with-apps-versions

2017-12-05 17:12 UTC, skjnldsv commented
All clear! Now we have nice and beautiful version suffixes! :)



```
<link rel="stylesheet" href="/apps/unsplash/css/login.css?v=f63163cd-18">
<link rel="stylesheet" href="/css/core/2933078af7952208ea8b73dc956a6293-share.css?v=190c0a6d-18">
<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=ca9f0d77-18">
<link rel="stylesheet" href="/css/core/2933078af7952208ea8b73dc956a6293-jquery.ocdialog.css?v=190c0a6d-18">
<link rel="stylesheet" href="/css/contacts/2933078af7952208ea8b73dc956a6293-style.css?v=47354877-18">
<link rel="stylesheet" href="/apps2/contacts/css/vendor/ui-select/select.min.css?v=47354877-18">
```

2017-12-06 07:32 UTC, rullzer submitted a review, later dismissed

2017-12-06 07:32 UTC, rullzer commented on lib/private/TemplateLayout.php
> +
Don't lie in your phpdoc :wink: If you say you returning a string do so :P

2017-12-08 15:47 UTC, MorrisJobke commented on lib/private/TemplateLayout.php
> +	static public function getAppNamefromPath($path) {
Is there a reason why this is a static method? I guess the `static` can be dropped here.

2017-12-08 15:47 UTC, MorrisJobke commented
@skjnldsv Could you address the comments? And then this can get in.

2017-12-08 16:43 UTC, skjnldsv commented
@MorrisJobke @rullzer all clear :)

2017-12-11 12:19 UTC, rullzer approved these changes

2017-12-11 12:54 UTC, MorrisJobke requested changes

2017-12-11 12:54 UTC, MorrisJobke commented on lib/private/TemplateLayout.php
> +		return false
Syntax error: `Missing ;` 😉 Let me push a fix for this

2017-12-11 12:55 UTC, MorrisJobke approved these changes
Works with my syntax fix 👍

2017-12-11 12:57 UTC, skjnldsv commented on lib/private/TemplateLayout.php
> +		return false
I was sure I pushed a fix for this! :O

2017-12-11 13:24 UTC, MorrisJobke commented
Rebased to fix the failing integration test, that was fixed on master.

2017-12-11 13:51 UTC, MorrisJobke commented
> Rebased to fix the failing integration test, that was fixed on master.

I was wrong - it was not yet merged to master -> CI looks good so far -> merging.

2017-12-11 13:51 UTC, merged

2017-12-11 13:54 UTC, MorrisJobke commented
Of course I have overlooked one issue in the setup integration tests because of the other one.

```
{"reqId":"KzL6vs3sDWz9myzeplMg","level":3,"time":"2017-12-11T13:53:47+00:00","remoteAddr":"192.168.99.1","user":"--","app":"core","method":"GET","url":"\/server\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':\\n\\nSQLSTATE[HY000]: General error: 10 disk I\\\/O error\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(992): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/DB\\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)\\n#2 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(623): OC\\\\DB\\\\Connection->executeUpdate('PRAGMA read_unc...')\\n#3 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/DB\\\/Connection.php(151): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#4 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#5 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/DB\\\/ConnectionFactory.php(152): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/Server.php(605): OC\\\\DB\\\\ConnectionFactory->getConnection('sqlite', Array)\\n#7 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#8 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(116): Pimple\\\\Container->offsetGet('OCP\\\\\\\\IDBConnecti...')\\n#9 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCP\\\\\\\\IDBConnecti...')\\n#10 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(164): OC\\\\ServerContainer->query('OCP\\\\\\\\IDBConnecti...')\\n#11 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->OC\\\\AppFramework\\\\Utility\\\\{closure}(*** sensitive parameters replaced ***)\\n#12 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(116): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#13 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#14 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/Server.php(1414): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#15 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/Server.php(421): OC\\\\Server->getDatabaseConnection()\\n#16 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#17 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(116): Pimple\\\\Container->offsetGet('OC\\\\\\\\AppConfig')\\n#18 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OC\\\\\\\\AppConfig')\\n#19 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(164): OC\\\\ServerContainer->query('OC\\\\\\\\AppConfig')\\n#20 \\\/srv\\\/projects\\\/server\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->OC\\\\AppFramework\\\\Utility\\\\{closure}(*** sensitive parameters replaced ***)\\n#21 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(116): Pimple\\\\Container->offsetGet('AppConfig')\\n#22 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppConfig')\\n#23 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/Server.php(1336): OC\\\\ServerContainer->query('AppConfig')\\n#24 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/legacy\\\/app.php(961): OC\\\\Server->getAppConfig()\\n#25 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/TemplateLayout.php(206): OC_App::getAppVersions()\\n#26 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/TemplateLayout.php(158): OC\\\\TemplateLayout->getVersionHashSuffix()\\n#27 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/legacy\\\/template.php(207): OC\\\\TemplateLayout->__construct('error', '')\\n#28 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#29 \\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/legacy\\\/template.php(351): OC\\\\Template\\\\Base->printPage()\\n#30 \\\/srv\\\/projects\\\/server\\\/index.php(71): OC_Template::printExceptionErrorPage(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#31 {main}\",\"File\":\"\\\/srv\\\/projects\\\/server\\\/lib\\\/private\\\/DB\\\/Connection.php\",\"Line\":64}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit\/604.3.5 (KHTML, like Gecko) Version\/11.0.1 Safari\/604.3.5","version":""}
```

Let me fix this.

2017-12-11 14:08 UTC, MorrisJobke commented
> Let me fix this.

#7449 <- that then also should be backported together with this PR.

2017-12-11 20:23 UTC, rullzer commented
@skjnldsv please prepare the backport

2018-01-09 14:49 UTC, MorrisJobke commented
@skjnldsv I guess this backport didn't made it yet, right?

2018-01-09 15:09 UTC, skjnldsv commented
Oups, my bad!

2018-01-09 15:11 UTC, MorrisJobke commented
I would like to wait for 12.0.6 for this, is this okay?

2018-01-09 15:13 UTC, skjnldsv commented
Okay for me