Fixed migration type hint
nextcloud/server pull request #7369
Opened 2017-12-03 10:52 UTC by splitt3r

The type hint seems to be wrong. It´s an instance of the Nc SchemaWrapper and not the Doctrine Schema. The SchemaWrapper has some differences and PHP 7 complains about the wrong type once type hint is added.

See: https://github.com/nextcloud/server/blob/master/lib/private/DB/MigrationService.php#L397

2017-12-05 07:18 UTC, rullzer requested changes

2017-12-05 07:18 UTC, rullzer commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
As far as I can see in https://github.com/nextcloud/server/blob/master/lib/private/DB/MigrationService.php#L392-L407 this is actually a Schema

2017-12-05 07:18 UTC, rullzer commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
Same here

2017-12-05 07:59 UTC, splitt3r commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
https://github.com/nextcloud/server/blob/master/lib/private/DB/SchemaWrapper.php but it´s no instance of Schema it only has the same methods. If it was a schema i would have to pass prefix on my own but https://github.com/nextcloud/server/blob/master/lib/private/DB/SchemaWrapper.php#L85 does it. So i think the hint makes a difference.

2017-12-05 08:03 UTC, splitt3r commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
That´s right. Will update it.

2017-12-07 10:46 UTC, splitt3r commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
May be a stupid qustion but why do the pre and post methods get the Schema and the change method get the SchemaWrapper? This way i would need to add Prefix to the table names in the pre and post methods but can directly use the table name without prefix in the change method. Will look quite strange? Are there any reasons for that?

2017-12-12 10:23 UTC, rullzer commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
It is a good question. I don't know. Once @nickvergessen is back maybe he can awnser

2018-01-17 09:15 UTC, nickvergessen commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
I think in the beginning the schema wrapper was only for the delete operations.

Now it also does the auto-prefix etc. so hmm would make sense. But I fear we can't do it anymore since that would break the API, so we now have to make sure that SchemaWrapper implements Schema or we have to introduce new interfaces....
Sad enough Schema is not our class, so we can't add the name-magic in there.

2018-01-17 10:17 UTC, splitt3r commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
But the API isn´t documented public yet? Still no chance to change it?

2018-01-17 10:46 UTC, nickvergessen commented on core/Command/Db/Migrations/GenerateCommand.php
> +	 * @param \Closure $schemaClosure The `\Closure` returns a `SchemaWrapper`
We checked all apps that are in the app store, there are only 2 and I'm the maintainer of both 🎉 
So I fixed all the stuff in a new PR: #7909

2018-01-17 10:56 UTC, closed without merging