Fixes #7158 - Allows adding of hex color to the theme-color
nextcloud/server pull request #7371
Opened 2017-12-03 13:11 UTC by Abijeet

Greetings,

Please find the merge request that fixes #7158

I've done the following,

1. Increased max length to allow for 7 characters.
2. Checking and adding # if not already present on the `change` event.
3. Added `jscolor {hash:true}` class so that user does not enter a 7 character colour by mistake.

---
Abijeet

2017-12-03 14:54 UTC, Abijeet commented
Will check the failed cases.

2017-12-03 17:30 UTC, Abijeet commented
I've fixed the test cases, now it's failing because I forgot to sign off a few commits. I hope that's not an issue for now. I'll be careful in the future.

2017-12-04 21:41 UTC, MorrisJobke commented
cc @nextcloud/theming @nextcloud/javascript

2017-12-05 07:41 UTC, juliusknorr requested changes
Thanks for your PR @Abijeet 
Works great, only a small nitpick, then it's good from my side 😉

2017-12-05 07:41 UTC, juliushaertl commented on apps/theming/templates/settings-admin.php
> +			<input id="theming-color" type="text" class="jscolor {hash:true}" maxlength="7" value="<?php p($_['color']) ?>" />
I'd prefer using the data-jscolor attribute here.

2017-12-05 17:17 UTC, Abijeet commented
@juliushaertl - Done! :)

2017-12-08 09:55 UTC, MorrisJobke commented
@Abijeet I fixed the commits and resubmitted your PR in #7426.

Thanks for your contribution 👍  I will close this PR here and we merge the other one :)

2017-12-08 09:55 UTC, closed without merging