Satisfy \@PasswordConfirmationRequired when authenticating with Bearer Authorization header
nextcloud/server pull request #7501
Opened 2017-12-13 22:22 UTC by DamnDam

When authenticated with an access token in a Bearer Authorization header in a stateless context, it is impossible to satisfy \@PasswordConfirmationRequired

2017-12-14 10:59 UTC, DamnDam commented
This is relevant for OAuth2 authentication, especially as an admin @LukasReschke

2017-12-14 23:25 UTC, DamnDam commented
This should fix the same issue as #7487

2017-12-18 08:43 UTC, ChristophWurst commented on lib/private/User/Session.php
> +		$this->session->set('last-password-confirm', $this->timeFactory->getTime());
Looks like this line is also hit for simple browser sessions (line 737 and below) and thus *completely* disables the password confirmation feature.

2018-01-02 21:04 UTC, DamnDam commented on lib/private/User/Session.php
> +		$this->session->set('last-password-confirm', $this->timeFactory->getTime());
Right, sorry about that!

2018-01-05 14:05 UTC, ChristophWurst requested changes

2018-01-05 14:05 UTC, ChristophWurst commented on lib/private/User/Session.php
> +		if($loginWithHeader) {
this variable is not set on all previous code paths. it should be initialized with `false` at the beginning of the method body.

2018-01-18 12:21 UTC, rullzer commented
Since #7487 is in. Lets close this.

2018-01-18 12:21 UTC, closed without merging