Use correct SVG icon on share view
nextcloud/server pull request #7580
Opened 2017-12-19 15:47 UTC by pixelipo

Discovered while testing #7575 - it seems that $image-logo SCSS variable was pointing to a deprecated SVG image.
Before:
![image](https://user-images.githubusercontent.com/4129927/34165205-ee1350c2-e4db-11e7-81f0-b703dcf67a30.png)
![image](https://user-images.githubusercontent.com/4129927/34165181-dd84f954-e4db-11e7-94f9-44544d5b7436.png)

After:
![image](https://user-images.githubusercontent.com/4129927/34165254-0c5194a4-e4dc-11e7-9f3f-f106f80deed1.png)
![image](https://user-images.githubusercontent.com/4129927/34165132-b810eef8-e4db-11e7-9962-f3b03637d7fa.png)

2017-12-19 16:28 UTC, MorrisJobke commented
Acceptance tests fail:

```

  Scenario: open the menu in a public shared link                   # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:26
    Given I act as John                                             # ActorContext::iActAs()
    And I am logged in                                              # LoginPageContext::iAmLoggedIn()
    And I share the link for "welcome.txt"                          # FilesAppContext::iShareTheLinkFor()
    And I write down the shared link                                # FilesAppContext::iWriteDownTheSharedLink()
    When I act as Jane                                              # ActorContext::iActAs()
    And I visit the shared link I wrote down                        # FilesSharingAppContext::iVisitTheSharedLinkIWroteDown()
    And I see that the current page is the shared link I wrote down # FilesSharingAppContext::iSeeThatTheCurrentPageIsTheSharedLinkIWroteDown()
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -''
      +'about:blank'
    And I open the Share menu                                       # FilesSharingAppContext::iOpenTheShareMenu()
    Then I see that the Share menu is shown                         # FilesSharingAppContext::iSeeThatTheShareMenuIsShown()
```

2017-12-19 17:32 UTC, pixelipo commented
That's baffling. This PR could not possibly cause that failure. Any ideas?

2017-12-19 17:32 UTC, juliusknorr requested changes
The logo should not be stretched to the whole container when we use the default Nextcloud logo. Similar to https://github.com/nextcloud/server/pull/4910

2018-01-02 18:54 UTC, rullzer commented
@pixelipo any chance you can take a look at the comment from @juliushaertl ?

2018-01-03 10:17 UTC, closed without merging

2018-01-03 10:17 UTC, MorrisJobke commented
Merged as #7670 🤣

2018-01-03 11:08 UTC, juliushaertl commented
Addressed the logo sizing in #7678