made small changes to login screen -  Signed-off-by: Robert R Pirrita…
nextcloud/server pull request #7650
Opened 2017-12-29 22:57 UTC by rpirritano

Made all the recommended changes to the login screen, as well as having wrong password message no longer appear with clicking forgot password link

2018-01-02 08:30 UTC, rullzer requested changes

2018-01-02 08:30 UTC, rullzer commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Don't commit to .htaccess please ;)

2018-01-05 17:15 UTC, jancborchardt commented
@rpirritano thanks for the contribution! :) Could you clarify what you mean by recommended changes, ideally with a before/after screenshot for easier testing?

cc @nextcloud/designers

2018-01-06 22:08 UTC, rpirritano commented
@jancborchardt , sure!  The small changes I made were recommended from this thread: https://github.com/nextcloud/server/issues/7265#issuecomment-348094139

Below I am copying the recommendations, and before/after screenshots:

1. Logo is too high up; actually, its distance from top is OK, but now it's too far from the form itself:
image

I would remove 16px top+bottom margins from form {} in guest.css since they don't seem

Before: 

![before1](https://user-images.githubusercontent.com/8380531/34644374-59595c02-f2ea-11e7-8954-33010b5d802d.png)

After:

![screen shot 2018-01-06 at 2 01 10 pm](https://user-images.githubusercontent.com/8380531/34644384-74273f2c-f2ea-11e7-9012-a15019aa0c1f.png)

2. Is there a reason why footer has height: 70px? We can easily remove it (I think) and change the p.info {margin: 0 auto; padding-top: 20px; to simpler p.info {margin: 20px auto;} Added advantage to these changes would mean that the whole page would fit nicely on 320*480 screen:

Before: 

![before2](https://user-images.githubusercontent.com/8380531/34644389-8e0060d6-f2ea-11e7-9c46-51aed4b8fbe4.png)

After:

![screen shot 2018-01-06 at 2 01 10 pm](https://user-images.githubusercontent.com/8380531/34644396-a0edd674-f2ea-11e7-8e71-a089a061fd92.png)

3. "Wrong password " warning is above the #submit# button, but the#lost-password` warning is bellow - makes no sense at all
3a. Additionally, "Lost Password" warning also has opacity: .7; added to it for some reason.
3b. Ideally, it should also disappear as soon as "Forgot password?" button is clicked. That way, only one error should be visible at any given moment.

Before:
![before3](https://user-images.githubusercontent.com/8380531/34644409-df9abb76-f2ea-11e7-9afc-11412ac2e4ac.png)

After:

![screen shot 2018-01-06 at 2 00 36 pm](https://user-images.githubusercontent.com/8380531/34644411-f2487402-f2ea-11e7-9ff4-4bddfc5080ed.png)

![screen shot 2018-01-06 at 2 00 55 pm](https://user-images.githubusercontent.com/8380531/34644413-f8e7f328-f2ea-11e7-9348-9a43d43ac27b.png)

2018-01-08 04:12 UTC, skjnldsv commented
> would fit nicely on 320*480 screen

Is there really many out there tough? :)
I think it's great to have a small bottom padding to the slogan, We don't want the footer to be just at the bottom ;)

2018-01-09 10:13 UTC, jancborchardt commented
@rpirritano seems mostly good – however you seem to have removed the border from the primary buttons? Let's not do that as it makes them not look as clickable, which is a big problem for the primary action. :)

2018-01-09 19:09 UTC, rpirritano commented
@jancborchardt , this pull request does have the correct code and does have the button borders.  Those screenshots above were accidentally taken from an older version.

I double checked my code by cloning this master, and it appears correct.  Sorry for the confusion.

2018-01-09 20:43 UTC, jancborchardt commented
@rpirritano could you update the screenshots? :)

@nextcloud/designers what do you think?

2018-01-09 23:43 UTC, rpirritano commented
ok updated the comment above with the correct "after" screenshots

2018-01-10 12:18 UTC, skjnldsv commented
- [ ] The footer height needs to stay at 70px
- [ ] The .htaccess file needs to be removed from this pr

2018-01-10 13:06 UTC, enoch85 commented
:+1: Design wise from me. Looks a lot better.

2018-01-10 14:57 UTC, MorrisJobke commented on .htaccess
> -</IfModule>
Now you have removed the whole .htaccess 😉 I guess there was a misunderstanding: it was only regarding the changes in .htaccess. Could you try to do that? Thanks a lot 👍

2018-01-10 15:04 UTC, rpirritano commented on .htaccess
> -</IfModule>
Just to clarify, your comment above, "Now you have removed the whole .htaccess "  I did remove that file?  Was I only supposed to remove changes in the file and if so, what changes?

2018-01-10 15:10 UTC, MorrisJobke commented on .htaccess
> -</IfModule>
Those changes from your first commit: https://github.com/nextcloud/server/pull/7650/commits/409c2a08f8927c41340ba1fba14f76c815ed8f42#diff-8052c42ab3b8aa06a3f5f788a4ddccc2R84

2018-01-10 16:05 UTC, MorrisJobke commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
@rpirritano Now the changes are back again :)

2018-01-10 16:09 UTC, rpirritano commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
sorry I am new to this and the apache server.  I removed the changes that you took a screen shot of.  Can you also do that for the changes that are back again?

2018-01-10 16:18 UTC, rpirritano commented
ok I deleted the changes and hope this worked.

On Wed, Jan 10, 2018 at 8:05 AM, Morris Jobke <notifications@github.com>
wrote:

> *@MorrisJobke* commented on this pull request.
> ------------------------------
>
> In .htaccess
> <https://github.com/nextcloud/server/pull/7650#discussion_r160721591>:
>
> > @@ -78,3 +78,7 @@ Options -Indexes
>  <IfModule pagespeed_module>
>    ModPagespeed Off
>  </IfModule>
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
>
> @rpirritano <https://github.com/rpirritano> Now the changes are back
> again :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/7650#discussion_r160721591>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AH_gcxPvvD9UvFmHZ0tDAfsUfgL1q5NHks5tJN_hgaJpZM4RPb4n>
> .
>

2018-01-10 16:29 UTC, MorrisJobke commented
> ok I deleted the changes and hope this worked.

Don't worry. Sadly it didn't worked out. Best would be to squash all 5 commits into 1 commit by rebasing the branch, but this is not that trivial. I would give you a step by step guide, but sadly I need to leave now. I will provide you the guide later (or maybe @rullzer or @nickvergessen can help you in the meantime).

Thanks for the contribution anyways.

2018-01-10 19:43 UTC, rpirritano commented
A guide would be good, in the meantime I will research it myself and give it a go.

2018-01-10 20:36 UTC, MorrisJobke commented
Let me do the guide:

First do a backup of the current situation in case something goes wrong:

```
$ git branch master-backup
```

Now we do an interactive rebase (which allows to squash all commits into one) based on the last commit from the Nextcloud master branch (`08cbfb6c6b554eed221aafe185c02dc2e7841d95` is the commit before the first commit in this PR :wink:):

```
$ git rebase -i 08cbfb6c6b554eed221aafe185c02dc2e7841d95
```

An editor should open, that looks like this:

![bildschirmfoto 2018-01-10 um 21 28 56](https://user-images.githubusercontent.com/245432/34793916-4aba97b8-f64d-11e7-82a4-7c4bea047538.png)

This shows you the 4 commits of your master branch and you can specify an operation per commit. Leave the `pick` on the first line and replace the `pick` with an `s` (like squash - see comment in the editor) in the 3 other commits. This will keep the first commit and squash the 3 others into this commit to generate a big commit. (Keep in mind to have a space between the `s` and the commit sha).

Then another editor opens, that will allow you to specify the commit message for this new commit. Adjust it like you want.

Now copy the .htaccess file from our current master (this is easier than to fiddle around with partial git reverts):

```
wget https://raw.githubusercontent.com/nextcloud/server/master/.htaccess -O .htaccess
```

Just add this new file to the staged area in git and amend the previous commit to get rid of this change (amending adds the current change to the last commit without creating a new one):

```
git add .htaccess
git commit --amend
```

Now you are ready for pushing your changes, but because you changed the git history you need to do a force push to overwrite the git history on your master branch:

```
git push -f origin master
```

You are done 🚀

2018-01-10 20:52 UTC, rpirritano commented
Thanks, the guide was easy to follow!

2018-01-11 08:15 UTC, rullzer approved these changes

2018-01-11 10:06 UTC, MorrisJobke commented
Let me check why the integration tests fail.

2018-01-11 11:24 UTC, MorrisJobke commented
@rpirritano Could you add following patch:

```patch
diff --git a/tests/acceptance/features/bootstrap/LoginPageContext.php b/tests/acceptance/features/bootstrap/LoginPageContext.php
index 560dd83f30..1496e3030c 100644
--- a/tests/acceptance/features/bootstrap/LoginPageContext.php
+++ b/tests/acceptance/features/bootstrap/LoginPageContext.php
@@ -66,7 +66,7 @@ class LoginPageContext implements Context, ActorAwareInterface {
 	 * @return Locator
 	 */
 	public static function wrongPasswordMessage() {
-		return Locator::forThe()->xpath("//*[@class = 'warning' and normalize-space() = 'Wrong password.']")->
+		return Locator::forThe()->xpath("//*[@class = 'warning wrongPasswordMsg' and normalize-space() = 'Wrong password.']")->
 				describedAs("Wrong password message in Login page");
 	}
 ```

Once you changed the file do this:

```
git add tests/acceptance/features/bootstrap/LoginPageContext.php
git commit --amend
git push -f origin master
```

Then the tests should pass

2018-01-11 11:24 UTC, MorrisJobke commented
Problem here: As you changed the class of the warning the selector was not working anymore.

2018-01-11 11:38 UTC, rullzer commented
I took the liberty to push that so we can merge it.
Again, good stuff @rpirritano  :D

2018-01-11 12:05 UTC, juliusknorr approved these changes
Fine by me, if the tests pass. :+1:

2018-01-11 12:55 UTC, merged

2018-01-12 04:26 UTC, rpirritano commented
since this was merged, do I still need to add that patch @MorrisJobke

2018-01-12 09:42 UTC, juliushaertl commented
@rpirritano That patch was already added by @rullzer, so everything is done here. 
Thanks for the contribution, further pull requests are always welcome. :wink:

2018-01-12 10:01 UTC, MorrisJobke commented
> @rpirritano That patch was already added by @rullzer, so everything is done here.
> Thanks for the contribution, further pull requests are always welcome. 😉

Correct :) 


@rpirritano Thanks for you contribution here :) You could join our chat on Freenode - the channel name is #netcloud-dev. If you are looking for other issues, that one labeled with "starter issues" are maybe a good entry point for other things to do: https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+issue%22

2018-01-12 14:44 UTC, rpirritano commented
Great! Thank you for all your help!

On Fri, Jan 12, 2018 at 2:01 AM, Morris Jobke <notifications@github.com>
wrote:

> @rpirritano <https://github.com/rpirritano> That patch was already added
> by @rullzer <https://github.com/rullzer>, so everything is done here.
> Thanks for the contribution, further pull requests are always welcome. 😉
>
> Correct :)
>
> @rpirritano <https://github.com/rpirritano> Thanks for you contribution
> here :) You could join our chat on Freenode - the channel name is
> #netcloud-dev. If you are looking for other issues, that one labeled with
> "starter issues" are maybe a good entry point for other things to do:
> https://github.com/nextcloud/server/issues?q=is%3Aissue+is%
> 3Aopen+label%3A%22starter+issue%22
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/server/pull/7650#issuecomment-357195541>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AH_gcy79WlsKLdQNtzhSUglSJ-rmL73tks5tJy2WgaJpZM4RPb4n>
> .
>