Fixes for avatarmanager
nextcloud/server pull request #7847
Opened 2018-01-13 19:39 UTC by rullzer

* Made strict
* Declare return types
* Properly pass in the private usermanager so we get the right object back

2018-01-14 19:08 UTC, ChristophWurst commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
Could you please elaborate why you want to inject the implementation rather than the interface? Are we using a method that's not in the interface?

From an OOP perspective this seems wrong, or at least dangerous. The `Manager` type is more specific than the interface `IUserManager`. The alias should be registered the other way around.

2018-01-14 19:25 UTC, rullzer commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
Yes, the avatarmanager needs the implentation because we need to get back the actual user object (instead of the implementation)..

You are right about the other way around. I'll fix that.

2018-01-14 19:55 UTC, MorrisJobke commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
I was also about to report this. Better leave the details out and only inject interfaces and also only allow to interfaces in the server container.

2018-01-14 19:58 UTC, MorrisJobke commented on lib/public/IAvatarManager.php
> +declare(strict_types=1);
Could you put this directly below the line with `<?php` because PHPstorm itself does this so it's easier to detect when it is already inserted and also properly resolves as conflict for PRs like #7392

2018-01-14 20:33 UTC, rullzer commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
Mmmm this would then mean that we can't strictly type all our internal stuff. As sometimes we require things that are not in the interface.

2018-01-14 20:53 UTC, MorrisJobke commented on lib/private/AvatarManager.php
> +			Manager $userManager,
Is there a reason to use the private implementation here instead of the interface? I would like to keep the interface.

2018-01-14 20:53 UTC, MorrisJobke commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
Could you point out what is needed here?

2018-01-14 21:19 UTC, ChristophWurst commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
> Mmmm this would then mean that we can't strictly type all our internal stuff. As sometimes we require things that are not in the interface.

In that cases it would make sense to just create internal interfaces that have all the required methods and extend the public ones. Internal classes may inject the internal (private) interface. All classes may inject the public one. And in both cases we resolve to the same implementation.

2018-01-14 21:21 UTC, rullzer commented on lib/private/AvatarManager.php
> +			Manager $userManager,
I'm also fine with dropping the final commit and creating an issue how to solve it. As in. How can we make sure that our internal classes can get the implementation but apps can't request the implementation...

2018-01-14 21:34 UTC, ChristophWurst commented on lib/private/AvatarManager.php
> +			Manager $userManager,
(in case it was overlooked since GitHub collapsed the conversation, I'm linking my previous response: https://github.com/nextcloud/server/pull/7847#discussion_r161410410)

2018-01-14 22:50 UTC, MorrisJobke commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
Okay - let's not overcomplicate things here. If our internal code needs non-public-interfaced code: fine - inject the implementation.

2018-01-14 22:50 UTC, MorrisJobke commented on lib/private/AvatarManager.php
> +			Manager $userManager,
I commented there too.

2018-01-14 22:51 UTC, MorrisJobke requested changes
Tests are still failing.

2018-01-15 07:25 UTC, rullzer commented on lib/private/Server.php
> +		$this->registerAlias(\OC\User\Manager::class, \OCP\IUserManager::class);
So the more I'm thinking about this the more I would say leave this as is for now. We just have the implementation in the server container. Apps should not use the implementation anyways. And if they do it can break at any time.

I really like to focus on getting this clean and working before we introduce again such an abstraction that can break things.

In other words. We already tell people use the OCP stuff. And well if they don't it is their own fault.

2018-01-16 16:53 UTC, MorrisJobke approved these changes

2018-01-16 21:32 UTC, ChristophWurst approved these changes

2018-01-17 09:40 UTC, nickvergessen commented on lib/private/AvatarManager.php
> +			Manager $userManager,
Could also just type hint in the line before:
```php
/** @var User $user */
```
❓

2018-01-17 12:46 UTC, merged

2018-01-17 12:49 UTC, MorrisJobke commented
ref #7392