Dont polute the log on DAV emaillogin
nextcloud/server pull request #8002
Opened 2018-01-23 09:00 UTC by rullzer

To test:

1. setup a user `user1` and set the email to something
1. `curl -u <email>:<pass> <server>/remote.php/webdav -X PROPFIND`

Before: get a log entry saying login failed
After: No log entry

I also fixed that the thorttler was not increased when the email login was also invalid.

2018-01-23 09:26 UTC, MorrisJobke commented on tests/lib/User/SessionTest.php
> +use const ZipStreamer\INT64_LOW_MAP;
❓

2018-01-23 09:34 UTC, rullzer commented on tests/lib/User/SessionTest.php
> +use const ZipStreamer\INT64_LOW_MAP;
yes good question :confused:

2018-01-23 10:59 UTC, icewind1991 requested changes

2018-01-23 10:59 UTC, icewind1991 commented on lib/private/User/Session.php
>  			}
missing an `else {return true;}`?

2018-01-23 11:02 UTC, rullzer commented on lib/private/User/Session.php
>  			}
See https://github.com/nextcloud/server/blob/ef127a30ec9acd07c32952bf8b97059b280f7168/lib/private/User/Session.php#L434

2018-01-23 11:09 UTC, icewind1991 approved these changes

2018-01-24 12:59 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-01-24 13:00 UTC, merged