Expose navigation entries as API endpoint
nextcloud/server pull request #8095
Opened 2018-01-29 12:01 UTC by juliushaertl

This PR adds new endpoints to get the navigation entries for the app and settings menu, as discussed in #7893. This will make it possible for clients to fetch the list of available "web apps" but also use this in apps management to update the app menu when installing/uninstalling an app. I'll do that in a separate PR once this is merged.

@camilasan 

<details>
<summary>Example request: apps</summary>

```
$ curl http://admin:admin@localhost:8140/index.php/core/navigation/apps 
[
  {
    "id": "files",
    "order": "0",
    "href": "/index.php/apps/files/",
    "icon": "/apps/files/img/app.svg",
    "type": "link",
    "name": "Dateien",
    "active": false,
    "classes": ""
  },
  {
    "id": "activity",
    "order": "1",
    "href": "/index.php/apps/activity/",
    "icon": "/apps/activity/img/activity.svg",
    "type": "link",
    "name": "Aktivität",
    "active": false,
    "classes": ""
  },
  {
    "id": "gallery",
    "order": 2,
    "href": "/index.php/apps/gallery/",
    "icon": "/apps/gallery/img/app.svg",
    "name": "Galerie",
    "active": false,
    "classes": "",
    "type": "link"
  },
  {
    "id": "deck",
    "order": 10,
    "href": "/index.php/apps/deck/",
    "icon": "/apps-extra/deck/img/deck.svg",
    "name": "Deck",
    "active": false,
    "classes": "",
    "type": "link"
  }
]
```
</details>

2018-01-29 12:49 UTC, rullzer commented
Any reason not to expose this in the capabilities?

2018-01-29 12:59 UTC, juliushaertl commented
Quoting @nickvergessen from #7893, and I think it makes sense to have a separate endpoint which can also be used for the apps management as well.

> Not abuse the capabilities even more

2018-01-29 13:24 UTC, nickvergessen submitted a review, later dismissed

2018-01-29 13:24 UTC, nickvergessen commented on core/Controller/NavigationController.php
> +class NavigationController extends Controller {
Use OCSController please

2018-01-29 13:24 UTC, nickvergessen commented on core/Controller/NavigationController.php
> +		return new JSONResponse($navigation);
`return  new DataResponse($navigation);`

2018-01-29 13:24 UTC, nickvergessen commented on core/Controller/NavigationController.php
> +		return new JSONResponse($navigation);
`return  new DataResponse($navigation);`

2018-01-29 13:24 UTC, nickvergessen commented on core/Controller/NavigationController.php
> +	private function rewriteToAbsoluteUrls(array &$navigation) {
I'd prefer return over by-reference

2018-01-29 13:24 UTC, nickvergessen commented on core/routes.php
> +		['name' => 'Navigation#getSettingsNavigation', 'url' => '/core/navigation/settings', 'verb' => 'GET'],
should be OCS routes, everything else is not to be used by clients

2018-02-01 11:25 UTC, juliushaertl commented
@nickvergessen Migrated it to be an OCSController. Any opinions about the endpoint naming? Should we add it to the /cloud OCS root? Or just have a separate core one (as it is currently)?

2018-02-01 11:37 UTC, rullzer commented
I'm fine with the url like that :)

2018-02-01 12:04 UTC, nickvergessen commented on core/Controller/NavigationController.php
> +	public function getAppsNavigation(bool $absolute = false) {
You can add `: DataResponse` too

2018-02-01 15:45 UTC, juliushaertl commented on core/Controller/NavigationController.php
> +	public function getAppsNavigation(bool $absolute = false) {
Ah thanks, I somehow missed that.

2018-02-08 20:13 UTC, rullzer commented on core/Controller/NavigationController.php
> +			if (0 !== strpos($entry['href'], $this->urlGenerator->getBaseUrl())) {
Shouldn't we do the same check for the icon? So that they can also be used?

2018-02-08 20:13 UTC, rullzer commented
I rebased upon master and updated the autoloader.

2018-02-08 20:13 UTC, rullzer approved these changes
Cool stuff!

2018-02-08 20:14 UTC, rullzer commented on lib/private/legacy/app.php
>  	public static function getSettingsNavigation() {
Same here

2018-02-09 07:43 UTC, juliushaertl commented on lib/private/legacy/app.php
> +		return OC::$server->getNavigationManager()->getAll();
Fixed and also replaced the usage of those methods in the server.

2018-02-12 16:31 UTC, juliushaertl commented
> Shouldn't we do the same check for the icon? So that they can also be used?

Sorry, I missed that comment. Not the icon url will also be absolute if requested. Ready for review now.

2018-02-12 19:46 UTC, rullzer approved these changes

2018-02-14 19:57 UTC, camilasan commented
Could we merge it @nickvergessen ?

2018-02-15 09:30 UTC, nickvergessen requested changes

2018-02-15 09:30 UTC, nickvergessen commented on lib/public/INavigationManager.php
> +	public function getAll(string $type = 'link'): array;
does not match docs

2018-02-15 09:30 UTC, nickvergessen commented on lib/private/NavigationManager.php
> +	private function proceedNavigation($list) {
add type hint and return type, also in docs

2018-02-15 09:38 UTC, juliushaertl commented on lib/public/INavigationManager.php
> +	public function getAll(string $type = 'link'): array;
:+1: Fixed

2018-02-15 10:00 UTC, nickvergessen approved these changes

2018-02-15 15:55 UTC, MorrisJobke approved these changes

2018-02-15 15:55 UTC, merged

2018-02-19 15:02 UTC, camilasan commented
Just in case someone else also needs it - this is the correct way of doing the request:

```
$ curl http://user:password@localhost/nextcloud/ocs/v1.php/core/navigation/apps
```

After the changes in the code, the first example given in the comments it is not valid anymore.

2018-02-19 15:04 UTC, rullzer commented
@camilasan please use v2.php ;) That gives better http status codes.