Validate appinfo against appstore schema
nextcloud/server pull request #8232
Opened 2018-02-07 15:31 UTC by nickvergessen

Fix #8007

2018-02-08 20:29 UTC, rullzer commented
CI is not happy about this

2018-02-08 21:22 UTC, nickvergessen commented
> Nextcloud is not installed - only a limited number of commands are available
> 
> 
>   [Doctrine\DBAL\DBALException]                                                
>   Failed to connect to the database: An exception occured in driver: SQLSTATE  
>   [HY000] [14] unable to open database file                                    
>                                                                                
> 
> app:check-code [-c|--checker CHECKER] [--skip-checkers] [--skip-validate-info] [--] <app-id>
> 
> PHP Warning: fileperms(): stat failed for /drone/src/github.com/nextcloud/server/data/nextcloud.log in /drone/src/github.com/nextcloud/server/lib/private/Log/File.php on line 139

sounds like disk is full?

2018-02-09 08:20 UTC, BernhardPosselt commented
Schema updated fyi

2018-02-14 15:42 UTC, nickvergessen commented
@MorrisJobke @rullzer rebased, please review

2018-02-15 13:53 UTC, MorrisJobke approved these changes

2018-02-15 15:36 UTC, nickvergessen commented on core/Command/App/CheckCode.php
> +			$infoChecker = new InfoChecker(\OC::$server->getAppManager());
Okay, this breaks the tests, because it depends on AppConfig which depends on IDBConnection, although the instance is not installed.
Easy fix would be to make this command not available anymore on non-installed instances.

Another idea would be to split the isShipped/isAlwaysEnabled methods out into another class which can be used without database.

Preferences? @rullzer @MorrisJobke

2018-02-15 15:44 UTC, MorrisJobke commented on core/Command/App/CheckCode.php
> +			$infoChecker = new InfoChecker(\OC::$server->getAppManager());
I would tend to have it in a separate class/trait and pull it in the app manager then. Something like we did with IConfig and SystemConfig. But this is only my opinion.

2018-02-16 09:25 UTC, nickvergessen commented on core/Command/App/CheckCode.php
> +			$infoChecker = new InfoChecker(\OC::$server->getAppManager());
Hmm instead of that I copied the "read shipped.json and check for existance" now to this class directly. Seems easier and good enough for now.

2018-02-16 13:43 UTC, MorrisJobke approved these changes

2018-02-16 14:18 UTC, juliusknorr requested changes

2018-02-16 14:18 UTC, juliushaertl commented on core/Command/App/CheckCode.php
> +			$infoChecker = new InfoChecker(\OC::$server->getAppManager());
The InfoChecker doesn't need the AppManager anymore. :wink:

2018-02-16 14:18 UTC, juliushaertl commented on core/Command/App/CheckCode.php
> +			$infoChecker = new InfoChecker(\OC::$server->getAppManager());
I don't like the duplicate code that much. Can't we just use the InfoChecker in the AppManager now?

2018-02-16 16:18 UTC, nickvergessen commented on lib/private/App/CodeChecker/InfoChecker.php
> +			if ($this->isShipped($appId)) {
> I don't like the duplicate code that much. Can't we just use the InfoChecker in the AppManager now?

@juliushaertl sorry, but that makes no sense from API point of view, also we are actually talking about 2 lines of code which read a JSON file. not worth a lot of troubles in my opinion. I can also remove all the function overhead which is just there to keep the code in line with the app manager.

```php
$content = json_decode(file_get_contents(\OC::$SERVERROOT . '/core/shipped.json'), true);
if (\in_array($appId, $content['shippedApps'], true)) {
```

2018-02-16 16:43 UTC, juliushaertl commented on lib/private/App/CodeChecker/InfoChecker.php
> +			if ($this->isShipped($appId)) {
Ok, fine by me then. I guess we should have a subset of the AppManager available for using without any DB setup in the future.

2018-02-16 16:44 UTC, juliusknorr approved these changes

2018-02-16 21:56 UTC, merged

2018-02-16 21:56 UTC, MorrisJobke commented on lib/private/App/CodeChecker/InfoChecker.php
> +			if ($this->isShipped($appId)) {
We also thought a lot about where to put it but in the end for those few lines of code it was just overkill to create another layer of abstraction. ;)