External storage test: log exceptions
nextcloud/server pull request #8284
Opened 2018-02-09 16:35 UTC by Cybso

If an external storage test fails the exception's message is now written
into the logfile (level INFO). This helps to resolve the reason for a
failing connection.

Signed-off-by: Roland Tapken <roland@bitarbeiter.net>

2018-02-09 16:51 UTC, icewind1991 requested changes

2018-02-09 16:51 UTC, icewind1991 commented on lib/private/Files/Storage/Common.php
> +			\OC::$server->getLogger()->info("External storage not available: " . $e->getMessage());
Please use `logException` instead to preserve stack trace.

(you can set the log level by passing `['level' => ...]` as 2nd argument)

2018-02-09 20:55 UTC, Cybso commented
logException doesn't have a message field. What do you think about this variant? While logging in INFO level this writes a short entry into the logfile, and in DEBUG level the stack trace would be available, too:

```
        try {
            if ($this->stat('')) {
                return true;
            }
            \OC::$server->getLogger()->info("External storage not available: stat() failed");
            return false;
        } catch (\Exception $e) {
            \OC::$server->getLogger()->info("External storage not available: " . $e->getMessage());
            \OC::$server->getLogger()->logException($e, ['level' => \OCP\Util::DEBUG]);
            return false;
        }
```

2018-02-10 12:45 UTC, icewind1991 commented
Looks good

2018-02-13 13:06 UTC, icewind1991 approved these changes

2018-03-01 19:32 UTC, rullzer approved these changes

2018-03-01 19:32 UTC, merged