AppData hardening
nextcloud/server pull request #8289
Opened 2018-02-09 19:20 UTC by rullzer

Since people sometimes do weird stuff with their appdata folders. Make them a bit more robust. basically we can check fs actions. And if they fail we do stuff

- [x] SimpleFile getContents
- [ ] SimpleFile putContent
- [ ] SimpleFolder newFile
- [ ] AppData newFolder

@juliushaertl @icewind1991 does this make sense?

2018-02-12 08:18 UTC, MorrisJobke commented
Makes sense IMO

2018-02-12 10:44 UTC, rullzer commented
Ok I think this should catch most of the issues:

File read/write: Before reading/writing stat the file so we know it is still there. If not we delete the file. And recursively delete up as long as they don't exist.

Folder create: Creating of a folder doesn't happen to often. So check if the current folder still exists (stat). If not recursively delete up until we find an existing folder.

2018-02-12 14:28 UTC, rullzer commented
O joy weird unit test errors

2018-02-12 15:32 UTC, icewind1991 commented on lib/private/Files/SimpleFS/SimpleFile.php
> +	private function checkFile() {
I dont understand what this is supposed to do.

It deletes the files and it's parent when it doesn't exist(?) and then fails if it went into the loop at least once(?)

2018-02-12 15:44 UTC, rullzer commented on lib/private/Files/SimpleFS/SimpleFile.php
> +	private function checkFile() {
yep

2018-02-12 16:26 UTC, icewind1991 commented on lib/private/Files/SimpleFS/SimpleFile.php
> +	private function checkFile() {
Could you add some comments explaining the why

2018-02-13 08:32 UTC, rullzer commented
Review time

2018-02-13 10:06 UTC, nickvergessen commented on lib/private/Files/SimpleFS/SimpleFile.php
> +			throw new NotPermittedException('File does not exist');
Should that be NotFoundException instead?

2018-02-13 13:04 UTC, icewind1991 requested changes

2018-02-13 13:04 UTC, icewind1991 commented on lib/private/Files/AppData/AppData.php
> +		if ($appFolder->stat() === false) {
Can you do the same thing here as you did got `getContent`, only do the check if the operation fails

2018-02-20 09:29 UTC, rullzer commented on lib/private/Files/SimpleFS/SimpleFile.php
> +			throw new NotPermittedException('File does not exist');
Yes

2018-02-20 09:29 UTC, rullzer commented on lib/private/Files/AppData/AppData.php
> +		if ($appFolder->stat() === false) {
Lets see if that is actually passed on...

2018-02-20 09:44 UTC, rullzer commented on lib/private/Files/AppData/AppData.php
> +		if ($appFolder->stat() === false) {
The issue is that I have a simple way to check if the newfolder is valid. At least not as far as I can tell...

2018-02-27 10:25 UTC, rullzer commented on lib/private/Files/AppData/AppData.php
> +		if ($appFolder->stat() === false) {
Ok maybe just checking the file is enough for now on read. As that will propegate up anyway. Let me fix it like that and we can get this in.

2018-03-01 18:53 UTC, rullzer commented
Ok lets first do this tiny part then. Review time!

2018-03-01 20:36 UTC, icewind1991 approved these changes

2018-03-02 10:26 UTC, nickvergessen approved these changes

2018-03-02 10:26 UTC, merged

2018-03-02 10:27 UTC, nickvergessen commented
Backport to 13?

2018-03-02 20:23 UTC, rullzer commented
Yes will take care!