New standard for top right header
nextcloud/server pull request #8373
Opened 2018-02-15 10:44 UTC by skjnldsv

### The goal:
- Create a simple way to add icons in the top right header with the minimum amount of css hacks (e.g: none!)

### Changed:
- The menus are now relative to the icons they belong to
- The width is now based on the browser viewport width (using px units or percent is not possible because of the relative position of the menu and its parent: the icon)
- The arrow is now automatically positioned. Before every app had to HARDCODE the right positioning (which was a nonsense) preventing new apps to add their own menus and therefore messing with the right positioning of all of this mess)

### Structure:
```
<div class="header-right">
	<div class="xxxxxxxxxx">
		<div class="xxxxxxxxxx-button menutoggle"></div>
		<div class="xxxxxxxxxx-container menu">
			
		</div>
	</div>
</div>
```

It's as simple as that! :)

2018-02-19 16:18 UTC, jancborchardt commented
As far as the standardization goes, sure, seems good. :)

But let’s not allow apps to just register things in the top right as well. Those are the core functions: Search, Contacts, Notifications and Settings – and that is already way enough for there. Otherwise the interface will just become a free-for-all.

2018-02-19 17:42 UTC, skjnldsv commented
I know, but people are doing it anyway, so at least provide a clean way to do it. :)
Do you want us not to document it then?

2018-02-19 18:15 UTC, juliushaertl commented
> The width is now based on the browser viewport width (using px units or percent is not possible because of the relative position of the menu and its parent: the icon)

@skjnldsv Doesn't seem to work here. Can you have a look, would be nice if we can have that so the menus will also work properly on small screens:
![bildschirmfoto vom 2018-02-19 17-54-07](https://user-images.githubusercontent.com/3404133/36391939-1510988a-15a9-11e8-9f7d-60a75ea33048.png)

> Do you want us not to document it then?

Makes sense to me to just have it standardized across internal apps, but not add it to the app developers docs. :+1:

2018-02-19 19:08 UTC, skjnldsv commented
@juliushaertl you're using a too narrow width. 320px?
I can push a fix for this width as well, but I don't really think many users have this width! ;)


On a side note, we should document our standard. Like min screen we supports, min browser (is this already somewhere) :)

2018-02-19 19:45 UTC, juliushaertl commented
@skjnldsv It is 395px actually. But i think 320px should still be supported, since there are still quite some smartphones out there with a smaller screen. :wink: 

Supported web browsers are listed here: https://docs.nextcloud.com/server/13/user_manual/webinterface.html

2018-02-20 06:52 UTC, skjnldsv commented
Okay, I'll push a fix then! :)

2018-02-20 10:08 UTC, skjnldsv commented
Hum, if I want to drop the positioning on narrow width, I have no choices but to remove the arrow.

Since there is no way to _calculate the `menutoggle` icon right distance-to-window_, I can't provide a fix to center the menu. The only way to do this is either, drop the relative positioning and use a fixed one, which means I can't position the arrow properly since I still can't _calculate the `menutoggle` icon right distance-to-window_. Which means I need to drop it :/

I could change the dom location of the arrow from within the menu to within the `menutoggle` icon, whic works perfectly. But I can't get a selector to decide whento show or hide the arrow ^^'
![capture d ecran_2018-02-20_11-07-34](https://user-images.githubusercontent.com/14975046/36418154-46cafca0-162e-11e8-9703-2535985748b3.png)

2018-02-21 12:32 UTC, jancborchardt commented
Ok, not documenting/encouraging it sounds good. :)

Agree with Julius on the width - there's also the case where people use splitscreen on their tablets etc. ;) It's not only old phones.

And yeah, the triangle should still show as that's important feedback and indicator as to what is open.

2018-02-21 12:51 UTC, skjnldsv commented
Okay, then we'll have no choices but to either
1. use a div for the arrow and not ::after (so we can set its visibility with the sibling selector)
2. edit the registerMenu function to add a class on open to the top right menu icon container
3. use some arbitrary width values which lead to an uneven visual due to the uneven distance-to-right of the icons menutoggle

2018-02-21 14:17 UTC, skjnldsv commented
Okay, I pushed a new fix, but I'm not quite fond of how the registerMenu function looks now. :/
It works fine and is retro compatible (if you omit the openedMenu boolean, the menu won't have an arrow, so not breaking anything. Everything looks fine nonetheless.

2018-02-27 11:36 UTC, juliusknorr requested changes
Seems the more apps menu is broken in general. Can you have another look @skjnldsv ?

2018-02-27 11:36 UTC, juliushaertl commented on core/templates/layout.user.php
> +										<div class="icon-loading-small" style="display:none;"></div>
Why this change? This will break the loading indicator in the more apps menu. :wink:

2018-02-27 11:39 UTC, skjnldsv commented on core/templates/layout.user.php
> +										<div class="icon-loading-small" style="display:none;"></div>
because the dark loader is supposed to be used on dark backgrounds. :)

2018-02-27 11:49 UTC, skjnldsv commented
- [ ] Fix app list menu

2018-02-27 11:50 UTC, juliushaertl commented on core/templates/layout.user.php
> +										<div class="icon-loading-small" style="display:none;"></div>
:see_no_evil: Ah sorry, confused that somehow.

2018-02-27 13:43 UTC, MorrisJobke commented on core/templates/layout.user.php
> +										<div class="icon-loading-small" style="display:none;"></div>
I was really confused how a whitespace change could cause a bug which is that critical 🙈 :

![bildschirmfoto 2018-02-27 um 14 43 02](https://user-images.githubusercontent.com/245432/36731958-98c7913c-1bcc-11e8-896b-49d3362a108a.png)

2018-02-27 13:45 UTC, skjnldsv commented on core/templates/layout.user.php
> +										<div class="icon-loading-small" style="display:none;"></div>
Ahahaha, github is strange sometimes ;D

2018-03-04 15:40 UTC, skjnldsv commented
![capture d ecran_2018-03-04_16-39-24](https://user-images.githubusercontent.com/14975046/36947346-9f78ac76-1fca-11e8-821c-b12c5aaf1f23.png)

@juliushaertl I need your help on this, I can't get the arrow to be over the menu. The drop shadow filter seems to override every zindex settings. Could you have a look? This is the last issue I have before sending this for review :)

2018-03-04 15:44 UTC, skjnldsv commented
Also, on small screens, shouldn't we go full screens? @nextcloud/designers 
![capture d ecran_2018-03-04_16-43-39](https://user-images.githubusercontent.com/14975046/36947395-501fd388-1fcb-11e8-8de2-a3245814f5f9.png)![capture d ecran_2018-03-04_16-44-09](https://user-images.githubusercontent.com/14975046/36947396-503a4150-1fcb-11e8-99ab-d23ad8e91dd0.png)

2018-03-05 11:18 UTC, juliushaertl commented
> @juliushaertl, @danxuliu I need your help on this, I can't get the arrow to be over the menu shadow on narrow screens (<480). The drop shadow filter seems to override every zindex settings. Could you have a look? This is the last issue I have before sending this for review :)

@skjnldsv I cannot reproduce the drop shadow layering issue here.

> Also, on small screens, shouldn't we go full screen? @nextcloud/designers

I'd say it's fine as it is right now. No need to complicate things, if it works with the default layout.

2018-03-05 11:24 UTC, skjnldsv commented
Then it's ready for reviews! @nextcloud/designers

2018-03-07 08:53 UTC, juliusknorr approved these changes
Works and changes look good.

2018-03-07 08:55 UTC, juliushaertl commented
The notifications icon is missing the popover-arrow but that should be fixed by adding the openedMenu class inside the notifications app.

2018-03-07 08:57 UTC, skjnldsv commented
@juliushaertl exactly! :)

2018-03-07 09:48 UTC, MorrisJobke submitted a review, later dismissed

2018-03-07 09:48 UTC, MorrisJobke commented on core/css/header.scss
> +			position: relative;
This kills the public page menu for me:

![bildschirmfoto 2018-03-07 um 10 26 02](https://user-images.githubusercontent.com/245432/37084140-024a0916-21f2-11e8-9b67-0e607439f4cd.png)

2018-03-07 10:06 UTC, skjnldsv commented on core/css/header.scss
> +			position: relative;
Okay, fixed. It was because the menu was not following the new standard :)

Also, the input will look better once #8575 is merged

2018-03-07 11:30 UTC, MorrisJobke commented
Also there is a little gap:

this branch:

<img width="368" alt="bildschirmfoto 2018-03-07 um 12 28 13" src="https://user-images.githubusercontent.com/245432/37090087-45faf772-2203-11e8-901f-5b981ec3169b.png">

master:

<img width="356" alt="bildschirmfoto 2018-03-07 um 12 29 42" src="https://user-images.githubusercontent.com/245432/37090090-4ab94a34-2203-11e8-8d92-5eb295b6920b.png">

2018-03-07 11:32 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-03-07 11:33 UTC, merged

2018-03-07 11:34 UTC, nickvergessen commented
> The notifications icon is missing the popover-arrow on mobile but that should be fixed by adding the openedMenu class inside the notifications app.

let me try this