Add dynamic icon creation
nextcloud/server pull request #840
Opened 2016-08-11 21:49 UTC by juliushaertl

So this basically addresses #218 and #378. With this change the theming app offers two new endpoints for getting themed icons:
http://localhost:8080/index.php/apps/theming/favicon/appname
http://localhost:8080/index.php/apps/theming/image/appname/filepath

Results:
![2016-08-11-231339_961x348_scrot](https://cloud.githubusercontent.com/assets/3404133/17605943/2b43e05a-601d-11e6-9d5e-11e5d9c665bd.png)
![2016-08-11-234209_191x31_scrot](https://cloud.githubusercontent.com/assets/3404133/17606053/c22e54d2-601d-11e6-8837-0afb9ee24685.png)

- [ ] use theming logo instead of nextcloud if available
- [ ] Add caching
- [ ] Unit tests
- [ ] touch homescreen icons
- [ ] search icons.css for classes like icon-folder to replace the icon with a themed one
- [ ] check if there are directory traversal issues
- [ ] cleanup

2016-08-14 16:37 UTC, rullzer commented
Mmmm I guess we kind of have to at some point. But we should add a big cache and cache buster (changed only when the theme is updated!) to make sure this hits the server as few times as possible. Because we will setup a lot of stuff to server an icon.

awesome initiative @juliushaertl!

2016-08-15 09:45 UTC, juliushaertl commented
I'm still trying to figure out how caching could be implemented. I think having the files on the file system makes the most sense.

For now I think I'll just store them into the data/ folder, like it is currently happening with the logo and background image, but this will become a huge mess due to number of icons. 
Therefore https://github.com/nextcloud/server/issues/136 looks promising.

2016-08-15 10:01 UTC, rullzer commented
@juliushaertl no the point is that right now all icons are serverd by the webserver. No PHP is involved etc.

We can easily add proper caching headers. Just let me know if you need help.

2016-08-26 08:37 UTC, jancborchardt commented
Awesome @juliushaertl! :) Only thing is that the favicon logo is black whereas the normal logo is white. The favicon should be the same as the chosen logo. :)

2016-08-26 10:11 UTC, juliushaertl commented
@jancborchardt ah right, I'll remove that.

I should have some time later today to finish this.

2016-08-29 15:05 UTC, juliushaertl commented
OK, i'll need some more time, as testing the Imagemagick stuff will be a bit harder. But I'm on it. :smile:

2016-08-30 10:13 UTC, juliushaertl commented
Finally ready for review! @nextcloud/theming 

@rullzer It would be great if you could have a look if the caching is fine. (apps/theming/lib/Controller/IconController.php)

It would also be good if someone could have a look if there are any problems with directory traversal. The route Icon#getThemedIcon accepts paths within the image parameter to allow getting images inside a subdirectory ( like `mimetypes/folder.svg` to get `/core/img/mimetypes/folder.svg`). 
It seems like those are already prevented, but it would be good to have someone
check that as well. @nextcloud/security

2016-08-30 12:51 UTC, MorrisJobke commented
Tested and works in Firefox. Opera, Safari, Chrome, Edge, IE11 and IE10 🙌 👍

2016-08-31 13:47 UTC, rullzer commented on apps/theming/lib/Controller/IconController.php
> +		return $response;
You don't store the colored svg anywhere?
If you have a themed instance with 50K users you will still have to do this for 50K users.

Also if you have a file that you server we could use https://github.com/nextcloud/server/pull/1121. you could set the ETag. That way if the file did not change the request is fast.

2016-08-31 19:44 UTC, juliushaertl commented on apps/theming/lib/Controller/IconController.php
> +		return $response;
> We can easily add proper caching headers. 

OK, maybe I misinterpreded your previous answer. I already thought that storing the generated icons in the filesystem would make sense. Do you have any hint how I could implement that?

We can't store it in the user-folders as these are also required for public/login page. I guess we should not just put them inside the data folder. That is why I thought that #136 might be important. Or is it possible to use a simple memory cache for these icons, as the number of those generated icons will stay quite low?

It would be great, if you could point me into the right direction.

2016-09-01 09:12 UTC, rullzer commented on apps/theming/lib/Controller/IconController.php
> +		return $response;
Hehe. Well there are 2 things of course.

1. We want to cache server side so serving is fast
2. We want to cache client side so we don't have to request stuff from the server every time

They are two different optimizations but work towards the same goal of less request => less server load & faster loading

I'll see if we can make #136 happen sooner rather than later. because I don't really feel comfortable just dumping this all in the root data folder.

2016-09-04 17:46 UTC, juliushaertl commented on apps/theming/lib/Controller/IconController.php
> +		return $response;
That would be great. :)

2016-10-06 13:48 UTC, rullzer commented
IAppData is in. So we should be able to do this a bit nicer now. I'll look into that!

2016-10-06 13:53 UTC, rullzer commented
Ah @juliushaertl you were already on it! awesome!

2016-10-06 13:56 UTC, juliushaertl commented
@rullzer Right, thank you very much for implementing this so fast. :rocket: 

I still need to fix some tests and go through the code again, but I'll try to finish this over the weekend.

2016-10-12 17:14 UTC, elioqoshi commented
@juliushaertl is this ready for review? Good job!

2016-10-12 19:00 UTC, juliushaertl commented
@elioqoshi @rullzer @MorrisJobke @nextcloud/theming Should be fine now. Please review.

The coverage is decreased, as we currently have no Imagemagick SVG-Provider in the CI docker container, but I guess we can address that later.

2016-10-13 13:06 UTC, MorrisJobke commented
Tested and works 👍

2016-10-13 13:07 UTC, MorrisJobke commented
I tested this in IE111, Edge, Safari, Chrome and Firefox 🎉

2016-10-14 09:50 UTC, rullzer commented
@juliushaertl awesome stuff! :rocket: See my comments to improve caching even more :D

2016-10-14 10:15 UTC, juliushaertl commented
@rullzer Which comments exactly? 

> We want to cache server side so serving is fast
Files are generated once and after that fetched from AppData.

> We want to cache client side so we don't have to request stuff from the server every time
> Also if you have a file that you server we could use #1121. you could set the ETag. That way if the file did not change the request is fast.
ETags are set by FileDisplayResponse, right?

Is there anything else I'm missing?

2016-10-14 10:24 UTC, juliushaertl commented on apps/theming/lib/Controller/IconController.php
> +		$response->addHeader('Expires', date(\DateTime::RFC2822, $this->timeFactory->getTime()));
@rullzer Ah, that Expires value doesn't make much sense :see_no_evil:

2016-10-14 11:23 UTC, rullzer requested changes

2016-10-14 11:23 UTC, rullzer commented
@juliushaertl ah my bad had to submit the review.

2016-10-14 11:24 UTC, rullzer commented
@juliushaertl yes etag magic is all handled in the response

2016-10-14 14:12 UTC, juliushaertl commented
@rullzer Ok, thanks for the comments. Changes are in.

2016-10-14 19:10 UTC, rullzer approved these changes

2016-10-14 19:12 UTC, rullzer commented
awesome stuff @juliushaertl 
Looks good now! Lets get this in! :+1:

2016-10-14 19:13 UTC, rullzer commented
@LukasReschke are you fine with merging this (since you are assigned)?

2016-10-14 19:55 UTC, juliushaertl commented
Sorry missed that you have already approved now. I've pushed another commit that removes a deprecated method call and fixes resizing issues that occurred when I tested this on Debian. But they are rather small :see_no_evil:

2016-10-15 17:51 UTC, rullzer commented
@juliushaertl np change is also fine :smile:

2016-10-17 09:09 UTC, nickvergessen commented
The favicon doesn't work for  me.

Also the folder icon in the "New" dropdown is still blue. Is this fixable?

2016-10-17 11:24 UTC, MorrisJobke commented
> The favicon doesn't work for me.

This is heavily cached and not easily removable from the cache. I also struggled very often with this. Just ignore it for now or use a completely fresh installed browser or a browser that never was on this domain. 🙈

2016-10-17 12:08 UTC, juliushaertl commented
>> The favicon doesn't work for me.

> This is heavily cached and not easily removable from the cache. I also struggled very often with this. Just ignore it for now or use a completely fresh installed browser or a browser that never was on this domain. :see_no_evil:

Hard reloading always works for me on chrome. But you can manually check if /index.php/apps/theming/favicon/settings?v=1 renders the correct favicon.

> Also the folder icon in the "New" dropdown is still blue. Is this fixable?

Good catch, will fix that later today.

2016-10-17 12:55 UTC, juliushaertl commented
@nickvergessen Fixed as well, it was already in but a missing bracket in the css code.

2016-10-17 12:55 UTC, nickvergessen commented
Works now 👍

2016-10-17 12:56 UTC, nickvergessen commented on apps/theming/lib/Controller/IconController.php
> +}
missing newline

2016-10-17 12:57 UTC, nickvergessen commented on apps/theming/lib/IconBuilder.php
> +			$tmp = new Imagick();
And what happens if you didn't install imagick?

2016-10-17 13:03 UTC, nickvergessen submitted a review, later dismissed

2016-10-17 13:03 UTC, nickvergessen commented on apps/theming/lib/IconBuilder.php
> +			$tmp = new Imagick();
As per docs imagick is optional, as per docs:
https://docs.nextcloud.com/server/10/admin_manual/installation/source_installation.html
> For preview generation (optional):
> * PHP module imagick

So please wrap with: `if(extension_loaded('imagick')) {`

2016-10-17 14:34 UTC, juliushaertl commented on apps/theming/lib/Controller/IconController.php
> +}
fixed in a77f774

2016-10-17 14:36 UTC, juliushaertl commented
Regarding the imagick checks, those are handled in the controller.

From IRC: 
> [16:04] < juliushaert> | nickvergessen: regarding your comments on https://github.com/nextcloud/server/pull/840 ... there is always a check in the controller if imagemagick is available, if not those methods you've commented will not be called. shall i add the check 
                            anyway?
[16:05] < nickvergessen> hmm
[16:07] < nickvergessen> I guess thats fine then

@nickvergessen @rullzer

2016-10-18 09:58 UTC, jancborchardt commented
Also reviewed it and it looks awesome! :+1: everything works except the caching problems with the favicon.

So, can we get this merged or is anything blocking?

2016-10-18 10:23 UTC, LukasReschke commented
I'll have a closer look later about any potential directory traversals.

2016-10-18 14:28 UTC, nickvergessen commented on apps/theming/appinfo/routes.php
> +		'defaults' => array("app" => "core"),
we use single quotes in php *nitpicking*

2016-10-19 06:15 UTC, juliushaertl commented on apps/theming/appinfo/routes.php
> +		'defaults' => array("app" => "core"),
I'll fix those at well, after Lukas had a look at it. :wink:

2016-10-22 14:13 UTC, LukasReschke commented
How can I test this? I use PHP 7.0 on Ubuntu 16.04 and installing php-imagick makes `\OCA\Theming\ThemingDefaults::shouldReplaceIcons` still return `false` because the SVG support is not loaded.

2016-10-22 14:44 UTC, oparoz commented
You need `libmagickcore-6.q16-2-extra`

2016-11-04 07:09 UTC, nickvergessen commented
Review status? @LukasReschke

2016-11-04 10:07 UTC, LukasReschke commented
> Review status? @LukasReschke

Looking at it … now … :)

2016-11-04 10:29 UTC, juliushaertl commented on apps/theming/lib/IconBuilder.php
> +<?php
This is just because the current drone docker image doesn't have any SVG provider for Imagemagick. So tests are skipped, just as it is done for the svg preview stuff atm. I thought we can add that later.

2016-11-04 11:00 UTC, LukasReschke commented on apps/theming/lib/IconBuilder.php
> +<?php
Let me add that to the Drone containers now. :)

2016-11-04 11:16 UTC, LukasReschke commented on apps/theming/lib/IconBuilder.php
> +<?php
Added. Let's see how CI goes :)

2016-11-04 11:27 UTC, LukasReschke commented
Rebased on current master as well.

2016-11-04 12:19 UTC, LukasReschke requested changes
The code works as expected and looks good to me generally speaking. Good job!

There are some security considerations that depending on one's server configuration will lead to a directory traversal. I'd like to see them addressed also some nitpicking in the comments :)

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	public function __construct(IConfig $config, IRootFolder $rootFolder) {
PHPDocs are always appreciated :)

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	private $config;
`/** @var IConfig */`

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	private $rootFolder;
`/** @var IRootFolder /*`

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/ThemingDefaults.php
> +								ICacheFactory $cacheFactory
This seems to not have been updated in above's PHPDoc :)

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/ImageManager.php
> +
Uneeded new lines.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Controller/IconController.php
> +			$response = new DataDisplayResponse(null, Http::STATUS_NOT_FOUND);
Just use a normal Response for that. No need to over-specify here.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +		$appPath = \OC_App::getAppPath($app);
Also I'd appreciate a check on `false` to harden the code a tad more.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +		$appPath = \OC_App::getAppPath($app);
Also I'd appreciate a check on `false` to harden the code a tad more.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	public function getAppIcon($app) {
For some more hardening also consider using \OC_App::cleanAppId. Since no public API might as well just copy it here.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +		$icon = $appPath . '/img/' . $image;
The code in this file is a little bit too optimistic to me. It basically assumes that the webserver is converting all `/../` and routing that to the upper folder. This is a configuration thingy and not always the case plus there may be other ways to make $image contain stuff like `../../../foo/`

Please sanitize $app and $image and ensure it doesn't contain any potential directory traversal characters. ` \OC_App::cleanAppId` may be a good start here.

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	public function __construct(IConfig $config, IRootFolder $rootFolder) {
PHPDOc

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	private $rootFolder;
PHPDoc

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/Util.php
> +	private $config;
PHPDoc

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/tests/Controller/IconControllerTest.php
> +
Unrequired newlines

2016-11-04 12:19 UTC, LukasReschke commented on apps/theming/lib/IconBuilder.php
> +		$appIconContent = file_get_contents($appIcon);
Too optimistic for me. Needs to catch error situations if the file does not exists and also have proper security by sanitizing $app as pointed out later.

2016-11-04 19:55 UTC, juliushaertl commented on lib/private/URLGenerator.php
> +		if(\OCP\App::isEnabled('theming') && $image === "favicon.ico" && \OC::$server->getThemingDefaults()->shouldReplaceIcons()) {
@LukasReschke Not sure how to handle this, as this will produce a circular dependency 

IURLGenerator -> ThemingDefaults -> IURLGenerator

Another point is that IURLGenerator is also beeing used before installation and therefore querying IAppManager fails as there is no database in place. But i guess we could handle it like here: https://github.com/nextcloud/server/blob/master/lib/private/Server.php#L561-L569

2016-11-04 19:56 UTC, juliushaertl commented on lib/private/URLGenerator.php
> +		if(\OCP\App::isEnabled('theming') && $image === "favicon.ico" && \OC::$server->getThemingDefaults()->shouldReplaceIcons()) {
@LukasReschke Thanks for the detailed review btw. :wink:

2016-11-05 19:13 UTC, juliushaertl commented on apps/theming/lib/IconBuilder.php
> +		$appIconContent = file_get_contents($appIcon);
Error handling in 56a5f4a
Sanitizing https://github.com/nextcloud/server/pull/840/commits/75d5a8d0c5f31a36348c75c106340c5d0878c745#diff-3de1769d04fcc4f13f8d546d9fbdac19R110

2016-11-05 19:20 UTC, juliushaertl commented on apps/theming/lib/Util.php
> +		$appPath = \OC_App::getAppPath($app);
@LukasReschke So adding getAppPath to IAppManager for that would be fine? Then I could add this in a seperate PR.

2016-11-05 19:21 UTC, juliushaertl commented
@LukasReschke Thanks again for the comments, those should be all fixed except for the injection stuff in URLGenerator.php and the private API call.

2016-11-16 13:11 UTC, juliushaertl commented
@rullzer @LukasReschke Would be great if you could comment on the following two:
https://github.com/nextcloud/server/pull/840#discussion_r86531269
https://github.com/nextcloud/server/pull/840#discussion_r86529463

2016-11-16 17:56 UTC, rullzer commented on lib/private/URLGenerator.php
> +		if(\OCP\App::isEnabled('theming') && $image === "favicon.ico" && \OC::$server->getThemingDefaults()->shouldReplaceIcons()) {
Ah crap indeed. Yeah this is because we do dark magic with the dark themeing magic. nothing to fix here I think.

2016-11-16 17:57 UTC, rullzer commented on apps/theming/lib/Util.php
> +		$appPath = \OC_App::getAppPath($app);
Separate PR is good. I guess no way around that.

But I think @LukasReschke is more concerend with that it can return `false`. So please check for that.

2016-11-18 10:53 UTC, juliushaertl commented
@rullzer @LukasReschke @nextcloud/theming Changes are in. Ready for another review.

2016-11-18 14:35 UTC, merged

2016-11-18 14:35 UTC, MorrisJobke commented
:+1:

2016-11-18 14:37 UTC, jancborchardt commented
Good stuff @juliushaertl :) as always

2016-11-18 14:43 UTC, juliushaertl commented
:tada:

@jancborchardt Thanks. I'm always glad to help. :wink: