Descend into newly created folder by clicking enter again
nextcloud/server pull request #8452
Opened 2018-02-20 13:18 UTC by sagorika1996

Fixes #1905

2018-02-21 08:04 UTC, MorrisJobke commented
cc @nextcloud/javascript

2018-02-26 15:08 UTC, juliusknorr requested changes
You can make the code a bit simpler, see the inline comments. Seems a bit of a hacky solution to me, but works. :wink:

2018-02-26 15:08 UTC, juliushaertl commented on apps/files/js/filelist.js
> +					$("#fileList tr").each(function(index) {
Just using `$('#fileList tr').removeClass('mouseOver');` should be enough here.

2018-02-26 15:38 UTC, ChristophWurst commented on apps/files/js/filelist.js
> +						if ($(this).hasClass("mouseOver")) {
I guess it's fine to just call `.removeClass`

2018-03-02 13:33 UTC, juliusknorr approved these changes

2018-03-05 10:31 UTC, MorrisJobke commented
CI failure is unrelated.

2018-03-05 14:36 UTC, MorrisJobke commented
For me this does nothing except adding CSS classes obviously. Tested in Safari.

2018-03-11 15:54 UTC, sagorika1996 commented
![awesomescreenshot-2018-03-11t15-44-23-853z](https://user-images.githubusercontent.com/20087782/37255433-58a7923c-2572-11e8-8fd6-c5e0233cb7fe.gif)

@MorrisJobke That's odd, its working fine in Chrome.

2018-03-20 10:39 UTC, sagorika1996 commented
@MorrisJobke @juliushaertl @skjnldsv ping

2018-03-20 10:50 UTC, skjnldsv commented
Looking at the code, I'm with @MorrisJobke, I don't see how that could work. What triggers the change?
Do we have an auto-focus on the folder's name link?

2018-03-20 13:26 UTC, sagorika1996 commented
When enter key is pressed, click action is triggered on the file which has the mouseOver class
https://github.com/nextcloud/server/blob/64feb3f3912f0976bb028f5d56a6434c55085925/apps/files/js/keyboardshortcuts.js#L101-L108

2018-04-11 15:56 UTC, MorrisJobke approved these changes
Tested and works 🙈

2018-04-11 15:58 UTC, merged