theming: handle not being in the serverroot
nextcloud/server pull request #8463
Opened 2018-02-21 06:52 UTC by kyrofa

Currently, the theming app assumes it's in the serverroot. However, with Nextcloud's flexibility regarding configurable app paths, this is not a safe assumption to make. If it happens to be an incorrect assumption, the theming app fails to work.

Instead of relying on the serverroot, this PR fixes #8462 by simply using the app path from the AppManager and utilizing relative paths for assets from there. Note that, in order to make this testable, the ability to inject an `IAppManager` to the `ThemingController` was added.

As this has been broken since v12, a backport to both stable13 and stable12 would be great (happy to do the legwork if given the okay).

2018-02-21 09:52 UTC, juliusknorr requested changes
Looks good besides one minor comment.

2018-02-21 09:52 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
There should be no need for such a check. The AppManager will be injected automatically.

2018-02-21 09:52 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		$appPath = $this->appManager->getAppPath('theming');
:see_no_evil: :+1:

2018-02-21 15:11 UTC, kyrofa commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
Well, only in [this test case](https://github.com/nextcloud/server/pull/8463/files#diff-60ef3451b737acfb4dc0ecc3f6645921R845), right? If it's not injected (like the other test cases, or in typical usage) it should default back to the server's app manager. Perhaps I misunderstand?

2018-02-21 15:12 UTC, kyrofa commented
(Note that the test failure here seems unrelated.)

2018-02-23 07:47 UTC, kyrofa commented
I'd very much like to backport this for 12.0.6 and 13.0.1!

2018-02-23 09:42 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
The mock should just be added to the controller here: https://github.com/kyrofa/server/blob/a1f18241166f335b89a6cf3d002efd3d825fde19/apps/theming/tests/Controller/ThemingControllerTest.php#L109

Then of course the method need to be configured  to the other tests as well.

2018-02-23 15:21 UTC, kyrofa commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
Sure, I can do that, although we'll still need the null check for the real system. Is that okay, or would you prefer to see this parameter become non-optional and have all the callers modified to pass it in?

2018-02-24 16:18 UTC, kyrofa commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
Updated the tests to add the mock in setUp.

2018-02-25 09:35 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
Ok, great. Then you can get rid of the is_null check since the appManager will be injected automatically, just like the other constructor arguments. So it will always be `\OC::$server->getAppManager()` except for the tests where we call the constructor ourselfs and it will be mocked then.

2018-02-26 10:35 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
You can read more about the dependency injection here: https://docs.nextcloud.com/server/13/developer_manual/app/container.html#how-does-automatic-assembly-work

This is basically where the "magic" happens: :wink: 
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/AppFramework/Utility/SimpleContainer.php#L50

2018-02-26 10:50 UTC, juliusknorr approved these changes

2018-02-26 17:11 UTC, skjnldsv approved these changes

2018-02-26 17:24 UTC, kyrofa commented on apps/theming/lib/Controller/ThemingController.php
> +		if (!is_null($appManager)) {
Ahhh and the puzzle pieces come together! Thank you for helping me understand this :) .

2018-02-26 17:27 UTC, merged

2018-02-26 17:30 UTC, kyrofa commented
Thanks folks. Can I get a yea/nay on backporting to stable{12,13}? Happy to propose.

2018-02-26 22:41 UTC, kyrofa commented
Backport PRs are up:

- #8549 for v12
- #8554 for v13