Update ThemingController.php
nextcloud/server pull request #8633
Opened 2018-03-02 16:46 UTC by rakekniven

Improved translation string.
Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/121491256?issue=yes

2018-03-03 14:09 UTC, juliusknorr approved these changes

2018-03-03 15:27 UTC, rakekniven commented
Tests are fixed.

2018-03-05 08:02 UTC, rullzer commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +						message = t('user_ldap', objectsFound + 'Entries available within the provided Base DN');
This looks weird. We probably should just include the number as parameter.

2018-03-05 10:18 UTC, rakekniven commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +						message = t('user_ldap', objectsFound + 'Entries available within the provided Base DN');
@rullzer Should I open separate issue regarding overwork of the code?

2018-03-05 12:02 UTC, rullzer commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +						message = t('user_ldap', objectsFound + 'Entries available within the provided Base DN');
Nah let me fix it on the branch

2018-03-05 12:05 UTC, rullzer commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +						message = t('user_ldap', objectsFound + 'Entries available within the provided Base DN');
Done

2018-03-05 12:06 UTC, rullzer approved these changes

2018-03-05 15:06 UTC, MorrisJobke requested changes

2018-03-05 15:06 UTC, MorrisJobke commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +							objectsFound: objectsFound
This should be moved to the plural translation function.

2018-03-09 18:32 UTC, rakekniven commented
Made a mistake, My last commit (https://github.com/nextcloud/server/pull/8633/commits/1c441e23241f2f0cca80c705ef07f837cb04b5ff) to my branch should not be included in this PR.
Should be separate one.

2018-03-10 12:00 UTC, rullzer commented on apps/user_ldap/js/wizard/wizardTabElementary.js
> +							objectsFound: objectsFound
fair enough. fixed.

2018-03-10 12:00 UTC, rullzer commented
@rakekniven removed your commit

2018-03-11 18:31 UTC, MorrisJobke approved these changes

2018-03-11 18:33 UTC, merged