Exclude file name patterns; ignore gentoo webapp files
nextcloud/server pull request #8647
Opened 2018-03-05 08:30 UTC by LeCoyote

Issue #3112

2018-03-05 09:54 UTC, nickvergessen requested changes

2018-03-05 09:54 UTC, nickvergessen commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +			['.webapp-owncloud-obee', false],
The regex uses nextcloud and a version number

2018-03-05 10:26 UTC, LeCoyote commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +			['.webapp-owncloud-obee', false],
Ah yeah, forgot about that. Fixed now.

2018-03-05 11:46 UTC, nickvergessen commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +		$this->filter = $this->getMockBuilder(ExcludeFileByNameFilterIterator::class)
Btw you can use `createMock()` here too

2018-03-05 11:47 UTC, nickvergessen commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +	/** @var ExcludeFileByNameFilterIterator */
Use 
`/** @var ExcludeFileByNameFilterIterator|\PHPUnit_Framework_MockObject_MockObject */`
so phpstorm doesn't complain later in the code

2018-03-05 12:07 UTC, LeCoyote commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +	/** @var ExcludeFileByNameFilterIterator */
I'm not at all familiar with phpstorm or any of the NextCloud internals and test units. Initially I simply copied a trivial commit over from OwnCloud so that Gentoo users could enjoy NextCloud *AND* Portage together. As a result, in spite of your comments, I'm afraid I don't know how to improve this PR. Sorry.

2018-03-05 12:11 UTC, LeCoyote commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +		$this->filter = $this->getMockBuilder(ExcludeFileByNameFilterIterator::class)
I'm sorry but I have no idea how or what you mean.

2018-03-05 12:12 UTC, nickvergessen approved these changes
No problem, it's fine

2018-05-23 16:31 UTC, rullzer commented
@LeCoyote could you address the comments from @nickvergessen 

We also require your commits to be signed off

2018-10-03 13:06 UTC, ChristophWurst commented
> @LeCoyote could you address the comments from @nickvergessen
> 
> We also require your commits to be signed off

@LeCoyote :ping_pong:

2018-10-03 18:40 UTC, LeCoyote commented
Done.

2019-01-28 16:50 UTC, ChristophWurst approved these changes
Fine by me. Code looks good :+1:

2019-01-28 16:51 UTC, ChristophWurst commented
@LeCoyote could you please rebase this onto the current master? Than we can check if CI is happy and finally merge this. Thank you!

2019-01-28 17:06 UTC, MorrisJobke commented
I rebased it - let's see 🕐

2019-01-29 10:07 UTC, MorrisJobke commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +		$this->filter->method('isDir')
PHPUnit fails:

```
1) Test\IntegrityCheck\Iterator\ExcludeFileByNameFilterIteratorTest::testAcceptForFiles with data set #0 ('a file', true)
Trying to configure method "isDir" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

I can have a look at this later. Or if anybody else wants to look into this: feel free.

2019-01-29 10:42 UTC, danielkesselberg commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +		$this->filter->method('isDir')
`$iteratorMock->method('isDir')` isDir is part of (Recursive)DirectoryIterator and not RecursiveFilterIterator.

2019-01-29 10:46 UTC, danielkesselberg commented on tests/lib/IntegrityCheck/Iterator/ExcludeFileByNameFilterIteratorTest.php
> +		$this->filter->method('isDir')
https://github.com/owncloud/core/commit/99e0a5a57ec4f840171235594078782f2629b470#diff-78f0d6c7f47812cd19a1806a1c2ff241

2019-02-14 10:44 UTC, danielkesselberg commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		'/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
Does not match `.webapp-netxcloud-12.0.5`

2019-02-14 10:56 UTC, nickvergessen commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		'/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
RIght, that's expected, but it also does not match `.webapp-nextcloud-12.0.5` which is unexpected.

2019-02-14 10:57 UTC, nickvergessen commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		'/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
```suggestion
		'/^\.webapp-nextcloud-(\d+\.){2}(\d+)(-r\d+)?$/', // Gentoo/Funtoo & derivatives use a tool known as webapp-config to manage wep-apps.
```

2019-02-25 23:17 UTC, closed without merging