Better debugging for "Your test case is not allowed to access the dat…
nextcloud/server pull request #8662
Opened 2018-03-05 15:11 UTC by nickvergessen

…abase."

Ref https://help.nextcloud.com/t/integration-test-failure/28383

### before
```
There was 1 error:

1) OCA\FocusFrog\Tests\Integration\Controller\TaskIntegrationTest::testUpdate
OCP\AppFramework\QueryException: Could not resolve service! Class service does not exist

/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:108
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:123
/home/nickv/Nextcloud/13/server/lib/private/ServerContainer.php:132
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:441
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:79
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:102
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:123
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:467
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:438
/home/nickv/Nextcloud/13/server/appstank/focusfrog/tests/Integration/Controller/TaskIntegrationTest.php:30

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
```

### before
```
There was 1 failure:

1) OCA\FocusFrog\Tests\Integration\Controller\TaskIntegrationTest::testUpdate
Your test case is not allowed to access the database.

/home/nickv/Nextcloud/13/server/tests/lib/TestCase.php:142
/home/nickv/Nextcloud/13/server/3rdparty/pimple/pimple/src/Pimple/Container.php:113
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:123
/home/nickv/Nextcloud/13/server/lib/private/ServerContainer.php:132
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:441
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:68
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:104
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:125
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:467
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:438
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:68
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:104
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:125
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:467
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:438
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:68
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:104
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/Utility/SimpleContainer.php:125
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:467
/home/nickv/Nextcloud/13/server/lib/private/AppFramework/DependencyInjection/DIContainer.php:438
/home/nickv/Nextcloud/13/server/appstank/focusfrog/tests/Integration/Controller/TaskIntegrationTest.php:30

FAILURES!
Tests: 2, Assertions: 1, Failures: 1.

```

2018-03-05 15:13 UTC, nickvergessen commented on lib/private/AppFramework/Utility/SimpleContainer.php
> +						$e instanceof \PHPUnit_Framework_AssertionFailedError) {
don't like this too much, I first tried to do it for `resolveName =IDBConnection  but then it get's lost on nested dependendies...
So this is the only way we can do it.

2018-03-05 15:41 UTC, MorrisJobke approved these changes
I don't fully like it, but it seems to be the only way to accomplish this kind of nested DI container query detection :/

2018-03-05 18:35 UTC, rullzer approved these changes

2018-03-05 18:36 UTC, rullzer requested changes
Phan is not happy with this....

2018-03-05 19:15 UTC, nickvergessen commented
Undeclared class, yeah that's why it is in class_exists.... Maybe denying autoload helps, but i dont think phan is so clever...

2018-03-06 21:22 UTC, MorrisJobke commented
> Phan is not happy with this....

Still not happy :(

lib/private/AppFramework/Utility/SimpleContainer.php:71 PhanUndeclaredClassInstanceof Checking instanceof against undeclared class \PHPUnit_Framework_AssertionFailedError

2018-03-06 21:22 UTC, MorrisJobke commented
> Still not happy :(

Maybe put it in one line instead of two?

2018-03-07 15:50 UTC, nickvergessen commented
Right, reported at https://github.com/phan/phan/issues/1543

And fixed it by moving the suppress to the method docs.

2018-03-07 15:52 UTC, MorrisJobke approved these changes

2018-03-07 20:53 UTC, rullzer approved these changes

2018-03-07 20:53 UTC, merged