disable part files for object stores
nextcloud/server pull request #8715
Opened 2018-03-07 12:36 UTC by icewind1991

Renaming the part file to the target file while preserving fileids can't be done for object stores without issues.

To test

- upload a new file to s3 object store
- check the fileid
- overwrite the file with dav upload
- check the fileid again

2018-03-07 13:56 UTC, MorrisJobke approved these changes

2018-03-08 08:04 UTC, rullzer requested changes
This needs more work.

If I checkout this branch we directly create a new version on upload.

2018-03-08 12:08 UTC, icewind1991 commented
@rullzer fixed

(this probably also was an issue when using s2s sharing)

2018-03-08 19:51 UTC, rullzer approved these changes
Seems to do the trick!

2018-03-08 19:52 UTC, merged