Pass on the return value of file_put_content
nextcloud/server pull request #8737
Opened 2018-03-08 20:59 UTC by rullzer

This will help with AppData hardening etc

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-03-09 13:42 UTC, icewind1991 requested changes
An exception should be thrown when it returns false instead

2018-03-12 20:56 UTC, rullzer commented
@icewind1991 any suggestions for which exception to use?

2018-03-15 13:24 UTC, icewind1991 commented
You can only use something generic here since we dont know the failure cause, not sure what would be best though

2018-03-26 20:54 UTC, rullzer commented
@icewind1991 ok added an exception.

I introduced the `GenericFileException` (fancy name I know). Maybe we should use this in case nothing specific matches? ALso we could base all othe file exceptions on it. Just so there is more of a hierarchy there.

2018-03-27 12:06 UTC, icewind1991 requested changes

2018-03-27 12:06 UTC, icewind1991 commented on lib/private/Files/Node/File.php
> +			if ($this->view->file_put_contents($this->path, $data)) {
missing a `!` :see_no_evil:

2018-03-27 12:10 UTC, rullzer commented on lib/private/Files/Node/File.php
> +			if ($this->view->file_put_contents($this->path, $data)) {
fixed...

2018-03-27 12:33 UTC, icewind1991 approved these changes

2018-03-27 14:11 UTC, nickvergessen approved these changes

2018-03-27 18:56 UTC, juliusknorr approved these changes

2018-03-28 06:25 UTC, merged