Remove unused methods of OC_Response
nextcloud/server pull request #8792
Opened 2018-03-12 17:43 UTC by MorrisJobke

Ref #8375 and #7827

2018-03-12 17:45 UTC, ChristophWurst requested changes
Looks good otherwise

2018-03-12 17:45 UTC, ChristophWurst commented on apps/files_sharing/public.php
> +	if ($protocol == 'HTTP/1.1') {
`===`?

2018-03-12 17:46 UTC, MorrisJobke commented on apps/files_sharing/public.php
> +	if ($protocol == 'HTTP/1.1') {
Just a copy paste and should be replaced soon anyways.

2018-03-12 17:54 UTC, ChristophWurst approved these changes

2018-03-13 06:05 UTC, skjnldsv commented on apps/files_sharing/public.php
> +		$status = '304 Found';
304 Not Modified is the proper code?

2018-03-13 06:05 UTC, skjnldsv commented on apps/files_sharing/public.php
> +		$status = '304 Found';
Or 302 Found? :)

2018-03-13 08:41 UTC, rullzer commented
HTTP 1.0 support needs to die anyway. 1.1 was release in 1997

2018-03-13 08:42 UTC, rullzer approved these changes

2018-03-13 08:43 UTC, skjnldsv commented
Cant we return HTTP 418 instead? :D

2018-03-13 08:47 UTC, merged