Vue migration: settings
nextcloud/server pull request #8824
Opened 2018-03-14 15:55 UTC by skjnldsv

Settings
- [ ] Design + base
- [ ] Quota
- [ ] Groups management
- [ ] Subadmins management
- [ ] User disablement
- [ ] User deletion
- [ ] Props edition (email, 

Components see #7738 
- [ ] Popovermenu v1
- [ ] AppNavigation v1

2018-03-16 13:53 UTC, MorrisJobke commented on settings/README.md
> +npm run build
Makefile please ... see `apps/updaternotifications` 😉

2018-03-16 13:58 UTC, skjnldsv commented on settings/README.md
> +npm run build
I'll implement it once done :)

2018-03-16 14:06 UTC, nickvergessen commented on settings/users.php
> +	'name' => 'Disabled users',
translate?!

2018-04-13 15:07 UTC, nickvergessen commented
- [ ] Loading icon/state for the items-list

2018-04-18 12:54 UTC, nickvergessen commented on settings/src/components/appNavigation/navigationItem.vue
> +		showMen() {
?

2018-04-18 13:31 UTC, skjnldsv commented on settings/src/components/appNavigation/navigationItem.vue
> +		showMen() {
Error indeed

2018-05-10 14:09 UTC, skjnldsv commented
Okay everyone, this is ready for review!
This is unfortunately a pretty big PR, because I cleaned a lot of old legacy stuff. Please don't be afraid! <3

@nextcloud/designers 

What to test:
- Addition/removal of users
- Addition/removal of groups
- Quota change
- Default quota change
- Password/displayname/email changes
- Groups/subadmins edition
- Custom quotas set/unset
- Group change on the app navigation
- Load the page with http://xxxx/index.php/xxx and without `index.php`
- Language change on users
- Password policy min length requirements

2018-05-10 14:33 UTC, juliushaertl commented
Really nice so far, just a few things from having a first try, i'll have a more detailed look tomorrow:

- When index.php is required for the URL the router doesn't seem to add it when clicking on groups in the navigation sidebar
- Clicking the 3-dots menu in the user list for the second time doesn't close the popover again
- The delete button for groups should be hidden by default in my opinion and just be shown on hover (or maybe as it was before just if you selected the group)
- A bit more space between the columns would be good for when inputs are besides plain text 
![image](https://user-images.githubusercontent.com/3404133/39874922-72f6d324-546f-11e8-82ff-42614cd6b2b5.png)
- The group multiselect input should have a pointer cursor to indicate that it is clickable
- Text fields and multiselect fields should have the same height
![image](https://user-images.githubusercontent.com/3404133/39874969-9ea58f9c-546f-11e8-86ea-2bb7edbe2f06.png)
- When clicking the new user button, the first input field should be focused

2018-05-10 14:38 UTC, skjnldsv commented
> The delete button for groups should be hidden by default in my opinion and just be shown on hover (or maybe as it was before just if you selected the group)

I'm not sure on this. I agree that it looks strange, but it's also a bad UX for users, like you don't know where you can delete the group. We could try something else tough, but I don't have any idea on this atm :(

Thanks for your review, I'll fix this asap :heart:

2018-05-11 05:48 UTC, juliushaertl commented on settings/src/router.js
> +	base: window.location.pathname.indexOf('index.php') > 0 ? '/index.php/' : '/',
I think that would still break when installed into a subdirectory. Can we just use `OC.generateUrl('')`?

2018-05-11 05:49 UTC, skjnldsv commented on settings/src/router.js
> +	base: window.location.pathname.indexOf('index.php') > 0 ? '/index.php/' : '/',
Good call. I need to determine the base url yes :)

2018-05-11 11:06 UTC, juliusknorr requested changes

2018-05-11 11:07 UTC, juliusknorr submitted a review, later dismissed
Looks good code wise, just two bugs with groups management found.

2018-05-11 11:09 UTC, juliushaertl commented
Two other issues with groups:
- [ ] Add a user while you are viewing a group list -> User is added without a group, imo we should prefill the group list with the current group there
- [ ] If you unassign a user from the group you are currently viewing it should be removed from the list

2018-05-14 07:39 UTC, skjnldsv commented on lib/private/L10N/Factory.php
> +	public function getLanguages() {
For the sanity of reviewers, I guess tests for this will come later ^^

2018-05-14 08:28 UTC, MorrisJobke commented
> We switched to a grid design, no more ugly table

How does it look in IE?

2018-05-14 09:47 UTC, skjnldsv commented
> How does it look in IE?

Descent for ie11!
Some center align issues, but nothing terrible. I added a config for ie polyfills. 
In the end we should really drop ie11!

2018-05-15 10:29 UTC, michag86 commented
Hi,
thanks for the work on the user management!

I have tested it and found some issues:
- [ ] Groups with long names are cut off in the group selection of the user.
- [ ] It would be nice if the results are sortable
- [ ] Problems for subadmins (/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/password_policy/minLength) results in error 997 "Logged in user must be an admin"
- [ ] If subadmin trys to create a user without selecting a group, the spinner is spinning for ever. 
- [ ] Subadmin can see the subadmin permissions and can try to change subadmin permissions. Maybe this should be hidden, hideable or read only for subadmins?
- [ ] User count for everyone (as subadmin) is not the count of the subadmin scope. Instead it represents all users.
- [ ] Subadmins can try to create a group and the spinner is spinning for ever.

2018-05-15 14:03 UTC, skjnldsv commented
> - It would be nice if the results are sortable

Maybe in a future pr :)

> - Problems for subadmins (/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/password_policy/minLength) results in error 997 "Logged in user must be an admin"

Have to be fixed in the policy app: https://github.com/nextcloud/password_policy

2018-05-18 06:05 UTC, skjnldsv commented
@nextcloud/designers bump :)

2018-05-18 14:58 UTC, skjnldsv commented
@michag86 small push to update the width of the groups list
Also: added a tooltip to show the full list on hover: 
![capture d ecran_2018-05-18_16-58-20](https://user-images.githubusercontent.com/14975046/40242003-af2ce24a-5abc-11e8-9755-64b9a32f725c.png)

2018-05-22 22:31 UTC, MorrisJobke approved these changes
Tested and works a lot better than before - some minor things for Edge and IE, but this is stuff for later 👍

2018-05-22 22:32 UTC, rullzer approved these changes
:elephant:

2018-05-22 22:32 UTC, merged

2018-05-23 06:40 UTC, danopz commented
Will the components be pushed to [nextcloud/vue-components](https://github.com/nextcloud/vue-components)?

2018-05-23 06:48 UTC, skjnldsv commented
@danopz very soon yes :)