Update ThemingController.php
nextcloud/server pull request #8861
Opened 2018-03-16 17:45 UTC by rakekniven

Changed wording according to discussion at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/121491259?issue=yes
Aligned ending of error messages

2018-03-16 19:52 UTC, MorrisJobke approved these changes

2018-03-16 21:36 UTC, rullzer approved these changes

2018-03-16 21:36 UTC, comradekingu commented on apps/theming/lib/Controller/ThemingController.php
> +			UPLOAD_ERR_CANT_WRITE => $this->l10n->t('Failed to write file to disk'),
The most commonly used convention in NC is:
"Could not write file to disk"

2018-03-19 09:30 UTC, juliushaertl commented on apps/theming/lib/Controller/ThemingController.php
> +			UPLOAD_ERR_CANT_WRITE => $this->l10n->t('Failed to write file to disk'),
@rakekniven Can you adjust that as well?

2018-03-19 13:51 UTC, nickvergessen commented
Test fails:
> OCA\Theming\Tests\Controller\ThemingControllerTest

2018-03-19 14:01 UTC, nickvergessen requested changes
Tests

2018-03-20 12:45 UTC, nickvergessen approved these changes

2018-03-20 12:45 UTC, merged