Move constants required by UserInterface into interface definition
nextcloud/server pull request #8896
Opened 2018-03-20 10:16 UTC by klada

The constants which need to be checked in `implementsActions` formerly
resided in the private \OC\User\Backend class. Since they need to be
accessed in apps they should actually reside in the public interface.

Closes #8895

2018-03-20 18:14 UTC, MorrisJobke commented on lib/public/UserInterface.php
> +	 * actions that user backends can define
Please add a `@since 14.0.0` tag so everybody knows when this was added and with what version it could be used.

2018-03-20 18:19 UTC, MorrisJobke commented
I still don't like the overall approach of how we implemented the user backends. I have in mind, that we discussed a bit more about distinct user backend interfaces for all of those constants. Something like `SetUserNameInterface` and then the interfaces defines that there is a `setUserName` method and you implement one or many of those interfaces. In this way we properly utilize language features instead of reimplementing what the language construct "interface" already provides.

As short term solution this still is okay, but we maybe should think about how to make it properly maintainable. ;)

2018-03-21 07:34 UTC, klada commented
As I pointed out in #8895 this is just a suggestion. Of course I am not in the position to decide which interface is supposed to be public or not, but let me explain my motivation:

I have written my own user backend which implements these public interfaces. Whenever I look at the code I feel quite good about the fact that I am only using public interfaces. There is only one place where the `UserBackend` interface forces me to access the private Nextcloud API (when I need to check against these constants). This always makes me think that my code can break any time soon and right now there is no way around that. And this also applies to `user_ldap` and `user_saml`.

And I also agree that the current situation with the user backend stuff is far from optimal at the moment. That's why I also suggested in #8895 that another approach could be to provide a **public** abstract user backend class instead of just the interface definitions. More code from `\OC\User\Backend` could then be reused by existing backends (such as `implementsActions` which would remove the need to add these constants to the public interface). But that would certainly require more code reorganization.

2018-03-21 08:23 UTC, nickvergessen approved these changes

2018-03-21 08:38 UTC, klada commented on lib/public/UserInterface.php
> +	 * compared with CREATE_USER etc.
@nickvergessen You are right, I have updated the comment and rebased my PR in order to keep the number of commits down.

2018-03-21 09:11 UTC, MorrisJobke approved these changes

2018-03-21 09:11 UTC, MorrisJobke commented
Let's wait for CI.

2018-03-21 09:17 UTC, MorrisJobke commented
Had a chat with @rullzer on IRC and it would maybe make sense to move the dedicated interfaces approach forward. Because this then would be a clean approach to tackle the underlying problem.

2018-03-21 09:24 UTC, MorrisJobke commented
@klada Let's leave this open for some days and we will look into how easy it is to go the proper way.

2018-03-21 09:24 UTC, MorrisJobke approved these changes
Blocking. See my previous comment.

2018-03-21 12:29 UTC, MorrisJobke requested changes
Blocking 😉

2018-03-22 08:21 UTC, rullzer commented
See https://github.com/nextcloud/server/pull/8935

2018-03-22 09:55 UTC, rullzer commented
Ok lets close this then and continue in #8935

2018-03-22 09:55 UTC, closed without merging