More whitespace: Increase header height from 45px to 50
nextcloud/server pull request #9002
Opened 2018-03-27 13:50 UTC by jancborchardt

As talked about with @karlitschek @nextcloud/designers 

@juliushaertl @skjnldsv there’s some issues with the Contacts menu and on mobile. Since you recently worked on those parts, do you have a clue? I played around a bit but there seem to be some mobile rules also which override things.

2018-03-27 13:58 UTC, juliushaertl commented
I'll look into the menu issues.

2018-03-27 14:03 UTC, skjnldsv submitted a review, later dismissed

2018-03-27 14:03 UTC, skjnldsv commented on core/css/header.scss
> +				height: 100%;
Wont work since parents (div/for) don't have a height set, that's why we used a 44px :)

2018-03-27 14:03 UTC, skjnldsv commented on core/css/header.scss
> +				padding-right: 12px;
Why adding this?

2018-03-27 14:03 UTC, skjnldsv commented on core/css/styles.scss
> +			width: 30px;
![capture d ecran_2018-03-27_16-03-27](https://user-images.githubusercontent.com/14975046/37972337-69c154fa-31d8-11e8-8853-c27e8f443ad1.png)
Too wide and not centered :)

2018-03-27 19:51 UTC, jancborchardt commented on core/css/header.scss
> +				padding-right: 12px;
Before there was a margin-right: 13px; on the parent element, so this is actually 1px less now. :) I changed it to padding so that the right part of the header is still clickable to open the user menu.

2018-03-27 19:54 UTC, skjnldsv commented on core/css/header.scss
> +				padding-right: 12px;
It was on the settings only if I recall correctly :)

2018-03-27 20:09 UTC, jancborchardt commented on core/css/header.scss
> +				padding-right: 12px;
Aaaah, right, now I get it. :) You are right, it should only be added to the settings element of course. Will fix. :)

2018-03-28 08:02 UTC, karlitschek commented
👍

2018-03-28 08:48 UTC, juliushaertl commented
I've pushed some fixes for the popover menus and app menu.

2018-03-28 08:48 UTC, juliushaertl commented on core/css/styles.scss
> +			width: 30px;
Fixed that as well.

2018-03-28 08:54 UTC, skjnldsv commented on core/css/header.scss
> +		padding-right: 12px;
~~Leaving the right margin/padding on `#settings` allows us to get rid of custom rule in line 411. :)~~
Okay, it's because of the click handler. Makes sense then.

2018-03-28 08:57 UTC, skjnldsv requested changes

2018-03-28 08:57 UTC, skjnldsv commented on core/css/mobile.scss
>  		max-width: calc(100vw - 26px);
We still need to set the left distance here as well, since we reduced the right margin from 13 to 5 :)

2018-03-28 08:59 UTC, skjnldsv submitted a review, later dismissed
![capture d ecran_2018-03-28_10-57-32](https://user-images.githubusercontent.com/14975046/38019099-ffbcab82-3276-11e8-8551-7029a3144510.png)

Arrow on mobile is having issue as well :)

2018-04-05 12:20 UTC, MorrisJobke approved these changes

2018-04-07 19:56 UTC, jancborchardt commented
Changes seem good to me too. What’s the build failure? And @skjnldsv can you recheck?

2018-04-07 21:39 UTC, skjnldsv commented
I'm fine with the global price if @juliushaertl fixed the issues I found :)

2018-04-09 10:41 UTC, MorrisJobke commented
> Changes seem good to me too. What’s the build failure? And @skjnldsv can you recheck?

Unrelated.

2018-04-10 07:57 UTC, juliushaertl commented
@skjnldsv Yes, I fixed the issues you've mentioned. Please have another look for review, so we can get this in :wink:

2018-04-10 09:35 UTC, skjnldsv commented on core/css/mobile.scss
>  		max-width: calc(100vw - 26px);
Still an issue :)
![dev skjnldsv com_8443_settings_users 1](https://user-images.githubusercontent.com/14975046/38548918-3f4d894c-3cb3-11e8-9f77-5699b9a155cb.png)

2018-04-10 09:37 UTC, skjnldsv requested changes

2018-04-10 09:37 UTC, skjnldsv commented on core/css/mobile.scss
>  		max-width: calc(100vw - 26px);
Still an issue :)
![dev skjnldsv com_8443_settings_users 1](https://user-images.githubusercontent.com/14975046/38548918-3f4d894c-3cb3-11e8-9f77-5699b9a155cb.png)

2018-04-10 19:39 UTC, skjnldsv approved these changes

2018-04-10 21:05 UTC, merged

2018-04-10 21:05 UTC, jancborchardt commented
Nice! :)

2018-04-11 06:46 UTC, skjnldsv commented
:tada: