Add appdata_path option to store appdata locally outside primary storage.
nextcloud/server pull request #9247
Opened 2018-04-19 13:19 UTC by UncleAlbie

Problem: Appdata are stored in primary storage. That means that (mostly even partial) unavailability of object storage (ex. S3) as primary storage causes Nextcloud web client to be unavailable as well.

Solution: Local directory is mounted to /appdata.local when 'appdata_path' is set in the configuration file.

Signed-off-by: Patrik Novotný patrik.novotny@gmx.com

2018-04-19 15:39 UTC, MorrisJobke commented
cc @icewind1991 @rullzer @schiessle 

I would say that this makes it hard to get up and running in a clustered environment. But I get the point that the CSS would be good to be served from the server in case of problems.

The case is similar to #5789

2018-04-19 15:39 UTC, MorrisJobke commented
cc @juliushaertl

2018-04-25 09:51 UTC, icewind1991 commented on lib/private/Files/AppData/AppData.php
> +				$name = '/appdata.local/appdata_' . $instanceId;
There is no need to have the separate `/appdata.local/` just having the mount provider mount the `appdata_path` into `/appdata_$instanceId` should be sufficient

2018-04-25 09:52 UTC, icewind1991 requested changes

2018-04-25 09:52 UTC, icewind1991 commented on lib/private/Files/AppData/AppData.php
> +				$name = '/appdata.local/appdata_' . $instanceId;
There is no need to have the separate `/appdata.local/` just having the mount provider mount the `appdata_path` into `/appdata_$instanceId` should be sufficient

2018-05-14 19:34 UTC, rullzer commented
I get the point. But this won't scale to well.

Appdat also holds the previews.
And soon it might also hold the versions.

So you'd need significant space on your device.
Also the cleanup of stuff then won't help if your main storage runs out of space etc.

2018-05-14 22:28 UTC, icewind1991 commented
Might be worth it to instead have a generalized system to have different appdata paths locally.

Things like previews and bundled css/js can be useful to have separate from the main data still

2018-09-28 16:04 UTC, faberto commented
> 
> 
> I get the point. But this won't scale to well.
> 
> Appdat also holds the previews.
> And soon it might also hold the versions.
> 
> So you'd need significant space on your device.
> Also the cleanup of stuff then won't help if your main storage runs out of space etc.

Would be nice to have the option to adjust the path to the preview folder in the settings file. Would make a lot of sense with external drives as having the previews on an internal drive will speed up the response time a lot. e.g. my current setup is an SSD as main disk and externals as Storage disks. Loading a lot of small files from an HDD takes long as they are most of the time not sequentially placed on the disk.

2019-10-24 12:35 UTC, ChristophWurst commented
Closing as it's unlikely that we'd integrate this change. Thanks for your effort :v:

2019-10-24 12:35 UTC, closed without merging