Do not load calendar/addressbook plugins if not needed
nextcloud/server pull request #9268
Opened 2018-04-23 07:53 UTC by rullzer

Fixes #6711
Based on https://github.com/owncloud/core/pull/30149/commits/f0fb21cf3563088284c56be4eac48c7d9725cb21

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-04-23 08:47 UTC, MorrisJobke commented
Does this also fix stuff like #8141?

2018-04-23 08:49 UTC, georgehrke commented
@MorrisJobke It should be as far as i can tell.

2018-04-23 08:50 UTC, georgehrke commented
I will check when testing this pr.

2018-04-23 08:52 UTC, rullzer commented
Yes it should

2018-04-23 10:17 UTC, MorrisJobke approved these changes
Tested, works and code makes sense 👍

2018-04-23 15:55 UTC, MorrisJobke commented
CI failure is due to a timeout :)

2018-04-25 20:15 UTC, rullzer commented
One more review please :)

2018-05-01 13:10 UTC, rullzer commented
Conflicts fixed and rebased.

2018-05-07 13:46 UTC, MorrisJobke commented
@georgehrke @blizzz @nickvergessen @ChristophWurst @skjnldsv Reviews would be nice :)

2018-05-07 15:18 UTC, blizzz requested changes
the repair step might lose valid shares when

1. Nextcloud is in maintenance mode
2. AND external user backends are used

since apps are not loaded in this context.

2018-05-08 11:07 UTC, rullzer commented
@blizzz I can drop the repair job... but then we might have invalid shares....

2018-05-09 00:16 UTC, blizzz commented
> @blizzz I can drop the repair job... but then we might have invalid shares....

Or add a switch that prevents running in maintenance mode.

2018-05-24 07:32 UTC, rullzer commented
@blizzz now they are only run if you run the expensive repair steps in case you run into it.

All our other repair steps are executed in maintenance mode so then it indeed would do :boom: in certain situations

2018-05-25 08:06 UTC, blizzz commented
> All our other repair steps are executed in maintenance mode so then it indeed would do :boom: in certain situations

Then it is better run as a seperate occ command, bound to apps, as i am afraid it would do more harm than good.

2018-05-25 09:15 UTC, rullzer commented
Nah during upgrade.

Now it is. occ maintenance:repair - - expensive

2018-05-27 19:03 UTC, rullzer commented
@blizzz ok one more time ;)

2018-05-28 09:42 UTC, blizzz approved these changes

2018-05-28 09:43 UTC, blizzz commented
looks good now, apart from tests

2018-05-28 11:52 UTC, merged

2018-05-31 15:22 UTC, MorrisJobke commented on lib/private/Repair.php
> +use OCA\DAV\Repair\RemoveInvalidShares;
<img width="382" alt="bildschirmfoto 2018-05-31 um 17 22 21" src="https://user-images.githubusercontent.com/245432/40791200-33cde280-64f7-11e8-911d-a6a15be4bdd5.png">

🙈