Move the Cache to the querybuilder
nextcloud/server pull request #9291
Opened 2018-04-24 10:43 UTC by rullzer

2018-04-24 18:04 UTC, rullzer commented
It moves already a part over. Lets do this in small steps.

2018-04-25 07:51 UTC, nickvergessen commented on lib/private/Files/Cache/Cache.php
> +		if (\is_string($file) || $file === '') {
Last part is useless, it already matches with `is_string`

2018-04-25 07:52 UTC, nickvergessen commented on lib/private/Files/Cache/Cache.php
> +			'storage_mtime', 'encrypted', 'etag', 'permissions', 'checksum')
`*` ?

2018-04-25 07:52 UTC, nickvergessen commented on lib/private/Files/Cache/Cache.php
> +		if (\is_string($file) || $file === '') {
Before it also matched null and 0, so that's actually a (intended?) behaviour change

2018-04-25 07:53 UTC, nickvergessen commented on lib/private/Files/Cache/Cache.php
> +			->where(
the indentation is killing me :dizzy_face:

2018-04-25 08:35 UTC, icewind1991 requested changes

2018-04-25 08:35 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +				$qb->expr()->eq('fileid', $qb->createNamedParameter($file))
please specify the parameter type for integers

2018-04-25 08:35 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +			$cursor->closeCursor();
there is no need to close cursors before a return

2018-04-25 08:35 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +			while($data = $cursor->fetch()) {
I believe that in the past we figured out that `fetchAll` performs better with some databases then repeated `fetch`es

2018-04-25 08:37 UTC, nickvergessen commented on lib/private/Files/Cache/Cache.php
> +			while($data = $cursor->fetch()) {
But it broke in memory usage for huge results?

2018-04-25 09:57 UTC, icewind1991 commented on lib/private/Files/Cache/Cache.php
> +			while($data = $cursor->fetch()) {
We store all entries in memory anyway here

2018-04-25 10:16 UTC, rullzer commented on lib/private/Files/Cache/Cache.php
> +			$cursor->closeCursor();
Still good practice to just always close them.

2018-04-26 20:19 UTC, closed without merging