option for a seperate audit log file
nextcloud/server pull request #9293
Opened 2018-04-24 20:15 UTC by blizzz

2018-04-25 11:25 UTC, icewind1991 submitted a review, later dismissed

2018-04-25 11:25 UTC, icewind1991 commented on lib/private/Log/Syslog.php
> +	static protected $levels = [
you can use class constant arrays with the currently supported php versions for a bit cleaner code

2018-04-25 11:25 UTC, icewind1991 commented on lib/private/Log/Syslog.php
>  		register_shutdown_function('closelog');
do this with a destructor now?

2018-04-25 11:25 UTC, icewind1991 commented on lib/private/Log.php
> +			$config = \OC::$server->getConfig();
Fairly sure switching from systemconfig to config will break yes

2018-04-25 12:36 UTC, blizzz commented on lib/private/Log.php
> +			$config = \OC::$server->getConfig();
gnah :(

2018-04-25 13:27 UTC, blizzz commented on lib/private/Log/Syslog.php
> +	static protected $levels = [
missed that one, thanks for the hint

2018-04-25 13:35 UTC, blizzz commented
✓ reverted change to IConfig in Log
✓ moved Log constants to ILogger and depracted them in Util
✓ polished Syslog a bit

2018-04-26 08:48 UTC, MorrisJobke commented
> ✓ moved Log constants to ILogger and depracted them in Util

Moved to a separate PR: #9308

2018-04-26 09:55 UTC, MorrisJobke commented
> Moved to a separate PR: #9308

Let me rebase and fix the conflicts in this PR as the other one was merged.

2018-04-26 20:27 UTC, rullzer requested changes

2018-04-26 20:27 UTC, rullzer commented on lib/private/Log/Errorlog.php
> +	public function write(string $app, $message, int $level) {
`string $message`?

2018-04-26 20:27 UTC, rullzer commented on lib/private/Server.php
> +		$this->registerAlias('LogFactory', ILogFactory::class);
Not needed

2018-04-26 20:27 UTC, rullzer commented on lib/private/Server.php
> +		return $this->query('LogFactory');
You can just query for ILogFactory::class

Or you remove this function in general and just query for the class where you need it

2018-04-26 20:27 UTC, rullzer commented on lib/private/Log/File.php
> +	public function __construct(string $path, string $fallbackPath = '', IConfig $config) {
Any reason to require IConfig over SystemConfig here? It is internal. And the systemconfig doesn't need DB stuff etc. So less change of cyclic dependencies.

2018-04-26 20:31 UTC, blizzz commented on lib/private/Log/Errorlog.php
> +	public function write(string $app, $message, int $level) {
Log takes arrays when logging exceptions :(

2018-04-26 20:33 UTC, rullzer commented on lib/private/Log/Errorlog.php
> +	public function write(string $app, $message, int $level) {
fair enough

2018-04-26 20:36 UTC, blizzz commented on lib/private/Log/File.php
> +	public function __construct(string $path, string $fallbackPath = '', IConfig $config) {
Probably i had in mind back then making to adding API for it, but went another path… anyway, using SystemConfig makes sense. I'll adapt.

2018-05-01 12:51 UTC, rullzer approved these changes

2018-05-02 14:16 UTC, MorrisJobke approved these changes
Tested and works 👍

2018-05-02 14:16 UTC, merged

2018-08-24 14:09 UTC, eniac111 commented
Hey, do you have any documentation on this?

2018-08-24 14:59 UTC, blizzz commented
@eniac111 in the description ↑ :speak_no_evil: 

 ``config:app:set admin_audit logfile --value="/var/log/nextcloud/audit.log"``

2018-08-24 15:36 UTC, MorrisJobke commented
> @eniac111 in the description ↑ 🙊

Could you add it to the documentation/manual?

2019-03-12 12:26 UTC, j-ed commented
@MorrisJobke I just stumbled over the missing documentation of the audit log function too. To be able to improve the documentation I would need some more information about this function, which is enabled by activating the **admin_audit** app.
I wonder if it is correct that only audit information (logins/logoffs) is being logged or if other applications should use it too (I also saw **"trashbin:expire"** log entries in this file)?

2019-03-12 12:35 UTC, MorrisJobke commented
> @MorrisJobke I just stumbled over the missing documentation of the audit log function too. To be able to improve the documentation I would need some more information about this function, which is enabled by activating the **admin_audit** app.

This separate log file is already used, but with this there is a way to customize the path of this file via:

```
config:app:set admin_audit logfile --value="/var/log/nextcloud/audit.log"
```



> I wonder if it is correct that only audit information (logins/logoffs) is being logged or if other applications should use it too (I also saw **"trashbin:expire"** log entries in this file)?

Only admin_audit entries are logged and we should not use settings of apps in other apps. So this then needs to be implemented in the trash bin as well.

2019-03-12 14:59 UTC, j-ed commented
@MorrisJobke I've createds the following pull request for the documentation change: https://github.com/nextcloud/documentation/pull/1300

Do I understand you correct that it is an error that **"trashbin:expire"** messages are logged in the audit.log? If yes, I would create a separate issue ticket to get that fixed:
```
{"reqId":"1qxu8bvbtOn53RyaB3S4","level":1,"time":"2019-03-12 15:56:04+01:00","remoteAddr":"","user":"--","app":"admin_audit","method":"","url":"\/nextcloud\/occ","message":"Console command executed: trashbin:expire --quiet","userAgent":"--","version":"15.0.5.3"}
```

2019-03-12 15:10 UTC, nickvergessen commented
> Do I understand you correct that it is an error that "trashbin:expire" messages are logged in the audit.log? If yes, I would create a separate issue ticket to get that fixed:

All `occ` calls are logged to the auditing and have to be. Since they allowed to disabled apps (e.g. the logging app) it would be crucial to not log that.