Federation 2.0
nextcloud/server pull request #9345
Opened 2018-04-30 10:01 UTC by schiessle

- Make Federated Sharing OCM compatible (with some small additions/modifications)
- Allow the implementation of federated calendar and contact sharing

- [ ] basic infrastructure
- [ ] receive shares over new API
- [ ] send shares over new API
- [ ] receive notifications over new API
  - [ ] permissions change
  - [ ] ask for re-share
  - [ ] share accepted
  - [ ] share declined
- [ ] send notifications over new API
  - [ ] permissions change
  - [ ] ask for re-share
  - [ ] share accepted
  - [ ] share declined

2018-06-14 11:27 UTC, icewind1991 requested changes

2018-06-25 08:47 UTC, schiessle commented on apps/cloud_federation_api/lib/AppInfo/Application.php
> +		$container->registerCapability(Capabilities::class);
most apps I checked, e.g. notifications and activity register the capabilities in the constructor. What side-effects are you referring too? I don't see a real different if I call it manually each time I instantiate the application or if it is done automatically in the constructor.

2018-06-25 08:48 UTC, schiessle commented on apps/federatedfilesharing/lib/ocm/CloudFederationProviderFiles.php
> +			error_log("new permissions: " . $ncPermissions);
removed

2018-06-25 08:48 UTC, schiessle commented on apps/cloud_federation_api/lib/Controller/RequestHandlerController.php
> +		if ($shareWith === null ||
not really an option here, because I want to be able to control the exception in case of a missing parameter.

2018-06-25 08:49 UTC, schiessle commented
@icewind1991 @rullzer @MorrisJobke @nickvergessen please test and review so that we can merge this as soon as possible

2018-06-29 12:00 UTC, rullzer commented
CI is not happy.

I gave it a quick smoke test and could share a folder.

2018-06-29 12:04 UTC, icewind1991 requested changes
Looks good otherwise

2018-06-29 12:04 UTC, icewind1991 commented on apps/federatedfilesharing/lib/Notifications.php
> +	protected function getOCMEndPoint($url) {
This seems to be partly duplicated in `CloudFederationProviderManager`

Additionally, the result here should be cached

2018-07-02 09:37 UTC, schiessle commented on apps/federatedfilesharing/lib/Notifications.php
> +	protected function getOCMEndPoint($url) {
Good catch, the method in notifications.php isn't used at all, so I removed it and added some caching to the other implementation

2018-07-03 14:31 UTC, schiessle commented
I think the failing tests can be ignored, they fail randomly and I don't see how they are connected to this PR. Looking for your final :+1: :wink:

2018-07-03 18:08 UTC, rullzer approved these changes
Huge and scarry. But seems to work. Lets do this.

2018-07-03 21:13 UTC, MorrisJobke approved these changes

2018-07-03 21:13 UTC, merged

2020-08-20 15:44 UTC, daraelmin commented
Not sur, but I think this pull request should sollve issue #1440 (Allow the implementation of federated calendar and contact sharing) and... there's a bounty on it. Maybe someone should take it.

https://www.bountysource.com/issues/37963414-federated-calendar-and-contacts-sharing-210-00

Many many many thanks to the dev for your work !
Cheers