Issue #9318: catch exceptions in SCSSCacher::resetCache()
nextcloud/server pull request #9352
Opened 2018-04-30 15:53 UTC by Cybso

Fixes hard fails when SCSSCacher::resetCache() is not able to delete a cached file, as described in issue #9318 after an upgrade from Nextcloud 13.0.0.0 to 13.0.0.2.

2018-05-02 07:25 UTC, rullzer requested changes

2018-05-02 07:25 UTC, rullzer commented on lib/private/Template/SCSSCacher.php
> +				} catch(NotPermittedException $e) {
I guess it is not the NotPermittedException that gets thrown here... (I know the phpdoc says that is what it throws). But I guess it fails on some uncatched thing deep in the code.

Better catch a bit more generic here I think

2018-05-02 07:46 UTC, Cybso commented
@rullzer Have a look at the stack trace in #9318 : Actually it is NotPermittedException that is thrown here, although I wasn't able to determine the root cause because the problem was not reproducible once the cache has been resetted. Nevertheless, other people reported the same exception in SCSSCacher::resetCache:

- https://help.nextcloud.com/t/solved-nc12-internal-server-error-after-login/13256/6
- https://help.nextcloud.com/t/manual-upgrade-nc13-failed/27938/11

2018-05-02 08:09 UTC, rullzer approved these changes
ok then lets do this!

2018-05-02 19:19 UTC, juliusknorr approved these changes

2018-05-03 07:56 UTC, merged

2018-05-03 07:57 UTC, MorrisJobke commented
@Cybso Mind to open a backport PR? Just base a branch on `stable13`, cherry-pick the commit from there onto it and then create a PR on GitHub against stable13.

2018-05-03 08:56 UTC, Cybso commented
@MorrisJobke  I tried in #9376, but I think I accidentally merged all changes in master...?!

Here's what I did:
```
git pull
git checkout stable13
git checkout -b 9318_SCSSCacher_resetCache_catch_exception_stable13
git cherry-pick -m 1 -x 0f8210792ce4bb786bed9fe09b97a4ec9f4d848e
git push origin 9318_SCSSCacher_resetCache_catch_exception_stable13
```

2018-05-03 08:59 UTC, MorrisJobke commented
@Cybso Just use the commit sha from this PR:

```
git checkpick 6270a01cab3d6cce864b8b795749598f9d65b6c3
```

That then should work ;)

2018-05-03 09:05 UTC, Cybso commented
Ok, I think I got it right, now :-)