allow to specify a link to a legal notice
nextcloud/server pull request #9437
Opened 2018-05-09 13:57 UTC by blizzz

Adds another input field to theming settings:

![screenshot_20180509_155443](https://user-images.githubusercontent.com/2184312/39818485-4d29b1f8-53a1-11e8-9d60-16844a317b96.png)

the legal notice is added to the footer:

![screenshot_20180509_155514](https://user-images.githubusercontent.com/2184312/39818506-5d66146c-53a1-11e8-9dda-eb0191efbf8b.png)

Also fixes a bug where changes to input[type=url] where not saved.

2018-05-09 19:56 UTC, jancborchardt requested changes

2018-05-09 19:56 UTC, jancborchardt commented on core/css/guest.css
> +	text-decoration: underline;
No underline on links please. We don't do that anywhere, compare to "Nextcloud" in the footer.

2018-05-09 19:56 UTC, jancborchardt commented on apps/theming/templates/settings-admin.php
> +				<span><?php p($l->t('Legal notice address')) ?></span>
"Legal notice link"

2018-05-09 20:03 UTC, blizzz commented on apps/theming/templates/settings-admin.php
> +				<span><?php p($l->t('Legal notice address')) ?></span>
Further up is also "Web address", I used this for conistency.

2018-05-09 20:04 UTC, blizzz commented on core/css/guest.css
> +	text-decoration: underline;
Actually we have a style for external links that does this: https://github.com/nextcloud/server/blob/master/core/css/styles.scss#L65-L68 I am fine with removing it however.

2018-05-09 20:06 UTC, MariusBluem commented
What about a seperate „Privacy“ link?

2018-05-10 14:38 UTC, MariusBluem commented
The `external`-app has options for positions (where login-page could be one I think). This would make it easily possible to change the link for specific languages (show it only in EU for example) and integrate it into the clients too...

However, it is working fine - THX 👍

2018-05-11 10:14 UTC, juliusknorr requested changes
Although I would prefer to have this integrated in the external sites app, since it would make the whole mechanism a lot more flexible and fit better to the concept of external sites than theming, i'd be fine to merge this to have it available quickly.

Looks good besides some small comments.

2018-05-11 10:14 UTC, juliushaertl commented on apps/theming/templates/settings-admin.php
> +				<input id="theming-imprintUrl" type="url" placeholder="<?php p($l->t('Legal notice address https://…')); ?>" value="<?php p($_['imprintUrl']) ?>" maxlength="500" />
I'd probably remove the `Legal notice address` from the placeholder, since that is duplicate to the label.

2018-05-11 10:14 UTC, juliushaertl commented on apps/theming/templates/settings-admin.php
> +				<div data-setting="imprintUrl" data-toggle="tooltip" data-original-title="<?php p($l->t('Reset to default')); ?>" class="theme-undo icon icon-history"></div>
The undo button is not working, as in not visible to the user. You probably need to add the empty default value here: https://github.com/nextcloud/server/pull/9437/files#diff-7336f3dab52c02ef94f856620590f56bR80

2018-05-11 10:17 UTC, juliushaertl commented
```
There were 4 failures:

1) OCA\Theming\Tests\Settings\AdminTest::testGetFormNoErrors
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
-        'iconDocs' => null
+        'iconDocs' => ''
         'images' => Array ()
+        'imprintUrl' => null

/drone/src/github.com/nextcloud/server/apps/theming/tests/Settings/AdminTest.php:111

2) OCA\Theming\Tests\Settings\AdminTest::testGetFormWithErrors
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
+        'imprintUrl' => null

/drone/src/github.com/nextcloud/server/apps/theming/tests/Settings/AdminTest.php:160

3) OCA\Theming\Tests\Controller\ThemingControllerTest::testGetJavascript
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
+    		imprintUrl: null,\n

/drone/src/github.com/nextcloud/server/apps/theming/tests/Controller/ThemingControllerTest.php:825

4) OCA\Theming\Tests\Controller\ThemingControllerTest::testGetJavascriptInverted
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
+    		imprintUrl: null,\n

/drone/src/github.com/nextcloud/server/apps/theming/tests/Controller/ThemingControllerTest.php:859
```

2018-05-11 13:34 UTC, blizzz commented
@juliushaertl external sites did not come up to my mind, and i have not looked at it for ages… last time i hada glance, you could only insert a link. This looks more interesting now :) But getting this to work there needs to be wired with templates at least, if not theming (pre-/post-footer vs. general footer). And, as you say, cannot be just shipped to 13 out of its maintenance release.

2018-05-11 13:35 UTC, blizzz commented on apps/theming/templates/settings-admin.php
> +				<input id="theming-imprintUrl" type="url" placeholder="<?php p($l->t('Legal notice address https://…')); ?>" value="<?php p($_['imprintUrl']) ?>" maxlength="500" />
Same for web address then ^

2018-05-11 13:56 UTC, blizzz commented on apps/theming/templates/settings-admin.php
> +				<div data-setting="imprintUrl" data-toggle="tooltip" data-original-title="<?php p($l->t('Reset to default')); ?>" class="theme-undo icon icon-history"></div>
the key issue was missing CSS rules for url-input fields, undoing "web address" was also broken. fixed with a coming commit :)

2018-05-11 13:58 UTC, blizzz commented
I left  "address" instead calling it link to keep it consistent with the web url. otherwise, all remarks are addressed.

2018-05-14 13:24 UTC, juliusknorr approved these changes

2018-05-15 15:06 UTC, blizzz commented
@jancborchardt :ping_pong:

2018-05-15 20:16 UTC, jancborchardt commented on apps/theming/templates/settings-admin.php
> +				<span><?php p($l->t('Legal notice address')) ?></span>
We should change that one to »Website link« also. »Address« is just too ambiguous, especially for a legal notice. It might as well be the postal address of an imprint. (I know it says »https://…« but let’s make sure to use simple language.)

2018-05-15 20:17 UTC, jancborchardt commented
@blizzz see my follow-up comment to the wording link. Let’s change those, otherwise it’s fine. :)

2018-05-15 22:56 UTC, blizzz commented
@jancborchardt done

2018-05-17 19:15 UTC, rullzer approved these changes
LGTM

2018-05-17 19:16 UTC, merged