properly lock the target file on dav upload when not using part files
nextcloud/server pull request #9473
Opened 2018-05-14 14:28 UTC by icewind1991

While non-partfile storages don't have the file corruption problem on current read/writes (which is why I left this until now) not locking the target file during write can still lead to an inconsistent filecache state because the scanner is not being blocked.

2018-05-14 19:04 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/File.php
>  			}
No need for two ifs ;)

2018-05-15 10:17 UTC, MorrisJobke commented on apps/dav/lib/Connector/Sabre/File.php
>  			}
Why? IMO it makes sense to split it. 🤔

2018-05-15 12:00 UTC, icewind1991 commented on apps/dav/lib/Connector/Sabre/File.php
>  			}
fixed

2018-05-15 12:04 UTC, rullzer approved these changes
Makes sense!

2018-05-16 13:27 UTC, MorrisJobke approved these changes

2018-05-16 13:28 UTC, MorrisJobke commented
Unit tests fail. :/

2018-05-24 07:41 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/File.php
> +					$this->emitPreHooks($exists);
You ignore the result here now. So if the prehook returns false you should probably also fail right?

2018-06-11 12:51 UTC, MorrisJobke commented on apps/dav/lib/Connector/Sabre/File.php
> +					$this->emitPreHooks($exists);
See the unit tests, which fail now due to this.

2018-06-11 12:51 UTC, MorrisJobke requested changes
See unit tests and @rullzer's comment.

2018-06-11 13:49 UTC, icewind1991 commented
Fixed the unit test

2018-06-11 14:53 UTC, MorrisJobke approved these changes

2018-06-11 14:54 UTC, merged

2018-06-11 14:54 UTC, MorrisJobke commented
@icewind1991 Does a backport to 13 makes sense or should we skip it?

2018-06-11 15:22 UTC, icewind1991 commented
backport makes sense imo

2018-06-12 13:28 UTC, MorrisJobke commented
@icewind1991 Could you prepare the PR?