Get url for schedule email
nextcloud/server pull request #9537
Opened 2018-05-22 05:01 UTC by Peterede

I have added a hook to allow inserting a URL into the schedule email sent out from CalDav when a new event is created.  This allows adding the URL of a meeting room when creating a meeting in the calendar.

2018-05-22 08:00 UTC, rullzer commented
@georgehrke please have a look

2018-05-22 08:19 UTC, georgehrke requested changes

2018-05-22 08:19 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +        $event = new GenericEvent(null, [
Please use tabs instead of spaces

2018-05-22 08:19 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> -		$meetingUrl = $vevent->URL;
This is the URL coming straight from the ical data. Why do you override it?

2018-05-22 08:19 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +				throw new \InvalidArgumentException('meetingUrl may not be empty');
You could just use `if (empty()) { ... } else {$meetingUrl = $event->URL}`, no need to throw an exception :)

2018-05-22 08:19 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +	public function __construct(IConfig $config, IMailer $mailer, ILogger $logger, ITimeFactory $timeFactory, L10NFactory $l10nFactory, IURLGenerator $urlGenerator, Defaults $defaults, $userId, EventDis
Please add tests for your changes: https://github.com/nextcloud/server/blob/master/apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php

2018-05-22 23:47 UTC, Peterede commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> -		$meetingUrl = $vevent->URL;
I need to override it to create a URL to a landing page for the meeting and also to add a PIN specific for each user so that they can use the PIN to join the meeting.

2018-05-23 00:05 UTC, Peterede commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +	public function __construct(IConfig $config, IMailer $mailer, ILogger $logger, ITimeFactory $timeFactory, L10NFactory $l10nFactory, IURLGenerator $urlGenerator, Defaults $defaults, $userId, EventDis
I have updated the test construct

2018-05-23 06:18 UTC, georgehrke commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +	public function __construct(IConfig $config, IMailer $mailer, ILogger $logger, ITimeFactory $timeFactory, L10NFactory $l10nFactory, IURLGenerator $urlGenerator, Defaults $defaults, $userId, EventDis
Can you please add actual tests that make sure that the event is properly dispatched? :)

2018-05-24 00:33 UTC, Peterede commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +	public function __construct(IConfig $config, IMailer $mailer, ILogger $logger, ITimeFactory $timeFactory, L10NFactory $l10nFactory, IURLGenerator $urlGenerator, Defaults $defaults, $userId, EventDis
I have added tests to dispatch the event, can you please tell me if they are correct?

2018-06-01 00:09 UTC, Peterede commented on apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
> +	public function __construct(IConfig $config, IMailer $mailer, ILogger $logger, ITimeFactory $timeFactory, L10NFactory $l10nFactory, IURLGenerator $urlGenerator, Defaults $defaults, $userId, EventDis
I found a good example of a dispatch test in CalDavBackendTest.php, I have updated the test for you to check.

2018-07-02 08:10 UTC, juliushaertl commented
What's the status here? 

@Peterede It seems there are still some spaces instead of tabs in the code. Besides that is it ready for review?

2018-07-02 22:54 UTC, Peterede commented
I will close this pull request, I no longer need it.

2018-07-02 22:54 UTC, closed without merging