allow admins to disable FreeBusy without modifying ShareAPI capabilities
nextcloud/server pull request #9550
Opened 2018-05-22 17:19 UTC by georgehrke

@MorrisJobke @rullzer As discussed last week

2018-05-31 09:05 UTC, rullzer requested changes

2018-05-31 09:05 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Principal.php
> +		$disableFreeBusy = $this->config->getAppValue('dav', 'disableFreeBusy', $shareAPIEnabled ? 'no' : 'yes');
mmm I'm not sure this is the right place.

Basically not being able to find principals if sharing is totally disabled makes sense. But if free busy is disabled this will kill all sharing.

Can't we extend this class for calendars? overrwite only this function and then do the extra check? (as for now it is only needed for calendars right?).

2018-05-31 10:44 UTC, georgehrke commented on apps/dav/lib/Connector/Sabre/Principal.php
> +		$disableFreeBusy = $this->config->getAppValue('dav', 'disableFreeBusy', $shareAPIEnabled ? 'no' : 'yes');
Yes, it was only implemented for FreeBusy support: https://github.com/nextcloud/server/pull/6715/files#diff-60741cfe42a3d593d42e433595d64f22R206

2018-05-31 11:21 UTC, rullzer commented on apps/dav/lib/Connector/Sabre/Principal.php
> +		$disableFreeBusy = $this->config->getAppValue('dav', 'disableFreeBusy', $shareAPIEnabled ? 'no' : 'yes');
Ok then fine by me. If we ever want to extend this we have to the magic then!

2018-05-31 11:21 UTC, rullzer approved these changes

2018-05-31 15:45 UTC, MorrisJobke commented
Once I set the value to `yes` via `php occ config:app:set dav disableFreeBusy --value=yes` it does not change the entries of a shared calendar.

I have two users, A shares a calendar to B. User A adds 3 events: one shown, one shown as busy and one not shown to the share. For user B in both cases (with and without the setting) the entry marked to be shown as "Busy" is shown :/

2018-05-31 15:46 UTC, MorrisJobke commented
But also putting a debug breakpoint to the two code parts inside the `Principal` does not get triggered :/

2018-05-31 16:40 UTC, georgehrke commented
@MorrisJobke I updated the description.

2018-05-31 17:19 UTC, georgehrke commented
Backport to stable13: https://github.com/nextcloud/server/pull/9707

Backport to stable12 is not necessary, because Free/Busy was only introduced with stable13

2018-06-01 10:00 UTC, MorrisJobke approved these changes

2018-06-01 10:00 UTC, merged