Migrate apps management to Vue.js
nextcloud/server pull request #9565
Opened 2018-05-23 17:59 UTC by juliushaertl

This PR will move the apps management to vue, heavily based on the work done by @skjnldsv in #8824 

General improvements to the existing feature set:
- Implement sidebar with app details
- Add search across categories

## ToDo
- [x] Proper sorting for apps
- [ ] Show app details in the sidebar https://github.com/nextcloud/server/issues/2138 #3193 #2138
  - [ ] Add more details
  - [ ] Fix layout
- [x] Find an app by name https://github.com/nextcloud/server/issues/6868
- [x] Your apps does not show available updates https://github.com/nextcloud/server/issues/8703
- [ ] Add group assignment in sidebar
- [ ] Make buttons work in sidebar
- [ ] Add dev docs link to nav
- [ ] loading indicators for navigation, app lists, sidebar, screenshots
- [ ] Implement enabling/disabling of bundles
- [ ] Hide settings in navigation since we don't use it
- [ ] Implement views for when categories are empty
- [ ] Tooltips for buttons
- [ ] Properly display authors
- [ ] Make svg invert filter ids unique
- [ ] In between state for buttons (loading / disabling app...)
  - [ ] Fix updating multiple apps https://github.com/nextcloud/server/issues/7581
- [ ] Push error message to list view when enabling/disabling multiple apps
- [ ] Check server health after actions, check for update-required
- [ ] Rebuild navigation after enabling/disabling
- [ ] Check if starts should be used https://github.com/nextcloud/server/issues/3593
- [ ] Make categories enabled/disabled/update filters, to reduce request https://github.com/nextcloud/server/issues/3194

2018-05-24 05:26 UTC, skjnldsv commented
Weeeeeeee! Let me know if you need help!
I'll probably move the new components to the repo as soon as I can :)

2018-05-25 22:14 UTC, skjnldsv commented on settings/src/store/apps.js
> +	APPS_API_FAILURE(state, error) {
Any reason not to use the global API_Failure?

2018-05-30 15:19 UTC, juliushaertl commented on settings/src/store/apps.js
> +	APPS_API_FAILURE(state, error) {
I introduced this because the apps management controller endpoints are no OCS API at the moment, so the regular API_FAILURE will not work. I didn't move them to proper OCS since I wanted to keep backend code changes in the beginning. If nobody protests, i would tackle that in a follow up PR.

2018-05-30 19:50 UTC, rullzer commented on settings/src/store/apps.js
> +	APPS_API_FAILURE(state, error) {
Guess who will earn a beer in Berlin if he makes that happen ;) :beer:

2018-06-02 08:17 UTC, juliushaertl commented
Ready for review. @nextcloud/designers @nextcloud/javascript

2018-06-02 12:06 UTC, rullzer commented
* If I enable an app. The state is toggled in the sidebar. But not in the main view
* I like the list overview (with the details). But a lot of the thumbnails in the list are to small to be meaningfull
* For apps without a screenshot (and rating) the sidebar looks a bit off. Large space between the title and the author etc.

2018-06-02 12:07 UTC, rullzer requested changes

2018-06-02 12:07 UTC, rullzer commented on settings/src/components/appDetails.vue
> +			<a class="appslink" :href="appstoreUrl" v-if="!app.internal" target="_blank" rel="noreferrer noopener">Im Store anzeigen ↗</a>
Lets write that in English ;)
And make it translatatble

2018-06-04 06:21 UTC, ChristophWurst reviewed
Good stuff, but quite a big PR to review :see_no_evil: 

I commented on a few spots that might need polishing.

2018-06-04 06:21 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> +use OCP\IConfig;
the import on L35 is unused then, I guess :wink:

2018-06-04 06:21 UTC, ChristophWurst commented on lib/private/App/AppManager.php
> -		$appData = $this->getAppInfo($appId);
was this removed intentionally?

2018-06-04 06:21 UTC, ChristophWurst commented on lib/private/App/AppStore/Manager.php
> +		return $this->apps[$appId];
null checks, e.g. with `??` syntax would be great

2018-06-04 06:21 UTC, ChristophWurst commented on settings/Controller/AppSettingsController.php
> +		$this->fetchApps();
IMO this class should be split into multiple at some point. There's so much going on here and the code is quite hard to understand for me.

2018-06-04 06:21 UTC, ChristophWurst commented on settings/src/store/users.js
> +	getGroups(context) { /* { offset, limit, search } */
what do these comments mean?

2018-06-04 07:13 UTC, skjnldsv commented on settings/src/store/users.js
> +	getGroups(context) { /* { offset, limit, search } */
I think it's a removed ES6 destructuring part of the function that was set aside?

2018-06-05 15:49 UTC, juliushaertl commented on settings/Controller/AppSettingsController.php
> +		$this->fetchApps();
Toally with you on that. It will get a lot simpler once those methods are moved to proper OCS endpoints, but I'd do that in a follow up PR as mentioned in https://github.com/nextcloud/server/pull/9565#discussion_r191810501

2018-06-05 15:49 UTC, juliushaertl commented on lib/private/App/AppManager.php
> +use OCP\IConfig;
Right, removed :)

2018-06-05 15:56 UTC, skjnldsv commented on settings/src/store/apps.js
> +	APPS_API_FAILURE(state, error) {
SO many beers :D

2018-06-05 16:03 UTC, juliushaertl commented
> If I enable an app. The state is toggled in the sidebar. But not in the main view
@rullzer Cannot reproduce that. Can you provide some steps how and which enable button you have clicked?

> I like the list overview (with the details). But a lot of the thumbnails in the list are to small to be meaningfull

I've changed the behavior there, so we always show the app icon in the list view.

All other comments should be fixed.

2018-06-05 19:19 UTC, rullzer approved these changes
I like it!

Lets get this in. And fix tiny things later if we find them!

2018-06-05 19:19 UTC, rullzer commented
CI not happy

2018-06-06 12:40 UTC, juliushaertl commented
@rullzer Fixed the CI failures. :wink:

2018-06-06 16:04 UTC, MorrisJobke approved these changes
Tested and works :+1:

2018-06-06 16:05 UTC, merged

2018-06-06 16:07 UTC, skjnldsv commented
:tada: