Emit event when running ./occ db:add-missing-indices
nextcloud/server pull request #9576
Opened 2018-05-24 08:40 UTC by rullzer

This allows apps to listen to this event in order to also update
indecies there.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

2018-05-24 08:58 UTC, juliusknorr requested changes

2018-05-24 08:58 UTC, juliushaertl commented on core/Command/Db/AddMissingIndices.php
> +	public function __construct(IDBConnection $connection, EventDispatcherInterface $dispatcher) {
You're missing the assignment of `$dispatcher` to the private field.

2018-05-24 09:17 UTC, rullzer commented on core/Command/Db/AddMissingIndices.php
> +	public function __construct(IDBConnection $connection, EventDispatcherInterface $dispatcher) {
*look again*

2018-05-24 09:29 UTC, juliusknorr approved these changes

2018-05-24 10:39 UTC, MorrisJobke approved these changes
Works 👍

2018-05-24 16:01 UTC, MorrisJobke commented on lib/public/IDBConnection.php
> +	const ADD_MISSING_INDEXES_EVENT = this::class . '::ADD_MISSING_INDEXES';
```
lib/public/IDBConnection.php:49 PhanUndeclaredClassConstant Reference to constant class from undeclared class \OCP\this
```

2018-05-24 16:03 UTC, MorrisJobke commented on lib/public/IDBConnection.php
> +	const ADD_MISSING_INDEXES_EVENT = this::class . '::ADD_MISSING_INDEXES';
I fixed it by replacing the `this` with `self` 😉

2018-05-24 18:33 UTC, merged

2018-05-24 18:34 UTC, rullzer commented
Would a backport make sense? it is a small change but then apps can already add indexes for 13 apps.

2018-05-25 07:49 UTC, MorrisJobke commented
> Would a backport make sense? it is a small change but then apps can already add indexes for 13 apps.

I would say so.

2018-05-26 11:28 UTC, rullzer commented
backport in https://github.com/nextcloud/server/pull/9620