display whats new info in admin settings
nextcloud/server pull request #9705
Opened 2018-05-31 15:41 UTC by blizzz

contributes to #9163 by adding the what's new info to the admin notification

requires https://github.com/nextcloud/updater_server/pull/116

* [ ] fix the CSS

@skjnldsv as you suggested I copied the corresponding popovermenu components from settings. However I needed to adjust the item a little bit for external links (target and rel). If it makes sense I can also port this over to the original (and don't hard code rel). Tell me.

Otherwise, the CSS styles do not match the linkless formats, and there's still a bit left to do to make it look beautiful. Some styles I applied. Currently:

![screenshot_20180531_173814](https://user-images.githubusercontent.com/2184312/40792116-6654abba-64f9-11e8-92de-4283a6092afa.png)

So it definitely needs to get wider and perhaps some margins/paddings could get better. I cannot take over the styles completely from where it contains a link. Before i mess around more in the app, I guess it's better to get it back into apps.scss, too. 

Otherwise, first feedback @jancborchardt @skjnldsv ?

2018-06-01 09:59 UTC, blizzz commented
Testing steps:

1. git clone the updater server https://github.com/nextcloud/updater_server and checkout `feature/115/whatsnew`
2. perhaps `composer install`, i don't recall…
3. patch it's config file to ship the info we want (see patch below)
4. start the updater server locally `php -S localhost:8888 index.php`
5. configure you dev instance to use the local updater server, per ` 'updater.server.url' => 'http://localhost:8888/',` in config.php
6. patch you dev instance to require these info (doesn't work with git channel), see path below
7. in apps/updatenotification run `make build-js`
8. go to /settings/admin/overview

patch for 3)
```diff
diff --git a/config/config.php b/config/config.php
index 594fa1b..74307cf 100755
--- a/config/config.php
+++ b/config/config.php
@@ -208,6 +208,22 @@ ZH1PxQilL7ihAvnOb2oU1Q==',
        ],
    ],
    'stable' => [
+       '14' => [
+           '100' => [
+               'latest' => '14.0.0',
+               'internalVersion' => '14.0.0.5',
+               'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-14.0.0.zip',
+               'web' => 'https://docs.nextcloud.com/server/14/admin_manual/maintenance/upgrade.html',
+               'eol' => false,
+               'minPHPVersion' => '7.0',
+               'signature' => 'AG3egWHJkQaqCraVLiRq5Q7GvqArmBgVv8PNAfVYTOXPN6xWmw8cbUeBvBZ3OS1/
+bup1ktLDwTLDjWm1XMBUhhQCxVDLtEd3A6WfaVJz9BWoz1MyxUGlaIJSzTHLoEfz
+nFVUdoGH0mAdq8WtxRQSNwQWeKn+iF1jpbtIbDc29POtWvvzEgT/KW8MDzeidx6s
+W78tH4vldR0/aBn1D3hwnkQEQ8+Kz+Y4ItjHHi6XpJEfRQzYD0j9T+VTQ9IX4Xf/
+XqTrcaUCqwOlSC4pM7aUUzgaePPcYU2zrRDRaEgLma9eSkVMzkkc4kfM3izBG0Iv
+STb5hZFB2HMLyJxuj1l05w==',
+           ]
+       ],
        '13' => [
            '100' => [
                'latest' => '13.0.2',
```


patch for 6)
```diff
diff --git a/lib/private/Updater/VersionCheck.php b/lib/private/Updater/VersionCheck.php
index d34549f184..b4a28e8802 100644
--- a/lib/private/Updater/VersionCheck.php
+++ b/lib/private/Updater/VersionCheck.php
@@ -55,7 +55,7 @@ class VersionCheck {
     */
    public function check() {
        // Look up the cache - it is invalidated all 30 minutes
-       if (((int)$this->config->getAppValue('core', 'lastupdatedat') + 1800) > time()) {
+       if (false && ((int)$this->config->getAppValue('core', 'lastupdatedat') + 1800) > time()) {
            return json_decode($this->config->getAppValue('core', 'lastupdateResult'), true);
        }
 
@@ -70,7 +70,7 @@ class VersionCheck {
        $version = Util::getVersion();
        $version['installed'] = $this->config->getAppValue('core', 'installedat');
        $version['updated'] = $this->config->getAppValue('core', 'lastupdatedat');
-       $version['updatechannel'] = \OC_Util::getChannel();
+       $version['updatechannel'] = 'stable'; // \OC_Util::getChannel();
        $version['edition'] = '';
        $version['build'] = \OC_Util::getBuild();
        $version['php_major'] = PHP_MAJOR_VERSION;
```

2018-06-01 11:27 UTC, blizzz commented
> P.S.: actually, you don't need to setup the updater_server. Instead patch VersionCheck::check() to deliver what we would have gotten. The updater_server make sense to test that one as well.

In that case, forget steps 1-5, start with 6 using this patch:

```diff
diff --git a/lib/private/Updater/VersionCheck.php b/lib/private/Updater/VersionCheck.php
index d34549f184..5b258ad055 100644
--- a/lib/private/Updater/VersionCheck.php
+++ b/lib/private/Updater/VersionCheck.php
@@ -54,6 +54,21 @@ class VersionCheck {
     * @return array|bool
     */
    public function check() {
+       return [
+           'version' => '14.0.0.5',
+           'versionstring' => 'Nextcloud 14.0.0',
+           'url' => 'https://download.nextcloud.com/server/releases/nextcloud-14.0.0.zip',
+           'web' => 'https://docs.nextcloud.com/server/14/admin_manual/maintenance/upgrade.html',
+           'changelog' => 'https://nextcloud.com/changelog/#14-0-0',
+           'whatsNew' =>
+               array (
+                   0 => 'Pollute the files failing to update l n files for pdf',
+                   1 => 'Emaillogin server show open graph preview in gallery removed old code',
+                   2 => 'Server sharee email search server log exceptions that s settings server',
+               ),
+           'autoupdater' => '1',
+           'eol' => '0',
+       ];
        // Look up the cache - it is invalidated all 30 minutes
        if (((int)$this->config->getAppValue('core', 'lastupdatedat') + 1800) > time()) {
            return json_decode($this->config->getAppValue('core', 'lastupdateResult'), true);

```

2018-06-05 11:40 UTC, blizzz commented
I pushed some pixels and updated the screenshot in the description

2018-06-05 11:44 UTC, blizzz commented on apps/updatenotification/js-src/components/popoverMenu/popoverItem.vue
> +		<a @click="item.action" v-if="item.href" :href="(item.href) ? item.href : '#' " :target="(item.target) ? item.target : '' " rel="noreferrer noopener">
@skjnldsv this is copied from `settings/src/components/popoverMenu/popovermenuItem.vue` as suggested. I added `:target` and `rel`. What are your current plans of consolidating it? Would be good to not diverge already. should i port it back?

2018-06-05 11:45 UTC, blizzz commented on apps/updatenotification/js-src/components/popoverMenu/popoverItem.vue
> +		<span class="item-wrapper" v-else>
@skjnldsv and here I added that class, but that's probably stupid… 🤔

2018-06-05 12:34 UTC, skjnldsv commented on apps/updatenotification/js-src/components/popoverMenu/popoverItem.vue
> +		<span class="item-wrapper" v-else>
@blizzz why do you need this class?
Indeed, this should be standardised, not customed to the needs of a specific app. :)

2018-06-05 12:36 UTC, skjnldsv commented
I need to check again the css, I'm currently sick, so unfortunately not ready.
I'll take a look this afternoon, but like the other day, I couldn't get the notification to appear! :/

2018-06-05 14:38 UTC, blizzz commented
> I need to check again the css, I'm currently sick, so unfortunately not ready.
I'll take a look this afternoon, but like the other day, I couldn't get the notification to appear! :/

Get well soon and get well first!

2018-06-06 10:10 UTC, blizzz commented on apps/updatenotification/js-src/components/popoverMenu/popoverItem.vue
> +		<span class="item-wrapper" v-else>
css style was not applied, adding this case to apps.scss fixed it, and i could get rid of this class and some rules: https://github.com/nextcloud/server/pull/9705/commits/67ec8443cefd09acb1280b703591150994a8ae83

2018-06-07 14:26 UTC, skjnldsv requested changes

2018-06-07 14:32 UTC, skjnldsv approved these changes

2018-06-07 14:39 UTC, skjnldsv commented
CI is crying @blizz :)

2018-06-07 14:51 UTC, blizzz commented
yeah, we also had some discussions today, cf. https://github.com/nextcloud/updater_server/pull/116#issuecomment-395434051 f, so some things gonna change that need to be reflected on client side.

2018-06-07 15:04 UTC, blizzz commented on apps/updatenotification/js-src/app.js
> +/**
stray from rebase i guess

2018-06-18 23:06 UTC, blizzz commented
@skjnldsv i rebased, though all was good, psuhed, but now locally i see 

```
merged.js%20line%20774%20%3E%20eval:1:7

Error: Module build failed: Error: 

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.5.13

…

    at Object.<anonymous> (/srv/http/nextcloud/master/apps/notifications/node_modules/vue-template-compiler/index.js:8:9)
…


```

no matter how often i clean, npm install or update, removing the packages lock file, or make build-js things :( the merged.js is rebuilt an the package.json looks alright.

2018-06-19 04:16 UTC, skjnldsv commented
@blizzz You need to clean your dev environment then :) 
Just do a make is enough and will install&compile from scratch

2018-06-19 07:54 UTC, blizzz commented
> @blizzz You need to clean your dev environment then :)

@skjnldsv did it several times :(

2018-06-21 14:51 UTC, jancborchardt commented
Looks very nice! :) But we should just use a simple ul (just round bullet points) instead of the stars. As it’s a bit confusing since normally we use the star for favoriting and it’s interactive.

(Also @skjnldsv here’s another case of why the default of the popover should be to have it centered ;)

2018-06-21 14:58 UTC, skjnldsv commented
@jancborchardt 
![doit](https://media2.giphy.com/media/exQrMRVK2x9rW/giphy.gif)

2018-06-28 18:53 UTC, rullzer commented
I took the liberty to rebase.
If needed I still have the original branch backedup.

2018-06-28 20:51 UTC, blizzz commented on apps/updatenotification/lib/Settings/Admin.php
> +	protected function findWhatsNewTranslation(string $lang, array &$result, array $whatsNew): bool {
for the user facing stuff i need to move it somewhere else. in the moment i am not sure where, so it is here.

2018-06-28 20:58 UTC, blizzz commented on lib/public/L10N/IFactory.php
> +	public function iterateLanguage(bool $reset = false): string;
that'll need to be mentioned in the 14 changes thing

2018-06-29 06:41 UTC, MorrisJobke commented on core/Migrations/Version14000Date20180626223656.php
> +		if(!$schema->hasTable('whats_new')) {
The version.php needs to be raised to trigger this migration. And this should be added to the install routine as well. @rullzer @nickvergessen Or am I wrong?

2018-06-29 07:05 UTC, MorrisJobke commented on core/Migrations/Version14000Date20180626223656.php
> +		if(!$schema->hasTable('whats_new')) {
Version bump seems to be enough. Let me add it.

2018-06-29 07:08 UTC, MorrisJobke commented
Let me rebase to fix the conflict.

2018-06-29 07:12 UTC, MorrisJobke approved these changes
Works 👍 

Let's fix the style in a followup PR

![bildschirmfoto 2018-06-29 um 09 07 28](https://user-images.githubusercontent.com/245432/42078373-7c41d58a-7b7c-11e8-951e-fb690566a34e.png)

2018-06-29 08:10 UTC, blizzz commented on core/Migrations/Version14000Date20180626223656.php
> +		if(!$schema->hasTable('whats_new')) {
Right, thank you!

2018-06-29 08:36 UTC, merged

2018-06-29 08:37 UTC, MorrisJobke commented
> Let's fix the style in a followup PR

#10047