Menu entry clickability
nextcloud/server pull request #9752
Opened 2018-06-05 11:43 UTC by jancborchardt

Adjust to proper minimum 44px size (we need to take care that all elements have this minimum clickable size), please review @nextcloud/designers 
Also has more breathing space and looks less cramped now. :)

Before:
![before](https://user-images.githubusercontent.com/925062/40973930-459969c6-68c6-11e8-998a-2f7b873cdf26.png)

After:

![after](https://user-images.githubusercontent.com/925062/40973931-45cb0c7e-68c6-11e8-90eb-46052e486673.png)

2018-06-05 14:17 UTC, skjnldsv requested changes
Does not fit all the use cases of the popover menus.

![capture d ecran_2018-06-05_16-12-01](https://user-images.githubusercontent.com/14975046/40981436-384fe83e-68db-11e8-9341-e46dfe915c4c.png)

2018-06-05 14:17 UTC, skjnldsv commented on core/css/apps.scss
> +			padding: 3px 20px 3px 3px !important; /* for nice visual balance */
I'm not fan of using the important elements
Why is this needed?

2018-06-05 14:17 UTC, skjnldsv commented on core/css/apps.scss
> +			padding: 3px 20px 3px 3px !important; /* for nice visual balance */
Also, far too much padding on buttons
![capture d ecran_2018-06-05_16-14-18](https://user-images.githubusercontent.com/14975046/40981562-83a53a96-68db-11e8-953c-faa80fdc1cad.png)

2018-06-21 22:12 UTC, rullzer commented
Conflicts.

What is left here?

2018-06-22 15:03 UTC, jancborchardt commented on core/css/apps.scss
> +			padding: 3px 20px 3px 3px !important; /* for nice visual balance */
>  Also, far too much padding on buttons and other elements :)

No? 44px is correct minimum height, and the padding on the right is so it’s nicely balanced with the left where the icon is.

2018-06-22 15:07 UTC, jancborchardt commented
> Does not fit all the use cases of the popover menus.

@skjnldsv this doesn’t happen in any app, no?

I would say let’s merge this, and the small discrepancies we can fix in a follow-up.

@rullzer it’s rebased on master. :)

2018-06-22 15:16 UTC, skjnldsv commented on core/css/apps.scss
> +			padding: 3px 20px 3px 3px !important; /* for nice visual balance */
I thought it was a mistake. It looks nice visually yes :)
Do you remember why you needed the `important` though?
I would prefer if we removed them! ;)

2018-06-22 15:17 UTC, skjnldsv commented
> I would say let’s merge this, and the small discrepancies we can fix in a follow-up.

I disagree, I worked hard to fit all those different options in the popover, please don't break them ;)

2018-06-22 22:42 UTC, jancborchardt commented
@skjnldsv right – will see to fix this :)

2018-07-24 13:40 UTC, MorrisJobke commented
> @jancborchardt Any news on this one?

Ping ... or we need to move this to 15.

2018-08-08 07:34 UTC, pixelipo commented on core/css/apps.scss
> +			padding: 3px 20px 3px 3px !important; /* for nice visual balance */
I agree with @skjnldsv regarding the `!important` tag - might be a good idea to check why is it actually needed here. Perhaps this rule should be applied higher "upstream"?

2018-08-20 15:10 UTC, MorrisJobke commented
15 it is then.

2018-08-25 13:53 UTC, AnonymousPolarbearFan commented
Did we make any progress here? I would really appreciate this feature. 👍

2018-11-07 14:45 UTC, MorrisJobke commented
I guess we need to move this to 16 😢

2019-01-28 17:13 UTC, MorrisJobke commented
#12785 will fix the this in another way - thus closing this one here.

2019-01-28 17:13 UTC, closed without merging