Svg color api
nextcloud/server pull request #9984
Opened 2018-06-25 09:20 UTC by skjnldsv

This create a new endpoint to get one of our svg and change the colour.
This will allow us to:
- Only maintain black svg
- Only maintain one set of icon
- Allow us not to use any filter to invert icons: ie11 compatibility and better handling of background images

2018-06-25 09:33 UTC, MorrisJobke commented on core/Controller/SvgController.php
> +		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
This then needs to be redone for all the other icon locations :/

2018-06-25 09:37 UTC, skjnldsv commented on core/Controller/SvgController.php
> +		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
Yeah, it was a first shot, I'm asking for feedback on how to tackle this :)
> how do you think we should handle custom paths? Right now I implemented this for the actions folder only, but in the end we'll probably need this for the apps menu and other stuff.

2018-06-25 09:37 UTC, MorrisJobke commented on core/Controller/SvgController.php
> +		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
On the other side I'm fine with doing it like this for now and test it.

2018-06-26 07:44 UTC, skjnldsv commented on core/Controller/SvgController.php
> +		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
@rullzer though we'll need to access icons in apps, so I guess I will add a new endpoint for apps icons

2018-06-26 07:55 UTC, rullzer commented on core/Controller/SvgController.php
> +		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
Sure but like I said. Small endpoints beat complex ones. so :rocket:

2018-06-26 08:21 UTC, juliushaertl commented
> how do you think we should handle custom paths? Right now I implemented this for the actions folder only, but in the end we'll probably need this for the apps menu and other stuff.

I think we can add another endpoint that is a bit more generic, so it works for other apps with different icon paths as well. We do have such a route in the theming app already: https://github.com/nextcloud/server/blob/master/apps/theming/appinfo/routes.php#L80-L84

2018-06-29 07:15 UTC, juliushaertl commented on core/Controller/SvgController.php
> +		$response->addHeader('Cache-Control', 'max-age=' . $ttl . ', immutable');
Use $response->cacheFor() https://docs.nextcloud.com/server/13/developer_manual/api/OCP/AppFramework/Http/Response.html#OCP\AppFramework\Http\Response::cacheFor

2018-06-29 07:17 UTC, juliushaertl commented
> I've added a new /svg/app/icon/color path :)

@skjnldsv I cannot find it, maybe you forgot to push? :wink:

2018-06-29 07:20 UTC, skjnldsv commented
> @skjnldsv I cannot find it, maybe you forgot to push? wink

😅😅

2018-06-29 14:54 UTC, MorrisJobke approved these changes
I like it 👍

2018-06-29 14:59 UTC, skjnldsv commented
@MorrisJobke still some fixes to do :)
- [ ] Find a way to recompile the icons on accessibility theme update
- [ ] Fix tests

2018-07-03 13:04 UTC, juliushaertl commented on lib/private/Template/IconsCacher.php
> +			$data .= "--$icon: url('$url?v=1');";
Is there a reason that the v=1 is appended here and not at the css level? I think that could lead to icons not being reloaded if they are changed.

2018-07-03 13:05 UTC, skjnldsv commented on lib/private/Template/IconsCacher.php
> +			$data .= "--$icon: url('$url?v=1');";
I have no idea, they were always like that, so I didn't give it a lot of thought :)

2018-07-03 13:12 UTC, juliushaertl commented on lib/private/Template/IconsCacher.php
> +			$data .= "--$icon: url('$url?v=1');";
I mean usually we have it inside of the css file, which is fine, since then it can be bumped once the icon file is changed, and the browsers can detect that they should load the file again.

2018-07-03 13:16 UTC, skjnldsv commented on lib/private/Template/IconsCacher.php
> +			$data .= "--$icon: url('$url?v=1');";
We should probably remove all of those ?v=1 then

2018-07-03 18:31 UTC, rullzer commented on lib/private/Template/IconsCacher.php
> +			$data .= "--$icon: url('$url?v=1');";
Probably yes.

2018-07-04 09:28 UTC, skjnldsv commented
Okay, that's how I proceed:
I added a mixin for our scss which automatically handle the svg colour api
``` scss
.icon-screen-off {
	@include icon-color('screen-off', 'actions', $color-black, true);
}
```

Basically you just need to add this to your css and the background-image will be automatically added to a variable. The Mixin works that way:
``` scss
/**
 * SVG COLOR API
 * 
 * @param string $icon the icon filename
 * @param string $dir the icon folder within /core/img if $core or app name
 * @param string $color the desired color in hexadecimal
 * @param bool [$core] search icon in core
 *
 * @returns string the url to the svg api endpoint
 */
@mixin icon-color($icon, $dir, $color, $core: false)
```

Then, every time the scss is compiled, the system will detect if an icon is used via this mixin and export it to a new css file called icons-vars.css (cached into the appdata)
The accessibility on dark theme automatically parse the icons-vars file and invert the proper colors from fff->000 and 000->fff (we don't reverse any other colours)


@nextcloud/designers what are your thoughts? Is this a good behavior?
@MorrisJobke @jancborchardt @juliushaertl @rullzer

2018-07-05 09:04 UTC, skjnldsv commented
I don't get the phan failure, can someone help?

```
+ ./lib/composer/phan/phan/phan -k build/.phan/config.php
lib/private/Log/Systemdlog.php:74 PhanUndeclaredFunction Call to undeclared function \sd_journal_send()
```

2018-07-05 09:05 UTC, nickvergessen commented
Just needs a rebase.

2018-07-05 09:36 UTC, skjnldsv commented
Failure unrelated!
Please review @nextcloud/designers

2018-07-05 17:31 UTC, juliushaertl commented on core/css/functions.scss
> +		#{$varName}: url('#{$webroot}/svg/core/#{$dir}/#{$icon}/#{$color}?v=1');
Shouldn't we have another parameter in the mixin for this so app developers can bump the number if they change the icons?

2018-07-05 21:11 UTC, skjnldsv commented on core/css/functions.scss
> +		#{$varName}: url('#{$webroot}/svg/core/#{$dir}/#{$icon}/#{$color}?v=1');
@juliushaertl I guess we could :)
Currently no one seems to use the version increment :/

2018-07-06 16:23 UTC, juliushaertl commented on core/css/functions.scss
> +		#{$varName}: url('#{$webroot}/svg/core/#{$dir}/#{$icon}/#{$color}?v=1');
At least for the core CSS we have some:

```
core/css/styles.scss
98:	background-image: url('../img/background.png?v=2');

core/css/inputs.scss
245:				background-image: url('../img/actions/confirm-fade.svg?v=2') !important;

core/css/variables.scss
39:$image-login-background: url('../img/background.png?v=2');

core/css/icons.scss
119:	background-image: url('../img/actions/audio.svg?v=2');
154:	background-image: url('../img/actions/clippy.svg?v=2');
170:	background-image: url('../img/actions/confirm.svg?v=2');
174:	background-image: url('../img/actions/confirm-fade.svg?v=2');
178:	background-image: url('../img/actions/confirm-white.svg?v=2');
451:	background-image: url('../img/actions/video.svg?v=2');

core/css/guest.css
26:	background-image: url('../img/background.png?v=2');
632:	background-image: url('../img/actions/info-white.svg?v=2');
635:	background-image: url('../img/actions/confirm.svg?v=2');
638:	background-image: url('../img/actions/confirm-white.svg?v=2');
```

Also from my understanding we have no option to force reloading icons otherwise if they change.

2018-07-10 13:55 UTC, juliushaertl commented
@skjnldsv Seems to have an issue with the index.php prefix again:

```
http://localhost:8140/svg/core/actions/timezone/000?v=1 404 (Not Found)
```

2018-07-10 14:05 UTC, skjnldsv commented
@juliushaertl strange, the webroot should be applied here: 
https://github.com/nextcloud/server/pull/9984/files#diff-3a9a30c772db7b84e90a0d119b278f94R43
https://github.com/nextcloud/server/pull/9984/files#diff-dc68e93a3894ea57d470448bd3fd66e3R260

2018-07-10 16:00 UTC, juliushaertl commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
Can we get rid of this invert rule as well?

2018-07-10 16:07 UTC, skjnldsv commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
No, header needs to use the proper urls
Or we need to exclude the variable invert for the header icons :)

2018-07-10 17:12 UTC, juliushaertl commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
Yes, I'd say we should exclude those. Their color anyway depends on the theming app color so we should keep that and not invert it.

2018-07-10 17:14 UTC, skjnldsv commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
Hum, since we're changing the global variables, I'm not sure we can ignore them :/

2018-07-10 18:13 UTC, juliushaertl commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
How about just setting the icon for the header with $color-primary-text instead of $color-white? Then they should not be inverted, if I get the code right.

2018-07-10 18:15 UTC, juliushaertl commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
So we would have the regular .icon-contacts with $color-white and a header .icon-contacts with $color-primary-text. Yes this will be some duplication, but the icons where this is used are quite limited, so it would be ok i think.

2018-07-10 19:01 UTC, skjnldsv commented on apps/accessibility/css/themedark.scss
> +		filter: invert(100%);
@juliushaertl Of course!!! Great thinking! :+1: :hugs:

2018-07-12 19:20 UTC, rullzer commented
What is left to do here?

2018-07-12 20:54 UTC, skjnldsv commented
@rullzer one small fix for the header :)
You can review still, everything works

2018-07-13 11:10 UTC, skjnldsv commented
@juliushaertl yeah, it's a tricky part.
I cannot use the variables name in scss unless we go for scss maps.
So I cannot differentiate variables that are using the $primary or $white colour since in the end, both of them will be ffffff. 
Not sure if I'm being clear :p

2018-07-18 17:08 UTC, juliushaertl commented
@skjnldsv I've pushed two other minor fixes. I'd say we should get this in and maybe handle the inverted other icons later. This is anyway just an issue for IE11 in combination for accessibility. For everything else this fixes the issue of inverting background images and makes it much easier to keep various colors of the icons without storing them individually. So it would be good from my side now.

cc @nextcloud/accessibility @nextcloud/designers

2018-07-18 17:12 UTC, juliushaertl commented
- [ ] We need to fix other apps like activity, since some use `IURLGenerator->imagePath('core', 'places/contacts-dark.svg');` which is not available anymore after this PR.

2018-07-18 20:52 UTC, rullzer commented
Conflicts.

2018-07-19 06:17 UTC, juliushaertl commented
@rullzer Rebased.

2018-07-19 17:34 UTC, MorrisJobke requested changes
Unit tests fail:


```

1) Test\Template\SCSSCacherTest::testProcessUncachedFileNoAppDataFolder

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:127
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:143

2) Test\Template\SCSSCacherTest::testProcessUncachedFile

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:167
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:179

3) Test\Template\SCSSCacherTest::testProcessCachedFile

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:203
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:210

4) Test\Template\SCSSCacherTest::testProcessCachedFileMemcache

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:242
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:249

5) Test\Template\SCSSCacherTest::testGetCachedSCSS with data set #0 ('core', 'core/css/styles.scss', '/css/core/styles.css', '14.0.0 alpha')
Expectation failed for method name is equal to "linkToRoute" when invoked 1 time(s)
Parameter 1 for invocation OCP\IURLGenerator::linkToRoute('core.Css.getCss', Array (...)): string does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'fileName' => '77d8-8422-styles.css'
+    'fileName' => '77d8-0ab8-styles.css'

/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:365
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:454

6) Test\Template\SCSSCacherTest::testGetCachedSCSS with data set #1 ('files', 'apps/files/css/styles.scss', '/css/files/styles.css', '1.9.0')
Expectation failed for method name is equal to "linkToRoute" when invoked 1 time(s)
Parameter 1 for invocation OCP\IURLGenerator::linkToRoute('core.Css.getCss', Array (...)): string does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'fileName' => 'd16b-8422-styles.css'
+    'fileName' => 'd16b-0ab8-styles.css'

/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:365
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:454
```

2018-07-19 17:44 UTC, rullzer submitted a review, later dismissed

2018-07-19 17:44 UTC, rullzer commented on core/Controller/SvgController.php
> +	 * @return DataDisplayResponse|NotFoundException
You don't return an exception you throw it ;)

2018-07-19 17:44 UTC, rullzer commented on core/Controller/SvgController.php
> +	public function getSvgFromCore(string $folder, string $fileName, string $color = 'ffffff') {
You can also declare return types ;)

2018-07-19 17:44 UTC, rullzer commented on core/Controller/SvgController.php
> +	 * @return DataDisplayResponse|NotFoundException
NotFoundResponse it seems

2018-07-19 17:44 UTC, rullzer commented on core/Controller/SvgController.php
> +		$appPath = \OC_App::getAppWebPath($app);
Can't the appmanager do this?

2018-07-19 17:44 UTC, rullzer commented on lib/private/Template/IconsCacher.php
> +/**
strict

2018-07-19 17:44 UTC, rullzer commented on tests/lib/Template/IconsCacherTest.php
> +/**
strict

2018-07-19 21:19 UTC, rullzer approved these changes
Lets do this. :guitar:

2018-07-19 21:53 UTC, MorrisJobke approved these changes

2018-07-19 21:54 UTC, merged

2018-07-21 14:10 UTC, skjnldsv commented on lib/private/Template/IconsCacher.php
> +	private $iconVarRE = '/--(icon-[a-z0-9-]+): url\(["\']([a-z0-9-_\~\/\?\&\=\.]+)[^;]+;/m';
@juliushaertl some of the icons are broken because of your last edit.
We shoudl exclude the ?v= from the matches because otherwise it gets re-added on every compile and we get stuff like that: --icon-confirm-fade-000: url('/svg/core/actions/confirm-fade/000?v=2?v=1?v=1?v=1?v=1');

Was there a specific reason? Or can I remove the ?=& from the regex? :)

2018-07-21 15:19 UTC, juliushaertl commented on lib/private/Template/IconsCacher.php
> +	private $iconVarRE = '/--(icon-[a-z0-9-]+): url\(["\']([a-z0-9-_\~\/\?\&\=\.]+)[^;]+;/m';
No, your right, we can remove those. The others might be needed depending on the base URL of the nextcloud installation.

2018-07-21 15:20 UTC, skjnldsv commented on lib/private/Template/IconsCacher.php
> +	private $iconVarRE = '/--(icon-[a-z0-9-]+): url\(["\']([a-z0-9-_\~\/\?\&\=\.]+)[^;]+;/m';
Weeee :balloon:

2018-07-30 09:33 UTC, nickvergessen commented on core/css/icons.scss
> +	filter: drop-shadow(1px 1px 4px var(--color-box-shadow));
Is there a bigger reason the `invert(100%)` was removed? this breaks the icons on the Talk UI, because now the white icon has a white shadow on a white background while you are waiting for a participant to join the call

2018-07-30 09:39 UTC, juliushaertl commented on core/css/icons.scss
> +	filter: drop-shadow(1px 1px 4px var(--color-box-shadow));
Invert is not available in IE11 (see #8702)

@skjnldsv Do you have an idea why the shadow would be white? The drop shadow should not be changed, right?

2018-07-30 09:44 UTC, skjnldsv commented
The shadow? you mean `drop-shadow`?
It should not be touched.

@nickvergessen are you using the proper new css class? `icon-video`

2018-10-08 13:21 UTC, MorrisJobke commented
This causes high load on Safari: #11179

😢